### ISSUE TITLE
Cannot disable touchpad

### ISSUE THREAD

**Issue by Bob-May** [linuxmint/cinnamon#10009]
```
 * Cinnamon version (4.8.6+ulyssa)

 * Distribution - (Mint 20.1)


 ```

**Issue**
Mouse and Touchpad controls  "Disable Touchpad when a mouse is attached" and "Enable touchpad" have no effect.

Touchpad remains enables regardless of settings. 

I've tried with both the default libinput driver and the synaptics driver. Same result.

**Steps to reproduce**
Toggle each setting.

**Expected behaviour**
Touchpad respects the settings.

**Other information**
`System:    Kernel: 5.4.0-70-generic x86_64 bits: 64 compiler: gcc v: 9.3.0 Desktop: Cinnamon 4.8.6 wm: muffin 4.8.1 
           dm: LightDM 1.30.0 Distro: Linux Mint 20.1 Ulyssa base: Ubuntu 20.04 focal 
Machine:   Type: Laptop System: Dell product: Inspiron 3780 v: N/A serial: <filter> Chassis: type: 10 serial: <filter> 
           Mobo: Dell model: 04HHXR v: A00 serial: <filter> UEFI: Dell v: 1.4.1 date: 03/20/2019 
Battery:   ID-1: BAT0 charge: 38.0 Wh condition: 38.0/42.0 Wh (90%) volts: 13.0/11.4 model: SMP DELL VM73283 type: Li-poly 
           serial: <filter> status: Full 
CPU:       Topology: Quad Core model: Intel Core i5-8265U bits: 64 type: MT MCP arch: Kaby Lake rev: C L2 cache: 6144 KiB 
           flags: avx avx2 lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx bogomips: 28800 
           Speed: 711 MHz min/max: 400/3900 MHz Core speeds (MHz): 1: 800 2: 775 3: 748 4: 797 5: 800 6: 799 7: 794 8: 798 
Graphics:  Device-1: Intel UHD Graphics 620 vendor: Dell driver: i915 v: kernel bus ID: 00:02.0 chip ID: 8086:3ea0 
           Display: x11 server: X.Org 1.20.9 driver: modesetting unloaded: fbdev,vesa 
           resolution: 1920x1080~60Hz, 1920x1080~60Hz 
           OpenGL: renderer: Mesa Intel UHD Graphics 620 (WHL GT2) v: 4.6 Mesa 20.2.6 direct render: Yes 
Audio:     Device-1: Intel Cannon Point-LP High Definition Audio vendor: Dell driver: snd_hda_intel v: kernel bus ID: 00:1f.3 
           chip ID: 8086:9dc8 
           Sound Server: ALSA v: k5.4.0-70-generic 
Network:   Device-1: Realtek RTL810xE PCI Express Fast Ethernet vendor: Dell driver: r8169 v: kernel port: 3000 
           bus ID: 01:00.0 chip ID: 10ec:8136 
           IF: enp1s0 state: down mac: <filter> 
           Device-2: Qualcomm Atheros QCA9377 802.11ac Wireless Network Adapter vendor: Dell driver: ath10k_pci v: kernel 
           port: 3000 bus ID: 02:00.0 chip ID: 168c:0042 
           IF: wlp2s0 state: up mac: <filter> 
           Device-3: Qualcomm Atheros type: USB driver: btusb bus ID: 1-10:4 chip ID: 0cf3:e009 
Drives:    Local Storage: total: 931.51 GiB used: 74.67 GiB (8.0%) 
           ID-1: /dev/sda vendor: Toshiba model: MQ04ABF100 size: 931.51 GiB speed: 6.0 Gb/s rotation: 5400 rpm 
           serial: <filter> rev: 0D scheme: GPT 
RAID:      Hardware-1: Intel 82801 Mobile SATA Controller [RAID mode] driver: ahci v: 3.0 port: 4060 bus ID: 00:17.0 
           chip ID: 8086.282a rev: 30 
Partition: ID-1: / size: 316.21 GiB used: 24.77 GiB (7.8%) fs: ext4 dev: /dev/sda8 
Sensors:   System Temperatures: cpu: 50.0 C mobo: N/A 
           Fan Speeds (RPM): cpu: 0 
Repos:     No active apt repos in: /etc/apt/sources.list 
           Active apt repos in: /etc/apt/sources.list.d/google-chrome.list 
           1: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
           Active apt repos in: /etc/apt/sources.list.d/nodesource.list 
           1: deb https://deb.nodesource.com/node_15.x focal main
           2: deb-src https://deb.nodesource.com/node_15.x focal main
           Active apt repos in: /etc/apt/sources.list.d/official-package-repositories.list 
           1: deb http://mirrors.seas.harvard.edu/linuxmint-packages ulyssa main upstream import backport
           2: deb http://la-mirrors.evowise.com/ubuntu focal main restricted universe multiverse
           3: deb http://la-mirrors.evowise.com/ubuntu focal-updates main restricted universe multiverse
           4: deb http://la-mirrors.evowise.com/ubuntu focal-backports main restricted universe multiverse
           5: deb http://security.ubuntu.com/ubuntu/ focal-security main restricted universe multiverse
           6: deb http://archive.canonical.com/ubuntu/ focal partner
           Active apt repos in: /etc/apt/sources.list.d/packagecloud-shiftky-desktop.list 
           1: deb [arch=amd64] https://packagecloud.io/shiftkey/desktop/any/ any main
           Active apt repos in: /etc/apt/sources.list.d/vscode.list 
           1: deb [arch=amd64,arm64,armhf] http://packages.microsoft.com/repos/code stable main
Info:      Processes: 256 Uptime: 50m Memory: 15.52 GiB used: 2.09 GiB (13.5%) Init: systemd v: 245 runlevel: 5 Compilers: 
           gcc: 9.3.0 alt: 9 Shell: bash v: 5.0.17 running in: gnome-terminal inxi: 3.0.38 `

```

**Comment by icarter09** [comment]
Cinnamon 4.8.6
Mint 20.1 64bit

I'm not able to reproduce this issue. Both settings work as expected.
