### ISSUE TITLE
Screen brightness values locked (won't change). 

### ISSUE THREAD

**Issue by jayypluss** [linuxmint/cinnamon#10003]
```
OS: Arch Linux x86_64 
Host: Inspiron 5537 A12 
Kernel: 5.11.8-arch1-1 
Uptime: 11 mins 
Packages: 664 (pacman) 
Shell: zsh 5.8 
Resolution: 1366x768, 1920x1080 
DE: Cinnamon 4.8.6 
WM: Mutter (Muffin) 
WM Theme: Numix-Cinnamon-Transparent (Arc) 
Theme: Arc [GTK2/3] 
Icons: Flat-Remix-Violet [GTK2/3] 
Terminal: tilix 
CPU: Intel i7-4500U (4) @ 3.000GHz 
GPU: AMD ATI Radeon HD 8850M / R9 M265X 
GPU: Intel Haswell-ULT 
Memory: 2047MiB / 15887MiB
 ```

**Issue**

Screen brightness values locked (won't change). 
When I change the values using the keyboard shortcut they are locked on 63% or 73%. 
When I try and change the values from the "Power Management" configurations bar, the value immediately goes back to where it was before.
I noticed it's something like https://github.com/linuxmint/cinnamon/issues/2219.

**Steps to reproduce**

Try and change screen brightness either from keyboard shortcut, fn+ function or Power Management configs. 

![Peek 2021-03-26 07-50](https://user-images.githubusercontent.com/17395606/112621113-249bb980-8e08-11eb-86c7-e7e387fa8c79.gif)

**Comment by icarter09** [comment]
Cinnamon 4.8.6
Mint 20.1 64bit

I'm not able to reproduce this issue. Using the keyboard shortcut of `Fn key + brightness +/-` changes the screen brightness on the Power Management window. The Power Management config bar also does not immediately go back to its previous value.
