### ISSUE TITLE
Network Manager applet - wireless network list settings

### ISSUE THREAD

**Issue by boughtonp** [linuxmint/cinnamon#10001]
When I'm connected to a wireless network, I don't care about other wireless networks I'm not connected to.

The network manager applet currently has no way of preventing this information being output, so I cloned it and added some settings.

First I changed the NUM_VISIBLE_NETWORKS constant (which controls how many networks to show before putting the rest in "More") to a setting (spinbutton) - this allowed a min value of 1 resulting in non-active networks going into the "More" menu instead, which was ok but still not quite what I wanted.

So I also added a boolean setting so that - when a wireless connection is active - no other wireless networks display (not even a more menu), but if the connection isn't active then it displays as normal.

Default settings are same as current behaviour - i.e. anyone who doesn't configure the applet will not see any difference.

Tested on Cinnamon 4.8.6 (Debian Testing) and it works for me, but I expect there's a better way of doing the settings than I used.

Assuming you agree with the idea, should I go ahead and raise a pull request against master, or use a different branch?

**Comment by icarter09** [comment]
@boughtonp create a PR against the master branch. Thanks.
