### ISSUE TITLE
You 1 vote against Stallman so Cinnamon is shit use https://ubuntucinnamon.org

### ISSUE THREAD

**Issue by ghost** [linuxmint/cinnamon#10016]
You 1 vote against Stallman so Cinnamon is shit use https://ubuntucinnamon.org

**Comment by ItzSwirlz** [comment]
i find it funny how i'm actually the ubuntu cinnamon developer and you hate me too

**Comment by mtwebster** [comment]
Will you PLEASE stop responding to this garbage - they don't care, they're not interested in discussion, it's a troll. Yes we know 'ghost' is a deleted user.
