### ISSUE TITLE
Start menu should close without eating the mouse action outside of its area

### ISSUE THREAD

**Issue by eandmsz** [linuxmint/cinnamon#10021]
* Cinnamon version (cinnamon --version)
Cinnamon 4.8.6
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
Linux Mint 20.1
64 bit
 * Graphics hardware *and* driver used
NVIDIA 1070 GTX with NVIDIA driver: 460.39

**Issue**
When the start menu is open, it's not possible to move or resize (or interact in any way) with an already opened window, as the mouse click outside of the start menu will first close the start menu, and then the user needs to click again to interact with the window.

**Steps to reproduce**
Open any program: for example file manager "Nemo"
Click on the start menu to open it
Try to grab the Nemo window by dragging its header

**Expected behaviour**
The start menu should close when mouse is clicked outside of its area, but that same mouse click should also have effect on the window where it was clicked.

**Comment by leigh123linux** [comment]
There are at lease a dozen similar reports, we don't need another one.
