### ISSUE TITLE
Using two or more Flatpak applications, only the first started one will display its tray icon

### ISSUE THREAD

**Issue by qwertfisch** [linuxmint/cinnamon#10033]
```
 * Cinnamon version: 4.8.6
   - no daily builds PPA
 * Distribution: Mint 20.1
 * 64 bit
 ```

**Issue**

When starting two applications, which were installed in a Flatpak version, their tray icons cannot be displayed both at the same time. The applications are both running in the background, but only the first started will display its icon in the tray area of Cinnamon taskbar and can be interacted that way. The tray icon of the application started as second (or of any subsequently started Flatpak app) will not be displayed.

As soon as I close the first application and its icon is removed from tray, the next started Flatpak application __will__ display its tray icon.

**Steps to reproduce**

I installed KeepassXC as well as Nextcloud desktop-client both as the Flatpak version via the Mint application manager. I started KeepassXC from the start menu, then Nextcloud.

**Expected behaviour**

Both applications should display an additional icon in the tray area. KeepassXC also displays (as default) a taskbar icon, whereas Nextcloud only interacts via tray icon with the user.

**Actual behaviour**
The tray icon of KeepassXC is visible, the tray icon of Nextcloud will not be displayed. I cannot interact with Nextcloud, only on startup when it opens the application menu _once_.

**Logfiles**
The xsession-errors lists the following:
```
Cjs-Message: 18:00:04.049: JS LOG: [LookingGlass/info] Adding XAppStatusIcon: org.kde.statusnotifieritem-2-1 (:1.46/org/x/StatusIcon/Icon)

(caribou:1430): dbind-WARNING **: 18:00:04.574: AT-SPI: Unable to open bus connection: Failed to connect to socket /run/user/1000/at-spi2-17P300/socket: Datei oder Verzeichnis nicht gefunden

(xapp-sn-watcher:1418): Gtk-CRITICAL **: 18:00:04.579: gtk_widget_set_accel_path: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed

(xapp-sn-watcher:1418): Gtk-CRITICAL **: 18:00:04.579: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed

(xapp-sn-watcher:1418): Gtk-CRITICAL **: 18:00:04.581: gtk_widget_set_accel_path: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed

(xapp-sn-watcher:1418): Gtk-CRITICAL **: 18:00:04.581: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
Cinnamon warning: Invalid WM_TRANSIENT_FOR window 0x6e00016 specified for 0x6e00014 (Nextcloud).

(caribou:1430): dbind-WARNING **: 18:00:16.840: AT-SPI: Unable to open bus connection: Failed to connect to socket /run/user/1000/at-spi2-4X8800/socket: Datei oder Verzeichnis nicht gefunden
```

The /var/log/syslog shows these messages:
```
Apr  5 18:00:01 shuttle CRON[3404]: (root) CMD (timeshift --check --scripted)
Apr  5 18:00:01 shuttle crontab[3439]: (root) LIST (root)
Apr  5 18:00:01 shuttle crontab[3440]: (root) LIST (root)
Apr  5 18:00:03 shuttle systemd[1118]: Started flatpak-org.keepassxc.KeePassXC-3443.scope.
Apr  5 18:00:16 shuttle systemd[1118]: Started flatpak-com.nextcloud.desktopclient.nextcloud-3472.scope.
Apr  5 18:00:22 shuttle dbus-daemon[550]: [system] Activating via systemd: service name='org.freedesktop.hostname1' unit='dbus-org.freedesktop.hostname1.service' requested by ':1.123' (uid=1000 pid=2894 comm="/usr/bin/gedit --gapplication-service " label="unconfined")
Apr  5 18:00:22 shuttle systemd[1]: Starting Hostname Service...
Apr  5 18:00:22 shuttle dbus-daemon[550]: [system] Successfully activated service 'org.freedesktop.hostname1'
Apr  5 18:00:22 shuttle systemd[1]: Started Hostname Service.
Apr  5 18:00:52 shuttle systemd[1]: systemd-hostnamed.service: Succeeded.
```

**Comment by leigh123linux** [comment]
Feel free to reopen if you can reproduce the issue without nextcloud, it's known to have a buggy tray icon.

https://github.com/linuxmint/cinnamon/search?q=Nextcloud&type=issues

**Comment by mtwebster** [comment]
This isn't really related to other previous issues..

It looks like they're both attempting to register the same 'name': org.kde.StatusNotifierItem-2-1, and only a single owner is allowed at a time. I can find a lot of related issues with google - this is probably caused by the 'xdg-dbus-proxy' which I think is used to allow sandboxed applications to communicate with the rest of the session.

The only workaround I can come up with for now is removing the xapp status applet, and it appears that they work ok with the old systray applet.

**Comment by qwertfisch** [comment]
It is indeed a problem of the registered name which seems to be identical for the Flatpak versions of KeepassXC and Nextcloud. It works with some other flatpak-ed applications I tested yesterday. This seems to be a more generic desktop issue and has [no final solution](https://github.com/flathub/org.keepassxc.KeePassXC/issues/78) yet.

For now I am using the AppImage version of Nextcloud. Thank you for your time.
