### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Rpned** [linuxmint/cinnamon#10040]
```
 * Cinnamon version (cinnamon --version) Triscia 19.3
   - Please specify if you are using the daily builds PPA
     (https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds).No
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 19.3
 * Graphics hardware *and* driver used
 * 32 or 64 bit
 * Attach ~/.xsession-errors, or /var/log/syslog
 ```

**Issue**
ausrpned@Mint193:~$ dmesg --level=err
[    2.230463] ACPI BIOS Error (bug): AE_AML_BUFFER_LIMIT, Field [TBF3] at bit offset/length 262144/32768 exceeds size of target Buffer (262144 bits) (20190816/dsopcode-203)

Following update, approx 8thApril 2021

**Comment by leigh123linux** [comment]
This isn't a cinnamon issue.
