### ISSUE TITLE
[Discussion] Cinnamon's default shell theme deserves a refresh !

### ISSUE THREAD

**Issue by Lurux** [linuxmint/cinnamon#10050]
**Issue**

Cinnamon is an excellent and polished desktop environment, and really I think it deserves to be treated as a first-class citizen by other Linux distros.

The problem is, for distributions that don't ship a custom theme, the default Cinnamon theme is starting to look really dated IMO.

**Possible solution**

I understand that using the modern Mint themes would weaken the distro's branding, and that creating a new theme from scratch would require a lot of time.

_In the meantime, why not use the older and retired "Linux Mint" theme as the default for Cinnamon ?_ I think it strikes a really good balance between keeping an older look while being really polished and pleasing to the eye, and using it would be as simple as renaming it in order to fit the job. (Ok, maybe just a little more, as @ItzSwirlz pointed out).

**Other information**

In the long run, I really wish Cinnamon could get a new shell theme and be used more often as a "main" option by the other distributions - even if I know it's not your main goal, and I understand it. I think it deserves it.

**Edit**

_Can we get the design team or concerned person here to get the conversation going ?_

**Comment by magunto** [comment]
Very much agree!  I use Win10 at work, but privately using Mint/Cinamon on my computer and love the speed and simplicity on the old laptop. But the default theme in comparison to Win10 looks very poor and outdated. It requires hours of installing, adjusting and experimenting with other  themes (found on the internet) to make it look better. (example - standard minimize/maximize/close buttons are difficult to use and ugly, so I change it immediately to Qogir). I think especially for new users, who transit from Windows, look and esthetics are important.

**Comment by Lurux** [comment]
My comment isn't about the Linux Mint theme, but about the default Cinnamon theme on other distributions. Just spin up Debian Cinnamon on distrotest.net and you'll see what I mean.

**Comment by ItzSwirlz** [comment]
This is where environment packages come in, it's easier for the distro maintainers themselves to work out the themes. It's hard to get a distro-unified version of a theme.. I suppose looking at MATE but I wouldn't go that way.

An example of an 'environment' package is in packaging terms (get ready): Having another theme ready locally to apply the gschemas to, in order to give the pleasant feel of the OS.

Ubuntu Cinnamon Remix's env package is here: https://github.com/Ubuntu-Cinnamon-Remix/ubuntucinnamon-environment. I'm not sure where but Mint's is somewhere (maybe mintartwork?), and if you look in the Fedora code by leigh123linux you can find that Fedora uses the blue version of the Mint theme. If you look around you'll find it but my point is, it depends on the distro maintainer.

**Comment by Lurux** [comment]
> This is where environment packages come in, it's easier for the distro maintainers themselves to work out the themes.

Just to clarify, I'm talking about the shell theme here, which AFAIK is contained in [/data/theme](https://github.com/linuxmint/cinnamon/tree/master/data/theme).

@ItzSwirlz, In this context I fail to see how what you're saying here is relevant. For distributions that don't ship a custom theme, Cinnamon comes with a built-in (default) shell theme, which IMO should be updated. Am I missing something here ?

**Comment by leigh123linux** [comment]
Perhaps the lazy cinnamon distro maintainers can do a PR if they want better a theme.

**Comment by Lurux** [comment]
@leigh123linux, the reason I launched a discussion is because I don't know if this would be accepted in the first place (would the Cinnamon maintainers be ok with swapping the default theme to what I suggested without prior discussion ?), and, yes, because I don't have full knowledge of how Cinnamon themes works.

I don't have any problem with taking part in the 'dirty' work (or at least trying to), but I don't see how that's useful if it's going to be rejected anyway. So I decided to discuss here.

I'm really sorry if you took that as an offense, or if I expressed myself badly.

_Again, am I missing something here ?_

**Comment by JosephMcc** [comment]
@Lurux Your original suggestion is valid. I've thought about it before. Would probably just make a new neutral theme to replace the old one. Don't think the old Linux Mint theme is really a good choice. I'll see what people think and work on a new one if it's ok'd.

This really has nothing to do with distro maintainers. This is more for users who have Cinnamon in their distros repo but it isn't really a "supported" flavor. It would give something a bit nicer looking by default.

**Comment by leigh123linux** [comment]
@JosephMcc  Perhaps we could replace the default theme with a  mint-y-* cinnamon theme.

I used to ship the default in fedora and never had a single compliant, Users were free to choose whatever they liked from spices.

**Comment by JosephMcc** [comment]
@ItzSwirlz This won't have any effect on distros that ship Cinnamon flavors. Any more than the default theme does now. Your comments actually have little to do with what the original issue was for. It shouldn't effect you at all. The idea is just to give something nicer to people who install Cinnamon from their repos and get the full stock setup. Currently it's really outdated and ugly.

@leigh123linux Honestly the only reason I wouldn't want to that is because I'd rather include something that isn't the generated .css we get with mint-y. I'd prefer to have some nice css since this is something people often use as a base to create their own custom themes from. But the style could be similar.

**Comment by Lurux** [comment]
@JosephMcc, please tell me if I can help ! I love messing with CSS, though I don't know much about gtk themes.

Also, if a discussion is actually going to take place here, maybe this should be re-opened in the meantime ?

**Comment by Lurux** [comment]
Any news on this ? Any way I can help ?

**Comment by Lurux** [comment]
@JosephMcc, any news on that ?

As a refresher for anyone seeing this, we were talking about changing the default theme of Cinnamon, for distributions such as Debian or Arch which don't ship customized flavours for each of their DEs.

Also, am I crazy in saying this should be re-opened in the meantime ?

**Comment by JosephMcc** [comment]
Actually I have a new theme pretty much done. I just need to fix a few small details before making a PR for wider feedback.

No real need to reopen it. It's being worked on.

**Comment by Lurux** [comment]
@JosephMcc: Cool, this is good !

Btw, just a question about Cinnamon themes: are these essentially just specialized Gtk3 themes, or are they actually their own thing ? I say that, because I see they use the same kind of CSS than Gtk3.

Speaking of Gtk themes (still just being curious), do you know of any theme that isn't thousands of lines long ? I've been interested in tweaking Gtk themes in the past and again recently, but the sheer size of their CSS sheets is scaring me off.

**Comment by JosephMcc** [comment]
> Btw, just a question about Cinnamon themes: are these essentially just specialized Gtk3 themes, or are they actually their own thing ? I say that, because I see they use the same kind of CSS than Gtk3.

They are there own thing. CSS is CSS pretty much everywhere. In Cinnamon or Gtk there may be only a subset of it supported but it's still the same.

> Speaking of Gtk themes (still just being curious), do you know of any theme that isn't thousands of lines long ? I've been interested in tweaking Gtk themes in the past and again recently, but the sheer size of their CSS sheets is scaring me off.

No. Not really. A properly done Gtk theme sort of requires that.

**Comment by Lurux** [comment]
> No. Not really. A properly done Gtk theme sort of requires that.

Ughhh. Would I be wrong in saying that earlier Gtk versions were quite a lot simpler (as in, Gtk3 being over-complicated) ?
I won't talk about Qt theming because I don't know how that looks, but I would be curious to see that.

Anyway, I'm getting off-topic here, will stop polluting this chat now.

**Comment by JosephMcc** [comment]
No worries. They were somewhat simpler in the past but the css theming gives a lot of possibilities. As for Qt. I'm fairly sure those themes are actually written in C :) I'll take gtk's CSS any day.

**Comment by Lurux** [comment]
Oh. Lol.

**Comment by Lurux** [comment]
@JosephMcc, any news on this ? I don't see the new default theme in Mint 20.3, the default "Cinnamon" shell theme is still ugly asf.

With all that's happening with Gnome and Libadwaita currently, people and distros may be searching for other DEs, and I think not showing Cinnamon in it's full glory would be a disservice to the community.

To me, this DE strikes the perfect balance between Gnome's simplicity and KDE's flexibility, and it really deserves to be much better regarded. But for that, it needs to look great out of the box.
