### ISSUE TITLE
An unknown package update caused almost all gnome-based programs not to start anymore

### ISSUE THREAD

**Issue by IvoAndonov** [linuxmint/cinnamon#10053]
```
 * Cinnamon version (cinnamon --version) - 4.8.6
   - Please specify if you are using the daily builds PPA: IDK, whatever comes from Arch's repo - that's it.
 * Distribution - Arch Linux
 * Graphics hardware *and* driver used GTX 1660 Ti, nvidia 450.57
 * 64 bit
 * Attach ~/.xsession-errors, or /var/log/syslog
 ```

**Issue**
After update early this morning (and after reboot), gnome-terminal doesn't start anymore and so do many other gnome related programs, including all file managers, so I can't even get to the .xsession-errors file. Pamac-classic doesn't appear in tray anymore.

The list of updated packages is long and I have no idea which one is causing it. See the list in "Other information".

**Steps to reproduce**
Full system update.

**Expected behaviour**
Apps should start normally.

**Other information**
These are all the packages waiting to be updated. One of them caused the described issue.

amtk-5.3.1-1  aom-3.0.0-2  attica-5.81.0-1  boost-1.75.0-3  boost-libs-1.75.0-3  botan-2.18.0-1  breeze-icons-5.81.0-1  ca-certificates-mozilla-3.64-1  cbindgen-0.19.0-1  cifs-utils-6.13-1  cmake-3.20.1-1  cups-1:2.3.3op2-2  curl-7.76.1-1  dpkg-1.20.7.1-1  electron-12.0.4-2  enchant-2.2.15-2  exo-4.16.2-1  expat-2.3.0-1  extra-cmake-modules-5.81.0-1  ffmpeg-2:4.3.2-6  file-5.40-2  file-roller-3.38.1-1  fuse-common-3.10.3-1  fuse3-3.10.3-1  gdk-pixbuf2-2.42.6-1  gdm-40.0-1  gedit-40.1-1  geoclue-2.5.7-3  glib2-2.68.1-1  glib2-docs-2.68.1-1  gnome-backgrounds-40.0-1  gnome-session-40.0-1  gnome-settings-daemon-40.0.1-1  gnome-shell-1:40.0-1  gsettings-desktop-schemas-40.0-3  gst-plugins-bad-1.18.4-4  gst-plugins-bad-libs-1.18.4-4  gtk-update-icon-cache-1:4.2.0-5  gtk3-1:3.24.28-4  gtk4-1:4.2.0-5  harfbuzz-2.8.0-3  harfbuzz-icu-2.8.0-3  icu-69.1-1  imagemagick-7.0.11.8-1  jack2-1.9.18-1  jasper-2.0.28-1  karchive-5.81.0-1  kauth-5.81.0-1  kbookmarks-5.81.0-1  kcmutils-5.81.0-1  kcodecs-5.81.0-1  kcompletion-5.81.0-1  kconfig-5.81.0-1  kconfigwidgets-5.81.0-1  kcoreaddons-5.81.0-1  kcrash-5.81.0-1  kdbusaddons-5.81.0-1  kdeclarative-5.81.0-1  kded-5.81.0-1  kdelibs4support-5.81.0-1  kdesignerplugin-5.81.0-1  kdoctools-5.81.0-1  kemoticons-5.81.0-1  kfilemetadata-5.81.0-1  kglobalaccel-5.81.0-1  kguiaddons-5.81.0-1  ki18n-5.81.0-1  kiconthemes-5.81.0-1  kinit-5.81.0-1  kio-5.81.0-1  kitemmodels-5.81.0-1  kitemviews-5.81.0-1  kjobwidgets-5.81.0-1  knewstuff-5.81.0-1  knotifications-5.81.0-1  knotifyconfig-5.81.0-1  kpackage-5.81.0-1  kparts-5.81.0-1  kservice-5.81.0-1  ktextwidgets-5.81.0-1  kunitconversion-5.81.0-1  kwallet-5.81.0-1  kwayland-5.81.0-1  kwidgetsaddons-5.81.0-1  kwindowsystem-5.81.0-1  kxmlgui-5.81.0-1  lib32-curl-7.76.1-1  lib32-expat-2.3.0-2  lib32-gdk-pixbuf2-2.42.6-1  lib32-glib2-2.68.1-1  lib32-harfbuzz-2.8.0-3  lib32-icu-69.1-1  lib32-libcurl-compat-7.76.1-1  lib32-libcurl-gnutls-7.76.1-1  lib32-libdrm-2.4.105-1  lib32-libnsl-1.3.0-2  lib32-librsvg-2.50.4-1  lib32-libxcrypt-4.4.19-1  lib32-libxkbcommon-1.2.1-1  lib32-libxml2-2.9.10-4  lib32-mesa-21.0.2-1  lib32-nss-3.64-1  lib32-vulkan-icd-loader-1.2.174-1  libavif-0.9.0-2  libcdr-0.1.7-2  libcmis-0.5.2-7  libcups-1:2.3.3op2-2  libcurl-compat-7.76.1-1  libcurl-gnutls-7.76.1-1  libdrm-2.4.105-1  libe-book-0.1.3-9  libgdm-40.0-1  libgweather-40.0-1  libhandy-1.2.1-1  libheif-1.11.0-3  libical-3.0.9-2  libmspub-0.1.4-10  libmwaw-0.3.18-1  libnsl-1.3.0-2  libqxp-0.0.2-6  libreoffice-fresh-7.1.2-3  librsvg-2:2.50.4-1  libva-mesa-driver-21.0.2-1  libvisio-0.1.7-5  libxcrypt-4.4.19-1  libxkbcommon-1.2.1-1  libxkbcommon-x11-1.2.1-1  libxml2-2.9.10-9  libxnvctrl-465.24.02-1  libzmf-0.0.2-10  lua-5.4.3-1  mesa-21.0.2-1  meson-0.57.2-1  metis-5.1.0.p10-2  mkvtoolnix-cli-56.1.0-1  mkvtoolnix-gui-56.1.0-1  mtools-4.0.27-1  mujs-1.1.1-1  mutter-40.0-3  nodejs-lts-dubnium-10.24.0-2  npm-7.10.0-1  npm-check-updates-11.4.1-1  nss-3.64-1  oath-toolkit-2.6.6-2  oniguruma-6.9.7.1-1  postgresql-libs-13.2-2  python-3.9.3-1  qt5-base-5.15.2+kde+r172-2  qt5-declarative-5.15.2+kde+r24-1  qt5-location-5.15.2-3  qt5-svg-5.15.2+kde+r7-1  qt5-tools-5.15.2+kde+r17-1  qt5-wayland-5.15.2+kde+r19-1  qt5-webengine-5.15.3-4  qt5-webkit-5.212.0alpha4-10  raptor-2.0.15-16  ruby-3.0.1-1  ruby-irb-1.3.5-1  ruby-reline-0.2.5-1  rubygems-3.2.15-1  samba-4.14.2-2  smbclient-4.14.2-2  solid-5.81.0-1  sonnet-5.81.0-1  systemd-248-5  systemd-libs-248-5  systemd-sysvcompat-248-5  tepl-6.00.0-2  thunderbird-78.9.1-3  thunderbird-i18n-bg-78.9.1-3  tracker3-3.1.1-2  uget-2.2.3-2  unrar-1:6.0.5-1  vala-0.52.2-1  vlc-3.0.12-4  vulkan-headers-1:1.2.175-2  vulkan-icd-loader-1.2.174-2  webkit2gtk-2.32.0-2  wpebackend-fdo-1.8.3-1  xf86-input-libinput-1.0.1-1  xfsprogs-5.11.0-2  xorg-server-1.20.11-1  xorg-server-common-1.20.11-1  xorg-server-xvfb-1.20.11-1  xorg-xwayland-21.1.1-1  youtube-dl-2021.04.17-1

**Comment by leigh123linux** [comment]
Report the issue to archlinux, it's probably a gnome issue.
