### ISSUE TITLE
Blank desktop in Virtual Box

### ISSUE THREAD

**Issue by noloader** [linuxmint/cinnamon#10067]
Hi Everyone,

```
 * Cinnamon version (cinnamon --version)
   - 4.8.6
 * Distribution
   - Fedora 34, x86_64, fully patched
 * Graphics hardware *and* driver used
   - VMware SVGA II Adapter (prog-if 00 [VGA controller])
 * Attach ~/.xsession-errors, or /var/log/syslog
   - Attached
 ```

**Issue**

I'm running Fedora 34 x86_64 with Cinnamon 4.8.6. When I enable 3D checkbox in Virtual Box settings, I get a blank/white desktop after login. Login is OK.

If I uncheck the 3D checkbox in Virtual Box settings the desktop is OK. But in non-3D we get warnings about no hardware acceleration. The reason I check the 3D checkbox is, the warnings are annoying (to me) because they show up on my desktop.

Cinnamon works well on Fedora (sans this 3D problem). I'm glad Cinnamon has been ported to Fedora. The Fedora-Cinnamon spin beats the snot out of GNOME3.

**Steps to reproduce**

Download the Fedora-Cinnamon spin at https://spins.fedoraproject.org/. On a modern Linux (like Ubuntu 18 or 20), setup a VM and install Fedora-Cinnamon spin. The VM will use the VMSVGA controller by default. Once setup enable 3D acceleration.

To enable 3D acceleration, power off the VM. Find the Fedora 34 VM, right click, then Settings. Click Display, select Screen tab, and then check the "Enable 3D acceleration" checkbox. Then power on the VM.

Before you enable 3D acceleration, you may want to `systemctl enable sshd` and `systemctl start sshd` . Then follow it with `ifconfig` to get the IP address. Then you will be able to SSH into the box (and shut it down with `sudo halt`).

**Other information**

I uploaded the system information to PasteBin at https://pastebin.com/dEF1CBFW.

I think a related issue is GH #8489. It looks like OP closed the issue before it was resolved.

xsession-errors: [xsession-errors.zip](https://github.com/linuxmint/cinnamon/files/6410016/xsession-errors.zip). The `xsession-errors` (without old) is experiencing the problem. The `xsession-errors-old` (with old) lacked 3D acceleration and was OK.

Xorg.0.log: [Xorg.log.zip](https://github.com/linuxmint/cinnamon/files/6410027/Xorg.log.zip).

Below is a screenshot of the blank/white desktop. The login screen is OK.

![VirtualBox_Fedora 34 Cinnamon (x64)_01_05_2021_13_14_31](https://user-images.githubusercontent.com/3538226/116790169-eafe4400-aa80-11eb-8cf9-7b0029cfe746.png)

**Comment by leigh123linux** [comment]
File the issue against vbox, cinnamon needs a proper working 3d graphics driver.

**Comment by noloader** [comment]
Thanks @leigh123linux.

How do I tell them its a problem with the 3D driver? Is there a log entry somewhere showing some capability is not available?

Is it possible to have Cinnamon fallback to a 2D driver when it detects a 3D driver is not acceptable? That is, just avoid the missing or misbehaving 3D feature?

And finally, is t possible to disable the 2D driver warning? There's no sense in nagging the user about something they have no control over and can't fix.

**Comment by leigh123linux** [comment]
After testing fedora an mint cinnamon spins in vbox .

1: fedora = white screen with 3d enabled.
2: mint = runs fine with 3d enabled.

You should file the issue against fedora mesa at bugzilla.

https://bugzilla.redhat.com/enter_bug.cgi

**Comment by noloader** [comment]
Thanks @leigh123linux,

The Fedora bug report was filed at Issue 1956512, [Blank desktop in Virtual Box 6.1](https://bugzilla.redhat.com/show_bug.cgi?id=1956512).

**Comment by Sanrax** [comment]
> 1: fedora = white screen with 3d enabled.
> 2: mint = runs fine with 3d enabled.

Most likely only worked because mint was more using more outdated packages. Thread on this issue in mint forums - https://forums.linuxmint.com/viewtopic.php?t=354405 I am having the same issue on a Mint VM after updating it.

Now it's like this:

1: fedora = white screen with 3d enabled.
2: mint = white screen with 3d enabled.

So, I'd say this is not a Fedora issue, and rather a Cinnamon issue.

**Comment by Alquas** [comment]
I had the same problem,
though it's not optimal selecting "cinnamon (software rendering)" when selecting DE (or any other if you have multiple DEs installed) on the login screen fixes the issue if you need to recover stuff from the VM or temporarily access it to install another DE (or if you don't mind the lack of performance as it's just a VM)
