### ISSUE TITLE
irregular RAM usage, freezing

### ISSUE THREAD

**Issue by sauce420** [linuxmint/cinnamon#10062]
```
 * Cinnamon version 4.8.6, kernel 5.8.0-50-generic
 * Distribution - Linux Mint 20.1
 * XFX Radeon RX 5500, amdgpu driver
 * 64 bit
 ```

**Issue**
Cinnamon used an unusual amount of ram and cpu, causing everything to freeze randomly

**Steps to reproduce**
Could be a lot of things, I had an external hard drive that I ejected, but it was still plugged in
I had a program that wanted to be running but it wasn't at the time, so it was throwing errors
fixing both of these errors didn't change anything in the Ram usage, but could have possibly caused it
sorry for being vague
**Expected behaviour**
cinnamon uses less resources

**Other information**
[image of ram usage](https://imgur.com/a/msAt4FS)
usage returned to normal after cinnamon restart with ctrl+alt+esc
at the time. there seemed to be 2 instances of cinnamon running, one of which was cinnamon, the other cinnamon --replace. The cinnamon task disappeared later, leaving cinnamon --replace

**Comment by sauce420** [comment]
[this issue looks similar](https://github.com/linuxmint/cinnamon/issues/9926), although I've had no cinnamon crash

**Comment by sauce420** [comment]
I'll close this issue, too similar to the issue linked in previous comment

**Comment by Ahmed-E-86** [comment]
Update Linux kernel to 5.11. You can use Mainline to do that >> https://github.com/bkw777/mainline
