### ISSUE TITLE
Why does cinnamon depend on gnome-online-accounts?

### ISSUE THREAD

**Issue by jmssil** [linuxmint/cinnamon#10065]
Cinnamon 4.8.6
Linux Mint 20.1 Ulyssa
64 bit

Why does cinnamon need gnome-online-accounts? Why gnome? Why online accounts? Why is this a base dependence?

**Comment by leigh123linux** [comment]
It's used for cinnamon-settings online accounts, if it wasn't a dep we would get users wringing that it didn't work.

https://github.com/linuxmint/cinnamon/blob/master/files/usr/share/cinnamon/cinnamon-settings/modules/cs_online_accounts.py

**Comment by jmssil** [comment]
OK, seems reasonable. But why is it running if I have never opened the "Online Accounts" program?

**Comment by leigh123linux** [comment]
I believe gtk3 starts it

https://www.systutorials.com/docs/linux/man/8-goa-daemon/
https://github.com/search?q=org%3Alinuxmint+org.gnome.OnlineAccounts&type=code

**Comment by jmssil** [comment]
Thanks.

I don't know much about Gtk, but why should a graphical user interface toolkit demand for gnome-online-accounts? Seems to make no sense whatsoever.

Why not run it if and only if cinnamon-settings online-accounts activates it?

**Comment by ItzSwirlz** [comment]
It's called a runtime dependency. It's functionality won't work.

Buttttt we could do a stand-alone module

**Comment by NikoKrause** [comment]
Is this a royal we (pluralis majestatis)?
Please stop talking in plurals unless you have concrete plans with other people. 
Try to circumscribe, e.g.
"A possibility would be to create a standalone module."
