### ISSUE TITLE
Shut Down Twice

### ISSUE THREAD

**Issue by dotnetspec** [linuxmint/cinnamon#10077]
```
 * Cinnamon version 4.8.6
   - Please specify if you are using the daily builds PPA
     No
 * Distribution - Mint 20.1
 * Graphics hardware *and* driver used - Intel Corporation Iris Plus Graphics G7 - (no driver specified in System Info).
 * 64 bit
 * Attach ~/.xsession-errors ('This file is hidden. Try again with another file')
 or /var/log/syslog ('We don't support that file type. Try again')
 ```

**Issue**
I have to shut down twice every time I shut down.

**Steps to reproduce**
-> Menu (Bottom left task bar) -> Quit -> (nothing happens) -> Menu (Bottom left task bar) -> Quit (second time it works as per normal).

**Expected behaviour**
-> Menu (Bottom left task bar) -> Quit

**Other information**

**Configuration info, if applicable**
N/A

Thanks for your attention.

**Comment by mtwebster** [comment]
What programs do you have running that put an icon in the system tray (where the update manager icon appears)? I've found certain programs that do this can sometimes interfere with shutdown and force me to do this same thing - shutdown twice - though I've been unable to reproduce it reliably.

**Comment by leigh123linux** [comment]
@mtwebster  Try qbittorrent, it should reproduce the issue.

**Comment by dotnetspec** [comment]
@mtwebster An (excellent) program I recently installed called NixNote2 is causing this (although others may have previously as well). It's therefore not a Linux Mint issue, but rather one for the developer of that app. Thanks again for your help in identifying the source of the problem ...
