### ISSUE TITLE
Postman double icon on panel

### ISSUE THREAD

**Issue by Mikhailov972** [linuxmint/cinnamon#10081]
- **Cinnamon version:** 4.8.6
I don't use the daily builds PPA.
- **Distribution:** Mint 20.1 ulyssa
- **Graphics hardware:** GPU: Radeon RX 580 Series (POLARIS10, DRM 3.35.0, 5.4.0-72-generic, LLVM 11.0.1)
- **Driver used:** 21.10
https://www.amd.com/ru/support/graphics/radeon-500-series/radeon-rx-500-series/radeon-rx-580
- **32 or 64 bit:** 64 bit
- **I haven't log error.**

**Issue**
I created Postman desktop entry in Linux mint menu and pin his on panel. But if I start Postman. My panel visible two postman icon.

**Steps to reproduce**
https://youtu.be/zggmtlhF28Q

**Expected behaviour**
If I start Postman his doesn't create new icon on panel.

**Comment by icarter09** [comment]
Have you noticed this issue with other applications? Also does Postman have a free download for me to test with? Thanks.

**Comment by mtwebster** [comment]
It's a flatpak

**Comment by icarter09** [comment]
Cinnamon 5.0.4
Mint 20.1 64bit

I'm not able to reproduce this issue using the version of Postman via the Software Manager.

**Comment by Teemitze** [comment]
> Have you noticed this issue with other applications? Also does Postman have a free download for me to test with? Thanks.
You can download free version here https://www.postman.com/downloads/
I not noticed this bug in other applications, but I think it is problem Mint, because I create launcher and get result in video.

> I'm not able to reproduce this issue using the version of Postman via the Software Manager.
I checked, yes it is.
