### ISSUE TITLE
~/.xsession-errors: ATTENTION! Currently cached group 1 is not equal to the current group from the event: 0

### ISSUE THREAD

**Issue by jkirk** [linuxmint/cinnamon#10083]
**Facts**
```
 * Cinnamon version: 4.8.6
 * Distribution: Debian GNU/Linux 11 (bullseye) (not yet released / but currently frozen)
 * Graphics hardware *and* driver use: Intel UHD Graphics 620 / driver: i915
 * 64 bit (x86_64)
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog: see below

% inxi -G -S   
System:
  Host: executor Kernel: 5.10.0-6-amd64 x86_64 bits: 64 
  Desktop: Cinnamon 4.8.6 Distro: Debian GNU/Linux bullseye/sid 
Graphics:
  Device-1: Intel UHD Graphics 620 driver: i915 v: kernel 
  Device-2: Chicony Integrated Camera (1280x720@30) type: USB 
  driver: uvcvideo 
  Display: x11 server: X.Org 1.20.10 driver: loaded: modesetting 
  unloaded: fbdev,vesa resolution: 1: 1920x1080~60Hz 2: 3840x2160~60Hz 
  OpenGL: renderer: Mesa Intel UHD Graphics 620 (KBL GT2) v: 4.6 Mesa 20.3.4 
 ```

**Issue**

`~/.xsession-errors:` gets spammed with the following lines:
```
![1620829855,000,xklavier_evt_xkb.c:xkl_xkb_process_x_event/] 	ATTENTION! Currently cached group 1 is not equal to the current group from the event: 0
![1620829855,000,xklavier_evt_xkb.c:xkl_xkb_process_x_event/] 	ATTENTION! Currently cached group 1 is not equal to the current group from the event: 0
![1620829862,000,xklavier_evt_xkb.c:xkl_xkb_process_x_event/] 	ATTENTION! Currently cached group 1 is not equal to the current group from the event: 0
![1620829862,000,xklavier_evt_xkb.c:xkl_xkb_process_x_event/] 	ATTENTION! Currently cached group 1 is not equal to the current group from the event: 0
![1620829866,000,xklavier_evt_xkb.c:xkl_xkb_process_x_event/] 	ATTENTION! Currently cached group 1 is not equal to the current group from the event: 0
![1620829866,000,xklavier_evt_xkb.c:xkl_xkb_process_x_event/] 	ATTENTION! Currently cached group 1 is not equal to the current group from the event: 0
![1620829870,000,xklavier_evt_xkb.c:xkl_xkb_process_x_event/] 	ATTENTION! Currently cached group 1 is not equal to the current group from the event: 0
```

**Steps to reproduce**

I actually can't yet, but I restarted cinnamon and it seems to have something to do with the mouse scroll wheel. I need to test it with a new user.

I need help debugging this issue. Thank you!

(How to list all activated extensions and applets via command line?)

**Comment by mtwebster** [comment]
Do you have multiple keyboard layouts installed? If so, try removing them then re-adding.

**Comment by jkirk** [comment]
Hmm... Yes, I have multiple keyboard layouts: English (intl., with AltGr dead keys) + German (Austria, no dead keys).

I removed one (German) and at first it seemed to work. As I was about to answer, the messages popped up again.
Then I re-added German and removed English and got this:
```
(cinnamon-screensaver:10001): XApp-CRITICAL **: 16:46:32.049: xapp_kbd_layout_controller_set_current_group: assertion 'controller->priv->enabled' failed

(cinnamon:9839): XApp-CRITICAL **: 16:46:39.700: xapp_kbd_layout_controller_set_current_group: assertion 'controller->priv->enabled' failed

(cinnamon:9839): XApp-CRITICAL **: 16:46:56.023: xapp_kbd_layout_controller_get_current_group: assertion 'controller->priv->enabled' failed

(cinnamon:9839): Cjs-CRITICAL **: 16:46:56.024: JS ERROR: TypeError: item is undefined
_syncGroup@/usr/share/cinnamon/applets/keyboard@cinnamon.org/applet.js:281:9

(cinnamon:9839): XApp-CRITICAL **: 16:46:56.026: xapp_kbd_layout_controller_get_current_group: assertion 'controller->priv->enabled' failed

(cinnamon:9839): Cjs-CRITICAL **: 16:46:56.026: JS ERROR: TypeError: item is undefined
_syncGroup@/usr/share/cinnamon/applets/keyboard@cinnamon.org/applet.js:281:9
```
Finally, I only kept English, restarted Cinnamon and then re-added German. Since then, I did not get an error message.
Seems to work now. But what is the problem? How could I have avoided this or is it a bug (and should we keep this issue open)?

It should also be noted that added/removing a keyboard layout makes not only the "Keyboard Layout" window but also the whole Cinnamon Desktop unresponsive for quite a few seconds. Any idea what is causing this kind of lag?

I appreciate your *very* quick response! Thx very much! 💪🏾 🖖🏾

**Comment by jkirk** [comment]
Oh no... The messages came back. So the problem is not solved yet... 😢

**Comment by mtwebster** [comment]
Try removing the layouts again, then log out and back in to see if that makes any difference

**Comment by jkirk** [comment]
Ok. Did remove the German layout, logged out, logged in and re-added the German layout again.

Now, after a few minutes and using the mouse scroll wheel, the messages are not shown anymore. Nice.

What was the thing? Is this a problem when updating from Cinnamon 3.8.x to 4.8.x and having more than one keyboard layout?

**Comment by mtwebster** [comment]
Sorry for taking so long to respond - I'm not really sure what could have caused it - that's a big cinnamon version jump - if you upgraded other system libraries at the same time then I think if this was the only issue you had, you're in good shape :)

**Comment by jkirk** [comment]
@mtwebster I tried to ignore this as long as I could, but this issue really bugs me:
```
❯ grep "ATTENTION! Currently cached group" .xsession-errors.old | wc -l 
269288

❯ grep "ATTENTION! Currently cached group" .xsession-errors | wc -l    
1133060
```
Could you re-open this issue, so other people can find it and/or provide help?

I understand that this problem does not seem very serious (for you and/or the Cinnamon project) and yes, I know Cinnamon 5 is out since a while now. I am willing to dig into it, maybe someone can give me some pointers on how to debug this problem.

Thank you!

**Comment by ItzSwirlz** [comment]
I'll see if I get it. Thanks for opening a Debian issue

**Comment by intx82** [comment]
Remove `~/.config/QtProject.conf`. That helps me.
