### ISSUE TITLE
[bug] nemo-desktop doesn't apply shadows to text when adding gtk.css to ~/.config/gtk-3.0

### ISSUE THREAD

**Issue by TPO100Cofficial** [linuxmint/cinnamon#10085]
cinnamon 4.8.6, pretty sure i'm not using the daily builds
linux mint 20.1
hardware irrelevant

**Issue**
text on the cinnamon desktop screen can be hard to read, or unreadable against close to/white backgrounds
maybe have an option for alternate text shadow effects? like a stronger "blurred duplicate of text" kind of effect?
sorry if this is a thing already present [in] cinnamon and i just didn't realize (hence the [*question*/request] tagging)

![image](https://user-images.githubusercontent.com/33667869/118188430-e72ed200-b42f-11eb-9cd6-7805f7b05396.png)

**Comment by IvoAndonov** [comment]
There is but it's not a built-in option, you have to do it yourself. This is how I did it:
• open /.config/gtk-3.0/gtk.css (or create that file there, if you don't have it)
• add this content in it:

.nemo-desktop.nemo-canvas-item {
  color: white;
   text-shadow: 2px 2px 0 #000000, 2px -2px 0 #000000, -2px 2px 0 #000000, -2px -2px 0 #000000, 2px 0px 0 #000000, 0px 2px 0 #000000, -2px 0px 0 #000000, 0px -2px 0 #000000;
}

save the file and restart Cinnamon. This will create outlining of the text on desktop icons. This is what it looks like:

![Picture_created_14-05-2021_14-12-16](https://user-images.githubusercontent.com/41172201/118263143-8ef2e100-b4be-11eb-919d-ce6bce0c316d.png)

**Comment by TPO100Cofficial** [comment]
thank you!

**Comment by TPO100Cofficial** [comment]
i was busy that day and closed this assuming it'd would work later, now i tried it and it? doesn't work?????
![image](https://user-images.githubusercontent.com/33667869/118363211-d3e04b80-b582-11eb-9bde-5ad10c87f875.png)
gtk.css wasn't here before either, am i doing something wrong? @IvoAndonov

**Comment by TPO100Cofficial** [comment]
i even tried  logging off and back on, but nothing! just disappointment

**Comment by IvoAndonov** [comment]
I don't see a reason to think your post is aggressive. :)
Did you try with (if I remember the combination properly) Alt+F2, type "r" (without the quotes) or "-r" and press Enter? I haven't done this in more than a year and I don't remember whether it was "r" or "-r". 
IDK why it doesn't work on your side. The screenshot I showed you is from my desktop and it works. Maybe you don't have gtk-3.0 installed? But then again I'm using Arch Linux and maybe that makes the difference.

**Comment by TPO100Cofficial** [comment]
i used "r", no minus
guess this is just one of those mysterious issues noone else has
![image](https://user-images.githubusercontent.com/33667869/118406099-7de6d300-b66a-11eb-8640-836234d6a2c6.png)
..also, i do have gtk-3, or at least don't see any reason i shouldn't since mint-y, cinnamon, etc even work

**Comment by IvoAndonov** [comment]
If you haven't been able to make it work, you can ask in Mint's forum for users help. You can even give tem a link to this topic here. Maybe someone will have a better idea why it won't work on your end.

**Comment by TPO100Cofficial** [comment]
still haven't been able to get it to work, even after reinstalling mint (for different reasons, i'm not that much of a freak about perfection)
i've tried various different methods to try to get it to work, too, like different gtk themes to apply to the desktop with bigger shadows for nemo-desktop files but none worked
i do not understand what i am doing wrong

**Comment by TPO100Cofficial** [comment]
> If you haven't been able to make it work, you can ask in Mint's forum for users help. You can even give tem a link to this topic here. Maybe someone will have a better idea why it won't work on your end.

tried that, no attention (understandably so, it's kinda dumb of me to get so worked up about bad text shadows)
i've bumped the post a few times, still nothing
gonna reopen this and see if the fate of this is any different

**Comment by TPO100Cofficial** [comment]
can't believe it took me this long to find out, apparently you just have to do pkill nemo-desktop in alt + f2 menu
thank you mint forums! [https://forums.linuxmint.com/viewtopic.php?t=285306](url)

**Comment by IvoAndonov** [comment]
I told you the mint forums are the best place to search for answers. ;)
