### ISSUE TITLE
Reserve some space in the panel to activate the panel context menu

### ISSUE THREAD

**Issue by autarkper** [linuxmint/Cinnamon#1010]
Now that we have a panel context menu, it would be great if there was a way to guarantee that there would always be some empty space in the panel where one can click, even when the panel is really crowded. Of course, one can have the Settings applet enabled for that purpose, but that is overkill, IMO.

**Comment by JosephMcc** [comment]
Thank you for your suggestion. See https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html for information on how we handle feature requests.
