### ISSUE TITLE
Bug which deletes apps pinned in taskbar

### ISSUE THREAD

**Issue by Luekk** [linuxmint/cinnamon#10106]
```
 * Cinnamon 4.8.6
 * Mint 20.1 Ulyssa 64-bit
 ```

**Issue**
If I change panel layout in welcome screen from modern to classic and switch back to modern again, my pinned apps from taskbar are becoming unpinned and default apps stays pinned.

**Steps to reproduce**
Log in to system
When welcome screen shows up go to first steps
Change panel layout from modern to classic
And all pinned apps are now unpinned. Defaults are unchanged

**Expected behaviour**
While changing panel layout all pinned apps should stay at their place.

**Other information**

**Configuration info, if applicable**

Please paste here

```

**Comment by icarter09** [comment]
One thing to note is that it does state this on the Welcome screen...

`Note: Cinnamon will restart after you choose a new layout. Any customization you made to the panel will be lost.`
