### ISSUE TITLE
drag&dropping element of the window list doens't work properly

### ISSUE THREAD

**Issue by calestyo** [linuxmint/cinnamon#10103]
```
 * Cinnamon version 4.8.6
 * Distribution Debian sid
 * Graphics hardware *and* driver used Intel Corporation HD Graphics 620 /  iHD_drv_video
 * 64 bit
 ```

**Issue**
Since at least a year or so, sometimes when moving elements of the window list, the indicator that shows where they element would end up jumps weirdly around and even worse, I cannot select any position in the list.

As said, this does not always happen (but quote often) and I haven't found an exact way to reproduce it. Also it doesn't necessarily seem to happen on all workspaces at the same time.

I guess it can be best shown with the following video:
https://drive.google.com/file/d/1BpaW7kGcvrVomJOqTwGGtj2oY8HxAjon/view?usp=sharing
(sorry, but even after 10 mins of trying I couldn't get this uploaded to github, neither as GIF, nor zipped nor renamed as .txt)

https://user-images.githubusercontent.com/1299302/119096618-b50f0880-ba0b-11eb-847c-d9a2ac1ee8ed.mp4

Thanks,
Chris.

**Comment by icarter09** [comment]
@calestyo try out [Peek](https://github.com/phw/peek). I've found it's pretty good for creating a simple gif of the issue and can be easily attached to a github issue.

**Comment by calestyo** [comment]
I had even converted the webm to gif with ffmpeg (which played back fine here), but github didn't accept it either... no idea, why.
Anyway, I guess the webm can be played back now.
But thanks for the pointer :D

**Comment by icarter09** [comment]
Cinnamon 4.8.6 daily build
Mint 20.1 64bit

I'm unable to reproduce this issue. I also added the Workspace applet since it appears from the video that you might be using that. Have you experienced it recently or established steps to reproduce it? Thanks.

**Comment by calestyo** [comment]
Hey.

Since cinnamon 5.0.5 has reached Debian, the problem seems gone. Thus closing.

Thanks,
Chris.
