### ISSUE TITLE
[feature] Switch to Pipewire (using PW's Pulseaudio client?)

### ISSUE THREAD

**Issue by mcarans** [linuxmint/cinnamon#10108]
I have switched to Pipewire in Mint 20.1 following the instructions here:
https://pipewire-debian.github.io/pipewire-debian/

(I added bluez5.msbc-support=true in /etc/pipewire/media-session.d/bluez-monitor.conf to enable SBC as otherwise the microphone quality is poor.) 

All works seamlessly - better than the original Pulseaudio where the microphone of my Bluetooth headset wouldn't work.

Fedora has already switched to Pipewire as have Ubuntu in their non LTS release. Mint and Cinnamon could switch to Pipewire perhaps using Pipewire's Pulseaudio client (which is my setup right now and is easy as it is a drop in replacement) or code to use Pipewire directly.

**Comment by leigh123linux** [comment]
I don't  think @clefebvre  will switch till the next ubuntu LTS release.

https://github.com/linuxmint/linuxmint/issues/336

```
$ inxi -SA
System:
  Host: mpd.lan Kernel: 5.11.21-300.fc34.x86_64 x86_64 bits: 64 
  Desktop: Cinnamon 4.8.6 Distro: Fedora release 34 (Thirty Four) 
Audio:
  Device-1: Intel Celeron/Pentium Silver Processor High Definition Audio 
  driver: snd_hda_intel 
  Device-2: Thesycon System & Consulting D10 type: USB driver: snd-usb-audio 
  Sound Server-1: ALSA v: k5.11.21-300.fc34.x86_64 running: yes 
  Sound Server-2: PipeWire v: 0.3.28 running: yes 
```
