### ISSUE TITLE
Unmaximising windows effect is broken

### ISSUE THREAD

**Issue by BeatLink** [linuxmint/cinnamon#10115]
```
 * Cinnamon version: Cinnamon 4.8.6
 * Not using Daily Builds PPA
 * Distribution: Linux Mint 20.1 Cinnamon
 * Graphics hardware *and* driver used" Intel Corporation UHD Graphics 620, default drivers
 * 32 or 64 bit: 64 bit
 * Attach ~/.xsession-errors, or /var/log/syslog: See below
 ```

**Issue**
Unmaximising windows effect does nothing

**Steps to reproduce**
* Go to Settings -> Effects -> Customize and enable customization
* Set Unmaximising windows to scale, easeNone, 500ms
* Restart cinnamon (also doesnt work without restart)
* Maximize a window
* Minimize a window and watch its effects
* Notice that the window instantly transitions from maximizing to unmaximized, without showing the effects

**Expected behaviour**
* The window is supposed to transition between maximized and unmaximized according to the effects setting

**Other information**

**Configuration info, if applicable**
If this bug report is related to an Applet, Desklet or Extension, please paste (or use a pastebin service) the offending extension's settings, if it has any.  You can obtain this by opening its configuration, clicking the 'hamburger' button in the upper-right corner of the window, and selecting "Export to a file". **Please be sure to review the contents and remove any personal data it may contain.**

```

Please paste here

Not Applicable

```

**Comment by gadass** [comment]
Hi @BeatLink, this issue should be fixed by this PR https://github.com/linuxmint/cinnamon/pull/10102.
