### ISSUE TITLE
Cinnamon enters in fallback mode when there is multiple nvidia graphic card attached with configured screens in xorg.conf

### ISSUE THREAD

**Issue by glgomes** [linuxmint/cinnamon#10122]
**System version**
```
Cinnamon 4.8.6 (default version)
Linux Mint 20.1 Ulyssa 64-bit
Kernel Linux 5.4.0-73-generic x86_64
Nvidia proprietary driver 460.73.01-0ubuntu0.20.4.1

 ```

**Issue**
Cinnamon enters in fallback mode when there is more than one nvidia graphic card attached and configured screens in xorg.conf. 
a) This same configuration works with Mate Desktop.
b) The screens are necessary to enable coolbits feature on nvidia driver. If line 7 of (attached) xorg.conf is commented, everything works fine. 

**Steps to reproduce**
In a machine with two or more nvidia cards, with one monitor attached to one of the cards
1) run sudo nvidia-xconfig --enable-all-gpus and edit or create a /etc/X11/xorg.conf file
2) reboot machine or restart lightdm service

**Expected behaviour**
Cinnamon should not enter in fallback mode

**Configuration and logs**
[xsession-errors.txt](https://github.com/linuxmint/cinnamon/files/6566636/xsession-errors.txt)

[xorg.conf.txt](https://github.com/linuxmint/cinnamon/files/6566640/xorg.conf.txt)

[inxi_output.txt](https://github.com/linuxmint/cinnamon/files/6566637/inxi_output.txt)

**Comment by leigh123linux** [comment]
> **System version**
> 
> ```
> Cinnamon 4.8.6 (default version)
> Linux Mint 20.1 Ulyssa 64-bit
> Kernel Linux 5.4.0-73-generic x86_64
> Nvidia proprietary driver 460.73.01-0ubuntu0.20.4.1
> ```
> 
> **Issue**
> Cinnamon enters in fallback mode when there is more than one nvidia graphic card attached and configured screens in xorg.conf.
> a) This same configuration works with Mate Desktop.
> b) The screens are necessary to enable coolbits feature on nvidia driver. If line 7 of (attached) xorg.conf is commented, everything works fine.
> 
> **Steps to reproduce**
> In a machine with two or more nvidia cards, with one monitor attached to one of the cards
> 
>     1. run sudo nvidia-xconfig --enable-all-gpus and edit or create a /etc/X11/xorg.conf file

Why use an obsolete tool to write a broken legacy xorg.conf?

> 
>     2. reboot machine or restart lightdm service
> 
> 
> **Expected behaviour**
> Cinnamon should not enter in fallback mode

It is the expected result due to your broken xorg.conf

(cinnamon:419064): Gdk-ERROR **: 10:06:08.646: The program 'cinnamon' received an X Window System error.
```
This probably reflects a bug in the program.
The error was 'BadMatch (invalid parameter attributes)'.
  (Details: serial 761 error_code 8 request_code 7 (core protocol) minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
```

> 
> **Configuration and logs**
> [xsession-errors.txt](https://github.com/linuxmint/cinnamon/files/6566636/xsession-errors.txt)
> 
> [xorg.conf.txt](https://github.com/linuxmint/cinnamon/files/6566640/xorg.conf.txt)

Try deleting the empty files section

```
Section "Files"
EndSection
```

> 
> [inxi_output.txt](https://github.com/linuxmint/cinnamon/files/6566637/inxi_output.txt)
