### ISSUE TITLE
[Help wanted] Zalgo

### ISSUE THREAD

**Issue by Leopardus4** [linuxmint/cinnamon#10120]
```
 * Cinnamon version 4.8.6
 * Distribution - Linux Mint 20.1
 ```

It was a funny observation.

**Issue**

[Z̪͐a͎͂l͚ͫgͪ̽o̫̪̣ͭ̊̆](https://en.wikipedia.org/wiki/Zalgo_text) is visible over, huh, _many things_.

**Steps to reproduce**
1. Open Firefox (i. e. v88).
2. Go to [this](https://github.com/as-com/_zalgo_/issues/1) site. ~You just opened this issue.~
~(So please don't change title of this issue. Thanks)~
3. Visit [`few`](https://www.wikipedia.org/) [`other`](https://eo.wikipedia.org/wiki/Vikipedio:%C4%88efpa%C4%9Do) [`websites`](https://pl.wikipedia.org/wiki/Wikipedia:Strona_g%C5%82%C3%B3wna).
4. Open history menu.
5. See z̓͒a̦̰̘̪̟̗̞ͨ̌̆͑̋̓ͧl̼̩̖͔ͣ̑̑͐g̊̃o over multiple items in history:
![zalgo](https://user-images.githubusercontent.com/48633054/120043553-73ceb800-c00c-11eb-88ee-ed14c7b20551.png)

**Expected behaviour**
Zalgo shall not cover multiple items.

**Other information**
Provided link makes your history just weird. But please unpack and open this html file:
[x.html.zip](https://github.com/linuxmint/cinnamon/files/6563378/x.html.zip)
...and your browser history will be really hard to read :upside_down_face:  

---

`Help wanted`: Please help me find more places where zalgo produces funny effects :wink: 
_[Zalgo generator](http://lionet.info/the-pony-he-comes/), [zalgo analyzer](https://www.fontspace.com/unicode/analyzer), large zalgo: `s̆̎̆̎̆̎̆̎̆̎̆̎̆̎̆̎̆̎̆̎̆̎̆̎̆̎̆̎̆̎̆̎̆̎̆̎̆̎̆̎̆̎̆̎̆̎̆̎̆̎̆̎̆̎̆̎̆̎̆̎̆̎̆̎̆̎̆̎̆̎̆̎̆̎̆̎̆̎̆̎̆̎̆̎̆̎̆̎̆̎̆̎̆̎̆̎̆̎̆̎̆̎̆̎̆̎̆̎̆̎̆̎̆̎̆̎̆̎̆̎̆̎̆̎̆̎̆̎̆̎`_

Please let me know in case it's a wrong project for this issue.

---

Few experiments later...

Looks like zalgo is problematic in more parts of DE. See below:

- Xed
![obraz](https://user-images.githubusercontent.com/48633054/120043832-feafb280-c00c-11eb-8d73-a96f5dcb555e.png)

- Nemo
![nemo2](https://user-images.githubusercontent.com/48633054/120047294-82b96880-c014-11eb-9c83-d44275029b99.png)

- Nemo, changing name of a file
![nemo2](https://user-images.githubusercontent.com/48633054/120047336-9b298300-c014-11eb-8977-24f90adf6215.png)

- "Recent files" in Cinnamon menu
![recent](https://user-images.githubusercontent.com/48633054/120044380-0754b880-c00e-11eb-92d3-83b5df28eabb.png)

- Gnome system monitor

  Just
  `terminate called after throwing an instance of 'Glib::RegexError'`-ed
  when I `Ctrl+F`-ed zalgo

...and the Oscar goes to:
- Gnome keyring
  I was able to create decorations outside of a window :rofl::
![keyring](https://user-images.githubusercontent.com/48633054/120047119-10488880-c014-11eb-94a6-14e3da750ba6.png)

**Comment by Leopardus4** [comment]
Window preview is amazing! :rofl:
![preview](https://user-images.githubusercontent.com/48633054/120050008-2fe3af00-c01c-11eb-8792-031e712b6a14.png)

**Comment by leigh123linux** [comment]
Don't edit it back otherwise I will close the issue, it fucks up my email client!!!!!

>     2. ~Go to [this](https://github.com/as-com/_zalgo_/issues/1) site~. You just opened this issue.
>        (So please don't change title of this issue. Thanks)

**Comment by NikoKrause** [comment]
I'm here to help. Stop using Zalgo. Flies away.

![Captain Hindsight](https://i.imgur.com/gBVGct6_d.webp?maxwidth=640&shape=thumb&fidelity=medium)
