### ISSUE TITLE
[Q] more on focus stealing

### ISSUE THREAD

**Issue by Lanchon** [linuxmint/cinnamon#10127]
```
 * Cinnamon version (cinnamon --version): Cinnamon 4.4.8
 * Distribution: linux mint 19.3
 * 64 bit
 ```

**Question**

* has window focus handling, especially in what regards focus stealing prevention, been updated since the old cinnamon i am using?

if yes, i will do nothing.
if no, i will report issues i am having and propose ideas for solution.

note that i have already read most if not all project issues regarding focus stealing.

thank you!

**Comment by mtwebster** [comment]
Quite a bit was done and are in the new cinnamon 5.0 release.

See https://github.com/linuxmint/cinnamon/issues/8059 for discussion and links to changes.

**Comment by Lanchon** [comment]
thank you!
