### ISSUE TITLE
Wayland will be supported in Cinnamon 5??

### ISSUE THREAD

**Issue by xzj8b3** [linuxmint/cinnamon#10136]
I'm testing Cinnamon on Fedora 34, it will support Wayland like all the other desktops, won't it? Xorg doesn't even receive updates anymore and it would be interesting to see Cinnamon working on Wayland!

When will be released more or less new version?

**Comment by leigh123linux** [comment]
There wont be any wayland support for cinnamon-5.x.x release.
I expect to release version 5 in a few weeks.

https://copr.fedorainfracloud.org/coprs/leigh123linux/cinnamon_next/builds/

**Comment by xzj8b3** [comment]
> Non ci sarà alcun supporto Wayland per il rilascio di cannella-5.xx.
> Prevedo di rilasciare la versione 5 in poche settimane.
> 
> https://copr.fedorainfracloud.org/coprs/leigh123linux/cinnamon_next/builds/

When will you have support for Wayland?
