### ISSUE TITLE
network applet shows up with NetworkManager disabled

### ISSUE THREAD

**Issue by logan001** [linuxmint/cinnamon#10131]
```
 * Cinnamon version 5.0.1
 * Distribution - Arch,
 * Graphics hardware *and* driver used Nvidia with 455.50.14 driver
 * 64 bit
 * Attach ~/.xsession-errors, or /var/log/syslog
 ```

**Issue**
network applet started to appear with NetworkManager disabled and of course the icon is the one without network. with left click there is an empty popup box and right click->configure i get an almost empty window.
its a good thing that i don't get the popup window that i have no internet connection :)
removing the applet will replace with another applect of network manager that also is almost empty
i'm not sure if its cinnamon new update or some other update trigger this. but i think its mostly cinnamon since i noticed a few changes after update.

**Steps to reproduce**
disable NetworkManger.

**Expected behaviour**
to have network manager applet hidden

P.S.: quick question: is the open file dialog that firefox show handle by firefox or cinnamon (nemo) cause i can't see hidden files. i can see hidden folders but hidden files in ~/ does not show up. and in chromium i can see hidden files too. strange

**Comment by leigh123linux** [comment]
> P.S.: quick question: is the open file dialog that firefox show handle by firefox or cinnamon (nemo) cause i can't see hidden files. i can see hidden folders but hidden files in ~/ does not show up. and in chromium i can see hidden files too. strange

It's gtk3, try

```
gsettings set org.gtk.Settings.FileChooser show-hidden true
```

**Comment by pnoumenon** [comment]
Can confirm. Not exactly a big problem, but that ugly applet icon really stinks up my panel.

**Comment by logan001** [comment]
one year later and this ugly network applet is still there

**Comment by Secret-chest** [comment]
Right click and remove it

**Comment by logan001** [comment]
i did that and then another icon appears. before when network manager was disabled there was no network icon

**Comment by pnoumenon** [comment]
That's the point, when you right-click and remove it, another ugly icon (even uglier in fact, if I might add) takes its place. Before there was no icon at all.

------- Original Message -------

**Comment by tebrobert** [comment]
I do also confirm the issue - I want to remove the Network Manager applet icon and I can't do it without removing the entire Cinnamon desktop environment. Please, how is it possible to remove the Network Manager applet icon from the tray?

**Comment by ntd** [comment]
> Please, how is it possible to remove the Network Manager applet icon from the tray?

From the [ArchLinux wiki](https://wiki.archlinux.org/title/cinnamon#Disable_the_NetworkManager_applet):
```
cp /etc/xdg/autostart/nm-applet.desktop ~/.config/autostart/
echo "X-GNOME-Autostart-enabled=false" >> ~/.config/autostart/nm-applet.desktop
```
Then logout and login to restart the cinnamon session.
