### ISSUE TITLE
Python dist-packages is a Debian convention

### ISSUE THREAD

**Issue by SparkyBluefang** [linuxmint/cinnamon#10135]
#10032 installs a python package in `/usr/lib/python3/dist-packages/`, however, this appears to be a Debian convention and isn't portable to other distributions.

I can work around this in Gentoo's packages, but it might be worth investigating a more distro neutral way to install these files.

**Comment by ItzSwirlz** [comment]
This is normally when we end up using patches, and LM is technically priority. Budgie DE needs some patches to work with Debian and I'm sure it can be ported to other distros. @leigh123linux How's Fedora doing with this? Debian/Ubuntu can't put it in yet because of Bullseye freeze.

**Comment by leigh123linux** [comment]
@ItzSwirlz  I move it to /usr/lib/python3.9/site-packages

https://src.fedoraproject.org/rpms/cinnamon/blob/rawhide/f/cinnamon.spec#_199

**Comment by ItzSwirlz** [comment]
Okay.. so I have no idea how Gentoo packaging works, I've only taken a peak at specs and Arch's PKGBUILD party trick thing but for now, I'll link this PR to https://github.com/gentoo/gentoo/pull/21047

**Comment by mtwebster** [comment]
Does that work? ^

**Comment by SparkyBluefang** [comment]
Yeah, a build parameter seems like a perfectly reasonable approach. Thanks!

**Comment by mtwebster** [comment]
You may not need one - see what python3.get_install_dir() decides, it could be correct already.

**Comment by eli-schwartz** [comment]
Hmm, I thought I'd subscribed to this ticket...

Yeah, the meson python module is generically correct, except not on Debian due to https://github.com/mesonbuild/meson/issues/8739

So this solution seems fine and works for me OOTB.

(I did NOT want an option that I needed to set manually :p because `py_dir=$(python -c "import site; print(site.getsitepackages()[0])")` is not convenient even if passing it to a meson option. Fortunately, `find_installation().get_install_dir()` works great.)

**Comment by SparkyBluefang** [comment]
Also worth noting that Gentoo has separated the concept of build hosts (build tools and their dependencies) and runtime hosts (package build and runtime dependencies), and supports multiple versions of python being installed side-by-side.

So, in the Gentoo world, it's entirely possible for meson, the system default, and Cinnamon to all be using different python installations. It's a bit complicated to explain, but the package system keeps it all self consistent - provided the build system isn't picking its own python target.

So I agree `get_install_dir` is the correct solution for the majority of cases, but Gentoo will also be using the build option :)

**Comment by eli-schwartz** [comment]
I assume gentoo also patches out the shebangs in the scripts then?

**Comment by SparkyBluefang** [comment]
> I assume gentoo also patches out the shebangs in the scripts then?
Yes, the shebangs are dynamically updated though package manager helper utilities. If packages don't do this automatically, they generate QA warnings and need to be fixed. This is even required for build system helper scripts that don't get installed.
