### ISSUE TITLE
No option to set a lockscreen wallpaper?

### ISSUE THREAD

**Issue by RDKRACZ** [linuxmint/cinnamon#10153]
```
 * Cinnamon 4.8.6
   - Please specify if you are using the daily builds PPA
     (https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds).
I don't think so as I installed Cinnamon by apt install cinnamon-desktop
 * Ubuntu Cinnamon 21.04
 * Nvidia GeForce GTX 1070 - driver v460.80
 * 64 bit
 * Attach ~/.xsession-errors, or /var/log/syslog
 No problem I can attach it if it's necessary but I thought it isn't in this case.
```

**Issue**
Seems like Cinnamon uses the same wallpaper for the desktop and the login screen. If there is no option to change this behaviour I would like to make this issue a feature request to make it possible as any other DE I used has this option and it can be useful e.g for people that want to have a photo of their loved ones as the desktop wallpaper and something not so personal as a lockscreen wallpaper.

**Expected behaviour**
Separated wallpaper preferences for the screensaver/lock screen and the desktop.

**Comment by RDKRACZ** [comment]
It looks like this option was present in the past as it can be seen in this video https://youtu.be/OgNUsHwOGXs?t=44

In the video:
<details>

![image](https://user-images.githubusercontent.com/43277609/121676882-78d44280-cab5-11eb-8437-e83b95b8092d.png)


</details>

In Cinnamon 4.8.6 - the "Administration" section is missing a few buttons:
<details>

![image](https://user-images.githubusercontent.com/43277609/121677007-9bfef200-cab5-11eb-84d1-4074c821e13c.png)


</details>

**Comment by mtwebster** [comment]
You're missing the lightdm-settings package.
