### ISSUE TITLE
wmctrl stopped working correctly since cinnamon 5.0 (switches desktop but does not raise window)

### ISSUE THREAD

**Issue by knochenhans** [linuxmint/cinnamon#10150]
```
 * Cinnamon version: Cinnamon 5.0.2
 * Distribution: Arch Linux
 * Graphics hardware: AMD Ryzen 7 4700U with Radeon Graphics (AMD Radeon RX Vega 7), AMDGPU driver
 * 64 bit
 ```

**Issue**
Hi, I’m using wmctrl frequently for switching between windows. After upgrading to Cinnamon 5.0.2 yesterday, wmctrl stopped working correctly: It seems to switch to the target window’s correct workspace but is not raising it correctly. For example, I want to switch to the application ZIM on workspace 10, where currently ZIM and Nemo is running, with Nemo being on top and ZIM being in the background. Running ```wmctrl -a 'ZIM'``` correctly switches to workspace 10 but does **not** raise ZIM to the foreground.

**Steps to reproduce**
Using wmctrl with the -a option to switch to a desktop, raise and focus a specified window.

**Expected behaviour**
wmctrl should not only switch to the correct desktop but also raise the respective window.

**Comment by mtwebster** [comment]
https://github.com/linuxmint/muffin/issues/588
