### ISSUE TITLE
Grouped window list functionality is "present" when switched off

### ISSUE THREAD

**Issue by hlascelles** [linuxmint/cinnamon#10157]
```
❯ cinnamon --version
Cinnamon 4.8.6
Mint 20.1 (Ulyssa)
 ```

**Issue**

Grouped Window funcationality is switched off, but still present in window menus.

![image](https://user-images.githubusercontent.com/299102/121771086-1175cb80-cb65-11eb-92f8-5420886afc78.png)

**Steps to reproduce**

1) Turn off Grouped Windows
2) Reboot just to be sure
3) Open any app and right click on it in taskbar

**Expected behaviour**

Grouped Window functionality should not be present. I *may* be misunderstanding the relationship between grouping and pinning... However this happens if the icon clicked is either pinned or unpinned.

I think this may be part of a larger set of issues to do with Reordering, Dragging, Grouping and Pinning task bar items. eg: https://github.com/linuxmint/cinnamon/issues/10119

**Comment by leigh123linux** [comment]
You have two chrome application  tabs so it appears to working as intended.
