### ISSUE TITLE
Fractional scalling renders UI elements blury and inconsistelty accross physical pixel grid 

### ISSUE THREAD

**Issue by mic-hall** [linuxmint/cinnamon#10158]
```
 * Cinnamon version - 4.8.6
   - Please specify if you are using the daily builds PPA - No
 * Distribution - Linux Mint 20.1 Cinnamon
 * Graphics hardware *and* driver used - AMD Vega 8 aGPU on 27inch 4K display - no graphics drivers
 * 32 or 64 bit - AMD 64bit
 * Attach ~/.xsession-errors, or /var/log/syslog - not applicable
 ```
**Issue**

New factorial scaling functionality enables to use of 160 dpi optimized displays that work best with 150% UI scaling (such as 27 inch 4K displays). However, it seems the implementation for factorial scaling uses integer scaling of 200% to project the desktop the to a larger virtual screen and then somehow reduces the size to fit to the smaller physical pixel grid. However the process renders UI elements that fall in between of this physical pixel grid as blurry and not sharp greatly increasing the eye fatigue. Interestingly it is not possible to demonstrate effects using  screenshot as it takes the grab off the virtual screen and not of the physical screen. 

**Steps to reproduce**

Use HIDPI display, switch on Fractional scaling ( System Settings > Display > Layout ? Fractional scaling > anything other than 100 or 200%. 

**Expected behavior**

UI elements shall remain sharp and do not extend to neighboring pixels. Moving UI elements across the screen shall not change how they are rendered on the pixel grid.

**Comment by J3m5** [comment]
I've experienced the same issue. 
I have a 16" 2560x1600 display and with 125% fractional scaling and user interface scale set to normal, the UI is all blurry.
But I have found that setting the user scale interface option to "Double (Hi-DPI)" and 125% fractional scaling fix the problem.

**Comment by JosephMcc** [comment]
https://github.com/linuxmint/cinnamon/issues/9429
