### ISSUE TITLE
wmctrl -R does not bring windows to the top anymore.

### ISSUE THREAD

**Issue by Zerophase** [linuxmint/cinnamon#10160]
```
 * Cinnamon version: 5.0.2
 * Distribution: Arch
 * 660ti and NVida proprietary.
 * 64 bit
 * [xsession-errors](https://pastebin.com/WccsNu8U)
 ```

**Issue**
When trying to bring Alacritty to the top of the windows stack, with `wmctrl -R "Alacrtitty"` on Cinnamon has stopped working since 5.0.

**Steps to reproduce**
1. Install Alacritty (works for any program too)
2. setup the hotkey for calling the script that pulls Alacritty down.
3. close alacritty with that same hot key, and it closes fine.
4. Click off the window onto another window, and hitting the hot key does not pull alacritty to the top.

**Expected behaviour**
Alacritty comes to the top of the window stack.

**Other information**
Script I'm using:
```bash
if pidof -x "alacritty" > /dev/null
then
	if [[ "$( /bin/xdotool getwindowfocus getwindowname )" == "Alacritty" ]]; then
		wmctrl -c "alacritty"
	else
		wmctrl -R "alacritty"
	fi
else
	/bin/alacritty
fi

**Comment by mtwebster** [comment]
https://github.com/linuxmint/muffin/commit/7f4e5661c80778f37c10e1ef69c814ca00af6ae7
