### ISSUE TITLE
Spelling error

### ISSUE THREAD

**Issue by hans-frogmaster** [linuxmint/cinnamon#10163]
* All Cinnamon versions and MATE, Xfce etc.
 * All Distributions 
 
Thanks for Linux Mint, my favorite operating system.

There is a spelling mistake in the Danish translation of Cinnamon's Wallpaper choice. The translators all concur to use wrong grammar. This error is repeated all over other Linux distributions as well.

The word 'strukket' does not exist in Danish. The correct word is 'strakt' ('stretched'), or with a phrase as in macOS's 'Udfyld skærm' (Fill screen).

Thank You

**Comment by icarter09** [comment]
Thanks. I've corrected the translation to use the correct word and have pushed the change to be reviewed.

**Comment by icarter09** [comment]
The change was reviewed, but not sure if it was accepted.
