### ISSUE TITLE
segfault to do with libnetwork.so

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/cinnamon#10186]
```
 * Cinnamon version (cinnamon --version) 4.8.6
   - Please specify if you are using the daily builds PPA: no.
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 20.1
 * Graphics hardware *and* driver used: Intel; Mesa
 * 32 or 64 bit: 64
 * Attach ~/.xsession-errors, or /var/log/syslog
```
[syslog.txt](https://github.com/linuxmint/cinnamon/files/6738171/syslog.txt)

**Issue**

In my syslog I have:
`cinnamon-settin[2112215]: segfault at 8 ip 00007feca4283740 sp 00007fff56c8bdf0 error 4 in libnetwork.so`

**Steps to reproduce**
Unknown. Possibly disconect from a wifi hotspot - for, that is one thing I did shortly before the error.

**Expected behaviour**

No segfault.

**Other information**

I saw no adverse effects - but I have a script that identifies such errors. That is how I know about the error.

I will provide a stacktrace, [if you tell me how to do so](https://github.com/linuxmint/mintreport/issues/73).

**Comment by leigh123linux** [comment]
Feel free to reopen once you have proper steps to reproduce and can provide a stacktrace.

https://wiki.archlinux.org/title/Core_dump#Examining_a_core_dump

**Comment by LinuxOnTheDesktop** [comment]
Thanks, but you need to do a bit more to help me to help you. Just what do you need? (That wiki page describes how to do more than one thing.) Also, do I need some special 'debugging' version(s) of software to be installed?
