### ISSUE TITLE
Adding an applet directly after removing it, gives an Warning

### ISSUE THREAD

**Issue by jonath92** [linuxmint/cinnamon#10181]
```
- cinnamon version 4.8.6 (no daily build)
- Distribution: Mint 20.1 (64 bit)
```

**Issue**
It is probably not so problematic for users but it can confuse applet developers. When you remove an applet and 
directly after add the applet again, it is shown the following warning message: 

```
Something went wrong while loading weather@mockturtl. Please make sure you are using the latest version, and then report the issue to its developer
```
I have tried with the radio, weather and Cinnamenu applets - so it is most likely not the fault of the applet developers. 

![image](https://user-images.githubusercontent.com/49979415/123549717-74bd4b80-d76a-11eb-813f-808db23df0ce.png)

**Steps to reproduce**
1. Open Applets Menu
2. Add an applet 
2. Remove the same Applet
3. Add the Applet Again

**Expected behaviour**
There shouldn't be a warning ...

**Other information**
This can be reproduced on a fresh installation

**Comment by icarter09** [comment]
This has been fixed https://github.com/linuxmint/cinnamon/pull/10071
