### ISSUE TITLE
Network Applet width

### ISSUE THREAD

**Issue by barongi** [linuxmint/cinnamon#10185]
Cinnamon version 5.0.3

When plugging in a TP-Link Archer U1 USB WIFI dongle, the network applet shows the whole name of both the dongle and the internal Qualcomm network card, making the applet width really wide.

![Network Applet Bug](https://user-images.githubusercontent.com/60045663/123745527-13f05900-d8b9-11eb-93c9-75dd6b85da8b.png)

**Comment by mtwebster** [comment]
We already have that commit. We just need to add more to the ignore list.

**Comment by leigh123linux** [comment]
That commit removes the ignore list and changes the naming method, see

https://github.com/GNOME/gnome-shell/commit/490206b5b23649017859b9cb6d534cce1855d6dd#diff-a21c08e9ee726447cc7bceb19c98676323db5d4193562999a1f0c7312011fa43L162
