### ISSUE TITLE
cinnamon-settings Segmentation fault

### ISSUE THREAD

**Issue by draganbjedov** [linuxmint/cinnamon#10195]
* Cinnamon 5.0.4
   - Using https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds
 * Distribution - Ubuntu 20.04
 * NVidia
 * 64 bit

**Issue**
cinnamon-settings crash with Segmentation fault
```
$ cinnamon-settings
Segmentation fault (core dumped)
```
It crashes even if I try to get version
```
$ cinnamon-settings --version
Segmentation fault (core dumped)
```

**Steps to reproduce**
Run from terminal cinnamon-settings

**Expected behaviour**

Cinnamon settings started

**Other information**
It works when started with `sudo` but then some settings are empty.

**Comment by mtwebster** [comment]
There's not much to do without more info - can you provide anything more? A trace or coredump?

**Comment by draganbjedov** [comment]
@mtwebster  Here is the core dump:
[core.tar.gz](https://github.com/linuxmint/cinnamon/files/6775869/core.tar.gz)

**Comment by sgilissen** [comment]
Just to add here that I have the same issue on 2 systems. 
One of them is on Fedora 32, the other on Fedora 33.

This is a core dump from the Fedora 32 machine
[cinnamondump.tar.gz](https://github.com/linuxmint/cinnamon/files/6806599/cinnamondump.tar.gz)

**Comment by leigh123linux** [comment]
@sgilissen I have no f33 installation to process the coredump so it's useless.
Have you been messing around with python/pip?

**Comment by sgilissen** [comment]
> @sgilissen I have no f33 installation to process the coredump so it's useless.
> Have you been messing around with python/pip?

Only in virtualenvs as I'm a Python dev. The core Python install is untouched, on both machines.

**Comment by sgilissen** [comment]
> Can you run cinnamon-settings in a terminal and post the output.

Sure! 

`[13:33:14][sgilissen@chiron] ~:$ cinnamon-settings

(cinnamon-settings.py:56799): Gtk-WARNING **: 13:33:17.406: Theme parsing error: colors.css:71:44: Invalid number for color value

(cinnamon-settings.py:56799): Gtk-WARNING **: 13:33:17.406: Theme parsing error: colors.css:72:44: Invalid number for color value

(cinnamon-settings.py:56799): Gtk-WARNING **: 13:33:17.406: Theme parsing error: colors.css:74:53: Invalid number for color value

(cinnamon-settings.py:56799): Gtk-WARNING **: 13:33:17.406: Theme parsing error: colors.css:75:53: Invalid number for color value

(cinnamon-settings.py:56799): Gtk-WARNING **: 13:33:17.406: Theme parsing error: colors.css:76:56: Invalid number for color value

(cinnamon-settings.py:56799): Gtk-WARNING **: 13:33:17.406: Theme parsing error: colors.css:77:65: Invalid number for color value
Segmentation fault (core dumped)
[13:33:18][sgilissen@chiron] ~:$ 

`

**Comment by mtwebster** [comment]
Can you verify for me the python in use?
```
which python3
```
Also, what version of python3-pil is installed? I haven't filled out the full coredump yet but it seems like it could be related to that python library.

**Comment by draganbjedov** [comment]
For me it is:
```
$ which python3
/usr/bin/python3

$ python3 --version
Python 3.8.10

$ apt list python3-pil
Listing... Done
python3-pil/focal-updates,focal-security,focal-updates,now 7.0.0-4ubuntu0.4 amd64 [installed]
N: There is 1 additional version. Please use the '-a' switch to see it
```

**Comment by mtwebster** [comment]
I'd like to reset any background settings and try again -
 
This will save the current settings:
```
dconf dump /org/cinnamon/desktop/background/  > saved # don't leave out the trailing /
```
then:
```
gsettings reset-recursively org.cinnamon.desktop.background
```

**Comment by sgilissen** [comment]
> Can you verify for me the python in use?
> 
> ```
> which python3
> ```
> 
> Also, what version of python3-pil is installed? I haven't filled out the full coredump yet but it seems like it could be related to that python library.
```
[15:32:01][sgilissen@chiron] ~:$ python3 --version
Python 3.8.10
[15:32:04][sgilissen@chiron] ~:$ which python
/usr/bin/python


[15:32:56][sgilissen@chiron] ~:$ python3
Python 3.8.10 (default, May  4 2021, 00:00:00) 
[GCC 10.2.1 20201125 (Red Hat 10.2.1-9)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import PIL
>>> PIL.__version__
'8.3.1'
```



> I'd like to reset any background settings and try again -
> 
> This will save the current settings:
> 
> ```
> dconf dump /org/cinnamon/desktop/background/  > saved # don't leave out the trailing /
> ```
> 
> then:
> 
> ```
> gsettings reset-recursively org.cinnamon.desktop.background
> ```

```
[15:43:09][sgilissen@chiron] ~:$ dconf dump /org/cinnamon/desktop/background/
[/]
picture-options='zoom'
picture-uri='file:///home/sgilissen/Pictures/goldsaucer.png'

[slideshow]
delay=15
image-source='directory:///home/sgilissen/Pictures'
[15:43:20][sgilissen@chiron] ~:$ 

[15:43:20][sgilissen@chiron] ~:$ gsettings reset-recursively org.cinnamon.desktop.background
[15:45:03][sgilissen@chiron] ~:$ cinnamon-settings

(cinnamon-settings.py:65142): Gtk-WARNING **: 15:45:10.187: Theme parsing error: colors.css:71:44: Invalid number for color value

(cinnamon-settings.py:65142): Gtk-WARNING **: 15:45:10.187: Theme parsing error: colors.css:72:44: Invalid number for color value

(cinnamon-settings.py:65142): Gtk-WARNING **: 15:45:10.187: Theme parsing error: colors.css:74:53: Invalid number for color value

(cinnamon-settings.py:65142): Gtk-WARNING **: 15:45:10.187: Theme parsing error: colors.css:75:53: Invalid number for color value

(cinnamon-settings.py:65142): Gtk-WARNING **: 15:45:10.187: Theme parsing error: colors.css:76:56: Invalid number for color value

(cinnamon-settings.py:65142): Gtk-WARNING **: 15:45:10.187: Theme parsing error: colors.css:77:65: Invalid number for color value
Segmentation fault (core dumped)
[15:45:10][sgilissen@chiron] ~:$ 


```


Also, @draganbjedov: my apologies, I didn't want to hijack your thread. I just think it may be the same issue, and all seems to point that way since we basically have the same versions of Python (and possibly PIL/Pillow?)

**Comment by draganbjedov** [comment]
> Ok, can you check if the following succeeds in a python3 session:
> 
> ```
> >>> from PIL import _imagingft
> ```
> 
> Thanks

```
$ python3
Python 3.8.10 (default, Jun  2 2021, 10:49:15) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from PIL import _imagingft
>>> 
```

**Comment by mtwebster** [comment]
Ok I managed to reproduce this by forcibly removing my distribution version of python3-pil(low) and reinstalling it via pip3.

@draganbjedov You're on ubuntu and your system version of pil is correct - 7.0.0, yet if you look at your PIL.__version__ it's 8.3.0 (maybe a not-quite-current pip version?)

@sgilissen You look like you may be using the pip version as well - 8.3.1, whereas the f33 version is 7.2 (I think?)

Can you guys remove your pip versions (assuming you have them installed) and try this?

**Comment by draganbjedov** [comment]
> Ok I managed to reproduce this by forcibly removing my distribution version of python3-pil(low) and reinstalling it via pip3.
> 
> @draganbjedov You're on ubuntu and your system version of pil is correct - 7.0.0, yet if you look at your PIL.__ version __ it's 8.3.0 (maybe a not-quite-current pip version?)
> 
> @sgilissen You look like you may be using the pip version as well - 8.3.1, whereas the f33 version is 7.2 (I think?)
> 
> Can you guys remove your pip versions (assuming you have them installed) and try this?
I have uninstalled Pillow 8.3.0 using pip.
```
pip uninstall Pillow
```
**Now it works!** Thanks a lot @mtwebster 

And PIL version is 7.0.0
```
$ python3
Python 3.8.10 (default, Jun  2 2021, 10:49:15) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import PIL
>>> PIL.__version__
'7.0.0'
>>> 
```

**Comment by leigh123linux** [comment]
> > Can you verify for me the python in use?
> > ```
> > which python3
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Also, what version of python3-pil is installed? I haven't filled out the full coredump yet but it seems like it could be related to that python library.
> 
> ```
> [15:32:01][sgilissen@chiron] ~:$ python3 --version
> Python 3.8.10
> [15:32:04][sgilissen@chiron] ~:$ which python
> /usr/bin/python
> 
> 
> [15:32:56][sgilissen@chiron] ~:$ python3
> Python 3.8.10 (default, May  4 2021, 00:00:00) 
> [GCC 10.2.1 20201125 (Red Hat 10.2.1-9)] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import PIL
> >>> PIL.__version__
> '8.3.1'
> ```
> 
> > I'd like to reset any background settings and try again -
> > This will save the current settings:
> > ```
> > dconf dump /org/cinnamon/desktop/background/  > saved # don't leave out the trailing /
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > then:
> > ```
> > gsettings reset-recursively org.cinnamon.desktop.background
> > ```
> 
> ```
> [15:43:09][sgilissen@chiron] ~:$ dconf dump /org/cinnamon/desktop/background/
> [/]
> picture-options='zoom'
> picture-uri='file:///home/sgilissen/Pictures/goldsaucer.png'
> 
> [slideshow]
> delay=15
> image-source='directory:///home/sgilissen/Pictures'
> [15:43:20][sgilissen@chiron] ~:$ 
> 
> [15:43:20][sgilissen@chiron] ~:$ gsettings reset-recursively org.cinnamon.desktop.background
> [15:45:03][sgilissen@chiron] ~:$ cinnamon-settings
> 
> (cinnamon-settings.py:65142): Gtk-WARNING **: 15:45:10.187: Theme parsing error: colors.css:71:44: Invalid number for color value
> 
> (cinnamon-settings.py:65142): Gtk-WARNING **: 15:45:10.187: Theme parsing error: colors.css:72:44: Invalid number for color value
> 
> (cinnamon-settings.py:65142): Gtk-WARNING **: 15:45:10.187: Theme parsing error: colors.css:74:53: Invalid number for color value
> 
> (cinnamon-settings.py:65142): Gtk-WARNING **: 15:45:10.187: Theme parsing error: colors.css:75:53: Invalid number for color value
> 
> (cinnamon-settings.py:65142): Gtk-WARNING **: 15:45:10.187: Theme parsing error: colors.css:76:56: Invalid number for color value
> 
> (cinnamon-settings.py:65142): Gtk-WARNING **: 15:45:10.187: Theme parsing error: colors.css:77:65: Invalid number for color value
> Segmentation fault (core dumped)
> [15:45:10][sgilissen@chiron] ~:$ 
> ```
> 
> Also, @draganbjedov: my apologies, I didn't want to hijack your thread. I just think it may be the same issue, and all seems to point that way since we basically have the same versions of Python (and possibly PIL/Pillow?)

It looks like local pil is being used.

```
[leigh@mpd Downloads]$ gdb -c cinnamonsettings.dump
GNU gdb (GDB) Fedora 10.2-3.fc34
Copyright (C) 2021 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word".

warning: Can't open file /usr/bin/python3.8 during file-backed mapping note processing

warning: Can't open file /home/sgilissen/.local/lib/python3.8/site-packages/Pillow.libs/libpng16-1d32fd47.so.16.37.0 during file-backed mapping note processing

warning: Can't open file /home/sgilissen/.local/lib/python3.8/site-packages/Pillow.libs/libharfbuzz-2c40391e.so.0.20801.0 during file-backed mapping note processing

warning: Can't open file /home/sgilissen/.local/lib/python3.8/site-packages/Pillow.libs/libfreetype-d0c4c5c9.so.6.17.4 during file-backed mapping note processing

warning: Can't open file /home/sgilissen/.local/lib/python3.8/site-packages/PIL/_imagingft.cpython-38-x86_64-linux-gnu.so during file-backed mapping note processing

warning: Can't open file /usr/lib64/python3.8/lib-dynload/_json.cpython-38-x86_64-linux-gnu.so during file-backed mapping note processing

warning: Can't open file /home/sgilissen/.local/lib/python3.8/site-packages/Pillow.libs/libXdmcp-e15573e7.so.6.0.0 during file-backed mapping note processing

warning: Can't open file /home/sgilissen/.local/lib/python3.8/site-packages/Pillow.libs/libXau-312dbc56.so.6.0.0 during file-backed mapping note processing

warning: Can't open file /home/sgilissen/.local/lib/python3.8/site-packages/Pillow.libs/liblzma-99449165.so.5.2.5 during file-backed mapping note processing

warning: Can't open file /home/sgilissen/.local/lib/python3.8/site-packages/Pillow.libs/libxcb-2dfad6c3.so.1.1.0 during file-backed mapping note processing

warning: Can't open file /home/sgilissen/.local/lib/python3.8/site-packages/Pillow.libs/libtiff-102594ad.so.5.7.0 during file-backed mapping note processing

warning: Can't open file /home/sgilissen/.local/lib/python3.8/site-packages/Pillow.libs/libz-b8b1b7c1.so.1.2.11 during file-backed mapping note processing

warning: Can't open file /home/sgilissen/.local/lib/python3.8/site-packages/Pillow.libs/libopenjp2-f0612b30.so.2.4.0 during file-backed mapping note processing

warning: Can't open file /home/sgilissen/.local/lib/python3.8/site-packages/Pillow.libs/libjpeg-ba7bf5af.so.9.4.0 during file-backed mapping note processing

warning: Can't open file /home/sgilissen/.local/lib/python3.8/site-packages/PIL/_imaging.cpython-38-x86_64-linux-gnu.so during file-backed mapping note processing
```

**Comment by leigh123linux** [comment]
> No problem @sgilissen. Looks like same issue.
> For me after reset background settings, same issue. Core dump without any print.
> 
> ```
> [/]
> picture-options='zoom'
> picture-uri='file:///usr/share/backgrounds/linuxmint-sonya/nfeans_street_lights.jpg'
> 
> [slideshow]
> delay=15
> image-source='xml:///usr/share/cinnamon-background-properties/linuxmint-sonya.xml'
> slideshow-enabled=true
> ```
> 
> May PIL version is 8.3.0
> 
> ```
> >>> import PIL
> >>> PIL.__version__
> '8.3.0'
> ```
> 
> I don't know does this makes any difference but my `PYTHONPATH` is set to:
> 
> ```
> $ echo $PYTHONPATH
> /opt/ros/noetic/lib/python3/dist-packages
> ```

And the same for you.

```
warning: Can't open file /usr/bin/python3.8 during file-backed mapping note processing

warning: Can't open file /home/bjedov/.local/lib/python3.8/site-packages/Pillow.libs/libpng16-1d32fd47.so.16.37.0 during file-backed mapping note processing

warning: Can't open file /home/bjedov/.local/lib/python3.8/site-packages/Pillow.libs/libharfbuzz-2c40391e.so.0.20801.0 during file-backed mapping note processing

warning: Can't open file /home/bjedov/.local/lib/python3.8/site-packages/Pillow.libs/libfreetype-d0c4c5c9.so.6.17.4 during file-backed mapping note processing

warning: Can't open file /home/bjedov/.local/lib/python3.8/site-packages/PIL/_imagingft.cpython-38-x86_64-linux-gnu.so during file-backed mapping note processing

warning: Can't open file /usr/lib/python3.8/lib-dynload/_json.cpython-38-x86_64-linux-gnu.so during file-backed mapping note processing

warning: Can't open file /home/bjedov/.local/lib/python3.8/site-packages/Pillow.libs/libXdmcp-e15573e7.so.6.0.0 during file-backed mapping note processing

warning: Can't open file /home/bjedov/.local/lib/python3.8/site-packages/Pillow.libs/libXau-312dbc56.so.6.0.0 during file-backed mapping note processing

warning: Can't open file /home/bjedov/.local/lib/python3.8/site-packages/Pillow.libs/liblzma-99449165.so.5.2.5 during file-backed mapping note processing

warning: Can't open file /home/bjedov/.local/lib/python3.8/site-packages/Pillow.libs/libxcb-2dfad6c3.so.1.1.0 during file-backed mapping note processing

warning: Can't open file /home/bjedov/.local/lib/python3.8/site-packages/Pillow.libs/libtiff-102594ad.so.5.7.0 during file-backed mapping note processing

warning: Can't open file /home/bjedov/.local/lib/python3.8/site-packages/Pillow.libs/libz-b8b1b7c1.so.1.2.11 during file-backed mapping note processing

warning: Can't open file /home/bjedov/.local/lib/python3.8/site-packages/Pillow.libs/libopenjp2-f0612b30.so.2.4.0 during file-backed mapping note processing

warning: Can't open file /home/bjedov/.local/lib/python3.8/site-packages/Pillow.libs/libjpeg-ba7bf5af.so.9.4.0 during file-backed mapping note processing

warning: Can't open file /home/bjedov/.local/lib/python3.8/site-packages/PIL/_imaging.cpython-38-x86_64-linux-gnu.so during file-backed mapping note processing
```

**Comment by sgilissen** [comment]
Can confirm, it all works now. Thanks!

**Comment by LinuxOnTheDesktop** [comment]
I had the same problem just now - after running the following commands, which try to update Python packages. I thought that the commands had altered no package but perhaps they did.

```
sudo -H pip3 install --upgrade pip
sudo -H pip list \
	--disable-pip-version-check\
	--format=freeze \
	--local \
	--no-color \
	--outdated \
	| grep -v '^\-e' \
	| cut -d = -f 1  \
	| xargs -n1 sudo -H pip install \
	--disable-pip-version-check \
	--no-color \
	--progress-bar=pretty \
	-q -q -q \
	-U
```


I found that `sudo -H pip uninstall Pillow` fixed the problem.
