### ISSUE TITLE
Unexpected window focus behaviour with windows launched by keyboard shortcuts

### ISSUE THREAD

**Issue by ramo-j** [linuxmint/cinnamon#10192]
```
* Cinnamon 5.0.3
* Fedora 34
* nvidia MX 150 - Driver Version: 465.31
* 64 bit
```

**Issue**

When using keyboard shortcuts to launch windowed applications, instances after the first do not gain window focus at launch.

**Steps to reproduce**

* Configure a keyboard shortcut to launch a windowed application
** used `Super + C` to launch `lxterminal --geometry=160x40`
* Press shortcut to launch application
* Move to another workspace
* Press shortcut to launch application -> Second instance does not have window focus

**Expected behaviour**

Second launched application should have window focus. 

**Other information**

This appears to be a regression as it only appeared after a recent upgrade from Fedora 32 with cinnamon package version `cinnamon-session-4.6.2-1.fc32.x86_64`

Window focus settings (click, sloppy, mouse and smart, strict) appear to have no effect.

**Comment by icarter09** [comment]
Cinnamon 5.0.4 daily builds
Mint 20.1 64bit

I'm not able to reproduce this issue. Second launched application has window focus as expected.

**Comment by LinuxOnTheDesktop** [comment]
I (another user) see this behaviour after updating to Mint 20.2 (Cinnamon 5.0.4). I can reproduce it as follows.

1. Launch a terminal (any which way).
2. Get a Nemo window focused and taking up most or all of the screen.
3. Launch a terminal (I am using xfce4-terminal) using its assigned keyboard shortcut.

The result - a newly launched but not immediately visible terminal - is not what the user expects.

**Comment by mtwebster** [comment]
This seems to happen with xfce4- and lxterminal but not gnome-terminal or tilix. Can you do the following and re-test?
```
gsettings set org.cinnamon demands-attention-passthru-wm-classes "['gnome-screenshot', 'lxterminal', 'xfce4-terminal']"
```

**Comment by LinuxOnTheDesktop** [comment]
@mtwebster 

Marvellous: that gsettings command seems to fix the problem.

**Comment by mtwebster** [comment]
I'm going to add these exceptions to that setting permanently. I can reproduce this in mate also (metacity and marco) though not in xfce4.

In previous cinnamon versions we allowed all windows (with some exceptions) to be brought to the top and focused, but this is also wrong for a number of other programs. Now we block by default but will allow some exceptions (those in that list). You can reproduce this undesirable behavior in cinnamon 4.8 by turning on 'prevent windows which require attention from stealing focus.' in window settings.

What's 'correct' and what programs have come to expect can vary quite a bit when it comes to focus handling. so I'd rather do a surgical fix like this for now.

**Comment by LinuxOnTheDesktop** [comment]
I wonder though whether _everything_ launched via keyboard shortcut needs to override the new default behaviour. For if I use a keyboard shortcut to e.g. launch Firefox when Firefox is running already - which has the effect of creating a new Firefox window - then I expect the new window to be focused immediately, but at present that does not happen.

**Comment by mtwebster** [comment]
Yes you're right - this is keyboard launching-specific. I can confirm firefox does it, yet chromium is fine. The problem is I don't have a way of tying a program window opening with the fact that a shortcut launched it, so the danger is allowing some program that you want to focus when you launch with a shortcut, but maybe that same program could make a new window on its own later on - some notification window - and you *don't* want that to grab focus.

I added firefox to this list also.
