### ISSUE TITLE
Wrong button layout order.

### ISSUE THREAD

**Issue by M4c4k** [linuxmint/cinnamon#10199]
Linux Mint 20.2 Cinnamon

**Issue**
The left button layout order is wrong. It should be "button_layout: close,minimize,maximize:", but is "close,maximize,minimize".

![button_layout](https://user-images.githubusercontent.com/67242036/125081503-5f2f1680-e0c6-11eb-8b8f-1c769f99fb47.png)

**Comment by mtwebster** [comment]
This was deliberate: https://github.com/linuxmint/cinnamon/commit/a895babecf72db544c33e54b0d8a64d1df41dde1 - see the linked issue there.
