### ISSUE TITLE
Window list entry disappears when launching applications with keyboard shortcut

### ISSUE THREAD

**Issue by JackTemaki** [linuxmint/cinnamon#10193]
```
 * Cinnamon version: 5.0.4
 * Distribution - Arch
 * Nvidia 1060 GTX - driver version 465.31 
 * 64 bit
 * ~/.xsession-errors - https://gist.github.com/JackTemaki/e62bad4d4c4e4953ed9418b36fda20a2
 ```

**Issue**
after launching an application via keyboard shortcut (e.g. xfce4-terminal via ctrl+arl+T) the following happens:
 - the application is launched without focus
 - a blinking window list entry appears

then when clicking on the blinking window list entry or selecting the window via alt+tab:
 - the application gets the focus, but the window list entry disappears

This only happens when launching applications via keyboard shortcut, all other methods of starting an application work fine.

**Steps to reproduce**
 - open an application (e.g. xfce4-terminal)
 - click on the desktop to change focus
 - open the same application (e.g. xfce4-terminal) with a keyboard shortcur
 - click on the newly created window list entry

**Expected behaviour**
 - the window list entry does not disappear
 - the application directly has the focus (#10192)

**Configuration info, if applicable**
Configuration for window-list:
```
{
    "section1": {
        "type": "section",
        "description": "Behavior"
    },
    "show-all-workspaces": {
        "type": "switch",
        "default": false,
        "description": "Show windows from all workspaces",
        "value": false
    },
    "enable-alerts": {
        "type": "switch",
        "default": true,
        "description": "Show an alert in the window list when a window from another workspace requires attention",
        "value": true
    },
    "enable-scrolling": {
        "type": "switch",
        "default": false,
        "description": "Enable mouse-wheel scrolling in the window list",
        "value": false
    },
    "reverse-scrolling": {
        "type": "switch",
        "default": false,
        "description": "Reverse the direction of mouse-wheel scrolling in the window list",
        "dependency": "enable-scrolling",
        "value": false
    },
    "left-click-minimize": {
        "type": "switch",
        "default": true,
        "description": "Left click to minimize window",
        "value": true
    },
    "middle-click-close": {
        "type": "switch",
        "default": true,
        "description": "Middle click to close window",
        "value": true
    },
    "section2": {
        "type": "section",
        "description": "Display"
    },
    "buttons-use-entire-space": {
        "type": "switch",
        "default": false,
        "description": "Window buttons can have different sizes and use the entire space available",
        "value": false
    },
    "window-preview": {
        "type": "switch",
        "default": true,
        "description": "Show window thumbnails on hover",
        "value": true
    },
    "window-preview-show-label": {
        "type": "switch",
        "default": true,
        "description": "Show title above thumbnail",
        "dependency": "window-preview",
        "value": true
    },
    "window-preview-scale": {
        "type": "radiogroup",
        "default": 1,
        "description": "Thumbnail size",
        "options": {
            "Small": 0.75,
            "Medium": 1,
            "Large": 1.25,
            "Largest": 1.5
        },
        "dependency": "window-preview",
        "value": 1
    },
    "last-window-order": {
        "type": "generic",
        "default": "",
        "value": "75497488::83886083::83886181::58741114::106954759::106999031"
    },
    "__md5__": "5ef6c9311df5af19c26eced1327c8c40"
}
```

**Comment by JackTemaki** [comment]
It seems I was slow in writing, duplicate with #10192

**Comment by icarter09** [comment]
Could you provide a video of this occurring? I'm not able to reproduce the issue, but want to make sure I'm performing the correct steps. Thanks.

**Comment by JackTemaki** [comment]
> Could you provide a video of this occurring? I'm not able to reproduce the issue, but want to make sure I'm performing the correct steps. Thanks.

I am sorry, it seemed I missed a condition for this (I am doing this every day and forgot about this):

 - One window of the application has to exist in another workspace
 
 So to reproduce this again I opened xfce4-terminal once, moved it to a different workspace (lets say workspace 2), and then opened xfce4-terminal via keyboard shortcut in workspace 1. Then the window list entry disappears.

**Comment by JackTemaki** [comment]
@icarter09 What is the preferred way here to share a video?

**Comment by icarter09** [comment]
Just whatever works best for you is fine. Personally, I have found [Peek](https://github.com/phw/peek) to work pretty well.

**Comment by JackTemaki** [comment]
> Just whatever works best for you is fine

Then I just use a WeTransfer link: https://we.tl/t-sbfoQSWp8r

This also shows the incorrect focus behavior mentioned in #10192

**Comment by icarter09** [comment]
Looks like WeTransfer is requiring me to sign up for an account. Can you attach the file here? Thanks.

**Comment by JackTemaki** [comment]
I honestly did not know you can just drag&drop some video files here... 

https://user-images.githubusercontent.com/10742135/124630287-92816380-de82-11eb-82f8-86b8f9ebc18a.mp4

**Comment by icarter09** [comment]
Thanks for the video. I'm still not able to reproduce the issue and did add in the extra step of making sure one window of the application pre-exists and is out of focus.

**Comment by JackTemaki** [comment]
I gave debugging it on my own a shot, and found out the following problems:

If I revert this change: https://github.com/linuxmint/cinnamon/commit/28c2254735b9755133f18de6cabc1f4ac806756f
the window list entry no longer disappears.

So the following happens (for the `AppMenuButton` in the window-list applet):
 - `this.alert = alert || metaWindow.is_demanding_attention() || metaWindow.is_urgent();` evaluates to true,
     because for whatever reason `metaWindow.is_demanding_attention()` is True for windows opened via keyboard shortcuts.
 - when I click on the (blinking, because of the alert) window list entry or the window itself, it gets into focus, then `onFocus()` gets called:
 
```javascript
    onFocus() {
        if (this._hasFocus()) {
            this.actor.add_style_pseudo_class('focus');
            this.actor.remove_style_class_name("window-list-item-demands-attention");
            this.actor.remove_style_class_name("window-list-item-demands-attention-top");
            this._needsAttention = false;

            if (this.alert) {
                this.destroy();
                this._windows.splice(this._windows.indexOf(this), 1);
            }
        } else {
            this.actor.remove_style_pseudo_class('focus');
        }
    }
```
 - because the AppMenuButton was created with `this.alert` as True, the entry will be destroyed (if I remove the alert part the entry is not destroyed)
 
 So my Bug is caused by two errors:
  - windows via keyboard shortcut are not launched with focus, but are demanding attention, which should be the problem in #10192 
  - because of the recent changes, the `AppMenuButton` will be in "alert" state, and thus deleted when getting the focus
  
  I would guess there is nothing directly wrong in the Applet, and when #10192 is fixed, this problem here is solved as well.
