### ISSUE TITLE
Power applet doesn't show battery status

### ISSUE THREAD

**Issue by NoXPhasma** [linuxmint/cinnamon#10194]
```
 * Cinnamon 5.0.4
 * Distribution - Arch Linux
 * Nvidia GTX 1080 470.42.01
 * 64 bit
 ```
 [xsession-errors.txt](https://github.com/linuxmint/cinnamon/files/6769959/xsession-errors.txt)

**Issue**
The power applet doesn't show anything, even upower shows the battery status. It worked fine in Cinnamon  4.x

**Steps to reproduce**
Attach a battery powered device and add the power applet to the panel.

**Expected behaviour**
Upower applet should show the battery status

**Other information**
<details><summary>upower -d output</summary>

> Device: /org/freedesktop/UPower/devices/gaming_input_gip0x0
>   native-path:          gip0.0
>   model:                Microsoft X-Box One pad
>   power supply:         no
>   updated:              Di 06 Jul 2021 14:18:03 CEST (20 seconds ago)
>   has history:          yes
>   has statistics:       yes
>   gaming-input
>     rechargeable:        yes
>     warning-level:       none
>     battery-level:       unknown
>     percentage:          50% (should be ignored)
>     icon-name:          'battery-good-charging-symbolic'
>   History (charge):
>     1625573878	50,000	pending-charge
>     1625573878	0,000	unknown
>   History (rate):
>     1625573878	0,000	unknown
> 
> Device: /org/freedesktop/UPower/devices/DisplayDevice
>   power supply:         no
>   updated:              Di 06 Jul 2021 14:17:58 CEST (25 seconds ago)
>   has history:          no
>   has statistics:       no
>   unknown
>     warning-level:       none
>     percentage:          0%
>     icon-name:          'battery-missing-symbolic'
> 
> Daemon:
>   daemon-version:  0.99.12
>   on-battery:      no
>   lid-is-closed:   no
>   lid-is-present:  no
>   critical-action: PowerOff

</details>

**Comment by mtwebster** [comment]
Can you be more specific about what sort of device this is? In upower can you provide what the 'BatteryLevel' property reports for this device?

**Comment by NoXPhasma** [comment]
It is the XBOX One S Gamepad and the driver is [xone](https://github.com/medusalix/xone). We've just could figured out that it is an issue in how xone reports it in the latest version, rather than the applet of Cinnamon in 5.0 (was just a timely coincidence).

Sorry for the noise.
