### ISSUE TITLE
Allow to select system wide colorscheme that other programs could use

### ISSUE THREAD

**Issue by ghost** [linuxmint/cinnamon#10197]
For people who like to have the same colorscheme in every program, in Themes there could be a way to select a colorscheme which would be saved to a file and other programs would be able to use the colorscheme by having an option to use the system theme.

Different programs need different number of colors for example vscode may not use the same number of colors as a terminal. But I'm sure something can be thought, for example use a high number of colors per colorscheme and let each program pick the first x number of colors they need from the file though there is probably some better option.

**Comment by fredcw** [comment]
I think what you're talking about is a new linux wide theming standard that would have to be adopted by all linux apps and desktops. This isn't something Linux Mint could do by itself.
