### ISSUE TITLE
Inhibition of power-management: various malfunctions in various players, including a strange one in Lollypop

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/cinnamon#10191]
```
 * Cinnamon version (cinnamon --version) 4.8.6
   - Please specify if you are using the daily builds PPA: no
 * Distribution - Mint 20.1
 * Graphics hardware *and* driver used: Intel; Mesa
 * 32 or 64 bit: 64
 ```

**Issue**

*Lollypop*

By design the Lollypop music player inhibits power-management - power-management in the form of screen-dimming and the turning off of the screen - only when the application is full-screen and/or the application is playing a file. _Sometimes_, that is what happens, i.e., power-management is inhibited in only those circumstances. At other times, power-management is inhibited whenever Lollypop is running (which is a problem because serious battery drain can be the result). The developer of Lollypop thinks ([see here](https://gitlab.gnome.org/World/lollypop/-/issues/2801)) that this is not a Lollypop problem. If actually it is a Lollypop problem, then it would be good to know what the problem is.

*VLC and Mpv, and Xplayer*

I find that the VLC and Mpv music players never inhibit power-management _at all_.

I find that Xplayer inhibits power-management _properly_.

**Steps to reproduce**

(1) For VLC and Mpv: (1a) run the application at issue; (1b) play either a song or a video; (ic) observe (via the Cinnamon power applet or in another way) that power-management is not inhibited.

(2) For Lollypop. (2a) run the application; (2b) observe (via the Cinnamon power applet or in another way) that power-management is inhibited, even though nothing is playing and the application is not full-screen.

**Expected behaviour**

All of these apps should inhibit power-management only when they are either full-screen or else playing something. I take it that Mint cannot make all player applications work well on Cinnamon; but the case of the Lollypop player - which works as it should, power-wise, *intermittently* - seems to suggest some sort of bug and indeed possibly a bug that is within Cinnamon.

**Other information**

Here is some relevant terminal output. That output has to do with Lollypop. The output was produced at a time when: Lollypop was running; Lollypop should not have been doing any inhibiting; Lollypop nevertheless was inhibiting.

```
$ systemd-inhibit --list
WHO            UID  USER     PID     COMM            WHAT                                                     WHY                                       MODE 
NetworkManager 0    root     3186022 NetworkManager  sleep                                                    NetworkManager needs to turn off networks delay
UPower         0    root     772     upowerd         sleep                                                    Pause device polling                      delay
<myUser>       1000 <myUser> 2748    csd-power       handle-lid-switch                                        Multiple displays attached                block
<myUser>       1000 <myUser> 2752    csd-media-keys  handle-power-key:handle-suspend-key:handle-hibernate-key Cinnamon handling keypresses              block
<myUser>       1000 <myUser> 2630    cinnamon-sessio shutdown:sleep                                           user session inhibited                    block
<myUser>       1000 <myUser> 2748    csd-power       sleep                                                    Cinnamon needs to lock the screen         delay
6 inhibitors listed.
```

I have been unable to determine what makes the difference between Lollypop's inhibiting as it should and it inhibiting in the blanket way that it should not perform. The cause seems _not_ to be (for these are the things that I have tested) power-source or connection or lack of connection to a DAC.

I have not managed to find anything that seems relevant in any log.

I have two Cinnamon devices and both are affected. Both devices are Thinkpads. Both run a 5.8 kernel.

In May I posted in the Mint forum about the problem (specifically: Lollypop) but nothing came of [that post](https://forums.linuxmint.com/viewtopic.php?f=18&t=349362&p=2016435&hilit=power+play#p2016435).

**Comment by hellzerg** [comment]
Regarding Lollylop, you can tweak a setting using dconf-editor.
Go to /org/gnome/Lollypop/power-management and set it to NONE.

That will allow suspend to work.

**Comment by LinuxOnTheDesktop** [comment]
@hellzerg 

Right, and thanks. However, I need something more granular. For, I want: (1) _suspend_ to occur _only when Lollypop is not playing anything_ (and/or not full screen); (2) _screen dimming_ to work _whatever Lollypop is doing_. I recall (from above) that Lollypop is meant to do 1 and 2, or near enough. For, as I wrote: 'By design the Lollypop music player inhibits power-management - power-management in the form of screen-dimming and the turning off of the screen - only when the application is full-screen and/or the application is playing a file. '

**Comment by dtki7** [comment]
**For Mpv:** Mpv uses wayland to set the inhibition. This seems to only set the inhibition in `org.gnome.SessionManager` but not in `org.freedesktop.login1.Manager` (which is used by `systemd-inhibit`). For more information about `org.gnome.SessionManager` see e.g. <https://github.com/linuxmint/cinnamon/issues/7175>.

**For VLC:** VLC really doesn't set an inhibition (see <https://code.videolan.org/videolan/vlc/-/issues/10790>).

**For Lollypop:** This is in fact a lollypop bug. I opened an issue with a solution to fix the bug: <https://gitlab.gnome.org/World/lollypop/-/issues/2983>.

However, none of these issues affects parts of Linux Mint, so I suggest to close this issue.

**Comment by LinuxOnTheDesktop** [comment]
@dtki7: that is some really impressive work. Well done, and thank you. I will close this issue.
