### ISSUE TITLE
Timeshift: restore routine needs clarification for ordinary users

### ISSUE THREAD

**Issue by rgreen5** [linuxmint/cinnamon#10206]
```
 * Cinnamon version (cinnamon --version) - 5.0.4
   - Please specify if you are using the daily builds PPA - No
     (https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds).
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) - Mint 20.2
 * Graphics hardware *and* driver used - Intel Corporation 2nd Generation Core Processor Family Integrated Graphics Controller.
 * 32 or 64 bit - 64 bit
 ```
**Issue**

When restoring a snapshot, the final window in the sequence is more difficult to use for inexpert users than in the previous version of LM.  S/he is faced with a large number of options, when all s/he may really want is a full restore of the previous system. Secondly, the default selection is "nothing selected" (!): so the inexpert user could click "next" without selecting anything!

**Suggestion**

Modify the last window to make this process easier for inexpert users ("restore all" as the default option?)

**Comment by fredcw** [comment]
I think Timeshift is developed here: https://github.com/teejee2008/timeshift
