### ISSUE TITLE
It is too easy to 'hang' the PC via ctrl-alt-F8

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/cinnamon#10208]
```
 * Cinnamon version: 5.0.4
   - Please specify if you are using the daily builds PPA: I am not.
 * Distribution: Mint 20.2
 * Graphics hardware *and* driver used: Mesa; Intel
 * 32 or 64 bit: 64.
 ```

**Issue**

Pressing ctrl-alt-F8 gives the appearance - a false one, to be sure - of hanging the computer.

**Steps to reproduce**

Press ctrl-alt-F8,
See that the PC seems to hang.

**Expected behaviour**

Either the switching to the special tty effected by the key combination should be disabled (and I _believe_ that no ttys are disabled by default on Mint) or else some sort of warning or instructions should be given.

**Other information**

The user might press the key combination by accident. For, the user might intend to press some other key combination. Or else the user might think that the combination will do something other than switch to a tty. Or else the user might think that it will switch to a normal tty. In any of those cases, the user is likely to think that she has hung her machine / that a bug has hung the machine. In short, current behaviour is not newbie-friendly.

**Comment by clefebvre** [comment]
How does one accidentally press Ctrl, Alt and F8?

I can agree with the assumption of a tty being there and the combo being pressed purposefully, but in that case the user would simply browse the other ttys until one is found.

**Comment by LinuxOnTheDesktop** [comment]
> How does one accidentally press Ctrl, Alt and F8?

Fair question. Answer: _by trying to trigger a different function_. _I believe that I was trying to lower the brightness of my laptop's screen_, an operation for which the correct key combination is `Fn` + `ctrl` + `F8`.

Also: _compare suddenly being confronted with unfamiliar debugging windows in Firefox_. That has happened to me. It happened because I was trying to press some other key combination (I forget which combination) and by accident I hit the combination that generated the baffling stuff. To my knowledge and in my experience, that unfortunate scenario cannot happen in Chrome, just as the tty-of-hang (as we might call it) cannot happen in Windows.
