### ISSUE TITLE
Items are cut in Cinnamon menu

### ISSUE THREAD

**Issue by InfoLibre** [linuxmint/cinnamon#10200]
```
 * Cinnamon version 5.0.4
   - Please specify if you are using the daily builds PPA : no
 * Mint 20.2
 * 64 bit
 ```

**Issue**
Items are cut in Cinnamon menu, we can't see the end of the line :

![Capture d’écran du 2021-07-10 13-12-09](https://user-images.githubusercontent.com/3955499/125161202-3ddf3080-e181-11eb-9fbb-2fc9f2d9c454.png)

**Expected behaviour**

It was not the case in precedent version of Cinnamon :

![menu Linux Mint - Synaptic](https://user-images.githubusercontent.com/3955499/125161217-57807800-e181-11eb-85ba-ece139d3c81e.png)

**Other information**

It seems that the width of the menu is now fixed. Is it intended ?

**Comment by mtwebster** [comment]
It's not fixed, there were substantial layout changes to the entire menu. The way we decide the max width needs to be adjusted.

**Comment by Lurux** [comment]
The full name and description was shown at the bottom of the menu, too

**Comment by InfoLibre** [comment]
Yes, but I don't want to put my mouse on each item. I want to see the full name of each item as soon as I open the menu.

**Comment by InfoLibre** [comment]
Perhaps some item names could be changed, in order to be smaller.
