### ISSUE TITLE
Mint Cinnamon disconnect my wifi and keep asking for password every five minutes

### ISSUE THREAD

**Issue by amirniknami** [linuxmint/cinnamon#10203]
This annoying bug had happened to me in cinnamon 4 and now it keeps happening in Linux mint 20.02 and cinnamon 5. i have no such a problem with other Linux distro. This is actually driving me nuts. I have searched for issue in forum and Reddit . Apparently other people is reporting this problem and it is a common issue but Linux mint team never tackle this issue so far.

**Comment by amirniknami** [comment]
I have disabled my power management for WIFI but nothing changed.

**Comment by leigh123linux** [comment]
This is moere likely caused by a faulty kernel wifi driver, you haven't posted any useful info.

Run this and reproduce the issue and post the result.

```
journalctl -fu NetworkManager
```

**Comment by amirniknami** [comment]
-- Logs begin at Fri 2021-07-09 21:43:06 +0430. --
Jul 11 13:52:58 amir-Lenovo-IdeaPad-Z510 NetworkManager[678]: <info>  [1625995378.1995] device (p2p-dev-wlp9s0): supplicant management interface state: authenticating -> associating
Jul 11 13:52:58 amir-Lenovo-IdeaPad-Z510 NetworkManager[678]: <info>  [1625995378.2177] device (wlp9s0): supplicant interface state: associating -> associated
Jul 11 13:52:58 amir-Lenovo-IdeaPad-Z510 NetworkManager[678]: <info>  [1625995378.2178] device (p2p-dev-wlp9s0): supplicant management interface state: associating -> associated
Jul 11 13:52:58 amir-Lenovo-IdeaPad-Z510 NetworkManager[678]: <info>  [1625995378.3015] device (wlp9s0): supplicant interface state: associated -> 4-way handshake
Jul 11 13:52:58 amir-Lenovo-IdeaPad-Z510 NetworkManager[678]: <info>  [1625995378.3016] device (p2p-dev-wlp9s0): supplicant management interface state: associated -> 4-way handshake
Jul 11 13:52:58 amir-Lenovo-IdeaPad-Z510 NetworkManager[678]: <info>  [1625995378.3095] device (wlp9s0): supplicant interface state: 4-way handshake -> completed
Jul 11 13:52:58 amir-Lenovo-IdeaPad-Z510 NetworkManager[678]: <info>  [1625995378.3108] device (p2p-dev-wlp9s0): supplicant management interface state: 4-way handshake -> completed
Jul 11 13:52:58 amir-Lenovo-IdeaPad-Z510 NetworkManager[678]: <info>  [1625995378.8542] dhcp6 (wlp9s0): activation: beginning transaction (timeout in 45 seconds)
Jul 11 13:52:58 amir-Lenovo-IdeaPad-Z510 NetworkManager[678]: <info>  [1625995378.8552] policy: set 'Auto Niknami' (wlp9s0) as default for IPv6 routing and DNS
Jul 11 13:52:58 amir-Lenovo-IdeaPad-Z510 NetworkManager[678]: <info>  [1625995378.8838] dhcp6 (wlp9s0): state changed unknown -> bound

**Comment by leigh123linux** [comment]
That doesn't show any disconnection issue.

**Comment by leigh123linux** [comment]
What wifi driver is used?

**Comment by amirniknami** [comment]
> That doesn't show any disconnection issue.

Yes.Currently the issue is gone. sometimes it happens. but its temporary.

**Comment by amirniknami** [comment]
`  *-network
       description: Wireless interface
       product: Wireless 7260
       vendor: Intel Corporation
       physical id: 0
       bus info: pci@0000:09:00.0
       logical name: wlp9s0
       version: 73
       serial: fc:f8:ae:8c:4e:b1
       width: 64 bits
       clock: 33MHz
       capabilities: pm msi pciexpress bus_master cap_list ethernet physical wireless
       configuration: broadcast=yes driver=iwlwifi driverversion=5.4.0-77-generic firmware=17.3216344376.0 ip=192.168.100.54 latency=0 link=yes multicast=yes wireless=IEEE 802.11
       resources: irq:34 memory:b5500000-b5501fff
`

**Comment by amirniknami** [comment]
*-network
       description: Wireless interface
       product: Wireless 7260
       vendor: Intel Corporation
       physical id: 0
       bus info: pci@0000:09:00.0
       logical name: wlp9s0
       version: 73
       serial: fc:f8:ae:8c:4e:b1
       width: 64 bits
       clock: 33MHz
       capabilities: pm msi pciexpress bus_master cap_list ethernet physical wireless
       configuration: broadcast=yes driver=iwlwifi driverversion=5.4.0-77-generic firmware=17.3216344376.0 ip=192.168.100.54 latency=0 link=yes multicast=yes wireless=IEEE 802.11
       resources: irq:34 memory:b5500000-b5501fff
`
`

**Comment by leigh123linux** [comment]
Can you try the 5.8 or 5.11 kernel?

**Comment by amirniknami** [comment]
> Can you try the 5.8 or 5.11 kernel?

It seems it got solved
