### ISSUE TITLE
menu@cinnamon.org will not resize width for long application names Mint 20.2

### ISSUE THREAD

**Issue by ChooChooAl** [linuxmint/cinnamon#10207]
* Cinnamon version 5.0.4
 * Distribution - (Mint 20.2)
 * Intel graphics
 * 64 bit

**Issue**
In menu@cinnamon.org the application column no longer automatically resizes to display the longest application name.

**Steps to reproduce**
Simply scroll up and down menu (All Items works best) and look at application names.   Make sure some app has a long name.  I found these truncated:
Advanced Network Configuration
Document Viewer (Xreader)
Document Viewer (Evince)
System Profiler and Benchmark

**Expected behaviour**
In 20.1 the menu would automatically resized the width after scrolling through the menu a few times.  It seemed to measure all application names and retain the max length and adjust the overall menu width.  While trying to reproduce I found that it seemed to take some time to see the resize, like I had to run a program or two?! There must have been a max-width since even 20.1 would truncate a few very very long lines, especially in the 'places' where filenames in 'places' were extremely long.

20.1 Menu - note advanced network configuration
![Menu 20 1](https://user-images.githubusercontent.com/26556059/125290168-03df6d00-e2ee-11eb-9239-7dec48ca88ef.png)

20.1 Menu - again note advanced network configuration
![Menu 20 2](https://user-images.githubusercontent.com/26556059/125290239-18236a00-e2ee-11eb-8b38-8ceb513e3437.png)

The menu on 20.1 in this case is about ~870px where in 20.2 the menu is only ~720px

My screen resolution is 1920x1080 and I have set fonts in the menu to 20 pt for my readability.

**Comment by mtwebster** [comment]
Fixed: https://github.com/linuxmint/cinnamon/commit/b4959089712aac057a7d25f495a100a20362c517

**Comment by ChooChooAl** [comment]
Thanks.  I saw b495908 but I wasn't 100% sure it was the same issue.  Glad to see I'm not crazy.
