### ISSUE TITLE
Losing original window size and position after a window is pinned/unpinned to/from the sides

### ISSUE THREAD

**Issue by tanev** [linuxmint/cinnamon#10211]
**Info** 

 * Cinnamon version - `5.0.4` (default coming with `Mint 20.2`)
 * Distribution - `Mint 20.2`
 * Graphics hardware and driver used - `AMD 5700XT` with `21.2~git2107130600.9d225c~oibaf~f` mesa version from latest oibaf repo

**Issue**

Default position and size for a window are lost after it is pinned to some of the desktop sides, and then unpinned back (not sure if this is the term, see the videos at the end). If the app window is, for example, with its default size/position when initially created (I think that under the mouse pointer is the default), then resized to the right half of the desktop, then an attempt to return will lose its original size/position and will appear like it was created on the half of the screen.

**Steps to reproduce**

* Open an application to create a new window (i.e., a new terminal would do)
* Use `Super + <some-arrow-here>` (i.e. `Super + Right Arrow`) - the window is now pinned to the right half side of the desktop)
* Use `Super + Left Arrow` - the window is no longer pinned to the right half of the screen, but keeps its size and position a few pixels left.

The same happens with any such action, for example, `Super + Up Arrow`, etc. The reproduction above is just exemplary.

**Expected behavior**

The same steps above should return the app window to its original size/position where it was initially created. Or at least it was so under 20.1 cinnamon release.

I think that a picture worths a thousand words, so uploading two small videos from a default 20.1 iso and then from 20.2 as well, with the same steps above (and a `screenkey` instance running in the background):
https://tanev.tk/HIB/mint20.1.mp4
https://tanev.tk/HIB/mint20.2.mp4

Staying available in case any other info is required.

Best,
T.

**Comment by mtwebster** [comment]
This is fixed already: https://github.com/linuxmint/muffin/commit/23b345f2250d4e9d60e5facde1d5b1517391c8f2, just needs an update.
