### ISSUE TITLE
Window entries not shown in menu bar

### ISSUE THREAD

**Issue by Pikarobbi** [linuxmint/cinnamon#10210]
```
 * Cinnamon 5.0.4
 * Distribution - (Mint 20.2)
 * Graphics hradware
> Extended renderer info (GLX_MESA_query_renderer):
>     Vendor: Intel (0x8086)
>     Device: Mesa Intel(R) HD Graphics 5500 (BDW GT2) (0x1616)
>     Version: 20.2.6
 * 64 bit
 * linux kernel 5.4.0-77
 ```

**Issue**
Sometimes an open window has no entry in the menu bar.

**Steps to reproduce**
Open two or more program windows at the same time. The windows not, which are not appearing in the front, are marked in red in the menu bar. When selecting the background window, by clicking on it's entry in the menu bar, the entry dissapears.
Similarly the issue seems to occur with other windows, that have their color changed, e.g. due to a notification of a new instant message.

**Expected behaviour**
The color of the entry turns to the normal background color and the entry stays on the menu bar.

**Other information**
Problem did not occur in Mint 20.1.
Windows no longer appearing in the menu bar can still be brought to front using "Alt + Tab".

**Comment by mtwebster** [comment]
This is already fixed - https://github.com/linuxmint/cinnamon/commit/1c7cc5de912a962f361ed77e47ea082eb95236b1

Hopefully an update will be out today or tomorrow.
