### ISSUE TITLE
Cinnamon crashes to fallback mode when ckb-next is opened

### ISSUE THREAD

**Issue by zfr77** [linuxmint/cinnamon#10219]
* Cinnamon version (cinnamon --version)
Cinnamon 4.4.8
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
Linux Mint 19.3 Tricia

 * Graphics hardware *and* driver used
Graphics:
  Device-1: Intel Xeon E3-1200 v3/4th Gen Core Processor Integrated Graphics 
  vendor: Gigabyte driver: i915 v: kernel bus ID: 00:02.0 chip ID: 8086:0412 
  Device-2: NVIDIA GM204 [GeForce GTX 970] vendor: Gigabyte driver: nvidia 
  v: 460.84 bus ID: 04:00.0 chip ID: 10de:13c2 
  Display: x11 server: X.Org 1.20.8 driver: nvidia 
  resolution: 1920x1200~60Hz 
  OpenGL: renderer: GeForce GTX 970/PCIe/SSE2 v: 4.6.0 NVIDIA 460.84 
  direct render: Yes 

 * 32 or 64 bit
64 bit

 * Attach ~/.xsession-errors, or /var/log/syslog
[xsession-errors.txt](https://github.com/linuxmint/cinnamon/files/6831921/xsession-errors.txt)
[cinnamon-crash-report.txt](https://github.com/linuxmint/cinnamon/files/6831904/cinnamon-crash-report.txt)

**Issue**
I use ckb-next for my Corsair keyboard
https://github.com/ckb-next/ckb-next

When I open ckb-next after watching a movie using VLC Media Player, Cinnamon crashes into fallback mode. After restarting Cinnamon I can open ckb-next normally.
It doesn't happen if I open ckb-next before opening VLC Media player. See below for exact steps to reproduce.

**Steps to reproduce**
(Using VLC Media Player 3.0.8)

- Have ckb-next start at login. Make sure "Delay application start" in its settings is enabled. This way when the OS starts, ckb-next icon should appear in the panel.
- Do *NOT* open ckb-next. Just make sure the icon is in the panel.
- Open a movie file with VLC Media player (I tried a few different ones, seemed to work in all). Then close it.
- Click on the icon to open ckb-next. Cinnamon crashes.

**Expected behaviour**
ckb-next opens normally

**Other information**
I opened an issue with ckb-next too, but was advised to open it here.
https://github.com/ckb-next/ckb-next/issues/732

**Configuration info, if applicable**
[ckb-next-report-1626448882.gz](https://github.com/linuxmint/cinnamon/files/6831961/ckb-next-report-1626448882.gz)

**Comment by mtwebster** [comment]
Can you see if there's a crash dump in mintreport (system reports in the menu) for cinnamon?

I can't reproduce this on mint 20, though I don't have a corsair keyboard attached. I have one, but my kid's using it so I'll try later.

Can you check this in Mint 20.2 in a live session?

**Comment by zfr77** [comment]
Yes, there is a crash report. It's attached above (cinnamon-crash-report.txt)

It doesn't happen immediately after startup. Usually after 30 mins or so of normal usage (browsing, videos, games). I couldn't see any particular thing that causes it to happen, but it happens almost always.

I'll see if I can narrow it down, or have it happen in Mint 20.2.

**Comment by zfr77** [comment]
OK, good news: I figured out how to replicate it so it happens consistently.

(Using VLC Media Player 3.0.8)

- Have ckb-next start at login. Make sure "Delay application start" in its settings is enabled. This way when the OS starts, ckb-next icon should appear in the panel.
- Do *NOT* open ckb-next. Just make sure the icon is in the panel.
- Open a movie file with VLC Media player (I tried a few different ones, seemed to work in all). Then close it.
- Click on the icon to open ckb-next. Cinnamon crashes.

Note: The crash doesn't happen if you open ckb-next before opening VLC Media Player. It also doesn't happen if the icon doesn't appear in the panel, and you simply open ckb-next from the menu or terminal.

Can anyone please confirm if they can replicate it?

**Comment by mtwebster** [comment]
I can't reproduce this on cinnamon 5 - have you had a chance to try a live session of 20.2? It sounds like maybe an issue with the tray icon from what you describe, though there's been heavy development in that area of cinnamon, so the situation definitely could have changed by now.

**Comment by zfr77** [comment]
Doesn't happen when I boot to 20.2 from USB. Closing.
