### ISSUE TITLE
[Feature request] Support WireGuard connections in the Network Manager applet (network@cinnamon.org)

### ISSUE THREAD

**Issue by siebenmann** [linuxmint/cinnamon#10225]
```
 * Cinnamon version (cinnamon --version): Cinnamon 5.0.4
 * Distribution - Fedora 34 x86_64
 * Graphics hardware *and* driver used: Intel Corporation HD Graphics 620 (Dell XPS 13 9360), but I'm not sure what Xorg driver
  ```

**Issue**
The Network Manager applet doesn't support WireGuard connections, although current versions of NetworkManager do. Such connections aren't shown in the list of networks that you can select (under any category) and there's no sign if one is active or inactive.

NetworkManager reports WireGuard connections as a new type, "wireguard", instead of as type "vpn". Based on looking at the code in files/usr/share/cinnamon/applets/network@cinnamon.org/applet.js, a simple solution might be to add a case for WireGuard connections to the this._ctypes variable that maps NetworkManager types to categories, as a 'vpn' connection. Probably most people using WireGuard connections (especially through the applet) are using them as a form of VPN, instead of more complex usage cases that might want them to be treated separately.

**Steps to reproduce**
Configure a WireGuard connection in NetworkManager, then attempt to see it in Cinnamon.

**Expected behaviour**
You can activate and deactivate a WireGuard connection.

**Comment by papadakospan** [comment]
[It seems that network-manager-applet itself supports activating WireGuard connections](https://gitlab.gnome.org/GNOME/network-manager-applet/-/issues/77#note_1038059), but cinnamon's applet (which from my understanding, depends on the original applet? not sure) does not.

I tried removing the cinnaomn network applet and running `nm-applet` by itself. Sure enough, under VPN connections there are both WireGuard and OpenVPN entries to toggle.

**Comment by basmevissen** [comment]
It would also be nice if one could import wireguard configurations. From the command line, it can be done with:
`nmcli connection import type wireguard file <file>`

**Comment by Inrumpo** [comment]
My search on how to toggle a WireGuard connection from my taskbar in Linux Mint brought me here.

For people wondering how to do this in a non-technical but somewhat cumbersome way until this issue is resolved:

To toggle on:

1. open `Network Connections`
2. select your WireGuard connection
3. klick the options (gear) symbol
4. Go to the `General` tab
5. activate `connect automatically with priority` set to `0`
6. `save` and close

To toggle off:

1. open `Network Settings` and note that your WireGuard connection is now (temporarily) listed
2. toggle off

**Comment by poelstra** [comment]
Same as above, and I found another solution:
- download and enable the [app-launcher](https://cinnamon-spices.linuxmint.com/applets/view/344)
- add `nmcli connection up <your_interface>` and `nmcli connection down <your_interface>` commands.

You can even use VPN connected/disconnected icons (although the active status won't updated, of course).

![image](https://user-images.githubusercontent.com/1025628/217369503-790ac405-3fb9-4151-832d-a12451beb76c.png)

![image](https://user-images.githubusercontent.com/1025628/217369734-02623ca0-1593-4a5b-9367-1f2de872fffb.png)

**Comment by timur-g** [comment]
Also at https://github.com/linuxmint/cinnamon/issues/10854.
In forum at https://forums.linuxmint.com/viewtopic.php?p=2232899&hilit=Wireguard#p2232899nd 
And https://forums.linuxmint.com/viewtopic.php?p=2328032&hilit=Wireguard#p2328032

**Comment by claudiux** [comment]
Did you try the VPN-Sentinel applet?
https://cinnamon-spices.linuxmint.com/applets/view/368

**Comment by timur-g** [comment]
VPN-Sentinel works, but I still find this request appropriate. I think I read that XFCE supports it, just Cinnamon not. 

Note (in addition to this request): not sure if this one can be made to work in Cinnamon, it assumes WireGuard is a type of VPN connection, which sounds OK, but needs a change of parameters for normal wireguard connections which have it's own type..
https://github.com/max-moser/network-manager-wireguard

**Comment by claudiux** [comment]
https://blogs.gnome.org/thaller/2019/03/15/wireguard-in-networkmanager/

**Comment by Ogloppi** [comment]
This is what I would like too.
Wireguard should be under VPN section of Network Manager.
This way I could easily specify what connections should use my Wireguard VPN connection and what should not. I remember that it's also possible to just import the client .conf file directly from Network Manager GUI on other platforms.
It's bizarre how this is not possible on Linux Mint Cinnamon, while for example it is possible on Linux Mint Mate.

**Comment by damnms** [comment]
i used xfce with wireguard like a charm, i can turn on or off wireguard connections. but when i do that in cinnamons nm applet (turning off wireguard connection), its "gone". there is no way to activate it again in the gui, only with nm cli.
that just s*cks. would be nice to have this basic functionality.

**Comment by timur-g** [comment]
One more aspect of this: today I tried to "import new VPN" via Network Connections using file with WireGuard configuration, it does not work. I added the file conf. via nmcli.

**Comment by claudiux** [comment]
The PR #11905 try to fix this issue. Can you test it (after saving the original applet.js script) please?

**Comment by timur-g** [comment]
As seen in PR comments, this works well and should be in merged in Cinnamon IMO. Also tjhere are some detals to clarify.

**Comment by timur-g** [comment]
Thanks a lot @claudiux . As noted in PR, network connections have "Automatically connect to VPN" and there should also be another check box for "Automatically connect to Wireguard". If done, please link here.

**Comment by claudiux** [comment]
![Screenshot from 2023-12-25 16-53-01](https://github.com/linuxmint/cinnamon/assets/33965039/c2f21066-3ed8-45a4-ac6f-ed9e57bdca13)

**Comment by LinuxOnTheDesktop** [comment]
It seems to me that it would be good to be able to _prevent_ the network icon changing to the 'secure' icon. For, the key icon does not immediately put one in mind of networks, and (accordingly) one might have another program, such as the popular KeePassXC, whichuses the key icon. My panel is in the following unfortunate situation - note the _two_ key icons.

![image](https://github.com/linuxmint/cinnamon/assets/47056543/2d605f54-38a1-42c0-82d6-233960a6eaa3)
