### ISSUE TITLE
Keyboard shortcuts for tiling/snapping no longer functioning

### ISSUE THREAD

**Issue by 392781** [linuxmint/cinnamon#10227]
```
 * Cinnamon 5.0.5/5.0.4 (Used Timeshift during troubleshooting which downgraded Cinnamon)
 * Distribution - Mint 20.2
 * Graphics hardware - Intel HD 602
 * 64 bit
 * Attached .xsession-errors [here](https://pastebin.com/iujzcxY3).
 ```

**Issue**
Previously I would use keyboard shortcuts to tile my windows.  An example of this is taking a focused, unmaximized window and using super+right to snap the window to the right.  Then, I would use super+left to "untile" the window back into it's original position, unmaximized.  Same in all other directions. 

Just today, I ran into an issue where tiling left/right/top/bottom would work properly but once I tried to "untile" the window back into it's original position, the window would not budge and sometimes would glitch a little.  I played around with this for a while and eventually, my windows would no longer respond to my keyboard shortcuts and would not tile at all.  Snapping seems to still work but with the same issue.  Whatever I do, I cannot get the window to "untile"

Here is an example of what is visually happening as I move the window to the right then to the left.  There is no middle step between the movement where the window is back to it's original position as per the issue.  Furthermore, you will notice that the window is slightly glitched in it's final position on the left side:

![image](https://user-images.githubusercontent.com/25296775/126265051-1374650f-574b-4c7f-8ac7-c3646e74bd89.png)
![image](https://user-images.githubusercontent.com/25296775/126265066-ab5e28ce-47e9-408c-bdbb-2dec93e9d781.png)
![image](https://user-images.githubusercontent.com/25296775/126265125-a1fde8db-71f3-476a-a7fd-5d03962ea50a.png)

**Steps to reproduce**
I am not sure.  This began today.  I was tiling my windows when they suddenly stopped tiling properly.

**Expected behaviour**
I expect to be able to "untile" the windows and without hiccup or glitching out.

**Other information**
I have disabled/uninstalled various applets and extensions.  In addition, I did a Timeshift reset to a previous time where tiling worked properly.  I also have been trying to restart Cinnamon.  None of these things were able to fix the issue.

**Comment by mtwebster** [comment]
Hi this has been fixed already:
https://github.com/linuxmint/muffin/commit/23b345f2250d4e9d60e5facde1d5b1517391c8f2

This will be in the next muffin update.

**Comment by 392781** [comment]
Thanks @mtwebster!  Apologies for posting in the wrong place.
