### ISSUE TITLE
Sleep Wake problem

### ISSUE THREAD

**Issue by burny0202** [linuxmint/cinnamon#10222]
```
 * Cinnamon version: cinnamon 5.0.5-1
 * Distribution - Arch
 * Nvidia 960. Proprietary driver
 ```

**Issue**

Cinnamon does not restore correctly from sleep. Blank screen, no input ..

**Steps to reproduce**

Set machine to sleep. Press a key to restore

**Expected behaviour**

Desktop/Lock screen should appear. Screen detect input

**Other information**
N/A

**Configuration info, if applicable**
N/A

```

**Comment by leigh123linux** [comment]
File it against the kernel or graphics driver.
