### ISSUE TITLE
Settings -> Themes -> Add/Remove shows uninstalled themes when sorting by 'installed'.

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/cinnamon#10231]
```
 * Cinnamon version: 5.0.5
   - Please specify if you are using the daily builds PPA: I am not
 * Distribution: Mint 20.2
 * Graphics hardware *and* driver used: Intel/Mesa
 * 32 or 64 bit: 64. [Isn't all Cinnamon now 64-bit?]
 ```

**Issue**

System Settings -> Themes -> Add/Remove shows, at the top of the list and when sorting by 'installed', themes that are not installed.

![image](https://user-images.githubusercontent.com/47056543/126505054-b2cf74a6-dd47-46e8-a872-d64732a387be.png)

**Expected behaviour**

Uninstalled themes should either not be displayed at all or else they should be greyed-out.

**Other information**

Resolution: 1366x768 @ 60.02Hz 
WM Theme: Mint-Y-Dark (Mint-Y-Dark) 
Theme: Mint-Y-Dark [GTK2/3] 
Icons: Paper [GTK2/3]

**Comment by mtwebster** [comment]
Do you have *any* 3rd party themes installed? If you don't have any, then that display is correct - it sorts the list only.

This being where you add or remove themes, you need to be able select any of them, installed or not.

**Comment by LinuxOnTheDesktop** [comment]
I have no third party themes installed - er, I think. One would think that part of the point of the 'installed' sort option would be show the user _whether_ she has any third party themes installed.

> This being where you add or remove themes, you need to be able select any of them, installed or not.

Right. Some greying-out might in order then.
