### ISSUE TITLE
Alt Tab Q to close windows was part of my workflow. Can there be a custom way to reanable this in Cinnamon 5?

### ISSUE THREAD

**Issue by LinuxBeaver** [linuxmint/cinnamon#10244]
I am hurt by the "Alt tab Q to close Window" feature being removed.  Is there any plans to make this a custom option that can be re-enabled in the Windows>Alt-Tab settings menu? That way users that benefited from it will not be disappointed.

**Comment by xerydian** [comment]
I use this feature too, please bring it back 😕

**Comment by clefebvre** [comment]
I'm sorry it's not coming back.

Accidentally hitting it sounds way more reasonable than what we've seen in the past (Ctrl-alt-backspace for instance), and it's not discoverable at all. Rapidly closing applications can also be done in many other ways, middle-click in GWL or window-list, Ctrl+W/Alt-F4 on active window, etc..
