### ISSUE TITLE
new window(s) does NOT get focus

### ISSUE THREAD

**Issue by vitaliis** [linuxmint/cinnamon#10249]
```
 * Cinnamon 5.0.5
 * Distribution: Linux Mint 20.2 Cinnamon
 * Graphics:  
   * Device-1: Intel UHD Graphics 630 driver: i915 v: kernel 
   * Device-2: NVIDIA GP107M [GeForce GTX 1050 Ti Mobile] driver: nouveau v: kernel
 * 64 bit
 ```

**Issue**
New window that is started from a terminal or by a keyboard shortcut is not shown in the foreground. And therefore does not react on any input.

**Steps to reproduce**
Open Terminal and maximize it. Run `nemo .`. It looks like nothing has happend, but an instance of nemo is running somewhere in background (not visible behind the terminal). And when 'window list' applet is not present/visible (as in my case the bottom panel is hidden) there is no visual hint that a new window is there.

**Expected behaviour**
The new window should be brought to the foreground and become active (react to input, e.g. another example to reproduce it is the address bar in firefox when new firefox window is started by a keyboard shortcut).

**Other information**
If any other info is needed, please let me know. And, by the way, there is a similar issue, but related to a keyboard shortcut: #9999.

**Comment by mtwebster** [comment]
Hi, what is the 'focus mode' set to in window settings?
![image](https://user-images.githubusercontent.com/262776/127655070-9f67926b-c03f-4893-a055-ae84d204db30.png)
Strict mode prevents new windows from taking focus if a terminal window is currently focused.  Setting it to 'smart' (the default) should restore expected behavior.

**Comment by vitaliis** [comment]
Right! Thanks, @mtwebster ! 

This issue is fixed. But the related one #9999 (with 2 monitors) is not fixed after update. Could you check it or mention somebody, who might have a clue, to progress there.

To recap it shortly: having active window on one display, moving mouse pointer to the other display and starting a new firefox window using a keyboard shortcut does not bring focus onto newly started window. If the mouse pointer is on the same display where current active window is, then all is fine, new firefox window and address bar gets focus and input cursor.
