### ISSUE TITLE
Installer is buggy

### ISSUE THREAD

**Issue by nomuna** [linuxmint/cinnamon#10241]
**Using the linuxmint-20.2-cinnamon-64bit.iso.**

```sh
λ sha256sum linuxmint-20.2-cinnamon-64bit.iso
50b833f1f093c029bfb7ba6148c9ce96619c01a83e92f35287983fbd62f26b01 *linuxmint-20.2-cinnamon-64bit.iso
```

Created a USB Stick using Rufus under windows 10.

**Issue**

- Installer apparently must have internet connection otherwise hangs
- Installer can not use the wired connection 
  - ping google.com -- Network unreachable
  - ping 8.8.8.8  -- Network unreachable
  - restarted the service with the same result
 
**Expected behaviour**

Installer must be able to install the system even when internet connection is unavailable. I have not selected the option "Install multimedia codecs" believing it will stop/prevent it from trying to download files over the internet.

Had to connect to a wireless network to make the installer work.

**Comment by leigh123linux** [comment]
This isn't a cinnamon issue.

File it at https://github.com/linuxmint/linuxmint/issues

**Comment by nomuna** [comment]
Sorry. I did.
