### ISSUE TITLE
[Enhancement] Make items on the ends of panels clickable from the corner

### ISSUE THREAD

**Issue by Davidy22** [linuxmint/cinnamon#10247]
```
 * Cinnamon version 4.8.6
 * Distribution - Mint 20.1
 * Driver Version: 418.113, GeForce GT 750M, although probably irrelevant for this ticket
 * 64 bit
 ```

**Issue**
I have two applets on the ends of my bottom panel, which I think are the default ones. The menu on one side, the desktop display on the other. Currently if I send my cursor all the way to the bottom left or right corner of my screen and click, nothing happens because the clickable area of the buttons are actually a couple of pixels from the edge, so I have to aim slightly. It'd be nice if the click region of items on the ends of panels extended to the edges so I can click the corners.

**Steps to reproduce**
Shove your mouse towards the bottom left corner with vigor and try to click the menu button

**Expected behaviour**
Menu opens, or whatever it is you have on the bottom left.

**Configuration info, if applicable**
Happens with any applet's icon in the corner, not just the menu, not sure how to get panel config but I can say that it's just one bottom panel and I haven't really done much to it.

**Comment by mtwebster** [comment]
Have you tried a different desktop theme? I can't reproduce this in Mint-Y.

**Comment by Davidy22** [comment]
Oh, just checked Mint-Y, and it does seem to be 100% down to the theme. Closing this ticket and heading over to the theme config then.
