### ISSUE TITLE
 notifications@cinnamon.org : Notifications can get cleared before i got a chance to read them

### ISSUE THREAD

**Issue by SebastJava** [linuxmint/cinnamon#10245]
```
 • Cinnamon 5.0.5
 • Mint 20.2 (new install and all up-to-date)
 • Graphics:  Device-1: Intel 2nd Generation Core Processor Family Integrated Graphics driver: i915 v: kernel 
           Display: x11 server: X.Org 1.20.9 driver: modesetting unloaded: fbdev,vesa resolution: 1920x1080~60Hz 
           OpenGL: renderer: Mesa DRI Intel HD Graphics 2000 (SNB GT1) v: 3.3 Mesa 20.2.6
 • 64 bit
 ```

**Issue**
Notifications can get cleared before i got a chance to read them.

**Steps to reproduce with Firefox and webmail**

1. Have desktop notifications enabled for your webmail account in Firefox.
1. Send an email message to your own webmail address from https://forums.linuxmint.com/ or elsewhere.
1. Wait for the notification to appear and disappear on your screen. DO NOT click on it in the system tray. Just pretend you did not see it and you did not read it.
1. Open and close or minimize some other application's window. See? The notification got cleared from the system tray before you got a chance to read it.

**Other steps to reproduce in order to demonstrate that this is not specific to Firefox**
(Yes, these notifications could be "transient", so what follows could be considered to be normal, but i couldn't find any other method to confirm that this strange behaviour is not specific to Firefox...)

Testing with the notifications applet:
1. Left-click on the notifications icon in the system tray and select [ Notifications settings ] (prerequisite: Configure > Show empty tray = true)
1. Click [ Display a test notification ] and wait 4 secs for this pop-up notification to disappear. Now you see this "1" added to the icon in the system tray, indicating a new notification. DO NOT click on it.
1. Open and Close or minimize some other unrelated application's window (except the Terminal).

Testing with the Gnome-clocks:
1. Select the timer. Set it to 3 secs. Start. Wait for the pop-up notification to appear and disappear. Now you see this "1" added to the icon in the system tray, indicating a new notification.
1. Open and Close or minimize some other unrelated application's window (except the Terminal).

You can probably do these same tests with any other application. Example: I got the same behaviour from Rhythmbox, which appears to have "non-transient" notifications, because there are "Previous, Pause, Next" control buttons on these.

**Expected behaviour**
I understand that notifications can be automatically cleared and i really appreciate this. But some notifications such as the email notifications should never disappear before i got a chance to see them.

**Other information**
As @mtwebster was explaining in https://github.com/linuxmint/cinnamon-screensaver/issues/391#issuecomment-887538968, there are various behaviours that can be expected from notifications. It can be a transient notification, or it can be withdrawn for any reason. So, i can't be sure this is a bug. It just feels strange. And i did these other tests as described above: all these notifications behave the same way.

**Configuration info**
```
{
    "section1": {
        "type": "section",
        "description": "Behavior"
    },
    "ignoreTransientNotifications": {
        "type": "switch",
        "default": true,
        "description": "Ignore transient notifications",
        "tooltip": "Check this to ignore transient notifications.",
        "value": false
    },
    "section2": {
        "type": "section",
        "description": "Display"
    },
    "showEmptyTray": {
        "type": "switch",
        "default": false,
        "description": "Show empty tray",
        "tooltip": "Check this to show the tray even when there are no new notifications.",
        "value": true
    },
    "section3": {
        "type": "section",
        "description": "Keyboard shortcuts"
    },
    "keyOpen": {
        "type": "keybinding",
        "description": "Show notifications",
        "default": "<Super>n",
        "tooltip": "Set keybinding(s) to show the notification popup menu.",
        "value": "::"
    },
    "keyClear": {
        "type": "keybinding",
        "description": "Clear notifications",
        "default": "<Shift><Super>c",
        "tooltip": "Set keybinding(s) to clear all notifications.",
        "value": "::"
    },
    "section4": {
        "type": "section",
        "description": ""
    },
    "btnSystemSettings": {
        "type": "button",
        "description": "Open notification settings",
        "callback": "on_btn_open_system_settings_clicked"
    },
    "__md5__": "a0c865754395f09606cbab225c8f1fc1"
}
```
![Notifications_settings](https://user-images.githubusercontent.com/31940713/127230010-b41e4894-9362-49d7-9a6f-266d61725c77.png)

**Comment by SebastJava** [comment]
**Configuration info** `json` file now corrected

**Comment by SebastJava** [comment]
One example among others:

https://user-images.githubusercontent.com/31940713/127243848-583901ec-c5de-4017-b7a3-5c3960919a7d.mp4

**Comment by mtwebster** [comment]
This is all happening because the originating programs are getting focus, thus they assume you don't need a notification anymore because you're now staring at the program. You can see that you got a new email in your inbox, etc...

Click the test notification button in cinnamon settings. If you focus out and back in, the notification goes away. If you focus out, click the notification, it focuses the app once more, and the notification goes away.

As I said in the other issue, not every program behaves the same way, but this is a pretty standard behavior.
