### ISSUE TITLE
Segfault in libcinnamon.so

### ISSUE THREAD

**Issue by henriquefm** [linuxmint/Cinnamon#1025]
Hi,
I was editing the Cinnamon Menu to add the LibreOffice Math icon. When I clicked the checkbox, Cinnamon crashed and didn't came back. I had to restart the computer. Now it doesn't work anymore, when I login it shows the wallpaper, the wireless connection notification and nothing else. Here's the log I found about cinnamon when I login:
syslog:

```
Aug 13 20:07:17 kernel: [  131.244221] show_signal_msg: 42 callbacks suppressed
Aug 13 20:07:17 kernel: [  131.244225] cinnamon[2278]: segfault at 8 ip 00007f2207e0327e sp 00007fff861f9040 error 4 in libcinnamon.so[7f2207dda000+96000]
Aug 13 20:07:25 gnome-session[2184]: WARNING: Application 'cinnamon.desktop' killed by signal 11
Aug 13 20:07:26 kernel: [  139.698190] cinnamon[2412]: segfault at 8 ip 00007fd6bfc0827e sp 00007fff69ccac70 error 4 in libcinnamon.so[7fd6bfbdf000+96000]
Aug 13 20:07:26 gnome-session[2184]: WARNING: App 'cinnamon.desktop' respawning too quickly
Aug 13 20:07:26 gnome-session[2184]: CRITICAL: We failed, but the fail whale is dead. Sorry....
Aug 13 20:07:26 gnome-session[2184]: WARNING: Application 'cinnamon.desktop' killed by signal 11
```

Apport created an /var/crash/_usr_bin_cinnamon.1000.crash , don't know if it was sent.

**Comment by benjaminaigner** [comment]
Hi,

I had a similar error today:
Debian Testing, Cinnamon 2.8.7-1 (from the repo)

While editing the Wine menu with the built-in menu editor, it was not possible to delete anything from the editor, it just hang.
Cinnamon also tried to restart
DIY solution :-): delete the menu directory I wanted to remove

-> the menu applet was not able to show any menus anymore, after some research I found this issue.
The solution was the same for me: deleting the menu file, now everything works fine.

Unfortunately, I can't reproduce this bug.
I can provide the glass.log if it is necessary.

Best regards, 

Benjamin

**Comment by hermann-san** [comment]
I had the same error messages after a power outage. Cinnamon didn't want to start and kept trying to restart, but without success. My solution was to go to the driver manager and re-enable my Nvidia drivers since it was automatically changed to xserver-xorg-video-nouveau. After I did that, Cinnamon started as usual and also my second screen was also working again.
