### ISSUE TITLE
Recent update (perhaps to mesa or xorg-server) completely breaks rendering of desktop in VMWare Workstation

### ISSUE THREAD

**Issue by vsajip** [linuxmint/cinnamon#10254]
```
 * Cinnamon version 4.8.6 (on Mint 20.1), 5.0.5 (on Mint 20.2)
   - NOT using the daily builds PPA
 * Distribution - Mint 20.1 Ulyssa, Mint 20.2 Uma
 * VMWare driver (VMWare Workstation 11.1.4) - "VMware SVGA II Adapter (prog-if 00 [VGA controller])"
 * 64 bit
 ```

**Issue**

After doing a system update and restarting, the screen isn't properly rendered - icons appear as gray rectangles. The system is unusable because of the UI, but appears otherwise functional (things happen when you mouse over or click icons, but you can't see what's happening because of the rendering problem)

**Steps to reproduce**

* In a VM on VMWare Workstation 11.1.4, use the Mint updater to update where the packages being installed include:

  - mesa 21.0.3-0ubuntu0.2-20.04.1
  - xorg-server 2:1.20.11-1ubuntu1-20.04.2

(I am assuming the problem is related to these)

* Restart the virtual machine

**Expected behaviour**

The system should come up as normal with all icons and other graphic elements correctly displayed.

**Other information**

The VMs have been working fine for weeks and only broke on the recent update.

**Comment by simongarrett** [comment]
Me too, but on VirtualBox using Ubuntu with Cinnamon desktop.  After running an update (apt full-upgrade) suddently Cinnamon renders as grey and white rectangles.  Other desktops work, and there are no other updates posted.

**Comment by vsajip** [comment]
I restored the VMs from yesterday's backup, updated while specifically omitting the `mesa` and `xorg-server` updates and restarted, and the desktop comes up as normal. It does seem to point to one or both of those updates as being the culprit.

**Comment by leigh123linux** [comment]
Report the issue to ubuntu against xorg or mesa.
