### ISSUE TITLE
Mouse generating phantom single clicks

### ISSUE THREAD

**Issue by weltyj** [linuxmint/cinnamon#10266]
```
 * Cinnamon version (cinnamon --version)  4.4.8
   * Distribution - Mint 19.3
 * Graphics hardware *and* driver used
 * Lenovo GP107M [GeForce GTX 1050 Ti Mobile]  Nvidia driver 390.144
 * 64 bit
 * Attach ~/.xsession-errors, or /var/log/syslog
 ```

**Issue**
I have a problem since the last upgrade which included the kernel, where something in the mouse driver appears to be generating single click events that are not real.   These events happen when the left button is pressed and held down (for example trying to drag an item, highlight text, ...).   A phantom click then can occur, which looks to the application handling the mouse as if I released the mouse button, and followed with a single click.

This happens maybe one out of ten times when not moving the mouse.  And the false click can come really fast -- sometimes a single click appears in the application as two single clicks separated by a fraction of a second.

But when moving the mouse for a drag n drop, or highlight, there can be many many false single click events.

As you might suspect this makes useablity of the system extremely problematic!

This may be specific to the logitech mouse driver.

**Steps to reproduce**
It is a little bit random, but if I run 
      "xev | grep "Button"  
I can see the events as they are generated easily enough, sometimes mouse movement generates a many (10-20) false clicks, sometimes movement generates no false clicks.

**Expected behaviour**
No false clicks.

**Other information**
root@lt3:/sys/bus/usb/drivers/usb/usb1/1-1# lsusb
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 004: ID 04ca:7070 Lite-On Technology Corp. 
Bus 001 Device 003: ID 148f:5370 Ralink Technology, Corp. RT5370 Wireless Adapter
Bus 001 Device 002: ID 046d:c52b Logitech, Inc. Unifying Receiver
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

root@lt3:/sys/bus/usb/drivers/usb/usb1/1-1# uname -a
Linux lt3 5.0.0-32-generic #34~18.04.2-Ubuntu SMP Thu Oct 10 10:36:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

```

Please paste here

```

**Comment by mtwebster** [comment]
Do you have another mouse you can try as well?  I've had mice I dropped one too many times start behaving strangely with regards to clicks, releases, weird behavior.

**Comment by weltyj** [comment]
Yes, I do.   I'll give that a try and report back.






On Thursday, August 12, 2021, 07:02:52 PM PDT, Michael Webster ***@***.***> wrote: 







Do you have another mouse you can try as well? I've had mice I dropped one too many times start behaving strangely with regards to clicks, releases, weird behavior.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by weltyj** [comment]
You nailed it!   A different mouse works just fine.   I'll withdraw the issue.

Thanks!
Jeff






On Thursday, August 12, 2021, 07:02:52 PM PDT, Michael Webster ***@***.***> wrote: 







Do you have another mouse you can try as well? I've had mice I dropped one too many times start behaving strangely with regards to clicks, releases, weird behavior.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by weltyj** [comment]
Another mouse worked just fine.  It was the mouse itself.
