### ISSUE TITLE
Debian 11 switch from mint-y to mint-x theme

### ISSUE THREAD

**Issue by Phil995511** [linuxmint/cinnamon#10279]
```
 * Cinnamon version 4.8.6-2
 * Distribution - Debian 11 Bullseye
 * Graphics hardware *and* driver used : Nvidia RTX 3080 and NVIDIA Driver Version 460.91.03
 * 64 bit
 
 * Description problem : 
 
After reinstallation from Debian 10 Buster Cinnamon v 3.8.8 to Debian 11 Bullseye Cinnamon 4.8.6-2 without erasing `/home`, my Cinnamon desktop became unstable.

The only solution found was to reinstall Debian 11 after removing all the hidden system files (.xxx) contained in the `/home` directory.

After that I tried switching my Debian 11 Bullseye from the preinstalled default Mint-y theme to the Mint-x theme that I like to use. Unfortunately, it is difficult and time consuming to achieve this.

However, there is a tool contained in the "mintwelcome" utility which makes it very easy to switch from Mint-y to Mint-x (or vice versa). Would you be so kind as to make this tool contained in the "mintwelcome" utility available to Cinnamon users not running Linux Mint ? 

I would need it for all my future installations !!!

Thank you.

**Comment by JosephMcc** [comment]
Sorry but I don't think that's going to happen. Mintwelcome is a Mint specific tool. Neither it nor the Mint themes are a part of Cinnamon.

**Comment by Phil995511** [comment]
Thank you for your message.

While installing Debian 11, you get stuck with the Mint-Y theme. I think it's the same with other recent distros.

From there, there are 3 solutions. Spending time returning to Mint X by hand which is very restrictive. Stick with Mint-Y which I don't like at all (I've been using Mint X for over 10 years). Change desktop and use Mate, Gnome, KDE or something else instead of Cinnamon...

If you want to continue streaming Cinnamon in other distributions than Linux Mint, you need to create a tool to easily switch from Mint-Y to Mint-X and vice versa... Or give up broadcasting Cinnamon outside of Linux Mint ;-(

Regards.

**Comment by JosephMcc** [comment]
You need to take that up with the Debian maintainers. We don't maintain Cinnamon or any of the Mint themes in Debian. We only maintain them ourselves for Mint and LMDE.

**Comment by Phil995511** [comment]
I speak bad English... I don't know if I'm not explaining myself well or if you don't want to understand ?!? A bit of both ?? :)

I don't want Mint themes in Debian and my request has been sent to the right place...

Let's stop talking about Mint-X or Mint-Y which doesn't seem like the right term to talk about my problem :

When you install a distro like Debian 10 you use Cinnamon 3.8.8 which displays the desktop in "old style".

When you install a distro like Debian 11, you are using Cinnamon 4.8.6-2 which displays the desktop in a "modern style".

Would you be so kind as to create a function for us that allows us to switch from the "modern style" ti the "old style" ??`? 

I have been using Cinnamon for over 10 years, I'm used to the old desktop style of Cinnamon 3.8.8 and earlier ... The desktop style of Cinnamon 4.8.6 (or newer) does not suit me.

Regards

**Comment by mtwebster** [comment]
I'm pretty sure Debian does not even package Mint themes.

As @JosephMcc mentioned, mintwelcome is a tool for Mint only, *not* a vanilla Debian install, *and is not necessary to do anything you've mentioned*.

If you open the main menu, and open "Themes", you can switch themes between any that are installed. If Mint-X is installed, you can switch to it easily there. As I mentioned, I don't think mint themes are part of Debian.

If Mint-X doesn't show up in the theme settings, you can try grabbing these packages and installing them:
http://packages.linuxmint.com/pool/main/m/mint-x-icons/mint-x-icons_1.6.3_all.deb
http://packages.linuxmint.com/pool/main/m/mint-themes/mint-themes_1.8.8_all.deb

I imagine they'll be fine on Debian 11.

You can re-enable the old 'window list' applet and remove the grouped window list from the 'Applets' program in the main menu.

There is nothing mintwelcome provides that you cannot achieve using what I just mentioned.

We do not maintain Cinnamon on Debian. We cooperate with the maintainers, but it's up to them to decide what themes to provide. Mint-X and Mint-Y are *not* specific to Cinnamon, so they're not really expected to package them - there are plenty of other themes out there to choose from.

**Comment by ItzSwirlz** [comment]
We don't package any mint packages (mint-*), I would recommend staying away. Of course if you like Mint themes, download the debs built and properly install. Mintcommon will
start to cause a chain of basically transforming it to LMDE.

**Comment by clefebvre** [comment]
He's referring to a set of settings known in Mint as modern vs traditional, i.e. window list vs GWL and so on... not just mint-x vs mint-y.... but that's a concept which is foreign to Cinnamon, it's a concept which only makes sense in Mint. The reason it's in Mint is because Mint's default settings changed radically, and part of that change is mostly attributed to the theme itself.

Having a quick way to revert these changes was added in Mint because of that, but there's no need for that in Cinnamon itself, especially not just to revert GWL and a few other things.

I'll close the issue since it won't lead to any changes.
