### ISSUE TITLE
Hibernate in my LMDE4 install is buggy

### ISSUE THREAD

**Issue by Wallby** [linuxmint/cinnamon#10272]
```
 * Cinnamon version (cinnamon --version) -> 5.0.5
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) -> LMDE 4 Debbie
 * Graphics hardware *and* driver used -> "intel GPU" + "NVIDIA GPU", but no additional drivers installed (i.e. using default from installation)
 * 32 or 64 bit -> 64 bit
 * Attach ~/.xsession-errors, or /var/log/syslog -> [xsession-errors.txt](https://github.com/linuxmint/cinnamon/files/6985441/xsession-errors.txt))
 ```

NOTE: as I cannot upload syslog.txt to github (I suspect it is too big), here is a link to "some file sharing service I found".. https://ufile.io/wvatzou0

**Issue**
Hibernate (called "slaapstand" for me) succeeded once thusfar (installed LMDE4 today). Other times it takes me to the login screen without first shutting down. The time that it did work it went to a black screen, then to the login screen (without mouse cursor and keypresses seemingly disabled) and then went into hibernate successfully). Another time it shut down, but then did not "resume" (i.e. firefox was open before, now it wasn't).
My swap partition is +- 16.75GiB and my swap partition is +- 18GB.

**Steps to reproduce**

**Expected behaviour**

**Other information**

**Configuration info, if applicable**

**Comment by Wallby** [comment]
Not an issue, but it would be nice if in the LMDE4 installer there is maybe some sort of checkbox for installing with hibernation support enabled (i.e. which will check the size of RAM and then size the swap partition accordingly or something). Or.. even better would be a gui tool that can be run from install to "enable hibernation" (+ in case of upgrading/downgrading RAM, e.g. resizing swap partition if that is how that would work).

**Comment by leigh123linux** [comment]
File the issue at https://github.com/linuxmint/linuxmint/issues
