### ISSUE TITLE
Cinnamon-Settings Segfault

### ISSUE THREAD

**Issue by darkwyrm** [linuxmint/cinnamon#10285]
```
 * Cinnamon version (cinnamon --version)
   - Please specify if you are using the daily builds PPA
     (https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds).
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
 * Graphics hardware *and* driver used
 * 32 or 64 bit
 * Attach ~/.xsession-errors, or /var/log/syslog
 ```
Cinnamon 5.0.5, not using daily builds PPA
Linux Mint 20.2 64-bit
Using nvidia-driver-470 with a GeForce GTX 750 Ti

**Issue**
The Cinnamon Settings app does not start. Digging further in, discovered that it was dumping core without displaying the main window. Relevant syslog entry with stack trace attached.

[syslog.txt](https://github.com/linuxmint/cinnamon/files/7027447/syslog.txt)

**Comment by mtwebster** [comment]
Hi, is there an entry for this in System Reports? Under crash reports - if there is I'd like the crash.tar.gz file generated (press the Local Files button.

Also, are you using python packages installed using pip? If so, take a look at this issue: https://github.com/linuxmint/cinnamon/issues/10195

**Comment by darkwyrm** [comment]
Crash caused by locally-installed Pillow autoinstalled by another package. I didn't see issue 10195 when searching for problems, so thank you. :)
