### ISSUE TITLE
Feature Request: Search shortcuts

### ISSUE THREAD

**Issue by suryaanshah** [linuxmint/cinnamon#10290]
In Linux Mint 20.2 Cinnamon, in the Keyboard settings, we can see the various shortcuts. If we could search shortcuts instead of always going to that application and trying to find the thing we need, then that would be great.
![MintGHsearch-shortcut-FeatureRequest](https://user-images.githubusercontent.com/47082682/130945797-ccdb9188-6a70-4472-aad8-6c3827b90898.png)

**Comment by nicekiwi** [comment]
Something like the GNOME Keyboard shortcut settings would be ideal, being able to see the action and shortcut inline and being able to search them. 

Also having the text centered is quite hard to read line to line, ideally would be left aligned.

**Comment by suryaanshah** [comment]
The message underneath "To edit a keyboard binding, click it....." is too small and I missed it in my first tries. Maybe show this when someone is trying to edit a keyboard binding.

**Comment by rcalixte** [comment]
75a53a8
