### ISSUE TITLE
Thumbnail/Icon view in file picker dialog

### ISSUE THREAD

**Issue by asquartz** [linuxmint/cinnamon#10317]
In the Cinnamon/Nemo file picker, that is displayed when you choose a file to insert or upload somewhere, files are always shown in List View with tiny thumbnails.  It would be good if you could select Icon View so that you can see the thumbnails properly.

There are no buttons top-right like the main Nemo window has, and the Ctrl-1 keyboard shortcut doesn't work either.

Example of the dialog I mean:  
![Screenshot from 2021-09-12 14-02-53](https://user-images.githubusercontent.com/34890493/132988948-4dd364a3-e75d-489a-bddb-50eccdfe4bc0.png)

The buttons I think should be included on the dialog:  
![Screenshot from 2021-09-12 14-12-14](https://user-images.githubusercontent.com/34890493/132988954-217d335f-f830-4968-8055-748d2dbf2741.png)

 * Cinnamon version 5.0.5
 * Distribution - (Mint 20.2 Uma)
 * 64 bit

**Comment by JosephMcc** [comment]
Those dialogs are supplied by Gtk, not by us. We don't have any control over them. Bug reports and feature requests should be filed on the the GNOME Gtk gitlab.

**Comment by asquartz** [comment]
Will do.  Thanks for replying.

**Comment by Zahrun** [comment]
This is now available in GTK 4 / GNOME 44. Any plan to have this feature in Cinnamon?

**Comment by JosephMcc** [comment]
As noted above, this has nothing to do with Cinnamon. It's up to the application you are using.

**Comment by Secret-chest** [comment]
Can we patch gtk3 to have this? I don't think we'll switch to gtk4 anytime soon.
