### ISSUE TITLE
Where is the `zoom level` option?

### ISSUE THREAD

**Issue by thep0y** [linuxmint/cinnamon#10324]
```
 * Cinnamon version (cinnamon --version)
   5.0.5
 * Distribution - Mint 20.2
 * Graphics hardware *and* driver used
   Intel UHD Graphics 630
   intel-media-va-driver
 * 64 bit
 ```

**Issue**
I want to set the zoom ratio to 150%, but I can't find the `zoom level` option.

**Steps to reproduce**
System Settings - Display

**Expected behaviour**
Set the zoom ratio to 150%.

**Other information**
![Screenshot from 2021-09-17 17-44-26](https://user-images.githubusercontent.com/51874567/133763495-23228456-2171-4469-8c50-1263f608efcf.png)

**Comment by mtwebster** [comment]
Enable it here:
![image](https://user-images.githubusercontent.com/262776/133768609-5261d1de-e8b1-4310-aa34-6e6d7a4b3e01.png)

Then you'll be able to set it in the Layout.
