### ISSUE TITLE
[Enhancement] Ask for confirmation when removing a panel

### ISSUE THREAD

**Issue by rduttshukla** [linuxmint/cinnamon#10337]
```
 * Cinnamon 5.0.5, not using daily builds ppa
 * Mint 20.2
 * Intel HD Graphics 620 | i915
 * 64 bit
 ```

**Issue**
I accidentally deleted my panel because clicking the remove button on the panel context menu removes the panel without confirmation.

**Steps to reproduce**
1. Right click on any panel
2. Click on "➖ Remove"

![Screenshot from 2021-09-20 15-24-20](https://user-images.githubusercontent.com/51123074/133984923-ab49014c-a202-4e02-87ff-382b93a269d9.png)

The panel is removed instantly.

**Expected behaviour**

A confirmation should be asked before removing the panel because otherwise this leads to unintentional loss of panel configurations.

**Comment by LinuxOnTheDesktop** [comment]
Cf. #9092 (which made the same request a year ago).
