### ISSUE TITLE
Feature request: fractional scaling with GTK (avoid xrandr)

### ISSUE THREAD

**Issue by Alex-Bujorianu** [linuxmint/cinnamon#10349]
```
 * Cinnamon version: 5.0.5-6
 * Distribution - Manjaro Linux
 * Graphics: AMD Ryzen 5 4000 with Mesa (open source) driver
 * 64-bit
 * Not a bug, defective by design
 ```

**Issue**
Fractional scaling on X11 causes higher-than-normal CPU and VRAM usage, and has some stability issues that lead to Cinnamon crashes. High resolution video playback, screen sharing and games are most affected, leading to mouse cursor lag. This solution is particularly suboptimal for games, as the game has to be upcaled from 3840x2160 to 5210x2880 and then back down again (this is what happens on a 4K monitor with 150% scaling). Many games will simply not work in fullscreen.

**Steps to reproduce**
Try playing a game or watching a 4K YouTube video on a 4K monitor with fractional scaling.

**Proposed solution**
All the major UI toolkits support fractional scaling, except for GTK. Apps made in Qt, Electron, Java/Swing, and Flutter can all scale fractionally. Font scaling is already handled by freetype. My question is, why can’t Nemo, Pluma, xed, and Cinnamon do the same thing? Can the Linux Mint team patch these apps, or patch GTK itself to work with fractional scaling? Firefox, LibreOffice and Thunderbird can scale fractionally even though they are built with a (custom) GTK toolkit.

**Comment by mindbeat** [comment]
I also notice the same issues. 4K 150% fscaling also breaks many games to detect the mouse position correctly. Ex: OpenRA with 150% f-scaling 4K and create this issue.

**Comment by JosephMcc** [comment]
Fractional scaling support directly in Gtk would need to be handled upstream by GNOME. It's outside the scope of Mint.

**Comment by Alex-Bujorianu** [comment]
You can always patch GTK yourselves in the same way you forked Cinnamon from Gnome. The current implementation of fractional scaling on Cinnamon is basically unusable for the average user, especially gamers. Fullscreen is broken. There is noticeable lag and tearing with animations.

**Comment by leigh123linux** [comment]
@Alex-Bujorianu  It is easier to dump the animations.
