### ISSUE TITLE
icons pinned to task bar overlapping with applets if we open many apps

### ISSUE THREAD

**Issue by dheerajgajula02** [linuxmint/cinnamon#10342]
```
 * Cinnamon version (Cinnamon 5.0.5)
   - Please specify if you are using the daily builds PPA
     (no).
 * Distribution - (Linux Mint 20.2 x86_64)
 * intel integrated dirver*and* none
 * 64 bit
 * Attach ~/.xsession-errors, or /var/log/syslog
 ```

**Issue**
if we are using a lot of apps once or if we pin a lot of apps to the task bar it starts overlapping on the applets

**Steps to reproduce**
may be if the apps count increases to some extent we might add another new line like it is in windows 10

**Expected behaviour**
that overlapping makes them not accessible

**Other information**
themes used
windows borders - mint-Y-dark
icons - mint-y-dark-grey
controls - mint -y-dark-grey
mouse pointer - adwaitha
desktop - mint-y-dark-grey

**Configuration info, if applicable**
i didn't install any extra themes I use one of the default themes given in linux mint cinnamon

in the picture i pasted below check the right bottom corner there we cant access any of the opened apps unless i use alt-tab and cycle through all of them until i again get that opened application I want

```
check that last 
Please paste here

``
![bug report](https://user-images.githubusercontent.com/83493115/134393974-8606b14e-0f99-42dc-9c59-c506cf3d2adc.png)
`

**Comment by JosephMcc** [comment]
This is a long standing issue https://github.com/linuxmint/cinnamon/issues/5042
