### ISSUE TITLE
Linux Mint version of Firefox ignores the "DisableAppUpdate" of Policies.json

### ISSUE THREAD

**Issue by ineuw** [linuxmint/cinnamon#10359]
```
 * Cinnamon version: 5.0.5
 * Using the daily builds PPA :  No
 * Distribution:  Mint 20.2
 * 64 bit
 * Graphics hardware: 
   00:02.0 VGA compatible controller: Intel Corporation CoffeeLake-S GT2 [UHD Graphics 630] (prog-if 00 [VGA controller])
  DeviceName: Onboard - Video

**Issue**
Linux Mint version of Firefox ignores the "DisableAppUpdate" of Policies.json. Although it is clearly active in about:support of my Firefox version 92.0.1. I have four installations of the same versions of Firefox in LMC 20.2, - two admin and two user accounts. I must be aware of the changes before updating and I cannot allow unexpected updates. What choices do I have?

**Steps to reproduce**
Install the attached policies.txt (json)

**Expected behaviour**
Don't ignore Firefox's user policies. 

``
[policies.txt](https://github.com/linuxmint/cinnamon/files/7250512/policies.txt)
`

**Comment by leigh123linux** [comment]
This isn't a cinnamon issue.

**Comment by clefebvre** [comment]
What do you mean by ignores.. can you describe what happens and what you expect instead? Please provide screenshots to explain the situation.

**Comment by ineuw** [comment]
I had version 90.0 installed everywhere, and I monitor FF versions for changes that are negative to my work. That is when I noticed that my policy setting was ignored. 
@leigh123linux, then whose issue is this?

**Comment by leigh123linux** [comment]
@ineuw  I believe it should be filed and addressed upstream.

https://bugzilla.mozilla.org/describecomponents.cgi?product=firefox

**Comment by leigh123linux** [comment]
@ineuw I believe it should be filed and addressed upstream.

https://bugzilla.mozilla.org/describecomponents.cgi?product=firefox

**Comment by mtwebster** [comment]
Are there any relevant messages/errors in the console? (ctrl-shift-J)

**Comment by ineuw** [comment]
@mtwebster, this happened when 92.0.1 was released. Now, we are between updates and will keep on monitoring the update manager's offerings.

@leigh123linux, my first post about this was on Github's Firefox policies site. They closed the issue immediately, saying that it's a Linux Mint issue. So, I posted it here. At this point it is a matter of curiosity as to who owns up to this. So now I am heading over to bugzilla which I didn't visit for ages.

**Comment by clefebvre** [comment]
I'm sorry, I don't understand what's going on... Firefox is installed by default, system-wide, and its updates are handled by APT. It doesn't matter which user is running it, it's the same version for everybody. Firefox cannot update itself since it doesn't have root privileges.

**Comment by ineuw** [comment]
@clefebvre, It's simple. APT ignored my policy settings and updated Firefox. When I noticed it, it was too late.

**Comment by clefebvre** [comment]
APT doesn't care about Firefox's policies and it shouldn't, these have nothing to do with each other.

**Comment by clefebvre** [comment]
You can blacklist a particular package name or a particular version using the Update Manager. The Firefox configuration is completely irrelevant to APT.

**Comment by clefebvre** [comment]
I almost forgot, it's never too late. Restore your latest Timeshift snapshot and you'll be back with the previous version of Firefox.
