### ISSUE TITLE
CSS .stroke and stroke by text-shadow not working

### ISSUE THREAD

**Issue by IvoAndonov** [linuxmint/cinnamon#10356]
```
 * Cinnamon version
 5.0.5
 * Distribution
 Arch Linux
 * Graphics hardware *and* driver used
 GTX 1660 Ti, 470.74
 * 32 or 64 bit
 64 bit
 ```

**Issue**
I'm using a 100% transparent theme. Trying to make a text stroke for calendar, so that the numbers are visible when the background image is light: https://i.imgur.com/Vb9Rflz.png . I tried to do that first by using text-shadow, then by .stroke, but the latter doesn't work at all. Interestingly enough, stroke by using text-shadow works for the desktop icons but not for items in the panel like the calendar. .Stroke (regular stroke, not text-shadow) works for the desktop icons as well but not for items in the panel, such as Calendar.

  .stroke {
    -webkit-text-stroke-width: 2px;
    -webkit-text-stroke-color: #000000;
}

This is an example of the stroke I got from an online generator.

**Steps to reproduce**
Not applicable.

**Expected behaviour**
.stroke and all other CSS attributes should work in Cinnamon, specifically for items in the panel.

**Comment by JosephMcc** [comment]
Cinnamon is not the web. While css is used for theming it's only a subset and not everything works. Not only that, what you are doing there is using .stroke as a style class. And that most certainly isn't used anywhere in Cinnamon.

The panel and the desktop icons are also two separate things. One is internal to Cinnamon, the other rendered by gtk. Gtk supports a wider range of css features.

**Comment by IvoAndonov** [comment]
Then what GTK file do you suggest that I change, so that I can have a stroked text in the panel (Calendar)?

**Comment by JosephMcc** [comment]
None. The cinnamon panel does not use Gtk. You just cannot do this in Cinnamon.
