### ISSUE TITLE
Sometimes Cinnamon desktop (background and desktop icons) is shown instead of application   (lookthrough effekt)

### ISSUE THREAD

**Issue by goebbe** [linuxmint/cinnamon#10386]
```
 * Cinnamon version (cinnamon --version):  5.05  with all updates (no daily builds)
 * Distribution - (Mint 19.2 )
 * Graphics hardware *and* driver used:   Intel Corporation 2nd Generation Core Processor Family Integrated Graphics Controller
 * 64 bit
 ```
**Issue**
Using e.g. Firefox in Cinnamon, sometimes frames in Firefox seem to be transparent. I.e. one can see the corresponding part of the desktop through a frame in Firefox. 

**Steps to reproduce**
Open the following page in Firefox: 
https://en.wikipedia.org/wiki/Portrayal_of_James_Bond_in_film
Now scroll to the very bottom of the web page and scroll up again. 
The frame on the right side called "Timeline of James Bond films" is not rendered correctly - instead, the corresponding part of the desktop is shown in the corresponding frame.  The effect is like a transparent frame.

Update: This was reproducible at the time of reporting - but i cannot reproduce now. However, the issue is still present from time to time.

See screenshot. 
![Screenshot from 2021-10-10 13-26-47](https://user-images.githubusercontent.com/35854226/136694037-a493880a-f68e-4604-abc0-02fea7ca9ea6.png)

**Expected behaviour**
Frames in Firefox should never show the Cinnamon Desktop. 

**Other information**
- I had similar effects, using MS-Office (Wine) on Cinnamon, recently. However, I was not able to reproduce the problem reliably. 
This is the reason I believe that the problem is possible caused by/ related to Cinnamon or mutter. 
- switching tabs will render the frame correctly  (e.g. switch to Calendar tab and then back to Wikipedia tab)
- Moving the application window (e.g. firefox), one can see different parts of the underlying desktop. The effect is like a window where you can look through.   

**Configuration info, if applicable**
All extension disabled. 

Please let me know, if I can provide additional information. 

Update 16.11.2021 - description updated

**Comment by goebbe** [comment]
I just had the same issue (lookthrough-effect) using Thunderbird 78.13.0 (64-bit) on LM-cinnamon: 
I could see the desktop background instead of the Inbox, and also when hovering over some buttons. However, the problem seems to sort itself out within a couple of second, so I could not take a screenshot, and I was not able to reproduce.  :-(

I never observed this kind of issue before LM 20.2.

**Comment by goebbe** [comment]
Now I had the lookthrough-effect using MS-Word in a Wine setting (Cross-Over Linux) 
The effect disappeared when I opened the menu (application launcher) and was not reproducible after that.  So I could not take a screenshot - again.

This laptop uses a pretty common **Intel** integrated graphic chip - so this is not due to some unsupported graphic card. 

Since I did **not** observe this kind of behaviour before LM 20.2, I suspect that the issue might be in the Linux Mint software stack. (Cinnamon? Muffin? ?)

**Comment by kevinbutchart** [comment]
I am seeing a similar effect - originally on ubuntu 20.04 running cinnamon 4.48, but reproduced on Linux Mint 20.3 (cinnamon version 5.2.7

The following steps allow the problem to be reproduced. Immediately after boot, launch one of these applications 

- xeyes
- xcalc
- zenity --info --title test --text test

without launching any other applications (if you need to launch the above from a terminal, run them with nohup and then close the terminal). Then minimise and remaximise the app window and then move the mouse over the window and back off it a few times. The window often becomes translucent. xcalc and xeyes, although not really very useful apps now days, are the easiest to see the effect . Most other windows go fully translucent. 
![20220120_153413 SMALL](https://user-images.githubusercontent.com/1140270/150493203-efb66539-2687-4d7f-9e36-6c8c577c901b.jpeg)
![20220120_153455 SMALL](https://user-images.githubusercontent.com/1140270/150493471-1ef9f77b-ba6a-443a-a4a6-34e7b53e07c0.jpeg)

**Comment by kevinbutchart** [comment]
I have not been able to reproduce this on cinnamon2d or other window managers. Also, I have had to take photos of the screen as the screenshot facility seems to re-composite the screen so the glitch disappears. (which may be a difference from the earlier posts)

The issue is easiest to reproduce with only one window open, but very occasionally I've seen it with more windows, here is an example.

![20220120_161835 SMALL](https://user-images.githubusercontent.com/1140270/150494074-396c2f95-2c2f-4dc9-8bd2-f81b51b48fd8.jpeg)
 And what the screen shot thought the screen was:
![Screenshot from 2022-01-20 16-20-29](https://user-images.githubusercontent.com/1140270/150494163-317e62dc-2c5e-4e86-b8a4-9ef40c8ada82.png)

**Comment by kevinbutchart** [comment]
And one showing it happen to firefox - it only seems to be reproducible if the firefox window is smallish and on the right hand side of the screen. Here the reproduction step was minimise-> unminimise - click in search bar

![20220121_113343 MEDIUM](https://user-images.githubusercontent.com/1140270/150521307-7ad37e0c-ac0e-40bb-bcb5-8a9aeffbd10e.jpeg)
And the screenshot of the same screen:

![firefoxonly](https://user-images.githubusercontent.com/1140270/150521372-2b9c4672-b4a6-4bef-9d30-fa754ae7802f.png)

And finally - if multiple application windows are shown, it only seems possible to reproduce it on the right-most window

![20220121_112330 MEDIUM](https://user-images.githubusercontent.com/1140270/150521671-d2cf690b-f3df-4422-8123-7390bb076a1e.jpeg)
(and expected screenshot)
![firefox](https://user-images.githubusercontent.com/1140270/150521723-7f2a43b3-879a-4154-90b5-790279d61867.png)

**Comment by goebbe** [comment]
I upgraded to Linux Mint 21 (cinnamon) recently and I did not observe the reported issue recently with intel graphic card. 
I propose to close this bug after another confirmation.

**Comment by goebbe** [comment]
Just to confirm, that with Linux Mint 21 (cinnamon) I did not encounter this issue during the last weeks.
This issue seems to be fixed.   I recommend closing the bug as fixed. 

However, this might still be an issue in Mint 19.2 as originally reported by me. 
So it depends on the policy of the LM-Team if the bug can be closed.

**Comment by s1ynsec** [comment]
I encountered a similar issue when using the Update Manager in Linux Mint Cinnamon. The window mixed with the wallpaper. Here’s a screenshot of the bug.
![bug1](https://github.com/user- /assets/c04e5a2d-d80b-412c-bf05-330af5a441c8)

how it occured : was playing with the window with mouse dragging it

**Comment by goebbe** [comment]
@s1ynsec Thanks for reporting the issue.  I am the original reporter of the bug.  
Note that the software stack hast changed quite a bit, since I reported the bug, three years ago. 

If you can reproduce the issue, please open a new issue and report your hardware/ software and a recipe to reproduce.

**Comment by goebbe** [comment]
I close this issue. 
Reason: I am the original reporter of the bug and I did not run into this issue for years.
Today I have a different computer (now with AMD graphics) and run a different software stack (LM22) - so I could not even  try to reproduce this issue under the reported conditions.  
If you encounter similar issues, please open a new issue.
