### ISSUE TITLE
[Feature request] Remove pulseaudio dependency

### ISSUE THREAD

**Issue by triazatriborinane** [linuxmint/Cinnamon#10392]
Currently pulseaudio is a dependency of cinnamon-settings-daemon. I think it will be nice for the people intending to switch to pipewire if this wasn't the case.

**Comment by leigh123linux** [comment]
I doubt this will happen for years as it will break older distro's including Linuxmint.
Cinnamon works fine using pulseaudio-libs and pipewire-pulseaudio.

Pulseaudio isn't needed, only the libs are required.

```
[leigh@mpd ~]$ rpm -qa *\pulseaudio\*
pulseaudio-libs-15.0-2.fc35.x86_64
pulseaudio-libs-glib2-15.0-2.fc35.x86_64
pulseaudio-libs-devel-15.0-2.fc35.x86_64
pipewire-pulseaudio-0.3.38-1.fc35.x86_64
[leigh@mpd ~]$ sudo dnf list pulseaudio
[sudo] password for leigh: 
Last metadata expiration check: 0:11:54 ago on Fri 15 Oct 2021 13:47:33 BST.
Available Packages
pulseaudio.x86_64                       15.0-2.fc35                       fedora
[leigh@mpd ~]$
```

**Comment by triazatriborinane** [comment]
Oh so it's just a pacman problem rather than a cinnamon problem (pacman lists pulseaudio as a dependency of cinnamon). Thank you.

**Comment by leigh123linux** [comment]
Archlinux bundles everything into one package, see 

https://archlinux.org/packages/extra/x86_64/pulseaudio/

Try filing a bug/request against it so they can improve their packaging to split the libs.
