### ISSUE TITLE
Grouped window list not updating icons

### ISSUE THREAD

**Issue by Schildkroet** [linuxmint/cinnamon#10401]
```
 Kernel: 5.11.0-38-generic x86_64 bits: 64 Desktop: Cinnamon 5.0.6 
 Distro: Linux Mint 20.2 Uma
 ```

**Issue**
The grouped window list does not update some icons of newly started applications (it only shows the generic icon). In my case this happens with "Oracle VM Virtual Box". If i restart the grouped window list or cinnamon, the icon is correctly shown.

![image](https://user-images.githubusercontent.com/29074960/137868624-c4289c50-0cc4-458c-9c56-0389397ceffb.png)
_Left_: Icon after cinnamon restart
_Right_: Icon before cinnamon restart

**Steps to reproduce**
Start new virtual machine in Oracle VM Virtual Box

**Expected behaviour**
The icon is updated automatically after start of application

**Comment by ronyala** [comment]
Hi @Schildkroet, I created a PR ( #10439 ) That fixed that issue for me, if you would like to try it.

**Comment by Schildkroet** [comment]
Hello,
thanks for your fix. Is there a readme how to build correctly? I tried building on LM20.2, but constantly ran into dependencies error etc...

**Comment by ronyala** [comment]
You can follow the guide here https://linuxmint-developer-guide.readthedocs.io/en/latest/building.html
I personally prefer using the daily builds PPA `ppa:linuxmint-daily-build-team/daily-builds` and manually copy-pasting the changes to the files, as the javascript part stays the same before and after compilation (probably in `/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/appGroup.js)`

**Comment by Schildkroet** [comment]
my bad, didn't realise i can just copy the file.
But i can confirm it works
