### ISSUE TITLE
Browser tab changing workspaces when detached

### ISSUE THREAD

**Issue by fp-big5** [linuxmint/cinnamon#10429]
```
 * Cinnamon version (cinnamon --version): **Cinnamon 5.0.6**
   - Please specify if you are using the daily builds PPA: **Not using**
   
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...): **Linux Mint 20.2 Uma**
 
 * Graphics hardware *and* driver used: **Mesa Intel(R) UHD Graphics 620 (WHL GT2) (0x3ea0)**
 
 * 32 or 64 bit: **64 bit**

 * Attach ~/.xsession-errors, or /var/log/syslog: **no errors shown on log files**
 ```

**Issue**

Chrome and Edge tabs changes from current workspace to last workspace where a chrome/edge instance was launched when the tab is detached.

**Steps to reproduce**

https://user-images.githubusercontent.com/91618990/139438227-75ffbc98-a2cd-49bb-aa6f-b27e7607e375.mp4

**Expected behaviour**

Keep detached tab on the same workspace

**Other information**

**Configuration info, if applicable**: ...

```

name of display: :0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Intel (0x8086)
    Device: Mesa Intel(R) UHD Graphics 620 (WHL GT2) (0x3ea0)
    Version: 21.0.3
    Accelerated: yes
    Video memory: 3072MB
    Unified memory: yes
    Preferred profile: core (0x1)
    Max core profile version: 4.6
    Max compat profile version: 4.6
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
OpenGL vendor string: Intel
OpenGL renderer string: Mesa Intel(R) UHD Graphics 620 (WHL GT2)
OpenGL core profile version string: 4.6 (Core Profile) Mesa 21.0.3
OpenGL core profile shading language version string: 4.60
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 4.6 (Compatibility Profile) Mesa 21.0.3
OpenGL shading language version string: 4.60
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile

OpenGL ES profile version string: OpenGL ES 3.2 Mesa 21.0.3
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20

```

**Comment by ilya-vasilyev** [comment]
**The same here**.
Happens on all WebKit based browsers: Chrome, Chromium, Edge.
It started roughly around the release of 95 version of Chrome, so it could be somehow related.

**Comment by fp-big5** [comment]
Just to update, I've tested on KDE Plasma on Mint and this issue does not happen.

It also doesn't happen on Mint XFCE.

This is only happening in cinnamon.

Cinnamon is pretty much useless right now to be used with multiple desktops.

If anyone could hop into this issue so we solve this, would be appreciated.

**Comment by fp-big5** [comment]
Hello Guys.

I've updated MS Edge today and this problem is not happening in edge anymore.

This issue is only happening on **Chrome using Cinnamon**. Using chrome in any other DE works fine.

I'll try using MS Edge for a while. It's easier to change the browser than changing the whole DE for another one.

I'm still available to troubleshoot this issue at anytime!

**Comment by mtwebster** [comment]
> Cinnamon is pretty much useless right now to be used with multiple desktops.

That's a bit of an exaggeration.

This happens in gnome-shell also.

It appears fixed in chromium 97 beta:
https://www.dropbox.com/s/t61s63i3vd6z9md/chromium_97.0.4692.20~beta%2Buma_amd64.deb?dl=0
