### ISSUE TITLE
lshw german

### ISSUE THREAD

**Issue by alexi3** [linuxmint/cinnamon#10436]
```
System:    Kernel: 5.11.0-38-generic x86_64 bits: 64 compiler: N/A Desktop: Cinnamon 5.0.6 Distro: Linux Mint 20.2 Uma
           base: Ubuntu 20.04 focal
Machine:   Type: Laptop System: HP product: HP Laptop 15s-fq2xxx v: N/A serial: <filter>
           Mobo: HP model: 87FE v: 57.16 serial: <filter> UEFI: AMI v: F.10 date: 04/15/2021
 ```

**Issue**
issue in german translation for lshw

**Steps to reproduce**

Language English, United States:
sudo lshw -class memory
[...]
  *-memory
       description: System Memory
       physical id: 1b
       slot: System board or motherboard
       size: 8GiB
     *-bank:0
          description: SODIMM [empty]
          physical id: 0
          slot: Bottom - Slot 1 (left)
     *-bank:1
          description: SODIMM DDR4 Synchronous 3200 MHz (0.3 ns)
          product: NT8GA64D88CX3S-JR
          vendor: Nanya Technology
          physical id: 1
          serial: xxxxxxxx
          slot: Bottom - Slot 2 (right)
          size: 8GiB
          width: 64 bits
          clock: 3200MHz (0.3ns)

Language German, Germany:
sudo lshw -class memory
[...]
  *-memory
       Beschreibung: Systemspeicher
       Physische ID: 1b
       Steckplatz: Systemplatine oder Hauptplatine
       Größe: 8GiB
     *-bank:0
          Beschreibung: SODIMMProject-Id-Version: lshwReport-Msgid-Bugs-To: FULL NAME <EMAIL@ADDRESS>PO-Revision-Date: 2012-05-30 08:16+0000Last-Translator: Hendrik Knackstedt <Unknown>Language-Team: German <de@li.org>MIME-Version: 1.0Content-Type: text/plain; charset=UTF-8Content-Transfer-Encoding: 8bitX-Launchpad-Export-Date: 2021-08-02 16:47+0000X-Generator: Launchpad (build 8bd362bf86c4b35e805f897f03c203e3576a7006) [leer]
          Physische ID: 0
          Steckplatz: Bottom - Slot 1 (left)
     *-bank:1
          Beschreibung: SODIMM DDR4 Synchron 3200 MHz (0.3 ns)
          Produkt: NT8GA64D88CX3S-JR
          Hersteller: Nanya Technology
          Physische ID: 1
          Seriennummer: xxxxxxxx
          Steckplatz: Bottom - Slot 2 (right)
          Größe: 8GiB
          Breite: 64 bits
          Takt: 3200MHz (0.3ns)
**Expected behaviour**
     *-bank:0
          Beschreibung: SODIMM [empty]
          Physische ID: 0
          Steckplatz: Bottom - Slot 1 (left)

**Other information**
 The email account de@li.org does not exist.

**Comment by leigh123linux** [comment]
You need to file the issue against lshw at ubuntu bug tracker.
