### ISSUE TITLE
Win+N (invoke notification window) is missing from keyboard shortcuts settings

### ISSUE THREAD

**Issue by mikkovedru** [linuxmint/cinnamon#10449]
```
 * Linux Mint 20.2 Cinnamon
 * Cinnamon 5.0.6
 ```

**Issue**
- Win+N key combination opens the notification window.
- I don't want that. I want to use that key combination for something actually useful.
- But I can't disable it because it is missing from the `Settings/Keyboard/Shortcuts`.

**Comment by mtwebster** [comment]
Applet-specific keybindings are configured in the applet:

If you right-click the notification applet and "Configure" you can clear the keybindings (click on the binding, then 'backspace' to clear it - the tooltip for it explains this). Then you can use those for other actions.

**Comment by mikkovedru** [comment]
@mtwebster 
Thank you!

I tried to click on the `Win+N` + "Nofication Settings":
![image](https://user-images.githubusercontent.com/2521942/141807766-8558036d-23f4-4de4-a8fc-4ac83944d0d7.png)
, but it gave me the following window:
![image](https://user-images.githubusercontent.com/2521942/141807905-2b3412c0-63a3-4a89-940b-fbe0dfb5b450.png)

So what I should have done is to:
## Variation 1
Right click on the applet when it is present (with notifications)
![image](https://user-images.githubusercontent.com/2521942/141808341-e21b1dd2-f69d-4acb-ac20-53d3f4eade3b.png)
and choose "Configure..." from there.

Or 

## Variation 2
Go to "System Settings"/"Applets"
![image](https://user-images.githubusercontent.com/2521942/141809136-36c92aaf-ebf7-4a7f-a545-36776de88cd7.png)
find the applet and check its settings.
![image](https://user-images.githubusercontent.com/2521942/141809321-4c4d2a0d-b86c-481f-8778-d89fa2857a60.png)
![image](https://user-images.githubusercontent.com/2521942/141809953-7619fcef-85d3-4920-b257-964b749ede9a.png)

# Conclusion?
Wouldn't you say that this is a very non-obvious place to search a setting? I had the right idea about right-clicking the applet, but even that didn't help. I did not know that there were two different settings-windows, one of which is accessible from 1 place and another accessible from 2 places with no link between them. 

@mtwebster 
Shouldn't there be only one settings window or at least some kind of way to switch between windows? Should I report it somehow differently or somewhere else? Or is this bug report enough?
