### ISSUE TITLE
Empty vertical stripe 40px wide on the left edge of the screen

### ISSUE THREAD

**Issue by jfikar** [linuxmint/cinnamon#10461]
```
 * Cinnamon version 5.0.7
 * Distribution Mint 20.2
 * Graphics hardware *and* driver used: Intel i915
 * 64 bit
 ```

**Issue**
On the screen there is a vertical stripe 40px wide on the left side. No window or wallpaper can be displayed there. Cursor can go there. The bar down is also displayed correctly. The stripe is of the same width as the (LM) start button in the bar. The screen resolution is 1920x1080. See the screenshot attached.

**Steps to reproduce**
The screen was fine until recently I discovered the stripe. Not sure what exactly I did. Maybe just an update. Also I had external screen connected recently via HDMI. Now I'm not able to get rid of the stripe.

![stripe](https://user-images.githubusercontent.com/9248946/141686072-9331e97e-f1c1-4dcd-ae52-4c58094a63f2.png)

**Comment by leigh123linux** [comment]
Try 'right click' on the blank panel and select remove.

**Comment by jfikar** [comment]
Ohhhh, OK. It's gone. Thank you :+1:
