### ISSUE TITLE
Too Many Windows in the Taskbar Overlaps the System Tray Area

### ISSUE THREAD

**Issue by equasman** [linuxmint/cinnamon#10466]
```
* Cinnamon 5.0.4
* Mint 20.2
* Graphics hardware: Intel 2nd Generation Core Processor Family Integrated Graphics
* Driver: i915
* 64 bit
 ```

**Issue**
Too many open windows in the taskbar crosses its area and overlaps the system tray area. As a result, can't see the system tray icons.

**Steps to reproduce**
Open as many windows until they crosses the taskbar and goes into system tray's area.

**Expected behaviour**
No matter how many open windows you have, they shouldn't overlap system tray area.

**Other information**
![Untitled](https://user-images.githubusercontent.com/61104876/142032178-6510cb14-d047-4547-9562-ecc24212de45.png)

**Comment by JosephMcc** [comment]
https://github.com/linuxmint/cinnamon/issues/5042
