### ISSUE TITLE
Default keyboard shortcuts

### ISSUE THREAD

**Issue by Mr-Bajs** [linuxmint/cinnamon#10463]
* Distribution - (Mint 20.2)

The default keyboard shortcuts in Cinnamon comes with _Ctrl + Arrowkey Left_ and _Ctrl + Arrowkey Right_ to change the position of the current window. Just this setup is bad because it overrides the regular function of _Ctrl + Left/Right_ that skips the position of the text cursor in text and code. 

The _Ctrl + Left/Right_ shortcut as text cursor shortcut is as far as i know pretty standard. It should also be this in Cinnamon. 
Course it's easy to change yourself in the keyboard settings jus, but this shouldn't be the case. Cinnamon should be using the Ctrl + Left/Right to the desktop convention of text cursor by default.

Maybe just change the Ctrl to Super or something.

**Comment by mtwebster** [comment]
These combinations are unused by default - word skip works fine for me in the text editor.. Window tiling is `super-<direction>`

**Comment by Mr-Bajs** [comment]
Really? 
Okey, then i guess so. Must have been my fault, changing them without remebering having done so.

**Comment by mtwebster** [comment]
Are you using an odd keyboard layout?  Do the super/control keys work properly otherwise?

**Comment by Mr-Bajs** [comment]
Nordic ISO Layout.
Cinnammon 5.0.7 
The Super and Control works fine. I think it's just an error on my fault.

But i noticed that this seams to be an issue though #10449

**Comment by mtwebster** [comment]
Ok - I resolved that other issue as well.
