### ISSUE TITLE
New calendar has extra space

### ISSUE THREAD

**Issue by NerdsMaxx** [linuxmint/cinnamon#10471]
```
 * Cinnamon version (cinnamon --version): Cinnamon 5.2.0
   I'm using daily build ppa  (https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds).
 * Distribution - Mint 20.2 with daily build
 * Intel UHD Graphics and NVIDIA GP108M [GeForce MX250]
 * 64 bit
 ```

**Issue**
I updated the system with daily build ppa

![image](https://user-images.githubusercontent.com/69761459/142227356-718db613-627c-46f4-92db-ddddfb664473.png)

**Comment by mtwebster** [comment]
Themes still need to catch up to the changes, including the mint ones.

**Comment by NerdsMaxx** [comment]
I understand, thanks.
