### ISSUE TITLE
Menu Editor causes unresponsiveness and memory leaking

### ISSUE THREAD

**Issue by Danko8321** [linuxmint/Cinnamon#1047]
This is something I need to call your attention on, since I've tested this a few times now and I seem to find this bug on every machine:

Cinnamon is not perfect and as everything eles, it suffers from memory leaks. However, most of them have been fixed... Most, but it seems that not this one. The thing is that when deleting or modifying items from the menu using the editor, Cinnamon's memory usage rapidly spikes, some times even causing the system to freeze temporarily and even a forced Cinnamon restart.

I have seen this going on for a while and didn't want to add it to another thread because of the fact that I know the cause (or at least the trigger). Anyway, OS details are as follow:

OS: Linux Mint 13
Cinnamon version: 1.4-UP3
Muffin Version: 1.0.3-UP2

Please let me know if you need any extra info and I will be more than happy to post it.

Cheers. Danko.

**Comment by lestcape** [comment]
I think, this can not be reproduced any more... @JosephMcc is cleaning invalid issues, please close it if it's solved.

**Comment by JosephMcc** [comment]
Old issue and the OP never responded to requests to test on newer version.
