### ISSUE TITLE
Calendar applet does not support multiple lines

### ISSUE THREAD

**Issue by dannypike** [linuxmint/cinnamon#10478]
**Feature request / question**

I have just installed Linux Mint and this may be possible, but I can't see how to do it. I have the task bar along the left hand side, but the Calendar applet does not appear to support multiple lines, which is what I need to be able to fit the day, date and time into the space available.

A `strftime()` format something like this is what I would like:
```
%A\n%b %e\n%H:%M:%S
```

Is that possible / would you please consider adding it? I'd have a go at doing it myself, but I'm only just starting out in Linux.

```
 * Cinnamon version 5.0.7
 * hostnamectl reports:
      Operating System: Linux Mint 20.2
            Kernel: Linux 5.13.0-21-generic
      Architecture: x86-64
 ```

**Comment by bridnour** [comment]
Instead of:
`%A\n%b %e\n%H:%M:%S`

Try:
`%A%n%b %e%n%H:%M:%S`

The neline character in strftime in this case is %n not \n.

See: [For a Good Strftime](https://www.foragoodstrftime.com/)

**Comment by dannypike** [comment]
Thank you, that's perfect!
