### ISSUE TITLE
Issues with two network cards

### ISSUE THREAD

**Issue by TheBlueMatt** [linuxmint/Cinnamon#1048]
If you have 2 wireless cards at startup - cinnamon will ask you for wifi password twice, if you click cancel both times, it will wait a minute and ask you again...if you click cancel both times again, it will immediately crash and make you log out.

Also, the second time it asks the password will not be auto-filled.

Oh, and (somewhat unrelated) when network manager crashes in some cases due to having two wireless adapters (see http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=675376), cinnamon will immediately crash.

Finally, and really unrelated, if you click cancel for the second wireless card once and the first card is connected, chances are you dont want the second card to connect at all, so asking again every minute seems redundant at best.

**Comment by JosephMcc** [comment]
Closing due to lack of response.
