### ISSUE TITLE
cinnamon-settings crashes when adding online account when used with newer webkitgtk

### ISSUE THREAD

**Issue by mkg20001** [linuxmint/cinnamon#10482]
```
 * Cinnamon version (cinnamon --version)
   - Please specify if you are using the daily builds PPA
     (https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds).
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
   - NixOS 22.05 unstable
 * Graphics hardware *and* driver used
  - qemu - llvm
 * 32 or 64 bit
  - 64
 * Attach ~/.xsession-errors, or /var/log/syslog
 ```

**Issue**
Adding an account crashes cinnamon-settings with

```
** (cinnamon-settings.py:34700): ERROR **: 17:57:40.026: GApplication is required for xdg-desktop-portal access in the WebKit sandbox.
```

**Steps to reproduce**

1. cinnamon-settings online-accounts
1. Click on any account that requires a web sign in (google for ex)
1. crash

**Expected behaviour**

Doesn't

**Other information**

This occurs because of a recently introduced upstream change in webkitgtk https://github.com/WebKit/WebKit/commit/7a8bd0f5889b9149cb6655e476cf29ff8869d4ac

Not sure if cinnamons version is new enough to reproduce

**Configuration info, if applicable**

**Comment by mtwebster** [comment]
Already fixed: https://github.com/linuxmint/cinnamon/commit/77ed66050f7df889fcb7a10b702c7b8bcdeaa130

**Comment by cpvb2** [comment]
This still appears to be an issue. Cinnamon crashes completely when I try to link an account. Running 21.1.

**Comment by leigh123linux** [comment]
@cpvb2  Start a new issue.
