### ISSUE TITLE
[ 7351.999456] cinnamon[1344]: segfault at 0 ip 0000000000000000 sp 00007ffe90b32d68 error 14 in .glzpfNYQ (deleted)[40698000+2000] [ 7351.999478] Code: Bad RIP value.

### ISSUE THREAD

**Issue by mb-real** [linuxmint/cinnamon#10491]
```
 * Cinnamon version : (Cinnamon 5.0.7)
   - Please specify if you are using the daily builds PPA : (No)
     (https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds).
 * Distribution -: (Mint 20.2)
 * Graphics hardware *and* driver used : (Nvidia GT9400) and driver (Nvidia 340.8)
 * 32 or 64 bit : (64 bit)
 * Attach ~/.xsession-errors, or /var/log/syslog : dmesg
 ```

**Issue**
Crash and hang while opening many tabs in Google Chrome

dmesg :
[ 7351.999456] cinnamon[1344]: segfault at 0 ip 0000000000000000 sp 00007ffe90b32d68 error 14 in .glzpfNYQ (deleted)[40698000+2000]
[ 7351.999478] Code: Bad RIP value.

**Steps to reproduce**
Crash and hang while opening many tabs in Google Chrome

**Expected behaviour**

**Other information**

**Configuration info, if applicable**
If this bug report is related to an Applet, Desklet or Extension, please paste (or use a pastebin service) the offending extension's settings, if it has any.  You can obtain this by opening its configuration, clicking the 'hamburger' button in the upper-right corner of the window, and selecting "Export to a file". **Please be sure to review the contents and remove any personal data it may contain.**

```

Please paste here

```
[eror.txt](https://github.com/linuxmint/cinnamon/files/7625958/eror.txt)

**Comment by mb-real** [comment]
The Cinnamon desktop application must properly manage the memory of other applications, so that if the RAM and swap are full, the application that has occupied the RAM will alert the user and ask the user to close it.

**Comment by leigh123linux** [comment]
> The Cinnamon desktop application must properly manage the memory of other applications, so that if the RAM and swap are full, the application that has occupied the RAM will alert the user and ask the user to close it.

I strongly disagree, cinnamon shouldn't have any role in handling other processes.
Systemd oomd  should handle the memory management.

http://manpages.ubuntu.com/manpages/hirsute/man1/oomd.1.html
