### ISSUE TITLE
caribou

### ISSUE THREAD

**Issue by mkg20001** [linuxmint/cinnamon#10496]
The GNOME caribou package does not seem to be used by the GNOME team anymore and seems to lack updates https://gitlab.gnome.org/GNOME/caribou/

Starting with vala 0.52 caribou no longer builds

What's linuxmint's plan on continuing with that?

Will caribou be replaced? How is/will the package maintained downstream?

**Comment by leigh123linux** [comment]
NixOS will need to patch their package.
Fedora 35 built caribou ok with vala-0.52.4 and 36 with vala 0.54.3

**Comment by mkg20001** [comment]
Yes we found that patch
But what about the lack of updates? Package doesn't seem to be maintained too well. I mean if it's not a big deal then it's not a big deal but 5 years without a proper release seems like a dead package to me.
