### ISSUE TITLE
Cinnamon <-> parted should not depend on each other

### ISSUE THREAD

**Issue by avlap** [linuxmint/cinnamon#10500]
One can't remove parted without removing cinnanom. This should be possible.

I want to make a installation for people, where they've all the root rights, but I want to prevent them to mess with the partitioning. So I uninstalled parted, which gave me problems with cinnamon session right away. I did the same setup in Kubuntu and there I could remove the partitioner without problems. That's the expected behavior.

**Comment by mtwebster** [comment]
It's not required by cinnamon, it's required by udisks2, which is required by a number of other packages (and so on) until it's a package cinnamon depends on. KDE has a very different 'ecosyatem', and it's understandable there'd be underlying differences.

If you trust the users with root, couldn't you trust them to not mess with partitioning? Even if you could manage what you wish here, it wouldn't stop a determined user in the least. Are you preventing them installing packages? Or creating a bootable usb (from which they could effect partition changes). Just observations, obviously I don't know the entire scenario.

Regardless, there's little we can do at this level. It looks like it may be an ubuntu requirement (parted->udisks2->gnome-disk-utility->ubuntu-minimal) which Mint inherits. You can run `aptitude why <packagename>` to analyze the dependencies (along with `apt depends/rdepends`).
