### ISSUE TITLE
Cinnamon workspaces' keyboard shortcuts conflict with apps'

### ISSUE THREAD

**Issue by Asghwor** [linuxmint/cinnamon#10507]
The keyboard shortcuts to manage workspaces on Cinnamon are, by default, either a `ctrl-alt-[arrow]` or `ctrl-alt-[number]` combination.

For instance:
- To switch between workspaces one by one, you'll press `ctrl-alt-left` and `ctrl-alt-right`.
- To switch to the third workspace, it will be `ctrl-alt-3`
- To show all workspaces, `ctrl-alt-up`.
- To show all windows of one workspace, `ctrl-alt-down`.

The problem is: many apps use `ctrl-alt-key` shortcuts internally, and expect them to be free. Specially web-apps.

For instance, when using Google Docs, you can change the text from normal to a heading type by pressing `ctrl-alt-number`. So, to get a heading 1, you'd press `ctrl-alt-1`. This wouldn't work on Cinnamon, however.

Another example: when writing a document on Jira's Confluence, to create a new row for a table, you can either go through a lengthy process to do it with the mouse, or do it with `ctrl-alt-arrow`. This also wouldn't work on Cinnamon, however.

`ctrl-alt-arrow` also seems to trigger some weird sound effect on Jitsi, forcing me to change tabs everytime I wanted to change workspaces.

This choice can also affect other shortcuts that are not defaults on Cinnamon, since a user, when creating new shortcuts, will make it follow the standard of the system.

---

My suggestion would be to change the shortcuts to include super in them. This way, they will never really conflict with any apps, since they do not use the key.

**Comment by Secret-chest** [comment]
> My suggestion would be to change the shortcuts to include super in them. This way, they will never really conflict with any apps, since they do not use the key.

Good idea. I have changed them to that before, actually.

**Comment by Secret-chest** [comment]
Suggestions:
Switch workspaces: Super + Tab and Super + Shift + Tab (makes more sense to use Tab)
Show all windows: Super + Down
Show all workspaces: Super + Up
Number workspace: Super + Alt + 3

For tiling windows we can add Control to the shortcuts.

**Comment by Asghwor** [comment]
Nice suggestions. I hadn't really thought of using shift+tab, but that makes sense.

I would opt for `super-w` and `shift-super-w` for showing all windows / all workspaces, though, mostly because I'm used to using `super-up` and `super-down` for maximizing/minimizing a window.

**Comment by mtwebster** [comment]
Ctrl-alt-number keys are unused by Cinnamon by default, so they should be available by programs.

Ctrl-arrow up/down/left/right shortcuts won't get changed because they've *always* defaulted to how they currently are, and are far too prominently used. We're not going inflict that change on the rest of our users, along with the cascading effect of having to then change tiling shortcuts, etc... Their current behavior is also fairly standard on other desktops as well.

These are easy enough to clear for those who wish to repurpose them.

**Comment by clefebvre** [comment]
Sublime-merge uses ctrl-alt-down.

**Comment by Asghwor** [comment]
Some of these applications, like Google Docs, are for normal users, though.

Would granny or Android guy know how to configure their system's keyboard shortcuts?
