### ISSUE TITLE
Linux Mint Website TYPO

### ISSUE THREAD

**Issue by aschwartz2018** [linuxmint/cinnamon#10508]
**Issue**
![image](https://user-images.githubusercontent.com/68354532/145107013-0ca84e88-9358-4cd0-8ae3-360ba13097f7.png)

**Steps to reproduce**
https://linuxmint.com/#:~:text=default%20and%20no-,unecessary,-questions%20are%20asked
(It should be "unnecessary" not "unecessary")

I apologize that this is the wrong place for this report

**Comment by clefebvre** [comment]
Typo fixed. Thanks @aschwartz2018
