### ISSUE TITLE
Add configurable delay to Hot corner

### ISSUE THREAD

**Issue by juliao** [linuxmint/Cinnamon#1050]
I think it would be nice if there were a option to add a delay (some milliseconds) to the 'Hot corner', to avoid accidental activation of it. By default should come as 0 ms and user could configure it.

**Comment by Luke-Nukem** [comment]
Good to see someone has taken this on. It's a definite needed item.

**Comment by theoar** [comment]
+1

**Comment by gordon-morehouse** [comment]
This is by far the biggest annoyance I have with Cinnamon on a day-to-day basis. +1000 for a configurable hover delay.

**Comment by nyeates** [comment]
https://github.com/linuxmint/Cinnamon/blob/master/js/ui/hotCorner.js

My guess is that it would be a change in this file, if anyone wants to have a look. There is some code about jitter that assures if the mouse is slightly moving in and out of a certain area, it doesnt trigger the hot corner multiple times. Not sure if that is related or gives someone a hint. I don't know enough to make this change, but maybe someone else can.

**Comment by ACinnamonUserInUK** [comment]
+1.

**Comment by Hobo4ssassin** [comment]
@nyeates I haven't tried it yet, but I would guess that changing line 12 to a higher value is the ticket here

**Comment by nakhla** [comment]
a better alternative "Activate when pushed" like in KDE, that require a deliberate push to trigger the action of hotcorner
or at least a delay option from terminal like:
`gsettings set org.cinnamon hotcorner-delay 500`
