### ISSUE TITLE
[Feedback] More preferences options in menus, makes it more complicated actually

### ISSUE THREAD

**Issue by avlap** [linuxmint/cinnamon#10501]
Mint puts a lot of work in making Linux easy. One thing I noticed, comparing it with other distributions, it shows a lot of items in the main menu under 'preferences' (I count 39 subitems: Accessibility, Acount details ... etc etc). 
I think one button for preferences and having the options only there makes it far more easy to find what you need.

**Comment by rgreen5** [comment]
I tend to agree; why duplicate what is already in Systems Settings?

**Comment by mtwebster** [comment]
Cinnamon's settings are available in favorite programs (icons down the left side), readily visible. You can also reach them by right-clicking the panel.  Some things in the preferences 'category' have nothing to do with cinnamon - it'd inappropriate to have them all in a single window, and if we did, how would that be any different than having them all in the menu?

The individual Cinnamon settings 'modules' are individually listed so people can type 'mouse' and immediately go where they wish, without having to navigate yet another UI to get there. This is all fairly standard behavior among other desktops (and Windows).
