### ISSUE TITLE
[Feature Request] Add dark mode in cinnamon

### ISSUE THREAD

**Issue by prorounak2005** [linuxmint/cinnamon#10518]
* Cinnamon version (cinnamon --version) - I am using cinnamon 5.0.7-3
 * Distribution - Arch linux 5.15.7.arch1-1
 * Graphics hardware *and* driver used - GTX 1650
 * 32 or 64 bit -  64 bit 
 

**Issue**

It would mean a lot to if there was a dark mode / dark theme for cinnamon because i use my pc at night and the light mode really hurts my eyes.

**Comment by WhosyVox** [comment]
Cinnamon has dark themes.

```
gsettings set org.cinnamon.desktop.interface gtk-theme "Mint-Y-Dark"
gsettings set org.cinnamon.theme name "Linux Mint"
gsettings set org.cinnamon.desktop.wm.preferences theme "Mint-Y-Dark"
```

**Comment by bardiarajabi** [comment]
Cinnamon already has dark mode.
Pls double check before posting your request.

**Comment by prorounak2005** [comment]
sorry I am closing it. Thanks btw it worked :)

**Comment by benmccann** [comment]
There's now `org.freedesktop.appearance color-scheme`: https://github.com/linuxmint/cinnamon/issues/10934. This is probably more inline with what was being requested than a particular theme
