### ISSUE TITLE
Kyiv, not Kiev should be displayed as option on the mint installation page

### ISSUE THREAD

**Issue by vitaliy-guliy** [linuxmint/cinnamon#10512]
**Issue**
Installation page of the latest Linux Mint 20.2 (Cinnamon) still displays old version of the name of the capital of Ukraine.
Nowadays, it's rather to name it Kyiv instead of Kiev.

There is a campaign, which goal is to persuade English-language media and organizations to use Kyiv (derived from the Ukrainian language name) instead of Kiev https://en.wikipedia.org/wiki/KyivNotKiev for details.

BTW, if you open a wikipedia https://en.wikipedia.org/wiki/Kiev, you will be redirected to https://en.wikipedia.org/wiki/Kyiv.

**Steps to reproduce**
Run the linux installation. When you being asked for your location, pick the Ukraine on the map.

![Screenshot from 2021-12-08 15-51-19](https://user-images.githubusercontent.com/1655894/145245635-12412d7c-ba76-4fb7-a200-86232c383187.png)

**Expected behaviour**
Should display Kyiv, not Kiev.

**Comment by lestcape** [comment]
@vitaliy-guliy This is probably not helpfully as you want to be, but just to point you in the right direction. The Mint installation process (like any other distro) use an installer program that have embedded the world map and that behaviour. So, probably you want to open the issue against the installer program who is really who used that map. Also this is not the only source of that map. Cinnamon itself inside the cinnamon-setting use it also (https://github.com/linuxmint/cinnamon/blob/master/files/usr/share/cinnamon/cinnamon-settings/modules/cs_calendar.py#L10-L11), but that map is also not part of Cinnamon, is instead part of a package that is provide by the linux distributions where cinnamon is installed. So, to fix a thing like that, you need to open an issue in all distros that have the TimezoneMap package and that will be a lot of distributions. Also Gnome settings have that map embedded in his code (https://gitlab.gnome.org/GNOME/gnome-control-center/-/blob/master/panels/datetime/cc-timezone-map.c) and you also will need to open an issue there if you want it will be fixed.

**Comment by vitaliy-guliy** [comment]
@lestcape thank you for pointing me on the places, that needs to be fixed.
Yes, I see that there is a lot of distributions, but nothing is impossible.
For the `gnome-control-center` and `cinamon-settings` is clear what to do. Could you also point me on the repository with linux installer (or something like that)? Googling gives me nothing, or I just ask it wrong question.

Btw, fixing the name in gnome-control-center looks easy. I think it will be enough to perform full-text search in https://gitlab.gnome.org/GNOME/gnome-control-center/-/tree/master/panels/datetime/po-timezones and replace the city name in all the files.

I also wonder, how the Cinammon refers on linux packages. Does it use the released and pre-built packages (e.g. python) or the builder build everything from sources? I'm thinking in which Cinammon release, or even Linux Mint release,  those changes will be applied.

**Comment by lestcape** [comment]
I don't use Linux Mint, but seem to be that the installer is a fork of [ubiquity](https://github.com/linuxmint/ubiquity). If you resolved the problem in the installer fork, thats not means it will be also resolved in all the forks and the original [ubiquity source](https://launchpad.net/ubiquity/). Also there can be other installer software that can or not included the same issue with the city that you want to fix out there.

Cinnamon can be installed in several distributions and it depend of several distro package that are compiled and provided just only one time in the specific distro for all desktops installed. But cinnamon itself it also a summary of several package that are provided by Mint directly and distributions only modify a little the source to be adapted to the specific distro case. So, both scenarios are correctly, it depend of the package itself who will be the maintainer, Mint or the Distro.

I am afraid that it will be too difficult to find a definitive solution to a situation like this, not only because of the amount of dispersion of the problem, but because of the little interest that programmers generally have in an issue that is more political than about programming.

**Comment by AtomicRobotMan0101** [comment]
I agree with most of the sentiments here, **but there is a but..**.

[Cities change names](https://en.wikipedia.org/wiki/List_of_city_name_changes), as do countries.

Every place and its people have proper names, as known to locals. It shouldn't be up to me, as a Male White Western Linux Dude as to how someone in ... Tajikistan ... wants to call Chkalovsk → Chkalov.  Its up to them.

Its a matter of finding the root place for this labelling and addressing it there.

It feels like one of those things that is very important.

**Comment by fredcw** [comment]
> It shouldn't be up to me, as a Male White Western Linux Dude...

It isn't up to you and nobody said it was up to you. Your comment makes me want to puke.

**Comment by fredcw** [comment]
@clefebvre @mtwebster 

Could someone remove @AtomicRobotMan0101's comment above as it is racist and sexist and implies that only white western males can contribute to Linux.

>...as a Male White Western Linux Dude...

Linux and open source software has always been developed by people of all races, nationalities, and of both sexes and there has never been any discrimination of this kind in linux development. The anglicisation of place names is and was done by English speakers regardless of race or sex and is something that's done in every other language to make place names easier to pronounce, e.g. Paris in Italian is Paridi and London in Greek is Λονδίνο (Londino)

I've reported this to github as this is not the place for this kind of racist and sexist content.

**Comment by leigh123linux** [comment]
File the issue against libtimezone

**Comment by clefebvre** [comment]
Thanks for closing this @leigh123linux, it's definitely getting heated and it's definitely upstream from us. 

This belongs to libtimezonemap indeed: 

https://bazaar.launchpad.net/~timezonemap-team/timezonemap/trunk/view/head:/src/data/cities15000.txt

This package is maintained by Ubuntu so the bug can be reported upstream directly.

Looking at its commits, it seems to sync with geonames, which was updated to use Kyiv in English.

https://www.geonames.org/search.html?q=Kiev&country=

We are indeed talking about the English name for the city which most people now refer to, in English, as Kyiv.

https://en.wikipedia.org/wiki/KyivNotKiev

**Comment by clefebvre** [comment]
That said, looking at this lib, it hasn't been updated in 8 years.

It's also still mentioning Kiev in Mint 22 ALPHA (Ubuntu 24.04).

I'll check to see if it's used in the new Ubuntu installer. If it isn't, it's unlikely to get updated so in this case we might need to do it ourselves.

**Comment by clefebvre** [comment]
It looks like this was fixed upstream in 24.04.

This is what I see in the latest Mint 22 ALPHA (12th of June).

![image](https://github.com/linuxmint/cinnamon/assets/1138515/aec9d960-311b-406e-94be-8b2ff90bffdc)
