### ISSUE TITLE
No focus after close any windows

### ISSUE THREAD

**Issue by panther1942** [linuxmint/cinnamon#10519]
```
OS: Linux Mint 20.1 x86_64 
Host: GE60 2PG REV:1.0 
Kernel: 5.13.0-22-generic 
Uptime: 1 day, 17 mins 
Packages: 3559 (dpkg), 8 (flatpak) 
Shell: bash 5.0.17 
Resolution: 1920x1080 
DE: Cinnamon 
WM: Mutter (Muffin) 
WM Theme: CBlack (Mint-Y-Dark) 
Theme: Mint-Y-Dark-Aqua [GTK2/3] 
Icons: Vibrancy-Kali-Full-Dark [GTK2/3] 
Terminal: konsole 
CPU: Intel i7-4710MQ (8) @ 3.500GHz 
GPU: Intel 4th Gen Core Processor 
GPU: NVIDIA GeForce GTX 850M 
Memory: 5994MiB / 15922MiB
 ```

when i close window, no window is foucsed

i launch a terminal
start any program from terminal
close the program
i want the terminal is focused
but no window is focused

**Comment by WhosyVox** [comment]
Could I ask you to check the Window Focus behaviour under Settings - Windows - Behaviour tab?
I tested with the default (click) with no luck, but for example the 'mouse' option would result in the behaviour you describe as your mouse would not be over the terminal window after closing an application.

**Comment by panther1942** [comment]
> Could I ask you to check the Window Focus behaviour under Settings - Windows - Behaviour tab? I tested with the default (click) with no luck, but for example the 'mouse' option would result in the behaviour you describe as your mouse would not be over the terminal window after closing an application.

i set click
i create a new user and all is normal, i think that maybe cause by some applet or something,my pc is run over 1 day, i modify some applet before, add lunar to the calendar,and limit history filename length, i reset all applet and reboot, its normal now, thank much
