### ISSUE TITLE
Distribution bullies user if wants to add a search engine to the list of optional search engines

### ISSUE THREAD

**Issue by ZackYovel** [linuxmint/cinnamon#10511]
```
 * Cinnamon version Cinnamon 5.0.7
   - Please specify if you are using the daily builds PPA
     (https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds). No
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 20.2
 * Graphics hardware *and* driver used not relevant
 * 32 or 64 bit not relvant
 * Attach ~/.xsession-errors, or /var/log/syslog not relevant
 ```

**Issue**
Not adding every single search engine in existence - cool. Good, actually. Would be a huge mess.
Hiding the link to the instructions on how to add search engines at the bottom of the relevant page in Firefox settings - not cool.
Hiding the links to the specific instructions for the different search engines at the bottom of the page in the link and using very small icons that are hard to see for people with eyesight that is not good but only okay due to age or whatever other reason - very not cool!
Making the instructions themselves so unintuitive and unnecessarily complicated - pathetically uncool...

**Steps to reproduce**
Try to add a search engine to the list of optional ones in Firefox > Settings > Search in the drop list under "Default Search Engine"

**Expected behaviour**
1. Just let me insert the web address of the search engine I want to use. It identifies a search engine uniquely, so you can do everything you need using this info.

Or at the very least:
2. The in the settings page should be next to the list itself, because it is expectable and very likely that a user will look for it after opening this list.
3. Icons on the opened page should be visible in the screen without needing to scroll, otherwise it seems like you are actually preventing the user from adding any other search engines to Firefox. Also, they should be BIG. Icons are meant to bi BIG. They usually are. Be friends, don't punish your users for whatever you don't like about some search engine. You do realize they are the ones you hurt, don't you?
4. Clicking said icon should be the final action, no other action should be required. Especially not if this other action is nothing more then clicking a different link, and everything else (right click) is just a way to hide this other icon from the user.
5. Be user-friendly. Because if Linux Mint is not user-friendly, then no f*&king Linux disto is. And that would be very sad.

**Other information**

**Configuration info, if applicable**
If this bug report is related to an Applet, Desklet or Extension, please paste (or use a pastebin service) the offending extension's settings, if it has any.  You can obtain this by opening its configuration, clicking the 'hamburger' button in the upper-right corner of the window, and selecting "Export to a file". **Please be sure to review the contents and remove any personal data it may contain.**

```

Please paste here

```

**Comment by leigh123linux** [comment]
File your rant at https://github.com/linuxmint/linuxmint/issues
