### ISSUE TITLE
Cinnamon themes broken after last update

### ISSUE THREAD

**Issue by NickVolt77** [linuxmint/cinnamon#10524]
Cinnamon 5.0.7
Manjaro Cinnamon

**Issue**
After last update some Cinnamon themes are broken. Mint-Y-Blue (and other with Mint-Y.. ) should have dark taskbar and light menu. After update taskbar is very light gray.

**Steps to reproduce**
Update Manjaro Cinnamon with theme Mint-Y-Blue.

**Expected behaviour**
Taskbar should stay dark as shown on theme preview.

**Other information**
Update caused taskbar color change on 2 machines.
I hope this is the right place to report this.

**Comment by leigh123linux** [comment]
This isn't a cinnamon issue, themes have changed.

https://github.com/linuxmint/mint-themes/commit/8dea24cf59d89729ea34308bf3f5caddd79cafc7

@clem @JosephMcc  The preview's need updating.
