### ISSUE TITLE
Trying latest Mint Cinnamon beta 20.3 Dark theme problem

### ISSUE THREAD

**Issue by enigma131** [linuxmint/cinnamon#10525]
I use on Linux mint 20.2 Dark theme but with white title bar (better distinguish between windows)  
On current beta , this possibility is no more possible, only dark ones (mint-x or mint-y) , why ?
Secondly, you have increase the hight of mint-Y , ok but I have a small screen on laptop ... I think i will not install this version of Mint.

**Comment by leigh123linux** [comment]
mint-themes has changed, try mint-themes-legacy.

https://github.com/linuxmint/mint-themes-legacy

**Comment by enigma131** [comment]
Thanks for answer. I'm on usb stick for testing the lm 20.3 beta. Can I install it on stick ?

**Comment by clefebvre** [comment]
`apt install mint-themes-legacy`, then select legacy themes for controls and titlebars.

**Comment by enigma131** [comment]
Merci Clement, it's clearly better for small screens and darks themes. Only windows border have to be set to legacy for my need. Have we chance to have legacy themes for final iso?
