### ISSUE TITLE
Laptop shuts down (and does not start) when unplugged

### ISSUE THREAD

**Issue by PhevosFnevripos** [linuxmint/cinnamon#10558]
```
System:    Kernel: 5.4.0-91-generic x86_64 bits: 64 compiler: gcc v: 9.3.0 Desktop: Cinnamon 5.0.7 
           wm: muffin dm: LightDM Distro: Linux Mint 20.2 Uma base: Ubuntu 20.04 focal 
Machine:   Type: Laptop System: HP product: HP 250 G6 Notebook PC v: Type1ProductConfigId 
           serial: <filter> Chassis: type: 10 serial: <filter> 
           Mobo: HP model: 8328 v: 23.47 serial: <filter> UEFI [Legacy]: Insyde v: F.34 
           date: 01/25/2018 
Battery:   ID-1: BAT1 charge: 17.7 Wh condition: 18.0/31.1 Wh (58%) volts: 12.1/10.9 
           model: Hewlett-Packard PABAS0241231 serial: <filter> status: Charging 
CPU:       Topology: Dual Core model: Intel Core i3-6006U bits: 64 type: MT MCP arch: Skylake 
           rev: 3 L2 cache: 3072 KiB 
           flags: avx avx2 lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx bogomips: 15999 
           Speed: 500 MHz min/max: 400/2000 MHz Core speeds (MHz): 1: 500 2: 500 3: 500 4: 500 
Graphics:  Device-1: Intel Skylake GT2 [HD Graphics 520] vendor: Hewlett-Packard driver: i915 
           v: kernel bus ID: 00:02.0 chip ID: 8086:1916 
           Display: x11 server: X.Org 1.20.13 driver: modesetting unloaded: fbdev,vesa 
           resolution: 1366x768~60Hz 
           OpenGL: renderer: Mesa Intel HD Graphics 520 (SKL GT2) v: 4.6 Mesa 21.0.3 
           direct render: Yes 
Audio:     Device-1: Intel Sunrise Point-LP HD Audio vendor: Hewlett-Packard driver: snd_hda_intel 
           v: kernel bus ID: 00:1f.3 chip ID: 8086:9d70 
           Sound Server: ALSA v: k5.4.0-91-generic 
Network:   Device-1: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet 
           vendor: Hewlett-Packard driver: r8169 v: kernel port: 3000 bus ID: 01:00.0 
           chip ID: 10ec:8168 
           IF: eno1 state: down mac: <filter> 
           Device-2: Intel Dual Band Wireless-AC 3168NGW [Stone Peak] driver: iwlwifi v: kernel 
           port: 3000 bus ID: 02:00.0 chip ID: 8086:24fb 
           IF: wlo1 state: up mac: <filter> 
Drives:    Local Storage: total: 465.76 GiB used: 29.17 GiB (6.3%) 
           ID-1: /dev/sda vendor: Western Digital model: WD5000LPCX-60VHAT0 size: 465.76 GiB 
           speed: 6.0 Gb/s serial: <filter> 

 ```

**Issue**

Although the battery is recognized, the laptop does not work without plugging its power cable. It simply switches off immediately after you unplug it and does not start until you plug it again. As if the battery were not used at all to power the system...
The issue made its appearance immediately after I installed Linux Mint 20.2 with Cinnamon 5.0.7. When using the previously installed Linux Mint 18.2, I did not face this problem.

**Steps to reproduce**
Try to start the laptop without connecting it to the grid. It will not start.
Then plug it and press the power button. You can then unplug it again to see it switch off.

```

**Comment by Tsoccerguy3** [comment]
On the taskbar , hover over , click on the battery icon , what is the status and percentage , lion batteries last 3 to 5 years regardless wether you use them and will not work if 1 cell goes bad . you have to accept that it can be a hardware failure . test batteries Ohms and voltage output .

**Comment by Tsoccerguy3** [comment]
If you believe that its the Kernel ,roll back

**Comment by PhevosFnevripos** [comment]
Thanks for the reply @Tsoccerguy3 ! The fact that batteries have a finite life, does not explain why the problem appeared only after I moved from Linux Mint 18.2 to Linux Mint 20.2 . Here are some screenshots that provide more information:

![Screenshot from 2022-01-05 19-45-51](https://user-images.githubusercontent.com/566415/148264617-00286ab1-44d0-4702-ab91-002cad6a448a.png)
![Screenshot from 2022-01-05 19-46-15](https://user-images.githubusercontent.com/566415/148264667-5384a8b9-86ea-42c4-897b-2307dab72bc5.png)
![Screenshot from 2022-01-05 19-46-42](https://user-images.githubusercontent.com/566415/148264678-25f255e5-c0f7-4492-9600-9561241acf7c.png)
![Screenshot from 2022-01-05 19-47-16](https://user-images.githubusercontent.com/566415/148264688-312554da-93cc-4c99-9573-3b8317c6cf54.png)

**Comment by Tsoccerguy3** [comment]
You can test if its the OS or hardware . 
See if pressing F2 or other key , on boot gets you into the Bios .
You can go to the HP website to find the Boot to Bios procedure . Bios is independent of the OS . 
If on Battery you can not boot to Bios then its hardware . If successful , 
prepare a boot CD or a boot USB .with any Linux distribution or a windows boot to check if its a bad update .

**Comment by PhevosFnevripos** [comment]
I did boot to BIOS with the laptop plugged to the grid. It boots normally and without any problem.
If what you mean with "...If on Battery you can not boot to Bios then its hardware..." is that I should try to boot after unplugging the laptop, then this is simply impossible. That is actually the bug, which I described initially; nothing happens unless you use the AC adapter. 

I did not understand the last part of your comment. How do I check if it is "a bad update", by using a bootable medium?

**Comment by Tsoccerguy3** [comment]
Simply , if you can not boot to the Bios on battery only , then it's a hardware issue . 
It may be a coincidence of a failure and the OS update .

Regardless , Linux Mint does nothing until The Bios is done posting . If you feel that Linux Mint 20 Toggled a soft switch on your HP laptop , then Try making a boot CD with Linux Mint 18 or Win 10 , instructions are on the net . Use Rufus to make a boot CD or USB , https://rufus.ie/downloads/
Booting off the CD may toggle a switch on.

Batteries are cheap and can be ordered online

On my laptop the battery icon on the task bar will be black when the battery is full and white when empty .

**Comment by PhevosFnevripos** [comment]
I did boot using a bootable DVD with Linux Mint 18.3 installed on it. Unsurprisingly, the problem did not disappear. 

I have not yet tried substituting the battery. As I wrote, it is being recognized by the OS (even if it never reaches a battery level of 100%). Again, since the bug made its appearance only after the installation of Linux Mint 20.2, it should not be a pure hardware issue, hence buying a new battery is unlikely to resolve it.

**Comment by Tsoccerguy3** [comment]
Go to the HP site for help on the hardware . There are key presses to reset Bios . One is hold power button while you plug it in , read up on the hardware on their site . If there is a soft switch controlled by a driver it could be toggled off , but highly unlikely . If 1 cell in the lion battery goes bad , it will no longer charge for safety reasons. If the charging circuit is broken , then its board may need to be changed .  Testing  the battery output with a voltmeter  would be the way to go to see if it has a charge in it .  What you have is a coincidence . Until you test the battery you won't know

**Comment by PhevosFnevripos** [comment]
@Tsoccerguy3 thanks for the support, but I do not want to perform a hard reset of any kind, neither do I have a voltmeter. 
Consulting the HP support pages, I found [reference](https://support.hp.com/us-en/product/hp-250-g6-notebook-pc/15747807/model/15747879/document/ish_4449597-3519507-16) to a utility called "HP Battery Health Manager" in the BIOS.

Needless to say, this does not exist in my BIOS. I am attaching a screenshot of what I see here. 
![IMG_20220110_124506](https://user-images.githubusercontent.com/566415/148756892-5c1ffc36-b7f5-49ba-8bd4-9a3fa4844b57.jpg)

**Comment by Tsoccerguy3** [comment]
Here are some links to checkout if you believe that a soft switch is toggled off . You may need a boot-able win 10 USB to use HP tools to fix or Diagnose this .  

https://support.hp.com/lt-en/help/diagnostics?category=computing&issue=battery-adapter-issues
https://support.hp.com/us-en/document/ish_2268927-1713329-16

https://h30434.www3.hp.com/t5/Notebook-Hardware-and-Upgrade-Questions/Battery-recognition-Linux/td-p/7040710

https://h30434.www3.hp.com/t5/Notebook-Hardware-and-Upgrade-Questions/battery-test-OK-but-can-t-power-PC-with-battery/td-p/7059353

https://h30434.www3.hp.com/t5/Notebook-Hardware-and-Upgrade-Questions/Battery-not-charging-yet-plugged-in/td-p/6451735

**Comment by kadarmarton** [comment]
Please note the following pieces of the information you posted:
  Energy (design) 31.2 Wh   <- this was when the battery was new
  Energy when full 18.1 Wh  <- this is now - the battery capacity is severely degraded
  Primary battery SN  ..... 12/22/2017  <- the battery is over 4 years old
What all this means is even if there may be some miniature chance for you to make it work a few more months, it will have to be replaced soon anyway. You do not risk needlessly buying a new battery.
Buy one. It will fix your issue for any operating system you have or will have installed in the coming couple of years.

**Comment by PhevosFnevripos** [comment]
I will follow your advice; there is not much to lose anyway. Given how abrupt the loss of the battery was (after a format and installation of a new OS) I am wondering whether it is preferable to try and test the new battery before buying it.

**Comment by PhevosFnevripos** [comment]
> Please note the following pieces of the information you posted: Energy (design) 31.2 Wh <- this was when the battery was new Energy when full 18.1 Wh <- this is now - the battery capacity is severely degraded Primary battery SN ..... 12/22/2017 <- the battery is over 4 years old What all this means is even if there may be some miniature chance for you to make it work a few more months, it will have to be replaced soon anyway. You do not risk needlessly buying a new battery. Buy one. It will fix your issue for any operating system you have or will have installed in the coming couple of years.

@kadarmarton I bought a new one and the problem seems to have been fixed.
