### ISSUE TITLE
[feature request, partially cosmetic] potential improvements for window management by the user ?

### ISSUE THREAD

**Issue by TPO100Cofficial** [linuxmint/cinnamon#10553]
it always occurred to me as oddly limiting how cinnamon's settings page is, relative to the quite tinkering-positive setup of the rest of the environment
there are certain functions present in cinnamon for the window management that don't have dedicated buttons, namely:
turning on shade mode, toggling always on top, toggling being present on all workspaces and lowering/raising it

it would obviously be quite cluttered to show all of these functions at the same time, and so a good solution is to, in the "Windows" settings page, change the title bar tab:
instead of immutable predefined layouts, aside from selecting a new one, keep the presets but also let button order/amount be modified
allowing the user to add/remove buttons not only for standard controls, like minimize, restore and exit, but also toggle shade, always on top and other functions that can be assigned to the mouse buttons

this might also have a mildly positive effect on accessibility/convenience, right click > select a dropdown option is mildly annoying

a few more tangentually related notes,
the shade toggle should have options for an animation to be played in effects, perhaps?
toggling always on top/present on all workspaces should maybe have some form of visual indication, like a subtle glow around the edges of the window for a moment

**Comment by smurphos** [comment]
It used to as you describe in Cinnamon 4.2.x and earlier. Custom button layouts are still available under the hood, they just need to set in the dconf database directly. One of the reasons for the change is that although the metacity format supports 9 button types, very few themes support all 9. The other reason I suspect is for a long time the intention has been to dump Metacity and move to GTK rendered window borders.

**Comment by JosephMcc** [comment]
@smurphos explained this well. Besides those reasons, windows that use header bars, or client side decorations, also do not support those button types at all. So the whole thing is very inconsistent. For those reasons I don't think you'll see this coming back.

**Comment by Secret-chest** [comment]
> It used to as you describe in Cinnamon 4.2.x and earlier. Custom button layouts are still available under the hood, they just need to set in the dconf database directly. One of the reasons for the change is that although the metacity format supports 9 button types, very few themes support all 9. The other reason I suspect is for a long time the intention has been to dump Metacity and move to GTK rendered window borders.

@smurphos So we'll have ALL windows use huge GTK header bars?

**Comment by smurphos** [comment]
Not necessarily - they don't have to follow the Gnome App styling. I'm not privy to the design / implementation discussions.

**Comment by Secret-chest** [comment]
> Not necessarily - they don't have to follow the Gnome App styling. I'm not privy to the design / implementation discussions.

Ah ok. Empty GTK titlebars occupy too much screen estate.
