### ISSUE TITLE
Nothing happens when clicking the New object button to add a new menu object

### ISSUE THREAD

**Issue by Umeaboy** [linuxmint/cinnamon#10556]
```
 * Cinnamon version (cinnamon --version)
Cinnamon 4.8.3
Cinnamon 5.2.5 is at the time of writing this in the development release of Mageia

 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
Mageia 8

 * Graphics hardware *and* driver used
ATI Radeon HD 6400 and later (radeon): Advanced Micro Devices, Inc. [AMD/ATI]|Caicos XT [Radeon HD 7470/8470 / R5 235/310 OEM] [DISPLAY_VGA]

I have x11-driver-video-nouveau and x11-driver-video-ati installed. 

 * 32 or 64 bit
64 bit

 * Attach ~/.xsession-errors, or /var/log/syslog
I can't find either of these files with the locate command. Mageia uses journalctl to handle logs and I've not touched it more than once so a specific journalctl command would be welcomed.

**Issue**
If I open cinnamon-menu-editor and I want to add an object to the program menu nothing happens when I click the New object button.

**Steps to reproduce**
1. Press Alt + F2.
2. Type cinnamon-menu-editor and hit Enter.
3. Click on Internet to the left and then click the New object button to the right. 
4. Nothing happens.

**Expected behaviour**
When you click the New object button you should get a popup window to add a new object.

**Comment by Umeaboy** [comment]
Here's the error when clicking the New object button:

Traceback (most recent call last):
  File "/usr/share/cinnamon/cinnamon-desktop-editor/cinnamon-desktop-editor.py", line 424, in <module>
    Main()
  File "/usr/share/cinnamon/cinnamon-desktop-editor/cinnamon-desktop-editor.py", line 351, in __init__
    editor = LauncherEditor(self.orig_file, self.launcher_cb)
  File "/usr/share/cinnamon/cinnamon-desktop-editor/cinnamon-desktop-editor.py", line 61, in __init__
    self.builder.add_from_file(self.ui_file)
gi.repository.GLib.Error: gtk-builder-error-quark: /usr/share/cinnamon/cinnamon-desktop-editor/launcher-editor.ui:70:1 Invalid object type 'XAppIconChooserButton' (6)

**Comment by inucat** [comment]
Hello @Umeaboy ,

I was going through the same issue on Mageia (9), but finally found what is wrong.

`cinnamon-menu-editor` requires `python3-xapps-overrides.noarch`, which is an unstated dependency.

This command line will solve the issue.

`sudo dnf in python3-xapps-overrides.noarch`

So, I suggest this issue be submitted to Mageia package maintainers.

Best,
