### ISSUE TITLE
Feature request: add search option to Startup Application's application list menu

### ISSUE THREAD

**Issue by WhosyVox** [linuxmint/cinnamon#10559]
Pretty plain and simple: Settings -> Startup Applications -> [+] -> Choose application
Add a search bar to the interface, filtering the application list based on search term.

It would just make this one area of the UI a smoother experience.

**Comment by JosephMcc** [comment]
There already is one. Simply start typing the name of what you are looking for ;)

**Comment by WhosyVox** [comment]
> There already is one. Simply start typing the name of what you are looking for ;)

In which case the request changes:
Show search bar prior to text entry or a button to open the search, in order to be consistent with other UI elements in Cinnamon (e.g. Menu, Settings, Nemo)
