### ISSUE TITLE
[Feature restoration request] Restore ms decay customization to Linux Mint 20.3 Cinnamon Beta's Effects

### ISSUE THREAD

**Issue by JohnAutodidact** [linuxmint/cinnamon#10565]
Subject OS: Linux Mint 20.3 Cinnamon Beta cum Linux Mint 20.3 Cinnamon.

Hardware tested: An Asus STRIX-GTX960-DC2OC-4GD5 with nVidia 495.44

Subject: Restoring the ms decay Customize portion of Linux Mint 20.2 Cinnamon's Effects to Linux Mint 20.3 Cinnamon's Effects.

An argument in favour of the above:

The ability to observe window and menu opening and closing transitions is not only subjectively pleasing to the eye, it also allows novice Linux Mint Cinnamon users to observe said transitions resulting from actions they take, as opposed to the somewhat jarring experience of having windows and menus appear and disappear in less than a blink of the eye.

More recent and performant graphics cards actually _need_ to have window and menu openings and closings slowed down a bit to mitigate the aforementioned jarring experience.

However, older yet still otherwise capable graphics cards, like the Asus STRIX-GTX960-DC2OC-4GD5 are inherently too slow for the default ms decay times currently employed in Linux Mint 20.3 Cinnamon Beta's Effects. Thus, the only mitigation available to them is turning the effects off thereby ceding the subjectively pleasing and quantifiably useful window and menu animations.

It is for the above reasons that, IMHO, a restoration of Linux Mint 20.2 Cinnamon's ms decay Effects Customize feature to Linux Mint 20.3 Cinnamon's Effects would be of benefit in allowing one to tailor the decay times of the various aspects of the Effects transitions to a much wider range of graphics cards in the service of enjoying a usefully pleasing, animated desktop.

As for the variety of effects types found in Linux Mint 20.2 Cinnamon's Effects? IMHO many of those are superfluous and likely add to the code burden in a needless manner. Thus, as a suggestion, they needn't be restored to Linux Mint 20.3 Cinnamon's Effects.

Thank you for your attention and consideration.

John

Pictured: The ms decay settings I use with Linux Mint 20.2 Cinnamon's Effects on an Asus STRIX-GTX960-DC2OC-4GD5 in order to achieve a performant, animated desktop.

![Linux Mint 20 2 Effects, Customize](https://user-images.githubusercontent.com/96786783/147587811-2ae69fa3-d816-4135-aabf-dfac188b7ef3.png)

**Comment by kevinfiol** [comment]
+1. I recently installed 20.2, and then was delighted to see a 20.3 release around the corner. I was perplexed when I could no longer find this menu after upgrading. I do prefer having window animations, but I like them to be quicker than the default speeds.

**Comment by JohnAutodidact** [comment]
Fortunately, kevinfiol, Linux Mint 20.2 Cinnamon, upgraded with Linux 5.13.0-25-generic #26~20.04.1-Ubuntu SMP Fri Jan 7 16:27:40 UTC 2022, runs superbly on the above GPU which is part of the hardware itemized below.

If you created a timeshift snapshot before upgrading from Linux Mint 20.2 to LM 20.3, then you can restore your OS to version 20.2. I've done this myself without issue.

Caveat: When using timeshift to restore to a preceding snapshot, please allow timeshift enough time to fully cue up the restore. This can be gauged by observing the amount of CPU activity via System Monitor. Once timeshift's cuing process has completed, the level of CPU activity will drop to near nil. At this point, one may proceed with the restore.

LM 20.2 Cinnamon | Sabertooth 990FX R2.0 | FX-8370 | KVR16E11K4/32 | STRIX-GTX960-DC2OC-4GD5 | GL2450HM, 29WK500-P | 220-G2-0850-XR | DRW-24B1ST J | 2x CT1000MX500SSD1, 1x SUV500480G, 2x ST6000DM001, 1x ST6000NE0023 | uPD720201 | TX3000E (AX200, BT 5.1)

**Comment by JosephMcc** [comment]
See: https://github.com/linuxmint/cinnamon/issues/10841
