### ISSUE TITLE
Default themes have now a 1px border

### ISSUE THREAD

**Issue by artik** [linuxmint/cinnamon#10577]
```
 * Cinnamon 5.2.7
 * Distribution - (Mint 20.3)
 * Nvidia Geforce 3090 proprietary drivers 460
 * 64 bit
 ```

**Issue**

Since Mint cinnamon 20.3 has been released, new default skin (light and dark) have now a 1px border, that looks kind of a regression

![screenshot13](https://user-images.githubusercontent.com/1015856/148485710-688a47bd-984f-417d-a4d8-e13680b5823e.png)
![screenshot14](https://user-images.githubusercontent.com/1015856/148486102-5af4459e-9f65-4d92-96ee-403941060db5.png)

When it was before clean and sharp:

![screenshot12](https://user-images.githubusercontent.com/1015856/148485856-8584586a-aaf5-4cd8-8ea2-fbe16b78383f.png)

**Comment by LinuxOnTheDesktop** [comment]
Is the following the same problem? Firefox is offset from the top of the screen and clicking Firefox's maximise button does nothing. (Also, Firefox seems to have uninstalled my default spell-checker language. I had to re-add it.)

![image](https://user-images.githubusercontent.com/47056543/148488761-748f787d-9f9c-4fcd-a0d6-43904e5f36c7.png)

The screenshot does not do the problem justice: there is a gap of some four pixels between the top of Firefox and the top of the screen.

**Comment by LinuxOnTheDesktop** [comment]
I find that installing the legacy themes and activating them ([once one has worked out how to do those things](https://github.com/linuxmint/mint-themes-legacy/issues/2)) works around the problem.

**Comment by artik** [comment]
> I find that installing the legacy themes and activating them ([once one has worked out how to do those things](https://github.com/linuxmint/mint-themes-legacy/issues/2)) works around the problem.

Oh great! Can you give us step by step install process?

**Comment by bradonomics** [comment]
I had the same problem and, yes, adding the "mint-themes-legacy" package in the Software Manager and switching the windows borders in the Themes settings worked.

**Comment by LinuxOnTheDesktop** [comment]
artik

Certainly (though I see that someone else has provided instructions already; still, I'd started so I'll finish).

- `sudo apt install -y mint-themes-legacy`
- Close any open Settings window.
- Open Settings and find the Themes option.
- Set the 'Window border' theme to something with 'legacy' in its title.

**Comment by artik** [comment]
Thanks for these workaround. I do think that the main new theme should have this border removed, kind of a regression visually

**Comment by JosephMcc** [comment]
I'd like to point out that this isn't a Cinnamon issue. Cinnamon has no default Gtk theme. You are talking about the default theme that is shipped with Linux Mint. While that distinction isn't always clear they are two separate things. If you have an issue with Mint's default theme it should probably be opened on the mint-themes repo.

**Comment by artik** [comment]
> I'd like to point out that this isn't a Cinnamon issue. Cinnamon has no default Gtk theme. You are talking about the default theme that is shipped with Linux Mint. While that distinction isn't always clear they are two separate things. If you have an issue with Mint's default theme it should probably be opened on the mint-themes repo.

Great, I'll do it right away. thanks for clarification

**Comment by Lurux** [comment]
@LinuxOnTheDesktop @artik

For the firefox problem, see linuxmint/mint-themes/issues#339

(pinging because I'm pretty sure people don't receive notifications from close issues)
