### ISSUE TITLE
menu@cinnamon.org with Change categories on hover =OFF

### ISSUE THREAD

**Issue by vegam57** [linuxmint/cinnamon#10573]
MintMenu of Cinnamon 5.2 (LM20.3beta)
This issue is on an intel real machine.
No VM.

[code]
System: Kernel: 5.4.0-91-generic x86_64 bits: 64 compiler: gcc v: 9.3.0 Desktop: Cinnamon 5.2.6
wm: muffin dm: LightDM Distro: Linux Mint 20.3 Una base: Ubuntu 20.04 focal
Machine: Type: Laptop System: Dell product: Latitude E6410 v: 0001 serial: Chassis:
type: 9 serial:
Mobo: Dell model: 04373Y v: A01 serial: BIOS: Dell v: A17 date: 05/12/2017
Battery: ID-1: BAT0 charge: 46.0 Wh condition: 46.0/48.8 Wh (94%) volts: 12.5/11.1
model: Samsung SDI DELL PT43699 serial: status: Full
Device-1: hidpp_battery_0 model: Logitech Wireless Mouse serial:
charge: 55% (should be ignored) status: Discharging
CPU: Topology: Dual Core model: Intel Core i5 M 520 bits: 64 type: MT MCP arch: Nehalem
rev: 5 L2 cache: 3072 KiB
flags: lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx bogomips: 19151
Speed: 1463 MHz min/max: 1199/2400 MHz Core speeds (MHz): 1: 1455 2: 1463 3: 1430
4: 1463
Graphics: Device-1: Intel Core Processor Integrated Graphics vendor: Dell Latitude E6410
driver: i915 v: kernel bus ID: 00:02.0 chip ID: 8086:0046
Display: x11 server: X.Org 1.20.13 driver: modesetting unloaded: fbdev,vesa
resolution: 1280x800~60Hz
OpenGL: renderer: Mesa DRI Intel HD Graphics (ILK) v: 2.1 Mesa 21.0.3
direct render: Yes

**Issue**
the focus will not be correct.
**Steps to reproduce**
Change categories on hover =OFF
and
If you use ↓ on the keyboard,

![cinnamon-20220105-1](https://user-images.githubusercontent.com/78515193/148160118-db280f70-0ea9-4222-9033-3201e2a446d8.gif)

**Comment by haggen88** [comment]
@mtwebster @clefebvre 
I confirm that the bug is present in Mint 20.2 and it seems to be related with #10212

https://user-images.githubusercontent.com/68134588/148160592-ff8f9427-4a72-4c55-aca8-8ef4482b2f0f.mp4

**Comment by mtwebster** [comment]
They're not related, this bug just makes it easier to observe the other bug manifesting.
