### ISSUE TITLE
Snap area appears at the top but does nothing

### ISSUE THREAD

**Issue by madprops** [linuxmint/cinnamon#10589]
Cinnamon 5.0.7
Nouveau Nvidia drivers
Fresh Linux Mint install in Virtualbox

The following happens if I drag a window to the top to snap it, but then move it a bit down. I don't know if it's a bug, so I'm reporting just in case. Releasing the mouse when that appears does nothing it seems.

![mintbug](https://user-images.githubusercontent.com/206498/148642099-704f354c-faee-4fde-aa56-a9ad03d7b3f4.jpg)

**Comment by mtwebster** [comment]
Are you able to shrink the window to half the screen height by simply resizing? If not, it won't be allowed to tile either. It looks like the file manager window you're dragging, which shouldn't have a problem with this, but I want to be sure.

**Comment by madprops** [comment]
Yes it was the file manager, which it can be resized, same with Firefox. I can tile it at the top normally, but this small area that appears at the top if I move the window a bit downwards before releasing the mouse button, doesn't seem to provide any function.

**Comment by mtwebster** [comment]
Oh.. it does nothing. It's just a hint for when you approach the edge of the screen that there is tile capability - if you keep going you get the actual tile preview. If you hold there for a second or two you also get an on-screen message with some help.

We've been considering doing away with it. Most desktops only have left/right tile so at the time when we implemented additional modes (corner, top, bottom) it was something to make these capabilities more discoverable by the user.

**Comment by madprops** [comment]
You could make them visible when a window drag operation is ongoing, that would be a clearer hint since having the cursor on that exact small area is unlikely
