### ISSUE TITLE
Rounded window corners interfere with Firefox

### ISSUE THREAD

**Issue by KrischnaGabriel** [linuxmint/cinnamon#10586]
```
**Distribution:** Linux Mint 20.3 Cinnamon

**Firefox version:**
version independent issue.
Tested both on 95.0.1 and 94.0.1 stable releases.
 ```
**Issue**
Cinnamon 20.3 added those rounded corners to windows.
This border also appears in Firefox. Firefox overlays it's GUI over it which leads in a slim, out of place border as visible on the picture.

![cinnamon border ff](https://user-images.githubusercontent.com/39499729/148637867-1c0e8311-a401-4021-8b2d-8eab4c1dd654.png)

On the default white or black themes it's barely noticeable, but existing.
Note: It is NOT a visual glitch caused by the firefox themes.
The Alpenglow Theme has a strong contrast so it is better visible that the border is there.

![gnome](https://user-images.githubusercontent.com/39499729/148637877-d9fade78-33b1-4964-80a3-c898d60986fc.png)

**Steps to reproduce**
1. Update to / Install Linux Mint 20.3 Cinnamon.
2. Open Firefox (a clean new profile)
3. maximize the window.
4. ☰ -> More Tools -> Customize toolbar... -> uncheck "Title Bar"
5. To see the effect better, install the Alpenglow Theme. (optional)

**Expected behaviour**
No border as it was with Cinnamon 20.2:
![efore](https://user-images.githubusercontent.com/39499729/148638087-a5137537-3690-4927-baa5-5b4da533f4df.png)

**Personal Note**
Not only are the rounded corners causing issues with certain applications, but also I generally dislike the look (makes the ui look plump), but couldn't find a option in "Themes" to turn them off.
If there isn't/won't be a simple option to turn it off, this is a solid reason to go back to Cinnamon 20.2.

**Additional system information (if required)**
https://termbin.com/qttn

**Comment by mtwebster** [comment]
firefox issue:
https://github.com/linuxmint/mint-themes/issues/339#issuecomment-1007493529

rounded corners:
```
apt install mint-themes-legacy
```
