### ISSUE TITLE
Scroll, then press ctrl = zoom

### ISSUE THREAD

**Issue by BraveSentry** [linuxmint/cinnamon#10587]
```
 * Cinnamon version 5.0.7
 * Mint 20.2
 ```

Whenever I scroll up in any window and then press ctrl, I zoom in. The contrary happens when I scroll down and then hit ctrl: I zoom out. 

This can be annoying when I want to scroll up and then open a new window with ctrl+n, or in fact do anything involving ctrl after scrolling.

I'm sorry if this is not cinnamon's fault. It it is not, please tell me where to go with this problem.

**Comment by madprops** [comment]
Can't confirm this on a Mint with the same Cinnamon I'm running in Virtualbox. 

But I tried with left Ctrl since right Ctrl is a vb special key.

**Comment by BraveSentry** [comment]
I used left ctrl too. To give some examples of where I found this: Firefox (across several versions), Nemo, Thunderbird (when viewing a mail). It does not happen on chrome - but chrome does not zoom with ctrl+scrolling anyway.
I tried some things now (sorry, should have thought about it earlier) and found out that it happens only with 2-finger-scrolling on my trackpad, not with a mouse wheel, arrow keys or page up/down.

**Comment by madprops** [comment]
Ah yeah, I tried in Firefox with a mouse, don't have a  trackpad.

**Comment by mtwebster** [comment]
Do you have Desktop Zoom enabled in accessibility settings?

Perhaps you set its modifier to ctrl (it's usually alt to avoid interfering with zoomable apps that use ctrl).
![image](https://user-images.githubusercontent.com/262776/148646101-671c40c1-1931-4b9c-9d4b-649860f4066c.png)

**Comment by BraveSentry** [comment]
> Do you have Desktop Zoom enabled in accessibility settings?

Nope. I switched it on out of curiosity, the modifier was alt. Now I switched it back off.

**Comment by SparkyBluefang** [comment]
If this is trackpad specific, you are probably using the synaptics xinput driver, which has scroll "Coasting" enabled by default.

If you want to disable this, set `CoastingSpeed` to `0` using `synclient` or in your xorg configuration file for the `synaptics` configuration.
https://wiki.archlinux.org/title/Touchpad_Synaptics
(file paths, package manager, etc, will depend on which distro you're using)

**Comment by BraveSentry** [comment]
Thanks a lot. This was it. It's a trade off though: Do I live with this minor bug to have dynamic scrolling, or do I want the bug gone but have to scroll without coasting. Anyway, thanks nonetheless!
