### ISSUE TITLE
Notification theme

### ISSUE THREAD

**Issue by pavolgaj** [linuxmint/cinnamon#10594]
```
Linux Mint 20.3 Cinnamon (official version)
 ```

**Issue**
After the upgrade from LM 20.2 to 20.3, the background of notifications was changed. Now, it's light grey - see image: 
![notif](https://user-images.githubusercontent.com/17177193/148740378-b32eb283-73cf-4dc2-9ace-c8729d430fce.png)
I use the "Linux Mint" theme and before upgrading, notifications were dark. Changing theme (e.g. to Mint-Y-Dark) doesn't help - notifications are always light.

**Expected behaviour**
The appearance of notifications should be according to the selected theme. In used theme, the background is:
```
background-gradient-direction: vertical;
background-gradient-start: rgba(66, 66, 66, 0.9);
background-gradient-end: rgba(55, 55, 55, 0.9);
```

**Comment by mtwebster** [comment]
Strange, that's a Mint-Y-styled notification - it's not just the color, but also the shape, icon size, and the fact the text is ellipsized.

Can you run:
```
gdbus call --session --dest org.freedesktop.DBus --object-path / --method org.freedesktop.DBus.GetConnectionUnixProcessID org.freedesktop.Notifications
```
It should print a process ID - take that and run:
```
ps -A | grep <id>
```
It should show the line containing `cinnamon`

**Comment by pavolgaj** [comment]
It shows `1958 ?        00:00:00 xfce4-notifyd`

**Comment by mtwebster** [comment]
It looks as though xfce is installed - did you ever install that desktop to try it out maybe?

To make sure you don't break anything removing this, simulate its removal:
```
apt remove --simulate xfce4-notifyd
```
And paste the output from that here if you have any concern about what's getting removed.  If it's only xfce-related stuff, and you're confident about it, you can go ahead and remove the --simulate flag and run it again, for real this time. Then log out and back in.

**Comment by pavolgaj** [comment]
Only xfce4-notifyd was removed. Now, it works as expected (with standard cinnamon notification).

I found that there are a few other xfce apps on my system. Here is a list of them (output of ```xfce + Tab``` in Terminal):
```
xfce4-about                   xfce4-panel-start
xfce4-accessibility-settings  xfce4-popup-applicationsmenu
xfce4-appearance-settings     xfce4-popup-clipman
xfce4-appfinder               xfce4-popup-clipman-actions
xfce4-clipman                 xfce4-popup-directorymenu
xfce4-clipman-settings        xfce4-popup-windowmenu
xfce4-color-settings          xfce4-session
xfce4-display-settings        xfce4-session-logout
xfce4-find-cursor             xfce4-session-settings
xfce4-keyboard-settings       xfce4-settings-editor
xfce4-mime-helper             xfce4-settings-manager
xfce4-mime-settings           xfce4-set-wallpaper
xfce4-mouse-settings          xfce4-terminal
xfce4-panel                   xfce4-terminal.wrapper
```

And also in apt, there are some packages available to remove:
```
xfce4                    xfce4-helpers            xfce4-settings
xfce4-appfinder          xfce4-panel              xfce4-terminal
xfce4-clipman            xfce4-pulseaudio-plugin  
xfce4-clipman-plugin     xfce4-session 
```
Simulate flag doesn't show any other package to remove.

I don't remember if I sometimes installed something related to xfce (some software). But, I certainly never installed xfce desktop on this computer. Always if I want to install different desktop, I reinstall whole system.

**Comment by mtwebster** [comment]
Weird that's definitely all or most of the xfce desktop.

You may be able to run:
```
apt remove xfce4*
```
Again, try simulate first (or make sure you don't hit Y right away) - you may discover the reason they're installed in the first place (if it tries to remove something non-xfce-prefixed).
