### ISSUE TITLE
Regression: calendar; 'Error calling StartServiceByName'

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/cinnamon#10597]
```
 * Cinnamon version (cinnamon --version): 5.2.7
   - Please specify if you are using the daily builds PPA: I am not.
     (https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds).
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...): Mint 20.3
 * Graphics hardware *and* driver used: Intel; Mesa
 * 32 or 64 bit: 64
 * Attach ~/.xsession-errors, or /var/log/syslog
 
[syslog.txt](https://github.com/linuxmint/cinnamon/files/7851998/syslog.txt)
 ```

**Issue**

Since moving from Mint 20.2 to 20.3, I see this in the syslog after boot:

`
org.cinnamon.CalendarServer[8099]: g-io-error-quark: Error calling StartServiceByName for org.gnome.evolution.dataserver.Sources5: Unit evolution-source-registry.service not found`

**Steps to reproduce**

Install Mint 20.3. Boot.

**Expected behaviour**

No error shown in the log.

**Other information**

Probably there is no harm aside from the log spam (and having to determine that the 'error' is harmless).

**Comment by mtwebster** [comment]
Does gnome-calendar fail to run also?

Can you try reinstalling evolution data server:
```
apt install --reinstall evolution-data-server
```
Then log out and back in.

If you don't actually need calendar event support then the message is harmless, though I'd still like to get to the bottom of it.


btw, links here don't work if they're inside of a code block (like the syslog.txt link in your original post).

**Comment by LinuxOnTheDesktop** [comment]
Thanks, mtwebster.

The affected computer - I find that only one of my two Mint PCs is affected - did not have gnome-calendar installed. Nor did it have evolution-data-server installed. (Should those packages have been installed? How does Cinnamons calendar applet relate to them?) After I installed those two packages on the affected PC, gnome-calendar opened without any problems (though I did not check the syslog). Also, after logging out and back in again, the original error message had not reappeared in the log. So: _having those two packages seems to stop the error message from appearing._

The file I posted was accessible, albeit misformatted. The file is [here](https://github.com/linuxmint/cinnamon/files/7851998/syslog.txt).

**Comment by mtwebster** [comment]
You don't need gnome-calendar installed (although cinnamon slightly integrates it if it is, launching it if you click on a particular event or the 'no events' button/label). All that's needed for calendar support is evolution-data-server.

Was the affected system a new install, or upgrade from 20.2->20.3? What about the unaffected one?

**Comment by LinuxOnTheDesktop** [comment]
Thanks. Each system had been upgraded from 20.2 (and from earlier versions before that).

**Comment by LinuxOnTheDesktop** [comment]
I think this problem is fixed and that the fix has been released.
