### ISSUE TITLE
Screenshot not possible while menu is open

### ISSUE THREAD

**Issue by tmanev** [linuxmint/cinnamon#10604]
```
Kernel: 5.4.0-94-generic x86_64 bits: 64 compiler: gcc v: 9.3.0 Desktop: Cinnamon 5.2.7 
wm: muffin dm: LightDM Distro: Linux Mint 20.3 Una base: Ubuntu 20.04 focal 
 ```
System information: [termbin](https://termbin.com/9mpm)

**Issue**
Cannot make printscr while some menu is open.
Normally I'm pressing printscr key, while for example, Nemo menu is being open.

**Steps to reproduce**
1. Open Nemo
2. Cklik on the menu, for example on File
3. Press printscr keyboard button

**Expected behaviour**
Screenshot to be taken.

**Other information**
Looks like none of the shortcuts work in this case.
For example, pressing the super button while the menu is open.

**Comment by fredcw** [comment]
Most screenshot apps allow you to set a delay giving you time to open the menu. Also hide/show pointer.

**Comment by mtwebster** [comment]
This is a limitation with how programs 'grab' the keyboard, and is beyond our control - there's nothing that can be done about it.
