### ISSUE TITLE
Volume percentage incorrectly displayed for small volume notification size

### ISSUE THREAD

**Issue by eliezerjrs** [linuxmint/cinnamon#10609]
```
 * Cinnamon version (cinnamon --version) 5.2.7
   - Please specify if you are using the daily builds PPA
     (https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds).
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) 20.3
 * Graphics hardware *and* driver used
 * 32 or 64 bit: 64 bit
 * Attach ~/.xsession-errors, or /var/log/syslog
 ```

**Issue**

Whenever I choose the small size notification to my media control volume keys, the percentage number and signs are displayed outside of the notification:
![image](https://user-images.githubusercontent.com/66121192/149705722-1d9dd2ba-0551-4028-a783-9379ae6aa907.png)

It's a small thing bug important to those who use this small size volume notification:
![image](https://user-images.githubusercontent.com/66121192/149705780-8b09f8f8-da48-4d39-bdbd-57475de5647c.png)
On screen media keys notifications
Notification size: Small

**Steps to reproduce**

1-Change desktop theme to anything except Linux Mint theme (works just fine on the three sizes for this theme) (Settings > Themes > Desktop);
2-Set the size of midia control keys to small (Settings > Notifications);
3-Hit volume up or volume down keys on your media keyboard.

**Expected behaviour**

The number and percentage are suposed to be display inside in the square notification.

**Other information**

**Configuration info, if applicable**
If this bug report is related to an Applet, Desklet or Extension, please paste (or use a pastebin service) the offending extension's settings, if it has any.  You can obtain this by opening its configuration, clicking the 'hamburger' button in the upper-right corner of the window, and selecting "Export to a file". **Please be sure to review the contents and remove any personal data it may contain.**

```

Please paste here

```

**Comment by smurphos** [comment]
Can  you share your settings in in the Font Selection application? I think this is a case of the notification not scaling properly on various themes to accommodate larger font settings.

**Comment by mtwebster** [comment]
Also, are you using hidpi?

**Comment by eliezerjrs** [comment]
> Can you share your settings in in the Font Selection application? I think this is a case of the OSD not scaling properly on various themes to accommodate larger font settings.

I use the default font size:
![image](https://user-images.githubusercontent.com/66121192/149859985-7e99f5a6-d5d1-4b3b-a435-4cdd8ffba329.png)

My computer moniter is samsung syncmaster 933sn and my screen resolution is set to default (1360x768):
![image](https://user-images.githubusercontent.com/66121192/149860256-9aa314ed-a59d-4173-ab45-08a64ab423a5.png)

**Comment by eliezerjrs** [comment]
> Also, are you using hidpi?

I wish :D my monitor is quite simple, Samsung syncmaster 933 sn
![image](https://user-images.githubusercontent.com/66121192/149860437-03ae8fce-4584-45a8-8f75-733c43939de5.png)

**Comment by mtwebster** [comment]
Ah I can reproduce this if I switch to that resolution. Thanks
