### ISSUE TITLE
Linux Mint 20.3 Cinnamon compatibility issues with Bravo 15 laptop (only works 100% with kernel 5.8)

### ISSUE THREAD

**Issue by nathangeffen** [linuxmint/cinnamon#10602]
```
  * Cinnamon 5.2.7
  * Linux Mint 20.3 
 * MSI Bravo 15 laptop 64-bit

**Issue**
Under kernel 5.4 the MSI Bravo 15 GPU appears not to work properly. One can only boot to GUI in compatibility mode.
But under kernel 5.13 one just gets a snowy screen. 
Consequently I am using kernel 5.8, which works fine, but this is near end of support. 

In all cases, I have this line in the /etc/default/grub

GRUB_CMDLINE_LINUX_DEFAULT="quiet splash apparmor=1 security=apparmor udev.log_priority=3 amdgpu.dc=1"


**Steps to reproduce**

For 5.4 simply use the default installation of Linux Mint 20.3 Cinnamon (and change /etc/default/grub)

For 5.13 use default installation of Linux Mint 20.3 Cinnamon. Boot in compatibility mode and install kernel 5.13. 


**Expected behaviour**

No snowy screen.

**Other information**

See note above on grub config 

**Configuration info, if applicable**
If this bug report is related to an Applet, Desklet or Extension, please paste (or use a pastebin service) the offending extension's settings, if it has any.  You can obtain this by opening its configuration, clicking the 'hamburger' button in the upper-right corner of the window, and selecting "Export to a file". **Please be sure to review the contents and remove any personal data it may contain.**

```

Please paste here

System:    Kernel: 5.8.0-63-generic x86_64 bits: 64 compiler: N/A Desktop: Cinnamon 5.2.7 
           wm: muffin dm: LightDM Distro: Linux Mint 20.3 Una base: Ubuntu 20.04 focal 
Machine:   Type: Laptop System: Micro-Star product: Bravo 15 A4DDR v: REV:1.0 serial: <filter> 
           Chassis: type: 10 serial: <filter> 
           Mobo: Micro-Star model: MS-16WK v: REV:1.0 serial: <filter> UEFI: American Megatrends 
           v: E16WKAMS.10E date: 05/21/2020 
Battery:   ID-1: BAT1 charge: 45.5 Wh condition: 45.5/51.3 Wh (89%) volts: 12.8/11.4 
           model: MSI Corp. MS-16WK serial: N/A status: Full 
           Device-1: hidpp_battery_0 model: Logitech Wireless Mouse serial: <filter> 
           charge: 55% (should be ignored) status: Discharging 
           Device-2: hidpp_battery_1 model: Logitech Wireless Keyboard K540/K545 serial: <filter> 
           charge: 100% (should be ignored) status: Discharging 
CPU:       Topology: 8-Core model: AMD Ryzen 7 4800H with Radeon Graphics bits: 64 type: MT MCP 
           arch: Zen rev: 1 L2 cache: 4096 KiB 
           flags: avx avx2 lm nx pae sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm bogomips: 92626 
           Speed: 1252 MHz min/max: 1400/2900 MHz Core speeds (MHz): 1: 1375 2: 1246 3: 1397 
           4: 1396 5: 1395 6: 1392 7: 1396 8: 1397 9: 1356 10: 1605 11: 1406 12: 1291 13: 1416 
           14: 1484 15: 1394 16: 1397 
Graphics:  Device-1: AMD Navi 14 [Radeon RX 5500/5500M / Pro 5500M] vendor: Micro-Star MSI 
           driver: amdgpu v: kernel bus ID: 03:00.0 chip ID: 1002:7340 
           Device-2: AMD Renoir vendor: Micro-Star MSI driver: amdgpu v: kernel bus ID: 07:00.0 
           chip ID: 1002:1636 
           Display: x11 server: X.Org 1.20.13 driver: amdgpu,ati 
           unloaded: fbdev,modesetting,radeon,vesa resolution: 1920x1080~120Hz, 1920x1080~60Hz 
           OpenGL: renderer: AMD RENOIR (DRM 3.38.0 5.8.0-63-generic LLVM 12.0.0) 
           v: 4.6 Mesa 21.0.3 direct render: Yes 
Audio:     Device-1: AMD Navi 10 HDMI Audio vendor: Micro-Star MSI driver: snd_hda_intel v: kernel 
           bus ID: 03:00.1 chip ID: 1002:ab38 
           Device-2: AMD Raven/Raven2/FireFlight/Renoir Audio Processor vendor: Micro-Star MSI 
           driver: N/A bus ID: 07:00.5 chip ID: 1022:15e2 
           Device-3: AMD Family 17h HD Audio vendor: Micro-Star MSI driver: snd_hda_intel 
           v: kernel bus ID: 07:00.6 chip ID: 1022:15e3 
           Sound Server: ALSA v: k5.8.0-63-generic 
Network:   Device-1: Intel Wi-Fi 6 AX200 driver: iwlwifi v: kernel bus ID: 04:00.0 
           chip ID: 8086:2723 
           IF: wlp4s0 state: up mac: <filter> 
           Device-2: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet vendor: Micro-Star MSI 
           driver: r8169 v: kernel port: f000 bus ID: 05:00.0 chip ID: 10ec:8168 
           IF: enp5s0 state: down mac: <filter> 
Drives:    Local Storage: total: 476.94 GiB used: 193.09 GiB (40.5%) 
           ID-1: /dev/nvme0n1 vendor: Toshiba model: N/A size: 476.94 GiB speed: 15.8 Gb/s 
           lanes: 2 serial: <filter> 
Partition: ID-1: / size: 467.96 GiB used: 96.54 GiB (20.6%) fs: ext4 dev: /dev/nvme0n1p2 
Sensors:   System Temperatures: cpu: 61.9 C mobo: N/A 
           Fan Speeds (RPM): N/A 
           GPU: device: amdgpu temp: 0 C fan: 65535 device: amdgpu temp: 45 C 
Repos:     No active apt repos in: /etc/apt/sources.list 
           Active apt repos in: /etc/apt/sources.list.d/official-package-repositories.list 
           1: deb http: //packages.linuxmint.com una main upstream import backport #id:linuxmint_main
           2: deb http: //archive.ubuntu.com/ubuntu focal main restricted universe multiverse
           3: deb http: //archive.ubuntu.com/ubuntu focal-updates main restricted universe multiverse
           4: deb http: //archive.ubuntu.com/ubuntu focal-backports main restricted universe multiverse
           5: deb http: //security.ubuntu.com/ubuntu/ focal-security main restricted universe multiverse
           6: deb http: //archive.canonical.com/ubuntu/ focal partner
Info:      Processes: 365 Uptime: 11h 33m Memory: 15.11 GiB used: 3.27 GiB (21.7%) Init: systemd 
           v: 245 runlevel: 5 Compilers: gcc: 9.3.0 alt: 9 Client: Unknown python3.8 client 
           inxi: 3.0.38 

```

**Comment by leigh123linux** [comment]
This isn't a cinnamon issue, file it against the ubuntu kernel.
