### ISSUE TITLE
Screenshot Shortcuts don't work any more

### ISSUE THREAD

**Issue by kyoforkshomebrews** [linuxmint/cinnamon#10605]
* Cinnamon version 4.4.8
 * Distribution Ubuntu 20.04
 * Graphics hardware *and* driver used: iGPU: `Intel Core i5-4200U` with driver `i915` dGPU: `AMD Radeon HD 8670M` with driver `amdgpu`
 * 64 bit
 * Attach ~/.xsession-errors, or /var/log/syslog

**Issue**
The following default screenshot shortcuts aren't working for me right now:
Shift+Ctrl+Print
Print
Ctrl+Print

**Steps to reproduce**
1. Try any of the shortcuts above
2. Notice that either nothing happens or a strike through circle appears

**Expected behaviour**
Screenshots either get taken and saved right away or the plus-cursor appears.

[xsession-errors.txt](https://github.com/linuxmint/cinnamon/files/7873997/xsession-errors.txt)

**Comment by leigh123linux** [comment]
cinnamon-4.4.x is EOL, update to cinnamon-5.2.x

**Comment by dominikpegler** [comment]
Same problem with a fresh installation on cinnamon 5.2.7

Cinnamon 5.2.7 
OS: Manjaro Linux x86_64 
20KH006JGE ThinkPad X1 Carbon 6th 
Kernel: 5.15.16-1-MANJARO 
1920x1080 
CPU: Intel i7-8550U (8) @ 4.000GHz 
GPU: Intel UHD Graphics 620 

The PRINT key is recognized correctly and is assigned
