### ISSUE TITLE
Linux-Kernal 5.13 not working

### ISSUE THREAD

**Issue by Captainpast** [linuxmint/cinnamon#10617]
```
 * Cinnamon 5.2.7
 * Mint 20.3
 * NVIDIA GeForce GTX 1650 Ti, nvidia-driver-470
 * 64 bit
 * PC: XMG CORE 15 (REN/M20) 
 ```

**Issue**
After installing  Linux-Kernal 5.13 and rebooting and after the Mint-logo is displayed the laptop screen is only flickering.

**Other information**
- Linux-Kernal 5.4 is also not working, but only black screen
- I currently use Linux-Kernal 5.11 (that’s working)
- external monitors also working, its only the laptop screen

**Comment by nachtelb** [comment]
I could confirm problems with 15 laptops at my school. It seems to me, the flickering laptop-monitor has something to do with the GPU and the internal monitor. 

The 15 laptops use Linuxmint 20.1, 20.2 and 20.3.

The following actions lead to the flickering internal monitor:
- Screensaver (Bug #10615)
- shutting off internal monitor through energy-saving
- Connecting to external monitors via hdmi 

My colleague installed latest ubuntu on one of the laptops and the problem could not be reproduced.

Systeminformation:
System:    Kernel: 5.13.0-27-generic x86_64 bits: 64 compiler: N/A Desktop: Cinnamon 5.0.7 
           wm: muffin dm: LightDM Distro: Linux Mint 20.2 Uma base: Ubuntu 20.04 focal 
Machine:   Type: Laptop System: LENOVO product: 20VF v: ThinkBook 14 G2 ARE serial: <filter> 
           Chassis: type: 10 v: ThinkBook 14 G2 ARE serial: <filter> 
           Mobo: LENOVO model: LNVNB161216 v: SDK0J40697 WIN serial: <filter> UEFI: LENOVO 
           v: FACN23WW(V1.06) date: 10/27/2020 
Battery:   ID-1: BAT1 charge: 32.5 Wh condition: 44.6/45.0 Wh (99%) volts: 12.4/11.6 
           model: 0x4C 0x47 0x43 0x00 0x32 0x30 0x 0x4C 0x31 0x39 0x4C 0x33 0x50 0x4500 
           serial: <filter> status: Charging 
CPU:       Topology: 8-Core model: AMD Ryzen 7 4700U with Radeon Graphics bits: 64 type: MCP 
           arch: Zen rev: 1 L2 cache: 4096 KiB 
           flags: avx avx2 lm nx pae sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm bogomips: 31937 
           Speed: 1397 MHz min/max: 1400/2000 MHz Core speeds (MHz): 1: 1397 2: 1397 3: 1397 
           4: 1397 5: 1397 6: 1397 7: 1397 8: 1397 
Graphics:  Device-1: AMD Renoir vendor: Lenovo driver: amdgpu v: kernel bus ID: 05:00.0 
           chip ID: 1002:1636 
           Display: x11 server: X.Org 1.20.13 driver: amdgpu,ati unloaded: fbdev,modesetting,vesa 
           resolution: 1920x1080~60Hz, 1920x1080~60Hz 
           OpenGL: renderer: AMD RENOIR (DRM 3.41.0 5.13.0-27-generic LLVM 12.0.0) 
           v: 4.6 Mesa 21.0.3 direct render: Yes 
Audio:     Device-1: AMD vendor: Lenovo driver: snd_hda_intel v: kernel bus ID: 05:00.1 
           chip ID: 1002:1637 
           Device-2: AMD Raven/Raven2/FireFlight/Renoir Audio Processor vendor: Lenovo driver: N/A 
           bus ID: 05:00.5 chip ID: 1022:15e2 
           Device-3: AMD Family 17h HD Audio vendor: Lenovo driver: snd_hda_intel v: kernel 
           bus ID: 05:00.6 chip ID: 1022:15e3 
           Device-4: C-Media Audio Adapter (Unitek Y-247A) type: USB 
           driver: hid-generic,snd-usb-audio,usbhid bus ID: 1-1.4:11 chip ID: 0d8c:0014 
           Sound Server: ALSA v: k5.13.0-27-generic 
Network:   Device-1: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet vendor: Lenovo 
           driver: r8169 v: kernel port: 2000 bus ID: 03:00.0 chip ID: 10ec:8168 
           IF: eno1 state: down mac: <filter> 
           Device-2: Intel Wi-Fi 6 AX200 driver: iwlwifi v: kernel port: 2000 bus ID: 04:00.0 
           chip ID: 8086:2723 
           IF: wlp4s0 state: up mac: <filter> 
           Device-3: Realtek RTL8153 Gigabit Ethernet Adapter type: USB driver: r8152 
           bus ID: 2-1.2:6 chip ID: 0bda:8153 
           IF: enx98fc84e22609 state: up speed: 1000 Mbps duplex: full mac: <filter> 
Drives:    Local Storage: total: 476.94 GiB used: 321.29 GiB (67.4%) 
           ID-1: /dev/nvme0n1 vendor: Western Digital model: PC SN530 SDBPMPZ-512G-1101 
           size: 476.94 GiB speed: 31.6 Gb/s lanes: 4 serial: <filter> 
Partition: ID-1: / size: 467.96 GiB used: 160.64 GiB (34.3%) fs: ext4 dev: /dev/nvme0n1p2 
Sensors:   System Temperatures: cpu: 50.6 C mobo: N/A gpu: amdgpu temp: 38 C 
           Fan Speeds (RPM): N/A 
Repos:     No active apt repos in: /etc/apt/sources.list 
           Active apt repos in: /etc/apt/sources.list.d/anydesk-stable.list 
           1: deb http: //deb.anydesk.com/ all main
           Active apt repos in: /etc/apt/sources.list.d/freecad-maintainers-freecad-stable-focal.list 
           1: deb http: //ppa.launchpad.net/freecad-maintainers/freecad-stable/ubuntu focal main
           Active apt repos in: /etc/apt/sources.list.d/google-chrome.list 
           1: deb [arch=amd64] http: //dl.google.com/linux/chrome/deb/ stable main
           Active apt repos in: /etc/apt/sources.list.d/libreoffice-ppa-focal.list 
           1: deb http: //ppa.launchpad.net/libreoffice/ppa/ubuntu focal main
           Active apt repos in: /etc/apt/sources.list.d/official-package-repositories.list 
           1: deb http: //packages.linuxmint.com uma main upstream import backport #id:linuxmint_main
           2: deb http: //archive.ubuntu.com/ubuntu focal main restricted universe multiverse
           3: deb http: //archive.ubuntu.com/ubuntu focal-updates main restricted universe multiverse
           4: deb http: //archive.ubuntu.com/ubuntu focal-backports main restricted universe multiverse
           5: deb http: //security.ubuntu.com/ubuntu/ focal-security main restricted universe multiverse
           6: deb http: //archive.canonical.com/ubuntu/ focal partner
           Active apt repos in: /etc/apt/sources.list.d/spotify.list 
           1: deb http: //repository.spotify.com stable non-free
           Active apt repos in: /etc/apt/sources.list.d/teamviewer.list 
           1: deb https: //linux.teamviewer.com/deb stable main
Info:      Processes: 286 Uptime: 36m Memory: 13.53 GiB used: 2.32 GiB (17.1%) Init: systemd 
           v: 245 runlevel: 5 Compilers: gcc: 9.3.0 alt: 9 Client: Unknown python3.8 client 
           inxi: 3.0.38

**Comment by leigh123linux** [comment]
Report the issue against the kernel or driver.
