### ISSUE TITLE
Caja has no icon on the taskbar and start menu

### ISSUE THREAD

**Issue by RDKRACZ** [linuxmint/cinnamon#10614]
```
 * Cinnamon version - 5.2.7 from Fedora repo
 * Distribution - Fedora 35
 * Graphics hardware *and* driver used - Intel i5-3427U (4) @ 2.800GHz with integrated GPU
 * 64 bit
 * Attach ~/.xsession-errors, or /var/log/syslog
 Will do if You say is necessary to debug this.
 ```

**Issue**
The second icon is Caja
![image](https://user-images.githubusercontent.com/43277609/150527926-ad5fbdb4-a435-43a1-ac4f-2e82c92af37f.png)

![image](https://user-images.githubusercontent.com/43277609/150527938-c28885e9-d8ab-4651-b1de-f8ea792a8c97.png)

**Comment by RDKRACZ** [comment]
https://github.com/mate-desktop/caja/issues/1604

**Comment by mtwebster** [comment]
I can't reproduce the problem in the taskbar. Caja doesn't (and shouldn't) show up in the start menu, as it's configured to only be visible when you're using MATE as your desktop, unless you create a custom menu entry.

Perhaps you made some custom desktop file and forgot to specify the icon in it? You can create one from the menu editor (right-click menu->second tab->open menu editor). You click on the large icon in the dialog that pops up, and can choose a specific icon to use.
