### ISSUE TITLE
cinnamon-settings network error

### ISSUE THREAD

**Issue by cromerc** [linuxmint/cinnamon#10616]
When running the command:
````cinnamon-settings network````

Users are getting this:
````
/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py:433: DeprecationWarning: Gtk.Window.set_wmclass is deprecated
  self.window.set_wmclass(wm_class, wm_class)
/usr/lib/python3.10/site-packages/gi/overrides/Gio.py:42: Warning: invalid unclassed pointer in cast to 'NMACertChooserButton'
  return Gio.Application.run(self, *args, **kwargs)
/usr/lib/python3.10/site-packages/gi/overrides/Gio.py:42: Warning: g_type_instance_get_private: assertion 'instance != NULL && instance->g_class != NULL' failed
  return Gio.Application.run(self, *args, **kwargs)
Segmentation fault
````

This is confirmed to happen in both artix linux and arch linux:
https://forum.artixlinux.org/index.php/topic,3550.msg22987.html#msg22987

**Comment by mtwebster** [comment]
There's insufficient info here. The template you deleted when you clicked 'new issue' is there for a reason, please don't ignore it.

Also, I need more than that terminal output. Can you get a stack trace or coredump?

**Comment by cromerc** [comment]
There is no template, I am posting from the github android app, sorry about that.

**Comment by mtwebster** [comment]
Ah, sorry - I didn't realize they ignore the template there.  That's a bit dumb.

I assume this is cinnamon 5.2? All cinnamon packages and muffin are as well? (I know sometimes arch packaging ends up staggered a bit during a new release)

**Comment by cromerc** [comment]
I haven't checked all of arch linux's package versions, but under Artix we have been using 5.2 since the end of December. And all cinnamon packages are up to date with the latest version tags here on github.

I will get those logs a little later, not at my computer to check at the moment.

**Comment by cromerc** [comment]
Now on my laptop, here is the template:

```
 * Cinnamon 5.2.7
 * Artix Linux
 * NVIDIA GeForce GTX 1650 with nvidia 495 driver
 * 64 bit
 * Attach ~/.xsession-errors, or /var/log/syslog
 ```

**Issue**
cinnamon-settings network crashes with a segfault when launched.


**Steps to reproduce**
Write "cinnamon-settings network" in a terminal and run.


**Expected behaviour**
Networking settings should open.


**Other information**
Not applicable.

**Configuration info, if applicable**
Not applicable.

I have attached my ~/.xsession-errors, a strace, and a core dump. If you need anything else just let me know.

[xsession-errors.txt](https://github.com/linuxmint/cinnamon/files/7918938/xsession-errors.txt)
[strace.txt](https://github.com/linuxmint/cinnamon/files/7918959/strace.txt)
[core dump](https://we.tl/t-Us3tA4N30p)

**Comment by CommanderRedYT** [comment]
I really would be interested in researching since when this is broken

**Comment by leigh123linux** [comment]
Works fine here.

```[leigh@mpd payload]$ python --version
Python 3.10.1
[leigh@mpd payload]$ cinnamon --version
Cinnamon 5.2.7
[leigh@mpd payload]$ cinnamon-settings network
Using pam module (python3-pampy)
/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py:433: DeprecationWarning: Gtk.Window.set_wmclass is deprecated
  self.window.set_wmclass(wm_class, wm_class)
```

Perhaps Arch has broken python?

**Comment by cromerc** [comment]
> Works fine here.
> 
> ```[leigh@mpd payload]$ python --version
> Python 3.10.1
> [leigh@mpd payload]$ cinnamon --version
> Cinnamon 5.2.7
> [leigh@mpd payload]$ cinnamon-settings network
> Using pam module (python3-pampy)
> /usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py:433: DeprecationWarning: Gtk.Window.set_wmclass is deprecated
>   self.window.set_wmclass(wm_class, wm_class)
> ```
> 
> Perhaps Arch has broken python?

The odds that python is broken on both arch and artix, 2 different distros isn't highly likely.

**Comment by CommanderRedYT** [comment]
I will check on that... The weird thing is, I did not find any touched files that could be the problem. And the problem just.. appeared.. maybe some dependencie needs an update, I'll try that asap

**Comment by TeeraAskort** [comment]
This started happening too on opensuse tumbleweed a couple days ago, although the cinnamon-settings version is different from arch's one, it still has this segmentation fault.
Can someone point which dependencies are needed to run this part of cinnamon settings, maybe some update removed some dependency needed and now it's segfaulting because it can't find it.

**Comment by leigh123linux** [comment]
Can anyone provide a useful backtrace?

https://wiki.python.org/moin/DebuggingWithGdb

**Comment by cromerc** [comment]
> Can anyone provide a useful backtrace?
> 
> https://wiki.python.org/moin/DebuggingWithGdb

I supplied both a strace and a core dump above.

**Comment by leigh123linux** [comment]
@cromerc  The un-processed core file is useless, it needs to be processed on your PC with the required debug symbols installed.

**Comment by cromerc** [comment]
Both arch and artix linux include the debug symbols in all binaries/libs by default... So not sure what the issue here is...

**Comment by aaruni96** [comment]
I have just installed Archlinux and am plagued by the same issue

Python version : 3.10.2
Cinnamon version : 5.2.7

@cromerc It would appear that the version of python included really does not have debug symbols.

The output from `gdb python` is

```
Reading symbols from python...
(No debugging symbols found in python)
```

**Comment by TeeraAskort** [comment]
I've installed python-dbg on arch and found that it can't find the network module and defaults to gnome-control-center.
```
(gdb) run /usr/bin/cinnamon-settings network
Starting program: /usr/bin/python-dbg /usr/bin/cinnamon-settings network
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
Unknown module network, calling gnome-control-center
process 23639 is executing new program: /usr/bin/gnome-control-center
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7fffea022640 (LWP 23643)]
[New Thread 0x7fffe97ff640 (LWP 23644)]
[New Thread 0x7fffe8bd8640 (LWP 23645)]
[New Thread 0x7fffe2332640 (LWP 23646)]
[New Thread 0x7fffe1b31640 (LWP 23647)]
[New Thread 0x7fffe1330640 (LWP 23648)]
[New Thread 0x7fffe0b2f640 (LWP 23649)]
[New Thread 0x7fffd57d1640 (LWP 23650)]
[New Thread 0x7fffd4fd0640 (LWP 23651)]
[New Thread 0x7fffb7fff640 (LWP 23652)]
[Thread 0x7fffb7fff640 (LWP 23652) exited]
[New Thread 0x7fffb7fff640 (LWP 23653)]
[Detaching after fork from child process 23654]
[New Thread 0x7fffb77fe640 (LWP 23659)]
[Thread 0x7fffb77fe640 (LWP 23659) exited]
[New Thread 0x7fffb77fe640 (LWP 23660)]
[New Thread 0x7fffb6ffd640 (LWP 23661)]
[Thread 0x7fffb77fe640 (LWP 23660) exited]
[New Thread 0x7fffb77fe640 (LWP 23662)]
[Thread 0x7fffb6ffd640 (LWP 23661) exited]
[New Thread 0x7fffb6ffd640 (LWP 23663)]
[Thread 0x7fffb77fe640 (LWP 23662) exited]
[Thread 0x7fffb6ffd640 (LWP 23663) exited]
[New Thread 0x7fffb6ffd640 (LWP 23664)]
[New Thread 0x7fffb77fe640 (LWP 23665)]
[New Thread 0x7fffb67fc640 (LWP 23666)]
[New Thread 0x7fffb571b640 (LWP 23667)]
[New Thread 0x7fffb4f1a640 (LWP 23668)]
[Thread 0x7fffb571b640 (LWP 23667) exited]
[New Thread 0x7fffb571b640 (LWP 23669)]
[New Thread 0x7fff9ffff640 (LWP 23670)]
[Thread 0x7fffb4f1a640 (LWP 23668) exited]
[Thread 0x7fffb571b640 (LWP 23669) exited]
[Thread 0x7fff9ffff640 (LWP 23670) exited]
[New Thread 0x7fff9ffff640 (LWP 23671)]
[New Thread 0x7fffb571b640 (LWP 23672)]
[Thread 0x7fff9ffff640 (LWP 23671) exited]
[New Thread 0x7fff9ffff640 (LWP 23673)]
[New Thread 0x7fffb4f1a640 (LWP 23674)]
[Thread 0x7fff9ffff640 (LWP 23673) exited]
[Thread 0x7fffb571b640 (LWP 23672) exited]
[New Thread 0x7fffb571b640 (LWP 23675)]
[New Thread 0x7fff9ffff640 (LWP 23676)]
[Thread 0x7fffb4f1a640 (LWP 23674) exited]
[Thread 0x7fffb571b640 (LWP 23675) exited]
[New Thread 0x7fffb571b640 (LWP 23677)]
[New Thread 0x7fffb4f1a640 (LWP 23678)]
[Thread 0x7fffb571b640 (LWP 23677) exited]
[Thread 0x7fff9ffff640 (LWP 23676) exited]
[Thread 0x7fffb4f1a640 (LWP 23678) exited]
[Thread 0x7fffb67fc640 (LWP 23666) exited]
[Thread 0x7fffb7fff640 (LWP 23653) exited]
[Thread 0x7fffd4fd0640 (LWP 23651) exited]
[Thread 0x7fffd57d1640 (LWP 23650) exited]
[Thread 0x7fffe0b2f640 (LWP 23649) exited]
[Thread 0x7fffe1330640 (LWP 23648) exited]
[Thread 0x7fffe1b31640 (LWP 23647) exited]
[Thread 0x7fffe2332640 (LWP 23646) exited]
[Thread 0x7fffe8bd8640 (LWP 23645) exited]
[Thread 0x7fffb6ffd640 (LWP 23664) exited]
[Thread 0x7fffe97ff640 (LWP 23644) exited]
[Thread 0x7fffea022640 (LWP 23643) exited]
[Thread 0x7fffea852440 (LWP 23639) exited]
[Inferior 1 (process 23639) exited normally]
```

This is the output from launching cinnamon-settings and the accessing the module from the GUI.
```
/usr/lib/python3.10/site-packages/gi/overrides/Gio.py:42: Warning: invalid unclassed pointer in cast to 'NMACertChooserButton'
  return Gio.Application.run(self, *args, **kwargs)
/usr/lib/python3.10/site-packages/gi/overrides/Gio.py:42: Warning: g_type_instance_get_private: assertion 'instance != NULL && instance->g_class != NULL' failed
  return Gio.Application.run(self, *args, **kwargs)

Thread 1 "cinnamon-settin" received signal SIGSEGV, Segmentation fault.
0x00007fffe2c8e370 in ?? () from /usr/lib/libnma.so.0
```

Is there anything else I need to run?

**Comment by leigh123linux** [comment]
Arch will probably need to rebuild cinnamon-control-center for the new libnma .so

```
$ rpm -q --requires cinnamon-control-center |grep libnma
libnma.so.0()(64bit)
libnma.so.0(libnma_1_2_0)(64bit)
libnma.so.0(libnma_1_8_0)(64bit)
```

**Comment by cromerc** [comment]
> 

Nope, that isn't the problem, our cinnamon-control-center is already built using libnma 1.8.34 and shows the same issue

I have attached the build log(which shows libnma 1.8.34 was used) from when it was compiled if it helps.

[jenkins.txt](https://github.com/linuxmint/cinnamon/files/7961085/jenkins.txt)
.

**Comment by cromerc** [comment]
I just did a test and installed libnma 1.8.32 in artix linux, and the issue does go away in artix too. So something changed between 1.8.34 and 1.8.32 that is causing it to be broken.

**Comment by justnext** [comment]
Void Linux Cinnamon 5.2.7 is in the same situation.  'cinnamon-settings network' command:
- works fine with libnma 1.8.32
- segfaults with libnma 1.8.34

**Comment by mtwebster** [comment]
Can someone try rebuilding cinnamon-control-center with this change? (The HAVE_NMA_18 line removed)
```
diff --git a/meson.build b/meson.build
index 3040abf..bdac92a 100644
--- a/meson.build
+++ b/meson.build
@@ -56,8 +56,6 @@ else
   libnma= dependency('', required: false)
 endif

-config.set('HAVE_NMA_18', libnm.version().version_compare('>=1.8.0'))
-
 if get_option('modemmanager')
   if not get_option('networkmanager')
     error('*** NetworkManager is required by ModemManager ***')

```

**Comment by cromerc** [comment]
> Can someone try rebuilding cinnamon-control-center with this change? (The HAVE_NMA_18 line removed)
> ```
> diff --git a/meson.build b/meson.build
> index 3040abf..bdac92a 100644
> --- a/meson.build
> +++ b/meson.build
> @@ -56,8 +56,6 @@ else
>    libnma= dependency('', required: false)
>  endif
> 
> -config.set('HAVE_NMA_18', libnm.version().version_compare('>=1.8.0'))
> -
>  if get_option('modemmanager')
>    if not get_option('networkmanager')
>      error('*** NetworkManager is required by ModemManager ***')
> 
> ```
> 

Will give it a shot tonight when I got on my computer.

**Comment by cromerc** [comment]
> Can someone try rebuilding cinnamon-control-center with this change? (The HAVE_NMA_18 line removed)
> 
> ```
> diff --git a/meson.build b/meson.build
> index 3040abf..bdac92a 100644
> --- a/meson.build
> +++ b/meson.build
> @@ -56,8 +56,6 @@ else
>    libnma= dependency('', required: false)
>  endif
> 
> -config.set('HAVE_NMA_18', libnm.version().version_compare('>=1.8.0'))
> -
>  if get_option('modemmanager')
>    if not get_option('networkmanager')
>      error('*** NetworkManager is required by ModemManager ***')
> ```

The patch is working. I am going to push cinnamon-control-center with this patch to our repos now.
