### ISSUE TITLE
Calendar view wrong padding

### ISSUE THREAD

**Issue by Dasdar990** [linuxmint/cinnamon#10627]
I am facing just a small graphical issue. Can you please fix this padding in the calendar view?  
![photo_2022-01-24_11-58-05](https://user-images.githubusercontent.com/56268536/150770725-4975e6e2-2fba-4312-8013-d7b4e6d16097.jpg)
I'm sorry for the photo but I couldn't take a screenshot

**Comment by Dasdar990** [comment]
I am currently using Canta, but I also tried Vimix

**Comment by smurphos** [comment]
I guess you've gathered it's an issue that needs to be fixed by the 3rd party theme.

**Comment by Dasdar990** [comment]
> I guess you've gathered it's an issue that needs to be fixed by the 3rd party theme.

Yes, since the last update I am facing different issues with this theme
