### ISSUE TITLE
[Feature Request] Show text and value when adjusting brightness slider

### ISSUE THREAD

**Issue by tur1ngb0x** [linuxmint/cinnamon#10622]
**Details**
* Distribution: Linux Mint 20.3 Cinnamon 64-bit
* Cinnamon Version: 5.2.7
* Graphics Hardware: Intel UHD 620 (i915)

**Issue**

By default, when adjusting brightness slider using Power Manager applet, it does not show brightness text and value.

**Steps to reproduce**
* Click on Power Manager applet.
* Drag the brightness slider to the left or right.

**Expected behaviour**

The brightness applet should show the brightness text and value like the Sound applet when sound is being adjusted.

**Screenshots**
![power-manager-applet](https://user-images.githubusercontent.com/25666761/150665625-6794eaf4-e5b7-4340-ade8-a3829c03ae70.png)

![sound-applet](https://user-images.githubusercontent.com/25666761/150665790-0cb6b920-0d80-4e10-8bdd-f52bb90d0df7.png)

**Comment by kimimaru4000** [comment]
@tur1ngb0x The feature has been merged in, so I believe this issue can be closed.
