### ISSUE TITLE
[Feature request] integrate with power-profiles-daemon

### ISSUE THREAD

**Issue by Lurux** [linuxmint/cinnamon#10634]
Since this seems to be a desktop-agnostic way to manage power profiles, I think it would be interesting to integrate it in the power settings (and applet)

**Issue**

Currently there is no easy way for Cinnamon users to manage power profiles, AFAIK

**Solution**

Install the ppdaemon by default and integrate it in Cinnamon. The daemon allows manual change, as well as automatic change on charge, low battery, high temperature and more

**Comment by ItzSwirlz** [comment]
Posting these files for reference:

https://github.com/GNOME/gnome-shell/blob/main/js/ui/status/powerProfiles.js
https://github.com/GNOME/gnome-shell/blob/main/js/ui/status/power.js
