### ISSUE TITLE
Offloading to discrete gpu.

### ISSUE THREAD

**Issue by DmitruMoth** [linuxmint/cinnamon#10665]
* Cinnamon version: 5.2.7
* Distribution: Arch
* GTX 1070, nvidia driver
* 64 bit
* Cinnamon warning: Log level 128: Offloading 'Steam (Native)' to discrete gpu.

**Issue**
Running apps with option `PrefersNonDefaultGPU=true` in .desktop file from panel / launch menu cause immediate logout.

**Steps to reproduce**
For example, steam-native from archlinux repository has this option in their .desktop file. Launch it from launch menu -> logout. Launch steam-native from terminal -> all work. Copy .desktop file to the desktop and launch -> all work. The problem is then launch from menu launcher or panel. There is this log in .xsession-errors: `Cinnamon warning: Log level 128: Offloading 'Steam (Native)' to discrete gpu.`.

**Expected behaviour**
Launch apps with `PrefersNonDefaultGPU=true`

**Other information**
I have Intel GPU in my cpu, but there is no installed driver and i dont use this.

**Comment by mtwebster** [comment]
I couldn't reproduce the logout/crash - the app i tried just launched normally. Either way, it should be fixed now.

**Comment by prorounak2005** [comment]
It has not been fixed -_________-
