### ISSUE TITLE
Opening steam in cinnamon logs out the user 

### ISSUE THREAD

**Issue by prorounak2005** [linuxmint/cinnamon#10664]
```
 * Cinnamon version (cinnamon --version) - cinnamon 5.2.7-2
   - Please specify if you are using the daily builds PPA
     (https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds).
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Arch Linux
 * Graphics hardware *and* driver used - GTX 1650 : I3-9100F CPU 
 * 32 or 64 bit - I am use 64 BIT pc 
 * Attach ~/.xsession-errors, or /var/log/syslog
 ```

**Issue**

Opening steam from menu logs out the user. Whenver I try to lauch steam from the cinnamon menu it logs me out. I installed a fresh arch linux today but still I am facing the same problem but on other desktop environments I am not facing the issue. But if I lauch steam from shortcut on desktop in cinnamon it doesnt log me out. 

**Steps to reproduce**
1. Use arch linux
2. Install steam 
3. Open the steam runtime shortcut from menu. (Don't click the steam shortcut on the desktop).
4. Ur screen will go black and u will automatically log out to ur display manager (lightdm in my case)
.

**Expected behaviour**

I expected it will launch steam so that I can play games :man_shrugging: 

**Other information**
N/A

**Configuration info, if applicable**
If this bug report is related to an Applet, Desklet or Extension, please paste (or use a pastebin service) the offending extension's settings, if it has any.  You can obtain this by opening its configuration, clicking the 'hamburger' button in the upper-right corner of the window, and selecting "Export to a file". **Please be sure to review the contents and remove any personal data it may contain.**

```

N/A

```

**Comment by DmitruMoth** [comment]
I have the same problem, look at #10665
