### ISSUE TITLE
[Feature request] Show seconds button in the "Date and Time Settings" window

### ISSUE THREAD

**Issue by RDKRACZ** [linuxmint/cinnamon#10698]
**Issue**
No option to enable seconds in the clock on the panel

**Other information**
Currently, this can be achieved by creating the custom date format but this is not a user-friendly solution and I'm sure the are Cinnamon users that are not even aware that this is possible.

![image](https://user-images.githubusercontent.com/43277609/157110181-0da424ab-731f-4c58-a980-ae7d097340af.png)

**Comment by mtwebster** [comment]
You don't see this?
![image](https://user-images.githubusercontent.com/262776/157111045-ba47aa98-e983-4984-99af-56b64b3e74d0.png)

**Comment by RDKRACZ** [comment]
It looks like there are two different date and time settings... The one you are talking about is accessed via System Settings whereas I was looking at the one that opens when you click at the "Configure" in the right-click menu of the clock:
![image](https://user-images.githubusercontent.com/43277609/157117491-8bccca23-85f8-4939-ab5e-5f44d6bb87f0.png)

**Comment by mtwebster** [comment]
The settings I mentioned are the global settings, which affect the calendar applet as well as any other extensions and apps that may display the time. The applet's settings simply allow you to customize its display, if you'd rather have some specific format.

Having 'standard' format variations based on the 24h, date and seconds settings also allows us to localize them for different regions - for a vast majority of users, it provides all the customization they'd ever want.
