### ISSUE TITLE
Cinnamon expires notifications

### ISSUE THREAD

**Issue by tripleo1** [linuxmint/cinnamon#10690]
Cinnamon 5.2.7 (although this is not new behavior)
Mint Una
Intel driver
64 bit

**Issue**

Cinnamon expires notifications

**Steps to reproduce**

Get a notification
Don't respond to it in time
Watch it disappear

**Expected behaviour**

Let it (them) persists until dismissed

**Comment by DirkHaar** [comment]
I'm not quite sure - but I think I read about that issue some years ago the other way round - i.e. "message should vanish and don't disturb me!" - or a complaint that the time was not adjustable.
Looked it up on my system and found this file:
~/cinnamon/configs/notifications@cinnamon.org/notifications@cinnamon.org.json
where I found keybinding <Super>n     ("some self-labelled key" + n on my system).
This pops up the notification applet ("No notifications/settings").
In these settings you can
- de/activate notifications
- set if n. are persistant
- set top or bottom to show the message and test it.
Test say: I don't give a fork on you asking for persistance... Surprise!

**Comment by DirkHaar** [comment]
There is another settings dialog when you enter via spices/applets and choose the settings for notifications there
having an additional topic "ignore temporary notif." (or similar, I use a German Mint).
Try combinations of the above settings, maybe not. can be declared to be temporary (i.e. "self-destructing") so setting to persist should not have an effect by defintion. I'm not awary if that's the case and - if - if the test button mentioned above issues a temporary one or if this is really a bug.

**Comment by tripleo1** [comment]
I looked in the system settings and couldn't find anything that would help me.

What I want is to control when notifications are no longer present on my system.  I notice GNOME 40 on Manjaro doesn't have this problem. Sometimes there are dozens of notifications waiting for my attention.

Also, and this has been noted elsewhere, that if you click one firefox notification all of them disappear.

**Comment by AxXxB** [comment]
It seems you should just disable "Ignore temporary notifications" settings to achieve desired behavior, as DirkHaar mentioned. It's not in the system settings but in the notifications applet settings (under right-click the notifications icon in the tray).

**Comment by tripleo1** [comment]
@AxXxB I don't have "Ignore temporary notifications" in my Notifications Settings Panel (Just checked).

@DirkHaar I didn't see anything about persistence in the .json file (Just checked). Maybe you could show me the relevant lines below?

**Comment by DirkHaar** [comment]
@tripleo1 
Are we still talking about the applet notifications@cinnamon.org?
Open it with right click.
Select "Ignore transient notifications".

That should do it.

Additionally you could select "Open notification settings" then where you find
"Remove notifications after their timeout is reached".
The timeout value can be changed via dconf-editor, it's the key
timeout in org.cinnamon.desktop.notifications, default 1.800.

You'll also find /org/cinnamon/desktop/notifications/fade-on-mouseover
"fade-opacity" and "remove-old".

**Comment by tripleo1** [comment]
On 4/6/22 10:35, AxXxB wrote:
>
> It seems you should just disable "Ignore temporary notifications" 
> settings to achieve desired behavior, as DirkHaar mentioned. It's not 
> in the system settings but in the notifications applet settings (under 
> right-click the notifications icon in the tray).
>
In English, it says "Ignore transient notifications" (as the other 
comment now says). I just found it and will try it and see if it works. 
Thanks for your help.

Two notes:

 1. What the h*ll is "Ignore transient notifications" supposed to mean?
 2. There should not be two places where configuration is taking place. 
    (And if there is, I would like to know the reason.)

**Comment by tripleo1** [comment]
@DirkHaar I will save this message. Thank you for your assistance. (I 
have replied above.)

**Comment by DirkHaar** [comment]
Interesting you complain about "transient"😅
Because I'm German and translating that back to English I came to "temporary". I had to start my English versioned VM 😁
Short-lived, fading or volatile would be more suitable for Average Joe's language, right?

**Comment by tripleo1** [comment]
On 4/16/22 18:40, DirkHaar wrote:
>
> Interesting you complain about "transient"😅
> Because I'm German and translating that back to English I came to 
> "temporary". I had to start my English versioned VM 😁
> Short-lived, fading or volatile would be more suitable for Average 
> Joe's language, right?
>
I'm not complaining about your translation, what I'm saying is that I 
have never heard the terminology "transient notifications", and there is 
no explanation anywhere for it.

FWIW, volatile is not an "Average Joe" word.

And why does it say "Ignore", and how was I supposed to find this 
setting, etc.

**Comment by mtwebster** [comment]
The point of the notification applet is to hang on to notifications you missed instead of them disappearing. 

Transient isn't a very helpful word, though that's how they're referred to in the developer side of things. A transient notification is one where, if you miss it, it's no big deal - a notification from your music player telling you the next song is an example of a transient. Unfortunately many apps that should make use of this distinction do not, so it's a crapshoot. The reason it's in the applet's settings is because that's what it affects - transient notifications don't get transferred to the tray once the timeout ends (or would, if the application implemented it properly).

**Comment by AxXxB** [comment]
I think it's should be rephrased because it's not sematically accurate. One could think that this option enabled means the applet will not show some sort of notifications (transient) instead of ignoring "transientness" of notifications. Maybe "Keep transient notifications" would be better?

**Comment by DirkHaar** [comment]
still "temporary", "fading", even "vanishing" or "ignorable" would be better imho.
