### ISSUE TITLE
Power management after suspend/hibernate

### ISSUE THREAD

**Issue by burny0202** [linuxmint/cinnamon#10718]
```
 * Cinnamon version - cinnamon-desktop 5.2.1-1 
 * Distribution - Arch
 * Graphics hardware *and* driver used - Nvidia 960 - nvidia-lts 1:510.54-9
 * 64 bit
 ```

**Issue**
Power management functions do not work after a suspend/hibernate

**Steps to reproduce**
Wait for screen to turn off - Success
Put computer into suspend
Wake Computer
Wait for screen to turn off - No longer works

**Expected behaviour**
To function as options direct, prior to suspend

**Other information**
ALT + F2  - CMD r  - Does not appear to fix

Swiching between TTY and then restarting cinnamon sometimes works. Sometimes gives strange transparent windows & theme
Not sure if related, journalctl below

`Mar 22 17:35:34 sys dbus-daemon[805]: [session uid=1001 pid=805] Activated service 'org.cinnamon.CalendarServer' failed: Process org.cinnamon.CalendarServer exited with status 1

Mar 22 17:36:32 sys dbus-daemon[805]: [session uid=1001 pid=805] Activating service name='org.cinnamon.CalendarServer' requested by ':1.284' (uid=1001 pid=27684 comm="cinnamon --replace")

Mar 22 17:36:32 sys org.cinnamon.CalendarServer[27729]: Traceback (most recent call last):

Mar 22 17:36:32 sys org.cinnamon.CalendarServer[27729]:   File "/usr/lib/cinnamon/cinnamon-calendar-server.py", line 14, in <module>

Mar 22 17:36:32 sys org.cinnamon.CalendarServer[27729]:     gi.require_version('EDataServer', '1.2')

Mar 22 17:36:32 sys org.cinnamon.CalendarServer[27729]:   File "/usr/lib/python3.10/site-packages/gi/__init__.py", line 126, in require_version

Mar 22 17:36:32 sys org.cinnamon.CalendarServer[27729]:     raise ValueError('Namespace %s not available' % namespace)

Mar 22 17:36:32 sys org.cinnamon.CalendarServer[27729]: ValueError: Namespace EDataServer not available

Mar 22 17:36:32 sys dbus-daemon[805]: [session uid=1001 pid=805] Activated service 'org.cinnamon.CalendarServer' failed: Process org.cinnamon.CalendarServer exited with status 1`

**Comment by leigh123linux** [comment]
Report the issue to nvidia.

https://forums.developer.nvidia.com/c/gpu-graphics/linux/148
