### ISSUE TITLE
Linux Mint 20.3 Cinnamon 

### ISSUE THREAD

**Issue by agentl074** [linuxmint/cinnamon#10717]
Issue: Cinnamon -- leaving session i.e., logout does not have sound chime. It is logout.ogg
Should it be logout.oga 

Kernel: 5.4.0-105-generic x86_64 bits: 64 compiler: gcc v: 9.4.0 
           Desktop: Cinnamon 5.2.7 wm: muffin dm: LightDM Distro: Linux Mint 20.3 Una 
           base: Ubuntu 20.04 focal 

```
 * Cinnamon version (cinnamon --version)
   - Please specify if you are using the daily builds PPA
     (https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds).
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
 * Graphics hardware *and* driver used
 * 32 or 64 bit
 * Attach ~/.xsession-errors, or /var/log/syslog
 ```

**Issue**

**Steps to reproduce**

**Expected behaviour**

**Other information**

**Configuration info, if applicable**
If this bug report is related to an Applet, Desklet or Extension, please paste (or use a pastebin service) the offending extension's settings, if it has any.  You can obtain this by opening its configuration, clicking the 'hamburger' button in the upper-right corner of the window, and selecting "Export to a file". **Please be sure to review the contents and remove any personal data it may contain.**

```

Please paste here

```

**Comment by mfreeman72** [comment]
Odd. It works fine for me. The correct file on my system is logout.ogg (the only one not .oga), which is what it also shows in the sound settings. And if the one you have is incorrect, you can change it by clicking on the filename and selecting the correct file.

**Comment by agentl074** [comment]
Disregard... it works.
