### ISSUE TITLE
Windows effect scale

### ISSUE THREAD

**Issue by barsdeveloper** [linuxmint/cinnamon#10714]
I remember some time ago cinnamon used to offer more effects for windows mapping and closing. One that I am looking for is the scaling, is there any way to bring it back? I want my windows to (fade out and) scale up to 1.2 when they are close, and to scale up also when they are mapped.
![image](https://user-images.githubusercontent.com/84736467/159046633-e1ef2f90-bf52-4856-9e83-766aaa7351fd.png)

**Comment by Secret-chest** [comment]
Also shuffle. I would also like to have separate effects for opening new windows and restoring them.

**Comment by JosephMcc** [comment]
Thanks for the input. The setup was overly complicated before and it was decided to simplify it some. Since this was just recently done, I don't see it coming back anytime soon.
