### ISSUE TITLE
Right-click context menu prevents desktop lock / screen lock / screensaver

### ISSUE THREAD

**Issue by SultanSoft** [linuxmint/cinnamon#10711]
```
 * Cinnamon version (cinnamon --version)
   - Please specify if you are using the daily builds PPA
     (https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds).
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
 * Graphics hardware *and* driver used
 * 32 or 64 bit
 * Attach ~/.xsession-errors, or /var/log/syslog
 ```

**Issue**
Right-click context menu prevents desktop lock / screen lock / screensaver.

To me, this is a security issue.  Right clicking on the desktop (or any icon) brings up the context menu.  If that menu is displayed on the screen, the screen will never lock on timeout.  This is a concern if a user accidentally right-clicks and brings up the context menu before stepping away from their computer.  The timeout will never engage the screen lock and the user session will remain unlocked indefinitely for someone else to have unauthorized access if the screen is not locked manually before stepping away.

+ Cinnamon: v5.2.7
+ Builds: No Daily Builds
+ Distros: Mint 20.3 (Also occurs in 20.2)
+ Graphics:
    - Using virtualbox - VMware SVGA II Adapter
    - GPU: AMD ATI Radeon HD 5000/6000/735 and GPU: AMD ATI Radeon HD 7470/8470 / R
+ 64 bit
+ No logs needed

**Steps to reproduce**
1) (Optional) Set screensaver timeout to 1 minute.
2) Right-Click on cinnamon desktop or any desktop icon and leave the context menu open.
3) Wait for screensaver timeout.  The screen will never lock.

**Expected behaviour**
Screensaver / screen lock timer should always work to lock the screen regardless of a context menu being opened unless the screensaver / screen lock is intentionally disabled.

**Other information**
There may be other context menus that prevent the screensaver from triggering.

**Configuration info, if applicable**
If this bug report is related to an Applet, Desklet or Extension, please paste (or use a pastebin service) the offending extension's settings, if it has any.  You can obtain this by opening its configuration, clicking the 'hamburger' button in the upper-right corner of the window, and selecting "Export to a file". **Please be sure to review the contents and remove any personal data it may contain.**

```

N/A

```

**Comment by JosephMcc** [comment]
This is a very old and well known issue: https://github.com/linuxmint/cinnamon-screensaver/issues/93
