### ISSUE TITLE
AMD Drivers not working / rendering with Blender 3d from fresh install...

### ISSUE THREAD

**Issue by paulvonlux** [linuxmint/cinnamon#10716]
```
 * Cinnamon version (cinnamon --version)
   - Please specify if you are using the daily builds PPA
     (https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds).
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
 * Graphics hardware *and* driver used
 * 32 or 64 bit
 * Attach ~/.xsession-errors, or /var/log/syslog
 ```

**Issue**
AMD Drivers not working! When i want to render in Blender 3d, the setup is not recognised.Hope you can fix it in Linux Mint 21.x,
Also i want to be OUT OF THE BOX READY FOR RENDERING!!! not to do the hassle to install manualy whatever driver, AT LEAST PUT IT IN THE SECTION OF AUTOINSTALL IF WANTED!! Thanks, until then i will stay in Windows...

**Steps to reproduce**
Start to render in blender

**Expected behaviour**
rendering

**Other information**

**Configuration info, if applicable**
If this bug report is related to an Applet, Desklet or Extension, please paste (or use a pastebin service) the offending extension's settings, if it has any.  You can obtain this by opening its configuration, clicking the 'hamburger' button in the upper-right corner of the window, and selecting "Export to a file". **Please be sure to review the contents and remove any personal data it may contain.**

```

Please paste here

```

**Comment by mfreeman72** [comment]
This has nothing to do with the Cinnamon desktop, and should be taken up with either Ubuntu, which is where the drivers are coming from (unless you're using AMD's proprietary drivers, or are using a PPA to get a different version) or with Blender. Either of those can help you more effectively than Cinnamon developers. That said, while I don't have a whole lot of experience with Blender, the little experience I do have says it works fine out of the box on the AMD drivers that come with Mint.
