### ISSUE TITLE
Inexplicable dependencies

### ISSUE THREAD

**Issue by xioren** [linuxmint/cinnamon#10722]
```
 * 5.2.7
 * Debian
 ```

**Issue**
The cinnamon desktop and other pre-installed software have a number of head scratching dependencies that make it such that they cannot be reasonably removed.

examples:
```
xioren@laptop:~$ sudo apt --purge remove firefox-esr 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  chromium chromium-common chromium-sandbox libjsoncpp25 libminizip1 libre2-9
Suggested packages:
  chromium-l10n chromium-shell chromium-driver
The following packages will be REMOVED:
  firefox-esr*
The following NEW packages will be installed:
  chromium chromium-common chromium-sandbox libjsoncpp25 libminizip1 libre2-9
0 upgraded, 6 newly installed, 1 to remove and 0 not upgraded.
Need to get 62.4 MB of archives.
After this operation, 10.0 MB disk space will be freed.
Do you want to continue?
```

You cannot remove Firefox without forcing you to install chromium. ```--no-install-recommends/suggests``` does not bypass this. In fact it turns out cinnamon inexplicably depends on them.

Trying to uninstall the totem media player:
```
xioren@laptop:~$ sudo apt --purge remove totem
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following packages were automatically installed and are no longer required:
  dleyna-server fonts-symbola gir1.2-totem-1.0 gir1.2-totemplparser-1.0 grilo-plugins-0.3
  libdleyna-connector-dbus-1.0-1 libdleyna-core-1.0-5 libdmapsharing-3.0-2 libglu1-mesa libgom-1.0-0
  libgrilo-0.3-0 liboauth0 libtotem-plparser-common libtotem-plparser18 libtotem0
  libtracker-sparql-3.0-0 task-desktop totem-common x11-apps x11-session-utils xinit xorg
Use 'sudo apt autoremove' to remove them.
The following additional packages will be installed:
  fonts-freefont-ttf libaribb24-0 libcddb2 libdouble-conversion3 libdvbpsi10 libebml5 libgles2
  libixml10 liblirc-client0 liblua5.2-0 libmad0 libmatroska7 libmd4c0 libopenmpt-modplug1
  libpcre2-16-0 libplacebo192 libprotobuf-lite23 libproxy-tools libqt5core5a libqt5dbus5 libqt5gui5
  libqt5network5 libqt5svg5 libqt5widgets5 libqt5x11extras5 libresid-builder0c2a libsdl-image1.2
  libsdl1.2debian libsidplay2 libspatialaudio0 libupnp13 libva-wayland2 libvlc-bin libvlc5 libvlccore9
  libvncclient1 libxcb-composite0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-render-util0
  libxcb-xinerama0 libxcb-xinput0 libxcb-xkb1 libxcb-xv0 libxkbcommon-x11-0 qt5-gtk-platformtheme
  qttranslations5-l10n vlc vlc-bin vlc-data vlc-l10n vlc-plugin-access-extra vlc-plugin-base
  vlc-plugin-notify vlc-plugin-qt vlc-plugin-samba vlc-plugin-skins2 vlc-plugin-video-output
  vlc-plugin-video-splitter vlc-plugin-visualization
Suggested packages:
  lirc qt5-image-formats-plugins qtwayland5 vlc-plugin-fluidsynth vlc-plugin-jack vlc-plugin-svg
  libdvdcss2
The following packages will be REMOVED:
  cinnamon-desktop-environment* task-cinnamon-desktop* totem* totem-plugins*
The following NEW packages will be installed:
  fonts-freefont-ttf libaribb24-0 libcddb2 libdouble-conversion3 libdvbpsi10 libebml5 libgles2
  libixml10 liblirc-client0 liblua5.2-0 libmad0 libmatroska7 libmd4c0 libopenmpt-modplug1
  libpcre2-16-0 libplacebo192 libprotobuf-lite23 libproxy-tools libqt5core5a libqt5dbus5 libqt5gui5
  libqt5network5 libqt5svg5 libqt5widgets5 libqt5x11extras5 libresid-builder0c2a libsdl-image1.2
  libsdl1.2debian libsidplay2 libspatialaudio0 libupnp13 libva-wayland2 libvlc-bin libvlc5 libvlccore9
  libvncclient1 libxcb-composite0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-render-util0
  libxcb-xinerama0 libxcb-xinput0 libxcb-xkb1 libxcb-xv0 libxkbcommon-x11-0 qt5-gtk-platformtheme
  qttranslations5-l10n vlc vlc-bin vlc-data vlc-l10n vlc-plugin-access-extra vlc-plugin-base
  vlc-plugin-notify vlc-plugin-qt vlc-plugin-samba vlc-plugin-skins2 vlc-plugin-video-output
  vlc-plugin-video-splitter vlc-plugin-visualization
0 upgraded, 61 newly installed, 4 to remove and 0 not upgraded.
Need to get 30.9 MB of archives.
After this operation, 128 MB of additional disk space will be used.
Do you want to continue? [Y/n]
```

WHAT!?
I cannot remove totem.....a media player....without uninstalling cinnamon and installing 128mb of bloat including/related to vlc. These are just two examples. There a a number of pre-installed software that cannot be removed without also removing essential things like cinnamon and x11 and/or install other unwanted software when you remove them, like with Firefox. This is not okay. There HAS to be a better way.

**Comment by mtwebster** [comment]
Which Debian is this?

It looks as though the metapackage Debian uses for cinnamon is requiring certain packages (or alternatives):
![image](https://user-images.githubusercontent.com/262776/159995839-1e4824af-9201-4672-85f3-c15130234f42.png)

@Fantu @ItzSwirlz

**Comment by xioren** [comment]
Debian testing

**Comment by Fantu** [comment]
@xioren cinnamon-desktop-environment is for full feature desktop, if you want a minimal instead you should install only cinnamon-core instead
if there are deps causing issue also without it or you want request add of other alternatives open a bug in debian cinnamon-desktop-environment package

**Comment by xioren** [comment]
If you are saying the dependencies are chosen by the Debian team, not the cinnamon devs then ill see about opening an issue there. However this has nothing to do with wanting a minimal or fully featured DE.

**Comment by Fantu** [comment]
was done by me and other maintainer over the years but similarly to other DEs
anyway as wrote is it is possible in a simple and fast way to have very minimal systems (like cinnamon-core without recommended or even just cinnamon without recommended) as some users have and when there were unexpected events they reported and we solved

**Comment by xioren** [comment]
I'm not looking for a "minimal" desktop environment, I just want to swap certain default programs with the ones I like. E.g. I use mpv, not totem and Brave not Firefox. As it stands I cannot remove Firefox without Chromium being installed and I cannot remove Totem without VLC getting installed. Maybe I am misunderstanding what you are suggesting, but there doesn't seem to be a reasonable solution.

Are you suggesting I just start with no Desktop Environment and then install cinnamon piecemeal?

**Comment by Fantu** [comment]
@xioren thanks for for the explanation, when I have time I will look at the metapackages of the other DEs and see if it is worth moving browsers and media players to the recommended ones, if you have missing alternatives to propose also that those will be added instead almost certainly (as long as they are present in the repository and not in non-free)

**Comment by ItzSwirlz** [comment]
Yeah. Cinnamon-desktop-environment contains everything. It would be a simple amendment to the control file. But they do have to be free iirc

**Comment by smurphos** [comment]
The weird browser dependencies come from libreoffice-help-en-us of all things...

steve@lmde5:~$ apt depends libreoffice-help-en-us
libreoffice-help-en-us
  Depends: libreoffice-common
  Depends: <libreoffice-l10n-en-us>
    libreoffice-common
  Depends: libreoffice-help-common
 |Depends: firefox-esr
 |Depends: epiphany-browser
 |Depends: konqueror
 |Depends: chromium
  Depends: firefox
  Recommends: libreoffice-core
  Replaces: libreoffice-help-common
