### ISSUE TITLE
Reporting kernel regressions

### ISSUE THREAD

**Issue by surruk51** [linuxmint/cinnamon#10723]
```
 * Cinnamon version (cinnamon --version)
 * 5.27
   - Please specify if you are using the daily builds PPA
   no
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
 * Mint 20.3
 * Graphics hardware *and* driver used
 * intel 8a56
 * 32 or 64 bit
 * 64 bit
 * Attach ~/.xsession-errors, or /var/log/syslog
 * not relevant
 ```

**Issue**
If you go to the Linux Kernel teams bug tracker they say to report it to the distro. But there is no section on this bug tracker specific to kernel issues.

**Steps to reproduce**

**Expected behaviour**

**Other information**

**Configuration info, if applicable**
If this bug report is related to an Applet, Desklet or Extension, please paste (or use a pastebin service) the offending extension's settings, if it has any.  You can obtain this by opening its configuration, clicking the 'hamburger' button in the upper-right corner of the window, and selecting "Export to a file". **Please be sure to review the contents and remove any personal data it may contain.**

```

Please paste here

```

**Comment by leigh123linux** [comment]
Report your kernel issue to Ubuntu bug tracker.
