### ISSUE TITLE
menu applet: ordering bug

### ISSUE THREAD

**Issue by Secret-chest** [linuxmint/cinnamon#10736]
```
 * Cinnamon version (cinnamon --version)
   - Please specify if you are using the daily builds PPA
     (https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds).
5.2.7, no
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
Mint 20.3
 * Graphics hardware *and* driver used
Intel UHD Graphics 620, Mesa
 * 32 or 64 bit
64-bit
 * Attach ~/.xsession-errors, or /var/log/syslog
--
 ```

**Issue**

In the menu applet, the list of applications is ordered alphabetically. When the language is set to Romanian or any other language with accents / diacritics, if there are any apps whose names begin with a diacritic letter, they are listed at the bottom.

**Steps to reproduce**

1. Get a .desktop file whose name begins with a diacritic letter 
2. Open the menu
3. It is listed at the bottom

**Expected behaviour**

The entries should be listed below the entries with the letter the diacritic letter was derived from. (For example: "Synaptic - administrator de pachete" is the last application with a S in my menu. "Șah" should be listed below it.)

**Other information**

**Configuration info, if applicable**

**Comment by mtwebster** [comment]
This is a bit of a challenge..

Sorting happens in a couple of different places - it's different for initial app listing and categories than it is for searches (I didn't catch this a while back when improving search behavior).

You mentioned Șah should be after Synaptic. I tested the category sort using String.localeCompare and it sorts like a normal S:
![image](https://user-images.githubusercontent.com/262776/162797536-f15df472-b627-416b-a940-ed73c72e4b17.png)

Would this be a better result?

I'd need to rework the search mechanism also - sah should match Șah I think, and this should apply to all components of our search strings (keywords, etc...).

**Comment by Secret-chest** [comment]
> I did a PR to test this a bit: https://github.com/linuxmint/cinnamon/pull/10738
> 
> It orders things like I mentioned above, I'm not keen on trying to force these entries to the bottom of a given letter.

It's fine. As long as they are close, it's OK. Thank you.
