### ISSUE TITLE
Adwaita icon theme: category icons missing since update to v42

### ISSUE THREAD

**Issue by herbstschweigen** [linuxmint/cinnamon#10742]
```
 * Cinnamon version (cinnamon --version) - 5.2.7
   - Please specify if you are using the daily builds PPA - no
 * Distribution - Arch
 * Graphics hardware *and* driver used - NVIDIA Corporation GM107M [GeForce GTX 850M], nvidia driver
 * 32 or 64 bit - 64
 * Attach ~/.xsession-errors, or /var/log/syslog
```
[20220412.xsession-errors.txt](https://github.com/linuxmint/cinnamon/files/8476155/20220412.xsession-errors.txt)
 

**Issue**
I was using Cinnamon with the Adwaita icon theme. With the recent update of package adwaita-icon-theme 42.0.1, many category icons disappeared from the panel menu.  Also, some buttons on AisleRiot solitaire have a broken image link.

**Steps to reproduce**
- System settings - Themes - Icons - select Adwaita
- restart Cinnamon
- open panel menu, some of the category icons are gone, e.g. for Office, Development, Internet
- same when opening menu editor
- AisleRiot solitaire game buttons display as broken images
- when selecting another icon theme, e.g. Mate, icons and buttons are back

![Adwaita-missing-icons](https://user-images.githubusercontent.com/61930179/163045141-0065ca73-9e82-41e1-8bc9-048b0c1ceca3.png)
![Mate-working-icons](https://user-images.githubusercontent.com/61930179/163045148-8db49afd-c8b7-45bf-800d-4bf04e202051.png)

**Expected behaviour**
Adwaita icon theme provides all icons, ust like other icon themes

**Other information**

**Configuration info, if applicable**
If this bug report is related to an Applet, Desklet or Extension, please paste (or use a pastebin service) the offending extension's settings, if it has any.  You can obtain this by opening its configuration, clicking the 'hamburger' button in the upper-right corner of the window, and selecting "Export to a file". **Please be sure to review the contents and remove any personal data it may contain.**

```

Please paste here

```

**Comment by mtwebster** [comment]
Looks like it's already reported for your distro:
https://bugs.archlinux.org/task/74350

There isn't anything we can do here, use a different theme for now I guess.

**Comment by herbstschweigen** [comment]
ah ok, thanks. Hadn't seen that.
