### ISSUE TITLE
[Feature request] avif thumbnail support in Nemo

### ISSUE THREAD

**Issue by Mr-Bajs** [linuxmint/cinnamon#10746]
Would be nice if the file manager supported thumbnails for .avif files.

avif and i suppose jpeg XL, are the next gen. image files. Not super important but it's sort of slight annoying not having thumbnails of you pictures in your picture folders and the .avif files doesn't show thumbnails.

**Comment by leigh123linux** [comment]
It's already supported, you need to install the heif thumbnailer.

https://packages.ubuntu.com/focal/heif-thumbnailer
