### ISSUE TITLE
Suggestion: Change default icon size

### ISSUE THREAD

**Issue by luisrguerra** [linuxmint/cinnamon#10749]
Could you please consider changing the default icon size in cinnamon from 22x22 to 24x24?  I'm a developer of icon themes for Linux and I for example had to redo all the icons in my theme in 22x22 resolution only because of Linux Mint while on other systems there was no need.  The 22x22 resolution is rarely used and if the system uses an icon in 24x24 resolution and resizes it to 22x22 it loses a lot of detail and gets blurred.  An icon to be sharp at low resolutions needs to be redone aligned with the pixels grid, this is mostly needed with straight lines.  When I have time, I'll send you a picture showing the problem.

**Comment by luisrguerra** [comment]
> Could you please consider changing the default icon size in cinnamon from 22x22 to 24x24?  I'm a developer of icon themes for Linux and I for example had to redo all the icons in my theme in 22x22 resolution only because of Linux Mint while on other systems there was no need.  The 22x22 resolution is rarely used and if the system uses an icon in 24x24 resolution and resizes it to 22x22 it loses a lot of detail and gets blurred.  An icon to be sharp at low resolutions needs to be redone aligned with the pixels grid, this is mostly needed with straight lines.  When I have time, I'll send you a picture showing the problem.

**Comment by JosephMcc** [comment]
Thanks for the feedback. If you're taking about the panel, these are often sized depending on the panel size and the user is able to manually change that size. By default I don't think any of them are set to 22px.  We'll keep this in mind when we look at this stuff.

**Comment by luisrguerra** [comment]
> If you're taking about the panel, these are often sized depending on the panel size

I'm talking about the application menu ("start menu"), not the panel at bottom with the multitask window selector
