### ISSUE TITLE
Intel net adapter 2500gb not worked in the box! 

### ISSUE THREAD

**Issue by BARUCHER777** [linuxmint/cinnamon#10759]
```
 * Cinnamon version (cinnamon --version)
   - Please specify if you are using the daily builds PPA
     (https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds).
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
 * Graphics hardware *and* driver used
 * 32 or 64 bit
 * Attach ~/.xsession-errors, or /var/log/syslog
 ```
Drivers and programs are all standard, I haven’t updated or downloaded anything yet, since I don’t need Wi-Fi, I need to use a wired connection (ETNERNET)
![setevaya karta!](https://user-images.githubusercontent.com/18327150/165445852-1d49c612-51a3-45a5-99ee-a75385e4ae58.jpg)

**Issue**
Unfortunately, the network card from Intel does not work - namely, but the Wi-Fi network card works right after the system is installed! Tell me what to do!?

**Other information**

OS installed on ssd adata 580 gb sata 3
Killer E3100G 2.5 Gigabit Ethernet 

**Configuration info, if applicable**
If this bug report is related to an Applet, Desklet or Extension, please paste (or use a pastebin service) the offending extension's settings, if it has any.  You can obtain this by opening its configuration, clicking the 'hamburger' button in the upper-right corner of the window, and selecting "Export to a file". **Please be sure to review the contents and remove any personal data it may contain.**

```
Using cinnamon shell, system version 20.3 64-bit
```
Unfortunately, the network card from Intel does not work - namely, but the Wi-Fi network card works right after the system is installed! Tell me what to do!?

**Comment by leigh123linux** [comment]
File your issue against the kernel.

**Comment by BARUCHER777** [comment]
> File your issue against the kernel.

I am not an experienced Linux user, I don’t know and don’t understand many things yet, if it doesn’t make it difficult for you, write here a link to the resource to which you need to report this problem with the network card!

**Comment by leigh123linux** [comment]
Try using a newer kernel, see

https://forums.linuxmint.com/viewtopic.php?t=363689
