### ISSUE TITLE
Display Resolution Feature Request

### ISSUE THREAD

**Issue by agentl074** [linuxmint/cinnamon#10756]
Linux Mint 20.3 
Asus M712U 17" laptop

Hello, I would like to have an option to set the display to 1600x900 on Linux Mint 20.3 for 17" laptop displays. 1366x768 is perfect for 15.6" displays,  so the comparable 1600x900 for 17" screens would fit nicely! Thanks!

**Comment by leigh123linux** [comment]
This is a hardware issue not software.
