### ISSUE TITLE
Update Manager says system is up to date when network isn't available

### ISSUE THREAD

**Issue by SB-London** [linuxmint/cinnamon#10753]
```
 * Cinnamon version (cinnamon --version) - **5.0.7**
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) **Mint 20.2 Uma**
 * Graphics hardware *and* driver used: **Intel Xeon E3-1200 Core Proc Integrated Graphics, i915**
 * 32 or 64 bit - **64 bit**
 * Attach ~/.xsession-errors, or /var/log/syslog - **Not applicable**
 ```

**Issue**
When you check for updates in the update manager and system network is down or Internet not available, update manager says system is up to date when in fact there could be updates that it could not check. It should state that it could not check for updates instead. 

**Steps to reproduce**
- Ensure no internet connectivity
- Launch Update Manager
- Check for updates

**Expected behaviour**

Update Manager should say: "Unable to to check for update, please check network connection and try again"

**Other information**
N/A

**Configuration info, if applicable**
If this bug report is related to an Applet, Desklet or Extension, please paste (or use a pastebin service) the offending extension's settings, if it has any.  You can obtain this by opening its configuration, clicking the 'hamburger' button in the upper-right corner of the window, and selecting "Export to a file". **Please be sure to review the contents and remove any personal data it may contain.**

N/A

Please paste here

```

**Comment by JosephMcc** [comment]
Here when I check for updates with no internet connection, I get a box telling me it can't retrieve the repository indexes. That seems like a proper warning. I'm closing this since an issue for `mintupdate` not Cinnamon.
