### ISSUE TITLE
(Customizable) Icons for .deb or portable apps when linked to Desktop via shortcut or symlink

### ISSUE THREAD

**Issue by ThiloteE** [linuxmint/cinnamon#10769]
```
 * Linux Mint 20.3 Cinnamon
   - no daily build
 * Cinnamon version 5.2.7
 * Intel Corporation Atom Processor Z36xxx/Z37xxx Series Graphics & Display
 * 64 bit
 ```

**Issue**

Sometimes I have to use .deb packages or portable versions of applications (because the snap/flathub version of the program fails to offer certain features I require). There will be no icon, if I create a shortcut to these apps.

**Steps to reproduce**

1. Have .deb or portable app
2. Create shortcut/symlink to the program so that I can start the program from Desktop
3. The shortcut will not show the icon as offered by the app.

Example screenshot:
![shortcuts without icons](https://user-images.githubusercontent.com/73715071/166439057-f7180ac5-a7f0-46c8-b1fb-a395313367e4.jpg)

**Expected behaviour**

- Either automatically show the icon as specified in the directory of the app
- or let users customize the icon

**Other information**

- example for [JabRef](https://www.jabref.org/): I can start the portable version of JabRef via a file which is in the folder `JabRef/lib/runtime/bin`. The JabRef.png icon can be found in the folder `JabRef/lib`, though. I guess the difficult part would be for cinnamon to know where the directory for the app starts and where exactly the icon would be located. If an automatic solution is not possible, a workaround that lets users customize the icon would be nice.

I hope I posted this at the right place.

**Comment by ThiloteE** [comment]
Related to #10731

**Comment by smurphos** [comment]
You can customise symlink icons. Right click the symlink > Properties > click on the existing icon on the top left of the properties dialogue to open the icon picker dialogue. If the needed icon isn't in your current icon theme use the browse functionality to find your application icon.

**Comment by smurphos** [comment]
Alternatively rather than symlinks use the Create Launcher function to make a desktop launcher - you can pick an icon in the same way during launcher creation. This has the advantage of offering to integrate the launcher into the menu system which will also result in proper integration of you app with the Grouped Window List.

**Comment by ThiloteE** [comment]
Thank you! I feel foolish. Found what you describe in https://github.com/linuxmint/cinnamon/issues/10769#issuecomment-1116031741. Did not expect clicking on that symbol would allow me to choose. Thanks!

Where exactly can I find the "create launcher" function?

**Comment by ThiloteE** [comment]
Never mind, I found it with help of https://www.xmodulo.com/create-desktop-shortcut-launcher-linux.html

closing this.
