### ISSUE TITLE
Create Shortcut to file or folder from right-click menu

### ISSUE THREAD

**Issue by ThiloteE** [linuxmint/cinnamon#10770]
```
 * Linux Mint 20.3 Cinnamon
   - no daily build
 * Cinnamon version 5.2.7
 * Intel Corporation Atom Processor Z36xxx/Z37xxx Series Graphics & Display
 * 64 bit
 ```

**Issue**

Ease workflow by offering to create shortcuts from right-click menu when clicking on files or folders.
Currently, shortcuts are very hidden. One can create them from the "edit" menu (I think it is that. Sorry, in German language the menu is called "bearbeiten") or via `CTRL+M`

**Comment by mtwebster** [comment]
Preferences->Context Menus->Selection, check "Make Link".  It should then appear in your right-click menu.
![image](https://user-images.githubusercontent.com/262776/166447913-f710c819-df65-4151-8667-edd4b7895d3b.png)


You can also create them using ctrl-shift-drag (look for the cursor changing to have a chain symbol).

**Comment by ThiloteE** [comment]
Thanks!

I think this is something that should be considered to be enabled by default.

Closing this issue, as you were able to solve it for me personally. Thanks again!
