### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by agentl074** [linuxmint/cinnamon#10771]
Linux Mint 20.3 Cinnamon 

I would like the Cinnamon wireless network icon to also show an ! next to the wifi bars in order to indicate that the wifi is connected, but the Internet connection is down. An example of this would be how the wifi icon on smartphones work. Thank you!

**Comment by Secret-chest** [comment]
Maybe it could use the `offlime-symbolic` icon?

**Comment by agentl074** [comment]
Yeah, that would work.
