### ISSUE TITLE
Cinnamon Feature Request -- Mint 21

### ISSUE THREAD

**Issue by agentl074** [linuxmint/cinnamon#10785]
Mint 21 Feature Request

After looking at Ubuntu 22, I think it would be nice to have an integrated blue light filter rather than Redshift. Something that allows you to filter blue light in the daytime as well as night time -- with adjustable filtering. 

If this is already in the works, please disregard. 

Thank you for all of your hard work!

**Comment by JosephMcc** [comment]
A search will show this had been brought up a number of times.
