### ISSUE TITLE
stat command fails for files in $PATH - unless an absolute path is given

### ISSUE THREAD

**Issue by Jeremy7701** [linuxmint/cinnamon#10781]
```
 * Cinnamon version 5.2.7
   - Please specify if you are using the daily builds PPA
     (https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds).
 * Distribution - (LMDE5)
 * Graphics hardware *and* driver used
 * 32 or 64 bit
 * Attach ~/.xsession-errors, or /var/log/syslog
 ```

**Issue**
Example:-
`stat apt`
stat: cannot **statx** 'apt': No such file or directory

`stat /usr/local/bin/apt`
  File: /usr/local/bin/apt
  Size: 7692      	Blocks: 16         IO Block: 4096   regular file
Device: 10302h/66306d	Inode: 1195619     Links: 1
Access: (0755/-rwxr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2022-05-06 22:32:48.794265932 +0100
Modify: 2021-11-22 13:19:37.000000000 +0000
Change: 2022-05-05 14:43:35.764328975 +0100
 Birth: 2022-05-05 14:43:35.756328982 +0100

**Steps to reproduce**

Choose any file in your path and run `stat` with just the name.
This appears to cause it to run `statx` - which doesn't appear to use $PATH 

**Expected behaviour**

statx should work in the same way as stat, or if it cannot then stat-style output should be returned.

**Other information**
stat --version
stat (GNU coreutils) 8.32

**Configuration info, if applicable**
N/A

**Comment by smurphos** [comment]
Why do you think this is a Cinnamon issue?

`stat apt` also fails on 20.3 (version 8.30) because stat isn't $PATH aware.

About the statx mentioned in the output on 8.32 - https://github.com/coreutils/coreutils/commit/6cc35de16fdc52d417602b66d5e90694d7e02994

You can always do `stat $(which apt)`

**Comment by Jeremy7701** [comment]
Didn't really know where to report this strange behaviour.
