### ISSUE TITLE
We're not asking users to configure things, we're letting them

### ISSUE THREAD

**Issue by Secret-chest** [linuxmint/cinnamon#10799]
_No offence, Clem and all other contributors. I still love Linux Mint. It's the best OS in the world. Just close this if you so desire._

I recently saw some discussions, in the volume step issues and PRs, with Clem saying we're not "going that far" and that we're "asking" users to configure it.

This: (text boldened, snipped by me)
<details>
<summary>

Clem in https://github.com/linuxmint/cinnamon/pull/8884#issuecomment-553994539

</summary>

> Hi @deskwizard,
> 
> ✂️
> 
> **I think it's overkill**. We're looking at an arbitrary value which isn't significant. The amount of increment we get on our media knob.. **we're not going to go as far as asking the user to tune that.** The 5% value is arbitrary. We can debate its value and that would be tuning. **Asking users to tune that themselves is going way too far.**
> 
> We're removing similar features elsewhere in Cinnamon, for instance asking the user to fine tune the number of millisecond a particular animation effect takes.
> 
> ✂️
> 

</details>

I understand the codebase mess idea, but it's just a new setting. You're not GNOME.

### Please reconsider. We're not asking them. We're letting them configure it, **_if they want, when they want._**

**Comment by cassepipe** [comment]
It seems like you want to make a philosophical point but I think it is one everybody here agrees on just because it is aligned to Mint's philosophy, or at least practice so far.
Clem's comment just questioned if that was a feature that may be desired by other persons for reasons he may not know. To which it was replied that probably not.
So the very question was whether it was really a feature I guess.
**It seems like drama over _nothing_.** (How did you manage to manage to have bigger text by the way ?)

This is not a forum, it is a place to provide important feedback to make LM better. I think it would be more respectful from you to close this issue so the devs can concentrate on making that distribution we both love.

**Comment by Secret-chest** [comment]
> It seems like you want to make a philosophical point but I think it is one everybody here agrees on just because it is aligned to Mint's philosophy, or at least practice so far.
> Clem's comment just questioned if that was a feature that may be desired by other persons for reasons he may not know. To which it was replied that probably not.
> So the very question was whether it was really a feature I guess.
> **It seems like drama over _nothing_.** (How did you manage to manage to have bigger text by the way ?)
> 
> This is not a forum, it is a place to provide important feedback to make LM better. I think it would be more respectful from you to close this issue so the devs can concentrate on making that distribution we both love. 

The _removal_ of animations, though... Clem  said we're "asking" users to configute them...

**Comment by Secret-chest** [comment]
> How did you manage to manage to have bigger text by the way ?
heading 4

**Comment by JosephMcc** [comment]
I'm going to close this but I'll try to offer some thoughts on it first.

> but it's just a new setting

Do you realize how many time we've heard those exact words? It's what everyone says when we don't implement the particular thing they want. But it's not just a setting. Everything you add has a cost. Not in money but in other ways. Implementation, testing, potential new bugs, UI complexity, code complexity. And every setting you have makes it that much more difficult to implement the next thing or rework and improve things under the hood. Sure your one thing might just be one little thing. But what about all the other things everyone asks for?

We typically only add new settings if we feel there is enough use case for it. Does it add a real benefit to a majority of users? Is there some specific thing that we are working around? Like how things behave under specific hardware or maybe some behavior of X11? And obviously some people are going to disagree with those choices. But that's the case pretty much no matter what decision you make. In the end it's about doing what works best for the majority of users and is manageable on our side.

**Comment by Secret-chest** [comment]
I agree. We shouldn't add things like changing the exact panel colour icon size.

But the volume step example? Here we can't satisfy everyone. If we would change it to 2, those with small speakers would get annoyed. If we leave it 5, those who need finer tuning would have to go to sound settings. I would personally leave it 4.

**Comment by Secret-chest** [comment]
> We typically only add new settings if we feel there is enough use case for it.

That's fine, but please don't break users' setups and don't remove settings without a technical reason. (I understand why the window control theme setting is gone)

**Comment by jelabarre59** [comment]
The Window Control theme setting is gone because the GNOME folks **_broke_** it in GTK+, most likely intentionally.

**Comment by JosephMcc** [comment]
> The Window Control theme setting is gone because the GNOME folks broke it in GTK+, most likely intentionally.

@jelabarre59 This is just total nonsense. It has no real place here. The decision to remove that setting was made by the Mint developers. It was talked about for a long time and imho was the right decision.

**Comment by jelabarre59** [comment]
Well, a bad decision there too.

But as far as I've been able to find, GTK can't even configure OR even recognize TitleBars anymore.  So it's broken as far as I'm concerned.  So GTK is kbroken, KDE is ugly and clunky, I'd be better off going back to CDE.

**Comment by Secret-chest** [comment]
> > The Window Control theme setting is gone because the GNOME folks broke it in GTK+, most likely intentionally.
> 
> @jelabarre59 This is just total nonsense. It has no real place here. The decision to remove that setting was made by the Mint developers. It was talked about for a long time and imho was the right decision.

It was already inconsistent. Now all apps use titlebars but the empty ones are thinner.

**Comment by AtomicRobotMan0101** [comment]
Is there a way to pull ALL the configs/settings/constants/variables into one huge file?

There must be a million little things spread all over the places.

e.g. /usr/share/cinnamon/applets/sound@cinnamon.org/applet.js has a few CONSTS on line 36 and 38.

These are a bit hard to find.

Has there, or is there, a project that looks for all these master settings and pulls them all into one place?
