### ISSUE TITLE
Setting up startup sounds doesn't work

### ISSUE THREAD

**Issue by rado84-github** [linuxmint/cinnamon#10807]
```
 * Cinnamon version: 5.2.7
 * Arch (LTS kernel, if it matters)
 * Graphics hardware *and* driver used 510.54, GTX 1660 Ti
 * 64 bit
 ```

**Issue**
Adding a startup sound (Starting Cinnamon, in my case) doesn't work. The sound doesn't get played at startup and also pressing the play button to hear the sound doesnt' do anything either.

**Steps to reproduce**
1. Open "Sounds" and select any desired sound file to set it up as a startup sound. Also set sound volume for the desired startup file.
2. Press the "play" button next to it in order to hear it. Notice that no sound is being played.
3. Reboot the computer and notice the sound doesn't get played at starup.

**Expected behaviour**
A startup sound should be played and perfectly audible.
Pressing the "play" button next to that sound should play it.

**Other information**
I noticed that the file selector window lists only wav files, so I chose a wav file. The wav file is perfectly fine because I use as a ringtone on my smartphone and just for the test (to make sure it's fine) I tested it as a startup sound for Windows 10 - it plays just fine in Windows 10, so whatever is wrong here, it's in Cinnamon. 

![Picture_created_26-05-2022_19-34-14](https://user-images.githubusercontent.com/41172201/170534284-bb4ca114-0a38-4bb2-b4b6-f3ab29b4ea1b.png)

![Picture_created_26-05-2022_19-41-16](https://user-images.githubusercontent.com/41172201/170534288-cbb8302a-72e9-4652-a14a-b5969e5666f2.png)

**Comment by smurphos** [comment]
Can you attach the sound file itself (maybe in a ZIP) to test

I've got no problem playing ogg or oga sounds, and just tested a random wav download and that's also fine. - this is on Mint with Cinnamon 5.2.7. Does your file play elsewhere nemo-preview, meda players etc?

`steve@steve-Inspiron-5580:~$ file "/home/steve/Downloads/Random/Imperial March60.wav"
/home/steve/Downloads/Random/Imperial March60.wav: RIFF (little-endian) data, WAVE audio, Microsoft PCM, 16 bit, mono 22050 Hz
`

**Comment by rado84-github** [comment]
Yes, it plays everywhere else - media players, my phone (I'm usin' it as a ringtone), even Firefox somehow managed to play it locally.

This is the wav file:
Crisis on Infinite Earths.7z
https://www67.zippyshare.com/v/PeOjFTt9/file.html

This is a recorded video for you to see it's not working:
simplescreenrecorder-2022-05-27_17.04.37.mkv
https://www67.zippyshare.com/v/62yuMpyw/file.html

**Comment by smurphos** [comment]
OK thanks - so that file doesn't work for me either - previews OK with nemo-preview, plays ok in MPV, interestingly neither wav produce any sound in Celluloid.

Comparison between one non-working and one working wav file -

```
steve@steve-Inspiron-5580:~$ mediainfo '/home/steve/Downloads/Random/Supergirl - Crisis on Infinite Earths.wav'
General
Complete name                            : /home/steve/Downloads/Random/Supergirl - Crisis on Infinite Earths.wav
Format                                   : Wave
File size                                : 2.70 MiB
Duration                                 : 9 s 833 ms
Overall bit rate mode                    : Constant
Overall bit rate                         : 2 304 kb/s
Track name                               : Crisis on Infinite Earths
Performer                                : Supergirl
Director                                 : Supergirl

Audio
Format                                   : PCM
Format settings                          : Little / Signed
Codec ID                                 : 00000001-0000-0010-8000-00AA00389B71
Duration                                 : 9 s 833 ms
Bit rate mode                            : Constant
Bit rate                                 : 2 304 kb/s
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 48.0 kHz
Bit depth                                : 24 bits
Stream size                              : 2.70 MiB (100%)


steve@steve-Inspiron-5580:~$ mediainfo '/home/steve/Downloads/Random/Imperial March60.wav'
General
Complete name                            : /home/steve/Downloads/Random/Imperial March60.wav
Format                                   : Wave
File size                                : 2.52 MiB
Duration                                 : 1 min 0 s
Overall bit rate mode                    : Constant
Overall bit rate                         : 353 kb/s

Audio
Format                                   : PCM
Format settings                          : Little / Signed
Codec ID                                 : 1
Duration                                 : 1 min 0 s
Bit rate mode                            : Constant
Bit rate                                 : 352.8 kb/s
Channel(s)                               : 1 channel
Sampling rate                            : 22.05 kHz
Bit depth                                : 16 bits
Stream size                              : 2.52 MiB (100%)
```

**Comment by leigh123linux** [comment]
It works ok if it's converted to vorbis

```
ffmpeg -i 'Supergirl - Crisis on Infinite Earths.wav' -codec:a libvorbis  'Supergirl - Crisis on Infinite Earths.oga'
```
[Supergirl - Crisis on Infinite Earths.oga.zip](https://github.com/linuxmint/cinnamon/files/8787940/Supergirl.-.Crisis.on.Infinite.Earths.oga.zip)

**Comment by rado84-github** [comment]
I don't wanna degrade it by converting it to a lesser format.

I didn't know mediainfo could work in terminal. Seeing smurphos last post, that gave me an idea what might be wrong and now I know for sure, after converting it to 16-bit using Audacity: Cinnamon doesn't support anything higher than 16-bit PCM WAV.
