### ISSUE TITLE
Increase the size of titlebar buttons (minimize, maximize, close)

### ISSUE THREAD

**Issue by TerrorSquad** [linuxmint/cinnamon#10814]
```
 * Cinnamon version - 5.2.7
 * Not using the daily builds PPA
 * Distribution - Linux Mint 20.3
 * Graphics hardware *and* driver used - RTX 3070 - nvidia-driver-510
 * 32 or 64 bit - 64bit
 * Attach ~/.xsession-errors, or /var/log/syslog - N/A
 ```

**Issue**
I'm using Linux Mint 20.3 Cinnamon on a 27" monitor with 1440p resolution. During the day I need to manage lots of opened windows - move them around, open/close, minimize, maximize and a big part of that workflow are the min,max,close buttons in the top right corner of the window.
The buttons are simply too small. I've wasted a lot of time hunting the darn buttons and moving the cursor ever so slightly closer to the button in order for it to become clickable.
I've tried OOTB themes as well as some themes I've found online. All of them suffer from the same issue - the buttons are too small.
I tried increasing the title bar font size as well as resolution scaling, but it didn't really help.

**Steps to reproduce**
Use any theme that's available out of the box, or even themes that you can download from the Internet

**Expected behaviour**
Titlebar buttons (minimize, maximize, close) are either bigger or can be scaled to a certain size.

**Other information**
In the end, I got so frustrated by this issue, that I installed Kubuntu 22.04 as my daily driver, and set the button size to Oversized. Now I can click on any of the aforementioned buttons with ease.
I would like to return back to Linux Mint because I like the simplicity of it. I've been a LM user since 2014. and this is the first time I faced an issue so big that I had to switch to another distro.

**Comment by Secret-chest** [comment]
I think it will be easier when we switch to GTK+ titlebars. These can be themed with ease.

**Comment by TerrorSquad** [comment]
Is there an ETA on when is that going to happen? Will those titlebars come with the option of choosing the size for the buttons, similar to KDE?

**Comment by JosephMcc** [comment]
There are currently no plans to allow changing the size with some sort of GUI option. The way theming works in gtk I'm not sure how doable that would even be without having tried it.

**Comment by TerrorSquad** [comment]
This repo contains some themes that come with a script to change the size of the title bar buttons:
https://github.com/smurphos/cinnamox_themes

I think it's worth checking it out. Perhaps some code or at least ideas can be used to implement this feature natively.

**Comment by JosephMcc** [comment]
I think this was answered.
