### ISSUE TITLE
Cinnamon 5.4 - Alt-F2 dialog issues

### ISSUE THREAD

**Issue by vladimir-didenko** [linuxmint/cinnamon#10829]
```
 * Cinnamon version - 5.4.0-2-gdb2866ec3
 * Distribution - Alt Linux Sisyphus
 * Graphics hardware *and* driver used - nvidia proprietary
 * 64 bit
 ```

**Issue**
In Cinnamon 5.4 I  have found several issues with Alt-F2 dialog
1. If you increase font size from the default to something bigger (e.g. 11 -> 13) then input field in dialog is not properly aligned see below
![Screenshot from 2022-06-12 13-18-58](https://user-images.githubusercontent.com/1499142/173228699-af34a3b3-79cd-4b8d-ad3f-3901e725723b.png)

2. Some tray icon (e.g. parcellite) are now shadowed - see below

![Screenshot from 2022-06-12 13-22-21](https://user-images.githubusercontent.com/1499142/173228784-6bfa1437-e057-4e1a-a50a-79bd89b2fdc7.png)

**Steps to reproduce**
1. For the first issue just increase font size to > 11pt in cinnamon settings and run Alt-F2
2. For the second issue - start parcellite application and just run Alt-F2

**Comment by vladimir-didenko** [comment]
It looks like the second issue it is not even Alt-F2 issue. Parcellite icon is shown even in full-screen applications. Probably, it makes sense to create a separate issue for this issue.

**Comment by JosephMcc** [comment]
Was able to easily reproduce the issue with the run dialog.
