### ISSUE TITLE
Applications bar settings like "Always on Top" are not kept after closing

### ISSUE THREAD

**Issue by SkyKwas** [linuxmint/cinnamon#10821]
```
 * Cinnamon version 5.2.7
   - Please specify if you are using the daily builds PPA: No
 * Distribution - Mint 20.3
 * 64 bit
 
**Issue**
I'm trying to have "System Monitor" be "Always on Top" and "Always on Visible Workspace" when I open it. This is in case a fullscreen application crashes and I need to force close it.

After I make these changes (by right-clicking the top application bar) and close "System Monitor", the settings are reverted to the defaults.

This happens on all applications.

**Comment by smurphos** [comment]
That's because these are window attributes, not application attributes. If you want to automate this you can do things like amend your launcher for an app to run a start-up script to launch your app window with a specific CLASS and use wmctrl to apply window attributes to the newly created window.

**Comment by JosephMcc** [comment]
I'm going to close this for now. Implementing this is really out of the scope of what we want to do. This starts to fall under session saving, which is something we discuss on occasion, but is not easy to implement properly.
