### ISSUE TITLE
Cinnamon 5.4 - pacellite tray icon is shown in full screen applications

### ISSUE THREAD

**Issue by vladimir-didenko** [linuxmint/cinnamon#10830]
```
 * Cinnamon version - 5.4.0-2-gdb2866ec3
 * Distribution - Alt Linux Sisyphus
 * Graphics hardware *and* driver used - nvidia proprietary
 * 64 bit
 ```

**Issue**
Parcellite tray icon is shown in full-screen applications or e.g. in Alt-F2 dialog it is not grayed. Example of the issue in celluloid

![Screenshot from 2022-06-12 13-55-11](https://user-images.githubusercontent.com/1499142/173229789-3ad12caf-dbb7-47a7-a8db-2b79eb9a566d.png)

**Steps to reproduce**
1. Start application e.g. celluloid.
2. Go to the full screen mode
3. Check that parcellite tray icon is visible

**Expected behaviour**
Parcellite tray icon shouldn't be visible in full screen mode

**Comment by mtwebster** [comment]
Does this always occur? Or just periodically? I've seen it a couple of times but can't reproduce it reliably.

**Comment by vladimir-didenko** [comment]
> Does this always occur? Or just periodically? I've seen it a couple of times but can't reproduce it reliably.

Indeed, I couldn't reproduce this issue reliably as well.

**Comment by nbz6** [comment]
This bug still occur to me.
When I play a video in fullscreen (vlc, mplayer, ..) I can always see the tray icons over my video. 
(except when tray icons are gone from visibility : #10883, #10866 or #10786 bugs)

```
 * Cinnamon version - 5.4.2
 * Distribution - ArchLinux
 * Graphics hardware *and* driver used - AMD (mesa)
 * 64 bit
```

**Comment by romario74** [comment]
I see a very similoar behaviour - reproducible everytime.
Use jdownloader2: the tray icon is black, the real icon is in the upper left corner of the screen.
Right click on any icon does not work.

* $ cinnamon --version
Cinnamon 5.4.2
* Dist: Manjaro testing
* GPU Intel and on AMD

**Comment by bebras123** [comment]
This bug is also present to me. Icons Redshift, Bluetoooth, System update -- always visible in fullscreen.
```
Cinnamon 5.4.2
Kernel: 5.17.15-1-MANJARO
UHD Graphics 620
```

**Comment by nathan-b** [comment]
In #10883, @mtwebster suggested enabling the new xapp tray applet alongside the old one. I just tried that, and I have not seen the problem reoccur so far. Perhaps you can try it as well to see if it helps?

**Comment by mtwebster** [comment]
Fyi, Parcellite is one such program that only works with the system tray currently, so the xapp applet won't help there.

@romario74 did jdownloader2 *ever* work? (like in 5.2). I tested it and it seems as though its problems are not related to (but far worse than) what's going on with everyone else here. A bit of searching suggested the problem isn't unique to Cinnamon.

**Comment by nathan-b** [comment]
Thank you for working on this!
