### ISSUE TITLE
eclipse window moved to active desktop on breakpoint hit

### ISSUE THREAD

**Issue by joske** [linuxmint/Cinnamon#1084]
Hi,

I have an eclipse debugging a java application on separate workspaces. When I hit a breakpoint the 'Urgent' WM hint is raised (I think it is via that mechanism). In Unity, the eclipse launcher then starts to wiggle, but in Cinnamon, the eclipse window is moved to the workspace of the java application is running. This is very annoying. Please provide some other way to handle the 'Urgent' hint.

**Comment by lestcape** [comment]
I think @JosephMcc can close it, as the author also it's joined to the active thread.
