### ISSUE TITLE
FEATURE REQUEST: Give the option for window border setting back

### ISSUE THREAD

**Issue by Rizado** [linuxmint/cinnamon#10842]
```
 * Cinnamon version 5.4.0
 * Distribution - Mint 21
 * Intel UHD Graphics 630 (internal graphic core of CPU - i5-10500)
 * 64 bit
 ```
**Issue**

In Cinnamon 5.4 option for windows border setting was removed. Why? Please give it back.
Please compare:
Cinnamon 5.2.7 (Linux Mint 20.3):
![Screenshot from 2022-06-15 15-50-12](https://user-images.githubusercontent.com/3373906/173833395-f36e855f-fb14-415b-80d2-660c034b465a.png)
Cinnamon 5.4.0 (Linux Mint 21):
![Screenshot from 2022-06-15 15-55-18](https://user-images.githubusercontent.com/3373906/173833406-905fc19d-e1d7-448f-bd68-03e4ddd6f831.png)

**Steps to reproduce**
Open theme settings in Cinnamon v. 5.2 and 5.4 and compare options.

**Expected behaviour**
Window border setting must be in v. 5.4.

**Comment by Secret-chest** [comment]
We now use GTK+ for window borders, that's why it's been removed.

**Comment by mtwebster** [comment]
Any reasonably maintained gtk (controls in cinnamon-settings) themes should already be supporting window borders as well.
