### ISSUE TITLE
Window animation settings seem to be missing

### ISSUE THREAD

**Issue by Zakarya1000** [linuxmint/cinnamon#10841]
```
 * Cinnamon version 5.2.7
   - Please specify if you are using the daily builds PPA No
 * Distribution - Mint 20.3
 * Radeon rx 570
 * 64 bit
```

**Issue**
There used to be lots of customization for window animations in previous versions of Cinnamon, but now they seem to be missing.

**Expected behaviour**
There should be a place in the system settings window that lets you set different animations for windows and what interpolation line they use, but now there is just a basic window that has way less options than before.

**Comment by JosephMcc** [comment]
These were removed intentionally. The things going on underneath the hood to make all that work was a bit of a complicated mess so the decision was made to remove them. There are currently no plans to bring them back.

**Comment by Secret-chest** [comment]
> There are currently no plans to bring them back.

Why?
