### ISSUE TITLE
FEATURE REQUEST: Add Wireguard as VPN option

### ISSUE THREAD

**Issue by fintmu** [linuxmint/cinnamon#10854]
Network client has currently only OpenVPN and PTPP VPN options. It would be very nice to see Wireguard as an option as well.

Wireguard has been part of Linux kernel already 2 years and it still lacks decent GUI on Linux. A native option on Linux Mint network settings would be awesome, because it would allow automatic tunnel establishment on selected networks.

![Screenshot from 2022-06-19 10-55-02](https://user-images.githubusercontent.com/56997162/174471423-6ed746e0-5768-4538-ae5b-02db5438ffc4.png)

**Comment by leigh123linux** [comment]
The NetworkManager team will need to create a wireguard plugin.

**Comment by leigh123linux** [comment]
https://wiki.gnome.org/Projects/NetworkManager/VPN

**Comment by fintmu** [comment]
I have WireGuard connection set up in my NetworkManager already but it will be shown in Network Settings UI only when the connection is established (from command line). After disconnecting it disappears from the list and also it's not listed on "Automatically connect to VPN" selection list for my desired network connection.

![image](https://user-images.githubusercontent.com/56997162/174497425-fd4c003a-a67d-4927-ba3d-d3500ea0fb77.png)
