### ISSUE TITLE
Calendar applet not showing events on startup since update to 5.4.0 desktop

### ISSUE THREAD

**Issue by joekm** [linuxmint/cinnamon#10855]
```
 * Cinnamon version (cinnamon --version)  5.4.0
   - Please specify if you are using the daily builds PPA
     (https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds).
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)  Arch
 * Graphics hardware *and* driver used  AMD RX6700xt  Open Source Driver
 * 32 or 64 bit  64 bit
 * Attach ~/.xsession-errors, or /var/log/syslog
 ```
[xsession-errors.txt](https://github.com/linuxmint/cinnamon/files/8935550/xsession-errors.txt)

**Issue**
Calender applets start ok, but does not have events from evolution-data-server.  If I manually reload the app after start, it then it will display them.

**Steps to reproduce**
Happens everytime on restart.

**Expected behaviour**
calendar applet should load data from evolution-data-server on startup.

**Other information**
No error messages on startup.  Makes me wonder if the app is simply starting before evolution-data-server is loaded?

**Configuration info, if applicable**
If this bug report is related to an Applet, Desklet or Extension, please paste (or use a pastebin service) the offending extension's settings, if it has any.  You can obtain this by opening its configuration, clicking the 'hamburger' button in the upper-right corner of the window, and selecting "Export to a file". **Please be sure to review the contents and remove any personal data it may contain.**

```
[calendar-applet-config.txt](https://github.com/linuxmint/cinnamon/files/8935555/calendar-applet-config.txt)

Please paste here

```

**Comment by mtwebster** [comment]
Should be fixed: https://github.com/linuxmint/cinnamon/commit/82001391338cd606d1b8288951a2baaf50beb66c

There should be a point release in the next day or two.

**Comment by joekm** [comment]
Thanks for the very quick turn :)

**Comment by daddy33** [comment]
It's doing this again (arco-linux, cinnamon 5.6.7).
