### ISSUE TITLE
Cinnamon 5.4.0 missing display settings 

### ISSUE THREAD

**Issue by Eris-JBG** [linuxmint/cinnamon#10856]
```
 * Cinnamon 5.4.0
 * Distribution - Arch Linux
 * AMD 6900XT with AMDGPU drivers
 * 64 bit
 ```

**Issue**
The 'Display' section is no longer available in the settings menu, making it so I can't rotate or rearrange my monitors, my current arrangement was reset on update and I am unable to get it back.

**Steps to reproduce**
Upgrade to cinnamon 5.4.0

**Expected behaviour**
Displaying settings should be available, or those settings should be moved to another settings panel (which afaik, they haven't been)

**Comment by JosephMcc** [comment]
See: https://github.com/linuxmint/cinnamon/issues/10850

**Comment by clinicalfinisher** [comment]
Upvote here: https://bugs.archlinux.org/task/75123

**Comment by mtwebster** [comment]
https://github.com/linuxmint/cinnamon-control-center/commit/5aa5fab4348de4496efe9ec0b5faa20be234d56e
