### ISSUE TITLE
Intelligently hidden panel bounces when revealed

### ISSUE THREAD

**Issue by warwickmm** [linuxmint/cinnamon#10869]
```
 * Cinnamon version (cinnamon --version): Cinnamon 5.4.2
 * Distribution: Arch
 * Graphics hardware *and* driver used
00:02.0 VGA compatible controller: Intel Corporation UHD Graphics 620 (rev 07) (prog-if 00 [VGA controller])
	Subsystem: Lenovo Device 225c
	Flags: bus master, fast devsel, latency 0, IRQ 138
	Memory at 2ffa000000 (64-bit, non-prefetchable) [size=16M]
	Memory at b0000000 (64-bit, prefetchable) [size=256M]
	I/O ports at e000 [size=64]
	Expansion ROM at 000c0000 [virtual] [disabled] [size=128K]
	Capabilities: <access denied>
	Kernel driver in use: i915
	Kernel modules: i915
 * 32 or 64 bit: 64 bit

 * Attach ~/.xsession-errors, or /var/log/syslog
 ```

**Issue**
When the panel (at the top of the screen) is set to "Intelligently hide panel", moving the cursor to the top of the screen causes the panel to bounce, and not fully appear.

![bouncing panel](https://user-images.githubusercontent.com/17345532/174918825-445a0ae9-c317-4ff9-8999-a742c1d7756c.gif)

**Steps to reproduce**
1. Set the panel to "Intelligently hide panel".
2. Maximize an application window.
3. Move the cursor to the top of the screen to reveal the panel.
4. Observe bouncing panel.

**Expected behaviour**
1. The panel should fully appear and remain so until the cursor is moved away from the panel location.

**Other information**

**Configuration info, if applicable**
If this bug report is related to an Applet, Desklet or Extension, please paste (or use a pastebin service) the offending extension's settings, if it has any.  You can obtain this by opening its configuration, clicking the 'hamburger' button in the upper-right corner of the window, and selecting "Export to a file". **Please be sure to review the contents and remove any personal data it may contain.**

```

Please paste here

```

**Comment by daddy33** [comment]
I can't reproduce this on a fresh (arcolinux) install, on a laptop using intel graphics drivers.
But I can reproduce [#10870](https://github.com/linuxmint/cinnamon/issues/10870) on all my machines.

**Comment by Nitrooo** [comment]
Just updated to version 5.4.2, same problem on Manjaro.

**Comment by trancef0rmer** [comment]
same here with 5.4.2 on Manjaro

**Comment by daddy33** [comment]
I have an empirical workaround for this bug. Put a "space" applet in the center of the panel and in the settings, select the maximum width. In fact I noticed that the panel was bouncing only when dragging the mouse cursor in the middle of the panel, which is empty of applets.
