### ISSUE TITLE
Intelligently hidden panel breaks "Show desktop" keyboard shortcut 

### ISSUE THREAD

**Issue by warwickmm** [linuxmint/cinnamon#10871]
```
 * Cinnamon version (cinnamon --version): Cinnamon 5.4.2
 * Distribution: Arch
 * Graphics hardware *and* driver used
00:02.0 VGA compatible controller: Intel Corporation UHD Graphics 620 (rev 07) (prog-if 00 [VGA controller])
	Subsystem: Lenovo Device 225c
	Flags: bus master, fast devsel, latency 0, IRQ 138
	Memory at 2ffa000000 (64-bit, non-prefetchable) [size=16M]
	Memory at b0000000 (64-bit, prefetchable) [size=256M]
	I/O ports at e000 [size=64]
	Expansion ROM at 000c0000 [virtual] [disabled] [size=128K]
	Capabilities: <access denied>
	Kernel driver in use: i915
	Kernel modules: i915
 * 32 or 64 bit: 64 bit

 * Attach ~/.xsession-errors, or /var/log/syslog
 ```

**Issue**

When the panel is set to "Intelligently hide panel", the keyboard shortcut for "Show desktop" does not behave as expected.  Invoking the shortcut once shows the desktop, but immediately invoking it again does not bring back the application windows.  If the panel is set to "Always show panel", the second invocation of "Show desktop" brings back the application windows as expected.

**Steps to reproduce**

1. Assign a keyboard shortcut (e.g., Super+d) to "Show desktop".
2. Set the panel to "Intelligently hide panel".
3. Hit Super+d to show the desktop.
4. Hit Super+d again to hide the desktop (e.g., reveal the application windows).
5. Notice that the second invocation of Super+d didn't do anything.

**Expected behaviour**

The second invocation of the "Show desktop" shortcut should show the application windows.  This is the behavior when the panel is set to "Always show panel".

**Other information**

**Configuration info, if applicable**
If this bug report is related to an Applet, Desklet or Extension, please paste (or use a pastebin service) the offending extension's settings, if it has any.  You can obtain this by opening its configuration, clicking the 'hamburger' button in the upper-right corner of the window, and selecting "Export to a file". **Please be sure to review the contents and remove any personal data it may contain.**

```

Please paste here

```

**Comment by warwickmm** [comment]
Sometimes, hitting the "show desktop" shortcut the first time results in both the desktop elements and the previous application window being visible.  The previous application window is not in focus, rather just an image of it remains visible.  Unfortunately, this doesn't happen all the time and is not consistently reproducible.

**Comment by mtwebster** [comment]
I can no longer reproduce this as of b9efe823cae1b56 and ae2bcbc18d93a.

Once and *if* you can confirm that please close this issue.

Thanks

**Comment by warwickmm** [comment]
Thanks @mtwebster, I can't reproduce this in 5.4.3.  I'll go ahead and close this.
