### ISSUE TITLE
On Cinnamon 5.2.7, the network management applet does not turn on the wired network.

### ISSUE THREAD

**Issue by kuzyaka62** [linuxmint/cinnamon#10873]
* **Cinnamon version**
Cinnamon 5.2.7

 * **Distribution**
  LMDE 5, Linux Mint 20.3, UbuntuCinnamon 22.04

 * **Graphics hardware**
VMware SVGA II Adapter
 * **32 or 64 bit**
64 bit

**Issue**
After disconnecting the wired network in the network management applet, it does not turn on and it can only be turned on in the notification area.

**Steps to reproduce**
1. Open the network management applet and make sure that the wired network is enabled.
 ![net1](https://user-images.githubusercontent.com/82034544/175580040-f1108b72-4407-4e64-87a2-53d24cffe0ff.png)
 
2. In the network management applet, disable the wired network.
![net2](https://user-images.githubusercontent.com/82034544/175580481-ece85d00-ca81-47b5-a039-027fab508c4c.png)

3. In the network management applet, enable the wired network and make sure that the wired network is not enabled.
![net3](https://user-images.githubusercontent.com/82034544/175580773-4403c34c-9fbf-4ab7-a263-90660c15a572.png)

**Expected behaviour**
In the network management applet, after enabling the wired network, it must be enabled.

**Other information**
This problem is present on different Linux kernels (5.4, 5.10 and 5.15) and on different wired adapters, not only on virtual ones.
![lmde5](https://user-images.githubusercontent.com/82034544/175778557-e40f38de-8985-4077-aac7-794f986062a5.png)
![LinuxMint20 3](https://user-images.githubusercontent.com/82034544/175778559-79fedb3e-a4d9-4e2d-8fd1-be2de34f4d4b.png)
![ubuntu-cinnamon](https://user-images.githubusercontent.com/82034544/175778563-2245f909-ad16-4bbe-9cc9-81ab39a0de78.png)

On LMDE 4, Linux Mint 20.2 and on Debian 11, where Cinnamon versions other than 5.2.7 (5.0.3, 5.0.7 and 4.8.6, respectively) are installed, this problem does not exist.
![debian11](https://user-images.githubusercontent.com/82034544/175778585-73985b51-6b43-4567-a788-cac2734ecaf7.png)
This problem manifests itself only on a wired network, there is no problem on a WiFi network.

This problem was also discussed [on the Linux Mint forum](https://forums.linuxmint.com/viewtopic.php?f=208&t=375971), where you can also look.

**Comment by kuzyaka62** [comment]
![net1](https://user-images.githubusercontent.com/82034544/175768093-3ad896f7-c46d-4abc-90b0-a3fdc5782d83.png)
![net2](https://user-images.githubusercontent.com/82034544/175768096-db3a8334-e32a-47d4-bbfd-e8dc3086e054.png)
![net3](https://user-images.githubusercontent.com/82034544/175768099-684d61bc-0e02-4c79-9b14-1c5b2eadadc0.png)

**Comment by szb512** [comment]
Strange...it happens to me too.

**Comment by happnatious1** [comment]
I also see this behavior on linux mint 21.

System:
  Kernel: 5.15.0-46-generic x86_64 bits: 64 compiler: gcc v: 11.2.0 Desktop: Cinnamon 5.4.11
    tk: GTK 3.24.33 wm: Mutter dm: LightDM Distro: Linux Mint 21 Vanessa base: Ubuntu 22.04 jammy
Machine:
  Type: Desktop Mobo: ASRock model: AB350M Pro4 serial: <superuser required>
    UEFI: American Megatrends v: P4.90 date: 07/06/2018
CPU:
  Info: 8-core model: AMD Ryzen 7 1700 bits: 64 type: MT MCP arch: Zen rev: 1 cache: L1: 768 KiB
    L2: 4 MiB L3: 16 MiB
  Speed (MHz): avg: 1544 high: 1547 min/max: 1550/3000 boost: enabled cores: 1: 1544 2: 1547
    3: 1544 4: 1545 5: 1545 6: 1539 7: 1521 8: 1547 9: 1547 10: 1547 11: 1547 12: 1547 13: 1546
    14: 1547 15: 1547 16: 1547 bogomips: 95815
  Flags: avx avx2 ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm
Graphics:
  Device-1: NVIDIA GP108 [GeForce GT 1030] vendor: Gigabyte driver: nvidia v: 510.85.02 pcie:
    speed: 8 GT/s lanes: 4 ports: active: none off: DVI-D-1,HDMI-A-1 empty: none bus-ID: 23:00.0
    chip-ID: 10de:1d01
  Device-2: Logitech QuickCam Pro 9000 type: USB driver: snd-usb-audio,uvcvideo
    bus-ID: 1-5.3.4:9 chip-ID: 046d:0990
  Display: x11 server: X.Org v: 1.21.1.3 driver: X: loaded: nvidia
    unloaded: fbdev,modesetting,nouveau,vesa gpu: nvidia display-ID: :0 screens: 1
  Screen-1: 0 s-res: 3440x2520 s-dpi: 96
  Monitor-1: DVI-D-0 pos: top-right res: 1920x1080 dpi: 37 diag: 1525mm (60")
  Monitor-2: HDMI-0 pos: primary,bottom-l res: 3440x1440 dpi: 109 diag: 867mm (34.1")
  OpenGL: renderer: NVIDIA GeForce GT 1030/PCIe/SSE2 v: 4.6.0 NVIDIA 510.85.02
    direct render: Yes
Audio:
  Device-1: NVIDIA GP108 High Definition Audio vendor: Gigabyte driver: snd_hda_intel v: kernel
    pcie: speed: 8 GT/s lanes: 4 bus-ID: 23:00.1 chip-ID: 10de:0fb8
  Device-2: AMD Family 17h HD Audio vendor: ASRock driver: snd_hda_intel v: kernel pcie:
    speed: 8 GT/s lanes: 16 bus-ID: 25:00.3 chip-ID: 1022:1457
  Device-3: Logitech QuickCam Pro 9000 type: USB driver: snd-usb-audio,uvcvideo
    bus-ID: 1-5.3.4:9 chip-ID: 046d:0990
  Sound Server-1: ALSA v: k5.15.0-46-generic running: yes
  Sound Server-2: JACK v: 0.125.0rc1 running: no
  Sound Server-3: PulseAudio v: 15.99.1 running: yes
  Sound Server-4: PipeWire v: 0.3.48 running: yes
Network:
  Device-1: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet vendor: ASRock driver: r8169
    v: kernel pcie: speed: 2.5 GT/s lanes: 1 port: f000 bus-ID: 1f:00.0 chip-ID: 10ec:8168
  IF: enp31s0 state: up speed: 1000 Mbps duplex: full mac: <filter>
  IF-ID-1: anbox0 state: down mac: <filter>
  IF-ID-2: vmnet1 state: unknown speed: N/A duplex: N/A mac: <filter>
  IF-ID-3: vmnet8 state: unknown speed: N/A duplex: N/A mac: <filter>
Info:
  Processes: 405 Uptime: 23h 29m Memory: 15.56 GiB used: 7.27 GiB (46.7%) Init: systemd v: 249
  runlevel: 5 default: 2 Compilers: gcc: 11.2.0 alt: 11/9 Client: Cinnamon v: 5.4.11 inxi: 3.3.13

**Comment by Benik3** [comment]
Hello.
Any news to this? I have this problem too, but I have the Cinnamon on Ubuntu 22.04.
I tried to update to Cinnamon 5.6.7 but it's still the same.
Also I found that not only turning ON/OFF doesn't work, but also any other settings in the network (like changing to static IP address).
