### ISSUE TITLE
Cinnamon broken when i minimize or maximize a window

### ISSUE THREAD

**Issue by maxcodev** [linuxmint/cinnamon#10874]
* $ cinnamon --version
Cinnamon 5.4.2

 * Distribution - Arch
 * Kernel: 5.15.49-1-lts
 * CPU: AMD Ryzen 5 3450U with Radeon Vega Mobile Gfx (8) @ 2.100GHz
 * GPU: AMD ATI Radeon Vega Series / Radeon Vega Mobile Series
 * 64 bit

-----

When i change to another Desktop, like GNOME, all good, when i return to Cinnamon, the problems begin.

**Comment by fredcw** [comment]
What do you mean by "Cinnamon broken"? What happens when you minimise or maximise a window? Does this happen with all windows?

**Comment by JosephMcc** [comment]
There was never an answer here so closing.
