### ISSUE TITLE
clear all notifications button

### ISSUE THREAD

**Issue by clumsyfingers** [linuxmint/cinnamon#10877]
5.4.2/arch
could we have a 'clear all notifications' button in the notifications applet?
if you enable notifiactions in twitter for example suddenly you have 100 notifications in the list. its a pain clearing them one by one

**Comment by JosephMcc** [comment]
Isn't that exactly what the "Clear notifications" menu entry already does?

**Comment by JosephMcc** [comment]
I think we already have this and there was never a response.
