### ISSUE TITLE
locate-pointer: concentric circle animation barely or not visible within dark themes or backgrounds

### ISSUE THREAD

**Issue by DirkHaar** [linuxmint/cinnamon#10881]
```
 * Cinnamon version 5.2.7
   - no daily builds, standard packages
 * Distribution - (Mint 20.3 Una
 * Graphics hardware Intel 620
 * 64 bit

**Issue**
When using the locate-pointer function on dark themes, the animation of dark concentric circles is barely or sometimes impossible to be seen, making it absolutely useless.

**Steps to reproduce**
In "Mouse ad Touchpad" activate "Show position of pointer when the Control key is pressed". 
Try to see the animation on any dark background. It's not necessary to install a dark theme to see the current animation is wrong as it is only useful on a bright background.

**Expected behaviour**
The animation is needed to change its colours, no matter if it changes between black and white, as a colour gradient or rainbow or at best as an adjustable settings, according to mouse arrow theme or colour theme.

https://user-images.githubusercontent.com/12502925/175824907-c954392c-0b29-4940-94c7-75f4dc2d0a72.mov

**Comment by Secret-chest** [comment]
> ```
>  * Cinnamon version 5.2.7
>    - no daily builds, standard packages
>  * Distribution - (Mint 20.3 Una
>  * Graphics hardware Intel 620
>  * 64 bit
> 
> **Issue**
> When using the locate-pointer function on dark themes, the animation of dark concentric circles is barely or sometimes impossible to be seen, making it absolutely useless.
> 
> **Steps to reproduce**
> In "Mouse ad Touchpad" activate "Show position of pointer when the Control key is pressed". 
> Try to see the animation on any dark background. It's not necessary to install a dark theme to see the current animation is wrong as it is only useful on a bright background.
> 
> **Expected behaviour**
> The animation is needed to change its colours, no matter if it changes between black and white, as a colour gradient or rainbow or at best as an adjustable settings, according to mouse arrow theme or colour theme.
> 
> https://user-images.githubusercontent.com/12502925/175824907-c954392c-0b29-4940-94c7-75f4dc2d0a72.mov
> 
> 
> 

Maybe it could be inverted.

Also I would like to see a hotkey setting - I would very much prefer it on right control so it doesn't interfere with shortcurs (or sprinting in Minecraft)

**Comment by DirkHaar** [comment]
Inverting wouldn't solve the problem making the circles brighter and invisible on white/light grey background.
"Inverting the background" or kind of flickering of the pointer is on would be okay.

As for hotkey: yes, it should be configurable.
It's ctrl on windows too, that's maybe the reason for the current setting.
In fact, it should (also) be put/found in the accessibility menu.
Visibility or motion impaired people might use this function even more often then me
- or would, but don't as they don't see the effect.
