### ISSUE TITLE
5.2.7 and 5.4.0 - Unable to change any icon on the panel

### ISSUE THREAD

**Issue by rado84-github** [linuxmint/cinnamon#10887]
```
 * Cinnamon version (5.2.7 and 5.4.0)
 * Distribution - (Arco Linux)
 * Graphics hardware *and* driver used: GTX 1660 Ti, 510.54.
 * 64 bit
 * Attach ~/.xsession-errors, or /var/log/syslog - no such files exist in both locations.
 ```

**Issue**
I had to reinstall Arch and now I can't change any icon on the panel bc there's this "loading" inscription at the bottom of the "icon selection" window and all of my custom icons never show up.
I first saw that on 5.4.0, so I downgraded cinnamon to 5.2.7 but it was there too.

![Picture_created_28-06-2022_22-29-22](https://user-images.githubusercontent.com/41172201/176317984-bd59d4e6-9ac0-4fe3-a935-5e4389eb989e.png)

I even made a video for better clarity of the problem:
[simplescreenrecorder-2022-06-28_23.27.11.zip](https://github.com/linuxmint/cinnamon/files/9005928/simplescreenrecorder-2022-06-28_23.27.11.zip)

The video also shows the steps to reproduce.
Manually typing the path to my custom icons has the same result: "Loading..."

**Steps to reproduce**
1. Open the menu editor.
2. Click on any application to change its icon.
3. Navigate to a folder with custom icons.
4. Watch the "Loading..." thing start spinning at the bottom of the window "Icon selection".

**Expected behaviour**
User images should be displayed in hte window "icon selection". 

**Other information**
I've been using these custom icons for the past 7 years, so it's not their format. Also, as you will see on the video, I managed to change the most of them manually by editing the corresponding .desktop files but there are two applets left whose icons I can't change bc they don't have .desktop files.

**Comment by JosephMcc** [comment]
This was fixed whenever your distro gets the update.
