### ISSUE TITLE
Right-click on menu should have Edit and Remove options

### ISSUE THREAD

**Issue by wrouesnel** [linuxmint/Cinnamon#1089]
Right clicking on items on the Cinnamon menu currently differs from how they behave on Panels and Desktops, in that there is no option to Edit or Remove an item when done so, requiring people to access the Edit Menu panel to make changes.

The common use case of both these options is for user-added menu items which have had their location changed or have been since deleted. In both cases, it would be faster and smoother for the use to be able to simply right click on an item and hit edit.

**Comment by Vahan86** [comment]
@JosephMcc , please see the comment posted above.

**Comment by JosephMcc** [comment]
Same as https://github.com/linuxmint/Cinnamon/issues/726
