### ISSUE TITLE
Feature request: webp images for desktop backgrounds

### ISSUE THREAD

**Issue by baubleb** [linuxmint/cinnamon#10899]
```
 * Cinnamon version (cinnamon --version)
Cinnamon 4.6.7

 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)

Mint 20

 * Graphics hardware *and* driver used

NV

 * 32 or 64 bit

64 bit
 ```

**Issue**

Unable to use .webp images for desktop background

**Steps to reproduce**
Attempt to use a .webp image format and select it as a background

**Expected behaviour**

webp image to show in the pictures preview and on the background when selected

**Comment by sonichy** [comment]
No hope

**Comment by mtwebster** [comment]
This is supported when [webp-pixbuf-loader](https://github.com/aruiz/webp-pixbuf-loader) is installed. It will be in the mint repos in Mint 21, but you can build it yourself in the meantime. This allows thumbnails in nemo as well. I've tested setting the desktop background with a webp.

ref:
https://github.com/linuxmint/xviewer/commit/dfeaf7d6e757df64c554483fb5a336f551781295
