### ISSUE TITLE
[System Settings] icon do not display in Launcher and Taskbar

### ISSUE THREAD

**Issue by sonichy** [linuxmint/cinnamon#10902]
```
 * Cinnamon 5.2.7
 * Arch
 * Intel Corporation 2nd Generation Core Processor Family Integrated Graphics Controller
 * 64 bit
 ```
![alt](https://s1.ax1x.com/2022/07/05/jt8QjP.png)

**Comment by szb512** [comment]
Did you perhaps change any settings that could have affected the icon not displaying?

**Comment by szb512** [comment]
Did you look in the 'All Applications' tab in the launcher?
It appeared there for me.
As of the taskbar, if it does not appear, the app is not running.

**Comment by sonichy** [comment]
Solved:
`sudo gtk-update-icon-cache /usr/share/icons/Adwaita`
