### ISSUE TITLE
Applet API need IconApplet.set_applet_icon_pixmap(pixmap)

### ISSUE THREAD

**Issue by sonichy** [linuxmint/Cinnamon#10909]
```
 * Cinnamon 5.2.7
 ```
[https://github.com/sonichy/CMDU_Cinnamon](https://github.com/sonichy/CMDU_Cinnamon)
Need draw dynamic icon per second, a line of MEM usage, a line of CPU usage, some fuction like:
```IconApplet.set_applet_icon_pixmap(pixmap)```
![alt](https://raw.githubusercontent.com/sonichy/CMDU_DDE_DOCK/master/preview.png)

**Comment by JosephMcc** [comment]
There are already applets that do this type of thing in https://github.com/linuxmint/cinnamon-spices-applets
Maybe look at how they are handling it.
