### ISSUE TITLE
Problems with Cinnamon sound module

### ISSUE THREAD

**Issue by MasterDevX** [linuxmint/cinnamon#10912]
```
 * Cinnamon 5.4.2
 * Arch Linux
 * NVidia MX110 with proprietary driver 515.57
 * 64 bit
 ```

**Issue**
I have installed Cinnamon during Arch installation via [archinstall](https://github.com/archlinux/archinstall). Noticed several issues with sound module while configuring audio:
- "Test Sound" menu shows incorrect channel map (8.1 surrounding audio system, while I have simple stereo) and does not play any sounds when buttons are clicked.
![2022-07-07-223547_494x498_scrot](https://user-images.githubusercontent.com/32103950/177857657-6a8de668-6128-425b-a93b-c6194c7f6ee4.png)
- Input level does not show anything, while the microphone itself works in other applications and I can change It's sensitivity using the slider above the input level.
![2022-07-07-223735_637x177_scrot](https://user-images.githubusercontent.com/32103950/177858247-3f156c06-5474-463c-8b44-fbc5f86c3b85.png)

**Expected behaviour**
- "Test Sound" menu should show only "front left" and "front right" channels (in my case) and play corresponding sounds when test buttons are pressed.
- Input level should show the actual input sound level.

**Other information**
I am almost sure this is not hardware specific thing because I have the identical issue on two PCs with absolutely different hardware but the same software (except video driver). Also, I have done a little research:
- When I run sound settings from terminal using ```cinnamon-settings sound```, I get the following error when clicking the "Test Sound" button:
```
Traceback (most recent call last):
  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_sound.py", line 397, in testSpeakers
    SoundTest(a.get_toplevel(), self.controller.get_default_sink())
  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_sound.py", line 458, in __init__
    self.setPositionHideState()
  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_sound.py", line 480, in setPositionHideState
    if map.has_position(SOUND_TEST_MAP[index][5]):
AttributeError: 'ChannelMap' object has no attribute 'has_position'
```
After this incorrect-mapped and non-working menu opens up.
So I decided to do ```print(dir(map))``` before line 480 in ```cs_sound.py``` just to ensure this object really has no attribure ```has_position```:
```
['__class__', '__copy__', '__deepcopy__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__gdoc__', '__ge__', '__getattribute__', '__gpointer__', '__grefcount__', '__gsignals__', '__gt__', '__gtype__', '__hash__', '__info__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '_force_floating', '_ref', '_ref_sink', '_unref', '_unsupported_data_method', '_unsupported_method', 'bind_property', 'bind_property_full', 'can_balance', 'can_fade', 'can_lfe', 'chain', 'compat_control', 'connect', 'connect_after', 'connect_data', 'connect_object', 'connect_object_after', 'disconnect', 'disconnect_by_func', 'do_volume_changed', 'emit', 'emit_stop_by_name', 'find_property', 'force_floating', 'freeze_notify', 'g_type_instance', 'get_balance', 'get_data', 'get_fade', 'get_lfe', 'get_mapping', 'get_num_channels', 'get_properties', 'get_property', 'get_qdata', 'get_volume', 'getv', 'handler_block', 'handler_block_by_func', 'handler_disconnect', 'handler_is_connected', 'handler_unblock', 'handler_unblock_by_func', 'install_properties', 'install_property', 'interface_find_property', 'interface_install_property', 'interface_list_properties', 'is_floating', 'list_properties', 'new', 'newv', 'notify', 'notify_by_pspec', 'override_property', 'parent', 'priv', 'props', 'qdata', 'ref', 'ref_count', 'ref_sink', 'replace_data', 'replace_qdata', 'run_dispose', 'set_balance', 'set_data', 'set_fade', 'set_lfe', 'set_properties', 'set_property', 'steal_data', 'steal_qdata', 'stop_emission', 'stop_emission_by_name', 'thaw_notify', 'unref', 'watch_closure', 'weak_ref']
```
- While on "Input" tab and trying to switch the microphone, the following error appears:
```
Traceback (most recent call last):
  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_sound.py", line 764, in defaultSourceChanged
    self.inLevel.setStream(defaultSource)
  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_sound.py", line 346, in setStream
    self.stream.remove_monitor()
AttributeError: 'MixerSource' object has no attribute 'remove_monitor'
```
I think it has something to do with the fact input level is blank, however, as I mentioned the entire PulseAudio system is working, switching microphones from current menu and changing sensitivity via sliders are working too.

I will appreciate any thoughts on this, thanks.

**Comment by leigh123linux** [comment]
Is 'Output profile' set to Stereo for the device?

![image](https://user-images.githubusercontent.com/1299302/178141190-e7415cfa-0a64-453a-a524-f56bac7c659d.png)

**Comment by MasterDevX** [comment]
> Is 'Output profile' set to Stereo for the device?

Sure, it is.

**Comment by Mike-773** [comment]
I had the same problem with 3 different computers over the few weeks. It happened with Linux Mint and also with Ubuntu budgie. It might be associated with installing the Vivaldi web browser and then having multiple tabs open as vivaldi has a feature to shut down sound on all tabs playing additional sound.

I was able to do a workaround and get sound back on one computer by typing the command alsamixer into the terminal.

![alsamixer command after corrections](https://user-images.githubusercontent.com/109114353/178374416-30b848da-3f47-44d1-b249-9eac72fbf6a1.png)


I've had sound issues over the years with the sound suddenly disappearing from Linux Mint so there is a definite long term issue there. 

Here is the post I used to correct this. It has more detail than I have given here. As I say it worked on one computer, not on another and the third computer had the sound back when I next opened it - I have never seen that with that "sound coming back" happen before, when the sound is gone it is usually gone.

https://www.maketecheasier.com/fix-no-sound-issue-ubuntu/

Mike

**Comment by Harry-W-Haines-III** [comment]
I believe this was fixed during the Mint 21 Beta.
https://github.com/linuxmint/mint21-beta/issues/7

**Comment by mtwebster** [comment]
The original issue, yes - that was just broken ui elements in cinnamon settings.

This one: https://github.com/linuxmint/cinnamon/issues/10912#issuecomment-1181060829 isn't related as far as I can see, so should be a new issue if it seems related to Cinnamon (it seems more like an upstream Ubuntu problem but I could be mistaken.

**Comment by Mike-773** [comment]
You're right Michael, it's definitely an Ubuntu issue - I tried loading
Ubuntu Budgie and had the same issue with that.

Mike Ward

**Comment by Mike-773** [comment]
That's great to hear Harry. I downloaded the new Linux Mint ISO last night
and will probably load it on one of my computers tomorrow.

Mike Ward
