### ISSUE TITLE
changing the brightness while using the menu in cinnamon desktop

### ISSUE THREAD

**Issue by 64hr** [linuxmint/cinnamon#10918]
```
 * Cinnamon 5.2.7
   - Please specify if you are using the daily builds PPA (NO)
     (https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds).
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) (LINUX MINT 20.3)
 * Graphics hardware *and* driver used (AMD RYZEN 5 - READEON VEGA GRAPHICS)
 * 32 or 64 bit (64 BIT)
 * Attach ~/.xsession-errors, or /var/log/syslog
 ```

**Issue**
changing the brightness using keyboard while opening menu (start menu to be clear) won't work unless you are not using the menu. (i'm using FN + F12 to change the brightness)
 

**Steps to reproduce**

**Expected behaviour**

**Other information**

**Configuration info, if applicable**
If this bug report is related to an Applet, Desklet or Extension, please paste (or use a pastebin service) the offending extension's settings, if it has any.  You can obtain this by opening its configuration, clicking the 'hamburger' button in the upper-right corner of the window, and selecting "Export to a file". **Please be sure to review the contents and remove any personal data it may contain.**

```

Please paste here

```

**Comment by JosephMcc** [comment]
I'm on Cinnamon 5.4 and here I can change the brightness with the functions keys while the menu is open.

**Comment by 64hr** [comment]
I'm using Cinnamon 5.2.7
I did not get Cinnamon 5.4 yet in my distro so I will close the issue.

**Comment by 64hr** [comment]
I'm using Cinnamon 5.2.7
I did not get Cinnamon 5.4 yet in my distro so I will close the issue.

**Comment by 64hr** [comment]
I'm using Cinnamon 5.2.7
I did not get Cinnamon 5.4 yet in my distro so I will close the issue.

**Comment by JosephMcc** [comment]
If you make the upgrade to Cinnamon 5,4 and Mint21 and the issue persists, feel free to reopen it.
