### ISSUE TITLE
[question] What controls the size of the X button?

### ISSUE THREAD

**Issue by rado84-github** [linuxmint/cinnamon#10920]
I found workarounds for the bugs with custom icons for apps and applets ( https://github.com/linuxmint/cinnamon/issues/10887 ) and now I wanted to change the icons on the title bar - the icons for the buttons that invoke the functions to minimize, maximize and close. For the most part I did it, minimize and maximize are done. But the X button appears in a strange way. It appears like this:
![Picture_created_10-07-2022_02-46-33](https://user-images.githubusercontent.com/41172201/178126170-1181b1e6-54db-4540-9fd9-82778dd35633.png)

But I want it to appear like the X button on Telegram-Desktop, meaning like this:
![Picture_created_10-07-2022_02-46-21](https://user-images.githubusercontent.com/41172201/178126183-d15cfb2d-b840-416c-93e2-f53e90a5eed5.png)

The question is - what and and where do I have to change in order to have the X button appear the way I want it?

**Comment by JosephMcc** [comment]
This is controlled by the themes you are using. I'm closing this since this isn't really the place for it. You'll get more help somewhere like the Mint forums.

**Comment by rado84-github** [comment]
Well, I thought this would be the better place to ask bc I'm guessing this question would be better answered by developers. But OK, I'll ask on the forum as well.
