### ISSUE TITLE
Lock up when dragging Firefox tab from one window to another

### ISSUE THREAD

**Issue by JulianHeuser** [linuxmint/cinnamon#10922]
```
 * Cinnamon version 5.2.7
 * Distribution - Mint 20.3
 * GPU: RX 570 4GB 
 * 64 bit
 ```

**Issue**
Sometimes, when dragging a tab from one Firefox window to another, the screen will freeze up. It seems like no input goes through either.

**Steps to reproduce**

1. Create two Firefox windows
2. Drag a tab from one window into the tabs of the other window.
3. Repeat it a few times, the desktop freezes up.

**Expected behaviour**
No crash

**Other information**
Best way to recover that I've found is to open a TTY and enter `export DISPLAY=:0.0 && cinnamon --replace &`

This doesn't happen with ungoogled chromium, and I'm running the most up-to-date version of Firefox for mint (102.0.1).

This also happens with a clean install of the flathub version.

I tested with no non-default applets/desklets/extensions, it still happened.

This could be an issue with Firefox.

**Comment by JosephMcc** [comment]
I can't reproduce this with Firefox installed from the repos. Also don't remember ever encountering this and it's something I do a good bit.

**Comment by JulianHeuser** [comment]
I'm not even getting errors in xsession-errors or syslog... Tried removing my custom theming and it still happens. This is really strange, I have no clue why it'd be happening to just me.

Since mint 21 is right around the corner, I'll upgrade to that when it's out of beta and see if the issue is still there. The rebase of mutter might include some obscure bug fixes.

**Comment by JulianHeuser** [comment]
After updating to firefox 103, I can no longer reproduce this issue. I'll close the issue now.
