### ISSUE TITLE
Menu applet: Two categories highlighted at the same time.

### ISSUE THREAD

**Issue by fredcw** [linuxmint/cinnamon#10935]
```
 * Cinnamon version 5.4.2
 * Mint daily builds PPA and Manjaro
 * Bug not present in Mint 20.3
 ```

**Issue**
When option "Change categories on hover" is _off_

two categories can be highlighted at the same time - hover highlight is not removed.

![simplescreenrecorder-2022-07-16_22 54 44](https://user-images.githubusercontent.com/58893963/179373339-ce0b3008-a884-4cbf-9a0e-5ad58419db49.gif)

**Comment by JosephMcc** [comment]
I can reproduce this. In this case it seems like we should probably have different styling for the hovered and active item. Also when moving from the categories to the app list the one that isn't active should lose the highlight.

**Comment by fredcw** [comment]
Yes, this is what I do in Cinnamenu. When I first looked at it this in cinnamenu, I noticed that there was a class defined in the Mint-Y themes called `.menu-category-button-hover` even though this was not used by any applets at the time. I added this class to cinnamenu and added it to a few of the themes in linuxmint/cinnamon-spices-themes eg, Adapta, Faded-Dream, Carta, Faience, and a few others. @smurphos also added this class to his Cinnamox themes. So Cinnamenu now adds style classes `.menu-category-button-selected` and `.menu-category-button-hover` with the former added as a backup style in case the later is not defined in the theme.

Perhaps in hindsight, it would have been better to use the pseudo class `hover` (`.menu-category-button:hover`) This would be slightly more logical and technically correct from the theme designers point of view although it probably wouldn't make a big practical difference. In any case, either solution should work fine and in the case of cinnamenu, I can just add `.menu-category-button:hover` in addition to `.menu-category-button-selected` and `.menu-category-button-hover` as `.menu-category-button:hover` has a higher specificity and would therefore take precedence.

**Comment by JosephMcc** [comment]
I personally prefer the use of the pseudo classes like `:selected` and `:hover` but since themes already contain the others maybe it's best just to stick with those. That type of convention exists all over in Cinnamon and I've never been a big fan :)

**Comment by fredcw** [comment]
I decided to go with just `menu-category-button:hover` in cinnamenu as I can then add a reasonable fallback style in Cinnamenu's `cinnamon.css` file. I also submitted a PR of this same style to cinnamon's default theme so that it be used as a fallback in the menu applet in future as well. https://github.com/linuxmint/cinnamon/pull/11451 i.e. just use pseudo class `menu-category-button:hover` instead of `menu-category-button-selected`.

**Comment by fredcw** [comment]
@mtwebster I'm trying to clean up some of the key navigation code in the menu applet and wondering if you know what the preferred/intended behaviour is. When navigating the app box with the up/down keys, if you then press left (i.e. put key nav focus on currently selected category button) and then immediately press right again without changing the category, should the top app in the app box be selected or should the app you was previously on be selected? The current behaviour is to go to the first app in the list and has been since at least Mint 20.0 and probably a lot longer. However, when categoryHover mode is off (not the default,) it goes back to the previously selected app. The applet code would suggest that the later was the original intended behaviour even if that hasn't been the actual behaviour for a long time.

For example line 1927:

```
case this.categoriesBox:
  ⋮
case "right":
  ⋮
item_actor = (this._previousVisibleIndex != null) ?
     this.appBoxIter.getVisibleItem(this._previousVisibleIndex) :
     this.appBoxIter.getFirstVisible();
```

Just wondering if anyone has any opinion on this.

**Comment by mtwebster** [comment]
I think it should return to the previously selected app for sure, not reset to the top.
