### ISSUE TITLE
[request] follow freedesktop appearance.color-scheme spec

### ISSUE THREAD

**Issue by MrQuerter** [linuxmint/cinnamon#10934]
I don't know if it's a good place to suggest this feature, but it seems right.

I was told to suggest following the freedesktop appearance.color-scheme spec since new software doesn't automatically detect the dark mode that I have enabled on my Linux Mint 20.3 Cinnamon. 

One such example of program not detecting the dark mode is Bottles and here's how I got to know about this issue.
https://github.com/bottlesdevs/Bottles/issues/1758

Now I don't know if it's cinnamon specific or does it happen on all Mint editions.

**Comment by mtwebster** [comment]
This is already on our TODO, we just haven't gotten to it yet - implementing xdg-desktop portals.

Ref:
https://github.com/linuxmint/cinnamon-desktop/issues/202

**Comment by benmccann** [comment]
This is now implemented

Docs for the setting here: https://flatpak.github.io/xdg-desktop-portal/
