### ISSUE TITLE
5.4.3 - restarting the desktop env stops the startup sound

### ISSUE THREAD

**Issue by rado84-github** [linuxmint/cinnamon#10944]
```
 * Cinnamon version (5.4.3)
 * Distribution - (Arch)
 * Graphics hardware *and* driver used (GTX 1660 Ti, 515.57)
 * (64 bit)
 * Attach ~/.xsession-errors, or /var/log/syslog (no such files available in either location)
 ```

**Issue**
Restarting Cinnamon while the startup music is playing stops the music in the middle.
It wasn't like that in 5.2.7. In 5.2.7 restarting the DE kept the startup music playing until its natural end.

**Steps to reproduce**
1. Setup any startup music to play when Cinnamon starts. It better be longer - 15-20 seconds (or more), so you can hear the difference.
2. Restart X (Ctrl+Alt+Backspace) to mimic computer reboot and log back in.
3. You will hear your startup music playing. While it's playing, press a key combination to restart the desktop environment. If you don't have a shortcut key combination set up for that, you'll have to set it and then go back to step 2.
4. Notice the startup music stops playing upon desktop env. restart.

**Expected behaviour**
Restarting the desktop should keep the startup music playing until it's finished.

**Other information**
The only reason I had to resort to desktop restart right after logon is because when Cinnamon starts, instead of my regular cursor, I see a clock working which indicates something is loading and it doesn't go away for another minute or so. The only way to make the clock go away is to restart Cinnamon.

**Comment by mtwebster** [comment]
The method by which sounds are played has changed, so they get stopped if the desktop is restarted. This isn't a bug - having to restart the desktop immediately upon login is not a normal thing to have to account for.

You should try to figure out what's causing the startup cursor - check your 'Startup Programs' in settings. If you discover what it is, you can edit its desktop file to eliminate the busy cursor.

For instance, this is part of LibreOffice Writer's desktop file:
```
Comment[zh_CN]=使用 Writer 对信函、报告、文档以及网页中的文字和图像进行编辑。
Comment[zh_TW]=使用 Writer 可以製作與編輯書信、報告、文件和網頁中的文字和影像。
Comment[zu]=Create and edit text and images in letters, reports, documents and Web pages by using Writer.
StartupNotify=true
X-GIO-NoFuse=true
Keywords=Text;Letter;Fax;Document;OpenDocument Text;Microsoft Word;Microsoft Works;Lotus WordPro;OpenOffice Writer;CV;odt;doc;>
InitialPreference=5
```
If I set `StartupNotify` to false, it will stop this from happening when I launch it.
