### ISSUE TITLE
[Muffin?] Window tiling and edge snapping do not work in rotated display

### ISSUE THREAD

**Issue by sudorook** [linuxmint/cinnamon#10957]
Cinnamon 5.4.4-1
Arch Linux
amdgpu driver (integrated graphics)
64-bit

I use an external monitor, and when I have the display rotated, window tiling/snapping does not work. Curiously, it does when in a normal rotation. See GIF below:

[Peek 2022-07-21 17-22.webm](https://user-images.githubusercontent.com/6200846/180328253-79178fb5-0a85-4a49-9378-d40162d87018.webm)

(The rotate command is a [wrapper script](https://github.com/sudorook/misc-scripts/blob/master/rotate) for using xrandr.)

No idea what is causing this.

Attached are the corresponding Cinnamon dconf settings for Cinnamon. I didn't see anything obviously odd, but I could be wrong.

[cinnamon-dconf-debug.txt](https://github.com/linuxmint/mint21-beta/files/9163208/cinnamon-dconf-debug.txt)

I should also note that in previous releases of 5.4 in the Arch repos, the keyboard shortcuts worked but dragging windows to tile/snap them did not. It was only until 5.4.4 that neither did.

**Comment by bitstrings** [comment]
Same here, rotated second monitor and tiling issues since 5.4.

**Comment by MartNytrm** [comment]
Can confirm the issue on on 5.15.55-1-MANJARO, Cinnamon 5.4.3-1, NVIDIA 470.129.06.
On my second monitor with rotation "portrait left" the **window tilling does not work when performed by dragging with mouse**.
**But window tilling does work when used with keyboard shortcuts (SUPER + ARROW).**
Everything will work fine on second screen if the second screen is not rotated.
On first screen (not rotated) window tilling works at all time.

**Comment by eris-price** [comment]
Also seeing this on the latest on arch linux, on cinnamon 5.4.8. it's been an issue for about 4/5 days now. TIling with the mouse or kb shortcuts does not work on rotated monitor, but works fine on the two monitors in the default orientation.

**Comment by MartNytrm** [comment]
Can confirm that the issue still persists on Cinnamon 5.4.8.

@eris-price Interesting thing I realized on 5.4.8 now: When trying to perform tiling on rotated second screen via kb shortcuts, it works as soon I move the mouse pointer on primary monitor. If pointer is on secondary, it won't work. Is it the same with yours?
I could swear that on 5.4.3 it has always worked no matter where the mouse pointer was.

**Comment by Eris-JBG** [comment]
Ah! I hadn't noticed that before but you are correct! When the mouse pointer is on one of my unrotated screens, but a window on the rotated screen has focus, the tiling shortcuts do work for the window on the rotated screen. That's definitely some strange behavior.
I can confirm that previous cinnamon versions were agnostic to where the mouse pointer was when using a tiling shortcut. I have 2 unrotated monitors, and 1 rotated one. If the pointer is on an unrotated monitor, cinnamon doesn't seem to care. 
Something I just tested was having a window on an unrotated monitor with focus, and moving my mouse pointer over to the rotated monitor, and then the tiling shortcuts stopped working for the app on the unrotated screen. 
So it seems like the tiling shortcuts break whenever the mouse pointer is on a rotated screen, and it has nothing to do with where the actual window with focus is.
