### ISSUE TITLE
Feature request for menu@cinnamon.org: Provide a way to get the command behind a menu entry

### ISSUE THREAD

**Issue by Sayanel01** [linuxmint/cinnamon#10959]
```
 * Cinnamon 5.2.7
leaving the other info, as this is a feature request
 ```

**Issue**
Many installed program will add menu entries. The command they run may be straightforward (firefox entry runs `firefox %u`, but it is not always the case (kompare will use `-o` option by default, and android studio installed through apt will run something like `/opt/android-studio-2021.2.1/android-studio/bin/studio.sh` because for whatever reason they don't place it in PATH. They are other non obvious entries, I just don't remember them all)

The fastest way I found to know what is behind a menu entry is "right click -> add to desktop -> right click on desktop entry --> property", which is a bit tedious.

**Wanted behaviour**
There should be a "property" option when right clicking menu entry. It could take us to the launcher property (e.g. similar as menu@cinnamon option -> menu tab -> open menu editor -> select your entry -> properties)

**Comment by mtwebster** [comment]
This has been suggested before - 

This isn't a common thing for people to do, so having it part of the right-click options in the menu itself doesn't make much sense - it just adds clutter.

In addition to the methods you mentioned, in the menu editor you can also 'Edit Desktop File'.
