### ISSUE TITLE
Unable to move mouse over start menu

### ISSUE THREAD

**Issue by M4rc3lv** [linuxmint/cinnamon#10967]
```
Cinnamon version: 5.2.7
Distribution: Linux Mint 20.3 x86_64 (64 bit)
Graphics: Intel Iris Plus Graphics 650
 ```

**Issue**
Unable to move the mouse cursor from a left side panel into a top side panel.

**Steps to reproduce**
Create a vertical panel to the left of the screen and a horizontal panel to the top of the screen. Try to move the mouse over the vertical panel to the top: the mouse cursor is stuck and can not move to the top of the screen.

**Expected behaviour**
Able to move the mouse cursor to every part of my screen, including my start menu.

![stuck](https://user-images.githubusercontent.com/19297663/180841095-b7bade3b-cc76-4dde-a4e0-23d2e256d035.png)

**Comment by rlatosky** [comment]
Hi,

You should be able to have the mouse move over to the start menu from the left side panel by right-clicking on the empty space of the side panel and, through the panel settings window, toggling on "Allow the pointer to pass through the edges of panels".

![Screenshot from 2022-07-25 14-01-39](https://user-images.githubusercontent.com/71101970/180843956-e358b0b4-62b5-4d89-9f79-9a69e3382598.png)

**Comment by JosephMcc** [comment]
The instruction provided by @rlatosky should fix this.

**Comment by mtwebster** [comment]
There probably should not be a horizontal barrier there in this type of configuration - I think one should only ever be created along a common monitor edge.
