### ISSUE TITLE
Flipping not working on Cinnamon 5.4

### ISSUE THREAD

**Issue by rado84-github** [linuxmint/cinnamon#10969]
Cinnamon 5.4.8
Arch Linux
GTX 1660 Ti, nvidia-dkms 515.57

Flipping not working. It can be seen by creating an application profile and rules in nvidia-settings and enabling profile setting GLShowGraphicsOSD. That works only for native linux games. If flipping is working, top left corner reads "FLIP • VSYNC ON" all with green characters. However, on Cinnamon 5.4 it always reads "BLIT • VSYNC ON" which means flippin isn't working. I tried everything I could think of to make it work but it won't. And I'm pretty sure the problem is in Cinnamon bc I installed a separate instance of Arch with KDE Plasma and flipping is working perfectly fine in Plasma:

![Picture_created_28-07-2022_20-58-22](https://user-images.githubusercontent.com/41172201/181612513-876c9e34-ddb8-4e1b-bb0c-0831f9c7c703.png)

**Comment by leigh123linux** [comment]
Have you enabled nvidia-settings to autostart?, without that nvidia-settings isn't used.

https://pkgs.rpmfusion.org/cgit/nonfree/nvidia-settings.git/tree/nvidia-settings-user.desktop

The arch package looks deficient.

https://archlinux.org/packages/extra/x86_64/nvidia-settings/

**Comment by rado84-github** [comment]
I just did that, as you suggested. Still not working.

![Picture_created_31-07-2022_12-10-21](https://user-images.githubusercontent.com/41172201/182019391-c14f0c9f-e614-47d0-aca5-7225c750b57f.png)

**Comment by leigh123linux** [comment]
See https://github.com/linuxmint/cinnamon/issues/11008
