### ISSUE TITLE
Feature request: Make tilix Cinnamon's own terminal

### ISSUE THREAD

**Issue by Scorpion2185** [linuxmint/cinnamon#10965]
Instead of relying on `gnome-terminal` can you use the amazing [tilix](https://github.com/gnunn1/tilix)?

They are searching for maintainers:
> ⚠️ Maintainers Wanted
>     This project is looking for maintainers! At the moment, only very minimal maintenance is done, no new features will be implemented and pull-requests may be reviewed very slowly.
> 
>     If you are interested in giving Tilix some ❤️, please chime in! https://github.com/gnunn1/tilix/issues/1700

**Comment by Secret-chest** [comment]
It looks very gnome, and gnome terminal is good for most people.

**Comment by Scorpion2185** [comment]
`tilix` has more tabs on the same window, customizable shortcuts, background image, quake mode (drop-down terminal),  etc.
It may resemble `gnome-terminal` but it has a lot of nice features.

**Comment by Scorpion2185** [comment]
`tilix` has more tabs on the same window, customizable shortcuts, background image, quake mode (drop-down terminal) etc.
It may resemble `gnome-terminal` but it has a lot of nice features.

**Comment by Scorpion2185** [comment]
`tilix` has more tabs on the same window (opened at the same time), customizable shortcuts, background image, quake mode (drop-down terminal),  etc.
It may resemble `gnome-terminal` but it has a lot of nice features.

**Comment by Secret-chest** [comment]
> `tilix` has more tabs on the same window (opened at the same time), customizable shortcuts, background image, quake mode (drop-down terminal),  etc.
> It may resemble `gnome-terminal` but it has a lot of nice features.

That headerbar... We don't need a fancy tiled terminal to be Cinnamon's own one. If a novice user wants to learn the terminal / enter some commands, they should be able to do that.

**Comment by Scorpion2185** [comment]
You can remove the headbar and I don't see why a novice should have problems.
Like nemo has fancy features I think that tilix would be great for Cinnamon.
I hope that you won't start using nautilus for the same reason.

**Comment by Scorpion2185** [comment]
You can remove the headbar and I don't see why a novice should have problems.
There is an option to tiled tabs, that you switch as usually with CTRL+TAB, and/or not tiled tabs with an optional sidebar (F12) or traditional tab view.

Like nemo has fancy features I think that tilix would be great for Cinnamon.
I hope that you won't start using nautilus for the same reason.

**Comment by bitstrings** [comment]
> > `tilix` has more tabs on the same window (opened at the same time), customizable shortcuts, background image, quake mode (drop-down terminal),  etc.
> > It may resemble `gnome-terminal` but it has a lot of nice features.
> 
> That headerbar... We don't need a fancy tiled terminal to be Cinnamon's own one. If a novice user wants to learn the terminal / enter some commands, they should be able to do that.

I don't know about making Tilix the default terminal but sorry to say, but your argument is weak, abysmal really.

**Comment by JosephMcc** [comment]
Ok. I'm going to close this before it has a chance to turn disrespectful. There is no place for that here. In addition, I don't think there is any real interest in maintaining this as a terminal just for Cinnamon.
