### ISSUE TITLE
Workspaces not working correctly with corner hotspot

### ISSUE THREAD

**Issue by legion1978** [linuxmint/cinnamon#10964]
```
 * Cinnamon version (cinnamon --version) 5.4.3
    Stable - no PPA or nightly
 * Distribution - Manjaro 21.3.5 - 64bit
 * Graphics hardware *and* driver used 
   GeForce GTX 1050 Ti
   nvidia 515.57


 ```

**Issue**
If no window is open in the current workspace, activating the hotspot will lock the desktop view there. You can switch via keyboard to the next workspace with a window opened if it exists or be forced to restart cinnamon to unlock the workspace. It would seem the views stack upon each other (because the transparency of the screen gets darker). In this locked state, direct navigation to another workspace via keyboard shortcut wont work either.

If there is at least one window opened, everything works as expected

If there are more than one window open, the preview behaves erratically, not rising the thumbnails upon cursor hover, showing only one. this applies to both grid and single row expo view

finally, I have 16 workspaces and can only assign keyboard shortcut to 14 of them.. (this has always been like this, dont know why)

**Steps to reproduce**
1 config desktop hotspot to show expo
2 activate desktop hotspot with no application window opened in a workspace

**Expected behaviour**
you should be able to move back to desktop or to another workspace through mouse interaction, even with no application window opened

**Other information**
most extensions stopped working with latest upgrade..

**Configuration info, if applicable**
there are no extensions active atm.

(cinnamon:1313): Clutter-CRITICAL **: 07:07:34.522: clutter_input_focus_set_cursor_location: assertion 'clutter_input_focus_is_focused (focus)' failed

**Comment by mtwebster** [comment]
This is fixed as of 2ba4a7f3d46de8e2ca52 and is in 5.4.5 - try updating Cinnamon.

**Comment by legion1978** [comment]
thanks. it says "system is up to date" :C

![image](https://user-images.githubusercontent.com/331242/180783444-d289a738-6f15-4f7b-96bd-feded7e2676f.png)

**Comment by legion1978** [comment]
thank you. 
ended up replacing the files from your link :)
