### ISSUE TITLE
When main panel is on top, thumbnails stays bottom

### ISSUE THREAD

**Issue by zelimir86** [linuxmint/cinnamon#10976]
I'm using latest stable Linux Mint 21 Cinnamon which I just downloaded. Moved panel to top, but thumbnails stays on botttom.
![Screenshot from 2022-07-29 15-37-55](https://user-images.githubusercontent.com/16905384/181772713-c771cad1-4b43-432d-b41a-21c85274bae9.png)

**Comment by spamegg1** [comment]
Same as https://github.com/linuxmint/mint21-beta/issues/23
