### ISSUE TITLE
Playing fullscreen video in VLC does not work with fractional scaling

### ISSUE THREAD

**Issue by Alex-Bujorianu** [linuxmint/cinnamon#10973]
```
 * Cinnamon 5.4.3
 * Distribution - Manjaro
 * AMD Ryzen 5 4600H with Mesa from kernel 5.15
[xsession-errors-28-july.txt](https://github.com/linuxmint/cinnamon/files/9207797/xsession-errors-28-july.txt)
 * 64 bit
 ```

**Issue**
Playing fullscreen video in VLC causes all sorts of strange artifacts and flickering, if fractional scaling is used.

**Steps to reproduce**
Play any fullscreen video with VLC when fractional scaling is enabled. Playing the video with MPV also exhibits issues, but different issues: the scaling resets to 200% and then back again when exiting fullscreen.

**Expected behaviour**
Should work normally as it does without fractional scaling.

**Other information**
This appears to be a regression; I did not experience this issue with the previous version of Cinnamon, but I did experience it in Gnome 42. So the issue likely stems from Cinnamon rebasing to a newer version of Mutter.

**Comment by leigh123linux** [comment]
The issue doesn't reproduce here using the latest cinnamon releases, tested with Intel and Nvidia hardware.

```
cinnamon-5.4.8-1.fc36.x86_64
cinnamon-calendar-server-5.4.8-1.fc36.x86_64
cinnamon-control-center-5.4.4-1.fc36.x86_64
cinnamon-control-center-filesystem-5.4.4-1.fc36.x86_64
cinnamon-desktop-5.4.2-1.fc36.x86_64
cinnamon-desktop-devel-5.4.2-1.fc36.x86_64
cinnamon-menus-5.4.0-1.fc36.x86_64
cinnamon-menus-devel-5.4.0-1.fc36.x86_64
cinnamon-screensaver-5.4.1-1.fc36.x86_64
cinnamon-session-5.4.0-1.fc36.x86_64
cinnamon-settings-daemon-5.4.3-1.fc36.x86_64
cinnamon-settings-daemon-devel-5.4.3-1.fc36.x86_64
cinnamon-themes-2.0.3-1.fc36.noarch
cinnamon-translations-5.4.2-1.fc36.noarch
cjs-5.4.1-1.fc36.x86_64
muffin-5.4.4-1.fc36.x86_64
muffin-devel-5.4.4-1.fc36.x86_64
nemo-5.4.2-1.x86_64
nemo-compare-5.4.1-1.fc36.noarch
nemo-devel-5.4.2-1.x86_64
nemo-dropbox-5.4.1-1.fc36.x86_64
nemo-extensions-5.4.2-1.x86_64
nemo-fileroller-5.4.1-1.fc36.x86_64
nemo-image-converter-5.4.1-1.fc36.x86_64
nemo-preview-5.4.1-1.fc36.x86_64
nemo-python-5.4.1-1.fc36.x86_64
nemo-search-helpers-5.4.2-1.x86_64
nemo-terminal-5.4.1-1.fc36.noarch
```

Report the issue against mesa to your distro bug tracker.

Also try bugging your distro cinnamon maintainer to update cinnamon stack to the latest versions.

**Comment by Alex-Bujorianu** [comment]
> The issue doesn't reproduce here using the latest cinnamon releases, tested with Intel and Nvidia hardware.
> 
> ```
> cinnamon-5.4.8-1.fc36.x86_64
> cinnamon-calendar-server-5.4.8-1.fc36.x86_64
> cinnamon-control-center-5.4.4-1.fc36.x86_64
> cinnamon-control-center-filesystem-5.4.4-1.fc36.x86_64
> cinnamon-desktop-5.4.2-1.fc36.x86_64
> cinnamon-desktop-devel-5.4.2-1.fc36.x86_64
> cinnamon-menus-5.4.0-1.fc36.x86_64
> cinnamon-menus-devel-5.4.0-1.fc36.x86_64
> cinnamon-screensaver-5.4.1-1.fc36.x86_64
> cinnamon-session-5.4.0-1.fc36.x86_64
> cinnamon-settings-daemon-5.4.3-1.fc36.x86_64
> cinnamon-settings-daemon-devel-5.4.3-1.fc36.x86_64
> cinnamon-themes-2.0.3-1.fc36.noarch
> cinnamon-translations-5.4.2-1.fc36.noarch
> cjs-5.4.1-1.fc36.x86_64
> muffin-5.4.4-1.fc36.x86_64
> muffin-devel-5.4.4-1.fc36.x86_64
> nemo-5.4.2-1.x86_64
> nemo-compare-5.4.1-1.fc36.noarch
> nemo-devel-5.4.2-1.x86_64
> nemo-dropbox-5.4.1-1.fc36.x86_64
> nemo-extensions-5.4.2-1.x86_64
> nemo-fileroller-5.4.1-1.fc36.x86_64
> nemo-image-converter-5.4.1-1.fc36.x86_64
> nemo-preview-5.4.1-1.fc36.x86_64
> nemo-python-5.4.1-1.fc36.x86_64
> nemo-search-helpers-5.4.2-1.x86_64
> nemo-terminal-5.4.1-1.fc36.noarch
> ```
> 
> Report the issue against mesa to your distro bug tracker.
> 
> Also try bugging your distro cinnamon maintainer to update the cinnamon stack to the latest versions.

I see that you are running 5.4.8.1 whereas I have 5.4.3. Version 5.4.8.1 is available on Arch but not, it would seem, Manjaro stable. Ah well, another Manjaro issue I guess, though this bug should not have made it into Cinnamon in the first place.
