### ISSUE TITLE
Fractional scaling resets on resume after a lid-close-lid-open cycle

### ISSUE THREAD

**Issue by AsterisMono** [linuxmint/cinnamon#10985]
```
 * Cinnamon version - 5.4.8 
 * Distribution - Mint 21 Venessa
 * Graphics hardware *and* driver used - Vega 8 (R5-4600U), amdgpu
 * 32 or 64 bit - 64bit
 * Attach ~/.xsession-errors, or /var/log/syslog
 ```

**Issue**
Fractional scaling resets on resume after a lid-close-lid-open cycle.

**Steps to reproduce**
1. Set monitor scale to 125%.
2. Close laptop lid.
3. Reopen laptop lid, login. (On login screen sometimes there are weird black stripes flashing.)
4. Monitor scale resets to 100%.

**Expected behaviour**
Monitor scale setting should persist.

**Other information**
- Monitor scale setting will reset **only when**:
  - Using a fractional scaling factor, like 125%. (200% works fine and can persist across lid events.)
  - And after a **lid-close-lid-open** cycle. (That is, manually triggering system sleep with `systemctl suspend` will NOT cause the setting to reset.

 - Changing mem_sleep mode between S2Idle and S3(deep) cannot address the problem.

 - I have deleted ~/.xsession-errors and triggered the bug once to narrow down error log, but no new .xsession-errors file was created after triggering the bug.

 - [/var/log/syslog](https://pastebin.com/SppAgVJs), with several suspension cycle in it.

 - May also see #10879 and #9483, very similar problems.

Also I am willing to provide any extra info as you request, just let me know.

**Comment by SethosII** [comment]
@AsterisMono I couldn't find a related issue in [cinnamon-screensaver](https://github.com/linuxmint/cinnamon-screensaver). Where is it tracked now? As a workaround I set this: `gsettings set org.gnome.desktop.interface scaling-factor 1` (the default value is 0).

**Comment by AsterisMono** [comment]
> @AsterisMono I couldn't find a related issue in [cinnamon-screensaver](https://github.com/linuxmint/cinnamon-screensaver). Where is it tracked now? As a workaround I set this: `gsettings set org.gnome.desktop.interface scaling-factor 1` (the default value is 0).

uh, I have left cinnamon for i3 for a while, and forgot to open that extra issue. Maybe you can open one in cinnamon-screensaver and copy-paste or reference _this_ issue there.
