### ISSUE TITLE
After 5.4 some applications always open fullscreen - did not before

### ISSUE THREAD

**Issue by jonnyabu1** [linuxmint/cinnamon#10987]
```
 * Cinnamon version 5.4.8
 * Distribution - Manjaro
 * Graphics hardware *and* driver used - NVidia 1080 GTX - NVidia driver 515.57
 * 64 bit
 ```

**Issue**
Some applications always open full-screen instead of a set size after 5.4 update.  The main culprit is things like Firefox or Evolution or Chrome or Vivaldi that I can think of off the top of my head.  Others do that too but did not before 5.4.  Not game breaking as I simply go and click the Maximize button to get it to shrink back to the size I had it before.  Just annoying to have to do that.  Oddly, not all applications do this.  Like, three of the four browsers I use do that, but Brave correctly opens the same size as when I closed it.

**Steps to reproduce**
Open Firefox and it'll be full-screen.  Open Evolution and it'll be full-screen.  Open Chrome and it'll be full-screen.  Open Vivaldi and it'll be full-screen

**Expected behaviour**
Application opens at the size I had it when it was closed, as was the previous behavior prior to 5.4

**Other information**

**Configuration info, if applicable**

```

Please paste here

```

**Comment by rado84-github** [comment]
I don't have such a problem with any of the listed applications, esp. Firefox since I use it every day. It always opens maximized (I like it that way), never fullscreen. I would guess it's a local problem for your distro or computer only.

**Comment by jonnyabu1** [comment]
I guess I misspoke. It opens maximized, not like a F11 Fullscreen. I myself
do not desire this behavior, and it did not exist until 5.4

**Comment by mtwebster** [comment]
Firefox and Chromium (and probably most other browsers since they're usually chromium-based) remember their size and whether or not they were maximized from session to session. If you exit them while they're maximized, the next time you launch they will be also. This is the behavior I observe currently in 5.4 (the same as prior versions).

Do you have any extensions or 3rd party software installed that may be related to window management/manipulation?

**Comment by jonnyabu1** [comment]
I do not ever maximize them. This is the reason for my big report.  I do
not intentionally maximize nearly any application nor do I want them to be.

Now when they open I have to unmaximize them. They stay that way until I
close them and then the next time I open them, they are again maximized. So
it is not from me maximizing them.

This is not behavior that occurred before. My supposition is with Muffin
being closer to Mutter, this might be something that Gnome does and now
Cinnamon had taken on this behavior.

It is not game breaking but I am reporting it because it is an annoyance to
me.  If I close an application maximized, stay that way when I reopen. If I
close unmaximized then stay that way. Which is what happened before 5.4

**Comment by mtwebster** [comment]
I'm not trying to dispute your reasoning or experience.

The fact it only appears to happen for you at this time suggests there may be some local factor at play here, which is why I asked about other programs.

**Comment by rado84-github** [comment]
In your profile directory (this is mine: ~/.mozilla/firefox/valso.default-release) find and delete the file xulstore.json, then run the browser again to see if ti opens the way you want it to be. But this for Firefox only. I don't use Chrome or any other browser (I use Chromium but only to compare website performances to Firefox), so IDK how to do that for them.

**Comment by jonnyabu1** [comment]
Yeah no worries.  I wasn't offended or anything.  Just trying to make sure I was being clear.

So, I have debated if it could be particular to my system, but I have observed this on my work desktop, home desktop, laptop, and a couple of VMs.  All are Manjaro except one of the VMs is Arco.  While it is possible something there is causing it, I figured that would be a lot of systems doing that so perhaps not.  I could very well be wrong but I don't know if I am.

I know Evolution opens Maximized now.  Remmina as well along with all RDP sessions I open with it ( pop out windows ).  Those are the others I can think of off the top of my head at the moment.

**Comment by jonnyabu1** [comment]
Deleting the xulstore.json did seem to work on the work desktop.  I shall test at home as well.  Thank for that suggestion and we'll see how that goes!

**Comment by jonnyabu1** [comment]
Interesting.  Not in a VM though

**Comment by jonnyabu1** [comment]
So yeah in the VM, it always recreates it with "Maximized" as the value.  The {"sizemode":"maximized",...} section.

Odd.  I tried to specify a size but it just writes over that and reverts to Maximized

**Comment by mtwebster** [comment]
Run:
```
gsettings set org.cinnamon.muffin auto-maximize false
```

This is a new setting. Do you run these apps nearly monitor-sized? When I was trying to reproduce this I was sizing the windows down fairly small or I may have noticed this.  I may disable it by default.

**Comment by jonnyabu1** [comment]
Well, yes that seemed to be it!  In the VM I discussed earlier now FF opens the size I closed it with.  On the work desktop, Evolution is now opening at the correct size as well as Remmina RDP sessions.  Outstanding.  I appreciate that suggestion.

**Comment by jonnyabu1** [comment]
Worked on my desktop as well.  Closing as changing the dconf setting prevents apps from always opening up maximized.  Thanks very much for providing that
