### ISSUE TITLE
Missing animations on some menus

### ISSUE THREAD

**Issue by Rantyrant** [linuxmint/cinnamon#10983]
```
 * Cinnamon version: 5.4.8
 * Distribution: Linux Mint 21
 * Graphics hardware *and* driver used: AMD RX 6900 XT + amdgpu
 * 32 or 64 bit: 64bit
 * Attach ~/.xsession-errors, or /var/log/syslog
 ```

**Issue**
Cinnamon previously had a nifty animation when you opened drop down menus in apps (if you click File, Edit, etc, in e.g. Nemo), but it seems to missing now on Cinnamon 5.4.8/Linux Mint 21.

**Steps to reproduce**
Open up Nemo (or other app) and hit the Files or Edit, and observe the (lack of) animation.

**Expected behaviour**
That said menus are animated.

**Other information**
Examples of the animations I'm talking about:
Linux Mint 20.3 edge
https://imgur.com/vTI2PoF

In Linux Mint 21:
https://imgur.com/v8uj17v

**Comment by Secret-chest** [comment]
@mtwebster Still not fixed.
