### ISSUE TITLE
Question about .desktop file - bug or intended?

### ISSUE THREAD

**Issue by rado84-github** [linuxmint/cinnamon#10991]
I know the title isn't clear enough, so let me explain what the problem is. Normally, when you right click on an ISO file, you see 2 functions - "Mount an ISO image" and "Burn an ISO image". In the past I've always been able to change the name of these two functions by editing their .desktop files and placing them in ~/.local/share/applications. But quite recently when I changed their names, these two functions disappeared from the right click menu of an ISO file.
So, what I need to know is:
1. Is there a way to change their names (because their translated form in my native language is too long) and keep them visible in the right click menu?
2. Is that behaviour a bug or is their disappearance intended to be like that, after changing their names? If it's a bug, I'll change this question into a proper bug report.

**Comment by mtwebster** [comment]
What desktop (or more specifically, file manager) are you using? Cinnamon/Nemo keep these files in different locations, though they're just as easy to modify. Mate uses the gnome disks utility. Xfce uses .desktop files in /usr/share/applications.

**Comment by rado84-github** [comment]
The original .desktop files are in /usr/share/applications but in order to avoid them being changed at updates, I copy them to ~/.local/share/applications and then modify them to change the names of the functions.
Here they are. As you can see, they ARE in the root dir for applications. The file manager is PCManFM but these functions, whenever their names are changed, also disappear from Nemo as well, which is why I asked this question.
They have the Bulgarian names, so you probably won't understand the text but that's what they mean: "Mount an ISO image" and "Burn an ISO image".

![Picture_created_01-08-2022_16-08-13](https://user-images.githubusercontent.com/41172201/182155813-5b960f55-044d-4cb9-a59c-d3b184efb2a9.png)

**Comment by mtwebster** [comment]
Go into `~/.local/share/applications` in a terminal, and run:
```
update-desktop-database .
```

This ordinarily wouldn't need to be done if you were just adding a custom *visible* entry in the start menu, but in this case you need to refresh the mimetype cache so it knows there are new programs available.

**Comment by rado84-github** [comment]
That worked! But it only worked after I entered the command like this:
`$ update-desktop-database ~/.local/share/applications`
Without the specific address it was trying to update the root location for apps which can not be done as the regular user.

**Comment by mtwebster** [comment]
The `.` was deliberate after the command (and already being in that folder) - I usually post what ever I just ran myself, sometimes it's not always the most clear and concise approach I suppose.

Glad it worked, closing this.
