### ISSUE TITLE
Screenshot app back button

### ISSUE THREAD

**Issue by alexnoise79** [linuxmint/cinnamon#10995]
```
 * Distribution - (Mint 21)
 ```

**Issue**
Screenshot app has no button back

**Steps to reproduce**
- Open Screenshot app
- Press "Take screenshot"
- available options are Cancel, Copy to clipboard, Save
- on click Cancel the window is closing and is not possible to take another screenshot

**Expected behaviour**
a Button back should be provided to give the possibility to the user to take another screenshot

Cannot make a screenshot of the screenshot app (sorry)

**Comment by namanlp** [comment]
Hi there, 
The actual application for taking screenshot is gnome-screenshot
https://github.com/GNOME/gnome-screenshot

Also, I am **unable to reproduce the bug** on Garuda Linux Cinnamon Edition with `gnome-screenshot 41.0+r25+g45f08f0-1` and `cinnamon 5.4.9-1`

![2022-08-05-01-01-39](https://user-images.githubusercontent.com/66401604/182940761-652d4f20-ecbb-43e3-a777-eeedf466758b.gif)

**Comment by alexnoise79** [comment]
my version on Cancel closes the window.

will try to open on the other repo, thanks

**Comment by JosephMcc** [comment]
As noted, this isn't a cinnamon issue but an issue with gnome-screenshot.
