### ISSUE TITLE
Windows minimize not possible

### ISSUE THREAD

**Issue by DerKlausner** [linuxmint/cinnamon#11005]
Hallo

If open Nemo (as example) i can minimize the Nemo Windows with the botton. Than the Nemo Windows is minimize i change my workplace from 1 to 2 and so on. Than i maximize the Nemo Windows. Okay. But if i minimize the Nemo Windows again the Windows is frozen. if restart Cinnamon the Nemo Windows is minimize and i can keep working.

`System:
  Kernel: 5.15.0-43-generic x86_64 bits: 64 Desktop: Cinnamon 5.4.9
    Distro: Linux Mint 21 Vanessa
Machine:
  Type: Virtualbox System: innotek GmbH product: VirtualBox v: 1.2
    serial: <superuser required>
  Mobo: Oracle model: VirtualBox v: 1.2 serial: <superuser required>
    BIOS: innotek GmbH v: VirtualBox date: 12/01/2006
Battery:
  ID-1: BAT0 charge: 50.0 Wh (100.0%) condition: 50.0/50.0 Wh (100.0%)
    volts: 10.0 min: 10.0
CPU:
  Info: quad core model: 11th Gen Intel Core i7-1165G7 bits: 64 type: MCP
    cache: L2: 5 MiB
  Speed (MHz): avg: 2803 min/max: N/A cores: 1: 2803 2: 2803 3: 2803
    4: 2803
Graphics:
  Device-1: VMware SVGA II Adapter driver: vmwgfx v: 2.19.0.0
  Display: x11 server: X.Org v: 1.21.1.3 driver: X: loaded: vmware
    unloaded: fbdev,modesetting,vesa gpu: vmwgfx resolution: 2560x1600~60Hz
  OpenGL: renderer: SVGA3D; build: RELEASE; LLVM; v: 2.1 Mesa 22.0.5
Audio:
  Device-1: Intel 82801AA AC97 Audio driver: snd_intel8x0
  Sound Server-1: ALSA v: k5.15.0-43-generic running: yes
  Sound Server-2: PulseAudio v: 15.99.1 running: yes
  Sound Server-3: PipeWire v: 0.3.48 running: yes
Network:
  Device-1: Intel 82540EM Gigabit Ethernet driver: e1000
  IF: enp0s3 state: up speed: 1000 Mbps duplex: full mac: <filter>
  Device-2: Intel 82371AB/EB/MB PIIX4 ACPI type: network bridge
    driver: piix4_smbus
Drives:
  Local Storage: total: 48 GiB used: 21.3 GiB (44.4%)
  ID-1: /dev/sda vendor: VirtualBox model: VBOX HARDDISK size: 30 GiB
  ID-2: /dev/sdb vendor: VirtualBox model: VBOX HARDDISK size: 18 GiB
Partition:
  ID-1: / size: 28.87 GiB used: 12.88 GiB (44.6%) fs: ext4 dev: /dev/sda5
  ID-2: /boot/efi size: 511 MiB used: 4 KiB (0.0%) fs: vfat dev: /dev/sda1
Swap:
  ID-1: swap-1 type: file size: 4 GiB used: 0 KiB (0.0%) file: /swapfile
Sensors:
  Message: No sensor data found. Is lm-sensors configured?
Info:
  Processes: 247 Uptime: 43m Memory: 3.83 GiB used: 1.17 GiB (30.6%)
  Shell: Bash inxi: 3.3.13

[xsessionerrors.txt](https://github.com/linuxmint/cinnamon/files/9274727/xsessionerrors.txt)
`

**Comment by CuBeRJAN** [comment]
I'm having the same issue, happens after switching workspaces with all windows minimized
