### ISSUE TITLE
Switch to libsoup3

### ISSUE THREAD

**Issue by jbicha** [linuxmint/cinnamon#11001]
**Issue**

GNOME is switching its core apps and libraries to libsoup3 for the GNOME 43 release.

It's not possible for apps to link against both libsoup2 and libsoup3 simultaneously. And distros aren't going to keep libsoup2 versions of things like evolution-data-server around. Therefore, Cinnamon will need to switch to libsoup3 to remain available and usable in distros.

Several libraries and apps provide an option to build against either libsoup2 or libsoup3. I think you'll want to do this because you want the latest Cinnamon to work on your Linux Mint base and also on the latest distros.

**Other information**

- https://libsoup.org/libsoup-3.0/migrating-from-libsoup-2.html
- https://gitlab.gnome.org/GNOME/libsoup/-/issues/218
- https://people.canonical.com/~ubuntu-archive/transitions/html/libsoup3.html (This shows things with a direct dependency on libsoup but indirect dependencies aren't shown.)

**Comment by leigh123linux** [comment]
Cinnamon doesn't use libsoup directly

```
libtimezonemap-0.4.5.1-11.fc36.x86_64 requires libsoup-2.4.so.1()(64bit)
libtimezonemap(x86-64) is needed by (installed) cinnamon-5.4.9-1.fc36.x86_64
```

**Comment by mtwebster** [comment]
we do: https://github.com/linuxmint/cinnamon/blob/master/src/cinnamon-util.h#L9

**Comment by leigh123linux** [comment]
@mtwebster  It doesn't look like soup is needed, Clem removed the need years ago.

see
https://github.com/linuxmint/cinnamon/commit/1c0c12014b54af946f987b158d2858d62817dabb#diff-ef8d5a0d19dc13739adb8bf6316622f8fb7580cd8841e5ec654aff5dabb124f2

 and the gnome commits

https://github.com/GNOME/gnome-shell/commit/96396163cf7f26f836489e49e0955b59c408d91d

and

https://github.com/GNOME/gnome-shell/commit/3e29ab54419cf4aa11da87c53cba64ae25560907

**Comment by ItzSwirlz** [comment]
Oh wow, I thought honestly the function would be fine to stay and that all that was needed was a meson dependency bump. If it's dead code, yeet it away. I think the spice harvester is using something else and I couldn't find any other cinnamon dependencies.



> Only one extension using it, though, but it's important (xkcd)

Mind sharing a link?

CC @Fantu + debian cinnamon team

**Comment by leigh123linux** [comment]
> Oh wow, I thought honestly the function would be fine to stay and that all that was needed was a meson dependency bump.

I tried that, it fails to compile due to soup changes.


```
../src/cinnamon-util.c: In function ‘cinnamon_write_soup_message_to_stream’:
../src/cinnamon-util.c:649:17: error: invalid use of incomplete typedef ‘SoupMessage’ {aka ‘struct _SoupMessage’}
  649 |   body = message->response_body;
```

Then I noticed the function was removed in the cinnamon js code 11 years ago :-)

**Comment by Fantu** [comment]
leigh123linux solved in cinnamon with https://github.com/linuxmint/cinnamon/pull/11002

about cinnamon deps:
- gir1.2-edataserver-1.2 have libsoup2 dep
- gir1.2-timezonemap-1.0 also have its library that have libsoup2 dep

what to do about calendar server part?

libtimezonemap was adopted in debian by cinnamon team years ago but upstream was missed by long time, I did only small packaging improvements recently, I also taken a look for possible timezones updated but except 2 files that can be easy/fast updated the images instead need to updated manually and other things so I not didn't as I don't have enough experience related and time I had given up to invest the time better to do more other things
I don't know if I'll have time recently to try to do d/patches for the migration to libsoup3 libtimezonemap.
Is present an alternative still updated (for updated timezones) for replace libtimezonemap?

**Comment by mtwebster** [comment]
> what to do about calendar server part?

I see e-d-s has switched to libsoup3 just recently, but our calendar server should be unaffected as far as I know, or am I missing something? We interact only with e-d-s there.

**Comment by Fantu** [comment]
sorry, I only checked fast https://tracker.debian.org/pkg/evolution-data-server that still using libsoup2 and no new upstream version reported by d/watch
now checking upstream I saw https://gitlab.gnome.org/GNOME/evolution-data-server/-/merge_requests/85 also you reported so will be solved in next stable version

so remain only libtimezonemap

**Comment by jbicha** [comment]
Yes, I have the GNOME debian/watch  watch files only look for stable releases.

evolution-data-server 3.45.2 is landing in Debian experimental now. Hopefully that helps your testing.

**Comment by ItzSwirlz** [comment]
Here is a libtimezonemap patch I made. No, I don't expect it to work but initial reviews would be great.
[libsoup3.diff.txt](https://github.com/linuxmint/cinnamon/files/9274106/libsoup3.diff.txt)

**Comment by Fantu** [comment]
Thanks @ItzSwirlz I did a fast testing build using your patch:
https://salsa.debian.org/cinnamon-team/libtimezonemap
http://debomatic-amd64.debian.net/distribution#unstable/libtimezonemap/0.4.6-4~/
build was successfull and I installed it and datetime part in cinnamon-settings that use (if I remember good) it seems still show the timezone map and correct data but I don't have time to test it good now or check if the patch needs improvements

**Comment by ItzSwirlz** [comment]
No problem - but I don't expect the patch to be 100% standalone complete, that's why I'm asking for reviews but I'm glad it doesn't majorly break anything.

**Comment by mtwebster** [comment]
@ItzSwirlz https://github.com/linuxmint/cinnamon-spices-desklets/tree/master/xkcd%40rjanja - it's currently broken though, non-soup-related.

**Comment by Fantu** [comment]
@mtwebster I saw https://github.com/linuxmint/cinnamon/commit/76224fe409d074f8a44c70e4fd5e1289f92800b9 that readd libsoup2 so this is not solved
from a grep I found use of soup only in https://github.com/linuxmint/cinnamon/blob/master/docs/search-providers-examples/wikipedia@cinnamon.org/search_provider.js
but I not understand the reason to add in js/ui/environment.js that cause still have libsoup2 as deps, is there other things I not found or don't know?

**Comment by mtwebster** [comment]
There are a fair amount of third party applets that use soup. You can't currently load both soap2 and 3 simultaneously, so until we can take care of that we'll need to depend on the old bindings.

**Comment by Fantu** [comment]
@mtwebster thanks for reply, I saw them now :( https://github.com/linuxmint/cinnamon-spices-applets/search?q=soup https://github.com/linuxmint/cinnamon-spices-desklets/search?q=soup

**Comment by jbicha** [comment]
On the Debian Testing / Ubuntu 22.10 side, we're going to have to bump cinnamon to libsoup3.0 soon despite the existence of third party applets. I expect that I will need to do this for Ubuntu 22.10 very soon because Feature Freeze is in less than 2 weeks and it's best if major transitions (like this big GNOME 43 core libraries switch to libsoup3) are finished or at least well in progress by then.

I think Fedora 37 has a similar deadline is in just over a week. Sorry for the time pressure.

**Comment by Fantu** [comment]
for now cinnamon without soup2 is in experimental, today or tomorrow probably I'll migrate to unstable
anyway applets and desklets that use it are many and I was thinking to apply latest patch for readd it, but probably I'll wait instead that users report it after migrate to unstable/testing
as wrote in https://github.com/linuxmint/cinnamon/issues/11001#issuecomment-1207192183 about libtimezonemap there is a patch in git but I did only a fast test, I don't know if I'll have time for a good check in these days, if someone do it please tell me and I'll upload it to unstable

**Comment by jbicha** [comment]
I don't think you should migrate Cinnamon built against libsoup3 to experimental yet. Maybe it runs for you because you're using evolution-data-server from experimental? The Debian transition bug is https://bugs.debian.org/1016706 It may take a few weeks for the transition to be ready for Debian Testing.

libtimezonemap can be uploaded to experimental but it shouldn't go to Unstable unless Cinnamon does.

**Comment by Fantu** [comment]
I started to migrate cinnamon 5.4 components from experimental to unstable 2 hours ago even if take very long time to process
cinnamon 5.4.10-1 don't build against libsoup3 but removed libsoup2 and itself don't require it, what I thinked was of readd runtime deps to libsoup2 and upstream commit to avoid issue for users that have applets/desktlets installed using it
anyway I suppose the applet/desklet issues is caused by not require specific libsoup2 and https://github.com/linuxmint/cinnamon/commit/76224fe409d074f8a44c70e4fd5e1289f92800b9 is only a workaround, is correct?
on my sid/experimental install I'm using for testing there is still gir of libsoup2 installed and there I don't see issue with applets using it even without apply https://github.com/linuxmint/cinnamon/commit/76224fe409d074f8a44c70e4fd5e1289f92800b9
but I am afraid that at least the dependency on gir soup2 is necessary or users who use such applets could remove the package if it was not needed for anything else (for now it is needed for libtimezonemap) or in clean installations do not install it (always when there are no more dependencies than it require)

**Comment by Fantu** [comment]
specify soup version required in applet probably is better that on cinnamon and probably as wrote here trying to support both version in applet is needed or in any case (only version 2.4 or only 3) will make it don't working on part of users
(https://github.com/linuxmint/cinnamon-spices-applets/pull/4433#issuecomment-1220613171)
or is there a better idea?

**Comment by Fantu** [comment]
hi, I saw that many spices added soup3 support, I didn't check if all did and are working correctly (probably I don't have time to do it), someone did it and can tell me please?
I need to know if possible migrate libtimezonemap with soup3 from experimental to unstable and change cinnamon deps from soup2 to soup3 before debian 12 freeze without cause issue to users

**Comment by Moilleadoir** [comment]
I still see `libsoup` (2.74.3-3) as a dependency of `timezonemap` which is a dependency of `cinnamon`. So this is still an issue?

**Comment by Fantu** [comment]
timezonemap 0.4.6-7 in debian (from Debian 13) and derivates was ported to libsoup3, debian 12 still have soup2 because first port to soup3 patch was broken and revert.

**Comment by Moilleadoir** [comment]
Ah OK, on Manjaro Cinnamon the `timezonemap` package version is 0.4.5.2-2

**Comment by Fantu** [comment]
From a fast search in Arch there is an issue open related: https://gitlab.archlinux.org/archlinux/packaging/packages/timezonemap/-/issues?show=eyJpaWQiOiIxIiwiZnVsbF9wYXRoIjoiYXJjaGxpbnV4L3BhY2thZ2luZy9wYWNrYWdlcy90aW1lem9uZW1hcCIsImlkIjoxOTYxNzd9
and an MR for solve it: https://gitlab.archlinux.org/archlinux/packaging/packages/timezonemap/-/merge_requests/1

**Comment by Moilleadoir** [comment]
Thanks!
