### ISSUE TITLE
[Regression] Ctrl+Alt+Shift+Tab doesn't switch between windows

### ISSUE THREAD

**Issue by awsms** [linuxmint/cinnamon#11004]
Running Cinnamon 5.4.9 on EndeavourOS

I'm often holding the Ctrl key when Alt-Tabbing because that's also the key used for switching tabs in web browsers. I recently noticed that Ctrl+Alt+Shift+Tab isn't recognized anymore, Ctrl+Alt+Tab still works however.

**Comment by awsms** [comment]
Reassigned manually in the keyboard shortcuts menu

**Comment by mtwebster** [comment]
The 'auto reverse with shift' thing is no more - I made sure to set 'Cycle backwards through open windows' shortcut shift-alt-tab so hopefully no one would notice. Maybe you had set it to something else at some point?

**Comment by awsms** [comment]
>Maybe you had set it to something else at some point?

Actually I imported my old keybinds from my Linux Mint install, so that's definitely possible.
However I noticed Ctrl+Alt+Shift toggles between all open windows on all workspaces, even if the keybind is set to "Cycle through open windows" in the Shortcuts menu. Not sure if this could be correctly remapped.

**Comment by DirkHaar** [comment]
@awsms You find ALT-Tab handling in the settings, "Windows", tab "Alt-Tab".

**Comment by tanev** [comment]
It is reliably reproducing with a clean Mint 21 ISO, steps in my case (5.4.12+vanessa):
- open a few applications on the local workspace (i.e. a nemo, a terminal and a browser instance)
- cycle forward and backward with Alt+Tab and Alt+Shift+Tab works as expected
- send one of them to a remote workspace (e.g. the browser window)
- forward cycle works normally with Ctrl+Alt+Tab, but backwards with Ctrl+Alt+Shift+Tab no longer cycles backwards.

I didn't know I've got so used to this feature, until I've realized I am no longer able to use it :)

**Comment by mtwebster** [comment]
As a partial workaround, run this from a terminal:

```
gsettings set org.cinnamon.desktop.keybindings.wm switch-panels-backward "['<Shift><Control><Alt>Tab']"
```

This will restore the reverse keybinding, *but only after the switcher has been opened by the forward one. To fix this, we need to wait on https://github.com/linuxmint/cinnamon/commit/325d7529e877ab50014699e229c062b323c43367 to make it into a new release.

If you're adventurous you could edit that file yourself (`/usr/share/cinnamon/js/ui/appSwitcher/appSwitcher.js`), as it's a fairly simple couple of changes.
