### ISSUE TITLE
panel menus drop behind panel

### ISSUE THREAD

**Issue by TeamFahQ** [linuxmint/cinnamon#11007]
```
 * Cinnamon 5.4.9
   - NOT using daily builds
 * OS: Linux Mint 21 x86_64
 * NVidia GeForce RTX 3060 *and* NVIDIA-SMI 470.141.03   Driver Version: 470.141.03   CUDA Version: 11.4
 * 64 bit
 * Issue does not appear in any logs
 ```

**Issue**
This only occurs on items, i.e. calendar, menu, printer, etc that has menu popup on LEFT click. Right click contexant menus are unaffected.
When left clicking on anything that has a menu on the panel with auto hide or intelligent hide enabled, the menu drops down a just a bit below the panel. It is most noticable when left clicking on menu or any default item on the right side of panel (sorry forgot what those are called), i.e. calendar,  and then moving mouse to the menu that appears.

**Steps to reproduce**
on menu or any default item on the right side of panel (sorry forgot what those are called), i.e. calendar,  and then moving mouse to the menu that appears

**Expected behaviour**
for the menu that appears to stay

**Other information**

**Configuration info, if applicable**
If this bug report is related to an Applet, Desklet or Extension, please paste (or use a pastebin service) the offending extension's settings, if it has any.  You can obtain this by opening its configuration, clicking the 'hamburger' button in the upper-right corner of the window, and selecting "Export to a file". **Please be sure to review the contents and remove any personal data it may contain.**

```

Please paste here

```

**Comment by mtwebster** [comment]
I can't reproduce this - is there any chance you can take a video (or maybe even a screenshot or two) of this happening? I'm not entirely sure what I'm looking for - do the popups become completely obscured? Or just 'attached' to the monitor edge instead of where the panel would be when visible? Or something in between?

**Comment by TeamFahQ** [comment]
Sure. First pic is of what I expect to see. The other 2 are what happens
![Screenshot from 2022-08-09 05-59-14](https://user-images.githubusercontent.com/2103628/183632262-b47f05ad-e74e-4343-8f59-1b1bae6b6757.png)
.
![Screenshot from 2022-08-09 05-59-28](https://user-images.githubusercontent.com/2103628/183632310-a7bdf360-8944-44b6-bd57-89b511b02e14.png)

![Screenshot from 2022-08-09 05-58-11](https://user-images.githubusercontent.com/2103628/183632330-78004fe8-68d5-4062-9b23-2e74b5191fae.png)

**Comment by TeamFahQ** [comment]
That is a theme I wrote, inspired by Mint Y Dark Red and Peppermint Dark. Subsequently, it does not happen with stock themes. Looks like I need to update some stuff. I apologize, I didn't even consider this might be theme related.
