### ISSUE TITLE
Feature request - user-adjustable window snapping

### ISSUE THREAD

**Issue by foley2k2** [linuxmint/cinnamon#11009]
```
 * Cinnamon version (cinnamon --version)
   - Please specify if you are using the daily builds PPA
     (https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds).
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
 * Graphics hardware *and* driver used
 * 32 or 64 bit
 * Attach ~/.xsession-errors, or /var/log/syslog
 ```
I'm on cinnamon 4.6.7, Mint 20 64-bit

**Issue**
Window snapping isn't narrow enough.
I'm using a 49" ultrawide monitor at 5120x1440 resolution and would like to have 4-6 horizontal window snap zones.
This monitor is like having two 1440p monitors with no bezel.

**Steps to reproduce**
press the 'window' key and arrow to move a window left or right
window + up and down work too - either half the screen or all the screen

**Expected behaviour**
Window snaps to the nearest zone as determined by the upper-left corner.
It currently only has 2 zones that are half the screen.
More would be MUCH better and similar to how ctrl+alt+arrows work now.

**Actual behaviour**
Snaps to half the screen or all the screen.

**Configuration info, if applicable**
n/a - new feature

**Comment by Secret-chest** [comment]
Use CinnTile extension, you can make up to 20x20 zones

**Comment by foley2k2** [comment]
I found gTile - works differently and uses a different keyboard/mouse interaction.
It's better than nothing though.
Listed here: https://cinnamon-spices.linuxmint.com/extensions/popular
Is there something else out there?

This request doesn't need a mouse.

**Comment by mtwebster** [comment]
This isn't going to happen in core Cinnamon - the way tiling is currently implemented it would require a complete rewrite and end up twice as complicated - not that it couldn't be done, it's just not worth the time and effort it would require, for only a handful of users.

gTile or something similar is really the solution here, short of switching to a different desktop/window manager that's tiling-centric - there are lots of these out there, though of course with tradeoffs compared with a traditional desktop like Cinnamon.
