### ISSUE TITLE
Built-in OpenJDK is too old

### ISSUE THREAD

**Issue by Rudxain** [linuxmint/cinnamon#11000]
```
 * Cinnamon version 5.2.7
   - Please specify if you are using the daily builds PPA: no
 * Distribution - Mint 20.3
 * Graphics hardware *and* driver used: (irrelevant, but here it is) Intel Corporation 3rd Gen Core processor Graphics Controller
 * 64 bit
 * Attach ~/.xsession-errors, or /var/log/syslog (irrelevant, and both probably contain private info)
 ```

**Issue**
Client> Error: LinkageError occurred while loading main class
Client> java.lang.UnsupportedClassVersionError: Main has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0
Fatal Error: java.io.IOException: Stream closed
Fatal Error: java.io.IOException: Stream closed
Fatal Error: java.io.IOException: Stream closed
Fatal Error: java.io.IOException: Stream closed
Fatal Error: java.io.IOException: Stream closed
Fatal Error: java.io.IOException: Stream closed
Fatal Error: java.io.IOException: Stream closed
Fatal Error: java.io.IOException: Stream closed
Fatal Error: java.io.IOException: Stream closed
Program ended incorrectly (exit code 1)

**Steps to reproduce**
Run any class file compiled by JDK 17 or 18

**Expected behaviour**
It should run without problems

**Other information**
I got this error some days ago, then I updated OpenJDK today using the Update Manager, but the problem persists. It seems I need to manually update to a major version. But how do I do that? I installed OracleJDK and the problem was gone (because it was a more recent version), then I uninstalled and the problem came back (as expected)

[Relevant Reddit post](https://reddit.com/r/linuxmint/comments/wef473/openjdk_is_too_old_for_my_needs)

**Configuration info, if applicable**
None

**Comment by ItzSwirlz** [comment]
How is this a cinnamon related issue? Did you try starting a program in Cinnamon that worked fine in other DEs?

**Comment by Rudxain** [comment]
> How is this a cinnamon related issue?

It probably isn't specific to Cinnamon. I didn't know where was the best place to post this.

> Did you try starting a program in Cinnamon that worked fine in other DEs?

Currently, no. But I may do so in the future if it seems necessary

**Comment by ItzSwirlz** [comment]
This is a mint problem with their repos - where to report I'm not sure but there are different versions of OpenJDK in repos, like openjdk-8, 11 and 16 I believe are the ones in Ubuntu Jammy repositories

**Comment by Rudxain** [comment]
Thanks. As a quick-fix, I'll try to change the source repo (IDK how, I'll search it)

**Comment by Rudxain** [comment]
Wait, [Ubuntu now ships OpenJDK18](https://discourse.ubuntu.com/t/jammy-jellyfish-release-notes/24668) (section: Toolchain Upgrades), so when I upgrade to Mint 21, the problem *should* be fixed!

I'll close this issue for now. If the issue persists I'll open again

**Comment by Rudxain** [comment]
I was wrong, v21 **still** uses OpenJDK-11. In the meantime, which PPA should I use to keep it updated?

**Comment by leigh123linux** [comment]
Report it to https://github.com/linuxmint/linuxmint/issues
