### ISSUE TITLE
Regression: various keyboard shortcuts erroneously produce notifications

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/cinnamon#11018]
```
 * Cinnamon version (cinnamon --version): 5.4.9
   - Please specify if you are using the daily builds PPA: no.
 * Distribution: Mint 21
 * Graphics hardware *and* driver used: Intel; Mesa
 * 32 or 64 bit: 64
 * Attach ~/.xsession-errors, or /var/log/syslog
 ```

[xsession-errors.txt](https://github.com/linuxmint/cinnamon/files/9285509/xsession-errors.txt)

**Issue**

Running XFCE terminal, or KeePassXC, in either case via keyboard shortcut, runs the program but also . . produces a graphical notification containing the name of the program,

**Steps to reproduce**

Use mintupdate to update Mint 20.3 Cinnamon to Mint 21 Cinnamon.
Reboot.
Use one of the affected keyboard shortcuts. The problem is intermittent with KeePassXC but constant with XFCE Terminal. And in the case of XFCE Terminal, the program starts in the background.

**Expected behaviour**

No notification. Program starts in the foreground.

**Other information**

XFCE terminal is set, in Mint's GUI options, as my default terminal.

**Comment by mtwebster** [comment]
What 'window list' applet are you using currently?

The notification is intended to only occur if you have no window list applet - this is sort of a last ditch way of trying to get your attention (vs the flashing window list item).

**Comment by LinuxOnTheDesktop** [comment]
Ah: I use no window list applet. Rather, I use the dock called 'plank'. I seem to recall that plank itself can flash icons (or something similar) and that under Mint 20.3 plank did do that.

**Comment by mtwebster** [comment]
Ok I'll ditch the notifications altogether, I forgot about plank and others.

You also said that if you launch XFCE terminal from a shortcut, it never starts focused?

**Comment by LinuxOnTheDesktop** [comment]
Thanks.

> You also said that if you launch XFCE terminal from a shortcut, it never starts focused?

Yes, that's right.

**Comment by LinuxOnTheDesktop** [comment]
Oddly, I find, _now_, that when launching XFCE-terminal, and whether by keyboard or not, there is no notification and the terminal opened in the foreground. And the same for KeePassXC. Yet, ten minutes ago, KeePassXC gave a notification (but did not open in the background; instead, the program did its auto-type thing, as it should). Similarly: a bit before that, XFCE-terminal gave a notification and opened in the background. In sum: _the notification and the opening-in-background seems intermittent_.
