### ISSUE TITLE
Regression: top-panel that is set to auto-hide never shows

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/cinnamon#11019]
```
 * Cinnamon version (cinnamon --version): 5.4.9
   - Please specify if you are using the daily builds PPA: no.
 * Distribution: Mint 21
 * Graphics hardware *and* driver used: Intel; Mesa
 * 32 or 64 bit: 64
 * Attach ~/.xsession-errors, or /var/log/syslog
 
[xsession-errors.txt](https://github.com/linuxmint/cinnamon/files/9285509/xsession-errors.txt)

 ```

**Issue**

I have a single panel. It is a top panel. It is set to auto-hide. Under Mint 21, it shows only when I edit it. So, it does not drop down in the way that it is meant to. It never appears at all (unless, as said, I edit it - via Mint's Setitngs). Under Mint 20.3, the panel worked.

**Steps to reproduce**

Have a top panel set to auto-hide.
Possibly: have no other panel.
Use mintupdate to update Mint 20.3 Cinnamon to Mint 21 Cinnamon.
Reboot.
Try and fail to see one's panel.

**Expected behaviour**

The panel should appear when the pointer is at the top of the screen.

**Other information**

I tried to create a new user so as to test with that. However, and perhaps because I use a Yubikey - and the update procedure seemed to mess with my Yubikey installation - any password that I set for the new user gets rejected when I try to log on. (I can log on as usual with my normal user.)

I made the panel into a left panel - using the 'change' option. The new, left panel had the same reticence.

**Comment by mtwebster** [comment]
Can't reproduce this -

What cinnamon theme are you using? If third-party, does this happen with the default Cinnamon or mint themes?

**Comment by LinuxOnTheDesktop** [comment]
My system themes:

![image](https://user-images.githubusercontent.com/47056543/183533306-f2d94e54-f8df-4bb2-b0ad-1121f31ceb0c.png)

**Comment by LinuxOnTheDesktop** [comment]
The following might be relevant. In XFCE terminal, and Gnome terminal, I see syslog messages. Here are examples.

```
Message from syslogd@X230 at Aug  9 01:38:15 ...
 sudo: <redacted> : PWD=/home/<redacted> ; USER=root ; COMMAND=/usr/sbin/ufw status [that is a command that a script of mine runs, and for which there is a sudoers entry.]

Message from syslogd@X230 at Aug  9 01:38:24 ...
 sudo: <redacted> : TTY=pts/0 ; PWD=/home/<redacted> ; USER=root ; COMMAND=/usr/local/bin/apt install ruby [that is a command that just now I entered in the terminal]
```
