### ISSUE TITLE
Cannot edit button layouts in Mint 21 beyond the default ones

### ISSUE THREAD

**Issue by apandada1** [linuxmint/cinnamon#11023]
```
 * Cinnamon version (cinnamon --version): Cinnamon 5.4.9
   - Please specify if you are using the daily builds PPA: No
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 21 Cinnamon edition
 * GPU: Intel Skylake GT2 [HD Graphics 520], Driver: i915
 * 32 or 64 bit: 64 bit
 ```

**Issue**
In previous versions of Linux Mint, I could freely edit buttons layout in the Window settings. I used to use the custom layout "Close, Minimize, Maximize" in the left.
However, in Mint 21, only four options are there (Right, Left, GNOME, Classic Mac). And the Left layout is "Close, Maximize, Minimize", and there is no way to edit that.

**Steps to reproduce**
Open System Settings and open "Windows". There are only four default layouts which cannot be edited further.
![image](https://user-images.githubusercontent.com/3063132/183555765-b672ea12-2214-4e0f-b625-fdc814a03aa0.png)

**Expected behaviour**
There should be more options to customize these layouts.

**Other information**
Please bring back the old layout configuration menu, where the user could freely sort the Close, Maximize, etc. icons as per their wish.

**Comment by mtwebster** [comment]
You can customize the setting directly if you need to using dconf-editor or from a terminal.
Get the current layout:
```
gsettings get org.cinnamon.desktop.wm.preferences button-layout
```
Set a new one:
```
gsettings set org.cinnamon.desktop.wm.preferences button-layout "close,minimize,maximize:"
```
Most users don't need anything beyond a few standard arrangements, so the ui for configuring specific buttons was removed to simplify things.
