### ISSUE TITLE
Single-letter shortcuts in "Activate Window Menu" are not working

### ISSUE THREAD

**Issue by wujastyk** [linuxmint/cinnamon#11033]
```
 * Cinnamon version (cinnamon --version)

  Kernel: 5.15.0-46-generic x86_64 bits: 64 compiler: gcc v: 11.2.0 Desktop: Cinnamon 5.4.9
    tk: GTK 3.24.33 wm: Mutter dm: LightDM Distro: Linux Mint 21 Vanessa base: Ubuntu 22.04 jammy

   - Please specify if you are using the daily builds PPA
     (https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds).

No

 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)

Mint 21

 * Graphics hardware *and* driver used

Device-1: Intel UHD Graphics 620 vendor: Lenovo driver: i915 v: kernel ports: active: eDP-1
    empty: DP-1, DP-2, HDMI-A-1, HDMI-A-2 bus-ID: 00:02.0 chip-ID: 8086:5917
  Device-2: Acer SunplusIT Integrated Camera type: USB driver: uvcvideo bus-ID: 1-8:5
    chip-ID: 5986:2113
  Display: x11 server: X.Org v: 1.21.1.3 driver: X: loaded: modesetting unloaded: fbdev,vesa
    gpu: i915 display-ID: :0 screens: 1
  Screen-1: 0 s-res: 1920x1080 s-dpi: 96
  Monitor-1: eDP-1 model: Lenovo res: 1920x1080 dpi: 142 diag: 395mm (15.5")
  OpenGL: renderer: Mesa Intel UHD Graphics 620 (KBL GT2) v: 4.6 Mesa 22.0.5 direct render: Yes


 * 32 or 64 bit

64

**Issue**

Pressing alt+space brings up the Activate Window Menu, as normal.

In Mint 20 and earlier, single-key shortcuts were available for minimize, maximize, unmaximize etc.  E.g.,, "x" would toggle max/unmax.  

After upgrade to Mint 21, these single-letter shortcuts are not present.


**Steps to reproduce**

Press alt-space, then "x". 

**Expected behaviour**

Maximize or unmaximize the screen.


**Other information**


Thinkpad T580.

**Comment by mtwebster** [comment]
It was too late to add this to 5.4 (due to necessary re-translations) so I made an extension for this until we can implement it directly in Cinnamon:
https://cinnamon-spices.linuxmint.com/extensions/view/92
(Available from Extensions->Download)

**Comment by wujastyk** [comment]
That's great!  Thank you so much.

Unfortunately, when I added this extension, it removed my alt-space menu altogether.  What am I doing wrong?  I tried restarting Cinnamon, and logging out and in.  No luck.

**Comment by mtwebster** [comment]
Just updated - let me know if there is still an issue after trying it. Thanks

**Comment by rohitchormale** [comment]
@mtwebster Extension you mentioned is not working as expected. If you need any additional information, pleaset let me know, happy to provide. Really appreciate your response !

**Comment by mtwebster** [comment]
@rohitchormale What's it doing? Is it incorrect behavior (compared to the old menu) or simply not working?

I admit I never used the window menu much in the past so I may have missed something. If it's just plain broken have a look at ~.xsession-errors and attach it if you see anything.

**Comment by wujastyk** [comment]
> @mtwebster Extension you mentioned is not working as expected. If you need any additional information, pleaset let me know, happy to provide. Really appreciate your response !

Seems completely fine to me, @rohitchormale .  Been using it since the upgrade a couple of days ago.  Are you sure you have run spices updates?

**Comment by rohitchormale** [comment]
sorry looks like error at my end. It is working now but I don't see underlines at mnemonics as it is shown here - https://cinnamon-spices.linuxmint.com/extensions/view/92 . This is minor issue though, just reporting. Attached screenshot


![no-underlines-under-mnemonics](https://user-images.githubusercontent.com/3373460/184411415-70072828-7bc5-4e1e-9777-e53e16f364bc.jpg)

**Comment by mtwebster** [comment]
They appear if you tap 'alt' while the menu is open.  I support I could add an option to always show them..

**Comment by rohitchormale** [comment]
Working after pressing 'alt' as you mentioned. I guess, showing them always could be more intutive. thanks again.
