### ISSUE TITLE
Theme corner options

### ISSUE THREAD

**Issue by lucasgabmoreno** [linuxmint/cinnamon#11036]
```
 * Cinnamon 5.4.9
 * Distribution: Linux Mint Debian Edition LMDE 5
 * Intel HD 5500(i915) + Nvidia 940M (nvidia-driver)
 * 64 bit
 ```

**Issue**

After updating to last Cinnamon version, Theme corner options dissapear.

![2022-08-10_19-08](https://user-images.githubusercontent.com/83520011/184029102-897fefb2-f792-45ac-903c-4b1f1e7b9837.png)

**Steps to reproduce**
Themes app

**Expected behaviour**
Change corner buttons

**Comment by rlatosky** [comment]
Hi,

The window corner buttons option in "Themes" was removed as part of the Cinnamon 5.4 update. More information is listed in Linux Mint 21's release notes:
https://www.linuxmint.com/rel_vanessa_cinnamon_whatsnew.php


**Excerpt from the Link: New Window Theme Customization Settings**

![image](https://user-images.githubusercontent.com/71101970/184031589-fe57158b-4607-4334-9339-cf558075547f.png)

**Comment by mtwebster** [comment]
This is definitely a good thing, and I think a lot of theme authors have already adapted, since this has been the standard with Gnome Shell for at least a few years now.

**Comment by lucasgabmoreno** [comment]
Oh... that's so sad. 
I love to mix themes like MacOS corner buttons + Adapta windows theme, etc.
Thanks!
