### ISSUE TITLE
[BUG] alt+space mnemonics are not working anymore

### ISSUE THREAD

**Issue by rohitchormale** [linuxmint/cinnamon#11049]
```
 * Cinnamon version (cinnamon --version)
   - Cinnamon 5.4.9 (Not using daily builds PPA)
 * Distribution - Mint 21
 * Graphics hardware *and* driver used - Intel Corporation UHD Graphics 620
 * 32 or 64 bit - 64 bit - 64 bit
 * Attach ~/.xsession-errors, or /var/log/syslog - no
 ```

### Issue
On pressing `alt+space`, when any window is selected, we can see multiple options like

- Minimize  - On pressing key 'n', window gets minimized
- Maximize - On pressing key 'x', window  gets maximized
- Close - On pressing key 'c', window gets closed

This is not happening anymore. Even underline to show menmonic keys are not there anymore.

### Steps to reproduce

- Select any window of application (n e.g. firefox, nemo) and press `alt+space` then `n`
- Select any window of application (n e.g. firefox, nemo) and press `alt+space` then `x`
- Select any window of application (n e.g. firefox, nemo) and press `alt+space` then `c`

### Expected behaviour

- On `alt+space` and then `n`, window should get minimized
- On `alt+space` and then `x`, window should get maximzed
- On `alt+space` and then `c`, window should get closed

### Configuration info, if applicable
If this bug report is related to an Applet, Desklet or Extension, please paste (or use a pastebin service) the offending extension's settings, if it has any.  You can obtain this by opening its configuration, clicking the 'hamburger' button in the upper-right corner of the window, and selecting "Export to a file". **Please be sure to review the contents and remove any personal data it may contain.**

**Comment by mtwebster** [comment]
workaround: https://github.com/linuxmint/cinnamon/issues/11033
