### ISSUE TITLE
Custom keyboard shortcuts aren't updated upon changing them

### ISSUE THREAD

**Issue by SwallowYourDreams** [linuxmint/cinnamon#11054]
```
 * Cinnamon version: 5.4.9 (no daily builds, part of Mint 21 stable)
 * Distribution: Mint 21
 * Graphics: Intel HD Graphics 620, driver: i915
 * 64 bit
 ```

### Issue
If you create a custom shortcut via `system settings > keyboard > shortcut` and change it later, the changes will not be applied.

### Steps to reproduce

1. Go to `system settings > keyboard > shortcut`.
2. Create a new shortcut "foo", which will call "foo.sh". Apply and test. "foo.sh" is called.
3. Change shortcut "foo" to now call "bar.sh". Apply and test. It will still call "foo.sh", not "bar.sh".

### Expected behaviour

Calling "bar.sh", thus applying changes made by the user.

### Other information

I've only encountered this issue in Cinnamon as shipped with the newest version of Linux Mint (21), i.e. it does not seem to be present in older versions.

**Comment by mtwebster** [comment]
Try 5.4.10, this should be fixed by https://github.com/linuxmint/cinnamon/commit/e88b1a999b97d524d45d64452c9a3ad0c8189330
