### ISSUE TITLE
[BUG] [REGRESSION] Show position of pointer when the Control key is pressed does nothing

### ISSUE THREAD

**Issue by rcalixte** [linuxmint/cinnamon#11053]
```
 * Cinnamon 5.4.9
   - Built from source locally
 * Distribution - Ubuntu 22.04.1
 * Graphics hardware *and* driver used
    * NVIDIA GeForce GTX 1650 Ti Mobile (nvidia-515)
    * Intel UHD 620 (N/A)
 * 64 bit
 ```

### Issue
Enabling "Show position of pointer when the Control key is pressed" does nothing.

### Steps to reproduce
System Settings -> Mouse and Touchpad -> Show position of pointer when the Control key is pressed

### Expected behaviour
Pressing the control key triggers the radial indicator around the pointer for a time after or until the cursor is moved.

### Other information
I started looking at the code but I haven't been able to pinpoint when the regression was introduced. This is across every instance of Cinnamon 5.4.x I have running so I don't believe it is a local system issue. I can also check system dependencies in case something is incongruent there as well. If I can solve this, I'll open a PR and link to this issue.

Duplicates #10341

**Comment by mtwebster** [comment]
There's a PR pending already to fix this: https://github.com/linuxmint/cinnamon/pull/10975

**Comment by rcalixte** [comment]
They were all closed. I'm inclined to reopen them with a few edits if that's okay with you @mtwebster.

**Comment by mtwebster** [comment]
He'll be opening a new one.  The others repos' pull requests he closed because they'll no longer be necessary.

**Comment by JosephMcc** [comment]
They were just closed after some discussion with mtwebster about handling them a bit differently.

**Comment by rcalixte** [comment]
Closed by
#11059
linuxmint/muffin#633
