### ISSUE TITLE
[BUG] After update new version, Cinnamon only works with Software Rendering

### ISSUE THREAD

**Issue by gsnebur** [linuxmint/cinnamon#11065]
```
 * Cinnamon 5.4.10
 * LMDE 5 Elsie
 * Intel 82865G Integrated Graphics - i915
 * 32 bit
 ```

### Issue
Hi team,

after upgrading to the latest version of Cinnamon in LMDE 5 (32 bit) I have to change to Software Rendering before log in. If I use the Cinnamon without Software Rendering I can't see the panel and the windows don't have title and the buttons (minimize, maximize and close). The previous version worked with Cinnamon (by default) without problems.

How can I solved it? 

Regards!

### Steps to reproduce
Update from Cinnamon 5.2.7 to Cinnamon 5.4.10 with LMDE 5 (32 bit)

### Other information
inxi -Fxxxrz
System:
  Kernel: 5.10.0-16-686 i686 bits: 32 compiler: gcc v: 10.2.1 
  Desktop: Cinnamon 5.4.10 tk: GTK 3.24.24 wm: Mutter dm: LightDM 1.26.0 
  Distro: LMDE 5 Elsie base: Debian 11.2 bullseye 
Machine:
  Type: Desktop System: Hewlett-Packard product: HP d530 SFF(DC578AV) v: N/A 
  serial: <filter> Chassis: type: 4 serial: <filter> 
  Mobo: Hewlett-Packard model: 085Ch serial: <filter> BIOS: Hewlett-Packard 
  v: 786B2 v2.18 date: 01/15/2004 
CPU:
  Info: Single Core model: Intel Pentium 4 bits: 32 type: MT 
  arch: Netburst Prescott rev: 4 L2 cache: 1024 KiB 
  flags: pae sse sse2 sse3 bogomips: 11969 
  Speed: 2992 MHz min/max: N/A Core speeds (MHz): 1: 2992 2: 2992 
Graphics:
  Device-1: Intel 82865G Integrated Graphics 
  vendor: Hewlett-Packard D530 sff driver: i915 v: kernel bus ID: 00:02.0 
  chip ID: 8086:2572 class ID: 0300 
  Display: x11 server: X.Org 1.20.11 driver: loaded: intel 
  unloaded: fbdev,modesetting,vesa resolution: 1024x768~60Hz s-dpi: 96 
  OpenGL: renderer: llvmpipe (LLVM 11.0.1 128 bits) v: 4.5 Mesa 20.3.5 
  compat-v: 3.1 direct render: Yes 
Audio:
  Device-1: Intel 82801EB/ER AC97 Audio vendor: Hewlett-Packard d330 uT 
  driver: snd_intel8x0 v: kernel bus ID: 00:1f.5 chip ID: 8086:24d5 
  class ID: 0401 
  Sound Server: ALSA v: k5.10.0-16-686 
Network:
  Device-1: Broadcom NetXtreme BCM5782 Gigabit Ethernet 
  vendor: Hewlett-Packard d530 CMT driver: tg3 v: kernel port: 1400 
  bus ID: 05:02.0 chip ID: 14e4:1696 class ID: 0200 
  IF: enp5s2 state: down mac: <filter> 
  Device-2: TP-Link RTL8812AU Archer T4U 802.11ac type: USB 
  driver: rtl88XXau bus ID: 4-2:2 chip ID: 2357:0101 class ID: 0000 
  serial: <filter> 
  IF: wlxa42bb0bee482 state: up mac: <filter> 
Drives:
  Local Storage: total: 74.53 GiB used: 10.45 GiB (14.0%) 
  ID-1: /dev/sda vendor: Seagate model: ST380011A size: 74.53 GiB 
  speed: <unknown> serial: <filter> rev: 8.11 scheme: MBR 
Partition:
  ID-1: / size: 15.58 GiB used: 8.69 GiB (55.8%) fs: ext4 dev: /dev/sda2 
Swap:
  ID-1: swap-1 type: partition size: 1024 MiB used: 0 KiB (0.0%) 
  priority: -2 dev: /dev/sda6 
Sensors:
  Message: No sensors data was found. Is sensors configured? 
Repos:
  Packages: apt: 2077 
  No active apt repos in: /etc/apt/sources.list 
  Active apt repos in: /etc/apt/sources.list.d/official-package-repositories.list 
  1: deb http://packages.linuxmint.com elsie main upstream import backport #id:linuxmint_main
  2: deb https://deb.debian.org/debian bullseye main contrib non-free
  3: deb https://deb.debian.org/debian bullseye-updates main contrib non-free
  4: deb http://security.debian.org bullseye-security main contrib non-free
  5: deb https://deb.debian.org/debian bullseye-backports main contrib non-free
Info:
  Processes: 165 Uptime: 19m wakeups: 0 Memory: 1.96 GiB 
  used: 920.6 MiB (45.9%) Init: systemd v: 247 runlevel: 5 Compilers: 
  gcc: 10.2.1 alt: 10 Shell: Bash v: 5.1.4 running in: gnome-terminal 
  inxi: 3.3.01

**Comment by mtwebster** [comment]
Your graphics 'card' is too old - this was a major update and unfortunately some compatibility with legacy systems was lost - anything that doesn't support at least opengl 2.0 (starting around 2005) will no longer work. From what I can find it looks like your graphics won't support beyond 1.3.

**Comment by gsnebur** [comment]
It's true, the PC is very old.

Thanks for the tip!
