### ISSUE TITLE
[BUG] new windows automaximize

### ISSUE THREAD

**Issue by zolstarym** [linuxmint/cinnamon#11068]
```
 * Cinnamon version (cinnamon --version)
 * Cinnamon 5.4.10
   - Please specify if you are using the daily builds PPA
  no
     (https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds).
 * Distribution - (Mint 21, Arch, Fedora 37, etc...)
 mint 21
 * Graphics hardware *and* driver used
 * nvidia
 * 32 or 64 bit
 * 64
 * Attach ~/.xsession-errors, or /var/log/syslog
 ```

### Issue
When opening new windows, they automaximize even though the previous windows were not maximized.

### Expected behaviour
The window manager should remember the windows size and position

### Configuration info, if applicable
If this bug report is related to an Applet, Desklet or Extension, please paste (or use a pastebin service) the offending extension's settings, if it has any.  You can obtain this by opening its configuration, clicking the 'hamburger' button in the upper-right corner of the window, and selecting "Export to a file". **Please be sure to review the contents and remove any personal data it may contain.**

**Comment by changke** [comment]
https://github.com/linuxmint/cinnamon/issues/11041
