### ISSUE TITLE
[BUG] Drag window and switch workspace not working

### ISSUE THREAD

**Issue by 7Ds7** [linuxmint/cinnamon#11069]
```
Cinnamon 5.4.10
Mint 21 64bits - updated from Mint 20
amd
64 bit
~/.xsession-errors has lots of the following errors when switching to workspace, unsure if it is related :

(cinnamon:5461): Gjs-CRITICAL **: 05:20:30.920: Object St.Button (0x559dd3ca0bf0), has been already disposed — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
== Stack trace for context 0x559dd3825380 ==
#0   7ffcfacc8fe0 b   /usr/share/cinnamon/js/ui/layout.js:732 (1160e668d060 @ 1098)
#1   7ffcfacc9d30 b   self-hosted:850 (32c311faf9c0 @ 398)

 ```

### Issue
In Mint 20 by default one could change the current dragged window to a different worskpace by switching to the desired worskspace.
The same does not appear to work in Mint 21.
While dragging a window and switching workspaces via a keyboard shortcut, the shortcut is not triggered and nothing happens.

### Steps to reproduce
- Start dragging a window by clicking and holding the application title bar
- Switch to a different workspace with keyboard ex: ctrl + 2 

### Expected behavior
It should switch workspace 2 and assign the window to that same workspace

**Comment by rschouwenburg** [comment]
I miss this feature every day in Mint 21.

I wanted to add that this also applies to "grab" + cursor key left + right shortcuts to move the window to the previous and next workspace.

**Comment by rschouwenburg** [comment]
Thanks fixing this @mtwebster. It works like perfectly again but with one exception. When I want to move a window to the first workspace using "Switch to workspace 1" shortcut (grab window + ctrl-1 for me), it does nothing.  It works for every other workspace.

**Comment by 7Ds7** [comment]
I came here to write the same thing as @rschouwenburg 
i was a bit reluctant because i thought it was a "my system thing" but even changing the workspace switching from crl+1 to another bind it it still happens and indeed only for the first (1) workspace

**Comment by rschouwenburg** [comment]
Yea it is super odd. I tried that too. :smile:  Plus I went through @mtwebster patch linked to this issue but could not find anything obviously wrong with it.
