### ISSUE TITLE
Redesing cinnamon settings icons.

### ISSUE THREAD

**Issue by Initu-Castilhos** [linuxmint/cinnamon#11074]
Cinnamon settings icons are based on mint-x which are quite old, it would be better to update icons with Adwaita style, similar to xfce settings
![upstream-icons](https://user-images.githubusercontent.com/59381215/184765021-d8daeafb-b6c2-4261-945e-c09110d9531c.png)

**Comment by JosephMcc** [comment]
There are currently no plans to redesign the defaults. And they can be overridden by any icon theme.
