### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by felixecited** [linuxmint/cinnamon#11075]
System:
  Kernel: 5.15.0-46-generic x86_64 bits: 64 compiler: gcc v: 11.2.0 Desktop: Cinnamon 5.4.10
    tk: GTK 3.24.33 wm: Mutter dm: LightDM Distro: Linux Mint 21 Vanessa base: Ubuntu 22.04 jammy
Machine:
  Type: Laptop System: HP product: HP Laptop 17-by0xxx v: Type1ProductConfigId
    serial: <superuser required> Chassis: type: 10 serial: <superuser required>
  Mobo: HP model: 84CA v: KBC Version 74.33 serial: <superuser required> UEFI: Insyde v: F.56
    date: 04/23/2020
Battery:
  ID-1: BAT0 charge: 31.5 Wh (100.0%) condition: 31.5/31.5 Wh (100.0%) volts: 12.9 min: 11.6
    model: HP Primary serial: <filter> status: Full
CPU:
  Info: dual core model: Intel Core i3-8130U bits: 64 type: MT MCP arch: Coffee Lake rev: A cache:
    L1: 128 KiB L2: 512 KiB L3: 4 MiB
  Speed (MHz): avg: 800 min/max: 400/3400 cores: 1: 800 2: 800 3: 800 4: 800 bogomips: 17599
  Flags: avx avx2 ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3
Graphics:
  Device-1: Intel UHD Graphics 620 vendor: Hewlett-Packard driver: i915 v: kernel ports:
    active: HDMI-A-1 off: eDP-1 empty: none bus-ID: 00:02.0 chip-ID: 8086:5917
  Device-2: Quanta HP TrueVision HD Camera type: USB driver: uvcvideo bus-ID: 1-6:6
    chip-ID: 0408:5362
  Display: x11 server: X.Org v: 1.21.1.3 driver: X: loaded: modesetting unloaded: fbdev,vesa
    gpu: i915 display-ID: :0 screens: 1
  Screen-1: 0 s-res: 3840x2160 s-dpi: 96
  Monitor-1: HDMI-1 mapped: HDMI-A-1 model: Sceptre N55 res: 3840x2160 dpi: 138
  OpenGL: renderer: Mesa Intel UHD Graphics 620 (KBL GT2) v: 4.6 Mesa 22.0.5 direct render: Yes
Audio:
  Device-1: Intel Sunrise Point-LP HD Audio vendor: Hewlett-Packard driver: snd_hda_intel
    v: kernel bus-ID: 00:1f.3 chip-ID: 8086:9d71
  Sound Server-1: ALSA v: k5.15.0-46-generic running: yes
  Sound Server-2: PulseAudio v: 15.99.1 running: yes
  Sound Server-3: PipeWire v: 0.3.48 running: yes
Network:
  Device-1: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet vendor: Hewlett-Packard
    driver: r8169 v: kernel pcie: speed: 2.5 GT/s lanes: 1 port: 4000 bus-ID: 01:00.0
    chip-ID: 10ec:8168
  IF: enp1s0 state: down mac: <filter>
  Device-2: Realtek RTL8821CE 802.11ac PCIe Wireless Network Adapter vendor: Hewlett-Packard
    driver: rtw_8821ce v: N/A pcie: speed: 2.5 GT/s lanes: 1 port: 3000 bus-ID: 02:00.0
    chip-ID: 10ec:c821
  IF: wlp2s0 state: up mac: <filter>
Bluetooth:
  Device-1: Realtek Bluetooth 4.2 Adapter type: USB driver: btusb v: 0.8 bus-ID: 1-8:9
    chip-ID: 0bda:b00a
  Report: hciconfig ID: hci0 rfk-id: 0 state: up address: <filter> bt-v: 2.1 lmp-v: 4.2
    sub-v: 7644
RAID:
  Hardware-1: Intel 82801 Mobile SATA Controller [RAID mode] driver: ahci v: 3.0 bus-ID: 00:17.0
    chip-ID: 8086:282a
Drives:
  Local Storage: total: 3.53 TiB used: 203.9 GiB (5.6%)
  ID-1: /dev/sda vendor: Western Digital model: WD10SPZX-60Z10T0 size: 931.51 GiB
    speed: 6.0 Gb/s serial: <filter>
  ID-2: /dev/sdb type: USB model: TO Exter nal USB 3.0 size: 698.64 GiB serial: <filter>
  ID-3: /dev/sdc type: USB vendor: Seagate model: Expansion Desk size: 1.82 TiB serial: <filter>
  ID-4: /dev/sdd type: USB model: Multiple Card Reader size: 1.87 GiB serial: <filter>
  ID-5: /dev/sde type: USB vendor: SanDisk model: Cruzer Blade size: 117.42 GiB serial: <filter>
Partition:
  ID-1: / size: 447.44 GiB used: 17.83 GiB (4.0%) fs: ext4 dev: /dev/sda3
  ID-2: /boot/efi size: 511 MiB used: 5.2 MiB (1.0%) fs: vfat dev: /dev/sda1
Swap:
  ID-1: swap-1 type: file size: 2 GiB used: 0 KiB (0.0%) priority: -2 file: /swapfile
Sensors:
  System Temperatures: cpu: 43.0 C pch: 40.0 C mobo: 0.0 C
  Fan Speeds (RPM): N/A
Repos:
  
Failures:
Bluetooth connected to mint 20.3 will not connect in mint 21 to BT k380. 

### Steps to reproduce
M720 connects fine, tried 2 different k380 keyboards no success. Took keyboard and headphones to one other mint 21 here doesn't find the keyboard and when it finds the bt headset and i choose it then it switches to connect the bedroom tv it found that OFF.

### Expected behavior
Normal Bluetooth connection

### Other information
Don't know how to upload logs to pastebin. 
I have 4 Linux mint computers that were all mint 20.3 now 2 are mint 21 and Bluetooth cannot find the keyboard on either 21 and tries to connect the wrong device

**Comment by FriedrichFroebel** [comment]
This does not sound like a Cinnamon issue, but rather like one from *blueman* or another package. https://github.com/blueman-project/blueman/issues/1825 seems to discuss a similar case as your report.
