### ISSUE TITLE
updating Cinnamon on Fedora

### ISSUE THREAD

**Issue by FBachofner** [linuxmint/cinnamon#11076]
I have a number of machines running Fedora 36 with Cinnamon.

There seems to be no way to update past Cinnamon 5.2.7, but as we know from Mint 21, that is not current.

Is there a repository for Cinnamon on Fedora?

[ Note: at https://copr.fedorainfracloud.org/coprs/  there are various Cinnamon repositores, however, these all seem limited to "enterprise" distros such as RHEL, CentOS, Rocky, Oracle and so forth ]

Thanks in advance for any insights.  :-)

**Comment by leigh123linux** [comment]
I'm not going to update F36 to latest cinnamon.

https://copr.fedorainfracloud.org/coprs/leigh123linux/cinnamon_next/

**Comment by FBachofner** [comment]
Hi @leigh123linux 

Thanks for your reply.

> I'm not going to update F36 to latest cinnamon.

Just curious, is this (maybe mostly?) due to the fact that Fedora 37 will be out soon?

Can you imagine in the future a release cadence where the Fedora Cinnamon spin _might_ (in the future) align with Cinnamon's upgrades (i.e. coterminous with LinuxMint upgrades)

F36 and LM 21 were not all that far apart, for example, so it could have maybe worked in this specific instance if the Cinnamon spin had just been "held back" a few weeks.  However, I realize the complexity of this concept since neither Fedora nor Mint commit to a particular release schedule (although they are generally fairly predictable)
 

> https://copr.fedorainfracloud.org/coprs/leigh123linux/cinnamon_next/

**Cool!**  Thanks for pointing me to what seems to be your testing / development repository.  I'll update from it in a moment and see what blows up!  ;-)  Maybe nothing will.

If the above described "alignment" is in no way possible for the Cinnamon spin and/or the official Fedora repos, would it be possible for you to publish a slightly more "official" looking COPR repository for Cinnamon so that educated risk takers can update Cinnamon outside of Fedora's official repos?

I am not an OS / DE developer but would be happy to assist in any way that could otherwise leverage my skills.

Thanks again.

**Comment by FBachofner** [comment]
Hi @leigh123linux


I enabled your copr repo on one machine last night and pulled down the Cinnamon DE updates.

It seemed entirely trouble free and the machine in question is still working without issue this morning.

That inspired me to update my daughter's laptop this morning before she headed off to school.  Slightly out-of-date-Cinnamon on that Fedora machine was having trouble taking full advantage of power management (for example, that machine could NOT be set to suspend on lid being closed -- she had to remember to suspend manually) as well as some other more minor issues.

I'll report back if there are any problems, but at the moment your "private" copr Cinnamon repo seems without issue (on Fedora 36, at least).

Again, please let me know if there is anything I can do to help in your efforts.  I figure the least I can do would be to report what does and doesn't work, just like here.

Thanks so much for your efforts to bring Cinnamon to other platforms!  :-)
