### ISSUE TITLE
[BUG] Cannot grab window titlebar and press switch workspace keys to take it to another workspace

### ISSUE THREAD

**Issue by Secret-chest** [linuxmint/cinnamon#11077]
```
 * Cinnamon version (cinnamon --version)
   - Please specify if you are using the daily builds PPA
     (https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds).
 * Distribution - (Mint 21, Arch, Fedora 37, etc...)  Mint 21
 * Graphics hardware *and* driver used  Intel UHD Graphics 620
 * 32 or 64 bit  64-bit
 * Attach ~/.xsession-errors, or /var/log/syslog
 ```

### Issue

Title

### Steps to reproduce

Grab a window titlebar and press your workspace switch shortcut

### Expected behaviour

Window to move to the other workspace

### Other information

This did not happen in Cinnamon 5.2.7/Mint 20.3

### Configuration info, if applicable
If this bug report is related to an Applet, Desklet or Extension, please paste (or use a pastebin service) the offending extension's settings, if it has any.  You can obtain this by opening its configuration, clicking the 'hamburger' button in the upper-right corner of the window, and selecting "Export to a file". **Please be sure to review the contents and remove any personal data it may contain.**

**Comment by Secret-chest** [comment]
I really need help on this

**Comment by JosephMcc** [comment]
This doesn't work for me either. I can however Shift+Ctrl+Alt+Right which moves the currently focused window to the workspace I am switching to. To the right in this case. Is that not essentially the same behavior?

**Comment by 7Ds7** [comment]
This is a duplicate at least of [11069](https://github.com/linuxmint/cinnamon/issues/11069)

And @JosephMcc although that shortcut works it is definitely not the same thing, the flow of having to dedicate both hands to have use that shortcut is a break in productivity

**Comment by mtwebster** [comment]
This needs re-implemented... it's in progress.

**Comment by Secret-chest** [comment]
My workspace switch shortcuts are Super+Shift+Tab and Super+Tab

**Comment by Secret-chest** [comment]
Closing since it works now.
