### ISSUE TITLE
[BUG] - Cinnamon 5.4.10 - Broken left Ctrl key

### ISSUE THREAD

**Issue by jonnyabu1** [linuxmint/cinnamon#11085]
```
 * Cinnamon version 5.4.10
 * Distribution - Manjaro
 * Graphics hardware *and* driver used - NVidia ( multiple systems ) - NVidia Driver 515.65.01
 * 64 bit
 * Attach ~/.xsession-errors, or /var/log/syslog
 ```

### Issue
Not sure where to report this but since it's pretty disruptive, I am putting it here as well as Manjaro's issue forum.

After updating to 5.4.10, most things that use the left Ctrl key, particularly Ctrl+Shift, do not work.  I don't know if this from the 5.4.10 changelog has a bearing:
* keybindings.js: Use a js Map to track keybindings and handle changes to custom keybindings properly.

I can use the right Ctrl button fine but after a couple of decades of using left Ctrl that's not something easy to change.

I can do things like Ctrl+Alt+left/right ( to change workspaces ) and that works ok.  If I bring up the Cinnamon keyboard from Keyboards > Layouts and press left Ctrl it never shows I'm hitting it.  However that's not totally right since Ctrl+Alt+left/right works - sometimes it knows I hit it.  I have had issues with Ctrl+C or Ctrl+V but not every time.  Generally Ctrl+Shift+something fails every time.

This happens on multiple systems and started after an update on all systems I did Tuesday ( which included 5.4.10 ) so that would rule out a keyboard hardware issue.

This may not be a Cinnamon thing.  But I don't know.  I did see an issue for this from 2018 in the Mint forums that blamed the issue on XOrg but again, I am unsure where the problem stems from so I wanted to have it out there.  The mention in the 5.4.10 patch notes on Github of the keybinding.js change made me question if that has caused the issue.

### Steps to reproduce
Generally left Ctrl+Shift+something.  Hit Ctrl key in Keyboards > Layouts and it never registers I pressed the key

### Expected behaviour
The key combo works

### Other information
Using right Ctrl+Shift+something seems to work all the time

**Comment by mtwebster** [comment]
So, to be clear, this all worked in 5.4.9?

Do you maybe happen to enable this? (in Mouse settings)
![image](https://user-images.githubusercontent.com/262776/185457364-a8b28a1d-932c-4dab-ac68-dd03abefced2.png)

**Comment by jonnyabu1** [comment]
I do not have it enabled, no

**Comment by jonnyabu1** [comment]
And yes, this problem did not manifest until I updated all my systems Tuesday, of which Cinnamon 5.4.10 was one of them.  But yeah, I cannot say if it's Cinnamon specific or something else along the way.  I just know it hit all my systems at once and I don't know what is the cause unfortunately

**Comment by mtwebster** [comment]
Could you try creating a new user and seeing if it occurs there? This could rule out any user setting causing it.

**Comment by jonnyabu1** [comment]
I am now highly confident this is a Cinnamon issue.

Got home and tested on the current install.  Broken.  Created a new user, same result.

Rebooted to my old HDD install I keep decently updated and use to test config changes and and also tested KDE with.  I logged in and tested and things worked fine, including correctly showing key strokes in the keyboard > layout section.  This was on Cinnamon 5.4.3.  I logged into KDE and did the same tests - worked.

I updated that and it's now on 5.4.10.  Broken.  I logged into KDE and it works fine there.

**Comment by jonnyabu1** [comment]
I will note another user also reported Ctrl issues in Cinnamon in the Manjaro forums for the latest update

**Comment by jonnyabu1** [comment]
I also went and tested different kernels.  On my old drive I boot into 5.15 but tried 5.10 and 5.4 as well.  Same result

**Comment by philmmanjaro** [comment]
With 5.4.10-3 I matched the current latest master commit. @jonnyabu1 maybe test if that improves something. As far as I see it: 5.4.10 seems to have some issues based on the other bug reports. You can follow our packaging [here](https://gitlab.manjaro.org/packages/community/cinnamon/cinnamon/-/commits/master).

**Comment by mtwebster** [comment]
Can you tell me what version of muffin you updated from when going 5.4.3 to 5.4.10?

Did you update from .3 directly to .10 everywhere?

**Comment by jonnyabu1** [comment]
No 5.4.3 was just on my old install I use for testing.  The others were already updated with the latest Manjaro had pushed out, so 5.4.9.  Monday or Tuesday they pushed a bunch of updates, and Tuesday after work I updated all the systems except my test install as I had not booted into it yet.

Phil at Manjaro pushed out 5.4.10-3 as he mentioned above and on my home desktop and a virtual that has worked!  I will apply this at work and the laptops and other virtual tonight but since the two I updated quick here before leaving did I would presume that will as well.  I appreciate the time and questions, and Phil for pushing that out.

**Comment by jonnyabu1** [comment]
This is working on my work desktop it appears so I think we're good.  I do appreciate you guys @philmmanjaro and @mtwebster for the time on looking at this.  Do you want to look at anything else in regards to this?  If not, I can close the issue.

**Comment by mtwebster** [comment]
Oops forgot about this - I'll close, thanks
