### ISSUE TITLE
[BUG] XApp Status Applet icons stay highlighted after cursor is moved away

### ISSUE THREAD

**Issue by ciandonovan** [linuxmint/cinnamon#11099]
```
 * Cinnamon version (5.4.10)
 * Distribution - (Mint 21)
 * Intel iGPU with Mesa
 * 64 bit
 ```

### Issue

XApp Status Applet icons, when any of their menu items are clicked, stay highlighted even after the cursor is moved away.

https://user-images.githubusercontent.com/94260580/185767551-49558d44-929e-44f7-88ea-5e3c08bc533e.mp4

Hovering the cursor over the erroneously highlighted icon, and moving it away again, resets its highlighted state.

### Steps to reproduce

Click on any XApp Status Applet icon that has a menu, then move the cursor upwards and click on any menu item.

### Expected behaviour

XApp Status Applet icon becomes unhighlighted again after a menu entry has been clicked, as it should no longer be in focus.

**Comment by anatolij-novoselcev** [comment]
I have the same problem 
![image](https://user-images.githubusercontent.com/111016103/186125341-d1dc7a15-213a-445f-b6d8-015e1e746712.png)
