### ISSUE TITLE
[BUG] Menu Applet don't close anymore with Super key

### ISSUE THREAD

**Issue by lucasgrvarela** [linuxmint/cinnamon#11100]
```
$ cinnamon --version
Cinnamon 5.4.10

$ cat /etc/os-release 
NAME="Linux Mint"
VERSION="21 (Vanessa)"
 ```

### Issue
When pressing the Super key the menu applet opens but If I click the super key again it doesn't close, I need to press ESC or click with mouse outside of the Menu panel, it was working until yesterday.

- I used a live USB to test and there it's working as expected
- I'm using the default configurations of the Menu Applet (I used the option 'Reset to defaults')
- The 'Keyboard shortcut to open and close menu' are defined as "Super L" and "Super R", I tried to change this shortcuts to another keys, restart the applet, restart the computer, etc.. nothing worked
- I could not find any error log on Melange or syslogs, so I have no idea what to provide here
- I would like to debug the application by myself to provide more infos but could not figure out how to do that
- On my Keyboard Shortcuts there is not any key overlapping with the Super key, just some keys composed of super, like Super+d

**Comment by changke** [comment]
Would be good to search before post: https://github.com/linuxmint/cinnamon/issues/11057

**Comment by lucasgrvarela** [comment]
Like the other guy said, I searched for "menu" and "super" but no similar result was found. Thank you for your help @changke

**Comment by JosephMcc** [comment]
When searching, make sure you are also searching the closed issues. That's probably why it didn't turn up.
