### ISSUE TITLE
[FEATURE REQUEST] Build script for disc image

### ISSUE THREAD

**Issue by matheusdiasdesouzads** [linuxmint/cinnamon#11119]
### Is your feature request related to a problem? Please describe.

No.

### Describe the solution you'd like

A build script to generate bootable disc image. Tell also what are the requirements to run the build script.

(Actually I don't know how to build the OS from sources. There's no guide anywhere (wiki) and I don't get help at Discord.)

### Describe alternatives you've considered

No idea.

**Comment by leigh123linux** [comment]
This isn't cinnamon related.
