### ISSUE TITLE
[BUG] Mint 21: Melange's green lines are near illegible when using inbuilt dark themes

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/cinnamon#11118]
```
 * Cinnamon version (cinnamon --version): 5.4.11
   - Please specify if you are using the daily builds PPA: I am not
 * Distribution: Mint 21
 * Graphics hardware *and* driver used: Intel; Mesa
 * 32 or 64 bit: 64
 ```

### Issue

Using Mint-Y-Dark, or Mint-Legacy-Dark (in at least some, but perhaps all, of the latter's variants), the green text in the Melange debugger is hard to read:

![image](https://user-images.githubusercontent.com/47056543/186961270-1a483b09-d953-4b8e-9a62-8812184fcfae.png)

### Steps to reproduce

Use one of the themes above.
Open Melange.

### Expected behaviour

Easily readable text, please!

**Comment by soonan5** [comment]
It's a Qt app? Well, Cinnamon have some theme problems with these ones. Like VirtualBox
Check this topic: https://forums.linuxmint.com/viewtopic.php?t=325692
You maybe need to use `Qt5 Settings`.

**Comment by LinuxOnTheDesktop** [comment]
I presume that Melange is not a QT app. For, Cinnamon uses GTK and Melange is Cinnamon's debugger.

**Comment by LinuxOnTheDesktop** [comment]
I believe that this problem has been fixed.
