### ISSUE TITLE
[BUG] Cinnamon crashes reliably in Virtualbox when booting Mint 21 live cd.

### ISSUE THREAD

**Issue by defnull** [linuxmint/cinnamon#11124]
```
 * Cinnamon version: 5.4.8
 * Distribution: Mint 21 (live cd)
 * Graphics: VMWare SVGA II (default settings)
 * 64 bit
 ```

### Issue
When installing Virtualbox on a fully upgraded Linux Mint 21 and trying to install Linux Mint 21 in a VM, the installer reliably crashes cinnamon. Directly after clicking "Install Linux Mint" I get the dialog that cinnamon crashed and is in fallback mode. Mouse moves, but clicks are not registered and keyboard also does not work anymore within the VM window, so I cannot restart cinnamon or inspect logs.

The host system runs on amdgpu (Radeon RX 5500) but that should not matter?

### Steps to reproduce
* Create a fresh VM with default settings in VirtualBox
* Boot from `linuxmint-21-cinnamon-64bit.iso`
* Click "Install Linux Mint"
* -> cinnamon crashes

### Expected behaviour
Cinnamon not crashing?

### Configuration info, if applicable
This is an issue with a fresh unmodified Linux Mint 21 live CD.

**Comment by rado84-github** [comment]
I don't get it, which Cinnamon crashes? The Host's Cinnamon or the Guest's Cinnamon? Whichever the case is, I tried to reproduce it but it's not happening - neither the Host or the Guest crashed.

![Picture_created_30-08-2022_19-11-26](https://user-images.githubusercontent.com/41172201/187487698-e72545cb-fe39-477b-8d27-d1171d2e416b.png)

**Comment by defnull** [comment]
Cinnamon crashed within the VM, but this was probably due to memory constrains. I increased available memory to 2GB and it no longer crashes as described. So, it was my own fault ignoring mints minimum requirements of 2GB. Sorry for the noise.
