### ISSUE TITLE
[Suggestion] Reopen GTK repository due to potential usability losses

### ISSUE THREAD

**Issue by Julvenzor** [linuxmint/cinnamon#11130]
Hello. I'm sorry this is not the right place. I haven't found a more appropriate place to discuss some of the recent GTK changes that affect and will affect future versions of Linux Mint.

I would like to present the proposal that Mint keep its repository to revert or adapt the upstream changes made by the GTK team due to potential usability losses. I know that Clement Lefebvre (@clefebvre) is very critical of changes that affect usability.

I am a Spanish writer. When I upgraded to Mint 21, I discovered what to me is a terribly annoying change perpetrated by the GTK developers.

Until now, when the user pressed on a dead key, nothing appeared until after another key was pressed, like a vowel in my language. Now, every time a dead key is pressed, it is displayed with an underscore before being "attached" to the corresponding key. This affects all distributions and environments that use the GTK development kit directly from source.

At first I thought it was a bug. Then I discovered that it is a "feature":

Dev Note: https://blog.gtk.org/2021/03/24/input-revisited/

As a writer, I find this new behavior terribly annoying for those of us who write a lot in languages ​​with accents because it visually distracts from seeing the tilde appear and disappear in the document. For example, on my screen, a word goes from "uni_ " to "unió" when I press "´" + "o".

As always, for GTK developers this change is "Much better!" [sic] and the author of this change has decided to close all the complaint topics on the GTK Gitlab page claiming that it is a "functionality", not a "bug".

One user even commented that the new "feature" had a security flaw because if a dead key is pressed in the password text boxes, it's visible. Obviously, the author of the change, Mattias Clasen, did not give it any importance:

https://gitlab.gnome.org/GNOME/gtk/-/issues/4245

Just three days ago, the first users commenting on Reddit about this annoying change began to appear. As it happened to me, many think and will think that it is a bug. As people update from Mint 20.3 to Mint 21, more people will express their opinions about this change.

https://www.reddit.com/r/linuxmint/comments/x0sic7/mint_21_strange_accent_key_behavior_it_shows/

After much reading, I have found a Reddit thread in which another Spanish complains and presents a solution:

https://www.reddit.com/r/linux/comments/lsda2x/gtk_has_changed_how_dead_keys_work_i_didnt_like/

It seems to me that this new functionality should be optional. And if it is even applied by default, the GTK developers should provide a "legacy" way for users accustomed to the classic way.

GNOME/GTK developers try to copy Apple to the core (they say so themselves) and every occurrence of them becomes default and unconfigurable. They forget that, till the date, the classic function of dead keys is how it is used by 90% of the world's users (Windows). This arrogance is only comparable to those of Wordpress and its blessed Gutenberg.

It's a shame that GNU/Linux development on the desktop seems to be championed by a supposedly arrogant mob who want to turn it into their Apple-style mini-farmhouse. And yes, I use these adjectives because I've read quite a few conversations from the developers and their spirit is evident.

I would like to hear any solution or proposal from the Linux Mint development team. Thank you very much in advance!

Regards.

**Comment by clefebvre** [comment]
Thanks @Julvenzor,

I understand your concerns but I would recommend you reopen the discussion upstream with GTK directly. If many people dislike this feature then it's up to GTK devs to consider reverting it or making it configurable, not to each distribution to patch it their own way.
