### ISSUE TITLE
Sound Applet application launch link

### ISSUE THREAD

**Issue by academo** [linuxmint/Cinnamon#1113]
Hi,

I had seen the sound applet works great with compatible players. The thing is, if I want to see the application window I must open the app again from apps menu and then It recovers the instance, I saw the systray has exceptions to hide those applications and sound applet doesn't have a link to open it again.

Would be great have a link to open the app again from this applet it could be located on applet title bar when It shows:  "application name  - playing"

I think is not so hard to do but I don't know how to, I know this is on /usr/share/cinnamon/applets/sound@cinnamon.org/applet.js just that I don't know how to add it.

Could you please add it as new feature for next commit? Thanks!

**Comment by andremiguelaa** [comment]
I confirm what cipri-tom described above.

**Comment by anandrkris** [comment]
@pixunil - For your awareness. :smile:

**Comment by pixunil** [comment]
I know that this answer will not satisfy you, but I think it's more a DBus issue of spotify than one of the sound applet.
https://community.spotify.com/t5/Help-Desktop-Linux-Mac-and/Raise-player-DBus-action-not-working/td-p/45467
You can try to disable "Hide systray icons for compatible players" in sound applet settings to see the spotify systray icon.

**Comment by cipri-tom** [comment]
It is a possibility, but then why would it happen intermittently ?

**Comment by pixunil** [comment]
I don't know why it happens intermittently, but I never experienced this bug with totem, vlc and banshee and the sound applet handles them all equal, so I'm pretty sure it's not a bug with Cinnamon.

To be sure, you can provide us the `~/.xsession-errors` log and `~/.cinnamon/glass.log` when this issue occurs and the versions of spotify and Cinnamon.

_Please post only lines that are belonging to the current session, and wrapped in [code blocks](https://help.github.com/articles/github-flavored-markdown/#fenced-code-blocks)._

**Comment by tp0** [comment]
Cinnamon: 2.4.5
spotify-client: 0.9.11.27.g2b1a638c

~/.xsession-errors

```
(cinnamon:8344): St-WARNING **: Did not find color property '-gradient-start'

(cinnamon:8344): St-WARNING **: Did not find color property '-gradient-end'

(cinnamon:8344): St-WARNING **: Did not find color property '-gradient-start'

(cinnamon:8344): St-WARNING **: Did not find color property '-gradient-end'

(cinnamon:8344): St-WARNING **: Did not find color property '-gradient-start'

(cinnamon:8344): St-WARNING **: Did not find color property '-gradient-end'

(cinnamon:8344): St-WARNING **: Did not find color property '-gradient-start'

(cinnamon:8344): St-WARNING **: Did not find color property '-gradient-end'

(cinnamon:8344): St-WARNING **: Did not find color property '-gradient-start'

(cinnamon:8344): St-WARNING **: Did not find color property '-gradient-end'

(cinnamon:8344): St-WARNING **: Did not find color property '-gradient-start'

(cinnamon:8344): St-WARNING **: Did not find color property '-gradient-end'
```

~/.cinnamon/glass.log shows nothing.

**Comment by ierpe** [comment]
> You can try to disable "Hide systray icons for compatible players" in sound applet settings to see the spotify systray icon.

That "solves" it for now thanks

**Comment by JosephMcc** [comment]
The sound applet has been completely redesigned and features much better support for Spotify. There are some limitations to what's possible because it's not an open-source app that we can hack on if we so chose. If there is still a problem feel free to open a new issue.
