### ISSUE TITLE
[QUESTION] Will there be a transition to GTK4+Libadwaita?

### ISSUE THREAD

**Issue by ketronixdev** [linuxmint/cinnamon#11149]
GTK4+Libadwaita have proven to be very good technologies, and the interfaces written on them look insanely nice. Will you port Cinnamon and Muffin to GTK4+Libadwaita?

**Comment by Secret-chest** [comment]
They are user-hostile.

**Comment by jonnyabu1** [comment]
Hopefully not Libadwaita....

**Comment by mtwebster** [comment]
No plans at this time.
