### ISSUE TITLE
Notification popups on top of panel ( top of screen )

### ISSUE THREAD

**Issue by jonnyabu1** [linuxmint/cinnamon#11148]
```
 * Cinnamon version 5.4.10-3
 * Distribution - Manjaro
 * Graphics hardware *and* driver used -- NVidia GTX 1080 - NVidia 515.65.01
 * 64 bit
 ```

### Issue
Opened this with the intro of 5.4 but that got closed.............
When updating to Cinnamon 5.4 months ago the monitors got switched around on both my desktops with 3 monitors.  Not physically moved mind you.  After updating to 5.4 and rebooting into both 3 monitor systems, my middle monitor was now the right monitor and the panel was over there.  Easy enough to fix.

But Cinnamon for some things acted like my ( now ) right monitor was still the primary.  I still have some applications that just open on my right monitor instead of the middle as before.  I have a reason for mentioning this.

Specifically this bug:  I keep my panel at the top of my middle screen.  Now popup notifications for anything ( emails, VPN connection, anything ) pops on top of the panel - so over it.  It covers the right side of the panel including the applets like network, sound, and the time, etc.  Previously notifications popped under the panel.  This occurs on both systems with three screens.

On single screen systems, such as two laptops and 2 VMs, notifications still pop up just below the panel and don't cover it.  The panel is at the top on those as well.

This is why I brought up the fact that Cinnamon still seems to think for some things that what used to the be middle screen before 5.4, which is now the right screen, is still the primary.

### Steps to reproduce
3 monitors - panel at the top of the middle monitor - get a notification.  

I'm unsure if this would reproduce on a system installed after the intro of 5.4 as it appears to me, though I may be incorrect, that this would be related to the monitors getting switched and Cinnamon still thinking that for some things my old middle monitor ( now the right ) is still the primary.

I have not tested a fresh install as I don't have a desire at this time to wipe and reload a system.

### Expected behaviour
Notifications pop up under the panel

**Comment by mtwebster** [comment]
Can you attach the output to:
```
dconf dump /org/cinnamon/ > output.txt
```
(There shouldn't be personal info in that but check in case)

- What are the resolutions of the three monitors?
- Are you using hidpi or any scaling?
- Instead of a fresh install, could you try a new user instead?

Thanks

**Comment by jonnyabu1** [comment]
Hopefully this is how you were wanting the output:
[output.txt](https://github.com/linuxmint/cinnamon/files/9498467/output.txt)

All three monitors are 1920x1080
No hidpi or any scaling

**Comment by jonnyabu1** [comment]
Attaching a couple of screenshots of the panel covered when the primary monitor is the middle vs the right

![panel_covered_middle_screen_primary](https://user-images.githubusercontent.com/45885795/188680022-0fbd77b1-9e23-43aa-a5b9-c5b90849ad03.png)

![panel_not_covered_right_screen_primary](https://user-images.githubusercontent.com/45885795/188680050-511dfe15-6a12-49b3-9415-7439e687d385.png)

**Comment by jonnyabu1** [comment]
i'm confused on the closing of this?

**Comment by jonnyabu1** [comment]
oh duh.  i see the fix.  nvmd

Thanks!
