### ISSUE TITLE
[BUG] Tooltips are broken in system tray

### ISSUE THREAD

**Issue by anatolij-novoselcev** [linuxmint/cinnamon#11155]
```
 * Cinnamon 5.4.12
 * Distribution - Mint 21
 * 64 bit
```

### Issue
After update to cinnamon 5.4.12 tooltips are broken in system tray. Tooltips disappear after a random period of time.
I had the same error in LM 20.3

Cinnamon 5.4.9 - 5.4.11 does not have this problem

inxi -Fxz
https://termbin.com/5z03

https://user-images.githubusercontent.com/111016103/188853220-db69c46e-5523-4ecf-a1d0-22c182b24350.mp4

**Comment by icarter09** [comment]
Are all the icons in the panel displaying this issue when it occurs?

**Comment by Elliot4444** [comment]
I don't know if it is the same problem I have, but my tooltips (text on hover) stop working on all items in the panel after some time. Particularly annoying for the volume tooltip I think.

But it is not the time I think but easy to reproduce:

If you disable in the "Grouped windows list" applet the "Group windows by application" and open two instances of one application and close one by middle click on the icon in the panel, the tooltips are no longer working on the panel.

**Comment by anatolij-novoselcev** [comment]
> Are all the icons in the panel displaying this issue when it occurs?
Yes, all icons

**Comment by fredcw** [comment]
Is this the same issue as this one?: https://github.com/linuxmint/mint21.2-beta/issues/11

**Comment by Elliot4444** [comment]
Yes it is the same issue.

**Comment by rcalixte** [comment]
@anatolij-novoselcev @Elliot4444 Is it okay to close this issue?

**Comment by anatolij-novoselcev** [comment]
> @anatolij-novoselcev @Elliot4444 Is it okay to close this issue?

Yes, thnx
