### ISSUE TITLE
Removable Drives Applet Visible After Unmount

### ISSUE THREAD

**Issue by mfreeman72** [linuxmint/cinnamon#11170]
```
 * Cinnamon version: Cinnamon 5.4.12 (Standard version included with Mint 21, NOT daily PPA)
 * Distribution: Linux Mint 21
 * Graphics hardware *and* driver used: AMD Ryzen 7 with Open Source driver, and NVIDIA GTX 1650 with proprietary driver v. 515
 * 64 bit
 * Attach ~/.xsession-errors, or /var/log/syslog
 ```

### Issue
After unmounting a USB or network drive, the Removable Drives panel applet remains visible, and does not list any available drives.

### Steps to reproduce
Unmount a USB or network drive and see that the applet is still visible.

### Expected behaviour
After unmounting a drive, the applet icon should not be visible on the panel until the next time a drive is mounted.

### Other information
Screenshot showing the visible applet and menu without any available drives, after having unmounted USB or network drive:
![Screenshot from 2022-09-15 13-54-33](https://user-images.githubusercontent.com/7842664/190507291-42a83a3a-5069-496c-8af3-8959c828b395.png)

### Configuration info, if applicable
This applet has no user-accessible settings.

**Comment by icarter09** [comment]
What are the steps you are doing to unmount the drive?

I'm seeing the expected behaviour if I right click the drive in Nemo and select `Safely Remove Drive`.

**Comment by mfreeman72** [comment]
It was happening when I either right clicked the drive and select Safely Remove Drive, or when I clicked the Eject-like icon in the removable drives applet. That said, it's not been happening recently, so I assumed this had been fixed, and just forgot to close the issue. I'll close it now.
