### ISSUE TITLE
Search box on the bottom panel

### ISSUE THREAD

**Issue by jcperil** [linuxmint/cinnamon#11200]
There is a search box when you click on the menu launcher.
#### Feature Request:

An option to place the search box on the bottom panel. Requesting only for placement without interfering with any functionality.

Attachment:
![before anyone gets triggered, requesting for an option only](https://user-images.githubusercontent.com/89805719/193395286-7a5df109-ecd1-47df-800f-b7221e62daa8.png)

**Comment by Secret-chest** [comment]
So a search box applet? Someone else can make it.

**Comment by AndreiMiculita** [comment]
Agree, and this issue is more appropriate for https://github.com/linuxmint/cinnamon-spices-applets

@jcperil consider copying it there and closing this one
