### ISSUE TITLE
Two Blueman Bluetooth indicators in appearing in panel.

### ISSUE THREAD

**Issue by Tater-K7S5A** [linuxmint/cinnamon#11206]
```
 * Cinnamon version:  5.4.12
    WM Theme: Mint-Y
    Theme: Mint-X [GTK2/3]
    Icons:  Mint-X-Dark [GTK2/3] 
    Desktop: Numix-Cinnamon-Transparent
 * Distribution: Linux Mint 21 (Fresh install 8-20-22: not an upgrade)
 * Graphics hardware *and* driver used:
  
    AMD Ellesmere [Radeon RX 570]
    vendor: Micro-Star MSI driver: amdgpu v: kernel pcie: speed: 2.5 GT/s
    lanes: 16 ports: active: HDMI-A-1,HDMI-A-2 empty: DP-1,DP-2,DVI-D-1
    bus-ID: 10:00.0 chip-ID: 1002:67df class-ID: 0300
  Display: x11 server: X.Org v: 1.21.1.3 driver: X: loaded: amdgpu,ati
    unloaded: fbdev,modesetting,vesa gpu: amdgpu display-ID: :0 screens: 1
  Screen-1: 0 s-res: 3840x1080 s-dpi: 96 s-size: 1016x286mm (40.0x11.3")
    s-diag: 1055mm (41.6")

 * 64 bit (AMD Ryzen 5 4500, MSI B450-A Pro Max)
 *  MPow Bluetooth dongle (Realtek rtl8761b, I believe)
 ```

### Issue
Two indicators for Blueman are appearing on panel.  One Black, One white.  The Black one appeared with initial fresh install of LM21 on August 20.  It has a working context menu but the tool tip shows below the icon.  The white one showed up in the last week or so (Or, should I say:   I noticed it in the last week.)  It has a broken context menu (blank) and it's tool tip shows above the icon.

![Blueman2a](https://user-images.githubusercontent.com/69114269/194039349-e63faf5c-3bb4-409a-9297-bfc46f57568b.png)

### Steps to reproduce
Fresh install of LM21 with MPOW dongle installed.
Wait indeterminate period of time for a white Blueman indicator to appear.
(I know, I know:  MPOW dongles and time are two things nobody has.)

### Expected behaviour
Preferably, the white Blueman indicator to be the only Blueman indicator on the panel.

### Other information
I have found that if I remove the dongle and then reboot the computer when I plug it back in there will be one indicator:  The white one which works as intended with a functional context menu.  

If I reboot with the dongle plugged in then I get both indicators again.

If I unplug the dongle the black indicator disappears.  The white indicator remains but still has a blank context menu.  If I then plug the dongle back in the black indicator returns.

Thank you for an excellent DE.  I really appreciate your efforts.

**Comment by Rudxain** [comment]
Can confirm. It happened to me twice, but without a dongle

**Comment by clefebvre** [comment]
Fixed by https://github.com/blueman-project/blueman/commit/6b219de1e8618699f918140b66caa12a05bea9ab. We'll backport it when it's tagged.

**Comment by Tater-K7S5A** [comment]
Thank you!  I appreciate the effort represented by #1870 and #1871.

**Comment by Tater-K7S5A** [comment]
A most excellent update today.  Thanks @clefebvre .
