### ISSUE TITLE
Removing icons from the Panel is too easy and dangerous

### ISSUE THREAD

**Issue by InfoLibre** [linuxmint/cinnamon#11203]
### Is your feature request related to a problem? Please describe.

It's too easy and dangerous to remove an icon (applet or application) from the panel, even if there's an alert message when doing it. A lot of new users remove accidentally these icons.

### Describe the solution you'd like

1) In each applet right-click menu, "Removing" should be removed:

![Capture d’écran du 2022-10-02 10-48-23](https://user-images.githubusercontent.com/3955499/193446332-fddb2d12-fd78-402b-a2f1-c15b9cd40477.png)

Applets should be added and removed from the panel with the applets manager only:

![Capture d’écran du 2022-10-02 10-49-06](https://user-images.githubusercontent.com/3955499/193446391-b1ac1649-ae91-45ee-a2fc-428530d939c9.png)

2) In grouped-window-list, in each application right-click menu, "Unpin" should be inactivated by default: 

![Capture d’écran du 2022-10-02 10-47-36](https://user-images.githubusercontent.com/3955499/193446548-f1d148aa-1b5b-4d78-bdad-c901a7c4addf.png)

Add an option here if you want to show this menu again:

![Capture d’écran du 2022-10-02 10-48-13](https://user-images.githubusercontent.com/3955499/193446742-a5911dbf-43a7-4ec3-97f3-0231399989cb.png)

### Additional context

See https://github.com/linuxmint/cinnamon/issues/9651 too.

**Comment by Secret-chest** [comment]
How would you remove a specific instance of an applet? A confirmation popup is enough.

**Comment by InfoLibre** [comment]
Even with a confirmation popup, it's too dangerous. It's more secure to remove it the applets manager window.

**Comment by JosephMcc** [comment]
I personally feel like this is over the top. For one, lets be real about this being any kind of "dangerous". You aren't jumping in front of a tank. You're talking about removing something like a pinned icon from the panel of your computer. Dramatics aside, this just feels like making things overly tedious. Might a user accidentally remove something? Sure. But it's not even just a single click to do so. You actually have to dig in a context menu and purposefully choose that option. There is such a thing as too much hand holding. And adding an option to enable an option? That's total overkill.

**Comment by InfoLibre** [comment]
New users often dig into the Trash context menu and accenditally remove it instead of emptying it.

**Comment by InfoLibre** [comment]
I only report 2 cases where I saw a lot of people staying lost because of too easy icons removing. You don't need to change all Cinnamon at all.
