### ISSUE TITLE
Terminal color-scheme doesn't match system

### ISSUE THREAD

**Issue by Rudxain** [linuxmint/cinnamon#11210]
```
 * Cinnamon version 5.4.12
   - Please specify if you are using the daily builds PPA
     (https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds). No
 * Distribution - Mint 21
 * Graphics hardware *and* driver used: Intel Corporation 3rd Gen Core processor Graphics Controller
 * 64 bit
 * Attach ~/.xsession-errors, or /var/log/syslog (I'll add it later, it doesn't seem useful)
 ```

### Issue

The GNOME Terminal app doesn't automatically switch color-scheme when switching it from the Themes app nor the Welcome Screen.

### Steps to reproduce

0. Open Terminal app
1. Go to "Edit"
2. Go to "Preferences"
3. Go to the "Colors" tab
4. Enable "Use colors from system theme"
5. Open Welcome Screen app
6. Go to "First Steps"
7. Toggle color-scheme switch if it's in "dark mode" (to enable "light mode")
8. Close and reopen the Terminal
9. The Terminal is still in dark theme

### Expected behaviour

The Terminal text should be black while the background is white

### Other information
Closely related to #10950
Somewhat related to #10197

I even tried rebooting, but to no avail.

**Comment by Rudxain** [comment]
If I had an OLED display, I would always use dark-scheme and would never have this issues. But not all users have OLED, so I ask the devs to please fix these bugs. I'm tired of doing this everytime:

1. Go to "Welcome Screen", go to "First Steps", then toggle color-scheme
2. If light-scheme was selected, go to Themes, then change "Desktop" from "Mint-Y-Dark" to "Mint-Y"
3. If using the Terminal, and light-theme was selected, go to "Preferences", then disable "Use colors from system theme" to use the built-in "black on white" scheme

I wish someone could **please** give me a temporary workaround script that automates those steps.

**Comment by clefebvre** [comment]
The terminal is dark by design in mint-y, whether you choose dark or light. That's by design. You can go against it by selecting a different color profile in the terminal preferences if you want.

The titlebar is also dark in light and dark themes. You can disable that in gnome-terminal -> preferences -> general -> theme variant.

**Comment by clefebvre** [comment]
Same thing with the panel, the default combo is light controls with a dark panel. You can decide to make everything light if you want, but by default we run a combination of light apps, dark media apps and a dark panel. That's what's been referred to as light by the welcome screen.

**Comment by Rudxain** [comment]
I understand, thank you for explaining. But it would be nice if the docs provided some script to automate this "consistent color-scheme feature"
