### ISSUE TITLE
window-list@cinnamon.org : add the pin function (like group-window-list@cinnamon.org)

### ISSUE THREAD

**Issue by sangorys** [linuxmint/cinnamon#11212]
### Is your feature request related to a problem? Please describe.
When we open an app, it goes at the end of the window-list applet. Then, we need to move the windows manually each time Cinnamon starts or crashes. It is painful

### Describe the solution you'd like
I would like to have an option to pin a window (like in Ms Window or in group-window-list@cinnamon.org). Like this the position of the window is always the same

### Describe alternatives you've considered
Saving automatically the windows positions in the disk each time a new app is launched : https://github.com/linuxmint/cinnamon/issues/11213

### Additional context
Nothing

**Comment by mtwebster** [comment]
This type of feature is why we added the grouped window list, so there are no plans to implement this, as you can make gwl look more or less the same already (and have pinned apps).

**Comment by MarkJeronimus** [comment]
I like to request this too. I want my windows icons to be separate (not grouped) but still able to pin them (not to lock position but to launch them in the first place)

**Comment by mtwebster** [comment]
Why can't you use panel launchers for this?
![image](https://github.com/linuxmint/cinnamon/assets/262776/44a26ff6-ea57-4c0b-9c55-0c45fec3bf31)

The traditional layout pre-grouped-window-list was this way. We added gwl so we didn't need to add all this stuff to the old window list applet.

**Comment by MarkJeronimus** [comment]
That creates duplicate launcher icons and running program icons.

I did not know the two applets are developed independently, as they are named so similar.

I like the features of the grouped-window-list, except I don't want the grouping feature.

And I hate one of the features of the window-list so I rage-removed that.

**Comment by Secret-chest** [comment]
You may use GWL and disable the grouping as well as opt to show labels. That's what I do.
