### ISSUE TITLE
NetworkManager panel applet doesn't properly disconnect Bluetooth tethering networks

### ISSUE THREAD

**Issue by wrouesnel** [linuxmint/Cinnamon#1122]
Setting up my iPhone for Bluetooth, if I click the "Use your mobile phone as a network device (PAN/NAP)" option, then the panel applet correctly picks up a new Mobile Broadband adapter.

If I then select the adapter, the NetworkManager will go ahead and connect to it, setup the bluetooth ethernet etc. - this all works fine.

The problem is:  the mobile broadband toggle switch on the menu does not get updated to reflect that it has connected to mobile broadband, and toggling the switch on and off fails to disconnect the network - my phone stays in "internet tethering" (and continues to forward internet connectivity correctly) until I manually delete the profile out of /etc/NetworkManager/system-connections.

The same behavior happens if I have a network in the mobile broadband list, and then click the "Mobile Broadband" on toggle. It will toggle on for a moment, connect to the mobile broadband network, and then be toggled off again (and refuse to turn off internet tethering again).

**Comment by ambalasis** [comment]
@anandrkris This bug still exists as of 64-bit Linux Mint 17.1 Rebecca.

**Comment by Vahan86** [comment]
@wrouesnel, is this still an issue for you in Cinnamon 3.2?

**Comment by Vahan86** [comment]
@JosephMcc, can we close this issue?

**Comment by Vahan86** [comment]
@JosephMcc, can we close the issue?
