### ISSUE TITLE
Screensaver leaking what music I am listening to.

### ISSUE THREAD

**Issue by Rezney** [linuxmint/cinnamon#11239]
I really like Cinnamon but there is this thing which has been bothering me for quite some time. Is there any reason for Fedora Cinnamon's screensaver to be leaking what music I am listening to? I mean this is not a mobile phone which you have either in your hand or in your pocket.

Can this be turned off by default? (how it can in fact be turned off?)

Thanks...

**Comment by leigh123linux** [comment]
Look in settings / screensaver / customize 

![image](https://user-images.githubusercontent.com/1299302/197986908-4f696650-1918-4f49-8f3c-bf1466d65e34.png)

**Comment by Rezney** [comment]
@leigh123linux Thanks for your answer. 

Can this be turned off by default? But I understand that if it is only me complaining about this, in my opinion, strange settings you will not change it. I just wanted to point it out.

**Comment by leigh123linux** [comment]
@clefebvre  ^^

**Comment by ItzSwirlz** [comment]
If it’s a gschema then it’s up to the maintainers of the distro I would say

**Comment by leigh123linux** [comment]
> If it’s a gschema then it’s up to the maintainers of the distro I would say

No one ever filed a redhat bugzilla requesting to change it from default, if it was changed I believe it would generate more bug reports than the request.

**Comment by Rezney** [comment]
Fair enough. Thank you again for your time and the pointer.

**Comment by mtwebster** [comment]
Yeah, in hindsight I agree with you, it perhaps should have been defaulted to the side of privacy, but it's one of those things that it's been this way for so long, to change it would cause more problems than it might solve - I doubt most people were aware you could toggle this in the first place.

At the time it was also pushed as a handy feature, being able to control your music while the computer was locked (like portable devices and phones).
