### ISSUE TITLE
GNOME-SCREENSHOT

### ISSUE THREAD

**Issue by kacperpaczos** [linuxmint/cinnamon#11249]
### Issue
When you make a screenshot, when you click CANCEL you should back to previous windows (to select type of screenshot)
It was in eariel version and it is in version from git: https://gitlab.gnome.org/GNOME/gnome-screenshot
BUT NOT IN LINUX MINT VERSION.
![image](https://user-images.githubusercontent.com/23406555/199048708-193f5f58-8d26-45b8-b246-b8ddaf1527cc.png)
It's very annoying. 

### Steps to reproduce
Open the screenshot tool in interactive mode and create the screenshot, then click "Cancel" button. Program will end.

### Expected behaviour
It should be work.

### Other information
Reinstall this package from this, and it's work 
https://launchpad.net/ubuntu/+source/gnome-screenshot/41.0-2/+build/23174992

Please, rebuild this package from upstream

**Comment by ItzSwirlz** [comment]
I think what you re asking for is a [backport](https://en.wikipedia.org/wiki/Backporting). This is a LM issue, not a global cinnamon issue. I suppose you could try pulling the .deb files directly from Launchpad?

**Comment by kacperpaczos** [comment]
No. I want upgrade package gnome-screenshot used on Linux Mint form version: 41.0+mint1+vanessa
to Ubuntu version: [gnome-screenshot_41.0-2_amd64.deb](https://launchpad.net/ubuntu/+archive/primary/+files/gnome-screenshot_41.0-2_amd64.deb) (44.9 KiB) from https://launchpad.net/ubuntu/+source/gnome-screenshot because new version have a couple of bug fixes.
![image](https://user-images.githubusercontent.com/23406555/215342902-407972d3-7a45-4276-9a54-86053b5e3b48.png)

For example, after make a screenshot, I can make "Cancel" to back to previous page of app, but on Linux Mint version of the gnome-screenshot have bug which make this impossible.

Actually error:
![error screenshot](https://user-images.githubusercontent.com/23406555/215343742-64c40e3c-0c36-4a1a-b74a-1b0d445c81bc.gif)

After update from Ubuntu:
![good screenshot](https://user-images.githubusercontent.com/23406555/215343733-80814880-8411-42e4-9e7d-f0f3d20fdd5b.gif)

@mtwebster @clefebvre

**Comment by clefebvre** [comment]
Fixed in 41.0+mint2+vanessa.

This button should close the app when it's launched in shortcut mode, but go back to the main UI when the main UI was first visible (i.e. when run in menu mode).
