### ISSUE TITLE
missing usability in alt-space context menu

### ISSUE THREAD

**Issue by poweruser2022** [linuxmint/cinnamon#11241]
hello, i hope i am right here

menu items in "alt-space context menu" (or "window menu") are _*without underlined*_ letters... so i have to use either the mouse or the arrow (-down) key instead of a single letter on the keyboard
![screenshot_contextmenu](https://user-images.githubusercontent.com/116865999/198514946-1d54c979-b90b-417b-9311-e04bdd07ee03.jpg)

TIA

Desktop: Cinnamon 5.4.12
tk: GTK 3.24.33
wm: Mutter
dm: LightDM
Distro: Linux Mint 21 Vanessa
base: Ubuntu 22.04 jammy

**Comment by mtwebster** [comment]
Hi, [this](https://cinnamon-spices.linuxmint.com/extensions/view/92) extension will restore this functionality for 5.4.

It's been added to cinnamon itself for the next major release:
https://github.com/linuxmint/cinnamon/commit/325eeb1f332d82b45f33392040213a2d3c73c1ed
