### ISSUE TITLE
Desklets simply not appearing when added

### ISSUE THREAD

**Issue by NathanC** [linuxmint/cinnamon#11265]
```
 * Cinnamon 5.4.12
   - Please specify if you are using the daily builds PPA (No)
 * Distribution - Arch
 * GeForce RTX 2080 Ti, NVIDIA Driver 520.56.06
 * 32 or 64 bit
 * Attach ~/.xsession-errors, or /var/log/syslog
 ```

### Issue

I simply cannot add Desklets. When I click the add button, it shows a checkmark saying it's added (and it shows settings have been loaded in ~/.xsession-errors) but.. nothing happens on either of my monitors. I am able to see an icon on my desktop, if that helps at all.

When I add the icon, a red error circle appears briefly (for half a second or so) directly to the left of the settings button in the desklet row.

I've looked in the looking glass log, and don't see anything besides the session errors log output below.

Any idea how to fix this?

### ~/.xsession-errors
```
(cinnamon-settings.py:131510): Pango-WARNING **: 01:27:29.391: Leftover font scales

(cinnamon-settings.py:131510): Pango-WARNING **: 01:27:29.391: Leftover font scales

(cinnamon-settings.py:131510): Pango-WARNING **: 01:27:29.391: Leftover font scales

(cinnamon-settings.py:131510): Pango-WARNING **: 01:27:29.391: Leftover font scales
libgoa-1.0.so.0: cannot open shared object file: No such file or directory
Failed to load module: /usr/lib/cinnamon-control-center-1/panels/libonline-accounts.so
/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py:442: DeprecationWarning: Gtk.Window.set_wmclass is deprecated
  self.window.set_wmclass(wm_class, wm_class)
Gjs-Message: 01:27:34.716: JS LOG: [LookingGlass/info] Installing settings for diskspace@schorschii
Gjs-Message: 01:27:34.717: JS LOG: [LookingGlass/info] Settings successfully installed for diskspace@schorschii
Gjs-Message: 01:27:35.350: JS LOG: [LookingGlass/info] Installing settings for diskspace@schorschii
Gjs-Message: 01:27:35.350: JS LOG: [LookingGlass/info] Settings successfully installed for diskspace@schorschii
Gjs-Message: 01:27:35.522: JS LOG: [LookingGlass/info] Installing settings for diskspace@schorschii
Gjs-Message: 01:27:35.522: JS LOG: [LookingGlass/info] Settings successfully installed for diskspace@schorschii
Gjs-Message: 01:27:35.684: JS LOG: [LookingGlass/info] Installing settings for diskspace@schorschii
Gjs-Message: 01:27:35.684: JS LOG: [LookingGlass/info] Settings successfully installed for diskspace@schorschii
Gjs-Message: 01:27:35.848: JS LOG: [LookingGlass/info] Installing settings for diskspace@schorschii
```

( I was adding and removing the desklet multiple times, hence the multiple statments. I tried it with all the desklets, not just diskspace, and had the same experience of nothing seeming to happen on the desktop)

**Comment by leigh123linux** [comment]
It works fine.

![image](https://user-images.githubusercontent.com/1299302/200114643-f2f2d69c-4bc4-421f-8732-6de72bdde549.png)

Report it to archlinux bug tracker

**Comment by NathanC** [comment]
> It works fine.
> 
> ![image](https://user-images.githubusercontent.com/1299302/200114643-f2f2d69c-4bc4-421f-8732-6de72bdde549.png)
> 
> Report it to archlinux bug tracker

It's working fine for you, but it's very much not working for me, and it's strange that there are no errors. What makes you think this an Arch specific bug?

Is there anything else I can do on my end to get information that would be useful to deduce what is happening? Do you know what sort of state could leads to the briefly flashing red error circle?

It seems like there must be at cinnamon logging bug here, as it flashes the error message and doesn't log anything, which implies a silently swallowed error.

**Comment by leigh123linux** [comment]
I consider this an archlinux issue as it doesn't reproduce on Linuxmint or Fedora 37 (python-3,11) installs.
You need to ask the archlinux cinnamon maintainer to see if they can reproduce it, if they can't it means it's an issue on your PC.

**Comment by NathanC** [comment]
@leigh123linux What about the error message flashing with no log? Is there something else besides `.xsession-errors` I can use to try and deduce what is happening?

I'll reach out the archlinux cinnamon maintainer.
