### ISSUE TITLE
Is it possible to provide a custom screensaver/lockscreen?

### ISSUE THREAD

**Issue by NathanC** [linuxmint/cinnamon#11277]
### Is your feature request related to a problem? Please describe.

My lock screen and screensaver/turning off the display from cinnamon completely bricks my PC, screen dies and I can't even switch to a TTY.

Besides that, even if it did work, the theming of it doesn't match the rest of my system/display manager, and I'd like to have a consistent theme.

### Describe the solution you'd like

Can I supply a custom screensaver/x-secure-lock command for cinnamon, so that the power 'turn off display" setting and manually triggering the lock functionality call, instead, something like [xsecurescreensaver](https://github.com/google/xsecurelock)

**Comment by mtwebster** [comment]
You can specify a custom command in place of cinnamon-screensaver:

```
gsettings set org.cinnamon.desktop.screensaver custom-screensaver-command <your-command>
```

This does nothing to alter existing power-save behavior - you'll have to disable that in power settings and roll it into whatever you might do here.

**Comment by NathanC** [comment]
Thanks @mtwebster, that's exactly what I was looking for! I've enabled it, and it works great—I've tested both with manually locking and with an automatic delay in screensaver settings.

What exactly does the power management "turn of the screen when inactive for X minutes" do? Use some library to just turn the display off, and nothing else?

The screensaver I'm using (`x-secure-lock`) turns off the display when inactive, so given that would there be any benefit for turning off the screen via power management itself? Just want to make sure I'm understanding it.

Thanks again!

**Comment by mtwebster** [comment]
The power manager calls `DPMSForceLevel` to turn the monitors on and off. `x-secure-lock` probably does the same so I imagine you can just set Cinnamon's 'Turn off the screen when inactive for' to Never.
