### ISSUE TITLE
Multiple instances of the same window are shown on all open workspaces in the expo workspace switch section

### ISSUE THREAD

**Issue by anaximeno** [linuxmint/cinnamon#11293]
```
 * Cinnamon version 5.4.12
 * Distribution - Mint 21 Vanessa
 * 64 bit
 ```

### Issue
Multiple instances of the same window are shown on all open workspaces in the expo workspace switch section when you drag and drop a window from any workspace in the section outside another workspace.

### Steps to reproduce
![Peek 19-11-2022 12-58](https://user-images.githubusercontent.com/63073056/202855329-f6933325-f7a0-4405-8c5f-919a0b8563b5.gif)

### Expected behaviour
The best behavior in this situation could be either creating a new workspace with that window only (the same behavior when moving a window to the right side section and sends the window to another workspace) or just returning the window to the previous workspace before the dragging it.

### Other information
I believe that all the windows shown when the bug happens are just a mirror of the same instance, because if you close one window all the others close at the same time. Also, dragging one of the duplicated windows and moving it to another workspace will "solve" the problem, making only one window to be shown again.

I didn't include a lot of information about my hardware and software configurations because I didn't find it relevant to the problem since this bug seems very easy to reproduce, but if you still believe it is needed just let me know.

**Comment by 887** [comment]
Please do not change this, i've been using this behavior to manage my windows for years.
I don't think this is a bug, it's a feature. In my eyes this is intentional and a quick way to put a window across all workspaces.
It could be implemented better, but i need this ability to put a window on all workspaces from workspace view.
If this gets changed it breaks my established workflow.

**Comment by anaximeno** [comment]
I am closing this issue as it seems to be more of a feature than an issue. But this should be better implemented to make it clear that it's intentional.
