### ISSUE TITLE
Add gtk-3 thumbnail for Yaru.

### ISSUE THREAD

**Issue by Initu-Castilhos** [linuxmint/cinnamon#11299]
Add gtk-3 thumbnail for Yaru theme. Image below for downloads.
![Yaru](https://user-images.githubusercontent.com/59381215/203839835-9037bc33-ef18-40da-af09-551a0547c4b0.png)
![Yaru-bark](https://user-images.githubusercontent.com/59381215/203839841-bae73d18-a206-4028-a903-0e89dd14a14f.png)
![Yaru-bark-dark](https://user-images.githubusercontent.com/59381215/203839848-b6ab63fc-5077-42ae-8a6e-5b920ed3a79a.png)
![Yaru-blue](https://user-images.githubusercontent.com/59381215/203839852-b6093026-cd00-4be3-99f7-88cb813e7cf9.png)
![Yaru-blue-dark](https://user-images.githubusercontent.com/59381215/203839857-5121e446-5c1a-413d-8433-900c2e2476ac.png)
![Yaru-dark](https://user-images.githubusercontent.com/59381215/203839859-f8fba5bd-a9a7-46e8-86c8-7a1b0bee296e.png)
![Yaru-magenta](https://user-images.githubusercontent.com/59381215/203839863-85cbcf3d-eb35-4e64-92d4-205bb1cc1713.png)
![Yaru-magenta-dark](https://user-images.githubusercontent.com/59381215/203839868-ac2c65bb-d6e9-4ea4-9f06-47b70f2531fe.png)
![Yaru-mate](https://user-images.githubusercontent.com/59381215/203839870-4784ec76-5706-4264-9a72-9c9655dec3e4.png)
![Yaru-mate-dark](https://user-images.githubusercontent.com/59381215/203839872-ed5c1d59-fa30-46ac-bad0-f3ce7dd5ba62.png)
![Yaru-olive](https://user-images.githubusercontent.com/59381215/203839876-d06c58cd-b0ca-4a8e-aa46-43e39c8f4ddd.png)
![Yaru-olive-dark](https://user-images.githubusercontent.com/59381215/203839879-cd106be4-90d2-4a98-a6db-522ffab2a6f1.png)
![Yaru-prussiangreen](https://user-images.githubusercontent.com/59381215/203839883-ce4e8135-0c69-4def-a827-3f55c7fd2128.png)
![Yaru-prussiangreen-dark](https://user-images.githubusercontent.com/59381215/203839888-acf1e4ff-bf81-4113-b241-f1f8e44890a1.png)
![Yaru-purple](https://user-images.githubusercontent.com/59381215/203839892-bb0f68a6-3f68-40d8-815e-9d2ea6a5c0ba.png)
![Yaru-purple-dark](https://user-images.githubusercontent.com/59381215/203839896-f7f16ba6-ccd4-4de8-9f08-af5f8ba74216.png)
![Yaru-red](https://user-images.githubusercontent.com/59381215/203839905-698fa0b7-1637-4f87-9705-468751bf6c3a.png)
![Yaru-red-dark](https://user-images.githubusercontent.com/59381215/203839906-aa2a15be-bb40-47bf-8e1b-279de8dc1229.png)
![Yaru-sage](https://user-images.githubusercontent.com/59381215/203839911-6a714b7d-9778-4173-8309-2175e5ab769b.png)
![Yaru-sage-dark](https://user-images.githubusercontent.com/59381215/203839916-7f7de49d-dd95-472f-b9b6-b0d8e415ab79.png)
![Yaru-viridian](https://user-images.githubusercontent.com/59381215/203839922-23d85f31-665b-46e8-8119-7f1d22b50bf5.png)
![Yaru-viridian-dark](https://user-images.githubusercontent.com/59381215/203839924-1ec2c9fb-2f4d-407a-9cd5-f6af48751adc.png)

**Comment by leigh123linux** [comment]
Yaru theme maintainer will need to do it.
