### ISSUE TITLE
lorem ipsum in system settings -> themes -> settings

### ISSUE THREAD

**Issue by awocrf** [linuxmint/cinnamon#11306]
* Cinnamon 5.4.12
 * mint 21
 * 64 bit

### Issue
lorem ipsum text in system settings -> themes -> settings

### Steps to reproduce
go to these settings
![image](https://user-images.githubusercontent.com/85415260/204100448-391990fe-5571-48b0-b7ad-b328cf0cf0b3.png)

**Comment by mtwebster** [comment]
It's just dummy text so you can test out scroll bar options.

https://en.wikipedia.org/wiki/Lorem_ipsum

**Comment by awocrf** [comment]
Oh...ok I was just going through settings and didn't even read what this one was for. Sorry!
