### ISSUE TITLE
Can't install to non-default location

### ISSUE THREAD

**Issue by hgdeoro** [linuxmint/Cinnamon#1130]
When trying to install to /opt/cinnamon-dev (with a normal, non-root user) I got a lot of:

    cp: cannot create regular file `/etc/xdg/menus/cinnamon-settings.menu': Permission denied

I've tried this using `./configure --prefix=/opt/cinnamon-dev`

I've seen that those files are copied from the `files/` directory. If I move `files/usr` to `files/opt/cinnamon-dev/usr` and `files/etc` to `files/opt/cinnamon-dev/etc`, then `make install` works.

But I don't know if the rest of Cinnamon will use the correct `/opt/cinnamon-dev` paths, or the hardcored on `/usr` (beside the manually compiled, I've the packages from Ubuntu PPA installed in my PC).

**Comment by lestcape** [comment]
This not appear to be an issue and @JosephMcc it's cleaning, please close it. If you are on Mint use the Mint forum for help.
