### ISSUE TITLE
Add "Shutdown after updates" button to shutdown menu when updates are running.

### ISSUE THREAD

**Issue by Jean28518** [linuxmint/cinnamon#11300]
### Problem:
If I want to shutdown my Linux Mint, the shutdown button is missing, when an update is running.
But I want to signalize now to the system that I want to shutdown it after the updates.

### Solution
Add a "Shutdown after updates" button to shutdown menu when updates are running.
(Displaying such a button while running system snapshots would be great also)

### Alternatives
Block Updates on specific timeframes.

**Comment by qwerty123a2** [comment]
just open terminal @Jean28518  and run sudo apt update && sudo apt upgrade && shutdown.

easy

**Comment by duracell80** [comment]
Very much needed for laptops, even if plugged in I'd want to be able to signal the shutdown after the updates had finished and then walk away. Rather than having to remember to come back and check possibly multiple times if I could shutdown yet or not.

**Comment by rogue-spectre** [comment]
The fact that the shutdown button is missing during automatic upgrade (like in xfce), induce that people tend to stop their computer via the physical button, adding by the way a potential break of update that need a "dpkg --configure -a" afterwards, that is not done practically by new adopters until some website need an upgrade of firefox or if they try to upgrade manually… resulting in the "execute dpkg --configure -a" error inducing a call to the IT Team to solve the problem.

**Comment by leigh123linux** [comment]
I believe this is the wrong approach, it would be easier to add the option to mintupdate to shutdown once complete.

https://github.com/linuxmint/mintupdate/issues
