### ISSUE TITLE
Keyboard layout indicator bugs

### ISSUE THREAD

**Issue by yesint** [linuxmint/cinnamon#11313]
```
 * Cinnamon version 5.14.12
 * Distribution - Mint 21
```

### Issue 1
When logging in the layout indicator is invisible in the vertical panel. Empty space is shown until mouse hover over it or layout changed by keyboard shortcut.

### Issue 2
If layout "Russian" is present in the list it is always set as default when logging in regardless of it's position in the list of layouts. 
This only applies to layout named just "Russian". If I choose "Russian (whatever)" the default layout is one which is the first in the list.

### Expected behaviour
1) Layout indicator have to be visible in the panel immediately when logging in.
2) The default layout should be the first layout in the list.

**Comment by yesint** [comment]
This bug persists in Mint 21.1 with Cinnamon 5.6.5

**Comment by linewelder** [comment]
I've also encountered the first issue recently, it seems to only take place when the panel is vertical and country flags are disabled. I'd like to work on it.

About the second issue, I didn't manage to replicate it.

**Comment by alexus26** [comment]
On mint 21.3 bug persists. When I installed mint 21.2 keyboard indicator worked properly. After update it does not work correctly.

**Comment by Kout** [comment]
I can confirm @alexus26, it happens all the time. I am using horizontal panel (standard position at the bottom of the screen) and country flags are off.
```
System:
  Kernel: 5.15.0-118-generic x86_64 bits: 64 compiler: gcc v: 11.4.0
    Desktop: Cinnamon 6.0.4 tk: GTK 3.24.33 wm: muffin vt: 7 dm: LightDM 1.30.0
    Distro: Linux Mint 21.3 Virginia base: Ubuntu 22.04 jammy
```

**Comment by disotocastro** [comment]
Having this bug with English (US) and  any other keyboard distribution in Spanish


`
  Desktop: Cinnamon v: 6.4.6 tk: GTK v: 3.24.41 wm: Muffin v: 6.4.1 vt: 7
    dm: LightDM v: 1.30.0 Distro: Linux Mint 22.1 Xia base: Ubuntu 24.04 noble
`
