### ISSUE TITLE
Machine awakes immediately after suspend (caused by changes to the screensaver code?)

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/cinnamon#11324]
```
 * Cinnamon version: 5.4.12
   - Please specify if you are using the daily builds PPA: I am not
     (https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds).
 * Distribution - Mint 21
 * Graphics hardware *and* driver used: Intel; Mesa
 * 32 or 64 bit: 64
 * Attach ~/.xsession-errors, or /var/log/syslog
 
[syslog.txt](https://github.com/linuxmint/cinnamon/files/10193920/syslog.txt)

 ```

### Issue

`systemctl suspend` suspends the computer for some five seconds, and then the lockscreen appears. Nor does the UI option to disable-monitor-on-idle work.

### Steps to reproduce

1) `$ systemctl suspend`
2) Wait.
3) See lockscreen.

### Expected behaviour

3 should occur only upon standard wake-up events.

### Other information
 
- Kernel 5.15.0

- I believe that this problem began after a recent update. The update in question might be the one that included an update to the screensaver / locker. Before doing that update I was using a preview version of the relevant package - and, I think, without any problems.

- The problem occurs on a ThinkPad X1C6. Within a few days I will be able to determine whether the problem affects another ThinkPad of mine (an X230), which runs the same version of Mint.

- Cf. #8882.

**Comment by LinuxOnTheDesktop** [comment]
Here is some further information.

`# echo freeze > /sys/power/state` _does_ work. Indeed: _after_ running that command (but before rebooting), `$ systemctl suspend` works and so does disable-monitor-after-<time _t_>!

Also: cf. perhaps [this problem](https://bugs.launchpad.net/ubuntu/+source/xorg/+bug/1922414?comments=all), described on the Ubuntu tracker?

I note finally that [this webpage](https://01.org/blogs/rzhang/2015/best-practice-debug-linux-suspend/hibernate-issues) contains useful steps for troubleshooting Linux suspend problems.

**Comment by LinuxOnTheDesktop** [comment]
As of today, `echo freeze >/sys/power/state` no longer circumvents the problem.

**Comment by t3hk0d3** [comment]
+1

**Comment by LinuxOnTheDesktop** [comment]
At present neither of my Mint machines - both of which are Lenovo laptops - have the problem. I am unsure why. (That the problem was intermittent makes testing tricky.) Possibly the cause of my current happy situation is the 'lidFix' code in this [script of mine](https://pastebin.com/E8m7FkDB). Another possible cause is the kernel I run: I am using a 6.1 kernel.

**Comment by LinuxOnTheDesktop** [comment]
The problem seems to be fixed.
