### ISSUE TITLE
Cinnamon 5.6.5 reports itself as 5.6.4

### ISSUE THREAD

**Issue by spsf64** [linuxmint/cinnamon#11331]
```
 * Cinnamon version (5.6.5)
   - Built/compiled  manually
 * Distribution - (Archlinux)
  * 64 bit
 
 ```

### Configuration info, if applicable

![565](https://user-images.githubusercontent.com/1877391/208154393-d7fac404-fecf-4296-8887-5d0c2833f44b.png)

**Comment by clefebvre** [comment]
It looks like a packaging problem.

The tag is fine, so is the meson bump. I can't reproduce it in mint either, it shows properly as 5.6.5.

It looks like you're running 5.6.4 still.

**Comment by spsf64** [comment]
Thanks for replying , I will double check what I did wrong, but pretty sure I downloaded this file: https://github.com/linuxmint/cinnamon/archive/refs/tags/5.6.5.tar.gz

**Comment by clefebvre** [comment]
Make sure you've got `project('Cinnamon', 'c', version : '5.6.5', meson_version : '>=0.47.0')` in your meson.build.

**Comment by spsf64** [comment]
> Make sure you've got `project('Cinnamon', 'c', version : '5.6.5', meson_version : '>=0.47.0')` in your meson.build.

O gosh, I'm so embarrassed, I made a big mistake here, for 3 times in a row... It is fixed and working now.
Sorry to bother you and thanks a LOT for this great project!!
Hope you and your family have a wonderful Christmas

**Comment by clefebvre** [comment]
Hey, no problem. We're all mostly human :)

Merry xmas to you too.
