### ISSUE TITLE
more clear visual selection when moving around with arrow keys

### ISSUE THREAD

**Issue by ghost** [linuxmint/cinnamon#11338]
Hi guys!

First of all I want to say that you are awesome! You do a really great job! Thank you for everything!
I want to suggest to improve the visual selection because the current behavior is not good enough; just see the examples what I mean:

I don not see where I am:(
[![shut-down.png](https://i.postimg.cc/YCK7hqYD/shut-down.png)](https://postimg.cc/7fVdR4BS)
You should make something like this; of course it is just an example; sorry for my drawing skills:)
[![shut-down-how-should-be.png](https://i.postimg.cc/fT03GyM8/shut-down-how-should-be.png)](https://postimg.cc/HVds5pcM)

Again, I do not  see where I am:(
[![accessibility.png](https://i.postimg.cc/15HthqLc/accessibility.png)](https://postimg.cc/CzRYbzMz)
Again, you should make something like this:
[![accessibility-how-should-be.png](https://i.postimg.cc/6p8yrQmr/accessibility-how-should-be.png)](https://postimg.cc/sMRjy3yx)

I just want to see clearly where I am when I am moving around with arrow keys.
So, I hope you got the idea!

Thank you and Good luck!

**Comment by DirkHaar** [comment]
This depends on the chosen theme.

Am 21. Dezember 2022 08:59:05 MEZ schrieb oleg-chumanov ***@***.***>:

**Comment by oleg-chumanov** [comment]
Hi there!
Hmm... I though about that!
I have tried all the possible themes (System Settings -> Themes -> Applications -> ...) and there is no one which I want (like on my screenshot). What Am I doing wrong?:(

**Comment by mlavi** [comment]
I have to agree, dependent on the theme, but even Settings > Accessibility > Visual Aids: High Contrast doesn't help.

**Comment by JosephMcc** [comment]
This has nothing to do with Cinnamon. It's the theme. You can see the indicator in every screenshot you posted. If you can't find a theme that gives you what you want, your best bet would just be to modify one that you like otherwise.
