### ISSUE TITLE
Mint 21.1 =gnome-disks app won't let me expand left section towards the right to allow seeing all of Disk's labels' names

### ISSUE THREAD

**Issue by motoryzen** [linuxmint/cinnamon#11332]
`nemo 5.6.1
System:
  Kernel: 6.0.0-1009-oem x86_64 bits: 64 compiler: N/A
    Desktop: Cinnamon 5.6.5 tk: GTK 3.24.33 wm: muffin dm: LightDM
    Distro: Linux Mint 21.1 Vera base: Ubuntu 22.04 jammy
Machine:
  Type: Desktop Mobo: ASRock model: X570 Taichi serial: <superuser required>
    UEFI: American Megatrends v: P4.60 date: 08/03/2021
Memory:
  RAM: total: 125.73 GiB used: 4.12 GiB (3.3%)
  RAM Report:
    permissions: Unable to run dmidecode. Root privileges required.
CPU:
  Info: 12-core model: AMD Ryzen 9 5900X bits: 64 type: MT MCP arch: Zen 3
    rev: 0 cache: L1: 768 KiB L2: 6 MiB L3: 64 MiB
  Speed (MHz): avg: 2532 high: 3700 min/max: 2200/4950 boost: enabled
    cores: 1: 2200 2: 2200 3: 2880 4: 2200 5: 3599 6: 2200 7: 2200 8: 2200
    9: 3700 10: 3598 11: 2200 12: 2200 13: 2200 14: 2200 15: 2200 16: 3700
    17: 2200 18: 2200 19: 2200 20: 2200 21: 2200 22: 3700 23: 2200 24: 2200
    bogomips: 177597
  Flags: avx avx2 ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm
Graphics:
  Device-1: AMD Ellesmere [Radeon RX 470/480/570/570X/580/580X/590]
    vendor: Sapphire Nitro+ driver: amdgpu v: kernel pcie: speed: 8 GT/s
    lanes: 8 ports: active: DP-1 empty: DP-2, DVI-D-1, HDMI-A-1, HDMI-A-2
    bus-ID: 0c:00.0 chip-ID: 1002:67df
  Display: x11 server: X.Org v: 1.21.1.3 driver: X: loaded: amdgpu,ati
    unloaded: fbdev,modesetting,vesa gpu: amdgpu display-ID: :0 screens: 1
  Screen-1: 0 s-res: 3840x2160 s-dpi: 96
  Monitor-1: DisplayPort-0 mapped: DP-1 model: ViewSonic XG320U
    res: 3840x2160 dpi: 138 diag: 812mm (32")
  OpenGL: renderer: AMD Radeon RX 580 Series (polaris10 LLVM 15.0.6 DRM
    3.48 6.0.0-1009-oem)
    v: 4.6 Mesa 22.3.1 - kisak-mesa PPA direct render: Yes
Audio:
  Device-1: AMD Ellesmere HDMI Audio [Radeon RX 470/480 / 570/580/590]
    vendor: Sapphire driver: snd_hda_intel v: kernel pcie: speed: 8 GT/s
    lanes: 8 bus-ID: 0c:00.1 chip-ID: 1002:aaf0
  Device-2: AMD Starship/Matisse HD Audio vendor: ASRock
    driver: snd_hda_intel v: kernel pcie: speed: 16 GT/s lanes: 16
    bus-ID: 0e:00.4 chip-ID: 1022:1487
  Sound Server-1: ALSA v: k6.0.0-1009-oem running: yes
  Sound Server-2: PulseAudio v: 15.99.1 running: yes
  Sound Server-3: PipeWire v: 0.3.48 running: yes
Network:
  Device-1: Realtek RTL8125 2.5GbE driver: r8169 v: kernel pcie:
    speed: 5 GT/s lanes: 1 port: f000 bus-ID: 0b:00.0 chip-ID: 10ec:8125
  IF: enp11s0 state: up speed: 1000 Mbps duplex: full mac: <filter>
Drives:
  Local Storage: total: 23.67 TiB used: 13.11 TiB (55.4%)
  ID-1: /dev/nvme0n1 vendor: Corsair model: Corsair MP600 PRO XT
    size: 3.64 TiB speed: 63.2 Gb/s lanes: 4 serial: <filter> temp: 25.9 C
  ID-2: /dev/sda vendor: Samsung model: SSD 860 EVO 1TB size: 931.51 GiB
    speed: 6.0 Gb/s serial: <filter>
  ID-3: /dev/sdb vendor: Samsung model: SSD 860 EVO 4TB size: 3.64 TiB
    speed: 6.0 Gb/s serial: <filter>
  ID-4: /dev/sdc vendor: Toshiba model: HDWR31G size: 14.55 TiB
    speed: 6.0 Gb/s serial: <filter>
  ID-5: /dev/sdd type: USB vendor: Micron model: 1100 MTFDDAK1T0TBN
    size: 953.87 GiB serial: <filter>
Partition:
  ID-1: / size: 97.87 GiB used: 29.11 GiB (29.7%) fs: ext4
    dev: /dev/nvme0n1p2
  ID-2: /boot/efi size: 510 MiB used: 5.2 MiB (1.0%) fs: vfat
    dev: /dev/nvme0n1p4
  ID-3: /home size: 3.48 TiB used: 62.06 GiB (1.7%) fs: ext4
    dev: /dev/nvme0n1p3
  ID-4: /media/taco/Timeshift Disk size: 937.83 GiB used: 64.93 GiB (6.9%)
    fs: ext4 dev: /dev/sdd1
  ID-5: /mnt/16TB Toshiba hdd size: 14.44 TiB used: 11.6 TiB (80.4%)
    fs: ext4 dev: /dev/sdc
  ID-6: /mnt/GoPro 1TB Backup size: 915.82 GiB used: 31 GiB (3.4%) fs: ext4
    dev: /dev/sda1
  ID-7: /mnt/sdb4 size: 3.44 TiB used: 1.32 TiB (38.5%) fs: ext4
    dev: /dev/sdb4
Swap:
  ID-1: swap-1 type: file size: 10 GiB used: 0 KiB (0.0%) priority: -2
    file: /swapfile
Sensors:
  System Temperatures: cpu: N/A mobo: N/A gpu: amdgpu temp: 51.0 C
  Fan Speeds (RPM): N/A gpu: amdgpu fan: 867
Repos:
  Packages: 2789 apt: 2772 flatpak: 17
  No active apt repos in: /etc/apt/sources.list
  Active apt repos in: /etc/apt/sources.list.d/google-chrome.list
    1: deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main
  Active apt repos in: /etc/apt/sources.list.d/kisak-kisak-mesa-jammy.list
    1: deb [arch=amd64 signed-by=/etc/apt/keyrings/kisak-kisak-mesa-jammy.gpg] https://ppa.launchpadcontent.net/kisak/kisak-mesa/ubuntu jammy main
  Active apt repos in: /etc/apt/sources.list.d/lunarg-vulkan-1.3.236-jammy.list
    1: deb https://packages.lunarg.com/vulkan/1.3.236 jammy main
    2: deb-src https://packages.lunarg.com/vulkan/1.3.236 jammy main
  Active apt repos in: /etc/apt/sources.list.d/official-package-repositories.list
    1: deb http://packages.linuxmint.com vera main upstream import backport
    2: deb http://mirror.mrjester.net/ubuntu/archive jammy main restricted universe multiverse
    3: deb http://mirror.mrjester.net/ubuntu/archive jammy-updates main restricted universe multiverse
    4: deb http://mirror.mrjester.net/ubuntu/archive jammy-backports main restricted universe multiverse
    5: deb http://security.ubuntu.com/ubuntu/ jammy-security main restricted universe multiverse
  Active apt repos in: /etc/apt/sources.list.d/openshot_developers-ppa-jammy.list
    1: deb [arch=amd64 signed-by=/etc/apt/keyrings/openshot_developers-ppa-jammy.gpg] https://ppa.launchpadcontent.net/openshot.developers/ppa/ubuntu jammy main
  Active apt repos in: /etc/apt/sources.list.d/teamviewer.list
    1: deb [signed-by=/usr/share/keyrings/teamviewer-keyring.gpg] https://linux.teamviewer.com/deb stable main
  Active apt repos in: /etc/apt/sources.list.d/winehq-focal.sources
    1: deb [arch=amd64 i386] https://dl.winehq.org/wine-builds/ubuntu focal main
  Active apt repos in: /etc/apt/sources.list.d/winehq-jammy.sources
    1: deb [arch=amd64 i386] https://dl.winehq.org/wine-builds/ubuntu jammy main
Info:
  Processes: 462 Uptime: 33m Init: systemd v: 249 runlevel: 5 Compilers:
  gcc: 11.3.0 alt: 11 Shell: Bash v: 5.1.16 running-in: gnome-terminal
  inxi: 3.3.13
Press enter to close

`

### Problem

Gnome-disks application since at least 21.1 ( possibly 21.0 ) won't let me expand the left section towards the right enough to be able to read all of the drives' labels

### Steps to reproduce.  

Launch gnome-disks and try to move your mouse cursor on the extremely thin divider vertical line that separates the Disks list section on the left from the majority-sized righthand side that only deals with the particular drive you have selected...no ... <->  icon appears which used to in guaranteed Mint 20.3 and older versions.

### Expected behaviour

The <->  icon to show up replacing my mouse cursor as long as I have it positioned on the vertical separator line and the ability to hold left click and move the mouse left or right to shrink or expand the left hand section

### Other information

It doesn't matter how I launch gnome-disks application,  lack of left-hand section expansions is still there.
### Configuration info, if applicable
If this bug report is related to an Applet, Desklet or Extension, please paste (or use a pastebin service) the offending extension's settings, if it has any.  You can obtain this by opening its configuration, clicking the 'hamburger' button in the upper-right corner of the window, and selecting "Export to a file". **Please be sure to review the contents and remove any personal data it may contain.**

---   screenshot below -==--

![Mint 21 1 won't let me expand left section to the right to enable seeing entire disks' labels' names](https://user-images.githubusercontent.com/71474191/208267403-ac0c69b3-3539-45f2-ad35-11d86c6228bd.jpg)

**Comment by mtwebster** [comment]
This is an issue with gnome-disks, it looks like it's been reported a whiel back:
https://gitlab.gnome.org/GNOME/gnome-disk-utility/-/issues/229

A 'bump' there probably wouldn't hurt.
