### ISSUE TITLE
Cinnamon Settings / Keyboard Applet crashes on the Layout tab

### ISSUE THREAD

**Issue by vladrob** [linuxmint/cinnamon#11330]
**The following is the outcome of $ inxi -Fxxxr**z

 System:
  Kernel: 5.15.0-56-generic x86_64 bits: 64 compiler: gcc v: 11.3.0
    Desktop: Cinnamon 5.4.12 tk: GTK 3.24.33 info: cairo-dock wm: Mutter vt: 7
    dm: LightDM 1.30.0 Distro: Linux Mint 21 Vanessa base: Ubuntu 22.04 jammy
Machine:
  Type: Desktop System: Hewlett-Packard product: HP Compaq Pro 6305 MT v: N/A
    serial: <superuser required> Chassis: type: 6 serial: <superuser required>
  Mobo: Hewlett-Packard model: 1850 serial: <superuser required>
    UEFI: Hewlett-Packard v: K06 v02.57 date: 08/16/2013
CPU:
  Info: dual core model: AMD A4-6300B APU with Radeon HD Graphics bits: 64
    type: MT MCP smt: enabled arch: Piledriver rev: 1 cache: L1: 96 KiB
    L2: 1024 KiB
  Speed (MHz): avg: 3427 high: 3521 min/max: 1800/3700 boost: enabled
    cores: 1: 3334 2: 3521 bogomips: 14772
  Flags: avx ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm
Graphics:
  Device-1: NVIDIA GF108 [GeForce GT 440] driver: nvidia v: 390.157 pcie:
    speed: 2.5 GT/s lanes: 4 bus-ID: 01:00.0 chip-ID: 10de:0de0 class-ID: 0300
  Device-2: Logitech QuickCam Pro 9000 type: USB
    driver: snd-usb-audio,uvcvideo bus-ID: 1-2:6 chip-ID: 046d:0990
    class-ID: 0102 serial: <filter>
  Display: x11 server: X.Org v: 1.21.1.3 driver: X: loaded: nvidia
    unloaded: fbdev,modesetting,nouveau,vesa gpu: nvidia display-ID: :0
    screens: 1
  Screen-1: 0 s-res: 1920x1080 s-dpi: 101 s-size: 483x272mm (19.0x10.7")
    s-diag: 554mm (21.8")
  Monitor-1: VGA-0 res: 1920x1080 hz: 60 dpi: 102
    size: 476x268mm (18.7x10.6") diag: 546mm (21.5")
  OpenGL: renderer: GeForce GT 440/PCIe/SSE2 v: 4.6.0 NVIDIA 390.157
    direct render: Yes
Audio:
  Device-1: AMD FCH Azalia vendor: Hewlett-Packard driver: snd_hda_intel
    v: kernel bus-ID: 00:14.2 chip-ID: 1022:780d class-ID: 0403
  Device-2: NVIDIA GF108 High Definition Audio driver: snd_hda_intel
    v: kernel pcie: speed: 5 GT/s lanes: 4 bus-ID: 01:00.1 chip-ID: 10de:0bea
    class-ID: 0403
  Device-3: Logitech QuickCam Pro 9000 type: USB
    driver: snd-usb-audio,uvcvideo bus-ID: 1-2:6 chip-ID: 046d:0990
    class-ID: 0102 serial: <filter>
  Sound Server-1: ALSA v: k5.15.0-56-generic running: yes
  Sound Server-2: PulseAudio v: 15.99.1 running: yes
  Sound Server-3: PipeWire v: 0.3.48 running: yes
Network:
  Device-1: Broadcom NetXtreme BCM5761 Gigabit Ethernet PCIe
    vendor: Hewlett-Packard driver: tg3 v: kernel pcie: speed: 2.5 GT/s
    lanes: 1 port: N/A bus-ID: 04:00.0 chip-ID: 14e4:1681 class-ID: 0200
  IF: enp4s0 state: up speed: 100 Mbps duplex: full mac: <filter>
Drives:
  Local Storage: total: 1.47 TiB used: 1017.74 GiB (67.4%)
  ID-1: /dev/sda vendor: Kingston model: SHFS37A120G size: 111.79 GiB
    speed: 6.0 Gb/s type: SSD serial: <filter> rev: BBF0 scheme: GPT
  ID-2: /dev/sdb vendor: Western Digital model: WD5000AAKX-60U6AA0
    size: 465.76 GiB speed: 6.0 Gb/s type: HDD rpm: 7200 serial: <filter>
    rev: 1H18 scheme: MBR
  ID-3: /dev/sdc type: USB vendor: Seagate model: ST1000LM025 HN-M101ABB
    size: 931.51 GiB type: HDD rpm: 5400 serial: <filter> rev: 1306 scheme: MBR
Partition:
  ID-1: / size: 108.98 GiB used: 93.54 GiB (85.8%) fs: ext4 dev: /dev/sda2
  ID-2: /boot/efi size: 511 MiB used: 5.2 MiB (1.0%) fs: vfat
    dev: /dev/sda1
Swap:
  ID-1: swap-1 type: file size: 2 GiB used: 0 KiB (0.0%) priority: -2
    file: /swapfile
Sensors:
  System Temperatures: cpu: 7.0 C mobo: N/A gpu: nvidia temp: 33 C
  Fan Speeds (RPM): N/A gpu: nvidia fan: 52%
Repos:
  Packages: 2936 apt: 2912 flatpak: 13 snap: 11
  No active apt repos in: /etc/apt/sources.list
  Active apt repos in: /etc/apt/sources.list.d/official-package-repositories.list
    1: deb http://mint.celtis.net vanessa main upstream import backport
    2: deb http://ubuntu.ipacct.com/ubuntu jammy main restricted universe multiverse
    3: deb http://ubuntu.ipacct.com/ubuntu jammy-updates main restricted universe multiverse
    4: deb http://ubuntu.ipacct.com/ubuntu jammy-backports main restricted universe multiverse
    5: deb http://security.ubuntu.com/ubuntu/ jammy-security main restricted universe multiverse
  Active apt repos in: /etc/apt/sources.list.d/skype-stable.list
    1: deb [arch=amd64] https://repo.skype.com/deb stable main
  Active apt repos in: /etc/apt/sources.list.d/teamviewer.list
    1: deb [signed-by=/usr/share/keyrings/teamviewer-keyring.gpg] https://linux.teamviewer.com/deb stable main
  Active apt repos in: /etc/apt/sources.list.d/winehq.list
    1: deb [signed-by=/usr/share/keyrings/winehq.gpg] http://dl.winehq.org/wine-builds/ubuntu/ jammy main
Info:
  Processes: 246 Uptime: 20h 5m wakeups: 29 Memory: 15.58 GiB
  used: 4.87 GiB (31.2%) Init: systemd v: 249 runlevel: 5 Compilers:
  gcc: 11.3.0 alt: 11 Shell: Bash v: 5.1.16 running-in: gnome-terminal
  inxi: 3.3.13
 ```

### Issue

I am working most of the time with text so it's quite important for me to quick switch the languages with a keyboard shortcut. After a fresh install of Linux Mint 21 Cinnamon ed. however a problem occurred which persist and I cannot find solution to: the keyboard shortcut which I normally set Alt+Shift stopped working two months after the install. When I tried to reassign the shortcut I found I cannot enter the Keyboard Layout Settings (Keyboard/Layouts/Settings). Every time I try to open it it crashes. Now the only way to switch between languages is by mouse clicking. I couldn't find someone experiencing a similar problem in the Forum so I decided to ask devs for help.


### Steps to reproduce



### Expected behaviour



### Other information


### Configuration info, if applicable

**The following is the outcome of  $ cinnamon-settings**

 (cinnamon-settings.py:5274): Gtk-CRITICAL **: 18:39:42.643: gtk_widget_get_toplevel: assertion 'GTK_IS_WIDGET (widget)' failed
dbus[5274]: arguments to dbus_message_iter_append_basic() were incorrect, assertion "_dbus_check_is_valid_utf8 (*string_p)" failed in file ../../../dbus/dbus-message.c line 2760.
This is normally a bug in some application using the D-Bus library.

  D-Bus not built with -rdynamic so unable to print a backtrace

**Comment by icarter09** [comment]
@vladrob could you provide the steps to reproduce the issue? Thanks.

**Comment by vladrob** [comment]
@icarter09 I don't know how to "provide the steps". I am not a tech person. At a certain time the keyboard shortcut stopped working and when I tried to change the settings in Keyboard/Layout tab I found the Settings crash every time I try to open it. If you can tell me where can I look I will copy and share the data.

**Comment by icarter09** [comment]
Sorry I should have explained that better. When I asked for the "steps", I was looking for a something like...

1. Open Menu
2. Click "Keyboard"
3. another step
4. and another

Just to make sure I was following exactly what you were doing so I could reproduce the issue and begin to debug. Thanks.

**Comment by vladrob** [comment]
Ok, now I understand. So, that's what I do:

1. Click the Flag icon on the panel.
2. Click on Keyboard Settings
3. Click on Layouts tab
4. Click on Settings (down right corner)
5. Crash follows and the window closes

That pattern repeats no matter how many times I try. The same is when I get there via Menu/System Settings/Keyboard/Layout tab/Settings. The crash follows and I start from the beginning.
Thank you @icarter09 for your help!

**Comment by icarter09** [comment]
@vladrob could you try starting the "Keyboard" from the terminal...

 `cinnamon-settings keyboard`

...and providing the output when the crash occurs? Thanks.

**Comment by vladrob** [comment]
This is the outcome from the terminal:

```
/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py:442: DeprecationWarning: Gtk.Window.set_wmclass is deprecated
  self.window.set_wmclass(wm_class, wm_class)
Loading Keyboard module

(cinnamon-settings.py:6503): Gtk-CRITICAL **: 13:55:17.920: gtk_widget_get_toplevel: assertion 'GTK_IS_WIDGET (widget)' failed
dbus[6503]: arguments to dbus_message_iter_append_basic() were incorrect, assertion "_dbus_check_is_valid_utf8 (*string_p)" failed in file ../../../dbus/dbus-message.c line 2760.
This is normally a bug in some application using the D-Bus library.

  D-Bus not built with -rdynamic so unable to print a backtrace
```

**Comment by vladrob** [comment]
This is the outcome from the terminal:

```
/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py:442: DeprecationWarning: Gtk.Window.set_wmclass is deprecated
  self.window.set_wmclass(wm_class, wm_class)
Loading Keyboard module

(cinnamon-settings.py:6503): Gtk-CRITICAL **: 13:55:17.920: gtk_widget_get_toplevel: assertion 'GTK_IS_WIDGET (widget)' failed
dbus[6503]: arguments to dbus_message_iter_append_basic() were incorrect, assertion "_dbus_check_is_valid_utf8 (*string_p)" failed in file ../../../dbus/dbus-message.c line 2760.
This is normally a bug in some application using the D-Bus library.

  D-Bus not built with -rdynamic so unable to print a backtrace
```

**Comment by correctmost** [comment]
This bug seems similar to https://github.com/linuxmint/cinnamon/issues/8419 and https://github.com/linuxmint/cinnamon/issues/7831.

Are you using a language like Russian or Bulgarian?

**Comment by vladrob** [comment]
Yes, I'm using Bulgarian language.

На пн, 22.01.2024 г., 15:23 ч. correctmost ***@***.***>
написа:
