### ISSUE TITLE
Mouse pointer changing.

### ISSUE THREAD

**Issue by stan-raynell** [linuxmint/cinnamon#11341]
System:
  Kernel: 5.15.0-56-generic x86_64 bits: 64 compiler: gcc v: 11.3.0 Desktop: Cinnamon 5.6.5
    tk: GTK 3.24.33 wm: muffin dm: LightDM Distro: Linux Mint 21.1 Vera base: Ubuntu 22.04 jammy

Regardless of the selected pointer theme mouse pointer changes to the new default Bibata-Modern-Classic in many newly launched applications. For example, in XnView MP it shows Bibata black arrow within the main window and the proper pointer (e.g. DMZ white) over the titlebar. In Google Chrome and Telegram Desktop whenever a "hand" pointer should be displayed Bibata one is shown. Firefox, on the other hand, is completely unaffected by this issue. Even in terminal the pointer resets to Bibata.

UPD. `sudo update-alternatives --config x-cursor-theme` from https://forums.linuxmint.com/viewtopic.php?f=208&t=387634 helped. A reboot is needed.

**Comment by Angedestenebres** [comment]
Hey :cat: 

In fact, I got a similar issue after the update of Linux Mint 21.1 and I noticed it happened only with Qt apps. The given command was not working even with a reboot.

To fix the issue on my side, I edited the following file: /usr/share/icons/default/index.theme like that:

```
[Icon Theme]
Name=Bibata-Modern-Classic
Inherits=Bibata-Modern-Classic
```

No reboot needed to see the change and even after reboot all is fine!

I guess I got the issue because I installed breeze theme and used it in the past. I can't reproduce that in VM but I always used default theme.

**Comment by Bilal-Z** [comment]
fix suggested by @Angedestenebres works but reboot was required in my case.

changed `/usr/share/icons/default/index.theme` to

```
[Icon Theme]
Name=DMZ-White
Inherits=DMZ-White
```

**Comment by jilroy** [comment]
Same issue in gnome terminal when using tmux.

I think the proper workaround is to use, as @stan-raynell  mentionned:

`sudo update-alternatives --set x-cursor-theme /usr/share/icons/DMZ-White/cursor.theme
`

No reboot is needed. I just had to restart gnome terminal.

**Comment by Angedestenebres** [comment]
Hey @darkguset 

For the login screen, the theme can be changed in System settings > Window login:

![Screenshot from 2022-12-23 08-43-01](https://user-images.githubusercontent.com/21110485/209295309-ac70e07c-08d4-4b52-83f1-b7d41e3de099.png)

In the first tab, you have a part theme for that including cursors :)

**Comment by darkguset** [comment]
Thank you @Angedestenebres!
