### ISSUE TITLE
Battery Indicator Not Updating Immediately

### ISSUE THREAD

**Issue by calebchris000** [linuxmint/cinnamon#11357]
Hello Mint Developers,

I am writing to report an issue I am experiencing with the battery indicator on my Mint system. Specifically, the indicator does not seem to be updating immediately when I unplug or plug in my laptop. This is causing problems for me because I use Conky to monitor my system's battery status, and the indicator is out of sync with Conky's readings.

I am using Mint version XX on a XXX laptop with XXX operating system. I have tried troubleshooting the issue by checking for updates and restarting my system, but the problem persists.

I have included the steps to reproduce the issue below:

    Plug in my laptop to a power source
    Observe that the battery indicator does not immediately show that it is charging
    Open Conky and observe that it correctly shows the battery as charging

I would greatly appreciate if this issue could be addressed. Thank you for your help.

**Comment by timur-g** [comment]
You are using Mint XX? You should write which. And see if the same as #12211 that is marked resolved.

**Comment by JosephMcc** [comment]
Closing this. We have an issue template for a reason. Things like Os and Cinnamon version are relevant. You can't provide it, we can't do much about this.
