### ISSUE TITLE
Disable middle-click paste

### ISSUE THREAD

**Issue by jez9999** [linuxmint/cinnamon#11358]
As far as I can tell, [this bug](https://github.com/linuxmint/cinnamon/issues/8450) was silently closed for no apparent reason.  Middle-click to paste is apparently "built in" to XOrg.  If that's true, how does Gnome offer the feature to disable middle-click paste in their tweaks tool (which by the way doesn't work on Cinnamon; it doesn't change the behaviour at all)?

![01-how-to-disable-middle-mouse-button-click-paste-on-ubuntu-20-04-focal-fossa-linux](https://user-images.githubusercontent.com/793830/209670764-d1081b76-234f-4dca-b4fc-387b8d15200d.png)

Sorry, but Cinnamon devs just closing these requests as "no, it's built into XOrg" is a terrible response.  Cinnamon should provide a way to disable this "functionality".  It's extremely annoying and unexpected behaviour for anyone coming from Windows.  I'm used to middle clicking all over the place to scroll and to select input boxes, and *not* getting anything being pasted.  I cannot get used to the middle-click paste functionality, and if Cinnamon is going to achieve its stated goal of "making users feel at home with an easy-to-use and comfortable desktop experience", it should definitely offer an official option to disable this behaviour, just like Gnome does.

**Comment by mtwebster** [comment]
Sometimes capabilities and features change in libraries, or long-standing truths become invalid. and we miss the parade that announces these changes, or they get buried amongst other things, to our sorrow.

Open or create `~/.config/gtk-3.0/settings.ini` and add:

```
[Settings]
gtk-enable-primary-paste=false
```

Put it under the existing [Settings] heading if the file already existed.

**Comment by jez9999** [comment]
Whilst that does work nicely for GTK apps, middle click paste still happens in, say, Chrome.

**Comment by sarath11kb** [comment]
I found something here @jez9999  [Link](https://www.maketecheasier.com/disable-middle-mouse-click-to-paste-feature-in-linux-quick-tips/) .
<img width="876" alt="Screenshot 2022-12-28 at 1 29 27 PM" src="https://user-images.githubusercontent.com/97025829/209779052-eda3783e-093b-418f-9de3-d252c608fb00.png">

Heres a link to the [extension](https://chrome.google.com/webstore/detail/autoscroll/occjjkgifpmdgodlplnacmkejpdionan)

**Comment by mfreeman72** [comment]
It took me a while to get used to middle-click paste, too. But wow! Once you get used to it, it's an amazing feature that I can't do without now that it's in my muscle memory! I highly recommend getting used to it. Yeah, it's not like Windows, but Linux isn't Windows. And you might actually find that some things work better in Linux, even if you aren't used to them at the moment. I definitely count middle-click paste as one of those things! I recommend giving yourself a chance to get used to using it. Personally, I've never actually used Windows much outside of a work environment (I came to Linux from 90's-00's MacOS and 80's-90's Atari OS at home), and I personally can't stand the way Windows does things. It has always made absolutely no sense to me, and things are such a mess in that OS. That said, I'm not demanding that Windows change when I do have to use it. It is what it is, and I just need to adjust my mindset when I'm using it. But, to be fair to your perspective, having options are always good. Just be kind about it, though, please.

**Comment by niciunu** [comment]
Looks like the MATE version for mouse settings has a "disable paste" option under "mouse settings".
A screenshot can be seen here: [https://forums.linuxmint.com/viewtopic.php?p=2298037](https://forums.linuxmint.com/viewtopic.php?p=2298037
)
(Maybe this info could help)
