### ISSUE TITLE
Cinnamon crashed when using Cinnamenu

### ISSUE THREAD

**Issue by haggen88** [linuxmint/cinnamon#11361]
```
 * Cinnamon version (5.6.5)
   - No PPA
 * Distribution - (Mint 21.1)
 * Graphics hardware *and* driver used:  Intel HD Graphics 4000 - Dell driver: i915 
 ```

### Issue
I recently upgraded from LM 21 to LM 21.1 and changed the cinnamon menu to Cinnamenu. I was using the computer as usual browsing the internet [Firefox] and using a couple of apps [poedit and xed] and when I used the menu the system crashed.

### Other information

[logs and report.zip](https://github.com/linuxmint/cinnamon/files/10310592/logs.and.report.zip)

https://termbin.com/0pp3

I only use 3 applets: Cinnamenu@json, qredshift@quintao and weather@mockturtl

**Comment by haggen88** [comment]
it happened again: [2-44.zip](https://github.com/linuxmint/cinnamon/files/10334510/2-44.zip)

**Comment by fredcw** [comment]
@haggen88 Was there something specific you was doing when it crashed, eg. scrolling, resizing the menu, typing in the search box, etc?

**Comment by haggen88** [comment]
I just had firefox running and a notepad... the crash happened when i clicked to open cinnamenu 5.1, it's random.

Btw the applet configuration:

Layout:
-Application view mode>Grid
-Sidebar location>Bottom
-Show favorites on sidebar>Apps only
-Application description placement>None

Behavior:
-activate categories on click
-enable autoscrolling
-open menu category >all applications

Search
-web search option>none

Appearance
-use a custom icon >linuxmint-logo-ring-symbolic

All other options disabled

**Comment by mtwebster** [comment]
Check if you have any applications or categories (or anything that gets displayed in a label) that have strange characters or anything that may be interpreted as an escape code  or part of one.. like &, <, >, etc...

It looks like it's failing to process a string that is intended to be used as markup (vs straight text) though it's mostly a guess from looking at the partial trace and pango's source.

I would suspect these areas - 
```
[02:12:23 PM] mtwebster@mintbox3:~/bin/cinnamon-spices-applets/Cinnamenu@json/files/Cinnamenu@json/4.0[master]> gr markup
utils.js
108:        this.tooltip.get_clutter_text().set_use_markup(true);
195:        let markup = str.slice(0, foundPosition) + '<b>' +
198:        return {score: score, result: markup};

appsview.js
39:            this.icon.get_clutter_text().set_markup(this.app.emoji);
68:        let markup = '<span>' + name + '</span>';
71:            markup += '\n<span size="small">' + description + '</span>';
74:        clutterText.set_markup(markup);

categoriesview.js
32:                this.icon.get_clutter_text().set_markup('🌷');
[02:12:25 PM] mtwebster@mintbox3:~/bin/cinnamon-spices-applets/Cinnamenu@json/files/Cinnamenu@json/4.0[master]> 
```
Maybe some sanitizing needs to be done before you `set_markup()`. Also, I'm not sure you even need to use markup for the emojis.

**Comment by haggen88** [comment]
@fredcw the only constant is that I have Firefox maximized [w 3 tabs} and clicking on Cinnamenu takes a second before it crashes Cinnamon. I checked and I had no problems with memory consumption or CPU load.

Btw it happened again: [1405_crash.zip](https://github.com/linuxmint/cinnamon/files/10361838/1405_crash.zip)

**Comment by fredcw** [comment]
@haggen88 Was this problem still occurring? Tbh, I didn't have the first clue how to start debugging this. I tried running Firefox for a bit but nothing happened and I don't really understand the log files except for .xsession-errors.

**Comment by haggen88** [comment]
@fredcw I changed the laptop recently, so far there have been no problems with Cinnamenu. If I have another crash I will let you know.
