### ISSUE TITLE
[Feature Request] Add support for Material Cursors

### ISSUE THREAD

**Issue by sun95n** [linuxmint/Cinnamon#11376]
I'm very happy with the new version of Mint and I like the idea of ​​customizing the desktop with new icons and cursors. Maybe you guys can support [Material Cursors](https://github.com/varlesh/material-cursors) for a next version. They are super cute and come in various sizes. Also this is the [Pling](https://www.pling.com/p/1346778/) link.

![001](https://user-images.githubusercontent.com/120290802/210112093-9e926bf1-35ae-4b6e-ae3d-2e6ea5cb1b2d.png)

**Comment by Secret-chest** [comment]
I think they are super opinionated, even more so than Bibata. I'm working on a new cursor theme specifically for Mint.

**Comment by Secret-chest** [comment]
Also, this wouldn't be a problem to me, but some might say it's racist.

**Comment by JosephMcc** [comment]
This isn't really a cinnamon issue. The cursors are included by Mint as part of the distro. Not by Cinnamon.
