### ISSUE TITLE
Two settings windows, one from the system and other from the applet itself is confusing

### ISSUE THREAD

**Issue by danimesq** [linuxmint/cinnamon#11383]
Two settings windows for Notifications: one from cinnamon-settings and other from the applet itself.

Isn't that confusing?

![Screenshot from 2022-12-31 16-54-20](https://user-images.githubusercontent.com/6765277/210154459-638155eb-d1dd-4f18-8c0c-626132baa826.png)

Suggestion: all of the settings in one place, with a tab menu separating.

If you're interested, I can dig into how this could work, precisely.

**Comment by danimesq** [comment]
Same for the Network Manager, Sound, Power Manager and Calendar applets.

**Comment by Secret-chest** [comment]
The default applets aren't mandatory...

**Comment by rcalixte** [comment]
This was discussed in #11433. It should be safe to close this. Are there still further questions?
