### ISSUE TITLE
Whatsapp desktop double key pressed

### ISSUE THREAD

**Issue by Giorgio-IT** [linuxmint/cinnamon#11399]
```
 *System:
  Kernel: 5.15.0-41-generic x86_64 bits: 64 compiler: gcc v: 11.2.0 Desktop: Cinnamon 5.4.12
    tk: GTK 3.24.33 wm: Mutter dm: LightDM Distro: Linux Mint 21 Vanessa base: Ubuntu 22.04 jammy
 
 * Distribution Mint 21
 ```

**Comment by clefebvre** [comment]
Thanks @Giorgio-IT. This version of whatsapp desktop isn't maintained anymore. We removed the package from the repositories.

I'd recommend Whatsie (Flatpak) from the sofware manager as an alternative.

**Comment by Giorgio-IT** [comment]
Thanks Clement.
Installing Whatsie include Flatpack and download 927 MB, use 3,1 GB of hard disk space and having frequent huge updates of Flatpack.
I think the best solution could be a Mint package of Whatsie or similar software without Flatpack.

**Comment by clefebvre** [comment]
Not for this. It's a proprietary software (whatsapp itself), this is always going to be a catchup game and I think flatpak is better able to do this than a frozen package base.

Alternatively you can make a web app using the Web App Manager which points to https://web.whatsapp.com/.
