### ISSUE TITLE
box after draging applets

### ISSUE THREAD

**Issue by randomUser453** [linuxmint/cinnamon#11398]
```
 Cinnamon version (cinnamon 5.6.5)
 Distribution - (Mint 21.1)
 Nvidia rtx 3060ti*and* nvidia-driver-515
 64 bit

### Issue
when I drag an applet from the 2. taskbar arround my desktop, a box of your colour you chose for your system pops up.. it doesn't go away even after i let go off that applet i was draging arround.


### Steps to reproduce
1. add a second taskbar to your Desktop
2. add an applet to the second Taskbar
3. activate the taskbar editing mode (the function where you can move your start menu etc. to the middle off the taskbar or else where)
5. drag any applet from the second taskbar arround and then let go of it


### Expected behaviour
that box shuldn't even appear


### Other information
- it is annoying.. but can be fixed by dragging arround a Desklet

### Configuration info, if applicable
If this bug report is related to any Applet

![Bildschirmfoto vom 2023-01-06 15-17-43](https://user-images.githubusercontent.com/117298087/211035984-af1050dc-ff92-4e0b-b753-313cd408c44d.png)
![Bildschirmfoto vom 2023-01-06 15-16-23](https://user-images.githubusercontent.com/117298087/211036002-5ea567ba-a261-44e5-920f-6f1da3a8a6d2.png)




https://user-images.githubusercontent.com/117298087/211037506-bb3997ce-c467-497f-90f4-b01cac2a3393.mp4

**Comment by anaximeno** [comment]
Video cont

> ```
>  Cinnamon version (cinnamon 5.6.5)
>  Distribution - (Mint 21.1)
>  Nvidia rtx 3060ti*and* nvidia-driver-515
>  64 bit
> 
> ### Issue
> when I drag an applet from the 2. taskbar arround my desktop, a box of your colour you chose for your system pops up.. it doesn't go away even after i let go off that applet i was draging arround.
> 
> 
> ### Steps to reproduce
> 1. add a second taskbar to your Desktop
> 2. add an applet to the second Taskbar
> 3. activate the taskbar editing mode (the function where you can move your start menu etc. to the middle off the taskbar or else where)
> 5. drag any applet from the second taskbar arround and then let go of it
> 
> 
> ### Expected behaviour
> that box shuldn't even appear
> 
> 
> ### Other information
> - it is annoying.. but can be fixed by dragging arround a Desklet
> 
> ### Configuration info, if applicable
> If this bug report is related to any Applet
> 
> ![Bildschirmfoto vom 2023-01-06 15-17-43](https://user-images.githubusercontent.com/117298087/211035984-af1050dc-ff92-4e0b-b753-313cd408c44d.png)
> ![Bildschirmfoto vom 2023-01-06 15-16-23](https://user-images.githubusercontent.com/117298087/211036002-5ea567ba-a261-44e5-920f-6f1da3a8a6d2.png)
> 
> 
> 
> 
> https://user-images.githubusercontent.com/117298087/211037506-bb3997ce-c467-497f-90f4-b01cac2a3393.mp4
> ```

Video:

https://user-images.githubusercontent.com/117298087/211037506-bb3997ce-c467-497f-90f4-b01cac2a3393.mp4
