### ISSUE TITLE
Bluetooth mouse not working after upgrade. Mint19 to Mint21

### ISSUE THREAD

**Issue by Gort400** [linuxmint/cinnamon#11395]
My Logitech Bluetooth mouse, MX Anywhere 2, worked flawlessly on Mint19 for many years. Last month I upgraded to Mint21. 
Now is only works for a few minutes after power up of Mint21. Then it quits working. If I power down and back up, it again will work for a few minutes...then quit. Something seems to be wrong with the new Bluetooth. I am on the same laptop Mint 19 was working on. Dell M6700.

**Comment by janstanka** [comment]
In Linux Mint 21 Blueman replaces Blueberry. May be this is the reason. 
In my case I noticed malfunctional mic mute button on my Sandberg Bluetooth Office Headset Pro+  after upgrade to Mint 21.

**Comment by Gort400** [comment]
That may be it. I never had any problems with the prior, Blueberry. Cant use the Bluetooth mouse anymore. I had to go back to a wired mouse.  It disconnects and never reconnects every time Mint21 starts. I wonder what changed in Blueman to make it not as robust???

**Comment by Vivek1078** [comment]
I am not able to connect any Bluetooth device even after updating it to latest version though its Bluetooth is working properly.

**Comment by leigh123linux** [comment]
This isn't a cinnamon issue.

https://github.com/linuxmint/blueman/issues
