### ISSUE TITLE
Touchpad changes screens by itself while typing

### ISSUE THREAD

**Issue by username227** [linuxmint/cinnamon#11408]
```
 * Cinnamon version (cinnamon --version)
   - Please specify if you are using the daily builds PPA
     (https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds).
 * Distribution - (Mint 21, Arch, Fedora 37, etc...)
 * Graphics hardware *and* driver used
 * 32 or 64 bit
 * Attach ~/.xsession-errors, or /var/log/syslog
 ```
I'm using Cinnamon 5.6.5-1 on Arch. I'm running graphics on AMD (driver in kernel) and Nvidia (525.78.01) 64 bit

### Issue

There was an update to some cinnamon packages yesterday, 1/7/23. These included cinnamon-desktop and others. Since that update, the touchpad has been causing major problems. I would be typing normally on my laptop, and then the screen changes since (apparently) the touchpad thinks i've brushed against it. I am not doing anything differently than normal, however, and this has never been an issue before. 

I attempted to downgrade the package cinnamon-desktop to the prior version (5.6.0-1) and it seemed like everything was working fine again. (However, this broke other features in cinnamon since I only downgraded that particular package to see what would happen).

### Steps to reproduce
Simply using the computer and attempting to type something on a laptop, which would have your hands near the touchpad, would be enough to cause the problem for me.

### Expected behavior
Something must have changed something about the way the touchpad is interacting with the new version of cinnamon. I would expect it to act normally - i.e. not to switch screens by itself while I am typing something, making the computer pretty much unusable.

### Other information
The temporary workaround I am using is to disable to touchpad (and use an external mouse). When I disable the touchpad through cinnamon settings, however, the buttons still operate (but i'm not including this in the bug report because that's already a separate issue from two weeks ago; I don't know if it's related). 

### Configuration info, if applicable
If this bug report is related to an Applet, Desklet or Extension, please paste (or use a pastebin service) the offending extension's settings, if it has any.  You can obtain this by opening its configuration, clicking the 'hamburger' button in the upper-right corner of the window, and selecting "Export to a file". **Please be sure to review the contents and remove any personal data it may contain.**

**Comment by mtwebster** [comment]
Check that 'tap to click' is disabled, the default was changed (to match previous releases)

**Comment by username227** [comment]
> Check that 'tap to click' is disabled, the default was changed (to match previous releases)

Yes, that seemed to do the trick. You guys might want to consider changing defaults like that only for new installs, not for current ones. Thanks so much for your help.
