### ISSUE TITLE
Cannot personalize window borders in Mint 21.1 + Cinnamon

### ISSUE THREAD

**Issue by harmin-parra** [linuxmint/cinnamon#11404]
```
 * Linuw Mint 21.1
 * Cinnamon 5.6.5+vera
 * 64 bit
 ```

### Issue
It is not possible to personalize the window borders in Mint 21.1.
The feature was present in previous versions of Mint.

### Steps to reproduce
Open **System Settings**
Under **Appearance**, go to **Themes**

You can see that the option to change the window border is missing

### Expected behaviour
The option to change the window border is present

![Screenshot](https://user-images.githubusercontent.com/16239820/211200598-06b41435-8663-40c2-932d-b9accfb9aaa1.png)

**Comment by harmin-parra** [comment]
[screenshot](https://ibb.co/g7S5yg3)

**Comment by JosephMcc** [comment]
https://github.com/linuxmint/cinnamon/issues/11126

**Comment by harmin-parra** [comment]
Is it because that feature relies on Metacity, which is old and difficult to maintain ?
