### ISSUE TITLE
Login Screen Wallpaper

### ISSUE THREAD

**Issue by agentl074** [linuxmint/cinnamon#11410]
Would it be possible to use the existing beautiful Mint wallpapers to randomly select a new login screen background everytime you get to the login screen -- like Windows?

**Comment by duracell80** [comment]
I do something similar with blur, so I use python to create a blurry copy of my current wallpaper. With Windows, it may not pick them at random on every single reboot / boot. You'll have the same image for a few days maybe? Pseudo English to help write a script:

- Create a JPEG in /usr/share/backgrounds named login_random.jpg
- Upon reboot and as root randomly select and copy a background from /usr/share/backgrounds to that file
- Only if the last modified datetime of the login_random.jpg is x days old
- Or use Python PIL to do the same thing if the background file is a PNG, convert it to JPEG

- Search for "login window" in the "start menu" change the background to /usr/share/backgrounds/login_random.jpg
- Toggle off "draw user backgrounds"

Run on reboot in Cron
@reboot sh /usr/share/wallpapers/randomize_bg_login.sh

Or as a service
chmod 644 /etc/systemd/system/randomize_bg_login.service
systemctl enable randomize_bg_login.service
