### ISSUE TITLE
Cinnamon 5.4.12 & 5.6 reset corrupts 150% scaling with Font Selection > 1.2X

### ISSUE THREAD

**Issue by jkalexu** [linuxmint/cinnamon#11411]
Two, 4K monitor setup.
To reproduce:
With Font selection at 1.3X or 1.5X and display scaling at 150X, perform a CTL-ALT-ESC cinnamon reset to corrupt display scaling changing the 150% or 175% setting to something much larger while the display app shows it as now set to 100% and yet both monitor screens show panel, windows, etc. magnified beyond 200%.

If I set display app to 100% or 125% for both monitors this post cinnamon reset scaling problem doesn't occur.

Repeating the CTL-ALT-ESC Cinnamon reset again restores the scaling to the 150% it was supposed to be. This cycle can be repeated continuously. On the odd count resets the scaling is broken on the even resets it is restored. I make no changes to the display app while doing this.

Above bug does NOT occur if "Font Selection" is set to 1.0, 1.1 or 1.2X.
1.3X is particularly demonstrative of bug. 1.5X as well.

This behavior is reproducible on a Custom Desktop (AMD GPU) and Dell 7490 (Intel built-in GPU) laptop running the same environments.

Running Live Linux Mint 21.1 having Cinnamon 5.6.5, shows this bug as well. 

System:
  Kernel: 5.15.0-56-generic x86_64 bits: 64 compiler: gcc v: 11.3.0 Desktop: Cinnamon 5.4.12
    tk: GTK 3.24.33 wm: Mutter dm: LightDM Distro: Linux Mint 21 Vanessa base: Ubuntu 22.04 jammy
Linux mint 21.0 
MESA OpenGL renderer version: 22.0.5.

I also started a thread at:
[https://forums.linuxmint.com/viewtopic.php?p=2278844#p2278844](url)
###

**Comment by mtwebster** [comment]
https://github.com/linuxmint/muffin/commit/c3221924fdf409f820311c4e37ce9e6f912ff34b
