### ISSUE TITLE
The icon spacing on the desktop is not reproducible in LM21.1Cinnamon 

### ISSUE THREAD

**Issue by kuehhe1** [linuxmint/cinnamon#11413]
Problem: The icon spacing on the desktop is not reproducible in LM21.1Cinnamon

By re-clicking > Desktop > Adjust, two sliders allow the horizontal and vertical spacing of the icons to be adjusted.
Unfortunately, there are no scales on the sliders and no values are displayed for reproduction.

For testing we can use the terminal command:
`gsettings set org.gtk.Settings.Debug enable-inspector-keybinding true` 
and then: `re.-click > desktop > adjust`
followed by: `Ctrl & Shift & d`
Start the GTK inspector and select >properties< in the drop-down menu with the target (top left) after marking a slider and set >draw-value< to >true< with a double-click. Now you can see the value of the slider...

The test shows that it is possible to display the values. Unfortunately, this state is only temporary and is lost after closing the window: Desktop > Adjust.
Diskussion auf: https://www.linuxmintusers.de/index.php?topic=76471.msg990351#msg990351

It would be good for the Cinnamon design and the usability to add these scales and display of the set values, as already in the settings: Sound, as is already the case in the settings.

Question: is it possible to add this in a *.css and if so what is the exact name of the*.css?

System:
`~$ inxi -S
System:
  Host: LM21-1-Test Kernel: 5.15.0-57-generic arch: x86_64 bits: 64
    Desktop: Cinnamon v: 5.6.5 Distro: Linux Mint 21.1 Vera
`

Best regards kuehhe1

![Schreibtisch_Re-Klick_Anpassen_org-gtk-gsettings_Skal -Werte_1](https://user-images.githubusercontent.com/45901795/211632935-ca2aa550-3a72-4443-ad6e-2848c3f666a2.png)

EDIT 19.01.2023: Since the problem results from nemo a new topic was created: https://github.com/linuxmint/nemo/issues/3167

**Comment by DirkHaar** [comment]
I don't even find the customization settings at all in my German version. I see them in the context menu on the desktop of a VM with Mint 21.1 setup in English as "customize", in my German version I find "Schreibtisch alphabetisch sortieren" and "Anordnung feststellen" (a bad translation too, should read "..fixieren").

**Comment by kuehhe1** [comment]
Then you could attach your note there: https://github.com/linuxmint/nemo/issues/3167
Or even better, open a separate issue for "translate" ?

**Comment by DirkHaar** [comment]
This may somehow be connected to #11442, while I don't even get to the dialog mentioned above due to the context entry  missing.

**Comment by kuehhe1** [comment]
EDIT 19.01.2023: Since the problem results from nemo a new topic was created: linuxmint/nemo#3167
