### ISSUE TITLE
blank area on the far left icons (above Lock, below Files)

### ISSUE THREAD

**Issue by pakair** [linuxmint/cinnamon#11416]
blank area on the far left icons (above Lock, below Files). 

21.1 Cinnamon. 

I restarted Cinnamon, reset all settings to Defaults, restarted my pc but that empty area is still there. 

None of my other pc/laptops have that empty area (all 21.1, Cinnamon). 

The far left icons are not configurable from the editor.

![left menu](https://user-images.githubusercontent.com/17964012/211904077-42d3c474-2308-4e4c-8686-90fb92e2bf6e.png)

![ksnip_20230111-122413](https://user-images.githubusercontent.com/17964012/211904164-ba07b75d-50e0-4c54-aba8-4cee8d0b9641.png)

**Comment by mtwebster** [comment]
With its default configuration, the menu applet will make itself tall enough to fit all categories without scrolling. It will do that until it runs out of work-area, then will add a scrollbar.

You can change this by checking 'Use a fixed menu height' in the menu's settings, then adjusting the height yourself. Perhaps you've configured your other machines differently (such as turning off recent and places categories)

**Comment by pakair** [comment]
The "Used a fixed menu" is unclicked. I also unclicked "show Category Icons" and that blank area is gone.

Thank you.
