### ISSUE TITLE
[Missing] Bring back the New Window option from the Grouped window list context menu

### ISSUE THREAD

**Issue by sun95n** [linuxmint/cinnamon#11426]
I wanted to report this for a long time but I thought it would be fixed at some point, although **this still happens in** [Linux Mint 21.1 Vera](https://www.linuxmint.com/edition.php?id=302).

This option exists in [Linux Mint 20.0 Ulyana](https://www.linuxmint.com/edition.php?id=281) but **in later versions it suddenly disappeared.** Was this necessary or did they forget to implement it when rewriting the [applet code](https://github.com/linuxmint/cinnamon/tree/master/files/usr/share/cinnamon/applets/grouped-window-list%40cinnamon.org) at the time?

![002](https://user-images.githubusercontent.com/120290802/212503655-09888f87-f9c3-412a-ab8e-f65bbb5e733d.png)
![001](https://user-images.githubusercontent.com/120290802/212503659-d1e84f2c-9d5e-4967-956b-4a4a7674ee87.jpg)

**Comment by mtwebster** [comment]
New Window will still appear in the menu if the application supports it. The problem before was it forced that item to appear on *all* programs  whether they supported it or not.
ref: https://github.com/linuxmint/cinnamon/commit/5eccc313c4d0cca46f00d63d136682203bd39cb2


An application can add support for it by having a 'New Window' 'action' in their desktop file:
https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s11.html

example:
https://github.com/linuxmint/xed/blob/master/data/xed.desktop.in.in#L15-L17
