### ISSUE TITLE
Improve Notifications Applet

### ISSUE THREAD

**Issue by dede53** [linuxmint/cinnamon#11433]
Hey,

recently I was quite annoyed by the notification applet. So I started to improve it. Right now I added a switch to disable all notifications and a do not disturb mode.
It is working fine, but I have a layout issue I'm unable to fix by myself yet. Maybe someone can help me:
Right now the DnD-mode looks like this:
![grafik](https://user-images.githubusercontent.com/13135177/212958659-87f5b82b-2cc0-4a17-9321-cf34e74e6a69.png)
And with the Dnd active it looks like this:
![grafik](https://user-images.githubusercontent.com/13135177/212958969-c7a76430-8ae8-4445-8f02-3430a862e74e.png)

Okay, but can be better. My goal is to get the label to the left and the cross to cancel the countdown the right. Same for the first image.

How is it working right now? I just took a imports.ui.popupMenu.PopupBaseMenuItem and put all icons/labels in there and hide/show them as necessary but lose all the spacing.

I would like to wrap all elements for both of the views together in a kind of widget and hide/show these widgets. I were unable to do so because a widget/floatbox never took the whole width so it couldn't help me out.

I tried to use two MenuItems and hide/show them but I didn't find a way to hide/show them.

So how can i replace items in a MenuItem without loosing spacing?

Hope it is okay to use an issue for such a question, I didn't find any place to ask such Mint specific questions to other devs.

**Comment by rcalixte** [comment]
@dede53 Have you thought about adding this functionality to [this internal applet](https://github.com/linuxmint/cinnamon/tree/master/files/usr/share/cinnamon/applets/inhibit%40cinnamon.org) instead? It already has the inhibition features implemented and maybe just one extra row for each duration item to implement the duration aspect/feedback? (You could also append any duration information at the top similar to the "Apps inhibiting power management:" section.) This interface may actually be easier to modify as well.

**Comment by dede53** [comment]
Thanks for your reply. I thought about that possibility, but I came to the conclusion that it is more convenient to manage notifications right there where they appear. Like with the wifi: I can de/activate it where I see the available networks.
In the same way I would expect to have the switch for power management in power@cinnamon.org

For me it is a question of UX. In a way it's the same like in https://github.com/linuxmint/cinnamon/issues/11383.
Should settings be grouped by topic or how it makes sense to implement it? Imho they should be grouped by topic where it is easy possible. I see that for the applets it is not easy to solve that, but for the notifications or the power management I don't see any problems.

**Comment by rcalixte** [comment]
> I came to the conclusion that it is more convenient to manage notifications right there where they appear.

The challenge I see with this is that it is not constant. The notification applet is not present when there are no notifications. If you want to tweak that setting, you would need to wait for/generate a new notification first.


> For me it is a question of UX. In a way it's the same like in #11383.

I partially understand that issue but also partially do not. There are two different settings for two different things. One for the applet, one for the system.

**Comment by dede53** [comment]
> The challenge I see with this is that it is not constant. 

I would change that setting that the applet is constant present. IMHO a notification system is important enough to get a constant icon. But I expect that there is a group of people taking care of such decisions.

> There are two different settings for two different things. One for the applet, one for the system.

As a normal user I don't want to have to think of which part of the system could be responsible for a setting i want to change.

But anyways, it seems to me, that I'm the only person with this issue and that improvements are hard to add to existing applets, I will close this issue and maybe publish my own notification applet. Even I think that more redundant applets are not really improving the quality of the whole system.
