### ISSUE TITLE
Completely unable to screenshot pop-up menus

### ISSUE THREAD

**Issue by Splarkszter** [linuxmint/cinnamon#11444]
* Cinnamon version - 5.6.7
 * Distribution - Mint 21
 * GPU Radeon R7 (Kavery)
 * 64 bit

### Issue
When i try to screenshot anything on my screen, any (or most) pop-up menu or tool-tip closes before taking the screenshot.

### Steps to reproduce
One that behaves like that is the firefox download thingy:
![image](https://user-images.githubusercontent.com/90066319/213607083-f0debf8b-9fa2-4689-80f8-ab083c40e6ee.png)

And the thing that pops up to select the status on discord:
![image](https://user-images.githubusercontent.com/90066319/213607514-8ba3cf60-fb9f-4932-bb01-330396265fd8.png)

### Expected behaviour
Being able to screenshot pop-up menus and tool-tips.

### Aditional Info

Even using third party software like flameshot or using an .exe app the behaviour is the same.

Shortcut used is the system default.

**Comment by rcalixte** [comment]
@Splarkszter If you use the "Open Launcher" option in Flameshot, there is an option to add a delay. This will allow you to capture pop-up menus and tool-tips. Any software for screenshots that supports a delay should work for capturing these objects.

**Comment by Splarkszter** [comment]
> There is an option to add a delay.

Yes, but this is not a proper solution.

**Comment by rcalixte** [comment]
> > There is an option to add a delay.
> 
> Yes, but this is not a proper solution.

It's the reason that feature exists. 😉 

What part of it makes it improper for you? I also have Shutter installed and it has dedicated menu and tool-tip options but I have previously found them inconsistent. Do you want to give that a try and see if it meets your needs?

**Comment by mtwebster** [comment]
There is no 'proper solution' - this is a limitation of x11, that two things cannot have key focus at the same time.

When a popup menu is visible in an application, that menu has an exclusive grab on the keyboard. As a result, shortcut keys are temporarily unavailable. There is no way around this, other than to use a delay.

There's really no issue with tooltips, though some programs may hide them upon receiving a keystroke, which gives the impression of not being able to screenshot them.

**Comment by DirkHaar** [comment]
May I add that instead of taking a screenshot it's possible to use the screen recorder (alt-shift-ctrl-r) to start a video recording (notice the red dot appearing in the panel), use the context menu, menu or what else, press the key combo again to stop. The video is stored as cinnamon-(timestamp).webp in your ~\video folder. See example video in issue #11442.
Playback that video, halt, take your screenshot.
