### ISSUE TITLE
Bluetooth `Connection Failed: br-connection-unknown`

### ISSUE THREAD

**Issue by ovari** [linuxmint/cinnamon#11456]
```
 * Cinnamon 5.6.7
 * Linux Mint 21.1
```

### Issue
Unable to pair Linux Mint computer and Nokia phone.

### Steps to reproduce
1. Turn on Bluetooth
2. Pair Nokia phone with Linux Mint and `Connection Failed: br-connection-unknown`
![Connection Failed br-connection-unknown](https://user-images.githubusercontent.com/17465872/215240979-9b88c586-8bbd-414f-be9d-fa978f104b02.png)
4. Bluetooth seems to connect and then disconnect seconds later
![image](https://user-images.githubusercontent.com/17465872/215241170-b463de04-c6bc-4ad0-b14c-08526216303a.png)

### Expected behaviour
Able to pair Linux Mint and Nokia devices to test [Bug 128854 - LibreOffice Impress Remote for Android 2.4.0 and LibreOffice 6.3.3.2 for Linux](https://bugs.documentfoundation.org/show_bug.cgi?id=128854).

Thank you

**Comment by anaximeno** [comment]
Hi, can you see if here [blueman-project/blueman](https://github.com/blueman-project/blueman) is more suitable for this bug?

**Comment by ovari** [comment]
https://github.com/blueman-project/blueman/issues/2026

**Comment by IvanDoganov** [comment]
Restarting Pulseaudio worked for me. Try this:
`pulseaudio --kill
pulseaudio -vvv --start`

**Comment by goebbe** [comment]
I don't know what the policy with respect to upstream bugs, but I think this bug should be reopened. 
Since LinuxMint integrates blueman this is also an issue in Linux Mint.

**Comment by goebbe** [comment]
For my two Bluetooth headsets, using bluetuith was a workaround to establish a stable connection on LM 21.2 CE. 
https://forums.linuxmint.com/viewtopic.php?t=409588
