### ISSUE TITLE
Add a horizontal line to separate the icon groups

### ISSUE THREAD

**Issue by ineuw** [linuxmint/cinnamon#11469]
### Describe the solution you'd like

There are so many beautiful icon and matching options and a simple horizontal bar would help where one group ends and the next begins. 

![230131_separating_theme_icons](https://user-images.githubusercontent.com/10367016/216157249-18df0541-4766-4521-a78c-99d56d18694d.jpg)

**Comment by JosephMcc** [comment]
This doesn't work. Your screenshot even shows this. The icons are laid out in a grid within the menu and you can see even in your image that adding a separator doesn't really divide the groups properly. You can have more then one "group" on a single row.

**Comment by ineuw** [comment]
Come on, There is such a thing as an empty space in a grid. Anyways, it was a suggestion to help new users to identify the profusion of icons.

**Comment by JosephMcc** [comment]
> Come on, There is such a thing as an empty space in a grid

Well you'd be welcome to try and implement it that way. How would you handle the single icon names shown in your image like ePapirus, Adwaita, breeze, High contrast, etc? Put each on it's own row with a separator and make the menu a mile long? You proposed a solution here but it isn't very well thought out and not very workable. The idea is fine but in the context of GtkMenu I don't think is all that workable.

**Comment by JosephMcc** [comment]
To add a bit, one issue we already have hear is users complain about having to scroll the menu which isn't super friendly with GtkMenu. Adding the need to scroll even more only makes that worse. I think to really fix the issue probably a completely different design needs to be implemented. Maybe something like GtkPopover that allows a lot more flexible content and can use normal scrollbars?

**Comment by ineuw** [comment]
There are 15 variations in each group. 5x3 or 3x5? I know nothing about GTK, but I am also having numerous display problems in applications using it. Issues relating visual presentation are very important to me.

**Comment by ineuw** [comment]
My suggestions are intended for the record. I don't expect anything, but observational experience suggests that accepted ideas are incorporated months down the line.
