### ISSUE TITLE
Notifications applet "clear all notifications" box disappears

### ISSUE THREAD

**Issue by wolkzel** [linuxmint/cinnamon#11483]
### Issue
After you disable "show notification numbers" in the Notifications Applet settings, "clear all notifications" box disappears.

### Steps to reproduce

1. Open up Notifications Applet settings.
2. Disable "show notification numbers" setting.

### Expected behaviour

Being able to clear all notifications with one click after you disable the setting I mentioned.

https://user-images.githubusercontent.com/46371662/216682978-2741d205-aeb7-4270-9386-c0c0d61db040.mp4

**Comment by claudiux** [comment]
Bug reproduced. Cinnamon 5.6.7.

**Comment by claudiux** [comment]
To solve this issue, edit as root the `/usr/share/cinnamon/applets/notifications@cinnamon.org/applet.js` script and comment the line 204; from:
`this.clear_action.actor.hide();`
to:
`// this.clear_action.actor.hide();`
Then, restart Cinnamon.

**Comment by wolkzel** [comment]
> To solve this issue, edit as root the `/usr/share/cinnamon/applets/notifications@cinnamon.org/applet.js` script and comment the line 204; from: `this.clear_action.actor.hide();` to: `// this.clear_action.actor.hide();` Then, restart Cinnamon.

This change solved the issue, thank you.
