### ISSUE TITLE
Libadwaita apps don't follow system theming

### ISSUE THREAD

**Issue by wolkzel** [linuxmint/cinnamon#11482]
I'm currently using LM 21.1, even though I enabled dark theme, Libadwaita apps didn't follow it. In order to enable dark theme on these apps, I had to enter this command "gsettings set org.gnome.desktop.interface color-scheme prefer-dark".

What I expect:

Libadwaita apps to follow the light/dark theming in the current system.

https://user-images.githubusercontent.com/46371662/216679034-49e9bf07-cf78-47ff-b420-7cd7b85c5f4a.mp4

**Comment by clefebvre** [comment]
If an app uses libAdwaita, that app is only designed to work in GNOME and only with Adwaita. Don't expect it to integrate in other themes and/or desktop environments.
