### ISSUE TITLE
Crash (?) after closing laptop with external display and reopening with external display

### ISSUE THREAD

**Issue by slinkp** [linuxmint/Cinnamon#1148]
Steps to reproduce:

1) Start with a laptop with external display attached via VGA cable. Not mirroring screens.
2) Close the laptop lid. External display goes blank.
3) Touch the keyboard. Login dialog appears on external display.
4) After login, only the external display is active - i.e. the menu appears at top of external display, the Display Settings app shows the laptop display as disabled, etc.

So far so good; I'm not sure what exactly is intended behavior here but I'm happy with it.

5) Without opening the laptop, unplug the external display.
6) Open the laptop.

Expected/hoped-for behavior: Cinnamon should be up and running, and all windows should have been pulled from the external display to the laptop display.
Actual behavior: Cinnamon appears to have crashed. My windows are still there, but without decorations - no title bars, no min/max/close buttons, etc.

There is a fair amount of stuff in ~/.xsession-errors that I think supports this conclusion. Maybe useful for diagnosis? I'm pasting them:

After step 1 (laptop open, external display attached): http://pastebin.com/UQXRA8nB

After step 4 (laptop closed, logged in):  http://pastebin.com/4X3JVmrt

After step 6 (external removed, laptop opened): http://pastebin.com/LNCD4tmZ

(I edited them to remove the overlapping stuff at beginning)

**Comment by JosephMcc** [comment]
Closed due to lack of response.

**Comment by slinkp** [comment]
Yeah sorry I haven't used cinnamon in years.

**Comment by JosephMcc** [comment]
No problem. Just cleaning up old issues.
