### ISSUE TITLE
Button borders do not appear  in the screenshot save dialog

### ISSUE THREAD

**Issue by xerxeslins** [linuxmint/cinnamon#11498]
```
 * Cinnamon version 5.6.7 (cinnamon --version)
   I am not using daily builds PPA
 * Distribution - Linux Mint 21.1 Cinnamon
 * Graphics hardware *and* driver used
 Intel Corporation CometLake-S GT2 [UHD Graphics 630]
 * 64 bit
 * does not produce ~/.xsession-errors, or /var/log/syslog
 ```

### Issue

Button borders do not appear when using one of the Mint-Y theme variants (dark or not) in the screenshot save dialog.

### Steps to reproduce

Shift + Print
Select area to print
The save image window appears, but the buttons (Cancel and Copy to clipboard) have no borders.

![no_borders](https://user-images.githubusercontent.com/7513301/217896713-1c75f6f1-4931-492e-983a-cdc790f6acf0.png)

### Expected behaviour

Buttons should have borders like in the Adwaita theme.

![with_borders](https://user-images.githubusercontent.com/7513301/217896690-e7ee8c38-ee20-4dc6-bb26-96061b60933d.png)

**Comment by JosephMcc** [comment]
This doesn't have anything to do with Cinnamon but with `mint-themes`. That being said, that is the design and style of Mint-y and always has been. It was meant to be a flat theme for fans of that since the beginning.
