### ISSUE TITLE
Problems with JAVA compiler on Linux Mint 21.1 Visual studio code

### ISSUE THREAD

**Issue by Martis23** [linuxmint/cinnamon#11490]
Problems with JAVA compiler on Linux Mint 21.1 Visual studio code

![Screenshot at 2023-02-06 17-52-50](https://user-images.githubusercontent.com/64471136/217022118-01be43ed-6d3d-426e-b9d9-14907374f2ce.png)

**Comment by mtwebster** [comment]
I'm not sure but it looks like maybe you need to install a JDK. This isn't really a Cinnamon/Mint issue.

**Comment by Martis23** [comment]
I tried to install and reinstall JDK, nothing helps. Maybe someone has a solution?
