### ISSUE TITLE
cinnamon-control-center doesn't work | undefined symbol: cairo_tee_surface_index

### ISSUE THREAD

**Issue by qundus** [linuxmint/cinnamon#11494]
```
 * Cinnamon 5.6.7
   - PPA: No
 * Arch
 * NVIDIA GeForce RTX 3050 Mobile with Nvidia proprietary driver
 * 64 bit
 * Attach ~/.xsession-errors, or /var/log/syslog
   - There's none
 ```

### Issue
After the last update two days ago on 6-02-2023 i just can't initialize cinnamon control center (settings) and some other applets as well, when I try to launch them through terminal i get the following error:
```bash
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 29, in <module>
    from bin import SettingsWidgets
  File "/usr/share/cinnamon/cinnamon-settings/bin/SettingsWidgets.py", line 12, in <module>
    from ChooserButtonWidgets import DateChooserButton, TimeChooserButton
  File "/usr/share/cinnamon/cinnamon-settings/bin/ChooserButtonWidgets.py", line 4, in <module>
    import cairo
  File "/usr/lib/python3.10/site-packages/cairo/__init__.py", line 1, in <module>
    from ._cairo import *  # noqa: F401,F403
ImportError: /usr/lib/python3.10/site-packages/cairo/_cairo.cpython-310-x86_64-linux-gnu.so: undefined symbol: cairo_tee_surface_index
```
all errors lead to `undefined symbol: cairo_tee_surface_index` and i can't figure this out.

### Steps to reproduce
- install archlinux with cinnamon DE and cinnamon-control-center
- open a terminal and launch cinnamon-settings
- you should see the error

### Expected behaviour
cinnamon control center GUI should work and appear on screen

**Comment by leigh123linux** [comment]
Report the issue to the /usr/lib/python3.10/site-packages/cairo/_cairo.cpython-310-x86_64-linux-gnu.so provider.
