### ISSUE TITLE
Directory Menu like XFCE

### ISSUE THREAD

**Issue by andysavage** [linuxmint/cinnamon#11518]
It can be extremely useful and time-saving to be able to drill down through a folder structure to a file you want.

XFCE has a panel plug-in called [Directory Menu](https://docs.xfce.org/xfce/xfce4-panel/directorymenu). 

I can find nothing similar for Cinnamon, despite extensive searching.

Would it be possible to make such a plug-in available for the Cinnamon Panel.

This is what it looks like in use:

[http://imgbox.com/ZsVJoEvE](http://imgbox.com/ZsVJoEvE)

**Comment by danimesq** [comment]
You gave me a viewpoint at file exploring productivity that I personally never thought about before.

I don't know where it is and even if Cinnamon have one: a page/repository to suggest new spices.
What you suggest would fit exactly an applet for Cinnamon's panels (please note there's no single one Panel).

Your issue could be moved to this repo: https://github.com/linuxmint/cinnamon-spices-applets

Taking into consideration the existing official applets, the possibility is low that the Linux Mint's small team for Cinnamon would be interested in developing an applet for this so particular purpose; you should try to find an independent applet developer to make your idea a reality.

**Comment by Secret-chest** [comment]
Cinnamenu can do this.

**Comment by andysavage** [comment]
> Cinnamenu can do this.
Thanks for replying. Could you tell me (or point me to) how to set it up to do this? I tried it and as far as I can see it's similar (almost the same) as the mint menu in the bottom left. I can't find any way to make it simply do a directory tree for a chosen directory that you can drill down into and get any file you like. I can't find any instructions online for this either, so I would be grateful.



> You gave me a viewpoint at file exploring productivity that I personally never thought about before.



> 

Thanks for replying,
Yes I came across this years ago when I was still using Mac OS. It was possible even in the classic mac os. You had to fight the defaults, and more so as time went by but it was possible and I found it the most efficient way to get to anything. It only is useful if you have a logical system and can figure where you would have put anything (or have a phenomenal memory!), but if you do, it's way more efficient than digging down clicking on folders, any file is always just 2 clicks away.

I am not very familiar with github or the other dev sites yet. How would I go about finding devs interested in doing htis? I'll check out the cinnamon spices repo you linked to.

**Comment by rcalixte** [comment]
Directory Menu is now available [here](https://cinnamon-spices.linuxmint.com/applets/view/388) and in your local Applets module in Cinnamon. Thanks to @torchipeppo for making it happen!

**Comment by andysavage** [comment]
Thanks that's great I hope lots of people enjoy it
