### ISSUE TITLE
Hot Corner Enhancement

### ISSUE THREAD

**Issue by mdchaves** [linuxmint/Cinnamon#1153]
Although currently we can enable any of the four desktop hot corners, we can not enable all four simultaneously. We have to choose one hot corner position at a time. Moreover, we can use hot corners to trigger only two actions: "expo view" or "scale view".

FEATURE REQUEST (inspired by Elementary OS):

We should have the ability to enable the four desktop hot corners concomitantly. Each hot corner should be able to trigger a selected function such as: 

Show expo view
Show scale view
Minimize current window
Maximize current window
Open Main Menu
Show Desktop
Lock Screen
Edge Flip
Execute custom command
Do nothing
other...

Screenshot from Elementary OS hot corners settings:

<a href="http://s580.photobucket.com/albums/ss244/marcio107/?action=view&amp;current=hot-corners_zps27114ef3.png" target="_blank"><img src="http://i580.photobucket.com/albums/ss244/marcio107/hot-corners_zps27114ef3.png" border="0" alt="Photobucket"></a>

**Comment by charsi** [comment]
@mdchaves I have created a new feature request for hot edges
