### ISSUE TITLE
Highlight for for currently selected application is too low contrast to see

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [linuxmint/cinnamon#11536]
```
* cinnamon --version
Cinnamon 5.4.12
 * 64 bit
 ```

### Issue

Look at my task bar and tell me which application has focus?
![image](https://user-images.githubusercontent.com/11778530/222526361-d536ad01-79cc-4893-b90e-d52550774bdf.png)

The highlight for the application with focus is too low contrast to see.  Turning on "High contrast mode" in the settings didn't help.

Same issue when I press ALT+TAB.  The highlight around the selected application icon is too subtle to see.
[Screencast from 2023-03-02 11-10-28.webm](https://user-images.githubusercontent.com/11778530/222528273-7270152a-3681-4429-9ebe-f70eb6ab08bb.webm)

### Steps to reproduce

Run 2 or more applications.

### Expected behaviour

A higher contrast highlight color.

**Comment by Secret-chest** [comment]
Try a different desktop theme.

**Comment by JosephMcc** [comment]
As pointed out above this really has nothing to do with Cinnamon itself. It would need to be changed in whatever theme you are using.
