### ISSUE TITLE
(Optional) panel slide in animation

### ISSUE THREAD

**Issue by Secret-chest** [linuxmint/cinnamon#11538]
### Is your feature request related to a problem? Please describe.

No, just looks better.

### Describe the solution you'd like

Have the panels slide in from the edge when the session starts.

### Describe alternatives you've considered

Not having it

**Comment by JosephMcc** [comment]
I'm pretty sure it used to be this way a long time ago. If I remember correctly it was the cause of another issue so was changed to the current behavior. I doubt you'll see it coming back.

**Comment by Secret-chest** [comment]
Just to ask, can this be made as an extension? (as to make it myself)
