### ISSUE TITLE
Request - Add Realtek RTL8852BE driver to kernel

### ISSUE THREAD

**Issue by landrover74656** [linuxmint/cinnamon#11545]
### Is your feature request related to a problem? Please describe.

Yes.  The current kernel does not have drivers for a popular WIFI card (Realtek RTL8852BE).  The RTW89 driver that exists on GIT hub (link below) works flawlessly in Mint 21 between kernel updates.  However every time I get a kernel update I loose the WIFI driver.  This forces me to have to connect my machine to a docking station (to use an RJ45 connection) to re-download and manually install the driver from the GIT hub repository in the terminal.  

https://github.com/HRex39/rtl8852be.git

Thanks in advance for your consideration. 

### Describe the solution you'd like

Please add the driver to kernel so myself and other users don't have to continue to manually reinstall the driver, or lock our system to an outdated kernel.  

### Describe alternatives you've considered

Locking the machine to an older kernel and forgoing security updates, or continually revert back to a kernel with the manually installed driver.  Both options compromise security.  

### Additional context

devon@devon-HP-Pavilion-Laptop-15-eh2xxx:~$ lspci
00:00.0 Host bridge: Advanced Micro Devices, Inc. [AMD] Renoir/Cezanne Root Complex
00:00.2 IOMMU: Advanced Micro Devices, Inc. [AMD] Renoir/Cezanne IOMMU
00:01.0 Host bridge: Advanced Micro Devices, Inc. [AMD] Renoir PCIe Dummy Host Bridge
00:02.0 Host bridge: Advanced Micro Devices, Inc. [AMD] Renoir PCIe Dummy Host Bridge
00:02.2 PCI bridge: Advanced Micro Devices, Inc. [AMD] Renoir/Cezanne PCIe GPP Bridge
00:02.4 PCI bridge: Advanced Micro Devices, Inc. [AMD] Renoir/Cezanne PCIe GPP Bridge
00:08.0 Host bridge: Advanced Micro Devices, Inc. [AMD] Renoir PCIe Dummy Host Bridge
00:08.1 PCI bridge: Advanced Micro Devices, Inc. [AMD] Renoir Internal PCIe GPP Bridge to Bus
00:14.0 SMBus: Advanced Micro Devices, Inc. [AMD] FCH SMBus Controller (rev 51)
00:14.3 ISA bridge: Advanced Micro Devices, Inc. [AMD] FCH LPC Bridge (rev 51)
00:18.0 Host bridge: Advanced Micro Devices, Inc. [AMD] Cezanne Data Fabric; Function 0
00:18.1 Host bridge: Advanced Micro Devices, Inc. [AMD] Cezanne Data Fabric; Function 1
00:18.2 Host bridge: Advanced Micro Devices, Inc. [AMD] Cezanne Data Fabric; Function 2
00:18.3 Host bridge: Advanced Micro Devices, Inc. [AMD] Cezanne Data Fabric; Function 3
00:18.4 Host bridge: Advanced Micro Devices, Inc. [AMD] Cezanne Data Fabric; Function 4
00:18.5 Host bridge: Advanced Micro Devices, Inc. [AMD] Cezanne Data Fabric; Function 5
00:18.6 Host bridge: Advanced Micro Devices, Inc. [AMD] Cezanne Data Fabric; Function 6
00:18.7 Host bridge: Advanced Micro Devices, Inc. [AMD] Cezanne Data Fabric; Function 7
01:00.0 Network controller: Realtek Semiconductor Co., Ltd. Device b852
02:00.0 Non-Volatile memory controller: Samsung Electronics Co Ltd NVMe SSD Controller 980
03:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Barcelo (rev c1)
03:00.1 Audio device: Advanced Micro Devices, Inc. [AMD/ATI] Renoir Radeon High Definition Audio Controller
03:00.2 Encryption controller: Advanced Micro Devices, Inc. [AMD] Family 17h (Models 10h-1fh) Platform Security Processor
03:00.3 USB controller: Advanced Micro Devices, Inc. [AMD] Renoir/Cezanne USB 3.1
03:00.4 USB controller: Advanced Micro Devices, Inc. [AMD] Renoir/Cezanne USB 3.1
03:00.5 Multimedia controller: Advanced Micro Devices, Inc. [AMD] Raven/Raven2/FireFlight/Renoir Audio Processor (rev 01)
03:00.6 Audio device: Advanced Micro Devices, Inc. [AMD] Family 17h (Models 10h-1fh) HD Audio Controller

devon@devon-HP-Pavilion-Laptop-15-eh2xxx:~$ uname -r
5.15.0-67-generic

devon@devon-HP-Pavilion-Laptop-15-eh2xxx:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Linuxmint
Description:	Linux Mint 21.1
Release:	21.1
Codename:	vera

**Comment by mfreeman72** [comment]
Mint doesn't supply the kernel. That comes from Ubuntu or Debian (in the case of LMDE). I would recommend bringing the problem to their attention. Another possible thing to try would be to use dkms to automatically add it to any newly installed kernels.
