### ISSUE TITLE
Internal MicroSD card reader not recognized.

### ISSUE THREAD

**Issue by OxyMauron** [linuxmint/cinnamon#11543]
```
 * Cinnamon 5.6.7
 * Mint 21.1
 * Graphics hardware *and* driver used
 * 64 bit
 * kernel 5.15.0-67-generic
 ```

### Issue

The MicroSD card reader is not being recognized in my Lenovo Ideapad 100S-14IBR. 

### Steps to reproduce

- Load Mint 21.1 Cinnamon on a Lenovo Ideapad 100S-14IBR.
- MicroSD card in slot is not detected.

### Expected behaviour

- MicroSD card is detected and mountable.

### Other information

I found a similar bug report for the same laptop model running [Ubuntu](https://bugs.launchpad.net/ubuntu/+source/linux-hwe/+bug/1710023). Testing with Mint 18 Cinnamon running a pre-4.10 kernel automatically mounted the MicroSD card without issue.

**Comment by leigh123linux** [comment]
You need to file the issue against the ubuntu kernel.
