### ISSUE TITLE
Alphabetic order of the English names for the three Windows applets 

### ISSUE THREAD

**Issue by ineuw** [linuxmint/cinnamon#11559]
Working with French and English versions, I noticed the differences and suggest the following changes for the windows applet names. Voltaire, Shakespeare, Molière, and Rousseau all agree.

Windows list
Windows grouped list
Windows quick list

![window applet names in english](https://user-images.githubusercontent.com/10367016/225257352-fb5507de-a110-4ed1-bb7a-b6ffb283cf06.jpg)

**Comment by Secret-chest** [comment]
Maybe rename the GWL to Window List / Switcher and Window List to Legacy Window List, since GWL can do ungrouped with labels just fine.

**Comment by ineuw** [comment]
The idea followed the French installation where all three were together by description and all I care about, is to make it easier for an inexperienced user.
