### ISSUE TITLE
Problemas para acesso de rede com Linux Mint 21.1

### ISSUE THREAD

**Issue by sadbloom** [linuxmint/cinnamon#11567]
Estou em processo de migração do Windows 10 para o Linux Mint 21.1 e, apesar de ter pouco conhecimento sobre o Linux, estou enfrentando um problema com a rede do meu notebook. Infelizmente, o meu notebook não tem entrada para rede cabeada e o sistema não está reconhecendo a rede via Wi-Fi. Já tentei diversas soluções, como pressionar a tecla F2 para ativar e desativar o acesso, mas, na verdade, ele habilita e desabilita o Bluetooth. Além disso, tentei instalar o Ubuntu em dual boot, mesmo preferindo o Linux Mint, e infelizmente tive o mesmo problema. Isso me leva a acreditar que o problema está relacionado ao driver de rede sem fio, mas infelizmente não consigo usar uma conexão cabeada para corrigi-lo.

Gostaria de pedir ajuda para solucionar este dilema. Alguma sugestão seria muito bem-vinda.

**Comment by leigh123linux** [comment]
This isn't a cinnamon issue, try asking on the forum instead.

https://forums.linuxmint.com/
