### ISSUE TITLE
Support for ARM Processors

### ISSUE THREAD

**Issue by bco2135** [linuxmint/cinnamon#11563]
Not really sure if this is possible, but would it be possible to run Linux Mint on a computer using an ARM processor? If it isn't possible, it would be nice to have an Ubuntu based edition of Linux Mint that supports ARM processors.

**Comment by ItzSwirlz** [comment]
> Not really sure if this is possible, but would it be possible to run Linux Mint on a computer using an ARM processor? If it isn't possible, it would be nice to have an Ubuntu based edition of Linux Mint that supports ARM processors.

It is already available. I'm not sure about Mint, but for Cinnamon you can definitely do it. I have Cinnamon DE running on my raspberry pi, which is Ubuntu based. The packages for cinnamon are set to build for arm64; and it also works on Asahi Linux if you are willing to try to dig through your Mac to use it. (No GPU acceleration but still good)

**Comment by BokBoy** [comment]
@ItzSwirlz, how to do it??
I've recently had the attention to try running a KVM of Windows 11 on my Mac. My friend suggested this because linux is more lightweight. I trust mint a lot since many of my friends (suggested one too) use it.
Do you have a  way to compile an iso to download and burn onto a USB??

**Comment by ItzSwirlz** [comment]
> @ItzSwirlz, how to do it?? I've recently had the attention to try running a KVM of Windows 11 on my Mac. My friend suggested this because linux is more lightweight. I trust mint a lot since many of my friends (suggested one too) use it. Do you have a way to compile an iso to download and burn onto a USB??

you can build it from source, or distros with arm repositories will have it.
