### ISSUE TITLE
Task manager applet and enhancement 

### ISSUE THREAD

**Issue by LinuxBoy-96** [linuxmint/cinnamon#11569]
So, the title and the picture are quite explicit. I think it would be a good idea to add an applet that displays basic performance stats for those who want it. Of course, that applet would act as a shortcut to the task manager when clicked on.

Why? Because you shouldn't have to open the task manager, which will take up a lot more resources by itself, to see if there may be an abnormal situation like bad optimization, memory leaks, etc. This would give you a constant understanding of your resource usage without the need to open the task manager. Sometimes, it can just give you an explanation of why your PC is suddenly slow.

As for the task manager itself, I think it should be modernized. To be honest, I think the design comes from the late 2000s and should look more like what the modern Windows Task Manager looks like, such as SysMonTask on Linux. My biggest problem is that it doesn't show all the information we have in Windows, especially RAM speed.

I'll give you my reasons, besides the fact that it's practical to remember or know what is in your PC. I remember when I built a PC for my dad, I had chosen the right RAM profile in the UEFI, but when I pressed the wrong option to exit and didn't save the change, the memory was set to the wrong and slower speed. It was on Windows, so I saw it on the task manager.

If I had used Linux that day, I would not have had any way to see that I messed up.
![cinnamon](https://user-images.githubusercontent.com/128245725/226120802-26858519-f59e-4866-9e0a-7aed0959b184.png)

**Comment by Secret-chest** [comment]
Those kinds of applets are available for download.

**Comment by LinuxBoy-96** [comment]
> Those kinds of applets are available for download.

I've never seen something like that, plz tell me more.

Plus - It does not change the fact that the task manager itself is lacking.
(All DE are lacking on that aspect tbh)

**Comment by Secret-chest** [comment]
> Plus - It does not change the fact that the task manager itself is lacking.

That's debatable.

**Comment by LinuxBoy-96** [comment]
So what I've discovered is that the System Monitor was probably not developed by the Cinnamon team, but I can't figure out who developed it.

**Comment by Secret-chest** [comment]
> So what I've discovered is that the System Monitor was probably not developed by the Cinnamon team, but I can't figure out who developed it.
> 

GNOME

**Comment by JosephMcc** [comment]
Closing this. As pointed out, there are applets available for this already and the task manager isn't a part of Cinnamon nor is it developed by the Mint team.
