### ISSUE TITLE
download-and-upload-speed@cardsurf: Glitches on resize

### ISSUE THREAD

**Issue by andrewille** [linuxmint/Cinnamon#11578]
```
 * Cinnamon version (cinnamon --version)
   Cinnamon 5.6.8
 * Distribution - (Mint 21, Arch, Fedora 37, etc...)
   Mint 21.1
 * Graphics hardware *and* driver used
 * 32 or 64 bit
   amd64
 * Attach ~/.xsession-errors, or /var/log/syslog
 ```
[.xsession-errors](https://gist.github.com/andrewille/27ae18c0a55bcb5c26c7338345bb2c6c)

### Issue
Hello,
since Mint 21 I have an issue with the download-and-upload-speed@cardsurf Cinnamon applet. This applet shows the current download and upload speed of selected network interfaces in your system tray as text. The icon in the system tray (resp. the text next to the icon) resizes frequently. Consider your network is in idle, so your download is (usually) 0B. Then you start a download and you got 10.5MB. Whenever the size of the text changes, it gets buggy. Sometimes, when the text should get more space, you don't see all of the text and if the text should shrink, you still see parts of the old text (like if its burnt it).
If I hover over the text, it will update and have the correct size.
I have recorded the incorrect behaviour. See https://youtu.be/bTDlHiTtebI

This might be an issue that is caused by the Applet, but I believe it is a Cinnamon issue. Redrawing after resizing should be done by Cinnamon.

### Steps to reproduce
1. Install the download-and-upload-speed@cardsurf Cinnamon applet
2. Add it to your system tray and select your network interface(s)
3. Watch what happens if you start downloading, especially if the speed changes frequently.

### Expected behaviour
It should reserve the correct space on updates and not crop anything or show old text

### Other information
My taskbar has a user-defined size of 36px if that matters.

### Configuration info, if applicable
If this bug report is related to an Applet, Desklet or Extension, please paste (or use a pastebin service) the offending extension's settings, if it has any.  You can obtain this by opening its configuration, clicking the 'hamburger' button in the upper-right corner of the window, and selecting "Export to a file". **Please be sure to review the contents and remove any personal data it may contain.**
https://gist.github.com/andrewille/27ae18c0a55bcb5c26c7338345bb2c6c

**Comment by anaximeno** [comment]
I also had the same problem.
