### ISSUE TITLE
Mirror Panels for Multiple Displays

### ISSUE THREAD

**Issue by linuxrichard** [linuxmint/cinnamon#11577]
Currently Cinnamon does not allow the panel/taskbar to duplicate across multiple displays. As more and more of us are working form home, more and more of us are able to use Linux for work and having multiple screens is now the norm. It is weird that this functionality does not exist in Cinnamon. It exists in Gnome, KDE Plasma and even Windows 10. This feature request was previously considered but close (see https://github.com/linuxmint/Cinnamon/issues/5352). No explanation was given for why it was closed but not implemented. Please could this issue be reconsidered.

**Comment by JosephMcc** [comment]
There is no reason to open another issue for this. You can add your comments to the other one you linked.

**Comment by jimav** [comment]
> Things like the system tray simply cannot have multiple instances because of how they function

I don't think multiple instances are being asked for.    

The request is to **display the exact same panel in multiple places.   No separate state.  Not individually configurable.**

It (the single instance) would need to map multiple images and listen for clicks from any of them, and make it so that popups appear on the same monitor that the click came from. 

I think this should be re-opened because it was closed based on a mis-conception.

**Comment by Ezelmannen** [comment]
"JosephMcc closed this as completed on Apr 2, 2023" really feels like a lie. 
Is there no way to "closed this as currently_not_under_development_or_in_the_roadmap_and_maybe_in_15_years_but_we_really_dont_want_this_clogging_up_our_github_at_the_moment" instead?

**Comment by billyswong** [comment]
@Ezelmannen It is fortunate we now get the "discussion" page to post feature request, and so far they haven't implemented that stupid "When you submit an idea, it is processed and then closed" in there this time. I come to this thread by link hopping from https://github.com/orgs/linuxmint/discussions/1106

**Comment by JosephMcc** [comment]
> so far they haven't implemented that stupid "When you submit an idea, it is processed and then closed" in there this time

That was simply an attempt to make the issues more manageable. The fact is, 99% of these requests will never be implemented.

> "JosephMcc closed this as completed on Apr 2, 2023" really feels like a lie.

There was a time when that was the only option. That was what github said for everything that was closed.
