### ISSUE TITLE
Arduino IDE not yielding any USB ports

### ISSUE THREAD

**Issue by s0170071** [linuxmint/cinnamon#11571]
I am just leaving this note for anyone running into trouble with the Arduino IDE under Linux Mint 20 and 21.1
If you do not find any USB ports in the Arduino IDE, it is because brltty (braille devices) accidentally hijacks all USB ports. 
They fixed the issue, but the package has still not been updated in LM21.1

For non blind people the fix is simply 
`
sudo apt-get remove brltty
`

That's it. 
See https://github.com/linuxmint/cinnamon/issues/11369

**Comment by leigh123linux** [comment]
File the issue at https://github.com/linuxmint/linuxmint/issues
