### ISSUE TITLE
Switcheroo Control Does Not Work Properly with Nvidia Drivers

### ISSUE THREAD

**Issue by BlindRepublic** [linuxmint/cinnamon#11580]
### Issue
Launching applications that have `PrefersNonDefaultGPU=true` in their `.desktop` file does not result in the application running on the Nvidia card.

### Steps to reproduce
1. Install Steam
2. Run Steam from menu (without changing environment variables)
3. Select a game to play
4. Note that game is using the integrated GPU (verify with `nvidia-smi`)

### Expected behaviour
The game should be using the Nvidia graphics card and the binary should be visible under `nvidia-smi`.

### Other information
 * Cinnamon version - Cinnamon 5.6.7
 * Distribution - Fedora 37
 * Graphics hardware *and* driver used - RTX 3050 with Nvidia proprietary driver 
 * Arch - 64 bit

**Comment by leigh123linux** [comment]
Does this work?

```
__NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia  steam
```

Maybe steam needs this to run


```
__NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia __VK_LAYER_NV_optimus=non_NVIDIA_only steam
```

**Comment by BlindRepublic** [comment]
Yes, and even manually running Steam via `switcherooctl launch /usr/bin/flatpak run --branch=stable --arch=x86_64 --command=/app/bin/steam-wrapper com.valvesoftware.Steam` works properly.

**Comment by mtwebster** [comment]
https://github.com/linuxmint/cinnamon/commit/00b0a65bd47d805b7bdbfcc4723f3d43ac1ea116

**Comment by InfinityBladeX10STD** [comment]
How to do this in fortnite in windows in laptop
