### ISSUE TITLE
Adds colored applications-multimedia icon in Adwaita.

### ISSUE THREAD

**Issue by Initu-Castilhos** [linuxmint/cinnamon#11588]
The applications-mutimedia icon in Adwaita is symbolic since Linux Mint 19, I know it's from GNOME. Example as shown in the image below:
![Captura de tela de 2023-03-25 06-13-05](https://user-images.githubusercontent.com/59381215/227735707-291596b2-385e-469c-8387-ba1d5e2a7928.png)

Expected behaviour

The solution is to copy the gnome icon that is located in categories and paste it in Adwaita in the legacy folder in sizes: 16,22,24,32 and 48. Example as shown in the image below:
![Captura de tela de 2023-03-25 15-50-25](https://user-images.githubusercontent.com/59381215/227735934-7d99941e-ce1a-4021-9b74-e3b6475f0ce5.png)

**Comment by leigh123linux** [comment]
This is no longer relevant as adwaita is blacklisted.

https://github.com/linuxmint/cinnamon/blob/master/files/usr/share/cinnamon/cinnamon-settings/modules/cs_themes.py#L37
