### ISSUE TITLE
Updating from kernel 5.15 to 5.19 doesn't work. Nvidia driver DKMS make fails (`Kernel configuration is invalid`)

### ISSUE THREAD

**Issue by mikkovedru** [linuxmint/cinnamon#11589]
```
* Cinnamon version: 5.6.8
* Distribution: Linux Mint 21.1 Cinnamon
* GPU: GeForce GTX 650. Driver `470.103.01-0ubuntu2`.
* 64 bit
 ```

### Issue
Updating from kernel 5.15 to 5.19 doesn't work because Nvidia driver DKMS make fails (`Kernel configuration is invalid`).
- kernel **5.15**.0-60 works.
- kernel **5.15**.0-67 works.
- kernel **5.19**.0-35 doesn't. After booting Cinnamon can only see one monitor (out of two), which is very low resolution (instead of 1440p).
- kernel **5.19**.0-28 likewise doesn't work.

### Steps to reproduce
1. Try to update the kernel
2. see errors
3. see that `/var/lib/dkms/nvidia/470.103.01` directory doesn't have compiled files for kernel 5.19 despite it being installed.
![2023-03-26_kernel-5 19-nvidia-error](https://user-images.githubusercontent.com/2521942/227749549-df59814d-0755-4559-a3fc-34cc2aef5a98.png)
4. Check the `/var/lib/dkms/nvidia/470.103.01/build/make.log` log: 
[2023-03-26_cinnamon-kernel-5.19-update-error-nvidia-driver-470-make.log](https://github.com/linuxmint/cinnamon/files/11070517/2023-03-26_make.log)
5. Restart and see that cinnamon:
- is showing only on one monitor
- settings don't show the second monitor
- the lone display is in low resolution and the desktop items are in disarray
- settings don't allow to change to higher resolution

**Comment by leigh123linux** [comment]
Report the issue against the nvidia driver.

**Comment by mikkovedru** [comment]
> Report the issue against the nvidia driver.

I don't understand (I am not a native speaker). :-( What do you mean by "against"?

I thought this was a packaging issue. And that it is Linux Mint that handles these kinds of issues? Should I report to Linux Mint, but in some other repo (not Cinnamon?) Or should I go upstream with that? To Ubuntu (since the name is `470.103.01-0ubuntu2`)? Or all the way to Debian?

I would highly appreciate a direct link to the place this bug should be reported, because currently I am totally lost and don't know how to proceed.

**Comment by mtwebster** [comment]
You're using a dated nvidia driver - you should be able to update it to 470.161.03.

What dkms version are you using? It **must** be 2.8.7-2ubuntu2.1mint1.

I'd make sure you're up-to-date with the driver and dkms before making a determination that there's something wrong with the drivers or kernel - 470 works ok for me.

btw, Mint doesn't package the nvidia drivers, we inherit them from Ubuntu.
