### ISSUE TITLE
Kaffeine 2.0.18 on Mint 21.1 

### ISSUE THREAD

**Issue by pinnerite** [linuxmint/cinnamon#11584]
```
 * Cinnamon version (cinnamon --version)
   - Please specify if you are using the daily builds PPA
     (https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds).
 * Distribution - (Mint 21, Arch, Fedora 37, etc...)
 * Graphics hardware *and* driver used
 * 32 or 64 bit
 * Attach ~/.xsession-errors, or /var/log/syslog
 ```
The desktop is Cinnamon on both versions of Mint.

This version of Kaffeine works perfectly in Mint 20.3 and Mageia 8 but not in Mint 21.1.

The symptoms when attempting to display live TV is that  it appears to start, a few words of audio can be heard, then it crashes. 

alan@albury:~$ /usr/bin/kaffeine
22-03-23 22:54:05.772 [Warning ] QCommandLineParser: already having an option named "h"
22-03-23 22:54:05.772 [Warning ] QCommandLineParser: already having an option named "help-all"
22-03-23 22:54:05.772 [Warning ] QCommandLineParser: already having an option named "v"
22-03-23 22:54:06.030 [Info    ] kaffeine.dvb: Using built-in dvb device manager
22-03-23 22:54:06.392 [Info    ] kaffeine.dev: Found dvb device U07f826de: DiBcom 3000MC/P
22-03-23 22:54:06.544 [Info    ] kaffeine.dev: Found dvb device U07f826de: DiBcom 3000MC/P
[00007f66e8004e90] gl gl: Initialized libplacebo v4.192.1 (API v192)
libva info: VA-API version 1.14.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/r600_drv_video.so
libva info: Found init function __vaDriverInit_1_14
libva info: va_openDriver() returns 0
[00007f66e8004e90] glconv_vaapi_x11 gl error: vaDeriveImage: operation failed
[00007f66f001ae80] main video output error: video output creation failed
[00007f66fc037960] main decoder error: failed to create video output
[00007f66e8004e90] gl gl: Initialized libplacebo v4.192.1 (API v192)
[00007f66fc037960] avcodec decoder: Using G3DVL VDPAU Driver Shared Library version 1.0 for hardware decoding
Segmentation fault (core dumped)
alan@albury:~$

### Configuration info, if applicable
If this bug report is related to an Applet, Desklet or Extension, please paste (or use a pastebin service) the offending extension's settings, if it has any.  You can obtain this by opening its configuration, clicking the 'hamburger' button in the upper-right corner of the window, and selecting "Export to a file". **Please be sure to review the contents and remove any personal data it may contain.**

**Comment by leigh123linux** [comment]
File the issue against Kaffeine
