### ISSUE TITLE
Bluetooth not work

### ISSUE THREAD

**Issue by LinuxUser-500** [linuxmint/cinnamon#11596]
* Cinnamon version 5.6.8
 * Distribution: Linux Mint 21.1
 * 64 bit version
 

### Issue
Can't find bluetooth devices.

**Comment by HDDmiller** [comment]
I'm having the same problem after recent updates.

**Comment by HDDmiller** [comment]
Here's some information. 

System:    Kernel: 5.4.0-146-generic x86_64 bits: 64 compiler: gcc v: 9.4.0 
           Desktop: Cinnamon 4.8.6 wm: muffin dm: LightDM Distro: Linux Mint 20.1 Ulyssa 
           base: Ubuntu 20.04 focal 

I don't remember what the recent updates were.  I will check.

**Comment by HDDmiller** [comment]
Ok, I had two updates on April 2.  Here's the log of the first one.

Commit Log for Sun Apr  2 20:45:42 2023


Upgraded the following packages:
mint-upgrade-info (1.1.9) to 1.2.1

**Comment by HDDmiller** [comment]
Here's the second update log from April 2. It was April 3 when my bluetooth stopped working after a reboot.

Commit Log for Sun Apr  2 20:46:20 2023


Upgraded the following packages:
apparmor (2.13.3-7ubuntu5.1) to 2.13.3-7ubuntu5.2
base-files (20.1.0) to 20.1.1
bind9-dnsutils (1:9.16.1-0ubuntu2.12) to 1:9.16.1-0ubuntu2.14
bind9-host (1:9.16.1-0ubuntu2.12) to 1:9.16.1-0ubuntu2.14
bind9-libs (1:9.16.1-0ubuntu2.12) to 1:9.16.1-0ubuntu2.14
bolt (0.9.1-2~ubuntu20.04.1) to 0.9.1-2~ubuntu20.04.2
brave-browser (1.48.171) to 1.49.132
curl (7.68.0-1ubuntu2.16) to 7.68.0-1ubuntu2.18
gvfs (1.44.1-1ubuntu1.1) to 1.44.1-1ubuntu1.2
gvfs-backends (1.44.1-1ubuntu1.1) to 1.44.1-1ubuntu1.2
gvfs-bin (1.44.1-1ubuntu1.1) to 1.44.1-1ubuntu1.2
gvfs-common (1.44.1-1ubuntu1.1) to 1.44.1-1ubuntu1.2
gvfs-daemons (1.44.1-1ubuntu1.1) to 1.44.1-1ubuntu1.2
gvfs-fuse (1.44.1-1ubuntu1.1) to 1.44.1-1ubuntu1.2
gvfs-libs (1.44.1-1ubuntu1.1) to 1.44.1-1ubuntu1.2
krb5-locales (1.17-6ubuntu4.2) to 1.17-6ubuntu4.3
libapparmor1 (2.13.3-7ubuntu5.1) to 2.13.3-7ubuntu5.2
libapparmor1:i386 (2.13.3-7ubuntu5.1) to 2.13.3-7ubuntu5.2
libc-ares2 (1.15.0-1ubuntu0.1) to 1.15.0-1ubuntu0.2
libcurl3-gnutls (7.68.0-1ubuntu2.16) to 7.68.0-1ubuntu2.18
libcurl3-gnutls:i386 (7.68.0-1ubuntu2.16) to 7.68.0-1ubuntu2.18
libcurl4 (7.68.0-1ubuntu2.16) to 7.68.0-1ubuntu2.18
libgssapi-krb5-2 (1.17-6ubuntu4.2) to 1.17-6ubuntu4.3
libgssapi-krb5-2:i386 (1.17-6ubuntu4.2) to 1.17-6ubuntu4.3
libk5crypto3 (1.17-6ubuntu4.2) to 1.17-6ubuntu4.3
libk5crypto3:i386 (1.17-6ubuntu4.2) to 1.17-6ubuntu4.3
libkrb5-3 (1.17-6ubuntu4.2) to 1.17-6ubuntu4.3
libkrb5-3:i386 (1.17-6ubuntu4.2) to 1.17-6ubuntu4.3
libkrb5support0 (1.17-6ubuntu4.2) to 1.17-6ubuntu4.3
libkrb5support0:i386 (1.17-6ubuntu4.2) to 1.17-6ubuntu4.3
libldb2 (2:2.2.3-0ubuntu0.20.04.3) to 2:2.4.4-0ubuntu0.20.04.1
libnss-myhostname (245.4-4ubuntu3.19) to 245.4-4ubuntu3.20
libnss-systemd (245.4-4ubuntu3.19) to 245.4-4ubuntu3.20
libpam-systemd (245.4-4ubuntu3.19) to 245.4-4ubuntu3.20
libprotobuf-lite17 (3.6.1.3-2ubuntu5) to 3.6.1.3-2ubuntu5.2
libprotobuf17 (3.6.1.3-2ubuntu5) to 3.6.1.3-2ubuntu5.2
libpython3.8 (3.8.10-0ubuntu1~20.04.6) to 3.8.10-0ubuntu1~20.04.7
libpython3.8-dev (3.8.10-0ubuntu1~20.04.6) to 3.8.10-0ubuntu1~20.04.7
libpython3.8-minimal (3.8.10-0ubuntu1~20.04.6) to 3.8.10-0ubuntu1~20.04.7
libpython3.8-stdlib (3.8.10-0ubuntu1~20.04.6) to 3.8.10-0ubuntu1~20.04.7
libsmbclient (2:4.13.17~dfsg-0ubuntu1.20.04.5) to 2:4.15.13+dfsg-0ubuntu0.20.04.1
libsnmp-base (5.8+dfsg-2ubuntu2.6) to 5.8+dfsg-2ubuntu2.7
libsnmp35 (5.8+dfsg-2ubuntu2.6) to 5.8+dfsg-2ubuntu2.7
libsnmp35:i386 (5.8+dfsg-2ubuntu2.6) to 5.8+dfsg-2ubuntu2.7
libsystemd0 (245.4-4ubuntu3.19) to 245.4-4ubuntu3.20
libsystemd0:i386 (245.4-4ubuntu3.19) to 245.4-4ubuntu3.20
libtalloc2 (2.3.1-0ubuntu0.20.04.1) to 2.3.3-0ubuntu0.20.04.1
libtdb1 (1.4.3-0ubuntu0.20.04.1) to 1.4.5-0ubuntu0.20.04.1
libtevent0 (0.10.2-0ubuntu0.20.04.1) to 0.11.0-0ubuntu0.20.04.1
libtiff5 (4.1.0+git191117-2ubuntu0.20.04.7) to 4.1.0+git191117-2ubuntu0.20.04.8
libtiff5:i386 (4.1.0+git191117-2ubuntu0.20.04.7) to 4.1.0+git191117-2ubuntu0.20.04.8
libudev1 (245.4-4ubuntu3.19) to 245.4-4ubuntu3.20
libudev1:i386 (245.4-4ubuntu3.19) to 245.4-4ubuntu3.20
libunwind8 (1.2.1-9build1) to 1.2.1-9ubuntu0.1
libwbclient0 (2:4.13.17~dfsg-0ubuntu1.20.04.5) to 2:4.15.13+dfsg-0ubuntu0.20.04.1
linux-generic (5.4.0.139.137) to 5.4.0.146.144
linux-headers-generic (5.4.0.139.137) to 5.4.0.146.144
linux-image-generic (5.4.0.139.137) to 5.4.0.146.144
linux-libc-dev (5.4.0-139.156) to 5.4.0-146.163
opera-stable (96.0.4693.20) to 97.0.4719.43
printer-driver-foo2zjs (20171202dfsg0-4) to 20171202dfsg0-4ubuntu0.1
printer-driver-foo2zjs-common (20171202dfsg0-4) to 20171202dfsg0-4ubuntu0.1
printer-driver-splix (2.0.0+svn315-7fakesync1build1) to 2.0.0+svn315-7fakesync1ubuntu0.1
python-apt-common (2.0.1) to 2.0.1ubuntu0.20.04.1
python3-apt (2.0.1) to 2.0.1ubuntu0.20.04.1
python3-ldb (2:2.2.3-0ubuntu0.20.04.3) to 2:2.4.4-0ubuntu0.20.04.1
python3-protobuf (3.6.1.3-2ubuntu5) to 3.6.1.3-2ubuntu5.2
python3-samba (2:4.13.17~dfsg-0ubuntu1.20.04.5) to 2:4.15.13+dfsg-0ubuntu0.20.04.1
python3-talloc (2.3.1-0ubuntu0.20.04.1) to 2.3.3-0ubuntu0.20.04.1
python3-tdb (1.4.3-0ubuntu0.20.04.1) to 1.4.5-0ubuntu0.20.04.1
python3.8 (3.8.10-0ubuntu1~20.04.6) to 3.8.10-0ubuntu1~20.04.7
python3.8-dev (3.8.10-0ubuntu1~20.04.6) to 3.8.10-0ubuntu1~20.04.7
python3.8-minimal (3.8.10-0ubuntu1~20.04.6) to 3.8.10-0ubuntu1~20.04.7
rsync (3.1.3-8ubuntu0.4) to 3.1.3-8ubuntu0.5
samba (2:4.13.17~dfsg-0ubuntu1.20.04.5) to 2:4.15.13+dfsg-0ubuntu0.20.04.1
samba-common (2:4.13.17~dfsg-0ubuntu1.20.04.5) to 2:4.15.13+dfsg-0ubuntu0.20.04.1
samba-common-bin (2:4.13.17~dfsg-0ubuntu1.20.04.5) to 2:4.15.13+dfsg-0ubuntu0.20.04.1
samba-dsdb-modules (2:4.13.17~dfsg-0ubuntu1.20.04.5) to 2:4.15.13+dfsg-0ubuntu0.20.04.1
samba-libs (2:4.13.17~dfsg-0ubuntu1.20.04.5) to 2:4.15.13+dfsg-0ubuntu0.20.04.1
samba-vfs-modules (2:4.13.17~dfsg-0ubuntu1.20.04.5) to 2:4.15.13+dfsg-0ubuntu0.20.04.1
smbclient (2:4.13.17~dfsg-0ubuntu1.20.04.5) to 2:4.15.13+dfsg-0ubuntu0.20.04.1
systemd (245.4-4ubuntu3.19) to 245.4-4ubuntu3.20
systemd-coredump (245.4-4ubuntu3.19) to 245.4-4ubuntu3.20
systemd-sysv (245.4-4ubuntu3.19) to 245.4-4ubuntu3.20
systemd-timesyncd (245.4-4ubuntu3.19) to 245.4-4ubuntu3.20
tcpdump (4.9.3-4ubuntu0.1) to 4.9.3-4ubuntu0.2
tdb-tools (1.4.3-0ubuntu0.20.04.1) to 1.4.5-0ubuntu0.20.04.1
thunderbird (1:102.7.1+build2-0ubuntu0.20.04.1) to 1:102.9.0+build1-0ubuntu0.20.04.1
thunderbird-gnome-support (1:102.7.1+build2-0ubuntu0.20.04.1) to 1:102.9.0+build1-0ubuntu0.20.04.1
thunderbird-locale-en (1:102.7.1+build2-0ubuntu0.20.04.1) to 1:102.9.0+build1-0ubuntu0.20.04.1
thunderbird-locale-en-us (1:102.7.1+build2-0ubuntu0.20.04.1) to 1:102.9.0+build1-0ubuntu0.20.04.1
ubuntu-advantage-tools (27.13.5~20.04.1) to 27.13.6~20.04.1
udev (245.4-4ubuntu3.19) to 245.4-4ubuntu3.20
vim-common (2:8.1.2269-1ubuntu5.11) to 2:8.1.2269-1ubuntu5.12
vim-tiny (2:8.1.2269-1ubuntu5.11) to 2:8.1.2269-1ubuntu5.12
xserver-common (2:1.20.13-1ubuntu1~20.04.6) to 2:1.20.13-1ubuntu1~20.04.8
xserver-xephyr (2:1.20.13-1ubuntu1~20.04.6) to 2:1.20.13-1ubuntu1~20.04.8
xserver-xorg-core (2:1.20.13-1ubuntu1~20.04.6) to 2:1.20.13-1ubuntu1~20.04.8
xserver-xorg-legacy (2:1.20.13-1ubuntu1~20.04.6) to 2:1.20.13-1ubuntu1~20.04.8
xul-ext-lightning (1:102.7.1+build2-0ubuntu0.20.04.1) to 1:102.9.0+build1-0ubuntu0.20.04.1
xwayland (2:1.20.13-1ubuntu1~20.04.6) to 2:1.20.13-1ubuntu1~20.04.8
xxd (2:8.1.2269-1ubuntu5.11) to 2:8.1.2269-1ubuntu5.12

Installed the following packages:
linux-headers-5.4.0-146 (5.4.0-146.163)
linux-headers-5.4.0-146-generic (5.4.0-146.163)
linux-image-5.4.0-146-generic (5.4.0-146.163)
linux-modules-5.4.0-146-generic (5.4.0-146.163)
linux-modules-extra-5.4.0-146-generic (5.4.0-146.163)

**Comment by HDDmiller** [comment]
Ok, so after checking today, bluetooth now sees my devices.  Not sure why.

HDD

**Comment by LinuxUser-500** [comment]
Hi, same here, mine bluetooth works too now and it see my devices.
I think it's some network issue or something disburting bluetooth connection because I have dual boot on my laptop (Windows 10 and linux mint) and my bluetooth did't work on Windows too, now it works

**Comment by HDDmiller** [comment]
Very strange. I don't have Windows on that particular machine.  Maybe it took a few reboots to fix itself???

**Comment by LinuxUser-500** [comment]
It can be that reboot, usually it solves many issues.
Even in the PC repair store staff didn't know what caused this issue.

**Comment by LinuxUser-500** [comment]
But problem solved.
