### ISSUE TITLE
Audio since upgrade

### ISSUE THREAD

**Issue by FreeBornAngel** [linuxmint/cinnamon#11601]
It has gone to crap.
Range is down.
Screeching tones are up.
When adjusting sound levels I get a high pitched squeal when I've 'gone too far'.
Connectivity is better. 
I'd call this trade off crap.
Maybe before I had to relaunch bluetooth a few times to get my dongle to connect, and now I don't, but I don't need my hearing permanently damaged in return as is now the case.

I use brave, if that makes a difference.

**Comment by leigh123linux** [comment]
Use the template next time and provide the requested info.
