### ISSUE TITLE
Menu overshoot

### ISSUE THREAD

**Issue by greytomorrow** [linuxmint/cinnamon#11603]
#### Summary
When using certain applications, if the menu selection is longer than the vertical screen space, the menu starts above the menu bar with no indicator arrow at the bottom of the list. This obviously impedes continuing towards the right of the menu bar.

#### Attachments
<details>
<summary>LibreOffice 7.3.7.2</summary>
![overshoot_01](https://user-images.githubusercontent.com/63914790/229312450-96130b92-ef58-426c-8843-0946481c7911.jpg)
![overshoot_02](https://user-images.githubusercontent.com/63914790/229312488-a229d5be-a33c-4048-8dbc-6ec747664568.jpg)
</details>
<details>
<summary>Inkscape 1.3</summary>
![overshoot_03](https://user-images.githubusercontent.com/63914790/229312511-88e345ef-af9c-45e8-a2aa-2178bca7813a.jpg)
</details>

Firefox 111.0.1 also has this problem (sorry, no screenshot). GIMP, on the other hand, handles long menus correctly, with arrows at the top and bottom of the menu.

I do not believe this is a per-application problem as, before I switched to Linux Mint/Cinnamon, I used Ubuntu/GNOME and menus always appeared correctly under each menu bar heading. Thank you.

[inxi_2023-04-01.zip](https://github.com/linuxmint/cinnamon/files/11130545/inxi_2023-04-01.zip)

**Comment by greytomorrow** [comment]
Another example, this time in Geany...
![overshoot_05](https://user-images.githubusercontent.com/63914790/229336786-2283e177-5c9c-4648-87bb-5379a7a1bb3e.jpg)

**Comment by greytomorrow** [comment]
Choice of UI fonts (TeX Gyre Heros Condensed) triggered this bug. A quick perusal showed that certain fonts will also trigger the menu overshoot.

Closing. Your choice to investigate further. Thank you.

**Comment by JosephMcc** [comment]
Were logging in and out or restarting your machine after changing the fonts? These kinds of changes can sometimes lead to bugs like this because not everything is properly being updated?

**Comment by greytomorrow** [comment]
@JosephMcc , absolutely. I'd been using that font selection for weeks with at least two or three restarts during that time, once being a kernel update, the other being a power outage.
