### ISSUE TITLE
network@cinnamon.org : The applet doesn't show well

### ISSUE THREAD

**Issue by pzim-devdata** [linuxmint/cinnamon#11622]
```
 * Cinnamon version (cinnamon --version) : Cinnamon 5.6.7

 * System:
  Kernel: 6.1.0-7-amd64 arch: x86_64 bits: 64 compiler: gcc v: 12.2.0 Desktop: Cinnamon v: 5.6.7
    tk: GTK v: 3.24.37 wm: muffin dm: LightDM Distro: Debian GNU/Linux 12 (bookworm)

 * Graphics hardware *and* driver used
   Device-1: Intel TigerLake-LP GT2 [Iris Xe Graphics] driver: i915 v: kernel arch: Gen-12.1 ports:
    active: HDMI-A-1 empty: DP-1, DP-2, DP-3, DP-4 bus-ID: 00:02.0 chip-ID: 8086:9a49
  Display: x11 server: X.Org v: 1.21.1.7 with: Xwayland v: 22.1.9 driver: X: loaded: modesetting
    unloaded: fbdev,vesa dri: iris gpu: i915 display-ID: :0 screens: 1
  API: OpenGL v: 4.6 Mesa 22.3.6 renderer: Mesa Intel Xe Graphics (TGL GT2) direct-render: Yes

 * Network:
  Device-1: Intel Wi-Fi 6 AX201 driver: iwlwifi v: kernel bus-ID: 00:14.3 chip-ID: 8086:a0f0
  IF: wlo1 state: down mac: <filter>
  Device-2: Intel Ethernet I225-LM driver: igc v: kernel pcie: speed: 5 GT/s lanes: 1 port: N/A
    bus-ID: 58:00.0 chip-ID: 8086:15f2
  IF: enp88s0 state: up speed: 100 Mbps duplex: full mac: <filter>
  IF-ID-1: bond0 state: up speed: 100 Mbps duplex: full mac: <filter>
  IF-ID-2: bonding_masters state: N/A speed: N/A duplex: N/A mac: N/A
  IF-ID-3: enxbe4cc46a17d3 state: up speed: N/A duplex: N/A mac: <filter>
  IF-ID-4: tun0 state: unknown speed: 10 Mbps duplex: full mac: N/A

 * Distribution - Debian Bookworm

 * 64 bit
 * Attach ~/.xsession-errors, or /var/log/syslog
[xsession-errors.zip](https://github.com/linuxmint/cinnamon/files/11242987/xsession-errors.zip)

 ```

### Issue
network@cinnamon.org : The applet doesn't show well. Sometimes I can't see any button : 

![Capture d’écran du 2023-04-16 19-29-20](https://user-images.githubusercontent.com/52496172/232330091-a2eb6dc3-93d6-4744-99aa-89591d1e0e8f.png)

### Steps to reproduce

Click on the icon of the network@cinnamon.org applet

### Expected behaviour

I would like to access to the buttons to turn off or turn on network cards

### Configuration info, if applicable
If this bug report is related to an Applet, Desklet or Extension, please paste (or use a pastebin service) the offending extension's settings, if it has any.  You can obtain this by opening its configuration, clicking the 'hamburger' button in the upper-right corner of the window, and selecting "Export to a file". **Please be sure to review the contents and remove any personal data it may contain.**
[network@cinnamon.org_config.json.zip](https://github.com/linuxmint/cinnamon/files/11242999/network%40cinnamon.org_config.json.zip)

Thanks

**Comment by pzim-devdata** [comment]
[xsession-errors.zip](https://github.com/linuxmint/cinnamon/files/11243003/xsession-errors.zip)

**Comment by JosephMcc** [comment]
Trying switching to the default Cinnamon theme. I've never seen this issue before and it's possibly a theme issue.

**Comment by pzim-devdata** [comment]
I already use the default them : Adwaita. It's perhaps because of Debian Bookworm which is in beta. I will wait final release of Debian Bookwarm. Thanks

**Comment by JosephMcc** [comment]
@pzim-devdata No you need to try changing the Desktop theme. It looks like you are using CBlack currently. Change that to the default "Cinnamon" theme. The theme you have set for Applications has no effect on things like the network manager applet.

**Comment by pzim-devdata** [comment]
Yes you are right. When I change from CBlack it works. Thank you

**Comment by JosephMcc** [comment]
Glad you got it working and found the problem.
