### ISSUE TITLE
Audio Improvements

### ISSUE THREAD

**Issue by FreeBornAngel** [linuxmint/cinnamon#11626]
### Is your feature request related to a problem? Please describe.

The new sound management system that came with the update makes the audio entirely too tinny.
Way too much treble and not enough midrange and base.

The screech that occurs when 100% is reached is damaging to my hearing.
My ears ring enough as it is.

These were not issues before the update.

### Describe the solution you'd like
A graphic equalizer so that I can tone down the screeching and maybe add some base.

Eliminate the screech for turning up the volume 'too loud'.

### Describe alternatives you've considered

Rolling back the playback because I couldn't understand what was being said because the treble was too damn high and lacking any base or midrange at all, but didn't want to have to experience the screech for turning the volume 'too loud'.

### Additional context

This is about the only complaint I've found, and I'm grumpy, so you would have heard about it by now if I had.
The bluetooth is working much better now, except on range, that dropped.

**Comment by fredcw** [comment]
Which update do you mean? Also, no Mint or cinnamon update should have any effect on the tone of your computer's sound output as there's no function or code to alter this in either that I'm aware of. Sounds like it might be a hardware issue or due to some other software you've installed perhaps?

**Comment by FreeBornAngel** [comment]
I've been using this setup in this space for more than 18 months.
When the update to 21 came out I installed it and the problems became immediately apparent.
Before the update no screeching tones occurred when the volume went over 90%, in fact I had the option to go to 125% with no screeching tones at all.
That option is no longer available.
Before the  update the range of the headphones dropped out at a specific place in the house, that place is now less distant from the transmitter.
Sound quality was less impacted by hitting the range before the update, and recovery was automatic once the distance to the transmitter was back in range.
Now, recovery is much more intermittent, sometimes I have turn them off and back on to get the static out, even sitting at the computer.

Clearly the bluetooth package was updated, it looks different.
The tone of the sound went to tin, like an old am radio.
The bass dropped out, midrange is diminished and upper range tones are much more obvious.
I have tinnitus and am sensitive to high range sounds.

This is why I suggest an equalizer be developed to allow users to set their own tones and not be restricted to the default settings.

The update did improve bluetooth connectivity.
I don't have to make multiple attempts at getting the headphones to connect, anymore.
I haven't had to time the turn on of both the transmitter and receiver to coincide to get connectivity, it now just mostly works upon turning them on.
So, that is a plus.

But, the sound quality went to crap.

**Comment by fredcw** [comment]
Mint 21 changed from using blueberry to using Bluman so I suspect this is a problem with Blueman bluetooth manager or it's settings. I don't have any bluetooth devices myself so I can't see what options are available in the program but searching online, a few comments suggest turning off "handsfree telephony" or switching to "A2DP sink". I don't know if there are any such options in Blueman.

It would seem unnecessary to install a sound equaliser if the problem can be fixed elsewhere, however if that's the only option then PulseEffects may be useful according to this thread: https://forums.linuxmint.com/viewtopic.php?t=373440

**Comment by FreeBornAngel** [comment]
https://www.addictivetips.com/ubuntu-linux-tips/install-pulseaudio-equalizer-on-linux/
I tried to install the ubuntu version, but when I searched menu, it wasn't there.
I'm new to this, did I miss something?

**Comment by fredcw** [comment]
PulseEffects, not pulseaudio-equaliser. It's in the software manager. When you open the app, click on the tick box next to the equaliser option and then double click on it to open the equaliser. Notice that you have to scroll the equaliser to the right because there's more than can fit on the screen.

**Comment by FreeBornAngel** [comment]
That's just it, the app is not there.
I have 'pulseaudio volume control' and it gives this:
![image](https://user-images.githubusercontent.com/18445737/235335507-11fc1622-e9b8-47de-81ea-0aecc130db42.png)
I'm not seeing 'PulseEffects'.
I tried to screencap the menu, but it wouldn't let me.

**Comment by rcalixte** [comment]
@FreeBornAngel The package is called "pulseeffects" if you install it from the command line.

**Comment by FreeBornAngel** [comment]
Thank you, fredcw, what you typed finally made it through to me.
Now it's just a matter of twisting knobs.
