### ISSUE TITLE
Cinnamon panel: Middle-clicking on the icons of gnome-text-editor and gnome-console does not open a new window

### ISSUE THREAD

**Issue by ktamp** [linuxmint/cinnamon#11620]
Cinnamon version: 5.6.8
Distribution: Arch, 64 bit

### Issue

When a Grouped Window List is configured so that middle-clicking on an application icon always opens a new window, this does not work for **gnome-text-editor** and **gnome-console**.

### Steps to reproduce

- Add a Grouped Window List to the panel.
- Configure the Group Window List so that middle-clicking on an application icon opens a new window.
- Pin the icons of **gnome-text-editor** and **gnome-console** to the task bar.
- Middle-click on the icons of **gnome-text-editor** and **gnome-console** more than once.

### Expected behavior

Middle-clicking on the **gnome-text-editor** and **gnome-console** icons should always open a new window.

### Other information

For other applications, e.g. **gnome-calculator**, middle-clicking always opens a new window as expected.

For GNOME with Dash-to-Panel extension, middle-clicking on the **gnome-text-editor** and **gnome-console** icons works as expected.

### Configuration info, if applicable

[grouped-window-list-settings.json.gz](https://github.com/linuxmint/cinnamon/files/11239978/grouped-window-list-settings.json.gz)

**Comment by JosephMcc** [comment]
This was answered. Not a Cinnamon issue.
