### ISSUE TITLE
Screen blanking on cinnamon lock screen when changing volume via keybindings

### ISSUE THREAD

**Issue by itz-me-zappex** [linuxmint/cinnamon#11632]
Cinnamon 5.6.8
Arch Linux (64 bit)
GPU Nvidia GeForce 1050Ti
Driver proprietary, version 530.41.03
I don't have "~/.xsession-errors" file because using sddm, "/var/log/syslog" absent too

Issue: screen blanking for a few seconds when changing volume on cinnamon lock screen via keybindings.

Steps to reproduce: lock screen and change volume using keybindings (e.g. function keys etc.)

Expected behaviour: showing popup with volume level instead of screen blanking
![image](https://user-images.githubusercontent.com/85901674/233850998-89915fb5-1d4f-4235-8c90-e97164a559a3.png)

**Comment by itz-me-ZaPPeX** [comment]
that is how it works
https://user-images.githubusercontent.com/85901674/234058783-1dfa4666-611f-4152-95ec-544fdc8525ec.mp4
