### ISSUE TITLE
Installing Google Earth Crashes Cinnamon [core dump]

### ISSUE THREAD

**Issue by haggen88** [linuxmint/cinnamon#11657]
### Distribution

Mint 21.1

### Package version

Cinnamon 5.6.8 

### Graphics hardware in use

Intel Haswell-ULT 

### Frequency

Always

### Bug description

Trying to install Google Earth Pro [in deb format from https://www.google.com/earth/about/versions/#download-pro ] crashes Cinnamon. 

### Steps to reproduce

install google-earth-pro-stable_current_amd64.deb

### Expected behavior

Gdebi proceed with the installation of the deb file

### Additional information

logs and report:  [xsession-crash log-crash report.zip](https://github.com/linuxmint/cinnamon/files/11424070/xsession-crash.log-crash.report.zip)

Applets installed: QRedshift and  Weather,

System info: https://termbin.com/4rd8t

**Comment by mtwebster** [comment]
Does this happen immediately when you launch it?

It runs ok for me on a desktop (nvidia) and a laptop using both intel or nvidia.

Did it ever work? Have you tried a different kernel?

**Comment by haggen88** [comment]
The problem occurs in the installation, after mentioning that there is another version in Software Manager. Then the installation crashes. I can't install G.Earth.
