### ISSUE TITLE
Offer an option to use colour icons in notifications

### ISSUE THREAD

**Issue by Secret-chest** [linuxmint/cinnamon#11651]
There are themes with black notifications and I find it very important to quickly see what app the notification comes from.

**Comment by clefebvre** [comment]
That's up to the notification source. We prefer symbolics, but if no symbolics are found we'll use fullcolor. Application icons are usually fullcolor so that doesn't change.

**Comment by Secret-chest** [comment]
I forgot about that. Thanks Clem anyways and thank you all for this best desktop! I must say that.
