### ISSUE TITLE
Network Manager: The previous VPN connection did not disconnect after connecting to a new VPN.

### ISSUE THREAD

**Issue by MeowIce** [linuxmint/Cinnamon#11652]
### Distribution

Mint 21.1

### Package version

5.6.8

### Graphics hardware in use

NVIDIA GT310M

### Frequency

Always

### Bug description

The previous VPN connection did not disconnect after connecting to a new VPN.
I'm connected to VPN 1 and I want to change to VPN 2 for example. Now the VPN 1 connection won't disconnect automatically then the IP address is still from VPN 1 while VPN 2 is shown as connected.

### Steps to reproduce

1. Connect to a VPN server.
2. Continue to connect to another VPN server.
3. The previous VPN did not disconnect.

### Expected behavior

The prev VPN got disconnected before connecting to a new one.

**Comment by claudiux** [comment]
You can try using the VPN-Sentinel applet: https://cinnamon-spices.linuxmint.com/applets/view/368

**Comment by MeowIce** [comment]
> You can try using the VPN-Sentinel applet: https://cinnamon-spices.linuxmint.com/applets/view/368

It doesn't seem to work for me. It keeps crashing with logs about its config file issues...

**Comment by claudiux** [comment]
Ok, I see the problem. I just fixed it. I'll make a new PR.

**Comment by claudiux** [comment]
#4841

**Comment by claudiux** [comment]
https://github.com/linuxmint/cinnamon-spices-applets/pull/4841

**Comment by timur-g** [comment]
Why would it disconnect? One may have multiple VPNs. See #7093 and it's dupe #12081. NotABug IMO.
