### ISSUE TITLE
Remove piercing tone for turning headsets 'too high'.

### ISSUE THREAD

**Issue by FreeBornAngel** [linuxmint/cinnamon#11659]
### Distribution

mint 21.1

### Package version

5.6.8

### Graphics hardware in use

Advanced Micro Devices, Inc. [AMD/ATI] Trinity [Radeon HD 7560D] (prog-if 00 [VGA controller])

### Frequency

Always

### Bug description

When the volume level passes 95 there is a piercing squeal produced by the headset.
This was not the case before the upgrade to 21.
It does it again when the volume us turned back down, giving 2 piercing squeals per incident.

### Steps to reproduce

Turn volume up past 90.
Turn volume back down.

### Expected behavior

Noting should happen.
Whomever thought this was a good idea needs a stern counseling session, imo.

### Additional information

Please tell me how to disable this 'feature'.
I often watch videos recorded in poor sound conditions, in order to understand what is being said I have to turn the volume up as high as it will go.
This new 'feature'  triggers my tinnitus leaving me with ringing ears for some period of time after getting punished for turning the volume 'too high'.

**Comment by leigh123linux** [comment]
Cinnamon uses pulseaudio-libs for sound so there is nothing to fix within cinnamon.
File the issue at.

https://github.com/linuxmint/linuxmint/issues

Also try

https://wiki.archlinux.org/title/Bluetooth_headset#Troubleshooting

**Comment by leigh123linux** [comment]
Have you tried disabling the volume control sound?

![image](https://github.com/linuxmint/cinnamon/assets/1299302/094cae91-42ce-4b85-a27a-628023c6a179)

**Comment by FreeBornAngel** [comment]
Thank you, leigh123.
