### ISSUE TITLE
Why are icon themes being skipped?

### ISSUE THREAD

**Issue by mrkskwsnck** [linuxmint/cinnamon#11675]
I am running Debian Testing (a.k.a. Bookworm) with Cinnamon-Desktop. Trying different themes for icons, I can't go back to the original _gnome_ theme from a user perspective, because it is not listed in the chooser menu.

![image](https://github.com/linuxmint/cinnamon/assets/486983/2e088e7d-b97f-4221-9a89-f997f8acb2a2)

I tried to figure out for myself why this particular folder `/usr/share/icons/gnome` is not processed. Then I stumbled over these lines of code

```python
        for directory in walked:
            if directory[0] in ("gnome", "hicolor"):
                continue
```

See the complete code at https://github.com/linuxmint/cinnamon/blob/9a5a5b7d9cf14b4e44899c1918c2755255e798ea/files/usr/share/cinnamon/cinnamon-settings/modules/cs_themes.py#L132

Unfortunately, there is no comment on why these particular themes are being skipped. Can anyone tell?

**Comment by mtwebster** [comment]
Hicolor only contains application-supplied icons, and the gnome icon theme became the adwaita theme years ago. Ubuntu still keeps the old package (it hasn't updated for 7 years) - Adwaita should be used.
