### ISSUE TITLE
g_setenv/g_unsetenv around meta_init discards some user defined environment variables

### ISSUE THREAD

**Issue by flo-at** [linuxmint/cinnamon#11673]
### Distribution

Arch

### Package version

5.6.8

### Frequency

Always

### Bug description

It's not possible to globally define `NO_AT_BRIDGE`, `NO_GAIL` (and probably some others) so that applications started inside Cinnamon will have them set as intended.

The reason is the combination or `g_setenv` / `g_unsetenv` around `meta_init`. The correct behaviour would be to save the old values of the affected variables and restore them instead of unsetting the variable.

### Steps to reproduce

Try to set `NO_AT_BRIDGE=1` in `/etc/environment`, `/etc/profile`, `~/.xprofile` or any of these and start cinnamon. It will be unset because of the bug and not affect the child processes as intended.

### Expected behavior

It should be possible to globally set the affected variables to whatever value the user wants them to be.

### Additional information

This is one of the lines that need to be changed: https://github.com/linuxmint/cinnamon/blob/ec10d06d56f19fb211631ab108f7eb5a2d7f668d/src/main.c#L342

**Comment by flo-at** [comment]
If I get some feedback on this, I'd create a PR.

**Comment by mtwebster** [comment]
This should be fine I think
