### ISSUE TITLE
Cloudsmith Balena Etcher update error stopping from updating other repositories. 

### ISSUE THREAD

**Issue by Skyler0x2** [linuxmint/cinnamon#11683]
### Distribution

21.1

### Package version

5.6.8

### Graphics hardware in use

RTX 3060 TI

### Frequency

Always

### Bug description

When trying to use "sudo apt update," terminal outputs:

  Err:2 https://dl.cloudsmith.io/public/balena/etcher/deb/linuxmint vanessa InRelease 402  Payment Required [IP:]

  The repository 'https://dl.cloudsmith.io/public/balena/etcher/deb/linuxmint vanessa InRelease' is no longer signed 

  GPG error: http://repository.spotify.com stable InRelease: The following signatures couldn't be verified because the 
  public key is not available:

  The repository 'http://repository.spotify.com stable InRelease' is not signed.

  Updating from such a repository can't be done securely, and is therefore disabled by default.
  

I am not sure why its trying to source Balena etcher or Spotify since I do not have Balena etcher nor Spotify installed. This error is preventing me from update other repositories. 

### Steps to reproduce

Typing "sudo apt update." in terminal.

### Expected behavior

"sudo apt update" should update everything that has an update available.  

### Additional information

I removed some information such as IP addresses for privacy and security reasons from the outputted results when typing in "sudo apt update" into terminal.

**Comment by leigh123linux** [comment]
Your issue has nothing to do with cinnamon.

**Comment by fredcw** [comment]
Maybe you have a PPA in your software sources that is no longer needed/out of date. Go to menu>Software Sources>PPAs and remove any PPAs that you no longer need.

**Comment by Skyler0x2** [comment]
> Maybe you have a PPA in your software sources that is no longer needed/out of date. Go to menu>Software Sources>PPAs and remove any PPAs that you no longer need.

This seemed to have fixed the issue. Thank you.
