### ISSUE TITLE
Volume Bar Should Use Logarithmic Scale

### ISSUE THREAD

**Issue by blausand** [linuxmint/cinnamon#11692]
### Distribution

Mint 21.1

### Package version

5.6.8

### Graphics hardware in use

NVIDIA Corporation GA104M [GeForce RTX 3070 Mobile / Max-Q]

### Frequency

Always

### Bug description

Volume Slider should be logarithmic

### Steps to reproduce

Slide down volume by 25%

### Expected behavior

Volume is perceived as 25% lower

### Additional information

Volume is perceived as -80%

**Comment by Secret-chest** [comment]
Can you explain more?

**Comment by blausand** [comment]
What facts are missing? I'm talking about Linux Mint's standard system volume slider, stating that it should work on a logarithmic scale while it obviously doesn't.
