### ISSUE TITLE
If I use Super for moving windows, Alt+Tab gets broken after hitting Super once

### ISSUE THREAD

**Issue by mikkorantalainen** [linuxmint/Cinnamon#1169]
Steps to reproduce:
(1) Set dconf setting `/org/gnome/desktop/wm/preferences/mouse-button-modifier` to `<Super>` (see http://askubuntu.com/questions/118151/disable-alt-for-window-move-in-gnome-shell)
(2a) Move a window by holding Super ("Windows key") and dragging the window around with left mouse button.
(2b) [Alternatively] Resize a window by holding Super ("Windows key") and dragging the window around with middle mouse button.
(3) Try to open Cinnamon menu ("Start button") by hitting Super once.
(4) Press Alt+Tab to change window

Expected Result:
Window should be changed

Actual Result:
Nothing happens

Additional info:
This seems to mess "hit Super to open Menu" ("Start button") and all keyboard shortcuts that use Super (for example, I'm trying to use Super+T to open a new terminal). The Super key starts to work better if I change windows with a mouse. This issue may be related to https://bugzilla.gnome.org/show_bug.cgi?id=662476

**Comment by dalcde** [comment]
We are no longer using GNOME settings daemon, and this is no longer reproducable.
