### ISSUE TITLE
Section headers disappeared (for other modules) in settings after entering the gesture module when no supported devices are available

### ISSUE THREAD

**Issue by anaximeno** [linuxmint/cinnamon#11697]
### Distribution

Mint 21 - Alpha Testing

### Package version

Cinnamon 5.8 (Daily builds)

### Frequency

Always

### Bug description

Section headers disappeared (for other modules) in settings after entering the gesture module when no supported devices are available. 

### Steps to reproduce

Just enter the settings application and enter the gestures module (when having no supported devices) and get out of there and try to open another setting module that should have a header section (where you can choose different sections like Manage, and Download in applets).

### Expected behavior

After entering the gestures module and no supported devices are found, when returning to the main view of the settings app and entering another module, it should have its section header (if it had one).

### Additional information

If you close the settings app and open it again the header sections are restored. If you got to the gesture module the process is repeated again.

**Comment by mtwebster** [comment]
Thanks
