### ISSUE TITLE
moving icons on desktop "disable" desktop

### ISSUE THREAD

**Issue by logan001** [linuxmint/cinnamon#11707]
### Distribution

archlinux

### Package version

Cinnamon 5.8.1

### Graphics hardware in use

APU

### Frequency

Always

### Bug description

i wanted to move the trash icon on desktop and the icon kept going back in same place. after repeating this for 2-3 times all icons disappears and there is no reaction with right click on desktop

### Steps to reproduce

see above

### Expected behavior

to work

### Additional information

fresh install or archlinux/cinnamon

**Comment by mtwebster** [comment]
Fixed in 5.8.2:
https://github.com/linuxmint/nemo/commit/820027c4eb2fd4b588f6f6c93aa5d880b1a80b73
