### ISSUE TITLE
Hardware video decoding does not work on 12th gen Intel

### ISSUE THREAD

**Issue by ChiefBigFeather** [linuxmint/cinnamon#11729]
### Distribution

Mint 21.1

### Package version

5.6.8

### Graphics hardware in use

1250u

### Frequency

Always

### Bug description

Hardware video decoding is not supported for 12th gen intel GPUs with the intel media drivers currently available in the packet manager. 12th gen intel GPUs apparently need intel-media-drivers 22.6 or later for vaapi to work. See this thread for more info and confirmation: https://github.com/intel/media-driver/issues/1371

### Steps to reproduce

This should be the case on all mobile Alderlake CPUs, maybe desktop too.

### Expected behavior

We need a newer version of intel-media-drivers and it's dependencies in the software manager.

**Comment by leigh123linux** [comment]
Not a cinnamon issue.

https://github.com/linuxmint/linuxmint/issues

**Comment by ChiefBigFeather** [comment]
Sorry, posted the issue over there.
