### ISSUE TITLE
Terminal GUI Bug

### ISSUE THREAD

**Issue by kaifkh20** [linuxmint/cinnamon#11722]
### Distribution

Mint 21.1

### Package version

5.6.8

### Graphics hardware in use

Intel Corporation GeminiLake [UHD Graphics 600] [8086:3185]

### Frequency

Always

### Bug description

https://github.com/linuxmint/cinnamon/assets/127656823/d4b358ac-40b6-496e-9c61-924816ed00e5

### Steps to reproduce

As shown in the video above.

### Expected behavior

It should not replicate it.

**Comment by fredcw** [comment]
Probably best to report the bug here: https://gitlab.gnome.org/GNOME/gnome-terminal/-/issues

**Comment by kaifkh20** [comment]
Thank you I reported it

**Comment by rcalixte** [comment]
Interestingly enough, I can generate somewhat similar behavior from mate-terminal. (I use mate-terminal as a default in Cinnamon with gnome-terminal as a backup.) I can also confirm this behavior with both terminals in other desktop environments.

**Comment by kaifkh20** [comment]
I wonder why. What do you think?

**Comment by rcalixte** [comment]
It might have been there a while. I don't make a habit of shrinking my terminals manually, nor that frequently. And mate-terminal was forked from gnome-terminal some time back so the code bases are largely very similar.

**Comment by kaifkh20** [comment]
It's shocking no one noticed this as far as I know.

**Comment by JosephMcc** [comment]
Your video doesn't seem to be showing anymore.

**Comment by kaifkh20** [comment]
It's visible to me.

**Comment by kaifkh20** [comment]
It's fixed with the new Update.

**Comment by kaifkh20** [comment]
![image](https://github.com/linuxmint/cinnamon/assets/127656823/6e4368e0-543f-423a-9c3b-51a58e5674e9)
