### ISSUE TITLE
[Bug] Not install Kernel 5.15.0.75

### ISSUE THREAD

**Issue by VuzzyM** [linuxmint/cinnamon#11721]
### Distribution

Mint Xfce 21.1

### Package version

5.6.8

### Graphics hardware in use

Geforge GT 710 - proprietary drivers

### Frequency

Always

### Bug description

Hello. The new kernel is not installed from the update manager, it has already tried for the third time and it still gives these errors. Please fix, thanks.

### Steps to reproduce

It is updated from the update manager and gives errors.

### Expected behavior

The new kernel should be installed correctly.

### Additional information

Processing triggers for linux-image-5.15.0-75-generic (5.15.0-75.82) ...
/etc/kernel/postinst.d/dkms:
 * dkms: running auto installation service for kernel 5.15.0-75-generic
   ...done.
/etc/kernel/postinst.d/initramfs-tools:
update-initramfs: Generating /boot/initrd.img-5.15.0-75-generic
I: The initramfs will attempt to resume from /dev/sda2
I: (UUID=eed09d7e-7d62-42d4-a14e-83c1ebcd9e41)
I: Set the RESUME variable to override this.
zstd: error 25 : Write error : No space left on device (cannot write compressed block) 
E: mkinitramfs failure zstd -q -1 -T0 25
update-initramfs: failed for /boot/initrd.img-5.15.0-75-generic with 1.
run-parts: /etc/kernel/postinst.d/initramfs-tools exited with return code 1
dpkg: error processing package linux-image-5.15.0-75-generic (--configure):
 installed linux-image-5.15.0-75-generic package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 linux-image-5.15.0-75-generic
E: Sub-process /usr/bin/dpkg returned an error code (1)
A package failed to install.  Trying to recover:
Setting up linux-image-5.15.0-75-generic (5.15.0-75.82) ...
Processing triggers for linux-image-5.15.0-75-generic (5.15.0-75.82) ...
/etc/kernel/postinst.d/dkms:
 * dkms: running auto installation service for kernel 5.15.0-75-generic
   ...done.
/etc/kernel/postinst.d/initramfs-tools:
update-initramfs: Generating /boot/initrd.img-5.15.0-75-generic
I: The initramfs will attempt to resume from /dev/sda2
I: (UUID=eed09d7e-7d62-42d4-a14e-83c1ebcd9e41)
I: Set the RESUME variable to override this.
zstd: error 25 : Write error : No space left on device (cannot write compressed block) 
E: mkinitramfs failure zstd -q -1 -T0 25
update-initramfs: failed for /boot/initrd.img-5.15.0-75-generic with 1.
run-parts: /etc/kernel/postinst.d/initramfs-tools exited with return code 1
dpkg: error processing package linux-image-5.15.0-75-generic (--configure):
 installed linux-image-5.15.0-75-generic package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 linux-image-5.15.0-75-generic

**Comment by fredcw** [comment]
I don't know anything about this but it says: zstd: error 25 : Write error : No space left on device (cannot write compressed block)

Do you have enough disk space?

**Comment by leigh123linux** [comment]
This isn't a cinnamon issue.

https://github.com/linuxmint/mintinstall/issues
