### ISSUE TITLE
Pulseaudio randomly causing lots of power draw

### ISSUE THREAD

**Issue by ChiefBigFeather** [linuxmint/cinnamon#11730]
### Distribution

Mint 21.1

### Package version

5.6.8

### Frequency

Quite often

### Bug description

The pulseaudio process sometimes does not go to sleep correctly. One such occasion I could make out is when muting the audio while on my Laptop speakers.

### Steps to reproduce

Mute the audio and start powertop to see pulseaudio drawing needlessly much battery.

### Expected behavior

Pulseaudio shouldn't require this much CPU time in the first place and should go to sleep properly.

### Additional information

Pulseaudio has had known issues for a long time, maybe Linux Mint could switch to pipewire?

**Comment by leigh123linux** [comment]
Not a cinnamon issue.

https://github.com/linuxmint/linuxmint/issues

**Comment by ChiefBigFeather** [comment]
Sorry, posted the issue over there.
