### ISSUE TITLE
Blueman-Applet tray icons don't follow the icon theme's that I have installed in Mint 21.1 Cinnamon

### ISSUE THREAD

**Issue by adrummer354** [linuxmint/cinnamon#11748]
I like all of the icons from epapirus-dark theme that I installed manually in Mint 21.1 Cinnamon except for the status tray icon that shows up for the blueman-applet 2.3.5 icons which don't change when I use the epaprius-dark icon theme. I want to keep my icon theme as epapirus-dark for most of my icons except I want to see the icon theme of Numix's style of icons for the blueman-applet in my system tray. I think that the blueman-applet/blueman-manager or the OS overrides my set epaprius-dark's icon theme's preferences and that blueman-applet maybe uses gnome's icons which are very dull and don't fit my desired icons which are the ones for numix/epaprius. I could send you a link to see what I mean. Have a look at this: https://imgur.com/a/XsMBw4Z

This is a more full list of the Numix style of icons I would want to use: https://imgur.com/a/ZqA3e21

**Comment by Hilyxx** [comment]
Blueman has custom icons. You need to change epapirus bluetooth icon name with name "blueman-symbolic.svg", "blueman-disabled-symbolic.svg" ect..

![Capture d’écran du 2023-07-25 00-12-43](https://github.com/linuxmint/cinnamon/assets/21991448/bba08841-8d1d-41d7-b76b-4fcbadde7658)

**Comment by adrummer354** [comment]
I got this changed out and the icons swtiched over to my preferred icon style when I changed them and renamed them
