### ISSUE TITLE
steam gui can't render after update to mint cinnamon 21.2

### ISSUE THREAD

**Issue by Lavoista** [linuxmint/cinnamon#11764]
### Distribution

Mint 21.2

### Package version

Cinnamon 5.8.4

### Graphics hardware in use

Rx 6600M

### Frequency

Always

### Bug description

After a succesfull update to Mint 21.2 from Mint 21.1, everything went fine, So I tried to game a little after rebooting the pc and loading steam, steam GUI can't render its gui, it tries to render but it blinks on an interval like 7-10 sec approximately

I uninstalled all steam-* and reinstall again, but same thing steam gui is not visible on screen, only its tray icon, trying to access any option from the tray icon show nothing

### Steps to reproduce

* a recently updated Mint/Cinammon 21.2
* start steam 
* try to use steam normally
* gui is not usable because it cannot render

### Expected behavior

* before update in mint 21.1 steam worked just fine

### Additional information
Linux HX90G 6.4.3 #1 SMP PREEMPT_DYNAMIC Sun Jul 16 03:58:01 -04 2023 x86_64 x86_64 x86_64 GNU/Linux
In mint 21.1 was using kernel 6.4.3, so using same kernel in mint 21.2
cpu CPU: AMD Ryzen 9 5900HX with Radeon Graphics (16) @ 3.300GHz
memory:  3762MiB / 63716MiB
GPU: AMD ATI 08:00.0 Cezanne
GPU: AMD ATI Radeon RX 6600/6600 XT/6600M

_No response_

**Comment by leigh123linux** [comment]
I doubt it's cinnamon at fault.
Report it to https://github.com/linuxmint/linuxmint/issues
