### ISSUE TITLE
Cinnamon menu applet left column entries flicker when hovering the mouse

### ISSUE THREAD

**Issue by pxcandeias** [linuxmint/cinnamon#11761]
### Distribution

Mint 21.2

### Package version

Cinnamon 5.8.4

### Graphics hardware in use

Intel Haswell-ULT Integrated Graphics

### Frequency

Always

### Bug description

When menu applet window is too small to show all items in the left side column, they flicker when hovering the mouse after scrolling the items full down (see attached video).

https://github.com/linuxmint/cinnamon/assets/11465815/c40a09b0-a105-442a-8628-6812f94c4445

### Steps to reproduce

Occurred right after Mint 21.2 upgrade. Running on bare metal, not virtual machine.

### Expected behavior

No flickering of the menu applet items (like when the items are scrolled full up).

### Additional information

Rebooted cinnamon, rebooted system, still occurs. Also happens on a completely different machine with freshly installed LM 21.2. May be related to issue #11760?

**Comment by anatolij-novoselcev** [comment]
I have the same problem 

https://github.com/linuxmint/cinnamon/assets/111016103/fd6128c1-beec-4ed6-86ab-3dcab5d47313

**Comment by basarkat** [comment]
I also have exactly the same problem.

https://github.com/linuxmint/cinnamon/assets/124076478/2468b8b0-1e39-4931-aaa9-c544954a1ad1

**Comment by BlazTech** [comment]
I have the same problem

**Comment by alexkuz** [comment]
I tried to debug this a bit, with no success so far.
What I've noticed:
- this only affects category list, applications are fine
- it affects specifically the right area of the list (about 130px in width)
- disabling vector mask (which is a unique mechanism for category list) doesn't help
![image](https://github.com/linuxmint/cinnamon/assets/790659/8b281412-3326-4492-b8ac-bf9cd18ff05a)

**Comment by pxcandeias** [comment]
This issue is definitely related to https://github.com/linuxmint/cinnamon/issues/11760. The fix presented there by @claudiux also solves this one. I had to manually change the `/usr/share/cinnamon/applets/menu@cinnamon.org/applet.js` file as the fix has not been merged yet in Linux Mint 21.3 Cinnamon 6.0.4.

I propose to mark this issue as solved and to close it.
