### ISSUE TITLE
Desktop handling crashes when trying to move link icons generated from Firefox

### ISSUE THREAD

**Issue by sponix** [linuxmint/cinnamon#11763]
### Distribution

Mint 21.2 Cinnamon Edition

### Package version

5.8.4

### Graphics hardware in use

virt-manager vm default video

### Frequency

Always

### Bug description

If you drag a link to the desktop from Firefox of say slashdot.org and then try to move that link icon it crashes the Desktop handling completely. There is no more icons shown, no mouse clicks there work like the right click menu.

### Steps to reproduce

Load a webpage in Firefox, drag the link of that page from the URL bar onto the Desktop. Right Click the Desktop, and go to Customize on that menu to toggle off auto-arrange. Then try to move that icon to another location on the Desktop.

### Expected behavior

It is expected that the icon just move to the new location on the Desktop, like the "computer" or "home" icons will if I have them present.

### Additional information

If you cannot reproduce this as I have (originally reported to me by a new user). Then let me know and I can do an OBS recording of the situation to clarify. Please write to me at sponix2ipfw@yahoo.com if needed

**Comment by mtwebster** [comment]
Fixed by:

https://github.com/linuxmint/nemo/commit/c64905efd219a4da64846e600ebd1f4ed0583131
