### ISSUE TITLE
Missing preview windows when hovering over icons in taskbar

### ISSUE THREAD

**Issue by DragonAzzy** [linuxmint/cinnamon#11767]
### Distribution

Mint 21.2

### Package version

Cinnamon 5.8.4

### Graphics hardware in use

Intel Corporation HD Graphics 630

### Frequency

Always

### Bug description

Only 1 window preview when hovering over icons in taskbar when opening new windows with middle-click on icon.

### Steps to reproduce

Firstly, configure applet preferences in the taskbar such that clicking on the middle button launches a new app instance.

--Doesn't work at all--
Launch any window (eg: Chrome) by clicking on the icon in the taskbar.
Launch a new instance by clicking the middle mouse button of the same icon (eg: Chrome).
Hover your mouse over the icon.
Only 1 window preview is visible.

--Does work partially--
Now launch an instance of that same application (eg: Chrome) through the menu.
Hover your mouse over the icon.
Only 2 window previews are visible (1 still missing).

### Expected behavior

Launching a new app instance in any manner should provide the same previewability for the instances you've launched.

### Additional information

Only started happening since I upgraded from Mint 21.1 to Mint 21.2

**Comment by mtwebster** [comment]
Looks like maybe the same as #11106.

Fixed today:
https://github.com/linuxmint/cinnamon/commit/2faa38d93fb5e1cac95e42662153e3fe2266ffb2

**Comment by DragonAzzy** [comment]
Similar area of concern but I dont think its the same issue.  It also says its random where my issue is not and so should be easier to isolate?

**Comment by burtek** [comment]
@mtwebster the fix isn't released yet, right?
