### ISSUE TITLE
Reminders: Something went wrong

### ISSUE THREAD

**Issue by Pamnem** [linuxmint/cinnamon#11766]
### Distribution

Linux Mint 21.2

### Package version

Cinnamon 5.8.4

### Graphics hardware in use

AMD Radeon RX 550

### Frequency

Always

### Bug description

Traceback (most recent call last):
  File "/app/lib/python3.10/site-packages/remembrance/browser/application.py", line 285, in run_service_method
    retval = self.service.call_sync(
gi.repository.GLib.GError: g-io-error-quark: Timeout was reached (24)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/lib/python3.10/site-packages/remembrance/browser/application.py", line 285, in run_service_method
    retval = self.service.call_sync(
gi.repository.GLib.GError: g-io-error-quark: Timeout was reached (24)

### Steps to reproduce

Open the "Reminders" app

### Expected behavior

Just open

**Comment by mtwebster** [comment]
The flatpak starts and runs ok for me. It looks like there's already an issue here: https://github.com/remindersdevs/Reminders/issues/51

Has it ever worked? Have you modified its permissions maybe using the Flatseal app?

The highlighted service is what's not responding:
![image](https://github.com/linuxmint/cinnamon/assets/262776/8655478a-2684-4c4e-8943-92ae0cb5d5ba)

If you install the 'd-feet' app (using apt or software manager), you can see if that's running.

It's not a cinnamon issue so closing this.
