### ISSUE TITLE
Linux Mint 21.2 - Theme changes are not being retained.

### ISSUE THREAD

**Issue by krsoulsby** [linuxmint/cinnamon#11771]
### Distribution

Mint 21.2

### Package version

5.8.4

### Graphics hardware in use

NVIDIA GeForce RTX 3060 Ti

### Frequency

Always

### Bug description

Any changes to the desktop theme using the System Settings are not retained.  Originally noted on upgrading to 21.2 from 21.1 where I had used the Mint-Y-Dark Icons.  As these no longer appear to be available my icons changed to a set of default icons.

Trying to change my icon them to anything else worked until cinnamon restarted (due to rebooting, login in and out, Alt-F2 and r) after which the icon theme reset to Mint-Y-Dark Icons (and the generic icons).

Since then I have tried changing all of the other theme-able areas (Applications and Desktop) and tried to change using the "Simplified Settings." All these changes worked initially but are not retained on restarting cinnamon.

### Steps to reproduce

1. Have Linux Mint 21.1 with (applications = Mint-Y-Dark; Icons = Mint-Y-Dark; Desktop = Mint-Y-Dark)
2. Upgrade to Linux Mint 21.2
3. Try to change any of the themes under "Themes" in System Setting
4. Restart Cinnamon (reboot | log out/in | CLI "r")
5. Themes return to original settings

### Expected behavior

Changes to Themes are retained after changing.  Not returning to original values on restarting Cinnamon

**Comment by claudiux** [comment]
Same here.

**Comment by claudiux** [comment]
Using dconf-editor, we can see that the value `/org/cinnamon/desktop/interface/icon-theme` is reset to 'Mint-Y-Dark' after restarting Cinnamon.

**Comment by krsoulsby** [comment]
After the updates made yesterday (15 September 2023) it appears to be fixed on my PC.  However looking at my update history I can't see any mint/cinnamon packages which have just been updated.  Last mint/cinnamon updated appeared to be 30 August 2023 and the above problem was still occurring after then.

**Comment by claudiux** [comment]
I solved this issue removing the 'darkmode@linuxedo' applet from my panel.

**Comment by krsoulsby** [comment]
> I solved this issue removing the 'darkmode@linuxedo' applet from my panel.

There was an update of that applet on the 3rd September, looks like they have fixed it there as well
