### ISSUE TITLE
Calculator doesn't open

### ISSUE THREAD

**Issue by danielgiljara** [linuxmint/cinnamon#11777]
### Distribution

Mint 21.1

### Package version

Cinnamon 5.6.8

### Frequency

Always

### Bug description

Calculator opens. But remains in taskbar and it is not shown.

### Steps to reproduce

Click on Linux Mint menu.
Type "calculator" on search box.
Click on Calculator.

### Expected behavior

Calculator should be shown.

### Additional information

Calculator is not shown.

**Comment by claudiux** [comment]
All works well here. Can't reproduce this issue.

**Comment by danielgiljara** [comment]
How can I reproduce it in other machine? What can I do? Reinstall Linux Mint? Any logs can I see?

**Comment by fredcw** [comment]
>But remains in taskbar and it is not shown.

What happens when you click on the icon in the taskbar?

Also, what happens if you type

`
gnome-calculator
`

into a terminal?

**Comment by danielgiljara** [comment]
> What happens when you click on the icon in the taskbar?

It doesn't open.

> Also, what happens if you type
>
> gnome-calculator
>
> into a terminal?

Shows the following message:

> (gnome-calculator:7): dbind-WARNING **: 10:29:58.888: Couldn't connect to accessibility bus: Failed to connect to socket /run/user/1000/at-spi/bus_0: No such file or directory

**Comment by claudiux** [comment]
Do you have any broken packages? Please use `synaptic-pkexec` and look at Status.

**Comment by claudiux** [comment]
Please give the result of the command:
`ls -l /run/user/1000/at-spi/`

On my computer:
```
total 0
srwxrwxrwx 1 <user> <group> 0 juil. 26 13:44 bus_0
```

**Comment by danielgiljara** [comment]
I will reinstall Linux Mint. By some reason that folder is not working on my system.

**Comment by danielgiljara** [comment]
Well, I don't know if want to continue with this issue.

The result of first command is:

`daniel@daniel-IdeaPad-3-15ITL6:~$ ls -l /run/user/1000/at-spi/
total 0
srwxrwxrwx 1 daniel daniel 0 jul 26 18:27 bus_0`

The result of systemctl on both services is "Active: active (running)".

**Comment by claudiux** [comment]
Yes, try to reinstall LM. I'm sorry I can't help you more.

**Comment by danielgiljara** [comment]
Ok! I will reinstall LM. Non deterministic behaviors!

**Comment by kzsa** [comment]
Hi,
I experienced the same error on my freshly installed system, then after a long trial I became suspicious that the problem occurred after installing firejail. Of course I ran a few rounds of unnecessary reinstallations before... :)

```
~$ gnome-calculator 

(gnome-calculator:9): dbind-WARNING **: 10:57:49.423: Couldn't connect to accessibility bus: Failed to connect to socket /run/user/1000/at-spi/bus_0: No such file or directory
```

```
~$ firejail --top

PID     User      RES(KiB) SHR(KiB) CPU%  Prcs Uptime    Command
5998    <USR>     61148    48640    99.7  5    00:00:25  firejail /usr/bin/gnome-calculator
```

```
~$ which gnome-calculator 
/usr/local/bin/gnome-calculator

~$ firejail --debug /usr/local/bin/gnome-calculator 
Building quoted command line: '/usr/local/bin/gnome-calculator' 
Warning: an existing sandbox was detected. /usr/local/bin/gnome-calculator will run without any additional sandboxing features
Starting application
LD_PRELOAD=(null)
execvp argument 0: /usr/local/bin/gnome-calculator
Warning: an existing sandbox was detected. /usr/bin/gnome-calculator will run without any additional sandboxing features

(gnome-calculator:35): Handy-CRITICAL **: 10:55:59.890: Couldn't read the color-scheme setting: GDBus.Error:org.freedesktop.DBus.Error.AccessDenied: Portal operation not allowed: Unable to open /proc/5296/root

(gnome-calculator:35): Handy-CRITICAL **: 10:55:59.892: Couldn't read the color-scheme setting: GDBus.Error:org.freedesktop.DBus.Error.AccessDenied: Portal operation not allowed: Unable to open /proc/5296/root

(gnome-calculator:35): Handy-CRITICAL **: 10:55:59.894: Couldn't read the high-contrast setting: GDBus.Error:org.freedesktop.DBus.Error.AccessDenied: Portal operation not allowed: Unable to open /proc/5296/root
```

I ran it using --debug and lo and behold:

![image](https://github.com/linuxmint/cinnamon/assets/59151228/709a10d5-d949-420f-8c9d-562592387e06)

Finally, after identifying the cause of the error, I ended up here:
https://github.com/netblue30/firejail/issues/4173

I hope this helps others too!
Br: Zsolt

**Comment by danielgiljara** [comment]
Yes. I experienced the error dissapears when desinstalled firejail.

**Comment by kzsa** [comment]
You can still use firejail, you just need to create a local profile for the calculator here: 

/home/\<username>\/.config/firejail/gnome-calculator.profile

and the gnome-calculator.profile should contain this:
```
private-bin gnome-calculator,sh
ignore include disable-shell.inc
include /etc/firejail/gnome-calculator.profile
```

For example:
```
mkdir -p ~/.config/firejail && echo "private-bin gnome-calculator,sh
ignore include disable-shell.inc
include /etc/firejail/gnome-calculator.profile" > ~/.config/firejail/gnome-calculator.profile
```
Br: Zsolt

**Comment by rusty-snake** [comment]
> you just need to create a local profile for the calculator here:
> /home/<username>/.config/firejail/gnome-calculator.profile

That's not the way you create a local override profile. It should be `gnome-calculator.local`. That way you can omit the installation dependet `include /etc/firejail/gnome-calculator.profile`.

**Comment by kzsa** [comment]
> > you just need to create a local profile for the calculator here:
> > /home//.config/firejail/gnome-calculator.profile
> 
> That's not the way you create a local override profile. It should be `gnome-calculator.local`. That way you can omit the installation dependet `include /etc/firejail/gnome-calculator.profile`.

Hi rusty-snake,
Thank you for correcting me and for your work in firejail! I have crossed out the part that was wrong.
Br: Zsolt

**Comment by rusty-snake** [comment]
Yes. Better use https://github.com/netblue30/firejail/wiki/Creating-overrides and https://github.com/netblue30/firejail/wiki/Creating-Profiles.

> Apart from the possibility to omit the import, is there a difference between ".local" and "customized profile"?

Not really, mostly convenience.
