### ISSUE TITLE
Prefered applications: Blu-Ray -> Blu-ray and HD-DVD -> HD DVD

### ISSUE THREAD

**Issue by InfoLibre** [linuxmint/cinnamon#11774]
### Distribution

Linux Mint 21.2

### Package version

5.8.4

### Frequency

Always

### Bug description

In Preferences - Preferred applications and at other places: Blu-Ray -> Blu-ray and HD-DVD -> HD DVD

![Capture d’écran du 2023-07-22 11-28-30](https://github.com/linuxmint/cinnamon/assets/3955499/9629b1bf-0218-4965-a56e-bb39c353b0f7)

See official logos on:

https://fr.wikipedia.org/wiki/Disque_Blu-ray

https://fr.wikipedia.org/wiki/HD_DVD

### Steps to reproduce

Open Linux menu **Preferences - Preferred applications**. Click on button **Other medias** and choose **disque Blu-Ray vierge** or **disque HD-DVD vierge**.

Perhaps it's only in the french translation, perhaps it's in all translations.

### Expected behavior

Blu-ray instead of Blu-Ray.
HD DVD instead of HD-DVD

**Comment by claudiux** [comment]
I've just made the requested changes. You'll have to wait for the next time the new translations are taken into account.

**Comment by InfoLibre** [comment]
Thank you very much.

**Comment by InfoLibre** [comment]
I'm trying Linux Mint 21.3 with Cinnamon 6.0.4 and the changes are not taken into account.

**Comment by InfoLibre** [comment]
Changes are done in Linux Mint 22.1. Thank you very much.
