### ISSUE TITLE
Applets settings window width is reduced to 800 px at start and can be reduced to less than 800 px but not after clicking on a button in its title-bar

### ISSUE THREAD

**Issue by InfoLibre** [linuxmint/cinnamon#11789]
### Distribution

Linux Mint 21.2

### Package version

5.8.4

### Frequency

Always

### Bug description

Applets settings window width is reduced to 800 px when you start it in a 800 x 600 screen:

![255810665-0320e64e-eeff-42e7-9fe2-d42e415e2c0a](https://github.com/linuxmint/cinnamon/assets/3955499/9a18eddf-19b1-4811-bbcc-5bd18d6330b9)

And it can even be reduced to less than 800 px:

![255811243-71ca1abd-a128-410e-ba8f-b57e586bbbf9](https://github.com/linuxmint/cinnamon/assets/3955499/7af8058c-48b2-4cd7-a88c-4f61be6733d0)

But as soon as you click on one of the two buttons in the title-bar (Télécharger and Gérer), the width can't be reduced anymore. So, the width can be reduced at the start and not after:

![255810244-79f5086a-0a0b-4fbb-b03d-d0665d8a8940](https://github.com/linuxmint/cinnamon/assets/3955499/b4221752-68ad-46e3-b376-a4af8ed1a0f1)

### Steps to reproduce

Install Linux Mint Cinnamon 21.2 in french version.

Start Applets settings in a 800 x 600 screen.

You can reduce the width of the window.

Click on "Télécharger" button and after, on "Gérer" button, in the title bar.

You can't reduce anymore the width of the window.

### Expected behavior

The width of the window should be resizable, like at when we start it.

**Comment by leigh123linux** [comment]
It's your PROBLEM if you choose to use to use an unsupported screen resolution.
