### ISSUE TITLE
Cinnamon does not honor gkrellm option "do not include on a taskbar" 

### ISSUE THREAD

**Issue by leigh123linux** [linuxmint/cinnamon#1178]
Bug forwarded from https://bugzilla.redhat.com/show_bug.cgi?id=851994

Description of problem:
Cinnamon does not honnor gkrellm option to not have a button on the taskbar if gkrellm is not of type 'dock' or 'panel'. If gkrellm is of type 'dock' or 'panel', then it won't have a button on the taskbar.

Version-Release number of selected component (if applicable):
cinnamon-1.5.2-6
gkrellm-2.3.5-9.fc17

How reproducible:
Always

Steps to Reproduce:
1. Start cinnamon
2. Start gkrellm and in Configuration > General > Properties, make sure "Set window type to be a dock or panel" is not selected and "Do not include on a taskbar" is selected.
3. Quit and restart gkrellm

Actual results:
A button for gkrellm appears on the taskbar.

Expected results:
No gkrellm button should appear on the taskbar.

**Comment by JosephMcc** [comment]
@leigh123linux is this still relevant?

**Comment by leigh123linux** [comment]
@JosephMcc  It's status is unknown as I don't use gkrellm.
