### ISSUE TITLE
Color picker don't pick any color

### ISSUE THREAD

**Issue by kacperpaczos** [linuxmint/cinnamon#11780]
### Distribution

21.2

### Package version

5.8.4

### Graphics hardware in use

NVIDIA GEFORCE RTX 2050

### Frequency

Always

### Bug description

I can use a color-picker only one times after install on fresh cinnamon session. If i remove an applet and restart system, i can install again this applet and then I can pick new color, but only once.

### Steps to reproduce

Install a color-picker and try use in normal way.

### Expected behavior

It should be work

### Additional information

I think the problem occurred after upgrade JS engine, in cinnamon 5.8.

xssession after add (and use) an applet:
Gjs-Message: 10:30:34.255: JS LOG: [LookingGlass/info] Reloading applet: systray@cinnamon.org/3
Gjs-Message: 10:30:34.257: JS LOG: [LookingGlass/info] Reloading applet: xapp-status@cinnamon.org/4
Gjs-Message: 10:30:34.260: JS LOG: [LookingGlass/info] Reloading applet: notifications@cinnamon.org/5
Gjs-Message: 10:30:34.260: JS LOG: [LookingGlass/info] Reloading applet: printers@cinnamon.org/6
Gjs-Message: 10:30:34.261: JS LOG: [LookingGlass/info] Reloading applet: removable-drives@cinnamon.org/7
Gjs-Message: 10:30:34.261: JS LOG: [LookingGlass/info] Reloading applet: keyboard@cinnamon.org/8
Gjs-Message: 10:30:34.261: JS LOG: [LookingGlass/info] Reloading applet: favorites@cinnamon.org/9
Gjs-Message: 10:30:34.261: JS LOG: [LookingGlass/info] Reloading applet: network@cinnamon.org/10
Gjs-Message: 10:30:34.262: JS LOG: [LookingGlass/info] Reloading applet: sound@cinnamon.org/11
Gjs-Message: 10:30:34.262: JS LOG: [LookingGlass/info] Reloading applet: power@cinnamon.org/12
Gjs-Message: 10:30:34.263: JS LOG: [LookingGlass/info] Reloading applet: calendar@cinnamon.org/13
Gjs-Message: 10:30:34.263: JS LOG: [LookingGlass/info] Reloading applet: cornerbar@cinnamon.org/14
Gjs-Message: 10:30:34.266: JS LOG: [LookingGlass/info] Adding systray: anydesk (22x22px)
Gjs-Message: 10:30:34.287: JS LOG: [LookingGlass/info] Adding systray: anydesk (22x22px)
Gjs-Message: 10:30:34.293: JS LOG: [LookingGlass/info] Adding systray: anydesk (22x22px)
Gjs-Message: 10:30:34.293: JS LOG: [LookingGlass/info] Adding systray: anydesk (22x22px)
Gjs-Message: 10:30:34.296: JS LOG: [LookingGlass/info] Adding systray: anydesk (22x22px)
Gjs-Message: 10:30:34.297: JS LOG: [LookingGlass/info] Adding systray: anydesk (22x22px)
Gjs-Message: 10:30:34.297: JS LOG: [LookingGlass/info] Adding systray: anydesk (22x22px)
Gjs-Message: 10:30:34.297: JS LOG: [LookingGlass/info] Adding systray: anydesk (22x22px)
Gjs-Message: 10:30:34.297: JS LOG: [LookingGlass/info] Adding systray: anydesk (22x22px)
Gjs-Message: 10:30:34.298: JS LOG: [LookingGlass/info] Adding systray: anydesk (22x22px)
Gjs-Message: 10:30:34.298: JS LOG: [LookingGlass/info] Adding systray: anydesk (22x22px)
Gjs-Message: 10:30:34.298: JS LOG: [LookingGlass/info] Adding systray: anydesk (22x22px)
Gjs-Message: 10:30:34.298: JS LOG: [LookingGlass/info] Adding systray: anydesk (22x22px)
Gjs-Message: 10:30:34.298: JS LOG: [LookingGlass/info] Adding systray: anydesk (22x22px)
Gjs-Message: 10:30:34.299: JS LOG: [LookingGlass/info] Adding systray: anydesk (22x22px)
Gjs-Message: 10:30:34.299: JS LOG: [LookingGlass/info] Adding systray: anydesk (22x22px)
Gjs-Message: 10:30:34.299: JS LOG: [LookingGlass/info] Adding systray: anydesk (22x22px)
Gjs-Message: 10:30:34.299: JS LOG: [LookingGlass/info] Adding systray: anydesk (22x22px)
Gjs-Message: 10:30:34.299: JS LOG: [LookingGlass/info] Adding systray: anydesk (22x22px)
Gjs-Message: 10:30:34.299: JS LOG: [LookingGlass/info] Adding systray: anydesk (22x22px)
Gjs-Message: 10:30:34.300: JS LOG: [LookingGlass/info] Adding systray: anydesk (22x22px)
Gjs-Message: 10:30:34.300: JS LOG: [LookingGlass/info] Adding systray: anydesk (22x22px)
Gjs-Message: 10:30:34.300: JS LOG: [LookingGlass/info] Adding systray: anydesk (22x22px)
Gjs-Message: 10:30:34.309: JS LOG: [LookingGlass/info] Adding systray: anydesk (22x22px)
Gjs-Message: 10:30:34.309: JS LOG: [LookingGlass/info] Adding systray: anydesk (22x22px)
Gjs-Message: 10:30:34.338: JS LOG: calendar@cinnamon.org: Calendar events supported.
Gjs-Message: 10:30:34.344: JS LOG: Unknown network device type, is 14

** (csd-power:2147): CRITICAL **: 10:30:34.344: abs_to_percentage: assertion 'max > min' failed
Gjs-Message: 10:30:34.347: JS LOG: Unknown network device type, is 13
Gjs-Message: 10:30:34.349: JS LOG: [LookingGlass/info] Hiding XAppStatusIcon (we have an applet): nm-applet
Gjs-Message: 10:30:34.349: JS LOG: [LookingGlass/info] Adding XAppStatusIcon: nvidia-prime (:1.51/org/x/StatusIcon/Icon)
Gjs-Message: 10:30:34.351: JS LOG: [LookingGlass/info] Adding XAppStatusIcon: mintUpdate.py (:1.92/org/x/StatusIcon/Icon)
Gjs-Message: 10:30:34.352: JS LOG: [LookingGlass/info] Adding XAppStatusIcon: mintreport (:1.97/org/x/StatusIcon/Icon)
Gjs-Message: 10:30:34.354: JS LOG: [LookingGlass/info] Adding XAppStatusIcon: process-monitor (:1.97/org/x/StatusIcon/Icon_1)
Gjs-Message: 10:30:34.356: JS LOG: [LookingGlass/info] Adding XAppStatusIcon: jetbrains toolbox (:1.43/org/x/StatusIcon/Icon_2)
Gjs-Message: 10:30:34.359: JS LOG: [LookingGlass/info] Adding XAppStatusIcon: blueman (:1.43/org/x/StatusIcon/Icon)
Gjs-Message: 10:30:34.361: JS LOG: [LookingGlass/info] Adding XAppStatusIcon: keybase (:1.43/org/x/StatusIcon/Icon_1)

**Comment by kacperpaczos** [comment]
@icarter09

**Comment by mtwebster** [comment]
What program are you using as a color picker?

**Comment by fredcw** [comment]
@mtwebster Color Picker applet (color-picker@fmete) I'm guessing. Seems to be working ok for me (Cinnamon 5.8.4)

**Comment by mtwebster** [comment]
If this is an issue with an applet, a bug should be opened in cinnamon-spices-applets.

If it's with an actual application (like gimp or a Flatpak application), there's a bug in xdg-desktop-portal and some missing functionality in Cinnamon that's causing it.

**Comment by kacperpaczos** [comment]
Ok
