### ISSUE TITLE
No homogeinity in minimal width of Cinnamon windows

### ISSUE THREAD

**Issue by InfoLibre** [linuxmint/cinnamon#11785]
### Distribution

Linux Mint 21.2

### Package version

5.8.4

### Frequency

Always

### Bug description

Applet Settings, Desklet Settings, and Cinnamon Extensions are similar applications but have different minimal window width:

![255611569-fce13d6d-96b8-4e4a-96eb-c6f43c5228be](https://github.com/linuxmint/cinnamon/assets/3955499/a7776979-ba84-4ab8-b1b7-5a4e536ec415)

It would be more logical to have homogeneity. There doesn't seem to be rules for window width in Cinnamon and sometimes the results are weird. The worst example is Meteo Cinnamon applet. Its width can't be less than 1044 px, it doesn't even fit into a 1204 x 768 screen:

![plus de 800 pixels de large](https://github.com/linuxmint/cinnamon/assets/3955499/13ead1e9-1862-46cf-b9c7-24baf7cab53c)

### Steps to reproduce

Open different Cinnamon Windows and look at their minimal width.

### Expected behavior

An homogeneity should be visible in all the Cinnamon windows, with minima like 800 or 1024.

**Comment by mtwebster** [comment]
What language is the weather applet settings? In Italian the window starts at about 800x600 and can even be shrunk slightly. It maximizes fine also:

![image](https://github.com/linuxmint/cinnamon/assets/262776/bc4a6650-34d5-487b-889f-9aa36dc3137e)

I'm not sure what's affecting you specifically to cause that oversized window.

**Comment by InfoLibre** [comment]
I'm using french version.

**Comment by JosephMcc** [comment]
So the original problem you opened this for isn't actually an issue. The Applets, Desklets, and Extensions can scale down to different sizes because the contents of each are different. The descriptions shown for the applets are word wrapped but the actual applet name isn't (the somecoolname@mycoolemail.org part). Nor should that part be. The hoops we would have to jump through to make all these have the same min width in all possible cases isn't worth it for a non issue.

**Comment by InfoLibre** [comment]
@JosephMcc I disagree with you, there's something wrong in the french version of Applet settings window. Applets settings window width is reduced to 800 px when you start it in a 800 x 600 screen:

![Capture d’écran du 2023-07-25 08-28-40](https://github.com/linuxmint/cinnamon/assets/3955499/bb7106bf-7fe1-4c55-8571-5cd2bfa33b9c)

But as soon as you click on one of the two buttons (Télécharger and Gérer), the width can't be reduced anymore. So, the width can be reduced at the start and not after:

![Capture d’écran du 2023-07-25 08-32-01](https://github.com/linuxmint/cinnamon/assets/3955499/79f5086a-0a0b-4fbb-b03d-d0665d8a8940)
