### ISSUE TITLE
Impossible to change the size of some windows or window width can't be 800px

### ISSUE THREAD

**Issue by InfoLibre** [linuxmint/cinnamon#11781]
### Distribution

Linux Mint 21.2

### Package version

5.8.4

### Frequency

Always

### Bug description

1) At the top of some windows, there's no icon to set the window to full screen:

![pas de bouton plein écran](https://github.com/linuxmint/cinnamon/assets/3955499/8dc37e6e-4c40-4971-be96-1b2f846a41b5)

![pas de bouton plien  cran](https://github.com/linuxmint/cinnamon/assets/3955499/f8e4c513-6257-4a5b-b4e4-3c36fa0b3389)

2) On a 800x600 screen, it's impossible to set the **Applet settings** window to full screen, the window remain larger than 800px when you click on button "Télécharger" at the top of the window (but not when you click on button "Gérer"):
You don't have this problem with **Desklet settings** window and with **Cinnamon extensions** windows, that are similar with **Applet settings** window.

### Steps to reproduce

Open menu Settings - Applets, click on buttons at the top of the window and put the window at full size, on a 800x600 screen.

### Expected behavior

Full screen should work

**Comment by claudiux** [comment]
Try to double-click on the titlebar of the window. Also try to move window with Alt+mouse-drag.

**Comment by JosephMcc** [comment]
As noted in another issue minimum supported resolution is 1024x768.

**Comment by InfoLibre** [comment]
Applets settings, Desklets settings and Cinnamon extensions are similar applications but their window minimal width is different. It would More logical to have an homogeneity.

![Capture d’écran du 2023-07-24 15-53-31](https://github.com/linuxmint/cinnamon/assets/3955499/fce13d6d-96b8-4e4a-96eb-c6f43c5228be)
