### ISSUE TITLE
Network Manager MFA Request broken

### ISSUE THREAD

**Issue by aldenpark** [linuxmint/cinnamon#11798]
### Distribution

Mint 21.1

### Package version

Cinnamon 5.6.8

### Graphics hardware in use

GeForce GTX 1660 Ti

### Frequency

Always

### Bug description

A recent update broke the dialog box allowing user input when a challenge-response would return when connecting to a VPN that requires an MFA. In the case of Okta you need to specify which option you wish to use for your challenge.  The message about the challenge still appears, but there is no box and button to return what method to use since the update.

### Steps to reproduce

Connect to VPN
enter a correct username and password
Select challenge is returned with no way to respond

### Expected behavior

An input box and button use to appear so I could enter my choice for the MFA option I wished to use.

### Additional information

The update that broke this was applied in the past seven days, because it was a holiday weekend I only noticed the issue this past Tuesday on the 25th.

**Comment by leigh123linux** [comment]
This isn't a cinnamon issue, please file it at https://github.com/linuxmint/linuxmint/issues
