### ISSUE TITLE
Incorrect window handling on bitwig with VST plugins

### ISSUE THREAD

**Issue by paranoidi** [linuxmint/cinnamon#11807]
### Distribution

Mint 20.3 Cinnamon

### Package version

Cinnamon 5.2.7

### Graphics hardware in use

NVIDIA GeForce RTX 2070 SUPER

### Frequency

Always

### Bug description

Cinnamon does something weird with window focusing that is causing issues with Bitwig 5.0.4. When ever closing any kind of menu and main application should be focused all external 3rd party plugins instances (VSTs) are brought into forward (as modal windows) and they must be closed individually. I have verified that this is not happening on other Linux distributions from Bitwig discord linux channel.

### Steps to reproduce

1. Install bitwig (demo mode or trial should work fine).
2. Install vitality VST (free).
3. Open new project
4. Create track(s) with the VST
5. Open any menu such as Quantize configuration (Alt-Q). Or keyboard shortcut help (Ctrl-Enter). 

Example of the issue can be seen in the following screen recording: [here](https://www.dropbox.com/scl/fi/x9isc6dxc3el9unc8luhx/cinnamon-bitwig.mkv?dl=0&rlkey=emrymqtsvg91neucjevu0e6o1)

### Expected behavior

VST plugins windows should remain minimized.

### Additional information

If necessary I am willing to testing help, more detailed instructions how to use bitwig or anything really to get this resolved. I am on mint discord too.

**Comment by leigh123linux** [comment]
Does the issue occur with a supported cinnamon version?

**Comment by paranoidi** [comment]
I made full disk image and tested by upgrading mint and installing MATE as well. It seems like this is the way it works when minimizing VSTs since it works exactly the same with MATE. Simply closing the VST window instead of minimizing works a lot better. Closing the ticket.
