### ISSUE TITLE
A Power Management option is on Screensaver settings instead of being in Power Management settings

### ISSUE THREAD

**Issue by InfoLibre** [linuxmint/cinnamon#11804]
### Distribution

Linux Mint 21.2

### Package version

Cinnamon 5.8.4

### Frequency

Always

### Bug description

In Screensaver settings, one can "Lock the computer when put to sleep". It's a Power Management option, not a Screensaver option. It would be more logical to move it from Screensaver settings to  Power Management settings:

![Capture d’écran du 2023-08-02 12-04-24](https://github.com/linuxmint/cinnamon/assets/3955499/fd7a3733-d1ed-47bc-a4a5-b906fb73e725)

### Steps to reproduce

Open LM menu "Preferences - Screensaver".

### Expected behavior

"Lock the computer when put to sleep" option should be in Power Management settings, not in Screensaver settings.

**Comment by leigh123linux** [comment]
Feature requests are no longer accepted here, please use https://github.com/orgs/linuxmint/discussions instead.
