### ISSUE TITLE
no menu open animation

### ISSUE THREAD

**Issue by Quantum-mutnauQ** [linuxmint/cinnamon#11802]
### Distribution

Cinnamon 21.2

### Package version

5.8.4

### Frequency

Always

### Bug description

Normally there is an animation when I open the menu but on the main menu (starting apps) isn't an animation. In the reason of that there is an small delay. In the delay normally it showing the animation of the opening.

### Steps to reproduce

·open the main menu(starting apps)

### Expected behavior

The menu shows but with out animation and with an short delay.

### Additional information

It would be nice if you tern on the animation. I thin the animation function doesn't call or an number have to change.

**Comment by Secret-chest** [comment]
You can enable it, right-click the menu and select preferences

**Comment by Quantum-mutnauQ** [comment]
I sew there is an option for the animation and are off but I never thernt off the option
