### ISSUE TITLE
Still yellow tooltips in a specific program

### ISSUE THREAD

**Issue by Mintulix** [linuxmint/cinnamon#11813]
### Distribution

Mint 21.2

### Package version

5.8.4

### Graphics hardware in use

Intel Corporation CoffeeLake-H GT2 / UHD Graphics 630

### Frequency

Always

### Bug description

At least one of my programs still shows the "old" yellow tooltips.
The problem is, when using a light theme, the characters also have a light color (white I think) and you can't recognize them. With a dark theme it looks better.

### Steps to reproduce

Install tipp10 from the standard repositories (10 finger typing learn program) and start it. In the lesson overview move the mouse over any lesson and it shows a tooltip. If you change the theme to dark or light, you have to start tipp10 again to see the effect.
Screenshots with mint-y-dark-red and mint-y-red:
![tooltip dark theme](https://github.com/linuxmint/cinnamon/assets/9968138/c6d1c954-9165-4b34-ba36-cce63490c62c)
![tooltip light theme](https://github.com/linuxmint/cinnamon/assets/9968138/dd37ffc0-2baf-4b70-91e8-eab04223725c)

### Expected behavior

I don't know if this is the only one program where this happens, and it's no problem at all that there are still the yellow tooltips, but the text in it should always be visible.

**Comment by mtwebster** [comment]
This seems to be the only program that uses the same libraries that does this - the rest follow the current theme.

As a workaround you can run 'Qt5 Settings' from the menu, and choose a different theme than 'gtk2', then click Apply. This should make the text legible (though the background will still be yellow).

**Comment by Mintulix** [comment]
@mtwebster  Great, for me this is fixed.
Thanks, Michael
