### ISSUE TITLE
Video thumbnails not generating on local network folders on File Managers - Nemo / Nautilius

### ISSUE THREAD

**Issue by ozchobie** [linuxmint/cinnamon#11818]
### Distribution

Mint 21.2

### Package version

5.8.4

### Graphics hardware in use

Nvidia RTX 3060

### Frequency

Always

### Bug description

Video thumbnails wouldn't generate on any file managers located on my local nas. Photos load fine and the video files open with no issues.

### Steps to reproduce

Loading up a folder located on my local nas that includes video files just shows the generic video icon and will not load a thumbnail regardless of the views and preview settings I have tried on both Nemo and Nautilius. Image thumbnails load fine.

### Expected behavior

This should generate video thumbnails similar to how it successfully generates them on files on the local disk. This problem only occurs on network folders.

### Additional information

I have also made sure Nemo settings show image thumbnails applied to all files and not only local files. Changed **Show Thumbnails: YES** and kept **Only for files smaller than 64gb.** No files that I am attempting to load on the file manager is bigger than 1gb by the way.

Tried the similar settings on Nautilius and also would not generate video thumbnails.

I also made sure  ffmpegthumbnailer and ffmpegthumbs are installed and I have cleared the thumbnail cache, rebooted and tried to load the folder containing the video files.

**SOLUTION FOUND**
I did manage to find a solution online [from this reddit post](https://www.reddit.com/r/pop_os/comments/ul7nua/thumbnails_for_mp4_files_not_showing_ive_found/) I had to run the second command twice to fully load the video thumbnails as running it once did not load other video thumbnails still. Now ALL my video files have generated thumbnails successfully.

Can this fix be integrated in Cinnamon?

From Reddit:
 

> Install this package (which should have come with Pop in the first place to make sure all thumbnails work, IMHO)
> 
>` sudo apt install gstreamer1.0-libav`

> Then clean up your thumbnail directory, specifically the failed thumbnails folder, with this command.
> 
> `rm -r ~/.cache/thumbnails/fail`
> 
> Then go to your video folder and the thumbnails should show up for all files. That's it!

**Comment by leigh123linux** [comment]
Duplicate of https://github.com/linuxmint/nemo/issues/2979

**Comment by ozchobie** [comment]
Edit: It only fixed it temporarily. The problem occured again after reboot. Running the codes again on terminal doesn't fully generate the video thumbnails anymore.

Also, it is not nemo-specific as it also fails on Nautilius.

**Comment by mtwebster** [comment]
Should be fixed by https://github.com/linuxmint/nemo/pull/3265
