### ISSUE TITLE
Bug with tooltip color in qt apps on 21.2 cinnamon dark themes

### ISSUE THREAD

**Issue by mirocw** [linuxmint/cinnamon#11820]
### Distribution

Cinnamon 21.2

### Package version

5.8.4

### Graphics hardware in use

AMD Ryzen 5 5600H with Radeon Graphics

### Frequency

Always

### Bug description

There's a bug in Cinnamon 21.2 edition on a tooltip background accent color, and only on dark themes with QT apps like keepass and other QT apps, the light themes are ok. On dark themes the background color is always yellow, while on light themes it follows it.

### Steps to reproduce

Install some of the QT apps like KeepassXC, have one of the dark themes and hover with mouse over some of the icons on a QT apps. The background of the tooltip, will be yellow and do not follow accent color of a theme. If you switch to some of the light cinnamon themes, the tooltip background color follows accent color theme

### Expected behavior

tooltip background color should follow accent color theme

**Comment by mirocw** [comment]
![dark](https://github.com/linuxmint/cinnamon/assets/107131525/f3c03659-8f68-45c9-b5ec-a7edcbb7223c)
![light](https://github.com/linuxmint/cinnamon/assets/107131525/60b94f1e-d769-4c6a-baa1-886968e1b5f8)

**Comment by mirocw** [comment]
This in how tooltip it looks on flatpak QT apps
![flatpak-dark](https://github.com/linuxmint/cinnamon/assets/107131525/6ddde88e-dc25-41ae-bf42-1eaa9acdb707)
![flatpak-light](https://github.com/linuxmint/cinnamon/assets/107131525/f40f08ea-a54c-4fe5-b243-492dfc7158e0)

**Comment by matkuki** [comment]
Probably the same issue: PyQt6 apps also do not respect stylesheets for QTooltips,
here is an example of a PyQt6 application with tooltips with white font on a black background:
![image](https://github.com/linuxmint/cinnamon/assets/10289651/be9a4ac0-9e21-4158-b244-6f156570fec3)
The tooltip font color should be white, but it's always black.

The background color however can be changed, for example: setting the stylesheet to a red background with yellow font:
![image](https://github.com/linuxmint/cinnamon/assets/10289651/2acbb15f-fd3a-4114-99e6-8b82995069ec)

**Comment by matkuki** [comment]
Confirming that if in the PyQt6 app the default tooltips are used (no stylesheet for tooltips), the problem is exactly the same as @mirocw mentioned in https://github.com/linuxmint/cinnamon/issues/11820#issuecomment-1672956710!

**Comment by leigh123linux** [comment]
This isn't a cinnamon issue, it's a qt issue.
Are the qgnomeplatform-qt5 and qgnomeplatform-qt6 packages installed.

**Comment by mirocw** [comment]
> This isn't a cinnamon issue, it's a qt issue. Are the qgnomeplatform-qt5 and qgnomeplatform-qt6 packages installed.

you're talking about flatpak apps or package apps?
My first picture of KeepasXC is package app. Also i can't find qgnomeplatform-qt5 and qgnomeplatform-qt6 as packages
