### ISSUE TITLE
[Feature Request] Bring back the old Green color to Mint-Y

### ISSUE THREAD

**Issue by sun95n** [linuxmint/cinnamon#11833]
Hi! I really miss the classic Mint-Y green color:

![osc](https://github.com/linuxmint/cinnamon/assets/120290802/bbdc65e4-5861-400d-9b21-d900cc2744ab)

Is it possible to include it along with the new color options?

![oscd](https://github.com/linuxmint/cinnamon/assets/120290802/c9af0cfc-31cf-43eb-80c7-6b87d0b2f458)

Thanks <3

**Comment by leigh123linux** [comment]
Feature requests are no longer accepted here, please use https://github.com/orgs/linuxmint/discussions instead.
