### ISSUE TITLE
The shutdown button in start menu is missing

### ISSUE THREAD

**Issue by prontok** [linuxmint/cinnamon#11832]
### Distribution

MInt 21.2

### Package version

Cinnamon 5.8.4

### Frequency

Always

### Bug description

Hello,
The shutdown button in start menu is missing

![v3bbdEE](https://github.com/linuxmint/cinnamon/assets/90829636/93cf81a3-7f53-45a0-a838-9f6d50911b95)

### Steps to reproduce

Please push the start menu

### Expected behavior

-

**Comment by leigh123linux** [comment]
It works fine here.

![image](https://github.com/linuxmint/cinnamon/assets/1299302/07afa339-98d2-4619-98a0-3b8235e3dea6)

Can you provide the full system info.

**Comment by prontok** [comment]
Hello,
The problem was fixed by updating the files from the /ets/skel directory with another files from Linux Mint operating system
