### ISSUE TITLE
USB key creator: wrong french translation

### ISSUE THREAD

**Issue by InfoLibre** [linuxmint/cinnamon#11837]
### Distribution

Mint 21.2

### Package version

Cinnamon 5.8.4

### Frequency

Always

### Bug description

Wrong french translation, should write **Souhaitez-vous** instead of **Souhaîtez-vous**:

![Créateur de clé USB_6](https://github.com/linuxmint/cinnamon/assets/3955499/69ba3add-6b3c-4a23-906d-d1a52141dccb)

### Steps to reproduce

Start USB key creator. Choose an ISO file and write it on an USB key. Before starting writing, an advertisement message appears, with the wrong translation into it.

### Expected behavior

**Souhaitez-vous** instead of **Souhaîtez-vous**:

**Comment by leigh123linux** [comment]
File the issue against the app.

https://github.com/linuxmint/mintstick/issues
