### ISSUE TITLE
linut mint, debian, improvements & ideas

### ISSUE THREAD

**Issue by birtisen** [linuxmint/cinnamon#11848]
### Distribution

lmde5

### Package version

-

### Frequency

Always

### Bug description

few things to see & check, about LMDE5, hope it would be changed/updated in the LMDE6..

### Steps to reproduce

few things to see & check, about LMDE5, hope it would be changed/updated in the LMDE6..

### Expected behavior

few things to see & check, about LMDE5, hope it would be changed/updated in the LMDE6..

### Additional information

[ideas-lmdeB.pdf](https://github.com/linuxmint/cinnamon/files/12543038/ideas-lmdeB.pdf)

**Comment by anaximeno** [comment]
The discussion section is more appropriate than here for this. Also LMDE 6 is in QA testing for the release so new features probably won't be added, at least just yet.

**Comment by Secret-chest** [comment]
These are all good ideas, but you should separate them.

**Comment by leigh123linux** [comment]
Feature requests are no longer accepted here, please use https://github.com/orgs/linuxmint/discussions instead.

**Comment by anaximeno** [comment]
He seems to have created it at https://github.com/orgs/linuxmint/discussions/147

**Comment by birtisen** [comment]
> Feature requests are no longer accepted here, please use https://github.com/orgs/linuxmint/discussions instead.

done :)

**Comment by birtisen** [comment]
> These are all good ideas, but you should separate them.

Im afraid just "one per one" idea would get their interest a bit lost..

**Comment by birtisen** [comment]
> The discussion section is more appropriate than here for this. Also LMDE 6 is in QA testing for the release so new features probably won't be added, at least just yet.

hope a patch would come soon, especially for up/down arrows, whom still miss since few years for lot of linuxies users..
