### ISSUE TITLE
Cinnamon crash to fallback mode every single bootup

### ISSUE THREAD

**Issue by Nightwing0815** [linuxmint/cinnamon#11858]
### Distribution

Mint 21.2

### Package version

5.8.4

### Graphics hardware in use

Intel TigerLake-LP GT2 [Iris Xe Graphics]

### Frequency

Always

### Bug description

Sine the middle of may (with version 21.1 vera), every time I start up my laptop, cinnamon session crashes to the fallback mode, and I can#t get rid of it. The only solution is to change permanently to the alternate cinnamon session, which is suggested in login prompt.
I'll attach the locale-files from sysreport and the stacetrack etc from [pastebin](https://pastebin.com/6yUaqaeW).

Thanks in advance,

ToM

[localfiles.zip](https://github.com/linuxmint/cinnamon/files/12601123/localfiles.zip)

### Steps to reproduce

Just boot and login

### Expected behavior

Working normally

### Additional information

I have an old timeshift backup from the 7th of may, with linuxmint 21.1: I can do a restore, and bootup only direct after the restore, this is the only way, to get cinnamon working in a normal behaviour. After that ONE bootup, it'll mess up, like mentioned above...

**Comment by ach5948** [comment]
I'm seeing the same thing since upgrading cinnamon, also on intel integrated graphics (Intel UHD Graphics 620).
[pastebin stacktrace](https://pastebin.com/S4ebKPe8)
[crash.tar.gz](https://github.com/linuxmint/cinnamon/files/12743544/crash.tar.gz)

**Comment by Nightwing0815** [comment]
Today, I had time to research and I've got a solution:

Go to file (or create one): /etc/X11/xorg.conf.d/20-intel-gpu.conf and you have to put the dri part in it, works now with the usual cinnamon session.

```
Section "Device"
    Identifier          "Intel Graphics"
    Driver              "intel"
    Option "DRI"        "iris"
    Option "TearFree"   "true"
EndSection
```

ToM
