### ISSUE TITLE
Opacity settings do not work

### ISSUE THREAD

**Issue by awsms** [linuxmint/cinnamon#11852]
### Distribution

EndeavourOS (6.4.12-arch1-1)

### Package version

5.8.4

### Frequency

Always

### Bug description

The opacity options do not work for me. I was a Mint user before and I remember it worked fine there, however it has never worked since I'm using another distro.

![Screenshot from 2023-09-08 15-24-56](https://github.com/linuxmint/cinnamon/assets/48278661/f32e7999-1034-4eaa-9a96-d8638bc0f4c7)

### Steps to reproduce

1. Set a keybind for "Increase opacity"/"Decrease opacity" in the Keyboard menu
2. Press the keybind

### Expected behavior

Increase/decrease the opacity of a window when the keybind is pressed.

**Comment by suzeanne** [comment]
This is affecting me on Linux Mint installs of multiple machines. 

I am using Linux Mint 21.2 Cinnamon.

Cinnamon is 5.8.4.

I have used this keyboard shortcut every day, many times per hour, for at least a decade, without issue, on prior versions of Linux Mint.

**Comment by awsms** [comment]
thanks for confirming this also affects the cinnamon build provided with Linux Mint, I thought I might have messed up with my configfiles. I've also been using this feature for years now without issue.
