### ISSUE TITLE
Printer will not work on Mint  21

### ISSUE THREAD

**Issue by sid15999** [linuxmint/cinnamon#11855]
### Distribution

Mint 21

### Package version

5.4.12

### Frequency

Always

### Bug description

Upgraded from Mint 20 to Mint 21. Printer will not work.

### Steps to reproduce

Hit the print button

### Expected behavior

Print

### Additional information

Printer work but then stopped.

**Comment by leigh123linux** [comment]
File the issue at https://github.com/linuxmint/linuxmint/issues
