### ISSUE TITLE
When you want to enable Gestures, the switch is stretched and distorted

### ISSUE THREAD

**Issue by Futhark1988** [linuxmint/cinnamon#11854]
### Distribution

Linux Mint 21.2 Cinnamon

### Package version

Cinnamon 5.8.4

### Graphics hardware in use

Intel© Core™ i7-4720HQ CPU @ 2.60GHz × 4

### Frequency

Always

### Bug description

When you want to enable Gestures, the switch is stretched and distorted.

![image](https://github.com/linuxmint/cinnamon/assets/12551657/505bc243-284a-4f3b-8e16-7f764874ad81)

### Steps to reproduce

Open Gestures (if already enabled, ust disable it)

### Expected behavior

The switch should look "normal"

**Comment by mtwebster** [comment]
What theme is this (Gtk/application)?

**Comment by Futhark1988** [comment]
Thank you for the excellent question! I didn think it's themes related.
The switch looks fine if Themes -> Applications is set to anything that starts with "Mint" and only looks weird with the three that others: Adwaita, Adwaita-Dark and HighContrast

**Comment by JosephMcc** [comment]
I just tested this with Adwaita on git master and it seems fine now.
