### ISSUE TITLE
'external-configuration-app' doesn't work with Extension

### ISSUE THREAD

**Issue by TobiZog** [linuxmint/cinnamon#11885]
### Distribution

Linux Mint 22.2

### Package version

5.8.4

### Frequency

Always

### Bug description

I want to create an Cinnamon Spices Extension. The user should see a custom GTK window on the cog symbol in the Extensions window.

![image](https://github.com/linuxmint/cinnamon/assets/67568441/954e25b7-b984-4655-914e-29265a9872a2)

So, I created for first test purposes an simple app. Structure:
test@test/
  |--extension.js
  |--icon.png
  |--metadata.json
  |--prefs.py

**extension.js**
```
let extension;

const Util = imports.misc.util;

function TestExtension(uuid) {
	this._init(uuid);
}

TestExtension.prototype = {
	_init: function(uuid) {
		
	}
}

function init(extensionMeta) {
	extension = new TestExtension(extensionMeta.uuid)
}

function enable() {
	return extension;
}

function disable() {
	// todo
}
```

**metadata.json**
```
{
    "external-configuration-app": "prefs.py",
    "uuid": "test@test",
    "name": "Test",
    "description": "123",
    "version": "1",
    "max-instances": 1,
    "cinnamon-version": [
        "4.8",
        "5.0",
        "5.2",
        "5.4",
        "5.6",
        "5.8"
    ],
    "author": "",
}
```

**prefs.py**
```
import sys, gi

gi.require_version("Gtk", "3.0")
from gi.repository import GLib, Gtk


class MyApplication(Gtk.Application):
    def __init__(self):
        super().__init__(application_id="com.example.MyGtkApplication")
        GLib.set_application_name("My Gtk Application")

    def do_activate(self):
        window = Gtk.ApplicationWindow(application=self, title="Hello World")
        window.present()


app = MyApplication()
exit_status = app.run(sys.argv)
sys.exit(exit_status)
```

But in the end, the window doesn't appear. I've get also no error message in Melange.

### Steps to reproduce

1. Creating the files in the test folder
2. Active the test extension
3. Click on the config cog icon

### Expected behavior

Click on the cog symbol should open the prefs.py window.

**Comment by mtwebster** [comment]
Is prefs.py executable?

**Comment by TobiZog** [comment]
> Is prefs.py executable?

I've changed it to be executable, but this doesn't changed the behavior.

**Comment by mtwebster** [comment]
Is that the entirety of prefs.py?

It needs to have a shebang on the first line:
```
#!/usr/bin/python3
```

Are  there any errors or warnings printed out if you run cinnamon-settings from a terminal?

**Comment by TobiZog** [comment]
> It needs to have a shebang on the first line:
> 
> ```
> #!/usr/bin/python3
> ```

That's it! Thank you very much.
Could you please add this to the documentation (https://projects.linuxmint.com/reference/git/cinnamon-tutorials/xlet-settings-ref.html)?
