### ISSUE TITLE
high CPU load on a lenovo T14 intel HD video and Linux Mint 21.2 (mint has no problem)

### ISSUE THREAD

**Issue by olisnr** [linuxmint/cinnamon#11887]
### Distribution

Linux Mint 21.2

### Package version

5.8.4

### Graphics hardware in use

  Device-1: Intel CometLake-U GT2 [UHD Graphics] vendor: Lenovo driver: i915 v: kernel ports:     active: eDP-1 empty: DP-1, DP-2, HDMI-A-1, HDMI-A-2 bus-ID: 00:02.0 chip-ID: 8086:9b41   Device-2: IMC Networks Integrated Camera type: USB driver: uvcvideo bus-ID: 1-8:3     chip-ID: 13d3:5406

### Frequency

Always

### Bug description

if i start mint and cinnamon on the i7 CPU uses 25% the hole time, and at playing youtube-videos on an external 4k monitor the CPU load is 100%.
also refresh rate on simple CAD-programs are bad. and all this things go away if i use the mate desktop.

where should i start to search the problem? in the logs i see nothing special.

### Steps to reproduce

dont know, on all other computer i use its working great.

### Expected behavior

the cinnamon process should use <2% CPU time in idle

### Additional information

may be its some kind of HW problem induced SW problem. the laptop has also problems to come out of the sleep mode. and this in 2 different linux versions and also windows.

**Comment by olisnr** [comment]
with mint has no probelm i mean  mint and the mate-desktop works perfect

**Comment by mtwebster** [comment]
Can you go to cinnamon settings ->System Info, and 'Upload system information', or copy/paste here.

**Comment by olisnr** [comment]
System:
  Kernel: 6.2.0-34-generic x86_64 bits: 64 compiler: N/A Desktop: Cinnamon 5.8.4 tk: GTK 3.24.33
    wm: muffin dm: LightDM Distro: Linux Mint 21.2 Victoria base: Ubuntu 22.04 jammy
Machine:
  Type: Laptop System: LENOVO product: 20S0000NMZ v: ThinkPad T14 Gen 1
    serial: <superuser required> Chassis: type: 10 serial: <superuser required>
  Mobo: LENOVO model: 20S0000NMZ v: SDK0J40697 WIN serial: <superuser required> UEFI: LENOVO
    v: N2XET39W (1.29 ) date: 07/25/2023
Battery:
  ID-1: BAT0 charge: 44.8 Wh (100.0%) condition: 44.8/50.5 Wh (88.8%) volts: 12.9 min: 11.5
    model: SMP 5B10W13906 serial: <filter> status: Full
CPU:
  Info: quad core model: Intel Core i7-10510U bits: 64 type: MT MCP arch: Comet/Whiskey Lake
    note: check rev: C cache: L1: 256 KiB L2: 1024 KiB L3: 8 MiB
  Speed (MHz): avg: 1700 high: 2300 min/max: 400/4900 cores: 1: 2300 2: 2300 3: 700 4: 700
    5: 700 6: 2300 7: 2300 8: 2300 bogomips: 36799
  Flags: avx avx2 ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx
Graphics:
  Device-1: Intel CometLake-U GT2 [UHD Graphics] vendor: Lenovo driver: i915 v: kernel ports:
    active: eDP-1 empty: DP-1, DP-2, HDMI-A-1, HDMI-A-2 bus-ID: 00:02.0 chip-ID: 8086:9b41
  Device-2: IMC Networks Integrated Camera type: USB driver: uvcvideo bus-ID: 1-8:3
    chip-ID: 13d3:5406
  Display: x11 server: X.Org v: 1.21.1.4 driver: X: loaded: modesetting gpu: i915 display-ID: :0
    screens: 1
  Screen-1: 0 s-res: 1920x1080 s-dpi: 96
  Monitor-1: eDP-1 model: BOE Display res: 1920x1080 dpi: 158 diag: 355mm (14")
  OpenGL: renderer: llvmpipe (LLVM 15.0.7 256 bits) v: 4.5 Mesa 23.2.1 - kisak-mesa PPA
    direct render: Yes
Audio:
  Device-1: Intel Comet Lake PCH-LP cAVS vendor: Lenovo driver: sof-audio-pci-intel-cnl
    bus-ID: 00:1f.3 chip-ID: 8086:02c8
  Sound Server-1: ALSA v: k6.2.0-34-generic running: yes
  Sound Server-2: PulseAudio v: 15.99.1 running: yes
  Sound Server-3: PipeWire v: 0.3.48 running: yes
Network:
  Device-1: Intel Comet Lake PCH-LP CNVi WiFi driver: iwlwifi v: kernel bus-ID: 00:14.3
    chip-ID: 8086:02f0
  IF: wlp0s20f3 state: up mac: <filter>
  Device-2: Intel Ethernet I219-V vendor: Lenovo driver: e1000e v: kernel port: N/A
    bus-ID: 00:1f.6 chip-ID: 8086:0d4f
  IF: enp0s31f6 state: down mac: <filter>
  IF-ID-1: docker0 state: down mac: <filter>
Bluetooth:
  Device-1: Intel AX201 Bluetooth type: USB driver: btusb v: 0.8 bus-ID: 1-10:4 chip-ID: 8087:0026
  Report: hciconfig ID: hci0 rfk-id: 1 state: up address: <filter> bt-v: 3.0 lmp-v: 5.2
    sub-v: 237e
Drives:
  Local Storage: total: 1.82 TiB used: 986.48 GiB (53.0%)
  ID-1: /dev/nvme0n1 vendor: Kingston model: SNVS2000G size: 1.82 TiB speed: 31.6 Gb/s lanes: 4
    serial: <filter> temp: 41.9 C
Partition:
  ID-1: / size: 100.69 GiB used: 76.01 GiB (75.5%) fs: ext4 dev: /dev/nvme0n1p5
  ID-2: /boot/efi size: 96 MiB used: 37.7 MiB (39.2%) fs: vfat dev: /dev/nvme0n1p1
Swap:
  Alert: No swap data was found.
Sensors:
  System Temperatures: cpu: 57.0 C mobo: N/A
  Fan Speeds (RPM): N/A
Repos:
  Packages: 3284 note: see --pkg apt: 3264 flatpak: 20
  No active apt repos in: /etc/apt/sources.list
  Active apt repos in: /etc/apt/sources.list.d/additional-repositories.list
    1: deb [arch=amd64] https: //repositories.intel.com/graphics/ubuntu jammy main
  Active apt repos in: /etc/apt/sources.list.d/intel-gpu-jammy.list
    1: deb [arch=amd64,i386 signed-by=/usr/share/keyrings/intel-graphics.gpg] https: //repositories.intel.com/gpu/ubuntu jammy client
  No active apt repos in: /etc/apt/sources.list.d/kicad-kicad-6_0-releases-focal.list
  Active apt repos in: /etc/apt/sources.list.d/kisak-kisak-mesa-jammy.list
    1: deb [signed-by=/etc/apt/keyrings/kisak-kisak-mesa-jammy.gpg] https: //ppa.launchpadcontent.net/kisak/kisak-mesa/ubuntu jammy main
  Active apt repos in: /etc/apt/sources.list.d/official-package-repositories.list
    1: deb https: //mirror.init7.net/linuxmint victoria main upstream import backport
    2: deb http: //mirror.infomaniak.ch/ubuntu jammy main restricted universe multiverse
    3: deb http: //mirror.infomaniak.ch/ubuntu jammy-updates main restricted universe multiverse
    4: deb http: //mirror.infomaniak.ch/ubuntu jammy-backports main restricted universe multiverse
    5: deb http: //security.ubuntu.com/ubuntu/ jammy-security main restricted universe multiverse
  No active apt repos in: /etc/apt/sources.list.d/picoscope7.list
  No active apt repos in: /etc/apt/sources.list.d/qucs-qucs-focal.list
  No active apt repos in: /etc/apt/sources.list.d/spotify.list
Info:
  Processes: 313 Uptime: 1d 1h 27m Memory: 46.71 GiB used: 2.29 GiB (4.9%) Init: systemd v: 249
  runlevel: 5 Compilers: gcc: 11.4.0 alt: 11/12/9 Client: Cinnamon v: 5.8.4 inxi: 3.3.13

**Comment by mtwebster** [comment]
Why the mesa PPA? Please remove it, then "Downgrade foreign packages" in software sources -> Maintenance and reboot.

**Comment by olisnr** [comment]
ppa-purge may be?

**Comment by leigh123linux** [comment]
Your issue isn't a cinnamon bug, you will need to reinstall and avoid the use of untested ppa repos.

**Comment by clefebvre** [comment]
No, it looks like the versions match Jammy.. so that looks correct. What isn't correct are the versions detected from the Ubuntu repository....

it looks like the mirror you're using for the Ubuntu repositories is completely outdated.

Try the following. In mintsources, click Restore the default settings, then update the cache.

Then go back to downgrade packages, and you should see far less than that.

**Comment by clefebvre** [comment]
For instance:

apt in jammy-updates is indeed 2.4.10, not 2.4.8.

It looks like you were pointing to a valid mirror, took updates from it, and then switched to an outdated one (mirror.infomaniak.ch) stuck in the past..

**Comment by olisnr** [comment]
also i tryed:
i did change to the default repositories and downgraded everything. now its even worse, the cinnamon process uses about 50% CPU time.
but i also installed a totally fresh mint-cinnamon on an external HD, and that is working perfect. i only didnt had the time to install all the updates and the other things, so i dont know where the problem was starting.  

i will reinstall my system. 

the reason for installing other intel-video-drivers was, that original drivers had problems with xschem. the later varinats didnt.

**Comment by olisnr** [comment]
only to let You know. i did a new 21.2 installation, and it works perfekt. 

thanky a lot for Your help!
