### ISSUE TITLE
Cinnamon 1.6 desktop black font color

### ISSUE THREAD

**Issue by anothergituser** [linuxmint/Cinnamon#1189]
Linux mint 13 cinnamon 1.6
Popular themes from gnome-look.org like Zukitwo or Adwaita Cupertino that work flawlessly in 1.4 have black font color for desktop icons, no matter what you have in your theme css.

For example, in my theme css, this

.nautilus-desktop.nautilus-canvas-item {
    color: #ffffff;
    text-shadow: 1 1 black;
}

would set the desktop font color to white, works in 1.4 not in 1.6

Strange enough, Mint-X and Mint-Y work as expected, white font color for desktop icons.

Another thing with the black fonts, if you hover over the applets, say the calendar, the tooltip is also black with no background.

**Comment by gabimladin** [comment]
For debian 8 with [cinnamon](https://gist.github.com/gabimladin/070c103236cbd06ca2898ef30bcdc41d)
