### ISSUE TITLE
Searching for a filename while saving a file occasionally overwrites an existing file

### ISSUE THREAD

**Issue by QuickQuant** [linuxmint/cinnamon#11895]
### Distribution

21.2 Cinnamon

### Package version

5.8.4

### Graphics hardware in use

NVIDIA GeForce RTX 2080 Rev. A

### Frequency

Always

### Bug description

with very common user input, you could accidentally overwrite a file very easily, which permanently deletes the original file

### Steps to reproduce

"save as" a file
control + f to search in the folder
start searching for some file name, including a search that contains a space
When pressing the spacebar, it attempts to save the file instead of putting the space in the search dialog!

### Expected behavior

The space should be applied to the search

**Comment by QuickQuant** [comment]
I lost a pretty important file doing this. Looks like theres no way to undo it.

**Comment by QuickQuant** [comment]
Also if you control F and start to search, then press control f again, another search box appears in the lower right. Dunno if this should be a separate bug but looks like this whole search is buggy.

**Comment by JosephMcc** [comment]
The "Save as" dialogs are provided by the toolkit used to build the application. Cinnamon nor Mint have any control over these.

**Comment by JLademan** [comment]
Theres no way, this was a problem for every save document in every app, libreoffice, all browsers, thunderbird, downloading files, like any time I went to save. Is this the same bug in libreoffice and brave save as their own save dialog??
They're all the same kind of save-as functionality, it looks like the file explorer

also when I grab the box and move it around really fast with my mouse while looking at top, cinnamon cpu usage spikes. So its a cinnamon dialog like 90% sure

**Comment by JLademan** [comment]
its still doing it, just try it out on any app

**Comment by leigh123linux** [comment]
@JLademan  Cinnamon draws the whole desktop so moving any app window will cause cinnamon to use the cpu!

**Comment by JLademan** [comment]
alright fair enough
still though, you really think its every program on my computer has this same bug?
If I ever save-as anything it sure seems like the same kind of box. Is this some common library they must all use I can report this bug to? not familiar with how I'd find where to report this thing. Its very consistent.
