### ISSUE TITLE
Random crash at "libgobject-2.0.so"

### ISSUE THREAD

**Issue by RedactedSoftware** [linuxmint/cinnamon#11898]
### Distribution

Fedora 38 (Cinnamon)

### Package version

5.8.4

### Graphics hardware in use

Radeon 680M

### Frequency

Quite often

### Bug description

If the computer is on for long enough, cinnamon will crash (and sometimes recover, but sometimes not) for seemingly no reason.

### Steps to reproduce

- Turn on pc
- Use it
- After a few hours, The display will freeze entirely for ~ 10 seconds and then blackscreen. If the audio stops, it won't come back. If it doesn't. Then it usually will and you can continue as normally.

### Expected behavior

- Not randomly crashing

### Additional information

My first thought was that crashing for no reason is sometimes caused by memory errors, I ran a memory test and it passed.

The crash seems to be a segfault in "libgobject-2.0.so" at "g_type_check_instance_is_fundamentally_a()"
A gist to the stacktrace / crash log can be found [here](https://gist.github.com/RedactedSoftware/ee6682691965c7774316a2cc5b2ceaf0)

The PC I am using is a mini pc with the "7735HS" SOC. Which includes the "Radeon 680M" Integrated Graphics.

**Comment by leigh123linux** [comment]
Reported @redhat bugzilla.

https://bugzilla.redhat.com/show_bug.cgi?id=2235025


No crashes here.

```
$ inxi -S
System:
  Host: mpd-pc Kernel: 6.5.7-300.fc39.x86_64 arch: x86_64 bits: 64
    Desktop: Cinnamon v: 5.8.4 Distro: Fedora release 39 (Thirty Nine)
```

```
$ uptime
 16:43:21 up 6 days,  3:51,  1 user,  load average: 0.36, 0.52, 0.53
```

previous uptime was 18 days, I rebooted for a kernel update

**Comment by RedactedSoftware** [comment]
Hello again, This crash is not caused by Cinnamon and is being tracked [here](https://gitlab.freedesktop.org/drm/amd/-/issues/2220) It appears to be a regression in AMDGPU which can be made significantly less likely by adding the following to **GRUB_CMDLINE_LINUX**

`amdgpu.gpu_recovery=1 amdgpu.noretry=0 amdgpu.dcdebugmask=0x10 amdgpu.vm_update_mode=3`

**Comment by JulianGro** [comment]
Are we sure this is AMDGPU related? I am running into an issue with libgobject on Intel and I have been having the same frequency of crashes on Nvidia proprietary. Here is the systemd-coredump output: https://bin.linux.pizza/?8da4bf3a2d89c327#EbkKxU5bnVt3px9ZxVdgKTxc9kCfxoYnXwqBtMwSfu8S
In my case, the issue happens most often when closing a window. Specifically when killing a crashed game.

**Comment by LinuxOnTheDesktop** [comment]
I think that _Timeshift_ is involved in causing the segfault. See [here](https://github.com/search?q=repo%3Alinuxmint%2Ftimeshift+segfault&type=issues).
