### ISSUE TITLE
QtQuick applications with menu bars segfault on exit

### ISSUE THREAD

**Issue by chasonr** [linuxmint/cinnamon#11904]
### Distribution

Mint 21.2

### Package version

5.8.4

### Graphics hardware in use

lspci reports: 00:02.0 VGA compatible controller: Intel Corporation Xeon E3-1200 v3/4th Gen Core Processor Integrated Graphics Controller (rev 06)

### Frequency

Always

### Bug description

Any QtQuick project created with QtCreator, with the main window an ApplicationWindow, containing a MenuBar with at least one Menu item, causes a segfault when closed.

I cannot replicate the error on Ubuntu 22.04.

The stack traceback looks like this:

`#0  0x0000000000000000 in ?? ()`
`#1  0x00007ffff06af96b in ?? () from /lib/x86_64-linux-gnu/libQt5Quick.so.5`
`#2  0x00007ffff06af9dd in ?? () from /lib/x86_64-linux-gnu/libQt5Quick.so.5`
`#3  0x00007ffff0838727 in QAccessibleQuickItem::role() const () from /lib/x86_64-linux-gnu/libQt5Quick.so.5`
`#4  0x00007ffff364e22a in ?? () from /lib/x86_64-linux-gnu/libQt5XcbQpa.so.5`
`#5  0x00007ffff3651098 in ?? () from /lib/x86_64-linux-gnu/libQt5XcbQpa.so.5`
`#6  0x00007ffff3652822 in ?? () from /lib/x86_64-linux-gnu/libQt5XcbQpa.so.5`
`#7  0x00007ffff06bdf0b in QQuickItemPrivate::setEffectiveVisibleRecur(bool) () from /lib/x86_64-linux-gnu/libQt5Quick.so.5`
`#8  0x00007ffff06c6af9 in QQuickItem::setParentItem(QQuickItem*) () from /lib/x86_64-linux-gnu/libQt5Quick.so.5`
`#9  0x00007ffff06c701a in QQuickItem::~QQuickItem() () from /lib/x86_64-linux-gnu/libQt5Quick.so.5`
`#10 0x00007ffff00b2b62 in ?? () from /usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Templates.2/libqtquicktemplates2plugin.so`
`#11 0x00007ffff71bba6e in QObjectPrivate::deleteChildren() () from /lib/x86_64-linux-gnu/libQt5Core.so.5`
`#12 0x00007ffff71c6924 in QObject::~QObject() () from /lib/x86_64-linux-gnu/libQt5Core.so.5`
`#13 0x00007ffff00b2ed2 in ?? () from /usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Templates.2/libqtquicktemplates2plugin.so`
`#14 0x00007ffff71bba6e in QObjectPrivate::deleteChildren() () from /lib/x86_64-linux-gnu/libQt5Core.so.5`
`#15 0x00007ffff71c6924 in QObject::~QObject() () from /lib/x86_64-linux-gnu/libQt5Core.so.5`
`#16 0x00007ffff00b3381 in ?? () from /usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Templates.2/libqtquicktemplates2plugin.so`
`#17 0x00007ffff772a9ce in QQmlApplicationEnginePrivate::cleanUp() () from /lib/x86_64-linux-gnu/libQt5Qml.so.5`
`#18 0x00007ffff772aa1d in QQmlApplicationEngine::~QQmlApplicationEngine() () from /lib/x86_64-linux-gnu/libQt5Qml.so.5`
`#19 0x00005555555554ca in main ()`

### Steps to reproduce

* Start QtCreator.
* Create a new QtQuick project.
* To main.qml, make these changes:
  * Add the line `import QtQuick.Controls 2.15`
  * Change the type of the window to ApplicationWindow
  * Add this property to the window:
`menuBar: MenuBar {`
`    Menu {`
`        title: qsTr("File")`
`        MenuItem {`
`            text: qsTr("Exit")`
`            onTriggered: close()`
`        }`
`    }`
`}`
* Run the program.
* Exit the program by any means.

### Expected behavior

Program exits normally and does not produce a segfault.

**Comment by leigh123linux** [comment]
File the issue against the app.
