### ISSUE TITLE
Skype share screen

### ISSUE THREAD

**Issue by academo** [linuxmint/cinnamon#1190]
Cinnamon version: last commited version from git repository

Currently is not possible share the screen on skype, it does allow to start sharing but other people don't see anything.

Researching I found gnome 3 people already fix the on gnome 3.4

Here is the thread about the fixing:

https://bugzilla.gnome.org/show_bug.cgi?id=677657

**Comment by Tiamarth** [comment]
@fisch246 I'm also seeing this issue with Cinnamon 2.6.13 - a little over a year later. Is this being worked on? Has it been forgotten? It's extremely annoying, in any case.

**Comment by Enelar** [comment]
Not reproducing at F25x64 Ci3.2.1

**Comment by Vahan86** [comment]
@academo, is this still an issue for you in Cinnamon 3.6?

**Comment by Vahan86** [comment]
@JosephMcc, since there is no response from OP for a long time, can we close this issue?

**Comment by academo** [comment]
Hi there. I am not longer using cinnamon so I can't confirm if the bug is still present or not. I guess if someone has this issue can open a new issue

**Comment by AlbertJP** [comment]
In Mint 18.2 / Cinnamon 3.4.4 with the latest Skype client it is already not a problem anymore, so please close. Could also have been a fix on Skype's end though as the present version is more stable anway than the 4.3 client.
