### ISSUE TITLE
issue report

### ISSUE THREAD

**Issue by zigmasmf** [linuxmint/cinnamon#11917]
### Distribution

mint 21.2

### Package version

5.8.4

### Graphics hardware in use

Intel Corporation 2nd Generation Core Processor Family Integrated Graphics Controller

### Frequency

Only occasionally

### Bug description

tengo este informe de error

### Steps to reproduce

===================================================================
 Info                                                              
===================================================================
           PID: 1466 (cinnamon)
           UID: 1000 (gianpier)
           GID: 1000 (gianpier)
        Signal: 6 (ABRT)
     Timestamp: Sat 2023-11-04 18:22:26 -05 (14h ago)
  Command Line: cinnamon --replace
    Executable: /usr/bin/cinnamon
 Control Group: /user.slice/user-1000.slice/session-c1.scope
          Unit: session-c1.scope
         Slice: user-1000.slice
       Session: c1
     Owner UID: 1000 (gianpier)
       Boot ID: 1dca58005c3c483f8f470feac3819437
    Machine ID: 10b971ac1a304176906b1f6a23827476
      Hostname: USUARIO
       Storage: /var/lib/systemd/coredump/core.cinnamon.1000.1dca58005c3c483f8f470feac3819437.1466.1699140146000000.zst (present)
     Disk Size: 13.7M
       Message: Process 1466 (cinnamon) of user 1000 dumped core.
                
                Found module linux-vdso.so.1 with build-id: 03c1c1c0fb8cc0421c677928d1169779f3d1fa80
                Found module libcanberra-pulse.so with build-id: ce8e9f5428fc4ecf7c2c2f9616b05d8937a4bae4
                Found module libnm.so.0 with build-id: b55112fc60cd68e75679304401959f759c26ff42
                Found module libopus.so.0 with build-id: 53a29374ac557d631d863d9908ff5bec82f55ba5
                Found module libvorbisenc.so.2 with build-id: 5d30e2a713669895dcf3b298ffed2e4ce56121e8
                Found module libFLAC.so.8 with build-id: 280eaf0c50a65ab561e803707fca2ec714cd28a3
                Found module libapparmor.so.1 with build-id: eedc16f04efd1e261091fea5c5306a57d7647d9f
                Found module libasyncns.so.0 with build-id: f192c4e5be41e201707cb7a5a962d43de3c675d2
                Found module libsndfile.so.1 with build-id: 08e2d078caf371d274047899e3526f7e6c0cf611
                Found module libpulsecommon-15.99.so with build-id: 1b08226b05ce048ed0fe3891ef46541035535196
                Found module libpulse-mainloop-glib.so.0 with build-id: b7b32f13a588ad6954b380a7c0301b1cbd965405
                Found module libpulse.so.0 with build-id: 71fae00e01a094ea686803e24fbb20a895e77adf
                Found module libcvc.so.0 with build-id: ac85b2eced3587c6ea29e01c4e52b37fac1efeb8
                Found module librsvg-2.so.2 with build-id: e29ac4267b59a7fa0226e2db1475d480a295b615
                Found module libpixbufloader-svg.so with build-id: cc0bb6bc80c180edd1a2f7b5deff6e3dda24b16f
                Found module libupower-glib.so.3 with build-id: 480bb85a72a85c810228afed92f8084f66023c76
                Found module ISO8859-1.so with build-id: 5baf6252cb4eacc9202ad0213ba9cf5aa4d615d4
                Found module libgioremote-volume-monitor.so with build-id: 44e6ba116e23759ddad789a966ea066d4a6b6760
                Found module libgee-0.8.so.2 with build-id: 13c7508a532a8df4da4bb9f524c9184349848be0
                Found module libcaribou.so.0 with build-id: f289da3819662f2cf6909141404a0dca54437b4f
                Found module libxapp-gtk3-module.so with build-id: 52e54b458e8327bdea03c65d79e37ec3b68ffe55
                Found module libgvfscommon.so with build-id: e7fa580fb91bb21aac9fc69229e0961dc743f2b1
                Found module libgvfsdbus.so with build-id: 28abe694dac468552cc1d23d6f643e7989de85e8
                Found module libpciaccess.so.0 with build-id: 4c93da952f83c1d085d4bdead692db544c79b004
                Found module libedit.so.2 with build-id: 9fcc3490de1a1f4919b1f6e398c99c7fa25f6863
                Found module libdrm_intel.so.1 with build-id: 78e82902c2a74278a5bac31c6cb8361a78bf7586
                Found module libdrm_nouveau.so.2 with build-id: 717e881b4ee3b0bc2344b0f63c4fc10c84263f13

### Expected behavior

solucionar el problema

**Comment by leigh123linux** [comment]
You need to provide a full backtrace.
