### ISSUE TITLE
After instaling Linux kernel 5.15.0-88.98 touchpad does not work anymore

### ISSUE THREAD

**Issue by mintepostal** [linuxmint/cinnamon#11911]
### Distribution

Mint 21.2

### Package version

5.8.4

### Graphics hardware in use

AMD Radeon Vega 3

### Frequency

Always

### Bug description

After installing kernel 5.15.0-88.98 on my laptop, ASUS L1500CD ExpertBook AMD Ryzen 3250U, the touchpad of the laptop does not work anymore. An attached USB mouse works just fine. After going back to kernel 5.15.0-87 using timeshift the touchpad works again. I tried it a second time, same effect.

### Steps to reproduce

Installing kernel 5.15.0-88.98 will cause the problem.

### Expected behavior

Have a working touchpad.

**Comment by leigh123linux** [comment]
File the issue against the kernel.
