### ISSUE TITLE
gdebi details window will not stretch

### ISSUE THREAD

**Issue by ChooChooAl** [linuxmint/Cinnamon#11926]
### Distribution

Mint 21.2

### Package version

Cinnamon 5.8.4 

### Graphics hardware in use

Intel UHD Graphics 620

### Frequency

Always

### Bug description

When opening a deb file for install, you have the option to look at the details of the packages to be installed.  The details window can be stretched, but the inside window with details does not follow.

### Steps to reproduce

Install a program with gdebi that requires additional files.
Click details to see what is needed.
![gdebi1](https://github.com/linuxmint/cinnamon/assets/26556059/b26ac0e2-9cd5-4cf9-987a-357e4960831b)

Try to drag the window down to see more detail.  The box with the detail does not follow with you.

![gdebi2](https://github.com/linuxmint/cinnamon/assets/26556059/726d3a4b-37bb-4362-84f4-62a04085fc1a)

### Expected behavior

The details list should stretch too.

**Comment by JosephMcc** [comment]
This has nothing to do with Cinnamon. It's an application issue.
