### ISSUE TITLE
Window snapping & tiling not working as expected

### ISSUE THREAD

**Issue by DavidPesticcio** [linuxmint/cinnamon#11925]
### Distribution

Linux Mint 21.1

### Package version

5.6.8

### Graphics hardware in use

NVIDIA GM108M

### Frequency

Always

### Bug description

When dragging the KeePassXC window to the left or right edge to snap and tile the window, this works fine - all other directions, including corners, fail to activate at all.

### Steps to reproduce

Un-minimize KeePassXC
Drag title bar to left or right edge to snap and tile - all ok.
Try dragging title bar to top or bottom edge, or into any corner - nothing happens. 😢

### Expected behavior

KeePassXC window should snap and tile when title bar is dragged to top or bottom edge, or into any corner.

### Additional information

@droidmonkey over at KeePassXC suggests this is not a KeePassXC issue. KeePassXC is a fork of KeePassX and that behaves as expected. As do many other Qt apps mentioned in link below.

For more info and context please see: https://github.com/keepassxreboot/keepassxc/issues/10018

All other apps tested also behave as expected, except the Bitwarden Desktop app, which is a Node.js app, which behaves in the same way as KeePassXC. :shrug:

**Comment by droidmonkey** [comment]
You also stated that Scibus didn't work at the edges as well:

> Interestingly, I tried the snapping with Scribus a DTP app, also Qt based, and it will do only left, right, and top to maximise - no corner or bottom edge options.

**Comment by mtwebster** [comment]
This is probably because tiling into those locations would cause the window to be resized smaller than its minimum size (in one or both directions).

These minimums are set by the app's toolkit (Gtk or Qt), whatever widget size calculations turn up.

To check you can just manually resize these windows to see if either dimension might prevent tiling in these locations. If you can't manually resize it enough, then Cinnamon/muffin won't do it either.

**Comment by DavidPesticcio** [comment]
@mtwebster - Thanks for the insight! I did think along those lines and resized the window manually, but  I didn't actually measure/compare the the size at the time.

Now that you have mentioned it as a factor, I have measured the size and there is a vertical overlap (i.e. due to a minimum size constraint) that seems to be the cause of the window not tiling on the top or bottom edges, and obviously the corners also as a result. I also compared the Bitwarden desktop app, and that also has a slight vertical overlap (also due to a minimum size constraint) - which would explain why it also displays the same behaviour. I suspect on a larger resolution this behaviour would not happen unless HDPI scaling was in use.

From my other examples in the linked issue over at KeePassXC, your insight doesn't seem to explain/clarify why some apps don't respond, even when they could, when dragged into a corner, and why some apps maximise when dragged to the top edge, and do nothing when dragged to the bottom edge. Are you aware of a similar rationale that would cause that behaviour?

Thanks.

**Comment by JosephMcc** [comment]
> From my other examples in the linked issue over at KeePassXC, your insight doesn't seem to explain/clarify why some apps don't respond, even when they could, when dragged into a corner, and why some apps maximise when dragged to the top edge, and do nothing when dragged to the bottom edge. Are you aware of a similar rationale that would cause that behaviour?

It's likely the exact same thing. Dragging to the bottom would require the window to fit in half the screen. Maximizing at the top does not.

**Comment by JosephMcc** [comment]
As noted, this is not a Cinnamon bug but a limitation of the app and screen resolution.
