### ISSUE TITLE
Invalid symbolic link for UEFI bootloader in linuxmint-21.2-cinnamon-64bit-edge.iso

### ISSUE THREAD

**Issue by pbatard** [linuxmint/cinnamon#11924]
### Distribution

Mint 21.2

### Package version

N/A

### Graphics hardware in use

N/A

### Frequency

Always

### Bug description

The `linuxmint-21.2-cinnamon-64bit-edge.iso` was improperly mastered on account that, on the ISO-9660 file system, its `/EFI/boot/bootx64.efi` is a (Rock Ridge) symbolic link to `/etc/alternatives/shimx64.efi.signed` __which does not exist on the ISO-9660 file system__.

As a result, any attempt to boot the media using [_File System Transposition_](https://www.mail-archive.com/grub-devel@gnu.org/msg34346.html) (which is the default method used by Rufus and other utilities, and which is different from DD copy) will fail, as the x86_64 UEFI bootloader is obviously invalid.

### Steps to reproduce

1. Mount the ISO under a Linux system.
2. Look at what `/EFI/boot/bootx64.efi` point to (`ls -alFh <ISO Mountpoint>/EFI/boot/bootx64.efi`)
3. Search for the link target or try to access the bootloader content.

### Expected behavior

A __proper__ symbolic link should always point to a target on the same file system. This is not the case. Therefore the `linuxmint-21.2-cinnamon-64bit-edge.iso` was improperly mastered and needs to be fixed.

### Additional information

Note that `linuxmint-21.2-cinnamon-64bit.iso` is fine (since it doesn't have a symbolic link for the `bootx64.efi` bootloader). It's only Edge that appears to be affected.

It should also be noted that using symbolic links for the bootloader is a __VERY__ bad idea, and should be avoided at all cost as you can not count on indirection to retrieve an early stage bootloader.

Finally, this improper mastering leads to major boot issues when using Rufus per https://superuser.com/a/1816478/286681 (since Rufus otherwise has no trouble making Mint work, even though it relies on symbolic links, as long as the UEFI bootloaders are not borked).

**Comment by leigh123linux** [comment]
This isn't a cinnamon issue.

https://github.com/linuxmint/linuxmint/issues

**Comment by pbatard** [comment]
Sigh... https://github.com/linuxmint/linuxmint/issues/622
