### ISSUE TITLE
gnome-logs show only 1 time period also when selecting past day it turns off

### ISSUE THREAD

**Issue by 666xan666** [linuxmint/cinnamon#11923]
### Distribution

Mint 21.2

### Package version

5.8.4

### Graphics hardware in use

NVIDIA Geforce RTX 4060 Ti

### Frequency

Always

### Bug description

Whenever I open gnome-logs and try to  select any date I got:
- only 1 date available
![Zrzut ekranu z 2023-11-12 01-37-48](https://github.com/linuxmint/cinnamon/assets/150563675/ef6fec3a-2202-479f-a81d-ce6d69e2cc06)

- when I select in search "previous launch" program quits
![Zrzut ekranu z 2023-11-12 01-38-19](https://github.com/linuxmint/cinnamon/assets/150563675/9df9416d-8a67-4605-a187-b9209a1fda3f)

### Steps to reproduce

1. Open gnome-logs
2. Check what days you can select - if only one this is the problem
3. Try to search and select "previous run" - program will quit

### Expected behavior

Be able to select all different dates not only from "this run".
Be able to use search and select "previous runs"

**Comment by rcalixte** [comment]
I was unable to replicate this with gnome-logs 42.0 and 43.0. Did anything change in your system logging configuration? Can you verify what version of the application you have?

**Comment by 666xan666** [comment]
I got stable version from LM and it is 42.0. I was changed absolutely nothing in logging config, at the other hand on 2nd LM installation on older laptop with older Nvidia card - everything is working fine - my assumption is that it can be related to NVidia drivers.

**Comment by rcalixte** [comment]
Interesting. My only machine with Nvidia is on R470 for now. What drivers do you have on the machine that isn't working? (And the one working too if that's different.)

**Comment by 666xan666** [comment]
On issued PC: 535.129.03 on old laptop IDK but some 400's because never one don't support this card anymore.

**Comment by JosephMcc** [comment]
I don't see how this is a Cinnamon issue. Seems more like an application issue.
