### ISSUE TITLE
Go down symbolic isn't usable for download anymore. Ugly.

### ISSUE THREAD

**Issue by carlosmintfan** [linuxmint/cinnamon#11945]
### Distribution

Mint 21.2

### Package version

Cinnamon 5.8.4

### Graphics hardware in use

_Not relevant_

### Frequency

Always

### Bug description

In Mint 21.2, after all that icon changes, the download button for spices in cinnamon settings looks ugly or at least - well, I was irritated at first. Maybe I could have been that even with the old symbol, anyway...
![grafik](https://github.com/linuxmint/cinnamon/assets/118076740/5c894c24-fdd8-4161-85c2-dfd73a5e87da)
Maybe use the new save icon? Or maybe `folder-download-symbolic`?

### Steps to reproduce

Open spices (applets, desklets etc.) settings and go to the install tab. Look how the install button on spices looks - without the | from the arrow!. Do you recognise it as install from the first look? https://github.com/linuxmint/cinnamon/blob/62b184e8210bceb5ed0209d79d3d8dad599caf65/files/usr/share/cinnamon/cinnamon-settings/bin/ExtensionCore.py#L766

### Expected behavior

A better symbol should be on the download/install button.

**Comment by mtwebster** [comment]
Fixed: https://github.com/linuxmint/cinnamon/pull/11918/commits/e0ca83bec66ad4a8cb4daa1e3109a92322f339e5
