### ISSUE TITLE
Samsung laptops have a variety of firmware issues

### ISSUE THREAD

**Issue by RustoMCSpit** [linuxmint/cinnamon#11948]
### Distribution

Mint 21.2 Victoria, LTS

### Package version

5.8.4

### Graphics hardware in use

Integrated Intel i5 iris xe

### Frequency

Always

### Bug description

Issues:
1. Can't have a charger inserted or removed while in use or will enter perpetual sleep cycle
2. Occasionally, trackpad becomes unusable as it won't let the cursor to move. Two finger zoom however is never usable (edit: just found out you need to hold ctrl, this should be an option in mouse and touchpad, regardless it is very inconsistent and janky and still 'malfunctioning')
3. Encryption of storage at the start of installation causes a perpetual sleep cycle which somehow even prevented BIOS from being opened(?) Required me to restart video drivers. (Ctrl + Super key + Shift + B) (Or maybe I pressed those buttons and it just worked, coincidences happen)
4. Can't login without perpetual sleep cycle, this occurs about ten seconds into the login screen, issue goes away once your past it.

Exact model:
Manufacturer: SAMSUNG ELECTRONICS CO., LTD.
Product Name: 750XED
Version: P13CFG

### Steps to reproduce

First:
1. Remove or insert charger
 
Second:
1. Truly random, does not happen midsession, only if PC just booted

Third:
1. Encrypt at install of LM
2. Try to boot, occasionally will get to the enter encryption password part but will enter infinite sleep cycle
3. Baffling prevents BIOS entering(?) (possibly, needs to be tested)

Fourth:
1. Boot PC
2. After about ten seconds of the login screen, you will enter a sleep cycle boot loop which inifinitely causes the PC to wake and sleep over and over (the wake is too short to do anything)

I feel like Linux Mint install should detect the PC a user is installing to and warn them that this model is marked as 'unstable' and list off its known issues

### Expected behavior

.

### Additional information
Interestingly, for the last issue, if a user does Ctrl + Alt + L after past the login screen for the first time of a session, they will never enter boot loop and it will function as intended

**Comment by RustoMCSpit** [comment]
If any more details are wanted please clarify

**Comment by timur-g** [comment]
I cannot help on that, but please try to update: fwupdmgr refresh && fwupdmgr get-updates && fwupdmgr update

**Comment by RustoMCSpit** [comment]
> I cannot help on that, but please try to update: fwupdmgr refresh && fwupdmgr get-updates && fwupdmgr update

would you know where to contacf?

**Comment by RustoMCSpit** [comment]
to get someone who can help

**Comment by leigh123linux** [comment]
This isn't a cinnamon issue, file it at https://github.com/linuxmint/linuxmint/issues

**Comment by RustoMCSpit** [comment]
> I cannot help on that, but please try to update: fwupdmgr refresh && fwupdmgr get-updates && fwupdmgr update

no availabke updates, wouldnt these be available in the update manager automatically?

**Comment by RustoMCSpit** [comment]
> This isn't a cinnamon issue, file it at https://github.com/linuxmint/linuxmint/issues

Do you know who manages that? All of the issues have no interaction for seemingly years beyond self closes

**Comment by RustoMCSpit** [comment]
> I cannot help on that, but please try to update: fwupdmgr refresh && fwupdmgr get-updates && fwupdmgr update

didnt work but thanms

**Comment by RustoMCSpit** [comment]
> This isn't a cinnamon issue, file it at https://github.com/linuxmint/linuxmint/issues

just linked there, is there anything else i can do? this is still broken
