### ISSUE TITLE
Cinnamon 6.0.0 not build on Debian SID

### ISSUE THREAD

**Issue by misterhsp** [linuxmint/cinnamon#11956]
### Distribution

Debian SID

### Package version

Cinnamon 6.0.0

### Frequency

Always

### Bug description

   dh_shlibdeps -a
dpkg-shlibdeps: warning: can't extract name and version from library name 'libst.so'
dpkg-shlibdeps: warning: can't extract name and version from library name 'libst.so'
dpkg-shlibdeps: warning: can't extract name and version from library name 'libcinnamon.so'
dpkg-shlibdeps: warning: can't extract name and version from library name 'libcinnamon.so'
dpkg-shlibdeps: warning: package could avoid a useless dependency if debian/cinnamon/usr/lib/x86_64-linux-gnu/cinnamon/libst.so was not linked against libGLESv2.so.2 (it uses none of the library's symbols)
   dh_girepository
dh_girepository: error: Could not find Clutter-0.gir dependency
make: *** [debian/rules:25: binary] Error 255
dpkg-buildpackage: error: debian/rules binary subprocess returned exit status 2

### Steps to reproduce

' '

### Expected behavior

' '

### Additional information

' '

**Comment by Fantu** [comment]
This is related to gobject-introspection changes in debian testing/unstable and next ubuntu

to fix and also avoid additional *-dev deps in cinnamon (using next debian/ubuntu) needs to add in d/rules:
```
override_dh_girepository:
	dh_girepository -XCinnamon-0.1.gir -XSt-1.0.gir /usr/lib/$(DEB_HOST_MULTIARCH)/muffin
```

**Comment by Fantu** [comment]
I think can be closed as solved with https://github.com/linuxmint/cinnamon/pull/11999
