### ISSUE TITLE
Brightness keys do not work when the taskbar menu is open

### ISSUE THREAD

**Issue by ylevental** [linuxmint/cinnamon#11955]
### Distribution

Fedora Linux 39 Cinnamon (x86-64)

### Package version

5.8.4

### Graphics hardware in use

Advanced Micro Devices, Inc. [AMD/ATI] Cezanne [Radeon Vega Series / Radeon Vega Mobile Series]

### Frequency

Always

### Bug description

When I open the taskbar menu and press the brightness buttons on my laptop, nothing changes.  This also applies to any other taskbar applet.  The brightness buttons work fine otherwise.  The volume buttons always work.

### Steps to reproduce

1. Press the "Menu" button on the Cinnamon taskbar
2. If you have brightness buttons on your keyboard, press either one.

### Expected behavior

The brightness buttons should always work, even if the taskbar menu is open.

**Comment by v1naykaushik** [comment]
@ylevental you should label it as bug. I have this same problem. System info is below

System:
  Kernel: 6.8.0-48-generic arch: x86_64 bits: 64 compiler: gcc v: 13.2.0 clocksource: tsc
  Desktop: Cinnamon v: 6.2.9 tk: GTK v: 3.24.41 wm: Muffin v: 6.2.0 vt: 7 dm: LightDM v: 1.30.0
    Distro: Linux Mint 22 Wilma base: Ubuntu 24.04 noble
Machine:
  Type: Laptop System: HP product: HP Laptop 14s-cf3xxx v: N/A serial: <superuser required>
    Chassis: type: 10 serial: <superuser required>
  Mobo: HP model: 868C v: 63.17 serial: <superuser required> part-nu: 172T4PA#ACJ
    uuid: <superuser required> UEFI: AMI v: F.21 date: 10/26/2022
Battery:
  ID-1: BAT0 charge: 36.0 Wh (100.0%) condition: 36.0/36.0 Wh (100.0%) volts: 12.4 min: 11.3
    model: Hewlett-Packard Primary type: Li-ion serial: <filter> status: discharging
CPU:
  Info: dual core model: Intel Core i3-1005G1 bits: 64 type: MT MCP smt: enabled arch: Ice Lake
    rev: 5 cache: L1: 160 KiB L2: 1024 KiB L3: 4 MiB
  Speed (MHz): avg: 1080 high: 1323 min/max: 400/3400 cores: 1: 1323 2: 1300 3: 1300 4: 400
    bogomips: 9523
  Flags: avx avx2 ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx
Graphics:
  Device-1: Intel Iris Plus Graphics G1 vendor: Hewlett-Packard driver: i915 v: kernel arch: Gen-11
    ports: active: eDP-1 empty: DP-1, DP-2, DP-3, DP-4, HDMI-A-1 bus-ID: 00:02.0 chip-ID: 8086:8a56
    class-ID: 0300
  Device-2: Cheng Uei Precision Industry (Foxlink) HP TrueVision HD Camera driver: uvcvideo
    type: USB rev: 2.0 speed: 480 Mb/s lanes: 1 bus-ID: 1-6:2 chip-ID: 05c8:03d2 class-ID: 0e02
  Display: x11 server: X.Org v: 21.1.11 with: Xwayland v: 23.2.6 driver: X: loaded: modesetting
    unloaded: fbdev,vesa dri: iris gpu: i915 display-ID: :0 screens: 1
  Screen-1: 0 s-res: 1366x768 s-dpi: 96 s-size: 361x203mm (14.21x7.99") s-diag: 414mm (16.31")
  Monitor-1: eDP-1 model: AU Optronics 0x733c res: 1366x768 hz: 60 dpi: 112
    size: 309x173mm (12.17x6.81") diag: 354mm (13.9") modes: 1366x768
  API: EGL v: 1.5 hw: drv: intel iris platforms: device: 0 drv: iris device: 1 drv: swrast
    surfaceless: drv: iris x11: drv: iris inactive: gbm,wayland
  API: OpenGL v: 4.6 compat-v: 4.5 vendor: intel mesa v: 24.0.9-0ubuntu0.2 glx-v: 1.4
    direct-render: yes renderer: Mesa Intel UHD Graphics (ICL GT1) device-ID: 8086:8a56
Audio:
  Device-1: Intel Ice Lake-LP Smart Sound Audio vendor: Hewlett-Packard driver: snd_hda_intel
    v: kernel bus-ID: 00:1f.3 chip-ID: 8086:34c8 class-ID: 0403
  API: ALSA v: k6.8.0-48-generic status: kernel-api
  Server-1: PipeWire v: 1.0.5 status: active with: 1: pipewire-pulse status: active
    2: wireplumber status: active 3: pipewire-alsa type: plugin
Network:
  Device-1: Realtek RTL8111/8168/8211/8411 PCI Express Gigabit Ethernet
    vendor: Hewlett-Packard RTL8111/8168/8411 driver: r8169 v: kernel pcie: speed: 2.5 GT/s lanes: 1
    port: 4000 bus-ID: 02:00.0 chip-ID: 10ec:8168 class-ID: 0200
  IF: enp2s0 state: down mac: <filter>
  Device-2: Realtek RTL8821CE 802.11ac PCIe Wireless Network Adapter vendor: Hewlett-Packard
    driver: rtw_8821ce v: N/A pcie: speed: 2.5 GT/s lanes: 1 port: 3000 bus-ID: 03:00.0
    chip-ID: 10ec:c821 class-ID: 0280
  IF: wlp3s0 state: up mac: <filter>
Bluetooth:
  Device-1: Realtek Bluetooth 4.2 Adapter driver: btusb v: 0.8 type: USB rev: 1.1 speed: 12 Mb/s
    lanes: 1 bus-ID: 1-10:3 chip-ID: 0bda:b00a class-ID: e001 serial: <filter>
  Report: hciconfig ID: hci0 rfk-id: 2 state: down bt-service: enabled,running rfk-block:
    hardware: no software: yes address: <filter>
RAID:
  Hardware-1: Intel 82801 Mobile SATA Controller [RAID mode] driver: ahci v: 3.0 port: 5060
    bus-ID: 00:17.0 chip-ID: 8086:282a rev: N/A class-ID: 0104
Drives:
  Local Storage: total: 238.47 GiB used: 69.32 GiB (29.1%)
  ID-1: /dev/nvme0n1 vendor: SK Hynix model: BC511 HFM256GDJTNI-82A0A size: 238.47 GiB
    speed: 31.6 Gb/s lanes: 4 tech: SSD serial: <filter> fw-rev: HPS0 temp: 33.9 C scheme: GPT
Partition:
  ID-1: / size: 233.18 GiB used: 69.31 GiB (29.7%) fs: ext4 dev: /dev/nvme0n1p2
  ID-2: /boot/efi size: 511 MiB used: 6.1 MiB (1.2%) fs: vfat dev: /dev/nvme0n1p1
Swap:
  ID-1: swap-1 type: file size: 2 GiB used: 0 KiB (0.0%) priority: -2 file: /swapfile
USB:
  Hub-1: 1-0:1 info: hi-speed hub with single TT ports: 12 rev: 2.0 speed: 480 Mb/s lanes: 1
    chip-ID: 1d6b:0002 class-ID: 0900
  Device-1: 1-6:2 info: Cheng Uei Precision Industry (Foxlink) HP TrueVision HD Camera
    type: video driver: uvcvideo interfaces: 2 rev: 2.0 speed: 480 Mb/s lanes: 1 power: 500mA
    chip-ID: 05c8:03d2 class-ID: 0e02
  Device-2: 1-10:3 info: Realtek Bluetooth 4.2 Adapter type: bluetooth driver: btusb
    interfaces: 2 rev: 1.1 speed: 12 Mb/s lanes: 1 power: 500mA chip-ID: 0bda:b00a class-ID: e001
    serial: <filter>
  Hub-2: 2-0:1 info: super-speed hub ports: 6 rev: 3.1 speed: 10 Gb/s lanes: 1 chip-ID: 1d6b:0003
    class-ID: 0900
Sensors:
  System Temperatures: cpu: 58.0 C mobo: N/A
  Fan Speeds (rpm): N/A
Repos:
  Packages: pm: dpkg pkgs: 2119
  No active apt repos in: /etc/apt/sources.list
  Active apt repos in: /etc/apt/sources.list.d/brave-browser-release.list
    1: deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg] https: //brave-browser-apt-release.s3.brave.com/ stable main
  Active apt repos in: /etc/apt/sources.list.d/google-chrome.list
    1: deb [arch=amd64] https: //dl.google.com/linux/chrome/deb/ stable main
  Active apt repos in: /etc/apt/sources.list.d/obsproject-obs-studio-noble.list
    1: deb [signed-by=/etc/apt/keyrings/obsproject-obs-studio-noble.gpg] https: //ppa.launchpadcontent.net/obsproject/obs-studio/ubuntu noble main
  Active apt repos in: /etc/apt/sources.list.d/official-package-repositories.list
    1: deb http: //packages.linuxmint.com wilma main upstream import backport
    2: deb http: //archive.ubuntu.com/ubuntu noble main restricted universe multiverse
    3: deb http: //archive.ubuntu.com/ubuntu noble-updates main restricted universe multiverse
    4: deb http: //archive.ubuntu.com/ubuntu noble-backports main restricted universe multiverse
    5: deb http: //security.ubuntu.com/ubuntu/ noble-security main restricted universe multiverse
  Active apt repos in: /etc/apt/sources.list.d/vscode.list
    1: deb [arch=amd64,arm64,armhf] https: //packages.microsoft.com/repos/code stable main
Info:
  Memory: total: 8 GiB note: est. available: 7.45 GiB used: 2.02 GiB (27.2%)
  Processes: 287 Power: uptime: 46m states: freeze,mem suspend: deep wakeups: 1
    hibernate: disabled Init: systemd v: 255 target: graphical (5) default: graphical
  Compilers: gcc: 13.2.0 Client: Cinnamon v: 6.2.9 inxi: 3.3.34

**Comment by ylevental** [comment]
@v1naykaushik it won't let me, so I will close this and open a new ticket.
