### ISSUE TITLE
"Turn on-screen keyboard on or off" does not enable/disable it (turn on/off) but shows/hide it

### ISSUE THREAD

**Issue by sphh** [linuxmint/cinnamon#11974]
### Distribution

Linux Mint 21.2 Cinnamon

### Package version

5.8.4

### Frequency

Always

### Bug description

Background: I have a tablet running Linux Mint and a docking station for it. A keyboard is connected to the docking station.

When I take the tablet out of the docking station, I do not have a physical keyboard. I click on the applet `On-Screen keyboard` which brings up the virtual keyboard.

When I take the tablet back and dock it, I do not need the virtual keyboard anymore. Clicking on the applet `On-Screen keyboard` shows/hides the virtual keyboard, but does not disable it.

I also have set the keyboard shortcut for `Universal Access > Turn on-screen keyboard on or off`. Pressing this shows/hides the virtual keyboard, but does not disable it.

The only way to disable the virtual keyboard is to open the `Accessibility` setting and switch it off there (`Enable the on-screen keyboard`).

### Steps to reproduce

1. Install the `On-Screen keyboard` applet.
2. Set a shortcut for `System settings > Keyboard > Shortcuts > Universal Access > Turn on-screen keyboard on or off`
3. Start the virtual keyboard either by clicking on the `On-Screen keyboard` applet or hitting the shortcut → the virtual keyboard appears if a text input widget gets the focus
4. Try to turn the virtual keyboard off by clicking on the applet, right-clicking on the applet or hitting the shortcut → the visibility of the virtual keyboard is toggled, but there is no way to switch it off
5. Switch the virtual keyboard off by going into the `System settings > Accessibility` setting and switch it off there

### Expected behavior

There should be a way to disable (=turn off = switch off) the virtual keyboard in addition to show/hide it.

### Additional information

1. I think the naming of the "`Turn on-screen keyboard on or off`" item in the `Keyboard > Shortcuts > Universal Access` should read "`Show/hide the on-screen keyboard`" to make clear the functionality of that shortcut.
2. There should be an additional shortcut to enable/disable the virtual keyboard in `System settings > Keyboard > Shortcuts > Universal Access`.
3. The applet should grow the possibility to disable the virtual keyboard:
    1. Add a menu item to the right-click menu item to disable the virtual keyboard
    2. Add a middle mouse button click to disable the virtual keyboard

**Comment by PowaBanga** [comment]
i have exactly the same issue on archlinux. this is extremely inconvenient...
