### ISSUE TITLE
Cinnamon Screensaver/Lock Screen Erroneously Uses Application Theme Instead of Desktop Theme

### ISSUE THREAD

**Issue by nsleasy** [linuxmint/cinnamon#11985]
### Distribution

Fedora 39

### Package version

5.8.4

### Graphics hardware in use

Intel Corporation TigerLake-LP GT2 [Iris Xe Graphics]

### Frequency

Always

### Bug description

After upgrade from Fedora 38 to Fedora 39 -- and the minor upgrade from Cinnamon package versions *-1 to *-2 -- the Cinnamon lock screen starts using Application Theme elements instead of Desktop Theme.

I have eliminated any specific user configuration issues. The problem arises on a freshly created user account as well.

Actual Results:  
A light theme (white password field) appears on authentication, matching the Applications theme.

### Steps to reproduce

1. Set a light Applications theme
2. Set a dark Desktop theme
3. Lock the screen and authenticate to unlock
4. Observe the light (white) password field background

### Expected behavior

Since a dark Desktop theme was set, one would expect the screensaver/lock screen to use that, versus the Application theme. Selecting a dark Applications theme produces the expected dark password field, but the screensaver/lock screen should use the Desktop theme.

### Additional information

The Cinnamon version was not upgraded going from F38 to F39 and the same version (5.8.4.5) does not produce the same behavior on Linux Mint. However, many underlying Cinnamon packages underwent a minor upgrade from versions *-1 to *-2 on Fedora 39.

This bug presents with the same behavior in the Cinnamon beta version 6.0.0 found on the latest openSUSE Tumbleweed snapshot.

To reiterate, the Cinnamon version was not upgraded going from F38 to F39 and the same version does not produce the same behavior on Linux Mint.

 It seems this bug was introduced in that minor update. The following behavior has been observed:

1 - The bug is NOT present on the latest release of Linux Mint Cinnamon (21.2)

2 - The bug is NOT present on Fedora 38, with the following configuration
rpm -qa | grep cinnamon
cinnamon-translations-5.8.1-1.fc38.noarch
cinnamon-control-center-filesystem-5.8.1-1.fc38.x86_64
cinnamon-themes-2.1.5-1.fc38.noarch
cinnamon-menus-5.8.0-1.fc38.x86_64
slick-greeter-cinnamon-1.8.2-1.fc38.noarch
cinnamon-desktop-5.8.0-1.fc38.x86_64
cinnamon-screensaver-5.8.0-1.fc38.x86_64
cinnamon-session-5.8.1-1.fc38.x86_64
cinnamon-settings-daemon-5.8.1-1.fc38.x86_64
cinnamon-control-center-5.8.1-1.fc38.x86_64
cinnamon-calendar-server-5.8.4-5.fc38.x86_64
cinnamon-5.8.4-5.fc38.x86_64

3 - The bug IS present on Fedora 39, with the following configuration
rpm -qa | grep cinnamon
cinnamon-translations-5.8.1-2.fc39.noarch
cinnamon-control-center-filesystem-5.8.1-2.fc39.x86_64
cinnamon-themes-2.1.5-2.fc39.noarch
cinnamon-menus-5.8.0-2.fc39.x86_64
cinnamon-desktop-5.8.0-2.fc39.x86_64
cinnamon-settings-daemon-5.8.1-2.fc39.x86_64
cinnamon-control-center-5.8.1-2.fc39.x86_64
cinnamon-session-5.8.1-2.fc39.x86_64
cinnamon-screensaver-5.8.0-2.fc39.x86_64
slick-greeter-cinnamon-1.8.2-2.fc39.noarch
cinnamon-5.8.4-5.fc39.x86_64
cinnamon-calendar-server-5.8.4-5.fc39.x86_64

4 - The bug IS present on the latest openSUSE Tumbleweed snapshot, with the following configuration:
rpm -qa | grep cinnamon
libcinnamon-menu-3-0-6.0.0-1.1.x86_64
libcinnamon-desktop-data-6.0.0-1.1.noarch
libcinnamon-desktop-data-branding-openSUSE-42.2-5.19.noarch
libcinnamon-desktop4-6.0.0-1.1.x86_64
libcinnamon-desktop-lang-6.0.0-1.1.noarch
cinnamon-settings-daemon-6.0.0-1.1.x86_64
cinnamon-settings-daemon-lang-6.0.0-1.1.noarch
cinnamon-screensaver-6.0.0-1.1.x86_64
cinnamon-screensaver-lang-6.0.0-1.1.noarch
cinnamon-gschemas-6.0.0-1.1.x86_64
cinnamon-gschemas-branding-openSUSE-42.2-5.19.noarch
libcinnamon-control-center1-6.0.0-1.1.x86_64
cinnamon-control-center-common-6.0.0-1.1.noarch
cinnamon-control-center-6.0.0-1.1.x86_64
cinnamon-control-center-lang-6.0.0-1.1.noarch
cinnamon-session-6.0.0-1.1.x86_64
cinnamon-6.0.0-1.1.x86_64
cinnamon-lang-6.0.0-1.1.noarch
cinnamon-session-lang-6.0.0-1.1.noarch
patterns-cinnamon-cinnamon_basis-202021205-2.8.x86_64
patterns-cinnamon-cinnamon-202021205-2.8.x86_64

**Comment by nsleasy** [comment]
- Reference Fedora Bug 2254841

https://bugzilla.redhat.com/show_bug.cgi?id=2254841

**Comment by leigh123linux** [comment]
https://github.com/linuxmint/cinnamon-screensaver/commit/37ab8ed18f35591f2bd99043f12c06d98b4527db
