### ISSUE TITLE
Permanent transparency

### ISSUE THREAD

**Issue by Glokanshmere** [linuxmint/cinnamon#11995]
### Distribution

Linux mint 21.2

### Package version

5.8.4

### Graphics hardware in use

PNY Nvidia 3060 RTX

### Frequency

Always

### Bug description

Hello, I am having issues with my Opacity for all programs. It seems my computer wants to set every program at 60% opaque and I have no control over it.
In my picture you can see all of the individual attempts that I have tried and none have worked.
-Using Keyboard to Increase/decrease opacity does not work.
-Increasing mouse scroll opacity to 100 does not work.
Opacify Windows - in extensions does not work, even when set to maximum.
-Timeshift - does not work to change it, the opacity remains the same
-Reseting defaults on each of these programs does not work.
I did not change anything in settings to cause this issue, it suddenly started doing this after I installed a new Clipboard manager for copying and pasting, Clipit, but I have since uninstalled it to see if that would fix the issue. 
Selecting a program will cause that program to become Opaque, but rest remain transparent. Not sure what to do. I need multiple programs to be opaque in order to run everything smoothly. Please check my picture for a reference.
![Screenshot from 2023-12-27 11-55-35](https://github.com/linuxmint/cinnamon/assets/155008893/044c87bf-5544-4cc1-8416-5001e9ed3ea3)

### Steps to reproduce

I did not change anything in settings to cause this issue, it suddenly started doing this after I installed a new Clipboard manager for copying and pasting, Clipit, but I have since uninstalled it to see if that would fix the issue. 

### Expected behavior

Everything should be Opaque
![Screenshot from 2023-12-27 11-55-35](https://github.com/linuxmint/cinnamon/assets/155008893/cf35e73b-ded1-4d80-b462-e9215681f680)

### Additional information

I have tried these options
-Using Keyboard to Increase/decrease opacity does not work.
-Increasing mouse scroll opacity to 100 does not work.
-Opacify Windows - in extensions does not work, even when set to maximum.
-Timeshift - does not work to change it, the opacity remains the same
-Reseting defaults on each of these programs does not work.

**Comment by claudiux** [comment]
In system settings -> Windows, please try to set  the minimum opacity to at least 80%.

**Comment by Glokanshmere** [comment]
Hello Claudiux, thank you for your input, I have already attempted to change the opacity in System Settings - Windows to 100, I have also tried other numbers like 80, 90, or 85. 

I have attempted these options below. If you have anymore insight or anything that you can think of below, let me know.

I have tried these options
-Using system settings - Keyboard to Increase/decrease opacity does not work.
-Increasing mouse scroll opacity to 100(or an other number) does not work(system settings - Windows - adjust opacity).
-Opacify Windows - in extensions does not work, even when set to maximum.
-Timeshift - does not work to change it, the opacity remains the same
-Resetting defaults on each of these programs does not work.

**Comment by Glokanshmere** [comment]
So the bug appears to occur with the user profile, I ended up creating a new account to see if that would fix the issue. I will say this issue is not resolved though, but the workaround solution is to create a new profile.

What's even weirder about the bug is that it also affects other Desktops. I currently have Linux Mint DE, KDE Plasma, and Gnome/Unity. All of these are affected by this transparency bug under that specific profile. As reported, none of these suggestions below worked.
-Using system settings - Keyboard to Increase/decrease opacity does not work.
-Increasing mouse scroll opacity to 100(or an other number) does not work(system settings - Windows - adjust opacity).
-Opacify Windows - in extensions does not work, even when set to maximum.
-Timeshift - does not work to change it, the opacity remains the same
-Resetting defaults on each of these programs does not work.

The only thing that did work is making a new account. Also, I have opacity control again in this new account. As you can see, everything is opaque now except for my file explorer which I made intentionally translucent with the mouse control. 
![Screenshot from 2023-12-27 20-28-31](https://github.com/linuxmint/cinnamon/assets/155008893/1476d493-cd86-4f54-87e9-ae8d8f4a72fe)

**Comment by claudiux** [comment]
Maybe check your Nvidia settings?

**Comment by JosephMcc** [comment]
I'm closing this since it seems to be unrelated to Cinnamon. That fact that it happens on all installed DE's would point to it being something that happened in that specific user profile.
