### ISSUE TITLE
Clicking Pix furiously while preferences window is open causes cinnamon to crash

### ISSUE THREAD

**Issue by Mustafa-eksi** [linuxmint/cinnamon#11996]
### Distribution

Mint 21.2

### Package version

5.8.4

### Graphics hardware in use

dualgpu: Intel CometLake-H GT2 [UHD Graphics], NVIDIA GeForce GTX 1660 Ti Mobile

### Frequency

Quite often

### Bug description

Clicking Pix furiously while preferences window is open causes cinnamon to crash.
Crash report: https://termbin.com/d8xk
Pix version: 3.0.2

### Steps to reproduce

1. Open Pix
2. Open Pix's Preferences window
3. Start furiously clicking to Pix's button on Grouped Window List.
4. Cinnamon crashes eventually

### Expected behavior

Clicking a app on group window list shouldn't crash cinnamon.
This issue doesn't happen with other apps as it should be.

### Additional information

Video Capture of bug:
https://github.com/linuxmint/cinnamon/assets/52630762/2dadd06a-2785-43b9-a11a-3dc7f28a33d8

**Comment by mtwebster** [comment]
I'm pretty sure this has been fixed in cinnamon 6.0:
https://github.com/linuxmint/cinnamon/commit/e2cb99ad4ab4f729571791e1c4337f7e3850fdf6

**Comment by Mustafa-eksi** [comment]
Yeah, I tested it in cinnamon 6.0.3 and it is fixed.
