### ISSUE TITLE
[Question]: How to style custom widgets?

### ISSUE THREAD

**Issue by crazydef** [linuxmint/cinnamon#12005]
Hi,

If I wanted to custom render parts of my application and have them look like standard Cinnamon widgets in the current theme, where would I obtain information about the current theme and how it's applied to widgets?

I'm not just looking for API documentation (but that will be useful), but also a top-level overview of how styles work in Cinnamon.

**Comment by fredcw** [comment]
Widgets are only styled by the widget toolkit. If your app is using Gtk then this can only be styled with a gtk theme. Cinnamon panel, applets, desklets, etc are drawn using St/Clutter libraries rather than Gtk and which are a part of cinnamon. St reads the current cinnamon theme to style it's widgets. Not sure how you would go about adding St/Clutter widgets to your application.

**Comment by crazydef** [comment]
Oh, so there's no common colour theme or render style across the entire desktop?  Applications just do whatever they like?

**Comment by crazydef** [comment]
So I guess my question still stands:  How do I read the current Cinnamon theme to style my application in the same way St and Gtk do?

**Comment by fredcw** [comment]
If you look at a theme like Mint-Y (`usr/share/themes/Mint-Y/`) you'll see folders and styles for different toolkits: gtk2, gtk3, gtk4, cinnamon (St), and metacity (used for drawing the titlebars and borders of windows that don't have client side decorations (CSD)). So the current theme can be used to give a similar style to apps using different toolkits. With cinnamon, the default file `/usr/share/cinnamon/theme/cinnamon.css` is read first and then the cinnamon.css of the currently selected desktop theme is read to override any css selectors in the default file. The current cinnamon theme being used is stored in gsettings `/org/cinnamon/theme/name`.

You would have to parse the current cinnamon.css file being used and then style your app accordingly which could be quite complicated to do. How you style your own apps widgets differently from the currently selected theme would depend on the toolkit you're using.

**Comment by crazydef** [comment]
Thanks, I'll look into those.

I'm using my own cross platform UI engine.  Hence the desire to make it look native on different platforms.  :)
