### ISSUE TITLE
session lock doesn't work after update to 21.3 Virginia

### ISSUE THREAD

**Issue by DirkHaar** [linuxmint/cinnamon#12016]
### Distribution

Mint 21.3

### Package version

6.0.4

### Graphics hardware in use

Intel i7-1360P  driver=i915

### Frequency

Always

### Bug description

Locking doesn't work, no reaction at all, neither via keyboard nor Cinnamon menu.

Issuing `cinnamon-screensaver-lock --lock` does nothing. 
Issuing `loginctl lock-sessions` opens a dialog saying privileged rights are needed for lock/unlock (on top of open windows/workspace), does nothing when these are granted. 

No log entries are added.

### Steps to reproduce

Open menu, click lock screen icon or use Alt-Ctrl-L (or other defined keystroke).

### Expected behavior

Display should be "blanked" or what else is defined, and screen should be locked (without necessity of privileges).

**Comment by mtwebster** [comment]
Can you run:
```
cinnamon-screensaver --debug
```
Then try to lock the screen and see if there are any errors there.

If it works there, check ~/.xsession-errors and also the systemd journal (try `journalctl -t org.cinnamon.ScreenSaver`)

Note: If this is a wayland session, the screensaver is disabled currently, and issues should go to https://github.com/linuxmint/wayland instead

**Comment by DirkHaar** [comment]
Ok, now I know what's causing it. I was experiencing this in the default Cinnamon session.
I booted into the default Cinnamon session, logged out, logged into Cinnamon Wayland and off again,
and back into the default X session. _Then_ I wanted to lock the screen.
So it seems due to the current "disabilty" under wayland the Cinnamon can't be locked also afterwards.
After a full reboot locking works as it should, fine.
I would have assumed that locking should not be connected to the previous session, but okay.

**Comment by mtwebster** [comment]
A previous session shouldn't matter, this is another issue currently.
