### ISSUE TITLE
Panel issue if multiple screens are used 

### ISSUE THREAD

**Issue by TobiZog** [linuxmint/cinnamon#12017]
### Distribution

Mint 21.3

### Package version

6.0.4

### Graphics hardware in use

Advanced Micro Devices, Inc. [AMD/ATI] Rembrandt (Ryzen 7 PRO 6850U iGPU)

### Frequency

Always

### Bug description

I'm using a Lenovo Thinkpad P14s Gen 3 with a Lenovo hub. To the hub are two displays attached. The issues comes with the new Cinnamon 6.0/Linux Mint 21.3.

Display Configuration:
![image](https://github.com/linuxmint/cinnamon/assets/67568441/92733ad4-5702-431d-8e2e-d8a264b9c81e)

There are multiple panel issues:
- If I right-click on the panel, select move and choose a position on another screen, the panel does not move to the screen, but uses the selected position (bottom, left, right, top)
- If I want to add a new panel to the Philips screen, Cinnamon moves the panel from the LG to the Philips one and creates a new panel on the integrated display.
- If I remove the empty panel on the integrated display, it will removed and the panel from the Philips display moves to the integrated display

Video:
https://github.com/linuxmint/cinnamon/assets/67568441/54290fda-8f7b-4f2a-bdba-12af05cdd659

### Steps to reproduce

See video

### Expected behavior

The panel should appear on the right display.

### Additional information

I think, there is a bug with the internal display counter. In the display manager drop-down menu is e.g. the Philips display with the number "3" described, but in the layout with the number "2". The internal display has no number in the layout manager screen.

**Comment by TobiZog** [comment]
Desktop icons can only be configured and created on the internal display of my laptop. But this is not the primary display. This means, that the bug does not only affects the panels. It affects everything around the display configuration

**Comment by Klaustrix** [comment]
I'm experiencing a very similar behaviour on my 4 monitor PC. Same Distribution and package, but my GPU is a RTX 2080 Ti.

I have it in a 2x2 as such:
![R2I5ZNY 1](https://github.com/linuxmint/cinnamon/assets/24738562/3d60d7fb-1f10-4c16-835e-70157c425cc7)

It's a tough problem to explain so I did a step by step illustration for what happens for me:
![LMPanels](https://github.com/linuxmint/cinnamon/assets/24738562/035ab849-5919-4d2e-98e5-6693621bc432)

**Comment by grimgrum** [comment]
I believe I am experiencing the same, 2 monitors here but display numbering is swapped, and if I try moving to the top of the left panel it puts it on the top of the right panel. Image of display settings and gif of behavior below.

![image](https://github.com/linuxmint/cinnamon/assets/87434271/fad3798a-ac14-4b5c-8ebd-f5e471feab3c)

![image](https://github.com/linuxmint/cinnamon/assets/87434271/521e4b76-34c9-466c-82b8-247d9d81769e)

**Comment by drstrangelove4** [comment]
I have the exact same bug as described here. The bug is only present in Linux mint 21.3 and not 21.2, where the bar behaviour works as expected.

**Comment by TaromaruYuki** [comment]
Exact same issue. Thought I was going crazy. 

Attached the Display Settings and a video showing how wonky the panel gets with one and two panels, completely making two panels on top and bottom impossible. (Ignore the double cursor, OBS had 'Capture Cursor' on)

![image](https://github.com/linuxmint/cinnamon/assets/48397556/538f7e58-3eee-458e-acb9-1a7ff372c5ae)

https://github.com/linuxmint/cinnamon/assets/48397556/da4f1ec3-1bdf-47f2-a0b0-10f236bfed60

**Comment by brian22333** [comment]
I'm also experiencing this issue on 21.3 Cinnamon v 6.0.4 of the panel jumping screens but also additional behaviour.
Once a panel is moved to the top of my screen and I add another on the bottom, the top panel moves to yet another screen.
Screen 2 is the desired and main monitor. The flow has gone like this:
- Move panel to top of screen 2 and it jumps to screen 1.
- Move panel to top of screen 1 to 'trick' it into moving to correct screen (2).
- Additional panel is created at the top of screen 1 (intention is to trick it to be on the correct screen (2)).
- First panel jumps to screen 3, a completely separate screen from any of this so far.
- Attempting to move the top panel back to screen 2 (by choosing 1 for the trick) the bottom panel jumps to screen 3.
- Top and bottom panel will not play nice and be on the same screen.

**Comment by mtwebster** [comment]
Try running the following:
```
gsettings get org.cinnamon panels-enabled
```
You should get a list of entries like:
```
['1:0:bottom', '2:0:top', '4:1:bottom']
```
If you only have one monitor and one panel in the bottom position, you'd get:
```
['1:0:bottom']
```
(Panel ID 1, monitor 0, bottom of screen)

**The size of this list should be the same as the number of panels the user currently has**

I've been able to reproduce similar issues with panel manipulation, as a result of having more entries there than I have panels (and having overlapping definitions)

A quick test is to run:
```
gsettings reset org.cinnamon panels-enabled
```

Cleaning up that settings key fixed the issue I was having.

*Again, I'm not sure if this is the same issue, but it's something to check.*

Also, there was an update to cinnamon-control-center yesterday to address the mis-labeling of monitors when configuring their layout  in Display settings.

Also, resetting panels *shouldn't* reset their configuration, or what applets are on it. Once you re-add panels, your applets should still be there and in the same positions.

**Comment by floresod** [comment]
> ```
> gsettings reset org.cinnamon panels-enabled
> ```


I tried this and the problem persists.

**Comment by amouiche** [comment]
Hello,

> gsettings reset org.cinnamon panels-enabled

doesn't do anything for me, but I'm able to configure thinks manually.
Here is an example.

I have 2 monitors. starting with one panel, I have

$ gsettings get org.cinnamon panels-enabled
['1:0:bottom']

Adding a second panel the 2nd monitor switch the first panel to the
second monitor and add a new empty in my main monitor. As we can see,
the gsetting content is wrong.
$ gsettings get org.cinnamon panels-enabled
['1:1:bottom', '2:0:bottom']

Updating manually the gsetting fix the order

$ gsettings set  org.cinnamon panels-enabled "['1:0:bottom', '2:1:bottom']"

Regards,
Arnaud

**Comment by brian22333** [comment]
Running the gsettings get command for the one main panel on the bottom of the primary screen shows
1:0:bottom

Trying to add a panel to the top of that primary screen (which shows as screen 2 for some reason in display settings, unable to change) I then have both panels jump to screen 3 and the settings show:
1:1:bottom, 2:1:top

Moving the bottom panel and clicking on screen 2 bottom moves it back to screen 1 (primary), with the top panel jumping to screen 2 and the settings then show
1:0:bottom 2:2:top

Resetting settings unfortunately does not resolve the issue.

Entering Arnaud's command:
gsettings set org.cinnamon panels-enabled "['1:0:bottom', '2:0:top']" did allow for both to be on the main screen properly!

**Comment by aledef** [comment]
I'm also experiencing this issue on Mint 21.3 Cinnamon v 6.0.4

**Comment by AKFrancq** [comment]
Also experiencing this issue on a fresh install

**Comment by cuceda** [comment]
I'm experiencing the same issue.
I have 2 screens and 2 panels. Whenever I drag either of them both of them jump to the other screen. Really annoying.

**Comment by itzZenti** [comment]
Also having this issue on 6.0.4 
Cinnamon 21.3

**Comment by agr8lemon** [comment]
I'm having the same issue, Mint 21.3, Kernel 5.15.0-112.

**Comment by CiroPen** [comment]
Can confirm this issue is **still present** on a fresh install of mint 21.3 as well, no workarounds discussed here worked.

**Comment by hajenso** [comment]
I'm also having this issue on a fresh install of Mint 21.3.

**Comment by noah-foltz** [comment]
+1 Can confirm this is still a problem

Mint 21.3
Cinnamon 6.0.4
Kernel 5.15.0-112-gen

**Comment by Meganekun98** [comment]
still an issue 


Linux Mint 21.3 Cinnamon
version: 6.0.4
kernel: 5.15.0-91-generic
Graphics hardware: Radeon Vega mobile
CPU: AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx × 4
I'm Using laptop ASUS Vivobook 14 X412DA


I tried to reset using the command provided
`gsettings reset org.cinnamon panels-enabled`
but it created another problem 
the panel seem to have inverted
when changing panel appearance of Right Zone it changes appearance of the Left Zone

https://github.com/linuxmint/cinnamon/assets/41239443/310f0d81-93aa-40bf-9edb-e7e7584829aa

**Comment by priit123** [comment]
Same issue.

**Comment by ysoyloco** [comment]
still an issue :/ Thinkpad t480s intelHD

**Comment by DenisBalan** [comment]
same issue, wondering why this is closed? Cinnamon 6.2.9

**Comment by emailforos** [comment]
Same issue, here.

Mint 21.3
Cinnamon 6.0.4
Kernel 5.15.0-119-gen

I don't know if this is solved in Mint 22 but in theory Mint 21.3 support is up to 2027 so closing an existing bug...

**Comment by Fry-kun** [comment]
I have the same issue, using Cinnamon `6.0.4`.
When I manually apply the attached fix to `panel.js`, behavior stays the same -- so the fix is insufficient

**Comment by VerbenaZero** [comment]
I was also experiencing this issue on a fresh install of Debian 12 with an Nvidia 3060 and two side-by-side monitors.   When I installed the official NVIDIA drivers from the Debian repository and removed the Nouveau drivers this issue resolved itself.  Not a true solution, and doesn't help anyone with AMD cards that may be experiencing this issue.  But another data point.

**Comment by cfpbiggs** [comment]
I am having this same issue with the panel not moving to my non-primary display, but my display numbering seems to match between my display settings and the enumeration of the screens up in the corners. 
<img width="7680" height="2160" alt="Image" src="https://github.com/user-attachments/assets/d519d2e8-5bc7-4149-a539-13ac5384204a" />

With that said, running the gsettings command does show that the enumeration within the terminal is offset by 1 from the enumeration in the display settings, so it is possible that the issue lies there.
<img width="7680" height="2160" alt="Image" src="https://github.com/user-attachments/assets/a3ba4e3d-48b2-411b-85b4-5a6912d1501c" />

Unfortunately the gsettings reset did not clear up my issue.

I actually have a lot of problems with my second monitor (running Linux Mint 22.3 with Cinnamon 6.6.7 environment). The second monitor does not turn off, does not allow panels (as this thread notes), and when I try to fullscreen VirtualBox, it always reverts the application to being on the primary monitor (thus blocking my panel). This is the main reason I'm actually trying to get my panel to move as when I have VirtualBox fullscreened, I have no way to quickly access the panel.

**Comment by keikoro** [comment]
In my case, the panel only recently unexpectedly switched to my secondary display.

> I am having this same issue with the panel not moving to my non-primary display, but my display numbering seems to match between my display settings and the enumeration of the screens up in the corners.

Same here.

I just managed to fix the issue on my end by clicking on the "Set as Primary" button for my primary display, i.e. _the one already labelled "1"_, in the Display settings. That made the panel move and now the button is greyed out.

> With that said, running the gsettings command does show that the enumeration within the terminal is offset by 1 from the enumeration in the display settings, so it is possible that the issue lies there.

I'd assume the terminal command uses zero-based numbering common in computing whereas the "Display" settings, being a GUI for end users, start counting from 1. So I don't think that's the problem.
