### ISSUE TITLE
Cinnamon-Settings Display showing wrong monitor numbers

### ISSUE THREAD

**Issue by PaganDegree** [linuxmint/cinnamon#12025]
### Distribution

Mint 21.3

### Package version

6.0.4

### Graphics hardware in use

AMD Radeon RX 7900 XTX

### Frequency

Always

### Bug description

After updating to Mint 21.3, Cinnamon 6.0.4, with kernel 6.5, the Cinnamon-Settings Display app no longer shows the correct monitor numbers in a multi-monitor output in the graphical representation of the monitors vs the drop down list.  
1 is missing, 3 is 2, and 2 is 1
![Screenshot from 2024-01-15 07-20-50](https://github.com/linuxmint/cinnamon/assets/34691012/2677bbb0-f206-4a0c-81bb-98c2405099ff)
Screenshot attached
This appears to be some kind of regression bug because this was not a problem before 21.3.

### Steps to reproduce

Just open Display to look at monitor layout

### Expected behavior

Numbers from drop down list should match the numbers on the graphical display.

**Comment by mtwebster** [comment]
Was this in an x11 session or wayland?

**Comment by PaganDegree** [comment]
X11

**Comment by timur-g** [comment]
Is it so only for 3 monitors, or also with 2?

**Comment by PaganDegree** [comment]
Also happens on 2 monitors
![Screenshot from 2024-01-16 08-10-19](https://github.com/linuxmint/cinnamon/assets/34691012/6a3f12ba-1588-46ec-a926-258b9a881333)

**Comment by nalmada** [comment]
Can reproduce with 2 or 3 displays, since 21.3
Seems that screen number now start at 0 so everything if shifted by -1 and the UI is buggy for the first screen 

![image](https://github.com/linuxmint/cinnamon/assets/10788696/bde5cec8-13a2-4673-9e49-8d9f6c9499eb)
