### ISSUE TITLE
Malware detected in wine installed using Mint's Software Manager

### ISSUE THREAD

**Issue by Xenophobe-01** [linuxmint/cinnamon#12026]
### Distribution

Mint 21.2 Cinnamon

### Package version

5.8.4

### Graphics hardware in use

RX 6950 XT

### Frequency

Always

### Bug description

I have ClamAV setup to do a weekly scan of my drives and it detected the following:

/home/name/.wine/drive_c/windows/system32/winver.exe: Win.Malware.Ulise-10018340-0 FOUND
/home/name/.wine/drive_c/windows/syswow64/winver.exe: Win.Malware.Ulise-10018340-0 FOUND

I sent the files in for ClamAV's team to analyze and they confirmed them as threats. I have not used regular wine in a while as steam proton handles my gaming needs.

This is the wine 6.0.3~repack-1 system package in Linux Mint's Software Manager. There have been no updates to this wine version in Update Manager since installation. The detection was Jan 14, 2024.

I uninstalled wine and deleted the .wine folder, ran sudo apt autoremove --purge && sudo apt autoclean, then reinstalled wine from Software Manager to test and ClamAV again flagged these files as malware threats.

Virus Total also has these listed as threats ... https://www.virustotal.com/gui/file/8b81da285744f5829b68a250737ca0c4fcd0933a0ec02e9fcce6e73be24dfbf7

### Steps to reproduce

Install wine 6.0.3~repack-1 system package from Linux Mint's Software Manager;
Setup wine;
Run ClamAV to scan the .wine folder.

### Expected behavior

No malware being installed with Software Manager.

**Comment by CrimsonXMC** [comment]
For 1, why are you running a Windows antivirus on Linux? For 2, It's what is called a false positive. It will be detected as malware because the antiviruses think it's a modified windows system file when it in fact is a custom executable with the same name. That's why only absolutely garbage antiviruses are detecting it as a virus.

**Comment by leigh123linux** [comment]
File the issue at https://github.com/linuxmint/mintinstall

**Comment by Xenophobe-01** [comment]
> For 1, why are you running a Windows antivirus on Linux? For 2, It's what is called a false positive. It will be detected as malware because the antiviruses think it's a modified windows system file when it in fact is a custom executable with the same name. That's why only absolutely garbage antiviruses are detecting it as a virus.

ClamAV is designed for unix and linux, just because it also supports windows doesn't make it a windows antivirus. https://docs.clamav.net/Introduction.html#supported-platforms

**Comment by Xenophobe-01** [comment]
> File the issue at https://github.com/linuxmint/mintinstall

reported at mintinstall, thank you.
