### ISSUE TITLE
"Util.each is not a function" error

### ISSUE THREAD

**Issue by Kladizkov** [linuxmint/cinnamon#12024]
After an upgrade I'm getting this error and menu doesn't show up.

```
error t=2024-01-13T21:33:18Z 
[menu@cinnamon.org]: Util.each is not a function
[menu@cinnamon.org]: Failed to evaluate 'main' function on applet: menu@cinnamon.org/15
```

How do I fix this error? Please help.

**Comment by fredcw** [comment]
Which version of cinnamon (`cinnamon --version`) and which distro?

**Comment by Kladizkov** [comment]
I'm having cinnamon 6.0.4

$ cinnamon --version
Cinnamon 6.0.4

I have menu@cinnamon.org in ~/.local/share/cinnamon/applets. Should I remove it?
