### ISSUE TITLE
Cinnamon's CPU load rises when other applications are busy

### ISSUE THREAD

**Issue by autarkper** [linuxmint/Cinnamon#1203]
I'm seeing a strange phenomenon on my laptop and my desktop machine: As soon as another application starts some presumably graphics-intensive activity, Cinnamon's CPU usage rises to about the same level as the other application.

Steps to reproduce:
1) Observe Cinnamon's CPU utilization for while and take note of the approximate idle average CPU % used.
2) Start Audacity.
3) In Audacity, start a recording.
4) Repeat the first step.

Expected outcome: Cinnamon's idle CPU utilization should not be any higher than before.
Actual outcome: Cinnamon's idle CPU utilization is higher than that of Audacity, just slightly lower than that of Xorg.

On my laptop, the figures are (measured with Conky):
1) Xorg: 12-15%
2) Cinnamon: 10-13%
3) Audacity: 8-11%

Before the experiment, Cinnamon's CPU usage was 1-3%. That's a huge difference!

Update: Originally I could only check on my laptop, Cinnamon 1.6/LMDE. I have now checked on my desktop machine, Cinnamon 1.6.1/Ubuntu 12.04, and it exhibits the same behavior.

Update (March 2013): This is still very much an issue in Cinnamon 1.7.2.

**Comment by Vahan86** [comment]
@autarkper,  is this still an issue for you in Cinnamon 3.0?

**Comment by autarkper** [comment]
@Vahan86, sorry I cannot tell, I no longer run Cinnamon.

**Comment by Vahan86** [comment]
@autarkpern, thanks for reply. In this case can you  please close the issue?
