### ISSUE TITLE
Shutdown and disconnect menu icons have no effect when multiple users are logged in

### ISSUE THREAD

**Issue by simx-bb** [linuxmint/cinnamon#12039]
### Distribution

Mint21.3

### Package version

6.0.4

### Graphics hardware in use

Integrated Intel 1235U GPU - Iris® Xe Graphics

### Frequency

Always

### Bug description

Logout and shutdown menu icons have no effect if multiple sessions are open (2 users are logged in)

### Steps to reproduce

- create a second user account
- click the disconnect icon and select change user from the user1 session
- login with user2
- click menu > shutdown icon: nothing happens
- click menu > disconnect icon: nothing happens

### Expected behavior

both icons normally open a multiple choice window (e.g. to reboot / shutdown / disconnect...)

**Comment by leigh123linux** [comment]
Duplicate of #12021
