### ISSUE TITLE
Cinnamon sound applet: Mute toggle with middle click is not working

### ISSUE THREAD

**Issue by kelebek333** [linuxmint/cinnamon#12035]
### Distribution

Mint 21.3

### Package version

6.0.4

### Frequency

Always

### Bug description

Mute toogle with middle click is not working for sound applet.

`JS ERROR: TypeError: this._input is null
_onButtonPressEvent@/usr/share/cinnamon/applets/sound@cinnamon.org/applet.js:1244:25`

### Steps to reproduce

.

### Expected behavior

.

### Additional information

.

**Comment by claudiux** [comment]
Please try replacing in 5.4/applet.js, each line `if (this._output.is_muted === this._input.is_muted)` by:

`if (this._input && this._output && this._output.is_muted === this._input.is_muted)`

(lines 1231 and 1242)

**Comment by claudiux** [comment]
@kelebek333 Please try the sound150@claudiux applet v5.1.1
https://cinnamon-spices.linuxmint.com/applets/view/306

**Comment by kelebek333** [comment]
> Please try replacing in `/usr/share/cinnamon/applets/sound@cinnamon.org/applet.js`, each line `if (this._output.is_muted === this._input.is_muted)` by:
> 
> `if (this._input && this._output && this._output.is_muted === this._input.is_muted)`
> 
> (lines 1231 and 1242)

Hi @claudiux ,

Your fix is working, issue solved . Thanks.


> @kelebek333 Please try the sound150@claudiux applet v5.1.1 https://cinnamon-spices.linuxmint.com/applets/view/306

Sound %150's mute toggling with middle click is working.
