### ISSUE TITLE
Unexpected error appers when installing app from Software manager on Linux Mint

### ISSUE THREAD

**Issue by JuraLys** [linuxmint/cinnamon#12045]
### Distribution

Mint 21.3 mate

### Package version

Cinnamon 5.2.7-4

### Frequency

Quite often

### Bug description

see screenshots 
![mint-soft-install-hang(](https://github.com/linuxmint/cinnamon/assets/146434286/ab169488-619a-4b5f-81ef-a1384583a50a)
![mint-soft-install(](https://github.com/linuxmint/cinnamon/assets/146434286/7616b126-6dcf-4633-9748-9001e9d27441)

### Steps to reproduce

open Software manager on Linux Mint and search Download word
click found app title and click Install button

### Expected behavior

selected app should be installed without errors

### Additional information

Linux Mint 5.15.0-91

**Comment by leigh123linux** [comment]
File the issue against the software manager.

**Comment by JuraLys** [comment]
> File the issue against the software manager.

please provide link for it.

**Comment by leigh123linux** [comment]
https://github.com/linuxmint/mintinstall/issues
