### ISSUE TITLE
Unexpected error appears in Synaptic when clicking Reload button on Linux Mint

### ISSUE THREAD

**Issue by JuraLys** [linuxmint/cinnamon#12047]
### Distribution

Mint 21.3 mate

### Package version

Cinnamon 5.2.7-4

### Frequency

Always

### Bug description

see screenshot 
![mint-synaptic-err(](https://github.com/linuxmint/cinnamon/assets/146434286/1e35afac-9567-4ff9-8ee9-cd4a622b48af)

### Steps to reproduce

Run Synaptic and click Reload button

### Expected behavior

Package list should be reloaded

### Additional information

Linux Mint 5.15.0-91

**Comment by JuraLys** [comment]
> This isn't a cinnamon issue.

please write link where I can create this issue.

**Comment by leigh123linux** [comment]
https://launchpad.net/ubuntu/+source/synaptic/+bugs
