### ISSUE TITLE
The "exec" and "eval" command seem to drop the HOME environment in the new session

### ISSUE THREAD

**Issue by robinkaty** [linuxmint/cinnamon#12046]
### Distribution

LMDE 6 Linux lmdetest 6.1.0-12-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.52-1 (2023-09-07) x86_64 GNU/Linux

### Package version

5.8.4

### Graphics hardware in use

Proxmox

### Frequency

Always

### Bug description

When trying to span a tigervnc session from systemctl it appears that the "exec" function is not sending a complete environment to the session. The HOME variable is not being set for normal users, root seems to work.
root@lmdetest:~# journalctl -fu tigervncserver@:2.service
Jan 24 00:22:58 lmdetest vncserver[9417]: Tigervncserver starting:
Jan 24 00:22:58 lmdetest tigervncsession[9430]: pam_unix(tigervnc:session): session opened for user rgranger(uid=1000) by (uid=0)
Jan 24 00:22:58 lmdetest systemd[1]: Started tigervncserver@:2.service - Remote desktop service (VNC).
Jan 24 00:22:59 lmdetest tigervncsession[9430]: tigervncsession: tigervncserver exited with status=255
Jan 24 00:22:59 lmdetest tigervncsession[9430]: pam_unix(tigervnc:session): session closed for user rgranger
**Jan 24 00:22:59 lmdetest vncserver[9545]: vncserver: The HOME environment variable must be set.**
Jan 24 00:22:59 lmdetest vncserver[9545]: Tigervncserver starting:
Jan 24 00:22:59 lmdetest systemd[1]: tigervncserver@:2.service: Control process exited, code=exited, status=1/FAILURE
Jan 24 00:22:59 lmdetest systemd[1]: tigervncserver@:2.service: Failed with result 'exit-code'.

### Steps to reproduce

This works
/usr/sbin/tigervncsession rgranger :2
This does not
eval /usr/sbin/tigervncsession root :3

### Expected behavior

Both of the above examples should work, the one for a normal user fails with the error:
root@lmdetest:~# journalctl -fu tigervncserver@:2.service
Jan 24 00:22:58 lmdetest vncserver[9417]: Tigervncserver starting:
Jan 24 00:22:58 lmdetest tigervncsession-start[9420]: HOME:/home/rgranger
Jan 24 00:22:58 lmdetest tigervncsession[9430]: pam_unix(tigervnc:session): session opened for user rgranger(uid=1000) by (uid=0)
Jan 24 00:22:58 lmdetest systemd[1]: Started tigervncserver@:2.service - Remote desktop service (VNC).
Jan 24 00:22:59 lmdetest tigervncsession[9430]: tigervncsession: tigervncserver exited with status=255
Jan 24 00:22:59 lmdetest tigervncsession[9430]: pam_unix(tigervnc:session): session closed for user rgranger
Jan 24 00:22:59 lmdetest vncserver[9545]: vncserver: The HOME environment variable must be set.
Jan 24 00:22:59 lmdetest vncserver[9545]: Tigervncserver starting:
Jan 24 00:22:59 lmdetest systemd[1]: tigervncserver@:2.service: Control process exited, code=exited, status=1/FAILURE
Jan 24 00:22:59 lmdetest systemd[1]: tigervncserver@:2.service: Failed with result 'exit-code'.

**Comment by leigh123linux** [comment]
File the issue against tigervncserver, it's not cinnamon's job to set.
