### ISSUE TITLE
Cinnamon goes back to Login Screen during Celluloid video playback

### ISSUE THREAD

**Issue by TobiZog** [linuxmint/cinnamon#12051]
### Distribution

Mint 21.3

### Package version

6.0.4

### Graphics hardware in use

Advanced Micro Devices, Inc. [AMD/ATI] Rembrandt

### Frequency

Quite often

### Bug description

I watched some videos with Celluloid in Full Screen mode. Sometimes (every 20-60 minutes) hangs the video (but sound works fine) for a couple of seconds. After that, the screen gets dark, the video sound stops and the Login screen of Cinnamon appears. The session was fully closed...

See also the log file:
[log messages.txt](https://github.com/linuxmint/cinnamon/files/14065974/log.messages.txt)

### Steps to reproduce

Play a video with Celluloid, wait some times until the bug happens.

### Expected behavior

Don't logout

**Comment by leigh123linux** [comment]
celluloid is crashing X, it's either a kernel or driver issue.

You will need to file the issue at.

https://github.com/linuxmint/linuxmint/issues
