### ISSUE TITLE
Redshift indicator on Notification Area says 0K, period: unknown. but when click redshift info actually working (4500K)

### ISSUE THREAD

**Issue by Reno-Sifana** [linuxmint/cinnamon#12068]
### Distribution

Linux Mint 21.3

### Package version

6.0.4

### Graphics hardware in use

Intel HD Graphics

### Frequency

Only occasionally

### Bug description

Sometimes Redshift Indicator on Notification Area says color temperature is 0K, Period: unknown with unknown reason. but whin i clicked Redshift Info it's says correct value (4500K) as described Screenshot Below 
![Screenshot from 2024-02-04 20-06-49](https://github.com/linuxmint/cinnamon/assets/68702583/09d4ad51-22ad-41dc-bafa-ce003f42c515)
![Screenshot from 2024-02-04 20-07-26](https://github.com/linuxmint/cinnamon/assets/68702583/db61995d-086f-49bd-ac00-868ae5017666)

### Steps to reproduce

I'm Just run automatically at startup and running in background

### Expected behavior

@clefebvre @mtwebster it's should be fixed in Cinnamon updates (e.g Cinnamon 6.0.5)

**Comment by leigh123linux** [comment]
File the issue against the thirdparty redshift applet

**Comment by Reno-Sifana** [comment]
> File the issue against the thirdparty redshift applet or redshift app.

Okay. understandable. I'm just using redshift-gtk preinstalled with Linux Mint. none third party applet i have tested. sorry.

**Comment by leigh123linux** [comment]
> > File the issue against the thirdparty redshift applet or redshift app.
> 
> Okay. understandable. I'm just using redshift-gtk preinstalled with Linux Mint. none third party applet i have tested. sorry.

Ubuntu repo provides redshift-gtk package, you would need to file the issue there.
