### ISSUE TITLE
Creating an additinional 2nd admin user causes 1st users fsencrypt to not associate with user.

### ISSUE THREAD

**Issue by jebbgrenham** [linuxmint/cinnamon#12063]
### Distribution

20.1

### Package version

4.8.6

### Graphics hardware in use

NVS 5400M

### Frequency

Always

### Bug description

Discovered bug after using mint long term then adding a 2nd user. If you create a 2nd admin user, decryption of the home folder will stop working for the 1st user.

### Steps to reproduce

1. INSTALL
- Install 20.1 (or upgrade from earlier).
- Choose FDE for install but also ECRYPTFS the home dir, and have /home/ on a 2nd hard drive (at least that's my case...)

2. USE
- Use the system normally for some time, create some files in the homedir of user1

3. BUG
- Using your original admin user1, create a NON-admin 2nd user named user2
- Using your original admin user1, change that user to an admin user.
- Log out of user1
- Log in as user 2
- Log out of user 2
- Log in to user1

4. BAD NEWS
- Your home directory is no longer decrypting, and you will be presented with a cinnamon desktop as if you had just created a new user with no files.

### Expected behavior

User 1 should be able to log in normally and access encrypted home

**Comment by leigh123linux** [comment]
Your version is 'end of life', please reopen if you can reproduce with cinnamon-6.x.x
