### ISSUE TITLE
Specified notification monitor number doesn't match display monitor number

### ISSUE THREAD

**Issue by alextpedro** [linuxmint/cinnamon#12064]
### Distribution

Mint 21.3

### Package version

Cinnamon 6.0.4

### Graphics hardware in use

NVIDIA GeForce GTX 1660

### Frequency

Always

### Bug description

In the notification settings, when selecting `Monitor to use for displaying notifications`, the number in the box doesn't match with the numbers assigned to the monitor overlays in the Display settings.

I suspect that the monitors are being counted differently for the overlays, the numeration inside Display, and in messageTray.js.

The way I see it, a user would see the Notification settings asking for a number and would (hopefully) go check the Display settings for the monitor number. 

Oh and monitor numbers start from 0 but the Notification settings don't let the user input 0. 

### Steps to reproduce

1. Open Notifications
2. Change Monitor to use for displaying notifications to The monitor specified below
3. Open Display
4. Check that the desired monitor is labeled in the big overlay as 2
5. Input 2 
6. Display a test notification
![Screenshot from 2024-02-02 19-53-53](https://github.com/linuxmint/cinnamon/assets/5782944/35765ca0-d7fe-456f-a69b-4fd1880caf83)

### Expected behavior

I expect that if I put in monitor 2 the notification shows up on the monitor that the Display labels as 2. Alternatively, Display should label it appropriately as 1, with the main monitor as 0, and Notifications should allow the user to input 0 as the number.

### Additional information

This setting is actually confusing for new users. In an ideal world, they would select which monitor they want from a graphical representation, instead of putting in numbers they might not know how to find or relying on trial and error.

**Comment by Klaustrix** [comment]
Think we're all having the same issues stemming from the same problem around display miss-matches.
https://github.com/linuxmint/cinnamon/issues/12017
