### ISSUE TITLE
mintinstall can't install packages within xsession.

### ISSUE THREAD

**Issue by Kreijstal** [linuxmint/cinnamon#12070]
### Distribution

Mint 21.3

### Package version

Cinnamon 6.0.4

### Graphics hardware in use

xrdp-xsession

### Frequency

Always

### Bug description

Can't install any package from mintinstall, no password asked, it attempts, then it gives up.

### Steps to reproduce

Fresh install.
Donwload ssh, set sshkey
create new user add to most groups, same as original user.
restart
log in as new user 
install xdrp
create new file with contents:
```
[Allow colord for all users]

Identity=unix-user:*
Action=org.freedesktop.color-manager.create-device;org.freedesktop.color-manager.create-profile;org.freedesktop.color-manager.delete-device;org.freedesktop.color-manager.delete-profile;org.freedesktop.color-manager.modify-device;org.freedesktop.color-manager.modify-profile;org.freedesktop.packagekit.system-sources-refresh
ResultAny=yes
ResultInactive=yes
ResultActive=yes
```
to /etc/polkit-1/localauthority/50-local.d/color.pkla
get into xdrp
open mintinstall
try to install anything

### Expected behavior

It should install or at least write an error message.

### Additional information

I updated from mint 21.2 to mint 21.3. aptitutde from terminal can do everything, fortunately

**Comment by leigh123linux** [comment]
This is a polkit limitation and isn't something that can be fixed within cinnamon.
I suggest you google or ask at linuxmint forum for a possible solution.

**Comment by Kreijstal** [comment]
not sure if it is a limitation or a misconfiguration but posting more information
journalctl:
```
Feb 05 18:15:47 k-NUC13ANHi7 systemd[1]: Started Authorization Manager.
Feb 05 18:15:47 k-NUC13ANHi7 PackageKit[3620]: uid 1001 failed to obtain auth
Feb 05 18:15:47 k-NUC13ANHi7 polkitd(authority=local)[11011]: Registered Authentication Agent for unix-session:c3 (system bus name :1.94 [/usr/lib/policykit-1-gnome/polkit-gnome-authenticatio>
Feb 05 18:
```
and some auth logs
```
Feb  5 18:15:47 k-NUC13ANHi7 PackageKit: uid 1001 is trying to obtain org.freedesktop.packagekit.package-install auth (only_trusted:1)
Feb  5 18:15:47 k-NUC13ANHi7 PackageKit: uid 1001 failed to obtain auth
Feb  5 18:15:47 k-NUC13ANHi7 polkitd(authority=local): Registered Authentication Agent for unix-session:c3 (system bus name :1.94 [/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1], object path /org/gnome/PolicyKit1/AuthenticationAgent, locale de_DE.UTF-8)
```
Not sure if it is a mint problem, or just really misconfigured
