### ISSUE TITLE
Installing extensions automatically activates them partly

### ISSUE THREAD

**Issue by schorschii** [linuxmint/cinnamon#12075]
### Distribution

Mint 21.3

### Package version

6.0.4

### Graphics hardware in use

NVIDIA Quadro P4000 with proprietary driver

### Frequency

Always

### Bug description

When installing an extension on the "Download" tab, it gets automatically activated. But on the "Manage" tab, it does not seem to be active ("Enable" button is clickable for the downloaded extension while "Disable" and "Extension Settings" are not).

### Steps to reproduce

Download e.g. the "Transparent Panels" from the "Download" tab. You'll see that the panel gets transparent directly after the download finished. Now, switch to the "Manage" tab. There you cannot open the extension settings (button disabled). You only can activate the extension again. After that, it is possible to access the extension settings.

### Expected behavior

Extensions should not be activated automatically after download.

**Comment by anaximeno** [comment]
I can confirm, I also had this issue.

**Comment by mortim** [comment]
I'd add also that the extension is still enabled even when it has been uninstalled

To reproduce that : You have to install the extension and remove it just after

I tried with theses extensions:
- https://cinnamon-spices.linuxmint.com/extensions/view/77
- https://cinnamon-spices.linuxmint.com/extensions/view/95
