### ISSUE TITLE
Font settings text scaling factor <> 1,0 causes an app crash when editing a bookmark in Chromium, Brave..

### ISSUE THREAD

**Issue by cdet67** [linuxmint/cinnamon#12082]
### Distribution

Mint 21.3 / LMDE6

### Package version

6.0.4

### Graphics hardware in use

Intel, AMD or Nvidia (different PCs)

### Frequency

Always

### Bug description

When in Fonts settings the "text scaling factor" is set different than 1,0 in Chromium it is not possible to edit a bookmark.
When clicking on  edit bookmark  the main chromium window starts flickering and after a while the app crashes.
That happens in Mint 21.3 and also in LMDE6 with cinnamon 6 on different hardware.

Same flicker problem when trying to install a extension in chromium (not for all extensions though).

The problem is reproducable on different notebooks, reboot doesn't change problem

### Steps to reproduce

Change System settings / Font settings / text scaling factor to 1,2 
Start chromium browser. 
Right-click on a Bookmark in Baookmark bar.
Click edit bookmark.
Issue: Chromium window starts to flicker, like permanently resizing. Key and mouse doesn't respond in the (edit) window.

Same flicker happens with Brave browser, but there a click in the bookmark editing window stops the flicker.

### Expected behavior

normal behaviour

### Additional information

The flickering window occurs in chromium (system package) and in Brave (Flatpack), but not with Firefox.
Setting back the text scaling factor to 1,0 , the problem is gone.

**Comment by mtwebster** [comment]
This occurs on other desktops as well (I tested MATE and gnome-shell).

It looks like it may be this bug:
https://issues.chromium.org/issues/324934135

I've added observations from my testing to the issue.
