### ISSUE TITLE
Updating Firefox not working correctly

### ISSUE THREAD

**Issue by Synix4Life** [linuxmint/cinnamon#12087]
### Distribution

Linux Mint 21.3 Cinnamon

### Package version

6.0.4

### Graphics hardware in use

Advanced Micro Devices, Inc. [AMD/ATI] Lucienne (Integreated AMD Raedon Graphics on the CPU Chip afaik)

### Frequency

Always

### Bug description

Hi, i have a problem while updating Firefox through the Update Manager. 
In general, the Update Manager works fine and installs applications with an exceptional speed, but not Firefox. Firefox takes ages to install, most of the times with < 1 kByte/s and then often fails with an error, like "Package can't be installed because of package loss" (or something like that, unfortunately i don't have the error on my hand right now). All other applications, even when they are installed in the same process as Firefox, download with the usual speed and no Problems occur. I've tried everything so far what I know, like restarting, clearing cache and so on, but it still doesn't work. 
![ff](https://github.com/linuxmint/cinnamon/assets/116163789/3ff1c22e-9a4b-479d-9c6d-f5966118b739)

### Steps to reproduce

Unfortunately, I can't really give you an explanation on reproduction, because i don't even know why it is happening

### Expected behavior

Well, it should install with the same speed as all other applications

### Additional information

I've had two different Linux Mint installations on my device as of now, and it occurred in both, so i don't think it has anything to do with a failed install. 
The installations have also both been from different Mirror websites

**Comment by leigh123linux** [comment]
File the issue at

https://github.com/linuxmint/mintupdate/issues

**Comment by mtwebster** [comment]
In the screenshot you're using the default mint mirror. A new firefox was released this morning, which generates a *lot* of traffic, and has been causing these issues (it's being worked on).

Other mirrors I can't say, but it wouldn't surprise me if this was also affecting at least some of them.
