### ISSUE TITLE
upgraded Linux MINT from 20.3 to 21.1: MINT 21.x does not recognize former SDA any more although boot runs till Grub

### ISSUE THREAD

**Issue by 12m18** [linuxmint/cinnamon#12088]
### Distribution

MINT 21.x

### Package version

5.4.12

### Frequency

Always

### Bug description

Hi all,

after having discussed my issue within a German forum I have been advised to document the issue here.
As I have just signed in to GitHub the first time I am not sure whether I have found the proper place to do so .
But I will try. Maybe someone is aware of a solution. Sorry for potentially bad English as I am not a native speaker.

Since years I have run MINT (Cinnamon) without problems and also upgraded from 18 to 19 to 20.
Recently I have tried to upgrade to MINT 21.1.
The upgrade process went well and finished with a message of success - just necessary to reboot the computer.
And that is where the trouble began.
The reboot just reached the Grub menu. After having selected the OS the MINT symbol showed up on the screen and the boot process ended up with an initramfs screen.
Of course the mentioned UUID is the proper one !
The crazy thing was that GParted from a MINT 21 life system also did not list the former SDA (thus an installation from scratch - being the worst case - was also excluded).
But GParted from a Knoppix 9 life system did list the HD. Also RedoRescue 4 did (thank God - otherwise I would not have been able to restore the MINT 20.3 image).

Cloning the system from the old Western Digital HD to a Seagate HD and using the Seagate HD did not help. The HD simply was invisible.
After some experiments I have found out that attaching the HD to a different SATA port made the difference.
The computer (HP Z620) provides 6 AHCI SATA connectors. Two of them offer 6 GB/s, four of them offer only 3 GB/s.
In the past (before the upgrade) my boot HD (including the MINT installation) was connected to a 6 MB/s connector.
This not working any more after the upgrade the HD is now connected to a 3 GB/s connector - and MINT 21.3 is running.
Unfortunately I have to accept a significant loss of performance now which is annoying.
Maybe this is a missing piece of hardware support in MINT 21.x in comparision to MINT 20.x ?

I have attached a file containing some details (e.g. inxi) about my machine.
Unfortunately I am not a hardware expert. Thus I had to use the documentation within the HP manual in respect to the SATA ports.

Update:
After having added an extra PCI-e card including four SATA 6GB/s ports and having connected SDA to one of these MINT 21.1 is able to detect all disks. Looks like Mint 21.x has a problem regarding the onboard SATA 6GB/s connections from HP.

### Steps to reproduce

I have tried out all SATA ports with several harddisks (formatted, not formatted, different manufacturer, different sizes, different MINT-versions)

### Expected behavior

MINT 21.x shoul be able to use the harddisk (including connection) that MINT 19.x and 20.x have used before the upgrade

### Additional information

Summary of Upgrade-Protocol (looks fine):

update-initramfs -u
update-initramfs: Generating /boot/initrd.img-5.15.0-91-generic
I: The initramfs will attempt to resume from /dev/sda4
I: (UUID=087d21cf-a2cd-4c95-bb00-e63edcd7c41d)
I: Set the RESUME variable to override this.
Check succeeded:  Letzte Phase
Upgrade successful! You can now close this terminal and reboot your computer.

--------------------------------------------------------------------------------------

System configuration before Upgrade (HD Western Digital having been used from MINT 18 on until MINT 20.3)

inxi MINT 20.3 (Western Digital model: WD2005FBYZ-01YCBB3)

rolf@home-4:~$ inxi -Fz
System:
  Kernel: 5.4.0-169-generic x86_64 bits: 64 Desktop: Cinnamon 5.2.7 
  Distro: Linux Mint 20.3 Una 
Machine:
  Type: Desktop System: Hewlett-Packard product: HP Z620 Workstation v: N/A 
  serial: <filter> 
  Mobo: Hewlett-Packard model: 158A v: 0.00 serial: <filter> 
  UEFI: Hewlett-Packard v: J61 v03.96 date: 10/29/2019 
CPU:
  Topology: 2x 6-Core model: Intel Xeon E5-2620 0 bits: 64 type: MT MCP SMP 
  L2 cache: 30.0 MiB 
  Speed: 1197 MHz min/max: 1200/2500 MHz Core speeds (MHz): 1: 1197 2: 1197 
  3: 1197 4: 1197 5: 1197 6: 1197 7: 1197 8: 1197 9: 1197 10: 1197 11: 1197 
  12: 1196 13: 1197 14: 1197 15: 1197 16: 1197 17: 1197 18: 1197 19: 1197 
  20: 1197 21: 1197 22: 1198 23: 1197 24: 1197 
Graphics:
  Device-1: NVIDIA GK106GL [Quadro K4000] driver: nvidia v: 470.223.02 
  Display: x11 server: X.Org 1.20.13 driver: nvidia 
  unloaded: fbdev,modesetting,nouveau,vesa resolution: 1920x1080~60Hz 
  OpenGL: renderer: Quadro K4000/PCIe/SSE2 v: 4.6.0 NVIDIA 470.223.02 
Audio:
  Device-1: Intel C600/X79 series High Definition Audio 
  driver: snd_hda_intel 
  Device-2: NVIDIA GK106 HDMI Audio driver: snd_hda_intel 
  Sound Server: ALSA v: k5.4.0-169-generic 
Network:
  Device-1: Intel 82579LM Gigabit Network driver: e1000e 
  IF: eno1 state: up speed: 100 Mbps duplex: full mac: <filter> 
  Device-2: Intel 82574L Gigabit Network driver: e1000e 
  IF: enp1s0 state: down mac: <filter> 
Drives:
  Local Storage: total: 6.37 TiB used: 679.37 GiB (10.4%) 
  ID-1: /dev/sda vendor: Western Digital model: WD2005FBYZ-01YCBB3 
  size: 1.82 TiB 
  ID-2: /dev/sdb vendor: Seagate model: ST1000LM049-2GH172 size: 931.51 GiB 
  ID-3: /dev/sdc vendor: Seagate model: ST1000LM049-2GH172 size: 931.51 GiB 
  ID-4: /dev/sdd vendor: Seagate model: ST1000LM049-2GH172 size: 931.51 GiB 
  ID-5: /dev/sde vendor: Seagate model: ST2000LM015-2E8174 size: 1.82 TiB 
Partition:
  ID-1: / size: 527.61 GiB used: 85.63 GiB (16.2%) fs: ext4 dev: /dev/sda5 
  ID-2: swap-1 size: 4.00 GiB used: 0 KiB (0.0%) fs: swap dev: /dev/sda4 
Sensors:
  System Temperatures: cpu: 42.0 C mobo: N/A gpu: nvidia temp: 43 C 
  Fan Speeds (RPM): N/A gpu: nvidia fan: 30% 
Info:
  Processes: 464 Uptime: 25m Memory: 94.32 GiB used: 4.01 GiB (4.3%) 
  Shell: bash inxi: 3.0.38 

----------------------------------------------------------------------------

System configuration before Upgrade (running cloned MINT 20.3 from Seagate HD)

inxi MINT 20.3 (Seagate model: ST2000DM008-2UB102)

rolf@home-4:~$ inxi -FS
System:
  Host: home-4 Kernel: 5.4.0-170-generic x86_64 bits: 64 
  Desktop: Cinnamon 5.2.7 Distro: Linux Mint 20.3 Una 
Machine:
  Type: Desktop System: Hewlett-Packard product: HP Z620 Workstation v: N/A 
  serial: <superuser/root required> 
  Mobo: Hewlett-Packard model: 158A v: 0.00 
  serial: <superuser/root required> UEFI: Hewlett-Packard v: J61 v03.96 
  date: 10/29/2019 
CPU:
  Topology: 2x 6-Core model: Intel Xeon E5-2620 0 bits: 64 type: MT MCP SMP 
  L2 cache: 30.0 MiB 
  Speed: 1197 MHz min/max: 1200/2500 MHz Core speeds (MHz): 1: 1197 2: 1197 
  3: 1197 4: 1197 5: 1197 6: 1197 7: 1197 8: 1197 9: 1197 10: 1197 11: 1197 
  12: 1197 13: 1197 14: 1197 15: 1197 16: 1197 17: 1197 18: 1197 19: 1197 
  20: 1197 21: 1197 22: 1197 23: 1197 24: 1197 
Graphics:
  Device-1: NVIDIA GK106GL [Quadro K4000] driver: nvidia v: 470.223.02 
  Display: x11 server: X.Org 1.20.13 driver: nvidia 
  unloaded: fbdev,modesetting,nouveau,vesa resolution: 1920x1080~60Hz 
  OpenGL: renderer: Quadro K4000/PCIe/SSE2 v: 4.6.0 NVIDIA 470.223.02 
Audio:
  Device-1: Intel C600/X79 series High Definition Audio 
  driver: snd_hda_intel 
  Device-2: NVIDIA GK106 HDMI Audio driver: snd_hda_intel 
  Sound Server: ALSA v: k5.4.0-170-generic 
Network:
  Device-1: Intel 82579LM Gigabit Network driver: e1000e 
  IF: eno1 state: up speed: 100 Mbps duplex: full mac: 74:46:a0:92:55:97 
  Device-2: Intel 82574L Gigabit Network driver: e1000e 
  IF: enp1s0 state: down mac: 74:46:a0:92:55:98 
Drives:
  Local Storage: total: 5.46 TiB used: 137.50 GiB (2.5%) 
  ID-1: /dev/sda vendor: Seagate model: ST2000DM008-2UB102 size: 1.82 TiB 
  ID-2: /dev/sdb vendor: Seagate model: ST1000LM049-2GH172 size: 931.51 GiB 
  ID-3: /dev/sdc vendor: Seagate model: ST1000LM049-2GH172 size: 931.51 GiB 
  ID-4: /dev/sdd vendor: Seagate model: ST2000LM015-2E8174 size: 1.82 TiB 
Partition:
  ID-1: / size: 527.61 GiB used: 89.26 GiB (16.9%) fs: ext4 dev: /dev/sda5 
  ID-2: swap-1 size: 4.00 GiB used: 0 KiB (0.0%) fs: swap dev: /dev/sda4 
Sensors:
  System Temperatures: cpu: 44.0 C mobo: N/A gpu: nvidia temp: 38 C 
  Fan Speeds (RPM): N/A gpu: nvidia fan: 30% 
Info:
  Processes: 513 Uptime: 15m Memory: 94.32 GiB used: 3.14 GiB (3.3%) 
  Shell: bash inxi: 3.0.38 

----------------------------------------------------------------------------

System configuration after Upgrade (running MINT 21.3 from Seagate HD)

inxi MINT 21.3

rolf@home-4:~$ inxi -FS
System:
  Host: home-4 Kernel: 5.15.0-94-generic x86_64 bits: 64
    Desktop: Cinnamon 6.0.4 Distro: Linux Mint 21.3 Virginia
Machine:
  Type: Desktop System: Hewlett-Packard product: HP Z620 Workstation v: N/A
    serial: <superuser required>
  Mobo: Hewlett-Packard model: 158A v: 0.00 serial: <superuser required>
    UEFI: Hewlett-Packard v: J61 v03.96 date: 10/29/2019
CPU:
  Info: 2x 6-core model: Intel Xeon E5-2620 0 bits: 64 type: MT MCP SMP
    cache: L2: 2x 1.5 MiB (3 MiB)
  Speed (MHz): avg: 1291 min/max: 1200/2500 cores: 1: 1197 2: 1197 3: 1197
    4: 1862 5: 1996 6: 1995 7: 1197 8: 1197 9: 1197 10: 1197 11: 1197 12: 1197
    13: 1197 14: 1197 15: 1197 16: 1197 17: 1197 18: 1197 19: 1197 20: 1197
    21: 1197 22: 1197 23: 1197 24: 1197
Graphics:
  Device-1: NVIDIA GK106GL [Quadro K4000] driver: nvidia v: 470.223.02
  Display: x11 server: X.Org v: 1.21.1.4 driver: X: loaded: nvidia
    unloaded: fbdev,modesetting,nouveau,vesa gpu: nvidia
    resolution: 1920x1080~60Hz
  OpenGL: renderer: Quadro K4000/PCIe/SSE2 v: 4.6.0 NVIDIA 470.223.02
Audio:
  Device-1: Intel C600/X79 series High Definition Audio driver: snd_hda_intel
  Device-2: NVIDIA GK106 HDMI Audio driver: snd_hda_intel
  Sound Server-1: ALSA v: k5.15.0-94-generic running: yes
  Sound Server-2: PulseAudio v: 15.99.1 running: yes
  Sound Server-3: PipeWire v: 0.3.48 running: yes
Network:
  Device-1: Intel 82579LM Gigabit Network driver: e1000e
  IF: eno1 state: up speed: 100 Mbps duplex: full mac: 74:46:a0:92:55:97
  Device-2: Intel 82574L Gigabit Network driver: e1000e
  IF: enp1s0 state: down mac: 74:46:a0:92:55:98
Drives:
  Local Storage: total: 4.55 TiB used: 728.3 GiB (15.6%)
  ID-1: /dev/sda vendor: Seagate model: ST1000LM049-2GH172 size: 931.51 GiB
  ID-2: /dev/sdb vendor: Seagate model: ST1000LM049-2GH172 size: 931.51 GiB
  ID-3: /dev/sdc vendor: Seagate model: ST1000LM049-2GH172 size: 931.51 GiB
  ID-4: /dev/sdd vendor: Seagate model: ST2000LM015-2E8174 size: 1.82 TiB
Partition:
  ID-1: / size: 245.02 GiB used: 87.16 GiB (35.6%) fs: ext4 dev: /dev/sda5
  ID-2: /boot/efi size: 497 MiB used: 7.5 MiB (1.5%) fs: vfat
    dev: /dev/sda1
Swap:
  ID-1: swap-1 type: partition size: 4 GiB used: 0 KiB (0.0%) dev: /dev/sda4
Sensors:
  System Temperatures: cpu: 38.0 C mobo: N/A gpu: nvidia temp: 39 C
  Fan Speeds (RPM): N/A gpu: nvidia fan: 30%
Info:
  Processes: 478 Uptime: 8m Memory: 94.31 GiB used: 2.8 GiB (3.0%)
  Shell: Bash inxi: 3.3.13

-----------------------------------------------------------------------------

Former SDA:

/dev/sda:

 Model=WDC WD2005FBYZ-01YCBB3, FwRev=RR09, SerialNo=WD-WCC6N1CC5LT6
 Config={ HardSect NotMFM HdSw>15uSec SpinMotCtl Fixed DTR>5Mbs FmtGapReq }
 RawCHS=16383/16/63, TrkSize=0, SectSize=0, ECCbytes=0
 BuffType=unknown, BuffSize=unknown, MaxMultSect=16, MultSect=off
 CurCHS=16383/16/63, CurSects=16514064, LBA=yes, LBAsects=3907029168
 IORDY=on/off, tPIO={min:120,w/IORDY:120}, tDMA={min:120,rec:120}
 PIO modes:  pio0 pio3 pio4 
 DMA modes:  mdma0 mdma1 mdma2 
 UDMA modes: udma0 udma1 udma2 udma3 udma4 udma5 *udma6 
 AdvancedPM=yes: unknown setting WriteCache=enabled
 Drive conforms to: unknown:  ATA/ATAPI-1,2,3,4,5,6,7

Presently used SDA before and after Upgrade:

/dev/sda:

 Model=ST1000LM049-2GH172, FwRev=SDM1, SerialNo=WN92ZC9H
 Config={ HardSect NotMFM HdSw>15uSec Fixed DTR>10Mbs RotSpdTol>.5% }
 RawCHS=16383/16/63, TrkSize=0, SectSize=0, ECCbytes=0
 BuffType=unknown, BuffSize=unknown, MaxMultSect=16, MultSect=16
 CurCHS=16383/16/63, CurSects=16514064, LBA=yes, LBAsects=1953525168
 IORDY=on/off, tPIO={min:120,w/IORDY:120}, tDMA={min:120,rec:120}
 PIO modes:  pio0 pio1 pio2 pio3 pio4 
 DMA modes:  mdma0 mdma1 mdma2 
 UDMA modes: udma0 udma1 udma2 udma3 udma4 udma5 *udma6 
 AdvancedPM=yes: unknown setting WriteCache=enabled
 Drive conforms to: Reserved:  ATA/ATAPI-4,5,6,7
![2024-01-22_AbgesicherterStart](https://github.com/linuxmint/cinnamon/assets/159486166/43dfcd54-6c07-42ba-91a5-8b28c1e3653f)
![Home-4_UUID](https://github.com/linuxmint/cinnamon/assets/159486166/ca5070a0-993e-43d3-b6fa-8280586f879b)
![Z620-SATA](https://github.com/linuxmint/cinnamon/assets/159486166/8deea915-9578-4950-9b82-32cbbd79b6b7)
![Z6120-AHCI SATA controller](https://github.com/linuxmint/cinnamon/assets/159486166/6d72daa4-a99b-40a5-8015-f881354dd2b6)

**Comment by leigh123linux** [comment]
File the issue at

https://github.com/linuxmint/linuxmint/issues
