### ISSUE TITLE
Columns of "Save As" and "Open Files" pickers not sortable while showing search results.

### ISSUE THREAD

**Issue by HT-7** [linuxmint/cinnamon#12097]
### Distribution

Mint 21

### Package version

Cinnamon 5.4.8

### Frequency

Always

### Bug description

In the "Save As" or "Open Files" window, the columns (Name, Size, Type, Modified) are normally sortable. However, while showing search results, the columns are not sortable.

### Steps to reproduce

1. Open the "Open Files" window in Xed by pressing <kbd>Ctrl</kbd>+<kbd>O</kbd> or from the "File" top menu.
2. Press <kbd>Ctrl</kbd>+<kbd>F</kbd> to access search.
3. Enter any search term which gets multiple results.
4. Clicking the column headers (the boxes at the top with the words "Name", "Size", "Type", "Modified") does not change the sorting.

### Expected behavior

Clicking on the column headers while showing search results should sort the listed items (files and folders) like it does when not showing search results.

**Comment by leigh123linux** [comment]
Gtk3 provides the "Open Files"  window.
This  can't be fixed within cinnamon or mint, file the issue against gtk3 if you like wasting time.
