### ISSUE TITLE
Assigned connected USB printer gets intermittenly unassigned by Linux Mint 21.3 

### ISSUE THREAD

**Issue by Aurorasky** [linuxmint/cinnamon#12091]
### Distribution

Mint 21.3 

### Package version

6.0.4

### Graphics hardware in use

Intel Corporation 4th Gen Core Processor Integrated Graphics Controller

### Frequency

Quite often

### Bug description

Often when going to print from one of many programs installed on the computer, the OS finds there is no connected USB printer.  Just reassigning the USB connected printer often will not work and a system reboot is necessary. 

### Steps to reproduce

Leave the computer on overnight and there will be a good chance the assigned printer will no longer be connected.

### Expected behavior

Once a USB printer is assigned, it should always be available until it is intentionally unassigned, disconnected, or turned off.

### Additional information

This problem came on immediately with the latest Mint 21.x versions.  The problem does not exist with the previous version of Mint 20.x which is still installed on my quad booting computer.  The printer driver for the 21.x OS is significantly different from the 20.x OS driver. It is very inconvenient to have reboot the computer when in the middle of performing other task that need access to the printer.  The printer is an HP Officejet Pro 8715 recognized as a 8710 which work fine when it is connected.

**Comment by leigh123linux** [comment]
File the issue at

https://github.com/linuxmint/linuxmint/issues
