### ISSUE TITLE
cinnamon-settings -t (or --tab) to open specific tab doesn't work

### ISSUE THREAD

**Issue by awvalenti** [linuxmint/cinnamon#12090]
### Distribution

Mint 20.3

### Package version

Cinnamon 5.2.7

### Graphics hardware in use

2nd Generation Core Processor Family Integrated Graphics Controller | Whistler [Radeon HD 6630M/6650M/6750M/7670M/7690M]

### Frequency

Always

### Bug description

Can't directly open tab of cinnamon-settings module via command line. `cinnamon-settings keyboard -t 1` doesn't work. It says that option `-t` is unknown. Full output (in Portuguese - my highlight in *):
```
Using PAM module (python3-pam)
/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py:433: DeprecationWarning: Gtk.Window.set_wmclass is deprecated
  self.window.set_wmclass(wm_class, wm_class)
Loading Keyboard module
/usr/share/cinnamon/cinnamon-settings/bin/capi.py:62: Warning: g_object_class_override_property: Can't find property to override for 'CcRegionPanel::argv'
  return GObject.new(panel_type)
 ************** Opção -t desconhecida ****************
```

That's very odd, since `man cinnamon-settings` specifically mentions support for it:
```
       To open the download tab of the applets settings:
              $ cinnamon-settings applets --tab=download
              or
              $ cinnamon-settings applets -t 1
```

### Steps to reproduce

```sh
man cinnamon-settings
cinnamon-settings applets --tab=download
cinnamon-settings applets -t 1
cinnamon-settings keyboard -t 1
```

### Expected behavior

Open specified module in specified tab

**Comment by leigh123linux** [comment]
The issue doesn't reproduce with the supported  cinnamon version.
Your version is no longer supported.
