### ISSUE TITLE
Worspace does not save Position for each Application

### ISSUE THREAD

**Issue by cubetti2004** [linuxmint/cinnamon#12099]
### Distribution

LMDE6

### Package version

6.04

### Graphics hardware in use

AMD

### Frequency

Always

### Bug description

Not save position in workspaces for each application after restart/logout.

### Steps to reproduce

Open application and move to workspace 2
Open application on workspace 1
Logout or restart. Then reopen applications. It is always on the the 1st workspace.

### Expected behavior

Save application position and move application automatically to the appropiate workspace.

**Comment by JosephMcc** [comment]
This is not a bug. Cinnamon does not support saving the users session. Has nothing to do with the having workspaces involved. Some apps remember their size and position, some apps do not. It's really up  to the application itself.

Session saving has been requested in the past but currently is not somethings that has focus or is being worked on.
