### ISSUE TITLE
Upgrade to Kernel 6.5.0-x Produces Unreliable Mouse Behavior in LibreOffice Calc

### ISSUE THREAD

**Issue by sproggit** [linuxmint/cinnamon#12092]
### Distribution

Mint 21.3/Cinnamon/64-Bit

### Package version

6.0.4

### Graphics hardware in use

nVidia GeForce T600 / nVidia-535-154-05

### Frequency

Always

### Bug description

Since upgrading from kernel 5.15 to 6.5.0 (initially 6.5.0-18, currently 6.5.0-21), behavior of my Logitech G903 Lightspeed mouse has become erratic, but only in LibreOffice Calc [so far]. On screen, the behavior is indistinguishable from, say, a sticking mouse wheel sensor. 

Apps tested include:-
With Issue:-
LibreOffice Calc [Version 7.3.7.2] 

Without Issue (basically *everything* else I've tested, including):- 
Bluefish Editor 2.2.12
Cinnamon Desktop [i.e. by selecting "All Applications" and scrolling up and down]
Claws-Mail 4.0.0
FireFox 123.0
GIMP 2.10.36
Google Earth 7.3.6.9750 [64-bit]
GThumb 3.12.0
LibreOffice Writer 7.3.7.2
Software Manager 21.3
Xed 3.4.5

Symptoms are that scrolling "up" a spreadsheet tab works as expected, but when trying to scroll "down" (i.e. pulling the top of the mouse wheel towards you) results in an irregular or "jammed" scrolling of the display on screen. So far, this symptom has only been observed in LibreOffice Calc. It is not visible in LibreOffice Writer or any of the apps listed above. It is *very* apparent. I'm a heavy user of Calc and was using the application either side of the kernel switch, which made the issue very obvious. 

Rebooting makes no difference. This hardware platform dual-boots with Windows 11/64-Bit/Pro - and to date zero issues have been observed with any peripherals or apps on Windows. 

Intend to report this to LibreOffice and potentially to downgrade back to 5.15, but wanted to report here in case it was some kind of odd signalling or hardware interface problem. It has definitely been induced by the kernel change. Hardware details are:-

inxi -F
System:
  Host: Fanless Kernel: 6.5.0-21-generic x86_64 bits: 64
    Desktop: Cinnamon 6.0.4 Distro: Linux Mint 21.3 Virginia
Machine:
  Type: Desktop System: ASUS product: N/A v: N/A serial: <superuser required>
  Mobo: ASUSTeK model: ROG STRIX B760-I GAMING WIFI v: Rev 1.xx
    serial: <superuser required> UEFI: American Megatrends v: 1604
    date: 12/15/2023
Battery:
  ID-1: hidpp_battery_0 charge: 100% condition: N/A
CPU:
  Info: 24-core (8-mt/16-st) model: Intel Core i9-14900T bits: 64
    type: MST AMCP cache: L2: 32 MiB
  Speed (MHz): avg: 809 min/max: 800/5100:5500:4000 cores: 1: 800 2: 800
    3: 800 4: 800 5: 800 6: 800 7: 800 8: 800 9: 800 10: 1100 11: 800 12: 800
    13: 800 14: 800 15: 800 16: 800 17: 800 18: 800 19: 800 20: 800 21: 800
    22: 800 23: 800 24: 800 25: 800 26: 800 27: 800 28: 800 29: 800 30: 800
    31: 800 32: 800
Graphics:
  Device-1: NVIDIA TU117GL [T600] driver: nvidia v: 535.154.05
  Display: x11 server: X.Org v: 1.21.1.4 driver: X: loaded: nvidia
    unloaded: fbdev,modesetting,nouveau,vesa gpu: nvidia resolution:
    1: 4096x2304~60Hz 2: 4096x2304~60Hz 3: 4096x2304~60Hz  {{ Note - this is wrong, actual res is 2560x1440 }}}
  OpenGL: renderer: NVIDIA T600/PCIe/SSE2 v: 4.6.0 NVIDIA 535.154.05
Audio:
  Device-1: Intel driver: snd_hda_intel
  Device-2: NVIDIA driver: snd_hda_intel
  Sound Server-1: ALSA v: k6.5.0-21-generic running: yes
  Sound Server-2: PulseAudio v: 15.99.1 running: yes
  Sound Server-3: PipeWire v: 0.3.48 running: yes
Network:
  Device-1: Intel driver: iwlwifi
  IF: wlp0s20f3 state: down mac: xxxxxxxxxxxxxxxxxx
  Device-2: Intel driver: igc
  IF: enp5s0 state: up speed: 2500 Mbps duplex: full mac: xxxxxxxxxxxxxxxxxx
Bluetooth:
  Device-1: Intel type: USB driver: btusb
  Report: hciconfig ID: hci0 state: up address: xxxxxxxxxxxxxxxxxx
RAID:
  Hardware-1: Intel Device driver: vmd
Drives:
  Local Storage: total: 7.28 TiB used: 179.93 GiB (2.4%)
  ID-1: /dev/nvme0n1 vendor: Samsung model: SSD 990 PRO 4TB size: 3.64 TiB
  ID-2: /dev/nvme1n1 vendor: Samsung model: SSD 990 PRO 4TB size: 3.64 TiB
Partition:
  ID-1: / size: 59.78 GiB used: 752.1 MiB (1.2%) fs: ext4 dev: /dev/nvme0n1p4
  ID-2: /boot/efi size: 96 MiB used: 32.3 MiB (33.6%) fs: vfat
    dev: /dev/nvme0n1p1
  ID-3: /home size: 59.78 GiB used: 1.77 GiB (3.0%) fs: ext4
    dev: /dev/nvme0n1p8
  ID-4: /tmp size: 29.87 GiB used: 1.5 MiB (0.0%) fs: ext4
    dev: /dev/nvme0n1p10
  ID-5: /usr size: 59.78 GiB used: 12.42 GiB (20.8%) fs: ext4
    dev: /dev/nvme0n1p7
  ID-6: /var size: 59.78 GiB used: 4.56 GiB (7.6%) fs: ext4
    dev: /dev/nvme0n1p9
Swap:
  ID-1: swap-1 type: partition size: 61.04 GiB used: 0 KiB (0.0%)
    dev: /dev/nvme0n1p6
Sensors:
  System Temperatures: cpu: 27.8 C mobo: N/A gpu: nvidia temp: 40 C
  Fan Speeds (RPM): N/A gpu: nvidia fan: 0%
Info:
  Processes: 551 Uptime: 40m Memory: 62.53 GiB used: 3.84 GiB (6.1%)
  Shell: Bash inxi: 3.3.13

Mouse is Logitech G903 Lightspeed - issue exists whether connected wirelessly or tethered
Keyboard is Logitech G916 - no issues observed either wirelessly or tethered 

Very happy to gather more data if required. 

### Steps to reproduce

Upgrade from kernel 5.15 to 6.5.0... Launch LibreOffice Calc, attempt to scroll and observe failure for display to move when scrolling down. 

### Expected behavior

Smooth scrolling driven by the mouse wheel, in either direction, in all applications.

**Comment by leigh123linux** [comment]
file the issue at  https://github.com/linuxmint/linuxmint/issues
