### ISSUE TITLE
Applet Feature Request - Calendar - more time formats

### ISSUE THREAD

**Issue by inson1** [linuxmint/cinnamon#12103]
### Applet name and maintainer

calendar@cinnamon.org

### What would you like to see?

I want more formats, so I could have for example 
3:1 as three hours and one minute
4.3.2024 as 4 day, 3 month 2024 year

Linux Mint 21.3

**Comment by rcalixte** [comment]
There is already a way to configure a custom date format if you right-click on the time and select 'Configure...' in the menu. From there, you can select, "Use a custom date format" and that will allow you to input whatever format you want. There is a button that links to [foragoodstrftime.com](https://foragoodstrftime.com/) if you need it as well.

**Comment by inson1** [comment]
@rcalixte I know about them, but I'm still missing these
Month of the year (1..12)
 Minute of the hour (0..59)

**Comment by rcalixte** [comment]
> Month of the year (1..12)

`%m`



> Minute of the hour (0..59)

`%M`

**Comment by inson1** [comment]
@rcalixte no, that is something else
%m is 01..12
%M is 00..59

**Comment by rcalixte** [comment]
> @rcalixte no, that is something else %m is 01..12 %M is 00..59

Ah, you want them without the leading "0":

`%-m`
`%-M`

More details on padding and other options are available in your terminal via `man date`.

**Comment by inson1** [comment]
@rcalixte Thank you!
I guess you dont have control over that website, but that info should be there or somewhere easily available :) so I would keep open :)

btw is there way to center it (the text in it and there is more lines)? or should create fr for that?

**Comment by rcalixte** [comment]
> I guess you dont have control over that website, but that info should be there or somewhere easily available :) so I would keep open :)

I often refer to the man page to be honest. It's a great site, but the terminal page is also one command away, very detailed, and searchable. That's what I default to but for most people, the website is also sufficient.



> btw is there way to center it (the text in it and there is more lines)? or should create fr for that?

For new lines: `%n`

It should already be centered? Can you share what you're seeing? If it isn't centered, it might be due to the theme.
