### ISSUE TITLE
Country flags are not shown for displaying language layout

### ISSUE THREAD

**Issue by koreanfan** [linuxmint/cinnamon#12108]
### Distribution

archlinux rolling release x86_64

### Package version

cinnamon 6.0.4-1

### Graphics hardware in use

one monitor, amd RX-5XX series

### Frequency

Always

### Bug description

Go to layout settings, enable option "country flags....". Only text shown for layout. Add non english layout, switch to another layout, no flags, only text

### Steps to reproduce

Go to layout settings, enable option "country flags....". Only text shown for layout. Add non english layout, switch to another layout, no flags, only text

### Expected behavior

Go to layout settings, enable option "country flags....". Country flag shown for layout. Add non english layout, switch to another layout, country flag shown

### Additional information

On debian cinnamon country flags working

**Comment by leigh123linux** [comment]
Install  https://aur.archlinux.org/packages/iso-flag-png

and report the missing dep to archlinux
