### ISSUE TITLE
DPI change causes cinnamon menu to behave unexpectedly

### ISSUE THREAD

**Issue by developer1105** [linuxmint/cinnamon#12126]
### Distribution

Arch Linux (20th /  march  / 2024)

### Package version

Cinnamon 6.0.4

### Graphics hardware in use

intel i915

### Frequency

Always

### Bug description

Letters are not appearing correctly after changing Qt/Gtk DPI options to make fonts look bigger, specifically in the search field, and app description field

### Steps to reproduce

Change Gtk/Qt DPI for bigger fonts, and then reboot, next click to open menu

### Expected behavior

The one that happens with normal font size, i.e. no change in Gtk/Qt DPI

### Additional information

An image demonstrates the issue (screen resolution 1280x768)
![cinnamon_menu](https://github.com/linuxmint/cinnamon/assets/67207296/3c2e7462-39ce-4ec1-bd5e-8630804da516)

**Comment by fredcw** [comment]
What cinnamon ("desktop") theme are you using?

**Comment by developer1105** [comment]
Mouse pointer: Adwaita
Applications: Mint-L-Orange
Icons: Tela-purple-light
Desktop: Qogir-Light

**Comment by fredcw** [comment]
@developer1105 Thanks, this is a problem with the Qogir-Light theme unfortunately. I'll have an update ASAP.
