### ISSUE TITLE
Telegram tray icon broken on program launch

### ISSUE THREAD

**Issue by mrmelon54** [linuxmint/cinnamon#12135]
### Distribution

Mint 21.3

### Package version

6.0.4

### Graphics hardware in use

NVIDIA GeForce RTX 3070 Ti

### Frequency

Always

### Bug description

When opening telegram the tray icon shows this error icon
![image](https://github.com/linuxmint/cinnamon/assets/48031324/b26d8a02-6eb3-4296-9942-7ab8589e45b8)

### Steps to reproduce

Just open telegram, I have no idea if anyone else can reproduce

### Expected behavior

Telegram opens with correct tray icon

### Additional information

The issue can be resolved by going into settings and turning off and on the "show tray icon" option. Unfortunately, the fix is only temporary as, when closing and reopening Telegram the initial tray icon issue persists.

**Comment by marco4mp** [comment]
How did you install Telegram? I have the Flatpak version installed and I haven't had that problem.

![telegram icon works ok](https://github.com/linuxmint/cinnamon/assets/52709674/d4b061a0-bec0-4a49-b8b7-e5b304e8fd4e)

**Comment by mrmelon54** [comment]
I downloaded it directly from the website. The same issue happens with the Flatpak version. It seems to work fine on my laptop, I guess it's only an issue on my PC, any chance you could give some suggestions on how to debug it?
