### ISSUE TITLE
When the application is in fullscreen mode after pressing Super(Win), the panel is visible, but does not work.

### ISSUE THREAD

**Issue by TranzistorP** [linuxmint/cinnamon#12159]
### Distribution

Mint 21.3

### Package version

6.0.4

### Graphics hardware in use

NVIDIA GeForce GTX 1650

### Frequency

Always

### Bug description

When the application is in fullscreen mode after pressing Super(Win), the panel is visible, but does not work.
But the menu works fine.

### Steps to reproduce

1. Open Firefox
2. Press F11
3. Press Super
4. Try to click on any applet on panel
As a result, the panel and menu will close without any action.
https://github.com/linuxmint/cinnamon/assets/96445511/a5ef4177-0563-4752-a709-1b97258c220e

### Expected behavior

The action assigned to the applet should work.

### Additional information

I have been observing this behavior for quite some time.

As I understand from these threads:
https://github.com/linuxmint/cinnamon/issues/575
https://forums.linuxmint.com/viewtopic.php?t=414466

Initially, only the menu was shown. But users asked to also show the panel.
Now the panel is shown, but does not work, which is even worse than before.
We need to either return to the older behavior or fix the current one.

At the same time, there is now a shortcut Super+S that opens the panel and it works fine!
Sorry for my English

**Comment by JosephMcc** [comment]
https://github.com/linuxmint/cinnamon/issues/11658
