### ISSUE TITLE
Nordvpn Status Message Pop-Ups are not Displayed in Debian 12 Bookworm

### ISSUE THREAD

**Issue by 7FKHOrQ1u7zDnlarq3zyVTZh90wQVtr5** [linuxmint/cinnamon#12158]
### Distribution

Debian 12 Bookworm

### Package version

12.5

### Graphics hardware in use

Intel Graphics

### Frequency

Always

### Bug description

Nordvpn does not display Status Message Pop-Up after system update.

### Steps to reproduce

After an upgrade to my Debian 12 installation on a Dell 3120 Latitude laptop, I noticed that the status message pop-ups no longer were being displayed.  After installing XFCE4 Desktop, and booting into XFCE4, the status messages began displaying normally.  I prefer Cinnamon Desktop so I removed the XFCE4 Desktop from the computer so I could use as-is, Then I rebooted into Cinnamon Desktop as before, but this time, status pop-ups still worked normally.  Then after installing an removing XFCE4 several time, I noticed, when I had done a full purge of XFCE4, that the Cinnamon installation needed to have libnotify-bin installed before Nordvpn status pop-up messages would work properly.   

### Expected behavior

What is supposed to happen is when a new Nordvpn site is selected, a pop-up message will be displayed indicating the change.  After installing libnotify-bin, status pop-up messages display as expected.

### Additional information

I do not know how to notify the appropriate maintainer, but I hope someone else does.  The issue is minor and does not effect Nordvpn, but when something stops working as expected, I try to find a fix.  It is my opinion that when the last updates were rolled out, libnotify-bin was not part of Debian 12 anymore and when issuing apt autoremove, libnotify-bin gets removed for some reason, which breaks the notifications feature.  It would appear that libnotify-bin needs to be re-added to the  package repository.  For now, it has to be manually installed for the status pop-ups to work.

**Comment by leigh123linux** [comment]
Us the template and provide all the requested info.
