### ISSUE TITLE
Kernel 5.15.0.102 Thunderbird error: not enough disk space

### ISSUE THREAD

**Issue by Source-finder** [linuxmint/cinnamon#12151]
### Distribution

Linux Mint 21.3 Cinnamon

### Package version

6.0.4

### Graphics hardware in use

ATI XT6650

### Frequency

Always

### Bug description

When moving mails form IMAP to local folder, placed on network drive: "There is not enough disk space to download new messages. Delete old e-mail, empry the trash, compress folders en try again.". Solutions like making new local folders, even a total new local folder, doesn't solve the problem. Testing Thunderbird on a second desktop with LM 21.3 showed no errors before updating to kernel 5.15.0.102, but after updating the same error. So rolling back to kernel 5.15.0.100 (second desktop) and 5.15.0.102 (initial desktop) solved the errors.

### Steps to reproduce

Linux Mint 21.3 with kernel 5.15.0.102 with local folder on local or network drive. Try to move a mail message to a subfolder (f.e. Inbox) in this local folder. Try the same thing with kernel 5.15.100 or 101.

### Expected behavior

Of course it should be possible to move mails form an (IMAP) inbox to a local folder.

**Comment by leigh123linux** [comment]
This isn't a cinnamon issue.

**Comment by Source-finder** [comment]
Try to add this issue to Linuxmint...
