### ISSUE TITLE
Calendar - more time formats redirects to non working website

### ISSUE THREAD

**Issue by lrolvink** [linuxmint/cinnamon#12162]
### Distribution

Linux Mint 21.3 x86_64

### Package version

6.0.4

### Graphics hardware in use

Intel Device 4690

### Frequency

Always

### Bug description

In the Calendar applet configuring window there is a button named 'Show information on date format syntax'. Pressing the button opens a webbrowser to https://www.foragoodstrftime.com/ what on the moment of writing is not working anymore.

### Steps to reproduce

1. Click on the date time Open de Calendar applet
2. Enable the ' Use a custom date format' 
3. Click on 'Show information on date format syntax'

### Expected behavior

A functioning website for date format syntax.

### Additional information

It would be better if there was a built-in syntax helper instead of depending on a website

**Comment by Secret-chest** [comment]
https://en.cppreference.com/w/c/chrono/strftime
