### ISSUE TITLE
error open google drive on online-accounts

### ISSUE THREAD

**Issue by Bug-Cache** [linuxmint/cinnamon#12166]
OS: Arch Linux x86_64
Kernel: 6.8.7-zen1-1-zen
DE: Cinnamon 6.0.4

error message

> Unknown module online-accounts
libgoa-backend-1.0.so.1: cannot open shared object file: No such file or directory
Failed to load module: /usr/lib/cinnamon-control-center-1/panels/libonline-accounts.so
/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py:444: DeprecationWarning: Gtk.Window.set_wmclass is deprecated
  self.window.set_wmclass(wm_class, wm_class)
Loading Online Account module
Could not load online-accounts module; is the cinnamon-control-center package installed?
'NoneType' object has no attribute 'set_no_show_all'

![image](https://github.com/linuxmint/cinnamon/assets/98657967/63dd8dd6-b360-4c2e-9cbc-5afd283cdeb1)

**Comment by leigh123linux** [comment]
We have dropped online accounts support from c-c-c due to gnome upstream changes.
File the issue at archlinux and request that they remove online accounts support from c-c-c and package gnome-online-accounts-gtk instead

https://github.com/xapp-project/gnome-online-accounts-gtk
