### ISSUE TITLE
fwupd service coredumps

### ISSUE THREAD

**Issue by MikeWDec54** [linuxmint/cinnamon#12184]
### Distribution

Mint 21.3

### Package version

6.0.4

### Graphics hardware in use

WhiskeyLake-U GT2 [UHD Graphics 620]

### Frequency

Always

### Bug description

fwupd service always coredumps.

$ sudo systemctl status fwupd
× fwupd.service - Firmware update daemon
     Loaded: loaded (/lib/systemd/system/fwupd.service; static)
     Active: failed (Result: core-dump) since Sun 2024-05-05 13:23:54 EDT; 4min 43s ago
       Docs: https://fwupd.org/
   Main PID: 1918 (code=dumped, signal=ABRT)
        CPU: 236ms

May 05 13:23:53 mikew-galp3 systemd[1]: Starting Firmware update daemon...
May 05 13:23:53 mikew-galp3 fwupd[1918]: **
May 05 13:23:53 mikew-galp3 fwupd[1918]: ERROR:../src/xb-lzma-decompressor.c:132:xb_lzma_decompressor_convert: code sho>
May 05 13:23:53 mikew-galp3 fwupd[1918]: Bail out! ERROR:../src/xb-lzma-decompressor.c:132:xb_lzma_decompressor_convert>
May 05 13:23:54 mikew-galp3 systemd[1]: fwupd.service: Main process exited, code=dumped, status=6/ABRT
May 05 13:23:54 mikew-galp3 systemd[1]: fwupd.service: Failed with result 'core-dump'.
May 05 13:23:54 mikew-galp3 systemd[1]: Failed to start Firmware update daemon.

### Steps to reproduce

Occurs on system reboot, or when doing "sudo systemctl start fwupd"

### Expected behavior

fwupd should not coredump.

### Additional information

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Linuxmint
Description:	Linux Mint 21.3
Release:	21.3
Codename:	virginia

$ uname -a
Linux mikew-galp3 6.8.0-76060800daily20240311-generic #202403110203~1714077665~22.04~4c8e9a0~dev-Ubuntu SMP PREEMPT_DY x86_64 x86_64 x86_64 GNU/Linux

$ cinnamon --version
Cinnamon 6.0.4

$ sudo coredumpctl debug
           PID: 4066 (fwupd)
           UID: 0 (root)
           GID: 0 (root)
        Signal: 6 (ABRT)
     Timestamp: Sun 2024-05-05 13:29:01 EDT (6min ago)
  Command Line: /usr/libexec/fwupd/fwupd
    Executable: /usr/libexec/fwupd/fwupd
 Control Group: /system.slice/fwupd.service
          Unit: fwupd.service
         Slice: system.slice
       Boot ID: 85191437b7e24d11b34b8983810e769f
    Machine ID: 10b971ac1a304176906b1f6a23827476
      Hostname: mikew-galp3
       Storage: /var/lib/systemd/coredump/core.fwupd.0.85191437b7e24d11b34b8983810e769f.4066.1714930141000000.zst (present)
     Disk Size: 4.0M
       Message: Process 4066 (fwupd) of user 0 dumped core.
                
                Found module linux-vdso.so.1 with build-id: 5df430132408577170d84cf46590d9b9c091082a
                Found module libftdi1.so.2 with build-id: d7adfdaa0b24e95f593ff7fca81fd8cdbc783d8d
                Found module libpci.so.3 with build-id: cdb834c0e7a047d5f2d608cf74d5240c1827994b
                Found module libflashrom.so.1 with build-id: e887cb03d567294bc237ae72ecc37b46e4935fc8
                Found module libfu_plugin_flashrom.so with build-id: 9c963114e847cb6c68c7e2ba7054ae133ad44f2f
                Found module libmbim-glib.so.4 with build-id: 837a5925296d941416ad9ba577a593ea7542051a
                Found module libqmi-glib.so.5 with build-id: a9d793244a1efaead6cd9e9ecd7021c8909c5781
                Found module libmm-glib.so.0 with build-id: cd41b3908f77cf3371f5c1c12c65c8e314c3ac66
                Found module libfu_plugin_modem_manager.so with build-id: ed9c60c505f2f1389ce38117925cbe312cc6d3d6
                Found module libgcc_s.so.1 with build-id: e3a44e0da9c6e835d293ed8fd2882b4c4a87130c
                Found module libstdc++.so.6 with build-id: e37fe1a879783838de78cbc8c80621fa685d58a2
                Found module libicudata.so.70 with build-id: b1c2496dd0543023c7a19c961bb7f3abc818f465
                Found module libresolv.so.2 with build-id: 01c8e0c8389941a2ff675b7e41799362d24cd30b
                Found module libkeyutils.so.1 with build-id: ff27227afa5eeddccab180dd29bd7fcff94aea7c
                Found module libicuuc.so.70 with build-id: bef3ff1d70aadd68aab07d858a759360c8b919ae
                Found module libbrotlicommon.so.1 with build-id: 43a72967cf84155914c8b3e915926733d1e57c11
                Found module libsasl2.so.2 with build-id: b8a924f277180f8743a0c6463a379b1a4ad1aae5
                Found module libkrb5support.so.0 with build-id: 384ac9986064cbae89ac8b2e33eb3604b5ab0395
                Found module libcom_err.so.2 with build-id: ce0901f10854b3c9276066b98d9a72303206e0d5
                Found module libk5crypto.so.3 with build-id: f7765f61555fd50c7960ea84cbb9609e7062a667
                Found module libkrb5.so.3 with build-id: fa7fe8222982647202746ba1275861042f966623
                Found module libassuan.so.0 with build-id: 6576f1e90e9cbc143a696846874f00a68d77441e
                Found module libpcre2-8.so.0 with build-id: 184a841c55fb7fe5e3873fcda8368c71016cd54c
                Found module libblkid.so.1 with build-id: ecc1dfaec3a7241b41b76c3590fa135fb3c8ddfa
                Found module libxml2.so.2 with build-id: aebf8e42966c3ce475ff9d9d51a762831adcbb61
                Found module libbz2.so.1.0 with build-id: e56b62c27bcc7ace8f9be36b255bd7b31bfde405
                Found module libacl.so.1 with build-id: 99117132cdc6e4b34c4d798bb10da1de61737c6d
                Found module libbrotlidec.so.1 with build-id: 4b1f390dd6e24d49684db8b2443d082379e8e977
                Found module liblber-2.5.so.0 with build-id: 1292a1dfb27c835a00883ee0b3995ad63723c52b
                Found module libldap-2.5.so.0 with build-id: 981fe2286740ff248aff7d837a8fb2cd254448b3
                Found module libgssapi_krb5.so.2 with build-id: 0204867906c20c8d6c55fb2a7a9950fa96c34b53
                Found module libpsl.so.5 with build-id: 2b1afc1a3bc8bdb016e432c50db058632e7895b9
                Found module libssh.so.4 with build-id: b7fd78c4b3609dd386755b09bba2fb6b096d906b
                Found module librtmp.so.1 with build-id: 9517ef375cd71ea3da824b4118f1599735093d66
                Found module libnghttp2.so.14 with build-id: b02e3f0f2201e893e2dc948840c6e380484c9623
                Found module libtss2-mu.so.0 with build-id: 41ff47bf67f0973f0bc81e14ad0238969851cf8b
                Found module libtss2-sys.so.1 with build-id: e397a01da2eb9cf8ce6ca550e29a0e2062bb7c03
                Found module libcrypto.so.3 with build-id: ca84e22a798dabf117de600cb13469a59f775d2a
                Found module libgmp.so.10 with build-id: f110719303ddbea25a5e89ff730fec520eed67b0
                Found module libhogweed.so.6 with build-id: 3cc4a3474de72db89e9dcc93bfb95fe377f48c37
                Found module libnettle.so.8 with build-id: 3d9c6bf106ef53d625b7b1c8bb1300e84598a74a
                Found module libtasn1.so.6 with build-id: 2fde6ecb43c586fe4077118f771077aa1298e7ea
                Found module libunistring.so.2 with build-id: ca5149da8d5a298b8f286ffca3d6e2402ec0fe01
                Found module libidn2.so.0 with build-id: 45b73e0e1c46a76be22f572ee98c60af5768bf8f
                Found module libp11-kit.so.0 with build-id: a0ffe1d002de5812dc718186172efb78604ddf2c
                Found module libusb-1.0.so.0 with build-id: 8974a74dbeb0e144e076801cc8d7dea1423597b0
                Found module libudev.so.1 with build-id: 210cc9ab74e8bd81fb3e29d554ee84d02a67ee73
                Found module libgpg-error.so.0 with build-id: 3fbec71c67bee60d8aef00697ee187079b0fb307
                Found module libgpgme.so.11 with build-id: 066c509ae563478588801b6de0da3fd6f4701941
                Found module libm.so.6 with build-id: b55ba6d8b5954b479fab2a69a54b9f56451fbee0
                Found module libpcre.so.3 with build-id: 3982f316c887e3ad9598015fa5bae8557320476a
                Found module libffi.so.8 with build-id: 59c2a6b204f74f358ca7711d2dfd349d88711f6a
                Found module libselinux.so.1 with build-id: 6fa53202ce676297de24873c886443b2759bfd8a
                Found module libmount.so.1 with build-id: a339abbcd0eb8dadcbd09c372ffac2f0eb31eeaa
                Found module libz.so.1 with build-id: 30840b79ac329ecbf1dec0bb60180eed256d319f
                Found module ld-linux-x86-64.so.2 with build-id: 246ac0d8deba5a40c63e9a1a87d4d779d8eb589f
                Found module libgcrypt.so.20 with build-id: 60a5e524de0ed8323edf33e9eb9127a9eee02359
                Found module libcap.so.2 with build-id: b4bf900abf14aabe12d90988ceb30888acb2bcb0
                Found module liblz4.so.1 with build-id: a85971851cd059f1af80d553c8e7170d42ec59a1
                Found module libzstd.so.1 with build-id: 5d9d0d946a3154a748e87e17af9d14764519237b
                Found module libcbor.so.0.8 with build-id: acad0db0549f0dc5f0cd0bc9b187943f507d9650
                Found module libarchive.so.13 with build-id: 73292bff64f2645587784b836b4acee8dc5db313
                Found module liblzma.so.5 with build-id: b85da6c48eb60a646615392559483b93617ef265
                Found module libgcab-1.0.so.0 with build-id: c1a202be8fea4fd0efe850c1c866f8e6efc9a71c
                Found module libgmodule-2.0.so.0 with build-id: 8b369a368c3070d179ddf64724ffc229c3f214b5
                Found module libcurl-gnutls.so.4 with build-id: 3171eb263c65a3a1553f96743908b140de46fe87
                Found module libtss2-esys.so.0 with build-id: 4335ca9b7ade7f1492eb391c421f7b9e7eec0517
                Found module libsmbios_c.so.2 with build-id: 9aaa3d9dd8d57433781d2bdcd4bae6c0c2948e96
                Found module libprotobuf-c.so.1 with build-id: 46375adf68b84de17698f2b4329f975a208cbb93
                Found module libgnutls.so.30 with build-id: 97b8f99f392f1fd37b969a7164bcea884e23649b
                Found module libsqlite3.so.0 with build-id: 87d00c07f9d8a822a4251d4f053484e5c0e4ead8
                Found module libpolkit-gobject-1.so.0 with build-id: a5c9ffbd93ee5ce4d2822f14f44af5175f8f7557
                Found module libgusb.so.2 with build-id: 275af99665117e5aa0691192dff076b34c0c5e09
                Found module libgudev-1.0.so.0 with build-id: b8325dee54d53266618de95232d1755edea29006
                Found module libjson-glib-1.0.so.0 with build-id: ad0e4fa336337086be19bf34bf6cc3abcf7a73de
                Found module libjcat.so.1 with build-id: 440c4c05734c798e81b373bd7f5911fd214c74b1
                Found module libc.so.6 with build-id: 962015aa9d133c6cbcfb31ec300596d7f44d3348
                Found module libxmlb.so.2 with build-id: e733bebdbfce669d59ca062a240d4ea8aaac859a
                Found module libglib-2.0.so.0 with build-id: c74e800dfd5f72649d673b44292f4a817e45150b
                Found module libgobject-2.0.so.0 with build-id: 7c47809b4e688382aab4127a2e07496450c5e6b0
                Found module libgio-2.0.so.0 with build-id: 07bd46a1bb58e321e6aabc67135d054e6b78069d
                Found module libsystemd.so.0 with build-id: b4247262ea7b9c36291d28f0538bb3d21d338274
                Found module libfwupdplugin.so with build-id: c14f9fe6e8a6a25848df64675b90a6063a4a6952
                Found module libfwupd.so.2 with build-id: 7a4225a08a4e0b4118d3334a4260ab5904c7b5cd
                Found module libfwupdengine.so with build-id: a0fed712f2b504686be9789349a9321e800609f4
                Found module fwupd with build-id: ddbe63575779c346367ab7ed7010193acf9699da
                Stack trace of thread 4066:
                #0  0x00007321452969fc __pthread_kill_implementation (libc.so.6 + 0x969fc)
                #1  0x0000732145242476 __GI_raise (libc.so.6 + 0x42476)
                #2  0x00007321452287f3 __GI_abort (libc.so.6 + 0x287f3)
                #3  0x0000732145644b57 n/a (libglib-2.0.so.0 + 0x1eb57)
                #4  0x000073214569e70f g_assertion_message_expr (libglib-2.0.so.0 + 0x7870f)
                #5  0x0000732145604548 n/a (libxmlb.so.2 + 0x9548)
                #6  0x00007321457afec5 n/a (libgio-2.0.so.0 + 0x4fec5)
                #7  0x00007321457de1f7 g_input_stream_read (libgio-2.0.so.0 + 0x7e1f7)
                #8  0x000073214560a22c xb_builder_compile (libxmlb.so.2 + 0xf22c)
                #9  0x000073214560b200 xb_builder_ensure (libxmlb.so.2 + 0x10200)
                #10 0x0000732145a80389 n/a (libfwupdengine.so + 0x80389)
                #11 0x0000732145a87d9b fu_engine_load (libfwupdengine.so + 0x87d9b)
                #12 0x00005799193618d2 fu_daemon_setup (fwupd + 0xc8d2)
                #13 0x000057991935c038 main (fwupd + 0x7038)
                #14 0x0000732145229d90 __libc_start_call_main (libc.so.6 + 0x29d90)
                #15 0x0000732145229e40 __libc_start_main_impl (libc.so.6 + 0x29e40)
                #16 0x000057991935c2e5 _start (fwupd + 0x72e5)
                
                Stack trace of thread 4067:
                #0  0x0000732145318bcf __GI___poll (libc.so.6 + 0x118bcf)
                #1  0x00007321456d11f6 n/a (libglib-2.0.so.0 + 0xab1f6)
                #2  0x00007321456793e3 g_main_context_iteration (libglib-2.0.so.0 + 0x533e3)
                #3  0x0000732145679431 n/a (libglib-2.0.so.0 + 0x53431)
                #4  0x00007321456aaa51 n/a (libglib-2.0.so.0 + 0x84a51)
                #5  0x0000732145294ac3 start_thread (libc.so.6 + 0x94ac3)
                #6  0x0000732145326850 __clone3 (libc.so.6 + 0x126850)

GNU gdb (Ubuntu 12.1-0ubuntu1~22.04) 12.1
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/libexec/fwupd/fwupd...
(No debugging symbols found in /usr/libexec/fwupd/fwupd)
[New LWP 4066]
[New LWP 4067]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/libexec/fwupd/fwupd'.
Program terminated with signal SIGABRT, Aborted.
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=126586703063808) at ./nptl/pthread_kill.c:44
44	./nptl/pthread_kill.c: No such file or directory.
[Current thread is 1 (Thread 0x732143782b00 (LWP 4066))]
(gdb)

**Comment by leigh123linux** [comment]
You will need to file your issue against ubuntu fwupd package.
