### ISSUE TITLE
Background Process not allowed for Pika Backup

### ISSUE THREAD

**Issue by hugh-osb** [linuxmint/cinnamon#12188]
### Distribution

Minte 21.3

### Package version

6.0.4

### Graphics hardware in use

AMD Radeon R9 M395/ M395X Mac Edition

### Frequency

Always

### Bug description

I cannot use the scheduling in Pika backup as the background process is not allowed.
![Screenshot from 2024-05-11 22-42-31](https://github.com/linuxmint/cinnamon/assets/169561538/715b4c97-a710-4668-8968-db72dbf30f66)

### Steps to reproduce

Open Pika, select enable scheduled backups, error message

### Expected behavior

The backup scheduling should be allowed

### Additional information

On some forums there is a suggestion that the error is due to the xdg-desktop-portal-gtk needing to be upgraded from 1.14 to 1.16

**Comment by mtwebster** [comment]
Implemented in xdg-desktop-portal-xapp: https://github.com/linuxmint/xdg-desktop-portal-xapp/commit/4be1618e39f8afe32a1419e0ad9b5588594bf500

Will be in Mint 22
