### ISSUE TITLE
Open windows in center of the screen

### ISSUE THREAD

**Issue by Paviluf** [linuxmint/Cinnamon#1219]
Include the option for setting that windows open by default centered on the screen.

**Comment by anandrkris** [comment]
Folks - There is a PR and if all goes well, we will hopefully see this in *next* version of Cinnamon.
https://github.com/linuxmint/Cinnamon/pull/3945

**Comment by dreamhunt** [comment]
And option to remember position and size would be nice. It's very annoying popups from FF for example to popup in the middle of the screen. Like smiles in phpbb3 for example.
