### ISSUE TITLE
Linux mint latest update broke the VPN SSR app

### ISSUE THREAD

**Issue by bryanray** [linuxmint/cinnamon#12209]
### Distribution

21.1.3

### Package version

0

### Frequency

Always

### Bug description

![332984205-125f211e-b15e-4689-a093-ad01fa7bd992](https://github.com/linuxmint/cinnamon/assets/1768531/d323d806-3724-41e0-89ef-b3454dbe97fc)

### Steps to reproduce

0

### Expected behavior

0

**Comment by bryanray** [comment]
it used to work with default installation of "Linux Mint 21.3, codename Virginia."
after today's first time internet connection to update installation, it fail to open and produce this message.

**Comment by leigh123linux** [comment]
The quality of this report  is very low, it's lacking the basic requested info, also it's reported against the wrong  component.

Report your issue against the app that has crashed.
