### ISSUE TITLE
Alt Clicking moves the window

### ISSUE THREAD

**Issue by NagrandHero** [linuxmint/cinnamon#12207]
### Distribution

Linux Mint 21.3 x86_64 

### Package version

Cinnamon 6.0.4

### Graphics hardware in use

AMD 7800XT

### Frequency

Always

### Bug description

No matter what your Move Window shortcut is set to holding alt and dragging the window with left click will move the window

### Steps to reproduce

Hold ALT and drag with left click

### Expected behavior

For nothing to happen

### Additional information

I have never changed the short cut from Alt+F7

**Comment by mtwebster** [comment]
This is normal behavior, to make it easy to drag from any part of the window (in case the title bar ended up off-screen).

You can disable this in Cinnamon's window settings -> Moving and Resizing -> "Special key to move and resize..."
