### ISSUE TITLE
Battery icon shows charging and using battery at the same time

### ISSUE THREAD

**Issue by Sugarcrisp-ui** [linuxmint/cinnamon#12211]
### Distribution

Mint 21.1

### Package version

5.6.8

### Frequency

Always

### Bug description

When laptop battery is plugged in and charging the battery icon correctly shows the battery charging symbol, but when you hover the mouse over the battery it says that it's running on battery

### Steps to reproduce

I've confirmed on 2 separate laptops the it is repeatable on both

### Expected behavior

The symbol is correct, but the message should say 'charging battery' or 'fully charged'

**Comment by rcalixte** [comment]
Fixed in #12053

**Comment by Sugarcrisp-ui** [comment]
If the issue is fixed, why do I see the issue on 2 laptops running 21.1
that are updated?

**Comment by rcalixte** [comment]
> If the issue is fixed, why do I see the issue on 2 laptops running 21.1 that are updated?

> running 21.1
> ### Package version
> 5.6.8


You are running an older version of Cinnamon. This will be released with Cinnamon 6.2 and Linux Mint 22.0.

**Comment by Sugarcrisp-ui** [comment]
Thanks Rick
