### ISSUE TITLE
Clicking panel in fullscreen hides it instead of performing an action, like opening an applet

### ISSUE THREAD

**Issue by iWisp360** [linuxmint/cinnamon#12224]
### Distribution

Mint 21.3

### Package version

6.0

### Graphics hardware in use

NVIDIA RTX 2060

### Frequency

Always

### Bug description

Whn I play games, sometimes I want to adjust volume, and to do that I press Super, and then I click on the audio applet to modify volume, but in cinnamon that isn't possible, to access the panel I have to open another app, like Nemo, alt+tab it and panel is accessible again.

### Steps to reproduce

1- Open a fullscreen game or app
2- Press Super Key
3- Click on any app or applet from the panel

### Expected behavior

Pressing super to show panel and clicking on an app should open it and clicking on an applet should open it.

**Comment by JosephMcc** [comment]
https://github.com/linuxmint/cinnamon/issues/11658
