### ISSUE TITLE
Sound applet-transparency in cover art

### ISSUE THREAD

**Issue by gauravjuvekar** [linuxmint/Cinnamon#1222]
For a PNG non-square cover art made square by adding transparency, the transparent areas get replaced by black colour in the sound applet.
Ideally, they should take the same color as the background(hence transparent) of the applet as determined by the theme so that rectangular images made square with transparency would look good.

(Such transparent images are needed if one wants to use a non-square image for cover art because most players resize such images to a square thus changing the aspect ratio. Note that the sound applet also resizes rectangular images to square so the images need to be made square with transparency to preserve the aspect ratio.)

Edit: Sound applet renders well the images that are taller than they are wider(without transparency) This is only a problem for landscape images. Landscape images are squashed to square thus changing the aspect ration.

**Comment by JosephMcc** [comment]
Is this still an issue in the revamped sound applet in Cinnamon 2.8?

**Comment by anandrkris** [comment]
@gauravjuvekar - Is this still an issue in latest Cinnamon 3?

**Comment by JosephMcc** [comment]
I'm closing this since it's been almost a year since the last response to this.
