### ISSUE TITLE
FEATURE REQUEST

### ISSUE THREAD

**Issue by ukmint7** [linuxmint/cinnamon#12231]
Please use:

A feature  'MOVE to' or 'COPY to' an object such as a file or folder to a new or different location by selecting it and pressing a short-cut key like 'Alt/Shift+M' (for Move to ) or 'Alt/Shift+C' (for Copy to) is highly desirable.
I found a similar feature in Faststone Image Viewer, where pressing M or C moves/copies the selected file to the new location.
Thanks.

**Comment by Secret-chest** [comment]
Shift-M and Shift-C are for typing, Alt-M and Alt-C are for menu navigation. You must use Control.

**Comment by rcalixte** [comment]
Duplicate of linuxmint/discussions#493
