### ISSUE TITLE
"Reboot" button logs the user out instead of rebooting

### ISSUE THREAD

**Issue by rado84-github** [linuxmint/cinnamon#12244]
### Distribution

Arch

### Package version

6.2.0

### Graphics hardware in use

GTX 1660 Ti

### Frequency

Always

### Bug description

When you open the menu, click the power button and then "reboot", instead of rebooting the computer, the user is being logged out and you have to either login again OR use the GDM's reboot option while logged out.

### Steps to reproduce

1. Open menu.
2. Click the power button.
3. Click "reboot".
4. Observe you being logged out instead of reboot.

### Expected behavior

Clicking "reboot" button should reboot the computer.

**Comment by leigh123linux** [comment]
closed https://github.com/linuxmint/cinnamon-session/issues/173
