### ISSUE TITLE
Wireguard doesn't work

### ISSUE THREAD

**Issue by ilcobrapizzica** [linuxmint/cinnamon#12257]
### Distribution

21.3 Cinnamon

### Package version

6.0.4

### Graphics hardware in use

Iris Plus 655

### Frequency

Always

### Bug description

After the last 2 updates wireguard doesn't work.
It works only if I restore a backup of 15 days ago.
If I update the system it doesn't work again.
Can you please fix the problem?

### Steps to reproduce

It works only if I restore a backup of 15 days ago.
If I update the system it doesn't work again.

### Expected behavior

Can you restore the network configuration like was 15 day ago?

### Additional information

Openvpn works correctly.
Only wireguard has problems.

**Comment by leigh123linux** [comment]
This isn't a cinnamon code issue, please file your issue at https://github.com/linuxmint/linuxmint/issues
