### ISSUE TITLE
British locale Rubbish Bin Context menu says "WasTebasket" should be Rubbish Bin

### ISSUE THREAD

**Issue by lemonzest79** [linuxmint/cinnamon#12268]
### Distribution

Fedora 40 Cinnamon

### Package version

6.2.2

### Graphics hardware in use

AMD Radeon RX 6600 XT

### Frequency

Always

### Bug description

In the British locale Rubbish Bin Context menu says "WasTebasket" should be Rubbish Bin

### Steps to reproduce

With the locale set to en_GB Right Click the Rubbish Bin Icon in Nemo

![image](https://github.com/linuxmint/cinnamon/assets/40669977/f3619531-4649-4116-8429-99a948e9ddfc)

### Expected behavior

To say "Empty Rubbish Bin"

**Comment by clefebvre** [comment]
Fixed in next translation update.
