### ISSUE TITLE
File Open/Save (As) dialog does not show all original matches for emptied search text box

### ISSUE THREAD

**Issue by Fool4UAnyway** [linuxmint/cinnamon#12263]
### Distribution

Linux Mint Cinnamon

### Package version

Cinnamon 6.0.4

### Graphics hardware in use

Nothing special, NVidia 730

### Frequency

Always

### Bug description

I did not check all dialogs, but it happens in the File Open dialog and in some File Save (As) dialogs.

When entering text (characters) and they do appear in the search entry text box, the according search results, matching files and folders, are shown.

With each additional character entered, the search result set may shrink, as there possibly are fewer matches.

When deleting a character, the search result set may grow again, because of more (original) matches.

Unfortunately, this is not true for the last character being deleted: the result set won't change anymore. It will keep showing all results for the the last character removed (one could overwrite it, so not necessarily the first character entered).

I expect all files and folders to be shown again.

### Steps to reproduce

Open a File Open dialog.

Press any character and one or some more.

Then remove all additional characters one by one.

Remove the last character.

Repeat this a couple of times with another starting character.

### Expected behavior

When the last remaining character is removed, all files and folders should be shown again.

### Additional information

Not all Save (As) dialogs show the behavior for the search box. Others have the focus on the file name to be used, so anything typed will have an effect on that name.

**Comment by leigh123linux** [comment]
Closed, see https://github.com/linuxmint/cinnamon/issues/9130#issuecomment-577415625
