### ISSUE TITLE
Some application buttons in Window List and Grouped Window List continue to demand attention even after being focused

### ISSUE THREAD

**Issue by mdpenguin** [linuxmint/cinnamon#12269]
### Distribution

Mint 21.3

### Package version

6.0.4

### Graphics hardware in use

Intel Corporation HD Graphics 630

### Frequency

Always

### Bug description

When an application already has a window open and a second instance is started then the button for the second instance on the Window List is highlighted for attention even if it is already in focus.  If a user clicks on the window, it remains highlighted.  If a user clicks on the button in the Window List then it minimizes the window but it remains highlighted for attention.

This happens with both the Window List and Grouped Window List applets.  For the Grouped Window List applet, grouping has to be turned off to see the issue.

This does not happen for all applications, but always happens for the ones that are affected.  I've confirmed the behavior with both Firefox & LibreOffice.

Editing the dconf settings for /org/cinnamon/demands-attention-passthru-wm-classes to exclude Firefox and that makes it so that clicking on the second instance of Firefox clears the attention demand highlight but it also means that Firefox doesn't receive focus upon launching, so that doesn't seem to be a good solution.

### Steps to reproduce

1. Open an instance of Firefox
2. Open a second instance of Firefox (screenshot 1)
3. Note that the second instance is highlighted as demanding attention (screenshot 2)
4. Click on second instance of Firefox to confirm that it is in focus
5. Note that it remains highlighted as demanding attention (screenshot 3)
6. Click on button in Window List for second instance of Firefox
7. Note that the window is minimized but is still highlighted as demanding attention (screenshot 4)

Screenshot 1:
![image](https://github.com/linuxmint/cinnamon/assets/122059580/73b56dca-d803-489b-9ce9-d39b6167af9f)

Screenshot 2:
![image](https://github.com/linuxmint/cinnamon/assets/122059580/bf97e209-9ceb-471e-9e92-49eadd8c32ec)

Screenshot 3:
![image](https://github.com/linuxmint/cinnamon/assets/122059580/9558fc34-bf5f-4c09-bd0a-a1507bde4fcc)

Screenshot 4:
![image](https://github.com/linuxmint/cinnamon/assets/122059580/1a8c0d37-6e1f-4b9e-8cb3-4c621f0e42e8)

### Expected behavior

If the second instance of the program opens in focus or the user clicks on it then the button should not be highlighted to demand attention

**Comment by mdpenguin** [comment]
A potential solution is to raise and focus the window in the WindowAttentionHandler rather than activating it.  I've deployed a similar solution to the extension focus-new-window@mdpenguin in https://github.com/linuxmint/cinnamon-spices-extensions/pull/659, but there's more done when using the activate method (e.g. handling when window is on another workspace) so maintainers may wish to consider other options (e.g. using unset_demands_attention method).

**Comment by rcalixte** [comment]
> A potential solution is to raise and focus the window in the WindowAttentionHandler rather than activating it. I've deployed a similar solution to the extension focus-new-window@mdpenguin in [linuxmint/cinnamon-spices-extensions#659](https://github.com/linuxmint/cinnamon-spices-extensions/pull/659), but there's more done when using the activate method (e.g. handling when window is on another workspace) so maintainers may wish to consider other options (e.g. using unset_demands_attention method).

Did you test with an activate and the other methods? They're redundant but with differing functionality so I think stacking them in the extension might work without too much overhead.

**Comment by mdpenguin** [comment]
Looking over the Muffin code a little more, I think that some logic will be needed to check that it is in the current workspace prior to using unset_demands_attention.  I'll do some more testing later in the week and submit a PR if it looks like it will work out (along with another one for the extension to keep aligned with the default functionality).

**Comment by mdpenguin** [comment]
Upon further review, the issue was with the Window List and Grouped Window List applets and has been addressed with https://github.com/linuxmint/cinnamon/pull/12006, so I've put in a PR to revert the changes to focus-new-window@mdpenguin (see https://github.com/linuxmint/cinnamon-spices-extensions/pull/661) and am closing this bug report.
