### ISSUE TITLE
Several issues with the Network applet

### ISSUE THREAD

**Issue by nclm** [linuxmint/Cinnamon#1227]
I use Cinnamon for two weeks now, and while the rest of the experience is great, I've got some troubles with the Wifi applet.

* When I click on the network I'm already connected to, it's probably because I've got an issue with it and I would like to reconnect to it (ie. disconnect then connect again). It works like that on other desktops, but currently Cinnamon does nothing (ignores the click).

* When I didn't choose any network yet (and I guess when my favourite ones are not available) Cinnamon seems to automatically selects a random one, even if it's locked. So it asks me a password, that I don't know. I cancel, but a second different dialogue window opens (from standard Gnome?) and I have to cancel a second time (so that's another bug) before actually be able to choose the network I want. Cinnamon just shouldn't choose any locked network automatically. 

* There are a lot of networks in my area, more than fifty. Cinnamon shows only about ten (six at the moment) at first, and offer you a “More…” button to see the others. That's okay. When you click on it, the fifty other networks are shown, but in a scrollable list, independent to the first. So you have six network inexplicably pinned to the top of the menu, and the other underneath are scrollable.

* And they are seemingly random. I can't understand why the first/pinned ones are these ones, nor in what order are the other ones. It's neither alphabetical order, neither sorted by availability percentages. It's not easy to find the network you want.

* When several networks have the same name, they are regrouped under the same line, with a little arrow that unfold new lines to specifically choose the one you want. That's good. But what happens is that very often (notably when in the middle of a long list) it doesn't work at all. The little arrow doesn't unfold anything, no new items appears, and you can't choose a specific network. Worse, you will not even be able to select any of these homonym networks because the only item where you can click is the one with the little arrow, that happens to be only here to unfold what doesn't unfold today.

So most of the time I open the Network Preferences window because of all these little issues in the applet. I really like the rest of Cinnamon, though :)

**Comment by JosephMcc** [comment]
Closed due to lack of response.
