### ISSUE TITLE
cinnamon should not depend on network-manager

### ISSUE THREAD

**Issue by OlafTitz** [linuxmint/cinnamon#12279]
### Distribution

Mint 21.3

### Package version

6.0.4

### Graphics hardware in use

not relevant

### Frequency

Always

### Bug description

I have a system with static network configuration, switched from Ubuntu to Mint, and want to get rid of all unnecessary stuff on that machine. NetworkManager is not needed here and nm-applet is useless, but I want to use cinnamon.

### Steps to reproduce

apt remove network-manager
--> it wants to remove cinnamon too, because of a hard dependency

### Expected behavior

cinnamon should not Depends: network-manager-gnome, a Recommends: is enough.

### Additional information

see also #10131

**Comment by leigh123linux** [comment]
Build it yourself if you don't like the package.

https://github.com/linuxmint/cinnamon/blob/master/meson_options.txt#L16

**Comment by leigh123linux** [comment]
Or you could disable NM if you don't need it.

```
systemctl disable NetworkManager.service
```
