### ISSUE TITLE
xlet-settings list widget - add/edit segfault

### ISSUE THREAD

**Issue by fredcw** [linuxmint/cinnamon#12270]
### Distribution

Mint 22, Manjaro

### Package version

Cinnamon 6.2

### Frequency

Always

### Bug description

xlet-settings "list" widget. When trying to add or edit a list entry, a segfault occurs. Only seems to happen in list widgets that have an "icon" column.

reported by @pegasusearl on [spices](https://cinnamon-spices.linuxmint.com/applets/view/281#count)

### Steps to reproduce

Using applet CinnVIIStarkMenu@NikoKrause, go to configure->Quicklauncher->Quicklauncher Places or configure->Web Search->Web Search Engine.
Click on "+" to add a new entry.
In "Add new entry" dialog, simply click "Cancel" or enter any values and click "OK" and xlet-settings.py crashes.

### Expected behavior

No crash.

### Additional information

Crash occurs in TreeListWidgets.py
```
[fred@fred-manjaro-cinnamon ~]$ xlet-settings applet CinnVIIStarkMenu@NikoKrause
/usr/share/cinnamon/cinnamon-settings/bin/TreeListWidgets.py:321: Warning: g_object_set_qdata: assertion 'G_IS_OBJECT (object)' failed
  dialog.destroy()
/usr/share/cinnamon/cinnamon-settings/bin/TreeListWidgets.py:321: Warning: instance with invalid (NULL) class pointer
  dialog.destroy()
/usr/share/cinnamon/cinnamon-settings/bin/TreeListWidgets.py:321: Warning: g_signal_handlers_destroy: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
  dialog.destroy()
Segmentation fault (core dumped)
```

Bug not present in Cinnamon 6.0

**Comment by rcalixte** [comment]
This is possibly related to #11908. Can you revert that locally and see if it fixes the issue? If so, we can ping @klangman to see about fixing both bugs (including the one the PR fixed).

**Comment by fredcw** [comment]
> Can you revert that locally and see if it fixes the issue?

Just tried that but it doesn't make a difference. Since the bug is not present in cinnamon 6.0, I tried looking for recent changes but couldn't find anything :/ Only translations have changed in the applet.

**Comment by klangman** [comment]
Was Python upgraded in 22? If so, maybe it's worth trying to revert Python.

**Comment by rcalixte** [comment]
> Was Python upgraded in 22? If so, maybe it's worth trying to revert Python.

We could test on an updated LMDE 6 environment, live (with updates) or installed once Cinnamon 6.2 is in the repos.

**Comment by mchilli** [comment]
Hey, I stumbled upon the same issue. But not only in the" TreeListWidget", also in my applet with a custom dialog and a "XAppIconChooserButton" in it. I get the same error when the code want to destroy the dialog:
```
/home/user/.local/share/cinnamon/applets/app-launcher@mchilli/dialogs.py:94: Warning: g_object_set_qdata: assertion 'G_IS_OBJECT (object)' failed
  self.dialog.destroy()
/home/user/.local/share/cinnamon/applets/app-launcher@mchilli/dialogs.py:94: Warning: instance with invalid (NULL) class pointer
  self.dialog.destroy()
/home/user/.local/share/cinnamon/applets/app-launcher@mchilli/dialogs.py:94: Warning: g_signal_handlers_destroy: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
  self.dialog.destroy()
[1]    168956 segmentation fault (core dumped)  xlet-settings applet app-launcher@mchilli
```
But only when I click on the IconChooserButton and the dialog appears. Then it doesn't matter if I change the icon or press cancel, after I click ok or cancel in my dialog, the whole thing crashes.
Maybe it has something to do with the XAppIconChooserDialog?!
