### ISSUE TITLE
Update Manager wipes /var/lib/dpkg on a fresh Encrypted ZFS install

### ISSUE THREAD

**Issue by jack-avery** [linuxmint/cinnamon#12286]
### Distribution

Mint 21.3

### Package version

6.0.4

### Graphics hardware in use

Intel GeminiLake [UHD Graphics 600] (integrated graphics, irrelevant to this issue)

### Frequency

Always

### Bug description

When installing Linux Mint with Encrypted ZFS the installation completes as usual. Running Update Manager -- and updating it when prompted -- processes for a bit, before booting the user from their session and leaving `/var/lib/dpkg` empty.

### Steps to reproduce

1. Perform a fresh installation of Linux Mint 21.3, selecting multimedia codecs and ZFS with Encryption.
2. Open Update Manager -- it requests an update -- run it
3. The user is booted out of their session, and upon logging back in, `/var/lib/dpkg` is empty.

### Expected behavior

Update Manager should not wipe `/var/lib/dpkg`.

### Additional information

`/var/lib/dpkg` is populated as normal right after the install. Upon running the Update Manager update and escalating privilege for Synaptic to do its' thing, the user is booted from their session back to the login screen, and `/var/lib/dpkg` is empty.

I cannot test whether this occurs beyond a fresh install as I don't have an existing Encrypted ZFS install to test with, but I assume it would occur just the same.

I am not sure whether this is related to Linux Mint itself, the Synaptic package manager, encrypted ZFS, or a combination of any of the above.

This does not occur on a regular (selecting no advanced options) fresh installation. This does not occur when performing a regular update using `sudo apt update && sudo apt upgrade` -- which also updates the Update Manager correctly.

**Comment by carlosmintfan** [comment]
Oh no. Please report this to https://github.com/linuxmint/mintupdate

**Comment by jack-avery** [comment]
> Oh no. Please report this to https://github.com/linuxmint/mintupdate

Mirrored. Closing this as a duplicate of the more appropriate https://github.com/linuxmint/mintupdate/issues/885
