### ISSUE TITLE
Cinnamon (the package itself) 6.2.2 fails to resume from suspend

### ISSUE THREAD

**Issue by rado84-github** [linuxmint/cinnamon#12297]
### Distribution

Arch Linux, 6.6.35-LTS kernel

### Package version

6.2.2

### Graphics hardware in use

GTX 1660 Ti, driver 555.58

### Frequency

Always

### Bug description

When I go to sleep, I put the computer to sleep as well. In the morning when I press a keyboard key, I expect the display to light up and to show me the desktop. However, with the package cinnamon-6.2.2 that doesn't happen: fans are spinning but the desktop doesn't show up. I tested it extensively with cinnamon 6.2.2 and it seems to happen after every "putting the computer to sleep", even after a complete system reboot.

### Steps to reproduce

1. Have cinnamon DE with the package cinnamon 6.2.2 installed.
2. Put the computer to sleep (suspend to RAM). To be more specific, use the option in keyboard settings, like I did:
![Picture_created_20-07-2024_14-35-56](https://github.com/user-attachments/assets/3f96e84c-ef76-44cb-b687-7129baddcf29)
3. Use that key to suspend the system. Wait 5 minutes or more than press any key to resume.
4. You'll see that the fans are spinning but the display won't light up to show you the desktop. At this point your only option left is to flip the PSU power switch to zero and then flip it back to 1 in order to boot from scratch. Only  then will the DE show up.

### Expected behavior

Resuming from suspend should show the desktop.

### Additional information

I've tested this for the last 90 minutes and it happens every time for as long as cinnamon 6.2.2 (only this package itself) is installed. Downgrading to cinnamon 6.2.0 (and restart cinnamon/the X server/the system) fixes the problem and the desktop shows up normally after every resuming.

**Comment by leigh123linux** [comment]
Report your issue to the archlinux bug tracker, nothing in cinnamon changed to cause this.

https://github.com/linuxmint/cinnamon/compare/6.2.0...6.2.2
