### ISSUE TITLE
Thunderbird displays an odd icon in panel bar

### ISSUE THREAD

**Issue by pauldl58** [linuxmint/cinnamon#12306]
### Distribution

Mint 22

### Package version

6.2.7

### Frequency

Always

### Bug description

This also happened in the beta. When I open Thunderbird and click on new message, I get this ugly pencil icon with the number 2 in the panel bar. That shouldn't be there. The number 2 should be displayed in the actual Thunderbird icon. The ugly pencil shouldn't be there.

### Steps to reproduce

Open Thunderbird and click on new message, You will see an ugly pencil icon appear with the number 2 in the panel bar. 

### Expected behavior

The number 2 should be displayed in the actual Thunderbird icon. The ugly pencil shouldn't be there.
![qJALphKD6gAuGNnJ](https://github.com/user-attachments/assets/b0605e46-a005-4c42-a208-2788b52d066d)

**Comment by DirkHaar** [comment]
It seems you have 2 thunderbird threads/instances open, i.e., TB and your new editing message.
Your panel app "stacks" instances and shows the number of windows/instances...
(I don't this app, so don't ask for the name).
The ugly pencil is part of the theme you chose - my icon is the standard envelope.

**Comment by pauldl58** [comment]
To DirkHaar:

It worked normally in all the past versions of Linux Mint that I have used. Been using Mint Cinnamon for years.

I added the Thunderbird app to the panel using the same method I always have. I right click the Thunderbird icon in the menu, select "Add to panel".

I click on the icon that was added to the panel to open Thunderbird as I always do. The ugly icon is something new.

Again version 21.3 didn't do this.

This is definitely a bug, not user error. 20+ year Linux user.

Theme:  Mint L Aqua ( nothing exotic )

Thanks for trying to help.

**Comment by mtwebster** [comment]
This will be fixed in the next thunderbird release. For now if you'd like to apply the fix:

Edit `/usr/share/applications/thunderbird.desktop` (as root), around line 106 where it has `StartupNotify=true`, add or insert:
```
StartupWMClass=thunderbird-esr
```

**Comment by tony1661** [comment]
I can confirm this fixed the issue for me as well
