### ISSUE TITLE
Legacy tray icons break Gsync VRR

### ISSUE THREAD

**Issue by SpoOokY1983** [linuxmint/cinnamon#12308]
### Distribution

Mint 22 Cinnamon

### Package version

6.2

### Graphics hardware in use

NVIDIA RTX 4070-ti

### Frequency

Always

### Bug description

Legacy tray icons from Battlenet and RSI-Launcher (Star-Citizen) break VRR until a restart of the OS. 
The error also occurs under Gnome with legacy tray icons enabled via extension. Disabling legacy tray icons fixes the error, or more precisely prevents it from occurring. 

### Steps to reproduce

1. Launch any app or game with VRR enabled
2. Check VRR indicator activated via NVIDIA settings app or monitor OSD. VRR kicks in once app or game is being shown fullscreen
3. Quit app or game
4. Launch Battlenet or RSI-Launcher both showing a tray icon in Cinnamon
5. VRR stops working until a restart of the OS

### Expected behavior

VRR works regardless of tray icons shown

**Comment by leigh123linux** [comment]
You will need to report the issue against the broken app.

**Comment by SpoOokY1983** [comment]
The issue clearly is how legacy tray icons are being handled by Cinnamon and Gnome. Even the wine tray icon breaks VRR. This issue does not occur with KDE. Hence, I would say something is broken in the underlying system of both mentioned DEs.

**Comment by AchillesBoi** [comment]
> You will need to report the issue against the broken app.

You are incorrect; It is an issue with Cinnamon, not with the app. Please re-open the issue or focus on moving the discussion to #12687.
