### ISSUE TITLE
Thunderbird does not integrate well in the panel applet grouped-window-list@cinnamon.org

### ISSUE THREAD

**Issue by mohicanb** [linuxmint/cinnamon#12314]
### Distribution

Mint 22

### Package version

6.2.7

### Graphics hardware in use

AMD Radeon RX 560

### Frequency

Always

### Bug description

if Thunderbird shortcut is added to the panel, when opening it, a new duplicate icon appears in the panel

### Steps to reproduce

add Thunderbird to the panel
open thunderbird

### Expected behavior

only one thunderbird icon should appear in the grouped window list

**Comment by spamegg1** [comment]
I can confirm, also see forum post
https://forums.linuxmint.com/viewtopic.php?p=2500171

**Comment by MiZoG99** [comment]
I can confirm too
