### ISSUE TITLE
Qt5 Configuration Tool (`qt5ct`) segfaults on fresh install of Mint 22 Wilma

### ISSUE THREAD

**Issue by spamegg1** [linuxmint/cinnamon#12318]
### Distribution

Mint 22

### Package version

6.2.7

### Graphics hardware in use

Graphics:   Device-1: AMD Picasso/Raven 2 [Radeon Vega Series / Radeon Mobile Series]     driver: amdgpu v: kernel   Display: x11 server: X.Org v: 21.1.11 with: Xwayland v: 23.2.6 driver: X:     loaded: amdgpu unloaded: fbdev,modesetting,vesa dri: radeonsi gpu: amdgpu     resolution: 1920x1080~60Hz   API: EGL v: 1.5 drivers: radeonsi,swrast platforms: x11,surfaceless,device   API: OpenGL v: 4.6 compat-v: 4.5 vendor: amd mesa v: 24.0.9-0ubuntu0.1     renderer: AMD Radeon Vega 11 Graphics (radeonsi raven LLVM 17.0.6 DRM 3.57     6.8.0-39-generic)

### Frequency

Always

### Bug description

(Not sure where this belongs, probably not related to Cinnamon. Sorry I could not think of any other place to report.)

Qt5 Settings, or `qt5ct` fails to launch after install.

### Steps to reproduce

1. Fresh install of Mint 22 Wilma.
2. `apt install qt5ct`
3. Run `qt5ct` (or launch Qt5 Settings from the Menu, nothing happens).
4. See error (segfault).

### Expected behavior

No crash, should work.

### Additional information

Others having the issue: https://forums.linuxmint.com/viewtopic.php?p=2500291

There IS a simple solution: add this to `~/.profile`:

```bash
# fix Qt5 Settings (qt5ct) issue
export QT_QPA_PLATFORMTHEME=qt5ct
```

Log out, log back in. Problem disappears permanently.

**Comment by Liam-Twomey** [comment]
Can confirm that this bug 1) occurs on update, and 2) is resolved via the `.profile` addition. Unless there's a real need to remove the Qt5 settings in LM22, I think it would be great to have it installed/upgraded by default.

Also, I kept track of which applications were listed as orphaned/incompatible during the upgrade process, and `qt5ct` was *not* listed among them.

**Comment by cgvirus** [comment]
In mint 22 somehow the qt5 config file is corrupted.

- do this in terminal:
`mv ~/.config/qt5ct/qt5ct.conf ~/.config/qt5ct/qt5ct.conf.bck `

- Then start qt5ct
` qt5ct `

- Configure qt5ct

- add this to ~/.profile:
`export QT_QPA_PLATFORMTHEME=qt5ct`

Logout and login. Start qt app like VLC.

**Comment by Liam-Twomey** [comment]
The defaults are mostly fine for _light_-themed QT5 apps, but I found that the best settings for a dark theme (tested on Kate and Okular) was Style: gtk2, icon theme: breeze dark or ePapirus dark, and all provided style sheets enabled. Specifically, if fusion-fixes.qss is not enabled, all dark theming is utterly broken. I _think_ these were previously the defaults in LM21.3, but I'm not 100% sure.

**Comment by LinuxOnTheDesktop** [comment]
The profile business does not stop qt5ct from crashing if one runs qt5ct as _root_; and one needs to run run qt5ct as root in order to theme the program KsystemLog properly. (Still, despite the crash, one can in that way theme KsystemLog correctly.)

>  I found that the best settings for a dark theme (tested on Kate and Okular) was Style: gtk2, icon theme: breeze dark or ePapirus dark, and all provided style sheets enabled. Specifically, if fusion-fixes.qss is not enabled, all dark theming is utterly broken. 

In order to fix - or keep fixed - one element in KsystemLog, namely, its drop-downs, I find that one needs to run qt5ct _as a normal user_ and ensure that 'fusion-fixes' is _not_ enabled. (It remains true that one needs to run qt5ct as root in order to fix Ksystemlogs log line colours. Here, i.e. when running qt5ct _as root_, and when trying to fix KsystemLog, it seems that it does not matter whether 'fusion-fixes' are enabled. What a mess!)

**Comment by LinuxOnTheDesktop** [comment]
Perhaps it's me, but I cannot manage to locate the commit that - according to the email that I received, though not according to what I see on GitHub - solves the problem. That commit is, apparently, f9676a57265cd091423c77292dc5c56660710854.

**Comment by LinuxOnTheDesktop** [comment]
> this is still a problem isnt it?

Well, for my part, and on Cinnamon 6.4.8 on Mint 22.1 Xia, I can run qt5ct as a normal user, and even change a setting within it, without a crash. Yet, if I run it as root - which sometimes (because of another bug?) I need to - then I do get a crash, and I described above.

**Comment by baaannnaaannn** [comment]
for qt6 and new apps u need a qt6ct i think
