### ISSUE TITLE
Keyring does not seem to be used by Element (on Flatpak)

### ISSUE THREAD

**Issue by lucasmz-dev** [linuxmint/cinnamon#12311]
### Distribution

Mint 22

### Package version

6.2.7

### Graphics hardware in use

NVIDIA GeForce RTX 2060

### Frequency

Always

### Bug description

Element (flatpak version, .deb version works fine) does not seem to be able to use the keyring. When checking the "Passwords and Keys" which usually lists these, nothing is found.

### Steps to reproduce

1. Download Element (flatpak version)
2. Login, etc.
3. Go into Passwords and Keys
4. Check the login folder, no entry for Element is found

### Expected behavior

An entry for Element should be there, instead nothing is found.

### Additional information

The only reason I'm reporting this here is because this worked fine in Fedora. Not with Mint though...
Beware, Element as a flatpak is community maintained, it is officially endorsed in element.io though.

As stated before, using the .deb version works fine, I see actually many entries, not just one like in Fedora when using Flatpak, but otherwise, there's literally none.

**Comment by rcalixte** [comment]
As you noted in the linked issue, this is a permissions issue with the Flatpak. Perhaps it is by design or maybe the maintainer(s) of the Flatpak will amend the permissions. Is there anything to be done here for this issue to remain open?

**Comment by lucasmz-dev** [comment]
I'd like to keep this open just in case, there is another permission to do with the keyring that does not seem to be used in Mint. (/xdg-app/keyring IIRC)

I do notice one difference which is that with permission to org.freedesktop.Secrets, I get more entries, so maybe Element was not using the keyring properly in Fedora either. 

When searching for keyring in issues there, I do notice some mentions to issues with that permission...

I'll close this myself in a few days if I don't get a response there.

TODO: look at Bitwarden flatpak because I had issues with the keyring there as well, but not in Fedora.

**Comment by lucasmz-dev** [comment]
No response there so...

**Comment by mtwebster** [comment]
Probably related to https://github.com/linuxmint/xdg-desktop-portal-xapp/issues/19

Fixes released today.
