### ISSUE TITLE
Starter menu is not fully expanded

### ISSUE THREAD

**Issue by Santhoshlm10** [linuxmint/cinnamon#12310]
### Distribution

Linux Mint 21.3 x86_64

### Package version

6.0.4

### Frequency

Always

### Bug description

https://github.com/user-attachments/assets/c6853d86-529f-4bc7-bd28-676a037afc32

### Steps to reproduce

Click on the Linux mint icon on bottom left or press the windows button, the menu appears

### Expected behavior

The menu window should be fully opened on press of window icon or on click of logo

**Comment by Santhoshlm10** [comment]
![image](https://github.com/user-attachments/assets/9aae723b-f1ba-4e7a-997d-7a94bd4d8875)
System info

**Comment by rcalixte** [comment]
Click and drag the corner to the size you would like it to be. You can also set the exact pixel size in the settings.

**Comment by rcalixte** [comment]
@Santhoshlm10 Are you all set? If so, feel free to close this out.

**Comment by Santhoshlm10** [comment]
@rcalixte go it!, thanks

**Comment by Santhoshlm10** [comment]
closing this ticket
