### ISSUE TITLE
Can't launch apps after logout/login

### ISSUE THREAD

**Issue by eugenialoli** [linuxmint/cinnamon#12321]
### Distribution

Mint 22

### Package version

6.4.2 (whatever's on 22)

### Graphics hardware in use

Intel

### Frequency

Always

### Bug description

I login, use the computer, logout, and login back again. After I do that 2-3 times, I can't launch ANY app anymore. Nothing launches from the icons on cinnamon. This happened on two different DELL laptops (one from 2012, one from 2020), one was an upgrade from 21.3, and the other one was a clean installation.

I don't have encrypted drives btw.

### Steps to reproduce

Login, open a few apps (system monitor, terminal etc), logout, login back again, use a couple more apps, logout, login back again, and now apps don't launch!

It happens even more if I logout in order to login as with wayland, and then logout and login back as X11, but it's not always necessary to trigger this bug.

### Expected behavior

To launch apps.

**Comment by fattila02** [comment]
I have this issue too. On virtual machines it needs 2-3-4 times to logout (Ctrl + Alt + Backspace) and login, with normal computers 1 time will do, then Ctrl + Alt + T / Alt + F2 -> gnome-terminal doesn't open the Terminal, System Monitor doesn't open neither.
