### ISSUE TITLE
USB headphones not handled correctly in LM 22

### ISSUE THREAD

**Issue by mfreeman72** [linuxmint/cinnamon#12328]
### Distribution

Linux Mint 22

### Package version

6.2.7

### Graphics hardware in use

Dual-GPU: AMD Vega 6 (open source driver) and NVIDIA GeForce GTX 1650 (proprietary driver version 535)

### Frequency

Quite often

### Bug description

This is a problem I've had since upgrading to Linux Mint 22 (I had a previous LM 21.3 installation and did a clean install with the ISO installer, but with previous /home in a separate partition to maintain settings and documents).

When I plug in my USB-C earbuds (Google brand that came with my Pixel phone several years ago), the sound system becomes confused:

- The Cinnamon sound applet volume control does not change the volume level in the earbuds, although it plays the volume beep through them (just at a constant volume level).
- Using the volume keys on my earbuds controls the volume on my laptop speakers instead, and plays the volume beep through the laptop speakers, but sound through all other applications still goes through the earbuds at an unchanging volume.
- If I open the Sound Settings dialog, the volume control there acts as it should, and controls the earbud volume correctly.

Occasionally, these earbuds and sound system will work perfectly fine, but that doesn't usually happen. I've also tried a completely different set of USB-C earbuds, and they have the exact same problem.

### Steps to reproduce

Running Linux Mint 22, plug in a USB(-C) headset/earbuds, and try to change volume level.

### Expected behavior

The expectation is that the sound applet volume control and volume control buttons on the earbuds appropriately function to control the earbud volume level.

### Additional information

In LM 20, and 21, these same earbuds functioned as expected.

In all other cases in Linux Mint 22, sound works exactly as expected: Laptop speakers, standard 1/8" jack earbuds, and Bluetooth earbuds all work normally. It's just USB(-C) sound, specifically, that's causing the problems.

**Comment by mfreeman72** [comment]
I removed Pipewire and enabled Pulseaudio, and it fixed the problem, so this is definitely a Pipewire issue.

**Comment by leigh123linux** [comment]
File your issue against ubuntu pipewire.
