### ISSUE TITLE
Calendar Applet Alignment Incorrect

### ISSUE THREAD

**Issue by 40GallonTophat** [linuxmint/cinnamon#12334]
### Distribution

Linux Mint 22 x86_64

### Package version

6.2.7

### Graphics hardware in use

Intel TigerLake-LP GT2 [Iris Xe Graphics] 

### Frequency

Always

### Bug description

I have two Calendar applets on my right-aligned vertical panel (40 pixel width). Up until Mint 22 these two applets appeared correctly with middle alignment to the panel.

Top: Now the date appears as "August       01" in the tooltip and "Aug      1" in the Date format thus making it not fit on the toolbar.

Bottom: Appears to have right alignment

![Calendar](https://github.com/user-attachments/assets/6cac1563-b924-4429-80a3-c79eeb13ced7)
![Calendar2](https://github.com/user-attachments/assets/19fcec17-b88b-412f-8d93-c361e7dd7e94)
![CalendarSettingsTop](https://github.com/user-attachments/assets/57f18143-88d7-4122-9cb7-fdf6989c84b7)
![CalendarSettingsBottom](https://github.com/user-attachments/assets/b77fe7e5-a3c3-4cfe-b671-e15e51275d0f)

### Steps to reproduce

Toolbar on the right side of the screen with 40 pixel width.

2x calendar applets
Top:
Date format: %b %e
Date format for tooltip: %A, %B %e, %H:%M

Bottom:
Date format: %l:%M
Date format for tooltip: %A, %B %e, %H:%M

### Expected behavior

Top: Should appear as "Aug 1" in panel and "August 01" in tooltip and thus fit in the toolbar
Bottom: Should be center aligned

### Additional information

N/A

**Comment by leigh123linux** [comment]
Duplicate #12176

**Comment by claudiux** [comment]
With `%e%n%b%n%H:%M` (French language):

![image](https://github.com/user-attachments/assets/960cdc1e-fe26-455e-9038-54c3ac2b4a42)

The `%e` format takes place of 2 characters.
