### ISSUE TITLE
Calendar: Hidden leading zeroes still take up space

### ISSUE THREAD

**Issue by DokterKaj** [linuxmint/cinnamon#12335]
### Distribution

Mint 22

### Package version

6.2.7

### Graphics hardware in use

Intel Corporation Meteor Lake-P [Intel Arc Graphics]

### Frequency

Quite often

### Bug description

When using `%e` (Day of the month without a leading zero) or `%l` (Hour of the day, 12-hour clock without a leading zero) in a custom date format, the leading zeroes that are supposed to be hidden will sometimes still take up space in the display. Switching to `%d` and `%I` will show the zeroes while the width stays the same.

Date format: `%d/%m/%Y  %l:%M %p`
Date format for tooltip: `%A, %B %e %Y, %H:%M`
![image](https://github.com/user-attachments/assets/988b3c42-0f68-4e23-bec0-12aadcfd3ba7)

Date format: `%d/%m/%Y  %I:%M %p`
Date format for tooltip: `%A, %B %d %Y, %H:%M`
![image](https://github.com/user-attachments/assets/64b104d6-6557-439f-a10b-bf818476b4f3)

### Steps to reproduce

1. Configure the calendar applet
2. Activate "Use a custom date format"
3. Add either `%e` or `%l` to the date format

### Expected behavior

Hidden leading zeroes should not take up space in the display.

### Additional information

This behaviour is inconsistent: I can recall times when hidden zeroes didn't take up space, but I don't know what causes it to or not to.

**Comment by DokterKaj** [comment]
Found [this post](https://stackoverflow.com/a/2073189) on StackOverflow which says that inserting a hyphen after the percent sign will remove the leading zero. `%-d` indeed hides the leading zero but also makes it so that it doesn't take up space. `%-e` actually makes the invisible leading zero disappear (so it looks exactly like `%-d`). Will be using this as a workaround for now.

**Comment by mtwebster** [comment]
This is a change that was done in a library we use (glib) - definitely not one we were happy about:

https://gitlab.gnome.org/GNOME/glib/-/commit/7074122f308b7b3402fba250f2010778fdad6eff
https://gitlab.gnome.org/GNOME/glib/-/commit/7169f6e1e58a53e4b69e5d40f3fd192dd9cd8ed4

We adapted our 'standard' formats (the ones used according to the main Date/Time switches):
https://github.com/linuxmint/cinnamon-desktop/commit/f1f82b35b48c2ebeca000caa2ef47d3b4d6b210c

You won't see this if you've got 'use a custom date format' disabled.
