### ISSUE TITLE
Nvidia driver Wine programs don't open

### ISSUE THREAD

**Issue by fattila02** [linuxmint/cinnamon#12330]
### Distribution

Mint 22

### Package version

6.2.7

### Graphics hardware in use

NVIDIA GeForce RTX 3050 Ti

### Frequency

Always

### Bug description

If I install the proprietary drivers: 470 / 535 / 545 / 550 / 555 for Nvidia RTX 3050 Ti, Wine programs run with Steam Proton / CrossOver simply doesn't open, whichever mode I set the Nvidia Optimus into (Power Saving / Nvidia Demanding / Nvidia Performance).
Steam indicates that the program is running, but nothing appeared in the screen. CrossOver simply can't run the exes.

When I replace the pro driver to open-source Nvidia version 555 (nvidia-driver-555-open, nvidia-dkms-555-open...), the situation is almost solved, but not completely: in Demanding mode neither of Win program opens likewise, but in Power Saving mode and Performance mode these programs launch and run perfectly.
On the other hand, if I install e.g the version 535 open-source drivers, no Win program opens.

### Steps to reproduce

When programs don't run: Install whichever proprietary driver, reboot and try to run Windows programs with Steam Proton 9 / CrossOver.

When the programs do run in certain cases: Install open-source Nvidia driver (sudo apt install nvidia-driver-555-open -y), reboot and adjust the Optimus to Power Saving or Performance, programs will start.
Then try the Demanding mode as well, there programs won't start.

### Expected behavior

When I install Nvidia drivers whether proprietary or open source and whichever mode I adjust the Nvidia Optimus into, these programs should always run flawlessly.

### Additional information

I experienced this issue only with RTX 3050 Ti, but I don't know whether other Nvidias are affected or not.

**Comment by leigh123linux** [comment]
This bug tracker is for cinnamon issues, file the issue at nvidia.

https://forums.developer.nvidia.com/c/gpu-graphics/linux/148
