### ISSUE TITLE
When trying to install some applications there are components missing from Mint

### ISSUE THREAD

**Issue by DarcSceptor** [linuxmint/cinnamon#12349]
### Distribution

Linux Mint 22 Cinnamon 

### Package version

6.2.9

### Graphics hardware in use

AMD Cezanne [Radeon Vega Series] APU

### Frequency

Only occasionally

### Bug description

I first encountered this trying to install SDR++ which is used to display radio signals picked up by an RTL-SDR receiver. The install kept missing a package which could not be installed directly! After coming close to making myself bald from pulling out my hair I came across the post that fixed EVERYTHING. I had to install **_libpango1.0-dev libcairo2-dev_** which the people discussing this said was missed by the devteam. After installing these two packages I was able to install my software. Previously, SDR++ installation reported it was missing module libvolk2-dev which seems to be a dependent module in one of those two packages missing. It should be a simple modification to the upgrade package.

### Steps to reproduce

Wipe a machine and install Linux Mint 21. (this is the exact sequence I took)
Updated Linux Mint 21 to Linux Mint 22.
Download SDRPP from https://github.com/AlexandreRouma/SDRPlusPlus/releases I tried the ubuntu_jammy version but it was recommended using sdrpp_debian_sid_amd64.deb and that is what I unstalled.

### Expected behavior

From everything I read and researched those two listed packages (libpango1.0-dev libcairo2-dev) should have been part of the core installation of Mint. If they were part of the install then the installation of SDR++ would have been without issues. Instead it took me almost 3 days to get the application installed because you cannot directly install libvolk2-dev. (believe me I tried many many times) and not until I finally discovered installing the two libraries listed above.

### Additional information

I am brand new to Linux Mint. About two weeks ago I eliminated Windows and installed Linux Mint 21. 
As a new guy I was quite lost what to do, what to install, what to try. I did sudo apt install... I did sudo dpkg install (or something like that) and I also tried installing Homebrew and hoping that would automatically locate and install libvolk2-dev.  I may be a new Linux fulltime user but tried running it since 1996 about every few years only to uninstall everything and return to Windows. I am also a retired developer so I kept banging away at this problem as if it was one of my programming problems.

**Comment by leigh123linux** [comment]
This isn't a cinnamon issue.
