### ISSUE TITLE
Changes to themes are not persistent/do not survive a reboot

### ISSUE THREAD

**Issue by Grydpype** [linuxmint/cinnamon#12345]
### Distribution

Linux Mint 22 Wilma 

### Package version

6.2.7

### Graphics hardware in use

Intel Iris Plus Graphics G1

### Frequency

Always

### Bug description

Changes to themes are not stored persistently.

My current desktop theme after booting is Mint-Y; my application theme is Mint-Y and my symbol theme is hicolor.

I change my themes from Mint-Y to Mint-Y-Blue and the symbol theme from "hicolor" to a blue folder. Works perfectly; views change, icons change in the task bar etc.; all is nice.

Then I re-boot and voila: everything is back to the previous state, i.e. Mint-Y and "hicolor" symbols (and with an ugly file manager icon for Nemo).

Anything I can do to keep my changes persistent; any settings that are new and I have overlooked?

### Steps to reproduce

- Boot Mint 22
- change the current themes to different themes
- reboot

### Expected behavior

After a reboot, the new themes should be used. Instead, system uses to the old themes.

**Comment by mtwebster** [comment]
Do you mean after a reboot, you go into cinnamon settings and the theme selector is back to Mint-Y and icons are hicolor? Or do you mean that's just what you're observing in nemo? What about the rest of the desktop or other apps?

Do you have anything in `~/.config/gtk-3.0/settings.ini` that may be affecting this?

Maybe something you installed, or a Cinnamon applet or extension?

You're not running nemo as root are you?

**Comment by Grydpype** [comment]
Several questions here, thank you for the quick response.

1.  After a reboot, Cinnamon starts and the themes are back to the old settings; Nemo doesn't really matter here.
2. Regarding ~/.config/gtk-3.0/settings.ini: I do not have this file, merely 2 text files: _bookmarks_ and _gtk.css_
3. I am not aware of any changes I made apart from upgrading from 21.3 Virginia to 22.0 Wilma
4. No, I am not running nemo as root, but as noted, nemo doesn't really enter into it, it's sufficient to look at the task bar and see that the nemo icon has reverted to the hicolor version like so: 
![image](https://github.com/user-attachments/assets/a77f0b02-3757-4cc5-a74c-9c0c8ed494fc)
![scrnshot nemo icon hicolor](https://github.com/user-attachments/assets/d31e3f1b-33c2-432b-9eb4-0586883f8ef2)

**Comment by mtwebster** [comment]
Can you paste or attach your `~/.xsession-errors` please? (make sure there's no personal info)

Also, is 'csd-xsettings' running?
```
ps -A | grep csd-xsettings
```

**Comment by Grydpype** [comment]
Current xsession-error attached; scanned for personal info; removed login name & changed suffix for uploading. 
And it looks like csd-settings is not running: " 1645 ?        00:00:00 csd-xsettings"

[xsession-errors-2024-08-07.txt](https://github.com/user-attachments/files/16532289/xsession-errors-2024-08-07.txt)

**Comment by mtwebster** [comment]
Hmm no help - can you run:
```
dconf dump /org/cinnamon/ > settings
```
then attach the 'settings' file - this is a listing of all Cinnamon-related settings that are not at their original values - there probably isn't any personal info but check anyhow.

Thanks again

**Comment by Grydpype** [comment]
OK, I am uploading 3 files: 
(1) first file directly after a boot; 
(2) second file after the changing of the theme, and 
(3) third file after a reboot. You can see that in the second file my change from Mint-Y to Mint-Y-Aqua is registered, but after the reboot it has been reverted.
Hope that helps ...

[1_settings_before_change.txt](https://github.com/user-attachments/files/16550743/1_settings_before_change.txt)
[2_settings_after_change.txt](https://github.com/user-attachments/files/16550744/2_settings_after_change.txt)
[3_settings_after_reboot.txt](https://github.com/user-attachments/files/16550745/3_settings_after_reboot.txt)

**Comment by Grydpype** [comment]
fyi: the cinnamon upgrade to 6.2.9 just now did not fix this behaviour

**Comment by Grydpype** [comment]
As a workaround, I have made a dconf dump of the desired settings and now execute a dconf load at startup. This works, but I would prefer a proper solution for this behaviour.

**Comment by Grydpype** [comment]
Short update: it looks like I have to execute a dconf load after waking up from sleep mode as well; even without a re-boot.

**Comment by anolis** [comment]
@Grydpype  I have just done a fresh Mint 22 install and am unable to replicate this issue. I have several thoughts. 

- Perhaps there is a permission issue on your end?
- Update your system if you haven't already
- strace the application while making changes, and see if its throwing any errors


good luck!

**Comment by Grydpype** [comment]
I think we can close this issue.

I set up a new user and with this user the issue cannot be reproduced. So far so good; I'll now migrate my applications from the old account to the new one and see if this behaviour pops up again; I expect not.

I'll close the issue over the weekend; I should have finished the migration till then.
Thanks for the support & feedback.
