### ISSUE TITLE
App Dragging does not let you move apps past the midway point on the bottom panel.

### ISSUE THREAD

**Issue by Sliish** [linuxmint/cinnamon#12346]
### Distribution

Mint 21.3 Cinnamon

### Package version

6.0.4

### Graphics hardware in use

No idea (old hp laptop)

### Frequency

Always

### Bug description

When you enable app button dragging, there is an invisible wall that keeps you from moving the apps around freely. It's kinda hard to explain, so I've attached a short screen recording.

https://github.com/user-attachments/assets/f2d6ad58-79a7-4b12-85e8-618bbcc30550

### Steps to reproduce

1. Have a few different apps open.
2. Right click on the bottom panel and enter "Edit Mode".
3. Right click on the apps at the bottom and click "configure"
4. Under Panel, enable "App Button Dragging".
5. Try dragging some of the apps from one side to the other. There seems to be an invisible line down the middle that the apps can't cross.

### Expected behavior

I feel like you should be able to move the apps from one side to the other and arrange them in whatever order you want.

### Additional information

No additional info :)
Thank you!

**Comment by DirkHaar** [comment]
That seems to be a wrong expectation here. The video shows that you are able to move apps to the first and last position.
I don't know which exact applet you are using for this ("grouped window list"?). It is set to ~ 1/6th the size of your screen width here, and what you are doing is moving opened app's icons around *on this applet*, but you can move them from that applet. I.e., you aren't moving apps on the panel, but on this particular applet. (In comparison: if you define your panel 50% of screen width on the left, you also wont be able to drag icons/apps to the right half of the screen beyond the end of the panel).

You might resize the window list applet or the areas left or right of it. I got mine (not grouped, with names+icons), on the left, right to the app shortcuts, and it takes all the space up to the system tray icons on the right and the icons are resized as the number of opened apps increase.

**Comment by Sliish** [comment]
Hi, thanks for your response.
After restarting my computer and closing all of my tabs, I think I've realized what my (perceived) problem is.
The applet is grouped window list. The problem I was having is that I have the leftmost three icons 'pinned' to the panel (by selecting "add to panel" in the start menu). I can't move any of the non-pinned icons to the left of any of the pinned icons.

For example:
(P is pinned, blank is unpinned)

[P] [P] [P] [  ] [  ] [  ]    <-- my current windows

What I expect to be able to do:
Take window X and move it over here
1.    [P] [P] [P] [  ] [X] [  ]

2.    [P] [P] [X] [P] [  ] [  ]

And then once I close window X it should go back to
[P] [P] [P] [  ] [  ]


Or in other words: Pinned windows are always on the left, but I expected to be able to move them around.



Thanks :)

**Comment by DirkHaar** [comment]
[P] [P] [P] [ ] [ ] [ ] <-- my current window

that is not what your video shows.
What I see is

[Menu][Programm starter app][white space][grouped window app][white space][other taskbar app icons]

You are trying - as far as I interpret your mouse movements and you [P] / [X] example above to move the icon of an opened windows - which is only a representation of running programs given by the grouped window list (taken as data from the system) - in to the group of program starters (which in fact is than a special,short kind of menu, comparable to the main menu). That is not possible as the grouped window list app doesn't even know how the running programs have been started, as is has not been designed for this purpose.

**Comment by Sliish** [comment]
Ah I see the confusion. I was not trying to move anything outside of the group window list. I was exaggerating my movements to show that it would not go to the other side of the grouped window list.

**Comment by DirkHaar** [comment]
Mark as solved then.

**Comment by Sliish** [comment]
? It isn't solved though

**Comment by anolis** [comment]
It isn't a bug per se, but I can see how the UI/UX is a little misleading, perhaps pinned apps should be visually distinct in some way from apps that are merely running. 

@Sliish  the idea here is that your pinned apps are always there and always maintain the same arrangement. I am assuming to keep important stuff from moving around. if you want to rearrange pinned apps you can, but if you want to mix a running app in with the list of pinned you have to pin it too it appears. 

Perhaps a boolean toggle to allow mixing of pinned/unpinned icons could be introduced. That would need to be filed as an improvement rather than a bug, however.

**Comment by Sliish** [comment]
Ahh I see. Will do!

Thank you :)
