### ISSUE TITLE
sublime-text is outdated in Linux Mint 22 wilma repository.

### ISSUE THREAD

**Issue by tur1ngb0x** [linuxmint/cinnamon#12343]
### Distribution

Linux Mint 22

### Package version

Cinnamon 6.2.7

### Frequency

Always

### Bug description

`sublime-text` package in linux mint repository is at v4169. upstream is at v4180.

Opening `sublime-text` shows update is available.

![image](https://github.com/user-attachments/assets/f73fa546-068e-44e6-9161-1cdb8d19eaab)

http://packages.linuxmint.com/search.php?release=wilma&section=import&keyword=sublime-text

https://www.sublimetext.com/download

### Steps to reproduce

Open `sublime-text`

```bash
$ apt-cache policy sublime-text
```

```plain
sublime-text:
  Installed: 4169
  Candidate: 4169
  Version table:
 *** 4169 500
        500 http://packages.linuxmint.com wilma/import amd64 Packages
        100 /var/lib/dpkg/status
```

### Expected behavior

Mint devs should remove `sublime-text` package from Linux Mint repos and let users install upstream version manually using `sublime-text` apt repository.

https://www.sublimetext.com/docs/linux_repositories.html#apt

**Comment by JosephMcc** [comment]
Not a Cinnamon issue.
