### ISSUE TITLE
Chromium browser not available in wilma

### ISSUE THREAD

**Issue by zadeck** [linuxmint/cinnamon#12359]
### Distribution

Mint 22 wilma

### Package version

Wilma xfce edition

### Graphics hardware in use

Not relevant

### Frequency

Always

### Bug description

Package does not appear to have been brought forward to wilma.   When you try to install it, the process fails because the package it finds depends on snap.   Worked fine on vanessa.

### Steps to reproduce

Try to install chromium-browser under wilma

### Expected behavior

Should install and run

**Comment by mtwebster** [comment]
It's chromium now, not chromium-browser.  This changed once Ubuntu started shipping it as a snap and we began building it ourselves.

**Comment by zadeck** [comment]
Thanks.   Sorry for the mistake.On Aug 23, 2024, at 9:56 PM, Michael Webster ***@***.***> wrote:﻿
It's chromium now, not chromium-browser.  This changed once Ubuntu started shipping it as a snap and we began building it ourselves.
