### ISSUE TITLE
Desktop Icons are gone after reboot

### ISSUE THREAD

**Issue by dtrunk90** [linuxmint/Cinnamon#1235]
Computer, Home folder, Trash, ... icons are gone.
Didn't tested restarting Cinnamon itself, but after rebooting they're gone.
Cinnamon version:  1.6.1-0ubuntu1~precise1

**Comment by kingnataraj** [comment]
ubunthu 12.04 LTS icons are not showing and then top of the right side cross mark is showing ...plz anyone help to come back to normal screen????
