### ISSUE TITLE
Clang Freeze

### ISSUE THREAD

**Issue by pbzinwindows** [linuxmint/cinnamon#12355]
### Distribution

mint 22

### Package version

Cinnamon 6.2.9

### Graphics hardware in use

ryzen 3 3200g

### Frequency

Always

### Bug description

When I use Clang to compile an Android ROM it freezes the entire system

### Steps to reproduce

install clang sudo apt install clang
and then try to compile your android rom

### Expected behavior

computer does not freeze completely until restarted

**Comment by leigh123linux** [comment]
Report the issue elsewhere as cinnamon isn't responsible for the freeze.

**Comment by leigh123linux** [comment]
Check systemd-oomd is enabled and running

`systemctl status systemd-oomd.service`

and enable it if it isn't

`sudo systemctl enable --now systemd-oomd.service`

It will kill your clang compile before clang can crash the system.

**Comment by pbzinwindows** [comment]
> Check systemd-oomd is enabled and running
> 
> `systemctl status systemd-oomd.service`
> 
> and enable it if it isn't
> 
> `sudo systemctl enable --now systemd-oomd.service`
> 
> It will kill your clang compile before clang can crash the system.

It didn't help, and I was wrong, it's not a clang problem, I went back to mint 21.3 despite it freezing a few times for a few seconds, it comes back and continues to work, unlike 22 where I have to restart the PC
