### ISSUE TITLE
Как отключить уведомление о нехватке места на диске?

### ISSUE THREAD

**Issue by V01FRam** [linuxmint/cinnamon#12365]
Не уверен, что кто либо ответит мне в закрытой 9 лет назад теме https://github.com/linuxmint/Cinnamon/issues/1425 поэтому открываю новую.
Хотелось бы возобновить обсуждение данного вопроса, так как он уже не однократно поднимался на разных форумах по Linux Mint. Это беспокоит определённое количество пользователей, которые время от времени наступают на эти грабли, любезно предоставленные разработчиками из самых лучших побуждений.
Я и сам наступил на эти грабли и не могу победить такое же уведомление у себя в системе:
Linux Mint 21.3 Cinnamon V6.0.4 Ядро Linux 5.15.0-119-generic Intel© Core™2 Duo CPU E7400 @ 2.80GHz × 2 3.8 ГиБ
Хотя я пробовал отключить этим методом: https://forums.linuxmint.com/viewtopic.php?p=1973410&sid=be881a324fbaa71ed0f1421ada9b7a68#p1973410
И так пробовал, набирал в терминале gsettings set org.gnome.settings-daemon.plugins.housekeeping ignore-paths "['/mnt/FE680RD2569D891B']"
Система не против этих способов и даже показывает изменения в редакторе dconf. Однако поведение системы не меняется. При каждом входе в систему появляется это назойливое уведомление.
Вопрос: Как это уведомление победить? Как отключить его для этого конкретного раздела? Меня устраивает его заполненность и я не намерен освобождать на нём место.
Может быть я что то не так делаю?

**Comment by leigh123linux** [comment]
Use ignore-paths, see

https://forums.linuxmint.com/viewtopic.php?t=142087

**Comment by V01FRam** [comment]
Especially for those whose browser cannot translate from Russian to English, I write my question in the language of Shakespeare.
I am not sure that anyone will answer me in the closed 9 years ago topic #1425, so I am opening a new one.
I would like to resume discussion of this issue, as it has been raised many times on different Linux Mint forums. It bothers a certain number of users, who from time to time step on this rake, courtesy of the developers with the best of intentions.
I've stepped on this rake myself and can't seem to defeat the same notification on my system:
Linux Mint 21.3 Cinnamon V6.0.4 Linux Kernel 5.15.0-119-generic Intel© Core™2 Duo CPU E7400 @ 2.80GHz × 2 3.8 Gigs
Although I tried disabling with this method: https://forums.linuxmint.com/viewtopic.php?p=1973410&sid=be881a324fbaa71ed0f1421ada9b7a68#p1973410
I tried it this way too, typing in terminal gsettings set org.gnome.settings-daemon.plugins.housekeeping ignore-paths “[‘/mnt/FE680RD2569D891B’]”
The system is fine with these methods and even shows the changes in the dconf editor. However, the behavior of the system does not change. Every time I log in, this annoying notification appears.
Question: How to defeat this notification? How do I disable it for this particular partition? I am happy with it being full and I don't intend to free up space on it.
Maybe I'm doing something wrong?

**Comment by V01FRam** [comment]
> Use ignore-paths, see

I did this: gsettings set org.gnome.settings-daemon.plugins.housekeeping ignore-paths “[‘/mnt/FE680RD2569D891B’]”
The notification keeps appearing.
