### ISSUE TITLE
Cannot take screenshot while LibreOffice Calc AutoFilter window is visible

### ISSUE THREAD

**Issue by NeatNit** [linuxmint/cinnamon#12360]
### Distribution

Mint 22

### Package version

6.2.9

### Frequency

Always

### Bug description

I can't take a screenshot of the AutoFilter UI in LibreOffice Calc. Whenever it's visible the PrintScreen button does nothing, regardless of Ctrl/Alt/Shift combinations.

It seems like Calc puts this sub-window on top of everything else in some way, but shouldn't it still be possible to take a screenshot?

### Steps to reproduce

1. Open LibreOffice Calc (I have version 
2. Input some data, or just copy this:
  Header
  1
  3
  2
  3
3. Activate AutoFilter ![image](https://github.com/user-attachments/assets/0626d98b-967a-48d9-bbc2-dda90681f858)
4. Open the dropdown filter
![image](https://github.com/user-attachments/assets/326132d0-5eaa-4c2c-b048-8ec7423b2bfb)
5. While it's open, try to take a screenshot using the PrintScreen key

### Expected behavior

Screenshot is taken

### Additional information

I don't know whether this is a Cinnamon issue or a LibreOffice issue, so I am opening an issue with both. I think Cinnamon should always be able to take a screenshot, but if LibreOffice is *specifically* blocking this (by a bug of course), then Cinnamon is obviously innocent. I personally have no way of figuring out which is at fault here.

**Comment by NeatNit** [comment]
Opened issue with LibreOffice: https://bugs.documentfoundation.org/show_bug.cgi?id=162611

**Comment by mtwebster** [comment]
I suspect this is 'normal behavior' - that header dialog window is really a combo box popup being abused as a dialog window.

It is exactly the behavior you get if you click a combo box in Nemo or cinnamon settings:
![image](https://github.com/user-attachments/assets/36f4ca1d-299a-4ed8-aa24-beed265f21c4)

When one of those combos is 'open', shortcut keys are also disabled.

In Cinnamon (and any other x11-based window manager/desktop), shortcut bindings are placed on all 'normal' windows automatically, so no matter what app is focused, those shortcuts will work. These popups are not normal windows - they're temporary, and usually untracked by the window manager, and as a result won't have had those bindings applied.

These popups grab all focus, keyboard and mouse, and nothing will work until they close again.

The right-click popup menu in Calc is the same way - open it and try to take a screenshot.

I'm guessing one reason they're creating that filter window in this manner is to take advantage of the fact that it will automatically lose focus and close if you click elsewhere in the page.

I'd probably have done the same thing :)

**Comment by mtwebster** [comment]
This issue is immortal, and is baked into x11. Leaving that window (or any other popup) open [can also block the screensaver from starting
](https://github.com/linuxmint/cinnamon-screensaver/commit/4ae9f1da8aed493d1d1f02b43fcb51803573042d)
Yeah, it's annoying to work around. One reasonably easy way is to launch cinnamon-screenshot from the menu, and enable a timer. Then you can have time to setup and get the window open before it triggers.

**Comment by NeatNit** [comment]
Thanks, that's an option I'll consider next time I need to do that.

**Comment by mtwebster** [comment]
Ok closing this then.
