### ISSUE TITLE
cinnamon-6.2.9 resets audio settings after each reboot

### ISSUE THREAD

**Issue by rado84-github** [linuxmint/cinnamon#12377]
### Distribution

Arch

### Package version

6.2.9

### Graphics hardware in use

GTX 1660 Ti 6GB

### Frequency

Always

### Bug description

IDK how exactly, but pavucontrol resets the user settings to some default profile at 41% sound volume after each reboot. I've described the problem here: https://forums.linuxmint.com/viewtopic.php?p=2520528#p2520528 and after some experimenting, I discovered it's cinnamon-6.2.9 that causes this. The experiment included downgrading the kernel to 6.6.36-lts (because I remember I had good memories with it) but that didn't change anything. Only after downgrading cinnamon to 6.2.2, pavucontrol began remembering the settings and profiles set by the user, thus the other application for sound ("cinnamon-settings sound" or something like that) also remembered my settings.

### Steps to reproduce

1. Open pavucontrol and set (for instance) HDMI profiles to be OFF, then set the other dropdowm menu to Analog Surround X.X Output and then click both icons to make the chose profiles default and to lock the soundcard to the chosen profiles.
2. Reboot. 
3. Open pavucontrol again and you should see that HDMI profiles are back to "enabled", your chosen surround profile is gone and has been replaced by the default "Analog stereo output".
4. Then go to Cinnamon's settings and open "Sound" - you'll see the sound volume has reverted back to 41% volume.

### Expected behavior

Pavucontrol and "cinnamon sound settings" should remember all user settings and volume levels.

### Additional information

I know it sounds strange but I've tried everything I could think of before performing that experiment, including deleting ~/.confing/pulse where pavucontrol stores the user settings, downgrading pavucontrol, making immutable the two text files in ~/.confing/pulse because when using 6.2.9, pavucontrol writes in them - all in the hopes that if it can't write in them, it won't reset the settings, but that didn't help either. It only made things even weirder.

**Comment by leigh123linux** [comment]
Ask the  pavucontrol maintainers.
