### ISSUE TITLE
`~/.themes` automatically created on boot

### ISSUE THREAD

**Issue by Susensio** [linuxmint/cinnamon#12372]
### Distribution

Mint 22.0

### Package version

6.2.9

### Graphics hardware in use

Iris Plus Graphics 655

### Frequency

Always

### Bug description

I've put my custom themes in `~/.local/share/themes/`, because it is the new standard (as far as I know) and I like to keep my `$HOME` decluttered.
But everytime I reboot `~/.themes/` folder is recreated and all themes are symlinked.

### Steps to reproduce

1. Download any theme into `~/.local/share/themes/` (or copy one from `/usr/share/themes/`.
2. Reboot
3. Now the theme has been **moved** into `~/.themes` and symlinked into `~/.local/share/themes/`

### Expected behavior

I would expect that everything stays as is

**Comment by mtwebster** [comment]
This is done for backward compatibility with Gtk2 applications - they only check .themes, whereas Gtk3 checks both locations.

Some discussion: https://github.com/linuxmint/cinnamon/pull/11175

**Comment by Susensio** [comment]
> This is done for backward compatibility with Gtk2 applications - they only check .themes, whereas Gtk3 checks both locations.
> 
> Some discussion: #11175

Okey I suspected that something like that was going on.
I see in the discussion a PR that sets **where downloaded themes are going**. Okey, seems fair.
I cannot find the code, or the discussion, about **moving and symlinking already present themes**. Could you give me a hint where to look?

I would like to, at least, remove that behavior locally because I think I don't use any GTK2 apps
