### ISSUE TITLE
Why Cinnamon uses so much memory? 

### ISSUE THREAD

**Issue by paulvonlux** [linuxmint/cinnamon#12370]
### Distribution

22

### Package version

6.2

### Graphics hardware in use

amd rx580

### Frequency

Always

### Bug description

Why Cinnamon uses so much memory? Probably the Upstream distro Ubuntu fault, because LM21 uses less memory , LM22 more?, efficiency is trash, too much memory consumption also the upstream occupy too much SSD space, Alpine Linux consumes 1.7gb on SSD... trash bloatware upstream

### Steps to reproduce

htop info

### Expected behavior

too much memory consumption also the upstream occupy too much SSD space

**Comment by leigh123linux** [comment]
This isn't a bug report, it is just your opinion.

**Comment by paulvonlux** [comment]
> This isn't a bug report, it is just your opinion.

true, but why? devs don't care anymore about efficiency...

**Comment by mtwebster** [comment]
You had all the answer you need here: https://github.com/orgs/linuxmint/discussions/596

Stop opening these issues - no means no.
