### ISSUE TITLE
Linux Kernal update of Sept. 12, 2024 borked my machine 

### ISSUE THREAD

**Issue by Kenarik** [linuxmint/cinnamon#12389]
### Distribution

Mint XFCE 21.3

### Package version

IDK and can't look it up, but the latest released today

### Frequency

Always

### Bug description

I updated, foolishly upon reflection, the Linux kernal. This is what I see
![20240912_213450](https://github.com/user-attachments/assets/cf877d9f-3b99-44b3-a5be-cfc462305a8d)

### Steps to reproduce

Download the kernal update from the update manager sent out today (Sept. 12, 2024). I have tried all of the options on screen and either it does nothing, shuts down my computer without doing anything, or I see the below 
![rn_image_picker_lib_temp_9037eb00-f53f-4e7b-9bbc-a78ba58e1530](https://github.com/user-attachments/assets/10ad6b7f-abb3-4506-a70c-71d6ecfc6c99)

### Expected behavior

I expected it to reboot as normal. 

### Additional information

My computer is a former Chromebook. Until today it has ZERO issues with Mint XFCE 21.3 I am not tech savvy with Mint yet as I am new to it. I thought I was doing what I needed to do and then it borked my machine.

**Comment by leigh123linux** [comment]
Report your issue against the kernel at ubuntu bug tracker.

**Comment by Kenarik** [comment]
Way to help a NEWBIE! I don't know where to report this issue and you could have at least out a link!

**Comment by leigh123linux** [comment]
Try reading https://wiki.ubuntu.com/Kernel/Bugs

If you want help, use the forum.

https://forums.linuxmint.com/

**Comment by mtwebster** [comment]
You can boot a previous kernel, if one is installed, by holding shift when restarting. This will bring up the 'GRUB' menu, you can select 'Advanced options...' and pick a different kernel to load. You'll have to do this every time you boot, until you fix the issue with your new version.

**Comment by Kenarik** [comment]
I have tried that, but I think the update screwed with everything. Everything I have tried results in either the computer doing nothing (and by nothing I let it sit for half an hour with no screen changes), shutting the computer down or giving me the warning I posted in the second image.

I think at this point I will just have to reinstall from a fresh copy, which makes me disheartened.
