### ISSUE TITLE
Highlighted filename cannot be edited when saving an image

### ISSUE THREAD

**Issue by steviedeeee** [linuxmint/cinnamon#12380]
### Distribution

Mint 21

### Package version

5.4.12

### Frequency

Always

### Bug description

When saving a file, the filename is highlighted, however if you type a new name the text in the highlighted box does not change. Instead I have to click outside to unhighlight the filename, then re-highlight it again to change it.

### Steps to reproduce

Right click on an image in a browser, for example.
Choose Save As, you will see the filename highlighted.
Try typing.

### Expected behavior

The highlighted text is the active focus, so typing should change the text in the highlighted area.

**Comment by JosephMcc** [comment]
Nothing to do with Mint or Cinnamon. Save, open, and save as dialogs are provided by the toolkit an app is built with. Mint has no control over that.
