### ISSUE TITLE
Boot issues

### ISSUE THREAD

**Issue by x64x2** [linuxmint/cinnamon#12402]
Decided to install cinnamon by making it my host os only to encounter glitches on my Thinkpad X1 carbon .

**Comment by leigh123linux** [comment]
You haven't posted any of the required info!

**Comment by x64x2** [comment]
> You haven't posted any of the required info!

Which required info??

**Comment by leigh123linux** [comment]
You ignored every question on the new bug template.

https://github.com/linuxmint/cinnamon/issues/new?assignees=&labels=BUG&projects=&template=bug_report.yaml
