### ISSUE TITLE
update -  thunderbird 1:128.2.3esr+linuxmint1+wilma breaks gmail

### ISSUE THREAD

**Issue by G4OVP** [linuxmint/cinnamon#12418]
### Distribution

Mint mate 22

### Package version

MATE 1.26.1

### Graphics hardware in use

n/a

### Frequency

Always

### Bug description

updating  -  thunderbird 1:128.2.3esr+linuxmint1+wilma breaks gmail
google asks to re-authenticate, but unable do to error.

### Steps to reproduce

![image](https://github.com/user-attachments/assets/c8e81918-d8da-471e-9f37-1a077df580ed)
install the update Thunderbird breaks,  every time.

### Expected behavior

just as before logon to google

### Additional information

sorry I cant remember the exact error code, as was not sure what was the cause at first

**Comment by leigh123linux** [comment]
This isn't a dumping ground for non cinnamon issues.
