### ISSUE TITLE
Could not create MokL - Volume Full

### ISSUE THREAD

**Issue by qbawoj** [linuxmint/cinnamon#12424]
### Distribution

Mint 22

### Package version

6.2.9

### Graphics hardware in use

GeForce GTX 1070 Mobile

### Frequency

Always

### Bug description

Problem occurs after fresh installation is completed, and always after turn off/reset the system when system try to modify Secure Boot settings of BIOS. 

### Steps to reproduce

No matter if Secure Boot is Enabled or Disabled when starting a computer, before Grub menu is showing I get a problem reporting:

Could not create MokL
istRT: Volume Full
Could not create MokListXRT: Volume Full
Could not create SbatLevelRT: Volume Full
Could not create MokListTrustedRT: Volume Full
Something has gone seriously wrong: import_mok_state() failed: Volume Full

### Expected behavior

Entrance to BIOS and erasing Secure Boot variables allows to run Grub and system works fine.

**Comment by leigh123linux** [comment]
There isn't anything to fix within the cinnamon package.
Your issue is occurring because you have filled the motherboard  NVRAM storage for keys, you will need to delete some to free space.

**Comment by qbawoj** [comment]
@leigh123linux The problem is that I remove all of keys every time before I running Linux Mint. Mint starts with a completely empty key list and overflows NVRAM when system shuts down.

**Comment by qbawoj** [comment]
Notabene: I also have windows next to linux. Windows does not cause this problem and I can use it. The problem occurs every time the last system used was Mint
