### ISSUE TITLE
Full panels are immovable

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/cinnamon#12427]
### Distribution

Mint 22

### Package version

6.2.9

### Frequency

Always

### Bug description

If a panel is full, one cannot move it. For, to move it, one must (middle) click upon an empty area within the panel. If a panel is nearly full, then one must hunt around for a bit of free space on which to click. Note also that on some touchpads middle-clicking itself isn't easy, yielding altogether No Fun At All.

### Steps to reproduce

1. Have a full panel.
2. Try to move it to another panel position.
3. Fail.

### Expected behavior

Not 3.

Functions should not be available only when some particular contingent circumstance obtains (at least not if the circumstance has no bearing upon whether one will need the function).

### Additional information

The advice within this very issue template says: 'Right-click an empty portion of the panel, select Troubleshooting, then "Restart Cinnamon". ' What if there is no empty space?

Another thing one cannot do if a panel is full is to leave 'edit' mode. The panel settings window - accessible via the main menu - does have an 'edit mode' toggle button, but I found that toggling it did not in fact quit edit mode.

**Comment by leigh123linux** [comment]
Use another workspace or close some apps to free some space.
