### ISSUE TITLE
Linux Mint 22 Won't properly shutdown after the PC is powered ON for more than 8 hours

### ISSUE THREAD

**Issue by kolotxoz** [linuxmint/cinnamon#12423]
### Distribution

Mint 22 Wilma

### Package version

Cinnamon 6.2.9

### Graphics hardware in use

Intel UHD 630

### Frequency

Quite often

### Bug description

Linux Mint wont turn off the machine entirely after clicking the shutdown button located in the "Start" menu, the shutdown process starts, but never completes, as the RGB lights from the case and the motherboard remain on, the display does turn off.

The problem doesn't happen with the restart option, only on shutdown, the system cannot be restarted with the REISUB combination.

### Steps to reproduce

The machine has to stay on (doesn't matter if in use or idling ) for more than 8 hours approximately, and then use the Power Off button from the 'Start' menu

### Expected behavior

The computer must fully shutdown normally, no RBG lights must remain on.

### Additional information

The case of the PC is this: https://aerocool.io/product/split/

The motherboard used is this: https://rog.asus.com/motherboards/rog-strix/rog-strix-b250f-gaming-model/

The display is connected through the HDMI port.

The system specs are these:

user@B250F:~ inxi -F
System:
  Host: B250F Kernel: 6.8.0-45-generic arch: x86_64 bits: 64
  Desktop: Cinnamon v: 6.2.9 Distro: Linux Mint 22 Wilma
Machine:
  Type: Desktop Mobo: ASUSTeK model: STRIX B250F GAMING v: Rev X.0x
    serial: <superuser required> UEFI: American Megatrends v: 2001
    date: 07/13/2021
CPU:
  Info: quad core model: Intel Core i7-7700 bits: 64 type: MT MCP cache:
    L2: 1024 KiB
  Speed (MHz): avg: 800 min/max: 800/4200 cores: 1: 800 2: 800 3: 800 4: 800
    5: 800 6: 800 7: 800 8: 800
Graphics:
  Device-1: Intel HD Graphics 630 driver: i915 v: kernel
  Display: x11 server: X.Org v: 21.1.11 with: Xwayland v: 23.2.6 driver: X:
    loaded: modesetting unloaded: fbdev,vesa dri: iris gpu: i915
    resolution: 1440x900~60Hz
  API: EGL v: 1.5 drivers: iris,swrast platforms: x11,surfaceless,device
  API: OpenGL v: 4.6 compat-v: 4.5 vendor: intel mesa v: 24.0.9-0ubuntu0.1
    renderer: Mesa Intel HD Graphics 630 (KBL GT2)
Audio:
  Device-1: Intel 200 Series PCH HD Audio driver: snd_hda_intel
  Device-2: GN Netcom Jabra EVOLVE 20 driver: jabra,snd-usb-audio,usbhid
    type: USB
  API: ALSA v: k6.8.0-45-generic status: kernel-api
  Server-1: PipeWire v: 1.0.5 status: active
Network:
  Device-1: Intel Ethernet I219-V driver: e1000e
  IF: enp0s31f6 state: down mac: 70:4d:7b:89:da:38
  Device-2: Realtek 802.11ac NIC driver: rtl8821cu type: USB
  IF: wlxa0d768110bd9 state: up mac: a0:d7:68:11:0b:d9
RAID:
  Hardware-1: Intel SATA Controller [RAID mode] driver: ahci
Drives:
  Local Storage: total: 1.38 TiB used: 34.38 GiB (2.4%)
  ID-1: /dev/nvme0n1 vendor: Seagate model: XPG GAMMIX S50 Lite
    size: 476.94 GiB
  ID-2: /dev/sda vendor: TeamGroup model: T253X7001T size: 931.51 GiB
Partition:
  ID-1: / size: 138.71 GiB used: 34.31 GiB (24.7%) fs: ext4
    dev: /dev/nvme0n1p5
  ID-2: /boot/efi size: 96 MiB used: 64.7 MiB (67.3%) fs: vfat
    dev: /dev/nvme0n1p1
Swap:
  ID-1: swap-1 type: partition size: 2 GiB used: 0 KiB (0.0%)
    dev: /dev/nvme0n1p6
Sensors:
  System Temperatures: cpu: 46.0 C mobo: N/A
  Fan Speeds (rpm): N/A
Info:
  Memory: total: 32 GiB note: est. available: 30.29 GiB used: 5.19 GiB (17.1%)
  Processes: 294 Uptime: 3h 32m Shell: Bash inxi: 3.3.34

**Comment by leigh123linux** [comment]
Report the issue against the kernel.
Also you provided no useful info needed to debug the issue.

**Comment by Newbie3576** [comment]
@kolotxoz   Hi, have you found a solution possibly?

**Comment by kolotxoz** [comment]
> [@kolotxoz](https://github.com/kolotxoz) Hi, have you found a solution possibly?

Hi, no, my """solution""" was to update to Mint 22.2, for the moment, the problem is gone

**Comment by Newbie3576** [comment]
@kolotxoz Thanks for your reply. Good to hear the problem seems to be gone 👍️
