### ISSUE TITLE
Network Manager (network@cinnamon.org): Appears offline despite being online

### ISSUE THREAD

**Issue by idc77** [linuxmint/cinnamon#12420]
### Distribution

Archlinux

### Package version

6.2.9

### Graphics hardware in use

NV 4070

### Frequency

Always

### Bug description

Since... recently... I can't say since when exactly, let's say in the last 30 days,
The Networkmanager applet on the taskbar shows a "not connected" icon and left clicking it shows an empty dialog box.
Right clicking show a dialog box with a menu with items

- about
- configure
- remove networkmanager

Notifications are
wired 1 has been disconnected (not the exact words)
2 seconds later
you are now connected to the wired 1 network

### Steps to reproduce

I can't answer that.
Boot my arch install with cinnamon and networkamanger enabled I guess?

### Expected behavior

The applet showing that it's connected
Left clicking showing, I don't know what, but not an empty dialog window, probably the ability to configure connections.

### Additional information

The configure item only leads to setting hotkeys

![cinnamon-networkmanager1](https://github.com/user-attachments/assets/ed24742d-c542-447a-ac21-e2bcf8fead1c)
![cinnamon-networkmanager2](https://github.com/user-attachments/assets/dcb35b6e-025e-4a4d-bae1-ea0343b30ef8)

**Comment by leigh123linux** [comment]
It's either a networkmanager or kernel issue.

**Comment by idc77** [comment]
Because?
