### ISSUE TITLE
Update from 6.8.0-38-generic to 6.60-45 generic makes touchpad behave erratically

### ISSUE THREAD

**Issue by frankvw2017** [linuxmint/cinnamon#12433]
### Distribution

Mint 22

### Package version

6.2.9

### Graphics hardware in use

VGA compatible controller: Intel Corporation GeminiLake [UHD Graphics 600] (rev 06)

### Frequency

Always

### Bug description

Since the update from 6.8.0-38-generic to 6.8.0-45-generic the touchpad on my PackardBell laptop is behaving erratically. The mouse cursor jumps randomly and mouse clicks are being registered randomly, even though I am not touching the system at all. This is so bad that the system has become essentially unusable. Entering the grub menu and booting the previous (6.8.0-38) version makes the problem disappear.

### Steps to reproduce

Not sure if it is hardware related. Booting into the most recent Linux Mint/Cinnamon version on my PackardBell laptop reliable reproduces the problem. On other systems it may not.

### Expected behavior

I expected the latest update not to break touchpad support to the point of rendering my system useless. :-)

### Additional information

https://forums.linuxmint.cm/viewtopic.php?p=2533956 refers.

**Comment by leigh123linux** [comment]
This isn't the right place to report your issue.
Either use 6.8.0-38-generic or report your issue against the kernel.
