### ISSUE TITLE
Can't make a screenshot when an applet menu is open. 

### ISSUE THREAD

**Issue by edofe99** [linuxmint/cinnamon#12445]
### Distribution

Mint 22 Cinnamon

### Package version

6.2.9

### Graphics hardware in use

Ryzen 5

### Frequency

Always

### Bug description

If you try to make a screenshot with an applet menu opened, like sound applet, the screenshot wont work. 
To make the description more effecive: try to make a screenshot of Cinnamon menu opened, you wont be able to do so. 

### Steps to reproduce

1. Set a favourite keyboard shortcut for making a screenshot. 
2. Test the hotkey and make a screenshot. 
3. Click sound applet, or caalendar, or wathever lies on your panel.
4. Try to make a screenshot by pressing the keyboard combination. 
5. It wont work. 

### Expected behavior

I expect that I can make a screenshot.

**Comment by claudiux** [comment]
@edofe99 
Here's how I solved this problem:

System settings -> Keyboard: Shortcuts tab. Add a custom shortcut:
Name: Delayed Screenshot
Command: `/usr/bin/gnome-screenshot -c -d 5`
Match it with: Super+print

When you use the **Super+print** shortcut, you have 5 seconds to open an applet menu. The screenshot is stored in the clipboard; you can paste it wherever you like.

**Comment by leigh123linux** [comment]
Closed as not planned.

**Comment by mtwebster** [comment]
Works fine for me.

Open a menu from a Cinnamon applet, hit the screenshot key.

What you cannot do is make an area selection while a menu is open. For that you can run the screenshot tool from the menu, add a delay, choose "Selection" then open the menu during the delay.
