### ISSUE TITLE
Bluetooth is reactivated after reboot

### ISSUE THREAD

**Issue by dtrunk90** [linuxmint/Cinnamon#1244]
My bluetooth is always reactivated after reboot, even if i disabled it in the last session by clicking on the symbol and turning it off...

does anyone else noticed this?

**Comment by JosephMcc** [comment]
Can anyone else still reproduce this problem under Cinnamon3?

**Comment by dtrunk90** [comment]
I can reproduce it again in conjunction with blueberry. But it happens only sporadically. In addition: If it happens and I open up blueberry my computer is recognized as "Bastien's computer" instead of "danny".

**Comment by JosephMcc** [comment]
Could you please add that info to this: https://github.com/linuxmint/blueberry/issues/11

They are likely related and the issue is probably there.
