### ISSUE TITLE
Inverted keycode for Apple family products

### ISSUE THREAD

**Issue by krisden** [linuxmint/cinnamon#12457]
### Distribution

Mint 22 - LMDE 6

### Package version

5.8.4

### Graphics hardware in use

ATI Radeon 6630M

### Frequency

Always

### Bug description

Bug is due to the installer, with LM 22 (Cinnamon and Mate version) and LMDE 6 fresh install but after use "mintupgrade" script too (21.3 to 22).
Keycode 49 and 94 are inverted (@ and <> keys).
Tests done on a late 2011 iMac (little `azerty` alu keyboard (without numeric pad) and a mid 2012 Macbook pro.

### Steps to reproduce

Boot on usb live media
Launch install LM 21.3 Cinnamon or Mate version (all tested on each pc)
Choose locale (french), keyboard type = Apple, mapping = fr-macintosh
Everything works well, locale and mapping are set correctly (at screen login connection and in the user session)

Now, apply updates, install "mintupgrade" package and launch it
After reboot, "@" and "<>" are inverted.

It is the same situation with the installer : try different setup for Apple pc, mapping pictures are ok but keycodes no

PS : especially for LMDE 6 installer, if you choose `model : macbbok pro` or `apple`, `mapping : macintosh` and locale `fr`, locale is set to english...

### Expected behavior

I've test with `xev` in order to check the mapping codes, create a `xmodmap` file, invert the two `49` and `94` keycode, launch it, it works (no persistent solution find after reboot)

**Comment by leigh123linux** [comment]
You need to file this issue at https://github.com/linuxmint/linuxmint/issues
