### ISSUE TITLE
Networking does not work when I upgraded to 5.15.0-124-generic kernel.

### ISSUE THREAD

**Issue by sellam-i** [linuxmint/cinnamon#12458]
### Distribution

Linux Mint 21.3 Virginia

### Package version

I'm not running Cinnamon, wtf.

### Graphics hardware in use

?

### Frequency

Always

### Bug description

I upgraded to 5.15.0-124-generic last night and when I woke my computer up this morning networking was not working.  My TP-Link TL-WN823N v2/v3 [Realtek RTL8192EU] USB WiFi adaptor (my normal network connection) would not come up.  The kernel does not seem to have this driver installed.  I simply could not bring up this interface no matter what I did.  Note: It was working JUST FINE before the downgrade.

In an attempt to get online to download the driver, I plugged my phone in via USB and turned on tethering.  I could ping to the gateway but beyond that I could not access the internet.

HERE'S THE KICKER (PAY ATTENTION, KIDS):

I reverted back to kernel 5.15.0-122-generic and everything worked fine again.

I'm the least sophisticated consumer here.  I have given you all I know.  Someone messed up the new kernel and fucked up networking.  Please fix it.

### Steps to reproduce

Upgrade your computer with my exact configuration and you can maybe reproduce the problem.

### Expected behavior

I expect the internet to work.

### Additional information

Thanks for your effort.

**Comment by leigh123linux** [comment]
> ### Package version
> I'm not running Cinnamon, wtf.

**Comment by leigh123linux** [comment]
File your issue at https://github.com/linuxmint/linuxmint/issues
