### ISSUE TITLE
Linux Mint 22 Cinnamon randomly restarts system

### ISSUE THREAD

**Issue by mihnea-radulescu** [linuxmint/cinnamon#12459]
### Distribution

22 (installed from scratch)

### Package version

6.2.9 (using X11)

### Graphics hardware in use

Integrated AMD ATI 04:00.0 Lucienne (from AMD Ryzen 5 5500U)

### Frequency

Quite often

### Bug description

The system restarts randomly, regardless of running apps, load, system resource usage, etc.

It seems to be related to the Cinnamon desktop environment and X11. 

### Steps to reproduce

Since the behavior is random, the steps to reproduce cannot be provided.

### Expected behavior

The system does not restart randomly.

### Additional information

[xsession-errors.txt](https://github.com/user-attachments/files/17451454/xsession-errors.txt)

**Comment by claudiux** [comment]
@mihnea-radulescu 
Try this:

- Open System settings
- Open Startup Applications
- Uncheck "Cinnamon Stats Tracker"
- Log out then log in.

**Comment by mihnea-radulescu** [comment]
Thanks for the suggestion, @claudiux, but my Startup Applications do not have the Cinnamon Stats Tracker app present, only the apps below.

![image](https://github.com/user-attachments/assets/a41bbd80-7a54-4db9-aa5e-9d57497a46fe)

**Comment by claudiux** [comment]
@mihnea-radulescu 
So, please install mint-dev-tools:
`apt install mint-dev-tools`

**Comment by mihnea-radulescu** [comment]
Thank you again for the update, @claudiux!

I deleted /etc/xdg/autostart/cinnamon-stats-tracker.desktop, since, indeed, it referenced a previous install of mint-tools, as well as /home/mihnea/.config/autostart/cinnamon-stats-tracker.desktop, and then restarted the system.

The error no longer appears in the .xsession-errors log, hopefully this will fix the random restarts.

I will close the issue in a couple of days, if no future random restart occurs, or update it, if restarts continue to happen.

**Comment by claudiux** [comment]
I should have thought that you had already installed and then removed (but not entirely) this package. Your solution is better than mine.

**Comment by mihnea-radulescu** [comment]
As the random system restarts have not reoccurred, I am closing this issue as fixed.
