### ISSUE TITLE
Gentoo Wayland isn't emerging

### ISSUE THREAD

**Issue by ActuallyTheOwner** [linuxmint/cinnamon#12472]
### Distribution

Gentoo Linux x86_64

### Package version

cinnamon-6.2.9.ebuild

### Graphics hardware in use

Nvidia RTX 3060

### Frequency

Always

### Bug description

When I emerge cinnamon, the useflag wayland becomes (-wayland) indicating something prevents me from using wayland. I have tried the ~amd64 keyword with no luck. 

### Steps to reproduce

I set use flags for Cinnamon in /etc/portage/package.use/cinnamon             
                                                                   
gnome-extra/cinnamon wayland gnome-keyring pulseaudio icu internal-polkit
gnome-extra/nemo wayland

### Expected behavior

Cinnamon should emerge with wayland as I have wayland support enabled for nvidia, and I have wayland installed on it's own.

### Additional information

I use Nvidia Driver Version: 565.57.01 with open kernel and wayland support

**Comment by leigh123linux** [comment]
You will need to ask at gentoo bug tracker.
