### ISSUE TITLE
[Question] How  to disable the key binding Alt-`?

### ISSUE THREAD

**Issue by netjune** [linuxmint/cinnamon#12480]
It currently switches between windows of the same application. This key binding conflicts with my app. I want to disable this key binding in cinnamon. But I can't find where it is in setting center.

**Comment by mtwebster** [comment]
For some reason it's displayed as 'Alt+AboveTab` in the keyboard bindings:
![image](https://github.com/user-attachments/assets/9d5d782c-ed8f-4abd-ba28-1f88aae7a8f5)

Click on the binding entry in the lower pane, then Backspace to clear it.
