### ISSUE TITLE
Network Manager (network@cinnamon.org) - VPN connections are unsorted, in random order

### ISSUE THREAD

**Issue by Kurgan-** [linuxmint/cinnamon#12485]
### Distribution

Linux Mint 21.3 Virginia

### Package version

Cinnamon 6.0.4

### Graphics hardware in use

Intel Iris XE

### Frequency

Always

### Bug description

When I open the network manager applet, the list of available VPNs (and the list of available WIFI networks, too)  is shown in a random order.  (I have edited out the names, but you can see that they are not in alphabetical order, or any other order, actually).

![image](https://github.com/user-attachments/assets/65996f71-62fd-49a0-9391-75f9aa7cae37)

### Steps to reproduce

Configure more than one VPN, or show the list of available WIFI connections, supposing there is more than one.

### Expected behavior

The list should be shown in alphabetical order, or maybe in some other sensible order.

**Comment by JosephMcc** [comment]
You just posted in the existing issue: https://github.com/linuxmint/cinnamon/issues/9859#issuecomment-2454905247

There is no reason to open a duplicate.

**Comment by Kurgan-** [comment]
It's actually a different issue. 

Bug 9859 is an issue with the list that changes (wifi networks are added to the list when you open it) and so you end up clicking on the wrong vpn because the list changes while you click.

This bug is about a sorting issue.
