### ISSUE TITLE
Themes not sorting by name in cinnamon-settings

### ISSUE THREAD

**Issue by ChooChooAl** [linuxmint/cinnamon#12493]
### Distribution

Mint 22

### Package version

Cinnamon 6.2.9 

### Graphics hardware in use

Intel UHD Graphics 620

### Frequency

Always

### Bug description

Cinnamon-settings themes, does not sort the themes by name.  Either applications or desktop.
This works in Mint 21.3
My themes are:
    Fluent-purple-Dark
    Lightningbug-Solid-Dark
    Mint-DarkGreen
    Mint-DarkOrange
    Mint-DarkPurple
    Mint-DarkRed
    Mint-DarkTeal
    Mint-Green
    Mint-Teal
    Orchis-Orange-Dark
    Yaru-olive-dark2

![Cinnamon-Settings](https://github.com/user-attachments/assets/0b522cac-dde1-4f21-a25b-9f34147779de)
My themes in ~/.themes have custom icons.  Read between the lines.   It's the name sorting I'm calling the bug.

Mint-DarkOrange is sorted in the wrong place.
Not only that but the custom Yaru-olive-dark2 (a copy of the system theme Yaru-olive-dark) in my .themes folder also sorts way before other system Yaru* themes (they show at the bottom and are not in the screenshot).   

### Steps to reproduce

Open settings->themes.
Have create a few themes in your home folder ~/.themes    You can copy one theme from /usr/share/themes and just duplicate it several times.   Chose names that are different, not all "Mint*". 
Reproduce the same names I have listed above.

### Expected behavior

All themes, mine and system, should sort alphabetically.   Or one would assume so.

**Comment by rcalixte** [comment]
Isn't this a feature? If you installed your own themes beyond the ones that are on the system, shouldn't they come first? Even if you were to disagree, this seems more like a design decision that you disagree with, not a bug. What if others prefer to have the theme(s) they installed come before the system themes?

**Comment by ChooChooAl** [comment]
That might be a good idea, and it seems to work for 'applications' but for 'desktop' it does not.
![Cinnamon-settings2](https://github.com/user-attachments/assets/2f7033f9-5d2a-4862-9463-c6deee5e3c3c)
I had Mint-DarkOrange (mine) linked to /usr/share/themes so the app thought that was part of the system and sorted it that way.   But cinnamon is a system theme and it sorts at the top before mine.

![Cinnamon-settings3](https://github.com/user-attachments/assets/31382ab3-0bac-484c-99df-fba908f1a96e)
With Mint-DarkOrange unlinked, all of my themes do sort at the top in 'applications' (no picture) and in 'desktop' they do too except for cinnamon theme.   

I can live with it this way.  Not sure why cinnamon does this but one out of 40 is fine with me.

**Comment by ChooChooAl** [comment]
Closed.
