### ISSUE TITLE
Gnome-terminal slow to start when connecting remotly with rdesktop

### ISSUE THREAD

**Issue by bcharbonneaupoly** [linuxmint/cinnamon#12499]
### Distribution

Mint 22

### Package version

6.2.9

### Frequency

Always

### Bug description

When connecting normally, gnome-terminal open instantly. When connecting remotly with rdesktop via xrdp, gnome-terminal open the first time in about 20 seconds. After that, it open instantly until the user log off.

The problem was not present in Mint 21. It is new with Mint 22.

In got the following in the logs:

7T00:00:00-04 to 2024-12-07T23:59:59-05
2024-11-04T09:22:28.166651-05:00 xxxx-xxx-07 cinnamon-session-binary[36058]: WARNING: t+22.22175s: Unable to inhibit system: GDBus.Error:org.freedesktop.DBus.Error.AccessDenied: Permission denied
2024-11-04T09:22:37.021950-05:00 xxxx-xxx-07 dbus-daemon[36065]: [session uid=59219997 pid=36063] Successfully activated service 'org.gnome.Terminal'
2024-11-04T09:22:37.139327-05:00 xxxx-xxx-07  xdg-desktop-por[37294]: Failed to create secret proxy: Error calling StartServiceByName for org.freedesktop.secrets: Timeout was reached
2024-11-04T09:22:37.139416-05:00 xxxx-xxx-07  xdg-desktop-por[37294]: No skeleton to export
2024-11-04T09:22:37.139705-05:00 xxxx-xxx-07  dbus-daemon[36065]: [session uid=59219997 pid=36063] Successfully activated service 'org.freedesktop.portal.Desktop'

Gnome-terminal open when the timout is reached...

### Steps to reproduce

1. Install xrdp
2. connect remotly
3. open gnome-terminal

### Expected behavior

gnome-terminal should open instantly.

**Comment by clefebvre** [comment]
This looks like an upstream issue in gnome-terminal. Can you reproduce this issue with Ubuntu 24.04 (using GNOME)?

**Comment by mtwebster** [comment]
I can't reproduce this in Mint 22 - 
```
Nov 14 13:16:19 mintbox3 systemd[50422]: Started xdg-desktop-portal-gtk.service - Portal service (GTK/GNOME implementation).
Nov 14 13:16:19 mintbox3 dbus-daemon[50444]: [session uid=1003 pid=50444] Successfully activated service 'org.freedesktop.impl.portal.desktop.gtk'
Nov 14 13:16:19 mintbox3 dbus-daemon[50444]: [session uid=1003 pid=50444] Successfully activated service 'org.freedesktop.portal.Desktop'
Nov 14 13:16:19 mintbox3 systemd[50422]: Started xdg-desktop-portal.service - Portal service.
Nov 14 13:16:19 mintbox3 dbus-daemon[50444]: [session uid=1003 pid=50444] Successfully activated service 'org.gnome.Terminal'
Nov 14 13:16:19 mintbox3 systemd[50422]: Started gnome-terminal-server.service - GNOME Terminal Server.
Nov 14 13:16:19 mintbox3 systemd[50422]: Started vte-spawn-444a5b82-4761-4562-9f92-f3c0c55a22af.scope - VTE child process 51504 launched by gnome-terminal-server process 51460.
~
```

The permission errors I see make me think there's something wrong in the environment - are there any relevant messages on your local machine's logs?

**Comment by bcharbonneaupoly** [comment]
With XRDP / Remote desktop, the portal services are not running.

Here is the log of xdg-desktop-portal --verbose.  Gnome-terminal is still slow to launch.  I alors tried the solution (DISPLAY=:10 timeout 0.5 xmessage -iconic x) from 3053 but it did not help...

etutestab@lava-vnl-07:~$ /usr/libexec/xdg-desktop-portal --verbose
XDP: Looking for portals configuration in '/home/hephaistos/etutestab/.config/xdg-desktop-portal/x-cinnamon-portals.conf'
XDP: Looking for portals configuration in '/home/hephaistos/etutestab/.config/xdg-desktop-portal/portals.conf'
XDP: Looking for portals configuration in '/etc/xdg/xdg-desktop-portal/x-cinnamon-portals.conf'
XDP: Looking for portals configuration in '/etc/xdg/xdg-desktop-portal/portals.conf'
XDP: Looking for portals configuration in '/etc/xdg-desktop-portal/x-cinnamon-portals.conf'
XDP: Looking for portals configuration in '/etc/xdg-desktop-portal/portals.conf'
XDP: Looking for portals configuration in '/home/hephaistos/etutestab/.local/share/xdg-desktop-portal/x-cinnamon-portals.conf'
XDP: Looking for portals configuration in '/home/hephaistos/etutestab/.local/share/xdg-desktop-portal/portals.conf'
XDP: Looking for portals configuration in '/home/hephaistos/etutestab/.local/share/flatpak/exports/share/xdg-desktop-portal/x-cinnamon-portals.conf'
XDP: Looking for portals configuration in '/home/hephaistos/etutestab/.local/share/flatpak/exports/share/xdg-desktop-portal/portals.conf'
XDP: Looking for portals configuration in '/var/lib/flatpak/exports/share/xdg-desktop-portal/x-cinnamon-portals.conf'
XDP: Looking for portals configuration in '/var/lib/flatpak/exports/share/xdg-desktop-portal/portals.conf'
XDP: Looking for portals configuration in '/usr/local/share/xdg-desktop-portal/x-cinnamon-portals.conf'
XDP: Looking for portals configuration in '/usr/local/share/xdg-desktop-portal/portals.conf'
XDP: Looking for portals configuration in '/usr/share/xdg-desktop-portal/x-cinnamon-portals.conf'
XDP: Preferred portals for interface 'default': xapp, gtk
XDP: Preferred portals for interface 'org.freedesktop.impl.portal.Secret': gnome-keyring
XDP: Using portal configuration file '/usr/share/xdg-desktop-portal/x-cinnamon-portals.conf' for desktop 'x-cinnamon'
XDP: load portals from /usr/share/xdg-desktop-portal/portals
XDP: loading /usr/share/xdg-desktop-portal/portals/xapp-gnome-keyring.portal
XDP: portal implementation supports org.freedesktop.impl.portal.Secret
XDP: loading /usr/share/xdg-desktop-portal/portals/xapp.portal
XDP: portal implementation supports org.freedesktop.impl.portal.Wallpaper
XDP: portal implementation supports org.freedesktop.impl.portal.Inhibit
XDP: portal implementation supports org.freedesktop.impl.portal.Screenshot
XDP: portal implementation supports org.freedesktop.impl.portal.Lockdown
XDP: portal implementation supports org.freedesktop.impl.portal.Settings
XDP: portal implementation supports org.freedesktop.impl.portal.Background
XDP: loading /usr/share/xdg-desktop-portal/portals/gnome-keyring.portal
XDP: portal implementation supports org.freedesktop.impl.portal.Secret
XDP: loading /usr/share/xdg-desktop-portal/portals/gtk.portal
XDP: portal implementation supports org.freedesktop.impl.portal.FileChooser
XDP: portal implementation supports org.freedesktop.impl.portal.AppChooser
XDP: portal implementation supports org.freedesktop.impl.portal.Print
XDP: portal implementation supports org.freedesktop.impl.portal.Notification
XDP: portal implementation supports org.freedesktop.impl.portal.Inhibit
XDP: portal implementation supports org.freedesktop.impl.portal.Access
XDP: portal implementation supports org.freedesktop.impl.portal.Account
XDP: portal implementation supports org.freedesktop.impl.portal.Email
XDP: portal implementation supports org.freedesktop.impl.portal.DynamicLauncher
XDP: portal implementation supports org.freedesktop.impl.portal.Lockdown
XDP: portal implementation supports org.freedesktop.impl.portal.Settings
XDP: Found 'xapp' in configuration for default
XDP: Using xapp.portal for org.freedesktop.impl.portal.Lockdown (config)
XDP: providing portal org.freedesktop.portal.MemoryMonitor
XDP: providing portal org.freedesktop.portal.PowerProfileMonitor
XDP: providing portal org.freedesktop.portal.NetworkMonitor
XDP: providing portal org.freedesktop.portal.ProxyResolver
XDP: providing portal org.freedesktop.portal.Trash
XDP: providing portal org.freedesktop.portal.GameMode
XDP: providing portal org.freedesktop.portal.Realtime
XDP: Found 'xapp' in configuration for default
XDP: Using xapp.portal for org.freedesktop.impl.portal.Settings (config)
XDP: Found 'gtk' in configuration for default
XDP: Using gtk.portal for org.freedesktop.impl.portal.Settings (config)
XDP: providing portal org.freedesktop.portal.Settings
XDP: Found 'gtk' in configuration for default
XDP: Using gtk.portal for org.freedesktop.impl.portal.FileChooser (config)
XDP: providing portal org.freedesktop.portal.FileChooser
XDP: Found 'gtk' in configuration for default
XDP: Using gtk.portal for org.freedesktop.impl.portal.AppChooser (config)
XDP: providing portal org.freedesktop.portal.OpenURI
XDP: Found 'gtk' in configuration for default
XDP: Using gtk.portal for org.freedesktop.impl.portal.Print (config)
XDP: providing portal org.freedesktop.portal.Print
XDP: Found 'gtk' in configuration for default
XDP: Using gtk.portal for org.freedesktop.impl.portal.Notification (config)
XDP: providing portal org.freedesktop.portal.Notification
XDP: Found 'xapp' in configuration for default
XDP: Using xapp.portal for org.freedesktop.impl.portal.Inhibit (config)
XDP: providing portal org.freedesktop.portal.Inhibit
XDP: Found 'gtk' in configuration for default
XDP: Using gtk.portal for org.freedesktop.impl.portal.Access (config)
XDP: providing portal org.freedesktop.portal.Device
XDP: providing portal org.freedesktop.portal.WebExtensions
XDP: providing portal org.freedesktop.portal.Location
XDP: providing portal org.freedesktop.portal.Camera
XDP: Found 'xapp' in configuration for default
XDP: Using xapp.portal for org.freedesktop.impl.portal.Screenshot (config)
XDP: providing portal org.freedesktop.portal.Screenshot
XDP: Found 'xapp' in configuration for default
XDP: Using xapp.portal for org.freedesktop.impl.portal.Background (config)
XDP: Starting background app monitor
XDP: providing portal org.freedesktop.portal.Background
XDP: Found 'xapp' in configuration for default
XDP: Using xapp.portal for org.freedesktop.impl.portal.Wallpaper (config)
XDP: providing portal org.freedesktop.portal.Wallpaper
XDP: Found 'gtk' in configuration for default
XDP: Using gtk.portal for org.freedesktop.impl.portal.Account (config)
XDP: using org.freedesktop.impl.portal.Account at org.freedesktop.impl.portal.desktop.gtk


XDP: providing portal org.freedesktop.portal.Account
XDP: Found 'gtk' in configuration for default
XDP: Using gtk.portal for org.freedesktop.impl.portal.Email (config)
XDP: providing portal org.freedesktop.portal.Email
XDP: Found 'gnome-keyring' in configuration for org.freedesktop.impl.portal.Secret
XDP: Using gnome-keyring.portal for org.freedesktop.impl.portal.Secret (config)

(/usr/libexec/xdg-desktop-portal:15958): xdg-desktop-portal-WARNING **: 14:45:29.339: Failed to create secret proxy: Error calling StartServiceByName for org.freedesktop.secrets: Timeout was reached

(/usr/libexec/xdg-desktop-portal:15958): xdg-desktop-portal-WARNING **: 14:45:29.339: No skeleton to export
XDP: Found 'gtk' in configuration for default
XDP: Using gtk.portal for org.freedesktop.impl.portal.DynamicLauncher (config)
XDP: providing portal org.freedesktop.portal.DynamicLauncher
XDP: Running app windows changed, wake up monitor thread

**Comment by bcharbonneaupoly** [comment]
Ok I tried to reproduce the issue with a new installation on another computer but everything is normal.  I will try to reinstall Mint on the computer with the problem.

**Comment by bcharbonneaupoly** [comment]
A reinstallation of Mint 22 fixed the issue.  I don't know what went wrong with the initinal installation...

**Comment by bcharbonneaupoly** [comment]
A reinstallation of Mint 22 fixed the issue.  I don't know what went wrong with the initinal installation...
