### ISSUE TITLE
Audio Applet Disappeared after update [sound@cinnamon.org]

### ISSUE THREAD

**Issue by KingKusuo** [linuxmint/cinnamon#12522]
### Distribution

Endeavour OS 6.12.1-arch1-1 

### Package version

6.2.9

### Graphics hardware in use

RX 6650 XT

### Frequency

Always

### Bug description

After an update for the Cinnamon packages i started receiving a popup saying that there was an error loading something on cinnamon, after some digging i found out that the sound applet was gone, and now changing the volume is impossible even when using the volume knob on my keyboard, also cannot pause media using the play/pause button on my mouse

The notification i received told me to contact the developers
![image](https://github.com/user-attachments/assets/dc6bf090-6cbb-4f2f-b9a0-342ada7c7b66)
Translation: "Problems during Cinnamon startup
Cinnamon started successfully, but it was not possible to load one or more applets, desklets, or extensions.

Check the system log and the Cinnamon LookingGlass log for any issues. You can disable the extension(s) in the Cinnamon Settings to prevent this message from appearing repeatedly. Please contact the developer."

LookingGlass logs show this error message:
![image](https://github.com/user-attachments/assets/f91cb9d1-e351-4a52-aa5d-e45d6521ea55)

Ctrl + Alt + T (Terminal Opening) and some other shortcuts like Super + E (Nemo) also does not seem to be working when pressed.
Some Cinnamon applications also are not opening, like the "Sound" application and  the Energy Management application

### Steps to reproduce

Start or Reload cinnamon, get the error notification and fail to load the Sound applet, fail to open specific cinnamon applications and use specific keybinds

### Expected behavior

The Sound applet should be loading normally and i should be able to change the volume and control my media through the applet
Also, i should be able to open the "Sound" application, same as the Energy Management application, and the keybinds for opening the terminal or nemo

### Additional information

_Pacman packages update history:_
[2024-11-26T11:40:05-0300] [ALPM] running '30-systemd-daemon-reload-user.hook'...
[2024-11-26T11:40:05-0300] [ALPM] running '30-systemd-update.hook'...
[2024-11-26T11:40:05-0300] [ALPM] running 'gtk-update-icon-cache.hook'...
[2024-11-26T11:40:05-0300] [ALPM] running 'update-desktop-database.hook'...
[2024-11-26T19:03:59-0300] [PACMAN] Running 'pacman -Sy'
[2024-11-26T19:03:59-0300] [PACMAN] synchronizing package lists
[2024-11-26T19:04:00-0300] [PACMAN] Running 'pacman -Su'
[2024-11-26T19:04:00-0300] [PACMAN] starting full system upgrade
[2024-11-26T19:04:23-0300] [ALPM] transaction started
**[2024-11-26T19:04:23-0300] [ALPM] upgraded cinnamon-menus (6.2.0-1 -> 6.4.0-1)**
**[2024-11-26T19:04:23-0300] [ALPM] upgraded cjs (6.2.0-1 -> 6.4.0-1)**
**[2024-11-26T19:04:23-0300] [ALPM] upgraded xapp (2.8.5-1 -> 2.8.6-1)**
[2024-11-26T19:04:23-0300] [ALPM] upgraded xed (3.6.6-2 -> 3.6.7-1)
[2024-11-26T19:04:23-0300] [ALPM] transaction completed

**[2024-11-26T19:55:05-0300] [ALPM] upgraded cinnamon-desktop (6.2.0-1 -> 6.4.0-1)**
**[2024-11-26T19:55:05-0300] [ALPM] upgraded cinnamon-control-center (6.2.0-1 -> 6.4.0-1)**
**[2024-11-26T19:55:05-0300] [ALPM] upgraded cinnamon-screensaver (6.2.1-1 -> 6.4.0-1)**
**[2024-11-26T19:55:06-0300] [ALPM] upgraded cinnamon-translations (6.2.2-1 -> 6.4.0-1)**
**[2024-11-26T19:55:06-0300] [ALPM] upgraded muffin (6.2.0-2 -> 6.4.0-1)**
[2024-11-26T19:55:06-0300] [ALPM] transaction completed

_#################### inxi -Fxxc0z ########################_

System:
  Kernel: 6.12.1-arch1-1 arch: x86_64 bits: 64 compiler: gcc v: 14.2.1
  Desktop: Cinnamon v: 6.2.9 tk: GTK v: 3.24.43 wm: Muffin dm: LightDM Distro: EndeavourOS
    base: Arch Linux
Machine:
  Type: Desktop System: ASUS product: N/A v: N/A serial: <superuser required>
  Mobo: ASUSTeK model: TUF GAMING B550M-PLUS v: Rev X.0x serial: <superuser required>
    part-nu: SKU UEFI: American Megatrends v: 3607 date: 03/22/2024
CPU:
  Info: 12-core model: AMD Ryzen 9 5900X bits: 64 type: MT MCP arch: Zen 3+ rev: 2 cache:
    L1: 768 KiB L2: 6 MiB L3: 64 MiB
  Speed (MHz): avg: 3404 min/max: 550/4951 boost: enabled cores: 1: 3404 2: 3404 3: 3404 4: 3404
    5: 3404 6: 3404 7: 3404 8: 3404 9: 3404 10: 3404 11: 3404 12: 3404 13: 3404 14: 3404 15: 3404
    16: 3404 17: 3404 18: 3404 19: 3404 20: 3404 21: 3404 22: 3404 23: 3404 24: 3404
    bogomips: 177652
  Flags: avx avx2 ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm
Graphics:
  Device-1: Advanced Micro Devices [AMD/ATI] Navi 23 [Radeon RX 6650 XT / 6700S 6800S] vendor: XFX
    driver: amdgpu v: kernel arch: RDNA-2 pcie: speed: 16 GT/s lanes: 16 ports: active: HDMI-A-1
    empty: DP-1, DP-2, DP-3, Writeback-1 bus-ID: 08:00.0 chip-ID: 1002:73ef
  Display: x11 server: X.Org v: 21.1.14 with: Xwayland v: 24.1.4 driver: X: loaded: amdgpu
    unloaded: modesetting alternate: fbdev,vesa dri: radeonsi gpu: amdgpu display-ID: :0 screens: 1
  Screen-1: 0 s-res: 1920x1080 s-dpi: 96
  Monitor-1: HDMI-A-1 mapped: HDMI-A-0 model: LG (GoldStar) ULTRAGEAR res: 1920x1080 dpi: 93
    diag: 604mm (23.8")
  API: EGL v: 1.5 platforms: device: 0 drv: radeonsi device: 1 drv: swrast gbm: drv: kms_swrast
    surfaceless: drv: radeonsi x11: drv: radeonsi inactive: wayland
  API: OpenGL v: 4.6 compat-v: 4.5 vendor: amd mesa v: 24.2.7-arch1.1 glx-v: 1.4
    direct-render: yes renderer: AMD Radeon RX 6650 XT (radeonsi navi23 LLVM 18.1.8 DRM 3.59
    6.12.1-arch1-1) device-ID: 1002:73ef
Audio:
  Device-1: Advanced Micro Devices [AMD/ATI] Navi 21/23 HDMI/DP Audio driver: snd_hda_intel
    v: kernel pcie: speed: 16 GT/s lanes: 16 bus-ID: 08:00.1 chip-ID: 1002:ab28
  Device-2: Advanced Micro Devices [AMD] Starship/Matisse HD Audio vendor: ASUSTeK
    driver: snd_hda_intel v: kernel pcie: speed: 16 GT/s lanes: 16 bus-ID: 0a:00.4 chip-ID: 1022:1487
  API: ALSA v: k6.12.1-arch1-1 status: kernel-api
  Server-1: sndiod v: N/A status: off
  Server-2: PipeWire v: 1.2.6 status: active with: 1: pipewire-pulse status: active
    2: wireplumber status: active 3: pipewire-alsa type: plugin 4: pw-jack type: plugin
Network:
  Device-1: Realtek RTL8125 2.5GbE vendor: ASUSTeK driver: r8169 v: kernel pcie: speed: 5 GT/s
    lanes: 1 port: f000 bus-ID: 05:00.0 chip-ID: 10ec:8125
  IF: enp5s0 state: down mac: <filter>
  IF-ID-1: wlan0 state: up mac: <filter>

**Comment by claudiux** [comment]
It seems that your distro contains pieces of Cinnamon 6.4.

Workaround:

- Replace your `sound@cinnamon.org` applet with the `sound150@claudiux` applet: https://cinnamon-spices.linuxmint.com/applets/view/306
- Rename your `~/.local/share/cinnamon/applets/sound150@claudiux/6.4` folder to: `~/.local/share/cinnamon/applets/sound150@claudiux/6.2`
- Restart Cinnamon, or log-out then log-in.

**Comment by KingKusuo** [comment]
> It seems that your distro contains pieces of Cinnamon 6.4.
> 
> Workaround:
> 
>     * Replace your `sound@cinnamon.org` applet with the `sound150@claudiux` applet: https://cinnamon-spices.linuxmint.com/applets/view/306
> 
>     * Restart Cinnamon, or log-out then log-in.

already tried these steps before but that applet also does not seem to have any effect
it gives these erros on LookingGlass:
error t=2024-11-26T22:08:21Z 
[sound150@claudiux]: GSettings key maximum-volume not found in schema org.cinnamon.desktop.sound
[sound150@claudiux]: Failed to evaluate 'main' function on applet: sound150@claudiux/57
error t=2024-11-26T22:08:21Z 
[sound150@claudiux]: Applet sound150@claudiux: Could not create applet object.
[sound150@claudiux]: Error importing applet.js from sound150@claudiux

**Comment by claudiux** [comment]
You can't use the default sound applet. To control media keys, open the sound150 applet settings, go onto the Shortcuts tab, check the "Redefine Multimedia Keyboard Shortcuts" box and click on "Use the same shortcuts as those defined by Cinnamon".

**Comment by claudiux** [comment]
I'm installing the EndeavourOS in a VM to test it.

**Comment by KingKusuo** [comment]
> You can't use the default sound applet. To control media keys, open the sound150 applet settings, go onto the Shortcuts tab, check the "Redefine Multimedia Keyboard Shortcuts" box and click on the "Use the same shortcuts as those defined by Cinnamon" button.

I'm sorry for the confusion. With the sound150 applet i can indeed control volume and media with my keybinds, what i meant was that some keybinds like (Ctrl + Shift + T) for terminal, or (Super + E) for nemo file explorer are still not working, which is a shame

**Comment by username227** [comment]
Having the same issue. using the workaround applet, but seems quirky; will hope for fix soon.

**Comment by slak44** [comment]
I have this exact issue, for anyone else on arch you can downgrade these packages to fix the issue until the arch cinnamon package gets updated/fixed:
```
warning: downgrading package muffin (6.4.0-1 => 6.2.0-2)
warning: downgrading package cjs (6.4.0-1 => 6.2.0-1)
warning: downgrading package cinnamon-translations (6.4.0-1 => 6.2.2-1)
warning: downgrading package cinnamon-screensaver (6.4.0-1 => 6.2.1-1)
warning: downgrading package xapp (2.8.6-1 => 2.8.5-1)
warning: downgrading package cinnamon-control-center (6.4.0-1 => 6.2.0-1)
warning: downgrading package cinnamon-desktop (6.4.0-1 => 6.2.0-1)
warning: downgrading package cinnamon-menus (6.4.0-1 => 6.2.0-1)
```

**Comment by clefebvre** [comment]
Don't upgrade any components until Cinnamon 6.4 is fully available.

**Comment by Totallynotmwa** [comment]
Is this why my volume control keys f3/f2 + fn is broken

**Comment by Totallynotmwa** [comment]
> Don't upgrade any components until Cinnamon 6.4 is fully available.

Wayland? 👀

**Comment by n3rdw1z4rd** [comment]
> I have this exact issue, for anyone else on arch you can downgrade these packages to fix the issue until the arch cinnamon package gets updated/fixed:
> 
> ```
> warning: downgrading package muffin (6.4.0-1 => 6.2.0-2)
> warning: downgrading package cjs (6.4.0-1 => 6.2.0-1)
> warning: downgrading package cinnamon-translations (6.4.0-1 => 6.2.2-1)
> warning: downgrading package cinnamon-screensaver (6.4.0-1 => 6.2.1-1)
> warning: downgrading package xapp (2.8.6-1 => 2.8.5-1)
> warning: downgrading package cinnamon-control-center (6.4.0-1 => 6.2.0-1)
> warning: downgrading package cinnamon-desktop (6.4.0-1 => 6.2.0-1)
> warning: downgrading package cinnamon-menus (6.4.0-1 => 6.2.0-1)
> ```

Hi @slak44 - i have never downgraded a package in arch before, can you provide the command you used?

thank you :)

**Comment by n3rdw1z4rd** [comment]
> > Hi @slak44 - i have never downgraded a package in arch before, can you provide the command you used?
> > thank you :)
> 
> First go to `/var/cache/pacman/pkg`, this is where pacman keeps old installed packages. The command I used is below, but you might have to use slightly different versions, depending on when you last updated your system.
> 
> ```
> cd /var/cache/pacman/pkg
> sudo pacman -U muffin-6.2.0-2-x86_64.pkg.tar.zst cjs-6.2.0-1-x86_64.pkg.tar.zst cinnamon-translations-6.2.2-1-any.pkg.tar.zst cinnamon-screensaver-6.2.1-1-x86_64.pkg.tar.zst xapp-2.8.5-1-x86_64.pkg.tar.zst cinnamon-control-center-6.2.0-1-x86_64.pkg.tar.zst cinnamon-desktop-6.2.0-1-x86_64.pkg.tar.zst cinnamon-menus-6.2.0-1-x86_64.pkg.tar.zst
> ```
> 
> Obligatory wiki link: https://wiki.archlinux.org/title/Downgrading_packages

Thank you @slak44 - unfortunately, this is a fresh arch install on a new machine - i'll have to manually download those packages it seems.

**Comment by archiebug** [comment]
Hi-
How would us arch users know  when 6.4 is fully available?  Parts of 6.4 have made it to the repos and it is available for pkg upgrade.

<pre><b>Package (8)                  </b>  <b>Old Version</b>  <b>New Version</b>  <b>Net Change</b>  <b>Download Size</b>

extra/cinnamon-control-center  6.2.0-1      6.4.0-1        0.00 MiB               
extra/cinnamon-desktop         6.2.0-1      6.4.0-1        0.00 MiB               
extra/cinnamon-menus           6.2.0-1      6.4.0-1        0.00 MiB               
extra/cinnamon-screensaver     6.2.1-1      6.4.0-1        0.00 MiB               
extra/cinnamon-translations    6.2.2-1      6.4.0-1        0.00 MiB       3.68 MiB
extra/cjs                      6.2.0-1      6.4.0-1        0.00 MiB               
extra/muffin                   6.2.0-2      6.4.0-1        0.02 MiB               
extra/xapp                     2.8.5-1      2.8.6-1        0.00 MiB               

</pre>

**Comment by username227** [comment]
> Hi- How would us arch users know when 6.4 is fully available? Parts of 6.4 have made it to the repos and it is available for pkg upgrade.
> 
> Package (8)                    Old Version  New Version  Net Change  Download Size
> 
> extra/cinnamon-control-center  6.2.0-1      6.4.0-1        0.00 MiB               
> extra/cinnamon-desktop         6.2.0-1      6.4.0-1        0.00 MiB               
> extra/cinnamon-menus           6.2.0-1      6.4.0-1        0.00 MiB               
> extra/cinnamon-screensaver     6.2.1-1      6.4.0-1        0.00 MiB               
> extra/cinnamon-translations    6.2.2-1      6.4.0-1        0.00 MiB       3.68 MiB
> extra/cjs                      6.2.0-1      6.4.0-1        0.00 MiB               
> extra/muffin                   6.2.0-2      6.4.0-1        0.02 MiB               
> extra/xapp                     2.8.5-1      2.8.6-1        0.00 MiB

Check  here: https://archlinux.org/packages/?q=cinnamon
See all of the packages in red that have been marked out of date? when the rest of them are updated to 6.4 and are no longer out of date, then it should be safe to upgrade. I was told on the arch IRC this morning that someone was going to open a bug report there, but I haven't found it. If I do, I will update this with a link.

**Comment by username227** [comment]
as of about an hour ago, it is now necessary to also tell pacman to ignore the following package upgrades:

cinnamon-session
cinnamon-settings-daemon

They insist on the IRC that the issues with cinnamon have been noticed already and are "slowly being fixed." I will continue to keep an eye on and update here if people want.

**Comment by Reezlaw** [comment]
> They insist on the IRC that the issues with cinnamon have been noticed already and are "slowly being fixed." I will continue to keep an eye on and update here if people want.

Thank you for your service

**Comment by ilikenwf** [comment]
Seems the Arch cinnamon package builder is moving slowly...which is odd since usually it's bleeding edge...very sad.

**Comment by username227** [comment]
> Seems the Arch cinnamon package builder is moving slowly...which is odd since usually it's bleeding edge...very sad.

I think that somebody really messed up on pushing updates to certain cinnamon packages before the entire 6.4 was ready. 

But I also think that there's a real possibility that their hands may be tied until the rest of the DE is ready (note the 'ciinnamon' package, and several others, are still listed at 6.2.9. This, I believe, is because updates for those were not pushed yet by the Mint people, which means that there's no way to update them until they become available. The only other possibility is to downgrade the repos to the prior version. But this would require significant manual intervention anyway, and is probably not feasible.

I had put in a bug report on Arch's cinnamon package last month about an unrelated Wayland issue I was experiencing with Arch, and I believe that they may not have a permanent maintainer for this at the moment (but I am not 100% sure), which could be part of the issue.

**Comment by Reezlaw** [comment]
> Downgrade **cinnamon-desktop** fixes the problem.

For everything to work normally I had to downgrade all of these:

muffin
cjs
cinnamon-translations
cinnamon-screensaver
xapp
cinnamon-control-center
cinnamon-desktop
cinnamon-menus
cinnamon-session
cinnamon-settings-daemon

**Comment by clefebvre** [comment]
> > Downgrade **cinnamon-desktop** fixes the problem.
> 
> For everything to work normally I had to downgrade all of these:
> 
> muffin cjs cinnamon-translations cinnamon-screensaver xapp cinnamon-control-center cinnamon-desktop cinnamon-menus cinnamon-session cinnamon-settings-daemon

Xapp is a separate project. Nemo and nemo-extensions should match your cinnamon version though.

**Comment by clefebvre** [comment]
All the Cinnamon components are now tagged at 6.4 here on github. I'm not sure how fast or automated Arch uploads are (they look way too fast and/or way too automated to me to be honest), but once all your updates are 6.4 you should have a functional desktop.

**Comment by clefebvre** [comment]
We still have a few features we want to squeeze in 6.4... this doesn't usually happen but we tagged 6.4 in a rush here to fix this issue.

**Comment by clefebvre** [comment]
> Hi- How would us arch users know when 6.4 is fully available? Parts of 6.4 have made it to the repos and it is available for pkg upgrade.

That's a very good question, but it's a question I can't answer for Arch.

In Mint the main goal is stability, so users never need to know if something is fully available or not. That's something the maintainers take care of. If something comes as an update it's always ready, stable, tested.

In Arch I think one of the main goals is to give users access to the very latest. It looks to me like you got updates just because they were tagged in git, without any testing.

To give you an idea of how bleeding-edge you are compare to us:

- It takes a couple of days for all components to get tagged on master, as they become feature-ready. Maybe a week. This just finished now.
- New strings are then sent for translators to translate. That takes another week, roughly.
- New features and changes introduce new bugs. This release introduces new clutter dialogs (theme breakages), night light, power modes etc.. we're definitely going to find bugs. We always do. From a git point of view, we continue to fix bugs on master and tag point releases as fixes happen. From a distribution point of view, we organize an entire 2 weeks of BETA testing for Linux Mint which follows the release of Cinnamon.

Our two biggest sources of bug reports following a Cinnamon release are the Mint BETA testers and Arch users, because they're exposed to regressions before anyone else.

This makes Arch extremely valuable to us, and I'm sure to many developers out there, but it has a cost on its user base. You guys are on the edge :)

Here are a few ideas to improve the situation for Arch Cinnamon users. This is for the maintainers. I'm not sure if they're feasible, it depends on how Cinnamon is maintained/uploaded in Arch:

- Make sure you never upload odd release numbers (we use them very rarely, 6.3, 6.5 for instance).
- Don't upload any Cinnamon components (cjs, cmenus, cdesktop, csr, csm, csd, ccc, muffin, nemo, nemo-ext, cinnamon, cinnamon-l10n) until they're ALL tagged for the new major release, in this case 6.4.x.
- Delay the upload by a week or by the first point release on cinnamon-l10n (6.4.1 in this occasion).
- Don't be shy. We're on Matrix on the Cinnamon, Xapp, Mint-development channels. We're glad you love Cinnamon, we're really glad you use it early, but hard breakages like this one.. you shouldn't be exposed to that. The more we talk with Arch maintainers the better... even for newly developed features (do you still use power-profiles-daemon for instance? old or new dbus interface? etc..).

**Comment by username227** [comment]
@clefebvre thank you so much for your reply. I'm sure I speak for everyone when I express my appreciation for your Arch support.

I've been using Cinnamon with Arch for several years already, and this has NEVER happened before to my knowledge. Believe it or not, while things do break occasionally, Arch is more solid than people generally give credit for. These updates should have been sent first to the testing repos for a week or so prior to them rolling out the updates to the regular repos, or even better, to the staging repos where the updates would have sat until all the pieces were complete. Then it would have been caught prior to a disastrous roll-out. Honestly I have no idea why this wasn't done, somebody there must have dropped the ball, or perhaps isn't as familiar with the intracacies of Cinnamon as prior maintainer(s). 

In any case, we really appreciate you rushing to tag the remaining pieces to fix the issue. As of this writing, Arch has not updated the two remaining packages yet, but they have been marked as "out-of-date" so hopefully soon.

**Comment by archiebug** [comment]
> > Hi- How would us arch users know when 6.4 is fully available? Parts of 6.4 have made it to the repos and it is available for pkg upgrade.
> 
> That's a very good question, but it's a question I can't answer for Arch.
> 
> In Mint the main goal is stability, so users never need to know if something is fully available or not. That's something the maintainers take care of. If something comes as an update it's always ready, stable, tested.
> 
> In Arch I think one of the main goals is to give users access to the very latest. It looks to me like you got updates just because they were tagged in git, without any testing.
> 
> To give you an idea of how bleeding-edge you are compared to us:
> 
> * It takes a couple of days for all components to get tagged on master, as they become feature-ready. Maybe a week. This just finished now.
> * New strings are then sent for translators to translate. That takes another week, roughly.
> * New features and changes introduce new bugs. This release introduces new clutter dialogs (theme breakages), night light, power modes etc.. we're definitely going to find bugs. We always do. From a git point of view, we continue to fix bugs on master and tag point releases as fixes happen. From a distribution point of view, we organize an entire 2 weeks of BETA testing for Linux Mint which follows the release of Cinnamon.
> 
> Mint BETA testers will get access to this in more than a week, maybe 2. Stable users will get it in Mint 22.2, late December or in 2025.
> 
> Our two biggest sources of bug reports following a Cinnamon release are the Mint BETA testers and Arch users, because they're exposed to regressions before anyone else.
> 
> This makes Arch extremely valuable to us, and I'm sure to many developers out there, but it has a cost on its user base. You guys are on the edge :)
> 
> Here are a few ideas to improve the situation for Arch Cinnamon users. This is for the maintainers. I'm not sure if they're feasible, it depends on how Cinnamon is maintained/uploaded in Arch:
> 
> * Make sure you never upload odd release numbers (we use them very rarely, 6.3, 6.5 for instance).
> * Don't upload any Cinnamon components (cjs, cmenus, cdesktop, csr, csm, csd, ccc, muffin, nemo, nemo-ext, cinnamon, cinnamon-l10n) until they're ALL tagged for the new major release, in this case 6.4.x.
> * Delay the upload by a week or by the first point release on cinnamon-l10n (6.4.1 in this occasion).
> * Don't be shy. We're on Matrix on the Cinnamon, Xapp, Mint-development channels. We're glad you love Cinnamon, we're really glad you use it early, but hard breakages like this one.. you shouldn't be exposed to that. The more we talk with Arch maintainers the better... even for newly developed features (do you still use power-profiles-daemon for instance? old or new dbus interface? etc..).

Thank you for the detailed reply.  I started out as a Mint user and dove into the Archlinux world later on.  I've always gravitated back to the Cinnamon DE as it is simple to use and has features that other DEs do not have.  If I get stuck on any implementations, I just spin up a LM 22 VM and see how things are put together and usually works out fine.

As @username227 mentioned, in the arch repos, only the [cinnamon](https://archlinux.org/packages/extra/x86_64/cinnamon/) and [xdg-desktop-portal-xapp](https://archlinux.org/packages/extra/x86_64/xdg-desktop-portal-xapp/) are left waiting for upgrades.

I appreciate the help.

*cheers*

**Comment by username227** [comment]
OK anybody on Arch following this, this issue appears to have been fixed now. You should comment out any ignored packages in /etc/pacman.conf and do a "sudo pacman -Syu" to update. But you might want to hold off.

Please note a few things that I have noticed:

1) Cinnamon loads very slow. It takes a good 30-45 seconds for it to start. 
2) The sound applet does seem to work.
3) When I close my laptop lid and reopen, cinnamon freezes. It does not seem to be a screensaver-related issue, but it obviously is not sustainable.
4) the xdg-desktop-portal-xapp has not been updated yet. I have built an updated version and installed it manually, but it did not solve these issues.

I am not sure if these are related to downstream arch packaging issues which still need fixing or if they are true bugs of 6.4 that warrant separate bug reports. Perhaps @clefebvre can shed some light on this, and I can open up some add'l bug reports if necessary.

**Comment by username227** [comment]
Update: the freeze in Cinnamon seems to happen even when I tell Cinnamon to do nothing when closing the lid. However, the mouse still works, and it seems to be a "lag" rather than a freeze. If I'm patient enough, then it catches up. I'd bet this is related to the lag in Cinnamon starting up. But at least this means that you don't have to restart after closing the lid.

**Comment by archiebug** [comment]
I did the update and it looks to be running okay for me. :)

**Comment by username227** [comment]
> I did the update and it looks to be running okay for me. :)

Interesting. After your update, I restored a timeshift backup to revert to a time before this whole problem started, and allowed the update again, with the same results. I tried without the nvidia card also, with the same lag and screen-close issue I described above. The more time that I give it, the more I am starting to believe that these issues may be genuine cinnamon bugs. I am inclined to create bug reports for these issues unless @clefebvre or another developer says that I shouldn't.

**Comment by claudiux** [comment]
The package update on EndeavourOS corrects the problem.

**Comment by archiebug** [comment]
> > I did the update and it looks to be running okay for me. :)
> 
> Interesting. After your update, I restored a timeshift backup to revert to a time before this whole problem started, and allowed the update again, with the same results. I tried without the nvidia card also, with the same lag and screen-close issue I described above. The more time that I give it, the more I am starting to believe that these issues may be genuine cinnamon bugs. I am inclined to create bug reports for these issues unless @clefebvre or another developer says that I shouldn't.

I seem to have a 5-10 second delay (blank screen) after logging in from the display manager.  This wasn't present in 6.2.  Can't seem to find what is causing it.
