### ISSUE TITLE
Sound is not working, brand new MSI laptop.  Works perfectly in Windows.  

### ISSUE THREAD

**Issue by chr0meice2** [linuxmint/cinnamon#12528]
### Distribution

 Distro: Linux Mint 22 Wilma base: Ubuntu 24.04 noble

### Package version

 Cinnamon v: 6.2.9 tk: GTK v: 3.24.41 wm: Muffin dm: LightDM

### Graphics hardware in use

  Device-1: NVIDIA AD107M [GeForce RTX 4060 Max-Q / Mobile] vendor: Micro-Star MSI driver: N/A     arch: Lovelace pcie: speed: 16 GT/s lanes: 8 bus-ID: 01:00.0 chip-ID: 10de:28a0   Device-2: AMD Phoenix3 vendor: Micro-Star MSI driver: amdgpu v: kernel arch: RDNA-3 pcie:

### Frequency

Always

### Bug description

Brand new MSI laptop.... came with Windows... Sound worked perfectly.  Installed mint.  Sound doesn't work in any application (firefox, or test sound in the sound manager)

I already asked about this on Discord but no solution.  HEre are the system specs below.  The sound should work; we already know it works fine in Windows...

System:
  Kernel: 6.8.0-49-generic arch: x86_64 bits: 64 compiler: gcc v: 13.2.0
  Desktop: Cinnamon v: 6.2.9 tk: GTK v: 3.24.41 wm: Muffin dm: LightDM
    Distro: Linux Mint 22 Wilma base: Ubuntu 24.04 noble
Machine:
  Type: Laptop System: Micro-Star product: Thin A15 AI B8VF v: REV:1.0 serial: <superuser required>
    Chassis: type: 10 serial: <superuser required>
  Mobo: Micro-Star model: MS-16RK v: REV:1.0 serial: <superuser required> part-nu: 16RK.3
    UEFI: American Megatrends LLC. v: E16RKAMS.30A date: 08/05/2024
Battery:
  ID-1: BAT1 charge: 45.3 Wh (89.2%) condition: 50.8/51.3 Wh (98.9%) volts: 12.7 min: 11.4
    model: MSI BIF0_9 serial: N/A status: charging
CPU:
  Info: 8-core model: AMD Ryzen 9 8945HS w/ Radeon 780M Graphics bits: 64 type: MT MCP arch: Zen 4
    rev: 2 cache: L1: 512 KiB L2: 8 MiB L3: 16 MiB
  Speed (MHz): avg: 1921 high: 5057 min/max: 400/5583:5263:5423:6228:5743:5903:6067 cores:
    1: 2119 2: 2685 3: 2008 4: 400 5: 2035 6: 5057 7: 400 8: 400 9: 3234 10: 400 11: 400 12: 1995
    13: 2127 14: 5042 15: 400 16: 2034 bogomips: 127763
  Flags: avx avx2 ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm
Graphics:
  Device-1: NVIDIA AD107M [GeForce RTX 4060 Max-Q / Mobile] vendor: Micro-Star MSI driver: N/A
    arch: Lovelace pcie: speed: 16 GT/s lanes: 8 bus-ID: 01:00.0 chip-ID: 10de:28a0
  Device-2: AMD Phoenix3 vendor: Micro-Star MSI driver: amdgpu v: kernel arch: RDNA-3 pcie:
    speed: 16 GT/s lanes: 16 ports: active: eDP-1 empty: DP-1, DP-2, DP-3, DP-4, DP-5, DP-6, DP-7,
    DP-8, Writeback-1 bus-ID: 05:00.0 chip-ID: 1002:1900 temp: 46.0 C
  Device-3: Bison HD Webcam driver: uvcvideo type: USB rev: 2.0 speed: 480 Mb/s lanes: 1
    bus-ID: 3-1:2 chip-ID: 5986:211b
  Display: x11 server: X.Org v: 21.1.11 with: Xwayland v: 23.2.6 driver: X: loaded: amdgpu
    unloaded: fbdev,modesetting,vesa dri: radeonsi gpu: amdgpu display-ID: :0 screens: 1
  Screen-1: 0 s-res: 1920x1080 s-dpi: 96
  Monitor-1: eDP-1 mapped: eDP model: ChiMei InnoLux 0x1521 res: 1920x1080 dpi: 142
    diag: 394mm (15.5")
  API: EGL v: 1.5 platforms: device: 0 drv: radeonsi device: 1 drv: swrast surfaceless:
    drv: radeonsi x11: drv: radeonsi inactive: gbm,wayland
  API: OpenGL v: 4.6 compat-v: 4.5 vendor: amd mesa v: 24.0.9-0ubuntu0.2 glx-v: 1.4
    direct-render: yes renderer: AMD Radeon Graphics (radeonsi gfx1103_r1 LLVM 17.0.6 DRM 3.57
    6.8.0-49-generic) device-ID: 1002:1900
Audio:
  Device-1: NVIDIA vendor: Micro-Star MSI driver: snd_hda_intel v: kernel pcie: speed: Unknown
    lanes: 63 bus-ID: 01:00.1 chip-ID: 10de:22be
  Device-2: AMD Rembrandt Radeon High Definition Audio driver: snd_hda_intel v: kernel pcie:
    speed: 16 GT/s lanes: 16 bus-ID: 05:00.1 chip-ID: 1002:1640
  Device-3: AMD ACP/ACP3X/ACP6x Audio Coprocessor vendor: Micro-Star MSI driver: snd_pci_ps
    v: kernel pcie: speed: 16 GT/s lanes: 16 bus-ID: 05:00.5 chip-ID: 1022:15e2
  Device-4: AMD Family 17h/19h HD Audio vendor: Micro-Star MSI driver: snd_hda_intel v: kernel
    pcie: speed: 16 GT/s lanes: 16 bus-ID: 05:00.6 chip-ID: 1022:15e3
  API: ALSA v: k6.8.0-49-generic status: kernel-api
  Server-1: PipeWire v: 1.0.5 status: active with: 1: pipewire-pulse status: active
    2: wireplumber status: active 3: pipewire-alsa type: plugin
Network:
  Device-1: Realtek RTL8111/8168/8211/8411 PCI Express Gigabit Ethernet vendor: Micro-Star MSI
    RTL8111/8168/8411 driver: r8169 v: kernel pcie: speed: 2.5 GT/s lanes: 1 port: e000
    bus-ID: 03:00.0 chip-ID: 10ec:8168
  IF: eno1 state: down mac: <filter>
  Device-2: MEDIATEK MT7922 802.11ax PCI Express Wireless Network Adapter driver: mt7921e
    v: kernel pcie: speed: 5 GT/s lanes: 1 bus-ID: 04:00.0 chip-ID: 14c3:0616
  IF: wlp4s0 state: up mac: <filter>
  IF-ID-1: vmnet1 state: unknown speed: N/A duplex: N/A mac: <filter>
  IF-ID-2: vmnet8 state: unknown speed: N/A duplex: N/A mac: <filter>
Bluetooth:
  Device-1: MediaTek Wireless_Device driver: btusb v: 0.8 type: USB rev: 2.1 speed: 480 Mb/s
    lanes: 1 bus-ID: 1-3:2 chip-ID: 0e8d:0616
  Report: hciconfig ID: hci0 rfk-id: 0 state: up address: <filter> bt-v: 5.3 lmp-v: 12
    sub-v: 2306
Drives:
  Local Storage: total: 953.87 GiB used: 63.24 GiB (6.6%)
  ID-1: /dev/nvme0n1 vendor: Samsung model: MZVL41T0HBLB-00BTW size: 953.87 GiB speed: 63.2 Gb/s
    lanes: 4 serial: <filter> temp: 34.9 C
Partition:
  ID-1: / size: 913.75 GiB used: 63.05 GiB (6.9%) fs: ext4 dev: /dev/dm-1 mapped: vgmint-root
  ID-2: /boot size: 1.61 GiB used: 194.1 MiB (11.8%) fs: ext4 dev: /dev/nvme0n1p2
  ID-3: /boot/efi size: 511 MiB used: 6.1 MiB (1.2%) fs: vfat dev: /dev/nvme0n1p1
Swap:
  ID-1: swap-1 type: partition size: 1.91 GiB used: 768 KiB (0.0%) priority: -2 dev: /dev/dm-2
    mapped: vgmint-swap_1
Sensors:
  System Temperatures: cpu: 52.9 C mobo: 42.0 C gpu: amdgpu temp: 48.0 C
  Fan Speeds (rpm): N/A
Repos:
  Packages: pm: dpkg pkgs: 1988
  No active apt repos in: /etc/apt/sources.list
  Active apt repos in: /etc/apt/sources.list.d/official-package-repositories.list
    1: deb https: //mirrors.seas.harvard.edu/linuxmint-packages wilma main upstream import backport
    2: deb http: //mirror.math.princeton.edu/pub/ubuntu noble main restricted universe multiverse
    3: deb http: //mirror.math.princeton.edu/pub/ubuntu noble-updates main restricted universe multiverse
    4: deb http: //mirror.math.princeton.edu/pub/ubuntu noble-backports main restricted universe multiverse
    5: deb http: //security.ubuntu.com/ubuntu/ noble-security main restricted universe multiverse
Info:
  Memory: total: 16 GiB note: est. available: 14.88 GiB used: 3.41 GiB (22.9%)
  Processes: 398 Power: uptime: 15m wakeups: 0 Init: systemd v: 255 target: graphical (5)
    default: graphical
  Compilers: gcc: 13.2.0 Client: Unknown python3.12 client inxi: 3.3.34

### Steps to reproduce

open firefox.  watch something on youtube with sound.  no sound comes out

open sound manager, do a "test" sound.  nothing comes out.  volume is on and up all the way

### Expected behavior

sound working

### Additional information

n/a

**Comment by leigh123linux** [comment]
Maybe try a newer kernel.
Your issue doesn't belong here. please file it at https://github.com/linuxmint/linuxmint/issues
