### ISSUE TITLE
GPaste Reloaded Applet doesn't working in Cinnamon 6.4.0

### ISSUE THREAD

**Issue by alb-soul** [linuxmint/cinnamon#12532]
### Distribution

Arch Linux

### Package version

6.4.0

### Graphics hardware in use

Intel Corporation TigerLake-LP GT2 [Iris Xe Graphics]

### Frequency

Always

### Bug description

Gpaste applet by feuerfuchs stops working in cinnamon 6.4.0, the applet can be installed but when click, show empty and small window (circle)
![gpaste applet](https://github.com/user-attachments/assets/5297d500-1444-4639-a5b2-65cbe6383ae2)

### Steps to reproduce

Using Arch Linux with Cinnamon DE, cinnamon version is 6.4.0. Install "Gpaste Reloaded" applet by for panel, but it's not working, previous cinnamon version works well. Even open/click configuration of the applet show nothing.
![Screenshot from 2024-11-29 13-05-26](https://github.com/user-attachments/assets/8fff35f7-8a02-4250-840b-391a78ae36d7)

### Expected behavior

Gpaste reloaded installed and works well, so I can easily fetch previous clipboard history.

**Comment by JosephMcc** [comment]
You should notify the author here: https://github.com/linuxmint/cinnamon-spices-applets/issues
There were changes in modal dialogs in Cinnamon 6.4 which are effecting this applet.

**Comment by alb-soul** [comment]
> You should notify the author here: https://github.com/linuxmint/cinnamon-spices-applets/issues There were changes in modal dialogs in Cinnamon 6.4 which are effecting this applet.

Okay, thanks

**Comment by claudiux** [comment]
ping @Feuerfuchs

**Comment by fredcw** [comment]
@Feuerfuchs hasn't been active on github for 5 years.

@JosephMcc I guess it's to do with the unusual way ModalDialog is inherited:

from [here](https://github.com/linuxmint/cinnamon-spices-applets/blob/bb34928d5bbe9e63fc49a2db01b45ba3e80b5034/gpaste-reloaded%40feuerfuchs.eu/files/gpaste-reloaded%40feuerfuchs.eu/GPasteNewItemDialog.js#L17-L25):

```
function GPasteNewItemDialog(callback) {
    this._init(callback);
}

GPasteNewItemDialog.prototype = {
    __proto__: ModalDialog.ModalDialog.prototype,

    _init: function(callback) {
        ModalDialog.ModalDialog.prototype._init.call(this, { styleClass: 'gpaste__new-item-dialog' });
```

This problem seems to affect a few other applets as well which inherit ModalDialog in a similar way. e.g. netusagemonitor@pdcurtis, cinnamon-timer@jake1164, SettingsPlus@lusito.info, and a few others.

What do you think would be the easiest way to fix the code in the example above?

**Comment by JosephMcc** [comment]
@fredcw Yes, that would be the new way to do it. You can also use
`let content = new Dialog.MessageDialogContent();
content.title = "Title";
content.description = "Description";
 this.contentLayout.add_child(content);`
to get a nice layout.

**Comment by gfreeau** [comment]
I'm the author of https://github.com/linuxmint/cinnamon-spices-applets/tree/master/pomodoro%40gregfreeman.org and this applet is also affected by the changes to ModalDialog. It won't run on 6.4.0.

I haven't found a solution in a backwards compatible way to support both existing and the latest cinnamon versions on one codebase.

In my applet I extend ModalDialog and also rely on signals for the applet to interact with dialogs (prior ModalDialog called `Signals.addSignalMethods(ModalDialog.prototype);`). The new ModalDialog https://github.com/linuxmint/cinnamon/blob/master/js/ui/modalDialog.js doesn't call this for you.

Can someone confirm that for the new ModalDialog if I want to use signals and emit events that I have to do something around

```js
GObject.registerClass({
        Signals: {
            'switch-off-pomodoro': {},
            'start-new-pomodoro': {},
            'hide': {}
        }
 }, class PomodoroDialog extends ModalDialog.ModalDialog {
        _init() {
            super._init();
            // ...... rest of implementation
```       

And then that doesn't solve my goal of one applet file supporting the different cinnamon versions.

**Comment by gfreeau** [comment]
@JosephMcc Can this issue be re-opened?

**Comment by fredcw** [comment]
@gfreeau Why not just add a new version for 6.4, seems like the easiest way to do it. Keeping one version backward compatible will likely get increasingly difficult with each new cinnamon version, may as well start fresh?

**Comment by gfreeau** [comment]
@fredcw I think you're right that's the best way if it is intended to be a backwards compatibility breaking change, can any devs confirm?

**Comment by JosephMcc** [comment]
@gfreeau It is breaking change for backward compatibility. That's a big part of why we have the versioned folders. Barring that, it might be possible to take the old modal dialog code, rename it, and use it internally in your applet, if you really want to try to avoid versioning.

**Comment by gfreeau** [comment]
Thanks guys that's enough for me to go on.

**Comment by alb-soul** [comment]
Thanks, guys! @fredcw fixed it : https://github.com/fredcw/Notes/issues/12#issue-2707377713
