### ISSUE TITLE
New Clutter dialogs aren't windows, they dim the desktop, can't be moved and are modal

### ISSUE THREAD

**Issue by Secret-chest** [linuxmint/cinnamon#12539]
This is a regression because it makes them harder to use and inconsistent

**Comment by JosephMcc** [comment]
This is going to be the way forward. These dialogs only popup when a specific user action is needed and are easily dismissed. That reduces the need to be able to move them around.

I'll also say, that hijacking other peoples issues to complain, or say "I'm moving to Mate" aren't helpful or useful to anyone.
