### ISSUE TITLE
New design bugs

### ISSUE THREAD

**Issue by tutralex** [linuxmint/cinnamon#12534]
### Distribution

Arch Linux

### Package version

kernel: 6.12.1 / cinnamon: 6.4.0

### Graphics hardware in use

AMD Radeon RX 6900 XT

### Frequency

Always

### Bug description

The dialog boxes for logging off or shutting down the computer with the new design do not have keyboard input focus. The buttons can only be pressed with the mouse. The volume pop-up window (multimedia buttons) first pops up in the upper left corner, and then moves to the center, it looks very ugly.

### Steps to reproduce

Update to version 6.4.0

### Expected behavior

Selecting the action from the keyboard. Displaying windows where they should be, not in the upper left corner.

### Additional information

P.S. I don't understand why you are trying to look like a gnome? The new design is not functional, has errors, and it also looks ugly. I am very sad to see where my beloved DE is heading...

**Comment by Alstruit** [comment]
See #12364 for context.

**Comment by leigh123linux** [comment]
Don't expect 6.4.0 to be a finished product, it's still in development and wont be finished till sometime late December.

**Comment by davidbepo** [comment]
can confirm, to add insult to injury, translations are missing and it doesnt respect theming

**Comment by JosephMcc** [comment]
It respects theming just fine. It's new and themes need to add support. Those that don't will just get the default theming until they do.

**Comment by clefebvre** [comment]
Translations always come in x.y.1, about a week later.
