### ISSUE TITLE
new 6.4 sound popup lacks %

### ISSUE THREAD

**Issue by davidbepo** [linuxmint/cinnamon#12535]
### Distribution

Manjaro

### Package version

Cinnamon 6.4.0

### Frequency

Always

### Bug description

the new clutter volume popup doesnt show %

### Steps to reproduce

change the volume

### Expected behavior

volume shows % as before

**Comment by clefebvre** [comment]
This is by design. It was removed to look cleaner and because the value wasn't meaningful.

The use case to set it to a particular value was discussed. We thought a keyboard shortcut would be much better at achieving that.

**Comment by davidbepo** [comment]
well this is very disruptive, specially with amplification enabled
is it possible to at least give an option to show it?

**Comment by clefebvre** [comment]
Sorry @davidbepo, this was discussed as well. You've a quick way to see the value in the applet tooltip. To set it to a precise value with just one press I'd recommend setting up a keyboard shortcut for it.

**Comment by Secret-chest** [comment]
Even televisions have %. Why not have an option?

**Comment by Secret-chest** [comment]
I'm switching to MATE after these redesigns, the animation time setting removal, because MATE is more modular and allows me to replace the parts I don't like.
