### ISSUE TITLE
focus tweak to facilitate drag and drop between 2 windows

### ISSUE THREAD

**Issue by geoffmen** [linuxmint/Cinnamon#1254]
When you want to drag and drop a file from a maximized browser window to a smaller application window in the foreground, you have to drag the file to the application's button in the window list, wait for it to popup and move the cursor to the application's window. Or you can first activate the "Always on top" mode for the application and then drag the file from Nemo directly. What I'd like to do is if I click a file, and don't release the button, in Nemo, to drag the file to another window, Nemo doesn't move to the front, hiding my second application's window. I think the simplest way to design this is to make Nemo wait for the mouse-click release before taking the focus, instead of taking the focus as soon as the mouse button is pushed down.

**Comment by JosephMcc** [comment]
Thank you for your suggestion. See https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html for information on how we handle feature requests.
