### ISSUE TITLE
The sound popup appears cut off on the main monitor

### ISSUE THREAD

**Issue by SmillerMP** [linuxmint/cinnamon#12540]
### Distribution

Arch 

### Package version

6.4.0

### Graphics hardware in use

 AMD Radeon Vega 11 Graphics [Integrated]

### Frequency

Always

### Bug description

When I adjust the volume the popup appears cut off at the bottom of the monitor, the same when I switch between work areas. This only happens on my main monitor, it does not happen on the secondary one.

![bug-cinnamon1](https://github.com/user-attachments/assets/49772d90-5f95-45ea-9fdc-3d48d833093c)

### Steps to reproduce

It appears when starting the system

### Expected behavior

On my second monitor this does not happen, the popup appears completely without any problem.

![bug-cinnamon2](https://github.com/user-attachments/assets/5d2fe9f6-5926-482e-a0b1-661b52ac63c1)

### Additional information

Both monitors are 1920x1080, main monitor 75hz, secondary monitor 60hz

**Comment by JosephMcc** [comment]
How are your monitors arranged?

**Comment by SmillerMP** [comment]
> How are your monitors arranged? And what Cinnamon theme are you using?

Hi, this is my monitor settings.

![imagen](https://github.com/user-attachments/assets/a285fa4e-bb33-4fa2-bb3d-ac72e07b66bb)

xrandr output

`$ xrandr
Screen 0: minimum 320 x 200, current 3840 x 1080, maximum 16384 x 16384
HDMI-A-0 connected primary 1920x1080+1920+0 (normal left inverted right x axis y axis) 544mm x 303mm
   1920x1080     60.00 +  74.97*   50.00    59.94
   1680x1050     59.88
   1280x1024     75.02    60.02
   1440x900      59.90
   1280x960      60.00
   1280x800      60.00
   1280x720      60.00    50.00    59.94
   1024x768      75.03    70.07    60.00
   832x624       74.55
   800x600       72.19    75.00    60.32    56.25
   720x576       50.00
   720x480       60.00    59.94
   640x480       75.00    72.81    66.67    60.00    59.94
   720x400       70.08
DVI-D-0 connected 1920x1080+0+0 (normal left inverted right x axis y axis) 527mm x 296mm
   1920x1080     60.00*+  50.00    59.94
   1680x1050     59.88
   1280x1024     75.02    60.02
   1440x900      59.90
   1280x960      60.00
   1280x800      60.00
   1280x720      60.00    50.00    59.94
   1024x768      75.03    70.07    60.00
   832x624       74.55
   800x600       72.19    75.00    60.32    56.25
   720x576       50.00
   720x480       60.00    59.94
   640x480       75.00    72.81    66.67    60.00    59.94
   720x400       70.08
DisplayPort-0 disconnected (normal left inverted right x axis y axis`


and my theme is dracula throughout
![imagen](https://github.com/user-attachments/assets/745ff328-0d5b-400d-92d1-3bac817e0ab9)


I have already tried to make some changes, in the themes and in the monitor configuration, and it is still the same, the popup always appears cut off in the HDMI-A-0

**Comment by JosephMcc** [comment]
Thank you! I'll try to set up an additional monitor and test later.

**Comment by JosephMcc** [comment]
I figured out how to reproduce this. I'll look at getting a fix done for it.

**Comment by JosephMcc** [comment]
PR'd a fix for this. It was actually a simpler one than I thought.

**Comment by SmillerMP** [comment]
> PR arreglaría esto. En realidad era más simple de lo que pensaba.

jsjsjs sometimes the hard part is finding the bugs, thank you very much
