### ISSUE TITLE
New clutter dialogs not working properly.

### ISSUE THREAD

**Issue by 5BNeumann** [linuxmint/cinnamon#12553]
### Distribution

EndeavourOS neo

### Package version

6.4

### Graphics hardware in use

Intel HD Graphics 520 @ 1.00 GHz [Integrated]

### Frequency

Always

### Bug description

When a dialog appears (such as shut down and force quit) I can't press "Enter" to confirm.
When the calendar/the start menu are opened, you can't use "Shift+PrtScr" to take a screenshot.

### Steps to reproduce

Try to shut down the computer and press "Enter" to confirm.
Open the calendar/start menu and press "Shift+PrtScr".

### Expected behavior

Validate with the default option, in bright red.
Allow to take a screenshot.

**Comment by clefebvre** [comment]
What's your exact version of Cinnamon?

**Comment by 5BNeumann** [comment]
I'm on 6.4.0.

**Comment by clefebvre** [comment]
Ok that makes sense, keyboard navigation was added in 6.4.1.

https://github.com/linuxmint/cinnamon/commit/e9ab16456ca161e934c67b9c06a6095e89c21923
