### ISSUE TITLE
Polkit refuses to launch "Enter Password" window for root authentication

### ISSUE THREAD

**Issue by sidambhire** [linuxmint/cinnamon#12568]
### Distribution

Arch Linux

### Package version

6.4.2

### Frequency

Always

### Bug description

Anything that requires root authentication doesn't work. No "Enter password" window pop-up are displayed. This is very much interfering with my usage of the system. Following things are impacted for example:
1. Mounting inbuilt devices in nemo.
2. Mounting partitions on gnome-disks.
3. Opening a folder as root in nemo.

### Steps to reproduce

1. Easiest way to reproduce is click on devices in nemo. 
2. Try to mount partition in gnome-disks.
3. Another way is to right click a folder in nemo and try to "open as root".

### Expected behavior

It should open pop-up window "Enter Password" for root to continue with the actions (mentioned above for example).

### Additional information

[Arch Linux Forum Post](https://bbs.archlinux.org/viewtopic.php?pid=2213792) has additional information provided by another user who could reproduce this bug.

**Comment by leigh123linux** [comment]
I have removed the bug tag as the issue doesn't reproduce.

**Comment by leigh123linux** [comment]
Cinnamon has it's own polkit dialog, you will need to disable/remove all others to stop them clashing.

**Comment by clefebvre** [comment]
Wait.. I'm not sure that's the polkit agent we're talking about here.

Does launching apps with pkexec work?

This sounds more like shellMountOperation, which afaik, was postponed until Cinnamon 6.6.

**Comment by clefebvre** [comment]
is csd-automount running?

**Comment by clefebvre** [comment]
Also, check for errors in ~/.xsession-errors, and in LG (right-click panel -> troubleshoot -> Looking Glass -> Log).

**Comment by clefebvre** [comment]
Could be related to https://github.com/linuxmint/mint22.1-beta/issues/18.

**Comment by clefebvre** [comment]
On a fresh login, check your process list to see what's running. I'd like to see if there's another agent started in the session.

**Comment by clefebvre** [comment]
On a fresh install of Arch+Cinnamon (cheating a bit.. using `archinstall` cough), I can't reproduce the issue.

![image](https://github.com/user-attachments/assets/fc2f1910-f499-4d95-80d9-a2e4a7edd919)

![image](https://github.com/user-attachments/assets/53071b75-83b1-4ab4-9f3e-8f129cdf840e)

**Comment by clefebvre** [comment]
In `/usr/share/cinnamon/js/ui/polkitAuthenticationAgent.js`, in the `_onInitiate` function, add the following lines:

```
        global.log("Authentication..");
        global.log(actionId);
        global.log(message);
        global.log(iconName);
        global.log(cookie);
        global.log(userNames);
```

The result should look like this:

![image](https://github.com/user-attachments/assets/60e704ef-f6cb-43bf-880c-6d626ed1ab55)

Then,

- Save the file
- Restart Cinnamon
- Run pkexec
- Check the logs via Looking Glass
- Paste the output here

**Comment by sidambhire** [comment]
Thanks for offering help with debugging this issue.

Output from Looking Glass after doing above steps:
```
info t=2024-12-12T15:17:51Z Authentication..
info t=2024-12-12T15:17:51Z org.freedesktop.policykit.exec
info t=2024-12-12T15:17:51Z Authentication is needed to run `/bin/bash' as the super user
info t=2024-12-12T15:17:51Z 
info t=2024-12-12T15:17:51Z 1-d825ee82fad597bce62ed514f6876b16-1-786a7a3520d40bbc9ae30065034cc860
info t=2024-12-12T15:17:51Z [
    'root',
]
info t=2024-12-12T15:17:51Z Updating user
```

**Comment by clefebvre** [comment]
That looks ok to me. @mtwebster any idea?

**Comment by clefebvre** [comment]
oh wait.. I think I might know what's going on.

You're logged in as root right? Your account has no real_name.

**Comment by clefebvre** [comment]
You can try `usermod -c "Root account" root` to assign your root account a real name. I've a feeling this will fix the problem.

If it does, please don't do it on the other computer though. We want to keep the bug going on that other computer so we can verify when we fix this on our side in Cinnamon itself.

**Comment by sidambhire** [comment]
Changing root account name did not fix the issue.

**Comment by sidambhire** [comment]
On Arch Linux forums somebody fixed the bug with following hack:
In file `/usr/share/cinnamon/js/ui/polkitAuthenticationAgent.js` there is a section of code which says TODO:

```
// TODO - maybe register probably should wait until later, especially at first login?
        this._native.register();
```
They commented out that line as following:
```
// TODO - maybe register probably should wait until later, especially at first login?
//        this._native.register();
```
That fixed the error for me as well.

**Comment by clefebvre** [comment]
What is your username, and is your account an admin account?

**Comment by sidambhire** [comment]
My username is sid and my account is an admin account.

**Comment by clefebvre** [comment]
I think that only works around the issue.

**Comment by Jakjm** [comment]
I am still encountering this issue on Arch Linux (kernel 6.12.10-arch1-1) with cinnamon 6.4.6-1.
@clefebvre  have these changes been put into a release version yet?

When trying to launch timeshift or gparted, the prompt for "Enter Password" does not appear and 
I have to manually run "sudo timeshift-gtk" or "sudo gparted" from the command line.

**Comment by pzim-devdata** [comment]
Same problem since the update of cinnamon and polkit. 

**This issue is not solved** and cinnamon 6.4.2. was published on testing ?

**Comment by mikaku** [comment]
Same problem after upgrading from Fedora 40 (Cinnamon 6.2) to Fedora 41 (Cinnamon 6.4).

**Comment by leigh123linux** [comment]
> Same problem after upgrading from Fedora 40 (Cinnamon 6.2) to Fedora 41 (Cinnamon 6.4).

It didn't reproduce here when I pushed 6.4.x to F41, I wont be addressing any issues for F41 as I consider it EOL once I move to F42, that happened over two months ago.

**Comment by mikaku** [comment]
@leigh123linux, if you don't plan to fix the bug in F41 at least let us know the patch and we'll be able to fix it ourselves.

**Comment by leigh123linux** [comment]
> This seems to happen only when you upgrade from F40 to F41. And, F41 is not EOL. It will be EOL around December, one month past of the release of F43.

Try creating a test user account and see if the issue reproduces there with default settings and theme.

F41 cinnamon might get minor cinnamon-6.4.x release updates if there are any, it won't get the next major release 6.6.x
I don't have anything older than F42 on any machines and don't consider using VM 's a reliable test platform.
This makes updating old releases a problem, the update can get pushed to the repo without any testing whatsoever. 
The above reason above are why I consider old releases as EOL

**Comment by leigh123linux** [comment]
> [@leigh123linux](https://github.com/leigh123linux), if you don't plan to fix the bug in F41 at least let us know the patch and we'll be able to fix it ourselves.


The bug could be a result of the upgrade, I used f41 cinnamon-6.4.x for nearly 3 months and never had any issues with polkit.

**Comment by mikaku** [comment]
> Try creating a test user account and see if the issue reproduces there with default settings and theme.

Hmm, this makes me think that perhaps the problem is that I'm continue using the Linux Mint theme from F40 (Cinnamon 6.2) on F41 (Cinnamon 6.4). Do you think that would be the cause?

I did that because during the upgrade to F41 the Linux Mint theme was no longer available and I had to ported it back to my new F41 from an F40 that I'm still using.

**Comment by mikaku** [comment]
That would explain why it works on fresh installations.

**Comment by leigh123linux** [comment]
@mikaku 

I believe a bad theme might cause issues, the themes had polkit support added.

https://github.com/linuxmint/mint-themes/commit/b36a70d1f848d901ca2c6348306411681d675e23

I haven't looked to see if there is any fallback support for it.



Are you a member of wheel group?

```
[leigh@mpd-pc ~]$ groups
leigh wheel video input mock zerotier-one
```

https://github.com/linuxmint/cinnamon/issues/12620

**Comment by mikaku** [comment]
> I believe a bad theme might cause issues, the themes had polkit support added.

I'll try using a theme provided by Cinnamon in F41 instead of the one that was provided by Cinnamon in F40 to see if that was the culprit.

> Are you a member of wheel group?

No, I haven't need it as I don't use `sudo` but `su -`.

**Comment by leigh123linux** [comment]
> > Are you a member of wheel group?
> 
> No, I haven't need it as I don't use `sudo` but `su -`.


polkit requires wheel to function

**Comment by mikaku** [comment]
> polkit requires wheel to function

You mean in Cinnamon 6.4? because on previous Cinnamon versions that was not needed.

**Comment by mikaku** [comment]
> I'll try using a theme provided by Cinnamon in F41 instead of the one that was provided by Cinnamon in F40 to see if that was the culprit.

I've tested with the default theme in Cinnamon 6.4 and the result is the same, no pop-up window to enter the root's password.

**Comment by mikaku** [comment]
Also, this seems related <https://bbs.archlinux.org/viewtopic.php?id=301680>

**Comment by Jakjm** [comment]
Adding myself to wheel group and removing sudo from the gparted command appears to have worked.

**Comment by Jakjm** [comment]
How can we prevent the need for users to come to this page before adding themselves to the wheel group and getting it to work?  I'm assuming it's a security risk if installing polkit or cinnamon automatically adds your user to the wheel group.
Is there a prompt when installing polkit to add yourself?

If nothing else, should I maybe add a troubleshooting note to the arch wiki page about cinnamon to give people a heads-up?
https://wiki.archlinux.org/title/Cinnamon
(I will try to do this tonight if I don't hear any compelling reasons for why not)

**Comment by Jakjm** [comment]
@mikaku while this isn't anything definitive, I think this article on the arch wiki suggests that yes, adding your user to the wheel group is a requirement for polkit.
https://wiki.archlinux.org/title/Polkit
