### ISSUE TITLE
Calendar - Date Format - "Show information on date format syntax" button - Domain dead

### ISSUE THREAD

**Issue by AtomicRobotMan0101** [linuxmint/cinnamon#12560]
### Distribution

Mint 22

### Package version

6.2.9

### Graphics hardware in use

GeForce RTX 2060

### Frequency

Always

### Bug description

Calendar toolbar app --> right click --> Configure --> Display, button in top box "Show information on date format syntax"

Button when pressed, pops up browser, "connect to the server at www.strfti.me" (Firefox error notice)

### Steps to reproduce

To check this, I open a terminal for a `whois` of `strfti.me` which works. 

Hmm. 

Next, lets do a `wget`... nope. No love.

```
wget strfti.me
--2024-12-09 13:11:00--  http://strfti.me/
Resolving strfti.me (strfti.me)... 192.64.119.203
Connecting to strfti.me (strfti.me)|192.64.119.203|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://www.strfti.me [following]
--2024-12-09 13:11:00--  https://www.strfti.me/
Resolving www.strfti.me (www.strfti.me)... failed: Name or service not known.
wget: unable to resolve host address ‘www.strfti.me’
````

### Expected behaviour

domain to deliver some content. 

Perhaps its been moved since first coded?

**Comment by clefebvre** [comment]
Fixed.
