### ISSUE TITLE
Many themes are broken in 6.4.2

### ISSUE THREAD

**Issue by tre-flip** [linuxmint/cinnamon#12574]
### Distribution

Void 6.6.65_1 x86_64 AuthenticAMD uptodate rF

### Package version

cinnamon-6.4.2_2

### Graphics hardware in use

AMD ATI 03:00.0 Lucienne 

### Frequency

Always

### Bug description

Hello! I've updated Cinnamon to 6.4.2 from Void linux repository, and now many cinnamon themes look ugly. 
OSD windows don't display properly, compared to the older versions of Cinnamon. They lack backgrounds, some buttons are much smaller, sound and screen brightness OSD don't have indicators.  

Did the theme specification change, so theme maintainers should update their themes, or is it a bug?

![2024-12-14_01-14](https://github.com/user-attachments/assets/0c3cfded-ddb8-4f2c-b47c-356a1feacb48)
![2024-12-14_00-08](https://github.com/user-attachments/assets/8bbe3543-b6be-4eb0-9b7b-9ca267d1d890)

### Steps to reproduce

Install and enable a third-party theme for Cinnamon, for example this https://www.gnome-look.org/p/1471298.
Try to log out using a menu in Cinnamon panel, change screen brightness or volume using media keys.

### Expected behavior

OSD windows should have backgrounds and indicator bars.

**Comment by leigh123linux** [comment]
It's the themes that need fixing.
