### ISSUE TITLE
New dialogs design

### ISSUE THREAD

**Issue by tutralex** [linuxmint/cinnamon#12591]
I use Cinnamon not only on my PC, but also on my TV, where only one gyroscopic mouse is connected. That is, for entering text, etc., the virtual keyboard "Onboard" is used. How can I use it if your fucking new dialog messages use the blackout screen and block all functions? How can I enter the same password when I need to elevate my rights? Why can I paste it from the clipboard, but I can't type it on the fucking "Onboard" keyboard?!

Btw, if I want a DE Gnome interface, I'll switch to using DE Gnome and delete Cinnamon, why do I need Cinnamon then?!.

**Comment by tutralex** [comment]
How to disable displaying dialog boxes in full screen mode?

**Comment by JosephMcc** [comment]
There is already a fix open for the keyboard issue: https://github.com/linuxmint/cinnamon/pull/12584

If you can't keep things decent in your comments, your issues are likely to get deleted. There is no call for being rude.
