### ISSUE TITLE
Can't set panel size higher than 25px on theme level

### ISSUE THREAD

**Issue by bimsebasse** [linuxmint/Cinnamon#1267]
This is a new bug that was reported by a user of the Baldr theme. If the panel in a theme is set to higher than 25px, the (bottom) panel will overlap gtk windows/modals. It's only an issue on theme level as setting panel height to e.g. 28px through Cinnamon Settings does not cause overlapping behaviour.

I have no idea what commit has dominoed this panel overlapping side-effect :o(

Of course theme makers can write "this theme works best with panel height set to 28px etc." but it's an unfortunate regression if it can be undone easily. 

To reproduce, edit the default theme's cinnamon.css:
# panel {

```
color: #ffffff;
background-color: #555555;
font-size: 8.5pt;
font-weight: normal;
height: 28px; /*was 25px;*/
```

}

Unmodified default theme:
http://i.imgur.com/s0dZS.png

Panel height set to 28px in cinnamon.css (panel overlapping bottom of webpage):
http://i.imgur.com/oTqRW.png

Panel height set to 28px in Cinnamon Settings (no overlap):
http://i.imgur.com/rsUZ5.png

**Comment by lolgear** [comment]
Hey, same issue here! I want to use Win7 theme by nooblabs and in this theme bottom panel height is 32px. 
Linux Mint 17.1, Cinnamon 2.4.6
