### ISSUE TITLE
After attaching a pendrive, Nautilus is opened instead of Nemo

### ISSUE THREAD

**Issue by pmarcelll** [linuxmint/Cinnamon#1274]
After I plug in a pen drive or an SD card, Nautilus is opened instead of Nemo.
I'm using the latest nightlies, both Cinnamon and Nemo.

**Comment by Vahan86** [comment]
To test it I have also installed the Nautilus. It seems works correctly now (in Cinnamon 3.0.7). After attaching a flash drive Nemo is opened.

@JosephMcc can we close this issue?

**Comment by JosephMcc** [comment]
Yeah, the original OP was asked to test this in a more recent version and never did.

**Comment by pmarcelll** [comment]
Sorry, I don't use Cinnamon anymore, but I'm glad this is resolved.
