### ISSUE TITLE
Firefox does not exit Private Browsing properly when there multiple windows on multiple workspaces

### ISSUE THREAD

**Issue by abrucey** [linuxmint/Cinnamon#1283]
Linux Mint 13 Maya + Cinnamon 1.6 (64bit)

Reproduce:

- Create 2 workspaces
- On workspace 1, launch one firefox window.
- On this firefox window, open 2 tabs.
- Go to workspace 2, launch another firefox window.
- On this firefox window, open 2 tabs.
- In this firefox window, go to Tools>Start Private Browsing
- Go to Tools>Stop Private Browsing

- The firefox window from workspace 1 will now appear on workspace 2 and will not function properly. It appears to be a maximized window, but only the size of a quarter of the screen.

This does not seem to happen with only 1 tab in each firefox window
When opening on more than 2 workspaces, the issue only seems to effect the first workspace window

**Comment by Vahan86** [comment]
@abrucey, does this issue still occur in Cinnamon 3.0.x (Linux Mint 18)?

**Comment by Vahan86** [comment]
@JosephMcc, can we close the issue?

**Comment by JosephMcc** [comment]
Yes. What I've been doing is waiting about 30 days after tagging something with the "close if no response" tag. I figure that gives a fair amount of time for someone to respond. I just check them about every week or so.
