### ISSUE TITLE
Some apps ignore alternative keyboard layout

### ISSUE THREAD

**Issue by nirvdrum** [linuxmint/Cinnamon#1309]
My apologies in advance if I'm filing this against the wrong project . . .

I switch between QWERTY and Dvorak layouts in the Cinnamon keyboard layout settings.  When in Dvorak, everything works fine unless it's a Swing app.  Swing apps will ignore this setting and always use QWERTY.  So, I don't know if it's a bug in Swing or an issue with the way Cinnamon reports the key events to Swing.

**Comment by JosephMcc** [comment]
Closed due to lack of response.
