### ISSUE TITLE
keyboard applet doesn't show up and doesn't work - libgnomekbd changed

### ISSUE THREAD

**Issue by kiilerix** [linuxmint/Cinnamon#1337]
As requested by the Fedora packager on https://bugzilla.redhat.com/show_bug.cgi?id=874225 .

cinnamon-1.6.4-1.fc18.x86_64
/usr/share/cinnamon/applets/keyboard@cinnamon.org/applet.js :

        let groups = this._config.get_group_names();
        if (groups.length > 1) {
            this.actor.show();
        } else {
            this.menu.close();
            this.actor.hide();
        }

The idea here is apparently that if only one keyboard layout is configured then the applet should remain invisible.

But something in Gnome / libgnomekbd-3.6.0-1.fc18.x86_64 has apparently changed. get_group_names no longer report the list of available layouts but ... 'something else'.

If the current layout is the default 'us' then groups will contain only that single element - 'English (US)'. The toggler will thus not be shown.

If several (more than two) layouts are configured and a non-us layout is selected then the list will only contain two elements, (for instance) 'Danish' and 'English (US)'.

This change also shows up in the output of 'setxkbmap -print'.

cinnamon needs to adapt to the new behaviour ... or convince libgnomekbd to change.

**Comment by pwil3058** [comment]
This is an issue for me on Korora 23 (Cinnamon).  The keyboard doesn't show up in the panel on any of the three systems I have.  If I click on "show" in the configuration menu a small rectangle shows up in the panel but it is hidden behind other apps and cant be clicked.  The reason that I'm concerned about this (where I normally wouldn't care or notice) is that one of my machines is a HP x360 Spectre and I'd like to be able to access an on screen keyboard if I go into tablet mode.

**Comment by leigh123linux** [comment]
@pwil3058 you need to have more than one keyboard layout defined for the keyboard applet to show.

surely if you want on-screen keyboard you would use the 'on-screen keyboard'  instead?

**Comment by pwil3058** [comment]
Have I misunderstood what the keyboard applet does?  I assumed (in the absence of documentation) that it was there to pop up the on screen keyboard.

I tried enabling the on screen keyboard in the accessibility options and, although this works OK, having to go through that procedure every time I want to go into tablet mode is less than ideal.  Leaving it enabled all the time isn't an option as it just gets in the way when not in tablet mode whenever you go into a window where a keyboard is needed.  A button in the panel to enable/disable it would be handy.

When Windows was installed, it just enabled/disabled the on screen keyboard when the computer was folded into tablet mode but I guess that's a bit hard to emulate without knowledge of how the computer tells Windows that it's been folded?

**Comment by JosephMcc** [comment]
The accessibility applet allow access to the on screen keyboard option.

**Comment by pwil3058** [comment]
Thanks.

**Comment by JosephMcc** [comment]
Closing this since there hasn't been any feedback on the original issue in over 3 years.
