### ISSUE TITLE
Screen Lock Will Not Work [Cinnamon 1.6.6, Arch Linux]

### ISSUE THREAD

**Issue by CanadianBakn** [linuxmint/Cinnamon#1347]
Cinnamon 1.6.6
3.6.6-1-ARCH
linux 3.6.6-1

My system will not lock my screen. I have attempted the following:
- Issuing gnome-screensaver-command -l
- Suspending my laptop
- Pressing the keyboard shortcut configured in Cinnamon (default ctrl+alt+L)

My system WILL lock from gnome-shell or gnome-fallback. Xinitrc has: gnome-session-cinnamon. This session will not lock.

I have also checked syslog and stderr (from direct screensaver command) for errors. When I issue this command, I simply get no output at all.

**Comment by dalcde** [comment]
Should be a non-issue now we have cinnamon-screensaver
