### ISSUE TITLE
Random broken display in terminal (1.6.4)

### ISSUE THREAD

**Issue by progzy** [linuxmint/Cinnamon#1356]
Randomly display is broken in terminal (black spaces ...). It seems "re-drawing the window" (two "Alt-Tab" ie ) corrects the display till the next break.

**Comment by JosephMcc** [comment]
Closing do to inactivity.

**Comment by progzy** [comment]
@AlbertJP : just found back this issue in my mailbox. Sorry for this delay :/. It is not anymore. Thank you!
