### ISSUE TITLE
Allow scale to multi-select windows to be moved to another workspace

### ISSUE THREAD

**Issue by wrouesnel** [linuxmint/Cinnamon#1372]
A lot of the time when I start working on something I simply open a browser on the workspace I'm currently in and go searching for whatever it is I'm trying to do. 6 terminal windows, 3 more browsers and a note taking application later, and my original task is buried under all that, OR I'm now thinking I'd like to put this stuff on a separate workspace.

As far as I know though, you can currently only move windows between workspaces one at a time in both scale and expo.

What I'd like to be able to do (probably in scale) is open it up, then check all the windows I want to move and either click or scroll them all at once to the workspace I'm targeting (or send them all to a brand new workspace).

**Comment by JosephMcc** [comment]
Thank you for your suggestion. See https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html for information on how we handle feature requests.
