### ISSUE TITLE
true flip on move

### ISSUE THREAD

**Issue by brub2** [linuxmint/Cinnamon#1380]
In recent cinnamon releases, we have a "edge flip" feature. We can drag a window to a edge, wait a few seconds and then the desktop flips with the window. But the window appears at the same place on the screen as on the previous desktop. Also, when "edge flip" is enabled, it also flips if only the mouse (without dragging any window) is maintained at the edge. An user may want to flip _only when moving a window_ (and not if he just points the mouse to the edge).

The idea here is to implement a true "flip on move" which, at least, would be equivalent to what we have in xfce. That means: when I drag a windows to the right edge, the screen instantly flips to the next desktop with this window (and the mouse) at the left of this desktop. From this point I can release the mouse button (and the move is done) or redrag to the left to return to the original desktop. Of course, it would be nice to add some animation; something to visualize what we are doing. It would then be better than xfce.

The expo feature of cinnamon is nice, but a true "flip on move" is a quicker way to move a current window to the next desktop (and go to this desktop).

**Comment by JosephMcc** [comment]
Thank you for your suggestion. See https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html for information on how we handle feature requests.
