### ISSUE TITLE
add good freatures of unity

### ISSUE THREAD

**Issue by timmie** [linuxmint/Cinnamon#140]
Cinnamon is far the best DE taht I used after Gnoem 2 went away! Congrats and THANKS.

nevertheless, there are some good things in Unity worth to integrate:

+ program menubar in title menubar (saves screen real estate)
+ orange rectangle when maximising windows
+ messaging menu with fast user switching, integration of Skype, other messaging services
+ logon/logoff menu with fast access to system settings

**Comment by JosephMcc** [comment]
Most of these are done except for the global menu, which won't be.
