### ISSUE TITLE
Inconsistent icon scaling in panel (blurry icons)

### ISSUE THREAD

**Issue by bwat47** [linuxmint/Cinnamon#1401]
I am using the latest cinnamon 1.6.7. I've noticed an issue with the scaling of icons in the cinnamon panel. With the default panel size (25) the quick launch icons are very blurry looking, but the icons on the window list and tray icons are sharp: http://i.imgur.com/u2ksk.png

If I change the panel size to 28 and allow cinnamon to scale the icons, the quick launch icons look perfectly sharp, a very noted improvement. However now the window list icons look very blurry: http://i.imgur.com/376JI.png

At the very least all panel icons should look sharp at the default panel size.

**Comment by jonmann20** [comment]
![screenshot from 2015-03-17 17 34 14](https://cloud.githubusercontent.com/assets/2007099/6698100/1f258bce-cccc-11e4-968d-1a9c90f2a810.png)

Still blurry.  Also on @sunbriel's point of number value feedback, I also find that not listing the pixel number for the panel height is frustrating.

**Comment by Vahan86** [comment]
@bwat47, is this still an issue for you in Cinnamon 3.0?

**Comment by Vahan86** [comment]
@JosephMcc,  can we close the issue?
