### ISSUE TITLE
The Workspace Switcher and Window List applets make workspace switching slow

### ISSUE THREAD

**Issue by mondalaci** [linuxmint/Cinnamon#1413]
Without these applets workspace switching is blazingly fast.  The Window List applet increases workspace switching delay by about 0.3 second and the Workspace Switcher applet adds another 0.3 seconds to the mix.  When both are enabled the delay is very noticable.

It's probably worth testing this issue with many windows opened on each workspace.

https://github.com/linuxmint/Cinnamon/issues/1037 is a related issue that I opened and some of the problems have been resolved there but this is still a noticable issue, especially if you use workspace switching thousands of times per day like me.

Using Cinnamon 1.6.7

**Comment by JREAM** [comment]
I am on a core i7, 16gb ram and the Window Applet in the top right also causes tons of slowness. I removed it and its much faster and animated.
