### ISSUE TITLE
Keyboard layout switching [BUG]

### ISSUE THREAD

**Issue by katoquro** [linuxmint/Cinnamon#1418]
I use Caps to switch between keyboard layouts. It's works in the majority cases but simultaneously this key trigger 'Caps Lock'-on and after switching 'Caps Lock'-off events. Sometimes when I start typing fast after pushing Caps it switches to 'Caps Lock'-on and layout doesn't change : 'this is text in Russian:LHEUFZ HFCRKFLRF' (should be: 'this is text in Russian:другая раскладка'). If I click Caps one more time then I will get right layout without Caps Lock.

**Comment by JosephMcc** [comment]
Closing do to inactivity.
