### ISSUE TITLE
Option to move(drag to reorder) workspaces.

### ISSUE THREAD

**Issue by gauravjuvekar** [linuxmint/Cinnamon#1422]
Consider you have a lot of windows open across say 6 workspaces.
You are currently in workspace 2 and you have related applications open in workspace 5 and you wan't to switch between them, dragging windows between them.
Going to expo or using shortcuts would be slow.
Also there are a lot of windows on each so dragging each window to another workspace would also be slow.

Rather it would be better if workspace 5(and all windows contained in it) could be dragged between workspace 2 and 3(kind of like arranging tabs in window-list). Then one could quickly use keyboard shortcuts to move between the now adjacent workspaces.

We could make the name tab(in expo) draggable(double click it to change name, perhaps?).

**Comment by Hubro** [comment]
Aw bummer... Would be a really nice time saver over dragging the windows one by one. Gnome 3 supports this as well.

**Comment by chuim** [comment]
+1. Was looking for how to do this today...

**Comment by jnupponen** [comment]
+1 I'd like this feature a lot.

**Comment by thorsummoner** [comment]
+1 Want this, I just found out today that after ctrl+alt+up to view expo you can use arrow keys to select a workspace, I thought that was mouseonly. But yeah moving worspaces arround is not a common thing I want to do but when I do want to do it and there is no way to do it, that is a big bummer.

**Comment by hellwolf** [comment]
+1

**Comment by aidygus** [comment]
+1.  This would make my life so much easier as I could reorder the related workspaces as the priorities of my job and projects I work on change.

**Comment by ristomatti** [comment]
+1

**Comment by PPLDevUk** [comment]
+1

**Comment by mynameisfiber** [comment]
+1 (is there a better place to vote for feature requests?)

**Comment by zakhar-herych** [comment]
+1, this would be very pain-reducing feature

**Comment by kariavka** [comment]
+1

**Comment by Topperfalkon** [comment]
Please stop with the +1's

**Comment by leigh123linux** [comment]
-1 for this feature

**Comment by Topperfalkon** [comment]
har har...

**Comment by tanmaywadhwa** [comment]
+1

**Comment by kamni** [comment]
This ticket has been open now for almost 4.5 years, and it's still a much-desired feature. +1

**Comment by dave08** [comment]
+1 !!!

**Comment by leigh123linux** [comment]
Locked!

All the +1's just means more spam for the dev's!

**Comment by JosephMcc** [comment]
Thank you for your suggestion. See https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html for information on how we handle feature requests.
