### ISSUE TITLE
Low disk space notification

### ISSUE THREAD

**Issue by orschiro** [linuxmint/Cinnamon#1425]
Hello, 

I am not sure whether this is a feature or a bug but the low disk space warning is shown every time after boot and does not disappear automatically like the other notifications. 

Can I somehow disable the notification or at least could there be a timer implemented to hide the message automatically?

Screenshot: http://dl.dropbox.com/u/8902804/Screenshots/LowDiskWarning.png

Regards

**Comment by JosephMcc** [comment]
As noted, this is by design and this hasn't been commented on in 3 years, so closing.

**Comment by V01FRam** [comment]
Хотелось бы возобновить обсуждение данного вопроса, так как он уже не однократно поднимался на разных форумах по Linux Mint.  Это беспокоит определённое количество пользователей, которые время от времени наступают на эти грабли, любезно предоставленные разработчиками из самых лучших побуждений.
Я и сам наступил на эти грабли и не могу победить такое же уведомление у себя в системе:
Linux Mint 21.3 Cinnamon V6.0.4 Ядро Linux 5.15.0-119-generic Intel© Core™2 Duo CPU E7400  @ 2.80GHz × 2 3.8 ГиБ
Хотя я пробовал отключить этим методом: https://forums.linuxmint.com/viewtopic.php?p=1973410&sid=be881a324fbaa71ed0f1421ada9b7a68#p1973410
И так пробовал. набирал в терминале gsettings set org.gnome.settings-daemon.plugins.housekeeping ignore-paths "['/mnt/FE680RD2569D891B']"
Система не против этих способов и даже показывает изменения в редакторе dconf. однако поведение системы не меняется. При каждом запуске появляется это назойливое уведомление.
Вопрос: Как это уведомление победить? Как отключить его для этого конкретного раздела?
Может быть я что то не так делаю?
