### ISSUE TITLE
Bluetooth dependencies

### ISSUE THREAD

**Issue by smancill** [linuxmint/Cinnamon#143]
Hi

Can you make the bluetooth dependencies of Cinnamon optional?

Most of the desktop computers and laptops do not have a bluetooth device, but installing Cinnamon also installs *gnome-bluetooth* and *bluez*, etc. It is unnecesary to have those packages and the bluetooth daemon running if I do not have bluetooth.

**Comment by JosephMcc** [comment]
Closing for lack of response.
