### ISSUE TITLE
If de-maximizing animation is enabled, a tiled window pops into fullscreen if titlebar is double-clicked

### ISSUE THREAD

**Issue by sunboy2** [linuxmint/Cinnamon#1442]
Reproduce:
1. Activate the demaximizing effect for windows and make sure that a double click on the titlebar is set to toggle maximize.
2. Edge-Tile a window.
3. Double click on the titlebar.

Mint 14, 64bit, cinnamon 1.6.7 from installation

**Comment by dalcde** [comment]
Sorry but what's the bug here?

**Comment by harogaston** [comment]
@dalcde Shouldn't this be closed? Issue dates from Nov, 2012 and doesn't seem to depict any bug or real issue.
