### ISSUE TITLE
If demaximizing animation is enabled and a maximized window is dragged, it scales first and then moves.

### ISSUE THREAD

**Issue by wilecoyote2015** [linuxmint/Cinnamon#1443]
Reproduce:
1. Activate the demaximizing effect for windows.
2. Maximize a window.
3. Drag the titlebar so that the window gets demaximized and dragged around.

You will notice that the window stays on it's place while scaling down to it's native size and after scaling is completed, it jumps to the actual position of the mouse cursor. I think it should already move with the cursor while scaling to avoid jumping.

Mint 14, 64bit, cinnamon 1.6.7 from installation

**Comment by Vahan86** [comment]
Tried to reproduce the issue on Cinnamon 3.0, it works fine for me.

@ wilecoyote2015, is this still an issue for you with Cinnamon 3.0?
