### ISSUE TITLE
deleting files freezes cinnamon

### ISSUE THREAD

**Issue by Lusito** [linuxmint/cinnamon#1461]
Just experienced this:
I deleted a couple of files in nemo, which made gvfsd-trash go to 120% cpu usage for half a minute. during this time, cinnamon was not reacting to anything anymore.
After gvfsd-trash was back to 0% it was back to normal.

**Comment by reubenfirmin** [comment]
This still happens and is a terrible bug. Why isn't it assigned?

**Comment by Slater91** [comment]
This is still present as of today. It crashed my PC twice when I was deleting 1+ GB of data. The cause of the freeze is Cinnamon itself, as I found out it eats GBs of memory away leading to system crash. In the screenshot you can clearly see it sits at 3.8 GB, which is almost half the total memory available on my system (8 GB).
![schermata del 2017-08-24 13-04-06](https://user-images.githubusercontent.com/11941225/29668903-06069442-88e2-11e7-9bd5-4b56a6042e92.png)

My system:
- Intel Core i7 950
- 8 GB RAM
- NVIDIA GeForce GTX960 with 384.69 proprietary drivers
- Linux Mint 18.2 with all updates installed

**Comment by it-libo-l10n** [comment]
I can confirm this; deleting quite a large number of files (130) freezes cinnamon.
Linuxmint 18.2 64bit - 8gb ram and dualcore quad cpu

**Comment by tmkwrisi** [comment]
Same here
* Linux Mint 19.1 Cinnamon 4.0.10, Linux Kernel 4.15.0-48-generic (previous version 18.4 - before upgrade - was ok)
* Intel Core i5-7600K
* 32 GB RAM
* NVIDIA Corporation GP107 [GeForce GTX 1050]

**Comment by simonwiles** [comment]
Yeah, I'm getting this issue on a new Mint 19.1 install, but only on one of two laptops.  `gvfsd-trash` consumes all available resources and locks up Cinnamon altogether.  Dropping to a TTY and killing the process, and then restarting Cinnamon, works just fine.

**Comment by icarter09** [comment]
@simonwiles how many files are you deleting to get this issue or how large are the file(s)? Thanks.

**Comment by icarter09** [comment]
Is anyone on this ticket still experiencing this issue or have any update? Thanks.

**Comment by fg-ok** [comment]
Having 19.3 on one system and 20.1 on another system (with one of the computers having had this issue), I'm not experiencing these freezes anymore.

**Comment by wunderlich** [comment]
I'm on Linux Mint 20.1 Cinnamon and I'm not experiencing these freezes anymore, too.

**Comment by icarter09** [comment]
Thanks for the updates.

**Comment by Douglas-Klos** [comment]
Mint 20.2, 5.11.0-25 kernel, still having this issue.  i7-10700k, 64GB DDR4, Z490-E, GTX 1070, NVME & SSD storage.  Terminals work fine.  gvfsd-trash hogs an entire core and grinds Cinnamon to a halt.

**Comment by cinnay** [comment]
I got the issue too. Deleting 100+ files freezes the system and extremely increases cinnamon process memory consumption. 
A lot more severe when trash is full (~1-2min freeze), but still noticeable with empty trash (~15sek).

Linux Mint 20.2 Cinnamon 5.0.7, Intel© Core™ i7-4720HQ CPU @ 2.60GHz × 4, 15.6 GiB RAM

**Comment by hernandezlopezfj** [comment]
Same issue here. I guess the only solution is moving away from cinammon, since this issue is more than 10 years old.

**Comment by CavemanJoe** [comment]
I'm also experiencing this problem; whether deleting torrents in qBittorrent or deleting files in any file manager, any time a file is deleted the machine freezes for a moment.  If I try to delete many files at once, then Cinnamon crashes and returns in fallback mode.  Trying to delete more than a handful of files at once hangs the system completely until I do a hard reboot.

**Comment by BeatLink** [comment]
It turned out for me that a file manager applet was causing the slowdown. Try disabling your applets and extensions and see if that fixes it.

**Comment by alexeymuranov** [comment]
@BeatLink what applet is that exactly?

**Comment by BeatLink** [comment]
I think it might be PlacesCenter but i might not be sure
