### ISSUE TITLE
Spanned Desktop Background Aspect Ratio Problems

### ISSUE THREAD

**Issue by txtad** [linuxmint/Cinnamon#1464]
On a system with dual-monitors, there is no desktop background "Picture aspect" setting that will work for images that are an exact match for the aspect ratio of the entire desktop. It would be very helpful if there was a "Spanned and Scaled" setting, or, if Spanned just worked to achieve the best fit. I'm trying this on Linux Mint 14.

**Comment by saveman71** [comment]
I can vouch for this feature, would be very useful. Currently, when I span my wallpapers, all of them have black borders around them.

Display settings:
![screenshot from 2017-10-23 10-07-37](https://user-images.githubusercontent.com/1615426/31878333-06d2f40c-b7da-11e7-81c2-06305d0e593e.png)

Panned (background color set to grey to make border appear more clearly than black on black):
![screenshot from 2017-10-23 10-11-30](https://user-images.githubusercontent.com/1615426/31878498-a0476438-b7da-11e7-8a85-ff4a8ddf62eb.jpg)

Zoom:
![screenshot from 2017-10-23 10-07-01](https://user-images.githubusercontent.com/1615426/31878413-4fb8b76a-b7da-11e7-8d8a-58f752a585b5.jpg)

**Comment by JosephMcc** [comment]
Thank you for your suggestion. See https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html for information on how we handle feature requests.
