### ISSUE TITLE
Screenshot not working properly - not taking current screenshot

### ISSUE THREAD

**Issue by cygnus8595** [linuxmint/Cinnamon#1468]
This is from my post on the Linux Mint forums - http://forums.linuxmint.com/viewtopic.php?f=47&t=103522&p=656457#p654212

I'm having the same issue on Ubuntu 12.04.1 LTS with Cinnamon 1.6.7 running FGRLX video drivers.

Issue:

I take a screenshot, and it creates and saves it in the ~/Pictures folder, but it's not a current screenshot. If I do the Cinnamon restart trick stated in an earlier post (focus on window you want - press Alt-F2 - type r - take screenshot) it does give me the latest screenshot, but the top window bar is missing. If I run gnome-screenshot from the terminal, it works but I get the same error as listed above:

 *\* (gnome-screenshot:9443): WARNING **: Unable to use GNOME Shell's builtin screenshot interface, resorting to fallback X11. Error: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.Shell was not provided by any .service files

When I log out and log in using the standard Unity session, screenshots work as they should, with the save prompt.

**Comment by willzfarmer** [comment]
Yeah, this is still a problem. It *sometimes* works, but about half of the time I get the following error message after I take a screenshot. It only seems to be bad when I select a portion of my screen however...

```
┬─[william@fillory:~]
╰─>$ gnome-screenshot --interactive
** Message: Unable to select area using GNOME Shell's builtin screenshot interface, resorting to fallback X11.
** Message: Unable to use GNOME Shell's builtin screenshot interface, resorting to fallback X11.
```

**Comment by Vahan86** [comment]
@cygnus8595, is this still an issue for you with Cinnamon 3.4?

**Comment by cranes-bill** [comment]
@Vahan86, i have this problem with 3.6.2.

**Comment by leigh123linux** [comment]
File the issue against linuxmint/gnome-screenshot 

https://github.com/linuxmint/gnome-screenshot
