### ISSUE TITLE
"Dialogue Box" stays when desktop effects are enabled for dialogue boxes in Cinnamon Settings

### ISSUE THREAD

**Issue by kashyapchhatbar** [linuxmint/Cinnamon#1475]
Dialogue Boxes which show information about extraction of archives stay on the screen until cinnamon gets restarted. This happens only when desktop effects are enabled for dialogue boxes. They function normally when desktop effects for them are disabled. 

Using Cinnamon 1.6.7 on Linux Mint 14 64-bit

**Comment by JosephMcc** [comment]
This was fixed.
