### ISSUE TITLE
Save and Restore cinnamon sessions

### ISSUE THREAD

**Issue by pokoli** [linuxmint/Cinnamon#1489]
Add a checkbox on gnome-session-properties to save sessions between logins. 

If the checkbox is checked cinnamon should remember the opened windows, so if the user logouts and logins the desktop should be in the same state as before logout.

**Comment by iNate71** [comment]
@Silmathoron How are you getting it to work? I'm on Mint 17 also, and can't get this to restore anything upon a reboot.

**Comment by Silmathoron** [comment]
Well, I used "dconf-editor" (Alt+F2, dconf-editor) in "org" > "cinnamon" > "cinnamon-session" > "auto-save-session" if my memories are correct.
Regardless, if you want to have nemo windows that open automatically on startup, I advise you to look at "wmctrl" (ex : http://ubuntuforums.org/showthread.php?t=2001005)

**Comment by harogaston** [comment]
+1 for session persistance

**Comment by guikubivan** [comment]
Only thing Cinnamon remembered is my terminal application without my tabs (chrome, atom editor, slack all forgotten), pretty much makes using my laptop for business really annoying. I'm gonna give MATE a try instead.

**Comment by ambs** [comment]
What is the status of this? Mate 18.1 and Cinnamon 3.2.7 here. Thanks

**Comment by leigh123linux** [comment]
Filed against wrong package, please refile it against cinnamon-session instead.

https://github.com/linuxmint/cinnamon-session

**Comment by ambs** [comment]
What is the status of this? Mate 18.1 and Cinnamon 3.2.7 here. Thanks
