### ISSUE TITLE
add a quick sound/mic mute option

### ISSUE THREAD

**Issue by timmie** [linuxmint/Cinnamon#149]
click on sound symbol should offer to mute speakers/microphone.

**Comment by freed00m** [comment]
Hmm :( Muting only affects speakers, microphone keeps recording non stop. I have to go to settings and do it manualy.

**Comment by anandrkris** [comment]
@freed00m - Right click'ing the applet gives mute microphone IIRC...

**Comment by freed00m** [comment]
Aha :D ok thanks, my appologies. Do you know about some cmd line for toggle input on/off by any chance?
