### ISSUE TITLE
Missing raise-window lower-window keyboard shortcuts.

### ISSUE THREAD

**Issue by mody** [linuxmint/Cinnamon#1495]
There are missing these two keyboard shortcuts. They were in Cinnamon 1.4UP3. Please add them.

Using Mint Maya with Cinnamon 1.6.7-20121212044019-precise from ppa.

**Comment by tp0** [comment]
+1. I've used the window title bar (middle click) lowering feature, but a shortcut key would be so much easier.

> They can be added easily, there are so many esoteric (for the majority of users) keybindings, we didn't want to inundate people with items one out of a hundred users may need. We can consider adding the remaining of them, maybe to a new category, or some other idea to keep them from being overwhelming.

There are already so many shortcuts (as a poweruser, the more the merrier to me) that one or two additional ones doesn't make much difference. The average majority user isn't really the sort of user that extensively uses shortcuts in the first place, so kind of an interesting rationale.

Actually, I think what needs cleaning up are the categories themselves. There are so many of them and one of them even having just one shortcut key inside them. I often do not remember which category had which ones.

**Comment by bhsolberg** [comment]
Same here. Having a keyboard shortcut to raise/lower windows can hardly be seen as any kind of "advanced" functionality - it's part of the basic set of functions needed to efficiently manage windows, and all other WMs and desktop managers have this functionality. Please bring it back ASAP (or let me know how I may otherwise achieve it with configuration - no external program should be necessary) so I won't have to switch WM...

Thanks,

Bjorn

**Comment by mtwebster** [comment]
A simple 'ping' here would have sufficed - this was long slipped-the-mind forgotten, and a simple fix.  We can do without the 'do this or else I'll leave'

**Comment by mtwebster** [comment]
btw, until the next major release, you can use dconf-editor to set the raise/lower keys in `org.cinnamon.desktop.keybindings.wm` (or the `gsettings` terminal command).  Alternatively, you can look at that commit and paste those two lines into your file `/usr/share/cinnamon/cinnamon-settings/modules/cs_keyboard.py` at the appropriate spot.

**Comment by bhsolberg** [comment]
Beautiful, that works great - even to override the F1 key which some distros bind to a help function with no (easy) possibility for override! (I use F1 for raise, F2 for lower, as I have for nearly 30 years of X11 usage now...)  I apologize if my frustration shone through too harshly in my previous post, and thank you for the patch!

Bjorn

**Comment by tp0** [comment]
Above dconf-editor setting works, but the lowered window remains active. It doesn't remove the focus. Is this intended?

The way it now works means it is easy to input keypresses into wrong window and into a window you might not be even seeing.

Simple repro:
- open two terminal windows
- lower the other one
- it remains active and thus all keypresses are directed to it...

`Window Focus Mode = Click`
`Prevent Focus Stealing = OFF` (if this and above are even relevant)
Cinnamon 2.8.7
