### ISSUE TITLE
Spacing between menu icon and text shrinks when no windows are open

### ISSUE THREAD

**Issue by cygnus8595** [linuxmint/Cinnamon#1496]
Running Cinnamon 1.6.7 on Ubuntu 12.0.4

When I have no windows open, the spacing between the menu icon and the "Menu" text shrinks and the application launchers also shift to the left. When I have any windows open and they show up in the panel, the spacing returns to normal and the launcher icons shift to the right. This happens on any theme I apply.

I would take screenshots, but I'm experiencing a screenshot bug where it's taking delayed screenshots. Also, when I take a full-screen screenshot, the panel is not displayed in the shot.

If you need any more information (configs, logs, etc) let me know.

**Comment by JosephMcc** [comment]
Fixed.
