### ISSUE TITLE
Windowlist applet scaling

### ISSUE THREAD

**Issue by hengestone** [linuxmint/Cinnamon#1500]
Hi -please add a setting to change the length of items in the windowlist panel applet.

On a hi-res screen with large fonts, the window names gets really short in the windowlist, sometimes only a few characters.

For extra brownie points, make the number of characters scale with DPI so that it remains the same for all displays (scale the length by the text scaling factor from Settings->Fonts).

I can add a screenshot if the above is unclear.

Thanks!
Conrad

**Comment by JosephMcc** [comment]
Closing due to lack of response when asked to test on a newer version.
