### ISSUE TITLE
Expo: Worspaces need long time to leave overview mode.

### ISSUE THREAD

**Issue by wilecoyote2015** [linuxmint/Cinnamon#1511]
Recent GIT, Mint 14, 64bit

Reproduce:
Have at least two workspaces with some windows opened.
Start Expo.
Move the mouse cursor from one to another workspace.
While the mouse is hovering, the workspace turns into overview mode immediately, but as the mouse is leaving, it takes some time until it returns to the normal state. I do not know if that is intended, but it feels sluggish and I think a workspace should return to normal state immediately after the mouse leaves.

**Comment by JosephMcc** [comment]
Closed due to lack of response.
