### ISSUE TITLE
Feature: Sound Applet Input Device and Volume

### ISSUE THREAD

**Issue by dionysius** [linuxmint/Cinnamon#1512]
Hello

I'd like to place a Feature Request for missing Input options. It's like the same things I want what already exists for output options.

I'd like to see following options:
- Define input device
- Define input volume

![Screenshot from 2012-12-16 15:56:35](https://f.cloud.github.com/assets/1341084/15571/c8c61030-4791-11e2-9c52-bf4726688e1e.png)
![Screenshot from 2012-12-16 15:56:45](https://f.cloud.github.com/assets/1341084/15570/c8baa07e-4791-11e2-9656-a1d4f7d0b5d9.png)
![Screenshot from 2012-12-16 15:56:58](https://f.cloud.github.com/assets/1341084/15572/c8c29f2c-4791-11e2-9651-bb12367beecc.png)

**Comment by mtwebster** [comment]
Implemented as of 05f65cf
