### ISSUE TITLE
Blank screen with FGLRX and Cinnamon combination (Problem with maximized borderless windows)

### ISSUE THREAD

**Issue by rayza** [linuxmint/Cinnamon#1513]
Sometimes when starting fullscreen (actually maximized borderless windowed mode I presume since I can Alt+Tab around) applications  I get a one colored background but not the actual application view. The actual application view is however displayed in the Alt+Tab menu and I can get the application view by temporarily switching to a different TTY and back again.  Sometimes it needs multiple attempts. This issue happens e.g. every time with Team Fortress 2, Osmos or the Steam Big Picture mode. The only thing that can be seen beside that one colored background is the "AMD Testing use only" watermark. The application itself though is running normally with e.g. correct sound playback.
This issue only occurs in a combination of using Cinnamon and the FGLRX graphics driver. Also in the Cinnamon panel there are refreshing issues with some icons like the Dropbox icon which doesn't get animated with that combination. When using e.g. Gnome classic, Gnome 3 or Unity this issue doesn't occur. Also the performance when using Cinnamon during gameplay is lower as with other desktop environments. It might be the window manager's fault.
PS: I can not switch to the "radeon" driver since there is no 3D acceleration enabled.

**Comment by JosephMcc** [comment]
Closed due to inactivity.
