### ISSUE TITLE
Applications menu goes outside of the vertical area of the screen

### ISSUE THREAD

**Issue by EagleScreen** [linuxmint/Cinnamon#1515]
This happens in a netbook Asus EeePC with 10 inches screen, resolution is 1024x600.
Please watch the screenshot.
![Screenshot](https://f.cloud.github.com/assets/2446961/15988/60f8a84a-47f1-11e2-8dcb-02249cbf9f6d.png)

**Comment by harogaston** [comment]
Duplicate of https://github.com/linuxmint/Cinnamon/issues/1556 ?
