### ISSUE TITLE
Cinnamon Has A General Problem with 3D And Videos

### ISSUE THREAD

**Issue by tsujan** [linuxmint/Cinnamon#1521]
At least with Cinamon 1.6.7 and nVidia, many 3d apps don't work SMOOTHLY under Cinnamon (while they work quite smoothly under Gnome-Shell). They run jerkily and sometimes cause total freezes. 3d games are good examples that elicit this problem clearly. However, glxgears also shows a similar issue: when it's running, using of Expo or Scale causes a hang-like state in Cinnamon (no hang though).

On the other hand, window scale-in and Expo animations sometimes aren't smooth while, with the same computer, Gnome-Shell animations are always smooth (I've added a scale-in animation to Gnome-Shell by patching it).

**Comment by JosephMcc** [comment]
Closed due to lack of response.
