### ISSUE TITLE
Notifications icon size, and hover effects

### ISSUE THREAD

**Issue by abn-volk** [linuxmint/Cinnamon#1531]
Now the icons in notifications are just 22-24px. They're too small for notifications which display album arts, images, etc. Notify-OSD and xfce4-notifyd use 48x48px icons, so it will be better if we have bigger icons. Big icons also make notifications with 2 - 3 lines look better, because the text is aligned.
Besides, because the notifications are clickable, we should add a hover effect to them, so that the users will know that they can click on them to close.

**Comment by JosephMcc** [comment]
Thank you for your suggestion. See https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html for information on how we handle feature requests.
