### ISSUE TITLE
System Tray Icons are shown as gray squares after updating to Cinnamon 1.6

### ISSUE THREAD

**Issue by digitsm** [linuxmint/Cinnamon#1532]
![Screenshot from 2012-12-23 00:32:09b](https://f.cloud.github.com/assets/2294506/28688/8d6571fe-4c7b-11e2-94b5-78aae78808de.png)
As you can see in the top right corner of the uploaded screenshot, after updating my cinnamon from version 1.4 to 1.6 the application icons displayed in the tray icon are converted to single gray boxes.
I don't know when this issue occurs but it happens sometimes.
I'm using Cinnamon 1.6 on LMDE x64

**Comment by ben2talk** [comment]
Sadly not for me.
http://forums.linuxmint.com/download/file.php?id=24520&mode=view
I have no systray icons, also my terminal and conky windows are invisible unless Cinnamon crashes.
Fallback mode works fine.

**Comment by ManIVIctorious** [comment]
Although I still have a lot issues with the system tray I haven't seen the grey boxes for a long time now, is this still an issue for some of you in latest cinnamon 3.0?

**Comment by Vahan86** [comment]
https://github.com/linuxmint/Cinnamon/issues/481
