### ISSUE TITLE
Alt+Tab switcher takes too long to show up (~2 seconds)

### ISSUE THREAD

**Issue by nucleartide** [linuxmint/Cinnamon#1536]
I just migrated from Ubuntu 12.04 with Cinnamon to Linux Mint with Cinnamon. When I was in Ubuntu-Cinnamon, holding Alt+Tab would display the Alt+Tab switcher immediately. In Mint-Cinnamon, there is a noticeable delay (~2 seconds) between initially pressing Alt+Tab, and the Alt+Tab switcher showing up. A quick Alt+Tab to the most recently viewed application works fine, but does not immediately show the Alt+Tab switcher as I would expect.

This is more of a personal preference than an issue. Is there any way to configure the delay time in Cinnamon's settings?

**Comment by awsms** [comment]
In case someone was wondering the same, I achieved it by tweaking alttab-switcher-delay to 0 in dconf (/org/cinnamon/alttab-switcher-delay)

![dconf](https://user-images.githubusercontent.com/48278661/82004404-149d4000-9663-11ea-94f8-b0a68a57ecea.png)
