### ISSUE TITLE
Egg Timer / Beachball Cursor

### ISSUE THREAD

**Issue by ukprototype** [linuxmint/Cinnamon#1551]
Similar to https://github.com/linuxmint/Cinnamon/issues/732.

I've noticed that when you click on a launch icon on the desktop there is no feedback to the user that the OS is away doing something. 

Coming from other OSes there is a subtle icon change that kinda say "yep, i'm on it" and you stop clicking the icon. With Mint/Cinnamon, I've found myself spam clicking because I think that nothing is happening.

Normally this isn't an issue as most applications load very quickly, however there are some e.g. wine applications, that take a little longer.

**Comment by leigh123linux** [comment]
Cursor theme is responsible for this.
