### ISSUE TITLE
Request: Allow overriding Cinnamon theme's font without manual editing

### ISSUE THREAD

**Issue by seaweedchan** [linuxmint/Cinnamon#1553]
To have a desktop consistent in fonts, my choices as a Cinnamon user are:
-Match all my font types to whichever one the theme developer picked, practically making having a font setting useless, or:
-Manually edit each theme I try just to change the font

I ask -- as a Cinnamon theme developer myself -- that there be a way to override the font type/weight/etc settings chosen by the Cinnamon theme, within the Font section of Cinnamon settings. Be this a regular font setting called "Cinnamon Theme Font" with the default of "Theme default" that otherwise works like any other font setting that already exists, or more extremely foregoing allowing developers to control the user's font choices at all. 

This is not something new to desktop environments in Linux, as it seems to be only Cinnamon and Gnome Shell which have full control over those fonts, something I think Cinnamon should have kicked from the get-go.

**Comment by dalcde** [comment]
Special case of #3356. Closing.
