### ISSUE TITLE
Cut menu on low resolutions (e.g. netbook)

### ISSUE THREAD

**Issue by dtrunk90** [linuxmint/Cinnamon#1556]
The menu is outside the viewport on low resolutions like on netbooks.

**Comment by Vahan86** [comment]
@dtrunk90, is this issue still relevant to Cinnamon 3?

**Comment by dtrunk90** [comment]
Since it's 3 years ago I don't have access to a netbook anymore. So I've changed the resolution to 800x600 and my menu is still fully visible. I guess this isn't relevant to Cinnamon 3 anymore.
