### ISSUE TITLE
cinnamon-menu-editor work

### ISSUE THREAD

**Issue by corbin-auriti** [linuxmint/Cinnamon#1563]
The cinnamon-menu-editor needs some work, its leggy and you don't have much control over what  you edit like dragging launchers to other sections and choosing where its running directory is, I propose forking MenuLibre and using that instead.

**Comment by tp0** [comment]
Are there any plans to work more on the editor?

I recently tried to do some reorganizing of the menus, but I just gave up. The slowness (the constant reloading of the menu files and repopulation of the lists), the aged and nonsensical UI and the bugs:

* drag and dropping, as known and mentioned many times
* cut & pasting an entry does not actually cut (remove) the original one, instead after pasting it in the new location it reappears (duplicates) in the original location
  * then if you delete it from the new location (or from the original location), it gets deleted from the original location too (or from the new location)
  * entry still shows up just once in the menu search
    * except when it sometimes somehow duplicates twice in the original location (!?)
  * these seem to concern only the existing entries, not custom ones
* everytime the category view refreshes/updates/repulates, the scrollbar position is reset
* can't select multiple entries

Overall, it is just appalling to use and pretty much only good for creating new entries once in a while. I think some of these bugs may have been already in the orginal `alacarte`.

**Comment by Translator5** [comment]
2016 ... Still do not work properly :( ...

Is there any command to restore deleted Menu-Items?

**Comment by ineuw** [comment]
Of all the frustrating experiences in using Linux is the lack of a decent menu manager. This being the foundation of a user's comfort in finding an app and using the OS, Linux is unbelievable deficient in such a key area. As the previous poster mentioned, this is 2016.

I am using Xubuntu with Menulibre, which is one of the sadder efforts of the Linux world. I believe that the developer, Sean Davis is 'dancing at too many weddings', and thus ignores users' complaints about the deficiencies of his MenuLibre concept and execution. Thus, this and all the other deficiencies make Linux not yet ready for prime time use.

**Comment by RavetcoFX** [comment]
Linux isnt ready because it doesn't have a perfect menu editor??!! You are
aware Windows & OSX doesn't have real ways of organizing their application
menus right? If it's such an issue to you, learn how to fix it.

**Comment by ineuw** [comment]
RavetcoFX, Since I suspect that you are still a child, I let you reconsider your reply, take a few moments and read what you wrote.

**Comment by mainmachine** [comment]
@ineuw - You're just trolling at this point. This is github, not a message board. Let's either talk about the code and how to improve it, or just stop the pedantic banter and name calling.

To address your point, if you don't like Cinnamon's menu editor, you can use Unity, Gnome, KDE, etc. - so it's unreasonable to judge Linux "not yet ready for prime time use" by the state of just one DE of dozens that one could easily use. And if you like Cinnamon, then contribute bug reports, code or meaningful discussion, or please don't bother. Also, "prime time" refers to television, in which Linux is appearing on a regular basis (see Mr Robot, not to mention the dozens of other, less niche genre TV shows where the occasional Gnome or Unity desktop just shows up every once in a while).

**Comment by bernd-wechner** [comment]
Just a bump. I surfed in here because I wanted to move menu items around. Sort of expecting to find some way to do that in the menu editor. But there ya go, a year later and nothing doing it seems. So seems this could use some attention I guess.
