### ISSUE TITLE
Issue with Panel Launchers applet and lightning applet

### ISSUE THREAD

**Issue by ImanolBarba** [linuxmint/Cinnamon#1575]
Hey! I've noticed another bug.

When using two panels ( Settings > Panel > Panel Layout ), if you add the Panel Launchers applet to the bottom panel and hover the mouse over it, the tooltips show below the top panel as if the applet was on the top panel itself.

Also, in such bottom panel, the lightning applet doesn't seem to work (I click over it and nothing happens, other applets seem to work fine.

I have not tested them all, maybe there are more applets with issues running with both panels.

Thanks for your attention!

**Comment by JosephMcc** [comment]
The panels have been completely redesigned. If you still have issues go ahead and open a new bug report.
