### ISSUE TITLE
Audacious is not correctly minimized

### ISSUE THREAD

**Issue by ImanolBarba** [linuxmint/Cinnamon#1576]
I've noticed that when using audacious with the classical winamp interface, if I hit the minimize button on audacious it just minimizes the main window, the equalizer and playlist remain on screen.

That's probably due to the fact that audacious using the winamp interface gets its own window managed, probably confusing muffin, though I'm not sure.

Other WM also have some quirks when dealing with said interface, but they all manage to minimize and restore it correctly _most_ of times.

Thanks a lot for your attention

**Comment by JosephMcc** [comment]
Closed due to lack of response.
