### ISSUE TITLE
gnome-terminal has wrong parent process with keyboard shortcut.

### ISSUE THREAD

**Issue by simonjbeaumont** [linuxmint/Cinnamon#1580]
Hi,

I'm not sure if this is a Cinnamon issue but I didn't see this issue before I switched to Cinnamon.

If I use the shortcut key to launch _the first_ terminal, `pgrep gnome-terminal | xargs -l1 pstree -s` outputs `gnome-terminal` as a direct child of `init`. However, if I launch it via the menu in Cinnamon it is an ancestor of gnome-session: 

    init───lightdm───lightdm───gnome-session───cinnamon───gnome-terminal

The launching as a non-ancestor of `gnone-session` means that things like SSH_AUTH don't work properly and detaching and reattaching to screen or tmux show odd behaviour.

**Comment by leigh123linux** [comment]
I haven't noticed this issue here

```
$ pgrep gnome-terminal | xargs -l1 pstree -s
systemd───gnome-terminal-─┬─bash───xargs───pstree
                          ├─bash
                          ├─{dconf worker}
                          ├─{gdbus}
                          └─{gmain}
```
