### ISSUE TITLE
[REQ] Add Google Calendar Account to Cinnamon Calendar Panel Applet

### ISSUE THREAD

**Issue by dtrunk90** [linuxmint/Cinnamon#1603]
I'll try to do this next time. Pull request will follow.

**Comment by mfreeman72** [comment]
Is anything going to ever happen with this? Are we doomed to forever have a completely useless, non-functional calendar in Cinnamon, when every other DE and OS that exists has had this functionality for decades?!?! Why does every feature request about this get quickly shut down and never go anywhere? The ability to access, show, and edit events and appointments should really be a very basic functionality requirement in any calendar applet, and Google is the most common way to do it these days. Let's get on this!

**Comment by icarter09** [comment]
@mfreeman72 this issue will be looked into. Please remember to tag people in the ticket to make sure that they are properly alerted. That will help in make sure the necessary developers look into the issue. The Linux Mint team is working hard to make sure this issue and others, along with new features, are properly implemented so your patience is greatly appreciated. I understand your frustration, but please remember that the issue tracker is not the place to vent. I will take it upon myself to look into this issue. If you are still frustrated, then I will be more than happy to chat with you on one of the Linux Mint IRC channels.

**Comment by mfreeman72** [comment]
@icarter09 Thanks for your reply! I apologize for venting. I will try to restrain myself in the future. I'm usually a very patient person, but this issue has bugged me for too many years. :) Thank you for looking into this!

**Comment by icarter09** [comment]
@mfreeman72 Appreciate your understanding and no worries! It happens to the best of us.

**Comment by antismap** [comment]
I'm using cinnamon since a few days and I'm positively impressed (Finally, a VM with a panel with window buttons (with titles!), which works and is stable !)
I was searching for this as well.
I think that this feature would greatly improve the overall experience :)

**Comment by Kambrian** [comment]
I've left the gnome/mate/cinnamon world ever since the launch of gnome 3. Now trying cinnamon again after many years to see if things have matured but disappointed to find that the calendar applet hasn't evolved!
