### ISSUE TITLE
sound applet: vlc controls sound applet volume

### ISSUE THREAD

**Issue by miskebekelniu** [linuxmint/Cinnamon#1606]
Hello,

i have this issue, if i set VLC sound to more than 100%, then cinnamon sound applet set volume identical to that in VLC (somehow it correlates) and that is annoying because if i turn off VLC the sound at cinnamon applet is the same i have set in VLC and if turn on some music via youtube sound gets distorted (over amplified).

Here is a screenshot of this issue:

http://imageshack.us/photo/my-images/547/20130111094148.png/

I have this posted on:

http://forum.cinnarch.com/viewtopic.php?f=7&t=652&sid=04f5c04f5ec780db1c58b511665c272e&p=1547#p1547 

and been directed by forum member to make my statement here, because provided links in the forum:

https://github.com/linuxmint/Cinnamon/issues/1371
https://github.com/linuxmint/Cinnamon/issues/99

does not solve my problem

**Comment by pixunil** [comment]
@mtwebster, if I remember good enough, you had this issue also, right? Can you please check?

For me, VLC is fine, even when going to 200% volume my "main" volume isn't touched.

**Comment by JosephMcc** [comment]
Closed due to lack of response.

**Comment by miskebekelniu** [comment]
Hi, sorry for not responding in time, didn't have cinnamon installed at the
time. Currently running latest stable mint with cinnamon - works fine, no
issue with vlc controlling sound applet.


Pagarbiai,
Justinas Petravičius
Mob. Tel.: +37067244884
El. Paštas: morka.tupinti.uz.kelmo@gmail.com

**Comment by JosephMcc** [comment]
Thanks for following up.
