### ISSUE TITLE
Minimize to tray doesn't remove the window from Cinnamon Window List

### ISSUE THREAD

**Issue by Nicolas01** [linuxmint/Cinnamon#1607]
When I minimize to tray (for instance with amule or keepassx) the window is well minimize but it isn't removed from the Cinnamon Window List.
To do remove the window from the Cinnamon Window List I need to click (or double-click) on the tray icon.

**Comment by anandrkris** [comment]
I just tried with HexChat and seems to work fine. Is this still an issue in latest Cinnamon?

**Comment by Vahan86** [comment]
@JosephMcc, can we close this issue?

**Comment by leigh123linux** [comment]
A month is long enough to respond

**Comment by Nicolas01** [comment]
Sorry for the late comment.
I confirm the problem has been fixed, it doesn't occur any more with my current version of cinnamon (3.2.1)
Thanks

**Comment by leigh123linux** [comment]
Thank for confirming.
