### ISSUE TITLE
Idea: Notification center similar to MacOS M.L.

### ISSUE THREAD

**Issue by bl4de** [linuxmint/Cinnamon#1614]
Hello,

The feature I'd like to see in Cinnamon is the global notification center similar to this one in MacOS Mountain Lion. 
There's a notifications applet right now, but I mean something more complex - one place, where I'll be able to configure notifications from all my activities: email accounts, Facebook, Twitter, Github and so on.

Every of these services have their own APIs, even in official applets for Cinnamon there is an applet "Gmail notification" (http://cinnamon-spices.linuxmint.com/applets/view/73), Gwibber uses notification applet for displays for example Twitter posts, Audacious or any other player shows actually played song and so on.

So, why can't join all these apllets into one sidebar, similar to MacOS? 

Here's little example, how it looks like on Mac:

![Notification_Center_Mountail_Lion](https://f.cloud.github.com/assets/3187617/70714/a13825a6-5fbc-11e2-989a-52a1abccb328.jpg)

 I've just started code an applet including that idea, so if I'll have any "working" version of it to show, I'll notice and give link to my Github repo :)

**Comment by javanesse** [comment]
superb. can't wait for this notification center comes to the linux

**Comment by Sunderland93** [comment]
Yeah, cool idea!

**Comment by JosephMcc** [comment]
Thank you for your suggestion. See https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html for information on how we handle feature requests.

**Comment by stefanoful** [comment]
you have to brush up on this idea ... apart from someone who will be against me, in person, in cinnamon like it !!!!

**Comment by pascaldls** [comment]
Hi came across this 
https://github.com/phuhl/linux_notification_center 
deadd-notification-center: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by deadd-notification-center)

may be if you can make this work

**Comment by KrischnaGabriel** [comment]
This is still not implemented is it? :(

**Comment by Secret-chest** [comment]
As long as the classic networking, clock, printer, battery, notifications, system tray and other applets stay, I'm fine with this.
