### ISSUE TITLE
Incorrect Behavior on SMplayer fullscreen

### ISSUE THREAD

**Issue by ztowfic** [linuxmint/Cinnamon#1621]
Hi,

I noticed the following odd behavior when using smplayer:

To reproduce:
1) Start a video
2) Maximize video (not fullscreen, just maximize the smplayer window)
3) Now go to fullscreen by doubling clicking the video.

What should happen is that the video should become fullscreen. What does happen is that the video is offscreen (top left hand corner in my case) with blue area on top of it. I am using XV overlay output module.

Now, if I do this instead:
1) Start a video
2) Make sure window is NOT maximized
3) Now go to fullscreen by doubling clicking the video.

Then everything works as it should. 

The reason I am posting this in the Cinnamon bugtracker is that I tried to reproduce this behavior in Unity and Gnome-shell, but Cinnamon is the only window manager that caused this behavior.

I tried both smplayer and smplayer2, same results.

**Comment by JosephMcc** [comment]
Can any of you reproduce this under Cinnamon3?

**Comment by Hexcles** [comment]
I haven't run into this problem for long and can't recall when the issue disappeared. Not sure if it's "fixed" by Cinnamon 3 or some other kernel/X11 driver update.

**Comment by JosephMcc** [comment]
Thanks for following up.
