### ISSUE TITLE
Feature request: Ability to invert colors on screen and individual windows

### ISSUE THREAD

**Issue by smkent** [linuxmint/Cinnamon#1644]
The ability to invert colors on individual windows (or the whole screen) was a key [feature of compiz](http://wiki.compiz.org/Plugins/Neg) that cinnamon is lacking, and it's making me consider switching back to MATE. Inverting windows is a useful feature for web sites and other windows with mostly-white backgrounds that are hard on a person's eyes.

I'd be willing to take a shot at writing this but I'm not sure where to begin. How are the fade/scale plugins implemented? I looked through some of the code but I can't figure out if the compositor code is written using the JavaScript bindings or if it's in the C code somewhere.

**Comment by leigh123linux** [comment]
Agreed

> Best implemented as extension
