### ISSUE TITLE
cinnamon-settings does not start

### ISSUE THREAD

**Issue by JCavallo** [linuxmint/Cinnamon#1647]
Hi !

I got a problem when trying to open cinnamon-settings : 

/usr/lib/python2.7/dist-packages/gobject/constants.py:24: Warning: g_boxed_type_register_static: assertion `g_type_from_name (name) == 0' failed
  import gobject._gobject
>>>

I somehow end up with a python prompt, and no settings :(

**Comment by Vahan86** [comment]
@JCavallo, is this still an issue for you with Cinnamon 3.0?

**Comment by Vahan86** [comment]
@JosephMcc, can we close this issue?

**Comment by JCavallo** [comment]
@Vahan86 Sry, I switched to e20 a year ago so I cannot test it anymore.

**Comment by Vahan86** [comment]
@JCavallo thanks for response.
In this case can you please close the issue?
