### ISSUE TITLE
Bluetooth file receive icon stays on tray forever

### ISSUE THREAD

**Issue by LunaticoCR** [linuxmint/Cinnamon#1650]
When I send a file from my phone to my computer the file is received fine but the icon stays on the panel tray forever, there is no way to dismiss it. Restarting Cinnamon does not remove the icon, only a logout does.
![icon](https://f.cloud.github.com/assets/2124383/114046/ee10bf18-6b89-11e2-97d6-2954a1313053.png)

To enable file sharing open Personal File Sharing from MintMenu and under Share Files over Bluetooth select:
- Receive files in Downloads folder over Bluetooth
- Notify about received files

The phone must be paired with the computer.
If the 'Notify about received files' option is not selected then the icon does not stay up forever, it just shows while the transfer is happening.

**Comment by JosephMcc** [comment]
Closed due to lack of response.
