### ISSUE TITLE
Typing BEHIND the lock screen

### ISSUE THREAD

**Issue by Exaeta** [linuxmint/Cinnamon#1667]
I'd been having this strange issue. I type BEHIND the lockscreen in cinnamon. I'm using mint 14. If I hit switch user, I can log in from there. But the default password box, text just goes behind it into whatever program was open. Annoying and a minor security vulnerability.

I'm using a non-default (but included) theme and settings, if that might have anything to do with it. Any configuration etc., just say what might be relevant.

**Comment by JosephMcc** [comment]
Do you still have this issue under Cinnamon3.0?

**Comment by Vahan86** [comment]
@JosephMcc, can we close this issue?
