### ISSUE TITLE
LibreOffice icons problem

### ISSUE THREAD

**Issue by I-sty** [linuxmint/Cinnamon#1668]
I opened two .doc with LibreOffice but just the second window have own icons.
Here my screenshot: <img src="http://kepfeltoltes.hu/130205/Screenshot_from_2013-02-05_10_41_25_www.kepfeltoltes.hu_.png"/>

And my cinnamon info: http://pastebin.com/5fQPbiM9

Cinnarch, cinnamon : 1.6.7-5, LO: 3.6.5-1

**Comment by JosephMcc** [comment]
Closed due to lack of response.
