### ISSUE TITLE
Icon panel delete the unchecked icons

### ISSUE THREAD

**Issue by I-sty** [linuxmint/Cinnamon#1670]
I added many icon to the icon-panel, when I tried to delete one of them I check the pidgin icon to delete it, but Cinnamon remove the Terminal icon what is before it with 3 icon.

I check pidgin to remove:
<img src="http://kepfeltoltes.hu/130126/Screenshot_from_2013-01-26_10_04_23_www.kepfeltoltes.hu_.png"/>

And Cinnamon remove the Terminal icon.
<img src="http://kepfeltoltes.hu/130126/Screenshot_from_2013-01-26_10_04_44_www.kepfeltoltes.hu_.png"/>

**Comment by JosephMcc** [comment]
Closed due to lack of response.
