### ISSUE TITLE
Hide user name from lock screen

### ISSUE THREAD

**Issue by toobuntu** [linuxmint/Cinnamon#1676]
This is a security risk in corporate settings. (A janitor could jostle the mouse and see a valid logon name.) On the other hand, it could be helpful in other use cases. So, please make it configurable whether or not to show or hide the username on the lock screen.

**Comment by leigh123linux** [comment]
This should be filed against cinnamon-screensaver and slick-greeter.

**Comment by NikoKrause** [comment]
It has been implemented recently:
> The login screen is more configurable than before. Options were added for automatic login as well as the ability to hide the user list and enter user names manually (this is useful for LDAP users).

http://blog.linuxmint.com/?p=3322

**Comment by NikoKrause** [comment]
Ah sorry, that's the login screen. You meant the screensaver.
