### ISSUE TITLE
Geany debugger crashes cinnamon

### ISSUE THREAD

**Issue by byteit101** [linuxmint/Cinnamon#1677]
On a Ubuntu 12.04 install (on lvm on dmcrypt if it matters) that I have installed from ppa cinnamon into, I can crash cinnamon by clicking the "stop debugging" red square of the debugging plugin for geany (version from the precise repos, its fixed in git head)

Observations:
* Only works when launching from menu or normal terminal. launching via byobu or tty1 caues geany to crash, but prevents cinnamon from crashing
* Does not crash compiz/unity (have not tried gnome-shell)
* When logging back in to cinnamon, I have lost control of all media keys (volume up/down, etc does nothing, though I can go to sound settings and manually adjust it)

crash log from stderr when running cinnamon --replace from tty1: (excluding 12k theme parsing errors)

     Window manager warning: Log level 16: STACK_OP_REMOVE: window 0x77 not in stack

     (cinnamon:25338): Clutter-CRITICAL **: clutter_actor_queue_relayout: assertion `CLUTTER_IS_ACTOR (self)' failed

versions of geany and geany plugins is 0.2.1.dfsg-2 and 0.21.dfsg-1ubuntu4
reproduction steps from fresh geany install:
* launch geany
* tools>plugin manager>enable 'debugger' plugin
* (note: my geany already had 'Addons', "Extra Selection" "File Browser", "GeanyVC" and "Split Window" also enabled, though according to geany developers, the issue is only from the debugger plugin)
* Create and compile c code with the -g debugging option to gcc
* add breakpoint to geany by clicking to the left of one or more lines of code
* go to the message window (view>show message window)
* go to debug tab in message window
* browse (or copy paste) the compiled file into the target text box
* hit the run button to the right side of the debug tab
* geany should stop on the first breakpoint you set
* hit the red stop button to the right side of the debug tab
* geany crashes
* cinnamon crashes

**Comment by JosephMcc** [comment]
Closed due to lack of response.
