### ISSUE TITLE
Expo, Scale and workspace switching animation stutter when not used for some time.

### ISSUE THREAD

**Issue by wilecoyote2015** [linuxmint/Cinnamon#1680]
Applies for Git and release versions, Mint 14, 64bit.

Most cinnamon features (Expo, Scale, workspace switching and the panel menu) are stuttering/have delay if they are started after they weren't used for some time.

Reproduce the Issue:
Use some applications without using Expo, Scale or the Panel for some minutes.
Then use the hot corner. The Scale or Expo will be very choppy while the first activations.

Are those processed killed after some time and have to be restarted again after some time?
If so, I would strongly appreciate an option to let all those processed run in the background continuously for stronger machines because the frequent stuttering is really annoying and blocking productivity.

**Comment by JosephMcc** [comment]
Closed due to lack of response.
