### ISSUE TITLE
[SUGGESTION] Expo should show workspaces on all screens for multiple monitors

### ISSUE THREAD

**Issue by wilecoyote2015** [linuxmint/Cinnamon#1694]
The Expo effect sticks all screens together to one big workspace and shows those big workspaces in expo mode on the first screen.
In my opinion it is better to have a desktop grid on every screen that shows all workspaces on the screen. KDE does so and it is clearly the better solution because it uses the given space more efficiently (even with only two monitors and three workspaces you get problems to distinguish many applications in expo mode because everything is squeezed to one single monitor.)

If you have more than one screens, it simply makes more sense to show the parts of every workspace on the according screens than simply putting it all together on one screen.
Of cause, if you hover on workspace a workspace on screen 1, the other half on screen 2 should be highlighted accordingly.

**Comment by JosephMcc** [comment]
Thank you for your suggestion. See https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html for information on how we handle feature requests.
