### ISSUE TITLE
Freemind menus close immediately in Cinnamon

### ISSUE THREAD

**Issue by fedir** [linuxmint/Cinnamon#1706]
File / Edit / View etc menus close unless you hold down the left mouse button in Freemind under Cinnamon. Can also be erratic - clicking on one menu item opens one two to the left for example.

This occurs if the window is maximised or at any other size than the defaulted window size. It is only a problem under Cinnamon, works fine under Gnome Shell.

Changing of window size resolves the temporary bug.

// Reposted from : https://bugs.launchpad.net/linuxmint/+bug/955081

**Comment by JosephMcc** [comment]
Closed due to lack of response.
