### ISSUE TITLE
Drag window to different workspace

### ISSUE THREAD

**Issue by LunaticoCR** [linuxmint/Cinnamon#1707]
Hello,

Is it possible to drag a window to a different workspace?

I don't seem to be able to do this... when I drag a window to the left or right it tries to go into half-screen full screen mode (or however that's called).

This would be a nice feature request.

Thanks.

**Comment by KES777** [comment]
any news here?

**Comment by charsi** [comment]
+1 for being able to drag windows to workspaces

**Comment by vakimov** [comment]
I've found a way to overcome missing of Shift-Ctrl-Alt-right/left methods.
You can make window been showing on all workspaces then move to the desired workspace and then make window been showing only on the current workspace.
1. In System/Keyboard/Shortcuts/Windows add keyboard binding for "Toggle showing windows on all workspaces" (Shft+Ctrl+ShiftR for example)
2. Install `pip install pynput`
3. Create in ~/.scrips/moving.py
```python
import time
from pynput.keyboard import Key, Controller

keyboard = Controller()

def gen_combination_handler(func):
    def handler(*keys):
        for key in keys:
            func(key)
    return handler

press_combination = gen_combination_handler(keyboard.press)
release_combination = gen_combination_handler(keyboard.release)

def push_combination(*keys):
    press_combination(*keys)
    release_combination(*keys)

def push_toggle_showing_an_all_workspaces():
    push_combination(Key.shift, Key.ctrl_l, Key.shift_r)

def move(is_right):
    direction_key = is_right and Key.right or Key.left
    # In order to properly make the first combination
    # you need to release currently pressed special buttons
    # So the next keys depend on the corresponding
    # System/Keyboard/Shortcuts/Custom Shortcuts keyboard bindings (see step 4.)
    release_combination(Key.alt, Key.ctrl)
    push_toggle_showing_an_all_workspaces()
    push_combination(Key.ctrl, Key.alt, direction_key)
    push_toggle_showing_an_all_workspaces()

```
3. Create and make it exacutable two sripts ~/.scripts/move_right.py and move_left.py
```python
#!/usr/bin/python
from moving import move
move(is_right=True)  # False for move_left.py
```
4. In System/Keyboard/Shortcuts/Custom Shortcuts add two shorcuts for both sript and add keyboard bindings to them (Ctrl+Alt+; and Ctrl+Alt+' for example)
