### ISSUE TITLE
Font-rendering in panel

### ISSUE THREAD

**Issue by ghost** [linuxmint/Cinnamon#1724]
The font in the panel is antialiased incorrectly: it ought to be subpixel (i.e. rgba) antialiased like the rest of the system, but it's currently using grayscale only.

I'm running up-to-date Arch Linux with Cinnamon 1.6.7.

**Comment by JosephMcc** [comment]
Thank you for your suggestion. See https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html for information on how we handle feature requests.
