### ISSUE TITLE
Focus stealing

### ISSUE THREAD

**Issue by ac000** [linuxmint/Cinnamon#1727]
Been using Cinnamon a few days now. Like it. However there is one niggling issue I see.

If I click a link in say Liferea or Claws Mail to open in Firefox. Firefox immediately takes the focus. This can be particularly irksome if you are clicking on several links to open.

Cheers,
Andrew

**Comment by bradonomics** [comment]
It's been a few years, but this is still an issue for me. I'm on Ubuntu 17.10 running Cinnamon 3.6.7. When applications open they steal focus from whatever I'm doing. It's especially annoying when I'm typing and hitting the spacebar selects whatever the default option is in the new window—whether I wanted that or not.

Is there a resolution for this?

**Comment by sstelfox** [comment]
For anyone else finding this, it seems the command `dconf write /org/cinnamon/prevent-focus-stealing true` can set turn on the option that was merged earlier in this issue.

**Comment by sstelfox** [comment]
For anyone else finding this, it seems the command `dconf write /org/cinnamon/prevent-focus-stealing true` can set turn on the option that was merged earlier in this issue.

**Comment by sstelfox** [comment]
For anyone else finding this, it seems the command `dconf write /org/cinnamon/prevent-focus-stealing true` can set turn on the option that was merged earlier in this issue.

**Comment by sstelfox** [comment]
For anyone else finding this, it seems the command `dconf write /org/cinnamon/prevent-focus-stealing true` can set turn on the option that was merged earlier in this issue.
