### ISSUE TITLE
Long notifications duplicated

### ISSUE THREAD

**Issue by Evoludo** [linuxmint/Cinnamon#1728]
The body of long and multi-line notifications is shown beside the title, as well as in the normal body of the notification. This is a duplication of information which can be confusing to the user.

Example:
```bash
 notify-send "New e-mail" "someone@example.com: Meet at 3pm\nanother@example.com: Re: your brains"
```
![notifcation_dup](https://f.cloud.github.com/assets/3641963/173972/df142fca-7aef-11e2-8e74-872078eab491.png)

Possibly a more sensible option would be to have either the text beside the title for short messages, as it does now, but not truncating and duplicating for long messages, only having the message body displayed. Or maybe a setting somewhere to choose between the two behaviours.

**Comment by pixunil** [comment]
Also couldn't reproduce this issue with 2.4 and git master.
