### ISSUE TITLE
Idea-extension "Doxpo"-A dock for expo.

### ISSUE THREAD

**Issue by gauravjuvekar** [linuxmint/Cinnamon#1739]
Currently, there's a lot of space on the top and bottom(somewhat taken by the window-to-trash) in expo.

How about adding a dock there. The concept is that you can drag the icons to workspaces to open the application in that workspace. You could also drag windows to a trash-bin like icon on the dock to close them retaining the current window-to-trash option. You could drag the icons of the open windows(top left) onto the dock to add that application.(A sophisticated right-click menu would also be required)

Just putting this idea out there. Would be really great if someone can code this.

PS We can use much code from the other docks out there.

EDIT: An entry in cinnamon-settings might be somewhat better than a right-click menu now that settings has become so awesome.

**Comment by JosephMcc** [comment]
Thank you for your suggestion. See https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html for information on how we handle feature requests.
