### ISSUE TITLE
flickering when running gnome application mail-notification

### ISSUE THREAD

**Issue by joequant** [linuxmint/Cinnamon#1741]
On a AMD catalyst machine, I'm getting flickering when running the gnome application mail-notification

http://www.nongnu.org/mailnotify/

It runs fine, but every time it attempts to put up a notification, the entire screen flickers.  

What seems to be happening is that the distribution sets up a background image.  When cinnamon and nemo start it puts up a different background image, but when running mail-notification or any other applets it flickers back to the distribution image.

**Comment by JosephMcc** [comment]
Closed due to lack of response.
