### ISSUE TITLE
Segmentation fault in cinnamon-settings (cinnamon 1.7.1)

### ISSUE THREAD

**Issue by faidoc** [linuxmint/Cinnamon#1752]
Adding new input sources under keyboard layout generates Segmentation fault (core dumped), no more output from terminal

OS tested: Archlinux and derivatives
Cinnamon: 1.7.1
Cinnamon-control-center: 1.7.1

**Comment by alxbour** [comment]
>>cinnamon-settings display
/opt/lib/libxml2.so.2: version `LIBXML2_2.9.0' not found (required by /lib64/libgoa-backend-1.0.so.1)
Failed to load module: /usr/lib64/cinnamon-control-center-1/panels/libonline-accounts.so
the error persists even after 
sudo dnf install libxml2*

**Comment by leigh123linux** [comment]
@alxbour Have you been playing around with the PATH env? as those paths look wrong.

F28 is working fine here

```
$ inxi -S
System:    Host: localhost Kernel: 4.17.4-200.fc28.x86_64 x86_64 bits: 64 Desktop: Cinnamon 3.8.7 
           Distro: Fedora release 28 (Twenty Eight)
```
```
$ cinnamon-settings display
Using pam module (python3-pampy)
Loading Online Account module
Loading Applets module
Loading General module
Loading Desktop module
Loading Effects module
```

```
$ env |grep PATH
XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session0
PATH=/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/home/leigh/.local/bin:/home/leigh/bin
```
