### ISSUE TITLE
[ENHANCEMENT] system tray toggle

### ISSUE THREAD

**Issue by codec-abc** [linuxmint/Cinnamon#1754]
I wish there was a system tray toggle like in Windows 7 & 8. I really like it because most of the apps in the system tray has no real use most of the time (that's why they only show there). It's better to just show up the system tray icons to access apps in it when necessary instead of continuously wasting space. Moreover most icons here are colorful, which can look disturbing contrasting with monochromatic icons.

**Comment by mahmutelmas06** [comment]
I suggest the idea.
https://cinnamon-spices.linuxmint.com/applets/view/265
https://cinnamon-spices.linuxmint.com/applets/view/293
this kind of applets behaviour could be used in dock. 

For exp. i dont use nvidia-intel switcher applet that much but it is always there and make crowd. so i could show it by a narrow icon and use if i need.
