### ISSUE TITLE
Expo cannot be used strictly from keyboard

### ISSUE THREAD

**Issue by tommysanterre** [linuxmint/Cinnamon#1756]
When launching expo with Ctrl + Alt + Up, it's impossible to select which window to switch to from the keyboard. The user is forced to click on the desired window. It should be possible to select the window by highlighting the currently selected one and changing the selection using the arrow keys. It would also be interesting to be able to type the name of the window to filter which one to switch to. It could also be implemented by putting a number  overlay on each of the window so the user could press that number to switch to the desired window (ordered by last openened window).

**Comment by JosephMcc** [comment]
Thank you for your suggestion. See https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html for information on how we handle feature requests.
