### ISSUE TITLE
Network Manager applet icon does not refresh some times

### ISSUE THREAD

**Issue by LunaticoCR** [linuxmint/Cinnamon#1762]
Hi,

I'm on LM15 32-bit. I've noticed that some times the network manager icon on the Cinnamon panel does not refresh properly. In other words, it does not reflect the actual status the network is in. For example, at the time of writing this I:
1. Laptop was docked so I was connected to wireless and wire
2. I turned off wireless
3. Undocked laptop and plugged a network cable
4. Unplugged network cable and turned on wireless

Right now it is connected but the icon shows it's still connecting.I then logged off and back in and now I'm connected to wireless but the icon says wired.
![screenshot_area_2013-03-01_15:47:19](https://f.cloud.github.com/assets/2124383/210145/926a7130-8287-11e2-8d12-68d89a984f61.png)

Is this known?

I see this quite often as I tend to dock and undock a few times during the day which means that I'm constantly changing from wired to wireless.

**Comment by kenden** [comment]
Is this still happening in Cinnamon 3?

**Comment by geckolinux** [comment]
@kenden Yes. This might be a duplicate bug: #5061 

https://github.com/linuxmint/Cinnamon/issues/5061#issuecomment-245821801

**Comment by Vahan86** [comment]
@JosephMcc, I think this issue is related to network manager applet and should belong here: https://github.com/linuxmint/network-manager-applet/issues

**Comment by JosephMcc** [comment]
Looks like the same as https://github.com/linuxmint/Cinnamon/issues/5061

**Comment by kojimairiguchi** [comment]
doesn't change the icon when I use VPN cisco anyconnect (openvpn), only when I user tunnerbear VPN service
