### ISSUE TITLE
Cinnamon 1.6.7 momentary freezes screen activity on USB disk connection

### ISSUE THREAD

**Issue by VK2BEA** [linuxmint/Cinnamon#1772]
Connecting or disconnecting a USB disk (flash drive etc) causes video activity to momentarily freeze.
To reproduce ... watch a you-tube video or use the mouse to move around a window whilst connecting or disconnecting a USB flash drive. When drive disconnects (usually after a second or two, coincident with the click) the screen will freeze momentarily.

This does not occur with gnome shell on the same system (s).

Is not related to applets (have removed them all)
Verified on multiple Fedora 17 and 18 systems.

**Comment by Vahan86** [comment]
@JosephMcc, tried to follow the steps to reproduce it, but noticed nothing strange. Works fine for me. Tested in Cinnamon 3.0.7.

**Comment by mainmachine** [comment]
This could easily be hardware specific, OP hasn't replied to the 2 year old request to re-test, and no-one else has added their $.02 to this issue; should be closed for any one of those reasons.

**Comment by JosephMcc** [comment]
Closing due to lack of response from the OP.
