### ISSUE TITLE
different background for different workspace

### ISSUE THREAD

**Issue by sujitnag** [linuxmint/Cinnamon#1774]
Now it support customize name for the workspace.
If it support different background for different work place it will be much more effective to identify different workspace.

1st work space background is set by default if specific background is not set for a workspace

**Comment by DirkHaar** [comment]
Different backgrounds per workplace can be done via this little script (found here 
http://forums.linuxmint.com/viewtopic.php?f=219&t=118540#p672189
was for Mint 13, but works still on 17.1, thanks to garalou!):

#!/bin/bash
# Workspace desktop image switcher WDIS 1.0
# Script to change the desktop image when switching workspaces.
# Tested on Linux Mint 17 'cinnamon' 64bit
desktop_dir="/home/username/.cinnamon/backgrounds/" # full path to "username"'s image folder;
# set some pics
desktop_img[0]="earth1.png"
desktop_img[1]="transmission_lost.png"
desktop_img[2]="frak0002.png"
desktop_img[3]="bulb1.png"
# add more images if using more workspaces
setdesktop() {
   gsettings set org.gnome.desktop.background picture-uri "file://$desktop_dir$1"
   }
xprop -root -spy _NET_CURRENT_DESKTOP | (
   while read -r; do
      desk=${REPLY:${#REPLY}-1:1}
      setdesktop ${desktop_img[$desk]}
   done
   ) 
##########################

BUT it would be much nicer if you could also have different sets of icons per workplace, 
e.g. links to manuals, sources and dev tools for your developer workplace,
music, videos and audio software for your creatice workplace ...

**Comment by JosephMcc** [comment]
Thank you for your suggestion. See https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html for information on how we handle feature requests.

**Comment by BugQContri** [comment]
I would formulate it this way:

- Each workspace should be able to get its own, user determined background. 
- Additionally each workspace should be able to host different desklets at different postion.
- This would enable to have a different workspaces for different work at the PC.
- If someone deletes a workspace, it is deleted, and needs to have a complete new customization.

e.g. I am using for each professional project and different private work a different activity in my LM KDE version. I would love to get the same functionality for LM Cinnamon as well. Cinnamon seems to be to be LM's flagship version. 

BTW in XFCE this is enabled already.

I am looking forward to see this enable in Cinnamon.

**Comment by GitHubIsToxic** [comment]
@JosephMcc: all duplicates of this ticket were closed, does that mean this feature request was rejected?
I think the feature request per BugQContri's formulation seems like a good and natural extension of the current Cinnamon multi-workspace & multi-display desktop experience.

**Comment by smurphos** [comment]
@GitHubIsToxic you might be interested in this mint forum thread - https://forums.linuxmint.com/viewtopic.php?f=208&t=304319

**Comment by dacj1s** [comment]
I have a solution for this feature request and wrote up a tutorial on how to implement it.
https://forums.linuxmint.com/viewtopic.php?f=42&t=360221
As you can see, it uses scripts, but I am sure the concepts can be incorporated in an elegant way without some of my hacks.
