### ISSUE TITLE
hot corner not working when full-screen window displayed

### ISSUE THREAD

**Issue by jdtournier** [linuxmint/Cinnamon#1776]
*note: I've already reported this (https://bugs.launchpad.net/linuxmint/+bug/1145771), but not sure that was the right place for, so I'm reporting it here too*

Using Cinnamon 1.7.1 on Arch Linux, with NVIDIA proprietary drivers.

When I have a full screen window on the primary display, the hot corner consistently does not work. Works fine as soon as the window is taken away from full screen. Works fine too for maximised windows, it's only when the window is actually full-screen (i.e. no window decorations or panel, etc). This can be a problem when working on multiple full screen apps across different workspaces (e.g. Inkscape or Blender in one, Virtualbox in the other).

Thanks,
Donald.

**Comment by FlowXP** [comment]
for me Hot Corners are not working at all when youtube/smplayer/vlc/virtualbox is in full screen.
For ex. if youtube is in fullscreen and I move the mouse to the configured corner, nothing happens. In any other situation the hot corners are working fine.
In LM 17.1 this was working perfectly
