### ISSUE TITLE
Relocate Edge Flip option to Workspaces and expand control

### ISSUE THREAD

**Issue by quotidianme2** [linuxmint/Cinnamon#1781]
(This is my first time writing anything here, so I'll apologize in advance for any poor form.)

It seems more logical to have the "Enable Edge flippling" option from the "Window" options menu to the "Workspaces" one --- since edge flipping occurs between and to workspaces.

Also, though I understand a slow-ish default, adding some sliders to the edge flipping function (similar to the ones in xfce) to permit user adjustments to speed of flip, delay till flip, distance till flip, will greatly expand and improve the function.

**Comment by JosephMcc** [comment]
This isn't relevant anymore since the edge flip option no longer exists in the settings.
