### ISSUE TITLE
Updating Desktop names in Desktop Switcher do not update xprop Desktop names

### ISSUE THREAD

**Issue by jameh** [linuxmint/Cinnamon#1786]
Cinnamon 1.6.7, LM 14
Since cairo-dock uses _NET_DESKTOP_NAMES for its switcher, their names do not correspond to Cinnamon's switcher names. It would be nice if they did.

bug report of same issue on cairo-dock:
https://bugs.launchpad.net/cairo-dock-plug-ins/+bug/1125623

Changing the desktop names in Cinnamon's switcher (by using the hot-corner) does not change the output of "xprop -root | grep "_NET_DESKTOP_NAMES(UTF8_STRING)"

**Comment by JosephMcc** [comment]
Closing due to lack of response.
