### ISSUE TITLE
Desktop icon resize doesn't work

### ISSUE THREAD

**Issue by posto** [linuxmint/Cinnamon#1790]
Hi,

I have a big icon from Spring Tools Suite that I'm unable to resize.
I attached the icon for your convenience: https://docs.google.com/file/d/0B7uszI03THGeaWhDMy1wOGFEOHM/edit?usp=sharing

BR,
Dumitru

**Comment by Vahan86** [comment]
@JosephMcc , please see the comment posted above.

**Comment by JosephMcc** [comment]
Looks like a duplicate https://github.com/linuxmint/nemo/issues/145
