### ISSUE TITLE
Request: Set gconf values when setting gtk and icon themes with System/Cinnamon Settings to help qt apps fit in

### ISSUE THREAD

**Issue by AndydeCleyre** [linuxmint/Cinnamon#1793]
When setting the gtk theme, running

```
gconftool-2 --set --type string /desktop/gnome/interface/gtk_theme <name-of-gtk-theme>
```

helps qtconfig/qt apps to emulate the gtk theme.

The same is true for the icon theme and

```
gconftool-2 --set --type string /desktop/gnome/interface/icon_theme <name-of-icon-theme>
```

**Comment by JosephMcc** [comment]
Thank you for your suggestion. See https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html for information on how we handle feature requests.
