### ISSUE TITLE
NetworkManager disconnected - tray icon shows connection

### ISSUE THREAD

**Issue by orschiro** [linuxmint/Cinnamon#1797]
When I disable my wireless connection, the NetworkManager tray icon still shows connected. status.

This error occurs in cinnamon 1.7.2

What error log can I provide you to trace back this issue?

![CinnamonNetworkManagerTrayIcon](https://f.cloud.github.com/assets/170947/257945/0c2a965c-8c7f-11e2-98d0-38f6a0649eda.png)

**Comment by JosephMcc** [comment]
https://github.com/linuxmint/Cinnamon/issues/1762
