### ISSUE TITLE
Cinnamon-screensaver unlock - switch input source with Shift-Caps

### ISSUE THREAD

**Issue by abarysiuk** [linuxmint/Cinnamon#1808]
Unable to switch input source while unlocking screensaver with Shift+Caps combination - dialog detects Caps but not switching itself. So i'm unable to back to my workspace, i have to switch to tty and kill cinnamon-screensaver.

3.8.3-2-ARCH
cinnamon 1.7.2-3
cinnamon-screensaver 1.7.1-4

**Comment by Vahan86** [comment]
@abarysiuk, is this still an issue for you with Cinnamon 3.2?

**Comment by abarysiuk** [comment]
@Vahan86 i don't use it anymore, so i can't say if it's still an issue. I'd rather close it like outdated.

**Comment by Vahan86** [comment]
@abarysiuk, thanks for prompt reply. In this case can you please close it?
