### ISSUE TITLE
Panel menus (main,right-click, context)slightly overlap the top panel but not the bottom.

### ISSUE THREAD

**Issue by 0xnate** [linuxmint/Cinnamon#1815]
http://forums.linuxmint.com/viewtopic.php?f=208&t=129013

**Comment by Vahan86** [comment]
@0xnate, does this issue still occur in Cinnamon 3.0?

**Comment by JosephMcc** [comment]
Closing this. We plan on reworking the menus and the original info linked to is now gone.
