### ISSUE TITLE
Create a Cinnamon SDK

### ISSUE THREAD

**Issue by fcole90** [linuxmint/Cinnamon#1834]
I think that many people would like to create applets, themes, desklets, extensions and other plugins for Cinnamon. I think that creating simple scripts in a package would make things easier. With those scripts you should be able to create a basic folder tree with basical informations shared between various plugins.

Example of usage of the script:
![Terminale_cinn-sdk](https://f.cloud.github.com/assets/1292230/327838/5334b834-9b84-11e2-9dae-5475f5fed574.png)

```
cinnamon-sdk applet myapplet@cinnamon.org
```

(that should create a folder called myapplet@cinnamon.org in /~ containing metadata, applet.js and other basical informations like a readme)

```
cinnamon-sdk doc
```

(that should show some tutorials)

other commands could be :

```
cinnamon-sdk desklet

cinnamon-sdk theme

cinnamon-sdl extension
```

**Comment by JosephMcc** [comment]
Thank you for your suggestion. See https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html for information on how we handle feature requests.
