### ISSUE TITLE
Create more tutorials and guide to use Applet/Theme/Desklet/Extensions

### ISSUE THREAD

**Issue by fcole90** [linuxmint/Cinnamon#1835]
I think that a bottleneck of Cinnamon is the lack of plugin. The more it's easy to produce plugin the more is the people involved and there will be more plugins and more user using Cinnamon. At the moment just a little wiki and a handful of tutorial exists.. I think this is totally insufficient for newbie who just want to make simple apps..

**Comment by dalcde** [comment]
#3186
