### ISSUE TITLE
Idea: Shortcuts to switch directly from EXPO to SCALE

### ISSUE THREAD

**Issue by geoffmen** [linuxmint/Cinnamon#1839]
When we are in EXPO it can be handy to zoom in to a desktop SCALE to better see its apps.
Right now the left-click and right-click do the same thing. Right-clicking could do the switch between

Another intuitive way would be to use CTRL + MouseWheel
CTRL + WheelUP = Zoom in = Expo to Scale
CTRL + WheelDOWN = Zoom out = Scale to Expo

**Comment by JosephMcc** [comment]
Thank you for your suggestion. See https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html for information on how we handle feature requests.
