### ISSUE TITLE
Black screen, only mouse pointer, ubuntu 12.10

### ISSUE THREAD

**Issue by v3ng3** [linuxmint/Cinnamon#1840]
Hi,
I get what's in the title yes. I've done nothing different the last night. I just closed my pc, opened it and nothing was there. I went to tty3 and logged in from there, then used startx to come up with a half-assed interface no bottom bar. I removed cinnamon with purge and re installed. Nothing happened. I used cinnamon --replace, but then I couldn't even see the window manager... Damn search result for "cinnamon logs", is just some cinnamon sticks and recipes for cookies n stuff... gadamn... Tell me where should I search for the logs or if you need the xorg log to send it here.

Respects

**Comment by PatrickScheffer** [comment]
@v3ng3 If I could give you a thumbs up I would give you three. Had this problem also and it was indeed a broken applet. Ironically it was a system monitor applet...

Descending into ~/.local/share/cinnamon/applets and removing it's contents, Cinnamon started up normally. Thank you!
