### ISSUE TITLE
alt+F2 then alt+tab

### ISSUE THREAD

**Issue by lejar** [linuxmint/Cinnamon#1841]
If alt+tab is pressed when the run command dialogue is open (alt+F2), the run dialogue window will lose focus and focus cannot be regained. When this happens, the mouse cannot be used to interact with windows and the screen is greyed out.

Using cinnamon 1.6.7 on Ubuntu 12.10.

**Comment by dalcde** [comment]
It seems to be fixed in Cinnamon master. Can someone else confirm?

**Comment by JosephMcc** [comment]
I'm unable to reproduce this on Cinnamon master.
