### ISSUE TITLE
Cinnamon - Virtual Box issues.

### ISSUE THREAD

**Issue by raymerjacque** [linuxmint/Cinnamon#1870]
When you install the visualization gfx driver for virtual box the start menu icons disappear for some of the tabs ( all applications and i think preference/system system settings as well )

This only happens on Cinnamon 1.7.3, mine is patched to newest build and this bug has been present for a while now.

**Comment by Vahan86** [comment]
@JosephMcc, can we close this issue since there is no response from OP for 2 years?
