### ISSUE TITLE
[Idea] Package desk/applets  separately 

### ISSUE THREAD

**Issue by lockjs** [linuxmint/Cinnamon#1871]
Would it be possible to package applets/desklets separately to the Cinnamon core files for distribution, so you would need to run:

apt-get install cinnamon cinnamon-xlets

in order to install / update both the core Cinnamon files and applets / desklets shipped as part of Cinnamon.

This would allow for applets / deklets to be updated outside the core Cinnamon releases; thinking about pull requests for improving the menu responsiveness and adding new audio players to the sound applet. 

Obviously if applet / desklet updates relied on new features / bug fixes which aren't included in the current stable branch they would need to wait for the stable branch to be updated first.

**Comment by JosephMcc** [comment]
Thank you for your suggestion. See https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html for information on how we handle feature requests.
