### ISSUE TITLE
[Suggestion] Add PulseAudio application-sound controls to the sound applet

### ISSUE THREAD

**Issue by wrouesnel** [linuxmint/Cinnamon#1874]
Windows 7's sound mixer looks something like this:
![](http://i.imgur.com/0zrUKUd.png)

This is a really good concept, because it means you can mute applications or adjust their volume individually. It is _great_ for when you have things with wildly different volume dynamics.

The PulseAudio preferences controller also provides something similar:
![](http://i.imgur.com/draHq0C.png)

But, it's buried on a menu you have to access through about 3-clicks, and it's not a quick 3-clicks. What's really needed is something like this (mockup):
![](http://i.imgur.com/iPwUOpj.png)

Which would bring the sound menu volume controls to the desktop in the same way.

**Comment by mtwebster** [comment]
Implemented as of https://github.com/linuxmint/Cinnamon/commit/05f65cfb4e4cba506a84bd30743b0f3f41f0ddb9
