### ISSUE TITLE
Problems with really big windows.

### ISSUE THREAD

**Issue by gauravjuvekar** [linuxmint/Cinnamon#1878]
A really long widow

![Long windows-2](https://f.cloud.github.com/assets/2271906/391016/4280485a-a755-11e2-9056-894e96a2e19b.png)

The same window just slightly more longer

![Long windows-1](https://f.cloud.github.com/assets/2271906/391014/2e3d4a82-a755-11e2-860d-4a4a6fd46c3b.png)

Doing this with system monitor crashes cinnamon(first a restart, doing it again crashes cinnamon(and muffin)-no window borders/titlebar)

**Comment by Vahan86** [comment]
@gauravjuvekar, is this still an issue in Cinnamon 3.0?

**Comment by Vahan86** [comment]
@JosephMcc, can we close the issue?

**Comment by gauravjuvekar** [comment]
Yeah, seems to be fixed in cinnamon 3.0.7 on mint 18.
