### ISSUE TITLE
Panel shadow visible on secondary screen

### ISSUE THREAD

**Issue by akaIDIOT** [linuxmint/Cinnamon#1885]
The shadow cast by the Cinnamon panel on the primary screen is visible on the second screen positioned on its right:

![panel-shadow](https://f.cloud.github.com/assets/144798/402062/2cb7d93e-a8f4-11e2-84c3-1a497e69a3ad.png)

Although hardly a critical bug, it keeps catching my eye and it's been bugging me :)
Additional information (more can be supplied if needed of course):
- Mint 14 & 15
- Cinnamon 1.6.7 & 1.8.8
- Primary screen resolution: 1920×1200
- Secondary screen resolution: 1680×1050 (rotated counter clock wise, positioned on the right of primary screen)

(My apologies if this has been fixed / has an easy fix in configuration; couldn't find any sources on the webs for Cinnamon (just GNOME+compiz))

( **EDIT**: confirmed for upgraded system as well)

**Comment by JosephMcc** [comment]
I don't think this is  a bug in Cinnamon. The cinnamon theme decides where/if those box shadows get drawn.
