### ISSUE TITLE
Changing sound level and mute on lock screen

### ISSUE THREAD

**Issue by KOLEGA007** [linuxmint/Cinnamon#1900]
When the screen is locked it will be usefull to change sound level (and mute)... Can be added brightness (or some switch in settings, which will make this possible)

**Comment by elrob** [comment]
I would also like to be able to control the volume from the lock screen. Nothing fancy, just let the volume keys work.

**Comment by kali-brandwatch** [comment]
According to https://www.linuxmint.com/rel_rafaela_cinnamon_whatsnew.php this is solved in Linux Mint 17.2 Cinnamon which uses cinnamon-screensaver 2.6.4

However the issue persist on Ubuntu using cinnamon-screensaver 2.8.0 from ppa from http://ppa.launchpad.net/kranich/cinnamon/ubuntu

Is there anything I'm missing?

**Comment by JosephMcc** [comment]
I don't see on that page where it says the volume works in the screensaver. It says the brightness and backlight.

**Comment by kali-brandwatch** [comment]
Totally correct, my bad. I read "multimedia keys" and got all high.

**Comment by JosephMcc** [comment]
These features are now being implemented in the screensaver

**Comment by KR1PTON** [comment]
What is OS ?
