### ISSUE TITLE
[Issue] Pop-up Windows show on top of locked screen

### ISSUE THREAD

**Issue by areynaldos** [linuxmint/Cinnamon#1910]
I've noticed that when the screen is locked and blanked, if any Thunderbird pop-ups show up (like reminders, for example) they are shown over the black screen.

No interaction is possible until the screen is unlocked though.

Anybody seen something similar?

**Comment by nigels-com** [comment]
Cinnamon 2.8.0 (Ubuntu 15.04 x86-64)
![img_20151202_133729](https://cloud.githubusercontent.com/assets/545677/11522202/86269cfe-9900-11e5-8c78-feffc4ef061a.jpg)

**Comment by JosephMcc** [comment]
Was the menu opened when the screen was locked or did you somehow open it with the lock screen active?

**Comment by Vahan86** [comment]
@areynaldos, @nigels-com is this still an issue for you in Cinnamon 3.0.7?

**Comment by JosephMcc** [comment]
I'm going to go ahead and close this. We have other open issues about the screensaver not locking correctly with certain types of popups open, lack of response from the OP, and the fact that the screensaver is completely new in 3.2.
