### ISSUE TITLE
Pop up windows remain on screen even after finishing

### ISSUE THREAD

**Issue by Charles-Mejia-Cruz** [linuxmint/Cinnamon#1912]
The best example I can give is using nemo to extract an archive. The pop up window with the "Extract Archive" remains on top with a blank window even after finishing. Stuff remains clickable underneath that window since I can drag files/folders from underneath around. I think this is a problem with Cinnamon and not Nemo because the problem doesn't occur in Unity.

Using Ubuntu 13.04 with Cinnamon 1.7.4-20130424050019-raring.

**Comment by JosephMcc** [comment]
Closing due to lack of response.
