### ISSUE TITLE
Panel & Taskbar becomes unresponsive after a while [ Cinnamon 1.7.4-2 - Gnome 3.8 ]

### ISSUE THREAD

**Issue by Prozium** [linuxmint/Cinnamon#1934]
I use the classic panel layout, and after a while both the menu and taskbar becomes unresponsive, restarting cinnamon does nothing - the only way is to restart X and wait until it becomes unresponsive again.
Cinnamon version: 1.7.4-2
Gnome version: 3.8

**Comment by tomatolog** [comment]
Cinnamon version: 2.8.6 with Ubuntu 15.10 x64
just found too that ibus-daemon produces such behavior. However I not only killed it but found also that settings of ibus-daemon immediately pop-up issue
"Show icon on system tray" [checked]
"Show the language panel" [Always]

then I switched off
"Show the language panel" [Do not show]

and issue went off

**Comment by robsonvn** [comment]
I had a problem like this one but i'm not sure if it was the same issue. 
My Painel was in Edit Mode and it makes the left click became unresponsive in taskbar. 
Solution : Right click on taskbar and turn the option "Painel edit mode" off.

**Comment by danuamirudin** [comment]
@timvandermeij 
 Hello I'am on Fedora and use Cinnamon for my DE
I dont know where directory to replace the file..
Thank
