### ISSUE TITLE
Cinnamon battery indicator sometimes reports wrong battery percentage

### ISSUE THREAD

**Issue by qammm** [linuxmint/Cinnamon#1964]
I am running LM 14.1 with cinnamon 1.6.7+nadia. Today I observed that sometimes cinnamon battery indicator reports wrong battery percentage. In my case battery indicator says 3% while both acpi and proc filesystem report 53%.

See screenshot:
![screenshot from 2013-05-04 19 58 39](https://f.cloud.github.com/assets/4301945/462845/184332f2-b4e6-11e2-90f1-99e70cd55b7a.png)

Also note that information in Power Settings seems to be wrong, too:
![screenshot from 2013-05-04 20 13 03](https://f.cloud.github.com/assets/4301945/462846/640c464c-b4e6-11e2-9836-d2631ab1220a.png)

**Comment by badarshahzad** [comment]
Would you like to help me I use ibam command it gave me few errors!

![error_ibam_comand](https://cloud.githubusercontent.com/assets/19945367/18774822/4c7034de-8176-11e6-897d-c7b9e2be0bb5.png)
