### ISSUE TITLE
Cinnamon settings displays wrong hardware info.

### ISSUE THREAD

**Issue by gauravjuvekar** [linuxmint/Cinnamon#1973]
Latest master

![workspace 1_027](https://f.cloud.github.com/assets/2271906/466965/eb119140-b669-11e2-821a-eeb09a190585.png)

**Comment by Vahan86** [comment]
@gauravjuvekar, is this still an issue in Cinnamon 3.0?

**Comment by JosephMcc** [comment]
The terminology has changed. The setting is now listed as "Hard Drives". It still shows the combined size of all mounted drives but to me it makes sense now that it does.
