### ISSUE TITLE
[1.8] Desktop icons are misplaced when fullscreen app is launched

### ISSUE THREAD

**Issue by dRaiser** [linuxmint/Cinnamon#1977]
Mint 14, Cinnamon 1.8 from PPA. I use dual monitor configuration. When I switch an application on primary monitor (which doesn't contain icons) to fullscreen mode, icons on second desktop are "jumping" up. They return to their places after switching to non-fullscreen mode or switching to another application.

**Comment by JosephMcc** [comment]
This issue is really old and I can no longer reproduce it on git master.
