### ISSUE TITLE
Notifications cut across the right screen edge.

### ISSUE THREAD

**Issue by gauravjuvekar** [linuxmint/Cinnamon#1987]
Cinnamon 1.8.0 git master LM13
Banshee notification cuts across right screen edge.

Probably due to using an older theme. Close if unconfirmed.

![screenshot from 2013-05-08 18 55 34](https://f.cloud.github.com/assets/2271906/477512/0ba0f47a-b7e4-11e2-8d44-ae419842c091.png)

**Comment by JosephMcc** [comment]
Duplicate https://github.com/linuxmint/Cinnamon/issues/4541
