### ISSUE TITLE
tray icons disappear when you restart cinnamon [Cinnamon 1.8.2-1] [Gnome 3.8]

### ISSUE THREAD

**Issue by Prozium** [linuxmint/Cinnamon#2009]
Tray icons in the panel disappear from time to time, i don't know if this have to do anything when you are restating the shell 
Edit i can reproduce this it hapens most of the times with xchat.
1) Start xchat
2) Restart cinnamon
3) The xchat tary-icon is gone

**Comment by JosephMcc** [comment]
Since no one ever replied to the request by @anandrkris for more feedback on this, I'm going to close it.
