### ISSUE TITLE
Can't assign  xdotool windowminimize $(xdotool getactivewindow) command to hot corner.

### ISSUE THREAD

**Issue by leohardtke** [linuxmint/Cinnamon#2032]
I would like to assign a command to minimize the current windows in the top left corner (ala ElementaryOS), I found that xdotool windowminimize $(xdotool getactivewindow) does the trick from terminal, but it is not working as command for the hot corner... is it fixable, am I doing something wrong? Its really very comfortable to minimize a window without the need to click on a "little" button! :-)
Thanks

**Comment by AntonTymczenko** [comment]
I've found)
you can make a ``` minimize.sh ``` file with this line indise
``` xdotool windowminimize $(xdotool getactivewindow) ```
after that use ```chmod``` to make this file executable:
``` chmod 744 minimize.sh```
and then in "hot corners" write a fullpath to this *.sh* file. in my case it look like this:
``` /home/tymczenko/minimize.sh ```
