### ISSUE TITLE
Show network devices names in Cinnamon panel (as currently it is in MATE)

### ISSUE THREAD

**Issue by ShinDarth** [linuxmint/Cinnamon#2040]
MATE is showing the names of your network devices directly in panel, but Cinnamon does not. It should do it.

For example, I have two devices named "My first network device" and "My network device 2" and MATE is showing them:

http://img41.imageshack.us/img41/5504/networkdevicesmate.png

but if I'm using Cinnamon I can't see their names, just IP addresses.

**Comment by JosephMcc** [comment]
Thank you for your suggestion. See https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html for information on how we handle feature requests.
