### ISSUE TITLE
Java artifacts in Cinnamon 1.8

### ISSUE THREAD

**Issue by fcole90** [linuxmint/Cinnamon#2058]
Using java software like Freemind, Freeplane and Xmind I often experience the appearance of artifacts, like pop-up, which cannot be closed in any way. It's just a visual artifact, because, if I try to click on it, its behavior is like if I clicked on what should be behind it. I solve it by rebooting cinnamon (ALT+F2 -> -r).

**Comment by JosephMcc** [comment]
Closing due to lack of response.
