### ISSUE TITLE
switch user on new cinnamon screensaver missing

### ISSUE THREAD

**Issue by brianjmurrell** [linuxmint/Cinnamon#2059]
In the new screensaver that's included with Cinnamon 1.8 the "Switch User" option is missing from unlock dialog.  It was quite simple to work around however by hard linking /usr/bin/{g,m}dmflexiserver.

This implies that the Cinnamon screensaver, and whole desktop system *requires* mdm rather than gdm when otherwise, gdm appears to work just fine.

Cinnamon should not enforce a login manager that is otherwise functional.  The solution here would be to have the screensaver check for the presence of gdmflexiserver and use that if present along with it's check for mdmflexiserver.

**Comment by Vahan86** [comment]
The "switch user" option is available in lock screen. I can confirm this for Cinnamon 2.4 and newer versions.

@JosephMcc, can we close this issue since there is no response from OP for over 2 years.
