### ISSUE TITLE
Main Menu mouse has no hover or select on sub-menus

### ISSUE THREAD

**Issue by allywilson** [linuxmint/Cinnamon#2067]
Linux Mint RC15 (olivia, x86-64)
Cinnamon 1.8.5 (but affected 1.8.2 and 1.8.3 as well).
Kernel: 3.8.0-21-generic / 32-Ubuntu SMP
Proc: Pentium D 3.40Ghz x 2
Memory: 2.9GiB
Graphics Card: AMD Mobility Radion HD 5430 (not using proprietary driver. xserver-xorg-video-ati v1:7.1.0-ubuntu2)

Click Menu in bottom left corner, move cursor over a sub-menu on the right/middle. Expect it to highlight the entry so it can be clicked - this doesn't happen.

The shortcut icons on the left of the menu can be highlighted and clicked (like shutdown, firefox, nemo, etc.).

By default the "All Applications" is selected in the middle column, and the entries on the right can be scrolled and selected (but the highlight function still not there).

Gentleman named Ricardo Almeida also reported this, but as a comment (twice) on the Cinnamon 1.8 announcement page (http://cinnamon.linuxmint.com/?p=261 - just search for his name)

**Comment by JosephMcc** [comment]
Has this been fixed?

**Comment by JosephMcc** [comment]
Closing due to lack of response.
