### ISSUE TITLE
Translations problem

### ISSUE THREAD

**Issue by giorgiofranceschi** [linuxmint/Cinnamon#2070]
The elements referred to as applets, extensions, themes and desklets are often referred to by variables like "%s" or similar. Translating into Italian (https://translations.launchpad.net/linuxmint/isadora/+pots/cinnamon) I have had several problems with genre (male and female) and the plural form.
Eg., in files/usr/lib/cinnamon-settings/bin/Spices.py the phrase

 "Refreshing index %s"

can be related to the extensions index (feminine in Italian) or themes index (masculine in Italian).

Translating this sentence is not possible to guess the genre. If I would get the masculine article:

 "Aggiornamento dell'indice dei %s"

 "Aggiornamento dell'indice dei temi" (corrected)
 "Aggiornamento dell'indice dei estensioni" (wrong, should be "delle estensioni").

In this case I chose to delete the variable "%s" and translate as:

 "Aggiornamento dell'indice" ("Refreshing index")

I don't know if it works.
I guess the problem is also present in other languages. Years ago, with the Gnome guys, I managed to change a few sentences to make them easier to translate. You can do something for Cinnamon?

Thanks and good luck!

**Comment by Vahan86** [comment]
@giorgiofranceschi, is this still an issue for you in Cinnamon 3?
