### ISSUE TITLE
[Bug] Wrong Time in sound-applet progressbar

### ISSUE THREAD

**Issue by ManIVIctorious** [linuxmint/Cinnamon#2080]
As you see in the Picture the applet thinks the song ran 6:06 minutes of 4:02 minutes.
The 4:02 minutes is the correct length of the song and in rhythmbox it's shown the right way.

http://imageshack.us/photo/my-images/163/bildschirmfotovom201305.png/

**Comment by pixunil** [comment]
The sound applet got some fixes and improvements in 2.6, can you please check?

**Comment by ManIVIctorious** [comment]
Sorry, didn't know this one was still open, this got fixed with cinnamon 2.4
