### ISSUE TITLE
Transparent Windows Menu and Emerald effect theme

### ISSUE THREAD

**Issue by fcole90** [linuxmint/Cinnamon#2083]
http://www.webupd8.org/2013/05/how-to-install-emerald-in-ubuntu-1304.html
I think that the current theme could and should be updated. One thing that many modern desktop share is the chance to have transparency effects on menus and on other tiles.
"Transparent" doesn't mean "impossible to read": a simple shade effect surrounding the words works perfectly.

**Comment by Anti-Ultimate** [comment]
Thanks for changing the title.

I thought it should look somewhere like this:
http://imgur.com/a/HiCBz

But I'd like to know how this would be possible without the application itself doing it. If it were implemented into the window manager like this, only the titlebar would be transparent, without the other things.

**Comment by Vahan86** [comment]
@JosephMcc, can we mark this issue as a feature request?

**Comment by JosephMcc** [comment]
Sure though I don't see it happening.

**Comment by JosephMcc** [comment]
Closing this since it's really outside of what we want to implement.
