### ISSUE TITLE
[Feature Request] Filter/launch applications from Scale and expo views

### ISSUE THREAD

**Issue by ildar** [linuxmint/Cinnamon#2089]
Comparing to G-Shell the Scale and expo views are underfunctional. I.e. pressing keys in these views do nothing.
If no plans on keys here, I'd suggest having possibility to filter-out launched apps/launch apps similar to Gnome-shell behavior.
Might be reasonable to implement this as an extension.
Please?

**Comment by JosephMcc** [comment]
Thank you for your suggestion. See https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html for information on how we handle feature requests.
