### ISSUE TITLE
[FR] implement Per-Window Keyboard Layout (xkb)

### ISSUE THREAD

**Issue by ildar** [linuxmint/Cinnamon#2091]
Exactly this thing: [Per-Window Keyboard Layout](https://extensions.gnome.org/extension/596/per-window-keyboard-layout/).
Strongly needed for international users.

**Comment by JosephMcc** [comment]
This is a duplicate and it seems you guys found a solution that worked for you.
https://github.com/linuxmint/Cinnamon/issues/2409
