### ISSUE TITLE
language and icons get messy after resume from sleep

### ISSUE THREAD

**Issue by LiamDawe** [linuxmint/Cinnamon#2094]
See screenshot: http://img844.imageshack.us/img844/1634/screenshotfrom201305291.png

Look at the Menu text, the two icons near the menu, the notifications icon and then my date, all screwed up, it's usually worse than that. Makes sleeping pointless as I then need to restart :-1:

**Comment by Vahan86** [comment]
@LiamDawe, is this still an issue for you with Cinnamon 3.0?

**Comment by LiamDawe** [comment]
Sorry don't use Cinnamon any more.
