### ISSUE TITLE
[Request] Change PrintScreen to use --interactive

### ISSUE THREAD

**Issue by wchargin** [linuxmint/Cinnamon#2096]
Currently, the PrintScreen keyboard key runs `gnome-screenshot`. This flashes the screen and provides no indication that an image has been saved, much less to `~/Pictures`.

If the command were changed to `gnome-screenshot --interactive` the user would be better able to control the destination.

It would also be nice if the command could be somehow implemented such that the actual screenshot is taken as soon as the user presses the PrintScreen key, but is stored in RAM until the user specifies the location. The same would work with Alt-PrintScreen.

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html
