### ISSUE TITLE
Photo frame desklet should be recursive

### ISSUE THREAD

**Issue by imarkskinner** [linuxmint/Cinnamon#2104]
In my opinion this should be default behaviour but at the very least there should be an option to toggle on/off whether to recurse into the selected folder, 
Similar to the photo frame screenlet of the old compiz widget layer.

**Comment by abatistas1709** [comment]
+1

**Comment by JosephMcc** [comment]
https://github.com/linuxmint/Cinnamon/commit/e5ed95b943e8d33429b36a18fe763ede6b9bd62f
