### ISSUE TITLE
Cinnamon settings is slow to open

### ISSUE THREAD

**Issue by bwat47** [linuxmint/Cinnamon#2107]
I've noticed the new cinnamon settings panel is quite sluggish to open compared to gnome-control-center. gnome control center opens nearly instantly for me even on slower hdd's, while even on my nice samsung 840 pro ssd cinnamon control center takes at least 3 seconds to open, even on a warm start.

Its even slower if you directly open to a sub cinnamon control center item (for example if I click network settings from the cinnamon network menu, it takes like 5 seconds for the cinnamon control center to open)

**Comment by JosephMcc** [comment]
Can we get some more feedback on this in newer Cinnamon versions. The loading speed of the main window is partially dependent on weather on not your icon theme supports the control center icons. For me it is now quite fast when using Cinnamon 2.8 with Mint-X.

**Comment by Vahan86** [comment]
It works fine for me with Cinnamon 3.0 as well.
