### ISSUE TITLE
Show workspace name in scale

### ISSUE THREAD

**Issue by gauravjuvekar** [linuxmint/Cinnamon#2128]
Currently, you can drag the edges in scale to change workspaces but there is no indication that you have dragged if both the workspaces have no windows.

Theres also no indication that you are in scale-it just looks like cinnamon without a panel.

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html
