### ISSUE TITLE
Unexpected frame

### ISSUE THREAD

**Issue by TonyWhite** [linuxmint/Cinnamon#2141]
**What happens**: a frame remains visible on all desktops, you can not activate it with the mouse or keyboard. It is always in the foreground, but the underlying components may be used.

**When:** dispose or hide maximized Java frame

**Workaround**: reboot Cinnamon → open Cinnamon Settings → Effects → disable Unmaximizing windows

**Happens with**: ATI (open and closed drivers) and nVidia (open and closed drivers)

**The bug**
![Image 1](https://dl.dropboxusercontent.com/u/18236517/screenshot/Cinnamon%20-%20Effect%20enabled%20-%20Close%20JFrame.png)

**The workaround**
![Image 2](https://dl.dropboxusercontent.com/u/18236517/screenshot/Cinnamon%20Effects.png)

**Comment by pixunil** [comment]
I think that this bug is resolved, as the window effects were reworked in 2.6.

**Comment by dalcde** [comment]
Closing. Even if it happens again, it would be a different bug.
