### ISSUE TITLE
Menu is slow to appear

### ISSUE THREAD

**Issue by wilecoyote2015** [linuxmint/Cinnamon#2148]
Issue #315 was closed, but users still experience a lag of about 0.5 seconds until the menu applet opens. 

I have tested this on linuxmint 14 with nightly cinnamon.

**Comment by DarekDeo** [comment]
It's very slow. "Configurable Menu" applet, which is fork of original Cinnamon menu fixed it long time ago, their menu opens instantly.

**Comment by Yanpas** [comment]
+1

**Comment by lestcape** [comment]
https://github.com/linuxmint/Cinnamon/issues/4984

**Comment by Vahan86** [comment]
@wilecoyote2015, is this still an issue for you in Cinnamon 3.0?

**Comment by vranki** [comment]
Menu appears instantly on Cinnamon 3.2.7. I think this has been fixed.

**Comment by Vahan86** [comment]
@JosephMcc, can we close this issue?
