### ISSUE TITLE
QuadScreen ATI Cinnamon Crash

### ISSUE THREAD

**Issue by gaby64** [linuxmint/Cinnamon#2153]
Cinnamon Fallback works fine.
Running package generated beta driver from amd for a 7870 Tahiti and 6950, also tested the stable release.
This is on a fresh install of Linux Mint 15

With or without Xinerama, it crashes.

I tried disabling everything on the desktop and it still crashes.

**Comment by JosephMcc** [comment]
Is this still an issue in Cinnamon3?
