### ISSUE TITLE
Can't automate key swap [from Capslock to Escape]

### ISSUE THREAD

**Issue by esn89** [linuxmint/Cinnamon#2154]
In LM15 and Cinnamon 1.8.8, it is not possible to add a start up script to "Start Up Applications"

I can run the script in terminal, manually

It runs in console but never when I reboot.

Tried with gnome-tweak-tools and the change does not take place either.

**Comment by anandrkris** [comment]
@esn89 _ Hi, Is this still an issue?

**Comment by Vahan86** [comment]
@JosephMcc, can we close this issue?
