### ISSUE TITLE
Cinnamon hits bug when restarting/shutting down with Spotify application open

### ISSUE THREAD

**Issue by abrucey** [linuxmint/Cinnamon#2158]
This has been a bug since at least LM14. When I have the spotify application open and I restart/shutdown, the cinnnamon theme looks like the following image and is very slow to shutdown. You will see the theme seems to fail and the icon set in the menu changes.

If I do not have spotify open, then it restarts/shutdown perfectly fine, so I'm assuming it's related to Spotify.

Not sure if any of the devs run Spotify, but you can install it free here to try and reproduce: https://www.spotify.com/us/download/previews/

See image for bug
![screenshot from 2013-06-09 17 14 32](https://f.cloud.github.com/assets/2570389/629068/2c6b7450-d120-11e2-98b4-1374a0e83844.png)

**Comment by Vahan86** [comment]
@JosephMcc, can we close this issue since there is no response from OP for a long time?
