### ISSUE TITLE
Ignored Notifications and configuration settings

### ISSUE THREAD

**Issue by jorgegarciadev** [linuxmint/Cinnamon#2160]
I have pressed by error the button for ignoring future notifications on a network-manager notification. I've been trying to get them back, have searched for a config file, for a solution here in github and google. Even did reset Cinnamon to default settings to get them back without luck.

Could anyone tell me where does Cinnamon store notifications that should be ignored and add somewhere to manage these notifications to the Cinnamon settings panel?

**Comment by kajzersoze** [comment]
So there's still no way to restore it if you disable it by accident ?

**Comment by matthias-johnson** [comment]
This seems like something an unfamiliar user could do accidentally and as such reversing it should be pretty straight-forward. What about having a notification icon in the panel or at least an entry in the menu that allows you to see/create/reset your notification settings?

**Comment by ManIVIctorious** [comment]
Well, I would also like to see more fine grained possibilities to adjust notification settings (ideally per app), but in this case I am pretty sure this is a setting of the network-manager and therefore it is not possible to solve this on cinnamon's side

**Comment by ottercynical** [comment]
Not fixed.  Bad developers.  Too lazy to finish coding a button used literally every single day by every single user.  Laughable.
