### ISSUE TITLE
Easier interface for adding items into the start menu

### ISSUE THREAD

**Issue by ienzo** [linuxmint/Cinnamon#2163]
I find adding items to the Cinnamon menu is not as easy as the Windows or Unity, sorry to say. The way the all programs folder works is that one can just drag a program or shortcut into the folder turns into a shortcut inside the menu.

What I suggest is that in the menu options, one could drag a *.desktop into a section within and then that and the *.desktop would be copied completely rather than copying all the different stats manually into the new .desktop in the menu.

I know this is minor, but it helps new users, much like how easy it is to pin new menu items in Unity.

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html
