### ISSUE TITLE
applet installer needs to understand proxies

### ISSUE THREAD

**Issue by brianjmurrell** [linuxmint/Cinnamon#2172]
I'm using Cinnamon 1.8.8 on Ubuntu Precise.

When I go to the applet manager and select the "Get more online" tab the manager complains:

An error occured while trying to access the server.  Please try again in little while.

Details <urlopen error [Errno 111] Connection refused>

I suspect this is due to the only access outside of this local network to the Internet is via proxy.  I do have my proxy configured however.  It seems the applet manager is just ignoring those settings though and trying to access websites directly.

**Comment by zablotski** [comment]
Hello, 

Is there plans to merge this feature to master?  

BR

**Comment by Reezlaw** [comment]
2019 and I'm still having this problem

**Comment by yutsuo** [comment]
2020 and I'm still having this problem

**Comment by claudiux** [comment]
@yutsuo What are your distro and version of Cinnamon?

**Comment by yutsuo** [comment]
@claudiux 
Cinnamon 4.4.8
Linux Mint 19.3 Tricia 64

**Comment by claudiux** [comment]
@yutsuo Can you access to https://cinnamon-spices.linuxmint.com/json/applets.json using your proxy?

**Comment by yutsuo** [comment]
@claudiux Via browser, yes. If I try wget I end getting a self signed certificate error: 

wget --ca-directory=/etc/ssl/certs/ https://cinnamon-spices.linuxmint.com/json/applets.json                                                            

--2020-02-28 12:54:45--  https://cinnamon-spices.linuxmint.com/json/applets.json
Resolving localhost (localhost)... 127.0.0.1
Connecting to localhost (localhost)|127.0.0.1|:3128... connected.
ERROR: cannot verify cinnamon-spices.linuxmint.com's certificate, issued by ‘[proxy-issued ca]’:
  Self-signed certificate encountered.

Maybe it's just a problem with my proxy certificates. I just find it puzzling that I can do everything but update Mint spices or even update it's cache.

**Comment by claudiux** [comment]
@yutsuo I have the packages `ca-certificates` and `ca-certificates-java` installed. The certificate of https://cinnamon-spices.linuxmint.com is certified by GoDaddy.com, Inc; it isn't self-signed.

**Comment by yutsuo** [comment]
@claudiux roger that! Then it's probably a problem with the way my corporate proxy handles certificates. 

Now we know that it's not a problem with Cinnamon.

Thanks for your time!
