### ISSUE TITLE
[ Feature Request ] Zaphod modes

### ISSUE THREAD

**Issue by Prozium** [linuxmint/Cinnamon#2181]
I use this configuration in my xorg.conf to enable zaphod mode
Section "ServerLayout"
    Identifier     "Layout0"
    Screen 0       "Screen0" 0 0
    Screen 1       "Screen1" 2000 0
EndSection

Why "Screen1" 2000 0 ?
Well because that places screen 1 far away from screen 0 thus jailing the mouse in each screen, i use a script mouse-switchscreen to move my pointer between the screens. This can be useful for eg only playing movies in screen 1

Fluxbox
Openbox
Xfce
etc supports this configuration

However Cinnamon crashes during startup when using that configuration, i would love to have two separate cinnamon desktops, and for some ive spoken to wanted to have have Xfce on screen 1, for whatever needs they have.

I don't know if this is a correct zaphod mode configuration, but as i said it works fine ine fluxbox and xfce.

This might also cause issues with the hotplugging eg a HDMI cable, since right now when a second screen is attached cinnamon automaticly extends the screen.

I hope this is something possible to achieve

**Comment by JosephMcc** [comment]
Zaphod mode isn't going to be supported. I don't think the underlying libraries we use will even allow this.

**Comment by AlbertJP** [comment]
In #776 you suggested a partial fix, that Cinnamon not crash in this mode but instead use only one of the X screens, are you sure you want to close this bug?

**Comment by JosephMcc** [comment]
Unless I'm missing something, I didn't suggest any sort of fix. I closed it because it is a feature request to add support for Zaphod modes, which isn't going to happen. Your correct that it probably shouldn't crash though.
