### ISSUE TITLE
Bluetooth connection options notification

### ISSUE THREAD

**Issue by mgsk** [linuxmint/Cinnamon#2187]
The options I was given when trying to connect a bluetooth device were as follows:

 1. ...
 2. ...
 3. ...

I am torn between 1 (...) and 3 (...). One the one hand, 1 is clearly ..., yet 3 also clearly ....

O' what to do?

...

![...](https://f.cloud.github.com/assets/1708333/675424/2fe60658-d8f1-11e2-8c9d-80b309ea1889.png)

**Comment by ManIVIctorious** [comment]
Is this still relevant on Cinnamon 3.0?

**Comment by JosephMcc** [comment]
Closing due to lack of response.
