### ISSUE TITLE
Inconsistent interaction in system settings

### ISSUE THREAD

**Issue by mgsk** [linuxmint/Cinnamon#2189]
In System settings > Themes, one can double-click a theme to install it, or right-click and select "Apply theme."; in System settings > Desklets, however, one can only right-click to install. The inconsistency is confusing, as being able to double-click to install/do something in one settings area naturally leads you to believe that you can do the same in another (indistinct) interface.

**Comment by anandrkris** [comment]
@JosephMcc - Seems to be a good suggestion, double click applet / desklet should also add x-let?

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html
