### ISSUE TITLE
keyboard shortcut for moving window between monitors

### ISSUE THREAD

**Issue by wulftone** [linuxmint/Cinnamon#2190]
I couldn't find this option anywhere, nor could I find it in the issues.  I'm surprised this hasn't come up!  It would be fantastic to have a keyboard shortcut setting for moving a window between two monitors in dual-monitor mode.  The mouse is hideously slow.  If this isn't the right place to request this feature, please let me know where to do it.

**Comment by keithharvey** [comment]
+1 to TheBacha's suggestion

**Comment by Topperfalkon** [comment]
Is there any plan to implement this? I'd quite like to have this feature, as I often have need to move windows between monitors.

**Comment by rm-richard** [comment]
The Super + Left/Right hotkeys should push tiles to the next monitor when the window is already on the side of the current display. Currently this doesn't happen, and it breaks your workflow if you are used to this feature in KDE or Windows.

**Comment by hesslau** [comment]
please make moving windows between monitors an option!

**Comment by mtwebster** [comment]
The original request is implemented in 2.6.x, any further issues/requests, make a new issue please.

**Comment by tghelere** [comment]
Shift + Windows + arrow

it works!

**Comment by edemir206** [comment]
> If you want @wulftone (or others), at least until Cinnamon maybe add this possibility later, here is the script I personally use for that (found I don't know anymore where on the web):
> 
> NEW LINK —AGAIN—: http://pastebin.com/zjFaRh28
> (updated version again, now fully OK for normal -and- maximized windows ;
> I've never looked more than that to this script content in fact, but was just basic shell script line errors about the maximized support! I fixed that. By the way, you just need to have these 3 tools installed before: xdotool, xwininfo, wmctrl)
> 
> Just edit and adapt these 2 lines at top for your situation (height is managed dynamically):
> — screen width (the effective resolution! just set yours here.) —
> screen_width1=1600
> screen_width2=1920
> 
> Working nice here, at least for my configuration (primary screen at right, secondary screen at left). But else, can be easily adapted if required, even though there is no particular reason for this script to not work in a flipped screen configuration: as long as you've a dual monitor configuration, it should be OK. Hope it'll work for you too then.
> 
> I personally set to trigger this script by setting:
> Command to execute: sh /path/to/move_window_monitor.sh
> Keyboard shortcut: F9
> 
> Pressing F9 will switch the current active window to the other screen. And vice versa if I press multiple times on it so. ;)
> 
> The window size is always kept, but the window position is always set at left of screen in that script —can be enhanced of course—. Not a real problem though according to me.

Thanks for posting this
 
Created an enhaced version of your script: https://github.com/edemir206/dual-monitor-window-switch

It swaps all screens between two monitors.

**Comment by contribucious** [comment]
Nice mate. Thank you for sharing!

> It swaps all screens between two monitors.

all *windows* I guess you meant (but I understood :wink:).
