### ISSUE TITLE
[Feature request] In Scale mode, allow us to move windows (thumbnails) from screen 1 to 2

### ISSUE THREAD

**Issue by contribucious** [linuxmint/Cinnamon#2195]
[EDIT] I mean by drag'n'dropping with the mouse here.

Would be cool to allow us to move windows —for example— from screen 1 (main) to screen 2 (secondary) when in Scale mode. And vice versa.

This will allow us, when we start to have too many windows, to reorganize easily and very quickly all the windows we decide to put on the secondary monitor. And in the Scale mode as it's the "overview of windows mode". We can still however already doing that in Expo mode but not so easy when we've many virtual spaces (as windows preview becoming too little to see/distinguish and review easily and quickly these windows we want to move to the secondary —or even third— monitor).

Maybe already planned or in development, who knows, but… ;-)
In all cases, keep up the good work!
So love Cinnamon, really!
Especially the Expo mode staying as the "old" Mac style rather than the new Mac style (as in Pantheon Shell used by the Elementary distro for example). If one day you decide to change that, please let an option for this current mode, I love this one! ;-)

TECHNICAL INFORMATION:
OS: Ubuntu 12.04.2 LTS (with Cinnamon)
Cinnamon version used: 1.8.8-0ubuntu1~precise1 (stable version)

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html
