### ISSUE TITLE
[Enhancement] In Scale mode, allow us to not show the minimized windows —as on OS X—

### ISSUE THREAD

**Issue by contribucious** [linuxmint/Cinnamon#2198]
Would be nice if we could set the Scale mode to not show the minimized windows, as currently. Only the opened (shown) ones therefore. For information, I use a Dock like on OS X ("Avant Window Navigator").

Maybe already proposed but I did not find anything with a search here.

TECHNICAL INFORMATION:
OS: Ubuntu 12.04.2 LTS (with Cinnamon)
Cinnamon version used: 1.8.8-0ubuntu1~precise1 (stable version)

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html
