### ISSUE TITLE
Launching the Scale mode (bottom right here) should not prevent to Launch the Expo mode (top right here) —as on OS X—

### ISSUE THREAD

**Issue by contribucious** [linuxmint/Cinnamon#2199]
Sometimes, I like to do a global review of everything I opened.
And previously on my OS X, I used to:
1) Launch what you call here the "Scale mode" and 2) after reviewed the current workspace, immediately having a quick look at all the other workspaces too (to see if I left some windows open there) by launching the "Expo mode".

But so, I used to trigger the "Expo mode" immediately after my review of the current workspace, when I'm still in the "Scale mode" in fact.

Here, we can't trigger the "Expo mode" when we're still in the "Scale mode" (to replace the last one by the first one then).
I need to go again with my mouse to "bottom right" one more time to close the current "Scale mode" AND ONLY THEN I can trigger the "Expo mode" at "top right".

The solution can be coded quickly to act as on OS X: simply let the hot corners still acting in the "Scale mode". At least if that'll trigger the "Expo mode" so.
But in OS X, even the "Show desktop" hot corner (bottom left personally) still works/triggers correctly, even when I'm still in the "Scale mode" as you call it you. However, if you don't want to fully let the hot corners acting as normal when in this mode (as the user can have set some specific actions like script triggering about operations on the current opened window or I don't know that act potentially weirdly in this Scale mode, who knows), at least let the hot corners still be OK for YOUR typical hot corner selectable things as you know their behaviors (Expo mode, Show desktop, etc.). At least to have a OS X similar experience about that therefore. ;-)

TECHNICAL INFORMATION:
OS: Ubuntu 12.04.2 LTS (with Cinnamon)
Cinnamon version used: 1.8.8-0ubuntu1~precise1 (stable version)

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html
