### ISSUE TITLE
[Enhancement] In Scale mode, add basic keyboard controls (Ctrl+w / ENTER) for the thumbnail/window we've below our mouse cursor

### ISSUE THREAD

**Issue by contribucious** [linuxmint/Cinnamon#2205]
As discussed with @autarkper in an other discussion/issue, the logical behavior he has implemented for the zoomed mode (in Scale mode) can be extended more globally for the Scale mode.
## 
## So, here is the interesting part of our discussion about that, starting with my reflexion:

Oh… and yeah, as we still talk about that, even if not in the zoomed mode anymore (but still in the Scale mode), I think that we should keep this logical behavior more globally, I mean:

In Scale mode, we never need to act (ALWAYS and ONLY) on the active (foreground) window of the desktop.
So, as soon as the mouse cursor hovers a thumbnail AND SHOW CONTROLS ON IT (Close icon, etc.), and especially if it's a large thumbnail when we don't have many windows opened, we're led to think that our keyboard will ALSO act on that.

At least for the classic controls:
Ctrl+w -> closing
Enter -> selecting to be the new active (foreground) window of the desktop.

It's like the duck shooting:
1) you aim the target with your mouse (right hand often) to let the controls appear on that window
2) you shoot with your keyboard (left hand often): ctrl+w (closing) or ENTER (selecting)

Logical too IMHO. What do you think about that autarkper?

> > > Originally posted here:
> > > https://github.com/linuxmint/Cinnamon/issues/2196#issuecomment-19861984
## 
## Followed by his response:

@contribucious: I agree that it makes sense but I think there would have to be some more logic to avoid changing the selection while the mouse travels from its initial position to the target window, and that can become quite complicated. I use the mouse very sparingly so I shouldn't be the one to decide, though. I suggest you open a separate issue and see what people say.

> > > Originally posted here:
> > > https://github.com/linuxmint/Cinnamon/issues/2196#issuecomment-19863458
## 
## But you…

…what do you think about this behavior? Is that behavior makes sense for you too? Let us know! ;-)

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html
