### ISSUE TITLE
Cinnamon volume control does not detect or affect USB Soundblaster Recon3D

### ISSUE THREAD

**Issue by aoighost** [linuxmint/Cinnamon#2206]
Cinnamon's volume control does not detect or have control over the volume of the USB Soundblaster Recon3D. The soundcard does not show up in the list, and the volume control does nothing to the volume using the sound card.

**Comment by pixunil** [comment]
Which volume control do you mean (cinnamon-settings or in the sound applet)?
There were some changes in the sound applet which should fix issues like that if it works in cinnamon-settings. (Cinnamon 2.5 | git master)

**Comment by Vahan86** [comment]
@aoighost, is this still relevant in Cinnamon 3.0?
