### ISSUE TITLE
[Enhancement] In Scale mode, add more "highlighting" for the selected window —as on OS X—

### ISSUE THREAD

**Issue by contribucious** [linuxmint/Cinnamon#2209]
In Cinnamon (1.8.8 stable at least), there are no way to determine the selected window other than by the little close icon shown. And in fact, it's even not totally true, because it's valid if we only use the keyboard (arrow keys), but if we use the mouse, the hovered window ALSO have these controls but is NOT the selected one, i.e. typing ENTER will not select that one for example (which is also a problem reported by the way: when using the mouse, make the hovered window becoming the selected one, as on OS X). In all cases, even if using the keyboard only, more "highlighting" will be welcome I think, therefore.

Here is what Apple has chosen to do in OS X 10.5 and less:
http://i.imgur.com/i3BgDh6.jpg (image from the web)
=> But still a problem: too many highlighting and therefore, we can't see clearly the content of the window. Especially as, in addition, the window name is in the middle of the window.

Here is, then, what Apple has chosen to do in OS X 10.6 and more:
http://i.imgur.com/hThmGuO.png (screenshot of my server)
=> Better! We still see correctly the window name, we better see the content of the window, and the highlighting is still very visible (to let the user know —and quickly in addition— the window currently selected).

What about doing an outline (bold like that) in Cinnamon too? Or at least, a more visual system to better inform the user of the currently selected window, in Scale mode?

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html
