### ISSUE TITLE
[Enhancement] In Expo mode, when a close icon appears on a window, we should be able also to middle-click on the thumbnail to close that window

### ISSUE THREAD

**Issue by contribucious** [linuxmint/Cinnamon#2210]
In a way to better uniformize Scale/Expo user experience, I think that in the Expo mode, we should be able to middle-click on a thumbnail/window to close it, when the close icon appears (when we hover a thumbnail/window). As in the Scale mode.

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html
