### ISSUE TITLE
filter to recent documents

### ISSUE THREAD

**Issue by timmie** [linuxmint/Cinnamon#222]
please add filters to the recent documents such as:
- file type (text, calculation, etc.)
- modification time

**Comment by JosephMcc** [comment]
Thank you for your suggestion. See https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html for information on how we handle feature requests.

**Comment by mscheper** [comment]
@anandrkris: Thank you, but the 'Privacy' feature doesn't seem to offer any filters; it merely enables and disables recent documents. A series of rsync-like include and exclude GLOBs would make 'recent docs' a hundred times more useful.

**Comment by smurphos** [comment]
@mscheper Curation of recents depends on context of access to them.  E.g. if you right click on a pinned app in the grouped window list you'll get a subset of the recents for which that app is the default.
