### ISSUE TITLE
[cinnamon 1.8.8-1] two-finger scrolling is not working

### ISSUE THREAD

**Issue by Prozium** [linuxmint/Cinnamon#2228]
Hey iam speaking on behalf of a friend who cannot get two-finger scrolling to work in cinnamon-settings when choosing two-finger scroll it simply ignores that setting however enabling edge scrolling seems to work

i am pasting the output from /proc/bus/input/devices

I: Bus=0011 Vendor=0002 Product=0007 Version=01b1
N: Name="SynPS/2 Synaptics TouchPad"
P: Phys=isa0060/serio4/input0
S: Sysfs=/devices/platform/i8042/serio4/input/input16
U: Uniq=
H: Handlers=mouse0 event16
B: PROP=1
B: EV=b
B: KEY=420 30000 0 0 0 0
B: ABS=11000003

just ask if you need any more info

**Comment by CottonEaster** [comment]
Compare #2459.
