### ISSUE TITLE
[Enhancement] Menu package Suggestion [MATE like]

### ISSUE THREAD

**Issue by RaedsLab** [linuxmint/Cinnamon#2231]
I loved the menu package suggestions while searching in MATE menu , and I'd love to see that in the  Cinnamon menu as well.

you search a word , and if there is a package you didn't install for it , is suggests it easy.  
[FEATURE REQUEST]

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html
