### ISSUE TITLE
Large gap between an icon clicked and the menu shown

### ISSUE THREAD

**Issue by contribucious** [linuxmint/Cinnamon#2236]
In many programs, when using Cinnamon, I've a very large gap between the icon clicked and the menu shown.

Here (cf. screenshots below) with the music player Tomahawk (uses QT) but also with the Twitter client Birdie (uses GTK+ 3) for example. So, it's a more general problem.

Also have this problem on some other desktop environments though.
But not with the combination of XFCE+Compiz I noticed.

TECHNICAL INFORMATION:
OS: Ubuntu 12.04.2 LTS (with Cinnamon)
Cinnamon version used: 1.9.1-20130706040307-precise
(nightly build version from this PPA: https://launchpad.net/~gwendal-lebihan-dev/+archive/cinnamon-nightly ; but was also there in the stable version 1.8.8)
Screens configuration: Nvidia twinview mode, with Secondary screen at left (1600x1200) and Primary screen at right (1220x680 using ViewPortOut, so 1280x720 with overscan ; even if the native resolution of this monitor is 1920x1200)

See screenshot took on my Primary screen (1220x680 at right):
![001](https://f.cloud.github.com/assets/4764956/758484/672e50ea-e736-11e2-9803-debe78192e69.png)
=> Note that I also have this large gap when right clicking on the systray icon of Tomahawk.

[EDIT] And… see screenshot took on my Secondary screen (1600x1200 at left, so 4/3 monitor here):
![002](https://f.cloud.github.com/assets/4764956/758520/cff6a64c-e739-11e2-907e-1acfe158d4e8.png)

**Comment by Wxnzxn** [comment]
I have this problem on Cinnamon 2.6.13 - for me, it only happens in windows on my primary monitor that are bigger than the resolution of my secondary monitor. It also does not happen with all problems, one example is Git Cola, and also several windows programs run in wine.

**Comment by Vahan86** [comment]
@contribucious, is this still an issue for you with Cinnamon 3.0?

**Comment by MKYounis** [comment]
hello, 
i know it is like 4 years after but i have the same issue and i need to know if there is a fix.
