### ISSUE TITLE
Cinnamon crashes when in a virtual terminal

### ISSUE THREAD

**Issue by jepst** [linuxmint/Cinnamon#2237]
When switching to a virtual terminal (with Ctrl-Alt-Fx), cinnamon will crash if I don't switch back within approximately 10 seconds. Switching to a virtual terminal and staying there for a period of time will reliably crash cinnamon, resulting in the message "Do you want to restart cinnamon? You are currently in fallback mode."

When crashing due to this bug, cinnamon emits the following message:

`(cinnamon:15704): Cogl-ERROR **: Failed to create an OpenGL framebuffer object
Trace/breakpoint trap`

This also sometimes happens when returning from suspend mode. The underlying cause may be the same.

Using Mint 15 with 3.8.0-26-generic and nvidia drivers.

**Comment by Vahan86** [comment]
@jepst, is this still an issue for you with Cinnamon 3.2?

**Comment by leigh123linux** [comment]
This was never a cinnamon issue.
