### ISSUE TITLE
Application Menu doesn't clear properly

### ISSUE THREAD

**Issue by nimdahk** [linuxmint/Cinnamon#2238]
When moving the mouse quickly through the menu, while on a theme that did not come with the ISO, "overlap" sometimes happens.

There is no definite reproduction method, but simply opening the menu and moving your mouse up and down over the categories quickly will soon produce the bug.

System specs:
- Intel i7-2670QM
- Linux Mint 15
- Cinnamon (obviously)

Affected themes:
- SmoothPurple
- Minty
- ICS
- Hacktivist
- (and ALL the other third-party themes)

Unaffected themes:
- Linux Mint
- Cinnamon

![menu cropped](https://f.cloud.github.com/assets/1014628/759122/3fc0c544-e775-11e2-8fe8-8d87a678a87a.png)

**Comment by Vahan86** [comment]
@nimdahk, is this still an issue for you in Cinnamon 3.0?

**Comment by JosephMcc** [comment]
This doesn't look like a Cinnamon bug. The problem looks to belong either in the underlying libraries that Cinnamon is using or in the themes.
