### ISSUE TITLE
When installing Spices, point out gksu is missing

### ISSUE THREAD

**Issue by MRudolph** [linuxmint/Cinnamon#2243]
Installing spices, which require installation of a setting schema, requires having installed gksu. Otherwise, it fails with the unspecific message

> Could not install the settings schema for %s.  You will have to perform this step yourself.

source: https://github.com/linuxmint/Cinnamon/blob/master/files/usr/lib/cinnamon-settings/bin/Spices.py#L423

Missing gksu (besides the installation script, which is part of cinnamon) is the only reason for this message to show up. So it would be reasonable to point this out to the user.

I'm opening this here because i don't know if it should be fixed in the Python source or if it should just be fixed in the translation files.

**Comment by leigh123linux** [comment]
Spices uses json schema in ~/ so this is no longer an issue.
