### ISSUE TITLE
vpnc through NetworkManager fails to connect

### ISSUE THREAD

**Issue by kpj104** [linuxmint/Cinnamon#2254]
Using a vpnc connection through NetworkManager fails to connect.  When I log into gnome3 I am able to use the same exact profile.  Here is the error I'm getting when I try and connect:

Jul 11 18:01:40 linuxlaptop NetworkManager[1146]: <info> Starting VPN service 'vpnc'...
Jul 11 18:01:40 linuxlaptop NetworkManager[1146]: <info> VPN service 'vpnc' started (org.freedesktop.NetworkManager.vpnc), PID 12918
Jul 11 18:01:41 linuxlaptop NetworkManager[1146]: <info> VPN service 'vpnc' appeared; activating connections
Jul 11 18:01:41 linuxlaptop NetworkManager[1146]: <error> [1373580100.994791] [nm-vpn-connection.c:1374] get_secrets_cb(): Failed to request VPN secrets #2: (6) No agents were available for this request.

I wasn't sure if it had something to do with keyring, but I thought cinnamon used the same keyring as gnome and gnome is working.  

Can someone help me work through this?  Thanks

**Comment by Vahan86** [comment]
@kpj104, is this still an issue for you in Cinnamon 3.0?

**Comment by Vahan86** [comment]
@JosephMcc, can we close the issue?
