### ISSUE TITLE
Unexpected behavior when dragging a window to top to maximize from screen 1 to screen 2

### ISSUE THREAD

**Issue by contribucious** [linuxmint/Cinnamon#2258]
In a dual-monitor configuration, when you drag a window from one screen to the top of your other screen to maximize it (option *tile-maximize* enabled needed if using the nightly build version), as long as you hold the left-click, you'll see the light background color to indicate you that the window will be placed there. Right.

But in fact, even with this indicator on the destination screen (right for example), the window can sometimes be maximized... on the screen where the window was initially dragged from (left from example).

**The problematic reason of this happening?**

Let's take a situation where we drag from screen 1 (left) to screen 2 (right), even if the opposite have the same behavior (just invert all the actions).
It happens if the dragged window is dragged to the top (at the "very" left) of screen 2 and that the window is still MAINLY located on the screen 1, and only visible for a part on the screen 2. In this situation... it'll become maximized on the *left* screen (which is not the intended behavior of course, as... dragged to top of *right* screen ; nor is the behavior indicated by the light background color shown on the *right* screen for the destination of the window). Cf. screenshots below.

**On a dual-monitor configuration (with Nvidia TwinView mode used):**

1. I drag a window from my left screen (screen not visible here) to the top of my right screen (my mouse cursor hits the top at the top left, near the left of the "1" of the Workspace Switcher applet). The window is still mainly on my left screen, but the hint (light background color for the destination area) let me thing, logically, that it'll be maximized on the right screen as asked.
![1](https://f.cloud.github.com/assets/4764956/793988/cd9717d4-ec5b-11e2-8b5f-13ea4c1efc95.png)

2. Here is the unexpected result: the window becomes maximized on the left screen (rather than right one), i.e. the screen where the window was initially dragged from.
![2](https://f.cloud.github.com/assets/4764956/793991/4f24e952-ec5c-11e2-9de8-4edaa3ed15eb.png)

**Comment by ManIVIctorious** [comment]
I can't reproduce this here, is this still an issue for you in cinnamon 3.0?

**Comment by Vahan86** [comment]
@JosephMcc, can we close this issue?
