### ISSUE TITLE
Hot corners only working on the primary monitor

### ISSUE THREAD

**Issue by contribucious** [linuxmint/Cinnamon#2263]
Maybe a desired behavior, but IMHO, hot corners should work on all monitors.
Or, at least, if you want to consider all the screens as "1", then having top-left and bottom-left on the leftmost monitor, and top-right and bottom-right on the rightmost monitor.

Especially considering that, if your two monitors have the same height resolution, and that your main monitor is the right one, you can't\* trigger the top-left nor the bottom-left corner. Because it's like a big rectangle and you're at the middle. You can try to shift a little bit one monitor to the other in height (in settings), but it only resolves the problem for one corner anyway (top-left or bottom-left). And also... your windows will not be anymore _nicely_ transferred between monitors because of a height shift.
- [_] In fact, for the top, it can still work (here, not the *same_ height between my 2 screens on my configuration but less height for my right main monitor; but so... same considerations anyway therefore):
  ![1](https://f.cloud.github.com/assets/4764956/798748/54dad7c4-ed67-11e2-9ccc-a09a2df382c9.png)
  (my main monitor is at right, the 24", running here in a small resolution because of overheating else... due to a hardware problem ^^ ; so running at 1220x680 instead of 1920x1200 -> the hot corners problem is the same in both resolutions here anyway)

**Comment by Vahan86** [comment]
@JosephMcc, can we mark this issue as a feature request?

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html
