### ISSUE TITLE
Bug in the Expo mode: redraw for windows position done only after a mouse move

### ISSUE THREAD

**Issue by contribucious** [linuxmint/Cinnamon#2266]
Detected a bug in the Expo mode after moving a window from screen 1 to screen 2: redraw for windows position is done only after a mouse move —even a very small one as in the video below—.

**Screens configuration:** Nvidia TwinView Mode, 1600x1200 at left / 1220x680 at right.
**Muffin version:** 1.8.2-20130716003005-precise (nightly build from today)
**Cinnamon version:** 1.9.1-20130716040308-precise (nightly build from today)

See http://youtu.be/pfXQm92lDSw
_(the flashing blue lines in this screencast shown sometimes are due to a well-known problem of nvidia proprietary driver + screencasting)_

**Comment by Vahan86** [comment]
@contribucious, is this still an issue for you in Cinnamon 3.0?

**Comment by Vahan86** [comment]
@JosephMcc, can we close the issue?

**Comment by Vahan86** [comment]
@JosephMcc, can we close this issue?
