### ISSUE TITLE
Text and Graphics become unreadable

### ISSUE THREAD

**Issue by incinirate** [linuxmint/Cinnamon#2267]
Hi, my linux text and menu has become squares of color, it is at the bottom of this picture, in the menu as well but i cant take a screen shot of that http://imgur.com/lvZOh6Q Any help is appreciated! BTW im using a NVIDIA GeForce 9600 GT graphics driver driver version 304.51

**Comment by Vahan86** [comment]
@JosephMcc, there is no response from OP for a long time, can we close the issue?
