### ISSUE TITLE
Desktop Icons rearrange on reboot/boot up

### ISSUE THREAD

**Issue by MeshWeaver** [linuxmint/Cinnamon#2271]
So I've recently switched back to Cinnamon from Mate, and 1.8 is great. However, I'm having an issue where every time I boot up my PC or reboot, all my desktop icons (about 20-30) auto-rearrange. Almost like when you sort them by name, only in random order - and all bunched together on the left side of my main screen. The main icons (computer, home, trash, etc) also get offset to the right, oddly enough.
I've looked it up and it seems a few others are also having this problem - apparently it could be when the monitors start up they aren't at their full resolution, so the icon positions get messed up.

Is there a fix for this already? Or maybe it's on the to-fix list?
(I went through 10 pages of open issues before creating a new one, couldn't spot anything related)

**Comment by cdosborn** [comment]
Here's a link to that [ticket](https://github.com/linuxmint/nemo/issues/358)
