### ISSUE TITLE
Cinnamon need an auxiliary thread.

### ISSUE THREAD

**Issue by ghost** [linuxmint/Cinnamon#2278]
Cinnamon only contains a process that is shared by all. When an applet, extension, or desklet need to extract information from a specific command. Say it is wodim, there are several ways to do this.

1 - The most natural is to run synchronously: let [res, out, err, status] = GLib.spawn_command_line_sync (command); But if the wodim command, is busy trying to read the optical device, all Cinnamon crashes.

2 -  The second way is to redirect the command output to a file asynchronously and then read in a synchronous way, when this is ready. However, if something needs to be done continuously, i would not be in the place of the poor hard drive's.

3-   The third way that occurs to me is that, Cinnamon have a global variable in the environment, which redirect the command output and that can be accessed later from another call to bash or the Cinnamon own. It really seems confusing this idea, since this variable should allow subcontexts for different desktop component, not fighting for it. 

4-The latter form seems the most logical and healthy. Cinnamon need to contains a separate process to the desktop, to wait for synchronous calls  to bash, and when these calls are met throw an event to be captured the containing information command output.

Thanks.

**Comment by glebihan** [comment]
@lestcape : see Util.spawn_async, which should now do what you want (using DBus as a backend).
https://github.com/linuxmint/Cinnamon/commit/a1639083e2ae2f55cc25d4534216145ef3f11feb

**Comment by lestcape** [comment]
Upss... You also see this... yep... You have right about the performance... Is a good point... Again thanks.

**Comment by lestcape** [comment]
@glebihan, how we can handle the python module that we could need to do things like that? I think that cinnamon can not handle all dependency of the current examples... Could be possible create a callback to the search provider when the extension is installed, to handle python dependencies using pip and add to cinnamon just the dependencies from python-pip? If the extension not need to install anything could decide omit the callback... Possible this could be implemented searching for an specific setup-file on cjs or python (setup.js setup.py).
