### ISSUE TITLE
[2.0/Tracker] Our date/time story sucks

### ISSUE THREAD

**Issue by mathrick** [linuxmint/Cinnamon#2310]
Setting date and time in Cinnamon is a disaster area currently. It's insanely hard to get it to show consistently throughout places, it doesn't respect the locale without a lot of manual work, the UI for setting it is just awful and difficult to navigate even for programmers, and 90% of the settings should not exist in the first place.

This bug should track all the issues related to getting it fixed. Specific bugs include: 
* ~~#2126~~ → linuxmint/cinnamon-screensaver#21
* #1966

**Comment by ManIVIctorious** [comment]
The locale settings have been reworked about two years ago.
@JosephMcc could this be closed?
