### ISSUE TITLE
Menus unusable when using java program

### ISSUE THREAD

**Issue by LiuGaofneg** [linuxmint/cinnamon#2318]
- when you click on a menu, it disappears as soon as you release the
  mouse button.
- when holding the mouse button and drawing along the menu (from File to
  Edit for instance), nothing happens (the File menu remains opened the
  Edit menu is not visible).
- when dragging further on the right, the Edit menu is finally
  displayed.
- It is almost impossible to select an item in the menu and when it
  finally works, you cannot select a sub-menu item

This problem is not resolved consistently by using sun-jre.

similar with user report in Ubuntu Bug #777425

https://bugs.launchpad.net/ubuntu/+source/openjdk-7/+bug/777425

**Comment by JosephMcc** [comment]
Can this still be reproduce in Cinnamon 2.8?

**Comment by salouma1** [comment]
Yes I noticed similar problem with Jmenu with cinnamon 2.8

**Comment by Vahan86** [comment]
@LiuGaofneg, is this still an issue for you with Cinnamon 3?

**Comment by LiuGaofneg** [comment]
@Vahan86 I am sorry, I do not have the test environment now ,Thanks for your care.

**Comment by Vahan86** [comment]
@JosephMcc, can we close this issue?
