### ISSUE TITLE
Progress bars in taskbar items & notifications for complete tasks

### ISSUE THREAD

**Issue by wulftone** [linuxmint/Cinnamon#2328]
Two features:

1) One feature I really like out of Windows is that you can see progress bars on any window (focused or unfocused) in the taskbar item for that window.  What are people's thoughts on including this feature in Cinnamon's taskbar?

Here's an example:
![clipboard05](https://f.cloud.github.com/assets/142784/925187/52c95e18-ff75-11e2-9750-f4d85c9c592e.png)

The advantage should be obvious... If I'm doing something else, I don't have to split my screen up just to notice the progressbar--it's right there all the time.

2) The other part of this is if I'm on a different desktop, I'd at least like a notification bubble for whenever my progress (whatever progress that may be) is complete.

Thoughts?

**Comment by TurkeyMan** [comment]
I'm really interested in this feature too. I'm sorry, I didn't understand the answer, who does this need to be addressed towards to put primitives in place that it may be supported?

**Comment by lestcape** [comment]
@TurkeyMan Maybe I'm wrong, but i think there are not an standar Dbus APi (or something similar) to export the status of a progress bar from a generic application. So, the only way that i think could be made an attempt to retrieve the progress is if you used X, but if the app have several progress bars, then you can not known the principal one.

**Comment by TurkeyMan** [comment]
Do you think there's a way to improve this situation in Linux? Where should it be improved?

**Comment by lestcape** [comment]
I consider the support need to be inside kde or gtk (but really for both). I think there are no way now, but is possible create a way to register a generic application progress, but i consider impossible the support of current and oldest version of (kde/gtk) that now are without support. Also for historical reasons, Gtk and Kde always they take different directions and are pretty important in the linux eco-system.

I really don't think that a magical solution could be appear right now, but also if appear (in my fantasy world), this will take a lot of time to be possible the usage in the most common programs.

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here. This is already implemented to some extent for things that will support it.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html
