### ISSUE TITLE
Possible issue with popups/notifications and Skype

### ISSUE THREAD

**Issue by psych** [linuxmint/Cinnamon#233]
I believe there might be an issue with Skype and Cinnamon, possibly to do with the way notifications are displayed. I'm not too sure about this though and can only report what I see. 

In Cinnamon 1.2 (this didn't happen in 1.1.3) whenever messages are received in Skype and Skype is minimized, Skype comes to the forefront for me and jumps on top of all other open windows. Obviously this isn't behavior we want. In Cinnamon 1.1.3 a notification Window was displayed in the top right, as I recall, if that option was set in Skype. This is ideal behavior. In Gnome Shell Skype also behaves correctly and a notification top center appears telling me a new message is received. 

I've tweaked the chat and notification settings in Skype to just display a notification and not display anything at all. Either way, Skype comes to the forefront. 

Skype should not be coming to the top and I believe it might have something to do with notifications if something was changed on the back end of Cinnamon between 1.1.3 and now, because it did used to work well.

Anyone else seeing this?

**Comment by 00gavin** [comment]
Substituting Pidgin for Quassel in /usr/share/cinnamon/js/ui/windowAttentionHandler.js was the fix for me.  Cheers!

**Comment by cavebeat** [comment]
hi,
i have the same problem. 
every cinnamon update the file /usr/share/cinnamon/js/ui/windowAttentionHandler.js is resetted to upstream values. 

i'd need two more Entries to suppress the stealing of Autofocus: Psi+ and RetroShare

I have created the following Pull-Request. 
https://github.com/linuxmint/Cinnamon/pull/4801

**Comment by densha** [comment]
Any updates on this? 3 years later, this is still an issue with the latest version of Linux Mint.

**Comment by lgoebkes** [comment]
I can confirm that this is still an issue with Telegram. Are there any updates on this matter?
