### ISSUE TITLE
Mouse attraction / snap / magnetization on default button

### ISSUE THREAD

**Issue by sangorys** [linuxmint/Cinnamon#2337]
Hello,

the idea is : the mouse is automatically moved to the default button of a dialog box.

This feature exists since Windows 95, but I never met it in any Linux distribution.

Ex: I delete a file in Nemo. Then a msg box appear to confirm the delete action. There is 2 buttons : once for OK and the default button is No (default button means if you type Enter in your keyboard, then the default button is pressed). The idea is that the mouse is automatically moved to the default button. Then it is a lot quicker to answer to message box.

For your information, I have put the Mouse pannel of Windows control panel.

Thank you

Regard
![mouse snap](https://f.cloud.github.com/assets/544194/943993/5688b624-028c-11e3-87a5-b86a45bd9c2e.png)

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html
