### ISSUE TITLE
Automatically allow Cinnamon to scale icon text and icons

### ISSUE THREAD

**Issue by Jesse-V** [linuxmint/Cinnamon#2346]
I propose that Cinnamon change the defaults on two of its panel settings:
1) automatically uncheck "Use Customize panel size."
2) automatically check "Allow Cinnamon to scale panel text and icons according to their size."

Changing these makes such a visual difference that it's one of the first things I do when the Cinnamon desktop first appears for Mint or another distro. I must first check the "use customized panel size" setting, then check the "allow Cinnamon to scale..." setting, and then uncheck the first setting. When this is done, the panel-bar suddenly becomes very neat and well-positioned. It looks so much more professional, and I would strongly recommend that these settings become the default.

**Comment by Vahan86** [comment]
@JosephMcc, can we mark this issue as a feature request?

**Comment by JosephMcc** [comment]
I'm closing this. Themes decide how they want to look. Those options are there so the user can override it to an extent.
