### ISSUE TITLE
Steam notifications go behind the panel

### ISSUE THREAD

**Issue by LiamDawe** [linuxmint/Cinnamon#2357]
So references this issue which was closed: https://github.com/linuxmint/Cinnamon/issues/1074#issuecomment-23231619

It still happens in the latest Cinnamon on Ubuntu as confirmed by another users in that bug report. Can someone re-look at it, it's extremely annoying.

**Comment by mixedCase** [comment]
I can reproduce this issue in KDE Plasma 5.2, except notifications display over my taskbar instead of behind it.

And the issue only occurs in a multi-monitor set-up, a margin is established if on a single-monitor set-up.
