### ISSUE TITLE
guake terminal does not start at log-in

### ISSUE THREAD

**Issue by timmie** [linuxmint/Cinnamon#2364]
guake terminal is in me start-programmes.

But it does not start when I log into Cinnamon.

**Comment by sayanriju** [comment]
As of today, it _is_ still an issue.

I've just moved on to Cinnamon from LXDE on a (L)Ubuntu 14.04 system, and Guake doesn't autostart as expected. Further, I can confirm that guake auotstart works as expected with KDE & vanilla Openbox  as well.

FWIW, I've managed to side-step the issue by disabling the "Enable popup notifications on startup" in Guake's preferences. 
Probably, there is a lag in the Cinnamon notification system at startup. Guake tries to put up a notification while the system is not yet ready, and silently fails to start at all!

**Comment by JosephMcc** [comment]
Have you tried setting a startup delay time for guake in Cinnamon Settings->Startup Applications?

**Comment by sayanriju** [comment]
@JosephMcc Nope. Since I managed to side-step the issue as mentioned earlier, I've left it at there. 
Perhaps later, but right now I'm busy playing with my new DE. :=)

**Comment by Stibbons** [comment]
I had problem with gnome for auto startup. Probably the hot key was registered too soon. Solved with a script that actually delay guake startup by 5s

Ps: I am the guake maintainer

**Comment by JosephMcc** [comment]
@Stibbons In cinnamon you can set a startup delay for individual apps in the startup applications ui. From what you say it sounds like setting a 5 or 10 second delay there would probably solve the issue.

**Comment by anandrkris** [comment]
From the discussion, seems this can be easily handled with delay in Startup Applications.

Can this be closed? @JosephMcc
