### ISSUE TITLE
Cinnamon - Enhancement suggestions for Runner (Alt + F2)

### ISSUE THREAD

**Issue by anandrkris** [linuxmint/Cinnamon#2366]
Hi - The current runner in Cinnamon is functional but very minimalistic.

May i suggest to incorporate some nice features into runner (similar to KDE's Krunner)
- Application launch - integration with Cinnamon Menu
- Shortcuts to features based on certain keywords - increase brightness, play / pause music, logout, restart cinnamon (current r does not show any tip that it is restarting cinnamon), etc.

http://www.maketecheasier.com/10-awesome-features-of-krunner-in-kde-4/2009/06/29
http://userbase.kde.org/Plasma/Krunner

**Comment by anandrkris** [comment]
@dalcde @mtwebster @RavetcoFX - How difficult or easy is to integrate search providers into Alt + F2 runner?
https://github.com/linuxmint/Cinnamon/pull/3928
https://github.com/linuxmint/Cinnamon/pull/3853

**Comment by lestcape** [comment]
@anandrkris i think that will be possible, but of course will need to be a different implementation and currently i will prefer stability instead, because what is added on the last days is more than what i expected. I think that will not be preferable to take risk, anyway +1

**Comment by anandrkris** [comment]
@lestcape Hmm, am not saying it should necessarily be implemented in the next release. :smile: But if it is implemented in generic fashion - perhaps it could be reused w//o much rework. In fact, i prefer it to be in runner than bloat the menu. 
Krunner supports plugins - unsure how Cinnamon runner is designed at the moment.

**Comment by RavetcoFX** [comment]
@anandrkris glebihan and I were mentioning the possibility of it, but its all still very up in the air at the moment what the plan will be

**Comment by anandrkris** [comment]
@RavetcoFX - Thanks for the update. Keen to see this in Cinnamon.
I recall my initial days of Linux with KDE and used to show off people what `Alt + F2` can achieve and how minimal `Super + R` in Windows...Apart from cool and fancy factor, many things are functional as well... (Nepomuk was slow and complex...then came Baloo...)...now am digressing :wink:

**Comment by anandrkris** [comment]
http://www.ocsmag.com/2015/03/13/plasma-is-my-new-favorite-desktop/ > Check out Krunner screenshots. Impressive. I am running Cinnamon and definitely not a KDE fan boy. Sharing here for interest / ideas !

**Comment by WiR3D-kNiGhT** [comment]
This needs more upvotes.

**Comment by jadlr** [comment]
+1

**Comment by brunoro** [comment]
Any advances on this? I'm with @martinrotter, integrating the results from the search bar from the panel "Menu" button would be already a big improvement. I can take some time to try it out if someone else is also interested on such feature.

**Comment by marcociara379** [comment]
Definitely a killer creature. Why not also file search results? Even better if from a index service like recoll

**Comment by kubaceg** [comment]
+1

**Comment by Madh93** [comment]
I think it should run aliases too.

**Comment by JosephMcc** [comment]
Support for aliases was actually implemented here: https://github.com/linuxmint/Cinnamon/commit/94b9494ea64bedf8e960c5ecf99479ff0c5982ce

You can set them with the org.cinnamon.run-dialog-aliases gsettings key.

**Comment by anandrkris** [comment]
https://www.maketecheasier.com/albert-launcher-linux/ Seems interesting

**Comment by RossBrunton** [comment]
As mentioned in #5093, the ability to expand shell variables and `~` would be greatly appreciated.

**Comment by imperative** [comment]
Almost all of this functionality is basically already implemented in the open-source program called Launchy.  It even works on linux. Not sure if it's easy, but you could just get it's code, polish a few things (if needed by rest of Cinnamon software) and include in the package. Both softwares are open source.

**Comment by well1791** [comment]
This feature is good to avoid searching through the main menu. Also as mentioned before, having the calculator ready to use in the runner is helpful as hell (miss that feature from KDE).

Perhaps if this integration is not feasible sooner or later (considering this issue exist from 2013), could you provide a good recommendation (preferably tested and approved) that can give us the same features without losing the smoothness of cinnamon?

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html

**Comment by rpxomi** [comment]
Sorry to put this here, but I do not know if it's the Arc theme, or this is related to Cinnamon. What is that bar that can be seen below the search box that appears with `Alt + F2`? _(I marked it with red color)_. Is it something that works poorly or simply decoration?

![runner](https://user-images.githubusercontent.com/31228150/39672773-1373caee-5107-11e8-9b20-cb55394d5a6f.png)

If my message has to be deleted, I understand. But I did not want to open a new issue just for this.

Thanks and I'm sorry again.

**Comment by leigh123linux** [comment]
@rpxomi  The arc-theme has broken cinnamon theme, using mint-y-theme (based on arc-theme) is a better choice.

**Comment by rpxomi** [comment]
Using the recommendation you gave me as a guide, I found this theme in Cinnamon Spices that integrates well with the colors of the Arc theme and does not have that bar in the search box (for not have to activate AUR and download mint-y-theme).

If someone is interested, this is the link:
https://cinnamon-spices.linuxmint.com/themes/view/Mint-Y-Blue

Thank you very much.

**Comment by Izaic** [comment]
Unit conversions would be extremely useful, as well as looking up timezone information, and being able to search files.
