### ISSUE TITLE
Systray unresponsive on Cinnamon start

### ISSUE THREAD

**Issue by collinss** [linuxmint/Cinnamon#2371]
When I start cinnamon (or restart), the systray icons are initially unresponsive (hover works but right and left clicks don't do anything). If I add something to the systray, or move it via panel edit mode, it starts working normally.

I have experienced this issue on multiple versions of Mint, and Cinnamon (including latest Git), and on both my laptop and desktop.

**Comment by JosephMcc** [comment]
@collinss is this still an issue?

**Comment by collinss** [comment]
I could never consistently reproduce this, though it did seem to be system dependent. I haven't seen this issue on my current machine so I'll close.
