### ISSUE TITLE
Right-click Context Menu disables Taskbar (Panel Menu) until dismissed.

### ISSUE THREAD

**Issue by donaldalanmorrison** [linuxmint/Cinnamon#2372]
Reproduction: Right-click the desktop area, but do not dismiss the context menu -- leave it open.  Notice when you move the cursor to the bottom of the screen, that Cinnamon will not reveal the Taskbar (Panel Menu) until you dismiss the context menu.  This also happens in applications such as Firefox.

**Comment by JosephMcc** [comment]
This is just the way interaction with Gtk menus works. Any click you make to do something is going to dismiss the menu anyhow.
