### ISSUE TITLE
Touchpad Tapping Stops workingf after resume from hibernate or suspend

### ISSUE THREAD

**Issue by anandrkris** [linuxmint/Cinnamon#2394]
Hi - I am using Mint 13 Cinnamon (daily PPA) and after hibernate or suspend & resume and my laptop touch pad _tapping_ stops working. Moving cursor works fine and touch pad click buttons are fine.

Currently, have to enable it using synpatiks UI or synclient TapButton1=1 TapButton2=2 TapButton3=3.

http://ubuntuhandbook.org/wp-content/uploads/2013/07/synaptiks-touchpad-tap-configuration.jpg

Any idea what could be the issue? Let me know if any more info is required.

P.S. I use Linux Mint 13 KDE as well but do not face this issue.
P.P.S For my USB Mouse, had an issue of USB disconnecting automatically. The below fixed the issue.
http://www.hecticgeek.com/2012/06/fix-usb-mouse-not-working-laptop-mode-tools-ubuntu/

**Comment by qdinar** [comment]
touchpad tap does not perform left click, (only touchpad's left button does), in linux mint 19's lock screen. i solved this by editing libinput file in /usr/share/X11/xorg.conf.d/ , with help of "man libinput".
