### ISSUE TITLE
Add "desktop" to Alt-Tab window list

### ISSUE THREAD

**Issue by dalcde** [linuxmint/Cinnamon#240]
It would be nice if we can switch to the desktop using Alt-Tab. Solves the issue mentioned here (post 3):
https://github.com/linuxmint/Cinnamon/issues/123

**Comment by Winterwolf** [comment]
+1

**Comment by Topperfalkon** [comment]
-1 (but seriously, stop with that crap unless you have a comment to go with it)

As @gauravjuvekar says, super+d works just fine. Having it in the windows list implies it's a window, which is unintuitive. The desktop isn't displayed in the alt-tab switcher on Windows, or at least not on W10

**Comment by Winterwolf** [comment]
Why you compare with Windows? Is still displayed in Ubuntu and I like it!

**Comment by Topperfalkon** [comment]
Because I want a window switcher to focus on switching windows. If I need my desktop, I have super+d for that

**Comment by archfrog** [comment]
Sorry for necroing an old thread, but the thread seems **extremely** relevant to me ;-)

Some of us habitually avoid the Windows ("Super") key on PC keyboards.  As far as I know, there's only one reason to use it ever: To show the desktop.  That breaks the flow for those of us that have used Alt-Tab to go to the desktop for the past decades.  Some of us have been going at the computer thing for so long that we actually remember having had keyboards **without** that blasted Windows key.  I still remember sighing when Microsoft added the Windows key - and the world followed suit...  I always saw this move as a simple marketing move: "Guys, we need to figure out how to make people think more about Windows?  Uhm, what if we add a Windows key to our keyboards?  Yeah, that'll work!"  And then a key with no real purpose or actual need was added.

It would be really cool if there was an option, possibly disabled by default, to show the desktop in the Alt-Tab window list.  The lack of this feature in Windows 10 is one of the many reasons why I have just installed Ubuntu Desktop 17.04.  Unfortunately, Unity is a sad excuse for a desktop environment, so I removed it and installed Cinnamon v3.4.  Only to discover that the Alt-Tab handling is quite irritating.  On Windows 10, I got used to hitting Ctrl-Escape to bring up the Classic Shell start menu, but that still doesn't flow naturally.

Please reconsider and think along the lines of "This will make many people happy!" and "Is it really so difficult to implement as an option?"  :-)  Cinnamon rocks most of the time, so why not make the small changes that can help making it the most widely used Linux desktop manager?  It seems that **you** don't like Alt-Tabbing to the desktop, but many people out there miss this feature in Cinnamon and Windows 10.  After all, it is only a tiny fraction of a percent of people who spend time on GitHub issues pages.

Try doing a google these words, if you don't believe me: `windows 10 alt-tab to desktop`.

**Comment by longnguyen2306** [comment]
+1 please. It takes just way too long to mouse the mouse to the desktop icon.

**Comment by crazyBaboon** [comment]
Alt+Tab **switcher should go to desktop** to make my life easier when I'm playing 0ad.

**Comment by sahibnasirov** [comment]
Yes why they removed it from Ubuntu 18.04 , The only thing i miss from Ubuntu 16 , hope they will add soon

**Comment by Slapbox** [comment]
Just had a fullscreen app crash on me when I tried to <kbd>Alt+Tab</kbd> away and there was nowhere to go.
