### ISSUE TITLE
Input volume settings in "Sound settings"

### ISSUE THREAD

**Issue by nask0** [linuxmint/Cinnamon#2404]
Input volume for microphone actually manipulates "Mic boost" settings, not the "Mic volume"

**Comment by pixunil** [comment]
Can you please explain your issue more accurately?

**Comment by nask0** [comment]
This issue not exists anymore, consider it as already fixed. 
Problem was that, when you changes mic volume settings from panel, it actually changes the mic boost not volume. 
However, it's gone :)
