### ISSUE TITLE
Two "System Settings" apps when using Cinammon

### ISSUE THREAD

**Issue by garymm** [linuxmint/Cinnamon#2408]
Menu -> System Tools
shows two identical icons, both of which are labeled "System Settings". One of them appears to be the Cinnamon-specific settings, the other is general Ubuntu (or GNOME?) settings.

I spent a long time trying to find the Cinnamon-specific settings yesterday because of this.

![cinnamon-system-settings](https://f.cloud.github.com/assets/421339/1247321/8f16fc2a-2aba-11e3-8f3e-d2e79c9ab708.png)

**Comment by ringo32** [comment]
had same sorta issue but found the soluition on my onwn side , its a kde app showed in menu two times :) adding X-cinammon did :)
