### ISSUE TITLE
Keyboard layout improvement (make it available per window)

### ISSUE THREAD

**Issue by nask0** [linuxmint/Cinnamon#2409]
It will be nice if keyboard layouts can "remember" layout per window (or app), not globally (for example, xfce has this option, see screenshot)
![xfce4-xkb-plugin-0 5 3-settings](https://f.cloud.github.com/assets/248198/1252134/cdb4faf4-2b41-11e3-8148-17972b7c2a52.png)

**Comment by SimSimY** [comment]
Isn't this the "allow different layout for individual windows" option under settings -> keyboard -> layouts?

**Comment by dikonov** [comment]
Yes. The per-window nput seems to work now in Cinnamon and I do not use Gnome 3 anymore.

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html
