### ISSUE TITLE
Problem when connecting two Mint 12 devices via Bluetooth

### ISSUE THREAD

**Issue by LexMidnight** [linuxmint/Cinnamon#243]
Tried to connect my tablet with my laptop, both running Mint 12 and Cinnamon. The pop-up where you type the pin in (see picture http://i42.tinypic.com/15dwfh4.png ) disappear too fast, and you can't type the pin.

**Comment by scintill** [comment]
Same issue as described in OP, Cinnamon 2.4.5 on two systems, one 32-bit, one 64-bit.  It's hard to get the text cursor/caret to focus on the PIN entry field (despite [the code](https://github.com/linuxmint/cinnamon-bluetooth/blob/master/files/usr/share/cinnamon/applets/bluetooth%40cinnamon.org/applet.js) apparently trying to auto-focus).  When I try to click for focus, either nothing happens, the notification is dismissed, or moving my cursor over it causes the notification to fade out partially, maybe to let me know I'm clicking "through" it.  I've even tried typing with the assumption it was focused, but the keystrokes go to the previously focused window.  As mentioned, it disappears pretty quickly too.

But, I have just used a workaround several times, so hopefully it's consistent: let the notification be dismissed.  Then you can open it again from the panel at the bottom of the screen (at least with the default setup), click to focus in the text field, and type the PIN.  For whatever reason the text field seems to behave correctly there.

I am not entirely sure I am actually connected, as I'm having issues setting up a PAN, but I believe this got me past the first hurdle...
