### ISSUE TITLE
Granting administrator rights to a network user

### ISSUE THREAD

**Issue by frederic-urban** [linuxmint/Cinnamon#2431]
Hello,

I'm new to Cinnamon... I'm already a big fan of it. Former user of Gnome 2, Gnome 3 was just a big joke to me well, lets go with the main problem...

This bug/problem is already present in Gnome2/3. When you have network accounts provided by nss (throught ldap, nss-db, ...), authentified by pam, you are unable to give admin rights to a network user in the User Account Panel.

First try from a local admin account, you see the user as soon as he logged in first, but the account type is locked. When you login as the network user, go to the User Account Panel i order to unlock with the local admin account, the panel simple don't load. Problem is the same with some other Panel as soon as you are not a local admin. I finally added user to adm,sudo admin groups with usermod -G ... but it's not so friendly and maybe something is missing in the process of granting a network user administrator rights.

Any solution ? If you need more details, feel free to contact me, ... I'm fighting with this for years now.

**Comment by Vahan86** [comment]
@JosephMcc, can we close the issue since there is no response from OP for about 2 years.
