### ISSUE TITLE
natural scrolling

### ISSUE THREAD

**Issue by m0n9oose** [linuxmint/Cinnamon#2434]
After update cinnamon i can´t enable natural scrolling! Please, turn it back!

**Comment by his** [comment]
It's quite inconsistent that a setting exists for the touchpad but not for the mouse wheel, whether one gets it or not. It should exist for both or neither.
(Cinnamon 2.4.8)

**Comment by AlbertVeli** [comment]
I just installed cinnamon 3.2.7+serena (Mint 18.1) and the "reverse scrolling direction" option is only available for Touchpad, not for Mouse. It would be nice to have it available for mouse too.

**Comment by nayosx** [comment]
Mid 2017 and the natural scrolling for mouse is parcial.

For many apps use this command, but not for another apps that use cinnamon for example nemo

echo "pointer = 1 2 3 4 5 6 7 8 9 10 11 12" > ~/.Xmodmap && xmodmap .Xmodmap

**Comment by leigh123linux** [comment]
Posting to a long dead report isn't going to get you anything.

P.S The issue should have been filed against  cinnamon-settings-daemon!
