### ISSUE TITLE
Spices (App/Desk let) - Update Warning - Active items

### ISSUE THREAD

**Issue by anandrkris** [linuxmint/Cinnamon#2441]
Hi, When an update is available for any of the desklets, a warning dialog is shown for _installed_ items. I feel, it is better to be shown for **installed** and **active** items. 

I may be wrong here though and perhaps has a valid rationale for the dialog.

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html
