### ISSUE TITLE
Is cinnamon bumpmaps still implemented?

### ISSUE THREAD

**Issue by seneq** [linuxmint/Cinnamon#2442]
Cinnamon 2.0 was released and i am curious if is still a feature that will be implemented in linux mint 16 or cinnamon ?
http://img.netupd8.com/bumpmaps.jpg 
It is a great feature to have and i hope it gets implemented.

**Comment by Vahan86** [comment]
Issue https://github.com/linuxmint/Cinnamon/issues/3466

**Comment by Vahan86** [comment]
@JosephMcc, can be marked as a feature request?

**Comment by clefebvre** [comment]
Now that boxpointer are gone, some themes which don't use rounding can de-facto be compatible with this.

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html

**Comment by ijash** [comment]
i want this too! so, how to implement it on `.menu{}` on cinnamon.css?help would be very appreciated!

**Comment by mfreeman72** [comment]
So, is this a thing yet, or not? Transparencies look dog ugly without some sort of background blur to go with them. It's so depressing as a fan of Cinnamon that this isn't a regular part of the OS's theming.

**Comment by Murat-Karakaya** [comment]
Unfourtunately it is buggy. To the point where it is unusable. Hopefully it will be fixed.
1) bumpmap often effect extends the element
2) This might be an issue about me but I couldn't find an image that would properly blur the background. (the /usr/share/cinnamon/bumpmaps/frost.png would make a bit of a mess)
3) hovering over menu items breaks the effects

<img width="414" height="380" alt="Image" src="https://github.com/user-attachments/assets/5a1c9e9e-2d34-4763-9e2d-55b2de7d547b" />
