### ISSUE TITLE
[Feature request] Add a settings option to control focus-stealing

### ISSUE THREAD

**Issue by gauravjuvekar** [linuxmint/Cinnamon#2445]
If you select many images and right-click--->open-with-GIMP , gimp shows a 'opening file' dialog for each file which horribly steals focus(n times if you open n files at once). It even makes the workspace switch to the one where gimp is. That's just one example that I know of. Could we add a setting to cinnamon/mutter to allow control over the level of focus-stealing permitted

eg
- [ ] Never steal focus
- [x] Highlight in window-list in panel
- [ ]  Steal focus if on same workspace
- [ ] Always steal focus

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html
