### ISSUE TITLE
Touchpad not working correctly after upgrade. 

### ISSUE THREAD

**Issue by JohannesTress** [linuxmint/Cinnamon#2459]
Hey there, after upgrading to Cinnamon 2.0.2-20131011040307-precise (Ubuntu 12.04 LTS) the touchpad of my Lenovo T420 Thinkpad is missing the click function and the scroll with two fingers function. Both of them are working fine under Gnome and Unity but not under cinnamon. Can you please fix this? 

Thanks indeed! 

Johannes

**Comment by CottonEaster** [comment]
@ sixman9 

I found that, on a ThinkPad with Mint 19, I had to do something after each suspend - rather than boot up - to keep edge-scrolling working. The script I used is [here](https://pastebin.com/Lst8jeHb).
