### ISSUE TITLE
Pidgin icon dissappears from tray icon area

### ISSUE THREAD

**Issue by alefq** [linuxmint/Cinnamon#246]
Pidgin tray icon behaves oddly. First it appears cropped, and when that happens, it dissappears at the next new message arrival. See the screenshots. I'm using Cinnamon 1.2 at Mint 12.
http://imageshack.us/photo/my-images/850/pidgincropped.png/
http://imageshack.us/photo/my-images/818/pidgininvisible.png/

**Comment by RalfJung** [comment]
Unfortunately, the workaround described by @slmingol has to be applied *every time* I start pidgin. Each time, the icon first comes up in the "bad" state where it just takes space in the system tray, but doesn't react to any input. Each time I have to toggle "Custom panel size" to make it appear.

**Comment by zquestz** [comment]
I was able to fix this by editing `/usr/share/pixmaps/pidgin/tray/hicolor/index.theme` and replacing it with:

```
[Icon Theme]
Name=Pidgin
Comment=Icon theme for Pidgin tray icons
Directories=scalable/actions,scalable/status

[scalable/actions]
MinSize=1
Size=128
MaxSize=256
Context=Actions
Type=Scalable

[scalable/status]
MinSize=1
Size=128
MaxSize=256
Context=Status
Type=Scalable
```
