### ISSUE TITLE
Switch input sources using Alt Shift Toggle

### ISSUE THREAD

**Issue by orschiro** [linuxmint/Cinnamon#2463]
Hello,

Why is it not possible to select Alt Shift as a switch for toggling the input sources?

![keyboard-alt-shift-toggle](https://f.cloud.github.com/assets/170947/1322829/6382f318-344f-11e3-93c7-b2af1764fb64.png)

**Comment by nstjhp** [comment]
@leigh123linux Even after turning input-sources-switcher off I still can't use Ctrl+Shift+Alt+Left (or Right) for moving things between workspaces - any ideas?

**Comment by Vahan86** [comment]
@orschiro, is this still a issue for you with Cinnamon 3.0?

**Comment by orschiro** [comment]
Dear @Vahan86,

I am sorry but I am no longer using Cinnamon. 

Warmly,

-Robert
