### ISSUE TITLE
Long press power button results in automatic shutdown

### ISSUE THREAD

**Issue by dtrunk90** [linuxmint/Cinnamon#2468]
When long pressing power button cinnamon should ask for action (as it is configured in power settings). The window which asks for action pops up (in english instead of german) and then it shuts down automatically.

Cinnamon version: 2.0.2-20131011040008-raring
Distribution: Ubuntu
Version: 13.04

**Comment by darkMatterSound** [comment]
This still isn't working for me.  Here's my powerbtn.sh:

[ -r /usr/share/acpi-support/power-funcs ] && getXconsole
PMS="cinnamon-settings-daemon gnome-settings-daemon kpowersave xfce4-power-manager"
PMS="$PMS guidance-power-manager.py dalston-power-applet"
PMS="$PMS mate-settings-daemon"
PMS="$PMS unity-settings-daemon"

And here's my logind.conf:

[Login]
#NAutoVTs=6
#ReserveVT=6
#KillUserProcesses=no
#KillOnlyUsers=
#KillExcludeUsers=root
Controllers=blkio cpu cpuacct cpuset devices freezer hugetlb memory perf_event net_cls net_prio
ResetControllers=
#InhibitDelayMaxSec=5
HandlePowerKey=ignore
HandleSuspendKey=ignore
HandleHibernateKey=ignore
HandleLidSwitch=ignore
#PowerKeyIgnoreInhibited=no
#SuspendKeyIgnoreInhibited=no
#HibernateKeyIgnoreInhibited=no
#LidSwitchIgnoreInhibited=yes
#IdleAction=ignore
#IdleActionSec=30min
