### ISSUE TITLE
Modal Dialogs

### ISSUE THREAD

**Issue by ghost** [linuxmint/Cinnamon#2474]
This can be a place for a  more "official" discussion on whether to theme modal dialogs using the cinnamon theme or the gtk theme.
I for one would love to see them themed by cinnamon as it looks more consistent to me.
This would my humble logic on this(i´m no pro designer by any stretch!):

Modal dialogs usually show a message that has to do with the system in general therefore they should be themed the way the system(read cinnamon) is themed.

Modal dialogs that are in connection with the window(asking if you want to leave the page etc...)  can be styled using those dialogs that are attached to windows and will be part of the gtk them thus making a nice distinction between these 2 types of dialogs.

Of course it gets a little awkward when you think about password input since that has to do with the system as well as the window, but I would personally leave passwords for modal dialogs too.
I also might throw in a really biased one: "cinnamon dialogs look freakishly awesome :D"

**Comment by dalcde** [comment]
Closing since implementation is not feasible (or logical)
