### ISSUE TITLE
Cinnamon 2.0 keyboard shortcut settings do not permit "Caps lock (while pressed)" to change KB layouts

### ISSUE THREAD

**Issue by geckolinux** [linuxmint/Cinnamon#2477]
Hello,

I use two different keyboard layouts, and I am accustomed to using the "Caps Lock (while pressed)" option that was always available in XFCE and Gnome and Mate keyboard settings to change the layout. That way the Caps Lock key acts sort of like a shift key for changing the keyboard layout only while pressed for entering certain special characters in a secondary language. Unfortunately this option is not available and is impossible to set with the new Cinnamon 2.0 keyboard shortcut settings. Can you please add it?

Thanks!

**Comment by Vahan86** [comment]
The option requested by @geckolinux is available in Cinnamon 3.0. 

![untitled](https://cloud.githubusercontent.com/assets/12819058/19020612/f509d7a4-88be-11e6-9c49-bfe8a305e188.png)

@JosephMcc, can we close this issue?
