### ISSUE TITLE
Windows disappear and are not added to panel on minimize (2.0.2)

### ISSUE THREAD

**Issue by moejamin** [linuxmint/Cinnamon#2478]
Just upgraded to Cinnamon 2.0.2 on Precise 12.04 and now when I try to minimize windows they disappear.  I can get to them through expo/scale but they are not minimized to the panel for easy selecting. Cinnamon window list is enabled.  Anyone else having this problem?

**Comment by mikkovedru** [comment]
I also have this problem. Mint Cinnamon 17.1. Changing settings doesn't fix the problem.

**Comment by mikkovedru** [comment]
I have been fighting this problem for over a week now. Reboots don't help.

But now I finally found how to (temporarily?) fix the problem.

Basically you have to go to Settings/Applets and disable/enable/add/change the applet by the name of "Window list". After that the list of windows will once again work (for new opened windows only, windows already running are still not shown; maybe this should be reported as bug and fixed?). Haven't tried a reboot yet, can't confirm that method will work from fresh start. I would imagine it would. Will report if it doesn't.

The solution was found here: http://forums.techarena.in/operating-systems/1467337.htm

**Comment by Vahan86** [comment]
@moejamin, is this still an issue to you with Cinnamon 3.0?
