### ISSUE TITLE
Tap-to-click & reversed mouse (Leftie) caues taps to be right clicks

### ISSUE THREAD

**Issue by byteit101** [linuxmint/Cinnamon#2480]
Got latest 2.0 cinnamon on Ubuntu 12.04 LTS. Atempted to enable tap to click and reversing mouse but tapping with the touchpad causes right clicks. Very annoying as it worked properly on 1.8.

**Comment by Vahan86** [comment]
@byteit101, is this still an issue in Cinnamon 3.0?

**Comment by byteit101** [comment]
Seems to work correctly in 2.8.3, the latest in my ppa.

**Comment by JosephMcc** [comment]
@byteit101 thanks for checking and closing
