### ISSUE TITLE
[FEATURE REQUEST]: Dynamic number of workspaces option (gnome3-like)

### ISSUE THREAD

**Issue by gabboman** [linuxmint/Cinnamon#2482]
I've been using this desktop for 3 hours. It's almost perfect. The only thing that I miss is to have a dinamic number of workspaces, if I need one more, that the system adds it. And if I don't need it (no apps on it, and it isn't the only remaining desktop) erase that workspace.

There is a lot of people who doesn't like this option, so it could be a feature in the configuration.

**Comment by jtylers** [comment]
Let the users decide what they want to enable and disable.  Please bring this feature back :'(

**Comment by EvanWashkow** [comment]
Want it. This is the only reason I'm not using Mint.

**Comment by alfzki** [comment]
after 8 years they still won't add it:( very disappointed 😞

**Comment by gabboman** [comment]
> after 8 years they still won't add it:( very disappointed 😞

The UX team must have its reasons. It might even be for being different than gnome and osx

also fun fact in the 8 years since this ticket I moved to…. osX
