### ISSUE TITLE
On screen feedback for screen brightness / volume unusable

### ISSUE THREAD

**Issue by grrrrr** [linuxmint/Cinnamon#2484]
Following an upgrade to `Cinnamon 2.0` the on screen notifications / feedback when increasing / decreasing volume and screen brightness has become less than useful.

Previously in `cinnamon 1.8` if you adjusted brightness or sound you would be presented with on screen notification with an indication bar of the current setting and how much you have changed it.

In `cinnamon 2.0` you are presented with a grey notification with a black _sun_ or _speaker_ icon.   As you adjust the brightness you get no visual feedback from this notification and with the sound a possible 14 volume positions are represented in only 3 segments.

![brightness cleaned](https://f.cloud.github.com/assets/1025506/1345017/ec05772a-3688-11e3-9ed7-d6c7ac2f18ba.jpg)

![sound cleaned](https://f.cloud.github.com/assets/1025506/1345018/f1d82ad0-3688-11e3-9cfb-8503b26681fc.jpg)

System info:

```
$ uname -a
Linux hostname 3.5.0-41-generic #64~precise1-Ubuntu SMP Thu Sep 12 16:50:04 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux
```

Cinnamon info:

```
$ dpkg -l| grep cinnam
ii  cinnamon                                                    2.0.2-20131011040307-precise            Cinnamon desktop
ii  cinnamon-common                                             2.0.2-20131011040307-precise            Cinnamon desktop (Common data files)
ii  cinnamon-desktop-data                                       2.0.1-20131011011505-precise            Common files for Cinnamon desktop apps
ii  cinnamon-screensaver                                        2.0.0-20131011013003-precise            Cinnamon screen saver and locker
ii  cinnamon-session                                            2.0.1-20131011043004-precise            Cinnamon Session Manager - Minimal runtime
ii  cinnamon-settings-daemon                                    2.0.1-20131011004504-precise            daemon handling the Cinnamon session settings
ii  cinnamon-translations                                       2.0.1-20131011040406-precise            Translation files for the Cinnamon desktop
ii  gir1.2-cinnamondesktop-3.0                                  2.0.1-20131011011505-precise            Introspection data for CinnamonDesktop
ii  libcinnamon-desktop0                                        2.0.1-20131011011505-precise            Utility library for loading .desktop files - runtime files
```

PPA info

ppa:gwendal-lebihan-dev/cinnamon-stable

**Comment by ffmnc** [comment]
Is there a folder where we can find and edit these icons?
