### ISSUE TITLE
power manager applet - hard to discern charge just from icon - suggested change

### ISSUE THREAD

**Issue by grrrrr** [linuxmint/Cinnamon#2485]
Following the upgrade to `cinnamon 2.0` the `power manager applet` has had a slight redesign which makes it much harder to discern the charge level when unplugged from a power source and if you don't have the percentage displayed.

**What happens**

With `2.0` the battery applet has a very feint green color which is hard enough to see that with out looking hard you could be mistaken that all that is displayed is an *empty* battery.   As the battery discharges and drops below 50% the battery reading color changes to white which is instantly noticeable

![battery_full cleaned](https://f.cloud.github.com/assets/1025506/1346727/037edb3c-36a5-11e3-8161-e05fa14f91be.jpg)
![battery_low cleaned](https://f.cloud.github.com/assets/1025506/1346726/0309ec82-36a5-11e3-94d2-1288bf78999d.jpg)

**What should happen - suggestion**

Rather than using the *green* for a full battery, use *white* to indicate full (in keeping with the other white applets) and then once charge starts getting critically low, e.g. 30%, change color to *red*.  This is similar to what happened with `1.8`

**Comment by JosephMcc** [comment]
The icons being used are controlled by your current icon theme.
