### ISSUE TITLE
Unable to change keyboard layout settings

### ISSUE THREAD

**Issue by richcocoa** [linuxmint/Cinnamon#2486]
Previously in Cinnamon I could do things like swap Caps Lock and Esc or disable Caps Lock entirely. I used to do this by Cinnamon Settings -> Regional Settings -> Input Sources -> A button to customize things (see image)

![regional settings_770](https://f.cloud.github.com/assets/878118/1350569/890d04e6-370d-11e3-9021-11a028a26d1a.png)

It is currently greyed out. By the window that used to popup there, one had access to plenty of options to tweak things like Shift and Caps Lock.

I tried creating a dummy user to check if the problem was a result of some stale files in my Home folder. But it did not work for me.

I am running an up-to-date Arch Linux system. Here are some of my software versions:

$ pacman -Qs cinnamon | grep '^[^ \t]'
local/cinnamon 2.0.2-2
local/cinnamon-control-center 2.0.2-1
local/cinnamon-desktop 2.0.1-1
local/cinnamon-screensaver 2.0.0-1
local/cinnamon-session 2.0.1-1
local/cinnamon-settings-daemon 2.0.1-2
local/cinnamon-translations 2.0.1-1
local/cjs 2.0.0-1
local/muffin 2.0.1-1
local/nemo 2.0.0-2

$ pacman -Qs kbd | grep '^[^ \t]'
local/kbd 2.0.0-2
local/libgnomekbd 3.6.0-1
local/xkeyboard-config 2.10.1-1

Please tell me if you want me to post anything more. In the meantime, I want to know if there is some other not so convoluted way to set these preferences. In dconf, the syntax for setting these things did not seem very intuitive to me.

**Comment by Vahan86** [comment]
You can change Caps Lock behavior (disable it, make Caps Lock an additional ESC, Ctrl, Num Lock ans so on ) in Cinnamon Settings-> Keyboard-> Layouts-> Options-> Caps Lock key behavior.

@JosephMcc, I think this issue can be closed.
