### ISSUE TITLE
Time applet doesn't use regional format

### ISSUE THREAD

**Issue by kaie** [linuxmint/Cinnamon#2487]
Cinnamon 2.0.2 on Fedora 19, after upgrade from earlier Cinnamon versions.

I noticed the time format shown was incorrect, used cinnamon settings, regional settings, and noticed that the regional format "german" was lost. I added the regional format and logged out and logged back in.

Still, the time shown in the clock applet is shown incorrectly. Instead of the expected 24 hour format (14:15), I get a 12 hour format (2:15).

**Comment by ManIVIctorious** [comment]
Works for me in cinnamon 3.0.7

@JosephMcc I think this can be closed
