### ISSUE TITLE
Windows Quick List: Add scrollbar if list doesn't fit on screen

### ISSUE THREAD

**Issue by andr3jx** [linuxmint/Cinnamon#2491]
I can't access all windows from applet windows quick list if the list doesn't fit on screen. Please add a scrollbar. A close button for each window in the list would be great too.
![quick-windows-list](https://f.cloud.github.com/assets/1810642/1360096/0b80b7a6-37ef-11e3-890e-065acfa48a11.png)

**Comment by Vahan86** [comment]
This is still an issue in Cinnamon 3.0.7

**Comment by MrElectroNick** [comment]
Still an issue in 3.4.3
![screenshot from 2017-07-08 22-43-31](https://user-images.githubusercontent.com/3267843/27988636-1ce978e6-642f-11e7-9eed-62e5ee8b693f.png)
