### ISSUE TITLE
Nemo: Properties in the selected file of other tab when Properties invoked

### ISSUE THREAD

**Issue by dpermar** [linuxmint/Cinnamon#2497]
I am trying to see the properties of a file and tried both right-click/properties or Alt+Enter and then saw the properties of the file selected in other tab.

Nemo 1.8.3
LinuxMint 15 x64
Cinnamon 1.8.8+olivia

**Comment by Vahan86** [comment]
@JosephMcc, can we close the issue since there is no clarifications from OP.
