### ISSUE TITLE
Cinnamon Calendar applet time stops on malformed date format string

### ISSUE THREAD

**Issue by ppwaskie** [linuxmint/Cinnamon#2499]
When using a custom date format string that has an unknown format character, the clock stops running.

The custom string I use is: %a %b %e %G, %I:%M%p

When trying to add the week of the year, typically %W, the parsing of this string causes the clock to stop updating.  Removing the offending character from the string does not cause the clock to start updating again.  The only way I can get it working again is by removing the applet and re-adding it to the taskbar.

Running cinnamon-2.0.2-1.fc19, x86_64.

**Comment by DUDEbehindDUDE** [comment]
Experiencing this issue on Mint 22 / Cinnamon 6.2.9

System:
  Kernel: 6.8.0-41-generic arch: x86_64 bits: 64 compiler: gcc v: 13.2.0
  Desktop: Cinnamon v: 6.2.9 tk: GTK v: 3.24.41 wm: Muffin dm: LightDM
    Distro: Linux Mint 22 Wilma base: Ubuntu 24.04 noble
