### ISSUE TITLE
Can't connect anymore to OpenVPN connection via Applet

### ISSUE THREAD

**Issue by r0gz** [linuxmint/Cinnamon#2503]
As soon as I upgraded to cinnamon 2.0.2-2 I wasn't anymore able to connect to my OpenVPN connection via applet while if I used a different DE / WM it worked (tested with xfce / openbox).

This is what happens:

Oct 19 13:41:29 blackbox NetworkManager[294]: <info> Starting VPN service 'openvpn'...
Oct 19 13:41:29 blackbox NetworkManager[294]: <info> VPN service 'openvpn' started (org.freedesktop.NetworkManager.openvpn), PID 1537
Oct 19 13:41:29 blackbox NetworkManager[294]: <info> VPN service 'openvpn' appeared; activating connections

==> /var/log/errors.log <==
Oct 19 13:41:29 blackbox NetworkManager[294]: <error> [1382179289.961062] [nm-vpn-connection.c:1374] get_secrets_cb(): Failed to request VPN secrets #2: (6) No agents were available for this request.

==> /var/log/messages.log <==
Oct 19 13:41:29 blackbox NetworkManager[294]: <info> Policy set 'wlan' (wlan0) as default for IPv4 routing and DNS.
Oct 19 13:41:35 blackbox NetworkManager[294]: <info> VPN service 'openvpn' dissapeared

I'm thinking that somehow can't contact with gnome keyring?

Some info about the system:
# uname -r
3.11.5-1-ARCH
Arch Linux x86_64

# pacman -Q | grep gnome
gnome-alsamixer 0.9.7-1
gnome-bluetooth 3.10.0-1
gnome-calculator 3.10.0-1
gnome-color-manager 3.10.1-1
gnome-desktop 1:3.10.1-1
gnome-doc-utils 0.20.10-1
gnome-icon-theme 3.10.0-1
gnome-icon-theme-symbolic 3.10.1-1
gnome-keyring 3.10.1-1
gnome-menus 3.10.1-1
gnome-mime-data 2.18.0-6
gnome-online-accounts 3.10.1-2
gnome-panel 3.6.2-7
gnome-screensaver 3.6.1-6
gnome-session 3.10.1-1
gnome-settings-daemon 3.10.1-1
gnome-settings-daemon-compat 3.6.4-3
gnome-system-monitor 3.10.1-1
gnome-themes-standard 3.10.0-1
gnome-vfs 2.24.4-7
gnome-video-effects 0.4.0-2
libgnome 2.32.1-4
libgnome-data 2.32.1-4
libgnome-keyring 3.10.1-1
libgnomecanvas 2.30.3-2
libgnomekbd 3.6.0-1
libgnomeui 2.24.5-1
libreoffice-gnome 4.1.2-2
polkit-gnome 0.105-2
python2-gnomekeyring 2.32.0-14

# pacman -Q | grep cinnamon
cinnamon 2.0.2-2
cinnamon-control-center 2.0.2-1
cinnamon-desktop 2.0.1-1
cinnamon-screensaver 2.0.0-1
cinnamon-session 2.0.1-1
cinnamon-settings-daemon 2.0.1-2
cinnamon-translations 2.0.1-1

The keyring daemon is correctly running:
1044  0.0  0.0 216132  3996 tty1     Sl   13:01   0:00 /usr/bin/gnome-keyring-daemon --start --components=gpg,pkcs11,secrets,ssh

**Comment by Vahan86** [comment]
@r0gz, is this still an issue in Cinnamon 3.0?
