### ISSUE TITLE
[Feature Request] Option to blur inactive monitor

### ISSUE THREAD

**Issue by gone-insane** [linuxmint/Cinnamon#2511]
it happens quite often to me, that I type something into the wrong textbox, assuming that textbox/window is focussed whilst any window on another monitor is focussed.

I'd wish to have a stronger optical feedback than the greyed out headline of the window frame in order to distinguish between an active and inactive window, especially when using multiple monitors…

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html
