### ISSUE TITLE
Input methods for East Asian languages don't work

### ISSUE THREAD

**Issue by hadiskeini** [linuxmint/Cinnamon#2517]
OS: Fedora 20/Mint 15/Ubuntu 13.10
Cinnamon 2.0.3

The keyboard input for languages like Chinese, Korean and Japanese doesn't work. Switching to them indicates that they're active, but the previously active input language is used instead.

**Comment by Vahan86** [comment]
@hadiskeini, is this still relevant in Cinnamon 3.0?
