### ISSUE TITLE
Cinnamon menu search still giving non-sensical results

### ISSUE THREAD

**Issue by wrouesnel** [linuxmint/Cinnamon#2518]
![](http://i.imgur.com/alzYX5f.png)

Somehow, eSpeak is getting ranked higher then two other applications which both start with "syn". At a guess, the pattern matching for words doesn't take into account the position in the sentence (i.e. things starting with the search term should always rank higher then things which simply contain it somewhere.

**Comment by dalcde** [comment]
Closing as duplicate #1220
