### ISSUE TITLE
Dragging panel items around with the is mouse inverse in RTL

### ISSUE THREAD

**Issue by WiseFerret** [linuxmint/cinnamon#2519]
This happens on Ubuntu 13.10 with current Cinnamon (2.0x) from PPA.
To recreate:
1. Start Cinnamon using an RTL locale (such as Hebrew or Arabic).
2. Try to re-arrange applets or open tasks using the mouse.
Expected results:
- When you drag an item to the right it moves to the right, when you drag it to the left it moves to the left.

Actual results:
- When you drag an item to the right and release it, it behaves as if it was dragged to the left, and vice versa.

**Comment by eladhen** [comment]
This is still an issue in Cinnamon 3.2 on Mint 18.1

**Comment by Vahan86** [comment]
@JosephMcc, can we mark this issue as a bug?

**Comment by JosephMcc** [comment]
There were some fixes for handling RTL in the panel code but it seems we need some more. Unfortunately no one on the dev team knows a RTL language so testing is difficult.
