### ISSUE TITLE
[cinnamon-settings → accessibility] high contrast toggle does not remember theme settings

### ISSUE THREAD

**Issue by VolMi** [linuxmint/Cinnamon#2533]
In the accessibility module of cinnamon-settings, if I activate and deactivate the "high contrast" toggle, my previously defined custom theme settings are lost.

**Comment by VolMi** [comment]
Still reproducible in 2.6.

**Comment by hallamjeff** [comment]
This is reproducible in 2.8.6

**Comment by JosephMcc** [comment]
Can still reproduce on 3.0 as well.

I think what's happening is when you switch to High Contrast and back it is setting your theme to the default value stored in org.cinnamon.interface. In the case of Linux Mint those are the Mint-X themes.

**Comment by mtwebster** [comment]
What I'm going to do here is add a bit more functionality to our accessibility plugin in c-s-d to take care this (along with a key or keys to store the previously selected themes) - indeed right now it recalls the default when you turn off high-contrast (the same as our old module did)
