### ISSUE TITLE
polkitAuthenticationAgent.js fails where gnome3 polkit agent does succeed

### ISSUE THREAD

**Issue by tkrah** [linuxmint/Cinnamon#2534]
I did edit the:

/etc/xdg/autostart/polkit-gnome-authentication-agent-1.desktop

to not start the agent if the session is cinnamon to use the cinnamon agent (which fails to start if there is already an agent registered).

Dialog does show but it fails to authenticate my user (non local user account).
gnome3 authentication agent does work and got no problem.

xsession-errors show this:

JS LOG: polkitAuthenticationAgent: Received 8 identities that can be used for authentication. Only considering the first one.

/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 works, so i am going to reenable it.

**Comment by leigh123linux** [comment]
This was fixed a long time ago.

**Comment by tkrah** [comment]
Just saw those comment so to answer:
Thanks this is fixed and it maybe fixed a long time ago ;-) but it was also reported a long long time ago before ^^.
