### ISSUE TITLE
Cannot get rid of some shortcuts (Alt-F1, Cltr-Alt-Shift-Up/Down, ...)

### ISSUE THREAD

**Issue by eekboom** [linuxmint/Cinnamon#2539]
There are some keyboard shortcuts that cannot be changed and/or never reach applications.
For example *Alt-F1* always toggles the Expo, even though I deleted all the shortcut assignments for Expo in the settings.

Also these are not defined anywhere in the keyboard shortcut settings, but still never reach a running application (eaten silently):
- Ctrl-Alt-Left
- Ctrl-Alt-Right
- Ctrl-Alt-Shift-Up
- Ctrl-Alt-Shift-Down

I have been using all of these shortcuts in my IDE (IntelliJ IDEA) for about ten years many times each day. So these shortcuts are ingrained by 100.000nds usages.

I have tried lots of things, for example the tips mentioned here: http://superuser.com/questions/531874/disable-alt-f1-keyboard-shortcut-in-cinnamon
but nothing helps.

Currently I am back to KDE where all these shortcuts work correctly (can be re-configured as I like).

However in general I like Cinnamon much better.
Please fix this.

Cinnamon 2.0.3
Ubuntu 12.0.4

**Comment by derrillhd** [comment]
The new schema location in dconf is org.cinnamon.desktop.keybindings.wm
I had to go into there because there's no way to define:

<Primary><Shift><Alt>at   (ctrl-shift-alt-@)  (or any of the keys in the UI... it's bug in the UI.. i'll file a bug when I have time..)

**Comment by tinchou** [comment]
If you add a `Super` to you combination (e.g. `super-ctrl-shift-alt-@`) it'll work... weird.

**Comment by perlun** [comment]
Big thanks for this thread! I was going crazy because Cinnamon would consume the Ctrl-Alt-Tab key combination - I use this all the time for switching between windows of an application. I was going crazy since even after setting the shortcut in the preferences in Cinnamon, Ctrl-Alt-Tab was _still_ being overridden by some other thing (Alt-Tab functionality, basically). This thread helped me find the right place to edit it via the `gconf-editor`. :+1: :cookie: :cake:

**Comment by provisota** [comment]
@maosmurf  thank you!
> Using your muffin-hint, I was able to disable ALT-F1 in Mint 16 Cinnamon as follows:
> 
> * run `dconf-editor`
> * navigate to `org.cinnamon.muffin.keybindings`
> * for `panel-main-menu`, replace `['<Alt>F1']` with `[]`
> * logout & login
Just want to add that `org.cinnamon.muffin.keybindings` is now deprecated and moved to `org.cinnamon.desktop.keybindings.wm`
