### ISSUE TITLE
Calibrate Touchscreen functioning

### ISSUE THREAD

**Issue by orschiro** [linuxmint/Cinnamon#2544]
I have a menu entry stating `Calibrate Touchscreen`. When I click it, the calibration screen opens. Once completed, however, I end up with the following shell window:

![](http://i.imgur.com/nvOZt94.png)

Is this the intended behaviour?

**Comment by pixunil** [comment]
Doesn't look like a Cinnamon issue to me, more like a terminal application that I don't know…

**Comment by orschiro** [comment]
@pixunil 

Let's close this issue since I am not using Cinnamon anymore. 

Regards,

Robert
