### ISSUE TITLE
Cinnamon is intolerant of a lazy thumb with buttonless trackpads

### ISSUE THREAD

**Issue by Pointedstick** [linuxmint/Cinnamon#2555]
All recent Mac laptops and some PC laptops that have trackpads that lack a separate button (the whole thing is a button). One nice feature in Mac OS X and Windows 8 is that resting a thumb on the bottom half of the pad as if there _were_ a button there isn't actually registered as a second touch. The purpose of doing this is to click the pad with the thumb, and move the cursor with the index finder.

In Linux Mint 15 with Cinnamon, this doesn't work; resting your thumb on the bottom half of the pad and attempting to use it with another finger registers as having two fingers on the pad. In order to move the pointer, you can truly only have one finger touching the pad at any one time. This is annoying.

**Comment by Vahan86** [comment]
@Pointedstick, is this still an issue in Cinnamon 3?

**Comment by Pointedstick** [comment]
It's not Cinnamon, it's actually Xorg or libinput, whichever is handling the touchpad on your system. I reported this bug against Cinnamon erroneously, not really understanding the difference at the time.

The answer is that both Xorg and libinput are substantially improved regarding thumb ignoring than they were in 2013. I'm using libinput now and have filed a goodly number of bugs to make it even better:

- https://bugs.freedesktop.org/show_bug.cgi?id=98799
- https://bugs.freedesktop.org/show_bug.cgi?id=98800
- https://bugs.freedesktop.org/show_bug.cgi?id=98801
- https://bugs.freedesktop.org/show_bug.cgi?id=98802
