### ISSUE TITLE
bugs/inconsistencies in the system settings application

### ISSUE THREAD

**Issue by vitamins** [linuxmint/Cinnamon#2561]
Trying out cinnamon in virtualbox, these are inconsistencies i came across. I am not sure how much of them are due to running cinnamon from within virtualbox, but i am sure that at least some of them can be reproduced.

- enabling network time does not return any error although ntpd is not installed
- network time can be toggled without entering a password by pressing on cancel in the password entry program
- the screensaver requires a password to be entered, although this is unset in
the screensaver settings
- the network applet says 'no connection', whilst i can ping google without
error
- the 'applications and media' settings have a huge empty space in between
the settings for default applications, and the autorun settings, which is not
decreasing, when the window is made smaller
- Energy settings says 'charging' whilst the battery is not charging
- In 'Regional settings' i can select a lot of languages that are not actually
available on the system backend, whithout error. Upon restart cinnamon falls back to
the installed language.
- If i set a different language in 'Regional Settings' the X input keyboard layout is
not actually changed until i select the new layout in the applet at the bar 
on the bottom
- When changing between the 'expert' and 'standard' option in the settings          
application, often nothing changes, even though the button is displayed

This happens on an up to date arch linux OS with no additional applications installed besides the cinnamon packages.

This does probably not qualify for a bug report:
- The menu and the gear in the left hand bottom corner are lighting up
seperatly when hovered, but they trigger the same menu, which is confusing.

**Comment by JosephMcc** [comment]
Closing old issues where the OP never responded to queries for new info.
