### ISSUE TITLE
[Enhancement] Allow more control over screenshot mechanism, including hotkeys, etc..

### ISSUE THREAD

**Issue by sb56637** [linuxmint/Cinnamon#2564]
Hi, I don't like the behaviour where gnome-screenshot saves a screenshot into my Pictures folder. I tried to set a custom keyboard shortcut to run "/usr/bin/mate-screenshot" and assigned it to the "Print Screen" key. It allows the shortcut to be created, but it doesn't work. Any suggestions?

Thanks a lot!

**Comment by rjanja** [comment]
@mtwebster In Linux Mint 17.1 I was able to clear default screenshot keybindings and then bind the print key to custom programs. Right now I have it bound to Desktop Capture in applet settings. It works great.

@lackovic I recommend not waiting for an LMDE update and instead considering Debian Testing, Mint 17.1 or another distribution that provides Cinnamon.
