### ISSUE TITLE
Cinnamon 2.0 system tray wrong size icons or icons not appearing

### ISSUE THREAD

**Issue by geckolinux** [linuxmint/Cinnamon#2566]
Hi, I'm using Cinnamon 2.0.6 on Manjaro Linux. The system tray is very buggy. The Pidgin icon is far too small. The Transmission icon often does not display. When I disable and then re-enable the Transmission icon, it displays. But when I close and re-start Transmission, the system tray briefly blinks, but the tray icon does not appear for Transmission. I have confirmed that this bug does not occur under Mate.

Thanks!

**Comment by Vahan86** [comment]
@geckolinux, is this still an issue for you in Cinnamon 3.0?

**Comment by geckolinux** [comment]
There's still some janky behavior at times, but it's generally OK.
