### ISSUE TITLE
in Settings > Keyboard > Keyboard shortcuts, add "Edit shortcut" button

### ISSUE THREAD

**Issue by kenden** [linuxmint/Cinnamon#2567]
- In Settings, click Switch to Advanced Mode,
- Click Keyboard,
- go to the Keyboard shortcut tab
- click a shortcut (ex Cinnamon)
----> there is apparently no way to edit the shortcut
       (in reality, there is, you need to double click on the shortcut and
        a custom shortcut will open)

It should be more evident how to edit a shortcut:
add a "Edit custom shortcut" between the "Add custom shortcut" and the "Remove custom shortcut" button.

This is on Mint 15

**Comment by JosephMcc** [comment]
Cinnamon settings has seen a large revamp. Hovering over a shortcut key binding brings up a tooltip with instructions on how to use it.

**Comment by kenden** [comment]
@joaorb64 Thanks. It's nice to get a tooltip.
But that tooltip is hard to discover (hover a second over a keyboard bindings: not obvious. It the only place in the keyboard preferences that does this).
There is a Add button and a Remove button. An Edit button seems logical. 
Grey it out if nothing is selected.
