### ISSUE TITLE
Make dependency on pulseaudio optional

### ISSUE THREAD

**Issue by felipec** [linuxmint/Cinnamon#2574]
Not everybody uses PulseAudio, it would be nice to be able to use Cinnamon without PulseAudio, like in other desktop environments like Xfce and Enlightenment.

Ideally cinnamon-settings-daemon would use ALSA instead of PA, but for a start it could disable all audio support if PA is not available.

**Comment by rnnr** [comment]
Pulseaudio as a mandatory dependency is the only reason I won't install Cinnamon. Please at least add the removal to your roadmap.

**Comment by leigh123linux** [comment]
Closed as 'wont fix'

**Comment by felipec** [comment]
If you want less users by all means don't implement this. I'll stay away from Cinnamon.

**Comment by NTULINUX** [comment]
Staying away from Cinnamon also because of this. Cinnamon technically doesn't need any sound support at all, that's what `alsamixer` and such are for.
