### ISSUE TITLE
Add UI configuration to resize with right button

### ISSUE THREAD

**Issue by felipec** [linuxmint/Cinnamon#2575]
The configuration /org/cinnamon/desktop/wm/preferences/resize-with-right-button should be available through the UI, I think only in the "advanced mode".

In fact, I think the default should be true, as that has been the standard in most DEs since a long long time.

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html
