### ISSUE TITLE
[network manager applet] jiggling toggle

### ISSUE THREAD

**Issue by VolMi** [linuxmint/Cinnamon#2582]
In the network manager applet, when I (dis-/en-)able wifi, the toggle does not have a simple transition `on → off` or vice versa, but instead jiggle-jumps between both states.

In this screencast, I clicked the button exactly twice (`on → off` & `off → on`):
https://dl.dropboxusercontent.com/s/uacyj1gqa1hajap/Cinnamon_nm-applet.webm

**Comment by anandrkris** [comment]
Not sure if this [patch] (https://github.com/linuxmint/Cinnamon/commit/2eb6586ce7f49fae601f45fe9375fac44ad8c252) addresses this issue as the dropbox link is unavailable now...

**Comment by VolMi** [comment]
Thanks for knocking, anandrkris. The main issue here is not reproducible in cinnamon 2.4. The transition is still not smooth but instant. But that was not the scope of this issue so I'm closing this.
