### ISSUE TITLE
/usr/lib/cinnamon-control-center in cinnamon-settings/bin/capi.py under a 64 bit box

### ISSUE THREAD

**Issue by marguerite** [linuxmint/Cinnamon#2585]
Hi, dear developers,

You used a hardcoded path "/usr/lib/cinnamon-control-center" in /usr/lib/cinnamon-settings/bin/capi.py which will cause modules provided by cinnamon-control-center can't be loaded on a 64bit environment.

cinnamon-control-center is not architecture independent, eg: libsound.so it provides is of course different on a 32bit from the one on a 64bit box. so hardcode "/usr/lib/cinnamon-control-center" is not corrent. 

We'd better us python OS function to determine the path.

**Comment by Vahan86** [comment]
@marguerite, is this still an issue in Cinnamon 3.2?

**Comment by leigh123linux** [comment]
Fixed by this commit https://github.com/linuxmint/Cinnamon/commit/dd2efa25cd3e2f9d3b27ff0bebaf7dcb573baa9a
