### ISSUE TITLE
cinnamon and gnome-shell both claims ownership for nm-applet

### ISSUE THREAD

**Issue by marguerite** [linuxmint/Cinnamon#2587]
eg, if you run "cinnamon --replace" inside a working gnome-shell with a running network connection.

It will certainly fail, because the nm-applet requirement for cinnamon-session (or cinnamon itself?) can't be met when a NetworkManager is already running.

This case doesn't happen on KDE which uses networkmanager-kde.

I know in real life no one will run cinnamon with a running gnome-shell with the same user name at the same time. But it's better we detach further from gnome-shell in this case, it'll help testers.

**Comment by leigh123linux** [comment]
This isn't a real issue.
