### ISSUE TITLE
Holding down ALT inside a window

### ISSUE THREAD

**Issue by Jace-** [linuxmint/Cinnamon#2590]
If a person holds down ALT in a window, and clicks their mouse, it'll interpret it as a dragging motion. This means a user is unable to ALT-click a button, i.e. on tumblr, or inside photo editing suites to move/select. 

Even if this is turned off (i.e. by changing the modifier in Window settings), the ALT key becomes useless if used in conjunction with the cursor.

**Comment by Vahan86** [comment]
@Jace-, is this still an issue for you with Cinnamon 3?

**Comment by JosephMcc** [comment]
This issue is old. It works as expected for me.
