### ISSUE TITLE
Idea: Cinnamon Styles for the Context Menu?

### ISSUE THREAD

**Issue by mintystark** [linuxmint/Cinnamon#2592]
Is there any way that context menus can use Cinnamon styling like Applets do.

I know this may mean you need to replace the GTK context menu with a newly coded cinnamon context menu, but this would really tie in the entire design and theme and make Cinnamon feel more whole.  Not to mention it would look much better then the default one as it would allow for rounded corners, etc.
Of course make sure there is a specific css class (.context-menu) on it for theme creators to manage it.

I know that some people might not like it as they might prefer the GTK theme instead so a setting to turn this on and off would best.

Thanks

**Comment by JosephMcc** [comment]
I know this is old and just happened to run across it. This isn't something we want to do though.
