### ISSUE TITLE
Can't run ./autogen.sh first then "dpkg-buildpackage"

### ISSUE THREAD

**Issue by marguerite** [linuxmint/Cinnamon#2594]
Hi, 

This is an issue I found when helping Chitwanix developers to get their cinnamon compiled.

Produced on Ubuntu 12.04 (precise):

1. git clone
2. install gnome-common and `./autogen.sh`
3. run `dpkg-buildpackage`

An `exit 1` error will happen to dh_autoreconf_clean process, because:

It tried to apply the `as-needed` patch to `config/ltmain.sh`.

Which is actually correct if you have run `./autogen.sh`. (meaning that file don't need to be patched in such case)

But `./autogen.sh` will be the first command we run to get depdencies, before running `dpkg-buildpackage`.

So this is an issue and should be fixed in debian/rules.

**Comment by ManIVIctorious** [comment]
@JosephMcc I think this can be closed
