### ISSUE TITLE
cannot set up regional settings/format in cinnamon

### ISSUE THREAD

**Issue by joequant** [linuxmint/Cinnamon#2595]
Forwarding bug from Mageia.  Please let us know if this is/is not reproduciable elsewhere.  We are currently on 2.0.4

https://bugs.mageia.org/show_bug.cgi?id=11578

If i try to set up the regional settings, under formats tab, i can't because the list is empty, can't add/modify anything.
Therefore i can't set up currency, measurement, dates, times, and also because of that first day of the week in calendar cannot be modifyed.
(first day of the week should change automaticaly after setting up those regional/format settings.)

Version-Release number of selected component (if applicable):
Cauldron/Cinnamon

How reproducible:
everytime i attempt to modify the regional/format settings

Steps to Reproduce:
1.Click menu, tools, system settings, regional settings, tab formats.
2.try to add/modify

**Comment by Vahan86** [comment]
@joequant, is this still an issue for you with Cinnamon 3.0?

**Comment by JosephMcc** [comment]
This is no longer relevant.
