### ISSUE TITLE
Menu applet icon changed to mint icon

### ISSUE THREAD

**Issue by i23098** [linuxmint/Cinnamon#2605]
Using Ubuntu 13.10 x64 and today cinnamon got updated. The menu icon changed from the "normal" gear icon (like http://connectwww.com/wp-content/uploads/2012/02/Cinnamon-menu.jpeg) to the mint icon (like http://cinnamon-spices.linuxmint.com/uploads/applets/L2H2-YESQ-DADW.png)

**Comment by jonataswalker** [comment]
> https://github.com/linuxmint/Cinnamon/blob/master/data/theme/menu.svg

404
