### ISSUE TITLE
Enabling Vertical Sync causes black screen in games.

### ISSUE THREAD

**Issue by Filar** [linuxmint/Cinnamon#2614]
When I enable vertical sync in amdcccle settings, games in Cinnamon go black at start. Example game is Super Meat Boy. My graphics card is AMD hd7670m. Even though I'm using Arch Linux now, a year or so age the same bug occured to me on Mint when I tried to start Heroes of Newerth. I'm using 3.11.6 kernel and catalyst 13.11 driver.

**Comment by Vahan86** [comment]
@JosephMcc, can we close the issue since there is no response from OP for almost 2 years?
