### ISSUE TITLE
Can not save background image settings. 

### ISSUE THREAD

**Issue by knutj** [linuxmint/Cinnamon#2627]
https://bugzilla.redhat.com/show_bug.cgi?id=1029554

When I save background setting using cinnamon setttings. I wil change back to default when I move to another workspace.

**Comment by cobrafast** [comment]
This still happens to me in Cinnamon 2.4.6.
I am unable to permanently change my desktop background, whenever I switch workspace or restart cinnamon, the previous background settings are restored.
I am not sure where the old settings are coming from as `gsettings get org.cinnamon.desktop.background picture-uri` reports the correct path after changing the background image.

**Comment by cobrafast** [comment]
I managed to solve the problem.
The `wallpapoz` tool, which I don't remember installing (it may have come with a fedora upgrade), did it.
Killing its uninstalling it through yum and then killing its process fixed the issue.
