### ISSUE TITLE
Disconnect from Wireless Network within Network Applet

### ISSUE THREAD

**Issue by clfarron4** [linuxmint/Cinnamon#2629]
At current, to disconnect from a wireless network, one can:
- connect to another network.
- turn off wireless completely and then turn it back on again.
- go to the network settings and disconnect from the network there.

Request: I would like to ask if an entry for disconnecting from the wireless network (whilst keeping the network card up) could be included in the applet.

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html
