### ISSUE TITLE
Keyboard settings reset after putting cinnamon to sleep

### ISSUE THREAD

**Issue by chrisbra** [linuxmint/Cinnamon#2635]
Hi,
I noticed, that whenever I resume from sleep my cinnamon session, my keyboard changes from nodeadkeys to deadkeys. I find this really disturbing. I hope this can be fixed easily.

Thanks,
Christian

**Comment by Vahan86** [comment]
@JosephMcc, can we close this issue due to lack of response from OP?

**Comment by chrisbra** [comment]
Am 2016-09-08 05:35, schrieb Vahan Harutyunyan:
> @JosephMcc [1], can we close this issue due to lack of response from
> OP?

sorry, I cannot test anymore, since I had to give up my linux 
workstation.
