### ISSUE TITLE
Wifi indicator icon doesn't change when network is disconnected.

### ISSUE THREAD

**Issue by Samuel789** [linuxmint/Cinnamon#2641]
When connected to a wifi network, disconnecting from the network should cause the indicator icon to change and reflect that you are no longer connected to a network. However, if you disconnecting by disabling your computer's wireless hardware (in my case with a keyboard shortcut) or using the indicator menu, the indicator icon does not change. The indicator itself, when clicked, knows the network is not connected, but the icon continues to imply that it is connected.

**Comment by JosephMcc** [comment]
https://github.com/linuxmint/Cinnamon/issues/1762
