### ISSUE TITLE
Regional keymap layout issues in cinnamon 2.0

### ISSUE THREAD

**Issue by croutch** [linuxmint/Cinnamon#2645]
I can not use my keyboad language even if i set it thrue system-settings/regional-settings. Now i have US keyboard but i want swedish.
All other language settings are like they should for me.

This post show same problem.
https://forums.gentoo.org/viewtopic-t-975620.html

**Comment by Vahan86** [comment]
It works fine for me in Cinnamon 3.0.
@croutch, is this still an issue for you?
