### ISSUE TITLE
Cinnmaon Menu-Icon not showing when using latest fglrx beta

### ISSUE THREAD

**Issue by krissel** [linuxmint/Cinnamon#2667]
Hi!
Im running Mint 16 on a Dell Vostro with an AMD Radeon 6630M. When i install the latest fglrx Beta driver from amd.com, the Icon on the Mint Menu disappears. If i switch to the integrated intel GPU or the Open Source Radeon driver, everything appears to be fine. I have not encountered any other Bugs when using fglrx. 

(As a side note: Using the fglrx provided in the Repos makes Cinnamon crash on startup, but thats another issue)

**Comment by Vahan86** [comment]
@JosephMcc, can we close this issue since there is no response from OP for 2 years?
