### ISSUE TITLE
Cinnamon 2.0 Virtualbox 4.2.20 Switching desktops impossible

### ISSUE THREAD

**Issue by taidoka** [linuxmint/Cinnamon#2672]
I don't know if this is a Cinnamon issue or an issue of Virtualbox.
But running my virtual machine in fullscreen mode makes it impossible to switch Screens.
Any help is appreciated. 

Thanks
taidoka

**Comment by Vahan86** [comment]
@JosephMcc, can we close the issue since there is no response from OP for 2 years?
