### ISSUE TITLE
Make automatic-mnemonics off operationnal

### ISSUE THREAD

**Issue by geoffm** [linuxmint/Cinnamon#2680]
In dconf I have set both
/org/gnome/desktop/interface/automatic-mnemonics false
/org/cinnamon/desktop/interface/automatic-mnemonics false
but the keybindings still don't appear in menus and buttons. This used to work in previous cinnamon versions.
Users need to see the keybindings in order to know they exist.

**Comment by Vahan86** [comment]
@geoffm, is this still an issue for you with Cinnamon 3?

**Comment by JosephMcc** [comment]
It is. That setting doesn't seem to do anything.

**Comment by JosephMcc** [comment]
The way this works changed somewhere around gtk3.10 and I don't believe gtk honors it any longer.
