### ISSUE TITLE
Secondary Monitor Flickers off/on with Screensaver

### ISSUE THREAD

**Issue by eumario** [linuxmint/Cinnamon#2684]
I'm using Nvidia 319.60 drivers, with a GeForce 210(GT218), on a dual monitor setup.  Primary monitor is connected via DVI, secondary Monitor is connected through VGA.  When the monitors go to sleep, after about 3 to 5 minutes, the secondary monitor pops back on, as though the screen is coming out of sleep mode, but always displays that it isn't receiving a signal, then powers back off after 15 seconds.  It repeats this loop for the longest time.  This is with the latest Cinnamon 2.0.14 on the Release Candidate of Petra.

**Comment by Vahan86** [comment]
@JosephMcc, since there is no response from OP for 2 years, can we close the issue?
