### ISSUE TITLE
Window snapping suggestion

### ISSUE THREAD

**Issue by imarkskinner** [linuxmint/Cinnamon#2688]
Love the new window snapping feature great work on that, I have an idea that would make it even cooler. In the cinnamon setting: [system settings > windows > action on title bar double/middle/right click] a great option would be to toggle snapped or tiled state.

So say I have a normally positioned window, it could be central and taking up about 80% of the screen, then I drag it to snap it to the top right corner, then double clicking it once will return to its central 80% size and a second double click will return again to top right corner snapped position.

What do you think?

I've dropboxed a video to illustrate exactly what I mean, in case its not clear enough, https://www.dropbox.com/s/dkm2h7qkaqpj7b2/screencast_2013-12-04_17%3A50%3A31.webm

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html
