### ISSUE TITLE
Spotify causes cinnamon to freeze frequently

### ISSUE THREAD

**Issue by Viavarian** [linuxmint/Cinnamon#2693]
When running spotify for a while, some part of the UI will "break" and any clicks to that region (e.g. the activitiy feed to the right or the center part) will cause cinnamon  to freeze.

If I restart cinnamon on another VT, clicking the problematic region again will have the same effects. Restarting spotify fixes the problem (until it happens again, anyway).

Sometimes even clicking the taskbar or pressing alt+tab will cause the freeze - in that case not even restarting spotify helps.

Cinnamon prints the following every time it happens:
(cinnamon:13161): St-WARNING **: percentage lengths not currently supported
    JS ERROR: !!!   Exception was: Gio.IOErrorEnum: Vorgang wird nicht unterstÃ¼tzt
    JS ERROR: !!!     message = '"Vorgang wird nicht unterstÃ¼tzt"'
    JS ERROR: !!!     fileName = '"/usr/share/cinnamon/applets/sound@cinnamon.org/applet.js"'
    JS ERROR: !!!     lineNumber = '714'
    JS ERROR: !!!     stack = '"0 anonymous("result" = [object _private_Gio_Task], "cover" = [object _private_unknown_GDummyFile])@/usr/share/cinnamon/applets/sound@cinnamon.org/applet.js:714
"'

And occasionally it's also repeating the following three messages:
(cinnamon:12850): Clutter-CRITICAL **: clutter_text_get_editable: assertion 'CLUTTER_IS_TEXT (self)' failed
(cinnamon:12850): Clutter-CRITICAL **: clutter_text_get_text: assertion 'CLUTTER_IS_TEXT (self)' failed
(cinnamon:12850): Clutter-CRITICAL **: clutter_text_set_text: assertion 'CLUTTER_IS_TEXT (self)' failed

I'm using Ubuntu 13.10 and Cinnamon 2.0.14 (also happens with older versions of Ubuntu and Cinnamon, though).

**Comment by Vahan86** [comment]
@JosephMcc, there is no response from OP for almost 2 years. Can we close this issue?
