### ISSUE TITLE
Image Get's Blurry 

### ISSUE THREAD

**Issue by ripgeneral** [linuxmint/Cinnamon#2699]
Cinnamon 2 is cool ,but  I have major installed linux mint 16 petra . CInnamon 2.0.13+petra
Have dual 1920*1080 screen. Why my screen getting fuzzy or blurry ? Trying to fixing it,but nothing helps.I will send you any files you need just help.

**Comment by Vahan86** [comment]
@ripgeneral, is this still an issue for you with Cinnamon 3.0?

**Comment by Raffles727** [comment]
This happened to me now in Dec 2018 with the latest version of Cinnamon and Ubuntu 18.04, so it is still an issue within Cinnamon. Turning off FXAA also solved it for me.

**Comment by JelleJansen** [comment]
Same intermittent issue here in February 2020. Nvidia K2200 with dual 1080p display and turning off FXAA + reboot fixed it. Took a while to find the root cause and this thread, but apparently @brendor beat me to the punch with a workaround in 2014! :beers:

**Comment by Bfitzy** [comment]
Had the same problem with Tara (Mint 19) with NVIDIA 550Ti, disabling FXAA and upgrading to Tricia however fixed it.
