### ISSUE TITLE
huge tiff files cause cinnamon to max out cpu and eat endless amount of RAM

### ISSUE THREAD

**Issue by kaefert** [linuxmint/Cinnamon#2703]
I've observed this very hard to track bug (cpu & memory usage) of cinnamon for more than a year now, reformatting my system and setting up the latest linux mint solved the issue for me in most cases.

This time I've taken more care of what I'm doing and I've been able to pin down the cause of this bug (for me) - It's the fact of having large tiff files (several GB in size, with 90.000 x 90.000 pixels in size) in my ~/Pictures folder. Moving the tiff away to an external disk using a terminal gets me back to normal operation.

I've configured nemo to NOT thumbnail files larger than 100 Megabytes, so this should not be the problem (unless the config is ignored somewhere?)

I'm currently running Mint 16 with all updates, but I've observed this bug since at least Mint 14 if not older (can't remember exactly when it first started, sorry)

If you need one of those huge tiff files, just write me an email and I will upload one for you.

**Comment by Vahan86** [comment]
@kaefert, is this still an issue in Cinnamon 3.0.x?

**Comment by kaefert** [comment]
hey there Vahan86! Thanks for asking. I just tried it on my Linux Mint 18 Cinnamon installation, and it seems now "only" Nemo goes crazy when seeing such a large TIF file, the Cinnamon process seems unimpressed.

Nemo does eat a lot of memory with such a tif file in its view, but it seems to hold stable at 21% (of 10GB RAM). The more annoying thing about nemo's behaviour is that it eats one CPU core 100%.

**Comment by JosephMcc** [comment]
This probably best moved to Nemo https://github.com/linuxmint/nemo/issues

**Comment by kaefert** [comment]
I created this entry in the nemo issue tracker: https://github.com/linuxmint/nemo/issues/1311
