### ISSUE TITLE
Suspend Problem

### ISSUE THREAD

**Issue by nfat** [linuxmint/Cinnamon#2705]
When suspend pc, after suspend all applet icons and texts (time etc.) and  looks streaky.
http://imgim.com/screenshotfrom2013-12-0714:30:54.png
http://imgim.com/screenshotfrom2013-12-0714:53:35.png

after cinnamon restart problem fix

Cinnamon 2.0.14
Arch Linux x86_64
nvidia gt 440 - nvidia driver 331.20

**Comment by JosephMcc** [comment]
This for cinnamon 2.2 and the OP never responded to the request to try with a newer version so I'm closing it.
