### ISSUE TITLE
Cinnamon Settings > Fonts > Add / Install option

### ISSUE THREAD

**Issue by anandrkris** [linuxmint/Cinnamon#2707]
I downloaded multiple font (*.ttf) files.
If I wanted to add all downloaded fonts, there should be an option to browse and (multi-)select font files?
Currently, I have to open each one of them and install individually. 
P.S. I added a nemo action issue as well for right-click and install multiple files.

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html
