### ISSUE TITLE
Cinnamon Screensaver - Pidgin - Away on lock

### ISSUE THREAD

**Issue by anandrkris** [linuxmint/Cinnamon#2708]
pidgin-awayonlock plugin to set as away on screensaver activation requires gnome-screensaver. Can this not work Cinnamon Screensaver ?

**Comment by Vahan86** [comment]
@JosephMcc, I think this issue is related to cinnamon-screensaver and should belong here: https://github.com/linuxmint/cinnamon-screensaver/issues

**Comment by JosephMcc** [comment]
There is already an issue for this in cinnamon-screensaver.
