### ISSUE TITLE
Holidays in Calendar

### ISSUE THREAD

**Issue by SteliosSk** [linuxmint/Cinnamon#2713]
I hope this is the correct place to express my request.
I wonder if it is possible to add the holidays feature in the calendar in the taskbar of cinnamon.
I mean something similar to the KDE calendar, which displays holidays and events when clicked.
Thank you for your attention.

**Comment by dalcde** [comment]
#2720

**Comment by dtrunk90** [comment]
What about the people using other mail clients like Thunderbird?

**Comment by dalcde** [comment]
Evolution is just what was written it the title. If we are going to support anything, it would be a generic protocal such as iCal. I definitely don't see tying in to one specific application (cf. sound applet - we don't just support, say, banshee)
