### ISSUE TITLE
Keyboard shortcuts not working

### ISSUE THREAD

**Issue by luther7hrol** [linuxmint/Cinnamon#2714]
I use Arch Linux with Cinnamon desktop. Keyboard shortcuts don't work whatever I try to set up in it using Preferences/Keyboard/Shortcuts menu. As far as I can remember, when I played around with Linux Mint 15 Olivia Cinnamon, it did not work either.

uname -a

Linux localhost 3.12.1-3-ARCH #1 SMP PREEMPT Tue Nov 26 11:17:02 CET 2013 x86_64 GNU/Linux

cinnamon --version

Cinnamon 2.0.14

**Comment by ManIVIctorious** [comment]
Is this still an issue in cinnamon 3.0?
Are the shortcuts never working, or only if you have any applets open?

**Comment by atomi** [comment]
I have this problem as well with Cinnamon 3.0.7
Linux CINNAMON 4.4.0-36-generic #55-Ubuntu SMP Thu Aug 11 18:01:55 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

Specifically setting Windows Minimize to Super+Down

**Comment by Vahan86** [comment]
@JosephMcc, can we mark this issue as a bug?

**Comment by JosephMcc** [comment]
The original bug report is about it not working from cinnamon settings. Based on the follow up and my own testing it now seems to work properly.
