### ISSUE TITLE
requested options: expo all windows on all workspaces; move entire workspace over

### ISSUE THREAD

**Issue by allenbina** [linuxmint/Cinnamon#2717]
I'm using the "windows quick list" applet on my panel which does a great job.  I would like to be able to use expo as one keyboard shortcut to see all the windows on my current workspace, and have another keyboard shortcut to see all windows on all workspaces.  

I also find it helpful to be able to move entire workspaces around on osx.  If you could add the option to move workspaces around that would be excellent.

Thanks!

**Comment by WildPenquin** [comment]
I'm seconding the re-arranging of workspaces (move entire workspace over). I find it such a basic feature, and I'm often missing it (it's available in all other desktops with workspaces I have used). The natural place would be the current Éxpo view (e.g. D&D from a non-window part of a Workspace (and / or the Workspace name) to another Workspace). 

I'm guessing a guick way to code it would be to make a feature to just move all windows to target Desktop. Even if there is no real arranging of the desktops, that would work for most cases. 

With a little more automation, it would even appear to the user exactly identical as arranging the Workspaces: Swap windows between target <-> source if they are adjacent, and if not, then windows could be moved automatically to the next/last workspace (from target and in-between workspaces) to create the desired effect. Even "0" windows should be moved (essentially allowing inserting new desktops).

Things will get somewhat more complicated, if there will be some Workspace-specific settings in the future; AFAIK currently there are none. But even then, just moving the windows is what the user probably wants.

But, things could get complicated if there are more than one monitor (especially with workspace-specific settings and/or different resolutions on monitors). I'm not sure how it is handled in other desktops; creating a new one, moving the windows and deleting the source, would probably be simplest and most intuitive.

Cheers!
