### ISSUE TITLE
legacy snapping makes snapping-UI stick and prevents any interaction with other windows

### ISSUE THREAD

**Issue by kaefert** [linuxmint/Cinnamon#2718]
Running Linux Mint 16 with Cinnamon 2.0.14

In the System Settings -> Window Tiling and Edge Flip
When both "Enable Window Tiling and Snapping" and "Enable legacy window snapping (hold <Shift> while dragging a window" are checked
When moving a window so that the new snapping UI
![cinnamon-dock-bar](https://f.cloud.github.com/assets/1448723/1722256/5c7d630c-623d-11e3-9fb4-59e87dc04539.png)
shows while holding Shift to enable legacy snapping, then the snapping UI will not disapear after ending the window-move-action by releasing the mouse button - and the user will not be able to interact with any window but the one just moved. To get back to normal the user has to move the same window again either without legacy snapping or in a way that will not trigger the new snapping-UI

**Comment by Vahan86** [comment]
@kaefert, does this issue still occur in Cinnamon 3.2?

**Comment by JosephMcc** [comment]
I cannot reproduce this on git master.

**Comment by kaefert** [comment]
no, I cannot reproduce this either on an up to date Linux Mint 18.1 installation.
