### ISSUE TITLE
right-click "add applet" option+ "lock features"

### ISSUE THREAD

**Issue by freemangilgamesh** [linuxmint/Cinnamon#2719]
1- I suggest you add the gnome 2 add applet feature. Users can add applets without going to the settings

2- Lock features option: I suggest you add a "lock features" option to Cinnamon: users can lock all feature while they are logged in as admins. Why! Because some people use  or work on the same computer and anyone can mess with the themes or applets or panel! What I mean that users can maintain many functionalities like installl and remove software and edit themes and all while they can protect their desktop from unexperienced users! This is very useful at scholls! My student keepmessing my panels and themes all the time. This feature should ban any user, except the root, from editing themes or even change wallpaper!

**Comment by dalcde** [comment]
1) The consensus seems to be that the current situation is sufficient
2) There is such thing as user accounts. If you let people use your account, you can't blame them for messing around! With that said, https://help.gnome.org/admin/system-admin-guide/stable/dconf-lockdown.html.en

**Comment by locness3** [comment]
I am currently trying to lockdown Cinnamon's settings, for an imaginary public computer setup where users would have their own accounts.

> With that said, https://help.gnome.org/admin/system-admin-guide/stable/dconf-lockdown.html.en

This seems to work for all settings which are stored in dconf. However, it appears that panel applets (including default ones) are instead storing their configuration within JSON files. Is there any way to lockdown these settings? I think these are amongst the most important things that users should better not be able to modify.
