### ISSUE TITLE
Evolution Integration Into Calendar Applet

### ISSUE THREAD

**Issue by MiguelQu** [linuxmint/Cinnamon#2720]
Please consider the integration of evolution into the default calendar applet.    Thanks in advance!

**Comment by mfreeman72** [comment]
Has there been any work done toward this? I still have a basically useless calendar sitting on my panel, and would love to have it become functional.

**Comment by mfreeman72** [comment]
@clefebvre Are there any plans for anything like this?

The calendar in the date/time applet is too non-interactive. What it really needs is some way of displaying and adding/editing/deleting appointments on selectable dates. It would be even better if it could also sync with installed calendar programs and/or online services, such as Google Calendar or any calendar with live online calendar URL's (ical, etc.).

If I knew how, I would try hammering out an applet of my own. Unfortunately, I don't have time to learn how to do that.

**Comment by hako1** [comment]
Since Ubuntu gave up on Unity and moves to Gnome, I tried Gnome with 17.04 1nd 17.10. Gnome is mostly a poor experience, so I installed Cinnamon on Ubuntu 17.10.
Many things work much better now. However, I miss the integrated date/calendar applet of Gnome and Unity.
Would be really nice to have such an applet in Cinnamon.

**Comment by uocxp** [comment]
I think many Cinnamon users miss this feature! It is really important to have an interactive calendar applet.

**Comment by ikuria** [comment]
oh yes, plz - big need!

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html

**Comment by mfreeman72** [comment]
@JosephMcc Just out of curiosity: Is anything being done with our suggestions? It's been three years since this was closed, and the current calendar applet is pretty much the same as it was from Cinnamon version 1. At least in function and appearance.
