### ISSUE TITLE
Improve Keyboard shortcuts dialog

### ISSUE THREAD

**Issue by geoffm** [linuxmint/Cinnamon#2724]
The keyboard shortcuts dialog could be improved by putting the bindings in columns next to the shortcut action nameses, instead of putting them separately with the user having to select a shortcut to see its bindings. If bindings were put in columns next to the shortcut action the user could see what the bindings are for every shortcut.
Additionnally:
- The Keyboard shortcut space should be resizable so that if we make the window bigger, it uses the newly available space;
- The add custom shortcut window should link the "Enter" key, to the "Update" or "Add" button
  ![cinnamon keyboard shortcuts dialog](https://f.cloud.github.com/assets/901518/1739463/a9fdb93a-639e-11e3-853d-744d44dbd647.png)

**Comment by Vahan86** [comment]
Keyboard Shortcuts window has been redesigned and the issue with wasted space is solved. The "space should be resizable" request is also implemented.

![22](https://cloud.githubusercontent.com/assets/12819058/20315781/969dac54-ab78-11e6-86f4-76a8be811542.png)
