### ISSUE TITLE
Add applets to top panel should add applets to the top panels not the bottom one

### ISSUE THREAD

**Issue by freemangilgamesh** [linuxmint/Cinnamon#2728]
When I change the panel layout settings to one panel at the top and another one at the bottom and try to add applets to the new one, they are automatically added to the default panel. Add applets to top panel should add applets to the top panels not the bottom one like on Mate and gnome2!

**Comment by dalcde** [comment]
Fixed via https://github.com/linuxmint/Cinnamon/commit/2d1d5417d6b9eaced744a944d822e7a871601713
