### ISSUE TITLE
config.status: error: po/Makefile.in.in was not created by intltoolize.

### ISSUE THREAD

**Issue by ghost** [linuxmint/Cinnamon#2729]
When I try to compile cinnamon 2.0.14 I see this message : 

hecking pkg-config is at least version 0.16... yes
checking for GLIB - version >= 2.0.0... checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes (version 2.38.2)
checking location of system Certificate Authority list... /etc/ca-bundle.crt
checking that generated files are newer than configure... done
configure: creating ./config.status
yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/nix/store/q09m5iknwzqcb4js54pmghzqzd18wz08-gcc-wrapper-4.6.3/bin/ld) supports shared libraries... yes
checking whether -lc should be explicitly linked in... config.status: creating Makefile
no
checking dynamic linker characteristics... config.status: creating data/Makefile
config.status: creating js/Makefile
config.status: creating js/misc/config.js
config.status: creating src/Makefile
config.status: creating tests/Makefile
config.status: creating po/Makefile.in
config.status: creating man/Makefile
config.status: creating files/Makefile
config.status: creating config.h
config.status: executing depfiles commands
config.status: executing libtool commands
GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no
checking how to run the C++ preprocessor... config.status: executing po-directories commands
config.status: creating po/POTFILES
config.status: creating po/Makefile
g++ -E
config.status: executing po/stamp-it commands
config.status: error: po/Makefile.in.in was not created by intltoolize.

Roelof

**Comment by ManIVIctorious** [comment]
@ghost Any news on this? Is this still an issue?

**Comment by JosephMcc** [comment]
Closing due to lack of response.
