### ISSUE TITLE
Nemo file sorting issues

### ISSUE THREAD

**Issue by msknight** [linuxmint/Cinnamon#2736]
Hi Folks,

Using 64 bit Mint 16, Cinnamon 2.0.14 with Nemo 2.0.8 

File sort order is apparently 00, 0A, 0B, 0C, 0D, 0E, 0F, 01, 02, 03 .. 09

Should be 00, 01, 02 .. 09, 0A, 0B, ... 0F

Also, If I have two files, "0A" and "0B" and I then try and rename "0B" to "0a" (a perfectly valid Linux file name) it complains that the file already exists.  It appears that Nemo is being case insensitive in its matches where it needs to be case sensitive.

**Comment by JosephMcc** [comment]
This bug belongs to Nemo, not Cinnamon.
