### ISSUE TITLE
Screen not turning off after inactive time interval

### ISSUE THREAD

**Issue by hordurk** [linuxmint/Cinnamon#2738]
My screen recently stopped turning off after the inactive time set in "Screensaver & Lock Settings". I believe this must have stopped working with the latest apt-get upgrade that I did, bringing Cinnamon to 2.0.14.
Before this I was still battling the 2 lock screen issue, but now I'm unable to get any auto-lock at all.
I'm running Cinnamon 2.0.14 from the gwendal-lebihan-dev ppa on Ubuntu 12.04.3 64-bit.

Please let me know what other information I can provide to help figure out what the issue is.

**Comment by anandrkris** [comment]
No feedback. Can be closed.
