### ISSUE TITLE
Network manager Applet issues -  UI Redesign + Meta Bug

### ISSUE THREAD

**Issue by anandrkris** [linuxmint/cinnamon#2746]
This is more of a suggestion / feature request than an issue - I came across the below link where KDE n/w applet prototype designs are being discussed and thought will bring it to developer's notice.

http://grulja.wordpress.com/2014/02/14/final-shape-of-plasma-nm
http://user-prompt.com/connect-to-network-manager-prototype/
http://user-prompt.com/knetworkmanager-approaching-the-finishing-line/
http://user-prompt.com/kde-network-manager-details-sorted/
http://forum.kde.org/viewtopic.php?f=285&t=119742&sid=031f412655735293e130867c0fb1dbde

In the current Cinnamon network applet - I cant seem to find a way to disconnect from a n/w. Only connect to another n/w. Is it a deliberate design choice? Not sure.

There are some good points like showing network speed graph inside the applet which Cinnamon n/w applet can implement. 

Update: Added new link.
Final design looks awesome. Especially, the details icon, header row switches all look neat, functional, visually appealing  and intuitive.  Brilliant work, worth copying :wink: .

http://dot.kde.org/sites/dot.kde.org/files/networkmanager.jpg

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
