### ISSUE TITLE
Change Keyboard Layouts to Input Sources

### ISSUE THREAD

**Issue by Charles-Mejia-Cruz** [linuxmint/Cinnamon#2753]
In GNOME 3.8, IBUS/Anthy can be added as a Input Source in the Region and Language Settings. I think this would be a nice addition for the keyboard applet and would make things much simpler.

**Comment by Vahan86** [comment]
Now you can install Input methods like IBUS and SCIM in Cinnnamon Settings-> Language Settings-> Input Method.

@JosephMcc, can we close this issue?
