### ISSUE TITLE
Changing the input source does not work!

### ISSUE THREAD

**Issue by anhhct** [linuxmint/Cinnamon#2754]
I add Vietnamese Telex m17n input source in settings/regional settings. But when i chose it the flag doesn't show on the applet and i can not type Vietnamese. May be the input engine was not loaded or something. Fedora 20 and cinnamon 2

![screenshot from 2013-12-19 23 41 10](https://f.cloud.github.com/assets/3386835/1784041/831c569a-68cc-11e3-9e07-baaa7353336c.png)

**Comment by Vahan86** [comment]
@JosephMcc, I have added Vietnamese keyboard layout in Cinnamon Settings->Keyboard->Layouts and Keyboard applet shows Vietnamese layout correctly.

![untitled](https://cloud.githubusercontent.com/assets/12819058/18140320/14a91352-6fc6-11e6-9885-6f43806173c3.png)

**Comment by JosephMcc** [comment]
Ok, thanks. Since the original OP never responded to the request to retest this in newer version I'll go ahead and close it.
