### ISSUE TITLE
workspace switcher applet functionality restore

### ISSUE THREAD

**Issue by ChurchX** [linuxmint/Cinnamon#2756]
If possible, reimplement in cinnamon/applets/workspace-switcher@cinnamon.org features seen in gnome's:

*) rough wireframe window representations (frame only as it was gnome (probably for performance reasons) instead of full preview thumbnail. Though better preview might be there for much higher panel & applet size for visual candy. If window on top in workspace is maximized, then display it's icon).
*) make those previews draggable right within applet between workspaces.

Optionally:
*) changing number of workspaces and their names within applet's preferences. Duplicates adding in expo but imho fits well here.

**Comment by JosephMcc** [comment]
Done.
