### ISSUE TITLE
calendar applet prefs +link to manpage?

### ISSUE THREAD

**Issue by ChurchX** [linuxmint/Cinnamon#2758]
Imho won't hurt to add in cinnamon/applets/calendar@cinnamon.org preferences scrollable page or button that will display one in new window with text from date command manpage describing formats, that will be always there locally even if current link to www.foragoodstrftime.com with format generation isn't available/changed/or no internet connectivity.
Very minor need for such addition though, can be ignored.

As alternative, for user friendliness one might add ten or so most common string combinations, also under textbox with entered string or in mouse-over tooltip why not display short explanation of what options are there currently?
For eg: "%d%b %a %R"
show: day of month ; locale's month ; locale's abbreviated weekday ; 24-h hour & minute

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html
