### ISSUE TITLE
panel settings - theme override behaviour enhancement

### ISSUE THREAD

**Issue by ChurchX** [linuxmint/Cinnamon#2760]
If in panel settings user has chosen option:
[x] Use customized panel size (otherwise it's defined by the theme)

*) option to custom override & set custom padding width & height for applets then those preset in theme. Would be nice to see easy way to override relevant settings in panel settings, to enable putting applets closer of further apart then preset in theme without it's custom editing. Imho very usable feature for those wishing to compact panel with many applets in it/low resolution.
*) When custom panel height is chosen smallest possible (20px), often theme artifacts can be seen, such as some applet elements/widgets are higher then reduced height of panel, so stick outside it's border. Most commonly this happens in light themes, including one of cinnamon's Mint-X. I wonder if related to this case theme settings/widget background images can be auto-fixed/auto-resized when user had chosen smallest possible panel height to save screen estate? Of course, fixing theme also is option, but this issue is seen in many themes (tried many downloadable light cinnamon themes) and it's hard to expect for most of them be fixed in timely fashion, so why not built in 'fix'?

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html
