### ISSUE TITLE
panel launchers applet drawers functionality & integration with menu editor & add launchers

### ISSUE THREAD

**Issue by ChurchX** [linuxmint/Cinnamon#2761]
Would be nice to see in cinnamon/applets/panel-launchers@cinnamon.org some of functionality as in gnome:
*) ability to display not just single app launchers, but also menu's submenus. In gnome it was possible to select for example 'Internet' 'Office' 'Sound & Video' menus aswell. Somewhat compromise between quickest app access via single app launcher and yet quicker and compact enough compared to main menu for accessing all of them.
In gnome i usually had Internet|Office|Multimedia menus alongside terminal and show desktop single launchers.
*) ease of adding & removing launchers could be improved over editing dconf setting by putting in preferences list of current ones for removal choice + two buttons for adding new one. One - launching main menu editor with ability to select & add menus & single launchers from it, second button - with 'Create a new launcher here' creating new and opening it's properties for edit.
Extra/new:
*) I'd also love to see added preferences option on opening such mini-menu on mouse over menu launchers, just like it's possible for main menu + auto closing it when mouse leaves it.

On side note.
Maybe worth implementing way of adding more then one instance of panel launchers? Eg. one quick launch with one launcher set at one part of panel (or one of panels, if multiple), another one with different set in another panel part (or another panel).

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html
