### ISSUE TITLE
menu applet itself hover delay

### ISSUE THREAD

**Issue by ChurchX** [linuxmint/Cinnamon#2762]
For cinnamon/applets/menu@cinnamon.org applet it seems that 'Menu hover delay' option changes only how quick submenus are opened, not - how quick menu auto-opens with 'Open the menu when I move my mouse over it' option enabled. I often manage to mistrigger in my desktop configuration (top flipped panel+window controls on left side of window title), so i wonder if there could be added second option of 'Main menu hover delay'. Separate - because i want for submenus to open immediately unlike main one. If this will seem too rarely used option, this second delay option for main menu opening delay could be added as dconf key only, or shown only when 'Open the menu..' is deselected (IIRC default).

Alternative (in some ways seems better to me) would be: if menu is mouse-over opened, temporarily increase hover delay + add way to close it with repeated mouse move to very corner. Kind of how Expo & Scale can be switched off on triggering their hot corner once more.

On side note - maybe it's worth to add behaviour to also auto-close menu, if mouse cursor leaves it's & (if opened) submenu-s area (after entering it prior that. Also if leaving it above (for top panel) or below (for normal one), for common situation of original need to click on some applet right by Menu applet). It probably should be this way only if 'Open the menu when .. mouse over' option is enabled.

**Comment by NikoKrause** [comment]
@JosephMcc 
This issue is fixed by https://github.com/linuxmint/Cinnamon/commit/feacb693f529bd7db279dfa371b5f2c3d4d8d838

**Comment by JosephMcc** [comment]
Cool, thanks for the heads up.
