### ISSUE TITLE
default menu for cinnamon should remember previous choice

### ISSUE THREAD

**Issue by jahid0903014** [linuxmint/Cinnamon#2764]
the default menu for cinnamon should remember previous choice (like in simpler menu) or may be another solution is to add log out and quit button in simpler menu.

**Comment by Vahan86** [comment]
@jahid0903014 , could you please clarify your issue? What should exactly remember the menu?

**Comment by ManIVIctorious** [comment]
@JosephMcc I think this should be closed

**Comment by ManIVIctorious** [comment]
Sorry, that tab wasn't reloaded for a few days..., just ignore the previous comment...
