### ISSUE TITLE
Icon sets can (lock up) Cinnamon when chosen in the interface.

### ISSUE THREAD

**Issue by derekdickerson** [linuxmint/Cinnamon#2767]
Some icons sets can cause Cinnamon to completely lock up when chosen in the drop down. It should have a fail safe if not compatible or damaged. 

This maybe the wrong answer but I was able to repro this issue with Pacifica icon and Moka Icon sets.

**Comment by pixunil** [comment]
Is this still in version 2.6?

**Comment by Vahan86** [comment]
@JosephMcc, can we close the issue since there is no response from OP for a long time?
