### ISSUE TITLE
Improved Cinnamon recovery from fallback

### ISSUE THREAD

**Issue by derekdickerson** [linuxmint/Cinnamon#2768]
Possible solutions would include:
1.)List of working video drivers, and display servers supported after fallback occurs.(we have tested with these driver versions this may become unstable)
2.)Last known working state (would you like to fall back to this date)
3.)Detailed error reporting on what caused the fallback with the popup(this caused the issue)
4.)Fallback recovery options (would you like to reset this configuration)
5.)Solutions to prevent fallback (driver is not supported with this version of Cinnamon)

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html
