### ISSUE TITLE
volume and brightness osd missing transparency/bars in precise/maya

### ISSUE THREAD

**Issue by hacco** [linuxmint/Cinnamon#2770]
The OSD used to have transparency and that made the volume/brightness bars visible
adding the brightness https://github.com/satya164/Evolve/commit/b467d14ebd2b53bbb908e207c78065ddd4dff646 didn't work (gtk3.4)
please help with a workaround

there are also two more issues with the missing bluetooth applet and the missing configuration of the new sound-events

**Comment by JosephMcc** [comment]
This is not longer relevant since the osd doesn't use the gtk theming anymore.
