### ISSUE TITLE
black backgrounds on settings

### ISSUE THREAD

**Issue by bhcopeland** [linuxmint/Cinnamon#2771]
http://i.imgur.com/NSmiXGU.png

http://i.imgur.com/wVaDs29.png

**Comment by abhi-84** [comment]
great hit @mtwebster........same issue still exists in ubuntu14.04 and same solution works :-)

**Comment by Logmytech** [comment]
Thanks a lot! I had this problem too until I run the fix command!

**Comment by harshhpareek** [comment]
I ran into this issue and gsettings set com.canonical.desktop.interface scrollbar-mode normal solved this for me. 
I'm new to the community. Can someone tell me where I could submit a patch to resolve this issue upstream? Apologies since this is obviously not the correct forum for this.

**Comment by JosephMcc** [comment]
The custom scrollbar implementation is being removed in Ubuntu 16.04 so this should not be an issue going forward.
