### ISSUE TITLE
Deletion of user-accounts isn't possible, system side default account-pictures not previewed

### ISSUE THREAD

**Issue by quicknick** [linuxmint/Cinnamon#2776]
Hello guys,

first some general system information: LinuxMint 13 LTS (Maya, 32-bit), Cinnamon 2.0.14 (backports activated). 

Problem Nr.1: In "Users and Groups" i can't remove user-accounts. After selection of a user-account and click on "Delete" the window "Users and Groups" is closing / crashing. The selected user-account for deletion is still existent after re-opening "Users and Groups".

Problem Nr.2: In the configuration-screens "Users and Groups" or "Account details" i can for sure select any picture; but the preview of preinstalled system side pictures isn't working. There is only a white screen - see screenshot below:

![users_and_groups](https://f.cloud.github.com/assets/6261420/1809228/997001c2-6dc1-11e3-8277-c31521e5b70f.png)

With english system language i got the same problems. For any help thanks in advance! :-)

Greetings from Germany, Nick

**Comment by Vahan86** [comment]
@JosephMcc, can we close this issue since there is no response from OP for 2 years?
