### ISSUE TITLE
Linux Mint 16 Cinnamon requires admin password twice in VirtualBox

### ISSUE THREAD

**Issue by te7** [linuxmint/Cinnamon#2777]
I have both Linux Mint Cinnamon 32 bit and 64 bit in VirtualBox 4.3.6. When I select admin level functions, like Software Manager, Update Manager, or managing Users, it asks for an admin password, then says it is incorrect, asks for it again, this time correct. I installed the XFCE desktop and the problem goes away. It could be a problem with the VirtualBox drivers.

**Comment by dalcde** [comment]
Not related to Cinnamon
