### ISSUE TITLE
[FEATURE-REGUEST] More desktop effects and side-panel mode

### ISSUE THREAD

**Issue by frantisekz** [linuxmint/Cinnamon#278]
I think, it will be good to have more/advanced desktop effects avaible at cinnamon.
I am thinking mainly about KDE Shell effects (semi-transparent windows, while moving them, avaibility to set transparency to panel - not by creating new theme) and more functionality to ,,Show Desktop,, button (http://extrawindows.cnews.cz/files/imagecache/400x300/obrazky/2008/10Oct/windows7-3.jpg for example).
And side panel mode. Yes, i am thinking about something like unity :D

Sorry for my bad English, i am native czech speaker :)

**Comment by bash99** [comment]
+1 for side panels.

**Comment by Kronykus** [comment]
+1

**Comment by mkasztelnik** [comment]
:+1: for side panels.

**Comment by odedfos** [comment]
I too hope to see the side panel feature (once technology makes it feasible)

**Comment by Deathangel908** [comment]
+1

**Comment by zenfuzz** [comment]
+1 for side panels, I've been using them in Windows since the beginning of Windows "task bars".  Much more efficient for multi-tasking, can see everything at a glance, especially with a 30 inch monitor and real estate to play with.

**Comment by RonKZ** [comment]
At the time of my post, I was using Cinnamon.  I am now using Mate 17.3 which allows the side taskbar.  Seems that adding a sidebar option to Cinnamon ought not be a big deal, but...

**Comment by mtwebster** [comment]
https://github.com/linuxmint/Cinnamon/pull/4996

**Comment by RonKZ** [comment]
thanks @mtw,  That's encouraging; seems it takes some time and some noise, but now it's in the works.

**Comment by JosephMcc** [comment]
@RonKZ Making noise only helps to a certain extent. Comments like this:

> Seems that adding a sidebar option to Cinnamon ought not be a big deal, but...

are just frustrating. I can assure you that implementing this isn't simple and easy. It shows a serious lack of respect for the people that dedicate their personal time and effort to implement things that users want. @brownsr deserves a lot of credit for the time he's spent on trying to get this done.

**Comment by JosephMcc** [comment]
This issue is making multiple requests in a single issue, some which have been done so I'm closing it.
