### ISSUE TITLE
DRI_PRIME offloading doesn't work with Cinnamon/Muffin

### ISSUE THREAD

**Issue by winternull** [linuxmint/Cinnamon#2783]
I'm using a laptop with muxless graphics (ATI/Intel hybrid) and I use the DRI_PRIME env variable (with Mesa) in order to offload rendering to the discrete card. This process requires a compositor to be running or else the image will be blank. This also occurs when a compositor uses GLX/OpenGL instead of Xrender.

This offloading doesn't work with Cinnamon -- I get a blank screen, as if a Compositor is not running. However as I am aware Cinnamon _always_ has a compositor running -- it's enabled by default -- so my assumption would be that the Cinnamon compositor uses GLX/OpenGL by default.

Is there a way to get Cinnamon to use Xrender instead of OpenGL, or am I SOL with using DRI_PRIME and Cinnamon?

**Comment by eternal-sorrow** [comment]
https://bugs.freedesktop.org/show_bug.cgi?id=69101 upstream Mesa bug

**Comment by Vahan86** [comment]
@winternull, is this still an issue for you with Cinnamon 3.2?

**Comment by leigh123linux** [comment]
This was never a cinnamon issue.
