### ISSUE TITLE
Cinnamon crashes into fallback-mode-crashloop when `service restart networking`

### ISSUE THREAD

**Issue by Redsandro** [linuxmint/Cinnamon#2784]
When I `sudo service networking restart`, Cinnamon will crash, reverting to some ugly default theme and unreadable black-on-black console text.

Sometimes it will bring the message _'Cinnamon is running in fallback mode. Do you want to restart Cinnamon?'_ message, and on choosing yes the same message appears.

From here on, `sudo restart now` won't work either because it will just start a bunch of things (in stead of stopping them (first) like a reboot normally does) and then hangs. Sometimes offering Ctrl+D for maintenance message.

I'm running fully updated Mint 16 Cinnamon 64 bit.

Not sure if #1485 is related.

**Comment by ManIVIctorious** [comment]
Is this still relevant in cinnamon 3.0
