### ISSUE TITLE
Not waking from suspend on lid close/open correctly

### ISSUE THREAD

**Issue by muff1nman** [linuxmint/Cinnamon#2787]
I can go through menu -> quit -> suspend and have the expected behavior:

laptop goes to suspend, close the lid, open the lid, screen comes on and I get prompted with the login screen

But when I just close the lid and then open the lid I get the following behavior:

The screen briefly shows the last screen as if I was logged in, then it flashes the login screen, then it suspends. 

If I press the power button after opening the lid, I get the expected behavior when resuming from suspend. 

Hardware:
Asus Zenbook UX31-A 

Software:
```
:~ $ pacman -Qq | grep cinnamon | xargs pacman -Qi | grep 'Name\|Version'
Name           : cinnamon
Version        : 2.0.14-1
Name           : cinnamon-control-center
Version        : 2.0.9-1
Name           : cinnamon-desktop
Version        : 2.0.4-1
Name           : cinnamon-screensaver
Version        : 2.0.3-3
Name           : cinnamon-session
Version        : 2.0.6-1
Name           : cinnamon-settings-daemon
Version        : 2.0.8-1
Name           : cinnamon-translations
Version        : 2.0.3-1
```

Relevant setting:

When lid is closed:  suspend.

**Comment by wangzhe3224** [comment]
The same behaviour....But I am in Debian 8....

**Comment by Vahan86** [comment]
@muff1nman, is this still an issue in Cinnamon 3.0?

**Comment by muff1nman** [comment]
I am no longer using cinnamon.
