### ISSUE TITLE
Can't use different language-settings for each user on same computer

### ISSUE THREAD

**Issue by Spartoid** [linuxmint/Cinnamon#2796]
Hi

I have changed from Ubuntu/Unity to Linuxmint/Cinnamon (Petra) 64-bit.

Me and my wife are Swedish and I would like to be able to have this regional settings (for various reasons).

My account:
Language: English
Formats: Sweden
Keyboard Layouts: Swedish

My wife's account:
Language: Swedish
Formats: Sweden
Keyboard Layouts: Swedish

But when I try to change Language (System Settings -> Regional Settings), it will change the language to the same setting for both accounts (including login screen).

I've also tried to change these settings through System Settings -> Languages within Cinnamon by moving Swedish to the top for my wife's account but this will also change the default language for both accounts when logged in (login screen will get "unselected language").

I have had this setting in Ubuntu/Unity where it worked, but I can't get it to work in Linuxmint/Cinnamon.

Please let me know if more information is required.

**Comment by Vahan86** [comment]
@Spartoid, is this still an issue to you with Cinnamon 3.0?
