### ISSUE TITLE
Better visibility of printers and printing

### ISSUE THREAD

**Issue by brownsr** [linuxmint/Cinnamon#2798]
I find the handling of printers less good than other elements of the system.  For disks, networks, WLAN, computer generally there are icons on the front page and/or installed applets.  For printers there is just the printer icon in the settings, which spins off rather clunky separate and crude windows for the queues. It is non-obvious to me to have to go to 'settings' for transactional activities like seeing a printer queue.  Installation of many printers appears to be awkward judging by comments in the forums, and from my experience e.g. having to install the hplip user interface, which gives poor error messages (e.g. not making it clear it has to run with root privileges when installing printers).  It is all rather bitty and a real weak area IMHO.  I would suggest some focus in this area to produce some really good, easy to use and consistent functionality would be well worthwhile for those users like me who just like to see things simple and consistent through the GUI interface.

Currently using Mint 16 Petra, standard edition. Printers used are old HP laserjet2300 (recognised automatically), much newer HP Laser P1005 (problematic, gives unhelpful messages on connecting.  Have got this installed in previous versions of Mint, but am now having to try to navigate the awkwardness of getting a suitable plugin installed again - two iterations through 'sudo hp-setup' seems to do it), and Pantum laser (windows only, it appears, cannot get to work at all).

**Comment by Vahan86** [comment]
@JosephMcc, can we mark this issue as a feature request?

**Comment by lestcape** [comment]
I think will be good to have a typelib for GtkPrinter (https://developer.gnome.org/gtk3/stable/GtkPrinter.html) and GtkPrintJob (https://developer.gnome.org/gtk3/stable/GtkPrintJob.html), or directly for CUPS (https://github.com/apple/cups)...

Thats for a properly implementation of a printer applet, that is in the roadmap (https://github.com/linuxmint/Roadmap).

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html
