### ISSUE TITLE
Theming regression when adding a keyboard layout

### ISSUE THREAD

**Issue by rseed42** [linuxmint/Cinnamon#2802]
After a fresh install of [Debian Wheezy 7.3 stable](http://cdimage.debian.org/debian-cd/7.3.0/amd64/iso-dvd/debian-7.3.0-amd64-DVD-1.iso) with Gnome, I have cloned and compiled the following packages automatically with dpkg-buildpackage at release tags:

* cjs: 2.0.0
* cinnamon-desktop: 2.0.4
* cinnamon-translations: 2.0.3
* cinnamon-session: 2.0.6
* cinnamon-settings-daemon: 2.0.8
* cinnamon-control-center: 2.0.9
* muffin: 2.0.5
* Cinnamon: 2.0.9
* nemo: 2.0.8
* cinnamon-screensaver: 2.0.3

Installed the [Faenza](https://launchpad.net/~tiheum/+archive/equinox/+files/faenza-icon-theme_1.3.1_all.deb) and [Faiance](https://launchpad.net/~tiheum/+archive/equinox/+files/faience-icon-theme_0.5.1_all.deb) deb-packaged icons system-wide. Copied the [Faiance theme](http://tiheum.deviantart.com/art/GTK3-Gnome-Shell-Faience-255097456) to /usr/share/themes.

After applying them, I add another input language to the keyboard (from Settings), so that the keyboard layout switching applet appears.

After logging out and back in, the theme has reverted to the default gnome theme and *gnome-terminal doesn't work any more* (no prompt displayed). A quick look in Settings shows that the Faiance theme is still on.

At first I thought I had some problems with the compilation, but after that I discovered that if I remove the second keyboard layout and relog, the Faiance theme works fine. I don't think that this bug relates to Faience (gnome shell theme), so there you have it.

**Comment by Vahan86** [comment]
@JosephMcc, can we close the issue since there is no response from OP for a long time?
