### ISSUE TITLE
Mounted folders do not show up on the Desktop

### ISSUE THREAD

**Issue by xEtherealx** [linuxmint/Cinnamon#2809]
Update: While I originally thought that my goal of getting a mount to show on the desktop was being hindered by having the icons double up, it seems that the real problem is that folders mounted (to /mnt or /media in this case) do not show up on the desktop when "Show Mounted Volumes" is selected.  The mounts I have are all cifs and mounted via an automount config.

Old:
Mint 16 Cinnamon, x86_64.  I have cifs automounts set up to mount to my desktop.  Upon login, there are two icons for each mount.  The icons differ in that one set has a network folder icon and the others do not.  Clicking on properties for the network folder icons provides a pie chart of free space while the others do not.  The non-network icon folders have sharing options; network folders do not.  

I see only one mount for each folder via `mount`.

The network folders are preferred.

**Comment by JosephMcc** [comment]
If this is still relevant it would be better off here since Nemo handles the desktop icons: https://github.com/linuxmint/nemo/issues
