### ISSUE TITLE
Ability to rate Applet / Desklet / Themes in Cinnamon settings

### ISSUE THREAD

**Issue by anandrkris** [linuxmint/Cinnamon#2811]
Spices rating mechanism can be integrated within Cinnamon Settings to facilitate users in providing feedback w/o having the need to navigate to spices website. (Much like Mint Software Manager and Community website integration).

This may perhaps increase volume of users giving feedback. Sample screenshot of extensions below, stars shown are user's ratings of the item. (Perhaps should be shown on installed tab)

![cinnamon-2 0-extensions_ratings](https://f.cloud.github.com/assets/4663298/1885897/094328b6-79da-11e3-9e16-fc28cdc108ff.png)

**Comment by NikoKrause** [comment]
A new rating system is planned as far as I know.
So this could probably be closed

@joseph @clem

**Comment by JosephMcc** [comment]
I'd rather close it once something is actually in place.

**Comment by anandrkris** [comment]
Also my request is to integrate x-let rating into Cinnamon Desktop itself instead of  a separate website...

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html
