### ISSUE TITLE
Add drag and drop support for adding applets

### ISSUE THREAD

**Issue by geoffm** [linuxmint/Cinnamon#2812]
Right now the only way to add an applet is to single click it and to go click "Add to panel".
User-friendlyness could be improved by making the applet install when double-clicking it, or by drag-dropping the applet to wherever the user wants it to be in the panel, like Gnome2 used to do.

**Comment by NikoKrause** [comment]
Is this still an issue with Cinnamon 3.0?

**Comment by lestcape** [comment]
@NikoKrause this is a feature request...

**Comment by NikoKrause** [comment]
Ah sorry. I mistaken applets with applications.

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html
