### ISSUE TITLE
Category for Applets / Desklets

### ISSUE THREAD

**Issue by anandrkris** [linuxmint/Cinnamon#2813]
As the Cinnamon ecosystem grows, I feel, there is a need to assign a Category to each applet / desklets to ensure that in future users can filter items based on category.

Example:
1. Utilities - Calculator, World Clock, Calendar, Stop watch, ScreenShot+Desktop Record, Record Desktop, Timer With Notifications, Brightness
2. Multimedia - Sound Box, 
3. System - CPU Monitor, CPU temperature, Bumblebee And NVidia Display (BAND), Network usage, GPU Temperature (ATI and NVIDIA)
4. Online Services / Social - News feeds, Sports Update, Weather, Gmail, Shortenize URL
5. Productivity -  Sticky Notes, Pomodoro, Hamster Time Tracker, GPaste 
6. Application Launchers - Win 7 Menu, Graphics Center, Office Center
7. Fun and Games - xkcd comic viewer, Fortune Quote of the day
8. Accessibility -  Caps / Num lock, 
9. Development - Github explore, development,XAMPP Panel Menu, Looking Glass Restart, ShellTools
10. Others - Open File Manager as Root

Each item could have one category or can have multiple tags - is something development team can decide. :smile:

**Comment by anandrkris** [comment]
http://standards.freedesktop.org/menu-spec/latest/apa.html > Just came across this link.

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html
