### ISSUE TITLE
Add "backup configuration", "restore to ..", "'restore to last known good configuration" along "restore to default"

### ISSUE THREAD

**Issue by ChurchX** [linuxmint/cinnamon#2818]
In context of #2733 issue about 'restore to default' being too destructive i remembered that in Windows there is another way - "restore to last known good configuration".
Some possible ways to implement:
Add "backup configuration" button that makes somewhere small .tar.gz archive of settings with date & time in file name + "restore to .." file dialog to select which archive to restore + as users usually customize in first run/day, then just keep using DE, maybe during first day each hour make new backup, during first week each day, during first month - each week, during first year - each month and then just once per year.
Hmm, or maybe something to do auto backup of settings, when those are changed + cinnamon keeps running without restart for at least an hour?
It sounds too much rarely used buttons for that UI dialog window, so maybe leave just 'restore to default' and group commands 'backup'|'restore to ..'|'restore to last know good configuration' in small drop down menu under button of 'configuration', '...', 'cfg backup' or alike name.

**Comment by icarter09** [comment]
The Timeshift application should be able to implement this feature request. If it does not, please create a new feature request ticket to document what Timeshift is missing that you would like to see implemented. Thanks.
