### ISSUE TITLE
cinnamon --replace uses over 30% RAM and periodically all CPU

### ISSUE THREAD

**Issue by BigBrotherLovesYou** [linuxmint/Cinnamon#2819]
cinnamon --replace periodically spikes its CPU usage to 100% and uses over 30% of my RAM (1,2 GB of 4 GB). even if not using a 100% CPU, if for example a movie is played every few seconds there is a minimal but noticeable stutter. if i do a cinnamon --replace, it starts out with minimal RAM/CPU usage, then /usr/lib/accountsservice/accounts-daemon will use all CPU for 30 seconds to one minute while cinnamon's RAM usage grows. after accounts-daemon calms down cinnamon will have the aforementioned RAM/CPU behaviour.
running petra 64 bit, fully updated
if any logs/tests are required i will happily provide them

**Comment by ManIVIctorious** [comment]
Still relevant in cinnamon 3.0?

**Comment by JosephMcc** [comment]
Closing due to lack of response.
