### ISSUE TITLE
Search "submenus" when searching the menu

### ISSUE THREAD

**Issue by xEtherealx** [linuxmint/Cinnamon#2820]
When I search the menu, e.g. for "mouse" I expect to find the mouse settings in the search results.  This doesn't currently happen.  A useful feature might be a horizontal separator below the found menu items, for sub-menu items that are found by the search algorithm.  as @lestcape pointed out, this should be generalized to all menu items with secondary submenus.

**Comment by ManIVIctorious** [comment]
@JosephMcc As far as I understand the original issue is resolved
the additional discussion about better search results can also be found in the issues #1320 #1220 and #4053
