### ISSUE TITLE
Blurry workspace-close buttons.

### ISSUE THREAD

**Issue by ghost** [linuxmint/Cinnamon#2822]
This issue has persisted since cinna 1.6.
Basically, as the number of workspaces changes the workspace close button will go from perfectly "crisp" to very blurry.

Most theme makers never payed attention to this and so the problem is very visible on the majority of themes(including the default themes!).Only in a bunch of my own themes have I played around with various padding values, but to no avail.
I managed to set it up so that the button starts blurring when you get to a lot of workspaces(which most people don´t).
I have really played with a bunch of settings, but couldn´t find the problem in the cinnamon.css.

Crisp:
![workspace 1_004](https://f.cloud.github.com/assets/5655339/1915049/f0ebf218-7d60-11e3-95a3-1be92ee01980.png)

Blurry:
![workspace 1_003](https://f.cloud.github.com/assets/5655339/1915052/fcf15b98-7d60-11e3-8ab2-122dc52717bd.png)

**Comment by Vahan86** [comment]
@ghost, is this still an issue for you in Cinnamon 3.0.x?

**Comment by Vahan86** [comment]
@JosephMcc, can we close this issue?
