### ISSUE TITLE
Window List Applet - Tasks on right clicking the launcher

### ISSUE THREAD

**Issue by anandrkris** [linuxmint/Cinnamon#2826]
Currently, when I right click any of the launchers in the applet, it shows New Window, Move to right workspace, Visible on all Workspaces, which is really good. 

In some of the applications, there are other tasks possible. For instance, in Firefox, other tasks such as Open New tab, Open Incognito Windows can also be done by the user (option available in Windows). 

Not sure if am asking for too much / if technically feasible for an applet (api support, etc) but thought will suggest after seeing the feature in Windows. Application also should communicate the available options for itself, I believe. maybe you can discuss with Cinnamon team as well.

I have put together some screen shots (googled) for illustration.
As is shown below, one can do the following: Tasks, Pinned, Open Recent documents, etc.

![windows_super_bar_illustration](https://f.cloud.github.com/assets/4663298/1920040/66ec749a-7de0-11e3-8f2a-2b41d3b20744.png)

**Comment by JosephMcc** [comment]
This feature is now available using the panel launcher applet.

**Comment by geoffm** [comment]
Actually there are officiel additionnal application actions in the freedesktop.org specifications, they just haven't been implemented yet by most DE's.
https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s10.html
