### ISSUE TITLE
Add the possibility to assign a desktop for each program.

### ISSUE THREAD

**Issue by roipoussiere** [linuxmint/Cinnamon#2828]
I always move my programs on the same desktops.
For example : Misc->D1 ; Firefox->D2 ; command line->D3.
So I spend some time to configure my environment each time I open a session.
It would be very useful if users could assign a desktop for each of their favorite programs. In this way, when they launch a program, it will be always on the good desktop.

**Comment by Vahan86** [comment]
@JosephMcc, can we mark this issue as a feature request?

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html
