### ISSUE TITLE
 Workspace profiles

### ISSUE THREAD

**Issue by caracana** [linuxmint/Cinnamon#2829]
As most of us use their PC for various purpose, my idea is to create workspaces profiles. When we activate the profile development, for example, it create 3 workspaces, the first called IDE, with codeblocks opened, the second with the browser at the documentation page, and the third called other with a terminal, and a web browser to search on forums (it is just an exemple).

The configuration of those profiles would be a file like :

```
"profile development
{
    workspaces(3,"IDE", "doc", "other")
    workspace(1)
    {
        codeblocks
    }
    workspace(2)
    {
        firefox http://doc.qt.digia.com/
    }
    ...
    }

    profile CAD
    {
        ...
    }

    profile web (default) //this one is activated by default
    {
        ...
    }"
```

And, to switch the proflie, there would be a shortcut, something like alt-tab, or a button in a panel applet

**Comment by Vahan86** [comment]
@JosephMcc, can we mark the issue as a feature request?

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html
