### ISSUE TITLE
Random Crashes : Segfault by libgio-2.0.so

### ISSUE THREAD

**Issue by koldbyte** [linuxmint/Cinnamon#2835]
I am experiencing random crashes.
I am using linux mint 16 Cinnamon 64 bit with all latest updates.
These are the related log entries i found ::

Jan 20 03:24:21 DarkPC kernel: [30810.090825] cinnamon[2096]: segfault at 0 ip 00007f0e71ae9ae4 sp 00007fffa0e76f50 error 4 in libgio-2.0.so.0.3800.1[7f0e71a98000+15c000]
Jan 20 03:24:21 DarkPC cinnamon-session[1580]: WARNING: Child process 2096 was already dead.
Jan 20 03:24:21 DarkPC cinnamon-session[1580]: WARNING: Application 'cinnamon.desktop' killed by signal 11
Jan 20 03:30:29 DarkPC kernel: [31178.708904] cinnamon[19980]: segfault at 0 ip 00007f75003f5ae4 sp 00007fffc4c88ff0 error 4 in libgio-2.0.so.0.3800.1[7f75003a4000+15c000]
Jan 20 03:30:29 DarkPC cinnamon-session[1580]: WARNING: Application 'cinnamon.desktop' killed by signal 11
J
....
....
Jan 20 05:25:46 DarkPC kernel: [38092.039089] cinnamon[20124]: segfault at 0 ip 00007fc54ac54ae4 sp 00007fff7be56d10 error 4 in libgio-2.0.so.0.3800.1[7fc54ac03000+15c000]
Jan 20 05:25:46 DarkPC cinnamon-session[1580]: WARNING: Application 'cinnamon.desktop' killed by signal 11
....
....
Jan 21 02:07:52 DarkPC kernel: [99731.826970] cinnamon[22465]: segfault at 0 ip 00007f5101602ae4 sp 00007fff4ff185b0 error 4 in libgio-2.0.so.0.3800.1[7f51015b1000+15c000]
Jan 21 02:07:52 DarkPC cinnamon-session[1580]: WARNING: Application 'cinnamon.desktop' killed by signal 11
....
....
Jan 21 02:19:10 DarkPC kernel: [100409.405012] cinnamon[13840]: segfault at 0 ip 00007f7278105ae4 sp 00007fff7017b330 error 4 in libgio-2.0.so.0.3800.1[7f72780b4000+15c000]
Jan 21 02:19:10 DarkPC cinnamon-session[1580]: WARNING: Application 'cinnamon.desktop' killed by signal 11
....
....
Jan 21 16:13:35 DarkPC kernel: [121667.432265] cinnamon[13995]: segfault at 0 ip 00007fbef75f0ae4 sp 00007fffd4e5b700 error 4 in libgio-2.0.so.0.3800.1[7fbef759f000+15c000]
Jan 21 16:13:35 DarkPC cinnamon-session[1580]: WARNING: Application 'cinnamon.desktop' killed by signal 11

This is my first bug posting. 
Pls tell me if you need more logs or anything on it.

Thanks

**Comment by Vahan86** [comment]
@koldbyte, @MichaelJCole , @dansie  does this issue still occur in Cinnamon 3.0.x?

**Comment by MichaelJCole** [comment]
@Vahan86 I upgraded to 3.0.7 and haven't experienced this in some time.  Thanks for asking :-)

**Comment by pdcurtis** [comment]
The current versions of NUMA do not show the problems as the update loop has been split into two equal parts and some buffering was added to remove the race condition. The only way to check for the original problem is for me to go back to an earlier version of NUMA or see if I can find my test version. At present I only have a mobile phone and it will take a while even after I get back home - it could be up to a month before I can give a reasonable definitive report for Mint 18 and Cinnamon 3.0 .

**Comment by pdcurtis** [comment]
I have run a copy of the version of NUMA (v18_2.3.7) that showed the problems modified to run at 10x the usual update rate for 48 hours without any segfaults. Testing of this form can never prove bugs do not exist but it is promising this has been run for such a long period when the segfaults would occur within a few hours at normal update rates under Mint 16 with Cinnamon 2.0.x on the same machine. This is highly indicative that the issue has been solved in Mint 18 with Cinnamon 3.0.7 and I agree the issue can be closed.

**Comment by JosephMcc** [comment]
Thanks for the feedback.
