### ISSUE TITLE
Applet and Desklet settings visual improvement...

### ISSUE THREAD

**Issue by lestcape** [linuxmint/Cinnamon#2837]
Cinnamon Settings for applets and desklets, are constructed using the settings-shema.json... The real true it's the currently thing that we can do with the applets and desklets settings not are to much, so...

I thinking in a way to add panels and allow layouts in the applets and desklets setting.

The best idea that i have it's add a new attribute parent in all settings object(can not be present). A parent always need to be a panel or not appear(in this case the default parent are the settings main frame), and also panels can to have a parent attribute  or not appear to.

An example of settings-shema.json can be this:

"horizontal-panel" : {
"type" : "horizontalpanel"
},
"first-panel" : {
"type" : "verticalpanel",
"parent" : "horizontal-panel"
},
"second-panel" : {
"type" : "verticalpanel",
"parent" : "horizontal-panel"
},
"menu-icon" : {
"type" : "iconfilechooser",
"parent" : "first-panel",
"default" : "/usr/share/cinnamon/theme/menu.png",
"description": "Icon",
"tooltip": "Select an icon to show in the panel."
},
"menu-label" : {
"type" : "entry",
"parent" : "second-panel",
"default" : "Menu",
"description" : "Text",
"tooltip" : "Enter custom text to show in the panel."
},

"show-recent" : {
"type" : "checkbox",
"default" : true,
"description": "Show recent files",
"tooltip": "Choose whether or not to show a recent file list in the menu."
}

This is the result of this example:
![setting](https://f.cloud.github.com/assets/1389572/1970941/89a3fbfa-8319-11e3-9034-6bdaf7414c1b.png)

The component "show-recent" don't have parent. For this reason this component was added in the current way, below the last component added above in the main frame. The same occurs with horizontal-panel.

The rest of components have a parent so he was added inside of the parent panel.

Those mechanims are compatible with the current especification of the setting, then we can be done without losing any other thing, or need to change all applet or desklet settings to be compatible with this new feature.

Finally can be added a new vertical and/or horizontal attribute inside panel, to allow also align the components...

The structure of the new way generate an inverted tree(the information are about the parent and not about the child). This type of tree are know how games tree.

Luckily the tree can be simulate with a dynamic array of components for the algorithm to generate a setting, added initially the components that not have parent and then when the current component are added, we can removed this component from the dynamic array and then add all components that have the current component as a parent.

Will be good have more opinions, because this allow me to not do things that can be done better or causing several problems....

Thanks...

**Comment by pixunil** [comment]
personally, I think defining layout containers as separate widgets with own ids bloats the json file unnecessary. My idea is adding a "reserved" id `__layout__` which is an array, maybe like following:

```json
"__layout__": [
    ["menu-icon", "menu-label"],
    "show-recent"
],
"menu-icon" : {
    "type" : "iconfilechooser",
    "default" : "/usr/share/cinnamon/theme/menu.png",
    "description": "Icon",
    "tooltip": "Select an icon to show in the panel."
},
"menu-label" : {
    "type" : "entry",
    "default" : "Menu",
    "description" : "Text",
    "tooltip" : "Enter custom text to show in the panel."
},
"show-recent" : {
    "type" : "checkbox",
    "default" : true,
    "description": "Show recent files",
    "tooltip": "Choose whether or not to show a recent file list in the menu."
}
```

An array inside `__layout__` is a HBox.
All widgets are referenced by their id.
To extend this idea, we could drop the `header` and `separator` type, with just putting the strings `__header__ <text>` or `__separator__` in the `__layout__` section.
The idea behind this is that widgets that have an id should have contact with the applet and those which not don't have an id. (as setting or button)

@lestcape do you think this is also a nice idea?

**Comment by lestcape** [comment]
@pixunil  I like the idea to create an array, but is missing on your comments add a panel inside another, or at less i can not see how you propose do this?

**Comment by pixunil** [comment]
I thought we can use a simple array inside `__layout__` as a shorthand for a HBox, and for other containers like a grid or a VBox an object notation:
```json
[
    "fubar",
    "__separator__",
    {
        "type": "grid",
        "width": 4,
        "height": 4,
        "children": [
            ["foo", "bar"],
            "__header__ Baz"
        ]
    },
    "qux"
]
```

`type` could be also `vbox` or `hbox` (useful for extra options like margin, indent etc. wich could be passed inside this object) 
Where the array `children` contains other notations like in `__layout__`.
(I think you mean with panels Boxes in Gtk)

**Comment by lestcape** [comment]
Yes, thats ok, i like your idea, but maybe could be improved more... My idea was not refine, and your idea maybe could better ... You are good on this.

**Comment by pixunil** [comment]
As a shorthand for multiple widgets I think `<key> ... <key>` is a nice idea.
Example with [my applet](https://github.com/pixunil/cinnamon-applet-system-monitor/blob/master/settings-schema.json) would be:
```json
"__layout__": [
    "__header__ General",
    "show-icon ... order",
    "__separator__",
    "__header__ Graphs",
    "graph-type ... graph-interval"
]
```

**Comment by lestcape** [comment]
We need to take care with the translation option. So yes, using key is better than use the value property, i suppose, but could be a little more complex to understand by the devs... What occurs to this, is that we don't do any thing here. This change need to be approved by Cinnamon devs, at less like an interesting thing to be tested, or otherwise we are lost the time... This matter is interesting to me and you, and i could do that for my own purpose but this is not enough for all, A thing like that, need to be general... Or in some cases will be interesting a way to add local plugins(on the home folder) to the cinnamon settings... On this way we can add or improve the cinnamon settings with more options like this, to be apply directly to owners extensions on cjs. Cinnamon Settings is not intended to be improved by a development of a cinnamon extensions, but on my opinion need to be. Is where we handled ours extension settings, and Cinnamon Settings could not be enough to use all options that we can need. There are a way to call an external settings, but like i say: "external", so this is not what i talk.

**Comment by lestcape** [comment]
I'm working on my own settings, that now is merged with cinnamon installer https://github.com/lestcape/Cinnamon-Installer, I have several bugs and incomplete things yet, but now appear to be functional, some day could be usable. When i finished the application core, i will implement all my ideas. Could be use by the cinnamon devs to test new features. We can not see some times the utility of some things before this thing is working.

**Comment by pixunil** [comment]
I talked a bit with @mtwebster about this a bit and he thinks that it needs in every case to stay simple and to have backwards compatibility.
Some work is already committed to show that this is not a real big change in python https://github.com/pixunil/Cinnamon/tree/xlet-settings-layout

**Comment by lestcape** [comment]
Ok, this is for me a totally different thing... I like how you separate the behavior of the translation on one place, is complex to understand in the old way. I think that VBox and HBox need to have another less cryptic name. The gtknotebook is a very important type of widgets that could be integrated here. The pages could refers to a list of boxes id and the value could be the current selected page, like comboboxes.

**Comment by lestcape** [comment]
I say that combo, because the page have a name, that will need to be translated... This type of structure is try on settings-schema.json as an "options" in combo, so nothing new. keys could be the associate box and value the display name to the page.

**Comment by pixunil** [comment]
Yes, I thought about this also, and I think because a Notebook widget should only appear once, we can define the `__layout__` as object instead of array:

```json
"__layout__": {
    "General": [
        "x ... y"
    ],
    "foo": [
        "bar"
    ]
}
```

**Comment by lestcape** [comment]
Why we can not have more than once if we want?

I say on that way:
```
"Notebook_id": {
   "pages": {
        "id_box_page1": "page_name1",
        "id_box_page2": "page_name2"
    },
    "default": "id_box_page1",
    "type": "Notebook",
    "value": "id_box_page2", //the selected page
   },
```
   page_name1, ... page_nameN need to be translate.

**Comment by lestcape** [comment]
Your idea, are not taking on account translate the page name, and why we need another object inside this if we can have a reference to an existing one? id_box_page1 as example.

**Comment by lestcape** [comment]
This was implemented by @collinss

**Comment by JosephMcc** [comment]
@lestcape Thanks for taking the time to go through and clean up issues you opened. We have been trying to get these cleaned up a bit and any help is appreciated.

**Comment by lestcape** [comment]
Yes, i know. Also if i found some issues that can be closed i will say your name, to help a little.
