### ISSUE TITLE
Cinnamon-Settings Region Keyboards: possible to integrate ibus methods?

### ISSUE THREAD

**Issue by rik-shaw** [linuxmint/Cinnamon#2845]
"cinnamon-settings region" or "cinnamon-control-center region" "Keyboard Layouts" tab doesn't show ibus input methods as options (and thus "Keyboard Applet" doesn't show them either).  I think this mainly boils down to using different gnome dconf values than Gnome now uses (read on).

In Cinnamon (tested with 2014-01-23 nightly in Ubuntu 14.04), enabling ibus as the system input method (in "gnome-language-selector") adds a separate ibus icon to the Cinnamon panel (adding input methods there just use the standard "ibus-settings" module).

This isn't terrible in itself, except I have just tested with Ubuntu 14.04 Gnome-Shell and there are some improvements there in "gnome-control-center region":
1.  The "Input Sources" tab (they don't have it called "Keyboard Layouts") allows choosing ibus methods also.  Adding a method writes to this dconf value like this:

/org/gnome/desktop/input-sources/sources
[('xkb', 'us'), ('ibus', '/usr/share/kmfl/SILEthiopic-1.3.kmn'), ('ibus', '/usr/share/kmfl/GE.kmn'), ('xkb', 'ara')]

Under Cinnamon, when I use the "cinnamon-settings region" Keyboard Layouts, it writes here:

/org/gnome/libgnomekbd/keyboard/layouts
['us', 'ara']

So, in that format it doesn't seem possible to add ibus methods.  Is it possible to connect to the other dconf value Gnome-Shell has updated to?

Right now in Cinnamon using the "ibus icon" in the panel ("ibus-setings") to add an additional method it writes here:

/desktop/ibus/general/engines-order
['xkb:us::eng', 'm17n:ar:kbd', '/usr/share/kmfl/GE.kmn', '/usr/share/kmfl/SILEthiopic-1.3.kmn']

Gnome-Shell won't show this ibus icon in the panel since their keyboard icon accounts for kbd and ibus methods, so they don't look at that dconf value (I think).

Note that it is possible in this "engines-order" location to add "xkb" AND "ibus" methods.  So, one possibility is for a user to ONLY use this ibus icon and NOT use the "Keyboard Applet" in the panel.  But "cinnamon-settings" integration is nice.

So, obviously it is quite confusing now to have 2 different places to deal with keyboards ("Keyboard Applet / cinnamon-settings region" OR ibus).  I am sure that Cinnamon 2.2 can solve this confusion if they update cinnamon dconf values to do  whatever gnome-control-center in 14.04 is doing to reference the "input-sources" dconf value instead of the "libgnomekbd" dconf value.

**Comment by Vahan86** [comment]
@rik-shaw, is this still an issue for you in Cinnamon 3?

**Comment by SolarLiner** [comment]
Another user coming from Unity in Ubuntu 16.10, I've installed Cinamon 3.0 and the Keyboard -> Layouts settings page do not change the iBus settings - I have to right click in the ibus tray icon to open its preferences, and be able to change input methods.

This wouldn't be so much of an issue, but I want to add Vietnamese Unikey input, provided by ibus-unikey, but adding Vietnamese input does not add Unikey but rather a layout that none of my vietnamese friends have ever seen. I can still add (and activate) Unikey through iBus preferences usingthe right-click tray meny, but for a new user it can be confusing.

**Comment by rik-shaw** [comment]
To followup for anyone that finds this thread later, the Cinnamon team took the "hands off approach" with regard to ibus or other input methods being integrated into the Cinnamon keyboard settings.  Actually in the end I think this is a *good* choice, to let the input method system be independent as the developers intend.  In the case of users of ibus that are annoyed that there would be 2 keyboard icons in the taskbar (if you have multiple xkb keyboards and also ibus keyboards) the answer is that newer ibus implementations integrate xkb keyboards into the ibus keyboard manager.  So you can have a single keyboard set in Cinnamon (thus the cinnamon keyboard icon won't be in the taskbar), and add multiple xkb and ibus keyboards through ibus.  So effectively only ibus is needed to handle all the keyboards.

Additionally, we hack a bit on cinnamon settings to add the ibus-preferences as a module there so users can find it easily, and we also make ibus the system-wide keyboard input method.

**Comment by craigs100** [comment]
LM 21.0. Installing Zoom also installs ibus as a dependency (that I understand it doesn't actually need!). That renders my keyboard switching useless.  I really enjoy using the built in Cinnamon keyboard layout switcher and do not want ibus there at all, but do need Zoom.  Is there any way to stop ibus interfering? 

Thanks.
