### ISSUE TITLE
Readability of desktop icons title text independent of selected wallpaper

### ISSUE THREAD

**Issue by ChurchX** [linuxmint/Cinnamon#2853]
I hate fact that oh so often i have to switch to different theme from prefered one just because of changed wallpaper, as simply black text on very dark wallpaper is not too readable. Problem is even worse if wallpaper is dark on one side and of light/bright colors on another, as readability is there only on half of desktop with most themes.
How about adding optional option of enforcing text background independent of whatever is set (or not) in theme? No clue, what should be best. Auto color depending on text color, semi transparent depending on wallpaper color (can it be made dependent from wallpaper local part colors where text is?), user selected color, something else or all these options as possible values for text background? Maybe even text itself color depending on local wallpaper part color? Or at very least fix this in default stock themes? Whichever is chosen at end, but readable text no matter what theme, no matter what wallpaper, imho is must have feature.

**Comment by JosephMcc** [comment]
This is a nemo issue. Some things have been changed regarding this. If you still have an issue, raise one there.
