### ISSUE TITLE
desktop icons not visible in shifted dual monitor configuration

### ISSUE THREAD

**Issue by VolMi** [linuxmint/Cinnamon#2856]
Look at this screnshot of my dual monitor setup:
![bildschirmfoto](https://f.cloud.github.com/assets/1189207/2035425/cb90fefc-8939-11e3-8f54-910222c19252.png)
I shifted the screen positions this way, because it resembles pretty accurately the actual physical positions of my screens. The small, lower one is my laptop screen.

The marked (invisible) area is where my usual desktop icons (probably) are. :-)
They are visible perfectly fine for any "sane" way of dual monitor setup, but I actually like it this way.

Could you somehow make sure that desktop icons are actually visible on the main screen?

**Comment by mtwebster** [comment]
This is actually a problem with nemo.  I believe right now it currently expects monitors to be fairly horizontal, so it can make a rectangle for its desktop layout.

Initial thoughts on a fix.. possibly constraining icons to the primary monitor only (as an option in these edge cases... more ideas may come.

**Comment by dalcde** [comment]
This is also happens to desklets. #3276 seems to be the same issue but with more details and discussion
