### ISSUE TITLE
Cinnamon acts like the computer is restarted after each suspend, no apps are running

### ISSUE THREAD

**Issue by cognacc** [linuxmint/Cinnamon#2861]
The workflow is lost each time you close the lid on your laptop. All applications are "gone".
i did a 

ps aux | grep someapp

I know should be running, right after a wakeup from suspend.
Please advise on how i can improve on the information, to solve this issue, i do not know how to debug this.

**Comment by Vahan86** [comment]
@JosephMcc, I had no this issue after suspension of the computer starting from Cinnamon 2.6

**Comment by JosephMcc** [comment]
Closing due to lack of response.
