### ISSUE TITLE
Always 12 hour clock in cinnamon lockscreen

### ISSUE THREAD

**Issue by cecar** [linuxmint/Cinnamon#2867]
The clock in Cinnamon lockscreen only shows 12 hour format although the systemclock is set to 24 hour format. There is no obvious way to change the time format on the lockscreen.

Cinnamon version: 2.0.14

**Comment by bartszu** [comment]
Same story in Mate 1.8.1 tho ;(

**Comment by RavetcoFX** [comment]
@bartszu I would recommend filling an issue in the mate-screensaver page https://github.com/mate-desktop/mate-screensaver as Cinnamon is a separate project
