### ISSUE TITLE
Skype tray icon disappears when started on login

### ISSUE THREAD

**Issue by ghost** [linuxmint/Cinnamon#287]
Skype tray icon not visible when started on login though when started manually it appears fine.  On login I hear the start up sound and i see it running in system monitor.

**Comment by YannickNascimento** [comment]
0
down vote
accepted
	
"It was found that "System tray" applet was disabled in my system.
Fixed in this way:

    enter app menu
    type "Applets" and press "Enter" button
    on "Installed Applets" tab search for "System tray" applet
    select it and press "Add to panel" button
    some running applications might need to be restarted in order to appear in the tray"
by https://unix.stackexchange.com/users/37713/gumkins
