### ISSUE TITLE
About Configuring Notification Applet.

### ISSUE THREAD

**Issue by highwindmx** [linuxmint/Cinnamon#2874]
1. easy way(GUI) to undo "Don't show this message again" notification;
2. Use opposite order to show notifications.(newest on the top)

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html
