### ISSUE TITLE
Applet - Webcam On / Off Indicator 

### ISSUE THREAD

**Issue by anandrkris** [linuxmint/Cinnamon#2875]
I will be glad if someone can build an applet which indicates whether webcam is on or not. My webcam is USB powered and if an application is accessing it stealthily I would like to know that it is being used. This will also help to know if it is activated or not. Eg; In Skype w/o getting into its settings.
 Insprired by chrome who are doing it in browser tabs to track sites that access webcam.
http://chrome.blogspot.in/2014/01/everyone-can-now-track-down-noisy-tabs.html

**Comment by JosephMcc** [comment]
A better place to request this would be here: https://github.com/linuxmint/cinnamon-spices-applets
