### ISSUE TITLE
Theme nodes for desklet not reload correctly.

### ISSUE THREAD

**Issue by lestcape** [linuxmint/Cinnamon#2880]
When you change the Cinnamon theme, the desklets lost the default style class... Need to restart Cinnamon to load correctly... Applets appear to load correctly. Test for example with soundbox of @collinss ...

**Comment by Vahan86** [comment]
@lestcape, is this still an issue in Cinnamon 3?

**Comment by lestcape** [comment]
@Vahan86 yes, it's still an issue :(
