### ISSUE TITLE
Network Manager — wifi network priority handling

### ISSUE THREAD

**Issue by lzbk** [linuxmint/Cinnamon#2881]
Hi, just a feature request, which …
With the multiplication of nationwide hotspot services provided by ISPs, I often have to tell my computer to prefer my own home network over the "free hotspot" provided by my neighbours. And I have to admit that I find that profoundly annoying (and don't start me about that feature in my cellphone…).

I don't know how this is handled, maybe it would be possible to cope with those hotspots with a wifi SSID ordered list and some well chosen rules to constitute it (it could really be sufficient, but I'm wondering whether it would not actually be a serialization of the strategy I suggest below), but maybe a more precise way to handle these (without resorting to geolocalization, which most computers don't have before they are connected to a network anyway…) would be to **handle network conflicts with a matrix**…

A network would be added to the matrix when the user first successfully connects to it. Each time the user manually chooses a network, it gets a +1 in its conflict with each network that is both present in the matrix and accessible from that spot (the not chosen network getting -1) → maybe there could be some weighing artifacts to handle the fact that a wifi network with authentication is most likely to provide good quality connection than an open one (as the former will probably often be a home connection and the latter a hotspot service).
This would provide two by two comparisons that, I think, will take into account that if a hotspot service is my favourite network when I'm roaming, I don't ever wanna connect to it at home.
This is not perfect: if ISP A hotspot is often your go to service (overall better connection), in some context, let's call it the "terrace of the foo bar" ;-), you prefer ISP B hotspot service, but you don't go there often enough to overcome the comparisons with ISP A. In this case, whenever you grab a drink at the terrace of the foo bar, you will systematically have to manually change the wifi network chosen. On the other hand, that provides statistics as to what is often the best hotspot service for you, for when you move a lot. Anyway, I don't see how to handle that without storing all the networks visible to identify the spot (which is a lot of data + a data that might not last long — people changing their ISP).

Well anyway, I'm not sure I'm very clear, but I'm sure I'm not the only one who wishes his computer would choose more wisely its preferred wifi network. This might not be a priority right now, but even though I haven't tested it (maybe I should do that, I'm still wondering whether a better handled list would not work just as well as that solution) I think this strategy could work better than the current one (whatever it is) and is not too complicated to implement.

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html
