### ISSUE TITLE
desktop show of icons VERY inconsistent

### ISSUE THREAD

**Issue by rholme** [linuxmint/Cinnamon#2887]
I installed Fedora 20, then Cinnamon on top of Gnome (bug with straight install and multiple logins) on 3 systems: 2 64bit and 1 32 bit. I was very surprised at the desktop differences in showing icons. All originally showed the home+computer+trash icons, but 3 out of 6 users additionally showed icons for all directories in home (reminds me of the clutter from MS screens). To fix the three, I had to run the following command
    gsettings org.nemo.desktop show-desktop-icons false
Then all icons go away - too bad as I did like the three controllable ones that were there.

For the record - the 32 bit version install was right for both me (admin) and my other user (non admin); the 64 bit machine with no graphics accelerator was right for me but not so good for the other user; and the 64 bit with a graphics accelerator was wrong for both of us.
The machines were installed the same way, but the 64 bit machines have more software installed by yum. All had yum install cinnamon.

I am fine with NO icons showing as that is the same as it was in prior Fedora 18, but it is a shame not to be able to turn off the showing of directory icons without turning off everything.

**Comment by JosephMcc** [comment]
This issue should probably be reported to nemo, not here.
