### ISSUE TITLE
(Feature Request) Option to Auto-Expose All Windows in Workspace Overview

### ISSUE THREAD

**Issue by ramraphael** [linuxmint/cinnamon#2889]
Cinnamon should have the option to automatically Expose all windows within each Workspace during Workspace Overview.

Benefits:

1.) A true 'Workspace Overview' that also shows opened applications on all Workspaces, and can even replace Scale altogether if the user so chooses. 

2.) Windows can be dragged between Workspaces faster. Currently, there is a noticeable delay, as individual Workspaces have to be "exposed" on mouseover.

Just a simple option that greatly helped my workflow during my brief flirtation with KWin. =)

**Comment by icarter09** [comment]
@collinss can this ticket be closed?

**Comment by collinss** [comment]
Yeah, I think so
