### ISSUE TITLE
CPU overhead

### ISSUE THREAD

**Issue by TheChuckster** [linuxmint/Cinnamon#2890]
Hi all, a sample PowerTOP CPU usage profiling report shows the following:

Power Consumption Summary

376.6 wakeups/second, 11.5 GPU ops/second, 0.0 VFS ops/sec, 54.0 GFX wakes/sec and 5.2% CPU use
Usage   Events/s    Category    Description
1.5%    74.7    Process     cinnamon --replace
0.8%    64.4    Process     /opt/google/chrome/chrome --type=renderer --enable-webgl-draft-extensions --lang=en-US --force-fieldtrials=AutocompleteDynamicT
0.3%    56.5    Process     /opt/google/chrome/chrome --no-startup-window
0.4%    42.6    Process     /usr/bin/python2 -O /usr/share/wicd/daemon/wicd-daemon.py --no-daemon
0.2%    39.1    Process     /usr/bin/python2 -O /usr/share/wicd/daemon/monitor.py
0.1%    27.1    Process     [irq/47-iwlwifi]
0.0%    17.5    Process     [rcu_preempt]
0.1%    7.5     Process     /usr/bin/python2 -O /usr/share/wicd/gtk/wicd-client.py --tray
0.1%    6.8     Timer   hrtimer_wakeup
0.0%    5.9     Timer   tick_sched_timer
0.0%    6.0     kWork   ieee80211_iface_work

1.5% at 74.7 wake-ups per second. Meanwhile, the UI remains almost completely static the entire time. Why is cinnamon wasting so many cycles doing nothing at all?

**Comment by Vahan86** [comment]
@TheChuckster, is this still an issue for you in Cinnamon 3.0?

**Comment by Vahan86** [comment]
@JosephMcc, can we close this issue?
