### ISSUE TITLE
Locale handling now is Mint specific

### ISSUE THREAD

**Issue by vladimir-didenko** [linuxmint/Cinnamon#2892]
Last commits in Cinnamon and cinnamon-control-center moved locales handling from c-c-c to mintlocale that is Mint specific and will not work in another distros. Are there any chances to get configuration module that will work on all distros?

**Comment by ManIVIctorious** [comment]
The locale settings are not only available on LinuxMint, at least they are integrated in Arch Linux and Fedora based distributions

@JosephMcc I think this can be closed
