### ISSUE TITLE
After Installing Cinnamon Can't Move Anything off SD cards, says "Read Only"

### ISSUE THREAD

**Issue by chosenbygrace** [linuxmint/Cinnamon#2894]
No, the lock isn't on. I'm reading my cards via a USB 3 hub and a targus card reader, the one sold in walmart at this time. I tried two different cards from diff companies, one a cheap 2GB one another a 32GB one. It won't let me make folders on them and says they are read only. I didn't have them problem in Unity, but to see if it's the GUI I'll switch back and check right now.

**Comment by Vahan86** [comment]
@JosephMcc, since there is no response from OP for 2 years, can we close this issue?
