### ISSUE TITLE
[Feature request] *Optional* "Locally integrated menus"

### ISSUE THREAD

**Issue by gauravjuvekar** [linuxmint/Cinnamon#2897]
http://www.omgubuntu.co.uk/2014/02/locally-integrated-menus-ubuntu-14-04

Old idea on community.linuxmint.com
http://community.linuxmint.com/idea/view/2978

**Comment by johnathanmorlock** [comment]
Hey guys, is this something that we can do? I've not seen the option for this nor a workaround to add this. I've initally added this request to the LM Community here:
http://community.linuxmint.com/idea/view/5567

**Comment by JosephMcc** [comment]
I don't think this is a direction we want to go.
