### ISSUE TITLE
Add PPPoE connections to network-manager-applet

### ISSUE THREAD

**Issue by mkmkme** [linuxmint/Cinnamon#2902]
Sorry for my bad English,
Repost from GNOME bugtracker. I just don't know, should I post individual issue for Cinnamon. https://bugzilla.gnome.org/show_bug.cgi?id=724945
"Please add subj to nm-applet. I really like GNOME 3 and, in particular,
Cinnamon, but the absence of DSL-connections drives me crazy."

**Comment by akostadinov** [comment]
Would have been nice if instead of DSL the label was something like "DSL/PPPoE". I couldn't figure out how to configure PPPoE on my own because my setup does not involve any DSL modems. </hijack>
