### ISSUE TITLE
[Usability/Readability] Network connections hard to identify

### ISSUE THREAD

**Issue by bcelary** [linuxmint/Cinnamon#2909]
Not sure if this has been already suggested. I've searched for this type of report and haven't found it.

The problem with cinnamons' release in LM 16 / Petra which I am using right now is the readability of the network connections. Instead of using a connection name assigned in the network manager, the network settings applet and the indicator for network devices uses the name of the device. I have 3 cards of the same type in my VBox machine. The problem is I am not able to distinguish which is which. Attaching a picture which explains what I mean:

![networking-readability](https://f.cloud.github.com/assets/376943/2256243/c08491d4-9e03-11e3-94aa-17975700f92f.png)

**Comment by Vahan86** [comment]
@bcelary, is this still relevant in Connamon 3.0?
