### ISSUE TITLE
Remember which Workspace each window belongs to across crashes/reboots

### ISSUE THREAD

**Issue by logannc** [linuxmint/Cinnamon#2912]
This is a feature request, I guess.

It would be nice to have Cinnamon remember which windows belonged where. Occasionally I'll have Cinnamon crash and all of my windows get shoved in Workspace 1 and I have to resort them to the other workspaces. It's not a problem, nor is it frequent, but I still feel like it'd be a good feature to have.

Optionally, this could also be persistent across reboots/OS crashes. I imagine solving this optional problem would also yield the ability to automatically restart the programs you had open on shutdown. I, personally, feel that it is more likely you want the same applications open again when you reboot more often than you want nothing to be there.

Incidentally, regarding the Cinnamon crash, I *think* it was caused by an overflow in a notification? But I can't be sure. Would that be an issue in Cinnamon or a different project?

**Comment by Vahan86** [comment]
Issue https://github.com/linuxmint/Cinnamon/issues/821
