### ISSUE TITLE
Edge resistance broken in multi-monitor environments with different resolutions

### ISSUE THREAD

**Issue by lewisthompson** [linuxmint/Cinnamon#2929]
Works:

3*1920x1080 monitors in a row (total resolution = 5760x1080)
Window moving edge resistance works at top, left, right and bottom of all three displays

Does not work:

2*1920x1080 monitors in a row with a third in portrait, e.g.

![screenshot from 2014-03-12 14 43 14](https://f.cloud.github.com/assets/4053372/2398352/acfeb322-a9f4-11e3-9a2e-60cedc159590.png)

In this configuration edge-resistance works on all monitors at left & right.  The third (portrait) monitor works additionally at top and bottom.

The two landscape monitors have no edge resistance at their top and bottom.

I presume this is because the algorithm is taking into account the overall bounding box and not that of the individual monitor.

**Comment by Vahan86** [comment]
@lewisthompson, is this still an issue in Cinnamon 3.0.x?

**Comment by lewisthompson** [comment]
Sorry not sure as I'm no longer using Cinnamon.
