### ISSUE TITLE
[Feature Request] Cinnamon Scale

### ISSUE THREAD

**Issue by nfat** [linuxmint/Cinnamon#2938]
i prefer scale for left-top hot corner. Scale may be improve. My idea is looks like this:
http://s28.postimg.org/wtl0bt3wd/idea.png

**Comment by kevlogan90** [comment]
+1

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html
