### ISSUE TITLE
Cinnamon Crashes when using nividia-graphics-current with dual moniters

### ISSUE THREAD

**Issue by sirlag** [linuxmint/Cinnamon#2939]
Cinnamon desktop crashes when trying to add a second monitor to cinnamon/xorg with the nividia control panel. The problem is resolved when swapping to a single monitor, using another desktop environment, or swapping back to the open source drivers.

**Comment by mattcbro** [comment]
I am having issues as well in the dual monitor case.  In particular linux mint 17.1 - 17.2 freezes at the start prior to mdm giving me a login screen,  whenever I have both monitors turned on.  I have an Nvidia gtx 770 graphics card.

**Comment by Vahan86** [comment]
@sirlag, is this still an issue for you in Cinnamon 3.0?

**Comment by Vahan86** [comment]
@JosephMcc, can we close this issue?
