### ISSUE TITLE
Conky disappeared after Cinnamon update (Arch Linux)

### ISSUE THREAD

**Issue by petter3k** [linuxmint/Cinnamon#2940]
Hi,

after the update of cinnamon-session (and possibly other things) a couple of days ago (version 2.0.6) conky now refuses to show.

Conky settings: http://codepaste.net/5gww8z

Cinnamon 2.0.14-3
Cinnamon-session 2.0.6-2

x86_64

Conky log is normal:

Conky: desktop window (120002f) is subwindow of root window (287)
Conky: window type - override
Conky: drawing to created window (0x1600001)
Conky: drawing to double buffer

**Comment by ManIVIctorious** [comment]
Is this still relevant in cinnamon 3.0?
