### ISSUE TITLE
Color of links in notifications

### ISSUE THREAD

**Issue by ghost** [linuxmint/Cinnamon#2952]
It seems that it is impossible to set the color of links that appear in notifications from within the cinnamon.css file.
The color is some light pink.
On any lighter theme (including mint-x) the links are barely visible.

**Comment by zagortenay333** [comment]
Bump. Still here: 
![screenshot-screen-2015-09-18-112026](https://cloud.githubusercontent.com/assets/11144630/9956471/36442478-5df9-11e5-9678-2515f1a59346.png)

**Comment by zagortenay333** [comment]
OK, I just noticed that they can be styled. The `.url-highlighter` uses a special `link-color` property to acomplish this. The only thing that is odd is how it borrows the opacity from the `color` property.

This should also be added to mint's default themes: https://github.com/zagortenay333/ciliora-tertia-cinnamon/blob/25c8755f12240a4b9202543c393aaaf432a40816/Ciliora-Tertia/cinnamon/sass/main-modules/_notifications.scss#L5-L12

**Comment by JosephMcc** [comment]
Cool, thanks for the heads up.

**Comment by Vahan86** [comment]
@JosephMcc, can we mark the issue as a feature request?

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html
