### ISSUE TITLE
Previous windows active when running app from main menu requires root password.

### ISSUE THREAD

**Issue by enlait** [linuxmint/Cinnamon#2953]
When a user runs an application from main menu, and that app asks for root password (e.g.: user groups); also, the previous active window is on a secondary display - that window is activated instead of root password window.

Very funny when that "previous active window" is a chat.

Quite minor and specific, but also very counter-intuitive.

**Comment by Vahan86** [comment]
@enlait, is this still an issue for you in Cinnamon 3.2?

**Comment by enlait** [comment]
I'm afraid I do not have a suitable installation up at the moment to verify if the issue persists. If it's not reproducible for you, close the issue as you see fit. Thank you.

**Comment by Vahan86** [comment]
@enlait, thank you for your reply. In this case can you please close the issue?

**Comment by Vahan86** [comment]
@JosephMcc, can we close the issue?
