### ISSUE TITLE
Cinnamon screen lock during suspend broken

### ISSUE THREAD

**Issue by geckolinux** [linuxmint/Cinnamon#2961]
Hi there, 
I have been running Cinnamon on Manjaro Linux for quite a while now. The most recent update to cinnamon-screensaver 2.0.3-4 and cinnamon-settings-daemon 2.0.8-4 seems to have introduced a regression. The dconf setting org.cinnamon.settings-daemon.plugin.power "lock on suspend" doesn't work anymore. My laptop does suspend, but upon resuming there is no lock screen. I downgraded to 
cinnamon-screensaver 2.0.3-3 and cinnamon-settings-daemon 2.0.8-2 and screen locking works again.
Thanks for the help with this bug!

**Comment by ManIVIctorious** [comment]
@JosephMcc I think this one can be closed

**Comment by ManIVIctorious** [comment]
Thanks :)
