### ISSUE TITLE
Open application on the workspace it was launched from

### ISSUE THREAD

**Issue by j-dowsett** [linuxmint/Cinnamon#2962]
It would be nice to have an option to restrict a new instance of an application to open on the workspace it was launched from.  eg, if I launch an application that takes a while to start I may then switch to another workspace to continue other work rather than wait for it to start.  However the launched application then opens on the currently active workspace rather than the one from which it was launched.

On a similar principle, if, eg, I double click a text file, the current workspace is changed to one in which the text editor is already open.  I would much prefer a new instance to be launched on the current active workspace.

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html
