### ISSUE TITLE
Accessibility Zoom causes Cinnamon 2.0 to freeze (Mint 13 / 16 / Debian 201403)

### ISSUE THREAD

**Issue by rojthevorlon** [linuxmint/Cinnamon#2963]
See pastebin:

Using accessibility zoom and zooming in / out causes the system to freeze in several situations:

http://pastebin.com/VVTJWvwF

**Comment by JosephMcc** [comment]
@rojthevorlon is this still an issue in Cinnamon 2.8?

**Comment by rojthevorlon** [comment]
No - I'm happy to report it's all good.  thanks!
