### ISSUE TITLE
Windows Move

### ISSUE THREAD

**Issue by fthpi** [linuxmint/cinnamon#2995]
if i move window with right click window title->move or alt+f7 combination after release mouse  button, window tiling isnt work correctly and window stay same position.
it looks:
http://i.imgur.com/tC8x0M4.png

**Comment by pixunil** [comment]
In latest git, the problem changed its behaviour: the window still doesn't resize and the outline stays, but the window is still moveable. I think it is because the outline is handled by cinnamon now.

**Comment by lisuml** [comment]
On my cinnamon-3.0.7 windows are not being moved correctly with ALT+F7 when pressing SHIFT+Arrow keys.

**Comment by stealthybox** [comment]
possibly related to #4272 ?

**Comment by Vahan86** [comment]
@nfat, is this still an issue for you in Cinnamon 3.6?

**Comment by icarter09** [comment]
Linux Mint 19.2
Cinnamon 4.2.4

I'm not able to reproduce this bug. I was able to move the window around with `Alt+F7` and with the mouse as well. Tiling worked correctly and resizing worked. Moved and resized several windows without any issues.

**Comment by Vahan86** [comment]
@icarter09, it works fine for me in Cinnamon 4.2.4 as well. Can we close the issue?
