### ISSUE TITLE
cinnamon lock-ups 

### ISSUE THREAD

**Issue by bhcopeland** [linuxmint/Cinnamon#3000]
Hi,

I have a freshly installed version of arch Linux. I have no applets installed. 

I am experiencing complete freezes. I can move the mouse but no windows respond. My only fix is to load up a different tty, write kill -HUP cinnamon, and the start up cinnamon again.  

However this doesn't always work and I often have to reboot. This has started happening at least once-twice a day now.

What do you need to diagnostic the problem?

Thanks

**Comment by megz** [comment]
its now 2.6 and now its all fine thanks  :)

**Comment by Vahan86** [comment]
@JosephMcc, can we close this issue since it seems to be fixed?

**Comment by JosephMcc** [comment]
This is probably a better place for it anyway https://github.com/linuxmint/Cinnamon/issues/4072
