### ISSUE TITLE
Better Overview & Scale

### ISSUE THREAD

**Issue by fthpi** [linuxmint/cinnamon#3001]
Maybe Overview and Scale are improve, i try small changes in overview.js, results are goods look

FOR SCALE:
open file -> sudo gedit /usr/share/cinnamon/js/ui/overview.js

1) Show Panels: 
comment (with //) rows 294 and 402:

294: //Main.disablePanels();
402://Main.enablePanels();

now panel is not hide when overview active

2)Show Desktop: 
change after row 155 like this ;
global.screen.toggle_desktop(global.get_current_time());
result = SwipeScrollResult.CLICK;
this.emit('swipe-scroll-end', result);
this.hide();

now when you click non-window area, show desktop is active

Fix for, window behind the panel issue (if you use top panel):
open workspacesView.js
sudo gedit /usr/share/cinnamon/js/ui/workspacesView.js
row 208, chaneg 0 value to your panel height (or if you want)
workspace.actor.set_position(x, 0);

http://s1.postimg.org/ciy5q8xdb/Ekran_G_r_nt_s_2014_04_03_15_31_20.png

FOR EXPO:
1)Show Panels
open expo.js
sudo gedit /usr/share/cinnamon/js/ui/expo.js 
Comment row 324 and 393
324: //Main.disablePanels();
393:  //Main.enablePanels();

Fix for, window behind the panel issue (if you use top panel):
open expoThumbnail.js
sudo gedit /usr/share/cinnamon/js/ui/expoThumbnail.js
row 213, change second 0 value to your panel height (or if you want)
this._expo.actor.set_position(0,0);

http://s28.postimg.org/hywov2urx/Ekran_G_r_nt_s_2014_04_03_17_15_09.png

**Comment by icarter09** [comment]
@collinss can this ticket be closed?

**Comment by collinss** [comment]
yup
