### ISSUE TITLE
[Bug Report] Archive Manager no work properly with auto-renamed duplicate file

### ISSUE THREAD

**Issue by highwindmx** [linuxmint/Cinnamon#3002]
I am not sure if it is a cinnamon bug, actually it comes from firefox and Archive Manager.
when download a duplicate (Name).tar.gz file in firefox the system will rename it into (Name).tar-1.gz then Archive Manager seems can not recognize it well.
![screenshot from 2014-04-03 20 55 00](https://cloud.githubusercontent.com/assets/6413481/2610877/c67c213a-bb93-11e3-8019-1a7e4c0dda5a.png)

**Comment by Vahan86** [comment]
@JosephMcc, it's not related to Cinnamon, can we close this issue?
