### ISSUE TITLE
[Feature Request] applet can show sessions at top N of network traffic

### ISSUE THREAD

**Issue by highwindmx** [linuxmint/cinnamon#3016]
nethogs is the only app I know for now can show network traffic by each session/process/program.
(
in particular, I mean the app can show like as following:
 firefox         XX kb/s     XX mb in total 
 user-script  XX kb/s     XX mb in total 
)
Do any one know more about such kind of apps? If not, here is the feature request.

I know it may not be actually a cinnamon thing, but if there is one, I think desktop users will quite like to use it.
Thanks.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
