### ISSUE TITLE
cinnamon-settings - wrong label trancation

### ISSUE THREAD

**Issue by vladimir-didenko** [linuxmint/Cinnamon#3017]
cinnamon-settings.py uses follow code 

```
name = sp.name
if len(name) > 30:
    name = "%s..." % name[:30]
```

to truncate label names. Unfortunately it doesn't work correctly with  utf-8 strings since some characters use 2 bytes to encode one symbol.  I am using follow patch

http://git.altlinux.org/people/cow/packages/?p=cinnamon.git;a=commitdiff;h=98339ea7f938a1e8a4788b7bac19342fcf768a57

though not sure that it is most right way to fix.

**Comment by Vahan86** [comment]
@vladimir-didenko, is this still an issue in Cinnamon 3.2?

**Comment by vladimir-didenko** [comment]
@Vahan86  No, it is fixed in upstream code.
