### ISSUE TITLE
Cinnamon menu logout "switch user" button does nothing

### ISSUE THREAD

**Issue by geckolinux** [linuxmint/Cinnamon#3018]
Hi,
I'm running Cinnamon 2.0.14-3 on Manjaro (Arch) with MDM. I'm not sure if MDM has anything to do with it, but the menu->logout->"switch user" button in the popup logout dialogue does nothing. However, user switching does work fine from the User Applet in my panel.
Thanks for the help!

**Comment by Vahan86** [comment]
@geckolinux, is this still an issue for you with Cinnamon 3.0?

**Comment by geckolinux** [comment]
Fixed now, thanks!
