### ISSUE TITLE
Dual Monitor and Desktop Layout

### ISSUE THREAD

**Issue by jobdiogenes** [linuxmint/Cinnamon#302]
When using Dual Monitor Settings (Extended Display/Not Mirror)

Desktop Layout:

Traditional: Works
Classic:  Panel Crash
Flipped: Panel Crash

Thanks

Job Diogenes

**Comment by ngolovin** [comment]
Sorry about digging up the grave

My Cinnamon 2.4.8 pannel and window rendering seem to crash if my dual monitor has different height from the main (left or right, it doesn't matter)
(my graphic card is a intel chipset with an i5)
If it's the same height, it seems to not crash, but did it once or twice (not so ofthen like when two monitors has different heights).
It may be related to hardware performance...

**Comment by DaAwesomeP** [comment]
I have a 945GM for graphics, and my computer becomes unusably slow with two monitors (also different heights and width).

**Comment by ngolovin** [comment]
did 'cinnamon --replace' process  pumping so much of cpu sometimes? i constated that recently
other thing i constated, adding a second bar on the auxiliary screen helps to maintain cinnamon without crashing too much times, i actually have one aux monitor with resolution bigger than the main one
it works for now...

**Comment by DaAwesomeP** [comment]
I found that it is compiz. The only available workarounds are to either disable compiz completely put the monitors on top of one another (vertically) instead of horizontally (left and right of each other). This is due to a limit of the maximum texture size of my graphics card (2048x2048). Both screens combined are larger than that. It is an old computer though.

**Comment by dalcde** [comment]
How could you possibly be using Cinnamon and compiz together?

**Comment by DaAwesomeP** [comment]
I guess that I'm not using compiz then. I'm pretty new to Cinnamon. But doing the same fix for [a bug in compiz](https://bugs.launchpad.net/ubuntu/+source/xorg-server/+bug/555641) **did** solve the problem - arranging the monitors vertically. Now it's as fast as if I only had one monitor. It is *extremely* annoying though. It's a hardware limitation, so I'm not sure how it would be fixed. I'm on openSUSE 13.2 i586 with Intel 945GM graphics on a Dell Latitude D620 (originally ran XP).
