### ISSUE TITLE
Strange behavior of Ctrl+(Shift|Alt) shortcuts

### ISSUE THREAD

**Issue by vladimir-didenko** [linuxmint/Cinnamon#3021]
Ctrl+(Shift|Alt) shortcut behavior is strange - it works only if Shift|Alt is pressed first. E.g. - set Ctrl + Shift shortcut as modifier to change keyboard layout and try to change layout. If Ctrl button is pressed first it doesn't work. But if Shift button is pressed first layout is changed as expected. The same situation if you set hotkey with Ctrl + (Shift|Alt) to run user specified command - it will work only if Ctrl is pressed last.

**Comment by Vahan86** [comment]
@JosephMcc, I suggest to close the issue since there is no response from OP for a long time.
