### ISSUE TITLE
Display rotation confuses start menu

### ISSUE THREAD

**Issue by vranki** [linuxmint/Cinnamon#3022]
I have a pc with two monitors. Rotating the left one (with taskbar) 90 degrees causes the start menu to be displayed incorrectly. The shortcut buttons on the left side are outside the screen and the application groups fit only half way. In more technical terms, the x coordinate of the menu is negative and width is more than the (rotated) display width.

Other apps work fine with rotated setup so I believe this is a bug in Cinnamon.
Tested with 2.0.14-20131203 on Ubuntu Saucy.

![20140409_001](https://cloud.githubusercontent.com/assets/81116/2655521/721055fa-bfe7-11e3-8208-bc6692d9012e.jpg)

**Comment by Vahan86** [comment]
@vranki, is this still an issue in Cinnamon 3.0?

**Comment by vranki** [comment]
Nope, this has been fixed.
