### ISSUE TITLE
[Feature Request] little UI design Problem: rearrange buttons in popup window.

### ISSUE THREAD

**Issue by highwindmx** [linuxmint/Cinnamon#3023]
![rr](https://cloud.githubusercontent.com/assets/6413481/2656348/e4d404c0-bff0-11e3-848f-65b5620488f8.png)
You can see in the pic, the width of window changed based on the file-name length,
then the problem comes: the three action button doesn't arrange align to left but right, then if there are multiple file waiting to be treated, I have to move my cursor continuously, it is quite inconvenient.

This little improvement may be more friendly to the users.
The solution may either align buttons to left or limit the width of the window, and I hope this obey the style of the main UI design.

**Comment by ManIVIctorious** [comment]
Totally agree with you. Unfortunately this is no cinnamon issue and belongs to linuxmint/nemo.
Could you please file the bug there?

**Comment by JosephMcc** [comment]
https://github.com/linuxmint/nemo/issues
