### ISSUE TITLE
[Suggestion] name of "Removable drives" applet

### ISSUE THREAD

**Issue by highwindmx** [linuxmint/Cinnamon#3027]
I know the designer making this applet for people who want to easily eject removable drives, while actually in its popup menu shows "mountable / unmountable devices", like in my computer it shows some partitions are not really un-removable.

Rename it or distinguish those un-removable devices? :)

Thanks

**Comment by Vahan86** [comment]
@JosephMcc, can we mark this issue as a feature request?
