### ISSUE TITLE
Automatically open a folder for automounted media option is wrong

### ISSUE THREAD

**Issue by nixahn** [linuxmint/Cinnamon#3028]
In nemo go to edit,preferences,behavior tab.

The automount options don't work properly. The second option (Automatically open a folder for automounted media) does not do what it says. Moreover, unless this option is checked, the automount selected from the first checkbox (Automatically mount removable media when inserted and on startup) does not work.

**Comment by Vahan86** [comment]
@JosephMcc, I think this issue is related to Nemo and should belong here: https://github.com/linuxmint/nemo.

@nixahn, does this still an issue in Cinnamon 3.0?

**Comment by JosephMcc** [comment]
If this is still an issue, please move it to the Nemo repo linked by @Vahan86.
