### ISSUE TITLE
Some minor visual issues in Cinnamon Settings

### ISSUE THREAD

**Issue by Garibaldo** [linuxmint/Cinnamon#3036]
Just some minor alignment issues on Cinnamon Settings:

<a href='http://postimage.org/' target='_blank'><img src='http://s27.postimg.org/79vwsq6ub/asdf.jpg' border='0' alt="asdf" /></a><br /><a target='_blank' href='http://postimage.org/'>gifs upload</a><br /><br />

<a href='http://postimage.org/' target='_blank'><img src='http://s30.postimg.org/bh0id4zdt/asdf2.png' border='0' alt="asdf2" /></a><br /><a target='_blank' href='http://postimage.org/'>pictures upload</a><br /><br />

**Comment by dalcde** [comment]
Closing unless someone reproduces it
