### ISSUE TITLE
Can't change keyboard layout in Lock Screen

### ISSUE THREAD

**Issue by Baranchik** [linuxmint/Cinnamon#3048]
when cinnamon enters lock screen, the keyboard layout can't be changed, which when in a non English layout renders the user impossible to unlock the screen.

affecting Cinnamon 2.0.14

**Comment by anandrkris** [comment]
Reported [here] (https://github.com/linuxmint/Cinnamon/issues/3483) as well.

**Comment by mtwebster** [comment]
There should be a language selector immediately to the right of the password entry.

Is this not the case?

**Comment by mxa** [comment]
No it is not the case. In MATE there is though.

**Comment by Vahan86** [comment]
Tested with some of non English layouts. Works fine for me. Cinnamon version: 3.0.7 

@JosephMcc, can we close this issue?

**Comment by JosephMcc** [comment]
I want to hold off. The screensaver is getting a complete rewrite for Cinnamon 3.2. I'll look at all the screensaver issues when that is done.

**Comment by Vahan86** [comment]
@Baranchik, is this still an issue for you with Cinnamon 3.2?

**Comment by Vahan86** [comment]
@JosephMcc, can we close the issue?

**Comment by NikoKrause** [comment]
@mxa Why should this be reopened? Any info of your system, screenshots?

**Comment by juliuspopp** [comment]
@NikoKrause I cannot change keyboard layout at login screen of LM 20.0

**Comment by leigh123linux** [comment]
@juliuspopp  Start a new issue!
