### ISSUE TITLE
[sound applet] album cover issues

### ISSUE THREAD

**Issue by ghost** [linuxmint/Cinnamon#3052]
2 suggestions!

Make the cd player icon smaller; it is humongous.Here is a comparison between the soundbox desklet and the sound applet:
![secondary_002](https://cloud.githubusercontent.com/assets/5655339/2705717/c36ff528-c482-11e3-9058-b6dc5f870493.png)

Also, an option to turn of the album cover would be very awesome.The album cover is not an essential part of the sound applet, yet it makes it huge!The soundbox applet has this option:
![selection_004](https://cloud.githubusercontent.com/assets/5655339/2705741/2281189e-c483-11e3-957d-b106cb36d125.png)

EDIT I think the "Unknown album" should be above the album cover, together with the other 2 infos!

**Comment by JosephMcc** [comment]
The sound applet has been completely redesigned since this request was made.
