### ISSUE TITLE
Modifer tap bindings should be on key up

### ISSUE THREAD

**Issue by Psykar** [linuxmint/Cinnamon#3057]
- Bind a function (say scale) to a modifier key only (ie. Control_L / Super_L etc)
- Hit the binding, action occurs on key down, which breaks any other bindings using that modifier.

Interestingly this _isn't_ an issue with the default menu binding - it only opens the menu on Super_L _up_, so other Super_L modifier bindings work fine - everything else will activate on the _down_ press.

**Comment by JosephMcc** [comment]
Can't be reproduced on git master.
