### ISSUE TITLE
[Bug Report] I can see my desktop without login

### ISSUE THREAD

**Issue by highwindmx** [linuxmint/Cinnamon#3060]
Cinnamon 2.0.14

The problem is after I suspend(or just close the lid) the computer, then wake it up again,
sometimes I can directly see my desktop, then wait for several seconds the login interface come back and let me to input password to login.
I think it may be related to some security problem for computer which is used by several people.

1.I will give more details as you asked.
2.does suspend + require password when waking ==  suspend + logout?

Thanks

**Comment by TopView** [comment]
**Solution:**  https://github.com/linuxmint/Cinnamon/issues/4324#issuecomment-1685426989
