### ISSUE TITLE
power applet bug

### ISSUE THREAD

**Issue by BurnLine** [linuxmint/Cinnamon#3068]
after upgrade to cinnamon 2.2.3 power applet disappear.

but after suspend (whitch is not working after lid close) there shows up icon...but after another suspend there are now two icons in power applet.... and so on... (now I have 4)

in d-feet program I can get informations about batery state from org.freedesktop.UPower, but in org.cinnamon.SettingsDeamon org/cinnamon/SettingsDeamon/power -> getDevices shows up that duplicated devices (or no device after restart and without suspend)

otherwise I like this new update

**Comment by moorkai** [comment]
I have built the 2.6.1 Cinnamon GitHub release as well as other dependencies needed for Cinnamon to build successfully (as per Mint's [Segfault] (http://segfault.linuxmint.com/2013/10/how-to-build-and-install-the-latest-cinnamon-from-git/) post) on my Vivid laptop and am encountering this issue. Prior to that, I was using [Tsvetko's build] (https://launchpad.net/~tsvetko.tsvetkov/+archive/ubuntu/cinnamon) of Cinnamon 2.4.8 as well as the dependencies found there on Utopic and everything was kinda fine, sans the *installing Trusty packages on Utopic* part. Updated to Vivid, built new Cinnamon, and ... here I am. "upower -d" properly shows battery percentage, unlike the Power Manager applet and the Power Management part of Cinnamon Settings. Just noticed Cinnamon 2.6.2 is out, is it maybe addressed there?
