### ISSUE TITLE
Cinnamon Menu :: Slow to appear when used the keyboard button while opens aptly when clicked.

### ISSUE THREAD

**Issue by koldbyte** [linuxmint/Cinnamon#3075]
I am noticing a huge difference between the time it takes to toggle the menu applet using the Keyboard's Super button and while using the mouse click.

With keyboard, it takes more than 1 s.
While with mouse click, it is almost instantaneous.
I am currently running on LinuxMint 16 Cinnamon 2.0. 
Panels are in top.(if it matters).
I have tried both the "Configurable Menu applet" and the Original default menu applet. Both gave the same result.

Is anyone facing the same problem?

**Comment by Vahan86** [comment]
@koldbyte, is this still an issue for you in Cinnamon 3.2?

**Comment by JosephMcc** [comment]
Yes, it is still slower.

**Comment by lestcape** [comment]
@JosephMcc your patch to remove the effect only for the main menu is working only inside the menu code. When the appletmanager  it's who send the signal, your patch don't take effect and the menu will be close with an animation. This probably the slow down that you notice.
