### ISSUE TITLE
Lock Desklets

### ISSUE THREAD

**Issue by highwindmx** [linuxmint/Cinnamon#3078]
Cinnamon2.0.14
recently,I tried some desklets such as "clock desklet" or "weather desklet"
There is one problem annoying me, which is I can't fix or pin the desklet on the desktop, they may be accidentally moved.

so my request is: can these desklets be embed in desktop,
I know once embed, it can't be moved, so how about create a edit mode (just like in panel).

Thanks

**Comment by abdupattoh** [comment]
This issue has forced me to remove the clock desklet.

**Comment by Vahan86** [comment]
@JosephMcc, can this issue be marked as a feature request?

**Comment by holtzilya2008** [comment]
+1

**Comment by Kwaadpepper** [comment]
This feature is needed and not a fancy thing. Please consider.

**Comment by johanvandegriff** [comment]
I kept moving the desklets so often that I had to write a script to move them to their original position:
```
gsettings set org.cinnamon enabled-desklets "['battery@schorschii:3:1700:100', 'devTools@scollins:9:850:0', 'netusage@30yavash.com:13:1425:850', 'simple-system-monitor@ariel:16:1700:200', 'TimeAndDate@nightflame:20:1650:0']"
```

You can find the current positions with:
```
gsettings get org.cinnamon enabled-desklets
```

**Comment by tetoNidan** [comment]
I to would very much like this to be a feature as I hate antecedently dragging them from their well positioned positions, mostly I hate having to put them back. It's a complete waste of time.

I have a workaround. You can install deconf editor and disable show-desktop-icons under ogg>nemo>desktop.

You will loose all your desktop icons.

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html

**Comment by mfreeman72** [comment]
What's the current state of this?

I've recently noticed a problem on Linux Mint 20, where if I'm simply moving my mouse pointer over a desklet's position, the desklet decides to attach to the mouse and moves with it. This happens with or without clicking, and even sometimes when interacting with a window that's on top of the desklet. It would be really great to have the option to just lock them down, and allow them to only move when initially placing them or editing their configuration.

**Comment by claudiux** [comment]
@mfreeman72 I have already encountered the same issue, which is still in Cinnamon 4.6.7. This issue is closed; please open a new one.

**Comment by eGit** [comment]
Yes. Desklets are horrible. It's sticking to my mouse pointer. I honestly wanted to punch the monitor. What the actual f**k! Sorry for my french but this is an embarrassment. Why not remove Desklets if you obviously don't give a damn?!

Why aren't Desklets "locked" by default and only movable when I click on "configure" or something.

**Comment by spuggiehawk** [comment]
How did this get closed.  It hasn't been addressed and isn't fixed.  eGit is correct, when a desklet has been placed, you should only be able to move it as part of it's configuration options.

**Comment by Ducvoccer** [comment]
Up

**Comment by gskerry** [comment]
+1
RE [github issues/feature tracking](https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html#why-are-ideas-and-feature-requests-closed)... is there a separate feature backlog with any sort of community upvoting functionality?

**Comment by Ducvoccer** [comment]
up

**Comment by mfreeman72** [comment]
Instead of replying to this one, why not use the issue that I opened? This one is closed, that one is not. Go to issue #9622

**Comment by DirkHaar** [comment]
> I kept moving the desklets so often that I had to write a script to move them to their original position:
> 
> ```
> gsettings set org.cinnamon enabled-desklets "['battery@schorschii:3:1700:100', 'devTools@scollins:9:850:0', 'netusage@30yavash.com:13:1425:850', 'simple-system-monitor@ariel:16:1700:200', 'TimeAndDate@nightflame:20:1650:0']"
> ```
> 
> You can find the current positions with:
> 
> ```
> gsettings get org.cinnamon enabled-desklets
> ```

Thanks for this example, I nearly gave up on this.
Neither the "gsetting set" syntax help text nor dconf-editor do show that
the array of comma-seperated, single quote enclosed strings enclosed by brackets has to be enclosed by double-quotes.
