### ISSUE TITLE
Support lxdm user switching

### ISSUE THREAD

**Issue by fluancefg** [linuxmint/Cinnamon#3083]
Hi,
Based on a discussion on Archlinux forum (https://bbs.archlinux.org/viewtopic.php?id=180326), it seems that cinnamon only supports GDM, MDM and LightDM for user switching. As some of us are using lxdm with cinnamon, it would be great if cinnamon supports lxdm user switching, too.
The same feature must be integrated in cinnamon-screensaver to display a switch user button when the screen is locked.
The same must be integrated in the user applet to support lxdm user switching (https://github.com/linuxmint/Cinnamon/tree/master/files/usr/share/cinnamon/applets/user@cinnamon.org).

**Comment by ManIVIctorious** [comment]
Is this still an issue in cinnamon 3.0?

**Comment by fluancefg** [comment]
I can't answer, I'm using lightdm at the moment.
