### ISSUE TITLE
Volume/Brightness OSD bar 1px to short

### ISSUE THREAD

**Issue by theSeppi** [linuxmint/Cinnamon#3088]
When changing the volume or screen brightness a small OSD appears. This OSD shows the current volume/brightness level with a horizontal white bar.

However, this bar is 1px too short when at it's maximum, so there's a 1px darker stripe remaining. (At least on my 1366x768 display.)

**Comment by pixunil** [comment]
Guess this is fixed in git as the whole OSD thing is now rendered in cinnamon (theming).
