### ISSUE TITLE
password visible while screen locked using ibus + anthy

### ISSUE THREAD

**Issue by Azanx** [linuxmint/Cinnamon#3089]
Linux Mint version: Linux Mint 16 Cinnamon 64-bit
Cinnamon version: 2.0.14
Linux Kernel: 3.11.0-12-generic

I was writing in japanese using IBUS+ANTHY.
I left the computer for a while (monitor switched off and screen was locked automatically), after unlocking the screen i have been asked for my user password.

When I started typing my password, I realised I can see all the numbers and letters(in the form of japanese kana signs of course) instead of standard "dots"
I couldn't change the keyboard settings to standard (polish in my case) with shortcut: ctrl+space, there was also no such option on the screen I could find.
I selected "switch user" option, and logged again from there to the same account without any problems

I think problem may be related to:
https://github.com/linuxmint/Cinnamon/issues/3048

**Comment by Vahan86** [comment]
@Azanx, is this still an issue for you in Cinnamon 3.0?

**Comment by Vahan86** [comment]
@JosephMcc, can we close this issue?

**Comment by Azanx** [comment]
Sorry for late reply. I just checked it (cinnamon 3.2.2, mint 18) and it seems to work correctly (I'm unable to replicate the issue)
