### ISSUE TITLE
Default netspeed applet for Cinnamon 2.2

### ISSUE THREAD

**Issue by freemangilgamesh** [linuxmint/Cinnamon#3094]
Would you please include a netspeed applet by default (like mate-netspeed) that monitors network interfaces automatically. the one that exists on cinnamon spices (http://cinnamon-spices.linuxmint.com/applets/view/141) does not work on cinnamon 2.2 and it needs lots of configuration.Most people now use mobile broadband connections (especially in my country) and they need it so much.

**Comment by Vahan86** [comment]
@JosephMcc, it's not an issue related to Cinnamon, can we close this issue?
