### ISSUE TITLE
[Eyecandy] [Lockscreen] Add fadeout animation when locking from shortcut

### ISSUE THREAD

**Issue by gauravjuvekar** [linuxmint/Cinnamon#3098]
When the screen locks after a timeout, there is a nice fade-out animation. Is it possible to do the same when the screen is locked by using keyboard shortcuts or through the  menu?

I don't mean exactly the same, it should probably be a bit faster(completing in approx 0.8-1.2 seconds) so that it feels responsive.

**Comment by temux86** [comment]
+1

**Comment by Lukypie** [comment]
+1

**Comment by JosephMcc** [comment]
Cinnamon 3.2 will have a new lockscreen where this is implemented.
