### ISSUE TITLE
Applet that notifies updates of installed x-lets.

### ISSUE THREAD

**Issue by anandrkris** [linuxmint/Cinnamon#3099]
The current update mechanism is perfect except that user has to manually check for availability of updates for the installed / active desklets, applets, extensions. The issue here is the discover-ability of new features and awareness of updates available. The current mechanism makes is bit cumbersome to check for updates in each of the places discretely.  There should be unified mechanism to at least notify users if not install updates for x-lets.

Should simply convey "Updates available for n - number of applets, m - number of desklets, etc.

Configuration required is only on frequency of refresh in hours / days.

Or a notification from each of the x-let is also welcome but requires changes by author of all x-lets. Eg: RSS feed applet puts a notification when a new feed item is available.

Another utopian alternative is integration with Update Manager but it is not tied only to Cinnamon, so refraining from the temptation of suggesting it. :wink:

**Comment by JosephMcc** [comment]
https://github.com/linuxmint/Cinnamon/issues/6706
