### ISSUE TITLE
Setting to center/freely place applets in bars

### ISSUE THREAD

**Issue by t3mux** [linuxmint/Cinnamon#3100]
Well i think the title says everthing. I just want my clock in the center of a bar but i cannot center it because its position is based on the applets on the right and the left.

I would like to see a center settings to avoid this or that applets could placed freely in the bar. The latter could be the better option.

**Comment by JosephMcc** [comment]
Applets placed in the center are now placed at screen center and ignore the size of the left and right boxes and it's been this way for awhile.
