### ISSUE TITLE
[Bug] Tab completion in alt+F2 dialog does not escape spaces

### ISSUE THREAD

**Issue by gauravjuvekar** [linuxmint/Cinnamon#3101]
Trying <kbd>alt</kbd>+<kbd>F2</kbd> `nemo /something/something/some`<kbd>Tab</kbd> gets completed to `nemo /something/something/some folder with spaces` instead of `nemo /something/something/some\ folder\ with\ spaces`

**Comment by dalcde** [comment]
Fixed in git master
