### ISSUE TITLE
Firefox shows no text after installing cinnamon

### ISSUE THREAD

**Issue by shubhamjain** [linuxmint/Cinnamon#3106]
I have installed cinnamon on my PC with Ubuntu v13.10 and strangely, Firefox has stopped displaying any text in windows or bars [ [Screenshot]([http://i.stack.imgur.com/2MteJ.png) ]. Even after updating Firefox to latest release the result was same.

**Comment by Vahan86** [comment]
@JosephMcc, can we close the issue since there is no response from OP for a long time?
