### ISSUE TITLE
Picture aspect settings on wallpaper not respected in lock screen

### ISSUE THREAD

**Issue by glasnt** [linuxmint/Cinnamon#3114]
Using a dual screen wallpaper with the picture aspect 'Spanned' setting works fine on the desktop. However, the same wallpaper is used in the standard lock screen, but uses the equivalent to the 'scaled' picture aspect, meaning the entire image is scaled to each screen individually.

**Comment by bkmeneguello** [comment]
Watching this for solution

**Comment by devmau5** [comment]
Still no workaround or fix? :(

**Comment by Vahan86** [comment]
@JosephMcc, can we mark this issue as a bug?

**Comment by JosephMcc** [comment]
If this is still an issue it belongs here: https://github.com/linuxmint/cinnamon-screensaver
