### ISSUE TITLE
system tray icon broken

### ISSUE THREAD

**Issue by kunaguvarun** [linuxmint/Cinnamon#3117]
1.Linux Mint 16 Cinnamon 32-bit edition

2.Suspend and Resume - Cannot login to the desktop. So I pressed CTRL + backspace to reload my desktop

3.Well, desktop reloaded and I'm able to login, but the variety wallpaper changer icon sitting in my system tray icon is broken. The icon uses the entire space as if when it displays fully, but only half of the icon is being displayed.

4.I expect the entire icon is displayed instead of a half.

5.Yeah, the problem happened many a times. I even experienced this with older versions of LM, but this is the first time I'm reporting it.

**Comment by Vahan86** [comment]
@JosephMcc, there is no response from OP for 2 years. Can we close this issue?
