### ISSUE TITLE
cannot unmount fuse file systems

### ISSUE THREAD

**Issue by Lanchon** [linuxmint/Cinnamon#3122]
nemo detects and lists (left pane) mounted fuse fs, shows eject icon next to it.

taskbar mounted fs notification icon, when clicked, lists mounted fuse fs, and also shows eject icon next to it.

both eject icons invoke umount and fail, since fuse fs has to be unmounted via fusermount -u.

encountered with: https://github.com/spion/adbfs-rootless

EDIT: this happens with stock cinnamon in linux mint 16.

PS. cinnamon rocks! :)

**Comment by Vahan86** [comment]
@Lanchon, is this still an issue in Cinnamon 3.0?

**Comment by Lanchon** [comment]
no idea, i'm still on LM 17.x

**Comment by Vahan86** [comment]
@Lanchon, is this issue still relevant to Cinnamon 3.2?
