### ISSUE TITLE
[cinnamon-screensaver] Cinnamon session randomly stops responding after screensaver activation and/or resume from suspend

### ISSUE THREAD

**Issue by geckolinux** [linuxmint/Cinnamon#3123]
Hi, I'm running the latest Cinnamon 2.2 and related packages on Manjaro (Arch). I'm using cinnamon-screensaver 2.2.2-1. I have set the Cinnamon screensaver to activate and turn the screen off after 5 minutes, and also to lock the screen only when suspending. Sometimes, but not every time, after the screensaver activates, I move the mouse and the mouse moves but the rest of the interface stops responding. Sometimes the Cinnamon interface appears but doesn't respond, and sometimes only the screen backlight turns on but shows black. Sometimes it only happens after resuming from suspend, but sometimes it also happens when the system is awake and the screen was turned off by the screensaver. When this happens I have to kill the X server to regain control, thus losing my entire session and all my work. Here's a log of my last X session that I had to terminate due to this bug: 

http://pastebin.mozilla.org/5087528

Notice the lines like:
`"(cinnamon-screensaver:5691): GLib-CRITICAL **: Source ID 323810 was not found when attempting to remove it"`
Not sure if that has anything to do with it?

This bug doesn't occur every time the screensaver activates, but it happens at least once a day, resulting in loss of my work, and started happening with Cinnamon 2.2.

**Comment by ManIVIctorious** [comment]
I personally didn't have this issue for a long time now. @geckolinux is this still an issue for you in cinnamon 3.0?

**Comment by geckolinux** [comment]
Looks like it's fixed now. (Cinnamon 3.x on openSUSE Tumbleweed and Leap.)

**Comment by JosephMcc** [comment]
Wanted to say a quick thanks. @ManIVIctorious for helping point out issues and @geckolinux for actually following up when questions are asked.

**Comment by geckolinux** [comment]
Also thanks for following up on bug reports and actually fixing them.

**Comment by ManIVIctorious** [comment]
I have some spare time this week and depending on the weather I'll help where I can ;)
