### ISSUE TITLE
Show Desktop Icon Style

### ISSUE THREAD

**Issue by xerxeslins** [linuxmint/Cinnamon#3126]
The default icon in the Cinnamon panel to show the desktop, it is very similar to the icon that gives access to Nemo. I suggest changing the style of the Show Desktop icon to be compatible with other icons like the Expo, Scale, Brightness icons, mounted volumes, battery, etc ...

**Comment by ACinnamonUserInUK** [comment]
I too am inconvenienced by this.

**Comment by anandrkris** [comment]
@JosephMcc - For your awareness. :smile:

**Comment by Vahan86** [comment]
Would be nice. +1

**Comment by JosephMcc** [comment]
This was already tried and turned down, so closing it.

**Comment by CottonEaster** [comment]
'This was already tried and turned down'. I find it hard to see why it is a good idea to have the two icons almost identical.

Here are the two icons in Mint 19.1 beta:

![spotthedifference](https://user-images.githubusercontent.com/9998846/49887864-5ce47d00-fe35-11e8-941d-087925f39ae2.png)

One can _tell_ the difference here, but the image above is _much larger_ than lifesize.

**Comment by xerxeslins** [comment]
Deepin has an interesting solution, although it is the same as Windows.
![deepin-show-desktop](https://user-images.githubusercontent.com/7513301/49889450-4da70480-fe20-11e8-9346-f497178dbdb3.jpg)
