### ISSUE TITLE
Automatically sort the desktop icons

### ISSUE THREAD

**Issue by metalmatze** [linuxmint/Cinnamon#3128]
Hey,
I'd like to see the option to select in the context menu on the desktop whether to sort the desktop icons automatically on change, or not.

I can't implement this, but I wanted to let you guy know.
Let me know if you've any questions.

Thanks for the cinnamon experience!

**Comment by JosephMcc** [comment]
This really belongs here: https://github.com/linuxmint/nemo/issues
