### ISSUE TITLE
Hide Panel Icon / Applets

### ISSUE THREAD

**Issue by digitalattorney** [linuxmint/Cinnamon#3129]
I have about 12 panel icons + my Cinnamon notification icon + CPU graph + Date/Time.  The icons (i.e. shutter, volume, bluetooth, chrome (background running), etc.) take up quite a bit of valuable screen real estate. My open windows icons which i rely on to see what I have open, don't have much room as a result and get scrunched together after I open about 5 windows.

XFCE has a nice little feature I hope you will consider. It's a little arrow that sits in the panel and can be clicked to hide / unhide such icons. It really helps free up the panel space.

**Comment by feren** [comment]
@MichaelTunnell There also an applet called 'Drawer', but it's applet-only, and it has some glitches, will give that applet a try

**Comment by feren** [comment]
@MichaelTunnell It works, but it isn't draggable in Panel Edit Mode, that's why I think there needs to be an applet + tray supporting Show/Hide Applet...

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html
