### ISSUE TITLE
Add an option to change screenshot behavior on Cinnamon

### ISSUE THREAD

**Issue by alberthdev** [linuxmint/Cinnamon#3135]
Currently, pressing the screenshot key Print Screen (or PrtSc) causes a screenshot to be taken and saved in the $HOME/Pictures folder. It's a great feature, but on certain keyboards (such as the newer Thinkpads), the Print Screen key is located in a way that makes it easy to trigger. As a result, I have tons of screenshots in my Pictures folder that I end up having to clean out each week.

Would it be possible to do either of the following, ordered by preference:
- Add an option to configure the screenshot key to either:
  - take a screenshot and save it to a timestamped file (the current case)
  - pop up a window with a prompt to save the screenshot or copy it to the clipboard
  - only copy to clipboard, no prompt
  - do nothing (may need to show a warning dialog when the user selects this option, as well as some sort of notification indicating that screenshots are completely disabled)
- Add an option to change the key used for taking a screenshot

If there's a better way to implement this, I'd be open to any other suggestions. Please consider adding some sort of option!

**Comment by debunge** [comment]
My version of cinnamon is Cinnamon 2.2.16
and I'm having exactly the same problem as topic starter. 
No settings to change PrtSc key, nor do custom shortcuts work.
