### ISSUE TITLE
Cinnamon Cannot detect some non-stock gtk themes and icons

### ISSUE THREAD

**Issue by Ubuntumaster** [linuxmint/Cinnamon#3137]
I am using cinnamon 2.2 on Korora (Fedora) 20 and was really excited to get the update... until now. It seems that a bug in the newest update of Cinnamon makes the settings Themes>Other Settings>Icons or Themes>Other Settings>Themes not able to recognize installed theme files in the /usr/shared/.. or ~/.themes . After waiting ~15 minutes, it seems that it can detect a only a few of the files in these directories, but only after waiting a long time. One of the themes which no longer works is the Mediterranean Night theme series from gnome-look.org . If you replace the contents of one of the pre-installed icon sets with you own (ex: AgingGorilla,Gnome) it will work, but the same method fails to work with gtk3 window themes. The Current working setup that I now have uses nightfall, Faenza Cupertino, and Delorean Dark themes which for a reason I cannot explain are not effected by this bug. Thanks for listening, any help will be appreciated.

**Comment by JosephMcc** [comment]
Is this still an issue in Cinnamon 2.8?

**Comment by Vahan86** [comment]
@JosephMcc, there is no response from OP for 10 months. Can we close the issue?
