### ISSUE TITLE
Systray icons not working correctly for Java apps

### ISSUE THREAD

**Issue by jmgomezpoveda** [linuxmint/Cinnamon#3139]
Java applications using the standard system tray (http://docs.oracle.com/javase/tutorial/uiswing/misc/systemtray.html) are not working correctly in Cinnamon. Tested with Oracle's JDK 7 & 8, and with OpenJDK 7.

Issues observed:
- When setting trayIcon.setImageAutoSize(true), the icon is rendered in 1/4 of the space (i.e. in the top-left quadrant).
- The display, tooltips, or menus are really small AND behind the panel, so totally unusable.

This might be partially related to HiDPI. Using Cinnamon 2.2.1-20140414040006-trusty.

**Comment by pquiring** [comment]
Here is an updated sample of the problem:

This is cinnamon 2.6.13 (Mint 17.2)
![cinnamon](https://cloud.githubusercontent.com/assets/4077107/10101982/14a91b40-636a-11e5-80d2-754065e9b6b7.png)

And here is Ubuntu unity and what it should look like:
![unity](https://cloud.githubusercontent.com/assets/4077107/10101997/31b9f38a-636a-11e5-8347-62dd5d679b13.png)

You'll notice the tooltip and popup menu are under the panel with Cinnamon.
This is a Java application available at http://jfpasswords.sourceforge.net

Thanks.

**Comment by tux-86** [comment]
I have same problem with Vuze in Cinnamon 3.0.7.

**Comment by JosephMcc** [comment]
Trying to keep all the systray related issues together in one place: https://github.com/linuxmint/Cinnamon/issues/481
