### ISSUE TITLE
Plank and Docky render incorrectly

### ISSUE THREAD

**Issue by jonchampagne** [linuxmint/Cinnamon#3142]
Using mint 17 rc

To reproduce: install docky or plank and start it.

What Happened: Program renders incorrectly, but doesn't seem to be missing compositing. Boxes around running indicators, among other issues.

What should happen: nice pretty dock.

Happens every time

![screenshot from 2014-05-14 17 28 20](https://cloud.githubusercontent.com/assets/1485633/2977774/94188e7c-dbaf-11e3-9ee9-743fa036e3bd.png)

**Comment by vermaden** [comment]
Same problem on FreeBSD 10.3-RELEASE, fresh install.

![vermaden_2016-09-07_14-19-34](https://cloud.githubusercontent.com/assets/1453362/18311714/6651945c-74f5-11e6-9ad9-5ab0eb537985.png)

**Comment by vermaden** [comment]
For the record, I have two graphics cards in laptop:
 - NVIDIA QUADRO K2000M - with binary nvidia driver - there is no problem 
 - INTEL HD 4000 (i7-3630QM CPU) - with open driver - there is problem (screenshot)

Hope that helps.

Regards,
vermaden

**Comment by Vahan86** [comment]
@jonchampagne, is this still an issue for you with Cinnamon 3.4?

**Comment by Vahan86** [comment]
@JosephMcc, can we close this issue since there is no response from OP for 3 months?

**Comment by JosephMcc** [comment]
Our method for handling issues is going to change very soon. I appreciate the help you've been but wouldn't invest too much time in doing this until the dust settles a bit :)
