### ISSUE TITLE
[Feature Request] Panel Dodge Full Screen Windows

### ISSUE THREAD

**Issue by azariah001** [linuxmint/Cinnamon#3143]
This request relates to the Cinnamon Panel auto-hide settings. Currently the panels can be fixed (default behaviour) or auto-hidden. However (personally) it would be even better if they were always visible on the desktop with no windows open, hidden in full screen apps, and hidden when windowed apps approach the edge of the screen (for window tiling etc.)

**Comment by brub2** [comment]
This feature is now available on xfce 4.12 ! 
http://lmelinux.net/2015/03/01/xfce-4-12-released-with-a-plenty-of-new-features/

Another desktop with this feature is pantheon (elementary OS) with the super-wingpanel.

Maybe now it's the time to implement it in Cinnnamon (as I suggested in issue #1381). Actually, this is the only thing that prevents me to use cinnamon panel (I use cairo-dock with a panel theme instead).

**Comment by dalcde** [comment]
I think what we want is a mode in which the panel authides, but will show itself regardless if there is no window in the way.

**Comment by brub2** [comment]
In fact, there are many possible levels of "intrusion" for the panel (cairo-dock offers 6 choices!). A good compromise would be "keep below" or "hide if it overlaps the active window". I think "keep below" would be better. The panel would be completely hiden if a window is maximised, but we would see the right part of it if a window occupies the entire left part of the screen (for example).

**Comment by azariah001** [comment]
Good suggestions guys. :+1:

@brub2 "keep below" sounds like a good option for left and right edge snapping of windows, however for top and bottom snapping we would still need the "hide if it overlaps a window" so that we could still access the panel if needed.

Again this should be user settable so that we don't alienate people who don't want this option. Actually just realised that... if memory serves Unity has this option with it's launcher (I know Unity is quite far removed from the Gnome base (as is Cinnamon for that matter :P ) but there might be some handy snippets of code that with appropriate credit could aid in hurrying implementation along. :)

**Comment by brub2** [comment]
@azariah001 Yes, the intellihide option should be disabled by default. However, I don't think we have to worry about tiling and snapping since they work well with the actual autohide option. Said otherwise, if the user choose the intellihide option then (like the autohide option) he doesn't want to reserve space for the panel. If the panel is completely hiden (bottom tiling or maximised window, for example), then he has to place the mouse to the bottom edge to reveal the panel (with the delay chosen); same behaviour as the actual autohide feature. Of course, we can add more options if we want more control, but we should keep it simple.

Good idea to see if Unity code can be ported. I think ElementaryOS code can be used also if collaboration is easier there.

**Comment by azariah001** [comment]
Mmmm a path be emerging. 😀 This is good. 😃 And as with all cinnamon features start by offering the basic mode, the current options plus the intelihide with roughly the setup I suggested (there be some warts in my plan so with the suggested modifications), then down the track if users are asking for it. Offer an expandable section for intelihide that allows the more adventurous users to tweak the settings to there hearts content.
I think most would be happy with autohide for all snapped windows but who knows there might be some that want autohide only for full screen windows. 😋 I'm positing possibilities out my arse but... You get the idea we should plan for the future even if we leave actual implementation till later. So long as the code is kept simple enough that new rules can be dropped in as need this should be an excellent feature.
Now to convince some of the 'code monkeys' that this should be looked at if not actually prioritised to some level. 😛 considering I'm a code monkey myself I should stop procrastinating and do it myself but.... I'm not familiar with the codebase and I'm still a fulltime UNI student so I should work on assignments before I look at this. 😐
Sent using CloudMagic
On Thu, Mar 12, 2015 at 11:19 PM, brub2 <notifications@github.com> wrote:@azariah001 Yes, the intellihide option should be disabled by default. However, I don't think we have to worry about tiling and snapping since they work well with the actual autohide option. Said otherwise, if the user choose the intellihide option then (like the autohide option) he doesn't want to reserve space for the panel. If the panel is completely hiden (bottom tiling or maximised window, for example), then he has to place the mouse to the bottom edge to reveal the panel (with the delay chosen); same behaviour as the actual autohide feature. Of course, we can add more options if we want more control, but we should keep it simple.

Good idea to see if Unity code can be ported. I think ElementaryOS code can be used also if collaboration is easier there.

**Comment by lestcape** [comment]
That will create me a problem when i try to put the menu on "full screen", but i will do more job if is needed, i like the idea.
Thanks @dalcde

**Comment by dalcde** [comment]
It is just an option. You can choose between normal autohide and "intelligent" autohide.

**Comment by lestcape** [comment]
Yes, is just that:
https://camo.githubusercontent.com/1f45effe884670d73fa98ac3d1d02b8e05caa481/68747470733a2f2f7261772e6769746875622e636f6d2f77696b692f6c657374636170652f436f6e666967757261626c652d4d656e752f696d672f6c61796f7574732f4c757a2d48656c656e612e706e67
this will depend of panel size, and like the applet is not a windows, i need to know the panel state and resize the menu according to the state...

**Comment by dalcde** [comment]
The panel _should_ stay shown if it is a popup menu.

**Comment by azariah001** [comment]
Woah! Never seen a full screen mint menu right! Yes that definitely needs to be addressed although I believe this is the default with the current auto hide anyway. When the menu or any other applet opens out from the panel the panel remains visible.

**Comment by azariah001** [comment]
Nice job @dalcde :D I really want to test this but... I've got no idea how. Is there a wiki on how to compile cinnamon from source? Luckily I've got a new laptop with oodles of horsepower to put a VM on so that's easy enough. :)

**Comment by brub2** [comment]
Can't wait to see this in action. Is it possible to test this (on mint 17.1 for example) without compilation (dev PPA or something)?

**Comment by lestcape** [comment]
@dalcde also if it's the opposite panel of where the applet is? @azariah001 yes, but how i don't like the normal autohide, i don't make any patch for this, but if this will be include on cinnamon i will patch, because i will like then.

**Comment by dalcde** [comment]
@brub2 https://github.com/linuxmint/Cinnamon/wiki/Building
@letscape In this case I think you'll have to manually detect the panels. It think it will be sensible to force the opposite panel to hide in this case if it is in auto/intelligent hide mode.

**Comment by lestcape** [comment]
thanks, that is what i supposed.... thanks again.

**Comment by brub2** [comment]
@dalcde freshly compiled Cinnamon packages as suggested on the wiki but I don't see any new option for intelligent hide. Not 100% sure (first time), but all packages have been compiled and installled in the mentionned order. Do I have to manually edit a config file to activate the new option?

**Comment by dalcde** [comment]
The code is not yet merged. You will have to try out the code here: https://github.com/linuxmint/Cinnamon/pull/3986

Guess Github wasn't really helpful at describing what happened :)

**Comment by brub2** [comment]
Hum... I'm sorry but I don't know how to plug new code from the link you provided and I'm a bit affraid to get a mess. But if it's merged soon, I can wait.

**Comment by azariah001** [comment]
I'm going to test this in a VM as soon as I've finished configuring my new laptop. Just had a miracle happen. Windows 8.1 migrated (minus drivers) to my new laptop without blue screening. Did not see that one coming. Anyway!

I'll get a VM up and running and possibly do a screen capture to post to youtube so everyone can see the feature in all its glory. 😃

With the instructions provided for compiling cinnamon you have to modify the links provided to point at @dalcde 's fork of the project code in order to get his changes to the panel hide options. 😃 Not super complicated bus also not spelled out anywhere.

**Comment by brub2** [comment]
You mean I must redo all the 11 "git clone" lines with new github links (is it git://github.com/dalcde/linuxmint/... ?) and redo all the compilation+installation? Sorry again if I'm lost.

**Comment by azariah001** [comment]
Not necessarily all. I'll have to check but I suspect that there'll only be one of the components that you'll have to download and recompile.

**Comment by collinss** [comment]
@brub2 No, you should only have to redo cinnamon and muffin. You will have to switch to the correct branch however, or you might be able to modify your line to
```
git clone -b intellihide https://github.com/dalcde/muffin.git
```
for muffin and
```
git clone -b ihide https://github.com/dalcde/Cinnamon.git
```
for cinnamon, though I haven't tried it.

**Comment by azariah001** [comment]
Well there you go. 😃

**Comment by brub2** [comment]
Didn't have time to try until now... IT WORKS, so thanks everybody (special mention to collinss).

I have some observations/suggestions:

1) If a panel is hidden on a workspace (maximized window, for example), it is hidden on all workspaces (even empty ones). The panel should show itself (if possible) after a workspace change.

2) If a window is maximized (example) and then closed, the panel(s) should show itself. It does if the windows is unmaximized, but not if is closed (we have to place the mouse on the edge and then we see the panel).

3) Actually, the pane "hides if it overlaps any window". I really think that "keep below" would be better (as explained above).

4) Previous panel options are not available (number of panels, position, etc.).

Let me know if anything is updated and I will update muffin and Cinnamon to test.

**Comment by brub2** [comment]
I forgot the main point: nice job @dalcde !!

**Comment by lestcape** [comment]
Some one test what happend with this extension:
   http://cinnamon-spices.linuxmint.com/extensions/view/29

I think, cloud be problems... I also try to add global menu, so if the panel will hiden when windows will be maximized, well... I don't know how we can access to the menu then...

**Comment by dalcde** [comment]
1, 2) I can fix those
3) I'm not sure how that's going to work. Does the panel raise when you hover over the panel? Also how do you access the panel if a window is completely maximized? The current implementation seems to be the standard in all DEs.
4) It is probably due to a previous change in cinnamon master. You add/remove/move panels by right clicking the panel and select "modify panel"
@letscape I think in that case you probably don't want intellihide?

**Comment by lestcape** [comment]
@dalcde i think that is not a question of if i want intellihide (I want, what i don' t want is the global menu). I'm doing this for users that want to have global menu and i don't know if i can finished. I think that i will need control that option and i will request a question to the user. He/she need decide what he want to do, apparently is not possible at same time has the two options, or i will need create a new behavior for global menu on this case, i think...

**Comment by dalcde** [comment]
I think we agree here... My point was that if you want to use global menu, then you shouldn't use intellihide (just like you shouldn't use autohide - I'm not introducing new problens here :) It's just not sensible (or helpful) to enable both at the same time.

**Comment by lestcape** [comment]
@dalcde true...

**Comment by brub2** [comment]
@dalcde about my point#3 (keep below)...

With "keep below" we have to force the panel to show (entirely) if the mouse cursor goes to its edge. Said otherwise, the panel is not really hidden but we allow other windows to be placed above it. 

Here I show cairo-dock with the top panel (and bottom dock) partially hidden by some windows:
![keep below](https://cloud.githubusercontent.com/assets/2837468/6885976/12f7dbc0-d5fc-11e4-81cf-4885b80533c1.png)
 
Here I show what happens if the mouse cursor goes to the top edge:
![show panel](https://cloud.githubusercontent.com/assets/2837468/6885984/4fe8f6f4-d5fc-11e4-9f22-ffc003f91983.png)

Actually, cairo-dock is configured to re-put the panel below the windows after a few seconds if the user does nothing, even if the mouse cursor remains at the top edge on an empty area of the panel. Of course, the panel remains visible if we open the menu or other applet on it (or have the mouse pointer on an applet). It returns immediately below the windows after the execution of the applet (or if we just pass the mouse cursor on a applet and quit this screen edge after).

**Comment by brub2** [comment]
@dalcde just to answer more clearly (on my point#3 "keep below suggestion"):

Yes the panel should raise if you hover over the panel or the screen edge (with the mouse). If a window is maximized (or panel completely hidden for another reason), the panel should raise if you go the the screen edge (like it does right now). By "keep below" I don't mean "always below"... (just below instead hidden).

Maybe it's not possible in cinnamon to have a window "above" the panel (really don't know). In that case, a compromise could be to hide only if the *active* window overlaps the panel.

**Comment by brub2** [comment]
Just for information: the intellihide behavior on xfce 4.12 is "hide if it overlaps the active window".

@dalcde If I understand well, the code will be merged soon? Should I retest something?

**Comment by dalcde** [comment]
I have totally no idea when the code will be merged :)

**Comment by brub2** [comment]
Intellihide is available with cinnamon nightly PPA, so I retested it. The panel now hides only if the active window is above it, which is nice. However, there are at least 2 bugs:

1) If I click on an empty desktop area (so no windows is actually selected), the panel hides.
2) If I close all windows on a workspace, the panel hides. Also, we can go to an empty workspace to have the same issue.

@dalcde: I will be happy to test again if this can be fixed. It should be easier now with the PPA.

**Comment by dalcde** [comment]
Please open a new issue for new problems
