### ISSUE TITLE
No more than four keyboard layouts allowed

### ISSUE THREAD

**Issue by jepst** [linuxmint/Cinnamon#3146]
In Mint RC 17, a maximum of 4 keyboard layouts can be configured at the same time. In Ubuntu 14.04, however, the user can configure any number of keyboard layouts. Since Ubuntu 14.04 is the base of Mint 17, I think Mint should support arbitrary number of keyboard layouts as well. It is strange that this feature was not inherited from upstream. This is an important feature for translators, polyglots, travellers, etc.

Ubuntu 14.04 allows arbitrary number of keyboard layouts:
![ubunt](https://cloud.githubusercontent.com/assets/617498/2982158/23daf1c4-dc11-11e3-9bc8-154f12454991.png)

Mint RC 17 allows maximum 4 (notice the "plus" button is disabled):
![mint](https://cloud.githubusercontent.com/assets/617498/2982156/2127a0bc-dc11-11e3-816c-0cbc86510726.png)

**Comment by Vahan86** [comment]
I can confirm this for Cinnamon 3.0.7 as well.

**Comment by JosephMcc** [comment]
https://github.com/linuxmint/Cinnamon/issues/3212

**Comment by Moilleadoir** [comment]
Cinnamon 6.4.2
