### ISSUE TITLE
[Feature Request] limit opactiy when using mouse scroll on the title bar

### ISSUE THREAD

**Issue by highwindmx** [linuxmint/Cinnamon#3151]
It's quite a great feature to let it possible to change windows opacity by using mouse wheel on their titlebars, but down to 0%? 
Users may be confused when their windows "disappear" when using this feature. How about setting a limit here?

Thanks

**Comment by anandrkris** [comment]
@mtwebster - Perhaps we can have it on Title Bar > Context menu?
