### ISSUE TITLE
Feature - Applets Scale and Expo to have a menu customization

### ISSUE THREAD

**Issue by SamuelSousa** [linuxmint/Cinnamon#3153]
Good day.
I would like to first thank you for your effort in preparing the cinnamon.
I liked having the option to change the icon, just put text or both, in the applet Scale and Expo as we have the applet applications.
Sorry my bad english.
![exemple of customize applet menu applications](https://cloud.githubusercontent.com/assets/7545072/3004763/ad44ffa0-ddb9-11e3-9fac-e572523a3bee.png)

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html
