### ISSUE TITLE
 Display missed notifications on lockscreen

### ISSUE THREAD

**Issue by theSeppi** [linuxmint/Cinnamon#3155]
A (or probably the only) thing I like about Windows 8 is that it displays missed notifications (new email,...) on the lockscreen.

I wonder if this would be possible in Cinnamon too (I have nearly no knowlegde of the GNOMy stuff, currently using KDE)

What I imagine is a possibility to set which notifications are to be displayed on the lockscreen, e.g. new message from Pidgin or finished download by TransmissionBT. Would this be possible to add? Or is this too much work?

**Comment by anandrkris** [comment]
http://blog.martin-graesslin.com/blog/2015/02/global-shortcuts-and-the-lock-screen/
KDE seems to have nice approach to solve this. Looks like even KDE has removed widgets and solving it through allowing only **certain** keys to be passed through lock screen.

@mtwebster @clefebvre - For your awareness.

**Comment by JosephMcc** [comment]
Cinnamon 3.2 will have a new lock screen that will display that you have missed notifications.
