### ISSUE TITLE
Mice button programmation

### ISSUE THREAD

**Issue by KDB2** [linuxmint/Cinnamon#3157]
Hello,

Would you please consider adding the possibility to program mice buttons in Cinnamon? 
It could be really interesting to be able to affect actions/keyboard shortcuts these extra buttons. With Gnome 2 + Compiz, it was possible to use scale and expo with the mouse for example. Affecting 'ctrl' to a button can help zooming with only one hand for example. 

Thanks for the good work. :)

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html
