### ISSUE TITLE
[bug] Cinnamon freezes while playing with settings

### ISSUE THREAD

**Issue by kalsan** [linuxmint/Cinnamon#3163]
When changing settings, for example Applets or Keyboard Shortcuts, the entire DE freezes randomly. Sometimes it works, sometimes not. I see no pattern in the freezes, but it happens only when playing with settings.
Behaviour: The mouse still moves. However, it does not react to any clicks. Buttons don't light up on mouseover. NumLock and CapsLock are still responding. Any shortcuts / keyboard strikes are ignored. The volume button usually turn orange (hardware, not on the screen) when I press it. That does not happen either on the freeze, so it's not just a display problem.
Running Arch Linux with Cinnamon 2.2.8

**Comment by ManIVIctorious** [comment]
Does this still happen with cinnnamon 3.0?
Please also see #4072

**Comment by JosephMcc** [comment]
It would be nice to consolidate as much of this info as possible in https://github.com/linuxmint/Cinnamon/issues/4072 instead of having it spread over 30 different bug reports.
