### ISSUE TITLE
Window goes all screen instead on stopping on the edge of the taskbar

### ISSUE THREAD

**Issue by zaclimon** [linuxmint/Cinnamon#3170]
When I use a program that is generally used for the majority of the screen (a web browser) the bottom of the window goes into the end of the screen instead of finishing on the taskbar. The results of it are that some functionnalities can't be used.

For example, when downloading something on Chrome, the download bar isn't accessible because it gets hidden with the taskbar.

![capture du 2014-05-19 12 21 15](https://cloud.githubusercontent.com/assets/1891861/3016781/f2e548ee-df71-11e3-9b60-478eb69448da.png)

**Comment by JosephMcc** [comment]
This seems to happen when you switch between themes that use different default panel sizes.

**Comment by Vahan86** [comment]
@zaclimon, is this still an issue in Cinnamon 3.0?

**Comment by JosephMcc** [comment]
Actually think we can close this. Testing on git master struts seem to get properly updated now when changing to themes with different panel sizes.
