### ISSUE TITLE
corrupted fonts

### ISSUE THREAD

**Issue by sebastian-de** [linuxmint/Cinnamon#3176]
I'm currently testing Linux Mint 17 RC and I get font rendering errors:
![font-error-01](https://cloud.githubusercontent.com/assets/7430495/3027213/9dff587e-e020-11e3-88d1-4e244eabbd17.jpg)
![font-error-02](https://cloud.githubusercontent.com/assets/7430495/3027217/a5cb774a-e020-11e3-90fb-15f3e1962c60.jpg)
![font-error-04](https://cloud.githubusercontent.com/assets/7430495/3027220/a80fe194-e020-11e3-9f71-1eddd9050a71.jpg)
The corrupted fonts only show up in cinnamon launchers/tooltips. Other applications aren't affected
![font-error-05](https://cloud.githubusercontent.com/assets/7430495/3027251/0c4f2f70-e021-11e3-933a-eada86b365d3.jpg)

I played around with different fonts and disabled hinting, but the rendering errors remain.
I have a Radeon Xpress 1250 and use the open source radeon driver.

**Comment by thepartisan** [comment]
I see the exact same issue on my machine, which also sports the Xpress 1250

**Comment by collinss** [comment]
I recently installed Mint on my brother-in-law's old laptop, and had this problem after opening a couple of applications. I just upgraded his memory from 1/2 gb to 2 1/4 gb and I haven't seen it since.

**Comment by Vahan86** [comment]
@sebastian-de, is this issue still relevant in Cinnamon 3.0.x?

**Comment by Vahan86** [comment]
@JosephMcc, can we close this issue?
