### ISSUE TITLE
Debian: eliminate Lintian tags

### ISSUE THREAD

**Issue by darealshinji** [linuxmint/Cinnamon#3178]
I realised that many Debian packages from Mint are not packaged as "clean" as they could. Very often it's something easy to fix.

This patch for example: https://gist.github.com/darealshinji/5a8c259b001bc042dddd

It should actually override this:
cinnamon: binary-or-shlib-defines-rpath usr/bin/cinnamon /usr/lib/gnome-bluetooth:/usr/lib/cinnamon
cinnamon: binary-or-shlib-defines-rpath usr/lib/cinnamon/libcinnamon.so /usr/lib/gnome-bluetooth
(in the override file it should be 'cinnamon binary:' instead of 'cinnamon:')

It should also fix:
description-starts-with-package-name
extended-description-line-too-long
embedded-javascript-library usr/lib/cinnamon-settings/data/spices/jquery.js
(jquery.js will be replaced with a symbolic link)

I could try to create such fixes for other packages too if you want.
As an example, I reworked the flashplugin source package: https://github.com/darealshinji/mint-flashplugin

**Comment by leigh123linux** [comment]
If you have improvements submit them as pull requests.
