### ISSUE TITLE
  Add "Wipe" and "Wipe available diskspace" to Nemo

### ISSUE THREAD

**Issue by freemangilgamesh** [linuxmint/Cinnamon#3183]
We all know that most people come to Linux mainly for security reasons. Wiping (shredding) files permanently from disk is capital for those relying on security to do their tasks. I suggest that the Linux Mint team add "Wipe" and "Wipe available diskspace" options to nemo like on Tails OS.

<a href="http://www.imagebam.com/image/097be5328224287" target="_blank"><img src="http://thumbnails112.imagebam.com/32823/097be5328224287.jpg" alt="imagebam.com"></a> <a href="http://www.imagebam.com/image/f0eafc328224290" target="_blank"><img src="http://thumbnails111.imagebam.com/32823/f0eafc328224290.jpg" alt="imagebam.com"></a>

**Comment by JosephMcc** [comment]
Not a cinnamon issue.
