### ISSUE TITLE
Desktop magnifier keyboard shortcut cannot be configured

### ISSUE THREAD

**Issue by jepst** [linuxmint/Cinnamon#3193]
Desktop magnification is controlled with three keyboard shortcuts: enable/disable, zoom in, and zoom out. This screenshot shows their current configuration:

![screenshot-window-2014-05-26-114123](https://cloud.githubusercontent.com/assets/617498/3082020/b2a2adea-e4ca-11e3-83f3-bf9decfeaeec.png)

However, the enable/disable shortcut cannot be configured. See this screenshot, showing that Zoom in/Zoom out are configurable, but not enable/disable.

![screenshot-window-2014-05-26-113830](https://cloud.githubusercontent.com/assets/617498/3081995/50fcfd70-e4ca-11e3-9cf9-5753113ecf2b.png)

**Comment by Basaltq** [comment]
But why was it removed? I don't understand the logic. It's an useful feature to toggle magnification with a quick key for special situations and I would actually need it.

**Comment by mtwebster** [comment]
There's no need to turn it on/off at the time of need any more.  It can be left 'On' but will *really* only activate once the magnification is set to > 1.0.  It's more convenient and useful now than it was.  Sorry if it's poorly explained here.  We changed the underlying behavior, removing the need for a shortcut key to turn it on/off - adjusting the magnification with those shortcuts now turns it on/off as necessary.

**Comment by systemdarena** [comment]
@mtwebster I disagree, it would be more convenient to support both. Why not leave it configurable? I don't want to have to do the "Zoom In" shortcut 5 times to go to a reasonable level of zoom then do the "Zoom Out" shortcut 5 times to shut it off. It's more convenient to have 1 keyboard shortcut to toggle it on/off at whatever the last set magnification was. Supporting the "toggle" shortcut would also still allow it to work just like you describe.
