### ISSUE TITLE
Don't displayed icon in the system tray

### ISSUE THREAD

**Issue by Morfeusz888** [linuxmint/Cinnamon#3195]
Some icons when you start a new application (eg Shutter) do not display their icons in the system tray. Instead, the program icon appears blank. To display appeared, restart Cinnamon environment. Unfortunately this temp solution is very cumbersome.

Operating System: Linux Mint 17 RC

**Comment by maxkoryukov** [comment]
nothing changes? I have the same bug: I don't have any applications in the system tray..

**Comment by maxkoryukov** [comment]
try to add the **System Tray** applet to the panel
in my case it had disappeared mystically after update..

**Comment by JosephMcc** [comment]
Please post systray icon issues in https://github.com/linuxmint/Cinnamon/issues/481
