### ISSUE TITLE
cinnamon-2.2.13 doesn't build against gnome-bluetooth-3.12

### ISSUE THREAD

**Issue by pacho2** [linuxmint/Cinnamon#3197]
I get:
/bin/sh ../libtool  --tag=CC   --mode=link x86_64-pc-linux-gnu-gcc  -O2 -pipe -march=native -Wall -Wmissing-prototypes -export-dynamic -Wl,-O1 -Wl,--as-needed -Wl,--hash-style=gnu -o run-js-test run_js_test-run-js-test.o libcinnamon.la -lm -ldbus-glib-1 -ldbus-1 -lxml2 -lmuffin -lcinnamon-desktop -lgtk-3 -lclutter-1.0 -lcjs -lmozjs185 -lplds4 -lplc4 -lnspr4 -lcinnamon-menu-3 -lgio-2.0 -lgstbase-1.0 -lgstreamer-1.0 -lgconf-2 -lgdk-3 -lsoup-2.4 -lGL -lclutter-1.0 -lcogl-path -latk-1.0 -lcogl-pango -lcogl -lgmodule-2.0 -pthread -lXrandr -ljson-glib-1.0 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -lgdk_pixbuf-2.0 -lcairo-gobject -lcairo -lX11 -lXext -lXdamage -lXcomposite -lXi -lstartup-notification-1 -lgirepository-1.0 -lcanberra -lpolkit-agent-1 -lpolkit-gobject-1 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lXfixes  -lnm-glib -lnm-util -ldbus-glib-1 -ldbus-1 -lgobject-2.0 -lgnome-keyring -lglib-2.0   libst-1.0.la libtray.la libgvc.la  
libtool: link: x86_64-pc-linux-gnu-gcc -O2 -pipe -march=native -Wall -Wmissing-prototypes -Wl,-O1 -Wl,--hash-style=gnu -o .libs/run-js-test run_js_test-run-js-test.o -pthread -Wl,--export-dynamic  -Wl,--as-needed ./.libs/libcinnamon.so -lmuffin -lcjs -lmozjs185 -lplds4 -lplc4 -lnspr4 -lcinnamon-menu-3 -lgstbase-1.0 -lgstreamer-1.0 -lgconf-2 -lsoup-2.4 -lGL -lstartup-notification-1 -lgirepository-1.0 -lcanberra -lpolkit-agent-1 -lpolkit-gobject-1 -lnm-glib -lnm-util -ldbus-glib-1 -ldbus-1 -lgnome-keyring ./.libs/libst-1.0.a -lm -lclutter-1.0 -lcogl-path -lcogl-pango -lcogl -lgmodule-2.0 -lXrandr -ljson-glib-1.0 -lXext -lXdamage -lXfixes -lXcomposite -lXi -lcroco-0.6 -lxml2 -lcinnamon-desktop -lX11 ./.libs/libtray.a -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 ./.libs/libgvc.a -lpulse-mainloop-glib -lpulse -lgobject-2.0 -lglib-2.0 -pthread -Wl,-rpath -Wl,/usr/lib64/cinnamon
libtool: link: x86_64-pc-linux-gnu-gcc -O2 -pipe -march=native -Wall -Wmissing-prototypes -Wl,-O1 -Wl,--hash-style=gnu -o .libs/cinnamon-real cinnamon_real-main.o -pthread  -Wl,--as-needed ./.libs/libcinnamon.so -lmuffin -lcjs -lmozjs185 -lplds4 -lplc4 -lnspr4 -lcinnamon-menu-3 -lgstbase-1.0 -lgstreamer-1.0 -lgconf-2 -lsoup-2.4 -lGL -lstartup-notification-1 -lgirepository-1.0 -lcanberra -lpolkit-agent-1 -lpolkit-gobject-1 -lnm-glib -lnm-util -ldbus-glib-1 -ldbus-1 -lgnome-keyring ./.libs/libst-1.0.a -lm -lclutter-1.0 -lcogl-path -lcogl-pango -lcogl -lgmodule-2.0 -lXrandr -ljson-glib-1.0 -lXext -lXdamage -lXfixes -lXcomposite -lXi -lcroco-0.6 -lxml2 -lcinnamon-desktop -lX11 ./.libs/libtray.a -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 ./.libs/libgvc.a -lpulse-mainloop-glib -lpulse -lgobject-2.0 -lglib-2.0 -pthread -Wl,-rpath -Wl,/usr/lib64/cinnamon
./.libs/libcinnamon.so: undefined reference to `bluetooth_applet_get_type'
collect2: error: ld returned 1 exit status
make[3]: *** [run-js-test] Error 1
make[3]: *** Waiting for unfinished jobs....
./.libs/libcinnamon.so: undefined reference to `bluetooth_applet_get_type'
collect2: error: ld returned 1 exit status
make[3]: *** [cinnamon-real] Error 1
g-ir-scanner: compile: cc -Wno-deprecated-declarations -pthread -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -O2 -pipe -march=native -Wall -Wmissing-prototypes -I/usr/include/gio-unix-2.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -c -o /var/tmp/portage/gnome-extra/cinnamon-2.2.13/work/Cinnamon-2.2.13/src/tmp-introspectgWkcPf/Gvc-1.0.o /var/tmp/portage/gnome-extra/cinnamon-2.2.13/work/Cinnamon-2.2.13/src/tmp-introspectgWkcPf/Gvc-1.0.c
g-ir-scanner: link: /bin/sh ../libtool --mode=link --tag=CC cc -o /var/tmp/portage/gnome-extra/cinnamon-2.2.13/work/Cinnamon-2.2.13/src/tmp-introspectgWkcPf/Gvc-1.0 -export-dynamic -O2 -pipe -march=native -Wall -Wmissing-prototypes -Wl,-O1 -Wl,--as-needed -Wl,--hash-style=gnu /var/tmp/portage/gnome-extra/cinnamon-2.2.13/work/Cinnamon-2.2.13/src/tmp-introspectgWkcPf/Gvc-1.0.o -L. libgvc.la -lgio-2.0 -lgobject-2.0 -Wl,--export-dynamic -lgmodule-2.0 -pthread -lglib-2.0
libtool: link: cc -o /var/tmp/portage/gnome-extra/cinnamon-2.2.13/work/Cinnamon-2.2.13/src/tmp-introspectgWkcPf/Gvc-1.0 -O2 -pipe -march=native -Wall -Wmissing-prototypes -Wl,-O1 -Wl,--hash-style=gnu /var/tmp/portage/gnome-extra/cinnamon-2.2.13/work/Cinnamon-2.2.13/src/tmp-introspectgWkcPf/Gvc-1.0.o -Wl,--export-dynamic -pthread -Wl,--export-dynamic  -Wl,--as-needed -L. ./.libs/libgvc.a -lpulse-mainloop-glib -lpulse -lgio-2.0 -lgobject-2.0 -lgmodule-2.0 -lglib-2.0 -pthread
g-ir-scanner: compile: cc -Wno-deprecated-declarations -pthread -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -O2 -pipe -march=native -Wall -Wmissing-prototypes -I/usr/include/clutter-1.0 -I/usr/include/cogl -I/usr/include/json-glib-1.0 -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0 -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libdrm -I/usr/include/libpng16 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -c -o /var/tmp/portage/gnome-extra/cinnamon-2.2.13/work/Cinnamon-2.2.13/src/tmp-introspectS52FSF/St-1.0.o /var/tmp/portage/gnome-extra/cinnamon-2.2.13/work/Cinnamon-2.2.13/src/tmp-introspectS52FSF/St-1.0.c
g-ir-scanner: link: /bin/sh ../libtool --mode=link --tag=CC cc -o /var/tmp/portage/gnome-extra/cinnamon-2.2.13/work/Cinnamon-2.2.13/src/tmp-introspectS52FSF/St-1.0 -export-dynamic -O2 -pipe -march=native -Wall -Wmissing-prototypes -Wl,-O1 -Wl,--as-needed -Wl,--hash-style=gnu /var/tmp/portage/gnome-extra/cinnamon-2.2.13/work/Cinnamon-2.2.13/src/tmp-introspectS52FSF/St-1.0.o -L. libst-1.0.la -lgio-2.0 -lgobject-2.0 -Wl,--export-dynamic -lgmodule-2.0 -pthread -lglib-2.0
libtool: link: cc -o /var/tmp/portage/gnome-extra/cinnamon-2.2.13/work/Cinnamon-2.2.13/src/tmp-introspectS52FSF/St-1.0 -O2 -pipe -march=native -Wall -Wmissing-prototypes -Wl,-O1 -Wl,--hash-style=gnu /var/tmp/portage/gnome-extra/cinnamon-2.2.13/work/Cinnamon-2.2.13/src/tmp-introspectS52FSF/St-1.0.o -Wl,--export-dynamic -pthread -Wl,--export-dynamic  -Wl,--as-needed -L. ./.libs/libst-1.0.a -lm -lclutter-1.0 -lcogl-path -lcogl-pango -lcogl -lXrandr -ljson-glib-1.0 -lXext -lXdamage -lXfixes -lXcomposite -lXi -lcroco-0.6 -lxml2 -lcinnamon-desktop -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lX11 -lgio-2.0 -lgobject-2.0 -lgmodule-2.0 -lglib-2.0 -pthread
make[3]: Leaving directory `/var/tmp/portage/gnome-extra/cinnamon-2.2.13/work/Cinnamon-2.2.13/src'
make[2]: *** [all] Error 2
make[2]: Leaving directory `/var/tmp/portage/gnome-extra/cinnamon-2.2.13/work/Cinnamon-2.2.13/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/var/tmp/portage/gnome-extra/cinnamon-2.2.13/work/Cinnamon-2.2.13'
make: *** [all] Error 2

I have seen Fedora and Mandriva are simply dropping bluetooth support from cinnamon :/

**Comment by ManIVIctorious** [comment]
Is this still an issue in cinnamon 3.0?
