### ISSUE TITLE
Add "toggle Always on Top" titlebar button

### ISSUE THREAD

**Issue by geoffm** [linuxmint/Cinnamon#3214]
I appreciate the new "sticky" and "shade" titlebar buttons, now all that is missing is a "toggle Always On Top" button.

**Comment by ManIVIctorious** [comment]
This seems to be implemented in cinnamon 3.0
@JosephMcc I think this can be closed

**Comment by JosephMcc** [comment]
I'm not so sure about that. The UI only supports stick, shade, menu, min, max, close. As far as I know that is all the metacity format exposes.

That being said I'm not sure this is really even worth implementing. Most themes seem to only support min, max, and close nowadays and client side decorated apps don't support those other buttons at all.

**Comment by p0lm** [comment]
Actually, metacity does support this (above, unabove).

**Comment by xenopeek** [comment]
Metacity indeed supports it. On Linux Mint 18.3 Cinnamon I tested this with Crux theme.

Just needs adding `("above", _("Above"))` to the button array in cs_windows.py, here: https://github.com/linuxmint/Cinnamon/blob/5c9848a48da3387825f627117ad58521474e0b2e/files/usr/share/cinnamon/cinnamon-settings/modules/cs_windows.py#L197

**Comment by JosephMcc** [comment]
Closing this. We are actually looking at removing metacity theme support. There are no plans to support more buttons. Thanks for the input.
