### ISSUE TITLE
Default theme isn't good for html forms/window controls

### ISSUE THREAD

**Issue by LiamDawe** [linuxmint/Cinnamon#3216]
Has anyone else noticed how bad the default theme is for html forms?

Here are some comparison shots, this is the default:
http://i.imgur.com/hXDIAsV.png

Here's it in high contrast, notice I can see the check in the box and what's selected in the right section:
http://i.imgur.com/Xf7RoYn.png

It's also bad when tabbing on html forms on websites, you can never tell where the tab currently is as there's practically no kind of feedback/outline on things like buttons, dropdown menus etc.

More testing is needed on the theme's I feel. Is this possible to be fixed soon or should I look to a new window control theme?

**Comment by OlsonB** [comment]
I have the exact same issue here with any of the Mint-X themes - eg http://i.imgur.com/pz5SfO6.jpg

If I change the window controls to say Adwaita, or as OP says the high contrast theme, they are revealed as expected.

**Comment by LiamDawe** [comment]
Is this going to be looked into for the current or the new theme being made for Linux mint? It's making many things a pain.

**Comment by JosephMcc** [comment]
I still don't have anything to test this with. Once the Mint18 RC's are available please test if you can.

I'm closing this since it actually has nothing to do with Cinnamon.

**Comment by LiamDawe** [comment]
Okay, so where am I supposed to report issues with the main theme? You could at least point me there.

**Comment by OlsonB** [comment]
If having something to test this with is the main problem you can get game called "The Way of Life" which is free, on Steam, and will produce the Unity launcher when it's run.

**Comment by JosephMcc** [comment]
@LiamDawe Sorry, should have given you a link. Here you go: https://github.com/linuxmint/mint-themes

@OlsonB Cool, thanks
