### ISSUE TITLE
GUI option to remove window decorations?

### ISSUE THREAD

**Issue by wrouesnel** [linuxmint/Cinnamon#3217]
With settings being added for window transparency, one big oversight is the ability to tell Cinnamon to strip all window decorations from an application.

There are various reasons to want to do this - a big one being quickly prototyping things which are supposed to run at full screen resolution (i.e. a kiosk style webpage for something) or setting up a dashboard-type view for special uses.

It would be a perfect complement to the current snap/tiling functionality, and control could be added to the window bar to restore decorations afterwards.

**Comment by thorsummoner** [comment]
I would like window decorators to be user-toggleable in the alt+space menu so that terrible wine games can be forced to behave like regular windows

**Comment by OpenNingia** [comment]
I also would like an option to toggle title bar for applications ( like Telegram Desktop ) that uses client side decorations.

**Comment by PoldoSbaffini** [comment]
A number of programs (e.g., Google Chrome) are able to tell the Cinnamon window manager not to draw window frames. As a stop gap measure, it should be possible to write a wrapper that runs an application inside its not-decorated window., e.g.,

    % wrapper mupdf my_16:9_slides.pdf

 It is even possible that such program already exists... are you aware of such a program?

**Comment by thorsummoner** [comment]
I've seen retroactive programs do it, like `wmctl`, and I've seen it built
in to the window manager, its not hard to do, it's rather not convenient to
do casually.

**Comment by JosephMcc** [comment]
This isn't the type of thing we are really interested in having in Cinnamon by default. Things like menubars in titlebars, global menus, removable window decorations and the like are outside of the scope of what we plan on implementing at this point.

**Comment by lestcape** [comment]
You can if you path muffin with a similar patch of what it's doing for mutter on arch:
https://aur.archlinux.org/packages/mutter-hide-legacy-decorations/

**Comment by rscircus** [comment]
Bumped into this. For anyone searching for a solution, here is what I found:

(1) There is an applet, that might help: https://cinnamon-spices.linuxmint.com/extensions/view/29
(2) https://unix.stackexchange.com/questions/52565/how-to-disable-window-decorations-in-cinnamon

Interestingly, *Cinnamon Maximum* is the third-most popular Cinnamon extension.
