### ISSUE TITLE
[bug]ibus-statusbar(property-panel) make system panel malfunction

### ISSUE THREAD

**Issue by highwindmx** [linuxmint/Cinnamon#3218]
LinuxMint17
when I use ibus to input chinese( no matter whether I use ibus-sunpinyin or ibus-rime) the system panel will be loss of function when I enable ibus-statusbar(which means set property-panel to "always" or "Hide automatically"(when it is not hiden)).

And loss of function means: 
1.all icons on panel are un-clickable( but win-key can evoke menu);
2.right click on panel show the right click menu of desktop;
3.left click on panel sometime seems clicking the buttons on this ibus-statusbar(which looks like the statusbar expand and mask the panel).

![1](https://cloud.githubusercontent.com/assets/6413481/3142206/7b8bfe84-e9b0-11e3-9f52-b0e9d782b27b.png)

**Comment by Vahan86** [comment]
@highwindmx, is this still an issue for you in Cinnamon 3.0.x?

**Comment by Vahan86** [comment]
@JosephMcc, can we close this issue?
