### ISSUE TITLE
Locking the screen takes very long when using multi displays

### ISSUE THREAD

**Issue by LiraNuna** [linuxmint/Cinnamon#3222]
When using multiple displays and locking the screen (default Ctrl+Alt+L), the desktop becomes halted for as long as 8 seconds until showing the lock screen.
When turning off one of the screens (using Display preferences) and locking the screen again in the same session, locking takes as little as half a second.
Restoring the multi display mode will reproduce this error.

**Comment by escobera** [comment]
I'm still having this issue on mint 18. Any news on this front?

**Comment by JosephMcc** [comment]
The lock screen is completely rewritten for Cinnamon 3.2. I guess we will find out if this is fixed :)

**Comment by LiraNuna** [comment]
Locking is instant now for me! I'm closing this issue!
