### ISSUE TITLE
Pidgin status icon.

### ISSUE THREAD

**Issue by SkyMaverick** [linuxmint/Cinnamon#3223]
Pidgin status icon is not showing even if in the settings it’s set to always show. Workaround: open Settings - set "never show" and "show always" again.
Using: Mint 17 cinnamon (32bit).

**Comment by luisfpg** [comment]
To me the Google Chrome icon always disappears too. I've got the hangouts extension, and curiously, I've never seen the hangouts icon missing, only the main chrome icon.
The shutter icon also disappears sometimes.
The workaround I use is to go to panel settings and change the panel size. But is annoying to do it every day.

**Comment by luisfpg** [comment]
To me Google Chrome's icon is always missing. Curiously I have the hangouts extension which also shows an icon, but it is never missing - only main chrome icon.
I've also seen this with the shutter icon.
I'm using Arch 64 bit, with cinnamon 2.4.6.
I don't think it is a driver problem, as changing the panel size always fixes the issue. Maybe is a run condition, or something like that.

**Comment by ntarocco** [comment]
I am on Mint 17.1 64bit Cinnamon 2.4.6 and I have the same problem.

**Comment by lduboeuf** [comment]
+1

**Comment by masac** [comment]
+1

**Comment by dmadiedo** [comment]
I don't understand why this is closed. Item persists in Linux Mint 17.1

**Comment by calestyo** [comment]
It does seem to work since 2.6.7 on Debian sid.

**Comment by aPollO2k** [comment]
Pidgin and Thunderbird seems to work. But KeePass2 (with mono-complete) have the same issue for me on Linux Mint 17.2 and Cinnamon 2.6.13

**Comment by brouillon** [comment]
+1 This bug is still here in Linux Mint 17.2 64bits  - Cinnamon 2.6.13.
First launch == blank space restart pidgin icon is displayed.

Same for Shutter's tray icon. and some times bad scaling for update manager but it's another issue.

Please reoppen this.

**Comment by kmdm** [comment]
This bug can also be resolved (probably obviously given the above workaround) in looking glass by inspecting the height (16 in my case) and setting it to 20 then back to 16.

E.g:-

 r(0).set_height(20); 
r(0).set_height(16);

Interestingly those have to be two separate commands "r(0).set_height(20); r(0).set_height(16);" on one line does not work to show the icon (but will work once the icon has been shown...)

**Comment by brouillon** [comment]
@kmdm : your comment is so useful, I found a fix, you can modify function resize_icon in '/usr/share/cinnamon/applets/systray@cinnamon.org/applet.js' with this one :
```
resize_icon: function(icon, role) {
        if (this._scaleMode) {
            let disp_size = this._panelHeight * ICON_SCALE_FACTOR;
            let size;
            if (icon.get_height() != disp_size) {
                size = disp_size;
            }
            else {
                // Force a resize with a slightly different size
                size = disp_size - 1;
            }

            // Don't try to scale buggy icons, give them predefined sizes
            // This, in the case of pidgin, fixes the icon being cropped in the systray
            if (["pidgin", "thunderbird", "shutter"].indexOf(role) != -1) {
                if (disp_size < 22) {
                    size = 16;
                }
                else if (disp_size < 32) {
                    size = 22;
                }
                else if (disp_size < 48) {
                    size = 32;
                }
                else {
                    size = 48;
                }
            }
			let timerId = 0;
            let i = 0;
            Mainloop.timeout_add(500, Lang.bind(this, function() { 
                icon.set_size(size, size);
                global.log("Resized " + role + " (" + icon.get_width() + "x" + icon.get_height() + "px)");
                i++;
                if (i == 2) {
                    Mainloop.source_remove(timerId);
                }
            }));
            //icon.set_size(size, size);
            //global.log("Resized " + role + " (" + icon.get_width() + "x" + icon.get_height() + "px)");
        }
        else {
            // Force buggy icon size when not in scale mode
            if (["pidgin", "thunderbird", "shutter"].indexOf(role) != -1) {
                let timerId = 0;
                let i = 0;
                timerId = Mainloop.timeout_add(500, Lang.bind(this, function() { 
                    icon.set_size(16, 16);
                    global.log("Resized " + role + " (" + icon.get_width() + "x" + icon.get_height() + "px)");
                    i++;
                    if (i == 2) {
                        Mainloop.source_remove(timerId);
                    }
                }));
                //icon.set_size(16, 16);
                //global.log("Resized " + role + " (" + icon.get_width() + "x" + icon.get_height() + "px)");
            }
        }
    },
```
I added 'shutter' to the array of bugged icons and put a delay of 500ms before applying resizing.

**Comment by kenden** [comment]
@brouillon Cool! Would you mind submitting a pull request for this?

**Comment by pepinoogorino** [comment]
@brouillon @kenden
This is not the correct solution. Icon pidgin has been fixed, but... mint update icon has been broken  (empty area) :(

**Comment by brouillon** [comment]
In my case pidgin icon is not fixed with Linux Mint 17.2 64bits - Cinnamon 2.6.13, first launch == blank space.
It's ok for you ?

**Comment by aPollO2k** [comment]
@brouillon @kenden dirty workaround but no fix. but looks like it worked for me. hope for an clean bugfix soon.

**Comment by kenden** [comment]
@clefebvre This bug needs to be reopened to track its status.

**Comment by Muscule** [comment]
Problem still exists.

**Comment by sergioad** [comment]
yes, and not only with Pidgin, for Steam too

**Comment by clefebvre** [comment]
https://github.com/linuxmint/Cinnamon/commit/f2134a4225f82a82ba57bd370b2a51312b731d9a should fix most cases: pidgin, shutter, filezilla, thunderbird, dropbox..etc... with a few limitations (filezilla/shutter/dropbox won't scale).

Steam is now handled via indicator (that's supported in Cinamon 2.8).

**Comment by geckolinux** [comment]
I had previously reported a system tray bug and then retracted it, thinking it was just due to an old Cinnamon theme. But now it appears that the bug does indeed exist. Just to be sure, I enabled the default "cinnamon" theme, and the bug is still occurring.

First, the Pidgin icon appears at the wrong size:
![screenshot from 2015-11-18 15-07-07](https://cloud.githubusercontent.com/assets/2692138/11253146/cf5aa9e6-8e07-11e5-891e-4cd0759bab2c.png)

Then after receiving a message it is supposed to flash the system tray icon. Instead, it disappears:
![screenshot from 2015-11-18 15-11-35](https://cloud.githubusercontent.com/assets/2692138/11253152/d698a97e-8e07-11e5-98da-f4cd07a68567.png)

**Comment by calestyo** [comment]
I think this problem kinda re-appeared... well after starting pidgin it takes like 15s until the systray icon appears (even though pidgin itself is already there and running).

Cinnamon 3.0.7,...everything Debian sid.

**Comment by zquestz** [comment]
I was able to fix this by editing `/usr/share/pixmaps/pidgin/tray/hicolor/index.theme` and replacing it with:

```
[Icon Theme]
Name=Pidgin
Comment=Icon theme for Pidgin tray icons
Directories=scalable/actions,scalable/status

[scalable/actions]
MinSize=1
Size=128
MaxSize=256
Context=Actions
Type=Scalable

[scalable/status]
MinSize=1
Size=128
MaxSize=256
Context=Status
Type=Scalable
```
