### ISSUE TITLE
black text in desktop icons when changing controls

### ISSUE THREAD

**Issue by Broly1** [linuxmint/Cinnamon#3226]
![screenshot from 2014-06-03 12 31 23](https://cloud.githubusercontent.com/assets/6778968/3163148/9c0111c6-eb3c-11e3-869b-e412b3aa2ad2.png)
i Have installed 3 different themes in Linux Mint 17 Cinnamon 32bit and 64bit all of them gives me the same behavior when i go to themes other settings and change the controls to any other theme besides mint x the text in icons on desktop becomes black invisible with dark wallpaper even if i change it to  Adwaita see screen shot below:
 https://plus.google.com/104912934147790631255/posts/MZLZ9myzwWh

https://plus.google.com/104912934147790631255/posts/R6jy2VDMZ96

**Comment by sergioad** [comment]
Hello I have a similar problem here with the Paper GTK theme and Cinnamon 2.4

here is the code what I use

/***********************
 * Nemo desktop icons *
***********************/

.nemo-desktop.nemo-canvas-item {
color: #FFFFFF;
text-shadow: 1px 1px alpha(#000, 0.2);
}

.nemo-desktop.nemo-canvas-item:active {
color: #FFFFFF;
text-shadow: 1px 1px alpha(#000, 0.2);
}

.nemo-desktop.nemo-canvas-item:selected {
background-color: #9FB0B9;/* Selection color */
background-image: none;
color: #FFFFFF;
text-shadow: 1px 1px alpha(#000, 0.2);
}

.nemo-desktop.nemo-canvas-item:backdrop {
color: #FFFFFF;
text-shadow: 1px 1px alpha(#000, 0.2);
}

.nemo-desktop.nemo-canvas-item:selected:backdrop {
color: @backdrop_selected_foreground;
}

.nemo-desktop.nemo-canvas-item:active,
.nemo-desktop.nemo-canvas-item:prelight,
.nemo-desktop.nemo-canvas-item:selected {
    text-shadow: none;
}

The text is working as it should when the desktop is focused but when I open sme window the text becomes back again, it returns to white when I focus the desktop so what I need to do?

**Comment by JosephMcc** [comment]
@sergioad Just judging by what you posted, try commenting out the two blocks that use the backdrop style class.

All we use in the Mint-X theme which works fine is:

.nemo-desktop.nemo-canvas-item {
    color: #fff;
    text-shadow: 1px 1px @desktop_item_text_shadow;
}

.nemo-desktop.nemo-canvas-item:selected {
    background-color: alpha(@theme_selected_bg_color, 0.8);
    background-image: none;
    color: @theme_selected_fg_color;
    text-shadow: none;
}

**Comment by sergioad** [comment]
thank you so much, I will try it

**Comment by omango** [comment]
Hello,

*.nemo-desktop.nemo-canvas-item {
color: #FFFFFF;
text-shadow: 1px 1px @desktop_item_text_shadow;
}*

*.nemo-desktop.nemo-canvas-item:selected {
background-color: alpha(#D64A38, 0.9);
background-image: none;
color: #FFFFFF;
text-shadow: none;
}*  

worked like a charm, thank you!

The problem is that the background selection is red and I just cannot change it in any other color whatever color code I put- e.g. **background-color: alpha(#249DD2, 0.9);** for blue. It just keep being red, it's really weird..

**Comment by mtwebster** [comment]
fyi, this issue is no longer applicable with the next nemo release - the desktop text will be readable regardless of the selected theme's support for nemo

**Comment by omango** [comment]
Well let's hope so :)
Actually it's okay, finally managed to make it another color than blue. Just had to reload "adwaita" from theme not by doing alt+f2+r only
Thanks guys for sharing!

**Comment by tacojones** [comment]
So, as of the newest versions of Cinnamon, we can no longer change the desktop font color? This was intentional?

**Comment by gabimladin** [comment]
For [Cinnamon on Debian](https://gist.github.com/gabimladin/070c103236cbd06ca2898ef30bcdc41d).
