### ISSUE TITLE
online seach in menu

### ISSUE THREAD

**Issue by sahilguleri** [linuxmint/Cinnamon#3227]
i think that we can integrate online search in menu.
just hit the super key and by typing keyword for example " abc google" would give us results for abc in google. Google and wiki would be good. without keywords it would be offline search.
we can also include map also like "map delhi,india" would give location of delhi on map.
today apple has also introduced online search in mac os 10.10

**Comment by anandrkris** [comment]
https://github.com/linuxmint/Cinnamon/pull/3853 Seems to address this. :smile:
