### ISSUE TITLE
Screenshots not working on Cinnamon (on Ubuntu)

### ISSUE THREAD

**Issue by djetty** [linuxmint/Cinnamon#3228]
I looked up the other solutions to this, but none have been relevant to my specific problem. Whenever I try to take a screenshot, it just takes a picture of what looks like the screen shown when I lock the screen.

The problem only started when I installed Cinnamon. I also tried downloading Shutter, and the screencapping on that has the same problem. How can I fix this?

![](http://i.imgur.com/ykeYkur.png)

By the way, I'm using Ubuntu 12.04 and Cinnamon v2.0.14

**Comment by rjanja** [comment]
Hi, have you tried this lately? I know the lock screen has had many changes since your initial report.

**Comment by ManIVIctorious** [comment]
Could you please check if this issue is still valid with cinnamon 3.0?

**Comment by JosephMcc** [comment]
The request to retest this from a year ago was never responded to, so closing it.
