### ISSUE TITLE
cinnamon-settings thumbnail file for themes missing

### ISSUE THREAD

**Issue by raymundovr** [linuxmint/Cinnamon#323]
I've just installed cinnamon in Debian Sid/Experimental and found the following issue when trying to change the theme settings:

r@bacha:~/.themes$ cinnamon-settings 
/usr/lib/python2.7/dist-packages/gobject/constants.py:24: Warning: g_boxed_type_register_static: assertion `g_type_from_name (name) == 0' failed
  import gobject._gobject
Themes
Traceback (most recent call last):
  File "/usr/lib/cinnamon-settings/cinnamon-settings.py", line 1006, in side_view_nav
    sidePage.build()
  File "/usr/lib/cinnamon-settings/cinnamon-settings.py", line 138, in build
    img = GdkPixbuf.Pixbuf.new_from_file_at_size( "/usr/share/cinnamon/theme/thumbnail.png", 64, 64 )
  File "/usr/lib/python2.7/dist-packages/gi/types.py", line 72, in constructor
    return info.invoke(cls, _args, *_kwargs)
gi._glib.GError: No se ha podido abrir el archivo «/usr/share/cinnamon/theme/thumbnail.png»: No existe el fichero o el directorio 
Translated: File does not exist.

The themes tab is not working due to this, it is very easy to solve it by creating the ...cinnamon/theme/ folder and then copying the thumbnail file from the data directory (pulled with git).
The installer should be modified maybe.

Cheers

**Comment by immikez** [comment]
When I updated System yesterday, I got the same issue.
➜  ~ cinnamon-settings
/usr/share/cinnamon/cinnamon-settings/bin/ChooserButtonWidgets.py:334: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if show_seconds is 'default':
/usr/share/cinnamon/cinnamon-settings/bin/ChooserButtonWidgets.py:338: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if show_seconds is 'true':
/usr/share/cinnamon/cinnamon-settings/bin/ChooserButtonWidgets.py:340: SyntaxWarning: "is" with a literal. Did you mean "=="?
  elif show_seconds is 'false':
True
/usr/share/cinnamon/cinnamon-settings/modules/cs_keyboard.py:422: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if category.int_name is not "custom":
/usr/share/cinnamon/cinnamon-settings/modules/cs_keyboard.py:431: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if category.int_name is "custom":
/usr/share/cinnamon/cinnamon-settings/modules/cs_keyboard.py:446: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if category.int_name is "custom":
/usr/share/cinnamon/cinnamon-settings/modules/cs_keyboard.py:456: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if entry is not "_invalid_":
/usr/share/cinnamon/cinnamon-settings/modules/cs_keyboard.py:539: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if cat[2].int_name is "custom":
/usr/share/cinnamon/cinnamon-settings/modules/cs_keyboard.py:577: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if cat[2].int_name is "custom":
/usr/share/cinnamon/cinnamon-settings/modules/cs_keyboard.py:603: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if cat[2].int_name is "custom":
/usr/share/cinnamon/cinnamon-settings/modules/cs_keyboard.py:694: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if entry is not "":
/usr/share/cinnamon/cinnamon-settings/modules/cs_keyboard.py:734: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if entry is not "":
/usr/share/cinnamon/cinnamon-settings/modules/cs_keyboard.py:780: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  ok_enabled = self.name_entry.get_text().strip() is not "" and self.command_entry.get_text().strip() is not ""
/usr/share/cinnamon/cinnamon-settings/modules/cs_keyboard.py:780: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  ok_enabled = self.name_entry.get_text().strip() is not "" and self.command_entry.get_text().strip() is not ""
