### ISSUE TITLE
Run in Software Rendering info should be stored in Notification Applet

### ISSUE THREAD

**Issue by highwindmx** [linuxmint/Cinnamon#3233]
![2014-06-041](https://cloud.githubusercontent.com/assets/6413481/3179602/eb05db8a-ec27-11e3-9fae-c90993cac42d.png)
I don't know whether a notification center is planned in next version of cinnamon, but I think info like this should be showed in notification applet for users who want to look at it again.

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html
