### ISSUE TITLE
Multi pointer support

### ISSUE THREAD

**Issue by jtsagata** [linuxmint/Cinnamon#3236]
I have a multi monitor setup, and i try a multi pointer setup. Useful if some friend visits you and asks to check something. Enable it give him a mouse a keyboard and a monitor and you can both work.

I follow the tutorial from here: http://www.linux.com/learn/tutorials/542356-weekend-project-zap-your-coworkers-minds-with-multi-pointer-x. But as soon as i reassign a device to a new virtual device the cinnamon reboots.

I know that multi pointer/keyboard is still an experimental feature but having an easy way to have a cheap multi seat environment on demand is a coll feature.

**Comment by Vahan86** [comment]
@JosephMcc, can we mark the issue as a feature request?

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html
