### ISSUE TITLE
Sound does not appear on removable device connect/disconnect

### ISSUE THREAD

**Issue by h4tr3d** [linuxmint/Cinnamon#3237]
Version: Linux Mint 17, cinnamon 2.2

Hi Team!

For begin I found that Removable device applet is hidden when I connect new removable device. It only shown after device mounting. Also in Mint 16 I hear sound on device physical connect/disconnect. At the Mint 17 it is wrong: I can't hear sound.

I make small research and found that sound plays in /usr/share/cinnamon/js/ui/placesManager.js on GIO drive-connected and drive-disconnected signals handling. So it looks like this signals does not arrived from Gio.VolumeMonitor().

Also, this signals translated to mounts-updated signal that handled by Removable Devices applet to update devices list. As a result Removable devices applet does not shown connected but unmounted devices.

Note, I try to run next GIO example: http://pastebin.com/xXbqpq8w and it correctly handle signals drive-connected and drive-disconnected.

As a conclusion use cases:

PRECONDITIONS: Linux Mint 17, cinnamon is installed and running, no any removables devices connected and mounted. Removable devices applet is hidden. Sound card configured and unmuted, sound level sets to max. Automounting is turned off.
1. Insert usb flash drive to USB
   Expected: sound is play, removable device applet shown
   Actual results: **WRONG**, sound does not play, removable devices applet is still hidden
2. Remove usb flash drive from USB
   Expected results: sound is play, removable applet hidden
   Actual results: **WRONG**, sound does not play, applet is still hidden
3. Repeat step 1. Open Nemo
   Expected results: connected device shown in device list
   Actual results: OK
4. In Nemo click on device
   Expected results: device connected and shown
   Actual results: OK, **but on this step removable devices applet also shown**.

**Comment by Vahan86** [comment]
@h4tr3d, is this still an issue for you in Cinnamon 3 (Mint 18)?

**Comment by h4tr3d** [comment]
@Vahan86 currently I migrate to Mate but I can check it on Mint 18.1 (I enable Sarah now) during some days. Can you wait before issue close?

**Comment by JosephMcc** [comment]
Yep. Thanks for the feedback.

**Comment by Vahan86** [comment]
@h4tr3d, thanks for help.

**Comment by Vahan86** [comment]
@JosephMcc, can we close the issue?
