### ISSUE TITLE
Cinnamon password including # does not work

### ISSUE THREAD

**Issue by wahmit** [linuxmint/Cinnamon#3239]
I've just installed Mint 17 - Cinnamon 64 bit.
If the password contains the # character the password is not recognised using the GUI but is recognised when logging in from the command line.

**Comment by Vahan86** [comment]
@wahmit, is this still an issue in Cinnamon 3.0.x?

**Comment by JosephMcc** [comment]
This isn't really a Cinnamon issue. The initial login has nothing to do with Cinnamon.
