### ISSUE TITLE
increase hotcorner functionality 

### ISSUE THREAD

**Issue by sahilguleri** [linuxmint/Cinnamon#3241]
i am very impressed by the way gnome  has introduced message tray at bottom of screen.
it would be great if Linux mint has same functionality but this messge tray would
 pop up at top of screen if we hit a hotcorner. we can use space more eficiently like adding  message etc
![messagetray-menu](https://cloud.githubusercontent.com/assets/7669448/3209539/0c2b3a04-ee75-11e3-8f1b-dae3225aaf78.png)

![message-tray-chat-3 10](https://cloud.githubusercontent.com/assets/7669448/3209534/dd8e7c60-ee74-11e3-95ab-47a083effae0.png)

**Comment by JosephMcc** [comment]
https://github.com/linuxmint/Cinnamon/issues/2117
