### ISSUE TITLE
options on right click on minimized tab

### ISSUE THREAD

**Issue by sahilguleri** [linuxmint/Cinnamon#3243]
plz add option like 'open in new window' and 'open private browsing' on right click on minimized tab of firefox 

![screenshot from 2014-06-08 01 36 50](https://cloud.githubusercontent.com/assets/7669448/3209695/a17d8e44-ee80-11e3-80b2-66ed1aef484c.png)

same could be done with other applications like on right click on thunder bird option like "create new mail" or "open inbox" could be added.

and with uget "resume all download" or "stop all download" etc

**Comment by pixunil** [comment]
Also requested in #3666.
