### ISSUE TITLE
Window tiling shortcuts rendered useless with sloppy or mouse focus modes

### ISSUE THREAD

**Issue by DiThi** [linuxmint/Cinnamon#3244]
When I press super+arrows to tile the active window, the window under the cursor changes and the sloppy focus mode makes that window focused. Every time I want to keep using the first window or to further tile it more (e.g. pressing super+right first, then super+down to tile it in the lower right corner).

The "sloppy" mode is not sloppy enough. It shouldn't change focus when not moving the mouse or explicitely switching windows with alt+tab. Enabling focus stealing prevention not only doesn't fix the problem, but some windows that I do expect to pop up are kept under.

Maybe a better and an easier fix would be moving the cursor alongside the window, in a position relative to where it was in the window before.

**Comment by ManIVIctorious** [comment]
I can confirm this issue, quite annoying...

**Comment by JosephMcc** [comment]
I'm not sure what the best way to handle this would be but I sure wouldn't want my mouse cursor jumping around on it's own.

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html
