### ISSUE TITLE
adding close button with 'all windows' preview 

### ISSUE THREAD

**Issue by sahilguleri** [linuxmint/Cinnamon#3246]
it would be good if you put a close button alongside with open application in window preview. it will save us from going to each tab and closing them one by one

![screenshot from 2014-06-07 14 01 31](https://cloud.githubusercontent.com/assets/7669448/3210422/f0ab376c-eebe-11e3-8f32-b99dbd7893f7.png)

**Comment by Vahan86** [comment]
@JosephMcc, can we mark this issue as a feature request?

**Comment by NikoKrause** [comment]
Right-click on an open Window: "Close all"

Or has it to be the above mentioned applet?

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html
