### ISSUE TITLE
wireless icon on limited access

### ISSUE THREAD

**Issue by sahilguleri** [linuxmint/Cinnamon#3248]
in windows on limited access yellow star on internet connection icon comes in the taskbar . i would like to have same functionality in linux mint. 
![w7_wireless_network](https://cloud.githubusercontent.com/assets/7669448/3211866/4ccd295e-ef34-11e3-8205-030c1eb2738d.png)

this would tell whenever internet connection is down

**Comment by Vahan86** [comment]
@JosephMcc, can we mark this issue as a feature request?

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html
