### ISSUE TITLE
Attaching dialog windows can result in permanently dimmed main window

### ISSUE THREAD

**Issue by jepst** [linuxmint/Cinnamon#3249]
When "Attach dialog box" is enabled in Cinnamon's Window settings, if the modal dialog box closes while the main window is minimized, the main (owning) window will be permanently grayed out (dimmed), although still usable. Follow these steps:
1. Start Synaptic package manager. Select some packages to install and click apply. A modal dialog box will appear showing the packages being downloaded and installed.
2. Ensure that the "Automatically close after installation" checkbox is checked.
3. While the download and installation is happening, minimize the main Synaptic window. The associated modal dialog will minimize as well.
4. Wait while installation completes.
5. After the installation, restore the Synaptic window.
6. You will see that the modal dialog is gone, but the main window is permanently grayed out (dimmed), as if there were still a modal dialog. The only way to fix this is to close the window and re-open it.

The bug can be reproduced with any application that (a) can be minimized (b) has modal dialog boxes and (c) those modal dialog boxes close on their own. Here is a screenshot from Cinnamon Update Manager after pressing Refresh, then minimizing, waiting, then restoring. Notice that the main window is dimmed after the dialog box is closed:

![screenshot from 2014-06-08 18 55 10](https://cloud.githubusercontent.com/assets/617498/3212487/5a6b69be-ef60-11e3-8c97-1c95b0963420.png)

Previously, attaching dialog windows resulted in a disappearing main window, as documented here: #2099 #2675 That was fixed with path #3161, which introduced this problem.

**Comment by anandtrex** [comment]
The same problem seems to have reappeared now in Cinnamon 2.6.7. This is on Archlinux

**Comment by mikkorantalainen** [comment]
I'm still experiencing this issue with Eclipse and Thunderbird. I'm using following versions:

cinnamon:
  Installed: 2.6.7-20150608040008-trusty
  Candidate: 2.6.7-20150609040009-trusty
http://ppa.launchpad.net/gwendal-lebihan-dev/cinnamon-nightly/ubuntu/ trusty/main amd64 Packages

muffin:
  Installed: (none)
  Candidate: 2.6.1-20150609003003-trusty
http://ppa.launchpad.net/gwendal-lebihan-dev/cinnamon-nightly/ubuntu/ trusty/main amd64 Packages

mtwebster commented on Jun 28, 2014 that correct muffin version should be used. I don't even have muffin installed at all and this is the only issue I'm having.

**Comment by mtwebster** [comment]
This should be fixed (again) in nightlies: https://github.com/linuxmint/Cinnamon/commit/794e84f3efe0cb64235cb72fdb0256e3779a3d3f

Have you restarted Cinnamon?

I can't reproduce in thunderbird - file->open saved message properly dims the parent window, then undims when the dialog closes.

**Comment by mikkorantalainen** [comment]
Okay. Installed latest nightly binaries (I installed muffin, too) and it now works for me. I the latest fix is the correct one.

$ apt-cache policy cinnamon muffin
cinnamon:
  Installed: 2.6.7-20150609040009-trusty
  Candidate: 2.6.7-20150609040009-trusty
  Version table:
 *** 2.6.7-20150609040009-trusty 0
        500 http://ppa.launchpad.net/gwendal-lebihan-dev/cinnamon-nightly/ubuntu/ trusty/main amd64 Packages
        100 /var/lib/dpkg/status
muffin:
  Installed: 2.6.1-20150609003003-trusty
  Candidate: 2.6.1-20150609003003-trusty
  Version table:
 *** 2.6.1-20150609003003-trusty 0
        500 http://ppa.launchpad.net/gwendal-lebihan-dev/cinnamon-nightly/ubuntu/ trusty/main amd64 Packages
        100 /var/lib/dpkg/status
     1.7.3-1ubuntu1 0
        500 http://fi.archive.ubuntu.com/ubuntu/ trusty/universe amd64 Packages
