### ISSUE TITLE
[bug] bookmark in menu inconsistent with in nemo side-panel

### ISSUE THREAD

**Issue by highwindmx** [linuxmint/Cinnamon#3251]
![bug2](https://cloud.githubusercontent.com/assets/6413481/3212891/143f7f02-ef79-11e3-8a86-49ba6c643cab.png)
when I report issue 3250 ,I find another bug, (and it may be a nemo issue, I am not sure)
you can see in the pic ,after I delete the folder "test测试",  the bookmark in nemo side-panel is just disappeared after a log-out/log-in, but it can still be found in bookmark manager and also show in menu->place

**Comment by Vahan86** [comment]
@highwindmx, is this still an issue for you in Cinnamon 3.0.x?

**Comment by Vahan86** [comment]
@JosephMcc, can we close this issue?
