### ISSUE TITLE
Bug: Most multimedia apps keep hanging or quitting on Linux Mint 17 Cinnamon

### ISSUE THREAD

**Issue by freemangilgamesh** [linuxmint/Cinnamon#3259]
Remenber when I reported the bug related to Freetuxtv!! I realized that this bug is common to most multimedia apps. For instance Minitube, which worked with no glitch on Linux Mint 16 and still does on Ubuntu 14.04, keeps quitting or hanging like in the screenshot below on Linux Mint 17 Cinnamon:

<a href="http://www.imagebam.com/image/5aaa0b332325385" target="_blank"><img src="http://thumbnails110.imagebam.com/33233/5aaa0b332325385.jpg" alt="imagebam.com"></a>

**Comment by ManIVIctorious** [comment]
Could you please check if this issue still exists in cinnamon 3.0.x?

**Comment by Vahan86** [comment]
@JosephMcc, can we close this  issue?
