### ISSUE TITLE
password screen is asked two times and font indicator does not switch

### ISSUE THREAD

**Issue by antonkulaga** [linuxmint/Cinnamon#3261]
I use my notebook in two monitor configuration (together with other monitor) with Ubuntu_14.04+Cinnamon. When I've been away for some time and my pc asks me the password "en" is always displayed in password prompt and when I push switch language key combinations the language switches but "en" is still displayed. When I type the right password it asks me to type the password once more. It is extremely annoyi9ng

**Comment by Vahan86** [comment]
@antonkulaga, is this still an issue for you in Cinnamon 3.0.x?

**Comment by Vahan86** [comment]
@JosephMcc, can we close the issue?
