### ISSUE TITLE
Better language setting support for Chinese users

### ISSUE THREAD

**Issue by highwindmx** [linuxmint/Cinnamon#3262]
When solving the question in the forum here: http://forums.linuxmint.com/viewtopic.php?f=90&t=170002, remind me to post this issue.

How about when adding Chinese language ,at least provide a guide to let people know if they want to input Chinese character they may need to install some more packages,(and hopefully not automatically install ibus as ubuntu do, lots of people are fans of fcitx or else, and don't like too many deps with ibus)

Thank you.

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html
