### ISSUE TITLE
Cinnamon restart required after changing UI scaling factor

### ISSUE THREAD

**Issue by ch3pjw** [linuxmint/Cinnamon#3264]
Changing `System Settings > General > Desktop Scaling` between `Normal` and `Double (Hi-DPI)` does not change all Cinnamon's UI elements to be scaled correctly until Cinnamon is restarted. Noticeably, the text on the panel bar remains small when double scale is selected, as do window title bars.

As a user, I would expect all UI elements to change when I select this option.

I currently have a simple workaround script for switching that doesn't involve the UI and restarts Cinnamon manually:
```
#!/bin/bash                                                                     
    
scaling_factor_path='org.cinnamon.desktop.interface scaling-factor'    
    
if [[ $(gsettings get $scaling_factor_path) == 'uint32 1' ]]; then    
    gsettings set $scaling_factor_path 2    
else    
    gsettings set $scaling_factor_path 1    
fi    
DISPLAY=:0    
cinnamon --replace > /dev/null 1>&2 &
```

**Comment by JosephMcc** [comment]
Duplicate https://github.com/linuxmint/Cinnamon/issues/3194
