### ISSUE TITLE
Colour profiles don't save/load properly

### ISSUE THREAD

**Issue by jtrees** [linuxmint/Cinnamon#3268]
On Linux Mint 16 with Cinnamon I am having issues with colour profile settings. I use a dual screen setup and have to re-apply the correct colour profile to each screen every time I log in. In the Colour section of the System Settings the profiles are listed as usual but I can see that they are not applied until I remove them and add them once again after logging in.

**Comment by Vahan86** [comment]
@JosephMcc, can we close this issue since there is no response from OP for a long time?
