### ISSUE TITLE
Cinnamon 2.2 does not restart when using Troubleshooting / Restart Cinnamon with desktop zoomed

### ISSUE THREAD

**Issue by rojthevorlon** [linuxmint/Cinnamon#3272]
If Troubleshoot / Restart Cinnamon is invoked while the desktop is zoomed, Cinnamon 2.2 does not restart.  The result is no taskbar, no menu and no window decorations.  ACPI Shutdown via the power button DOES bring up the shutdown / restart dialog and can be used to restart the system.

**Comment by Vahan86** [comment]
@rojthevorlon, is this still an issue for you in Cinnamon 3.0?

**Comment by rojthevorlon** [comment]
Will let you know is 24 - system running movie encode right now.

**Comment by rojthevorlon** [comment]
No, it's all good. :)
