### ISSUE TITLE
Folder hover text jitters top left in nemo

### ISSUE THREAD

**Issue by mtroyka** [linuxmint/Cinnamon#3273]
If you open a nemo window and mouse over the default folders in the left panel, the pop-up text box with the description for each first appears at the top-left corner of the screen, where it causes a brief jitter effect before moving to where it's supposed to go. It isn't always noticeable but if you move the mouse slowly over the folders you can see it.

**Comment by ManIVIctorious** [comment]
Is this still relevant for cinnamon 3.0?

**Comment by mtwebster** [comment]
No - https://github.com/linuxmint/muffin/commit/bf22fd7a96f8257af9a9f67bbcd933fd06756719
