### ISSUE TITLE
Docky displaying wrong icons

### ISSUE THREAD

**Issue by ez-man** [linuxmint/Cinnamon#3277]
In the Docky bay are the wrong (or no) icons visual.

For example: the Cinnamon Settings windows the Bluetooth icon (+ text "Bluetooth") is shown,   see image below. For Recoll there is no icon, instead the "no icon" is shown.

If tockled  with Alt + Tab you see the same behaviour when Docky is in action, but it disappeared when Docky is not active, then the correct icons are shown.. 

 <i>Frans v d Veer</i>

![cinnamon docky](https://cloud.githubusercontent.com/assets/7921450/3311749/71e599c4-f6c8-11e3-88a8-6a92e9fe3090.png)

**Comment by Vahan86** [comment]
@JosephMcc, is this Cinnamon related issue or we can close it?

**Comment by JosephMcc** [comment]
It doesn't look like a cinnamon issue and it's really old.
