### ISSUE TITLE
Netbeans 7 (Swing) issue with cinnamon on mint 12

### ISSUE THREAD

**Issue by ghost** [linuxmint/Cinnamon#328]
There is an issue with Netbeans 7 (Swing) on Linux Mint 12 with cinnamon.
http://netbeans.org/bugzilla/show_bug.cgi?id=198639
This Problem is solved on Gnome 3, but not on Mint 12 + cinnamon.
The crazy thing is on Fedora 16 + cinnamon, this bug don’t appear.

**Comment by onyxnz** [comment]
I have the same issue, with Mint 17.1 Cinnamon 64bit. It also does a similar thing with Firefox and Chrome, where I cannot accurately interact with them until I Unmaximize. Reproducible always if switching between virtual desktops.
