### ISSUE TITLE
The default volume for audio devices should not be 100%

### ISSUE THREAD

**Issue by Hubro** [linuxmint/Cinnamon#3283]
Scenario: My PC is freshly booted. The active audio device is my USB Headset. I don't realize this before I start a YouTube video. Video playing, I switch to my speakers using the "Output device..." section of the volume tray and TotalBisquit's intro music wakes the entire neighborhood.

I deal with this issue several times per day, both when switching from speakers to headset and the other way around. Currently I have to triple check that my PC isn't playing *any* sound before switching audio device and setting the volume level to 50%.

I can imagine several ways this could be addressed:

0. The volume could default to 50% instead of 100%
0. The default volume could be a user controlled setting
0. The volume could be remembered between reboots

All of the options above would pretty much solve the issue.

I could also reduce the volume level of my physical speakers to a point where 100% is usable, but this isn't a very good solution. I would have to adjust the volume level of the physical speakers if I want to increase the volume for any reason. Also this isn't possible with my USB headset.

**Comment by ManIVIctorious** [comment]
@JosephMcc I think this can be closed, since it doesn't seem to be a cinnamon bug and also applies to the sound settings, which have been revamped since the original post
