### ISSUE TITLE
cinnamon-menu-editor repaint bug (not usable)

### ISSUE THREAD

**Issue by shanemikel** [linuxmint/Cinnamon#3286]
When checking (or un-checking) items in any list within this application, I can only check (or uncheck) three items at a time before I have to wait a second or so for the interface to repaint the newly checked or unchecked items as bold or not..  This is especially a problem when working with a long list of .desktop files because it also resets the interface to the top of the scroll list (so if you were at the bottom you need to keep scrolling down after every three checks)

**Comment by Vahan86** [comment]
@shanemikel, is this still an issue for you with Cinnamon 3?

**Comment by shanemikel** [comment]
Actually, I've given up Cinnamon for the extraordinary and still promising experience of the new KDE.  Though I appreciate all you (unqualified plural, though certainly not including myself) have done to ease the pain of the misguided state of free desktops, and will definitely return if (when?) KDE becomes monstrous yet again.

**Comment by Vahan86** [comment]
@JosephMcc, can we close the issue?
