### ISSUE TITLE
cinnamon-screensaver fails to paint the screen

### ISSUE THREAD

**Issue by shanemikel** [linuxmint/Cinnamon#3287]
I am unable so far to reproduce this bug..

the cinnamon-screensaver every now and again will lock the screen properly (but fail to paint that shadow deal over the screen OR present the window for entering user password) so it would appear to the user as if the desktop has crashed only showing wallpaper and desktop icons (no panel or anything else)

When this happens I am able to unlock by typing password and hitting ENTER, but it could be a frustrating problem to others

**Comment by Vahan86** [comment]
@shanemikel, is this still an issue for you in Cinnamon 3.0?

**Comment by JosephMcc** [comment]
In git master most of the screensaver bugs are no longer going to be valid since the screensaver is new and completely rewritten.
