### ISSUE TITLE
Finish implementation of the Video file associations in Preferred Applications

### ISSUE THREAD

**Issue by geoffm** [linuxmint/Cinnamon#3290]
When setting an application as default for Videos in Preferred Applications, it changes only a few of most of the mimetypes associated with Videos. I set VLC as the default application in Videos, but after that the mimetypes are as follows:
 But my registered mimetypes are the following:

In ~/.local/share/applications/mimeapps.list:

video/3gpp=banshee.desktop
video/avi=banshee.desktop
video/dv=vlc.desktop
video/fli=banshee.desktop
video/flv=banshee.desktop
video/mp4=vlc.desktop
video/mp4v-es=vlc.desktop
video/mpeg=vlc.desktop
video/msvideo=vlc.desktop
video/ogg=banshee.desktop
video/quicktime=vlc.desktop
video/vivo=banshee.desktop
video/vnd.divx=banshee.desktop
video/vnd.vivo=banshee.desktop
video/x-anim=vlc.desktop
video/x-avi=vlc.desktop
video/x-flc=vlc.desktop
video/x-fli=vlc.desktop
video/x-flic=banshee.desktop
video/x-flv=vlc.desktop
video/x-m4v=banshee.desktop
video/x-matroska=vlc.desktop
video/x-mpeg=vlc.desktop
video/x-mpg=banshee.desktop
video/x-ms-asf=vlc.desktop
video/x-ms-wm=banshee.desktop
video/x-ms-wmv=vlc.desktop
video/x-ms-wmx=banshee.desktop
video/x-ms-wvx=banshee.desktop
video/x-msvideo=vlc.desktop
video/x-nsv=vlc.desktop
video/x-ogm+ogg=vlc.desktop
video/x-theora=banshee.desktop
video/x-theora+ogg=banshee.desktop
video/vnd.rn-realvideo=vlc.desktop
video/mp2t=vlc.desktop
video/webm=vlc.desktop

[Added Associations]
video/3gpp=banshee.desktop;
video/avi=banshee.desktop;
video/dv=banshee.desktop;vlc.desktop;
video/fli=banshee.desktop;
video/flv=banshee.desktop;
video/mp4=banshee.desktop;
video/mp4v-es=banshee.desktop;vlc.desktop;
video/mpeg=banshee.desktop;vlc.desktop;
video/msvideo=banshee.desktop;vlc.desktop;
video/ogg=banshee.desktop;
video/quicktime=banshee.desktop;vlc.desktop;
video/vivo=banshee.desktop;
video/vnd.divx=banshee.desktop;
video/vnd.vivo=banshee.desktop;
video/x-anim=banshee.desktop;vlc.desktop;
video/x-avi=banshee.desktop;vlc.desktop;
video/x-flc=banshee.desktop;vlc.desktop;
video/x-fli=banshee.desktop;vlc.desktop;
video/x-flic=banshee.desktop;
video/x-flv=banshee.desktop;vlc.desktop;
video/x-m4v=banshee.desktop;
video/x-matroska=banshee.desktop;vlc.desktop;
video/x-mpeg=banshee.desktop;vlc.desktop;
video/x-mpg=banshee.desktop;
video/x-ms-asf=banshee.desktop;vlc.desktop;
video/x-ms-wm=banshee.desktop;
video/x-ms-wmv=banshee.desktop;vlc.desktop;
video/x-ms-wmx=banshee.desktop;
video/x-ms-wvx=banshee.desktop;
video/x-msvideo=banshee.desktop;vlc.desktop;
video/x-nsv=banshee.desktop;vlc.desktop;
video/x-ogm+ogg=banshee.desktop;vlc.desktop;
video/x-theora=banshee.desktop;
video/x-theora+ogg=banshee.desktop;
video/vnd.rn-realvideo=vlc.desktop;
video/mp2t=vlc.desktop;
video/webm=vlc.desktop;[/code]

In /usr/share/applications/defaults.list

video/3gpp=totem.desktop
video/dv=totem.desktop
video/fli=totem.desktop
video/flv=totem.desktop
video/mp2t=totem.desktop
video/mp4=totem.desktop
video/mp4v-es=totem.desktop
video/mpeg=totem.desktop
video/msvideo=totem.desktop
video/ogg=totem.desktop
video/quicktime=totem.desktop
video/vivo=totem.desktop
video/vnd.divx=totem.desktop
video/vnd.rn-realvideo=totem.desktop
video/vnd.vivo=totem.desktop
video/webm=totem.desktop
video/x-anim=totem.desktop
video/x-avi=totem.desktop
video/x-flc=totem.desktop
video/x-fli=totem.desktop
video/x-flic=totem.desktop
video/x-flv=totem.desktop
video/x-m4v=totem.desktop
video/x-matroska=totem.desktop
video/x-mpeg=totem.desktop
video/x-ms-asf=totem.desktop
video/x-ms-asx=totem.desktop
video/x-msvideo=totem.desktop
video/x-ms-wm=totem.desktop
video/x-ms-wmv=totem.desktop
video/x-ms-wmx=totem.desktop
video/x-ms-wvx=totem.desktop
video/x-nsv=totem.desktop
video/x-ogm+ogg=totem.desktop
video/x-theora+ogg=totem.desktop
video/x-totem-stream=totem.desktop

Moreover, trying to change the association in nemo in File Properties / Open with doesn't work either: I chose another application and set it as default but the association didn't actually change.

I had to manually change the entries in those files to get the right associations.

**Comment by anandrkris** [comment]
@geoffm - Is this issue seen in latest Cinnamon?

**Comment by Vahan86** [comment]
@JosephMcc, can we close this issue?
