### ISSUE TITLE
Unable to rescale some types of icon on the panel properly

### ISSUE THREAD

**Issue by xuhdev** [linuxmint/Cinnamon#3292]
When "Allow cinnamon to scale panel text and icon according to the panel height" is selected, some icons cannot be scaled properly.

For example, the [jitsi](https://jitsi.org/) icon:

![screenshot from 2014-06-21 15 39 40](https://cloud.githubusercontent.com/assets/325476/3350186/f7bf0ee4-f994-11e3-80a9-495d22bed26e.png)

**Comment by Vahan86** [comment]
@JosephMcc, https://github.com/linuxmint/Cinnamon/pull/5876

**Comment by JosephMcc** [comment]
This belong here: https://github.com/linuxmint/Cinnamon/issues/481 so we can keep the systray related issues together.
