### ISSUE TITLE
Window focus mode: OSX style

### ISSUE THREAD

**Issue by Hubro** [linuxmint/Cinnamon#3295]
Currently the window focus mode has 3 options - click, sloppy and mouse (the latter two are identical):

![screenshot from 2014-06-23 15 46 45](https://cloud.githubusercontent.com/assets/597206/3358313/e29fead0-fadc-11e3-8c97-1d4ebee06218.png)

I suggest adding an option for the window focus style that OSX uses. When a window is unfocused, clicking the window _only_ puts it into focus, it doesn't produce a click inside the window. This means that you can't accidentally click a button or a link when you're only trying to bring a window into focus. If you want to click a button in a window that is not in focus, you first have to click _anywhere in the window_ to bring the window into focus, then click the button. There are multiple scenarios where I miss this:
- I want to focus a full-screened video player, and clicking the video makes it pause. This is also true for maximized YouTube videos.
- I want to focus a text editor without changing the position of the text cursor.
- I want to focus a browser window, but the window is full of ads and links that I have to carefully avoid clicking.

This is one of the few things that I miss from my hackintosh days. I'm sure anybody switching to Linux + Cinnamon from OSX would also appreciate this option.

**Comment by kevlogan90** [comment]
@mtwebster - Was this feature ever added? I don't think I've seen this option, and it isn't available as of Cinnamon 2.6.7. Is there a reason this wasn't added?

**Comment by Hubro** [comment]
Just a small bump from me. I just went back from i3wm to Cinnamon, and even though I'm using the most recent version available in Debian testing (2.6.13) there's still no soft mouse focus setting :(

![2015-08-24 windows 03](https://cloud.githubusercontent.com/assets/597206/9433340/953ee296-4a31-11e5-9455-c029a03552a6.png)

If somebody would make a patch to add it to 2.6.13 I would love to resume testing it.

(Otherwise, great to see Cinnamon looking very polished!)

**Comment by Hubro** [comment]
I should also add, I used this feature for around 6 months after mtwebster implemented it, and it worked absolutely flawlessly.

**Comment by NikoKrause** [comment]
Isn't it merged yet?
