### ISSUE TITLE
The second audio device lost its volume settings after rebooting

### ISSUE THREAD

**Issue by xuhdev** [linuxmint/Cinnamon#3296]
I'm currently on the latest LMDE. I noticed that the volume level of the second device is lost every time after rebooting, but the first device can always remember its volume level. This can be reproduced by selecting either output device when rebooting. The cinnamon version is 2.0.14.

**Comment by anandrkris** [comment]
@mtwebster @pixunil - Fixed?

**Comment by Vahan86** [comment]
@xuhdev, is this still an issue for you in Cinnamon 3.0?

**Comment by xuhdev** [comment]
@Vahan86 I no long own hardware with two audio output devices. Sorry.
