### ISSUE TITLE
dvd icon overwrites existing launcher icon

### ISSUE THREAD

**Issue by miltmobley** [linuxmint/Cinnamon#3298]
Linux Mint16 Cinnamon on VAIO vpcf111fx  laptop.

I started Mint today with a DVD inserted in the DVD drive. The DVD's icon appeared to have replaced the Eclipse launcher icon that normally occupies the lower left corner of my screen. I created another Eclipse launcher, which appeared near the top of the screen. When starting Mint this evening, both the DVD icon and the old Eclipse icon appeared at the lower left, one on top of the other. The new Eclipse icon was in its expected location at the top of the screen.

**Comment by Vahan86** [comment]
@JosephMcc, please see the comment posted above.

**Comment by miltmobley** [comment]
I originally reported this problem on Mint16. I haven't seen it happen on Mint 17.1
