### ISSUE TITLE
enable html to be displayed as background

### ISSUE THREAD

**Issue by highwindmx** [linuxmint/Cinnamon#3303]
Inspired by this issue: https://github.com/linuxmint/Cinnamon/issues/2671
I also tried wallch, then this idea come into my mind:
can a html file(I prefer a local file) be displayed as a background, so that lots of feature (include cycling background pics) can be realized.

**Comment by JosephMcc** [comment]
https://github.com/linuxmint/Cinnamon/issues/2075
