### ISSUE TITLE
Missing shortcuts

### ISSUE THREAD

**Issue by Alan01** [linuxmint/Cinnamon#3304]
LM 17 Cinnamon:
Preferred Applications: "Text" has no shortcut (alt+letter) whereas the others do.
Account Details: Clicking "Password" to change it opens a dialog box where the button "Change" has no shortcut whereas "Cancel" do.

**Comment by Vahan86** [comment]
Preferred Applications: besides "Plain Text", "Documents" and "Source Code" don't have shortcuts as well.

**Comment by Vahan86** [comment]
@JosephMcc, can we mark the issue as a feature request?
