### ISSUE TITLE
Missing translation

### ISSUE THREAD

**Issue by Alan01** [linuxmint/Cinnamon#3305]
LM 17 Cinnamon
When configuring a desklet/applet/extension and hovering the mouse over the buttons Highlight and Remove a tool tip appears. The tool tip is translated (Danish) except for the word desklel/applet/extension which appears in English.

**Comment by ManIVIctorious** [comment]
Does a translation for these words even exist? I wouldn't know one in german...
Also I don't think that things should be "over translated", e.g. in german the desktop is translated to "Schreibtisch" nobody would ever use that word in days to day usage...

**Comment by JosephMcc** [comment]
This is a non issue with the xlet settings revamp coming in Cinnamon 3.2
