### ISSUE TITLE
add "Switched to AC/Battery Time" in Power Manager applet

### ISSUE THREAD

**Issue by davenul** [linuxmint/Cinnamon#3312]
For Laptop users, Power Manager applet shows the battery remaining time in tooltip, but the user doesn't have an easy/simple indicator for his battery performance.
It would be nice if when power is unplugged, the applet will show a line like “Switched to Battery on: 09:33:51” sort of indicator when clicking the applet's battery icon. Once AC power resume, the line will be like “Switched to AC on: 11:43:28”.
This way, the simple user (or not) will have a simple mean to measure and understand his battery performance, without the need to use “power Statistics” application.

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html
