### ISSUE TITLE
Systray should provide a blacklist feature 

### ISSUE THREAD

**Issue by s3lph** [linuxmint/Cinnamon#3318]
It currently disturbs me that I cannot blacklist certain items from appearing in the systray applet. E.g. LibreOffice is more than unusable without enabling it's systray quickstarter, but still I don't want the icon to appear in the tray.

Would someone mind to implement this? I can't do this own my own for a lack of time and documentation.

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html

**Comment by orbitalchicken** [comment]
@s3lph where can I edit the "hardcoded blacklist" on my system ?

**Comment by eyalroz** [comment]
So, this was not resolved... and continues to bother people today as well.

It is specifically an issue when you use wicd rather than NetworkManager, so and the applet is just confusing and annoying. Some people (myself included) use the former by mistake, and end up with conflicting DHCP licenses, and ugh, it's a mess.  ... and wicd is indeed used by default on Debian 10 and Devuan 3 at least.

So please address this....

**Comment by RadoBenoist** [comment]
> So, this was not resolved... and continues to bother people today as well.
> 
> It is specifically an issue when you use wicd rather than NetworkManager, so and the applet is just confusing and annoying. Some people (myself included) use the former by mistake, and end up with conflicting DHCP licenses, and ugh, it's a mess. ... and wicd is indeed used by default on Debian 10 and Devuan 3 at least.
> 
> So please address this....

I recently came across this problem (after a few gnome packages updated and the network icon became ultraugly) and when I removed the ugly icon, this other applet appeared which doesn't have an option to be removed from tray. So far the only possible way to get rid of the unwanted applet was to add a a command to be executed at startup: 'killall nm-applet' and problem solved.

**Comment by macrokernel** [comment]
If someone like me is struggling with this issue, here is a hint on where exactly the hard-coded blacklist can be created in Cinnamon version 6.0.4, Xapp-status version 1.0. 

1. Edit `/usr/share/cinnamon/applets/xapp-status@cinnamon.org/applet.js`.
2. Locate the following block of code:
```js
    shouldIgnoreStatusIcon(icon_proxy) {
        let hiddenIcons = Main.systrayManager.getRoles();

        let name = icon_proxy.name.toLowerCase();

        if (hiddenIcons.indexOf(name) != -1 ) {
            return true;
        }

        return false;
    }
```
3. Append items to the blacklist by adding the line with `hiddenIcons.push(...)`
```js
   shouldIgnoreStatusIcon(icon_proxy) {
        let hiddenIcons = Main.systrayManager.getRoles();

        hiddenIcons.push('dropbox', 'some-other-icon');

        let name = icon_proxy.name.toLowerCase();

        if (hiddenIcons.indexOf(name) != -1 ) {
            return true;
        }

        return false;
    }
```

Not sure if this is the best way, but it works for me.
