### ISSUE TITLE
Systray menu doesn't get the right position

### ISSUE THREAD

**Issue by xubincs** [linuxmint/Cinnamon#3320]
When clicking the systray icon, the corresponding menu doesn't get the right position, some of the    menus popup on top edge of the bottom panel but some of them popup right beside the icon.

![1](https://cloud.githubusercontent.com/assets/3786308/3442540/ac367d58-0115-11e4-833a-8efe856e0ff7.png)
![2](https://cloud.githubusercontent.com/assets/3786308/3442542/af5af428-0115-11e4-860d-c81d8a957a8e.png)

**Comment by Vahan86** [comment]
@xubincs, is this still an issue in Cinnamon 3.0?
