### ISSUE TITLE
Network Manager Applet

### ISSUE THREAD

**Issue by cortman** [linuxmint/Cinnamon#3321]
My idea is about the network manager applet on the Cinnamon panel.
Typically, if I'm clicking the applet, it's to show a list of wireless networks, and to potentially connect to one of them.
However, it doesn't appear that the applet refreshes very often and therefore if I've just started up a network or come to a new place the fastest way to get connected is to disable, then re-enable the wireless connection.
What if, by clicking on the icon, it automatically refreshes the available networks list?

**Comment by Vahan86** [comment]
@JosephMcc, duplicate of Issue https://github.com/linuxmint/Cinnamon/issues/1054
