### ISSUE TITLE
add 'Move to another workspace' to panel menu

### ISSUE THREAD

**Issue by TomRoche** [linuxmint/Cinnamon#3323]
**summary:** Please add the option to 'Move to another workspace' to the panel menu à la the frame/window menu.

**details:**

    $ date
    Tue Jul  1 22:44:14 EDT 2014
    $ cinnamon --version
    Cinnamon 2.0.14
    $ lsb_release -ds
    LMDE Cinnamon Edition
    $ cat /etc/debian_version
    jessie/sid
    $ uname -rv
    3.11-2-amd64 #1 SMP Debian 3.11.8-1 (2013-11-13)

I have 3 workspaces. If in workspace=1 I focus on a window (or 'frame'--I forget which is the correct UI jargon in this case) and do Alt-spacebar, I get a menu like

    Minimize
    Maximize
    Move
    Resize
    ----
    Always on Top
    Always on Visible Workspace
    Only on This Workspace
    Move to Workspace Right
    Move to Another Workspace  >
    ----
    Close

But if I right-click on its panel icon (or whatever you call the movable thingies in the panel that represent the open frames/windows--again, apologies for UI-illiteracy), I get a menu like

    Visible on all workspaces
    Move to left workspace
    Move to right workspace
    ----
    Close all
    Close others
    ----
    Minimize
    Maximize
    Close

This annoys, because I

* usually have many workspaces open (3 is actually not many for me)

* often invoke the panel menu when I want to move a frame/window to a particular workspace

Hence I would appreciate Cinnamon making the option to 'Move to another workspace' available from the panel menu as it does the frame/window menu.

**Comment by tp0** [comment]
+1.

This is particularly annoying with applications that insist on not using (or simply work better without) system title and borders, such as Chromium/Chrome.

I'd even go as far as a replacing the "move to right/left workspace" with this as a way to not clutter the menu too much.

**Comment by calestyo** [comment]
Absolutely agree on the later as well. Or even better... let people customize what they get in the window context menu.

btw: For all those that suffer from GNOME's CSD crap (where one doesn't get the context menu on the window' title region - Alt + right click will actually show it.

**Comment by tp0** [comment]
> btw: For all those that suffer from GNOME's CSD crap (where one doesn't get the context menu on the window' title region - Alt + right click will actually show it.

Thanks for that. That also works anywhere in the window.

**Comment by JosephMcc** [comment]
With the latest muffin from git you get the right click context menu on CSD window titlebars just like any other.
