### ISSUE TITLE
[RFC] Make Start up applications Friendly

### ISSUE THREAD

**Issue by anandrkris** [linuxmint/Cinnamon#3324]
Hi - Today, I was trying to add Artha dictionary to my start up list. I am aware of the process to add it. I need to give a name, type the command or browse for the binary. In case of artha, i know 'artha' itself is executable name. So, easy-peasy. Take another case, where I want to add Transmission, its executable name is transmission-gtk. Currently, I open the menu editor, browse it and check for the process name. I believe, this could be improved? The "Browse" is not so friendly as it opens home directory and not all users, especially who have used other OS in the past, are aware of the installed location (/usr/bin).

1. Option 1- Browse should list the list of applications installed. (Nemo - open with)
*I feel, somehow menu and this process could be clubbed.*
2. Option 2 is to to have the ability a program as start-up in Menu editor itself. 
3. Option 3 is to have this as a right-click option. (Add to Startup along with Add to Favorites, Panel, Desktop). Am aware that Mint has zero tolerance for bloat, so some may have reservations. :wink: 

Open for Discussion. :smiley: 
*P.S. Sorry, for the story style reporting.*

Update: Option 3 is https://github.com/linuxmint/Cinnamon/issues/726 suggested earlier.

**Comment by JosephMcc** [comment]
Startup applications now allows you to add an application directly form a list using Add->Choose application.

**Comment by anandrkris** [comment]
Thanks, missed closing this.
