### ISSUE TITLE
XCOM breaks theme in Cinnamon

### ISSUE THREAD

**Issue by gitdox** [linuxmint/Cinnamon#3326]
XCOM:EW breaks the theme and other things in Cinnamon

How to reproduce:
Start XCOM:EW
Quit XCOM:EW

What to expect:
... the usual stuff

What happens:
When starting the game i get a login sound.
When quitting the game...
1) the theme (Icons) is screwed
2) I cant minimize or close windows and the bar doesn't react to left clicks.

right click the bar seems to fix the second problem.

cinnamon version: 2.0.14+lmde

EDIT: The second problem seems to not occour everytime but when it occurs right click on the bar fixes it and after a click in steam it reappears

**Comment by JosephMcc** [comment]
Is this still an issue in current Cinnamon versions?

**Comment by Vahan86** [comment]
@JosephMcc, can we close the issue?
