### ISSUE TITLE
Close lid settings do not apply to shutdown

### ISSUE THREAD

**Issue by bakkerthehacker** [linuxmint/Cinnamon#3327]
Linux Mint 17 64-bit

When shutting down my laptop, I often close the lid immediately.  I have both ac and battery settings to ignore the close lid.  This works fine when my laptop is running.  However, when shutting down, the system will still suspend my laptop instead of shutting down.  Waking my laptop resumes the shutdown process.

**Comment by Pjotr123** [comment]
You can fix it easily with this single command line:
```
sudo sed -i '/lid_options =/,+1 {s/("suspend", _("Suspend")),/&\n ("shutdown", _("Shutdown immediately")),/}' /usr/lib/cinnamon-settings/modules/cs_power.py
```
Then you should have the "Shutdown immediately" option for closing the lid, in Power Manager (with thanks to Laurent85 from the Linux Mint forum, who invented this hack).

**Comment by Vahan86** [comment]
@bakkerthehacker,  is this still an issue for you with Cinnamon 3.0?

**Comment by bakkerthehacker** [comment]
I have not had my laptop for quite a while, so I am unable to test this on the hardware it was initially filed under.

**Comment by supergeante** [comment]
I used this command on cinnamon 3.2.7 with a slight change in the path, as cs_power.py is located here /usr/share/cinnamon/cinnamon-settings/modules/cs_power.py
