### ISSUE TITLE
Support additional sizes of the volume OSD window

### ISSUE THREAD

**Issue by nkoep** [linuxmint/Cinnamon#3330]
The OSD window which is displayed after volume changes is obnoxiously large in my opinion. It would therefore be desirable to be able to adjust its size in Cinnamon. To quote @mtwebster:
```text
<mtwebster> right now it scales according to screen size
<mtwebster> (which is probably broken now i think about it, for hidpi support)
<mtwebster> i wouldn't go more than 'small, medium, large' though, any more configurability is unnecessary i think
<mtwebster> and 'off
```
Technically, this affects [linuxmint/cinnamon-settings-daemon](https://github.com/linuxmint/cinnamon-settings-daemon) which is responsible for drawing the overlay window, but configuration should obviously still go through cinnamon-settings which is why I opened this issue here.

**Comment by pixunil** [comment]
Done in Cinnamon 2.6. ("Off", "Small", "Medium", "Large")
