### ISSUE TITLE
[Cosmetic] Empty space appears when switching between settings

### ISSUE THREAD

**Issue by anandrkris** [linuxmint/Cinnamon#3339]
A niggle really and perhaps not worth reporting! Anyways when switching back from Network settings to All settings, empty space gets drawn for a while *(seen in it in few other settings instances as well, was able to screen grab this time :smile: )*

![screenshot from 2014-07-08 18 12 08](https://cloud.githubusercontent.com/assets/4663298/3509735/d3d19c9c-069e-11e4-9c5b-13e84bc162a6.png)

**Comment by anandrkris** [comment]
@dalcde > [This] (https://github.com/linuxmint/Cinnamon/commit/62bd31ffb5a95ec7c52a80e616beda06fc0c32d6) fixes the issue?

**Comment by dalcde** [comment]
Don't think so

**Comment by anandrkris** [comment]
Okies, not a big deal anyways...

**Comment by Vahan86** [comment]
@JosephMcc, tried to reproduce the issue. It seems the issue is fixed. Cinnamon version: 3.0.7

**Comment by JosephMcc** [comment]
@anandrkris do you still see this problem?

**Comment by anandrkris** [comment]
Nope, can be closed.
