### ISSUE TITLE
Keyboard Shortcuts Passthrough

### ISSUE THREAD

**Issue by somini** [linuxmint/Cinnamon#3340]
Not sure if this is the right location to place this, but I wanted to know if it's possible to set a keyboard shortcut as passthrough.
What I mean is that when I define a keyboard shortcut, the program I defined is executed but the current window doesn't receive the keypress event. This can also be "solved" by pointing me to a way to send that keypress event from inside the program itself (shell script basically).

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html
