### ISSUE TITLE
cinnamon crashes and runs in fallback mode only

### ISSUE THREAD

**Issue by rmsarma** [linuxmint/Cinnamon#3345]
Linux gurus.. mint17 sinnamon startup issues seems to crash out and run in fallback mode all the time.. any suggestions ?

**Comment by Diskdoc** [comment]
I have this problem with a fresh install of 17.1 32-bit. Cinnamon crashes and enters fallback when booted from Live USB and also after install after having installed updates and rebooted.

Part of glxinfo:

"direct rendering: Yes
.
.
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) 865G x86/MMX/SSE2
OpenGL version string: 1.3 Mesa 10.1.3"

from lspci:

"00:02.0 VGA compatible controller: Intel Corporation 82865G Integrated Graphics Controller (rev 02)"

From Xorg.0.log:
[    31.684] (--) intel(0): Integrated Graphics Chipset: Intel(R) 865G
[    31.685] (--) intel(0): CPU: x86, sse2
[    31.685] (II) intel(0): Creating default Display subsection in Screen section
        "Default Screen Section" for depth/fbbpp 24/32
[    31.685] (==) intel(0): Depth 24, (--) framebuffer bpp 32
[    31.685] (==) intel(0): RGB weight 888
[    31.685] (==) intel(0): Default visual is TrueColor
[    31.686] (**) intel(0): Framebuffer tiled
[    31.686] (**) intel(0): Pixmaps tiled
[    31.686] (**) intel(0): "Tear free" disabled
[    31.686] (**) intel(0): Forcing per-crtc-pixmaps? no
[    31.686] (II) intel(0): Output VGA1 has no monitor section
[    31.686] (II) intel(0): Output VIRTUAL1 has no monitor section
[    31.686] (--) intel(0): Output VGA1 using initial mode 1680x1050 on pipe 0
[    31.686] (==) intel(0): DPI set to (96, 96)
.
.
[    31.687] (==) Depth 24 pixmap format is 32 bpp
[    31.708] (II) intel(0): SNA initialized with Almador (gen2) backend
[    31.708] (==) intel(0): Backing store enabled
[    31.708] (==) intel(0): Silken mouse enabled
[    31.709] (II) intel(0): HW Cursor enabled
[    31.709] (II) intel(0): RandR 1.2 enabled, ignore the following RandR disabled message.
[    31.710] (==) intel(0): DPMS enabled
[    31.710] (II) intel(0): Textured video not supported on this hardware
[    31.727] (II) intel(0): [DRI2] Setup complete
[    31.727] (II) intel(0): [DRI2]   DRI driver: i915
[    31.727] (II) intel(0): [DRI2]   VDPAU driver: i915
[    31.727] (II) intel(0): direct rendering: DRI2 Enabled
[    31.727] (==) intel(0): hotplug detection: "enabled"
[    31.727] (--) RandR disabled
[    31.742] (II) SELinux: Disabled on system
[    31.966] (II) AIGLX: enabled GLX_MESA_copy_sub_buffer
[    31.966] (II) AIGLX: enabled GLX_ARB_create_context
[    31.966] (II) AIGLX: enabled GLX_ARB_create_context_profile
[    31.966] (II) AIGLX: enabled GLX_EXT_create_context_es2_profile
[    31.966] (II) AIGLX: enabled GLX_INTEL_swap_event
[    31.966] (II) AIGLX: enabled GLX_SGI_swap_control and GLX_MESA_swap_control
[    31.966] (II) AIGLX: enabled GLX_EXT_framebuffer_sRGB
[    31.966] (II) AIGLX: enabled GLX_ARB_fbconfig_float
[    31.966] (II) AIGLX: GLX_EXT_texture_from_pixmap backed by buffer objects
[    31.966] (II) AIGLX: Loaded and initialized i915
[    31.966] (II) GLX: Initialized DRI2 GL provider for screen 0
[    31.988] (II) intel(0): switch to mode 1680x1050@60.0 on VGA1 using pipe 0, position (0, 0), rotation normal, reflection none
[    32.004] (II) intel(0): Setting screen physical size to 444 x 277"
"

**Comment by djjeck** [comment]
I'm having the same problem.
Cinnamon was working fine until I ran an apt-get upgrade.

**Comment by tuxcanfly** [comment]
A recent update caused some conflicts in config files and crashed cinnamon on reboot. Uninstalling fglrx packages (including config files) and re-installing them again fixed the issue.

**Comment by prods** [comment]
Mine crashes on reboot if the network-manager desklet is not able to connect to a wifi network. I am running Sarah 18 Cinnamon on a DELL XPS 13 9530 skylake i7 with the original wifi card. I was able to reproduce it by forgetting the wifi network and rebooting my laptop. Cinnamon crashes immediately after login and then it falls back into fallback mode until I add a wifi connection from the network connections option. When there is a wifi connection already registered Cinnamon boots up ok, but in some scenarios it fails but it loads fine once it connects to the wifi network and I click the "retry" to start Cinnamon from fallback mode dialog.

**Comment by Vahan86** [comment]
@JosephMcc, can we mark this issue as a bug?

**Comment by JosephMcc** [comment]
I'm closing this. The original bug is old and on an old Cinnamon version. The newer posts here aren't even relevant to the original issue. The original issue title probably doesn't help.

**Comment by lechatthecat** [comment]
I am using Linux mint Sylvia 18.3 for 64bit with nvidia GPU. Still experiencing this crash.

**Comment by chrsdiklly** [comment]
I am running Linux Mint Cinnamon 18.3 64 bit.  After I install updates and upgrade Gimp the next start up I get the message Cinnamon crashed would I like to restart cinnamon.  If I choose yes it continues to crash. and it will only run in fallback mode.  The only way to get back to cinnamon is to reinstall from my boot usb.

**Comment by Pislify** [comment]
i am running cinnamon every time i let the pc for a while it gives me this damn error
