### ISSUE TITLE
wallpaper per workspace

### ISSUE THREAD

**Issue by calestyo** [linuxmint/Cinnamon#3346]
Hi.

Please add functionality, so that one can set wallpapers per workspace.

- This could be one single static wallpaper per workspace,
- or a slideshop per workspace (where it should be possible that each workspace uses different slideshow settings/image repo ... or the same, and if the same is configured, it should be guaranteed that the same image isn't used for different workspaces, if possible).

Cheers,
Chris.

**Comment by p5a0u9l** [comment]
Agree.

**Comment by abdupattoh** [comment]
+1

**Comment by JosephMcc** [comment]
https://github.com/linuxmint/Cinnamon/issues/1774
