### ISSUE TITLE
scale panel applets with the panel

### ISSUE THREAD

**Issue by calestyo** [linuxmint/Cinnamon#3348]
Hi.

If the panel size is changed, then the size of the applets and launcher icons should be scaled as well.

Cheers,
Chris.

**Comment by Vahan86** [comment]
"Allow Cinnamon to scale panel text and icons according to the panel heights" option is available in Cinnamon Settings-> Panel.

**Comment by calestyo** [comment]
That was noticed already earlier, but as I've described then, the problem is that the text scales as well, which makes it ugly big and uses up quite some space without necessity.

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html
