### ISSUE TITLE
[bug] [archlinux] Sudenly everything panel-related dissapears

### ISSUE THREAD

**Issue by gabboman** [linuxmint/Cinnamon#3350]
http://gyazo.com/809f013cb87738daaf526fa47a4a6b5f
I have this problem, it happens sometimes. I use an intel HD graphics, what other data should I give?

**Comment by ManIVIctorious** [comment]
Can you please check if this issue still exists in cinnamon 3.0.x? The stability has improved a lot for me in the past few cinnamon revisions.

**Comment by Vahan86** [comment]
@JosephMcc, can we close this issue?
