### ISSUE TITLE
merge compiz effects

### ISSUE THREAD

**Issue by calestyo** [linuxmint/Cinnamon#3351]
Hey.

Probably that’s not as easily doable as I’d like to have it… but are there any chances to take over functionalities/effects from compiz to cinnamon's window manager?

So far compiz is the best WM I've ever seen, unfortunately it's more or less dead upstream.

One could literally configure every aspect of the desktop and window behaviour via ccsm, it has wonderful effects (which can all be configured on a per window-type basis,... e.g for popups, normal windows, etc.) and gazillions of values could be tuned, like how many milliseconds it takes for a window to maximize, or to minimize and so on and so on.
Another nice functionality was the "shading" of windows.. where a window could be collapes to just it's title bar.

Cheers,
Chris.

**Comment by dalcde** [comment]
#1682
