### ISSUE TITLE
fullscreen flash freezes on window notify

### ISSUE THREAD

**Issue by silviucc** [linuxmint/Cinnamon#3352]
When I'm watching something in a fullscreen flash window and someone mentions my name in an IRC channel causing the Hexchat button in the taskbar to flash, the video in the fullscreen window either freezes or the display goes green.

I can press escape and the flash embed in the page is still bugged. This can be fixed by either reloading the page or, in extremis, restarting firefox.

I'm using Linux Mint 17 with everything up to date, an nvidia GTX 660 card + the 331.38 binary blob installed via the driver manager.

**Comment by Vahan86** [comment]
@silviucc, is this still an issue for you with Cinnamon 3.0 (Linux Mint 18)?

**Comment by silviucc** [comment]
Hi,

I don't know whether this still happens or not. I'm not using Mint or Cinnamon as a DE

**Comment by Vahan86** [comment]
@silviucc, if we can't get updated info on the status of this issue, could you please close it? Thanks.
