### ISSUE TITLE
[Regression] Cinnamon 2.x: Tearing in full-screen applications

### ISSUE THREAD

**Issue by SOIMiMozO** [linuxmint/Cinnamon#3355]
Cinnamon has very strong video tearing, (at least with nvidia drivers)easily noticeable in video playback or games. The only way to fix that, is to add:
"CLUTTER_PAINT=disable-clipped-redraws:disable-culling
CLUTTER_VBLANK=True"
code into /etc/environment file.
Since 2.x version this workaround is valid only for non full-screen applications. Anything what goes full-screen still gets that tearing. 
This is my topic on forums, related to this problem:
http://forums.linuxmint.com/viewtopic.php?f=208&t=172254&p=886768#p886768

**Comment by Vahan86** [comment]
@SOIMiMozO, is this still an issue for you with Cinnamon 3.2?

**Comment by SOIMiMozO** [comment]
Nope, don't have it anymore.
