### ISSUE TITLE
[Feature Request] Newer and Powerful Desktop Handler

### ISSUE THREAD

**Issue by koldbyte** [linuxmint/Cinnamon#3359]
Currently, Nemo handles the desktop and its icons.
Its very rudimentary and needs a overhaul. Desktop Icons are cumbersome to organize and align in grids properly.
I am suggesting a newer Desktop Handler that will not just help in tidying icons but will also help in adding advanced features like grouping of desktop icons(similar to android), better grids, advanced background management.

Newer Handler may also help in optimizing the functionality of desklets. 
I believe HTML and CSS3 may form the core of the this handler and so live wallpapers may also be possible without much work.
There are many sources of inspirations for functionality like Android, KDE etc. 

Please share your opinions on the current desktop handler and if a newer desktop handler is a necessary change for cinnamon.

**Comment by ACinnamonUserInUK** [comment]
+1.

**Comment by koldbyte** [comment]
I am closing this issue as most of the things I requested are being discussed in other issues. But still I would like to emphasize the need for decoupling the Nemo and "Desktop". This could help a lot to add new and innovative features which might not be possible to add through Nemo. 
Desktop is a very important element of a DE and this thing is at the very core of the DE design. 
So, I believe it will need a lot of thinking and activity.
Thanks.
