### ISSUE TITLE
mousewheel zoom

### ISSUE THREAD

**Issue by sprintcowboy** [linuxmint/Cinnamon#336]
Would be nice to have a mousewheel zoom like compiz enhanced zoom desktop.
I am currently using gnome-shell-mousewheel-zoom  https://github.com/tobiasquinn/gnome-shell-mousewheel-zoom .
It uses the alt and mouse wheel so it does not interfere with Firefox's zoom or the menu.
I did have to edit the .desktop file to git it to work.
It does have a few issues but it works.
It sometimes jumps into zoom when initialized and it would be nice if the mouse pointer did not scale when zoomed.
It gets in the way of what I am trying  to zoom.
I would like to see this included in Cinnamon.

**Comment by kaefert** [comment]
hmm, the fine out of the box alt+mousewheel desktop zoom does not come with a fresh linux mint cinnamon 17.1 install. On another machine I've upgraded from 17 to 17.1 this still works, so its just a matter of missing config-option I guess.

I can configure keyboard shortcuts to zoom in and out, but I want it to work with alt+mousehweel and the keyboard-shortcut configuration tool ignores mouse events.
