### ISSUE TITLE
Improve cinnamon screesaver

### ISSUE THREAD

**Issue by aeametal** [linuxmint/Cinnamon#3369]
Suggest improvement to cinnamon-screensaver to avoid screen burns (a problem in dual monitor setup):
1. change position of clock on the screen every few minutes
2. fade clock during transition to next position
3. allow RSS news feeds (e.g. BBC, CNN) with adjustments to frequency of updates

**Comment by JosephMcc** [comment]
The first two have now been implemented and the screensaver completely redesigned.
