### ISSUE TITLE
Strange left mouse click behaviour.

### ISSUE THREAD

**Issue by bigos** [linuxmint/Cinnamon#3371]
I've noticed problems with Cinnamon on my two machines where computer does not respond as expected to mouse clicks. On my net-book with sticky keys enabled after a while computer begins to interpret left mouse clicks as right-mouse clicks. Switching sticky key off solves the problem for a while. 

Another problem I've noticed today on my desktop where clicking on Firefox icon on the bottom panel would open 155 Firefox windows. Logging out seems to have solved the problem.

I'm not giving up on Cinnamon yet and I'm willing to help to improve the report. How do I investigate such problems in Cinnamon?

**Comment by Vahan86** [comment]
@bigos, is this issue still relevant in Cinnamon 3.0?

**Comment by bigos** [comment]
I was related to a long standing bug in Linux's handling of sticky keys. I guess in the recent version of Mint it was fixed. I do not use a small laptop where having sticky keys help a lot. But I have tried it some time ago and didn't have any problems.
