### ISSUE TITLE
Cut / copy / paste stops wroking in Nemo

### ISSUE THREAD

**Issue by rojthevorlon** [linuxmint/Cinnamon#3374]
Using the Wordstar keystrokes for cut / copy / paste / select all stops working in Nemo after repeated and heavy use.  When this happens, the menu items for those functions also stop working.  Exiting and restarting Nemo restores that functionality.  This problem has been there since Cinnamon 2.0.

**Comment by fcastilloec** [comment]
I'm using nemo 2.4.5 on Ubuntu and I still have this bug. It happens quite often and as previously mentioned, the only way to restore functionality is to kill nemo and restart it.
Any ideas why this is happening or how to stop it?

**Comment by rojthevorlon** [comment]
it seems that it just "forgets" the wordstar commands to do cut / copy / 
paste and once it does even menu-driven cut / copy / paste stops working.

the place i'd look is whatever routines in nemo accept the wordstar key 
commands And Then Pass Them On To Be Executed.  I'd guess the keystroke 
commands are being captured (i'd check that first just to be sure) but 
then whatever piece processes those commands gets confused after that 
and either gets stuck or bypassed.  exiting and restarting nemo must 
reinitialize that process or buffer.

**Comment by lenashou** [comment]
this is not only the copy-paste that sometimes stop working on 2.4.5
renaming has the same issue. You can activate the renaming (f2), but it's impossible to change letters of delete some of them.
as the "suppr" key isn't working, it's impossible to delete file this way too.
"nemo -q" is a workaround, but it's quite annoying

**Comment by fedy2** [comment]
Same problem here. Copy and paste stop working after a while. The only solution is to kill nemo. Really annoying, especially if you're working on file organization.

**Comment by hydrospheric** [comment]
Confirming the same problem. Nemo 2.4.5, Mint 17.1.
I also noticed however that it also extends to - right-click, copy, paste - not just the key shortcuts (as rojthevorlon mentioned as well).

**Comment by mtwebster** [comment]
Can't reproduce this to save my life - can you guys run:

`nemo --quit`
then
`nemo`

and see if there are any warnings or errors being spit out once this problem manifests?

Also, are you copying within the same filesystem, between fs's?  Doesn't matter?

Thanks

**Comment by fcastilloec** [comment]
This problem was solved for me on Ubuntu. There have been some updates to nemo lateley (2.4.5-2) from the Webup8 PPA and also updates to nautilus from the Ubuntu repositories. I'm assuming this have fix the issue completely for me and I'm not able to reproduce it anymore.

**Comment by lenashou** [comment]
Found a solution. The pblm seems to be related with ibus.
I had to remove it, (sudo apt-get autoremove ibus), and now everything is working fine.
No more problems.

**Comment by fedy2** [comment]
I've got no messages on quitting it. When I've restarted Nemo I got this message, but I don't think is related to the problem:
"Nemo-Share-Message: Called "net usershare info" but it failed: 'net usershare' returned error 255: net usershare: cannot open usershare directory /var/lib/samba/usershares. Error Permission denied
You do not have permission to create a usershare. Ask your administrator to grant you permissions to create a share."

**Comment by fedy2** [comment]
Any news on this bug? 
I think this is a really serious bug, a file explorer with a buggy cut/copy/paste operation make it useless.

**Comment by cmcginty** [comment]
I keep hitting this bug and I do not have ibus installed, however I am running Mint 16 so take this with a grain of salt.

**Comment by rojthevorlon** [comment]
I hit this bug Every Single Day on Mint 17.1.

**Comment by rojthevorlon** [comment]
Bug persists in Mint 17.2.  That's how many years now?

**Comment by mtwebster** [comment]
Can I get anyone experiencing this to take the following steps:

In Mint 17, post the links to the urls returned from these commands:
```
dconf dump /org/cinnamon/ | pastebin
dconf dump /org/nemo/ | pastebin
dpkg --list | grep "nemo-" | pastebin
```
In anything else, redirect to a file, then pastebin/dpaste the files:
```
dconf dump /org/cinnamon/ > org.cinnamon.dmp
dconf dump /org/nemo/ > org.nemo.dmp
dpkg --list | grep "nemo-" > dpkg.dmp
```

This bug won't get fixed until it can be reproduced, so I need to try and figure out exactly what everyone's system state is... I've never been able to reproduce this, even once in a while, never.  I revisit it fairly often too and I'd like to get to the bottom of it.

Thanks

**Comment by rojthevorlon** [comment]
I hope one of my fellow users can help with this  at present as I leave for five and a half weeks in Europe in a couple of days.  If the bug is still giving grief when I get back, I'll definitely wade in and help.

 Cheers!

**Comment by Arxi** [comment]
@mtwebster happened to me today, here you go:

http://paste.linuxmint.com/view/r0qq/
http://paste.linuxmint.com/view/isqe/
http://paste.linuxmint.com/view/ln62/

**Comment by sab666** [comment]
@mtwebster here are my pastebins (very annoying to get these without copy&paste)

http://paste.linuxmint.com/view/w95m
http://paste.linuxmint.com/view/77of
http://paste.linuxmint.com/view/5gze

**Comment by mjbales** [comment]
@mtwebster Having the same problem today.  Here are mine.  I recently messed with GTK themes if that is any lead.
http://paste.linuxmint.com/view/ryza/
http://paste.linuxmint.com/view/l6ak/
http://paste.linuxmint.com/view/kghc/

**Comment by roblevy** [comment]
Hit this again today!

> dconf dump /org/cinnamon/ | pastebin
http://paste.linuxmint.com/view/siqp
> dconf dump /org/nemo/ | pastebin
http://paste.linuxmint.com/view/byep
> dpkg --list | grep "nemo-" | pastebin
http://paste.linuxmint.com/view/1ey6

**Comment by mtwebster** [comment]
Can you guys tell me when this happens, if you right-click and mouse over cut/copy, does it show "Copy the selected text to the clipboard" or "Cut the selected.." rather than what it *should* show in nemo - "prepare the selected files to be copied/moved..."?

If so, it seems triggered by renaming - see https://github.com/linuxmint/nemo/issues/909 - or at least that seems one of the ways to trigger it.  Just curious if it's the same bug.

Thanks

**Comment by Tekaiguy** [comment]
<img width="308" height="460" alt="Image" src="https://github.com/user-attachments/assets/c6871ce9-0f23-4e9f-b062-7f503376106d" />

2026 and this is still happening on Linux Mint 22.3 Cinnamon!
