### ISSUE TITLE
Inserting flash drive when zoomed may hang UI

### ISSUE THREAD

**Issue by rojthevorlon** [linuxmint/Cinnamon#3375]
Inserting a USB flash drive when the desktop is zoomed will always cause a significant pause and freezing of the desktop momentarily.  The handler to start Nemo may then work, launching Nemo successfully,  with the desktop un-freezing and functionality continuing normally.  However, the handler may also launch Nemo and freeze (requiring and OS reboot) or completely fail to launch Nemo and also freeze (requiring a reboot).  This does not happen if an external USB hard drive is inserted, appearing to be linked only to USB flash drives.

**Comment by Vahan86** [comment]
@rojthevorlon, does this issue still occur in Cinnamon 3.0?

**Comment by rojthevorlon** [comment]
No, it's all good. :)
