### ISSUE TITLE
Audio Problems

### ISSUE THREAD

**Issue by EndeavourAccuracy** [linuxmint/Cinnamon#3376]
Linux Mint 17 Cinnamon, fresh install.
Running Audacity gives a bunch of "ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred" messages and garbled sound; pressing Stop then hangs the application.
Then I tried Sweep, which gives an "Error opening ALSA device plughw:0,0: Device or resource busy".
I'm an experienced Linux user, so I'm aware of all the Pulseaudio problems and can work around them, but it's still painful to get underruns with Audacity immediately after a fresh distro install.
It's easy to just blame Audacity or Pulseaudio, but everybody blames everybody, so just move this bug report to whoever you think needs to look into this.

**Comment by anandrkris** [comment]
Yes, issue does not belong here, i.e., not a Cinnamon issue.
