### ISSUE TITLE
crazy updatemanager icon in system tray

### ISSUE THREAD

**Issue by penttila** [linuxmint/Cinnamon#3384]
Sometimes the icon of update manager (mintUpdate 4.6.7) in the system tray 'changes' from its normal 'shield' form to an 'undefined square' one.

See this attached screen shot under the cursor.

![icon_screenshot](https://cloud.githubusercontent.com/assets/8037522/3636888/cb5f0944-0fe7-11e4-8fec-554cbd90d3e4.png)

Linuxmint 17 cinnamon (version 1)

**Comment by Vahan86** [comment]
@penttila, is this still an issue for you with cinnamon 3.0?

**Comment by penttila** [comment]
I haven't seen this problem for a while. At the beginning of 2016 summer I installed Linux Mint Cinnamon with Cinnamon 3.0 but I am not sure about the exact time when this problem disappeared (maybe already earlier). Hopefully this issue got fixed somehow somewhere and the bug report can be closed.
