### ISSUE TITLE
[feature request] sound applet: control more applications

### ISSUE THREAD

**Issue by who-me** [linuxmint/Cinnamon#3385]
By default, the sound applet in Cinnamon allows the user to control the last application that is started. For example, if one has Banshee running and then opens VLC, they will only be able to control VLC through the sound applet. If Banshee is minimized (hidden) then, the only way to get it back is to close VLC and then click the button in the applet to bring up the window.

I think that the sound applet should be extended to support controlling more than one application at a time.

**Comment by mtwebster** [comment]
Implemented as of 05f65cf
