### ISSUE TITLE
Improve "downloading theme cache"

### ISSUE THREAD

**Issue by fpilee** [linuxmint/Cinnamon#3386]
When the user click for first time the tab "Obtain more themes" in Themes, it take too much for download themes cache, Why you don't use that cache for:

Install themes offline.
Pop-up window for see bigger screenshot.

**Comment by dalcde** [comment]
Please clarify

**Comment by mtwebster** [comment]
Downloader is now multi-threaded fwiw - it takes *drastically* less time than in 2.4

**Comment by fpilee** [comment]
Please try to not download the screenshot of the theme, or use a thumbnail. It take so much to download all the theme cache, also let cancel or close that task.

**Comment by dalcde** [comment]
How else would you know how the theme looks like if you don't download the screenshot?

**Comment by anandrkris** [comment]
From what I see, Themes - Add / remove desktop themes - refresh list can be canceled midway but doesn't properly cancel and come back to previous state once initiated. Seem like a bug to me.

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html
