### ISSUE TITLE
Password window will not close after changing password

### ISSUE THREAD

**Issue by theancientone** [linuxmint/Cinnamon#3390]
Hi,

I changed my password and after I was done the window would not close. I tried  it a few time but still the same. To confirm if your password is changed you need to run a sudo command like sudo apt-get update or logout and back in.

I all did was using the interface.

**Comment by Vahan86** [comment]
@theancientone, is this issue stiil relevant to Cinnamon 3?

**Comment by theancientone** [comment]
Hi,

To be honest, I did not test it. However, by a quick look, the problem 
seems to be solved.

Kind regards,

The ancient one


Op 30-11-16 om 15:13 schreef Vahan Harutyunyan:

**Comment by Vahan86** [comment]
@theancientone, thanks for reply. In this case can you please close the issue?
