### ISSUE TITLE
[Menu] Search box cursor does not blink. 

### ISSUE THREAD

**Issue by gauravjuvekar** [linuxmint/Cinnamon#3402]
Pretty self-explanatory.

LMDE UP8
Cinnamon 2.0.14

**Comment by dalcde** [comment]
Is that a problem?

**Comment by gauravjuvekar** [comment]
Yes, we provide this as an option ==> consistency
![keyboard_004](https://cloud.githubusercontent.com/assets/2271906/7492194/e2027bc0-f40e-11e4-932c-d8fa8426b975.png)



And it can look like an 'l' with some fonts
![workspace 2_006](https://cloud.githubusercontent.com/assets/2271906/7492196/ea086906-f40e-11e4-9fcd-a291412e9ad2.png)

**Comment by dalcde** [comment]
https://github.com/linuxmint/Cinnamon/commit/1a07385f8ec6c0520284233ac18ed7a5b04f7314
