### ISSUE TITLE
[Feature Request] Add dconf option to disable background setting.

### ISSUE THREAD

**Issue by unlimitedbacon** [linuxmint/Cinnamon#3405]
Since Cinnamon's background control panel has limited options (especially for multiple monitors) I would like to use Nitrogen instead. In order to do this, though, Cinnamon's own background setting needs to be disabled. Could you please add a dconf option to turn off all drawing of the desktop background, so that other applications can handle it instead?

**Comment by NathanC** [comment]
@mtwebster do you know how I can do this now? org.cinnamon.settings-daemon.plugins.background doesn't seem to exist anymore
