### ISSUE TITLE
Cinnamon requires Network Manager!

### ISSUE THREAD

**Issue by Arucarn** [linuxmint/Cinnamon#3409]
I don't know about other distros, but in Arch Linux networkmanager is a dependency of cinnamon. This is stupid. I want to use wicd but can't because cinnamon won't run without networkmanager. In Linux I should be able to do what I want and that means I should have the choice between differnet Network Managers. Please fix this soon.

**Comment by andy-vetrov** [comment]
Sorry for necroposting ;-) You can now safely remove NetworkManager dependency from Cinnamon 4.X.X (tested on latest 4.0.9) in Arch Linux - look at:
https://aur.archlinux.org/packages/cinnamon-slim/
In other Linux you must apply remove-networkmanager.patch and delete directory /Cinnamon-4.X.X/files/usr/share/cinnamon/applets/network@cinnamon.org in source files before make package.

P.S. Connman with connman-gtk works much more better, than NM.
