### ISSUE TITLE
Sound applet distorts images included in audio files if not standard ratio

### ISSUE THREAD

**Issue by donlencho** [linuxmint/Cinnamon#3411]
The image display of the sound applet is meant to show the CD or LP cover, usually a standard squarish image. But sometimes the cover image stored in the file is not the same size/ratio.
If it's "more vertical", it displays ok (see attached capture).
But if it's "more horizontal", it is horizontally squashed in order to fit in the standard ratio (see other capture). The captures show the sound applet next to the file in a nemo window, showing clearly what the cover images are supposed to be.
This is certainly not a priority issue, but a small detail that can probably be corrected very easily.

**Comment by JosephMcc** [comment]
Is this still an issue in the current sound applet?

**Comment by donlencho** [comment]
Yes it seems its fixed! Closing.
