### ISSUE TITLE
Cinnamon Menu: duplicate between System settings and Preferences menu entry

### ISSUE THREAD

**Issue by donlencho** [linuxmint/Cinnamon#3412]
It seems to me there are efforts to concentrate every settings in the System Settings window and to clean it up. But there is still a Preferences menu entry in the menu which includes pretty much exactly the same content, maybe it should be removed to clearly direct user to the System Settings if they want to change something?
There are a small number of other things in there it seems, like a double entry for the network settings, and some stuff are named differently in the menu and in the System Settings (at least in French).
If the point is to have everything searchable in the menu (which is convenient), it should at least be the same content and the same names.

**Comment by dandv** [comment]
Why are there two very similar Network dialogs? Can we get rid of the one below?

![image](https://cloud.githubusercontent.com/assets/33569/17685977/79c6d6da-631d-11e6-9b7c-79b32318291d.png)

This dialog shows incorrect information (#5539), and doesn't let me connect to any of the saved networks it displays. What's the point?

**Comment by mainmachine** [comment]
I've wondered that myself... what is the difference...?

**Comment by dandv** [comment]
@JosephMcc: yes, it's Cinnamon after it crashed and went into "fallback mode", if I remember correctly.

Not sure what you mean by multiple desktops; I have an external monitor connected, but you can reproduce the problem (two different but essentially the same network dialogs) on a standalone laptop with only one workspace in use - simply click the Wireless connection applet, and choose `Network settings`, then click again and choose `Network connections`.

**Comment by dandv** [comment]
Screenshot with Cinnamon running, if that makes any difference:

![image](https://cloud.githubusercontent.com/assets/33569/17688857/e8ad8dea-6337-11e6-99a6-6c079f51d23d.png)

BTW, the Network Connections list also adds "Auto" before every wireless network, even those I explicitly asked to forgot, like `xfinitywifi` above. Another bug that would go away if we get rid of this dialog.

**Comment by JosephMcc** [comment]
Ok, so once cinnamon crashes into fallback mode you are no longer running Cinnamon at all. That is a metacity/gnome-panel session that is there simply to give a gui you can use to troubleshoot whatever issue caused the Cinnamon crash. We don't maintain or develop those. In a perfect world you would never even know it was there.

As to the the second question about multiple desktop environments. Do you something like Mate installed as well as Cinnamon? I get that other dialog also but I have Cinnamon, Xfce, and Mate desktops installed on Mint18. If not I would be curious to find out where that dialog is coming from.

**Comment by mainmachine** [comment]
Ah, it's got to be from MATE... problem solved. :)

Now we should close this...

**Comment by f2404** [comment]
No, it's Cinnamon that provides both Network Settings and Network Connections dialogs - you can open either of them from NetworkManager applet. The Settings one allows to configure proxy,   wireless networks, etc, while Connections only shows the connections history, as I understand; I'm never opening the latter one.

**Comment by leigh123linux** [comment]
cinnamon provides 'cinnamon-settings network' only the other one is nm-connection-editor which isn't part of cinnamon.
nm-connection-editor is still required as it offers greater control of wired networks.

**Comment by f2404** [comment]
The 'Network Connections' dialog is 'cinnamon-settings network', right? What value does it have?

**Comment by leigh123linux** [comment]
@f2404 

You can use it to setup advanced wired networks

![screenshot from 2016-08-16 07-39-15](https://cloud.githubusercontent.com/assets/1299302/17690195/e3461e10-6384-11e6-9a80-1a9413f17a1a.jpg)

![screenshot from 2016-08-16 07-39-18](https://cloud.githubusercontent.com/assets/1299302/17690201/e7e8cc1a-6384-11e6-859e-5bc58f2c7957.jpg)

**Comment by f2404** [comment]
@leigh123linux Thanks! Never got this far into it.

**Comment by mainmachine** [comment]
I stand corrected, victim of a thumbs down.

Wouldn't it still make sense to consolidate these two interfaces...?

**Comment by donlencho** [comment]
Couldn't agree more, I was always confused by the two different interfaces. Not that I use any of the two often, thankfully my networks just work. But it would clarify the menu and settings to have just one, which was actually the point of this issue (which has gotten slightly off topic for a bit!).

**Comment by mainmachine** [comment]
Yeah I've used both (just because), and generally prefer the prettier one. Couldn't see any difference, and the overlap was confusing... never run mint, always some *buntu flavor with Cinnamon installed on top, so I just kind of assumed it was from another installed desktop.

**Comment by ManIVIctorious** [comment]
This obviously is no cinnamon issue, one of the entries you see is the gtk interface of network manager and the other one is the interface provided by cinnamon itself. It definitely is no bug for the menu to show all installed applications.

If anything this could be improved on the distribution side by just not displaying the networkmanager-gtk entry in the menu, so please close.

**Comment by donlencho** [comment]
Well, this issue wasn't about the network manager in the first place, but rather about the clarity and logic of the menu, what goes where and how it is presented. This seems to me like a Cinnamon issue. Anyway, some answers were given and maybe some leads are here to make it more obvious in future evolutions. Closing this now.
