### ISSUE TITLE
[Feature request] Disable/configure OSD for volume or luminosity changes

### ISSUE THREAD

**Issue by donlencho** [linuxmint/Cinnamon#3413]
Just like it is nice to be able to disable notifications, it would be nice if one could disable (or maybe configure in a less intrusive way) the OSD pop-ups when volume or luminosity is changed.
Feature request similar to #3330, but I would really like to be able to disable them totally, for situations like public presentations when you don't want that to appear on screen.

**Comment by anandrkris** [comment]
http://segfault.linuxmint.com/2015/02/recent-cinnamon-development/ > Should feature in the next Cinnamon release.
