### ISSUE TITLE
Cinnamon goes black in sleep mode

### ISSUE THREAD

**Issue by DTSCode** [linuxmint/Cinnamon#3415]
This issue is actually inherited from gnome3, but I'm not sure if I post the fix there it will find its way back into cinnamon, and I have a much more invested interest in cinnamon. For some reason, this issue isn't reproducible on all machines (since I've had other machines that don't replicate it), but certainly happens on the Dell Latitude E6410 issue. Anyways, in cinnamon, when I close my laptop it enters sleep mode (or whatever the default power saving mode is. I can't remember off the top of my head) and when I open it back up it lets me login like normal. However, if I log in, then the entire screen goes black. All of the windows are still there (I can tell because I still have audio and can move the cursor around), but I can't see anything. This does not happen on mate, or windows 7.

**Comment by Vahan86** [comment]
@DTSCode, is this still an issue for you with Cinnamon 3.2?

**Comment by Vahan86** [comment]
@JosephMcc,  can we close the issue?
