### ISSUE TITLE
With dual monitors of different resolutions, the login screen on LM17 Cinnamon is displayed at the wrong resolution on secondary, higher resolution monitor

### ISSUE THREAD

**Issue by CyanBlob** [linuxmint/Cinnamon#3417]
I am running Linux Mint 17 Cinnamon Edition on a laptop with a built-in 1366x768 resolution monitor, and am using an external 1920x1080 monitor. The login screen shows on both monitors, however, on the external monitor, there are large black bars on the right hand side and the bottom. This happens  every time, neither disabling the built-in monitor through the Cinnamon settings menu nor shutting the laptop lid while booting has any effect on this issue. The issue has persisted through multiple installations of LM17 Cinnamon. I have not tried any other DE, but I am fairly certain this is an issue with Cinnamon.

**Comment by dalcde** [comment]
No it's not a cinnamon issue. You need to get your system-wide xorg settings right.

http://www.gregfreeman.org/2012/fix-wrong-resolution-at-mdm-lightdm-login-screen-in-linux-mint-ubuntu/

And some relevant irc logs
```
<clem> ok, here's some theory that can explain what's happening..
<clem> when you configure your monitors, you're basically configuring them for "you" as a user, not system-wide
<clem> typically you're modifying a file called ~/.config/monitors.xml
<clem> when you run the DM (login screen), it runs as root so it's using whatever default configuration Xorg has
<clem> you should still be able to define an /etc/X11/xorg.conf
<clem> or you can resort to calling xrandr in /etc/mdm/Init/Default
<clem> there's info at https://wiki.ubuntu.com/X/Config/Resolution
<clem> you can also edit /usr/share/X11/xorg.conf.d/*.conf instead of modifying /etc/X11/xorg.conf
<PcMojo> would the conf.d be the preferred method or Init/Default?
<PcMojo> I ran on script inIt/ default that was supposed to fix it and no joy.
<clem> either way
<clem> the conf is Xorg's conf... whereas Init/Default is what's executed by MDM after Xorg is launched
```

**Comment by clefebvre** [comment]
http://segfault.linuxmint.com/2015/08/configuring-the-mdm-login-screen-for-multiple-monitors/
