### ISSUE TITLE
The volume/brightness indicators reappear each time you change something and it doesn't appear as a smooth animation

### ISSUE THREAD

**Issue by GiedriusS** [linuxmint/Cinnamon#3420]
OS: Arch Linux GNU/Linux
Cinnamon version: 2.2.14-2
What am I doing: changing the sound / brightness level repeatedly using the keyboard shorcut buttons (Fn key + brightness up/down or volume up/down) and cinnamon has binded functionality to them
What happens: the brightness / audio level changes like it should _but_ it seems that everytime the either level is changed the whole indicator (sorry if this is the wrong word) gets redrawn/reappears and it doesn't look like a smooth animation
What should happen: I think the indicator/cinnamon shouldn't redraw the whole indicator to show a new, changed level of brightness or audio volume. Basically, it should wait a few seconds after a change to see if a user changes it again too and show it in the same instance
I uploaded a video: https://www.youtube.com/watch?v=LoaxRH11Pu8&feature=youtu.be
It seems that it happens more often with the audio level indicator

**Comment by dalcde** [comment]
Fixed in git
