### ISSUE TITLE
Cinnamon Menu does not respect System Font Settings

### ISSUE THREAD

**Issue by stefan-niedermann** [linuxmint/Cinnamon#3421]
If i set the system fonts to 14pt, the cinnamon menu keeps the same font size as before. I don't know a way to manipulate the font-size yet.

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html
