### ISSUE TITLE
Modal dialogs don't get focus when open

### ISSUE THREAD

**Issue by liamdawe** [linuxmint/Cinnamon#3422]
Something has been really annoying me lately.

When you open a dialog box (i think they are what you call "modal") in something like gimp to save an image, or even say chrome to save an image or file the dialog box doesn't have focus.

So, if i want to re-name something I have to manually click into the filename box to give it focus.

It's a real usability issue that never used to happen, so it's only come about since Mint 17 from what I can remember.

**Comment by diwu1989** [comment]
I'm also seeing this problem, in Hipchat join chat dialog

**Comment by diwu1989** [comment]
@mtwebster if you install hipchat, you'll be able to reproduce the issue when u do control T.

Please fix this, I use linux mint + hipchat professionally at work and this problem is becoming more and more frustrating everyday.

**Comment by liamdawe** [comment]
It's ruining my workflow too when I use gimp multiple times a day, and export with different filenames a lot.

Not having focus in the save window as it's supposed to is a constant annoyance.

**Comment by JosephMcc** [comment]
@liamdawe I can't reproduce this. If I use the hotkeys to save, save as, or export in gimp, the dialog opens with the image name focused at the top. I can just start typing to set the name or hit Enter to save. It works exactly as expected.

**Comment by mtwebster** [comment]
Same here, cannot reproduce - 

It's possible you've some crazy combination of settings, perhaps try resetting wm-related settings:

gsettings reset-recursively org.cinnamon.muffin
gsettings reset-recursively org.cinnamon.desktop.wm

Then logout/in or restart cinnamon.

**Comment by liamdawe** [comment]
Gaaah went to video the bug, and now it's not doing it for me, so closing.

**Comment by brouillon** [comment]
I found this issue when i search a solution of a annoying feature. 

The case is nearly the same as mentioned, for reproduce : 
With geany / firefox / ... when saving filename is selected and have focus you can rename it --> cool !
But if you change the path with mouse,  filename is always selected but haven't the focus, can't modify.
It's a feature ?
IMHO What is missing is :
- if filename is selected, typing will rename the file even if i have change the path (it's what i prefer ;) )
- or the filename have to lose selection after changing path

Otherwie is there an hotkey to focus the filename field ? it seems ctrl+L is ok, sometime need twice

Sorry for my poor english spoken and for digging this issue.

**Comment by anydoby** [comment]
This issue is bugging me for a long time with cinnamon. It's especially annoying in Eclipse, it occurs almost every time a dialog is opened. Also happens in the file explorer (Nemo) when deleting files, you have to click confirmation with a mouse. With XFCE i did not see this.

**Comment by purefan** [comment]
+1 here, crazy that this has been going on for so long
