### ISSUE TITLE
dark theme variant window border

### ISSUE THREAD

**Issue by dzklaim** [linuxmint/Cinnamon#3424]
System: arch linux, gtk 3.12.2, cinnamon 2.2.14

if some application is supposed to use the dark theme variant, Cinnamon respects the controls but does not respect the dark theme window border (image below).

![screenshot from 2014-08-10 10 33 02](https://cloud.githubusercontent.com/assets/1281848/3874213/3bad0856-213e-11e4-922e-20a9ad1a4859.png)

**Comment by JosephMcc** [comment]
This should be fixed now by https://github.com/linuxmint/muffin/commit/43169065857c7bcfa9707ca69aafa693bc04c6cb
