### ISSUE TITLE
window ordering with 'prevent focus stealing' and 'always on top' 

### ISSUE THREAD

**Issue by cuprayon** [linuxmint/Cinnamon#3432]
Issue:
When 'prevent focus stealing' is set, the 'window focus mode' is set to 'sloppy' or 'mouse', and one or more windows is set to 'always on top', any newly launched window is opened below _all_ other windows on the desktop. 

Compare this to when 'prevent focus stealing' is set and the 'window focus mode' is set to 'click', when the behavior is closer to correct; meaning a new window opens below any 'always on top' windows and the focused window, but above all other windows. 

Personally, I'm used to and prefer focus stealing prevention that has _zero_ effect on the window ordering. (Meaning that new windows will launch above the focused windows, just without taking focus.) Regardless, the issue above is clearly improper behavior.

**Comment by dalcde** [comment]
Not reproduced

**Comment by Vahan86** [comment]
@cuprayon, is this still an issue for you in Cinnamon 3?

**Comment by Vahan86** [comment]
@JosephMcc, can we close the issue?
