### ISSUE TITLE
Auto-remount network drives during connection change

### ISSUE THREAD

**Issue by cjermain** [linuxmint/Cinnamon#3434]
When using a number of ssh folders in nemo that are mounted, it would be a nice enhancement to have those folders automatically remount when a network connection changes. This is an annoyance when my wireless network changes or a VPN service is started. Currently they just hang if not unmounted.

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html
