### ISSUE TITLE
[REQ] Integrate Online Accounts

### ISSUE THREAD

**Issue by ghost** [linuxmint/Cinnamon#3439]
Give users the ability to integrate online accounts (eg. Google, Facebook, Twitter) into Cinnamon. Give user the option to display desktop notifications for these services. Where calenders are available sync them to Cinnamon and display events/meetings in the calendar applet. When a calendar event comes due display notification giving the user the ability to Snooze or Dismiss the event (This is similiar to the functionality currently available in Gnome and Unity.)

**Comment by feren** [comment]
Now available.
