### ISSUE TITLE
Cinnamon deletes all entrys in the Menu-Applet after change something

### ISSUE THREAD

**Issue by andrk** [linuxmint/Cinnamon#3440]
Cinnamon --version: 2.2.16

I've installed a game using Wine.
After the installation i cut out the game-shortcut and put it from Wine to Games
After paste the shortcut in Games Cinnamon does a restart, automatically
I opened the Menu and all entrys were gone
I want to open the "Menu-Editor" but after i click on "Open the Menu Editor" nothing happens

Resetting everything to Default does not take any effect

**Comment by Neutrino-Sunset** [comment]
I have just done the exact same thing. Thankfully the steps described above enabled me to recover my cinnamon configuration but I did not appreciate seeing my entire start menu destroyed and the extra hours work to fix it as a result of a simple change in the menu editor.

One of the main points of a having a gui is that is constrains the user to only performing those operations that are valid. The whole point of the Menu Editor is to allow users to move icons around in the menu. So for it to be the case that using the Menu Editor to move an icon from one location to another results in totally trashing your entire start menu configuration is unsatisfactory to say the least.

Imo this issue should be opened and marked as a bug.
