### ISSUE TITLE
IBus engines list accumulates multiple copies of US English

### ISSUE THREAD

**Issue by quickdudley** [linuxmint/Cinnamon#3441]
I'm filing this bug with Cinnamon rather than iBus because it is not present in other desktop environments.
This is what I get when I run "dconf dump /desktop/ibus" with everything set correctly:
[general]
engines-order=['xkb:mao::mao', 'pinyin']
preload-engine-mode=0
use-system-keyboard-layout=true
preload-engines=['pinyin', 'xkb:us::eng', 'xkb:mao::mao']
preload-engines-inited=true
version='1.5.5'

[engine/pinyin]
ShiftSelectCandidate=false
FuzzyPinyin_N_L=false
FuzzyPinyin_G_K=false
CorrectPinyin_ON_ONG=true
FuzzyPinyin_F_H=true
FuzzyPinyin=false
CorrectPinyin_UE_VE=true
FuzzyPinyin_IN_ING=true
FuzzyPinyin_ING_IN=true
MinusEqualPage=true
CorrectPinyin=true
DoublePinyin=false
FuzzyPinyin_CH_C=false
FuzzyPinyin_ANG_AN=true
CorrectPinyin_IOU_IU=true
FuzzyPinyin_L_N=true
FuzzyPinyin_K_G=true
CommaPeriodPage=true
FuzzyPinyin_L_R=false
FuzzyPinyin_R_L=false
CorrectPinyin_GN_NG=true
FuzzyPinyin_Z_ZH=true
LookupTablePageSize=5
FuzzyPinyin_EN_ENG=true
CorrectPinyin_MG_NG=true
CorrectPinyin_V_U=true
InitFull=false
CorrectPinyin_UEN_UN=true
CorrectPinyin_UEI_UI=true
FuzzyPinyin_S_SH=true
FuzzyPinyin_SH_S=false
IncompletePinyin=true
FuzzyPinyin_ZH_Z=false
InitSimplifiedChinese=true
InitChinese=true
FuzzyPinyin_ENG_EN=true
LookupTableOrientation=0
FuzzyPinyin_H_F=false
FuzzyPinyin_AN_ANG=true
FuzzyPinyin_C_CH=true
AutoCommit=false
InitFullPunct=true
SpecialPhrases=true
DoublePinyinSchema=0

[panel]
lookup-table-orientation=0

Every time I reboot or reset the cinnamon session: the entry "general/engines-order" changes such that any instance of "xkb:mao::mao" becomes "xkb:us::eng", and an additional copy of "xkb:us::eng" is appended to the end of the list. The instances of "xkb:us::eng" accumulate and are visible on the input method selector, but only one is visible in the ibus preferences.

**Comment by Vahan86** [comment]
@quickdudley, is this still an issue for you with Cinnamon 3.2?

**Comment by quickdudley** [comment]
I will test it in the weekend: I don't have cinnamon installed at the moment.

**Comment by Vahan86** [comment]
@JosephMcc, can we close this issue?
