### ISSUE TITLE
Steam system info text copy pop-up ends-up in top left corner

### ISSUE THREAD

**Issue by silviucc** [linuxmint/Cinnamon#3444]
When attempting to copy information from the Steam system information window, after right clicking, the pop-up that would allow the user to "Copy", "Select all" or "Copy all information to clipboard" shows up in the top left corner of the screen but the various options cannot be clicked on.

How to reproduce:

1) Open the linux version of Steam
2) Go to Help -> System Information
3) right-click in the are where the system information is shown

**Comment by Vahan86** [comment]
@silviucc, is this still an issue for you with Cinnamon 3.2?

**Comment by silviucc** [comment]
Hi,

I don't use Cinnamon anymore. Sorry.

I'll close the issue.
