### ISSUE TITLE
USB sticks become read-only

### ISSUE THREAD

**Issue by nix666** [linuxmint/Cinnamon#3446]
Hi there Mint folks

There is an issue with Mint 17 Cinnamon, where every now and again I try to copy paste from another drive to a USB stick - Nemo gives the error :

    Error while copying to "USB stick". The destination is read-only. 

What I know already :

1. This happens only in the Cinnamon edition.
2. I've tried multiple USB sticks from different manufacturers - same result.
3. I use the USB image formatter and writer tool to format and make bootable sticks.
4. The stick does infact not become read-only , because I can write / copy to it via the command line without issues.
5. I have had suggestions that this has to do with Nemo - Therefore only happens in Cinnamon.

Can anyone shed some light on the issue ? I would like to get the attention of Clem and the team on this, so if anyone knows
about an existing bug report/ thread on this, please advise.

Thanks in advance

**Comment by tenoreamer** [comment]
I am running Archlinux with kernel 3.17.6 and using Cinnamon 2.4.5 with Nemo 2.4.4. It's so bad that the bug has persisted till now.

**Comment by gabrielaraujof** [comment]
Actually, @anandrkris , the exact command should be:
`sudo nano /etc/fstab`  and then add the line `/dev/sdc /mnt/usb auto user` at the end of fstab file.

**Comment by pradacr** [comment]
Hi gabrielaraujof I added the line at the fstab file and now I can read/writte the SD memory, but the problem is that I get a message to mount a drive when I start Linux. I am using Linux Mint 17.2. Thanks

**Comment by tacojones** [comment]
Yeah, be careful with adding that to fstab. A user might not be able to boot to a desktop afterwards. If the USB stick is read only, try rebooting first.

**Comment by oislone** [comment]
i use archlinux.
chage /etc/fusc.conf 
modify 
#user_allow_other 
to 
user_allow_other 

save. relogin. is OK.

**Comment by RafalSkolasinski** [comment]
It looks like bug is fixed in Linux Mint 18 Cinnamon. Why the bugfix wasn't backported to Mint 17?

**Comment by JosephMcc** [comment]
Glad it seems fixed. This issue belongs to Nemo and not Cinnamon anyway.

**Comment by aitorbk** [comment]
Nice to see it is fixed.  I have Linux Mint 18 and have the problem... :(

**Comment by theoar** [comment]
I have the same problem on LMDE, Cinnamon 3.2.1.

**Comment by aitorbk** [comment]
The solution is "sudo chmod 777 /media/<user>

Do that, and the either restart nemo or reboot the computer.

**Comment by pradacr** [comment]
Hi aitorbk, I made as you did "sudo chmod 777 /media/julio"
Restarted nemo and stayed read only
If I reboot the pc, does it keep the command for the next session?
Would it be required each time a media is inserted?

**Comment by aitorbk** [comment]
Strange.. it should keep as this:
itor@Mint-McTEa /media $ ls -latr
total 20
drwxrwxrwt   2 root root 4096 May 11  2016 nomachine
drwxr-xr-x   5 root root 4096 Jun 10 17:17 .
drwxr-x---+  2 root root 4096 Jun 10 17:23 root
drwxr-xr-x  25 root root 4096 Oct 27 11:53 ..
drwxrwxrwx+  2 root root 4096 Nov 17 18:15 aitor

I just connected a usb stick:

aitor@Mint-McTEa /media $ cd aitor
aitor@Mint-McTEa /media/aitor $ ls -latr
total 24
drwxr-xr-x   5 root  root   4096 Jun 10 17:17 ..
drwxrwxrwx+  3 root  root   4096 Nov 18 15:54 .
drwxr-xr-x  17 aitor aitor 16384 Nov 18 15:54 EAGET


And it should be a permanent solution.
Is it working for you?

**Comment by pradacr** [comment]
Hi Aitorbk, I think my problem is with file managers like Nemo and Nautilus, not with the terminal.
I can create and delete with terminal, but not with file manager even if I open them using sudo.
I'm a Linux user so I even find it difficult to follow you on the terminal :o(

julio@E6410 /media $ ls -latr
total 12
drwxrwxrwx   3 root  root  4096 Aug  4 09:20 .
drwxr-xr-x  23 root  root  4096 Nov 11 22:03 ..
drwxrwxrwx+  3 julio julio 4096 Nov 18 10:06 julio

**Comment by jontis** [comment]
Same issue here. USB (previously used as live boot drive) formatted with several file systems.
File Manager in Linux Mint 18 says its read only, but I have no problem copying to it using the terminal.
Formatting the USB does not help and is probably not the issue.

**Comment by aitorbk** [comment]
Use my solution and it will be solved.

The problem comes, I think, because the permission levels are ok for terminal, but Nemo/Nautilus run on a different privilege level.. so as nemo is running as root it fails.

On a terminal:
Go to /media

Then do "sudo chmod 777 /media/"user"   , user being the name of your user.

After that, reboot nemo or simply reboot your computer.

The problem will almost for sure be fixed/

**Comment by pradacr** [comment]
Hi Aitorbk, thanks for helping me again.

I did just as you said:

julio@E6410 / $ cd media
julio@E6410 /media $ ls
julio
julio@E6410 /media $ sudo chmod 777 /media/julio
[sudo] password for julio: 
julio@E6410 /media $

After that, reboot nemo (using Cinnamon shortcut or the terminal as root)

But Nemo and Nautilus continue with the problem as if nothing was done.  :o(

Note: if I reboot the PC with the SD card in, Nemo will work fine. But that is an impractical workaround of this problem.

**Comment by oniongarlic** [comment]
chmod 777 is not a solution, it makes it world readable and writable and is a serious security issue.

**Comment by cesc1989** [comment]
I tried setting permissions on the drive but it didn't work.

Restarted Nemo with `nemo -q` in a terminal window and then the message was gone even after unmounting-mounting the drive.

**Comment by cocokuif** [comment]
Set the action to be taken when inserting removable media to : Do Nothing.
System settings--> Preferred applications--> removable media.

That solved the problem for me

**Comment by b-schliessmann** [comment]
Hello

As it appears to me: Copying files using nemo yields the error message "the target is read only". After that, the copying dialogue is stuck while "preparing" and must be closed manually.

This is definitely **no** permissions issue; copying using the terminal and cp works just fine. Also checked the permissions of /media/<user>/, the above mentioned "solution" doesn't help.

**What does work for a certain time, however, is killing nemo (killall nemo).** After restarting nemo, the above-mentioned error doesn't appear and the files are copied successfully. Most probably a nemo bug.

Using nemo 3.2.2+serena with Mint Cinnamon (18.1).

An appeal to you guys: **Please refrain from suggesting and copy-pasting manipulations you don't understand**, such as manipulating /etc/fstab (interfering with automount and potentially with system boot) or doing "chmod" 777 (unnecessary privileges). This can cause serious pain for other users trusting your judgment.

Best regards

Björn

**Comment by M-Klekowicki** [comment]
So generally, after 4 years this is still happening (Mint 19 Tara here, and so far, no workaround I tried worked). Isn't it getting a little ridiculous at this point? This is a very serious issue as it affects one of the basic functionalities required from a modern desktop operating system. Not taking this seriously will be perceived as trumendously incompetent by any user coming from other platforms.
