### ISSUE TITLE
Alt-F2 tab completion killing commands in 2.3.0-20140811040020 nightly

### ISSUE THREAD

**Issue by mpaik** [linuxmint/Cinnamon#3447]
Alt-F2 tab completion killing commands in 2.3.0-20140811040020 nightly

Reproduce:

emacs <file>
Tab to raise menu - buffer in text box replaced by file selected, not just the string that was being tab completed.

**Comment by dalcde** [comment]
Reproducable by typing gedit-tab-space-tab.
