### ISSUE TITLE
Cinnamon x-lets - Support for Fonts

### ISSUE THREAD

**Issue by anandrkris** [linuxmint/Cinnamon#3450]
Lest I forget the discussion in IRC - Adding this request here. ...

Currently, I hear, that desklets and applets do not support exhaustive Font selection mechanism. 
For instance, Sticky Desklet font list is limited to a has hard-coded values and does not reflect the **installed** fonts. Many other x-lets could make use of this - especially text driven x-lets like Quote of the Day, Gpaste, etc

Ideally, x-lets settings should be able to invoke support Fonts using the *'Pick a Font'* dialog and support the selections (Font type and size). Configuration for other attributes like Font Color, etc would be a welcome addition. :smile: 

![screenshot-from-2012-11-18-115042 1](https://cloud.githubusercontent.com/assets/4663298/4055050/ee914af0-2d9a-11e4-978f-183329c81771.png)

https://github.com/lestcape/Sticky-Notes/issues/8

X-let developers - Please add anything you might want to say from a development perspective....

**Comment by anandrkris** [comment]
@collinss - In case you want to pick this up as part of Settings widgets...

**Comment by collinss** [comment]
There is now a font chooser available to the xlet settings (as well as several other new widget types). If you are on the latest git version, you can try them all out by adding the settings-example applet.

**Comment by lestcape** [comment]
@JosephMcc can you close this thread?

**Comment by lestcape** [comment]
Thanks @collinss
