### ISSUE TITLE
cinnamon-settings power crash

### ISSUE THREAD

**Issue by dimti** [linuxmint/Cinnamon#3453]
[dimti@arch-usb-stick ~]$ cinnamon-settings power
Python module
Could not find bluetooth module; is the cinnamon-control-center package installed?
Loading Power module

(cinnamon-settings.py:2781): libupower-glib-WARNING **: Couldn't connect to proxy: Не удалось подключиться к: Нет такого файла или каталога

(cinnamon-settings.py:2781): GLib-GIO-CRITICAL **: g_dbus_proxy_call_sync_internal: assertion 'G_IS_DBUS_PROXY (proxy)' failed
Ошибка сегментирования (core dumped)

Im use ArchLinux.
Cinnamon launched in chroot.
[dimti@arch-usb-stick ~]$ pacman -Q | grep "cinnamon"
cinnamon 2.2.16-1
cinnamon-control-center 2.2.10-3
cinnamon-desktop 2.2.3-1
cinnamon-menus 2.2.0-1
cinnamon-screensaver 2.2.4-1
cinnamon-session 2.2.2-1
cinnamon-settings-daemon 2.2.4-2
cinnamon-translations 2.2.4-1

[dimti@arch-usb-stick ~]$ pacman -Q | grep "upower"
upower 0.99.0-2

cinnamon-session - not launched. I unable to use cinnamon on my pc where using chroot environment.
How to resolve this problem?

**Comment by pixunil** [comment]
The power module of cinnamon settings was redesigned in 2.6. (nightly) Can you please check if this persists?

**Comment by dimti** [comment]
Hello
I unable to test this - my arhclinux packages not updated cinnamon to 2.6 and i unable install from aur packages (cinnamon-git, cinnamon-desktop-git - build crach https://github.com/linuxmint/cinnamon-desktop/issues/48)

**Comment by dalcde** [comment]
Can you try now?
