### ISSUE TITLE
Sound menu needs extra menu

### ISSUE THREAD

**Issue by tylery71** [linuxmint/Cinnamon#3459]
LM 17 Cinnamon (Ubuntu Based) 
I5 Intense PC 2 (similar to mintboxes)

This created a workaround and identifies the problem:
http://www.fit-pc.com/forum/viewtopic.php?f=121&t=5446

The problem is the audio is cut from the audio jack while having a HDMI connected.
To fix, you need to install pavucontrol and go into config and select "Analog Stereo Output + Digital Stereo (IEC958) Input".
This is impossible with the standard sound menu.
If you click on the only option in output in the sound menu after changing the config, it defaults back and ruins (garbles) the audio again.

pavucontrol
![pavucontrol](https://cloud.githubusercontent.com/assets/4926565/4108857/a5bce59a-31dd-11e4-930a-b66326c2800d.png)

Sound menu
![sound](https://cloud.githubusercontent.com/assets/4926565/4108855/96abf6c2-31dd-11e4-846f-44790cf2a15c.png)

**Comment by ManIVIctorious** [comment]
The sound settings have been reworked for cinnamon 3.0, does this issue still exist in current cinnamon versions?
