### ISSUE TITLE
Notification bubbles get in the way

### ISSUE THREAD

**Issue by harogaston** [linuxmint/Cinnamon#3465]
The problem:
Notification bubbles - which appear in the right hand corner - from WiFi connected/disconnected, song change, Pydgin contact online/offline, etc. Do block the way of what resides behind, this should not be happenning.

The solution:
For a solution I looked into ubuntu's way of dealing with notifications. They have come up with a pretty extense and ~~concise~~ *detailed* document describing the correct (expected) behaviour and appearence of this notification bubbles.
[Here is the document](https://wiki.ubuntu.com/NotifyOSD#Bubble_appearance_and_layout) ->> I REALLY RECOMMEND YOU TAKE A LOOK AT IT!

The proposal:
Is there any room/willingness to port/implement this in Cinnamon?

I'll be happy to provide you with more info/comments if you require so.
Sincerely,
Gastón Haro.

**Comment by anandrkris** [comment]
Sharing some links I came across -
https://wiki.gnome.org/Design/OS/Notifications/Redux
https://developer.gnome.org/gio/stable/gio-GNotification.html

**Comment by harogaston** [comment]
@dalcde This has been implemented in LM 17.1 at least now notification blur and become translucent when you mouse-hover them. I'll mark this as closed.

**Comment by cifkao** [comment]
@harogaston I don't think this solves the issue. You can hover over the bubble to see what's beneath it, but you still cannot interact with that part of the screen. For example, when you get the song change notification, the only thing you can do to get rid of the bubble is a) wait until it disappears, or b) click it, which takes you to the music player. There should be a way to simply close a notification bubble (e. g. an X mark).
