### ISSUE TITLE
Blur effect for transparent menus

### ISSUE THREAD

**Issue by harogaston** [linuxmint/Cinnamon#3466]
It all comes from a 2012/2013 post on forums.linuxmint.com.
The post:
[Cinnamon effects and visual transparency](http://forums.linuxmint.com/viewtopic.php?f=208&t=97101)

The idea:
Adding a blur effect to transparent menus/panels/windows. Because transparency without blur just doesn't seem to work in most cases.

The solution:
They seem to be using [ClutterEffect](https://developer.gnome.org/clutter/stable/ClutterEffect.html) and [ClutterBlurEffect](https://developer.gnome.org/clutter/stable/ClutterBlurEffect.html) to achieve this.

The proposal:
Is there any room/ people interested to bring this into Cinnamon?

I'll be happy to provide you with more details if needed.

Finally I include a few images of the work that was done in 2012:
# ![iqvij](https://cloud.githubusercontent.com/assets/5424205/4141425/28ec9ede-33ae-11e4-8346-62556c67f363.jpg)
# ![21z6b](https://cloud.githubusercontent.com/assets/5424205/4141424/28e89104-33ae-11e4-8c6d-a5da1a93db45.jpg)

![6nhwx](https://cloud.githubusercontent.com/assets/5424205/4141426/28f3c998-33ae-11e4-85be-c353d54ad43f.jpg)

**Comment by jtflynnz** [comment]
This would be a neat feature to see implemented; after playing around with it, I was slightly disappointed to see that this interacts somewhat poorly with transparency. It would be interesting to see what theme-makers would be able to develop with a fully functional form of this, is there any chance of this being revised for more efficient use, even if it is down the road a ways?

**Comment by harogaston** [comment]
@anandrkris you should address @dalcde regarding that https://github.com/linuxmint/Cinnamon/issues/3466#issuecomment-59180841

**Comment by AdmiralAnimE** [comment]
I would love this to be fixed/implemented. At least simple blur, thats probably enough. It gives a lot of possibilities for themes and it looks very nice. As other people are saying - partial transparency is very popular but it's not nearly as effective when there is no blur.
Currently the bump maps are extremely buggy and the blur doesn't work.

**Comment by harogaston** [comment]
I "fixed" it. I just installed openSUSE with KDE. It is an excelent desktop
where transparency and blur work perfectly.

**Comment by AdmiralAnimE** [comment]
Yea I know, KDE 5 is nice and can be more beautiful at the moment - much
more themes and possibilities. But for me Cinnamon is simpler and easier,
and there are a few things that are possible here but not in KDE.
Overall it's the small things that matter when choosing between a few
different but very similar things, in this case desktop environment /
distribution.

2015-10-29 13:15 GMT+02:00 Gastón Haro <notifications@github.com>:

**Comment by Vahan86** [comment]
@JosephMcc, please see mtwebster's comment https://github.com/linuxmint/Cinnamon/issues/3466#issuecomment-54699269 

Can we close this issue?

**Comment by Vahan86** [comment]
@JosephMcc, can we mark this issue as a feature request?

**Comment by feren** [comment]
@mtwebster Could this feature be unlocked for the panel in 3.0? Tried it and it didn't work...

**Comment by mfreeman72** [comment]
Agreed, @feren I cannot get this feature to work in Cinnamon 3.2. I love transparency in themes, but I hate when what's the background interferes visually with what's in the menu. Blur is a must!

**Comment by harogaston** [comment]
I will close this, as I am not longer interested.

**Comment by ijash** [comment]
i am supporting this idea +1.

**Comment by mfreeman72** [comment]
I really wish this issue wasn't closed. Cinnamon is a great desktop, but when any sort of transparency is enabled, it looks terrible. It desperately needs a blur effect for transparent menus! And no, I'm not going to install KDE

**Comment by aragubas** [comment]
> I really wish this issue wasn't closed. Cinnamon is a great desktop, but when any sort of transparency is enabled, it looks terrible. It desperately needs a blur effect for transparent menus! And no, I'm not going to install KDE

Same, KDE runs like crap on my machine, and it has a Nvidia 550TI...
