### ISSUE TITLE
clock in calendar applet does not update it's time

### ISSUE THREAD

**Issue by brianjmurrell** [linuxmint/Cinnamon#3468]
With cinnamon 2.2.x on Fedora 20 I am noticing that the clock in the Calendar applet is not updating.  It will update if I open it's configuration settings and adjust the display format but it will only update that one time and not continue to update.  Any time I adjust the configuration it will update just that once but not again.

This happens with both the stock Calendar applet as well as the World Clocks applet.

**Comment by Vahan86** [comment]
@JosephMcc, please see the comment posted above.
