### ISSUE TITLE
lockscreen widgets/applets/extension/younameit

### ISSUE THREAD

**Issue by mmerlone** [linuxmint/Cinnamon#3469]
Hi,

Would be nice to be able to add content to lock screen, replacing a screensaver. Some suggestions:
- Weather information;
- RSS News;
- Zabbix/Nagios dashboard;
- Picture gallery;
-Sky is the limit as always.

Thanks for Cinnamon, made me compiz-free. :)

**Comment by leetwanker** [comment]
I'd love to see this feature added also.

**Comment by JosephMcc** [comment]
https://github.com/linuxmint/Cinnamon/issues/3369
