### ISSUE TITLE
Nouveau driver crash

### ISSUE THREAD

**Issue by dimti** [linuxmint/Cinnamon#3475]
Hi

Today my cinnamon crashed two times. 

I'm work with my apps and cinnamon crashed.  X11 stopped. Startx go to freeze my system. 

I'm have screenshot my console after crash
![tmp_3326-img_20140908_174719-878178566](https://cloud.githubusercontent.com/assets/582144/4186304/aa070d7e-375f-11e4-93f2-3d9a08fc62bf.jpg)

**Comment by Eirikur** [comment]
I've seen very similar messages (failed to idle channel) on Nouveau with my GeForce 660.

**Comment by Vahan86** [comment]
@dimti, does this issue still occurs in Cinnamon 3.0?

**Comment by dimti** [comment]
Hello, i try to checked it into two-fev days

**Comment by clefebvre** [comment]
Hi,

This looks like an Xorg issue more so than Cinnamon. If Cinnamon crashed you'd still have a working mouse pointer for instance.
