### ISSUE TITLE
JavaEmbeddedFrame visible on taskbar

### ISSUE THREAD

**Issue by drsood** [linuxmint/Cinnamon#3476]
Reference: [Issue 728](https://github.com/linuxmint/Cinnamon/issues/728)
This was supposedly fixed a long time ago. But I am having this issue with Mint 17 and
java version "1.7.0_65"
OpenJDK Runtime Environment (IcedTea 2.5.1) (7u65-2.5.1-4ubuntu1~0.14.04.2)
OpenJDK 64-Bit Server VM (build 24.65-b04, mixed mode)

Running a java application (eg JDownloader,SelekTOR) displays an additional JavaEmbeddedFrame window and taskbar icon, if the application has a system tray icon and their is no way to hide it unless the system tray icon is disabled from within the application's settings.

**Comment by Zerophase** [comment]
I'm getting this issue as well, when running the Serviio console, and java version "1.7.0_85".

**Comment by Fornax96** [comment]
This issue used to be fixed like I confirmed in 2014, but now it's happening again. I'm not sure what caused the return but it's definitely there: 
![screenshot from 2016-09-15 17-18-00](https://cloud.githubusercontent.com/assets/1247928/18555559/9c8e90dc-7b68-11e6-941a-f9b8a36e90f7.png)

Screenshot was taken with cinnamon 3.0.7 on Linux Mint 18 and openjdk-8-jdk
