### ISSUE TITLE
Missing icons

### ISSUE THREAD

**Issue by GeorgeChalkitis** [linuxmint/Cinnamon#3478]
![selection_501cinnamon bugs](https://cloud.githubusercontent.com/assets/5755827/4208195/e8b0868c-385d-11e4-9a66-5e75585c74fb.png)

There are icons missing.The two of them are shutter and google chrome(working on backround when closed option).
Linux Mint 17 64 all updates applied.

**Comment by JosephMcc** [comment]
Please use https://github.com/linuxmint/Cinnamon/issues/481
