### ISSUE TITLE
Super + <KEY> requires double tapping <KEY> using the pre-made shortcuts

### ISSUE THREAD

**Issue by Nerdy314159265** [linuxmint/Cinnamon#3480]
I discovered this when I wanted to set the Lock Screen keyboard shortcut to Super + L. If I use the premade shortcut then I have to double tap "L" to get the screen to lock and the first "L" is sent through to whatever window was focused before the lock.

However, if I make a custom shortcut for locking the screen, it works as intended. I've also tested this with the Launch the Help Browser to try and confirm it's the pre-made shortcuts and it had the same issue.

**Comment by Vahan86** [comment]
@Nerdy314159265, is this still an issue for you with Cinnamon 3.2?

**Comment by Nerdy314159265** [comment]
I cannot answer that as my laptop that I run Linux Mint with Cinnamon on,
is unavailable at the moment. When I get the chance, I'll update to
Cinnamon 3.2 and confirm the status of the issue.

**Comment by Nerdy314159265** [comment]
Update:

Apparently my copy of Linux Mint refuses to update to a newer version (I think it's so old that the repos are broke). I'm going to say that if no one else is having this issue anymore then you can go ahead and close this issue. If/When I get Cinnamon 3.2 and I'm still having this error, then I'll just comment here for it to be reopened.
