### ISSUE TITLE
Can't adjust brightness with screen locked

### ISSUE THREAD

**Issue by benmccann** [linuxmint/Cinnamon#3487]
fn+f9 and fn+f10 can be used to adjust the brightness on my laptop. However, these don't work as long as the screen is locked. This ends up being very frustrating because if I unplug an external monitor it will lower my brightness to zero and then I have a really hard time unlocking the computer because the screen is off and I can't turn it back on by raising the brightness until I manage to login with the screen off.

I'm using Cinnamon 2.2.16 on an HP Elitebook 850 G1.

**Comment by ACinnamonUserInUK** [comment]
+1.

**Comment by anandrkris** [comment]
This is already possible AFAIK.

https://www.linuxmint.com/rel_rafaela_cinnamon_whatsnew.php

> Note: Brightness and keyboard backlight are now also modifiable via multimedia keys while the screen is locked.

**Comment by anandrkris** [comment]
@JosephMcc - Please close if you agree.

**Comment by JosephMcc** [comment]
I would like a confirmation that this is no longer an issue for the original OP if possible.

**Comment by theSeppi** [comment]
Not the OP, but on my setup it;s working now.
