### ISSUE TITLE
Off-workspace urgency hints result in annoying behaviour

### ISSUE THREAD

**Issue by fish-face** [linuxmint/cinnamon#3489]
An issue that's been in Cinnamon for a while and has been visited several times in the past is what to do when the user takes an action which results in a window requesting attention or setting the urgency hint. See [Pull Request #1392](https://github.com/linuxmint/Cinnamon/pull/1392) and the linked issues.

The annoyance for me is the following: I'm reading IRC or something similar and click a link. I often wish to carry on reading IRC before heading to read the link, and I might want to click more links. However, if the browser is not on the current workspace, this is not possible; depending on the value of the setting in "Windows" either the browser is brought to the current workspace (agh! I like my windows to remain where I put them!) or I get switched to that workspace (noo! I wanted to read more!)

My understanding of the past discussions is that the browser is setting the urgency hint when this happens. Unlike the weaker "requires attention" hint, where it was decided that displaying a highlight in the taskbar sufficed for informing the user, the urgency hint should take immediate action.

I at least find this objectionable, and would prefer the configuration options in the Windows settings page to allow me to make all such WM hints behave in the same way: flashing a notification in the taskbar which, when clicked, would bring me to the other workspace (or else I can just switch myself using the keyboard)

I understand the desire to not flood the settings pages with options. Anticipating that line of thought, perhaps it would be useful considering the most common or reasonable desires (for instance: does anyone really want desires-attention hints to switch windows/workspaces around? I gather that happens whenever an IM program makes a notification, which sounds horrendous.) If it were to be decided that my desires aren't common enough, then I still think it's annoying enough to warrant a dconf key to configure it.

**Comment by icarter09** [comment]
@fish-face has your issue been addressed in Cinnamon 4.2.4?

**Comment by fish-face** [comment]
I switched to gnome quite a while ago so it will be a while before I can
confirm.

**Comment by icarter09** [comment]
@fish-face i will close this issue until you are able to re-test. You can create a new ticket and link to this one if needed. That will also bring the issue to the forefront instead of at the bottom at the issue tracker. If you feel differently, just let me know and I'll reopen this ticket.
