### ISSUE TITLE
Desktop Menu is empty (no apps)

### ISSUE THREAD

**Issue by hexillium** [linuxmint/Cinnamon#3490]
Hello,
Since few days, after that i tried to modify my desktop menu on Linux Mint 17 64 bits with Cinnamon, the Configure menu freezed and i lost all the apps listed in the menu, favorites and quick launch icons. Even searching an app with the search bar doesn't work.

When i right click on Menu, and choose 'Configure', the button 'Open Menu editor' doesn't work. I needed to install mozo to be able to launch it, but it doesn't work because i see full of apps that should be listed (see screenshot) but are not.

![capture du 2014-09-14 13 01 18](https://cloud.githubusercontent.com/assets/8767296/4264062/ffe04910-3c12-11e4-9f77-a87d3cd6320e.png)

Here is the Error result of lg command 

![capture du 2014-09-14 16 21 22](https://cloud.githubusercontent.com/assets/8767296/4264221/b3753aba-3c1a-11e4-882f-1a916175c43f.png)

Is the problem already known ? Is there a fix to this ?

Thanks

**Comment by ricardo-7** [comment]
Thanks!

**Comment by teguhsiswanto87** [comment]
Thanks, had same issue,
