### ISSUE TITLE
Hot Corner improvement

### ISSUE THREAD

**Issue by gilbertohasnofb** [linuxmint/Cinnamon#3492]
Hello all,

I'd like to suggest a little improvement for the hot corners. I am currently using Mint 17 (Cinnamon 64-bit) and I set my top right corner to "Show all windows" (the default suggestion, though off by default). It works wonderfully well, but it has an annoying behaviour: when you have only a single window opened and use the hot corner "show all windows" to close it, Mint should automatically exit "show all windows" since there is nothing else to be shown! The current behaviour is confusing for new users and annoying for experienced ones, since suddenly the panel disappears and the desktop dims and I need to touch that hot corner once again to deactivate it (or press the ESC key). Also, this hot corner shouldn't be active when no windows are opened (for the same reasons as above), in case the user accidently touches it.

Best,
Gilberto

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html

**Comment by gilbertohasnofb** [comment]
> Your job is done and we'll take it from here :)

Great, many thanks.
