### ISSUE TITLE
Network control panel only shows the v4 IP address.

### ISSUE THREAD

**Issue by hobarrera** [linuxmint/Cinnamon#3493]
The network control panel only shows the v4 IP address and not the v6 one. As a result, users with no IPv4 connectivity need to use the terminal to get their current IP address (or to even know if they're getting one).

**Comment by Vahan86** [comment]
@hobarrera, is this still an issue in Cinnamon 3.0?

**Comment by Vahan86** [comment]
@JosephMcc, can we close this issue?
