### ISSUE TITLE
[Bug] (cinnamon:751): Clutter-CRITICAL

### ISSUE THREAD

**Issue by WolleTD** [linuxmint/Cinnamon#3496]
Found my log spammed with Clutter-CRITICAL messages.
Checked for #3136, but it's not related.

```
slim[417]: (cinnamon:751): Clutter-CRITICAL **: clutter_text_get_editable: assertion 'CLUTTER_IS_TEXT (self)' failed
slim[417]: (cinnamon:751): Clutter-CRITICAL **: clutter_text_get_text: assertion 'CLUTTER_IS_TEXT (self)' failed
slim[417]: (cinnamon:751): Clutter-CRITICAL **: clutter_text_set_text: assertion 'CLUTTER_IS_TEXT (self)' failed
```
Error seems to come from something music/sound related. It only appears while some music is playing in a player using the media display function. (tested Spotify and VLC). Stops when music is paused.

**Comment by dalcde** [comment]
Do you have any third party applets installed?
