### ISSUE TITLE
Unable to mount (iPhone) crash

### ISSUE THREAD

**Issue by Brandantl** [linuxmint/Cinnamon#3503]
Unable to mount (in my case iPhone), every now and again when connecting my phone to the USB I have an error unable to mount. Normally this is fine and you click 'OK' and move on.

But sometimes it freezes then a window pops up '' has stopped responding, force quit or wait.

If you force quit then cinnamon restarts, at least the desktop manager,  and you have a different theme style changes. Nothing else changes and the system runs fine afterwards besides the older window style and icons. 

Linux brandan-G73Jw 3.13.0-24-generic #47-Ubuntu SMP Fri May 2 23:30:00 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux 

Linux Mint 17 w/ cinnamon.

Image of the Desktops Style change 
![screenshot from 2014-09-19 14 25 20](https://cloud.githubusercontent.com/assets/6909044/4342367/ec71682a-4043-11e4-95b8-c9263b8e46a3.png)

![screenshot from 2014-09-19 14 31 41](https://cloud.githubusercontent.com/assets/6909044/4342406/6fa72626-4044-11e4-9686-486b26a78371.png)

**Comment by ManIVIctorious** [comment]
Is this still an issue in cinnamon 3.0?

**Comment by Vahan86** [comment]
I have similar but not the same issue when want to connect my Samsung mobile phone to my computer. After connecting the system opens a lot of modal windows with "unable to mount" message. After closing the windows, they open again and again. I will send printscreen of what's happening in my case.
@JosephMcc, should I open separate Issue for this?

**Comment by JosephMcc** [comment]
I would say so. Your issue doesn't seem quite the same.
