### ISSUE TITLE
Allow one workspace per display

### ISSUE THREAD

**Issue by s3lph** [linuxmint/Cinnamon#3507]
Currently, an second monitor shares the workspace with the first one. I'd like to see the feature that each display has its own workspace(s), instead of sharing one big.

This could come in handy e.g. if someone has to hold a presentation and plugs his/her laptop to a beamer. Now, as I prefer the Reference View feature of Impress (laptop screen shows current slide, nect slide and a menu, external shows the current slide in full screen), I don't want to mirror the screens. Now I need to arrange the screens on their common workspace, which looks ugly, and can cause some problems (#3504) . If there were the possibility to let each screen have its own workspace, some situations could be much better.

PS: I think this once was possible in older versions of GNOME, but they removed it in GNOME 3 and therefore it's missing in Cinnamon. But the GNOME dev's seem not to want to readd this.

**Comment by pstephenwille** [comment]
+1

**Comment by davidzhuo1** [comment]
+1

**Comment by GonzaloRizzo** [comment]
+1

**Comment by cristiadu** [comment]
+1

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html
