### ISSUE TITLE
keyboard shortcuts ignore alt modifier (perhaps only on the menu button applet)

### ISSUE THREAD

**Issue by calestyo** [linuxmint/Cinnamon#3511]
From: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=762368

Hi.

I have the following problem with the keyboard shortcuts

Switch to workspace 3 is set to: F3
Menu button is set to Alt+F3

However, when I press F3, the menu opens at the menu button, while when I
press Alt+F3, nothing happens at all.

May I add:
It seems that this doesn't happen with all shortcuts, e.g. I've set
Alt+F3 on the "Toggle Window shade status", while F3 on the "Switch to
workspace F3" and that works for both cases.
Maybe the "Menu button" shortcut is somehow special, and this is perhaps
an upstream issue.

Cheers,
Chris.

**Comment by Fantu** [comment]
can someone tell me if is this fully solved in 2.4.3 please?

**Comment by mtwebster** [comment]
Should be:

https://github.com/linuxmint/muffin/commit/f63fcd0905f50fab14f29e21af42b92688dadfb3
https://github.com/linuxmint/muffin/commit/8039f9ec6eb4286228e4317e4e3a32f22cdd0beb
