### ISSUE TITLE
Calendar applet: use default time representation for the locale

### ISSUE THREAD

**Issue by calestyo** [linuxmint/Cinnamon#3514]
Hi.

It's really great that one can configure the time format in your calendar applet :-) ...
May I suggest to use a default value of:
%c     The  preferred  date  and  time  representation  for the current locale.

This should give just the correct representation for everyone on the system.

Cheers,
Chris.

**Comment by AlbertJP** [comment]
It's a confusing string for translators, they often don't understand what %A %B %e, %Y means. I have changed this in the translation for Dutch, but I think many other translators got it wrong too (just copied the text). The translations for Cinnamon are found here: https://translations.launchpad.net/linuxmint/latest/+pots/cinnamon/
You can find this string by clicking your language and searching for %A.

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html
