### ISSUE TITLE
nightly -  On screen keyboard does not show except by installing applet

### ISSUE THREAD

**Issue by brownsr** [linuxmint/Cinnamon#3517]
Development version via PPA to Cinnamon nightly.  Do not appear to be able to launch the on screen keyboard except by loading the applet that toggles the on screen keyboard.  Adding a shortcut key binding does not appear to work.  Similarly turning it on through the separate accessibility settings does not seem to work either.

**Comment by Vahan86** [comment]
@brownsr, is this still an issue for you in Cinnamon 3.0?

**Comment by Vahan86** [comment]
@JosephMcc, can we close the issue?
