### ISSUE TITLE
Better integration between Noise player and sound menu (for Cinnamon 2.4)

### ISSUE THREAD

**Issue by sergioad** [linuxmint/Cinnamon#3525]
Hello I am here to ask you for a better integration between Noise player and sound menu for the upcomming Cinnamon 2.4; I am currently using Cinnamon 2.2 and Noise is allready on the compatible players, this by default: it can be launched with sound menu on the launch player option but before opened the sound menu's icon does not changes to a musical note like with other players and when I open it it does not show the playback buttons or track info can you add better integration for Noise after you release Cinnamon 2.4?

Here is my screenshot of this issue, I hope you can fix it

![captura de pantalla de 2014-09-24 15 19 26](https://cloud.githubusercontent.com/assets/5375145/4395111/239688fc-4428-11e4-8acb-6a2d35850f70.png)

**Comment by pixunil** [comment]
There is no special integration for each player. We use the DBus MPRIS interface, which is used by many players. You can look into the settings / plugin page of your player and look for a entry that sounds like a DBus thing, as some players have this feature disabled as default.

You can also check with an application like dfeet if you see there a bus name of your player - it's the fault of the sound applet then.

**Comment by ManIVIctorious** [comment]
Since the integration with the sound applet doesn't work due to the lack of MPRIS2 support in noise-player this doesn't seem to be a cinnamon issue.
Can this be closed?
