### ISSUE TITLE
focus stealing "false positives"

### ISSUE THREAD

**Issue by calestyo** [linuxmint/cinnamon#3526]
Hey.

Focus stealing is a really nice feature, especially for things like "I enter a password somewhere, while a chat window is created by pidgin, steals the focus and I send my password _D'ohh_".

However, when activating it, there seem to be some "false positives" where the focus doesn't change even though it should.
For example:
When I'm in Firefox, and Ctrl+N to create a new Window, I'd expect that this new window get's the focus (and is in the front of the screen),... however both isn't the case.

Actually the very same thing seems to work with some other applications (e.g. gnome-terminal)... or when in gimp I press Ctrl+O, the file selection dialogue gets the focus.

So not sure whether this is a bug in Firefox then,... or what can be done here.

One way would be to extend the proposal of #2445 to allow windows from the same process to steal the focus.
But OTOH, this could also destroy the positive effect of focus stealing prevention for some other applications (e.g. when using pidgin with one window per conversation).

Cheers,
Chris.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
