### ISSUE TITLE
menu applet: search-filesystem doesn't delete old entries in the menu

### ISSUE THREAD

**Issue by calestyo** [linuxmint/Cinnamon#3537]
Hey.

When one enables search-filesystem for the menu applet (i.e. "Enable filesystem path entry in search box") and then incrementally searches then the following happens:

- old no longer matching entries are not removed
e.g. search for /usr/ then remove this and search for /bin/ and then for /usr/ again, but /bin will be still there.

- if the same entries are found several times, they're not merged
e.g. if you search for /usr, then you first enter / then u then s then r.
At with /u, it will already list /usr, with /us it will list it a 2nd time, and a 3rd time when you search for /usr

![screen](https://cloud.githubusercontent.com/assets/919933/4429189/65055e00-45de-11e4-9cb0-d35b4555c8c2.jpg)

Cheers,
Chris.

**Comment by ManIVIctorious** [comment]
Since this issue seems to be fixed, can it be closed?

**Comment by calestyo** [comment]
I'd haven't noticed it anymore… thus closing.
