### ISSUE TITLE
Nemo 'burn / write to disk" option like on Ubuntu nautilus

### ISSUE THREAD

**Issue by freemangilgamesh** [linuxmint/Cinnamon#3538]
I suggest a burn option to Nemo file manager like on Ubuntu nautilus. I think it makes burning process easier for new users.

<a href="http://imgur.com/o0CNwwE"><img src="http://i.imgur.com/o0CNwwE.png" title="Hosted by imgur.com" /></a>

**Comment by Lx** [comment]
Nemo already has partial support for burning discs, as Nemo is presented as an option when inserting a blank disc.  However, although files can be dragged into the resultant window, there's no way to finalise the operation by initiating the burn.

So it seems that in the meantime, perhaps Nemo should be removed as a disc burning option.

**Comment by leigh123linux** [comment]
-1 if you intend to use brasero as it's total shit!

**Comment by JosephMcc** [comment]
This is a nemo issue. Please open it there.
