### ISSUE TITLE
No brightness control in cinnamon-settings power

### ISSUE THREAD

**Issue by leigh123linux** [linuxmint/Cinnamon#3540]
I have no brightness control in cinnamon-settings power, the brightness applet functions fine.
I suspect the test  is failing in cs-power.py

https://github.com/linuxmint/Cinnamon/blob/master/files/usr/lib/cinnamon-settings/modules/cs_power.py#L58

Cinnamon version = 2.2.16
OS = Fedora 21 x86_64
Hardware = Lenovo T410

**Comment by dalcde** [comment]
Is this still an issue on cinnamon git?

**Comment by leigh123linux** [comment]
@dalcde 

Sorry I don't know as I haven't tested git for a couple of months

**Comment by dalcde** [comment]
Because we recently rewritten a lot of stuff in cinnamon-settings, and ported a lot of stuff from cinnamon-control-center to python. Might be worth trying again.

**Comment by leigh123linux** [comment]
git still fails due to this broken test, patch below fixes the issue

```
--- a/files/usr/lib/cinnamon-settings/modules/cs_power.py	2014-11-26 10:02:59.000000000 +0000
+++ b/files/usr/lib/cinnamon-settings/modules/cs_power.py	2014-12-02 10:20:08.218282012 +0000
@@ -173,7 +173,7 @@ class Module:
             screen = CinnamonDesktop.RRScreen.new(Gdk.Screen.get_default())
             outputs = CinnamonDesktop.RRScreen.list_outputs(screen)
             for output in outputs:
-                if (output.is_connected() and output.is_laptop() and output.get_backlight_min() >= 0 and output.get_backlight_max() > 0):
+                if (output.is_connected() and output.is_laptop()):
                     primary_output = output
                     break
         except Exception, detail:
```

**Comment by leigh123linux** [comment]
@dalcde 

The broken test remains unchanged so it still doesn't display the brightness controls.

https://github.com/linuxmint/Cinnamon/blob/master/files/usr/lib/cinnamon-settings/modules/cs_power.py#L176

The same laptop also has the same issue with Debian Jessie (repo provided packages).

**Comment by clefebvre** [comment]
Fixed by https://github.com/linuxmint/Cinnamon/commit/3bd6dbace263b45da79d692c60f516f3683d9cf5
