### ISSUE TITLE
nightly - can trigger CPU loop condition from high contrast accessibility option

### ISSUE THREAD

**Issue by brownsr** [linuxmint/Cinnamon#3541]
If I turn on the high contrast then the windows and icons change to high contrast (not all the icons, but that may be down to me mangling my icons inadvertently).  Press it again and it turns back.  However if I press the button repeatedly without giving the screen time to respond then the screen freezes, there is no sign of disk activity, and my laptop fans kick in indicating some form of CPU loop.  Repeatable.

**Comment by ManIVIctorious** [comment]
Is this still relevant in cinnamon 3.0?
