### ISSUE TITLE
add options that disable downloading applets/extensions/themes

### ISSUE THREAD

**Issue by calestyo** [linuxmint/Cinnamon#3542]
Hi,

Could you please add two sets of options, each for applets, extensions and themes (i.e. all kinds of code that can be downloaded/installed from the web).

One set of option should control system-wide, whether users are allowed to download applets/extensions/themes (and/or have those, which were somehow manually placed in .cinnamon, being used) or not (and the respective tabs in the control panel shouldn't appear then).

The idea behind this is, that all distros have their package management system, from where they (ideally) provide packages which are under security support and retrieved in a secure way from upstream.
System administrators may want to forbid their users to directly download/install arbitrary code from locations outside of the distro's archives.

Of course it must also be assured, that an applet/extension/theme, which is installed system-wide via a distro package, isn't tried to be updated by a user, effectively only creating a new installation of the respective thing in the user's local ~/.cinnamon

Of course these settings must be set in a place, which can't be controlled by normal users but only by root.

A second set of options (though less important) could be that each single user can decide for himself, whether he wants those online download+install stuff to be enabled or not.

Cheers,
Chris.

**Comment by dalcde** [comment]
I don't see a rationale for this. Users are always assumed to be able to execute arbitrary code, and the syadmins should always assume this. cinnamon-settings is one way to do so. Firefox is another way. Or email. Or ftp. Or reading the source code off your phone and typing it into the machine.

Anyway, even if this is justified, I don't think this is a sufficiently common use case, and sysadmins should be sufficiently knowledgable to implement this in some way. If you for some abstruse reason don't want users to configure the desktop, use this: https://help.gnome.org/admin/system-admin-guide/stable/dconf-lockdown.html.en. But remember someone will eventually find some way to bypass it.
