### ISSUE TITLE
 nightly - allow the theme to be previewed at a large size

### ISSUE THREAD

**Issue by brownsr** [linuxmint/Cinnamon#3545]
I like the way this reworking of the themes is going.  The large window showing all the installed themes is very nice, and the description showing on the selected components is clearer.  Just one usability problem I find, which is that there is no preview facility.  The thumbnails are small, which means that it is hard to assess a theme until it is installed.  A preview popup on hover/follow, say, would help considerably, or some other way to see what the theme is going to look like before installing it.  On the spices site,  by comparison, you can do this by clicking into the theme.

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html
