### ISSUE TITLE
allow to control the text alignment for applets

### ISSUE THREAD

**Issue by calestyo** [linuxmint/Cinnamon#3555]
Hi.

I always try to make "perfect" use of my panel space, which is why I have e.g. the following clock applet layout:
![screen](https://cloud.githubusercontent.com/assets/919933/4464358/2585c22c-48d3-11e4-8d21-06f0c1318fb9.jpeg)
As you can see the format string used is something like "%A%n%F%n%T" instead of "%A %F %T", which would use much more space, since all would be written in one line, wasting the space above and below that line.

The only issue that arises when doing so, is that for must applets, the whole thing looks a bit ugly, because everything is left aligned - where I'd prefer centre alignment.
Could you add options to all the applets, so that one can control for each of them how text is aligned, if there is any.

Cheers,
Chris.

**Comment by Vahan86** [comment]
@JosephMcc, can be marked as a feature request?

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html
