### ISSUE TITLE
allow to format the output of the power manager applet

### ISSUE THREAD

**Issue by calestyo** [linuxmint/cinnamon#3556]
Hi.

The power manager applet allows to select between percentage and remaining time (or both or none).
I think this should be handled more generic by using format strings.

E.g. there could be something like this:

 %In - Icon (i.e. the battery icon) for the n-th battery
%I - Icon (i.e. the battery icon) for overall representation of all the batteries

%Tn - remaining time to charge/discarge for the n-th battery
%T - remaining time to charge/discarge for the all batteries
The same could e.g. be extended like:
%Tn{time-format}  respectively  %T{time-format}
where time-format is a strftime(3) format string to control the out format of the time. Of course this would need an escaping of the { and } characters (e.g. via %{ %} within the timeformat.

%Pn - current percentage for the n-th battery
%P - current percentage for the all batteries

One could even think to extend this even more and allow things like colour schemas for %P/T/I to be defined (also in a {...} syntax) which control how the colour of text/icons should change gradually depending on the status or whether it's charging, discharging or on AC only.

Implementing such powerful functionality, would also solve #2950 IMHO.

And it would solve the following issue:
When I currently select to show both, percentage and time, it looks like this:
![screen](https://cloud.githubusercontent.com/assets/919933/4464685/aa1b25de-48d5-11e4-9766-49c4368545fc.jpeg)
I'd have however rather each of those value in a separate line, to save space, which could be easily done via a format string like:
%P%n%P
(where %n is again a newline).

Cheers,
Chris.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
