### ISSUE TITLE
Improve xlet installer

### ISSUE THREAD

**Issue by lestcape** [linuxmint/Cinnamon#3562]
I like to have a way to register an extensions manager inside cinnamon settings...
Because the default Cinnamon Installer:
1- Not download/install, several applets, desklets, ... at the same time.
2- Not have a way to check for a hard/soft packages dependency.
3- Not have a real cache ready to search for an extension.
4- Not provide a service/terminal/a way/ to an external application that could install some extension.
5- Is just basic.
5- ....
Additional to this problem, there are not intention, for add some of this features, because some are relate to an specific distro. So, the best way that i see(in consequence with the action taking in cinnamon, about things like that) to have some of this features, is that cinnamon settings, delegate this action to the distros or external application in general.

Proposal on how to do:
1- Create a new value on gsettings, connect cinnamon-settings-daemon to this new attribute. This attribute will need to have a special format, to call a program with parameters. Could be use the normal spawn command line notation.
2- When an external application try to change this value, cinnamon can send a notification of user that some application will try to register as a default installer. If user accept the change, then allow the override, and pass a control to the external application and continue checking silents this value, to detect an uninstallation of the external application and recover the control of this feature.
3- Provide a way in the cinnamon settings, where the user can revert this change.
4- Report to devs of applets desklet and extension, that dependency of a packages could be wrote in metadata.json with an specific format.

Format to dependencies:

{
    "uuid": "screen-inhibit@mtwebster", 
    "icon": "video-display", 
    "last-edited": "1370116733", 
    "name": "Screensaver Inhibitor", 
    "description": "Click to inhibit the screensaver, click again to remove inhibition",
    "dependencies": "package_name_on_distros1,package_name_on_distros2,package_name_on_distros2,....",
    "package_name_on_distros1": "Mint,Ubuntu,Debian",
    "package_name_on_distros2": "ArchLinux,Atergos,Manjaro"
}

How resolve dependency:
We need to know the name of our distro, so we find all possible names directly in the dependency  attribute, and then we need to filter the correct entry where appear the current distro. This entry will be a packages name required in your distro. Then just call to install with the distro default installer this packages.

Final consideration:
This at less could be implemented in Linux Mint distro, without affect other distros. So in my opinion this could be a good and easy way to improved Cinnamon, then Mint.

Thanks for considered, and improve that with more ideas.

**Comment by mtwebster** [comment]
Coming soon..  https://github.com/mtwebster/cinnamon-desktop/commit/062a8bbeeed34c081bb3e833cd0b90d2fcd75854

**Comment by lestcape** [comment]
@mtwebster thanks for this. As i see, us will have a way to install packages. Will also can have a way to register others ways? I think will be really important for mint at less, to have a more specific way to be controled the installation (probably in mint is important checking the level of the repository). So, i think an option for register the preferable installer (probably as a plugings) will be important for performance, user preference, not overkilling Mint with other type of installer and other things. Also if this will be used just for the cinnamon extension and is not connected to the normal installation behaviour, then will be really slow the installation of a package, as first will be required a repository synchronization (thats could occurs constantly or just when you want to install a packages), both behaviors are complex. Another way is write a mint back-end directly for packagekit.
