### ISSUE TITLE
Network applet shows wrong network name

### ISSUE THREAD

**Issue by nirvdrum** [linuxmint/Cinnamon#3563]
If I create a VPN connection, close out of the settings, then go back in and rename it, the network applet will show the original name.  The network manager, however, will show the correct name.  I haven't found a way to force a refresh or cache invalidation.  The only fix is to delete the connection and recreate it with the new name.

**Comment by Vahan86** [comment]
@JosephMcc, this issue is related to Network-manager-applet and if this is still an issue should be moved to this repo: https://github.com/linuxmint/network-manager-applet/issues

**Comment by Vahan86** [comment]
@nirvdrum, is this still an issue in Cinnamon 3.0?

**Comment by JosephMcc** [comment]
@Vahan86 the network applet these issues are about is a built in Cinnamon applet so this is probably the best place for them.

**Comment by Vahan86** [comment]
Ok @JosephMcc, thanks for clarification.

**Comment by Vahan86** [comment]
@JosephMcc, can we close this issue?

**Comment by nirvdrum** [comment]
Sorry, I haven't had a chance to try this out. I'll need to set up a VM with Cinnamon 3.0.
