### ISSUE TITLE
Cinnamon System Settings - Administrator Mode

### ISSUE THREAD

**Issue by anandrkris** [linuxmint/Cinnamon#3565]
Hi - Currently, the options that require root privileges prompt for password for every application. _(This will also fix the issue of inconsistent password required dialogs shown currently )_

The Date module has an 'Unlock' option, similarly am asking for unlock mode for the entire settings. Admin mode could be placed like the now-removed Advanced Mode.

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html
