### ISSUE TITLE
System Info - Copy to Clipboard

### ISSUE THREAD

**Issue by anandrkris** [linuxmint/Cinnamon#3569]
This would be much useful in reporting the system details while asking for help in forums, etc.
Moderators often ask people to provide the output of commands like 'inxi - Fx' from terminal,  but copy option using GUI could be handy instead avoiding the terminal route for new comers.

This system information details also could be enhanced perhaps to include other details.

**Comment by anandrkris** [comment]
Looks like now we have a xapps common library that allows uploading all relevant details still would like to see full output instead of limited info.

https://github.com/linuxmint/Cinnamon/commit/e7d7a9cafcb72b0bbb3cce5d52ef5685cd44c6f2

**Comment by clefebvre** [comment]
I'll close this for now and it's almost implemented.

I tried to show the inxi output in a textview, but it's very messy.

**Comment by anandrkris** [comment]
You mean **System Info** shows detailed output like `inxi -F` ?
> System:    Host: anand-Intense-PC Kernel: 4.4.0-21-generic x86_64 (64 bit)
           Desktop: Cinnamon 3.0.7  Distro: Linux Mint 18 Sarah
Machine:   Mobo: CompuLab model: Intense-PC v: 1.x
           Bios: Phoenix v: CR_2.2.0.377 X64 date: 04/10/2013
CPU:       Dual core Intel Core i5-3337U (-HT-MCP-) cache: 3072 KB 
           clock speeds: max: 2700 MHz 1: 801 MHz 2: 802 MHz 3: 847 MHz
           4: 802 MHz
Graphics:  Card: Intel 3rd Gen Core processor Graphics Controller
           Display Server: X.Org 1.18.3 drivers: intel (unloaded: fbdev,vesa)
           Resolution: 1920x1080@60.00hz
           GLX Renderer: Mesa DRI Intel Ivybridge Mobile
           GLX Version: 3.0 Mesa 11.2.0
Audio:     Card Intel 7 Series/C210 Series Family High Definition Audio Controller
           driver: snd_hda_intel
           Sound: Advanced Linux Sound Architecture v: k4.4.0-21-generic
Network:   Card-1: Intel 82579LM Gigabit Network Connection driver: e1000e
           IF: enp0s25 state: down mac: 00:01:c0:13:68:87
           Card-2: Realtek RTL8723AE PCIe Wireless Network Adapter
           driver: rtl8723ae
           IF: wlp4s0 state: up mac: 00:0d:f0:ad:6b:c4
           Card-3: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller
           driver: r8169
           IF: enp5s0 state: down mac: 00:01:c0:13:68:88
Drives:    HDD Total Size: 120.0GB (35.6% used)
           ID-1: /dev/sda model: Samsung_SSD_840 size: 120.0GB
Partition: ID-1: / size: 107G used: 37G (36%) fs: ext4 dev: /dev/sda1
           ID-2: swap-1 size: 4.07GB used: 0.00GB (0%) fs: swap dev: /dev/sda5
RAID:      No RAID devices: /proc/mdstat, md_mod kernel module present
Sensors:   System Temperatures: cpu: 38.0C mobo: 38.0C
           Fan Speeds (in rpm): cpu: N/A
Info:      Processes: 198 Uptime: 5 min Memory: 779.4/3742.4MB
           Client: Shell (bash) inxi: 2.2.35 



`
