### ISSUE TITLE
Looks for /usr/share/gnome-background-properties if /usr/share/cinnamon-background-properties is not available

### ISSUE THREAD

**Issue by pacho2** [linuxmint/Cinnamon#3575]
On Fedora, Arch and Gentoo we are needing to apply patches (or sed) to change cinnamon-background-properties by gnome-background-properties because seems that cinnamon-background-properties is not available

**Comment by clefebvre** [comment]
This is not a bug. Cinnamon should not show GNOME backgrounds. Why GNOME anyway? why not KDE or Xfce4 backdrops, or MATE ones? Distros have the ability to fine tune which backgrounds appear in which DEs thanks to the fact that each DE uses its own location. Let's not break that.

Rather than patching the code, you're better off fixing your backgrounds and make them support the DEs you want them to support.

**Comment by rik-shaw** [comment]
@clefebvre You are correct that we shouldn't necessarily look at GNOME **instead** of KDE, Xfce4, etc, but the original question is **when cinnamon-background-settings doesn't exist, then what should happen**?  Users in Ubuntu or other distros won't have the LinuxMint background packages, so then also won't have the /usr/share/cinnamon-background-settings folder.  So when you choose "change desktop background" no backgrounds will show at all as available.

I would suggest that Cinnamon could look in all known background folders for all desktops: they are pretty pictures so why not have all the pretty pictures findable by Cinnamon?

**Comment by mtwebster** [comment]
The only solution I personally would like to implement is to ship a default, simple wallpaper with cinnamon.  None of these other desktops are searching for cinnamon backgrounds, I can guarantee that, and while we frequently make these sort of concessions, I'm really not keen on conceding on this.

Shipping a default 'cinnamon' wallpaper would guarantee at least something other than a black background.

**Comment by rik-shaw** [comment]
@mtwebster thanks for the reply.  I wonder if it is possible to add /usr/share/backgrounds as one of the default added folders? That contains the actual images without the desktop-specific metadata.

**Comment by eli-schwartz** [comment]
Is there any status on Cinnamon distributing its own backgrounds? I cannot even tell where the files it expects to see come from... should I just keep patching the Arch packages to use gnome-backgrounds?

I genuinely have no idea what to even do here.

**Comment by clefebvre** [comment]
No, you don't need to patch anything.

You can place backgrounds anywhere you want on the filesystem. Define collections in xml files in /usr/share/cinnamon-background-settings and point to whichever backgrounds you want to show up.

If you're not shipping with any collection, then it's normal for Cinnamon not to show any.

@mtwebster I disagree with shipping a default background. Again, artwork is distro-specific, I really don't want DEs to get in the way here.
