### ISSUE TITLE
Use wheel group instead of relying on sudo

### ISSUE THREAD

**Issue by pacho2** [linuxmint/Cinnamon#3576]
Fedora, Arch and Gentoo are applying this patch to not rely on sudo:
http://pkgs.fedoraproject.org/cgit/cinnamon.git/tree/set_wheel.patch

Maybe would be interesting to try to upstream it :)

Thanks

**Comment by dalcde** [comment]
Fedora/Arch/Gentoo uses wheel while Debian-based distros use sudo. Since Cinnamon by default targets debian-based distros (eg the debian packaging is included in the source), sudo will stay.
