### ISSUE TITLE
Patch for compatibility with gnome/gtk 3.14

### ISSUE THREAD

**Issue by pacho2** [linuxmint/Cinnamon#3577]
Fedora and Arch are applying this patch for compatibility with Gnome 3.14... but I haven't found any report for upstreaming this :/
http://pkgs.fedoraproject.org/cgit/cinnamon.git/tree/cinnamon-gtk-3.14.patch

**Comment by nardholio** [comment]
Would wrapping this in #if ! GNOME_CHECK_VERSION(3,14,0) work? I haven't compiled that yet myself but it seems like it would work.

**Comment by JosephMcc** [comment]
Don't think this is relevant anymore.
