### ISSUE TITLE
Look for cinnamon-control-center panel path not for the unneeded binary

### ISSUE THREAD

**Issue by pacho2** [linuxmint/Cinnamon#3578]
On ArchLinux the following sed is being applied:
        # Check for the cc-panel path, not for the unneeded binary
        sed -i 's|/usr/bin/cinnamon-control-center|/usr/lib/cinnamon-control-center-1/panels|' \
                files/usr/bin/cinnamon-settings || die

Maybe would be interesting to try to notify to upstream to not need to carry this forever :)

Thanks

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html
