### ISSUE TITLE
polkit-gnome-authentication-agent-1 is required by cinnamon

### ISSUE THREAD

**Issue by pacho2** [linuxmint/Cinnamon#3579]
As reported downstream to:
https://bugs.gentoo.org/show_bug.cgi?id=523958

Not having polkit-gnome-authentication-agent-1 running leads to some problems. Then, we saw that Fedora and Arch are patching the session file to ensure it's run and are also providing an autostart file:
http://pkgs.fedoraproject.org/cgit/cinnamon.git/tree/autostart.patch
http://pkgs.fedoraproject.org/cgit/cinnamon.git/tree/polkit-cinnamon-authentication-agent-1.desktop

Thanks

**Comment by Vahan86** [comment]
@pacho2, is this still an issue in Cinnamon 3.2?

**Comment by Vahan86** [comment]
@JosephMcc, can we close the issue?

**Comment by Vahan86** [comment]
@JosephMcc, can we close the issue?
