### ISSUE TITLE
mousewheel zoom and qt

### ISSUE THREAD

**Issue by friedemann-** [linuxmint/cinnamon#3580]
Hi,

I recently found out, that cinnamon in mint 17 has mousewheel zoom on alt+wheel, so I could deactivate my old extension.

But I have a problem now:

In some qt application ('tiled', a mapeditor) there should be horizontal scrolling available with alt+wheel, and it doesn't work on mint, or inside a windows client virtualbox on mint, works on real windows though.
This isn't a feature of the application, but qt default behaviour.
I can't find another possible cause for this, so could the alt+wheel-feature blocking this in some way?
Deactivating alt+wheel doesn't help.
I also googled around, but couldn't find any other people complaining about this, so maybe I screwed this up myself - can somebody reproduce?

Either way: it would be nice to have an option for this, I would appreciate beeing able to choose a modifier key / combo for the zoom.

Ah, and the mouse cursor flickers sometimes when zoomed in, but I could live with that.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
