### ISSUE TITLE
CSS Theming Bug when drawing a border at panel top

### ISSUE THREAD

**Issue by theSeppi** [linuxmint/Cinnamon#3582]
I tried to modify the *Linux Mint* Cinnamon theme a litte, when I ran in some difficulties with the CSS section for the panel. The *Linux Mint* Theme styles the panel as follows:

    #panel {
        color: #ffffff;
        background-gradient-start: rgba(70,70,70,0.9);
        background-gradient-end: rgba(50,50,50,0.9);
        background-gradient-direction: vertical;
        font-size: 9pt;
        font-weight: normal;
        height: 25px;
        box-shadow: 0px 0px 2px 2px rgba(0,0,0,0.5);
    }

I changed it a bit: I set `background-gradient-start: rgba(70,70,70,0.5);`, which worked fine. However, I also added the following:

    border-top: 1px solid rgba(70,70,70,0.8);

Even though I only defined the border for the top side of the panel, it is also drawn at the panel's bottom. Since Cinnamon doesn't interpret clicks on the border, I now can't move my mouse to the screen bottom to access an applet, launcher or window. I have to stop one pixel above to be able to use them. Even when I explicitly define the bottom border as `0px none rgba(0,0,0,0)`, it is still drawn.

Here's a comparison of both themes (*Linux Mint* and my customized one) applied to the panel:

![csspanelbug](https://cloud.githubusercontent.com/assets/5564491/4559200/7ebed81c-4ee9-11e4-991b-25895a2a0b4c.png)

As you might see, when you look closely, the items in the panel are shrinked by one px at the bottom, where the border is drawn.

Am I doing something wrong or is it really a Cinnamon bug?

**Comment by JosephMcc** [comment]
https://github.com/linuxmint/Cinnamon/issues/1375 is the same issue and shows a workaround.
