### ISSUE TITLE
Cinnamon stops responding when trying to open partially downloaded 0 byte MP4 on desktop

### ISSUE THREAD

**Issue by geckolinux** [linuxmint/Cinnamon#3584]
Hi, I just found a bug that I can consistently reproduce on Manjaro, running the latest Cinnamon, Xorg 1.15, and Intel graphics. 

While downloading with Firefox, it uses a 0 byte "filename.extension" file, and a "filename.extension.part" file, which actually buffers the downloading content. I was downloading an MP4 to my ~/Desktop dir, and I mistakenly tried to open the 0 byte filename.mp4 file from the Cinnamon desktop with the default player, VLC. Each time I try this, Cinnamon completely stops responding, although the mouse still moves and I can restart Xorg with Ctl+Alt+Backspace.

A 0 bytes text file on the desktop opens correctly in gedit without any hangups.

Thanks for looking into this!

**Comment by ManIVIctorious** [comment]
Is this still an issue in cinnamon 3.0?

**Comment by geckolinux** [comment]
Looks like it's fixed in Cinnamon 3.x under openSUSE Tumbleweed. Thanks!
