### ISSUE TITLE
alt + wheel doesn't work - event doesn't reach application

### ISSUE THREAD

**Issue by friedemann-** [linuxmint/Cinnamon#3585]
see below

**Comment by edmundlaugasson** [comment]
ALT+wheel not working here (17.1 Cinnamon, 64-bit)

**Comment by mtwebster** [comment]
Okay figured this out, will give details once it's fixed.

**Comment by edmundlaugasson** [comment]
It seems like the file manager Thunar in XFCE does not follow that logic. Others (tested Dolphin in KDE, Caja in MATE, PCManFM in LXDE - all based in Ubuntu 14.04) do follow that logic (directly dragging will move, holding CTRL copies and holding ALT after dragging gives choices).
