### ISSUE TITLE
there should be an official system monitor and a sensor/hardware monitor applet

### ISSUE THREAD

**Issue by calestyo** [linuxmint/Cinnamon#3586]
Hey.

Quoting myself from #3556:
>As for the 3rd party applet:
>I personally really hate the idea of plugins/applets (from an organisational PoV).
>3rd party applets are typically less tested (security?) and less maintained (which means they can
>break with every upgrade of the main product - just look at Mozilla).
>And you have the problem, that there will be n applets doing more or less the same or having
>different functionality that should be actually merge into one - just look at the number of 3rd party
>system monitor applets for Cinnamon: Many of them do the same, some use old techniques, some
>look ugly, some of them should have their functionality merged.
>
>I fully agree that things like "applet for some local newspaper" or clearly external stuff like "applet
>for Nagios/Icinga alerts" shouldn't become part of the official set of applets.
>But for everything else, when it's a good idea, it should be part of the official distribution (which of
>course doesn't mean that something needs to be implemented the next week)

That being said, we have several 3rd party system monitor and sensor/hardware monitor applets...
I think one should either pick one of them and start to make it an official one or start one from scratch.

Monitoring is of course a big and complex field and one could make an extremely large application out of this...
Some design ideas:
- using existing libraries (gtop?)
- I personally liked the system monitor applets from GNOME classic a lot, where one had fields for CPU, Disk, Network, Swap, Memory... could configure the colour of them, their width and the update interval. Also visualising stuff like cached memory, shared, etc.. One could have several applets running on different places of the panel (even on different screens),... and one could configure them (i.e. what they show) separately.
- maybe adding more functionality, like that one configures the data source (which CPU/HDD/Network is shown? all or just single selectable CPUs, disks, NICs)..

as for the hardware/sensor monitoring:
- one can use lm-sensors for most values
- configuration of colours, warning thresholds, reload intervals
- their are libraries which allow integration of proprietary stuff like NVIDIA GPU temperatures
- perhaps SMART monitoring

Cheers,
Chris.

**Comment by denispr** [comment]
@unlimitedbacon I second pixunil, it would be nice to have a cinnamon-applet-extras package with supported applets, while today you're never sure the applets that you download from the applets dialog will work (It often depends on the cinnamon version you're running and you have to try them one by one to see if they work or not. Quite a pain...)

**Comment by JosephMcc** [comment]
This is not likely to happen. For many users these applets are the source of a lot of desktop freezing issues due to how Cinnamon works internally. That alone would preclude them from being part of the default applets.

**Comment by calestyo** [comment]
hmm strange... what would be the problem? such applets already worked pretty fine back in the GNOME2 days... and there are so many other applets which do regular redrawings...

it's really a big deficiency of the cinnamon desktop.. especially that one has basically no chance to get proper overview and warnings about system resource usage and health (SMART,etc.)

**Comment by JosephMcc** [comment]
Well Cinnamon isn't gnome2.

The problem comes down to the fact that the entire Cinnamon process runs in one thread and the constant updating these applets do can lock things up.

**Comment by calestyo** [comment]
> Well Cinnamon isn't gnome2.

Sure but it follows more its spirit (i.e. let the user control his system and see what's going on) than that of GNOME3 ("better don't tell the user that there's something like resources, cause the user is anyway considered to be too stupid for it").


> The problem comes down to the fact that the entire Cinnamon process runs in one thread and the constant updating these applets do can lock things up.

Isn't this than rather some general problem that will hit cinnamon sooner or later in other places as well?

**Comment by JosephMcc** [comment]
> Sure but it follows more its spirit (i.e. let the user control his system and see what's going on) than that of GNOME3 ("better don't tell the user that there's something like resources, cause the user is anyway considered to be too stupid for it").

It has absolutely nothing to do with "spirit". It has to do with design and implementation. Cinnamon is forked from gnome shell and brought those things with it. Changing that would essentially mean writing a new DE.
