### ISSUE TITLE
[Calendar applet] Incorrect time zone and UTC number listed

### ISSUE THREAD

**Issue by Obsidian-Jackal** [linuxmint/Cinnamon#3587]
The cinnamon calender applet shows an incorrect time zone and UTC number when I have <code>%Z %z</code> in the custom date format. In the "Date & Time" settings of cinnamon, network time is set to on, the city is set to New York in the America region and the time is 5:52. In the panel, the callendar applet reports that my time zone is EDT -0400 instead of EST -0500. This problem happened when it started being daylight sayings time.

**Comment by robersonccgomes** [comment]
I'm having the same problem here.
I have just installed Linux Mint 18 Cinnamon.

Initially the applet shows `13:03` (which is correct).
If I check `Use a custom date format`, it changes to `17:03`.
Unchecking, it goes back to `13:03`.
