### ISSUE TITLE
Menu options are automatically clicked when moving the mouse before menu appears

### ISSUE THREAD

**Issue by AlbertJP** [linuxmint/Cinnamon#3596]
If I click the menu, it sometimes takes a while to appear - not very problematic, but it becomes quite annoying if I'm already moving the mouse towards the firefox or thunderbird icon if the menu is not open yet.
When the menu finally appears, it automatically opens the program on which my mouse is located at that moment.
This only happens when clicking the menu, not when opening it with the Windows key. It is also not 100% reproducible, because of the short time the menu takes to open, but it has frequently happened to me that another program in the favourites bar suddenly opened.

**Comment by xunli** [comment]
@mtwebster  , Can you tell me where the code is? I want to know how to fix this problem, and may be it's in menu@cinnamon.org/applets.js?  ApplictionButton 's _onButtonReleaseEvent() used to open new window by one click, but I can't find which part is used to avoid this problem. [Sorry for my English :'( ]
