### ISSUE TITLE
window packing and growing

### ISSUE THREAD

**Issue by jonorthwash** [linuxmint/Cinnamon#3604]
Window packing lets you move a window in the direction you specify until it hits another window or the edge of a monitor.  Window growing lets you make a window larger in the direction you specify until it hits another window or the edge of a monitor.  Both of these features allow the user to do a sort of faux-tiling.

It would be great to have these built into the window manager, mappable to key combinations.

**Comment by JosephMcc** [comment]
You made the same requests here: https://github.com/linuxmint/muffin/issues

**Comment by jonorthwash** [comment]
Yes, I did, nearly two years later when I couldn't find my original request and decided I had imagined making one :-P  Thanks for slapping labels on them.
