### ISSUE TITLE
HiDPI and Multiple Monitor setups

### ISSUE THREAD

**Issue by pacharanero** [linuxmint/Cinnamon#3606]
Using Cinnamon in HiDPI mode with multiple monitors (one HiDPI Dell M3800 laptop screen, one 22" lower-res external monitor via HDMI) causes everything on the external monitor to be excessively large.

What we need to be able to do is set the HiDPI settings separately for different displays. This would have the side effect of bringing the HiDPI controls into the Display section of Settings, where I would argue if belongs, rather than in General.

**Comment by fattchris** [comment]
Cinnamon is using Wayland now, right? Is there a fix for this issue yet?

**Comment by JosephMcc** [comment]
Nope.

**Comment by vincenzocaselli** [comment]
Hi, I am in the same situation (one HiDPI Dell M3800 laptop screen, one 21" 1920x1080 external monitor via HDMI) => everything on the external monitor is large.
Any update or workaround to fix it?
Thank you very much
Vincenzo

**Comment by vincenzocaselli** [comment]
Just found a workaround in this post
http://askubuntu.com/questions/393400/is-it-possible-to-have-two-different-dpi-configurations-for-two-different-screen
My monitors are:
external 1920x1080, top
laptop 3200x1800, bottom
so my settings are:
xrandr --output HDMI1 --mode 1920x1080 --scale 2x2 --fb 3840x3960
xrandr --output eDP1 --scale 1x1 --pos 0x2160

calculations are the following:
TOP - External monitor (1920x1080), 3840=1920x2, 3960=2x1080+1800 (total area of both monitors) 
BOTTOM - Laptop monitor (3200x1800), 0x2160=> laptop monitor, left=0, top=1080x2 

HTH

**Comment by sathi-007** [comment]
when i tried this workaround, my mouse area restricted by invisble bounadries in seconadry screen.
I am using centos 7 and xrandr version 1.4.3

**Comment by ambs** [comment]
One year later from @vincenzocaselli post, is there an easy fix? I am not using xrandr (at least directly). Just the HiDPI option in cinnamon. Thanks.

**Comment by jeetsrs** [comment]
Had to modify the settings suggested by @vincenzocaselli  a bit for my two different external monitors when used with my laptop individually (don't have a dual HDMI out cable yet). 

Monitor 1: External Monitor 2560X1440, Internal/Laptop Monitor 3200x1800
xrandr --output eDP-1 --scale 1x1 --pos 0x2880
xrandr --output DP-1 --mode 2560x1440 --scale 2x2 --fb 5120x4680

Monitor 2: External Monitor 1920x1080, Internal/Laptop Monitor 3200x1800
xrandr --output eDP-1 --scale 1x1 --pos 0x2160
xrandr --output DP-1 --mode 1920x1080 --scale 2x2 --fb 3840x3960

These work, but there is a significant amount to tearing in the high resolution monitor (laptop) when I move windows, resize screens  or scroll on a browser. This feels like a software rending solution (which has all these issues of tearing, and slow refreshes). 

Its 2017, Linux/Gnome needs to address the multi-monitor, mixed scaling solution. Both Windows 10 and OS X have this resolved without having to resort to command line band-aid fixes that partially work (the tearing issue isn't acceptable for gaming)

**Comment by zdorovo** [comment]
Is there a way to open this issue again, now that Cinnamon uses Wayland? Should someone/I submit a new issue?

**Comment by JosephMcc** [comment]
> Is there a way to open this issue again, now that Cinnamon uses Wayland? Should someone/I submit a new issue?

Cinnamon doesn't use Wayland.

**Comment by maxim2muchcoffee** [comment]
This issue is still not resolved. There are few weird workarounds, but no solutions

**Comment by dl-sledding** [comment]
I am encountering the same thing, Linux Mint 18.3 on a Surface Pro 2017 with an HP ZR30w monitor.

The Surface screen is 2736x1824 and the HP monitor is 2560x1600.  The HP is to the right of the Surface.

I have run the command:

xrandr --output DP1 --mode 2560x1600_60.00 --scale 2x2 --pos 2736x0 --fb 7856x3200
and even
xrandr --output DP1 --mode 2560x1600_60.00 --scale 2x2 --pos 2736x0 --fb 7856x5024

I get the proper scale on the HP, but it is only the top left 1/4 of the monitor; and my mouse cannot enter the lower 20% of the scaled image.

I realize that Mint is free, but this is becoming a very common use.  I can't believe that the community hasn't yet "fixed" this...  I would if I could, but I am a lowly SysAdmin, not a dev.  I would gladly help in any way that I can.

**Comment by dl-sledding** [comment]
FYI: excellent write up here: http://wok.oblomov.eu/tecnologia/mixed-dpi-x11/

For those blaming X11 as the limitation of using mixed-DPI monitors by the DE, please read it.  X11 is not the problem, the tools written to configure the screens is the problem.

**Comment by Lunderberg** [comment]
Thank you @dl-sledding for the article.  The link itself is broken, but it's [available on archive.org](https://web.archive.org/web/20201230000047/http://wok.oblomov.eu/tecnologia/mixed-dpi-x11/) in case anybody else arrives here from a google search.
