### ISSUE TITLE
allow hiding of network-manager's (or any) systray icon

### ISSUE THREAD

**Issue by Lx** [linuxmint/Cinnamon#3608]
By default, Cinnamon's panel features a network applet.  When this applet is shown, Cinnamon hides `network-manager`'s systray icon to avoid two similar icons being shown.  When the applet is removed, the systray icon is unhidden.

For a new user, the intuitive result of removing the network applet from the panel is that no network icon would remain.  What actually currently happens is that the removable network icon is replaced with another non-removable icon.

[I filed this behaviour as a bug](https://bugs.launchpad.net/linuxmint/+bug/1382946); the bug report was [rejected](https://bugs.launchpad.net/linuxmint/+bug/1382946/comments/1).  Accordingly, I'm rewriting the report as a feature request here.

In my case, I want to remove all network icons from the panel because my PC is permanently connected to the network using Ethernet, and an icon showing no further information than "yes, connected" isn't of enough value to me for me to want screen real estate taken up by it.

Another user, who was connected via Ethernet at the time, also [wanted to do this back in 2008](http://forums.linuxmint.com/viewtopic.php?f=150&t=10013&p=62206#p61859).

In the bug report linked above, [Clement Lefebvre](https://launchpad.net/~clementlefebvre) suggested that this feature request could be implemented as "a blacklist of systray icons to hide in Cinnamon" and labelled such an implementation as "easy to do."

**Comment by dalcde** [comment]
Closing as duplicate

**Comment by orbitalchicken** [comment]
I think this is not resolved. I have the same problem in 2019, in mint 18.3: When I disable the Network Applet, the other appears.... I do not like that weird bahavior.
