### ISSUE TITLE
Using Super as the key to move windows causes further problems using the key

### ISSUE THREAD

**Issue by kupiakos** [linuxmint/Cinnamon#3609]
If I use the Super key as the "special key to move and resize windows" instead of Alt (Alt is used a lot in graphics programs), strange problems occur after moving a window. 

If I move or resize any window by using the Super key and dragging, I can no longer
- Click Super to bring up the menu
  - It acts as if it's open and accepting input, but it doesn't show, nor does it run anything when enter is clicked. If I click Super and type in "nemo<Enter>", nothing will happen. However, when I click the Menu button manually, it will immediately run Nemo.
  - After clicking Super to bring up the menu after dragging, I cannot Alt-Tab.
- Use a keyboard shortcut using the Super key
  - I use Super-E to bring up Nemo

If I click the Menu button manually a few times, _sometimes_ that will fix it.

I am currently on Cinnamon 2.3 (built 2014-11-21), but this issue has existed since (at least) Cinnamon 2.0.

**Comment by Vahan86** [comment]
@kupiakos, does this issue still occur in Cinnamon 3.0?

**Comment by kupiakos** [comment]
I cannot confirm this; I'm currently on Plasma 5 right now (with its own different set of problems).

**Comment by Vahan86** [comment]
@kupiakosn, thanks for reply.

@friedemann-, @tylery71, can you please confirm, is this still an issue in Cinnamon 3.0 or not?

**Comment by Vahan86** [comment]
@JosephMcc, can we close the issue?
