### ISSUE TITLE
Steam notifications pop up behind the taskbar with dual monitors

### ISSUE THREAD

**Issue by bkacjios** [linuxmint/Cinnamon#3610]
I run Arch Linux and have cinnamon installed on both my desktop and laptop. I noticed that the notifications work perfectly fine on my laptop, yet they go behind the taskbar on my desktop. It took me awhile to figure out that it was my second monitor causing the issue. Disabling one of the monitor allows the notifications to work as normal.

**Comment by mixedCase** [comment]
I can reproduce the issue in KDE Plasma 5.2. With a single monitor notifications work well, in a dual monitor set-up they cover the taskbar in the primary display.

**Comment by mrmaffen** [comment]
The issue is still present with the latest Steam client (Built: Feb 18 2015, at 15:33:35) and Cinnamon (2.4.6) Muffin (2.4.3). The notifications still pop up behind the taskbar.

**Comment by hypershadsy** [comment]
I'm on Cinnamon 2.2.16 / Mint 17, with dual monitors, and unplugging the secondary monitor does fix the notifications issue until it's plugged back in.

**Comment by Lawl078** [comment]
Still happening on Cinnamon 2.4.8 with dual monitors. Is this fixed in the upcoming cinnamon release?

**Comment by ndbeals** [comment]
Happens to me on Ubuntu 14.04 with Cinnamon 2.8.6 and muffin 2.8.4

**Comment by JosephMcc** [comment]
Has anyone tested this with Cinnamon 3.0?

**Comment by Vahan86** [comment]
@JosephMcc, can we close the issue?
