### ISSUE TITLE
Add hover option for panel/tray icons

### ISSUE THREAD

**Issue by hjan** [linuxmint/Cinnamon#3611]
Hey folks,

I personally find it quite annoying when I want to look up several information in the panel, say notification list, music-player status, or networkstatus and whatnot, and I have to **click** on each icon one after the other to get to those information. It feels quite unintuitive.

A more natural way would be to just click once and then be able to hover over the icons like you would do in the menu of an application/window and the actual information (whatever the panel/tray icon provides) is being displayed.

Would be much appreciated to have an option somewhere in the settings to enable/disable such a thing.

so long,
hjan

**Comment by Vahan86** [comment]
+1 for this request. Will be great to see this implemented.

**Comment by JosephMcc** [comment]
https://github.com/linuxmint/Cinnamon/issues/1732
