### ISSUE TITLE
"Always on top" desklet

### ISSUE THREAD

**Issue by BjornMelgaard** [linuxmint/Cinnamon#3614]
How can I change [photoframe@cinnamon.org](https://github.com/linuxmint/Cinnamon/tree/master/files/usr/share/cinnamon/desklets/photoframe%40cinnamon.org) to make it always viewed on top?
Is such property exists at all?

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html
