### ISSUE TITLE
OS X Dashboard widgets.

### ISSUE THREAD

**Issue by mzs112000** [linuxmint/Cinnamon#3615]
As many of you know OS X has had dashboard widgets since 10.4(?), it would be great if these would work on Linux(Cinnamon) too, as of now there are 2050 OS X dashboard widgets, it would help Cinnamon a lot if it could run these.
This is something KDE has done for a while now plasma-scriptengine-webkit allows this, the devs could use this as a reference(the part for loading widgets could be ported, UI is QT and would need to be replaced, Webkit could be replaced with a python net library.).

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html
