### ISSUE TITLE
LM 17 Cinnamon: Qt 5 developed app not displaying properly in VirtualBox

### ISSUE THREAD

**Issue by t753** [linuxmint/cinnamon#3617]
I am running Linux Mint 17 Cinnamon 32 bit and 64 bit in VirtualBox 4.3.18 on a Windows 7 64 bit host. I am also running a Linux Mint 17 Xfce 32 bit virtual machine on the host. I am developing a Qt 5 application and it doesn't display properly (items missing) with 3D acceleration enabled in the VirtualBox display settings for the guest virtual machines of LM 17 Cinnamon. There is no problems with the LM 17 Xfce virtual machine displaying the Qt 5 app properly with 3D acceleration enabled.

**Comment by te7** [comment]
I am now running Linux Mint 17.1 Cinnamon in VBox 4.3.26 on a Windows 7 64 bit host and I still get the problems with 3D acceleration enabled for the VBox VM. Any progress on this?

**Comment by te7** [comment]
The problem doesn't seem to happen outside of VirtualBox, at least not in VMWare Player with 3D acceleration.

**Comment by te7** [comment]
Here's the issue posted on the VirtualBox forum:

https://forums.virtualbox.org/viewtopic.php?f=3&t=68650&p=326745#p326745

**Comment by Vahan86** [comment]
@te7, is this still an issue for you in Cinnamon 3.0 (Linux Mint 18)?

**Comment by te7** [comment]
I haven't upgraded to LM 18 yet so I don't know. I'll bookmark this page, and when I upgrade to LM 18 I'll report back. It's a chore upgrading because I have find the correct dependencies for QT development. But I'll do it and report back.

**Comment by Vahan86** [comment]
ok @t753, thanks for help.

**Comment by Cos-mo** [comment]
You might try (without upgrading Mint) VB 5.1.x, as Oracle has moved to Qt5 in this release-branch.

**Comment by Vahan86** [comment]
@t753, is this still an issue in Cinnamon 4.2?

**Comment by t753** [comment]
I don't know. I changed my app long ago. Probably a dead issue.
