### ISSUE TITLE
Show borders/icons/controls/mouse info in themes list in 17.1

### ISSUE THREAD

**Issue by brownsr** [linuxmint/Cinnamon#3618]
I find a practical problem in loading themes, yes even in the lovely new theme manager that is coming in 17.1, is that I have no way through the theme manager of knowing just how extensive the theme is. I end up downloading it, and then going to .themes in nemo to see just what I have got. At the time of downloading I cannot tell through the theme manager whether it is Cinnamon only, does it include the metacity directory so that I can apply it to the windows etc. etc.  Would there be a way to indicate this in the themes listing ?  For example the main themes window is grouped into borders, icons, controls, mouse, and desktop, so it would be good to know just which of those a theme would/could affect, before downloading it.

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html
