### ISSUE TITLE
weird escaping in Recent Files menu description area when a file path has square brackets

### ISSUE THREAD

**Issue by Lx** [linuxmint/Cinnamon#3620]
*Menu > Recent Files* shows the full path of the selected item in the description area at the bottom of the menu.

For files with square brackets in the path, the brackets in the full path are URL-escaped.  Please see the attached screen shot.  The correct path is `.../Desktop/Folder [with square brackets]/File.txt`.

![screenshot from 2014-10-29 11 31 52](https://cloud.githubusercontent.com/assets/160164/4819476/fa9d97f0-5f03-11e4-866b-75e584d4c0d5.png)

**Comment by Vahan86** [comment]
Tested in Cinnamon 3.0.7. The issue is still there.

**Comment by Odyseus** [comment]
Hello, everybody.

I'm also seeing this on Cinnamon 3.0.7 (stable and nightly). It seems that this is the product of only un-escaping spaces on the following two lines of the applet code:

[Line 1784](https://github.com/linuxmint/Cinnamon/blob/master/files/usr/share/cinnamon/applets/menu%40cinnamon.org/applet.js#L1784)

```javascript
this.selectedAppDescription.set_text(button.place.id.slice(16).replace(/%20/g, ' '));
```

[Line 1851](https://github.com/linuxmint/Cinnamon/blob/master/files/usr/share/cinnamon/applets/menu%40cinnamon.org/applet.js#L1851)
```javascript
this.selectedAppDescription.set_text(button.file.uri.slice(7).replace(/%20/g, ' '));
```

To fix it, and as a test, I tried to use **decodeURIComponent** like this:

```javascript
this.selectedAppDescription.set_text(decodeURIComponent(button.place.id.slice(16)));
```

```javascript
this.selectedAppDescription.set_text(decodeURIComponent(button.file.uri.slice(7)));
```

With the previous edit, all paths were shown correctly inside the info box. I repeat, this was just a test. I don't know if it is *safe* to use **decodeURIComponent** in that place. Maybe not all characters should be un-escaped inside a label? It would be great to have the opinion of one of the developers.
