### ISSUE TITLE
lost bluetooth in update

### ISSUE THREAD

**Issue by rcrath** [linuxmint/Cinnamon#3625]
upgraded from Cinnamon 2.2-16 to git 2.30 from arch aur in manjaro system.  This fixed the problem I was having with nemo crashing (see [issue 734](https://github.com/linuxmint/nemo/issues/734), but now bluetooth is not working.  When I do bluetooctl, it recognizes my adapter but does not see the touchpad in discover mode when I type "devices" from the bluetooth prompt.  Working through the cinnamon applet, I deleted the old trust/pair setup and started over.  If I dosetup new device, it sees a device sometimes, but does not give the right passphrase options, offering only "random" or "Skip" which I think means it is not recognizing it as a touchpad.  I am happy to provide debug info if you tell me what to run/where to look.  Need the touchpad back!

**Comment by Vahan86** [comment]
@rcrath, is this still an issue for you in Cinnamon 3.0?

**Comment by leigh123linux** [comment]
@Vahan86 

Cinnamon 3.0 has no bluetooth any more so this report isn't valid and can be closed.

**Comment by rcrath** [comment]
sorry I missed this.  My bluetooth mgr is working fine in Cinnamon, as is touchpad, so plz close.
