### ISSUE TITLE
cinnamon texts disapear from menu and toolbar

### ISSUE THREAD

**Issue by lupa18** [linuxmint/Cinnamon#3628]
Distributor ID:	LinuxMint
Description:	Linux Mint 17 Qiana
Release:	17
Codename:	qiana

Cinnamon 2.2.16

I can't reproduce it but all texts are lost. See screenshots: 
* http://i.imgur.com/Aurao8l.png
* http://i.imgur.com/kon2MiC.png
* http://i.imgur.com/SHl3not.png

Is the second or third time it happened and a workaround is run: 
   nohup cinnamon --sync --replace

**Comment by Vahan86** [comment]
@lupa18, does this issue still occur in Cinnamon 3.0?

**Comment by lupa18** [comment]
No. There is no more problems.
