### ISSUE TITLE
Expo appears to be leaking memory (8MB ish) when first initiated [nightly]

### ISSUE THREAD

**Issue by brownsr** [linuxmint/Cinnamon#3632]
Initiating expo for the first time appears to munch up around 8MB+ of memory that does not come back.  There does not appear to be any problem on the second or subsequent invocation.  It makes no difference whether expo is initiated via applet, hot corner, or keys.  Readily repeatable after restarting cinnamon (leaving long enough for startup applications to launch).

**Comment by Vahan86** [comment]
@brownsr, is this still an issue for you in Cinnamon 3.2?

**Comment by Vahan86** [comment]
@JosephMcc, can we close this issue?
