### ISSUE TITLE
web browser launches without focus using the keyboard shortcut [2.4]

### ISSUE THREAD

**Issue by petrucci4prez** [linuxmint/Cinnamon#3637]
Upgraded to 2.4 on Arch and noticed that when using the keyboard shortcut for the web browser launcher, the browser will launch but will not be in focus.  Sebsequent instances do not have this problem.  Launching with shortcut/terminal does not produce problem.  Using Firefox 33.0.2

**Comment by iohannez** [comment]
I have the same issue on Mint with Cinnamon 2.6.13

**Comment by ManIVIctorious** [comment]
Is this still an issue in cinnamon 3.0?
