### ISSUE TITLE
Laptop screen brightness change crashes windows

### ISSUE THREAD

**Issue by ghost** [linuxmint/Cinnamon#3639]
Changing the laptop screen brightness has some unexpected results.

1) Changing the laptop screen brightness using the built in keyboard hotkeys crashes some windows (Thunderbird for example). 

2) Pressing the brighten or dim keys once acts like it has been held for a few seconds. I.E if you press it once it will go full dark, press it again its 40% press it again its 90% etc its random. If you hold the brighten or dim keys the brightness will cycle randomly for an extended amount of time. For example if I hold the brightness key for about 5 seconds, the brightness will cycle dark/light/dark/light/dark/light for about 45+ seconds.

Gateway NE71B, Mint 17 Cinnamon (2.2.16) x64
Linux Kernel 3.13.0-24
xserver-xorg-video-ati 1:7.3.0.1ubuntu3.1

**Comment by Vahan86** [comment]
@ghost, is this issue still relevant to Cinnamon 3.2?

**Comment by Vahan86** [comment]
@JosephMcc, can we close this issue?
