### ISSUE TITLE
[FEATURE REQUEST] Password to Lock Desktop Layout

### ISSUE THREAD

**Issue by Malsasa** [linuxmint/Cinnamon#3645]
It would be great if Cinnamon has a lock mechanism to avoid any change to the current desktop layout. And it will be perfect if the lock given password to avoid accidental changes.

Example: 

- I have 10 PCs on my lab.
- I set every Cinnamon to have 8 workspaces.
- Plus a clock widget in every desktop. 
- I don't want users to change either it is on purpose or not, my desktop settings. 
- So, I just lock the desktop layout and set a password in every PC.
- No user can change them after me, unless he has the password.

**Comment by dalcde** [comment]
Apart from the fact that this is not technically feasible to implement without HUGE structural changes, there really isn't any point in doing so. If you don't want users to change your settings, then DON'T LET THEM USE YOUR ACCOUNT! Even if you want to keep your current setup, you don't password-lock the desktop settings. They are not confidential information! You can write a script to restore desktop settings on login, or implement something like guest accounts. Password locking is just ... too much.
