### ISSUE TITLE
Can't find how to change "Sunday" as first day of the week.

### ISSUE THREAD

**Issue by DrOptix** [linuxmint/Cinnamon#3655]
The title explains it all. I can't find a way to change the damn ugly Sunday as the first day of the week. I want a normal, Monday starting calendar, even if I use en-us locale for other aspects of the desktop.

I'm sure there must be some arcane way to do it by editing some config file, but the calendar plugin should be able to set this from the GUI.

Thank you!

**Comment by dalcde** [comment]
Fixed in git master
