### ISSUE TITLE
Bottom panel appears over the bottom of windows when using Mint-X theme

### ISSUE THREAD

**Issue by kenden** [linuxmint/Cinnamon#3658]
Cinnamon 2.4 beta (in Mint 17 romeo)

When using the Mint-X theme,
the bottom panel appears over the window underneath, so it is not possible to see the bottom of the program you are using.
Attaching video with Terminal. The bottom of the fullscreen Terminal cannot be seen.

![withmint-x](https://cloud.githubusercontent.com/assets/480586/4936473/bf943436-65b9-11e4-8dcd-dff8274dcce2.png)
![withoutmint-x](https://cloud.githubusercontent.com/assets/480586/4936472/bf8fe232-65b9-11e4-8b17-b8f845b4cedd.png)

**Comment by ManIVIctorious** [comment]
Is this still an issue in cinnamon 3.0?

**Comment by JosephMcc** [comment]
This seem to fine, at least in the latest git. It used to happen when you changed themes and the theme you changed to used a different panel height then the one you were coming from.

Can't reproduce it anymore.
