### ISSUE TITLE
QT5 won't respect GTK theme inside Cinnamon

### ISSUE THREAD

**Issue by geckolinux** [linuxmint/Cinnamon#3663]
Hi,

I'm running Cinnamon 2.4 on openSUSE 13.2. I've tried everything to make QT5 apps obey the font settings, above all the DPI setting. QT5 apps are almost unreadable on my high resolution screen under Cinnamon. QT5 apps do obey the Gnome font settings when launched under Gnome Shell, but they look totally different under Cinnamon. I tried the following environment variables:

> export DESKTOP_SESSION="gnome"
> QT_STYLE_OVERRIDE=gtk

But the fonts are still not at the right DPI.

Could something be done in Cinnamon to make QT5 apps obey the Cinnamon fonts settings, above all the DPI? 

Thanks a lot!

**Comment by sb56637** [comment]
I tried opening a new bug, because the issue persists, and QT isn't taking any action on the old, closed bug.
https://bugreports.qt.io/browse/QTBUG-43745
