### ISSUE TITLE
changing input method while in Menu is impossible

### ISSUE THREAD

**Issue by mxa** [linuxmint/Cinnamon#3669]
when in the Menu (the button in the launcher menu in the corner) there is no way to change the input method. so when i want to launch a program but am currently in a non-latin input method, i can't type the name of the program to launch. i need to close the menu first, then change the input method (ctl=space in my case) then open the menu again. a little bit cumbersome.

**Comment by Vahan86** [comment]
The issue is fixed in Cinnamon 3.0.7. Now you can change а keyboard layout when the Menu is open.

@JosephMcc can we close this issue?

**Comment by JosephMcc** [comment]
@mxa is this fixed for you in the current version of Cinnamon?

@Vahan86 I'd like to give the OP a chance to confirm/deny before closing.

**Comment by mxa** [comment]
I can confirm that it works now for me. However, since the original issue report I switched from IBUS to fcitx.
