### ISSUE TITLE
Connection applet icon doesn't update after login with VPN

### ISSUE THREAD

**Issue by kehugter** [linuxmint/Cinnamon#3670]
Running Mint 17 Cinnamon v2.2.16 x64

Related packages:
* openvpn
* network-manager-openvpn-gnome

Steps:
* Connect to the VPN. The icon changes from "wireless" to "LAN with padlock"
* Log out. Do not disconnect from the VPN
* Log in again. The connection applet icon is now "wireless" without padlock, but the VPN is connected

**Comment by Vahan86** [comment]
@kehugter, is this still an issue in Cinnamon 3.0?

**Comment by kehugter** [comment]
Can't tell, have been using the terminal to manage my connections since long.

**Comment by JosephMcc** [comment]
others:
https://github.com/linuxmint/Cinnamon/issues/3671
https://github.com/linuxmint/Cinnamon/issues/4616

**Comment by kenden** [comment]
I get this issue in Cinnamon 3: https://github.com/linuxmint/Cinnamon/issues/5527

**Comment by JosephMcc** [comment]
@kenden Thanks.
