### ISSUE TITLE
Wireless + VPN connection applet icon

### ISSUE THREAD

**Issue by kehugter** [linuxmint/Cinnamon#3671]
Cinnamon 2.2.16

I noticed that the connection applet icon changes from "wireless" to "LAN with padlock" after connecting to a VPN (using openvpn). In Mate, you get a "wireless with padlock" icon. Shouldn't that be the behaviour in Cinnamon too?

**Comment by pixunil** [comment]
@JosephMcc is this more or less a icon name issue?

**Comment by kehugter** [comment]
Update: in Cinnamon 2.6.13 it changes from wireless to normal LAN icon, without padlock.

**Comment by pixunil** [comment]
@kehugter, no, I just tried it, it's still with padlock (`2.8` here)

**Comment by kehugter** [comment]
I see. I think it has to do with the fact that I no longer use Mint, but Debian, and installed the X-Mint icon pack separately (downloaded from the mint repos). I found a few desktop snapshots still running Mint Cinnamon 17.2 and you're right, 2.6.x had a padlocked LAN icon.

The original issue remains unchanged then.

**Comment by JosephMcc** [comment]
@pixunil I would assume we are just asking for the wrong named icon in this case. Somewhere we are probably just asking for the same one regardless of the connection being wired or wireless.

**Comment by pixunil** [comment]
@JosephMcc yes, see [line 2246](https://github.com/linuxmint/Cinnamon/blob/7384c438a9ef47e5ee490b7972571d0bba096f15/files/usr/share/cinnamon/applets/network%40cinnamon.org/applet.js#L2246) and [line 2190](https://github.com/linuxmint/Cinnamon/blob/7384c438a9ef47e5ee490b7972571d0bba096f15/files/usr/share/cinnamon/applets/network%40cinnamon.org/applet.js#L2190).
There is `network-vpn` and `network-vpn-acquiring`.

******

My question was if there is actually an icon name that it used by most icon themes that represents vpn connection on a wireless setup. I can't find one in those I've installed.
It would be a very quick fix to implement a `network-vpn-wireless-<strength>` in Mint-X, but other themes would fail.
Please let me know if I'm taking something wrong as I assume we have no "fallback" icon mechanism.

**Comment by JosephMcc** [comment]
More up to date: https://github.com/linuxmint/Cinnamon/issues/5527
