### ISSUE TITLE
Cinnamon 2.6.13 .xsession-errors recursively populated with disconnected bluetooth devices errors

### ISSUE THREAD

**Issue by MarceloRuiz** [linuxmint/Cinnamon#3672]
Linux mint 17, linux 3.17.2-031702-generic, nvidia driver 340.58, Toshiba Qosmio X500 - core i7 (first gen)

I noticed the problem after installing Cinnamon 2.4.1 from Romeo
The .xsession-errors file is recursively populated with this errors:

glibtop: Failed to open "/sys/class/net/18:83:31:1D:03:D8/statistics/rx_packets": No such file or directory
glibtop: Failed to open "/sys/class/net/18:83:31:1D:03:D8/statistics/tx_packets": No such file or directory
glibtop: Failed to open "/sys/class/net/18:83:31:1D:03:D8/statistics/rx_bytes": No such file or directory
glibtop: Failed to open "/sys/class/net/18:83:31:1D:03:D8/statistics/tx_bytes": No such file or directory
glibtop: Failed to open "/sys/class/net/18:83:31:1D:03:D8/statistics/rx_errors": No such file or directory
glibtop: Failed to open "/sys/class/net/18:83:31:1D:03:D8/statistics/tx_errors": No such file or directory
glibtop: Failed to open "/sys/class/net/18:83:31:1D:03:D8/statistics/collisions": No such file or directory

The hardware addresss mentioned (18:83:31:1D:03:D8) is my bluetooth adaptor.
Minutes after starting the session the log file is 13 Mb!!! I could not upload a zip version of it, so here is a link to it:

https://dl.dropboxusercontent.com/u/7707848/xsession-errors.zip

Maybe this is causing the super low transition (1+ min) from MDM to Cinnamon? I notice a lot of I/O activity in my hard drive during the transition...
The problem is that the file keeps growing and growing...

**Comment by ccadeptic23** [comment]
This is the dev for the applet can u tell me what kind of adapter you are using. I have not seen this issue before. I am using libgtop to get the statistics for the applet. If the adapter is not playing nice with that library there maybe little i can do.

**Comment by MarceloRuiz** [comment]
@ccadeptic23
Hi, sorry for the late comment. The problem still shows up in the most current version of Cinnamon.
The bluetooth device is a headset (that is not always connected). Maybe there is something in libgtop that tells you if the bluetooth device is actually disconnected, so you can safely skip it in your loop.
This error causes Cinnamon to take a long time to first load (actually it collapses the log in .xsession-errors until the log limit is reached).

**Comment by kaefert** [comment]
I just experienced the same problem with the multicore-sys-monitor applet. turning off the "mac-address"-named device in it's configurations "Network"-Tab stops the spamming.

**Comment by k2qwerty2k** [comment]
Patched already in upstream for cinnamon version 3.4+
https://github.com/linuxmint/cinnamon-spices-applets/commit/6d6aa95e434457bab5c248fd128154dd5bfa2091#diff-1491592cfc63b99e463c71047e690bc9
