### ISSUE TITLE
A setting to orient workspaces vertically instead of horizontally

### ISSUE THREAD

**Issue by thestagemanager** [linuxmint/Cinnamon#3673]
Currently, in at least a simple 2 workspace configuration, the two spaces are oriented horizontally to each other and there is no easy way to change this.

A partial workaround would be to simply remap the keyboard shortcuts so that CTRL+ALT UP/DOWN do the switching instead of LEFT/RIGHT.  However, this doesn't affect the fact that the desktop animations visually continue to move everything in the original horizontal orientation.

For multi-monitor desktops, some may prefer the desktop switching to move in an up/down direction between spaces.  So, if there were a way to actually re-arrange the geometry of the workspaces so that switching truly worked in a vertical fashion, that would be really cool.

**Comment by ManIVIctorious** [comment]
related to #3347

**Comment by JosephMcc** [comment]
I'm going to leave this open for now but I wouldn't hold my breath. The consensus among the devs has generally been that we don't have any desire to support vertical or grid type workspace layouts. Partially because so many things are tied to the a horizontal type of layout.

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html
