### ISSUE TITLE
Connections applet - list of available connections doesn't display correctly

### ISSUE THREAD

**Issue by ghost** [linuxmint/cinnamon#3678]
Cinnamon 2.2.16

The list of available wireless connections sometimes (can't tell how to reproduce) doesn't get trimmed, extending beyond the screen area. This also prevents the hidden VPN connections from being displayed: the arrow button changes direction when clicked, but nothing is shown.

Attempting to connect to another wireless network usually fixes the display.

![screenshot from 2014-11-17 10 31 35](https://cloud.githubusercontent.com/assets/6382342/5067827/3ff8a040-6e47-11e4-9cab-383e5d0ca69c.png)

![screenshot from 2014-11-17 10 34 30](https://cloud.githubusercontent.com/assets/6382342/5067831/4838af3e-6e47-11e4-8a01-b292f3072e6f.png)

**Comment by Lupul** [comment]
I am also affected.
This bug is still present in cinnamon 2.6.7 (Mint)

**Comment by kehugter** [comment]
Still an issue in Cinnamon 2.6.13.

**Comment by kr41** [comment]
Still an issue in Cinnamon 3.0.7

**Comment by icarter09** [comment]
@ghost are you still experiencing this issue?

**Comment by Vahan86** [comment]
@icarter09, can we close this issue?
