### ISSUE TITLE
Linux Mint 17.1 Cinnamon issues

### ISSUE THREAD

**Issue by freemangilgamesh** [linuxmint/Cinnamon#3679]
I want to report the following issues I'm not satisfied with:

1- Some MDM (html) themes not working
2- When you set panel settings to classic mode (two panels) you can't add applets to the bottom panel and if you try to they will be added to the top one.
3- Mint-X Cinnamon themes fonts look blurry. I suggest you replace:
.applet-box {
	font-weight: bold;
	color: rgb(74,74,74);

with:

.applet-box {
	font-weight: bold;
	color: black;

Here is what they should look like in my humble opinion  http://cinnamon-spices.linuxmint.com/themes/view/365

I also suggest this Cinnamon theme to replace the default Linux Mint theme  http://gnome-look.org/content/show.php/openSUSE+KDE+%28Cinnamon%2B+GTK%29?content=167757 
It matches the default wallpaper best.

4- Bootsplash does not match the new Linux Mint style. I suggest a modified  version of this theme http://gnome-look.org/content/show.php/ice-cream%3A+Linux+Mint+plymouth+theme?content=163329

With these issues fixed. I think Linux Mint 17.1  will be the best release ever!

**Comment by dalcde** [comment]
1) Not a cinnamon problem
2) Fixed in master
3) Not a cinnamon problem and is subjective
4) Not a cinnamon problem
5) Fixed
