### ISSUE TITLE
Cinnamon slow to load

### ISSUE THREAD

**Issue by Jason-King1992** [linuxmint/Cinnamon#3681]
Just like the title says, cinnamon desktop start up so slowly after Login.

detailed description：
After inputing username and password, then I press enter key,there is showing a black screen with cursor（about 10-15 seconds ）,and finally the Cinnamon Desktop appears.

Does anybody know what's wrong?And how to deal with this "bug"? For example,modify Cinnamon source code,modify the configuration files,or update some software and so on...

Uh,by the way,maybe we can try to use a picture to replace the black screen when the Cinnamon start up.But how to realize it ? 

Look forward to your help ::>_<:: 

(In addition,My system is "Linux Mint 17 Qiana (Cinnamon Edition)",and my display manager is MDM.)

**Comment by Vahan86** [comment]
I have the same issue with Cinnamon 3.2. It takes about 1 minute to load the desktop.

**Comment by leigh123linux** [comment]
Not one of you have posted hardware specs or ~/.cinnamon/glass.log

**Comment by Vahan86** [comment]
System:    Kernel: 4.4.0-53-generic x86_64 (64 bit gcc: 5.4.0)
           Desktop: Cinnamon 3.2.7 (Gtk 3.18.9-1ubuntu3.1) dm: mdm Distro: Linux Mint 18.1 Serena
Machine: Hewlett-Packard (portable) product: HP ENVY 15 Notebook PC
CPU:       Quad core Intel Core i7-4710HQ (-HT-MCP-) cache: 6144 KB
Graphics:  Card: Intel 4th Gen Core Processor Integrated Graphics Controller
           Display Server: X.Org 1.18.4 drivers: intel (unloaded: fbdev,vesa)
Drives:    HDD Total Size: 1500.3GB

**Comment by r1sknt** [comment]
I've just installed cinnamon 3.2.8 on Ubuntu and it takes more than a minute to load!

**Comment by leigh123linux** [comment]
If this is still an issue in cinnamon-3.6.x feel free to open a new issue for it, remember to include hardware specs and ~/.cinnamon/glass.log
