### ISSUE TITLE
Rendering glitches with cinnamon HEAD on Nvidia graphics cards

### ISSUE THREAD

**Issue by wrouesnel** [linuxmint/Cinnamon#3683]
Since one of the more recent Cinnamon updates, I've been experiencing severe rendering glitches with Cinnamon on my systems with Nvidia graphics cards. Both my laptop running bumblebee with nvidia, and a separate desktop running nouveau will periodically stop drawing text properly on cinnamon desktop elements and refuse to display windows properly.

Cinnamon HEAD on my desktop with open source radeon drivers displays none of the same problems.

http://i.imgur.com/l0k8vfc.jpg

This is from my laptop, interestingly none of the other windows have the problem. `cinnamon --replace` will fix the problem briefly before it returns.

**Comment by Vahan86** [comment]
@wrouesnel, is this still an issue for you in Cinnamon 3.0?

**Comment by Vahan86** [comment]
@JosephMcc, can we close the issue?
