### ISSUE TITLE
startup animation doesn't support login dialog fading

### ISSUE THREAD

**Issue by cjjnjust** [linuxmint/Cinnamon#3684]
Dear Dev Team
Great job to mint 17.1!!!

I noticed that login dialog doesn't fading out and there still a time interval between logging on and desktop showing up,  while comments in js/ui/layout.js say that would be supported if it is greeter session.

**Comment by dalcde** [comment]
the comments were... wrong! Both effects you mentioned are intended. Since the login dialog is not managed by Cinnamon, it would be difficult to make a nice transition effect in between. And there is time between loggin on and desktop showing because it takes time for things to load.
