### ISSUE TITLE
Handling of frozen X forwarded windows

### ISSUE THREAD

**Issue by bulldozer2003** [linuxmint/Cinnamon#3687]
I use X forwarding fairly often and when the SSH connection stops transferring packets, but doesn't die, the entire desktop freezes. Sometimes the connection begins working again and the desktop becomes responsive again, but sometimes I have to kill SSH (in another vtty) and the windows just disappear. I've observed this in cinnamon both "natively" in Qiana and when installed in ubuntu. When the SSH connection is killed, the forwarded windows disappe

When the same thing happens in unity shell (Ubuntu) the forwarded window fades to grey, but the rest of the desktop is usable. Perhaps something like that can be implemented in cinnamon.

**Comment by Vahan86** [comment]
@bulldozer2003, does this issue still occur in Cinnamon 3.0?

**Comment by Vahan86** [comment]
@JosephMcc, can we close the issue?
