### ISSUE TITLE
Dark colour Cinnamon themes that match Linux Mint 17.1 GTK/ icon themes

### ISSUE THREAD

**Issue by freemangilgamesh** [linuxmint/Cinnamon#3689]
I have made 7 dark cinnamon themes for Linux Mint 17.1 that match the GTK/ icon themes. I named them as follows:
LinuxMint-Purple: http://gnome-look.org/content/show.php/LinuxMint-Purple?content=167944
LinuxMint-Blue: http://gnome-look.org/content/show.php/LinuxMint-Blue?content=167945
LinuxMint-Orange: http://gnome-look.org/content/show.php/LinuxMint-Orange?content=167943
LinuxMint-Ghost: http://gnome-look.org/content/show.php/LinuxMint-Ghost?content=167942
LinuxMint-Red: http://gnome-look.org/content/show.php/LinuxMint-Red?content=167941
LinuxMint-Green: http://gnome-look.org/content/show.php/LinuxMint-Green?content=167940
LinuxMint-Yellow: http://gnome-look.org/content/show.php/+LinuxMint-Yellow+?content=167939
and they are all variations openSUSE KDE theme that I made http://gnome-look.org/content/show.php/openSUSE+KDE+%28Cinnamon%2B+GTK%29?content=167757

I want to suggest these themes to the Linux Mint developers. I hope you like them.

**Comment by dalcde** [comment]
Not a cinnamon issue
