### ISSUE TITLE
scrollbar configuration in Sys Settings

### ISSUE THREAD

**Issue by jelabarre59** [linuxmint/Cinnamon#3691]
Since various theme makers have the mistaken impression that no one uses scrollbar arrows, and in various cases don't want scrollbars that are wide enough to use, I think there needs to be a separate configuration for scrollbars in "System Settings" under "Appearance". At minimum there needs to be a setting under "Themes" to override what a particular theme does, so you can force a minimum scrollbar width as well as force a theme to show scrollbar arrows.  Seeing as there are 2 sets of GTK libraries, this will have to set GTK2 as well as GTK3.

**Comment by nardholio** [comment]
Except the default cinnamon themes lack scrollbars, so it is kind of Cinnamon's fault

**Comment by GLolol** [comment]
@nardholio The default theme that Cinnamon uses depends on where you're getting it from. It will usually use GNOME's Adwaita theme as a default (on most distros), or Mint-X if you're running it on Linux Mint. Regardless, you should be contacting those developers instead. Cinnamon is a desktop environment, not a GTK theme!

**Comment by jelabarre59** [comment]
But there should be a way to tweak that value within the entire UI.  Rather than having to contact a few hundred theme makers, have **ONE** place to fix the problem.  How does it make sense to have to hunt down a multitude of theme makers, who probably have their own "vision" which will be in conflict with actual usability.

**Comment by nardholio** [comment]
I gave up and switched to clearlooks-phenix which has the arrows. In doing so I noticed another bug, Chrome is using the KDE settings for gtk themes instead of my actual gtk settings. But that's a different discussion.

**Comment by jelabarre59** [comment]
>  I gave up and switched to clearlooks-phenix which has the arrows. In doing so I noticed another bug, Chrome is using the KDE settings for gtk themes instead of my actual gtk settings. But that's a different discussion.
   
Yeah, I notice the only answer people want to give on this glaring defect is to limit myself to butt-ugly themes.  With that sort of "we're right and you're wrong" I might as well be using MSWin or OS-X.

**Comment by KAMI911** [comment]
Hi Folks,
What about to add three state Theme settings (Enable, Disable, Use Theme default settings) that include a css file in /.config/gtk-3.0/gtk.css
For example:
@import url("/usr/share/cinnamon/cinnamon-settings/data/theme/gtk-scrollbar-enable.css");
or
@import url("/usr/share/cinnamon/cinnamon-settings/data/theme/gtk-scrollbar-disable.css");
depending on the three state.
If someone can help me I would happy to implement this feature.
