### ISSUE TITLE
Cinnamon Settings "Preferred Applications" please add preferred file manager

### ISSUE THREAD

**Issue by geckolinux** [linuxmint/Cinnamon#3695]
Hello,

When installing Cinnamon on systems that have Nautilus pre-installed, Nautilus often opens on events such as insertion of USB media or anywhere else that xdg-open is used. This is a problem because 1) the Cinnamon user usually wants Nemo, not Nautilus and 2) Nautilus conflicts with Nemo for managing Cinnamon desktop icons, resulting in [duplicate desktop icons](https://github.com/linuxmint/nemo/issues/761).

The manual way to fix this is by running:

```
xdg-mime default nemo.desktop inode/directory
```

But it would be better if there was a GUI option in Cinnamon Settings, Preferences, Preferred Applications for "Preferred file manager".

Thanks!

**Comment by margamanterola** [comment]
Users may share a computer with other users that want other desktop environments, so claiming that it's the user's problem for having Nautilus installed is not really a good solution. Cinnamon was developed to be used in Mint, but is currently available in many different distributions.

Cinnamon should set nemo to be the preferred file browser by default, and then allow the user to select something else (either through the UI or through dconf).

**Comment by JosephMcc** [comment]
This should actually be implemented now.
