### ISSUE TITLE
Display information when toggling screen mode.

### ISSUE THREAD

**Issue by Zaharid** [linuxmint/Cinnamon#3700]
When I connect my laptop to an external screen and press the Fn screen toggling key, I would like some visual indication (Eg, OSD) explaining in which mode I am in. Since it takes some time for the screen to change, it is easy to cycle past the desired mode.

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html
