### ISSUE TITLE
 Loading screen on encrypted accounts

### ISSUE THREAD

**Issue by Falconus** [linuxmint/Cinnamon#3703]
When you log into an encrypted account, it takes between half a minute and a minute before you see the desktop. During this time, it is a dark screen with only the cursor. I was thinking that it would be nice (if it isn't too much effort) to put some kind of loading graphic there while it is loading the user account. I think it would make it a little bit nicer for new users who might be wondering "why is my screen black? what's wrong?"

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html
