### ISSUE TITLE
Contextual hot-corners

### ISSUE THREAD

**Issue by tyler71** [linuxmint/Cinnamon#3709]
Normal hot corners works if the mouse goes to the corner and clicks or hovers over it.
To add more commands, you need additional hot corners (maxing at 4 per screen) which increases the chance of accidently hitting the corner.

As a feature request, add the ability to put modifiers in. If you're holding ctrl when going to hot corner, it will do a different command. 

A example setup would be doing nothing when normally hitting the corner, expo with alt, scale with ctrl. Or a normal expo when hitting the corner
I don't see this regressing any functionality while adding a lot of possibility. It would also help with preventing accidently hitting it and having a unwanted command run (even though most of the time it works really well)

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html
