### ISSUE TITLE
Unable to Right Click on Desktop

### ISSUE THREAD

**Issue by TheHerd7** [linuxmint/Cinnamon#3714]
Not completely sure if this is a bug or a choice that was made. However, when the "Show Desktop Icons" option is unchecked, I am no longer able to right click my desktop in order to change wallpaper etc.  If this is enabled, I now have the ability to right click on the desktop.  This was reproduced without fail.  I do not know If this had happened before or not.  

Linux Mint 17.1
Dell Latitude E6430

**Comment by JosephMcc** [comment]
Additional work was done for Cinnamon/Nemo 3.0 to address this. You can find new options in Cinnamon Settings->Desktop
