### ISSUE TITLE
Keyboard layout changes need session restart to take effect

### ISSUE THREAD

**Issue by freemangilgamesh** [linuxmint/Cinnamon#3715]
When you add a new keyboard layout to Linux Mint 17.1 Cinnamon you need to log out to get it working.

**Comment by xhpohanka** [comment]
It seems to be fixed in current Mint updated from Romeo (Cinnamon 2.6.7), is there a way how to fix it also in Arch Linux? Isn't it distribution specific?

**Comment by vladimir-didenko** [comment]
Have the same issue on Alt Linux.

**Comment by Vahan86** [comment]
It works fine for me in Cinnamon 3.0 (Mint 18).

@freemangilgamesh, @xhpohanka, @vladimir-didenko, is this still an issue for you in Cinnamon 3.0.x?

**Comment by vladimir-didenko** [comment]
It works now. I think we can close this issue.
