### ISSUE TITLE
Window List with App Grouping should be included by default in Linux Mint 17.2

### ISSUE THREAD

**Issue by freemangilgamesh** [linuxmint/Cinnamon#3716]
I think that the current Cinnamon layout (panel launcher + Window list) is archaic and messy. I have a cyber cafe and I do lots of work on my desktop and when I open many windows I lose track of my last window because the list become too small to discern. The current "Window List with App Grouping" applet is not compatible with the default linux Mint menu; when I try to add an app to the panel, it adds a whole launcher to the right; "TOTAL MESS WITH A CAPITAL M".

Please consider this issue seriously and don't forget that people get bored with the same look no matter how stable the OS is. Eat spaghetti everyday and you will see what I mean. 

This is what I get with the current layout;

<a href="http://imgur.com/A8GCqHZ"><img src="http://i.imgur.com/A8GCqHZ.png" title="source: imgur.com" /></a>

which should look like this with the exact number of apps running;

<a href="http://imgur.com/1peftAy"><img src="http://i.imgur.com/1peftAy.png" title="source: imgur.com" /></a>
<a href="http://imgur.com/2YIrJhG"><img src="http://i.imgur.com/2YIrJhG.png" title="source: imgur.com" /></a>

I don't think that the current layout has anything to do with elegance or practicality!! It is a mess to hard working people like me.

Think about it!!!!

**Comment by IllyaMoskvin** [comment]
:+1: Window List with App Grouping was the first applet I installed after switching to Linux Mint. Love it. It makes Mint feel more like Win 7 than XP. Wishing that the options to group windows and hide titles were included by default.

I know #67 is the main place to discuss this topic, but I just want to put in my 2¢ to say that WLwAG (?) does it right. That might be the model to follow.

**Comment by freemangilgamesh** [comment]
Yes guys it's time to make Linux Mint rock again!!

**Comment by mcarans** [comment]
Now that Windows List with App Grouping breaks with 18.1, app grouping should be added to the default window list so that an applet is not needed.

**Comment by mcarans** [comment]
We have Icing Task Manager now, but as recent issues around libcjs and crashing illustrate, this functionality should be part of the core Cinnamon to ensure that it works out of the box.

**Comment by jaszhix** [comment]
There are two alternatives that work on Mint 18/19.

https://cinnamon-spices.linuxmint.com/applets/view/269
https://cinnamon-spices.linuxmint.com/applets/view/287

I maintain Icing Task Manager, and its forked from Windows List with App Grouping. CobiWindowList is also a good option.

**Comment by kauffy** [comment]
I highly second Icing. It does exactly what I want a "taskbar" to do.
