### ISSUE TITLE
Cinnamon freezes upon recieving Steam notifications

### ISSUE THREAD

**Issue by raidermax** [linuxmint/Cinnamon#3718]
I am using the latest release Cinnamon (one that just came out, on manjaro/arch linux) and whenever recieving a Steam notifcation, whether it be from a gift or message, the entire Cinnamon panel (including the menu, window buttons, and tray icons/apps) become unusable or inactive. As soon as the notifcation goes away everything on the panel is active again.

**Comment by smdrz** [comment]
this is still happening in 3.x
