### ISSUE TITLE
Cinnamon Volume Tray no longer shows Album cover from Spotify app

### ISSUE THREAD

**Issue by raidermax** [linuxmint/Cinnamon#3719]
Previously, before the latest Cinnamon update, the Volume tray app would display the picture of an album cover on any song. However now it only shows a white CD. I have an image attached to show an example of what it looks like now (I dont have any before pictures but essentially it would just be able to dispaly the album covers)

![screenshot from 2014-12-02 21 09 22](https://cloud.githubusercontent.com/assets/7957970/5274743/9c326658-7a67-11e4-8588-9c4e46fc4431.png)

**Comment by tp0** [comment]
Maybe this has something to do with Spotify itself: I noticed that on albums that show the empty disc icon, in case where you play something before playing that album, they keep showing the previous album's cover.

![screenshot from 2015-02-06 15 22 07](https://cloud.githubusercontent.com/assets/5863551/6079978/143017b4-ae15-11e4-9d74-9993ccb0344e.png)
![screenshot from 2015-02-06 15 24 45](https://cloud.githubusercontent.com/assets/5863551/6079979/14307a9c-ae15-11e4-8e56-3c0dfbb23efa.png)

Ubuntu 14.04
Cinnamon: 2.4.5
theme: Numix-Cinnamon

**Comment by jayeemsuh** [comment]
I'm experiencing similar behavior. Also using Cinnamon on Arch. 

Start Spotify
Play a track from album A --> Sound applet displays correct album art
Play a track from album B --> Sound applet lags on displaying album art and eventually shows album art from another album by same artist
Play a track from album C and a different artist --> Sound applet shows no album art and sometimes wrong album art.

Kernel: 3.19.3-3-ARCH x86_64 (64 bit) Desktop: Cinnamon 2.4.7  Distro: Arch Linux

**Comment by dalcde** [comment]
The sound applet has been rewritten considerably for 2.6. Try using the sound applet from git master.

**Comment by JosephMcc** [comment]
Since no one has responded to @dalcde request and the sound applet has seen a considerable amount of changes, I'm closing this.

**Comment by Salamandar** [comment]
Well I got the same problem (before and) after the 2.8 update (Manjaro, stable then unstable channel).
Where could I see any log ?
glass.log or cinnamon --replace inside a terminal don't show anything.

**Comment by Salamandar** [comment]
OK, I think I found the problem.
For some albums, the player uses the .jpg/.png file it finds.
For others, it uses the embeded image inside one of the music files of the album.

In the first case, no problem ! The applet finds the cover.
In the second… I don't know how is sent the image info to the audio daemon, but the applet doesnt show anything.
