### ISSUE TITLE
Items in Window List disappear if Window List applet is removed and readded

### ISSUE THREAD

**Issue by GLolol** [linuxmint/Cinnamon#3720]
Running Cinnamon 2.2.16-4 from Debian jessie/sid's official repository. 

When the Window List applet is removed, all apps that were present in it before disappear! Alt-Tab will still work fine, and it's possible to fix the issue by just restarting every app affected. New apps are added and still behave like like normal: [Quick video demonstration](https://secure.overdrive.pw/f/cinnamon-windowlist-applet.mp4)

**Comment by dalcde** [comment]
Fixed in git master

**Comment by GLolol** [comment]
:+1:
