### ISSUE TITLE
Add Option to Mouse and Touchpad Settings: Disable touchpad when mouse is plugged in

### ISSUE THREAD

**Issue by mfreeman72** [linuxmint/cinnamon#3721]
In the Mouse and Touchpad settings, in the touchpad tab, there are options to automatically disable the touchpad while typing, but I would also like to see the option to disable it when a mouse is plugged in. This has been done in the past through a touchpad applet (which now doesn't work after the Cinnamon 2.4 update). With the exception of this one feature, that applet was redundant, as all other functions are covered by system settings in the Mouse and Touchpad window. It would seem more appropriate to me to have this feature also as a system preference rather than taking up space on the panel.

**Comment by mtwebster** [comment]
Someone was on irc earlier working on this, though I don't know their github name - I had worked on this some time back:

https://github.com/mtwebster/cinnamon-settings-daemon/commit/f7b7d112b8d334fed26877281cb2d0e5257b463c

I'm honestly not sure what the issue was, why i didn't commit it - I think it had something to do with mis-identification of devices, so I put it off to the side, but here it is if interested.

**Comment by mfreeman72** [comment]
Is there any way to adapt the Gnome Touchpad Indicator Extension (https://extensions.gnome.org/extension/131/touchpad-indicator/) into a Cinnamon Applet? That would serve the purpose fairly well if this isn't a feature the Cinnamon devs are willing to add anytime soon. I wouldn't know where to even begin doing something like this, myself, so I don't know if it's even possible.

**Comment by Skillzore** [comment]
No solution to this yet? not even a workaround? :/

**Comment by mfreeman72** [comment]
So... after about 5 years of waiting for any movement toward this feature, should I assume this is a no from the devs?

**Comment by JosephMcc** [comment]
I haven't looked at this so don't know how difficult this would be to implement. But it could be that or just no one has picked it up to work on it more.

**Comment by mtwebster** [comment]
https://github.com/linuxmint/cinnamon/commit/9ed0e388cf050b9742949f4ff075152adacc4610

**Comment by yuritoledo** [comment]
@mtwebster How can i update cinnamon to enable it?
