### ISSUE TITLE
Screen locker changes desktop resolution when HDMI KVM is switched to other machine

### ISSUE THREAD

**Issue by chrispitude** [linuxmint/Cinnamon#3726]
I've got a fresh Linux Mint 17.1 Cinnamon installation on an i7-4790k box with integrated graphics. It's driving a 24" monitor through an HDMI KVM.

When the box boots up, the desktop displays at the native 1920x1200 resolution. When I switch the KVM focus away from the linux box, the desktop resizes itself to 1024x768 when the desktop screen locker activates. When I switch back to the linux box, everything is at 1024x768. If I run Preferences/Display, the resolution immediately switches back to 1920x1200 as soon as the window opens. If the KVM focus is on the linux box, the screen locker activates normally with no behavior change. I assume it's somehow triggering a default resolution change when the locker activates and the computer can't "see" the monitor through HDMI.

I can prevent this issue by disabling all settings in Preferences/Screen Locker/Lock Settings. I am able to keep display shut-down enabled in Power Management/Power Options.

**Comment by Vahan86** [comment]
@chrispitude, is this still an issue for you with Cinnamon 3 (Mint 18)?

**Comment by JosephMcc** [comment]
This will probably need to be retested in Cinnamon3.2 since it has an all new screensaver.

**Comment by chrispitude** [comment]
Unfortunately I no longer have this machine, KVM, or monitor. I cannot
retest. :(

**Comment by JosephMcc** [comment]
Ok, since no one else has reported this issue I'm going to close it.
