### ISSUE TITLE
Add smooth transitions for background slideshow

### ISSUE THREAD

**Issue by cschreib** [linuxmint/Cinnamon#3727]
The background slideshow is a very nice addition to cinnamon 2.4. However, the transition between two background images is too sharp. It would look much nicer to introduce at least a cross-fade animation, lasting maybe a second or two (customizable).

**Comment by JosephMcc** [comment]
Done https://github.com/linuxmint/muffin/commit/5b7656c0ac389e8b974f27db080893ddb87f1ead
