### ISSUE TITLE
Different mouse cursor when navigating online extensions, desklets, and applets

### ISSUE THREAD

**Issue by raidermax** [linuxmint/Cinnamon#3728]
I am using Cinnamon 2.4.5 and whenever I go into System Settings > Applets or Extensions or Desklets and go into the tab that allows me to view and install online applets, extensions, or desklets, the mouse cursor changes from my default cursor to a very weird looking one.

I would post a screenshot but whenever I do take a screenshot, the pointer is of the cursor that I like and not the strange one that only appears in the places that I listed above. The pointer is rather skinny and is tilted id say 45 degrees to the right.

**Comment by raidermax** [comment]
This is still occurring on the latest Cinnamon release.

**Comment by dalcde** [comment]
What cursor theme are you using? Also you might try taking a photo of your computer monitor.

**Comment by Vahan86** [comment]
@raidermax, is this still an issue for you in Cinnamon 3.0.x?

**Comment by Odyseus** [comment]
Hello, everybody.

@Vahan86: This happens to me too. But I don't think that it is a problem with Cinnamon. I used see this *strange* cursors in certain parts of XFCE too. It seems to only happen with cursor themes created for KDE.

This image is of the [Capitaine](https://www.gnome-look.org/p/1148692/) cursor theme on the **Available applets (online)** section:

![cursor-capitaine-on-applets-window](https://cloud.githubusercontent.com/assets/3822556/18817475/66adc95c-8337-11e6-883f-558cf645bc0a.png)

And this is an image of the Breeze-AIO cursor theme (don't remember where I got this theme) on the same window:

![cursor-breeze-on-applets-window](https://cloud.githubusercontent.com/assets/3822556/18817477/76209d1a-8337-11e6-92b7-94e4a291f259.png)

When the correct cursor should look like this:

![cursor-capitaine-correct](https://cloud.githubusercontent.com/assets/3822556/18817478/8022b8ac-8337-11e6-9ba3-1137b9510972.png)

With the Adwaita cursor theme the **Available applets (online)** window displays the correct cursor. My guess is that there must be a missing file inside the **cursors** folder of the cursor themes that we are using. This doesn't bother me that much, so I never investigated the issue further.

**Comment by JosephMcc** [comment]
@Odyseus Thanks for the additional info.

**Comment by Vahan86** [comment]
@Odyseus, thanks for info.

**Comment by NikoKrause** [comment]
I investigated this issue a little bit.
I used the Capitaine cursor theme. The issue happens, because the cursor theme is missing an cursor icon called `arrow`.

So to fix this issue, you need to create a symbolic link `arrow`, which points to the normal cursor (sometimes called `default` or `left_ptr`) in your custom cursor theme.

**Comment by Odyseus** [comment]
Hello, everybody.

I can confirm @NikoKrause's findings ( 👍 ). By simply adding the `arrow` file to the icon theme, the *Spices window* will start to use the correct icon.

Just as a side note, the new design of the *Spices window* introduced by this [pull request](https://github.com/linuxmint/Cinnamon/pull/6714) will not have the mouse cursor problem, even with the `arrow` file missing on the icon theme.

**Comment by keeferrourke** [comment]
I've updated [Capitaine cursors](https://github.com/keeferrourke/capitaine-cursors) to include an 'arrow' cursor, as per @NikoKrause's request.

**Comment by NikoKrause** [comment]
@keeferrourke Thanks

**Comment by NikoKrause** [comment]
@Odyseus I think you are right. I assume it's because of the line:
```
self.gm_treeview.get_window().set_cursor(Gdk.Cursor.new(Gdk.CursorType.ARROW))
```
in the ExtensionCore.py file.
