### ISSUE TITLE
Slingshot should replace Cinnamon menu

### ISSUE THREAD

**Issue by freemangilgamesh** [linuxmint/Cinnamon#3729]
I think the current Cinnamon should have a more modern look and design. To achieve this I think it should receive Slingshot's design  http://cinnamon-spices.linuxmint.com/applets/view/197. 

<a href="http://imgur.com/VD1yGDP"><img src="http://i.imgur.com/VD1yGDP.png" title="source: imgur.com" /></a>

It is more elegant and practical and it could look even better if we add   user and shutdown icons to it;

<a href="http://imgur.com/AvIn2g2"><img src="http://i.imgur.com/AvIn2g2.png" title="source: imgur.com" /></a>
or something similar to this menu 

<a href="http://imgur.com/0DYQbQs"><img src="http://i.imgur.com/0DYQbQs.jpg" title="source: imgur.com" /></a>

**Comment by dalcde** [comment]
Closing for reasons described above.
