### ISSUE TITLE
Freeze when attempting to lock the screen

### ISSUE THREAD

**Issue by AKSoo** [linuxmint/Cinnamon#3731]
Cinnamon did not recognize any keyboard input. I could move the mouse cursor around, but mouse buttons did not work.

I switched to tty1 for a bit and came back to find Cinnamon in fallback mode. Cinnamon prompted whether I would like it to restart, but I can't interact with it at all.

After killing `cinnamon-screensaver`, I then could give keyboard and mouse input. Of course, I just restarted cinnamon.

version: 2.0.14

suspect excerpts from .xsession-errors
```
(cinnamon-screensaver:2206): Gdk-CRITICAL **: gdk_device_get_source: assertion 'GDK_IS_DEVICE (device)' failed
 ...
*** Error in `cinnamon-screensaver': malloc(): smallbin double linked list corrupted: 0x000000000185d9e0 ***
 ...
** (cinnamon-screensaver-command:8383): WARNING **: unable to send message: Timeout was reached
** Message: Did not receive a reply from the screensaver.
```

**Comment by ManIVIctorious** [comment]
Does this issue still occur  with cinnamon 3.0?

**Comment by JosephMcc** [comment]
Probably not much chance of getting a response from the OP since he says he doesn't use Cinnamon anymore.
