### ISSUE TITLE
Symbols and text on cinnamon panel disappear

### ISSUE THREAD

**Issue by cycelonix** [linuxmint/Cinnamon#3732]
System:
Arch linux
Cinnamon: 2.4.5
Kernel: 3.14.25-1-lts
Intel Core 2 Duo CPU L9400 @ 1.86Ghz x2
4GB Ram
Intel Corporation Mobile 4 Series Chipset Integrated Graphics Controller

2 external montitors plugged in via vga and dvi. But problem also occurs with one monitor

Steps:
1.)  Open any programms like chrome, expolorer, ....
2.) Open some more programms

Actual result: The symbols and text on the panel (partly) disappear. Have a look on the sceenshots. The symbols are not shown, but they can be pressed.

Expected: Symbols and text are shown on the panel, no matters how many open programms.

There is no fixed number of programms. The issue just occurs. Reboot is not necessary. Either open new terminal and type "cinnamon --replace" or [Alt]+[F2] and input "r". Most times the panels are OK afterwoods. Sometimes also a few programms have to be closed in order to have success with this procedure. 
I have already executed "gsettings reset-recursively org.cinnamon" with no success.

Can anyone help me?
Please do not hesitate to ask for logs, .... but I am not sure which one would be usefull.

**Comment by finswimmer** [comment]
I can confirm this with Arch Linux, an Intel Graphic Card and a second screen connected.

It's just a feeling but it seems that the problem doesn't occur if there isn't a second screen. And mostly it appears when a KDE application like okular is started.

**Comment by Vahan86** [comment]
@cycelonix, is this still an issue for you with Cinnamon 3.0?
