### ISSUE TITLE
Bug in Cinnamon 2.4 on Linux Mint 17.1;  window controls not working

### ISSUE THREAD

**Issue by freemangilgamesh** [linuxmint/Cinnamon#3734]
Occasionally window controls are no loger working and it seems like the windows is frozen! This bug happened to me many time on my HP and Dell laptops (Both i3 with 4GB of RAM).

**Comment by danielterhorst** [comment]
Same issue here; loss of control except for everything in the task bar. If I right click and close one of my apps from the task bar, full control is regained. Happens with Qiana, Petra and Rebecca which I am currently using. I'm using a dual monitor set-up.

cinnamon 2.4.5+rebecca amd64

Linux WPL122 3.13.0-39-generic #66-Ubuntu SMP Tue Oct 28 13:30:27 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

**Comment by gordon-morehouse** [comment]
cinnamon 2.4.5+rebecca amd64, graphics card is an nVidia EN GT240.

Linux ws02 3.13.0-37-generic #64-Ubuntu SMP Mon Sep 22 21:28:38 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

*WORKAROUND:* I was able to Ctrl-Alt-F1 into a terminal (which looked like it was in 40-column mode!) and then Ctrl-Alt-F8 back into Cinnamon and the window manager started responding again fine.

**Comment by dalcde** [comment]
#4072
