### ISSUE TITLE
Nemo 2.2.4 Crash and Desktop Disappears

### ISSUE THREAD

**Issue by nimbus396** [linuxmint/Cinnamon#3738]
When opening nemo, the desktop icons disappear.  The issue comes when a DVD, Flash, CD or other disk is captured by a VM.  As you can see from below, nemo cannot read my CD when it is captured by the VM.  Once I unmounted the disk from the VM, nemo worked perfectly and the desktop came back.

open("/usr/share/icons/hicolor/scalable/actions/view-compact-symbolic.svg", O_RDONLY) = 16
fstat(16, {st_mode=S_IFREG|0644, st_size=270, ...}) = 0
read(16, "<?xml version=\"1.0\" encoding=\"UT"..., 8192) = 270
read(16, "", 8192)                      = 0
close(16)                               = 0
open("/media/james/OFFICE14/setup.exe", O_RDONLY) = 16
fstat(16, {st_mode=S_IFREG|0500, st_size=464248, ...}) = 0
read(16, "MZ\220\0\3\0\0\0\4\0\0\0\377\377\0\0\270\0\0\0\0\0\0\0@\0\0\0\0\0\0\0"..., 65536) = 65536
close(16)                               = 0
write(2, "\n(nemo:4492): GdkPixbuf-CRITICAL"..., 106
(nemo:4492): GdkPixbuf-CRITICAL **: gdk_pixbuf_get_n_channels: assertion 'GDK_IS_PIXBUF (pixbuf)' failed
) = 106
write(2, "\n(nemo:4492): GdkPixbuf-CRITICAL"..., 102
(nemo:4492): GdkPixbuf-CRITICAL **: gdk_pixbuf_get_height: assertion 'GDK_IS_PIXBUF (pixbuf)' failed
) = 102
write(2, "\n(nemo:4492): GdkPixbuf-CRITICAL"..., 101
(nemo:4492): GdkPixbuf-CRITICAL **: gdk_pixbuf_get_width: assertion 'GDK_IS_PIXBUF (pixbuf)' failed
) = 101
write(2, "**\nGdk:ERROR:/tmp/buildd/gtk+3.0"..., 251**
Gdk:ERROR:/tmp/buildd/gtk+3.0-3.10.8~8+qiana/./gdk/gdkcairo.c:193:gdk_cairo_surface_paint_pixbuf: assertion failed: (cairo_image_surface_get_format (surface) == CAIRO_FORMAT_RGB24 || cairo_image_surface_get_format (surface) == CAIRO_FORMAT_ARGB32)
) = 251
rt_sigprocmask(SIG_UNBLOCK, [ABRT], NULL, 8) = 0
tgkill(4492, 4492, SIGABRT)             = 0
--- SIGABRT {si_signo=SIGABRT, si_code=SI_TKILL, si_pid=4492, si_uid=1000} ---
+++ killed by SIGABRT +++

**Comment by Vahan86** [comment]
@JosephMcc, I think this issue is related to Nemo and should belong here: https://github.com/linuxmint/nemo.

@nimbus396, does this issue occur in Cinnamon 3.0?

**Comment by JosephMcc** [comment]
Yes it belongs to Nemo and should be moved to the link @Vahan86 provided.
