### ISSUE TITLE
Pidgin tray icons missing in Mint-X theme (solution included)

### ISSUE THREAD

**Issue by janbre** [linuxmint/Cinnamon#3744]
After upgrading from Mint 17 (Qiana, Cinnamon edition) to 17.1 (Rebecca, Cinnamon edition) the tray status icons for Pidgin has disappeared when using any Mint-X theme. The only icon being displayed is a miniature of the one used in the Mint-menu (found at /usr/share/icons/Mint-X/apps/16/pidgin.png), rendering the tray icon next to useless since it only shows you that Pidgin is running and doesn't show your status or notify you of pending messages and new conversations. 

Seems to be caused by the removal of the "pixmaps" folder in this package http://packages.linuxmint.com/pool/main/m/mint-x-icons/
mint-x-icons_1.1.8 contains "pixmaps", in mint-x-icons_1.2.1 and 1.2.3 "pixmaps" does not exist.

In Qiana, there's a folder /usr/share/pixmaps/pidgin/tray containing subfolders "16", "hicolor", "Mint-X" and "Mint-X-Dark". In Rebecca, "Mint-X" and "Mint-X-Dark" is missing. I downloaded the mint-x-icons_1.1.18 and copied the "/usr/share/pixmaps/pidgin/tray/Mint-X" and "/usr/share/pixmaps/pidgin/tray/Mint-X-Dark" folders from the package to /usr/share/pixmaps/pidgin/tray on my system and that solved the problem.

**Comment by gherold** [comment]
Thanks! I spend quite some time searching/replacing a lot of icons in various folders without effect before I found this. Your solution works perfectly (LM 17.1)

**Comment by dalcde** [comment]
File this against Mint-X-icons instead. This is not related to Cinnamon.

**Comment by JosephMcc** [comment]
Actually this should already be fixed in git: https://github.com/linuxmint/mint-x-icons/commit/efa9365b0003daf66a035003e25b155974d19836
