### ISSUE TITLE
Sound applet volume tooltip intermittently remains on screen indefinitely

### ISSUE THREAD

**Issue by Lx** [linuxmint/Cinnamon#3745]
I am frequently finding that the "Volume: _nn_%" tooltip shown by the Sound applet remains on the screen indefinitely after a volume change unless I mouse over the applet again.

Unfortunately I can't find a guaranteed way to reproduce the issue, but it seems to occur more frequently if I perform these steps:

1.  Mouse over the applet.
2.  Wait for the "Volume: _nn_%" tooltip to appear.
3.  Scroll the mouse wheel to change the volume.
4.  Move the mouse away from the applet area.

```
$ cinnamon --version
Cinnamon 2.4.5
```
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	LinuxMint
Description:	Linux Mint 17.1 Rebecca
Release:	17.1
Codename:	rebecca
```

**Comment by pixunil** [comment]
Duplicate of #1833.
