### ISSUE TITLE
"module" alias of environment-modules not defined when GUI login

### ISSUE THREAD

**Issue by chbrandt** [linuxmint/Cinnamon#3747]
I have installed environment-modules version 3.2.10 under Linux Mint Qiana running Cinnamon. The interface command of the package, "module" is not working. Actually, the "module" command is not defined.
 The "module" command is an alias to the "_module" function defined in the file /etc/bash_completion.d/modules. The last line of that file defines the alias: "complete -o default -F _module module". The function is defined at the same file, one object above the alias.
 It seems to be a problem with the user environment initialization under the GUI login. In other words, it seems that with the graphical user interface (cinnamon) login the initialization files are not correctly read/executed. I say that because after installing the environment-modules the shell/environment has to be re-initialized, so that the file added to /etc/bash_completion.d/ is read. The way I do to test is to run "su - username", and test the package installation with a "module avail" command.
 If I do "su - username" or open a non-graphical terminal (a console, ctrl+alt+F?) it works perfectly. But it does not work, even if I reboot the system, under the graphical terminal/interface.
 It is actually strange because the function (e.g, "_module") is defined on my environment. But when I execute it, it raises the error "-su: test: -gt: unary operator expected"; I think becausea variable (COMP_CWORD) is not properly defined. And then -- as far as I understood -- the command "complete" ("complete -o default -F  _module module") does not define the "module" alias once the "_module" function presents error.

**Comment by dalcde** [comment]
/etc/bash_completion.d/modules does not define aliases. It defines *completions*, as the name suggests. https://www.debian-administration.org/article/316/An_introduction_to_bash_completion_part_1

Also, Cinnamon is not gauranteed to read and parse things defined in /etc/bash_*, since Cinnamon is not bash (I don't know if it does, but I would be slightly surprised if it did). Also see this: http://askubuntu.com/a/438170
