### ISSUE TITLE
[regression] Cinnamon unable to switch to 24Hz modes on secondary displays

### ISSUE THREAD

**Issue by Drag0nFly** [linuxmint/Cinnamon#3749]
After much testing I've confirmed that there is an issue with how Cinnamon handles refresh rates on secondary displays.  

This has been tested as working with earlier versions of Cinnamon; last known good version is 1.8.8 (from Olivia). Qiana and Petra both exhibit incorrect behaviour (I went through three complete upgrades and subsequent rollbacks to Olivia as a result of this issue.)

On the same system where this is failing, and using the same drivers, correct behaviour is seen with other DEs, e.g, XFCE4 & Mate. The Desktop manager (MDM) has also been ruled out, as the issue is present when launching Cinnamon (2.2.16) via startx/xinit.

Any attempt to switch to 24Hz causes it to briefly try, then immediately revert back to 60Hz.

Unsuccessful attempts (two tries from within Cinnamon DE):

[ 19644.190](II) intel(0): switch to mode 1920x1080@24.0 on HDMI2 using pipe 1, position (1920, 0), rotation normal, reflection none
[ 19644.455](II) intel(0): switch to mode 1920x1080@60.0 on HDMI2 using pipe 1, position (1920, 0), rotation normal, reflection none
[ 19697.520](II) intel(0): switch to mode 1920x1080@24.0 on HDMI2 using pipe 1, position (1920, 0), rotation normal, reflection none
[ 19697.833](II) intel(0): switch to mode 1920x1080@60.0 on HDMI2 using pipe 1, position (1920, 0), rotation normal, reflection none

Succcessful attempt (from within Gnome MATE):

[  1900.389](II) intel(0): switch to mode 1920x1080@24.0 on HDMI2 using pipe 1, position (2560, 0), rotation normal, reflection none
[  2290.400](II) intel(0): resizing framebuffer to 2560x1600
[  2290.400](II) intel(0): switch to mode 2560x1600@60.0 on eDP1 using pipe 0, position (0, 0), rotation normal, reflection none

I can provide xtraced xrandr output if needed, but the issue should be easy enough to independently reproduce. From looking at reports online there are other people experiencing the same issue.

**Comment by Vahan86** [comment]
@Drag0nFly, is this issue still relevant to Cinnamon 3.2?

**Comment by Vahan86** [comment]
@JosephMcc, can we close this issue?
