### ISSUE TITLE
[Sound applet] slider position goes backwards when using VLC

### ISSUE THREAD

**Issue by aukevo** [linuxmint/Cinnamon#3750]
When a media player seeks and send updates via MPRIS over DBus, the sound applet can get its displayed position out of sync by upto a second.  Play any media with VLC AND seek 1/2 way through, the sound applet slider position will jump backwards and forwards in time as vlc plays. 

The cause is the sound applet runs its own clock to display playback position progress, when a media player sends a MPRIS Seeked over DBus, sound applet leaves its clock running while updating and may get a timer tick immediatly after the update or up to one second after the update. the timing is unpredictable. 

Solution is to restart the sound applets timer when playback position is updated via MPRIS/DBus so the 1 second tick actually happens 1 second after the update.

Here is a patch against the ubuntu utopic nightlies from thursday the 11th december. The patch stops and restarts the timer when a MPRIS/DBus position update happens.

BTW I am not a .js programmer!!  so check I'm not doing something naughty in the .js world.
my version of the _setPosition function:

    _setPosition: function(value) {
        if (value == null && this._playerStatus != 'Stopped') {
            this._updatePositionSlider(false);
        }
        else {
            this._currentTime = value / 1000000;
            if (this._playerStatus == 'Playing') {
                if (this._timeoutId != 0) {
                    Mainloop.source_remove(this._timeoutId);
                    this._timeoutId = 0;
                }
                this._timeoutId = Mainloop.timeout_add_seconds(1, Lang.bind(this, this._runTimerCallback));
	        }
            this._updateTimer();
        }
    },

**Comment by pixunil** [comment]
I don't really notice this bug on my machine with normal playing speed, but it could be a little issue, as the difference will only be some seconds. The code looks fine to me, I can include it in my PR #3858.

Regarding playing media on faster / slower speed: this is a bigger issue imo, and could be fixed with the [rate property](http://specifications.freedesktop.org/mpris-spec/latest/Player_Interface.html#Property:Rate).

**Comment by mtwebster** [comment]
fixed as of 05f65cf
