### ISSUE TITLE
Colors are "bleached out" after waking up computer

### ISSUE THREAD

**Issue by NeoGeo64** [linuxmint/Cinnamon#3753]
OK, this has been an issue ever since I 17.1 RC. This never happened to me in 17.0. I am running the final release of 17.1 Rebecca Cinnamon.

Every time when I leave my computer and it locks, when I come back and unlock the screen the colors and everything is white and black and has a "whiteout/bleached-out" effect. It doesn't cause any issue except very strange colors. The only way I can resolve it is hit CTRL+ALT+F5 (or any other terminal screen) and then go back to the GUI by pressing CTRL+ALT+F7, which returns the colors back to normal or by rebooting the computer.

I tried taking a screenshot of how it looks when it's crashed but when I looked at the screenshot the colors were normal! Basically, it's looks like someone drew my desktop with coloring pencils on a white peice of paper. I see outlines and strange colors, it's actually pretty trippy. However, I want to get work done and I love Linux Mint. I know this is just a strange glitch or bug and I'm asking has anyone else experienced this or something similar? I would love help on this. I am running the free X.org drivers. My card is the AMD Radeon HD 7570. My computer is a Dell XPS 8700. I have a 1TB HDD and Linux is the only operating system installed. There is no Windows on my computer at this time. (if that matters)

Please, any assistance would be appreciated. This is annoying bug. This never happened to me in 17.0. I won't ditch Mint because of this but it does make me sad. :(

Please help! =)

Also, upon further investigation I found that this doesn't happen every time. I closed out every program I was using and let the computer go into lock mode (10 minutes) and unlocked it. Screen was fine. So, I have made a note about everything I had open when the glitch happened. Totem, FIrefox (YouTube's HTML5 player with a video loaded up or playing, Flash being used on other websites). These are the only two logical things. It appears that having one of these open makes the video card driver go crazy when the computer goes to "sleep" (locked screen) and is "woken up" (password prompt). I'll test out these two programs and let you all know. In the meantime, however, please provide me with your best guesses or expertise. Thanks!

~ Neo

**Comment by dalcde** [comment]
Closing this as fixed/upstream driver issue.
