### ISSUE TITLE
Too high CPU usage when playing video

### ISSUE THREAD

**Issue by iwis** [linuxmint/Cinnamon#3759]
In Linux Mint 17.1 64-bit, during playing a movie from a file in VLC or playing DVB-T stream in XBMC (using tvheadend) the usage of CPU by Cinnamon is in my opinion too high (see screenshot). I wasn't moving any windows while playing the movie so in my opinion CPU usage by Cinnamon should not be so high. I don't remember so high CPU usage in Mint 17.0. The problem is greater when I play HD DVB-T stream. XMBC uses about 18% itself, and Cinnamon uses additional 18-45%! Total 40-60% results in notebook fan being noisy, what is not desirable when watching TV.

![screenshot](https://cloud.githubusercontent.com/assets/8080496/5424945/f34cba66-8303-11e4-88ed-32ad4531993f.png)

![screenshot2](https://cloud.githubusercontent.com/assets/8080496/5425060/d9b92d4c-8307-11e4-80ee-627cb9a1ba6b.png)

My configuration (I downgraded nVidia driver because of https://bugs.launchpad.net/linuxmint/+bug/1401526 bug):
inxi -Fxz
System:    Host: darek-Lenovo-IdeaPad-Y550 Kernel: 3.13.0-37-generic x86_64 (64 bit gcc: 4.8.2)
           Desktop: Cinnamon 2.4.5 (Gtk 3.10.8~8+qiana) Distro: Linux Mint 17.1 Rebecca
Machine:   System: LENOVO (portable) product: 20017 v: Lenovo IdeaPad Y550
           Mobo: LENOVO model: KIWB1 v: REFERENCE Bios: LENOVO v: 15CN35WW(V2.08) date: 03/15/2010
CPU:       Dual core Pentium T4400 (-MCP-) cache: 1024 KB flags: (lm nx sse sse2 sse3 ssse3) bmips: 8777 
           clock speeds: max: 2200 MHz 1: 1200 MHz 2: 1600 MHz
Graphics:  Card: NVIDIA GT218M [GeForce G210M] bus-ID: 01:00.0
           Display Server: X.Org 1.15.1 drivers: nvidia (unloaded: fbdev,vesa,nouveau)
           Resolution: 1366x768@60.0hz
           GLX Renderer: GeForce G210M/PCIe/SSE2 GLX Version: 3.3.0 NVIDIA 331.38 Direct Rendering: Yes
Audio:     Card-1 NVIDIA High Definition Audio Controller driver: snd_hda_intel bus-ID: 01:00.1
           Card-2 Intel 82801I (ICH9 Family) HD Audio Controller driver: snd_hda_intel bus-ID: 00:1b.0
           Sound: Advanced Linux Sound Architecture v: k3.13.0-37-generic
Network:   Card-1: Intel PRO/Wireless 5100 AGN [Shiloh] Network Connection
           driver: iwlwifi v: in-tree: bus-ID: 04:00.0
           IF: wlan0 state: up mac: <filter>
           Card-2: Broadcom NetLink BCM5784M Gigabit Ethernet PCIe driver: tg3 v: 3.134 bus-ID: 08:00.0
           IF: eth0 state: down mac: <filter>
Drives:    HDD Total Size: 500.1GB (10.4% used) ID-1: /dev/sda model: WDC_WD5000BEVT size: 500.1GB
Partition: ID-1: / size: 242G used: 41G (18%) fs: ext4 dev: /dev/sda6
           ID-2: swap-1 size: 8.63GB used: 0.00GB (0%) fs: swap dev: /dev/sda7
RAID:      No RAID devices: /proc/mdstat, md_mod kernel module present
Sensors:   System Temperatures: cpu: 52.0C mobo: N/A gpu: 0.0:43C
           Fan Speeds (in rpm): cpu: N/A
Info:      Processes: 158 Uptime: 40 min Memory: 993.8/3948.4MB Init: Upstart runlevel: 2 Gcc sys: 4.8.2
           Client: Shell (bash 4.3.111) inxi: 2.2.16

**Comment by ledufff** [comment]
I'm using Cinnamon 2.4.6 on Fedora 21, and it doesn't happens, tested with MPV and Banshee.
But, I see some memory leak when watching videos.
But I think this is related to: https://github.com/linuxmint/Cinnamon/issues/3690

**Comment by iwis** [comment]
The problem is still present after upgrading to LM 17.2. CPU usage by Cinnamon drops radically when I minimize Kodi (former XBMC) like on afita's computer. It is pity that it has not be fixed yet :(

**Comment by donquixote** [comment]
It just happened to me while playing a youtube video with Chromium.

**Comment by spdionis** [comment]
When I play youtube videos on chrome my cpu usage is around 70% if played in foreground and 30-40% if in background. Normally chrome uses less than 10%.

I have AMD + integrated Intel video card. Is that the cause?

**Comment by tp0** [comment]
Cinnamon 2.6.13
17.2

Using full vaapi GPU acceleration with `mpv`, the video window on secondary display with no other windows below or on top of it:

![22222](https://cloud.githubusercontent.com/assets/5863551/10713586/6ed35328-7ac7-11e5-80ad-cb6e5c20c6fa.png)

Same situation but the window minized:

![111](https://cloud.githubusercontent.com/assets/5863551/10713587/72c46e22-7ac7-11e5-905e-f33aeaf47213.png)

**Comment by tp0** [comment]
This is still present on 2.8.6.

**Comment by Vahan86** [comment]
@iwis, is this still an issue for you with Cinnamon 3.2?

**Comment by iwis** [comment]
@Vahan86: Yes, the problem still exists. Now I am using Linux Mint 18.1 (Serena) 64-bit Cinnamon 3.2
Linux kernel: 4.4.0-53, linux-firmware: 1.157.5.

Do you know how to fix it?

**Comment by leigh123linux** [comment]
It working fine here using F26 and cinnamon-3.2

![screenshot from 2017-02-19 11-19-51](https://cloud.githubusercontent.com/assets/1299302/23101860/911bdf18-f695-11e6-8884-e9e18ff7a8cf.png)

**Comment by calestyo** [comment]
I have this as well on my notebook with cinnamon 3.8.8 and Intel(R) HD Graphics 620 (Kaby Lake GT2).

When I play e.g. a video with VAAPI enabled with mpv, then cinnmon's CPU usage get's pretty high (>30% up to 50%)...

Interestingly, when switching on another desktop (while the video still plays on another), only mpv's CPU usage is high (during playback) while cinnamon stays low.

**Comment by leigh123linux** [comment]
The information provided is incomplete and old.

P.S Don't bother posting screenshots as they are meaningless.
