### ISSUE TITLE
Screen resolution doesn't jump back to normal after removing HDMI cable

### ISSUE THREAD

**Issue by amo13** [linuxmint/cinnamon#3760]
Linux Mint 17.1 32bit Cinnamon

I use a projector via HDMI and set the screen to the resolution of the projector (720p) and choose "morror displays".
So when I want to use the projector I just turn it on, plug the HDMI cable into the computer and the screen automatically sets to the chosen configuration (mirror and 720p). Nice so far. When I am done, I turn off the projector and remore the cable from the computer. Then I expect the screen resolution to jump back to normal (larger than 720p) but it doesn't happen unless I open the "display" settings window. What makes it seem like a bug for me is that opening the "display" settings window is enough to make the screen resolution jump back to normal - before applying any changes in that window.
Bug happened without exception so far.

I had the bug already in Linux Mint 17 32bit Cinnamon (same pc).

**Comment by Vahan86** [comment]
@amo13,  is this still an issue for you with Cinnamon 3.0?

**Comment by amo13** [comment]
Don't have any projector or external monitor right now. Unfortunately, I can't test it.
Maybe somebody with an external monitor can try and confirm if the bug is fixed?

**Comment by pettert85** [comment]
I can confirm this. I'm running Linux Mint 18 Sarah and have the exact same symptoms when connecting computer to my TV using HDMI. The screen also freezes on removal of HDMI and i have to log out or restart.

**Comment by Vahan86** [comment]
@amo13, @pettert85, is this still an issue for you with Cinnamon 4.2?

**Comment by amo13** [comment]
Sorry, can't tell, I switched to manjaro linux years ago

**Comment by icarter09** [comment]
@amo13 no worries and thanks for the update.
