### ISSUE TITLE
Fix Cinnamon Removable Drives eject feature

### ISSUE THREAD

**Issue by freemangilgamesh** [linuxmint/Cinnamon#3761]
The current Removable Drives  does not eject properly drives and instead it mouts them. I suggest you add a separate eject button to it.

<a href="http://imgur.com/AiC7w0P"><img src="http://i.imgur.com/AiC7w0P.png" title="source: imgur.com" /></a>

**Comment by dalcde** [comment]
Clicking the device opens it in nemo. Clicking the eject icons ejects the drive. This is by design.
