### ISSUE TITLE
Missing icon on systray

### ISSUE THREAD

**Issue by gnurichard** [linuxmint/Cinnamon#3762]
Hi I'm user of Fedora 21 with Cinnamon 2.4.5, recently updated. I installed kde-connect indicator(an libappindicator indicator for Kde connect) I had previously tested it in fedora 20 with cinnamon 2.4 and I had absolutely no problem , but now, the Notifier icon are disapeared but the indicator is here, if I click, displays me her menu, but I can not see the icon, I have already tried to resize folder, or use another theme and the problem stills, I have tried the indicator also in xfce panel and the icon appears. regards
![captura de pantalla de 2014-12-15 01 37 36](https://cloud.githubusercontent.com/assets/10189405/5432161/9ced6edc-83fc-11e4-9f9b-8aaf25a2808e.png)

**Comment by Vahan86** [comment]
@gnurichard, is this still an issue for you in Cinnamon 3.0?

**Comment by Vahan86** [comment]
@JosephMcc, can we close this issue?
