### ISSUE TITLE
Cannot use `Super_L+space` as shortcuts.

### ISSUE THREAD

**Issue by weakish** [linuxmint/Cinnamon#3764]
ibus uses `Super_L+space` by default to switch input method.
But this does not work on Cinnamon 2.2.4.

It works out of box with Gnome 3.14.

After setting muffin overlay-key to `Super_R`, `Super_L+space` works for ibus.  

And it is still possible to use `Super_L` for both muffin overlay-key and ibus:

- Hold down `Super_L` for about two seconds.

- Click space slowly

    If not slow, it doesn't work.

    If you hold down space, then ibus keeps changing between input methods so it is hard to predict what method will win when you release)

- Release `Super_L`.

BTW, I use ibus 1.5.9.
Though I guess its version is irreverent here.
For example, `Super_L+space` does not work for Gnome Do too (which uses `Super+space` as default). And if you try to assign `Super_L+space` in Gnome do, Gnome do just recognize it as `space`.

**Comment by mtwebster** [comment]
Should be fixed by https://github.com/linuxmint/muffin/commit/f63fcd0905f50fab14f29e21af42b92688dadfb3
