### ISSUE TITLE
Desktop icons do not always load at login

### ISSUE THREAD

**Issue by Falconus** [linuxmint/Cinnamon#3765]
I am using Linux Mint 17.1 Rebecca with Cinnamon 2.4.5. Sometimes when I log in the desktop icons are not displayed (it's inconsistent; some days it seems like it happens a lot, other days not at all). What I see: my desktop with the menu at the bottom, no icons on the desktop. What I expect to see: the icons on the desktop. It happens on a normal login (I don't do anything special, but my home directory is encrypted, if that matters), and the way I solve the problem is by rebooting the computer or logging out and logging back in.

**Comment by Vahan86** [comment]
@Falconus, is this still an issue in Cinnamon 3.0?

**Comment by Falconus** [comment]
No, it's no longer a problem for me. Thanks for checking back!
