### ISSUE TITLE
[Feature Request][Lockscreen] Permit volume keys to pass through

### ISSUE THREAD

**Issue by gauravjuvekar** [linuxmint/Cinnamon#3766]
Atleast volume mute. Possibly also brightness controls

EDIT: or put volume controls on the lockscreen itself

**Comment by anandrkris** [comment]
https://github.com/linuxmint/Cinnamon/issues/1900
https://github.com/linuxmint/Cinnamon/issues/3487
https://github.com/linuxmint/Cinnamon/issues/3155
https://github.com/linuxmint/Cinnamon/issues/3369

**Comment by gauravjuvekar** [comment]
Closed as dupe of #1900
