### ISSUE TITLE
Some buttons in Firefox are truncated in Cinnamon LM 17(.1)

### ISSUE THREAD

**Issue by MikkCZ** [linuxmint/Cinnamon#3768]
First button I noticed is [The Old reader Notifier] (https://addons.mozilla.org/firefox/addon/the-old-reader-notifier/) add-on. When there are any unread post, it looks like this.
![the old reader notifier button](https://cloud.githubusercontent.com/assets/3941344/5471513/fba34d7e-85f6-11e4-9e04-d1126d9d199d.png)
At first, I thought it's a bug of this add-on, but now I tested it in Windows 7 and Ubuntu and was unable to reproduce it.

After updating to 17.1, this started to happen in [Instantbird] (http://instantbird.com/), which is also a Mozilla based program.
![instantbird icons](https://cloud.githubusercontent.com/assets/3941344/5471512/fb9d9d5c-85f6-11e4-9f8c-1871fc590526.png)
So it seems to me as an issue of Cinnamon, but I could be wrong. If so, please let me know and I will fill it as a Mozilla bug.

**Comment by dalcde** [comment]
Cinnamon does not interfere with how icons are drawn. It is most likely a bug that is only triggered by some theme (which would be Mozilla/gtk's problem, not the theme's problem)
