### ISSUE TITLE
Background Slide Show Feature Enhancement Request

### ISSUE THREAD

**Issue by ven-u** [linuxmint/cinnamon#3769]
Love the slide show feature for the background. There are a couple of features I'd love to have

PREVIOUS button.  We can now show NEXT but not previous. If it's impossible in the Random function, how about allowing it when Random is unchecked?

FILENAME display.  I have approx 1,000 pretty pictures and when one appears, I'd like to know its filename in case I need to crop or resize it, or just look it up again in Wikipedia. 

Thanks.

**Comment by anandrkris** [comment]
@ven-u - I can now see filename and resolution of pictures added under a folder.
Also, there is a slideshow applet available to change it to next background.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
