### ISSUE TITLE
Fuse the pidgin tray with user applet

### ISSUE THREAD

**Issue by gnurichard** [linuxmint/Cinnamon#3770]
Hi eveybodoy one of the few features That I liked at  her time of gnome shell , was the integration of emphaty   With The button in the upper right corner . I think it would be a nice Addition to the user applet,  Besides would not see many icons discordant  in the system tray applet

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html
