### ISSUE TITLE
Keybindings continue to function once removed

### ISSUE THREAD

**Issue by tylery71** [linuxmint/Cinnamon#3772]
Mint 17.1 Cinnamon 2.4.5

With a set keybinding, if you remove it by only hitting backspace (not replacing it with another keybinding) it stays in effect until:
Cinnamon is restarted
another keybinding is set.

Multiple keybindings can be erased and stay in effect until one of the two above actions occur.

**Comment by Vahan86** [comment]
Tested in Cinnamon 3.0.7. It's working fine for me.

@tylery71, is this still an issue for you in Cinnamon 3.0?

**Comment by Vahan86** [comment]
@JosephMcc, can we close this issue?
