### ISSUE TITLE
Expo and scale - Arrage windows nearest to their onscreen location

### ISSUE THREAD

**Issue by gauravjuvekar** [linuxmint/Cinnamon#3775]
Open four windows and tile them at corners.
Go to scale or expo

Observed: The windows are randomly arranged by scale/expo
Expected: The windows should be arranged with least displacement from their onscreen position.

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html
