### ISSUE TITLE
AltGr not working on login

### ISSUE THREAD

**Issue by petri00** [linuxmint/Cinnamon#3777]
While login to Cinnamon the AltGR key doesn't result the special characters like ] with keyboard Logitech MK710. Other keyboards seems to work. I can use another keyboard to press the AltGr-key and in MK710 I press the 9-key and it results the ]-sign but not on MK710 alone. After the first ]-sign the login box registers ]-signs (and all the other special signs with AltGR) from MK710. This bug exists on Mint 16 and 17.

**Comment by dalcde** [comment]
Probably an issue with the keyboard driver instead of Cinnamon, unless it works in other DEs, which I doubt
