### ISSUE TITLE
Split button in Nemo

### ISSUE THREAD

**Issue by michelsaey** [linuxmint/Cinnamon#3778]
I've come from the KDE version in the past and now switched to Cinnamon 2.4 and I love it very much including the file manager 'Nemo' that responds very fast. There is one thing in the file manager 'Nemo' missing: a split button. In KDE's Dolphin, there is a split button and that comes very handy to moves files from one directory in the other.

**Comment by JosephMcc** [comment]
This is not a Cinnamon issue. It belongs here: https://github.com/linuxmint/nemo
