### ISSUE TITLE
show auto-hide panel for full-screen windows

### ISSUE THREAD

**Issue by ibukanov** [linuxmint/Cinnamon#3783]
Currently there is no way to access the Cinnamon panel from a full-screen window. It would be nice if there would be option to show auto-hide panel on top of full-screen windows in the same way as it is shown on top of maximized applications. That is, just by moving the mouse off-screen the panel coud always be activated no matter if a window is full-screen or not.

**Comment by dalcde** [comment]
Showing panel when the mouse reaches the bottom of the screen isn't a good solution, since in, say, Youtube, you access the video controls by reaching the bottom of the screen as well. I think a good solution would be to show it when you press the Super key, hence #575
