### ISSUE TITLE
SFTP file transfers in Nemo give no progress information

### ISSUE THREAD

**Issue by the-allanc** [linuxmint/Cinnamon#3784]
Not sure if this is a Nemo issue or a Linux Mint one - but on Linux Mint 17.1, if I move some files over SFTP with Nemo, the only progress it will report is a message such as "Preparing to Move..." and indicate how many files it has left.

Normal file transfers give the standard progress bar and progress information (size of data moved so far, estimated time to completion etc.)

It also used to work in the past on older Linux Mint releases for SFTP transfers.

**Comment by bminer** [comment]
+1 - Confirmed on my system running Linux Mint 17 Qiana

**Comment by leigh123linux** [comment]
Must be a Mint issue as it works fine here.

![screenshot-area-2015-06-03-064015](https://cloud.githubusercontent.com/assets/1299302/7953369/c7c5f8f0-09bb-11e5-9ea6-351e50d24943.png)

**Comment by bminer** [comment]
I am running nemo 2.2.4+qiana, Cinnamon 2.2.16.  I have read that older versions of nemo work fine...

**Comment by leigh123linux** [comment]
@bminer 

I doubt 2.2 will get fixed as it's probably EOL.

Using nemo-2.6.5 here and it's fine.

**Comment by the-allanc** [comment]
Did a new install of 17.1, allowed updates to install, seems to still be broken. Perhaps 17.2 will be in a better state?

**Comment by Vahan86** [comment]
@the-allanc, is this still an issue for you in Cinnamon 3?

**Comment by Vahan86** [comment]
@JosephMcc, can we close this issue?
