### ISSUE TITLE
Lower panel not behaving correctly after HiDPI change

### ISSUE THREAD

**Issue by jmgomezpoveda** [linuxmint/Cinnamon#3785]
In my screen with resolution of 3200x1800, Cinnamon 2.4.5 Nightly (but also happened with earlier versions) automatically detects the pixel density and doubles the size of everything. If I temporarily switch to 1600x900 (for gaming or connecting to a remote desktop), it automaticlly changes the detected pixel density, so it still behaves greatly.

However, after setting a lower resolution, once I am back to 3200x1800, the lower panel (the one with the applications menu, shortcuts, running applications, system tray, and clock) only detect clicks and mouse hovers on the upper half of the panel. The panel is displayed correctly, but the lower half of it won't detect any mouse action.

This behaviour remains until I restart the computer, or as a workaround, I right click on the panel, enter the panel settings, select use customised panel size, and deselect it again. Then everything works perfectly again.

**Comment by anandrkris** [comment]
Maybe we just need to add a note in Display Settings sayings 'Needs restart of Cinnamon'.

**Comment by jmgomezpoveda** [comment]
Or better yet, if deemed necessary, could the restart be automatically triggered after a resolution change?

**Comment by anandrkris** [comment]
@jmgomezpoveda Hmm...As per existing Panel settings, auto restart doesn't seem to be the practice perhaps for valid reasons...I know, its just a **Cinnamon** restart..
![screenshot from 2015-01-12 18 52 27](https://cloud.githubusercontent.com/assets/4663298/5703418/53ca31d0-9a8c-11e4-95e8-ada55fe2cb68.png)

**Comment by dalcde** [comment]
Does this still happen on Cinnamon git? The panel code has be rewritten considerably.

**Comment by jmgomezpoveda** [comment]
@dalcde: I will update to the git version and report back.

**Comment by jmgomezpoveda** [comment]
This seems to be fixed in Cinnamon git (2.5.0-20150511040).

**Comment by jmgomezpoveda** [comment]
Kudos to the Cinnamon devs.
