### ISSUE TITLE
When a selection is made the beggining is not taken into account.

### ISSUE THREAD

**Issue by Paviluf** [linuxmint/Cinnamon#3786]
Hi,

I don't know if it's a bug but when I want to select some text or move something quickly, very often the beggining of the selection or displacement is not taken into account.

I found that I have to set, in system settings / mouse, the last 2 settings to 1 instead of 8.

**Comment by mtwebster** [comment]
Can't reproduce this - 

In gnome-terminal, the drag threshold delays selection of text, but it still eventually selects the correct area.

In gedit and others, the threshold is entirely ignored, and selection takes place immediately.

Any other programs I can try?

**Comment by Paviluf** [comment]
For me it happen everywhere, in gedit, terminal, libreoffice, even on the desktop.
You have to move relatively quickly to make it happen.

**Comment by JosephMcc** [comment]
I can't reproduce this either. Not in terminal or gedit.

**Comment by Paviluf** [comment]
I don't know what can cause this but on windows, ubuntu and kubuntu it doen't happen.

**Comment by Paviluf** [comment]
With Cinnamon 2.6.2 in system settings / mouse, there is now only one settings that I can set to 1 instead of 8 but it's doesn't work anymore.

**Comment by JosephMcc** [comment]
Which setting is missing in 2.6?

**Comment by mtwebster** [comment]
Do you use ibus or any other input method helper? (fcitx, etc..)

**Comment by Paviluf** [comment]
I don't use ibus or other input method.

The missing setting is: GTK drag threshold

**Comment by Paviluf** [comment]
Ok I found that bug that is exactly the same problem:
https://github.com/linuxmint/Cinnamon/issues/3725

It have a workaround (desactivating the Middle Click emulation) but a proper fix will be much appreciated
