### ISSUE TITLE
can't unlock desktop using password dialog box

### ISSUE THREAD

**Issue by SaintDanbert** [linuxmint/Cinnamon#3792]
SYMPTOMS
When the desktop locks -- keystroke, menu, or timeout -- entering a password results in "Checking ..." then a return to the unlock dialog box without opening the desktop.

I can select [Switch User] button and login as the current active user, using the same password as I tried with unlock, and everything opens correctly.

I created a new, previously undefined user login. This user has the same problem with desktop unlock as the original user.

I have no idea if a lock screen issue is specific to the Cinnamon environment or if it is part of other subsystems.

I don't consider this a security matter other than it leaves a user session active while preventing that user access to the session.

CONFIGURATION
Previous system was Linux Mint-15 Cinnamon: single drive, multiple partitions.
Mint 17.1 Cinnamon desktop fresh install: Formatted /boot, swap, and / (root). Preserved /home

**Comment by dalcde** [comment]
Is it possible that this is because the lock screen uses a different keyboard layout? (e.g. Dvorak)

**Comment by SaintDanbert** [comment]
I really REALLY hate it when this sort of this happens...

The symptoms in my original report have simply GONE AWAY.

Yes, I have installed updates using mint-update.
Yes, I have used the workstation for daily operations.
No, I have no idea what has changed (we all know that something changed) to cause the original symptoms to GO AWAY.

~~~ 0;-/ Dan
