### ISSUE TITLE
[Brightness Applet] Scrolling increments not consistent

### ISSUE THREAD

**Issue by gauravjuvekar** [linuxmint/Cinnamon#3794]
Scrolling down from 100% on applet icon
`100% <- Normal 5% steps -> 45% <- WTH -> 41% <- Normal 5% steps -> 1% -> 0%`

Scrolling up from 0% on applet icon
`0% <- WTH -> 4% <- Normal 5% steps -> 54% <- WTH -> 58% <- Normal 5% steps -> 98% -> 100% `

Scrolling down from 100% on slider in applet menu.
`100% <- Normal 5% steps -> 95% <- WTH -> 89% <- Normal 5% steps -> 4% -> 0%`

Scrolling up from 0% on slider in applet menu.
`0% <- Normal 5% steps -> 40% <- WTH -> 44% <- Normal 5% steps -> 54% <- WTH -> 60% <- Normal 5% steps -> 100%`

---------

````
$ cinnamon --version
Cinnamon 2.4.5
````
on rebecca

Probably similar to #2618

**Comment by gauravjuvekar** [comment]
@mtwebster Reopen, persists in Cinnamon 2.4.8 from romeo (rebecca)

**Comment by pixunil** [comment]
As far as I know, this isn't in `2.4`, but in `2.5` (you can try [nightly](https://github.com/linuxmint/Cinnamon/wiki/Trying-out-the-latest-Cinnamon-without-building-it.))
