### ISSUE TITLE
Cinnamon crashes on desktop load

### ISSUE THREAD

**Issue by EvilSupahFly** [linuxmint/Cinnamon#3797]
Running Cinnamon 2.4.5 over a clean Ubuntu 14.10 x64 install on kernel 3.18.1-031801-generic. Cinnamon crashes when the user logs in as the desktop loads. Attempting to run `cinnamon --replace` from the terminal yields the following error:
```
(cinnamon:23306): Cjs-WARNING **: JS ERROR: GLib.Error g-invoke-error-quark: Could not locate gnome_desktop_get_media_key_string: 'gnome_desktop_get_media_key_string': /usr/lib/x86_64-linux-gnu/libcinnamon-desktop.so.4: undefined symbol: gnome_desktop_get_media_key_string
Window manager warning: Log level 32: Execution of main.js threw exception: JS_EvaluateScript() failed
```
Attempts to remove then reinstall cinnamon have not yielded any positive results.

**Comment by daviday** [comment]
What machine is the install on?

**Comment by EvilSupahFly** [comment]
Does this help?
```
root@black-beast:/etc/apt# uname -a
Linux black-beast 3.18.1-031801-generic #201412170637 SMP Wed Dec 17 11:38:50 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```
It's an Intel Core2 Quadcore CPU (Q6600)  @ 2.40GHz, an nVidia GT430 video card with 1 GB vram, and 6 GB of Kingston RAM.

**Comment by daviday** [comment]
A little. Seems as if you jumped the gun. Try to downgrade the kernel to an earlier build. 

Www.kernel.prg

**Comment by EvilSupahFly** [comment]
Well, I have tried kernels 3.16.0, 3.16.6, 3.16.7, 3.17.1, 3.17.7, and
3.18.1 and Cinnamon fails every time. I don't know what else to do except
purge Cinnamon completely, and revert to base Ubuntu. Or switch to Mint.

**Comment by daviday** [comment]
I'm a little confused. Are you on a desktop or a tablet?

**Comment by EvilSupahFly** [comment]
Desktop

**Comment by daviday** [comment]
A lot of people seem to be having similar issues in the crossystem command translations unfortunately.

**Comment by collinss** [comment]
@EvilSupahFly I'm no expert, but I wonder if it has anything to do with your GNOME version. The current version of Cinnamon is optimized for Mint 17.1 which uses the Ubuntu 14.04LTS codebase - which has the GNOME 3.10 libraries - whereas Ubuntu 14.10 uses 3.12. I know in the past there have been numerous problems with using different versions of the GNOME libraries, as each version seems to break something else.

**Comment by EvilSupahFly** [comment]
You raise an excellent point. Since I have to reinstall from scratch anyway
because of other issues relating to 14.10 and driver problems, I will
simply install 14.04 instead. The changes between .04 and .10 are minor at
best anyway, and if it solves this Cinnamon problem, so much more the
reason to revert.

Thanks for looking into this!

**Comment by EvilSupahFly** [comment]
On a clean install of 14.04.1, I am able to run Cinnamon without issue, so it seems that the issue was the Gnome 3.12 libs, which caused other issues as well. Considering this resolved. :)

**Comment by vranki** [comment]
Does anyone know a workaround for this? 14.10 is the latest Ubuntu version so many would like to run Cinnamon on it. 15.04 will be out soon and it'll also have newer Gnome libs so the problem isn't going away.

**Comment by mtwebster** [comment]
Can any of you post the contents of ~/.xsession-errors after a crash?  Switch to a tty when it happens and copy the file to a new name (or else it will get overwritten).

Also, I've run into what could be a similar problem on debian - check the results of:

`dpkg --list | grep cinnamon-desktop`
and
`dpkg --list | grep cjs`

You should *only* have 2.4 versions there - keep an eye out for a rogue 2.2 version of something, and run:

`dpkg --purge --force-all *name*`

**Comment by vranki** [comment]
I had libcjs0 and libcinnamon-desktop4 version 2.2.* installed. After removing those Cinnamon started. 
Thanks! 

Perhaps the current packages should conflict to those, to make sure no one gets the same issue?

**Comment by mtwebster** [comment]
We've identified a couple of issues with our packaging, that's causing this - hopefully we'll be able to address soon.

@lestcape not sure if you can do anything with your stable ppa in the meantime to prevent this for Ubuntu users?  It seems that upstream debian 2.2 packages are interfering.

**Comment by GLolol** [comment]
I added a conflict on `libcinnamon-desktop4 (<< 2.4~)` to resolve this after I got the exact same problem: GLolol/cinnamon-desktop@d8f987875, though it's probably better to package the library as `libcinnamon-desktop4` in source in the long run. linuxmint/cinnamon-desktop#12 suggests just that.

`libcjs0` got automatically removed in upgrading to 2.4, IIRC. The Breaks/Conflicts are set up correctly for that.

**Comment by lestcape** [comment]
@mtwebster thats is not possible, I'm not provide Cinnamon on ubuntu 14.10 or higher, exactly to prevent conflict with the debian maintainer of cinnamon and also to avoid conflict on the libraries version... The only reason of the repo is provide cinnamon where is not officially supported (on ubuntu 14.04). So they sure use the tsaveko repo...

**Comment by EvilSupahFly** [comment]
If this helps, I have a couple of logs you can browse (.xsession-errors):

http://pastebin.com/WugNLXZA
http://pastebin.com/CBisj6V7

**Comment by mtwebster** [comment]
@EvilSupahFly please try what I suggested here: https://github.com/linuxmint/Cinnamon/issues/3797#issuecomment-76428838

and purge anything that is not 2.4.x, should fix your issue.

**Comment by EvilSupahFly** [comment]
I did, and I have no conflicting libraries, but I have no menu bar. Nemo loads, and I have desktop icons, and can alt+tab between open applications but there's no menu and I can't run apps with F2.

**Comment by EvilSupahFly** [comment]
OK, well, after a reboot, and a downgrade of my nVidia drivers, it's working on my x64 desktop. However, after a recent Cinnamon upgrade on my x86 laptop, it's still crashing. Laptop .xsession-errors is as follows:

http://pastebin.com/2un8W4Nc

**Comment by EvilSupahFly** [comment]
Downgrading my nVidia video driver and rebooting fixed it.

**Comment by EvilSupahFly** [comment]
Why doesn't the process of upgrading to 2.4.x remove the 2.2.x components? I just upgraded Cinnamon on my x86 laptop and had to perform the steps in #3797 because the initial upgrade broke Cinnamon. Shouldn't Synaptic/dpkg/APT/etc catch that?
