### ISSUE TITLE
System Info applet crashes with mounted Samba Shares

### ISSUE THREAD

**Issue by Apostle7** [linuxmint/Cinnamon#3801]
Linux Mint 17.1 Cinnamon 64-bit

System Info applet crashed when launched from cinnamon-settings.

I have extensive programming experience. However, I have never written in Python
or submitted a code fix. I hope submitting it as a bug is the proper procedure. 
I've already tracked the problem and corrected it.

The function:

getDiskSize()

In file:

/usr/lib/cinnamon-settings/modules/cs_info.py

This function gets the output from the 'df' command and adds up the total amount
of disk space for the machine. The problem is that I mount Samba shares at
boot and this command ends up returning a string that is being converted to a
float: error!

If I use: "df -l" in terminal, it only returns local info. However, if I pass
that argument in python, it does not like it. So here is my amateur fix...

Original code:

def getDiskSize():
    disksize = 0
    for line in getProcessOut("df"):
        if line.startswith("/"):
            disksize += float(line.split()[1])
            
    return disksize

My code:

def getDiskSize():
    disksize = 0
    for line in getProcessOut("df"):
        if line.startswith("//"):
            pass
        elif line.startswith("/"):
            disksize += float(line.split()[1])
            
    return disksize

Python looks very clean, is very picky and I think I like it. However, I felt it
better to let a pro take a look...

**Comment by GLolol** [comment]
Try this patch:

```
diff --git a/files/usr/lib/cinnamon-settings/modules/cs_info.py b/files/usr/lib/cinnamon-settings/modules/cs_info.py
index d50be27..e5aba69 100644
--- a/files/usr/lib/cinnamon-settings/modules/cs_info.py
+++ b/files/usr/lib/cinnamon-settings/modules/cs_info.py
@@ -50,7 +50,7 @@ def getGraphicsInfos():
 
 def getDiskSize():
     disksize = 0
-    for line in getProcessOut("df"):
+    for line in getProcessOut(("df", "-l")):
         if line.startswith("/"):
             disksize += float(line.split()[1])
```

It's probably better to grab a copy of the source and build it yourself, as editing the files of an installed copy of Cinnamon might cause upgrade issues later on if you choose to do so.
