### ISSUE TITLE
Failure to put computer into sleep mode, missing widgets in dialog box

### ISSUE THREAD

**Issue by burann** [linuxmint/Cinnamon#3802]
Linux Mint 17.1 - 64 bit - All updates applied
Cinnamon - 2.4.5
Linux Kernel - 3.13.0-24-generic
Desktop computer
Intel i7 - 16 GB memory - Radeon 280x with drivers

After a reboot I can successfully put the computer in sleep mode twice, the third time when clicking the "quit" button in Cinnamon, the dialog fails to show directly, it takes around aprox 60 seconds, and when it shows, the "sleep" option does not display correctly.

At this point, doing a sudo shutdown will not succeed, pressing esc will show that linux mint have printed out information about services terminating, but never complete the shutdown or reboot.

I find the following in the logs:

Jan 4 21:20:32 XXXXX cinnamon-session[2450]: Gtk-CRITICAL: gtk_progress_bar_set_fraction: assertion 'GTK_IS_PROGRESS_BAR (pbar)' failed
Jan 4 21:20:32 XXXXX cinnamon-session[2450]: Gtk-CRITICAL: gtk_progress_bar_set_show_text: assertion 'GTK_IS_PROGRESS_BAR (pbar)' failed
Jan 4 21:20:32 XXXXX cinnamon-session[2450]: Gtk-CRITICAL: gtk_progress_bar_set_text: assertion 'GTK_IS_PROGRESS_BAR (pbar)' failed

**Comment by Vahan86** [comment]
@burann, is this still an issue for you with Cinnamon 3.0?
