### ISSUE TITLE
  Double click on a date on the Calender to create an event/reminder	

### ISSUE THREAD

**Issue by tranjeeshan** [linuxmint/Cinnamon#3805]
Calender applet is a basic applet. A great functionality can be added in it. That is, when any date on the Calender is clicked or double-clicked, it would prompt for an event creation or reminder.

**Comment by sprintcowboy** [comment]
I second this.
It would be nice to have a reminder popup of a event using the calender applet.

**Comment by dalcde** [comment]
#2720
