### ISSUE TITLE
  Middle-Mouse-Click in Sound applet to toggle mute state 

### ISSUE THREAD

**Issue by tranjeeshan** [linuxmint/Cinnamon#3806]
Clicking on the sound/volume applet with middle mouse click would mute the sound and again toggles it in other DEs. This feature would be great to have on Cinnamon.

**Comment by mtwebster** [comment]
This was a 2.4 regression that has actually already been fixed (just not re-released yet): https://github.com/linuxmint/Cinnamon/commit/88ded424de0f212741378198990d9243aa3ee2f0

**Comment by tranjeeshan** [comment]
Thanks :)
