### ISSUE TITLE
Cinnamon bluetooth keyboard "keyboard settings" crashes cinnamon-settings.py

### ISSUE THREAD

**Issue by bogger33** [linuxmint/Cinnamon#3807]
I'm using LMDE Cinnamon 64-Bit

Cinnamon version 2.0.14
Linux Kernel 3.11-2-amd64

Steps to reproduce:
$ cinnamon-settings bluetooth
(gui opens)
select already paired keyboard in the devices list
In the bottom right corner, press "keyboard settings"

the following crash happens:
    ** (cinnamon-settings.py:30706): CRITICAL **: cc_shell_set_active_panel_from_id: assertion `CC_IS_SHELL (shell)' failed
    Segmentation fault

I'm using an apple A1314 bluetooth keyboard, not sure if that matters. it's a japanese layout keyboard. Here's the whole console output, not just the crash part:

[139]user@device ~/Desktop $ cinnamon-settings bluetooth
Unknown module bluetooth, using cinnamon-control-center
/usr/lib/cinnamon-settings/modules/cs_user.py:112: Warning: g_object_unref: assertion `G_IS_OBJECT (object)' failed
  file_icon = Gio.FileIcon().new(file)

(cinnamon-settings.py:30706): Gtk-CRITICAL **: gtk_list_store_get_path: assertion `iter->stamp == priv->stamp' failed

(cinnamon-settings.py:30706): Gtk-CRITICAL **: gtk_list_store_get_path: assertion `iter->stamp == priv->stamp' failed

(cinnamon-settings.py:30706): Gtk-CRITICAL **: gtk_list_store_get_path: assertion `iter->stamp == priv->stamp' failed
__init__ took 654.655 ms
** Message: has_config_widget 28:37:37:29:F3:B0 HumanInterfaceDeviceService

** (cinnamon-settings.py:30706): CRITICAL **: cc_shell_set_active_panel_from_id: assertion `CC_IS_SHELL (shell)' failed
Segmentation fault

If you have any questions, let me know.

**Comment by Vahan86** [comment]
@bogger33, is this still an issue in Cinnamon 3.0?

**Comment by JosephMcc** [comment]
It's Cinnamon 2.0. I don't think this is even relevant anymore as bluetooth is now handled via blueberry.
