### ISSUE TITLE
show extended description of extension inside cinnamon settings

### ISSUE THREAD

**Issue by lestcape** [linuxmint/Cinnamon#3809]
On cinnamon settings, would be imported html2txt packages, to show the spices extended description directly on the online tab. This improvement the user possibility to know the usages of an online extension, without need to visit the online spices page.

https://github.com/aaronsw/html2text
https://pypi.python.org/pypi/html2text/2014.12.29

The idea is do this without webkit (is currently not active anyway).

**Comment by JosephMcc** [comment]
Not sure about this one. With the large number of applets that can be showing in that tab, I wouldn't want to have to scroll for an hour to get to the ones at the bottom. I'm not really sure what the benefit would be versus just using the "More info" button that is already there.

**Comment by lestcape** [comment]
@JosephMcc see the code. What happened, is that a new dialog will be open to show the information(comments say ala Mint...) and also could be a panel that show only the information for the selected extension, like occurs on the cinnamon menu with the description of the application. Is, not necessary the scroll.
In all cases what currently happen it's that we need to download this information from the spices server on all updates and we not use this information, currently. I know that it's a little hardly use the webkit, but an easy conversion... Why not?

**Comment by lestcape** [comment]
Here is just an idea that i implemented (you can move the pane to the position that you want):
![captura de pantalla de 2015-01-27 18 38 24](https://cloud.githubusercontent.com/assets/1389572/5930326/b9b85f4e-a653-11e4-9f3a-9151f85a3687.png)

Here the cinnamon current code (is hidden on the previously return):
https://github.com/linuxmint/Cinnamon/blob/master/files/usr/lib/cinnamon-settings/bin/Spices.py#L170-193
