### ISSUE TITLE
[wiki] Add instructions to return to stable release

### ISSUE THREAD

**Issue by kehugter** [linuxmint/Cinnamon#3810]
It would be useful to have the procedure to return to the stable release documented in the "[Trying out the latest Cinnamon without building it.](https://github.com/linuxmint/Cinnamon/wiki/Trying-out-the-latest-Cinnamon-without-building-it.)" wiki page.

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html
