### ISSUE TITLE
Skype new message notification in Window list applet

### ISSUE THREAD

**Issue by nbasov** [linuxmint/Cinnamon#3812]
Hello developers!

Is it possible to implement into Window applet following fix for Skype new message notification?
https://superuser.com/questions/726444/highlight-skype-window-when-i-receive-a-message

Missing this solution is very inconvenient to chat in Skype.

**Comment by anandrkris** [comment]
I understand this is for Window list. Just checking, it's been sometime since I used Skype, do notifications appear on System tray for incoming messages?

**Comment by nbasov** [comment]
No, notifications still doesn't appear on System tray for incoming messages

**Comment by dalcde** [comment]
Should be fixed by new window-list applet. Please confirm

**Comment by nbasov** [comment]
When new skype chat appears - system creates new window list button that is flashing. It flashes about 4 times and then stops even if i don't open this chat window. If there is new message in this chat - window list button never flash.

Is this right behavior? I assume that window list chat button should always flash until it opened.
