### ISSUE TITLE
Cinnamon calendar start day & date options

### ISSUE THREAD

**Issue by bearfreeman** [linuxmint/Cinnamon#3815]
Hi,

I couldn't find a way to change the Cinnamon calendar, so the start day is Monday, or swop the date settings so that ie Friday Jan 9 becomes Friday 9 January. Hope these can be incorporated.

Fanx,

Bear.

**Comment by anandrkris** [comment]
https://github.com/linuxmint/Cinnamon/pull/3665 > There seems to be a pull request for this.

https://github.com/linuxmint/Cinnamon/issues/2490> looks like this is removed in Calendar applet and is available as part of Cinnamon Date settings.
https://github.com/linuxmint/Cinnamon/pull/2501

**Comment by bearfreeman** [comment]
Ok, sussed it, I configured the date to the international setting ie Thursday 22 January 2015, and now Monday is the start of the week, and the weekend is at the end of the week. Sorted :o) [This is in Mint Cinnamon 16]

**Comment by bearfreeman** [comment]
Just installed Linux Mint 17.1, got the date in international mode, and the weekend is at the end of the week, so that's fine, but I note that at the top of the calender panel, the month is still in front of the day, ie Tuesday January 27. Also, the weather applet in 5 day forecast mode is too large to fit my 15" monitor, it was fine in Mint 16.

**Comment by Vahan86** [comment]
@bearfreeman,

1. It's now possible to change the first day of week: Cinnamon Settings->Date&Time->Format->First day of week.

2. You can change the date format as well: right click on Calendar applet->Configure...->Use a custom date format.

@JosephMcc, can we close this issue?
