### ISSUE TITLE
[Sound applet] Removing a player does not remove it from the list

### ISSUE THREAD

**Issue by gauravjuvekar** [linuxmint/Cinnamon#3817]
1. `sudo apt-get install rhythmbox`
2. Open sound-applet > Launch player
  - Rhythmbox is shown
3. `sudo apt-get remove rhythmbox`
4. Open sound-applet > Launch player
  - **Rhythmbox is still shown**
  - Clicking it gives a failed to launch notification

**Comment by pixunil** [comment]
https://github.com/pixunil/Cinnamon/commit/e78fe896ce41d115cbefe3413147924514ebb6fb

**Comment by mtwebster** [comment]
fixed as of 05f65cf and 6b7d342
