### ISSUE TITLE
Add titlebar colour changes depending on the GTK 3 theme's CSS

### ISSUE THREAD

**Issue by sergioad** [linuxmint/Cinnamon#3818]
Hello Friends as you know the mos recent GNOME 3 apps can use dark themes but unfortunelly the Cinnamon's titlebars does not changes with the GTK theme so the window looks dark but the titlebar looks light, other example is with the Paper GTK theme what uses material design but it does not looks consistent on Cinnamon because the same reazon, can you add this feature soon?

**Comment by JosephMcc** [comment]
This is already fixed in git: https://github.com/linuxmint/muffin/commit/fb27514d6d2fce28ce3f8524a4f1154f981f7882

**Comment by sergioad** [comment]
thank you so much when will come the update for Arch and Mint?

**Comment by dalcde** [comment]
When the next version of Cinnamon is released (or if you use the nightly ppa/AUR git version)
