### ISSUE TITLE
A unique id for themes could prevent some current problems.

### ISSUE THREAD

**Issue by lestcape** [linuxmint/Cinnamon#3820]
The current state of theme id it's certainly a known problem. I only recommend create a unique id, that i propose could be the lower case of the theme name.

The problem is that currently the Tron theme appear on spices as Tron, but it's installed as TRON, so this is a little problematic and is allowed. This mean that if we want to continue using the theme name as an id, we need to be sure that this could not be converted on a problem. It's more difficult resolve this problem on cjs, so please create a restriction on the spices website and on cinnamon settings to not allow theme names with upper and lower case. This problem now can be resolved.

Take care with the spice data, they need to be encode to utf-8 and then we can apply lower case.

**Comment by lestcape** [comment]
Here is the problem:
https://github.com/linuxmint/Cinnamon/blob/master/files/usr/lib/cinnamon-settings/bin/Spices.py#L463-465

If we want to have the same name we need to change this code to not override the title:
```
if not os.path.exists(temp_path):
    title_folder = os.listdir(dirname)[0] # We assume only a single folder, the theme name
    temp_path = os.path.join(dirname, title_folder)
```

This will be more easy to understand, on this way and we can have a way to match the local themes with the spices themes.

Thanks for pay attention to this.

**Comment by lestcape** [comment]
This affected the possibility to know if there are an update for a theme, so i change the title of the issue.

**Comment by lestcape** [comment]
As remember, in the Cinnamon settings is not shown the possibility to update a theme when is possible, if the author provide a theme with a different folder name. Why take efforts to validate themes, when user don't known that some themes have an update? Please fix this problem, is just one wrong line.

**Comment by dalcde** [comment]
I don't see where the issue is. The name of the theme specified on Cinnamon Spices need not be the same as the name of the theme itself, as it is entirely possible (even though not recommended) to ship a spice containing multiple themes.

Cinnamon assigns each theme a uuid and is stored inside the metadata.json inside the theme folder. So there is no problem of mis-recognizing a theme.

**Comment by lestcape** [comment]
Sorry, but i can reproduce the issue. If you create a theme with a name and then create a folder where the theme will be put with a different name, then if you install the theme and then the theme will be updated, cinnamon settings not report any update of the theme to you...

The issue is here:
https://github.com/linuxmint/Cinnamon/blob/master/files/usr/lib/cinnamon-settings/bin/Spices.py#L534-L536

This line is not true:
https://github.com/linuxmint/Cinnamon/blob/master/files/usr/lib/cinnamon-settings/bin/Spices.py#L535

All themes have a name, and cinnamon some times use the real name and some times the folder name, so is impossible on that way math as we don't have a way to know the folder name online...

Sorry for my first link, is currently broken

**Comment by lestcape** [comment]
The id of themes is not the uuid, and i have some uuid for themes that not match with the online uuid. I don't know why, but this need to be the reason of use the theme name(or folder name) as a id of the theme. If you found where the uuid of the theme are used as an identifier for themes, please close this issue.

**Comment by dalcde** [comment]
I don't reproduce the issue. CInnamon does not care about what the theme name is. It only recognizes uuids. I created a test theme with different folder name and name-on-spices. Every time I update it on Cinnamon Spices, cinnamon-settings tells me there is an update.

For the sake of clarification, the uuid of a theme is a number assigned, not what the theme designer calls the theme. It can be found in metadata.json. It is not normally visible to the user, but can be seen here: http://cinnamon-spices.linuxmint.com/json/themes.json as well as in metadata.json.

**Comment by lestcape** [comment]
I have not internet connection to find and reference all things. I know what and where is the uuid of themes, and the cinnamon-settings don't use it (on themes) to identify a particular one, he use the folder name and the theme name. Online, we can not find a folder name, so, i really don't know how you will match what with what, if not always is used the same thing.

See what is loading on name for online data on 5 column:
https://github.com/linuxmint/Cinnamon/blob/master/files/usr/lib/cinnamon-settings/bin/ExtensionCore.py#L906

This is how you know if some theme ar loaded:
https://github.com/linuxmint/Cinnamon/blob/master/files/usr/lib/cinnamon-settings/bin/ExtensionCore.py#L1154

The column that is in used:
https://github.com/linuxmint/Cinnamon/blob/master/files/usr/lib/cinnamon-settings/bin/ExtensionCore.py#L1158

The columns explantions is here:
https://github.com/linuxmint/Cinnamon/blob/master/files/usr/lib/cinnamon-settings/bin/ExtensionCore.py#L298

This will fail:
https://github.com/linuxmint/Cinnamon/blob/master/files/usr/lib/cinnamon-settings/bin/ExtensionCore.py#L1163

So theme will be loaded as other name:
https://github.com/linuxmint/Cinnamon/blob/master/files/usr/lib/cinnamon-settings/bin/ExtensionCore.py#L1185

**Comment by lestcape** [comment]
Maybe now, you are rigth and the uuid for themes on spice not change, but as i have reference of some changes, the theme uuid is not a solution to me, or this was fixed after i install some themes... The folder name could change as a desition of the author of themes, so this is why i report this. I really have not internet access to test what happend again... I can not do more than report  what i see. I will close that, as aparently this is fixed some how...

Any way thanks for take a look.
