### ISSUE TITLE
Graphics Glitch/Tearing when Using Cinnamon

### ISSUE THREAD

**Issue by zorbama** [linuxmint/Cinnamon#3822]
I am using Linux Mint 17.1, 32-bit with Cinnamon. When using some applications, I get heavy graphic glitches/tearing (I'm not sure how to define it), as shown in this video: http://youtu.be/hZDebOwwAa0

It also happens when using MyPaint: the line that is painted is cut in the very end, giving it a square edge (the painting itself comes out fine in the end).

I have an NVIDIA GeForce 9500 GT graphics card, with nvidia-331 (the recommended driver) installed through the driver manager.

**Comment by theSeppi** [comment]
Which graphics card and driver do you use?

**Comment by zorbama** [comment]
Ah, sorry for leaving that out. I have added the information to the original post.

**Comment by zorbama** [comment]
Updated Nvidia driver to 340.65. Same issues.

**Comment by cptX** [comment]
Similar or even worse experience with Linux Mint 17.1 64bit with ATI X1950 pro Graphics Card. In my  previous Ubuntu 10.10 with the opensource drivers I never had a problem.
Now parts of the screen just become teared, sometimes with black content. Sometimes some fonts also become corrupted!!

**Comment by Vahan86** [comment]
@zorbama, is this still an issue for you in Cinnamon 3 (Mint 18)?

**Comment by zorbama** [comment]
Not that I've noticed. I've also changed my graphics card since this issue was opened.
