### ISSUE TITLE
Size of the Mint Search Enhancer 1.0

### ISSUE THREAD

**Issue by YoungFaithful** [linuxmint/Cinnamon#3823]
System)
Cinnamon 17 "Qina" 64-bit

How to create the problem)
open pons.eu, click in the search field (firefox) => many search engines to add, go to another tab, click in the search field again => many empty lines

How it should be)
Acutalising the size of the Search enhancer

In addition)
It would be great if one would be able to add specific symbols to the personal search engines (else it is not possible to decide on the first view which one is german-spanisch and which on is german-english)

**Comment by dalcde** [comment]
This is an upstream issue with firefox, not cinnamon or even mint. File it against firefox instead.
