### ISSUE TITLE
When snapping window to edge window freezes and outline stays

### ISSUE THREAD

**Issue by Swistaku** [linuxmint/Cinnamon#3825]
Hello,

I've noticed one more bug with cinnamon. When I'm snapping window to bottom right edge and I click right mouse button (when cursor is on the panel) window freezes and the outline stays, also after few seconds popup notice appears. Only cinnamon restart helps

Here's how it looks:
![screenshot from 2015-01-16 22 50 52](https://cloud.githubusercontent.com/assets/640241/5785027/4978246e-9dd2-11e4-88f6-9f8ba07f2940.png)

**Comment by pixunil** [comment]
Possible link to #2995

**Comment by JosephMcc** [comment]
I can reproduce this as well

**Comment by dalcde** [comment]
Seems like dragging the window again solves the issue

**Comment by pixunil** [comment]
Yes, the issue isn't that critical it was. Before, there was really the need to restart.

**Comment by JosephMcc** [comment]
I can no longer reproduce this on git master.
