### ISSUE TITLE
Day name replaced by ellipsis in calendar applet

### ISSUE THREAD

**Issue by gauravjuvekar** [linuxmint/Cinnamon#3826]
![selection_003](https://cloud.githubusercontent.com/assets/2271906/5788551/9fca827c-9e62-11e4-901c-3b6842d7bc11.png)

````
$ lsb_release -drc
Description:	Linux Mint 17.1 Rebecca
Release:	17.1
Codename:	rebecca
$ cinnamon --version
Cinnamon 2.4.5
$ 
````

**Comment by leigh123linux** [comment]
Can you reproduce this issue using the default mint theme?

**Comment by gauravjuvekar** [comment]
Nope, happens to specific themes only, but this didn't happen in Qiana.

**Comment by leigh123linux** [comment]
Qiana probably has an older cinnamon version, the broken theme needs fixing.

**Comment by mtwebster** [comment]
What theme is that so I can reproduce?

**Comment by gauravjuvekar** [comment]
@mtwebster 

Tyr Jord http://cinnamon-spices.linuxmint.com/themes/view/153
Tyr Himinn http://cinnamon-spices.linuxmint.com/themes/view/181
Minty (for Wednesday) http://cinnamon-spices.linuxmint.com/themes/view/25

None of these are cinnamon 2.4 certified, but I didn't see any required changes to themes in the segfault announcement. http://segfault.linuxmint.com/2014/11/cinnamon-2-4/

**Comment by pixunil** [comment]
Can't reproduce issue with Cinnamon 2.6 (nightly) with none of the themes.

**Comment by dalcde** [comment]
I can reproduce it with the Numix Theme

**Comment by Vahan86** [comment]
@gauravjuvekar, is this still an issue for you with Cinnamon 3.0?

**Comment by gauravjuvekar** [comment]
Yeah, still there for 3.0.7 with the minty theme, however, it can be fixed by changing the spacing around the element in the css (forgot exactly which css property).

**Comment by JosephMcc** [comment]
Can you close this if it's a theme related issue? It doesn't happen in the default themes for Cinnamon or Mint so I don't really feel like it is a Cinnamon bug.

**Comment by gauravjuvekar** [comment]
The replaced by ellipsis part seems to be cinnamon related. This would be purely theme related if the text was displayed as is (albeit bad / overlapping with adjacent). 

Closing anyways as it is fixable from themes. Reopen if you think that this should be fixed in cinnamon.

**Comment by gauravjuvekar** [comment]
The property was 
.calendar-day-heading
changing width from 2em to 2.15 em fixed it.
