### ISSUE TITLE
Ability to add VPN connection of type vpnc no longer available in network settings 

### ISSUE THREAD

**Issue by supertzar** [linuxmint/Cinnamon#3827]
I have typically enabled VPNC functionality to connect to Cisco IPSEC VPN concentrators.  This has worked up until Mint 17.  In 17.1 Cinnamon, it appears to be broken.  

To enable this functionality in the past, I have been doing:  sudo apt-get install network-manager-vpnc network-manager-vpnc-gnome.  

After doing so, I have had an option when adding a new network connection, selecting type VPN, and vpnc shows as an entry.  Now, all I see is PPTP as an option, even after installing these packages. 

I have verified all packages are installed:

storey@roadwarrior /etc/network $ dpkg -l | grep vpnc
ii  network-manager-vpnc                        0.9.8.6-1ubuntu2                                    amd64        network management framework (VPNC plugin core)
ii  network-manager-vpnc-gnome                  0.9.8.6-1ubuntu2                                    amd64        network management framework (VPNC plugin GNOME GUI)
ii  vpnc                                        0.5.3r512-2ubuntu1                                  amd64        Cisco-compatible VPN client
ii  vpnc-scripts                                0.1~git20120602-2                                   all          Network configuration scripts for VPNC and OpenConnect

I tried removing and reinstalling the network-manager packages, restarting the GUI (alt+f2,r) and it did not help.

**Comment by liponcio** [comment]
+1
was working in Petra but in Rebecca I can't see the vpnc option
