### ISSUE TITLE
import don't work on css files (Cinnamon theming)

### ISSUE THREAD

**Issue by LaraCraft93** [linuxmint/Cinnamon#3830]
Why "import" don't works on css files? I would like to separate some things in different style sheets.

**Comment by zagortenay333** [comment]
Under cinnamon 2.4.6 it works. What version are you on?

Id like to know whether anybody has an idea whether the @import always worked in cinnamon.

**Comment by collinss** [comment]
I've been using it in my soundbox desklet for quite a few versions now without a problem. You can check out how I did it ![here](https://github.com/collinss/Cinnamon-Soundbox/blob/master/stylesheet.css).
