### ISSUE TITLE
Loop Mic Input through Speakers for Playback

### ISSUE THREAD

**Issue by FeralBytes** [linuxmint/Cinnamon#3832]
This a Feature Request, to loop microphone input to be played out of the Speakers. My use case is when I use Pandora on my Phone which has unlimited data plan to play music, rather than using my limited satelite bandwidth on the PC.

The code to implement this would be simple it just needs to be a system call like below:
`pactl load-module module-loopback latency_msec=10`
But be sure to catch the returned module number and store it for undoing the loop latter.

To undo this action a system call like below:
`pactl unload-module ##`

To visually implement it, I would recommend a check mark style box on the Input source.

Developers, thank you for your time.

Reference: https://orkultus.wordpress.com/2013/05/25/unmuting-your-mic-for-live-speaker-output-pulseaudio/

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html
