### ISSUE TITLE
Use of deprecated cogl functions in Cinnamon

### ISSUE THREAD

**Issue by austin987** [linuxmint/Cinnamon#3834]
Compiling Cinnamon 2.4.6 on Fedora 21 fails because of several deprecated functions in Cinnamon, e.g.,:
st/st-background-effect.c: In function 'st_background_effect_pre_paint':
st/st-background-effect.c:262:9: error: 'cogl_read_pixels' is deprecated (declared at /usr/include/cogl/cogl/deprecated/cogl-framebuffer-deprecated.h:228): Use 'cogl_framebuffer_read_pixels' instead [-Werror=deprecated-declarations]
         cogl_read_pixels (self->bg_posx_i,
         ^
st/st-background-effect.c:279:13: error: 'cogl_texture_new_from_data' is deprecated (declared at /usr/include/cogl/cogl/deprecated/cogl-auto-texture.h:118): Use 'cogl_texture_2d_new_from_data__OR__cogl_texture_2d_sliced_new_from_data' instead [-Werror=deprecated-declarations]
             self->bg_texture = cogl_texture_new_from_data  (self->bg_width_i,
             ^
st/st-background-effect.c:354:15: error: 'cogl_texture_new_with_size' is deprecated (declared at /usr/include/cogl/cogl/deprecated/cogl-auto-texture.h:54): Use 'cogl_texture_2d_new_with_size__OR__cogl_texture_2d_sliced_new_with_size' instead [-Werror=deprecated-declarations]
               self->bg_sub_texture = cogl_texture_new_with_size (self->bg_width_i, self->bg_height_i,
               ^
st/st-background-effect.c: In function 'st_background_effect_paint_target':
st/st-background-effect.c:412:7: error: 'cogl_push_source' is deprecated (declared at /usr/include/cogl/cogl/cogl1-context.h:618) [-Werror=deprecated-declarations]
       cogl_push_source (self->pipeline2);
       ^
st/st-background-effect.c:414:7: error: 'cogl_pop_source' is deprecated (declared at /usr/include/cogl/cogl/cogl1-context.h:634) [-Werror=deprecated-declarations]
       cogl_pop_source ();
       ^
st/st-background-effect.c:417:7: error: 'cogl_offscreen_new_to_texture' is deprecated (declared at /usr/include/cogl/cogl/cogl-offscreen.h:127): Use 'cogl_offscreen_new_with_texture' instead [-Werror=deprecated-declarations]
       vertical_FBO = cogl_offscreen_new_to_texture (self->bg_sub_texture);
       ^
st/st-background-effect.c:418:7: error: 'cogl_push_framebuffer' is deprecated (declared at /usr/include/cogl/cogl/deprecated/cogl-framebuffer-deprecated.h:138) [-Werror=deprecated-declarations]
       cogl_push_framebuffer ((CoglFramebuffer*)vertical_FBO);
       ^

I'll attach a log.

**Comment by austin987** [comment]
Can't seem to attach a log, so here it is inline:
grep error ~/make.txt
st/st-background-effect.c:262:9: error: 'cogl_read_pixels' is deprecated (declared at /usr/include/cogl/cogl/deprecated/cogl-framebuffer-deprecated.h:228): Use 'cogl_framebuffer_read_pixels' instead [-Werror=deprecated-declarations]
st/st-background-effect.c:279:13: error: 'cogl_texture_new_from_data' is deprecated (declared at /usr/include/cogl/cogl/deprecated/cogl-auto-texture.h:118): Use 'cogl_texture_2d_new_from_data__OR__cogl_texture_2d_sliced_new_from_data' instead [-Werror=deprecated-declarations]
st/st-background-effect.c:354:15: error: 'cogl_texture_new_with_size' is deprecated (declared at /usr/include/cogl/cogl/deprecated/cogl-auto-texture.h:54): Use 'cogl_texture_2d_new_with_size__OR__cogl_texture_2d_sliced_new_with_size' instead [-Werror=deprecated-declarations]
st/st-background-effect.c:412:7: error: 'cogl_push_source' is deprecated (declared at /usr/include/cogl/cogl/cogl1-context.h:618) [-Werror=deprecated-declarations]
st/st-background-effect.c:414:7: error: 'cogl_pop_source' is deprecated (declared at /usr/include/cogl/cogl/cogl1-context.h:634) [-Werror=deprecated-declarations]
st/st-background-effect.c:417:7: error: 'cogl_offscreen_new_to_texture' is deprecated (declared at /usr/include/cogl/cogl/cogl-offscreen.h:127): Use 'cogl_offscreen_new_with_texture' instead [-Werror=deprecated-declarations]
st/st-background-effect.c:418:7: error: 'cogl_push_framebuffer' is deprecated (declared at /usr/include/cogl/cogl/deprecated/cogl-framebuffer-deprecated.h:138) [-Werror=deprecated-declarations]
st/st-background-effect.c:419:7: error: 'cogl_push_source' is deprecated (declared at /usr/include/cogl/cogl/cogl1-context.h:618) [-Werror=deprecated-declarations]
st/st-background-effect.c:421:7: error: 'cogl_pop_source' is deprecated (declared at /usr/include/cogl/cogl/cogl1-context.h:634) [-Werror=deprecated-declarations]
st/st-background-effect.c:422:7: error: 'cogl_pop_framebuffer' is deprecated (declared at /usr/include/cogl/cogl/deprecated/cogl-framebuffer-deprecated.h:153) [-Werror=deprecated-declarations]
st/st-background-effect.c:426:7: error: 'cogl_push_source' is deprecated (declared at /usr/include/cogl/cogl/cogl1-context.h:618) [-Werror=deprecated-declarations]
st/st-background-effect.c:429:7: error: 'cogl_pop_source' is deprecated (declared at /usr/include/cogl/cogl/cogl1-context.h:634) [-Werror=deprecated-declarations]
st/st-background-effect.c:439:3: error: 'cogl_push_source' is deprecated (declared at /usr/include/cogl/cogl/cogl1-context.h:618) [-Werror=deprecated-declarations]
st/st-background-effect.c:441:3: error: 'cogl_pop_source' is deprecated (declared at /usr/include/cogl/cogl/cogl1-context.h:634) [-Werror=deprecated-declarations]
st/st-background-effect.c:451:3: error: 'cogl_push_source' is deprecated (declared at /usr/include/cogl/cogl/cogl1-context.h:618) [-Werror=deprecated-declarations]
st/st-background-effect.c:453:3: error: 'cogl_pop_source' is deprecated (declared at /usr/include/cogl/cogl/cogl1-context.h:634) [-Werror=deprecated-declarations]
st/st-background-effect.c:543:11: error: 'cogl_texture_new_from_file' is deprecated (declared at /usr/include/cogl/cogl/deprecated/cogl-auto-texture.h:84): Use 'cogl_texture_2d_new_from_file__OR__cogl_texture_2d_sliced_new_from_file' instead [-Werror=deprecated-declarations]
st/st-background-effect.c:794:3: error: 'cogl_texture_new_from_file' is deprecated (declared at /usr/include/cogl/cogl/deprecated/cogl-auto-texture.h:84): Use 'cogl_texture_2d_new_from_file__OR__cogl_texture_2d_sliced_new_from_file' instead [-Werror=deprecated-declarations]
st/st-background-effect.c:823:1: error: no previous prototype for 'st_background_effect_new' [-Werror=missing-prototypes]
st/st-bin.c:465:7: error: 'clutter_actor_unparent' is deprecated (declared at /usr/include/clutter-1.0/clutter/deprecated/clutter-actor.h:58): Use 'clutter_actor_remove_child' instead [-Werror=deprecated-declarations]
st/st-bin.c:475:7: error: 'clutter_actor_set_parent' is deprecated (declared at /usr/include/clutter-1.0/clutter/deprecated/clutter-actor.h:54): Use 'clutter_actor_add_child' instead [-Werror=deprecated-declarations]
st/st-box-layout.c:944:7: error: 'cogl_push_matrix' is deprecated (declared at /usr/include/cogl/cogl/cogl1-context.h:290): Use 'cogl_framebuffer_push_matrix' instead [-Werror=deprecated-declarations]
st/st-box-layout.c:945:7: error: 'cogl_translate' is deprecated (declared at /usr/include/cogl/cogl/cogl1-context.h:333): Use 'cogl_framebuffer_translate' instead [-Werror=deprecated-declarations]
st/st-box-layout.c:952:7: error: 'cogl_pop_matrix' is deprecated (declared at /usr/include/cogl/cogl/cogl1-context.h:301): Use 'cogl_framebuffer_push_matrix' instead [-Werror=deprecated-declarations]
st/st-box-layout.c:972:5: error: 'cogl_clip_push_rectangle' is deprecated (declared at /usr/include/cogl/cogl/deprecated/cogl-clip-state.h:126): Use 'cogl_framebuffer_push_rectangle_clip' instead [-Werror=deprecated-declarations]
st/st-box-layout.c:986:5: error: 'cogl_clip_pop' is deprecated (declared at /usr/include/cogl/cogl/deprecated/cogl-clip-state.h:207): Use 'cogl_framebuffer_pop_clip' instead [-Werror=deprecated-declarations]
st/st-box-layout.c:1004:7: error: 'cogl_push_matrix' is deprecated (declared at /usr/include/cogl/cogl/cogl1-context.h:290): Use 'cogl_framebuffer_push_matrix' instead [-Werror=deprecated-declarations]
st/st-box-layout.c:1005:7: error: 'cogl_translate' is deprecated (declared at /usr/include/cogl/cogl/cogl1-context.h:333): Use 'cogl_framebuffer_translate' instead [-Werror=deprecated-declarations]
st/st-box-layout.c:1012:7: error: 'cogl_pop_matrix' is deprecated (declared at /usr/include/cogl/cogl/cogl1-context.h:301): Use 'cogl_framebuffer_push_matrix' instead [-Werror=deprecated-declarations]
st/st-box-layout.c:1029:5: error: 'cogl_clip_push_rectangle' is deprecated (declared at /usr/include/cogl/cogl/deprecated/cogl-clip-state.h:126): Use 'cogl_framebuffer_push_rectangle_clip' instead [-Werror=deprecated-declarations]
st/st-box-layout.c:1043:5: error: 'cogl_clip_pop' is deprecated (declared at /usr/include/cogl/cogl/deprecated/cogl-clip-state.h:207): Use 'cogl_framebuffer_pop_clip' instead [-Werror=deprecated-declarations]
st/st-box-layout.c:1255:3: error: 'clutter_container_add_actor' is deprecated (declared at /usr/include/clutter-1.0/clutter/deprecated/clutter-container.h:43): Use 'clutter_actor_add_child' instead [-Werror=deprecated-declarations]
st/st-box-layout.c:1276:3: error: 'clutter_container_add_actor' is deprecated (declared at /usr/include/clutter-1.0/clutter/deprecated/clutter-container.h:43): Use 'clutter_actor_add_child' instead [-Werror=deprecated-declarations]
cc1: all warnings being treated as errors
cc1: all warnings being treated as errors
cc1: all warnings being treated as errors

**Comment by austin987** [comment]
cogl-devel-1.18.2-9.fc21.x86_64

**Comment by JosephMcc** [comment]
Most all of the Cinnamon packages will give you these deprecation warnings. The gnome developers deprecate and change things with every new version of Gnome.

**Comment by austin987** [comment]
Sure, but if -Werror is enabled by default, then warnings such as these should be considered bugs.

**Comment by leigh123linux** [comment]
It compiles fine for me 

https://koji.fedoraproject.org/koji/buildinfo?buildID=604963

https://admin.fedoraproject.org/updates/cinnamon-2.4.6-1.fc21

use this if you wish to compile the code yourself

```
./configure \
 --disable-static \
 --disable-rpath \
 --disable-schemas-compile \
 --enable-introspection=yes \
 --enable-compile-warnings=no
```

You can close this report and all the other related bug reports to this as we don't need the extra noise!

**Comment by austin987** [comment]
That compiles for me, but fails to run:
[austin@localhost Cinnamon-2.4.6]$ ./src/cinnamon --replace

(lt-cinnamon-real:17047): Cjs-WARNING **: JS ERROR: Error: No JS module 'ui' found in search path
@<main>:1

Window manager warning: Log level 32: Execution of main.js threw exception: JS_EvaluateScript() failed

**Comment by leigh123linux** [comment]
The error is clear, it's looking for /usr/share/cinnamon/js/ui/ or /usr/local/share/cinnamon/js/ui/ js files.

**Comment by austin987** [comment]
Well, that's not completely clear, those paths aren't specified in the error. In any case, files do exist there:
[austin@localhost ~]$ ls /usr/share/cinnamon/js/ui/
appFavorites.js            flashspot.js           placesManager.js
applet.js                  hotCorner.js           popupMenu.js
appletManager.js           keybindings.js         radioButton.js
appSwitcher                keyboard.js            runDialog.js
backgroundManager.js       layout.js              scripting.js
boxpointer.js              lightbox.js            search.js
checkBox.js                link.js                settings.js
cinnamonDBus.js            lookingGlassDBus.js    slideshowManager.js
cinnamonEntry.js           lookingGlass.js        soundManager.js
cinnamonMountOperation.js  magnifierDBus.js       statusIconDispatcher.js
desklet.js                 magnifier.js           systray.js
deskletManager.js          main.js                themeManager.js
dnd.js                     messageTray.js         tooltips.js
edgeFlip.js                modalDialog.js         tweener.js
environment.js             notificationDaemon.js  windowAttentionHandler.js
expo.js                    overrides.js           windowManager.js
expoThumbnail.js           overview.js            workspace.js
extension.js               panel.js               workspacesView.js
extensionSystem.js         panelMenu.js           xdndHandler.js

**Comment by leigh123linux** [comment]
Try installing it instead of trying to run it from the compile directory.

**Comment by mtwebster** [comment]
Closing all of these - yes I know we have deprecated functions, yes I know there are issues, but there doesn't need to be 10 reports for it.  We'll fix them when we get around to it.
