### ISSUE TITLE
 implicit declaration of function 'cogl_framebuffer_allocate' 

### ISSUE THREAD

**Issue by austin987** [linuxmint/Cinnamon#3836]
st/st-texture-cache.c:595:3: error: implicit declaration of function 'cogl_framebuffer_allocate' [-Werror=implicit-function-declaration]
   if (!cogl_framebuffer_allocate (offscreen, &error))
   ^

cogl-devel-1.18.2-9.fc21.x86_64
cinnamon 2.4.6, gcc 4.9.2

must workaround issue 3834 and issue 3835 to see this.

**Comment by anandrkris** [comment]
@austin987 - If you could narrow down the issues in code to this level of detail, perhaps you could submit a pull request. No offense meant, just a suggestion.
