### ISSUE TITLE
cinnamon-2.4.6: applets don't start due to not finding libcinnamon-js.so

### ISSUE THREAD

**Issue by pacho2** [linuxmint/Cinnamon#3843]
Looks like gnome-shell includes some hacks to prevent a similar problem:
https://git.gnome.org/browse/gnome-shell/commit/?id=3c81e9f0e7e06d77528643c749868f7524f572b0
https://git.gnome.org/browse/gnome-shell/commit/?id=b4a48a7644122f09b01f898fb64d184becba971d

But cinnamon looks to fail and applets cannot start due to it not finding libcinnamon-js.so. It affects not only to Gentoo, but also to other distributions like OpenSuSE and Mageia:
https://bugs.gentoo.org/show_bug.cgi?id=536374
https://bugzilla.opensuse.org/show_bug.cgi?id=904414

They are for now applying this workaround to solve this:
http://svnweb.mageia.org/packages/cauldron/cinnamon/releases/2.4.5/1.mga5/SPECS/cinnamon.spec?revision=800478&view=co
# fix rpath for CinnamonJS
# see http://bugzilla.opensuse.org/show_bug.cgi?id=904414

chrpath -d %{buildroot}%{_bindir}/cinnamon
patchelf --force-rpath --set-rpath %{_libdir}/cinnamon %{buildroot}%{_bindir}/cinnamon
chrpath -l %{buildroot}%{_bindir}/cinnamon

Thanks for your help on this

**Comment by Vahan86** [comment]
@pacho2, is this still an issue for you with Cinnamon 3?

**Comment by Vahan86** [comment]
@JosephMcc, can we close this issue?
