### ISSUE TITLE
cinnamon-settings backgrounds will not import new photo

### ISSUE THREAD

**Issue by urcminister** [linuxmint/Cinnamon#3844]
Linux Mint 17.1 Cinnamon Rebecca 64bit.  I open cinnamon-settings backgrounds, click on Pictures and then click the '+' symbol.  I get a file-browser that takes me to the image I want (a .jpg).  Nothing I try by way of left/right/doubleclick etc. lets me select or use the image.  Right click on the desktop lets me select an image - but only if it is in the ~/Pictures directory.  I am completely new to Mint as well as to Cinnamon, so I hope I'm, making some sense with thie bug report.  Will be glad to help if asked.     Barry.

**Comment by pixunil** [comment]
With this browser you should choose a folder (images are greyed out), it'll then appear in the right panel.
You can select the folder there now and choose your picture.

Maybe you can convert this to a feature request, as it is a much easier way to choose a picture.

**Comment by urcminister** [comment]
Thanks for that.  This was so non-intuitive it ought to go as either a bug or a feature request.  Even after your instructions, it took me a while to realise exactly what to do!  Sorry not to have seen this for myself.

**Comment by tylery71** [comment]
If you right click on a image you can also set it as wallpaper. So if you want to set a individual image, just right click on it - not in backgrounds but through the file manager
The backgrounds menu is angled more at having a entire directory of images
The + & - are to set personalized directories.

**Comment by FeralBytes** [comment]
I have to concur the default behaviour of the Desktop Wallpaper Settings is not intuitive. I took about 10 minutes and some searching on the Forums before i found the answer as to how I could set an image as the background.

**Comment by anandrkris** [comment]
Tooltip says Add New folder but still should allow addition of individual images as most users would try to do that. I think the question then would be how to place image in a category / folder. 
Perhaps easier way out it is add image and show all images under folder as well.
@JosephMcc - Any thoughts?

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html
