### ISSUE TITLE
`skip_taskbar` flag not being respected

### ISSUE THREAD

**Issue by twolfson** [linuxmint/Cinnamon#3845]
I am trying to use `atom-shell` for a desktop application. It is toggling X11's `skip_taskbar` flag:

https://github.com/atom/atom-shell/blob/v0.20.7/atom/browser/native_window_views.cc#L538-L539

However, when I am using it in Linux Mint, the flag is not being respected. I reduced the case to using:

``` bash
wmctrl -r :ACTIVE: -b toggle,skip_taskbar
```

**Taskbar present** (as expected)

![selection_010](https://cloud.githubusercontent.com/assets/902488/5851263/2bd251cc-a1ca-11e4-9b26-ab4f14ede990.png)

**Taskbar still present after toggle** (unexpected)

![selection_011](https://cloud.githubusercontent.com/assets/902488/5851265/2e5bc180-a1ca-11e4-97a2-6ab47904f3e5.png)

For sanity, I checked in an Ubuntu VM and it is being respected there.

**Taskbar present**

![selection_008](https://cloud.githubusercontent.com/assets/902488/5851269/47b2dfa6-a1ca-11e4-861d-c4a1e5993399.png)

**Taskbar not present after toggle**

![selection_009](https://cloud.githubusercontent.com/assets/902488/5851270/4bff797a-a1ca-11e4-995b-82ba33b8293b.png)

**Comment by twolfson** [comment]
Any word on whether this will be looked into?

**Comment by Vahan86** [comment]
@twolfson, is this still an issue for you with Cinnamon 3?

**Comment by JosephMcc** [comment]
https://github.com/linuxmint/Cinnamon/commit/ed4f472ad7d49c92ca30cde869027b2faaa8ad1e and https://github.com/linuxmint/Cinnamon/issues/5162

**Comment by twolfson** [comment]
Unfortunately I'm still on Cinnamon@2.4.8. Whenever I upgrade and if there's an issue still, then I'll open another issue. That commit + PR looks promising though. Thanks for the work on this! =)

**Comment by JosephMcc** [comment]
If you discover it's still an issue, feel free to post back here. These can be reopened if needed.
