### ISSUE TITLE
Option to change Cinnamon menu applet panel area background and menu icon animation and size 

### ISSUE THREAD

**Issue by freemangilgamesh** [linuxmint/Cinnamon#3851]
I suggest that we add an option to edit the  colour of Cinnamon menu applet panel area and menu icon animation and size in Cinnamon. For the first I made a mockup theme with a png and not a special icon code. Get this theme at http://gnome-look.org/content/show.php/Lux?content=168706&PHPSESSID=37ab0dd5844f44113279e6b676d0115d

<a href="http://imgur.com/gHKVNIU"><img src="http://i.imgur.com/gHKVNIU.png" title="source: imgur.com" /></a>

**Comment by dalcde** [comment]
Reason?

**Comment by leigh123linux** [comment]
-1

**Comment by lestcape** [comment]
@freemangilgamesh I really don't know what do you want? You know that you can make your own theme with the color that you want on the menu area. What you could request could be a way to also set the default image for the menu as an special value on the css. This could have some sense, maybe...

**Comment by freemangilgamesh** [comment]
I can change the menu area only if I use a png for the panel. The menu applet area is part of the applets section in cinnamon.css and if I edit its background this will effect other applets too!!

**Comment by lestcape** [comment]
@freemangilgamesh ok, thats the trick, add a way to set a default image and set the style of the menu area, is a good request... but it's not what you say or it's? On configurable menu you have a selector for the menu area also taking on account the menu position. I not remember what happend on cinnamon menu, sorry. >(

**Comment by freemangilgamesh** [comment]
Check this theme and you'll see what I'm talking about  http://gnome-look.org/content/show.php/Lux?content=168706

**Comment by dalcde** [comment]
freemangilgamesh: is there any reason why we have to make the menu special? Why not, say, the date applet?

**Comment by lestcape** [comment]
@dalcde i think that he can not say well what he want... Apparently he don't want to make the cinnamon menú special on the cinnamon theme. What he want, is the possibility to apply a selector to the menu if he want to do that on his own theme. He have several themes on spices... I don't see a reason to do what he want, but also i don't see a reason to not do. Is like any other thing, just the possibility to change the appearance... like any other box on the menu that right now have a selector that can be use on a css file.
