### ISSUE TITLE
Running cinnamon under valgrind fails

### ISSUE THREAD

**Issue by austin987** [linuxmint/Cinnamon#3852]
Hello,

I'm trying to run cinnamon under valgrind, to track down the memory leak in #2986. However, it seems that cinnamon fails to run under valgrind (silently exits and restarts itself). There is very little output to stdout/stderr, nothing different from a non-valgrind run (is there a way to increase Cinnamon's verbosity?):
      JS LOG: About to start Cinnamon
Window manager warning: Trying to remove non-existent custom keybinding "magnifier-zoom-in".
Window manager warning: Trying to remove non-existent custom keybinding "magnifier-zoom-out".
      JS LOG: Cinnamon started at Mon Jan 26 2015 04:06:38 GMT-0600 (CST)

(cinnamon:1642): St-CRITICAL **: st_widget_get_theme_node called on the widget [0x18612010 StBoxLayout.menu-selected-app-box] which is not in the stage.
      JS LOG: network applet: Cannot find connection for active (or connection cannot be read)
Window manager warning: Log level 16: Symbolic icon /usr/share/cinnamon/applets/notifications@cinnamon.org/empty-notif-symbolic.svg is not in an icon theme directory
Window manager warning: Log level 16: Symbolic icon /usr/share/cinnamon/applets/windows-quick-list@cinnamon.org/windows-quick-list-symbolic.svg is not in an icon theme directory

commandline used to run cinnamon under valgrind:
valgrind --trace-children=yes --trace-children-skip=/usr/bin/pkill --track-origins=yes --gen-suppressions=all --suppressions=/home/austin/cinnamon.supp --log-file=/home/austin/cinnamon.log --tool=memcheck --num-callers=25 --leak-check=yes --show-leak-kinds=definite --leak-resolution=high /usr/bin/cinnamon --replace

tested with cinnamon 2.2.16 and 2.4.5, valgrind is 3.10.0

**Comment by lestcape** [comment]
Thats intresting... See some currently problems: https://github.com/linuxmint/Cinnamon/issues/3690 I think that you need to fixed the known problem first and then you could find more problems.

**Comment by austin987** [comment]
The issue is that valgrind won't cooperate with cinnamon at all, making it
very difficult to find the leak in #2986, #3690, or any others.

On Mon, Jan 26, 2015 at 7:06 AM, Lester Carballo Pérez <
notifications@github.com> wrote:

> Thats intresting... See some currently problems: #3690
> <https://github.com/linuxmint/Cinnamon/issues/3690> I think that you need
> to fixed the known problem first and then you could find more problems.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/linuxmint/Cinnamon/issues/3852#issuecomment-71457643>.
>



-- 
-Austin

**Comment by Vahan86** [comment]
@austin987, does this issue still relevant to Cinnamon 3.6?

**Comment by austin987** [comment]
Hi Vahan,

I can't say, I stopped using cinnamon due to
https://github.com/linuxmint/Cinnamon/issues/2986.

If you're interested, it should be trivial to reproduce with valgrind
installed from repos.

Good luck.
