### ISSUE TITLE
Add a possibility to filter the search providers

### ISSUE THREAD

**Issue by lestcape** [linuxmint/Cinnamon#3854]
First at all, thanks for this amazing feature.
I'm thinking on a possibility to filter the providers that could use some specific extension, by the uuid of this extension. The request is because we can have different types of extensions and some of them could be specialized on some type of things(a role). Receive the data from all the search providers could not be what they want. Maybe we can register the uuid of the requester extension and with then two list:

"allowed_providers" and "denied_providers" and also we can use "All" and "None" as a modifiers (like policykit do) instead of a list of providers.

Again thanks, specially to @glebihan

**Comment by glebihan** [comment]
That is something I've thought about but I've had a different approach.
Instead of filtering the providers, I give each result a type, which can then be used to filter results.
The reason I'm doing it that way is because a unique provider can have results of different types (see the tracker example : https://github.com/linuxmint/Cinnamon/tree/master/doc/search-providers-examples/trackerprovider%40cinnamon.org).

An example of this filtering can be seen in the menu applet : https://github.com/linuxmint/Cinnamon/blob/master/files/usr/share/cinnamon/applets/menu%40cinnamon.org/applet.js#L2581 (we're not interested in software results there, as we already list them).

What remains to be done is to standardize the list of result types, and to force providers to indicate the type (which isn't the case yet).

**Comment by lestcape** [comment]
@glebihan thanks for the explanation, and yes, my request it's because i don't see yet an standar way to always filter the result, but is good that you consider to forced the provider to indicate the type.

About the approaches of filter providers as a postcondition, this could be a creepy thing if some one added an slower provider to the list and thats is not needed on the extension. So or provider could emit the search result "asynchronous" (better say on different moments), or the extension could need to wait for a response of a provider that don't needed. I hope that this helped to find the better way, i don't have a clear way to do the things yet, but well i need to test for some time how this is working to have a better idea. 

Again thanks.

**Comment by glebihan** [comment]
@lestcape : all the current search providers provided in examples are already working asynchronously (except for those that give instantaneous results), and all search providers should always do so.
So the extension doesn't wait for results, it receives them as they come.

**Comment by lestcape** [comment]
@glebihan I asked just for nothing, i try to share my ideas faster without tested anything, because it's better changed the thing now than after when is on use. But what can i say, you done the thing how i want thanks!!!

**Comment by glebihan** [comment]
OK, then. Let's close this issue for now then. Let me know when you've had a chance to test it a little further.
Thanks for your feedback.

**Comment by lestcape** [comment]
Ok, this are only ideas...
I think that what you say it's that all providers will do asynchronous the response at one time and what i say it's not wait for one provider send the result of the others... After make my own "search provider" to search for packages and to search on web, i also note that i need an action cancel, when the user changed  faster the search pattern  (He is writing the pattern in this moment). Otherwise we need to add a search button to perform the search.

**Comment by glebihan** [comment]
@lestcape : I really encourage you to look at how I implemented things, and at the examples at https://github.com/linuxmint/Cinnamon/tree/master/doc/search-providers-examples/
Among those are already present a provider to search for packages as well as a Wikipedia search, and the issue you're describing with searching while typing is already handled.

As for asynchronous thing, it also already works as you described : each provider sends its results as soon as it's done doing its search and the results are immediately displayed. It doesn't wait for all providers to be done.

**Comment by lestcape** [comment]
@glebihan ok, thanks and sorry.

**Comment by glebihan** [comment]
@lestcape : no need to be sorry, feedback is definitely welcome

**Comment by lestcape** [comment]
@glebihan thanks for the pretty last example, is more clear for me now. I will try to use on my code... The "sorry", is because my emotion with this feature and speak without test it, I only try to understand the code because i like this...
