### ISSUE TITLE
Add Keyboard layout option - Swap Ctrl-keys with Win-keys

### ISSUE THREAD

**Issue by decoursin** [linuxmint/Cinnamon#3855]
I would like to swap my right Windows key with my right Ctrl key, but I cannot do this in the latest version of Linux Mint 17.1 Cinnamon. Could you please add this functionality? There is a lot of keyboard layout options (thank you for all of them!) but this exact option is not provided. I use my right Ctrl-key for vim that's why.

**Comment by leigh123linux** [comment]
Why should they change all keybindings on dozens of packages just to suit you!!

**Comment by anandrkris** [comment]
Can be done with xmodmap easily?

**Comment by decoursin** [comment]
I'm not asking them to change default keyboard layouts. I'm asking them to add another option for users to be able to change keybindings. There exists options for users to do this: Settings -> Keyboard -> Keyboard layouts -> Options. However, you are missing an option to swap Ctrl-key(s) with Win-key(s).

Thanks for the xmodmap suggestion. I have not heard of that yet. I suppose that I will look into it when I get a chance.

**Comment by ManIVIctorious** [comment]
I think the most generic way to do this would be a graphical implementation of xmodmap

**Comment by dalcde** [comment]
The options are not supplied by Cinnamon, but by xkb itself. There is nothing we can do.
