### ISSUE TITLE
Panel becomes blank and windows dissapear when multiple windows open

### ISSUE THREAD

**Issue by mateevici** [linuxmint/Cinnamon#3856]
I’m using Cinnamon on Ubuntu 14.10 and I’ve been having trouble ever since.

The problem is that if I have a large number of open windows, the panel will show all the open windows as blank and some of the open windows won’y show anymore.

I’ve noticed that this happens also when I have an open window in fullscreen on a second monitor and switch between desktops.

How can I debug it?

P.S.: in the screenshot I hav a dual screen monitor, with the secondary monitor on the top, with no windows in it.
![screenshot from 2015-01-27 11 51 19](https://cloud.githubusercontent.com/assets/10723794/5917247/f62f1e7e-a61a-11e4-82de-7b51361c3af2.png)

**Comment by pixunil** [comment]
There are two logs that are relevant:

- `~/.cinnamon/glass.log`
- `~/.xsession-errors`

Please post them or parts of them so we can track down this bug.

Please provide us also those information:

- version of Cinnamon
- info about the apps (which, how many)
- a nice "how to reproduce" description
- which applets do you use (Cinnamon or 3rd-party)

**Comment by Vahan86** [comment]
@mateevici, is this still an issue for you with Cinnamon 3.2?

**Comment by JosephMcc** [comment]
The OP was asked for more info the day he posted (over 2 years ago) and never responded.
