### ISSUE TITLE
Having Hexchat open moves icons and text on panel downwards

### ISSUE THREAD

**Issue by ontherunvaro** [linuxmint/Cinnamon#3857]
HexChat's window title displays in two lines on window list in default panel. This makes all icons and applets on the left hand side of the window list, as well as the text and icons in the rest of windows, move down by about half of the panel (see attachment).
This bug can be reproduced simply by opening hexchat and connecting to a network (unconnected hexchat has 1 line  title)
![captura de pantalla de 2015-01-27 15 43 19](https://cloud.githubusercontent.com/assets/8677743/5920675/a1845e24-a63e-11e4-8493-b7b8d8958487.png)
Additional info:
Linux Mint 17.1 out of the box, no additional applets, cinnamon 2.4.6.
glass.log: http://paste.linuxmint.com/view/gfnn
xsession-errors: http://paste.linuxmint.com/view/bupy

**Comment by dalcde** [comment]
Probably same issue as #3985. See if the window-list applet from git helps

**Comment by JosephMcc** [comment]
Weird. I use hexchat everyday and have never seen an effect like described here.
