### ISSUE TITLE
Add the option to create an Access Point in Cinnamon network manager to share network in ad hoc mode with Android devices

### ISSUE THREAD

**Issue by freemangilgamesh** [linuxmint/Cinnamon#3860]
I suggest you add an option to create an access point like on "plasma-nm"  http://ubuntuhandbook.org/index.php/2014/06/share-internet-with-android-ubuntu-1404/ to be able to share network with Android devices. This is different from the WiFi Hotspot option we have on Ubuntu and Linux Mint.

**Comment by leigh123linux** [comment]
I suggest you close this report and file your request against the right component (cinnamon-control-center).

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html
