### ISSUE TITLE
GtkBox elements rendering incorrectly with background-color: transparent

### ISSUE THREAD

**Issue by wrouesnel** [linuxmint/Cinnamon#3861]
Starting Gnome Logs (under some circumstances) results in a transparent GIEventView
![screenshot from 2015-01-30 10 27 07](https://cloud.githubusercontent.com/assets/772445/5968365/ba8545f4-a86a-11e4-9053-4d80b5d99754.png)

(PNG does not properly capture the effect in screenshot mode)

This also appears to be effecting the NetworkManager network view, but does result in a solid black element:
![screenshot from 2015-01-30 10 28 35](https://cloud.githubusercontent.com/assets/772445/5968376/daac6808-a86a-11e4-9afb-f8697dbee09d.png)

As far as I can tell, both of these seem to be a product of having GtkBox default to transparent in mint-themes-gtk3 however if I attach a debugger or gtkparasite or similar, both adopt their correctly light-grey background color - which makes me think that somehow Cinnamon or Muffin is picking up the wrong library to draw the themes by default.

**Comment by wrouesnel** [comment]
Ok resolved this: this is related to this bug here: https://bugs.launchpad.net/egtk/+bug/1303783

and is caused by having overlay-scrollbars installed. It can be fixed by `sudo apt-get remove overlay-scrollbars`

**Comment by JosephMcc** [comment]
@wrouesnel there is a wip version of the mint theme for gtk3.14 here: https://github.com/linuxmint/mint-themes-gtk3

Fixes quite a few other issues under 3.14.
