### ISSUE TITLE
drag & drop for Menu and Panel

### ISSUE THREAD

**Issue by cptX** [linuxmint/Cinnamon#3865]
It would be a great enhancement to support drag & drop from desktop icons to the Menu, from Panel to the Menu and from one folder of the Menu to another without the need for Menu Editor. In general to support full exchangeability of icons between these 3 groups (desktop, Menu, Panel).

Right now, the only thing that works is drag & drop an icon from a Menu to the Panel. The opposite is not possible, the drag & drop from and to Desktop is not possible and also the drag & drop from one folder to another in the Menu is not possible.

I discovered that by right clicking on an Icon/Link in a menu a new menu appears underneath with the following items:
Add to Panel
Add to Desktop
Add to Favorites
Uninstall

By clicking these actions the above requested functionality is achieved but not with drag & drop. I think it makes clear sense to support the same capabilites with drag & drop.

**Comment by lestcape** [comment]
https://github.com/linuxmint/Cinnamon/issues/5028#issuecomment-262874381

**Comment by lestcape** [comment]
I see grab_notifier in **src/cinnamon-global.c**: https://github.com/linuxmint/Cinnamon/search?q=grab_notifier&type=Code&utf8=%E2%9C%93
but the windows is never mapped or shown, i don't know if this Gtk windows cloud be used to also receive the Gtk drag and drop information and allow send it to cjs. But if will be possible, cinnamon could react to a gtk drag and drop and accept drops from gtk application like nemo.

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html
