### ISSUE TITLE
Allow to disable Super_L shortcut

### ISSUE THREAD

**Issue by lstrzelecki** [linuxmint/Cinnamon#3866]
In previous verson of Cinamon/Mint17.1 there was option to disable Super_L shortcut which usually open Menu.

Now:
1. This option is not avaliable under System Settings ->  Keyboard
2. This shortcut (Super_L) blocks other shortcuts which contain this button (i.e. Super_L + Esc)

**Comment by pixunil** [comment]
You can disable the Super_L shortcut with the settings of the menu applet.
Just right click on the menu applet and choose "Settings...", then a new window will open and in the first row you should see the shortcuts.
To remove the Super_L one, click on the button labelled with Super_L and press Backspace.

**Comment by anandrkris** [comment]
A screenshot i had attached in another report
https://cloud.githubusercontent.com/assets/4663298/4665637/8b2e33ae-554c-11e4-92e7-d3d64d444857.png

**Comment by lestcape** [comment]
I think that maybe could help create a new category on keyboard module of cinnamon-settings to also configure the current keyboard shortcut assigned by an extension, but possible this will need to be implemented very different to the current keyboard shortcut... I sure that @mtwebster have a plan to enhanced keyboard shortcut on the future even more.

**Comment by lstrzelecki** [comment]
@pixunil 
I had that option on 'Configure...'  Never suspect that there can be that option. Thanks.
So its doable. 

It mislead me, because in prev version of cinnamon it was possible from System Settings > Keyboard
