### ISSUE TITLE
USB image writer uses a tonne of CPU in pulses and stutters in bursts of 2 seconds on write

### ISSUE THREAD

**Issue by megz** [linuxmint/Cinnamon#3869]
as per title, also if you look at system monitor once an ISO has been written to a USB pen using the image writer, all but one Core goes back to normal load.. the remaining core is 100% loaded until the application is closed ?!

thanks

**Comment by anandrkris** [comment]
I don't suppose this is a Cinnamon specific issue.
https://github.com/linuxmint/mintstick/issues Should be filed here, i believe.
