### ISSUE TITLE
Desktop icons get displaced randomly . .

### ISSUE THREAD

**Issue by ACinnamonUserInUK** [linuxmint/Cinnamon#3874]
. . after a restart, sometimes. Possibly this is caused by restarting Cinnamon (using the panel) and/or by using the 'align' feature. (Also: why does the align feature not impose regular vertical spacing upon icons? The feature seems to line icons up only horizontally.)

EDIT: the icon displacement is not by more than a few hundred pixels, and seems to have some sort of order to it.

**Comment by Vahan86** [comment]
@ACinnamonUserInUK, is this still an issue for you in Cinnamon 3.0?

**Comment by ACinnamonUserInUK** [comment]
@Vahan86, no it isn't. Thanks for asking. (Admittedly, I can't get icons to dodge my 'Conky', but I think that is probably Conky's fault, not Cinnamon's.)

**Comment by Vahan86** [comment]
@ACinnamonUserInUK, thank you for response. In this case, could you please close the issue?
