### ISSUE TITLE
Scale missing feature

### ISSUE THREAD

**Issue by PierreMoustache** [linuxmint/cinnamon#3875]
Hello everyone!
I'm loving the applets like scale or expo.
I choose scale because I'm using only one workspace,  and expo is a bit slower on my machine.

Anyway, there's something more I would like to see in Scale, but I'm not familiar with js, even if the code looks easy in scale.js..

I Use it with hot corners. Activated I can choose through opened windows, but when I click on an empty space, nothing happens. I have to click in the corner again to return to the desktop. And for example when there is no windows, you're in a sort of "blocked" situation if you don't think to click the corner again. Not very intuitive.

Is there a way to "unscale" when you click in an empty space, or on the desktop?

Thanks in advance.

**Comment by PierreMoustache** [comment]
const Applet = imports.ui.applet;
const Lang = imports.lang;
const Main = imports.ui.main;
const Gtk = imports.gi.Gtk;
const Settings = imports.ui.settings;

function MyApplet(metadata, orientation, panel_height, instance_id) {
    this._init(metadata, orientation, panel_height, instance_id);
}

MyApplet.prototype = {
    __proto__: Applet.IconApplet.prototype,

    _init: function(metadata, orientation, panel_height, instance_id) {
        Applet.IconApplet.prototype._init.call(this, orientation, panel_height, instance_id);

        try {            
            Gtk.IconTheme.get_default().append_search_path(metadata.path);
            this.set_applet_icon_symbolic_name("cinnamon-scale");
            this.set_applet_tooltip(_("Scale"));            
            this._hover_activates = false;            

            this.settings = new Settings.AppletSettings(this, metadata["uuid"], this.instance_id);

            this.settings.bindProperty(Settings.BindingDirection.IN,
                                       "activate-on-hover",
                                       "_hover_activates",
                                       function () {});

            this.actor.connect('enter-event', Lang.bind(this, this._onEntered));
        }
        catch (e) {
            global.logError(e);
        }
    },

    on_applet_clicked: function(event) {
        if (this._hover_activates)
            return;
        this.doAction();
    },

    _onEntered: function(event) {
        if (!this._hover_activates || global.settings.get_boolean("panel-edit-mode"))
            return;
        this.doAction();
    },

    doAction: function() {
        if (!Main.overview.animationInProgress)
            Main.overview.toggle();
    }
};

function main(metadata, orientation, panel_height, instance_id) {
    let myApplet = new MyApplet(metadata, orientation, panel_height, instance_id);
    return myApplet;
}

**Comment by harogaston** [comment]
Well scale is not exactly an applet...

If I am not mistaken:
it is implemented as part of cinnamon itself. There is an applet that acts as a short cut, but you won't be able to alter the behaviour of Scale by touching anything in that code you posted.

Nevertheless I think it is a good idea to implement.

**Comment by kevlogan90** [comment]
+1. I would like to have it so clicking on the background should either 1) go back to the previously focused window or 2) go to the desktop if no windows are open

**Comment by rik-shaw** [comment]
@clefebvre  This is an essential feature to change scale to have a way to get out of it.  Currently if scale is used as an applet in the panel, and *no* windows are open when it clicks, scale is activated but there is no way to "click out of it".  The only way out is to hit "ESC" which many new users will not find.

**Comment by mtwebster** [comment]
We should just not activate scale if there are no windows, shouldn’t we?

**Comment by rik-shaw** [comment]
@mtwebster well that is a good point: however there are other times where a user clicks to activate scale and then "wants to get out of it".  I think selecting an active window is logical for them to "get out" and make what they want active, but I think there would be cases where they don't want anything "active".... meaning that "show desktop" would be a good action if the user clicks in an empty area.  But I think either that or what you suggest of not allowing scale to activate without any open windows would both be acceptable.

To give insight, I have had many users get confused by the "no windows click scale" problem so some action would really make sense and help these users out.  As it stands I have removed the scale applet from the panel for safety from this problem: but I would like them to be able to use it since they at other times have 10 windows open and can't read the window list very well since it is too cluttered.  Anyway, thanks for the consideration and all the great work over the years!

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
