### ISSUE TITLE
Qt tray icons aren't displayed

### ISSUE THREAD

**Issue by theSeppi** [linuxmint/Cinnamon#3878]
To use a game pad for games without support for it, I'm using the software QJoyPad, which should display its icon in the system tray. However, there is just a blank square space in the tray, other tray icons wrap around it.

I suspect it got something to do with the fact that QJoyPad uses Qt, and Cinnamon's system tray doesn't work with it. On Ubuntu/Unity, there's a wrapper called sni-qt, which displays qt tray icons as Unity indicators, so it worked there, but not with Mint/Cinnamon

**Comment by GLolol** [comment]
Possibly related to #2846?

**Comment by dalcde** [comment]
Closing as duplicate
