### ISSUE TITLE
Window list moves right when trying to organize windows

### ISSUE THREAD

**Issue by zorbama** [linuxmint/Cinnamon#3880]
SETUP
Linux Mint 17.1 Cinnamon, 32-bit
Default windows list applet in use

REPRODUCE
1. Open several windows
2. Click and drag the leftmost window to the right

EXPECTED RESULT
The next window in the list should move left and allow the dragged window to be placed after it.

ACTUAL RESULT
All the windows listed after the dragged window move to the right. Only after dragging some more does the next window in the list move to the left, as seen in the attached image.

![2015 02 03-bug-lo-windowlist](https://cloud.githubusercontent.com/assets/6951677/6027206/4bffd20c-abe9-11e4-8d07-678e9608751d.png)

**Comment by arfett** [comment]
I find this bug rather aggrevating and have to hold the click much longer than I should have to to make sure my window is going where I expect it.

**Comment by dalcde** [comment]
Fixed in git master
