### ISSUE TITLE
Power Manager cause unintended hibernation on wake up

### ISSUE THREAD

**Issue by antoine9298** [linuxmint/Cinnamon#3881]
When you have multiple batterie (like in my HP Pavillon X2) and you have at least a empty one (like one at 73% and one at 1%), your laptop will at wake up shutdown or hibernate (depending wich you have choosen in the power settings).

this is a small bug but it's an *annoying* one… :pensive:

:thought_balloon: a immediate “fix” may be something like adding the option “do nothing at low power”

**Comment by Vahan86** [comment]
@antoine9298, is this still an issue for you in Cinnamon 3.0?

**Comment by Vahan86** [comment]
@JosephMcc, can we close the issue?

**Comment by antoine9298** [comment]
Well, I can’t test it anymore : I changed of computer, so, yes, I think we can close it

**Comment by Vahan86** [comment]
@antoine9298, thanks for reply. In this case can you please close the issue?

**Comment by antoine9298** [comment]
done
