### ISSUE TITLE
sound applet does not show clementine after using vlc

### ISSUE THREAD

**Issue by schokoladi** [linuxmint/Cinnamon#3882]
Linux Mint 17.1 Cinnamon 64-bit, Cinnamon 2.4 obviously :)
- Start Clementine and playpack information appears in the cinnamon sound applet
- Open Clementine and listen to something
- Open VLC and watch movie, both Clementine and VLC details now appear in the sound applet
- Closed VLC, no player details shown anymore in sound applet, Clementine still open though
- Close Clementine and start again via sound applet (launch player), Cinnamon starts but still no details in sound applet
Not tested with other Players but it seems like the problem is with the sound applet, Clementine and VLC work flawlessly

**Comment by anandrkris** [comment]
I saw a PR with sound applet enhancements. Not sure, if this is already handled by it...
https://github.com/linuxmint/Cinnamon/pull/3858

**Comment by mtwebster** [comment]
Implemented as of 05f65cf
