### ISSUE TITLE
Custom keyboard shortcut groups with window conditions

### ISSUE THREAD

**Issue by ipsod** [linuxmint/Cinnamon#3884]
In Linux Mint 17.1 KDE, it's possible to create custom keyboard shortcut groups and to specify the conditions under which that group's shortcuts should be used (ie: Active Window: _Vim_, Existing Window: "Calculator").  This feature (paired with xdotool) is a wonderful and elegant solution for GUI productivity scripting, and everyone should use it!

Without it, scripting for the GUI beyond basic launchers and such becomes a woefully complex operation.  That's the only thing keeping me from switching to Cinnamon, and I'd love to see it added.

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html
