### ISSUE TITLE
New Wireless Connection should be able to allow advanced login parameters

### ISSUE THREAD

**Issue by TrickyHarry** [linuxmint/Cinnamon#3891]
I am not sure when this changed but the current Cinnamon Network Manager does not support defining advanced connection parameters. Currently the advanced connection parameters are only available after a connection is made - when it nearly not needed.

This is a change of configuration, the Network Manager was not like this about 6 months ago.

I am a contractor and I my last customer requires me to define my UserID and Password to login to the Wireless connection. This is rear these days but it is still an option. The bad part is that my Android phone & Windows still allows me to define my additional security settings prior to the connection.

My existing connections, prior to this update still work - I am not sure how I would have dealt with this.

I need to specify the authentication type & userID / Password but I cannot set this prior to my connection in this version of Cinnamon Network Manager

![selection_333](https://cloud.githubusercontent.com/assets/1596448/6097447/eb447b72-afb5-11e4-9623-0a34cd8266bd.png)

[root@naipaulpc ~]# rpm -qa | grep -i network | grep -i Manager | sort
NetworkManager-0.9.9.0-46.git20131003.fc20.x86_64
network-manager-applet-0.9.9.0-10.git20140123.fc20.x86_64
NetworkManager-glib-0.9.9.0-46.git20131003.fc20.i686
NetworkManager-glib-0.9.9.0-46.git20131003.fc20.x86_64
NetworkManager-l2tp-0.9.8.7-1.fc20.x86_64
NetworkManager-openconnect-0.9.8.6-1.fc20.x86_64
NetworkManager-openvpn-0.9.9.0-0.1.git20140128.fc20.x86_64
NetworkManager-openvpn-gnome-0.9.9.0-0.1.git20140128.fc20.x86_64
NetworkManager-pptp-0.9.8.2-3.fc20.x86_64
NetworkManager-pptp-gnome-0.9.8.2-3.fc20.x86_64
NetworkManager-vpnc-0.9.8.2-3.fc20.x86_64
NetworkManager-vpnc-gnome-0.9.8.2-3.fc20.x86_64

**Comment by lestcape** [comment]
Instead of Network preferences, could you try Network connection? You can set your settings on that way?

**Comment by TrickyHarry** [comment]
Dear Cinnamon,

I have just tried looked at that method of connection and it does support the editing of connections that were
never made - something that I can verify on Wednesday.
  - Thanks for the assistance, it gives me home
  - Network Connections is available in the drop-down menu as well, rather than me going to look for it.

While that is the case - as a work-around, my original point is that the Applet has changed to remove that functionality
and it was there previously.
  - Its just a shame

Best Regards

Naipaul Ojar

 

May you have a blessed Day.
  ~~0~0~0~~


Date: Sun, 8 Feb 2015 19:27:29 -0800

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html
