### ISSUE TITLE
feature request: Vertical Panels

### ISSUE THREAD

**Issue by anacon** [linuxmint/Cinnamon#3893]
In general I like Cinnamon, but the inability to configure the panels vertically is a dealbreaker for me. I (and many others it seems) prefer to use the buggy implementation of vertical panels inherited from gnome2 by Mate, than be stuck with horizontal panels. In contrast, this is one of the things that Windows actually got right, their implementation of vertical panels has worked flawlessly ever since Windows 95.

**Comment by pixunil** [comment]
Duplicate of #629. Please close this thread and use #629 for further discussion.

**Comment by anacon** [comment]
Duplicate, please refer to #629
