### ISSUE TITLE
Changing the default icon for the file types

### ISSUE THREAD

**Issue by karakartala** [linuxmint/Cinnamon#3895]
Right now, changing the default icon for the file types is some troublesome. But this option add in theme settings, will be easier than right now.

Note: Sorry. My English is bad.

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html

**Comment by hopelessdecoy** [comment]
Where does someone go to use this feature?
