### ISSUE TITLE
Notifications do not respect notify-send -t settings

### ISSUE THREAD

**Issue by broomdodger** [linuxmint/cinnamon#3896]
I tried using the "-t" option to change how long notifications appear but nothing changes.

-t, --expire-time=TIME
Specifies the timeout in milliseconds at which to expire the notification.

**Comment by broomdodger** [comment]
The original post describing `notify-send -t` failing is using Mint 17.1 Cinnamon.

Yesterday I tried the same using Mint 17.1 xfce... and there it works.

**Comment by mtwebster** [comment]
in cinnamon settings, go to Notifications, check "Remove notifications after their timeout is reached"

**Comment by broomdodger** [comment]
Checked or un-checked... has **NO** effect on `notify-send -t`

That checkbox **ONLY** changes how **many** items are displayed in the **tray** notification area. It has no effect on the **duration** of notification ***bubble***.

Note: both Mint 17.1
The following **displays** the notification ***bubble*** correctly for both Cinnamon and xfce.
It fails to keep the notification ***bubble*** displayed for 10 seconds in Cinnamon but works in xfce.

The effect of the `-t 10000` is to keep the notification ***bubble*** displayed for 10 seconds, rather than the default... about 5 seconds.
```
n="/usr/bin/notify-send"
i="-i /home/tech/Pictures/icons/preferences-system-time-symbolic.svg"

test="Bzz Bzz Bzz"
 * * * * * DISPLAY=:0 ${n} ${i} -t 10000 "${test}"
```

**Comment by broomdodger** [comment]
More info about `notify-send`

notification-spec-0.9.txt

**Expiration Timeout**

The timeout time in milliseconds since the display of the notification at which the notification should automatically close.

If -1, the notification's expiration time is dependent on the notification server's settings, and may vary for the type of notification.

If 0, the notification never expires.

**Comment by mtwebster** [comment]
Do these other DE's have a tray-type applet/panel container to catch missed notifications?  This isn't really cut and dry for us because of the tray, regardless of what the spec says.  I'm curious about their behavior in these cases.

**Comment by broomdodger** [comment]
@mtwebster
> Do these other DE's have a tray-type applet/panel container to catch missed notifications?

Neither XFCE nor MATE have a tray-type applet/panel container to catch missed notifications.

Both XFCE and MATE **display** a notification **bubble** for the time specified by the `-t` option.

I now understand how it works in cinnamon:
The `-t` option specifies how long a notification will remain in the notification **tray**.

I would like an option to specify how long the notification **bubble** will display in the upper right of the screen.

**Comment by anandrkris** [comment]
Happened to see this - http://blogs.gnome.org/mclasen/2015/02/23/gnome-3-16-sightings/
>>The message tray is gone, old notifications can now be found in the calendar popup.

**Comment by ion201** [comment]
This is a "won't fix" bug in libnotify: https://bugs.launchpad.net/ubuntu/+source/notify-osd/+bug/390508. The documentation here has been changed to reflect that: http://anonscm.debian.org/viewvc/pkg-gnome/desktop/unstable/libnotify/debian/notify-send.1?r1=44098&r2=44097&pathrev=44098

**Comment by CottonEaster** [comment]
It would be good were it possible to extend the default expiration, even if upstream makes this hard (and even if - as on my system - notifications that I send from scripts using `notify-send -t` do respect the time assigned).

**Comment by CottonEaster** [comment]
Can I be right in thinking that _Mint allows the user no control over how long the notification pop-up lasts_? That would be unfortunate and, when combined with several unadjustable features of / bugs with various parts of Cinnamon, would make for a bad user experience.

**Comment by C0rn3j** [comment]
This issue dates back to 2009, nice.

My use case was a notification message that does not go away without user interaction, which is what I accomplished by the flag '-u critical' in the end without using an insanely high timeout.

**Comment by groovenectar** [comment]
Really wish there is a way to control the timeout. It's too quick for some cases.

I found a section in dconf editor:

`/org/cinnamon/desktop/notifications/timeout`

Some of the settings in this area take (the position, for example), but not the timeout.

I tried changing it from 1,800 to 50,000, and it still went away too quickly

**Comment by cropinghigh** [comment]
Same issue on Linux Mint 19.3 Cinnamon 4.4.8.
Works fine some time, then starts ignoring timeout, and to return it to working state, need to restart cinnamon, then again works some time and ignoring timeout.

**Comment by bguerout** [comment]
The only solution i found was to update `/usr/share/cinnamon/js/ui/messageTray.js` as described here : https://askubuntu.com/questions/807999/cinnamon-notifications-settings
