### ISSUE TITLE
Syncronize scaling-factor defined in org.cinnamon.desktop.interface and org.gnome.desktop.interface

### ISSUE THREAD

**Issue by drewrobson** [linuxmint/Cinnamon#3899]
I connected a new HiDPI monitor (Dell P2715Q, 27" 4K) but Cinnamon did not automatically enable 200% scaling as I would have expected (should I file an issue?). I fixed this manually by selecting "Double (Hi-DPI)" in the "User interface scaling" dropdown menu.

My [text editor](http://atom.io) continued to use 100% scaling. It turns out it was using org.gnome.desktop.interface scaling-factor, which still had a value of 0.

Sure enough, the "User interface scaling" Combo Box only sets org.cinnamon.desktop.interface.

```
combo = GSettingsUIntComboBox(_("User interface scaling:"), "org.cinnamon.desktop.interface", "scaling-factor", ui_scales)
```

Perhaps this dropdown should also set the scaling-factor in org.gnome.desktop.interface since some software uses that value. I can also file an issue with the editor if this should be considered a bug, but I think if there's going to be a value in org.gnome.desktop.interface it might as well be right.

**Comment by mtwebster** [comment]
https://github.com/atom/electron/issues/1150#issuecomment-105047544
