### ISSUE TITLE
Sound Applet - Kodi Support

### ISSUE THREAD

**Issue by tedr56** [linuxmint/Cinnamon#3901]
The former Xbmc have been renamed to Kodi and is not yet supported by the sound@cinnamon.org applet.

**Comment by pixunil** [comment]
There should be no "not supported", as the sound applet uses DBus mpris to control players.
Please check if kodi has got support for DBus mpris.
(maybe you need to activate a plugin like on totem or activate a setting)

**Comment by mtwebster** [comment]
A new version of Cinnamon with that change hasn't been released yet - we still rely on a compatibility list in stable.

**Comment by mtwebster** [comment]
My mistake - the applet should detect the mpris interface if it has one, it just currently won't show up in the player as a launch option.  So, you should be able to control the player once it's launched, but not launch it directly from the applet.

**Comment by dalcde** [comment]
There is nothing specific to xbmc in the sound applet code. It will show up as a launch option after the first time it is run. A simple grep shows that the word "xbmc" doesn't appear in the sound applet code/
