### ISSUE TITLE
Feature missing E4X, feature request gxml support...

### ISSUE THREAD

**Issue by lestcape** [linuxmint/Cinnamon#3905]
As is known, mozilla decided remove the NATIVE support for E4X: https://developer.mozilla.org/en-US/docs/Archive/Web/E4X and was moved the code to DOM interfaces, that is out of the cjs scope.

This involved  the lost of the possibility to parse NATIVE an XML over cjs. There are only one current implementation as I know, that support GObject instrocpection. That is Gxml library: https://github.com/GNOME/gxml That is a wrapper of libxml2 and is the recomendation of gnome shell devs as a replace of the obsolete E4X.

I really don't know how is the best way to recover the functionalities, if as a dependency of the existing packages on the all linux distros (currently not exist), or if as a new packages for cinnamon, rename the Gxml library to Cxml or what can be do?

On this thread, aparently will be implemented an alternative new one library by mozilla and google:
https://mail.gnome.org/archives/desktop-devel-list/2013-April/msg00294.html

But more recently aparently the plan go down:
https://mail.gnome.org/archives/gnome-shell-list/2013-December/msg00032.html

What is the Cinnamon plan?

This fact is affecting  this applet:
https://github.com/jonbrett/cinnamon-feeds-applet/issues/48

And also is important of have a library to parse one of the most important files of internet (the xml).

Thanks for any suggestion.

**Comment by lestcape** [comment]
As a quick fix, could be added a global function to receive the xml string and send the string in a json format.

**Comment by dalcde** [comment]
Cinnamon has no plan. If gxml works through gi, then use it. We don't have to fork it. If gxml doesn't work, go bug the GNOME guys - they are maintaining it. Alternatively, packaging something like this: https://code.google.com/p/marknote/ with your applet.

**Comment by lestcape** [comment]
Is not my applet, but anyway i try to help. I need to swap to python and parse the xml to json format, and then send it over dbus to cjs... A lot of unnecessary things... and if like you recommended some one try to parse a general xml inside cinnamon code using a third party api, i don't know, but at less i estimated a big performance reduced over cinnamon.
https://github.com/lestcape/cinnamon-feeds-applet/blob/master/xmltojson.py

**Comment by dalcde** [comment]
My point is that it is outside the scope of Cinnamon/cjs. cjs simply
glues together existing libraries, not create new ones. The other
suggestions are made with my random-passer-by hat

**Comment by lestcape** [comment]
Thanks :) just is a shame and i think that add a function like this one:
https://github.com/lestcape/cinnamon-feeds-applet/blob/master/xmltojson.py#L409
 but on C possible on global class is not hard, and help a lot.
