### ISSUE TITLE
Locking window position in Scale / Expo

### ISSUE THREAD

**Issue by quicksi1vr** [linuxmint/Cinnamon#3906]
It would be nice to have the option to lock the window positions in Scale - for example, I have a Firefox, terminal and Nemo window in that order, with Firefox in focus. Then when I bring Nemo to focus, the order if the window changes and Nemo moves to the front. I know it kinda mimics the alt-tab behaviour from Unity / MS Windows, but I'm so used to Gnome shell, where the windows in Scale / Overview hold their position. Thanks

**Comment by tp0** [comment]
+1. This has always annoyed me in Unity/Compiz Scale too. It causes visual distraction as the position of the windows cycle all the time. It would be sufficient to me if the positions (and preferably sizes too*) of the windows remained the same for as long as user does not open or bring new windows to that workspace.

* https://github.com/linuxmint/Cinnamon/issues/3336

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html
