### ISSUE TITLE
Crash with new clutter.

### ISSUE THREAD

**Issue by vovka-korovka** [linuxmint/Cinnamon#3909]
After upgrading to Gnome 3.15 libraries Cinnamon crashes with follow assertion in log

Clutter:ERROR:x11/clutter-stage-x11.c:1276:clutter_x11_get_stage_window: assertion failed: (CLUTTER_IS_STAGE_X11 (impl))

**Comment by vovka-korovka** [comment]
Follow export helped
export CLUTTER_BACKEND=x11

**Comment by leigh123linux** [comment]
I got the same with f22+

http://pkgs.fedoraproject.org/cgit/cinnamon-session.git/tree/set_clutter_env.patch?id=843913bcf04ece103b831fef53e63e42c9bc8c7b

**Comment by two-dogs** [comment]
seeing same with Distro: openSUSE 20150405 (Tumbleweed) ,

**Comment by mtwebster** [comment]
https://github.com/linuxmint/cinnamon-session/commit/70893dc7a32fb983f44c8e9be07ffe65baf6bbd3

**Comment by mhsabbagh** [comment]
Hello.

I've the same problem here on openSUSE Tumbleweed with Gnome 3.16.
"export CLUTTER_BACKEND=x11" Did the trick for me, but for some reason it's not working by default from the code.

**Comment by daira** [comment]
The ``CLUTTER_BACKEND`` workaround seems to not quite be an adequate fix for this bug, because I get a warning about software rendering potentially causing high CPU usage (that I didn't get before the GNOME "upgrade").

**Comment by daira** [comment]
(I'm on LMDE, if that is relevant.)

**Comment by leigh123linux** [comment]
@daira 

software rendering is an indication that your 3D graphics driver isn't working.

**Comment by two-dogs** [comment]
i am currently using cinn-2.6 from opensuse-cinn-factory-tumbleweed, i no longer need the tweak, works fine, kudos to the devs-cinn and opensuse packagers

**Comment by mtwebster** [comment]
Moved this patch to the cinnamon binary instead of -session (this way it is unimportant what environment you start cinnamon in)
