### ISSUE TITLE
Freeze when changing Text Scale Factor

### ISSUE THREAD

**Issue by coolghost** [linuxmint/Cinnamon#3911]
In the fonts entry of system settings, when i would click the plus or minus buttons to change text scale factor, cinnamon would freeze and it would take up 100% of the cpu.

**Comment by Vahan86** [comment]
Couldn't reproduce the issue in Cinnamon 3.0. It's working fine for me.

@coolghost, is this still an issue for you in Cinnamon 3.0?

**Comment by Vahan86** [comment]
@JosephMcc, can we close the issue?
