### ISSUE TITLE
Reset button in font settings

### ISSUE THREAD

**Issue by coolghost** [linuxmint/Cinnamon#3912]
After adjusting the various font setting in system settings, i couldnt remember what the original font settings were and it would be nice to have a reset button that would do this.

**Comment by anandrkris** [comment]
:+1: I was struggling the other day to find out original settings after I messed it up...

**Comment by harogaston** [comment]
+1 Think this could prove handy.

**Comment by dalcde** [comment]
I'd make it a "reset button in all setttings."

**Comment by Vahan86** [comment]
+1

**Comment by Bl4ckb0ne** [comment]
+1

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html
