### ISSUE TITLE
Desktop wallpaper lost after cinnamon crash

### ISSUE THREAD

**Issue by coolghost** [linuxmint/Cinnamon#3913]
After cinnamon crashed and showed a dialog to restart, it restarted successfully, but my desktop wallpaper was reset back to the default linux mint wallpaper.

**Comment by kehugter** [comment]
Has happened to me a couple of times too.

**Comment by philipzae** [comment]
I noticed that sometimes it would reset the background and other times it wouldnt.

**Comment by rkingsbury** [comment]
I've experienced this several times following a cinnamon crash.

Mint 17.1 x64

**Comment by JosephMcc** [comment]
Just trying to keep all the related issue together: https://github.com/linuxmint/Cinnamon/issues/3953
