### ISSUE TITLE
package requirements not met

### ISSUE THREAD

**Issue by luca-vercelli** [linuxmint/Cinnamon#3914]
I cannot compile the source code.
configure says:
Package requirements (...) were not met,
Requested 'cjs-internals-1.0 >= 2.3.1' but version of cjs-internals-1.0 is 2.2.2

now, where can I find cjs-internals-1.0 >= 2.3.1? Maybe I just installed the wrong dev package. Using Linux Mint 17 Qiana.

**Comment by pixunil** [comment]
How do you compile it? You should use `dpkg-buildpackage` and please keep in mind that you should build [muffin](https://github.com/linuxmint/muffin) first (also with `dpkg-buildpackage`).
It will generate a couple of .deb files in the directory one level up (`..`) which you can install via `sudo dpkg -i *.deb`.

**Comment by luca-vercelli** [comment]
I have tried with dpkg-buildpackage, too. This is the output:

    $ dpkg-buildpackage 
    dpkg-buildpackage: Pacchetto sorgente cinnamon
    dpkg-buildpackage: Versione sorgente 2.4.6
    dpkg-buildpackage: Distribuzione sorgente rebecca
    dpkg-buildpackage: Sorgente modificata da Clement Lefebvre <root@linuxmint.com>
    dpkg-buildpackage: Architettura host amd64
    dpkg-source --before-build Cinnamon
    dpkg-checkbuilddeps: Unmet build dependencies: libcjs-dev (>= 2.3.1)
    dpkg-buildpackage: Avviso: build dependencies/conflicts unsatisfied; aborting
    dpkg-buildpackage: Avviso: (Utilizzare l'opzione -d per sovrascrivere).

and

    $ dpkg -l|grep libcjs-dev
    ii  libcjs-dev                                  2.2.2                                                    amd64        Mozilla-based javascript bindings for the Cinnamon platform

I have also tried with dpkg-buildpackage -d, however the compilation fails for some error in C source.

**Comment by dalcde** [comment]
You need to compile cjs first.

**Comment by luca-vercelli** [comment]
thank you
