### ISSUE TITLE
Strange hotkeys assigned to Esc + modifiers

### ISSUE THREAD

**Issue by theSeppi** [linuxmint/Cinnamon#3915]
There seem to sit some commands on shortcuts like Ctrl+Alt+Esc and Alt+Shift+Esc, which draw black borders around windows or the complete desktop as long as they're being held down.

What are these supposed to do? They aren't listed in the Keyboard settings. You can assign those combinations to something else (I want to assign one to xkill), but they are swallowed and instead produce these black margins.

Is there any reason behind those strange black borders and the fact that those shortcuts can't be used for something else?

Unfortunately I can't make a screenshot while holding down those keys, but I assume it to be reproducable.

***

Linux Mint 17.1 Cinnamon Edition 
Cinnamon 2.4.6 
Muffin 2.4.3

**Comment by mtwebster** [comment]
They're vestigial keybindings in muffin (left over from metacity I imagine) - some sort of alt-tab-like switcher stuff.  I keep forgetting to remove or otherwise disable them.

**Comment by theSeppi** [comment]
I think they are here: https://github.com/linuxmint/muffin/blob/master/src/core/keybindings.c:2409

**Comment by mtwebster** [comment]
Ah yes - you should be able to use dconf-editor and clear out:

`org.cinnamon.desktop.keybindings.wm cycle-panels` and `cycle-windows` to free up those keys.

**Comment by theSeppi** [comment]
Tanks a lot. Now I was able to reassign these shortcuts.

**Comment by anandrkris** [comment]
Tagging related issues....
https://github.com/linuxmint/Cinnamon/issues/1530
https://github.com/linuxmint/Cinnamon/issues/1638
https://github.com/linuxmint/Cinnamon/issues/2539

**Comment by dalcde** [comment]
Removed in git master
