### ISSUE TITLE
Windows area locked

### ISSUE THREAD

**Issue by kehugter** [linuxmint/Cinnamon#3916]
Since about a week, the area where the windows are displayed get locked a few times a day, as if it had a layer over it preventing the clicks to pass trough. The panel area isn't affected.

A common trigger is to change windows by clicking them on the panel. Sometimes one will "jump" and lock the upper area. I can't reproduce the issue at will though.

To get it back to normal, I run the scale mode (ctrl + alt + down).

---

Mint 17.1
running nightlies

**Comment by dalcde** [comment]
Should be fixed by https://github.com/linuxmint/Cinnamon/commit/3855777086e569d21fc666a03bc8b2e18f200267. If not, it is still documented here: https://github.com/linuxmint/Cinnamon/issues/2946. So closing
