### ISSUE TITLE
Application exit breaks the Cinnamon Desktop Environment 

### ISSUE THREAD

**Issue by LipkeGu** [linuxmint/Cinnamon#3917]
Hello, We got December 2014, an Issue where Players reported that our Project breaks the Desktop environment. We cant find any infos and ideas why our Application breaks the environment.

In this moment we doesnt know if its a bug related to Our Project or a bug of Cinnamon
I would like to ask if any of the Developers here could take a look at Our issue on OpenRA

Thanks in advance

https://github.com/OpenRA/OpenRA/issues/7234

**Comment by mtwebster** [comment]
Hi, any chance someone can run `cinnamon --replace` from a terminal, then try to reproduce the crash?  The output may shed some light on this.  (if not I'll try installing the game when I have a chance)

**Comment by leigh123linux** [comment]
OpenRA closed the issue as it wasn't reproducible
