### ISSUE TITLE
Cinnamon ignores global dark theme

### ISSUE THREAD

**Issue by testman42** [linuxmint/Cinnamon#3919]
I am on Fedora 21 with Cinnamon installed.
It was working as expected until suddenly one day Cinnamon decided that it will ignore global dark theme setting. (~/.config/gtk-3.0/settings.ini has "gtk-application-prefer-dark-theme=1" )
Here is exampe of how Nemo used to look like and how it looks like now: http://imgur.com/rYmS3xx

I was told on IRC that this issue is being worked on, but I couldn't find any existing bug reports or in fact any description of this issue at all, so I am making one here.

**Comment by vovka-korovka** [comment]
Works for me. Did you really restart nemo? It still is running in background when you close window so you need to restart session or kill nemo and start it again.

**Comment by mtwebster** [comment]
It was fixed here: https://github.com/linuxmint/muffin/commit/fb27514d6d2fce28ce3f8524a4f1154f981f7882

As long as you have muffin > 2.4.3 it should work now.  You need to be sure your GTK theme supports it as well though.

**Comment by leigh123linux** [comment]
Works fine here on Fedora!

**Comment by testman42** [comment]
OK, I have muffin 2.4.4 installed and before now I haven't been playing with themes around at all, I was happy with the way default theme looked. If I am not mistaken, default theme for Fedora 21 is dark Adwaita theme.
I managed to get UI looking dark again by going to System Settings -> Themes and changing "Controls" setting from Zukitwo to Adwaita and then restarting Cinnamon.
Don't ask me why it was set to Zukitwo, I haven't touched the thing at all.
