### ISSUE TITLE
notify-send multiple lines fail to display

### ISSUE THREAD

**Issue by broomdodger** [linuxmint/Cinnamon#3920]
It is possible to display multiple lines with `notify-send`.
BUT
There is a bug in the cinnamon version.
All examples work **CORRECTLY** in xfce.
In cinnamon, failure is both summary and body line length dependent.
48 characters or less in the body
AND/OR
6 characters or less in the summary
Examples:
```
notify-send -i error "summary" \
"summary=7 body=48 --FAIL--\
\r123456789012345678901234567890123456789012345678\
\r123456789012345678901234567890123456789012345678"

notify-send -i info "summary" \
"summary=7 body=49 --OK--\
\r1234567890123456789012345678901234567890123456789\
\r1234567890123456789012345678901234567890123456789"

notify-send -i error "summar" \
"summary=6 body=49 --FAIL--\
\r1234567890123456789012345678901234567890123456789\
\r1234567890123456789012345678901234567890123456789"

notify-send -i info "summar" \
"summary=6 body=50 --OK--\
\r12345678901234567890123456789012345678901234567890\
\r1234567890123456789012345678901234567890123456789"
```

**Comment by pixunil** [comment]
Works correctly for me on nightly builds. (commit 23befb8d7cbda36f5f1425edc1dbb88155fc1115)

**Comment by dalcde** [comment]
I don't see anything wrong with the message displayed. Closing unless you specify exactly how it fails (you did not) and we can reproduce the failure.

**Comment by broomdodger** [comment]
Currently I only have Linux Mint 17.1 xfce installed which does not suffer the same problem.

I will install LMDE2 Cinnamon and give you more info.
LMDE2 Cinnamon should have an updated `notify-send` so maybe the problem has been fixed.

**Comment by dalcde** [comment]
What was the problem you experienced? You only mentioned it failed, without saying how. Does it fail to display at all? Or some parts are truncated?

**Comment by broomdodger** [comment]
As I recall some parts are truncated.
In the next few days I will install Cinnamon on a test machine.
Would you prefer I install LM 17.1 where I noticed the problem or shall I go with LMDE2 and see if it works correctly?

**Comment by dalcde** [comment]
Either would be fine

**Comment by broomdodger** [comment]
These 4 tests have been tried with both:

+ Linux Mint 17.1 Cinnamon
+ LMDE2 Cinnamon

And fail in the same way on both.
The failure is dependent on BOTH the summary length and body length.

Copy these `notify-send` tests to a file
Name the file: `notify.sh`

Open a terminal
Change permissions: `chmod u+x notify.sh`
Execute: `./notify.sh`

Click on each notification to dismiss and proceed to the next.

```
# .......1.........2.........3.........4.........5.........6....
# this works correctly
# it will produce the notification
# with the summary title
# a blank line
# then the 3 body lines
notify-send -i info "summary" \
-u critical \
"summary=7 body=49 --OK--\
\r1234567890123456789012345678901234567890123456789\
\r1234567890123456789012345678901234567890123456789"


# this works correctly
# it will produce the notification
# with the summary title
# a blank line
# then the 3 body lines
notify-send -i info "summar" \
-u critical \
"summary=6 body=50 --OK--\
\r12345678901234567890123456789012345678901234567890\
\r1234567890123456789012345678901234567890123456789"


# this FAILS, displays only 1 line
# with the summary title
# and text ONLY up to the --FAIL--
notify-send -i error "summary" \
-u critical \
"summary=7 body=48 --FAIL--\
\r123456789012345678901234567890123456789012345678\
\r123456789012345678901234567890123456789012345678"


# this FAILS, displays only 1 line
# with the summary title
# and text ONLY up to the --FAIL--
notify-send -i error "summar" \
-u critical \
"summary=6 body=49 --FAIL--\
\r1234567890123456789012345678901234567890123456789\
\r1234567890123456789012345678901234567890123456789"

# .......1.........2.........3.........4.........5.........6....
```

**Comment by dalcde** [comment]
Not reproduced. What theme are you using? Also is there any reason why they have to be saved into a file instead of running directly from the terminal?

**Comment by broomdodger** [comment]
I installed LMDE2 Cinnamon with NO changes to Themes: Mint-X

Sure you can run each anyway you want.
My original intent was to use the `notify-send` in a `crontab`.
That `crontab` and script work **great**.
In the process of creating them, I ran into these anomalies.

Attached are 4 screenshots:
+ Themes Setting
+ Notification Setting
+ **good** notification dialog
+ **bad** notification dialog

![theme](https://cloud.githubusercontent.com/assets/2816723/7643548/3d40f80e-fa4f-11e4-8c5f-f863cdc3a10b.png)
![notifications](https://cloud.githubusercontent.com/assets/2816723/7643545/3cbe21b8-fa4f-11e4-8b90-54391dc9a257.png)

The **bad** notification SHOULD look like the **good** one.
But as you can see it is **truncated**.
The **only** difference is the length of the body text.

![notify-good](https://cloud.githubusercontent.com/assets/2816723/7643547/3cd00946-fa4f-11e4-986a-4eeef9e666a8.png)
![notify-bad](https://cloud.githubusercontent.com/assets/2816723/7643546/3ccaf988-fa4f-11e4-907f-5985e0a7f59a.png)

**Comment by dalcde** [comment]
Reproduced on 2.4.8 but not on git master. So I calll that fixed.
