### ISSUE TITLE
Wrong selection of the panel id

### ISSUE THREAD

**Issue by lestcape** [linuxmint/Cinnamon#3922]
I use only one bottom panel.

This is the gsettings output:

lestcape@lestcape:~$ gsettings get org.cinnamon panels-resizable
['1:false', '-1:true', '2:false']
lestcape@lestcape:~$ gsettings get org.cinnamon panel-edit-mode
false
lestcape@lestcape:~$ gsettings get org.cinnamon panels-height
['1:25', '-1:32', '2:25']

here i modify on cinnamon-settings the panel height (one panel) and then I repeat again the command, to see the id that changed:

lestcape@lestcape:~$ gsettings get org.cinnamon panels-height
['1:25', '-1:42', '2:25']

To see what happend on cjs, I insert this line:

´´´
log("PANEL_HEIGHT_KEY " + panelHeight + " PANEL_RESIZABLE_KEY " + this._getProperty(PANEL_RESIZABLE_KEY, "b") + " PANEL_SCALE_TEXT_ICONS_KEY " + this._getProperty(PANEL_SCALE_TEXT_ICONS_KEY, "b") + " panelId " +this.panelId);
´´´

before this line https://github.com/linuxmint/Cinnamon/blob/master/js/ui/panel.js#L1644

This is the output:
Cjs-Message: JS LOG: PANEL_HEIGHT_KEY 25 PANEL_RESIZABLE_KEY false PANEL_SCALE_TEXT_ICONS_KEY false panelId 1
Cjs-Message: JS LOG: PANEL_HEIGHT_KEY 25 PANEL_RESIZABLE_KEY false PANEL_SCALE_TEXT_ICONS_KEY false panelId 1
Cjs-Message: JS LOG: PANEL_HEIGHT_KEY 25 PANEL_RESIZABLE_KEY false PANEL_SCALE_TEXT_ICONS_KEY false panelId 1

So cinnamon-settings modify the panel id: -1 and my panel have the id 1 on cjs.

**Comment by lestcape** [comment]
I don't know what mean panel id=-1 i add another panel and apparently this resolve the problem, and panel id = -1 is not used... I think that will be useful make a parse of gsettings value always before save the values, to fix any problem, that could be caused, but also see why this happen, to prevent futures problems.

**Comment by dalcde** [comment]
I think the problem lies in cinnamon-settings, not js

**Comment by lestcape** [comment]
@dalcde i think the same...

See, I like how this is working and i consider this an excellent enhancement. I will recommend: 

1- Does not storage on gsettings of true or false for bottom and top panel, instead use "bottom", "top"... This could be used to provide on the future also "left" and "right" panels without create again incompatibilities. 
2- Not thinking on only one directional panel (allow double, triple panels on code if some one want to do that on their extensions).
3- Allow names for panels, to be more easy to user identify a panel, like is currently do on expo.
4- Allow delete panels on cinnamon-settings, panel module and also show the current panel name.

**Comment by mtwebster** [comment]
2 - All I can think of are Internet explorer search bars stacked on top of one another.  I'm not sure I like the idea.  Also, with an extension, couldn't they accomplish it regardless?
3 - I think the only problems here are that a) the panel you're configuring isn't readily identifiable in anything but the default theme - *this will be fixed* - and b) the dbus connection between the panel configuration page and Cinnamon isn't fault-tolerant right now - it never tries to reconnect if something goes wrong, or you restart Cinnamon - *again, this will be fixed.*

**Comment by lestcape** [comment]
2- I don't say that a thing like that will be implemented on cinnamon, i also dislike the this idea, but same as you, I'm thinking on several programs that allow multi panels... And is easy take care on code to not depend of only one panel and make this the more general as possible.
3- I don't see this like a problem(also not any of this points), is just as an enhanced. If panel have a name, could be use latter to add applet to "panel name", thats is really intuitive if on panel on the edit mode, has a name to be identify.

**Comment by lestcape** [comment]
If i'm not on gnome shell, is because Cinnamon panels are several times more flexible than the gnome shell equivalent. My comments is on the direction of be the most flexible as possible and try to prevent new upcoming changes to not create incompatibilities more than one time if can be do at one...

Like i say the most important thing for me and the reason of I used cinnamon is the panels, so thanks for this great improvement. Without this, also are well for me, now are brilliant. Thanks for the things that are doing on the panels.

**Comment by lestcape** [comment]
@mtwebster sorry, for write this here (it's just for report)... I delete my .local folder (because I'm stupid), don't ask me, but then, was a good moment to test cinnamon with the default config.

First thing (i don't see any similar report):
I see that the cinnamon menu is searching the apps slowly. Do you note the same?

Second thing (there are some of report with the same):
I also see that cinnamon is not reacting without an apparent reason... I started the session and only used firefox, and i lost my internet connection. I try to restart the wireless network, but cinnamon not display any popup menu and not react at all, i need to restart my computer instead.
