### ISSUE TITLE
Background Pictures recursive

### ISSUE THREAD

**Issue by FlowXP** [linuxmint/Cinnamon#3923]
Hi,
I found a bug :
In All Settings -> Backgrounds, when adding a new folder it does not search for pictures recursively.
If the selected folder contains another folder with pictures, it won't show up any pictures at all.

Linux Mint 17.1 32 bit
Cinnamon 2.4.5

**Comment by FlowXP** [comment]
why is nobody answering ?
is anybody there ?

**Comment by JosephMcc** [comment]
Nope, nobody here ;)

All joking aside, it isn't a bug. It's that way intentionally. With recursive search it's way too easy to get into situation where you are trying to generate hundreds or even thousands of thumbnails in the settings ui.

**Comment by FlowXP** [comment]
tanks for the response :)
I now understand the reason, but shouldn't be a warning somewhere in there ??

**Comment by Acidburn0zzz** [comment]
Me too but, i search and thatsp right. But i si stupide i have look at that on same time i'm eating. Ans speaking with m'y girl and m'y moms, and i forger whats mâkes.

**Comment by sevenskull** [comment]
With the new slideshow option, i agree it's a must feature, because put every organized picture in a single folder is too much disorganization and trouble.

**Comment by damodaranudas** [comment]
I'm agree and there's not solution yet, I had to copy all my folders of pictures to a single messy folder

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html

**Comment by FlowXP** [comment]
> Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)
> 
> For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html

still not implemented yet :(

**Comment by ManIVIctorious** [comment]
What about a configurable maximum depth option? This would allow for recursive searches and prevent a infinite loop.

**Comment by FlowXP** [comment]
level 2 or even 3 would be awesome !

**Comment by FlowXP** [comment]
still nada :((((
