### ISSUE TITLE
Cinnamon menu doesn't display applications and can't access its settings 

### ISSUE THREAD

**Issue by tothpsk** [linuxmint/Cinnamon#3925]
1. Linux Mint 17.1 Cinnamon 64 bit; Cinnamon version 2.4.6, Linux core 3.16.025-generic
2. I was working in menu editor and tried to move a shortcut of applications from one cathegory to the next. After doing so, I closed the menu editor and mintmenu applet settings. After a while I tried to access the mint editor again, but I couldnt. When I pushed the button to open the mintmenu editor, it wasnt opening.
![obrazovka z 2015-02-23 09 32 02](https://cloud.githubusercontent.com/assets/11166910/6338525/cf1bc378-bbaf-11e4-981d-477c1ba1b568.png)

3. After rebooting the computer when I opened the mintmenu, all the applications, all the shortcuts disappeared (please see attachment). Also restarting Cinnamon and resetting its setting didnt help. Also all shortcuts which I had in applet "Window list with app groupig" disappeared.
4. I expected that the menu editor will work and after rebooting the computer everything will work as before.
5. This is the first time the problem with mintmenu appeared. But now after rebooting and restarting the problem with Cinnamon menu persists.

**Comment by mtwebster** [comment]
Hi,

If you can't open the menu editor (via the configuration page) you can try to run it from a terminal:

cinnamon-menu-editor

If that doesn't work, as a last resort, go into ~/.config/menus and delete or rename `cinnamon-applications.menu` - this should at least return you to your original menu layout, and restore function.

**Comment by tothpsk** [comment]
Thank you very much for your answer. The second solution helped :)

**Comment by Vahan86** [comment]
@tothpsk, is this still an issue for you in Cinnamon 3.0?

**Comment by tothpsk** [comment]
Hi, so far I havent experienced any problems with mintmenu. To be honest I try to edit the shortcuts as little as possible... But after a new install of Linux Mint 18 and playing with the menu the problem wasnt there.

**Comment by Vahan86** [comment]
@tothpsk, thanks a lot for reply. In this case can you please close this issue?

**Comment by tothpsk** [comment]
OK, issue closed. Many thanks
