### ISSUE TITLE
Applet icons not scaled properly

### ISSUE THREAD

**Issue by zagortenay333** [linuxmint/Cinnamon#3926]
I noticed that after an update to cinna 2.4.6 the applet icons aren't scaled properly. In my themes they should be 16px but appear smaller. They can't be scaled from within the cinnamon.css either, only from within the panel settings.
![screenshot from 2015-02-24 12 03 44](https://cloud.githubusercontent.com/assets/11144630/6348086/56a46d96-bc1d-11e4-9c02-5bb5c0419f75.png)
This is how they should look
![screenshot from 2015-02-24 12 07 15](https://cloud.githubusercontent.com/assets/11144630/6348139/bbdd7252-bc1d-11e4-8908-6a1a02be31fe.png)

Also, when increasing the panel from within the panel settings, the battery icon doesn't change at all.
![screenshot from 2015-02-24 12 04 13](https://cloud.githubusercontent.com/assets/11144630/6348107/6e9002ee-bc1d-11e4-9332-a90b1011c795.png)

**Comment by mtwebster** [comment]
What distro is this on?  The panel improvements we just merged had a bug that caused this (and has since been fixed) but this shouldn't be in a release yet.

**Comment by zagortenay333** [comment]
It's mint 17.1

**Comment by mtwebster** [comment]
Probably this: https://github.com/linuxmint/Cinnamon/commit/2cfffbcf6d496d455a7b1fd59504d0030222432b

I'll see about fixing it...

**Comment by zagortenay333** [comment]
That was quick! Thanks.

**Comment by mtwebster** [comment]
Pushed to 2.4 maintenance branch also, hopefully we'll get an update out

**Comment by zagortenay333** [comment]
Nice.

**Comment by lestcape** [comment]
That was fast... +1
