### ISSUE TITLE
Cinnamon and high resolution screen

### ISSUE THREAD

**Issue by DimitriyPS** [linuxmint/Cinnamon#3929]
I apologize for my English.

I use Linux Mint Cinnamon 17.1 laptop screen 13.4 inches diagonal and a resolution of 3200*1800. I chose this distro for supporting high-resolution screens. In places, minor bugs, but In General, all very good. However, 2 problems I've encountered is totally unacceptable.

1. Programme picture viewer, when viewed in the mode "1:1", increase the image on the screen 2 times. Just when viewing an image, it is not significant. But this is not acceptable when working (processing) photos.

2. A program that makes the screenshots. This is the reverse problem. It makes screenshots in 2 times less than the screen resolution (1600*900).

These problems are greatly hampered in their daily work. I beg to correct these errors as soon as possible. If possible until the next release.

**Comment by DimitriyPS** [comment]
Good afternoon.

I want to go to the developers Cinnamon. Please give your feedback on my conversion. If the problem described is not clear, I will try to describe more available.

**Comment by mtwebster** [comment]
Hi, can you be more specific which program you're using for viewing pictures (in item 1)

Regarding 2, and (and possibly 1, and hidpi in general), we don't have full control how these programs behave.  Some support hidpi, many do not (and depending on what libraries they're using for their GUI, never will) - for instance, pretty much any program written using the gtk2 toolkit is completely unaware of hidpi factors, and assumes you're just using a very hi resolution monitor - this more or less explains your issue in 2, but is contrary to what you're describing in 1, which is why I'd like to know the name of the program.

**Comment by DimitriyPS** [comment]
mtwebster, thank you for your feedback.
 		
I use the standard program: "EOG" and "gThumb". gThumb functional and comfortable. But the interface gThumb is not displayed correctly.
![gthumb](https://cloud.githubusercontent.com/assets/11189223/7142760/8e7532b8-e2e3-11e4-9150-5724e52c1e11.png)
In the end, prefer EOG. I described the problem No. 1, refers to both programs.
Software screen shots - the standard. The name I don't know.

Assumption: it is possible for GTK3 rendering uses a point size of 2*2 pixels.

The screenshot above - you can evaluate what is the result (problem 2).

P. S.: I started using this laptop running XFCE (GTK2). When using XFCE with these problems I not encountered. When I started using Cinnamon, I immediately detect into these problems.

It's not so bad, worse things do happen. But it really bothers in their daily work.

**Comment by dalcde** [comment]
Do you mean the exact same programs work as desired on xfce? Or the programs that come with xfce work?

**Comment by DimitriyPS** [comment]
What information is needed? I don't understand the question.

The question is that you are not able to reproduce this bug? It is very simple, in the Cinnamon settings switch to support high resolution.

**Comment by dalcde** [comment]
What do you mean by "When using XFCE with these problems I not encountered"? Did you try to use exactly the same programs (ie. eog and gthumb) in xfce, or did you use some other program in xfce and they worked?

**Comment by DimitriyPS** [comment]
gThumb in XFCE I used. About eog just can not say, used the standard in XFCE.

In XFCE (when I used it), support for high resolution screens was worse than Сinnamon. There's only scaled text (buttons, menus, etc.). Indents, spacing, size icons - remained on the monitor is not of high density. If I am not mistaken XFCE was then GTK2 (I do not know as of now). The Cinnamon GTK2 applications the same scale not full (as it was in XFCE).

Therefore, I guess that the problem lies not in the cinnamon but GTK3. To be more precise in how it implements scaling. I think he did not recalculate the size according to the PDI, and changes (doubles) pixel size. This approach explains the obi my problems.

**Comment by dalcde** [comment]
Closing then

**Comment by DimitriyPS** [comment]
>>Closing then
But the problems have not gone away. What to do?

**Comment by dalcde** [comment]
Report it to eog/gThumb/gtk
