### ISSUE TITLE
Cinnamon settings apps will not controlling mouse after installing gpointer. 

### ISSUE THREAD

**Issue by Marsfan** [linuxmint/Cinnamon#3930]
After I installed gpointer (package gpointing-device-settings) the default cinnamon settings app no longer changed settings for the touch pad on my computer. Even if I uninstall gpointer.

**Comment by Vahan86** [comment]
@Marsfan, is this still an issue for you in Cinnamon 3.0?

**Comment by Vahan86** [comment]
@JosephMcc, can we close the issue?
