### ISSUE TITLE
Skype tray icon is not correctly scaled

### ISSUE THREAD

**Issue by artik** [linuxmint/Cinnamon#3933]
I noticed that the Skype icon is too big regarding the others : http://i.imgur.com/maLLKwb.png

Maybe this could be changed ? I tried to changed the scale of all icons in /usr/share/cinnamon/applets/systray@cinnamon.org/applet.js (line 9 : const ICON_SCALE_FACTOR = .8;) I changed to .64 for exemple, but the others become to small).

**Comment by vovka-korovka** [comment]
Check your gtk theme  (gtkrc) - looks like 'gtk-icon-sizes' values are hardcoded to 22x22 pixels when skype uses 24x24.

**Comment by artik** [comment]
Ok, any suggestion to fix this ?

**Comment by vovka-korovka** [comment]
Fix you gtkrc file - e.g. 

gtk-icon-sizes  = "gtk-button=24,24"

**Comment by artik** [comment]
I tried :
sudo subl /usr/share/themes/Mint-X/gtk-2.0/gtkrc

Then uncomment the line, testing 24,24 or 16,16, and nothing changed.

**Comment by lestcape** [comment]
@artik i think that what you need is speak with microsoft. What you need is increase the padding, canvas and real images don't have always the same size and this is normal. could be apply e prefilter to the images to find the real color borders and then cut the padding, but thats on my opinion will decrease the performance just for be perfect.

**Comment by ManIVIctorious** [comment]
This seems to be more of a skype issue than one of cinnamon...
Nevertheless, does this still occur with latest cinnamon (3.0.x) and the newest version of skype?

**Comment by mainmachine** [comment]
Also, should check against both versions of Skype, the stale (but fuller featured) "legacy" and the recently released "Skype for Linux Alpha", which will likely replace the old one entirely within a few months...

https://www.skype.com/en/download-skype/skype-for-linux/

https://community.skype.com/t5/Linux/Skype-for-Linux-Alpha-and-calling-on-Chrome-amp-Chromebooks/td-p/4434299

**Comment by JosephMcc** [comment]
Trying to keep all the systray related issues together in one place https://github.com/linuxmint/Cinnamon/issues/481
