### ISSUE TITLE
crash when dragging large objects in Chromium

### ISSUE THREAD

**Issue by gordon-morehouse** [linuxmint/Cinnamon#3935]
This is cinnamon 2.4.6+rebecca, running on binary nVidia drivers on an Intel i7 w/GT240 graphics card.

This is 100% reproducible, at least with the one large object I've encountered it with in Chromium (a very "tall" post on a social networking site which I attempt to drag to move).

WHAT ACTUALLY HAPPENS
------

1. I click and drag the post
2. A number of black regions appear on various parts of the screen, including things that aren't Chromium. some icons in the panel tray may be replaced with what appears to be bits of other windows or graphic primitives
3. if I release the mouse button, it stays as the "dragging hand" cursor
4. the mouse pointer moves but nothing is clickable and the cursor remains the "dragging hand"
5. alt-tab does nothing; ctrl-alt-bksp does nothing; ctrl-alt-F1 works fine
6. ctrl-alt-del brings up a dialog which, along with its followup ("programs are still running") can be interacted with only by keyboard. everything else remains unusable and other dialogs brought up by programs being killed can't be clicked or switched to
7. logout appears to work normally
8. cinnamon appears to work normally after logging back in

WHAT I EXPECT TO HAPPEN
------

1. I can click and drag large objects in any application without a crash.

**Comment by gordon-morehouse** [comment]
I accidentally re-reported this on launchpad at https://bugs.launchpad.net/linuxmint/+bug/1475940 - oops. I'll add my new impressions from current Linux Mint 17.2 and Cinnamon 2.6.13+rafaela.

This report is for Mint 17.2 running Cinnamon, kernel 3.13.0-37-generic #64-Ubuntu SMP Mon Sep 22 21:28:38 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux, latest updates as of this writing were all installed. This is a Core i17 box with 4 physical (8 logical) cores and an EN 240 GT nVidia graphics card. It has two panels connected, one by DVI and one by VGA, though the VGA panel was disconnected the second time I observed this bug. I am running Chromium Version 43.0.2357.130 Built on Ubuntu 14.04, running on LinuxMint 17.2 (64-bit).

STEPS TO REPRODUCE:

1. Find a REALLY REALLY TALL tumblr post - this one triggers the bug for me: http://milokeen.tumblr.com/post/123679782459/vegan-master-post
2. Put it in your queue.
2a. Possibly, populate your queue with a ton of posts and have it near the bottom.
3. "Grab" the post by the top header in order to drag it within the Tumblr queue.

WHAT ACTUALLY HAPPENS

Sometimes a whole-screen disappearance except desktop background, followed by a repaint of all windows. Sometimes similar flickery technicolor behavior and then a dialog announcing "Cinnamon has crashed. You are currently running in fallback mode. Restart Cinnamon?" Restarting appears to re-enable normal function, at least insofar as I'm writing this report without having restarted X.

WHAT I EXPECT TO HAPPEN

I should be able to drag and drop the post as normal without Cinnamon crashing.

As I recall this was a fairly reproducible bug once posts large enough were found in one's queue. I suppose I'll find out now.

-----

Okay, this is 100% reproducible with the post in question on my current session. Also, there's a lot of mouse cursor switching between arrow and text-highlight and maybe some other pointers. WTF.

-----

I rebooted the machine. Test results:

  * able to reproduce with same post in Chromium after a reboot
  * the first time I grab such an object, I get a screen clear to background image, then a complete repaint and it appears to function normally. the next time I grab the object, I get the "Cinnamon has crashed" fallback mode dialog.

I tried other things:

  * unable to reproduce in Firefox
  * unable to reproduce in Chromium when *editing* the post and attempting to "grab" it, but when successful the entire Chromium content area flashed grey

**Comment by gordon-morehouse** [comment]
This is still a problem in Cinnamon 2.8.6+rosa amd64 with Chromium 48.0.2564.82 amd64.

This time I got an immediate "Cinnamon has crashed" message on the first drag, but uptime for my session was 6 days.

3.13.0-61-generic #100-Ubuntu SMP Wed Jul 29 11:21:34 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by mtwebster** [comment]
I'm wondering if this is possibly related to https://github.com/linuxmint/Cinnamon/issues/4789 - would you mind trying the test debs I've posted there?

**Comment by gordon-morehouse** [comment]
I'll try to follow up on that bug when I can. If you don't hear from me in a couple days and still need diagnostic help feel free to ping me.

**Comment by ManIVIctorious** [comment]
Does the issue still occur in cinnamon 3.0?

**Comment by gordon-morehouse** [comment]
I can't reproduce this with a similar object in Chromium 51.0.2704.79 64-bit on Cinnamon 3.0.1+sarah.

**Comment by mtwebster** [comment]
For the record, this is a chrome(ium) bug - and we workaround it here: https://github.com/linuxmint/muffin/commit/8fc6ff94fbe5e572fb335270338a526298258b86 with a followup here: https://github.com/linuxmint/muffin/commit/d8dc04f88dda242dca53b0462740af98be3f5a21
