### ISSUE TITLE
Using panel applet icons after installation

### ISSUE THREAD

**Issue by philipzae** [linuxmint/Cinnamon#3937]
After installing an applet into the panel, if you go to the other tab to activate it, it no longer shows in the list with its custom icon and as a result, when i installed 8 system monitor apps, i couldnt easily tell the difference between them and instead jumped between the two tabs to compare the email address associated with them.

**Comment by dalcde** [comment]
This is because the "install" page uses the icon set on cinnamon-spices, while the other page uses the icon set inside the applet, which may or may not be the same.

**Comment by NikoKrause** [comment]
It's up to the developer. He is in charge, which icon will be used.
@joseph @clem your thoughts on this?

**Comment by JosephMcc** [comment]
Well the developer decides which icons are being used. If it's a huge problem it can be addressed in the spices repos now.
