### ISSUE TITLE
Active Application Locked When "Show Desktop" Is Clicked

### ISSUE THREAD

**Issue by madprops** [linuxmint/Cinnamon#3939]
When I click on the "Show Desktop" button all the windows get minimized. But when I try to open the application that is active on the panel (the application that was active before I clicked the show desktop button) it doesn't open. If I click on any other application on the panel they open. I find this behavior very awkward.

**Comment by Swistaku** [comment]
This must be a regression, as on Mint live (downloaded today) the problem doens't occur. However, I can confirm that after installing & updating I can notice the same problem - not only with Show Desktop applet, but also when using Super-D - last active window, when clicked on panel doesn't show up

**Comment by dalcde** [comment]
Seems to be fixed in git master. Can someone confirm?

**Comment by JosephMcc** [comment]
It does seemed to be fixed. When I have two windows open and activate the applet, all windows are hidden and I am able to activate the one that was active before doing it.
