### ISSUE TITLE
Sound applet - Sound effects working not as expected (Changing the sound volume sound effect) 

### ISSUE THREAD

**Issue by Swistaku** [linuxmint/Cinnamon#3941]
Hey,

I've noticed that sound applet doesn't care about the setting in 'Changing the sound volume' sound effect. Doesn't matter if I turn it off or on, when I change volume I still can hear the sound effect. What else that is interesting, I've noticed that when I mess with 'Starting cinnamon' sound effect at the same time it changes the setting of aforementioned effect.

1. Both (1) 'Starting cinnamon' & (2) 'Changing the sound volume' ON - can hear the sound
2. (1) ON, (2) OFF - still can hear the sound
3. (1) OFF, (2) OFF - as expected changing the sound volume effect is now disabled
4. (1) OFF, (2) ON - no sound effect
5. (1) ON, (2) ON - (2) now is back
6. (1) OFF, (2) ON - can hear the sound effect
7. (1) OFF, (2) OFF - can hear the sound effect

Here are my current settings:
![screenshot from 2015-03-01 12 08 46](https://cloud.githubusercontent.com/assets/640241/6430488/bec66a9a-c00b-11e4-944b-b1bbe2c00546.png)

And I'm able to hear (2) sound effect

Edit: Don't know if #3858 is solving the problem, can anyone check this?

**Comment by pixunil** [comment]
Is now fixed in #3858.

**Comment by mtwebster** [comment]
https://github.com/linuxmint/Cinnamon/commit/05f65cfb4e4cba506a84bd30743b0f3f41f0ddb9
