### ISSUE TITLE
Can't open power settings: "Unknown module power, using cinnamon-control-center"

### ISSUE THREAD

**Issue by hyOzd** [linuxmint/Cinnamon#3944]
When I try to open Power Management from the menu, I get control panel. And there is no power management icon. I tried to run command in the .desktop file for Power Management menu item:

`>> cinnamon-settings power`

And I get this:

    Unknown module power, using cinnamon-control-center

    (cinnamon-settings.py:5573): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:135:2: Missing name of pseudo-class
    __init__ took 104.837 ms

This is Linux Mint 17, Cinnamon 2.4.1 . It wasn't always like this, probably I messed up something but I have no idea.

**Comment by mtwebster** [comment]
See if the power module exists:
`ls /usr/lib/cinnamon-settings/modules/cs_power.py`

That's supplied by the 'cinnamon' package - you can try simply re-installing it:
`sudo apt-get install --reinstall cinnamon`

**Comment by hyOzd** [comment]
There is `cs_power.pyc` in that directory. That means cs_power.py was there but got deleted at some point. Probably I have updated cinnamon from a non-stable source. Sorry, I can't remember the details. But I can't "reinstall" cinnamon now, it's not "downloadable".

**Comment by hyOzd** [comment]
I have updated Linux Mint via update manager to 17.1 Rebecca. Now my cinnamon version is 2.4.6, and Power Management settings is back. Thanks for help.
