### ISSUE TITLE
calendar has same week twice, leads to off-by-one on following weeks

### ISSUE THREAD

**Issue by pirkkalalainen** [linuxmint/Cinnamon#3947]
Tried this on
Linux Mint 17.1 Rebecca - Cinnamon 64bit
and
Linux Mint 16 Petra - Cinnamon 64bit

Open calendar with the default applet on down-right corner. 

There are two weeks numbered as 13 in the year 2015.  This leads to an off-by-one problem on the week numbers later than 13. This seems to correct itself in January 2018 when Monday is 1st of January. :)

I hope this is just me but might be not.

![calendar_offset](https://cloud.githubusercontent.com/assets/6960572/6529559/40db1c90-c432-11e4-9f2c-d6a912e0a5f7.png)

**Comment by mtwebster** [comment]
Probably this: https://github.com/linuxmint/Cinnamon/commit/6be6ca1a54781283017132cb51d4605c7b91f4c4

Should be fixed in a coming update on Rebecca.

**Comment by pirkkalalainen** [comment]
Ah, so it seems. Same problematic days and all. Good to know, thank you.

**Comment by cptmintalicious** [comment]
Hey there. Has there already been a bug fix in an update? I've spotted the same issue. Week number 13 exists twice, but week number 43 is missing. At both weekends our time zone switches from standard time to summertime and vice versa. Could this cause the issue?

**Comment by pirkkalalainen** [comment]
I can confirm that I'm still suffering from double 13. I'm pretty sure that week 43 was not missing before, but now it is indeed missing. Earlier I noticed that this off by one was going to be fixed in January 2018 for some reason. But now this missing week 43 will "fix" this off by one earlier.

**Comment by stefan123t** [comment]
I replaced the following line in calendar.js which resolves the problem for me.

/usr/share/cinnamon/applets/calendar@cinnamon.org/calendar.js
@@ -393,1 +393,1
@@ Calendar.prototype = {
-            if (this.show_week_numbers && iter.getDay() == 4) {
+           if (this.show_week_numbers && ((7 + iter.getDay() - this._weekStart) % 7) == 0) {

Kind regards,
Stefan

**Comment by stefan123t** [comment]
cptmintalicious / pirkkalalainen, this just did not feel right yet.

Anyone knows how to reopen the issue ?

**Comment by stefan123t** [comment]
I opened a new issue for the change to be commited.

 calendar@cinnamon.org calendar week numbers suffer from one-off #4031
