### ISSUE TITLE
Panel can't be placed on the top display in vertical dual display setup

### ISSUE THREAD

**Issue by tp0** [linuxmint/Cinnamon#3949]
Repro:
1. Arrange displays in a vertical setup and so that the top display = primary
2. What goes wrong: panel gets placed on the bottom (secondary) display.

Not a new thing I think or at least to me this has been always like this, just didn't see a bug about this.

Cinnamon 2.4.5
Ubuntu 14.04

![screenshot from 2015-03-07 19 31 40](https://cloud.githubusercontent.com/assets/5863551/6542453/35b062c4-c501-11e4-95eb-220e39886c4f.png)

~/.config/monitors.xml:

```
<monitors version="1">
  <configuration>
      <clone>no</clone>
      <output name="LVDS1">
          <vendor>LGD</vendor>
          <product>0x0354</product>
          <serial>0x00000000</serial>
          <width>1366</width>
          <height>768</height>
          <rate>60</rate>
          <x>0</x>
          <y>768</y>
          <rotation>normal</rotation>
          <reflect_x>no</reflect_x>
          <reflect_y>no</reflect_y>
          <primary>yes</primary>
      </output>
      <output name="VGA1">
      </output>
      <output name="HDMI1">
          <vendor>SAM</vendor>
          <product>0x07d0</product>
          <serial>0x00000000</serial>
          <width>1360</width>
          <height>768</height>
          <rate>60</rate>
          <x>0</x>
          <y>0</y>
          <rotation>normal</rotation>
          <reflect_x>no</reflect_x>
          <reflect_y>no</reflect_y>
          <primary>no</primary>
      </output>
      <output name="DP1">
      </output>
  </configuration>
</monitors>
```

**Comment by collinss** [comment]
The next release of Cinnamon will feature a more flexible panel system in which you can place panels on any monitor you want. I have tested the change myself with a vertical configuration, and didn't have that problem.

**Comment by tp0** [comment]
Great. For reference: http://segfault.linuxmint.com/2015/02/recent-cinnamon-development/
