### ISSUE TITLE
No unminimize effect when restoring minimized window via Alt+Tab or panel menu 

### ISSUE THREAD

**Issue by tp0** [linuxmint/Cinnamon#3950]
Repro:
1. open e.g. two terminal windows
2. minimize window 1
3. Alt+Tab to window 1 OR right mouse click on window 1 in the window list and select "Restore"

Expected result is an unminimize effect. Now the window reappears as if it was just behind other window(s) in the background which causes visual confusion.

The effect for unminimizing already exists and works when unminimizing/restoring the window via cliking it in the window list.

This seems to something inherited Gnome 3, so I guess this is more of a feature request.

**Comment by dalcde** [comment]
I believe this is by design. Alt-Tab is designed for quick window switching

**Comment by tp0** [comment]
A bit disappointing answer/reason. If this effect did exist and was also configurable in the Effects panel, one could set the speed in milliseconds or turn it off completely which even could stay as the default.

Do you mean by design by Gnome and that Cinnamon just never revised this?

**Comment by dalcde** [comment]
We've messed with Alt-tab quite a lot, so it should be a Cinnamon desgin.

I'd personally want no animation for alt-tab, and animations will look really silly if you use window preview.

**Comment by tp0** [comment]
> The effect for unminimizing already exists and works when unminimizing/restoring the window via cliking it in the window list.

Not anymore on 2.6. Broken or removed on purpose?
