### ISSUE TITLE
Applets in autohidden panels show tooltips, and are clickable(!), *before* they show

### ISSUE THREAD

**Issue by ACinnamonUserInUK** [linuxmint/Cinnamon#3952]
This clickable-when-not-yet-unhidden functionality (or 'functionality') is counter-intuitive, looks messy and sloppy, and, especially with a top panel, can interfere with what one is doing.

Applies to: all recent versions of Cinnamon (at least when run on Mint 17.1 x64 - I haven't tested on other systems).

I love Cinnamon, but this one is a bit of show-stopper for me.

**Comment by ion201** [comment]
I can confirm this issue.

Min 17.1 x64; cinnamon 2.4.6; kernel 3.16

To reproduce, the panel must be set to autohide with some nonzero delay before appearing. With the bottom panel, mousing over the lowest pixel row of the panel will behave as if the tray were extended while any space above that (even while still over the unextended panel) will behave as expected and interact with the foreground window.
