### ISSUE TITLE
Nemo crash/corruption

### ISSUE THREAD

**Issue by MintyMorkyMindy** [linuxmint/Cinnamon#3954]
http://forums.linuxmint.com/viewtopic.php?f=208&t=190967

"I am unsure how to classify the following other than to relate the outcomes as follows.

This has occured on a number of occasions and I am unsure the origin, but it happened again just now when I was using Nemo file manager to start VLC media player.

Everything froze for many seconds and then when I got control again the following occured, which is consistent with the other times this has happened:

1. Nemo is the default green, but when it starts again it looks like Windows Explorer 95, greyish and very old school buttons.
2. My desktop changes to some random image, and if this crash/corruption happens again, that same image becomes the desktop.

The only way I have found to fix this is to restart Linux Mint.

That is the problems, crash/corruption that occurs occasionally.

Linux Mint 17.1 fully updated.

Thanks."

**Comment by leigh123linux** [comment]
Verified by who?

What you describe sounds like a cinnamon-settings-daemon crash, without any error logging the issue isn't verified (post some logs).

**Comment by dalcde** [comment]
If no one else has experienced the same problem, I'd recommend checking your disk.

**Comment by Vahan86** [comment]
@MintyMorkyMindy, does this issue still occur in Cinnamon 3.0?

**Comment by Vahan86** [comment]
@JosephMcc, can we close this issue?
