### ISSUE TITLE
Nemo - 500GB HDD internal, formated, now not recognised until selected directly ...

### ISSUE THREAD

**Issue by MintyMorkyMindy** [linuxmint/Cinnamon#3955]
The 500 GB HDD is internal and working no problem for months. I then formatted the HDD to ext4 as before, and bookmarked a folder.

At start up the folder has a a mini orangish error icon and the following pop up:

"Could not find "/media/username/HDDname/foldername"

Once I directly click on the HDD in Nemo and the folder, it starts to work.

The problem appears one of not remembering settings once Linux Mint is restarted.

I have version 17.1 installed, the HDD are Seagate.

**Comment by leigh123linux** [comment]
Is "/media/username/HDDname/foldername" in fstab?, if not you will need to mount it first in nemo.
