### ISSUE TITLE
Cinnamon Calendar applet - smaller date under bigger time

### ISSUE THREAD

**Issue by hrvoojex** [linuxmint/Cinnamon#3956]
Wouldn't it be great in Cinnamon Calendar applet to have an option to make the time bigger and above smaller date, in two rows.

Because when I make bottom panel larger and use 'Allow Cinnamon to scale panel text..." option, the Calendar applet is 10 cm long and it doesn't look nice.

**Comment by anandrkris** [comment]
Related request
https://github.com/linuxmint/Cinnamon/issues/3555

**Comment by JosephMcc** [comment]
This is close enough to the linked issue that I'm closing it as a duplicate.
