### ISSUE TITLE
Cinnamon mintInstall - can't browse screenshots  

### ISSUE THREAD

**Issue by hrvoojex** [linuxmint/Cinnamon#3957]
It is not possible to browser pictures in mintInstall if there is more than one picture. You have to go back and select another picture. 

Would it be possible to make when you click on one picture just to browser right or left to see other pictures?

**Comment by anandrkris** [comment]
Guess you're referring to Application screenshots...Should be logged here then - https://github.com/linuxmint/mintinstall

**Comment by hrvoojex** [comment]
@anandrkris you are right ;) I was thinking of Aplication screenshots. Ok, what should I do now so that the author sees my proposal?

**Comment by anandrkris** [comment]
Am sure devs look into every issue although they don't reply on every item. This is definitely a good usability improvement but will be prioritized based on their availability.

**Comment by dalcde** [comment]
Please open a new issue in https://github.com/linuxmint/mintinstall. Closing this.
