### ISSUE TITLE
Touch screen matrix does not transform when connecting a screen

### ISSUE THREAD

**Issue by Zaharid** [linuxmint/Cinnamon#3958]
When I connect an external screen to my laptop and set it to be above my laptop's, I need to call:

```
xinput set-prop 9 'Coordinate Transformation Matrix' 1 0 0 0 0.5 +0.5 0 0 1 --type=float
```

In order to have the touchscreen still point to the correct position when I touch it. When disconnected the screen I have to reset this setting by:

```
xinput set-prop 9 'Coordinate Transformation Matrix' 1 0 0 0 1 0 0 0 1 --type=float
```

I notices this is not necessary in Ubuntu (Unity) and it would be nice if Cinnamon had this feature.

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html
