### ISSUE TITLE
Right click context menu hidden by panel

### ISSUE THREAD

**Issue by zaahirlaher** [linuxmint/Cinnamon#3964]
Hi

I'm running linux mint 17 (cinnamon). When using netbeans, the bottom of the right click context menu  (when right clicking at the lower part of the screen) is behind the panel. 

In the screenshot, the last Item in the menu is behind the panel.
![screenshot from 2015-03-16 11 28 46](https://cloud.githubusercontent.com/assets/653578/6663479/aa565820-cbcf-11e4-87e0-56131d6ae46e.png)

**Comment by zaahirlaher** [comment]
I also had this issue when I was running Cinnamon on Ubuntu (on a different machine)

**Comment by JosephMcc** [comment]
I just installed netbeans and its plethora of dependencies to test this and the issue seems to be fixed in git master for the upcoming Cinnamon 3.0
