### ISSUE TITLE
Shutdown-dialog on cinnamon thinclient (per ltps) not working

### ISSUE THREAD

**Issue by quicknick** [linuxmint/Cinnamon#3967]
Hi there,

i've implemented a LTSP environment on LinuxMint 17.1 (Rebecca) with an chroot ubuntu thinclient clientimage. The environment is working fine after installing the "ltsp-server-standalone" package and building the clientimage via "ltsp-build-client --dist trusty --mint-dist none --exclude software-properties-gtk  --arch i386 --purge-chroot".

Also the package "ldm-mint-theme" for an LinuxMint theme at the LDM based logon-menu is working fine. Also, there is in the Cinnamon (v 2.4) Menu a shutdown-button (in German: "Herunterfahren") at the thinclient. But with this button i can't shutdown the thinclient, there is only a button to abort/cancel (German: "Abbrechen") the dialog / operation. 

My translation (from German) about the popup-window: 
`
[SESSION]
Do you would like to power down the Computer?
You're currently logged in as %USERNAME%.
(Abort / Cancel)-Button
`
For sure, i could poweroff the thinclient after logout the user in cinnamon with the thinclient LDM based menu, but that's not very helpful for the users on my terminalserver.  :? At the terminalserver, i could for sure shutdown the terminalserver with the cinnamon shutdown-menu dialogbox. 

For any help thanks in advance!

**Comment by Vahan86** [comment]
@quicknick, is this issue still relevant to Connamon 3?

**Comment by Vahan86** [comment]
@JosephMcc, can we close the issue?
