### ISSUE TITLE
After upgrade to Linux Mint 17.1 Cinnamon, no Language Settings

### ISSUE THREAD

**Issue by DavidNemeskey** [linuxmint/Cinnamon#3968]
I upgraded from Linux Mint 17 (Cinnamon edition) to 17.1 just today. I had especially been looking forward to the new Language Settings, which is a pet peeve of mine (https://bugs.launchpad.net/indicator-datetime/+bug/1024663). Here are the steps I took:

- in the Update Manager, clicked on the menu 'upgrade to 17.1'
- ran the update
- at one point, I got this error message: "_trying to overwrite '/usr/share/mdm/html-themes/SpaceRace/ship3.png', which is also in package mdm-html5-themes-samriggs 0.1.2~debian+dmd_"
- since the application exited, I went to the console and did:
  - `dpkg --remove mdm-html5-themes-samriggs`
  - `aptitude install -f`
- restarted the system

The packages that I checked (mdm, mdm-themes, nemo) are at the version they should be in 17.1. However, the System Settings does not have a Language Settings section; indeed, searching for "lan" in there finds nothing.

**Comment by dalcde** [comment]
I'm sorry to tell that the new Language Settings does not belong to Cinnamon but Unity...

**Comment by mtwebster** [comment]
No, it's mintlocale - see if that's installed:

sudo apt-get install mintlocale

**Comment by DavidNemeskey** [comment]
@mtwebster Thanks, that was indeed the package I needed! Two more things than:

1. Was it not installed because of the upgrade problem I had? I.e. is this package installed when the user upgrades? Because it is on the "New features" page, one would expect it to.
2. Might there be other packages I am missing? Is there a list of packages I should try to install just to be sure?
