### ISSUE TITLE
Seemingly one cannot add applets to a panel when that panel is full

### ISSUE THREAD

**Issue by ACinnamonUserInUK** [linuxmint/Cinnamon#3969]
. . but not because there is no more room - for I think that panel applets would resize themselves to accomodate a new panel - but, rather, because one cannot access the menu for adding applets. That menu seems to be accessible, only, by right clicking . . an empty area of panel.

**Comment by anandrkris** [comment]
https://github.com/linuxmint/Cinnamon/issues/1010 Same as this?

**Comment by JosephMcc** [comment]
In this case you can use Cinnamon settings to do what you need. Applet settings allow you to add applets to the panel and the panel settings allow you to activate panel edit mode to move them around. This can also be theme dependent. If your theme has some spacing between the applets you can click in that space to get the panel menu.

**Comment by dalcde** [comment]
Closed for duplicate
