### ISSUE TITLE
Can't drag folders into "My computer" section of nemo

### ISSUE THREAD

**Issue by raidermax** [linuxmint/Cinnamon#3982]
For some odd reason, whenever I try to drag in a folder into the "My computer" section in Nemo, it either does not work or gets put into the "Bookmarks" section. I am on arch linux (same thing happens on Manjaro) and this weird bug occurs, however if I go on a Linux mint 17.1 machine I have running it does not behave like this. I have nemo 2.4.5 and cinnamon 2.4.6-1

**Comment by dalcde** [comment]
Confirmed on nemo git (arch)

**Comment by JosephMcc** [comment]
Same problem here with LMDE2 and nemo git.

**Comment by raidermax** [comment]
Any news on whether this will get looked at?

**Comment by GLolol** [comment]
I'm getting this too with nemo git. Originally I had some items in My Computer from before, and adding new items there worked. On a fresh installation though without any pre-existing bookmarks, it breaks.

**Comment by s8dtvt** [comment]
confirm bug with nemo 2.6.7 in arch linux

**Comment by mtwebster** [comment]
https://github.com/linuxmint/nemo/commit/77f108e68a39f4073cd94119c9866baac2b0b4ff

**Comment by raidermax** [comment]
@mtwebster 
Quick question, is this patch in the most recent version of Nemo? If it is, I am still experiencing this issue.
