### ISSUE TITLE
Cinnamon 1.7.4 stops responding to mouse and keyboard

### ISSUE THREAD

**Issue by TheKiwi5000** [linuxmint/Cinnamon#3987]
When clicked on any applet on  the left of bottom toolbar, cinamon stops responding to mouse clicks and keyboard shortcuts.

I have ubuntu, here's output of `lsb_release -a`
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.10
Release:	14.10
Codename:	utopic
```
I have installed cinnamon like [here](http://www.omgubuntu.co.uk/2014/11/install-cinnamon-2-4-ubuntu-14-04-lts)

If anything else needs to be posted, tell me.

**Comment by leigh123linux** [comment]
Cinnamon 1.7.4 in unsupported please update to cinnamon 2.4.x

**Comment by mtwebster** [comment]
Are you sure this is 1.7.4?  Please run `cinnamon --version` - otherwise, as mentioned, it's unsupported.

**Comment by TheKiwi5000** [comment]
I'm sure i was 1.7.4. Unfortunately this was latest version from my distro's repo (this version i will download from your nightly repo).
