### ISSUE TITLE
adding key-shortcuts freezes cinnamon and resets wallpaper

### ISSUE THREAD

**Issue by albvalente** [linuxmint/Cinnamon#3993]
If I try to add some custom shortcuts, the first works fine, when I add the second, cinnamon freezes for some seconds and my wallpaper goes back to default wallpaper

**Comment by Vahan86** [comment]
@albvalente, does this issue still occur in Cinnamon 3.0?

**Comment by JosephMcc** [comment]
This belongs here: https://github.com/linuxmint/Cinnamon/issues/3953

A search turns up a bunch of already closed issues for this exact thing.
