### ISSUE TITLE
screenshot doest have the mouse i use in cinnamon

### ISSUE THREAD

**Issue by Hanmac** [linuxmint/Cinnamon#3998]
when making a screenshot with gnome-screenshot it doesnt use the correct mouse cursor i set in cinnamon.

**Comment by dalcde** [comment]
Does it show the wrong cursor or does it not show a cursor at all? afaik the cursor is not intended to be shown in screenshots, unless you use the -p option.

**Comment by patricktokeeffe** [comment]
I think this should be left open. AFAICT, there is no way to modify the command tied to the keyboard shortcut such that the `-p` flag is included. 

More broadly, hiding such a common and fundamental option behind a command line flag is just crappy UX. But that's `gnome-screenshot`'s problem, not Cinnamon's.
