### ISSUE TITLE
dual monitor can cause to have two mouse cursors

### ISSUE THREAD

**Issue by Hanmac** [linuxmint/Cinnamon#3999]
for my current monitor setting i have two monitors, one of them is rotated.

it can happen than it does show two mouse cursors, one of them rotated too at the correct position.
Changing the mouse cursor in the theme does remove the problem.

because of #3998 i cant make a screenshot to show what i mean.

**Comment by dalcde** [comment]
Can you take a photo or something to illustrate the issue?

**Comment by Mrono** [comment]
http://imgur.com/9FyvHVX

I have 3 monitors (laptop, 2 external) and one is rotated to portrait,  The issue only occurs for me when I have one of them rotated and the cursor will randomly go away and come back.  It doesn't display an extra on the rotated monitor.

**Comment by Vahan86** [comment]
@Hanmac, is this still an issue for you with Cinnamon 3.0.x? If not, could you please close it?

**Comment by Hanmac** [comment]
@Vahan86: i don't have multimonitor anymore, might ask @Mrono if he still has the problem.

**Comment by Vahan86** [comment]
@JosephMcc, can we close this issue?
