### ISSUE TITLE
Alt-Tab is app-centric

### ISSUE THREAD

**Issue by clefebvre** [linuxmint/Cinnamon#4]
The Alt-Tab switcher is app-centric. It should be window-centric.

**Comment by b3rs3rk1ng** [comment]
I've created PR #13498 which addresses both this issue and #2883 by making the behavior configurable.

The PR adds a new setting `alttab-switcher-group-by-app` that users can toggle in System Settings → Windows → Alt-Tab.

This way:
- Users who prefer window-centric Alt+Tab can keep it disabled (default)
- Users who want application-centric Alt+Tab can enable it

Both preferences are satisfied with a simple toggle.

Standalone version available at: https://github.com/b3rs3rk1ng/cinnamon-group-windows-by-app
