### ISSUE TITLE
Remove from favorites in panel menu with right click option 'remove'

### ISSUE THREAD

**Issue by hrvoojex** [linuxmint/Cinnamon#4000]
When you want to remove an item from favorites, you have to find it in a menu and then right click and select 'remove from favorites'.

Would it be possible to remove it right from the favorites menu with a right click or a mouse?

**Comment by collinss** [comment]
You can just drag it from the favorites to the main part of the menu.

**Comment by hrvoojex** [comment]
Didn't know that because it doesn't work if you drag it outside of the menu

**Comment by raidermax** [comment]
Wait, right clicking the apps on my favorites doesn't bring anything up, I have to search the app first and then I can remove it. Is this intended?

**Comment by JosephMcc** [comment]
@raidermax simply drag the item out of favorites over any other part of the menu and it will be removed from the favorites box

**Comment by anandrkris** [comment]
@NikoKrause - In case you want to pick this up - Right click options for Favorties...

**Comment by NikoKrause** [comment]
I think that right click for favorites is problematic.
The favoritesBox has a fixed height, i.e. it is not scrollable like the applicationsBox.
Which means, that if favorites would have a right click menu, the height of the whole menu would change.
That would look ugly.

Also the favorites are only icons. How should the context menu look like?
I think it's easier to drag and drop to remove it.

The only other way I could imagine is to set the DeleteKey to remove a favorites from it's box.

**Comment by anandrkris** [comment]
Hmm right, it would increase height and will make it look unwieldy. Delete shortcut key is a good idea.

As OP suggests, usually dragging outside the menu is considered as removal - perhaps we can show an delete 'x' indicator beneath the dragged icon when you drag outside Favorites are to make it a bit intuitive?
> Didn't know that because it doesn't work if you drag it outside of the menu

**Comment by hrvoojex** [comment]
Would it be possible to remove the icon from favorites by drag and drop outside of menu also. This might be confusing for a new user when they try first to drag and drop outside the menu and then think it is not possible without trying to drag and drop inside the menu

**Comment by NikoKrause** [comment]
@hrvoojex 
I think that would be too mich.
It is now possible to delete a favorite by pressing the delete button.
And if my other pull request will also be merged, then the mouse cursor will look different, when a Favorite is draged over the menu compared to when it is draged outside the menu.

It would make more sense to add a feature, which drops the applet at the desktop, when you hover it outside the menu. But I don't know how to do it. If you want to, you can create a feature request for that. Maybe someone else will look into it.

**Comment by NikoKrause** [comment]
> It would make more sense to add a feature, which drops the applet at the desktop, when you hover it outside the menu.

A few years ago @rjanja tried to implement that:
https://github.com/linuxmint/Cinnamon/pull/842

It wasn't merged back then. But nemo didn't existed at that time.
Maybe now this could be done with nemo?

**Comment by anandrkris** [comment]
> If you want to, you can create a feature request for that. 
https://github.com/linuxmint/Cinnamon/issues/5028 We already have a feature request for this.

**Comment by dg1727** [comment]
From https://github.com/linuxmint/Cinnamon/issues/4000#issuecomment-255806335
>The favoritesBox has a fixed height, i.e. it is not scrollable like the applicationsBox.
Which means, that if favorites would have a right click menu, the height of the whole menu would change.
That would look ugly.

A user would expect that a separate rectangle could appear over the apps menu with the option for "Remove from Favorites."  That rectangle doesn't have to follow the inline submenu approach that's currently used for a right-click on the regular app icons in the apps menu.  
>Also the favorites are only icons. How should the context menu look like?

The fact that the favorites are only icons will, I think, make it understandable to the user that the submenu there looks different than for regular app entries, which are both icons & text.  

Currently, on mouse-over of a favorites icon, a highlight rectangle appears.  On right-click, this rectangle could, for example, be made L-shaped to contain the text "Remove from Favorites" and any future context-menu entries.  

As to the Delete key and drag-&-drop, they are nice, but many users just won't think of them.  A good way to make the Delete key "discoverable" would be to add a tooltip anyway, which is much the same thing graphically as a right-click menu.  :smiley:  The menu itself (when closed) can already be configured by a right-click menu that pops up a rectangle; users won't understand why they can't do the same thing with Favorites.  

I think that:  
- any perceived stylistic inconsistency of having a right-click menu on Favorites look different than a right-click menu on a regular app entry 

is less of a problem than:  
- users perceiving that items can't be removed from Favorites at all except by browsing through the whole menu to find the same icon that they want to remove from Favorites.

**Comment by JosephMcc** [comment]
Please stop opening what are effectively duplicate issues. All of this could just be added to the already opened issue you linked to.

**Comment by JosephMcc** [comment]
Sorry. I was doing this from my email and mistook what it was. Deleted my irrelevant comment.

**Comment by rjanja** [comment]
I would expect that you could right-click anything in the menu for contextual options, and that if you wanted to do something with an individual entry you would just drag it around to where you want it, including the desktop if you want an easy shortcut. Dragging a shortcut and dropping on an empty space to remove it is unintuitive. Hidden functions like highlighting something with a mouse and pressing a keyboard key or combination is likewise not intuitive.

I would favor the approach of using a consistent behavior for editing anything in the menu, so in this case using a right-click menu to edit the favorites.

**Comment by hrvoojex** [comment]
Right click opens a new rectangle with an option to remove? What could be ugly about that? After 2 years who cares. I will close this.

**Comment by JosephMcc** [comment]
> Right click opens a new rectangle with an option to remove? What could be ugly about that? After 2 years who cares. I will close this.

It's not about being ugly. I'm not sure it's technically possible to do that at the moment. I'm not sure if we can draw a menu on top of an existing menu like that.
