### ISSUE TITLE
Cinnamon Brightness panel applet (from 'online') doesn't work on 2008 Macbook

### ISSUE THREAD

**Issue by gordon-morehouse** [linuxmint/Cinnamon#4007]
This is a 2008 era Macbook, white plastic, 2.1GHz core 2 duo.

WHAT ACTUALLY HAPPENS

1. install brightness panel applet from the 'online' applets in panel edit mode
2. attempt to use it
3. nothing happens, however the mac keyboard brightness keys do call something which can change brightness

WHAT I EXPECT TO HAPPEN

The brightness panel applet AND function keys specific to Mac should both work.

**Comment by collinss** [comment]
The online applets are all third-party. The Cinnamon team doesn't maintain them at all (much like firefox extensions). Many of the online applets have actually been abandoned by their developers, and don't work with later versions of Cinnamon. There has been some discussion about how to improve the situation, but AFAIK there have been no decisions made on the matter. In the mean time you could try to contact the developer of the applet (click 'More info' from the 'Available applets' tab in settings).

**Comment by dalcde** [comment]
Cinnamon has a built-in brightness applet though. Does that work for you?

**Comment by gordon-morehouse** [comment]
Do you know of an open issue or meta-issue about the fact that most of 
the applets are abandoned random code which thus makes Mint/Cinnamon 
look bad? ;) If not I'd like to open one.

I will look for the original developer if I can.

**Comment by gordon-morehouse** [comment]
I'll double-check which brightness applet I'm using shortly.

**Comment by collinss** [comment]
@gordon-morehouse the issue has actually been brought up a number of times in the past, but no consensus has been made as to what course is the best one (at least that I know of). I know that Clem is trying to get some web developers together to redesign the many different sites that Linux Mint has, so perhaps part of that effort will be to clean up the spices website, or at least make it easier to distinguish broken applets from the good ones.

**Comment by gordon-morehouse** [comment]
Aye, my thought is that opening an issue for it could centralize 
discussion, but I don't know if Cinnamon's github is the best place as 
I'm still pretty new to Mint. :)

**Comment by anandrkris** [comment]
Check my [comment here](https://github.com/linuxmint/Cinnamon/issues/3829#issuecomment-73410321).
Clem agreed to look into it and have some sort of mechanism in which users can report *broken* applets / themes / desklets etc.

**Comment by lestcape** [comment]
One thing is find broken applets and another will be find a solution for broken applets... I think that this two things will be important. The first thing can be fixed with a redesign, but the another could be solved if will be possible add a patch for broken applets... The idea that i have is that anyone could summit a patch when an applet is declared as broken and this patch could be installed and tested by the final users and can be approved or not... In this way all people can contribute and thats will be good on my opinion.

**Comment by gordon-morehouse** [comment]
Sorry for the delay, my non-functioning applet reports itself as:

    Brightness
    brightness@markbokil.REDACTED
    An app to control xgamma brightness
