### ISSUE TITLE
User defined panel launchers (usability suggestion)

### ISSUE THREAD

**Issue by anydoby** [linuxmint/Cinnamon#4008]
Hello. I am a new user to Cinnamon and had a question on usability.

I have been using many linux desktops and here is what I find really strange in the latest desktop breeds: why did you remove a possibility to have an arbitrary launcher on a launchers panel? 

A simple example - I develop with Eclipse. I do not want to install it from an rpm, or deb or any other distribution file - it's a java app with its own plugins and configuration system. If I accidentally update it using the system update it will crash my existing plugins. Now I have to jump through hoops - create some weird .desktop file, put it to a secret place (it takes time to investigate, learn unnecessary system details, ask stupid questions on forums, make errors) only to create a tiny button for launching a non-standard application. This boils down to a serious irritation.

Is this a political decision made in order to divert users from desktop linux? I'm not getting it really.

**Comment by mtwebster** [comment]
Hi, you can already do what you want with the panel launcher applet in Cinnamon - right-click an existing panel launcher, click "Add" and it will bring up a dialog where you define your command line and an icon.

**Comment by anydoby** [comment]
Wow. You made my day. I was trying to click on the panel to no avail. Then I tried clicking on an existing (!?) icon and I had the Add option. Thanks a lot :)
