### ISSUE TITLE
Be able to change right scrollbar width in Settings center

### ISSUE THREAD

**Issue by squid-f** [linuxmint/Cinnamon#4009]
Hello all

I have been using a lot Linux Mint Cinnamon on desktop PC's and on on touch-screen laptops as well.
With notebook screen size and with in addition touch-screen ability, it is not easy to catch the scrollbar on the right of the windows. Actually, even with the touchpad, it is not easy to stabilize the mouse to grab the scrollbar.

Having the ability to set the width of the scrollbar in the Settings center would be a great feature.

What do you think ?

Kind regards

**Comment by JosephMcc** [comment]
@squid-f There has already been a discussion about this here: https://github.com/linuxmint/Cinnamon/issues/3691

**Comment by squid-f** [comment]
Thanks JosephMcc

Actually, I have posted already this idea on the Linux Mint community portal. Then, they rejected it and asked me to post it here, on GitHub...

I just read the discussion you referred to in your post. 
I can just concur with the proposal made to have an option in the Control Center to change scrollbar parameters. I understood though there are several perspectives in this story...

I will not insist because I am not able to judge what team should work on this (if agreed). However, I can just tell you that if you don't know how to mess around with themes which are not proposed by default by your distribution, you are not going to find a way around. It will be the case of lot of newbies !
I will conclude by saying that this narrow scrollbar is a pain in the ... with a modern touch screen laptop.

Thanks anyway for your support on other things. Without you, I would be obliged to stick with Windows ! (better for the scrollbar but worse for many other things !)
