### ISSUE TITLE
Arrange expo workspaces in grid instead of linear

### ISSUE THREAD

**Issue by dalcde** [linuxmint/Cinnamon#401]
In expo mode, the workspaces are arranged linearly, which becomes awkward when many workspaces are present. It should be presented in grids (e.g. 2x2 grid of workspaces) instead of a line

**Comment by thorsummoner** [comment]
I'm partial to the linear workspaces, however I would like the flexibility of I change my mind. (This will never be Apple OS or Ubuntu after all, so removing options in not the primary objective)

This shortcoming is one of the top reasons my colleagues don't use mint.

**Comment by raacampbell** [comment]
Glad there is a solution to the workspace grid. This is a **must**. I echo the above comments: absolutely will not use a DE without a grid.

**Comment by jamiehutber** [comment]
This has really be driving me nuts! So much so that I had to stop using Mint. Any plans to get this out any time soon?

**Comment by JosephMcc** [comment]
You realize you're posting in a very old and closed issue? There are no plans to implement this.

**Comment by hernejj** [comment]
It is not perfect but I wrote an applet to provide this feature.
http://cinnamon-spices.linuxmint.com/applets/view/116

**Comment by jamiehutber** [comment]
Oh amazing mate. Its working!

**Comment by YousufAzadSami** [comment]
*sigh* I wish they will give this a thought

**Comment by LucaRed** [comment]
14 years passed and this is still my biggest complaint with Cinnamon. Workspaces on multiple lines is a basic need for my workflow.

[This article at the top of today's HackerNews](https://blog.hopefullyuseful.com/blog/macos-needs-its-grid-back/) describes the problem perfectly, referring to the same regression that happened on macOS.
