### ISSUE TITLE
[Solved] Feature request: double-click tiling undo

### ISSUE THREAD

**Issue by brub2** [linuxmint/Cinnamon#4010]
When you double-click on a window bottom edge (for example) it grows to use all the vertical space (but conserve the horizontal size). I'm not sure if "tiling" is the correct term in this case, but here I go.

It would be nice to return to the initial size for this window by another double-click on the bottom (or top) edge. Actually, you have to maximize and then unmaximize the window to returns to its initial size. 

Said otherwise, the double-click trick should work both ways.

**Comment by Swistaku** [comment]
@brub2 it works for me, although I'm using Numix GTK theme, but I doubt that matters - double clicking when arrow appears (on the edge) will expand the window in desired direction, and then double clicking same/opposite edge will restore it to original size

**Comment by brub2** [comment]
@Swistaku You're right, it works in Mint 17.1 (at least). My production machine is still on Mint 13 and I didn't realize it was a new feature... Good news.

**Comment by Swistaku** [comment]
@brub2 I guess you can close the issue then :-)
