### ISSUE TITLE
Cinnamon does not work (start) with latest  Adwaita theme

### ISSUE THREAD

**Issue by Kozzi11** [linuxmint/Cinnamon#4011]
Because of this commit: https://github.com/GNOME/gnome-themes-standard/commit/53ee6e886c64fb704030a743dc920d0f02771571

**Comment by vovka-korovka** [comment]
Ask you distro maintainer to create package with Adwaita metacity theme from gtk 3.14. Also there is already reported request for gtk decorations support in muffin repo

https://github.com/linuxmint/muffin/issues/177

**Comment by Kozzi11** [comment]
thanks for answer
