### ISSUE TITLE
cinnamon default window size doesn't scale well with hi-dpi

### ISSUE THREAD

**Issue by wgnann** [linuxmint/Cinnamon#4012]
Version: LMDE 2 "Betsy", Cinnamon 64bit
Display size: 1920x1080

When I change to hi-dpi in Cinnamon some windows, like Mint welcome dialogue and settings menu, have their size larger than the screen itself. Also, the lock-screen dialogue is messed.

Thank you!

**Comment by mtwebster** [comment]
Hi,  1080 is *not* considered hidpi - in hidpi mode that means your effective display size is only 960 x 540 - smaller than the default size of many programs.

**Comment by wgnann** [comment]
Oh, my fault.

I didn't read the definition about hidpi. I thought my display was high dpi because its size is 15.6 inches, but its resolution is 1080p. Is there anything I can do to increase the dpi to something less than 200%?

**Comment by leigh123linux** [comment]
You need to reset the hidpi setting back to "normal" as it relates to scaling, not dpi.
Why do you need to change dpi?

https://wiki.archlinux.org/index.php/Xorg#Display_size_and_DPI
