### ISSUE TITLE
keyboard@cinnamon.org not react to switching layouts after "ibus restart"

### ISSUE THREAD

**Issue by SerCeMan** [linuxmint/Cinnamon#4013]
After executing "ibus restart", keyboard@cinnamon.org does not react to switching layouts and layout item removes from panel

**Comment by Vahan86** [comment]
@SerCeMan, is this still an issue for you with Cinnamon 3?

**Comment by SerCeMan** [comment]
I haven't seen this bug for awhile. So it is probably worth closing now.
