### ISSUE TITLE
LP / PLP setup Backgrounds need options

### ISSUE THREAD

**Issue by ghost** [linuxmint/Cinnamon#4015]
Landscape 16:9
Portrait 16:9

dual monitor. the desktop background software isnt capable of setting a. ) a wallpaper per monitor and b.) rotating the wallpaper per monitor.

The stable but ( old ) xfce manages this, however I think it does not manage to alternate the monitor aspect dependent on portrait or landscape. I think this is an area where Cinnamon could be better

Thanks

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html
