### ISSUE TITLE
Notifications fail with JS ERROR: RangeError: invalid language tag

### ISSUE THREAD

**Issue by marcvinyals** [linuxmint/Cinnamon#4024]
Cinnamon-2.4 has trouble processing Freedesktop notifications. When running e.g.

```
notify-send "meh"
```

but also if an application such as rhythmbox or pidgin is sending a notification, instead of the notification displaying I get the following error in ~/.xsession-errors:

(cinnamon:28266): Cjs-WARNING **: JS ERROR: RangeError: invalid language tag: %l:%M %p
Notification.prototype.update@/usr/share/cinnamon/js/ui/messageTray.js:590
Notification.prototype._init@/usr/share/cinnamon/js/ui/messageTray.js:521
Notification@/usr/share/cinnamon/js/ui/messageTray.js:422
NotificationDaemon.prototype._notifyForSource@/usr/share/cinnamon/js/ui/notificationDaemon.js:401
NotificationDaemon.prototype.NotifyAsync/<@/usr/share/cinnamon/js/ui/notificationDaemon.js:385
_proxyInvoker/asyncCallback@resource:///org/gnome/gjs/modules/overrides/Gio.js:90

Commenting out line 590 in /usr/share/cinnamon/js/ui/messageTray.js fixes the problem, and so does removing the argument to the call to toLocaleTimeString(). Note: this is currently line 591 in the master branch.

In fact, according to the spidermonkey documentation at https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleTimeString, this function expects a locale, not a time format.

This may be related to the following cjs unit test failing in my system:
testToLocaleDateString
from https://github.com/linuxmint/cjs/blob/master/installed-tests/js/testLocale.js

I previously reported this issue at https://bugs.gentoo.org/show_bug.cgi?id=545772

**Comment by Krishath** [comment]
+1

**Comment by perfect7gentleman** [comment]
deleted line 591, now notifications work. Gentoo, testing, up-to-date.

**Comment by Vahan86** [comment]
@marcvinyals, is this still an issue for you in Cinnamon 3?

**Comment by marcvinyals** [comment]
No longer an issue; this was fixed in #4673.

**Comment by marcvinyals** [comment]
No longer an issue; this was fixed in #4673.

**Comment by Vahan86** [comment]
@marcvinyals, thanks for reply. In this case can you please close this issue?
