### ISSUE TITLE
Menu entries are not displayed when .desktop files are not stored under /usr/share/applications

### ISSUE THREAD

**Issue by DiegoQueiroz** [linuxmint/Cinnamon#4026]
According to the FreeDesktop.org specification (see http://standards.freedesktop.org/menu-spec/latest/ar01s02.html), it should be OK to store .desktop files into any folder listed in $XDG_DATA_DIRS/applications (like /usr/local/share/applications, for example).

But Cinnamon seems to only recognize what is stored under /usr/share/applications and ~/.local/share/applications.

Utilities like "update-desktop-database" and "gtk-update-icon-cache" seem to properly scan all directories in $XDG_DATA_DIRS and update the cache following the FreeDesktop.org standard, but Cinnamon does not recognize them anyway. 

Is this behavior an issue, or it was done by design?

I am using Linux Mint 17.1 64-bit with Cinnamon 2.4.7+rebecca.
This issue was also discussed at https://github.com/sqlitebrowser/sqlitebrowser/pull/248

**Comment by DiegoQueiroz** [comment]
Any updates on this?

**Comment by Vahan86** [comment]
@DiegoQueiroz, is this still an issue in Cinnamon 3.0.x?

**Comment by DiegoQueiroz** [comment]
I am not sure. I do not have it installed right now to test. ;/
