### ISSUE TITLE
Leaking Nemo

### ISSUE THREAD

**Issue by KAMI911** [linuxmint/Cinnamon#4028]
It seems there is a leaking bug in Nemo. I am using LM 17.1 on my laptop and suspend and hibernate it between my work sessions. After some time period Nemo becomes CPU hog and memory hungry application like:

My Nemo packages are:
ii  nemo                                        2.4.5+rebecca                                       amd64        file manager and graphical shell for Cinnamon
ii  nemo-data                                   2.4.5+rebecca                                       all          data files for nemo
ii  nemo-dropbox                                2.4.0+rebecca                                       amd64        Dropbox integration for Nemo
ii  nemo-emblems                                2.4.3+rebecca                                       all          Change a folder or file emblem
ii  nemo-fileroller                             2.4.0+rebecca                                       amd64        File Roller integration for Nemo
ii  nemo-folder-color-switcher                  1.0.3                                               all          Change a folder color
ii  nemo-share                                  2.4.0+rebecca                                       amd64        Nemo extension to share folder using Samba
ii  python-nemo                                 2.4.1+rebecca                                       amd64        Python binding for Nemo components

Laptop is HP ProBook 6560b / VGA: Seymour [Radeon HD 6400M/7400M Series] with Open Source driver: xserver-xorg-video-radeon                   1:7.3.0-1ubuntu3.1

Linux Mint 17.1 Rebecca \n \l

Linux Godzilla 3.16.0-31-generic #43~14.04.1-Ubuntu SMP Tue Mar 10 20:13:38 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Some "top" output are:
13675 kami      20   0 12,008g 0,010t  49020 D  20,2 67,0   2514:15 nemo

13675 kami      20   0 12,008g 0,010t  48708 D   3,2 67,0   2514:18 nemo

 3305 kami      20   0 5266976 3,736g  34072 R 101,9 23,9 265:50.93 nemo 

If you need more information, do not hesitate to ask.

**Comment by JosephMcc** [comment]
This isn't a Cinnamon issue and belongs on the Nemo github page.
