### ISSUE TITLE
Win + space for switching keyboard layout works in one direction only

### ISSUE THREAD

**Issue by xhpohanka** [linuxmint/Cinnamon#4029]
I'm trying Cinnamon 2.4.7 DE on Arch linux.  As I use two keyboard layouts I need a shortcut to switch them. I would prefere `alt+shift` but as "onKeyRelease" won't work here due to Xorg limitation and it would replace many of other bindings I got used to `win+space` in gnome. 
Unfortunately when I select `win+space` shortcut it works only to change from first to second (English to Czech in my case) layout. When I'm on the second one the shortcut does nothing and more over the `space` is recognized and normally send to active application.
On the same computer this shortcut works as expected using Gnome3.

**Comment by xhpohanka** [comment]
I would like to confirm that the bug persists in Cinnamon 2.6. I'm a bit surprised that there is no other people complaining. Isn't it just Arch specific issue?

**Comment by xhpohanka** [comment]
Any news here? It is really unpleasant for users with multiple layouts to use mouse to switch the layout.

**Comment by itay-grudev** [comment]
I have that too. Official Cinnamon on top of the latest Arch.

**Comment by xhpohanka** [comment]
Still the same in Cinnamon 2.8...

**Comment by Elemag** [comment]
Well, I have the very same issue and I am also running Arch. And it appears in both Cinnamon and KDE.

However, I've found out that when you swap the main layout with the secondary, it starts working.

**Comment by Elemag** [comment]
This is the main problem: https://bugs.freedesktop.org/show_bug.cgi?id=89038

**Comment by Vahan86** [comment]
@xhpohanka, is this issue still relevant to Cinnamon 3?

**Comment by xhpohanka** [comment]
Seems to be fixed now, thanks...

**Comment by Vahan86** [comment]
@xhpohanka, thanks for reply. In this case can you please the issue?

**Comment by ahmafi** [comment]
Seems like an old issue, but I still have it in Linux Mint 20.2
