### ISSUE TITLE
gtk 3.16 broke cinnamon ..

### ISSUE THREAD

**Issue by ringo32** [linuxmint/Cinnamon#4032]
http://i.imgur.com/vbLmOpi.png

in Cinamon-session gnome over used adwaita-xml has taken is not a problem
But this is virtualbox offcourse,  but after gtk 3.16 cinnamon broke.

in 2d renderingmode i can access some config and dit reboot but still of the same.

somehow gtk 3.16 broke cinnamon

this is virtualbox offcourse, Manjaro Linux in unstable. but sync with Arch-stable repo.

**Comment by dalcde** [comment]
Try this: https://github.com/linuxmint/muffin/pull/185

**Comment by leigh123linux** [comment]
or https://github.com/linuxmint/cinnamon-session/commit/70893dc7a32fb983f44c8e9be07ffe65baf6bbd3

**Comment by dalcde** [comment]
#4039
