### ISSUE TITLE
GNOME 3.16 meta-thread

### ISSUE THREAD

**Issue by dalcde** [linuxmint/Cinnamon#4039]
# Known issues and solutions
GNOME 3.16 is known to break Cinnamon in three ways. Both are fixed in Cinnamon master. Below documents temprorary fixes users can take to make their systems working, and the last section documents the proper fixes package maintainers (and more sophisticated users) should use.

### Clutter crashing
Clutter defaults to using Wayland as its backend, but Cinnamon wants X11. The CLUTTER_BACKEND environment variable has to be set to x11 instead. This is fixed in Cinnamon master https://github.com/linuxmint/cinnamon-session/commit/70893dc7a32fb983f44c8e9be07ffe65baf6bbd3, and can be locally solved by running (as root)

````
echo -e '#!/bin/sh\nexport CLUTTER_BACKEND=x11' > /etc/X11/xinit/xinitrc.d/cinnamonfix.sh
chmod 755 /etc/X11/xinit/xinitrc.d/cinnamonfix.sh
````
You can also add the "export CLUTTER_BACKEND=x11" line to your ~/.xinitrc (before exec cinnamon-session), if you are using startx. Symptoms of this issue include the following line in the log files:
````
Clutter:ERROR:x11/clutter-stage-x11.c:1276:clutter_x11_get_stage_window: assertion failed: (CLUTTER_IS_STAGE_X11 (impl))
````
or in fact any ERROR (not WARNING) that mentions clutter and x11

### Muffin crashing
GNOME has removed all the metacity themes it used to ship with (eg. Adwaita). If those are the only themes you've got, you are left with no metacity themes and muffin will refuse to start. This can be solved by installing some metacity theme (which will be automatically recognized by muffin). An easy solution would be to install the "metacity" package itself, which comes with a few (rather ugly) themes. After you can login, you can spend your time to pick your favorite theme and set it through cinnamon-settings. Symptops include log lines like
````
Window manager warning: Failed to load theme "Adwaita": Failed to find a valid file for theme Adwaita
Window manager warning: Failed to load theme "Simple": Failed to find a valid file for theme Simple
...
Window manager error: Could not find a theme! Be sure /usr/share/themes exists and contains the usual themes.
````

### Ugly window borders
Due to changes in how Gtk works, the window titles in most themes become black boxes. This is since metacity themes usually say "use the background color from your gtk theme for this", but gtk no longer returns the correct value. You can solve this for a specific theme by hardcoding the color instead of asking gtk to provide it.

The themes specifications are located at
````
/usr/share/themes/<theme name>/metacity-1/metacity-theme-<n>.xml
````
where \<n\> is usually 3. If there are multiple such files, edit the one with the largest number.

You will see some lines saying "gtk:bg[NORMAL]". Replace this with the background color of regular gtk widgets in hex colour code. You can find the color code at
````
/usr/share/themes/<theme name>/gtk-3.0/
````
It is usually specified in gtk.css or gtk-main.css in the form of
````
@define-color theme_bg_color #deaded
````
where #deaded is the color you want. Most other gtk substitutions work, eg. gtk:fg[THING] usually works, and gtk:bg[INSENSITIVE] works sometimes, depending on theme. If something else breaks, use your imagination to figure out what color it should be.

### Broken Cinnamon Settings
Several changes in Gtk 3.16 broke Cinnamon settings in several ways. The fixes are as follows:
https://github.com/linuxmint/Cinnamon/commit/1e3f31e0d4c5724d298a3dae70b3b19e0a1835b3
https://github.com/linuxmint/Cinnamon/commit/5c8872c078afe418e37cacd746bf663ee7b2bf6a

## Long-term proper fixes for package maintainers and people willing to dive deep
The first issue is fixed by https://github.com/linuxmint/cinnamon-session/commit/70893dc7a32fb983f44c8e9be07ffe65baf6bbd3, which sets CLUTTER_BACKEND=x11 in the cinnamon launch script; and the other two are solved by https://github.com/linuxmint/muffin/commit/417ab781aae40562718a023c9f48f07e7222e59c. It adds a fallback theme to muffin so that it doesn't crash, and loads existing themes properly without the monkey-patch for individual themes. Distro packagers should apply this two commits as patches to their cinnamon packages.

# Other issues
None as far as I know! Report other issues below if any, or if any of the above fixes don't work. Keeping all issues here instead of distributing it in different bug reports will help people upgrading to 3.16 more easily.

**Comment by JosephMcc** [comment]
Think it's safe to close this now. Gtk3.20 is the new problem ;)
