### ISSUE TITLE
scid_vs_pc-4.14 HOWTO install on Linux Mint 17.1 Cinnamon?

### ISSUE THREAD

**Issue by nimzotech** [linuxmint/Cinnamon#4046]
Hello World!

I am attempting (but fail miserably) to install Scid vs. PC an open-source chess database program:
http://scidvspc.sourceforge.net

I followed the install instructions from
http://scidvspc.sourceforge.net/#toc4
AND
http://www.linuxx.eu/2012/11/scid-vs-pc-installation-guide-ubuntu.html

One user via the linuxmint forums has found a solution but did not provide instructions regarding importing the 'MAKEFILE'

"Cinnamon on this regard: you can't create a proper makefile either with tcl8.5 or tcl8.6 without triggering "fatal mistakes". I had to import a makefile from LMDE to install on Qiana, which is not easy for everyone".

Would someone guide me please?

I get stuck while running the following command
auto-apt run ./configure

_______________________________________
The result i get is
Location of "tk.h" : not found

P.S.

Scid vs. PC requires Wish (Tcl/Tk) 8.5 or later (though 8.5.10 has nasty bugs and should be avoided), and a C++ compiler .
Example packages required include "tcl, tk, tcl-devel, tk-devel" and "gcc-c++ , libstdc++"; but of course will vary with your distribution.

As far I know I have installed these guys...

**Comment by dalcde** [comment]
Not a cinnamon issue... Are you sure you installed the tk8.5-**dev** and tcl8.5-dev packages?

**Comment by nimzotech** [comment]
Yes, I have followed the following guide: http://www.linuxx.eu/2012/11/scid-vs-pc-installation-guide-ubuntu.html

**Comment by nimzotech** [comment]
I get stuck while running the following command
auto-apt run ./configure

The result i get is
Location of "tk.h" : not found

**Comment by nimzotech** [comment]
after the command
apt-get install tk8.6-dev tk8.6 lbgcj15-dev
I get: unable to lcate package libgcj15-dev

**Comment by GLolol** [comment]
Try `libgcj14-dev` for Linux Mint 17.x/Ubuntu 14.04.

**Comment by nimzotech** [comment]
GLolol - You're the man!

lbgcj14-dev worked!

Pardon my ignorance - makes sense if Mint 17 is based on Ubuntu 14 distro.

Cheers!
