### ISSUE TITLE
dnd: recent@cinnamon.org to allow drag-n-drop, e.g. for mail attachments

### ISSUE THREAD

**Issue by stefan123t** [linuxmint/Cinnamon#4049]
I would probably use the recent Applet a bit more frequently if you could add the following feature. 
The recent@cinnamon.org Applet should allow drag-n-drop, e.g. for mail attachments etc. pp.

Kind regards,
Stefan

**Comment by dalcde** [comment]
Can you explain a bit more?

**Comment by stefan123t** [comment]
The applet populates itself with the documents I have recently opened or worked with. When i write an Email instead of opening a file dialog I would prefer to drag them from this list into my mail for attachements. Same for copying, renaming/moving (or deleting) it would be nice to drag them from the recent app eg. into Nemo.

Kind regards,
Stefan

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html
