### ISSUE TITLE
Desktop Icons Not Working

### ISSUE THREAD

**Issue by chazdgg** [linuxmint/Cinnamon#405]
Cinnamon 1.3.1.  This may be a bug, or perhaps it can be fixed. When I double click an Icon on my Desktop, the program does not open. I can go down to the Menu which works fine, or right click the icon on the Desktop to open the program. Any suggestions or is this a bug?

**Comment by Aspect9** [comment]
my desktop icons revert back to gnome-theme, and they dont seem to change back when tweaked. 
whats going on?
