### ISSUE TITLE
Part of Steam window rendered over the desktop

### ISSUE THREAD

**Issue by plata** [linuxmint/Cinnamon#4050]
First things first: I'm completely unsure if this is a Cinnamon issue or a Steam issue or an issue of Steam on Cinnamon.
Anyway here's what happened: I opened Steam, after minimizing the window, a part of Steam still is shown. It is also not possible to access any buttons behind that Steam window part. Before it happened, the "Midweek Madness"-window was shown.

![steam part](https://cloud.githubusercontent.com/assets/3973260/7143221/77bf7218-e2de-11e4-8e98-d0d851cf5e53.png)

**Comment by Vahan86** [comment]
@plata, does this issue still occur in Cinnamon 3.0.x?

**Comment by plata** [comment]
I can't tell. Using KDE right now.
