### ISSUE TITLE
Bluetooth settings missing from hardware section of System Settings

### ISSUE THREAD

**Issue by ricelid** [linuxmint/Cinnamon#4052]
I see no bluetooth button in system settings.
However, when I run `bluetooth-wizard` from the command line, I can find and pair with new bluetooth devices just fine.
However, without the applet and without the settings, I can't manage bluetooth connections.

![settings](https://cloud.githubusercontent.com/assets/421339/7152302/e5b939e8-e2ed-11e4-983e-96e9f68fe206.png)

This is on Cinnamon 2.2.16

**Comment by leigh123linux** [comment]
What distro are you using? (some haven't packaged cinnamon-bluetooth).

**Comment by ricelid** [comment]
Ubuntu. Strange, my other ubuntu machine has it but for some reason on this one I had to:
`$ sudo apt-get install cinnamon-bluetooth`
Thanks for the quick reply.

**Comment by SEETHAMRAJU** [comment]
hello how r u who r u

**Comment by JoelVaz** [comment]
Hello open terminal and type
sudo apt-get install blueberry
