### ISSUE TITLE
No sound in headphones in a second jack

### ISSUE THREAD

**Issue by ashumkin** [linuxmint/Cinnamon#4054]
I have a Dell XPS L702X laptop. It has two 3.5" headphone jacks. When I plug headphones to the "first" jack, sound disappers from speakers and goes to headphones. That is ok, as expected. But when I plug headphones to the second jack.  Sound disappears from speakers and does NOT appear in headphones.
That is annoying. Expecially that the second jack works correctly in Gnome (3.10, 3.14), Classic Gnome (3.14), and even (I do not use it but I've tested it) in Openbox (3.5.2).

Fedora (RFRemix) 21, Cinnamon 2.4.6

**Comment by ManIVIctorious** [comment]
The sound settings and sound applet have seen a lot of work in the last two cinnamon iterations, is this issue still relevant in cinnamon 3.0?

**Comment by ashumkin** [comment]
Thank you for remind ))
The issue is fixed.
P.S. Cinnamon v3.0.7, Fedora (RFRemix) 23
