### ISSUE TITLE
Login screen arrow navigation issue with no-password logins

### ISSUE THREAD

**Issue by PwnzorBot4000** [linuxmint/Cinnamon#4059]
Steps to reproduce:
Let there be three accounts, named A, B, and C.
Set a password for A, and leave B and C without password - or add them to the group 'nopasswdlogin'.
Login to A, then logout or switch user, so that you reach the user selection screen.
Try going to B or C using the arrow keys.
Result:
The first user account that the arrow keys will navigate to will automatically login, preventing the user from navigating to a different account, and perhaps logging in to an unwanted account.
Possible solution:
It seems to me that the login screen's reactions to keyboard events and mouse events have to be split and dealt with differently. In the general case, I would expect clicking an account with the mouse to result in a login - as it does now-, but navigating with the arrow keys on an account without need for a password to wait for me to press 'Enter' to login.
System info:
Linux Mint 17.1 64-bit, Cinnamon 2.4.8.

**Comment by dalcde** [comment]
Please file this against mdm: http://github.com/linuxmint/mdm
