### ISSUE TITLE
Keyboard layout not saved

### ISSUE THREAD

**Issue by martinrotter** [linuxmint/Cinnamon#4061]
I have set two layouts - USA and CZ (Czech). I put CZ keyboard layout on top to be the first in list of activated layouts.

But still, after restart, USA layout is selected.

```
% pac-lst|grep cinnamon
cinnamon 2.4.8-1
cinnamon-control-center 2.4.2-3
cinnamon-desktop 2.4.2-1
cinnamon-menus 2.4.1-1
cinnamon-screensaver 2.4.2-1
cinnamon-session 2.4.3-2
cinnamon-settings-daemon 2.4.3-1
cinnamon-translations 2.4.4-1
```

**Comment by martinrotter** [comment]
Interestingly, issue goes away if I remove English (USA) layout and add English (Brittain) layout.

**Comment by hultberg** [comment]
I have had this same issue with Debian Jessie on my laptop but not on my desktop computer. By running `setxkbmap` my preferred keyboard layout gets instantly selected.

**Comment by martinrotter** [comment]
Okay, anyway, issue solved. Closing.
