### ISSUE TITLE
Macbook brightness keys do not work in Cinnamon resume screen

### ISSUE THREAD

**Issue by gordon-morehouse** [linuxmint/Cinnamon#4062]
### WHAT ACTUALLY HAPPENS

Hello, I've observed this behavior on a Macbook4,1  (2008ish Core 2 Duo) on Linux Mint 17.1 "Rebecca," 64-bit. After putting the laptop to sleep, upon resuming but before entering a password, the brightness adjustment controls on the keyboard have no effect.

This is particularly problematic if one has used the brightness controls to shut off the screen in order to save battery power.

### WHAT I EXPECT TO HAPPEN

I see two solutions to this in supposed order of increasing difficulty.

1. If the screen backlight has been shut off by brightness controls, after resuming from sleep, Cinnamon should set the brightness to the minimum "on" setting so the user can see the screen.
2. The brightness control keys should work in the lock screen.

### ADDITIONAL INFO

To find your Apple Mac system type in Linux, run `sudo dmidecode -s "system-product-name"` on the command line.

**Comment by gordon-morehouse** [comment]
systemd-backlight or sysvinit-backlight might be a workaround that'd close this? See http://askubuntu.com/a/227553 and somewhat-related https://bugs.launchpad.net/hundredpapercuts/+bug/1270579 ...?

**Comment by Vahan86** [comment]
@gordon-morehouse, is this still an issue for you in Cinnamon 3.0 (Linux Mint 18)?

**Comment by gordon-morehouse** [comment]
Hi there, I've switched to Lubuntu on this device as it was already fairly slow on Mint 17.
