### ISSUE TITLE
add plugin or feature for ColorFilter

### ISSUE THREAD

**Issue by Hanmac** [linuxmint/Cinnamon#4064]
i dont know how it might be possible, but i would like to have a plugin or feature to colorize the desktop like with http://wiki.compiz.org/Plugins/Colorfilter it also would be nice if it can be set different for different monitor displays

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html
