### ISSUE TITLE
Cinnamon desktop uses more battery

### ISSUE THREAD

**Issue by KAMI911** [linuxmint/Cinnamon#4071]
It seems Cinnamon desktop uses more battery power than Unity on some machines. The lifetime on battery is nearly half compared to Ubuntu on those machine:
powertop:
                Usage       Events/s    Category       Description
            254,8 ms/s      41,1        Process        nemo -n
             25,9 ms/s      46,5        Process        cinnamon --replace
top:
 3394 kami      20   0 1923316 523184  60052 S 101,3  3,2 108:20.24 nemo

**Comment by dalcde** [comment]
It is unlikely the cinnamon uses a lot of your battery (from my experience, even switching to a low-resource wm like openbox hardly makes a difference in battery life). Are you running Cinnamon on Mint? Is laptop-mode-tools installed?

**Comment by KAMI911** [comment]
I am using Linux Mint 17.1,
Linux Godzilla 3.16.0-34-generic #47~14.04.1-Ubuntu SMP Fri Apr 10 17:49:16 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by dalcde** [comment]
Is laptop-mode-tools installed on Mint? And on Ubuntu?

Also, try running Unity on Mint and see what results you get (You can also try Cinnamon on Ubuntu, but Cinnamon found on Ubuntu is a rather old version unless you use the PPAs). It's more likely to be a Mint vs Ubuntu thing than a Cinnamon vs Unity thing.

**Comment by KAMI911** [comment]
Hi,
I have installed the laptop-mode-tools.
Output in syslog:
Apr 24 10:31:44 Godzilla laptop-mode: Laptop mode 
Apr 24 10:31:44 Godzilla laptop-mode: enabled, active [unchanged]
Apr 24 10:31:44 Godzilla laptop-mode: Laptop mode 
Apr 24 10:31:44 Godzilla laptop-mode: enabled, active [unchanged]
Apr 24 10:31:44 Godzilla laptop-mode: Laptop mode 
Apr 24 10:31:44 Godzilla laptop-mode: enabled, active
Apr 24 10:31:45 Godzilla laptop-mode: Laptop mode 
Apr 24 10:31:45 Godzilla laptop-mode: enabled, active
Apr 24 10:31:46 Godzilla laptop-mode: Laptop mode 
Apr 24 10:31:46 Godzilla laptop-mode: enabled, active [unchanged]
Apr 24 10:31:47 Godzilla laptop-mode: Laptop mode 
Apr 24 10:31:47 Godzilla laptop-mode: enabled, active [unchanged]
Apr 24 10:31:48 Godzilla laptop-mode: Laptop mode 
Apr 24 10:31:48 Godzilla laptop-mode: enabled, active [unchanged]
Apr 24 10:31:49 Godzilla laptop-mode: Laptop mode 
Apr 24 10:31:49 Godzilla laptop-mode: enabled, active [unchanged]
Apr 24 10:31:50 Godzilla laptop-mode: Laptop mode 
Apr 24 10:31:50 Godzilla laptop-mode: enabled, active [unchanged]
Apr 24 10:31:51 Godzilla laptop-mode: Laptop mode 
Apr 24 10:31:51 Godzilla laptop-mode: enabled, active [unchanged]
Apr 24 10:31:57 Godzilla laptop-mode: Laptop mode 
Apr 24 10:31:57 Godzilla laptop-mode: enabled, active [unchanged]
Apr 24 10:32:00 Godzilla laptop-mode: Laptop mode 
Apr 24 10:32:00 Godzilla laptop-mode: enabled, active [unchanged]
Apr 24 10:32:19 Godzilla laptop-mode: Laptop mode 
Apr 24 10:32:19 Godzilla laptop-mode: enabled, active [unchanged]
Apr 24 10:32:22 Godzilla laptop-mode: Laptop mode 
Apr 24 10:32:22 Godzilla laptop-mode: enabled, active [unchanged]
Apr 24 10:32:23 Godzilla laptop-mode: Laptop mode 
Apr 24 10:32:23 Godzilla laptop-mode: enabled, active [unchanged]
Apr 24 10:32:23 Godzilla laptop-mode: Laptop mode 
Apr 24 10:32:23 Godzilla laptop-mode: enabled, not active
Apr 24 10:32:26 Godzilla laptop-mode: Laptop mode 
Apr 24 10:32:26 Godzilla laptop-mode: enabled, not active [unchanged]
Apr 24 10:32:26 Godzilla laptop-mode: Laptop mode 
Apr 24 10:32:26 Godzilla laptop-mode: enabled, not active [unchanged]
Apr 24 10:32:46 Godzilla laptop-mode: Laptop mode 
Apr 24 10:32:46 Godzilla laptop-mode: enabled, not active [unchanged]
Apr 24 10:33:08 Godzilla laptop-mode: Laptop mode 
Apr 24 10:33:08 Godzilla laptop-mode: enabled, not active [unchanged]
Apr 24 10:33:30 Godzilla laptop-mode: Laptop mode 
Apr 24 10:33:30 Godzilla laptop-mode: enabled, not active [unchanged]
Apr 24 10:33:52 Godzilla laptop-mode: Laptop mode 
Apr 24 10:33:52 Godzilla laptop-mode: enabled, not active [unchanged]
Apr 24 10:34:14 Godzilla laptop-mode: Laptop mode 
Apr 24 10:34:14 Godzilla laptop-mode: enabled, not active [unchanged]
Apr 24 10:34:36 Godzilla laptop-mode: Laptop mode 
Apr 24 10:34:36 Godzilla laptop-mode: enabled, not active [unchanged]
Apr 24 10:34:58 Godzilla laptop-mode: Laptop mode 
Apr 24 10:34:58 Godzilla laptop-mode: enabled, not active [unchanged]
Apr 24 10:35:42 Godzilla laptop-mode: Laptop mode 
Apr 24 10:35:42 Godzilla laptop-mode: enabled, not active [unchanged]
Apr 24 10:36:04 Godzilla laptop-mode: Laptop mode 
Apr 24 10:36:04 Godzilla laptop-mode: enabled, not active [unchanged]
Apr 24 10:36:26 Godzilla laptop-mode: Laptop mode 
Apr 24 10:36:26 Godzilla laptop-mode: enabled, not active [unchanged]
Apr 24 10:36:48 Godzilla laptop-mode: Laptop mode 
Apr 24 10:36:48 Godzilla laptop-mode: enabled, not active [unchanged]
Apr 24 10:37:28 Godzilla laptop-mode: Laptop mode 
Apr 24 10:37:28 Godzilla laptop-mode: enabled, not active
Apr 24 10:37:28 Godzilla laptop-mode: Laptop mode 
Apr 24 10:37:28 Godzilla laptop-mode: enabled, not active
Apr 24 10:37:28 Godzilla laptop-mode: Laptop mode 
Apr 24 10:37:28 Godzilla laptop-mode: enabled, not active
Apr 24 10:37:28 Godzilla laptop-mode: Laptop mode 
Apr 24 10:37:28 Godzilla laptop-mode: enabled, not active
Apr 24 10:37:30 Godzilla laptop-mode: Laptop mode 
Apr 24 10:37:30 Godzilla laptop-mode: enabled, not active [unchanged]
Apr 24 10:37:31 Godzilla laptop-mode: Laptop mode 
Apr 24 10:37:31 Godzilla laptop-mode: enabled, not active [unchanged]
Apr 24 10:37:53 Godzilla laptop-mode: Laptop mode 
Apr 24 10:37:53 Godzilla laptop-mode: enabled, not active [unchanged]
Apr 24 10:38:38 Godzilla laptop-mode: Laptop mode 
Apr 24 10:38:38 Godzilla laptop-mode: enabled, not active [unchanged]
Apr 24 10:39:00 Godzilla laptop-mode: Laptop mode 
Apr 24 10:39:00 Godzilla laptop-mode: enabled, not active [unchanged]
Apr 24 10:39:44 Godzilla laptop-mode: Laptop mode 
Apr 24 10:39:44 Godzilla laptop-mode: enabled, not active [unchanged]
Apr 24 10:40:06 Godzilla laptop-mode: Laptop mode 
Apr 24 10:40:06 Godzilla laptop-mode: enabled, not active [unchanged]


It looks like nemo drains the resources and eats the 50-100 power of one CPU core.
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND     
 3984 kami      20   0 1186072  87656  68828 S  83,8  0,5   2:11.70 nemo        

I have removed nemo-dropbox as additionally installed component, but I have same problem after restart.

**Comment by leigh123linux** [comment]
Might be related to https://github.com/linuxmint/nemo/issues/671

**Comment by Vahan86** [comment]
@KAMI911, is this still an issue for you with Cinnamon 3?

**Comment by Vahan86** [comment]
@JosephMcc, can we close this issue?
