### ISSUE TITLE
using cinnamon with fglrx does send all notifications at once

### ISSUE THREAD

**Issue by Hanmac** [linuxmint/Cinnamon#4073]
i tested it with normal radeon driver:
session is locked and monitor-power is off
still does send notifications (to hear it with the acoustic signal)
and when i enter the session again i can see what notifications i did miss

using fglrx driver that does happen:
session is locked and monitor-power is off
does not send notifications (i need to check that)
but when i enter the session again all notifications does trigger at once
(to hear it with many signals at once)
and all notifications does popup even if they should not

**Comment by Vahan86** [comment]
@Hanmac, is this still an issue for you with Cinnamon 3.0.x?

**Comment by Hanmac** [comment]
@Vahan86: my system did kick out the fglrx driver and force me to use the radeon one.

So I can't say if it still would happen.

Hm but you can close it for now I think.

**Comment by Vahan86** [comment]
@Hanmac, thank you for your prompt response. In this case, could you please close the issue? Thank you.
