### ISSUE TITLE
Mono apps show wrong icon in taskbar panel

### ISSUE THREAD

**Issue by StephenMcConnel** [linuxmint/Cinnamon#4079]
![screenshot from 2015-04-24 18 14 46](https://cloud.githubusercontent.com/assets/2228246/7330129/93535f12-eaae-11e4-86e7-c3ac9046f34a.png)
As shown by the image I've uploaded, the four independent programs are showing only two icons in the taskbar panel.  The first program and fourth program across the panel should have different icons than what is shown.  The second program caused the icon of the first program to change, and the fourth program somehow picked up the icon of the third program instead of showing its own.  (All of these programs use WinForms for portability with Windows instead of GTK like many Linux-centric Mono programs.)
Any advice on how the icon is chosen for display, and how a program should set things up would be appreciated.  One at a time, the programs work fine and show the proper icon.  On Ubuntu/Unity the proper icon is maintained: this behavior appears to affect only Cinnamon.

**Comment by Naruki** [comment]
I believe this is the same problem as this bug:
https://github.com/linuxmint/Cinnamon/issues/3814

**Comment by Vahan86** [comment]
@StephenMcConnel, is this still an issue in Cinnamon 3.0.x?

**Comment by Vahan86** [comment]
@JosephMcc, can we close the issue?
