### ISSUE TITLE
Notification-Center

### ISSUE THREAD

**Issue by ManIVIctorious** [linuxmint/Cinnamon#4082]
Since two weeks I get desktop notifications ("process started" and "process ended") and I just can't find out which program is sending these. 

It would be nice if cinnamon could monitor the applications, which are sending the notifications and provide a switch to turn them off.

**Comment by collinss** [comment]
That sounds like my Command Launcher applet. If it is, you can disable it from settings.

**Comment by ManIVIctorious** [comment]
@collinss : thanks, since I normally start applications via runner (alt+f2) I would never have thought about that^^

But I still think a better configuration for notifications would be a great improvement

**Comment by harogaston** [comment]
@dalcde Think this issue is too vague. What exactly is the feature requested here? Maybe some clarification from the OP @ManIVIctorious ... Otherwise this could be closed.

**Comment by ManIVIctorious** [comment]
Oh, sorry that it took so long^^
Just to be a little more precise: I would like to be able to switch notifications of defined applications off or to prevent them from saving their notifications to the notification tray. But I don't really know if this is possible at all. Is it possible to determin which application sends which notification?

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html
