### ISSUE TITLE
mousewheel zoom after switching display resolution

### ISSUE THREAD

**Issue by kaefert** [linuxmint/Cinnamon#4088]
After switching from a beamer (lower resolution) to my two desktop-monitors, this is the picture I see when I use mousewheel zoom:
![screenshot from 2015-04-28 1220](https://cloud.githubusercontent.com/assets/1448723/7367658/561f06dc-eda1-11e4-9a81-f2dca92b89da.jpg)

I guess the resolution is only queried once after bootup, when I reboot after changing displays everything works again as expected

**Comment by Vahan86** [comment]
@kaefert, is this still an issue for you with Cinnamon 3.0?

**Comment by kaefert** [comment]
@Vahan86 I'm sorry, but I do not have access to a beamer right now, and therefore cannot test this.

**Comment by Vahan86** [comment]
@JosephMcc, can we close this issue since we don't have updated information on the issue existence?
