### ISSUE TITLE
Make use of the deskop entries additional applications actions

### ISSUE THREAD

**Issue by ManuelSchneid3r** [linuxmint/Cinnamon#4090]
Desktop entries contain cool actions to use. Use them to make cinnamon an even nicer experience e.g. by implemening jumplists.

**Comment by dalcde** [comment]
Can you please explain yourself? I have no idea what a jumplist is, what cool actions there are in desktop entries, and how the two ideas are related. At all.

**Comment by GLolol** [comment]
Per http://standards.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#extra-actions-identifier, .desktop files are allowed to specify custom actions. Cinnamon doesn't seem to show these.

**Comment by dalcde** [comment]
Thanks that was much more helpful. It doesn't seem difficult to implement, so it probably will happen sooner or later

**Comment by ManuelSchneid3r** [comment]
Thanks for the fast clearification while I was afk.

**Comment by JosephMcc** [comment]
This is now supported in the panel launcher applet in git master. With Firefox for example I can right click the panel launcher icon and have options for "Open a new window" and "Open a new private window"
