### ISSUE TITLE
Very hard to drag system tray

### ISSUE THREAD

**Issue by ghost** [linuxmint/cinnamon#4100]
If one tries to drag the system tray then, at least on my computer, most of the time it does not work. For most of the time, one ends up trigger stuff from the icons one is trying to drag.

(And, yes, I do have panel edit mode set to 'on.)

Linux Mint 17.1 x64, Cinnamon <latest public release.>

**Comment by JosephMcc** [comment]
It is hard to drag. There is very little empty space between the icons for you to get a hold of without triggering one. I find it easiest to grab it at the bottom but some more spacing in between would help.

**Comment by icarter09** [comment]
Closing due to original submitter is no longer present on github.
