### ISSUE TITLE
allow desktop icons to change with workspace

### ISSUE THREAD

**Issue by kobi2187** [linuxmint/Cinnamon#4108]
what user sees:
user switches to a different workspace, and has the links custom to that workspace show up in desktop (complete with their location on the desktop)

how it works:
every workspace may have a folder of its own, let's say 
~/workspaces/1
~/workspaces/2
~/workspaces/3
each contains links and files.
it means there are many desktops or that the desktop is interchangeable.
when changing workspaces, the links or files in that folder are shown, 
instead of the links in ~/Desktop.
the rationale is that different contexts all in one place clutter the workflow and focus for my current task. 
if i have 4 different contexts, say entertainment, development, reading, work 
then in every context or mode, i'll have 75% desktop clutter. (3 unrelated modes)

(I think this feature can be (user)hacked by making the desktop-folder be a hardlink to one of the workspace folders when switching to them. But I feel it would be better to implement it properly.
in essence, making the desktop folder a parameter, in the method that shows the desktop.

**Comment by ScooterTooterson** [comment]
`#!/bin/bash
# Workspace desktop image switcher WDIS 1.0
# Script to change the desktop image when switching workspaces.
# Tested on Linux Mint 13 'cinnamon'
desktop_dir="/home/username/.cinnamon/backgrounds/" # full path to images directory;
desktop_img[0]="Main.jpg"
desktop_img[1]="Coding.jpeg"
desktop_img[2]="Main.jpg"
desktop_img[3]="Music.jpeg"
# add more images if using more workspaces

setdesktop() {
   gsettings set org.gnome.desktop.background picture-uri "file://$desktop_dir$1"
   }
xprop -root -spy _NET_CURRENT_DESKTOP | (
   while read -r; do
      desk=${REPLY:${#REPLY}-1:1}
      setdesktop ${desktop_img[$desk]}
      gsettings set org.nemo.desktop show-desktop-icons false
      sed -i '/\(^XDG_DESKTOP_DIR="$HOME\/Desktop\)[^"]*"/s//\1'"$desk"'"/' /home/username/.config/user-dirs.dirs
      gsettings set org.nemo.desktop show-desktop-icons true
   done
   )`
This works!

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html
