### ISSUE TITLE
Hide Blueman status icon when bluetooth applet is present

### ISSUE THREAD

**Issue by dtrunk90** [linuxmint/Cinnamon#4113]
The Blueman status icon should be hidden if the bluetooth applet is present.
Some of the options from that status icon menu should be moved to the bluetooth applet menu if possible.

**Comment by NikoKrause** [comment]
I think this has been fixed. Can you check?

**Comment by clefebvre** [comment]
No, blueman is an alternative to blueberry. It shouldn't be installed by default, and if you install it, it should show.
