### ISSUE TITLE
Edge flip while screen is locked shows workspace(s)

### ISSUE THREAD

**Issue by mdjones325** [linuxmint/Cinnamon#4115]
This is in LM 17.1

When the screen is locked (grey screen, prompt for password) I can trigger the edge flip feature with the mouse. This allows the hidden workspaces to be momentarily visible. This is a privacy issue, and possibly security as well.

First bug report, please email me if I need to include more information

**Comment by harogaston** [comment]
Can't reproduce the issue on my system (17.1 as well). Maybe provide some more insights.

**Comment by Vahan86** [comment]
@mdjones325, is this still an issue for you in Cinnamon 3.0.x?

**Comment by JosephMcc** [comment]
The edge flip feature is no longer in the settings and isn't even working/supported anymore.
