### ISSUE TITLE
notifications in 24h format

### ISSUE THREAD

**Issue by two-dogs** [linuxmint/Cinnamon#4118]
i found one place only to change format, did so, still seeing format in 12h, everything else on cinnamon is default 24h, the app creating the notifications is 'knoversation' regardless, any notification from what ever source is still in 12h format, change made at line 252 of applet.js changed to 'let dateFormat = _("%H:%M");'

**Comment by dalcde** [comment]
Sorry what exactly is the issue?

**Comment by two-dogs** [comment]
On Tuesday, May 05, 2015 13:58:35 dalcde wrote:
> Sorry what exactly is the issue?
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/linuxmint/Cinnamon/issues/4118#issuecomment-99219956

i was wanting to see time-stamped notifications via notifications@cinnamon.org 
in 24hour format, i found what i thought was the line to edit #252 of 
applet.js and did make the change to %H:%M . 
no joy, notifications are still listing in 12hour format.

**Comment by dalcde** [comment]
>i was wanting to see time-stamped notifications via notifications@cinnamon.org
>in 24hour format, i found what i thought was the line to edit #252 of
>applet.js and did make the change to %H:%M .
>no joy, notifications are still listing in 12hour format.

Sorry I still don't see what the issue is. Do you want us to make an
option to display it in 24 hour format? Or are you just asking for
programming help?

**Comment by two-dogs** [comment]
On Tuesday, May 05, 2015 23:33:45 dalcde wrote:
> >i was wanting to see time-stamped notifications via
> >notifications@cinnamon.org in 24hour format, i found what i thought was
> >the line to edit #252 of applet.js and did make the change to %H:%M .
> >no joy, notifications are still listing in 12hour format.
> 
> Sorry I still don't see what the issue is. Do you want us to make an
> option to display it in 24 hour format? Or are you just asking for
> programming help?
> 
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/linuxmint/Cinnamon/issues/4118#issuecomment-99342582

yes to both, based on infomation provided by my earlier, should i be seeing 
24h format from notifications? or pls provide me a 
notiications@cinnamon.org/applet.js file with the 24h formatted time enabled. 
thnks

**Comment by collinss** [comment]
AFAIK, the time that is displayed in the notifications is based on your system locale. If your locale is set to use 24h time, than that is how it is displayed in the notification label. You could try changing locale, or look at /usr/share/cinnamon/js/ui/messageTray.js and hard-code the date format with your own string format codes.

**Comment by two-dogs** [comment]
....You could try changing locale, or look at /usr/share/cinnamon/js/ui/messageTray.js and hard-code the date format with your own string format codes...
tried above, no joy, set format to %H:%M , system/locate time is set to 24h, at every setting i can think of, as a matter of fact the only place i dont see time in 24h is in notifications, only thing i can think now is that he issue is specific to any kde app producing the notifications, although time on kde is also set 24hour, so far tweaking two locations no joy.

**Comment by harogaston** [comment]
I know this is not a support forum..but can you post you Language Settings? Or at least show how to reproduce the issue.The language setting you have will determine how date and time are formatted. Simple, even for the notifications applet time-stamp.

**Comment by brownsr** [comment]
If you change the 12/24 hour toggle in the date time settings it only affects the clock date time shown in the panel.  The timestamp in the notifications stays as set by the locale ( I believe).  It would be better if the two things stayed in sync i.e.  if the hours shown in the notifications tracks the hours setting in the date time settings.

**Comment by two-dogs** [comment]
from irc chat, .......................
 <glebihan> Two_Dogs, I can give you a workaround if you want
...................................
 <glebihan> Two_Dogs, in /usr/share/cinnamon/applets/notifications@cinnamon.org/applet.js, change line "let str = orig_time.toLocaleTimeString();" to let str = orig_time.toLocaleFormat('%T');

i did as shown and i am seeing 24hr format now on notifications
