### ISSUE TITLE
No JS module 'dbus' found in search path

### ISSUE THREAD

**Issue by ManuelSchneid3r** [linuxmint/Cinnamon#4121]
I cant add applets for the following reason

  error t=2015-05-06T14:47:21.741Z No JS module 'dbus' found in search path
trace t=2015-05-06T14:47:21.741Z 
<----------------
@/home/manuel/.local/share/cinnamon/applets/hamster@projecthamster.wordpress.com/applet.js:22
Extension.prototype._init@/usr/share/cinnamon/js/ui/extension.js:152
Extension@/usr/share/cinnamon/js/ui/extension.js:119
loadExtension@/usr/share/cinnamon/js/ui/extension.js:383
onEnabledAppletsChanged@/usr/share/cinnamon/js/ui/appletManager.js:197
---------------->
error t=2015-05-06T14:47:21.741Z [Applet "hamster@projecthamster.wordpress.com"]: Error importing applet.js from hamster@projecthamster.wordpress.com

**Comment by dalcde** [comment]
http://segfault.linuxmint.com/2014/08/attention-applet-desklet-extension-developers/

Bug the applet developer to fix their applet.

**Comment by border0464111** [comment]
Solution here : 
https://github.com/projecthamster/cinnamon-applet/issues/14
