### ISSUE TITLE
Some bugs with the intelligent panel hide feature 

### ISSUE THREAD

**Issue by brub2** [linuxmint/Cinnamon#4122]
Intellihide is now available with cinnamon nightly PPA, so I tested it. There are at least 2 bugs:

1) If I click on an empty desktop area (so no windows is actually selected), the panel hides.
2) If I close all windows on a workspace, the panel hides. Also, we can go to an empty workspace to have the same issue.

**Comment by brub2** [comment]
#1 seems to be fixed (with last nightly). However, I have new bugs:
3) If a window is moved above (a part of) the panel, it doesn't hide. It hides if we go to the panel edge with the mouse.  
4) Suppose that the panel is hidden by a (small) window. If this window is moved away, the panel remains hidden.
5) Suppose that the panel is hidden by a window. If this window is closed, the panel remains hidden.

**Comment by dalcde** [comment]
Try using https://github.com/linuxmint/Cinnamon/pull/4138 and see if the problem remains

**Comment by dalcde** [comment]
Should be fixed

**Comment by brub2** [comment]
Thank you dalcde. I had no time for testing until today. I confirm all is ok with the last nightly.
