### ISSUE TITLE
Void themes = no void anymore?

### ISSUE THREAD

**Issue by brub2** [linuxmint/Cinnamon#4123]
With Cinnamon nightly, I realize that Void themes don't produce the void (in the panel) that they are supposed to. I still get two "zones" but one is simply stretched to fill all the space. It was a nice feature, so I hope we will recover it.

**Comment by dalcde** [comment]
Current git master fixes the problem when there is no applet in the center panel and panel-edit-mode is off.

**Comment by brub2** [comment]
Thank you again dalcde
