### ISSUE TITLE
Backspace does not remove key-binding.  Key-binding becomes backspace.

### ISSUE THREAD

**Issue by GodloveD** [linuxmint/Cinnamon#4129]
I go to Menu ->Preferences ->Keyboard shortcuts ->System ->Suspend.  I double click on unassigned.  I press a key combo to give it a key binding.  I realize that this works for crap because my computer doesn't display text properly on resume.  I write my own .sh file for suspend and create a custom shortcut.  It works well.  I go back to ->Preferences ->Keyboard shortcuts ->System ->Suspend and double click on my previous binding.  When floating it says "Press Backspace to clear current key-binding".  I press backspace.  Now every time I press backspace my computer Suspends.  To fix this I set my Suspend Key-Binding to an awkward combo I will never use.  But it would be nice to remove the key-binding altogether or at least reset it to default.  

Running cinnamon 2.4.5 on Ubuntu 14.04.2 LTS using a Logitech K400r bluetooth keyboard.

**Comment by mtwebster** [comment]
This is fixed already in master (and the latest 2.4.8 release) - in the meantime you can run:

`gsettings reset org.cinnamon.desktop.keybindings.media-keys suspend`

to get out of your current 'bind' (pun intended)

**Comment by GodloveD** [comment]
Groovy.  Thanks.  

________________________________________
