### ISSUE TITLE
not possible to change laptop screen dimming

### ISSUE THREAD

**Issue by SiKing** [linuxmint/Cinnamon#4131]
I just upgraded to LM 17.1 - Cinn. When I am running on my laptop from battery power, after 30 seconds of inactivity the screen dims. There is no obvious way to change this or to turn this off.
This is pretty annoying when watching something over streaming video.

**Comment by mtwebster** [comment]
From a terminal, run:

`gsettings set org.cinnamon.settings-daemon.plugins.power idle-dim-battery false`

This will turn off that behavior.

This issue is already fixed for Cinnamon 2.6 - in addition, even with the feature enabled, it will be suppressed whenever the screensaver is inhibited (most video players block the screensaver during playback)

**Comment by SiKing** [comment]
How can I easily find out what version of Cinn I am running. The System Monitor used to have a tab at one time (LM13 days?) that told me the version of kernel, the version of Cinn, and few other useful things. That tab is now gone. :(

The player that I was using was a web player, like UTube, which cannot inhibit the screen saver.

**Comment by mtwebster** [comment]
There should be a System Info page in settings, it will tell you - if you're on Mint 17.1, it'll likely be Cinnamon 2.4.8 if you're up-to-date.  There's an applet you can download off spices to prevent the screensaver temporarily (search 'inhibit')

**Comment by SiKing** [comment]
Found the info page. Thanx.
I'm OK with the command you posted above to disable the dimming.

**Comment by dalcde** [comment]
A guess there is a checkbox called "On battery, dim screen to <x>% after <y>" in the cinnamon-settings power module? (It's not terribly clear what it does, but we reworded it in 2.6)
