### ISSUE TITLE
Broken ui after hidpi changes

### ISSUE THREAD

**Issue by jmgomezpoveda** [linuxmint/Cinnamon#4136]
After switching from a HiDPI resolution (e.g. 3200x1800) to a normal one (1920x1080), the context menu of the lower panel shows a gigantic on/off button next to the "Panel edit mode" option. Using Cinnamon git (2.5.0-20150511040).

**Comment by dalcde** [comment]
in general nothing gets displayed properly after changing hidpi settings :(

**Comment by jmgomezpoveda** [comment]
Actually, there are only a few of glitches here and there, but the desktop is pretty usable after a resolution change, even across the "hidpi boundary". If you have the time for the fixes I'll be glad to help with testing and reporting.

**Comment by JosephMcc** [comment]
All that's required is a Cinnamon restart. Either from the Panel context menu or Alt+f2 r.

**Comment by jmgomezpoveda** [comment]
@JosephMcc true, but Cinnamon is so close to being perfectly usable without a Cinnamon restart that seems like a waste not to iron out those small glitches so as to give a smoother, more robust experience.

I don't understand why is everybody happy with glitches that have a workaround. Yes, they may not have huge priority, but don't you prefer a bug-free, bulletproof desktop than one with glitches and workarounds?

**Comment by anandrkris** [comment]
Just thinking aloud, why not just put a note saying requires restart in settings where resolution is changed. Like the below one (old screenshot )
http://www.omgubuntu.co.uk/wp-content/uploads/2012/11/06-cinnamon-settings-panel.jpg

**Comment by jmgomezpoveda** [comment]
@anandrkris that sounds definitely better than leaving the user discover the glitches and not know what to do, but of course less user friendly that having everything fixed automatically.

Just note that a few of the times that I have restarted Cinnamon I have ended up with an unusable desktop (some issue in the Cinnamon restart), requiring then a full system restart.

**Comment by basmevissen** [comment]
I would also love it when Cinnamon could switch between hidpi and normal without restart. It looks like Cinnamon is so close, that it would be possible without an overly amount of effort.
It would probably also pave the road to support situations where hidpi and normal displays are mixed and one can set this setting per window. Maybe not with X anymore, but it is definitly something that is expected to be supported on Wayland.

**Comment by JosephMcc** [comment]
@jmgomezpoveda I never said I was happy with because of the simple workaround. Just letting you know there was one. Of course it would be nicer if everything "just worked".

@basmevissen If it was that easy it would already work :)

**Comment by basmevissen** [comment]
OK, fair :-)
Maybe start with an automatic restart or a dialog box that asks for it and gradually refine it that only part of cinnamon WM gets restarted/re-initialised.

**Comment by jmgomezpoveda** [comment]
I'd say this has improved lately, to the point that I no longer need to restart Cinnamon after a HiDPI change. Well done, Cinnamon devs.

Of course, a few glitches are still left, such as:
- The Menu icon on the lower-left corner
- The tray icons and clock on the lower-right corner
- The maximise et all, buttons on top of the windows
- The mouse cursor

**Comment by jmgomezpoveda** [comment]
I see a lot of progress in the last few months. Congrats to the developers.

There seems to be only one small issue left. When switching between low and high resolution, the icons at the left of the launcher (quit, logout, lock screen...) do not resize.

As far as I can tell, everything else seems to be resizing great after the resolution change.

**Comment by Vahan86** [comment]
@jmgomezpoveda, can we close this issue since it seems fixed?

**Comment by jmgomezpoveda** [comment]
I just tested it with Cinnamon 3.0.7-1 and everything seems to resize correctly, except the tray icons and clock on the lower-right corner, which remain with the previous size.

![screenshot from 2016-09-14 12-04-29](https://cloud.githubusercontent.com/assets/3722516/18508455/846ac06a-7a74-11e6-8945-943a1b2e9d30.jpg)

**Comment by basmevissen** [comment]
A resize still has some glitches that require a Cinnamon restart. Apart from the elements already named, for example the panel font is not resized as well. So I would vote to keep the bug open until a change in the UI scaling is not handled 100% without Cinnamon restart.

**Comment by JosephMcc** [comment]
Just realized this was a duplicate https://github.com/linuxmint/Cinnamon/issues/3194

**Comment by basmevissen** [comment]
On September 27, 2016 8:53:34 PM GMT+02:00, JosephMcc <notifications@github.com> wrote:
>Closed #4136.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/linuxmint/Cinnamon/issues/4136#event-804349945

I would say you closed the wrong duplicate.
-- 
Bas.
