### ISSUE TITLE
Sound applet volume increment

### ISSUE THREAD

**Issue by sjdenny** [linuxmint/Cinnamon#4137]
In Cinnamon sound applet, the default increment when scrolling is fixed at 5%.  Occasionally this is too coarse, and it would be good if this could be user-defined.  It appears to be hard-coded here:
https://github.com/linuxmint/Cinnamon/blob/master/files/usr/share/cinnamon/applets/sound%40cinnamon.org/applet.js#L33

**Comment by martinrotter** [comment]
What about non-linear increments? Usually, if volume is very high and you want to decrease it, then it would make sense to have rather big decrement (6%).

When volume is medium, then average decrement could be best (4%).

For me, when volume is low, then I want to adjust its level more precisely, therefore decrement/increment in that case could be for example 2%.

For example Winamp (audio player for Windows) supports this and calls this feature logarithmic volume.

**Comment by zyisrad** [comment]
I tried to tackle this one today. There are a few problems.

* I don't have enough knowledge of developing on Cinnamon to do what I need to do yet
* There needs to be a global volume variable that every applet that changes volume must use
* This global volume variable must be saved between sessions
* This global volume variable doesn't actually change the volume. It is the data we use to change the volume based on easing functions
* @sjdenny The constant you referenced only works for when the mouse is hovering over the applet in the panel
* I haven't tested switching between users or operating systems. Switching users is no problem if there is a saved session variable. We just set the volume at session start based on the saved variable.
*Lastly, switching easing functions will bounce the volume around; sometimes enough to increase the volume dramatically thus damaging speakers and/or ears.

So far, the main obstacle is every applet is currently manipulating the hardware volume directly and they all have their own implementations. To implement easing functions, the hardware volume needs to derive from a global incrementing variable that is then plugged into these easing functions. These easing function either need to be globally accessible or implemented into every applet. 

```javascript
// vol_inc minimum is 0 and maximum is 1
let vol_inc = 0;
vol_inc += .025;
hardware_volume = easingFunction(vol_inc);
```

I have only gotten it to work for when the mouse is hovering over the sound applet on the panel. It needs to be implemented for when the mouse is hovering over any volume slider and for when the volume media keys are pressed. You can check it out on my volEase branch. https://github.com/zyisrad/Cinnamon/tree/volEase

**Comment by pixunil** [comment]
AFAIK, all applets in the Cinnamon ecosystem uses Gvc as a central place for manipulating volume things, which we can control.

But, IMO, it's overkill, because there needs to be a setting (toggle ease, increment size) and I really don't see the point to have it for all users. For me, I prefer to change my value with the slider (2 clicks) when I need something more precise.

Conclusion: It is possible, but I first want to hear more opinions.

**Comment by quent8192** [comment]
I also feel the need to customize the step. It is indeed too coarse, and when I am watching a movie on my laptop with both loud and quiet scenes I like to adjust the sound setting without leaving fullscreen. The mouse solution is not really practical in this situation (and, being a keyboard guy, I never use the slider). Furthermore it is sometimes harder to be more precise with a mouse/touchpad than with a keyboard (I was yesterday watching a movie in a shaking train, so this is not a rare situation, at least for me :-) )
The logarithmic adjustment would really be a neat bonus.

**Comment by Vahan86** [comment]
+1

**Comment by Cthol** [comment]
Well, actually this applet has nothing to do with volume control. At least on its own.
Since I liked the idea, I've implemented the logarithmic adjustment using Math.pow(), but the volume keeps changing by ±5%.
Here's the non functioning patch :-)
(I'm using Mint 18.)

```patch
--- /usr/share/cinnamon/applets/sound@cinnamon.org/applet.js	2016-07-14 23:42:47.000000000 +0200
+++ applet.js	2016-07-14 23:19:40.444346000 +0200
@@ -1065,10 +1065,12 @@
     _onScrollEvent: function(actor, event) {
         let direction = event.get_scroll_direction();
         let currentVolume = this._output.volume;
+        let volumeIncrement = Math.max(3,Math.ceil(Math.pow(currentVolume, 0.55)))
 
         if (direction == Clutter.ScrollDirection.DOWN) {
             let prev_muted = this._output.is_muted;
-            this._output.volume = Math.max(0, currentVolume - this._volumeMax * VOLUME_ADJUSTMENT_STEP);
+            //~ this._output.volume = Math.max(0, currentVolume - this._volumeMax * VOLUME_ADJUSTMENT_STEP);
+            this._output.volume = Math.max(0, currentVolume - volumeIncrement);
             if (this._output.volume < 1) {
                 this._output.volume = 0;
                 if (!prev_muted)
@@ -1077,7 +1079,8 @@
             this._output.push_volume();
         }
         else if (direction == Clutter.ScrollDirection.UP) {
-            this._output.volume = Math.min(this._volumeMax, currentVolume + this._volumeMax * VOLUME_ADJUSTMENT_STEP);
+            //~ this._output.volume = Math.min(this._volumeMax, currentVolume + this._volumeMax * VOLUME_ADJUSTMENT_STEP);
+            this._output.volume = Math.min(this._volumeMax, currentVolume + volumeIncrement);
             this._output.push_volume();
             this._output.change_is_muted(false);
         }
```

**Comment by clefebvre** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
