### ISSUE TITLE
Can't lock the screen after update 20150512

### ISSUE THREAD

**Issue by lewylewus** [linuxmint/Cinnamon#4140]
Linux Mint 17.1 Cinnamon 64 bit
Cinnamon version 2.5.0 - 2.5.1
3.13.0-24-generic

After applying Mint updates with datestamp 20150512 I can't lock the screen.
I can't lock the screen using Menu button, navigation bar or shortcut.
The lockscreen just doesn't work.

I can't make it back working. Tried changing shotcuts etc. Clicking on LockScreen button in Menu shows the Dialog with custom message but after confirmation it doesn't trigger the lockscreen.

**Comment by dalcde** [comment]
try running cinnamon-screensaver-command --lock

**Comment by lewylewus** [comment]
Tried 
sudo cinnamon-screensaver-command --lock
and
cinnamon-screensaver-command --lock

Nothing happens.

**Comment by dalcde** [comment]
Just in case - did you restart cinnamon after updating?

Try killing the cinnamon-screensaver process, running cinnamon-screensaver from the terminal, and then run cinnamon-screensaver-command --lock from elsewhere, and report anything displayed in the terminal

**Comment by lewylewus** [comment]
Hey, I did couple of restarts. Seems like cinnamon-screensaver process wasn't running at all. 
I tried on first terminal window:
cinnamon-screensaver start

Then on second terminal window I typed:
cinnamon-screensaver-command --lock

Result from first terminal:
(cinnamon-screensaver:4065): GLib-GIO-ERROR **: Settings schema 'org.cinnamon.desktop.screensaver' does not contain a key named 'screensaver-enabled'
Pułapka debuggera/breakpoint

PS. Today I updated Cinnamon with fresh 20150513 updates. No changes.

**Comment by dalcde** [comment]
Did you upgrade cinnamon desktop as well?

**Comment by lewylewus** [comment]
Do you mean Cinnamon package ?

![zrzut ekranu z 2015-05-13 14 20 04](https://cloud.githubusercontent.com/assets/12410891/7610198/47012bf4-f97b-11e4-95cb-ee1234195c1a.png)

**Comment by dalcde** [comment]
I mean cinnamon-desktop. It seems like cinnamon-screensaver isn't actually building on launchpad, and the version mismatch is causing it to break

**Comment by lewylewus** [comment]
Hi, today's updates 20150514 fixed the problem. The lock screen is working again !!! ;) thank you for assistance.
