### ISSUE TITLE
cinnamon-settings panel, using panel-edit makes cinnamon go red.

### ISSUE THREAD

**Issue by leigh123linux** [linuxmint/Cinnamon#4151]
Here a screenshot

![screenshot-screen-2015-05-15-171956](https://cloud.githubusercontent.com/assets/1299302/7657051/cfe53cba-fb26-11e4-884c-2e2b32720740.png)

It doesn't change back to grey after exiting 'panel edit mode' (only changes back to grey after exiting the panel tab).

**Comment by dalcde** [comment]
The red is to indicate the panel you are currently configuring, since you can have many panels. Panel Edit Mode will make the three different regions have different colours
