### ISSUE TITLE
Integrate window preview and app grouping into Cinnamon

### ISSUE THREAD

**Issue by Anti-Ultimate** [linuxmint/Cinnamon#4154]
I know there are third party applets for this, but most of them have several problems so that I'd rather not use them at all.

Seeing as these are probably some of the most used applets ever, I'd really like to see this be in Cinnamon by default. At least app grouping, so that I'm able to have several of the same apps open at the same time without all of them using up all the space on my panel.

You shouldn't just copy pasta the Win7/8 copy pasta ofc, but I find those features very handy and really miss those on Cinnamon.

**Comment by dalcde** [comment]
#67
