### ISSUE TITLE
Fails to startup with Cjs-WARNING at js/ui/keybindings.js:85

### ISSUE THREAD

**Issue by fhimpe** [linuxmint/Cinnamon#4156]
After upgrading from cinnamon 2.2 to version 2.4.8 on Debian, Cinnamon fails to start properly on multiple systems.

This is printed when starting cinnamon from a terminal:

$ cinnamon --replace
Window manager warning: Log level 16: The property GSettings:schema is deprecated and shouldn't be used anymore. It will be removed in a future version.
Cjs-Message: JS LOG: About to start Cinnamon
Window manager warning: Log level 16: The property ClutterStage:color is deprecated and shouldn't be used anymore. It will be removed in a future version.

(cinnamon:7473): Cjs-WARNING **: JS ERROR: Error: Expected type utf8 for Argument 'binding' but got type 'object'
KeybindingManager.prototype.addHotKeyArray@/usr/share/cinnamon/js/ui/keybindings.js:85
KeybindingManager.prototype.setup_media_keys@/usr/share/cinnamon/js/ui/keybindings.js:131
KeybindingManager.prototype._init@/usr/share/cinnamon/js/ui/keybindings.js:49
KeybindingManager@/usr/share/cinnamon/js/ui/keybindings.js:33
start@/usr/share/cinnamon/js/ui/main.js:385
@<main>:1

Window manager warning: Log level 32: Execution of main.js threw exception: JS_EvaluateScript() failed

Downstream Debian bug: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=781888

**Comment by mtwebster** [comment]
try `dpkg --list | grep -E "cinnamon|cjs|muffin"`

Check if there are a couple packages installed that show 2.2 still, alongside 2.4 counterparts - I think cinnamon-desktop particulary.

If you have both 2.2 and 2.4, try running `dpkg --purge --force-all *exact-name-of-package*` on each 2.2 package.

**Comment by mtwebster** [comment]
This was a package/versioning error on our part that's been causing issues on debian-based systems.

**Comment by dalcde** [comment]
Fixed in git master and packaging fixes should be backported to debian by the package maintainers (also this should not be a problem if you do a full upgrade, which should be the case if it gets released to testing).
