### ISSUE TITLE
Region setting wrong in Language settings

### ISSUE THREAD

**Issue by erikdubois** [linuxmint/Cinnamon#4159]
Choosing English as language and as keyboard be-latin1 you end up in the gui language settings with language English BUT as region German, Belgium UTF-8. That seems strangs as only a small part of the 11 million speak german.

Changing is not possible on this button with German on it.
Adding Dutch; Flemish Belgium utf8 with the install/remove languages does work. Then you can change it on the region button.
![screenshot from 2015-05-17 06 33 09](https://cloud.githubusercontent.com/assets/10594806/7669065/10d86696-fc5f-11e4-84fa-9c4387cd4747.png)
![screenshot from 2015-05-17 06 36 22](https://cloud.githubusercontent.com/assets/10594806/7669064/10d3d2ca-fc5f-11e4-8357-dafda3dc8176.png)

**Comment by GLolol** [comment]
The Language Settings app is actually a separate program; file the issue here: https://github.com/linuxmint/mintlocale/issues

**Comment by erikdubois** [comment]
done
