### ISSUE TITLE
Startup application on specific monitor and workspace

### ISSUE THREAD

**Issue by erikdubois** [linuxmint/Cinnamon#4161]
Feature request : can you add extra option for dual screen users and workspace users
I like to auto-start with 
firefox, sublime, nemo, spotify, geary
I have dual screen and this is my working environment.
Screen 1
Firefox (workspace 1), nemo (workspace 2), sublime (workspace 3)
screen 2 
Geary (workspace 9), Spotify (workspace 10)

**Comment by tp0** [comment]
Meanwhile, you can **gdevilspie** (it is in the repos). It recognizes windows and does things with them and it has an option to set workspace. Just tested so it also works on Cinnamon. It doesn't seem to have a display/screen option though.

**Comment by cpaulik** [comment]
I would like to add that this should not be limited to autostarted apps. I've been using Awesome WM for some time and also use Cinnamon and this is one of the features I miss most from Awesome. To just start an app on a workspace based on some rule. GNOME 3 has this already if that helps in any way.

**Comment by maxim2muchcoffee** [comment]
+1
It could be very useful not to overload at startup first workspace with Transmission, Skype and Banshee (which are usually on the 2nd and 3rd workspaces )

**Comment by DirkHaar** [comment]
With my new Yoga 910 a real boot (incl. hardware passwort, DualBoot-Enter, and logon) takes about 22 sec to complete the desktop w/ FF, TB, LO, nemo, geany, xed, tomboy, hibiscus, xterm, ghex. Mostly I would not have to start any programs manually (nor to close as I got 16GB).
With such modern hardware it should be standard that you have those apps opened on different workspaces by default. The gain at autostart is lost when you ahve to move apps to other workspaces manually (even with keyboard shortcuts for that in mind).

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html
