### ISSUE TITLE
expo windows are not clickable

### ISSUE THREAD

**Issue by aminehmida** [linuxmint/Cinnamon#4165]
### To reproduce ###
1. open expo and select any random window
2. re open expo and select any random window
3. do it many times

### what should happen ###
The window is selected and is put to the front and expo mode is closed

### what happen ###
The window is selected but not put to the front and the expo mode is not closed but if you click *ENTER* keyboard button the window is selected and put to the front normally. 

### system informations ###
    cinnamon --version : 
    Cinnamon 2.4.8
    uname -a : 
    Linux 4.0.2-1-ARCH #1 SMP PREEMPT Thu May 7 06:47:54 CEST 2015 x86_64 GNU/Linux

This bug is observed with kernel 3 and 4

**Comment by dalcde** [comment]
Does this happen consistently? About how many times do you have to do 1 and 2 until the bug occurs?

**Comment by aminehmida** [comment]
In general, I need to repeat it 3 or more time to make it happen

**Comment by aminehmida** [comment]
I want just to add that this bug happens randomly

**Comment by JosephMcc** [comment]
I just tried repeating the steps about 30x in a row with no issues.

**Comment by aminehmida** [comment]
Hi, I have recorded a short video showing this bug https://youtu.be/ECS-xcFDvmw I hope this will help

**Comment by ManIVIctorious** [comment]
Does this issue still occur in cinnamon 3.0?

**Comment by aminehmida** [comment]
Problem solved for me.
