### ISSUE TITLE
cinnamon-settings: Incorrect WPA2 settings (system-ca-certs=true)

### ISSUE THREAD

**Issue by kmdm** [linuxmint/Cinnamon#4168]
When using cinnamon settings to configure a WPA2 Enterprise network (possibly others) it always adds the following setting into the config file when not providing a certificate:-

system-ca-certs=true

This prevents the wireless from connecting in the case where no certificate was provided since it's unable to verify the wireless certificate against the system certificates. 

This does not occur when using "nm-connection-editor"  which notably also has an additional config option "No CA certificate is required". 

Software versions (Debian testing):-

cinnamon: 2.4.8 (from Debian experimental)
network-manager: 1.0.2

Original bug: https://bugzilla.gnome.org/show_bug.cgi?id=702608
Fixing commit: https://git.gnome.org/browse/network-manager-applet/commit/?id=c798c40c5dce3bc6d9b615621cefe59660b5a504

**Comment by leigh123linux** [comment]
This issue is in cinnamon-control-center (not cinnamon)!
@AlbertJP was looking into it a while back and has this commit in his fork

https://github.com/AlbertJP/cinnamon-control-center/commit/3a1a14c5b442d3aeea4531ffdc4ddadc06635180

It didn't fix the eduroam issue but may help this one

https://trello.com/c/goYW35vG/68-3623-eduroam-problem

**Comment by kmdm** [comment]
Yes, sorry. I realised a few minutes ago while digging into it that I should have logged this against cinnamon-control-center. :(

**Comment by AlbertJP** [comment]
@kmdm How did you get to the dialog where you can enter connection details? Bug #3623 already exists for a while, in cinnamon-control-center versions 2.4.0 and later, which causes the dialog with connection details to fail to appear when you click the network.
