### ISSUE TITLE
LibreOffice floating toolbar causes keyboard/window focus to be lost

### ISSUE THREAD

**Issue by ericjding** [linuxmint/Cinnamon#4173]
I've come across an annoying issue while using LibreOffice Writer with Cinnamon: floating toolbars are (often) causing the Writer window to lose keyboard focus. This happens whether I've got window focus mode set to sloppy, mouse, or click-to-focus.

Most egregious are common toolbars like the Bullets and Numbering toolbar; if I use the mouse or cursor keys to navigate through the document and the cursor moves to a line that's part of a bulleted or numbered list, the toolbar shows up and the main Writer window loses keyboard/window focus. Suddenly, my keyboard cursor's gone! In order to get back to the document, I either have to click in the document or (in focus-follows-mouse mode) move the mouse cursor out and back into the main window.

I can work around this bug by docking that specific toolbar. But I'd prefer to have it fixed so that it behaves as expected!

I have found that if I run the Linux Mint LiveUSB in a VirtualBox VM, then I don't see this behavior (i.e., the focus is not lost by the main window). If I run the LiveUSB on the native hardware, then I do still see this behavior. To make sure there wasn't something peculiar to my settings, I created a new test user account on my system and tried with that account, and experience the same problem. The problem happens with or without the "Prevent focus stealing" check box selected in Settings->Windows. Every now and then, the focus actually seems to stay on the main window. Feels like a timing issue.

I tested the issue also using LinuxMint live USB systems with other desktop environments. With KDE and XFCE, the problem doesn't occur. With both Cinnamon and MATE, the problem occurs; when it does, if I hit Alt-PrtSc to capture the current window, I get a screenshot of the entire desktop, rather than just the LibreOffice Writer window.

I'm running Linux Mint 17.1 64-bit on a ThinkPad x220 with Intel HD 3000 graphics chip. I've upgraded all software on my system as recommended. I'm currently using LibreOffice 4.2.8.2 with the default kernel (3.13.0-37) and Cinnamon 2.4.8.

**Comment by ericjding** [comment]
Another data point: someone else has been able to reproduce this issue in a VM too, even though I wasn't able to, which confirms that it's not a hardware/driver issue, and that it's probably a tricky timing issue of some sort. See http://forums.linuxmint.com/viewtopic.php?f=47&t=196350 for discussion.

**Comment by Vahan86** [comment]
@ericjding, is this still an issue in Cinnamon 3.0.x?

**Comment by ericjding** [comment]
I just tried to see if this is an issue with the Linux Mint 18 live USB system (running LibreOffice 5.1.2.2 and Cinnamon 3.0.6) on my computer, since I'm still running Mint 17.3 as my everyday system. I was unable to reproduce the issue in Mint 18, so while I can't technically vouch for it being fixed, I can say that if it's still there, I wasn't able to get it to happen! :-)

**Comment by Vahan86** [comment]
@JosephMcc, can we close this issue?
