### ISSUE TITLE
power manager not working

### ISSUE THREAD

**Issue by daddy33** [linuxmint/Cinnamon#4177]
Hello,

with cinnamon 2.6 I have the following problem (power manager not launching)

cinnamon-settings power
Python module

(cinnamon-settings.py:6287): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:157:38: Missing name of pseudo-class

(cinnamon-settings.py:6287): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:169:23: Missing name of pseudo-class
Loading Power module
Traceback (most recent call last):
  File "/usr/lib/cinnamon-settings/cinnamon-settings.py", line 582, in <module>
    window = MainWindow()
  File "/usr/lib/cinnamon-settings/cinnamon-settings.py", line 89, in wrapper
    res = func(*arg)
  File "/usr/lib/cinnamon-settings/cinnamon-settings.py", line 297, in __init__
    self.go_to_sidepage(cat, path)
  File "/usr/lib/cinnamon-settings/cinnamon-settings.py", line 115, in go_to_sidepage
    sidePage.build()
  File "/usr/lib/cinnamon-settings/bin/SettingsWidgets.py", line 329, in build
    self.module.on_module_selected()
  File "/usr/lib/cinnamon-settings/modules/cs_power.py", line 168, in on_module_selected
    self.build_battery_page()
  File "/usr/lib/cinnamon-settings/modules/cs_power.py", line 244, in build_battery_page
    if device[1] == UPowerGlib.DeviceKind.UPS and device_states[i] == UPowerGlib.DeviceState.DISCHARGING:
NameError: global name 'device_states' is not defined

**Comment by leigh123linux** [comment]
Please post the output for this command


```
upower -d
```

**Comment by daddy33** [comment]
upower -d
Device: /org/freedesktop/UPower/devices/ups_hiddev1
  native-path:          /sys/devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.1/2-1.1:1.0/usbmisc/hiddev1
  vendor:               Eaton
  power supply:         yes
  updated:              jeu. 01 janv. 1970 01:00:00 CET (1432315930 seconds ago)
  has history:          yes
  has statistics:       yes
  ups
    present:             yes
    state:               empty
    percentage:          0%

Daemon:
  daemon-version:  0.9.23
  can-suspend:     yes
  can-hibernate:   yes
  on-battery:      no
  on-low-battery:  no
  lid-is-closed:   no
  lid-is-present:  no
  is-docked:       no

**Comment by daddy33** [comment]
Clem wrote in the forums that he fixed it.

**Comment by leigh123linux** [comment]
Yes I see the commit

https://github.com/linuxmint/Cinnamon/commit/4dd9362ec0c789e4550af495c68c827954d24ce5
