### ISSUE TITLE
Add/Remove desktop themes window blank

### ISSUE THREAD

**Issue by HalinReno** [linuxmint/Cinnamon#4178]
I upgraded to Cinnamon 2.6 on my main rig and a virtual machine and after the upgrade, I bring up the Themes window and when I click on Add/remove desktop themes... it gives me a blank window. It happens and both my main rig and in the VM.
![untitled](https://cloud.githubusercontent.com/assets/9020284/7776483/30ab8dee-0070-11e5-8215-7b0ddbf27803.jpg)

**Comment by dalcde** [comment]
Fixed by https://github.com/linuxmint/Cinnamon/commit/cbdce0dfd9110948734ef88480cde0dbc153840e
