### ISSUE TITLE
Allow change the sidepage visibility dinamically in cinnamon settings

### ISSUE THREAD

**Issue by lestcape** [linuxmint/Cinnamon#4179]
If any specific distro/user will try to add valid modules only on this specific distro, they will need to patch the application or otherwise if the user decide to remove the application, the module will still active for an application that not exist. Here there are an example of a module that is only relate with ubuntu:

cs_ubuntu_software_center.py
```
#!/usr/bin/env python
#  -*- coding: utf-8 -*-

from SettingsWidgets import *
from gi.repository import Gio

class Module:
    def __init__(self, content_box):
        launcher = Gio.DesktopAppInfo.new("ubuntu-software-center.desktop")
        keywords = _("Sources, PPA, Install, Uninstall, Remove, Purchase, Catalogue, Store, Apps")
        self.name = launcher.get_display_name()

        icon = launcher.get_icon().to_string()
        command = "/usr/bin/software-center"#launcher.get_commandline()
        sidePage = SidePage(self.name, icon, keywords, content_box,
                            exec_name=command, is_standalone=True, module=self)
        self.sidePage = sidePage
        self.comment = launcher.get_description()
        self.category = "admin"

    def on_module_selected(self):
        pass
```

As can be see, is easy to add a module to call an external existing application, but user could uninstall this application, and then the module will not be removed.

There are ofcourse a lot of possible usages of this feature, because all things not necessary will be always active.

What I request is that SidePage contain a functions get_visible and set_visible, and also emit a signal when the visibility of the sidepage change.

Then, in cinnamon-settings.py this signal could be captured and change the visibility of the module, dinamically, this also can include change the visibility of the category if there are not any other sidepage visible.

The necessary changes only will be here:
https://github.com/linuxmint/Cinnamon/blob/master/files/usr/lib/cinnamon-settings/cinnamon-settings.py#L333

```
    def filter_visible_function(self, model, iter, user_data = None):
        sidePage = model.get_value(iter, 2)
        text = self.search_entry.get_text().lower()
        if sidePage.get_visible() and (sidePage.name.lower().find(text) > -1 or \
           sidePage.keywords.lower().find(text) > -1):
            return True
        else:
            return False
```

https://github.com/linuxmint/Cinnamon/blob/master/files/usr/lib/cinnamon-settings/cinnamon-settings.py#L530

```
def anyVisibleInCategory(self, category):
        id = category["id"]
        iter = self.storeFilter[id].get_iter_first()
        visible = False
        while iter is not None:
            sp = self.storeFilter[id].get_value(iter, 2)
            cat = self.storeFilter[id].get_value(iter, 3)
            visible = sp.get_visible() and (cat == category["id"])
            iter = self.storeFilter[id].iter_next(iter)
        return visible
```

In the sidepage visibility change signal could be call "anyVisibleInCategory" and decide if will show  or not the category.

Thanks and regards.

**Comment by dalcde** [comment]
wouldn't the right thing to do be include the software-center module in the software-center package instead?

**Comment by lestcape** [comment]
@dalcde yes, but that could be possible if cinnamon is the default desktop of the distro, otherwise, sure this will not approved. So currently this is only possible on mint, makulu and Antergos... I also try to provide cinnamon in ubuntu 14.04 and i like to add several specific ubuntu modules to the cinnamon settings. Ofcourse, i can not modify any ubuntu packages....

Regards.

Regards

**Comment by lestcape** [comment]
@dalcde there are right now a solution, thats is not my intention, but well. if the application not exist, Gio.DesktopAppInfo.new will throw an error and this will prevent that cinnamon load the module, but this is not properly the solution and this will not help not be used on other things...

**Comment by lestcape** [comment]
Also will be more interesting create a little application for write the first code automatically to the module folder of cinnamon-settings while will be change automatically the .desktop line only. That application could be also a cinnamon-setting module.

**Comment by dalcde** [comment]
Well as you mentioned you can make it throw an error when it shouldn't be there. This is arguably the "pythonic way"?

**Comment by lestcape** [comment]
This is a little drastically i think... but is working... Any way i will do a module to dynamically generate modules and include this on my repository. thanks.

**Comment by lestcape** [comment]
I don't know if this will be usefull add something like this https://github.com/lestcape/Cinnamon-Settings-Editor to cinnamon.
