### ISSUE TITLE
Battery applet not refreshing

### ISSUE THREAD

**Issue by moithil** [linuxmint/Cinnamon#4180]
The battery applet stopped refreshing its status after I updated cinnamon on linux mint to the current version - 2.4.8.
It shows correct status after i log out and log in but during one session, it remains in same condition even if i pull out the adapter.

**Comment by dalcde** [comment]
Does this happen on Cinnamon 2.6? The applet has been reworked considerably.

**Comment by moorkai** [comment]
It started happening to me with 2.6 (#4176), Cinnamon 2.4.8 was fine...

**Comment by moithil** [comment]
when is it going to be stable? When will we get the update without having
it from unstable repos?
