### ISSUE TITLE
[Meta] Last minute bug fix propositions before the release of Cinnamon 2.6

### ISSUE THREAD

**Issue by Paviluf** [linuxmint/Cinnamon#4182]
I really love Linux Mint and Cinnamon but there is still some little problems that prevent me to use it. On the eve of the new version, it may be the right time to fix some of these little things. I don't know what the devs will think but as a user this is this that prevent me to use Cinnamon.

**Cinnamon Freezing** (most important one and may be already fixed!)
https://github.com/linuxmint/Cinnamon/issues/4072

**When a selection is made the beggining is not taken into account**
https://github.com/linuxmint/Cinnamon/issues/3786

**Cinnamon menu "enhanced / simple / basic" search**
https://github.com/linuxmint/Cinnamon/issues/1220

**Unity indicators not displaying properly in systray**
https://github.com/linuxmint/Cinnamon/issues/4035

**Arrow is not always displayed when a folder is not empty**
https://github.com/linuxmint/nemo/issues/894

If you have some important problem too write it in the comments but remember that we ask nothing as Linux Mint is free and is the result of countless developpers working for free. But if some of theses things can be fixed/improved it will only get better for every user of this great free software.

Thank you !

**Comment by dalcde** [comment]
This is pointless.

**Comment by Paviluf** [comment]
I was pretty sure that someone will close it...
A buggy Cinnamon is pointless. Why not listen to the people that use the software you take time to make ? There is about 800 bugs open and I don't think you know/remember every of them...

**Comment by dalcde** [comment]
We might not know all bugs, but we are all aware of serious release-critical bugs. We know and are aware of the bugs you pointed out, and we are able to prioritize. If there is a serious bug out there we haven't fixed, that's probably because we've tried very hard and still couldn't. We do listen to users and read the feedback provided in the release announcement comments and friends. If you want to make your point, feel free to express it there.

For what it's worth, your post seems to be just a list of bugs you've encountered and filed. You are not representative of the whole population of users. If this goes on and other people comment, this will just become a huge thread listing all 800 bugs in Cinnamon, which is pointless. We read and take into account all the comments from all users, and decide what is most critical thing we have to fix. This thread is not helpful at all.

This is a bug tracker, not a discussion forum. Is this a bug? Is it a feature request? Are there any circumstances where we can call this "fixed"? No. Then don't post it here. Please.

**Comment by Paviluf** [comment]
Ok I understand your point and I am sorry to try to help the wrong way however I did that because I can't understand why there is no sign of activity on some bugs. Take this one (https://github.com/linuxmint/Cinnamon/issues/3786), no comment so I assume (maybe wrongly) no one tried anything, but I can guarantee you that this bug can make you crazy when you want to select some text for exemple and you do that often.

**Comment by Paviluf** [comment]
How can we, simple users, can proceed to have some of the most annoying bugs for us fixed ?
It's frustating to really like Cinnamon but can't use it on a daily basis because of some bugs.

**Comment by dalcde** [comment]
You file a bug report.

**Comment by Paviluf** [comment]
Ok I give up. You say "file a bug report", ok, but what happen when you file a bug report in 2012 (like this one https://github.com/linuxmint/Cinnamon/issues/1220 but there is other) and the bug is still here in 2015 ???

**Comment by dalcde** [comment]
There was a reply by mtwebster to explain why that is the case, why it was the best solution we could come up with at that time, and that we are looking for solutions. We weren't able to come up with solutions at that time. If we were not able to solve it, you can grumble about it as much as you wish, and we are still incapable of solving it. **IT DOESN'T HELP SOLVE THE PROBLEM AT ALL. THIS IS THE POINT I AM MAKING.**

With that said, we have recently discussed that issue on the irc and think there might be a viable solution, but given that it requires major changes in codebase and the feature freeze is here, we'll have to leave that for the next release.

In addition to the bugs you mentioned, there are *lots* of things that need fixing. Panels on multiple monitors was implemented in this release. Then we have veritcal panels, broken systrays (they are not just broken for unity indicators, they are broken everywhere) to more minor things such as https://github.com/linuxmint/Cinnamon/issues/575. They might be solved in the next release, or the one after that, or never. No one knows. We just try our best.

I'll reiterate: **we are aware of long-standing issues in the bug tracker. We try our best to solve them, but we don't always succeed. There isn't a magic button we press to instantly solve bugs. It takes time and effort to do so. So be patient. Complaining doesn't help.**

**Comment by ManIVIctorious** [comment]
@Paviluf to be honest but you have to admit that there are a lot of bugs which have a higher priority to the cinnamon devs. Cinnamon 2.4 for example had a lot of stability issues which have to be fixed.

**Comment by Paviluf** [comment]
I do not grumble, as you can see I rarely come to write here and I try to be polite. Of course I know that complaining doesn't help but when nothing happen for 3 years, one can be upset. I just wish that I can use Cinnamon, because I like it.

**Comment by lestcape** [comment]
@Paviluf, really sorry but you use cinnamon? I'm probably one of the most problematic cinnamon users, but believe me when i say that report a lot of problem one behind another, is not like help...
