### ISSUE TITLE
Cinnamon process burns 100% CPU playing WMA file using xdg-open from chrome web browser

### ISSUE THREAD

**Issue by ericjster** [linuxmint/Cinnamon#4185]
When playing a WMA file via xdg-open from a web site with Chrome, Cinnamon burns 100% CPU.

Versions:
Linux Mint 17.1 'Rebecca'
Cinnamon 2.4.6
Chromium-browser 41.0.2272.76-0
gvfs  1.20.3-0ubuntu
vlc   2.1.6-0ubuntu1

Repro:
1. Chrome, browse to: http://www.kexp.org/live/liveperformance.aspx?rId=34625
2. Click on "Full Performance", to launch the WMA file.
3. Get popup "External Protocol Request... link requested is mms://media-...WMA ... following application .. xdg-open ..."
4. Click OK to launch xdg-open. Note that /usr/bin/xdg-open is a shell script. On my system, $DE=gnome, and the shell script launches gvfs-open.
xdg-open mms://media-wm.cac.washington.edu/dw/1/51/3c/3c440110-2fd5-4d5a-8a4b-1021d4a5658f.WMA

Expected:
On FireFox I can pick vlc as the program to run, and only about 5-10% cpu is used while the audio plays.

Actual:
Launching from Chrome burns about 100% in a chrome process and about 100% in the cinnamon process. (My machine reports 8 CPUs, so the 100% is out of 800%.)
(Sorry I used "sudo perf record -ag" but after an hour of looking for the symbols for Cinnamon 2.4.6 I still could not find them so I only have numeric call stacks.)

Reproducability:
For some reason it stopped playing the audio, but I still see 100% CPU until I close the web page in Chrome.

**Comment by Vahan86** [comment]
@ericjster, is this still an issue for you in Cinnamon 3.0.x?

**Comment by Vahan86** [comment]
@JosephMcc, can we close the issue?
