### ISSUE TITLE
Launching the media player from sound applet

### ISSUE THREAD

**Issue by marmistrz** [linuxmint/Cinnamon#4193]
The sound applet is notifying that e.g. Banshee is playing. It should be possible to unminimize the minimized to taskbar media player without launching it explicitly.

**Comment by pixunil** [comment]
The sound applet should do this job already. There is in versions lower 2.6, a button with an arrow up right to the play, pause, etc. buttons, in version 2.6 (nightly) it is left to the title "Banshee - Playing".
Press it, and the player is raised (unminimized also).

**Comment by marmistrz** [comment]
Thanks! :)

**Comment by marmistrz** [comment]
The concept is much better now :) Only the show/close buttons are a little too small, as for me

**Comment by pixunil** [comment]
See #4305 for that
