### ISSUE TITLE
Possible to get Gnome 3 style screen locks?

### ISSUE THREAD

**Issue by Anti-Ultimate** [linuxmint/Cinnamon#4195]
Right now I'm using Cinnamon with GDM. What I really like about the Gnome shell is that when you lock your computer, it puts you into the GDM log-in dialogue. 

I think Cinnamon should put you back into the MDM log-in dialogue aswell.

**Comment by dalcde** [comment]
There is a "switch user" option. We couldn't always go to the MDM login dialogue, because we don't force everyone to use MDM (eg. you are using GDM). In fact you can *not* use a display manager at all. Also, I doubt what you see is actually the GDM dialogue, but something that resembles it.

**Comment by Anti-Ultimate** [comment]
Gnome 3 doesn't allow you to lock your screen without GDM installed, so that's what I assume is happening.

**Comment by dalcde** [comment]
If that's the case, it's entirely stupid.

**Comment by Anti-Ultimate** [comment]
Tried using LightDM for now, that seems to work fine with Switch Users.

Maybe remove the lockscreen entirely and do whatever "Switch users" does? Both these things work exactly the same, it's just that one moves you into the dm while the other one has you stay in Cinnamon (you can still switch users anyways).

**Comment by dalcde** [comment]
What if you don't have a display manager?

**Comment by Anti-Ultimate** [comment]
It should obviously be optional.

**Comment by Anti-Ultimate** [comment]
"Switch users" appears to work only with MDM and LightDM. Couldn't get it to work with GDM or any other DM. However, as Cinnamon is obviously the flagship de for Linux Mint, which uses MDM,  I think it should be done anyway.

**Comment by dalcde** [comment]
What is the benefit of doing so?

**Comment by Anti-Ultimate** [comment]
It looks and feels way better. Say you want to use your account while someone else has locked the computer.

OLD:Lock screen->"Switch users"->Select User and log in
New: Lock screen->Select other user and log in

Pretty similiar to how Windows does, and since Linux Mint is pretty much a distribution aimed for people looking to switch to the Linux side, it would make them feel a lot more at home.

**Comment by dalcde** [comment]
I disagree. Most likely you are the person trying to unlock, and the screensaver looks and feels much better because everything is centered and things are focused correctly. I would believe it is also much faster this way because no X session switching is needed.

There is absolutely no need and no reason to mimic the behaviour of Windows.

**Comment by Anti-Ultimate** [comment]
You're probably right, I just wished it looked a bit more modern ;9

You can't really customize your lock-screen while you can customize your dm all you want though.
