### ISSUE TITLE
wrong Python sha-bang

### ISSUE THREAD

**Issue by WimpyMan** [linuxmint/Cinnamon#4197]
Cinnamon uses:
```bash
#!/usr?bin/python
```
Or
```bash
#!/usr/bin/env python
```

Which means that it is impossible to use it in a python 3 environnement.
Please use
```bash
#!/usr/bin/env python2
```

Cinnamon version: 2.2.16
Linux: Debian unstable

**Comment by dalcde** [comment]
That was fixed long time ago and works properly in Cinnamon 2.6. The only case where /usr/bin/env python is used is docs/reference/cinnamon-js/gen_doc.py, which was specifically designed to work with both python2 and python3
