### ISSUE TITLE
When all panels are removed, Panel settings do not open

### ISSUE THREAD

**Issue by anandrkris** [linuxmint/Cinnamon#4200]
As discussed over IRC, filing it here.

When I remove the last panel in Cinnamon, there seems to be an issue in recovering from that state without tweaking gsettings keys.

I have some misgivings on removing *all* panels without a warning to the user.  When panel is removed, consequently Cinnamon menu disappears as well. Also, pressing `Super` key does not bring up the menu so users could be lost not knowing how to launch applications / programs. IMO, this could put novice users to a spot of bother as they need to use `Alt + F2` to launch Cinnamon Settings and recover the panel if it was inadvertently removed.

Another option is for the Desktop COntext menu to have *Add Panel* at least when there are no panels. Similar to Add Desklets and Change Desktop background options available at the moment.

**Comment by dalcde** [comment]
Fixed in git master

**Comment by anandrkris** [comment]
@dalcde - Applied new updates. Original issue is fixed. :clap: 
Can we keep it open for warning message when you remove the last panel? I can amend the topic.
