### ISSUE TITLE
The cover preview is broken after a suspend

### ISSUE THREAD

**Issue by marmistrz** [linuxmint/Cinnamon#4201]
If the machine is suspended, such thing is displayed instead of the cover after waking up the computer.
![workspace 1_009](https://cloud.githubusercontent.com/assets/2914938/7799182/32d660f4-0303-11e5-99e8-e4061b9bd980.png)

**Comment by nicdumz** [comment]
I think that this is a duplicate of https://github.com/linuxmint/Cinnamon/issues/4747

**Comment by marmistrz** [comment]
I have an nvidia driver (proprietary)

**Comment by Vahan86** [comment]
@JosephMcc, dublicate of https://github.com/linuxmint/Cinnamon/issues/4747

**Comment by JosephMcc** [comment]
The root cause may be the same but I'm not sure.

**Comment by Vahan86** [comment]
@marmistrz, does this issue still relevant to Cinnammon 3.6?

**Comment by marmistrz** [comment]
I no longer experience this issue
