### ISSUE TITLE
Second monitor not detected

### ISSUE THREAD

**Issue by awzang** [linuxmint/Cinnamon#4206]
I did a fresh Arch linux installation and installed Cinnamon as my desktop environment. First time I connected my second monitor, it mirrored my primary screen (laptop). I wanted to change this by making it extend my primary screen. Once it transitioned to extending the primary screen it crashed. Ever since Cinnamon isn't detecting my second monitor. My second monitor is detected though by LightDM, my display manager.

**Comment by dalcde** [comment]
Do you get any errors? (eg. ~/.xsession-errors, or even logs from Xorg itself)

**Comment by awzang** [comment]
@dalcde Here is my Xorg.0.log: https://gist.github.com/awzang/46972a8b7b31c9402e86

**Comment by dalcde** [comment]
The
```
[607:607:0526/210245:ERROR:gles2_cmd_decoder.cc(11539)] [GroupMarkerNotSet(crbug.com/242999)!:D078FD55931A0000]GL ERROR :GL_INVALID_OPERATION : glTexStorage2DEXT: <- error from previous GL command
[607:607:0526/210247:ERROR:gles2_cmd_decoder.cc(11539)] [GroupMarkerNotSet(crbug.com/242999)!:D0A07057931A0000]GL ERROR :GL_INVALID_OPERATION : glTexStorage2DEXT: <- error from previous GL command
[607:607:0526/210258:ERROR:gles2_cmd_decoder.cc(11539)] [GroupMarkerNotSet(crbug.com/242999)!:D016A158931A0000]GL ERROR :GL_INVALID_OPERATION : glTexStorage2DEXT: <- error from previous GL command
 ```
lines look suspecious. Have you tried changing back to mirror display? Also can you try gnome shell to see if the same issue occurs?

**Comment by awzang** [comment]
@dalcde I did the following:
```
xrandr --addmode DP2 --mode 1024x768
xrandr --output DP2 --mode 1024x768 --same-as eDP1
```
What happens next is, I see the transition and then it crashes. Should I install gnome 3.16? Only gnome 3.16 is available in AUR.

**Comment by dalcde** [comment]
Wait what? You don't have 3.16?

**Comment by awzang** [comment]
@dalcde I reinstalled my laptop with the official Linux Mint Cinnamon version, problem remains.

**Comment by dalcde** [comment]
Then I guess it is more of an X issue than a Cinnamon issue. Have you tried, say, xfce or kde (or even a bare X session)?

**Comment by awzang** [comment]
@dalcde I reinstalled my laptop with an older version of Arch Linux (March 2015) and that solved my problem. I can finally use my second monitor correctly. Thanks for your effort!
