### ISSUE TITLE
Cinnamon Menu resets search results when typing too fast

### ISSUE THREAD

**Issue by friedemann-** [linuxmint/Cinnamon#4209]
When you press the Super-(Win-)Key and type immediately after, the first letter(s) are missing. This is not about that.

When you Press Super (Win) and wait some short time (half a sec, depending on how quickly your application list loads - you can see the scroll bar shrinking, when it does) you can enter your search keyword, which is also displayed, but the search results just blink up and then a part of "all applications" reappears.

It seems to load in parts, so in my case it is always everything from "Date & Time" down.

This is a very minor issue, but:
I think, some (maybe many) people consider it a great matter of convenience, being able to type WIN + the first letters of an application to start a program quick.

Not losing letters would also be nice, probably not possible though. But in the moment - at least on my installation - I have to wait a safety second before typing anything, or I'll have to start over again.

I never start anything with the mouse, so on any desktop or OS I highly appreciate, when this feature works smoothly and I start looking for other solutions, if it doesn't.

I hope I'm not nagging about too obscure things here. I use cinnamon a lot, have done a lot of customizing and I'm able to work as efficient as never before. I think cinnamon pretty great.

**Comment by icarter09** [comment]
@friedemann- what version of Cinnamon you are using?

**Comment by KOLEGA007** [comment]
I think, thats the neverending story (problem) with time of loading the menu ... You just type before the entry is active ... It will be hard to solve this ... :-1:

**Comment by Vahan86** [comment]
Tried to reproduce on Cinnamon 3.0.7 but in vain. Works fine for me. 
@JosephMcc, can we close this issue?

**Comment by JosephMcc** [comment]
@friedemann- can you still reproduce this?

**Comment by Vahan86** [comment]
@JosephMcc, can we close the issue?
