### ISSUE TITLE
Full screen on one monitor causes you not to be able to interact with panel on second monitor

### ISSUE THREAD

**Issue by m00ster** [linuxmint/Cinnamon#4215]
when you have one monitor in a dual monitor setup and have added a panel to the 2nd monitor, you lose the ability to interact with the panel on the other screen when using a full screen app on the first screen. Clicking the panel gives you the standard desktop background context menus. This is on cinnamon 2.6.3 on mint 17.1.

**Comment by JosephMcc** [comment]
Can you try this in Cinnamon 2.8. There are still issues with fullscreen apps but I think this particular one is fixed.
