### ISSUE TITLE
Menu Editor Choose an Icon size bug

### ISSUE THREAD

**Issue by RaedsLab** [linuxmint/Cinnamon#4216]
When choosing an icon for an entry in the menu editor the preview size is not resized and left as the actual size of the icon. 

The screenshot shows that this could be troublesome for some very large icons (like the default one with visual code).

![screenshot from 2015-05-28 11 46 27](https://cloud.githubusercontent.com/assets/1442690/7858336/707c1b1e-052f-11e5-9c32-b28411718fed.png)

**Comment by mtwebster** [comment]
Already fixed in 2.6:

https://github.com/linuxmint/Cinnamon/commit/5885ce9cb3d1c803ed306409a052dfc161af5ebd
