### ISSUE TITLE
clicking about for the power applet will cause the about screen to take focus and not let you click ok

### ISSUE THREAD

**Issue by m00ster** [linuxmint/Cinnamon#4217]
Clicking about on the power applet will take focus and lock you from clicking anywhere on the desktop. It will also not allow you to clock ok to release focus and let you resume control of your desktop. The only way for me to recover was killing the xserver.

**Comment by dalcde** [comment]
Not reproduced.

**Comment by m00ster** [comment]
I am unable to reproduce this as well. It did occur once for me though. Feel free to close the report. Thanks!

**Comment by JosephMcc** [comment]
I cannot reproduce either.
