### ISSUE TITLE
Applications trying to set geometryfor windows on 2nd monitor with added panel act as though the panel was not present when calculating window position

### ISSUE THREAD

**Issue by m00ster** [linuxmint/Cinnamon#4218]
Applications requesting geometry for windows on the 2nd monitor with the new panel feature activated and present do not properly set geometry relative to the panel, instead setting geometry as though the panel was not there. Doing the same on the first monitor properly sets geometry based on visible canvas outside of the panel.

**Comment by dalcde** [comment]
With what applications are you experiencing this?

**Comment by m00ster** [comment]
I am experiencing this with mpv when configured to center the window with the following options:

autofit-larger=90%x90%
geometry=50%:50%

**Comment by m00ster** [comment]
you can see the difference by changing the option screen=2 back and forth to screen=1. The window is properly centred around the panel on the main screen, but not on the secondary screen with the new panel feature.

**Comment by dalcde** [comment]
mpv displays incorrectly in both monitors for me

**Comment by Vahan86** [comment]
@m00ster, is this still an issue in Cinnamon 3.0?

**Comment by itzexor** [comment]
There is a good explanation on why this doesn't work here: https://lists.freedesktop.org/archives/xdg/2015-October/013576.html

In Nemo, to draw the desktop the correct size, we have worked around it by maximizing the desktop window instead.

**Comment by JosephMcc** [comment]
The link from @itzexor explains the issue. It isn't really a bug in Cinnamon.
