### ISSUE TITLE
wine full screen windowed mode game doesnt display on top of panels in 2nd monitor.

### ISSUE THREAD

**Issue by m00ster** [linuxmint/Cinnamon#4223]
Hello,

Running full screen windowed mode apps under wine do not hide the panels on the 2nd monitor. I see the panels on top of the app.

App tested: world Of warcraft full screen windowed mode using opengl under latest wine version.

**Comment by m00ster** [comment]
another way to reproduce is to put a full screen wine app on the primary monitor, and you will see correct behavior. then open the same app on the secondary monitor with a panel. you will see the bug.

**Comment by Vahan86** [comment]
@m00ster, is this still an issue for you in Cinnamon 3.0.x?

**Comment by Vahan86** [comment]
@JosephMcc, can we close the issue?

**Comment by m00ster** [comment]
This is no longer an issue on Cinnamon 3.X

Thanks!

**Comment by Vahan86** [comment]
@m00ster, thanks for reply. In this case can you please close the issue?
