### ISSUE TITLE
Wrong charging icon is shown when Bluetooth mouse is present

### ISSUE THREAD

**Issue by ghost** [linuxmint/Cinnamon#4225]
Hello!
I'm using Linux Mint 17.1 with Cinnamon 2.4.8.
When a Bluetooth mouse is present, its battery icon is shown instead of the laptop battery icon.
As you can see from the picture (couldn't take a screenshot) there is a mismatch between the two.
This is misleading since at a first glance I have no idea if the widget is reporting the status of my laptop battery or the status of the mouse battery, of which I honestly don't care.
Thank you.

![photo 29-05-2015 15 19 52](https://cloud.githubusercontent.com/assets/12660100/7883558/c91f00b8-0617-11e5-8f23-7de6c8f65b3d.jpg)

**Comment by pixunil** [comment]
The power applet was updated in 2.6. Can you try to update your cinnamon and muffin packages to 2.6 (romeo or [nightly](https://github.com/linuxmint/Cinnamon/wiki/Trying-out-the-latest-Cinnamon-without-building-it.)) and try to reproduce?

**Comment by Vahan86** [comment]
@JosephMcc, there is no responce from OP for 1 year. Can we close this issue?
