### ISSUE TITLE
Cannot Move Window Below Primary Display Panel

### ISSUE THREAD

**Issue by winder** [linuxmint/Cinnamon#4227]
I updated to Cinnamon 2.6.3 today and came across this problem.

I have my monitors configured in a C shape with the primary horizontal monitor ontop of another horizontal monitor and a vertical monitor to the right of both of these (screenshot 1). This has been a problem for Cinnamon until now since it wouldn't honor the primary display monitor. In 2.6.3 the first thing I noticed was the main panel showed up on the primary display (as it should! thank you!).

Unfortunately I'm not able to move any application windows to the bottom screen. I'll try to describe the behavior.

It seems like the header part of the window with the minimize and X buttons are what wont go below the panel (screenshot 3), I can make a window very tall so that it extends onto the lower monitor, but the top portion of the window locks at the panel.

I can move the window below the primary display panel on the vertical monitor, but when I drag it onto the lower monitor it can't go past the minimize and X buttons again (screenshot 2).

![screenshot from 2015-05-29 11 14 27](https://cloud.githubusercontent.com/assets/125509/7886444/29f1f794-05f8-11e5-9c8e-c064fb2cfe51.png)

![screenshot from 2015-05-29 11 43 57](https://cloud.githubusercontent.com/assets/125509/7886449/2fc24b1a-05f8-11e5-83af-07700f10e4db.png)

![screenshot from 2015-05-29 11 44 07](https://cloud.githubusercontent.com/assets/125509/7886455/32a56c36-05f8-11e5-9d27-f7997091c9ff.png)

**Comment by winder** [comment]
I tried leaving the bottom window as the primary display and adding a new panel to the top display. This time the programs couldn't be moved to the top display with the same sort of behavior.

**Comment by sshtmc** [comment]
I'm also affected by this.

**Comment by sshtmc** [comment]
Are there any updates? I would love to have this issue resolved...

**Comment by dlitster** [comment]
I am affected by this issue as well.  Cinnamon 2.6.7.  I can provide debugging information if needed.
![screenshot from 2015-08-07 13 21 36](https://cloud.githubusercontent.com/assets/5834364/9142795/a2673e8c-3d07-11e5-9d2d-81d0fa29c598.jpg)
![selection_021](https://cloud.githubusercontent.com/assets/5834364/9142826/e5f6a7f0-3d07-11e5-8d5c-46e7995ae15d.png)

**Comment by taurus-forever** [comment]
I am also affected by the issue (Cinnamon 2.6.13), cannot move window "below primary monitor".
Can someone share some workarounds here?
Tnx in advance!

**Comment by mtwebster** [comment]
Fixed by https://github.com/linuxmint/Cinnamon/commit/2bce9b50f9726320969de2b0f83b4446a36ffa33 and https://github.com/linuxmint/muffin/commit/72dacf50548811f3ff5f91ec1ebdc4f71e6d1450

**Comment by taurus-forever** [comment]
For the history:
workaround for the people who cannot wait for the fix to be released, 
use "Intelligently hide panel" mode. It will hide "panel" on a moment of
moving window through the panel which allows to move window under the panel.

P.S. Thank you for proper fix here!
