### ISSUE TITLE
Network icon not showing VPN connected

### ISSUE THREAD

**Issue by HalinReno** [linuxmint/Cinnamon#4228]
After the latest cinnamon update from Romeo repository, the network icon does not show it's connected to VPN (padlock over icon). It's possible that this problem was present with the update before this latest one. Can't remember if I used VPN before this latest update.
![screenshot from 2015-05-29 11 20 09](https://cloud.githubusercontent.com/assets/9020284/7889651/ac4526ce-05f5-11e5-8d98-799809414914.png)
 Thank you for your great work!

**Comment by dexx086** [comment]
I have the same issue, since I switched to LMDE2 in last october (actually I've never seen this icon changing).
Do you guys plan to fix this icon issue as it worked in the past as expected? Would be great to see in the systray whether you're connected to a VPN or not.

**Comment by Vahan86** [comment]
@HalinReno, is this still an issue in Cinnamon 3.0?

**Comment by kenden** [comment]
I didnt have the problem before Cinnamon 3, that's when it appeared for me. I had created a different issue because of that difference of version.
https://github.com/linuxmint/Cinnamon/issues/5527

**Comment by JosephMcc** [comment]
Ok. I'm going to close this one since the other provides more detailed info.
