### ISSUE TITLE
Icon theme changed to default gnome after logout / login

### ISSUE THREAD

**Issue by ghost** [linuxmint/Cinnamon#4230]
In Cinnamon 2.6.3 the icon theme is changed to default gnome after logout / login.
But in settings it's still the selected one (Mint-X-Aqua)

**Comment by mtwebster** [comment]
Where are you seeing this?  The desktop icons?  Or in the cinnamon panels?  The desktop issue should be fixed in nemo version 2.6.5

**Comment by Paviluf** [comment]
It's in the panel and the menu at least
![screenshot from 2015-05-30 03 27 46](https://cloud.githubusercontent.com/assets/2451563/7895107/4981d9ce-067c-11e5-997f-555a873fbdfc.jpg)

**Comment by Paviluf** [comment]
Also the window border color isn't right

**Comment by Vahan86** [comment]
Is this still an issue for you with Cinnamon 3.0?
