### ISSUE TITLE
detailed names of bluetooth headset devices

### ISSUE THREAD

**Issue by john-2000** [linuxmint/Cinnamon#4233]
Current implementation in the sound applet menu  shows all bluetooth headset devices as "Headset" - as both my bluetooth speaker (Edge.sound) and my headphones (Sennheiser MM400) are registered as headsets it would be better if the device was identified by its name.

For instance: 
Headset (Sennheiser MM400) 
Headset (Edge.sound)

This would just help using the sound applet menu
![headsets](https://cloud.githubusercontent.com/assets/12682796/7901902/3b3f4712-0798-11e5-9a47-d106443de962.png) 
**NB the image uploaded only had one bluetooth connection live**

**Comment by anandrkris** [comment]
I think this is fixed now, I can see name of my bluetooth speaker "JBL Flip" in Sound applet.
@JosephMcc  - Can be closed IMO.

![bluetooth_speaker](https://cloud.githubusercontent.com/assets/4663298/19161790/daa3d1ce-8c12-11e6-92b7-26e174624018.png)

![sound_settings](https://cloud.githubusercontent.com/assets/4663298/19161934/6a74e5e0-8c13-11e6-8110-e25cc4145a6b.png)

**Comment by JosephMcc** [comment]
@john-2000 Is this working for you now?

**Comment by john-2000** [comment]
totally ready to be closed! 

thanks developers!
