### ISSUE TITLE
gnome-terminal crashes under Cinnamon when overlay-scrollbar is installed and moving tabs between windows

### ISSUE THREAD

**Issue by margamanterola** [linuxmint/Cinnamon#4237]
Hi,

This is a very specific issue, that I've experienced in Ubuntu Trusty using cinnamon 2.2.16. It's possible that it's fixed in later versions, but currently I can't check this, sorry.

Preconditions for the bug to occur: have the overlay-scrollbar and dependant packages installed.
Steps to reproduce:
0. Log into a cinnamon session.
1. Open a terminal, maximize it, open a new tab in it, so you now have one maximized terminal with two tabs.
2. Open another terminal, not maximized.
3. Take the visible tab from the maximized terminal and drag it over to the non-maximized terminal.
4. If it hasn't crashed yet, drag it back.
5. repeat steps 3 and 4 until it is dead. It usually crashes on the first or second attempt.

This crashes under Cinnamon, but not under Unity. So I believe that the issue is actually related to the window manager getting confused because of the overlay-scrollbar being installed but cinnamon not taking it into account.

**Comment by lestcape** [comment]
@margamanterola The overlay-scrollbar require make some stuff in the gtk theme to then work properly. Why do you want to use the overlay-scrollbar? Normally this look bad, and on cinnamon worse. You can remove it from the gtk environment variables, when the cinnamon session init. I think the best will be disabled it, as like also you say, cinnamon don't used it and don't care.

Some patch like this:
https://github.com/linuxmint/cinnamon-session/pull/49
but in the cinnamon settings daemon. 

If some day this will be better supported can be removed.

**Comment by margamanterola** [comment]
Indeed, I don't want the overlay-scrollbar at all. But it's installed by default in Ubuntu.  Currently, any Trusty user will experience this until they realize that they need to remove overlay-scrollbar (there's no easy way to disable them on cinnamon only).

A patch like the one you mention probably would help yes.  In the meantime I've hacked something to remove the overlay scrollbar from GTK_MODULES variable during session startup.  It's hacky and ugly but it works for my usecase:

$ cat /etc/X11/Xsession.d/82cinnamon-session_disable-overlay-scrollbar 
# Disable Canonical's overlay-scrollbar if running under Cinnamon.
case "$DESKTOP_SESSION" in
  cinnamon)
    GTK_MODULES=$(echo "$GTK_MODULES" | tr ":" "\n" | egrep -v "^overlay-scrollbar$" | tr "\n" ":")
    export GTK_MODULES
  ;;
esac

This allows Unity to still have the overlay scrollbar while taking it away from cinnamon where it breaks things.

**Comment by lestcape** [comment]
This rule also look better that my crude hack... i think also cinnamon devs will want to do some thing, but all attempt clear will need to be a patch as this is only an invention of ubuntu. I use ubuntu, but shh...

**Comment by JosephMcc** [comment]
Closing this since the ubuntu specific overlay scrollbars are a thing of the past as of 16.04
