### ISSUE TITLE
Menu not populated

### ISSUE THREAD

**Issue by mellobob** [linuxmint/Cinnamon#4238]
When I log into Cinnamon desktop the standard menu (Main cinnamon menu) has no entries. If I wait for what seems to be at least 5 to 10 minutes AND do a menu->configure->edit->restore-default it will repopulate.

It was all working just fine the other day. I have to assume that some update clobbered this. Either that or I have a very odd setting?

All I have right now when I click on the menu applet is a search bar entry.

**Comment by mtwebster** [comment]
Are you using Romeo packages?  If so I think it was broken and already fixed, keep an eye out for new packages.

**Comment by mellobob** [comment]
No, not to my knowledge. Not sure how I would know ... but there doesn't seem to be anything "romeo" in my repositories:

apt-cache policy | grep -i cinn
 500 http://ppa.launchpad.net/gwendal-lebihan-dev/cinnamon-nightly/ubuntu/ vivid/main Translation-en
 500 http://ppa.launchpad.net/gwendal-lebihan-dev/cinnamon-nightly/ubuntu/ vivid/main i386 Packages
     release v=15.04,o=LP-PPA-gwendal-lebihan-dev-cinnamon-nightly,a=vivid,n=vivid,l=Cinnamon nightly builds,c=main
 500 http://ppa.launchpad.net/gwendal-lebihan-dev/cinnamon-nightly/ubuntu/ vivid/main amd64 Packages
     release v=15.04,o=LP-PPA-gwendal-lebihan-dev-cinnamon-nightly,a=vivid,n=vivid,l=Cinnamon nightly builds,c=main

Is this the same stuff? Should I change it? 

I'd back to using mate and I really do miss the nicer Cinnamon.

**Comment by collinss** [comment]
Looks like you're using the nightly ppa, which is actually updates more often than Romeo. The fix was made this morning, so it should be in the next update which will probably be tonight or tomorrow morning (depending on what part of the world you are in).

In the mean time (if I'm not mistaken), you should be able to do a Cinnamon restart (alt-f2, r, enter) to fix it.

**Comment by mellobob** [comment]
Okay, I'll have to wait a day or so then ... I'm in Pacific (north america) TZ.

Nope, Alt-f2 R Enter doesn't fix the problem

Thanks.

**Comment by mellobob** [comment]
I just discovered that if I use Cinnamon Software rendering the menu seems to work okay -- odd that hardware rendering would make a difference. I'll go with the software for a day or so, but it is painful :)

**Comment by grmblfrz** [comment]
I'm on arch linux. I found that killing cinnamon-settings-daemon brought the menu back to normal and also the program starter icons on the panel.

**Comment by dalcde** [comment]
It's fixed on git master and a new point release is made (2.6.7). Now you should go bug the arch maintainer to update the packages :)

**Comment by mellobob** [comment]
My nightlys updated last night and it seems to be working just fine now. BTW, version "appears" Cinnamon 2.6.6 ... but I don't think this is updated on the nightlys.

**Comment by collinss** [comment]
mellobob, that's because Cinnamon was tagged 2.6.7 this morning, so it hasn't made it into the nightlies yet.
