### ISSUE TITLE
[2.6.7] Power Management: spawning batteries

### ISSUE THREAD

**Issue by VolMi** [linuxmint/Cinnamon#4239]
This is a Debian stretch installation with Cinnamon et al. manually added from the LMDE2 romeo repository.

    :~$ cinnamon --version
    Cinnamon 2.6.7

In the Power Management, battery view, this happens when I unplug/replug the power cord several times:
http://www.file-upload.net/download-10661897/power-management_batteries.webm.html

verbal description:
I have only one battery in my Laptop. When I unplug the power adapter, the battery view is not updated, but a 2nd battery is added. When I plug in the adapter again, a 3rd and 4th battery is shown etc.

**Comment by leigh123linux** [comment]
Are you using systemd?

post

```
gsettings list-recursively  org.cinnamon.desktop.session
```

**Comment by VolMi** [comment]
> Are you using systemd?

Yes.

    ~$ gsettings list-recursively  org.cinnamon.desktop.session
    org.cinnamon.desktop.session session-manager-uses-logind false
    org.cinnamon.desktop.session session-name 'cinnamon'
    org.cinnamon.desktop.session settings-daemon-uses-logind false
    org.cinnamon.desktop.session idle-delay uint32 0
    org.cinnamon.desktop.session screensaver-uses-logind false

**Comment by leigh123linux** [comment]
Ok you need to turn on support for it


```
gsettings set org.cinnamon.desktop.session settings-daemon-uses-logind true
gsettings set org.cinnamon.desktop.session session-manager-uses-logind true
gsettings set org.cinnamon.desktop.session screensaver-uses-logind true
```

**Comment by VolMi** [comment]
Meh, thanks a lot! I was searching for 'systemd' in gsettings but did not find anything. When I found logind I thought this is the non-systemd way and let it at 'false'...

Okay, but unfortunately the problem still persists.

**Comment by leigh123linux** [comment]
I wonder if upower is mis-reporting

post

```
upower -d
```

**Comment by VolMi** [comment]
Discharging:

    ~$ upower -d
    Device: /org/freedesktop/UPower/devices/line_power_AC
      native-path:          AC
      power supply:         yes
      updated:              Di 02 Jun 2015 09:47:24 CEST (182 seconds ago)
      has history:          no
      has statistics:       no
      line-power
        warning-level:       none
        online:              no
        icon-name:          'ac-adapter-symbolic'

    Device: /org/freedesktop/UPower/devices/battery_BAT0
      native-path:          BAT0
      vendor:               Notebook
      model:                BAT
      serial:               0001
      power supply:         yes
      updated:              Di 02 Jun 2015 09:48:54 CEST (92 seconds ago)
      has history:          yes
      has statistics:       yes
      battery
        present:             yes
        rechargeable:        yes
        state:               discharging
        warning-level:       none
        energy:              49,6392 Wh
        energy-empty:        0 Wh
        energy-full:         55,9995 Wh
        energy-full-design:  53,28 Wh
        energy-rate:         2,12832 W
        voltage:             11,896 V
        time to empty:       23,3 hours
        percentage:          88%
        capacity:            100%
        technology:          lithium-ion
        icon-name:          'battery-full-symbolic'
      History (charge):
        1433231334	88,000	discharging
      History (rate):
        1433231334	2,128	discharging

    Device: /org/freedesktop/UPower/devices/DisplayDevice
      power supply:         yes
      updated:              Di 02 Jun 2015 09:48:54 CEST (92 seconds ago)
      has history:          no
      has statistics:       no
      battery
        present:             yes
        state:               discharging
        warning-level:       none
        energy:              49,6392 Wh
        energy-full:         55,9995 Wh
        energy-rate:         2,12832 W
        time to empty:       23,3 hours
        percentage:          88%
        icon-name:          'battery-full-symbolic'

    Daemon:
      daemon-version:  0.99.2
      on-battery:      yes
      lid-is-closed:   no
      lid-is-present:  yes
      critical-action: HybridSleep

Charging:

    ~$ upower -d
    Device: /org/freedesktop/UPower/devices/line_power_AC
      native-path:          AC
      power supply:         yes
      updated:              Di 02 Jun 2015 09:52:05 CEST (4 seconds ago)
      has history:          no
      has statistics:       no
      line-power
        warning-level:       none
        online:              yes
        icon-name:          'ac-adapter-symbolic'

    Device: /org/freedesktop/UPower/devices/battery_BAT0
      native-path:          BAT0
      vendor:               Notebook
      model:                BAT
      serial:               0001
      power supply:         yes
      updated:              Di 02 Jun 2015 09:52:05 CEST (4 seconds ago)
      has history:          yes
      has statistics:       yes
      battery
        present:             yes
        rechargeable:        yes
        state:               charging
        warning-level:       none
        energy:              48,8844 Wh
        energy-empty:        0 Wh
        energy-full:         55,9995 Wh
        energy-full-design:  53,28 Wh
        energy-rate:         7,7256 W
        voltage:             11,844 V
        time to full:        55,2 minutes
        percentage:          87%
        capacity:            100%
        technology:          lithium-ion
        icon-name:          'battery-full-charging-symbolic'
      History (charge):
        1433231454	87,000	discharging
      History (rate):
        1433231525	7,726	charging
        1433231525	14,636	charging
        1433231454	2,613	discharging

    Device: /org/freedesktop/UPower/devices/DisplayDevice
      power supply:         yes
      updated:              Di 02 Jun 2015 09:52:05 CEST (4 seconds ago)
      has history:          no
      has statistics:       no
      battery
        present:             yes
        state:               charging
        warning-level:       none
        energy:              48,8844 Wh
        energy-full:         55,9995 Wh
        energy-rate:         7,7256 W
        time to full:        55,2 minutes
        percentage:          87%
        icon-name:          'battery-full-charging-symbolic'

    Daemon:
      daemon-version:  0.99.2
      on-battery:      no
      lid-is-closed:   no
      lid-is-present:  yes
      critical-action: HybridSleep

Ok, maybe I should say that I use a self-configured kernel based on the vanilla 4.1.0-rc6 release. Later today I can test it with Debian's official kernel.

**Comment by VolMi** [comment]
Ok, I updated Cinnamon to 2.6.7 and muffin to 2.6.1 and tried the official 3.16.0-4-amd64 kernel. It's still the same problem. I updated the link to the screencast in the 1st post.

**Comment by leigh123linux** [comment]
Just tested here and I can reproduce it as well on fedora.

**Comment by clefebvre** [comment]
Can you confirm this happens only in the Power settings? and not in the applet itself?

**Comment by VolMi** [comment]
Yes, the applet is fine: A single battery all the time.
