### ISSUE TITLE
USB drive context menu shows both Eject and Safely remove drive

### ISSUE THREAD

**Issue by ghost** [linuxmint/Cinnamon#4240]
Hello!
I think that safely unmounting a USB drive should be "Safely remove drive", while ejecting a disc should be "Eject".
Why are both shown when right clicking the icon of a mounted device?
Isn't it a bit confusing for the end user?
Thank you

**Comment by lestcape** [comment]
@ghost sorry for use your issue, as is for the same applet, i don't want to open another...

Just i will add take a look to this behavior: https://github.com/lestcape/Drives-Manager/issues/10
As i don't see any report of the user. I don't think that encrypt a partition will be a common usage, but anyway.

**Comment by DevR00kie** [comment]
Please mark as closed, unable to see both Eject and "Safely Remove Drive" in the context menu of mounted drives as of Linux Mint 19.
