### ISSUE TITLE
[Feature request] Quickly mounting drives via the "Removable drives" applet

### ISSUE THREAD

**Issue by marmistrz** [linuxmint/Cinnamon#4241]
In Linux Mint the partitions which aren't specified to in fstab aren't mounted on boot. You need to open the file manager in order to mount them. You can also use third-party addons such as Places Center 2.1 so as not to launch the fm. 

It would be a great idea to use the "Removable drives" applet to mount the hard disk partitions without opening them in the fm. This would enhance the usability of this applet.

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html
