### ISSUE TITLE
Allow Main Panel Menu to be Horizontally Resized

### ISSUE THREAD

**Issue by ghost** [linuxmint/Cinnamon#4242]
It would be nice if the horizontal width of the panel (main) menu in Cinnamon could be resized by the user. This would help save some screen realestate when using the menu, but needing to see a window in the background while doing so. Windows 10 now has the feature and I would love to see it ported over to Cinnamon.

**Comment by SaeedIranzad** [comment]
Yes, I am willing to resize panel width just to the size of applets which I need to have an eye on them every second I need.
(cpu, core temp, data traffic which can not be seen on a dock.)

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html
