### ISSUE TITLE
No options in shutdown menu [Arch, Cinnamon 2.6.6]

### ISSUE THREAD

**Issue by ion201** [linuxmint/Cinnamon#4244]
Arch Linux
Kernel 4.04
Lightdm 1.14.0-3
Cinnamon 2.6.6
Nemo 2.6.5-1

When selecting menu -> shutdown or user-tray-icon -> power off: I get the following popup which doesn't have any selectable options:
 
![shutdown-screenshot](https://cloud.githubusercontent.com/assets/6099993/7951326/f887fc88-095a-11e5-9b63-607474f08048.png)

This started happening after upgrading from 2.4 and persists after a reinstall. The "log off" menu appears as expected.

**Comment by dalcde** [comment]
https://bugs.archlinux.org/task/45174
