### ISSUE TITLE
2.6.7 - Regression ? Battery applet does not let you show time remaining

### ISSUE THREAD

**Issue by Myu-Unix** [linuxmint/Cinnamon#4245]
On Cinnamon 2.4 series, the battery applet used to be able to display the time remaining, on 2.6.7, it doesn't seems possible anymore (option is not here).

Could this be a regression ? It was a convenient feature.

Cheers and thanks for your work on Cinnamon !

**Comment by leoluk** [comment]
Yes, would be nice to get it back!

**Comment by Vahan86** [comment]
I agree, it was really useful feature...

**Comment by numian** [comment]
This was really useful, please put it back, or at least as an option.

In the meanwhile, I've changed a little bit the applet to get the time remaining.
It's here https://github.com/numian/cinnamon-power-applet if anyone need it too.
This version ignores the "show percentage" option.

**Comment by Vahan86** [comment]
This issue is fixed in Cinnamon 3.0.7. 

![untitled](https://cloud.githubusercontent.com/assets/12819058/18698981/3cf96824-7fdf-11e6-9346-b747f9d055cb.png)
