### ISSUE TITLE
Window Quick List applet doesn't truncate long window titles

### ISSUE THREAD

**Issue by michael-lopiccolo** [linuxmint/Cinnamon#4247]
Expected behavior: When a window has a very long title, the applet will cut it off at a reasonable length
Actual behavior: The applet attempts to display the entire title and goes off the edge of the screen

I have two monitors, which may have been a factor.

Linux Mint 17.1 Cinnamon 64-bit
Cinnamon 2.4.8
Linux Kernel 3.13.0.37-generic

Edit: I replicated this without two monitors. I got a long window title by using the Chatzilla Firefox extension and joining a channel with a long MOTD.

**Comment by dalcde** [comment]
Fixed in 2.6
