### ISSUE TITLE
Menu Issues since update to 2.6.6

### ISSUE THREAD

**Issue by eiabea** [linuxmint/Cinnamon#4249]
I updated from 2.4.8 to 2.6.6 and now the menu is broken
All launcher icons also disappeared

![screenshot from 2015-06-03 20-28-08](https://cloud.githubusercontent.com/assets/688128/7968214/84fdecb6-0a2f-11e5-9c8e-3104605056ef.png)

**Comment by eiabea** [comment]
Removing Applet and adding it again fixed the issue

**Comment by eiabea** [comment]
After a reboot it breaks again (screenshot)

CPU Usage is also very high

**Comment by dalcde** [comment]
Fixed in 2.6.7
