### ISSUE TITLE
Show desktop alternates between last two focused windows

### ISSUE THREAD

**Issue by kevlogan90** [linuxmint/Cinnamon#4250]
I'm not entirely sure if this is a bug or intentional, but when using the show desktop hot corner it will focus on the previous window instead of the current window. So if I were to use this hot corner it will keep switching between the last two focused windows. I'm currently using cinnamon 2.6.7, but this was in 2.4 as I recall.

**Comment by mtwebster** [comment]
Fixed by https://github.com/linuxmint/muffin/commit/8bdd4252b8e0b736c82a9bb0896bcb7d16964de2
