### ISSUE TITLE
Desklets only on certain workspaces

### ISSUE THREAD

**Issue by kevlogan90** [linuxmint/Cinnamon#4251]
I think it would be nice to have a way for a desklet to only appear on a certain workspace instead of all workspaces.

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html
