### ISSUE TITLE
Volume OSD Positioning Incorrect When Secondary Display on Left-Hand Side

### ISSUE THREAD

**Issue by zyisrad** [linuxmint/Cinnamon#4252]
### When the secondary display is on the right, the volume OSD displays correctly on the primary monitor
![screenshot from 2015-06-03 12-36-25](https://cloud.githubusercontent.com/assets/6982053/7969676/74305b18-09ed-11e5-86a4-7c4da29568b0.png)

### When the secondary display is on the left, the OSD displays incorrectly on the secondary monitor
![screenshot from 2015-06-03 12-36-48](https://cloud.githubusercontent.com/assets/6982053/7969715/ab54640e-09ed-11e5-9631-7521c49e3503.png)

Linux 4.0.4-2-ARCH #1 SMP PREEMPT Fri May 22 03:05:23 UTC 2015 x86_64 GNU/Linux
Cinnamon 2.6.6-1 and 2.6.7-1
Any Theme

**Comment by JosephMcc** [comment]
Does a cinnamon restart straighten this out?

**Comment by zyisrad** [comment]
It is persistent through a cinnamon restart, reboot, and trashing of all dconf and cinnamon folders in home. I also tried using a blank user. Same outcome.

**Comment by zyisrad** [comment]
Fixed in Pull Request https://github.com/linuxmint/Cinnamon/pull/4260
