### ISSUE TITLE
[Cinnamon 2.6] Workspace window drag causing rendering glitches with window effects

### ISSUE THREAD

**Issue by TTSpaxxy** [linuxmint/Cinnamon#4253]
Whenever I drag a window from one workspace to another using the keyboard shortcut, the window renders oddly upon further workspace switching. When switching to an adjacent workspace, it doesn't get swept off to the side like the other windows do, instead, it stays on the screen for the duration of the switch effect. Similarly, it shows up on screen before the other windows do when switching back to the workspace containing it. Oddly, this only happens to one window at a time. Dragging another window across workspaces cancels out the effect on the first window, and the first window renders normally. If this description isn't making sense, I made a screen capture of this happening that you can see here: https://youtu.be/ZdUtPlm8stc

I'm running LMDE Betsy 64 bit with Cinnamon version 2.6.7 and kernel version 3.16.0-4-amd64. My graphics hardware is 3rd generation Intel integrated graphics.

**Comment by dalcde** [comment]
The first effect is intended. If you are dragging a window with you, it stays on the screen.
