### ISSUE TITLE
Some text and lines got missing from the System Monitor using the Adwaita Controls

### ISSUE THREAD

**Issue by AXDOOMER** [linuxmint/Cinnamon#4254]
I have Cinnamon 2.4.8. Running Linux Mint 17.1 updated. Kernel version 4.0.4. 

![screenshot from 2015-06-04 02 17 44](https://cloud.githubusercontent.com/assets/6194072/7978231/02b0da48-0a61-11e5-9c02-b1e61a8b651a.png)

**Comment by dalcde** [comment]
Are you sure it is a Cinnamon bug?

**Comment by leigh123linux** [comment]
I've never seen this issue before, it's got to a system-monitor issue.

![screenshot-screen-2015-06-04-111738](https://cloud.githubusercontent.com/assets/1299302/7982070/be7f79ec-0aab-11e5-911d-423093b4a8d4.png)

**Comment by AXDOOMER** [comment]
It happens if you use the Adwaita Controls. Go on the Themes panel and chose Adwaita. It's not a problem with other controls like Mint-X or High Contrast.

**Comment by leigh123linux** [comment]
@AXDOOMER  then it's a awaita issue, file a bug against that instead.

**Comment by AXDOOMER** [comment]
@leigh123linux This repository?
 https://github.com/leigh123linux/Adwaita-Cinnamon

**Comment by leigh123linux** [comment]
No it's provided by ubuntu (Linuxmint uses it as a base) repository

https://help.ubuntu.com/community/ReportingBugs

**Comment by AXDOOMER** [comment]
@leigh123linux  Ok, thanks for the hint!
