### ISSUE TITLE
[Bug] Menu - Rightclick on recent files gone

### ISSUE THREAD

**Issue by ManIVIctorious** [linuxmint/Cinnamon#4256]
Was there any reason to remove this feature? I think it was one of the most handy features in the menu

**Comment by clefebvre** [comment]
Yes, performance. It was a niche feature and it cost a lot.

In the vast majority of cases you just launch the default mime handler. For particular cases it's also possible to open Nemo on recent files and either select other apps there or reassign mimes.

Last but not least, any 3rd party applet can specialize in recent documents and push things further to provide similar features.
