### ISSUE TITLE
Binding Super-Shift-Down to "Minimize window" no longer works

### ISSUE THREAD

**Issue by leoluk** [linuxmint/Cinnamon#4257]
Cinnamon 2.6.4, worked fine in 2.4. Binding to Super-Alt-Down works fine.

**Comment by ManIVIctorious** [comment]
I can confirm this bug for cinnamon 3.0.7 on arch linux.
This seem to be expandable to all Super+Shift shortcuts (although I have only tried a few)

**Comment by JosephMcc** [comment]
Doesn't work here either.

**Comment by tsoernes** [comment]
Super-Shift-Up works here, but not Super-Shift-Down

**Comment by tsoernes** [comment]
This can be solved by installing a dconf editor, going to `org.cinnamon.desktop.keybindings.wm` and deleting the shortcuts for `move-to-monitor-up` and `move-to-monitor-down` which by default occupy Super-Shift-Up and Super-Shift-Down.

It can probably be done in the Settings app as well, which clearly lack keybinding conflict detection.
