### ISSUE TITLE
Menu and panel shortcuts aren't populated after boot

### ISSUE THREAD

**Issue by madopal** [linuxmint/Cinnamon#4258]
In version 2.6.6, it appears that the menu and panel shortcuts don't get populated after a boot. The menu is blank except for the query box, and the shortcuts are missing except for "show desktop".

They can be restored in the following manner:
Menu - right click on menu, choose Configure..., click on Open the menu editor, and check properties of any listed object. The menu then shows back up.
Shortcuts - after restoring the menu, right click on any item and choose "Add to Panel". After that, the new shortcut will be added, and any existing shortcuts will show back up.

I'm running Fedora 22, and I've got the top/bottom panels enabled (was it called Classic mode?) from a previous version. My menu and shortcuts are on the top panel.

**Comment by dalcde** [comment]
Fixed in 2.6.7, which should land on Fedora soon.
