### ISSUE TITLE
2.6.7 - Panels no longer scale with text-scaling-factor

### ISSUE THREAD

**Issue by leoluk** [linuxmint/Cinnamon#4259]
In Cinnamon 2.4, you could set scaling-factor to 2 and text-scaling-factor to a fraction (like 0.75), and the windows titles and the panels would be sized down accordingly. This no longer works.

**Comment by dalcde** [comment]
I'm not sure what changed, but if I set the text scaling factor to < 1, I would expect the text to shrink. Not everything. The window titlebar/panel is not text. It is an object on its own and I would expect it to scale according to scaling-factor.

**Comment by leoluk** [comment]
The text-scaling-factor can be set to non-integer values, whereas the scaling-factor cannot, so the previous behaviour was quite convenient and consistent with (at least) GTK and Qt. This is important if you, for some reason, want non-integer scaling factors.

**Comment by leoluk** [comment]
Actually, I just discovered that the panel height can be customized and the contents resized to fit, which solves my issue.

**Comment by dalcde** [comment]
Closing then. The expected behaviour of scaling text should be scaling text, not some random things that contain text.

**Comment by leigh123linux** [comment]
The default setting was changed so it scales properly in all cases, if you want the old behavior set it to off in panel settings. 

https://github.com/linuxmint/Cinnamon/commit/ac7bf525e3061f0b93e8b0684b1c28b0af0baf71
