### ISSUE TITLE
'Refresh' button in Network Manager applet

### ISSUE THREAD

**Issue by pacharanero** [linuxmint/Cinnamon#4263]
When viewing the list of available networks in the Network Manager Applet, when you know a new network is available, there is often a lag before the new network is visible. I presume that the network manager polls periodically/regularly to look for new networks, but I'm unsure of the interval at which it does this. Would it be possible to have a 'refresh' button on the drop-down left-click menu, that would refresh the list of available networks?

**Comment by Lupul** [comment]
+1
A 'refresh' button would be extremely helpful.

**Comment by Vahan86** [comment]
+1

**Comment by Vahan86** [comment]
@JosephMcc, Issue https://github.com/linuxmint/Cinnamon/issues/1054

**Comment by Sawiq** [comment]
+1 Would be lovely.
