### ISSUE TITLE
Segfault libgtk-3 when starting WebStorm

### ISSUE THREAD

**Issue by dirkk** [linuxmint/Cinnamon#4264]
I just upgraded from Fedora 20 to 22 and I am experiencing a complete cinnamon shutdown when trying to start IntelliJ WebStorm. `dmesg` shows:

```
[206464.411199] cinnamon[7266]: segfault at 30 ip 00007f0e2f2cf833 sp 00007ffd354ca7f0 error 4 in libgtk-3.so.0.1600.3[7f0e2f02a000+6da000]
[206471.996163] cinnamon[7991]: segfault at 30 ip 00007fc24b9f2833 sp 00007ffd2ffe2140 error 4 in libgtk-3.so.0.1600.3[7fc24b74d000+6da000]
[206479.966535] cinnamon[8132]: segfault at 30 ip 00007f39f8b67833 sp 00007ffe9b982800 error 4 in libgtk-3.so.0.1600.3[7f39f88c2000+6da000]
[207489.076165] input: 6C:AD:F8:44:38:8E as /devices/virtual/input/input12
[208034.373152] cinnamon[9613]: segfault at 30 ip 00007f31abcfe833 sp 00007ffeaacb0b20 error 4 in libgtk-3.so.0.1600.3[7f31aba59000+6da000]
[208040.794920] cinnamon[11309]: segfault at 30 ip 00007fe745b91833 sp 00007ffef864a750 error 4 in libgtk-3.so.0.1600.3[7fe7458ec000+6da000]
[208675.929973] cinnamon[15266]: segfault at 30 ip 00007fd6d6f5d833 sp 00007ffe4f96d6a0 error 4 in libgtk-3.so.0.1600.3[7fd6d6cb8000+6da000]
[208681.688849] cinnamon[15929]: segfault at 30 ip 00007fcb6333a833 sp 00007fff99b8c210 error 4 in libgtk-3.so.0.1600.3[7fcb63095000+6da000]
```

For reference, `uname -a` shows

```
Linux localhost.localdomain 4.0.4-301.fc22.x86_64 #1 SMP Thu May 21 13:10:33 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

The problem does not appear when running a GNOME session, so I guess somehow cinnamon is causing this.

**Comment by leigh123linux** [comment]
Did you consider the upgrade might have screwed your installation.
wstorm works here without issue.

![screenshot-screen-2015-06-10-131540](https://cloud.githubusercontent.com/assets/1299302/8082162/04380604-0f73-11e5-9c0d-66649d5c7c48.png)

**Comment by leigh123linux** [comment]
Can you post the output for

```
rpm -qa cinnamon\* nemo\* muffin cjs
package-cleanup --problems
package-cleanup --dupes
```

**Comment by dirkk** [comment]
`rpm -qa cinnamon\* nemo\* muffin cjs |sort`

```
cinnamon-2.6.7-2.fc22.x86_64
cinnamon-control-center-2.6.0-3.fc22.x86_64
cinnamon-control-center-filesystem-2.6.0-3.fc22.x86_64
cinnamon-desktop-2.6.4-2.fc22.x86_64
cinnamon-menus-2.6.0-1.fc22.x86_64
cinnamon-screensaver-2.6.3-2.fc22.x86_64
cinnamon-session-2.6.1-1.fc22.x86_64
cinnamon-settings-daemon-2.6.1-1.fc22.x86_64
cinnamon-translations-2.6.2-1.fc22.noarch
cjs-2.6.0-1.fc22.x86_64
muffin-2.6.1-1.fc22.x86_64
nemo-2.6.5-1.fc22.x86_64
nemo-extensions-2.6.5-1.fc22.x86_64
nemo-fileroller-2.6.x-1.fc22.x86_64
nemo-preview-2.6.x-1.fc22.x86_64
```
`package-cleanup --problems`

```
Yum-utils package has been deprecated, use dnf instead.
See 'man yum2dnf' for more information.


Loaded plugins: langpacks
No Problems Found
```

`package-cleanup --dupes`

```
Yum-utils package has been deprecated, use dnf instead.
See 'man yum2dnf' for more information.


Loaded plugins: langpacks
```

So I can't really see any problems here...

**Comment by leigh123linux** [comment]
Have you got the abrt report that this crash would generate as the backtrace would be useful.

**Comment by dirkk** [comment]
I uploaded the report using gist, you can find it here: https://gist.github.com/dirkk/3005315bc4d4cee7ee7d
Any help is appreciated!

**Comment by leigh123linux** [comment]
Looks muffin related, can you post

```
gsettings get org.cinnamon.desktop.wm.preferences theme
```

**Comment by dirkk** [comment]
gsettings get org.cinnamon.desktop.wm.preferences theme
    'Clearlooks'

**Comment by leigh123linux** [comment]
Ok try default and see if the issue still reproduces

```
gsettings reset org.cinnamon.desktop.wm.preferences theme
```

**Comment by dirkk** [comment]
Unfortunately, yes. Same thing happens. I also tried various themes, its all the same.

**Comment by df-jablan** [comment]
Any news about this? I'm having the same issue.

**Comment by lucifurious** [comment]
I'm having this issue as well, but only with Ubuntu 15.04.

```
 Aug 16 18:58:25 azrael kernel: [83144.213877] cinnamon[8205]: segfault at 30 ip 00007fc0d238c063 sp 00007ffda9eebce0 error 4 in  libgtk-3.so.0.1400.13[7fc0d2108000+6b1000]
 Aug 16 18:59:13 azrael cinnamon-session[8067]: WARNING: Application 'cinnamon.desktop' killed by signal 11
```
On my Linux Mint system running Cinnamon, I don't have this issue. It looks like a libgtk-3 issue to me.

**Comment by ThomasJunk** [comment]
Same goes here: Archlinux
Kernel: 4.1.6-1-ARCH #1 SMP PREEMPT
gsettings get org.cinnamon.desktop.wm.preferences theme
'Yosemite-Shelll'
pacman -Qs cinnamon
local/cinnamon 2.6.13-3

Aug 26 22:58:06 $boxname cinnamon-session[9163]: CRITICAL: We failed, but the fail whale is dead. Sorry....
Aug 26 22:58:06 $boxname cinnamon-session[9163]: WARNING: App 'cinnamon.desktop' respawning too quickly
Aug 26 22:58:06 $boxname kernel: cinnamon[9652]: segfault at 30 ip 00007f20f2741c83 sp 00007ffdcfffd800 error 4 in libgtk-3.so.0.1600.6[7f20f249c000+6d9000]

This is with every Jetbrains product I use (Intellij, PyCharm).

**Comment by df-jablan** [comment]
@ThomasJunk I have a second system with the latest LinuxMint and Cinnamon and have no issues. The problem/bug appears to be in the version/rev of `libgtk3` being shipped with Ubuntu 15.04

**Comment by ThomasJunk** [comment]
@df-jablan Hey, thanks for the feedback so far. 
As I said, I run an _Archbox_ not Ubuntu, so: happy Ubuntu folks and poor me ;)
I just ran 

```
ldconfig -v | grep libgtk-3.so
libgtk-3.so.0.1600.6
```

According http://packages.ubuntu.com/vivid-updates/amd64/libgtk-3-0/filelist Ubuntu folks run
_libgdk-3.so.0.1400.13_ (Mint - when I looked correctly uses _libgdk-3.so.0.1400.05_) Yay!

Which possibly explains 
>This issue does not occur in Gnome or Unity on 15.04, which is curious.

And then it is not so curious ;)

>You could have a corrupted webide cache

I could rule that one out, since it was a fresh set up Archbox and fresh install of Intellij and Pycharm.

>If you still have the issue then it's probably the libgtk bug.

At least, I am able to say, that the bug is somehow related to libgtk.

During startup, there are two complete restarts of cinnamon (due to a segfault). Either one is somehow triggered, when the java application simply spawns windows:

1) Splash screen leads to segfault
2) When the application window as such opens leads to a second restart due to a segfault

Initially, the bug showed up with WebStorm, but I am adding Intellij and Pycharm to the table, so that it is not limited to one IDE.

The question is how to get the issue fixed?

**Comment by df-jablan** [comment]
@ThomasJunk PhpStorm, WebStorm, PyCharm and IntelliJ **all** share a common code base as far as I know. So the IDE difference may not be relevant.

**Comment by df-jablan** [comment]
@ThomasJunk if we know 1400.05 works, a downgrade should fix you right up.

**Comment by ThomasJunk** [comment]
@df-jablan 

> if we know 1400.05 works, a downgrade should fix you right up.

Nope: 
```
Aug 27 22:07:01 Oberon cinnamon-session[1305]: CRITICAL: We failed, but the fail whale is dead. Sorry....
Aug 27 22:07:01 Oberon cinnamon-session[1305]: WARNING: App 'cinnamon.desktop' respawning too quickly
Aug 27 22:07:00 Oberon kernel: cinnamon[1825]: segfault at 30 ip 00007f9ac4d23793 sp 00007ffcb920c340 error 4 in libgtk-3.so.0.1400.5[7f9ac4aa1000+6a5000]
```

For some strange reason: same here ... -.-

**Comment by lucifurious** [comment]
I give. :)

---
Imagine something witty here...

**Comment by ThomasJunk** [comment]
Everything works fine (again) with libgtk-3.so.0.1800.1.
Thank you for ...

**Comment by df-jablan** [comment]
Cool. Thanks for letting me know. I can go back to Cinnamon now. Yay! Gnome makes me feel sad inside. :(

**Comment by Vahan86** [comment]
@dirkk, is this still an issue in Cinnamon 3.2?

**Comment by dirkk** [comment]
@Vahan86 No, with my current setup (Fedora 25, Cinnamon 3.2.7) this issue does not occur anymore, at least for me.
