### ISSUE TITLE
 Ülease get gtk3 css definition to be similar to cinnamon themes in future! 

### ISSUE THREAD

**Issue by bluedxca93** [linuxmint/Cinnamon#4265]
Hi,
in cinnamon themes you can simply write: border-image: url("XXX.png") YZ; 
on gtk2 it was:
engine "pixmap"
  {
    image
    {
      file				= "XXX.png"
      border			= {YZ, YZ, YZ, YZ}
      stretch			= TRUE
    }
}

Its very very time intensive to devellop a good gtk3  theme without having the possibility to use a normal stretched bitmap as temporary working solution. Clear that its slower than css definitons but why is that disabled ? To hide the real speed of gtk3? Or are theme devellopers  technically bound to 2nd quality png2css tools even for very early theme devellopment for gtk3?
On gtk2 there were so much themes and ways to dewsign a theme  on gtk3 version i do see the few existing themes see breaking every half year.
Css definitons for more complex borders, background etc.   changes from time to time . What to do??The step from gtk3.2 to 3.6 was horrible, now ( 3.8-3.16) its luckily not as big but also miss a good reference/knowledge base.Its better to have a slow theme working stable than a fast flat one without any creativity in my opinion.

Hope that gtk3 theming on cinnamon follows soon a minimal standard allowing designers to do at least the same options stable for gtk3 as on cinnamon. Please do not the current garbage, meaning no 2nd inline borders, no gtk3 scrollbar handles, no easy background/border tiling continue in future.

This is a real issue, bug and problem. Not something to write on a wishlist or a feature request. Assune its possible to do with a simple gtk3 engine, if they haven`t been even droppped.

**Comment by dalcde** [comment]
Cinnamon does nothing related to gtk themes at all. Go bug the gtk developers. We are also very annoyed, but there is nothing we can do.
