### ISSUE TITLE
Unable to add complex commands in menu editor

### ISSUE THREAD

**Issue by marmistrz** [linuxmint/Cinnamon#4266]
It's impossible to change the command of a menu item to `LANG=pl_PL.UTF8 myexec` even when the command is perfectly valid.

**Comment by mtwebster** [comment]
It's because the library function we use to check validity thinks it *isn't* valid - for a workaround you can wrap it like this:

`sh -c "LANG=pl_PL.UTF-8 myexec"`

I'll try to fix for 2.6

**Comment by marmistrz** [comment]
The same happens in the alt+f2 menu

**Comment by ManIVIctorious** [comment]
Is this still an issue in cinnamon 3.0?

**Comment by JosephMcc** [comment]
I'm going to mark this as a feature request since it is currently possible to do as @mtwebster pointed out.

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html
