### ISSUE TITLE
Option to disable tooltips in Window list Applet

### ISSUE THREAD

**Issue by simonwiles** [linuxmint/Cinnamon#4267]
The mouseover tooltips in the window list applet frequently get in my way (most noticeably if I use the mouse to activate my terminal emulator, and then I get a popup which covers the active line I'm typing on), and they strike me as almost entirely superfluous anyway (esp. if using the option to allow the window buttons to use lots of space).  Would it be possible to have an option to disable them?

**Comment by dalcde** [comment]
No (#4269)
