### ISSUE TITLE
Window list "move to the other monitor" doesn't show # of monitor

### ISSUE THREAD

**Issue by tp0** [linuxmint/Cinnamon#4271]
I guess this was changed on purpose in 2.6, but in my opinion the old way was better:

**2.4:** _Move to monitor #_ (I think this is what it said word to word, but in any case it showed the number of the monitor)
**2.6:** _Move to the other monitor_

This creates confusion especially when a window is minimized and adds unneeded user memory load since nothing on the window list itself indicates on which monitor the window is on.

![untitled](https://cloud.githubusercontent.com/assets/5863551/8015856/2629362a-0be5-11e5-81ac-2e0295866ceb.png)

**Comment by RavetcoFX** [comment]
This is done on purpose, so if you have exactly 2 monitors, it will say "Move to the other monitor" while if you have 3+ monitors it will say "Move to Monitor X"

**Comment by tp0** [comment]
> This is done on purpose, so if you have exactly 2 monitors, it will say "Move to the other monitor" while if you have 3+ monitors it will say "Move to Monitor X"

Makes sense and clearly I didn't think about this (since I have only two monitors), but the problem stands for dual display and problem being that both monitors are called "other monitor". Bad change.
