### ISSUE TITLE
Can not move/resize tiled window with arrow keys 

### ISSUE THREAD

**Issue by tp0** [linuxmint/Cinnamon#4272]
Repro:
1. open some window and tile/snap it
2. activate window menu (by mouse or by specified shortcut key)
3. select "Move" or "Resize"
4. try to move or resize window with arrow keys

What goes wrong:
Nothing happens for as long as the window is in tiled/snapped state.

What does work: doing the moving or resizing by mouse

Cinnamon 2.6.7 (but not a 2.6 regression: this has been broken at least since 2.4... if this has ever worked?)

**Comment by Vahan86** [comment]
Tested in Cinnamon 3.0.7. It's working fine for me.

@tp0, is this still an issue for you in Cinnamon 3.0.x?

**Comment by JosephMcc** [comment]
Works here on git master as well.
