### ISSUE TITLE
[Bug] Scale mode not aligned properly when 3 windows open

### ISSUE THREAD

**Issue by kevlogan90** [linuxmint/Cinnamon#4273]
If 3 windows are open and scale mode is activated, then the top row close buttons are slightly cut off. This also occurs with 4, 7, 8, and 9 windows, however, not with 5 or 6 windows. I haven't tried with more than that.

**Comment by dalcde** [comment]
Any screenshots? What theme are you using?

**Comment by kevlogan90** [comment]
This occurs on my laptop, but not my desktop. Only a couple pixels are cut off with the Linux Mint Theme. The Zukitwo Theme has almost half cut off.
![Uploading Mint.png…]()

![Uploading Zukitwo.png…]()

**Comment by kevlogan90** [comment]
This only occurs on my laptop, but not on my desktop. The Linux Mint Theme only has a couple of pixels cut off, but the Zuktiwo Theme almost has half. 

![mint](https://cloud.githubusercontent.com/assets/8071070/8025112/932e2032-0d07-11e5-9cc5-a13db777c8cf.png)


![Zukitwo](https://cloud.githubusercontent.com/assets/8071070/8025103/56cd87c2-0d07-11e5-9987-652dc4bc60f2.png)

**Comment by JosephMcc** [comment]
I can't reproduce this regardless of the number of windows I have open but I do notice a couple of things in your screenshot:

1. Something looks off with your window border theme. Could you try switching to the Mint-X theme and see if it sorts things out just to eliminate it as a cause.

2. Where is the window border on your Firefox window? Are you doing something to remove/hide it? If so undo it and see if that fixes the issue.

**Comment by kevlogan90** [comment]
I am using the Maximus extension to remove the border on full screen windows. I did a fresh install of the Cinnamon-RC and everything seems to work now even with the Maximus and all themes are working that I've tested.
