### ISSUE TITLE
Applets/Desklets Feature Request: Delay on start

### ISSUE THREAD

**Issue by Mintulix** [linuxmint/Cinnamon#4274]
Sometimes the weather applet and desklets load before the wlan connection is established. For half an hour (default) they're not updated. Is this something that should be addressed in the specific applets/desklets or is a global delay the better solution?

**Comment by lestcape** [comment]
I will recommend not delay anything and speak with the authors about this issue instead, for the reasons below:
1- You not need to set your wireless on auto-connect mode. So, the connection would occur on start or could occur afterwards, as this is a user decision. i.e. Any start of an applet not mean is ready to provide a functionality.
2- Is easy add a flag to check if the download not occurs and increase the update frequency in this case.
3- Any delay in the start  of applets or desklets make it difficult to implement an option to drag a drop (for example) and possible other features.

**Comment by Mintulix** [comment]
Hola Lester, you're absolutely right. A check flag would be great. I have this problem since I use an SSD and Cinnamon starts "too fast" ;-).

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html
