### ISSUE TITLE
fails to start on multiple screen configuration

### ISSUE THREAD

**Issue by brianjmurrell** [linuxmint/Cinnamon#4276]
I have a dual-head configuration but rather than having a single logical screen (:0.0) I have opted for separate screens (:0.0 and :0.1).  Without debating the merits of one over the other, Cinnamon fails to start in dual-screen mode with:

```
Window manager warning: Log level 8: gdk_display_get_screen: assertion 'screen_num == 0' failed
Window manager warning: Log level 8: gtk_window_set_screen: assertion 'GDK_IS_SCREEN (screen)' failed
Window manager warning: Log level 8: gdk_display_get_screen: assertion 'screen_num == 0' failed
Window manager warning: Log level 8: gdk_screen_get_setting: assertion 'GDK_IS_SCREEN (screen)' failed
```

This is also filed in a [ticket](https://bugzilla.redhat.com/show_bug.cgi?id=1066987) downstream at Red Hat with all of the usual abrt collateral.

Would love to have Cinnamon here on my dual-screen, but I cannot give up the independence of dual-screens (i.e. changing workspaces on one screen does not change workspaces on the other).

**Comment by dalcde** [comment]
Have you tried running GNOME shell? I am under the impression that gdk no longer supports using multiple screens in the same display, and there is nothing we can do to help. I might be wrong, though.

**Comment by clefebvre** [comment]
Hi,

I don't really know if that's possible either (i.e. if the toolkit/libs layer underneath Cinnamon/Muffin allow it).

Just to add a bit of info on "changing workspaces on one screen does not change workspaces on the other" though --> that's possible with the option org.cinnamon.muffin workspaces-only-on-primary set to true... for the primary monitor at least.

**Comment by brianjmurrell** [comment]
@clefebvre Thanks for the comment.  Could you expand enough on your doubts about the toolkit enough for me to write up a ticket for the GTK/GDK folks?  What are the assertions that are failing?  And are those what is causing the fallback mode or are they just fallout of that?

As for org.cinnamon.muffin workspaces-only-on-primary that precludes having a set of workspaces on the secondary monitor though doesn't it?

Using MATE currently, I have two screens each with 4 workspaces on them and I can switch each screens' workspaces independently of the other.  That's the functionality I am looking for in Cinnamon.

**Comment by JosephMcc** [comment]
As noted the toolkits/libs we use don't support this. Please open a separate issue for the other request, using separate workspaces per monitor.

**Comment by ManIVIctorious** [comment]
@JosephMcc already reported in #3507

**Comment by JosephMcc** [comment]
@ManIVIctorious yep, sorry ;)
