### ISSUE TITLE
sliding from workspace to another in scale mode

### ISSUE THREAD

**Issue by aminehmida** [linuxmint/Cinnamon#4277]
### To reproduce
1. open scale
2. click on an empty space and try to slide the the next workspace
3. release the cursor half-way 
### what should happen

The first workspace is switched back
### what happen

It is just hanging there: you can not select any workspace and when you move the mouse you get the sliding effect without being able to select any workspace. Your only option is to use the keyboard ( esc ) to exit the scale mode. You can not click the tool bar anymore it just ignore the mouse left clicks(I think because cinnamon think that it is still sliding) and you need to right click the toolbar and navigate to [troubleshoot] --> [Restart Cinnamon]
### system informations

```
cinnamon --version : 
Cinnamon 2.4.8 (and 2.6.7)
```

**update** : this happens in scale mode not in expo mode. I don't know how to edit the title.

**Comment by dalcde** [comment]
Not reproduced. Do you mean scale instead of expo? Does this happen consistently?

**Comment by aminehmida** [comment]
Yes, I am really sorry. This happens in scale mode not in expo mode. I was confused with the names.
I have updated the bug report but I cant change the title. should I reopen an other bug ?

**Comment by aminehmida** [comment]
Hi, any news on this : can I help you on debugging this bug ? I just don't know where to start

**Comment by Vahan86** [comment]
@aminehmida, is this still an issue for you in Cinnamon 3.0?

**Comment by Vahan86** [comment]
@JosephMcc, can we close this issue?
