### ISSUE TITLE
Attaching dialog windows can result in permanently dimmed main window

### ISSUE THREAD

**Issue by anandtrex** [linuxmint/Cinnamon#4283]
Issue #3249 seems to have reappeared with the latest Cinnamon 2.6.7 (and muffin 2.6.1) release with the same exact symptoms. I'm running this on an up-to-date version of Archlinux.

**Comment by mtwebster** [comment]
Already fixed post 2.6.7: https://github.com/linuxmint/Cinnamon/commit/794e84f3efe0cb64235cb72fdb0256e3779a3d3f
