### ISSUE TITLE
file cinnamon-file-dialog request python 2

### ISSUE THREAD

**Issue by pantera31752** [linuxmint/Cinnamon#4285]
```
The file has incompatible shebang:
 *   file: ./files/usr/bin/cinnamon-file-dialog
 *   current shebang: #!/usr/bin/env python3
 *   requested impl: python2.7
```

**Comment by dalcde** [comment]
Are you running an ancient distro without python3 or what? What is wrong with python3?

**Comment by pantera31752** [comment]
!!! One of the following packages is required to complete your request:
- gnome-extra/cinnamon-2.6.7::x-portage (Change USE: -python_targets_python3_3 -python_targets_python3_4)

**Comment by dalcde** [comment]
Closing until you can start to explain yourself and tell us why you think there is a problem with *Cinnamon*, **NOT WHATEVER YOU ARE TRYING TO DO IN GENTOO**. Posting random error messages does not help. This is clearly an issue of someone mis-applying patches and expecting old patches to work with a newer version when >13000 lines of code have changed.

So. What are you trying to do?
