### ISSUE TITLE
With padding set to 3px text and icons move when mousing over launcher icons.

### ISSUE THREAD

**Issue by nuttzo34** [linuxmint/Cinnamon#4286]
When editing the cinnamon.css file and changing the panel launcher padding to something like 3px(which looks much better than the squashed 1px default) some of the icons and text shift slightly downwards when hovering over launcher icons.

The menu,desktop show icon and the text/icons inside the window bars are affected.

This is using an nvidia gt 610 and happens with both proprietary and nouveau drivers.

I have attempted to make a quick video with my phone where it's hard to see.

https://vid.me/6dLt

Steps to reproduce.

1.Edit  usr/share/themes/Linux\ Mint/cinnamon/cinnamon.css

Find value 
  .panel-launcher {
    margin: 1px;
    padding: 3px;(changed from 1px to 3px which adds more space between launcher icons in panel)

2.Right click panel/themes/change desktop to something else and then back to Linux Mint

3.Mouse over an icon in the panel launcher and witness text and icons moving.

**Comment by JosephMcc** [comment]
I'm not so sure this is a bug. When you change the padding to 3px you are adding that padding to all 4 sides of the panel launcher icon. Then on hover an additional 1px is added to the bottom for a border. That seems to push the entire size wanted by the panel launcher to more than the size of the panel. In css that sort of things usually results in things getting pushed around and moved it unexpected ways. You can test by making the panel slightly larger, which solves the issue.

The proper way to add the padding between the launchers is to leave the padding value at one and add a padding-left and padding-right value of 3. That will produce the effect your after without causing the problems you're getting.

**Comment by nuttzo34** [comment]
Thanks josephmcc,adding the padding-left and padding-right values solves the issue,thanks.
