### ISSUE TITLE
Improvements to "Move to another workspace" panel menu

### ISSUE THREAD

**Issue by tp0** [linuxmint/Cinnamon#4288]
1. Show the current workspace (in a greyed out unselectable way). If you for example have 4 workspaces and you're currently on workspace 2, the list looks like:

   > WORKSPACE 1
   > WORKSPACE 3
   > WORKSPACE 4

   * At least I have to constantly actually register the workspace number instead of just relying on intuition and active selection / cursor position. For example lets say I want to pick workspace 3 and I am currently on workspace 2: my eyes expect workspace 3 to be the 3rd choice in the list, but since the current workspace is omitted, it is the 2nd choice.

2. Make the list of workspaces open automatically (mouse hover / on top) or make it a sub-menu to reduce the amount of required clicks to two (from three).

Both of these would make it more similar in behaviour to the system window context menu:

![untitled](https://cloud.githubusercontent.com/assets/5863551/8036883/2c428370-0e03-11e5-9337-699b7d55b249.png)

**Comment by Vahan86** [comment]
+1 for proposed improvements.

**Comment by mainmachine** [comment]
On 3.0.7 it looks like this is the way it works - not sure when but it looks like this got implemented already. :)

**Comment by JosephMcc** [comment]
The original OP is talking about how it appears in the panel window list right click menu. That hasn't changed.

**Comment by mainmachine** [comment]
Ah, of course you're right. Sorry about that, should probably go to bed. :/
