### ISSUE TITLE
Missing Systray Icons on Cinnammon 2.6

### ISSUE THREAD

**Issue by cmaltais-quatral** [linuxmint/Cinnamon#4290]
Linux Mint 17.1 
Cinnamon 2.6.7+rafaela

Dropbox and owncloud is running but there is no icons in the systray. I can see the update manager icon just fine. 
This was working on 2.4

**Comment by dalcde** [comment]
Try killing dropbox and starting it again

**Comment by cmaltais-quatral** [comment]
That worked.

Thanks
