### ISSUE TITLE
Maximize issue on Cinnamon 2.6.7

### ISSUE THREAD

**Issue by onyxnz** [linuxmint/Cinnamon#4292]
Similar to the Java swing issue that has been closed, I am having issues with maximized windows.
Cinnamon 2.6.7 on LM 17.1 x64, Cinnamon version nightly because I saw it was a required diagnostic step. Single Panel at top.

Steps to reproduce: 
Maximize an app. I have tested with Firefox, Chrome, and Netbeans.
Go to next workspace ( CTRL+ALT+ -> ).
Run an app that is capable of full screen usage, eg VLC with F key, or Chrome with F11, and set to full screen.
Go to previous workspace ( CTRL+ALT+ <- )
![screenshot from 2015-06-09 14 51 21](https://cloud.githubusercontent.com/assets/139939/8049767/a308b2d6-0eb7-11e5-80b3-ee0e32556517.png)

Issue is immediately noticeable, as the maximized apps have now got hidden titlebars, and there is a panel-sized gap at the bottom of the screen (remember, panel is on top!). Mouse interaction is off by about the size of the panel also. The app needs to be Unmaximized in order to get it working.
OR on the second workspace, if the fullscreen app is reverted to normal screen then all is fine again.

**Comment by m00ster** [comment]
I believe this is related to the full screen issues i am having as well whereas you can go full screen on one monitor and not be able to interact with the panels on the other, also full screen mode doesnt work correctly with some apps such as wine apps on the secondary monitor. you will see the panels regardless of the full screen state of the app.

**Comment by ledufff** [comment]
Reproduced with MPV on Fedora 22.

**Comment by JosephMcc** [comment]
I can no longer reproduce this on git master.
