### ISSUE TITLE
Problems with touchpad scrolling in Cinnamon 2.6

### ISSUE THREAD

**Issue by Vahan86** [linuxmint/Cinnamon#4295]
I am have  HP Envy 15t notebook. The notebook's  touchpad has scrolling area on the right side which allows you to scroll using one finger. This function worked nice in Cinnamon 2.4. After installing Cinnamon 2.6 (I am using Linux Mint 17.1) touchpad's scrolling area doesn't work anymore.

**Comment by dalcde** [comment]
Please don't open two issues for the same problem. You could have re-opened the other issue if you accidentally closed it.

Have you tried fiddling with the Touchpad page in cinnamon-settings?

**Comment by Vahan86** [comment]
I checked this option in Touchpad settings. Actually "Edge scrolling" option is disabled by default in Cinnamon 2.6. Instead of this the "two-finger scrolling" is enabled by default. So, the problem is solved. Thanks for helping.
