### ISSUE TITLE
cinnamon-desktop-environment depends on pidgin

### ISSUE THREAD

**Issue by skmlcd** [linuxmint/Cinnamon#4300]
Debian 8.1 Stable (Jessie)

When I wanted to remove ```pidgin``` from my (fresh Cinnamon 2.2 install from Debian netinst) system I got a warning that ```cinnamon-desktop-environment``` depends on ```pidgin```, which should not be this way. This would completely destroy my system.

**Comment by GLolol** [comment]
`cinnamon-desktop-environment` is a Debian meta-package - what it actually does it pull in programs for your OS via dependencies. This is not actually related to Cinnamon, but rather the packaging in Debian. If you want a more lightweight install, try installing `cinnamon-core` and then removing `cinnamon-desktop-environment`.

**Comment by skmlcd** [comment]
You're right, it would be more appropriate to post an issue elsewhere, but still... I thought someone from Mint team packages Cinnamon for Debian, since there is a LMDE. This should not be done this way.

**Comment by GLolol** [comment]
I agree with you. Relevant Debian bug: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=771418
