### ISSUE TITLE
Add livewallpaper option to background section in Cinnamon 2.6

### ISSUE THREAD

**Issue by freemangilgamesh** [linuxmint/Cinnamon#4302]
Besides the slideshow option, I suggest a livewallpaper option to backgrounds section. Here is a stable one http://www.omgubuntu.co.uk/2015/05/animated-wallpaper-adds-live-backgrounds-to-linux-distros

<a href="http://imgur.com/6HTg9Uu"><img src="http://i.imgur.com/6HTg9Uu.jpg" title="source: imgur.com" /></a>

<a href="http://imgur.com/I2VbHCP"><img src="http://i.imgur.com/I2VbHCP.png" title="source: imgur.com" /></a>

**Comment by leigh123linux** [comment]
-1  The drawbacks listed are too much

**Comment by lestcape** [comment]
-1 There are any inconvenience to use this app in cinnamon? I don't see this as a distro default option. This is interesting for a group of user, and is not relate with any productive things, just a complete lost of performance.

**Comment by freemangilgamesh** [comment]
What if you work out something similar with less cpu usage?

**Comment by freemangilgamesh** [comment]
BTW I have been using it on many laptops and I haven't seen any drawbacks, just a better looking and more exciting desktop.

**Comment by lestcape** [comment]
@freemangilgamesh sorry, but anything that you add has CPU requirements, I'm not saying that you are wrong, just i don't see this as a DEFAULT desktop feature, because NOT all users want to have an exciting desktop.

**Comment by Topperfalkon** [comment]
@freemangilgamesh What's wrong with just installing and using the live wallpapers package if you want to use it?

**Comment by freemangilgamesh** [comment]
Nemo desktop icons keep disappearing when I run it on Cinnamon

**Comment by leigh123linux** [comment]
@freemangilgamesh  I'm glad your icons disappear :+1: 

Try reading you own link!!  

http://www.omgubuntu.co.uk/2015/05/animated-wallpaper-adds-live-backgrounds-to-linux-distros

```
Drawbacks
No Desktop Icons
```

So why would you expect icons!!

**Comment by valgusk** [comment]
I dont see why not allow this option directly in cinnamon. Certainly need an alternative that allows to keep icons. Been searching for this feature for years

**Comment by JosephMcc** [comment]
https://github.com/linuxmint/Cinnamon/issues/2075

**Comment by freemangilgamesh** [comment]
These guys hate us they want us o use a dull desktop. Why don't youmake cinnamon a simple readme file and we make our own desktops!!

**Comment by JosephMcc** [comment]
Go ahead. Feel free to make your own DE. Beauty of open source.
