### ISSUE TITLE
Other screensavers disappeared in 2.6.7

### ISSUE THREAD

**Issue by madopal** [linuxmint/Cinnamon#4304]
In 2.6.6, xscreensavers (or others on the system) were visible and able to be used. With the release of 2.6.7, the only option on the screensaver configuration is back to only being "Screen Locker."  Intentional?

**Comment by mtwebster** [comment]
Check and make sure xscreensaver didn't somehow get removed when you updated?  Nothing should have changed

**Comment by madopal** [comment]
Nope, everything that was there before is still there. The only thing that seems to have changed is the name in the settings. It was showing as "Screen Locker", but now it shows "Screensaver". Could it be a version issue with cinnamon vs. cinnamon desktop in the Fedora repos? Sorry if I'm reporting this in the wrong place if so. I've seen this on 3 different machines, btw. Any logs I should look at to see what it's looking for to populate the screensaver list?

Version outputs:

$ rpm -qa | grep xscreensaver
xscreensaver-gl-extras-5.32-12.fc22.x86_64
xscreensaver-extras-5.32-12.fc22.x86_64
xscreensaver-5.32-12.fc22.x86_64
xscreensaver-gl-base-5.32-12.fc22.x86_64
xscreensaver-base-5.32-12.fc22.x86_64
xscreensaver-extras-base-5.32-12.fc22.x86_64
xscreensaver-gl-extras-gss-5.32-12.fc22.x86_64
xscreensaver-extras-gss-5.32-12.fc22.x86_64

$ rpm -qa | grep cinnamon
cinnamon-desktop-2.6.4-2.fc22.x86_64
cinnamon-translations-2.6.2-1.fc22.noarch
cinnamon-menus-2.6.0-1.fc22.x86_64
cinnamon-control-center-filesystem-2.6.0-3.fc22.x86_64
cinnamon-control-center-2.6.0-3.fc22.x86_64
cinnamon-screensaver-2.6.3-2.fc22.x86_64
cinnamon-session-2.6.1-1.fc22.x86_64
cinnamon-2.6.7-2.fc22.x86_64
cinnamon-settings-daemon-2.6.1-1.fc22.x86_64

**Comment by mtwebster** [comment]
I think maybe @leigh123linux disabled it in Fedora - see http://pkgs.fedoraproject.org/cgit/cinnamon-screensaver.git/commit/?id=c2b6e2d8fbe21c432014b4fad27aeff9378e4722 because of stability issues.

Not sure what a subpackage is, but maybe you do.

**Comment by madopal** [comment]
Thanks for checking that. I'll try and cruise the other issues before bugging you all about it.

**Comment by leigh123linux** [comment]
@madopal 

Be aware that I'm not supporting xscreensaver issues at bugzilla. 

```
dnf install cinnamon-screensaver-unsupported
```

**Comment by leigh123linux** [comment]
@mtwebster 

This will explain what a subpackage is

http://docs.fedoraproject.org/en-US/Fedora_Draft_Documentation/0.1/html/RPM_Guide/ch10s04.html
