### ISSUE TITLE
[Sound applet][UX] Open player and close player buttons are too close to each other

### ISSUE THREAD

**Issue by gauravjuvekar** [linuxmint/Cinnamon#4305]
and also too small.
I doubt there's even a 1px gap between them.
Instead, is it possible to use the player name to open the player and a single (larger) close player button?

**Comment by JosephMcc** [comment]
Yeah, I agree with you. I preferred the way that it was before with the those two buttons inline with the other player control buttons.

**Comment by marmistrz** [comment]
Well, tbh, I'd prefer the current way if the buttons were a little larger and not so close to each other

**Comment by pixunil** [comment]
![sound-applet-raise-quit-buttons](https://cloud.githubusercontent.com/assets/7093655/8698701/88964070-2b00-11e5-94f6-4ecafe16877b.png)
[A quick fix](https://github.com/pixunil/Cinnamon/commit/482d4935a88dcad0769ca8da886cce5d453eb2f6) would be to use the style class `.sound-button-container`.
It makes things bigger, but it is fully compatible with old themes and should solve the issue.

The other possibility would be to use another class… Opinions?

I like to have the buttons right to the player name, as:

- there are now (optional) loop and shuffle controls, with quit and raise there would be eight buttons, making the whole thing too wide
- in the upper section the player can be changed (when there are multiple), so it would make sense to kill it or show it

**Comment by gauravjuvekar** [comment]
@pixunil +1

**Comment by JosephMcc** [comment]
I think I would go for using a style class of it's own. Backward compatibility isn't a big issue since an element can be marked as important so it gets default theming if there is none.

**Comment by marmistrz** [comment]
@pixunil: please make a pull request, the patch is great, I applied it myself

**Comment by pixunil** [comment]
Sorry for the delay, here is the slightly refined version. I used now the pseudo class `:small`, so theme designers can use `.sound-button:small` (`width` and `height`) and `.sound-button:small StIcon` (`icon-size`) to resize the buttons. (I didn't want to screw with `important`) 
![sound-applet-raise-quit-buttons 2](https://cloud.githubusercontent.com/assets/7093655/9114638/30035d00-3c5b-11e5-9a1a-904363b686e9.png)

**Comment by marmistrz** [comment]
Well, although the distance between the buttons is ok in 17.3, I'd really prefer the styling as in the pixunil's fork
