### ISSUE TITLE
menu applet keyboard shortcuts silently override control-center shortcuts

### ISSUE THREAD

**Issue by calestyo** [linuxmint/Cinnamon#4309]
Hey.

Cinnamon 2.6.7, Debian sid.

I was just nearly about to reopen #2344 until I've noticed that assigning the Super key to e.g. opening the terminal actually works, but only when one removes the very same key binding before in the applet specific config of the menu applet.

It would be nice if there was some kind of warning that a shortcut is already used by the menu applet in a global fashion... or that setting should went to the control center as well.

Cheers,
Chris.

**Comment by dalcde** [comment]
Not sure if this is plausible, as applets can add arbitrary bindings as they wish. Even if we do this for the stock menu applet, users can still use third-party menus and the problem would still persist.

**Comment by calestyo** [comment]
Well so you could argue then for those shortcuts managed by the CC itself as well.
Why giving there a warning, if it can anyway happen that any 3rd party program catches it as well.

Obviously the above isn't the very most critical bug ;-) ... but I think it would be nice if at least everything officially provided by Cinnamon would give such warnings.

Perhaps one could even provide an API for 3rd party apps, which they could use for the same checks/popup windows, when they register shortcuts.

**Comment by lestcape** [comment]
Actually, cinnamon provide a complicated mechanism to handle keybindings. I consider then important and necessary have a thing like that, also if this will break any current third-party applet. If i need to go to all applets development website to propose a patch, i will do it.

Anyway, I think actually we can do this to all third-party extension without affect any. As i see, currently there are not any keybinding without a way to configure it inside the setting of the extension. If there are someone, that are not in this situation will be only one or two. So, this is not a big deal.

Proposition:
1- When user provide some different keybinding, emit a signal to be used in the future to know the change, but, also update the settings-shema.json copy in ~/.cinnamon/configs/uuid/uuid.json that have this keybinding to the new value.
2- Provide an special cinnamon-settings session inside the keyboard module to show all registry keybindings, not just the custom keybindings (custom-list), using the keybinding name, of all calls to addHotKey.

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html
