### ISSUE TITLE
when setting an already used keyboard shortcurt, ESC doubles its usage

### ISSUE THREAD

**Issue by calestyo** [linuxmint/cinnamon#4310]
Hey.

When setting a keyboard shortcut for, say "switch to workspace 6" in the control centre and using a shortcut that's already used (e.g. Alt+F7 which is IIRC used for "move window" per default), then a pop up comes up that askes no/yes whether to move the shortcut.

But when escape is pressed the popup goes away and both, old and new action have the same shortcut... but it works only for one of them.

Cheers,
Chris.

**Comment by calestyo** [comment]
Cinnamon 2.6.7, Debian sid.

**Comment by ManIVIctorious** [comment]
Still valid for cinnamon 3.0

**Comment by Vahan86** [comment]
@calestyo, is this still an issue in Cinnamon 3.6?

**Comment by calestyo** [comment]
Just tried it with 3.6.7, which has finally arrived in Debian,... and the issue still persists.

**Comment by calestyo** [comment]
Just tried it in 3.6.7 which has finally arrived in Debian and the issue still persists.
