### ISSUE TITLE
smart placement of newly opened windows

### ISSUE THREAD

**Issue by calestyo** [linuxmint/Cinnamon#4313]
Hi.

Since cinnamon 2.6, new windows (which don't position themselves) seem to be opened in the centre of the screen.

I'm tempted to say, that there's only one situation where this is a not-completely-wrong choice:
A fully empty workspace.
And even there, other choices seem to be better, e.g.:
- close to the mouse pointer, so that one doesn't have to move it long ways to reach that window
- somewhere rather close to a corner (typically the upper left), so that any further opened windows can use up the (work)space efficiently

Imagine a situation where one needs to open say 4 Terminals:
I press my keyboard shortcut for Terminal 4 times, and 4x gnome-terminal windows pop up, all at the very same location with the same size,... only one is immediately visible and usable.
Not so optimal.

Let me propose a better way:
Basically it's what ye good old compiz window manager did.
1) windows that set their own position were of course not affected by the following

2) neither were, child windows or popup windows related to other existing windows (those were still opened somewhere within/above the "parent" window

3) but for the other cases, compiz tried to use up space efficiently, e.g. like the following:
- if the workspace was still empty, then the first window was opened somewhere close to the top left corner... not exactly at the corner because this may cause undesired docking or thing like that.
- any further window (assuming the first one wasn't moved/resized) would have been placed depending on the size of the new window, and where space is available.. this could e.g. be right of the first terminal (the next one would be opened in the bottom left corner, and the next bottom right)
  again here, the window wouldn't be placed directly at the other window's border, because this could cause docking
- if the next window was however too big for that matrix like placement... it could also place it diagonally i.e. the 2nd one already justified to the bottom right corner.
- and if there wasn't enough space even then, windows would also overlap, but in such a way, that one still sees as much as possible from each window
- compiz was even so smart to handle "multiple layers" of windows eating up the workspace:
  Imagine a workspace where you open a browser window maximised, or at least eating up most of the workspace.
  If one now opens a much smaller terminal window... there would of course be no space for it on the blank workspace background... thus the browser window is basically considered a lower layer and ignored... that means, our new small terminal window would get placed according to the same rules as above.
  And when I open another terminal windows,... the same.

One question is a bit problematic here though:
Imagine again: maximised browser window, then small terminal window... now I focus to the browser window (i.e. the terminal goes to the back and is no longer visible).
What should happen now, when I open another terminal windows?
Should the WM try to take the lower windows "layers" (i.e. our single small terminal in the back) into account or not? And if yes, to which extent should it try to be smart (as this could also lead to undesired effects).

Cheers,
Chris.

**Comment by JosephMcc** [comment]
You do realize that the center placement is just the default setting? You have a couple of other choices in System Settings->Windows on the Behavior tab. The "Location of newly opened windows" setting.

**Comment by calestyo** [comment]
@JosephMcc sure, but none of the other methods seems to be really much more advanced, Automatic is definitely not as useful as what I describe above...

Which is why I can't quite undesrtand why @dalcde has closed this ticket without any further discussion?

**Comment by dalcde** [comment]
You started the comment with "Since Cinnamon 2.6", so I assumed you were looking for the old behaviour, which is what you can get by choosing "Automatic", which is why I closed the issue.

"Automatic" is also sort-of what you described in your suggestion. As you have noticed yourself (in the last paragraph), window placement is a complicated issue that is impossible to do right because we don't have psychic abilities to know exactly what the user wants to do. So unless you have a concrete suggestion of how we can improve the window placement logic and explain why it is superior, I don't see much point in keeping this open.

**Comment by calestyo** [comment]
Well as I just wrote above, automatic seems to be really not what I propose here,...when you have that and open say 4 terminals in a row it will merely shift each of them a few pixels right and down, even if plenty of (work)space would be left,... so effectively it's (IMHO) better than 2.6' new default but still not really efficient.

Well the concrete proposal is what I wrote above which quite found, I'd guess. The only really open questions is, how to decide placement of new windows, when a lower (but not visible) "layer" of windows on the current workspace would still have free space.

And I think it's quite obvious why the above proposal is superior - it tries to maximise (work)space usage.


Perhaps you have somewhere an old installation with compiz left... I'm not sure whether this mode of window placement was the default or whether I manually chose it somehow, but if you could try it out, you'd see that it's basically a whole new experience. Or better said, you spend much less time with re-positioning your windows.
Even while this may sound like a small improvement, it hat an enormous benefit on my whole interaction with the DE.
Acutally, when I had to switch away from compiz because Debian dropped it and I choose GNOME classic first and later cinnamon, this was amongst the features I've most desperately missed.

**Comment by dalcde** [comment]
Regarding the "4 terminals in the row" thing, it only happens when there are windows in the way. If there are no windows open, then they tile nicely near the center. Alternatively, if you have a window tiled to the right (occupying half of the screen), the first two windows will still tile nicely:
![screenshot from 2015-06-14 15-20-19](https://cloud.githubusercontent.com/assets/1336336/8148899/e2df57e4-12a8-11e5-985d-acf521855765.png)
Windows also tend to avoid others if possible.

So the only missing thing is the last "layering" feature you mentioned.

And when I say "concrete", I mean a well-defined deterministic mechanism, without things like "you could", "somewhere near" etc. Alternatively, this means that if you separate two people and ask them to implement it according to your suggestions, they should produce the same behaviour

**Comment by calestyo** [comment]
Ah... seems you're right... when the workspace is empty and I open e.g. the 4 terminals in a row... they are positioned in a matrix like style.
Is that new since 2.2 or did it that already before an I just cannot remember it correclty?

So as you said, the "layering" thing is missing.

But perhaps in addition:
- when it place the windows on an empty workspace, the first one has (at least on my screen) already considerable space to the left border (like ~150 pixles or so)... I think that could be much less, e.g. the same as it has to the top border, where there are only like 10 pixels (i.e. "wasting less space").

-  Further, and I think one can see that in you screenshot as well... even though there is still plenty space left, it places the windows so that they touch each other exactly towards their centre broders.
I think it would be better if there were some 5-10 pixels in between.
This is not only to avoid snapping/docking, but it also simply looks somehow ugly... (due to the shadow of windows) and because it gives somehow the feeling as if those windows would belong to each other (because of their exact connection).
Actually, if not enough space is left to leave 5-10 pixles between window, but if there was enough space so that they fit exactly (i.e. the broders touch exactly) I think I'd even prefer if the windows are placed overlapping then.
Maybe it's just me, but if windows really exactly touch others at their broders, then this feels somehow special or even strange.

- last but not least, it may be a nice feature to allow people to configure the order in which windows are placed
Right now, when e.g. opening the 4 terminals in a row, you'd get about that:
1 3
2 4
but for some people it may e.g. be better to have:
1 2
3 4
or even
1 3
4 2
or maybe even
2 4
3 1

This may seem like nitpicking, but it has IMHO some great influence on efficiency, largely depending on how one personally works with windows, e.g. whether one typically scales them horizontally or vertically... or whether one rather wants to read from left to right or right to left... or perhaps whether one has applets/desklets in a specific region of the screen and thus wants the windows to open close there.

Window placement order is probably nothing that e.g. GNOME3 would let you configure, but I think it's one of the core functionalities of DEs and their window managers and while their should be decent defaults, "power users" should have strong means to configure (nearly) every aspect to their wishes.


Best,
Chris.

**Comment by dalcde** [comment]
On Sun, Jun 14, 2015 at 09:13:38AM -0700, Christoph Anton Mitterer wrote:
>But perhaps in addition:
>- when it place the windows on an empty workspace, the first one has (at least on my screen) already considerable space to the left border (like ~150 pixles or so)... I think that could be much less, e.g. the same as it has to the top border, where there are only like 10 pixels (i.e. "wasting less space").

Personally I prefer the current mechanism because things look more
symmetric. Told you window positioning is complicated

>I think it would be better if there were some 5-10 pixels in between.
>This is not only to avoid snapping/docking, but it also simply looks somehow ugly... (due to the shadow of windows) and because it gives somehow the feeling as if those windows would belong to each other (because of their exact connection).
What do you mean by snapping/docking?

>Window placement order is probably nothing that e.g. GNOME3 would let you configure, but I think it's one of the core functionalities of DEs and their window managers and while their should be decent defaults, "power users" should have strong means to configure (nearly) every aspect to their wishes.

Which is why in the good old days, the window manager is separated from
the DE and people can opt to use tiling window managers/more powerful
stuff.

**Comment by calestyo** [comment]
Yeah,... it would probably bethe best to make even that configurable.
You like the more symmetric way... I perceive it a bit unnatural (what's what I meant with strange before)... and another one may have some totally different opinion ;)

Snapping/docking:
Right now in cinnamon, when e.g. the left border of window B is moved over the left border of window A, then there's a short amount of movement needed to actually cross the border, i.e. where you move the mouse but the window B doesn't move.
Docking/snapping isn't the right term, though, because this also happens when the windows weren't exactly adjusted by there borders before and it doesn't happen when moving the window "away" form the other.

Yeah,... the good old days :-(

**Comment by mikkorantalainen** [comment]
I'd suggest ignoring all maximized windows while computing position for a new window. That would make terminal windows open without overlapping even if I already have a browser window maximized on the same workspace. If you cannot avoid overlapping the maximized window you may as well totally ignore it.

As for the case where I have too many small windows already covering the workspace and a new small window is opened, I would prefer putting the center point of newly opened window on the corner of one or more existing windows. That maximizes the probability that at least half of the newly opened window is still visible after and another window is raised on the same workspace.

If multiple positions for a newly opened window are available given above basic rules, select the one with smallest number of windows overlapping a single pixel on the screen. I think that overlap for the center point of the possible new window location needs to be computed. However, an even better solution would be to compute overlapped area (in pixels) for each window and select the location that has the lowest overall overlap.

I believe the above is pretty near the "Smart" positioning of Compiz.

**Comment by calestyo** [comment]
Just ignoring maximised windows isn't enough, though. One may have windows which are nearly maximised,... and were still no reasonably sized new window fits aside it.

As for your second proposal: Only as an additional option. I, for example, would consider it extremely strange and irritating behaviour if a window is placed so that parts of it are outstide the visible desktop. There you have the guarantee that you don't see viable content (and that you'll definitely have to move the window)... while with the "multiple layers" approach I described above, you only hide parts of other windows (which is kinda inherent to the windowing idea).

Also I don't think that compiz ever placed parts of a window outside the visible desktop, did it?

**Comment by mikkorantalainen** [comment]
Windows should be always placed to be fully on the screen (with the exception that it's okay to put window border outside the screen but that only saves around 3-7 pixels). Every single pixel of the window content area should always be visible after a window has been opened.

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html
