### ISSUE TITLE
cannot set the single <Menu> key as a shortcut via the control center

### ISSUE THREAD

**Issue by calestyo** [linuxmint/Cinnamon#4314]
Hi.

While #2344 is actually fixed and one can set the single Menu key as shortcut from dconf-editor, this doesn't seem to work from the control centre.
It then always opens the context menu of the text box where one would "enter" the keyboard shortcut.

Cheers,
Chris.

**Comment by calestyo** [comment]
That seems to work in at least 3.0.2.
If someone would confirm it, this issue could be closed.

**Comment by f2404** [comment]
Works for me - Arch Linux, Cinnamon 3.0.2.
