### ISSUE TITLE
Attached dialogues: window greyed out

### ISSUE THREAD

**Issue by floriandejonckheere** [linuxmint/Cinnamon#4315]
This bug is only visible if `/org/cinnamon/muffin/attach-modal-dialogs` is set to `true`.
After updating to Cinnamon 2.6.7 from 2.4.1 in the Arch Linux repositories yesterday, all dialog windows behave as following:

- Dialog is attached to parent window's titlebar, underlying window is not greyed out (as it should be)
- On closing dialog (dismissing or confirming) the window turns grey, but everything still works
- The condition is only fixable by restarting the affected application

Downgrading to Cinnamon 2.4.1 solves the problem.

**Comment by JosephMcc** [comment]
This should be fixed here: https://github.com/linuxmint/Cinnamon/commit/794e84f3efe0cb64235cb72fdb0256e3779a3d3f
