### ISSUE TITLE
Add 3G connection type to Cinnamon network manager applet(UMTS, EDGE....)

### ISSUE THREAD

**Issue by freemangilgamesh** [linuxmint/Cinnamon#4316]
I suggest you add a label on Cinnamon network manager applet indicating 3G connection type like on Mate desktop (UMTS, EDGE....). This is very useful to tell signal strength.

<a href="http://imgur.com/MyUaNdY"><img src="http://i.imgur.com/MyUaNdY.jpg" title="source: imgur.com" /></a>

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html
