### ISSUE TITLE
Immediate crash when using Nvidea drivers other than Nouveau

### ISSUE THREAD

**Issue by Eirikur** [linuxmint/Cinnamon#4317]
Nvidea (ASUS) GeForce 660.  Using either driver-manager or manual install of the vendor-specified driver, anything other than Nouveau results in Cinnamon crashing at startup.  It will run after asking if I want to run with software rendering.  Sorry, this is the only Nvidea card that I have.  I'm a developer, I'd be happy to debug this but I'm not familiar with how to debug Cinnamon.  Point me to instructions if you can.

**Comment by leigh123linux** [comment]
This is more likely to be a nvidia issue as my 660 works great in cinnamon.

```
$ inxi -GS
System:    Host: localhost.localdomain Kernel: 4.0.5-300.fc22.x86_64 x86_64 (64 bit)
           Desktop: Cinnamon 2.6.8  Distro: Fedora release 22 (Twenty Two)
Graphics:  Card: NVIDIA GK106 [GeForce GTX 660]
           Display Server: Fedora X.org 117.1 driver: nvidia
           Resolution: 3840x2160@60.00hz
           GLX Renderer: GeForce GTX 660/PCIe/SSE2
           GLX Version: 4.5.0 NVIDIA 346.72
```

**Comment by ManIVIctorious** [comment]
Have the Same issue with gtx750 on my main PC, if i can provide any informationto track this down just tell me how. 

System arch Linux, cinnamon 2.6.7

**Comment by leigh123linux** [comment]
@ManIVIctorious 

Provide the info requested in my previous post.

**Comment by ManIVIctorious** [comment]
Unfortunately this will take some time, i will Post it when i have access to my pc again, could take a week or two...

**Comment by Eirikur** [comment]
I just took my nvidia card out of my system.  I'll get that data when I open the computer again in a couple of days.

**Comment by ManIVIctorious** [comment]
Forgot about that one... I am currently sitting at my main machine and everything works flawlessly. The problem was definitely a nvidia issue and got resolved in spring (I think, could have been earlier...)

@Eirikur Does the issue still occur on your side?

**Comment by Vahan86** [comment]
@JosephMcc, can we close this issue?
