### ISSUE TITLE
Displays has issues with the UI hanging when working with multiple monitors

### ISSUE THREAD

**Issue by Eirikur** [linuxmint/Cinnamon#4318]
When I first open Displays, I can't select my second monitor at all.  If I check the mirror displays box, and uncheck it without doing an Apply, I can select my second monitor.  I'd like to get an error dialog here if there's a real reason this must happen, but I think it's just a bug.

 I think Displays needs more defensive coding and error reporting.  Displays either doesn't see a monitor on my Nvidea board, or sees it, shows it in black and it is not selectable.

Nvidea GeForce 660 using Nouveau driver from standard 17.1 install
AMD/ATI Radeon  HD 5450 using 17.1 standard install or amd-catalyst-omega-15.5-linux-run-installers

**Comment by Vahan86** [comment]
@Eirikur, is this issue still relevant to Cinnamon 3?

**Comment by Eirikur** [comment]
No, and it can be closed.
    
    
    
    On 11/30/2016 09:20 AM, Vahan
      Harutyunyan wrote:
    
    
      @Eirikur, is this issue still
        relevant to Cinnamon 3?
      —
        You are receiving this because you were mentioned.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/linuxmint/Cinnamon","title":"linuxmint/Cinnamon","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/linuxmint/Cinnamon"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Vahan86 in #4318: @Eirikur, is this issue still relevant to Cinnamon 3?"}],"action":{"name":"View Issue","url":"https://github.com/linuxmint/Cinnamon/issues/4318#issuecomment-263884735"}}}

**Comment by Vahan86** [comment]
@Eirikur, thanks for reply. In this case can you please close this issue?
