### ISSUE TITLE
flgrx driver offered by driver-manager cannot be installed because of package system state

### ISSUE THREAD

**Issue by Eirikur** [linuxmint/Cinnamon#4319]
driver-manager offers flgrx for my AMD/ATI Radeon HD5450.  It fails to install via driver-manager or synaptic due to held packages.  This reproduces on a fresh 17.1 install.

driver-manager probably should not offer drivers that cannot be installed.  Downloading the driver from AMD and installing it manually works fine.

**Comment by dalcde** [comment]
This is not a Cinnamon issue
