### ISSUE TITLE
An easy meta-package and a more flexible one.

### ISSUE THREAD

**Issue by lestcape** [linuxmint/Cinnamon#4320]
I will recommend provide a meta-package to ensure install all dependencies that  is required in cinnamon (on applets, desklets, extensions ) and another with less restrictions for advance users, containing only the real dependency for cinnamon and not the applets, desklets dependencies... In this way, the advanced users can easy change his favorite audio provider for example: http://forums.linuxmint.com/viewtopic.php?f=58&t=197204

This change will not create a problem for the not advanced users, as they can install cinnamon from the most restrictive packages that contain all dependencies.

**Comment by GLolol** [comment]
Meta-packages are usually made by different distros' packagers, not Cinnamon itself. I'm pretty sure that Cinnamon is hardcoded to use PulseAudio right now, as mentioned in the forum post, so a meta-package wouldn't really help in this case.

If you create packages for desklets, they can declare dependencies themselves. Therefore, I don't feel a meta-package is necessary at all.

**Comment by lestcape** [comment]
@GLolol If there are a hard dependency in the code to any audio implementation, sure there are a way to remove it. I'm pretty sure that if in other DE can do this, there are a way to do it. I'm also pretty sure that there several unneeded dependency for start cinnamon, that are only there because are needed for an specific extension, that user can decide disable it.

I'm not saying that what is need is a create more dependency in a meta package(this is what the distros are doing as you say). What i say is provide a package with less dependencies (cinnamon-minimal), this is not what the distros do.

**Comment by leigh123linux** [comment]
To be honest I don't give a stuff about what power users want as they could do it themselves .
I cater for the standard user who wants anything to work without additional effort, that way I receive less bugreports.

**Comment by GLolol** [comment]
@lestcape So you want to separate Cinnamon's stock applets into their own packages?

**Comment by lestcape** [comment]
@leigh123linux, I'm agree with you, is true that this will increase the bug report. But i disagree with you, because i care what users want, especially the advance users, because they can help more than a not advanced one. If this will satisfy the requirements, i consider this a good thing. Also will help the distro packager, to decide how cinnamon will be provided in a more detailed way. So, will increase you power to adapt cinnamon to your distro better. If the fedora devs decide remove some thing or use it a different way, what do you want to do then modify the cinnamon package?... The Indicators could be an example?

@GLolol not this is not what i proposed, and this will not help, because then cinnamon package, will contain a dependency to the stock applets, and this is the same situation. I propose break this, using an uncomplete cinnamon (a minimal one) with not all dependencies, that as @leigh123linux is saying, will be the cause of more bugreports, because then cinnamon can be installed with non functional features.

**Comment by leigh123linux** [comment]
I disagree, even the dumbest fedora users can provide better info than most advanced users from other distros due to ABRT.

https://github.com/abrt/abrt/wiki/abrt-auto-reporting-tool

To be honest again, advanced users are a pain in the butt, they try shit like this

https://bugzilla.redhat.com/show_bug.cgi?id=1097542

Then they expect you to fix it, that's why fedora has no muffin binary!

Some XFCE users have made similar requests to the Fedora MATE maintainer ( @raveit65 )  to reduce the deps so they can cherry pick stuff to use.

**Comment by lestcape** [comment]
@leigh123linux Sorry, my intention is not create problems, is make the thing more easy for you. I really don't understand, why you pay attention to this bugcrap? If this is a legitimate bug, then please remove cinnamon from fedora, because in ubuntu 10.04 is causing some troubles. Anyway, i will close this then. It's more important what think the people that are working that the others that only know how ask for things. I really do not understand, but I can read and absurd things like this can happen, best avoided.
