### ISSUE TITLE
Getting more English(US) keyboard layouts every time I switch back from MATE to Cinnamon

### ISSUE THREAD

**Issue by mxa** [linuxmint/Cinnamon#4321]
There is some weirdness when I switch back from MATE to Cinnamon, I get a new English(US) Keyboard, so pressing my keyboard switching shortcut the list gets longer and longer...
![screenshot from 2015-06-15 13 07 37](https://cloud.githubusercontent.com/assets/1220707/8153004/838d8938-1360-11e5-9265-721528639a0a.png)

**Comment by Vahan86** [comment]
@mxa, is this still an issue for you in Cinnamon 3.0?

**Comment by mxa** [comment]
I no longer use MATE. Do you want me to install and test?

**Comment by ManIVIctorious** [comment]
Just for confirmation this would be really helpful

**Comment by Vahan86** [comment]
@mxa, would be great, thanks for help.

**Comment by mxa** [comment]
I've tried, and it seems that this issue is fixed. I am almost certain, but I don't have the on-screen display any more on Ctl+Space, as this hotkey is now defined within fcitx, not cinnamon any more.

**Comment by Vahan86** [comment]
@mxa thanks for reply. In this case can you please close this issue?
