### ISSUE TITLE
Make the lock screen look like the login screen

### ISSUE THREAD

**Issue by Vahan86** [linuxmint/Cinnamon#4322]
Just a proposal: it would be good to have the same look (design) for login and lock screens. In my opinion, it will be more polished and elegance in terms of aesthetics and design.

What we have now: 
Lock Screen:
![359821fc-0f69-11e5-9063-f60ae9da7bf4](https://cloud.githubusercontent.com/assets/12819058/8158627/e968026a-136f-11e5-9bc1-006a0778edfc.jpg)

Login Screen:
![3f80b260-0f69-11e5-9287-2c8736d201b0](https://cloud.githubusercontent.com/assets/12819058/8158629/ef238d0a-136f-11e5-9edd-ac324fcc7fe2.png)

What Ubuntu did: http://www.webupd8.org/2014/03/unity-7-to-get-its-own-lockscreen.html

Thank you in advance.

**Comment by dalcde** [comment]
This is non-trivial because people can customize the login screen

**Comment by getgnu** [comment]
What does it mean, "login screen"? Very interesting!

**Comment by getgnu** [comment]
What does it mean, "login screen"? Very interesting! This is mine: http://postimg.org/image/5oii0f14v/

**Comment by Vahan86** [comment]
Having an opportunity for customizing the login screen is good for sure, but anyway, it would be more professional and polished if by default (after fresh install of OS) we have the same design for both login and lock screens.

Thanks.

**Comment by Migunderscore** [comment]
Vahan, I agree. I want to harmonise my lock and login screens. It's cleaner.
What if lock would get the same (or a similar) customizing possibility as login and you can choose whether or not to pick the same theme? .. would be nice.

**Comment by leigh123linux** [comment]
The next lock screen will probably look like

![screenshot from 2016-08-12 14-28-03](https://cloud.githubusercontent.com/assets/1299302/17623704/35bf633e-6099-11e6-92cd-14ed0d0b94fa.png)

https://github.com/linuxmint/cinnamon-screensaver/pull/129

**Comment by JosephMcc** [comment]
These are two very different things. The lock screen is a part of Cinnamon while the login/display manager (MDM) is not. It is shared between all Mint flavors (besides KDE). It has it's own settings and theming capabilities that are completely separate from anything to do with Cinnamon. You have the option to use other display managers with Cinnamon such as LightDM or GDM.

**Comment by dzift** [comment]
But that's a poor argument. I think what he was saying is shouldn't there be a login screen theme included in LM which works well with Cinnamon's defaults? After all it is the most popular distro/DE package.
