### ISSUE TITLE
Cinnamon menu should prioritize entries with matching 'Name' field

### ISSUE THREAD

**Issue by AdamBadawy** [linuxmint/Cinnamon#4327]
The Cinnamon menu appears to list search matches in the order they appear when just browsing the menu. This leads to annoying little quirks like these:
http://imgur.com/a/XpBQx

I propose that matches are prioritized based on which fields match. E.g., first by Name, then by Comment, and so on.

It may also be beneficial to prioritize matches which line up with the beginning of the Name. E.g., putting "LibreOffice" before "Calibre" for the search "Libre".

**Comment by dalcde** [comment]
#4053
