### ISSUE TITLE
Add software's logo in title's bar

### ISSUE THREAD

**Issue by LucienPe** [linuxmint/Cinnamon#4328]
I suggest to add the possibility to add the software's logo in the title bar with theses options:
(in System Settings -> Preferences -> Windows -> Title bar)
- Any
- On left
- On left of the title
- On right
- On right of the title
- ...

See the images for the example.
Hoping that you have understood my suggestion.

![title bar left](https://cloud.githubusercontent.com/assets/10365117/8204257/8ef5712c-14e7-11e5-9cfd-54e54250beaa.png)
![title bar left of title](https://cloud.githubusercontent.com/assets/10365117/8204258/8ef8b422-14e7-11e5-8e48-1ef450386362.png)
![title bar right](https://cloud.githubusercontent.com/assets/10365117/8204260/8efb3b84-14e7-11e5-86d7-396af77209ee.png)
![title bar right of title](https://cloud.githubusercontent.com/assets/10365117/8204259/8ef9b1e2-14e7-11e5-9191-060dd6d49d7f.png)

**Comment by JosephMcc** [comment]
I wouldn't be against doing this but I would be against making it like 5 different settings.

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html
