### ISSUE TITLE
Battery icon changes strangely with percentage?

### ISSUE THREAD

**Issue by lf-** [linuxmint/cinnamon#4329]
The battery icon in the power applet is definitely bugged. At 24%, it was showing a third full. Now at 23%, it's showing full:

![image](https://cloud.githubusercontent.com/assets/6652840/8212051/d9b30a0a-14d6-11e5-84f7-854f7a63b982.png)

Now it's showing something somewhat indicative of percentage:

![image](https://cloud.githubusercontent.com/assets/6652840/8212111/17a1c860-14d7-11e5-98ff-d36e20db4436.png)

Does this correspond with half percentage points? This is highly unintuitive behaviour.

Expected behaviour: battery icon "fullness" should correspond linearly with battery percentage.

**Comment by rpbaptist** [comment]
I experience the same issue since upgrading Cinnamon to 2.6.11 along with Mint 17.2. (Coming from Mint 17.1)

**Comment by sfilipov** [comment]
I experience a similar issue when charging. Every 2-3 percent change while charging, the icon will add or remove the little lightning sign even though the laptop is plugged in and charging all the time. It is confusing whether the laptop is plugged in or not. Clicking the applet will show the true information as shown in the screenshot below.

![power_applet2](https://cloud.githubusercontent.com/assets/2607726/8633477/1c9e54dc-27d3-11e5-9a92-75e8a50611d6.png)

**Comment by pixunil** [comment]
@sfilipov, Yep, that's true - for a little explanation: after each update (cable (un-) plugged, charge change) the icon for the status is extracted and if the icon is the same than before, it sets to the full one. It's also fixed.

**Comment by rpbaptist** [comment]
I locally merged both the pull requests which references this, but found neither of them worked.

Which version was used in Mint 17.1? I will have to rever the power applet back to that one.

**Comment by lf-** [comment]
I don't know. I thought (90% sure) it was fixed when I reverted the applet but I'm not reinstalling a Linux version with Cinnamon on my laptop at this time. (this decision has nothing to do with this bug. I switched to bspwm ;P)

**Comment by rpbaptist** [comment]
I copied the power applet from Cinnamon 2.4.0 and it's working as I expected it to be. I believe the problem has been introduced in 2.4.1 with these two commits:

https://github.com/linuxmint/Cinnamon/commit/bad763dfd3363a31a336fea8cf0a022d97d9c294
https://github.com/linuxmint/Cinnamon/commit/035e2fca3a2570300d7592ec22ec3e2085c4e128

The Power Applet hasn't changed between 2.4.1 and 2.4.8. It has been refactored and updated a lot on 2.6.0 but it was overlooked that the battery indicator was bugged.

**Comment by rpbaptist** [comment]
Here is the easy workaround to get the old applet back:
```cd /usr/share/cinnamon/applets/power@cinnamon.org 
sudo wget https://raw.githubusercontent.com/linuxmint/Cinnamon/2.4.0/files/usr/share/cinnamon/applets/power%40cinnamon.org/applet.js
sudo wget https://raw.githubusercontent.com/linuxmint/Cinnamon/2.4.0/files/usr/share/cinnamon/applets/power%40cinnamon.org/settings-schema.json```

Log out and back in.

The file `metadata.json` was not changed so you don't need to revert that.

**Comment by rpbaptist** [comment]
This doesn't seem to be the solution after all. I am at a loss here and guess this bug is the result of something else in Cinnamon.

**Comment by rpbaptist** [comment]
@clefebvre You seem to be closing these issues without checking the actual fix.

**Comment by JosephMcc** [comment]
@rpbaptist Are you running the latest Cinnamon from git? Issues get closed when a fix is made even if it will be in the next version of Cinnamon. Doesn't mean there isn't still an issue. Just making you aware.

**Comment by Vahan86** [comment]
@JosephMcc , the issue still exists in Cinnamon 3.0.7. In my case it was showing 65%, but the battery indicator was full.

**Comment by JosephMcc** [comment]
I'll reopen this since it seems it still isn't fully fixed.

**Comment by Vahan86** [comment]
![untitled](https://cloud.githubusercontent.com/assets/12819058/18285162/13e2a7e6-747e-11e6-9643-d4ccaeccb9c6.png)

**Comment by Vahan86** [comment]
Still an issue in Cinnamon 3.6.7

**Comment by trancef0rmer** [comment]
still for 4.6.7-1

**Comment by ItzSwirlz** [comment]
@mtwebster fixed this with cinnamon-settings-daemon and the power applet recently-this can be closed.
