### ISSUE TITLE
Option for Alt-Tab switcher to list windows on current monitor only

### ISSUE THREAD

**Issue by jochenberger** [linuxmint/Cinnamon#4330]
In a multi-monitor setup, it should be possible to configure the Alt-Tab switcher to switch between the windows on the "current" monitor only, where the "current" one is the one that contains the focussed window.

**Comment by tp0** [comment]
Great suggestion, something I also often have in mind.

I guess preferable a configuration option under Windows > Alt-Tab settings, but additionally there could be a new opt-in shortcut key.

**Comment by davidzhuo1** [comment]
+1

**Comment by rained23** [comment]
+1

**Comment by rolandomar** [comment]
+1

**Comment by atomi** [comment]
I believe Windows 10 has an option that allows you to use ctrl+alt+tab to view all windows in all monitors and alt+tab for just windows on the current monitor.

**Comment by jonwadsworth** [comment]
+1

**Comment by jonwadsworth** [comment]
Can you elaborate on the thumbs-down comment?

**Comment by tp0** [comment]
Probably: since there is the thumbup/down feature, posting just "+1" is a bit spammy.

**Comment by mstawick** [comment]
Dang. Did any of you guys figure out a usable workaround for this issue?

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html

**Comment by kylescousin** [comment]
Is this implemented? I can't find any option to set this.

**Comment by tp0** [comment]
> Is this implemented? I can't find any option to set this.

No, but the issue was closed because in feature suggestions are no longer handled here.

**Comment by baditaflorin** [comment]
I would find this really useful, as I`m mostly using 2 or 3 monitors and having this limitations forces me for some tasks to use other OS so I can be more productive.

**Comment by delchiaro** [comment]
I solved this issue easily:

Edit file: /usr/share/cinnamon/js/ui/appSwitcher

Go to line 66, after the line
`    windows = windows.filter( Main.isInteresting );`
    

We want to add the following line of code:
`    windows = windows.filter(w => w.get_monitor() === global.screen.get_current_monitor())`



I.E. we have to change getWindowsForBinding function, the result is the following:

`

function getWindowsForBinding(binding) {
    // Construct a list with all windows
    let windows = [];
    let windowActors = global.get_window_actors();
    //let windowActors = getWindowList();

    for (let i in windowActors)
        windows.push(windowActors[i].get_meta_window());

    windows = windows.filter( Main.isInteresting );
    windows = windows.filter(w => w.get_monitor() === global.screen.get_current_monitor()) ##   NEW LINE !!!!!!!!

    switch(binding.get_name()) {
        case 'switch-panels':
            // Switch between windows of all workspaces
            windows = windows.filter( matchSkipTaskbar );
            break;
        case 'switch-group':
            // Switch between windows of the same application
            let focused = global.display.focus_window ? global.display.focus_window : windows[0];
            windows = windows.filter( matchWmClass, focused.get_wm_class() );
            this._showAllWorkspaces = global.settings.get_boolean("alttab-switcher-show-all-workspaces");
            if (!this._showAllWorkspaces) {
                windows = windows.filter( matchWorkspace, global.screen.get_active_workspace() );
            }
            break;
        default:
            // Switch between windows of current workspace
            this._showAllWorkspaces = global.settings.get_boolean("alttab-switcher-show-all-workspaces");
            if (!this._showAllWorkspaces) {
                windows = windows.filter( matchWorkspace, global.screen.get_active_workspace() );
            }
            break;
    }

    // Sort by user time
    windows.sort(sortWindowsByUserTime);

    return windows;
}
`

**Comment by Nowaker** [comment]
Thank you @delchiaro for this. This still works. Cinnamon 4.4.8 on Arch Linux 20200327.

**Comment by baditaflorin** [comment]
Hi @delchiaro, I can confirm this works in Linux Mint 19.3 

The folder location is /usr/share/cinnamon/js/ui/appSwitcher/

The file is actually named:
appSwitcher.js

And don`t forget to restart Cinnamon after doing the change. 

Most simple way is by pressing ALT+F2, type `r` and press Enter

**Comment by delchiaro** [comment]
> Hi @delchiaro, I can confirm this works in Linux Mint 19.3
> 
> The folder location is /usr/share/cinnamon/js/ui/appSwitcher/
> 
> The file is actually named:
> appSwitcher.js

Corrected the path in my comment, thanks

**Comment by perlun** [comment]
> Most simple way is by pressing ALT+F2, type r and press Enter

Another way (which I have to do from time to time) is to do execute `cinnamon --replace &` from a command prompt.

@delchiaro Thanks a lot for your change, greatly appreciated. :+1: Please try to get a PR created with this feature so we can get it into Cinnamon upstream, it's really useful. (I guess it will have to be configurable in some way to get it merged, but the Cinnamon developers can probably assist you with useful suggestions about that part.)

**Comment by Petermhen** [comment]
@delchiaro Can confirm that this works on Linux Mint 20.3. Thanks! With multi monitors being so common I think this is an important feature to add to the alt-tab System settings.

**Comment by gbc921** [comment]
> I solved this issue easily:
> 
> Edit file: /usr/share/cinnamon/js/ui/appSwitcher/appSwitcher.js
> 
> Go to line 66, after the line ` windows = windows.filter( Main.isInteresting );`
> 
> We want to add the following line of code: ` windows = windows.filter(w => w.get_monitor() === global.screen.get_current_monitor())`
> 
> I.E. we have to change getWindowsForBinding function, the result is the following:
> 
> ```
> 
> function getWindowsForBinding(binding) {
>     // Construct a list with all windows
>     let windows = [];
>     let windowActors = global.get_window_actors();
>     //let windowActors = getWindowList();
> 
>     for (let i in windowActors)
>         windows.push(windowActors[i].get_meta_window());
> 
>     windows = windows.filter( Main.isInteresting );
>     windows = windows.filter(w => w.get_monitor() === global.screen.get_current_monitor()) ##   NEW LINE !!!!!!!!
> 
>     switch(binding.get_name()) {
>         case 'switch-panels':
>             // Switch between windows of all workspaces
>             windows = windows.filter( matchSkipTaskbar );
>             break;
>         case 'switch-group':
>             // Switch between windows of the same application
>             let focused = global.display.focus_window ? global.display.focus_window : windows[0];
>             windows = windows.filter( matchWmClass, focused.get_wm_class() );
>             this._showAllWorkspaces = global.settings.get_boolean("alttab-switcher-show-all-workspaces");
>             if (!this._showAllWorkspaces) {
>                 windows = windows.filter( matchWorkspace, global.screen.get_active_workspace() );
>             }
>             break;
>         default:
>             // Switch between windows of current workspace
>             this._showAllWorkspaces = global.settings.get_boolean("alttab-switcher-show-all-workspaces");
>             if (!this._showAllWorkspaces) {
>                 windows = windows.filter( matchWorkspace, global.screen.get_active_workspace() );
>             }
>             break;
>     }
> 
>     // Sort by user time
>     windows.sort(sortWindowsByUserTime);
> 
>     return windows;
> }
> ```

Hi! Awesome work! Thanks for this!

However, I think it would be nice to change the comment at the end (`##   NEW LINE !!!!!!!!`) to
`//   NEW LINE !!!!!!!!` so it doesn't brake cinnamon, thinking it is a command, not a comment. :)

**Comment by ZXSwire3** [comment]
> However, I think it would be nice to change the comment at the end (## NEW LINE !!!!!!!!) to
// NEW LINE !!!!!!!! so it doesn't brake cinnamon, thinking it is a command, not a comment. :)

Thanks, I did `##` instead of `//` and completely messed up cinnamon, but was able to fix it because of your comment. :)

**Comment by Maurifc** [comment]
Thx. It worked on Cinnamon 6.0.4

**Comment by dalekirkwood** [comment]
> I solved this issue easily:
> 
> Edit file: /usr/share/cinnamon/js/ui/appSwitcher/appSwitcher.js
> 
> Go to line 66, after the line ` windows = windows.filter( Main.isInteresting );`
> 
> We want to add the following line of code: ` windows = windows.filter(w => w.get_monitor() === global.screen.get_current_monitor())`
> 
> I.E. we have to change getWindowsForBinding function, the result is the following:
> 
> ```
> 
> function getWindowsForBinding(binding) {
>     // Construct a list with all windows
>     let windows = [];
>     let windowActors = global.get_window_actors();
>     //let windowActors = getWindowList();
> 
>     for (let i in windowActors)
>         windows.push(windowActors[i].get_meta_window());
> 
>     windows = windows.filter( Main.isInteresting );
>     windows = windows.filter(w => w.get_monitor() === global.screen.get_current_monitor()) ##   NEW LINE !!!!!!!!
> 
>     switch(binding.get_name()) {
>         case 'switch-panels':
>             // Switch between windows of all workspaces
>             windows = windows.filter( matchSkipTaskbar );
>             break;
>         case 'switch-group':
>             // Switch between windows of the same application
>             let focused = global.display.focus_window ? global.display.focus_window : windows[0];
>             windows = windows.filter( matchWmClass, focused.get_wm_class() );
>             this._showAllWorkspaces = global.settings.get_boolean("alttab-switcher-show-all-workspaces");
>             if (!this._showAllWorkspaces) {
>                 windows = windows.filter( matchWorkspace, global.screen.get_active_workspace() );
>             }
>             break;
>         default:
>             // Switch between windows of current workspace
>             this._showAllWorkspaces = global.settings.get_boolean("alttab-switcher-show-all-workspaces");
>             if (!this._showAllWorkspaces) {
>                 windows = windows.filter( matchWorkspace, global.screen.get_active_workspace() );
>             }
>             break;
>     }
> 
>     // Sort by user time
>     windows.sort(sortWindowsByUserTime);
> 
>     return windows;
> }
> ```

You are a hero! Why on earth this is not included as an option if it really is just so easy. Would anyone consider making this an Applet?

I need to save this somewhere 🙂

**Comment by perlun** [comment]
> I need to save this somewhere 🙂

I have it noted down [in my personal dotfiles repo](https://github.com/perlun/dotfiles/tree/master/cinnamon#appswitcherjs-bug-fix). 😂 But seriously, this should be fixed in Cinnamon proper (or be made configurable or what not).

**Comment by ForsythsGambit** [comment]
> I solved this issue easily:
> 
> Edit file: /usr/share/cinnamon/js/ui/appSwitcher/appSwitcher.js
> 
> Go to line 66, after the line ` windows = windows.filter( Main.isInteresting );`
> 
> We want to add the following line of code: ` windows = windows.filter(w => w.get_monitor() === global.screen.get_current_monitor())`
> 
> I.E. we have to change getWindowsForBinding function, the result is the following:
> 
> ```
> 
> function getWindowsForBinding(binding) {
>     // Construct a list with all windows
>     let windows = [];
>     let windowActors = global.get_window_actors();
>     //let windowActors = getWindowList();
> 
>     for (let i in windowActors)
>         windows.push(windowActors[i].get_meta_window());
> 
>     windows = windows.filter( Main.isInteresting );
>     windows = windows.filter(w => w.get_monitor() === global.screen.get_current_monitor()) ##   NEW LINE !!!!!!!!
> 
>     switch(binding.get_name()) {
>         case 'switch-panels':
>             // Switch between windows of all workspaces
>             windows = windows.filter( matchSkipTaskbar );
>             break;
>         case 'switch-group':
>             // Switch between windows of the same application
>             let focused = global.display.focus_window ? global.display.focus_window : windows[0];
>             windows = windows.filter( matchWmClass, focused.get_wm_class() );
>             this._showAllWorkspaces = global.settings.get_boolean("alttab-switcher-show-all-workspaces");
>             if (!this._showAllWorkspaces) {
>                 windows = windows.filter( matchWorkspace, global.screen.get_active_workspace() );
>             }
>             break;
>         default:
>             // Switch between windows of current workspace
>             this._showAllWorkspaces = global.settings.get_boolean("alttab-switcher-show-all-workspaces");
>             if (!this._showAllWorkspaces) {
>                 windows = windows.filter( matchWorkspace, global.screen.get_active_workspace() );
>             }
>             break;
>     }
> 
>     // Sort by user time
>     windows.sort(sortWindowsByUserTime);
> 
>     return windows;
> }
> ```

Thank you so much, this works flawlessly! This has made my day :D

Out of curiosity do you have a way to switch monitors via keyboard shortcut, for when you'd deliberately want to switch focus?

**Comment by perlun** [comment]
> Out of curiosity do you have a way to switch monitors via keyboard shortcut, for when you'd deliberately want to switch focus?

Good question in fact @ForsythsGambit. :thinking: I think I tend to use mouse-clicking for this (i.e. click on a window which is currently visible on the other monitor).

**Comment by ForsythsGambit** [comment]
@perlun Gotcha, I've been using super + the corresponding number in the panel to do it generally.

**Comment by perlun** [comment]
> I've been using super + the corresponding number in the panel

Hmm... what is that number? :thinking: I wonder if we are using different panel settings, since I don't see any numbers on my running applications.

**Comment by ForsythsGambit** [comment]
@perlun There aren't numbers on the panel itself, however I keep my most frequently used programs pinned to the panel in the same order. This allows me to switch between my most used apps with a specific shortcut for each app. For example Firefox is always the first and Files is always the second.

**Comment by krabhi1** [comment]
> /usr/share/cinnamon/js/ui/appSwitcher/appSwitcher.js

replace ## to //
