### ISSUE TITLE
Feature: Redshift integration

### ISSUE THREAD

**Issue by osos** [linuxmint/Cinnamon#4331]
Please consider to integrate redshift or similar functionality into Cinnamon/MDM.

Available here: http://jonls.dk/redshift/

Redshift adjusts the color temperature of your screen according to your surroundings. This may help your eyes hurt less if you are working in front of the screen at night. This program is inspired by f.lux (please see this post for the reason why I started this project).

It would be ideal to have the Screen color temperature adjustable in the power applet.

This provides for screen brightness and color temperature control also on stationary monitors and not only laptops.

**Comment by hadim** [comment]
+1

**Comment by lf-** [comment]
In the power applet? Why? It's not power related besides controlling brightness. Colour does NOT belong there.

**Comment by osos** [comment]
@lf-, I understand your point. However, the power applet already handles brightness of laptop screens and other illuminated devices such as keyboards. Thus, from a useability view, I think the power applet is the right place.

Maybe the power applet should be renamed, I dont know.

Or where do you think the functionality provided by redshift would fit best?

**Comment by lf-** [comment]
@osos That's the best place to put it I guess.

**Comment by dalcde** [comment]
I don't see a need to integrate it into Cinnamon directly. It would make much more sense to make it a separate third-party applet

**Comment by miloskroulik** [comment]
I agree with dalcde - I see no reason, why Redshift should be directly integrated into CInnamon.

**Comment by Rebel450** [comment]
I do see a reason.
Agree with osos.

**Comment by ManIVIctorious** [comment]
Could you please elaborate which advantage you see in the direct redshift integration?
I personally like redshift and use it a lot, but I think the redshift-gtk tray icon handles every desired functionality

**Comment by Vahan86** [comment]
@JosephMcc, can we close this issue?

**Comment by JosephMcc** [comment]
I'll leave this open for now. It seems a valid feature request though I'm not sure why we would do it if the existing tool works perfectly well. Just means adding something we have to maintain without good reason.

**Comment by lnikon** [comment]
+1

**Comment by JosephMcc** [comment]
Closing this. There is no reason currently for us to do this when Redshift works well and on multiple DE's.
