### ISSUE TITLE
Installing KDE side-by-side breaks Cinnamon

### ISSUE THREAD

**Issue by marmistrz** [linuxmint/Cinnamon#4333]
I installed KDE on a LM 17.1 system running Cinnamon. KDE was running without noticeable problems. Then I rebooted, switched back to Cinnamon. Cinnamon failed to launch with KDE installed, there was a black screen with some graphic weirdness. Even after removing KDE Cinnamon doesn't launch as quickly as expected or sometimes fails to launch at all.

Software which might have impact on the environment: Cinnamon spice "Collapsible system tray"

cf. http://forum.linuxmint.com/viewtopic.php?f=208&t=198273

**Comment by marmistrz** [comment]
Cross reported here: https://bugs.kde.org/enter_bug.cgi?product=kde&format=guided

**Comment by GLolol** [comment]
I believe your bug links are incorrect; they seem to lead to the page where you create bug reports. :)

**Comment by lestcape** [comment]
@GLolol: http://forum.linuxmint.com/viewtopic.php?f=208&t=198273

**Comment by marmistrz** [comment]
Yep, fixed

**Comment by lf-** [comment]
@marmistrz Your link for the KDE bug is still bad.

**Comment by marmistrz** [comment]
@lf- thanks, fixed

**Comment by marmistrz** [comment]
It was alleviated by the 2.6.x update but didn't disappear completely.

**Comment by ManIVIctorious** [comment]
I have kde-plasma and cinnamon installed side by side for more than a year now, no issues on my side, is this still releveant to you?

**Comment by marmistrz** [comment]
What is your distro btw.?

**Comment by ManIVIctorious** [comment]
Sry, Arch Linux with:
`pacman -Qs cinnamon | grep "^\S"`
`local/cinnamon 3.0.7-1`
`local/cinnamon-control-center 3.0.1-1`
`local/cinnamon-desktop 3.0.2-1`
`local/cinnamon-menus 3.0.2-1`
`local/cinnamon-screensaver 3.0.1-1`
`local/cinnamon-session 3.0.1-1`
`local/cinnamon-settings-daemon 3.0.1-1`
`local/cinnamon-translations 3.0.3-1`
`local/cjs 3.0.1-1`
`local/muffin 3.0.5-1`
`local/nemo 3.0.6-1`
`local/nemo-terminal 3.0.0-1`

`pacman -Qs plasma | grep "^\S"`
`local/breeze 5.7.4-1 (plasma)`
`local/breeze-gtk 5.7.4-1 (plasma)`
`local/drkonqi 5.7.4-2 (plasma)`
`local/kactivitymanagerd 5.7.4-1 (plasma)`
`local/kde-cli-tools 5.7.4-1 (plasma)`
`local/kde-gtk-config 5.7.4-1 (plasma)`
`local/kdecoration 5.7.4-1 (plasma)`
`local/kdeplasma-addons 5.7.4-1 (plasma)`
`local/khotkeys 5.7.4-1 (plasma)`
`local/kinfocenter 5.7.4-1 (plasma)`
`local/kmenuedit 5.7.4-1 (plasma)`
`local/kscreen 5.7.4-1 (plasma)`
`local/kscreenlocker 5.7.4-1 (plasma)`
`local/ksshaskpass 5.7.4-1 (plasma)`
`local/ksuperkey 0.4-1`
`local/ksysguard 5.7.4-1 (plasma)`
`local/kuiserver 5.7.4-2 (plasma)`
`local/kwin 5.7.4-1 (plasma)`
`local/libkscreen 5.7.4-1 (plasma)`
`local/libksysguard 5.7.4-1 (plasma)`
`local/milou 5.7.4-1 (plasma)`
`local/plasma-desktop 5.7.4-1 (plasma)`
`local/plasma-framework 5.25.0-1 (kf5)`
`local/plasma-integration 5.7.4-1 (plasma)`
`local/plasma-mediacenter 5.7.3-2`
`local/plasma-nm 5.7.4-1 (plasma)`
`local/plasma-workspace 5.7.4-2 (plasma)`
`local/plasma-workspace-wallpapers 5.7.4-1 (plasma)`
`local/polkit-kde-agent 5.7.4-1 (plasma)`
`local/powerdevil 5.7.4-1 (plasma)`
`local/systemsettings 5.7.4-1 (plasma)`

**Comment by marmistrz** [comment]
So let's close it. That was Plasma 4, Cinnamon 2.x Linux Mint, so long ago. I even changed my distro to Arch in the meantime.
