### ISSUE TITLE
Depends and conflicts should be supported for spices

### ISSUE THREAD

**Issue by marmistrz** [linuxmint/Cinnamon#4334]
Some applets don't work nice with the others. It should be possible to auto disable the conflicting spices (after user's confirmation)

Cf. https://github.com/Koutch/Cinnamon-systray-collapsible/issues/5

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html
