### ISSUE TITLE
nemo window does not gain focus

### ISSUE THREAD

**Issue by atomi** [linuxmint/Cinnamon#4335]
Nemo window doesn't get focus. I've tried opening nemo from the menu and a shortcut, ```super+e```, for nemo under Keyboard Keyboard Shortcuts Launchers Home folder.

Edit: Settings > Windows > Window Focus mode is click and all options are checked.

**Comment by dalcde** [comment]
Can you try recompiling muffin after commenting this line out: https://github.com/linuxmint/muffin/blob/master/src/core/window.c#L2711?

**Comment by ledufff** [comment]
I replied this also with Firefox and Thunderbird.

**Comment by ManIVIctorious** [comment]
Does this still apply to cinnamon 3.0?

**Comment by atomi** [comment]
@ManIVIctorious  I haven't had any problems on Linux Mint 18. Thanks.
