### ISSUE TITLE
Alt-Tab preview won't hide

### ISSUE THREAD

**Issue by chrisolsen** [linuxmint/Cinnamon#4342]
When using alt-tab to switch between apps the app switcher will not close after clicking esc, alt-tab or selecting one of the apps displayed. The only way I can hide the switcher is to manually click on the alt-tab preview box, or if that doesn't work I need to get a window to render on top of it.

Another issue probably related to this one is the multiple alt-tab instances that render over top of each other.

I am running a clean 17.1 install on a Lenovo Thinkpad T430
VGA compatible controller: Intel Corporation 3rd Gen Core processor Graphics Controller (rev 09)

![image](https://cloud.githubusercontent.com/assets/41582/8267449/6acfb02a-171f-11e5-8d7e-7afe4461aa9c.png)

**Comment by dalcde** [comment]
Not reproduced

**Comment by JosephMcc** [comment]
I can't reproduce this either. I don't use alt-tab a lot but I've never seen anything like that.

**Comment by chrisolsen** [comment]
The problem seems to have resolved itself.  I installed some other video drivers and things seemed to work, then out of curiosity I uninstalled them to verify they were the fix, but the problem remained fixed.  So I guess this bug can be closed until it happens again.

**Comment by mp3user** [comment]
I have the same problem after install plank/
