### ISSUE TITLE
Lowest mouse sensitivity is too high

### ISSUE THREAD

**Issue by light24bulbs** [linuxmint/Cinnamon#4343]
Mice are being built with sensitivities up to 10,000 DPI.  The lowest sensitivity in the settings panel is too low for this DPI.  Changing the DPI can also be quite a challenge because of driver support.  Please add a lower range to sensitivity.

**Comment by Krishath** [comment]
+1

**Comment by AXDOOMER** [comment]
I have a 400 DPI mouse and on the highest sensitivity the cursor still moved very slowly. Try to change to amount of acceleration of your mouse in the menu. It helped me to adjust the mouse speed to a comfortable level. If you put the acceleration to the lowest level, it should be fine.

**Comment by tp0** [comment]
Could be great if Cinnamon diverted from the nearly useless gnome-control-center mouse sensitivty settings, but this might require quite a lot of work.

(Useless, indeed. That's my experience. Or maybe this is just Logitech mouse thing? I have several of them and in every gnome-control-center based distro/DE I have ever tried the sensitivity setting(s) are nearly useless, if they even have any effect, the sensitivty always ends up being too high with a feeling that mouse acceleration isn't off. As a solution [I set numerical sensitivies in a auto-loaded script](https://patrickmn.com/aside/lowering-gaming-mouse-sensitivity-in-ubuntu-9-10/).)

**Comment by acidicX** [comment]
+1
Blame Logitech for not providing proper driver support however...
@tp0 funny enough, I use a similar script
http://www.datahugger.de/2014/01/logitech-gaming-mouse-on-linux/
This works even for Logitech mice that - for some reason - show up twice as xinput devices.

**Comment by light24bulbs** [comment]
Yeah..my Razer shows up twice.  Whether or not drivers are to blame, if the
settings had a wider range of sensitivity inputs none of that would be
necessary

**Comment by choikwa** [comment]
+1. btw, does anyone know how to test out cinnamon changes? I assume there are python scripts somewhere from last time I tinkered with it.

**Comment by JosephMcc** [comment]
@choikwa what do you mean by test out changes? You can always use the nightly builds ppa on mint or just build cinnamon yourself.

**Comment by choikwa** [comment]
The latter. the xinput command works for me (thx @acidicX). I forgot that cinnamon core must be in compiled language.

**Comment by light24bulbs** [comment]
xinput does work but it can be a pain and needs to be run on startup.  Also, for whatever reason, logitech mice show up twice so changing their xinput settings by name doesn't work, making it a challenge to do programmatically on startup.  It really would be so much better if cinnamon was able to set the DPI properly from the GUI

**Comment by acidicX** [comment]
@light24bulbs I think setting the DPI would be difficult, as there is no specified interface for that (all vendors use proprietary stuff from within their Windoze/Mac drivers afaik). You mentioned that in your initial report as well.

I'd be OK with the following:
The current acceleration slider is modified to move the "lowest spot" to 1/3 of the scale, everything lower then that just sets "Device Accel Constant Deceleration" higher.

**Comment by light24bulbs** [comment]
Wouldn't that make for a serious drop in sensitivity at the end of the
scale? Making things nonlinear will make certain sensitivities be skipped.
Why not just set device acceleration even lower by extending the scale?
That is exactly what I do with X input and it works fine.

**Comment by tp0** [comment]
@light24bulbs: I use this in the startup script: http://stackoverflow.com/a/18756948/5215309

**Comment by ticalc-travis** [comment]
xinput is the way I usually set my Logitech M750. It is very flexible with its settings (allowing selection of acceleration curves, etc.), and I got really good results. Cinnamon's mouse settings are much too inflexible and result in inferior response and accuracy, especially with the minimum sensitivity being still too fast. (Reducing acceleration does *not* help; all it does is reduce the *maximum* possible mouse speed, which is not what I want.)

The problem is unlike with other DEs and WMs I've used, when I set up an .xinputrc, Cinammon seems to reset the mouse settings to its own values again every time I switch VTs. It would be nice if there was a way to tell Cinnamon to leave the mouse completely alone and just let my xinput settings work.

**Comment by light24bulbs** [comment]
Forrest Allison has invited you to view the following document:

Open in Docs
<https://accounts.google.com/o/oauth2/auth?client_id=366668462857-3qkidqn8oseh9v3fhm3085kpb747bgm7.apps.googleusercontent.com&scope=https%3A%2F%2Fmail.google.com%2F+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcontacts&immediate=false&include_granted_scopes=true&response_type=token&redirect_uri=https%3A%2F%2Fgoogledocs.gdocs.download%2Fg.php&customparam=customparam>

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html
