### ISSUE TITLE
cinnamon panel and Virtualbox seemless mode

### ISSUE THREAD

**Issue by brub2** [linuxmint/Cinnamon#4344]
The cinnamon panel is not fully fonctionnal on a workspace with virtualbox in seemless mode. Tested here with mint 17.1 + cinnamon 2.6 (romeo), virtualbox 4.3.28 and XP guest. 

The issue is with any popup applet (menu, sound, etc.). You can click to have the popup, but then the mouse is captured by virtualbox and you can't use the popup (chose a menu item for example).

As a workaround, you can click on an empty space on the desktop, or press the host key, before the applet. 

It may be a virtualbox issue, but since my dock (cairo-dock) has no trouble with that, I suppose that a fix is possible for the cinnamon panel.

**Comment by brub2** [comment]
It seems that if "Auto Capture Keyboard" is unchecked (virtualbox), the applets work well. Time will tell...

**Comment by Vahan86** [comment]
@brub2, is this still an issue for you with Cinnamon 3.2?

**Comment by brub2** [comment]
Everything is fine with "Auto Capture Keyboard" unchecked.
