### ISSUE TITLE
Panel edit mode should put bounding boxes around applets

### ISSUE THREAD

**Issue by aaroncohen73** [linuxmint/Cinnamon#4345]
When moving applets around in edit mode, it's difficult to move applets that may not necessarily be visible such as spacers and window lists. By adding easily visible bounding boxes around applets when editing a panel, it would be easier to arrange applets. Some themes already do this, but this functionality should be built into Cinnamon so that users aren't reliant on theme creators to implement it.

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html
