### ISSUE TITLE
Add 'shut down laptop when lid is closed' option to Cinnamon

### ISSUE THREAD

**Issue by freemangilgamesh** [linuxmint/Cinnamon#4350]
Unlike mate, Cinnamon lack the option to  'shut down laptop when lid is closed' and it is very useful when someone is in a hurry. I suggest you add it to Cinnamon power setting.

**Comment by corcrash** [comment]
I think this issue should be moved to "linuxmint/cinnamon-settings-daemon". The daemon is the one doing the observation and configuration of the power settings.

**Comment by ManIVIctorious** [comment]
As @corcrash said, this belongs to "linuxmint/cinnamon-settings-daemon".
In the moment I don't have a laptop here to test, is this option still missing in cinnamon 3.0?

**Comment by Vahan86** [comment]
I just checked, shut down option is missing in Cinnamon 3.0. There three options for now: suspend, hibernate and do nothing.

**Comment by Vahan86** [comment]
I just checked, shut down option is missing in Cinnamon 3.0. There are three options for now: suspend, hibernate and do nothing.

**Comment by 55abhilash** [comment]
Hi. I would love to work on this issue. Can you give me a link to the conventional cinnamon compilation / testing process?

**Comment by JosephMcc** [comment]
@55abhilash This is a good place to start: http://segfault.linuxmint.com/2013/10/how-to-build-and-install-the-latest-cinnamon-from-git/

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html
