### ISSUE TITLE
New Files/Folders Saved to Desktop With Unequal Height Monitors Don't Appear on Visible Desktop

### ISSUE THREAD

**Issue by mattlach** [linuxmint/Cinnamon#4352]
All,

In multimonitor desktops where the leftmost monitor has a shorter pixel height than the highest monitor in the group, new files/folders being saved/copied/created default to being created in the empty spot above the leftmost monitor.

See this setup:
https://farm1.staticflickr.com/335/18869825470_c49fdf301c_o.png

And this screen shot:
https://farm4.staticflickr.com/3909/19057531025_f5664eef95_o.png

Current Behavior:
When saving files form a file dialogue, the default location for new files is top left (black region in above screen shot) but this region is not displayed, so files can not be accessed, unless you go into nautilus or another file manager and look at the desktop folder.

Expected behavior:
Good: Areas of Desktop screen not displayed on monitor are excluded from containing any icons.
Best:  Above, plus default new icon location is top left of primary monitor, not top left of total screen area.

Thanks,
Matt

**Comment by dalcde** [comment]
#3276
