### ISSUE TITLE
Poor title in Update Manager for package "cinnamon"

### ISSUE THREAD

**Issue by mikkorantalainen** [linuxmint/Cinnamon#4353]
Ubuntu Update Manager (`/usr/bin/update-manager`) shows package "cinnamon" as "Hot Corners" instead of "Cinnamon desktop". I don't know a proper fix but it seems that the Update Manager tries to localize package names by reading the first (in alphabetical order) `*.desktop` file installed by the package and using it as the name for the package. In case of "cinnamon" package, that file is

    $ dpkg -L cinnamon | fgrep .desktop | head -1
    /usr/share/applications/cinnamon-settings-hotcorner.desktop

I guess a hack fix for this issue would be to add a new desktop file that is first in alphabetical order and has suitable localizations.

![screenshot from 2015-06-23 08 48 25](https://cloud.githubusercontent.com/assets/259482/8299707/f142f10a-1984-11e5-9cf9-200feacc1421.png)

**Comment by dalcde** [comment]
Why don't you file a bug against Ubuntu update manager?

**Comment by leigh123linux** [comment]
@dalcde 

I agree with that :)

It isn't so bad with the latest cinnamon

```
$ rpm -ql cinnamon | fgrep .desktop | head -1
/usr/share/applications/cinnamon-killer-daemon.desktop
```

```
$ cat /usr/share/applications/cinnamon-killer-daemon.desktop |grep Name
Name=Cinnamon Killer Daemon
```
