### ISSUE TITLE
Cinnamon ignores indicators in autostart

### ISSUE THREAD

**Issue by marmistrz** [linuxmint/Cinnamon#4354]
`indicator-keylock` automatically installs an autostart entry in `/etc/xdg/autostart`. Unfortunately, Cinnamon ignores the entry, so the application doesn't launch.

This should be at least configurable.

**Comment by mtwebster** [comment]
See https://github.com/linuxmint/cinnamon-session/issues/58 for an explanation and workaround (for cinnamon 2.6)

With cinnamon-session 2.6.3, you can run:

`gsettings set org.cinnamon.SessionManager whitelist ["'indicator-keylock'"]`

And indicator-keylock should autostart.
