### ISSUE TITLE
really no printer tray icon in cinnamon?

### ISSUE THREAD

**Issue by brub2** [linuxmint/Cinnamon#4356]
I see many posts on printer tray icon issues here (meta bug#481 and bug#2476) and on linux mint forum. 

I'm new on cinnamon panel and I have no tray icon when a printing job is pending (Mint 17.1 + cinnamon 2.6 romeo). So is it "by design" (notifications are ok) or really a bug? It's not clear for me... but I would like to have this icon and I think I'm not alone. 

Any workaround (manually launch the printer control applet or the cups web page is not an acceptable workaround)?

**Comment by dalcde** [comment]
I guess it's a bug and there is already a bug report opened for it?

**Comment by brub2** [comment]
@dalce:
Meta Bug #481 refers to it as "Printing icon appears sometimes" in the "ICON DOESN'T APPEAR AT ALL" section but the original bug #117 is closed and is very old. If Bug #481 is the correct place for this issue, then it should be updated since printing icon *never* appears (at least it's the case here) and other issues have been reported (#2476 still active and this one #4356). 

Also, the metabug reports issues with external applications and we are talking here of the base OS (printing applet). So maybe we should remove from the metabug and have a separate issue? 

Finally, I have read some posts suggesting that the absence of tray icon for the printer is the normal behavior and since all this is very old, that contributed to my confusion. Sorry to have opened this new issue; I didn't know what else to do.

**Comment by dalcde** [comment]
#2476 seems to be the right place for it. If you think this is not a bug but intended behaviour (or if you wish to ask if this is the case), then you should be commenting on that thread, not opening a new thread for it.
