### ISSUE TITLE
cinnamon 2.6.9 keyboard applet cannot use flags to display current layout

### ISSUE THREAD

**Issue by petrucci4prez** [linuxmint/Cinnamon#4357]
Keyboard applet no longer displays a flag for the current keyboard layout (only "en" for english for example) This occurs regardless of the configuration setting. Downgrading to 2.6.8 solves issue

**Comment by EmergReanimator** [comment]
I have made small patch for this which works for me.

$ diff -u  applet.js /usr/share/cinnamon/applets/keyboard\@cinnamon.org/applet.js
--- applet.js	2015-07-11 20:47:40.000000000 +0200
+++ /usr/share/cinnamon/applets/keyboard@cinnamon.org/applet.js	2015-07-11 20:54:05.000000000 +0200
@@ -139,7 +139,7 @@
         for (let i = 0; i < groups.length; i++) {
             let icon_name = this._config.get_group_name(i);
             let actor;
-            if (this._showFlags && this.icon_theme.has_icon(icon_name))
+            if (this._showFlags)
                 actor = new St.Icon({ icon_name: icon_name, icon_type: St.IconType.FULLCOLOR, style_class: 'popup-menu-icon' });
             else
                 actor = new St.Label({ text: short_names[i] });
@@ -171,7 +171,7 @@
         let selectedLabel = this._labelActors[selected];
 
         this.set_applet_tooltip(item._long_name)
-        if (this._showFlags && this.icon_theme.has_icon(item._icon_name)) {
+        if (this._showFlags) {
             this.set_applet_icon_name(item._icon_name);
             this.set_applet_label("");
         } else {

**Comment by leigh123linux** [comment]
This commit breaks it

https://github.com/linuxmint/Cinnamon/commit/e6c3fd9fb247f08e65b316540c2b0e5fd6de65f4

**Comment by perfect7gentleman** [comment]
EmergReanimator, thanx for patch

**Comment by JosephMcc** [comment]
That commit only breaks things under some newer gtk versions. Gtk.IconTheme.has_icon() returns the incorrect value for some reason. Either it's behavior was changed or there is a bug which needs to be fixed in gtk. Works fine under gtk3.10

**Comment by Rolice** [comment]
The patch worked for me as it seems the bug is still present in the current version, thanks @EmergReanimator . I wonder why the release contain such a malfunction (extra logic check within some icon theme)? Does this patch keep the consistency? Why it is not still applied in the master release?

**Comment by JosephMcc** [comment]
It's not merged because it's not really a proper fix. The call to has_icon() is there to cover the situation where you choose a language where no flag is available. In that case you get text instead of an icon. Either another way to deal with that situation needs to be implemented or we need to find out why the has_icon() function isn't returning a proper value.

**Comment by Rolice** [comment]
Thanks you for the information @JosephMcc. So this means that `this.icon_theme.has_icon` funciton is failing as the flags are there as phisical files, but it does not detect them for some reason. I will try isolating the issue, if I get some spare time.

**Comment by JosephMcc** [comment]
@Rolice Yes. The flag icons are added to the icon theme by the applet. For some reason in newer gtk versions calling has_icon() returns false even when the icon exists. In Mint for example with gtk3.10 it works as expected.

We actually walked through this with @leigh123linux in IRC on a newer Fedora install that had this issue and the icons were added properly to the current icon theme but that one function call wasn't giving the expected value.

**Comment by Rolice** [comment]
Yes I confirm the same issue here on Debian with GTK 2.0 and 3.0 installed. Two installations same issue.

**Comment by lisuml** [comment]
Same issue here on cinnamon 2.8.4.

**Comment by lisuml** [comment]
Please review another patch: https://github.com/lisuml/Cinnamon/commit/90eec97a1abcbcd6592311ac2b9016846724a639

Basically instead of using `has_icon` method of IconTheme I replaced it with `lookup_icon`.

**Comment by ManIVIctorious** [comment]
This seems to work in cinnamon 3.0.7 Arch linux

**Comment by JosephMcc** [comment]
@petrucci4prez Does it work for you now?
