### ISSUE TITLE
cinnamon calendar applet should change its time zone after user applies system lang/region

### ISSUE THREAD

**Issue by tomoe-musashi** [linuxmint/Cinnamon#4359]
the calendar applet should automatically change its time zone after user applies system lang or region.
also, when users click the lock button, nothing happens, its not telling users are they really locked the date and time or not, there should be an unlock button or something.
(in mintlocale,i think that the description for language column "date and time" should be moved to the region column.)

**Comment by ManIVIctorious** [comment]
How do you set the time zone? When set by the cinnamon date and time settings this seems to work in cinnamon 3.0 flawlessly

**Comment by Vahan86** [comment]
@JosephMcc, can we close the issue?

**Comment by Vahan86** [comment]
@JosephMcc, can we close the issue?
