### ISSUE TITLE
full screen issues with 2.6.9

### ISSUE THREAD

**Issue by m00ster** [linuxmint/Cinnamon#4360]
Cannot have 2 full screen apps running on each monitor in a dual monitor setup:

full screen app on primary monitor when has focus causes panels on second monitor to be visible over the full screen app on that monitor and vise versa.

Full screen wine apps also cannot operate correctly on secondary monitor, but work correctly on primary.

**Comment by JosephMcc** [comment]
This should be fixed for Cinnamon 3.0
