### ISSUE TITLE
Issues with mouse cursor and scaled display

### ISSUE THREAD

**Issue by HTL2001** [linuxmint/Cinnamon#4362]
Recently (2? package updates ago on arch linux) the mouse pointer started respecting xrandr screen scaling (previously it would be the unscaled size even when scaling was enabled).  However this also came with two problems:

Graphical corruption: Around the pointer are a bit of a different pointer or just jumbled graphics
Inaccurate location: The actual "active" area of the pointer isn't matched to where the graphic shows it, noticed by say moving close to the window decoration.

Note that neither of these two show up if I try to do a screenshot in GIMP and include the pointer, the pointer is instead in the correct position and has no corruption.

**Comment by HTL2001** [comment]
Just to comment, the pointer corruption only seems to occur if I've recently had the mouse over an app with some other weirdness with hidpi (ie hipchat - text selection cursor is small but normal pointer is correct, online/away icons are small, text in searches only is small).  The inaccurate location is consistent though.

**Comment by HTL2001** [comment]
So I think the inaccuracy is present even on the main monitor of a hidpi display (not sure about non-hidpi), but its just small enough to not be an issue.  Its in the same direction (pointer above and to the left of actual click)

**Comment by HTL2001** [comment]
Issue appears to not be with cinnamon but probably xorg itself, it occurs as well under XFCE.  I'm unsure where I should report this though.

**Comment by MichaelAquilina** [comment]
I'm actually experiencing the exact same issue in Ubuntu Gnome 15.10

Did you find a solution for this?

It occurs when I use the following for example:
```
xrandr --output DP1 --scale 1.5x1.5
```

**Comment by Vahan86** [comment]
@HTL2001, is this still an issue for you with Cinnamon 3.2?

**Comment by Vahan86** [comment]
@JosepMcc, can we close the issue?
