### ISSUE TITLE
Cinnamon freezes while transferring files to a smartphone or tablet.

### ISSUE THREAD

**Issue by infected-lp** [linuxmint/Cinnamon#4363]
I have a Sony Xperia Z2 that is not recognized in Rebecca and Rafaela via USB (Both MTP and ADB) when i connect it.

I have to this procedure:

Install the libs libmtp-common mtp-tools libmtp-dev libmtp-runtime libmtp9

edit  /etc/fuse.conf
and uncomment "user_allow_other"

check usb connection to the PC via "lsusb"

edit file /lib/udev/rules.d/69-mtp.rules and add:

ATTR{idVendor}=="0fce", ATTR{idProduct}=="51af", SYMLINK+="libmtp-%k", ENV{ID_MTP_DEVICE}="1", ENV{ID_MEDIA_PLAYER}="1"

edit file /etc/udev/rules.d/51-android.rules and add:

ATTR{idVendor}=="0fce", ATTR{idProduct}=="51af", MODE=”0666"

then "sudo service udev restart"

This allows me to connect the Xperia Z2 to my PC and transfer files.
The issue is with Cinnamon now, that everytime i transfer a file, it simply freezes, no transfer dialog box is showed, and only when it finishes transferring, Cinnamon unfreezes.

If any further info is needed, please let me know. this bug is easily reproduced.

**Comment by leigh123linux** [comment]
This is a nemo issue please move your issue here

https://github.com/linuxmint/nemo

**Comment by infected-lp** [comment]
done.
