### ISSUE TITLE
[NOT A BUG] Request for glib2-2.44 help for backgroundManager.js

### ISSUE THREAD

**Issue by leigh123linux** [linuxmint/Cinnamon#4365]
Setting the background in programs like firefox, eog and shotwell no longer works due to glib2-2.44 changes.
Clem says he doesn't intend support the change and will revert the change in glib instead.
I was wondering if anyone could purpose a distro specific patch that could be used to fix it.

**Comment by clefebvre** [comment]
Link to upstream bug https://bugzilla.gnome.org/show_bug.cgi?id=733791

The fix is trivial, revert this in Glib: https://bug733791.bugzilla-attachments.gnome.org/attachment.cgi?id=281780
