### ISSUE TITLE
hour(s), minute(s) etc. should be fetched with ngettext

### ISSUE THREAD

**Issue by gunchleoc** [linuxmint/Cinnamon#4368]
There are some strings that need proper plural formatting in https://github.com/linuxmint/Cinnamon/blob/master/files/usr/lib/cinnamon-settings/modules/cs_power.py

e.g.:

```
if minutes < 60:
    if minutes == 1:
        time_string = ("%d " % minutes) + _("minute")
    else:
        time_string = ("%d " % minutes) + _("minutes")
    return time_string
```

should be:

```
if minutes < 60:
    return some_formatting_function(ngettext("%d minute", "%d minutes", minutes), minutes)
```

Same for everything down to line 77.

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html

**Comment by gunchleoc** [comment]
Thanks for pointing me to the document. It doesn't explain how you track which issues have been implemented though, so I actually find it a bit confusing.

Also, this is a bug, not a feature request, because it forces many translations to be broken ;)
