### ISSUE TITLE
Vocal  stills on the sound menu even after killing the process

### ISSUE THREAD

**Issue by sergioad** [linuxmint/Cinnamon#4370]
Hello @clefebvre @mtwebster and all t he Linux mint team, I noted an issue on t he Cinnamon's sound menu with Vocal and it is that  Vocal  stills on the sound menu even after killing the process, this is a hi level issue wich should be fixed as soon as possible, can you fix it and push the fix to a new Cinnamon 2.6 mantaince release? I really want this issue solved because when you kill Vocal or close it directly from the sound menu and them you open another window you get another Vocal entry on the sound menu untill you refresh cinnamon with Alt+F2 r or by logging off from the session

![captura de pantalla de 2015-06-26 16 16 03](https://cloud.githubusercontent.com/assets/5375145/8387543/e91ca5ec-1c1e-11e5-896b-daf35d041a0c.png)

![captura de pantalla de 2015-06-26 16 16 53](https://cloud.githubusercontent.com/assets/5375145/8387542/e91bfc82-1c1e-11e5-8e73-8c8376d7e626.png)

**Comment by pixunil** [comment]
Do you remember whether a similar issue also was there before `2.6`, so it is a regression?
On your machine, is it only Vocal or also another application?
One last question: when you close / kill Vocal and open the sound applet, before opening a new instance, is the old entry there?

In every case, I would like to see your logs `~/.cinnamon/glass.log` and `~/.xsesson-errors` (would be nice when you use some paste site, e.g. GitHub Gist)

**Comment by sergioad** [comment]
@pixunil https://gist.github.com/sergioad/c92e34cdd54e4c2d8b41

**Comment by collinss** [comment]
@pixunil I have experienced a similar issue with vlc and my soundbox desklet. I was planning on looking into it later, but haven't had a chance. I wonder, though, if it is a problem that some players have with dbus, so that the signals don't get sent when the player closes. Just a thought if you decide to look into it before I get the chance...

**Comment by pixunil** [comment]
As your logs don't look like the sound applet has failed in a way, can you try to launch some application to monitor your DBus? (e.g. `d-feet`)
After startng vocal, search in your session bus for the bus name `org.mpris.MediaPlayer.vocal` (the last part, `vocal`, can be different), close it and look if t disappears or not.

When it is so, it is the fault of vocal, and it wouldn't be a big surprise for me as very many young players fail with parts of mpris DBus stuff…

**Comment by sergioad** [comment]
I willt try in some time, I have switched from Cinnamon by now :smile:
