### ISSUE TITLE
FR: More fine grained power management options for Inhibit applet

### ISSUE THREAD

**Issue by michael-schaller** [linuxmint/Cinnamon#4372]
Hi everyone,

I'm currently wiping old disk drives and I'm using the Inhibit applet to temporarily disable the standby mode. This works great but unfortunately it also prevents my screen from going into standby.

Could the Inhibit applet be changed so that is is more similar to the Power Management options under Cinnamon Settings? The Power Management options under Cinnamon Settings allow to configure when screens will go into standby and when a machine goes into standby separately.

Maybe even better would be to have a general on/off switch for all Power Management options and nest the more specific suboptions under it...

Best,

Michael

FYI: @clefebvre

**Comment by Vahan86** [comment]
@JosephMcc, can we mark this issue as a feature request?

**Comment by weedy** [comment]
I would also like to see this done.

I just need to inhibit sleep/hibernate, I would prefer if my screen still went to sleep.

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html
