### ISSUE TITLE
Network applet shows wrong connection state (sometimes)

### ISSUE THREAD

**Issue by Hukuta** [linuxmint/Cinnamon#4373]
![selection_133](https://cloud.githubusercontent.com/assets/3100053/8392317/7e0a8fae-1cef-11e5-971e-59700742b0e3.png)

Sometimes it happens. 
Normalized after reconnection. 

File /usr/share/cinnamon/applets/network@cinnamon.org/applet.js is same as repository version.

**Comment by leigh123linux** [comment]
It isn't lying, it's showing the LAN icon in the applet which shows a disconnected state (same is displayed in your 'cinnamon-control-center network' screenshot).
Try disabling wired connection in  'cinnamon-control-center network' it should display the WIFI icon after that.

**Comment by Hukuta** [comment]
>Try disabling wired connection in 'cinnamon-control-center network' it should display the WIFI icon in applet after that.

How to do that? LAN is not connected, Wi-Fi is connected, but applet shows a disconnected state - is it not a bug?

**Comment by leigh123linux** [comment]
Go to wired tab and disable it with the slider (see screenshot)

![screenshot-window-2015-06-28-090523](https://cloud.githubusercontent.com/assets/1299302/8395645/58af178a-1d75-11e5-8920-546bcd8a0657.png)

**Comment by Hukuta** [comment]
![selection_133](https://cloud.githubusercontent.com/assets/3100053/8395651/55adad9c-1d86-11e5-98a5-ea3d7ceaa207.png)

i have'nt this element on wired tab

**Comment by Hukuta** [comment]
![screenshot1](https://cloud.githubusercontent.com/assets/3100053/8395658/ba0c307e-1d86-11e5-9f95-f737358cfcb3.png)
I found something like that on applet, but its disabled

**Comment by leigh123linux** [comment]
If you have a LAN cable plug it in and the missing slider should appear, after it does slide it to off.

**Comment by geckolinux** [comment]
I am also seeing this bug on openSUSE Tumbleweed with the latest Cinnamon 2.8. After the first login, the WiFI network connects very fast, but the Cinnamon network manager applet continues to show it in "connecting" state.

**Comment by camypaj** [comment]
I might have created a duplicate issue to what @geckolinux is experiencing:
[linuxmint/network-manager-applet/issues/9](https://github.com/linuxmint/network-manager-applet/issues/9). I did not manage to find anything that describes my problem accurately, so I created a new one. Only then I discovered that all the issues get created here, and not in the individual repositories. :/

**Comment by Vahan86** [comment]
@Hukuta, is this still an issue for you with Cinnamon 3.0?

**Comment by Hukuta** [comment]
no, can be closed

**Comment by geckolinux** [comment]
I still see have this issue occasionally with my WiFI connection, upon logging in to Cinnamon, the network applet shows unconnected, but the WiFI is actually connected.

**Comment by JosephMcc** [comment]
https://github.com/linuxmint/Cinnamon/issues/5061
