### ISSUE TITLE
Translation: Some strings need to be fetched with ngettext

### ISSUE THREAD

**Issue by gunchleoc** [linuxmint/Cinnamon#4374]
Please fetch the following strings with ngettext, so that they can be translated properly:

```
 (%s seconds ago)
```

Located in: files/usr/share/cinnamon/applets/notifications@cinnamon.org/applet.js:314

This one:

```
 (%s minute ago)
```

Located in:  files/usr/share/cinnamon/applets/notifications@cinnamon.org/applet.js:317

Can be combined with:

```
 (%s minutes ago)
```

Located in:  files/usr/share/cinnamon/applets/notifications@cinnamon.org/applet.js:320

This one:

```
%d updates available!
```

Located in: files/usr/lib/cinnamon-settings/bin/ExtensionCore.py:1126

Can be combined with:

```
%d update available!
```

Located in:  files/usr/lib/cinnamon-settings/bin/ExtensionCore.py:1128

**Comment by ManIVIctorious** [comment]
Is this still an issue in cinnamon 3.0?

**Comment by gunchleoc** [comment]
Yes, number ranges are still hard-coded in https://github.com/linuxmint/Cinnamon/blob/master/files/usr/share/cinnamon/applets/notifications%40cinnamon.org/applet.js#L318

**Comment by NikoKrause** [comment]
PR created to fix this issue
