### ISSUE TITLE
[FEATURE REQUEST] Implement power profiles

### ISSUE THREAD

**Issue by Anti-Ultimate** [linuxmint/Cinnamon#4376]
These would let you customize the CPU frequency, screen savers etc. for different cases of usage.

For instance, let's say you're using a notebook, and you have to use the battery.
You certainly don't want to have the CPU run at 100% and probably want to have it in power saving mode. This is where Windows and OSX are pretty good. They let you adjust CPU frequencies, spin down harddrives, and allow you to create several profiles so you can decide what you want to do.

Without any way to adjust cpu frequency, Cinnamon/Linux Mint simply isn't good for using on a notebook - I know there exist things like TLP that let you do this, but I think this should be in the settings manager regardless.

**Comment by tp0** [comment]
I'm not sure if this sort of stuff is in the scope of a smallish DE.

**Comment by Anti-Ultimate** [comment]
It should at least be a tool included in Linux Mint.

**Comment by roman-yagodin** [comment]
You could try [CPU Frequency Selector](http://cinnamon-spices.linuxmint.com/applets/view/70) applet. It sometimes hangs the Cinnamon (click on it carefully), and will ask for superuser rights for switching frequency for every core by default (it could be solved by setting `<allow_active>yes</allow_active>` in `/usr/share/polkit-1/actions/org.gnome.cpufreqselector.policy`).

**Comment by Vahan86** [comment]
@JosephMcc, can we mark this issue as a feature request?

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html
