### ISSUE TITLE
option to add a custom background to nemo file manager on Cinnamon

### ISSUE THREAD

**Issue by freemangilgamesh** [linuxmint/Cinnamon#4378]
I think users should be able to set a custom background to nemo file manager on Linux Mint.

**Comment by JosephMcc** [comment]
Not really sure why you would want to do this and I really don't see why there needs to be a setting for it. If you really wanted you could probably do this via the gtk theme.

**Comment by JosephMcc** [comment]
This is a nemo request not a Cinnamon one.
