### ISSUE TITLE
[Feature Request] Add 'Favorites apps' to menu applet.

### ISSUE THREAD

**Issue by leigh123linux** [linuxmint/Cinnamon#4380]
Please add 'Favorites apps' to menu applet like the one in mintmenu.

![2012-06-24-204605_1366x768_scrot](https://cloud.githubusercontent.com/assets/1299302/8403513/71b35e8a-1e3d-11e5-9e0b-05c241adc7a7.png)

**Comment by JosephMcc** [comment]
We currently have favorites on the left side of the menu. Are you just wanting some different type of layout?

**Comment by leigh123linux** [comment]
I know, it would more useful if it could dynamically change to reflect the recently used apps in it's own plane/tab.
The current favorites is kind of limited as anymore than 4-6 presets makes the menu huge.

**Comment by lestcape** [comment]
-1 to this idea if will change the cinnamon menu, +1 if this will be implemented as an option or in a different menu applet. +1 if favorites will have a hidden scroll and user can decide the maximum menu size.

**Comment by lestcape** [comment]
@leigh123linux about reflect the recently used apps, this can be implemented in a different menu category or also in a third-party applet. In configurable menu, when this commit will be reverted: https://github.com/linuxmint/Cinnamon/commit/51caa96c2e41b1c4019dce05828effc2e0ab919e

**Comment by SamuelMiller** [comment]
I like leigh123linux's suggestion. Unlike the Mate menu, there is little room to display and organize favourites in the default Cinnamon menu, besides the one column on the far left.  If one has, let's say, a dozen or more favourites, the menu ends up being fairly tall. Notice also that in the Mate menu, there are separators that allow one to group favourites.

**Comment by Vahan86** [comment]
+1 for @lestcape 's suggestion.

**Comment by NikoKrause** [comment]
I think it's similar to https://github.com/linuxmint/Cinnamon/issues/97

**Comment by JosephMcc** [comment]
@leigh123linux description for what he wants does fit that one.
