### ISSUE TITLE
Sound Applet Open/Quit Player Buttons Missing [solved]

### ISSUE THREAD

**Issue by Chaotajo** [linuxmint/Cinnamon#4381]
This seems to be happening quite a bit: When minimizing banshee to the sound applet, then clicking on the sound applet; there are no open or quit banshee buttons (one is an upward arrow, the other is an x). I have to restart cinnamon in order for the button to load. I have to open banshee from the menu.
![soundappletissue](https://cloud.githubusercontent.com/assets/13105761/8413338/68272032-1e55-11e5-97f2-a5afd72da2b1.png)
Any insights into this issue?
Update: this is now working after a clean install of 17.3.

**Comment by martinrotter** [comment]
Experienced exact same bug with VLC. Actually I have never seen quit/open buttons in sound applet. I thought that functionality is not even there.

**Comment by Chaotajo** [comment]
The buttons show sometimes. They are in the JavaScript file. Another thing that is happening is that banshee will be playing music and minimized to the sound applet but does not show up. In this case, I have to launch the (already open) banshee from the sound menu again. Strange...

**Comment by pixunil** [comment]
The sound applet checks whether the players allow raising and quitting.
Try to enable settings like MPris, DBus Interface in your player.
For me, it works perfectly with VLC.

**Comment by Chaotajo** [comment]
Mpris/Dbus is active. This has been less of an issue since I have upgraded to Rafaela (and also the buttons have moved to the top) I have never had an issue with VLC. Banshee is such a troublesome application that I am not ruling it out as the culprit. I would just like to know so I can prevent it from happening again.

**Comment by ManIVIctorious** [comment]
The sound applet has been reworked since the original post. Does this issue still apply to cinnamon 3.0?

**Comment by JosephMcc** [comment]
Seems to work fine here. I admit I don't use banshee a lot because I've had numerous issues with it and its buggy behavior in the past.

**Comment by Chaotajo** [comment]
This is still an issue for me. Another thing that happens is that if I launch VLC, I lose controls for Banshee.

**Comment by NikoKrause** [comment]
The sound applet has been reworked in LM 18.1.
I see close buttons (tested with Rhythmbox, VLC, XPlayer).
Also now it's possible to select/switch, which player to control, in the sound applet.
