### ISSUE TITLE
[Bug?] Activating panel windows with drag&drop

### ISSUE THREAD

**Issue by martinrotter** [linuxmint/Cinnamon#4383]
Let's imagine you have opened some file manager (for example Double Commander). In that file manager you have highlighted HTML file which you want to view. Beside Double Commander, you have also opened web browser (let's say Firefox) --> so you have two items in windows panel list (Double Commander and Firefox, Double Commander window is visible, Firefox window is minimized).

Let's say that you wish to drag selected HTML file and drop it into Firefox window to display it. Currently you must perform these steps:
1. Select and drag the file.
2. While dragging the file, hit ALT+TAB to bring Firefox window to front.
3. Drop the file onto Firefox window.

Some desktop environments and Windows offer this:
1. Select and drag the file.
2. While dragging, HOVER OVER target window ITEM IN WINDOWS PANEL LIST -> this will automatically bring hovered item's window in front.
3. Drop the file onto Firefox window.

So I am asking for drag&drop activation of items in windows panel list.

**Comment by dalcde** [comment]
I thought this is already working?

**Comment by martinrotter** [comment]
Not for me. When I use Double Commander + Firefox to reproduce this, it is not working.
Distribution: Arch Linux. What more info should I provide?

**Comment by JosephMcc** [comment]
It works for me as far as dragging the file over the window list brings the hovered window list item to the front. Firefox does not accept drag and drop of an HTML file regardless of how I do it. Don't think that's a cinnamon issue though. Works fine with some other apps. Sublime text for example.

**Comment by dalcde** [comment]
It seems to me that it's double commander that is handling dnd in a funny way. I could reproduce the issue with double commander but nothing else

**Comment by martinrotter** [comment]
Interesting. So is this doublecmd issue? I am using Qt 4-based version of doublecmd.

**Comment by martinrotter** [comment]
Firefox accepts drag&drop if you drop it in top tab bar to empty space as new tab.

**Comment by dalcde** [comment]
Curiously, the qt version works for me. However, it only works for the first time, when I drag to the window list. I cannot drag across different window list items. The gtk version doesn't work at all

**Comment by JosephMcc** [comment]
Ok, well if I drag to the proper place in Firefox it works fine with the Firefox and Nemo combo.

**Comment by martinrotter** [comment]
@dalcde Precisely.

**Comment by Vahan86** [comment]
@martinrotter, is this still an issue for you in Cinnamon 3.0.x?

**Comment by martinrotter** [comment]
@Vahan86 I switched to MATE some time ago. So not an issue for me anymore. :)
