### ISSUE TITLE
Desktop background is messed up

### ISSUE THREAD

**Issue by mondalaci** [linuxmint/Cinnamon#4385]
My desktop background is all messed up as can be seen on the picture below. Worse yet, I cannot change it via the Backgrounds dialog. Cinnamon 2.2.16

![screenshot from 2015-06-30 16 00 13](https://cloud.githubusercontent.com/assets/300402/8432594/47f998a2-1f41-11e5-8f6e-3fbd9fbf5727.png)

**Comment by theSeppi** [comment]
What's the brand and model of your graphics card/chip and which driver are you using?

**Comment by mondalaci** [comment]
Gainward GeForce 770GTX 4GB GDDR5 Phantom
[    89.543] (II) NVIDIA GLX Module  352.21  Tue Jun  9 21:22:54 PDT 2015
[    90.127] (II) NVIDIA(0): NVIDIA GPU GeForce GTX 770 (GK104) at PCI:1:0:0 (GPU-0)

**Comment by mondalaci** [comment]
As it turns out, the background chances upon resuming from sleep. Thought this additional info might be useful.

**Comment by lehjr** [comment]
This looks like the issue reported here: https://bugzilla.gnome.org/show_bug.cgi?id=739178
However, it should be noted that this is not limited to just nVidia proprietary drivers, as I have this with the fglrx (catalyst 15.5) driver on my HP Radeon HD 7450. 
[screenshot from 2015-07-19 10 58 33](https://cloud.githubusercontent.com/assets/1084367/8766426/f1f0b2aa-2e05-11e5-9dc6-ab5997fdbc20.png)

**Comment by Vahan86** [comment]
@mondalaci, is this still  an issue for you with Cinnamon 3?

**Comment by mondalaci** [comment]
@Vahan86 Nope, this is not an issue for me anymore. Running Cinnamon 3.0.7 right now.

**Comment by lehjr** [comment]
@Vahan86 I don't see this issue with Mint 18, but I'm using the nightly builds of Cinnamon.

**Comment by Vahan86** [comment]
@mondalaci, @lehjr thanks a lot for your reply. @mondalaci in this case can you please close this issue?

**Comment by Incanus3** [comment]
I'm having this exact issue with cinnamon 3.0.7 and nVidia GF106GLM [Quadro 2000M] graphics card.
