### ISSUE TITLE
The sound applet icon changes when the volume is adjusted

### ISSUE THREAD

**Issue by AXDOOMER** [linuxmint/Cinnamon#4387]
When I watch a video with VLC, the icon that the sound applet uses is the music note icon. When I adjust the volume while the video is played, the icon will change to the speaker icon for a few seconds and then go back to the music note icon. 

The "Control Players" option must be enabled. It is enable by default.

**Comment by JosephMcc** [comment]
It has been that way for as long as I can remember. I believe that is the intended behavior.

**Comment by pixunil** [comment]
As you said, it depends on the setting "Control Players".
If the setting "Show album art as icon" is deactivated, the note is shown.
If it is activated, and the player gives a cover, it shows it, else a cd icon.

In every case this means "I know you are playing media, you can control it with me".
But when you adjust your volume, it shows the normal volume icon for three seconds, to show you the volume level.

*******

As it is intended, I would like to know what you (not) expect.

**Comment by AXDOOMER** [comment]
From my perspective, I though that showing the normal volume icon when changing the volume was a bug and that the icon got refreshed after only three seconds so it corrected itself after this delay. The refresh delay seemed long to me. I didn't realize that showing the normal volume icon was there for the purpose of showing the volume level for these three seconds.

**Comment by JosephMcc** [comment]
If your issue has been answered could you please close this?

**Comment by AXDOOMER** [comment]
I wasn't aware that I could close my own issues. So, I've been told it's not a problem. I'll close the issue.
