### ISSUE TITLE
Cinnamon 2.6.12 crashes on Alt+Tab with several windows using Coverflow style

### ISSUE THREAD

**Issue by luisfpg** [linuxmint/Cinnamon#4388]
This bug happens to me once every 2-3 days, but can be easily reproduced.
I'm using Cinnamon 2.6.12 on Arch Linux in a dual-monitor setup.
I have Coverflow (3D) as Alt-Tab style.
Open nemo. Press Ctrl+N, and keep it pressed for a few seconds. You should open a lot (50+) nemo windows.
Then press Alt+Tab.
Then go to the second monitor and press Alt+Tab again (so the switcher should show in the second monitor).
Cinnamon crashes, and even the Alt+F2 dialog doesn't work, so I can restart Cinnamon.

**Comment by pixunil** [comment]
Can you try using only one monitor? With my single-monitor, this doesn't happen.

**Comment by JosephMcc** [comment]
I can't reproduce this on my dual monitor setup either. Running latest git Cinnamon on Mint 17.2.

**Comment by gajdy** [comment]
I can't reproduce it either. Tried with Mint 17.2 and Cinnamon 2.6.11. Maybe see screenshot below - no crash
![screenshot from 2015-07-06 22 05 54](https://cloud.githubusercontent.com/assets/516707/8532261/2e4b8fc8-242d-11e5-99ab-5ff76b67c880.png)

**Comment by luisfpg** [comment]
I can reproduce it all the time.
Here are 2 screenshots: before the problem and after the problem (the panel disappears):
Before:
![captura de tela de 2015-07-07 07-35-57](https://cloud.githubusercontent.com/assets/1183737/8544378/2c6f98ea-247b-11e5-8dae-abab9bba029c.png)
After:
![captura de tela de 2015-07-07 07-35-44](https://cloud.githubusercontent.com/assets/1183737/8544387/3ab3facc-247b-11e5-8225-a2cf1ba89248.png)

**Comment by Vahan86** [comment]
@luisfpg, is this still an issue for you with Cinnamon 3.2?

**Comment by luisfpg** [comment]
Sorry, I no longer have a second monitor to test it.

**Comment by Vahan86** [comment]
@luisfpg, thanks for your reply, in this case can you please close this issue?

**Comment by luisfpg** [comment]
Closing the issue as it can no longer be reproduced
