### ISSUE TITLE
Qt5 developed app doesn't display correctly using Cinnamon desktop in VirtualBox

### ISSUE THREAD

**Issue by te7** [linuxmint/Cinnamon#4389]
I have an app I've developed in Qt 5.3.1 that doesn't display data in output text boxes when using the Linux Cinnamon desktop in VirtualBox with 3D acceleration enabled in the display settings for the virtual machine. 

It does this when using the Cinnamon desktop in any Linux Distro (I've tried Cinnamon with Linux Mint, Ubuntu and Debian). The regular Unity desktop in Ubuntu and the Xfce desktops in both Linux Mint and Debian have no problem. Just Cinnamon. 

I don't know if this is a Cinnamon, VirtualBox or Qt problem. Months ago I registered a bug with the Cinnamon folks but I never saw a fix, or that the problem was replicated anywhere. If I disable 3D acceleration for any of the Cinnamon virtual machines in VirtualBox the problem doesn't happen.

I'm posting here because maybe some Qt developers have seen similar problems with Cinnamon in either VirtualBox, or a native Linux machine.

The app is called Lottery Analyzer Expert QL: it can be downloaded at http://tcesoftware.webs.com, follow the link to Linux Downloads. 

It's free. My main versions are Windows, but I have both a 32 bit and 64 bit version for Linux developed in Qt 5.3.1. I hope the link I posted is OK. It's a free application, though not open source (because of the nature of the subject). 

It does various analyses on the Powerball and Mega Millions lottery games. I developed the programs out of curiosity of how to do it, and offering them for free for all the very useful free software I've used over the years. 

Again, I hope posting the link is OK. I just want someone to try my program and see if they can replicate the problem in any environment. 

Just double click on either Lottery_32 (32 bit) or Lottery_64 (64 bit) in the folder created by downloading and unzipping the tar.gz. Then choose one of the analyze buttons or "drawn" buttons after entering the number of draws to sort. If it runs correctly data will fill the text boxes for the game chosen to sort the totals of. The problem will show if the text boxes are empty except for the last row.

Any comments or replies would be welcome. Thanks in advance for any.

**Comment by dalcde** [comment]
On Wed, Jul 01, 2015 at 09:45:46PM -0700, te7 wrote:
>Months ago I registered a bug with the Cinnamon folks but I never saw a fix, or that the problem was replicated anywhere.

Then why are you opening another issue for it?

**Comment by te7** [comment]
I thought this issue post had more info pertinent to the problem. Sorry if it wasn't acceptable. My apologies.

**Comment by te7** [comment]
BTW, in VMWare Player with 3D acceleration the problem doesn't appear. It only seems to appear with Cinnamon in VirtualBox with 3D acceleration.

**Comment by dalcde** [comment]
You could have commented on the original post
