### ISSUE TITLE
Suggestion for the "Attach dialog to parent titlebar" design

### ISSUE THREAD

**Issue by theSeppi** [linuxmint/Cinnamon#4391]
Currently, a dialog that is attached to its parent's title bar, looks like this, using the default theme in LM17.2:

![dialog_current](https://cloud.githubusercontent.com/assets/5564491/8503785/0cb487c6-21c5-11e5-93f1-aa66ed5955d4.png)

However, this dialog still looks rather detached from the parent window. I haven't found any possibility to theme that (yet, tell me if there is), but I've come up with an idea of how it could look more like it actually belonged to the parent:

![dialog_suggestion](https://cloud.githubusercontent.com/assets/5564491/8503800/5af5b84c-21c5-11e5-97c7-15234140cee0.png)

Note: This image was created using my poor image manipulation abilities... I would welcome it if something like this could be included. If it is possible to theme it (haven't found anything in `cinnamon/cinnamon.css`), please let me know.

**Comment by JosephMcc** [comment]
This happens due to the dimming effect that occurs on the parent window. I don't think there is anything you can do theme wise. I have an idea I can try but I don't know it will get anywhere. Also not sure if it's possible to force the window dimming to ignore only the applications title bar.

**Comment by JosephMcc** [comment]
The design was changed in 2.8. Attached window are now centered on the parent window.
