### ISSUE TITLE
[Documentation] Linux Mint 17.2 Cinnamon Edition - Greek 

### ISSUE THREAD

**Issue by NikTh** [linuxmint/Cinnamon#4392]
Hello and happy new "Rafaela" release. 
The documentation for Linux Mint Cinnamon edition has been updated to reflect the new version (17.2). 
Please upload the files where they belong (http://www.linuxmint.com/documentation.php) :+1: 

1) https://dl.dropboxusercontent.com/s/sz5784ret9fvhey/greek_17.2.pdf
2) https://dl.dropboxusercontent.com/s/xrsn79xb7b4bj0y/greek_17.2.odt

Best Regards 
[NickTh](https://en.gravatar.com/nikth76)

**Comment by dalcde** [comment]
This is not a Cinnamon issue. Send it to clem or something

**Comment by NikTh** [comment]
Done! 
Thanks
