### ISSUE TITLE
Nemo 2.6.7: Setting the arrange items "By Detailed Type" in the Default View is broken.

### ISSUE THREAD

**Issue by rsanting** [linuxmint/Cinnamon#4393]
When you set the arrange items under the Default view to "By Detailed Type" and you use the reset view to defaults option, nemo sorts by "Date Modified" instead of Detailed Type. This also happens in  any folder you have not yet entered before.

**Comment by tp0** [comment]
https://github.com/linuxmint/nemo/issues

**Comment by rsanting** [comment]
I totally missed that, I'll add the issue there.
