### ISSUE TITLE
[Regression] [Cinnamon 2.6.11] Tiling not working for all apps

### ISSUE THREAD

**Issue by MarceloRuiz** [linuxmint/Cinnamon#4394]
I am unable to tile Evolution. Tiling works with other apps (LibreOffice), but not with Evolution. It used to work in previous versions

**Comment by JosephMcc** [comment]
Evolution tiles fine here but there are a couple things you need to keep in mind with regards to tiling. For an app to tile it must be able to be resized to fit in the tiled area. Just testing really quick Evolution only allows resizing down to a certain size. That means that even though it works here, if your screen is a lower resolution it might not work for you. For example, if I want to tile to one half of the screen the app has to allow being resized to less that one half the screen width in pixels.

**Comment by MarceloRuiz** [comment]
Thanks for the answer!
Weird, but now that you mention it, Evolution does not resize to half of my screen (1080p). It did though in 17.1 (I often worked tiling Evolution and LibreOffice). Is there anything is the settings that has changed? I'm confused...

**Comment by JosephMcc** [comment]
It works here on my 1080p screen in 17.2. I'm not really familiar with Evolution but it could be the way the UI is set up or something you have open in it that I don't. The gtk and window border theme could probably even effect this if it's close.

**Comment by MarceloRuiz** [comment]
I can confirm that is not the theme nor the window border theme the cause of trouble.

**Comment by JosephMcc** [comment]
Well if Evolution won't resize to less than one-half the screen width, this isn't a Cinnamon issue. I don't really know what else might have changed.

**Comment by MarceloRuiz** [comment]
I can confirm it is not a Cinnamon problem: Evolution seems to have a minimum size that is not hard coded in pixels.
What triggered the problem was a change in the font settings: the new one is wider than the old one, pushing the minimum size forced by Evolution slightly above half of my screen resolution. That is why I could not tile it.
