### ISSUE TITLE
Error message cannot be closed when installing >1 theme

### ISSUE THREAD

**Issue by plata** [linuxmint/Cinnamon#4395]
I tried to install 2 Cinnamon themes at a time via the "theme" menu. The server was not reachable, so an error message showed up. It was not possible to close the first error message until the second one appeared. Obviously this happened because the dialog with the progress bar got window focus (or in other words: the error message did not stay modal on top of the progress dialog).

**Comment by Vahan86** [comment]
@plata, is this still an issue in Cinnamon 3.0?

**Comment by plata** [comment]
@Vahan86 Yes. 

It's really simple to reproduce it: Just go to themes, turn of your internet connection, select multiple themes and click install.

**Comment by Vahan86** [comment]
Can not reproduce the issue described in OP. It's working fine for me.
