### ISSUE TITLE
[17.2] [Optimus] System Tray GPU Icon not present on Optimus Laptop

### ISSUE THREAD

**Issue by MarceloRuiz** [linuxmint/Cinnamon#4399]
Hi,
I upgraded to mint 17.2 and it is not showing the GPU tray icon that should show which GPU I'm using.
(I have a Toshiba Satellite M640).
I tried to look for the applet to add it to the tray, but it is not listed anywhere. In fact, Mint 17.2 can't refresh the list of applets not extensions online (maybe it's there?). I am submitting a new issue for that.
Thanks!

**Comment by albel1205** [comment]
I had exactly the same problem with my Nvidia graphic card. I tried to go to the Driver Manager to install a driver for my Nvidia card from the list, then installed the prime-indicator to show the current running GPU by these commands below:
====================
~# add-apt-repository ppa:nilarimogard/webupd8
~# apt-get update
~# apt-get install mesa-utils prime-indicator
=================

Reference article link: http://xmodulo.com/install-configure-nvidia-optimus-driver-ubuntu.html

Hope this help

**Comment by anandrkris** [comment]
We now have a Nvidia Prime stock applet in Cinnamon.
@clefebvre - Can this be closed?

**Comment by clefebvre** [comment]
nvidia-prime-applet is the package at play here. Yes, this can be closed, it doesn't belong to cinnamon but to https://github.com/linuxmint/nvidia-prime-applet
