### ISSUE TITLE
[17.2] Unable to update applets or extensions lists online

### ISSUE THREAD

**Issue by MarceloRuiz** [linuxmint/Cinnamon#4400]
After installing Mint 17.2 in two different computers, I am unable to refresh the list of extensions or applets. The refreshing messages stays forever and eventually the connection times out or is reset by peer. I did not have this problem in 17.1.

**Comment by dalcde** [comment]
It's a server problem and is (probably) fixed now.

**Comment by Fjodor42** [comment]
Incidentally, I get a number of dialog windows with HTTP 404 when trying to update the theme lists now - is this related?

**Comment by MarceloRuiz** [comment]
Ok, now it shows the applets, but it does not upgrade them... is this the same server problem?
