### ISSUE TITLE
[Cinnamon 2.6.12] crashes after Login after update in Ubuntu 14.04

### ISSUE THREAD

**Issue by akalypse** [linuxmint/Cinnamon#4401]
I upgraded to Cinnamon 2.6.12 recently.
After a restart, I got: "Cinnamon just crashed. You are currently running in Fallback Mode. Do you want to restart Cinnamon?"

syslog shows that the application quit with signal 15:
cinnamon-session[3596]: WARNING: Application 'cinnamon.desktiop' killed by signal 15
cinnamon-session[3596]: WARNING: App 'cinnamon.desktop' respawning too quickly
cinnamon-session[3596]: CRITICAL: We failed, but the fail whale is dead. Sorry....

if I launch:

> cinnamon --replace

I see something related to an infinite recursion caused by calling global.settings.get_boolean("enable-looking-glass-logs") in /usr/share/cinnamon/main.js:260 (I added a log statement in overrides.js:78)

Window manager warning: Log level 8: gdk_display_get_screen: assertion 'screen_num == 0' failed
Window manager warning: Log level 8: gtk_window_set_screen: assertion 'GDK_IS_SCREEN (screen)' failed
Window manager warning: Log level 8: gdk_display_get_screen: assertion 'screen_num == 0' failed
Window manager warning: Log level 8: gdk_screen_get_setting: assertion 'GDK_IS_SCREEN (screen)' failed
Cjs-Message: JS LOG: GSettings key recursive. schema: org.cinnamon, key: enable-looking-glass-logs
Cjs-Message: JS LOG: About to start Cinnamon
Cjs-Message: JS LOG: GSettings key recursive. schema: org.cinnamon.sounds, key: switch-enabled
Cjs-Message: JS LOG: GSettings key recursive. schema: org.cinnamon.sounds, key: switch-file
Cjs-Message: JS LOG: GSettings key recursive. schema: org.cinnamon.sounds, key: close-enabled
Cjs-Message: JS LOG: GSettings key recursive. schema: org.cinnamon.sounds, key: close-file
Cjs-Message: JS LOG: GSettings key recursive. schema: org.cinnamon.sounds, key: map-enabled
Cjs-Message: JS LOG: GSettings key recursive. schema: org.cinnamon.sounds, key: map-file
Cjs-Message: JS LOG: GSettings key recursive. schema: org.cinnamon.sounds, key: minimize-enabled
Cjs-Message: JS LOG: GSettings key recursive. schema: org.cinnamon.sounds, key: minimize-file
Cjs-Message: JS LOG: GSettings key recursive. schema: org.cinnamon.sounds, key: maximize-enabled
Cjs-Message: JS LOG: GSettings key recursive. schema: org.cinnamon.sounds, key: maximize-file
Cjs-Message: JS LOG: GSettings key recursive. schema: org.cinnamon.sounds, key: unmaximize-enabled
Cjs-Message: JS LOG: GSettings key recursive. schema: org.cinnamon.sounds, key: unmaximize-file
Cjs-Message: JS LOG: GSettings key recursive. schema: org.cinnamon.sounds, key: tile-enabled
Cjs-Message: JS LOG: GSettings key recursive. schema: org.cinnamon.sounds, key: tile-file
Cjs-Message: JS LOG: GSettings key recursive. schema: org.cinnamon.sounds, key: login-enabled
Cjs-Message: JS LOG: GSettings key recursive. schema: org.cinnamon.sounds, key: login-file
Cjs-Message: JS LOG: GSettings key recursive. schema: org.cinnamon.sounds, key: plug-enabled
Cjs-Message: JS LOG: GSettings key recursive. schema: org.cinnamon.sounds, key: plug-file
Cjs-Message: JS LOG: GSettings key recursive. schema: org.cinnamon.sounds, key: unplug-enabled
Cjs-Message: JS LOG: GSettings key recursive. schema: org.cinnamon.sounds, key: unplug-file
Cjs-Message: JS LOG: GSettings key recursive. schema: org.cinnamon.desktop.sound, key: volume-sound-enabled
Cjs-Message: JS LOG: GSettings key recursive. schema: org.cinnamon.desktop.sound, key: volume-sound-file
Cjs-Message: JS LOG: GSettings key recursive. schema: org.cinnamon.theme, key: name
Cjs-Message: JS LOG: GSettings key recursive. schema: org.gnome.desktop.background, key: color-shading-type
Cjs-Message: JS LOG: GSettings key recursive. schema: org.gnome.desktop.background, key: picture-options
Cjs-Message: JS LOG: GSettings key recursive. schema: org.gnome.desktop.background, key: picture-uri
Cjs-Message: JS LOG: GSettings key recursive. schema: org.gnome.desktop.background, key: primary-color
Cjs-Message: JS LOG: GSettings key recursive. schema: org.gnome.desktop.background, key: secondary-color
Cjs-Message: JS LOG: GSettings key recursive. schema: org.gnome.desktop.background, key: picture-opacity
Cjs-Message: JS LOG: GSettings key recursive. schema: org.cinnamon.desktop.background.slideshow, key: slideshow-enabled
Cjs-Message: JS LOG: GSettings key recursive. schema: org.cinnamon, key: enable-edge-flip
[... removing similar logs - not relevant]
Window manager warning: Trying to remove non-existent custom keybinding "magnifier-zoom-in".
Window manager warning: Trying to remove non-existent custom keybinding "magnifier-zoom-out".

Cjs-Message: JS LOG: network applet: Cannot find connection for active (or connection cannot be read)
Cjs-Message: JS LOG: GSettings key recursive. schema: org.cinnamon, key: panels-show-delay
Window manager warning: Log level 16: Duplicate event event for 'glx.swapComplete'
Window manager warning: Log level 8: _cinnamon_global_set_plugin: assertion 'global->plugin == NULL' failed
Window manager warning: Log level 16: Duplicate event event for 'tweener.framePrepareStart'
Window manager warning: Log level 16: Duplicate event event for 'tweener.framePrepareDone'

Cjs-Message: JS LOG: GSettings key recursive. schema: org.cinnamon, key: enable-looking-glass-logs
[.... skipping a few log entries - they do only repeat]
Cjs-Message: JS LOG: GSettings key recursive. schema: org.cinnamon, key: enable-looking-glass-logs

(cinnamon:4936): Cjs-WARNING **: JS ERROR: InternalError: too much recursion
key_exists@/usr/share/cinnamon/js/ui/overrides.js:32
check_key_and_get@/usr/share/cinnamon/js/ui/overrides.js:36
overrideGio/Gio.Settings.prototype.get_boolean@/usr/share/cinnamon/js/ui/overrides.js:78
check_key_and_get@/usr/share/cinnamon/js/ui/overrides.js:38
overrideGio/Gio.Settings.prototype.get_boolean@/usr/share/cinnamon/js/ui/overrides.js:78
check_key_and_get@/usr/share/cinnamon/js/ui/overrides.js:38
[.... skipping a few log entries - they do only repeat]
overrideGio/Gio.Settings.prototype.get_boolean@/usr/share/cinnamon/js/ui/overrides.js:78
check_key_and_get@/usr/share/cinnamon/js/ui/overrides.js:38
overrideGio/Gio.Settings.prototype.get_boolean@/usr/share/cinnamon/js/ui/overrides.js:78
start@/usr/share/cinnamon/js/ui/main.js:261
@<main>:1
Window manager warning: Log level 32: Execution of main.js threw exception: JS_EvaluateScript() failed
---

I naively tried removing the check for that setting in main.js:

> if (false) { //added by me temporarily
> // if (global.settings.get_boolean("enable-looking-glass-logs")) {

but then cinnamon-session stopped with the following error:

> Window manager warning: Log level 16: Duplicate event event for 'glx.swapComplete'
> Window manager warning: Log level 8: _cinnamon_global_set_plugin: assertion 'global->plugin == >NULL' failed
> Window manager warning: Log level 16: Duplicate event event for 'tweener.framePrepareStart'
> Window manager warning: Log level 16: Duplicate event event for 'tweener.framePrepareDone'
> Cjs-Message: JS LOG: About to start Cinnamon
> (cinnamon:5052): Cjs-WARNING **: JS ERROR: Gio.IOErrorEnum: An object is already exported for >the interface org.Cinnamon at /org/Cinnamon
> Cinnamon.prototype._init@/usr/share/cinnamon/js/ui/cinnamonDBus.js:107
> Cinnamon@/usr/share/cinnamon/js/ui/cinnamonDBus.js:101
> start@/usr/share/cinnamon/js/ui/main.js:293
> @<main>:1
> 
> Window manager warning: Log level 32: Execution of main.js threw exception: JS_EvaluateScript() >failed

I suspect that there is some race-condition happening because cinnamon runs twice.
Thanks for your support and Kind regards,
Andy

**Comment by lestcape** [comment]
What repo you use? that's not happened to me...

**Comment by akalypse** [comment]
The unofficial PPA provided by you:
> cat /etc/apt/sources.list.d/lestcape-cinnamon-trusty.list
> deb http://ppa.launchpad.net/lestcape/cinnamon/ubuntu trusty main
> deb-src http://ppa.launchpad.net/lestcape/cinnamon/ubuntu trusty main

I just read (https://launchpad.net/~lestcape/+archive/ubuntu/cinnamon ) that I should use mdm, not lightdm. Just tried this, but same behavior as before.

**Comment by lestcape** [comment]
Please verify that you have not any retained package, and please verify that you don't use any third-party applet, desklet or extension. if you have someone, please move this extensions outside the folder and then try to initialize cinnamon. Then cinnamon init., move the extension back one by one checking always what is the extension that can be the cause of your problem.

**Comment by akalypse** [comment]
I don't have any third-party applets, desklets, extensions installed.
I tried removing cinnamon completely from my system and then re-install it. No success.
Switched back to Unity for now :-(

**Comment by lestcape** [comment]
Sorry, i have no idea why this could happen. You can test with the official unstable repo, to know better where is the problem.

**Comment by ptlis** [comment]
I'm having what looks like the same problem.

Linux Mint 17.1 & Cinnamon 2.4.8

[log files for cinnamon --replace & xorg](https://gist.github.com/ptlis/73fd740718f706abec5e)

I'm using the current fglrx driver from by AMD and I'm trying to use 3 displays.

Interestingly this only occurs when in multi-monitor mode, cinnamon is fine when using a mirrored setup.

As with @akalypse I don't have anything custom installed - this is a 100% vanilla Cinnamon/Mint install.

**Comment by skerit** [comment]
I'm having the same issue with a freshly installed Linux Mint 17.2, only when in multi-monitor mode using nvidia drivers.

**Comment by thendrix** [comment]
This seems to be related to XScreen changes.  I have a reproduction case for this from 2.8.6+rosa package build.  Basically, when I move a third monitor from Screen 0 to Screen 1 ( HMD ) it will reproduce this bug on my Nvidia 760GTX.  As a workaround I just disable the display or move it back to Screen0 as needed.  
Working display layouts with all displays on Screen0:  
[1920x1200][1200x1920][Disabled]
[1920x1200][1200x1920][1080x1920]

**Comment by ManIVIctorious** [comment]
Does this issue still happen with cinnamon 3.0?

**Comment by Vahan86** [comment]
@JosephMcc, can we close the issue?
