### ISSUE TITLE
hotcorner issue Mint 17.2, Cinnamon

### ISSUE THREAD

**Issue by DarekDeo** [linuxmint/Cinnamon#4402]
After update from 17.1 to 17.2. Currently issue happens on 17.2, on 17.1 it worked fine.

If I have my applet panel on top then right-top corner doesn't react if I move cursor from left to its right.
I've checked other hotcorners and everything works fine except right-top one.
Hotcorner works fine when I touch it from bottom, but If I touch it from left/top it doesn't react.

Similar things happens if I move applet panel to bottom of the screen, then buttom-right hotcorner stops working fine and top one works as supposed to.

Restaring Cinnamon doesn't help (haven't tried log-in/out yet).

**Comment by JosephMcc** [comment]
This should actually be fixed here: https://github.com/linuxmint/Cinnamon/pull/4375
It's part of the Cinnamon 2.6.12 update but I'm not sure if Mint has received it yet.
