### ISSUE TITLE
Panel appears over fullscreen windows when switching workspaces

### ISSUE THREAD

**Issue by Archenoth** [linuxmint/Cinnamon#4404]
When a window is fullscreen on a workspace, the panel is hidden below the window. This is good.
When you switch workspaces, and switch back, it remains hidden. This is also good.
But, when you try this with *two* monitors, the panel appears above the fullscreen window. This is not.

You can see the panel is blocking the Emacs Modeline on my first monitor here:
![screenshot from 2015-07-06 09 59 24](https://cloud.githubusercontent.com/assets/1385527/8526763/cf81aa02-23c5-11e5-98f1-e361081d3cce.png)

This happens reliably every workspace switch, and it happens regardless of the contents of the second monitor. (So, it happens when the fullscreen application is the only thing open.)

You can fix it by unfocusing the window... (Which seems to inadvertently happen when taking a screenshot.)

This is with CInnamon version 2.6.11+rafaela.

**Comment by Archenoth** [comment]
As a bit of an update... The workaround to hide the menubar I mentioned above does not appear to work when the fullscreen window is the only window open on any workspace.

Instead, you have to take the window out of fullscreen and put it back in again.

(Checked with 2.6.13)

**Comment by Archenoth** [comment]
I also found out that [Ctrl] + [Backspace] works as another workaround that puts the fullscreen window above the panel, though most other key combinations don't... (I wonder why those two keys in particular?)

**Comment by Archenoth** [comment]
Since this is mildly infuriating, and because the key-combo workarounds fail now... Here is what I use as an Emacs hook to keep it in the foreground.

``` emacs-lisp
(add-hook 'focus-in-hook (lambda ()
                           (lower-frame)
                           (raise-frame)))
```

This probably gives a hint as to what is wrong too... (Since I am just unfocusing and focusing in the frame again) Such a workaround can work for other applications too.

**Comment by JosephMcc** [comment]
Should be fixed by https://github.com/linuxmint/Cinnamon/pull/5229
