### ISSUE TITLE
when restarting, windows are not re-painted

### ISSUE THREAD

**Issue by brianjmurrell** [linuxmint/Cinnamon#4407]
When cinnamon [crashes and] is restarted [say, with killall -HUP cinnamon] the windows that are on the screen don't repaint.  All I see is the root window background.  Crashing/killing cinnamon into fallback mode repaints the windows, but when I choose *Yes* in the dialog that tells me I am in fallback mode to get it to restart cinnamon, I go back to the no-windows-painted mode.

This used to happen in 2.4 also but I could crash/kill it enough times that eventually one of the restarts would paint the windows.  This doesn't even seem to work with 2.6 and every single time it is restarted, no windows are repainted.

**Comment by JosephMcc** [comment]
I don't remember ever running into this and I crash Cinnamon quite a bit doing dev work. How are you causing so many crashes? Also you could check the logs, like .xsession-errors, to see if there are any indications as to why this is happening.

**Comment by brianjmurrell** [comment]
I think you are misunderstanding.  There was only one *original* crash, from having a few thousand notifications in the notifications applet and trying to open it.  All subsequent restarts were induced by using ```cinnamon --replace``` or ```killall -HUP cinnamon``` in a effort to get the windows to repaint.

They never did.  I ended up having to log out and in again.

But in 2.4, where cinnamon would "freeze" a few times a week or sometimes as a few times a day I had to restart cinnamon with a ```killall -HUP cinnamon``` and maybe half of the time I'd have to do that a few times before cinnamon would repaint the windows when it started.  In 2.6, I couldn't get it to restart and paint windows even after dozens of attempts (at ```kill -HUP cinnamon```, ```cinnamon --replace```, and ALT-CTRL-ESC) and as I mentioned, ended up having to logout and in again from a fallback session that started after killing cinnamon with ```-HUP```.

**Comment by VolMi** [comment]
This sounds like a non-Cinnamon issue to me. After all, the window manager is muffin.

Are you aware of the new shortcut, Ctrl+Alt+Esc, to restart Cinnamon? If I remember correctly, it does more than just restart Cinnamon itself, maybe it's Cinnamon+muffin.

**Comment by brianjmurrell** [comment]
> This sounds like a non-Cinnamon issue to me. After all, the window manager is muffin.

AFAIU, muffin is from Cinnamon.  It's a fork of mutter but as a fork, it means it's a Cinnamon component.

> Are you aware of the new shortcut, Ctrl+Alt+Esc, to restart Cinnamon?

Yes, per my previous message (to yours) in this thread, I mentioned using ALT-CTRL-ESC.

> If I remember correctly, it does more than just restart Cinnamon itself, maybe it's Cinnamon+muffin.

Maybe or maybe not.  Regardless, those three keys don't do anything to resolve the issue.

**Comment by Vahan86** [comment]
@brianjmurrell, is this still an issue in Cinnamon 3.0?

**Comment by brianjmurrell** [comment]
@Vahan86, I suppose it isn't.  But I haven't needed to kill cinnamon in a long while either.
