### ISSUE TITLE
[17.2] Network Manager Displaying Wrong Icon and Not Showing All Wireless SSIDs

### ISSUE THREAD

**Issue by MarceloRuiz** [linuxmint/cinnamon#4408]
I am connected to my WiFi Network. The connection is active, I am using it to write this bug report.
The Network Manager Applet displays as if my computer was connected through an Ethernet cable (no wireless icon shown). At the same time, it does not even display the SSID of the WiFi I am connected to in the list of available WiFi Networks. 
Issuing: "iwlist wlan0 scanning"  does show the network.

**Comment by Thorbur** [comment]
I sometimes experience the same problem. But then, when I turn wifi down and up again, the right symbol is shown. It would be good to know, if this is a reproducible bug or if there might be even an issue in the network connection itself. I am thinking of something like a stealth established VPN connection to sniff data or something like that. Has somebody any clue about it?

**Comment by Vahan86** [comment]
@MarceloRuiz, is this still an issue for you in Cinnamon 3.2?

**Comment by MarceloRuiz** [comment]
Yes, still present, random occurrence. My workaround was to just remove the applet and use the default indicator. The downside is the icon color of the default indicator is black...

**Comment by Vahan86** [comment]
@JosephMcc, can we mark this issue as a bug?

**Comment by Vahan86** [comment]
@MarceloRuiz, is this still an issue in Cinnamon 4.2?

**Comment by Vahan86** [comment]
@icarter09, can we close the issue since there is no response from OP?
