### ISSUE TITLE
Sound applet doesn't show up (probably crashed?)

### ISSUE THREAD

**Issue by plsamuel** [linuxmint/Cinnamon#441]
My sound icon applet never shows up...  Also, don't know if it's related, but my volume keys don't work at all either.  Restarting doesn't help.  Here's my dconf entry:

> ['panel1:left:0:menu@cinnamon.org', 
> 'panel1:left:3:places-bookmarks@dmo60.de',
> 'panel1:left:6:panel-launchers@cinnamon.org', 
> 'panel1:right:12:sound@cinnamon.org',          <----- HERE
> 'panel1:right:15:network@cinnamon.org', 
> 'panel1:right:18:bluetooth@cinnamon.org',
>  'panel1:right:21:power@cinnamon.org', 
> 'panel1:right:31:systray@cinnamon.org', 
> 'panel1:right:41:xrandr@cinnamon.org', 
> 'panel1:right:51:weather@mockturtl', 
> 'panel1:right:61:calendar@cinnamon.org', 
> 'panel1:right:71:power-off@martin', 
> 'panel2:center:0:window-list@cinnamon.org', 
> 'panel2:right:11:hwmonitor@sylfurd', 
> 'panel1:center:0:removable-drives@cinnamon.org']

is there a way to get a log of the plugin to help you debug why it doesn't load?  Audio works great in Flash, Skype and Banshee...

**Comment by pantuts** [comment]
me i just used volti
