### ISSUE TITLE
Cinnamon-preload preloading for all users in LDAP

### ISSUE THREAD

**Issue by Craigacp** [linuxmint/Cinnamon#4411]
I'm using Cinnamon 2.6 on a machine using an LDAP server for user authentication & automounted home directories. The cinnamon-preload daemon is iterating through the users in the LDAP directory and trying to preload information for them (which causes their home directory to be mounted). Is there an option to turn off this behaviour as it makes cinnamon unusable in my environment. Also, defaulting to su-ing from root to a user in a network environment is unfriendly.

I'm running Ubuntu 15.04 and the systemd journal is full of lines like:
Jul 07 08:11:12 `<hostname>` su[11353]: Successful su for `<username>` by root
Jul 07 08:11:12 `<hostname>` su[11353]: + ??? root:`<username>`
Jul 07 08:11:12 `<hostname>` su[11353]: pam_unix(su:session): session opened for user `<username>` by (uid=0)
Jul 07 08:11:12 `<hostname>` cinnamon[839]: gdk_mir_display_open
Jul 07 08:11:12 `<hostname>` cinnamon[839]: Failed to connect to Mir: Failed to connect to server socket: Permission denied
Jul 07 08:11:12 `<hostname>` cinnamon[839]: Unable to init server: Could not connect: Connection refused
Jul 07 08:11:12 `<hostname>` cinnamon[839]: (cinnamon-preload:11367): dconf-CRITICAL **: unable to create directory '/run/user/0/dconf': Permission denied.  dconf will not work properly.
Jul 07 08:11:12 `<hostname>` cinnamon-preload[11367]: Loading theme gnome for user ID `<userid>`
Jul 07 08:11:13 `<hostname>` cinnamon-preload[11367]: Loading gnome took 0.77 seconds
Jul 07 08:11:13 `<hostname>` su[11353]: pam_unix(su:session): session closed for user `<username>`

**Comment by mtwebster** [comment]
I'm doing some research on ldap ... do you guys know of a sure way to detect ldap is being used - would save me some trouble.

Thanks

**Comment by dalcde** [comment]
I don't think detecting ldap would be an effective solution. It is also possible that a computer has many non-ldap accounts, and preloading all of them would still take quite a lot of time.

**Comment by Craigacp** [comment]
It might be difficult as there are multiple different daemons which can connect to an LDAP server (or a NIS server), and all of them provide things through nsswitch, and I don't know if they can be easily inspected through that (e.g. nslcd, pam_ldap, sssd, yp). Simply turning this behaviour off when the LDAP/NIS packages are installed would probably be an easier fix, as they are not to be installed by default in common distributions like Ubuntu, Fedora or RHEL. Or just have it ask the user as part of package installation if they'd like the preload behaviour turned on.

**Comment by JosephMcc** [comment]
Cinnamon-preload has been removed.
