### ISSUE TITLE
cinnamon-preload with ldap configuration is doing weird stuff

### ISSUE THREAD

**Issue by manofthepeace** [linuxmint/Cinnamon#4412]
I've experienced something really weird and bad while upgrading to cinnamon 2.6.12 with lestcape's ppa on ubuntu 14.04. My user is not in the passwd file or a system user. I am in a ldap env.

*for p in pwd.getpwall():*

this python function returns all users including ldap (in my case more than 80 000), and the line after is
*subprocess.call(["su", p.pw_name, "-c", os.path.realpath(sys.argv[0])])*

so for all the users in the ldap it will create a home folder.. I was wondering why my laptop battery was lasting 30 mins and all the fans were at the max speed. So after you upgrade you MUST comment out the script that runs that I think this script can never really finish because the ldap is really big, I think it ran for more than 4 hours on my laptop total. Even using an other window manager wont help since it runs before the window manager. In top you will only see a "python2" running for different users for few seconds, taking 30% of the cpu;

TEMP. SOLUTION
*sudo vi cinnamon-preload-wrapper* (put a # before the only line)

Then if you home folder is dirty you can delete all the folders that were generated; there might be many ways but that's what I did for the cleanup;

from /home
*ls > /tmp/foo
sublime_text /tmp/foo  (remove important users from list)
sudo xargs -a /tmp/foo rm -rf*

**Comment by mtwebster** [comment]
duplicated here: https://github.com/linuxmint/Cinnamon/issues/4411
