### ISSUE TITLE
Cinnamon does not fullscreen minecraft 100% of the time

### ISSUE THREAD

**Issue by raidermax** [linuxmint/cinnamon#4413]
This occurs with the proprietary game Minecraft with the Radeonsi/open source drivers. It also occurs regardless of OpenJDK-JRE java (both 7 and 8). Essentially, when clicking fullscreen on Minecraft the window only resizes to the maximum, the panel still shows but the window is the color of my theme. I have to close Minecraft and open it up again in order for fullscreen to actually work. Turning off fullscreen also will work (after being in fullscreen already) but again, trying to enable it afterwards results in the same original problem I had.

I think this is a problem with the WM as, although my other machine configuration is completely different (LXDE + Openbox with nvidia prop. drivers) it does not have this issue, so I know for sure it is not Minecraft.

**Comment by Vahan86** [comment]
@raidermax, is this still an issue for you in Cinnamon 3.0?

**Comment by raidermax** [comment]
Sure is, I just tried it and the same issue described in OP still occurs. I am on Arch linux, kernel 4.7.4-1, cinnamon 3.0.7 and mesa 12.03, uhh, it happens on both OpenJdk/jre 7 and 8.

**Comment by Vahan86** [comment]
@raidermax, is this still an issue in Cinnamon 4.2?

**Comment by Vahan86** [comment]
@icarter09, can we close this issue since there is no response from OP?
