### ISSUE TITLE
Mouse click on empty workspaces: no desktop shown

### ISSUE THREAD

**Issue by roman-yagodin** [linuxmint/Cinnamon#4414]
In Cinnamon 2.0 (on LMDE 1), click on empty workspace always showed desktop. In Cinnamon 2.6.11 (on LMDE 2) this is not happen right after Cinnamon start / restart. 

To make this function work, I should open / close expo several times, drag some windows between workspaces, etc. - I can't tell exact sequence, but after some good kicks empty workspaces in expo start responding to mouse clicks, showing desktop.

Linux ******* 3.16.0-4-amd64 # 1 SMP Debian 3.16.7-ckt9-3~deb8u1 (2015-04-24) x86_64 GNU/Linux

**Comment by JosephMcc** [comment]
Can you still reproduce this in 2.8?

**Comment by roman-yagodin** [comment]
Using Cinnamon 2.8 about half an hour - but looks like the issue is fixed.

**Comment by JosephMcc** [comment]
Thanks.
