### ISSUE TITLE
nvidia-settings saved to /etc/X11/xorg.conf are ignored

### ISSUE THREAD

**Issue by jar349** [linuxmint/Cinnamon#4416]
I have a sager NP9752-S laptop with a Nvidia GTX 970M card (running Cinnamon). I have two external monitors connected, but my BIOS doesn't give me the option to switch the boot screen to one of them, so I need to keep my laptop screen open so that I can see the grub boot screen.

In 17.1, I was able to configure my /etc/X11/xorg.conf to disable the laptop screen (even though it was open) and just use my two external monitors.

In 17.2, once I log in, the laptop display turns on and becomes part of my screen, which sucks because my laptop screen is under my desk and becomes my "primary display". Note that my login screen appears on my external monitor as always. The laptop display only turns on once I log in.

I can use nvidia-settings (as root) to disable the laptop display and save it to /etc/X11/xorg.conf, but as soon as I reboot and log in, the laptop display turns on.  By the way, if I close the laptop screen, my display settings automatically change to just use the two external monitors - even though my power settings are configured to "do nothing" when the laptop screen is closed.

Because of this behavior and because the screen settings change at login, I suspect that there may be some new user-level setting in 17.2 that has to do with changing display settings?  My xorg.conf file is neither removed nor modified - it simply seems to be ignored.

**Comment by jar349** [comment]
Here's my /etc/X11/xorg.conf file (DP-1 and DP-3 are my two DELL U2515H monitors):
```
# nvidia-settings: X configuration file generated by nvidia-settings
# nvidia-settings:  version 346.47  (buildmeister@swio-display-x86-rhel47-01)  Thu Feb 19 19:18:25 PST 2015

Section "ServerLayout"
    Identifier     "Layout0"
    Screen      0  "Screen0" 0 0
    InputDevice    "Keyboard0" "CoreKeyboard"
    InputDevice    "Mouse0" "CorePointer"
    Option         "Xinerama" "0"
EndSection

Section "Files"
EndSection

Section "InputDevice"
    # generated from default
    Identifier     "Mouse0"
    Driver         "mouse"
    Option         "Protocol" "auto"
    Option         "Device" "/dev/psaux"
    Option         "Emulate3Buttons" "no"
    Option         "ZAxisMapping" "4 5"
EndSection

Section "InputDevice"
    # generated from default
    Identifier     "Keyboard0"
    Driver         "kbd"
EndSection

Section "Monitor"
    # HorizSync source: edid, VertRefresh source: edid
    Identifier     "Monitor0"
    VendorName     "Unknown"
    ModelName      "DELL U2515H"
    HorizSync       30.0 - 113.0
    VertRefresh     56.0 - 86.0
    Option         "DPMS"
EndSection

Section "Device"
    Identifier     "Device0"
    Driver         "nvidia"
    VendorName     "NVIDIA Corporation"
    BoardName      "GeForce GTX 970M"
EndSection

Section "Screen"
    Identifier     "Screen0"
    Device         "Device0"
    Monitor        "Monitor0"
    DefaultDepth    24
    Option         "Stereo" "0"
    Option         "metamodes" "DP-1: nvidia-auto-select +0+0, DP-3: nvidia-auto-select +2560+0"
    Option         "SLI" "Off"
    Option         "MultiGPU" "Off"
    Option         "BaseMosaic" "off"
    SubSection     "Display"
        Depth       24
    EndSubSection
EndSection
```

**Comment by leigh123linux** [comment]
Why do you think that this is a cinnamon issue?, cinnamon doesn't even know of /etc/X11/xorg.conf existence and never has.
Xorg server reads it!
As for power settings 'lid setting' this has nothing to do with monitor setting, it sets power action only (suspend, off, or do nothing).


If you want the monitor to do nothing try

```
gsettings set org.cinnamon.settings-daemon.plugins.xrandr default-monitors-setup do-nothing
```


```
clone' will display the same thing on all monitors, 'dock' will switch off the internal monitor, 'do-nothing' will use the default Xorg behaviour (extend the desktop in recent versions). The default, 'follow-lid', will choose between 'do-nothing' and 'dock' depending on whether the lid is (respectively) open or closed.
```

The defaut setting is follow-lid

**Comment by jar349** [comment]
When I first boot up, the login screen shows on the external monitor, and the laptop monitor is turned off.  So it seems like Xorg server reads the conf file and does the correct thing.  It's only when I log in that the laptop monitor turns itself on and gets added to my "screen".

Since this happened with the upgrade to 17.2, I thought that there might have been a new addition to Cinnamon that is doing something.  If that's not the case, then I need to figure out what else runs at user login to figure out what is resetting my display settings.

**Comment by pupuser** [comment]
Check your lid settings. In windows it's somewhere in the power settings. On Puppylinux there are text configs under /etc/laptop-mode.

**Comment by pupuser** [comment]
in cinnamon 18 it seems to be in /usr/share/cinnamon/cinnamon-settings/modules/cs_power.py 
do a text search for lid_options

**Comment by ManIVIctorious** [comment]
@JosephMcc I don't think this is a cinnamon issue

**Comment by JosephMcc** [comment]
@jar349 Are you still having this issue? Have you by chance tested with any other DE's to see if the behavior is different?

**Comment by jar349** [comment]
Yes, though I discovered a "fix" in a reddit thread:

1. use nvidia-settings to make the changes you want and apply them.  Close the app.
2. open the mint display settings and use the "identify" function and then click save/apply (I forget the button name offhand).

From then on, my settings are remembered.

**Comment by leigh123linux** [comment]
@JosephMcc I believe this could be addressed by exposing the default-monitors-setup options in settings

```
org.cinnamon.settings-daemon.plugins.xrandr default-monitors-setup
```

clone' will display the same thing on all monitors, 'dock' will switch off the internal monitor, 'do-nothing' will use the default Xorg behaviour (extend the desktop in recent versions). The default, 'follow-lid', will choose between 'do-nothing' and 'dock' depending on whether the lid is (respectively) open or closed.

**Comment by sling00** [comment]
This bug is still present, it is 100% related to cinnamon, and still super annoying, now in the latest iteration of cinnamon, one must click apply and then click "revert" when it asks to keep or revert settings.  Then the settings applied with nvidia-settings will stick.

Please bring the linux desktop in to the current century and remove artificial limitations like this.  Or at least offer a tickbox to honor the xorg settings so that power users may do as they wish.

**Comment by leigh123linux** [comment]
Using /etc/X11/xorg.conf is obsolete so why should we support it!

**Comment by sling00** [comment]
Because your management tool cannot handle all scenarios.  In fact, it cannot even change the refresh rate of the monitor.  At least this would allow a workaround to use advanced options if desired, vs the utterly hacky way of making settings stick now.

**Comment by pupuser** [comment]
Obsolete or Deprecated. It seems Xorg is still working. And superior in some situations.

**Comment by pupuser** [comment]
We could always move to a kinder distro which is more flexible and doesn't use "!" when communicating to its user base.
