### ISSUE TITLE
No panel after suspend

### ISSUE THREAD

**Issue by jmgomezpoveda** [linuxmint/Cinnamon#4417]
The suspend functionality was recently fixed (https://github.com/linuxmint/Cinnamon/issues/4060) for my use (Ubuntu 15.04, systemd).

However, when my computer resumes after suspend, the lower panel is not visible. I have tried restarting Cinnamon (F2 + r), but the lower panel does not come back. Only restarting the system does the lower panel appear again.

There is no error message shown.

**Comment by jmgomezpoveda** [comment]
I have just realised that this problem does not just happen after suspend, but whenever Cinnamon is restarted (i.e. if I press F2 + r at any time, the lower panel disappears).

**Comment by mrpohoda** [comment]
I have a similar problem with panel after suspend - I can only see icons in the notification area. No Workspaces, launched programs nor Applications menu are visible.

**Comment by Vahan86** [comment]
@jmgomezpoveda, is this still issue for you with Cinnamon 3.0?

**Comment by jmgomezpoveda** [comment]
This seems to be fixed now. I just tested this in 3.0.7-1 (Ubuntu 16.10) and the panel is there after suspend and resume. Restarting Cinnamon (ALT-F2 + r) also works fine now.
