### ISSUE TITLE
[Feature Request] menu search results: highlight category on mouse hover

### ISSUE THREAD

**Issue by VolMi** [linuxmint/Cinnamon#4420]
**Problem**
Sometimes I wonder in which category of the Cinnamon menu would i find an application. There is the search, which is great, but does not provide this answer:
![current_no_help](https://cloud.githubusercontent.com/assets/1189207/8591060/230509b4-2626-11e5-8a4b-0475c4b75562.png)

**Suggestion**
Make use of the category column and when a specific search result is focused (e.g. mouse hover), highlight the corresponding category:
![mockup_category_highlight](https://cloud.githubusercontent.com/assets/1189207/8591063/2881451a-2626-11e5-8de4-da749028ae9a.png)

**Comment by Vahan86** [comment]
@JosephMcc, can we mark this issue as a feature request?

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html
