### ISSUE TITLE
Startup applications

### ISSUE THREAD

**Issue by wirebeard** [linuxmint/Cinnamon#4422]
Can't apply application or user command in Control Center - Startup application. Nothing happens when i click "Apply". Cinnamon 2.6.13.

**Comment by JosephMcc** [comment]
Could you do me a favor? Open a terminal and run:
cinnamon-settings startup

See if it shows any errors and maybe explain a bit more what you're trying to do so I can try to reproduce and fix it here.

**Comment by wirebeard** [comment]
Here terminal output:

~ $ cinnamon-settings startup
Python module
Loading Startup Applications module
__init__ took 163.977 ms
Traceback (most recent call last):
  File "/usr/lib/cinnamon-settings/modules/cs_startup.py", line 532, in on_add_app
    print "Failed to copy desktop file %s" % desktop_file
NameError: global name 'desktop_file' is not defined

After in pop-up window, when i am click close button, nothing happens. Window closes when click close button in window corner.

**Comment by wirebeard** [comment]
After add in /usr/lib/cinnamon-settings/modules/cs_startup.py in  line 532 

 print "Failed to copy desktop file %s" % user_desktop_file

I see, that i did not have the permissions in /home/user/.config/autostart, after change - all works.

**Comment by JosephMcc** [comment]
Not having permissions caused your problem but it still pointed out an error in the code. So thanks for raising the issue so it can be fixed.

**Comment by wirebeard** [comment]
You are welcome))
