### ISSUE TITLE
Can't send to sleep laptop while lock screen is active

### ISSUE THREAD

**Issue by Arpy222** [linuxmint/Cinnamon#4423]
Hello!
There is no interaction when the machine is locked, when I would like to just suspend it.
I have to login to be able to do that.
It would be really useful, If it could be enabled in the settings.
dmesg message about it:
[66077.779144] ACPI Error: No installed handler for fixed event - PowerButton (2), disabling (20140424/evevent-286)

Thank you for your help!

**Comment by qgates** [comment]
You can try suspend from the lock screen by editing `/etc/systemd/logind.conf` and un-commenting and changing minutes:
```
IdleAction=suspend
IdleActionSec=15min
```
The above solution works for the login prompt (ie. with no user logged in) and may work for the lock screen too.

**Comment by Vahan86** [comment]
@JosephMcc, can we mark this issue as a feature request?

**Comment by JosephMcc** [comment]
If it is still an issue it belongs here: https://github.com/linuxmint/cinnamon-screensaver
