### ISSUE TITLE
Window snapping and tiling shortcuts reversed in Keyboard Settings

### ISSUE THREAD

**Issue by rkingsbury** [linuxmint/Cinnamon#4424]
On my install (upgraded from 17.1 to 17.2), the keyboard short cuts listed for window snapping and tiling in the Keyboard settings dialog are reversed. Super+arrow keys snaps windows, but is described as "Push Tile up/down/left/right" in the dialog. Ctrl+Super+arrow keys tiles windows, but is described as "Push snap up/down/left/right".

**Comment by JosephMcc** [comment]
Just tested here on Mint 17.2. Both shortcuts seem to behave exactly the same for me. They both tile the window if it's untiled and then push it around the monitor edges or untile it if it's already tiled.

**Comment by dalcde** [comment]
It's working fine for me

**Comment by Vahan86** [comment]
It's working fine for me as well. Cinnamon version: 3.0.7
