### ISSUE TITLE
Cinnamon 2.6, 2.8 crashes when external monitor is connected.

### ISSUE THREAD

**Issue by timawesomeness** [linuxmint/Cinnamon#4425]
LMDE 2, Cinnamon 2.6.7, Kernel 4.1, Latest Intel drivers in Jessie.
When connecting my computer to an external monitor, Cinnamon crashes. If I run "cinnamon --replace", it crashes with the error message: 

```
Cogl-ERROR **: Failed to create texture 2d due to size/format constraints
Trace/breakpoint trap
```

**Comment by KOLEGA007** [comment]
@timawesomeness I dont know, how to help you, but provide more informations about kernel and driver, I had the same issue, but when i upgraded kernel to 3.19 everything went fine ...

**Comment by timawesomeness** [comment]
Kernel 4.1, Latest Intel drivers in Jessie.

**Comment by tomasss1024** [comment]
cinnamon also crashes on mint 17.2 (Asus Eee - connected external monitor)
kernel 3.16.0-38
cinnamon 2.6.11

**Comment by KOLEGA007** [comment]
Guys, copy the output from this command here
*tail -f /var/log/syslog*
right after cinnamon freeze (you can go using Ctrl + Alt + F1 to another terminal)

**Comment by tomasss1024** [comment]
the same on kernel 3.16.0-43, 3.19.0-22

eeepc colord: Device added: xrandr-Hewlett Packard-HP E231-3CQ3161D64
eeepc kernel: [  119.029056] perf interrupt took too long (2515 > 2500), lowering kernel.perf_event_max_sample_rate to 50000
eeepc cinnamon-session[2141]: WARNING: Application 'cinnamon.desktop' killed by signal 15
eeepc kernel: [  130.844238] usb 3-1: USB disconnect, device number 2
eeepc acpid: input device has been disconnected, fd 12
eeepc colord: device removed: sysfs-Lite-On_Technology_Corp.-HP_Basic_USB_Keyboard
eeepc laptop-mode: Laptop mode 
eeepc laptop-mode: enabled, active
eeepc laptop-mode: Laptop mode 
eeepc laptop-mode: enabled, active
eeepc cinnamon-session[2141]: WARNING: App 'cinnamon.desktop' respawning too quickly
eeepc cinnamon-session[2141]: CRITICAL: We failed, but the fail whale is dead. Sorry....

**Comment by timawesomeness** [comment]
Here's what I get:
```
Jul 21 18:36:19 chickengenerator colord: Device added: xrandr-Samsung Electric Company-SyncMaster-HVDZ904438
Jul 21 18:36:30 chickengenerator kernel: [153175.030461] traps: cinnamon[2213] trap int3 ip:7f4040b8ad30 sp:7ffdc80fd900 error:0
Jul 21 18:36:30 chickengenerator x-session-manager[2048]: WARNING: Application 'cinnamon.desktop' killed by signal 15
Jul 21 18:36:32 chickengenerator console-kit-daemon[918]: (process:2751): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed
Jul 21 18:36:57 chickengenerator console-kit-daemon[918]: (process:2842): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed
```

**Comment by timawesomeness** [comment]
Still an issue with Cinnamon 2.8.5.
Arch Linux, Kernel 4.2.5, latest Intel drivers that Arch has.
Same errors as before.

An interesting thing to note is that I am also on an eeepc, and the issue doesn't occur on my desktop, or with an HP netbook.

**Comment by slizovskiy** [comment]
I have the same problem!   Dec 15 13:00:54 sergey-PORTEGE-R700 kernel: [ 4463.515786] [UFW BLOCK] IN=eth1 OUT= MAC=00:23:18:8f:28:92:00:08:e3:ff:fd:a8:08:00 SRC=158.125.160.38 DST=158.125.34.61 LEN=124 TOS=0x00 PREC=0x00 TTL=61 ID=59904 PROTO=ICMP TYPE=3 CODE=10 [SRC=158.125.34.61 DST=158.125.160.38 LEN=96 TOS=0x00 PREC=0x00 TTL=61 ID=50124 DF PROTO=UDP SPT=137 DPT=137 LEN=76 ] 
Dec 15 13:00:54 sergey-PORTEGE-R700 kernel: [ 4463.515837] [UFW BLOCK] IN=eth1 OUT= MAC=00:23:18:8f:28:92:00:08:e3:ff:fd:a8:08:00 SRC=158.125.160.38 DST=158.125.34.61 LEN=124 TOS=0x00 PREC=0x00 TTL=61 ID=59905 PROTO=ICMP TYPE=3 CODE=10 [SRC=158.125.34.61 DST=158.125.160.38 LEN=96 TOS=0x00 PREC=0x00 TTL=61 ID=50125 DF PROTO=UDP SPT=137 DPT=137 LEN=76 ] 
Dec 15 13:00:56 sergey-PORTEGE-R700 kernel: [ 4465.518444] [UFW BLOCK] IN=eth1 OUT= MAC=00:23:18:8f:28:92:00:08:e3:ff:fd:a8:08:00 SRC=158.125.160.38 DST=158.125.34.61 LEN=124 TOS=0x00 PREC=0x00 TTL=61 ID=59906 PROTO=ICMP TYPE=3 CODE=10 [SRC=158.125.34.61 DST=158.125.160.38 LEN=96 TOS=0x00 PREC=0x00 TTL=61 ID=50192 DF PROTO=UDP SPT=137 DPT=137 LEN=76 ] 
Dec 15 13:00:56 sergey-PORTEGE-R700 kernel: [ 4465.518505] [UFW BLOCK] IN=eth1 OUT= MAC=00:23:18:8f:28:92:00:08:e3:ff:fd:a8:08:00 SRC=158.125.160.38 DST=158.125.34.61 LEN=124 TOS=0x00 PREC=0x00 TTL=61 ID=59907 PROTO=ICMP TYPE=3 CODE=10 [SRC=158.125.34.61 DST=158.125.160.38 LEN=96 TOS=0x00 PREC=0x00 TTL=61 ID=50193 DF PROTO=UDP SPT=137 DPT=137 LEN=76 ] 
Dec 15 13:01:02 sergey-PORTEGE-R700 kernel: [ 4471.021979] traps: cinnamon[5555] trap int3 ip:7f8a2629bc13 sp:7ffd90cb6d30 error:0
Dec 15 13:01:02 sergey-PORTEGE-R700 cinnamon-session[2434]: WARNING: App 'cinnamon.desktop' respawning too quickly
Dec 15 13:01:02 sergey-PORTEGE-R700 cinnamon-session[2434]: CRITICAL: We failed, but the fail whale is dead. Sorry....

**Comment by ManIVIctorious** [comment]
Is this still an issue in cinnamon 3.0?

**Comment by timawesomeness** [comment]
It no longer crashes with 3.0(.7), but is extremely laggy, to the point of being unusable, when the external monitor is connected. Every GUI action in any application has a delay of at minimum several seconds, generally much longer.

Cinnamon output is as follows:
```
Cjs-Message: JS LOG: About to start Cinnamon
St-Message: cogl npot texture sizes SUPPORTED
Cjs-Message: JS LOG: Cinnamon started at Tue Sep 06 2016 16:58:13 GMT-0600 (MDT)
Window manager warning: Log level 16: Theme directory status/scalable of theme Circle-Flat has no size field

Window manager warning: Log level 16: Theme directory status/scalable of theme Circle-Flat has no size field

Cjs-Message: JS LOG: network applet: Cannot find connection for active (or connection cannot be read)
Window manager warning: Log level 16: Theme directory status/scalable of theme Circle-Flat has no size field

openGL version 2.1 Mesa 12 detected (GL Cogl Driver)
MetaSyncRing disabled: couldn't find required GL extensions, or the minimum safe openGL version was not met
Cjs-Message: JS LOG: Invalid network device type, is 14
Cjs-Message: JS LOG: network applet: Found connection for active
Window manager warning: Log level 16: STACK_OP_RAISE_ABOVE: window 0x1c002d0 not in stack
Window manager warning: Log level 16: STACK_OP_RAISE_ABOVE: window 0x1c00396 not in stack
Window manager warning: Log level 16: STACK_OP_RAISE_ABOVE: window 0x1c003c4 not in stack
Window manager warning: last_focus_time (643634) is greater than comparison timestamp (488353).  This most likely represents a buggy client sending inaccurate timestamps in messages such as _NET_ACTIVE_WINDOW.  Trying to work around...
Window manager warning: last_user_time (495063) is greater than comparison timestamp (489648).  This most likely represents a buggy client sending inaccurate timestamps in messages such as _NET_ACTIVE_WINDOW.  Trying to work around...
Window manager warning: 0x1c00413 (nemo) appears to be one of the offending windows with a timestamp of 495063.  Working around...
```
journalctl does not report any errors.

No issues occur when mirroring the displays or only using one, only when extending the displays.

**Comment by clefebvre** [comment]
We believe this issue is fixed. Please test against the latest Cinnamon version (3.6). If the issue happens again, create a new issue and add a stracktrace.

**Comment by githukuj** [comment]
Cinnamon 4.4.8 crashes during software update, installation of new application and when Mendeley Desktop is ran. This ONLY occurs in extended display, no problems when no external monitor is attached.
