### ISSUE TITLE
Feature request: unify the behavior of set_style_class_name and add_style_class_name

### ISSUE THREAD

**Issue by lestcape** [linuxmint/Cinnamon#4428]
The method that i currently use to insert any external extension inside a cinnamon theme support, is find an appropriate similar selector in the cinnamon stock theme and set this style to my objects, instead of if used for another complete different things. Thats is problematic then.

I recommend:

Create standard selectors for the most common usage, that not include any padding for example, and  set it with set_style_class_name then can be included a more refine one using add_style_class_name for the cinnamon stock themes.

In this way, the externals devs can reused the cinnamon standard themes, without any problem and add a more refined one to be used in his particular cases. This will also a big help for the theme authors that currently they want to support externals applets and desklets and also for the externals devs.

Anyway, there are a more problematic things, that can be easy resolved. When an external development invoke add_style_class_name after used set_style_class_name the add_style_class_name will be omitted, also if there are not a selector in the stock theme. See an example:

cinnamon.css
.example-selector {
    color: black;
}
.other-selector {
    color: red;
}

stylesheet.css (the style inside the external applet)
.example-selector {
    color: white;
}
.add_style-selector {
    color: blue;
}
.set_style-selector {
    color: white;
}

if i do:
actor.set_style_class_name('example-selector') my actor will receive the black color as need to be, because the priority is for the cinnamon theme.

if I do:
actor.set_style_class_name('set-style-selector') my actor will receive the white color as need to be, because the priority is for the cinnamon theme but not exist a selector in this case and will be used my selector. Excelent!!!

if I do:
actor.set_style_class_name('example-selector')
actor.set_style_class_name('other-selector')
my actor will receive the red color as need to be, because the priority is for the last selector in the cinnamon theme. Excellent!!!

but if i do:
actor.set_style_class_name('example-selector')
actor.add_style_class_name('add-style-selector')
my actor will receive the black color, i think this is complete opposite to what externals devs want. The selector add-style-selector need to be override the example-selector in this case, as is not present in the stock theme.

**Comment by JosephMcc** [comment]
This is something that certainly could be improved. I've talked with mtwebster about it and he was looking into the idea of using Sass. While it wouldn't work exactly like you are describing, it would be similar. We could create a set of "stock" variables, so to speak, for themes to use that a dev could rely on for their custom elements.

**Comment by lestcape** [comment]
Ahh... @JosephMcc yes, but what you say is more than what i say.
What you say will be wonderfull, as will resolved the most common users request, that will be change the color of things for example and not the space in some places.

Sass, is a more refined way, but i think is not what common user want, and will be more complex make a theme with Sass and will be also more work to @mtwebster. Anyway also with Sass i consider this taks important. I think, we can use property inheritance in a stylesheet in a css  and then inherit the basic style without affecting the cjs code...

Speaking of other thing. I will appreciate your advice in this applet. If you have time.
https://github.com/lestcape/Color-Chooser

**Comment by JosephMcc** [comment]
Learning Sass takes a bit of work but once you get the hang of it creating themes is really no more difficult than with normal css. Plus a lot of users want to do simple things like adjust colors which is much easier to do since it introduces the use of color variables much like you have it gtk themes.

It's also the direction the gnome devs have gone with gnome-shell and gtk so people are going to be getting more familiar with it as time goes by.

**Comment by dalcde** [comment]
I'm not sure I understand the request here. The documentation clearly states

`st_widget_set_style_class_name()`
>  Set the style class name list. `style_class_list` can either be `NULL`, for no classes, or a space-separated list of style class names

`st_widget_add_style_class_name()`
> Adds `style_class` to actor's style class name list, if it is not already present.

The distinction between `add_style_class_name` and `set_style_class_name` is completely unrelated to the usage of different css stylesheets.

**Comment by lestcape** [comment]
@dalcde and what we talk is about the usage, not about the documentation. What we talk is not a contradition with any in the documentation. As how we have two source (css stylesheets). One in the global theme, and another inside the applet (for example). You can say that there are not classes if there are not one in the global css stylesheets, but there are one in the applet stylesheets? I think, in this case add_style class_name need to use the applet stylesheets. What currently occurs is that don't use anything, if there are not in the global theme, they don't see the applet. And i consider this fact a problem, because there are one (in the applet). With  set_style class_name not occurs the same. If there are not a global, they look inside the applet.

**Comment by dalcde** [comment]
Okay I was misinterpreting your title. I thought you meant that there was discrepancy between the behaviours of `set_style_class_name` and `add_style_class_name`

**Comment by lestcape** [comment]
@dalcde yes... Sorry for my english...

**Comment by lestcape** [comment]
As additional i consider also important make a fork of this:
https://git.gnome.org/browse/gnome-shell/commit/?id=2935fd4

When you want to separate actors, the current way is create a container to this actor and set the padding in the container. With the margin property, we don't need anymore the container.

**Comment by lestcape** [comment]
This is why i consider this important: https://github.com/lestcape/Color-Chooser/issues/1

**Comment by collinss** [comment]
@lestcape you can also create space between actors by using the ```spacing:``` property on the container. That way you don't have to create a separate container for each actor just to give it padding.

**Comment by lestcape** [comment]
@collinss the spacing attribute is not an standard one. This is only possible inside a CinnamonGenericContainer, and not inside any St actor. I try to avoid the usage of CinnamonGenericContainer, as is more less the same of people of Gnome try to do in his popupmenu api, and this possible will be ported to Cinnamon in the future. A CinnamonGenericContainer is an anachronistic class than on my opinion will disappear in the future releases of St.

**Comment by collinss** [comment]
@lestcape I use the spacing property inside a ```St.BoxLayout``` all the time and it works just fine for me. I'm pretty sure it wont work in a CinnamonGenericContainer unless you specifically code it in. Also, CinnamonGenericContainer is used when you need to have more control over allocation than an St actor will give you. It allows you to do things in Javascript that you can't do any other way. I've actually used it several times in my projects, and it has been VERY invaluable. I doubt it's going anywhere any time soon.

**Comment by lestcape** [comment]
@collinss, I'm agree with you about the current importance of CinnamonGenericContainer, but i say in the future of St. 

For CinnamonGenericContainer: https://github.com/linuxmint/Cinnamon/blob/master/js/ui/popupMenu.js#L84 and https://github.com/linuxmint/Cinnamon/blob/master/js/ui/popupMenu.js#L336

Where is spacing in the standard stylesheets model? I can not get it work out of a GenericContainer, and also spacing wont create the same effect of margin, so is not the same. If I only have one actor, spacing where?
http://www.yourhtmlsource.com/stylesheets/cssspacing.html

**Comment by lestcape** [comment]
@collinss https://github.com/GNOME/gnome-shell/blob/master/js/ui/popupMenu.js take a look, GenericContainer is obsolete in the shell popupmenu api. And i consider this an important improve of gnome shell, as a lot of people, see:
https://github.com/rgcjonas/gnome-shell-extension-appindicator/blob/master/dbusMenu.js#L472-L476
