### ISSUE TITLE
Gnome keyring dialog for unlocking ssh key does not get focus

### ISSUE THREAD

**Issue by xhpohanka** [linuxmint/Cinnamon#4440]
If I try to call ssh command from terminal (guake in my case) opened keyring dialog does not have focus so I need to use a mouse to fill my password in.

**Comment by Vahan86** [comment]
@xhpohanka, is this still an issue for you in Cinnamon 3.0.x?

**Comment by xhpohanka** [comment]
I just tried it again. It works as expected in gnome-terminal, but not with guake. Maybe it is guake issue...

**Comment by aL3xa** [comment]
I had the same problem in Guake (although on Arch + GNOME). Unchecking _Run command as a login shell_ in _Shell_ options tab did the trick.

**Comment by Vahan86** [comment]
@JosephMcc, can we close this issue?
