### ISSUE TITLE
[Idea] A swipe gesture to open expo

### ISSUE THREAD

**Issue by marmistrz** [linuxmint/Cinnamon#4441]
It's a little clumsy to open the expo now, either with a kbd shortcut or some mouse hover stuff. It'd be great to use "swiping" - for example drag the very bottom of the screen halfway to the top.

**Comment by JosephMcc** [comment]
To be honest, that hardly seems easier than the current options.

**Comment by marmistrz** [comment]
Well, to me it would be much quicker to swipe than to press ctrl+shift+down/up

**Comment by pixunil** [comment]
#861 · Similar issue (only the movement is new)

For me, the problem exists for the dragging part: I have my panel at the bottom and often many apps fullscreen.
When I drag somewhere, should it effect the application (dragging items, resizing, …), the applets on the panel (e.g. windowlist, starters), or should it be expo or scale?
I don't try to tell that this is impossible, but I think it could create conflicts or unexpected actions.

**Comment by JosephMcc** [comment]
@pixunil I agree with you. I think it comes down to the fact that I don't understand how this would be less clumsy than using the hot corners.

**Comment by gordon-morehouse** [comment]
What about multitouch dragging instead? Such things are included in OS X and people who like them tend to like them a lot.
