### ISSUE TITLE
Alt+Enter doesn't show file/folder properties in 17.2 cinnamon

### ISSUE THREAD

**Issue by sevenskull** [linuxmint/Cinnamon#4442]
One of my last cinnamon update, disabled the shortcut Alt-Enter for file/folder info in desktop or in nemo manager.
This happen in Cinnamon.

I've made a fresh 17.1 cinnamon install (no additional softwares installed), updated to 17.2 (with kernel) before other updates, since here it was ok.
Then i updated everything else (even level 4 and 5) in update manager, restarted, and alt-enter shortcut is not working anymore.
Every update i did was through the update manager.

I formated my computer again, and happened again. One update caused this, but i don't know which one.

Desktop: Cinnamon 2.6.13
Kernel: 3.16.0-38-generic x86_64 (64 bit)
Distro: Linux Mint 17.2 Rafaela

**Comment by qgates** [comment]
Can't reproduce this. I too upgraded from 17.1 to 17.2 and with the latest updates Alt+Enter is working properly (64 bit). I've also tested on other machines, both laptops and desktops, running 32-bit Cinnamon with the latest updates. In my case all machines are running standard graphics (ie. no proprietary gfx driver installed).

I can only assume something else is affecting this. Perhaps some add-on program is stealing the shortcut. Are you running a vanilla install of Mint, or have you added other programs / desktop mods?

**Comment by sevenskull** [comment]
This was a vanilla install, like i said (no additional software installed).
1: I installed 17.1 from my pendrive, reboot.
2: Went to update manager, get the last update manager.
3: Update to 17.2
4: Update the kernel to the recommended
5: reboot
6: Update everything from 1 to level 5.
7: reboot

And Alt+Enter not working anymore. Like i said i did this format thing twice, and both time happened.

This was on my notebook. I also use cinnamon on my desktop. There i have a lot of programs and stuff, and custom things, proprietary drivers, etc. And there i update to 17.2 and i had no problems at all.

About my notebook again, i downloaded the 17.2 and made a vanilla install. Updated everything, and the problem didn't happened.

So i guess it was something specific to my notebook, and updating from 17.1 to 17.2.

Should i close this?

**Comment by qgates** [comment]
Suggest leaving this open for now. It would be useful to see if anyone else is affected, specifically upgrading from 17.1 to 17.2. It's possible that this may have something to do with your specific setup since it was fairly customised, but if the issue can be repeated by others we may get down to a bug :)

**Comment by KOLEGA007** [comment]
Unaffected, Upgraded from 17 -> 17.1 -> 17.2 64bit Cinnamon, Nemo 2.6.7
@sevenskull What is your nemo version? (Nemo->Help->About)

**Comment by sevenskull** [comment]
@KOLEGA007 
Couldn't say it now for sure, because i formatted all over again and installed 17.2 directly, and it's working fine now.
But like i said i updated everything available from lvl 1 to 5 with update manager.
And in my home desktop which i update from 17.1 to 17.2 with a lot of softwares installed, i didn't had this issue, just with my fresh install with my notebook.

**Comment by KOLEGA007** [comment]
@sevenskull Ok, so probably there was something bad, which we cant detect now :) At least its working for you :)
