### ISSUE TITLE
mouse sensitiviy changes on new monitor connection

### ISSUE THREAD

**Issue by acidicX** [linuxmint/cinnamon#4443]
This is a long standing issue for me :-)
Every time I connect another monitor the mouse sensitivity changes (at least for my touchpad). The bigger the monitor, the faster the pointer becomes. This is annoying for laptops on a docking station with external (secondary) monitors and every time you connect a projector to your laptop.
This could be fixed while working on https://github.com/linuxmint/Cinnamon/issues/4343 ?
Thanks!

//edit: latest cinnamon on Arch Linux btw, but I had the same issue with Linux Mint two years ago.

**Comment by Vahan86** [comment]
@acidicX, is this still an issue for you in Cinnamon 3.0?

**Comment by acidicX** [comment]
@Vahan86 Yes, issue still exists. Currently on arch with `Cinnamon 3.0.7`

**Comment by Vahan86** [comment]
@acidicX, does this issue still exist in Cinnamon 4.2?

**Comment by acidicX** [comment]
@Vahan86 idk, switched to gnome3 recently. I did not notice it anymore before that, though, but might have been because the display resolution changed.

**Comment by icarter09** [comment]
@acidicX thanks for the update.
