### ISSUE TITLE
Incorrect transition effect when restoring windows from minimised (2.6)

### ISSUE THREAD

**Issue by qgates** [linuxmint/Cinnamon#4444]
The desktop effect in question is “Mapping” which is used both for new windows and restoring minimised windows.

In Cinnamon 2.6 - for "mapping" the effect used when restoring window from minimised state behaves like “Scale” even when set to “Traditional”. Can we have the 17.1 / Cinnamon 2.4 effect back ie. shows the window zooming up from the panel, and perhaps have a separate option for “creating” windows?

Interestingly, the effect preview for "Traditional" shows "scale" behaviour when viewing effect previews in "mapping", versus the correct behaviour for all other transition categories. I am aware from the readme that this behaviour is at least partially by design, however I assume the intent is for _new windows_ to appear using the "scale" effect, and _not_ windows restored from minimised state.

**Comment by pixunil** [comment]
When a window is unminimised, there are two cases:

- the _minimised_ effect is `traditional`: Use `traditional` as _unminimize_ effect (the reverse thing)
- else, run the _mapping_ effect

afaik, it was the same as in 2.4

The _mapping_ and _closing_ effect `traditional` is new and the preview is correct. It applies a different effect for dialog boxes (see [the source](https://github.com/linuxmint/Cinnamon/blob/master/js/ui/windowEffects.js#L139))

**Comment by JosephMcc** [comment]
The unminimize effect was broken during some updates to the window list applet.

**Comment by qgates** [comment]
@pixunil Thanks for the info. But the current unminimise behaviour is not using the "traditional" effect, it is always using "scale". As @JosephMcc points out, this effect is incorrect. Cinnamon 2.4 behaviour showed windows correctly "zooming up" from the panel when restored from a minimised state - assuming "traditional" was set as the minimise effect.

Can we agree that the current behaviour is incorrect ie. a bug?
