### ISSUE TITLE
Queued file copy progress shows incorrect percentage when copying many files to a device

### ISSUE THREAD

**Issue by qgates** [linuxmint/Cinnamon#4445]
Queued file copy progress percentage is incorrect by a country-mile when copying a number of large files sequentially (ie. file by file) to a device, say using drag and drop for each file

**Comment by Vahan86** [comment]
@qgates, could you please check it in Cinnamon 3.0 and let us know is this still an issue for you or not?

**Comment by JosephMcc** [comment]
If this is still an issue it should probably be here: https://github.com/linuxmint/nemo/issues
 There may in fact already be an open issue for this.
