### ISSUE TITLE
Pull request: Added support for hardware mic mute button (XF86AudioMicMute)

### ISSUE THREAD

**Issue by gerow** [linuxmint/Cinnamon#4448]
According to xev the hardware mic mute button on my machine generates an event with the key XF86AudioMicMute but it's currently unhandled (if it is supposed to be handled, sorry but I guess this would turn into a bug report instead). XF86AudioMute already seems to be handled properly, so hopefully this shouldn't be too complicated of a change.

Let me know if I need to elaborate.

**Comment by gerow** [comment]
It's just occurred to me that the actual change would lie in cinnamon-settings-daemon (I think). Is the intention that all Cinnamon issues should share a common issues queue or should I move this over to cinnamon-settings-daemon?

**Comment by gerow** [comment]
I have a patch in the works for this. Will open PR on the appropriate repos when it's ready.

**Comment by gerow** [comment]
*ping*

**Comment by gerow** [comment]
*ping* again

I have PRs open in cinnamon-desktop and cinnamon-settings-daemon to implement this, but it's been all quiet.

**Comment by clefebvre** [comment]
Hi, sorry for the delay. We're working in cycles of 6 months, sometimes it takes time, sometimes it goes fast, it all eventually gets reviewed though :)

Many thanks for these PR.

**Comment by gerow** [comment]
Ah, looks the last time I opened a PR I was just lucky to get right on the end of that cycle.

Thanks!
