### ISSUE TITLE
[Feature request] Add 'Refresh' to the desktop context menu

### ISSUE THREAD

**Issue by tomoe-musashi** [linuxmint/Cinnamon#4449]
as title.

**Comment by kelebek333** [comment]
Could you manually add as following.

First install xdotool

sudo apt-get install xdotool

Then run following command

sudo gedit /usr/share/nemo/actions/nemo-refresh.nemo_action

And paste following lines to nemo-refresh.nemo_action and save it.

[Nemo Action]

Name=Refresh

Comment=Nemo Refresh

Exec=xdotool key ctrl+r

Selection=None

Extensions=any;

Icon-Name=view-refresh

Name[tr]=Tazele



Finally refresh Nemo file manager

nemo -q
nemo -n &

**Comment by tomoe-musashi** [comment]
thank you anyway.
we can find refresh button in the menu bar, but not on the desktop.
please consider ship this by default.

**Comment by KOLEGA007** [comment]
@tomoe-musashi Why you need refresh? 
If you create in desktop location a file (from Nemo's window) it appears on desktop, so where is the problem?

**Comment by mtwebster** [comment]
F5 still works on the desktop to refresh

**Comment by Vahan86** [comment]
@tomoe-musashi, could you please explain why we need "Refresh" in desktop context menu?

**Comment by JosephMcc** [comment]
https://github.com/linuxmint/nemo/issues/1048
