### ISSUE TITLE
"Urgent" hint blinks window list button four times, then stops blinking

### ISSUE THREAD

**Issue by crsaracco** [linuxmint/Cinnamon#4450]
In Pidgin, I can set it to send the "Urgent" window manager hint via Pidgin's "Message Notification" plugin. In cinnamon, this seems to blink just four times and then stops blinking. I'd like options to keep it blinking forever, or keep the window's button red forever (without blinking).

Right now I miss a lot of messages because I don't know that they come in, because I miss the only four blinks that occur.

I'm using Cinnamon 2.6.13-1 on Arch linux.

**Comment by mtwebster** [comment]
The pre-2.6 behavior was to blink a few times and stay highlighted - I really don't think options are necessary here, I've fixed it to behave that way once more.
