### ISSUE TITLE
Snap to a configured width instead of 50/50

### ISSUE THREAD

**Issue by jankramer** [linuxmint/Cinnamon#4451]
Is it possible to configure the size of the grid to which windows snap using the super+arrow key combination somehow? E.g. 66% for the left side and 33% for the right side. Currently I achieve this by manually resizing windows, but it would be nice if you could configure the size of the grid.

If this feature is currently not available and if you accept contributions, I would be willing to add the functionality. I'm not familiar with the Cinnamon code base however, so some quick pointers on how/where this should be implemented would be great.

**Comment by tp0** [comment]
+1. Something I have always missed from Compiz Grid. I find 1/3 and 2/3 split much more useful than 1/2.

Are you familiar with Compiz Grid plugin? In that, when you just kept pressing e.g. super+left/right it kept cycling through the pre-configured sizes (e.g. 1/3 -> 1/2 -> 2/3).

There's an applet galled [gTile](http://cinnamon-spices.linuxmint.com/applets/view/100), unfortunately it requires mouse to be used, so not really the same thing.

**Comment by tp0** [comment]
Also, I found this Gnome Shell extension:

https://github.com/dnoegel/KeyTiling
https://www.youtube.com/watch?v=wEN9_X6wG2g

An old comment [from here](https://blueprints.launchpad.net/linuxmint/+spec/compiz-grid-functionality-for-cinnamon): _It works in Cinnamon (only requires that "cinnamon-version": ["1.4"] is added to metadata.json). It assumes that the panel is located at the top of the screen, but that can easily be modified in extension.js._

I tried that and put the current version in the .json file, is it just supposed to show up in the Extensions settings?

Anyway, maybe that code could be re-used or the extension could be simply ported to Cinnamon.

**Comment by caligari87** [comment]
+1 from me as well. Another extension or program which achieves the same is QuickTile, which mimics WinSplit Revolution. Pressing the left/right snap keys cycles between 1/2, 1/4, and 3/4 screen width, but I don't want to install yet another 3rd-pary program to duplicate/replace functionality that could already be included in Cinnamon

**Comment by rpbaptist** [comment]
Considering 21:9 monitors and high res 16:9 monitors are becoming more and more present, this feature would be really helpful. I often work on a 21:9 monitor and tiling left and right just doesn't work as well on that ratio.

The ultimate scenario would be having a configuration where a desktop grid for tiling and snapping could be defined.

**Comment by pappasam** [comment]
+1 from me as well. This functionality would be most-excellent and would be great for use with wide monitors.

**Comment by skuep** [comment]
+1. That is what I want to do in a few weeks and would hate to not use Cinnamon.

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html

**Comment by Futureknows** [comment]
+1 from me only thing I miss from Gnome
