### ISSUE TITLE
Do not make Nemo hard-dependency of Cinnamon

### ISSUE THREAD

**Issue by martinrotter** [linuxmint/Cinnamon#4452]
Not sure if this is distro-specific (Arch Linux), but I guess it is not.

I am not using Nemo ('cause it has some annoying unsolved bugs and lacks some core features). I am using Double Commander instead, thus, I do not need having Nemo installed? Why Cinnamon desktop depends on Nemo? At least in Debian, Ubuntu, Arch it does. Could Cinnamon be tweaked to not depend on Nemo?

**Comment by leigh123linux** [comment]
It's added by the distro

https://projects.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/cinnamon#n20

I do the same for fedora

http://pkgs.fedoraproject.org/cgit/cinnamon.git/tree/cinnamon.spec#n132

I can't remember why it is so.

**Comment by GLolol** [comment]
https://github.com/linuxmint/Cinnamon/search?utf8=%E2%9C%93&q=nemo

Cinnamon-session, cinnamon-killer-daemon, and cs-desktop (Cinnamon settings) all expect Nemo to be there as far as I can tell.

**Comment by leigh123linux** [comment]
It's listed as a required components in the session file in cinnamon.

https://github.com/linuxmint/Cinnamon/blob/master/files/usr/share/cinnamon-session/sessions/cinnamon.session#L3

**Comment by martinrotter** [comment]
@GLolol  And why is that? I mean, nemo is file manager....

**Comment by GLolol** [comment]
@martinrotter I'm totally for more flexibility in the dependency chain; I'm just pointing out what requires Nemo atm. It isn't my call which dependencies get added.

**Comment by mtwebster** [comment]
Nemo is *Cinnamon's* file manager - it's never been intended to be anything but.  As such, it has a number of Cinnamon-specific interactions, like special context menu items, desktop management (whose options are controlled in Cinnamon Settings) and so on.  Simply put, Cinnamon is not intended to be used without Nemo, from a UX perspective, and so it's called out as a dependency.

Of course it's not strictly needed by Cinnamon.  It can be made to not start at all simply by unchecking 'Show desktop icons' in Cinnamon Settings->Desktop options.  Apart from it still being installed, it will not be used by anything if you make sure to alter any file manager defaults for launching programs and the like to point to some other preferred file manager.

**Comment by lestcape** [comment]
I think that the basic problem here, is that not exist a protocol of what a file-manager need to ensure. And there are not a general interface to do it. 
I agree with @martinrotter,  speak of a "file-manager-y"  is the Desktop-x's file manager is in my opinion wrong, but as opposite, is necessary. Not all file-managers have the same interface to recive the call of an action. I think this needed to be reported in freedesktop.org and wait to be accepted from all file-managers and distros, and then will be possible remove the dependency. Also the gnome dependency of nautilus or the unity dependency of nautilus.

**Comment by martinrotter** [comment]
So basically, If I force removal of nemo, what will break in cinnamon itself? Are there also other parts of cinnamon which in-fact can be removed without any functionality loss?

**Comment by lestcape** [comment]
@martinrotter if there are a packages that can be removed without lost functionalities, please report it, sure will be removed from the cinnamon default debian rules and then for other distros and packages when they see the change. So, not, there are not any thing that you can removed without lost functionalities. For the first question, you has already a response here: https://github.com/linuxmint/Cinnamon/issues/4452#issuecomment-122363251, please test it yourself.

**Comment by martinrotter** [comment]
Well, I would expect that all components actually TRACK its dependencies when they are developed by someone. This state looks like ABSOLUTE MESS to me. I mean, Cinnamon devs really do not know exact dependencies of each Cinnamon component they develop?

**Comment by martinrotter** [comment]
So, OK. I will test it for Nemo. I created Arch nemo-dummy package for testing.

https://gist.github.com/martinrotter/1d68548bbd725dad79ba

**Comment by martinrotter** [comment]
Okay, tested. Cinnamon does not allow any log-ins when Nemo is not installed. I mean, seriously? It is supposed to be just file manager, but what can I do. :)

**Comment by leigh123linux** [comment]
@martinrotter 

It's your mistake!!, you will need to remove nemo-autostart from the required components in the session files.

 https://github.com/linuxmint/Cinnamon/blob/d889044ff5381b43522a10c3dd2a79a1fd0f7dc9/files/usr/share/cinnamon-session/sessions/cinnamon.session

https://github.com/linuxmint/Cinnamon/blob/d889044ff5381b43522a10c3dd2a79a1fd0f7dc9/files/usr/share/cinnamon-session/sessions/cinnamon2d.session

**Comment by martinrotter** [comment]
@leigh123linux Thx, for hint. :)

**Comment by mtwebster** [comment]
The way we have dependencies set up is intentional, of course we know what's required where.  It's a conscious decision to make nemo required.  If you don't agree, that's fine, you're allowed, but it's our intention that nemo runs with Cinnamon, and the line between DE an file manager isn't distinct in this environment.  We're not going to limit ourselves in that way if we feel we can make a more integrated desktop as a result.

Distro maintainers are free to make whatever changes they want, including reducing this dependency if they wish.  We don't make Cinnamon for the entire Linux world, we make it for Linux Mint.

**Comment by martinrotter** [comment]
Okay, will try to propagate this issue to arch bug tracker/forums.
