### ISSUE TITLE
Cinnamon freeze on NAS I/O

### ISSUE THREAD

**Issue by shaygover** [linuxmint/cinnamon#4454]
Hi guys,

Recently I returned to Cinnamon as the common ~1 min freeze was fixed. 
Now I'm having an I/O related freeze.

I have a NAS server. Drives are mounted in fstab at startup.
Recently my server gives me slow response. Cinnamon freezes a lot as a result. I have no idea why cinnamon has to freeze because of this...

During the freeze I have sound and mouse. Ctrl+Alt+Esc doesn't help. After ~10 min I got the desktop back but the window manager has crashed (I had no window controls and panels). This time Ctrl+Alt+Esc did work.
During those ~10 min, top showed me that X and Cinnamon compete for 100% CPU time.

After the system is responsive again my desktop background slideshow stops and resets to Mint default background.

Syslog:
Jul 19 00:05:16 <PC Name> kernel: [92187.313305] usb 3-3: new high-speed USB device number 8 using xhci_hcd
Jul 19 00:05:16 <PC Name> kernel: [92187.441267] usb 3-3: New USB device found, idVendor=0424, idProduct=2514
Jul 19 00:05:16 <PC Name> kernel: [92187.441271] usb 3-3: New USB device strings: Mfr=0, Product=0, SerialNumber=0
Jul 19 00:05:16 <PC Name> kernel: [92187.442211] hub 3-3:1.0: USB hub found
Jul 19 00:05:16 <PC Name> kernel: [92187.442339] hub 3-3:1.0: 4 ports detected
Jul 19 00:05:17 <PC Name> kernel: [92187.712930] usb 3-3.4: new high-speed USB device number 9 using xhci_hcd
Jul 19 00:05:17 <PC Name> kernel: [92187.802041] usb 3-3.4: New USB device found, idVendor=04a9, idProduct=1909
Jul 19 00:05:17 <PC Name> kernel: [92187.802045] usb 3-3.4: New USB device strings: Mfr=1, Product=2, SerialNumber=0
Jul 19 00:05:17 <PC Name> kernel: [92187.802047] usb 3-3.4: Product: CanoScan
Jul 19 00:05:17 <PC Name> kernel: [92187.802048] usb 3-3.4: Manufacturer: Canon
Jul 19 00:05:17 <PC Name> colord: Device added: sysfs-Canon-CanoScan
Jul 19 00:05:20 <PC Name> kernel: [92191.541253] usb 5-1.4: new high-speed USB device number 7 using xhci_hcd
Jul 19 00:05:20 <PC Name> kernel: [92191.629283] usb 5-1.4: New USB device found, idVendor=0424, idProduct=2514
Jul 19 00:05:20 <PC Name> kernel: [92191.629286] usb 5-1.4: New USB device strings: Mfr=0, Product=0, SerialNumber=0
Jul 19 00:05:20 <PC Name> kernel: [92191.629731] hub 5-1.4:1.0: USB hub found
Jul 19 00:05:20 <PC Name> kernel: [92191.629856] hub 5-1.4:1.0: 4 ports detected
Jul 19 00:50:53 <PC Name> dhclient: DHCPREQUEST of <segment>.106 on br0 to <segment>.2 port 67 (xid=0x71690723)
Jul 19 00:50:53 <PC Name> dhclient: DHCPACK of <segment>.106 from <segment>.2
Jul 19 00:50:53 <PC Name> dhclient: bound to <segment>.106 -- renewal in 3392 seconds.
Jul 19 00:52:28 <PC Name> dbus[850]: [system] Activating service name='org.freedesktop.systemd1' (using servicehelper)
Jul 19 00:52:28 <PC Name> dbus[850]: [system] Successfully activated service 'org.freedesktop.systemd1'
Jul 19 00:52:44 <PC Name> dbus[850]: [system] Activating service name='org.freedesktop.systemd1' (using servicehelper)
Jul 19 00:52:44 <PC Name> dbus[850]: [system] Successfully activated service 'org.freedesktop.systemd1'
Jul 19 00:53:30 <PC Name> kernel: [95078.237260] atl1c 0000:06:00.0: atl1c: eth0 NIC Link is Down
Jul 19 00:53:30 <PC Name> kernel: [95078.237299] br0: port 1(eth0) entered disabled state
Jul 19 00:53:30 <PC Name> vmnetBridge: RTM_NEWLINK: name:eth0 index:2 flags:0x00001003
Jul 19 00:53:30 <PC Name> vmnetBridge: Removing interface eth0 index:2
Jul 19 00:53:30 <PC Name> vmnetBridge: RTM_NEWLINK: name:eth0 index:2 flags:0x00001003
Jul 19 00:53:30 <PC Name> vmnet-natd: RTM_NEWLINK: name:eth0 index:2 flags:0x00001003
Jul 19 00:53:30 <PC Name> kernel: [95078.443694] userif-4: sent link down event.
Jul 19 00:53:30 <PC Name> kernel: [95078.443698] userif-4: sent link up event.
Jul 19 00:53:30 <PC Name> vmnet-natd: message repeated 2 times: [ RTM_NEWLINK: name:eth0 index:2 flags:0x00001003]
Jul 19 00:53:31 <PC Name> vmnet-natd: RTM_NEWLINK: name:br0 index:3 flags:0x00001003
Jul 19 00:53:30 <PC Name> vmnetBridge: RTM_NEWLINK: name:eth0 index:2 flags:0x00001003
Jul 19 00:53:31 <PC Name> vmnetBridge: RTM_NEWLINK: name:br0 index:3 flags:0x00001003
Jul 19 00:53:31 <PC Name> vmnetBridge: Removing interface br0 index:3
Jul 19 00:53:31 <PC Name> kernel: [95079.235693] bridge-br0: disabling the bridge
Jul 19 00:53:31 <PC Name> vmnetBridge: Stopped bridge br0 to virtual network 0.
Jul 19 00:53:31 <PC Name> kernel: [95079.251526] bridge-br0: down
Jul 19 00:53:31 <PC Name> kernel: [95079.251532] bridge-br0: detached
Jul 19 00:53:31 <PC Name> kernel: [95079.435682] userif-4: sent link down event.
Jul 19 00:53:31 <PC Name> kernel: [95079.435686] userif-4: sent link up event.
Jul 19 00:53:33 <PC Name> vmnet-natd: RTM_NEWLINK: name:eth0 index:2 flags:0x00011043
Jul 19 00:53:33 <PC Name> vmnetBridge: RTM_NEWLINK: name:eth0 index:2 flags:0x00011043
Jul 19 00:53:33 <PC Name> vmnetBridge: Adding interface eth0 index:2
Jul 19 00:53:33 <PC Name> vmnetBridge: Started bridge eth0 to virtual network 0.
Jul 19 00:53:33 <PC Name> vmnetBridge: RTM_NEWLINK: name:eth0 index:2 flags:0x00011043
Jul 19 00:53:33 <PC Name> kernel: [95081.259178] atl1c 0000:06:00.0: atl1c: eth0 NIC Link is Up<1000 Mbps Full Duplex>
Jul 19 00:53:33 <PC Name> kernel: [95081.259196] br0: port 1(eth0) entered listening state
Jul 19 00:53:33 <PC Name> kernel: [95081.259233] br0: port 1(eth0) entered listening state
Jul 19 00:53:33 <PC Name> kernel: [95081.259481] /dev/vmnet: open called by PID 5725 (vmnet-bridge)
Jul 19 00:53:33 <PC Name> kernel: [95081.259489] /dev/vmnet: hub 0 does not exist, allocating memory.
Jul 19 00:53:33 <PC Name> kernel: [95081.259506] /dev/vmnet: port on hub 0 successfully opened
Jul 19 00:53:33 <PC Name> kernel: [95081.259517] bridge-eth0: up
Jul 19 00:53:33 <PC Name> kernel: [95081.259519] bridge-eth0: attached
Jul 19 00:53:33 <PC Name> kernel: [95081.459465] userif-4: sent link down event.
Jul 19 00:53:33 <PC Name> kernel: [95081.459468] userif-4: sent link up event.
Jul 19 00:53:35 <PC Name> kernel: [95083.259572] br0: port 1(eth0) entered learning state
Jul 19 00:53:36 <PC Name> dbus[850]: [system] Activating service name='org.freedesktop.systemd1' (using servicehelper)
Jul 19 00:53:36 <PC Name> dbus[850]: [system] Successfully activated service 'org.freedesktop.systemd1'
Jul 19 00:53:37 <PC Name> vmnetBridge: message repeated 4 times: [ RTM_NEWLINK: name:eth0 index:2 flags:0x00011043]
Jul 19 00:53:37 <PC Name> vmnetBridge: RTM_NEWLINK: name:br0 index:3 flags:0x00011043
Jul 19 00:53:37 <PC Name> vmnetBridge: Adding interface br0 index:3
Jul 19 00:53:37 <PC Name> vmnet-natd: message repeated 5 times: [ RTM_NEWLINK: name:eth0 index:2 flags:0x00011043]
Jul 19 00:53:37 <PC Name> vmnet-natd: RTM_NEWLINK: name:br0 index:3 flags:0x00011043
Jul 19 00:53:37 <PC Name> kernel: [95085.261625] br0: topology change detected, propagating
Jul 19 00:53:37 <PC Name> kernel: [95085.261634] br0: port 1(eth0) entered forwarding state
Jul 19 00:53:37 <PC Name> kernel: [95085.261807] bridge-eth0: disabling the bridge
Jul 19 00:53:37 <PC Name> vmnetBridge: Stopped bridge eth0 to virtual network 0.
Jul 19 00:53:37 <PC Name> vmnetBridge: Started bridge br0 to virtual network 0.
Jul 19 00:53:37 <PC Name> kernel: [95085.273621] bridge-eth0: down
Jul 19 00:53:37 <PC Name> kernel: [95085.273627] bridge-eth0: detached
Jul 19 00:53:37 <PC Name> kernel: [95085.273668] /dev/vmnet: open called by PID 5725 (vmnet-bridge)
Jul 19 00:53:37 <PC Name> kernel: [95085.273676] /dev/vmnet: hub 0 does not exist, allocating memory.
Jul 19 00:53:37 <PC Name> kernel: [95085.273690] /dev/vmnet: port on hub 0 successfully opened
Jul 19 00:53:37 <PC Name> kernel: [95085.273698] bridge-br0: up
Jul 19 00:53:37 <PC Name> kernel: [95085.273702] bridge-br0: attached
Jul 19 00:53:37 <PC Name> kernel: [95085.461779] userif-4: sent link down event.
Jul 19 00:53:37 <PC Name> kernel: [95085.461783] userif-4: sent link up event.
Jul 19 00:54:37 <PC Name> dbus[850]: [system] Activating service name='org.freedesktop.systemd1' (using servicehelper)
Jul 19 00:54:37 <PC Name> dbus[850]: [system] Successfully activated service 'org.freedesktop.systemd1'
Jul 19 00:55:10 <PC Name> acpid: client 19055[0:0] has disconnected
Jul 19 00:55:26 <PC Name> acpid: client connected from 19055[0:0]
Jul 19 00:55:26 <PC Name> acpid: 1 client rule loaded
Jul 19 00:55:45 <PC Name> acpid: client 19055[0:0] has disconnected
Jul 19 00:56:11 <PC Name> acpid: client connected from 19055[0:0]
Jul 19 00:56:11 <PC Name> acpid: 1 client rule loaded
Jul 19 00:56:41 <PC Name> acpid: client 19055[0:0] has disconnected
Jul 19 00:57:02 <PC Name> dbus[850]: [system] Activating service name='org.freedesktop.systemd1' (using servicehelper)
Jul 19 00:57:02 <PC Name> dbus[850]: [system] Successfully activated service 'org.freedesktop.systemd1'
Jul 19 00:57:03 <PC Name> acpid: client connected from 19055[0:0]
Jul 19 00:57:03 <PC Name> acpid: 1 client rule loaded
Jul 19 00:57:14 <PC Name> acpid: client 19055[0:0] has disconnected
Jul 19 00:57:41 <PC Name> sensord: Chip: acpitz-virtual-0
Jul 19 00:57:41 <PC Name> sensord: Adapter: Virtual device
Jul 19 00:57:41 <PC Name> sensord:   temp1: 27.8 C
Jul 19 00:57:41 <PC Name> sensord:   temp2: 29.8 C
Jul 19 00:57:41 <PC Name> sensord: Chip: coretemp-isa-0000
Jul 19 00:57:41 <PC Name> sensord: Adapter: ISA adapter
Jul 19 00:57:41 <PC Name> sensord:   Physical id 0: 51.0 C
Jul 19 00:57:41 <PC Name> sensord:   Core 0: 51.0 C
Jul 19 00:57:41 <PC Name> sensord:   Core 1: 49.0 C
Jul 19 00:57:41 <PC Name> sensord:   Core 2: 51.0 C
Jul 19 00:57:41 <PC Name> sensord:   Core 3: 50.0 C
Jul 19 00:57:48 <PC Name> acpid: client connected from 19055[0:0]
Jul 19 00:57:48 <PC Name> acpid: 1 client rule loaded
Jul 19 00:58:25 <PC Name> acpid: client 19055[0:0] has disconnected
Jul 19 00:58:27 <PC Name> acpid: client connected from 19055[0:0]
Jul 19 00:58:27 <PC Name> acpid: 1 client rule loaded
Jul 19 00:59:07 <PC Name> acpid: client connected from 19055[0:0]
Jul 19 00:59:07 <PC Name> acpid: 1 client rule loaded
Jul 19 00:59:13 <PC Name> acpid: client 19055[0:0] has disconnected
Jul 19 00:59:43 <PC Name> acpid: client connected from 19055[0:0]
Jul 19 00:59:43 <PC Name> acpid: 1 client rule loaded
Jul 19 01:00:12 <PC Name> postfix/qmgr[4360]: 4BE64200AD7: removed
Jul 19 01:00:18 <PC Name> acpid: client 19055[0:0] has disconnected
Jul 19 01:00:18 <PC Name> acpid: client connected from 19055[0:0]
Jul 19 01:00:18 <PC Name> acpid: 1 client rule loaded
Jul 19 01:00:30 <PC Name> acpid: client 19055[0:0] has disconnected
Jul 19 01:00:56 <PC Name> acpid: client connected from 19055[0:0]
Jul 19 01:00:56 <PC Name> acpid: 1 client rule loaded
Jul 19 01:01:03 <PC Name> acpid: client 19055[0:0] has disconnected
Jul 19 01:01:33 <PC Name> acpid: client connected from 19055[0:0]
Jul 19 01:01:33 <PC Name> acpid: 1 client rule loaded
Jul 19 01:02:35 <PC Name> cinnamon-session[19146]: WARNING: Application 'cinnamon.desktop' killed by signal 15
Jul 19 01:02:52 <PC Name> dbus[850]: [system] Activating service name='org.freedesktop.systemd1' (using servicehelper)
Jul 19 01:02:52 <PC Name> dbus[850]: [system] Successfully activated service 'org.freedesktop.systemd1'
Jul 19 01:03:03 <PC Name> kernel: [95650.761187] traps: cinnamon[3092] general protection ip:7f1347ec8213 sp:7ffc61c2b9d0 error:0 in libmuffin.so.0.0.0[7f1347e78000+b2000]
Jul 19 01:03:07 <PC Name> kernel: [95655.171645] traps: cinnamon[3105] general protection ip:7f7b905a3213 sp:7ffe8ab130c0 error:0 in libmuffin.so.0.0.0[7f7b90553000+b2000]
Jul 19 01:03:12 <PC Name> dbus[850]: [system] Activating service name='org.freedesktop.systemd1' (using servicehelper)
Jul 19 01:03:12 <PC Name> dbus[850]: [system] Successfully activated service 'org.freedesktop.systemd1'
Jul 19 01:03:44 <PC Name> acpid: client 19055[0:0] has disconnected
Jul 19 01:03:47 <PC Name> kernel: [95694.675379] traps: cinnamon[3312] general protection ip:7fdc7eb28213 sp:7ffd8ed8e750 error:0 in libmuffin.so.0.0.0[7fdc7ead8000+b2000]
Jul 19 01:03:51 <PC Name> kernel: [95699.107906] traps: cinnamon[3334] general protection ip:7f20542f8213 sp:7ffcffe7efe0 error:0 in libmuffin.so.0.0.0[7f20542a8000+b2000]
Jul 19 01:03:56 <PC Name> kernel: [95703.360961] traps: cinnamon[3349] general protection ip:7f84863c7213 sp:7ffea0474890 error:0 in libmuffin.so.0.0.0[7f8486377000+b2000]
Jul 19 01:04:19 <PC Name> kernel: [95726.476503] traps: cinnamon[3416] general protection ip:7f21392b8213 sp:7ffc6a0609e0 error:0 in libmuffin.so.0.0.0[7f2139268000+b2000]
Jul 19 01:04:21 <PC Name> acpid: client connected from 19055[0:0]
Jul 19 01:04:21 <PC Name> acpid: 1 client rule loaded
Jul 19 01:04:32 <PC Name> kernel: [95740.094981] traps: cinnamon[6198] general protection ip:7fb461d4d213 sp:7ffeaf061f60 error:0 in libmuffin.so.0.0.0[7fb461cfd000+b2000]
Jul 19 01:04:36 <PC Name> kernel: [95744.180584] traps: cinnamon[6192] general protection ip:7f9109e09213 sp:7ffda5770bd0 error:0 in libmuffin.so.0.0.0[7f9109db9000+b2000]
Jul 19 01:04:41 <PC Name> cinnamon-session[19146]: WARNING: App 'cinnamon.desktop' respawning too quickly
Jul 19 01:04:41 <PC Name> cinnamon-session[19146]: CRITICAL: We failed, but the fail whale is dead. Sorry....
Jul 19 01:04:41 <PC Name> kernel: [95748.405570] traps: cinnamon[6186] general protection ip:7f6057f48213 sp:7ffe378ca370 error:0 in libmuffin.so.0.0.0[7f6057ef8000+b2000]
Jul 19 01:04:41 <PC Name> cinnamon-session[19146]: WARNING: App 'cinnamon.desktop' respawning too quickly
Jul 19 01:05:08 <PC Name> vmnetBridge: RTM_NEWLINK: name:br0 index:3 flags:0x00011043
Jul 19 01:05:08 <PC Name> kernel: [95775.673899] device br0 left promiscuous mode
Jul 19 01:05:36 <PC Name> kernel: [95803.368789] vboxnetflt: 0 out of 23259968 packets were not sent (directed to host)
Jul 19 01:06:52 <PC Name> sudo: pam_ecryptfs: pam_sm_authenticate: /home/<USER> is already mounted
Jul 19 01:08:41 <PC Name> acpid: client 19055[0:0] has disconnected
Jul 19 01:08:45 <PC Name> acpid: client connected from 19055[0:0]
Jul 19 01:08:45 <PC Name> acpid: 1 client rule loaded
Jul 19 01:09:01 <PC Name> CRON[7698]: (root) CMD (  [ -x /usr/lib/php5/maxlifetime ] && [ -x /usr/lib/php5/sessionclean ] && [ -d /var/lib/php5 ] && /usr/lib/php5/sessionclean /var/lib/php5 $(/usr/lib/php5/maxlifetime))
Jul 19 01:09:17 <PC Name> acpid: client 19055[0:0] has disconnected
Jul 19 01:09:23 <PC Name> dbus[850]: [system] Activating service name='org.freedesktop.systemd1' (using servicehelper)
Jul 19 01:09:23 <PC Name> dbus[850]: [system] Successfully activated service 'org.freedesktop.systemd1'
Jul 19 01:09:24 <PC Name> acpid: client connected from 19055[0:0]
Jul 19 01:09:24 <PC Name> acpid: 1 client rule loaded
Jul 19 01:22:54 <PC Name> kernel: [96840.709983] vboxdrv: ffffffffc0000020 VMMR0.r0
Jul 19 01:22:54 <PC Name> kernel: [96840.811932] vboxdrv: ffffffffc00f7020 VBoxDDR0.r0
Jul 19 01:22:54 <PC Name> kernel: [96840.814799] vboxdrv: ffffffffc0115020 VBoxDD2R0.r0
Jul 19 01:22:54 <PC Name> kernel: [96841.064737] VBoxNetFlt: attached to 'br0' / 90:2b:34:33:32:08
Jul 19 01:22:54 <PC Name> kernel: [96841.080153] vboxdrv: ffffffffc0119020 VBoxEhciR0.r0
Jul 19 01:22:59 <PC Name> acpid: client 19055[0:0] has disconnected
Jul 19 01:23:03 <PC Name> kernel: [96849.968191] device br0 entered promiscuous mode
Jul 19 01:23:07 <PC Name> acpid: client connected from 19055[0:0]
Jul 19 01:23:07 <PC Name> acpid: 1 client rule loaded
Jul 19 01:27:41 <PC Name> sensord: Chip: acpitz-virtual-0
Jul 19 01:27:41 <PC Name> sensord: Adapter: Virtual device
Jul 19 01:27:41 <PC Name> sensord:   temp1: 27.8 C
Jul 19 01:27:41 <PC Name> sensord:   temp2: 29.8 C
Jul 19 01:27:41 <PC Name> sensord: Chip: coretemp-isa-0000
Jul 19 01:27:41 <PC Name> sensord: Adapter: ISA adapter
Jul 19 01:27:41 <PC Name> sensord:   Physical id 0: 53.0 C

X log looks mostly like that:
[ 96833.112](--) NVIDIA(GPU-0): DELL U2412M (DFP-4): connected
[ 96833.112](--) NVIDIA(GPU-0): DELL U2412M (DFP-4): Internal DisplayPort
[ 96833.112](--) NVIDIA(GPU-0): DELL U2412M (DFP-4): 960.0 MHz maximum pixel clock
[ 96833.112](--) NVIDIA(GPU-0): 
[ 96833.144](II) NVIDIA(0): Setting mode "DVI-I-1: nvidia-auto-select @1920x1200 +1920+0 {ViewPortIn=1920x1200, ViewPortOut=1920x1200+0+0}, DVI-D-0: nvidia-auto-select @1920x1200 +0+0 {ViewPortIn=1920x1200, ViewPortOut=1920x1200+0+0}, DP-1: nvidia-auto-select @1920x1200 +3840+0 {ViewPortIn=1920x1200, ViewPortOut=1920x1200+0+0}"
[ 96833.398](II) NVIDIA(0): Setting mode "DVI-I-1: nvidia-auto-select @1920x1200 +1920+0 {ViewPortIn=1920x1200, ViewPortOut=1920x1200+0+0}, DVI-D-0: nvidia-auto-select @1920x1200 +0+0 {ViewPortIn=1920x1200, ViewPortOut=1920x1200+0+0}, DP-1: nvidia-auto-select @1920x1200 +3840+0 {ViewPortIn=1920x1200, ViewPortOut=1920x1200+0+0}"
[ 96833.685](II) NVIDIA(0): Setting mode "DVI-I-1: nvidia-auto-select @1920x1200 +1920+0 {ViewPortIn=1920x1200, ViewPortOut=1920x1200+0+0}, DVI-D-0: nvidia-auto-select @1920x1200 +0+0 {ViewPortIn=1920x1200, ViewPortOut=1920x1200+0+0}, DP-1: nvidia-auto-select @1920x1200 +3840+0 {ViewPortIn=1920x1200, ViewPortOut=1920x1200+0+0}"
[ 96834.049](II) XKB: reuse xkmfile /var/lib/xkb/server-BE3DB48EC3A5F6218DA27D9FA5843CC3C9304645.xkm

Nothing on .xsession-errors. I've added LimitSessionOutput=false to the debug section

Any other log you need?

I think that I'll move to a different login manager, just to be on the safe side.

Thanks

**Comment by Vahan86** [comment]
https://github.com/linuxmint/Cinnamon/issues/4072

**Comment by Vahan86** [comment]
@icarter09, can we close this issue since there is no response from OP?
