### ISSUE TITLE
Fedora 22 backgrounds aren't showed in control center 

### ISSUE THREAD

**Issue by ledufff** [linuxmint/Cinnamon#4456]
![controlcenter](https://cloud.githubusercontent.com/assets/10855368/8764774/45977590-2db3-11e5-9546-c8de99fa9497.png)
F21 is blank too.

**Comment by mtwebster** [comment]
Are there any errors if you run `cinnamon-settings backgrounds` and try to change categories?

**Comment by ledufff** [comment]
Python module
/usr/lib/cinnamon-settings/cinnamon-settings.py:178: Warning: The property GtkEntry:primary-icon-stock is deprecated and shouldn't be used anymore. It will be removed in a future version.
  self.builder.add_from_file("/usr/lib/cinnamon-settings/cinnamon-settings.ui")
/usr/lib/cinnamon-settings/cinnamon-settings.py:178: Warning: The property GtkEntry:secondary-icon-stock is deprecated and shouldn't be used anymore. It will be removed in a future version.
  self.builder.add_from_file("/usr/lib/cinnamon-settings/cinnamon-settings.ui")
/usr/lib64/python2.7/site-packages/gi/overrides/__init__.py:313: Warning: The property GSettings:schema is deprecated and shouldn't be used anymore. It will be removed in a future version.
  return super_init_func(self, **new_kwargs)
Could not find bluetooth module; is the cinnamon-control-center package installed?
/usr/lib/cinnamon-settings/cinnamon-settings.py:423: Warning: The property GtkCellRendererPixbuf:follow-state is deprecated and shouldn't be used anymore. It will be removed in a future version.
  pixbuf_renderer.set_property("follow-state", True)
Loading Backgrounds module
/usr/lib64/python2.7/site-packages/gi/overrides/Gtk.py:567: Warning: The property GtkButton:use-stock is deprecated and shouldn't be used anymore. It will be removed in a future version.
  self.add_button(text, response)
/usr/lib64/python2.7/site-packages/gi/overrides/Gtk.py:567: Warning: The property GtkSettings:gtk-button-images is deprecated and shouldn't be used anymore. It will be removed in a future version.
  self.add_button(text, response)
/usr/lib/cinnamon-settings/bin/SettingsWidgets.py:47: Warning: The property GtkColorButton:color is deprecated and shouldn't be used anymore. It will be removed in a future version.
  widget.set_property(prop, key_to_prop(self[key]))
__init__ took 596.482 ms
Not trying to convert 
	
	 : not a recognized image file
Not trying to convert 
	
	 : not a recognized image file

___________________

Just some warnings.
Not trying to convert 
	
	 : not a recognized image file
Not trying to convert 
	
	 : not a recognized image file
these two are printed after click on F22 and F21 categories.

**Comment by vladimir-didenko** [comment]
Do Fedora wallpapers have xml format? I have similar issue with Gnome wallpapers - it is possible to use them but cinnamon-settings doesn't show it.

**Comment by ledufff** [comment]
It does, they're xml format.

**Comment by ledufff** [comment]
any news about this bug?

**Comment by Vahan86** [comment]
@ledufff, is this still an issue in Cinnamon 3.0?

**Comment by ledufff** [comment]
No, it's not, thanks.
