### ISSUE TITLE
Cinnamon lockscreen doesn't shows the wallpaper [Fedora]

### ISSUE THREAD

**Issue by ledufff** [linuxmint/Cinnamon#4457]
![2015-07-02-211214_1366x768_scrot](https://cloud.githubusercontent.com/assets/10855368/8764786/bfb68884-2db3-11e5-942f-43ef5f35a3b4.png)

**Comment by pirateblanc** [comment]
I am experiencing the same issue with 2.6.x. Is this the expected behavior? I was seeing the wallpaper on previous Cinnamon releases. Thanks in advance.

**Comment by Vahan86** [comment]
@ledufff, is this still an issue for you in Cinnamon 3.0.x?

**Comment by Vahan86** [comment]
@JosephMcc, can we close the issue?
