### ISSUE TITLE
Merge in systray-collapsible

### ISSUE THREAD

**Issue by marmistrz** [linuxmint/Cinnamon#4459]
Our Cinnamon tray lacks the possibility of collapsing. Maybe it'd be worth merging the code of this extension: https://github.com/Koutch/Cinnamon-systray-collapsible

It doesn't seem to receive updates anymore and since it's a fork, doesn't receive updates from upstream.

**Comment by DarekDeo** [comment]
Agree, panel lacks this feature.

**Comment by anandrkris** [comment]
Same as https://github.com/linuxmint/Cinnamon/issues/3129 ?

**Comment by JosephMcc** [comment]
Similar yes, but different enough to go ahead and leave open for now.

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html
