### ISSUE TITLE
Cinnamon leaks .serverauth.$$ files if is started manually.

### ISSUE THREAD

**Issue by ledufff** [linuxmint/Cinnamon#4460]
I don't know if Cinnamon supports start X at login (tty1), if not, sorry this is not a bug.

According with ArchLinux wiki the best way to start X at login is adding to your .bashrc file:
[[ -z $DISPLAY && $XDG_VTNR -eq 1 ]] && exec startx

and adding to your .xinitrc file:
exec cinnamon-session

It works excellent, with most DE. 

The bug here, is that startx script creates a .serverauth.$$ file and after logout it deletes it. When using Cinnamon it doesn't deletes that file, while using for example Xfce or Openbox it does.

**Comment by leigh123linux** [comment]
I don't consider it a cinnamon bug

https://bugzilla.redhat.com/show_bug.cgi?id=1238456

**Comment by dalcde** [comment]
I don't have the issue when starting manually with startx

**Comment by ledufff** [comment]
I made a fresh install I cannot reproduce this bug anymore, my old system seemed to be corrupted or something, thanks for your responses lads.
