### ISSUE TITLE
Cinnamon freezes

### ISSUE THREAD

**Issue by DarekDeo** [linuxmint/Cinnamon#4461]
I had today 2 freezes, first happend when I tried to plug in sdcard - I managed to fix it by hitting ctrl + alt + esc. Second freeze was some time later during ctrl + alt + esc. My whole desktop did freeze, mouse did not react and tty did not respond. I had to do ctrl + alt + esc second time because hotcorner to show all applications stopped working (this is very common issue for me since I've started using Mint 17).

Sys log as follows, anything else you need?:
http://wklej.org/id/1760856/

**Comment by mtwebster** [comment]
Do you have any sort of system monitor applet running on the panel?  If so, try removing it temporarily, restarting cinnamon, and seeing if this continues to occur.

**Comment by DarekDeo** [comment]
I have indeed "CPU Temperature Indicator". I'll remove it and see if freezes still happen. I'll respond in few days with results.

**Comment by KOLEGA007** [comment]
I had the same issue like half year before, for some unknown reason the solution was removing ~/.cinnamon folder (if I remember corectly) ... But it is painful solution ...

**Comment by lestcape** [comment]
Yes, i don't know why something in configuration is related with a problem like this, but this happened. @mtwebster what @KOLEGA007 is saying, is the same of what i tell you some time ago about the memory leak when i try to take an screen-shoot. Thats only occurs when something is using the hard disk. https://github.com/linuxmint/Cinnamon/issues/3657 The same in mint forum: http://forums.linuxmint.com/viewtopic.php?f=208&t=183250&sid=89a701f002cf688c2bbb36cc7410f6bc

**Comment by DarekDeo** [comment]
Had the freeze again while opening small image icon. First i tried ctrl alt esc, it did not help, then i moved to tty and tried to: pkill -HUP -f "cinnamon --replace" which worked under 2.4, but now it did not help. I had to reboot system (system was in black screen, i could only move mouse and heard playing music in background).

It happend somewhere near 15:00, at 15:09 i rebooted laptop:
http://wklej.org/id/1761272/

**Comment by DarekDeo** [comment]
After removing CPU Temperature Indicator system looks more stable. Althought I found out that it still freezes when opening images (using default viewer from Mint 17.2) from time to time.

**Comment by JosephMcc** [comment]
Please report freezing issues here: https://github.com/linuxmint/Cinnamon/issues/4072
