### ISSUE TITLE
Language switch to English after waking up from suspension.

### ISSUE THREAD

**Issue by stevendobay** [linuxmint/Cinnamon#4466]
After suspension, the login screen and the whole system uses English keyboard layout which makes it hard for non-english users to login. I need to click on the "Change user" button which uses the default keyboard layout(what I selected before). After the login the desktop still uses English even though I've removed it from the layouts' list.

**Comment by stevendobay** [comment]
This bug is inherited from gnome shell.

**Comment by stevendobay** [comment]
Manual fix: http://unix.stackexchange.com/questions/136382/mint-login-screen-wrong-keyboard-layout

**Comment by Vahan86** [comment]
@JosephMcc, I have tried to reproduce this issue and had no problem with login when using non-English layout. It works fine for me. Cinnamon version: 3.0.7

**Comment by stevendobay** [comment]
The bug wasn't always reproducible.

**Comment by JosephMcc** [comment]
@stevendobay Does it still happen for you. I can reopen this if it does.

**Comment by stevendobay** [comment]
I don't use cinnamon nowadays so I can't make you sure that the issue is still present.
