### ISSUE TITLE
Improve cinnamon power manager applet (battery)

### ISSUE THREAD

**Issue by fthuin** [linuxmint/Cinnamon#4467]
Hi ! I've got a laptop with 2 batteries. When I was on Ubuntu Unity, the applet showed the mean percentages of both, which is not the case on Cinnamon (you have to click on the applet to see the percentage of each battery)

Current behavior : Showing only the percentage of the first battery, 100% during few hours and then starts decreasing when second battery died.

Recommended behavior : Showing the average percentage of batteries when there are multiple laptop batteries.

**Comment by USER762341** [comment]
I too would like it if multiple batteries were averaged so the correct total percentage is displayed.

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html
