### ISSUE TITLE
Cinnamon still freezes as of 2.6.13

### ISSUE THREAD

**Issue by marmistrz** [linuxmint/Cinnamon#4469]
Since the metabug is all about 2.4.x, I'm opening a new issue.

In my panel there was the force quit applet right to the system tray.
In my system tray I have (left to right): Firetray | Redshift | Indicator-cpufreq | Workrave

I wanted to click the workrave icon in the system tray. My cursor took a path which came over the "force quit" applet. I did a click. Then the desktop hung. The background of the items in the system tray became black. I could move the mouse but nothing else happened. When the desktop was frozen, the force quit applet was still illuminated (i.e. indicated a mouse over itself)!

What's interesting, there is a spot, where the click is handled by the workrave applet in the system tray but the force quit applet is still lit up, indicating a mouse hover! (reproduced, but no freeze in this try)

Ctrl+alt+bksp, ctrl+alt+esc did nothing. Neither did `killall cinnamon`. Only restarting mdm let me use the system back. After restarting mdm, the desktop background was restored to the default one.

**Comment by lestcape** [comment]
@marmistrz I think you need take on account that never the cinnamon devs try to do the "perfect desktop". There are not a thing like that, if you allow use third-party extensions... The author of the third-party extensions can freeze cinnamon if he/she want. Not on cinnamon, this occurs in any desktop enviroment.

The cinnamon devs try to provide a good desktop free of bugs, but only if you used the standard extensions (thats that come with cinnamon). They can prevent some crashes, but not all possible crash and freeze. So, please what is really important is report problems when occurs without any third-party extensions. It is certainly known that obsolete third-party extensions can cause serious problems to cinnamon in some specific cases that are difficult or impossible to control.

**Comment by marmistrz** [comment]
@lestcape 
Firstly, forcequit is provided by Cinnamon, so it the system tray.

I'm providing the information about other applets to make it easier to reproduce. This may be well a bug in either Cinnamon, add-on or in both. If had suspected a bug in a third-party add-on, I'd have reported the bug there. Most probably it's something connected with something Cinnamon-stock, as the other applets are far away and weren't activated (and never caused a freeze)

The bug report should always be as complete as possible.

**Comment by lestcape** [comment]
Yes, but also the more clean as possible, with third-party, at less as i see, not many people will try to reproduce it. Not me at less. Good luck.

**Comment by marmistrz** [comment]
This is almost surely not connected with the add-ons. Another occurence: I booted the system and Cinnamon took very long to launch. After starting the wallpaper was reset. Experienced it twice.

This may be connected with #4333

**Comment by lestcape** [comment]
@marmistrz the problem, of some times (not always), Cinnamon took very long to launch or restart, also occurs to me, so, i think is not relate with KDE. I try to provide a log, but for do that, we need some special conditions, When i try it, i had not lucky to reproduce it. I don't know why or with is relate, but some time ago this was constantly, now only occurs some times. So, probably is related with the order or the time in with the cinnamon session will launch the subprocesses, but i don't sure.

**Comment by marmistrz** [comment]
@lestcape Can I get some log somehow if I experience it once again?

**Comment by lestcape** [comment]
@marmistrz is complex, you can read the @mtwebster comments here: https://github.com/linuxmint/Cinnamon/issues/4072#issuecomment-111390249, but i also speak more about this problem in the same thread. If you have time, please read all, to have a better idea of the problem.

Anyway thanks for try, i know is difficult get the log.

**Comment by ruthan** [comment]
I have fully update LMDE and i got today at least 6 freezes in Cinnamon, i dont have other GUI installed, i cant say that installation is 100 procent ok, but on same HW other distros and Windows are ok. 
  Nvidia 352 drivers, but i froze even in virtualbox and i with nouveau drivers.

**Comment by kremit** [comment]
I seem to now be experiencing a related issue in the latest Fedora 22 packages... 
```
# dnf list installed cinnamon\*
Last metadata expiration check performed 2:05:47 ago on Wed Sep 30 19:40:53 2015.
Installed Packages
cinnamon.x86_64                                                                                  2.6.13-10.fc22                                                         @System
cinnamon-control-center.x86_64                                                                   2.6.0-3.fc22                                                           @System
cinnamon-control-center-filesystem.x86_64                                                        2.6.0-3.fc22                                                           @System
cinnamon-desktop.x86_64                                                                          2.6.5-5.fc22                                                           @System
cinnamon-menus.x86_64                                                                            2.6.0-1.fc22                                                           @System
cinnamon-screensaver.x86_64                                                                      2.6.4-4.fc22                                                           @System
cinnamon-session.x86_64                                                                          2.6.3-2.fc22                                                           @System
cinnamon-settings-daemon.x86_64                                                                  2.6.3-5.fc22                                                           @System
cinnamon-translations.noarch                                                                     2.6.2-1.fc22                                                           @System
```
After the latest update, and about an hour's use, the desktop becomes increasingly sluggish. Leaving the system overnight (which is a desktop - monitors turn off after 10 mins but the system remains awake) causes the desktop to become very unresponsive. It takes 8-10 seconds for any click to take effect. Doing an Alt+F2 => "r" (restart Cinnamon) seems to restart just the cinnamon daemon and all is smooth again. I don't believe I have any non-standard extensions installed (list from the looking glass Extensions tab):
Menu
Panel launchers
Window list
Notifications
Network Manager
Removable drives
Keyboard
Sound
System Tray
User Applet
Calendar
Clock desklet

**Comment by JosephMcc** [comment]
Please report Cinnamon freezing problems on this issue: https://github.com/linuxmint/Cinnamon/issues/4072 after reading the first post by mtwebster.
