### ISSUE TITLE
Sonicwall vpn client hangs on 17.2

### ISSUE THREAD

**Issue by credzba** [linuxmint/Cinnamon#4471]
I am using the kde version of mint 17.1, also I use the cinnamon mint 17.1. 
sonicwall client works correctly.

I upgraded my kde machine to 17.2, and now the startct command hangs.
I booted with the cinnamon 17.2 iso install, and tried running the startct command from there, it also hung.

I can provide a client and vpn test site for you if needed.

**Comment by Vahan86** [comment]
@credzba, is this issue still relevant to Cinnamon 3.0?

**Comment by credzba** [comment]
I can't answer as I skipped to Linux mint 18 and it works properly on 18.

I don't think it was a cinnamon issue because even the client version
failed. I suspect it was a network stack issue.

**Comment by Vahan86** [comment]
Ok @credzba, thanks for reply, in this case can you please close this issue?
