### ISSUE TITLE
[Menu applet] Icons with same path/filename not reloaded

### ISSUE THREAD

**Issue by martinrotter** [linuxmint/Cinnamon#4472]
*How to reproduce:*
1. Open menu applet settings and select some image with path *x/y/z.png*. Menu now shows the image. Close settings.
2. Overwrite file *x/y/z.png* with another picture.
3. Open menu applet settings again and again navigate and select *x/y/z.png* as an image.

*Expected result:* After 3, new image (although from the same path/filename) is applied.
*Real result:* Nothing happens after 3, new image (with the same path/filename) is not selected.

It seems that if there is image from the same path/filename cached, then cache is not cleared and that image from cache is used, despite the path/filename may now in fact contain new image.

**Comment by pixunil** [comment]
Regression should be caused by commit https://github.com/linuxmint/Cinnamon/commit/51942292a87b585d76402f6d0b6b1bd8d2081d9a. Guess it was performance vs feature.

**Comment by martinrotter** [comment]
@pixunil It may be related to tha commit. But, when I explicitly select new icon through "Select Icon" dialog, I would expect icon to change itself. This is 100% bug. Performance optimizations should not introduce bugs.

**Comment by JosephMcc** [comment]
If this is a good feature vs performance design choice is debatable. However, since it behaves as the code intends for it to behave it is 100% NOT a bug.

**Comment by martinrotter** [comment]
Bug = A software bug is an error, flaw, failure, or fault in a computer program or system that causes it to produce an incorrect or unexpected result.

Thus, this IS a bug. Intentional bug.

**Comment by martinrotter** [comment]
:)
