### ISSUE TITLE
Applet development documentation?

### ISSUE THREAD

**Issue by niberius** [linuxmint/Cinnamon#4476]
Hello.
I want to create my own applet but I can't find normally fully documetation :( Does it exists anywhere? Need Cinnamon API description. For example: what the objects are Cinnamon.WindowTracker, global.window_manager, global.display.focus_window and what methods and properties it has? Few of them have method "connect". So, what argmunets can be passed to it? And where I can find it description and possible values? For exampe:

```javascript
let tracker = Cinnamon.WindowTracker.get_default();
tracker.connect('notify::focus-app', Lang.bind(this, this._doSome));
...
global.window_manager.connect('minimize', Lang.bind(this, this._doSome));
...
global.display.focus_window.connect('notify::title', Lang.bind(this, this._doSome));
```

What values can be passed to the frist argument (instead of 'notify::focus-app', 'minimize', 'notify::title') to method 'connect' of these objects? 
 
p.s. Sorry for my english.

**Comment by dalcde** [comment]
http://developer.linuxmint.com/

**Comment by niberius** [comment]
Thank you very much!
