### ISSUE TITLE
cannot start remote desktop sharing

### ISSUE THREAD

**Issue by brianjmurrell** [linuxmint/Cinnamon#4477]
When I try to turn the "OFF" to "ON" in the remote desktop sharing section of gnome-control-centre I get the following:

```
(gnome-control-center:27578): sharing-cc-panel-WARNING **: Failed to enable service vino-server: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.SettingsDaemon.Sharing was not provided by any .service files

(gnome-control-center:27578): sharing-cc-panel-WARNING **: couldn't list networks: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.SettingsDaemon.Sharing was not provided by any .service files

(gnome-control-center:27578): sharing-cc-panel-WARNING **: Failed to enable service vino-server: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.SettingsDaemon.Sharing was not provided by any .service files

(gnome-control-center:27578): sharing-cc-panel-WARNING **: couldn't list networks: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.SettingsDaemon.Sharing was not provided by any .service files
```

and then the ON/OFF switch goes back to OFF.

This is Cinnamon 2.6.x on Fedora 22.

**Comment by leigh123linux** [comment]
cinnamon-settings-daemon doesn't support sharing

https://git.gnome.org/browse/gnome-settings-daemon/commit/?id=0fb38bb7e4b2335c515c85d7510c30115db5b8ce

**Comment by brianjmurrell** [comment]
That's a pity.  Is it on the roadmap at least?

**Comment by brianjmurrell** [comment]
And in absence of that, what is the solution to desktop sharing for Cinnamon users?

**Comment by leigh123linux** [comment]
I'm using sftp, nfs and dlna (minidlna) here for sharing.

**Comment by leigh123linux** [comment]
@brianjmurrell Are you using F24? and want to test

https://bodhi.fedoraproject.org/updates/FEDORA-2016-ccbc9a6223

**Comment by JosephMcc** [comment]
I'm going to close this. Not sure why you would expect gnome-control-center to work in Cinnamon. Feel free to open a feature request for this if there isn't one already.
