### ISSUE TITLE
Files operations and Removable drives applet

### ISSUE THREAD

**Issue by bohelinux** [linuxmint/Cinnamon#4478]
now i report two issues of Cinnamon 2.6:

1."File operations are now queued and performed in sequence rather than in parallel." i think this feature is unreasonable, and i hope you will cancel it in the new versions.

2.when i umount a disk by clicking "Removable drives" applet in the tray, the menu of this applet won't disappear. i think it is a bug.

thanks!

**Comment by dalcde** [comment]
On Thu, Jul 30, 2015 at 05:59:33AM -0700, 薄荷开源网 wrote:
>1."File operations are now queued and performed in sequence rather than in parallel." i think this feature is unreasonable, and i hope you will cancel it in the new versions.
Why is it unreasonable? Bother to explain? Your hard disk is physically
incapable of reading two files at the same time. Performing file
operations in parallel can only possibly make things slower (unless the
two operations are on completely different disks. I'm not sure if Nemo
handles this properly).

>2.when i umount a disk by clicking "Removable drives" applet in the tray, the menu of this applet won't disappear. i think it is a bug.
Please open a different issue for a different bug

**Comment by brouillon** [comment]
It's sometimes annoying for me because renaming or deletion are also queued.
When i want to reorder some files / dirs, having to wait for a moving operation to finish before a renaming or a deletion was applied is not really usable.

For move operation i think it's a good idea, but do you think it's also good for others files operations ?

**Comment by JosephMcc** [comment]
The file operations are handled by nemo and belong here: https://github.com/linuxmint/nemo
As @dalcde  said please open one issue per bug.
