### ISSUE TITLE
Power applet shows full battery with 29% available

### ISSUE THREAD

**Issue by marmistrz** [linuxmint/Cinnamon#4481]
I have 29% of battery available (this is displayed by the applet itself). Still, the icon shows full battery.

**Comment by marmistrz** [comment]
And a screenshot: the icon in the popup is correct, the icon on the panel is wrong.
![screenshot from 2015-08-01 17 10 58](https://cloud.githubusercontent.com/assets/2914938/9022289/5e8edc2e-3870-11e5-9ce4-b99499ab8d43.png)

**Comment by rpbaptist** [comment]
Issue already reported: https://github.com/linuxmint/Cinnamon/issues/4329
