### ISSUE TITLE
add capability to switch back to last visited workspace

### ISSUE THREAD

**Issue by vt5491** [linuxmint/Cinnamon#4482]
Allow the ability and associated key binding to switch to the last visited workspace.  Dexpot window manager (windows) has this capability as the following screen print shows:

![dexpot_screen](https://cloud.githubusercontent.com/assets/8662470/9018170/1911ed38-3791-11e5-81e8-45ffe1f4f443.png)

keybinding in 'org.cinnamon.desktop.keybindings.wm' should be something like 'switch-to-last-workspace'

See also stack exchange entry http://unix.stackexchange.com/questions/218966/is-there-a-key-binding-to-switch-to-last-workspace-in-mint-17-2

**Comment by vt5491** [comment]
I just discovered that muffin the window manager for cinnamon.  Does this question belong under under muffin https://github.com/linuxmint/muffin/issues?

**Comment by vt5491** [comment]
Ok, after setting up a test image, looking at the code, and doing some research, I came up with a solution to fix this.  Note: this is currently just a workaround that involves manually editing a few files.  In order to submit this as an "official" fix I would need to:

1) add support for a new keyword "switch-to-workspace-last" so that it's visible in, at lest dconf-editor, if not in the Keyboard->Shortcuts gui in the control panel.
2) Write any unit tests (although, I don't see any uts for the files I touched under /tests).
3) Deal with creating an actual build of .deb of the cinnamon package (or is this not necessary to submit a fix).
4) Maybe get a little more feedback on if the way I did it is a good way to do it.

For now, I'm just going to stick with the workaround.  I'm actually just so happy that I have a workaround, and that it's just a couple of lines to implement.  This allows me I to get started using this right away (and boy is it great to have).

Anyway, in another comment, I will write a detailed posting about what exactly needs to be done as I propagate the fix into my production image.

**Comment by vt5491** [comment]
How to add hot-key support for "visit last workspace" in Cinnamon 17.2 (2.6.13+rafaela).

Overview:
-----------
We will hijack the functionality of a rarely used key binding of your choice (I used 'move-to-workspace-left') with the functionality to implement "move-to-workspace-last".  This involves adding a few lines to '/usr/share/cinnamon/js/ui/windowManger.js'.  We will need to add a new state variable 'global.screen.penultimate_workspace' to the 'global' js variable, and then utilize function 'global.screen.get_workspace_by_index(new_index)' to activate the 'last' workspace, and then call 'activate' to switch to it.

A good example of an existing file that does something simliar is the workspace-switcher applet, which is located at '/usr/share/cinnamon/applets/workspace-switcher@cinnamon.org/applet.js'.  You have to add this applet to the panel in order to see the file. 

Fortunately, this can be done entirely in the JavaScript portion of Cinnamon.

Detail
-------
### Code changes
Edit file '/usr/share/cinnamon/js/ui/windowManger.js' like so:

1) Init new global var 'screen.penultimate_workspace':
```
WindowManager.prototype = {                                                                   
          _init : function() {                                                                      
         this._cinnamonwm =  global.window_manager;  
         ...
         //fix add
        global.screen.penultimate_workspace = 1;
        //fix end

```

2) update the penultimate_workspace whenever someone manually switches to a workspace via the 'switch-to-workspace-<n>' key.  This is function _switchWorkspace in windowManager.js ;

```
   _switchWorkspace : function(cinnamonwm, from, to, direction) {
        //fix add
        global.screen.penultimate_workspace = from;
        //fix end
        if (!this._shouldAnimate()) {
            cinnamonwm.completed_switch_workspace();
            return;
        }
```

3) overlay your selected key-binding handler:
```
   _moveWindowToWorkspaceLeft : function(display, screen, window, binding) {
        //original code
        //this._shiftWindowToWorkspace(window, Meta.MotionDirection.LEFT);
        //end original code
        //fix add
        // get workspace object for 'last' workspace
        let metaWorkspace = global.screen.get_workspace_by_index(global.screen.penultimate_workspace);
        // save current workspace index into penultimate_workspace
        global.screen.penultimate_workspace = global.screen.get_active_workspace_index();

        // and switch to penultimate workspace
        metaWorkspace.activate(global.get_current_time() );
        //fix end
    },
```
### dconf-editor changes:
1) I chose to use "Ctrl-Alt-l" (that's lower case 'ell) as my 'switch-to-workspace-last' command.  Unfortunately, this was already in use as screen lock.
a) so goto control panel->Keyboard->Shortcuts->System->LockScreen and change to Ctrl-Alt-Shift-l (or whatever you want)

2) using dconf editor change 'move-to-workspace-left' to be '[<Control><Alt>l]
in schema org.cinnamon.desktop.keybindings.wm

### Activate changes
1) type "Ctrl-Alt-Esc" to refresh the cinnamon window manager.  This is somewhat like logging off and logging on, except all your windows and editing sessions will still be in effect.

That's it.  After doing this pressing "Ctrl-Alt-l" should take you the last visited window.

### Debuging help:
1) use Ctrl-Alt-Esc to refresh if window manager if you change a file.  Any changes you make will not take effect until you do this.

2) use global.log("vt: windowManger. blah");

to see debug mesages.  Do tail -f on ~/.cinnamon/glass.log to see the messages:

tail -f glass.log 

Note: you have to kill any prior tail -f sessions and start anew everytime you do a "Ctrl-Alt-Esc" to refresh the window manager.

**Comment by Vahan86** [comment]
@JosephMcc, can we mark this issue as a feature request?

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html
