### ISSUE TITLE
Screenshots size on high DPI

### ISSUE THREAD

**Issue by jaskmar** [linuxmint/Cinnamon#4484]
When I change interface scaling to high DPI mode, screenshots are two times smaller per each dimension (eg. 960x540 on FullHD display).

My Cinnamon version: 2.6.13+rafaela

**Comment by utack** [comment]
Should be fixed with a new version of the gnome screenshot tool (which FYI is not part of cinnamon), can you check?

**Comment by Vahan86** [comment]
@JosephMcc, can we close the issue since there is no response from OP for a long time?

**Comment by utack** [comment]
This has been fixed with a gnome-screenshot tool release quite a while back (March maybe), definitely fixed
