### ISSUE TITLE
Paste as Plaint Text missing?

### ISSUE THREAD

**Issue by crydalch** [linuxmint/Cinnamon#4485]
Can we get a Paste as Plain Text option in the RMB menu? It's so handy, and I'm almost positive it was there before. Or maybe I'm remembering incorrectly, from using other distro(s) at work?

Either way, it'd be great!

Thanks!

**Comment by tp0** [comment]
> Or maybe I'm remembering incorrectly, from using other distro(s) at work?

Chrome/Chromium?

**Comment by crydalch** [comment]
That must be it, you're right. but it'd be a good option, maybe as a plugin?

**Comment by tp0** [comment]
Maybe if there's someday going to be a built-in clipboard manager... and speaking of which, many of those make pastes plain text automatically or there is a specific setting for that. Try glipper (my favourite due to the simplicity), parcellite or clipit.

**Comment by crydalch** [comment]
Thanks for the suggestions, I'll give those a try.

Cheers!
