### ISSUE TITLE
Move windows from screen to screen with keys

### ISSUE THREAD

**Issue by Simplimus** [linuxmint/Cinnamon#4487]
I'm working on a two monitor system and love the feature that I can move windows around the desktop with the windows key and arrow keys. 
But it lacks the ability to move the window from one screen to the other. I always have to drag it to the desired screen with the mouse and can then use the keys again.

Situation: The active window is attached to the left side of a screen or in the upper left corner or in the lower left corner and there is at least one other screen to the left of it.

Key input: super key (windows key) + left arrow

Expected behavior: The active window moves to the screen which has the closest and longest border to the left of the former screen. Alternatively you could implement it to go to the screen where first the center is closest to the former screen and second the angle from the direct line going left is the smallest), otherwise go to the upper one. 
The window will then be attached to the right side of the new screen, or in the upper right corner or in the lower right corner, just as it was on the former screen.
The same action applies to the directions up, right and down respectively.

**Comment by Topperfalkon** [comment]
There's a separate keybinding for switching windows.

See Settings>Keyboard>Windows>Inter-monitor

I think it is set to Super-Shift-<direction> by default

**Comment by Simplimus** [comment]
So that's a Won't Fix? I don't find this solution intuitive.

**Comment by stefan123t** [comment]
@Simplimus, that is a solution already implemented. Just use Super (aka Windows) + Shift + Cursor to move between monitors. I.e. simply adding the Shift key to the shortcut will move between monitors, instead of snapping windows to the current screen.

**Comment by tp0** [comment]
@stefan123t, sufficient to me, but as I understand its not really what the OP wants.

**Comment by Topperfalkon** [comment]
@stefan123t I think OP's complaint is that snapping should switch through monitors automatically, rather than requiring a separate key combination. I see his point, but the provided solution is usable for me.

**Comment by JosephMcc** [comment]
This currently works just as it should. Using <Super+cursor> tiles within the current monitor. One press of <Super+Shift+cursor> will move it to another monitor where you can then continue to us <Super+cursor> to tile around that monitor.
