### ISSUE TITLE
Ensure Disable compositing for fullscreen windows is OFF by default

### ISSUE THREAD

**Issue by megz** [linuxmint/Cinnamon#4489]
As per the recent phoronix article where the FPS on games was the lowest of all on Cinnamon making it 'seem' the worst choice for transitioning gamers. Im assuming here (( I use cinnamon BECAUSE of its good game performance and this feature which sometimes helps when vsync doesn’t work on full screen )) it was that they/he did not undirect for fullscreen ( which wouldn’t surprise me as its phoronix and well ... ugg..

http://www.phoronix.com/scan.php?page=article&item=fedora-22-8way&num=1

Many users, especially new users who choose mint wont understand what this feature is or know it is there. It might be OFF by default, but I recently found on my installation it was ON by default.

thanks.

**Comment by dalcde** [comment]
afaik it is indeed off by default. What makes you think it is on by default on your installation? Could you have switched it manually but forgot?

**Comment by leigh123linux** [comment]
It's set to false for fedora (same as mint default).

```
$ gsettings get org.cinnamon.muffin unredirect-fullscreen-windows
false
```

**Comment by megz** [comment]
I installed cinnamon-mint-meta onto my mint xfce installation.

**Comment by dalcde** [comment]
Are you absolutely sure you haven't changed anything yourself? Can you reproduce the issue?

**Comment by lestcape** [comment]
I think, this can not be magic here, so there are not issue and about the result, well, that's an interesting result... a score of show, as is not provided any information of how the desktop was configured. Certainly, could be interesting make an internal test and then can be used to enhanced the cinnamon performance. Really, after the HPDI feature, i'm not all happy of how i was with the first versions of cinnamon (If we speak of performance), but is clear for me that any new feature need to impact the performance, and cinnamon in all releases have a lot of new features. So, if this result is true, i can understand why.

**Comment by leigh123linux** [comment]
IMO benchmark results from phronix are poorly  interpreted by Michael Larabel
Mate's poor results in Unique engine are more significant as are waylands complete failure .
