### ISSUE TITLE
Black screen on LUKS when Nvidia Closed driver is used.

### ISSUE THREAD

**Issue by megz** [linuxmint/Cinnamon#4490]
Using the LUKS/LVM disc encryption. I have been running the closed nvidia driver and as so far haven’t managed to remove the black screen on boot ( grub/2 update didn’t work ) This happens as soon as you put a closed nvidia driver on Linux Mint. I believe it may be an oldish issue but the 'fixes' don’t work. 

I don't even get the old password entry terminal ( instead of the nice logo on mint ) just a black screen. but ... it still works, I just type in the password and away we go.

FYI, today I mistyped my password and on the 2nd entry (correct that time ) it momentarily displayed the last half of my password on boot :/  clear to see on the screen and that was just before it switched to MDM.

not sure if this is a show stopper but its annoying as you cant reliably run the opensource nvidia driver and LUKS is really nice for protecting your laptop should you lose it.

**Comment by dalcde** [comment]
Not a cinnamon issue

**Comment by megz** [comment]
could you even care less ? at least move it to somewhere useful it is a Mint bug ? Im not an expert on this, Mint is my first goto with Linux..

try be helpful :/

**Comment by GLolol** [comment]
@megz Try filing a bug at https://bugs.launchpad.net/ubuntu/+source/nvidia-graphics-drivers/, which is the issue tracker for the Ubuntu's NVIDIA drivers.
