### ISSUE TITLE
Disable shortcut with Alt key

### ISSUE THREAD

**Issue by rand0m86** [linuxmint/Cinnamon#4493]
I'm using Intellij IDEA that has <kbd>Alt</kbd>+<kbd>Shift</kbd>+<kbd>LMB</kbd> shortcut to toggle selection or put new cursor (like <kbd>Ctrl</kbd> key in Sublime Text) but I can't found any associations with this keys.

I've only found `Settings > Windows > Behaviour > Special key to move and resize windows` set to `<Alt>` and disabled it but it stills doesn't lead to desired result.

**Comment by tp0** [comment]
I have Alt+mousewheel up/down in Sublime Text as as shortcut, it works, but Alt+Shift as the modifier for the same thing does not.

ps. Typo on title.
