### ISSUE TITLE
Feature request: Show desktop / minimize windows "toggle"

### ISSUE THREAD

**Issue by tp0** [linuxmint/Cinnamon#4495]
Feature request: changing the "Show desktop" behaviour so that it functions like a toggle that remembers its status. As in Unity*. In Unity it is possible to:
- minimize all windows and then restore all windows (like now in Cinnamon)
- minimize all except the active window while dragging it and then restore the other windows
- minimize all windows, open new window(s), minimize the new window(s) and then restore all at once

A video probably explains this the best:
- https://vid.me/UR6R
- mirror/download: https://dl.dropboxusercontent.com/u/13766493/shared/minimize-in-unity.webm

If it is hard to see the usefulness of the last one (3rd point): try it in Cinnamon. As soon as one opens a new window, the status of the "show desktop" sort of like resets and then one has to restore all other windows one by one, because pressing Super+D will only minimize and then restore the new (active) window.

(*) I don't know if it is actually Compiz or the Unity Plugin in it, as far as I remember it worked like this in Ubuntu already before Unity (Gnome 2.x).

**Comment by Vahan86** [comment]
@JosephMcc, can we mark this issue as a feature request?

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html
