### ISSUE TITLE
Various dropdown menus don't appear in dual monitor setup

### ISSUE THREAD

**Issue by irrenhaus3** [linuxmint/Cinnamon#4496]
Reporting from a fresh Mint 17.2 install with cinnamon 2.6.13, on a Lenovo Thinkpad with intel/nvidia graphics.  
Right-clicking on any panel applet (like Skype, KeePass and the Turpial twitter client) in the cinnamon panel does not spawn the context menu these applets normally display. The default cinnamon applets - slideshow, calendar, battery etc. - still work. It's worth noticing that dropdown menus within the affected applications also don't spawn.  
This seems to be a dual screen (and/or GTK?) issue since the menus display correctly when the external monitor is not plugged in to the notebook. Also, note that the notebook's display has a Full-HD resolution while the external monitor is set to a 4K resolution - it might be that this causes menu positions to be calculated incorrectly.  
If I missed anything, feel free to shout at me. :-)

**Comment by pwil3058** [comment]
I'm experiencing similar problems but they're intermittent and occur all over the workspace not just the panel.  There are two manifestations: 1. no response at all for a right button click and 2. the menu pops up bu only or a millisecond and then disappears.

As well as the right button problem, I have instances where clicking on a link in a Thunderbird mail window pops up a Firefox window but the URL field is blank.

It's highly likely that these two issues are related as they occur at the same time.  I.e. either Cinnamon is working normally or both of these problems are occuring.  Occurrence is relatively rare - probably less than 5% of the time.

**Comment by pwil3058** [comment]
I forgot to mention that Cinnamon seems to freeze if the network connection is disabled.

**Comment by stefan123t** [comment]
Dear irrenhaus3,
please check if #4645 is matching your problem.
Kind regards,
Stefan

**Comment by pwil3058** [comment]
Which problem?

**Comment by stefan123t** [comment]
@pwil3058 
I was referring to the following in the OPs question:
"<snip> It's worth noticing that dropdown menus within the affected applications also don't spawn.

This seems to be a dual screen (and/or GTK?) issue since the menus display correctly when the external monitor is not plugged in to the notebook. Also, note that the notebook's display has a Full-HD resolution while the external monitor is set to a 4K resolution - it might be that this causes menu positions to be calculated incorrectly."

**Comment by pwil3058** [comment]
OK, memory jogged. I don't think that my problems are related to #4645 
but, except for Cinnamon freezing when Internet is disconnected, I'm no 
longer experiencing the problems I described in #4496.

However, I was experiencing similar problems with the "Window List With 
App Grouping" panel app until I turned off "hover peek".  The exact 
symptoms were that when I put the mouse over an application's icon the 
list of windows for that application would pop up as expected but as 
soon as the mouse was moved to try and select one of them the list would 
flash a couple of times then disappear.

Hope this helps,
Peter

**Comment by irrenhaus3** [comment]
Hi stefan123t,
I can definitely confirm that all menus are in their proper place in a single-monitor setup, and it's believable that "not appearing" in this issue might actually mean "appear somewhere outside the screen boundaries", since menus in a dual-monitor setup are often displaced as shown in #4645.

**Comment by JosephMcc** [comment]
https://github.com/linuxmint/Cinnamon/issues/4894
