### ISSUE TITLE
Buggy nemo viewing

### ISSUE THREAD

**Issue by grenzor** [linuxmint/Cinnamon#4499]
So my  nemo setup was default with icon view. Although I did manually set some as list. Now when I did edit->preferences and set all to list+different zoom, they are now all list BUT 1 of the ones I manually list have non-updated settings (list+default zoom) only when I restore default settings visit the last folder i set the view for manually that settings for that stays the same.

kind of hard for me to explain without going into a bunch of repetitive detailing but hopefully you guys find this out.

**Comment by tp0** [comment]
More detailed explaining no matter how much depeating is better.

**Comment by JosephMcc** [comment]
If I follow your explanation this is actually the intended behaviour. Plus this isn't a Cinnamon issue.
