### ISSUE TITLE
The spacing in system tray grows too big

### ISSUE THREAD

**Issue by marmistrz** [linuxmint/Cinnamon#4502]
See the screenshots

Bad:
![bad](https://cloud.githubusercontent.com/assets/2914938/9205624/91d62984-4063-11e5-9109-45e159166a88.png)

Good:
![good](https://cloud.githubusercontent.com/assets/2914938/9205636/a782a582-4063-11e5-80f5-01307055a20a.png)

This fixes itself somehow but should not happen at all

**Comment by marmistrz** [comment]
It seems to happen when an applet is removed from the system tray. It is removed but the tray doesn't change its size.

**Comment by JosephMcc** [comment]
Do you still see this with Cinnamon 3.0?

**Comment by marmistrz** [comment]
I'll reopen this if I ever encounter it. Seems ok with Cinnamon 3.
