### ISSUE TITLE
Additional key mappings for chromebook-like computers

### ISSUE THREAD

**Issue by browcio** [linuxmint/cinnamon#4504]
Hello,

I have archlinux with Cinnamon installed on chromebook. Typical chromebook's keyboard looks like this: http://blog.laptopmag.com/wpress/wp-content/uploads/2014/02/chromebookkeyboard-670x361.jpg . My problem is that there are some keys missing, especially there are no delete, home, end, pg-up pg-down. I tried to map them with xmodmap etc. without success.

I would love to see in keyboard's settings, option to use for example SUPER+backspace as delete (key with magnifying glass is SUPER). SUPER+arrows as home, end, pg-up, pg-down would be also appreciated.

**Comment by Vahan86** [comment]
@JosephMcc, can we mark this issue as a feature request?

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
