### ISSUE TITLE
some mint/cinnamon config windows cannot be resized (bad behaviour on small screens)

### ISSUE THREAD

**Issue by ugobob99** [linuxmint/Cinnamon#4506]
Hi, I'd like to report two cases of windows which cannot be resized and when used on a smallish screen this becomes annoying - solving this will give cinnamon a even more user-friendly look.
1. The "software sources" window is 1173 pixel wide and cannot be resized: on both my pc (1152x864) and netbook (1024x600) the "x" to close the window is off the screen, so I need to move the window to close it.
2. The ldm configuration window is 568 pixel tall and can only be resized horizontally - so when I use it on my netbook (1024x600) panel the last line is hidden behind the lower panel, unless I set the panel to autohide.
Thanks.

**Comment by dalcde** [comment]
Not a Cinnamon issue
