### ISSUE TITLE
Icons gone in Expo

### ISSUE THREAD

**Issue by DarekDeo** [linuxmint/Cinnamon#4507]
While using few workspaces applications will loose their icons in Expo when this will occur:
1. Application is not installed through .deb, instead it just unpacked from archive
2. if 1 will occur application icon shows correctly in Expo till it is moved to another workspace

Check this out:
before moving program to another workspace:
![before_image](http://i.imgur.com/I8EywWZ.png)
after moving program to third workspace (notice that icon is now gone):
![after_image](http://i.imgur.com/syvriCX.png)

**Comment by JosephMcc** [comment]
Does this still happen in Cinnamon3.0?

**Comment by DarekDeo** [comment]
Sorry, can't test it, switched DE some time ago. It's easy to test, I've used AMD gpu if that's important.

**Comment by JosephMcc** [comment]
I can't reproduce it.
