### ISSUE TITLE
Unobvious how to configure workspaces

### ISSUE THREAD

**Issue by tripleee** [linuxmint/Cinnamon#4510]
I wanted to configure additional workspaces because the two I get out of the box is not sufficient for my working habits.

I struggled to find where to configure this, including, but not limited to,

 * Open the Workspaces settings panel.  Utterly suprised to not find a setting to control this behavior.
 * Configured the bottom panel to add the workspace switcher panel applet.  Again, utterly surprised to not be able to add workspaces there (tried right-clicking, alt-clicking, ctrl-clicking, etc).

Finally, Google revealed to me that there is a "hot corner" functionality which is disabled by default in Debian, and that enabling this would allow me to use Expo, where (somewhat unintuively) a big plus on the right hand side adds workspaces (where you would expect it to maybe add windows, if that made sense).  I later discovered that there is also a hotkey to bring up the Expo screen; but again, this detour is entirely unintuitive to me and arguably impossible to discover if you know what you are looking for, and not just playing around and/or clicking on everything in desperation.

At the very least, I think it should be simple and straightforward to expose this setting in the Workspace settings.  Exposing the Workspace settings when right-clicking on the workspace switcher applet would be a nice bonus.

(Sorry if this is a duplicate; I am obviously new to Cinnamon.  This is based on an install of the Debian 8.0 Live Cinnamon distro.)

**Comment by tripleee** [comment]
For what it's worth, https://www.google.com/search?q=cinnamon+number+of+workspaces gets me a large number of posts in various forums from people with the same question.  By rough estimate, dozens of people have asked and hundreds have participated in discussions, suggesting that easily hundreds and possibly thousands of users have been stymied just like myself.

**Comment by JosephMcc** [comment]
This could be improved. To be fair though, right clicking the workspace switcher applet shows an entry for "Manage workspaces".

**Comment by tripleee** [comment]
@JosephMcc That's not the case for me.  I only get the "Remove this applet" pop-up. For what it's worth, `/usr/share/cinnamon/applets/workspace-switcher@cinnamon.org/metadata.json` doesn't contain a version number but was installed by the Debian package `cinnamon-common` version 2.2.16-5.

**Comment by JosephMcc** [comment]
@tripleee Ah, I'm on 2.6 which does have this.

**Comment by xHN35RQ** [comment]
Try <kbd>Ctrl</kbd>-Alt-Up`

**Comment by JosephMcc** [comment]
In 2.8 right clicking the workspace applet now give options for Adding/Removing/Managing workspaces.

**Comment by tripleee** [comment]
I would still expect to find a way to at least inspect all the settings for this functionality in one place in the Workspaces settings panel.
