### ISSUE TITLE
Moving desktop icons leaves "shadow icons" in old location on Ubuntu 15.

### ISSUE THREAD

**Issue by exit0** [linuxmint/Cinnamon#4512]
Please see attached screenshot.  The icons to the right have just been moved.  The ones to the left are in the old locations, but aren't really there, in the sense that they can't be clicked on or moved.

Some supporting information:

xxxx@xxxx:~$ !inxi
inxi -Gxx 
Graphics:  Card-1: NVIDIA G92M [GeForce GTX 260M] bus-ID: 02:00.0 chip-ID: 10de:0618
           Card-2: NVIDIA G92M [GeForce GTX 260M] bus-ID: 03:00.0 chip-ID: 10de:0618
           Display Server: X.Org 1.17.1 drivers: nouveau (unloaded: fbdev,vesa) Resolution: 1920x1200@60.0hz
           GLX Renderer: Gallium 0.4 on NV92 GLX Version: 3.0 Mesa 10.5.2 Direct Rendering: Yes

xxxx@xxxx:~$ cat /etc/*ease
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=15.04
DISTRIB_CODENAME=vivid
DISTRIB_DESCRIPTION="Ubuntu 15.04"
NAME="Ubuntu"
VERSION="15.04 (Vivid Vervet)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 15.04"
VERSION_ID="15.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"

xxxx@xxxx:~$ dpkg -l libgtk2.0-0 libgtk-3-0
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                                            Version                      Architecture                 Description
+++-===============================================-============================-============================-===================================================================================================
ii  libgtk-3-0:amd64                                3.14.13-0ubuntu1             amd64                        GTK+ graphical user interface library
ii  libgtk2.0-0:amd64                               2.24.27-0ubuntu1             amd64                        GTK+ graphical user interface library

xxxx@xxxx:~# dpkg -l | grep -i clutter
ii  gir1.2-clutter-1.0                                   1.20.0-1ubuntu1                            amd64        GObject introspection data for the Clutter 1.0 library
ii  gir1.2-gtkclutter-1.0                                1.6.0-1                                    amd64        GObject introspection data for the GTK+ Clutter library
ii  gstreamer1.0-clutter                                 2.0.12-1build1                             amd64        Clutter PLugin for GStreamer 1.0
ii  libclutter-1.0-0:amd64                               1.20.0-1ubuntu1                            amd64        Open GL based interactive canvas library
ii  libclutter-1.0-common                                1.20.0-1ubuntu1                            all          Open GL based interactive canvas library (common files)
ii  libclutter-gst-2.0-0:amd64                           2.0.12-1build1                             amd64        Open GL based interactive canvas library GStreamer elements
ii  libclutter-gtk-1.0-0:amd64                           1.6.0-1                                    amd64        Open GL based interactive canvas library GTK+ widget

xxxx@xxxx:~# dpkg -l | grep -i cogl
ii  gir1.2-cogl-1.0                                      1.18.2-3                                   amd64        GObject introspection data for the Cogl 1.0 library
ii  gir1.2-coglpango-1.0                                 1.18.2-3                                   amd64        GObject introspection data for the CoglPango 1.0 library
ii  libcogl-common                                       1.18.2-3                                   all          Object oriented GL/GLES Abstraction/Utility Layer (common files)
ii  libcogl-pango20:amd64                                1.18.2-3                                   amd64        Object oriented GL/GLES Abstraction/Utility Layer
ii  libcogl-path20:amd64                                 1.18.2-3                                   amd64        Object oriented GL/GLES Abstraction/Utility Layer
ii  libcogl20:amd64                                      1.18.2-3                                   amd64        Object oriented GL/GLES Abstraction/Utility Layer
![screenshot from 2015-08-13 16 38 15](https://cloud.githubusercontent.com/assets/6293498/9263554/77b3824e-41db-11e5-99fe-2058c78957ff.png)

**Comment by exit0** [comment]
Running "cinnamon --replace" from the Alt+F2 box restarts Cinnamon, but does not rectify the problem.

**Comment by jmgomezpoveda** [comment]
I have had the same issue intermittently for quite some time; Maybe 1 or 2 years. Sometimes it's fine, sometimes icons are duplicated. Also using Ubuntu with Cinnamon.

Another user is reporting this issue in the Ubuntu forums: http://ubuntuforums.org/showthread.php?t=2286043&p=13340670

**Comment by exit0** [comment]
One way I can definitively recreate this problem is by invoking "nautilus" from the Alt+F2 box.

Subsequently, issuing "pkill nautilus" from the Alt+F2 box resolves the issue.

**Comment by exit0** [comment]
^ also true, predictably, when the commands are issued from gnome-terminal.

**Comment by jmgomezpoveda** [comment]
That solves the issue for me as well. So, may the real issue be both nautilus and nemo showing desktop icons at the same time?

**Comment by exit0** [comment]
It appears that issuing the following:

gsettings set org.gnome.desktop.background show-desktop-icons false

Permanently alleviates the issue for me.

**Comment by jmgomezpoveda** [comment]
Ok, so it appears to be another instance of the Cinnamon settings not being optimised for Ubuntu users, like in https://github.com/linuxmint/Cinnamon/issues/4060#issuecomment-109432926.

I wonder if it would be possible to create a cinnamon-ubuntu package that collected and set automatically those settings, or having Cinnamon auto-detect if it's being run within Mint or Ubuntu (or better yet, check if Nautilus or Systemd are present and set the corresponding settings).

**Comment by leycec** [comment]
@exit0 You win the Internet tubes. Your astute fix appears to have obviated this issue for me as well.

@jmgomezpoveda I completely agree with the auto-detection suggestion. The Cinnamon experience under Ubuntu is... well, to put it charitably, **not the best.** It _sort-of_ works, until it doesn't. Auto-detection of running processes (e.g., `nautilus`, `systemd`) and establishment of corresponding sane defaults would seem to be the ideal long-term fix.

In any case, thanks, all! :deciduous_tree:

**Comment by julenpardo** [comment]
I was getting desperate with the duplicate icons, thanks a lot for that fix @exit0

**Comment by pjsanfil** [comment]
Removing Nautilus fixes this issue for me in Ubuntu 15.10.

**Comment by JosephMcc** [comment]
Cinnamon is primarily developed by and for Mint users and devs. Our priority is making sure things work properly for Mint users. We can't really test it on every distro out there. That being said, we welcome patches, PR's, etc. from others. The maintainers/users from Arch and Fedora are quite active in this regard. For some reason we don't see this from any sort of ubuntu maintainer.

**Comment by anpel** [comment]
@exit0 This worked for me too, cinnamon 3.4 on ubuntu 16.04.
