### ISSUE TITLE
Cinnamon  2.6.13:rafaela crashes on login, after almost every install, randomly throughout session - Segfault

### ISSUE THREAD

**Issue by xHN35RQ** [linuxmint/Cinnamon#4514]
I'm getting Cinnamon (2.6.13:rafaela) crashes and falls-back to basic version on these 3 conditions:

* When I login
* After almost every installation (Update Manager, Synaptic, apt-get install)
* Randomly during session, sometimes when launching new app, switching desktops, Alt-Tabbing, minimizing windows, normal usage.

I used to have `cinnamon-slideshow` running to change my desktop background, and Cinnamon was crashing almost every 2-3 minutes. So I disabled it, and immediately had much less crashing.

Upon crash, I can get Cinnamon to relaunch most times, however sometimes it refuses to relaunch for some minutes, insisting on falling back to basic version. So I wait for 2-3 minutes, and usually can get Cinnamon to launch within 1-3 tries of launching.

Looking at syslog I see it's segfaulting. Here's some examples:

    Aug 15 00:26:45 4t34ec3z kernel: [96872.170891] cinnamon[22887]: segfault at 600000014 ip 00007f2a81aa58c2 sp 00007ffc710c0200 error 4 in libc-2.19.so[7f2a81a27000+1bb000]

    Aug 15 00:30:54 4t34ec3z kernel: [97121.270956] cinnamon[24122]: segfault at 10 ip 00007f5125c00f31 sp 00007ffd838332e0 error 6 in libc-2.19.so[7f5125b81000+1bb000]

    Aug 15 01:48:06 4t34ec3z kernel: [101755.957503] cinnamon[28026]: segfault at 1200000013 ip 00007f7490e05ce7 sp 00007ffd5d3f6ed0 error 4 in libc-2.19.so[7f7490d86000+1bb000]

Also, I see for every Cinnamon segfault, it show an accompanying `pool` segfault. For example this segfault preceded the first `cinnamon` segfault shown above:

    Aug 15 00:26:43 4t34ec3z kernel: [96870.600865] pool[22876]: segfault at 300000012 ip 00007f7d328128c2 sp 00007f7d0497d4a0 error 4 in libc-2.19.so[7f7d32794000+1bb000]

Thanks for your help!

**Comment by kaefert** [comment]
Hey there! I just swapped out the Nvidia G-Force GT 730 card that came with my new PC for my old Grafic card (RV620 PRO [Radeon HD 3470]) because the Nvidia was unstable. See also these posts for details:
http://forums.linuxmint.com/viewtopic.php?f=59&t=206140
https://devtalk.nvidia.com/default/topic/881248/linux/geforce-gt-730-random-colorful-x-crashes/

Now with the Radeon HD 3470 everything looks fine up to the login screen, but I can't get cinnamon to start in normal mode, it always says imediatly that it crashed, and gives me lines like these in dmesg (which made me find your post here):
```
[   25.111102] cinnamon[3298]: segfault at 0 ip 00007f549f76927d sp 00007ffcf1257188 error 4 in libc-2.19.so[7f549f6c8000+1bb000]
[   25.248136] cinnamon[3349]: segfault at 0 ip 00007fefa49a727d sp 00007fff32df3c58 error 4 in libc-2.19.so[7fefa4906000+1bb000]
[   27.507525] cinnamon[3415]: segfault at 0 ip 00007fee98f5527d sp 00007fff6aef2a78 error 4 in libc-2.19.so[7fee98eb4000+1bb000]
[   29.003205] cinnamon[3449]: segfault at 0 ip 00007fd38a67827d sp 00007ffe4b4e9e48 error 4 in libc-2.19.so[7fd38a5d7000+1bb000]
[   30.370749] cinnamon[3489]: segfault at 0 ip 00007f12e35cc27d sp 00007ffd8a2acc38 error 4 in libc-2.19.so[7f12e352b000+1bb000]
[   31.657890] cinnamon[3525]: segfault at 0 ip 00007fd9e020627d sp 00007ffee565f428 error 4 in libc-2.19.so[7fd9e0165000+1bb000]
```

**Comment by xHN35RQ** [comment]
not using cinnamon anymore, closing because this might have been caused by me using bleeding edge gfx binaries.
