### ISSUE TITLE
Intelligent panel: doesn't hide in multi-monitor setup if other monitor has focus

### ISSUE THREAD

**Issue by tp0** [linuxmint/Cinnamon#4515]
Repro:
- requirement: (at least) 2 monitors
- open some full screen mode capable application on monitor 2 and active the full screen mode
- focus (click) anything on monitor 1

**Result:** panel becomes visible on monitor 2, when at least I would expect panel to stay hidden.

This behaviour seems to match the behaviour when there are just windowed applications, but imho when an application is in fullscreen, there is no reason to expect that the user wants to see the panel at all. Most obvious real life use case: playing video in the other monitor in full screen, while working on something else on main monitor.

Reproduced at least on: SMPlayer, mpv, VLC, Chrome/Chromium (affects also Flash and HTML5 videos)

Cinnamon 2.6.13

**Comment by JosephMcc** [comment]
There have been improvements for fullscreen handling for the upcoming Cinnamon3.0 and I can no longer reproduce this on git master.
