### ISSUE TITLE
Battery Meter sometimes glitches.

### ISSUE THREAD

**Issue by SethDusek** [linuxmint/Cinnamon#4516]
So, this doesn't always happen, but the little lightning thing on the battery meter dissapears, hence I have to click on it to check whether it is charging or not.

Here is a screenshot:
See how it's charging but theres no lightning thingy? http://i.imgur.com/AgqxGD9.png

**Comment by pfaivre** [comment]
I have this issue as well.
The power applet sometimes shows the "battery-full" icon even if the battery is not charged.

Unfortunately it seems pretty random. The problem can persist a few seconds as well as a few minutes. When it is happening, the applet switches between the "battery-full-charging" and "battery-full-charged" icons.

Linux Mint 17.2
Cinnamon 2.6.13

**Comment by pixunil** [comment]
#4329
Can you please check with git master? You can use this command to patch the power applet:
```
$ sudo wget -O /usr/share/cinnamon/applets/power@cinnamon.org/applet.js https://raw.githubusercontent.com/linuxmint/Cinnamon/master/files/usr/share/cinnamon/applets/power%40cinnamon.org/applet.js
```

**Comment by pfaivre** [comment]
Ouch! There is no icon anymore on my configuration with this patch.
![power-applet-issue](https://cloud.githubusercontent.com/assets/6364094/9414362/22bacd70-4838-11e5-8721-e5ce8f791e5b.png)

But yes this seems to be the same issue as #4329

**Comment by pixunil** [comment]
Yep, ouch. No idea in my head why that happened, also the text is really wrong.
Do you have errors in `~/.xsesson-errors`, `~/.cinnamon/glass.log` or `~/.cinnamon/glass.log.last`?
Please post them external, e.g. GitHub Gist.

**Comment by pfaivre** [comment]
Hmm okay in `~/.xsession-errors ` I spotted this:
```
JS ERROR: Error: Expected type utf8 for Argument 'str' but got type 'number'
```
There is something going on in lines 121, 97 and 429. 

logs at https://gist.github.com/pfaivre/d60b6784d7c6e68f1e31

PS: I tried to downgrade to power applet to 2.4.0 and it seems to work fine. But I didn't tested for a long time though.

**Comment by pixunil** [comment]
Oh, I missed commit 2c5b9d5aa3381a1c2e31bdf5f1ee11a7e3574179, which needs a newer version of `cinnamon-settings-daemon`, which results in a very broken power applet.
When you have the chance, you can try [nightly builds](https://github.com/linuxmint/Cinnamon/wiki/Trying-out-the-latest-Cinnamon-without-building-it.) (to have the added vendor labels), or you can use this command (which gets the fixed power applet at the point ef60793faaf022c6189bbaaa8c13b3be74711e78):
```
$ sudo wget -O /usr/share/cinnamon/applets/power@cinnamon.org/applet.js https://raw.githubusercontent.com/linuxmint/Cinnamon/ef60793faaf022c6189bbaaa8c13b3be74711e78/files/usr/share/cinnamon/applets/power@cinnamon.org/applet.js
```

**Comment by pfaivre** [comment]
Oh okay.
After installed cinnamon nightly 2.6.13-201508220400 and rebooted, I performed a charging/discharging test from 8% to 80%.

It works perfectly fine, without the glitches:
* < 10% : `battery-caution`
* between 10% and 30% : `battery-low`
* between 30% and 60% : `battery-good`
* > 60% : `battery-full`

Awsome! It works for me.
Thanks a lot.

**Comment by pixunil** [comment]
@SethDusek, as you original created this thread, can you still reproduce? Else, please close this.

**Comment by SethDusek** [comment]
http://i.imgur.com/wDAVo2e.png

It is charging but the lightning thing dissapears

**Comment by pixunil** [comment]
Are you sure you updated? (See above for explanations)

**Comment by SethDusek** [comment]
Hm right now it seems to be fixed, but I'd like to take some time to test so don't close yet

**Comment by SethDusek** [comment]
After about 10 days of testing in which my laptop has been unplugged, replugged during normal use, this update seems to be working

**Comment by bmbariah** [comment]
@SethDusek Which theme are you using on your mint to have it appear like that image?

**Comment by SethDusek** [comment]
@bmbariah The window borders are numix-osx and the theme is mona 2.0
