### ISSUE TITLE
Power manager: battery charge indicator icon wrong but percentage correct (2.6.13)

### ISSUE THREAD

**Issue by wutr** [linuxmint/Cinnamon#4519]
The battery charge indicator shows an incorrect level (full) compared to the actual charge percentage. It occasionally changes to the correct level, but soon reverts back to the wrong icon.

See screenshot:
![cinnamon_power_battery_indicator_bug](https://cloud.githubusercontent.com/assets/13820537/9293816/1b29d3c2-4431-11e5-8293-1b0ba428ef12.png)

**Comment by clefebvre** [comment]
This is fixed on master.

**Comment by rpbaptist** [comment]
@clefebvre Actually it is not. I am using the master branch right now and looking at 64% with a full icon.

**Comment by banstola** [comment]
I have Mint Rafaela with the same issue on Cinnamon Desktop.
