### ISSUE TITLE
Launching nautilus changes desktop background

### ISSUE THREAD

**Issue by ch3pjw** [linuxmint/Cinnamon#4521]
Impact:
Visual appearance and behaviour of desktop are changed unintentionally.

Reproduction:
Change desktop background to non-default
Launch nautilus file browser (e.g. from run dialogue)
Observe desktop changes to the default LinuxMint17.2 wallpaper.
Observe that I can now right-click and, e.g., make a new folder, which was disabled previously.

Notes:
It looks like the correct wallpaper is still there underneath when I log out.
After log out, logging in again yields the correct wallpaper again, until nautilus is re-launched.
There are not any obvious new processes that I can see that nautilus might have launched.

Nautilus 3.10.1 installed from the normal mint repos.
Mint 17.2 64-bit
Cinnamon 2.6.13

**Comment by leigh123linux** [comment]
If desktop icons are active in nautilus it will take over the desktop when started, you need to disable them using dconf-editor or run this as standard user

```
gsettings set org.gnome.desktop.background show-desktop-icons false
```

**Comment by ch3pjw** [comment]
Fab, thanks, that worked a treat. Whilst this isn't a bug, per-se, is interaction with nautilus in this manner unsupported as far as mint/cinnamon is concerned?

**Comment by kurdtpage** [comment]
FYI this bug is still active using the following versions:
Linux Mint 18.1
Nautilus 3.14.3
XFCE 4.12

The "fix" as suggested by @leigh123linux fixes the bug and the desktop is restored

**Comment by leigh123linux** [comment]
@kurdtpage  I wouldn't describe this as a bug!
It's a choice to pollute your system with nautilus and use it.
