### ISSUE TITLE
Cinnamon settings segfaults when trying to open date/time.

### ISSUE THREAD

**Issue by Protryon** [linuxmint/cinnamon#4522]
I'm trying to edit my date/time settings as they got offset, after I reinstalled windows on another hard drive(probably unrelated), by 6 hours back.

python2 /usr/lib/cinnamon-settings/cinnamon-settings.py
**init** took 178.578 ms
Loading Calendar module

(cinnamon-settings.py:8356): datetime-cc-panel-WARNING **: could not get proxy for DateTimeMechanism: Error calling StartServiceByName for org.cinnamon.SettingsDaemon.DateTimeMechanism: GDBus.Error:org.freedesktop.DBus.Error.Spawn.ExecFailed: Failed to execute program /usr/lib/dbus-1.0/dbus-daemon-launch-helper: Success

(cinnamon-settings.py:8356): GLib-GIO-CRITICAL **: g_dbus_proxy_call_sync_internal: assertion 'G_IS_DBUS_PROXY (proxy)' failed
Segmentation fault

I am of course, in the latest cinnamon in the Mint repo.

**Comment by Vahan86** [comment]
@Protryon, does this issue still occur in Cinnamon 3.0?

**Comment by Protryon** [comment]
It happened in the latest versions as late as about February/March 2016 (I got a new WM).

**Comment by icarter09** [comment]
@Protryon are you still experiencing this issue?

**Comment by Vahan86** [comment]
@icarter09, can we close the issue since there is no response from OP?
