### ISSUE TITLE
Panel disable when focus on fullscreen terminal

### ISSUE THREAD

**Issue by adam900710** [linuxmint/Cinnamon#4523]
Like the attached two pictures.

If current focus is on a fullscreen terminal (In my case, gnome-terminal using F11 to fullscreen it, not normal maximum windows), the panel just disappears.
And if I change focus to a normal, non-fullscreen terminal, the panel appear again.

IIRC, for MATE or xfce4, such problem doesn't happen.
So it should be a cinnamon bug.

Version:
cinnamon 2.6.13
distribution: Archlinux
![2015-08-18-145236_1440x900_scrot](https://cloud.githubusercontent.com/assets/460269/9324045/37e516c8-45b9-11e5-81d7-626f1da9968c.png)
![2015-08-18-145233_1440x900_scrot](https://cloud.githubusercontent.com/assets/460269/9324046/37e52c8a-45b9-11e5-9225-6dd71599735a.png)

**Comment by dalcde** [comment]
It is intended behaviour. Imagine it is a full screen movie, instead of a terminal. You probably won't want your panel to be there to obstruct the top/bottom of the movie.

**Comment by adam900710** [comment]
No, for your full-screen movie player case, that will not affect the user, as the player should be above panel layer, so user shouldn't notice the panel.

As I mentioned, for xfce4, the panel will be just below the full-screen terminal layer, and don't disappear.

So IMHO, the case shouldn't be closed.

Thanks.

**Comment by JosephMcc** [comment]
Just because another DE handles it one way and Cinnamon another doesn't make it a bug. I assume in your use case you want to be able to see the panel when you have the transparent full screen terminal over it?

**Comment by adam900710** [comment]
Yes, I just want to see the panel using a transparent full-screen terminal.
