### ISSUE TITLE
Desktop and windows sometimes don't appear on login

### ISSUE THREAD

**Issue by rmwiseman** [linuxmint/Cinnamon#4524]
Sometimes (maybe one time in 20 or so) when I log in, the screen blanks as normal after log-in, the mouse pointer appears as normal, moves around a bit as normal (I've got two monitors, and it seems to appear on monitor 1, move to the centre of the overall monitor area and then go to the centre of monitor 1) and then ... nothing.  It just sits there.  Usually, the desktop and windows kind of zoom into view, but on these less-common occasions, all I have is the black screen and the mouse pointer (which is perfectly responsive to movement).

In response to another bug I've reported, I installed sshd, and I can log into the machine remotely when it's stuck like this.  I didn't really know what to do once in, though, so I captured the running processes in case they provide any clues as to what's going on.  I tried "kill -HUP" on the cinnamon processes I could see, but that had no obvious effect except that the processes were no longer around!

Any suggestions would be appreciated!

I have tried Ctrl+Alt+Esc and Ctrl+Alt+Backspace, by the way, but I guess they're not active at the point where it gets stuck.

Oh, and I'm on 17.2 Rafaela, if that helps.  I never experienced this problem on 17.1, and I was using that daily for a few months.

**Comment by rmwiseman** [comment]
It didn't do it for a while so I thought maybe it was fixed, and then it happened again yesterday morning.

**Comment by Vahan86** [comment]
@rmwiseman, is this still an issue for you in Cinnamon 3.0.x (Mint 18)?

**Comment by rmwiseman** [comment]
No, I've not experienced this in quite a while thanks.  Please feel free to close the issue.
