### ISSUE TITLE
Cinnamon graphical performance

### ISSUE THREAD

**Issue by presianbg** [linuxmint/Cinnamon#4525]
Dear All,

First I need to say how much I love and respect your work, Cinnamon is great DE.

I'm using ASUS G551JM with Optimus technology (bumblebee)  and Fedora 22 (all up to date) and just found that Cinnamon graphical performance is a kind behind from MATE. Here is what I'm talking about:

1. Benchmark with ```vblank_mode=0 primusrun glxspheres64```.
 Cinnamon:
![cinnamon-performance](https://cloud.githubusercontent.com/assets/2163486/9328453/6ebbed0a-45b1-11e5-9765-33b375f0249f.png)

 MATE:
![mate-performance](https://cloud.githubusercontent.com/assets/2163486/9328455/7a962e4c-45b1-11e5-9ac1-e300456277e0.png)

2. Benchmarking with Dota 2 Reborn:
Cinnamon results in 40-60 fps (fps drops and laggs) with medium graphical settings.
MATE results in constant 60 fps (much smoother than Cinnamon) with maxed graphical settings + weather effects. 

So there must be a bottleneck (probably I'm wrong) in Cinnamon + bumblebee. I will be happy to assist and give more info.

Best Regards, 
presianbg

**Comment by mortan** [comment]
Try disabling compositing for full screen apps!

**Comment by presianbg** [comment]
@mortan I will test later and give feedback.

**Comment by leigh123linux** [comment]
It might be worth trying another benchmark (glxspheres isn't benchmark) as cinnamon might have a issue with Dota.

http://unigine.com/en_us/products/benchmarks/heaven

**Comment by presianbg** [comment]
I played one match (Dota 2 Reborn) and looks like ``` disabling compositing for full-screen windows ``` makes a huge difference. Dota 2 Reborn is running smoother. Thank you. I'm closing this.
