### ISSUE TITLE
panel-launcher not finding custom .desktop files.

### ISSUE THREAD

**Issue by ColonelCarston** [linuxmint/Cinnamon#4527]
Using the inbuilt Launcher Properties to create a custom launcher for the panel launcher adds a .desktop file to the /home/user/.cinnamon/panel-launchers/ however, the actual panel-launcher only seems to look in the /usr/share/applications/ directory for the actual shortcuts it uses.

In order to test this I did the following:
-Created custom launcher
-Checked that custom launcher was in the .cinnamon/panel-launchers/ directory.
-Checked that the correct file name was added to the .json configuration file located in .cinnamon/configs/panel-launchers@cinnamon.org/
-At this point, the launcher was not located in the panel.
-Restarted Cinnamon; the .json reloaded itself and removed the file name for the custom launcher.
-Copy custom launcher to /usr/share/applications/ directory.
-Add custom launcher name back into the .json configuration file manually.
-Save the configuration file.
-Launcher now appears in the panel.
-Restart Cinnamon and the launcher stays in the panel and is not removed from the .json configuration file.

I am currently running Linux Mint 17.2 64bit and it is up to date.

**Comment by miken58b** [comment]
Just hit the same problem and spent a few hours wondering what I was doing wrong...  This looks like a Mint bug to me.  One minor point - I did't have to edit the .json file - I copied the shortcut file made by a failed attempt to /usr/share/applications/ and then added a shortcut with the same name so I guess it found the one copied previously.

I have a love/hate relationship with Linux....really shouldn't have to face this kind of stupidity if it wants to be a serious challenger to Windows....  Perhaps it all works if one is the 'root' user...

Mike

**Comment by miken58b** [comment]
And, of course, thank you for posting the solution!  :).  Mike

**Comment by JosephMcc** [comment]
I'm going to close this since it seems to be fixed in Cinnamon 2.8. If you still have issues I can reopen.

**Comment by miken58b** [comment]
I've just installed Mint with a fresh download (64bit) and it installed Cinnamon 2.6.3.  Upgrade to 2.8 hasn't been offered via Update Manager - I guess I have to hunt it down!

**Comment by JosephMcc** [comment]
It's available if you enable backports in the Update manager. Even though it may not be in 17.2 by default it will be in the upcoming 17.3. Like I said it should be fixed. If it's not when you get the chance to test 2.8 I'll reopen this.
