### ISSUE TITLE
Keyboard layout

### ISSUE THREAD

**Issue by AlaaDesouky** [linuxmint/Cinnamon#4528]
I installed linuxmint-17.2-cinnamon-64bit, but when I tried to make shift+alt change keyboard layout I couldn't find "keys to change layout" in "keyboard layout option" menu
![screenshot from 2015-08-19 02 27 10](https://cloud.githubusercontent.com/assets/11396968/9346172/dd6d89b2-4619-11e5-8134-6d7deb60807e.png)

**Comment by vladimir-didenko** [comment]
Use "Switching to another layout" entry.
