### ISSUE TITLE
[Bug][Expo][Multimonitor] Dont show workspace for second monitor if "Show workspaces only on primary monitor" is selected

### ISSUE THREAD

**Issue by gauravjuvekar** [linuxmint/cinnamon#4529]
![Image](http://i.imgur.com/rXE4v6w.jpg)
Don't show the crossed out area. Show as if only one monitor was present.

**Comment by tp0** [comment]
The behaviour is the same at least on Ubuntu Unity (Compiz), can't put it to technical words but I'm afraid this is something deeper and more inherited than just Cinnamon/Muffin...

But I've always been annoyed by this, showing the same secondary monitor multiple times is just utterly pointless, confusing and waste of space.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
