### ISSUE TITLE
Thunderbird tooltip remains visible when screen is locked

### ISSUE THREAD

**Issue by einheber** [linuxmint/Cinnamon#4530]
A tooltip from Thunderbird actively being displayed when the screen is locked remains visible on the lock screen and does not fade.  These should not be visible after screen lock.  I haven't been able to reproduce this with tooltips from other applications.

Experienced on Linux Mint 17.2 with Cinnamon running Thunderbird 31.8.0.

**Comment by leigh123linux** [comment]
https://github.com/linuxmint/cinnamon-screensaver/issues/34
