### ISSUE TITLE
Cinnamon settings stopped working, in terminal is some python error

### ISSUE THREAD

**Issue by ruthan** [linuxmint/Cinnamon#4532]
LMDE fully update, without external repositories.

In terminal this:

cinnamon-settings
Traceback (most recent call last):
  File "/usr/lib/cinnamon-settings/cinnamon-settings.py", line 38, in <module>
    modules = map(__import__, mod_files)
  File "/usr/lib/cinnamon-settings/modules/cs_applets.py", line 3, in <module>
    from ExtensionCore import ExtensionSidePage
  File "/usr/lib/cinnamon-settings/bin/ExtensionCore.py", line 29, in <module>
    curr_ver = subprocess.check_output(["cinnamon", "--version"]).splitlines()[0].split(" ")[1]
  File "/usr/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['cinnamon', '--version']' returned non-zero exit status -11

I dont know how to debug it, which extension applet do it and how disable it, when setting not working.

**Comment by GLolol** [comment]
Try running `cinnamon --version` in a terminal; for some reason, that's failing and causing the Settings app to crash.

**Comment by ruthan** [comment]
ruthan@ruthanlmde ~ $ cinnamon --version
Cinnamon 2.6.13
Segmentation fault

**Comment by JosephMcc** [comment]
Duplicate https://github.com/linuxmint/Cinnamon/issues/4542
