### ISSUE TITLE
Multimonitor - add file to desktop- will add file on primary monitor not on left one, feature request  or rationalisation

### ISSUE THREAD

**Issue by ruthan** [linuxmint/Cinnamon#4533]
I have problem with my setup my secondary monitor is on left, primary on right, im using secondary monitor only sometimes, but im using it as primary for other machines and switching through monitor buttons - monitor has 4 inputs.

  Problem is when im adding not files to desktop, for example through browser downloading into desktop folder, every new file is added in left, top corner of my extended desktop not on primary monitor like in Windows and Mac.. So i have to handling with monitors more often. Primary monitor should be really primary for everything or secondary should be optimal, only for things which user enable - for example by moving so window to secondary monitor.
 
  Would be nice at least have a choice how to control this behavior.

**Comment by mtwebster** [comment]
Right now, nemo (which handles this) treats the desktop as a large rectangle that encompasses all monitors.  It has no conception as to which is primary or not, it simply works from the top left as its origin for all initial placement calculations.

There are plans to change this (hopefully for 2.8) - and treat each monitor as its own file container to a certain extent, and respect the primary monitor selection (as well as better tiling and layout).

**Comment by ruthan** [comment]
And 2.8 delivery forecast?

**Comment by tp0** [comment]
> There are plans to change this (hopefully for 2.8)

Good to hear. At some point I even used vertical setup because of this, but I've just gotten used to this...

**Comment by JosephMcc** [comment]
I'm going to close this since it's actually a nemo issue. The needed improvements didn't make it for 2.8 but it will hopefully make it for 3.0: https://github.com/linuxmint/nemo/pull/987
