### ISSUE TITLE
L10n issue: Cinnamon lock screen defaults to 24-hour time for Australian locale

### ISSUE THREAD

**Issue by mscheper** [linuxmint/Cinnamon#4534]
Although my locale is set to en_AU, the Cinnamon lock screen displays the time in 24-hour format. I can fix this by setting _Screensaver → Date → Time Format_ to `%l:%H %p`, but the default ought to be localised. en_AU is _not_ the same as en_GB (and definitely not en_US).

**Comment by mscheper** [comment]
Version: 2.6.13

**Comment by anandrkris** [comment]
@mscheper - Can you confirm if you see it on latest Cinnamon?

**Comment by Vahan86** [comment]
@JosephMcc, can we close the issue?
