### ISSUE TITLE
No help for Screensaver → Date → Time/Date Format

### ISSUE THREAD

**Issue by mscheper** [linuxmint/Cinnamon#4535]
In 2.6.13, there is no explanation for the format to use for the configuration fields _Screensaver → Date → Time Format_ and _Date Format_. (Websearching just yields posts calling for the introduction of these fields.) It turns out they just use `strftime`, but there's no indication of this.

Additional knitpick: The _Date Format_ label has a trailing colon, but none of the other fields' labels do.

(Thanks for adding this much-needed configuration feature, though!)

**Comment by anandrkris** [comment]
Yes, would be good to show help like how we currently have in Date Applet. A button that leads to http://www.foragoodstrftime.com/

![help](https://cloud.githubusercontent.com/assets/4663298/17941126/93cb9c4e-6a4f-11e6-9f38-af552fd4d48f.png)
