### ISSUE TITLE
Global media hotkeys do not work with Banshee

### ISSUE THREAD

**Issue by rkingsbury** [linuxmint/cinnamon#4536]
Media hotkeys (Play/Pause, Next, Previous) do not work with Banshee or with the sound indicator. I can go into keyboard shortcuts and assign them to the respective actions, so I know they are being recognized by the system, but they don't do anything when banshee or other media players are playing.

Mint 17.2 Cinnamon (updated from an original 17.0 installation).

**Comment by JosephMcc** [comment]
This works fine for me on 17.2, at least with Banshee and Rhythmbox.

**Comment by f1xmAn** [comment]
Reproduces with Clementine. But if sound applet is opened they work. I have Mint 17.2 upgraded from 17.1.

**Comment by justsml** [comment]
me too on an upgraded 17.2 LMDE2

**Comment by JosephMcc** [comment]
This works for me on an updated LMDE2 as well. Most players seem to need an extension/plugin enabled for this to work. With Banshee, in the preferences, you need to enable a multimedia keys extension.

**Comment by devsseb** [comment]
Same problem as f1xmAn and rkingsbury with 17.2 and 17.3 (upgraded).
My keyboard is a Logithech K270.

**Comment by ManIVIctorious** [comment]
Seems to not work with clementine either. Clementine only supports its own or gnome-keyboard shortcuts. Wouldn't it be easier to use the MPRIS interface than to create an additional api for the keybindings?

**Comment by BNolet** [comment]
Issue persists on Linux 4.10.6-1-ARCH #1 SMP PREEMPT Mon Mar 27 08:28:22 CEST 2017 x86_64 GNU/Linux

Cinnamon ver: 3.2.8

Media keys don't work unless the media applet is opened _or_ the desktop is locked.

**Comment by Vahan86** [comment]
@rkingsbury, is this still an issue for you in Cinnamon 4.2?

**Comment by rkingsbury** [comment]
@Vahan86 Have not tested in quite some time; I no longer use Linux Mint on a regular basis.

**Comment by icarter09** [comment]
@rkingsbury no worries and thanks for the update.
