### ISSUE TITLE
notifications and mjpeg issues

### ISSUE THREAD

**Issue by zeos386sx** [linuxmint/Cinnamon#4538]
I have a mjpeg camera window up in firefox all the time and whenever a notification pops up the screen sometimes goes crazy and I have to maximize the window to stop it.  Disabling the notifications works, but I would like to be able to use the notifications if a fix is possible.

**Comment by dalcde** [comment]
How exactly does it go crazy?

**Comment by zeos386sx** [comment]
Well naturally when I went to record it I couldn't get it to happen. I guess I'll make a new thread if I can get it recorded.
