### ISSUE TITLE
[Bug][Multimonitor] Notifications cut across both monitors in extended mode

### ISSUE THREAD

**Issue by gauravjuvekar** [linuxmint/cinnamon#4541]
![screenshot from 2015-08-22 15 47 38](https://cloud.githubusercontent.com/assets/2271906/9423563/6579c022-48e6-11e5-9ca0-6c617aff0702.png)
That's for banshee's "Next song" notification

**Comment by JosephMcc** [comment]
I can't reproduce this using the default cinnamon theme. You might already know this but the theme has some control over this: https://github.com/linuxmint/Cinnamon/blob/master/data/theme/cinnamon.css#L597

Maybe an issue with the theme you're using?

**Comment by gauravjuvekar** [comment]
@JosephMcc Mine is set to 0px, still shouldn't it be flush with right edge of one monitor and not cross-over?

**Comment by JosephMcc** [comment]
@gauravjuvekar Yes it should. I can reproduce this but the behavior is a little strange. Testing with Banshee, after a Cinnamon restart the first notification is properly placed. The ones that come after are placed partially on the next screen like in your screenshot though.

**Comment by Vahan86** [comment]
@gauravjuvekar, is this still an issue for you with Cinnamon 4.4?

**Comment by gauravjuvekar** [comment]
No repro, v4.4.8
