### ISSUE TITLE
LMDE2 Cinnamon System Tray icon border (for BlueBerry icon etc)

### ISSUE THREAD

**Issue by wibble99** [linuxmint/Cinnamon#4543]
The icon for BlueBerry (and other systray icons too) in Cinnamon under LMDE2 has a black border around it that is inconsistent with the rest of the panel theme.
![border](https://cloud.githubusercontent.com/assets/11399478/9429298/3e1f1b34-49c3-11e5-8546-0391c57bcb6f.jpg)

What's even stranger is that sometimes (in ways that I cannot knowingly reproduce) the border disappears. I've tried changing Cinnamon theme, but that has no effect. Situations where the border has disappeared include clicking the BlueBerry icon to access the control window and disconnecting my Bluetooth mouse and reconnecting it. However the border remains most of the time when I do these things.

The issue did not occur under any version of Cinnamon in the Main Edition, and it occurs in both Cinnamon 2.4 and 2.6 under LMDE2 (including the live DVD).

**Comment by Silmathoron** [comment]
Same problem with border color that depends on the theme; appears around bluetooth and keyboard input icons.
It does not seem to come from conflict with the root theme.
I never see them disappear, though.

**Comment by wibble99** [comment]
Fixed in Cinnamon 3.0.6 - thank you.
