### ISSUE TITLE
Cinnamon lock screen: unlock button should be greyed out before a password is typed

### ISSUE THREAD

**Issue by EmielBlanko** [linuxmint/Cinnamon#4544]
(minor issue, but slightly annoying) 
In the Cinnamon lock screen, the popup for typing the password has an active Unlock button before a single character of the password is typed in. This invites the user to click on it before giving the password, only resulting in a "wrong password" message. It would be better to 'grey-out' the Unlock button untill the 1st character of the password is given (and either not allow empty passwords or still accept the enter-key in case of an empty password).

**Comment by dalcde** [comment]
not a valid issue imo. People can have empty passwords and I don't see why people would want to just click the unlock password if there is clearly a box to fill in the password. Even if they did, the same mistake probably won't be committed after 2-3 times.
