### ISSUE TITLE
Can anyone please add new gitg to cinnamon ?

### ISSUE THREAD

**Issue by xerosanyam** [linuxmint/Cinnamon#4547]

**Comment by dalcde** [comment]
Bother to explain?

**Comment by leigh123linux** [comment]
The title is vague.

It's a NO if you expect linuxmint to do it!
If you expect a newer version through the repo's (package manager) you will need to file a bugreport against whatever distro you use.

You are always free to DIY

https://wiki.gnome.org/action/show/Apps/Gitg?action=show&redirect=Gitg#Install_from_source
