### ISSUE TITLE
Distracting bottom panel tooltips

### ISSUE THREAD

**Issue by segrey** [linuxmint/Cinnamon#4549]
When mouse is over some items from the bottom panel, a tooltip is shown up occupying visual area above the bottom panel. The shown tooltips are eye-catching and distract me a bit.
Most times it happens when I switch to another running application from the taskbar using mouse. The thing is that after clicking an application (switching to it), I don't need mouse anymore, so mouse's pointer is being over taskbar resulting in persistent tooltips. Moreover, such a tooltip doesn't provide any new information for me, because it duplicates the window's title from the taskbar.

This screenshot illustrates the tooltip
![taskbar-tooltip](https://cloud.githubusercontent.com/assets/607109/9465091/372f5922-4b32-11e5-97a0-249c6f6079ae.png)

Personally, I have been using Linux Mint MATE for years, and I hadn't noticed such a problem there. The difference is that MATE shows tooltips inside the bottom panel, not above the bottom panel.

Let me suggest a few possible improvements:
- Show tooltips inside the bottom panel like MATE does.
- Provide a way to disable tooltips for running application from the taskbar as these tooltips provide no new information. ~~Or maybe disable by default?~~
- It seems to me that the tooltip's padding space (between text and tooltip's edge) could be diminished a bit without impact on text readability. For example, "Files" tooltip component area seems to be larger than needed for "Files" text:
  ![too-big-tooltip](https://cloud.githubusercontent.com/assets/607109/9470039/b4691b2e-4b52-11e5-8729-21c7010d4262.png)

Thanks!

**Comment by lestcape** [comment]
Reference of the same appreciation, about the tooltips feature.

https://github.com/lestcape/Global-AppMenu/issues/17

I want to comment that this is not a problem to me, but in some cases (not all) I consider that tooltips could be annoying. Disable the tooltips by default isn't a good option to me as will impact the new user, but if is provided a way to disable it or an option to show in..., will be good, i think.

**Comment by segrey** [comment]
@lestcape Thanks for the information. Agreed, disabling taskbar tooltips by default isn't a desirable change to do. Although, taskbar tooltip duplicates application title, it could be useful, if there are quite many running applications, so taskbar application element area is small enough.
BTW, do you know by chance if there is a workaround to suppress tooltips in Linux Mint 17.2 Cinnamon?

**Comment by swartzd** [comment]
Definitely would appreciate the option to turn these off. When using Synergy and mousing to a computer physically "below", the tooltips remain after the mouse exits the screen.

**Comment by artik** [comment]
Disturbed too. I found a workaround.

Edit your cinnamon.css file of your theme, located in ~/.themes/your_theme/cinnamon/cinnamon.css

Search (or create) this class :

#Tooltip {
background-color: rgba(0,0,0,0.0);
color:  rgba(0,0,0,0.0);
}

(display: none; doesn't work). Nos the tooltip is fully transparent, so unvisible.

**Comment by Falnir** [comment]
@artik  My themes folder is empty. What can I do?

**Comment by JosephMcc** [comment]
The theme could also be in /usr/share/themes. Just check in the themes settings to find the name of the theme you are using.

**Comment by Falnir** [comment]
@JosephMcc Thanks, it works now :)

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
