### ISSUE TITLE
Tooltips from some applications appear on lock screen

### ISSUE THREAD

**Issue by kjfergu** [linuxmint/Cinnamon#4550]
Distribution: LMDE (Fully updated)

Cinnamon Version:  2.6.13

Reproducible: Always (In certain applications)

Method to Reproduce: Let mouse hover over a box or button that displays a tooltip, then allow the screen to time out and lock.

Observed Behavior: The tooltip will remain open on the lock screen

Expected Behavior: The tooltip should not appear on the lock screen

I have only reproduced this using Firefox and Thunderbird from the LMDE repos, so it is possible that this is an upstream issue in those projects. It does not appear to occur when using apps built as part of Cinnamon (Settings app, panel, etc)

I have also noticed that on applications which do not display this behavior, the tooltip will be dismissed as soon as the screen begins to fade, and the tooltip will not appear on the lock screen. In cases where the tooltip does appear on the lock screen, the tip is not dismissed during the fade.

**Comment by leigh123linux** [comment]
https://github.com/linuxmint/cinnamon-screensaver/issues/34

**Comment by kjfergu** [comment]
That is definitely it. I'll close this bug in favor of that one.
