### ISSUE TITLE
Sound applet slows down login

### ISSUE THREAD

**Issue by inf3rno** [linuxmint/Cinnamon#4551]
I had the same issue as the guys here: https://bugs.launchpad.net/linuxmint/+bug/1339048 with cinnamon 2.6.13. Sometimes 20 secs login time, but at least 5 secs. I followed this instruction https://bugs.launchpad.net/linuxmint/+bug/1339048/comments/8 . I removed the sound applet from the desktop and now I got 1-2 secs login time. So something is really bad about that DEFAULT applet, you should debug it.

**Comment by inf3rno** [comment]
it might be related to this issue https://github.com/linuxmint/Cinnamon/issues/3681

**Comment by leigh123linux** [comment]
@inf3rno 
You will need to debug this as you have the issue.
As for the bugreport you linked it has no useful info and seems to be a bunch of fools complaining but not presenting any evidence!

**Comment by inf3rno** [comment]
what log should I use?

**Comment by pixunil** [comment]
`~/.cinnamon/glass.log`, and please verify that you have fair conditions (hot start vs cold start)
E.g. after cinnamon has started, every restart is fast (1 to 2 seconds even on my slow HDD), after a plain reboot, it is much more.
I really don't think that ths is the fault of the sound applet, as there are much more heavier modules of Cinnamon / your computer (I assume that there are more programs that are run in the background).

**Comment by inf3rno** [comment]
@pixunil You are right, it was only fast because the hot start. With cold start I got black screen for 10 secs.
