### ISSUE TITLE
Network manager forcibly saves OpenVPN private key password

### ISSUE THREAD

**Issue by Kurgan-** [linuxmint/Cinnamon#4553]
I am running Mint 17.2 with Cinnamon.

It seems that I cannot save a VPN (Openvpn) config in Network Manager WITHOUT saving the private key password too.

If the private key requires a password, the "save" button is greyed out (disabled) until I enter a password to be saved along with the VPN configuration in NM, thus preventing the user from saving a VPN configuration without the private key password.

IMHO this behaviour is horribly wrong and totally insecure. 

While it's fine to able to save the private key password for a VPN, it definitely should NOT be mandatory to do so. 

If the password is not saved, it should be requested interactively at every VPN activation.

**Comment by GLolol** [comment]
This would be a NetworkManager issue, and not a Cinnamon problem: https://bugzilla.gnome.org/enter_bug.cgi?product=NetworkManager

**Comment by Kurgan-** [comment]
Sorry, I thought it was a Cinnamon issue because on my old Ubuntu with NM I was able to avoid saving vpn passwords. I will report the bug to NM devs.

**Comment by douardda** [comment]
@Kurgan- did you open a ticket on the NM bugzilla? I also find this "feature" very annoying.

**Comment by Kurgan-** [comment]
Yes, I did, but no one cared.

Here is the link: https://bugzilla.gnome.org/show_bug.cgi?id=754126

**Comment by Vahan86** [comment]
@JosephMcc, could this issue be related to Cinnamon?

**Comment by Vahan86** [comment]
@Kurgan-, is this still an issue for you in Cinnamon 3.2 (Mint 18.1)?

**Comment by Kurgan-** [comment]
Yes. I have just set up a VM with Mint 18.1 and I have found that the issue is resolved. the default behaviour is still the same (ask for password and save it) but it can be changed.
![New GUI](https://cloud.githubusercontent.com/assets/10371854/22626610/eaac2aa4-ebb1-11e6-8719-0769a009c045.jpg)

**Comment by Vahan86** [comment]
@Kurgan-, thanks for your reply. In this case can you please close the issue?

**Comment by Kurgan-** [comment]
Sure. The issue, AFAIK, is resolved in Mint 18.1.
