### ISSUE TITLE
Unable to upload updated desklet to cinnamon-spices

### ISSUE THREAD

**Issue by tipichris** [linuxmint/Cinnamon#4554]
I am unable to upload an update of the Weather Desklet to http://cinnamon-spices.linuxmint.com/desklets/view/20. I get the following error:

`The uploaded file exceeds the maximum allowed size in your PHP configuration file.`

The site claims to be able to handle files up to 10MB. The file I wish to upload is 7.6MB, pretty much the same size as the version currently there, and slightly smaller than some earlier versions have been.

**Comment by tipichris** [comment]
If this is the wrong place to report this, can anyone suggest where the right place is? Or has cinnamon-spices been abandoned?

**Comment by ManIVIctorious** [comment]
Well, I'd say the right place for this would be [linuxmint/cinnamon-spices](https://github.com/linuxmint/cinnamon-spices/issues?q=is%3Aopen+is%3Aissue)

**Comment by tipichris** [comment]
Ah, makes sense. Thanks.
