### ISSUE TITLE
xdg-open doesn't obey defaults in Cinnamon

### ISSUE THREAD

**Issue by geckolinux** [linuxmint/cinnamon#4555]
I'm running Cinnamon 2.6 with the Nemo file manager in Ubuntu 15.04. For some reason, I can't make Nemo automatically launch with the `xdg-open` command, which is probably why inserting removable media also wants to launch Nautilus instead of Nemo. Nautilus seems to be hard-coded.

I already tried following this, to no avail:
http://askubuntu.com/questions/260244/make-nemo-the-default-file-browser

Here's my `~/.local/share/applications/mimeapps.list`

```
[Default Applications]
inode/directory=nemo.desktop;
application/x-gnome-saved-search=nemo.desktop;
x-content/unix-software=nemo-autorun-software.desktop
```

I also removed all instances of `nautilus.desktop` from `/usr/share/applications/mimeinfo.cache`.

But when I run `xdg-open $HOME` it still launches Nautilus. What's the matter here?

In a simple openbox session, `xdg-open` correctly launches Nemo, but not under Cinnamon.

Here's my `printenv` output: http://paste.ubuntu.com/12203716/

Thanks for your help.

**Comment by leigh123linux** [comment]
Try this as I believe cinnamon uses ~/.config for storing and reading mime

```
ln -s ~/.local/share/applications/mimeapps.list  ~/.config/mimeapps.list
```

**Comment by sb56637** [comment]
Thanks very much for the help @leigh123linux . I can confirm that copying [this](http://pkgs.fedoraproject.org/cgit/cinnamon-desktop.git/plain/x-cinnamon-mimeapps.list) into `~/.config/mimeapps.list` works.

So I guess the question is: Should Cinnamon be using `~/.config/mimeapps.list` if it is a non-standard location? Everything else uses `~/.local/share/applications/mimeapps.list` as far as I can tell.

Thanks again!

**Comment by leigh123linux** [comment]
The file location is permitted by the freedesktop standards.

http://standards.freedesktop.org/mime-apps-spec/mime-apps-spec-1.0.1.html#file

**Comment by sb56637** [comment]
Hmm, still isn't common though. And the `xdg-mime` command also sets defaults in `~/.local/share/applications/mimeapps.list`, not  `~/.config/mimeapps.list`.

**Comment by ManIVIctorious** [comment]
I also think that this should be changed

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
