### ISSUE TITLE
Defining a default audio device

### ISSUE THREAD

**Issue by artscoop** [linuxmint/Cinnamon#4556]
Hello,
I have some annoying problems with the Cinnamon audio applet (2.6), which are:
1. When an audio device is lost (USB or network), all applications default to the base device. (OK)
2. When the device is found again, you have to select it manually, but open applications do not switch to the selected device (Not OK)
3. The applet provides no way to select the device for an open app (Not OK)

This issue is hence a feature request, which involves the following features:
- Showing all historically known plugged devices (with available devices first, and others greyed out), and allow a user to select one as default (even a greyed out one), which means it's selected as soon as it is available. Open apps don't have to switch to the default device as it gets available.
- Add an option (checkbox) to automatically move playing apps to the current device as it changes.
- Add device selection for each application.

**Comment by ManIVIctorious** [comment]
The sound applet and audio settings have been revamped since cinnamon 2.6, does this issue still occur in cinnamon 3.0?

**Comment by Vahan86** [comment]
@JosephMcc, can we close the issue?
