### ISSUE TITLE
[Feature Request] Keyboard Shortcut to Open/Make Visible Programs from the Panel

### ISSUE THREAD

**Issue by pretodor** [linuxmint/Cinnamon#4557]
Like in Ubuntu or the latest versions of Windows when you hit Super+[number].

Apologies is this has already been asked.

**Comment by tp0** [comment]
You mean from the shortcut launcher or window list?

Check **Window List With App Grouping** applet which has this feature and pretty much is how W7 works.

http://cinnamon-spices.linuxmint.com/applets/view/16

**Comment by pretodor** [comment]
The applet is not quite what I have in mind. I am asking that the already visible icons on the left side of the panel have this functionality. 

Also, when I change the places of the icons, I would like to see this reflected in the keyboard combinations. So, if I want to open up System Settings, I'll have to hit Super + 1 in this situation:
![photo1](https://cloud.githubusercontent.com/assets/1466111/9640848/39d8f076-51bc-11e5-8a9c-4739c2d9d3b7.png)

and Super + 2 in this situation:
![photo2](https://cloud.githubusercontent.com/assets/1466111/9640868/4866683a-51bc-11e5-8289-ffd7c04da256.png)

Thanks for suggesting the applet. It's neat but not exactly what I'm looking for.

**Comment by dandv** [comment]
@pretodor actually the applet does switch to pinned apps, though due to [a bug](https://github.com/jake-phy/WindowIconList/issues/147), it only switches to the default ones, and if you unpin and pin again, it breaks.

**Comment by edkv** [comment]
I've created an extension that provides this functionality. It also allows cycling through windows and moving them.

https://github.com/edkv/cinnamon-window-list-controller
