### ISSUE TITLE
Cinnamon 2.6.13 crashes randomly

### ISSUE THREAD

**Issue by Boldewyn** [linuxmint/Cinnamon#4558]
This is an LMDE upgraded recently from v1 to v2. Cinnamon is at v2.6.13. The system ran smoothly for some time, but I start to get Cinnamon crashes at random times now. That is, it crashes during sessions, not necessarily at specific points. An example syslog entry:

```
Aug 27 15:15:38 localhost kernel: [  304.704847] traps: cinnamon[3964] trap int3 ip:7fadd1e9ed30 sp:7ffc71f92030 error:0
Aug 27 15:15:39 localhost x-session-manager[3824]: WARNING: Application 'cinnamon.desktop' killed by signal 15
```

_Edit:_ It seems, that this crash happens when I have opened a specific page in a Firefox tab, and Firefox is focused and in the foreground. Unfortunately, that's an intranet page, so that I can't share a public URL.

**Comment by Vahan86** [comment]
@Boldewyn, is this still an issue for you in Cinnamon 3.2?

**Comment by Boldewyn** [comment]
Can't tell. I switched to XFCE since, partly because of this issue...

**Comment by Vahan86** [comment]
@Boldewyn, thank you for you reply, in this case can you please close the issue?
