### ISSUE TITLE
"keep aligned" option fails to do the one thing it is meant to do for desktop file icons, need automatic desktop icon alignment feature like within Nemo folder view

### ISSUE THREAD

**Issue by Swiftpaw** [linuxmint/Cinnamon#4561]
**Problem:**

For file icons on your desktop, when "keep aligned" is turned off, you can move icons a tiny amount in any direction.

When this option is turned on, icons need to be drug farther *horizontally* before they will move horizontally.  However, they still do not align nicely to a grid or to columns when moved horizontally.  You can still place them in between two columns of icons.  For example, when you do an "Organize Desktop by Name", the columns that it gives you are broken by the ability to move icons in between those columns even with this "keep aligned" option turned on, rendering it useless.

Furthermore, when icons are moved vertically, you can still move them a tiny bit just like you can when the option is disabled, meaning the only point of the "keep aligned" feature is supposed to be keeping them aligned to the columns **which it fails at doing**, and you can still overlap icons on top of one another vertically which is annoying.  I assume the reasoning behind the column snapping having an intermediate snap between the two columns was "if we keep them aligned completely to columns, they will jump around too much when moving/creating icons on the desktop", but any user with "keep aligned" on should be expecting this.

**Solution:**

At the very least, make icons align to columns, if not a grid, when "keep aligned" is turned on.  I'd prefer a grid like Windows does, as things get messy when you can put icons covering each other up vertically, so have a snapping/alignment option for a grid would be best.  You could also have an option for "keep sorted" which means no matter where you drop/create an icon on the desktop, it will be sorted like when you select "Organize Desktop by Name" (but you wouldn't have to keep clicking on that option like you do now).

I think these changes would go a long way to making the default Cinnamon desktop better than other desktops. :wolf:

**Comment by JosephMcc** [comment]
This is a nemo issue. If you go here: https://github.com/linuxmint/nemo you will find existing threads about the misbehaviour of nemo desktop icon alignment :)
