### ISSUE TITLE
Add options for launching multiple instances of app by launcher

### ISSUE THREAD

**Issue by jaskmar** [linuxmint/Cinnamon#4571]
There are programs that people don't want to execute multiple times but just one instance. Git-cola is good example for me. I would suggest to ease this behaviour by adding some options for launchers, for example as on the image:
![zrzut ekranu z 2015-09-01 08 36 45](https://cloud.githubusercontent.com/assets/4416966/9598088/5880afbc-5088-11e5-9bd7-c56249cdce8a.png)

**Comment by Vahan86** [comment]
@JosephMcc, can we mark this issue as a feature request?

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
