### ISSUE TITLE
[feature request] disable tablet touch on GUI

### ISSUE THREAD

**Issue by BlackDizel** [linuxmint/cinnamon#4572]
need some checkbox on tablet settings to disable tablet touch with wacom pen&touch tablets 

or tablet icon on tray with fast tablet settings like buttons reassign, current buttons mapping and disable/enable touch checkbox.

http://askubuntu.com/questions/487490/wacom-intuos5-disable-touch-by-default

**Comment by Vahan86** [comment]
@JosephMcc, can we mark this issue as a feature request?

**Comment by cgarciaq** [comment]
There is a magick-rotation script that does this. It also rotates correctly the touchscreen, along with your screen, when you rotate your 2-in-1 (or whichever device that has an accelerometer to detect your position).

**Comment by icarter09** [comment]
@BlackDizel did @cgarciaq comment help get this feature implemented in the mean time for you?

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
