### ISSUE TITLE
No workspace switching effect when using "Cycle through open windows of the same application"

### ISSUE THREAD

**Issue by tp0** [linuxmint/Cinnamon#4573]
Repro:
- have at least 2 workspaces
- open some same application on both workspaces
- use "Cycle through open windows of the same application" shortcut to switch between them

Expected result: workspace switching effect, as when normally switching between workspaces via keyboard shortcuts.

**Comment by Vahan86** [comment]
It's working fine for me in Cinnamon 3.0.7. 

@tp0, is this still an issue for you in Cinnamon 3.0?

**Comment by Vahan86** [comment]
@JosephMcc, can we close the issue?

**Comment by shadowxnex** [comment]
For me, it's not.
I have Cinnamon 3.4.3. Several sublime application is displayed on several workspaces. When I use this shortcut, I have workspace switching behaviour. It's wrong, I suppose.
