### ISSUE TITLE
[feature request] Have switch workspace applet on tool bar show contents of each workspace

### ISSUE THREAD

**Issue by jdallara** [linuxmint/Cinnamon#4574]
With Gnome DE on Ubuntu, the switch workspace applet in the tool bar shows a representation of what is in each workspace using solid colored blocks to represent each window that is open in the workspace.  Is it possible to do that currently or can that be added to Mint?  I'm using Mint 17.2.  It makes it easy to find open workspaces and to see what is on each workspace.

Thanks,  Jon.

**Comment by clefebvre** [comment]
You read my mind :) I started working on that a couple of days ago and I'm almost finished now. It will be a feature in Cinnamon 2.8.

**Comment by jdallara** [comment]
Thank you!  Appreciate all the hard work that is being done.

Jon

On 09/02/2015 02:44 AM, Clement Lefebvre wrote:
>
> You read my mind :) I started working on that a couple of days ago and 
> I'm almost finished now. It will be a feature in Cinnamon 2.8.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/linuxmint/Cinnamon/issues/4574#issuecomment-137002851>.
>

-- 
Jon Dallara
Assistant Director
FIT Ministries

Lead Foreman / Project Manager
Chariatable Construction and Landscaping Services
209.483.1407

Sent using Thunderbird
