### ISSUE TITLE
When disabling Wired connection, system freezes (Linux Mint 17.2)

### ISSUE THREAD

**Issue by wishx** [linuxmint/Cinnamon#4575]
Hardware:
ASUS G750
NVidia GTX 770M
32GB RAM

OS:
Linux Mint 17.2 Cinnamon 64-bit

Problem:
When I click on the networking applet and click on Wired to shut it off, the entire system freezes except for the mouse which will still move, but not click. The HD will run, but no keyboard or mouse clicking is possible immediately after this. It's like the OS has been slowed to a crawl. It will remain like this for minutes with an occasional second of activity.

Since everything freezes as it was, I can click where the Wired button is to turn it back on, but I have to wait until one of those blips of activity to happen so the input takes effect. This can take 10-15 minutes or more. The same thing happens if I pull the ethernet cable out of the the computer. It doesn't matter if I turn Wireless on or off before this. Wireless seems to be irrelevant in this scenario.

If I hold down the power button and force a hard reboot, the OS will come back up like normal whether I have Wired on or off. If I turn it on and connect, fine. If I try to turn it off or yank the ethernet cable again, it freezes. I've let it sit like that for a half hour and it never recovers. I have to either turn it back on or put the ethernet cable back in for everything to work smoothly again. I'm baffled!

```
$ inxi -N
Network:   Card-1: Qualcomm Atheros AR9485 Wireless Network Adapter driver: ath9k 
           Card-2: Qualcomm Atheros QCA8171 Gigabit Ethernet driver: alx
```

```
$ lspci -nn
00:00.0 Host bridge [0600]: Intel Corporation Xeon E3-1200 v3/4th Gen Core Processor DRAM Controller [8086:0c04] (rev 06)
00:01.0 PCI bridge [0604]: Intel Corporation Xeon E3-1200 v3/4th Gen Core Processor PCI Express x16 Controller [8086:0c01] (rev 06)
00:14.0 USB controller [0c03]: Intel Corporation 8 Series/C220 Series Chipset Family USB xHCI [8086:8c31] (rev 04)
00:16.0 Communication controller [0780]: Intel Corporation 8 Series/C220 Series Chipset Family MEI Controller #1 [8086:8c3a] (rev 04)
00:1a.0 USB controller [0c03]: Intel Corporation 8 Series/C220 Series Chipset Family USB EHCI #2 [8086:8c2d] (rev 04)
00:1b.0 Audio device [0403]: Intel Corporation 8 Series/C220 Series Chipset High Definition Audio Controller [8086:8c20] (rev 04)
00:1c.0 PCI bridge [0604]: Intel Corporation 8 Series/C220 Series Chipset Family PCI Express Root Port #1 [8086:8c10] (rev d4)
00:1c.2 PCI bridge [0604]: Intel Corporation 8 Series/C220 Series Chipset Family PCI Express Root Port #3 [8086:8c14] (rev d4)
00:1c.3 PCI bridge [0604]: Intel Corporation 8 Series/C220 Series Chipset Family PCI Express Root Port #4 [8086:8c16] (rev d4)
00:1c.4 PCI bridge [0604]: Intel Corporation 8 Series/C220 Series Chipset Family PCI Express Root Port #5 [8086:8c18] (rev d4)
00:1d.0 USB controller [0c03]: Intel Corporation 8 Series/C220 Series Chipset Family USB EHCI #1 [8086:8c26] (rev 04)
00:1f.0 ISA bridge [0601]: Intel Corporation HM87 Express LPC Controller [8086:8c4b] (rev 04)
00:1f.2 SATA controller [0106]: Intel Corporation 8 Series/C220 Series Chipset Family 6-port SATA Controller 1 [AHCI mode] [8086:8c03] (rev 04)
00:1f.3 SMBus [0c05]: Intel Corporation 8 Series/C220 Series Chipset Family SMBus Controller [8086:8c22] (rev 04)
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation GK106M [GeForce GTX 770M] [10de:11e0] (rev a1)
01:00.1 Audio device [0403]: NVIDIA Corporation GK106 HDMI Audio Controller [10de:0e0b] (rev a1)
03:00.0 Network controller [0280]: Qualcomm Atheros AR9485 Wireless Network Adapter [168c:0032] (rev 01)
04:00.0 Ethernet controller [0200]: Qualcomm Atheros QCA8171 Gigabit Ethernet [1969:10a1] (rev 10)
```

```
$ uname -a
Linux Blade 4.1.6-040106-generic #201508170230 SMP Mon Aug 17 06:32:14 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

```
$ modinfo alx
filename:       /lib/modules/4.1.6-040106-generic/kernel/drivers/net/ethernet/atheros/alx/alx.ko
license:        GPL
description:    Qualcomm Atheros(R) AR816x/AR817x PCI-E Ethernet Network Driver
author:         Qualcomm Corporation, <nic-devel@qualcomm.com>
author:         Johannes Berg <johannes@sipsolutions.net>
srcversion:     1917D292620190CB7319BDE
alias:          pci:v00001969d000010A0sv*sd*bc*sc*i*
alias:          pci:v00001969d000010A1sv*sd*bc*sc*i*
alias:          pci:v00001969d00001090sv*sd*bc*sc*i*
alias:          pci:v00001969d0000E091sv*sd*bc*sc*i*
alias:          pci:v00001969d00001091sv*sd*bc*sc*i*
depends:        mdio
intree:         Y
vermagic:       4.1.6-040106-generic SMP mod_unload modversions
```

Thanks in advance!

**Comment by wishx** [comment]
No ideas?

**Comment by wishx** [comment]
I've been forced to switch to MATE. Thanks anyway.

**Comment by ManIVIctorious** [comment]
Could you try if this is still an issue in cinnamon 3.0? 
If not this will have to be closed due to too few information.

**Comment by wishx** [comment]
> Could you try if this is still an issue in cinnamon 3.0?

It is definitely still an issue. I am now on Linux Mint 18 / Cinnamon 3.x and it's still a problem. I notices just yesterday that, when I am connected to ethernet and I activate a wireless connection also, the desktop freezes for almost 5 minutes. The mouse still moves and music will play (if playing), but the desktop freezes. It also happens if you only have ethernet or wireless connected and disconnect it. Basically, any change in network state and it's freezing. If you disconnect, it will freeze until a connection is made again. If not, I've seen it remain frozen and trying to recover for hours. It's definitely still a problem.

**Comment by mainmachine** [comment]
I am not seeing this behavior on an Acer V17 - the only thing that will break for me if I enable/disable one network device or the other is any SSH sessions I had will hang, but that's a "broken pipe" and unrelated. At work I have an ehternet cable plugged in 90% of the time and WiFi may or may not be on, and I often pull the Ethernet to move to a meeting table without powering down or suspending, and aside from an SSH session hanging, I never see an issue...

Could this be hardware specific, maybe a firmware bug on either your WiFi or NIC?

Is this a mint issue...?

```
$ sudo lshw -c net | grep 'vendor:\|product:'
product: Wireless 7260
vendor: Intel Corporation
product: NetLink BCM57780 Gigabit Ethernet PCIe
vendor: Broadcom Corporation
```

**Comment by wishx** [comment]
It doesn't happen with any other desktop environment. I can use MATE. XFCE, Unity, etc. without incident. None of them care if I yank the ethernet while connected to (or disconnected from) WiFi. That suggests it's something with Cinnamon and likely something that's carried over from version to version. This ticket has been open for just over a year. (Happy Anniversary, bug!)

**Comment by kbazsi** [comment]
I have the same problem, when network cable is pulled off cinnamon freezes. If I reconnect the cable everything works.
While the graphical user interface it's frozen I can switch to command line with Ctrl + Alt + F1 and there everything works.

$ inxi -Fx
System:    Host: myHP Kernel: 4.4.0-57-generic x86_64 (64 bit gcc: 5.4.0)
           Desktop: Cinnamon 3.0.7 (Gtk 3.18.9-1ubuntu3.1) Distro: Linux Mint 18 Sarah
Machine:   System: Hewlett-Packard product: HP ProDesk 400 G2 MT
           Mobo: Hewlett-Packard model: 198E Bios: Hewlett-Packard v: L02 v02.18 date: 05/09/2014
CPU:       Dual core Intel Core i3-4150 (-HT-MCP-) cache: 3072 KB
           flags: (lm nx sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx) bmips: 13968
           clock speeds: max: 3500 MHz 1: 3500 MHz 2: 3500 MHz 3: 3500 MHz 4: 3500 MHz
Graphics:  Card: Intel 4th Generation Core Processor Family Integrated Graphics Controller bus-ID: 00:02.0
           Display Server: X.Org 1.18.3 drivers: intel (unloaded: fbdev,vesa) Resolution: 1920x1080@60.00hz
           GLX Renderer: Mesa DRI Intel Haswell GLX Version: 3.0 Mesa 11.2.0 Direct Rendering: Yes
Audio:     Card Intel 8 Series/C220 Series High Definition Audio Controller driver: snd_hda_intel bus-ID: 00:1b.0
           Sound: Advanced Linux Sound Architecture v: k4.4.0-57-generic
Network:   Card: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller
           driver: r8169 v: 2.3LK-NAPI port: e000 bus-ID: 02:00.0
           IF: enp2s0 state: up speed: 1000 Mbps duplex: full mac: a0:d3:c1:4c:22:ff
Drives:    HDD Total Size: 500.1GB (6.8% used) ID-1: /dev/sda model: ST500DM002 size: 500.1GB
Partition: ID-1: / size: 454G used: 28G (7%) fs: ext4 dev: /dev/sda2
           ID-2: swap-1 size: 4.22GB used: 0.00GB (0%) fs: swap dev: /dev/sda3
RAID:      No RAID devices: /proc/mdstat, md_mod kernel module present
Sensors:   System Temperatures: cpu: 29.8C mobo: 27.8C
           Fan Speeds (in rpm): cpu: N/A
Info:      Processes: 233 Uptime: 58 min Memory: 2343.5/7912.0MB Init: systemd runlevel: 5 Gcc sys: 5.4.0
           Client: Shell (bash 4.3.421) inxi: 2.2.35

**Comment by wishx** [comment]
"I have the same problem, when network cable is pulled off cinnamon freezes. If I reconnect the cable everything works."

I'm still having the same issue as well.

**Comment by pwil3058** [comment]
Me too.  In fact, I have two wired connections and if i disconnect either one of them Cinnamon freezes except for mouse motion.  Does not happen with wi-fi connections on any of my laptops.

**Comment by leigh123linux** [comment]
After two years no one has provided any logging for the issue, if none is provided in the next week I will close the issue.

**Comment by pwil3058** [comment]
Exactly what logging do you require and how do I find it to give it to you?

**Comment by leigh123linux** [comment]
@pwil3058 ~/.xsession-errors or /var/log/messages with an error would help

**Comment by pwil3058** [comment]
Cinnamon warning: Failed to load theme "Adwaita": Failed to find a valid file for theme Adwaita

Cinnamon warning: Could not find theme Adwaita. Falling back to default theme.vmware-user: could not open /proc/fs/vmblock/dev
Failed to play sound: Sound disabled
** Message: nemo-desktop: session is cinnamon, establishing proxy
sys:1: Warning: g_hash_table_foreach: assertion 'version == hash_table->version' failed

(nemo-desktop:14755): GLib-GIO-CRITICAL **: g_dbus_proxy_call_sync_internal: assertion 'G_IS_DBUS_PROXY (proxy)' failed
Cjs-Message: JS LOG: About to start Cinnamon
St-Message: cogl npot texture sizes SUPPORTED
Cjs-Message: JS LOG: Cinnamon started at Sun Nov 12 2017 16:47:09 GMT+1000 (AEST)
** Message: nemo-desktop: session is cinnamon, establishing proxy
Cjs-Message: JS WARNING: [/home/peter/.local/share/cinnamon/applets/github-projects@morgan-design.com/applet.js 297]: reference to undefined property notifyContent.replace
glibtop(c=14707): [WARNING] Failed to open "/sys/class/net/D4:AE:05:97:C2:9C/statistics/rx_packets": No such file or directory
glibtop(c=14707): [WARNING] Failed to open "/sys/class/net/D4:AE:05:97:C2:9C/statistics/tx_packets": No such file or directory
glibtop(c=14707): [WARNING] Failed to open "/sys/class/net/D4:AE:05:97:C2:9C/statistics/rx_bytes": No such file or directory
glibtop(c=14707): [WARNING] Failed to open "/sys/class/net/D4:AE:05:97:C2:9C/statistics/tx_bytes": No such file or directory
glibtop(c=14707): [WARNING] Failed to open "/sys/class/net/D4:AE:05:97:C2:9C/statistics/rx_errors": No such file or directory
glibtop(c=14707): [WARNING] Failed to open "/sys/class/net/D4:AE:05:97:C2:9C/statistics/tx_errors": No such file or directory
glibtop(c=14707): [WARNING] Failed to open "/sys/class/net/D4:AE:05:97:C2:9C/statistics/collisions": No such file or directory
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.

**Comment by pwil3058** [comment]
Cinnamon warning: Failed to load theme "Adwaita": Failed to find a valid file for theme Adwaita

Cinnamon warning: Could not find theme Adwaita. Falling back to default theme.vmware-user: could not open /proc/fs/vmblock/dev
Failed to play sound: Sound disabled
** Message: nemo-desktop: session is cinnamon, establishing proxy
sys:1: Warning: g_hash_table_foreach: assertion 'version == hash_table->version' failed

(nemo-desktop:14755): GLib-GIO-CRITICAL **: g_dbus_proxy_call_sync_internal: assertion 'G_IS_DBUS_PROXY (proxy)' failed
Cjs-Message: JS LOG: About to start Cinnamon
St-Message: cogl npot texture sizes SUPPORTED
Cjs-Message: JS LOG: Cinnamon started at Sun Nov 12 2017 16:47:09 GMT+1000 (AEST)
** Message: nemo-desktop: session is cinnamon, establishing proxy
Cjs-Message: JS WARNING: [/home/peter/.local/share/cinnamon/applets/github-projects@morgan-design.com/applet.js 297]: reference to undefined property notifyContent.replace
glibtop(c=14707): [WARNING] Failed to open "/sys/class/net/D4:AE:05:97:C2:9C/statistics/rx_packets": No such file or directory
glibtop(c=14707): [WARNING] Failed to open "/sys/class/net/D4:AE:05:97:C2:9C/statistics/tx_packets": No such file or directory
glibtop(c=14707): [WARNING] Failed to open "/sys/class/net/D4:AE:05:97:C2:9C/statistics/rx_bytes": No such file or directory
glibtop(c=14707): [WARNING] Failed to open "/sys/class/net/D4:AE:05:97:C2:9C/statistics/tx_bytes": No such file or directory
glibtop(c=14707): [WARNING] Failed to open "/sys/class/net/D4:AE:05:97:C2:9C/statistics/rx_errors": No such file or directory
glibtop(c=14707): [WARNING] Failed to open "/sys/class/net/D4:AE:05:97:C2:9C/statistics/tx_errors": No such file or directory
glibtop(c=14707): [WARNING] Failed to open "/sys/class/net/D4:AE:05:97:C2:9C/statistics/collisions": No such file or directory
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.

**Comment by leigh123linux** [comment]
Try removing any monitoring applets and the libgtop package.
