### ISSUE TITLE
"Disable compositing for full-screen windows" causes full-screen windows to misbehave across workspaces

### ISSUE THREAD

**Issue by Hubro** [linuxmint/Cinnamon#4578]
When "Disable compositing for full-screen windows" is enabled (found in the General settings) full-screen windows become somewhat incompatible, or at least buggy, with workspaces. I have found two specific issues:
1. When a full-screen window is open and you switch to an empty workspace, the full-screen window is displayed on that workspace. If anything pops up to re-enable compositing, like a notification or opening the main menu, the full-screen window temporarily disappears from the empty workspace.
2. When a full-screen window is open, it occasionally and unpredictably covers the active workspace, whether it's empty or not. I can be typing an issue into Github, and the full-screen video player from a different workspace suddenly covers the screen. I haven't found a way to reproduce this completely reliably, but it happens pretty often (like every few minutes) so you should be able to reproduce it regardless. Switching to another workspace and back makes the full-screen window go away.

Disabling the aforementioned composition setting completely eliminates this issue, so it's definitely related.

---

I'm using Debian stretch with Cinnamon installed from the default repo (version 2.6.13-1).

**Comment by Vahan86** [comment]
@Hubro, is this still an issue for you in Cinnamon 3.0.x?

**Comment by JosephMcc** [comment]
Testing with xed in fullscreen I can't reproduce 1.

**Comment by Hubro** [comment]
I'm currently installing Cinnamon 3. I'll test this ASAP.

**Comment by Vahan86** [comment]
@Hubro, thanks a lot for reply. We will wait for the outcome of your testing.

**Comment by Hubro** [comment]
It has been almost 2 months and I still haven't found time when I'm at my Linux box. I apologize for that, and I'll assume for now that the bug is fixed. If I come across the bug again I'll just re-open.
