### ISSUE TITLE
Panel does not detect cursor

### ISSUE THREAD

**Issue by DarekDeo** [linuxmint/Cinnamon#4584]
First of all, it is hard to reproduce. Sometimes it even works fine for whole day or two, then issue appears.

I have Intelli hide enabled, Mint 17.2 (updated from 17.1), Cinnamon 2.6.13, panel on top, one laptop screen, 2-3 workspaces. Default Mint-x theme (only default-gnome icon theme). Applications in tray:
-chromium
-tomboy
-mint update
-shutter
-dropbox
-glipper
-pidgin
-gnomedo (but it was happening even if I had tray for gnomedo disabled)
and applets:
-places custom applet @dmo60.de (same as with gnomedo, it was happening before i installed applet, so that shouldn't be the problem)
-sound (sometimes using Quod Libet as system player, it is integrated with this applet using inapp plugin)
-battery
-connection
-notifications
-custom weather applet v1.11.13
-calendar with date format: %a, %b %d %H:%M:%S
-user with name
-expo

Steps to reproduce: N/A
What's happening:
1. Panel does not detect hovering cursor above it, which means if it is hidden using intelli hide it won't appear when mouse cursor is nearby it, instead I have to minimize maximized window to see the panel
2. when panel appears on screen it still does not detect that mouse is at it, it means no tips after hovering above window list or tray, also while hovering above applets doesn't give that shine effect.
3. To fix it I have to click few times on any panel item until it starts reacting.

**Comment by Vahan86** [comment]
@DarekDeo, is this still an issue for you in Cinnamon 3.0?

**Comment by DarekDeo** [comment]
@Vahan86 no idea, I've switched my distro some time ago. If that's going to help, issue happend on Asus K53TK laptop (which I don't own anymore), it has AMD/Radeon APU, drivers were fglrx (the ones which are depraceted now).

I think if noone else reports it You can close it safely.

**Comment by Vahan86** [comment]
@DarekDeo, thanks a lot for reply.

In this case, can you please close this issue?
