### ISSUE TITLE
clock does hang and only update each minute

### ISSUE THREAD

**Issue by Hanmac** [linuxmint/Cinnamon#4588]
for unknown reason (i referenced to the reason) the clock in cinnamon only does update to full minute
so it does jump from 07:46:02 to 07:47:01 without updating each second as it should.

i already restart cinnamon but it didn’t help.
(date still does return the right time in the console)

My Settings: i dont use custom format, but i set in the Date & Time settings to show seconds

**Comment by Fjodor42** [comment]
I'm seeing this as well
