### ISSUE TITLE
Switching monitor mode with Fn+F7 (laptop) crashes Cinnamon

### ISSUE THREAD

**Issue by theoldfellow** [linuxmint/Cinnamon#4589]
Laptop running Mint 17.2. 

Connect powered-up Acer (4:3)  projector by VGA cable before boot.  Boot.  Displays correctly on both screens, although 4:3 screen has a horizontally compressed picture 16:9 -> 4:3.

*\* Scenario 1.
Press Fn-F7 to cycle dual monitor modes, Cinnamon crashes.  Restart fails.  Reboot required.
Unplug Acer projector, restart works ok, but Cinnamon crashes as soon as it is replugged.  

*\* Scenario 2.
Menu->Prefs->Display.  Select a 4:3 resolution and Mirror Monitors,  Apply.  All OK.

It appears that the built in facility to switch monitor modes is the culprit - but the failure is permanent until reboot.

**Comment by Vahan86** [comment]
@theoldfellow, is this still an issue for you with Cinnamon 3.2 (Mint 18.1)?

**Comment by theoldfellow** [comment]
No idea, I can't move to Mint 18 until I can find a better AMD R9 driver.  Stuck with 17.3.
Close it.
