### ISSUE TITLE
Menu grabbing focus from Alt-F2

### ISSUE THREAD

**Issue by dalcde** [linuxmint/cinnamon#4591]
Steps to reproduce:
1. Press Alt-F2 to launch Run dialog
2. Press the super button (or equivalent) to launch menu. Search field of box should now be focused
3. Type something (into the menu search box)
4. Alt-F2 can no longer regain focus and is stuck on the screen

**Comment by Vahan86** [comment]
The issue still exists in Cinnamon 3.0.7.

**Comment by Vahan86** [comment]
It seems to be fixed in Cinnamon 4.2.3
