### ISSUE TITLE
Power applet battery icon showing full incorrectly

### ISSUE THREAD

**Issue by rpbaptist** [linuxmint/Cinnamon#4592]
Described here: https://github.com/linuxmint/Cinnamon/issues/4519

Closed while the referred merge addresses another issue (something about time remaining not displaying)

I commented on these unjustified ticket closing without result so I am opening this ticket in hope that it will be fixed.

This problem does not exist in Cinnamon 2.4.

**Comment by bluethirdup** [comment]
![20](https://cloud.githubusercontent.com/assets/9600108/10284290/fa4f62de-6b8b-11e5-881e-1b914045dde7.png)

I can confirm that using the master brach did not fix it.

**Comment by pixunil** [comment]
Can you give additional information?
Please, give us the output of these two commands, it will show your detected batteries:
```
$ dbus-send --session --dest=org.cinnamon.SettingsDaemon --type=method_call --print-reply /org/cinnamon/SettingsDaemon/Power org.cinnamon.SettingsDaemon.Power.GetPrimaryDevice
$ dbus-send --session --dest=org.cinnamon.SettingsDaemon --type=method_call --print-reply /org/cinnamon/SettingsDaemon/Power org.cinnamon.SettingsDaemon.Power.GetDevices
```

Also, if you use a git / nightly version, on which commit do you built and _how_ do you built?

**Comment by rpbaptist** [comment]
```
dbus-send --session --dest=org.cinnamon.SettingsDaemon --type=method_call --print-reply /org/cinnamon/SettingsDaemon/Power org.cinnamon.SettingsDaemon.Power.GetDevices     
method return sender=:1.5 -> dest=:1.555 reply_serial=2
   array [
      struct {
         string "/org/freedesktop/UPower/devices/line_power_AC"
         uint32 1
         string ". GThemedIcon ac-adapter-symbolic ac-adapter "
         double 0
         uint32 0
         uint64 0
      }
      struct {
         string "/org/freedesktop/UPower/devices/battery_BAT0"
         uint32 2
         string ". GThemedIcon battery-full-symbolic gpm-battery-080 battery-full "
         double 87
         uint32 2
         uint64 18505
      }
   ]
```
```
dbus-send --session --dest=org.cinnamon.SettingsDaemon --type=method_call --print-reply /org/cinnamon/SettingsDaemon/Power org.cinnamon.SettingsDaemon.Power.GetPrimaryDevice
method return sender=:1.5 -> dest=:1.554 reply_serial=2
   struct {
      string "/org/freedesktop/UPower/devices/battery_BAT0"
      uint32 2
      string ". GThemedIcon battery-full-symbolic gpm-battery-080 battery-full "
      double 87
      uint32 2
      uint64 27748
   }
```

I simply copied the contents of the repo files from the latest tag and original 17.2 tag (2.6.0) from `files/usr/share/cinnamon/applets/power@cinnamon.org` to  `/usr/share/cinnamon/applets/power@cinnamon.org` on my laptop. I can't say I built anything. Other than that I am using all the official updates from the Mint 17.2 Update Manager.

**Comment by pixunil** [comment]
Yes, this should work, but keep in mind that it can be overwritten on update.
If you restart Cinnamon, and the bug still persists, there is something other involved than I fixed.

******

Does it have the same behaviour than last time?

- A not-full battery icon is shown
- Some seconds pass
- A full battery icon is shown (false)
- The state changes (AC plugged), correct icon shown

**Comment by hrvoojex** [comment]
I can confirm this too. 

![screenshot from 2015-10-12 21 36 21](https://cloud.githubusercontent.com/assets/11456950/10437035/b7ebf6a6-712a-11e5-8384-2a31abfd0736.png)

Those two command give me:
Error org.freedesktop.DBus.Error.ServiceUnknown: The name org.cinnamon.SettingsDaemon was not provided by any .service files

**Comment by bluethirdup** [comment]
`dbus-send --session --dest=org.cinnamon.SettingsDaemon --type=method_call --print-reply /org/cinnamon/SettingsDaemon/Power org.cinnamon.SettingsDaemon.Power.GetPrimaryDevice`

`method return sender=:1.6 -> dest=:1.56 reply_serial=2
    struct {
      string "/org/freedesktop/UPower/devices/battery_BAT0"
      uint32 2
      string ". GThemedIcon battery-full-symbolic gpm-battery-060 battery-full "
      double 68
      uint32 2
      uint64 5870 }`


`dbus-send --session --dest=org.cinnamon.SettingsDaemon --type=method_call --print-reply /org/cinnamon/SettingsDaemon/Power org.cinnamon.SettingsDaemon.Power.GetDevices`

`method return sender=:1.6 -> dest=:1.57 reply_serial=2
   array [
      struct {
         string "/org/freedesktop/UPower/devices/line_power_AC0"
         uint32 1
         string ". GThemedIcon ac-adapter-symbolic ac-adapter "
         double 0
         uint32 0
         uint64 0
      }
      struct {
         string "/org/freedesktop/UPower/devices/battery_BAT0"
         uint32 2
         string ". GThemedIcon battery-full-symbolic gpm-battery-060 battery-full "
         double 67
         uint32 2
         uint64 6291
      }
   ]`

this is the icon I have

![screenshot from 2015-10-14 22 56 16](https://cloud.githubusercontent.com/assets/9600108/10495885/d3c3b5b0-72c6-11e5-85db-afff22816cc9.png)

I copied this file over applet.js
https://github.com/linuxmint/Cinnamon/blob/ef60793faaf022c6189bbaaa8c13b3be74711e78/files/usr/share/cinnamon/applets/power%40cinnamon.org/applet.js

**Comment by pixunil** [comment]
It is expected that the battery icon has got only five states:

Name | Charge
:--:|----
`full` | more than two third
`good` | one to two third
`low` | lower than one third
`critical` | only some minutes left
`empty` | none

Don't confuse them with the `gpm-battery-{percentage}` part, it is the `battery-{state}(-symbolic)` part which is applied. So I don't see there an issue…

**Comment by bluethirdup** [comment]
I did not know that and I were actually waiting for an answer like this because the behaviour of the applet seemed consistent in itself the more i used it and with the info you have just given it is clear that it works as intended .So problem solved. Happy coding for all cinnamon contributers.

**Comment by sunnystormy** [comment]
Confirmed on Debian Stretch with 4.2.0 kernel running Cinnamon 2.6.13. The battery icon constantly switches between full and appropriate states, usually at one-to-two minute intervals.

**Comment by rpbaptist** [comment]
On the latest build it is working as designed. The problem was that it switched from low to full incorrectly. Over the last couple of days the behaviour is consistent. Thanks for the fix.

Cinnamon 2.8.4
