### ISSUE TITLE
Add 'Edit' or 'Properties' to Cinnamon main menu

### ISSUE THREAD

**Issue by ven-u** [linuxmint/Cinnamon#4593]
Often I want to investigate or run some menu item in a terminal.  Or perhaps I just want to know what the starting parameters are for a certain program.  But there no quick and easy way to do this. Using the kludgy Menu editor is definitely out--mainly because it has no 'Search' function so it takes forever to find a little-used app.

What I have to do now is
1. Right-click a menu item and select 'Add to Panel'
2. Right-click the new panel icon and select properties to discover the startup command
(3. Run the startup command in a terminal, edit it, test it, whatever)
(4. Use the menu editor to edit the original command, if nec)
5. Right-click the panel item again & delete it from the panel.

Seems like a long way around. Much easier would be to have a "Properties" or "Edit" function on the context menu for main menu items. As I recall, such a function is available in other desktops, even Windoze.

-Sadhu

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
