### ISSUE TITLE
Rubbish Bin - Property Error

### ISSUE THREAD

**Issue by struy1** [linuxmint/Cinnamon#4594]
When deleting something (in my case a folder) with sudo nemo where sudo is needed, an error occurs when trying to open the rubbish bin. When nemo then gets started without sudo, the object appears in the rubbish bin, but cannot be deleted. The folder must then be deleted via Terminal.

**Comment by pixunil** [comment]
Nemo issues should be handled at https://github.com/linuxmint/nemo/issues.
Afaik, the trash (or rubbish bin) is in `~/.local/share/Trash`, so it is at user-level, not in a system-wide.
For instance, you aren't able to move something from a network device to the trash, as there is no.
(Exceptions are sticks)

As there is no trash accessible as root, the error message shows up.

(Don't trust me fully, it is not real knowledge I just wrote, it's more thoughts and conclusions)

**Comment by ManIVIctorious** [comment]
Please move this issue to [linuxmint/nemo](https://github.com/linuxmint/nemo)
