### ISSUE TITLE
black screen sometimes when booting with lvm and encryption

### ISSUE THREAD

**Issue by mudongliang** [linuxmint/Cinnamon#4596]
Sometimes when I start my linuxmint 17.2 with Cinnamon, lvm and encryption, I can't get the password input box. It finally turns into black screen and can't go into cinnamon. Next time I reboot the computer, it comes back. It's strange.
I don't know what's the problem. Need Help!

**Comment by leigh123linux** [comment]
Well cinnamon has nothing to do with encryption so you will need to file your issue against whatever ubuntu package is responsible for the password input box.

**Comment by mudongliang** [comment]
OK.
