### ISSUE TITLE
cinnamon-settings-daemon has to be killed to repair printer notification messages

### ISSUE THREAD

**Issue by brub2** [linuxmint/Cinnamon#4597]
I have this issue on Mint 17.2 cinnamon 64 bit (up to date).

When you print, you have typically a first notification box followed by another one when the printing is finished. All this works very well after a fresh login, but for an unknown reason it stops after a while (typically after few days, I suspend/wake my computer and want my session back every day). 

As a workaround, I can repair these printer notifications if I kill the cinnamon-settings-daemon process, which is then automatically reloaded.

Maybe there is a better solution?

**Comment by leigh123linux** [comment]
Are you using USB or a network printer?

**Comment by brub2** [comment]
network (wired).

**Comment by brub2** [comment]
Can someone can at least confirm the issue, so it can be marked as a bug?

Since the printer tray icon is not working on Cinnamon (another issue), we must at least have print notification messages...

**Comment by Vahan86** [comment]
@brub2, is this still an issue for you in Cinnamon 3.0.x?

**Comment by brub2** [comment]
With my new printer (Brother), I don't have this issue anymore. The previous printer was an HP and had the issue (not sure of the cinnamon version last time I used it).
