### ISSUE TITLE
Alt tab not working properly

### ISSUE THREAD

**Issue by JustinSpedding** [linuxmint/Cinnamon#4598]
When I press alt-tab multiple times, using any of the themes, it creates multiple instances of the alt-tab interface on top of each other. When I click a window on the most recent alt-tab interface, it works. But, all of the others stop responding. I can only get out of them by clicking a panel a bunch of times.

The number of alt-tab instances should be limited to 1 and any subsequent presses of alt-tab should cycle through the windows instead of opening a new switcher.

I am using Cinnamon v2.6.13 on Linux Mint 17.2

**Comment by JustinSpedding** [comment]
It somehow fixed itself overnight. Issue resolved, I guess...

**Comment by akshayr-prax** [comment]
I still have this issue
