### ISSUE TITLE
Arrow keys do not work with the alt-tab window switcher

### ISSUE THREAD

**Issue by JustinSpedding** [linuxmint/Cinnamon#4599]
When I open the alt-tab window switcher, I expect the arrow keys to allow me to select different windows by pressing left/right. Instead, the arrows continue to affect the last window that was focused. I can see the arrow keys affecting that window within the preview. Please make it so that the arrow keys allow me to navigate through the windows in the alt-tab interface.

I am using Cinnamon v2.6.13 on Linux Mint 17.2

**Comment by dalcde** [comment]
Works as expected for me (classic icon + preview). What switcher are you using?

**Comment by JustinSpedding** [comment]
I was using Coverflow 3D. However, I just went to take a video of it, and it somehow fixed itself overnight. Issue resolved, I guess...
