### ISSUE TITLE
If you login too fast after suspend, the screen will lock again.

### ISSUE THREAD

**Issue by ledufff** [linuxmint/Cinnamon#4601]
I'm using Fedora 22/Cinnamon 2.6.13

**Comment by leigh123linux** [comment]
OK I suppose I could raise the password character limit to 30, that would slow you down.
Or you could type slower!

**Comment by ledufff** [comment]
I think I didn't make myself clear.

I don't login in a second, I just type my password right after the lockscreen is "properly" displayed (https://github.com/linuxmint/Cinnamon/issues/4457), that takes from 3 to 10 seconds. Typing my password can be like 3 or 5 seconds. That means that I'm pressing Send/Enter, 15~ seconds after having my laptop awake. I think that's enough time you don't think so?
I'm able to see my things, you know browser, or whatever I'm using, from 3 to 5 seconds, and then zap, Cinnamon will be locked again, asking me to type my password again.

I can off course wait like 30 seconds or a minute after waking up my laptop, I just thought this wasn't supposed to happen.

**Comment by stopal** [comment]
Yep! I discovered the same problem! although it happens really randomly.

**Comment by mbolivar** [comment]
This happens to me reliably with Cinnamon 3.0.5-1 on Arch.

**Comment by Vahan86** [comment]
@ledufff, is this issue still relevant to Cinnamon 3.2?

**Comment by Vahan86** [comment]
@JosephMcc, can we close the issue?
