### ISSUE TITLE
Move window without losing focus...

### ISSUE THREAD

**Issue by pstephenwille** [linuxmint/Cinnamon#4602]
With focus-follows mouse enabled, moving a window with the keyboard (Super+Shift+Arrow) to another monitor causes focus to fall where ever the mouse is.  This prevents me from resizing the newly moved window, or moving it to a third monitor.   What I have to do is:
1. move the window
2. move the mouse to give focus to the newly moved window.
3. reposition the window on the monitor
4. move mouse to give it focus.

Its awfully clunky.  The work flow should be:
1. Shift+Super+Left
2. Super+Up
The window is now on the other monitor, top half of screen, and it has focus.

I've been experimenting with xdotool to handle this.  One approach was to move the mouse to the window on top of the stack, but I don't seem to be able to bind to the Super key (Shift+Super).  Another thought was to disable the mouse and re-enable it on key release, so Super+Shift+release would restore the mouse.  Hopefully, this would allow focus to stay on the window while I'm moving it, until the keys were released.

**Comment by ManIVIctorious** [comment]
Same as #3244
