### ISSUE TITLE
Pop-up tips show at the upper left corner in a twinkling

### ISSUE THREAD

**Issue by Frederick888** [linuxmint/Cinnamon#4604]
![output](https://cloud.githubusercontent.com/assets/4507647/9711986/0b4dc4ae-557a-11e5-8a76-068bcce63571.gif)

I'm not sure how to reproduce the problem but it just happens from time to time. This problem influences all Cinnamon components here on my PC.

My PC features a Nvidia GTX560M graphics card and I'm running Cinnamon under Fedora with the official Nvidia driver.

**Comment by ledufff** [comment]
I have this issue too, Fedora 22, Intel HD Graphics 3000.

**Comment by Vahan86** [comment]
@Frederick888, is this still an issue for you in Cinnamon 3.2?

**Comment by JosephMcc** [comment]
I would be curious to here back from the original OP. This was a tricky issue that a good bit of time was put into trying to fix.
