### ISSUE TITLE
Screenshot not working properly, images with blue masks are saved

### ISSUE THREAD

**Issue by Frederick888** [linuxmint/Cinnamon#4605]
I'm not sure whether this is a dupe of #1468 , but it seems to be somehow different.

When taking screenshots of a certain area, the area will be covered by a blue mask as a visual effect, and the mask is often captured together with the screenshot.

For example, 
![screenshot from 2015-09-08 00-38-21](https://cloud.githubusercontent.com/assets/4507647/9720727/a3d5de0c-55c3-11e5-845c-1a531030aff9.png)

**Comment by rjanja** [comment]
I haven't seen that before. What screenshot tool are you using? Also what version of Cinnamon and which video driver and version are you running?

**Comment by Frederick888** [comment]
@rjanja I'm using Fedora which comes with GNOME so `gnome-screenshot` is used.

**Comment by ManIVIctorious** [comment]
Hm, no problem on Arch Linux with `gnome-screenshot-3.16.2` and `cinnamon-2.6.13`

<a href="http://de.tinypic.com?ref=65a4y8" target="_blank"><img src="http://i57.tinypic.com/65a4y8.png" border="0" alt="Image and video hosting by TinyPic"></a>

**Comment by Frederick888** [comment]
Oh, forgot to paste the version numbers...

I'm using Cinnamon 2.6.13 and the official Nvidia driver 352.41

**Comment by ManIVIctorious** [comment]
Driver issue sounds plausible, had a lot of problems with the official nvidia driver on my main machine. I'll try to reproduce there the next time I'm at home, will take about two weaks though...

**Comment by ManIVIctorious** [comment]
A bit late, just retried with gnome-screenshot-3.20.2 on Arch Linux, still not reproducible.
I also don't think that this is somehow related to cinnamon
Does this still occur on your setup with latest cinnamon 3.0.x?

**Comment by JosephMcc** [comment]
@ManIVIctorious your keeping me busy while I drink my morning coffee ;)

**Comment by ManIVIctorious** [comment]
Well, different time zones ;), I'll now take my evening meal, good day

**Comment by Vahan86** [comment]
@JosephMcc, can we close the issue?

**Comment by brain90** [comment]
Same problem here. Ubuntu 16.04 + gnome classic. 
Reproduce:
 ```
1. Press Shift + PrntScr button 
2.  Using the mouse, make some selection, 
3.  release the click button.
```
Screenshot successfuly made, but with covered mask.
 
![screenshot from 2017-03-16 17-21-31](https://cloud.githubusercontent.com/assets/858382/23991760/06896ff0-0a6d-11e7-8445-4e0999221cb3.png)

**Comment by Strum355** [comment]
I have this on two computers as well, a laptop and desktop, both with nvidia (gtx970, gtx1070 and gt940m). It doesnt happen all of the time, but often enough to be annoying. Cinnamon 3.6.7

**Comment by alberto2000** [comment]
I have this exact issue on Arch Linux, Gnome 3.28.2 with Wayland

**Comment by Strum355** [comment]
Changed to Antergos, have this issue again with Cinnamon 3.8.9 and gnome-screenshot 3.30.0

**Comment by sleeply4cat** [comment]
Have this issue on Cinnamon 3.6.7 and gnome-screenshot 3.25.0

**Comment by martin2250** [comment]
Same here with cinnamon 3.8.9-1 and gnome-screenshot 3.30.0-1, it doesn't happen all the time but at least 80%. Can we please reopen this issue?
