### ISSUE TITLE
Allow configuring "drag to top of the screen" action

### ISSUE THREAD

**Issue by mikkorantalainen** [linuxmint/Cinnamon#4607]
I have a high resolution screen and it seldom makes sense to fully maximize windows. However, because most windows contain text, vertically maximizing a window often still makes sense.

I suggest adding a configuration option for dragging a window to the top edge of the screen. Sensible options that I can think of are

1. Maximize (default)
2. Maximize vertically, keep the current window width
3. Maximize vertically and set width to 50% of the screen
4. Maximize horizontally and set height to 50% of the screen

I would personally prefer option 3 because I can already maximize vertically with a middle click on the title bar and maximize with double click on the title bar.

Option 3 would give an option to have have three 50% windows with minimal overlap when combined with the existing "drag window to the side edge of the screen" behavior.

**Comment by ManIVIctorious** [comment]
Options 1 and 4 already exist, to maximize vertically you can tile the window to the left or right side of the screen.
By the way you can already maximize a window vertically with keyboard shortcuts or by double clicking at the top or bottom window edge.

**Comment by mtwebster** [comment]
You can also double-click a window edge (where the mouse pointer changes to a resizer) and it will maximize only in that direction.  You can then freely position the window linearly along the non-maximized axis and it will remain maximized the other direction.

Option 1 and 4 are configurable in Settings->Tiling and Snapping (pick one or the other)

With all these cases covered, I don't really feel it's necessary to add more options to the drag-to-top action at this point.
