### ISSUE TITLE
Cinnamon Menu Configuration

### ISSUE THREAD

**Issue by gothicpreston** [linuxmint/Cinnamon#4608]
Could the cinnamon menu be enhanced to enable different configurations to be selected, taking some inspiration from the popular spices options for Windows 7, Whisker and Gnome Classic menu ideas?

This would benefit those in an environment where mixed IT hardware running different desktops causes some users to have issues with the different user interfaces. Allowing cinnamon to adopt a menu configuration which matches other systems in local use would mitigate/remove this perceived difference for casual users. This also applies to users with a different desktop in their employers workplace to their own domestic PC/laptop.

Whilst the cinnamon menu is technically superb, it is sometimes the small configuration details that make/break a users perception of the overall system and in this respect the menu is THE first interface point from which many users obtain their "first impression" of the cinnamon desktop.

I'm sure many of our current users have chosen one version of Mint to be "their" favorite, based to some degree upon the XFCE/Gnome/KDE/Whisker/Cinnamon menu being the most comfortable/efficient for their needs. Enabling the cinnamon menu to adopt other configurations may simplify user choice and gravitate more people to the primary desktop for Mint.

**Comment by JosephMcc** [comment]
This is part of the reason for the existence of Cinnamon spices and the availability of the 3rd party xlets. There are already several alternate menu options available on the spices site. Not sure if that really needs to be supported by cinnamon itself.
