### ISSUE TITLE
Incomplete translations in pkexec dialog for Nemo (and some other apps)

### ISSUE THREAD

**Issue by sveinki** [linuxmint/Cinnamon#4609]
In Linux Mint 17.2 “Rafaela” Cinnamon:

When launching Nemo as root, the login box is localized except for the title "Authentication is required to run Nemo as root". BTW this is also valid for Synaptic Package Manager, for which there is a bug in Ubuntu:
<https://bugs.launchpad.net/ubuntu-translations/+bug/1260484>

A quick look at the files in /usr/share/polkit-1/actions show that some files use direct call to gettext-domain:

For example in "org.cinnamon.settingsdaemon.datetimemechanism.policy":

`  <action id="org.cinnamon.settingsdaemon.datetimemechanism.configure">`
`    <description gettext-domain="cinnamon-settings-daemon">Change system time and date settings</description>`
`    <message gettext-domain="cinnamon-settings-daemon">To change time or date settings, you need to authenticate.</message>`

But in "org.nemo.root.policy" there's only:

`<action id="org.nemo.root">`
`   <description>Run Nemo with elevated privileges</description>`
`   <message>Authentication is required to run Nemo as root</message>`

Some of the other files in /usr/share/polkit-1/actions have also hardcoded strings just after the description/message, so that by adding:
`    <message xml:lang="is">Auðkenningar er krafist til að keyra Nemo skráastjórann sem kerfisstjóri</message> `
my pkexec dialog became fully translated to Icelandic. I could do the same for Synaptic and Gparted - but I guess this is only a temporary solution. 

Probably the correct way is to call the gettext-domain; thing is that while the Synaptic PO-file contains "Authentication is required to run the Synaptic Package Manager", the nemo.po does not include the above corresponding string.
Hardcoding those strings inside each of the .policy files for every language seems a bit cumbersome.

I know that the Synaptic bug is upstream, but I thought I'd report this at least for Nemo.

**Comment by sveinki** [comment]
Already had filed this as a bug in Launchpad:
https://bugs.launchpad.net/linuxmint/+bug/1494340

Sorry for the duplicate.

**Comment by sveinki** [comment]
little accident ;)

**Comment by JosephMcc** [comment]
This is a nemo issue, not a cinnamon one.
https://github.com/linuxmint/nemo
