### ISSUE TITLE
Cinnamon restart required on image edit

### ISSUE THREAD

**Issue by zagortenay333** [linuxmint/Cinnamon#4610]
It would be pretty awesome for themers if this nuisance could be solved.

When editing any images in cinnamon themes, you have to restart cinnamon to see changes.

This is quite annoying as I need to make hundreds of little tweaks on particular assets sometimes. Under gnome-shell 3.16 only a theme restart is required to update an image. I even made a gulpfile which uses this for autoreloading on changes (absolutely awesome to work with!):
https://github.com/zagortenay333/ciliora-tertia-shell/blob/dd4f75d127412d2fa6bc91ec5f704ac6ce26e127/Ciliora-Tertia/gnome-shell/gulpfile.js#L39-L43

**Comment by rjanja** [comment]
This would be the Cinnamon equivalent:
```
gsettings set org.cinnamon.theme name default
gsettings set org.cinnamon.theme name "Ciliora-Tertia"
```
You can also use `Alt+F2` and `rt` (reload theme)

**Comment by zagortenay333** [comment]
That's not what I'm talking about. The problem is that restarting the theme doesn't update the images. You have too restart cinnamon. In gnome-shell only a theme restart is enough.

**Comment by rjanja** [comment]
I just checked by installing your Ciliora-Tertia from repository.

For me, while running `gulp`, a change to the scss results in an immediate display change within Cinnamon, no restart required. I've so far tried background colors, background images and border images. Which version of Cinnamon are you running?

**Comment by zagortenay333** [comment]
The issue is when you edit an image, not the stylesheets. Open an image in Inkscape edit it, save, and then restart the theme only. The image won't change 'till you restart cinnamon.

**Comment by rjanja** [comment]
Oh, I see now.  Hmm.

**Comment by rjanja** [comment]
Good news - this is not a Cinnamon problem. Gulp is just not listening for changes to assets.

Compare your [Gnome Shell gulpfile.js](https://github.com/zagortenay333/ciliora-tertia-shell/blob/master/Ciliora-Tertia/gnome-shell/gulpfile.js#L63) to your [Cinnamon gulpfile.js](https://github.com/zagortenay333/ciliora-tertia-cinnamon/blob/master/Ciliora-Tertia/cinnamon/gulpfile.js#L60) and you will notice that your asset folders are missing from Gulp's watch list. Which means Gulp is never going to fire off the call to `gsettings` unless you also change CSS.

**Comment by zagortenay333** [comment]
Uff... you really aren't paying attention. I did that on purpose. There is no point in watching them if a theme restart cannot update them.

**Comment by rjanja** [comment]
Maybe something else is broken then because changes to the images take immediate effect once I set the theme via gsettings. I tried via gulp first because that's what you mentioned in your original issue description. It works fine for me. Good luck.

**Comment by zagortenay333** [comment]
Really? Hmm.

So ignore gulp for a moment. When you edit an image and go for _alt-f2_ + `rt` it updates the image?
What cinna verson are you on? I'm on `2.6.7`

**Comment by JosephMcc** [comment]
@zagortenay333 there is a little newer version of 2.6 available. It won't change the problem you're having though. I'm pretty sure the issue you have is actually the intentional behavior at the moment. It was done as an attempt to increase performance. Not sure if it actually makes any noticeable difference but this is now the second issue that's been raised that I believe it causes. I'll bring it up in IRC and see what the feeling about it is.

**Comment by zagortenay333** [comment]
Oh, OK. I hope it gets changed. It's a life-saver for theme makers.

**Comment by rjanja** [comment]
I'm on Cinnamon 2.4.8, and for me, changes to images already loaded into textures do not require restarting Cinnamon or even reloading the theme to take effect.

In 51942292a87b585d76402f6d0b6b1bd8d2081d9a, and starting with Cinnamon 2.6.0, @clefebvre disabled the filesystem monitoring of assets used by textures. This should probably be an option in Cinnamon Settings "General" tab though, even if it defaults to off, as I can see this being especially important for theme developers.

Regardless, if you have experience building Cinnamon, reverting this change should get you the desired behavior.

**Comment by zagortenay333** [comment]
Mmmm, I don't feel particularly comfortable building cinnamon. :/
Hopefully it's reverted. I mean, is the performance boost really that significant?

**Comment by JosephMcc** [comment]
@zagortenay333 The change that was giving you issues has been reverted for Cinnamon 3.0
