### ISSUE TITLE
Switching Between First and Last Workspace (Cycling Enabled) Makes Animation in Wrong Direction

### ISSUE THREAD

**Issue by zorbama** [linuxmint/Cinnamon#4613]
Setup:
* Linux Mint 17.2 32-bit
* Cinnamon 2.6.13

To Reproduce:
1. Turn on cycling through workspaces (Cinnamon Settings > Workspaces > Settings > Allow cycling through workspaces).
2. Leave one window open on the leftmost (first) workspace.
3. Switch one workspace to the left to get to the rightmost (last) workspace.

Expected Result:
The open window on the first workspace should be moved out of the screen to the right.

Actual Result:
The open window is moved to the left, as if the workspace switch was one workspace to the right, as demonstrated in [this video](https://youtu.be/keThQPD1T_Y).

**Comment by dalcde** [comment]
Well the workspace really *is* on the right. I am pretty sure this is a desgin decision.

**Comment by zorbama** [comment]
Perhaps, but I would say that this design decision should be changed, as this is very confusing. If something moves in a loop, it makes more sense that it will close the loop in the same direction as it opened it. This, I believe, gives better understanding of where you actually are in the space of your virtual desktops than having two animations at the same direction lead to two different desktops.

**Comment by JosephMcc** [comment]
I'm with @zorbama This probably should work differently then it does.

**Comment by mattst** [comment]
Using: Linux Mint 17 Qiana, Cinnamon 64-bit 2.2.16

I agree and opened a dupe. [Oops sorry JosephMcc.]

If you loop all the way through the workspaces going in one direction, it clearly looks wrong when moving from the last workspace to the first or visa-versa. In both cases all that needs changing is the direction of the slide effect - quite an easy fix I'd think.
