### ISSUE TITLE
Can't switch workspace after closing last Nemo window

### ISSUE THREAD

**Issue by SavoyRoad** [linuxmint/Cinnamon#4615]
Running Mint 17.2

So this seems to be a very specific issue.  Whenever the last open window in a workspace is a Nemo window and I close it (with either the keyboard or mouse), all of my keyboard shortcuts are disabled.  I can't switch workspaces with `Ctrl+Alt+Right/Left`, and I can't even get into a virtual console.

I've tried it out with any other program's window, and it only seems to be a problem with the file manager.  It only happens if Nemo is the last window to be closed.

**Comment by JosephMcc** [comment]
I tried to reproduce this. I have two workspaces and on the second one nemo is the only open window. I switch to that workspace, close nemo, and everything still works fine. Am I missing something to reproduce this?

**Comment by SavoyRoad** [comment]
I did some more trial and error, and it seems to be a problem when I choose not to show any desktop items.  With those disabled, the keyboard shortcut error begins, as well as being unable to right click.

**Comment by JosephMcc** [comment]
@SavoyRoad I tried that and still couldn't reproduce the problem. I'll play with it a bit more.

You can't right click because turning off "Show desktop icons" disables nemo from handling the desktop. Since the context menu is a nemo menu it's no longer accessible in that case.

**Comment by SavoyRoad** [comment]
Thank you for the info!
