### ISSUE TITLE
Network panel icon doesn't change when connected with VPNC

### ISSUE THREAD

**Issue by kevinclevenger** [linuxmint/Cinnamon#4616]
Connecting with OpenVPN does change the network panel icon to a lock, but for some reason connecting with VPNC doesn't change the icon at all.

RELEASE=2
CODENAME=betsy
EDITION="Cinnamon 64-bit"
DESCRIPTION="LMDE 2 Betsy"
All current updates

**Comment by JosephMcc** [comment]
https://github.com/linuxmint/Cinnamon/issues/3671
