### ISSUE TITLE
mint 17.2 cinnamon still has disappearing icons bug

### ISSUE THREAD

**Issue by stevedonato** [linuxmint/Cinnamon#4617]
Sept 13, 2015  and still this bug has not been resolved. It is intermittent.
 Cinnamon crashing is also still happening intermittently, (not related to missing Desktop icons).

**Comment by JosephMcc** [comment]
Could you be a bit more clear on what disappearing icons bug you're talking about?

**Comment by stevedonato** [comment]
Default cinnamon desktop icons (ie Computer) and any launcher icons added by the user. attached screen print is desktop missing system Computer Icon and many user Launchers that are on the desktop. I can send what it should look like by re booting if you would like to see it. I restarted cinnamon from the command line but it did not restore the launchers or the system Computer Icon.

**Comment by stevedonato** [comment]
Hi Joe,
        
        I replied on git hub and included screen print,  but did not see
        any way to say post the comment, and I hit 'Close' by mistake.
        
        The cinnamon system icons for  "Computer" , "Home" and "Trash"
        disappears along with an user added Launcher icons and any
        launchers added by having menu drop down select; add to desktop.
        icon launchers added to the panel however remain intact.  I
        restarted cinnamon via the command line but it did not restore
        the system icons or any user launchers
        
        I pasted my desktop screen prints here showing all desktop icon
        that were present and 2nd shot after it.. They only re appear if
        I reboot;
      
    
        I changed my wallpaper since the above screen print; below is
          the screen print with missing icons;
    
        Steve
      
    
    
    
    On 09/14/2015 04:54 PM, JosephMcc
      wrote:
    
    
      Could you be a bit more clear on what disappearing icons bug
        you're talking about?
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by kehugter** [comment]
Are you sure that it isn't Nemo crashing/being killed? In other words, does
`$ killall nemo`
reproduce your problem? Does opening Nemo fix it?

**Comment by JonathanMH** [comment]
I just had the same old fashioned icons, but running `killall nemo` and re-opening fixed it

**Comment by JosephMcc** [comment]
The desktop icons are handled by nemo. There were cases where changing settings in Cinnamon Settings->Desktop could cause Nemo to crash so the desktop icons would disappear. These have been improved. If the problem still persists with 3.0 pleas open an issue on the nemo github page.

**Comment by aitorbk** [comment]
It keeps happening, I have mint 18 and it still happens...

**Comment by kehugter** [comment]
@aitorbk 
> If the problem still persists with 3.0 please open an issue on the nemo github page
