### ISSUE TITLE
Nemo still stalls copying large files

### ISSUE THREAD

**Issue by stevedonato** [linuxmint/Cinnamon#4618]
How can a file copy program stall? Does anybody know why the "Stalled" message is displayed?
The most basic of functions, a simple file copy program (read a record, write a record)It is the most BASIC type of program. The program cannot stall, it must be something controlling it? NEMO?

**Comment by JosephMcc** [comment]
This is a nemo issue, not a cinnamon issue.
https://github.com/linuxmint/nemo
