### ISSUE TITLE
Overlay dialog in themes settings grabs global shortcuts

### ISSUE THREAD

**Issue by gadelat** [linuxmint/Cinnamon#4623]
System Settings -> Themes:

Press e.g. `<SUPER>`. Works.

Now click on some of the button on the right and press `<SUPER>` again. It doesn't work while this overlay is showed. Neither do work other shortcuts, like `ALT+TAB`, `PrtScr`, etc. It caused me complications while trying to take a screenshot for previous bug I reported.

**Comment by JosephMcc** [comment]
I don't think this is really a cinnamon bug but just how gtk menus work. Open any gtk application, gnome-terminal for instance, open a menu from the menubar and try using the <Super> key. It doesn't work.

**Comment by gadelat** [comment]
Yeah... you are right
