### ISSUE TITLE
[Feature Request] screensaver applet options in other applets

### ISSUE THREAD

**Issue by darekdeo** [linuxmint/Cinnamon#4624]
2.6 Cinnamon introduced new applet for screensaver which allows to disable system notifications and screensaver.

This is my personal feeling about it, I think that:
1. option to disable system notifications should be available in notification applet too.
2. option to disable screensaver should be available in power applet too.

If not by default, then at least as option to turn setting visibility on/off.
Would greatly appreciate.

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
