### ISSUE TITLE
Request: Sound events, please add "Restore Windows" Event Sound

### ISSUE THREAD

**Issue by spsf64** [linuxmint/Cinnamon#4628]
In sound effects there is no option for sound when restoring windows from minimized to its original state, this would be a nice addition.
TIA

**Comment by pixunil** [comment]
Currently, the sound effect of "Mapping windows" is used when unminimizing.
I think this goes nice with visual effects, as also the "map" effect is used (exception is effect `traditional`).

**Comment by spsf64** [comment]
@pixunil I dont see any "Mapping Windows" option?? Where to find it?
I am running cinnamon ver 2.6.13 in archlinux

**Comment by pixunil** [comment]
Sorry, I mistranslated the label. Correctly it is "Opening new windows" in _Settings_ > _Sound_ > _Effects_

![open-windows-sound-effect](https://cloud.githubusercontent.com/assets/7093655/9966623/33fdc616-5e3e-11e5-9eaa-2ef358636e99.png)

**Comment by spsf64** [comment]
@pixunil ah, ok, I have it thicked/enabled, however it just plays sounds when opening a new window, when restoring from minimized (unminimize as you said) there is sound at all
