### ISSUE TITLE
Request: Special theme for "medium DPI" screens

### ISSUE THREAD

**Issue by yesint** [linuxmint/Cinnamon#4632]
Cinnamon currently has an option for x2 UI scaling. This is perfect for QHD screens, but not for Full HD 13.3 with 1920x1080 resolution (which is common for many laptops). For such screens x1 scaling is too small and x2 is too large. x1.5 will be ideal but GTK can't do this as far as I know.

It is possible to solve the problem partially by setting font scaling to 1.8-1.9 but this does not scale checkboxes, radio buttons, scrollbars and various icons - they all remain too small.

My suggestion is to provide a special variant of the default theme for such screens where all icons, bitmaps and controls are 1.5 larger. What need to be increased:
- Bitmaps for checkboxes and radiobuttons
- Scrollbars and sliders
- Toolbar icons from 16x16 to 24x24.
- Icons in treeview and such.

Unfortunately my knowledge of GTK themes is clearly not enough to do this but this task is easy for any theme developer.

**Comment by dalcde** [comment]
#3455
