### ISSUE TITLE
Wrong icon background in LibreOffice 5

### ISSUE THREAD

**Issue by yesint** [linuxmint/Cinnamon#4633]
![screenshot from 2015-09-20 12 07 19](https://cloud.githubusercontent.com/assets/14368585/9979993/ca70add6-5f90-11e5-872c-6147fe694b16.png)
Some icons in the LibreOffice 5 are displayed with weird blue background in Cinnamon. The problem is not present in Xfce with the same version of LibreOffice. 
It seems to be connected with screen DPI and font size - the problem disappears when I set font scaling to 1 but appears for scaling >1.6. 
Observed for all available LO icon themes but for different icons.

**Comment by ManIVIctorious** [comment]
I can't reproduce this with cinnamon 3.0.7 and libreoffice 5.2.0 on Arch Linux. Is this still an issue for you with the latest cinnamon/libreoffice packages?

**Comment by Vahan86** [comment]
@JosephMcc, can we close this issue?
