### ISSUE TITLE
for some desklets, highlight button highlights a random "applet" instead

### ISSUE THREAD

**Issue by hyOzd** [linuxmint/Cinnamon#4634]
When I click the "Highlight" button in the configuration dialog of a desklet, a seemingly random applet is highlighted. Desklet itself is not highlighted.

Cinnamon 2.6.13

I've reproduced this issue with two different desklets;

* Weather Desklet bbcwx@oak-wood.co.uk
* Clock Desklet clock@cinnamon.org

These desklets that I tried didn't have the same issue (highlight worked correctly);

* Digital photo frame photoframe@cinnamon.org
* Desktop Calculator calculator@scollings

**Comment by rjanja** [comment]
Confirmed - *instance ID* is not unique across applets and desklets. One solution is to change the dbus signatures for `activateCallback` and `highlightApplet` to accept an xlet type and use that to highlight the right thing. But I think it might be better to change these signatures and `appletManager.js` and `deskletManager.js` to use *UUID* and *instance ID* both, and get rid of the arbitrary *id*.

**Comment by rjanja** [comment]
I've submitted a pull request that resolves this problem.

To reproduce:
```
gsettings set org.cinnamon next-desklet-id 0
```
Then add a desklet to the desktop, configure it, and click "Highlight".
