### ISSUE TITLE
New css classes for alt-tab switcher

### ISSUE THREAD

**Issue by zagortenay333** [linuxmint/Cinnamon#4636]
I think adding a few new classes rather than reusing existing ones wouldn't be bad. I want to be able to style the box with the icons independently from the box holding the thumbnails and the window caption in the _coverflow_ and _timeline  modes_.  Example:
![workspace 2_002](https://cloud.githubusercontent.com/assets/11144630/9982238/60781ff0-5fd5-11e5-9909-d9a7e23d57ef.png)
![workspace 2_004](https://cloud.githubusercontent.com/assets/11144630/9982241/69c0c4d6-5fd5-11e5-88e3-53caa8ae2a37.png)

I  can do it already, but the code is absurd: https://github.com/zagortenay333/ciliora-tertia-cinnamon/blob/a6b472447aecc62fa9f076288637110d7470076d/Ciliora-Tertia/cinnamon/sass/main-modules/_alt-tab.scss#L10-L58

I'm selecting them based off of how many pseudo-classes they have..

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
