### ISSUE TITLE
Shaded windows get stuck shaded after changing desktops

### ISSUE THREAD

**Issue by kevinclevenger** [linuxmint/Cinnamon#4638]
I have my windows set to shade/unshade on titlebar double mouse click. This works correctly when staying on a single virtual desktop. But after shading an application, changing to any other desktop, returning to the desktop with the shaded application, and then double mouse clicking the shaded window titlebar there's no response at all from the window. You also can't move the shaded window titlebar around on that desktop.

The only way to recover the shaded application is to Alt-tab (or whatever the user has it set to) to the application, which will unshade and restore it.

RELEASE=2
CODENAME=betsy
EDITION="Cinnamon 64-bit"
DESCRIPTION="LMDE 2 Betsy"

**Comment by JosephMcc** [comment]
I can reproduce this on Mint 17.2 with the latest cinnamon nightly builds as well.

**Comment by Fjodor42** [comment]
Incidentally, this used to be the case for me on Ubuntu 14.04 with nightly packages, but seemed to stop some time last week - YMMV.

**Comment by gerow** [comment]
I can produce this issue using cinnamon 2.6.13 as well. Video displaying the issue here <https://www.youtube.com/watch?v=QTXStw-c4Ys>.

**Comment by paulharris** [comment]
+1

**Comment by micahkwillard** [comment]
Reproduced on Mint 17.3 with cinnamon 2.8.6
