### ISSUE TITLE
Screenshots don't save to symlinked Pictures folder

### ISSUE THREAD

**Issue by bruce2409** [linuxmint/Cinnamon#4639]
In Cinnamon 2.6.13 in Mint 17.2, if you take a screenshot using the Print Screen button and have your Pictures folder symlinked to a different location, Cinnamon doesn't save the screenshots in the symlinked folder, but rather in the root home folder for the user. This is the same as the behaviour when you don't have a Pictures folder in place.

Permissions on the folder and soft symlink are correct and normal data can be written to the folder, but Cinnamon doesn't seem to acknowledge its existence.

**Comment by leigh123linux** [comment]
Well cinnamon doesn't have any part in taking screenshots so close this report and file one against gnome-screenshot instead.

**Comment by ManIVIctorious** [comment]
This is obviously no cinnamon issue, could you please close it?
