### ISSUE TITLE
PlacesManager (or allowing to choose which volumes we do want automounted - or Security flaw)

### ISSUE THREAD

**Issue by Meistache** [linuxmint/Cinnamon#4647]
Hi there mateys!

In before anything: I'm running Arch Linux x64, Cinnamon 2.6.13, 4.1.6-1 kernel, no crypt hooks for CPIO.

I've just made a test filesystem using dm-crypt/cryptsetup and it's all good. I didn't want to mount it on startup (because, well, it's supposed to require a password and being requested), however Cinnamon is doing this since I restarted it.

This is my crypttab and fstab. No inclusion. I did nothing about it.

    root@darksol ~]# cat /etc/crypttab 
    # crypttab: mappings for encrypted partitions
    #
    # Each mapped device will be created in /dev/mapper, so your /etc/fstab
    # should use the /dev/mapper/<name> paths for encrypted devices.
    #
    # The Arch specific syntax has been deprecated, see crypttab(5) for the
    # new supported syntax.
    #
    # NOTE: Do not list your root (/) partition here, it must be set up
    #       beforehand by the initramfs (/etc/mkinitcpio.conf).
    
    # <name>       <device>                                     <password>              <options>
    # home         UUID=b8ad5c18-f445-495d-9095-c9ec4f9d2f37    /etc/mypassword1
    # data1        /dev/sda3                                    /etc/mypassword2
    # data2        /dev/sda5                                    /etc/cryptfs.key
    # swap         /dev/sdx4                                    /dev/urandom            swap,cipher=aes-cbc-essiv:sha256,size=256
    # vol          /dev/sdb7                                    none
    [root@darksol ~]# cat /etc/fstab 
    # UUID=dbc726d2-05b9-416f-806d-30d464196a1c
    /dev/mapper/linuxvg-arch_root_lv	/         	ext4      	rw,relatime,data=ordered	0 1
    
    # UUID=a63436fe-fa6b-480b-a94a-883c4b2a59e8
    /dev/mapper/linuxvg-arch_usr_lv	/usr      	ext4      	rw,relatime,data=ordered	0 2
    
    # UUID=d19aa437-d73f-4d61-a8f2-66126768c36a
    /dev/mapper/linuxvg-opt_lv	/opt      	ext4      	rw,relatime,data=ordered	0 2
    
    # UUID=4bb50d46-c92b-4298-8aea-169c11fa3566
    /dev/mapper/linuxvg-home_lv	/home     	ext4      	rw,relatime,data=ordered	0 2
    
    # UUID=bb02e9a7-4da3-41ff-acbe-e92b5d8f177a
    /dev/sda2           	none      	swap      	defaults  	0 0

And so this is a peek at ~/.cinnamon (for my user of course) and glass.log.last

  

      [root@darksol .cinnamon]# cat glass.log.last 
        info t=2015-09-22T16:36:08.840Z Cinnamon.AppSystem.get_default() started in 23 ms
        info t=2015-09-22T16:36:16.790Z loading user theme: /home/meistache/.themes/Manjaro Maia Plasma 5/cinnamon/cinnamon.css
        info t=2015-09-22T16:36:16.822Z added icon directory: /home/meistache/.themes/Manjaro Maia Plasma 5/cinnamon
        info t=2015-09-22T16:36:16.922Z PlacesManager: Updating devices
        info t=2015-09-22T16:36:17.000Z loaded at Tue Sep 22 2015 13:36:17 GMT-0300 (BRT)
        info t=2015-09-22T16:36:17.523Z Loaded applet menu@cinnamon.org in 522 ms
        info t=2015-09-22T16:36:17.529Z Role locked: windowlist
        info t=2015-09-22T16:36:17.529Z Loaded applet window-list@cinnamon.org in 6 ms
        info t=2015-09-22T16:36:42.544Z Loaded applet calendar@cinnamon.org in 25013 ms
        info t=2015-09-22T16:36:42.549Z Loaded applet workspace-switcher@cinnamon.org in 5 ms
        info t=2015-09-22T16:36:42.555Z Loaded applet windows-quick-list@cinnamon.org in 6 ms
        [root@darksol .cinnamon]# pwd
    /home/meistache/.cinnamon
        [root@darksol .cinnamon]# 

It looks like it's something coded on Cinnamon engine for the PlacesManager method in which I may never ever be able to manage as user/superuser. I do need to report this as a feature request to Cinnamon since:
1) Loading encrypted volumes DO delay startup
2) Loading encrypted volumes without requesting my passphrase is a HUGE security flaw
3) Loading encrypted volumes... just no I want them hid till I want them files.
4) Ok I just need to know how things work too if I want to contribute sometime :)

So that's it. Thanks in advance!

**Comment by leigh123linux** [comment]
Cinnamon isn't to blame, please close and report it against whatever package your distro uses for encrypted partitions!
