### ISSUE TITLE
[taskbar] Windows moved to a different monitor get moved to the end of the list

### ISSUE THREAD

**Issue by margamanterola** [linuxmint/Cinnamon#4648]
This bug started happening to me when I moved from cinnamon 2.2 to cinnamon 2.6, I believe it's related to the fact that there can now be per-monitor panels and each with its own window list.

What happens is that when using two monitors **but only one panel**, dragging a window from one monitor to the other, causes the entry in the window list applet to be moved to the end.

Moving it back to the first monitor does not restore the original position. It doesn't matter from which monitor to which monitor the window is getting moved, it always goes to the end of the window list. This is 100% reproducible, for many users.

**Comment by jrial** [comment]
Also happens when connecting/disconnecting external monitors. This reorders the entire window list.

**Comment by Vahan86** [comment]
@margamanterola, is this still an issue for you with Cinnamon 3.2?

**Comment by margamanterola** [comment]
No, doesn't happen with Cinnamon 3.2.
