### ISSUE TITLE
 Code injection in cinnamon-settings-users.py

### ISSUE THREAD

**Issue by TheRegRunner** [linuxmint/Cinnamon#4649]
https://bugs.launchpad.net/linuxmint/+bug/1499056

![edit group name](https://cloud.githubusercontent.com/assets/13422603/10057577/403102f2-6241-11e5-863d-7527a8afcadb.png)

If you edit a group name or add a new group , the edit field allows to inject shell commands with root permissions.
If the administrator types in the character ";" into the group name field , the text behind the";" will be executed as root.

File :
cinnamon-settings-users.py

Functions :
on_group_addition
on_group_edition

**Comment by TheRegRunner** [comment]
use subprocess to fix shell injections, no os.system() call please.

To also fix group names like this

mail$(thunderbird)

or this group name

list&gedit

**Comment by lestcape** [comment]
+1

**Comment by clefebvre** [comment]
https://github.com/linuxmint/Cinnamon/commit/5aadb1b2b5970d572ef895ce9ab60950d8e87dc4
