### ISSUE TITLE
[Request] Optimize png files

### ISSUE THREAD

**Issue by VolMi** [linuxmint/Cinnamon#4653]
This is for Cinnamon 2.6 in Debian testing.

I noticed that Cinnamon's png files are not optimized for size:

    $ find /usr/share/cinnamo* -name '*.png' -exec cp '{}' . \;   # copy all pngs to current (empty) directory
    $ du -hs                       # get size of all files in current directory
    3,0M	.
    $ optipng *.png                # optimize all png files
    $ du -hs
    2,8M	.                      # 7% less

This is not huge but it should not hurt to go for minimal size, no?

**Comment by JosephMcc** [comment]
Thats a tiny improvement. Not sure if it's worth the effort. That being said if someone makes a PR to do it, I doubt it would be turned down.
