### ISSUE TITLE
CurrentTime used to focus window

### ISSUE THREAD

**Issue by iplayfast** [linuxmint/Cinnamon#4654]
After running
    cinnamon --replace
in a terminal and keeping the terminal open I noticed I was getting a lot of 
Window manager warning: CurrentTime used to choose focus window; focus window may not be correct.
Window manager warning: Got a request to focus 0x3e4615f (chris@shop) with a timestamp of 0.  This shouldn't happen!
Window manager warning: CurrentTime used to choose focus window; focus window may not be correct.
Window manager warning: Got a request to focus 0x3600001 (Forge of E) with a timestamp of 0.  This shouldn't happen!
Window manager warning: CurrentTime used to choose focus window; focus window may not be correct.
Window manager warning: Got a request to focus 0x3e4615f (chris@shop) with a timestamp of 0.  This shouldn't happen!
Window manager warning: CurrentTime used to choose focus window; focus window may not be correct.
Window manager warning: Got a request to focus 0x4000005 (cqsmain.cp) with a timestamp of 0.  This shouldn't happen!
Window manager warning: CurrentTime used to choose focus window; focus window may not be correct.
Window manager warning: Got a request to focus 0x3646501 (Issues · ) with a timestamp of 0.  This shouldn't happen!

This might be something to do with the meta freezing bug, I don't know. But thought it should be fixed in any case. If any diagnostics are needed let me know and I'll try to comply.

**Comment by iplayfast** [comment]
Just realized that the warning is a bit of a red herring. The addresses given are just programs that are running and have nothing to do with the window manager.

**Comment by Vahan86** [comment]
@iplayfast, is this still an issue for you in Cinnamon 3?

**Comment by Vahan86** [comment]
@JosephMcc, can we close this issue?
