### ISSUE TITLE
Desklet stylesheet applied to whole cinnamon

### ISSUE THREAD

**Issue by hyOzd** [linuxmint/Cinnamon#4655]
I used `*` selector in a desklet stylesheet to keep things simple. Like this;

    * {
         color : #5fbbdf;
    }

Turns out this is applied to whole cinnamon. Applets, panels, desklets... I was expecting a desklet stylesheet to be only applied to that desklet's components. Am I wrong? Or is this a bug?

**Comment by JosephMcc** [comment]
I doesn't work that way. Using "*" means apply that style to everything. Think of the xlet style sheet as just being added to your current cinnamon theme. You need to use the specific style classes used by the xlet.

**Comment by hyOzd** [comment]
Ok, thanks for clarification.
