### ISSUE TITLE
Implement some ExtensionUtils.getCurrentExtension()

### ISSUE THREAD

**Issue by Keruspe** [linuxmint/Cinnamon#4656]
While porting an extension from gnome-shell to cinnamon, a lot of code can be reused (at least for applets), only some boilerplate require changes.
It's currently not possible for the ones split into several files as they all use gnome-shell provided ExtensionUtils.getCurrentExtension() to import other files from the same extension.

Implementing this would facilitate compatibility a lot.

**Comment by lestcape** [comment]
I think you can implement this function and then use it where you want. Also you can wrap St, and others libraries to use the gnome shell style... Then, will be only really a little changes, but the idea of cinnamon is not keep the compatibility is just the opposite, is do the things different, and improve whatever need to be improved without need to keep compatibility with a different conception of a product. This will be an additional charge. so why?

**Comment by pixunil** [comment]
If you look for a function to import files, look at [#4537](https://github.com/linuxmint/Cinnamon/pull/4537#issue-102391191) for a possibility.
The currently supported and safe method is getting one of these, depending on your xlet type:
```javascript
let files = imports.ui.appletManager.applets[uuid];
let files = imports.ui.deskletManager.desklets[uuid];
let files = imports.ui.extensionSystem.extension[uuid];
```

It will return an import object, similar to `imports`, but pointng to your xlet directory.
As you can see, you'll need to pass the `uuid`.

**Comment by Keruspe** [comment]
I already considered those two ideas.

To sum things up: I have a gnome-shell extension, divided in something like 10 files.

Only two things are incompatible with cinnamon: one file that I want to make conditional and replace by a cinnamon one for cinnamon, and the call to ExtensionUtils.getCurrenExtension that I do in every single one of these files.

It's a pity that I'd have to copy and duplicate all these hundreds of lines of code just to change *one* import.

One alternate solution could be

```
const Me = imports.ui.ExtensionUtils.getCurrentExtension() || imports.ui.extensionSystem.extension[uuid];
```

But last time I checked it just aborted everything because ExtensionUtils doesn't exist.

Forcing people to duplicate a lot of code for this single helper utility just because "we don't want to be compatible" when a *lot* of other stuff is actually compatible is really sad...

**Comment by lestcape** [comment]
@Keruspe, you can easy check if a function exist:
```
var ext = null;
if (imports.ui.ExtensionUtils)
    ext = imports.ui.ExtensionUtils.getCurrentExtension();
else if (imports.ui.extensionSystem)
    ext = imports.ui.extensionSystem.extension[uuid];
const Me = ext;
```
Also, maybe this a problem that you have currently, but be sure there are a lot of changes in st and others interfaces between cinnamon and gnome shell. So, is really a lot of changes if you want to be general and this is a lot of work.

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
