### ISSUE TITLE
ALT-TAB Stuck when running fullscreen game with fglrx driver

### ISSUE THREAD

**Issue by Lukypie** [linuxmint/cinnamon#4657]
Noticed this after installed the Catalyst-Test driver on ArchLinux in team fortress 2, I can't move anything after pressing alt-tab it's all frozen.

**Comment by Lukypie** [comment]
Some updates, the problem persists in ubuntu 15.10 but I've noticed that you can hover the mouse on it and switch anyway, but, at example, it does not work in other games such as sanctum where you don't have a cursor.

**Comment by Lukypie** [comment]
https://www.mediafire.com/?zjfxngvqulu6qsx

I've also made a video showing the bug.

**Comment by Vahan86** [comment]
@Lukypie, is this still an issue for you with Cinnamon 3.6?

**Comment by Vahan86** [comment]
@icarter09, since there is no response from OP, can we close this issue?
