### ISSUE TITLE
Hiden Docky on LMDE gives a red tint above the place where it is when unhiden

### ISSUE THREAD

**Issue by Filidrag** [linuxmint/Cinnamon#4659]
I'm using LMDE 2 64-bit. If I use Docky and enable any form of hiding the dock (doesn't matter if it's autohide or intellihide), whenever the dock is hidden, a line that seems to be equal in height to the height of the dock itself, and as wide as the screen will appear. Everything displayed across that line has a red tint to it. It is a constant issue, and I noticed that there reports of this happening from people that upgraded from Debian 7.8 to 8.x. On the Ubuntu-based variant of Mint this doesn't happen. I have personally observed this on Cinnamon 2.6

**Comment by Vahan86** [comment]
@Filidrag, is this still an issue for you in Cinnamon 3?

**Comment by Vahan86** [comment]
@JosephMcc, can we close the issue?
