### ISSUE TITLE
Sound applet should switch to bluetooth audio when enabled.

### ISSUE THREAD

**Issue by dest4131** [linuxmint/Cinnamon#4660]
Dear community,
I'd like to report the following behavior of the sound applet which could be improved:
- fresh boot of the laptop
- I set bluetooth on, and connect external speakers.
- the cinnamon sound applet is set on the internal speakers, but the audio goes to the external speakers,
- changing the volume has no effect: you first have to change the audio out device in the sound applet menu. this can lead to nasty effects like waking up the whole neighborhood.

It would be better if the sound applet switched to "bluetooth out" when bluetooth connects, or in general if the applet displayed more reliably the current audio output device.
I'd like to know if this behavior can be reproduced on other machines.

system: LMDE 2

**Comment by ManIVIctorious** [comment]
The audio settings have seen a lot of work since cinnamon 2.6. Does this issue still occur in cinnamon 3.0?

**Comment by Vahan86** [comment]
@JosephMcc, can we close the issue?
