### ISSUE TITLE
rdesktop full screen underneath bottom panel

### ISSUE THREAD

**Issue by shnplr** [linuxmint/Cinnamon#4662]
rdesktop window with "-g 100%%" sits underneath the bottom panel hiding the bottom panel on remote system.  Preferred behaviour is as per maximize any window.

This may not have occurred in cinnamon 1.8.x

Since window cannot be resized my current workaround is to toggle auto hide panel

LM 17.2 64bit
Cinnamon 2.6.13 (Mint-X)
rdesktop 1.7.1-1ubuntu2
Monitors: 1
Linux 3.13.0-57-generic

**Comment by shnplr** [comment]
also with "-f" option the screen is positioned over the bottom panel, however the panel did not appear (using auto hide) and I was unable to minimize windows via cmd-D key.  Other function keys responded to the remote system.  Could not alt-tab to any other window.  I ended up having to ctrl-alt-backspace to restart the desktop. When I alt-tabbed the windows showed but I couldn't select them. Using cmd-D the panel actually appears but clicking on panel shortcut didn't start the app, nor did right-clicking + close on the rdesktop (window list)

**Comment by Vahan86** [comment]
@shnplr, is this still an issue for you in Cinnamon 3?

**Comment by Vahan86** [comment]
@JosephMcc, can we close the issue?
