### ISSUE TITLE
[taskbar] [feature request] Permanent state change for window attention

### ISSUE THREAD

**Issue by RalfJung** [linuxmint/Cinnamon#4664]
When a window demand attention, its taskbar entry flashes a few times. However, that's easy to miss - either because the user is currently focused on some other part of the screen, or because the user left the PC for a short while.
It would hence be desirable to the attention indicator not to vanish silently. For example, the taskbar entry could stay in that "red" state until the window actually has focus again. This way, the user is much less likely to miss windows needing attention.

**Comment by JosephMcc** [comment]
Some apps already do this. For example, in Hexchat, it does stay red until I focus the window. Not sure what exactly controls that.

**Comment by mtwebster** [comment]
This is fixed already in Cinnamon master: https://github.com/linuxmint/Cinnamon/commit/bd788ff20c9a41793ea4cf386988111129341e33

**Comment by RalfJung** [comment]
That's great, thanks :)
