### ISSUE TITLE
Confusing interpaly between "removable devices" and network shares

### ISSUE THREAD

**Issue by RalfJung** [linuxmint/cinnamon#4665]
After accessing a network share (sftp://some.server/folder) via Nemo, confusingly, the "Removable Devices" icon in the systray appears. My network share is not a "device", so something about this UI is not quite right.

**Comment by pixunil** [comment]
Both removable drives and network shares are "mountable" and the applet handles both the same way.
I think it should be divided into sections (like in nemo) "Network" and "Devices"-

**Comment by RalfJung** [comment]
Yes, and maybe the widget should then be renamed from "Removable Devices" to "Removable Folders" or "Mounted ???" or something like that.

I understand the technical reason for this behavior. I am just saying, from a user perspective, something is wrong here.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
