### ISSUE TITLE
Network Manager menu: Current network sometimes shown twice, with a white box

### ISSUE THREAD

**Issue by RalfJung** [linuxmint/Cinnamon#4666]
The network menu sometimes shows the current network (or the network it currently attempts to connect to) twice in the list, together with a strange white square instead of the link quality for the first entry.

See the following screenshot:
![network](https://cloud.githubusercontent.com/assets/330628/10192686/6df937b2-677e-11e5-91a8-06f4e1467916.png)
(the name, "wlan-XXX", is the same in the first two rows)

This is not reproducible, but it happens frequently for me.

**Comment by dalcde** [comment]
occurs to me sometimes as well

**Comment by RalfJung** [comment]
I also just had a situation in which the WiFi network I was connected to did not show up at all in the list.

**Comment by Vahan86** [comment]
@JosephMcc, I think this issue is related to network-manager-applet and should be moved to this repository: https://github.com/linuxmint/network-manager-applet/issues

**Comment by Vahan86** [comment]
@RalfJung, does this issue still occur in Cinnamon 3.0?

**Comment by RalfJung** [comment]
I am not using CInnamon any more, so I can't tell -- sorry.
