### ISSUE TITLE
Triggering "Show Desktop" and un-triggering it does not preserve window order

### ISSUE THREAD

**Issue by RalfJung** [linuxmint/Cinnamon#4667]
I have Super+D set up to be the hotkey for showing the desktop. I would expect that hitting Super+D twice will restore the window order that I started with. That is however not always the case.

I can reproduce this by having the Cinnamon system settings as the topmost window: If I now do Super+D twice, system settings moved "one layer down" the stack, it's the second-topmost window now. It should, instead, remain the topmost window.

**Comment by mtwebster** [comment]
Fixed in muffin master: https://github.com/linuxmint/muffin/commit/8bdd4252b8e0b736c82a9bb0896bcb7d16964de2
