### ISSUE TITLE
Menu cut off with HiDPI on

### ISSUE THREAD

**Issue by grenzor** [linuxmint/Cinnamon#4668]
With HiDPI enabled the top of the menu, ~2-3cms are cut off (i.e. the search bar and a bit below are completely not able to be seen). Without HiDPI Menu is fine to see.

**Comment by JosephMcc** [comment]
What is the screen resolution?

**Comment by grenzor** [comment]
1920x1080

**Comment by JosephMcc** [comment]
I don't believe that resolution is considered HiDPI. The menu isn't really designed to work when using 2x scaling on a normal dpi screen. It would probably need to be redesigned to work in that situation.

**Comment by utack** [comment]
Can reproduce this.
However having a display with "virtual" 960x540 pixels is tiny, cinnamon is not designed for that.
Just bump the font size and the panel size up?

**Comment by alff0x1f** [comment]
@JosephMcc I use asus zenbook ux32ln (1920x1080 and 13.3' screen). Without HiDPI mode all elements looks tiny, so I turn hiPDI mode and decrease fonts to 0.75

    gsettings set org.cinnamon.desktop.interface scaling-factor "uint32 2"
    gsettings set org.cinnamon.desktop.interface text-scaling-factor "0.75"
    gsettings set org.cinnamon active-display-scale "2"

So UI normal now, but menu is too tall. (It'n not critical for me at all, I just turn off couple Menu Item in menu editor). I just notice this issue now and write it for clear situation.

![screenshot from 2015-11-06 19 41 23](https://cloud.githubusercontent.com/assets/3997330/10999552/8b4891e8-84be-11e5-963e-a900810a207a.png)

**Comment by mtwebster** [comment]
You definitely shouldn't be using hidpi mode.  Try turning it off, and instead increasing the font sizes and panel heights.

**Comment by grenzor** [comment]
What do you mean I shouldn't be using HiDPI? Everything else is the perfect size/height except the menu. Surely there's a way to fix it or at least a way for us to modify it.

**Comment by JosephMcc** [comment]
If you disable showing a couple categories like Places and Recent Files it will probably fit. 

Running a 1080p screen in HiDPI gives you an effective resolution of 960x540 which doesn't even meet Cinnamons minimum system requirements.

**Comment by alff0x1f** [comment]
@mtwebster thanks! I turn off highDPI mode, increase fonts to 1.5, increase height menu panel and now all looks even much better (in hidpi mode some elements was little bigger than I need, reason why I use this mode - first time I did't find panel height settings.)

![screenshot from 2015-11-12 11 23 09](https://cloud.githubusercontent.com/assets/3997330/11111928/c533209c-892f-11e5-840e-1eed4c12e928.png)

P.S. Now search input size too small for text. Should I open issue?

**Comment by trentks** [comment]
Sorry to reopen this issue, but the search bar as pictured by  alff0x1f doesn't scale its height with the text scaling factor leading to the text getting cut off. 

Hi-DPI is suboptimal for the reasons mentioned (menu getting cut off), but this font-scaling presents this issue still. I use a 1080p TV, and as such, some scaling is required.

**Comment by JosephMcc** [comment]
@trentks could you open a new issue for that. It's a different problem really. That way you can also provide the info in the issue template.
