### ISSUE TITLE
[Regression] Slow MDM to Cinnamon 2.6.13 transition and wrong icons in Nemo

### ISSUE THREAD

**Issue by MarceloRuiz** [linuxmint/Cinnamon#4669]
After entering password in MDM Cinnamon takes 35+ seconds to show up. This is a problem that appeared a couple of days ago (it used to take 6+ seconds).
On top of that, Nemo is not showing the right Icons (configured under themes).
If I logout and login again, everything works fine. Right icons are shown.
I created a new user with no additional settings and the problem still exist. Again, it happens only during the first login, no matter the user account used. Subsequent logins work fine.
I noticed today the problem disappears randomly on first boot, but it usually shows up (99% of the time).
The computer is a Core I7, discrete nvidia card with nvidia drivers (no optimus) and SSD.
I will reboot the computer, login with the newly created user and post the .xsession-errors file.

**Comment by MarceloRuiz** [comment]
Here there is a screenshot after opening Nemo after the first login in a newly created user account:

![screenshot from 2015-10-01 09 24 17](https://cloud.githubusercontent.com/assets/1209270/10221961/797d677e-681f-11e5-8f93-1b17ab04d34e.png)

Here is the content of the .xsession-errors file:

mdm[2992]: DEBUG: Forking extra process: /etc/mdm/PreSession/Default
mdm[2992]: DEBUG: Running /etc/mdm/Xsession cinnamon-session-cinnamon for m2 on :0
/etc/mdm/Xsession: Beginning session setup...
localuser:m2 being added to access control list
Script for none started at run_im.
Script for auto started at run_im.
Script for default started at run_im.
Script for none started at run_im.
Script for auto started at run_im.
Script for default started at run_im.
GNOME_KEYRING_CONTROL=/run/user/1001/keyring-Vg8XcH
GNOME_KEYRING_CONTROL=/run/user/1001/keyring-Vg8XcH
GNOME_KEYRING_CONTROL=/run/user/1001/keyring-Vg8XcH
SSH_AUTH_SOCK=/run/user/1001/keyring-Vg8XcH/ssh
GPG_AGENT_INFO=/run/user/1001/keyring-Vg8XcH/gpg:0:1
GNOME_KEYRING_CONTROL=/run/user/1001/keyring-Vg8XcH
SSH_AUTH_SOCK=/run/user/1001/keyring-Vg8XcH/ssh
cinnamon-session[2992]: WARNING: Application 'cinnamon-settings-daemon.desktop' failed to register before timeout
cinnamon-session[2992]: CRITICAL: We failed, but the fail whale is dead. Sorry....
cinnamon-session[2992]: WARNING: Failed to start app: Unable to start application: Failed to execute child process "blueman-applet" (No such file or directory)
Can't find all required implementations:
- http://dispcalgui.hoech.net/0install/dispcalGUI.xml -> (problem)
    No known implementations at all
Note: 0install is in off-line mode
Cjs-Message: JS LOG: About to start Cinnamon
nm-applet-Message: using fallback from indicator to GtkStatusIcon
Initializing folder-color-switcher extension...
Initializing nemo-image-converter extension
St-Message: cogl npot texture sizes SUPPORTED
Window manager warning: Trying to remove non-existent custom keybinding "magnifier-zoom-in".
Window manager warning: Trying to remove non-existent custom keybinding "magnifier-zoom-out".
Cjs-Message: JS LOG: Cinnamon started at Thu Oct 01 2015 09:23:27 GMT-0400 (EDT)

** (nemo:3363): WARNING **: Can not determine workarea, guessing at layout
Cjs-Message: JS LOG: network applet: Cannot find connection for active (or connection cannot be read)
Cjs-Message: JS LOG: network applet: Found connection for active
Cjs-Message: JS LOG: Ignored exception from dbus method: Gio.DBusError: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.cinnamon.SettingsDaemon was not provided by any .service files
Cjs-Message: JS LOG: Ignored exception from dbus method: Gio.DBusError: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.cinnamon.SettingsDaemon was not provided by any .service files

(cinnamon-settings-daemon:3218): libupower-glib-WARNING **: Couldn't enumerate devices: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.

(cinnamon-settings-daemon:3218): power-plugin-WARNING **: failed to get device list: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
mintUpdate: no process found

(mintUpdate.py:3500): libglade-WARNING **: unknown attribute `swapped' for <signal>.

(mintUpdate.py:3500): libglade-WARNING **: unknown attribute `swapped' for <signal>.

(mintUpdate.py:3500): libglade-WARNING **: unknown attribute `swapped' for <signal>.

(mintUpdate.py:3500): libglade-WARNING **: unknown attribute `swapped' for <signal>.
Cjs-Message: JS LOG: Ignored exception from dbus method: Gio.DBusError: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.cinnamon.SettingsDaemon was not provided by any .service files
=== xinerama setup Configuration ===
  Clone: false
  Output: (null) attached to VGA-0
     status: off
     width: -1
     height: -1
     rate: -1
     primary: false
     position: -1 -1
  Output: Laptop attached to LVDS-0
     status: on
     width: 1920
     height: 1080
     rate: 60
     primary: true
     position: 0 0
  Output: (null) attached to HDMI-0
     status: off
     width: -1
     height: -1
     rate: -1
     primary: false
     position: -1 -1
  Output: (null) attached to DP-0
     status: off
     width: -1
     height: -1
     rate: -1
     primary: false
     position: -1 -1
  Output: (null) attached to DP-1
     status: off
     width: -1
     height: -1
     rate: -1
     primary: false
     position: -1 -1
=== Applying Configuration Configuration ===
  Clone: false
  Output: (null) attached to VGA-0
     status: off
     width: -1
     height: -1
     rate: -1
     primary: false
     position: -1 -1
  Output: Laptop attached to LVDS-0
     status: on
     width: 1920
     height: 1080
     rate: 60
     primary: true
     position: 0 0
  Output: (null) attached to HDMI-0
     status: off
     width: -1
     height: -1
     rate: -1
     primary: false
     position: -1 -1
  Output: (null) attached to DP-0
     status: off
     width: -1
     height: -1
     rate: -1
     primary: false
     position: -1 -1
  Output: (null) attached to DP-1
     status: off
     width: -1
     height: -1
     rate: -1
     primary: false
     position: -1 -1
Window manager warning: Log level 16: Failed to create background texture from pixmap: Unable to query pixmap size
** Message: Unable to use GNOME Shell's builtin screenshot interface, resorting to fallback X11.
Nemo-Share-Message: Called "net usershare info" but it failed: 'net usershare' returned error 255: net usershare: cannot open usershare directory /var/lib/samba/usershares. Error Permission denied
You do not have permission to create a usershare. Ask your administrator to grant you permissions to create a share.

** Message: Unable to use GNOME Shell's builtin screenshot interface, resorting to fallback X11.

(eog:3805): EOG-WARNING **: Couldn't load icon: Error writing

(eog:3813): EOG-WARNING **: Couldn't load icon: Error writing

**Comment by websitevirtuoso** [comment]
I have the same error on UBUNTU 15.04 CINNAMON 2.6

viktor@viktor-Lenovo-Y50-70:~$ sudo cinnamon status
Window manager warning: Screen 0 on display ":0" already has a window manager; try using the --replace option to replace the current window manager.
viktor@viktor-Lenovo-Y50-70:~$ sudo cinnamon-launcher status
Cjs-Message: JS LOG: About to start Cinnamon
St-Message: cogl npot texture sizes SUPPORTED
Cjs-Message: JS LOG: Cinnamon started at Sat Dec 05 2015 17:22:02 GMT+0500 (UZT)
Cjs-Message: JS LOG: network applet: Cannot find connection for active (or connection cannot be read)

(cinnamon:4756): St-WARNING **: Ignoring length property that isn't a number
Window manager warning: Log level 8: cr_parser_new_from_buf: assertion 'a_buf && a_len' failed
Window manager warning: Log level 8: cr_declaration_parse_list_from_buf: assertion 'parser' failed
Cjs-Message: JS LOG: Invalid network device type, is 14
Cjs-Message: JS LOG: network applet: Found connection for active

(cinnamon:4756): St-WARNING **: Ignoring length property that isn't a number
Window manager warning: Log level 8: cr_parser_new_from_buf: assertion 'a_buf && a_len' failed
Window manager warning: Log level 8: cr_declaration_parse_list_from_buf: assertion 'parser' failed

(cinnamon:4756): St-WARNING **: Ignoring length property that isn't a number

(cinnamon:4756): St-WARNING **: Ignoring length property that isn't a number
Cjs-Message: JS LOG: Ignored exception from dbus method: Gio.DBusError: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.cinnamon.SettingsDaemon was not provided by any .service files
Cjs-Message: JS LOG: Ignored exception from dbus method: Gio.DBusError: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.cinnamon.SettingsDaemon was not provided by any .service files
Cjs-Message: JS LOG: Ignored exception from dbus method: Gio.DBusError: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.cinnamon.SettingsDaemon was not provided by any .service files
Cjs-Message: JS LOG: Ignored exception from dbus method: Gio.DBusError: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.cinnamon.SettingsDaemon was not provided by any .service files
Cjs-Message: JS LOG: Ignored exception from dbus method: Gio.DBusError: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.cinnamon.SettingsDaemon was not provided by any .service files

**Comment by Vahan86** [comment]
@MarceloRuiz, is this still an issue for you with Cinnamon 3?

**Comment by MarceloRuiz** [comment]
No, it seems to be fine now
