### ISSUE TITLE
Switching app instances (alt + apostrophe/tilde/Above_Tab) in active workspace

### ISSUE THREAD

**Issue by entr** [linuxmint/Cinnamon#4671]
Switching window instances of application when multiple workspaces are used doesn't honor active workspace and shows windows from all workspaces.

I personally found it a bit frustrating. Is that the intended behavior?

Linux Mint 17.2 / Cinnamon 2.6.13

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
