### ISSUE TITLE
Deleting ~/.cache resets Wallpaper

### ISSUE THREAD

**Issue by utack** [linuxmint/Cinnamon#4674]
When deleting the ~/.cache folder the wallpaper is reset.
Given the name, this folder should probably not influence the configuration in any way.
Maybe related to #3953 or #3913 , does one of the situations in these issues clear the cache?

**Comment by dralley** [comment]
I can't reproduce.  A copy of the wallpaper is kept in .cache, but as far as I can tell it isn't used... the gsettings key points directly to the original image.

Can you verify that this is still an issue on 2.8.6?  Did you change your wallpaper in a specific way?

**Comment by dralley** [comment]
@utack ?

**Comment by utack** [comment]
Seems to be only when the "original file" is removed too, just deleting the cache folder alone will not do it.
