### ISSUE TITLE
gnome-screenshot freezes with white screen in Cinnamon

### ISSUE THREAD

**Issue by geckolinux** [linuxmint/Cinnamon#4677]
Hello, under Manjaro Linux (Arch derived), gnome-screenshot 3.16 on Cinnamon 2.6 freezes at the white screen of the "flash" effect, leaving the entire screen painted white and requiring ESC or sometimes ALT+F4 to get rid of it. And since you have to manually kill the white screen, you also lose the screenshot you were trying to take. This appears to be an incompatibility with Cinnamon, because it works just fine in other desktop environments.

**Comment by geckolinux** [comment]
Same issue on Cinnamon 2.8 in openSUSE.

**Comment by leigh123linux** [comment]
I'm seeing this issue with gnome-screenshot

https://bugzilla.redhat.com/show_bug.cgi?id=1275123

what video driver are you using? as I don't get the white screen using nvidia.com driver

**Comment by geckolinux** [comment]
Intel video.

I should specify that the PrtSc key shortcut does work without issues. But this frozen white screen bug appears only after first opening gnome-screenshot and using any one of the fullscreen, window, or selected area screenshot options.

**Comment by ManIVIctorious** [comment]
So this issue is resolved and can be closed?

**Comment by geckolinux** [comment]
I think so, thanks.
