### ISSUE TITLE
Computer not locked while in suspend

### ISSUE THREAD

**Issue by RalfJung** [linuxmint/cinnamon#4678]
I just put my machine into suspend by closing the lid. A few minutes later, when I resumed the computer, the screen was _not_ locked - I had access to my session, with all its saved passwords, without any further authentication.

I do have "Lock the computer when put to sleep" enabled in the setting. This is on Debian testing, using systemd. Needless to say, this is a critical security issue.

**Comment by igordovgaluk** [comment]
i had second monitor connected to the laptop. 
after i close the lid the system is not suspended indeed.
instead the laptop monitor is off and all windows moved to the second monitor.

so looks like the issue is that machine is not suspended on lid close.
i have the action for lid close - Suspend (for both A/C and battery)

Cinnamon 2.8.2-20151104040013-trusty

**Comment by manjitkarve** [comment]
Cinnamon 2.8.8+rosa:
My laptop is configured to go to sleep when the lid is shut. It is also configured to ask for the password when it comes out of sleep. This works just fine except when the "Start" menu (the one on the panel) is open. In that case, the laptop goes to sleep, but doesn't lock the screen. On opening the lid, I'm directly landed on the desktop.

No second monitor is attached.

Let me know if you need any logs and where to find them.

Regards,
Manjit

**Comment by ManIVIctorious** [comment]
Could this be somehow related to #1430 or #920 ?

**Comment by JosephMcc** [comment]
It could be. We need to know if it happens for the users here if one of those things isn't open.

**Comment by DirkHaar** [comment]
see my comment at #1430, any menu applet dialog prevents from locking.

**Comment by Vahan86** [comment]
@RalfJung, is this still an issue for you with Cinnamon 4.4?

**Comment by RalfJung** [comment]
Sorry, I stopped using Cinnamon a while ago, so I couldn't tell.

**Comment by Vahan86** [comment]
@icarter09, @xenopeek, can we close this issue?
