### ISSUE TITLE
Double Lock Screen Arch Linux

### ISSUE THREAD

**Issue by cabellicar123** [linuxmint/Cinnamon#4682]
I am running Cinnamon 2.0 on very updated Arch. Heres some information:

```
$ uname -a
Linux arch 4.2.2-1-ARCH #1 SMP PREEMPT Tue Sep 29 22:21:33 CEST 2015 x86_64 GNU/Linux
```
Whenever the screen locks and after it is unlocked the lock screen appears again after a few seconds. Unlocking it once again fixes the issue. I saw this has been an issue in the past, but it was closed and does not seem to be fixed. `gnome-screensaver` is neither installed nor running:

```
$ ps -A | grep gnome
  699 ?        00:00:00 gnome-keyring-d
  805 ?        00:00:00 polkit-gnome-au
15384 ?        00:00:00 gnome-pty-helpe
```

**Comment by dalcde** [comment]
Why does your very updated Arch not have the lastest Cinnamon version?

**Comment by cabellicar123** [comment]
Sorry `cinnamon 2.6.13-3`

**Comment by cabellicar123** [comment]
As an update this appears to be tied to the screensaver. When I switch away from the default screensaver "Screen Locker" to the other screensaver "Stars" the double lock screen issue disappears. Unfortunately, this stars screensaver also has its issues as it sometimes prohibits me from logging in again (no matter what key presses or mouse movements I make). This often eventually goes away after a period of time.

**Comment by cabellicar123** [comment]
Correction. This did not appear to resolve the issue. It appears that the issue is less prevalent when just locking the screen `ctrl-alt-l`. It appears that the screensaver lock is being called twice for some reason. This is the same lock screen twice by the way (not two different lock screens like issues before).

**Comment by cabellicar123** [comment]
This problem appears to have been fixes as of `2.8.6-1`, so I am closing for now. I will come back if the problem reoccurs.

**Comment by cabellicar123** [comment]
Correction this is not yet fixed.

**Comment by ManIVIctorious** [comment]
Is this still an issue for you on latest cinnamon 3.0.7?

**Comment by cabellicar123** [comment]
@ManIVIctorious I have not experienced this recently and am running 3.0.7 so at this point I would say it is not still an issue.

**Comment by cabellicar123** [comment]
@ManIVIctorious I have not experienced this recently and am running 3.0.7 so at this point I would say it is not still an issue.
