### ISSUE TITLE
Cinnamon recommends "cinnamon-bluetooth", but this package is absent in the Linux Mint.

### ISSUE THREAD

**Issue by Splarv** [linuxmint/Cinnamon#4683]
Linux Mint  17.2 'Rafaela'
cinnamon Version: 2.6.13+rafaela
According to the file ".xsession-errors" Cinnamon depends on the library libwayland-egl.so.1 and don't work without it. But this dependence is abscent in the dpkg and this lead to a problem, for instance, when upgrade to the LTS vivid stack. As I undestand cinnamon must depend upon  the virtual package libwayland-egl1, this will solve this problem.

**Comment by Zero3** [comment]
Can confirm this is still an issue with Linux Mint 17.3 (Cinnamon 2.8.6).

I ran into this problem after running `gtkorphan` and removing the package `libwayland-egl1-mesa-lts-vivid` because nothing depended on it. This broke `cinnamon-settings` which silently crashed with a console error complaining about the missing library.

**Comment by ManIVIctorious** [comment]
This is obviously a packaging issue and not related to cinnamon itself. Could you please close this defect?

**Comment by Splarv** [comment]
Oh, this was one year ago.
Yep, this was package from Linux Mint, it's the Debian package. Files for the debian package are in the Cinnamon Git source repository. As I can understand this is the file.
https://github.com/linuxmint/Cinnamon/blob/master/debian/control 
Let me check is this problem still exists.

**Comment by Splarv** [comment]
I checked. Now this problem is fixed, Cinnamon depends upon libcogl20 and libcogl20 depends upon libwayland-egl1.

But there is another problem in dependences. Cinnamon recommends "cinnamon-bluetooth", but this package is absent in the Linux Mint.

**Comment by ManIVIctorious** [comment]
Packaging issues should be filed against the corresponding distribution. I have to admit I don't know where this place is for linux mint but the linux mint forums would be a good starting point. Could you please close this issue, since its resolved (and doesn't belong here)?

**Comment by JosephMcc** [comment]
Closing since the original issue is fixed.
