### ISSUE TITLE
Cinnamon Menu Editor Cut/Copy/Paste

### ISSUE THREAD

**Issue by FiretronP75** [linuxmint/cinnamon#4684]
This has never worked in any previous version and still does not. When you copy and paste an item from one folder to another, it also creates a copy in the source folder. And then one of them is linked to the one you pasted elsewhere. And if you delete one it will delete both, or in some case all 3.

**Comment by tp0** [comment]
Closed meta? bug: #1563

**Comment by icarter09** [comment]
Linux Mint 19.2
Cinnamon 4.2.4

I'm not able to reproduce this issue. I created a folder with test docs. Copied and pasted the test docs into another folder. Deleted the original. The new one was unaffected. Tried this several times while deleting the original in some cases and the new one in others.
