### ISSUE TITLE
Cinnamon Menu Editor Requires Logout to Refresh

### ISSUE THREAD

**Issue by FiretronP75** [linuxmint/Cinnamon#4686]
Any changes made in the Cinnamon Menu Editor do not show up on the menu until you log out and back in.

**Comment by dralley** [comment]
I can't reproduce on 2.8.  Can you give an example?

**Comment by dralley** [comment]
@FiretronP75 If you update to Cinnamon 2.8, could you test this again and see if it still happens?

**Comment by jawz101** [comment]
I'm on Arch Linux running Cinnamon 2.8.6 and this has always been an issue.

**Comment by f2404** [comment]
Same for me. Any program disappears from the menu after it's been updated or installed with the package manager.

**Comment by keitalbame** [comment]
@f2404 Seems the same issue as #4498.

Workaround is move the affected application files out and back in of /usr/share/applications/

**Comment by f2404** [comment]
@keitalbame Thanks, will try it next time the issue happens.

**Comment by Vahan86** [comment]
@FiretronP75, is this still an issue for you with Cinnamon 3.0.7?

**Comment by Vahan86** [comment]
@JosephMcc, can we close the issue?

**Comment by FiretronP75** [comment]
@Vahan86, I've been using Mint KDE exclusively this year, partly because of this issue. I didn't make the time yet to try a new install of Mint Cinnamon.

**Comment by FiretronP75** [comment]
Back when I opened this issue, when I was asked to try it in 2.8, 2.8 hadn't been released yet, so I couldn't try it in 2.8.

**Comment by Odyseus** [comment]
Hello, everybody.

I cannot reproduce this issue on Cinnamon 3.0.7 nor 3.2.x. Editing any application with the menu editor triggers an immediate update of the menu and the changes are visible instantly.

**Comment by JosephMcc** [comment]
@Odyseus Thanks for testing. If someone turns up with the problem we can always re-open it.

**Comment by kva1966** [comment]
Hi Folks, this is what I'm on:

```
System:  Kernel: 3.16.0-4-amd64 x86_64 (64 bit gcc: 4.8.4)
Desktop: Cinnamon 3.4.6 (Gtk 2.24.25) dm: lightdm Distro: LinuxMint 2 betsy
```
The scenario is as follows:

* Install new app, manually, in $HOME (Telegram in this case, has no repository package)
* Add a .desktop entry to $HOME/.local/share/applications/telegram.desktop 
* Searching in menu for new item does not bring it up.

Note that I do have other custom applications in $HOME with their .desktop entries that are being picked up; I haven't logged out yet, but I suspect that'll do the trick.

Menu does not update. Before using LMDE, I was on Debian using a Synapse launcher, it would pick up these changes on any changes to the folder near instantly. Not sure what sort of background indexing process was used, whether it was a Debian thing or a synapse dependency. 

Out of curiosity, what's Cinnamon's mechanism to update it's menu on changes?

**Comment by TopView** [comment]
One way I've found **to force Cinnamon to update** it's menu from the underlying xdg files, **is to restart it,** like with Alt-F2 and enter 'r' (for restart), or I've seen applets with a button to restart it.  For example a Desklet called Developer's tools has a button to restart it.  It's kind of a slow process, but it works without logout and/or reboot.

**I am still looking for a cli way to update a cinnamon menu**, but so far haven't found it.  I suppose it might depend on which menu applet one is using.  Currently i'm trying out CinnVIIStartMenu.

**Comment by TopView** [comment]
**Update:**  Updating a .menu or .desktop file (editing it and saving to disk) causes the GUI cinnamon menu editor to automatically update.  It also causes the menu applet to update.  

(Debian Buster 10.2 / Cinnamon 3.8.3.)

**Comment by snakyjake1** [comment]
I have this issue with Cinnamon v4.8.6.

This mostly occurs when installing user flatpaks.
