### ISSUE TITLE
Wifi networks don't show up in network settings only in applet and bluetooth issue

### ISSUE THREAD

**Issue by AlexAlexandru** [linuxmint/Cinnamon#4688]
http://imgur.com/a/NU6A9
1.In the first photo you can see that the wifi is working but in the network panel the networks don't show up.Sometimes they do show up but I don't know exactly what I do that they show up maybe it's random?
2.Also in the second photo you can see that I set to wireless do not use this device but is still working is this the intended way of working?
3.I use linux mint so I don't know if I this a  linux mint issue or cinnamon but I will post here.
When I turn off bluetooth my airplane led from laptop is on but my wifi is still on.The airplane led should be off because wifi is still on right?

**Comment by pixunil** [comment]
1. It happened also to me when I activate wireless in settings. The switch is on, but the list keeps being empty. Opening a new instance of settings resolves this.
2. You disabled the _driver_ for wireless, but it looks like it works without it. Shouldn't be the issue you mentioned.
3. About the airplane led, I have no idea which part of your system is controlling it.

**Comment by Vahan86** [comment]
@AlexAlexandru, is this still an issue for you in Cinnamon 3?

**Comment by Vahan86** [comment]
@JosephMcc, can we close the issue?
