### ISSUE TITLE
Steam Notifications Below Panel

### ISSUE THREAD

**Issue by netsudo** [linuxmint/Cinnamon#4690]
Recently stated using a second monitor on Mint with Cinnamon 2.4.8, I have them both on a single xscreen because cinnamon doesn't support two (was getting fallback modes). Anyways switched over to xfce for a while and tried out kde a bit, when I decided to just use a single xscreen because I missed cinnamon my steam notifications started to pop up below my taskbar on it, is there any fix for this I could perform manually? It's really bugging me. Also note that none of the hover-over text of the icons appears below taskbar, just steam notifications.

**Comment by mtwebster** [comment]
We tried to get Steam to fix this - they decided only to fix it for single-monitor situations, or (I think) where you're running Steam on the primary monitor.  I keep hoping they'll fix it properly...

**Comment by netsudo** [comment]
Ah, bummer. I thought maybe xfce or kde panel configs were perhaps creating dissonance for Steam's notifications. It's unfortunate it's my monitors that are doing it, I suppose I can keep taskbar hidden for the time being. As far as running steam on primary display goes though it doesn't work. Running steam on my primary middle monitor currently which also has the taskbar set on it and notifications are popping up underneath.

**Comment by JosephMcc** [comment]
Duplicate https://github.com/linuxmint/Cinnamon/issues/3610
