### ISSUE TITLE
Real pointer is not under cursor

### ISSUE THREAD

**Issue by ManuelSchneid3r** [linuxmint/Cinnamon#4693]
Hard to describe in detail. Displayed cursor is not real pointer. See picture. Display applet is hovered but cursor is elsewhere. This happens only if display is rotated.
![Image of cursor](http://i.imgur.com/qMHRUBt.png)

**Comment by Vahan86** [comment]
@ManuelSchneid3r, is this still an issue for you in Cinnamon 3.0?

**Comment by ManuelSchneid3r** [comment]
Nope, is fixed. Thank you.
