### ISSUE TITLE
Fix the implementation of the Queuing system for File Operations that was added in 17.2 release

### ISSUE THREAD

**Issue by sproger1** [linuxmint/Cinnamon#4694]
Please implement a 'smarter' queuing system for file operations. The current implementation (as of 17.2) is really annoying. I find myself performing duplicate delete and move operations of the same files because I keep forgetting that they're queued due to having a long copy operation going on. The queue currently allows duplicate operations to be in the queue waiting, which later results in annoying pop-ups.

Changes requested:
1) Identical operations{delete, move, and possibly copy} on the identical files that have not yet been started should not be allowed, as it should be obvious that they cannot be completed.
2) Not all file operations are equal. 'DELETE' and 'MOVE(within the same partition/drive)' should have the highest priority (or better yet, NOT QUEUED AT ALL) since those operations should only take milliseconds to perform. 
3) If multiple hard drives are present, the queue should allow for performing multiple copy operations in parallel if they are being performed on drives that are independent of each other (since there is no penalty on those cases). 
4) If there are multiple copies in the queue, give the smaller files higher priority since they would leave the queue faster (thus giving the illusion of faster responsiveness, by having the File explorer display closer to the end state quicker). 
5) Allow disabling of this feature. I like the idea of queuing large copy operations, but, this currently blocks small/quick file operations, and so is not usable in its current form. I don't see a means to turn it off.

**Comment by alium** [comment]
+1

**Comment by tp0** [comment]
+1

**Comment by JosephMcc** [comment]
This is a nemo issue, not a Cinnamon issue.
https://github.com/linuxmint/nemo
