### ISSUE TITLE
Accessibility option - Caps Lock sounds

### ISSUE THREAD

**Issue by tonywhelan** [linuxmint/Cinnamon#4697]
Mint 17.2 raphaella Cinnamon 64 bit.

In System Settings, Accessibility, "Seeing" tab, when you enable the "Beep on Caps and Num Lock" the computer does NOT beep (as it should) when those Lock keys are pressed.

This is also the case in Ubuntu 14.04 and several prior versions.

I have verified this feature does not work on 4 different machines with LM Cinnamon 17 installed, incl 1 laptop.

It appears the current code inherited from Ubuntu is intended to sound the "beep" via the PC speaker. However:
1. Some systems (eg lapops) don't have a PC speaker:
2. Mint by default blacklists the PC speaker as its often too loud and ugly
3. Having the same sound for Caps Lock ON and Caps Lock OFF is pointless; we need a separate sound for On and OFF key states.

Its possible for someone with a bit of knowledge to set up a key binding and a script that will play a beep when a Lock key is pressed ON, and play a different (lower-toned) beep when pressed OFF. Its a bit slow but it does work. But it shouldn't be necessary - the facility should work out of the box.

Fixing the above bug would be appreciated not just by people with disability restrictions, but also by anyone using keyboards or laptops that have no Caps Lock or Num Lock light, or have a light that's too small to be useful.

**Comment by coffeeking** [comment]
this requires both a code fix in cinnamon itself and also a sound theme with the appropriate sound files. I believe what you want is button-toggle-on for on and button-toggle-off for off. I can't use linux mint right now because it does not include orca in it's distribution live cd, but they might have a sound for those events. If not, they'll need to add those sounds in order for this to work out of the box.

**Comment by JosephMcc** [comment]
@tonywhelan I just saw your post about this on the Segfault Cinnamon3.0 release announcement. Mtwebster improved this a great deal for 3.0. When turning on the audio indicator for caps or num lock you can now set a sound file to play in much the same way you can can for other Cinnamon sound effects. There is also now a visual indicator that reuses the volume osd to indicate when caps or num lock is activated and deactivated.

**Comment by tonywhelan** [comment]
Thanks Joseph, that's good to hear.I'm looking forward to seeing this when Mint 18 is released.

**Comment by JosephMcc** [comment]
Did you have the chance to try this? If it meets your needs can this be closed?

**Comment by coffeeking** [comment]
hi
Yup, it works like a charm. It can safely be closed.
Thanks
Kendell Clark


JosephMcc wrote:

**Comment by tonywhelan** [comment]
Thanks Joseph, it works very nicely, and is much appreciated.

Tony Whelan
