### ISSUE TITLE
Remove mouseover event from 2D window switchers

### ISSUE THREAD

**Issue by multiwebinc** [linuxmint/Cinnamon#4698]
When using one of the 3D window switchers (coverflow or timeline), you can move your mouse all around the screen, but the window doesn't become the "active" one in the list simply by moving your mouse over it. The only mouse event bound to the 3D switchers is the click, which switches directly to that window.

With the 2D switchers, on the other hand, when you mouse over one of the window icons, that window becomes the highlighted window (in the window list) and if I release the Alt button, that becomes the current window on the screen. To me that behavior is undesired. I would like it to only switch to a window using the mouse if I actually click on the icon. 

Very frequently when I push Alt-Tab to switch windows I also have my hand on the mouse at the same time. I might not be moving it much, but if it just so happens to be in the same region as the window switcher, even a little jiggle will cause me to switch to the wrong window. I could see this happening even more in the "Icons and window preview" option where people may begin to move their mouse to the desired location before even actually switching to that window.

Doesn't anybody else have this problem? In essentially all user interfaces I have ever used in my life, you don't select things by mousing over them. You select them by clicking.

P.S. I'm using Cinnamon 2.2.16-5 on Debian. I apologize for posting if this behavior has been changed in more recent versions.

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
