### ISSUE TITLE
Run as Administrator feature

### ISSUE THREAD

**Issue by bernd-wechner** [linuxmint/Cinnamon#4699]
The lack of this in Cinnamon has proved frustrating to me after moving from Windows 7 I admit.

I come across a wonderful package like etherApe and it cannot run sensibly without admin privileges. 

The nearest existing issue filed I found was:

Add Capability to Run Launcher as Root #2244 

but this is not actually a duplicate and that was closed as a non-issue.

My need has two current workarounds:

1) Fix the applications binary to run setuid root. Alas GTK+ binaries refuse to run like that so no go for them, and etherape is one such. So fail in this case.

2) fix the launcher properties by prefixing the command with gksudo. It now runs much like the MINT  software manager and asks for a root password every time I start it which is a pain really, as unlike the software manager I'm very happy for family members to run etherape without needing to know a root password. Hence while liveable on a personal level, a fail for etherape still as it wants to provide a service to any desktop user in a sense who wants to watch network activity (and is allowed to).

There is definitely a cinnamon issue here at the very least because there could (arguably should) be a Run as Administrator on the drop down right-click menu that the Menu applet offers. Currently it has Add to panel, Add to desktop, Add to favourites and Uninstall, the last of which needs admin privileges presumably as well.

Cinnamon could/should have Run as Adminsitrator in this list as well which does what I did (launches with gksudo), but that's a minimal. In the ideal (though this may no longer be a Cinnamon issue, and if not any tips as to where it's best addressed are appreciated) it would do that but allow me as an administrator to flag this as running as an administrator and not have to provide a password each time, and to be able to configure family member accounts like that too.

**Comment by leigh123linux** [comment]
Bookmarked as reminder,  if this change is ever added (merged) I will remove it for fedora packages!

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.

**Comment by bernd-wechner** [comment]
Thanks, the linked to page was also reviewed. What it fails to address is if the submitter of a cool idea has any way of tracking whether it will be implemented or not. It would be nice to know if it's going to implemented or not, surely?

**Comment by NikoKrause** [comment]
I think that's an interesting feature request. Though I'm not sure if it's (security)wise to allow scripts to run as sudo without password.
I have found the following answer, but haven't tested it. Maybe that'll help you:
https://askubuntu.com/questions/39281/how-to-run-an-application-using-sudo-without-a-password

**Comment by bernd-wechner** [comment]
It needn't be available on every item or script I guess. Though ideally configurable, (in the manner of the old setuid root trick used on historic systems I guess - though that's frowned upon). Problem is no matter how secure we want things to be, there are some tools (and etherape is one I can think of) that want or need root access, but are considered safe and I don't want to to type a password every time I start it, not prevent my family from using it, nor empower with with a root password ... etc.). Fairly ordinary old use case I'd have thought. Or like sudo itself it could prompt on first invocation and then  last for a given time (sudo seems to last on CLI and time out eventually). so on subsequent uses it runs without prompt. Slick design for efficient use, and a good compromise between security and utility.

**Comment by decuser** [comment]
It seems like this needn't run without password - just add "run as administrator" and let it prompt for a password. I recently installed glogg in debian running cinnamon and it would be nice if there were a way to get it to run as an administrator directly from the cinnamon menu, rather than having to sudo glogg.

**Comment by decuser** [comment]
2022 workaround for somebody not wanting to provide credentials is to visudo and add NOPASSWD: to sudo line:

`%sudo ALL=(ALL:ALL) NOPASSWD:ALL`

and make sure the user's in sudo group:

`usermod -a -G sudo user`
