### ISSUE TITLE
Copy/Link/Move indicator below cursor are missing

### ISSUE THREAD

**Issue by ManuelSchneid3r** [linuxmint/Cinnamon#4700]
2.6.13: Copy/Link/Move indicator below cursor are missing, but the functionality is still there, when using Ctrl and Ctrl+Shift.

**Comment by tp0** [comment]
Can't repro. 2.6.13

Is this a Nemo thing? https://github.com/linuxmint/Nemo/issues

**Comment by ManuelSchneid3r** [comment]
The problem is that I deleted the currently set cursor theme a while ago. X switches to an ugly cursor fallback, which is a single static black cursor. I chose Adwaita and everything is fine. Maybe this is a rare cornercase or maybe this should be checked on session start. Up to you.
Regards

**Comment by JosephMcc** [comment]
It seems like this is an issue with the cursor theme. The couple I tried worked fine.

**Comment by ManuelSchneid3r** [comment]
True but the case i described is when the current cursor theme is deinstalled from the system. Its a rare case but somhow the existance of the cursortheme should be checked at least on session start.
