### ISSUE TITLE
Cinnamon/panel not responsive to mouse, but keyboard and shortcuts works

### ISSUE THREAD

**Issue by petter3k** [linuxmint/Cinnamon#4705]
Hi,

as title says.

Mouse have no effect what so ever on the cinnamon panel and cinnamon --replace & gives the following output:

```
Cjs-Message: JS LOG: About to start Cinnamon
St-Message: cogl npot texture sizes SUPPORTED
Window manager warning: Trying to remove non-existent custom keybinding "magnifier-zoom-in".
Window manager warning: Trying to remove non-existent custom keybinding "magnifier-zoom-out".
Cjs-Message: JS LOG: Cinnamon started at Tue Oct 13 2015 20:46:22 GMT+0200 (CEST)
Cjs-Message: JS LOG: network applet: Cannot find connection for active (or connection cannot be read)
Cjs-Message: JS LOG: network applet: Cannot find connection for active (or connection cannot be read)
Cjs-Message: JS LOG: network applet: Cannot find connection for active (or connection cannot be read)

(cinnamon:3095): Cjs-WARNING **: JS ERROR: TypeError: value is null
Player.prototype._dbus_acquired/<@/usr/share/cinnamon/applets/sound@cinnamon.org/applet.js:492
_proxyInvoker/asyncCallback@resource:///org/gnome/gjs/modules/overrides/Gio.js:86
```

Running Arch with Cinnamon 2.6.13

**Comment by petter3k** [comment]
No upgrade or reinstall have fixed this so far, as of today.

**Comment by rogerberm** [comment]
Same here. On the first mouseover I get:

(cinnamon:24741): Cogl-WARNING **: driver/gl/cogl-framebuffer-gl.c:1078: GL error (1280): Invalid enumeration value

but so does when I open the menu via keyboard, so I guess it has nothing to do.

Some tray icon apps are responsive (google hangouts, google chrome), but nothing else.

Cinnamon 2.6.13 / Arch linux

**Comment by petter3k** [comment]
Still same problem. This problem however is only affecting my desktop computer with nvidia graphics.

Running the exact same setup on my laptop, and I cannot reproduce the error on this machine.

The desktop specs is:

Intel Q6600 Core2Duo Quad CPU
Nvidia 8800GTS 
4gb RAM

Laptop specs:

Asus UX32LN
Optimus hardware (nvidia 840m, intel hd graphics 4500)
8GB RAM
Intel Haswell 4510U

**Comment by Vahan86** [comment]
@petter3k, does this issue still occur in Cinnamon 3.0.x?

**Comment by petter3k** [comment]
@Vahan86 I found the issue - it happens with older nvidia-drivers, atleast in Arch Linux. nvidia-304xx the issue happens. 340xx works, but has issues with my 8800gts 640mb.

**Comment by ManIVIctorious** [comment]
So this seems to be a driver issue and can't be adressed by the cinnamon devs?

**Comment by petter3k** [comment]
Well it was obviously working at one point. so I think whats causing this lies in the transition that Cinnamon made to v3

**Comment by JosephMcc** [comment]
Ok, we have an open issue for the nvidia 304 driver problem. Here https://github.com/linuxmint/Cinnamon/issues/5548

I have the same issue on my gtx260. Works great with the open source driver.
