### ISSUE TITLE
Keyring should be occasionally purged

### ISSUE THREAD

**Issue by RalfJung** [linuxmint/Cinnamon#4708]
I like putting my machine in suspend mode when I don't use it, rather than shutting it down all the time. This way, it comes back up way more quickly.

However, with Cinnamon (through gnome-keyring) keeping my secret SSH and GPG keys open for as long as the session lasts, this actually becomes a significant security thread: The keys will be loaded into the keyring for several days, for no good reason. In addition, there are known attacks that extract key material from RAM of a suspended machine.

Cinnamon should at least offer to regularly close the keyring, _including_ all SSH and GPG keys. This could happen, for example, each time the screen is locked, or each time the machine goes to suspend. The way gnome-keyring works currently, I feel very uneasy.

Notice that not using gnome-keyring for SSH/GPG, while a possible option, is very badly supported by Cinnamon. For example, using Nemo to access an SFTP folder is no longer possible when the SSH part of gnome-keyring is disabled.

**Comment by pixunil** [comment]
I hope it helps you a bit (I didn't try it):

From [https://wiki.gnome.org/Projects/GnomeKeyring/SecurityFAQ](https://wiki.gnome.org/Projects/GnomeKeyring/SecurityFAQ#Can_I_lock_the_keyring_every_time_I_suspend_the_computer.3F):

> ### Can I lock the keyring every time I suspend the computer?
> Yes, but currently you need to configure the Gnome Power Manager to do it. Use the configuration editor, gconf-editor, and enable the option `/apps/gnome-power-manager/lock/gnome_keyring_suspend`.
>
> Update: this was fixed in gnome-power-manager, and will eventually be released.

I could imagine an option in the privacy module of settings.

**Comment by RalfJung** [comment]
That sounds very much like it is all about gtk2-based components. I could not find any such option in the gtk3-based dconf-editor.

**Comment by linux-modder** [comment]
As someone that uses suspend and  many DEs among one is  Cinnamon
Suspending for long periods with session keys  live (even if  in a warm
state) in and of itself is a  security risk consider using a usb key or
similiar to hold keys which leaves the system when you do (or system
suspends)..

Corey W Sheldon
Freelance IT Consultant, Multi-Discipline Tutor
Ameridea LLC, Founder, CTO
Fedora Ambassador, North America
---------------------------------------------------------------------------------------------------
PGP: 0xe958c5d6718bf597 FP = 2930 99EB 083D D332 0752 88C4 E958 C5D6 718B
F597 linuxmodder@keybase.io
Tox: Corey84 || Linux-modder
9357BC6A5944A08AFC7D1EFFD61F6A73B9EABF8B2FB84ACF1DAC9A1A4D0A4705FFCCD0E5499B
Linphone: sip:linuxmodder
BitAddress:15cn1BvAFEREHk8UekJ6i9Dxi9Wbw6vzDD

**Comment by leigh123linux** [comment]
File your issue against gnome-keyring instead.
