### ISSUE TITLE
Delay in closing windows - 3-4 seconds

### ISSUE THREAD

**Issue by abdupattoh** [linuxmint/Cinnamon#4710]
After running cinnamon for a while, I experience a delay in window managment, especially in closing windows.

For example, I used the keyboard to open a Nemo window, and then ctrl-F4 to close it.  It took almost four seconds to close the window.  It gets quite annoying.

Restarting cinnamon from inside cinnamon (ALT-F2 r) doesn't seem to make a difference, nor does a forced garbage collection from looking glass.  Logging out and re-logging in helps, but the problem comes back after a while.

I have disabled all extensions.  Still a problem.

Don't chase me to XFCE - cinnamon is really a nice windowing environment.

**Comment by justsml** [comment]
+1 
:+1:

**Comment by tgregoneil** [comment]
I'm having the same problem. Always a few seconds for a window to close after dismissing it. This happens even a fresh reboot. This feels like either clumsy handling of a callback, or worse, handling the dismiss event in a polling fashion.

**Comment by Vahan86** [comment]
@abdupattoh, does this issue still relevant to Cinnamon 3.6?
