### ISSUE TITLE
Window grouping in taskbar

### ISSUE THREAD

**Issue by grenzor** [linuxmint/Cinnamon#4712]
Currently it's not possible in Linux Mint.

It was pioneered by Windows and it's possible in KDE (and I like it a lot) from 4.2 I guess, but still not possible in Cinnamon.

Are you working on this feature? If so, please don't forget for the possibility of windows previews and the ability to rearrange them - this is one thing that is currently not possible in Windows 7 and I wish I have that feature on many occasions)

I think a lot of people will appreciate that because it's in Windows too.

**Comment by dalcde** [comment]
Closed for duplicate
