### ISSUE TITLE
Add right-click option to open as Root + Space to right click

### ISSUE THREAD

**Issue by grenzor** [linuxmint/Cinnamon#4713]
1) Currently you can only open folders as Root but not sure why open file as root isn't an option as I find that much more useful.

2) Add some space in the bottom or sides of folders where users can click and it will show us the options to create new file/folders etc. 90% trying to create a file with a full folder it ends up right clicking a folder where the cursor is and there is no where to right click to open the options of create new.

**Comment by JosephMcc** [comment]
This is a nemo issue. Please post it on the appropriate repo: https://github.com/linuxmint/nemo
