### ISSUE TITLE
cinnamon 2.6 has various accessibility issues

### ISSUE THREAD

**Issue by coffeeking** [linuxmint/cinnamon#4715]
hi all. I'm relatively new to the cinnamon project, but I'd like to help improve it's accessibility for the disabled. I'm a visually impaired user, and so depend on a screen reader to read the screen to me. Cinnamon is partially accessible, with a number of issues I'll now detail. Most of the current accessibility is only there because gtk3 provides some basic accessibility of it's own. However, talking to mtwebster on irc reveals that you guys use a lot of custom widgets. At present, the issues I've  found so far are: it seems impossible to get to the panel via alt+f1. Upon opening this area of the desktop, orca reports simply "panel" and will read nothing else. The cinnamon menu is not accessible. Upon opening it, orca says simply "text" indicating an input area. I can visually see the search results appear but orca will neither read them nor navigate through them. The file manager preferences are inaccessible apart from the close button. In the settings, many of the tabs in dialogs are not marked as page tabs, so a little trial and error is needed to find them and navigate through them. There are lots of unlabeled buttons in the settings. This is just a high level overview, I will gladly get specific if needed. As a recommendation, I'd try navigating cinnamon using orca, which is probably available in your linux distribution. The important thing isn't to understand the speech, but just to make sure there aren't any critical accessibility issues before release. I'll gladly provide any more info you guys need, since this is a little vague.

**Comment by icarter09** [comment]
I'm going to close this ticket out since it's focused on Cinnamon 2.6

@coffeeking feel free to open up a new ticket with the accessibility issues concerning Cinnamon 4.2. Thanks.
