### ISSUE TITLE
Terminal-installed applications don't showup in Mint Menu unless user logs out 

### ISSUE THREAD

**Issue by MarceloRuiz** [linuxmint/cinnamon#4717]
In a fresh install of Mint 17.2 Cinnamon open a terminal an install a program:
"sudo apt-get install gnome-commander"
Let the installation finish.
Optionally wait for a while.
Open Mint Menu and try to find the installed application: it won't be there, contrary to expectations.
Log out and log back in and the application shows up.

**Comment by pixunil** [comment]
Can reproduce, with one addition: it resolves by restarting cinnamon.

*****

It depends on the application. Most apps will display right after install in the menu.
I assume that some of cinnamon internals don't recognize the change while running.

**Comment by JosephMcc** [comment]
I install pretty much everything from the terminal. Most things show up by I did run into something the other day that didn't but I don't remember what it was.

**Comment by Vahan86** [comment]
@MarceloRuiz, does this issue still exist in Cinnamon 4.2?

**Comment by Vahan86** [comment]
@icarter09, can we close this issue since there is no response from OP?
