### ISSUE TITLE
Fix icon aligment bug in System Settings

### ISSUE THREAD

**Issue by MarceloRuiz** [linuxmint/cinnamon#4718]
In a newly installed Mint 17.2 Cinnamon open System Settings, select Fonts and change the Font Scalling to 1.2 (or whatever value you want), go back to System Settings and notice that the Appearance Icons "Backgrounds", "Effects", "Fonts" and "Themes"  are not aligned anymore with the remaining icons (the ones under Preferences, Hardware and Administrations are properly aligned).

**Comment by Vahan86** [comment]
Tried to reproduce this issue in Cinnamon 3.0.7. It seems the issue is fixed.

@MarceloRuiz, is this still an issue for you?

**Comment by MarceloRuiz** [comment]
@Vahan86 Yes, the problem is still there. I just checked and I run Cinnamon 3.0.7

**Comment by Vahan86** [comment]
@MarceloRuiz, is this still an issue for you with Cinnamon 4.2?

**Comment by Vahan86** [comment]
@icarter09, can we close this issue since there is no response from OP?

P.S. Can't reproduce this issue in Cinnamon 4.2.4. It works fine for me.
