### ISSUE TITLE
add lock/unlock panel setting

### ISSUE THREAD

**Issue by A-Shahbazi** [linuxmint/Cinnamon#4720]
It is very nice that cinnamon panel is highly configurable(like the early days of gnome2) but after one finishes the configuration it's better to have a "lock panel" option in panel settings (System Settings > Panel) so that the right clicking on blank space or on applets doesn't bring up context menus that are for configuration purposes.

The idea behind this suggestion is that once you finish the configuration you want the panel to feel SOLID for everyday use. You rarely decide to change panel configuration once you have it set. Using this option you make sure there won't be unintentional pop up of a configuration window or even unintentional change in panel layout. Moreover, this is the default behavior for other desktop environments.

BTW, this bug report is not from a security point of view like what we have at #2719. So this is not a duplicate of that bug.

**Comment by dalcde** [comment]
After you lock it, how do you unlock the panel? Dig through cinnamon-settings to find the right button?

**Comment by JosephMcc** [comment]
> After you lock it, how do you unlock the panel? Dig through cinnamon-settings to find the right button?
Well, you right-click and unlock it of course :)
I actually always thought the way some other desktops do this was an annoyance. I can honestly say I don't think I've ever accidentally messed up my panel. As far as I can think of I don't know any case where a single accidental right click on the panel would screw anything up.

**Comment by A-Shahbazi** [comment]
Yes, the lock/unlock button should be available through cinnamon-settings. (As I mentioned earlier: Settings > Panel)
So you unlock the panel the same way you had it locked.

**Comment by A-Shahbazi** [comment]
@JosephMcc
How often do you change your panel layout?! I think it's unnecessary to have the configuration features always on(Just take another look to the plenty of configuration options available for panel. They obviously are not for everyday use). Moreover, you can keep your panel unlocked forever even if the feature is implemented.

After all, I think the purpose for locking panel is clear and it is the same for all other desktops and apps which offer it.

**Comment by JosephMcc** [comment]
Well to be fair I probably screw around with my panel layouts (and everything else in Cinnamon) a lot more than a typical user. That being said, I stick by my original comment. An inadvertent click on the panel can't do anything. Even if you have a crazy, twitchy finger there is really no way to accidentally screw up your panel layout. That makes a lock/unlock something that isn't needed in my opinion. In fact, having to enable "Panel edit mode" to move anything is almost the same thing.

**Comment by A-Shahbazi** [comment]
You don't screw things that much obviously! It's just a panel. You can remove it and build a new one from the beginning. It's just a feature that makes panel feel SOLID for everyday use. Again, it has the same purpose of all lock/unlock features available elsewhere and thus the same importance.

BTW, I meant the whole configuration features either available for whole panel(by right clicking on blank space in panel) or individual configurations (available through right clicking each applet). The "Panel edit mode" is just one fraction of those configurations.

**Comment by dalcde** [comment]
I'd say it is likely that the user would be confused if they want to configure the panel but it is locked. Even if they initially locked it through Cinnamon Settings, as you have said, by the time they want to change the configuration, that would have been a long time ago and they probably won't remember where to unlock.

With that said, you definitely don't want to hide applet right-click menus since they are not necessarily used for configuring the applet, eg. the window list/sound applet.

I am still not convinced why hiding the configuration options would make it feel "solid"

**Comment by lestcape** [comment]
I really disagree to have an option for see an another option. What might make sense to me is in all case, ask to the user and then allow configure the panel as is the most common behavior in cases where the user could be disturbed by an accidental click. This also can used to alert the user of how he can do the action. So, will be a verbose solution for the novice user instead of hide the few information that he can take in the begin of the usage of a new shell.

**Comment by A-Shahbazi** [comment]
@dalcde 
There are only two candidates for changing panel appearance: First, through settings > panel and second, by right clicking the panel. I don't understand how one might get confused when there is only 2 choices.

About right clicking special applets the desired action is obvious in my opinion: just show the applet's specific items without "about", "configure", and "Remove this applet".

By feeling solid I meant the panel should seem not changing as if configuring is not allowed like many desktops. This way we benefit capability of configuration beside the stability of panel layout. Furthermore, availability of configuration options in everyday use is superfluous. Just take another look to them: "Add applets ...", "Panel settings", "Themes", "All settings", "Troubleshoot"!!, "Modify panel", "Panel edit mode". It's obvious to me that they are not for everyday use.

**Comment by A-Shahbazi** [comment]
@lestcape 
the following screenshot shows one of those options to see another option in cinnamon: (i.e. "Use customized panel size"!)
![screenshot from 2015-10-19 19 37 14](https://cloud.githubusercontent.com/assets/7456141/10583283/ef7d3756-7698-11e5-8811-2aac24324e63.png)

I think a single line of description will make things clear(as in this example). In addition, the default setting can be set to unlock so that the configuration options are shown from the very first try of the desktop environment. BTW, as an alternative way I thought of adding a dconf key for panel lock/unlock. This way novice users won't get confused at all. (I still think it won't result in that much confusion as locking/unlocking is a popular feature but just in case you are too worried about novice users...)

**Comment by lestcape** [comment]
@A-Shahbazi you understood my idea. The option that you mention, provide a way to change the state of one real characteristic, for one provider to another one. What you want, is change the visibility and/or access to an option. I'm not in opposite to have alternatives at all, if this involved a different behavior, but for add restrictions, yes i have my inconvenients.

**Comment by dalcde** [comment]
> @dalcde
> There are only two candidates for changing panel appearance: First, through settings > panel and second, by right clicking the panel. I don't understand how one might get confused when there is only 2 choices.

No. To most people there is only one choice - right click. Right clicking to access configuration options is almost a universal standard, and I'd say most people would expect a popup menu with configuration options to appear when you right click

> About right clicking special applets the desired action is obvious in my opinion: just show the applet's specific items without "about", "configure", and "Remove this applet".

Not exactly trivial since applets are allowed to tinker with the menus as they wish.

> By feeling solid I meant the panel should seem not changing as if configuring is not allowed like many desktops. This way we benefit capability of configuration beside the stability of panel layout. Furthermore, availability of configuration options in everyday use is superfluous. Just take another look to them: "Add applets ...", "Panel settings", "Themes", "All settings", "Troubleshoot"!!, "Modify panel", "Panel edit mode". It's obvious to me that they are not for everyday use.

Errr... do you randomly right click your panel when you are bored? The only reason why one would want to right click the panel is to access configuration options. The right click button isn't *that* easy to accidentally press.

**Comment by JosephMcc** [comment]
> Errr... do you randomly right click your panel when you are bored? The only reason why one would want to right click the panel is to access configuration options. The right click button isn't that easy to accidentally press.

This. It's the whole reason I find the idea of this option nothing but complication/confusion we don't need. Even if you click once all it does is open the menu, not change anything. You have to accidentally click a second time to trigger a menu item. Even then it doesn't change anything. It at most creates a state where you can make a change. At that point I'd like to know how how are changing something you don't mean to change.

**Comment by A-Shahbazi** [comment]
I must admit that accidental change of panel layout is hardly possible although changing some configuration or bringing a window up is not that impossible. Despite that I still think there should be setting to hide those bunch of configuration settings. So I came up with these suggestions which I think will address all concerns:

1. make configuration settings(including applet ones) depend on "Panel edit mode"(may be renaming the option to "Panel & Applets Configuration Enabled" makes more sense) and set the default option as enabled.
2. provide a dconf key to hide that option for power users who know what exactly they are doing.

This way the superfluous configuration options can be hidden until they are really needed. Moreover, there won't be any confusion because the option is there at right click for normal user and they get it from the first encounter to the desktop environment(it's enabled by default).
> ...The option that you mention, provide a way to change the state of one real characteristic, for one provider to another one.

The above suggestions are so because "Panel edit mode" changes a real characteristic and it will be from one provider to another one.
> ...The only reason why one would want to right click the panel is to access configuration options.

I think we can not rule people for using or not using right click. Many people do click here and there say when a program is not responding or taking long to open.
> ... The right click button isn't *that* easy to accidentally press.

!!?
I think one would need a better argument to defeat the whole concept of locking/unlocking.

**Comment by JosephMcc** [comment]
> !!?
I think one would need a better argument to defeat the whole concept of locking/unlocking.

Actually I would need a better argument than what you've given to think this needs to be implemented. You yourself said

> I must admit that accidental change of panel layout is hardly possible

Which pretty much undoes your whole argument ;)

**Comment by A-Shahbazi** [comment]
> Actually I would need a better argument than what you've given to think this needs to be implemented. You yourself said

It's just an OPTION and the main stream desktop environment do that in this way so I think there should be a good reason deviating from the whole linux os main stream. BTW, I have implemented it through a gsettings key and I have submitted a PR linuxmint/Cinnamon/pull/4807.

> Which pretty much undoes your whole argument ;)

You should pay attention to the difference between { panel not BEING solid / panel not FEELING solid / panel showing more than needed options on a simple right-click }. Moreover, locking/unlocking feature doesn't always prevent a bullet/bomb from going off! It just can be used to hide modification options when they are not needed. To sum up, panel not being solid is one of the reasons to implement panel locking/unlocking but without considering this aspect there's still good reason to implement it.

**Comment by Vahan86** [comment]
@JosephMcc, can we mark this issue as a feature request?

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
