### ISSUE TITLE
systray-applet: regression with qbittorrent built against qt5

### ISSUE THREAD

**Issue by leigh123linux** [linuxmint/Cinnamon#4721]
qbittorrent has always worked fine with systray-applet till the recent 2.8 changes, now it looks like this.

![screenshot-area-2015-10-19-074806](https://cloud.githubusercontent.com/assets/1299302/10571355/57387210-7636-11e5-8773-4f0138e70cb5.png)

```
info t=2015-10-19T08:16:18Z Hiding systray: network
info t=2015-10-19T08:16:18Z Adding systray: blueman-applet (40x40px)
info t=2015-10-19T08:16:19Z Resized blueman-applet with normalized size (32x32px)
info t=2015-10-19T08:16:23Z Adding indicator: qBittorrent
info t=2015-10-19T08:16:23Z IconCache: adding qbittorrent@40
info t=2015-10-19T08:16:24Z creating menu on org.kde.StatusNotifierItem-12992-2,/MenuBar
info t=2015-10-19T08:16:27Z Adding systray: unknown (40x40px)
info t=2015-10-19T08:16:28Z Resized unknown with normalized size (32x32px)
info t=2015-10-19T08:16:37Z IconCache: removing qbittorrent@40
info t=2015-10-19T08:16:37Z Destroying icon actor
info t=2015-10-19T08:17:05Z Adding systray: kvirc (40x40px)
info t=2015-10-19T08:17:06Z Resized kvirc with normalized size (32x32px)
```
additional info

qbittorrent built against qt4 works fine, it's only affected when built against qt5.

**Comment by two-dogs** [comment]
I use opensuse tumbleweed and will reference packages avail via opensuse repos to suggest a fix,
other distros should have equivalent to what i have installed.

Information for package qbittorrent a qt5 app;
------------------------------------
Repository: opensuse.org/tumbleweed/repo/oss
Name: qbittorrent
Version: 3.3.1-1.1
Arch: x86_64

Information for package libqt5-qtct:
------------------------------------
Repository: opensuse.org/tumbleweed/repo/oss
Name: libqt5-qtct
Version: 0.20-1.1
Arch: x86_64
Vendor: openSUSE
Installed: Yes
Status: up-to-date
Installed Size: 399.1 KiB
Summary: Qt5 Configuration Tool

once libqt5-qtct is running it should manage the qt5 app appearance and behavior as shown here;
http://i.imgur.com/J6qOxja.png
 
reference:
https://wiki.archlinux.org/index.php/Qt#Qt5
http://www.webupd8.org/2015/11/configure-qt5-application-style-icons.html

**Comment by ManIVIctorious** [comment]
Just installed qbittorrent to test. I can't reproduce this issue on cinnamon 3.0.7 with qbittorrent 3.3.6 (built with qt 5.7.0) on Arch Linux. Is this still an issue for you in latest cinnamon?

**Comment by leigh123linux** [comment]
I can't reproduce this issue  any more either

**Comment by two-dogs** [comment]
@ManIVIctorious  i think it should be closed also
