### ISSUE TITLE
StIcon doesn't support transparency

### ISSUE THREAD

**Issue by zagortenay333** [linuxmint/Cinnamon#4726]
Fixed in gnome-shell 3.16, and I believe it was fixed in 3.14 too.

I'd really like to be able to use transparency here. On top of that, I can't make them inherit the text colors,  which forces me to make a whole set of redundant variables just to fix this.

https://github.com/zagortenay333/ciliora-tertia-cinnamon/blob/5cfc856aec4946e27568417f973e11bb0de70c5b/Ciliora-Tertia/cinnamon/sass/base/_colors.scss#L24-L29

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
