### ISSUE TITLE
hibernate on mouse battery low?!!!!!

### ISSUE THREAD

**Issue by brianjmurrell** [linuxmint/Cinnamon#4729]
In today's episode of Completely Silly and Bizarre Computer Tricks, my desktop PC (not a laptop, no battery in it) just hibernated (or failed to, so rebooted) because my mouse battery died.

**Comment by pixunil** [comment]
This should be an issue with the power plugin of [cinnamon-settings-daemon](https://github.com/linuxmint/cinnamon-settings-daemon/issues).

However, one question: did you receive a message, and with which content?

Examples are:

Mouse (correct) | Battery (wrong)
---------------------|-------------------
Wireless mouse is low in power (_charge_%) | Battery low
Mouse battery low | Battery critically low
This device will soon stop functioning if not charged. | Computer will hibernate very soon unless it is plugged in.

I'm suspecting that you're computer thinks that the mouse battery is a real laptop battery.

**Comment by brianjmurrell** [comment]
Actually, no.  No message, or none that I saw before the machine just started shutting down.

> I'm suspecting that you're computer thinks that the mouse battery is a real laptop battery.

Indeed.  My suspicion also.  Although hovering/clicking on the task bar icon currently shows it's a mouse.

**Comment by pixunil** [comment]
Are you absolutely sure, that your mouse battery was in this moment out of power and there is no other reason, like accidentally pressing the power button?
Also, might be a very stupid question, can you try to reproduce, like removing the battery if possible?

Anyway, what is your Cinnamon version? Is it reproducible in 2.8?

**Comment by brianjmurrell** [comment]
On Mon, 2015-10-26 at 10:40 -0700, pixunil wrote:
> Are you absolutely sure, that your mouse battery was in this moment
> out of power and there is no other reason, like accidentally pressing
> the power button?

Please don't be insulting.  I'd know if I reached out over 3 feet to my
tower to "accidentally" press the power button.  And yes, I had to
change the mouse batteries when this happened so they were definitely
dead and the cause of the shutdown.

> Also, might be a very stupid question, can you try to reproduce, like
> removing the battery if possible?

Not at this moment.  I cannot afford the time of having my machine shut
itself down right now.

> Anyway, what is your Cinnamon version?

2.6.13

>  Is it reproducible in 2.8?

I don't know.  My distribution, Fedora, does not have 2.8 available
yet.

**Comment by leigh123linux** [comment]
If low battery on your mouse is causing this issue it indicates a problem with upower.

**Comment by brianjmurrell** [comment]
On Tue, 2015-10-27 at 00:01 -0700, leigh123linux wrote:
> If low battery on your mouse is causing this issue it indicates a
> problem with upower.

Are upower's actions/activities logged anywhere so that we can go see
what it did and why?

**Comment by leigh123linux** [comment]
I don't think there is a log but you can monitor with this command

```
upower -m
```

**Comment by brianjmurrell** [comment]
On Tue, 2015-10-27 at 08:20 -0700, leigh123linux wrote:
> I don't think there is a log but you can monitor with this command
> 
> ```
> upower -m
> ```

Right.  I was hoping there was something to post-mortem rather than pre
-mortem.

So that command above yields:

```
$ upower -m
Monitoring activity from the power daemon. Press Ctrl+C to cancel.
[12:46:54.146]	device changed:    
 /org/freedesktop/UPower/devices/mouse_hid_00o1fo20oe5o51o03_battery
[12:46:54.146]	device changed:    
 /org/freedesktop/UPower/devices/mouse_hid_00o1fo20oe5o51o03_battery
[12:46:54.146]	device changed:    
 /org/freedesktop/UPower/devices/mouse_hid_00o1fo20oe5o51o03_battery

```

Seems to indicate that it is seeing a mouse.

**Comment by dralley** [comment]
@pixunil If this is confirmed as an issue with UPower, this issue can probably be closed

**Comment by Vahan86** [comment]
@brianjmurrell, is this issue still relevant in Cinnamon 3.0.x?

**Comment by brianjmurrell** [comment]
I don't think so.  Mouse batteries died in the last day or two and there was no suspend.

**Comment by JosephMcc** [comment]
I'm going to go ahead and close this then. It can always be reopened if it is still happening.
