### ISSUE TITLE
Battery icon in systray often outdated

### ISSUE THREAD

**Issue by RalfJung** [linuxmint/Cinnamon#4735]
It is often the case that the battery icon in the systray is not being updated correctly. For example, in the following screenshot, you can see that the battery is at 43%, but the icon still shows more than 50%. It even sometimes happens that while the laptop is connected to AC, the icon still shows just the battery and no indication of the device being charged. The information shown in the on-demand popup is generally correct, so this looks like a bug in cinnamon, and not in upower.

![screenshot from 2015-10-22 19-54-59](https://cloud.githubusercontent.com/assets/330628/10673636/2dee80ca-78f7-11e5-8eb4-9cbc00c3223e.png)

This is with Cinnamon 2.6.13 on Debian testing.

**Comment by pixunil** [comment]
Try to upgrade to [`2.8`](http://segfault.linuxmint.com/2015/10/early-access-to-cinnamon-2-8/), it should be fixed there.
Duplicates: #4516 #4481 #4329, please search in future also for _closed_ issues.
