### ISSUE TITLE
Windows not opening in center when set in 'windows' settings module.

### ISSUE THREAD

**Issue by jayeemsuh** [linuxmint/Cinnamon#4740]
This is occuring for me on an out of the box install of LM 17.2 when opening Nemo. The placement seems to still be following 'smart placement.' Other windows such as gedit seem to follow the desired placement setting.

**Comment by AdmiralAnimE** [comment]
+1
It's very annoying. If there is another window open, most of the time Nemo opens in one of the corners of the screen. When it's set to center, I want it to stay centered..

**Comment by JosephMcc** [comment]
This isn't a bug in Cinnamon. Some applications like Nemo place windows where they want regardless of that setting. I assume this could be changed in Nemo since it's ours but the issue really belongs there.
