### ISSUE TITLE
black icons & windows cinnamon 2.4

### ISSUE THREAD

**Issue by hackoon** [linuxmint/Cinnamon#4742]
I did test mint cinnamon 17.1 from dvd image on thinkpad T42 with radeon M7 (rv200)

* nemo icons -> all **black**
* open windows -> all **black**
* panel -> ok
* background -> ok
* menu -> ok

compiz runs fine
I know its an old radeon with only 32Mb it should still be able to run cinnamon...

**Comment by Vahan86** [comment]
@hackoon, is this still an issue for you with Cinnamon 3.0?

**Comment by hackoon** [comment]
I will test it

**Comment by JosephMcc** [comment]
The video card your running just isn't really up to the task of running Cinnamon.
