### ISSUE TITLE
Multiple input device settings

### ISSUE THREAD

**Issue by uiii** [linuxmint/cinnamon#4744]
Hi, is it possible in Cinnamon to set multiple input devices differently? I have laptop with trackpoint and wireless mouse, but there is in Cinnamon only settings for "mouse" which is applied to both devices. E.g. in XFCE is I'm able to set each device another way. Thanks

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
