### ISSUE TITLE
Can't change name of first workspace

### ISSUE THREAD

**Issue by plagasul** [linuxmint/Cinnamon#4752]
Linux Mint 17.2 Rafaela, Cinnamon 64bit

I created four workspaces. I try to rename them. I can rename all of them EXCEPT for the first workspace. 

When clicking on the first workspace name on the workspace grid screen, a text cursor appears, then dissappears with a small visual glitch (brief and subtle zoom in out of the spaces)

It should be possible to change the name of the first workspace.

The problem happens persistently

A workaround is to give the second workspace the name you were going to give to the first workspace. Then delete first workspace.

**Comment by mtwebster** [comment]
I can't reproduce this - what cinnamon theme are you using?  Can you try with "cinnamon" or "Linux Mint" themes (if you're not already)?

Thanks

**Comment by plagasul** [comment]
The desktop theme I am using is EnhancedMinty. And you are right, it does work well with Cinnamon team.

**Comment by JosephMcc** [comment]
This should probably be reported to the theme developer.
