### ISSUE TITLE
Rubbish-bin applet causes cinnamon to crash [fedora 23 beta]

### ISSUE THREAD

**Issue by frac2738** [linuxmint/Cinnamon#4753]
Description of problem:
Cinnamon completely crashes when trying to empty the bin using the panel applet.
It does not happen all the time but quite often.
I've been using the beta for two weeks (as main OS) and it happens 4-5 times a day.

Version-Release number of selected component (if applicable):

fedora 23 beta
cinnamon-2.6.13-10.fc23.x86_64

How reproducible:

Add the "Rubbish bin" applet to the panel and select "Empty rubbish bin"

Steps to Reproduce:
1. click on the applet "Rubbish Bin" in the panel
2. select "Empty rubbish bin"
3. select "Yes" when prompted

Actual results:

An error appears saying that cinnamon has crashed (no codes or other info). Cinnamon completely disappear and after 3-4 seconds a screen asks if you want to restart cinnamon.
After "yes" is selected, cinnamon restarts and everything works fine.

Expected results:

The bin is emptied without errors/crashes.

Additional info:

It does not happen all the time

**Comment by mtwebster** [comment]
Fixed by https://github.com/linuxmint/Cinnamon/commit/e98e9c88e0190b4785dc025ba23cf2038b9f90dd
