### ISSUE TITLE
Cinnamon 2.6.13 frequently crashes

### ISSUE THREAD

**Issue by MarceloRuiz** [linuxmint/Cinnamon#4756]
I am experiencing frequent Cinnamon crashes. It mostly happens when I am browsing the Internet with Firefox.
The first noticeable thing is that the mouse stops responding, then there is a spike in CPU or GPU usage (Cinnamon freezes here) and nothing really works after that (no Ctrl+Esc, no Ctrl+Backspace, no Alt+F1...10 to access TTYs).
I did think that the problem was related to using Kernel 4.1, so I decided to do a fresh Mint install and keep the stock kernel. The problem was not shown for days (with kernel 4.1 it happened everyday) but it did happen to me today.
I don't understand how if an app is crashing (Firefox maybe?) how it can take down the whole desktop.
I would like to provide logs. Can anyone please tell me where to find all the relevant logs to help finding the cause for this bug?
I have a Toshiba Qosmio X500 - Core i7 - nVidia GTS360M with nVidia 340.93 driver.

**Comment by JosephMcc** [comment]
Is it freezing or crashing? These can be two different things. A crash usually drops you into fallback mode with a dialog asking if you would like to restart cinnamon.

**Comment by MarceloRuiz** [comment]
It's a freezing then... Thanks for clarification

**Comment by JosephMcc** [comment]
Thanks for answering. I'm going to close this since we have an open issue to gather as much info as we can on this problem in one place. Could you please read the first post by mtwebster here: https://github.com/linuxmint/Cinnamon/issues/4072 and add your information.
