### ISSUE TITLE
Cinnamon don't launch, error 5483

### ISSUE THREAD

**Issue by therevenger** [linuxmint/Cinnamon#4757]
Hi, 

Using linux mint 17.2, cinnamon 2.6.13, openjdk-amd64 1.7.0_85.

User session was open, watching HTML5  video at Youtube (anything amazing so), then the edge  windows desappear, software  menu are freeze, I see a black screen on the desktop instead of my wallpaper  but not arround of Cairo-Dock. Firefox loose my profile, but not Thunderbird.
That's amazing !

Tring those commande line : cinnamon reset, or only cinnamon, I Have this : 
>(cinnamon:5483): Cjs-WARNING **: JS ERROR: Error: Requiring CjsPrivate, version none: Typelib >file for namespace 'GdkPixbuf', version '2.0' not found
>@resource:///org/gnome/gjs/modules/gettext.js:36
>@/usr/share/cinnamon/js/ui/environment.js:10
>@`<main>`:1
>
>Window manager warning: Log level 32: Execution of main.js threw exception: JS_EvaluateScript() >failed

I have try every thing (cinnamon --replace ...; reinstalling cinnamon+nemo+compiz; dpkg-reconfigure ...; even under the TTY, nothing change.

Thank you.

Nicolas

**Comment by JosephMcc** [comment]
Did this only happen once or can it be reproduced? You can't run Cinnamon with Compiz. Does it happen if you aren't using Cairo-Dock?

**Comment by JosephMcc** [comment]
Closing since there has been no response.
