### ISSUE TITLE
Volume Control Makes Full Screen Programs Freeze

### ISSUE THREAD

**Issue by ekianjo** [linuxmint/Cinnamon#4760]
It does not happen all the time, but frequently enough - this happens usually within games, or in web videos made to run fullscreen (youtube or others). When this happens you cannot do anything except alt+tabbing and killing the whole program/window affected by the issue.

**Comment by JosephMcc** [comment]
I tested this with fullscreen youtube videos in Firefox and couldn't reproduce it.

**Comment by ManIVIctorious** [comment]
Can't reproduce this either, is this still an issue for you in cinnamon 3.0?

**Comment by Vahan86** [comment]
@JosephMcc, can we close this issue?
