### ISSUE TITLE
XRDP or alternative

### ISSUE THREAD

**Issue by anton-johansson** [linuxmint/Cinnamon#4761]
Hi!

I've been trying to get a good remote desktop solution working for Linux Mint with the Cinnamon desktop environment, no success so far.

I've tried xrdp and tightvncserver, but Cinnamon crashes instantly when connecting to the remote desktop. I assume this is because Cinnamon is 3D-accelerated, which xrdp does not support. I should probably ask this elsewhere, but is there a plan for xrdp to support 3D-accelerated desktop environments?

I also considered changing to Linux Mint MATE, because xrdp works fine there. But MATE had some other troubles, so I'd like to keep Cinnamon.

Is there any good alternatives to XRDP? I want the screen to be locked on the remote computer when I connect through remote desktop, just like Windows RDP. It would also be good to "hijack" the existing active session on the computer, just like Windows RDP, but this is not a requirement.

Thanks!

**Comment by benhaze** [comment]
You could try TeamViewer...

**Comment by anton-johansson** [comment]
I was hoping there was an alternative, but I'll give it a try.

**Comment by ManIVIctorious** [comment]
The linuxvoice magazine had a grouptest for remote Desktop Programms, you can download the pdf by following this link 
http://www.linuxvoice.com/issues/012/gt12.pdf

**Comment by JosephMcc** [comment]
Closing since this is more a question about xrdp then Cinnamon.
Also https://github.com/linuxmint/Cinnamon/issues/934
