### ISSUE TITLE
applets doesnt react to the highlight button anymore

### ISSUE THREAD

**Issue by Hanmac** [linuxmint/Cinnamon#4762]
i don’t know why it did happen but applets which are added to the taskbar or other bars doesn’t react to the highlight button in their settings any more. (so nothing is highlighted)

**Comment by clefebvre** [comment]
Possible regressions:

https://github.com/linuxmint/Cinnamon/commit/98ce2319a5fc2b917d86e7b3ef6d29cc05e0fc76

https://github.com/linuxmint/Cinnamon/commit/f075328c6e983b3cae3c4bf0a0fe5e05f0c8f29c

**Comment by clefebvre** [comment]
Fixed by https://github.com/linuxmint/Cinnamon/commit/c6f2394403810c68e261c10730761571bdeded54
