### ISSUE TITLE
Switching windows by  direction

### ISSUE THREAD

**Issue by cpaulik** [linuxmint/Cinnamon#4764]
Would it be possible to implement keybindings for switching to another window by direction?

For example if I have more than two windows tiled I would like to select the window below or to the right of the current window using a keybinding. This allows for more direct switching of windows than hitting `alt-tab` a certain number of times.

**Comment by JosephMcc** [comment]
This gets complicated. What if I have a window tiled to the left of my monitor and 2 windows tiled to the right, one top half, one bottom half. Where should the keybinding take me?

**Comment by cpaulik** [comment]
This could be configurable. e.g. `top-first` `left-first`. 
I'm currently trying to start writing an extension that might be able to replicate a few features I miss from Awesome WM including this one in Cinnamon. But I'm only at the stage of trying to wrap my head around the API.

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
