### ISSUE TITLE
unable to add application to startup applications LMDE 2 Cinnamon

### ISSUE THREAD

**Issue by Pepelluepe** [linuxmint/Cinnamon#4765]
When I select `Startup Applications`/`Add`/`Choose Application`, I am able to search through and choose an application in the `Applications` pop-up, but neither the `Close` or `Add Application` button seem to have any effect. The window only goes away when using the `x` on the frame.  When using `Add` /`Custom Command` I am able to add my information and clicking `Add` closes the window, but does not add the program to the Startup Applications list.
This is on LMDE 2 "Betsy" running Cinnamon 2.6.13 and has been happening for over a month every time I have tried to do this.  It has worked on this computer at least at some point because I have in the past added 2 programs to the list.

**Comment by JosephMcc** [comment]
Cinnamon 2.8 should now be available on Betsy. Will try this again and see if it's been fixed?

**Comment by Pepelluepe** [comment]
I am now on Cinnamon 2.8.6 and going through `Startup Applications/Add/Choose Application`, I am still able to choose the application, but not only do `close` and `add application` not close or add application, but now the `Choose Application` window will not close. I had to log out to get rid of it. The `Custom Command` behavior remains the same.

I'm sorry that I didn't reply sooner. I didn't see the notification about your response.

**Comment by JosephMcc** [comment]
I just tried this on betsy. Going to startup applications->Add->Choose application. I chose "Calculator" and hit "Add Application" and worked fine.
Could you maybe try running `cinnamon-settings startup` in a terminal and try again? See if it produces any errors.

**Comment by Pepelluepe** [comment]
I'm getting 
```
Python module
Could not find bluetooth module; is the cinnamon-control-center package installed?
Loading Startup Applications module
Failed to load /home/jstoume/.config/autostart/steam.desktop
__init__ took 147.882 ms
Traceback (most recent call last):
  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_startup.py", line 527, in on_add_app
    desktop_file_name = self.find_free_basename(os.path.basename(desktop_file_dir))
  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_startup.py", line 563, in find_free_basename
    while (self.find_app_with_basename(basename) is not None and
  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_startup.py", line 576, in find_app_with_basename
    if basename == app.basename:
AttributeError: AutostartApp instance has no attribute 'basename'
```
I checked and `cinnamon-control-center` was installed and up to date.
I looked next at the `steam.desktop` file. I was initially trying to add steam to startup applications, but this output was from trying to add calculator as a test. I deleted `steam.desktop` and was then able to add calculator, remove calculator, and then add steam. 
It seems that I just had a corrupted file. Thank you for helping me find a solution.
