### ISSUE TITLE
cinnamon-control-center can not load panel module

### ISSUE THREAD

**Issue by kronolio** [linuxmint/Cinnamon#4767]
Loading Calendar module and Keyboard module
/usr/share/cinnamon/cinnamon-settings/bin/capi.py:53: Warning: instance of invalid non-instantiatable type 'CcDateTimePanel'
  return GObject.new(panel_type)

crash cinnamon-control-center

==================================

Display module
/usr/share/cinnamon/cinnamon-settings/bin/capi.py:53: Warning: invalid cast from 'CcDisplayPanel' to '<invalid>'
  return GObject.new(panel_type)
/usr/share/cinnamon/cinnamon-settings/bin/capi.py:53: Warning: instance of invalid non-instantiatable type 'CcDisplayPanel'
  return GObject.new(panel_type)

====================================

list /usr/lib{64}/cinnamon-control-center-1/panels/
-rwxr-xr-x 1 root root  56K окт 28 23:20 libcolor.so
-rwxr-xr-x 1 root root  72K окт 28 23:20 libdate_time.so
-rwxr-xr-x 1 root root  81K окт 28 23:20 libdisplay.so
-rwxr-xr-x 1 root root 561K окт 28 23:20 libnetwork.so
-rwxr-xr-x 1 root root  73K окт 28 23:20 libregion.so
-rwxr-xr-x 1 root root 193K окт 28 23:20 libsoundnua.so
-rwxr-xr-x 1 root root  36K окт 28 23:20 libuniversal-access.so

os: gentoo
cinnamon: 2.8.2

**Comment by lisuml** [comment]
Similar problems on cinnamon 2.8.2 on Manjaro Linux. Affected settings modules:

* Accessibility
* Date & Time
* Color
* Display
* Graphics Tablet
* Networking

**Comment by kronolio** [comment]
How to fix it? This is upstream bug?

**Comment by lisuml** [comment]
@kronolio: If you are on x86_64 can you check if your `/usr/lib64` is a symlink to `/usr/lib` please?

**Comment by kronolio** [comment]
os:gento64 multilib
in gentoo 
/usr/lib64 is a directory
/usr/lib symlynk to /usr/lib64

ls -alh /usr/lib
lrwxrwxrwx 1 root root 5 июл 24  2014 /usr/lib -> lib64

**Comment by kronolio** [comment]
paths += ["/usr/lib/x86_64", "/usr/lib/x86_64-linux-gnu"]
            if not os.path.islink("/usr/lib"):
               paths += ["/usr/lib64"]

it works in gentoo

**Comment by lisuml** [comment]
Yes. I'm on manjaro and I have opposite situation: 

```
$ ls -l /usr/lib* -d
drwxr-xr-x 238 root root 135168 Nov 13 14:23 /usr/lib
drwxr-xr-x  45 root root  45056 Nov 13 09:15 /usr/lib32
lrwxrwxrwx   1 root root      3 Sep 30 21:43 /usr/lib64 -> lib
```

So I'm trying to do it generic.

**Comment by kronolio** [comment]
maybe just leave
paths += ["/usr/lib"] for 86_64 bit system ?

**Comment by lisuml** [comment]
It can break on distributions where there is only `/usr/lib64` directory.

**Comment by kronolio** [comment]
hm
leave as is and gentoo developers to write gentoo specific patch

I'm just a user in this case. I understand that where you have to change to work. thank

**Comment by lisuml** [comment]
https://github.com/lisuml/Cinnamon/commit/a22c2249c5aa36911690fb1863a63c766b8763c2

Should be fine for both Manjaro and Gentoo.

**Comment by kronolio** [comment]
the last code works for me. thank you again

**Comment by dralley** [comment]
I believe this can then be closed?

**Comment by kronolio** [comment]
yes

**Comment by JosephMcc** [comment]
For future reference, the person who opened the original issue can close it as well.
