### ISSUE TITLE
Odd Mouse Bug on Source Engine Based Games

### ISSUE THREAD

**Issue by netsudo** [linuxmint/Cinnamon#4768]
When you're searching for a game on CS:GO for instance and you're in the community game browser the mouse and in-game cursor will become desynchronized. This leads to the in-game cursor being stuck in a certain position. This would be okay, but the cursor you're left with is very buggy, it doesn't like to move and you have to drag the mouse very hard to get it to move inches. Once it gets onto the community list it moves around fine over it, but getting it on top of there is painful. 

This also happens with the media controls when you're watching demos. The cursor just doesn't want to move, and you have to keep pushing the mouse very aggressively towards the media controls inch by inch, once it's on top of the media controls it works smoothly until you take it off again. It's somewhat of a frustrating issue, I tested this in XFCE as well but it works fine on there, same with KDE, only Cinnamon has this odd mouse sticking.

**Comment by Vahan86** [comment]
@netsudo, is this still an issue for you in Cinnamon 3.0?

**Comment by Vahan86** [comment]
@JosephMcc, can we close the issue?
