### ISSUE TITLE
Wrong directory association in Cinnamon applets on Debian 8

### ISSUE THREAD

**Issue by kehugter** [linuxmint/Cinnamon#4769]
Using Cinnamon in Debian 8 testing. This wasn't an issue with Mint Cinnamon 17.2, at least with an up-to-date system some weeks ago.

After compiling and installing [bomi](https://github.com/xylosper/bomi) (`make` + `make install`), the directory shortcuts in Cinnamon applets (the `Rubbish Bin` applet, to name one installed by default) open with bomi.

Removing bomi from the PATH fixes the association back to Nemo. Needles to say, that's not the solution I'm looking for. Nemo opens fine if I chose it from the menu. Softlinked directories open with Nemo too. There's no "bomi" entry in `/usr/share/applications/mimeinfo.cache`. So I guess that this is exclusively an error in Cinnamon handling of URIs.

Installing bomi the wrong way, with the deb package in the [developer's Ubuntu PPA](https://launchpad.net/~darklin20/+archive/ubuntu/bomi/+packages) leads to the same result.

**Comment by ManIVIctorious** [comment]
Could be linked to your personal mime app list. You could try to execute the following in a terminal:
`$ xdg-mime default nemo.desktop inode/directory`

This should set nemo as default for opening directories. I hope that helped

**Comment by kehugter** [comment]
Thanks for your answer ManIVIctorious. Unfortunately for debugging purposes, I can not longer reproduce after you posted your comment. Re-compiled and re-installed (same system, some variations in the packages) bomi, putting it in and out of the PATH, made different permutations in the "Preferred Applications"... nothing seems to _break_ the applet shourtcuts now.

I couldn't say what triggered this change. I haven't made any further efforts to fix it since I posted this originally at [stackexchange](http://unix.stackexchange.com/questions/238007/wrong-directory-association-in-cinnamon-applets-on-debian-8) last week. I made no relevant Cinnamon configurations either.

I'm closing this issue for now.

**Comment by kehugter** [comment]
It's back!

`xdg-mime default nemo.desktop inode/directory` fixed it, thanks again. I just had to create the directory `applications` in `/home/user/.local/share/` because it didn't exist and `xdg-mime` complained.

I re-installed some packages to compile [toxcore](https://github.com/irungentoo/toxcore/) and [qTox](https://github.com/tux3/qTox) so I guess that the responsible is among them. Here's the list

>check
checkinstall
debhelper
dh-strip-nondeterminism
gir1.2-gtk-2.0
libatk1.0-dev
libavdevice-dev
libcairo-script-interpreter2
libcairo2-dev
libfile-stripnondeterminism-perl
libgdk-pixbuf2.0-dev
libgtk2.0-dev
libice-dev
libmail-sendmail-perl
libopenal-dev
libopus-dev
libpango1.0-dev
libpixman-1-dev
libqrencode-dev
libqrencode3
libsm-dev
libsodium-dev
libsubunit-dev
libsubunit0
libsys-hostname-long-perl
libvpx-dev
libxcb-shm0-dev
libxcomposite-dev
libxcursor-dev
libxft-dev
libxi-dev
libxinerama-dev
libxrandr-dev
libxrender-dev
libxss-dev
po-debconf
qrencode
x11proto-composite-dev
x11proto-randr-dev
x11proto-render-dev
x11proto-scrnsaver-dev
x11proto-xinerama-dev

Plus toxcore and qTox that were `# make install`ed

**Comment by ManIVIctorious** [comment]
Well if my command worked this is no cinnamon bug. Seems to me, that the install process just links the program to open directories. I always have the same issue with easytag (that's why I know the fix :-) )

**Comment by JosephMcc** [comment]
If this is not a Cinnamon bug will you please close it?

**Comment by kehugter** [comment]
Sure
