### ISSUE TITLE
Add option to click categories in Menu, instead of mouse hover

### ISSUE THREAD

**Issue by hiboudev** [linuxmint/Cinnamon#4771]
Hi,

I don't really like buttons that react to mouse hover. Most of the time it is less efficient than simply clicking the targeted button. With a delay of 0 ms it opens each category you hover, and with a higher delay you have to wait a bit before to select the button, I don't feel this intuitive.

Would it be possible to add an option to open categories with click instead of mouse hover ?

Thanks, I like Cinnamon desktop, good job! :)

**Comment by hiboudev** [comment]
I forgot to say that sometimes the hover doesn't work well and the button under mouse is not selected. Then, if I move a little it selects the button.

**Comment by ManIVIctorious** [comment]
This is by intention, if you move the mouse a little to the right it doesn't change the category so you can hover directly to the applications of the current category without changing category.
I never had any problems with this not working well

**Comment by hiboudev** [comment]
Maybe I sometimes move a little the mouse on right, while selected a category, and that doesn't select the category I target but the previous one.

But anyway, I would appreciate an option to use click instead of hover, so it will always work as expected. :-)

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
