### ISSUE TITLE
Slider and separator objects

### ISSUE THREAD

**Issue by zagortenay333** [linuxmint/Cinnamon#4772]
Why are the popup separators and slider not using these? I still have to use the `.popup-menu-separator` and  `.popup-slider-menu-item`

**Comment by JosephMcc** [comment]
Originally it did. However in an effort to avoid breaking existing third party applets it was left the way it was.

**Comment by zagortenay333** [comment]
Yeah, I figured. Is there perhaps a way to make it inherit both classes?
