### ISSUE TITLE
Loss of Shortcuts Tied to Super Key When Nemo is Killed

### ISSUE THREAD

**Issue by gritty-gitty** [linuxmint/Cinnamon#4774]
Although this happens when *Nemo* is killed (either from terminal or by *xkill*, it doesn’t matter), the issue is more related to *Cinnamon* itself as it’s the latter that’s supposed to manage key shortcuts.

I’ve noticed it in two recent LM 17.2 installations (on different hardware, so that driver problems can be ruled out): if *Nemo* — in its current version 2.6.7 of the Rafaela repositories — is killed by force, shortcuts defined with the [Super] key get lost. This is a regression in more than a matter compared to v2.4.x:
* There is no convenient way to restart *Nemo* with [Super+e];
* As the menu cannot be called any more with [Super] alone, the file manager can only be started by mouse, which is confusing if someone prefers using the keyboard, or knows of the dedicated shortcut [Super+e].

**Comment by JosephMcc** [comment]
When you get the chance, try this again on Cinnamon 2.8. Here if I type xkill in a terminal and then select the nemo window my <Super> still works fine. <Super+e> also reopens nemo. If this has been fixed then I'd like to close this.

**Comment by gritty-gitty** [comment]
Indeed, the issue has gone with Cinnamon 2.8, so you can close this for sure.
