### ISSUE TITLE
Empty keyboard shortcuts continues to trigger on last value set before clearing

### ISSUE THREAD

**Issue by henriklindgren** [linuxmint/Cinnamon#4777]
Linux Mint 17.2 (Rafaela)
Cinnamon 2.6.13

To reproduce, 
 * open dconf
 * go to org.cinnamon.desktop.keybindings.wm
 * save content of begin-move to a text-editor
 * set begin-move to []
 * close dconf
 * select a window and press the key combination you saved in the text file, begin-move will trigger.

It is not bound to the default value, which I thought first, it seems to just keep the last non-empty value you set.

**Comment by JosephMcc** [comment]
It works once you restart Cinnamon. Would be nice if that wasn't needed.

**Comment by JosephMcc** [comment]
The same behaviour occurs when doing this from the Cinnamon settings UI.

**Comment by JosephMcc** [comment]
I can no longer reproduce this on git master.
