### ISSUE TITLE
Cinnamon 2.6: Panel Vanishes when taking full-screen screenshot

### ISSUE THREAD

**Issue by jtflynnz** [linuxmint/Cinnamon#4779]
So I just found this out while taking screenshots for another bug, but I can reproduce every time I try this (not sure why). Each time I take a screenshot with the built in tool, the panel vanishes while looking at the window for the screenshot (as though full-screen) even though it is a small window. Closing the window or restarting Cinnamon resolves this. 

edit: Also this also only occurs with "Grab the whole screen," using it for a window or screen region does not create this issue.

**Comment by dralley** [comment]
I can verify that this still occurs in the 2.8 release

**Comment by ManIVIctorious** [comment]
I can't reproduce this with cinnamon 3.0.7 and gnome-screenshot 3.20.1
Is this still an issue for you?

**Comment by jtflynnz** [comment]
Unfortunately I'll have to post back later, I haven't had time to migrate my laptop to Mint 18 yet. I'll try it again this weekend!

**Comment by Vahan86** [comment]
@jtflynnz, does this issue still relevant to Cinnamon 3.4?

**Comment by jtflynnz** [comment]
I will recommend closing this issue if no one else is able to test this, Unfortunately I no longer am running Cinnamon on any machines, so I will not have a method to test this. If someone else who reproduced the bug is able to check, great, otherwise it likely was fixed in one of the updates since this issue occurred with 2.6/2.8.
