### ISSUE TITLE
Screen brightness and power

### ISSUE THREAD

**Issue by prensing** [linuxmint/Cinnamon#4780]
The settings for screen brightness and power really could be improved:

1) there is no setting for the minimum brightness when on battery. It sets it down to essentially 0. I would like to be able to set that value.

2) when the machine is back on AC, it does not put the brightness back up to 100%.

**Comment by dralley** [comment]
> 2) when the machine is back on AC, it does not put the brightness back up to 100%.

Maybe not 100%, but I agree that being able to set an "On AC" brightness level and an "On Battery" brightness level might be useful.

**Comment by overkill22** [comment]
I agree.
Especially the minimum brightness. It should be by default something >0.

**Comment by igordovgaluk** [comment]
Linked to https://github.com/linuxmint/Cinnamon/issues/5646

**Comment by JosephMcc** [comment]
Relevant issue: https://github.com/linuxmint/Cinnamon/issues/5646 and https://github.com/linuxmint/Cinnamon/issues/7080
