### ISSUE TITLE
2.8: Merge Power applet into Battery applet

### ISSUE THREAD

**Issue by grenzor** [linuxmint/Cinnamon#4782]
Don't understand why there are two applets in the system tray in the new version of Cinnamon:

1) Battery/Power settings
2) Applet to choose between Performance and Power save

Would make more sense to merge the 2nd into the 1st and save system tray space.

**Comment by JosephMcc** [comment]
What two applets are they? I only see the Power Manager applet. Unless the other one your talking about is the Inhibit applet.

**Comment by grenzor** [comment]
The default "Battery/Power settings" applet and the new "CPU frequency scaling indicator" applet.

**Comment by JosephMcc** [comment]
It wouldn't be the first time I was wrong but as far as I know there is no CPU frequency scaling indicator applet included with Cinnamon.

**Comment by grenzor** [comment]
It's in Cinnamon 2.8.

**Comment by JosephMcc** [comment]
You may have installed something that has indicator support. Since that is new in 2.8 you would probably see if now where you didn't before. Indicators that show in the systray and applets are actually separate things. Since we don't actually ship the applet your talking about, is it ok to close this?

**Comment by Garibaldo** [comment]
A strange indicator/applet appeared on my systray as well. Here is a screenshot:
[url=http://postimage.org/][img]http://s27.postimg.org/6akir6sn7/screenshot_cinnamon_2015_11_04_184149.png[/img][/url]
[url=http://postimage.org/]images hosting[/url]

**Comment by JosephMcc** [comment]
I'm going to go ahead and close this since the original topic isn't really relevant since we don't even include one of the two applets you want combined ;)
