### ISSUE TITLE
[2.8.2] Can't find additional drivers anymore

### ISSUE THREAD

**Issue by entr** [linuxmint/Cinnamon#4784]
Just updated to 2.8.2. Can't find additional drivers anymore in Menu applet or Settings. In fact typing "settings" in menu quick search doesn't show general settings menu entry but only the settings sections show up (like Account, Applets, Background, Bluetooth etc.).

**Comment by JosephMcc** [comment]
For me typing drivers in menu turns up the driver manager. It also seems to be in the main cinnamon settings window at the bottom.

**Comment by entr** [comment]
OK, turns out I was missing `mintdrivers`, which could be caused by me messing with `ubuntu-drivers-common` dep earlier. Just installed `mintdrivers` again.
