### ISSUE TITLE
login screen exposes passwords

### ISSUE THREAD

**Issue by brianally** [linuxmint/Cinnamon#4786]
I like that I don't need to always type my username in the login UI, simply typing my password. However, periodically, it does prompt for the username first. This is a problem because it's not obvious that it is doing so until i notice my password on the screen in plaintext, because there is only a single text input and it's very easy to miss the label.

On a system with just a single user (that can login, ie. not including daemon users) the login screen should never prompt for the username. It should, of course, still show the *expected* username as it does now. But it shouldn't occasionally revert to prompting for it.

**Comment by Topperfalkon** [comment]
Agreed. Fortunately people don't make a habit of sitting over my shoulder when I'm unlocking my PC, but the occasional times where this happens it's particularly annoying to find I've started to type my password in plaintext on the screen

**Comment by kmkom** [comment]
I also run into this pitfall. It should be fixed to avoid exposing the password. 
Still, Linux Mint Cinnamon is terrific!

**Comment by dralley** [comment]
+1

**Comment by grenzor** [comment]
Agreed, also a problem

**Comment by JosephMcc** [comment]
This is an issue with MDM: https://github.com/linuxmint/mdm

**Comment by brianally** [comment]
-1 Would you mind linking to the specific issue?

**Comment by JosephMcc** [comment]
What do you mean -1? This issue has nothing to do with Cinnamon. The link was to the MDM repo which is the proper place for this. Sorry if I wasn't clear.

**Comment by Topperfalkon** [comment]
This issue has been raised here:
https://github.com/linuxmint/mdm/issues/139

**Comment by brianally** [comment]
Thank you @Topperfalkon for clearing that up.
