### ISSUE TITLE
Desktop icons cannot move above primary monitor

### ISSUE THREAD

**Issue by mtjohnson47** [linuxmint/Cinnamon#4791]
Cinnamon will not allow me to place icons on the top monitor.  If I try, it moves them to the same x coordinate on the bottom right monitor

1) The version and edition of Linux Mint you are using (if you are not sure, open a terminal and run "mintwelcome").
Linux Mint 17.2 Cinnamon amd64

2) What you did for the problem to happen, and how to reproduce it.
1. Use multiple monitors with the secondary above the primary
2. Try to move a desktop icon to the secondary monitor

3) What happened.
Icon gets moved to below top of primary monitor

4) What you expected to happen instead.
Icon goes where I place it

5) If the problem happened once, sometimes, or always.
Always

Monitor setup for reference:
![screenshot from 2015-11-04 16 25 16](https://cloud.githubusercontent.com/assets/5100948/10954298/32bfe24a-8312-11e5-8315-3e8d5915cf97.png)

**Comment by mtwebster** [comment]
Should be fixed in 2.8 - see https://github.com/linuxmint/Cinnamon/issues/1437 for related issue

**Comment by mtjohnson47** [comment]
I can move windows up there (see the 2 in the screenshot, normal windows work too), just not icons.  The other bug report is similar but not the same thing, so this should be reopened

**Comment by JosephMcc** [comment]
The fix sorted a number of issues with stacked monitors. Even though the commit message doesn't say it, this should be fixed as well.
