### ISSUE TITLE
System tray buggy

### ISSUE THREAD

**Issue by grenzor** [linuxmint/Cinnamon#4793]
When I first upgraded to 2.8, everything seemed fine for system tray. But after a few restarts, programs that are supposed to be appearing on system tray are not appearing - even after opening a program fresh.

**Comment by leigh123linux** [comment]
You probably need to disable appindicator support.

https://github.com/linuxmint/Cinnamon/issues/4741

**Comment by JosephMcc** [comment]
Could you be a bit more specific as to what apps are having issues?

**Comment by grenzor** [comment]
Update Manager has stopped showing up in systray even after doing what is said in comment 2 and opening update manager.

**Comment by JosephMcc** [comment]
Update manger seems fine here. If you open it and go to Edit->Preferences do you possibly have "Hide the update manager after applying updates" and "Only show a tray icon when updates are available" turned on.

**Comment by grenzor** [comment]
Both are turned off.

**Comment by geckolinux** [comment]
Sorry, it looks like this was happening because of the outdated Cinnamon 2.6 theme I was using. Seems OK now with the theme updated to the 2.8 version.

**Comment by geckolinux** [comment]
Please re-open this bug. Thanks.

**Comment by PNH1960** [comment]
Linux Mint 17.2 64 bit Cinnamon 2.6.13. 

I have exactly the same problem with the system tray and the Update Manager icon. It suddenly disappeared and does not come back after reboots, shut downs and checking update manager config (I change it back and forth after the problem appeared, but it makes no difference.

 I am new to Linux so I can't say much more.
