### ISSUE TITLE
Effects problem

### ISSUE THREAD

**Issue by kajzersoze** [linuxmint/Cinnamon#4796]
If I select 'Fly up, down' or 'Fly down, up' for Effects style everything works fine, except in Kodi where the panel is always visible (and it shouldn't be)
Not just in Kodi, same thing happens with youtube in full screen.
If I select some other effects style then everything is fine and panel is not visible.
Any idea what's going on and how can I fix this ?

**Comment by Vahan86** [comment]
@kajzersoze, is this issue still relevant to Cinnamon 3.0?

**Comment by kajzersoze** [comment]
I'm not using Cinnamon for a long time now, so I don't know.

**Comment by Vahan86** [comment]
@kajzersoze, thanks for reply. In this case, can you please close this issue?

**Comment by kajzersoze** [comment]
Was thinking about that, but maybe the bug is still there, it's not that hard to reproduce it, in fact it's very simple, but nobody cared about this for a year now, so ok I'll close it, why not :)
