### ISSUE TITLE
cinnamon-settings: accessibility section style is inconsistent with other sections

### ISSUE THREAD

**Issue by gwvr** [linuxmint/Cinnamon#4797]
The accessibility section of system settings uses standard (old style) tabs, whereas I think all other sections use CSD style tabs (or whatever they're called).
This affects Cinnamon 2.6 and 2.8 under LMDE2.

**Comment by JosephMcc** [comment]
Yes, there are a couple of panes that could still stand some tweaks for the changes that came in cinnamon settings in 2.6. Hopefully can fix these up for 3.0.

**Comment by JosephMcc** [comment]
mtwebster revamped the accessibility settings for 3.0 and they are much improved.
