### ISSUE TITLE
Intermittent crash when pressing Alt-Space

### ISSUE THREAD

**Issue by wchargin** [linuxmint/Cinnamon#4800]
Unfortunately, this bug is entirely intermittent. But it's been bothering me for a few months, so I was hoping that someone could point me in the right direction to investigate/fix it.

The gist of it is that sometimes, when I press <kbd>Alt</kbd><kbd>Space</kbd>, Cinnamon crashes. That is, the windows all lose their title bars for about a quarter second, then they all disappear and reveal my desktop, then about two seconds pass, then the windows re-appear as Cinnamon relaunches.

If this happens twice in the same session, I'll get a dialog asking me if I want to use fallback mode. If it happens three times, Cinnamon drops down into the mode where it basically looks like GNOME 2.

I have tried opening Looking Glass and inspecting the log immediately after this happens, but there are no error messages.

I have no Cinnamon extensions, third-party desklets, third-party drivers, etc.

Has anyone else experienced this issue? If not, is there anything I can do to capture more useful information the next time it happens?

(Cinnamon 2.6.13, metacity 2.34.13, LM 17.2, Intel Haswell-ULT integrated graphics)

**Comment by JosephMcc** [comment]
If you haven't, after this happens check ~/.xsession-errors. It will always show a Cinnamon restart and may show what led to it crashing.

**Comment by WChargin** [comment]
@JosephMcc Okay! I'll save the log next time it happens. Thanks.

**Comment by WChargin** [comment]
Okay! Here's the last paragraph of [the log output](https://gist.github.com/WChargin/d4d9f4fd00e33935e867#file-xsession-errors-L1225-L1249). The crash happened right at 13:34:44. I hit `Alt-Space` in `gnome-terminal` in vim, if that matters, but I've had it happen in Chrome and `evince`, too, so I don't think that's really related.

```
(gnome-terminal:14941): GLib-GIO-CRITICAL **: g_settings_get: the format string may not contain '&' (key 'monospace-font-name' from schema 'org.gnome.desktop.interface'). This call will probably stop working with a future version of glib.
Cjs-Message: JS LOG: Removing an access point that was never added
Cjs-Message: JS LOG: Removing an access point that was never added
Cjs-Message: JS LOG: Removing an access point that was never added
Cjs-Message: JS LOG: Removing an access point that was never added
Cjs-Message: JS LOG: Removing an access point that was never added
Cjs-Message: JS LOG: Removing an access point that was never added
Cjs-Message: JS LOG: Removing an access point that was never added
Cjs-Message: JS LOG: Removing an access point that was never added
Cjs-Message: JS LOG: Removing an access point that was never added
Cjs-Message: JS LOG: Removing an access point that was never added
Cjs-Message: JS LOG: Removing an access point that was never added
Window manager warning: Log level 8: gdk_window_get_support_multidevice: assertion 'GDK_IS_WINDOW (window)' failed
Window manager warning: Log level 8: gdk_window_get_effective_parent: assertion 'GDK_IS_WINDOW (window)' failed
Window manager warning: Log level 8: g_object_ref: assertion 'G_IS_OBJECT (object)' failed
Window manager warning: Log level 8: g_object_ref: assertion 'G_IS_OBJECT (object)' failed
Window manager warning: Log level 8: gdk_window_get_device_position_double: assertion 'GDK_IS_WINDOW (window)' failed
cinnamon-session[2226]: WARNING: Application 'cinnamon.desktop' killed by signal 15
Cjs-Message: JS LOG: About to start Cinnamon
St-Message: cogl npot texture sizes SUPPORTED
Window manager warning: Trying to remove non-existent custom keybinding "magnifier-zoom-in".
Window manager warning: Trying to remove non-existent custom keybinding "magnifier-zoom-out".
Cjs-Message: JS LOG: Cinnamon started at Mon Nov 09 2015 13:34:44 GMT-0800 (PST)
Cjs-Message: JS LOG: network applet: Cannot find connection for active (or connection cannot be read)
Cjs-Message: JS LOG: network applet: Found connection for active
```

I've seen the format string `GLib-GIO-CRITICAL` previously and it hasn't caused a crash, so I don't know whether that's related, either. (Wish these were timestamped! :confused:)

The full log is here: 	https://gist.github.com/WChargin/d4d9f4fd00e33935e867

Any ideas?

**Comment by WChargin** [comment]
Okay, it happened again—this log is much cleaner: https://gist.github.com/WChargin/1490696e619fb8daf4f7.

This time, the crash happened in Chrome.

By comparing the two logs, the following common lines stand out to me:
```
Window manager warning: Log level 8: gdk_window_get_support_multidevice: assertion 'GDK_IS_WINDOW (window)' failed
Window manager warning: Log level 8: gdk_window_get_effective_parent: assertion 'GDK_IS_WINDOW (window)' failed
Window manager warning: Log level 8: g_object_ref: assertion 'G_IS_OBJECT (object)' failed
Window manager warning: Log level 8: g_object_ref: assertion 'G_IS_OBJECT (object)' failed
Window manager warning: Log level 8: gdk_window_get_device_position_double: assertion 'GDK_IS_WINDOW (window)' failed
```
These happened immediately before the restart each time. Not sure if that caused the crash, was caused by the same thing that caused the crash, or occurred during the restart.

Possibly related: [Eclipse Bug 427776](https://bugs.eclipse.org/bugs/show_bug.cgi?id=427776), where the user notes:

> Now I have seen two crashes today with same pattern: I'm pressing a shortcut on keyboard to bring up an in-place dialog, like "Quick fix" or "Refactor" and only shadow of the new dialog is drawn and JVM immediately starts dumping core.

Perhaps the Eclipse context menu and the GTK…top-left window dropdown menu…suffer from the same problem?

**Comment by WChargin** [comment]
Happened again. `GDK_IS_WINDOW` and `G_IS_OBJECT` are present (same five lines). The `sibling window` complaint isn't in the most recent 600 lines, so I doubt it's the problem.

Looks like we have a culprit—thoughts?

**Comment by WChargin** [comment]
In case it's helpful, Cinnamon hasn't crashed yet today, so here is a "control" log: https://gist.github.com/WChargin/36a7adcccb54a1ba464b

In particular, "removing an access point that was never added" abounds, and "sibling window…not in stack" appears 18 times as well. However, the `GDK_IS_WINDOW` assertions appear as well. It's possible they're still the problem, though.

**Comment by WChargin** [comment]
Okay, this is about the cleanest log you're going to get (happened immediately after launch):
https://gist.github.com/WChargin/d8bd01cbda8c5c26e45d

@JosephMcc: What can I do to make sure this gets addressed? I'm happy to help.

```
/etc/mdm/Xsession: Beginning session setup...
localuser:wchargin being added to access control list
Script for none started at run_im.
Script for auto started at run_im.
Script for default started at run_im.
Script for none started at run_im.
Script for auto started at run_im.
Script for default started at run_im.
GNOME_KEYRING_CONTROL=/run/user/1000/keyring-G77rsF
SSH_AUTH_SOCK=/run/user/1000/keyring-G77rsF/ssh
GNOME_KEYRING_CONTROL=/run/user/1000/keyring-G77rsF
SSH_AUTH_SOCK=/run/user/1000/keyring-G77rsF/ssh
GPG_AGENT_INFO=/run/user/1000/keyring-G77rsF/gpg:0:1
GNOME_KEYRING_CONTROL=/run/user/1000/keyring-G77rsF
SSH_AUTH_SOCK=/run/user/1000/keyring-G77rsF/ssh
GPG_AGENT_INFO=/run/user/1000/keyring-G77rsF/gpg:0:1
GNOME_KEYRING_CONTROL=/run/user/1000/keyring-G77rsF
SSH_AUTH_SOCK=/run/user/1000/keyring-G77rsF/ssh
GPG_AGENT_INFO=/run/user/1000/keyring-G77rsF/gpg:0:1
cinnamon-session[3741]: WARNING: Failed to start app: Unable to start application: Failed to execute child process "/usr/sbin/synconf.sh" (No such file or directory)
Starting Dropbox...
** (nm-applet:4040): CRITICAL **: nm_secret_agent_register: assertion 'priv->registered == FALSE' failed
Cjs-Message: JS LOG: About to start Cinnamon
nm-applet-Message: using fallback from indicator to GtkStatusIcon

** (nemo:4039): WARNING **: Can not determine workarea, guessing at layout
St-Message: cogl npot texture sizes SUPPORTED
Window manager warning: Trying to remove non-existent custom keybinding "magnifier-zoom-in".
Window manager warning: Trying to remove non-existent custom keybinding "magnifier-zoom-out".
Cjs-Message: JS LOG: Cinnamon started at Wed Dec 02 2015 10:55:29 GMT-0800 (PST)
Cjs-Message: JS LOG: network applet: Cannot find connection for active (or connection cannot be read)
Done!
failed to create drawable
Cjs-Message: JS LOG: network applet: Found connection for active

(gnome-terminal:4166): GLib-GIO-CRITICAL **: g_settings_get: the format string may not contain '&' (key 'monospace-font-name' from schema 'org.gnome.desktop.interface'). This call will probably stop working with a future version of glib.
Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x2c00001 (New Tab - )
Window manager warning: Log level 8: gdk_window_get_support_multidevice: assertion 'GDK_IS_WINDOW (window)' failed
Window manager warning: Log level 8: gdk_window_get_effective_parent: assertion 'GDK_IS_WINDOW (window)' failed
Window manager warning: Log level 8: g_object_ref: assertion 'G_IS_OBJECT (object)' failed
Window manager warning: Log level 8: g_object_ref: assertion 'G_IS_OBJECT (object)' failed
Window manager warning: Log level 8: gdk_window_get_device_position_double: assertion 'GDK_IS_WINDOW (window)' failed
cinnamon-session[3741]: WARNING: Application 'cinnamon.desktop' killed by signal 15
Cjs-Message: JS LOG: About to start Cinnamon
St-Message: cogl npot texture sizes SUPPORTED
Window manager warning: Trying to remove non-existent custom keybinding "magnifier-zoom-in".
Window manager warning: Trying to remove non-existent custom keybinding "magnifier-zoom-out".
Cjs-Message: JS LOG: Cinnamon started at Wed Dec 02 2015 10:55:42 GMT-0800 (PST)
Cjs-Message: JS LOG: network applet: Cannot find connection for active (or connection cannot be read)
Cjs-Message: JS LOG: network applet: Found connection for active

(gnome-terminal:4567): GLib-GIO-CRITICAL **: g_settings_get: the format string may not contain '&' (key 'monospace-font-name' from schema 'org.gnome.desktop.interface'). This call will probably stop working with a future version of glib.
```

**Comment by WChargin** [comment]
I've now experienced the same issue with Linux Mint 17.3 and the latest Cinnamon, this time running within a VM with a Windows host. Surely this means it can't *all* be my fault! Have you ever encountered this @JosephMcc ?

**Comment by JosephMcc** [comment]
No I haven't but I don't really use that shortcut.

**Comment by osaad** [comment]
WCharging, do u have a nVidia card? I get the same with nVidia-352 and 340 drivers, but it doesn't happen with nouveau

**Comment by WChargin** [comment]
I'm running on a Thinkpad T440s with no custom drivers or firmware. Here's `lspci`:

```shell
$ lspci | grep VGA
00:02.0 VGA compatible controller: Intel Corporation Haswell-ULT Integrated Graphics Controller (rev 0b)
```

**Comment by WChargin** [comment]
Okay. This just happened again (as it continues to do frequently; I just haven't been reporting it every time), except this time it killed the browser window I was using once Cinnamon restarted. This is much worse than a mild inconvenience.

Here's `.xsession-errors`: https://gist.github.com/WChargin/9b11bd4718baa74bfb89

**Please let me know what I can do to help fix this or help this get fixed.**

**Comment by mtwebster** [comment]
It's possible it may have been fixed here: https://github.com/linuxmint/muffin/commit/35425b3196e88722521c54ff6d2af6e350ad94d4

Since I've never been able to reproduce this particular issue, you'd have to try the nightly builds to check, however, or else build muffin (branch `2.8-maintenance`)

**Comment by Vahan86** [comment]
@wchargin, is this still an issue for you in Cinnamon 3.0?

**Comment by wchargin** [comment]
@Vahan86 I'm on 2.8.8 LTS and have (intentionally) not upgraded; sorry.

**Comment by clefebvre** [comment]
We believe this issue is fixed. Please test against the latest Cinnamon version (3.6). If the issue happens again, create a new issue and add a stracktrace.
