### ISSUE TITLE
changeable workspaces on both screens

### ISSUE THREAD

**Issue by brianjmurrell** [linuxmint/Cinnamon#4803]
Right now, if one has two monitors, one can choose to have workspaces on the primary monitor and not on the secondary monitor, or workspaces shared across both monitors.

It would be nice and useful if one could have independent workspaces on each monitor the way having multiple X screens used to be able to do.

**Comment by ManIVIctorious** [comment]
I totally agree that this would be incredible useful. This feature has already been requested in #3507 .
So please close this one
