### ISSUE TITLE
Cinnamon 2.8.2: Wrong telegram icon in tray when indicators support is enabled

### ISSUE THREAD

**Issue by marcogiannini** [linuxmint/Cinnamon#4805]
Wrong telegram icon in tray with cinnamon 2.8.2 when indicators support is enabled
![senzanome](https://cloud.githubusercontent.com/assets/4943897/11023246/ac7bd42c-8673-11e5-8648-db44264055ff.jpg)
Icon telegram should appear blue and not yellow.

Okay when indicators are off
![schermata del 2015-11-09 00 03 46](https://cloud.githubusercontent.com/assets/4943897/11023308/868e7150-8675-11e5-9112-d57dbcaadc40.png)

**Comment by ManIVIctorious** [comment]
I am quite sure this isn't a cinnamon issue. Much more likely this is connected to your icontheme or to the app itself. 

You could check if this persists with other iconthemes and when it does you should file a bugreport/featurerequest to Telegramm (or live with the orange Icon)

**Comment by JosephMcc** [comment]
Ok, maybe this is a dumb question since I don't use telegram, but why is it wrong. Do the different color icons represent different states, or is is just pulling the wrong icon from the theme?

**Comment by marcogiannini** [comment]
Same status, only start Telegram. The blue icon is the exact one, the yellow icon is the wrong one. The theme used is the standard Linux Mint which does not provide a custom icon for Telegram.

**Comment by JosephMcc** [comment]
I don't think this is a Cinnamon issue. The indicator controls what icon it wants.

**Comment by marcogiannini** [comment]
The bug is only about Cinnamon with indicators support enabled. I tried on Ubuntu with Unity, KDE Plasma 5, GNOME Shell and it's all ok.

**Comment by pixunil** [comment]
I reproduced the issue yesterday, but now it's resolved. I updated both telegram and Cinnamon, so I can't say which update brings the success.
![telegram-blue-in-tray](https://cloud.githubusercontent.com/assets/7093655/11708355/c6816752-9f0e-11e5-941c-9fcec9676ed8.png)

**Comment by lestcape** [comment]
There are an array of pixmap and one with a good size will selected. Probably a better algorithm is needed for select the icon here: https://github.com/linuxmint/Cinnamon/blob/master/js/ui/indicatorManager.js#L968
