### ISSUE TITLE
Buggy applets must be removed manually

### ISSUE THREAD

**Issue by ACinnamonUserInUK** [linuxmint/Cinnamon#4811]
At present (up to and including Cinnamon 2.8), is a user installs an applet that does not work properly - such as the Recoll applet, or the Internet search applets (both applets, by the way, that it would be really good to have working) - an error message is displayed, the applet shows as installed, and the applet cannot successfully be uninstalled with the GUI.

This is a bad situation for novice users. What should happen: the applet should not installable in the first place or, if it is installable, it should be removable.

**Comment by ACinnamonUserInUK** [comment]
EDIT: Actually, it seems the applets *do* uninstall, even though initiating the uninstall generates an error message saying the applet in question may need to be manually uninstalled (though not details are given about how to do that). What made me think the applets had not been removed was that, until closing and re-opening the 'available applets' window, the applets showed, there, as installed.

**Comment by mtwebster** [comment]
Just tried both of these - they install successfully for me here, but give an error when you try to add them to your panel.  They uninstall just fine... I'm not sure why you're experiencing different behavior.

Could you try reproducing all of this, while running cinnamon settings from a terminal (to see what, if any, errors you get there).

fyi, these applets get installed to `~/.local/share/cinnamon/applets`, in case you need to remove manually.
