### ISSUE TITLE
Alt-tab hangs halfway between switching from one window to another . .

### ISSUE THREAD

**Issue by ACinnamonUserInUK** [linuxmint/Cinnamon#4817]
. . is there is heavy CPU (and/or disk?) activity, as for instance if one alt-tabs when installing a .deb package. I have tested this on the latest Cinnamon only on the '3d coverflow' version of alt-tab, but I am pretty sure that, at least in Cinnamon 2.7, it affected other versions of alt-tab too.

What should happen: well, pretty much anything but this, obviously!

Mint 17.2 Cinnamon x64, on Dell laptop with Intel graphics and an SSD and dual-core processor.

**Comment by Vahan86** [comment]
@ACinnamonUserInUK, is this still an issue for you in Cinnamon 3?

**Comment by ACinnamonUserInUK** [comment]
No, it seems fixed, thank you (although a perhaps related problem, namely that occasionally my hidden top panel drops down for no apparent reason and then rolls itself up again does persist).
