### ISSUE TITLE
SignalManager fails...

### ISSUE THREAD

**Issue by lestcape** [linuxmint/Cinnamon#4818]
SignalManager fails with:

(cinnamon:5629): Cjs-WARNING **: JS ERROR: Exception in callback for signal: blacklist: TypeError: invalid 'in' operand signal[0]
SignalManager.prototype._signalIsConnected@/usr/share/cinnamon/js/misc/signalManager.js:120
SignalManager.prototype.disconnectAllSignals@/usr/share/cinnamon/js/misc/signalManager.js:208
IconActor.prototype.destroy@/usr/share/cinnamon/js/ui/indicatorManager.js:1121
_emit@resource:///org/gnome/gjs/modules/signals.js:140
AppIndicator.prototype.setInBlacklist@/usr/share/cinnamon/js/ui/indicatorManager.js:335
MyApplet.prototype._onSystrayManagerChanged@/usr/share/cinnamon/applets/systray@cinnamon.org/applet.js:116
_emit@resource:///org/gnome/gjs/modules/signals.js:140
SystrayManager.prototype.registerRole@/usr/share/cinnamon/js/ui/systray.js:15
MyApplet.prototype._init@/usr/share/cinnamon/applets/network@cinnamon.org/applet.js:1656
MyApplet@/usr/share/cinnamon/applets/network@cinnamon.org/applet.js:1644
main@/usr/share/cinnamon/applets/network@cinnamon.org/applet.js:2280
createApplet@/usr/share/cinnamon/js/ui/appletManager.js:329
addAppletToPanels@/usr/share/cinnamon/js/ui/appletManager.js:256
finishExtensionLoad@/usr/share/cinnamon/js/ui/appletManager.js:59
loadExtension@/usr/share/cinnamon/js/ui/extension.js:451
onEnabledAppletsChanged@/usr/share/cinnamon/js/ui/appletManager.js:197

Please i really don' t know how is working this line:
https://github.com/linuxmint/Cinnamon/blob/master/js/misc/signalManager.js#L120

But to fix the problem, we can simple replace the line:
```
else if ('signalHandlerIsConnected' in signal[0])
```
with:
```
else if (signal[0].toString().indexOf('signalHandlerIsConnected') != -1)
```
I can not swap to use the signalmanager in the appindicator because of this problem.

Regards.

**Comment by Cobinja** [comment]
If I read the signal manager correctly, it should be signal[1] in line 120, not signal[0], which contains the signal name.
Better way to check whether a JS object has a certain function: hasOwnProperty()
I don't have the time right now, but I will check later today.

**Comment by Cobinja** [comment]
If I read the signal manager correctly, it should be signal[1] in line 120, not signal[0], which contains the signal name.

**Comment by lestcape** [comment]
As i say, i don't know how will be or what is the real problem. What i receive is an incompatible operation (in) because recive as an argument the signal[0], and this is an string (for non clutter objects) and is supposed that will be an array. Could be probably a change in cjs because i know @clefebvre merged the commit where @dalcde fixed this problem a time ago, i never tested the result before now.
