### ISSUE TITLE
cinnamon freezes every now and then when meld is started via git mergetool

### ISSUE THREAD

**Issue by calestyo** [linuxmint/cinnamon#4819]
Hey.

This is forwarded from: http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=804821
Cinnamon version is: 2.6.13 ... everything from Debian sid

I have a very strange issue.
Every now and then (say at least 1 out of 10, rather more) when I do
a git mergetool, which then starts meld, the whole destkop freezes.
When it froze, CPU goes up 100% as long as cinnamon is displayed -
when I switch e.g. to the console, it stops eating up CPU.

This never happens when I run meld normally, e.g. via the terminal
or via git difftool... maybe the difference is that mergetool
does a 3-way-diff, which I don't do otherwise.
I also have no clue whether this is cinnamon related, or perhaps
at a lower level (GTK?).

Nothing helps (e.g. killing meld on the console nor Ctrl-Alt-Esc)
except Ctrl-Alt-Backspace (i.e. killing X).

There's nothing particular in the logs, at leat not in xorg's log.
There's no .xsession-errors.

glass.log contains only the following:
info t=2015-11-12T00:43:30.484Z PlacesManager: Updating devices
info t=2015-11-12T04:07:50.338Z Adding systray: pidgin (20x20px)
info t=2015-11-12T04:07:50.338Z Resized pidgin (16x16px)
info t=2015-11-12T04:07:50.368Z Adding systray: pidgin (20x20px)
info t=2015-11-12T04:07:50.368Z Resized pidgin (16x16px)
info t=2015-11-12T04:07:51.238Z loading default theme
info t=2015-11-12T04:07:51.264Z BackgroundManager: org.gnome.desktop.background changed!
info t=2015-11-12T04:07:51.271Z BackgroundManager: org.gnome.desktop.background changed!
info t=2015-11-12T04:07:51.272Z BackgroundManager: org.gnome.desktop.background changed!
info t=2015-11-12T04:07:51.272Z BackgroundManager: org.gnome.desktop.background changed!
info t=2015-11-12T04:07:51.273Z BackgroundManager: org.gnome.desktop.background changed!
info t=2015-11-12T04:07:51.273Z BackgroundManager: org.gnome.desktop.background changed!
info t=2015-11-12T04:07:51.274Z BackgroundManager: org.gnome.desktop.background changed!

The freeze was at 04:07:51Z ... when I log in again, after restarting
X, the previously set background image is gone (i.e. not the file,
but it's just no longer selected, and I have to configure it again).

Also, when I switch back from the console to the frozen cinnamon,
the pidgin systray icon's backgroun (i.e. in the square) looks bogus,
as if the transparent areas would be wrongly drawn.

Not much, but perhaps you have an idea on what to do.

Cheers,
Chris.

**Comment by mtwebster** [comment]
Can you try something for me?

Open up `/usr/share/cinnamon/js/ui/backgroundManager.js`

Comment out this line:

https://github.com/linuxmint/Cinnamon/blob/master/js/ui/backgroundManager.js#L36

Simply insert a `//` at the beginning of line.  Save the file, then restart Cinnamon (or log out/in.)

Let me know if you can still reproduce the issue.

Thanks!

**Comment by calestyo** [comment]
Unfortunately that doesn't seem to solve the issue.

**Comment by calestyo** [comment]
I just had, for the first time, the same issue when gedit was started from Evolution (by opening an attachment).

Yeah, not really much more info... but perhaps it may give a hint.

**Comment by iandsamson** [comment]
Forgive me in advance, I am a noob. Had a total system freeze yesterday just after upgrading to Linux Mint 17.3 'Rosa'. I had open these programs: Firewall, Terminal, Google Chrome, Pale Moon 25.8, and LibreOffice. I was editing text, changing the font size, when the entire machine froze. Only the mouse pointer moved. Ctrl+Alt+Del did nothing, clicking on open apps did nothing, had to press the RESET button. Is there a log file somewhere that may explain what happened? There are many in /var/log but I don't know in which one to look. Thanks.

**Comment by KarelJakubec** [comment]
+1

I am experiencing the same issue. It happens just on some merges, but it is deterministic - if merge caused it once, the same merge will cause it again. There is one exception - if it happens and I switch to console and restart gdm, then I can safely run git mergetool and it passes on that file and I can do the merge. But it may happen again on another file and then the process is the same - in worst case one restart of gdm per file in merge.  And I can confirm the missing background image... :)

Is there anything I can capture for you guys? Any log file that would help?

**Comment by calestyo** [comment]
I just had such a freeze again, though this time it wasn't caused by meld... it rather "just happened".
So not sure if it was really the same type of freeze as I've reported originally

I could solve that by kill -HUP <pid of cinnamon>

**Comment by calestyo** [comment]
And one more update:
It may actually be the same freeze... cause the background was gone, as well.
And interestingly,.. in the same session I cannot set it again... if I choose another wallpaper, it still stays empty.

**Comment by calestyo** [comment]
Taking back the "And interestingly,.. in the same session I cannot set it again... if I choose another wallpaper, it still stays empty." from my last comment... that was wrong O:-)

**Comment by calestyo** [comment]
I've also noticed that this happens more often recently,... but at all kinds of different "actions"... switching a workspace, clicking somewhere...
Debian has updated all kinds of MESA libs recently in sid...so maybe it's something at that level

**Comment by KarelJakubec** [comment]
I have another observation, which could possibly help. The freeze occurs only when file to me merged in meld is simultaneously open in another editor (PyCharm). If I close the editor before doing the merge it works ok and no freeze occurs or at least it did not happen so far.

I will try to confirm it in the opposite way - if it happens everytime when the file is open in another editor during merge or not - and will let you know the result.

**Comment by maxyz** [comment]
Mmh, is this another instance of a bug caused by the recently-used files that gtk tracks? So far we have seen gtk stating every file listed in the ~/local/share/recently-used.xbel whenever a gtk program opens or closes a file. Which breaks havoc if any file is inaccesible, or calling stat is very slow (such as when the files are in a network fs).

Would you mind adding a line:
gtk-recent-files-enabled=0
to your ~/.config/gtk-3.0/settings.ini under [Settings] in order to check if this solves the issue?

Thanks,

**Comment by mtwebster** [comment]
You can temporarily disable recent files in cinnamon-settings-> privacy as well

**Comment by calestyo** [comment]
@maxyz Hmm the problem is, up today I haven't found a way to make this issue fully reproducible... perhaps your above explanation helps me herewith.
So just adding that option wouldn't really tell me whether it solve it or not

**Comment by maxyz** [comment]
@calestyo Were you able to reproduce this issue after disabling the gtk recent-files mangling?

**Comment by calestyo** [comment]
Uhm...  it's a bit difficult to say, I still have recent files enabled in cinnamon-settings-> privacy... and haven't seen the issue for a while.
But I was using meld/git mergetool very rarely recently, so it may be just that I didn't trigger it anymore...

**Comment by gmh04** [comment]
+1

**Comment by calestyo** [comment]
I haven't seen this issue in quite a while... (and I had recent files enabled in privacy).

So I would kinda guess it's fixed, and thus close it now.
But if someone still sees it, feel free to re-open.

Thanks,
Chris
