### ISSUE TITLE
Not sound notification on Transmission in Cinnamon DE

### ISSUE THREAD

**Issue by varlesh** [linuxmint/Cinnamon#4820]
Transmission - default torrent-client for Linux Mint, but sound notification not playing after finishing downloading.
LOG:

```
alex@pc ~ $ transmission-gtk
Failed to play sound: Sound disabled
```

Config:

```
...
    "torrent-added-notification-enabled": true, 
    "torrent-complete-notification-enabled": true, 
    "torrent-complete-sound-command": "canberra-gtk-play -i complete-download -d 'transmission torrent downloaded'", 
    "torrent-complete-sound-enabled": true,
...
```

Linux Mint 17.2 amd64
Cinnamon 2.6
Transmission 2.84

**Comment by varlesh** [comment]
Hm, It's very strange. canberra-gtk-play need enabled event-sounds:
```
gsettings set org.cinnamon.desktop.sound event-sounds true
```
And as deafault=true on sources:
https://github.com/linuxmint/cinnamon-desktop/blob/master/schemas/org.cinnamon.desktop.sound.gschema.xml.in.in
And on Cinnamon 2.6 event-sound deafault=true in /usr/share/glib-2.0/schemas/org.cinnamon.desktop.sound.gschema.xml
![2015-11-13 03 46 25](https://cloud.githubusercontent.com/assets/8083855/11135742/3128b18e-89b9-11e5-85d8-306d4492140d.png)
But on dconf-editor this scheme event-sounds  as default=false
![2015-11-13 03 48 44](https://cloud.githubusercontent.com/assets/8083855/11135763/79da3d62-89b9-11e5-88d8-4f4d78caeaf1.png)

Why?

**Comment by anandrkris** [comment]
Hi, Is this issue still present?

**Comment by Vahan86** [comment]
@JosephMcc, can we close this issue since there is no response from OP for over 2 months?
