### ISSUE TITLE
Visual feedback in Menu

### ISSUE THREAD

**Issue by regs01** [linuxmint/Cinnamon#4821]
Menu needs some visual feedback (hover background) while moving mouse, so it wouldn't feel like it lags. Right now there is only active item background. But submenus takes a time to load, so category highlight lags heavily behind the mouse.

**Comment by JosephMcc** [comment]
I'm a little confused. For me, hovering over items in the categories column does provide visual feedback unless I'm misunderstanding what the issue is. What cinnamon theme are you using?

**Comment by regs01** [comment]
Numix, but no matter of theme i use it's always same behavior. Menu items gets highlighted only for opened categories. Since categories opens automatically while you hovering menu if feel a bit of hovering feedback. But since categories takes a time to load it also feels like it very laggy hover effect.

**Comment by ManIVIctorious** [comment]
@regs01 could you be a bit more specific on what exactly you mean with "visual feedback" maybe a mockup could be helpful. I have to admit, I absolutely don't know what you are requesting

**Comment by regs01** [comment]
Hover effect. Highlighting an item of category when moving mouse over it.

There is no hover effect atm. It will only highlight activated item, so it feels very laggy, or you won't see it at all if using option not to open categories automatically on mouseover.

**Comment by JosephMcc** [comment]
> or you won't see it at all if using option not to open categories automatically on mouseover.

There is no option for that.

**Comment by Odyseus** [comment]
Hello, everybody.

@regs01, the *hover effect* of categories in the menu is linked to the activation of the categories. You can tweak the activation delay on categories by changing the option called **Mouse hover delay** on the menu settings window.

I also initially thought that my menu was very laggy because categories were taking very long to activate on mouse hover. And it was because I had set the **Mouse hover delay** option to 200 milliseconds, thinking that that delay was used by the option **Open the menu when I move my mouse over it**. But, then I read its tooltip that says *Delay between switching categories*. That was a *face palm moment* for me!! LOL

And, like JosephMcc said, there isn't an option in the Cinnamon default menu to disable activation of categories on mouse hover. This repository might not be the right place to report your issue.

**Comment by JosephMcc** [comment]
> I also initially thought that my menu was very laggy because categories were taking very long to activate on mouse hover. And it was because I had set the Mouse hover delay option to 200 milliseconds, thinking that that delay was used by the option Open the menu when I move my mouse over it. But, then I read its tooltip that says Delay between switching categories. That was a face palm moment for me!! LOL

Well you are the only one. I had no idea it worked that way. I can't see why it does. I always assumed that served the same purpose you did. I'm going to find out if there is a reason for that. If so it needs to be named better than that.

**Comment by regs01** [comment]
There are in forks, so they help to understand the problem.  

@Odyseus even if you set to minimum categories takes time to load, so it still feels very laggy. and if you bypass some category it won't visually feedback mouse movement at all, so it feels inconsistent.

**Comment by mtwebster** [comment]
I think the best bet is to remove this delay from having an effect on category selection, and only affect the menu itself opening.. in other words, make it behave just like the setting description says.

With this setting disabled, I see no category delay - any delay that might be there is likely based on individual computer performance.  All items and categories are preloaded and sorted.  Adding any sort of visual feedback beyond this to show that you've moused over another category but it isn't selected yet would simply re-introduce some sort of delay, just for the sake of accounting for said delay.

**Comment by regs01** [comment]
There is delay and very noticable - over 100 ms. And again if you bypass it wouldn't highlight at all.

**Comment by regs01** [comment]
There is delay and very noticeable - over 100 ms. And again if you bypass it wouldn't highlight at all.
Checked nightly, same there is no hover effect at all. It will only highlight active category.

**Comment by mtwebster** [comment]
What theme are you using?   Try a different one, does it behave the same? There is no programmed delay, adding a highlight effect will do nothing but add needless processing.  It's possible the theme you're using (if it's not a stock mint theme) has a style transition set, which would introduce a delay via the theme engine.  We don't recommend this for the menu applet, and removed it long ago from the themes we maintain - check the .css file of the theme you're using for "transition-duration."

**Comment by regs01** [comment]
video
https://yadi.sk/d/EFXiiu6ev3pSD

**Comment by mtwebster** [comment]
I don't see any issue there.  I'm done with this.  I'm not sure you understand what 100ms means.  You're asking for more effects, yet complain that you perceive the menu is slow.  This is contradictory.

**Comment by regs01** [comment]
Not an effect, but visual feedback on mouse movements. Lack of visual feedback makes it feel laggy. You can see massive skips on video.

**Comment by lestcape** [comment]
@regs01 what you try to say it's that this can be see as a video, when there are some frames with a damage and the video player have the capability to skip this frames and as consequence, you can see how one scene will transform in another, without follow a real time-line, that a continuous and sustained movement should create in the real world?
