### ISSUE TITLE
Don't dim screen when video is playing

### ISSUE THREAD

**Issue by grenzor** [linuxmint/Cinnamon#4823]
Currently, if a video is playing on a player or an online site, the screen is dimmed. Only when a screen is idle should it dim, watching a video should not be considered as such.

**Comment by Vahan86** [comment]
As a solution you can use "inhibit" applet which was presented for first time in Cinnamon 2.6.

The description of the applet presented in review of Cinnamon 2.6 you can find below:

----------------------

A new “inhibit” applet was introduced which allows you to quickly turn notifications off or to disable power management. This applet is handy when performing presentations, to prevent unwanted notifications to pop up, to prevent the screen from dimming brightness or the screen to get locked.  You no longer need to modify your power settings, you can just temporarily disable all that.

----------------------

**Comment by JosephMcc** [comment]
Some players don't support the inhibit feature on their own. That's what the inhibit applet is for. You can use it to prevent the screen dimming for those players.
