### ISSUE TITLE
Add a Clutter effect to convert a Full-Color icon into a Symbolic one.

### ISSUE THREAD

**Issue by lestcape** [linuxmint/Cinnamon#4824]
I think will be nice, if we can have an option to convert a full color icon in a symbolic one, or at less something similar. This can be used in any icon inside the panel and create a more softer presentation of cinnamon icons in the panel than the current one as is a convination of several icons types.

Maybe, this can be done using a convination of this effects:
https://developer.gnome.org/clutter/stable/ClutterDesaturateEffect.html
https://developer.gnome.org/clutter/stable/ClutterColorizeEffect.html
ofcourse using the theme color in the colorize effect as a normal symbolic icon is.

**Comment by JosephMcc** [comment]
I'm not sure about this. Full color icons aren't really designed to be represented that way. You'll notice that most symbolic icons are just really simple basic shapes. That's so they are still readable as a greyscale type of image.

**Comment by lestcape** [comment]
@JosephMcc is a clutter effect, is not necessary to use the clutter effect for all icons, just if you want to use it. The greyscale is really a problem, as for symbolic icons there are not an scale, so after desaturate the icons we will need to apply the Otsu's method, to change the color histogram of the image to black and white, where black will be the pure gray color (the color of the symbolic icon) and the white color will be a transparent one.

**Comment by JosephMcc** [comment]
Sorry, I just don't see the use case for this. Where would you use it? Currently applets use the icon the applet creator decides for it to use. You can't just convert icons like the panel launcher icons to greyscale and expect them to look good. If that is what a particular user wants, they could just use a different icon theme.

**Comment by lestcape** [comment]
You can not force the appindicators to use a symbolic icon, because they are not developed to be used in cinnamon, so they can look like ugly, a clutter effect to convert in symbolic icons for this case would help to a better presentation of the systray.

**Comment by lestcape** [comment]
I used the desaturate clutter effect in global menu, where the same occurs and just i think will be better use an effect like i describe instead of the usage of the clutter desaturate.

**Comment by JosephMcc** [comment]
Same idea holds true for icons weather they belong to the indicators or panel launchers. Forcing a full color icon to be colorized like a symbolic icon is not the same as having a symbolic icon in the first place. Other icons in the systray aren't symbolic either.

**Comment by lestcape** [comment]
@JosephMcc yes, of course will not be the same what i say and the symbolic icon (will be an approximation only) and would fail, because in Otsu's you will need to select an appropriate value to separate the space of the colors and is not warranty of this value will be the best to the human eyes. Another solution will be create and add by default a cinnamon icon theme, to ensure that icons will be showed appropriately, but well this is not a warranty, because in the appindicator can export icons as binary and probably they are only available in the corresponding application resource, so the icon theme will fail.

**Comment by lestcape** [comment]
@JosephMcc see this: https://github.com/bil-elmoussaoui/Hardcode-Tray
