### ISSUE TITLE
Cinnamon 2.8.4  - sound channel and volume control mixed up

### ISSUE THREAD

**Issue by kmkom** [linuxmint/Cinnamon#4825]
After booting Mint the output device is HDMI/DisplayPort 2 and the sound comes from this device, but the slider does not change the volume of the HDMI output. After checking the settings (right click context menu) I see, that the Output device is set to “Analog Output”. So the sound comes from the HDMI channel, but the volume slider controls the “Analog output”! 
If I change the output to “ HDMI/DisplayPort 2” the volume slider works as expected.
Sadly, but after the next boot the setting is wrong again!

It should not happen that the sound comes from device X but the sound applet controls the Output of device Y.

How can the User set up a default “Output device”? How is this handled in Cinnamon?

(I used Banshee player)

**Comment by ManIVIctorious** [comment]
The sound settings have been reworked in cinnamon 3.0, is this still an issue for you in latest cinnamon?

**Comment by kmkom** [comment]
>is this still an issue for you in latest cinnamon?
Yes, tested with Cinnamon 3.0.7, same bug...
This time i used VLC.

**Comment by clefebvre** [comment]
We believe this issue is fixed. Please test against the latest Cinnamon version (3.6). If the issue happens again, create a new issue and add the output of "cinnamon-settings sound".
