### ISSUE TITLE
Not for all applications dialog windows are attached to their parent window by default.

### ISSUE THREAD

**Issue by Vahan86** [linuxmint/Cinnamon#4826]
In Cinnamon 2.8 the improved feature was presented by which dialog windows are now attached to their parent window by default.

But this nice feature doesn't work for some of applications installed by default in Linux Mint. 

The applications for which the feature doesn't work:

* Upload Manager
* Update Manager
* Software Manager
* Tomboy Notes
* Text Editor(gedit)
* Synaptic Package Manager
* Firefox Browser
* GIMP
* HexChat
* LibreOffice
* Printers (system-config-printer)
* Thunderbird

**Comment by JosephMcc** [comment]
It won't work on all dialogs. This is partly controlled by applications. Dialogs should also only be attached if they are modal. We shouldn't be attaching the dialog if the program still allows interaction with the main window while the dialog is open.

**Comment by Vahan86** [comment]
Thank you for the clarification.
