### ISSUE TITLE
Brightness keys have little effect

### ISSUE THREAD

**Issue by Karkus476** [linuxmint/cinnamon#4827]
Until you get to 0, at which point the screen goes black

**Comment by surya80** [comment]
Fn + Brightness keys misbehaving, sort of behaves randomly. The brightness level does change but after a long delay and seems to be quite arbitrary. The brightness change OSD pops up every now and then randomly even when I am not clicking the Fn + Brightness key combination. I'm using a five year old HP Pavilion dv6 series Entertainment Notebook.

**Comment by Karkus476** [comment]
I am also using brightness keys which do not need you to press Fn

- Karkus

**Comment by RavetcoFX** [comment]
Hi @Karkus476, Could you post some more information about the model of laptop you have and what version of Linux you are using, thanks.

**Comment by Karkus476** [comment]
@Corbin
I am using a Lenovo G500, and LINUX Mint 17.2 with Cinnamon (duh). The F11 and F12 keys function as brightness keys when pressed without Fn. I can change the brightness (as I would expect, no bug) from power management brightness settings

- Karkus

**Comment by RavetcoFX** [comment]
@Karkus476 I've seen general issues with brightness in Linux with Lenovo laptops before, can you try this out http://itsfoss.com/fix-brightness-ubuntu-1310/

**Comment by callagg2** [comment]
As I said here, the brightness buttons don't work on macbook pro with Cinnamon 3.4.1 but do with XFCE
https://forums.linuxmint.com/viewtopic.php?f=18&t=245004

**Comment by Vahan86** [comment]
@Karkus476, is this still an issue in Cinnamon 4.4?

**Comment by icarter09** [comment]
Cinnamon 4.8.6
Mint 20.1 64bit

Not able to duplicate the issue. The brightness keys are workings as intended.
