### ISSUE TITLE
Export the menu of the tray status icon over dbus.

### ISSUE THREAD

**Issue by lestcape** [linuxmint/Cinnamon#4828]
As i read in this classes, the status menu are build over gtk. I' m right?
https://github.com/linuxmint/Cinnamon/blob/4f40fd2aa40daba6273b388d727d7bae44f7a874/src/cinnamon-gtk-embed.c
https://github.com/linuxmint/Cinnamon/blob/4f40fd2aa40daba6273b388d727d7bae44f7a874/src/cinnamon-tray-icon.c
https://github.com/linuxmint/Cinnamon/blob/4f40fd2aa40daba6273b388d727d7bae44f7a874/src/tray/na-tray-manager.c
https://github.com/linuxmint/Cinnamon/blob/4f40fd2aa40daba6273b388d727d7bae44f7a874/src/tray/na-tray-child.c

I really don't know if this is done in some distro or in other place, but i think most usefull code will be in the unity-gtk-module where they do something similar.

Gtk have his own way to export a GtkMenu over Dbus and we can think that our systray menu are an special case of an applications and then export the systray menu of this "application" over Dbus in an special path (different to the standar app menu) and then handle this path with muffin or directly inside the systray classes.

Please see the GtkDbus specification.
https://wiki.gnome.org/Projects/GLib/GApplication/DBusAPI

After this, we can ask for the Dbus path of a systray icon and read the GtkDbus especification inside the Cjs, and build the status icon menu using the implementation that i have for read the GtkDbus specification in the global menu:
https://github.com/lestcape/Global-AppMenu/blob/master/globalAppMenu%40lestcape/dbusMenu.js#L671

In this way we  don't need to show any more a gtk menu inside cinnamon and we will see a more self-contained desktop environment.

**Comment by lestcape** [comment]
Or more simple, would be export the menu in a standard way to the appindicator api directly:
https://wiki.ubuntu.com/DesktopExperienceTeam/ApplicationIndicators

**Comment by lestcape** [comment]
Additional to this, please see, the x-chat status icon will not load correctly after a cinnamon restart.

**Comment by JosephMcc** [comment]
@lestcape Probably a little off-topic but I've noticed something with the indicators. I'm currently running Cinnamon under Ubuntu Xerus and the ubuntu software updater puts an indicator in the systray. It doesn't seem to properly update though. The icon doesn't change when updates become available without a Cinnamon restart. Also after updating the indicator menu doesn't update to show it. It will still say that there are updates available at the top even when there aren't. I'm not sure if this is an issue with the indicator or with the implementation in Cinnamon.

**Comment by lestcape** [comment]
I need to see how is working in unity, to find what we can do about it. I think will not be an issue of the cinnamon indicator implementation, but well maybe is.

**Comment by JosephMcc** [comment]
@lestcape apparently someone already raised the issue I was talking about with ubuntu's update indicator: https://github.com/linuxmint/Cinnamon/issues/4702

**Comment by lestcape** [comment]
Thanks.

**Comment by lestcape** [comment]
@clefebvre take this seriously, he want to add libindicator... So, this have not reason to continues opened...
