### ISSUE TITLE
Sliders in submenus

### ISSUE THREAD

**Issue by zagortenay333** [linuxmint/Cinnamon#4830]
The `StDrawingArea` inside of submenus has a weird padding on the right. This is an issue if the theme uses a `border-image` property since it is not affected by it, making it look like the handle cannot be scrolled all the way to the right.
![workspace 5_003](https://cloud.githubusercontent.com/assets/11144630/11168667/8bb7bd16-8b99-11e5-9232-6efd817b9311.png)

Even if you don't use a `border-image`, the problem will be that the slider doesn't align properly on the right. The default theme solved this arbitrarily by setting a `padding-right: 0;` to the submenu items, which is not good.

**Comment by JosephMcc** [comment]
There is something weird going on in the sound applet menu. Hopefully we can manage to get it fixed but we haven't figured out what is causing it. Currently that slider has a padding-right that is hard coded.

**Comment by zagortenay333** [comment]
Ah, ok.

**Comment by JosephMcc** [comment]
I'm closing this since a commit was merged that should fix it.
