### ISSUE TITLE
Doing things with applets sometimes reverts wallpaper to default one

### ISSUE THREAD

**Issue by ACinnamonUserInUK** [linuxmint/Cinnamon#4831]
I don't know exactly what applet actions cause this, but it seems to be either moving applets around on a panel and/or adding new instances of applets. The problem may be connected to the misbehaving 'spacer' applet - misbehaviour that I have reported on here before. The current problem - whatever its cause - is that suddenly my wallpaper is gone and replaced with the default silver Mint 17.2 logo wallpaper.

Thanks.

Mint x64 17.2 Cinnamon 2.8.2.

**Comment by JosephMcc** [comment]
We already have an existing issue for this. Could please add your info to that one. https://github.com/linuxmint/Cinnamon/issues/3953
