### ISSUE TITLE
The notification that the applets list has been refreshed is sometimes too fast to see 

### ISSUE THREAD

**Issue by CottonEaster** [linuxmint/Cinnamon#4833]
(. . although at other times it times out and gives an error).

Go to system settings. Click 'applets'. Select 'available applets (online). Click 'refresh'. Then you may see a brief flash. That is the notification - that one does not get time to read - that the list has been refreshed.

What should happen: one should have time to read the notification.

Also: I don't really see the point of the animation between the installed applets and the ones available online, especially since (1) sometimes that animation stalls a little on my system, half way through, (2) the animation does not seem under the control of any animation settings.

**Comment by Vahan86** [comment]
@ACinnamonUserInUK, is this still an issue for you in Cinnamon 3.0?

**Comment by ACinnamonUserInUK** [comment]
@Vahan86: I am afraid so, yes.

I am on Cinnamon 3.0.7.

**Comment by NikoKrause** [comment]
The applets settings have been changed in Cinnamon 3.6
