### ISSUE TITLE
Cinnamon becomes hard to use

### ISSUE THREAD

**Issue by BloodFever5643** [linuxmint/Cinnamon#4834]
Hi linux mint is good (and way better then window$) but after like 30 minutes it becomes all hard to use and and I need to unplug the cord and take out the battery and wait a few hours. I use the alienware 17 laptop with core i7, 64gb of memory, Nvidia GTX 980M 4gb. Please fix asap, its becoming annoying

**Comment by RavetcoFX** [comment]
Can you provide more info on what "hard to use" means please. It's hard for to help you with such a vague description.

**Comment by aplatypus** [comment]
I had trouble with mouse and keyboard freezes.  I saw the post on the Mint site, about NIVIDIA drivers.

Take a look at the readme:
*  http://linuxmint.com/rel_rafaela_xfce.php

You may need to install some different versions until you find the 'right' one for your set-up.  I had similar trouble when I had windows on this PC.  At least with Linux I have some discretion over what is running.
