### ISSUE TITLE
[[URGENT!!] Make futuristic looking

### ISSUE THREAD

**Issue by BloodFever5634** [linuxmint/Cinnamon#4835]
Hi again, I forgot my password and needed to create a new account, if your wondering why its called BloodFever that because she's my favorite pony. anyways can you make the system look futuristic, it would make linux a head of the game in every aspect. it would be very kick ass

here are some pictures i found on google like I want it to look futuristic.

![interface 1454x884 wallpaper_www wallpaperto com_5](https://cloud.githubusercontent.com/assets/15885291/11205527/af9bd6f4-8cc5-11e5-9d17-beb6f243becd.jpg)

![maxresdefault](https://cloud.githubusercontent.com/assets/15885291/11205533/ba716922-8cc5-11e5-900c-8c9eaadf6be6.jpg)

please do those if at all possible

**Comment by JosephMcc** [comment]
This type of setup would only ever appeal to a very small number of users. It's not the sort of interface we could use by default. If you're interested in this type of thing look into 3rd party tools like conky to help with creating it.

**Comment by BloodFever5634** [comment]
Can you do it for me, I dont have any time to set that up, and please make sure it doest become all slow or laggy as thats not good to game on or use
