### ISSUE TITLE
All Icons go away 

### ISSUE THREAD

**Issue by BloodFever5634** [linuxmint/Cinnamon#4839]
hi again all my icons disappear randomly and when i type in cat /proc/fb in the command prompt it fixes it, can you please fix asap it is annoying thanks

**Comment by BloodFever5634** [comment]
but why is it annoying it is an urgent matter as it makes my whole system and games hard to use and i dont want to have to keep typing in command prompts to fix issues these issues should just be fixed atomatically. if it helps i have a alienware 17 laptop with 64gb of ram 980m gt graphics card and core i7 THANKS for fixing it

**Comment by Topperfalkon** [comment]
It may be urgent to you, but to the people working on Cinnamon this is a wild goose chase. You've not provided steps to reproduce your issue, or any significant amount of troubleshooting to identify what caused the issue you're having. It might not even be reproducible on other systems, and therefore would most likely be far less urgent than an issue affecting all Cinnamon users.

If you want your issue to get fixed sooner, providing more details about what you're doing when your icons disappear will help.

**Comment by BloodFever5634** [comment]
@Topperfalkon IF YOU ARE not going to be a useful member you should just be quite seinse you are obviously not going to FIX IT. just be like you name Faggetter hHAHA

**Comment by Topperfalkon** [comment]
Neither is anyone else with that attitude.

And yes, I was trying to be helpful, by suggesting what you could do to get your issue looked at quicker.
