### ISSUE TITLE
Cinnamon 2.6 desktop showing in window

### ISSUE THREAD

**Issue by MPE2016** [linuxmint/Cinnamon#4840]
L.S.,

When I log in, my Cinnamon 2.6 desktop is somehow showing the desktop and icons in a window (see attachment). I cannot close the window, but when i minimize it disappears, and so do the desktop icons. I run ubuntu 14.04 on a Dell Inspiron N5050.

If more info is required, feel free to ask for it, as I am not completely sure which info is required. 

Many thanks in advance!
MPE

![schermafdruk van 2015-11-19 07 39 41](https://cloud.githubusercontent.com/assets/15818884/11264135/7039f450-8e91-11e5-82c2-592b7a9432e1.png)

**Comment by ManIVIctorious** [comment]
I had a similar issue about half a year ago, but it got resolved, is this still an issue for you in cinnamon 3.0?

**Comment by MPE2016** [comment]
It is no longer an issue after installing cinnamon 3


Op 06-09-16 om 17:02 schreef ManIVIctorious:

**Comment by ManIVIctorious** [comment]
So could you please close the issue?

**Comment by MPE2016** [comment]
Apologies for not closing earlier. I rarely use github and simply forgot.


Op 06-09-16 om 17:44 schreef ManIVIctorious:
