### ISSUE TITLE
Cinnamon 2.8.2 - broken CRUX theme

### ISSUE THREAD

**Issue by gtxSeries** [linuxmint/Cinnamon#4841]
CRUX GTK3 theme is bugged with Cinnamon 2.8.2, screenshot attached.
![screenshot from 2015-11-19 13 14 54](https://cloud.githubusercontent.com/assets/15925146/11270472/ac6ee09c-8ebf-11e5-9b92-0c1ef3810748.png)

**Comment by leigh123linux** [comment]
This isn't a cinnamon issue, please close and re-file the issue against the CRUX theme instead!

**Comment by gtxSeries** [comment]
Thank you! I'm new to github, any idea how to close it and where could I report this then?

**Comment by JosephMcc** [comment]
There should be a button to close the issue somewhere on this page. I'll go ahead and close this one.
