### ISSUE TITLE
Cinnamon search box in Mint Menu is (still) sometimes displaced

### ISSUE THREAD

**Issue by ACinnamonUserInUK** [linuxmint/Cinnamon#4844]
Please see screenshot - which is of what I see, sometimes, when I start to type in the search box.

Cinnamon 2.8.2.
![screenshot-screen-2015-11-19-184549](https://cloud.githubusercontent.com/assets/9998846/11280589/9bebfdb6-8eee-11e5-8cd5-c70f70f7157e.png)

**Comment by JosephMcc** [comment]
This should be fixed by: https://github.com/linuxmint/nemo/commit/d4437fc949b1462f6b70694e31985688b730efcd
What version of nemo are you running?

**Comment by mtwebster** [comment]
https://github.com/linuxmint/nemo/commit/5d1711fd84267b823fc482559ab784fc813347d9

This makes no sense really to work on the desktop.
