### ISSUE TITLE
Graphical oddity with Mint Menu

### ISSUE THREAD

**Issue by ACinnamonUserInUK** [linuxmint/Cinnamon#4845]
When using Mint Menu, and more specifically searching using the text box, and more specifically yet when one, also, moves the mouse between the results and the categories, the following peculiar thing happens. Category words become highlighted (as the word 'games' is in the attached screenshot) but only after a degree of back and forth between the aforementioned sections. Try it.

![1](https://cloud.githubusercontent.com/assets/9998846/11280767/5d769202-8eef-11e5-9a05-ff8e1e571bb6.png)

Cinnamon 2.8.2

**Comment by JosephMcc** [comment]
I can reproduce it.

**Comment by JosephMcc** [comment]
This should be fixed by https://github.com/linuxmint/Cinnamon/commit/d9a40a6e1fb3e5adb3b92dd1b459e33e5df5f131
