### ISSUE TITLE
Switching between users prompts for password for SMART status

### ISSUE THREAD

**Issue by ACinnamonUserInUK** [linuxmint/Cinnamon#4846]
On my Mint laptop something strange and a bit irritating happens when I switch users (either by using the 'switch users' option or by logging one user out and logging another in). To wit: the Disks utility (I think it is this) pops up a box asking for my password so as to do something with disk SMART status (i.e. with disk health monitoring).

I disabled SMART monitoring (using the aforementioned Disk utility) for both users but that seems to make no difference: I still get the popup - screenshot attached.

![cqcdl7j](https://cloud.githubusercontent.com/assets/9998846/11280828/aeb6d8a2-8eef-11e5-9a80-2d1807157a5d.png)

Linux Mint 17.2 x64 Cinnamon 2.8, with an Intel SSD.

**Comment by ManIVIctorious** [comment]
Seems to be more of a Linux Mint issue than a cinnamon issue to me. Does this still happen with latest packages (particularly cinnamon 3.0)?
