### ISSUE TITLE
Cinnamon - How to Greatly Improve "Create a new launcher here..." Routine

### ISSUE THREAD

**Issue by RadicalRadish** [linuxmint/Cinnamon#4849]
System details as follows:
Linux Mint 17.2 x64 Cinnamon Edition
Cinnamon 2.6.23
Nemo 2.6.7

In Cinnamon the user can right click on the desktop and select to "Create a new launcher here..." Once that is clicked a dialogue window opens titled "Launcher Properties". In that dialogue there is an item titled "Command:" (where you enter what command you want performed by the new launcher).

Problem is that the text box to enter in the command is not very long. Enter a long command string and the user can't actually see all of the command in one go. Hence, forced to scroll back and forth while you check the command.

It is possible to resize the the Launcher Properties dialogue horizontally by the click and drag method. However, when the user does this the Command: text box doesn't get any longer. What happens is that the space that the "Rocket" (icon) occupies gets bigger and bigger as you drag. This is totally useless to the user. What would be much better is if the Rocket icon stayed the same size but the text boxes for entering "Name", "Command" and "Comment" got longer as the dialogue is resized horizontally.

In case I haven't explained very well what I'm getting at here is a screenshot of the Rocket icon and the kind of space it gets allocated in the dialogue when the dialogue is resized horizontally:

![screenshot make new launcher](https://cloud.githubusercontent.com/assets/15947700/11310944/9f9ce9ee-8fc4-11e5-96c5-d4fb6337b04b.png)

Therefore, my suggestion is please make this possible in Launcher Properties. I don't think it would take much by way of coding to achieve this. And it would make the entry of a long string for a Command much, much more comfortable for the user and give the user a much more polished desktop experience.

**Comment by JosephMcc** [comment]
Opened a PR here https://github.com/linuxmint/Cinnamon/pull/4863 to implement your idea since it makes more sense then the current behaviour
