### ISSUE TITLE
Scrolling bug in some themes

### ISSUE THREAD

**Issue by LER0ever** [linuxmint/Cinnamon#4851]
I am running  Manjaro 15.09 using Cinnamon 2.6.13
Cinnamon has something like bouncing when users scroll to the end or the top.
But when I switch to the theme "Air" from Parrot Security OS, the bouncing effect don't even disappear when i scroll to the middle! It's always there and sometimes covers important content.
![image](https://cloud.githubusercontent.com/assets/10568668/11316223/2fecc47a-903c-11e5-86e9-8b8a86b4027e.png)
As you see, there is two triangle blocks on the top and bottom in Nemo. Hope there is a way to turn off this effect or make it normal.

**Comment by LER0ever** [comment]
Plus an image in system settings, i highlighted the triangle that covers content
![screenshot from 2015-11-21 10-51-25](https://cloud.githubusercontent.com/assets/10568668/11316353/180f4460-903f-11e5-9dc4-779e2898ec7a.png)

**Comment by Cobinja** [comment]
That's not Cinnamon, it's a new feature in Gtk3 and is ( or should be) handled by your Gtk3 theme.
