### ISSUE TITLE
Unable to see underneath popup in cinnamon 2.8.

### ISSUE THREAD

**Issue by mathwhiz1212** [linuxmint/Cinnamon#4852]
If there is a popup window the grays the background, if you try to move that popup window it moves both the popup window and the window under it:

https://mc.livetolearn.org/problem.webm

**Comment by Cobinja** [comment]
That's an old, re-introduced feature which only applies to modal windows, which don't allow interaction with the parent window anyway. You can turn it off in Settings->Windows->Behavior->"Attach dialog windows to the parent window".

**Comment by mathwhiz1212** [comment]
Thank you!
