### ISSUE TITLE
Allow switching media players in the new sound-applet

### ISSUE THREAD

**Issue by cgoise** [linuxmint/Cinnamon#4853]
In the old version of the sound-applet, if several player were open (eg vlc + banshee) at the same time, you had the option to click the name of the current player in the plugin. Then a list would appear where you could select the other player and control it from the applet.

The new applet would be much more usable, if this was implemented there, too.

**Comment by ManIVIctorious** [comment]
I have already raised that issue in #4755, you have by far the better title though...

**Comment by JosephMcc** [comment]
Duplicate https://github.com/linuxmint/Cinnamon/issues/4755
