### ISSUE TITLE
audio visualizer desklet like impulse for Cinnamon

### ISSUE THREAD

**Issue by freemangilgamesh** [linuxmint/Cinnamon#4856]
I suggest a sound equalizer desklet like impulse   http://gnome-look.org/content/show.php/?content=99383

It makes our desktop more beautiful and fun 

<a href='http://postimg.org/image/gxmo365ij/' target='_blank'><img src='http://s1.postimg.org/gxmo365ij/Screenshot_from_2015_11_22_14_56_45.jpg' border='0' alt="Screenshot from 2015 11 22 14 56 45" /></a>

**Comment by lestcape** [comment]
The equalizer api for pulse audio is disable by default in ubuntu and other distros, this is why i  stopped my attempt to do some things with that.

**Comment by JosephMcc** [comment]
This sort of request is best handled by a third party app, desklet, or extension.
