### ISSUE TITLE
Resume Fails after Suspend

### ISSUE THREAD

**Issue by iandsamson** [linuxmint/Cinnamon#4857]
I left machine in "suspend" all night, resumed perfectly this morning. Then I suspended for 2 hours, it refused to resume, had to press RESET button. LM17.3 'Rosa' x64, Cinnamon 2.8.4. 8GB RAM.

**Comment by leigh123linux** [comment]
Cinnamon has nothing to do with suspend so please close this issue and re-file against the kernel!
