### ISSUE TITLE
Ubuntu1510 - Desktop Background Not Changable

### ISSUE THREAD

**Issue by n00b42** [linuxmint/Cinnamon#4862]
* I recently did a fresh install of Ubuntu 15.10.
* I changed my background to be grey and after some other setup (like more recent nvidia drivers) I installed cinnamon. 
* Restarted and then selected cinnamon upon login.
* Everything fine except some icon issues which I could fix by installing some gnome icon pack.
* Icons on desktop are hard to read and as there is no option to change that text I tried to change the background.
* Using the "backgrounds" dialog no action has any concequence, neither selecting an image nor defining a desktop gradient or anything else.

cinnamon: Version: 2.6.13-1ubuntu2

**Comment by dralley** [comment]
Could you test whether this occurs with the latest version of Cinnamon, v2.8?

You will have to install this PPA as Ubuntu's repositories only contain the old version ```ppa:gwendal-lebihan-dev/cinnamon-nightly```

**Comment by n00b42** [comment]
Updated but issue(s) still persist.
Currently, I assume it is not only cinnamon but also related to nemo and some driver stuff....

**Comment by rpbaptist** [comment]
I am experiencing the same issue. Also on an Ubuntu 15.10 install I did last weekend. Funny enough it was working okay, but I changed a few more settings (using `lightdm-gtk-greeter` instead of `unity-greeter`) and now my lock screen will have only a grey background instead of my current wallpaper.

When my screen times out and locks, I see a partially transparant background around the time, but the rest remains grey.

My current wallpaper is one from the folder I set up to use as a slideshow, but it won't change and I cannot select any other.

**Comment by rpbaptist** [comment]
Well, I figured out at least part of the problem. I used `gnome-tweak-tool`. It set the background which was selected at that point. No I am unable to change it. It seems the tool locked it.

**Comment by mtwebster** [comment]
Try seeing if nautilus is installed - if you're not using it (assuming you're using nemo instead), remove it - it could be interfering with trying to draw the desktop.

**Comment by rpbaptist** [comment]
I did remove nautilus, but there is one component still there: nautilus-data. This in turn depends on other packages.

I did find I have several gnome components which I suspect may interfere with cinnamon, but I am not certain I can safely remove them:

```
> sudo apt-get remove gnome-settings-daemon
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following extra packages will be installed:
  libfcitx-config4 libtimezonemap-data libtimezonemap1 libunity-settings-daemon1 unity-control-center
  unity-settings-daemon
Suggested packages:
  fcitx gnome-screensaver xscreensaver
The following packages will be REMOVED:
  gdm gnome-control-center gnome-session gnome-settings-daemon gnome-shell gnome-tweak-tool
The following NEW packages will be installed:
  libfcitx-config4 libtimezonemap-data libtimezonemap1 libunity-settings-daemon1 unity-control-center
  unity-settings-daemon
```

I am not sure why it wants to install unity components. (I completely removed them). Since I wish to use Cinnamon, is it safe to remove these?

**Comment by mtwebster** [comment]
You can safely leave nautilus-data installed if you want, to keep from messing with all those dependencies.  Removing the `nautilus` package gets rid of the actual program, which is all we really want here.

I'm honestly not sure why it wants to install unity components when you remove gnome stuff.

**Comment by rpbaptist** [comment]
Well I removed what I could. I noticed something else. When I log in, I briefly see the cinnamon background. Same when I log out. It is being drawn over, probably by gnome settings.

I did a `dconf dump / | grep <image name>' yet no results. I have no idea where this is being stored now.

**Comment by rpbaptist** [comment]
Okay, my bad. I have two background images in the folder with very similar names.

I did find it under `/org/gnome/desktop/background`

In dconf-editor I set it back to default. I saw the default one. Now I changed it in Cinnamon configuration and it is back to normal.

**Comment by rpbaptist** [comment]
And after a reboot it is again drawing over the cinnamon background, but now with a blue single color. I would love to find a way to have cinnamon take precedence over gnome in this.

**Comment by rpbaptist** [comment]
Installed gnome-tweak-tool again, it came with a ton of dependencies. Removed it and we're good again. Even after a reboot. Issue solved for me now at least.

**Comment by rpbaptist** [comment]
And the show goes on. I solved it by removing the schema file and reloading. But that in turn broke Nemo.

Considering doing a whole new install next weekend and never touching gnome-tweak-tool. Although I believe it was necessary for getting my laptop to suspend and lock properly.

**Comment by mtwebster** [comment]
The only PPA that can be considered 'official' is the nightly ppa (https://launchpad.net/~gwendal-lebihan-dev/+archive/ubuntu/cinnamon-nightly) - it can be unstable for sure, but I can actually walk you through troubleshooting it.  I can't vouch for, nor do I know what, if any, modifications are done in these other PPAs, nor the trickled-down (obsolete) packages that make their way to Ubuntu by way of Debian.

**Comment by ManIVIctorious** [comment]
Is this still an issue to you with cinnamon 3.0?

**Comment by rpbaptist** [comment]
Not for me

**Comment by JosephMcc** [comment]
If you happen to be running nautilus and allowing it to handle the desktop it will draw a background over the cinnamon background. Could that be what is happening @n00b42 ?

**Comment by n00b42** [comment]
Switched to Xfce some weeks ago. So cant confirm anymore. As rpbaptist noted that he has no issue anymore, I close this issue.
