### ISSUE TITLE
Weather applet displays wrong information after sleep/hibernation

### ISSUE THREAD

**Issue by cstoudt** [linuxmint/Cinnamon#4864]
Linux Mint 17.2 Cinnamon 64-bit, Cinnamon Version 2.6.13, Kernel 3.16.0-38 generic, Weather applet 1.9.9

The panel applet displays the correct weather information at startup.  When the computer goes into sleep or hibernation and then resumes, the weather app displays weather information that appears to be that for several days previous and doesn't update according to the update interval.  It requires logout/logon to restore the correct information.

I've noted this behavior on both a laptop and a desktop, both running the same version of Mint/Cinnamon.

**Comment by JosephMcc** [comment]
The weather applet is developed by a 3rd party. Please report the issue to it's developer here: http://cinnamon-spices.linuxmint.com/applets/view/17
