### ISSUE TITLE
Firefox full screen videos controls hidden

### ISSUE THREAD

**Issue by sackwort** [linuxmint/Cinnamon#4865]
Linux Mint 17.3 Cinnamon 64-bit. Cinnamon 2.8.5.

When viewing full-screen YouTube videos in Firefox, the bottom line of video controls ("Play", "Next", "Volume" etc) are hidden behind the bottom Cinnamon desktop panel.

**Comment by JosephMcc** [comment]
Are you using multiple monitors? Any of the panel auto-hide features? When playing a full screen Youtube video here, the video goes over the panel but there are instances with a dual monitor setup where I can cause the panel to pop back up over the video.

**Comment by sackwort** [comment]
Yes, sorry, I forgot to say that I am using dual monitors. I'm not using the auto-hide features, though.

After reading your message, I just tried disabling the second monitor and this results in full-screen YouTube videos displaying correctly; above the bottom panel. When I then re-enable the second monitor, the video controls are again hidden.

**Comment by sackwort** [comment]
Full-screen videos are working perfectly now.
