### ISSUE TITLE
(cinnamon:5042): Cogl-ERROR **: Failed to create texture 2d due to size/format constraints

### ISSUE THREAD

**Issue by Eirikur** [linuxmint/Cinnamon#4867]
This is where I'm dying in Cinnamon.  I'm trying to pin it down. It's probably not a Cinnamon bug, but something else running out of resources.  As I recall, I had problems under MATE as well.  I'm running Cinnamon under gdb now and I'll see if I can find out more.  It would be nice to handle this situation if it is recoverable.  I have a lot of pixels (three monitors, one is 2560x1600 and it's flanked by two 1920x1200s in portrait).  I'm running all three monitors off of a Radeon R9 270 using the binary fglrx driver installed via driver-manager.  The open source Xorg ATI driver doesn't like more than two monitors, it seems.

Thanks,

Eirikur

 ~ ⮀ $ ⮀cinnamon --replace
Cjs-Message: JS LOG: About to start Cinnamon
St-Message: cogl npot texture sizes SUPPORTED
Cjs-Message: JS LOG: Cinnamon started at Mon Nov 23 2015 22:33:06 GMT-0500 (EST)

(cinnamon:5042): St-WARNING **: percentage lengths not currently supported
Cjs-Message: JS LOG: network applet: Cannot find connection for active (or connection cannot be read)
Cjs-Message: JS LOG: network applet: Found connection for active

(cinnamon:5042): Cogl-ERROR **: Failed to create texture 2d due to size/format constraints
Trace/breakpoint trap
 ~ ⮀ $ ⮀

**Comment by JosephMcc** [comment]
My random guess would be it's trying to create a texture larger than your videocard can handle.

Have you tried this under a newer version of Cinnamon?

**Comment by mainmachine** [comment]
@Eirikur - both drivers can handle >2 displays just fine, although the best results I've seen currently (on AMD GPUs) are on teh Radeon/AMDGPU (open source) drivers, and for best results you want to use a custom /etc/X11/xorg.conf file, especially since you're using mixed resolutions and orientations. 

I've done quite a bit of work with this on several other DE's & WM's, but oddly enough I haven't tested it on Cinnamon (my preferred DE).

**Comment by Eirikur** [comment]
Thank you for the input.  I seem to have it working now on a
      later R9-based card.
    Eirikur
    
    
    On 09/06/2016 01:14 AM, David Martinka
      wrote:
    
    
      @Eirikur - both drivers can handle
        >2 displays just fine, although the best results I've seen
        currently (on AMD GPUs) are on teh Radeon/AMDGPU (open source)
        drivers, and for best results you want to use a custom
        /etc/X11/xorg.conf file, especially since you're using mixed
        resolutions and orientations. 
      I've done quite a bit of work with this on several other DE's
        & WM's, but oddly enough I haven't tested it on Cinnamon (my
        preferred DE).
      —
        You are receiving this because you were mentioned.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/linuxmint/Cinnamon","title":"linuxmint/Cinnamon","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/linuxmint/Cinnamon"}},"updates":{"snippets":[{"icon":"PERSON","message":"@mainmachine in #4867:  @Eirikur - both drivers can handle \u003e2 displays just fine, although the best results I've seen currently (on AMD GPUs) are on teh Radeon/AMDGPU (open source) drivers, and for best results you want to use a custom /etc/X11/xorg.conf file, especially since you're using mixed resolutions and orientations. \r\n\r\nI've done quite a bit of work with this on several other DE's \u0026 WM's, but oddly enough I haven't tested it on Cinnamon (my preferred DE)."}],"action":{"name":"View Issue","url":"https://github.com/linuxmint/Cinnamon/issues/4867#issuecomment-244851613"}}}

**Comment by JosephMcc** [comment]
Can this be closed?

**Comment by Eirikur** [comment]
Yes, please.  Thank you.
    
    
    On 09/06/2016 02:42 PM, JosephMcc
      wrote:
    
    
      Can this be closed?
      —
        You are receiving this because you were mentioned.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/linuxmint/Cinnamon","title":"linuxmint/Cinnamon","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/linuxmint/Cinnamon"}},"updates":{"snippets":[{"icon":"PERSON","message":"@JosephMcc in #4867: Can this be closed?"}],"action":{"name":"View Issue","url":"https://github.com/linuxmint/Cinnamon/issues/4867#issuecomment-245048577"}}}

**Comment by JosephMcc** [comment]
@Eirikur I'll close it. Since you opened the issue that means you can also close it.

**Comment by mainmachine** [comment]
@Eirikur - glad you got it working. Cheers! :+1:
