### ISSUE TITLE
VMware 3D Acceleration makes some windows translucent to Desktop

### ISSUE THREAD

**Issue by kingramze** [linuxmint/Cinnamon#4870]
Upon updating to 4.x linux kernel series and mesa 11 drivers, VMware with 3D Acceleration enabled now displays many application windows as fully or partially translucent -- showing the Desktop background image / wallpaper within the app.

This behavior is seen on Ubuntu, Cubuntu, Arch Linux, and other distributions.  The change, for me, was noticed sometime after upgrading from kernel 3.9 to 4.0 with both cinnamon 2.6 and 2.8.

Turning off 3D Acceleration displays properly, as does "software rendering mode" of Cinnamon.

another forum discussing the bug if it's helpful:
https://bbs.archlinux.org/viewtopic.php?id=203474

**Comment by leigh123linux** [comment]
Can you close this report and re-file a bug against VMware on their site instead!

**Comment by kingramze** [comment]
Are you certain VMware is the issue?   Considering the bug doesn't affect Mate, KDE Plasma 5, XFCE, LXDE, Unity, or any of the other DE's tested with the exact same install?   VMware could certainly be the cause, but it seems unlikely.

**Comment by dinobagio** [comment]
Hi, I experience the same issue with my new mint/cinnamon virtual machine using Virtual Box.

Linux Mint 17.3 Rosa
VERSION="14.04.3 LTS, Trusty Tahr"
cinnamon:
  Installed: 2.8.6+rosa
3D Acc Enabled 
glxinfo 2>/dev/null | grep "direct rendering"
direct rendering: Yes

Every time I get to a dialog box, the parent window shades as described in the 2.8.0 changelog
* windowManager: Make the window dimming effect with attached dialogs a bit stronger and more obvious*

So obvious that the parent window gets fully transparent and I can't ever get back the window after I close the dialog box.

I found a way though, If I disable the "attach  dialog windows to their parent window's titlebar" setting in Settings/Windows/Behavior which is ON by default in Mint 17.3, the window doesn't disappear anymore. and I can get hold of it.

Now that I've checked, I can experience the same on Mint 17.2 with Cinnamon 2.6.13 if I enable the same setting which is OFF by default in this version.

What is this setting about ?
Is it bad if we disable it ?

**Comment by JosephMcc** [comment]
@dinobagio The setting just provides visual feedback that the dialog is modal and you will be unable to do anything in the parent window until the dialog is closed. There is no harm at all in disabling it.

**Comment by dinobagio** [comment]
OK thank you for this feedback,
How can we debug what happens when the setting is enabled ?

**Comment by kingramze** [comment]
While I am glad you've resolved your issue, this not the behavior of the bug I reported, and your solution does not fix mine.    My report is that Cinnamon, while using 3D accelleration on VMware (regardless of which distro used) has a bleed-through effect of the desktop onto certain areas of most programs and windows.   See below:

![untitled](https://cloud.githubusercontent.com/assets/16008405/11894447/2f1fd9c4-a545-11e5-8672-1e3edb23cf66.jpg)

**Comment by kingramze** [comment]
OpenGL 3, Mesa 11.1, linux kernel 4.3 (or higher) and vmware's virtual hardware version 12 have resolved the issue

**Comment by robert-scheck** [comment]
Confirming above results with Fedora 23 and Cinnamon: After updating the VMware Workstation Player to version 12, the VMware machine configuration file `*.vmx` had afterwards to be manually changed to `virtualHW.version = "12"` to solve the issue.

**Comment by ccrome** [comment]
Ah!  Thank you for the pointer.  Changing virtualHW.version="12" worked for me too.  Thanks!

**Comment by jrial** [comment]
In my case, I had to also give it more graphics RAM. Raised it from 768MB (Recommended) to 1GB did the trick for me. Changing the virtualHW.version had no effect.

**Comment by kode54** [comment]
I am having this issue with Cinnamon 3.6.7 on Ubuntu 18.04.1, using VMware Workstation Player version 14.1.3. The virtualHW.version is 14.
