### ISSUE TITLE
mouse pointer disappears

### ISSUE THREAD

**Issue by jsmad** [linuxmint/Cinnamon#4871]
I'm not sure if this is the right place to report this. Please let me know. I'm running Fedora 23 Cinnamon spin.

When I click on a shell terminal and I start typing, my mouse pointer disappears! When there is only a single terminal on the screen, I can move the mouse and it re-appears. BUT when I've got 2 (or more) terminals filling the entire screen, then moving the mouse does absolutely nothing, it still remains hidden. I know its there because I can still blindly click on things.

Any help would be appreciated.

Thank you.

**Comment by leigh123linux** [comment]
I would blame your graphics card driver, which one are you using?

**Comment by jsmad** [comment]
Thank you for your quick answer, I'm using the binary nvidia drivers.

I'm not sure how the graphics driver would interfere. When I move the mouse over the terminal, there is no problem. The pointer disappears only when I focus (via mouse or keyboard) AND type something on the terminal. Strange eh?

**Comment by leigh123linux** [comment]
Try updating to the latest packages

https://bodhi.fedoraproject.org/updates/FEDORA-2015-4b7a69d81e

```
sudo dnf --enablerepo=u*g update cinnamon muffin nemo*
```

**Comment by jsmad** [comment]
I updated to the latest packages and that didn't fix the problem of the disappearing mouse pointer.

I did some research and I found many other people with the same problem. Apparently it is a "hateful" feature of gnome-terminal and currently there is no way to disable it, unless you recompile it (or some package manager adds a custom option).

For example:
http://superuser.com/questions/902909/disabling-mouse-hiding-in-gnome-terminal-while-typing
https://mail.gnome.org/archives/gnome-list/2015-April/msg00000.html

So this is definitely not a Cinnamon issue, sorry for disturbing you.

**Comment by E3V3A** [comment]
@jsmad 

Apparently this issue have resurfaced and it indeed [seem](https://social.technet.microsoft.com/Forums/office/en-US/87e132b4-8133-4d65-8dd5-845077f35730/hyperv-issue-mouse-pointer-invisible-in-linux-mint-17-run-in-hyperv-of-windows-10?forum=winserverhyperv) to be Cinnamon related. I just encountered this problem in LM 18 Cinnamon ("Sarah"). Everything was working great until suddenly (and seemingly out of the blue)  the mouse disappeared, after a copy/paste operation, from Firefox. 

Searching around, I tried the following:
```bash
gsettings get org.cinnamon.settings-daemon.plugins.cursor active
gsettings set org.cinnamon.settings-daemon.plugins.cursor active false
```
At first this didn't work, but then I rebooted the machine. And the problem has been gone so far.

Alternative solutions have been to restart the windows manager **or** doing `CTRL-ALT-F1` and then `CTRL-ALT-F7`. (I didn't try that.)

**Comment by leigh123linux** [comment]
@E3V3A 

Without any logs or error output your not in a position to blame cinnamon and say it not graphics driver related!

**Comment by E3V3A** [comment]
Hi @leigh123linux ,

> Without any logs or error output your not in a position to blame cinnamon and say it not graphics driver related!

Ok, agreed, but then you're equally not in a position to say it **is** the graphics driver, since there is no such solution nor explanation around. In addition I'm not using any Nvidia drivers since I'm running this in a VirtualBox. I have ~9 different *nix distros running (including several LM versions) and have never encountered this problem before in any of them.  And now the problem seem resolved from what I did above, so I can't really test this any further. 
 
```
00:02.0 VGA compatible controller: InnoTek Systemberatung GmbH VirtualBox Graphics Adapter
```
Which error logs would you like? What other info could help you? 

For others with this problem still occuring please post the output of:
```bash
# gsettings list-recursively | sort | uniq | grep -i cursor

org.cinnamon.desktop.interface cursor-blink-time 1200
org.cinnamon.desktop.interface cursor-blink-timeout 10
org.cinnamon.desktop.interface cursor-blink true
org.cinnamon.desktop.interface cursor-size 24
org.cinnamon.desktop.interface cursor-theme 'DMZ-White'
org.cinnamon.settings-daemon.plugins.cursor active false
org.cinnamon.settings-daemon.plugins.cursor priority 99
org.gnome.desktop.interface cursor-blink-time 1200
org.gnome.desktop.interface cursor-blink-timeout 10
org.gnome.desktop.interface cursor-blink true
org.gnome.desktop.interface cursor-size 24
org.gnome.desktop.interface cursor-theme 'DMZ-White'
org.gnome.settings-daemon.plugins.cursor active true
org.gnome.settings-daemon.plugins.cursor priority 0
org.gnome.yelp show-cursor false
org.x.editor restore-cursor-position true
```

You can also check your `mouse` setting this way.

**Comment by jsmad** [comment]
Just to add to the confusion, its definitely not related to the nvidia driver, because I have the same  problem in my laptop running Cinnamon, which uses the nouvo driver with the Intel graphics chipset.
