### ISSUE TITLE
open file dialog, missing "backspace"

### ISSUE THREAD

**Issue by jsmad** [linuxmint/Cinnamon#4872]
In the old gnome2 open file dialog, we could hit "backspace" to traverse upwards the directory tree without using the mouse. It seems that the Cinnamon dialog is missing this functionality.

So this must be a feature request :)

**Comment by JosephMcc** [comment]
Sorry but this isn't a Cinnamon issue but an issue with Gtk.

**Comment by dmatic** [comment]
As described [here](https://askubuntu.com/questions/1046296/navigate-to-parent-folder-with-backspace-key-in-open-file-dialog), this can be achieved by creating the file ~/.config/gtk-3.0/gtk.css with the following content:

```
@binding-set MyOwnFilechooserBindings
{
    bind "BackSpace" { "up-folder" () };
}

filechooser
{
    -gtk-key-bindings: MyOwnFilechooserBindings
}
```
 
With this fix open file dialog now works with "backspace" key. Fresh mint install should contain this file. I don't know if this is the right place for this proposal, though.

**Comment by claudiux** [comment]
@dmatic Thank you! I updated the file `~/.config/gtk-3.0/gtk.css` with these lines (before all other lines) and it works like a charm!
```
@binding-set MyOwnFilechooserBindings
{
    bind "BackSpace" { "up-folder" () };
}

filechooser
{
    -gtk-key-bindings: MyOwnFilechooserBindings
}

/***** scrollbar slider - cinnamon-settings-generated - do not edit *****/
scrollbar slider {
    min-width: 12px;
    min-height: 12px;
}
```
The `scrollbar slider` parameters can always be changed using `System Seetings -> Themes -> Settings tab`, without any problem.

**Comment by mtwebster** [comment]
It might be better in /etc/gtk-3.0 - this way it could apply to all users (it could only be placed into a new user's .config folder, not existing).
