### ISSUE TITLE
Problem with editing Main Menu and changing deffault application for a file.

### ISSUE THREAD

**Issue by anthony0013** [linuxmint/cinnamon#4873]
Problem with editing Main Menu and changing default application for a file.
Please check this video:
https://youtu.be/mu8sATYcegI

I've just installed WinFF, and icons in menu are not created, but I can run application from terminal.

Linux Mint 17.2 Cinnamon x32 /// kernel 3.16.0-38-generic

**Comment by Vahan86** [comment]
@anthony0013, is this still an issue in Cinnamon 4.2?

**Comment by Vahan86** [comment]
@icarter09, can we close this issue since there is no response from OP?
