### ISSUE TITLE
sound applet - bluetooth

### ISSUE THREAD

**Issue by sakulstra** [linuxmint/Cinnamon#4874]
When connecting to a bluetooth speaker the sound output automatically switches to the bluetooth speaker, which i think is the expected behaviour - but when adjusting the sound volume via applet or fn key the sound volume still adjusts the "internal output", so one have to open the sound settings and select the bluetooth speaker manually.
The expected behaviour would be, that the volume settings automatically apply to the selected output.

Regards,
Lukas

**Comment by ManIVIctorious** [comment]
The cinnamon sound settings have been improved with the switch to cinnamon 3.0, is this still an issue for you in latest cinnamon?

**Comment by sakulstra** [comment]
Actually It got a lot worse :/ which may not be related to cinnamon but mint 18 in general...
Bluetooth doesn't really work at all any more. I could add the speaker one initial time and it's unfunctional since than.
![cinnamon](https://cloud.githubusercontent.com/assets/4396533/18746131/fadbc8aa-80c5-11e6-97ba-ae4161030fc9.gif)

**Comment by NikoKrause** [comment]
Bluetooth has been improved in LM 18.2. Maybe you give it a try?

**Comment by sakulstra** [comment]
Sadly i cannot :/ Not usingen cinnamon any more - feel free to close that issue.

**Comment by NikoKrause** [comment]
@sakulstra 
I can reproduce this on my Dell Notebook with Built-In Bluetooth.
It happens here because the bluetooth is blocked. I have to do the following command in the terminal:
```
rfkill unblock bluetooth
```

Can you tell, which device you have?
