### ISSUE TITLE
[URGENT!!] The new one version is too hard to use

### ISSUE THREAD

**Issue by BloodFever5634** [linuxmint/Cinnamon#4875]
the title says it all, please fix ASAP

**Comment by Topperfalkon** [comment]
Erm, no it doesn't?

What is the problem you're having?

**Comment by BloodFever5634** [comment]
IGNORING You!!!

**Comment by Topperfalkon** [comment]
Ok, fine. I'm not sure why you expect the developers to have any better idea...

**Comment by AlbertJP** [comment]
Closed for obvious reasons. You have to provide more details to be taken seriously.
