### ISSUE TITLE
Window preview does not scale correctly

### ISSUE THREAD

**Issue by utack** [linuxmint/Cinnamon#4877]
The new Window preview in 2.8.5 does scale when the high dpi setting is enabled and is tiny and misplaced:
![bildschirmfoto vom 2015-11-25 20-45-37](https://cloud.githubusercontent.com/assets/8551234/11408123/794025bc-93b7-11e5-847b-e21578e8ec8a.png)

**Comment by JosephMcc** [comment]
There is already a PR to fix this: https://github.com/linuxmint/Cinnamon/pull/4868

**Comment by utack** [comment]
Oh well, I only checked issue reports, sorry and thanks.

**Comment by JosephMcc** [comment]
The fix is merged now.
