### ISSUE TITLE
Improvement for the Return from Suspend Mode Login Routine.

### ISSUE THREAD

**Issue by RadicalRadish** [linuxmint/Cinnamon#4878]
(I am assuming this is a Cinnamon issue. If it isn't would it be possible for someone to move it to the appropriate category.)

How to express this? I have the system in "Suspend/(Sleep) Mode". When I press a key on the keyboard the system comes out of Suspend Mode and a login dialogue appears. What I want to suggest concerns this login dialogue and the sequence of events that follow it.

As things stand just now when that login dialogue appears the user thinks that they can immediately start typing in their login password. But if the user immediately tries that it doesn't work. The reason seems to be that the keyboard has to be initialised first (at least I take that is what happening when the keyboard lights flash after the user gets presented with this login dialogue). So what generally happens to me (and I would suspect to other users as well) is the following:

1) As soon as the login dialogue appears I start typing immediately and find that as I type no characters are being entered into the login text box. (My immediate reaction is, "Obviously there is something wrong with this computer.")
2) Now the keyboard initialisation process steps in and the keyboard suddenly becomes useable.
3) However, during all this process I've still been typing and, from the instant the keyboard does get initialised, the characters that I type do get entered. This is problematic because what has actually happened is that I have managed to type in, say, half a password and then I hit <Enter>. Result is groans and mumbles as you then have to 're-enter' the password in full.

To my way of thinking this is not a good login process sequence of events. I would be much better if the following process sequence was followed in this order:

1) Press the keyboard to launch system out of Suspend mode.
2) The keyboard gets initialised.
3) Only AFTER the keyboard gets initialised should the login dialogue be presented to the user (with, of course, the system focus being in the "login text box" so that the user can then immediately type in their full password without having to click inside the text box first).

(I haven't tested other instances of when the login dialogue is presented to the user but if this kind of thing occurs during login from other 'modes' the system can be in then it would be best if the above suggested login sequence was used as well.)

Is this important? Why is this important? I would say this is crucially important. For people coming new to Linux Mint - say from Windows - they are hyper-sensitive to anything that might seem like a bug, a glitch, a just lack of attention to detail in the ease of use experience. It this kind of thing that can turn a potential new user of Mint into someone that thinks, "No, this OS isn't really ready yet. Even the login doesn't work without problems." Because the potential new user will identify the kind of niggling issue I've described above as a 'fault' and so they just switch off from installing Mint. Attention to detail is important - fine polishing is important

I would add that I think this would be very easy to code. Maybe not much more than switching some code into a different sequence order that just ensures the keyboard is initialised BEFORE the login dialogue appears.

Hope this helps.

**Comment by RadicalRadish** [comment]
Sorry, I forgot to include system details. As follows:
Linux Mint 17.2 x64 Cinnamon Edition - Rafaela
Cinnamon 2.6.13
Nemo 2.6.7

**Comment by lestcape** [comment]
Hi @RadicalRadish in any case i think will be more helpfully If you are using mdm(Mint Display Manager) if you post your request here:  https://github.com/linuxmint/mdm/issues

I don't know if this can be consider a bug or not, but if it's not and is the plan, because wherever.... You can switch to other display manager more interesting to you without lost cinnamon.

Regards.

**Comment by RadicalRadish** [comment]
Thanks for letting me know I've posted in the wrong place, lestcape.

I'll post it in the place that you suggest. I'm a complete newbie to Mint and honestly don't know the names of the different components that make it up - I tend to think that everything is 'Cinnamon' just now.

If anyone can delete my OP from here then please do so.
