### ISSUE TITLE
Window preview uses wrong window title

### ISSUE THREAD

**Issue by utack** [linuxmint/Cinnamon#4879]
The new window preview in 2.8.5 always seems to use the "first" title for all instances of the same application.
For example nemo on the left was opened first, then the one on the right, which should have the title "tmp":
![bildschirmfoto vom 2015-11-25 20-45-37](https://cloud.githubusercontent.com/assets/8551234/11408173/bd89c098-93b7-11e5-92cd-f30e26340465.png)

The old title persists when the first instance of the application is closed and for all new windows opened after that.

Edit: It also happens for a single application instance, some old title can get permanently stuck
![bildschirmfoto vom 2015-11-26 05-12-29](https://cloud.githubusercontent.com/assets/8551234/11414953/699d3af6-93fc-11e5-9a32-c82da43eb8eb.png)

**Comment by donlencho** [comment]
Good to read this has been fixed in git, but will it actually be merged into 2.8? It has been a while since the fix is reported but still no update for cinnamon in Mint 17.3.
Thank you,
