### ISSUE TITLE
documentation bug: addCommandlineAction - addCommandLineAction

### ISSUE THREAD

**Issue by hyOzd** [linuxmint/Cinnamon#4880]
There is a slight documentation bug here:

https://github.com/linuxmint/Cinnamon/blob/9ec0aaade7358e79636285d8cde177288999745f/js/ui/popupMenu.js#L1641

The function addCommand**l**ineAction, is documented as addCommand**L**ineAction. Also can be seen in this page:

http://developer.linuxmint.com/reference/2.6/cinnamon-js/cinnamon-js-ui-popupMenu-PopupMenuBase.html#cinnamon-js-ui-popupMenu-PopupMenuBase-addCommandLineAction

I know it's a small thing but these kind of problems can take unexpected amount of time to figure out for newcomers :)

**Comment by dalcde** [comment]
Fixed
