### ISSUE TITLE
BUG - Italian translation only - Create new Template

### ISSUE THREAD

**Issue by Timmy93** [linuxmint/Cinnamon#4882]
I'm using Linux Mint 17.2 Cinnamon 2.6 and I think to have found a bug in templates.

I created a model in "~/Modelli" (it's italian) that should be the english "~/Templates".
A simple empty file saved as "text.txt".
Then when I press right click of mouse>Create new document>text.txt it creates me a new file called: "text.txt senza nome" (in english "Unamed text.txt").
The problem is that the only part highlighted is "text" so if I change the name in "newText" I obtain: "newText.txt senza nome".

Is it possible to solve this problem? It's not so heavy cancel each time " senza nome" from the new file but it's of course a bit annoying.

**Comment by Timmy93** [comment]
EDIT: in English "Modelli" is "Templates" not "Models".
Mutatis mutandis, sorry for the mistake.

**Comment by JosephMcc** [comment]
This is handled by Nemo: https://github.com/linuxmint/nemo/issues
