### ISSUE TITLE
cinnamon not respecting skip_tasklist

### ISSUE THREAD

**Issue by brianjmurrell** [linuxmint/Cinnamon#4884]
The Window List panel applet is not honouring the skip_tasklist property which can be set by either devilspie or wmctrl.

```$ devilspie -d``` reports for example:
```
Setting pinned
Skipping tasklist
Window Title: 'Bilbo Baggins'; Application Name: 'Pidgin'; Class: 'Pidgin'; Geometry: 896x473+1600+1447
Setting pinned
Skipping tasklist
Window Title: 'Buddy List'; Application Name: 'Pidgin'; Class: 'Pidgin'; Geometry: 184x616+2496+1303
```

And while those Pidgin windows are pinned they still show up in the list of windows on the taskbar.

Additional reports of this from the Intertubes:

https://bugs.launchpad.net/linuxmint/+bug/1129028
https://www.reddit.com/r/linux4noobs/comments/27dgl4/

I'm using Cinnamon 2.8.3 here on FC23 but given the above reports, this has been around for a while.

**Comment by JosephMcc** [comment]
https://github.com/linuxmint/Cinnamon/issues/5162
