### ISSUE TITLE
German translation for Indicator setting misguiding

### ISSUE THREAD

**Issue by utack** [linuxmint/Cinnamon#4888]
The string to enable or disable indicators (translated to "Anzeigen" in the German language) is misguiding, since "Anzeigen" will most likely be interpreted as "Displays" and definitely not as indicators.

![xyjfp_swtz](https://cloud.githubusercontent.com/assets/8551234/11453947/033ce472-961e-11e5-8edf-cc7e95342bde.png)

**Comment by tomoe-musashi** [comment]
i see the latest translation get it fixed in launchpad, maybe you could install the latest translations package and check whether its fixed or not.
if you have any problem on l10n, you can visit launchpad.net and join the local team for translations.
translations are handled in launchpad.
