### ISSUE TITLE
systray not displaying backintime icon

### ISSUE THREAD

**Issue by denispr** [linuxmint/Cinnamon#4893]
When backintime performs a backup, it is supposed to display an icon in the systray. This is what happens on Mate desktop, but unfortunately not with Cinnamon 2.8.4 on LMDE Betsy.

**Comment by denispr** [comment]
Still there with cinnamon 3.0.5 on LMDE Betsy.
Is there any debugging info I can provide to help fixing it ?
Thanks

**Comment by denispr** [comment]
Still not fixed in Cinnamon 3.2.7+betsy.
Any chance someone takes care about it soon ? Backintime icon is properly displayed on other DE : Mate, Gnome, Budgie...
Thanks

**Comment by Vahan86** [comment]
@denispr, is this still an issue in Cinnamon 3.8?

**Comment by denispr** [comment]
Fixed witn Cinnamon 3.8.9 on LMDE Cindy !
