### ISSUE TITLE
Wrong download link

### ISSUE THREAD

**Issue by outrofelipe** [linuxmint/Cinnamon#4898]
The download link for linux mint cinnamon 17.2 64 bits is redirecting for MATE version. The name of file is ok (Linux Mint Cinnamon 17.2 64 bits), so I only discover it after finished the download. 
Link: http://www.linuxmint.com/edition.php?id=190, I try torrent and brazilian mirror link.

**Comment by JosephMcc** [comment]
Ok, thanks for reporting this. I'm going to close it but I'll try to let the right people know.
