### ISSUE TITLE
Interrupted text in terminal

### ISSUE THREAD

**Issue by ACinnamonUserInUK** [linuxmint/Cinnamon#4901]
Dear all

Could we avoid the situation whereby one opens a terminal, starts typing and, because the system is under load (and the processor slow?), some text appears *before* the terminal prompt, as in the attached screenshot? Thanks. 
![screenshot-window-2015-12-01-020310](https://cloud.githubusercontent.com/assets/9998846/11490390/2f1b304a-97d0-11e5-8cbc-a2d3fc14d1c4.png)
(In the screenshot, one can see the first three characters of 'screenfetch' appearing before the prompt.)

**Comment by leigh123linux** [comment]
There are two solutions.

1. Type slower!
2. Get a faster proc!

**Comment by dalcde** [comment]
Not a Cinnamon issue
