### ISSUE TITLE
Window-list: window thumbnail remains open after opening the main window.

### ISSUE THREAD

**Issue by Vahan86** [linuxmint/Cinnamon#4903]
When you hover over item from window list, window thumbnail appears. But when you left click item to open a window, after the window is open, the window thumbnail isn't closed. (please see attached screenshot).

![untitled](https://cloud.githubusercontent.com/assets/12819058/11508755/6e5aa2a4-986b-11e5-954d-fb08d322cbf8.png)

It would be better if after opening the main window, window thumbnail will disappear, since after the main window is open, there is no sense of open window thumbnail.

**Comment by pixunil** [comment]
I think it is generally unnecessary to show the preview if the window has focus.

**Comment by JosephMcc** [comment]
It only shows as long as you hover the item in the window list. That is how it's supposed to work.

**Comment by Vahan86** [comment]
Even if you hover the item in the list, and the window has already had focus it is unnecessary to show the preview. It's just my opinion.
