### ISSUE TITLE
False click detection when opening a menu

### ISSUE THREAD

**Issue by ngabor7** [linuxmint/Cinnamon#4904]
I noticed a bug when if I open a menu (start menu or right click menu) and move my mouse before the menu actually gets opened and at the moment when the menu opens my mouse happens to be above a button (for example above the shut down button in the start menu) it will register it as if I clicked that button. It doesn’t happen every time, but I think it is easier to reproduce this bug when running the os from the live cd, since the first and most times I encountered this bug was when I started installing mint from the live cd, but it happens even now after it is installed.

**Comment by ManIVIctorious** [comment]
Whitch version of cinnamon are you using? I remember having this issue on cinnamon 2.4.x but after that it worked well.

**Comment by ngabor7** [comment]
Cinnamon 2.6.13
Linux Mint 17.2 Rafaela 64 bit
Linux Kernel 3.16.0-38-generic
Processor Intel Core i3-2348M CPU @ 2.30 GHz x 2
RAM 4 GB
Graphic Card #1 Nvidia GeForce 710M with 1GB VRAM
Graphic Card #2 integrated Intel

**Comment by Vahan86** [comment]
@ngabor7, is this issue still relevant to Cinnamon 3.2?

**Comment by Vahan86** [comment]
@JosephMcc, can we close this issue?
