### ISSUE TITLE
[Feature Request] Option to expand folders on the desktop

### ISSUE THREAD

**Issue by ngabor7** [linuxmint/Cinnamon#4905]
So I think it would be cool if it was possible to expand folders on the desktop. I'm thinking of some kind of container inside which is the content of the folder and on the upper side of the frame of the container is the folder which is expanded. As for the way to expand the folders maybe I would add an entry to right click menu, idk.

**Comment by JosephMcc** [comment]
This would best be a feature request for Nemo since it actually handles this. Do a search there because I could have sworn we already had a similar feature request.
https://github.com/linuxmint/nemo/issues
