### ISSUE TITLE
Cannot Open cinnamon-settings in Fedora 23

### ISSUE THREAD

**Issue by cschlick** [linuxmint/Cinnamon#4906]
I cannot open cinnamon-settings in Fedora 23. I verified that PyGObject2 was up to date, so I believe this is a bug. Maybe it belongs in the Fedora bugzilla? I am new to bug reporting fyi

$ cinnamon-settings
Traceback (most recent call last):
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 12, in <module>
    import gi
ImportError: No module named gi

**Comment by RavetcoFX** [comment]
You are missing the pygobject3 package, this is probably an issue with how it was packaged on Fedora

**Comment by leigh123linux** [comment]
@RavetcoFX  you seem to be right this time :+1: 
@cschlick It appears you installed cinnamon in a non-standard way (didn't use cinnamon install media or groupinstall)

Run this to fix (other packages in the group require the missing package "python-gobject")

```
sudo dnf update
sudo dnf install @cinnamon-desktop
```

I have also fixed the issue in cinnamon-2.8.5-3.fc23

https://koji.fedoraproject.org/koji/buildinfo?buildID=702691

or wait for the update

https://bodhi.fedoraproject.org/updates/FEDORA-2015-191b0e0824

**Comment by RavetcoFX** [comment]
@leigh123linux hehe

**Comment by cschlick** [comment]
So I install cinnamon from a default F23 install using the recommended way. Here it is again:

dnf install @cinnamon-desktop
Last metadata expiration check performed 1:46:31 ago on Wed Dec  2 13:29:51 2015.
Group 'Cinnamon' is already installed, skipping.
Dependencies resolved.
Nothing to do.
Complete!

dnf install pygobject3
Last metadata expiration check performed 1:46:31 ago on Wed Dec  2 13:29:51 2015.
Package python-gobject-3.18.2-1.fc23.x86_64 is already installed, skipping.
Dependencies resolved.
Nothing to do.
Complete!


Yet, I get the error message.

**Comment by RavetcoFX** [comment]
@cschlick check if you have python-gobject installed

**Comment by leigh123linux** [comment]
@cschlick 

Can you check that python-gobject installed python-gobject-base as a requires.

**Comment by linux-modder** [comment]
in fedora it's @cinnamon-desktop-environment  NOT @cinnamon-desktop

**Comment by cschlick** [comment]
dnf install @cinnamon-desktop-environment
Last metadata expiration check performed 0:13:22 ago on Thu Dec  3 15:17:33 2015.
Environment 'Cinnamon Desktop' is already installed, skipping.
Dependencies resolved.
Nothing to do.
Complete!
dnf install python-gobject-base
Last metadata expiration check performed 0:13:40 ago on Thu Dec  3 15:17:33 2015.
Package python-gobject-base-3.18.2-1.fc23.x86_64 is already installed, skipping.
Dependencies resolved.
Nothing to do.
Complete!
dnf install python-gobject
Last metadata expiration check performed 0:13:47 ago on Thu Dec  3 15:17:33 2015.
Package python-gobject-3.18.2-1.fc23.x86_64 is already installed, skipping.
Dependencies resolved.
Nothing to do.
Complete!
 
And still the same error. I don't want to reinstall the os because I just got all my stuff compiled and set up which took a couple days. I guess I will need to wait for the cinnamon update?

**Comment by leigh123linux** [comment]
@cschlick 

Have you been messing around with python?

https://bugzilla.redhat.com/show_bug.cgi?id=1284929

**Comment by cschlick** [comment]
Thanks, I'm an idiot. A custom Python interpreter was being used as the default. Everything works fine.
