### ISSUE TITLE
window stuck to task bar when draging

### ISSUE THREAD

**Issue by northteam** [linuxmint/Cinnamon#4907]
After running Ubuntu for days, when I dragging some window from window list, the window tab occasionally gets stuck to the task bar, and the mouse pointer remains the icon when dragging. The stuck window cannot be moved or get focus any more through mouse.

![screenshot from 2015-12-01 21 12 48](https://cloud.githubusercontent.com/assets/218151/11524558/907d4436-9906-11e5-97f9-69e4010f1e30.png)

OS: Ubuntu 14.04 64bit
cinnamon: 2.6.13

**Comment by northteam** [comment]
I finally figure out when will this happen. I am using VirtualBox in full screen mode on one of my monitors. When VirtualBox get focused, I try to move window tab in window list bar on the other monitor. The window tab will freeze on window list bar, and cannot be moved any more.

**Comment by Vahan86** [comment]
@northteam, is this issue still relevant to Cinnamon 3?

**Comment by northteam** [comment]
I have switched back to Ubuntu unity for a while and can not confirm this issue.

**Comment by JosephMcc** [comment]
Ok, since you can't confirm it and no one else has reported it, I'm going to close it.

**Comment by aidan2129** [comment]
I am getting this problem now and then running linux mint 18.

**Comment by rdrpenguin04** [comment]
I can confirm on Linux Mint 19. Please reopen this.

**Comment by leigh123linux** [comment]
@rdrpenguin04 A me to on the end of an issue closed two years ago isn't the way to report, start a new one with full info.

Locked!
