### ISSUE TITLE
Sound applet & Parole - inconsistent volume

### ISSUE THREAD

**Issue by jsmad** [linuxmint/Cinnamon#4908]
I found some inconsistencies between the sound applet and the parole player. When I change volume from parole, for example from 20% to 50%, the main volume is also raised but it goes from 50% to 70%, which makes the overall audio too loud.

Thus, I try to lower the volume from the sound applet, but because the % is higher, it makes parole's volume go down to 0% and it mutes completely.

In the attached image, you can see how I started lowering the volume from the sound applet from 100% down to about 80%. You can also see how the volume of parole dropped down to 0% at the same time.

![screenshot](https://cloud.githubusercontent.com/assets/279256/11528516/ec35c670-98ef-11e5-92e3-db9f0d09215a.png)

**Comment by Vahan86** [comment]
@jsmad, is this still an issue for you in Cinnamon 3?

**Comment by jsmad** [comment]
Yes I'm still having this problem with Cinnamon 3.0.7 (Fedora 23).

**Comment by leigh123linux** [comment]
Parole controls application volume only not master, if you think it should be different file a bug against parole.
