### ISSUE TITLE
Screen does not lock when monitor turns off

### ISSUE THREAD

**Issue by raidermax** [linuxmint/Cinnamon#4909]
I have the setting "Lock the computer when the screen turns off" set to ON. However if I manually turn off my monitor and turn it back on, it does NOT ask me for my password.

I am on arch linux using latest cinnamon available.

**Comment by pixunil** [comment]
If I understood you correctly, you pressed the hardware power button of your monitor.
Cinnamon does lock your screen when the monitor is turned of by software (→ _not_ by hardware). Typically, this is the case when you're setting "Turn of monitor when inactive for _x_ minutes" (could be labelled different) in your power settings.

I'm unsure whether it is possible to detect the power state of connected monitors by software, in other words if your assumed behaviour can be implemented.

**Comment by raidermax** [comment]
I could've sworn though in past releases I would turn off the monitor by the physical button and it lock. If it has never done this then my memory is just getting confused. I don't have any other versions of cinnamon to test though.

**Comment by JosephMcc** [comment]
I don't think we can even do what you are talking about.
