### ISSUE TITLE
Screen Lock will not Accept no password to resume session

### ISSUE THREAD

**Issue by ugadog** [linuxmint/Cinnamon#4910]
I set up an account for the kids on Linux Mint 17.2 Cinnamon Version 2.6.13 Linux kernel 3.16.0-38.  As it is just browser and educational games I set no password for this standard user.  Initial login is fine with blank password entry but when computer wakes from screen lock to login password,  login will not accept a blank password entry to resume kids session. Login dialog returns "Incorrect Password".  Error is reproducible with a timed lock and/or a manual Screen Lock.  This error occurs every lock screen.

Workaround is to click switch user and select the kids account to resume kids session.  Easy workaround for me but not intuitive for 8 year olds, giving them a reason to ditch homework I assign. 

Edit:  Error also occurs when powering off from other session.  Cinnamon asks for session password and will not accept password being left blank though kids user is set to no password.  Workaround is switch users to kids and power off from there.

**Comment by TehLeviter** [comment]
I have the same problem, two accounts, one without password but it will not let me in after I lock the screen.

**Comment by Vahan86** [comment]
@JosephMcc, issue https://github.com/linuxmint/cinnamon-screensaver/issues/15
