### ISSUE TITLE
Cinnamon --replace never fishes

### ISSUE THREAD

**Issue by Zerophase** [linuxmint/Cinnamon#4912]
Since updating to Cinnamon 2.8 `cinnamon --replace` seems to be freezing in the command line. Eventually, it gives up or I close the prompt and I lose the ability to interact with my desktop correctly.

Error output:
>Cjs-Message: JS LOG: About to start Cinnamon
>St-Message: cogl npot texture sizes SUPPORTED
>Cjs-Message: JS LOG: Cinnamon started at Thu Dec 03 2015 08:28:02 GMT-0600 (CST)
>Cjs-Message: JS LOG: network applet: Cannot find connection for active (or connection cannot be read)
>Cjs-Message: JS LOG: Invalid network device type, is 14
>Cjs-Message: JS LOG: network applet: Found connection for active
>Cinnamon WARNING: Possible orphan label being accessed via st_label_set_text().  Check your timers and handlers!
>Address: 0x3ce1f30  Text: 0
>Cinnamon WARNING: Possible orphan label being accessed via st_label_set_text().  Check your timers and handlers!
>Address: 0x622d380  Text: 0
>Cinnamon WARNING: Possible orphan label being accessed via st_label_set_text().  Check your timers and handlers!
>Address: 0x5713000  Text: 0
>Window manager warning: Log level 16: STACK_OP_RAISE_ABOVE: sibling window 0x1200073 not in stack
>Window manager warning: Log level 16: STACK_OP_LOWER_BELOW: sibling window 0x1200073 not in stack
>Cinnamon WARNING: Possible orphan label being accessed via st_label_set_text().  Check your timers and handlers!
>Address: 0x4c8bb00  Text: 0
>Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x1200019 (Steam)
>Cinnamon WARNING: Possible orphan label being accessed via st_label_set_text().  Check your timers and handlers!
>Address: 0x590df00  Text: 0

**Comment by ManIVIctorious** [comment]
cinnamon --replace is starting cinnamon, so the process ends when you kill cinnamon / log out. 
You can start it in the background with
cinnamon --replace &
and then enter exit (or hit ctrl-d) to close the shell.

**Comment by Zerophase** [comment]
Ah ok, so the behavior of `cinnamon --replace` was just changed?  I remember being able to run `cinnamon --replace` to reload cinnamon in the previous release.

**Comment by lestcape** [comment]
@Zerophase Your sure remember another thing.
http://unix.stackexchange.com/questions/4004/how-can-i-close-a-terminal-without-killing-the-command-running-in-it

**Comment by ManIVIctorious** [comment]
It never changed, it always behaved this way

**Comment by Zerophase** [comment]
@lestcape I get the `&` usage. I'm just saying previously whenever I ran `cinnamon --replace` from within a terminal I'd get the terminal back afterwards, at least in Arch.

**Comment by dalcde** [comment]
I've always needed to use & for this to work properly

**Comment by Zerophase** [comment]
Thanks, I can just add `&`
