### ISSUE TITLE
A network manager bug

### ISSUE THREAD

**Issue by ACinnamonUserInUK** [linuxmint/Cinnamon#4913]
What happens: If (via the Network Manager program) one enters a wrong password for a network - or at least a wireless one - one cannot easily change that password. To do that, I find that I must tell Mint (via, I think, that same application) to forget the connection, then switch wifi (as a whole on) and then off again, then try to reconect to the network (at which point one will be prompted for a new password). But - ah - there is an 'edit' option under Network Connections. I think this should be easier to find. 

What should happen: it should be a simpler and more intuitive process to re-enter a network password.

Mint 17.2. Cinnamon 2.8.

**Comment by Vahan86** [comment]
@ACinnamonUserInUK, is this still an issue for you in Cinnamon 3.2?

**Comment by ACinnamonUserInUK** [comment]
Hi Vaham86

I am afraid I do not know. Nor do I want to find out, because my network setup (which, now - but not when I filed the bug - involves a VPN) is rather fragile ; so I don't want to start fiddling with the connections, I am afraid.
