### ISSUE TITLE
Another Network Manager bug

### ISSUE THREAD

**Issue by ACinnamonUserInUK** [linuxmint/Cinnamon#4914]
What happens: sometimes (but not always), after entering incorrect password for a network, that network seems to disappear from the menu (without one telling Mint to forget about it).

What should happen: I imagine that the network should not disappear but remain in the list, and re-prompt for a password - with an indication that the previous one was rejected.

Mint 17.2. Cinnamon 2.8.

**Comment by RavetcoFX** [comment]
I can't seem to reproduce this, is this still happening? If so what kind of network is it? (Secured, Not ect.) Could you possibly include a screenshot or recording of this happening if it still does.

**Comment by JosephMcc** [comment]
A request for more info was never responded to.
