### ISSUE TITLE
Start menu is slow, not very responsive

### ISSUE THREAD

**Issue by TurkeyMan** [linuxmint/Cinnamon#4916]
Open the start menu, hover over the various app categories and applications; notice that the highlight cursor, and subcategory listing lags significantly behind the mouse, I estimate close to 100ms for the menu to update and render. Computer is very high perf, it's just this menu update/rendering appears to be quite inefficient.
The menu should be snappy, menu updates and render should happen instantaneously. User-perceptable lag behind the mouse isn't a very good look, makes the OS feel generally slow and sluggish, even though it's not.

**Comment by lestcape** [comment]
@TurkeyMan This is known and i propose a solution here: https://github.com/linuxmint/Cinnamon/issues/4464

**Comment by lestcape** [comment]
https://github.com/linuxmint/Cinnamon/issues/4984

**Comment by leigh123linux** [comment]
@TurkeyMan 

It doesn't matter how powerful your PC is as cinnamon is single threaded!

**Comment by lestcape** [comment]
@leigh123linux relax, he is interested in performance and certainly always there are a better way to do the things. I hope he can realize that if he want improve things, he need to read a lot of code and take in account a lot of thing. No one can explain all that's involved and if some one realize that there are a better way to do the things, i think will be merged. All things related about performance is pretty interesting. This is not like predefined actions, so i think will be a pleasure know that something could be better. Let him prove it.
