### ISSUE TITLE
Cinnamon crashes with Firefox using an "black background" app going to certain pages

### ISSUE THREAD

**Issue by elDan101** [linuxmint/Cinnamon#4917]
Hi, 

OS:
Linux Mint 17.2 64 bit Cinnamon (2.6.13) 

It took me a while to figure out what the issue was, but now I am able reproduce the bug on my machine (details see below). Every time I visit certain (not every) webpages, e.g. https://en.wikipedia.org/wiki/Runge%E2%80%93Kutta_methods, Cinnamon crashes (i.e. the Linux Mint login screen appears with the current session lost).  

Setting to produce crash:

* "Firefox 42.0 for Linux Mint" 
* Inside Firefox I'm using the "Black background and white text app" Version 0.3.7.1-signed https://addons.mozilla.org/en-US/android/addon/black-background-white-text/
* Visit above example page with "inverted" (I didn't try out different the other possibilities yet)

**Comment by elDan101** [comment]
upgraded to Cinnamon 2.8.6 - crash does not occur anymore, at least not for the example page above (I'll leave it on for a while).

**Comment by JosephMcc** [comment]
After you've tested for a bit, if you don't encounter anymore issues, could you close the issue?

**Comment by elDan101** [comment]
new test site, reproducible every time I go to this page (2 times):
https://en.wikipedia.org/wiki/Floating_point

I observed that when I load it in a tab it loads and when I open the tab Cinnamon crashes. Another observation: so far only Wikipedia articles (while studying, highly inconvenient). More information is provided on request. 

I leave the app off, which is unfortunate for my eyes :/

**Comment by JosephMcc** [comment]
Check ~/.xsession-errors and see if there is anything that might be related.

**Comment by elDan101** [comment]
I just reproduced the crash, and now look at the mentioned .xsession-errors file.
I don't understand much but just by interpreting this might be the only thing that could be related:

(gnome-terminal:10138): GLib-GIO-CRITICAL **: g_settings_get: the format string may not contain '&' (key 'monospace-font-name' from schema 'org.gnome.desktop.interface'). This call will probably stop working with a future version of glib.
nm-applet-Message: moving back from GtkStatusIcon to indicator

**Comment by JosephMcc** [comment]
Those errors have nothing to do with your issue. Next time it happens maybe pastebin the entire .xsession-errors files and drop a link here.

**Comment by elDan101** [comment]
Updated to Firefox 43.0 
Crash still occurs as described above. 

.xsession-error file after crash:
http://pastebin.com/raw/ZUN3guva

**Comment by elDan101** [comment]
Updates:
Dark-background-light-text-extension 0.5.3 (renamed)
Firefox 45.0 

I was not able to reproduce any of the errors.
