### ISSUE TITLE
supend to ram on closing laptop only works after one manual try

### ISSUE THREAD

**Issue by verymilan** [linuxmint/cinnamon#4919]
Hi, i have an problem with my macbook late 2008 running archlinux:

If i try to set the laptop in str on closing it, it doesnt work.
If i do it from the menu or via console command, it works fine.
After trying it manually, it will work on close...in one mode... if its on power, 
i have to set it manually to suspend again.

This problem is only in cinnamon. Gnome, or awesomewm working fine!
_Edit: this time on power it worked after the second try on closing._

**Comment by keitalbame** [comment]
I also have this issue on Arch.
I previously had Gnome and never had issues.

**Comment by keitalbame** [comment]
Just notice that you mentioned suspend to RAM.

In my case, I have swap partition and suspend normally will use swap for this.

Searching the issues, I found #3054 that points to # 42 on linuxmint/cinnamon-settings-daemon.
Commit 9f3e78c was done, but right now, the code seems to be changed or that same commit is configured on a different place or in a different way.
Is this a cinnamor or upower bug?

This were my tests with Dell laptopts, E6400(Arch Linux) and D630(first with Mint 17.2 and after upgrade to 17.3) with and without AC:

Test 1

1-turn on laptop
2-confirm power management on AC and battery are configured to "Suspend" on lid close and when power button pressed, set to "Ask"
3-close lid

expected action: laptop to suspend
actual action: laptop stays on

4-open lid
5-close lid

expected action: laptop to suspend
actual action: laptop stays on


Test 2

1-turn on laptop
2-Configure power management on AC and battery, to suspend when inactive for 5m. Confirm if "Suspend" on lid close is selected and when power button pressed, set to "Ask"
3-wait for suspend on inactive.
4-power on and login
5-close lid

expected action: laptop to suspend
actual action: laptop stays on

6-open lid
7-close lid

expected action: laptop to suspend
actual action: laptop stays on


Test 3

1-turn on laptop
2-confirm power management on AC and battery are configured to "Suspend" on lid close and when power button pressed, set to "Ask"
3-press power button and select suspend

expected action: laptop to suspend
actual action: laptop suspends

4-turn on laptop and login
5-close lid

expected action: laptop to suspend
actual action: laptop stays on

6-open lid
7-close lid

expected action: laptop to suspend
actual action: laptop stays on

8-open lid and wait 5m to suspend
9-power on and login
10-close lid

expected action: laptop to suspend
actual action: laptop suspends

Test 4

1-turn on laptop
2-confirm power management on AC and battery are configured to "Suspend" on lid close and when power button pressed, set to "Ask"
3-press power button and select suspend

expected action: laptop to suspend
actual action: laptop suspends

4-turn on laptop and login
5-close lid

expected action: laptop to suspend
actual action: laptop stays on

6-open lid
7-press power button and select suspend

expected action: laptop to suspend
actual action: laptop suspends

8-power on and login
9-close lid

expected action: laptop to suspend
actual action: D630: laptop suspends, on batteries. With AC it doesn't suspend. E6400: laptop always suspends, on batteries and AC, until reboot.

**Comment by Vahan86** [comment]
@tchncs, is this still an issue for you with Cinnamon 3.2?

**Comment by tchncs** [comment]
@Vahan86 unforunaly i don't have the hardware anymore - dunno if this happened with my computer too but i am with i3wm there now and don't have fast enough internet to be able to reverse check yet... .

**Comment by Vahan86** [comment]
@tchncs, thanks for your reply. In this case can you please close the issue?

**Comment by tchncs** [comment]
But i was not the only one with this issue, wasn't i?

**Comment by Vahan86** [comment]
@keitalbame, is this still an issue for you in Cinnamon 4.2?

**Comment by keitalbame** [comment]
@Vahan86 I'm no longer using Cinnamon, so I can not confirm if issue is still present.

**Comment by icarter09** [comment]
@keitalbame no worries and thanks for the update.
