### ISSUE TITLE
Applets/indicators

### ISSUE THREAD

**Issue by sadalavoaoj** [linuxmint/Cinnamon#4922]
Hi there,

My pidgin icon is too close to the dropbox one. The other icons are with correct space, is there a way to change manually this two icons space?

![captura de ecra de 2015-12-07 00 10 46](https://cloud.githubusercontent.com/assets/14188908/11616768/b3da0e78-9c7b-11e5-8cf3-3fce0b9d4b60.png)

**Comment by ACinnamonUserInUK** [comment]
One can change the spacing with the inbuilt 'spacer' applet. Or at least one is supposed to be able to - but it does not work properly, at least on my system. I find that brokenness one of the most irritating things about Cinnamon panels, sadly. I really think this stuff needs fixing *pronto*.

I had thought that I had reported this on this bit of github, or on https://bugs.launchpad.net/linuxmint, but unfortunately I cannot find the report.

**Comment by lestcape** [comment]
Hi @sadalavoaoj Can you detect if the was pidgin or dropbox how cause the issue? Please see, there is not the same the applet space to the systray space. The systray applet is one applet where you put icons with some space and the space between applets are of course different. Any way there are an issue about the systray space when you use the systray with appindicator support. this was fixed here:
https://github.com/linuxmint/Cinnamon/pull/4814

I supposed will be better now, but i think will not be perfect anyway.

**Comment by sadalavoaoj** [comment]
Hi @lestcape,

When i only have one dont cause the problem, only with both, so i cannot say wich one is because it happens when the two are together.

I will wait for a fix in the future.It is not urgent so i can wait for a fix.
Tks for the help :+1:

**Comment by Vahan86** [comment]
@sadalavoaoj, is this still an issue for you in Cinnamon 3.0.x?

**Comment by Vahan86** [comment]
@JosephMcc, can we close the issue?
