### ISSUE TITLE
Panel launcher applet: some icons do not show

### ISSUE THREAD

**Issue by CottonEaster** [linuxmint/Cinnamon#4923]
To reproduce (if it does reproduce on other systems):

Use the Panel Launcher applet to add a launcher to a panel, choosing for its icon this: bookmark-missing.svg
Then launcher will not then show, but if you click where it should be, it will function.

I think the problem may be using a .svg icon file. Also, though, even when the applet does appear, its tooltip is 'Files' even though that is not what I've changed the tooltip to show!

Mint 17.3
Cinnamon 2.8.6.
Desktop theme: Linux Mint

**Comment by Ertain** [comment]
I'm getting a similar problem with the applets in my panel.  I start an applet of some kind (Mint Update, for instance) and it doesn't show up.

**Comment by ManIVIctorious** [comment]
Same here with dropbox, it just vanishes but the program is still running.
Happens with indicators enabled and disabled, seems the systray still needs some work...

**Comment by ManIVIctorious** [comment]
@Ertain The systray-applet works quite different from the panel launcher applet, so I don't think these issues are related, just look at #4967, #1532 or #481

**Comment by NikoKrause** [comment]
Just tried it. SVG icons show fine. I'm closing this. If the problem still persists (on LM18.3/Cinnamon3.6.7), let us know.
