### ISSUE TITLE
Allow cycling through workspaces problem.

### ISSUE THREAD

**Issue by mattst** [linuxmint/Cinnamon#4924]
Using:  Linux Mint 17 Qiana, Cinnamon 64-bit 2.2.16

If the `Workspace` setting `Allow cycling through workspaces` is selected, users can scroll straight from the last workspace to the 1st and visa-versa but when doing so the window slide effect goes the wrong way from the conceptual loop. i.e.

If scrolling right from the 1st workspace to the last, the slide effect moves the windows in from the right, but when again scrolling right from the last workspace to the first, the slide effect moves the windows in from the left and it looks wrong. The same thing happens in reverse when scrolling left from the 1st workspace to the last.

Thanks.

**Comment by JosephMcc** [comment]
Duplicate https://github.com/linuxmint/Cinnamon/issues/4613

**Comment by mattst** [comment]
Oops sorry.
