### ISSUE TITLE
Linux Mint Cinnamon 17.3 crashes hourly after upgrade from 17.2

### ISSUE THREAD

**Issue by dblaisde** [linuxmint/Cinnamon#4928]
I get a pop up regularly which says (roughly) "Cinnamon has crashed. Would you like to restart it or stay in Fallback mode".

There's nothing in ~/.xsession-errors to help diagnose this. (as Clem advised to check on another bug report), and so far I haven't been able to reproduce it, or relate any specific actions to bring it about.

What should I do on this end to help you narrow it down, eg log files, dumps, etc?

uname -a:

Linux doug-X201EP 3.16.0-37-lowlatency #51~14.04.1-Ubuntu SMP PREEMPT Wed May 6 15:57:14 UTC 2015 i686 i686 i686 GNU/Linux

My machine is an Asus x201e, with 4GB memory, 32bit LM 17.3, Celeron(R) CPU 847 @ 1.10GHz, Intel internal graphics chip

This machine ran fine with 17.2 installed (running latest versions of LM for 2 years), but started crashing almost immediately after booting 17.3.

**Comment by dblaisde** [comment]
Changed the permissons on .xsession-errors and now there's something there, as follows:

/etc/mdm/Xsession: Beginning session setup...
localuser:doug being added to access control list
Script for none started at run_im.
/etc/mdm/Xsession: 31: /etc/X11/Xsession.d/98vboxadd-xclient: /usr/bin/VBoxClient: not found
/etc/mdm/Xsession: 32: /etc/X11/Xsession.d/98vboxadd-xclient: /usr/bin/VBoxClient: not found
/etc/mdm/Xsession: 33: /etc/X11/Xsession.d/98vboxadd-xclient: /usr/bin/VBoxClient: not found
/etc/mdm/Xsession: 34: /etc/X11/Xsession.d/98vboxadd-xclient: /usr/bin/VBoxClient: not found
/etc/mdm/Xsession: 35: /etc/X11/Xsession.d/98vboxadd-xclient: /usr/bin/VBoxClient: not found
Script for none started at run_im.
cinnamon-session[1842]: WARNING: t+0.12422s: Could not parse desktop file /home/doug/.config/autostart/indicator-remindor.desktop: Key file does not start with a group
cinnamon-session[1842]: GLib-GObject-CRITICAL: t+0.12455s: object CsmAutostartApp 0x9640098 finalized while still in-construction
cinnamon-session[1842]: GLib-GObject-CRITICAL: t+0.12469s: Custom constructor for class CsmAutostartApp returned NULL (which is invalid). Please use GInitable instead.
cinnamon-session[1842]: WARNING: t+0.12485s: could not read /home/doug/.config/autostart/indicator-remindor.desktop
GNOME_KEYRING_CONTROL=/run/user/1000/keyring-uv9y82
GNOME_KEYRING_PID=3033
GNOME_KEYRING_CONTROL=/run/user/1000/keyring-uv9y82
GPG_AGENT_INFO=/run/user/1000/keyring-uv9y82/gpg:0:1
GNOME_KEYRING_CONTROL=/run/user/1000/keyring-uv9y82
GPG_AGENT_INFO=/run/user/1000/keyring-uv9y82/gpg:0:1
GNOME_KEYRING_CONTROL=/run/user/1000/keyring-uv9y82
GPG_AGENT_INFO=/run/user/1000/keyring-uv9y82/gpg:0:1
SSH_AUTH_SOCK=/run/user/1000/keyring-uv9y82/ssh
=== xinerama setup Configuration ===
  Clone: false
  Output: Laptop attached to LVDS1
     status: on
     width: 1366
     height: 768
     rate: 60
     primary: true
     position: 0 0
  Output: (null) attached to VGA1
     status: off
     width: -1
     height: -1
     rate: -1
     primary: false
     position: -1 -1
  Output: (null) attached to HDMI1
     status: off
     width: -1
     height: -1
     rate: -1
     primary: false
     position: -1 -1
  Output: (null) attached to DP1
     status: off
     width: -1
     height: -1
     rate: -1
     primary: false
     position: -1 -1
  Output: (null) attached to VIRTUAL1
     status: off
     width: -1
     height: -1
     rate: -1
     primary: false
     position: -1 -1
=== Applying Configuration Configuration ===
  Clone: false
  Output: Laptop attached to LVDS1
     status: on
     width: 1366
     height: 768
     rate: 60
     primary: true
     position: 0 0
  Output: (null) attached to VGA1
     status: off
     width: -1
     height: -1
     rate: -1
     primary: false
     position: -1 -1
  Output: (null) attached to HDMI1
     status: off
     width: -1
     height: -1
     rate: -1
     primary: false
     position: -1 -1
  Output: (null) attached to DP1
     status: off
     width: -1
     height: -1
     rate: -1
     primary: false
     position: -1 -1
  Output: (null) attached to VIRTUAL1
     status: off
     width: -1
     height: -1
     rate: -1
     primary: false
     position: -1 -1

(gnome-terminal:3227): GLib-GIO-CRITICAL **: g_settings_get: the format string may not contain '&' (key 'monospace-font-name' from schema 'org.gnome.desktop.interface'). This call will probably stop working with a future version of glib.
/usr/lib/python2.7/dist-packages/deluge/ui/gtkui/gtkui.py:180: Warning: Attempt to add property GnomeProgram::sm-connect after class was initialised
  self.gnome_prog = gnome.init("Deluge", deluge.common.get_version())
/usr/lib/python2.7/dist-packages/deluge/ui/gtkui/gtkui.py:180: Warning: Attempt to add property GnomeProgram::show-crash-dialog after class was initialised
  self.gnome_prog = gnome.init("Deluge", deluge.common.get_version())
/usr/lib/python2.7/dist-packages/deluge/ui/gtkui/gtkui.py:180: Warning: Attempt to add property GnomeProgram::display after class was initialised
  self.gnome_prog = gnome.init("Deluge", deluge.common.get_version())
/usr/lib/python2.7/dist-packages/deluge/ui/gtkui/gtkui.py:180: Warning: Attempt to add property GnomeProgram::default-icon after class was initialised
  self.gnome_prog = gnome.init("Deluge", deluge.common.get_version())
nm-applet-Message: using fallback from indicator to GtkStatusIcon

** (nemo:3235): WARNING **: Can not determine workarea, guessing at layout
Cjs-Message: JS LOG: About to start Cinnamon
St-Message: cogl npot texture sizes SUPPORTED
Cjs-Message: JS LOG: Cinnamon started at Fri Dec 11 2015 11:10:23 GMT+0800 (PHT)
mintUpdate: no process found

(mintUpdate.py:4375): libglade-WARNING **: unknown attribute `swapped' for <signal>.

(mintUpdate.py:4375): libglade-WARNING **: unknown attribute `swapped' for <signal>.

(mintUpdate.py:4375): libglade-WARNING **: unknown attribute `swapped' for <signal>.

(mintUpdate.py:4375): libglade-WARNING **: unknown attribute `swapped' for <signal>.
Cjs-Message: JS LOG: network applet: Cannot find connection for active (or connection cannot be read)
[1449803435] [ERR] hddtemp: failed to open connection.
[1449803435] [ERR] Failed to retrieve NVIDIA information.
nm-applet-Message: moving back from GtkStatusIcon to indicator
failed to create drawable
getrlimit(RLIMIT_NOFILE) failed
Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x2800001 (My Anonamo)
getrlimit(RLIMIT_NOFILE) failed
/usr/lib/linuxmint/mintUpdate/mintUpdate.py:2536: GtkWarning: IA__gdk_window_thaw_toplevel_updates_libgtk_only: assertion 'private->update_and_descendants_freeze_count > 0' failed
  gtk.main()
Cjs-Message: JS LOG: network applet: Found connection for active
[3238:3509:1211/111113:ERROR:ssl_client_socket_openssl.cc(1056)] handshake failed; returned -1, SSL error code 1, net_error -101
[3238:3509:1211/111114:ERROR:ssl_client_socket_openssl.cc(1056)] handshake failed; returned -1, SSL error code 1, net_error -101
[3238:3509:1211/111117:ERROR:ssl_client_socket_openssl.cc(1056)] handshake failed; returned -1, SSL error code 1, net_error -101
getrlimit(RLIMIT_NOFILE) failed
getrlimit(RLIMIT_NOFILE) failed
getrlimit(RLIMIT_NOFILE) failed
Window manager warning: nm-applet-Message: using fallback from indicator to GtkStatusIcon
Panel leaving: a new panel shell is starting.

(gnome-panel:9892): EggSMClient-CRITICAL **: egg_sm_client_set_mode: assertion 'global_client == NULL || global_client_mode == EGG_SM_CLIENT_MODE_DISABLED' failed

(gnome-panel:9892): Gtk-WARNING **: no parent (nil) is not realized but child GtkPlug 0xa0b4190 is realized

(gnome-panel:9892): Gtk-WARNING **: no parent (nil) is not realized but child GtkPlug 0xa0b4308 is realized

(gnome-panel:9892): Gtk-WARNING **: no parent (nil) is not realized but child GtkPlug 0xa0b4480 is realized
Cjs-Message: JS LOG: About to start Cinnamon
St-Message: cogl npot texture sizes SUPPORTED
Cjs-Message: JS LOG: Cinnamon started at Fri Dec 11 2015 11:14:40 GMT+0800 (PHT)
Cjs-Message: JS LOG: network applet: Cannot find connection for active (or connection cannot be read)
nm-applet-Message: moving back from GtkStatusIcon to indicator
Cjs-Message: JS LOG: network applet: Found connection for active
getrlimit(RLIMIT_NOFILE) failed
getrlimit(RLIMIT_NOFILE) failed
getrlimit(RLIMIT_NOFILE) failed

**Comment by dblaisde** [comment]
Second crash. The first happened just after a clean boot with no user interaction. The second happened while I was typing this....(PS. This output is what's above plus the new crash, which happened only a few minutes after)


/etc/mdm/Xsession: Beginning session setup...
localuser:doug being added to access control list
Script for none started at run_im.
/etc/mdm/Xsession: 31: /etc/X11/Xsession.d/98vboxadd-xclient: /usr/bin/VBoxClient: not found
/etc/mdm/Xsession: 32: /etc/X11/Xsession.d/98vboxadd-xclient: /usr/bin/VBoxClient: not found
/etc/mdm/Xsession: 33: /etc/X11/Xsession.d/98vboxadd-xclient: /usr/bin/VBoxClient: not found
/etc/mdm/Xsession: 34: /etc/X11/Xsession.d/98vboxadd-xclient: /usr/bin/VBoxClient: not found
/etc/mdm/Xsession: 35: /etc/X11/Xsession.d/98vboxadd-xclient: /usr/bin/VBoxClient: not found
Script for none started at run_im.
cinnamon-session[1842]: WARNING: t+0.12422s: Could not parse desktop file /home/doug/.config/autostart/indicator-remindor.desktop: Key file does not start with a group
cinnamon-session[1842]: GLib-GObject-CRITICAL: t+0.12455s: object CsmAutostartApp 0x9640098 finalized while still in-construction
cinnamon-session[1842]: GLib-GObject-CRITICAL: t+0.12469s: Custom constructor for class CsmAutostartApp returned NULL (which is invalid). Please use GInitable instead.
cinnamon-session[1842]: WARNING: t+0.12485s: could not read /home/doug/.config/autostart/indicator-remindor.desktop
GNOME_KEYRING_CONTROL=/run/user/1000/keyring-uv9y82
GNOME_KEYRING_PID=3033
GNOME_KEYRING_CONTROL=/run/user/1000/keyring-uv9y82
GPG_AGENT_INFO=/run/user/1000/keyring-uv9y82/gpg:0:1
GNOME_KEYRING_CONTROL=/run/user/1000/keyring-uv9y82
GPG_AGENT_INFO=/run/user/1000/keyring-uv9y82/gpg:0:1
GNOME_KEYRING_CONTROL=/run/user/1000/keyring-uv9y82
GPG_AGENT_INFO=/run/user/1000/keyring-uv9y82/gpg:0:1
SSH_AUTH_SOCK=/run/user/1000/keyring-uv9y82/ssh
=== xinerama setup Configuration ===
  Clone: false
  Output: Laptop attached to LVDS1
     status: on
     width: 1366
     height: 768
     rate: 60
     primary: true
     position: 0 0
  Output: (null) attached to VGA1
     status: off
     width: -1
     height: -1
     rate: -1
     primary: false
     position: -1 -1
  Output: (null) attached to HDMI1
     status: off
     width: -1
     height: -1
     rate: -1
     primary: false
     position: -1 -1
  Output: (null) attached to DP1
     status: off
     width: -1
     height: -1
     rate: -1
     primary: false
     position: -1 -1
  Output: (null) attached to VIRTUAL1
     status: off
     width: -1
     height: -1
     rate: -1
     primary: false
     position: -1 -1
=== Applying Configuration Configuration ===
  Clone: false
  Output: Laptop attached to LVDS1
     status: on
     width: 1366
     height: 768
     rate: 60
     primary: true
     position: 0 0
  Output: (null) attached to VGA1
     status: off
     width: -1
     height: -1
     rate: -1
     primary: false
     position: -1 -1
  Output: (null) attached to HDMI1
     status: off
     width: -1
     height: -1
     rate: -1
     primary: false
     position: -1 -1
  Output: (null) attached to DP1
     status: off
     width: -1
     height: -1
     rate: -1
     primary: false
     position: -1 -1
  Output: (null) attached to VIRTUAL1
     status: off
     width: -1
     height: -1
     rate: -1
     primary: false
     position: -1 -1

(gnome-terminal:3227): GLib-GIO-CRITICAL **: g_settings_get: the format string may not contain '&' (key 'monospace-font-name' from schema 'org.gnome.desktop.interface'). This call will probably stop working with a future version of glib.
/usr/lib/python2.7/dist-packages/deluge/ui/gtkui/gtkui.py:180: Warning: Attempt to add property GnomeProgram::sm-connect after class was initialised
  self.gnome_prog = gnome.init("Deluge", deluge.common.get_version())
/usr/lib/python2.7/dist-packages/deluge/ui/gtkui/gtkui.py:180: Warning: Attempt to add property GnomeProgram::show-crash-dialog after class was initialised
  self.gnome_prog = gnome.init("Deluge", deluge.common.get_version())
/usr/lib/python2.7/dist-packages/deluge/ui/gtkui/gtkui.py:180: Warning: Attempt to add property GnomeProgram::display after class was initialised
  self.gnome_prog = gnome.init("Deluge", deluge.common.get_version())
/usr/lib/python2.7/dist-packages/deluge/ui/gtkui/gtkui.py:180: Warning: Attempt to add property GnomeProgram::default-icon after class was initialised
  self.gnome_prog = gnome.init("Deluge", deluge.common.get_version())
nm-applet-Message: using fallback from indicator to GtkStatusIcon

** (nemo:3235): WARNING **: Can not determine workarea, guessing at layout
Cjs-Message: JS LOG: About to start Cinnamon
St-Message: cogl npot texture sizes SUPPORTED
Cjs-Message: JS LOG: Cinnamon started at Fri Dec 11 2015 11:10:23 GMT+0800 (PHT)
mintUpdate: no process found

(mintUpdate.py:4375): libglade-WARNING **: unknown attribute `swapped' for <signal>.

(mintUpdate.py:4375): libglade-WARNING **: unknown attribute `swapped' for <signal>.

(mintUpdate.py:4375): libglade-WARNING **: unknown attribute `swapped' for <signal>.

(mintUpdate.py:4375): libglade-WARNING **: unknown attribute `swapped' for <signal>.
Cjs-Message: JS LOG: network applet: Cannot find connection for active (or connection cannot be read)
[1449803435] [ERR] hddtemp: failed to open connection.
[1449803435] [ERR] Failed to retrieve NVIDIA information.
nm-applet-Message: moving back from GtkStatusIcon to indicator
failed to create drawable
getrlimit(RLIMIT_NOFILE) failed
Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x2800001 (My Anonamo)
getrlimit(RLIMIT_NOFILE) failed
/usr/lib/linuxmint/mintUpdate/mintUpdate.py:2536: GtkWarning: IA__gdk_window_thaw_toplevel_updates_libgtk_only: assertion 'private->update_and_descendants_freeze_count > 0' failed
  gtk.main()
Cjs-Message: JS LOG: network applet: Found connection for active
[3238:3509:1211/111113:ERROR:ssl_client_socket_openssl.cc(1056)] handshake failed; returned -1, SSL error code 1, net_error -101
[3238:3509:1211/111114:ERROR:ssl_client_socket_openssl.cc(1056)] handshake failed; returned -1, SSL error code 1, net_error -101
[3238:3509:1211/111117:ERROR:ssl_client_socket_openssl.cc(1056)] handshake failed; returned -1, SSL error code 1, net_error -101
getrlimit(RLIMIT_NOFILE) failed
getrlimit(RLIMIT_NOFILE) failed
getrlimit(RLIMIT_NOFILE) failed
Window manager warning: nm-applet-Message: using fallback from indicator to GtkStatusIcon
Panel leaving: a new panel shell is starting.

(gnome-panel:9892): EggSMClient-CRITICAL **: egg_sm_client_set_mode: assertion 'global_client == NULL || global_client_mode == EGG_SM_CLIENT_MODE_DISABLED' failed

(gnome-panel:9892): Gtk-WARNING **: no parent (nil) is not realized but child GtkPlug 0xa0b4190 is realized

(gnome-panel:9892): Gtk-WARNING **: no parent (nil) is not realized but child GtkPlug 0xa0b4308 is realized

(gnome-panel:9892): Gtk-WARNING **: no parent (nil) is not realized but child GtkPlug 0xa0b4480 is realized
Cjs-Message: JS LOG: About to start Cinnamon
St-Message: cogl npot texture sizes SUPPORTED
Cjs-Message: JS LOG: Cinnamon started at Fri Dec 11 2015 11:14:40 GMT+0800 (PHT)
Cjs-Message: JS LOG: network applet: Cannot find connection for active (or connection cannot be read)
nm-applet-Message: moving back from GtkStatusIcon to indicator
Cjs-Message: JS LOG: network applet: Found connection for active
getrlimit(RLIMIT_NOFILE) failed
getrlimit(RLIMIT_NOFILE) failed
getrlimit(RLIMIT_NOFILE) failed
Window manager warning: Log level 6: /build/buildd/glib2.0-2.40.2/./glib/gmem.c:133: failed to allocate 2048 bytes
nm-applet-Message: using fallback from indicator to GtkStatusIcon
Panel leaving: a new panel shell is starting.

(gnome-panel:17405): EggSMClient-CRITICAL **: egg_sm_client_set_mode: assertion 'global_client == NULL || global_client_mode == EGG_SM_CLIENT_MODE_DISABLED' failed

(gnome-panel:17405): Gtk-WARNING **: no parent (nil) is not realized but child GtkPlug 0x9c21238 is realized

(gnome-panel:17405): Gtk-WARNING **: no parent (nil) is not realized but child GtkPlug 0x9c213b0 is realized

(gnome-panel:17405): Gtk-WARNING **: no parent (nil) is not realized but child GtkPlug 0x9c21528 is realized
Cjs-Message: JS LOG: About to start Cinnamon
St-Message: cogl npot texture sizes SUPPORTED
Cjs-Message: JS LOG: Cinnamon started at Fri Dec 11 2015 11:21:00 GMT+0800 (PHT)
Cjs-Message: JS LOG: network applet: Cannot find connection for active (or connection cannot be read)
nm-applet-Message: moving back from GtkStatusIcon to indicator
Cjs-Message: JS LOG: network applet: Found connection for active

**Comment by dblaisde** [comment]
Why was this bug closed? There was no reason that I could see. Should I be reporting this elsewhere???

**Comment by JosephMcc** [comment]
> Why was this bug closed? There was no reason that I could see. Should I be reporting this elsewhere???

You closed it yourself.

**Comment by dblaisde** [comment]
Ok, thanks.

**Comment by ManIVIctorious** [comment]
Is this still an issue for you with cinnamon 3.0?

**Comment by Vahan86** [comment]
@JosephMcc, can we close the issue?
