### ISSUE TITLE
Useless "Learn more" link in color system settings

### ISSUE THREAD

**Issue by Zero3** [linuxmint/Cinnamon#4929]
The link saying "Learn more" in the color system settings is pretty useless. It links to http://www.linuxmint.com/documentation.php, but neither that page, nor the user guide linked from it, contains any information about color profiles.

**Comment by leigh123linux** [comment]
This isn't a cinnamon issue so please close.

**Comment by RavetcoFX** [comment]
Please re-open in https://github.com/linuxmint/mintdoc

**Comment by Zero3** [comment]
@leigh123linux That's not a very constructive response. Since the "broken" link is located in the Cinnamon system settings, I fail to see how this is not a Cinnamon issue. Even if it is not, "please close" will not fix it.

@RavetcoFX I can do that, but are you sure this is a documentation issue? As I mentioned above, the link is located in the Cinnamon system settings. The other sections of the system settings do not appear to have links such as this one, and it doesn't even deep-link into the documentation, so one could argue that it should be removed instead. I don't know.

**Comment by ManIVIctorious** [comment]
Even when it isn't a documentation issue it would be one for cinnamon-settings and not for cinnamon itself

**Comment by JosephMcc** [comment]
I don't think most users understand the distinction between all the different packages that make up Cinnamon. A number of issues in this repo probably belong on others but for the most part it's fine.

**Comment by Zero3** [comment]
@ManIVIctorious Are you trying to say that this is not the correct repository for system settings issues? If so, please let me know where the right repository is. Since the system settings appear to be a central part of Cinnamon, this repository seemed like a good place to post the issue. I'll be more than happy to post this in the correct repository, but as @JosephMcc notes, it is not trivial to figure out which one is the correct one.

**Comment by ManIVIctorious** [comment]
Ah, sorry for my late respond, have missed this one...
I'd say the right place for this is [linuxmint/cinnamon-control-center](https://github.com/linuxmint/cinnamon-control-center)

**Comment by JosephMcc** [comment]
Just a reminder

> I don't think most users understand the distinction between all the different packages that make up Cinnamon. A number of issues in this repo probably belong on others but for the most part it's fine.

So it's ok here. It's mostly just nemo issues I would like to keep separated.

**Comment by clefebvre** [comment]
https://github.com/linuxmint/cinnamon-control-center/commit/c6a292985fa07d397216866cb1b078e371daa818
