### ISSUE TITLE
[Linux Mint 17.3, Cinnamon 2.8] Icons remain in the non-primary monitor

### ISSUE THREAD

**Issue by siemprepeligroso** [linuxmint/Cinnamon#4930]
When using more than one monitor setup, in case that the primary monitor is chosen to be the one on the right side, the icons remain on the non-primary monitor.

Suggestion: always migrate the icons to the primary monitor

**Comment by Vahan86** [comment]
@siemprepeligroso, is this stilll an issue for you in Cinnamon 3?

**Comment by Vahan86** [comment]
@JosephMcc, can we close this issue?
