### ISSUE TITLE
Bug: Mint 17.3 Ignores Inhibit Suspend Mode Signals Being Issued by Programs

### ISSUE THREAD

**Issue by RadicalRadish** [linuxmint/Cinnamon#4933]
System Details:
Linux Kernel 3.19.0-32-generic
Linux Mint 17.3 x64 Cinnamon - Rosa
Cinnamon 2.8.6
Nemo 2.8.6
Tixati 2.28

It seems there is a bug in Mint that prevents Tixati (peer-to-peer torrent program) from preventing the system going into Suspend Mode (the same bug might, of course, similarly affect other programs). For details of the bug please see the following thread on Tixati forums. It is all explained there with good evidence as to why this is Mint bug. http://forum.tixati.com/support/2091/?p=1#6605

Please could someone fix this.

**Comment by mtwebster** [comment]
https://github.com/linuxmint/cinnamon-settings-daemon/commit/103c33de6bf4f4df0b2144e908693bf4d67d66c9

**Comment by mtwebster** [comment]
also, https://github.com/linuxmint/Cinnamon/commit/94e57196e180b92fe116ec46bd482893c4aed047
