### ISSUE TITLE
[Feature Request] Showing Date & Time with two lines on the Panel

### ISSUE THREAD

**Issue by dirent1** [linuxmint/Cinnamon#4935]
Hello,
Greetings from Turkey.
As a new user of Cinnamon, if possible, I would like to see date and time information with two lines on the panel, like this:
http://s24.postimg.org/afv5fkahd/image.jpg
Regards,

**Comment by dirent1** [comment]
Hello again,
The solution:
1- Go to:
 /home/user_name/.cinnamon/configs/calendar@cinnamon.org folder
2- Open the .json file
3- At custom-format section, change the value to:
 "%e.%b.%a \n  %H:%M:%S" 
or 
"  %H:%M:%S \n%e.%b.%a" 
(inclued double-quotes)
which you want to prefer.

**Comment by repsac-by** [comment]
Without having to edit the file, you can copy/paste the newline character.

**Comment by solarjoe** [comment]
> Without having to edit the file, you can copy/paste the newline character.

Just in case you are wondering what the newline character is in that case (like I did), it is `%n` (see [here](
https://www.foragoodstrftime.com/#reference)).
