### ISSUE TITLE
Desktop icons disappear when font sizes are changed

### ISSUE THREAD

**Issue by RogerAraujo** [linuxmint/Cinnamon#4936]
Hi,
I've just installed Linux Mint 17.3 Cinnamon, and I noticed that if I change the size of any global font under System Settings, the "Computer" and "Home" icons disappear from my desktop. Also, if I right-click the desktop after the icons have disappeared, nothing happens. I found a workaround: if I open a new Nemo window, the icons reappear where they should, and the desktop responds to right-clicks correctly.

**Comment by JosephMcc** [comment]
That means Nemo probably crashed. It controls the desktop icons and context menu. That's why when you open a new nemo window everything starts to work again.

**Comment by RogerAraujo** [comment]
I see. Apart from submitting a patch, is there anything I could do to help isolate or fix this bug?

**Comment by Vahan86** [comment]
@RogerAraujo, does this issue still happen in Cinnamon 3.0?

**Comment by JosephMcc** [comment]
This really belongs here: https://github.com/linuxmint/nemo/issues
