### ISSUE TITLE
[Feature Request] Show Display settings when a new monitor is attached

### ISSUE THREAD

**Issue by rogeraraujo** [linuxmint/cinnamon#4937]
Hi,
I'd like to suggest a feature: it would be nice if the Display settings got shown when a new monitor is attached to the system. This feature is present in Linux Mint Xfce.

**Comment by ManIVIctorious** [comment]
That would be really useful

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
