### ISSUE TITLE
Indent battery status in power applet

### ISSUE THREAD

**Issue by philipzae** [linuxmint/cinnamon#4939]
Indenting the battery status line of each battery source will make it look better.

![cinnamon_power](https://cloud.githubusercontent.com/assets/4412114/11814791/208f3fa6-a362-11e5-91fd-375d16c3cddb.png)

On a side note, the mouse icon isnt aligned similar to the other battery icons.

![icon alignment](https://cloud.githubusercontent.com/assets/4412114/11814933/dc9f23d2-a362-11e5-8916-8e1e3fd66bdb.png)

**Comment by philipzae** [comment]
Forgot to also mention that right aligning the charge percentage would make it easier to look through the list.

**Comment by fahmed24** [comment]
I was able to indent the battery status but I did not right align the charge percentage.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
