### ISSUE TITLE
Icons for mute toggles in sound applet context menu

### ISSUE THREAD

**Issue by philipzae** [linuxmint/Cinnamon#4940]
It would be nice if the two mute toggle lines had icons to the left of their labels.

![cinnamon_sound2](https://cloud.githubusercontent.com/assets/4412114/11815867/389b63b8-a367-11e5-9a4c-b756a40ef734.png)

If this is accepted, then it would be good to move 'Applications' and 'Output device' labels to the right so that all text aligns together.

![cinnamon_sound2](https://cloud.githubusercontent.com/assets/4412114/11816001/dd09a018-a367-11e5-8053-e38e871a8ea1.png)

**Comment by NikoKrause** [comment]
@philipzae 
The icons were added to the sound-applet.
I'm not sure about the text alignment though.
Other applets don't align. 
Do you consider your feature request to be solved, or do you want it still to be open, because of the alignment?

**Comment by philipzae** [comment]
@NikoKrause
Glad to hear that the icons were added. About the alignment, its up to the cinnamon design team to decide if they want to do the alignment or not, so please ask them.
