### ISSUE TITLE
Can't use "Escape" within a keyboard shortcut

### ISSUE THREAD

**Issue by telmotrooper** [linuxmint/Cinnamon#4941]
Since the last update of Cinnamon with Mint 17.3 I can't use "Escape" in my keyboard shortcuts anymore. I always define a custom shortcut for the system monitor as "Ctrl+Shift+Escape" but on 2.8.6 Escape has the function of canceling the operation so I can't use within the shortcut any more.

**Comment by mtwebster** [comment]
I can't reproduce this - can you run `cinnamon-settings keyboard` from a terminal and tell me if you get any errors when trying to do this?

**Comment by telmotrooper** [comment]
Just opened the dialog, tried setting the shortcut, it didn't work and I closed the dialog.
> [telmo@Telmo-LT ~]$ cinnamon-settings keyboard
> Python module
> Could not find bluetooth module; is the cinnamon-control-center package installed?
> Loading Keyboard module
> __init__ took 473.025 ms
> /usr/lib/python2.7/site-packages/gi/overrides/GObject.py:541: Warning: gsignal.c:2634: instance '0x55b3ca50cb80' has no handler with id '2460'
>   return func(*args, **kwargs)
It's important to point out that I'm using Cinnamon 2.8.6 over Antergos, but I've asked a friend to reproduce the issue on MInt 17.3 and the same thing happened. The problem is that "Escape" is the key to "cancel the operation", so since 2.8.6 it can't be used within a shortcut.

**Comment by mtwebster** [comment]
I can't reproduce on either mint 17 or Ubuntu 16.04 - I have no issue using escape in shortcuts (when paired with modifiers).

Can you do me a favor and pastebin the contents of the file: `/usr/share/cinnamon/cinnamon-settings/modules/cs_keyboard.py`

**Comment by telmotrooper** [comment]
Of course.
http://pastebin.com/2H1Vj46h

**Comment by Zerophase** [comment]
I'm having the same issue. Been trying to press the key combination really fast, to see if it will stick, no luck so far. Is there a command line work around for assigning the shortcut?

**Comment by alok-sin** [comment]
Hi, even I am unable to bind Esc with any modifier on cinnamon. I am using Antergos with Cinnamon 2.8.6
The GUI has trouble assigning Escape key to bind a shortcut as Escape is also the key that cancels bindings.

Please let us know if there is an alternative to this.

**Comment by keitalbame** [comment]
Also see this on Arch and Mint 17.3 (upgraded from 17.2), when replicating @telmotrooper actions.

Tooltip mentioning to use the Escape key to cancel the assigning operation.

![2016yyy55m03-08-16d09 55 02tooltip_001](https://cloud.githubusercontent.com/assets/16195977/13597535/6fd7884a-e519-11e5-8a05-91c979bc024f.png)

**Comment by Zerophase** [comment]
I don't know if it fixed it for everyone, but the recent updates to Cinnamon seem to have fixed the issue.

**Comment by keitalbame** [comment]
Yes, it is fixed for me too, both on Arch and Mint 17.3.
