### ISSUE TITLE
Tab and cursor keys do not work on login screen

### ISSUE THREAD

**Issue by ACinnamonUserInUK** [linuxmint/Cinnamon#4942]
. . or at least when using the 'GTK' ('No theme, just pure GTK') theme. It would useful if they could, thus allow one to use the keyboard, in a natural fashion, to change the user to be logged in.

Thanks for your time.

**Comment by JosephMcc** [comment]
This has nothing to do with Cinnamon. Please open an issue here: https://github.com/linuxmint/mdm
