### ISSUE TITLE
Middle click on a system tray icon should close it.

### ISSUE THREAD

**Issue by alextpedro** [linuxmint/Cinnamon#4943]
I would love this feature especially now that we have handy indicators. Indicators that have a large list of menu items take forever to open and aren't always the most stable. It'd be awesome to be able to middle click to close them, like we can with windows on the taskbar.

**Comment by lestcape** [comment]
Hi @alextpedro speaking of appindicator, there are an standard:
http://www.freedesktop.org/wiki/Specifications/StatusNotifierItem/StatusNotifierItem/

Please see the description of the SecondaryActivation (is currently not supported inside cinnamon). 

Whatever, this should not be set as an specific action (the dev of the application can do what he/she want when recive the action). Anyway, what could be added (better say, displayed) is the blacklist of appindicators, to be controlled by users and not in an internally way only. Anyway I'm against of an easy option to make a control of the blacklist. Maybe a hidden gsetting option instead.

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
