### ISSUE TITLE
All indicators are displayed on startup even if they are not supposed to be there

### ISSUE THREAD

**Issue by donlencho** [linuxmint/Cinnamon#4945]
For instance with Synapse or Gnome-Pie, you have an option not to show indicators in the status bar, but on start-up they are there. If you then go to respective settings, tick the box to show the indicator then untick it, they will disappear, but be back on next boot.
The behaviour is good with status icon and not indicators.
[Up to date Mint 17.3]

**Comment by lestcape** [comment]
@donlencho i can not reproduce what you say, but also i think is not possible currently, or the case is that you have an issue on gsettings. This condition restrict what occurs  https://github.com/linuxmint/Cinnamon/blob/master/js/ui/indicatorManager.js#L108

There are no way to watch for indicators if the gsetting value not let you to execute the indicator code. There are not a complex code here, is just a condition, so what you have aparently is another thing.

**Comment by donlencho** [comment]
OK, thank you for your reply. It's strange. But I don't really see the advantage of indicators for the moment so I will just disable them and avoid the problem that way. Thank you.
