### ISSUE TITLE
Insane input delay for Volume/Brightness controls after suspend and resume

### ISSUE THREAD

**Issue by thehans** [linuxmint/cinnamon#4947]
After suspending then resuming my laptop, attempting to change the volume from my buttons on the keyboard does not have any effect until about 30 minutes later.  The machine is completely responsive during this time, and I can change the volume by manipulating the "Sound" applet with my mouse pointer, but 30 minutes or so later I see the OSD popup and the volume finally changes from the previous button presses.

The brightness controls actually take effect immediately, but without displaying OSD popup. However, when the OSD comes up 30 minutes later, the brightness is manipulated a second time for the same button presses.

~~If I remove and re-add the Sound applet to the panel, it seems to gets rid of the issue, and all the queued up commands execute immediately after re-adding it.~~  This "fix" seems to have been a fluke which I can't reproduce any more.

Linux Mint 17.2 Rafaela
cinnamon-session 2.6.3+rafaela
Lenovo Thinkpad W510
NVIDIA Corporation GT216GLM [Quadro FX 880M](rev a2)
Nvidia driver 340.96

**Comment by WeNDoRx** [comment]
same problem on t420 with mint 17.3

**Comment by icarter09** [comment]
@thehans are you still experiencing this issue?

**Comment by thehans** [comment]
@icarter09 I have since gotten a newer laptop and am on latest 19.2 now, so I don't recall when I last experienced that issue.

**Comment by icarter09** [comment]
@thehans thanks for the update.

**Comment by ryleu** [comment]
I don’t believe this should be closed as it is still an issue:

![backlight delay](https://media.discordapp.net/attachments/958517233485746228/963418753457086474/IMG_5277.mov)
