### ISSUE TITLE
Cinnamon internal error

### ISSUE THREAD

**Issue by jezarate** [linuxmint/Cinnamon#4948]
I just installed LinuxMint 17,3 Cinnamon, updating my LinuxMint 17.2 that worked very good and when finished Cinnamon doesn't work anymore "Internal error has produced" and it is executing in debug mode. I installed Mate Desktop and works very good

I am working over this hardware: 

00:00.0 RAM memory: NVIDIA Corporation MCP61 Host Bridge (rev a1)
	Subsystem: Gigabyte Technology Co., Ltd Device 5001
00:01.0 ISA bridge: NVIDIA Corporation MCP61 LPC Bridge (rev a2)
	Subsystem: Gigabyte Technology Co., Ltd Device 0c11
00:01.1 SMBus: NVIDIA Corporation MCP61 SMBus (rev a2)
	Subsystem: Gigabyte Technology Co., Ltd Device 0c11
	Kernel driver in use: nForce2_smbus
00:01.2 RAM memory: NVIDIA Corporation MCP61 Memory Controller (rev a2)
	Subsystem: Gigabyte Technology Co., Ltd Device 0c11
00:02.0 USB controller: NVIDIA Corporation MCP61 USB 1.1 Controller (rev a3)
	Subsystem: Gigabyte Technology Co., Ltd Device 5004
	Kernel driver in use: ohci-pci
00:02.1 USB controller: NVIDIA Corporation MCP61 USB 2.0 Controller (rev a3)
	Subsystem: Gigabyte Technology Co., Ltd Device 5004
	Kernel driver in use: ehci-pci
00:04.0 PCI bridge: NVIDIA Corporation MCP61 PCI bridge (rev a1)
00:05.0 Audio device: NVIDIA Corporation MCP61 High Definition Audio (rev a2)
	Subsystem: Gigabyte Technology Co., Ltd Device a002
	Kernel driver in use: snd_hda_intel
00:07.0 Bridge: NVIDIA Corporation MCP61 Ethernet (rev a2)
	Subsystem: Gigabyte Technology Co., Ltd Device e000
	Kernel driver in use: forcedeth
00:08.0 IDE interface: NVIDIA Corporation MCP61 SATA Controller (rev a2)
	Subsystem: Gigabyte Technology Co., Ltd Device b002
	Kernel driver in use: sata_nv
00:08.1 IDE interface: NVIDIA Corporation MCP61 SATA Controller (rev a2)
	Subsystem: Gigabyte Technology Co., Ltd Device b002
	Kernel driver in use: sata_nv
00:0d.0 VGA compatible controller: NVIDIA Corporation C61 [GeForce 7025 / nForce 630a] (rev a2)
	Subsystem: Gigabyte Technology Co., Ltd Device d000
	Kernel driver in use: nvidia
00:18.0 Host bridge: Advanced Micro Devices, Inc. [AMD] Family 15h Processor Function 0
00:18.1 Host bridge: Advanced Micro Devices, Inc. [AMD] Family 15h Processor Function 1
00:18.2 Host bridge: Advanced Micro Devices, Inc. [AMD] Family 15h Processor Function 2
00:18.3 Host bridge: Advanced Micro Devices, Inc. [AMD] Family 15h Processor Function 3
	Kernel driver in use: k10temp
00:18.4 Host bridge: Advanced Micro Devices, Inc. [AMD] Family 15h Processor Function 4
	Kernel driver in use: fam15h_power
00:18.5 Host bridge: Advanced Micro Devices, Inc. [AMD] Family 15h Processor Function 5

Regards, this is my fisrt edition in this forum

**Comment by JosephMcc** [comment]
Not sure how relevant this is at this point. If it's still a problem it can always be re-opened.
