### ISSUE TITLE
wallpaper ?

### ISSUE THREAD

**Issue by ghost** [linuxmint/Cinnamon#4949]
i set the wallpaper but sometimes it goes back to the Gnome wallpaper is irritating i dont know what to find those to fix or what i did

.xsession-errors : http://paste.pound-python.org/show/U2KIQ3dEIQxbGEX19mHc/

what did i wrong i got also a dualscreen setup but technically i find it buggy
because right screen stays when i switch workspaces but is a happy feature on my side because i keep irc in on a eye.. got also manjaro linux dont know if its really a bug afterall ..

**Comment by ringo32** [comment]
hmm happends again, when gedit (gtk3) opened a config filen but its a symlink

**Comment by ManIVIctorious** [comment]
Duplicate of #3953
