### ISSUE TITLE
Steam chat window null title prevents window from being listed in window-list applet

### ISSUE THREAD

**Issue by itzexor** [linuxmint/Cinnamon#4950]
I have had a problem for a while where Steam chat windows will not appear in the window list most of the time. Today I noticed an error in .xsession-errors that coincides with this failure to appear:

`(cinnamon:11990): Cjs-WARNING **: JS ERROR: Error: Argument 'text' (type utf8) may not be null
WindowPreview.prototype._init@/usr/share/cinnamon/applets/window-list@cinnamon.org/applet.js:108
WindowPreview@/usr/share/cinnamon/applets/window-list@cinnamon.org/applet.js:77
AppMenuButton.prototype.onPreviewChanged@/usr/share/cinnamon/applets/window-list@cinnamon.org/applet.js:284
AppMenuButton.prototype._init@/usr/share/cinnamon/applets/window-list@cinnamon.org/applet.js:251
AppMenuButton@/usr/share/cinnamon/applets/window-list@cinnamon.org/applet.js:203
MyApplet.prototype._addWindow@/usr/share/cinnamon/applets/window-list@cinnamon.org/applet.js:1046
MyApplet.prototype._onWindowAdded@/usr/share/cinnamon/applets/window-list@cinnamon.org/applet.js:911`

I coded in a simple check to see if it is null and if so set the label to "null" instead and got the windows to appear in the window list every time. After doing this I noticed that the AppMenuButton displays the correct title, and tried to implement the same functionality in the WindowPreview prototype. I did manage to get it working reliabily, but I don't know a lot about applet coding or javascript in general so I'm going to post a diff here and hope someone more knowledgable can look into this. The attached diff is vs the latest commit on the window list applet [edf483e324ee1225065a6c2c219224c386d70bb2](https://github.com/linuxmint/Cinnamon/commit/edf483e324ee1225065a6c2c219224c386d70bb2).

[diff_edf483e324ee1225065a6c2c219224c386d70bb2.txt](https://github.com/linuxmint/Cinnamon/files/67694/diff_edf483e324ee1225065a6c2c219224c386d70bb2.txt)

Edit: This also fixes https://github.com/linuxmint/Cinnamon/issues/4879

**Comment by itzexor** [comment]
Here's an updated diff, I noticed a bug after running it for a while. I forgot to disconnect _updateCaptionId in _destroy and I removed the tooltip setting code because I don't think it is needed.

[diff2_edf483e324ee1225065a6c2c219224c386d70bb2.txt](https://github.com/linuxmint/Cinnamon/files/67749/diff2_edf483e324ee1225065a6c2c219224c386d70bb2.txt)

**Comment by kajzersoze** [comment]
Have this problem too, so annoying..

**Comment by kajzersoze** [comment]
@itzexor, your patch fixed the problem for me.

**Comment by JosephMcc** [comment]
For those of you that can, could you try the latest nightly builds or build cinnamon from git. This was just merged https://github.com/linuxmint/Cinnamon/commit/ded116d53631a2e8cd249cad7583328424ef8609
I think it will fix the issue that you're having since the window previews now get their title directly from the AppMenuButton. It should effectively be doing the same thing as the provided patch.

**Comment by itzexor** [comment]
This does not fix the issue. The initial call to get_title() on line 108 returns null and set_text() doesn't allow that. It needs to be checked for null rather than passed directly. Steam seems to have a delay before it sets that window property as subsequent calls to get_title() return the correct window title.

in .xsession-errors:

    (cinnamon:27423): Cjs-WARNING **: JS ERROR: Error: Argument 'text' (type utf8) may not be null
    WindowPreview.prototype._init@/usr/share/cinnamon/applets/window-list@cinnamon.org/applet.js:108
    WindowPreview@/usr/share/cinnamon/applets/window-list@cinnamon.org/applet.js:77
    AppMenuButton.prototype.onPreviewChanged@/usr/share/cinnamon/applets/window-list@cinnamon.org/applet.js:288
    AppMenuButton.prototype._init@/usr/share/cinnamon/applets/window-list@cinnamon.org/applet.js:255
    AppMenuButton@/usr/share/cinnamon/applets/window-list@cinnamon.org/applet.js:207
    MyApplet.prototype._addWindow@/usr/share/cinnamon/applets/window-list@cinnamon.org/applet.js:1060
    MyApplet.prototype._onWindowAdded@/usr/share/cinnamon/applets/window-list@cinnamon.org/applet.js:918

Since this does now update properly after the initial creation, we can just use a placeholder value intially, or not set it if that is allowed. Otherwise I suggest we at least copy over two lines from AppMenuButton to check for both possible null cases and set it to "?" if everything else fails.

    let title = this.metaWindow.get_title();
    if (!title) title = app ? app.get_name() : '?';
    this.label.set_text(title);

**Comment by JosephMcc** [comment]
@itzexor Thanks for taking the time to test and give feedback. Would you mind testing this to see if it works for you https://github.com/linuxmint/Cinnamon/pull/5022

**Comment by itzexor** [comment]
#5022 works just fine. Thanks for working on this, JosephMcc. I'm going to close this issue now as that fix seems to have been merged and I can't reproduce this issue anymore.

**Comment by JosephMcc** [comment]
@itzexor I appreciate the time and effort. I don't use steam so never would have known.

**Comment by kajzersoze** [comment]
I can also confirm that it works, thanks.

**Comment by Lukypie** [comment]
Hi. can I ask when the fix will come to the ubuntu 16.04 repo?
