### ISSUE TITLE
Multiple keyboard layouts. How do I set the default one ?

### ISSUE THREAD

**Issue by marco44** [linuxmint/Cinnamon#4951]
Hi,

I have 3 different layouts, as I need them depending on what I am doing… fr_bepo,fr, and us (declared in this order in Keyboard/Layout in Cinnamon 2.8, archlinux).

And at startup, I always get a us keyboard, while I was expecting fr_bepo. Is there a way to set up the default keyboard that should be applied at startup ?

Xorg's configuration is also set to use fr_bepo.

**Comment by NikoKrause** [comment]
@marco44 
Can you make a screenshot of your keyboard setting, like this:
![bildschirmfoto vom 2016-09-15 23-19-34](https://cloud.githubusercontent.com/assets/8415124/18567965/ee816ad6-7b9a-11e6-97e0-9194a669c90f.png)

**Comment by marco44** [comment]
Sorry, but it's been almost one year. I am by to Kde, which doesn't suffer from this.

Regards

**Comment by NikoKrause** [comment]
So this issue can be closed now?

**Comment by marco44** [comment]
I think so.
