### ISSUE TITLE
Crash that results in fallback mode. 

### ISSUE THREAD

**Issue by defnull** [linuxmint/Cinnamon#4952]
/var/log/syslog

```
Dec 20 21:17:32 nava kernel: [26154.260821] traps: cinnamon[3051] trap int3 ip:7f226bb9dc13 sp:7ffd84b52680 error:0
Dec 20 21:17:33 nava cinnamon-session[2476]: WARNING: Application 'cinnamon.desktop' killed by signal 15
Dec 20 21:17:34 nava cinnamon-session[2476]: WARNING: App 'cinnamon.desktop' respawning too quickly
Dec 20 21:17:34 nava cinnamon-session[2476]: CRITICAL: We failed, but the fail whale is dead. Sorry....
Dec 20 21:21:13 nava kernel: [26375.282048] traps: cinnamon[16114] trap int3 ip:7f93f4c70c13 sp:7fff2cf12b00 error:0
```

/var/log/Xorg.0.log

```
[ 15669.027] (II) XKB: reuse xkmfile /var/lib/xkb/server-873B3C386247E02A5BA52E0A618C87D485AC438E.xkm
...
[ 19581.598] (II) XKB: reuse xkmfile /var/lib/xkb/server-873B3C386247E02A5BA52E0A618C87D485AC438E.xkm
[ 22231.670] (II) XKB: reuse xkmfile /var/lib/xkb/server-873B3C386247E02A5BA52E0A618C87D485AC438E.xkm
[ 26141.535] (II) XKB: reuse xkmfile /var/lib/xkb/server-873B3C386247E02A5BA52E0A618C87D485AC438E.xkm
[ 26142.131] (II) fglrx(0): EDID vendor "BNQ", prod id 30887
[ 26142.131] (II) fglrx(0): Using hsync ranges from config file
[ 26142.131] (II) fglrx(0): Using vrefresh ranges from config file
[ 26142.131] (II) fglrx(0): Printing DDC gathered Modelines:
[ 26142.131] (II) fglrx(0): Modeline "1920x1080"x0.0  148.50  1920 2008 2052 2200  1080 1084 1089 1125 +hsync +vsync (67.5 kHz eP)
...
[ 26142.131] (II) fglrx(0): Modeline "1920x1080"x0.0   74.25  1920 2558 2602 2750  1080 1084 1089 1125 +hsync +vsync (27.0 kHz e)
[ 26142.396] (II) XKB: reuse xkmfile /var/lib/xkb/server-873B3C386247E02A5BA52E0A618C87D485AC438E.xkm
[ 26362.321] (II) XKB: reuse xkmfile /var/lib/xkb/server-873B3C386247E02A5BA52E0A618C87D485AC438E.xkm
... end ...
```

cinnamon --version

```
Cinnamon 2.6.13
```

fglrxinfo

```
display: :0  screen: 0
OpenGL vendor string: Advanced Micro Devices, Inc.
OpenGL renderer string: AMD Radeon R9 200 Series
OpenGL version string: 4.5.13416 Compatibility Profile Context 15.20.1013
```

Using an upgraded LinuxMint 17.2

**Comment by defnull** [comment]
Looks like `XKB: reuse xkmfile` and `traps: cinnamon[xxx] trap int3 ip:7f226bb9dc13 sp:xxx error:0` are correlated.

I also have lags when firefox is opening popups. The fade-in animation is in slow motion and the whole X process is very busy for several seconds, hogging one CPU core completely and ignoring any mouse/keyboard input.

**Comment by sdalbert** [comment]
I'm having the same problem using Cinnamon 2.8.6 on a fresh, first installation on an HP DV2000. Output from Xorg.0.log below. Syslog output is below that. Currently using NVIDIA's current supported driver.

[    36.954] (II) XKB: reuse xkmfile /var/lib/xkb/server-1908D3BB0224FA577B58A32F49D8B4107F7BAFFD.xkm
[    51.156] (II) NVIDIA(GPU-0): Display (Seiko/Epson (DFP-0)) does not support NVIDIA 3D
[    51.156] (II) NVIDIA(GPU-0):     Vision stereo.
[    51.156] (**) NVIDIA(0): Using HorizSync/VertRefresh ranges from the EDID for display
[    51.156] (**) NVIDIA(0):     device Seiko/Epson (DFP-0) (Using EDID frequencies has
[    51.156] (**) NVIDIA(0):     been enabled on all display devices.)
[   191.538] (II) XKB: reuse xkmfile /var/lib/xkb/server-1908D3BB0224FA577B58A32F49D8B4107F7BAFFD.xkm
[   303.780] (II) XKB: reuse xkmfile /var/lib/xkb/server-1908D3BB0224FA577B58A32F49D8B4107F7BAFFD.xkm
[   352.019] (II) XKB: reuse xkmfile /var/lib/xkb/server-1908D3BB0224FA577B58A32F49D8B4107F7BAFFD.xkm
[  1649.225] (II) NVIDIA(GPU-0): Display (Seiko/Epson (DFP-0)) does not support NVIDIA 3D
[  1649.225] (II) NVIDIA(GPU-0):     Vision stereo.
[  1649.225] (**) NVIDIA(0): Using HorizSync/VertRefresh ranges from the EDID for display
[  1649.225] (**) NVIDIA(0):     device Seiko/Epson (DFP-0) (Using EDID frequencies has
[  1649.225] (**) NVIDIA(0):     been enabled on all display devices.)
[  1649.399] (II) XKB: reuse xkmfile /var/lib/xkb/server-1908D3BB0224FA577B58A32F49D8B4107F7BAFFD.xkm

Jan  4 21:17:33 risa-hp kernel: [  303.431921] traps: cinnamon[2054] trap int3 ip:7f320bc95c13 sp:7ffea8ad5570 error:0

**Comment by Vahan86** [comment]
@defnull,is this still an issue for you in Cinnamon 3.0?

**Comment by defnull** [comment]
I have not seen this bug for a while now. Currently using Cinnamon 3.0.7.

**Comment by Vahan86** [comment]
@defnull, thanks for reply, in this case can you please close this issue?
