### ISSUE TITLE
Closing nemo makes desktop icons disappear

### ISSUE THREAD

**Issue by jmgomezpoveda** [linuxmint/Cinnamon#4954]
Many of the times that I close nemo (not always though), all the desktop icons disappear until I open another instance of nemo.

If I open nemo from the command line, there are some errors, but nemo runs normally. When I press the X to close nemo, the process keeps running in the command line. When I press CTRL+C, nemo finishes and the desktop icons disappear.

$ nemo
(nemo:2902): IBUS-WARNING **: Unable to connect to ibus: Could not connect: Connection refused
** (nemo:2902): WARNING **: Can not calculate _NET_NUMBER_OF_DESKTOPS
** (nemo:2902): WARNING **: Can not get _NET_WORKAREA
** (nemo:2902): WARNING **: Can not determine workarea, guessing at layout
^C

This happens as well when nemo is opened directly from its shortcut.

Using Cinnamon nightly.

**Comment by lestcape** [comment]
Hi, this is what is supposed to happen, as is nemo who control de desktop background. If nemo have a crash then all icons will disappear. What do you want instead? This behaviour is the same that have nautilus and other browsers...

**Comment by jmgomezpoveda** [comment]
Personally, I would prefer nemo not to crash in the first place.

**Comment by lestcape** [comment]
Yes, me too, nemo for this day has a lot of crashes. In my case i think is related with the session state.

**Comment by leigh123linux** [comment]
Well it's a nemo issue and should be reported here instead

https://github.com/linuxmint/nemo

**Comment by jmgomezpoveda** [comment]
My bad, I didn't know nemo was a separate project. It looks like this may be related to issue https://github.com/linuxmint/nemo/issues/1047 - I will close this ticket then.
