### ISSUE TITLE
File System Properties

### ISSUE THREAD

**Issue by cj0nes** [linuxmint/Cinnamon#4955]
Honestly, I have no idea if this is a Cinnamon issue or an Arch issue, so, sorry if I wasted your time.  When I right click File System and go to Properties, the "Contents" section reports that I have 140.7TB worth of items; it's only a 250GB drive that I have installed.

![filesystempropertiesdiscrepancy](https://cloud.githubusercontent.com/assets/13335711/11942694/ea0ef5b6-a7fd-11e5-852c-68baf34851f4.png)

**Comment by leigh123linux** [comment]
Well it's a nemo issue and should be reported here instead

https://github.com/linuxmint/nemo

I can also reproduce the issue on fedora.

**Comment by cj0nes** [comment]
Thanks, reported the issue on the nemo git.

Date: Tue, 22 Dec 2015 01:11:53 -0800
