### ISSUE TITLE
Scaling panel icon size while leaving text size unchanged

### ISSUE THREAD

**Issue by drewgendreau** [linuxmint/Cinnamon#4956]
Hi,

In the panel, is there a way to specify a scaling size for icons and text separately?  Or a way to specify these settings in a cinnamon.css file?  I know where/how to change the text size, but not the icon size.

Thanks,
Andrew

**Comment by repsac-by** [comment]
The icon size is hard coded in this function https://github.com/linuxmint/Cinnamon/blob/master/files/usr/share/cinnamon/applets/systray%40cinnamon.org/applet.js#L143

**Comment by JosephMcc** [comment]
@repsac-by that only affects the systray applet, not all applets on the panel.

**Comment by drewgendreau** [comment]
I was able to solve half my issue by poking around in the applets.  

I changed this
https://github.com/linuxmint/Cinnamon/blob/master/files/usr/share/cinnamon/applets/panel-launchers%40cinnamon.org/applet.js#L18

Which affected the pinned start icons on the panel, but did not affect the icons next to each running application or the menu icon.  Any ideas where I can find those settings?

Here is a picture of the icons I want to resize:

<a href="http://tinypic.com?ref=t5pptu" target="_blank"><img src="http://i67.tinypic.com/t5pptu.jpg" border="0" alt="Image and video hosting by TinyPic"></a>

(1) The Menu and Show Desktop icons on the left
(2) The icon next to each open application
(3) The "All Windows" icon at the far right

It doesn't show in the image, but I was able to scale up the applet icons, thanks to @repsac-by 

Thanks

**Comment by Vahan86** [comment]
https://github.com/linuxmint/Cinnamon/issues/3348#issuecomment-56457313
