### ISSUE TITLE
[Linux Mint 17.3, Cinnamon 2.8] Fullscreen cancels when using other screen

### ISSUE THREAD

**Issue by siemprepeligroso** [linuxmint/Cinnamon#4957]
In a multi monitor setup, when playing Adobe Flash video in fullscreen (within the browser) in the non-primary monitor, the video exits the fullscreen when pressing anything in the primary monitor.

Somehow the "plugin-container" can not survive clicks anywhere in the environment.

**Comment by JosephMcc** [comment]
I don't believe this is a Cinnamon issue but an issue with Flash since I've seen this exact same behaviour under other desktops environments.

**Comment by ManIVIctorious** [comment]
Since I haven't installed falsh I can't try that, but viewing a youtube video on second monitor in full screen mode is possible while I am typing this message -> I am pretty sure this is no cinnamon issue.

**Comment by JosephMcc** [comment]
This is an issue with flash. On Youtube for example you can eliminate this behavior by switching to the html5 player.
