### ISSUE TITLE
[Linux Mint 17.3, Cinnamon 2.8] All of the applications are placed to the first workspace when disconnecting monitor

### ISSUE THREAD

**Issue by siemprepeligroso** [linuxmint/Cinnamon#4958]
In a multi-monitor setup (the laptop display, and another monitor) when the external monitor (which acts as primary) is disconnected all of the windows from all of the workspaces are moved to the first workspace.

I would understand if all the windows and tabs from the primary monitor are moved to the new primary monitor but still within the same workspace, but why move everything from all workspaces to one single workspace?

Important Related Setting: Workspaces --> Only use workspaces on primary monitor: toggle ON

**Comment by jean** [comment]
I'm not seeing this. Can the issue be closed?

System: Host: X250 Kernel: 3.19.0-32-generic x86_64 (64 bit)
Desktop: Cinnamon 2.8.8 Distro: Linux Mint 17.3 Rosa

**Comment by JosephMcc** [comment]
I'd like to get confirmation from the original OP before closing. If he/she doesn't respond I'll try to test it and confirm that it's now ok.

**Comment by Vahan86** [comment]
@JosephMcc, can we close this issue?
