### ISSUE TITLE
Windows preview X button

### ISSUE THREAD

**Issue by grenzor** [linuxmint/Cinnamon#4959]
There should be a close button where in the top right corner of the windows preview there is a close (x) button. This is a must for usability especially with multiple tabs when it comes.

**Comment by JosephMcc** [comment]
Feature requests are always welcome but I hardly see this as a "must". Especially since the preview disappears when you move the mouse out of the window list. Would make it a bit hard to hit an "x". Plus who says there is going to be support for multiple tabs?

**Comment by sprintcowboy** [comment]
You can middle click or three finger tap on the window list button to close the window in case you did not know.

**Comment by grenzor** [comment]
@JosephMcc - clem said he has plans for it so I assume it will be. Also, if you use Windows 7/8+ you can see how this would work. Very useful.

**Comment by Vahan86** [comment]
+1 for supporting multiple tabs.

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
