### ISSUE TITLE
mesa-vdpau-drivers package removes Cinnamon

### ISSUE THREAD

**Issue by muzena** [linuxmint/Cinnamon#4961]
When I try to install mesa-vdpau-drivers package to have video hardware acceleration on Radeon 5670 HD removes Cinnamon and other packages, on Linux mint 17.2 don't exist this problem.

**Comment by ManIVIctorious** [comment]
This is obviously a packaging issue and should be reported to your distributions packager.

**Comment by ManIVIctorious** [comment]
@JosephMcc I think this can be closed

**Comment by JosephMcc** [comment]
@muzena  You say it doesn't happen on Mint17.2 but you don't say where it is happening.

**Comment by muzena** [comment]
sudo apt-get install mesa-vdpau-drivers, removes cinnamon package, that was problem.
In Mint 18 there is no such problem, package is installed without problem.
