### ISSUE TITLE
Too many open windows leads to windows' icons overlapping applets on the right of the panel

### ISSUE THREAD

**Issue by BRKsays** [linuxmint/Cinnamon#4964]
If I open too many windows, say, by clicking New(Ctrl+N) in LibreOffice Calc, then eventually the windows' icons starts to overlap the applets on the right. The issue is not limited to LibreOffice Calc only though. I checked with opening multiple instances of Nemo too with the same outcome.

I'm using Linux Mint 17.3 "Rosa" Cinnamon 64-bit.

![screenshot from 2015-12-24 08 56 19](https://cloud.githubusercontent.com/assets/5929272/11988983/5532d644-aa1c-11e5-8823-5f1de079d3ff.png)

**Comment by gmiller001** [comment]
I am experiencing the same issue on multiple PCs.
Linux Mint 17.2 and 17.3 Cinnamon 64-bit.
![screenshot from 2016-01-06 11 42 58](https://cloud.githubusercontent.com/assets/16580127/12149709/d402864c-b46a-11e5-86e8-b8da50a8f011.png)

**Comment by Ocelot92** [comment]
I can confirm this too. Linux Mint 17.3 Cinnamon 64 bit.

**Comment by JosephMcc** [comment]
Duplicate #5042

**Comment by knabity** [comment]
JosephMcc 5042 was created after this in January, and was never resolved so this is not a duplicate.

**Comment by JosephMcc** [comment]
It's still a duplicate of the same issue. I don't care which came first. That doesn't really matter. Usually I will keep the one that seems to have the most pertinent info.

**Comment by TooHuman** [comment]
This is still a bug in Linux Mint 18.1 using Cinnamon 3.2.7
