### ISSUE TITLE
[Cinnamon 2.8.6-rosa] Semi-random 1 second freezes

### ISSUE THREAD

**Issue by Redsandro** [linuxmint/Cinnamon#4965]
Upgraded Linux Mint 17.2 to 17.3. Cinnamon now at **2.8.6+rosa** on my Lenovo Carbon X1 (first generation).

Now I have random 0.5 - 1.0 freezes of the screen. Every minute or so, so perhaps not so random. I have the feeling it's everywhere, though I've actively noticed it when typing in Chrome, working in Eclipse, when watching a movie, or when dragging windows. Note that this does not trigger the freeze, it seems to be random.

Cinnamon is always between 7% and 12% CPU usage (don't know if that's normal - I never took notice before), but during these freezes it's at 50% - 55%. I think that means it's maxed out because the CPU has two cores.

Nothing actually crashes, just freezes and unfreezes. There is no crash log.

What can I do to identify the cause of this? Is there something Cinnamon does every minute?

![image](https://cloud.githubusercontent.com/assets/1702193/11995079/a37a9e4e-aa4a-11e5-9226-1bceb352866b.png)

**Comment by Redsandro** [comment]
I remember that I had already upgraded my desktop before, and it has no problems. The most notable hardware difference - apart from pretty much everything - is perhaps the video card. The laptop has integrated Intel graphics. The desktop has nVidia graphics.

```
$ sudo lshw -c video
  *-display               
       description: VGA compatible controller
       product: 3rd Gen Core processor Graphics Controller
       vendor: Intel Corporation
       physical id: 2
       bus info: pci@0000:00:02.0
       version: 09
       width: 64 bits
       clock: 33MHz
       capabilities: msi pm vga_controller bus_master cap_list rom
       configuration: driver=i915 latency=0
       resources: irq:28 memory:f0000000-f03fffff memory:e0000000-efffffff ioport:4000(size=64)
```

**Comment by Vahan86** [comment]
@Redsandro, is this still an issue for you in Cinnamon 3.2?

**Comment by Redsandro** [comment]
I have since replaced my laptop with a different model, so I can't say definitively. But there has been no one who verified the issue since, so I'm guessing it's been a one-off.

Thanks for getting back to this.
