### ISSUE TITLE
[Archlinux, Cinnamon 2.8.6-1] Tray issues.

### ISSUE THREAD

**Issue by Mayurifag** [linuxmint/Cinnamon#4967]
Hello! Thanks for all job you guys doing here. Sorry for my English, it is not my native language.

I have some issues w/ my cinnamon since last updates. 
1) Guake issue. I have unticked «Show tray icon» there. However, after launching it's showed in tray. Tick-untick in guake resolves issue, but I dont want to do it every time.
2) Keepassx issue. I have it at autostart as well. After typing password to unlock my database I minimize it to tray. Well, «Show window» button of keepassx from tray doesn't work nice. It appears for a 0.1 second in windows list near my tray and... That's all. Nothing happens. I have to launch keepassx from menu.
3) Some programms like cutegram doesnt show their icon in tray, they have a little invisible place there. So annoying to see that!

Thanks for reply!

**Comment by lestcape** [comment]
Hi.
1- If  Guake don't export his indicator icon, there are no way to get it. So, is exported and probably they just change the state to passive, but currently the cinnamon appindicator show the indicators if is in the passive state.

2- I don't understand, but probably an app issue: https://github.com/dlech/Keebuntu. Apparently the icon is not supported in unity, so not have an appindicator yet.

3- Probably is needed a default icon when an indicator icon fail to be loaded. Anyway this also appear to be a problem with the application, not with the appindicator: https://github.com/Aseman-Land/Cutegram/issues/21

**Comment by Mayurifag** [comment]
1) Can you please tell me what have I do now? I installed guake from git, gonna see if it will change the situation
2) It's for keepass, not for keepassx.
3) So, i have to wait updates?

**Comment by lestcape** [comment]
1- You need to wait for a decision, if will be show the icon in the passive state or not, I think the properly way is not show the icon. This could be decided probably in 3.0. Read this: https://github.com/linuxmint/Cinnamon/issues/4702

3- You can install the last version from source if you know how.

**Comment by Mayurifag** [comment]
3 - i recently installed some appindicator packets, they probably solved the issue

**Comment by ion201** [comment]
Re: keepassx. Same issue?
https://www.reddit.com/r/linux4noobs/comments/3y6fol/keepassx_icon_in_the_tray_doesnt_work_properly/cyaxl9l

**Comment by Mayurifag** [comment]
OH MY GOD, @ion201 , it solved my problem.
Also, cutegram still is not showed properly sometimes in tray.

**Comment by ManuelSchneid3r** [comment]
This title is not saying anything about the issue. Please give a precise and concise description of the problem. Please think of the users that are searching the issue for the issue they want to report to not duplicate it and have to open all those issues with titles like "I have a problem".
