### ISSUE TITLE
Cinnamon Display Setting Overriding Nvidia Setting (xorg.conf)

### ISSUE THREAD

**Issue by sigsegv1005** [linuxmint/cinnamon#4971]
here xorg.log and xorg.conf
**xorg.log**
[    28.066] 
X.Org X Server 1.15.1
Release Date: 2014-04-13
[    28.066] X Protocol Version 11, Revision 0
[    28.066] Build Operating System: Linux 3.2.0-37-generic x86_64 Ubuntu
[    28.066] Current Operating System: Linux sigsegv 4.2.0-22-generic #27~14.04.1-Ubuntu SMP Fri Dec 18 10:57:53 UTC 2015 x86_64
[    28.066] Kernel command line: BOOT_IMAGE=/boot/vmlinuz-4.2.0-22-generic root=UUID=9ee0f11a-1fa1-4b12-bef4-bb88738eaf3c ro quiet splash vt.handoff=7
[    28.066] Build Date: 16 April 2014  01:36:29PM
[    28.066] xorg-server 2:1.15.1-0ubuntu2 (For technical support please see http://www.ubuntu.com/support) 
[    28.066] Current version of pixman: 0.30.2
[    28.066]    Before reporting problems, check http://wiki.x.org
    to make sure that you have the latest version.
[    28.066] Markers: (--) probed, (*_) from config file, (==) default setting,
    (++) from command line, (!!) notice, (II) informational,
    (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
[    28.066](==) Log file: "/var/log/Xorg.0.log", Time: Mon Dec 28 11:06:35 2015
[    28.066](==) Using config file: "/etc/X11/xorg.conf"
[    28.066](==) Using system config directory "/usr/share/X11/xorg.conf.d"  --- xorg.conf
[    28.067](==) ServerLayout "Layout0"
[    28.067](**) |-->Screen "Screen0" (0)
[    28.067](**) |   |-->Monitor "Monitor0"
[    28.067](**) |   |-->Device "Device0"
[    28.067](**) |-->Input Device "Keyboard0"
[    28.067](**) |-->Input Device "Mouse0"
[    28.067](**) Option "Xinerama" "0"
[    28.067](==) Automatically adding devices
[    28.067](==) Automatically enabling devices
[    28.067](==) Automatically adding GPU devices
[    28.067](WW) The directory "/usr/share/fonts/X11/cyrillic" does not exist.
[    28.067]    Entry deleted from font path.
[    28.078](==) FontPath set to:
    /usr/share/fonts/X11/misc,
    /usr/share/fonts/X11/100dpi/:unscaled,
    /usr/share/fonts/X11/75dpi/:unscaled,
    /usr/share/fonts/X11/Type1,
    /usr/share/fonts/X11/100dpi,
    /usr/share/fonts/X11/75dpi,
    built-ins
[    28.078](==) ModulePath set to "/usr/lib/x86_64-linux-gnu/xorg/extra-modules,/usr/lib/xorg/extra-modules,/usr/lib/xorg/modules"
[    28.078](WW) Hotplugging is on, devices using drivers 'kbd', 'mouse' or 'vmmouse' will be disabled.
[    28.078](WW) Disabling Keyboard0
[    28.078](WW) Disabling Mouse0
[    28.078](II) Loader magic: 0x5634c3e60d60
[    28.078](II) Module ABI versions:
[    28.078]    X.Org ANSI C Emulation: 0.4
[    28.078]    X.Org Video Driver: 15.0
[    28.078]    X.Org XInput driver : 20.0
[    28.078]    X.Org Server Extension : 8.0
[    28.078](II) xfree86: Adding drm device (/dev/dri/card0)
[    28.079](--) PCI:_(0:1:0:0) 10de:1180:1043:83f7 rev 161, Mem @ 0xf6000000/16777216, 0xe8000000/134217728, 0xf0000000/33554432, I/O @ 0x0000e000/128, BIOS @ 0x????????/524288
[    28.079] Initializing built-in extension Generic Event Extension
[    28.079] Initializing built-in extension SHAPE
[    28.079] Initializing built-in extension MIT-SHM
[    28.079] Initializing built-in extension XInputExtension
[    28.079] Initializing built-in extension XTEST
[    28.079] Initializing built-in extension BIG-REQUESTS
[    28.079] Initializing built-in extension SYNC
[    28.079] Initializing built-in extension XKEYBOARD
[    28.079] Initializing built-in extension XC-MISC
[    28.079] Initializing built-in extension SECURITY
[    28.079] Initializing built-in extension XINERAMA
[    28.079] Initializing built-in extension XFIXES
[    28.079] Initializing built-in extension RENDER
[    28.079] Initializing built-in extension RANDR
[    28.079] Initializing built-in extension COMPOSITE
[    28.079] Initializing built-in extension DAMAGE
[    28.079] Initializing built-in extension MIT-SCREEN-SAVER
[    28.079] Initializing built-in extension DOUBLE-BUFFER
[    28.079] Initializing built-in extension RECORD
[    28.079] Initializing built-in extension DPMS
[    28.079] Initializing built-in extension Present
[    28.079] Initializing built-in extension DRI3
[    28.079] Initializing built-in extension X-Resource
[    28.079] Initializing built-in extension XVideo
[    28.079] Initializing built-in extension XVideo-MotionCompensation
[    28.079] Initializing built-in extension SELinux
[    28.079] Initializing built-in extension XFree86-VidModeExtension
[    28.079] Initializing built-in extension XFree86-DGA
[    28.079] Initializing built-in extension XFree86-DRI
[    28.079] Initializing built-in extension DRI2
[    28.079](II) LoadModule: "glx"
[    28.088](II) Loading /usr/lib/xorg/modules/extensions/libglx.so
[    28.596](II) Module glx: vendor="NVIDIA Corporation"
[    28.596]    compiled for 4.0.2, module version = 1.0.0
[    28.596]    Module class: X.Org Server Extension
[    28.627](II) NVIDIA GLX Module  358.16  Mon Nov 16 18:54:01 PST 2015
[    28.653] Loading extension GLX
[    28.653](II) LoadModule: "nvidia"
[    28.654](II) Loading /usr/lib/xorg/modules/drivers/nvidia_drv.so
[    28.906](II) Module nvidia: vendor="NVIDIA Corporation"
[    28.906]    compiled for 4.0.2, module version = 1.0.0
[    28.906]    Module class: X.Org Video Driver
[    28.942](II) NVIDIA dlloader X Driver  358.16  Mon Nov 16 18:32:40 PST 2015
[    28.942](II) NVIDIA Unified Driver for all Supported NVIDIA GPUs
[    28.965](++) using VT number 8

[    28.977](II) Loading sub module "fb"
[    28.977](II) LoadModule: "fb"
[    28.977](II) Loading /usr/lib/xorg/modules/libfb.so
[    28.977](II) Module fb: vendor="X.Org Foundation"
[    28.977]    compiled for 1.15.1, module version = 1.0.0
[    28.977]    ABI class: X.Org ANSI C Emulation, version 0.4
[    28.977](II) Loading sub module "wfb"
[    28.977](II) LoadModule: "wfb"
[    28.977](II) Loading /usr/lib/xorg/modules/libwfb.so
[    28.977](II) Module wfb: vendor="X.Org Foundation"
[    28.977]    compiled for 1.15.1, module version = 1.0.0
[    28.977]    ABI class: X.Org ANSI C Emulation, version 0.4
[    28.977](II) Loading sub module "ramdac"
[    28.977](II) LoadModule: "ramdac"
[    28.977](II) Module "ramdac" already built-in
[    29.004](**) NVIDIA(0): Depth 24, (--) framebuffer bpp 32
[    29.004](==) NVIDIA(0): RGB weight 888
[    29.004](==) NVIDIA(0): Default visual is TrueColor
[    29.004](==) NVIDIA(0): Using gamma correction (1.0, 1.0, 1.0)
[    29.036](**) NVIDIA(0): Option "Stereo" "0"
[    29.036](**) NVIDIA(0): Option "nvidiaXineramaInfoOrder" "DFP-1"
[    29.036](**) NVIDIA(0): Option "SLI" "Off"
[    29.036](**) NVIDIA(0): Option "MultiGPU" "Off"
[    29.036](**) NVIDIA(0): Option "BaseMosaic" "off"
[    29.036](**) NVIDIA(0): Stereo disabled by request
[    29.036](**) NVIDIA(0): NVIDIA SLI disabled.
[    29.036](**) NVIDIA(0): NVIDIA Multi-GPU disabled.
[    29.036](**) NVIDIA(0): Option "MetaModes" "1920x1080_60_2 +0+0"
[    29.036](**) NVIDIA(0): Enabling 2D acceleration
[    29.858](--) NVIDIA(0): Valid display device(s) on GPU-0 at PCI:1:0:0
[    29.858](--) NVIDIA(0):     CRT-0
[    29.858](--) NVIDIA(0):     DFP-0
[    29.858](--) NVIDIA(0):     DFP-1 (boot)
[    29.858](--) NVIDIA(0):     DFP-2
[    29.858](--) NVIDIA(0):     DFP-3
[    29.858](--) NVIDIA(0):     DFP-4
[    29.861](--) NVIDIA(0): CRT-0: disconnected
[    29.861](--) NVIDIA(0): CRT-0: 400.0 MHz maximum pixel clock
[    29.861](--) NVIDIA(0): 
[    29.865](--) NVIDIA(0): DFP-0: disconnected
[    29.865](--) NVIDIA(0): DFP-0: Internal TMDS
[    29.865](--) NVIDIA(0): DFP-0: 330.0 MHz maximum pixel clock
[    29.865](--) NVIDIA(0): 
[    29.877](--) NVIDIA(0): LG Electronics M227WAP (DFP-1): connected
[    29.877](--) NVIDIA(0): LG Electronics M227WAP (DFP-1): Internal TMDS
[    29.877](--) NVIDIA(0): LG Electronics M227WAP (DFP-1): 340.0 MHz maximum pixel clock
[    29.877](--) NVIDIA(0): 
[    29.877](--) NVIDIA(0): DFP-2: disconnected
[    29.877](--) NVIDIA(0): DFP-2: Internal TMDS
[    29.877](--) NVIDIA(0): DFP-2: 165.0 MHz maximum pixel clock
[    29.877](--) NVIDIA(0): 
[    29.877](--) NVIDIA(0): DFP-3: disconnected
[    29.877](--) NVIDIA(0): DFP-3: Internal TMDS
[    29.877](--) NVIDIA(0): DFP-3: 330.0 MHz maximum pixel clock
[    29.877](--) NVIDIA(0): 
[    29.877](--) NVIDIA(0): DFP-4: disconnected
[    29.877](--) NVIDIA(0): DFP-4: Internal DisplayPort
[    29.877](--) NVIDIA(0): DFP-4: 960.0 MHz maximum pixel clock
[    29.877](--) NVIDIA(0): 
[    29.877](II) NVIDIA(GPU-0): Found DRM driver nvidia-drm (20150116)
[    29.878](II) NVIDIA(0): NVIDIA GPU GeForce GTX 680 (GK104) at PCI:1:0:0 (GPU-0)
[    29.878](--) NVIDIA(0): Memory: 2097152 kBytes
[    29.878](--) NVIDIA(0): VideoBIOS: 80.04.09.00.c3
[    29.878](II) NVIDIA(0): Detected PCI Express Link width: 16X
[    29.878](**) NVIDIA(0): Using HorizSync/VertRefresh ranges from the EDID for display
[    29.878](**) NVIDIA(0):     device LG Electronics M227WAP (DFP-1) (Using EDID
[    29.878](**) NVIDIA(0):     frequencies has been enabled on all display devices.)
[    29.880](II) NVIDIA(0): Validated MetaModes:
[    29.880](II) NVIDIA(0):     "1920x1080_60_2+0+0"
[    29.880](II) NVIDIA(0): Virtual screen size determined to be 1920 x 1080
[    29.884](--) NVIDIA(0): DPI set to (101, 101); computed from "UseEdidDpi" X config
[    29.884](--) NVIDIA(0):     option
[    29.884](--) Depth 24 pixmap format is 32 bpp
[    29.884](II) NVIDIA: Using 3072.00 MB of virtual memory for indirect memory
[    29.884](II) NVIDIA:     access.
[    30.004](II) NVIDIA(0): Setting mode "1920x1080_60_2+0+0"
[    30.052] Loading extension NV-GLX
[    30.058](==) NVIDIA(0): Disabling shared memory pixmaps
[    30.058](==) NVIDIA(0): Backing store enabled
[    30.058](==) NVIDIA(0): Silken mouse enabled
[    30.058](**) NVIDIA(0): DPMS enabled
[    30.058] Loading extension NV-CONTROL
[    30.058] Loading extension XINERAMA
[    30.058](II) Loading sub module "dri2"
[    30.058](II) LoadModule: "dri2"
[    30.058](II) Module "dri2" already built-in
[    30.058](II) NVIDIA(0): [DRI2] Setup complete
[    30.058](II) NVIDIA(0): [DRI2]   VDPAU driver: nvidia
[    30.058](--) RandR disabled
[    30.061](II) SELinux: Disabled on system
[    30.061](II) Initializing extension GLX
[    30.578](II) XKB: reuse xkmfile /var/lib/xkb/server-B20D7FC79C7F597315E3E501AEF10E0D866E8E92.xkm
[    30.579](II) config/udev: Adding input device Power Button (/dev/input/event1)
[    30.579](**) Power Button: Applying InputClass "evdev keyboard catchall"
[    30.579](II) LoadModule: "evdev"
[    30.580](II) Loading /usr/lib/xorg/modules/input/evdev_drv.so
[    30.608](II) Module evdev: vendor="X.Org Foundation"
[    30.608]    compiled for 1.15.0, module version = 2.8.2
[    30.608]    Module class: X.Org XInput Driver
[    30.609]    ABI class: X.Org XInput driver, version 20.0
[    30.609](II) Using input driver 'evdev' for 'Power Button'
[    30.609](**) Power Button: always reports core events
[    30.609](**) evdev: Power Button: Device: "/dev/input/event1"
[    30.609](--) evdev: Power Button: Vendor 0 Product 0x1
[    30.609](--) evdev: Power Button: Found keys
[    30.609](II) evdev: Power Button: Configuring as keyboard
[    30.609](**) Option "config_info" "udev:/sys/devices/LNXSYSTM:00/LNXPWRBN:00/input/input1/event1"
[    30.609](II) XINPUT: Adding extended input device "Power Button" (type: KEYBOARD, id 6)
[    30.609](**) Option "xkb_rules" "evdev"
[    30.609](**) Option "xkb_model" "pc105"
[    30.609](**) Option "xkb_layout" "us"
[    30.609](II) config/udev: Adding input device Power Button (/dev/input/event0)
[    30.609](**) Power Button: Applying InputClass "evdev keyboard catchall"
[    30.609](II) Using input driver 'evdev' for 'Power Button'
[    30.609](**) Power Button: always reports core events
[    30.609](**) evdev: Power Button: Device: "/dev/input/event0"
[    30.609](--) evdev: Power Button: Vendor 0 Product 0x1
[    30.609](--) evdev: Power Button: Found keys
[    30.609](II) evdev: Power Button: Configuring as keyboard
[    30.609](**) Option "config_info" "udev:/sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0C0C:00/input/input0/event0"
[    30.609](II) XINPUT: Adding extended input device "Power Button" (type: KEYBOARD, id 7)
[    30.609](**) Option "xkb_rules" "evdev"
[    30.609](**) Option "xkb_model" "pc105"
[    30.609](**) Option "xkb_layout" "us"
[    30.609](II) config/udev: Adding drm device (/dev/dri/card0)
[    30.609](II) config/udev: Ignoring already known drm device (/dev/dri/card0)
[    30.609](II) config/udev: Adding input device HDA NVidia HDMI/DP,pcm=3 (/dev/input/event15)
[    30.609](II) No input driver specified, ignoring this device.
[    30.609](II) This device may have been added with another device file.
[    30.609](II) config/udev: Adding input device HDA NVidia HDMI/DP,pcm=7 (/dev/input/event16)
[    30.609](II) No input driver specified, ignoring this device.
[    30.609](II) This device may have been added with another device file.
[    30.609](II) config/udev: Adding input device HDA NVidia HDMI/DP,pcm=8 (/dev/input/event17)
[    30.609](II) No input driver specified, ignoring this device.
[    30.609](II) This device may have been added with another device file.
[    30.609](II) config/udev: Adding input device HDA NVidia HDMI/DP,pcm=9 (/dev/input/event18)
[    30.609](II) No input driver specified, ignoring this device.
[    30.609](II) This device may have been added with another device file.
[    30.610](II) config/udev: Adding input device HDA Intel PCH Front Mic (/dev/input/event7)
[    30.610](II) No input driver specified, ignoring this device.
[    30.610](II) This device may have been added with another device file.
[    30.610](II) config/udev: Adding input device HDA Intel PCH Rear Mic (/dev/input/event8)
[    30.610](II) No input driver specified, ignoring this device.
[    30.610](II) This device may have been added with another device file.
[    30.610](II) config/udev: Adding input device HDA Intel PCH Line (/dev/input/event9)
[    30.610](II) No input driver specified, ignoring this device.
[    30.610](II) This device may have been added with another device file.
[    30.610](II) config/udev: Adding input device HDA Intel PCH Line Out Front (/dev/input/event10)
[    30.610](II) No input driver specified, ignoring this device.
[    30.610](II) This device may have been added with another device file.
[    30.610](II) config/udev: Adding input device HDA Intel PCH Line Out Surround (/dev/input/event11)
[    30.610](II) No input driver specified, ignoring this device.
[    30.610](II) This device may have been added with another device file.
[    30.610](II) config/udev: Adding input device HDA Intel PCH Line Out CLFE (/dev/input/event12)
[    30.610](II) No input driver specified, ignoring this device.
[    30.610](II) This device may have been added with another device file.
[    30.610](II) config/udev: Adding input device HDA Intel PCH Front Headphone (/dev/input/event13)
[    30.610](II) No input driver specified, ignoring this device.
[    30.610](II) This device may have been added with another device file.
[    30.610](II) config/udev: Adding input device USB Keyboard (/dev/input/event4)
[    30.610](**) USB Keyboard: Applying InputClass "evdev keyboard catchall"
[    30.610](II) Using input driver 'evdev' for 'USB Keyboard'
[    30.610](**) USB Keyboard: always reports core events
[    30.610](**) evdev: USB Keyboard: Device: "/dev/input/event4"
[    30.610](--) evdev: USB Keyboard: Vendor 0x4d9 Product 0x120
[    30.610](--) evdev: USB Keyboard: Found keys
[    30.610](II) evdev: USB Keyboard: Configuring as keyboard
[    30.610](**) Option "config_info" "udev:/sys/devices/pci0000:00/0000:00:1d.0/usb6/6-1/6-1.6/6-1.6.1/6-1.6.1:1.0/0003:04D9:0120.0003/input/input7/event4"
[    30.610](II) XINPUT: Adding extended input device "USB Keyboard" (type: KEYBOARD, id 8)
[    30.610](**) Option "xkb_rules" "evdev"
[    30.610](**) Option "xkb_model" "pc105"
[    30.610](**) Option "xkb_layout" "us"
[    30.611](II) config/udev: Adding input device USB Keyboard (/dev/input/event5)
[    30.611](**) USB Keyboard: Applying InputClass "evdev keyboard catchall"
[    30.611](II) Using input driver 'evdev' for 'USB Keyboard'
[    30.611](**) USB Keyboard: always reports core events
[    30.611](**) evdev: USB Keyboard: Device: "/dev/input/event5"
[    30.611](--) evdev: USB Keyboard: Vendor 0x4d9 Product 0x120
[    30.611](--) evdev: USB Keyboard: Found keys
[    30.611](II) evdev: USB Keyboard: Configuring as keyboard
[    30.611](**) Option "config_info" "udev:/sys/devices/pci0000:00/0000:00:1d.0/usb6/6-1/6-1.6/6-1.6.1/6-1.6.1:1.2/0003:04D9:0120.0005/input/input8/event5"
[    30.611](II) XINPUT: Adding extended input device "USB Keyboard" (type: KEYBOARD, id 9)
[    30.611](**) Option "xkb_rules" "evdev"
[    30.611](**) Option "xkb_model" "pc105"
[    30.611](**) Option "xkb_layout" "us"
[    30.611](II) config/udev: Adding input device Sony PLAYSTATION(R)3 Controller (/dev/input/event6)
[    30.611](II) No input driver specified, ignoring this device.
[    30.611](II) This device may have been added with another device file.
[    30.611](II) config/udev: Adding input device Sony PLAYSTATION(R)3 Controller (/dev/input/js1)
[    30.611](II) No input driver specified, ignoring this device.
[    30.611](II) This device may have been added with another device file.
[    30.611](II) config/udev: Adding input device A4TECH USB Device (/dev/input/event2)
[    30.611](**) A4TECH USB Device: Applying InputClass "evdev keyboard catchall"
[    30.611](II) Using input driver 'evdev' for 'A4TECH USB Device'
[    30.611](**) A4TECH USB Device: always reports core events
[    30.611](**) evdev: A4TECH USB Device: Device: "/dev/input/event2"
[    30.611](II) evdev: A4TECH USB Device: Using mtdev for this device
[    30.611](--) evdev: A4TECH USB Device: Vendor 0x9da Product 0x9066
[    30.611](--) evdev: A4TECH USB Device: Found 1 mouse buttons
[    30.611](--) evdev: A4TECH USB Device: Found scroll wheel(s)
[    30.611](--) evdev: A4TECH USB Device: Found relative axes
[    30.611](--) evdev: A4TECH USB Device: Found absolute axes
[    30.611](--) evdev: A4TECH USB Device: Found absolute multitouch axes
[    30.611](--) evdev: A4TECH USB Device: Found x and y absolute axes
[    30.611](--) evdev: A4TECH USB Device: Found keys
[    30.611](II) evdev: A4TECH USB Device: Forcing relative x/y axes to exist.
[    30.611](II) evdev: A4TECH USB Device: Configuring as mouse
[    30.611](II) evdev: A4TECH USB Device: Configuring as keyboard
[    30.611](II) evdev: A4TECH USB Device: Adding scrollwheel support
[    30.611](**) evdev: A4TECH USB Device: YAxisMapping: buttons 4 and 5
[    30.611](**) evdev: A4TECH USB Device: EmulateWheelButton: 4, EmulateWheelInertia: 10, EmulateWheelTimeout: 200
[    30.611](**) Option "config_info" "udev:/sys/devices/pci0000:00/0000:00:1d.0/usb6/6-1/6-1.7/6-1.7:1.0/0003:09DA:9066.0001/input/input5/event2"
[    30.611](II) XINPUT: Adding extended input device "A4TECH USB Device" (type: KEYBOARD, id 10)
[    30.611](**) Option "xkb_rules" "evdev"
[    30.611](**) Option "xkb_model" "pc105"
[    30.611](**) Option "xkb_layout" "us"
[    30.611](II) evdev: A4TECH USB Device: initialized for relative axes.
[    30.612](WW) evdev: A4TECH USB Device: ignoring absolute axes.
[    30.612](**) A4TECH USB Device: (accel) keeping acceleration scheme 1
[    30.612](**) A4TECH USB Device: (accel) acceleration profile 0
[    30.612](**) A4TECH USB Device: (accel) acceleration factor: 2.000
[    30.612](**) A4TECH USB Device: (accel) acceleration threshold: 4
[    30.612](II) config/udev: Adding input device A4TECH USB Device (/dev/input/js0)
[    30.612](II) No input driver specified, ignoring this device.
[    30.612](II) This device may have been added with another device file.
[    30.612](II) config/udev: Adding input device A4TECH USB Device (/dev/input/event3)
[    30.612](**) A4TECH USB Device: Applying InputClass "evdev pointer catchall"
[    30.612](II) Using input driver 'evdev' for 'A4TECH USB Device'
[    30.612](**) A4TECH USB Device: always reports core events
[    30.612](**) evdev: A4TECH USB Device: Device: "/dev/input/event3"
[    30.668](--) evdev: A4TECH USB Device: Vendor 0x9da Product 0x9066
[    30.668](--) evdev: A4TECH USB Device: Found 20 mouse buttons
[    30.668](--) evdev: A4TECH USB Device: Found scroll wheel(s)
[    30.668](--) evdev: A4TECH USB Device: Found relative axes
[    30.668](--) evdev: A4TECH USB Device: Found x and y relative axes
[    30.668](II) evdev: A4TECH USB Device: Configuring as mouse
[    30.668](II) evdev: A4TECH USB Device: Adding scrollwheel support
[    30.668](**) evdev: A4TECH USB Device: YAxisMapping: buttons 4 and 5
[    30.668](**) evdev: A4TECH USB Device: EmulateWheelButton: 4, EmulateWheelInertia: 10, EmulateWheelTimeout: 200
[    30.668](**) Option "config_info" "udev:/sys/devices/pci0000:00/0000:00:1d.0/usb6/6-1/6-1.7/6-1.7:1.1/0003:09DA:9066.0002/input/input6/event3"
[    30.668](II) XINPUT: Adding extended input device "A4TECH USB Device" (type: MOUSE, id 11)
[    30.668](II) evdev: A4TECH USB Device: initialized for relative axes.
[    30.668](**) A4TECH USB Device: (accel) keeping acceleration scheme 1
[    30.668](**) A4TECH USB Device: (accel) acceleration profile 0
[    30.668](**) A4TECH USB Device: (accel) acceleration factor: 2.000
[    30.668](**) A4TECH USB Device: (accel) acceleration threshold: 4
[    30.668](II) config/udev: Adding input device A4TECH USB Device (/dev/input/mouse0)
[    30.668](II) No input driver specified, ignoring this device.
[    30.668](II) This device may have been added with another device file.
[    30.668](II) config/udev: Adding input device Eee PC WMI hotkeys (/dev/input/event14)
[    30.668](**) Eee PC WMI hotkeys: Applying InputClass "evdev keyboard catchall"
[    30.668](II) Using input driver 'evdev' for 'Eee PC WMI hotkeys'
[    30.668](**) Eee PC WMI hotkeys: always reports core events
[    30.668](**) evdev: Eee PC WMI hotkeys: Device: "/dev/input/event14"
[    30.668](--) evdev: Eee PC WMI hotkeys: Vendor 0 Product 0
[    30.668](--) evdev: Eee PC WMI hotkeys: Found keys
[    30.668](II) evdev: Eee PC WMI hotkeys: Configuring as keyboard
[    30.668](**) Option "config_info" "udev:/sys/devices/platform/eeepc-wmi/input/input17/event14"
[    30.668](II) XINPUT: Adding extended input device "Eee PC WMI hotkeys" (type: KEYBOARD, id 12)
[    30.668](**) Option "xkb_rules" "evdev"
[    30.668](**) Option "xkb_model" "pc105"
[    30.668](**) Option "xkb_layout" "us"
[    44.002](--) NVIDIA(GPU-0): CRT-0: disconnected
[    44.002](--) NVIDIA(GPU-0): CRT-0: 400.0 MHz maximum pixel clock
[    44.002](--) NVIDIA(GPU-0): 
[    44.004](--) NVIDIA(GPU-0): DFP-0: disconnected
[    44.004](--) NVIDIA(GPU-0): DFP-0: Internal TMDS
[    44.004](--) NVIDIA(GPU-0): DFP-0: 330.0 MHz maximum pixel clock
[    44.004](--) NVIDIA(GPU-0): 
[    44.016](--) NVIDIA(GPU-0): LG Electronics M227WAP (DFP-1): connected
[    44.016](--) NVIDIA(GPU-0): LG Electronics M227WAP (DFP-1): Internal TMDS
[    44.016](--) NVIDIA(GPU-0): LG Electronics M227WAP (DFP-1): 340.0 MHz maximum pixel clock
[    44.016](--) NVIDIA(GPU-0): 
[    44.016](--) NVIDIA(GPU-0): DFP-2: disconnected
[    44.016](--) NVIDIA(GPU-0): DFP-2: Internal TMDS
[    44.016](--) NVIDIA(GPU-0): DFP-2: 165.0 MHz maximum pixel clock
[    44.016](--) NVIDIA(GPU-0): 
[    44.016](--) NVIDIA(GPU-0): DFP-3: disconnected
[    44.016](--) NVIDIA(GPU-0): DFP-3: Internal TMDS
[    44.016](--) NVIDIA(GPU-0): DFP-3: 330.0 MHz maximum pixel clock
[    44.016](--) NVIDIA(GPU-0): 
[    44.016](--) NVIDIA(GPU-0): DFP-4: disconnected
[    44.016](--) NVIDIA(GPU-0): DFP-4: Internal DisplayPort
[    44.016](--) NVIDIA(GPU-0): DFP-4: 960.0 MHz maximum pixel clock
[    44.016](--) NVIDIA(GPU-0): 
[    44.283](II) NVIDIA(0): Setting mode "HDMI-0: nvidia-auto-select @1920x1080 +0+0 {ViewPortIn=1920x1080, ViewPortOut=1920x1080+0+0}"   --overriding with 1080p @60hz
[    48.088](--) NVIDIA(GPU-0): CRT-0: disconnected
[    48.088](--) NVIDIA(GPU-0): CRT-0: 400.0 MHz maximum pixel clock
[    48.088](--) NVIDIA(GPU-0): 

xorg.conf
# nvidia-settings: X configuration file generated by nvidia-settings
# nvidia-settings:  version 358.16  (buildmeister@swio-display-x64-rhel04-12)  Mon Nov 16 19:58:01 PST 2015

Section "ServerLayout"
    Identifier     "Layout0"
    **Screen      0  "Screen0" 0 0**                     -- single monitor
    InputDevice    "Keyboard0" "CoreKeyboard"
    InputDevice    "Mouse0" "CorePointer"
    Option         "Xinerama" "0"
EndSection

Section "Files"
EndSection

Section "InputDevice"
    # generated from default
    Identifier     "Mouse0"
    Driver         "mouse"
    Option         "Protocol" "auto"
    Option         "Device" "/dev/psaux"
    Option         "Emulate3Buttons" "no"
    Option         "ZAxisMapping" "4 5"
EndSection

Section "InputDevice"
    # generated from default
    Identifier     "Keyboard0"
    Driver         "kbd"
EndSection

Section "Monitor"
    # HorizSync source: edid, VertRefresh source: edid
    Identifier     "Monitor0"
    VendorName     "Unknown"
    ModelName      "LG Electronics M227WAP"
    HorizSync       28.0 - 83.0
    VertRefresh     48.0 - 61.0
    Option         "DPMS"
EndSection

Section "Device"
    Identifier     "Device0"
    Driver         "nvidia"
    VendorName     "NVIDIA Corporation"
    BoardName      "GeForce GTX 680"
EndSection

Section "Screen"
    Identifier     "Screen0"
    Device         "Device0"
    Monitor        "Monitor0"
    DefaultDepth    24
    Option         "Stereo" "0"
    Option         "nvidiaXineramaInfoOrder" "DFP-1"
   *\* Option         "metamodes" "1920x1080_60_2 +0+0" *\*  ---telling to driver that we want 1080p @59.9hz
    Option         "SLI" "Off"
    Option         "MultiGPU" "Off"
    Option         "BaseMosaic" "off"
    SubSection     "Display"
       Depth       24
    EndSubSection
EndSection

**Comment by leigh123linux** [comment]
This is a picnic issue so please close

https://en.wiktionary.org/wiki/PICNIC

**Comment by sigsegv1005** [comment]
really ? 
http://forums.linuxmint.com/viewtopic.php?f=90&t=210878
https://www.reddit.com/r/linuxmint/comments/3ce881/cinnamon_resets_nvidia_x_server_settings/
https://bbs.archlinux.org/viewtopic.php?id=193949

**Comment by leigh123linux** [comment]
@sigsegv1005 

As you have difficultly understanding the issue I will explain it to you.
You can only use one display setting tool, if you use the nvidia driver you use nvidia-settings only.
Most nvidia settings are stored in xorg.conf which are loaded when starting the display manager (MDM, GDM, etc).
The cinnamon-settings display tool settings aren't run (if set) till the user logs into cinnamon session which will override anything in xorg.conf

**Comment by sigsegv1005** [comment]
yes. you're right about that but i think you missed my point. you said that we can only use one display setting tool. the problem is when aspect ratio or scaling and also refresh rate from cinnamon-settings display tool is different from nvidia-setting that stored in xorg.conf. there's no problem with mdm display resolution and refresh rate but after mdm sending messages to cinnamon to wake up then cinnamon will re-instantiate the display and overriding xorg.conf with its default setting or with "auto-select". therefore the display screen will be broken such as windows screen is bigger than monitor (vertical and horisontal) and also blurry and overshadowing text. in that case, our temporary solution is forcing the display resolution and refresh rate with xrandr and put that command in application startup.

**Comment by Vahan86** [comment]
@sigsegv1005, is this still an issue under Cinnamon 3.6?

**Comment by icarter09** [comment]
We believe this issue is fixed. Please test against the latest Cinnamon version (4.2). If the issue happens again, create a new issue and add the output of "cinnamon-settings sound".
