### ISSUE TITLE
Sometimes emblems show only after hitting refresh

### ISSUE THREAD

**Issue by ACinnamonUserInUK** [linuxmint/Cinnamon#4972]
Sometimes - or always? - when one adds an emblem to a previously emblemless icon, then, at least if the icon is on the desktop (as against displaying in a standard Nemo window), the emblem shows only after hitting refresh (F5). What should happen: the change should show immediately or almost immediately.

Linux Mint 17.3 x64 Cinnamon 2.8.6.

**Comment by JosephMcc** [comment]
This is a nemo issue. Please reopen it there.

**Comment by ACinnamonUserInUK** [comment]
JosephMcc: thanks, but I cannot find the Nemo bugtracker. *Please advise*, or this bug will go unreported. Thank you.

It seems to me that where one should report various problems one encounters when using Linux Mint could be a lot clearer than it is. Faced with this, many users who wish to file bug reports will simply give up and problems will go unfixed.

**Comment by JosephMcc** [comment]
Sorry. I post the link a lot of the time. I've seen you here regularly and just assumed you could find it: https://github.com/linuxmint/nemo

**Comment by ACinnamonUserInUK** [comment]
Ah. Thank you. I had found that page, but had come to think it was the wrong one.
