### ISSUE TITLE
Confirm dialog renders old content in application

### ISSUE THREAD

**Issue by bendovercz** [linuxmint/Cinnamon#4974]
Hello,
It looks like when you get confirm dialog in any application it takes some kind of snapshot of current content of application so it can be shown under the confirmation in grayscale (new behaviour since 2.8). But this snapshot shows outdated content most of the times (after showing dialog for the first time)

How to reproduce - it happens in every app that uses system confirm dialog
1. For example open terminal - then su (just because you will get confirm dialog when pressing Alt+F4)
2. Now cause a dialog confirmation - Alt+F4 - press Cancel
3. Now hit an enter few times or whatever you want - we just need to change content of your window so you can see the problem
4. Press Alt+F4 again and you will see terminal in background with content without changes you did in step 3.

I have tested this on multiple Mint installations with latest Cinnamon - all suffering this issue.

Is there any way to disable new confirm dialog behaviour?

**Comment by mtwebster** [comment]
Windows settings-> behavior-> uncheck "attach modal dialogs..."

**Comment by mtwebster** [comment]
btw, what graphics card/driver are you using?

I can't reproduce this in virtualbox mint 17.3

**Comment by bendovercz** [comment]
@mtwebster Its Intel HD. Unchecking helps. Will keep it that way temporarily. I will try it with nVidia in a few minutes and will report result.

**Comment by JosephMcc** [comment]
Not sure there is anything we can do about this if it's a limitation of the driver. We set that setting back to off by default since it causes issues in some other cases as well.
