### ISSUE TITLE
[Feature request] Export list of applications from start menu

### ISSUE THREAD

**Issue by ngabor7** [linuxmint/Cinnamon#4975]
I'm requesting a feature where it is possible to export the list of applications from the start menu into a text file or something like that. The button to do this can be put in the menu editor for example. This way people can create backups of the list of gui applications they installed and use it after reinstalling the os.

**Comment by Vahan86** [comment]
@JosephMcc, can we mark this issue as a feature request?

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
