### ISSUE TITLE
Panels don't get hidden when switching to a workspace with a fullscreen window

### ISSUE THREAD

**Issue by theSeppi** [linuxmint/Cinnamon#4977]
When I'm e.g. watching a film in fullscreen, and I'm doing something besides, most times I have the fullscreen window (Chrome, VLC, ...) open on one workspace, and do all other stuff of different workspaces. Sometimes, when switching back to the workspace with the fullscreen window, the panel still remains visible above.

**Steps to reproduce**  
1. Open a webbrowser, go to youtube, watch a video clip in fullscreen
2. Switch to another workspace (e.g. with hotkeys or hot corners)
3. Switch back to the previous workspace

**Expected behavior**  
The panel should be hidden once a workspace with a focused fullscreen window becomes active.

**Actual results**  
The panel remains visible after switching, even if the fullscreen window is focused.

**Reproducability**  
Only happens sometimes

**Comment by ticalc-travis** [comment]
I'm seeing this problem with full screen mpv in Cinnamon 2.8.8 (installed in Ubuntu 15.10 via PPA), but it's happening 100% reliably for me, not just sometimes. I have to toggle fullscreen mode to hide the panels every time I switch back. This is on a dual-display setup, in case that matters.

**Comment by ticalc-travis** [comment]
I just noticed another oddity to this glitch. Right now, when I switch workspaces to the full-screen menu on my primary monitor, the panel on that monitor does not hide as it should, but the panel on the secondary monitor (where the window is *not* displayed) *is* disappearing. Maybe it's related to multi-monitor support?

**Comment by JosephMcc** [comment]
Should be fixed by https://github.com/linuxmint/Cinnamon/pull/5229

**Comment by FlowXP** [comment]
for me Hot Corners are not working at all when youtube/smplayer/vlc/virtualbox is in full screen.
For ex. if youtube is in fullscreen and I move the mouse to the configured corner, nothing happens. In any other situation the hot corners are working fine.
In LM 17.1 this was working perfectly
