### ISSUE TITLE
applet release procedure is too permissive

### ISSUE THREAD

**Issue by hyOzd** [linuxmint/Cinnamon#4978]
I have just released my first applet via cinnamon-spices.linuxmint.com . Lack of https was the first thing surprised me but not as much as my applet being published and available for install _right away_.

It's nice that procedure has been lightning fast. But I'm worried that this can be used for malicious purposes. Someone uploads the '[UPDATED]' version of a popular applet...?

I was expecting at least a simple review making sure applet files doesn't contain a binary blob! Maybe a one time review per applet/author.

I understand if the rule is: "user has the responsibility to confirm the authenticity of the applet". But "Applets" dialog makes it too easy to install an applet and gives the indication that applets are coming from "Linux Mint" or at least they are approved by Linux Mint team. At least that was what I've been thinking until now. 

I think this situation should be clarified to user somehow, or some safe guards must be put in place.

**Comment by lestcape** [comment]
I think there are no such thing like that.. If you install a third party software, also if this come for a Mint repo, this is always a user decision and user need to take in account that the author of the applet is not Mint. Mint just provide a public repository, and in my opinion not need to be the Mint responsibility (free software is without warranty). Anyway what is more problematic is that: We don't need a binary or something to cause damage. We can cause damage using javascript as we can use gi. This is not like an html page. The only thing that i don't like about security, is the use of the user home folder to install extensions. This could to be placed in a restricted zone and always ask for credential to install an applet. In this way, the user will be alerted of what he is doing and will can avoid an "accidental" script execution.

**Comment by JosephMcc** [comment]
@hyOzd The issue with review/verification is that someone has to do it. The Mint developer team is small and mostly people doing the work in their free time.

**Comment by hyOzd** [comment]
> This could be placed in a restricted zone and always ask for credential to install an applet. In this way, the user will be alerted of what he is doing and will can avoid an "accidental" script execution.

Is there a reason that "adding a warning to applet installation dialog" isn't enough? I don't understand the need for installing on a different directory? Is it because another user can modify the home folder?

**Comment by lestcape** [comment]
@hyOzd  it's because you can create a silent extension, some one with the ability of not modify anything, but could have for example a timer to get all keyboard input and then send it to an specific internet receiver, then this extension can be copy into the extension folder without alert the user and then can be enable it without alert the user. When i say in a different folder, i say a folder with administrative privileges, in this way and like the user not have this right, the silent extension can not be copied to the extensions folder, so, cannot be activated without the required elevated credential.

**Comment by lestcape** [comment]
Finally, not request credential for install extension is the same security risk of not request credential to install the packages.

**Comment by anandrkris** [comment]
There seems to be some sort of warning shown for certain applets - not sure how this is derived just thought will point this out here
![applet_warning](https://cloud.githubusercontent.com/assets/4663298/19775538/5a2c4aa8-9c8e-11e6-8d6e-574fc6dcd67e.png)
And for https we have another report here
https://github.com/linuxmint/Cinnamon/issues/3789

**Comment by NikoKrause** [comment]
This can be closed now since spices are having a GitHub repository now.

@joseph
