### ISSUE TITLE
Power Applet not showing label text on laptop with more than one battery (suggested fix included)

### ISSUE THREAD

**Issue by razziel89** [linuxmint/cinnamon#4979]
On Linux Mint 17.3 running Cinnamon 2.8.6, I noticed that the power applet does not show any label text on my Lenovo T440s, which has two batteries. The only thing I get is some tooltip that's just a summary of the current state. Moreover, explicitly configuring the applet to show "percentage and time remaining" also did not show any label text. In earlier versions of Cinnamon (or rather the applet), the applet at least showed the state of one of the batteries.

I edited the JavaScript file and attached the result, which works for me. I would like to suggest to include the changes I made to that file in the next release. A short summary of the changes I made:
- always show information about all devices separated by " | " in the label and the tooltip
- fix a bug that caused some devices to be reported multiple times by the system (i.e. this._devices contained some devices more than once, devices are screened by their device_id)
- show time information only for the device that is currently in use (determined by comparing the time-to-full or time-to-empty reported by the system to the value at the last update of the label text)

It might need some further work to be a viable replacement for everybody since two numbers are hard-coded to work for my device. I would like to help with that but I am unsure about what to do exactly since some config-options might have to be added to the GUI. I attached a screenshot of the result.

[power_applet.txt](https://github.com/linuxmint/Cinnamon/files/76040/power_applet.txt)
![powerappletfix](https://cloud.githubusercontent.com/assets/10134766/12072418/7ba57f3a-b0dd-11e5-8ede-93287cb26b7a.png)

**Comment by luyikei** [comment]
Thank you for your suggestion. Did you create a pull request? If you did not, you should try to create one because developers can easily examine your suggestion or code. Making a pull request can be boring, but it is worth doing!

**Comment by razziel89** [comment]
I was kind of hoping to get in touch with the devs first to see whether any more changes should be made to the applet (I think there should be and I would not mind incorporating them, if possible) before its actually transferred anywhere. And since I have never created a pull request on Github, I was not sure whether I should create one for an applet that's not yet fully done. What is your advice? Thanks in advance!

**Comment by luyikei** [comment]
Now I understand your point. Why don't you join IRC: #linuxmint-dev on irc.spotchat.org to discuss your fix with the dev team?

**Comment by razziel89** [comment]
Right, will do when I find the time (sometime at the end of this week maybe). That's the same channel where people pointed me to the project's github page. Thanks again.

**Comment by luyikei** [comment]
Also, you should change the title into more feature-request-like one.

**Comment by lucascosti** [comment]
> On Linux Mint 17.3 running Cinnamon 2.8.6, I noticed that the power applet does not show any label text on my Lenovo T440s, which has two batteries. The only thing I get is some tooltip that's just a summary of the current state. Moreover, explicitly configuring the applet to show "percentage and time remaining" also did not show any label text. In earlier versions of Cinnamon (or rather the applet), the applet at least showed the state of one of the batteries.

+1 to this. I have a T440s on Fedora 23 with Cinnamon 3.0.7.

Previous versions used to be useful with the label when one of the batteries was discharging, but now it doesn't show any label at all.

**Comment by razziel89** [comment]
HI. I finally managed to get back to this. Could anyone please give me a very brief tutorial about how to create a pull request in this case? As I said the version is not perfectly final, yet, but since it works for my laptop it's probably worth a show. Thank you very much.

**Comment by lucascosti** [comment]
@razziel89 

Have a look at: https://help.github.com/articles/creating-a-pull-request/

But to summarize the workflow from the scratch:

1. Fork the Cinnamon project on GitHub.
2. In your fork, create a branch for the change.
3. Make the changes in your branch, and commit the changes.
4. Submit a pull request from your branch as in the link above.

Google should help you do each of the above steps. Thanks for the work in trying to get this fixed :).

**Comment by neonpixii** [comment]
This is still a problem for me; and it makes using cinnamon very annoying because i can't see where my battery is really at. any word of a fix?

**Comment by icarter09** [comment]
For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
