### ISSUE TITLE
Make the visibility of the tooltips of window list items configurable

### ISSUE THREAD

**Issue by mondalaci** [linuxmint/Cinnamon#4980]
I often drag my mouse pointer over the window list applet, so it's not in the way. In this case, I expect nothing extra to appear, but even if I disable window previews the tooltip containing the full name of the window appears.

I'd like an option to disable this tooltip, just like the window preview.

**Comment by JosephMcc** [comment]
Duplicate https://github.com/linuxmint/Cinnamon/issues/4267
