### ISSUE TITLE
alt-printscreen support missing

### ISSUE THREAD

**Issue by LiamDawe** [linuxmint/Cinnamon#4982]
Hi,

Love Cinnamon, but ALT+Printscreen is a really useful feature that just seems to be completely missing in Cinnamon. On all other desktops, it is used to capture just the active window, could we get this in?

On the default latest Linux Mint it doesn't seem to be in there.

**Comment by luyikei** [comment]
As far as I know, Cinnamon nightly builds can. However, they are intended for debugging purposes.

https://launchpad.net/~gwendal-lebihan-dev/+archive/ubuntu/cinnamon-nightly

**Comment by luyikei** [comment]
Sorry, it appears that at least the latest Linux Mint has the feature. If it does not work, it is because of a bug. Currently, if you alt-printscreen, the screenshot will be saved in your default picture folder.

http://www.shortcutworld.com/en/linux/Linux-Mint-Cinnamon-Edition_17.2.html

**Comment by NaughtySquid** [comment]
It flat out does nothing for me. I have of course checked my Picture folder, nothing happens.

**Comment by luyikei** [comment]
Can you take a screenshot just by printscreen?

**Comment by NaughtySquid** [comment]
Yes.

**Comment by luyikei** [comment]
Weird. This issue might be out of my hands, but I can tell you some possible causes.

1, Your alt-printscreen signal is not correctly received by Cinnamon/Muffin. In this case, you should be able to take a screenshot of a window by using another screenshot software like Shutter.

2, Your graphic driver has a problem. If so, you can't do what I suggested above.

3, You are trying to take a screenshot of a certain software that handles Alt-key. If so, you should be able to take a screenshot of software like Terminal, which is unlikely.

4, My misunderstanding.

5, Any other cause that I currently can't hit on.

If you have enough time to test what I suggested, please do it and tell the results here.

**Comment by mtwebster** [comment]
gnome-screenshot is broken.

All alt-printscreen does is run `gnome-screenshot --window`

If you run that from a terminal, you can see it crashes.  We're looking into why (and/or possibly coming up with a replacement for the next release)

There are a few Cinnamon applets that can take window shots successfully, though I'm not sure they can be bound by hotkeys.

**Comment by NaughtySquid** [comment]
I see, glad to see it's not just me then and that it is a known issue. I hope you guys can come up with something, as it's an incredibly useful thing.

**Comment by JosephMcc** [comment]
In the meantime you can try this: http://cinnamon-spices.linuxmint.com/applets/view/96
A fantastic applet for taking screenshots in Cinnamon. It even allows you to configure hotkeys for different screenshot types.

**Comment by NaughtySquid** [comment]
There's an issue with that applet.

When removed and uninstalled, in the same session it is still capturing the shortcut keys.

Also, when editing shortcut keys with it, it doesn't seem to always save your new ones, and reverts to the defaults.

**Comment by Vahan86** [comment]
It's working fine for me in Cinnamon 3.0?

@LiamDawe, is this still an issue for you in Cinnamon 3.0.x?

**Comment by Vahan86** [comment]
@JosephMcc, can we close the issue?
