### ISSUE TITLE
Unfocused windows don't trigger the 'demands attention' hint.

### ISSUE THREAD

**Issue by alextpedro** [linuxmint/Cinnamon#4983]
I have a dual monitor setup and usually I have Skype on the secondary monitor while I work on the primary. 

Whenever a skype chat window is unfocused and some part of it is behind another window (say another sky chat window or browser), it will flash and remain highlighted on the window-list applet. However, if the window is unobstructed and unfocused, it won't flash. 

I haven't been able to find any workarounds for this, but it's quite annoying as I don't always notice the text moving in my peripheral vision.

**Comment by JosephMcc** [comment]
So I just tried this with hexchat and it works as expected. With the window unfocused and unobstructed the window list applet still turns red. It makes me wonder if it's a setting in skype or a problem particular to skype. I don't currently have it installed to test.

**Comment by alextpedro** [comment]
I don't know. Since previously the issues with Skype flashing have all been a Cinnamon problem and Skype has pretty much abandoned its Linux users (no I can't change to another program) I figured it'd be easiest to see if something can be done on Cinnamon's side. The issues I mentioned:
[Skype taskbar flashing then stopping?] (http://forums.linuxmint.com/viewtopic.php?f=208&t=199720)
[How to Recover Skype Taskbar Flashing in Cinnamon] (http://arbitraryposting.blogspot.pt/2015/03/how-to-recover-skype-taskbar-flashing.html)

**Comment by Vahan86** [comment]
@alextpedro, is this still an issue for you in Cinnamon 3.2?

**Comment by alextpedro** [comment]
Not that I've noticed. There's been some inconsistencies but I'm pretty sure it's the program now (no longer Skype thankfully).
