### ISSUE TITLE
Cinnamon Freeze on alt-tab

### ISSUE THREAD

**Issue by phenix-factory** [linuxmint/Cinnamon#4987]
Hello,

I got all my system freezing when i use alt-tab. I use the "icone only" option.
Not all the time, just sometimes. I don't really understand why.
It s not a new problem, i got that bug on 17.2

I switch to "icon and  preview" to try... 

Config:
```
I7 4770k
Asus Saberthoot
Double AMD R9 200 + AMD driver
8 Go
```
Updated Linux Mint 17.2 => 17.3 at the stable release.

**Comment by Vahan86** [comment]
@JosephMcc, https://github.com/linuxmint/Cinnamon/issues/4072

**Comment by JosephMcc** [comment]
It would be nice to keep these consolidated in one place https://github.com/linuxmint/Cinnamon/issues/4072
