### ISSUE TITLE
Right-click context menu "open with" wrong text

### ISSUE THREAD

**Issue by USER762341** [linuxmint/Cinnamon#4989]
The right-click open with context menu displays the correct icon but not the correct text.

In this example, the default application is geany, the icon is for geany and if I click the link it opens in geany, but the text is displayed as leafpad.

![screenshot from 2016-01-06 13-41-38](https://cloud.githubusercontent.com/assets/2036866/12152630/4cd3227e-b47b-11e5-9db5-f868dc986675.png)

**Comment by mtwebster** [comment]
Fixed in nemo: https://github.com/linuxmint/nemo/commit/fb97b62aad23bb44820713c8084785bbc147bfd7
