### ISSUE TITLE
screen tearing in Cinnamon with Nvidia proprietary graphics

### ISSUE THREAD

**Issue by LiamDawe** [linuxmint/Cinnamon#4990]
For some reason, now and then when I boot up everything in Cinnamon has tearing, and a simple reboot seems to fix it.

This is tested in Cinnamon 2.8 since that's the latest in Mint 17.3.

Scrolling in firefox, videos etc all tear in a horizontal line. When I reboot it's all back to normal.

Running on Intel i7, 16GB RAM, Nvidia 980ti, all available drivers tested.

**Comment by NaughtySquid** [comment]
If it helps, here's my xorg log: https://gist.github.com/NaughtySquid/989d4f0c53c424643f91

**Comment by LiamDawe** [comment]
I have found that the Nvidia setting "ForceFullCompositionPipeline" will remove tearing, but it will be nice not to have to do that.

**Comment by JosephMcc** [comment]
https://github.com/linuxmint/Cinnamon/issues/3423
