### ISSUE TITLE
Java JWindow shows up as "win0" in the Window list (taskbar) instead of being hidden

### ISSUE THREAD

**Issue by bxabi** [linuxmint/cinnamon#4992]
Linux Mint 17.3 Rosa, Cinnamon 2.8.6 64 bit.

My Java program Creates a JWindow. This should not show up in the Taskbar (Window List).
https://docs.oracle.com/javase/8/docs/api/javax/swing/JWindow.html

It works fine in KDE and Windows (no taskbar element), but in Cinnamon an element called "win0" appears in the taskbar.
![win0](https://cloud.githubusercontent.com/assets/11303766/12198422/fbaa5340-b60f-11e5-9705-0d914f50bb40.png)

**Comment by dmarcaida** [comment]
Experiencing this as well on Linux Mint 17.2 Rebecca, Cinnamon

**Comment by donquixote** [comment]
One application where this is happening for me: PhpStorm.
https://youtrack.jetbrains.com/issue/WI-39812

**Comment by DanielRios549** [comment]
I recently notice something like that, but I see this issue after creating a new one: #7329.
This problem is terrible, I think they should fix this bug in the next release.

**Comment by icarter09** [comment]
Anyone on this ticket have any update on the status of this issue?
