### ISSUE TITLE
Allow setting the screensaver/locker

### ISSUE THREAD

**Issue by ManuelSchneid3r** [linuxmint/Cinnamon#4993]
Is there a way to set the screenlocker? I use lightdm and would prefer to let lightdm do the screenlocking. Just for visual consistancy. No fancy ui stuff. Just a line in a config file

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
