### ISSUE TITLE
Screenshot default file name does not play well.

### ISSUE THREAD

**Issue by daose** [linuxmint/Cinnamon#4997]
When screenshotting, the ':' stamps for the time does not play well when uploading to web or opening the file on a Windows computer. 

I've had an issue where I could not open, delete, or move the file on Windows because it couldn't process the string name for the .png.

e.g. "Screenshot from 2016-01-11 21:37:54.png" The ':' causes issues, it's not a big problem because I can manually change it myself, but it's not very convenient, especially when taking multiple screenshots repeatedly.

**Comment by JosephMcc** [comment]
Duplicate https://github.com/linuxmint/Cinnamon/issues/4999
