### ISSUE TITLE
maxima package is incomplete

### ISSUE THREAD

**Issue by cwinant** [linuxmint/Cinnamon#4998]
After installing maxima from software source or sudo apt-get install maxima, maxima doe nor find the package ode2.mac

**Comment by JosephMcc** [comment]
Sorry, but I don't see how this issue is related to Cinnamon.

**Comment by cwinant** [comment]
Well it is a package that was built for cinnamon. In a case like this where
should the bug report be filed?  If I understand correctly, some wonderful
folks take the time to maintain and update packages for each update of
Linux Mint.  Where should bug reports about those packages be filed?

Thank you so much for the wonderful work you and your colleagues are doing.

Clinton Winant
