### ISSUE TITLE
print screen issue

### ISSUE THREAD

**Issue by bawasaab** [linuxmint/Cinnamon#4999]
When i have took the screen shot in both linux mint or LMDE that (.png) file <b>does not opened</b> in the windows 7 and shows the following error

<b>"windows photo viewer can't open this picture because either the picture is deleted , or it's in a location that isn't available."</b>

**Comment by mjenki03** [comment]
Which version of mint? What tool did you use to make the screenshot? Can you check the file size?

**Comment by bawasaab** [comment]
Dear Mint Team,

I simply take the screen shot using the (PRINT SCREEN) button present on 
my keyboard. The screen shot can be viewed in linux mint but not in 
windows 7.

Deepak Bawa

**Comment by bawasaab** [comment]
Dear Team,

I have used linux mint 17.2,3 and LMDE. This issue exists in all these 
versions.

Deepak Bawa

**Comment by leigh123linux** [comment]
Surely this is a windoze issue!

**Comment by bawasaab** [comment]
OK. thanx for reply.

**Comment by Vahan86** [comment]
@bawasaab, is this still an issue for you with Cinnamon 3.4?

**Comment by Vahan86** [comment]
@JosephMcc, can we close this issue since there is no response from OP for a long time?
