### ISSUE TITLE
Sarah: Suggestions

### ISSUE THREAD

**Issue by jessepfrancis** [linuxmint/Cinnamon#5001]
It will be great if you add a "Mate-Do" or a "Cinnamon-Do" or mix-em-up to one "Mint-Do", which does just what GNOME-Do does (or something better).

On login, this "Mint-Do" can stay in panel or in one corner of desktop and capture keyboard strokes automatically (optional), so that it saves users from few clicks. Can also be seen as a free, not-tracked take on WIndows10's Cortana in panel.

For example, at present, I have MATE, with GNOME-Do (works neat, except that GNOME-Do fails to start automatically in say 1/10 login attempts) and it knows me well that pressing "F" takes me to Firefox, T to terminal (based on my usage, tracked locally) etc.

And may be integration with Android/Firefox OS devices (like notifications on desktop for a paired android device - that which linconnect does with android more control on notifications) will be something new and unique to Mint (18)

I had posted it in LM Community and I was asked to post feature request here instead. I have posted it in MATE Issues as well; I can't find the link to delete it!

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
