### ISSUE TITLE
Multiple rows in window list applet

### ISSUE THREAD

**Issue by Sammyboy** [linuxmint/Cinnamon#5002]
As far as I can see, there seems to be no feature to let the window list applet display the items in more than one row and I think that would be a useful feature.

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
