### ISSUE TITLE
Window jumps to last position on taskbar when moved between monitors

### ISSUE THREAD

**Issue by gerow** [linuxmint/Cinnamon#5003]
Observed this with Cinnamon 2.6.13. I haven't had a chance to test with more recent versions but I couldn't find any resolved issues that mentioned something like this.

Video of this behavior: https://www.youtube.com/watch?v=8B2y7rVl66s

**Comment by moplam** [comment]
Thanks for the quick fix :+1:

**Comment by gerow** [comment]
I've backported the patches to 2.6.13 and can confirm that this fixes the issue there too. Thanks a bunch for the fix!
