### ISSUE TITLE
[feature request]: drag & drop apps in window list to other screen

### ISSUE THREAD

**Issue by glumanda99** [linuxmint/Cinnamon#5005]
I tried this a few times on a multi monitor setup. It would be nice if you could move your application from `window list` in a `panel` on monitor 1 to another `window list` in a `panel` on monitor 2.

**Comment by JosephMcc** [comment]
Do you mean via drag and drop? If I right click on the window list on monitor 1 and choose to "Move to other monitor" it does exactly that.

**Comment by mankoell** [comment]
Yes, I mean drag & drop.

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
