### ISSUE TITLE
Applets module crashes with ValueError in Spices.py

### ISSUE THREAD

**Issue by Ko-** [linuxmint/Cinnamon#5008]
```
~$ cinnamon-settings applets                                           ~
Python module
Loading Applets module
Traceback (most recent call last):
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 603, in <module>
    window = MainWindow()
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 92, in wrapper
    res = func(*arg)
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 318, in __init__
    self.go_to_sidepage(cat, path)
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 124, in go_to_sidepage
    sidePage.build()
  File "/usr/share/cinnamon/cinnamon-settings/bin/SettingsWidgets.py", line 329, in build
    self.module.on_module_selected()
  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_applets.py", line 16, in on_module_selected
    self.sidePage.load()
  File "/usr/share/cinnamon/cinnamon-settings/bin/ExtensionCore.py", line 443, in load
    self.spices.scrubConfigDirs(self.enabled_extensions)
  File "/usr/share/cinnamon/cinnamon-settings/bin/Spices.py", line 727, in scrubConfigDirs
    panel, align, order, uuid, id = enabled.split(":")
ValueError: need more than 4 values to unpack
```
All other modules are working fine. This is a fresh install of Cinnamon 2.8.6 on an up-to-date Arch Linux. Any ideas why this might be happening?

**Comment by mtwebster** [comment]
Check the gsettings key: `org.cinnamon`, `enabled-applets` - you can check it either from the command line (`gsettings get org.cinnamon enabled-applets`) or using dconf-editor (I recommend this, as you can more easily fix your problem with that also) - 

Each entry in this string array should have 5 values delimited by `:` - somehow it seems that at least one of your entries has less than that - see if you can spot it, and, if so, correct it (just remove the offending entry).  If all else fails, you can reset the entry, but that will also reset your panel to having just the default applets.

**Comment by Ko-** [comment]
All of them have only 4 values.
```
~$ gsettings get org.cinnamon enabled-applets | tr ',' '\n'            ~
['panel1:left:0:menu@cinnamon.org'
 'panel1:left:1:show-desktop@cinnamon.org'
 'panel1:left:2:panel-launchers@cinnamon.org'
 'panel1:left:3:window-list@cinnamon.org'
 'panel1:right:0:notifications@cinnamon.org'
 'panel1:right:1:user@cinnamon.org'
 'panel1:right:2:removable-drives@cinnamon.org'
 'panel1:right:3:keyboard@cinnamon.org'
 'panel1:right:4:bluetooth@cinnamon.org'
 'panel1:right:5:network@cinnamon.org'
 'panel1:right:6:sound@cinnamon.org'
 'panel1:right:7:power@cinnamon.org'
 'panel1:right:8:systray@cinnamon.org'
 'panel1:right:9:calendar@cinnamon.org'
 'panel1:right:10:windows-quick-list@cinnamon.org']
```

**Comment by mtwebster** [comment]
Looking further into this, our default entry for that key is 4-value sets, just like you're showing - upon the first run of cinnamon, these get an additional value added.

Theoretically, you should only run into this problem if you haven't actually run cinnamon yet.

Can you double-check your installed versions?  Also, open `/usr/share/cinnamon/js/ui/appletManager.js` and search for **checkForUpgrade**

**Comment by Ko-** [comment]
I had not run it yet. Sorry for wasting your time.

**Comment by lestcape** [comment]
I don't know what @Ko- is trying to do, but maybe will be useful perform the split inside an array, then check how many values there are and then report to the user what he/she need to do or instead of this, request an automatically update if is required as apparently somehow this situation may occur.
