### ISSUE TITLE
[Feature Request] Drag & drop from applications to minimized window should action it.

### ISSUE THREAD

**Issue by alextpedro** [linuxmint/Cinnamon#5010]
Hello!

Currently, when you are working in an application and want to send a file or piece of text to another one, you have to drag the file and alt+tab to where you want to open/put it. 

It would be nice to have a behavior like in Windows where you can drag and drop from one place to the next using the taskbar.

For example, if you download a file in chrome, you should be able to drag it from the download bar to a minimized nemo window to have the file move over to that location.

Related: #4383

**Comment by JosephMcc** [comment]
In Cinnamon3 I can for example drag a text file from nemo to the minimized text editor on the task bar. That unminimizes the window and allows me drop it in the interface. Does that meet your needs?

**Comment by alextpedro** [comment]
Yes, it does!

**Comment by JosephMcc** [comment]
Ok. Closing this then.
