### ISSUE TITLE
Unable to set keybindings using the Up / Down arrow keys

### ISSUE THREAD

**Issue by FujiMakoto** [linuxmint/Cinnamon#5012]
Cinnamon 2.8.6

When trying to set a keybinding the uses the Up or Down arrow keys, it seems to effectively escape out of the keybinding box and won't actually save the keybinding. This is reproducible with any key combination involving the up/down arrow keys.

**Comment by JosephMcc** [comment]
There was work done to the keybinding settings on git master. This problem seems to be fixed. I can assign "Switch to workspace" right to Ctrl+UpArrow with no issues.
