### ISSUE TITLE
Screen power management

### ISSUE THREAD

**Issue by andreabellitto** [linuxmint/Cinnamon#5014]
I'm on Ubuntu 15.10 with Cinnamon 2.8.6, i suffer this bug, i have my screen power management settings as follow:

On battery: turn off screen after 5 minutes of inactivity
On AC: never turn off screen

If turn on my PC while it is attached to AC power source, my screen never turns off on inactivity periods, if then i remove te AC power cable it follow my settings and after 5 minutes of screen inactivity turns off the screen. But if then i attach again my PC to AC power cable, it remains with the 5 minutes timeout setting on the screen power management settings. To make it work again I need to restart my PC or to restart Cinnamon.

It's a very annoyng bug, please investigate on it.

**Comment by Vahan86** [comment]
@andreabellitto, is this still an issue in Cinnamon 3.6?

**Comment by andreabellitto** [comment]
I't a problem even on Cinnamon 3.6.7

**Comment by leigh123linux** [comment]
Please file the issue against cinnamon-settings-daemon as that handles power.
