### ISSUE TITLE
LMDE issue in pen drive mount

### ISSUE THREAD

**Issue by bawasaab** [linuxmint/Cinnamon#5015]
System: Dell Vostro 1540
RAM: 2gb
Processor: intel i3
OS: LMDE - 2 Cinnamon 64 bit

I had plug my 16gb sandisk pendrive in slot. The pendrive icon was appeared but the pendrive was not mounted sucessfully. Then I removed my pendrive but the icon remains there as the system was not able to detect the ejection of pendrive. I had plugged and unplugged the device 2-3 times but the issue remains same. Then i reboot my system and then it was able to mount my pendrive.

**Comment by lestcape** [comment]
Please be sure you have a good configuration for your cinnamon session in gsettings:
http://segfault.linuxmint.com/2015/06/cinnamon-2-6/
