### ISSUE TITLE
network settings window does not display wifi state correctly

### ISSUE THREAD

**Issue by voxspox** [linuxmint/cinnamon#5018]
The dialog window "Networking" from "System Settings" displays a wrong Wi-Fi status after Hotspot was enabled.

This problem still is present in Linux Mint 17.3 Rosa / Cinnamon 64 bit

steps:
1. networking applet shows "wifi disabled" (and that is true)
2. open networking dialog via the network applet clicking on "Network settings"
3. networking shows "Wi-Fi Hotspot on" (which is wrong)
4. click on switch -> dialog opens, click "stop Hotspot"
5a. Wi-Fi is activated and available APs are shown
5b. sometimes Wifi is off
6. close window and reopen like step 2
7. networking shows "Wi-Fi Hotspot on" (which is wrong)

The "Networking" dialog behaves wired when a hotspot was used. It seems that the wifi on/off state and also the hotspot on/off state is somehow not detected correctly.

Additionally, I expect that the "create hotspot" dialog will activate wifi, which is not the case. And the other way round also.

**Comment by Vahan86** [comment]
@voxspox, is this still an issue in Cinnamon 4.2?

**Comment by Vahan86** [comment]
@icarter09, can we close this issue since there is no response from OP?

**Comment by voxspox** [comment]
sorry. I verified this on Cinnamon 4.4.8. The status is now displayed as expected.

What I'm still missing is that the "Use Hotspot" dialog should activate Wifi if currently disabled.
