### ISSUE TITLE
Logout gets delayed if Steam is open

### ISSUE THREAD

**Issue by intdel** [linuxmint/Cinnamon#5019]
I am using Fedora 23, and installed steam from the rpmfusion repo.
If steam is open and I hit log out, everything closes, but I still need to wait ~30 seconds until the log out actually happens. If I close steam manually just right before I log out, the log out works fine.

**Comment by leigh123linux** [comment]
duplicate of https://github.com/linuxmint/Cinnamon/issues/3752

**Comment by intdel** [comment]
Thanks @leigh123linux .
