### ISSUE TITLE
Window List title is not always up to date

### ISSUE THREAD

**Issue by rmwiseman** [linuxmint/Cinnamon#5025]
I noticed today that when I saved my new LibreOffice document, the icon title changed in the window list applet, but the title on the thumbnail remained the same.  I've attached a screen shot that demonstrates the issue:

![incorrectthumbnailtitle](https://cloud.githubusercontent.com/assets/10866705/12445623/4eff5d78-bf5d-11e5-9ffc-540752f8623e.png)

**Comment by JosephMcc** [comment]
Fixed in git master. See https://github.com/linuxmint/Cinnamon/issues/4879
