### ISSUE TITLE
since 2.8 popups have no window decorations and darken the main window

### ISSUE THREAD

**Issue by calestyo** [linuxmint/Cinnamon#5027]
Hey.

I quite strangely feel remembered to GNOME3... apparently since 2.8, when a window get's some child popup window create (e.g. a save dialogue or so),.. the mainwindow darkens (why?! Id' still would like to be able to properly read content there)... and the popup has no window decorations anymore (WTF?! Why should users want to have *that*??? No more control over the window, no more being able to move it,...)

Please do away with that GNOME3 style or make it at least configurable.

Cheers,
Chris.

**Comment by JosephMcc** [comment]
Well, it is configurable. Cinnamon-setting->Windows->Behavior "Attach dialog windows to the parent window"

**Comment by calestyo** [comment]
hmm I see.. then one should perhaps make a task bug like: do not change default to fancy new behaviour, where people have to search for how to get back to the traditional desktop schema.

thx anyway =)

**Comment by mtwebster** [comment]
It's already been reverted to default to the old behavior

**Comment by calestyo** [comment]
Ah.. great to hear :-)
