### ISSUE TITLE
Drag and Drop (Start) Menu entries to Desktop

### ISSUE THREAD

**Issue by Mintberry1** [linuxmint/Cinnamon#5028]
I wanted to suggest that you can drag and drop menu entries of programs to the Desktop (To make an additional copy of the launcher on the Desktop) and the bottom Panel bar as well to make a copy.

I know you can rightclick on the entry and choose the option but drag and drop would be nice, easy and intuitively to use i think

**Comment by lestcape** [comment]
And also is possible and easy do that.

**Comment by JosephMcc** [comment]
You can already drag and drop applications to the panel launchers applet. Doing it to the desktop might be a different story since you are talking about two different UI toolkits.

**Comment by lestcape** [comment]
@JosephMcc he say "menu entries", but you also can add panel buttons launchers and they are clutter objects...

He also only want to create a .desktop file (this is not a different UI toolkits), is just a file this a format specification that you can create when you want and put where you want over cjs.

Inside the desktop, there are a clutter object to. So, the desktop clutter object can capture the clutter buttons drop and ask for the delegate class of the buttons.

Then you can add a render_desktop_file function inside the delegate class with a the path parameter (in that case the desktop path) for all buttons.

And now, when you capture the drop inside the desktop object, ask for the delegate class of the button, call the render_desktop_file function of the button with the desktop path parameter and then accepted the drop.

**Done**, this is just what is needed. i don't see the  two different UI toolkits.

**Comment by lestcape** [comment]
What could be difficult, is the possible drag and drop way, from the desktop to the menu, but is also possible. Who Nemo is who control the desktop, you can write a dbus function inside cinnamon Dbus with a path parameter of a desktop file. When nemo detect a drag  of .desktop file he can call the Dbus function and with the path of the file as a parameter, capture the response of the Dbus function and if is true stop the drag and drop and hide the object that is dragging.

As cinnamon receive the path of the desktop file inside the dbus function, he can construct a panel launcher button on fly and add it to the desktop object again and force the drag and drop class to begin a normal drag and drop of an a clutter object. So, as it's a clutter object you can drop it inside any component where you want that accept this type of button.

**Comment by lestcape** [comment]
This last techniques, also could be generic, if the dbus function receive also as a parameter the class of the object that cinnamon will construct. Again, the result clutter object can be drop in any clutter object that accept this type of object.

This have a directly application in cinnamon settings, to drag and drop applets and desklets.

**Comment by anandrkris** [comment]
Also linking a PR that wasn't merged for reference which has details on possible things to consider...
https://github.com/linuxmint/Cinnamon/pull/842

**Comment by lestcape** [comment]
Configurable Menu allows drag and drop application buttons to the desktop too...

**Comment by NikoKrause** [comment]
Isn't the configurable menu broken?
In the past I wanted to try it, but I was never able to get it running.
It seems as it is abandoned. I think the problem with configurable menu is, that it has too many configurations. Too many things, which could break and which make it harder to maintain.
In my opinion it should have been splited into more applets. If the source of these applets would stay as near as possible to the original menu, this would make it easier to maintain and to get fixes, which were made upstream. And it would have been easier to fork it.

**Comment by NikoKrause** [comment]
@lestcape 
Could you reference the (specific) part of the code of Configurable menu, which handles this feature?

**Comment by lestcape** [comment]
@NikoKrause the problem with configurable Menu, in my opinion, was extend for the cinnamon API, and then modify the children class, as the Cinnamon API is not stable, never was, my code of course will be broken on any little change inside the parent class (the cinnamon classes). I can easy fix configurable menu if i only create a fix where there are a change in cinnamon code. Just I’m done of do that... What i tray to do now it's not depend of cinnamon code at all... The configurable Menu kernel it's working in my computer, but with a lot of problems if i try to change something, because there are a lot of work to fix all possible behaviours. But how it`s now a change on the cinnamon code, will not create a problem on configurable Menu. For example in cinnamon the box-pointer was removed, but the configurable menu has his own box pointer...

Here you can find the relate code:
https://github.com/lestcape/Configurable-Menu/blob/master/configurableMenu%40lestcape/menuItems.js#L118

https://github.com/lestcape/Configurable-Menu/blob/master/configurableMenu%40lestcape/menuItems.js#L1340

**Comment by lestcape** [comment]
@NikoKrause what possible you are looking for it's here:
https://github.com/lestcape/Configurable-Menu/blob/master/configurableMenu%40lestcape/menuItems.js#L2123

How in cinnamon, there are not a Desktop class, to accept the drop of the buttons, i handled the drop inside the button class instead (of course) inside the missing class.

What i do it's check if the button it's inside a desktop actor and if this is the case i render the desktop file in the desktop path, when the button was drop.

**Comment by NikoKrause** [comment]
@lestcape 
Would the same code work with the original menu.
If yes, what speaks against this implementation?
I'm not very familiar with handling drag&drop code, but I think it isn't the fine British style to handle it like this, is it?

**Comment by lestcape** [comment]
@NikoKrause Yes will work in the cinnamon menu, without a problem. Things that i can see as problematic:
1- This is not a good implementation. A good implementation will be create a desktop manager class and accept the drop there and share it implementation for all client that want to use it.
2- This is not properly a drag and drop implementation, because there are not one that acepted the drop.
3- A good implementation need to take in account both direction for drag and drop and this will be only in one way from an applet to the desktop, and not from the desktop to an applet.
4- You can not decide to drop an item in the desktop position that you want.
5- This is really much specific, because only considered a drag and drop to the desktop, and a general behavior will be a way to merged gtk drag and drop with clutter drag and drop.

**Comment by NikoKrause** [comment]
@lestcape 
Thanks for the explanation.

> 3- A good implementation need to take in account both direction for drag and drop and this will be only in one way from an applet to the desktop, and not from the desktop to an applet.

I don't think it would be a good idea to allow drag&drop from the Desktop to the menu. This way it would be too easy to mess the menu up.

**Comment by lestcape** [comment]
@NikoKrause this depend of how you see the favorites buttons in the menu.
I see this a box where you can create links to applications **and places**  from a source: the menu items, the panel launcher, the desktop or whatever there are a reference to an specific place or application. Then it's not in my opinion more mess add another source, just more general.

**Comment by lestcape** [comment]
In fact the cinnamon windows list can detect a drag of something from the desktop over the windows list and in that case he active the windows. Same thing probably could be added to the menu to open it on a drag and then accept the drop in the favorites box if what is dragging is a desktop file that have a valid link to an app.

**Comment by lestcape** [comment]
@NikoKrause as how apparently this is interesting to you, here there are a better implementation. Just add this class to the layout.js (https://github.com/linuxmint/Cinnamon/blob/master/js/ui/layout.js) file:
```
function NemoDesktopArea() {
    this._init();
}

NemoDesktopArea.prototype = {
    _init: function() {
        this.actor = global.stage;
        if(!this.actor.hasOwnProperty('_delegate'))
           this.actor._delegate = this;
        this._setPositionIdle = 0;
    },

    acceptDrop : function(source, actor, x, y, time) {
        let app = source.app;
        if(app == null || app.is_window_backed())
            return false;  
        let backgroundActor = global.stage.get_actor_at_pos(Clutter.PickMode.ALL, x, y);
        if(backgroundActor != global.window_group)
            return false;
        let file = Gio.file_new_for_path(app.get_app_info().get_filename());
        let destFile = Gio.file_new_for_path(FileUtils.getUserDesktopDir()+"/"+app.get_id());
        try {
            file.copy(destFile, 0, null, function(){});
            FileUtils.changeModeGFile(destFile, 755);
            // FIXME: if you want to drop the desktop file to a position remove the comments to the next two lines
            // but any way this is a bad solution. We have another posibility?
            //if (this._setPositionIdle == 0)
            //    this._setPositionIdle = Mainloop.timeout_add(500, Lang.bind(this, this.setPosition, destFile, x, y));
        } catch(e) {
            global.log(e);
            return false;
        }
        return true;
    },

    handleDragOver: function(source, actor, x, y, time) {
        let app = source.app;
        if(app == null || app.is_window_backed())
            return DND.DragMotionResult.NO_DROP;  
        let backgroundActor = global.stage.get_actor_at_pos(Clutter.PickMode.ALL, x, y);
        if(backgroundActor != global.window_group)
            return DND.DragMotionResult.NO_DROP;
        return DND.DragMotionResult.COPY_DROP;
    },

    setPosition: function(destFile, x, y) {
        if (this._setPositionIdle != 0) {
            Mainloop.source_remove(this._setPositionIdle);
            this._setPositionIdle = 0;
        }
        let path = destFile.get_path();
        x = Math.round(x);
        y = Math.round(y);
        Util.spawnCommandLine("gvfs-set-attribute -t string \"" + path +"\" \"metadata::nemo-icon-position\" \""+x+","+y+"\"");
        Util.spawnCommandLine("mv " + path + " /var/tmp/");
        Util.spawnCommandLine("mv /var/tmp/" + destFile.get_basename() + " " + FileUtils.getUserDesktopDir());
    },
}
```

In the end of the init function of LayoutManager add this line:
```
        this._desktop = new NemoDesktopArea();
```
Make sure you will import all this at the begin of the file:
```
const DND = imports.ui.dnd;
const FileUtils = imports.misc.fileUtils;
const Util = imports.misc.util;
```

Now drag and drop a desktop file to the desktop.

**Comment by lestcape** [comment]
A little better to set the icon position:
```
function NemoDesktopArea() {
    this._init();
}

NemoDesktopArea.prototype = {
    _init: function() {
        this.actor = global.stage;
        if(!this.actor.hasOwnProperty('_delegate'))
           this.actor._delegate = this;
        this._setPositionIdle = 0;
    },

    acceptDrop : function(source, actor, x, y, time) {
        let app = source.app;
        if(app == null || app.is_window_backed())
            return false;  
        let backgroundActor = global.stage.get_actor_at_pos(Clutter.PickMode.ALL, x, y);
        if(backgroundActor != global.window_group)
            return false;
        let file = Gio.file_new_for_path(app.get_app_info().get_filename());
        let destFile = Gio.file_new_for_path(FileUtils.getUserDesktopDir()+"/"+app.get_id());
        try {
            file.copy(destFile, 0, null, function(){});
            FileUtils.changeModeGFile(destFile, 755);
            // FIXME: if you want to drop the desktop file to a position remove the comments to the next two lines
            // but anyway this is a bad solution. We have another posibility?
            if (this._setPositionIdle == 0) {
                this.setPosition(destFile, x, y);
                //this._setPositionIdle = Mainloop.timeout_add(500, Lang.bind(this, this.setPosition, destFile, x, y));
            }
        } catch(e) {
            global.log(e);
            return false;
        }
        return true;
    },

    handleDragOver: function(source, actor, x, y, time) {
        let app = source.app;
        if(app == null || app.is_window_backed())
            return DND.DragMotionResult.NO_DROP;  
        let backgroundActor = global.stage.get_actor_at_pos(Clutter.PickMode.ALL, x, y);
        if(backgroundActor != global.window_group)
            return DND.DragMotionResult.NO_DROP;
        return DND.DragMotionResult.COPY_DROP;
    },

    setPosition: function(destFile, x, y) {
        if (this._setPositionIdle != 0) {
            Mainloop.source_remove(this._setPositionIdle);
            this._setPositionIdle = 0;
        }
        let path = destFile.get_path();
        x = Math.round(x);
        y = Math.round(y) - 48;
        destFile.set_attribute_string("metadata::nemo-icon-position", x+","+y, Gio.FileQueryInfoFlags.NONE, null);
        //We need to force nemo to reload the desktop file (F5)
        Util.spawnCommandLine("mv " + path + " " + path + ".bak");
        Util.spawnCommandLine("mv " + path + ".bak" + " " + path);
    },
}
```

**Comment by NikoKrause** [comment]
@lestcape 
I hadn't time to look into it. I see now, that you already created a Pull Request for that.
Sounds great. Thanks for the effort!

**Comment by lestcape** [comment]
Yes, this is only for applications, configurable menu can drag and drop also places to the desktop.

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
