### ISSUE TITLE
VPN Static IP routing issues caused by obscurely mandatory Gateway field

### ISSUE THREAD

**Issue by FujiMakoto** [linuxmint/cinnamon#5029]
##### Arch Linux/Cinnamon 2.8.6

For the last month or so, I've had all of my static routes for my VPN configured manually through a bash script that calls `ip route add` directly, and this has worked without issue.

I decided to try and set this up through NetworkManager for the sake of simplicity today, but despite my best efforts, I could not get it to work. No matter how I set it up, I would always get an error like this returned,
https://bpaste.net/show/f59f40d07d45

This appears to be caused by the fact that Cinnamon's Networking applet lists the Gateway field when configuring VPN routes as **mandatory**. `ip` does not, neither does NetworkConfig's own configuration applet. You can specify static routes with no Gateway address provided.

When this is done, it appears to default to using `0.0.0.0` for the gateway address, which works. The problem is since I didn't have to input this on _anything else_ other than with Cinnamon's own Networking applet, I had no idea what it expected me to input here.

I tried everything I could think of, including my VPN's actual address, and I couldn't find any resources anywhere that suggested to use 0.0.0.0 in its place, nor did anyone on Arch's IRC seem to know what should have to be put here. But once I configured the VPN manually through NetworkManager's own applet, everything worked again.

Can the mandatory requirement please be removed on this field, so that it will work as everything else seems to and default to `0.0.0.0` when no input is provided?

**Comment by icarter09** [comment]
@FujiMakoto are you still experiencing this issue?
