### ISSUE TITLE
gnome-terminal missing option to open in window/tab

### ISSUE THREAD

**Issue by kitsguru** [linuxmint/Cinnamon#5030]
I have just installed Mint 17.3 with Cinnamon 2.8.6 & gnome-terminal 3.6.2.

I have been unable to get gnome-terminal to open in a new tab from either the panel launcher, command line or bash script.

gnome-terminal --tab

should open new instance in a tab but is always opening a new window. 

According to gnome-terminal website there is an option in Preferences->General to select window or tab but is not present in my version. 

I am using Sublime Text 3 and Sublime Terminal Package and want to open the terminal from there in a new tab.

Any help would be appreciated.

**Comment by ManIVIctorious** [comment]
Sorry but I just can't see how this should be a cinnamon issue. Please file a bug against gnome-terminal and close this one

**Comment by kitsguru** [comment]
New to Cinnamon, my apologies if I posted this in the wrong place. Who is responsible for updating the gnome apps in cinnamon? The latest gnome-terminal is 3.18 and 3.16 was released almost a year ago. Linux Mint 17.3 is fairly recent as well. I am a bit confused as all the interplay with all the various components.

**Comment by JosephMcc** [comment]
https://github.com/linuxmint/gnome-apps
