### ISSUE TITLE
Touchpad settings per device

### ISSUE THREAD

**Issue by keitalbame** [linuxmint/cinnamon#5040]
Add the possibily to select per device, the touchpad settings.
In my use case, I have a laptop without 2 finger scrolling and when using a external touchpad (with 2 finger scrolling), I need to change manual the scrolling from edge to 2 finger and vice versa when unplugged.

Maybe this option would be present if, a external mouse(or touchpad) is detected by the system (still to implement on #3721).

**Comment by keitalbame** [comment]
Strange thing is that using Logitech K400 with integrated touchpad, the 2 finger scroll works with the edge scroll selected.

http://support.logitech.com/en_us/product/wireless-touch-keyboard-k400

When using the external touchpad, Logitech Wireless Touchpad T-R0002, I need to change manually to 2 finger scroll, to use the feature.

http://support.logitech.com/en_us/product/wireless-touchpad

Maybe this is some device limitation. I'm using separate Unifying Receivers. 

I'm on Arch.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
