### ISSUE TITLE
[Feature request] Add "Close this window then open file" to nemo

### ISSUE THREAD

**Issue by coucout** [linuxmint/Cinnamon#5043]
Very often, as everybody i think, i open nemo to search a file and open it only, not to manipulate files (copy, paste, rename etc...).
In this context of use, it would be very cool if the concerning Nemo window could be immediately closed then the desired file is opened. I think it would be more productive because when you have finished editing/viewing the file, your brain do not need to ask : "Why this Nemo window is opened ?". Or in multitasking perspective, your taskbar is not overcrowded with unnecessary window/buttons.

So i suggest to add a function to Nemo, like "Shift Double Click" to achieve this idea, same with contextual menu "open with", "Shift click".

**Comment by JosephMcc** [comment]
Please move this request to the nemo github page: https://github.com/linuxmint/nemo
