### ISSUE TITLE
Cinnamon graphic glitches Kernel 4.x Intel HD 5xx

### ISSUE THREAD

**Issue by pepe4** [linuxmint/Cinnamon#5044]
Hello

i just got a Dell XPS 13 (9350 late 2015/2016). It has a Skylake chip with Intel HD 520 graphics on board.

I installed Linux Mint 17.3 and upgraded to Kernel 4.4 (mainline) for the Wifi to work. 
4.4 did not fix it, even if its supposed to support the Broadcom 4350 chip. I got the Wifi working using this custom Kernel from the first answer: http://askubuntu.com/questions/709794/dell-xps-13-9350-compatibility/719947

However, both Kernels (custom 4.3 and 4.4 mainline from ubuntu repos) caused Cinnamon to flicker and graphic glitches. Especially if i click or move the mouse, the glitches are heavier.

A screenshot of the bug and other people reporting the problem can be found here:
http://forums.linuxmint.com/viewtopic.php?f=90&t=213443

The screen does not look like this all the time, only if you interact with mouse or keyboard and sometimes randomly. The other time the screen looks fine like its supposed to be.

People report they dont have this issue using MATE or Ubuntu so i suppose its a bug in Cinnamon.

The driver used is i915 and i tried several Kernelparameters i found when i googled the problem. Nothing fixes it.

Thanks for reading

**Comment by leigh123linux** [comment]
This is clearly a driver issue so close this report and file the issue against mesa or the kernel!

**Comment by pepe4** [comment]
Using MATE or other window managers, this problem does not exist. Are you really sure this is driver related?

**Comment by leigh123linux** [comment]
Mate uses the 2D driver for desktop display and cinnamon uses the 3D driver

**Comment by pepe4** [comment]
okay thank you!

**Comment by josedellabosca** [comment]
iam using cinnamon on gentoo, kernel 4.12, i tried the intel driver, the generic driver. i also load the dmc, guc and huc blobs, and the result is the same, It works but its very laggy.
Gpu is intel 620.
