### ISSUE TITLE
PM applet: Battery icon is switched to brightness icon when system is shutting down

### ISSUE THREAD

**Issue by HoracioDos** [linuxmint/Cinnamon#5047]
PM applet: Battery icon is switched to brightness icon when system is shutting down.
I don't know to provide more information as I can't see anything meaningful in the syslog and can't get a screenshot when the system shuts down.

**Comment by marlock9** [comment]
Confirm.

**Comment by keitalbame** [comment]
I also noticed that.

`sudo shutdown -k now` can't reproduce that.

**Comment by cromerc** [comment]
Happens for me as well.

**Comment by HileV** [comment]
+

**Comment by Vahan86** [comment]
@HoracioDos, is this issue still relevant to Cinnamon 3?

**Comment by JosephMcc** [comment]
Probably. I don't see what the issue is. Things shutdown in a certain sequence. The applet just loses contact with something during the shutdown process.

**Comment by leigh123linux** [comment]
@JosephMcc Next they will be complaining the desktop icons disappear when shutting down 🙄
