### ISSUE TITLE
[2.8.3] Networking stopped working

### ISSUE THREAD

**Issue by MarceloRuiz** [linuxmint/Cinnamon#5049]
Linux Mint 17.3
Cinnamon 2.8.6

Networking stopped working when I started the computer. The network applet is not present in the panel. It was working with no problems before in this computer and now the problem is present all the time. If I open networking it displays: 

> The system network services are not compatible with this version. 

dmesg shows many messages like this one:

`[    6.526210] init: network-manager main process (998) killed by SEGV signal`
`[    6.526222] init: network-manager main process ended, respawning`
`[    6.542510] init: network-manager main process (1003) killed by SEGV signal`
`[    6.542523] init: network-manager main process ended, respawning`

and finally, after many of those it shows:

`[    6.658296] init: network-manager respawning too fast, stopped`

If I try to restart the service I get:

`$ sudo service networking restart`
`stop: Job failed while stopping`
`start: Job is already running: networking`

`$ sudo service networking stop`
`stop: Job failed while stopping`

I can get networking running by running at the command line:

`$ sudo ifconfig wlan0 up`
`$ sudo dhcp`

I had to install Wicd as a temporary workaround.

**Comment by MarceloRuiz** [comment]
Found the solution here:

[http://askubuntu.com/questions/727127/last-upgrade-crashes-network-manager-no-internet-connection-no-applet/727462#727462](url)

The solution is to downgrade libnl packages and wait for an upgrade of network-manager package:

`sudo apt-get install libnl-3-200=3.2.21-1 libnl-route-3-200=3.2.21-1 libnl-genl-3-200=3.2.21-1`

**Comment by JosephMcc** [comment]
This doens't really look like a Cinnamon problem.
