### ISSUE TITLE
[Feature Request] Remove menu margin.

### ISSUE THREAD

**Issue by SebThe3rd** [linuxmint/Cinnamon#5050]
Hello,
I would like to suggest an option to allow the user to make the menu look more like this http://i.imgur.com/8kmDs54.png rather than the original http://i.imgur.com/Rtxznna.png. basically to remove the speech bubble type triangle at the bottom and move the menu to the left or just let the users control that.

**Comment by JosephMcc** [comment]
The menu arrow is actually controlled by the theme. Some have them and some don't. There are already some on going discussions about the distance between the menu and screen edge. One such is here: https://github.com/linuxmint/Cinnamon/issues/4918 and another is here: https://github.com/linuxmint/Cinnamon/issues/4728

Feel free to add to those discussions. I'm going to go ahead and close this as a duplicate.
