### ISSUE TITLE
No "Ok" button in "Power Off" dialog

### ISSUE THREAD

**Issue by swarnendubiswas** [linuxmint/Cinnamon#5052]
The "Power Off" dialog only shows "Cancel" button, there is no "Ok" button to confirm the action. 

![screenshot from 2016-01-31 20-00-55](https://cloud.githubusercontent.com/assets/7343807/12706546/c112230e-c855-11e5-8e38-98d1955e2cba.png)

I am using Cinnamon nightly ppa on Ubuntu Gnome 15.10.

**Comment by JosephMcc** [comment]
Make sure the three settings in org.cinnamon.desktop.session that end in logind are enabled. You can do this with dconf.

**Comment by swarnendubiswas** [comment]
Thanks. Those were unchecked. The problem is resolved now.
