### ISSUE TITLE
High DPI @ 27" 4k - looks not normal

### ISSUE THREAD

**Issue by ManoWent** [linuxmint/Cinnamon#5056]
Hi @all,

i really like Linux Mint and this is my favourite linux distribution at work. Now i had luck and can use an 27" Display with a 4k resolution (3.840 × 2.160). It's no Problem to use the display with Linux Mint but the representation is not really good. I switched high DPI on and changed the text scaling factor. Helps but looks not perfect neither good.

But if i change just the display resolution to 2560 x 1440 down it looks perfect at all.

I'am using Linux Mint 17.3

**Comment by JosephMcc** [comment]
Not really sure what the issue is here. Not all things support hidpi and some of them are out of our control. Could you be more specific what the actual problem is?

**Comment by ManoWent** [comment]
Issue: high dpi works not well
Solution: change the display resolution to a less resolution

I can make pictures to share the wrong representation. Yes i know, it seems so high DPI support is not so simple to solve...

**Comment by JosephMcc** [comment]
Sorry if there is a lack of understanding on my part but I don't really see the Cinnamon issue here.

**Comment by ManoWent** [comment]
I tested with Linux Mint 18 Beta again and high resolution support does not scale the desktop wright. Unity does this better. It has a variable scale factor not a fixed scale factor.
