### ISSUE TITLE
deborphan

### ISSUE THREAD

**Issue by arosella** [linuxmint/Cinnamon#5058]
Mint 17.3 installed on a brand new lenovo b50-10
uninstalled speech-dispatched and run "deborphan" in order to remove unneded packages;

unfortunately, mark as "orphan" 
libwayland-egl1
If uninstalled, cinnamon won't start (crash - fallback mode...)

Incorrect dependencies?

Ciao
A

**Comment by Vahan86** [comment]
@arosella, is this still an issue for you in Cinnamon 3 (Mint 18)?

**Comment by NikoKrause** [comment]
Close if no response?
