### ISSUE TITLE
Automatic desktop scaling for HiDPI screens no longer works

### ISSUE THREAD

**Issue by pietsch** [linuxmint/Cinnamon#5059]
Please find all the details here: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=812805

**Comment by Cobinja** [comment]
This is a regression caused by https://github.com/linuxmint/Cinnamon/commit/ac7bf525e3061f0b93e8b0684b1c28b0af0baf71
Text and icon scaling is only effective if the panel is marked as resizable, which the commit doesn't do.

**Comment by leigh123linux** [comment]
Automatic desktop scaling has never worked in fedora

**Comment by JosephMcc** [comment]
@pietsch In your case it's likely because of this: https://github.com/linuxmint/cinnamon-settings-daemon/commit/fa3e2fd638422cc7ec259e3ffa4a0bb3ab4533d7

Since 1440 is really the starting resolution for HiDpi displays maybe that would be a better choice.
