### ISSUE TITLE
Can't scroll Visible WiFi Connections

### ISSUE THREAD

**Issue by Dinosaur1946** [linuxmint/Cinnamon#5064]
Hi All

First time ever reporting a "bug".
I am using Mint 17.2 Cinnamon V 2.6.13, but also noticed same problem on 17.3

Currently I reside in an apartment complex that has literally dozens of WiFi connections showing up.
But Murphy's law says that the one you want, won't show, because the screen is full.
Pressing More doesn't work once the screen is full.

My suggestion:
Allow scrolling of the full page
OR
Allow removal of connections that you have no interest in.
Screen Print available here:
http://www.tubejoiners.com/downloads/WifiList.odt

Regards

**Comment by kehugter** [comment]
#3678?

It looks better in Cinnamon 2.8 (different, at least), but I can't tell if the issue is solved: my list of available connections got shorter and my screen larger. I might add some VPN connections to test later.

**Comment by Dinosaur1946** [comment]
HI All
Yes, when I connect a larger screen to my laptop, then more will show.

**Comment by JosephMcc** [comment]
Duplicate #3678
