### ISSUE TITLE
Composition appears to hinder MPV motion interpolation.

### ISSUE THREAD

**Issue by DistantThunder** [linuxmint/cinnamon#5065]
Using Cinnamon 2.8.6, with NVIDIA proprietary drivers 361.18 (the problem also occured with the previous stable drivers).

When using the "--video-sync=display-resample --vo=opengl:interpolation" options in order to obtain motion interporlation (See https://github.com/mpv-player/mpv/wiki/Display-synchronization  and https://github.com/mpv-player/mpv/wiki/Interpolation) with the MPV media player, the video shows noticeable stuttering and hiccups on Cinnamon.

After much trying and testing (https://github.com/mpv-player/mpv/issues/2567), it seems the choppy video playback those options incurs are linked to the way Cinnamon handles composition and possibly vsync. 

I tried playing back with the same options on a "blank" Xsession and was able to have seamless playback with Motion Interpolation and display synchronization enabled.

I tried notably with Openbox, with and without Compton, with and without Xorg's TWM window manager. Gnome Shell (3.18.3) however does display this behaviour. So maybe it's something generic to Gnome derived compositors.

**Comment by icarter09** [comment]
@DistantThunder are you still experiencing this issue?
