### ISSUE TITLE
Shutdown shortcut is gated by a setting in Power Management panel

### ISSUE THREAD

**Issue by marga-google** [linuxmint/cinnamon#5066]
Hi!

This happens at least on cinnamon 2.6 and 2.8.

There are certain shortcuts already configured for System -> Shut down, but neither those specified there nor other keybindings that the user may set trigger a shutdown when pressed.

Invoking dbus-monitor and pressing ctrl-alt-end (one of the pre-configured shortcuts), shows:

method call time=1454599395.228184 sender=:1.18 -> destination=:1.6 serial=18297 path=/org/cinnamon/SettingsDaemon/KeybindingHandler; interface=org.cinnamon.SettingsDaemon.KeybindingHandler; member=HandleKeybinding
   uint32 28
method return time=1454599395.228690 sender=:1.6 -> destination=:1.18 serial=2581 reply_serial=18297

And nothing happens.

After following the code around, I discovered that this is caused by the fact that the shortcut is given the same identifier as the power button and the power button is controlled by what the user sets in System > Power Management > When the power button is pressed.  However, this is very much non-obvious.  A user wanting to set a shortcut for shutting down is not likely going to know that they should set the actual behavior of the shortcut in a different window.

Some possibilities for fixing this:
1) Change the description of the "Shut down" entry to something like "Power off button (configured in Power Management)"
2) Have two separate entries, one for the configurable Power off and one for actual Shutdown
3) Have the default for shutdown be shutdown and not empty

Or anything along the lines that doesn't require a user to go digging around in the code to figure out that to trigger an actual shutdown they need to configure the behavior of the power off button.

Relevant code:
https://github.com/linuxmint/cinnamon-settings-daemon/blob/master/plugins/media-keys/csd-media-keys-manager.c#L1427
https://github.com/linuxmint/cinnamon-settings-daemon/blob/master/plugins/media-keys/csd-media-keys-manager.c#L1740

**Comment by mscheper** [comment]
@margamanterola: Thanks for posting this. Maybe you can help me with an issue I'm having.

In Mint 19, I've set _Power Management → Power → Extra Options → When the power button is pressed_ to _Lock Screen_, but the power button doesn't lock the screen… it doesn't do anything.

Thanks for mentioning the Ctrl+Alt+End shortcut. It's good to know, but I'd prefer to be able to lock my laptop with one button, or at least one hand. (My previous laptop had a function key for locking the screen, but my new one doesn't.)

This is on a Lenovo P51, in case that's helpful to know. Hopefully I just have to change some other setting for it to work? And I suspect this will prove your point, too. :smiley: Cheers.

**Comment by icarter09** [comment]
@margamanterola and @mscheper: either of you still experiencing this issue?
