### ISSUE TITLE
Issue when connecting to Wi-fi network with WPA2-PEAP encryption type

### ISSUE THREAD

**Issue by loremIpsum1771** [linuxmint/Cinnamon#5068]
My school's enterprise network uses the WPA2-PEAP encryption which can successfully be connected to on Windows and MacOS fine. On Linux Mint however, the network manager won't connect to the network and you can't change the encryption type within the GUI. In order to do this, I downloaded the WISC network manager which features the selection of more network options. However, even after switching to the correct encryption type, the network still couldn't be connected to. 

I finally was able to connect after following the instructions provided in the second answer for this [ask ubuntu post](http://askubuntu.com/questions/279762/cant-connect-to-wpa2-enterprise-peap) by adding another SSID file and including the necessary fields for security. 

**_Suggestions**_
1. Add options to the default network manager for changing the encryption type, DNS, etc...
2. Some how make it so that when the user tries to connect to networks with this type, the corresponding file in `/etc/NetworkManager/system-connections/`is created.

**Comment by patricktokeeffe** [comment]
It's highly unfortunate and also pretty crappy this error occurs without any kind of notice to the user. Another workaround would be to use the 'create hidden network' option. 

See also (and vote for!) [Launchpad bug 1104476](https://bugs.launchpad.net/ubuntu/+source/network-manager-applet/+bug/1104476) and the Linux Mint [roadmap](https://github.com/linuxmint/Roadmap/blob/master/Postponed.md#cinnamon) (6th item under 'networking' - it's "postponed" as I write this).

**Comment by loremIpsum1771** [comment]
So the workaround for manually creating an SSID file somewhat worked for a while, but there was still a delay from the time the computer booted to when it was able to connect to the network. I had also been advised to delete the default network manager, which I did following the instructions [here](http://xmodulo.com/disable-network-manager-linux.html). I thought that this would enable the WICD network manager to take priority so I could connect the network faster, however, this disabled me from connecting to any network. 

I tried to reinstall the default network manager, but was unsuccessful. I was advised to delete the linux mint partition and just switch back to using Ubuntu, but I like KDE better than Unity. If my Linux mint partition is now defunct, is there a way to install KDE on Ubuntu?

**Comment by anandrkris** [comment]
`but I like KDE better than Unity. If my Linux mint partition is now defunct, is there a way to install KDE on Ubuntu?`
Apologies, was this experienced in Cinnamon or KDE?

**Comment by Vahan86** [comment]
@JosephMcc, can we close this issue?

**Comment by loremIpsum1771** [comment]
Sorry, I meant Cinnamon.

**Comment by leigh123linux** [comment]
WPA2 enterprise PEAP, LEAP and TTLS are working fine here.

**Comment by loremIpsum1771** [comment]
Idk, this was like over a year ago.

**Comment by leigh123linux** [comment]
As it's working now I'm closing the issue.
