### ISSUE TITLE
Cinnamon preference with by default a confusing double negative (Disable - Off)

### ISSUE THREAD

**Issue by Pjotr123** [linuxmint/cinnamon#5069]
In order to reach this setting: Menu button - Preferences - System Settings - Section Preferences: General
- Disable compositing for full-screen windows (default: off)

This can create confusion, because it's a "double negative": Disable - Off.
Better would be:
- Enable compositing for full-screen windows (default: on)

Enable - On is immediately clear.

Just a matter of words, but "double negatives" are always confusing to read, especially when you're tired...

**Comment by Piiit** [comment]
I agree on this...
Another example is the right-click-menu within the sound-applet in Cinnamon on Mint 17.3:
- Output mute OFF (Better and simpler: Output OFF/ON without mute)
- Input mute OFF

**Comment by JosephMcc** [comment]
I tend to agree with you on this one.

**Comment by mainmachine** [comment]
+1 for this, especially with something like compositing where the effect is not always obvious. 

If vertical sync is enabled by the GPU driver, then this seems to do nothing, other than drop your FPS in full screen games if you're compositing *and* v-syncing at the driver level...

**Comment by JosephMcc** [comment]
Ok. I assigned this to myself to see about getting it improved.

**Comment by icarter09** [comment]
@JosephMcc any update on this request?

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
