### ISSUE TITLE
Taskbard graphic weirdness with VirtualBox

### ISSUE THREAD

**Issue by IgnacioFDM** [linuxmint/Cinnamon#5070]
Notice those "dark marks" on each element.

![mintgraphics](https://cloud.githubusercontent.com/assets/12388603/12873029/54911fea-cd92-11e5-9172-f308c4270795.PNG)

Fresh mint 17.3 install, no settings changed

VirtualBox 5.0.14
3D acceleration in virtualbox enabled

Host: Windows 7, i7 3820, ATI 4850 GPU
Tested ATI 6850 and Windows 10, same issue.

**Comment by JosephMcc** [comment]
It has been this way for as long a I remember. It only happens in VirtualBox and is harmless so no effort has really been put into finding out why it does it and I doubt anyone will try to fix it.
