### ISSUE TITLE
Touchpad > Tap to Click doesn't work in 2.8.6

### ISSUE THREAD

**Issue by chrismacp** [linuxmint/Cinnamon#5073]
Hi,

I just installed the latest Arch with Cinnamon 2.8.6 on a macbook pro 2015, a pretty clean install. 

When I set the Touchpad > 'Tap to click' option on, it has not affect. 

I tried using xfce also and it works fine with that so I think it's a Cinnamon bug. 

I do not have multiple 'system settings' apps like some articles mention on the web for this bug. I also checked dconf-editor and the setting seems to be enabled properly.

I'm not sure what else to to check but if you have anything you want me to check then let me know.

Thanks

**Comment by leigh123linux** [comment]
Does Arch use libinput or synaptics driver for touchpad?

post

```
synclient
```

**Comment by f2404** [comment]
@chrismacp Do you have `xf86-input-synaptics` installed?

**Comment by chrismacp** [comment]
Hi,

Thanks for getting back. I did not install xf86-input-synaptics and as it was working fine in XFCE I didn't think I needed to install anything else. 

However I have just installed xf86-input-mtrack-git (see https://wiki.archlinux.org/index.php/MacBookPro11,x#input-mtrack) and canconfirm everything is working as expected now. I think using this driver with appropriate config file renders the Cinnamon mouse/trackpad configuration menu useless as settings are configued in a config file, but hey, it works :)

**Comment by d-ee** [comment]
I've got the same issue after upgrading Debian Scratch today.
Tap does not click, however touchpad two-finger-slide does scroll, so the fingers are technically registered, just the tap is not interpreted as a click, despite being set in the settings.
`synclient` returns `Couldn't find synaptics properties. No synaptics driver loaded?`

**Comment by leigh123linux** [comment]
@d-ee If xserver-xorg-input-libinput package is installed /usr/share/X11/xorg.conf.d/90-libinput.conf overrides (prevents it loading)  /usr/share/X11/xorg.conf.d/50-synaptics.conf from the xserver-xorg-input-synaptics package.

To fix

```
ln -sf /usr/share/X11/xorg.conf.d/50-synaptics.conf /usr/share/X11/xorg.conf.d/99-synaptics-cinnamon.conf
```

renaming it to 99- prefix means it's read after 90-libinput.conf which will override libinput.

**Comment by d-ee** [comment]
@leigh123linux actually, that worked! Here the libinput was called `60-libinput.conf` but loaded after `50-snaptics.conf`.

Mouse moving feels different now, not sure if I like it, but tap works again.
When restoring my backup system i check if I was using synaptics at all.

Do you have an idea why it broke suddenly and manual interaction was necessary?

**Comment by leigh123linux** [comment]
It looks like the issue has been fixed in xorg synaptics

https://cgit.freedesktop.org/xorg/driver/xf86-input-synaptics/commit/?id=59e5db025307404fbfbc82f2fb3fe91d6a3005d7

**Comment by marga-debian** [comment]
Yeah, the synaptics config is now placed after the libinput config, so if both are present synaptics is preferred. For Debian, this is already in unstable and will be in testing in a few days time.

However, the migration to libinput needs to happen as eventually synaptics will go away.  I'll file a separate bug about this.

**Comment by leigh123linux** [comment]
@marga-debian  already filed

https://github.com/linuxmint/cinnamon-settings-daemon/issues/78

**Comment by leigh123linux** [comment]
cinnamon-seetings-daemon now has libinput support as well as synaptics.
