### ISSUE TITLE
[REQUEST] Advanced desk features

### ISSUE THREAD

**Issue by Translator5** [linuxmint/Cinnamon#5074]
Dudes thanks for Cinnamon!
Here some requests:
- fix this item on  the desk / ignore this item while sorting
- vertical alphabetical sorting is already included, 
  but where is the horizontal alphabetical sorting, v/h sort for type?
  I would like to see this two features for the next release.
Thanks for Linux Mint!

Also by the way, if there is a possibility to show the content of a folder, while not opening it please tell me in the Nemo FileManager like in Dolphin; Here is what i mean: [Linux Mint Forums](http://forums.linuxmint.com/viewtopic.php?f=90&t=206301)

**Comment by JosephMcc** [comment]
The desktop is actually handled by nemo: https://github.com/linuxmint/nemo
Please try to provide a good description of your request there.
