### ISSUE TITLE
WIFI list exceeds screen size

### ISSUE THREAD

**Issue by RalfJung** [linuxmint/Cinnamon#5075]
When there are many wifi near-by, the wifi list becomes higher than my screen. This means I cannot turn off wifi any more, and I cannot select wifis that are listed in the cut-off part.

This screenshot demonstrates the issue - it has not been cut off at the top:
![screenshot from 2016-02-09 09-59-29](https://cloud.githubusercontent.com/assets/330628/12911647/4507e922-cf14-11e5-898e-bd990f33b80f.png)

This is with cinnamon 2.8.6.

Possible duplicates: #3678, #5064 . I was nut sure though, since this is not about glitches in relation to the "more" button, it is the applet already behaving incorrectly if I do not even press that button.

**Comment by ledufff** [comment]
This bug is also present in Fedora 23 Cinnamon 2.8.6.

**Comment by JosephMcc** [comment]
Duplicate #3678
