### ISSUE TITLE
Allow CTRL-ALT-k for keyboard layout switching

### ISSUE THREAD

**Issue by th0ma7** [linuxmint/Cinnamon#5076]
Gnome finally switched to a new interface for selecting the method for switching keyboard layouts that easily allow selecting the shortcut we prefer instead of a pre-defined list.  Within gnome I can set my shortcut to CTRL-ALT-k (similar to default KDE), something which cannot be done under cinnamon.

This really is the most annoying thing for my workflow as I have to switch keyboard layout every few minutes depending of language and application needed.

Thnx in advance!

**Comment by JosephMcc** [comment]
See https://github.com/linuxmint/Cinnamon/issues/3212 and https://github.com/linuxmint/Cinnamon/issues/5615
