### ISSUE TITLE
Scrollbars: too pale/low contrast

### ISSUE THREAD

**Issue by Frank-Miller** [linuxmint/Cinnamon#5078]
Hello,

the scrollbars are too pale and have a very low contrast thus making them hard to spot.

While browsing the net one usually only uses peripheral vision. Because of the low contrast the scrollbars are hard to spot at first sight. This hampers the usability

Cheers
Frank

Distro: Linux Mint 17.3 Rosa
Desktop: Cinnamon 2.8.6

**Comment by JosephMcc** [comment]
That is a gtk theme issue and has nothing to do with Cinnamon.
