### ISSUE TITLE
System Monitor Memory Monitor Ignores Ramdisk Size

### ISSUE THREAD

**Issue by RadicalRadish** [linuxmint/Cinnamon#5079]
System Details:
Linux Kernel 3.16.0-38-generic
Linux Mint 17.2 x64 Cinnamon - Rafaela
Cinnamon 2.6.13
Nemo 2.6.7
======================

Don't know if this is a bug or not (I would class it as one). I have 16.00GB of installed memory. I permanently run a large ramdisk of 10.00GB. Whenever I look in System Monitor it indicates that I'm only using 1.3GiB of memory. Clearly this isn't correct the memory being used by the ramdisk is being totally ignored. Really needs some work done this.

**Comment by JosephMcc** [comment]
System monitor is not a Cinnamon application. It's a gnome application that's included by default in Linux Mint but we don't develop or maintain it.

**Comment by RadicalRadish** [comment]
Thanks for the response and the further info. In line with that I reported this as a bug at "Gnome Bugzilla". Report can be seen here if necessary: https://bugzilla.gnome.org/show_bug.cgi?id=761997

At the end of the discussion there the person that was dealing with the issue said: 
> OK, then this is actually fixed in GNOME 3.16. I've patched it in August 2015.
> You may want to ask your distro to backport this patch https://git.gnome.org/browse/libgtop/commit/sysdeps/linux/mem.c?id=0580b2fb2ca8fdde2031c8aba991bafac64d8dbd

So what I would like to do now is ask for this "backport" to be made into Mint, so that the bug is crushed. Could someone please tell me where/how I make this request. (I'm a newbie to Mint and still don't know my way around this bug reporting system properly.)

**Comment by JosephMcc** [comment]
Since Mint18 will be based on GNOME3.18 it should get that fix.

**Comment by RadicalRadish** [comment]
Very many thanks, Joseph. :)
