### ISSUE TITLE
Click to activate hot corners

### ISSUE THREAD

**Issue by Janne-d-Arc** [linuxmint/Cinnamon#5081]
I like the hot corners feature but I don't use them because they are too easy to activate unintentionally.

Would it be possible to add an option to activate them only after clicking on the corner?

I know there exist an option to show an icon that performs this function but the icon overlaps many other buttons or menus when I work with full-screen windows.

**Comment by Frank-Miller** [comment]
Agreed. +1 from me. The icon in the down right corner for instance overlaps with the system tray icons. See attachment.
![screenshot1293242](https://cloud.githubusercontent.com/assets/17180573/13003327/53c25bec-d175-11e5-95b0-e17f71f910fb.png)

**Comment by gordon-morehouse** [comment]
This is closely related to #1050

**Comment by Frank-Miller** [comment]
I don't think so. A click-to-activate-function is something different than a delay imho.

**Comment by gordon-morehouse** [comment]
"Closely related" does not mean "the same as."

I also linked this ticket to one that's already been self-assigned by a developer for a reason.

**Comment by Frank-Miller** [comment]
Ok, I get your point there.

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
