### ISSUE TITLE
"Startup Applications" - Add a "Run Now" Button

### ISSUE THREAD

**Issue by RadicalRadish** [linuxmint/Cinnamon#5084]
System Details:
Linux Kernel 3.16.0-38-generic
Linux Mint 17.2 x64 Cinnamon - Rafaela
Cinnamon 2.6.13
Nemo 2.6.7

Hi,

I would like to request that the "Startup Applications" dialogue window has added to it the following feature:

(1) Click on (select) a program in the listing.
(2) There is a "Run Now" button that can run the selected program immediately.

Why is this useful. This would be particularly useful if the user has added a "Custom Command". The user can test the new command immediately to see that if things run as expected. No waiting on having to reboot the system to test the command to then (perhaps) find that the Custom Command fails.

Hope this is of help.

**Comment by JosephMcc** [comment]
Why do you have to reboot to test? If it doesn't run properly in a terminal it probably isn't going to run on startup either.

**Comment by RadicalRadish** [comment]
Thanks for the response Joseph,

I agree with what you say. However, running the command in the terminal and running from Startup Applications don't always produce the same results. For example, if I double-click a script in a folder, among other choices, I have the option to "Run in Terminal". Running from Startup Applications I don't get this option and I have to reboot to check if I do or not. Kind of annoying really.

Yes, the addition I am suggesting is cosmetic but it is also useful - isn't that the kind of thing that truly distinguishes a distro as 'better than the others' (more thoughtful towards the user).

Having written what I've just written I'd, therefore, like to add another feature request for Startup Applications. Can we also have button that forces a script to "Run in Terminal" when it is launched by Startup Applications. With the addition of such a button the user can get actual visual feedback that the script is being executed on startup - because they can see it running in the terminal. So now two feature requests.

(I do realise that this kind of thing would probably not be high on the developers' list of things to do. They would though be useful so throw them in the pot for consideration.)

**Comment by JosephMcc** [comment]
The "Run now" button is implemented.
