### ISSUE TITLE
Need Monitor Rotation

### ISSUE THREAD

**Issue by gh4snow** [linuxmint/Cinnamon#5085]
Linux Mint 17.3 Cinnamon 64bit, AMD A10, two RS 230 HD 6450/7450/8450 Video Graphics Adapters, two Dell 1600x1200 Monitors. Need Landscape mode on Primary Monitor & Rotation on Secondary Monitor. Current driver only rotates primary monitor on primary adapter & not second monitor on second adapter. But if second monitor on primary adapter, it will rotate. Thus, rotation on second adapter is the issue.

**Comment by JosephMcc** [comment]
If this is a driver issue I'm not really sure how it's a Cinnamon problem. Does it work properly under other Linux desktops? It works fine here with my Nvidia GTX260 card and open source drivers.

**Comment by JosephMcc** [comment]
Closing this since it seems to be a driver issue.
