### ISSUE TITLE
Cinnamon just crashed. You are currently running in Fallback in linux mint 17.3

### ISSUE THREAD

**Issue by ypersyntelykos** [linuxmint/Cinnamon#5086]
Cinnamon just crashed. You are currently running in Fallback Mode.
this message write in 17,3 in 64 or 32 mode

my system is
operating system............ linux mint 17,3 cinnamon 32-bit
linux kernel.................... 3.19.0-32-generic
processor...................... intel core 2cpu t5550 @ 1.66ghz x2
memory......................... 3.0 gib
hard drive...................... 23.9 gb
vraphic card................... NVIDIA CORPORATION G72M [CUADRO NVS 110M/GEFORCE GO 7300]

any help ???

**Comment by dralley** [comment]
Potentially related to https://github.com/linuxmint/Cinnamon/issues/4932?

You need to specify more details.  Are you using Nvidia proprietary drivers or Noveau?  What driver version?

**Comment by ypersyntelykos** [comment]
This is the propiertary driver which i use but 17,3 crasheed
![proprietary](https://cloud.githubusercontent.com/assets/10236771/13054706/e20b102e-d413-11e5-8eca-8ec50b4219cd.jpg)

**Comment by dralley** [comment]
@ypersyntelykos Go look at https://github.com/linuxmint/Cinnamon/issues/4932, that seems to be the same issue.  You can try @mtwebster patches from that issue discussion

**Comment by ypersyntelykos** [comment]
![proprietary](https://cloud.githubusercontent.com/assets/10236771/13054981/4dabf63a-d415-11e5-9072-5b1a1994655d.jpg)
