### ISSUE TITLE
RTL problem

### ISSUE THREAD

**Issue by ttv20** [linuxmint/Cinnamon#5087]
** sorry about my broken english **
When the system is on RTL lang (arabic, hebrew, etc...)
on the desktop
when new icon added
it appear the top right corner
when new icon added - he appear on the first icon insted below him

my system:
Linux Mint 17.3

**Comment by JosephMcc** [comment]
I going to close this since it's actually an issue for Nemo and belongs here: https://github.com/linuxmint/nemo
Feel free to repost it there as we get very little feedback from users of RTL languages.
