### ISSUE TITLE
Bring back the Edge Flip feature

### ISSUE THREAD

**Issue by cranes-bill** [linuxmint/Cinnamon#5088]
Hi,
In Gnome 2 i used Compiz due to _WALL_ plugin only. A lot of Compiz features was already implemented in Cinnamon, but this one still missing. So i would like if similar function (just to drag a window from one work space to other with mouse only) can be add here!

And one more thing: after upgrade to 2.8, i lost _text preview_ over text icons. Is that a bug?

Thank you for your good work and sorry for my bad English!

**Comment by JosephMcc** [comment]
Could explain a bit how the effect works? Not familiar with the compiz feature.

The text preview on icons is going away. As of gtk3.14 it's no longer supported properly.

**Comment by cranes-bill** [comment]
Thank you for the answer!
If i try to explain, i'm afraid that might be unreadable because of my English. Maybe i will try to make a video later....
Actually, after i read [here](http://wiki.compiz.org/Plugins/Wall), i found that this plugin has some features which i didn't knew so far. So i do not need'em. I meant this one **Edge Flip Move** (i think), which switching to the next _WORKSPACE_, if a window is dragged to the screen edge. I found a bit more about that [here](https://wiki.archlinux.org/index.php/Compiz_configuration#Edge_bindings).

**Comment by JosephMcc** [comment]
Thanks. Cinnamon actually had this feature. I believe it was disabled due to not working correctly or interfering with other things like window tiling. I'm not sure a decision was ever really made on how to handle it moving forward.

**Comment by feren** [comment]
+1

**Comment by feren** [comment]
@JosephMcc A way to fix it could be to intergrate a new dconf setting + Cinnamon Settings toggle that enables such a feature to replace the 'Press Ctrl to Enable Snap Mode' and then add a 1 second delay in-between dragging a window to the side of the screen and Cinnamon switching workspaces...

**Comment by memeplex** [comment]
I think this is already done and could be closed.

Even without enabling edge flipping in the dconf editor when I drag a window against an edge after some time I get a popup explaining: use ctrl to snap, use arrow keys to shift workspace. It's not even necessary to wait for this popup. So drag towards edge + arrow keys allows to drag between workspaces. It's easy enough, integrates well with tiling and snapping and it has an explanatory popup for first timers (it worked for me!).

Maybe the gsettings option could be removed, since it seems to have no effect at all?

**Comment by JosephMcc** [comment]
Yeah, I don't see this coming back. At some point we should probably clean up the old leftovers.

**Comment by JosephMcc** [comment]
> I did not understand why this was closed

>  I don't see this coming back

There are no plans to re-implement this feature.

**Comment by memeplex** [comment]
You can *almost* do it, drag a window against the edge and then briefly press an arrow key while dragging.

**Comment by mtwebster** [comment]
You don't even need to drag to an edge.  Simply 'pick up' a window, and right/left arrow will suffice.

**Comment by memeplex** [comment]
Yes, but dragging is better sometimes when you need to more carefully
position the window in the target workspace.
