### ISSUE TITLE
Window preview/desktop overview buggy with GTK3 windows

### ISSUE THREAD

**Issue by ManuelSchneid3r** [linuxmint/Cinnamon#5090]
Much too complicated to explain. I made a [screencast](https://youtu.be/0POOw5PGuM8). Regarding the shadows I guess the preview is redrawn (intended?) but the background is not cleared before.
The desktop overview is affected too, but window overview somehow just partially.
![desktop overview](http://i.imgur.com/XO7hwIQ.jpg)
![window overview](http://i.imgur.com/GcXxdHs.jpg)

**Comment by ManuelSchneid3r** [comment]
Env: 
Archlinux
linux 4.4.1-2
cinnamon 2.8.6-1
gtk2 2.24.29-1
gtk3 3.18.7-2

**Comment by keitalbame** [comment]
Arch
file-roler 3.16.4
gedit 3.18.3

I normally have preview off on window list applet but I tried this and only had this behaviour after I opened a second window of file-roler.
After disable and enable the preview, still persists. Did not tried a reboot yet.

alt+f2 did not changed the behaviour.

Maximizing will change the preview but when change the window size, the preview returns to the point where it was when (what seems to be) opened the second window of file-roler.

Opened gedit and gnome-calculator and also shows the same issue.

GTK3/Client side decorations related!?

![2016yyy10m02-18-16d16 10 57tooltip_001](https://cloud.githubusercontent.com/assets/16195977/13147788/980e0f14-d65a-11e5-8f9a-0a1535e57577.png)

![2016yyy08m02-18-16d16 08 58tooltip_001](https://cloud.githubusercontent.com/assets/16195977/13147799/a971b1fc-d65a-11e5-9680-4b38fc9484e1.png)

**Comment by JosephMcc** [comment]
As far as I have seen it's an issue with gtk3 client side decorated windows.

**Comment by robrobinbin** [comment]
Since CSD is here to stay and plenty of applications use them nowadays, I think better support is desirable.

When zooming in on an application in "overview" (by scrolling) there is no buggy backdrop (the buggy backdrop doesn't zoom with the rest of the window). I don't know much about how cinnamon works, but maybe the "zoomy part" of the window could be used as a preview? (I you know what I mean)

**Comment by leigh123linux** [comment]
@robrobinbin 

I bet you couldn't name a dozen CSD apps!

**Comment by robrobinbin** [comment]
All the latest gnome and elementary apps do. I know mint doesn't like it (therefor they're making the x-apps) and I absolutely respect that, I would be very grateful though if cinnamon provided a more polished experience for CSD. I personally quite like it design wise. I'm running Manjaro at the moment and very frequently use the gnome archive manager (file-roller), gedit, gnome pdf-viewer (evince) and the Manjaro software manager (pamac), all off them have client side decorations.

Not that it proves anything, but I can name a dozen CSD apps on the top of my head, most of them default gnome apps though: nautilus, totem, pamac, evince, gedit, file-roller, noise, pantheon-files, gnome-(music|weather|maps|mines), pitivi

**Comment by leigh123linux** [comment]
I didn't realize that there were that many now.
I'm going to use mate apps for the fedora 25 cinnamon iso release as they are all gtk3 based,

**Comment by JosephMcc** [comment]
This shouldn't be an issue anymore. Just tested in Cinnamon4.0 and it the issue is gone.
