### ISSUE TITLE
Export all System Settings

### ISSUE THREAD

**Issue by ap-hyperbole** [linuxmint/Cinnamon#5092]
I would like to be able to export all Cinnamon settings so that when I install Linux mint on another PC I can simply import these settings and have my desktop environment look and feel exactly the same. 

Ideally this should include the option of bundling any custom themes, icons, desktop backgrounds, screen savers, anything under "System Settings".

**Comment by cranes-bill** [comment]
`dconf dump / >all-settings`
or
`dconf dump /org/cinnamon/ >cinnamon-settings`
