### ISSUE TITLE
ALT+F2 Runner does not expand variables or "~"

### ISSUE THREAD

**Issue by RossBrunton** [linuxmint/Cinnamon#5093]
The script runner that is brought up by pressing ALT+F2 does not expand environment variables (such as $USER, or the "~" home directory thing). That is, using it to run "nemo ~" or "nemo /home/$USER" will cause it to try to open a folder literally called "~" or "$USER".

Apologies if this is the wrong repo for this.
Version: Cinnamon 2.8.6

**Comment by JosephMcc** [comment]
This is the right repo but we it would be nice to keep all of the requests here: https://github.com/linuxmint/Cinnamon/issues/2366
