### ISSUE TITLE
Symplify admin tasks from simple account users

### ISSUE THREAD

**Issue by joe-13** [linuxmint/Cinnamon#5096]
I set up different accounts on my laptop (mint 17.3 cinnamon).
Sometimes I help one of my children logged on their account, which is a simple user account.
When I want to perform admin task from this account (like launch updates, copy files from my account...), I am prompted with a 'type your admin password', but since I'm not logged as the admin, I may type whatever password it doesn't work.
My kid pwd doesn't work because they're not admin. My password doesn't work because I'm not logged in as myself or as root...

Why not have the 'windows' way and ask in this case which admin account to select and then be able to type the pwd accordingly ?

**Comment by keitalbame** [comment]
Just created a test user with standard permissions and when I try to update using Update Manager, it prompts for the password from my user that have sudo permissions.

Are you sure your user have sudo permissions?

Tested this on Arch and Mint 17.3, upgraded from 17.2.

**Comment by joe-13** [comment]
Hi
No, the user has not sudo permission because I don't want them to perform admin task. 
What is abnormal, is that when you click on updates, for example, from this simple account, you are prompted with a window asking for a password. 
You should either have a message saying: 'this account is not an administrator account'  or the possibility to select an admin account to type the corresponding password from.

**Comment by keitalbame** [comment]
When a user without sudo permissions, performs some activity than needs sudo, a password prompt appears, asking for the password of the user that have sudo permissions.

Example
Standard user: test
First Admin/sudo user: useradmin
Second

When user "test" updates some packages using "Update Manager", a prompt for selecting a sudo user and respective password.

What seems to be happening is other applications are not dealing this the same way and only asking for a password.
For example, when you open "Users and groups", a password prompt appears to run "/usr/share/cinnamon/cinnamon-settings-users/cinnamon-settings-users.py".
It this case, it is not requesting to select a user, so I assume this should be the root password that is requesting. Tried with the my root password but still complains that the password is not correct.

"Software Manager" (mintinstall), "Software Sources", "Backup Tool" also does not allow to specify the sudo user and password.

So yes, administration tasks needs to be more consistent when using a non admin user.

What I think is strange is the update not asking for the admin user prompt. Below is a screenshot of that prompt.

![screenshot from 2016-02-24 15 46 39](https://cloud.githubusercontent.com/assets/16195977/13289029/c90a321a-db0e-11e5-8475-dcb08716f953.png)


Does your system have a user with admin rights?

When you mention updates, are using "Update Manager" correct?

**Comment by joe-13** [comment]
You're right. Thank you for trying. Update manager, as for Grub customizer, or Gparted ask for an admin user, so I was wrong on these ones.
But this is not consistent as you mentioned for Software manager, user and groups, software sources, backup tool... in that case, a password is requested, and if I type my admin account pwd, it says 'bad pwd', if I type the user account pwd, nothing happens.

**Comment by JosephMcc** [comment]
Closing this since it isn't a Cinnamon issue.
