### ISSUE TITLE
Duplicate 'open with' program entries

### ISSUE THREAD

**Issue by joe-13** [linuxmint/Cinnamon#5097]
When right clicking on a file, selecting 'open with', I choose 'other app'.
Then the window pops up with the default app, the recommended apps below, and other apps below.
In the other apps, I have duplicate entries, for example 16 times okular and several times (2 to 5) program from wine install (internet explorer, wine app, rundll, etc.)

**Comment by keitalbame** [comment]
I also have some duplicates and I believe they are related with them being duplicated on the menu. If you go to System Settings >> Applets >> Menu >> Open Menu Editor, you should see the same duplicated applications their.
In my case, the difference I see is the commands are slightly different (banshee and rhytmbox) and the other have the same icon (remmina and vinagre).

Maybe this was related with the previous versions that weren't properly cleaned/updated...

**Comment by joe-13** [comment]
I don't know where this comes from.
You're right, when I open the menu editor, I can see many duplicates, especially in the Apps -> Other part.
Can I delete them ?

**Comment by keitalbame** [comment]
It is better not to remove, especially if they have different commands associated.

Don't know if those commands were added by the applications itself on install/update or if is something cinnamon uses in its internals like file associations or "open with" options.

**Comment by Vahan86** [comment]
@joe-13, is this sill an issue for you with Cinnamon 3.4?

**Comment by joe-13** [comment]
Hi
yes, this is, as you can see on the window capture.
Many duplicates in the app menu when you select 'open with', and then
'choose an app'.
Thanks
JoeLe samedi 28 octobre 2017 à 16:17 +0000, Vahan Harutyunyan a écrit :

**Comment by leigh123linux** [comment]
okular has 16 desktop files hence it's listed 16 times

```
/usr/share/applications/okularApplication_chm.desktop
/usr/share/applications/okularApplication_comicbook.desktop
/usr/share/applications/okularApplication_djvu.desktop
/usr/share/applications/okularApplication_dvi.desktop
/usr/share/applications/okularApplication_epub.desktop
/usr/share/applications/okularApplication_fax.desktop
/usr/share/applications/okularApplication_fb.desktop
/usr/share/applications/okularApplication_ghostview.desktop
/usr/share/applications/okularApplication_kimgio.desktop
/usr/share/applications/okularApplication_mobi.desktop
/usr/share/applications/okularApplication_ooo.desktop
/usr/share/applications/okularApplication_pdf.desktop
/usr/share/applications/okularApplication_plucker.desktop
/usr/share/applications/okularApplication_tiff.desktop
/usr/share/applications/okularApplication_txt.desktop
/usr/share/applications/okularApplication_xps.desktop
```

And they are all called okular

```
$ grep -e Name=Okular /usr/share/applications/okularApplication_*.desktop
/usr/share/applications/okularApplication_chm.desktop:Name=Okular
/usr/share/applications/okularApplication_comicbook.desktop:Name=Okular
/usr/share/applications/okularApplication_djvu.desktop:Name=Okular
/usr/share/applications/okularApplication_dvi.desktop:Name=Okular
/usr/share/applications/okularApplication_epub.desktop:Name=Okular
/usr/share/applications/okularApplication_fax.desktop:Name=Okular
/usr/share/applications/okularApplication_fb.desktop:Name=Okular
/usr/share/applications/okularApplication_ghostview.desktop:Name=Okular
/usr/share/applications/okularApplication_kimgio.desktop:Name=Okular
/usr/share/applications/okularApplication_mobi.desktop:Name=Okular
/usr/share/applications/okularApplication_ooo.desktop:Name=Okular
/usr/share/applications/okularApplication_pdf.desktop:Name=Okular
/usr/share/applications/okularApplication_plucker.desktop:Name=Okular
/usr/share/applications/okularApplication_tiff.desktop:Name=Okular
/usr/share/applications/okularApplication_txt.desktop:Name=Okular
/usr/share/applications/okularApplication_xps.desktop:Name=Okular
```
