### ISSUE TITLE
Lock Screen on Hot Corner wont let you log back in until mouse is moved

### ISSUE THREAD

**Issue by nyeates** [linuxmint/Cinnamon#5100]
When you set a hot corner to Lock the Screen, and you keep the mouse where it is in the corner, and then log back in later - you are quickly logged in and then immediately back out again. The use-case would be that someone sets their computer as locked, they go to lunch, and then come back, not recalling that their mouse is still in the corner. They login, not thinking about it and see the below unexpected Result.

**Reproduction steps**

1. Set one of your Hot Corners to be 'Run a command'
2. Enter the command that will Lock you Screen: "cinnamon-screensaver-command --lock"
3. Put your mouse into the hot corner you set and keep it there
4. Type in your password to login, hit enter on the keyboard (dont touch mouse)

**Result**
You get logged into the desktop very quickly and then immediately the hot corner is activated again and you are locked out again.

**Expected result**
No recurrence of the Hot Corner command when you log back in from a lock screen.

**Impact**
- Small currently, as it is likely not many people are using this custom functionality.
- Larger in the future, if Lock Screen is added as a hardcoded dropdown in the UI.
- This additionally effects any other hot corner action when unlocking your desktop. If your mouse is in a corner, while screen is locked (closed lid), and you login, that hot corner will immediately be triggered.

**Comment by nyeates** [comment]
This is similar, yet fully different from Issue #920

**Comment by JosephMcc** [comment]
Linking some issues that have the same root cause.
https://github.com/linuxmint/Cinnamon/issues/1430
