### ISSUE TITLE
Scrollbar covers ratings in Available applets (online) in Arch.

### ISSUE THREAD

**Issue by Zerophase** [linuxmint/Cinnamon#5101]
The scrollbar covers the rating of applets, extensions, and desklets on Arch Linux.

![image](https://cloud.githubusercontent.com/assets/4284284/13239283/a2782768-d99e-11e5-9a02-957dbe55b1e2.png)

It effects other themes as well. On themes with thinner scrollbars the issue doesn't stand out as much.

**Comment by JosephMcc** [comment]
You need to go complain to gtk devs about this. They implement new features in gtk like these overlay scrollbars that break a lot of existing applications. I like the idea but implementing them in a way that leaves other devs using the toolkit to clean up after them sucks.

**Comment by Zerophase** [comment]
Yeah, it probably is gtk.

**Comment by leigh123linux** [comment]
@Zerophase 

In fedora I disable overlay scrollbars in the cinnamon-session package with this patch

http://pkgs.fedoraproject.org/cgit/rpms/cinnamon-session.git/tree/disable_overlay_scrollbars.patch

**Comment by Zerophase** [comment]
Thanks.
