### ISSUE TITLE
shadow problem with gnome applications in ALT-TAB menu

### ISSUE THREAD

**Issue by Dea1993** [linuxmint/Cinnamon#5102]
I'm using cinnamon 2.8.6 on archlinux, but i've a big problem with gnome applications (nautilus, gedit, ....).
in these screenshots you can see the problem.
Is this a bug or there is a way to fix this problem with gnome CSD (client side decoration)?

![schermata del 2016-02-23 13-03-05](https://cloud.githubusercontent.com/assets/5217483/13251031/f797a626-da2d-11e5-8e7f-41650f4aff01.png)
![schermata del 2016-02-23 13-03-40](https://cloud.githubusercontent.com/assets/5217483/13251030/f794a188-da2d-11e5-9e63-8ca75f87cc75.png)

thanks

**Comment by keitalbame** [comment]
Probably related with #5090

**Comment by JosephMcc** [comment]
This is the same problem as #5090
