### ISSUE TITLE
Weird transparency problem

### ISSUE THREAD

**Issue by vroni92** [linuxmint/Cinnamon#5103]
Since an update last week, I'm experiencing some weird problems with my current Linux Mint version. I've already installed all available updates, even the latest Cinnamon nightly build, but nothing I have done yet resolved the issue.
My panel doesn't show anything apart from two lighter squares for Firefox and the Guake terminal. (Although, after installing the latest nightly build, it is displayed correctly until I hover over it with the mouse.)
As far as I have experienced, the only windows that correctly displayed are Firefox (but only one window, if I open another, I can only see my background) and the Guake terminal. If I open anything else, the background is shown instead of the window. Even when I try to attach a picture here, instead of the file picker I only see a patch of my window, which makes it, sadly, quite difficult to show a picture of my problems.
Even the menu is transparent to the window beneath (Firefox or the background), I can only see the writing, and it's flashing.

I have no idea what's the problem and no idea how to resolve it. Any ideas?

**Comment by Vahan86** [comment]
@vroni92, is this still an issue for you with Cinnamon 3?

**Comment by Vahan86** [comment]
@JosephMcc, can we close the issue?
