### ISSUE TITLE
Not updated applet "power"

### ISSUE THREAD

**Issue by HileV** [linuxmint/Cinnamon#5104]
A few days ago stopped updating the applet, which shows the battery level. It brings a lot of inconvenience. I reinstalled, nothing helps. On other DE - all right. SAVE!
[https://www.youtube.com/watch?v=5wtHvJx19T0](url)

**Comment by keitalbame** [comment]
probably same issue as #4925

**Comment by JosephMcc** [comment]
Duplicate
