### ISSUE TITLE
Backlight does not light after resume from Suspend

### ISSUE THREAD

**Issue by deutrino** [linuxmint/cinnamon#5105]
## What I expect to happen
1. Suspend the machine.
2. Resume the machine.
3. The backlight functions normally.
## What actually happens
1. Suspend the machine.
2. Resume the machine.
3. The backlight will not light and brightness keys do not work. Brightness is set to 0; the unlock screen is visible on the LCD. Only a power button hold will resolve the issue.
## Relevant info
- **MacBook4,1** - Early 2008 white plastic MacBook, Core 2 Duo T8100 2.1GHz, Intel GMA X3100
- Linux macbook 4.2.0-19-generic #23~14.04.1-Ubuntu SMP Thu Nov 12 12:33:30 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
- Mint 17.3
- Cinnamon 2.8.6+rosa amd64, mdm 2.0.7+rosa amd64

Use `sudo dmidecode -s "system-product-name"` to find out your Mac version (e.g. MacBook4,1).

**Comment by bluezclouds** [comment]
This problem occurs on my laptop if brightness is reduced before putting the machine to sleep.  If brightness is set to maximum the problem does not occur and laptop resumes normally with the backlight on.  

Sony Vaio VPCF121GX
Linux Mint 17.3 Rosa
Nvidia 310M 
Nvidia Driver 340.96
Cinnamon 2.8.8

**Comment by RavetcoFX** [comment]
Does this occur with other distros such as Ubuntu as I suspect that its a kernel bug and probably has nothing to do with Mint/Cinnamon. I would try filing a bug with the Linux kernel and seeing if they can help.

**Comment by Vahan86** [comment]
@deutrino, is this still an issue for you with Cinnamon 4.2?

**Comment by claudiux** [comment]
@Vahan86 Yes. I use the `brightness-and-gamma-applet@cardsurf` applet to fix this issue.
