### ISSUE TITLE
cinnamon-settings doesn't properly disable some non-writable gsettings keys

### ISSUE THREAD

**Issue by gerow** [linuxmint/Cinnamon#5107]
I noticed this specifically with the screensaver settings window. With most settings if they are locked (and, hence, not writable) the ui will show them greyed out, but with some this isn't the case. The UI lets the user change the setting, and even close the window with the setting they desire, but the setting won't be applied and the next time they open the settings window it will revert to the original value.

This screenshot should make things abundantly clear:

![gerow-screensaver-settings](https://cloud.githubusercontent.com/assets/403962/13370125/58fe0e40-dcb4-11e5-8611-91974e143d22.png)

Here the GSettingsSwitch is appropriately rendered as greyed out because I can't write to it, but the GSettingsComboBox for the delay isn't despite the fact that I can't write to it.

Looking at the code this appears to be because we aren't binding to settings with GSettingsComboBox but instead adding custom handlers https://github.com/linuxmint/Cinnamon/blob/master/files/usr/share/cinnamon/cinnamon-settings/bin/SettingsWidgets.py#L919. I'm assuming this is a hack to get around the fact that there is no bind_with_mapping function in gir1.2-glib-2.0 (or at least I couldn't find one), which works but apparently misses the handling of writability. I haven't looked through the other SettingsWidgets but I'm guessing a few of them may have similar behavior.

**Comment by Vahan86** [comment]
@gerow, is this still an issue for you in Cinnamon 3.2?

**Comment by Vahan86** [comment]
@JosephMcc, can we close the issue?

**Comment by sharpentheaxe** [comment]
I am having a simular issue after cinnamon went into fallback mode.  Not sure why but I can not change any settings.  All the settings are grayed out.

When I run "gsettings set org.cinnamon.theme name "Railway"" I get the result "The key is not writable"

I think there is a missing file or permissions issue but I don't know where.  I have installed and reinstall cinnamon a dozen times with no resolve.

The screen shot below shows the Mouse and Touch pads settings panel grayed out.  

The themes and wallpaper will not change.

![image](https://user-images.githubusercontent.com/6506172/38677221-96db8b36-3e2b-11e8-97a5-915759962a38.png)
