### ISSUE TITLE
Cinnamon crashed when the applet executes St.Label(null)

### ISSUE THREAD

**Issue by NaruTrey** [linuxmint/Cinnamon#5108]
Сrash occurs at a similar code:
```javascript
this._myLabel = new St.Label(null);
```

.xsession-errors:
> (cinnamon:2227): Clutter-CRITICAL **: clutter_text_get_text: assertion 'CLUTTER_IS_TEXT (self)' failed

Cinnamon will not restore its work until the defective applet does not remove from the panel.

_Linux Mint 17.3
Cinnamon 2.8.6
Clutter 1.16.4_

**Comment by JosephMcc** [comment]
This needs to be fixed by the applet dev or you if it's your applet. St.Label() takes a string as an argument.
