### ISSUE TITLE
Taskbar notification icons overlap windows

### ISSUE THREAD

**Issue by WChargin** [linuxmint/Cinnamon#5110]
Okay yes I'm running a lot of things. But this is still a bug!

In this screenshot, zoom to full size and scroll to the right; note that the Chrome icon overlaps the notifications icon, and the Slack icon overlaps the users and groups icon (or whatever that is? I don't actually know).

![taskbar](https://cloud.githubusercontent.com/assets/4317806/13377301/2e40b51e-dda3-11e5-9c26-4efdbb1d8894.png)

Cinnamon 2.8.6, LM 17.3.

**Comment by keitalbame** [comment]
seems similar to #5042

**Comment by JosephMcc** [comment]
Yep it's a duplicate. Thanks for pointing it out.
