### ISSUE TITLE
Background ignores stored orientation of images (layout is always put to landscape, even if image gets shown as portrait in an image viewer application)

### ISSUE THREAD

**Issue by rapgro** [linuxmint/Cinnamon#5111]
Description of problem:
The background dialog shows all images in landscape mode, even if some of them are stored as portrait.

Version-Release number of selected component (if applicable):
n/a

How reproducible:
yes

Steps to Reproduce:
1. login to cinnamon session
2. open background settings
3. look for orientation option

Actual results:
not possible to switch between portrait and landscape orientation

Expected results:
images show in preferred orientation mode (portrait|landscape), either choosable in settings dialog or directly read from image file

Additional info:
Not sure which concrete component to blame. As a start, I report against cinnamon cause it seems to be the most general.

Downstream:
https://bugzilla.redhat.com/show_bug.cgi?id=1294217

**Comment by itzexor** [comment]
@rapgro Can you still reproduce this in the latest releases? I can't reproduce this and believe it was fixed by @clefebvre in cinnamon-desktop 3.0.2
https://github.com/linuxmint/cinnamon-desktop/commit/0a5f072befd97b6282a8cff71f0e184becf538b8

**Comment by rapgro** [comment]
I did not hear any complains for the user. Feel free to close if you can't reproduce (any more).
