### ISSUE TITLE
Alt+F4 shortcut should trigger "Shutdown-dialog" when no apps are open

### ISSUE THREAD

**Issue by Piiit** [linuxmint/Cinnamon#5112]
Feature request: "close" Cinnamon iff no apps are open and alt+f4 is pressed (or the configured shortcut for closing apps). This means, open the shutdown/suspend/... dialog.

I would like this, because I close all windows with alt+f4, when i want to shutdown the computer to see if something must be saved.... Last keystroke triggers then a close-cinnamon...

Cheers.

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.

**Comment by MaxEtMoritz** [comment]
I wanted to have the same behavior and wrote a small bash script that does something similar.
The script checks if a window is currently focused. If yes, the window is closed. If not, the shutdown dialog is opened (as opposed to no windows being open like requested here).
I put that script into a gist: https://gist.github.com/MaxEtMoritz/94e276b87dd19613070fb59ee6521f2f
The script has to be downloaded and registered as a custom keyboard shortcut with Alt+F4 assigned to it.
