### ISSUE TITLE
To slow on debian 8 to open programs

### ISSUE THREAD

**Issue by damnhalfling** [linuxmint/Cinnamon#5113]
Hi;

I have experience some slow to open programs expecialy google-chrome. But evem termila take a 5 seconds to open. 

Google-chrome take 10 seconds.

Some one know how to improve this???

Thanks

**Comment by leigh123linux** [comment]
Try faster hardware!
It might help if you actually posted something useful like your hardware specs!

**Comment by lestcape** [comment]
Use puppylinux: http://puppylinux.org/
