### ISSUE TITLE
Return behaviour for workspace switching

### ISSUE THREAD

**Issue by ManuelSchneid3r** [linuxmint/cinnamon#5114]
I often move to dedicated workspaces, e.g. my music workspace, with hotkeys, e.g. <kbd>Meta</kbd>+<kbd>4</kbd>. Generally I dont remember where I came from and have to do a complex linear search over my 4 screens after making something on that music screen. :smile: 

I really would like to have the workspace switcher to remember the last workspace and return to that one, if I activate the current workspace again, i.e. by hitting the hotkey or pressing the workspace switcher applet. Best would be, if the backend implements this, so that the hotkeys and the applet have the same behaviour.

Thanks, cinnamon is gorgeous :+1:

**Comment by jlnknz** [comment]
Ok. Here is a patch attempt to add the keybinding. 

[issue-5114.patch.txt](https://github.com/linuxmint/Cinnamon/files/748850/issue-5114.patch.txt)

I don't really see any use for adding this feature to the applet, and I would not know where to add this in its UI and in its code :)

The patch does not work: after replacing the 2 files on my system and restarting cinnamon (yes, naive approach), I try to open the keyboard application in the system settings (where you can edit the keyboard shortcuts), and it crashes. I get the following in `dmesg`.

`[ 1598.490477] traps: cinnamon-settin[4899] trap int3 ip:7ff625209a6b sp:7fffec5e4430 error:0`

Also, I don't see the new `switch-to-last-workspace` entry in dconf-editor. However, the existing keyboard shortcuts are still working.

I didn't compile the whole project and install cinnamon in a clean environment. This is probably the problem. The building process is probably doing something very smart.

Should you be interested in that feature, a little bit of guidance would be most welcome :) As you can see I have zero experience with the development environment and build processes of cinnamon.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
