### ISSUE TITLE
The battery applet freezes after a suspend [Arch Linux]

### ISSUE THREAD

**Issue by marmistrz** [linuxmint/Cinnamon#5117]
I installed Cinnamon in Arch Linux. I suspended my computer. After the suspend the battery percentage remains frozen. When I execute `r` in alt+f2 popup so as to restart Cinamon, the battery indication becomes correct. After another suspend - another applet freeze.

Nothing interesting can be found in Looking Glass

**Comment by marmistrz** [comment]
Noticed that it's discussed in the Arch Linux forum: https://bbs.archlinux.org/viewtopic.php?id=209439

**Comment by f2404** [comment]
There are open issues here: #5116, #4925
