### ISSUE TITLE
Dropbox system tray icon doesn't respond with 17.3 64 bit, cinnamon 2.8.6

### ISSUE THREAD

**Issue by johnf76** [linuxmint/Cinnamon#5118]
Originally reported here: 

https://www.dropboxforum.com/hc/en-us/community/posts/204928873-Dropbox-tray-icon-not-responding-now-totally-gone-in-Linux-Mint-17-3-Cinnamon-64-bit?page=1#community_comment_206986926

I don't know if it's actually a dropbox issue or a cinnamon issue, figured it'd be best to bring up here as well just in case.  It's a pain and did work on version <= mint 17.2.  Basically the context menu for dropbox doesn't work anymore after upgrading to 17.3.  

Here is what shows when doing a "right click", there's usually a dropbox context menu that appears where the user can edit preferences or change sync settings, now it only shows the cinnamon system tray applet menu.
![Image of cinnamon dropbox panel](https://www.dropboxforum.com/hc/user_images/6Cb0avP9oKrS-gyBbl4Sdg.png)

Here is my version of mint:
![Image of system information](https://www.dropboxforum.com/hc/user_images/FmgDLweTY6a8qn6TIOt0MA.png)

**Comment by HileV** [comment]
The eternal problem of Cinnamon....

**Comment by keitalbame** [comment]
I believe there is similiar problems with viber and telegram tray icons and is related with qt. Can't find the issue number but will check later.

**Comment by keitalbame** [comment]
Similar to #4946.

Disabling `System settings >> General >> Enable support for indicators` will display the correct behavior.

**Comment by estebanprimost** [comment]
@keitalbame Thanks, it works.

**Comment by seyyaw** [comment]
@keitalbame Thanks, it works for me too.

**Comment by lyftsoftware** [comment]
Worked for me as well, thank you.

**Comment by mmmhhhhhhh** [comment]
@keitalbame Thanks a lot, I had been looking for this for months....

**Comment by telmotrooper** [comment]
keitalbame's fix works, someone should close the issue now.

**Comment by lyftsoftware** [comment]
I respectfully disagree with closing.  The work around does correct the right click issue which is fantastic and makes dropbox manageable again.  Much thanks to @keitalbame for that!!  However, the underlying issue hasn't been addressed in cinnamon where users need to disable the option for dropbox to work.   Just my opinion, but it seems to me like it should just work given it worked just fine previously.

**Comment by mmmhhhhhhh** [comment]
Well, I believe I was too happy too soon. The dropbox applet doesn't show up when starting, I need to go to the terminal and type dropbox stop and dropbox start. Then the applet shows up. So the @keitalbam solution partially solves the problem, but not completly... unless someone could tell me if I'm doing something wrong....

**Comment by keitalbame** [comment]
To be honest, I didn't test with dropbox.
I had the same problem with telegram and viber and those are working fine, at least for now :), even after restart.

**Comment by juanluperez** [comment]
@keitalbame, disabling support for indicators solves the behavior issue but crates a new one. Systray icons for Qt programs won't work. I'm in a fresh new linux mint 17.3 install and this is what I get, I only can decide between an awful behavior or dissappearing icons...

**Comment by keitalbame** [comment]
@juanluperez what to you mean with:

> Systray icons for Qt programs won't work.

I believe you wanted to paste some screenshot but I can't see none.

Regarding the dissapearing icons, is [this](https://github.com/linuxmint/Cinnamon/issues/4946#issuecomment-165965083) what you are experiencing?

If it is, you can check the thread and try to troubleshoot the problem.

**Comment by juanluperez** [comment]
I mean that no systray icon are shown for any Qt program, ever. No Telegram systray icon. Dropbox systray icon is not shown either at startup, I have to restart it manually. And after that I cannot interact with it because I only can get right click menu with "quit this applet" and "About" options.

It doesn't matter whether I enable or disable support for indicator in general settings. After restart I got also nothing good. Now its even worse after trying to solve this.

> Regarding the dissapearing icons, is this what you are experiencing?
No, they are just not showed in first place.

Thanks for your help, by the way... :smile:

**Comment by keitalbame** [comment]
My Telegram is working fine on my Arch install, with the indicators off.

Just tested on Mint 17.3 and after disabling the indicators, it wasn't appearing on the tray.
Since its not my main laptop, it wasn't starting on boot and while I was testing, I added to Cinnamon startup (`Startup Applications`) and also disable and reenable the `"Show Tray Icon"` on Telegram Settings.

Don't know if reenabling the tray icon in Telegram settings did the trick but seems to be working fine now, opening manually or on system boot.

NOTE: Telegram also updated itself to v0.9.33.

**Comment by telmotrooper** [comment]
I don't have any problems with Telegram on Antergos (which is Arch-based) with 

> Enable support for indicators

Disabled.

**Comment by juanluperez** [comment]
@telmotrooper 
> I don't have any problems with Telegram on Antergos (which is Arch-based) with Enable support for indicators disabled.

This doesn't help to me at all.

**Comment by JosephMcc** [comment]
Closing this since the original issue is solved by turning off indicators. We may very well go back to disabling these by default in the next version of Cinnamon since it's causing so many issues. There are already plenty of open issue about the Cinnamon systray that we don't need this one as well.

**Comment by xjcl** [comment]
@keitalbame Worked! Thanks!

**Comment by juanluperez** [comment]
Yes, it works, but only sometimes!!

**Comment by ap-Codkelden** [comment]
@juanluperez wow :(
thanks for tip, watch on it.

**Comment by juanluperez** [comment]
I can tell you that Telegram systray icon is shown around half of times... Dropbox icon works many times, but not always.

**Comment by ap-Codkelden** [comment]
@juanluperez okay, I have both Telegram and Dropbox applications installed, both present for the time being.

**Comment by mmmhhhhhhh** [comment]
What I have noticed is that dropbox systray icon works fine... until a new important upgrade comes (level 1). Then, the next time I start the computer, it doesn't show up. And I have to get to the terminal and write "dropbox stop && dbus-launch dropbox sart".
It will show up until a new upgrade comes.
Don't know if this can help you to identify the problem...

**Comment by zquestz** [comment]
Simplest solution that works.

Disable the systemd dropbox service.
Setup dropbox to auto start
Open Startup Applications and enable Dropbox with a 3 second delay.
Open your terminal and run sudo chattr +i ~/.config/autostart/dropbox.desktop
This will make the autostart file read only and dropbox can't overwrite it to remove the delay. To disable auto start you will need to chattr -i the file, and then you can delete it or uncheck the startup checkbox in Dropbox.

**Comment by ciciolina** [comment]
How do you find the support indicator? my cinnamon Arch dont have this: 

System settings >> General >> Enable support for indicators

[https://i.imgur.com/4HMyx3V.png](url)
