### ISSUE TITLE
drop-down menu misplacement in gtk+ 3.19.4 or later

### ISSUE THREAD

**Issue by shuyoko** [linuxmint/Cinnamon#5119]
Drop-down menu in firefox or nemo appears at wrong place.

1. Right click. (the first menu appeared.)
2. Move the mouse cursor.
3. Left click to close the first menu.
4. Right click to open the second menu.

- Actual Result: The second menu appeared where the first menu appeared.
- Expected Result: The second menu appeared at the place of the mouse cursor.

These bugs are only reproduced in using Cinnamon, not GNOME.
see also https://bugzilla.mozilla.org/show_bug.cgi?id=1022241#c26
> some DE (Cinamon) sends expose_event to hidden popup window which predates Gtk internal logic

== Tested Environment ==
Fedora 24 developmental branch
Cinnamon 2.8.6
gtk+ 3.19.4 and 3.19.11
Firefox 45.0
Nemo 2.8.6

**Comment by vladimir-didenko** [comment]
It looks like I reported duplicate in muffin repo 

https://github.com/linuxmint/muffin/issues/224
