### ISSUE TITLE
Caps Lock doesn't toggle at login

### ISSUE THREAD

**Issue by ishmartbuoy** [linuxmint/Cinnamon#5120]
CapsLock icon (exclamation in a triangle) appears when CapsLock has been selected - at the login screen. The symbol remains even when CapsLock is toggled to off. 

Observed this on:
OS: Linux Mint 17.2 Rafaela
Kernel:Linux  3.16.0-38-generic #52~14.04.1-Ubuntu SMP

**Comment by JosephMcc** [comment]
Are you talking about the password entry in Cinnamon screensaver or the entry in the actual MDM login screen?
If it's the MDM login screen, please close this issue and move it here: https://github.com/linuxmint/mdm

**Comment by JosephMcc** [comment]
Closing due to lack of response.
