### ISSUE TITLE
More control over power management

### ISSUE THREAD

**Issue by Ocelot92** [linuxmint/Cinnamon#5122]
Why not adding a way in the settings to set when the battery is considered at critical level? The default is too low (one day the battery was low with the default value and the pc had not the time to hibernate leaving the battery to run out -> ~ 10% of battery gone forever).

I have to use dconf every time I install mint (and for every user created) and settings it from there.

PS: using battery percentage instead of time as default would be cool too maybe...

**Comment by JosephMcc** [comment]
https://github.com/linuxmint/Cinnamon/issues/4367
