### ISSUE TITLE
Sound mixer improvement

### ISSUE THREAD

**Issue by Bleuzen** [linuxmint/Cinnamon#5123]
Hi,
the only thing i hate in Mint / Cinnamon is the sound mixer.
Why? Here is an example:

I have set the master volume (and the volume of all other applications) to 30 %.
Now i start Spotify and the master volume is on 40 (because last time i used Spotify i set it to 40), during the volume of all other apps stays on 30. If i now use the "lower volume" key on my keyboard 2 times, the master volume and Spotify are on 30%. The bad thing is that the other applications are now on 23 % volume. I have to reset them to 30%, EVERY application then Spotify. If i do a mistake (not exact clicking) and i set one app to 31%, i have to reset the master volume to 30 and start again setting all apps to 30 % volume.

... same problem with VLC or other application...

I´m pretty sure that i hadn´t this problem back in the past with ubuntu. This is only in Linux Mint / Cinnamon.

My ideas to fix this:
When a application starts, the system shouldt set it´s volume to the master volume.
(Spotify want to start with 40% but the sound mixer sets it to 30 % on start)...
OR
I don´t know how i can describe it best, but:
If an app has a volume of 50% and the system master volume is on 50%, the output of this app shouldt be 25%. If the master volume is on 50% and the app volume on 100%, the output shouldt be 50%.
If the master volume is on 45% and the app volume on 100%, the output shouldt be 45%.
If the master volume is on 100% and the app volume on 60%, the output shouldt be 60%.

**Comment by ManIVIctorious** [comment]
Sounds like pulse audio isn't configured right for your needs. Check if flat-volumes is set to false. 

https://wiki.archlinux.org/index.php/PulseAudio

**Comment by BleuzenYT** [comment]
flat-volumes was already set to "no". False also doesn´t work. Here is my /etc/pulse/daemon.conf:
http://pastebin.com/xe6eAh1D
