### ISSUE TITLE
Clicking twice needs a little enhancement

### ISSUE THREAD

**Issue by rmwiseman** [linuxmint/Cinnamon#5124]
Whilst it's very handy to be able to click a file, pause, and then click it again to edit its name, there are times when this doesn't behave in what I'd consider an intuitive fashion.  Perhaps it's because I'm more used to the Windows behaviour, but for me, intuitive behaviour is: "If you click an already-selected file, you can edit its name."

This would mean that you can click a file that has already been selected using the keyboard in order to edit its name.  It would also mean that you don't have to re-click within a set period of time to edit the name.  (Currently, you have to click it, pause -- but not for too long -- and re-click.)

**Comment by JosephMcc** [comment]
This is an issue with nemo not Cinnamon. Please move it here: https://github.com/linuxmint/nemo
