### ISSUE TITLE
Window list doesn't show windows after moving one window to an other work space

### ISSUE THREAD

**Issue by fobus42** [linuxmint/Cinnamon#5126]
1- open two applications  Chrome and Phpstorm. 
2- Right click on chrome on windows list and move it to workspace 2.
3- Go to workspace 2 by using Ctrl+Alt+Right
Chrome is not display in windows list anymore. Also, some times the other applications is not listing.

It is not a specific  problem of official windows list applet of Cinnamon, because all other applets unable to display too. Except of this one : https://cinnamon-spices.linuxmint.com/applets/view/16

My system info;

myname@mycomp ~ $ uname -a
Linux mycomp 3.13.0-77-generic #121-Ubuntu SMP Wed Jan 20 10:50:42 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
myname@mycomp ~ $ cinnamon --version
Cinnamon 2.8.6
myname@mycomp ~ $ cat /etc/linuxmint/info 
RELEASE=17.3
CODENAME=rosa
EDITION="Cinnamon 64-bit"
DESCRIPTION="Linux Mint 17.3 Rosa"
DESKTOP=Gnome
TOOLKIT=GTK
NEW_FEATURES_URL=http://www.linuxmint.com/rel_rosa_cinnamon_whatsnew.php
RELEASE_NOTES_URL=http://www.linuxmint.com/rel_rosa_cinnamon.php
USER_GUIDE_URL=help:linuxmint
GRUB_TITLE=Linux Mint 17.3 Cinnamon 64-bit

myname@mycomp ~ $ gnome-session --version
gnome-session 3.9.90

**Comment by mtwebster** [comment]
This appears fixed in git master (probably because of this https://github.com/linuxmint/Cinnamon/commit/8ebe48fff19e32eea17f63dae7fb20da6655c4ec)

**Comment by fobus42** [comment]
@mtwebster  Thanks for your help.
I have download and overwrite the files but now it doesn't work anymore. What is the best way to update it?
