### ISSUE TITLE
Cinnamon does not detach windows in firefox

### ISSUE THREAD

**Issue by timmie** [linuxmint/Cinnamon#5127]
The recent Cinnamon version do not allow to detach the print window from the main Firefox window.
Rather, the Firefox window moves around together with the small print dialogue around.

Reproduce:

1. Open Firefox
1. Press CTRL+P
1.  Move the dialogue that opens around
1. observe that the main application window also moves

The expected behaviour, like in all other programs (inclusive Thunderbird)

Thanks.

**Comment by mtwebster** [comment]
open Cinnamon Settings -> Windows, behavior tab, window focus, turn off "attach dialog windows to the parent window"
