### ISSUE TITLE
Changing margin-from-top-edge-of-screen #notification css property in theme not working

### ISSUE THREAD

**Issue by piotrekkr** [linuxmint/Cinnamon#5130]
I'm trying to change position of notification popup like here http://www.webupd8.org/2012/06/how-to-change-notifications-position-in.html . But adding or changing `margin-from-top-edge-of-screen` has no effect at all. In contrast changing `margin-from-right-edge-of-screen` works fine.

I'm using Linux Mint 17.3 with `Linux Mint` theme and my #notifications looks like this:
    
    #notification {
    font-size: 8.5pt;
    border-radius: 10px 10px 10px 10px;
    border: 2px solid rgba(214,214,214,0.5);
    background-gradient-direction: vertical;
    background-gradient-start: rgba(66,66,66,0.9);
    background-gradient-end: rgba(55,55,55,0.9);
    padding: 8px 8px 8px 8px;
    spacing-rows: 10px;
    spacing-columns: 10px;
    margin-from-right-edge-of-screen: 80px;  
    margin-from-top-edge-of-screen: 350px;
    width: 34em;
    color: white;    
    /* The px are a temporary fix until get_theme_node() can return raw numbers. */
    opacity:255px;
    mouseover-opacity:96px
    }

Any idea why changing `margin-from-top-edge-of-screen` has no effect?

**Comment by JosephMcc** [comment]
That's because margin-from-top-edge-of-screen isn't a real property. There is no such thing so Cinnamon is just ignoring it. The post you pointed to is really old. Things have likely changed since then.

**Comment by piotrekkr** [comment]
Ok so is there a way to move this popup so it is not over minimize/maximize/close buttons? It's really annoying to place popups in right top corner of screen...

**Comment by JosephMcc** [comment]
Closing this since the the original issue is about a property that doesn't even exist and we have other open issues about being able to move notifications.

**Comment by kwa** [comment]
(saving for posterity)
For others wanting to make a change given
```
$ cinnamon --version
Cinnamon 5.2.7
```
`vim /usr/share/cinnamon/js/ui/messageTray.js`
In my version: line 955 and 959 are changed and I have marked them with "THIS IS THE CHANGE"

```
  _showNotification: function() {
        this._notification = this._notificationQueue.shift();
        if (this._notification.actor._parent_container) {
            this._notification.actor._parent_container.remove_actor(this._notification.actor);
        }

        this._notificationBin.child = this._notification.actor;
        this._notificationBin.opacity = 0; 

        let monitor = Main.layoutManager.primaryMonitor;
        let topPanel = Main.panelManager.getPanel(0, 0);
        let bottomPanel = Main.panelManager.getPanel(0, 1);
        let rightPanel = Main.panelManager.getPanel(0, 3);
        let topGap = 10;
        let bottomGap = 10;
        let rightGap = 0; 

        if (rightPanel) {
            rightGap += rightPanel.actor.get_width();
        }

        if (!this.bottomPosition) {
            if (topPanel) {
                topGap += topPanel.actor.get_height();
            }
            this._notificationBin.y = /* THIS IS THE CHANGE */ (monitor.height / 2)  + monitor.y + topGap; // Notifications appear from here (for the animation)
        }

        let margin = this._notification._table.get_theme_node().get_length('margin-from-right-edge-of-screen');
        this._notificationBin.x = monitor.x + /* THIS IS THE CHANGE */ monitor.width/2 - this._notification._table.width - margin - rightGap;
        if (!this._notification.silent || this._notification.urgency >= Urgency.HIGH) {
            Main.soundManager.play('notification');
        }
        if (this._notification.urgency == Urgency.CRITICAL) {
            Main.layoutManager._chrome.modifyActorParams(this._notificationBin, { visibleInFullscreen: true });
        } else {
            Main.layoutManager._chrome.modifyActorParams(this._notificationBin, { visibleInFullscreen: false });
        }
        this._notificationBin.show();

```

The result is that the notification is placed approximately in the center of the screen.
