### ISSUE TITLE
Left Click Doesn't Work On Panel

### ISSUE THREAD

**Issue by maxchill** [linuxmint/Cinnamon#5133]
Using all the latest Arch packages as of time of posting.  Left click isn't working on anything in the panel.  Right click does however work.

Note that I'm using a Lenovo Cardbon X1, with touch screen and HiDPI.  I've disabled the touch screen to help isolate the problem.  I'm wondering if HiDPI resolution has something to do with it.

If I open an application using Alt+F2, clicking in the open application functions as expected.

Any suggestions for debugging would be appreciated.

**Comment by maxchill** [comment]
Apparently panel edit mode was enabled, and I didn't know.  I'm new to cinnamon.  Perhaps this could be indicated more clearly?

**Comment by mtwebster** [comment]
It's generally pretty clear - the panels change appearance, usually drastically, to highlight the different panel zones, and show that you're in edit mode.  My guess is you are using some broken, old theme.
