### ISSUE TITLE
VMware application menu is visible under Gnome but not Cinnamon

### ISSUE THREAD

**Issue by TrickyHarry** [linuxmint/Cinnamon#5134]
I have VMware 12.1.0 installed and when I use my favourit desktop Cinnamon, the top level menu appears as white text on white back-ground - operational but not visible.
When I login via Gnome3, I see the menu items.
  - I am accessing the same application via 2 different desktops on Fedora 22.

I am not sure how to approach this problem.

VMware 12.0.1 and previous did not have this problem on Cinnamon. I had VMware v11, v12.0.1 menu's working well.
v12.0.1 - I believe ...
![selection_529](https://cloud.githubusercontent.com/assets/1596448/13793040/d0371010-eaec-11e5-9c14-5b58733b6134.png)
The following is v12.1.0 where the top level menu is not displayed.
![selection_497](https://cloud.githubusercontent.com/assets/1596448/13793064/ffaca8c8-eaec-11e5-85fc-467c7b98616f.png)

Here is the VMware application when I use the Standard Gnome Desktop
![selection_533_gnome3](https://cloud.githubusercontent.com/assets/1596448/13807891/76efcc08-eb5b-11e5-8830-3ef3e2eda77c.png)

**Comment by leigh123linux** [comment]
This is a gtk theme issue, try another theme!

![screenshot from 2016-03-17 10-09-53](https://cloud.githubusercontent.com/assets/1299302/13842927/a64ce4c2-ec28-11e5-8033-22fe65a374b3.png)

**Comment by TrickyHarry** [comment]
Thanks Leigh,

It was not a desktop theme but a "Control Theme" that required a change. Now I can see the menus.
 - I can probably pick a suitable control, now that I know the problem.
