### ISSUE TITLE
Cinnamon Menu applet is separated from the panel and moved to the top of the screen.

### ISSUE THREAD

**Issue by bagjunggyu** [linuxmint/Cinnamon#5135]
Please, see the screenshot, 
Cinnamon Menu applet is separated from the panel and moved to the top of the screen.
I turned on mouse hover, but it happens whether it is on or off, whenever I press the Super key.
It is a Rosa Cinnamon. 
Before this happened, I removed Menu applet by fault, so that I restored applets to default.
and after that process, it happened.
after the logout & login, it's gone.
![2016-03-17 04 55 55](https://cloud.githubusercontent.com/assets/2834031/13826820/c99243b8-ebfc-11e5-9ac8-3ea7f195e456.png)

**Comment by bagjunggyu** [comment]
But, Idea is , what about cinnamon menu pops up at the position where the cursor is. 
wherever the cursor is, cinnamon menu pops up there, beside of the cursor, I think it would be more convenient to access the menu especially for the laptop users who use the track pad.

**Comment by HileV** [comment]
No, it's bad idea. I have notebook and in this situation - all ok.

**Comment by Vahan86** [comment]
@bagjunggyu, is this still an issue for you in Cinnamon 3?

**Comment by bagjunggyu** [comment]
@Vahan86 Yes, it still happens to.
![2016-11-28 04-17-50](https://cloud.githubusercontent.com/assets/2834031/20651101/d3009b2c-b521-11e6-9008-de965ae56289.png)

**Comment by bagjunggyu** [comment]
Summary of reproduce
* Remove Menu applet
* Add Menu applet from Cinnamon-Settings
* Press Super key to check

**Comment by Odyseus** [comment]
Hello, @bagjunggyu.

This is a know issue with some applets that have key-bindings. When you remove the applet, the key-binding will still open the menu of the recently removed applet.

This already has been resolved on the menu applet that comes with CInnamon 3.2.x.

**Comment by JosephMcc** [comment]
This should be fixed already in the next Cinnamon version.
