### ISSUE TITLE
Turning of animations for specific apps

### ISSUE THREAD

**Issue by marmistrz** [linuxmint/Cinnamon#5137]
Cinnamon looks very well, and it wouldn't if not for the animations. But sometimes the animations are irritating, e.g. when hiding/unhiding the Guake terminal.

It'd be great if there were an option to disable animations on a per-app basis.

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
