### ISSUE TITLE
Toggle for GTK3 Dark Themes in Cinnamon theme Settings

### ISSUE THREAD

**Issue by Term1nal** [linuxmint/Cinnamon#5138]
Not sure why I need to install gnome-tweak-tool and all of its prerequisite dependencies to flip a toggle switch to allow dark GTK themes. Could this be added to Cinnamon's theme settings page? Thanks.

**Comment by JosephMcc** [comment]
For now you don't need to install gnome-tweak-tool to do this. Add a file named setting.ini in ~/.config/gtk-3.0/
Then add the following line and save:
`gtk-application-prefer-dark-theme=true`

**Comment by JosephMcc** [comment]
This is now implemented in Cinnamon in the theme settings. Your gtk theme needs to support it for it work.
