### ISSUE TITLE
Cannot edit menu item if it's icon has been deleted

### ISSUE THREAD

**Issue by aembleton** [linuxmint/Cinnamon#5139]
To reproduce:

1. Open the menu editor
2. Create a New Item and set it's icon
3. Delete or rename the icon on the file system
4. In the menu editor, select the new item and click on Properties

Notice how clicking on Properties won't open the dialog.  Restoring the icon will allow you to open it.

**Comment by JosephMcc** [comment]
As it turns out this is probably the same as: https://github.com/linuxmint/Cinnamon/issues/5062
