### ISSUE TITLE
Cursor stuck in loading animation

### ISSUE THREAD

**Issue by Marcel-Robitaille** [linuxmint/Cinnamon#5142]
Sometimes my cursor gets stuck with the loading animation but everything else works fine.

Linux Mint 17.2. Cinnamon 2.6.13.

**Comment by JosephMcc** [comment]
Is some app busy when this happens? Does it get stuck like that or does it eventually go back to normal on it's own?

**Comment by Marcel-Robitaille** [comment]
One time I noticed it I had clicked the sublime text launcher. Since I already had st open, It didn't open another window and I got the cursor. Eventually it fixes itself.

**Comment by JosephMcc** [comment]
I get this with sublime as well. I don't think it's a problem with Cinnamon.

**Comment by Marcel-Robitaille** [comment]
Ah ok thanks
