### ISSUE TITLE
Awesome!!!

### ISSUE THREAD

**Issue by robinhood2014** [linuxmint/Cinnamon#5143]
Where do I post praise for Cinnamon? If I'm in the right spot, I'd just like to say to the developers, you guys have really done an awesome job! I'm running Cinnamon on Arch Linux, and I have to say, next to KDE, Cinnamon is the most complete Linux desktop environment available. Great job!!

**Comment by JosephMcc** [comment]
I'm going to close this since it isn't actually an issue but thank you, it appreciated.
