### ISSUE TITLE
MintMenu will not disappear . .

### ISSUE THREAD

**Issue by ACinnamonUserInUK** [linuxmint/Cinnamon#5144]
. . when an area outside it is clicked, or when escape pressed. I had to restart Cinnamon to get it to disappear.

The CPU was under heavy load at the time of the freeze - which may be relevant.

CInnamon 2.8.7, on Mint 17.3 x64.

**Comment by JosephMcc** [comment]
We can't do much with this. Any idea how to reproduce? Anything that might be relevant in .xsession-errors?

**Comment by ACinnamonUserInUK** [comment]
Thanks. I haven't looked at the log file before, and it contains much that, I imagine, it shouldn't. Here is some of it (with lines of space indicating elisions):
`
cinnamon-session[2592]: EggSMClient-WARNING: t+0.05475s: Invalid Version string '0.9.4' in /home/[username redacted]/.config/autostart/xfce-autostart-wm.desktop

gnome-keyring-daemon: insufficient process capabilities, unsecure memory might get used
gnome-keyring-daemon: insufficient process capabilities, unsecure memory might get used
gnome-keyring-daemon: insufficient process capabilities, unsecure memory might get used

cinnamon-session[2592]: WARNING: t+3.39179s: Failed to start app: Unable to start application: Failed to execute child process "recollindex" (No such file or directory)
Cjs-Message: JS LOG: About to start Cinnamon

** (nm-applet:3204): CRITICAL **: nm_secret_agent_register: assertion 'priv->registered == FALSE' failed
nm-applet-Message: using fallback from indicator to GtkStatusIcon
Initializing folder-color-switcher extension...
Initializing nemo-dropbox 2.8.0


(nemo:3203): Gdk-WARNING **: gdk_window_set_icon_list: icons too large

** (nemo:3203): WARNING **: Can not calculate _NET_NUMBER_OF_DESKTOPS

** (nemo:3203): WARNING **: Can not get _NET_WORKAREA

** (nemo:3203): WARNING **: Can not determine workarea, guessing at layout
St-Message: cogl npot texture sizes SUPPORTED
Cjs-Message: JS LOG: Cinnamon started at Wed Mar 23 2016 21:23:42 GMT+0000 (GMT)
[94m[INFO 21:23:39.934542][0m [synapse-main:266] Starting up...
[94m[INFO 21:23:40.406243][0m [synapse-main:208] Binding activation to <Control>space
[94m[INFO 21:23:40.675017][0m [view-base:251] Screen is composited.
[94m[INFO 21:23:40.676808][0m [controller:56] Using gtk-im-context-simple input method.
[93m[WARN 21:23:40.770653][0m [desktop-file-service:343] Desktop session type is not recognized, assuming GNOME.
[93m[WARN 21:23:41.200397][0m [desktop-file-service:508] Key file contains line 'application/vnd.ms-word;' which is not a key-value pair, group, or comment
[93m[WARN 21:23:41.241917][0m [desktop-file-service:196] Unable to create AppInfo for /usr/share/applications/kde4/knetattach.desktop
[93m[WARN 21:23:41.277865][0m [desktop-file-service:72] X-Cinnamon is not understood
[93m[WARN 21:23:41.290084][0m [desktop-file-service:72] X-Cinnamon is not understood
[93m[WARN 21:23:41.290612][0m [desktop-file-service:72] X-Cinnamon is not understood
[93m[WARN 21:23:41.295594][0m [desktop-file-service:72] X-Cinnamon is not understood
[93m[WARN 21:23:41.296272][0m [desktop-file-service:72] X-Cinnamon is not understood
[93m[WARN 21:23:41.301991][0m [desktop-file-service:72] X-Cinnamon is not understood
[93m[WARN 21:23:41.306046][0m [desktop-file-service:72] X-Cinnamon is not understood
[93m[WARN 21:23:41.321159][0m [desktop-file-service:72] X-Cinnamon is not understood
[93m[WARN 21:23:41.321923][0m [desktop-file-service:72] X-Cinnamon is not understood
[93m[WARN 21:23:41.322628][0m [desktop-file-service:72] X-Cinnamon is not understood
[93m[WARN 21:23:41.323348][0m [desktop-file-service:72] X-Cinnamon is not understood
[93m[WARN 21:23:41.337969][0m [desktop-file-service:72] X-Cinnamon is not understood
[93m[WARN 21:23:41.345866][0m [desktop-file-service:72] X-Cinnamon is not understood
[93m[WARN 21:23:41.346610][0m [desktop-file-service:72] X-Cinnamon is not understood
[93m[WARN 21:23:41.347324][0m [desktop-file-service:72] X-Cinnamon is not understood
[93m[WARN 21:23:41.354007][0m [desktop-file-service:72] X-Cinnamon is not understood
[93m[WARN 21:23:41.356698][0m [desktop-file-service:72] X-Cinnamon is not understood
[93m[WARN 21:23:41.366095][0m [desktop-file-service:72] X-Cinnamon is not understood
[93m[WARN 21:23:41.372956][0m [desktop-file-service:72] X-Cinnamon is not understood
[93m[WARN 21:23:41.378078][0m [desktop-file-service:72] X-Cinnamon is not understood
[93m[WARN 21:23:41.378781][0m [desktop-file-service:72] X-Cinnamon is not understood
[93m[WARN 21:23:41.382606][0m [desktop-file-service:72] X-Cinnamon is not understood
[93m[WARN 21:23:41.402194][0m [desktop-file-service:72] X-Cinnamon is not understood
[93m[WARN 21:23:41.410120][0m [desktop-file-service:72] X-Cinnamon is not understood
[93m[WARN 21:23:41.410857][0m [desktop-file-service:72] X-Cinnamon is not understood
[93m[WARN 21:23:41.411555][0m [desktop-file-service:72] X-Cinnamon is not understood
[93m[WARN 21:23:41.412335][0m [desktop-file-service:72] X-Cinnamon is not understood
[93m[WARN 21:23:41.413939][0m [desktop-file-service:72] X-Cinnamon is not understood
[93m[WARN 21:23:41.432402][0m [desktop-file-service:72] X-Cinnamon is not understood
[93m[WARN 21:23:41.450473][0m [desktop-file-service:196] Unable to create AppInfo for /usr/share/applications/mintinstall-kde.desktop
[93m[WARN 21:23:41.521675][0m [desktop-file-service:72] X-Cinnamon is not understood
[93m[WARN 21:23:41.579791][0m [desktop-file-service:196] Unable to create AppInfo for /usr/share/applications/evolution-calendar.desktop
[93m[WARN 21:23:41.700535][0m [desktop-file-service:196] Unable to create AppInfo for /usr/share/applications/unity-activity-log-manager-panel.desktop
[93m[WARN 21:23:42.041845][0m [desktop-file-service:196] Unable to create AppInfo for /usr/share/applications/brasero-nautilus.desktop
[93m[WARN 21:23:42.118002][0m [desktop-file-service:196] Key file contains key 'Hidden' which has a value that cannot be interpreted.
[93m[WARN 21:23:42.159859][0m [desktop-file-service:72] X-Cicopying user files


[2016-03-23T21:23:44] [ERR] hddtemp: failed to open connection.
[2016-03-23T21:23:44] [ERR] atasmart: sk_disk_open() failure: /dev/sda.
cat: /home/[username redacted]/.urserver/urserver.pid: No such file or directory
starting server
[31m[21:23:43.826689 Warning][0m desktop-file-service.vala:485: Key file contains line 'application/vnd.ms-word;' which is not a key-value pair, group, or comment
[31m[21:23:43.986597 Warning][0m [35m[DesktopFileInfo][0m Unable to create AppInfo
[31m[21:23:44.042878 Warning][0m desktop-file-service.vala:101: X-Cinnamon is not understood
[31m[21:23:44.048113 Warning][0m desktop-file-service.vala:101: X-Cinnamon is not understood
[31m[21:23:44.072676 Warning][0m desktop-file-service.vala:101: X-Cinnamon is not understood
[31m[21:23:44.086381 Warning][0m desktop-file-service.vala:101: X-Cinnamon is not understood
[31m[21:23:44.090267 Warning][0m desktop-file-service.vala:101: X-Cinnamon is not understood
[31m[21:23:44.102743 Warning][0m desktop-file-service.vala:101: X-Cinnamon is not understood
[31m[21:23:44.111297 Warning][0m desktop-file-service.vala:101: X-Cinnamon is not understood
[31m[21:23:44.129151 Warning][0m desktop-file-service.vala:101: X-Cinnamon is not understood
[31m[21:23:44.145341 Warning][0m desktop-file-service.vala:101: X-Cinnamon is not understood
[31m[21:23:44.146338 Warning][0m desktop-file-service.vala:101: X-Cinnamon is not understood
[31m[21:23:44.170047 Warning][0m desktop-file-service.vala:101: X-Cinnamon is not understood
[31m[21:23:44.170893 Warning][0m desktop-file-service.vala:101: X-Cinnamon is not understood
[31m[21:23:44.175419 Warning][0m desktop-file-service.vala:101: X-Cinnamon is not understood
[31m[21:23:44.184462 Warning][0m desktop-file-service.vala:101: X-Cinnamon is not understood
[31m[21:23:44.202336 Warning][0m desktop-file-service.vala:101: X-Cinnamon is not understood
[31m[21:23:44.213871 Warning][0m desktop-file-service.vala:101: X-Cinnamon is not understood
[31m[21:23:44.214533 Warning][0m desktop-file-service.vala:101: X-Cinnamon is not understood
[31m[21:23:44.225759 Warning][0m desktop-file-service.vala:101: X-Cinnamon is not understood
[31m[21:23:44.234624 Warning][0m desktop-file-service.vala:101: X-Cinnamon is not understood
[31m[21:23:44.242559 Warning][0m desktop-file-service.vala:101: X-Cinnamon is not understood
[31m[21:23:44.254177 Warning][0m desktop-file-service.vala:101: X-Cinnamon is not understood
[31m[21:23:44.269781 Warning][0m desktop-file-service.vala:101: X-Cinnamon is not understood
[31m[21:23:44.270591 Warning][0m desktop-file-service.vala:101: X-Cinnamon is not understood
[31m[21:23:44.272062 Warning][0m desktop-file-service.vala:101: X-Cinnamon is not understood
[31m[21:23:44.284327 Warning][0m desktop-file-service.vala:101: X-Cinnamon is not understood
[31m[21:23:44.306419 Warning][0m desktop-file-service.vala:101: X-Cinnamon is not understood
[31m[21:23:44.321404 Warning][0m desktop-file-service.vala:101: X-Cinnamon is not understood
[31m[21:23:44.322322 Warning][0m desktop-file-service.vala:101: X-Cinnamon is not understood
[31m[21:23:44.334800 Warning][0m desktop-file-service.vala:101: X-Cinnamon is not understood
[31m[21:23:44.381929 Warning][0m [35m[DesktopFileInfo][0m Unable to create AppInfo
[31m[21:23:44.570259 Warning][0m desktop-file-service.vala:101: X-Cinnamon is not understood
[31m[21:23:44.686402 Warning][0m [35m[DesktopFileInfo][0m Unable to create AppInfo
[31m[21:23:44.877897 Warning][0m [35m[DesktopFileInfo][0m Unable to create AppInfo
[31m[21:23:45.306568 Warning][0m [35m[DesktopFileInfo][0m Unable to create AppInfo
[31m[21:23:45.472530 Warning][0m [35m[DesktopFileInfo][0m Key file contains key 'Hidden' which has a value that cannot be interpreted.
[31m[21:23:45.642513 Warning][0m desktop-file-service.vala:101: X-Cinnamon is not understood
[31m[21:23:45.687758 Warning][0m desktop-file-service.vala:101: X-Geeqie is not understood
[31m[21:23:45.851241 Warning][0m desktop-file-service.vala:101: X-Cinnamon is not understood
[31m[21:23:45.851881 Warning][0m desktop-file-service.vala:101: X-Cinnamon is not understood
[31m[21:23:45.854263 Warning][0m desktop-file-service.vala:101: X-Cinnamon is not understood
[31m[21:23:45.871327 Warning][0mskipping manager
Unknown configuration setting `gamma-night'.

Cjs-Message: JS WARNING: [/home/[username redacted]/.local/share/cinnamon/applets/capture@rjanja/applet.js 1279]: anonymous function does not always return a value
Cjs-Message: JS WARNING: [/home/[username redacted]/.local/share/cinnamon/applets/capture@rjanja/applet.js 1427]: anonymous function does not always return a value
Cjs-Message: JS WARNING: [/home/[username redacted]/.local/share/cinnamon/applets/capture@rjanja/applet.js 1546]: anonymous function does not always return a value
Cjs-Message: JS WARNING: [/home/[username redacted]/.local/share/cinnamon/applets/capture@rjanja/applet.js 1579]: anonymous function does not always return a value
Cjs-Message: JS WARNING: [/home/[username redacted]/.local/share/cinnamon/applets/places-with-terminal@mtwebster/applet.js 50]: assignment to undeclared variable button
Cjs-Message: JS LOG: network applet: Cannot find connection for active (or connection cannot be read)
openGL version 2.1 Mesa 11 detected (GL Cogl Driver)
MetaSyncRing disabled: couldn't find required GL extensions, or the minimum safe openGL version was not met
nm-applet-Message: moving back from GtkStatusIcon to indicator
failed to create drawable
sudo: no tty present and no askpass program specified

** (nemo:3203): WARNING **: Can not calculate _NET_NUMBER_OF_DESKTOPS

** (nemo:3203): WARNING **: Can not get _NET_WORKAREA

** (nemo:3203): WARNING **: Can not determine workarea, guessing at layout

** (nemo:3203): WARNING **: Can not calculate _NET_NUMBER_OF_DESKTOPS

** (nemo:3203): WARNING **: Can not get _NET_WORKAREA

** (nemo:3203): WARNING **: Can not determine workarea, guessing at layout
Cjs-Message: JS LOG: network applet: Found connection for active

** (zeitgeist-datahub:3804): WARNING **: zeitgeist-datahub.vala:229: Unable to get name "org.gnome.zeitgeist.datahub" on the bus!
mintUpdate: no process found

(mintUpdate.py:3813): libglade-WARNING **: unknown attribute `swapped' for <signal>.

`
There's some stuff for me to work on in there!

**Comment by Vahan86** [comment]
@ACinnamonUserInUK, is this still an issue for you with Cinnamon 3.2/3.4?

**Comment by ACinnamonUserInUK** [comment]
No, I don't think so; I haven't seem the problem recently. Still, very recently I replaced the Mint Menu with the applet 'CinnVIIStarkMenu'. Now, I've heard you are redesigning the Mint Menu. You could do worse that make use of the code in that applet.

Thanks for asking.
