### ISSUE TITLE
[Feature request] Make cinnamon menu available for the plank dock.

### ISSUE THREAD

**Issue by mabod** [linuxmint/Cinnamon#5146]
Hi

I am using plank as a dock for my most common applications. The cinnamon panel is on auto-hide so that I rarely see it. I would like to add the cinnamon menu to the plank dock. https://launchpad.net/plank
Can you support this? It would allow me to basically get rid of the cinnamon panel.

By the way, my main reason for using the plank dock is actually that I want to have a vertically oriented dock/panel which cinnamon is unfortunately not supporting.

**Comment by lestcape** [comment]
There are a serious work for get vertical panels here: https://github.com/linuxmint/Cinnamon/pull/4996

In general, a native component of a desktop is not for an specific external app. Is the external app in all case, which should be adapted to the desktop. This without enter on the fact that is complex to not say impossible integrate different applications technologies.

I think, will be several time more easy, make native dock to cinnamon than think of what you want.

**Comment by mabod** [comment]
I was more thinking in the way like the xfce whisker menu is supporting docks like plank or cairo. If you execute "xfce4-popup-whiskermenu -p" it will open a whisker menu at the position of the mouse cursor. Would it be possible ask the cinnamon menu to do exactly that, triggered by a small app like for example cinnamon-popup-menu? The regular menu can sit in the cinnamon panel which is on autohide. cinnamon-popup-menu, when executed, sends a signal to the menu to show up at the position of the mouse cursor.

**Comment by lestcape** [comment]
That's is currently possible for all popupmenu. Probably, a more easy way to do that can be added in a generic way to all popupmenu, but in all case will be the external app who need to invoke that and I think will also a problem handled the difference of the theme representation. In fact you can add a cinnamon extension to control the popup menu to be open where you want, then you can use it over DBus, Gsettings...

**Comment by lestcape** [comment]
Maybe this can clarify you, that you can do what you want with cinnamon and Gnome shell, from a "command-line".

http://glx-dock.org/ww_page.php?p=Cairo-Dock%20and%20Gnome-Shell&lang=en#1-%20Remove%20the%20dash
http://blog.fpmurphy.com/2012/02/d-bus-cinnamon-and-the-gnome-shell.html

https://github.com/linuxmint/Cinnamon/blob/master/js/ui/cinnamonDBus.js#L20

**Comment by mabod** [comment]
Thank you for this info. That looks like that a simple python script would do the trick. But I know too little about dbus etc. to get this going. Not to mention that I am not a programmer at all ;-) Would you mind to provide a few more hints how to activate the menu at a given position? I know some python, perl or bash to try to implement it on my own.

**Comment by lestcape** [comment]
As I say, is not easy (only possible), sorry. The steps could be, create a js script ( You will run the script using eval, so ofcourse you can do all this.
) where:
1- Locate the menu instance using the AppletManager instance for Main.
2- Override the shiftPosition function (injecting code inside the actor instance). The code is for provide the position where the menu need to be opened. Instead override a higher function or create a new one for provide a complete algorithm to open the menu in a dynamic coordinate as a parameter.
3- Call the function with the required values.
4- Return the function to the original state if you override one.
Then call the cjs script using the eval function when you need to open the menu.

Good luck.

**Comment by lestcape** [comment]
To open the menu in a coordinate see this: https://github.com/linuxmint/Cinnamon/blob/master/js/ui/popupMenu.js#L2143

So: https://github.com/linuxmint/Cinnamon/blob/master/js/ui/boxpointer.js#L382

then: https://github.com/linuxmint/Cinnamon/blob/master/js/ui/boxpointer.js#L395

and ofcourse: https://github.com/linuxmint/Cinnamon/blob/master/js/ui/boxpointer.js#L506

The solution: https://github.com/linuxmint/Cinnamon/blob/master/js/ui/boxpointer.js#L519

**Comment by JosephMcc** [comment]
Sorry, but I just don't see this happening.
