### ISSUE TITLE
Onscreen drawing

### ISSUE THREAD

**Issue by luria** [linuxmint/Cinnamon#5147]
Hi there.
Could it be possible to have the compiz desktop's "annotation" feature?
I mean a simple way to draw on screen for highlighting areas. As a teacher, it would really help a lot to point focus on certain things on my projected desktop. I've tried Ardesia but seems to conflict with cinnamon and its way too complicated.
Thanks for your time!

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.

**Comment by xahon** [comment]
@JosephMcc Hi. Any updates?
