### ISSUE TITLE
Spotify does not show up in window list

### ISSUE THREAD

**Issue by Nihlus** [linuxmint/Cinnamon#5148]
When starting the latest version of Spotify, the window does not get a button on the task bar, resulting in that you lose the window if you minimize it. If Cinnamon is restarted, the button shows up.

Cinnamon Version: 2.8.7
Spotify Version: 1.0.24.104.g92a22684
Kernel: 4.2.0-25-generic

**Comment by JosephMcc** [comment]
Duplicate https://github.com/linuxmint/Cinnamon/issues/4858
