### ISSUE TITLE
Menu for custom theme shifts to the right if autohide is on.

### ISSUE THREAD

**Issue by Zerophase** [linuxmint/Cinnamon#5149]
Having autohide or intelligently hide turned on the positioning of a themes menu shifts to the right, if the menu doesn't have the same placement as the default Cinnamon menu.

To reproduce:
1. Install Windows 10 theme (might happen with other themes as well)
2. Turn autohide or intelligently hide on
3. Set custom panel size
4. Disable Cinnamon scaling panel text and icons according to panel height.

I came up with a work around, by setting the `.popup-menu` `border-left` to a negative value.

**Comment by Vahan86** [comment]
@Zerophase, does this issue still relevant to Cinnamon 3.4?

**Comment by Zerophase** [comment]
@Vahan86 I switched themes since then. I can get back to you on this issue in a couple days. Just need to update that theme and the package build it uses.

**Comment by Zerophase** [comment]
It's not relevant anymore.
