### ISSUE TITLE
Window menu appears on wrong monitor

### ISSUE THREAD

**Issue by basic6** [linuxmint/Cinnamon#5151]
There are 3 monitors in this setup, on 2 graphics cards.
Window menus show up on the second monitor if the window is on the third monitor.
The menu shows up on the same monitor if the window is on either of the other two monitors.

See the attached screenshot.

![menu_on_wrong_screen](https://cloud.githubusercontent.com/assets/2535481/13999660/98106f4a-f13d-11e5-8b52-5c879312bd50.png)

**Comment by stefan123t** [comment]
Dear basic6,
my problem #4645 seems related.
Would you mind updating either issue with the link to the bug report you filed elsewhere ?
Kind regards,
Stefan

**Comment by basic6** [comment]
@stefan123t: Interesting. In your case, it looks like the wrong menu position has something to do with the position of your main panel?

I'm convinced this only happens in a multi-monitor setup with different resolutions and/or more than 1 graphics card. Another (unrelated) Cinnamon issue is #5152 (a window on the third screen moves over to the second one when maximized); the details on the the monitor setup I've posted there are from the same computer.

This is the bug I opened against the distribution:
https://bugzilla.redhat.com/show_bug.cgi?id=1320731

**Comment by stefan123t** [comment]
In your case it looks like the width of the center display is wider than the others. Could be that some code is calculating the offset from the left falsely in this situation.
In my case it is related to the height of the displays, but it sounds familiar, as my menues are also sometimes shifted to the left, probably when the right screen is wider. Even though In that case the larger right screen is set as primary (if this makes any difference).
Kind regards,
Stefan

PS: IMHO, it looks like the width and location of the left-top panel has influence on the popup menu locations. Dunno if this has something to do with the maximizing issue you have on display three (right). Could be the offset is outside (left) of the snap area for maximizing it on that screen ?
