### ISSUE TITLE
no home is way inferior

### ISSUE THREAD

**Issue by two-dogs** [linuxmint/Cinnamon#5153]
its about time mint-cinnamon at least offer home partition as an option, no home is way inferior

**Comment by RogerioLuzCoelho** [comment]
There should be a dropdown menu in partitioning: 
> Use hole drive
> Use hole drive with /home

**Comment by RogerioLuzCoelho** [comment]
The drop down menu should have options: 
> Use whole drive (where the installer just installs a swap and /) 
> Use whole drive with /home (where the install aranges 20GB of / space , the swap and the rest as /home)
> Manually assign the partitions.

**Comment by dalcde** [comment]
Not related to Cinnamon

**Comment by two-dogs** [comment]
can you tell me where to submit then? the iso/installer  is specific to installed desktop, in this case cinnamon

**Comment by JosephMcc** [comment]
Try here: https://github.com/linuxmint/ubiquity/issues

**Comment by two-dogs** [comment]
Will do, thank you.
