### ISSUE TITLE
I can not turn off your computer

### ISSUE THREAD

**Issue by bm0** [linuxmint/Cinnamon#5154]
In the dialog box, there is no off button the computer.

![2016-03-23 16-55-14](https://cloud.githubusercontent.com/assets/17692213/14016890/2132f0a4-f1d4-11e5-81a8-6b07c9bbe417.png)

**Comment by JosephMcc** [comment]
If you are using a distro that has systemd, open dconf-editor and under org.cinnamon.desktop.session turn on the three settings that end in logind.

**Comment by bm0** [comment]
Thank you so much! You solved my problem. Can you tell you about how it works?

**Comment by matcheydj** [comment]
That's probably because it's not on.

**Comment by matcheydj** [comment]
Hi linuxmint/Cinnamon,

I'd like to add you to my professional network on LinkedIn.

- David

Confirm that you know David: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=pQQX4bM8&invitationId=6188766499650498561&trk=eml-guest-invite-cta&trkEmail=eml-invite_guest-null-2-null-null-0%7Eitucpubr%7Etc








You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-itucpubr-tc&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQGzRrEzo3ftrwAAAVeLqpMdYuQnL0o-2ojRuURW28-C3PDt9uhxbN0qummh4VIx0fD1Bxa6n1G9kv0qDu2fR_wLsMHp_L2RLf7vH7ISQJlTgtGHYgqvxNVBihZ8jqgnJzQYcDMDyABOe3i5QmZbNby-24PMDrZfJSpGwSQm1-dguYf2nbwoA2b1uZsC_C_bPEzh&eid=0-itucpubr-tc


This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-itucpubr-tc&a=customerServiceUrl&ek=invite_guest

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by matcheydj** [comment]
David Matchey would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=pQQX4bM8&invitationId=6188766499650498561&trk=eml-first_guest_reminder_01-hero-121-accept_text&trkEmail=eml-first_guest_reminder_01-hero-121-accept_text-null-%7Eyegasv%7Eiu4ibpkw%7Ey

View David Matchey&#39;s profile: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=pQQX4bM8&invitationId=6188766499650498561&trk=eml-first_guest_reminder_01-hero-3-profile_text&trkEmail=eml-first_guest_reminder_01-hero-3-profile_text-null-%7Eyegasv%7Eiu4ibpkw%7Ey





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=-yegasv-iu4ibpkw-y&t=lun&midToken=AQFmrFVhGEd36Q&ek=first_guest_reminder_01&li=123&m=unsub&ts=HTML&eid=-yegasv-iu4ibpkw-y&loid=AQEdSa1uyxaqLQAAAVexf7Ubor5WsVdNL7NtdCb42WUXr0Eiqfn6daTeSRkqclv-bYCAJ932YP0E97Zy1yInldQu58ZKhpf69qAHLHejJR90fAQqi7BJwCFP_roXXvG_g2LhXfwbpxvJfnBPmQvwv5UdFJHsbGs1J1ip_uuvywMlu4HCPEZorlfZq0casoK12gMX

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=-yegasv-iu4ibpkw-y&a=customerServiceUrl&ek=first_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.
