### ISSUE TITLE
How to automatically login?

### ISSUE THREAD

**Issue by Siecje** [linuxmint/Cinnamon#5156]
There doesn't seem to be a setting to automatically be logged in.

**Comment by f2404** [comment]
Depends on the login manager you're using, I guess.
For example, for `lightdm` on Arch: https://wiki.archlinux.org/index.php/LightDM#Enabling_autologin

**Comment by Siecje** [comment]
Is this something that can be set in Settings? With a GUI?

**Comment by JosephMcc** [comment]
On mint using MDM you should have an entry in your menu for "Login window" where you can set this.
I'm going to close this since it's not a cinnamon issue.
