### ISSUE TITLE
Comes out of suspend when lid is closed.

### ISSUE THREAD

**Issue by skrish13** [linuxmint/Cinnamon#5157]
When the laptop is put to **suspend** and the **lid is closed** the laptop **un-suspends** as it has to lock the screen aka the screensaver ( 'standard screen locker'). Disabling the screen lock when **'lid is closed'** resumes the laptop without any need of password. 

So how do i actually suspend the laptop and travel with it without it getting woken up when i close the lid or allow it to remain insecure by having no password on wake.

**Comment by Vahan86** [comment]
@skrish13, is this issue still relevant to Cinnamon 3.2?

**Comment by leigh123linux** [comment]
If it's still an issue re-file your report against cinnamon-settings-daemon

**Comment by skrish13** [comment]
@Vahan86 I haven't checked it out on cinnoman 3.2. @leigh123linux Yeah sure.
