### ISSUE TITLE
Sound output missing in 2.8.7

### ISSUE THREAD

**Issue by Setlaz** [linuxmint/Cinnamon#5160]
Hi,

System:Ubuntu 16.04 with Cinnamon 2.8.7 via PPA.

I'm using Pulseaudio-dlna (https://github.com/masmu/pulseaudio-dlna) to stream audio but DLNA output does not appear in the new Cinnamon Sound Settings.
The only way to set my audio output to Pulseaudio-DLNA is through installing pavucontrol and changing sound output setting from there.

**Comment by Setlaz** [comment]
The issue appeared again when I switched to Linux Mint 17.2 and current Cinnamon version 3.4.
Again, the sink in missing from Cinnamon Sound Settings but is present and working in pavucontrol.

**Comment by clefebvre** [comment]
We believe this issue is fixed. Please test against the latest Cinnamon version (3.6). If the issue happens again, create a new issue and add the output of "cinnamon-settings sound".
