### ISSUE TITLE
Please implement skip_taskbar and skip_pager?

### ISSUE THREAD

**Issue by SethDusek** [linuxmint/Cinnamon#5162]
Apparently skip_taskbar and skip_pager doesn't work on Cinnamon so I can't hide my terminal widget. According to archwiki "Note: Wmctrl is intended for use with Window managers which meet the EWMH/NetWM specifications. The following was tested only on Xfce4 with Xfwm4 so it is unconfirmed whether it will work with other desktop environments/window managers correctly as of this writing. For a list on environments which wmctrl may work with visit wikipedia:Wmctrl"

**Comment by mtwebster** [comment]
They're implemented in muffin, it's our window list applet that doesn't notice the changes and update accordingly.

Try restarting cinnamon after setting these on a window.  (alt-f2, r, enter)

**Comment by SethDusek** [comment]
So how can I put a widget on startup of cinnamon without having to restart it?

**Comment by SethDusek** [comment]
@mtwebster So is there any solution I can apply at the moment? Because I want this widget to run at startup and I'd prefer if I didn't have to restart cinnamon to get it to not appear in taskbar

**Comment by brianjmurrell** [comment]
I'm not quite following.  Is ```skip_tasklist``` working or not?  On Cinnamon 3.0.x I still see items on my tasklist widget on my panel that have the skip_tasklist property set.

**Comment by mtwebster** [comment]
Sorry for not following up on this sooner.  If (more likely when) we do a bug-fix update for cinnamon 3.x, I'll be sure this stuff is included in it.
