### ISSUE TITLE
Mouse wheel zoom also scrolls content

### ISSUE THREAD

**Issue by lhamil64** [linuxmint/Cinnamon#5163]
When using the "mouse wheel modifier" in the Accessibility settings for Zoom, if the mouse is positioned above scroll-able content, that content will scroll as well as the screen zooming in. I feel that this is a bug, and my suggestion would be to prevent scrolling in the application while zooming.

EDIT: My version is 2.8.0

**Comment by JosephMcc** [comment]
I can't reproduce this on git master.

**Comment by kaefert** [comment]
On my system (Ubuntu 16.04 with cinnamon 2.8.6-1ubuntu1) alt+mousewheel does correctly only control the desktop zoom when the mouse is contained in one of those scrollable apps:
chromium, firefox, mate-terminal

it does however at the same time control zooming when hovering over a gedit window.

**Comment by kaefert** [comment]
I just tried the described problem (simultanous destkop zoom control and normal mouse wheel scroll function) when using alt+mousewheel on Linux Mint 19 with Cinnamon 3.8.9.

**Comment by kaefert** [comment]
I can still reproduce this issue on my Linux Mint 19.1 Cinnamon 4.0.10 Kernel 4.15.0-70 system with gedit 3.28.1. Also the aplication Signal Desktop v1.29.0 shows the same problem.

Firefox correctly will ignore the mouse wheel when the alt modifier is pressed at the same time so it's used for desktop zooming.

**Comment by joaoarieira** [comment]
I'm at Linux Mint 20 Cinnamon 4.6.7 and if I use alt+mousewhell with Visual Studio Code runing, the same issue described by @kaefert happens:

https://user-images.githubusercontent.com/50000569/134366656-a06745cd-dfaf-450d-9d04-0177df33f31b.mp4

**Comment by Random-Brain** [comment]
@joaoarieira and @kaefert I solved this by assigning the shift key, within accesebility options, instead of the alt key for zooming. Maybe less convenient, but it works.

**Comment by joaoarieira** [comment]
> @joaoarieira and @kaefert I solved this by assigning the shift key, within accesebility options, instead of the alt key for zooming. Maybe less convenient, but it works.

Thank you. I will try later
