### ISSUE TITLE
Updating Mime database breaks cinnamon (fallback mode, only)

### ISSUE THREAD

**Issue by Hordeking** [linuxmint/cinnamon#5164]
Editing mime types causes cinnamon to be unable to properly load when it is restarted next. It can only enter fallback mode, and runs very poorly. Cannot be corrected by reinstallation of graphics drivers or cinnamon itself. Requires reinstallation of the package shared-mime-info to correct.

Steps to reproduce (on my system, with sudo):
1. Open /usr/share/mime/packages/freedesktop.org.xml in text editor.
2. Find the line  &lt;mime-type type="application/vnd.adobe.flash.movie"&gt;
3. Change the mime type to application/x-shockwave-flash
4. Run update-mime-database /usr/share/mime
5. run cinnamon --replace

Obviously this is somehow breaking whatever cinnamon is looking for in the mime database.

**Comment by Vahan86** [comment]
@Hordeking, is this still an issue in Cinnamon 4.2?

**Comment by Hordeking** [comment]
I haven't extensively checked it, but the past few times I've needed to update things, nothing has broken. I followed the above steps verbatim and did not experience any issues with having to go to fallback mode. It might have been fixed since I posted this.

**Comment by icarter09** [comment]
@Hordeking thanks for the update.
