### ISSUE TITLE
Workspace switcher applet, workspace preview truncated

### ISSUE THREAD

**Issue by maxyz** [linuxmint/cinnamon#5165]
Forwarding: Debian#813363 http://bugs.debian.org/813363

Originally reported by Rolando Mas:
I have two wide monitors.  The "main" monitor is landscape, and the
"secondary" monitor (located to the right) is portrait.  The workspace
preview applet, that I have in a panel, doesn't show the whole
workspaces.  Attached is a screenshot displaying the problems.  I placed
four windows at the four corners of the main monitor, one in the upper
half of the secondary monitor and one in the lower half.  You'll notice
that only a sliver of the lower windows of the main monitor are visible
in the applet, and that the window in the lower half of the secondary
monitor is completely hidden.
![capture du 2016-02-01 10-29-06](https://cloud.githubusercontent.com/assets/103059/14075363/d6358280-f4d8-11e5-98b1-b9b897408732.png)

**Comment by Vahan86** [comment]
@maxyz, is this still an issue in Cinnamon 4.2?

**Comment by Vahan86** [comment]
@icarter09, can we close this issue since there is no response from OP?
