### ISSUE TITLE
Mint menu not showing user defined icon

### ISSUE THREAD

**Issue by bitboy85** [linuxmint/Cinnamon#5166]
I recently installed qTox but it doesn't create a Menu entry on its own. I copied the svg file into /usr/share/icons/Mint-X/96/apps directory and used the menu editor to create a new entry. In the launcher editor window all seems fine but after clicking OK no icon was shown.

Only after executing sudo gtk-update-icon-cache /usr/share/icons/Mint-X
the icon was shown in the menu.

To make icon handling easier for users i think it should work like the following:
1. Icons which are not in the default icon folder should be copied there to have a central store and to keep it working even a user deletes the temporary downloaded icon. Make a hint that *.svg is preferred so that other sizes can be generated if needed.
2. If the menu editor notices that an icon is not in the cache, it should update it automatically

If someone likes to put the icon in the default installation, here it is
[qtox.svg.zip](https://github.com/linuxmint/Cinnamon/files/192230/qtox.svg.zip)

**Comment by JosephMcc** [comment]
Actually neither thing could or should happen automatically. Both require a user to have sudo privileges which should not be required for a user to make changes to the menu.
