### ISSUE TITLE
Visible in the system tray the program icon after system start

### ISSUE THREAD

**Issue by HileV** [linuxmint/Cinnamon#5167]
Visible in the tray icon of the program after the start of the system, but in settings this option is disabled. You have to turn it on and immediately turn off so the program is gone from the system tray.

How to solve the problem?
<a href="http://mepic.ru/view/?id=56feb559121f6bf777f9f9c9257be9e5" target=_blank><img src="http://mepic.ru/up/pic_s/56feb559121f6bf777f9f9c9257be9e5.jpg"></a>

**Comment by JosephMcc** [comment]
I don't know if this will help but have you tried setting a delay before the application starts up?

**Comment by Vahan86** [comment]
@HileV, is this still an issue for you with Cinnamon 3.2?

**Comment by Vahan86** [comment]
@JosephMcc, can we close this issue?
