### ISSUE TITLE
Docker - mounted volumes

### ISSUE THREAD

**Issue by f3l1x** [linuxmint/Cinnamon#5168]
Hello, I have Linux Mint 17.3 and Docker 1.6.2.

A see all docker mounted volumes on sidebar (more on image bellow).

![image](https://cloud.githubusercontent.com/assets/538058/14114432/392d5e22-f5d7-11e5-80f7-4d503f5c5099.png)

Is there any chance to disable this feature? I mean only for docker. I would like to see my USB devices etc.

Thank you.

**Comment by JosephMcc** [comment]
This is an actually a feature request for nemo so please move it there https://github.com/linuxmint/nemo
