### ISSUE TITLE
Battery options bug

### ISSUE THREAD

**Issue by grenzor** [linuxmint/Cinnamon#5170]
Currently the only options when battery are low are Hibernate and Do nothing.

Even when hibernate is on, the computer will do a hard shut down instead of hibernate (which is pretty much do nothing). Why is this?

**Comment by HileV** [comment]
+

**Comment by ManIVIctorious** [comment]
I experienced the same problem yesterday, where my notebook switched off with no prior warning... I am on arch linux with:
`pacman -Qs cinnamon | grep ^local`
`local/cinnamon 2.8.7-1`
`local/cinnamon-control-center 2.8.1-1`
`local/cinnamon-desktop 2.8.1-1`
`local/cinnamon-menus 2.8.0-1`
`local/cinnamon-screensaver 2.8.0-1`
`local/cinnamon-session 2.8.3-1`
`local/cinnamon-settings-daemon 2.8.4-3`
`local/cinnamon-translations 2.8.3-1`
`local/cjs 2.8.0-2`
`local/muffin 2.8.5-1`

**Comment by Vahan86** [comment]
@grenzor, is this still an issue for you with Cinnamon 3.6?

**Comment by JosephMcc** [comment]
Closing this unless someone reproduces it under a current Cinnamon version and can provide us enough feedback to troubleshoot.
