### ISSUE TITLE
Allow fixed geometry for Sound Applet

### ISSUE THREAD

**Issue by ManIVIctorious** [linuxmint/Cinnamon#5171]
It would be nice to have the possibility to set a fixed size for the cover art of the sound applet. In my case, I have a lot of cover arts with different sizes/ratios (some are not square) so when I want to skip some songs I always have to move my mouse to hit the skip button, as it never stays where it was...

I hope the I explained this well enough...

**Comment by JosephMcc** [comment]
The menu itself is resizing when the cover art changes?

**Comment by ManIVIctorious** [comment]
Exactly, to reproduce just use a audio file with widescreen (E.g. 16:9, although i have nothing that dramatic...) cove art and one with square cover art and switch between the titles. I'll try to make a mockup when I am back on my pc. 

If it is important: i only tried clementine as audio Player

**Comment by ManIVIctorious** [comment]
As you can see the applet changed in size. This is pretty annoying when skipping through the library, since the buttons don't stay in place...

<a href="http://tinypic.com?ref=103wh8w" target="_blank"><img src="http://i65.tinypic.com/103wh8w.png" border="0" alt="Image and video hosting by TinyPic"></a>
