### ISSUE TITLE
[Nemo] Starting nemo in another DE starts the nemo desktop

### ISSUE THREAD

**Issue by RalfJung** [linuxmint/Cinnamon#5172]
Steps to reproduce:
* Use some non-Cinnamon DE (e.g., LXQt)
* Start nemo

Actual behavior:
On the desktop (i.e., after minimizing all windows), I now get a transparent overlay of both the original LXQt desktop and a desktop rendered by nemo.

Expected behavior:
Nemo should not mess with other DE's desktops.

This is with nemo 2.8.7 on Debian testing.

**Comment by JosephMcc** [comment]
Nemo issues belong here: https://github.com/linuxmint/nemo
This is already fixed here: https://github.com/linuxmint/nemo/pull/1109
