### ISSUE TITLE
Power management applet does not update battery level

### ISSUE THREAD

**Issue by serkazak** [linuxmint/Cinnamon#5173]
The power management applet at panel updates battery percentage/time remaining only when ac power is attached/detached or system is restarted.
(A screenshot of panel displaying 61%)
![panel](https://cloud.githubusercontent.com/assets/16784884/14156784/e21b08e6-f6d0-11e5-85e2-e344348089e6.png)

Wheras power management in the system settings show accurate battery state.
(Actual battery level is 56%)
![powermanagement](https://cloud.githubusercontent.com/assets/16784884/14156789/e493d4e0-f6d0-11e5-845f-ad110aff10a6.png)

(Note that panel can show 100% while the actual level is 5%)

**Comment by f2404** [comment]
This is supposed to be resolved... Please look among closed issues.

**Comment by serkazak** [comment]
Updated to cinnamon-settings-daemon 2.8.4-2 from unstable repo and it works now. Thank you for your guidance.
