### ISSUE TITLE
Power Manager applet not updating

### ISSUE THREAD

**Issue by milomak** [linuxmint/Cinnamon#5175]
Hi,

I am using Cinnamon in Debian Sid

# dpkg -l | grep cinnamon
ii  cinnamon                                  2.8.7-1                             amd64        Innovative and comfortable desktop

The Power Manager applet shows my battery percentage as 100% and never changes after a full charge.

i have to use upower in a terminal to see the true status of the battery.

**Comment by f2404** [comment]
Please see #5173 (the latest one of many).

**Comment by JosephMcc** [comment]
duplicate
