### ISSUE TITLE
Telegram Desktop icon is hidden

### ISSUE THREAD

**Issue by andrew-xdn** [linuxmint/cinnamon#5176]
Application version: 0.9.33 64-bit
Cinnamon: 2.8.7

The problem is quite uncomfortable. There is no such problem in Unity with the same Telegram version.

Tested with indicators support and without it.

**Comment by kans3i** [comment]
I had the same problem, and I fix it removing telegram application and installing it again

**Comment by Gameranand** [comment]
I have similar problem. Icon is not displayed but the there is blank space instead of icon. When I click on the blank space, its as if icon is there but not on the display because right click pop up opens.

![image](https://cloud.githubusercontent.com/assets/11816991/20301576/e1c1fa02-ab49-11e6-9663-651a0ed9b157.png)

**Comment by Gameranand** [comment]
Anyway I found the alternative solution for the time being.

dbus-launch ~/.softwares/Telegram/Telegram start & disown

Just replace the path with yours and it will do. It will open the Telegram with the systray icon and with disown added at the last you can close the terminal just fine after Telegram opens.

Found this solution on Telegram github issues.

**Comment by Vahan86** [comment]
@andrew-xdn, does this issue still relevant to Cinnamon 3.4?

**Comment by a114m** [comment]
@Vahan86, I'm still having the same problem after upgrading to Cinnamon 3.6.7 even after reinstalling Telegram and removing `~/.local/share/TelegramDesktop/`
The only fix worked is the mentioned above.

Though i didn't have it with a fresh Linux installation on another machine.

**Comment by Vahan86** [comment]
@JosephMcc, can we mark this issue as a bug?

**Comment by icarter09** [comment]
Linux Mint 19.2
Cinnamon 4.2.4

I was unable to reproduce this bug. Initial install and running of Telegram displayed the desktop icon.

**Comment by icarter09** [comment]
We believe this issue is fixed. Please test against the latest Cinnamon version (4.2). 
If the issue happens again, create a new issue and add the output of "cinnamon-settings sound".
