### ISSUE TITLE
Crash when resizing window in IntelliJ CE using 2.8.7-20160404040133-wily

### ISSUE THREAD

**Issue by wrouesnel** [linuxmint/Cinnamon#5182]
When running the current latest nightly from gwendal's PPA, everytime I try to resize the window in IntelliJ (and certain other apps, but this one is reproducible) while running in Virtual 5.0.16 with 3D acceleration and latest guest additions, cinnamon will immediately crash (and restart).

This only happens with mouse dragging - if I use tiling or snaps to move the window around or resize it, it works fine.

**Comment by wrouesnel** [comment]
Right when the crash happens this is the line which goes down: `muffin:ERROR:core/window.c:9877:update_resize: assertion failed: (gravity >= 0)`

**Comment by wrouesnel** [comment]
Stack trace: https://gist.github.com/wrouesnel/431d175f55aa646dbfe34a8e06f025bc

**Comment by JosephMcc** [comment]
Closing this one since the muffin issue actually has more info.
