### ISSUE TITLE
PPA Channel for Ubuntu?

### ISSUE THREAD

**Issue by aungthurhahein** [linuxmint/Cinnamon#5183]
I just want to know this ppa is still releasing updates for Ubuntu.

    ppa:gwendal-lebihan-dev/cinnamon-nightly

**Comment by swarnendubiswas** [comment]
Which version of Ubuntu are you referring to? It provides Cinnamon v2.8.7 for xenial and wily.

**Comment by glebihan** [comment]
That PPA is still getting updates. The supported releases in that PPA are trusty, vivid, wily and xenial.
Be careful though, that PPA is a nightly PPA and isn't meant for usage on a production machine. It can (and will) break at any time.
