### ISSUE TITLE
How to change DPI

### ISSUE THREAD

**Issue by JohnyGemityg** [linuxmint/Cinnamon#5187]
Is there way how to change DPI ? I am using LInux mint 17.2 with full hd display and everything is to small and double hidpi option in Preference->General is too big.

I tried run xrandr --dpi xxx withou any effect.

Thank you.

**Comment by nan0desu** [comment]
See #4033, there are dconf fix.

**Comment by JohnyGemityg** [comment]
Thank you, that did the job. Hope this will be native option in next version ;)
