### ISSUE TITLE
Alt-tab switcher gets interrupted by cinnamon desktop notifications

### ISSUE THREAD

**Issue by Topperfalkon** [linuxmint/cinnamon#5188]
I'm experiencing a problem with the alt-tab switcher.

If I'm trying to switch between windows and a desktop notification is triggered, this interrupts the alt-tab switcher and drops me out on whatever window I had selected at the time. This becomes somewhat annoying when I'm receiving notifications to the desktop from HipChat because people are having conversations in a room I'm in whilst I'm trying to switch windows.

**Comment by Vahan86** [comment]
@Topperfalkon, is this still an issue for you in Cinnamon 4.2?

**Comment by Topperfalkon** [comment]
@Vahan86 I've not used Cinnamon in a few years now, so I'm unable to answer that for you.

**Comment by icarter09** [comment]
@Topperfalkon no worries and thanks for the update.
