### ISSUE TITLE
linux mint 17.3 can't lock

### ISSUE THREAD

**Issue by jackssirs** [linuxmint/Cinnamon#5190]
system setting-->screeen locker-->Lock the computer when the screen turns off "Immediately"
and return
system setting->power management -->power options 
Turn off the screen when inactive for "5 minutes"
suspend when inactive for "Nerver"
when the power button is pressed "Ask"
start the screensaver when inactive for "Never"
then "back"   and wait 5 minitues  The monitor turns black but not locked the computer
 pressed the keyboard any key or move mouse  returned the desktop

the cinnamon-screensaver doesn't work?

**Comment by JosephMcc** [comment]
Probably don't need the exact same issue in two places. It's also here: https://github.com/linuxmint/cinnamon-screensaver/issues/119
