### ISSUE TITLE
The widgets in "Power Managment" window are at the botton instead of top

### ISSUE THREAD

**Issue by surenenfiajyan** [linuxmint/Cinnamon#5194]
Open "System Settings" -> "Power Management"

Expand or maximize the window, you will see that the widgets are tied to the bottom instead of top.
In other windows the widgets are tied to the top.

I think it's a bug.

![power_settings](https://cloud.githubusercontent.com/assets/13224708/14413601/f2644952-ff8f-11e5-9081-a5e09c4668cd.png)

**Comment by kmkom** [comment]
I can confirm that behavior in Linux Mint 17.3 Cinnamon 2.8.8.

**Comment by f2404** [comment]
Not confirmed on Arch Linux, Cinnamon 2.8.8.

**Comment by JosephMcc** [comment]
This was confirmed by clem. It depends on what battery powered devices are currently attached to your machine. That's why some see it and some don't. A fix is in the works.
