### ISSUE TITLE
[REGRESSION] Some dialogs always appear in top left corner

### ISSUE THREAD

**Issue by geckolinux** [linuxmint/Cinnamon#5195]
Hi, I'm running Cinnamon 2.8.8 on openSUSE Tumbleweed. I am now seeing a new bug where certain dialogs, such as `gnomesu` and the Cinnamon logout session dialog always appear at the top left. They used to appear in the center of the screen as expected.

**Comment by f2404** [comment]
Confirm - Arch Linux, Cinnamon 2.8.8.
Looks like all Cinnamon dialogs (such as applets configuration or System Info/Settings) are appearing in the top left corner.

**Comment by leigh123linux** [comment]
Same here with fedora 24, looks like the gtk devs have fucked up gtk-3.20 release

**Comment by 887** [comment]
Same, Arch, Cinnamon 2.8.8. Here is what this looks like on my setup. Looks like my mouse has to travel far for now. The big screen, with the task bar, is the one these windows should appear. 

PS: Left monitor is on top of the big one in reality, but i prefer my x-session setup this way.  

![screenshot from 2016-04-12 00-01-17-for-github](https://cloud.githubusercontent.com/assets/5199263/14443872/4ca00782-0042-11e6-8335-d443acde213b.jpeg)

**Comment by ScriptSmith** [comment]
Also experiencing problems, see eclipse:

![screenshot from 2016-04-12 15-15-46](https://cloud.githubusercontent.com/assets/17246877/14450433/a7d5a358-00c1-11e6-85e6-50ab0868e3bf.png)

**Comment by JosephMcc** [comment]
I could have sworn I read somewhere that this was a gtk bug.

**Comment by HileV** [comment]
Yes, I have same bug. This is a gtk bug.

**Comment by ScriptSmith** [comment]
I've just downgraded the gtk package. The issue does no longer occur

**Comment by geckolinux** [comment]
On my openSUSE bug report I assumed it was a GTK issue and filed it there, but they said that `gnomesu` opens correctly on the center of the screen under Gnome, so they tossed it back to the Cinnamon maintainer.

**Comment by f2404** [comment]
On Arch, the issue seems to have been resolved with the latest update include gtk3-3.20.3.

**Comment by greyseal96** [comment]
I can also confirm that this was fixed on Arch after updating to gtk3-3.20.3-1.

**Comment by leigh123linux** [comment]
gtk3-3.20.3 also fixes the issue here

**Comment by mtwebster** [comment]
So... can I close?

**Comment by vladimir-didenko** [comment]
>So... can I close?

I think yes but there is related problem

https://github.com/linuxmint/muffin/issues/224

**Comment by two-dogs** [comment]
i saw same glitch for a while, not seeing it now; 

System:    Host: linux-s4s1 Kernel: 4.5.0-3-default x86_64 (64 bit gcc: 5.3.1)
           Desktop: Cinnamon 2.8.8 (Gtk 3.20.2) dm: sddm,sddm Distro: openSUSE Tumbleweed (20160414)

not sure where the fix came into play.
