### ISSUE TITLE
[Minor bug] Linux Mint 17.3 Cinnamon 2.8.8 - Launcher Dialog resize

### ISSUE THREAD

**Issue by kmkom** [linuxmint/Cinnamon#5196]
MintMenu: When I edit a launcher entry I can resize the dialog to see the full command line.
But when I try to do the same in System Settings -> Startprograms it's possible to resize the dialog, but the field within the dialog are not resized! Please check the appended screen shoot.

And I'm wondering: why is one dialog translated into my local language, but the other is not?
Is there something wrong with my installation or setting?

![bildschirmfoto launcher2](https://cloud.githubusercontent.com/assets/15555865/14422756/9ea622c4-ffd8-11e5-881c-879441a26736.png)

**Comment by JosephMcc** [comment]
The resize issue is already fixed in git master so should work as expected in Cinnamon 3.0
