### ISSUE TITLE
Is Cinnamon using some default GTK settings..?

### ISSUE THREAD

**Issue by eGit** [linuxmint/Cinnamon#5197]
I noticed this post in the Linux Mint forums and tried to reproduce the problem/question. Now I also wonder where Cinnamon get this information from: https://forums.linuxmint.com/viewtopic.php?f=47&t=220180

Is Linux Mint injecting some default GTK stuff into Cinnamon?

How can one make Cinnamon on Ubuntu/Xubuntu look identical to Cinnamon on Linux Mint..? Is there some secret setting one has to use? The Cinnamon themes are definitely not enough.

**Comment by mtwebster** [comment]
Gtk3 is patched in Mint for a few design and compatibility reasons (similarly, Ubuntu patches Gtk as well, for various reasons).  Dialogs like the one shown are part of what gets modified - the stock layout is fairly ugly in our opinion.

Gtk3 for Mint 17.x: https://github.com/linuxmint/gtk/tree/3.10

for LMDE: https://github.com/linuxmint/gtk/tree/master

**Comment by eGit** [comment]
Thanks for the insightful reply.

1. What means patched GTK3? I guess this means not really changes in the GTK3 C-code but rather settings files that describe default settings like UI control distances, borders, button sizes? What files exactly are patched?

2. Does this mean both Cinnamon ships with its own patched version of GTK3? Linux Mint does ship with a differently patched version of GTK3, and Cinnamon will use Mint's GTK3 instead of the GTK3 in its own repo?

3. When In install Cinnamon on Ubuntu, Cinnamon won't use its own patched version of GTK3 but Ubuntu's patched version of GTK3? Why?

Sorry, but I am still quite a bit confused. Is there an easy way to make Cinnamon on Ubuntu look like Cinnamon on Mint? Do I need to replace Ubuntu's GTK3 with Mint's GTK3? Or is it enough to replace a few plain-text GTK3 settings files which are different for Ubuntu and Mint.

Cheers!

**Comment by mtwebster** [comment]
1) C code is changed.  Those links show exactly what files are changed in the recent commits.

2) Cinnamon doesn't 'ship' - Mint does.  Gtk3 is a system library, anything that uses gtk in its code will use the gtk version that is installed.  So, programs in Mint use mint's supplied gtk, programs in Ubuntu use Ubuntu's gtk.  This includes Cinnamon or anything else.

3) See 2.  Programs are dynamically linked to their libraries in Linux.  This allows one to update library A and B that program C uses, without needing to also update program C at the same time.

To be fair, none of this has *any* relation to Cinnamon.  These dialogs we're looking at are not Cinnamon dialogs, they're gtk dialogs.  You could be running Mate or XFCE and they would look like that.  Cinnamon *does not use* Gtk.

To have your computer use Mint's gtk instead of Ubuntu's, you would need to compile Gtk3 from the source I've linked to and install it over your current libraries.  Note this is only valid for Ubuntu Trusty.  If you wish to compile for something after Trusty, you'll have to take Ubuntu's source, and apply our patches over that.

In trusty,

```
sudo apt-get build-dep gtk+3.0
git clone git@github.com:linuxmint/gtk.git
cd gtk
git checkout 3.10
dpkg-buildpackage
cd ..
sudo dpkg -i *.deb
```

**Comment by eGit** [comment]
Thank you for your answer. I somehow got it in my head - wrongly - that Cinnamon comes with its own gtk, which didn't make a lot of sense to my. Hence my confusing questions. I am well aware of dynamic linking and that gtk is part of the os.

Do you know if applying the Cinnamon theme (Mint-X), adjusting fonts and using Mint's gtk3 is enough to make Ubuntu + Cinnamon pixel-identical to Ubuntu + Cinnamon (assuming both Cinnamon versions are the same)?

Or is there some further patching going on in UI related artifacts like gtk2, metacity or something else entirely?

**Comment by eGit** [comment]
The original clone command didn't work. This worked for me:
git clone https://github.com/linuxmint/gtk.git

This didn't work however:
sudo apt-get build-dep gtk+3.0
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to find a source package for gtk+3.0

**Comment by mtwebster** [comment]
Ah sorry, you'll have to add source repositories to your apt setup (duplicate your sources.list with deb-src lines as well then update)

As for making it identical, yes, if you use mint's gtk, all the appropriate Cinnamon/Mint themes (mint-themes, mint-themes-gtk3, cinnamon-themes.. there is no magic going on, it should end up looking the same.  You may need to check fonts too, that has a bit of impact as well.

**Comment by eGit** [comment]
Hmm...I am not sure if I understand what you said and can reproduce it.

Also I was thinking if compiling Mint's gtk3 myself is the best option - especially since I will miss all the updates.

Isn't it possible to tell Ubuntu to fetch gtk3 from the Mint repo or ppa?

**Comment by mtwebster** [comment]
Just re-read - you're sort of out of luck right now if you're using 16.04, we don't have a Mint version of the particular gtk that's used in it (yet) - which is 3.18.  Once we have that done, theoretically you could add the mint repos to your system and simply install everything via apt-get (including all the theme packages I mentioned).  That said, even without the different Gtk, you should be able to get everything else the same.  The gtk changes are only noticeable really in popup dialogs and I believe the file save/open dialogs.

I brought up this thread with Clem, regarding auto-updates.. there are valid reasons not to do it, and I appreciate the reasons.  You could set up a simple cron job for these users, but there would be no filtering involved (you'd get whatever updates are available, not strictly security updates).  And if something got broken, it'd be completely out of the blue, no obvious explanation, etc...

For what it's worth, I'm one of those folks who neglect to install any updates for months or years :) and I'm a developer.  A security update is only as important as you think it is - i.e. does it affect you, or a program you use?  For most average users (behind a router using nat, etc..), if they only updated their browser regularly, they would never have a problem.

**Comment by eGit** [comment]
Thanks. I know there are valid reasons for both options. The solution is to place a little checkbox in the settings UI which allows users with root priviliges to switch autoupdates on (actually I would prefer updates for everything not only security stuff since I am not sure browser updates are always marked as security updates but they always are).
The current situation looks like this: I know about a dozen users who switched from Windows to Linux Mint. 9 out of those do never update their system. That's just a fact - I tried to tell them otherwise but they forget.
The remaining 3 who do updates see it as a total chore and they ALWAYS install ALL updates. They are in no position to decide what to install and what not to install. Actually you should count me in. I update daily but I never deselected any update and in truth it is just a waste of time and doesn't increase my security even a bit. Linux Mint is doing almost everything right were other distributions fail horribly...still with auto-updates I have to say Linux Mint is somewhere between stubborn and dumb.

As I said, a cron job is no alternative. I want autoupdates to be an integral part of my distribution which means it is TESTED and most probably works and keeps working. I don't want no cron job since that is even less secure then no updates at all!

About security updates: we are just lucky all those ransom-ware does focus Windows and OSX. At the moment. This can change very quickly and maybe soon Linux Mint is also a target. A lot of Windows users switched and keep switching every day. The option to activate autoupdates should be a no-brainer. If you are afraid of offering this option why not display a horrible warning dialog: Please only activate if you know what you are doing and list the dangers of autoupdates.

**Comment by JosephMcc** [comment]
Closing this since it isn't really a bug report and the original question was answered.
