### ISSUE TITLE
Is it possible to make auto window resizing available when using two monitors even in the center

### ISSUE THREAD

**Issue by ebretteville** [linuxmint/cinnamon#5198]
Is it possible to make auto window resizing available when using two monitors even in the center. I think the title explain the problem but to be sure I add a little screenshot about what I'm talking.

![rect3022-9](https://cloud.githubusercontent.com/assets/3687099/14426918/164dbbc0-fff2-11e5-8f27-50ca785ed73d.png)

**Comment by skrish13** [comment]
Hi, Please mention which version of cinnamon you are using. In Linux Mint 17.3, where I use laptop+monitor,(2 displays extended) the center is also an active zone, hence window resizing is available even in the center.

**Comment by cybermarmotte** [comment]
Sorry I forgot.
Cinnamon 2.8.6
OS: LMDE2 (Betsy)

**Comment by JosephMcc** [comment]
Sorry if I'm being dense but what do you mean by "auto window resizing"? Are you talking about the window tiling features? If thats the case it does work in the center zone. It just requires that the window you are trying to use it with is capable of being resized into the dimensions the tiling wants.

**Comment by ebretteville** [comment]
I tried, nothing changed. And the windows tiles on a screen only configuration.

Thx

**Comment by Vahan86** [comment]
@ebretteville, is this still an issue in Cinnamon 4.4?

**Comment by Vahan86** [comment]
@icarter09, can we close the issue since there is no response from OP?
