### ISSUE TITLE
context menu opens at wrong/last position 

### ISSUE THREAD

**Issue by jeweloper** [linuxmint/Cinnamon#5202]
In some applications the context menu (right mouse click) opens at the position it was opened before and not at the current mouse position.

reproduce:
1. open/run for example gnome-terminal
2. open context menu (right mouse click) at any position
3. move the cursor to another position
4. open context menu at the new position again

expected behaviour:
The context menu opens at the new cursor position.

current behaviour:
The context menu opens at the position where it opened the first time (in relation to the current gnome-terminal instance).
This problem exists since the update from gtk+ v3.20.2 to v3.20.3.

Applications I could reproduce the problem:

- gnome-terminal
- firefox
- nemo

Applications I could not reproduce the problem:
- gedit
- gnome-calculator

I'm not sure if it's related to gtk+ or cinnamon, because under the gnome DE I couldn't reproduce this bug.

Here you can find the related gtk-Ticket: https://bugzilla.gnome.org/show_bug.cgi?id=764959

Enviroment:
Antergos (4.4.5-1-Arch)
Cinnamon 2.8.8
gtk3 v3.20.3-1
gtk-theme: Adwaita

**Comment by argamanza** [comment]
I'm experiencing the same issues with an almost identical environment (Antergos + Cinnamon) freshly installed.

I attached a video showing the issue, notice the grey line on the right hand side of the screen which shows only when icons are available on the desktop, it's almost new and I'm not sure if it has something to do with the issue. 
[Video on YouTube showing the issue](https://youtu.be/rnSEAq41h3w)

**Comment by DemonWav** [comment]
On Arch Linux this has been happening as well. Some programs that handle it on their own, like Chrome, IntelliJ, or Hexchat do not have this problem. However, any program which uses the normal GTK context menu will have this issue (as far as I can tell).

**Comment by k-freeman** [comment]
i can confirm this. right clicking folders works fine, but right clicking on the desktop background e.g. will open at the position, where the context menu was opened for the first time.

**Comment by vladimir-didenko** [comment]
FYI: There is already reported issue in muffin repo

https://github.com/linuxmint/muffin/issues/224

**Comment by Ufeldraku** [comment]
Happens to me aswell, hope it gets fixed

**Comment by ladywithhat** [comment]
problem still persists on:

gtk2 2.24.30-1
gtk3 3.20.3-1
cinnamon 2.8.8-2

Any advice how to fix it on archlinux?

**Comment by vladimir-didenko** [comment]
@ladywithhat  Ask your maintainer to add follow patch https://github.com/linuxmint/muffin/commit/65fd5fe41436ccfa74ea37b886f96adee6f258c1 to muffin package

**Comment by olliemath** [comment]
@ladywithhat @DemonWav until patched in the official repo, you can use the PKGBUILD at https://bbs.archlinux.org/viewtopic.php?id=211560 to install the patched version of muffin. It should upgrade naturally when 2.8.6 is released.

**Comment by real-or-random** [comment]
For the Arch guys: Now it's in the official repos:
https://projects.archlinux.org/svntogit/community.git/commit/trunk?h=packages/muffin&id=8755204de5b4c16fc09ea3f4ee670e5366c37300

**Comment by diegofcv** [comment]
I'm also suffering with this, happens in both and old but up-to-date cinnamon and in a fresh one, different machine. Is the Arch patch above mentioned good to be used in the Mint?
