### ISSUE TITLE
Panel items reorder when moving application to another monitor

### ISSUE THREAD

**Issue by skurger** [linuxmint/Cinnamon#5203]
Linux Mint 17.3 Cinnamon 64-bit
Cinnamon 2.8.8

I have a 3 monitor setup.  Anytime that I move an application window from one monitor to another the panel item for that application moves to the end (rightmost) of the panel items.  This makes it a pain when I have to undock my laptop to go to another room or redock.  This did not happen on Mint 17.2.

**Comment by f2404** [comment]
Confirmed for Arch Linux, Cinnamon 2.8.8.

**Comment by mtwebster** [comment]
This should already be fixed by https://github.com/linuxmint/Cinnamon/commit/8ebe48fff19e32eea17f63dae7fb20da6655c4ec

Will be in 3.0... it is not in our 'official' 2.8.8

**Comment by f2404** [comment]
@mtwebster OK, thanks.

**Comment by skurger** [comment]
Great, thanks for the help!
