### ISSUE TITLE
Changing window borders change only minimize/maximize/close icons

### ISSUE THREAD

**Issue by argamanza** [linuxmint/Cinnamon#5204]
Changing the window borders inside the themes manager doesn't change the colors and looks of the borders, only the icons for the minimize, maximize and close buttons.

Before the change:
![Before](https://cloud.githubusercontent.com/assets/9576019/14545984/c8aae6fc-02aa-11e6-8264-56155855186a.png)

After the change:
![After](https://cloud.githubusercontent.com/assets/9576019/14545983/c8a85fd6-02aa-11e6-8e55-8d710b6814d8.png)

As you see not the preview neither the preview nor the result window borders are as they should look, except of the border icons.

Tried with multiple dark themes and in all of them, the window borders are not changing.

## Enviroment:

OS: Antergos 
Kernel: x86_64 Linux 4.5.0-1-ARCH
Shell: bash 4.3.42
Resolution: 3200x1800
DE: Cinnamon 2.8.8
WM: Muffin
WM Theme: Numix-Frost (Numix-Frost-Light)
GTK Theme: Numix-Frost-Light [GTK2/3]
Icon Theme: Numix-Square

**Comment by JosephMcc** [comment]
First the preview in the settings. That is just a png in image provided by the theme. What you see there is whatever the theme designer provided.

For the window border color. Most newer window border themes draw the background color from the gtk theme you are currently using. This is how the dark variation of the theme that some applications use works correctly.

**Comment by argamanza** [comment]
@JosephMcc I just changed all the themes to the dark style, and restarted my machine, and it worked.. I feel kinda stupid but i already did it before and restarted the DE, not the computer, and it didn't change before.

Thanks.
