### ISSUE TITLE
Cinnamon has glitched graphics if DRI3 and EXA/UXA are enabled in Radeon card

### ISSUE THREAD

**Issue by MischievousTomato** [linuxmint/cinnamon#5209]
AMD Radeon 7520g
I have to use Glamor acceleration.
Thanks, I can't record it, as it appears fine in the recording.

**Comment by leigh123linux** [comment]
Any glitches are driver related, please close this issue and file it against radeon instead.

**Comment by Vahan86** [comment]
@MischievousTomato, is this still an issue for you with Cinnamon 4.2?

**Comment by Vahan86** [comment]
@icarter09, can we close this issue since there is no response from OP?
