### ISSUE TITLE
Can't alt+tab out of  fullscreen games

### ISSUE THREAD

**Issue by Ufeldraku** [linuxmint/Cinnamon#5210]
Just as title says, however, In Minecraft, I'm able to do it, however, it's like the minecraft's windows never minimized, because, if I click, the sound of clicking an option in minecraft is played, the only thins that solves this is in terminator, do a $ cinnamon --replace, also, the perfomance boosted significantly if I do the --replace thingy, weird.

**Comment by Ufeldraku** [comment]
Interesting, doing the cinnamon --replace in the terminator, allows me to do the alt+tab out of the game, normally as it should be.

**Comment by Ufeldraku** [comment]
Is there any difference from doing cinnamon --replace in alt+f2 and doing it in a terminal?

**Comment by AlbertJP** [comment]
Probably has to do with unredirection of fullscreen applications to speed up games. I think it's a Muffin problem as unredirection is handled in Muffin, IIRC.

**Comment by Ufeldraku** [comment]
Ah, but in 3.0.5 is fixed though.
