### ISSUE TITLE
Cinnamon themes app is incompatible with new themes

### ISSUE THREAD

**Issue by marmistrz** [linuxmint/Cinnamon#5211]
See this discussion, my post and the reply: https://github.com/tista500/Adapta/issues/1

**Comment by clefebvre** [comment]
That theme shows up properly for me in cinnamon settings.

You didn't explain how you installed it though?

I cloned the Adapta git repo and copied it in /usr/share/themes/.

**Comment by marmistrz** [comment]
I downloaded it from AUR. Here are the files: http://paste.pound-python.org/show/sk0OfEOEMgbkZ6b38y3f/

Adapta is visible under "Window borders" but not under "Controls"

**Comment by clefebvre** [comment]
https://github.com/linuxmint/Cinnamon/commit/aab4ee74bc6f1d3137fbec0a3dd8f3d9a23eb2de
