### ISSUE TITLE
MintUpload: multiple icons in panel

### ISSUE THREAD

**Issue by ACinnamonUserInUK** [linuxmint/Cinnamon#5212]
What happens: run MintUpload (via any route, I think). Close it. Run it again. Close again. Result: two MintUpload icons in my panel. Indeed one can generate three icons in this manner.

What should happen: either the icon should disappear when one quits the program, or, if not, only one icon should ever appear at any one time. Presumably!

Mint 17.3 x64 Cinnamon 2.8.8.

**Comment by JosephMcc** [comment]
This isn't a Cinnamon issue. You are starting multiple instances of MintUpload. If you feel it should work differently please open an issue on the mintupload git repo.
