### ISSUE TITLE
Startup Manager: 'on' & 'on' sliders ambiguous

### ISSUE THREAD

**Issue by ACinnamonUserInUK** [linuxmint/Cinnamon#5213]
**What happens:** within the Startup Manager, the 'on' and 'off' sliders are ambigious, a least somewhat, between (1) turning the autostart on and off (respectively) and (2) turning the _delay_ on and off (respectively). 1 is what the sliders actually control.

**What should happen**: it seems to me that it would be better were this ambiguity not present. To that end, a title could be added above the sliders, saying 'Autostart enabled?' or something to that effect. (If that were done, the word delay could moved to this top, column title position as well. It might not be a bad idea to indicate, in this overview window, that the unity of delay is _seconds_, too.)

Mint 17.3 x64 Cinnamon 2.8.8.

**Comment by JosephMcc** [comment]
I don't see the ambiguity here and it doesn't seem others do either as we've really seen no complaints over it. It's unlikely to change.
