### ISSUE TITLE
'Remove this applet' can easily remove the system tray applet

### ISSUE THREAD

**Issue by ACinnamonUserInUK** [linuxmint/Cinnamon#5214]
**What happens.** Imagine that you have a program running that puts an icon in panel - say, the program TeamViewer. One wants to (completely) exit that program. To that end, one tries to right-click the panel icon; attempting this generates a 'remove this applet' option, which one might - somewhat unthinkingly - click. Result: the system tray applet is removed from the tray. Now, it is easy to put the applet back, and the message 'remove this applet' - rather than, say, 'quit TeamViewer' - would alert the user who is paying attention, i.e. would tell them what is really going on. However, I submit that it is too easy - I do it myself fairly often - to fall into this confusion, i.e. t_o close the tray when one means to close an application_.

**What should happen:** not sure. Perhaps show the message 'Remove this applet ('System Tray [or what have you])' rather than just 'remove this applet'?

Mint 17.3 x64 Cinnamon 2.8.8.

**Comment by JosephMcc** [comment]
If you disable support for indicators in Cinnamon Settings->General, right clicking should bring up the actual menu from the teamviewer tray icon instead of the applet context menu.

**Comment by ACinnamonUserInUK** [comment]
Aha. It is good to have that option. Why not, though, change the message in the way I suggested?

**Comment by brownsr** [comment]
@ACinnamonUserInUK That's a function that is shared between all applets.  It would be a bit awkward to adapt systray to use its own local version, or find some other coding change.  Quite a bit harder then the simple wording change you might imagine it to be without looking at the code.  A better change might be to consider adding the applet name to the message.

**Comment by ACinnamonUserInUK** [comment]
@brownsr: your notion of altering Cinnamon such that its 'remove this applet' option always reads 'remove this applet (<applet name>)' sounds like a good idea to me!

**Comment by JosephMcc** [comment]
Fix merged.
