### ISSUE TITLE
Global handling of modifier keys can confuse applications

### ISSUE THREAD

**Issue by ticalc-travis** [linuxmint/cinnamon#5216]
Observed on:
Ubuntu 15.10, Cinnamon 2.6.13 in main repos, and Cinnamon 2.8.8 in PPA http://ppa.launchpad.net/embrosyn/cinnamon/ubuntu/
Linux Mint 17.3, Cinnamon 2.8.6, Cinnamon 2.8.8

Cinnamon's handling of the Super key, and the Ctrl key when “Show position of pointer when Control key is pressed” is enabled in the mouse settings, seems to cause difficulties in several programs:
- The text cursor and/or selection in many apps, such as Firefox and GNOME terminal, flash off and on as the key is pressed and released, even simply to type a shortcut key, which is distracting/disorienting.
- GNU Emacs gets confused when “Show position of pointer” is on: Ctrl-G fails to work correctly. One press should exit the Emacs minibuffer, for instance, but it remains stuck in minibuffer mode. If the show-pointer-on-Ctrl option is off, it works correctly.
- Cinnamon completely grabs the keys before apps like VirtualBox get to see them. It does not seem possible to pass a Super key to a running VirtualBox VM at all; Cinnamon completely intercepts it. Worse, this means that if the host key is Super, it can be impossible to escape the VM input grab and return to the host WM at all! Other DEs/WMs I've used play more nicely by letting VB get the key first as a special case (even if a global action is tied to it), and the user can use the VB host key to instead direct the key back to the host DE/WM which would normally handle it.

**Comment by Vahan86** [comment]
@ticalc-travis, is this still an issue in Cinnamon 4.2?

**Comment by ticalc-travis** [comment]
Unfortunately, I haven't used Cinnamon in quite a long time, and I don't currently have a convenient way to test now. If that situation changes, though, I'll try to remember to report on it.
