### ISSUE TITLE
network manager needs scroll options

### ISSUE THREAD

**Issue by SiKing** [linuxmint/Cinnamon#5220]
I have a low resolution machine: 1366 x 768. I also live in an apartment building, so my network manager shows a lot of neighbours' wireless devices.
![nm](https://cloud.githubusercontent.com/assets/5496738/14656384/1b9c7a3a-063c-11e6-96f1-42e6efc4e624.png)
I cannot see the bottom of the network manager controls, such as the VPN connections. It would be desirable to either:

1. make the list shorter than the maximum window height allows, or
2. allow for the control to scroll.

**Comment by JosephMcc** [comment]
Duplicate https://github.com/linuxmint/Cinnamon/issues/3678

**Comment by SiKing** [comment]
Sorry, should have searched better. :(
Thank You.
