### ISSUE TITLE
Unexpected behaviour when placing external monitor left of laptop monitor

### ISSUE THREAD

**Issue by grauerkoala** [linuxmint/cinnamon#5221]
I've somewhat recently started using Cinnamon and finally tried attaching a second monitor. Mirroring works fine, but I have trouble once I want to expand my desktop.

The second monitor ist to the left of my laptop screen, so I configured it thusly using the settings dialog, effectively in this way:
`xrandr --output eDP1 --auto --output HDMI0 --auto --left-of eDP1`
where eDP1 is my laptop monitor and HDMI0 is the external one.

On the first look, the result looks promising: my laptop monitor still contains all the panels and windows while the external one is empty and contains my mouse cursor. Once I start moving said cursor right towards my laptop monitor, however, the contents of the laptop screen scroll into the external monitor as the mouse moves. I can even make it go back again by moving the cursor all the way to the right so that it looks like it works correctly again.
Additionally, the Desktop appears to be treated as a great big combined desktop, so maximizing windows spans them over both monitors (and partly out of sight, of course, since my monitors have different heights).

For the sake of experimenting, I tried putting the external monitor above my laptop screen, which resulted in a very similar behaviour (same thing, but vertically instead of horizontally).

When I finally configured the external monitor to be on the "right" of my laptop monitor, everything worked as expected: maximizing a windows keeps it on the respective screen, moving the mouse cursor doesn't cause any scrolling of desktops.

Now, I'll say that the scrolling in general looks like it's a very much intentional feature. However, expanding the monitor the way it is when the external monitor is top or left of the laptop screen seems wrong, which is the point of this wall of text (sorry).

Thanks for bearing with me!

**Comment by KDra** [comment]
I have the same problem

**Comment by icarter09** [comment]
@grauerkoala are you still experiencing this issue?
