### ISSUE TITLE
Expo applet icon resembles searching-for-network icon

### ISSUE THREAD

**Issue by CottonEaster** [linuxmint/Cinnamon#5226]
The three dots of the 'Expo' icon resembles the icon that the Network Manager shows when searching for a network. This causes some visual jar and is potentially slightly confusing. Suggestion: change the expo icon to some other design.

Cinnamon 2.8.8. Mint 17.3.

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
