### ISSUE TITLE
Auto dismissing notifications

### ISSUE THREAD

**Issue by matthias-johnson** [linuxmint/Cinnamon#5236]
Probably my most frequent notification is battery alerts and the critical battery alert does not dismiss itself automatically when charging. I can understand the argument that messages should not disappear on their known but some messages have no use once the state of notification no longer exists. I searched through the open tickets for notification so my apologies in advance if this is a dupe.

**Comment by awnumar** [comment]
I mean there is a notifications drawer, so once the notification flashes on-screen, there's no need for it to continue being there. On smartphones, a notification overlays on your stuff for maybe a few seconds max, and then disappears into the drawer until it's dismissed.

**Comment by cmrdt** [comment]
perhaps if-rule-sets/logic
- app-name
- keywords in notification

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
