### ISSUE TITLE
Blueberry on cinnamon 3.0.0 close panel is side opposite of icon and menu

### ISSUE THREAD

**Issue by two-dogs** [linuxmint/Cinnamon#5237]
Blueberry on cinnamon 3.0.0 close panel is side opposite of icon and menu, my menu is top right, blueberry icon is on top right, close/quit panel is side opposite , extreme left-top, its odd but not unfunctional, just wondering if issue is related to my choice of panel location and menu location?

http://img.susepaste.org/57884325 <-- look at top left corner

System:    Host: linux-s4s1 Kernel: 4.5.0-3-default x86_64 (64 bit gcc: 5.3.1)
           Desktop: Cinnamon 3.0.0 (Gtk 3.20.3) dm: sddm,sddm Distro: openSUSE Tumbleweed (20160417)

info on muffin https://gist.github.com/d0b1ac05ff34802a66d713591d9e274e

just installed cinn-3.0.0, nothing to complain about, works great, kudos to the dev's and thank you Clem.

**Comment by JosephMcc** [comment]
Could you possible show a screenshot? I'm having a hard time picturing what you're describing.

**Comment by two-dogs** [comment]
On Monday, April 25, 2016 10:17:01 PM PDT JosephMcc wrote:
> Could you possible show a screenshot? I'm having a hard time picturing what
> you're describing.
> 
> ---
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/linuxmint/Cinnamon/issues/5237#issuecomment-214618570

i have updated the comment with a image

**Comment by leigh123linux** [comment]
@two-dogs  which muffin version are you using?

**Comment by two-dogs** [comment]
added muffin info, i dont have any errors while running cinnamon

**Comment by XRevan86** [comment]
https://github.com/linuxmint/blueberry/commit/c4d29f6 should do the trick.

**Comment by two-dogs** [comment]
@XRevan86 , yeap, your tweak did do the trick, FIXED, now action panel is directly below the systray icon for blueberry, thank you.
i am using;
System:    Host: linux-s4s1 Kernel: 4.5.0-3-default x86_64 (64 bit gcc: 5.3.1)
           Desktop: Cinnamon 3.0.0 (Gtk 3.20.3) dm: sddm,sddm Distro: openSUSE Tumbleweed (20160417)
