### ISSUE TITLE
Secondary monitor desktop is not a desktop

### ISSUE THREAD

**Issue by f2404** [linuxmint/Cinnamon#5239]
I cannot drag an icon from my primary monitor desktop to the secondary one; the right-click menus are different (the secondary monitor menu only allows to add desklets or change background).
Is this intended?
Arch Linux, Cinnamon 3.0.1.

**Comment by JosephMcc** [comment]
In 3.0 you have much more control over how this works. Go to Cinnamon Settings->Desktop and choose the layout you like.

**Comment by f2404** [comment]
Yes, that's it, thanks!
