### ISSUE TITLE
Chromium suddenly enters full-screen when panel auto-hide is enabled

### ISSUE THREAD

**Issue by mdchaves** [linuxmint/Cinnamon#524]
When the panel is set to auto-hide, sometimes chromium browser enters in full-screen mode unexpectedly, without any user action. When that happens, I can't exit from the full-screen (F11 and Esc keys don't work) unless I disable the “auto-hide panel” option in “panel settings”. This bug is still present in cinnamon 1.4.

**Comment by JosephMcc** [comment]
This issue is old and Cinnamon's panels have been completely revamped.
