### ISSUE TITLE
Automatic on screen keyboard should be configurable

### ISSUE THREAD

**Issue by loewexy** [linuxmint/cinnamon#5242]
I am using Cinnamon on a Lenovo Thinkpad Yoga. Also I use the integrated on screen keyboard.
Before Cinnamon 3.0 I had an applet in the system tray to toggle the keyboard, so I can manually chose when I want to use it.
Since Cinnamon 3.0 every time an input field occurs the keyboard is displayed which is pretty annoying if I am using the device in Laptop mode where I can use the physical keyboard. It would be perfect if the automatic can be disabled in the settings.

**Comment by brownsr** [comment]
Just giving this a try, but I only have a standard laptop, so I can't test removal/adding of a keyboard readily.  In 3.0 you turn the on screen keyboard on with the accessibility settings.  There is a keyboard shortcut to turn it on or off as well.  This appears to work regardless of whether the on-screen keyboard has been turned on in the accessibility  settings or not.  The mapping is visible under settings, keyboard, universal access.  On my computer it is Alt Super /    .  Is using keyboard shortcuts feasible for you when you plug up the keyboard ?

There does seem to be a quirk where the keyboard is launched when starting up a settings module, if turned on in the accessibility settings even if it has been subsequently turned off with the keyboard shortcut, but I would think that's a separate issue to yours.

**Comment by loewexy** [comment]
If I flip my yoga into tablet mode the keyboard is blocked, so I can't use it.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
