### ISSUE TITLE
Sound applet & Banshee

### ISSUE THREAD

**Issue by HileV** [linuxmint/Cinnamon#5246]
Recently something is happening with the media player Banshee. After some time it hangs. To kill it in the processes is impossible, as well from the terminal it is not killed, but does not start. So well behaved and the sound applet in which the player controls. It gives very great discomfort.

It started even before updating to 3.0 cinnamon. I hope you help me.
<a href="http://mepic.ru/view/?id=3028f824931ea76ba4c7a0ca29150292" target=_blank><img src="http://mepic.ru/up/pic_s/3028f824931ea76ba4c7a0ca29150292.jpg"></a>

<a href="http://mepic.ru/view/?id=d522d402cbb0a59eeb12be5f209dfc4e" target=_blank><img src="http://mepic.ru/up/pic_s/d522d402cbb0a59eeb12be5f209dfc4e.jpg"></a>

**Comment by JosephMcc** [comment]
Not really sure how this is a Cinnamon issue. In my experience Banshee has always suffered from this issue and I stopped using it a long time ago because of it.

**Comment by HileV** [comment]
@JosephMcc but I it has never happened before....
