### ISSUE TITLE
Alt+Tab doesn't show open windows since 3.0.1 update

### ISSUE THREAD

**Issue by argamanza** [linuxmint/Cinnamon#5247]
Using Arch Linux, since the latest big 3.0.1 update, when i'm trying to switch to another open window using Alt+Tab it will only show me a darken desktop without the thumbnails of open windows.

The Alt+Tab functions as it should, but without an overview of open windows and showing which window i'll see when releasing the Alt key it can't be used.

Attached: Screenshot of what i see when i press Alt+Tab (And hold it / press tab again, i see it until i release the Alt and than i see another active window)
![Screenshot](https://cloud.githubusercontent.com/assets/9576019/14844246/a52f6cb2-0c5e-11e6-84ab-9796c63006fd.png)

**Comment by f2404** [comment]
Works fine for me on Arch Linux.
Did you try rebooting?

**Comment by argamanza** [comment]
Yep, doesn't work...

**Comment by argamanza** [comment]
I stupidly forgotten i have a "Coverflow 3D" Alt+Tab extension, which was the reason my Alt+Tab got broken.
If anyone experience same issue in the future since 3.1.0 version check if you have an extension responsible for the previews.
