### ISSUE TITLE
[3.0.1] System volume control does not list PulseAudio RAOP devices anymore

### ISSUE THREAD

**Issue by acidicX** [linuxmint/Cinnamon#5248]
I'm using [pulseaudio-zeroconf-raop2](https://aur.archlinux.org/packages/pulseaudio-zeroconf-raop2/) to connect to AirPlay-compatible devices. Since 3.0.1, I cannot select the AirPlay devices in the system volume control applet anymore:

![bildschirmfoto vom 2016-04-27 16-19-11](https://cloud.githubusercontent.com/assets/1297454/14855350/df6934f0-0c93-11e6-860c-2ab86e6961b7.png)

They were available to select in Cinnamon 2 before.

The devices still show up in PulseAudio (No. 4 / 5):
````
➜  ~ pactl list sinks short
0	alsa_output.pci-0000_01_00.1.hdmi-stereo	module-alsa-card.c	s16le 2ch 44100Hz	SUSPENDED
1	alsa_output.pci-0000_00_1f.3.analog-stereo	module-alsa-card.c	s16le 2ch 48000Hz	SUSPENDED
4	raop_output.peerumio.local	module-raop-sink.c	s16le 2ch 44100Hz	SUSPENDED
5	raop_output.peerumio.local.2	module-raop-sink.c	s16le 2ch 44100Hz	SUSPENDED
````

Otherwise, nice work on 3.0. I'm loving the new slide-out effect of context menus.

**Comment by collinss** [comment]
Do you get any errors when running ```cinnamon-settings sound``` in a terminal?

**Comment by acidicX** [comment]
Yep:
**GTK**
````
(cinnamon-settings.py:12204): Gtk-WARNING **: Failed to measure available space: Der angegebene Ort wird nicht unterstützt
(a lot of those)
````
**PYTHON**
````
Traceback (most recent call last):
  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_sound.py", line 707, in deviceAdded
    lookup = iconTheme.lookup_by_gicon(gicon, 32, 0)
TypeError: Argument 1 does not allow None as a value
Traceback (most recent call last):
  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_sound.py", line 707, in deviceAdded
    lookup = iconTheme.lookup_by_gicon(gicon, 32, 0)
TypeError: Argument 1 does not allow None as a value
````

**Comment by collinss** [comment]
I don't have any Airplay devices, so I can't test this myself. Could you please replace the contents of /usr/share/cinnamon/cinnamon-settings/modules/cs_sound.py with http://pastebin.com/nTTxM6kH and let me know if that works?

**Comment by acidicX** [comment]
Works with your cs_sound.py. No icons for the outputs though.

![bildschirmfoto vom 2016-04-28 10-38-56](https://cloud.githubusercontent.com/assets/1297454/14880117/87d49d02-0d2d-11e6-8bb6-69ca473457ea.png)

For AirPlay/RAOP2 testing:
If you have a Raspberry Pi, you can flash [volumio2](https://github.com/volumio/Volumio2#volumio-2-system-images) on it. It's AirPlay compatible (and really nice to have, too ;-))

**Comment by collinss** [comment]
Unfortunately I don't have the budget for a Raspberry Pi, so I still can't test. I wonder if the missing icons are due to using an icon theme that doesn't have that particular icon. What icon theme are you using? If you can, check if it has the icon ```audio-card```.

**Comment by acidicX** [comment]
I'm using Numix / Numix-Shine. Does not work with Adwaita as well though.

Adwaita has those:
````
./Adwaita/scalable/devices/audio-card-symbolic.svg
./Adwaita/scalable/devices/audio-speakers-symbolic.svg
./Adwaita/scalable/devices/audio-headset-symbolic.svg
./Adwaita/scalable/devices/audio-input-microphone-symbolic.svg
./Adwaita/scalable/devices/audio-headphones-symbolic.svg
./Adwaita/scalable/devices/media-optical-cd-audio-symbolic.svg
./Adwaita/scalable/mimetypes/audio-x-generic-symbolic.svg
./Adwaita/scalable/status/audio-volume-muted-symbolic.svg
./Adwaita/scalable/status/audio-volume-medium-symbolic.svg
./Adwaita/scalable/status/audio-volume-low-symbolic.svg
./Adwaita/scalable/status/audio-volume-high-symbolic.svg
````

Numix does not seem to provide anything with `audio`.

**Comment by collinss** [comment]
Looks like it's probably an icon theme issue then. I just went ahead and opened a pr for the first issue. I'm not sure what the best way to handle the missing icons is. We could probably find an appropriate replacement in your icon themes, but ultimately, we can't cover all possible use cases. I'll have to consult the higher-up on how to move forward.
