### ISSUE TITLE
(Some) GTK and Icon theming not honoured

### ISSUE THREAD

**Issue by Fjodor42** [linuxmint/Cinnamon#5249]
Might not be a bug as such, and may be because I have used Cinnamon on this machine since way back when.

Anyway, the GTK menu bar colour is black for my windows, no matter which GTK theme I choose, whereas on my other machines, where I use Radiance, it is a nice, light grey.

For some reason, watching the provided screenshot in eog, the title bar has the same colour, and the buttons are opposite what they are on other windows, which I only just now discovered.

Furthermore, I have selected the Suru icon theme, which, again, works well on my other machines, but not on this one.

Hence, I wonder if some old theme settings might be left over from an old version, but still honoured in the new ones (3.0.1 on Ubuntu 16.04 presently, but a problem for quite at least half a year, if not more), and what I might try to eliminate the problem.

**Comment by Fjodor42** [comment]
It would seem that I can't find out how to attach an image, butplease see [https://nephele.molgaard.org/index.php/s/aMedFoed9sBt6We](url)

**Comment by Vahan86** [comment]
@Fjodor42, is this still an issue for you with Cinnamon 3.6?
