### ISSUE TITLE
[GTK] Bug with CSD in Gnome System Monitor

### ISSUE THREAD

**Issue by Sunderland93** [linuxmint/Cinnamon#5252]
Hello. In Cinnamon 2.8.6 and 3.0.1, installed on Ubuntu 16.04 (with GTK+ 3.18), Gnome System Monitor looks like this

![2016-04-24 04 09 43](https://cloud.githubusercontent.com/assets/11344982/14880418/09e5946a-0d72-11e6-97e3-cdd22fda396f.png)

but in LMDE 2 and Debian 8 (with GTK+ 3.14), Gnome System Monitor looks like this

![2016-04-25 19 22 16](https://cloud.githubusercontent.com/assets/11344982/14880500/6fffe89a-0d72-11e6-9cdb-48260bda8309.png)

In Ubuntu, GSM have two window title.

**Comment by JosephMcc** [comment]
Don't see how this is a Cinnamon issue. Ubuntu probably patches the app for their own use and so it works correctly with the their menubars being in the window titlebar on Unity. They do this with a number of apps.
