### ISSUE TITLE
Panel no longer respects "Text scaling factor" after upgrading to Cinnamon 3.0

### ISSUE THREAD

**Issue by sruggier** [linuxmint/Cinnamon#5256]
I have a high DPI monitor that I cope with by setting the `Text scaling factor` setting to 1.5. I just upgraded to Cinnamon 3.0 and now the menu applet, window list, and clock applets have very small text.

Now, given the limited panel real estate, and my propensity to open a large number of windows, I can pretend that this is actually a feature, but I think there should probably be an option in the panel settings to let the user control this behaviour.

**Comment by f2404** [comment]
I've also noticed that the panel font is not affected by the scaling factor setting.

**Comment by leigh123linux** [comment]
Works fine here, I am using cinnamon-3.2.2

**Comment by Vahan86** [comment]
@sruggier, is this still an issue for you with Cinnamon 3.2?

**Comment by JosephMcc** [comment]
Seems  to work fine here on Cinnamon3.4 as well. I can reopen this if there is further info.
