### ISSUE TITLE
Super shortcuts require double-tapping (Menu applet assigned to Super)

### ISSUE THREAD

**Issue by jimbo1qaz** [linuxmint/Cinnamon#5257]
Similar to #3480, but that may be outdated.

Cinnamon 2.8.6, Ubuntu 16.04.

If I have the Super key assigned to the menu applet, I must double-tap any Super-key shortcuts bound to external apps, including clipboard managers and programs. This **does not apply** to shortcuts assigned from **Cinnamon Settings**.

**Comment by NikoKrause** [comment]
Related to https://github.com/linuxmint/Cinnamon/issues/3485
