### ISSUE TITLE
Mapping menu applet to key-combinations should wait for key-release

### ISSUE THREAD

**Issue by jimbo1qaz** [linuxmint/Cinnamon#5258]
Cinnamon 2.8.6, Ubuntu 16.04.

As a workaround for #5257, I can map the menu applet to Ctrl-Super. Unfortunately, this breaks mapping other shortcuts to Ctrl-Super-key. Instead, the menu pops up as soon as I press (don't release) Ctrl-Super, making it difficult to enter the shortcut.

The Ctrl-Super binding should not activate as soon as I press Ctrl-Super. Instead, it should activate when releasing the Super key (second key), for consistency with Ctrl-C, etc.

I'm not sure how to handle cases where the user presses Super first.

**Comment by NikoKrause** [comment]
Related to https://github.com/linuxmint/Cinnamon/issues/3485
