### ISSUE TITLE
LMDE 2 Cinnamon 3 Thunderbird 45 MinTrayR

### ISSUE THREAD

**Issue by FlameFlood** [linuxmint/Cinnamon#5260]
MinimizeToTray addon do not work (not minimizing to tray) in Thunderbird 45 in Cinnamon 3.0.1.
In Mate (1.14.0) all fine.

**Comment by Vahan86** [comment]
@FlameFlood, is this still an issue for you with Cinnamon 3.2?

**Comment by Vahan86** [comment]
@JosephMcc, can we close the issue?
