### ISSUE TITLE
LMDE2 Cinnamon 3: Cinnamon crashes on mouse resizing of a snapped window

### ISSUE THREAD

**Issue by ccprog** [linuxmint/Cinnamon#5262]
Using the mouse for all of this:

1. Maximize the vertical size of a window by dragging the upper and lower border to the limits of the screen. Then, resize the window in any direction by dragging the window border: works as expected.

2. Maximize the vertical size of a window by double-clicking on the title bar. Then, resize the window in any direction by dragging the window border: Cinnamon crashes (going to recovery mode).

3. Maximize the vertical size of a window by double-clicking on the title bar. Then, detach the window from the upper screen limit by moving the title bar down some distance. Then, resize the window in any direction by dragging the window border: works as expected.

LMDE 2 64-bit, Cinnamon 3.0.1, Kernel 3.16, Intel 4 Series Chipset Integrated Graphics Controller, one screen

Window theming is Mint-X, desktop is Crunchy, mouse pointer is DMZ-White

Window effects: active, Cinnamon style, no custom settings

Window tiling: disabled.

Windows settings:
- Titlebar action on double click: vertical maximize
- Titlebar action on middle click: move to background
- Titlebar action on right click: Menu
- Titlebar action on mouse scroll: none
- Window focus behaviour: click
- all other window focus effects are off
- Theshold for move/resize: 24px
- Edge resistance with other windows: on

Mouse settings:
- Left hand mouse
- drag-n-drop threshold: 8px

**Comment by ccprog** [comment]
Might this be related to #4706? I just noticed that for gedit (which has UI elements in the titlebar), double clicking maximizes the window in **both** directions and resizing by dragging is no longer possible.

**Comment by JosephMcc** [comment]
This is a duplicate https://github.com/linuxmint/muffin/issues/226
