### ISSUE TITLE
Area screenshot keyboard shortcuts (shift+print & ctrl+shift+print) are still broken 

### ISSUE THREAD

**Issue by surenenfiajyan** [linuxmint/Cinnamon#5263]
Hi, shift+print and ctrl+shift+print combinations for area grabbing usually don't work. They are guaranteed to work only when holding shift (or ctrl+shift) and doing a quick tap on print button. This issue is quite annoying and still present in Mint 17.3.

A possible solution is to add a little delay before executing 'gnome-screenshot -a' like below 

#!/bin/sh

sleep 0.125
gnome-screenshot -a

**Comment by dandv** [comment]
This is so weird - I have to tap Print Screen *really quick*, or the area screenshot won't work. This isn't a problem in Unity; please fix :)

**Comment by xenopeek** [comment]
This looks to be the same issue (and workarounds) as described in issue #3981.

**Comment by ManIVIctorious** [comment]
I just tried all screenshot/recording shortcuts and they all seem to work for me on Arch Linux with cinnamon 3.0.7 and gnome-screenshot 3.20.1 installed.
Is this still an issue for you with latest cinnamon?

**Comment by JosephMcc** [comment]
Duplicate https://github.com/linuxmint/Cinnamon/issues/3981

**Comment by WHDarling** [comment]
Print Area in linux mint 19-1 cinnamon

Hold shift key first, then hit print screen, the cursor is now turns into a little cross (move mouse to a starting point on the screen) then pick a spot to start by holding down left mouse button and drag to choose area of screen to save (screen changes color where you choice to save is, then a dialog pops up giving you an option to either save of copy to clipboard or save to pictures in home folder.
