### ISSUE TITLE
Cannot map keyboard shortcuts onto Super-Up/Down

### ISSUE THREAD

**Issue by jimbo1qaz** [linuxmint/Cinnamon#5264]
Cinnamon 2.8.6, Ubuntu Studio 16.04.

In System Settings, I cannot map "maximize" to Super-Up. Instead, the field value remains unchanged.

**Comment by jimbo1qaz** [comment]
Manually assigning through dconf-editor works fine.

**Comment by itzexor** [comment]
It seems to work for me (in the latest development version). I get a popup asking if i'm sure because those are the default shortcuts for tile snap up and tile snap down. Did you possibly click through that? Try unsetting those shortcuts first, if not.

**Comment by JosephMcc** [comment]
Could you retest this under Cinnamon3 and see if it is still an issue?

**Comment by lindwurm** [comment]
works fine for me on Cinnamon3

- Ubuntu 16.04.1
- x86_64
- Linux 4.4.0-36-generic
- Cinnamon 3.0.6-20160628040158-xenial from [ppa:kranich/cinnamon](https://launchpad.net/~kranich/+archive/ubuntu/cinnamon)
