### ISSUE TITLE
Hot corner indicator not rotated

### ISSUE THREAD

**Issue by ManuelSchneid3r** [linuxmint/Cinnamon#5268]
![bildschirmfoto vom 2016-05-03 14-42-23](https://cloud.githubusercontent.com/assets/3252315/14983423/8fe28a9a-113d-11e6-88d0-799bc3569775.png)

The indicator that the corner was activated is not rotated. It is the idicator of the top left corner. The "waves" move to the bottom right direction.

**Comment by JosephMcc** [comment]
Not sure what theme you are using but that's a theme issue not a cinnamon issue.

**Comment by ManuelSchneid3r** [comment]
Are you sure? Mint-X and Mint-Y is affected too. The indicators look the same. I'm not sure if you understood what I mean.

Indicator bottom left
![image](https://cloud.githubusercontent.com/assets/3252315/14992919/ba15a416-1168-11e6-8ace-e981cf3f9916.png)

Indicator bottom right
![image](https://cloud.githubusercontent.com/assets/3252315/14992924/be85ebb4-1168-11e6-8738-be8a7573e5d2.png)

**Comment by JosephMcc** [comment]
Works fine here in Mint-X and I just fixed this issue a day or two ago in mint-y.
