### ISSUE TITLE
Network Applet shows "Not Connected" when one of device isn't connected

### ISSUE THREAD

**Issue by anandrkris** [linuxmint/Cinnamon#5270]
I have a Data card device, with an inbuilt wi-fi router, which I have connected through wireless.
Now this device is also plugged into my Mint box for charging and shows up as HUAWEI mobile. 
Although am connected to network wirelessly, network applet shows no collection till I disable the HUAWEI item.
![before disable1](https://cloud.githubusercontent.com/assets/4663298/15019522/0b614d1a-123c-11e6-8c4d-67206be70831.png)
After Disable shows wireless icon as expected.
![after disable](https://cloud.githubusercontent.com/assets/4663298/15019535/1c95f9d2-123c-11e6-825f-20a2c14114ff.png)

**Comment by AlbertJP** [comment]
That's the symbol for an established wired connection. Which symbol is shown if you have only Huawei mobile turned on?

**Comment by anandrkris** [comment]
You're right, just realized its not actually "Not Connected"  - when it is connected it is indeed a darker shade. "Connected to the wired network" is the tooltip as well.
Aside - How can I permanently disable it to connect as a wired connection?

**Comment by leigh123linux** [comment]
@anandrkris 
Try unchecking the 'connect automatically' box in 'network-settings' / wired / identity

**Comment by AlbertJP** [comment]
Please post the line about your Huawei device from the output of:
`nmcli con`

**Comment by anandrkris** [comment]
@AlbertJP  - I believe this is not a defect. I tried @leigh123linux suggestion and seems to work anmd doesn't connect now.

If at all there is an issue, it is probably cosmetic with bit of resemblance of icons for connected and not connected. 
CC @JosephMcc

**Comment by JosephMcc** [comment]
Ok, I'm going to go ahead and close this since it seems the actual issue is resolved.
