### ISSUE TITLE
"Test sound" window has no controls or Close button

### ISSUE THREAD

**Issue by f2404** [linuxmint/Cinnamon#5273]
The "Test sound" window (Sound -> Output -> Test sound) has no controls or Close button - it can only be closed by Alt-F4.
Cinnamon 3.0.1, Arch Linux.

**Comment by mtwebster** [comment]
This is a theme issue, if i recall, but we'll add a button as well to avoid this scenario.

**Comment by JosephMcc** [comment]
Some metacity themes don't show the close button on the window titlebar in dialogs which is why you don't see one.

**Comment by f2404** [comment]
I'm using Adwaita. All other windows I could test had either "Close" or "Cancel" button, or the titlebar controls.
I'd prefer the "Test sound" window having "Close" button, too.

**Comment by JosephMcc** [comment]
I agree. It needs to be fixed by us.

**Comment by f2404** [comment]
Thanks.
