### ISSUE TITLE
Low pitched bell sound [Cinnamon 3.0.1]

### ISSUE THREAD

**Issue by petrucci4prez** [linuxmint/Cinnamon#5276]
The normal bell sound is supposed to some high-pitched sound, but since Cinnamon 3 upgrade it sounds like it's several octaves lower. To reproduce (there are many possible examples) go to Nemo, switch the file location pathbar to entry-mode, clear the entry box, and press backspace in the empty entry box to activate the bell sound

The source sound file (I think) is /usr/share/sounds/freedesktop/stereo/bell.oga, and this sounds normal when I play it through an audio player.

**Comment by bendovercz** [comment]
I had a same issue. Almost shit my pants first time I heard it. I got rid of that sound by unloading pcspkr module from kernel.

**Comment by f2404** [comment]
Looks similar to #5253

**Comment by JosephMcc** [comment]
Duplicate
