### ISSUE TITLE
Problem with the fonts

### ISSUE THREAD

**Issue by Alextrestrestres** [linuxmint/cinnamon#5277]
Can someone help me with this? Thanks!!!!
![captura de pantalla de 2016-05-06 22-20-08](https://cloud.githubusercontent.com/assets/19230560/15085230/3d79fdc6-13d9-11e6-8da5-aeb11251470e.png)

**Comment by Vahan86** [comment]
@Alextrestrestres, is this still an issue in Cinnamon 4.2?

**Comment by icarter09** [comment]
Linux Mint 19.2
Cinnamon 4.2.4

I'm not able to reproduce this issue. 

@Alextrestrestres if you are still experiencing this bug, reopen a new ticket with the steps listed to reproduce the bug. Thanks.
