### ISSUE TITLE
Suggestion: Windows Quick List Multi Monitor Improvments

### ISSUE THREAD

**Issue by imarkskinner** [linuxmint/Cinnamon#5278]
Suggestion 1
The windows quick list is very useful at showing all windows spread across all workspaces and telling you what window is where. However it's not very good at splitting your windows up by monitors.
All windows from monitor 1 and 2 and beyond are jumbled together so long as they're all on the same workspace. I think it would be a vast improvement if it were organized by Workspaces first and sub organized by monitors, it should have this layout (forgive the crappy formatting)

```
-------------------------
Workspace 1
----Monitor 1
         Window 1:1:1
         Window 1:1:2
----Monitor 2
        Window 1:2:1
        Window 1:2:2
--------------------------
Workspace 2
---- Monitor 1
        Window 2:1:1
----Monitor 2
        Window 2:2:1
-------------------------

```

Hopefully this diagram gets my point across because I really feel it could use some more organizing, at the moment it's a bit of a disaster with multi monitor setups.

Suggestion 2
The window quick list should have the same contextual menu for a right click as the window list does. Currently right clicking a window in the window list gives you a list of options regarding moving, minimizing, maximizing and closing that window. Right clicking a window in the window quick list however just gives that window focus.
The window list and the window quick list give fundamentally similar functionality so they should have near identical behavior when you interact with it.

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
