### ISSUE TITLE
Prevent resize in top right of window

### ISSUE THREAD

**Issue by Iambecomeroot** [linuxmint/Cinnamon#5279]
In some applications (such as chromium), when I put my cursor in the very to right of the window, I get a resize cursor. I think that all close buttons should be right against the edge of the screen so they are trivial to find with your mouse. How can I disable applications from implementing this stupid behavior?

Linux mint 17.2. Cinnamon 2.6.13. Unfortunately I can't seem to take a screenshot of the mouse pointer but hopefully you know what I am talking about.

**Comment by JosephMcc** [comment]
You can't as far a I know. It's really up to the metacity theme being used how much space is present in that area around the close button. Using mint-x and maximizing a window, putting my cursor all the way in the upper right corner and clicking closes the window.

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
