### ISSUE TITLE
[LMDE2, Cinnamon 3.0.1] VLC systray icon missing

### ISSUE THREAD

**Issue by kmkom** [linuxmint/cinnamon#5280]
Whatever setting i tried, i can't get the VLC systray icon.
And why does the media change pop-up appear at the top left?
For detail check the screen-shot.

In Linux Mint 17.3, Cinnamon 2.8.8 the systray icon appears as expected.
![screenshot](https://cloud.githubusercontent.com/assets/15555865/15093523/294f00be-148b-11e6-81c5-297038d56690.png)

**Comment by kolorafa** [comment]
For me it looks like you don't have "System Tray" applet on your taskbar.
Maybe because of some "bug" it unloaded? 

Because i don't see any "status icons" from any other app.
Try to run skype or any other app with icon and/or post your Applet list, check if you have "System Tray" applet running.

**Comment by icarter09** [comment]
@kmkom are you still experiencing this issue?

**Comment by kmkom** [comment]
Yes, the problem is still present in Mint 19.2, Cinnamon 4.2.4 as described above.

**Comment by icarter09** [comment]
@kmkom VLC is already contained within the systray by way of the Sound applet. Within the Sound applet, there is the **Launch player** dropdown, which has VLC as a default option.

**Comment by kmkom** [comment]
Thank you, yes I know that VLC is now integrated in the Sound applet. The systray-setting within VLC unfortunately has no influence on this. But that is ok for me. But I don't like the pop-up, which unexpectedly appears in the **upper left corner** of the screen...

**Comment by JosephMcc** [comment]
What happens if you disable showing the popup in the settings? Do you get a normal cinnamon notification?

**Comment by leigh123linux** [comment]
You need to turn off 'hide system tray icons' in sound applet configure.
![Screenshot from 2019-11-29 17-07-18](https://user-images.githubusercontent.com/1299302/69883176-e1d8d880-12ca-11ea-91fd-ab3cfa816640.png)
