### ISSUE TITLE
Hotkey when screen is locked.

### ISSUE THREAD

**Issue by vveliev** [linuxmint/Cinnamon#5282]
Hey I wound it a bit inconvenient, when i try to change volume or mute sound I have to unlock screen.

Not sure if it's best to make it enabled by default or have setting that allows to enable certain hotkey to be accessible when screen is locked. 

I'm not familiar with this project, but there is python module , that may be easily added to the core of the cinnamon. https://github.com/chrisspen/freekey

thanks.

**Comment by f2404** [comment]
I doubt that allowing to control the machine while it's being locked is actually a good idea...

**Comment by vveliev** [comment]
well limited functionality may be a good idea  ;) .

Ex. you have computer running, playing music LOUD.  You get phone call, need to mute sound .... you have to unlock your screen first....or just press one button. (OR shut down if it's not your user and you cannot go far enough to speak ..... extreme  case ;) ..but possible   ) 

I have noticed that OSX does allow you to control volume with lock. 

As of permission restriction and action restriction. No one can delete files open send emails, etc ....
You do have ability to reboot and shutdown someone else's PC even with lock screen.... so adding volume control may be helpful ;)

**Comment by JosephMcc** [comment]
I know it has been discussed in the past to show some things in the lockscreen. Allowing things like music playback controls or letting you know you have notifications. I believe some other desktops such as gnome shell allow this and I see where it could come in handy.

**Comment by anandrkris** [comment]
https://github.com/linuxmint/Cinnamon/issues/1900
Related issue

**Comment by JosephMcc** [comment]
You will be able to adjust the volume in the new screensaver for Cinnamon 3.2
