### ISSUE TITLE
Gtk-CRITICAL error on opening "Power off..." dialog

### ISSUE THREAD

**Issue by f2404** [linuxmint/Cinnamon#5284]
`cinnamon-session[637]: Gtk-CRITICAL: t+8306.66200s: gtk_image_set_from_icon_name: assertion 'GTK_IS_IMAGE (image)' failed`
Appears each time the dialog gets opened.

Arch Linux, Cinnamon 3.0.1.

**Comment by JosephMcc** [comment]
Duplicate https://github.com/linuxmint/cinnamon-session/issues/70
