### ISSUE TITLE
Cinnamon should be less sensitive to mouse movements when display is powered off

### ISSUE THREAD

**Issue by jf99** [linuxmint/Cinnamon#5285]
To save energy, I have configured Cinnamon to switch off the display after 5 minutes of inactivity. Unfortunately the display wakes up quite often because I have a very sensible mouse. For example, writing something on a paper lying on my desk already causes the mouse to move a few pixels and wakes up my display.

To solve this, Cinnamon should not wake up the display once it's dark, unless it is really clear that the user moves the mouse intentionally.

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
