### ISSUE TITLE
Make menu editor more visible

### ISSUE THREAD

**Issue by pokoli** [linuxmint/Cinnamon#5291]
In cinnamon the cinnamon-menu-editor command it is used to edit the menu entries, but currently it is not avaiable on the menu, so its dificult to discover for new users. 

I propose to add them to the System menu, in order to make it easly searchable.

**Comment by pokoli** [comment]
I can work on this if someone can guide me on how to modify the default values for menu installation.

**Comment by f2404** [comment]
Actually, the "menu editor" menu entry can be enabled through the menu editor. Don't you think this is enough?

**Comment by JosephMcc** [comment]
You can also right click the applet and choose configure just like any other applet to get to it.

**Comment by pokoli** [comment]
El 12/05/16 a les 12:49, Igor ha escrit:
> Actually, the "menu editor" menu entry can be enabled through the menu
> editor. Don't you think this is enough?
Yeaaaah!!! Didn't think about it. That solved the problem for me, but 
new people will face the same issue, so i think it should be enabled by 
default on new installations.


-- 
Sergi Almacellas Abellana
www.koolpi.com
Twitter: @pokoli_srk

**Comment by JosephMcc** [comment]
Configuration for applets is handled through the applet right click context menu. The menu applet is the same as any other. If a new user wants to be able to configure the settings for any applet they are going to have to learn the basics of the DE they are using.
