### ISSUE TITLE
Weird graphics+flicker after returning from idle

### ISSUE THREAD

**Issue by GeorgeTG** [linuxmint/cinnamon#5293]
`I am not quite sure if this is cinnamon, or driver related and if this is the correct place to report the bug, since I am using cinnamon on arch linux.`

After leaving my computer idle for about an hour and the screen is turned off automatically,  when trying to "wake up" by moving the mouse, my primary monitor  starts turning on and off, staying and off for about the same interval and the graphics look really weird. My second monitor works correctly though.
I'm using the open source AMD driver.

dmesg:

> [    4.129048] fbcon: radeondrmfb (fb0) is primary device
> [    4.187227] Console: switching to colour frame buffer device 240x67
> [    4.192004] radeon 0000:01:00.0: fb0: radeondrmfb frame buffer device
> [    4.202456] [drm] Initialized radeon 2.43.0 20080528 for 0000:01:00.0 on minor 0
> [    4.202496] snd_hda_intel 0000:01:00.1: enabling device (0000 -> 0002)
> [    4.202609] snd_hda_intel 0000:01:00.1: Handle vga_switcheroo audio client
> [    4.202612] snd_hda_intel 0000:01:00.1: Force to non-snoop mode
> [    4.263603] input: HDA ATI HDMI HDMI/DP,pcm=3 as /devices/pci0000:00/0000:00:01.0/0000:01:00.1/sound/card2/input20
> [    4.263668] input: HDA ATI HDMI HDMI/DP,pcm=7 as /devices/pci0000:00/0000:00:01.0/0000:01:00.1/sound/card2/input21
> [    4.263722] input: HDA ATI HDMI HDMI/DP,pcm=8 as /devices/pci0000:00/0000:00:01.0/0000:01:00.1/sound/card2/input22
> [    4.263778] input: HDA ATI HDMI HDMI/DP,pcm=9 as /devices/pci0000:00/0000:00:01.0/0000:01:00.1/sound/card2/input23
> [    4.263834] input: HDA ATI HDMI HDMI/DP,pcm=10 as /devices/pci0000:00/0000:00:01.0/0000:01:00.1/sound/card2/input24
> [    4.263894] input: HDA ATI HDMI HDMI/DP,pcm=11 as /devices/pci0000:00/0000:00:01.0/0000:01:00.1/sound/card2/input25
> [    5.511629] e1000e: eno1 NIC Link is Up 1000 Mbps Full Duplex, Flow Control: None
> [    5.511669] IPv6: ADDRCONF(NETDEV_CHANGE): eno1: link becomes ready
> [   14.295892] fuse init (API version 7.24)
> [ 8862.631070] [drm:si_dpm_set_power_state [radeon]] _ERROR_ si_restrict_performance_levels_before_switch failed
> [ 8880.900162] traps: cinnamon-screen[1198] trap int3 ip:7f7542eb07eb sp:7fff1c145770 error:0
> [13038.661350] perf interrupt took too long (2512 > 2495), lowering kernel.perf_event_max_sample_rate to 50100
> [67652.146105] snd_hda_codec_hdmi hdaudioC2D0: HDMI ATI/AMD: no speaker allocation for ELD

Attaching screenshots too:
![deepinscreenshot20160512225058](https://cloud.githubusercontent.com/assets/6360940/15228582/8c4551ce-1895-11e6-9152-b69c1d6d0bb6.png)
![dsc_1193](https://cloud.githubusercontent.com/assets/6360940/15228583/8c469d36-1895-11e6-8a7d-e0d09f3f2017.JPG)

**Comment by icarter09** [comment]
@GeorgeTG are you still experiencing this issue?
