### ISSUE TITLE
Maximized gnome apps in cinnamon 2.8.7 and 3.x missing half of titlebar

### ISSUE THREAD

**Issue by slartibart70** [linuxmint/Cinnamon#5294]
Maximizing a gnome app, like evince, shows the titlebar of the window only in half - the rest is outside the upper part of the screen
Happens in 2.8.7 and 3.0.x in fedora23/cinnamon spin

**Comment by JosephMcc** [comment]
Duplicate https://github.com/linuxmint/Cinnamon/issues/4611
