### ISSUE TITLE
Ill behave in systray

### ISSUE THREAD

**Issue by reasonset** [linuxmint/Cinnamon#5302]
### TaskCoach

The icon in systray when showing windows or start with iconified, but not iconify in systray but application ends when window is closed.

### DropBox

Dropbox icon is not shown in systray if startup with no delay, but DropBox overwrites delay by itself.

This issue came from Cinnamon 3.0.0.

**Comment by JosephMcc** [comment]
Please search the open issues for "systray". There are already plenty of them you could add to. Thanks.

**Comment by reasonset** [comment]
Sorry, I considered not enough.

I think Dropbox icon issue is already known, but TaskCoach issue is not.
I couldn't choose appropriate existing issue for adding it.
(I thought should I add it to VLC icons in systray issue, but TaskCoach issue is "app closed when closing window," not "no avilable icon in systray"...)

I cannot express it well. Sorry.

**Comment by JosephMcc** [comment]
No problem. The systray is problematic and the source of a lot of issues. Would just like to keep them somewhat consolidated and not spread over twenty different open issues.
