### ISSUE TITLE
Cinnamon 3.02 on Ubuntu Studio 16.04 LTS statusIconDistpacher.js not propogating _onTrayIconAdded

### ISSUE THREAD

**Issue by psionprime** [linuxmint/cinnamon#5304]
While researching a method to get the applet, systray@cinnamon.org to work with variable width indicator icons, eg, indicator-multiload, it seems that the event,  _onTrayIconAdded is not propogating the chain of applet <--- statusIconDistpacher.js <--- Cinnamon.TrayManager <--- cinnamon-tray-manager.c

I made a hack for Linux Mint 17.3's Cinnamon (v?) that involved the applet function, _resizeStatusItem, where I trapped "multiload" and forced the width I wanted. This worked well for me, though not a true fix. While the code for the applet in the Cinnamon 3.02 source has not changed, the applied hack no longer works as the function is never called. 

Below is the looking glass log where I placed global.log debug messages at the top of every function. You will see, the event for adding a tray icon is never called at this level:

`
info t=2016-05-16T19:05:10.529Z Entered: _onIndicatorAdded

info t=2016-05-16T19:05:10.530Z Hiding indicator (role already handled): nm-applet

info t=2016-05-16T19:05:10.531Z Entered: _onIndicatorAdded

info t=2016-05-16T19:05:10.531Z Adding indicator: multiload

info t=2016-05-16T19:05:10.531Z Entered: _getIndicatorSize

info t=2016-05-16T19:05:10.574Z _onIndicatorAdded: multiload

info t=2016-05-16T19:05:10.574Z _onIndicatorAdded: 34w, 34h

info t=2016-05-16T19:05:25.699Z Entered: on_panel_height_changed

info t=2016-05-16T19:05:25.700Z Entered: _onBeforeRedisplay

info t=2016-05-16T19:05:25.700Z Entered: _getIndicatorSize

info t=2016-05-16T19:06:11.279Z Entered: _onIndicatorAdded

info t=2016-05-16T19:06:11.279Z Adding indicator: software-update-available

info t=2016-05-16T19:06:11.279Z Entered: _getIndicatorSize

info t=2016-05-16T19:06:11.281Z _onIndicatorAdded: software-update-available

info t=2016-05-16T19:06:11.281Z _onIndicatorAdded: 16w, 16h
`

The above is when the applet started with a larger panel size than normal with two indicators. I resized the panel back to normal. There a couple of debug messages to tell me "multiload" was detected and the icon size at that point in the applet.

I checked the revisions but do not see much change in the C code for a while. So I do not know if this is a mint thing that UbuntuStudio doesn't have...the kernel is 4.04... I don't know and don't have familiarity with Cinnamon to know if I am even researching the right area but will continue on.

**Comment by icarter09** [comment]
@psionprime are you still experiencing this issue?
