### ISSUE TITLE
Any way to use screenlets?

### ISSUE THREAD

**Issue by thockin** [linuxmint/Cinnamon#5307]
I have a robust screenlet config that works well as a "widget layer" in Compiz.  But I have Unity and I want to use Cinnamon.  Is there any way to make screenlets disappear and reappear with a keypress, but keep running?

They don't seem to respond to `wmctrl` "shaded" or "hidden". 

Ubuntu 14.04.

**Comment by JosephMcc** [comment]
Not that I know of. You would probably get more help with this in either the Linux mint forums or #linuxmint-help on IRC. People some times come up with interesting ways to work around things.
