### ISSUE TITLE
Coverflow/Timeline horribly broken on multi monitor

### ISSUE THREAD

**Issue by SethDusek** [linuxmint/cinnamon#5308]
Hi, so I have a 1080p monitor on my left and a 1366x768p primary one, and coverflow/timeline are broken on a multi-monitor setup. Often times my screen "tears" in half while I alt tab. It's hard to explain so [here](http://i.shibe.ml/QmbW5pMez6Ghwxw6zeJCXCeLBG7WK6ohubxvsaKiywmrbL.mp4) is a video demonstrating it.

It doesn't happen with the normal icon + preview or any other icon + alt tab option, only with coverflow and timeline it happens.

I'm on Kernel 4.4, cinnamon version is  Cinnamon 2.8.8 and I'm on intel drivers on Mesa 10.1.3 and I'll check whether this happens on NVIDIA drivers or not

**Comment by leigh123linux** [comment]
coverflow isn't part of cinnamon, you will need to close this issue and refile it here instead

https://github.com/dmo60/CoverflowAltTab/issues

**Comment by SethDusek** [comment]
@leigh123linux https://github.com/dmo60/CoverflowAltTab/issues/59#issuecomment-219625384

**Comment by JosephMcc** [comment]
Coverflow and Timeline are options built into Cinnamon. You can choose them from Cinnamon Settings->Windows->Alt-Tab->Alt-Tab switcher style.

**Comment by leigh123linux** [comment]
@JosephMcc  I didn't notice that they had been added :sleeping:

**Comment by Vahan86** [comment]
@SethDusek, is this still an issue in Cinnamon 4.2?

**Comment by Vahan86** [comment]
@icarter09, can we close this issue since there is no response from OP?
