### ISSUE TITLE
Unable to login after the latest update

### ISSUE THREAD

**Issue by MangTomas23** [linuxmint/Cinnamon#5309]
Here's the message:

Your session only lasted 10 seconds. If you have not logged out yourself, this could mean that there is some installation problem..

View details ~/.xsession-errors file

cinnamon-session[1996]: GLib-GIO-ERROR: t+0.00151s: settings schema 'org.cinnamon.desktop.interface' does not contain a key named 'gtk-overlay-scrollbars'
aborting...

**Comment by Dizirgee** [comment]
hey there, wondering why this is already closed...
i had same issue today. After installing latest updates to 3.0.5 after reboot i couldnt log in, as cinnamon was crashing after login prompt.

Not sure what fixed it, as with last reboot before i finally fixed it, i did two things.
1.  added "gtk-overlay-scrollbars" into /usr/share/glib-2.0/schemas/org.cinnamon.desktop.interface.gschema.xml
    <key type="b" name="gtk-overlay-scrollbars">
	<default>false</default>
	<summary>workaround for crash</summary>
	<description>workaround for crash</description>
   </key>

2. apt-get install --reinstall cinnamon

also not sure if "gsettings-desktop-schemas" has anything to do with this (from the name it could :) ) next thing i was planning was to update this package from testing repo
minterez ~ # apt-cache policy gsettings-desktop-schemas
gsettings-desktop-schemas:
  Installed: 3.14.1-1
  Candidate: 3.14.1-1
  Version table:
     3.20.0-3 300
        300 http://httpredir.debian.org/debian testing/main amd64 Packages
        300 http://httpredir.debian.org/debian testing/main i386 Packages
 *** 3.14.1-1 500
        500 http://debian.lagis.at/debian jessie/main amd64 Packages
        500 http://debian.lagis.at/debian jessie/main i386 Packages
        100 /var/lib/dpkg/status

**Comment by mtwebster** [comment]
Check your cinnamon-desktop-data, libcinnamondesktop4, both should be version 3.0.1
