### ISSUE TITLE
Suspend not working with cinnamon 3 on ubuntu 16.04

### ISSUE THREAD

**Issue by falke34** [linuxmint/Cinnamon#5310]
After a fresh install of ubuntu 16.04 and cinnamon on my Toshiba Z930 notebook suspend is not working when I close the lid of the laptop. Also there is no suspend-button in the shutdown menu.

It must be a problem with cinnamon because when I login into unity on the same system then it works fine.

**Comment by JosephMcc** [comment]
See here: https://github.com/linuxmint/Cinnamon/issues/4060

**Comment by falke34** [comment]
The workaround worked for me. Thank you.
But is it not possible to query some system parameter and decide what environment parameter to set?

**Comment by mpapis** [comment]
could the configuration be done in post-install step of the package that handless it? it would be like few lines of code - I could even write it if I know all the variables
