### ISSUE TITLE
Selecting microphone input device has no effect

### ISSUE THREAD

**Issue by areynoua** [linuxmint/cinnamon#5311]
Hello, I'm on Linux Mint Debian Edition 2 / Cinnamon and since some weeks It's seems that selecting an input device in the sound panel has no effect.
I have 2 microphone, one embedded and one on USB headset. For output device I'm able to select either headset or internal speakers. But for microphone this has no effect, the internal is always used.

I think that the error occurred for first time when it was made possible to actually use internal speaker when a USB headset was plugged in.

Sorry if I don't report bug at the good place or if I made mistakes speaking english…

**Comment by bbbjjj** [comment]
Cinnamon 3.2.7

I can reproduce this behaviour. Problem is in cs_sound.py. Method activeInputUpdate never gets called and inputId not gets set.

`File "/usr/share/cinnamon/cinnamon-settings/modules/cs_sound.py", line 675, in setActiveDevice
    if id != None and id != getattr(self, type+"Id"):
AttributeError: Module instance has no attribute 'inputId'`

**Comment by icarter09** [comment]
@areynoua are you still experiencing this issue?

**Comment by areynoua** [comment]
Sorry, I moved back on Debian for now so I can not check.

**Comment by icarter09** [comment]
@areynoua no worries and thanks for the update.
