### ISSUE TITLE
Cinnamon Places not using color set for folders in Nemo

### ISSUE THREAD

**Issue by bananabob** [linuxmint/Cinnamon#5315]
In the Cinnamon menu option PLACES does not use the settings for colour folders as does NEMO? What I mean by this is when I set a folder to be a certain color using the file manager, the colour of the folder is not shown in the Cinnamon PLACES – the default colour is used.

**Comment by mtwebster** [comment]
Fixed by https://github.com/linuxmint/Cinnamon/commit/61dbeb727f70edc67ef7574ee2646cfedb26b39d
