### ISSUE TITLE
consider defaulting the overlay scrollbar feature to be disabled

### ISSUE THREAD

**Issue by calestyo** [linuxmint/Cinnamon#5316]
Hey.

This is a follow up to #5306:
As cinnamon is for most people the GNOME without any crap that makes the later unusable on the desktop, you may want to consider disabling the overlay scrollbar feature per default.
(Although I'd be okay if you don't want to, since it's configurable :-) )

The reasons for why it think it should be default to off are basically the same as given in #5306.

Cheers,
Chris.

**Comment by marga-debian** [comment]
+1 to this.  We have disabled overlay scrollbars in Debian's Cinnamon already.

**Comment by JosephMcc** [comment]
We talked about this when they were first introduced and decided to leave them enabled. Obviously not everyone will agree but they are easy to disable in Cinnamon now. If enough people complain they will end up disabled by default :)

My 2 cents. I actually like them and specific apps can choose to disable them in their code when needed.
