### ISSUE TITLE
Window headbar idea

### ISSUE THREAD

**Issue by Vali19n** [linuxmint/Cinnamon#5317]
Can you add an option to hide the title in the headbar of any window and to show the minimize/close buttons at the same height as the menu buttons? It should be off by default.
Example:
![image](https://cloud.githubusercontent.com/assets/13157676/15392541/63167108-1dd0-11e6-9e26-6e4e523a78c3.png)

**Comment by alxgvr** [comment]
I think it is better to add global menu applet to the applets set, so when you activate it - menu bar will be removed from window, and will be displayed on the panel (like in Unity or OsX).

I do not like massive window decorations too. I like light and simple windows like in Unity. Very convenient on small laptop screens.

**Comment by Vali19n** [comment]
I want to get rid of the title, not the menu bar, but thank you for the recommendation.

**Comment by lestcape** [comment]
@alxgvr if there are a function to do what @Vali19n want, the global menu could call this function on windows maximized and then remove the menu panel. The effect will be the same that occurs on Unity or OsX. But is more easy for what you want if there are a function to decorate/undecorate a windows directly inside cinnamon, actually there are not a function like this.

**Comment by ManIVIctorious** [comment]
Ubuntu's unity has this feature and I have to admit it would be quite nice

http://arstechnica.com/information-technology/2014/02/ubuntu-desktop-moving-application-menus-back-into-application-windows/

**Comment by lestcape** [comment]
@ManIVIctorious I disagree with almost all the inventions of Canonical in Unity, but i agree this is not an annoying feature if will be optional.

**Comment by ManIVIctorious** [comment]
Totally agree with you, of course it should be optional

**Comment by ntfs1984** [comment]
Well...This feature is named "GTK CSD", and works in Cinnamon, but depends on application, but not on DE.

![screenshot from 2016-06-18 13-03-35](https://cloud.githubusercontent.com/assets/12632755/16170251/21281598-3555-11e6-976c-9b6d8ef34fb4.png)

**Comment by Vahan86** [comment]
I would be happy to see this feature in Cinnamon.

**Comment by alxgvr** [comment]
Here is how I love (it was mint 17.2, can`t reproduse it again)

![gmenu1](https://cloud.githubusercontent.com/assets/19569543/17789460/efa36be6-659a-11e6-8121-c1faabb8ade6.png)

**Comment by JosephMcc** [comment]
This isn't the type of thing we are really interested in having in Cinnamon by default. Things like menubars in titlebars, global menus, removable window decorations and the like are outside of the scope of what we plan on implementing at this point.

**Comment by lestcape** [comment]
@Vali19n, I think you need to request this type of things in the muffin repository https://github.com/linuxmint/muffin, not here. One thing is as @JosephMcc say a Cinnamon default option, and another different, the possibility of use this option in a third-party application. Without the muffin support, this option will not be possible at all, by default or not.

An option like this will not have priority over others if the others are interesting for cinnamon and this option not, but at less will be possible that in some moment someone implemented this.

Another way is request this on gnome Mutter(https://github.com/GNOME/mutter), if this will be implemented will be more easy port the code later to cinnamon.

**Comment by JosephMcc** [comment]
Moving this request to the muffin repo isn't going to change anything.

For the most part all Cinnamon related issues are fine here regardless of weather or not they effect Cinnamon, Muffin, cinnamon-settings-daemon, etc. It seems a bit much to expect typical users to understand the split in the underlying packages.

The one exception is Nemo since it seems a good number of people use it outside of Cinnamon.

**Comment by lestcape** [comment]
Well, if it's in this way, I will change this sentence: "This isn't the type of thing we are really interested in having in Cinnamon by default" by this: "This isn't the type of thing we are really interested in having in Cinnamon", because by default or not, if there are not support will not be possible. Sorry if i missing understand.
