### ISSUE TITLE
Faulty Reporting With Power Applet

### ISSUE THREAD

**Issue by napperley** [linuxmint/Cinnamon#5319]
Every time the Power applet is clicked the battery level for the Logitech mouse (**M185**) is always at 70%. Both the Logitech mouse and keyboard (**K270**) always have even battery level percentage values, with the second digit of each value always stuck at 0 (eg mouse is 70% and keyboard is 20%). Currently using **Linux Mint 17.3** (64 bit) with **Cinnamon 2.8.8** on a ThinkCentre M91p. Similar issues also occur on a Toshiba Tecra M9 (using Linux Mint 17.3 with Cinnamon 2.8.?) which also uses the same Logitech mouse and keyboard.

Very clear that the power reporting is never accurate and has been this way since **Linux Mint 17** (Main Edition).

**Comment by JosephMcc** [comment]
I'm not sure this is a problem with Cinnamon but with the info that the Logitech devices provide. I use them as well and this has always been the case. Have you tried other Linux Desktop environments where these seemed to work properly?

**Comment by leigh123linux** [comment]
Cinnamon can only report  the info that upower provides it, this is definitely a upower issue.

```
$ upower -d
Device: /org/freedesktop/UPower/devices/mouse_0003o046Do4013x0006
  native-path:          /sys/devices/pci0000:00/0000:00:13.0/usb5/5-4/5-4:1.2/0003:046D:C52B.0003/0003:046D:4013.0006
  vendor:               Logitech, Inc.
  model:                M525
  serial:               724A11AC
  power supply:         no
  updated:              Fri 20 May 2016 07:01:21 BST (102 seconds ago)
  has history:          yes
  has statistics:       no
  mouse
    present:             yes
    rechargeable:        yes
    state:               discharging
    warning-level:       none
    **percentage:          90%**
    icon-name:          'battery-full-symbolic'
```
