### ISSUE TITLE
Cinnamon Control Themes not loading properly version: 2.7.8

### ISSUE THREAD

**Issue by StefanMallia** [linuxmint/Cinnamon#5320]
On debian testing Cinnamon does not load these themes properly.
![screenshot from 2016-05-20 12-14-02](https://cloud.githubusercontent.com/assets/5004438/15424734/9083a278-1e84-11e6-82ae-1932ff122e59.png)

Resulting in windows that look like this:

![screenshot from 2016-05-20 12-17-15](https://cloud.githubusercontent.com/assets/5004438/15424829/feca5d4e-1e84-11e6-9669-708a04f71069.png)

This is not just with numix but with all themes that are not Adwaita

**Comment by JosephMcc** [comment]
This isn't cinnamon's fault. Debian testing is using gtk3.20. Make sure you use versions of the themes that are compatible.
