### ISSUE TITLE
ALT+F2 and keycombinations do not reparent process to session process

### ISSUE THREAD

**Issue by ManuelSchneid3r** [linuxmint/cinnamon#5321]
![image](https://cloud.githubusercontent.com/assets/3252315/15428943/93dfe0de-1e9e-11e6-9c81-26aa81393ae5.png)

albert is run using Alt+F2 and terminator using a key combination set in the settings. The processes should be children of  the session like all others. This may introduce problems with proper termination of processes.

![image](https://cloud.githubusercontent.com/assets/3252315/15429001/deaaed7a-1e9e-11e6-8cbe-1a6347d69d83.png)

**Comment by icarter09** [comment]
@ManuelSchneid3r are you still experiencing this issue?

**Comment by Vahan86** [comment]
@icarter09, can we close the issue since there is no response from OP?

**Comment by Vahan86** [comment]
@icarter09, can we close the issue since there is no response from OP?
