### ISSUE TITLE
[bug] some bugs inherited from gnome 3

### ISSUE THREAD

**Issue by startas** [linuxmint/Cinnamon#5325]
A few bugs i noticed that cinnamon has inherited from gnome:
1) Doesnt matter what graphics, intel hd 4400 or nvidia 840m, about 2/5 of screen at the top is tearing and without vsync.
2) Very bad GUI performance when pc is being used - i.e., its enough to play a simple youtube video, and the whole GUI becomes super choppy, like a game running at 5 fps...

**Comment by AlbertJP** [comment]
This bug needs more information, such as Linux distribution, Cinnamon version and model of computer.
If Gnome does this too then there's probably another reason why you have problems running a composited desktop environment on your computer.

**Comment by Vahan86** [comment]
@startas, is this issue still relevant to Cinnamon 3.2?

**Comment by JosephMcc** [comment]
More info was requested a long time ago and never given.
