### ISSUE TITLE
no indicators for non approved applets

### ISSUE THREAD

**Issue by Evil-Wayz** [linuxmint/Cinnamon#5327]
I use Gnome weather and lunar indicator.  I get notifications, but there is no icon on the panel bar.  Running them from terminal shows they are up and running.  I also have bluetooth up and running, but there is no bluetooth icon.  These problems are not present when I run a different session.

**Comment by Vahan86** [comment]
@Evil-Wayz, is this still an issue for you with Cinnamon 3.2?

**Comment by JosephMcc** [comment]
Closing due to lack of info. No cinnamon version, distro, whether or not indicators are enabled in settings, etc.
