### ISSUE TITLE
menu applet: weird key navigation behaviour, when first pressed TAB

### ISSUE THREAD

**Issue by NikoKrause** [linuxmint/Cinnamon#5333]
Open menu, press TAB key, press RIGHT key two times. You get the following gap:
![weirdnavigationwithtab](https://cloud.githubusercontent.com/assets/8415124/15491106/a9998980-216d-11e6-967e-4e0048a93028.png)

It seems as it is possible to navigate through the menu. You can see see where your are,
if you press right, because then a gap opens. If you press left, the gap vanishes.
![weirdnavigationwithtab2](https://cloud.githubusercontent.com/assets/8415124/15491182/3fcf5786-216e-11e6-9192-da18320316d9.png)

**Comment by JosephMcc** [comment]
Ok. Can reproduce this one.
