### ISSUE TITLE
Mint-Y theme suggestion. 

### ISSUE THREAD

**Issue by alxgvr** [linuxmint/Cinnamon#5335]
May I suggest to make "controls" bar grey in Mint-Y Darker Theme? 
Screenshots attached (Paper Theme is used here. Also Ambiance Flat for "windows borders")﻿

I believe grey+black (or light grey + dark grey) looks good :)

![image](https://cloud.githubusercontent.com/assets/19569543/15537199/0a48ae78-2286-11e6-9483-bafa370f5037.png)
![image](https://cloud.githubusercontent.com/assets/19569543/15537200/0a48eb90-2286-11e6-9034-8f13edae7529.png)

**Comment by collinss** [comment]
You should probably post this issue here instead: https://github.com/linuxmint/mint-y-theme as Mint-y is not part of Cinnamon.
