### ISSUE TITLE
gcdemu: no tray icon or window opens in Cinnamon desktop

### ISSUE THREAD

**Issue by human-human** [linuxmint/Cinnamon#5336]
Linux Mint 17.3 'Rosa' Cinnamon 64-bit
What I did:

http://www.hecticgeek.com/2014/05/cdemu-disc-drive-emulator-ubuntu-14-04/:
I installed gcdemu with these commands from the website above:

sudo apt-add-repository ppa:cdemu/ppa
sudo apt-get update
sudo apt-get install gcdemu

(Installation finished without errors)

I tried to start gcdemu from the start menu and cdemu-daemon started running (Cinnamon gave a "device plugged in" sound when cdemu-daemon started), but no window or tray icon showed up as I was expecting.

I started a terminal and typed:

pkill cdemu   #to kill the cdemu-daemon and related processes
gcdemu     #to start gcdemu via terminal, to get some information

The terminal message that I got back was:
"AppIndicator tray icon mode" (without the quotes), but again, no tray icon or window. (gcdemu did not crash here, it kept running)

I tried installing lxde-session and logged into the lxde desktop. The tray-icon for gcdemu was there when I logged in, as expected, and it worked fine. After logging back into Cinnamon, no tray icon or window from gcdemu...

**Comment by collinss** [comment]
Did you try disabling indicators? (open cinnamon-settings, go to General, turn off Enable support for indicators, restart cinnamon)

**Comment by human-human** [comment]
I tried it just now. What i did:
disabled indicators as you described, then restarted my pc (just to make sure cinnamon restarts too)
It does not work
