### ISSUE TITLE
Cinnamon should fall back to no-extensions no-applets if it crashed on starting

### ISSUE THREAD

**Issue by marga-debian** [linuxmint/Cinnamon#5339]
Currently the cinnamon-launcher script tries to start cinnamon and if it fails it then starts the "fallback mode" which consists of running gnome-panel (or tint2) and metacity.

Before falling back to programs that may or may not be installed in the machine, I think that it would make sense to try starting cinnamon with no extensions or applets enabled. As reported in many other issues,extensions or applets that are outdated with respect to the current cinnamon may cause the session to crash, and it makes sense to have the fallback mode take care of that.

See for example: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=785336 for a case of a user that had a bad experience as cinnamon crashed due to an extension that was no longer supported.

**Comment by JosephMcc** [comment]
> Before falling back to programs that may or may not be installed in the machine

As far as I see Cinnamon depends on metacity and gnome panel or tint2 being installed https://github.com/linuxmint/Cinnamon/blob/master/debian/control#L101. If this is changed for some reason in debian, they should fix it. That mechanism is there for exactly this reason. I would also like to point out when installing an extension like opacify windows, if you try to activate it, a dialog pops up warning you that it is incompatible with the current Cinnamon version. At least in Cinnamon 3.0.6. Possibly that doesn't happen in the version used in the debian bug report.

The fallback session using metacity is a far more usable desktop than what you would get starting cinnamon with no applets.
