### ISSUE TITLE
OOM at Cinnamon session startup

### ISSUE THREAD

**Issue by ensastiga** [linuxmint/Cinnamon#5341]
This issue happens at random times since updating to Cinnamon 3.0.2 in Debian 8 (testing). Login with  LightDM but Cinnamon never fully loads (visually only the wallpaper) meanwhile there is high CPU usage and Ctrl + Alt + ESC is the only way out

[outmemerror.txt](https://github.com/linuxmint/Cinnamon/files/287609/outmemerror.txt)
[syslog.txt](https://github.com/linuxmint/Cinnamon/files/288067/syslog.txt)

edit: included syslog file

**Comment by leigh123linux** [comment]
Cinnamon 3.0.2 is EOL, if you can reproduce with cinnamon 3.8.x feel free to reopen.
