### ISSUE TITLE
Can't fullscreen correctly some gnome applications.

### ISSUE THREAD

**Issue by Lukypie** [linuxmint/Cinnamon#5343]
I don't know if that's releated to gnome-applications such as eog (the gnome image viewer) but when I open an image with it and then resizing moving it on the top, it isn't resized correctly and I have to double click on the bar to fill the space correctly (in fact, the borders were out of the screen) this seems to happen with all the gtk3 programs i think.

**Comment by JosephMcc** [comment]
I've seen this but in my tests could only reproduce it with Eye of Gnome. The other client side decorated apps I tried seemed ok.

**Comment by ManIVIctorious** [comment]
At least had the issue with gnome-photos and totem (gnome-videos) too

**Comment by sdgathman** [comment]
x2goclient also does not fullscreen correctly under cinnamon.  The screen is covered, but mouse clicks go to the invisible cinnamon panel underneath - launching applications and everything.  It was disconcerting to launch x2goclient, click around on the panel displayed for the remote system, wondering why nothing was happening, then give up and close x2goclient only find dozens of local windows launched!

I also reported this on RedHat bugzilla:
https://bugzilla.redhat.com/show_bug.cgi?id=1345901
https://bugzilla.redhat.com/show_bug.cgi?id=1343250
