### ISSUE TITLE
Panels no longer work

### ISSUE THREAD

**Issue by Evil-Wayz** [linuxmint/Cinnamon#5344]
I was instructed by a launchpad person to try Cinnamon with a mainline kernel (4.6) to see if the bluetooth audio issue was kernel specific.  This messed up my system so I reverted.  Everything works again, including bluetooth but now the panel does not respond.  When I open new programs thru the launch they show up, as do notifications. The clock also works.  No notifications appear from non cinnamon programs (my-weather-indicator, lunar indicator etc.) I created another account and this issue is also present, with one weird issue, in the newly created account, the bluetooth icon is present, and i can click on it and it will open.  The bluetooth icon is not present in my primary account.  I am not using mint, but Ubuntu 16.04 stable with Cinnamon 3.0 with the 4.44 kernel.  I have tried running unity and gnome flashback sessions and no errors are present.

**Comment by JosephMcc** [comment]
It worked fine before you started messing with things? I'm not this is really a Cinnamon issue. At worst you could remove and re-install Cinnamon.

**Comment by Evil-Wayz** [comment]
The panel sort of worked. There were no indicators from third party programs.  And bluetooth didnt work.  Now bluetooth works, but third party indicators still don't show up, and the panel is non responsive. No can I create another one anywhere else.  Ive tried purging and reinstalling, issue persists.

**Comment by Vahan86** [comment]
@Evil-Wayz, is this still an issue for you with Cinnamon 3.2?

**Comment by Vahan86** [comment]
@JosephMcc, can we close this issue?
