### ISSUE TITLE
Mirror Panels for Multiple Displays

### ISSUE THREAD

**Issue by eygraber** [linuxmint/cinnamon#5352]
It would be awesome if I could just setup the panel on my main display and have it mirrored to all other displays.

**Comment by Borillion** [comment]
You can right click on the main default panel, Select Panel Settings and add more. 
Some changes to it would be helpful, many desktops are lacking even on other desktops. We can already add our own panels. It would be nice to start off with a clone of what is set on the primary screen and then allow it to be customized. A checkbox at the simplest. Also support on the window list for knowing what screen its on as well as corresponding windows.

Definitely able to code this up here, not sure what branch to code on.

**Comment by JosephMcc** [comment]
The window list already works that way. Just add another instance to your other monitor.

**Comment by leigh123linux** [comment]
Doesn't the the display clone setting already do this?

**Comment by Minipada** [comment]
On linux mint 19, do:

On the main panel:
Right click -> Modify panel -> Copy Applet configuration

On the second one:
Right click -> Modify panel -> Paste Applet configuration

**Comment by ManIVIctorious** [comment]
I think a major limitation at the moment is, that many stock applets do not support multiple instances.
E.g. Sound, network and systray are the ones bugging me the most

**Comment by jlaustill** [comment]
I think this is a very important feature.  Some of us have different monitor setups at home and at work.  I love having the ability to copy a panel and create new ones, but it is very annoying having to do that every time I plug a new monitor in.  I would like the option on any given panel to simply say "show this panel on all monitors."  Plug a new one in, it shows up, unplug it, it is destroyed.  

The mac top bar and dock do this, and it is a really important feature for the future of multi-monitor support.  I would point out that no other DE supports this that I am aware of(or I would switch to it). 

Lastly, I am a developer with decades of experience.  I would be more than willing to do the work for this panel feature if someone would be willing to help me get my dev environment for cinnamon setup.  I've never contributed to Linux Mint, but I would be glad to try :)

**Comment by rphenix** [comment]
Agreed I was surprised this was an issue.  Panel copy doesn't work when majority of the system applets wont work on multiple panels you end up with a second panel that looks nothing like the primary.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.

**Comment by aaronnewcomb** [comment]
> On linux mint 19, do:
> 
> On the main panel:
> Right click -> Modify panel -> Copy Applet configuration
> 
> On the second one:
> Right click -> Modify panel -> Paste Applet configuration

This used to work but not as of 19.3. This functionality was removed for some reason. Bummer!

**Comment by Minipada** [comment]
I found a workaround by switching back to KDE plasma

**Comment by phillies** [comment]
> > On linux mint 19, do:
> > On the main panel:
> > Right click -> Modify panel -> Copy Applet configuration
> > On the second one:
> > Right click -> Modify panel -> Paste Applet configuration
> 
> This used to work but not as of 19.3. This functionality was removed for some reason. Bummer!

Exactly. This honestly makes cinnamon very awkward in multi monitor mode, as I have to move the cursor to the other monitor to switch from one window to the other instead of just moving down to the panel. Please bring this functionality back!!

**Comment by MartinX3** [comment]
I think about the same due to the performance issues

**Comment by ruthan** [comment]
Im missing this feature too.. im using DisplayFusion on windows and need same thing.

**Comment by KUGA2** [comment]
Updated from LM 19.3 and had to add the panel :( Mirror function would be great

**Comment by Walker555** [comment]
I'm using LM 20 and missing the "mirror panel" function.

**Comment by noetic-faizan** [comment]
> Updated from LM 19.3 and had to add the panel :( Mirror function would be great

hi walker555 , would you pls tell me .. how did you do it

**Comment by Walker555** [comment]
@noetic-faizan There isn't any "duplicate panel by one mouse click" solution. Unfortunately you must manually add new panel on the second monitor and add applets step-by-step :-( 
Tedious, but works.

**Comment by twieskot** [comment]
For me, this is a decider issue - if you have to switch your displays regularly between multiple real-life workplaces,
a option like "Show this panel on all displays" is a must have feature!

Copying the panels manually isn't an option at all, its fiddly and if you want to change something, you have to do it for every new display. Furthermore: some one-panel-only  applets are missing completely (sound, network, etc.) 

Thanks for all your great work so far...

**Comment by rajmondburgaj** [comment]
I think this is a basic feature to allow users to show one panel in all displays or not. Since this ticket is closed I think this will never happen which is unfortunate :(

**Comment by ruthan** [comment]
If someone wonder why Linux on desktop still sucks, this is exactly things like this..

**Comment by spikespaz** [comment]
I really don't want to switch to KDE because it is so very bloated. Please, can we have this basic feature present in Windows and mac?

**Comment by firewiremb** [comment]
Today I put my second screen into operation and looked for the setting to mirror the taskbar for ages. The inability to mirror the taskbar is really annoying.
With Window 10 this works with a single setting option.

**Comment by ruthan** [comment]
Just for info it is this working with Mate, Kde or other Linux environments?

**Comment by LordEvron** [comment]
i am also really interested to this feature.  it should show the same main panel over all the displays..

**Comment by ruthan** [comment]
If developers would be afraid of real users opinions, make some user request poll, this would be one of top priority.

**Comment by automationsClub** [comment]
We are almost 6 years since this issue was requested, 2.5 years since it was closed, but still - No feature.

I love LM but this is such a basic feature. Please let us know when it is due.

**Comment by ruthan** [comment]
Well i call this Linux desktop "quality" level.. and i mean this as not hate is simply pointing out reality.

**Comment by Hronom** [comment]
True, need same, sad to see it closed

**Comment by linuxrichard** [comment]
Resubmitted as https://github.com/linuxmint/cinnamon/issues/11577

**Comment by sylvainfaivre** [comment]
@icarter09 I read the doc regarding feature requests, I understand that this issue is not the place to keep track of feature requests, but the doc fails to answer the question : how and where can users track discussion about feature requests ?
This issue has been closed for 3.5 years and it seems like it was buried...
If we knew the state of the feature request, we might be able to comment on it, or suggest some alternative options. For example, if mirroring panels is not accepted for future development, I would like to ask for another feature : allowing all applets to have several instances. I'm OK with setting up one panel on each sreen if the panel cannot be mirrored, but I'd like to be able to show the same content on each panel.

**Comment by suspiciousRaccoon** [comment]
Why was the functionality for copy pasting panel configurations removed? It fixed this issue.

**Comment by ruthan** [comment]
Because of Linux "quality".. i gave up on this.. linux is nice servers for scripting, but as desktop waste of time for me.. maybe SteamOS, which is glorified game launcher..

**Comment by omergoktas** [comment]
Please reopen this issue, this is bugging many users.

**Comment by PacketFiend** [comment]
> Please reopen this issue, this is bugging many users.

Agreed. While I understand the principle behind closing the issue after it's been processed, this leaves us users completely in the dark as to whether or not this will ever be implemented. It's opaque, and user hostile.

> The process is much simpler now and much more efficient. When you submit an idea, it is processed and then closed. It might lead to an implementation, it might lead to a design discussion within the team, it might be planned for a particular release and put on the roadmap, it might lead to nothing at all, or it might stick in people’s minds as something they could improve later on. Either way, your role is done when the idea is reported and once it’s understood by the development team.

In other words, Cinnamon developers are intentionally leaving users in the dark about not only this feature request, but _all_ of them.

Back to the issue at hand, what is the status of this feature request? It's pretty basic functionality...

**Comment by SillyHats** [comment]
I would also like to see this feature implemented

**Comment by vosscodes** [comment]
it's 2024 and somehow this is less possible than it used to be

**Comment by Jer-C** [comment]
The inability to have certain applets (i.e. the default Linux Mint Sound applet) on multiple panels is a major pain point. I don't know if I'll switch desktop environments or if I'll switch back to Windows or if I'll just stick it out on Cinnamon, but could we at least get an update on whether this is still in development or if it was declined?

**Comment by KhalilSecurity** [comment]
ZorinOs has this feature out of the box. I really hope LM would allow us to clone taskbar across monitors in once click. I try not to download any extra applets because they crashed my system before. Now even with manual applets added, the two monitors look very different and icons won't allow moving to the far left on second monitor. Cinnamon overall seems to be the least reliable portion of the DE.
![2ND](https://github.com/linuxmint/cinnamon/assets/51271290/b972d3a9-7ae1-452f-b6b6-048f0ec932a2)
![MAIN](https://github.com/linuxmint/cinnamon/assets/51271290/01d2da9b-5a0d-489f-9ccf-f7c3bcee825c)

**Comment by Jer-C** [comment]
Thanks, I'll consider it.

**Comment by KhalilSecurity** [comment]
> Thanks, I'll consider it.

@Jer-C I didn't mean that as a replacement to Mint. LM is way more stable. I actually found the easiest fix to duplicate taskbar on LM. 

1. Switch to KDE desktop environment
```
sudo apt install kde-plasma-desktop
```
2. During installation I choose the new lock screen "SDDM", instead of cinnamon lock screen.
3. After restart I changed session in lock screen to "plasma". 
4. On second monitor > right click > add new panel > default panel.

![main kde](https://github.com/linuxmint/cinnamon/assets/51271290/04cc1a86-7da1-4cdc-81b8-bbc480b88994)

![2nd kde](https://github.com/linuxmint/cinnamon/assets/51271290/e0e201f1-a658-42c4-a8c3-a9ea509c4cd2)

**Comment by KhalilSecurity** [comment]
> Here is how I mirrored panels and the applets:
> 
> Get active cinnamon configuration. `dconf dump /org/cinnamon/ > panels.txt`
> 
> Open up txt file with your text editor. `code panels.txt`
> 
> Look for the panels-enabled first and add the new panel/s here: panels-enabled=['1:2:bottom', '2:0:bottom', '3:1:bottom']
> 
> In `enabled-applets` array repeat the applets for each panel, it should look like
> 
> `enabled-applets=['panel1:left:0:Cinnamenu@json:51', 'panel1:left:6:pomodoro@gregfreeman.org:99', 'panel2:left:0:Cinnamenu@json:51', 'panel2:left:6:pomodoro@gregfreeman.org:99', 'panel3:left:0:Cinnamenu@json:51', 'panel3:left:6:pomodoro@gregfreeman.org:99', 'panel4:left:0:Cinnamenu@json:51', 'panel4:left:6:pomodoro@gregfreeman.org:99']`
> 
> Save the panels.txt
> 
> Load the file:
> 
> ```
> dconf load /org/cinnamon/ < panels.txt
> ```
> 
> Replace conf:
> 
> ```
> cinnamon --replace &
> ```

Nice try, but it doesn't work, not to mention the complexity for end user
![cinnamon](https://github.com/user-attachments/assets/5cd4613e-04cc-4177-985a-a5cfa3b268e7)

**Comment by MadCatMKII** [comment]
> Here is how I mirrored panels and the applets:
> 
> Get active cinnamon configuration. `dconf dump /org/cinnamon/ > panels.txt`
> 
> Open up txt file with your text editor. `code panels.txt`
> 
> Look for the panels-enabled first and add the new panel/s here: panels-enabled=['1:2:bottom', '2:0:bottom', '3:1:bottom']
> 
> In `enabled-applets` array repeat the applets for each panel, it should look like
> 
> `enabled-applets=['panel1:left:0:Cinnamenu@json:51', 'panel1:left:6:pomodoro@gregfreeman.org:99', 'panel2:left:0:Cinnamenu@json:51', 'panel2:left:6:pomodoro@gregfreeman.org:99', 'panel3:left:0:Cinnamenu@json:51', 'panel3:left:6:pomodoro@gregfreeman.org:99', 'panel4:left:0:Cinnamenu@json:51', 'panel4:left:6:pomodoro@gregfreeman.org:99']`
> 
> Save the panels.txt
> 
> Load the file:
> 
> ```
> dconf load /org/cinnamon/ < panels.txt
> ```
> 
> Replace conf:
> 
> ```
> cinnamon --replace &
> ```

This worked pretty well. Only problem is you can't activate the edit mode of the taskbars without a mess happen. Not sure why they haven't implemented something similar yet.

**Comment by ruthan** [comment]
This Linux "quality" world.. Dont be hasty maybe they will make it before we die.. and even so, it would be probably work for short moment and after it would be one of zillions Linux regressions bugs.

**Comment by cerels** [comment]
Would really like this feature, zorin have it already

**Comment by ruthan** [comment]
Well, i thing that you have to contact some boss of bosses of Cinnamon.. From my experience there of them some analyst or testers, or simply moderators in first row, which are reviewing and forwarding issues.

   Also often developers go after easiest issues to implement (it make sense except some really important features like this) and close some complicated and hope that anybody will note. 
  I these day when you are really working with computers you have multiple monitors a need some desktop environment to support it (with panel synch, forcing app to specific monitor, icon position saving etc), actually not support of extended desktop and 2nd, 3rd monitor is now most annoying thing on Android for example. 
   I as wrote above some companies even build 15+ years old business on it, im using Display fusion for very long time.

**Comment by KonstantinKuklin** [comment]
bump 👀

**Comment by Believe82** [comment]
Adding my vote for this request.

**Comment by ruthan** [comment]
Well some feature voting, something like has Gog for games and Galaxy client features and eshop would be nice, but i never saw it in Linux world..
   It would be nice to see most requested features vs some forecast how much work it would be and transparent process of decision what to do next based on summary of both of these values.

**Comment by Bober65031** [comment]
bump

**Comment by Dzubrul** [comment]
Bump

**Comment by gmaxferr** [comment]
bump

**Comment by Bober65031** [comment]
bump

**Comment by Glundyn** [comment]
Adding my vote. Would love to see multiple instances of the same panel without mirroring entire screens

**Comment by Ash-Crow** [comment]
Same, especially as the system seems to lose memory of what was configured for a monitor after it is unplugged.

**Comment by fathoni** [comment]
Would also be happy to see this feature implemented :)
