### ISSUE TITLE
Text and buttons cutoff from shutdown/restart/logoff box

### ISSUE THREAD

**Issue by iamnotzerocool** [linuxmint/Cinnamon#5353]
Ubuntu 16.04 with Cinnamon 3.0.3 installed.  After clicking on the power icon I'm presented with a box that should ask me what I want to do.  But the text and buttons are cutoff and this box is not re-sizable.

**Comment by JosephMcc** [comment]
I've never seen anything like that on ubuntu 16,04 or Mint. Does changing the gtk theme make any difference? What theme are you using?

**Comment by JosephMcc** [comment]
Closing due to lack of response.
