### ISSUE TITLE
Auto updates for widgets (applet, desklet extensions)

### ISSUE THREAD

**Issue by muzena** [linuxmint/Cinnamon#5356]
@collinss
I think, it will be usefule if it possible that widgets have auto update, or at least notification to notify user for available widget updates or maybe this all update integrated through update manager.
I have installed a few additional desklet and extension and usually I notice that they have update after 2-4 weeks after new widget release.

**Comment by lestcape** [comment]
Yes will be useful create a cron job to call a python script, to check periodically for any update, also update the description of all new applets and desklets... Then show a message to the user if he want to install the updates. Some thing like that is what i try to do here, but is a little slow and incompatible with the last version of cinnamon:

https://github.com/lestcape/Spices-Menu

Also i try to add a way to control the extensions settings inside cjs, also is not finished.

**Comment by anandrkris** [comment]
https://github.com/linuxmint/Cinnamon/issues/3099 One possible way is to have another appet that shows available updates...

**Comment by lestcape** [comment]
@anandrkris not only an applet, because you will overhead the only thread that cinnamon have with that. So, probably as i say a python script. The applet in all case will be optional and only to show results...

**Comment by anandrkris** [comment]
@letscape Hmm. Not a technical user here. Just thought since x-lets are Cinnamon specific, can't go to Update manager so suggested another applet to present complete update information.

**Comment by lestcape** [comment]
@anandrkris yes, what i say is only technical... The applet can exist, without a problem.

**Comment by JosephMcc** [comment]
https://github.com/linuxmint/Cinnamon/issues/6706
