### ISSUE TITLE
Focus stealing and Quassel

### ISSUE THREAD

**Issue by niayh** [linuxmint/Cinnamon#5358]
I've seen many issues opened up a few years ago that mention that Quassel pops to the forefront and immediately steals focus upon receiving any notification that marks the task bar entry (https://github.com/linuxmint/Cinnamon/issues/2087)

It seems the problem has returned for Quassel in recent version of Cinnamon (later version of 2.0 and currently on 3.0). (https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=816241)

I found a note that mentioned adding the following (global.log_error("Focus stolen by : " + window.get_wm_class());) to the file /usr/share/cinnamon/js/ui/windowAttentionHandler.js would allow me to grab the specific name of the object that stole attention. I set off to do this, thinking perhaps the name had been altered for Quassel; however, once I enabled logging and restarted Cinnamon, Quassel no longer steals focus!

This is a definitely a good work around, but will get re-written after each upgrade of cinnamon -- would like to see a proper fix implemented into the source as this focus stealing behavior can be incredibly frustrating and doesn't happen on other desktop environments.

Currently using manjaro 16.06, but have had the problem on debian, ubuntu and arch variants.

**Comment by leigh123linux** [comment]
I have the same issue with kvirc

**Comment by niayh** [comment]
This update is now in 3.0.6 and Quassel is still exhibiting the focus stealing behavior even with the referenced commits.

**Comment by mtwebster** [comment]
Did you at least restart Cinnamon or login/out?  I definitely can't reproduce this any longer.

**Comment by niayh** [comment]
Ugh, you're probably correct. I think I did forget to restart after the update, but I did restart cinnamon after applying the logging line and that probably kicked it in.
