### ISSUE TITLE
Misleading error message for unavailable network locations

### ISSUE THREAD

**Issue by CottonEaster** [linuxmint/Cinnamon#5360]
The screenshot shows what happens when I attempt to access a share (set up via autofs, if that makes a difference) on a computer this powered off.

![screenshot-area-2016-06-07-030142](https://cloud.githubusercontent.com/assets/9998846/15843719/4feaa870-2c5c-11e6-954f-6c70e2c6da26.png)

How about amending  the message to suggest (something like) that a remote location may be unavailable? This is in fact an explanation that will be true on more occasions, I think, than the one offered at present/in the screenshot.

It seems to me that this is one of those matters where - at least in concert with similar improvements - a small change could make a somewhat substantial improvement.

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
