### ISSUE TITLE
Can't adjust volume when screen locked

### ISSUE THREAD

**Issue by ACinnamonUserInUK** [linuxmint/Cinnamon#5364]
Imagine you've played a video, and then stopped playing it by closing your laptop's lid (and perhaps you've stopped the video to, using its controls - but YouTube or what-have-you is on autoplay setting . .). Imagine further that you open up the laptop later. Audio from the video then comes blaring out - and pressing the laptop's mute button, or volume down button, makes no difference - until one logs in.

Cf. https://github.com/linuxmint/Cinnamon/issues/3487

Cinnamon 2.8.8 on Mint 17.3

**Comment by JosephMcc** [comment]
Duplicate https://github.com/linuxmint/Cinnamon/issues/1900
