### ISSUE TITLE
LightTable stays "on top" in VirtualBox

### ISSUE THREAD

**Issue by pwhittin** [linuxmint/cinnamon#5365]
I have installed linuxmint-18-cinnamon-64bit-beta.iso as a VirtualBox Version 5.0.20 r106931 guest running on a Windows 10 host.  When I run LightTable version 0.8.1, from lighttable.com, LightTable seems to stay "on top" all the time.  By "on top" I mean that visually nothing will ever display on top of the LightTable window, whether it is full screen or not (e.g., Pressing Alt-TAB results in part of the usual Alt-TAB display being obscured by the LightTable window.

This always happens when the VirtualBox VM's settings include enabling the "Display->Enable 3D Acceleration", and never happens when it is not enabled.  Note that when "Display->Enable 3D Acceleration" is not enabled the VM runs in "slow" software rendering mode.  This issue also happens with LinuxMint 17.3 Cinnamon 64-bit in the same environment with the same settings.  Note that this issue does **NOT** happen with LinuxMint 17.3 MATE 64-bit.

**Comment by icarter09** [comment]
@pwhittin are you still experiencing this issue? If so, what version of Mint and Cinnamon are you running?

**Comment by pwhittin** [comment]
I no longer have the ability to set up and test this configuration.  I don't know if the issue persists.

**Comment by icarter09** [comment]
@pwhittin no worries and thanks for the update.
