### ISSUE TITLE
[Ubuntu Feature Request] new keyboard layout (Russian for Germans, Transliteration) for ubuntu

### ISSUE THREAD

**Issue by NikoKrause** [linuxmint/Cinnamon#5366]
Hey guys,

I know this doesn't really belong here. Maybe someone can help me to find the right place for my request.

I know a lot of people, who are used to a certain russian keyboard layout, i.e. this one here:
![keytra](https://cloud.githubusercontent.com/assets/8415124/15911708/3d12737e-2dd1-11e6-9abd-9939134b6ec7.gif)

Can anyone help me, creating this one? I also could look into it by myself.
There are some tutorials out there.

But when I am finished with it, I would like this keyboard layout to be in the default keyboard layout set in Linux Mint/Ubuntu.

But I don't know, where is the right place to contribute or suggest this to.

In Linux Mint it is easy. I could create a pull request here on github. But I think, this is a problem with ubuntu. And I haven't found them on github o.O

Can anyone help me?

Regards

Niko

**Comment by JosephMcc** [comment]
Ubuntu uses Launchpad instead of github. I'm going to close this since it's unrelated to Cinnamon. Anyone getting github notifications will still see it and maybe someone will have an answer for you.

**Comment by mtwebster** [comment]
Are you wanting to create this new custom layout?  There are a lot of tutorials for doing this - search for adding xkb layout in ubuntu or linux.  As for including it in Mint or Ubuntu, you could package it and make a PPA for it for others to use, or try to get it added to the default list.

**Comment by NikoKrause** [comment]
@JosephMcc 
Okay, I thought so. Thanks for your quick reply.

@mtwebster 
Do you know, how to try to get it added to the default list?

**Comment by mtwebster** [comment]
Looks like you have to submit it to this project: https://www.freedesktop.org/wiki/Software/XKeyboardConfig/

I really am not sure though - it looks like a good place to start.

**Comment by NikoKrause** [comment]
Thanks for your help. The layout is finished. Now I have to try, to submit it to the project.
