### ISSUE TITLE
Some theme inconsistencies with gnome applications in Linux Mint 18

### ISSUE THREAD

**Issue by surenenfiajyan** [linuxmint/Cinnamon#5367]
I discovered that gnome calculator window border didn't change its theme when I changed the border theme to ark.

![screenshot from 2016-06-09 20-02-48](https://cloud.githubusercontent.com/assets/13224708/15936985/2d63f68e-2e7e-11e6-9ca8-a1323394b457.png)

I think such gnome apps must be replaced with x-apps, for example replacing gnome-calculator with something like xcalculator.

**Comment by f2404** [comment]
Could it be that one of the apps (is it xfce4-terminal?) is using GTK2 theme while another (the calculator) - GTK3 theme?

**Comment by surenenfiajyan** [comment]
@f2404 No, it's gnome-terminal. Is gnome-terminal using GTK 2?

**Comment by f2404** [comment]
No, it has switched to GTK3 quite some time ago... You can verify it by using your package manager and looking into terminal's dependencies but it doesn't look like this is the case.

**Comment by f2404** [comment]
Actually, I've just installed gnome-calculator, and it's indeed looking differently from other apps - either based on GTK or Qt.

**Comment by surenenfiajyan** [comment]
@f2404 I also didn't like the new system monitor look. That's why Mint team is migrating to x-apps.

**Comment by JosephMcc** [comment]
Normal server side decorated apps make uses of the Metacity theme for window borders and client side decorated apps like gnome calculator use the gtk theme. This is what you're going to get when you mix and match different ones.

Regardless, this is for Cinnamon issues, which this isn't one.
