### ISSUE TITLE
Request to add 'shortcut to file or folder' and 'shortcut to url' in desktop right click context menu

### ISSUE THREAD

**Issue by sikejsudjek** [linuxmint/Cinnamon#5368]
One thing that confused me as a windows user switching to Cinnamon on linux mint was the lack of a right click context menu entry to create shortcuts on the desktop. Xfce seems to have this - it would be much more user friendly to have this in Cinnamon too.

**Comment by JosephMcc** [comment]
It has "Create launcher here". That doesn't provide the functionality you want?

**Comment by sikejsudjek** [comment]
Thanks for replying JosephMcc. I don't think the present method on Cinnamon is as intuitive as perhaps it could be  (to ex windows users at least !) as to how the 'create launcher' works. XFCE by contrast has explicit context menu entries to create the links similar to windows os functionality. 
This is about the only thing that (temporarily) confused me when starting to use cinnamon on mint. Pretty much everything else is very easy to figure out.  I have actually worked in IT for 8 years and been programming for a while - so if it confused me I suspect it might confuse other users who move over to linux !

**Comment by f2404** [comment]
@sikejsudjek What kind of a desktop link would you like to have?
You know you can use `ls -l` to create a symbolic link, right?

**Comment by JosephMcc** [comment]
Could you move this feature request to the nemo repo? It's nemo that actually controls this.
