### ISSUE TITLE
cinnamon freezes on ubuntu 16.04 with two monitors on boot

### ISSUE THREAD

**Issue by lionghostshop** [linuxmint/Cinnamon#5370]
cinnamon --version
Cinnamon 3.0.5
I am using Thinkpad 440p. 
 Intel Corporation 4 Gen Core Processor Integrated Graphics Controller
 NVIDIA Corporation GK208 [GeForce GT 730]
on ubuntu 16.04

If it connect two monitors when cold booting, it always freezes.
if It uses default one laptop monitor, it works. After booting to desktop, then connect to another monitor, it works.

**Comment by JosephMcc** [comment]
Have you tried other graphics drivers? I spent quite a bit of time on xenial during development for Cinnamon3 and I always use dual monitors. Never ran into this issue. I run an older gtk260 with the open source driver.

**Comment by lionghostshop** [comment]
I found that 361.42 has the issue. 
I change to 340.96, it works.

**Comment by lionghostshop** [comment]
May I ask what driver do you use if you use nvidia driver?

**Comment by JosephMcc** [comment]
I don't remember now. I tried all the ones available in ubuntus driver manager tool. On my specific card I get really poor performance in simple things like dragging windows around the screen on all of them. I would also sometime get hard crashes. Not just Cinnamon but crashed to a tty or black screen full of output no regular person can comprehend ;) I have none of those issues with the open source driver. I don't play games or anything though so the nvidia driver isn't providing me with any real benefit.

If you've sorted your issue would mind closing this?
