### ISSUE TITLE
Mouse acceleration cannot be disabled

### ISSUE THREAD

**Issue by Frogging101** [linuxmint/Cinnamon#5372]
If one moves the mouse acceleration slider in Cinnamon Settings<sup>1</sup>, mouse acceleration will be enabled irreversibly, with no obvious way of turning it off again. One has to go into dconf and set `org.cinnamon.settings-daemon.peripherals.mouse.motion-acceleration` to -1.

The mouse acceleration slider control (which is linked to the aforementioned dconf value) has a range of 1.0 to 10.0. The value must be set to -1 in order to disable mouse acceleration, and the slider does not allow this. I can think of two ways to fix this:
- Add a checkbox to enable acceleration and display the slider
- Make the lowest value on the slider correspond to -1, and indicate to the user that this means it's turned off

It's probably a trivial enough change. I can make a PR if somebody wants to tell me how it should be done.

<sup>1</sup> as of 2.8.8, however I looked at the master branch code and it doesn't look fixed

**Comment by JosephMcc** [comment]
It isn't fixed. I just brought this up in IRC yesterday when looking at another issue with this same slider that some one reported on the Mint18 beta.

**Comment by JosephMcc** [comment]
Fixing this has been added to the roadmap for 3.2. I just want to do it in a way that fits in design wise with our other settings.

**Comment by Cobinja** [comment]
We could just set the range for the slider from 0 to 10, with steps of 0.1. Cinnamon settings daemon uses steps of 0.25, if the value is > 1, and does it steps of 0.1 if the value is > 0 and <= 1. If the value is 0, it handles it as "acceleration deactivated".

**Comment by JosephMcc** [comment]
You would have to map 0 to a value of -1 in that case. It still doesn't allow you to get back to the default -1 value. -1 and 0 are not treated the same as you can see if you set the gsettings key to 0 in dconf-editor or from the terminal.

**Comment by Cobinja** [comment]
Not really. Acc. to https://github.com/linuxmint/cinnamon-settings-daemon/blob/master/plugins/mouse/csd-mouse-manager.c#L436 the acceleration is disabled, no matter if you set it -1 or 0. The GSettings key is not used anywhere else in Cinnamon related code, except for being set from Cinnamon Settings.

**Comment by Swiftpaw** [comment]
Hi all,

Glad to hear this is on the roadmap for Cinnamon 3.2.  [This thread on Linux gaming](https://www.reddit.com/r/linux_gaming/comments/4ym6kj/how_to_completely_disable_mouse_acceleration_in/?st=is3ctfj4&sh=90228e51) brought it up again as a highly requested feature.  I see posts about disabling mouse acceleration all the time.

Thanks for helping to make gaming on Linux better! :wolf:

**Comment by JosephMcc** [comment]
This is fixed now in git master.
