### ISSUE TITLE
Make an option to disable Muffin's composition

### ISSUE THREAD

**Issue by Ufeldraku** [linuxmint/Cinnamon#5373]
Why, you may ask? Because I currently use Mate 1.12[Arch won't update to 1.14], and I use Marco as a Window Manager, and Compton as my Composite manager, Compton offers a great tearfree experience, plus it has good effects too!

And well, Compton is faster for me than Muffin.....

Thanks!

**Comment by leigh123linux** [comment]
-1 

I recommend that you continue to use Mate and leave Cinnamon alone as muffin isn't something you can disable!
