### ISSUE TITLE
menu-applet: Highlighting categories of newly installed applications

### ISSUE THREAD

**Issue by NikoKrause** [linuxmint/Cinnamon#5374]
After an application is installed, the application is highlighted/bold in the menu.
It would be great if the category of the application would also be highlighted. 
Sometimes the user doesn't know, in which category he has to search for the newly installed application. 
This would make it easier to find the application.

**Comment by anandrkris** [comment]
Was exactly having same doubt after installing FBreader that reads epub files :)

**Comment by Vahan86** [comment]
Good idea. +1

**Comment by anandrkris** [comment]
Also, category highlight needed on Search results.
https://github.com/linuxmint/Cinnamon/issues/4420

**Comment by NikoKrause** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
