### ISSUE TITLE
Applet listing will come up not showing all columns when applet description is large

### ISSUE THREAD

**Issue by brownsr** [linuxmint/Cinnamon#5375]
![screenshot from 2016-06-14 21-10-15](https://cloud.githubusercontent.com/assets/6322481/16058411/3bc6dc36-3276-11e6-90ba-0f0965f3265c.png)

The column placement appears to be controlled by the length of the longest description.  This means that when the applet screen first appears after an install it will appear to be missing the installed/locked columns for the unwary user, if the applet list contains an applet with a long description, - and the inhibit applet that is installed by default has a very long description.

I have had to drag the right margin of the applet list well to the right from the default size after installation to generate the image as shown.  As it launched for me after installation the columns to the right were invisible.

To avoid this the description should be given a sensible display length and wrapped

**Comment by NikoKrause** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.

**Comment by NikoKrause** [comment]
Just kidding. This has changed in Cinnamon 3.6
