### ISSUE TITLE
no notification, when removing usb stick with right click on desktop symbol

### ISSUE THREAD

**Issue by NikoKrause** [linuxmint/cinnamon#5377]
Hey,

when I remove an USB-Stick from nemos sidebar, I get a notification in the top right corner of my screen: "You can remove USB-Stick now"
When I remove an USB-Stick with right click on the desktop symbol, the notification doesn't show up.

I like the notification, so it would be great, if it would also show up with the second option.

**Comment by NikoKrause** [comment]
Maybe this belongs to nemo? I'm not sure though.

**Comment by Vahan86** [comment]
Still an issue in Cinnamon 4.2

**Comment by Vahan86** [comment]
The notification doesn't show up also when removing usb stick using Removable drives applet.

**Comment by claudiux** [comment]
@Vahan86 Did you try this version of `/usr/share/cinnamon/js/ui/placesManager.js`? https://github.com/linuxmint/cinnamon/blob/4e94b9faba57cdcba0aab81a73fef37df8e51460/js/ui/placesManager.js

**Comment by Vahan86** [comment]
@claudiux, I have tested the version of /usr/share/cinnamon/js/ui/placesManager.js provided by you and the issue with the applet seems to be fixed. Thanks.
