### ISSUE TITLE
[abrt] cinnamon: meta_workspace_index(): cinnamon killed by SIGSEGV

### ISSUE THREAD

**Issue by rbieb** [linuxmint/cinnamon#5380]
I have an issue with cinnamon where it's just segfaulting randomly (happens multiple times a day). I'm running fedora and the issue happens both in fedora 23 and 24 with cinnamon versions cinnamon-2.8.6-1.fc23 and cinnamon-3.0.4-1.fc24.

There are complete bug reports over here:
Fedora 23: https://bugzilla.redhat.com/show_bug.cgi?id=1299145
Fedora 24: https://bugzilla.redhat.com/show_bug.cgi?id=1346923

I'd really appreciate some help on this because this issue has been driving me mad for months now.

**Comment by icarter09** [comment]
@rbieb are you still experiencing this issue? If so, what version of Mint and Cinnamon are you running?
