### ISSUE TITLE
Desktop background resets to default when plugging USB device

### ISSUE THREAD

**Issue by andreaiacoponi** [linuxmint/Cinnamon#5383]
System: Ubuntu 16.04
Cinnamon version: 3.0.5-1~xenial0

When I start the system with USB device already plugged, desktop background is set with an image I selected.

Once I plug in an USB device, desktop background reset to the default image and is no more possible to change it to the chosen image. Restarting the system, background displays again the correct image.

**Comment by ntfs1984** [comment]
BUG replicated with web-camera.
BTW, it doesn't related to Cinnamon. It related to segfault of upower library with any DE. Theme is resetting to default in 10-20 sec after login, but will return to normal, once we logout to lightdm, and re-enter to Cinnamon.

**Comment by JosephMcc** [comment]
https://github.com/linuxmint/Cinnamon/issues/3953
