### ISSUE TITLE
Remove window decorations (humble request)

### ISSUE THREAD

**Issue by alxgvr** [linuxmint/Cinnamon#5384]
Hi.

I like to move pannel to the top, put global menu applet and window buttons applet to the left corner. So I have Unity-like desktop. 
Only thing is missing - ability to remove maximized window decorations. 
In Mint 17.2 I used Maximus for that. Maximus is not working in 17.3.
In MATE and XFCE we have an option in system settings "undecorate maximized windows".

I would like to ask for that feature in Mint 18. 

P.S. Also, would be great if developers will include Global-AppMenu applet (https://github.com/lestcape/Global-AppMenu) to Cinnamon default (preinstalled) applet list.

**Comment by lestcape** [comment]
https://github.com/linuxmint/muffin/issues/183
