### ISSUE TITLE
[critical] Cannot securely lock screen on scaled display

### ISSUE THREAD

**Issue by Redsandro** [linuxmint/Cinnamon#5385]
Linux Mint Cinnamon 18 BETA release but fully updated

When locking the screen - but having a display scaled above it's default resolution - the lock modal does not cover the whole screen. The underlying windows can be interacted with.

Some functionality is locked out. For example, you cannot use keyboard or right-click. But you can use the mouse with the left button. You can move around files and directories in Nemo, move to trash, scroll around. When a terminal is open doing an important job, you can close the terminal tab. Etc.

This used to work properly in Linux Mint 17.

![20160617_131829](https://cloud.githubusercontent.com/assets/1702193/16149337/671381ac-3490-11e6-9147-aca37f146e96.jpg)

![20160617_131837](https://cloud.githubusercontent.com/assets/1702193/16149377/a2fbd8cc-3490-11e6-9e5f-03ce46df2af2.jpg)

The main monitor has two "lockscreens" because of a :bug: bug where Cinnamon/Gnome doesn't support monitors that use Displayport-MST to achieve higher framerates for UHD/4k content: https://github.com/linuxmint/cinnamon-control-center/issues/142

The second monitor scaling is necessary because Cinnamon :bug: does not support having both a HiDPI and normal DPI display at the same time like macOS and Windows transparently do. Everything on the normal display will be unusably huge. A workaround is scaling to the maximum factor the monitor will allow.

In this case, the `1280x1024` monitor is displaying a `1965x1572` viewport.

Scaling is possible with `xrandr`, or with `xorg.conf`:

```

Section "Screen"
    Identifier     "Screen0"
    Device         "Device0"
    Monitor        "Monitor0"

    Option         "TwinView"
    Option         "TwinViewXineramaInfoOverride" "3840x2160+0+0"
    Option         "Stereo" "0"
    Option         "nvidiaXineramaInfoOrder" "DP-0.9, DP-0.8, DVI-I-0"
    Option         "metamodes" "DP-0.8: 1920x2160 +1920+0, DP-0.9: 1920x2160 +0+0, DVI-I-0: 1280x1024 +3840+0 {viewportin=1965x1572}"
EndSection
```

Note the `DVI-I-0: 1280x1024 +3840+0 {viewportin=1965x1572}`

I think the lockscreen blocks over the 1280x1024 display size of the screen, while it should be over the viewport size which is 1965x1572, as it did in Mint 17.3.

**Comment by mtwebster** [comment]
So, just messing around with my nvidia settings, I created a panned screen - I'm not sure if it's the same situation you have (I'm not real familiar with these sorts of configurations), but I have come up with a fix that may solve the problem regardless.

Could you try this patch: http://dpaste.com/0MCXG5T and build cinnamon-screensaver?  Or, if you'd like, I don't mind building a test package to try out, just tell me what arch you're on - 32 or 64 bit?

**Comment by mtwebster** [comment]
Hmm now I cannot reproduce this - the only difference being I switched out video cards (I had been testing an older one).

What graphics card and driver are you using?

**Comment by Redsandro** [comment]
@mtwebster if you can provide a .deb package for 64 bit that would be great.
I'm using the nVidia proprietary driver using TwinView for the HiDPI monitor, hardware being a VGA Gigabyte GeForce GTX970 ITX. Don't think TwinView is the problem though, it's the scaled view on the second monitor.

**Comment by Redsandro** [comment]
Currently on laptop with Intel video, I cannot reproduce the problem on this hardware, but perhaps I need an external monitor for that. I will write down the commands I used so I can retry at a later point when I have access to an external display.

```
$ xrandr --current
Screen 0: minimum 8 x 8, current 1600 x 900, maximum 32767 x 32767
LVDS1 connected primary 1600x900+0+0 (normal left inverted right x axis y axis) 309mm x 174mm

$ xrandr --output LVDS1 --scale 1.2x1.2
$ xrandr --current
Screen 0: minimum 8 x 8, current 1920 x 1080, maximum 32767 x 32767
LVDS1 connected primary 1920x1080+0+0 (normal left inverted right x axis y axis) 309mm x 174mm
```

I do experience a different problem though - the lock screen goes fullscreen (which is good) but the mouse cursor is now restricted in an invisible box as defined by the old resolution.

**Comment by Redsandro** [comment]
The problem is that the Cinnamon Display Settings does not support scaling but `x` and `xrandr` do:

![image](https://cloud.githubusercontent.com/assets/1702193/18310613/b8060116-74ff-11e6-970a-b27f60595af5.png)

```terminal
$ xrandr
Screen 0: minimum 8 x 8, current 5805 x 2160, maximum 16384 x 16384
DVI-I-0 connected 1965x1572+3840+0 (normal left inverted right x axis y axis) 338mm x 270mm
   1280x1024     60.02*+  75.02  
   1024x768      75.03    70.07    60.00  
DP-0.8 connected 1920x2160+1920+0 (normal left inverted right x axis y axis) 527mm x 296mm
   1920x2160     59.99*+
DP-0.9 connected primary 1920x2160+0+0 (normal left inverted right x axis y axis) 527mm x 296mm
   1920x2160     59.99*+
```

`DVI-I-0` has a `1965x1572` viewport projected on a `1280x1024` panel.
Nvidia knows this. Xranrx knows this. X server knows this.
__Cinnamon does not.__ And Cinnamon is responsible for cutting/stitching wallpapers (as seen in https://github.com/linuxmint/Cinnamon/issues/5654) and lockscreens.

**Comment by mtwebster** [comment]
https://github.com/linuxmint/cinnamon-screensaver/commit/c3715694aba68423bcde67b96b10462b41469939
