### ISSUE TITLE
Feature Request: Windows management improvements: move groups of windows together, resize tiles

### ISSUE THREAD

**Issue by s7jones** [linuxmint/Cinnamon#5388]
I use third party window management software in my Windows boot, and I think it has some features that Cinnamon would benefit from. To my knowledge Cinnamon is unable to do either of the following:

The following gifs and descriptions (from [here](http://www.nurgo-software.com/products/aquasnap)) are a good example of the effects:
- **Adjustable window tiling**
> http://www.nurgo-software.com/images/AquaSnap/GroupSize.gif
> Window tiling
> Sometimes, splitting your desktop into halves or quarters is not ideal
> 
> When two windows are side-by-side, resizing one of them while pressing [Ctrl] will also resize the other one. It's an easy and powerful way to modify the layout of several tiled windows.

- **Ability to drag a group of windows that share an edge**
> http://www.nurgo-software.com/images/AquaSnap/GroupMove.gif
> Move windows together
> Easily manage these small floating windows
> 
> Professional applications with complex UI often scatter small toolbox windows on your desktop. Keep them grouped and move them all at once. Move one window while pressing [Ctrl] and the whole group of adjacent windows will follow.

Thanks.

**Comment by JosephMcc** [comment]
There is a very similar request here: https://github.com/linuxmint/Cinnamon/issues/4920

Could you please just add to that request so we can avoid having too many open issues dealing with the same thing.
