### ISSUE TITLE
Desktop does not lock with some Taskbar interactions.

### ISSUE THREAD

**Issue by LoadingEllipsis** [linuxmint/Cinnamon#5389]
17.3 Cinnamon 64-bit

Having the calendar open or leaving the properties open by right clicking the taskbar will prevent the computer from locking.

Keeping, "Menu" open will temporarily prevent a lock, but then one will happen after a few seconds of opening a laptop.

This was consistently reproducible.

//Thanks for the great OS!  Keep up the good work!

My first report.  I searched but couldn't find it.  Sorry if it was known or intended.

**Comment by JosephMcc** [comment]
Thanks for making the effort to search first. You can find the issue here: https://github.com/linuxmint/cinnamon-screensaver/issues/93
