### ISSUE TITLE
Menu applet closes-opens after moving panel [BUG]

### ISSUE THREAD

**Issue by germanfr** [linuxmint/Cinnamon#5391]
There is a bug that happens after you move the panel, then when you open the menu it closes and reopens itself while you are moving the cursor through the menu button. I'ts not a theme issue because I've tried it with the default Cinnamon theme. The problem is solved when you restart Cinnamon.

I can reproduce the bug. I'm on Cinnamon 3.0.5.

**Comment by JosephMcc** [comment]
This should be fixed in 3.0.6. When you get the update please test it and close this if it seems good.

**Comment by germanfr** [comment]
OK, waiting for the update. I'll leave a message here once I get it.

**Comment by germanfr** [comment]
Fixed on 3.0.6. I'll close the issue
