### ISSUE TITLE
Applets menus are not navigable when virtualbox is in fullscreen and have the focus.

### ISSUE THREAD

**Issue by DG-Tal** [linuxmint/cinnamon#5393]
Applets menus are not navigable when virtualbox is in full-screen (but work in windowed mode) and have the focus. You cannot select any elements and clicks will be registered to the windows below the menu. The menu will also stay open until the button is clicked again.

Setup required to reproduce:
-2 or more monitors
-Virtualbox in full-screen on one monitor
-Panel with a pop-able menu on the second monitor

As long as the virtual machine have the focus, the menus don't work. [I recorded my desktop to show the bug](http://webmshare.com/mxBeJ), virtualbox is in fullscreen on my main monitor. You can see the menus working once i click the desktop.

Tested on mint 18 with cinnamon 3.0.5 and virtualbox 5.0.18 (with XP and 7)

_If this issue concern more virtualbox then cinnamon I would be happy to redirect this issue to their bug tracker._

**Comment by Jakeroid** [comment]
I have same bug. Then virtualbox running on full screen on  my second monitor I can't click on any elements in applets menus.

**Comment by icarter09** [comment]
@DG-Tal are you still experiencing this issue?

**Comment by Vahan86** [comment]
@icarter09, can we close this issue?
