### ISSUE TITLE
Ability to move groups of windows together

### ISSUE THREAD

**Issue by s7jones** [linuxmint/Cinnamon#5394]
Originally mentioned in #5388.

I use third party window management software in my Windows boot, and I think it has some features that Cinnamon would benefit from.

The following gifs and descriptions (from [here](http://www.nurgo-software.com/products/aquasnap)) are a good example of the effects, but the one I'm mentioning here is the ability to move groups of windows that share an edge.
- **Ability to drag a group of windows that share an edge**
  > http://www.nurgo-software.com/images/AquaSnap/GroupMove.gif
  > Move windows together
  > Easily manage these small floating windows
  > 
  > Professional applications with complex UI often scatter small toolbox windows on your desktop. Keep them grouped and move them all at once. Move one window while pressing [Ctrl] and the whole group of adjacent windows will follow.

Thanks.

**Comment by JosephMcc** [comment]
You added your request to the already open issue I pointed you to. Please don't keep opening new ones.

**Comment by s7jones** [comment]
The request are for two different features, so I split them.

**Comment by JosephMcc** [comment]
Sorry, I didn't read carefully enough.

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
