### ISSUE TITLE
NEMO Can't change folder colour 

### ISSUE THREAD

**Issue by KiszonkaMariana** [linuxmint/Cinnamon#5397]
Linux Mint 18 Beta (Sarah) Cinnamon 64-bit

I changed "Documents" folder color into yellow, but next time, when I clicked right on random folder, I couldn't see nemo folder color switcher as normal user, but only as root.

Rebooting doesn't help.

**Comment by JosephMcc** [comment]
Please open an issue here: https://github.com/linuxmint/nemo
