### ISSUE TITLE
sound-applet: turn Volume to more than 100% without the need to open settings

### ISSUE THREAD

**Issue by NikoKrause** [linuxmint/Cinnamon#5398]
I often find myself opening the settings of the sound applet, so I can turn the slider of the sound volume to more than 100%, because with the sound buttons it is only possible to turn the volume to 100%.

It would be great to have a checkbox or a counter, which allows you to set the max. volume% you can get with your sound buttons or sound ?wheel? (is this the right word?).

**Comment by anandrkris** [comment]
+1. Although should be a configurable options in applet settings. That is, allow > 100 %

**Comment by clefebvre** [comment]
https://github.com/linuxmint/Cinnamon/pull/7238
