### ISSUE TITLE
slide switches are confusing

### ISSUE THREAD

**Issue by ByteHazard** [linuxmint/Cinnamon#5399]
The "on/off" switches used throughout Linux Mint Cinnamon are confusing, and should be replaced by traditional check-boxes. Despite their recent popularity, 'slide toggles' or 'slide switches' are regarded by many end-users as anti-intuitive, and violate basic user interface design principles.
Read more here: http://ux.stackexchange.com/questions/63884/checkbox-vs-toggle

My suggestion is to make the appearance of this particular UI control configurable via theme settings, with the default preferably being 'check box'.

**Comment by clefebvre** [comment]
That's outside of the scope for Cinnamon. This feature request should be done upstream with GTK.
