### ISSUE TITLE
Cinnamon, nvidia properitary driver but Graphics Card is not plugged in

### ISSUE THREAD

**Issue by jounathaen** [linuxmint/cinnamon#5400]
Hey Devs. First: I love cinnamon!
But I have a problem with this special setup:
I have a Laptop (MSI GS30) which has a Dockingstation with a PCIe port for a desktop graphics card. (Basically the whole dock is just a PCI extension). My Graphics Card inside the dock is the gtx780.
When I use the proprietary driver (nvidia-361) and use the Laptop outside the dock (with no external graphics card), Cinnamon crashes and goes to fallback mode. (Fallback mode works) - When Docked and connected to the gtx it works.
This Problem does NOT occur on Mate or Xfce.
Using the nouveau driver does not lead to this issue.
Here is the glass.log when it doesn't work:

> info t=2016-06-15T22:59:02.437Z Cinnamon.AppSystem.get_default() started in 188 ms
> info t=2016-06-15T22:59:02.440Z loading user theme: /usr/share/themes/Mint-Y/cinnamon/cinnamon.css
> info t=2016-06-15T22:59:02.454Z added icon directory: /usr/share/themes/Mint-Y/cinnamon
> info t=2016-06-15T22:59:02.500Z PlacesManager: Updating devices
> info t=2016-06-15T22:59:02.516Z loaded at Thu Jun 16 2016 00:59:02 GMT+0200 (CEST)
> info t=2016-06-15T22:59:02.754Z Loaded applet menu@cinnamon.org in 237 ms
> info t=2016-06-15T22:59:02.758Z Loaded applet show-desktop@cinnamon.org in 3 ms
> info t=2016-06-15T22:59:02.777Z Role locked: panellauncher
> info t=2016-06-15T22:59:02.777Z Loaded applet panel-launchers@cinnamon.org in 18 ms
> info t=2016-06-15T22:59:02.786Z Loaded applet window-list@cinnamon.org in 8 ms
> info t=2016-06-15T22:59:02.792Z Role locked: notifications
> info t=2016-06-15T22:59:02.795Z Loaded applet notifications@cinnamon.org in 8 ms
> info t=2016-06-15T22:59:02.800Z Loaded applet removable-drives@cinnamon.org in 5 ms
> info t=2016-06-15T22:59:02.828Z Loaded applet keyboard@cinnamon.org in 27 ms
> info t=2016-06-15T22:59:02.879Z Loaded applet network@cinnamon.org in 50 ms
> info t=2016-06-15T22:59:02.903Z Loaded applet sound@cinnamon.org in 23 ms
> info t=2016-06-15T22:59:02.914Z Loaded applet power@cinnamon.org in 11 ms
> info t=2016-06-15T22:59:02.920Z Loaded applet systray@cinnamon.org in 6 ms
> info t=2016-06-15T22:59:02.936Z Loaded applet calendar@cinnamon.org in 15 ms
> info t=2016-06-15T22:59:02.941Z Loaded applet windows-quick-list@cinnamon.org in 5 ms
> info t=2016-06-15T22:59:02.973Z Loaded applet sticky@scollins in 31 ms
> info t=2016-06-15T22:59:02.974Z AppletManager.init() started in 458 ms
> info t=2016-06-15T22:59:02.976Z Cinnamon took 737 ms to start
> info t=2016-06-15T22:59:03.515Z Adding systray: blueberry-tray.py (20x20px)
> info t=2016-06-15T22:59:03.516Z Hiding systray: network
> info t=2016-06-15T22:59:23.166Z Adding systray: mintupdate.py (20x20px)
> info t=2016-06-15T23:06:15.265Z GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.cinnamon.SettingsDaemon was not provided by any .service files
> trace t=2016-06-15T23:06:15.265Z 
> <----------------
> _proxyInvoker/asyncCallback@resource:///org/gnome/gjs/modules/overrides/Gio.js:83
> ---------------->

**Comment by icarter09** [comment]
@jounathaen are you still experiencing this issue?

**Comment by jounathaen** [comment]
I cannot tell you, because like every sane person, I came to the conclusion to sell my NVI%@! Card and bought an AMD one...

But this should be closed, as it is most probably a NVIDIA Bug and not a Cinnamon Bug
