### ISSUE TITLE
Feature Requests: Auto Disable Touchpad & Allow louder then 100% - Checkbox

### ISSUE THREAD

**Issue by masternetra** [linuxmint/Cinnamon#5403]
Just a couple of simple ideas, both already been implemented elsewhere already and are convenient/useful. 

1. Auto disable touchpad with mouse plugged in. In windows with the synaptic drivers installed I get a checkbox option that when checked disables touchpad when there is a mouse detected and re-enables it when there is no mouse present. 
I personally don't like to use the touchpad normally, but it is good for backup or when you can't use a mouse. With this option if for some reason you mouse dies (like with a wireless mouse) you wouldn't have to navigate into settings via keyboard just to enable the touchpad.

2. "Allow louder then 100%" checkbox. Ubuntu (unity) itself already has this, and have been quite disappointed to see mint in general doesn't (unless mate does, not into mate so haven't seen if it does or not) my volume at 100% is pretty conservatively low and often find myself having to push past the normal 100%. As it stands currently if one wants to raise the volume in Linux Mint Cinnamon, you have bring up sound settings and click and drag the volume past 100% while using the volume buttons/keys can drop it to or below 100%.
It would be far more convenient to just check a box in settings allowing volume past 100% and let the volume keys/buttons be able to handle the rest outside of settings.

**Comment by JosephMcc** [comment]
Please open one issue per feature request. It makes maintaining these easier. Also a quick search turns up this:
https://github.com/linuxmint/Cinnamon/issues/3721
and https://github.com/linuxmint/Cinnamon/issues/5398
