### ISSUE TITLE
Progress bar in windows list

### ISSUE THREAD

**Issue by qmarlats** [linuxmint/Cinnamon#5407]
I think it would be great to have a progress bar in the windows list, like on Plasma 5.6 ([see here](https://www.kde.org/announcements/plasma-5.6.0.php), at "Supercharged Task Manager"). And why not something directly integrated in Nemo, like Gnome.

**Comment by Vahan86** [comment]
+1

**Comment by Vahan86** [comment]
Issue https://github.com/linuxmint/Cinnamon/issues/2328
