### ISSUE TITLE
Dropdown menue (combobox) of firefox misplaced

### ISSUE THREAD

**Issue by Piiit** [linuxmint/Cinnamon#5409]
![search results - mozilla firefox_026](https://cloud.githubusercontent.com/assets/6096063/16357470/c776f728-3af7-11e6-9223-1805a9284481.jpg)

This happens with form fields and the search and address bar as well.
If I attach a second monitor as secondary to VGA the dropdown appears on the other screen only, but more or less on the right position regarding x-y-coords. It does not happen always, just some times. 

Firefox v47.0
Mint Cinnamon 17.3 
Cinnamon 2.8.8

**Comment by lestcape** [comment]
True, but i can not reproduced with cinnamon 3.0.5

**Comment by JosephMcc** [comment]
This was fixed in muffin for v3. Not sure what if any plans there are to address this for 2.8.

**Comment by Piiit** [comment]
Good news.

Could it be that this bug of xreader is also related to muffin?

https://github.com/linuxmint/xreader/issues/17

**Comment by JosephMcc** [comment]
Have you had the chance to test this under Cinnamon3. I would like to close this if the issue is resolved.

**Comment by Piiit** [comment]
@JosephMcc Sorry haven't thought of this since reporting, it is solved in Cinnamon3.
