### ISSUE TITLE
Cinnamon slow to load and fails loading themes

### ISSUE THREAD

**Issue by PiMaker** [linuxmint/Cinnamon#5411]
Sometimes Cinnamon takes about 15+ seconds to load, as supposed to the usual 2-4. When it comes up then, none of the themes (icon, shell) have been loaded, it's all on default. It loads correctly once I relog.

System: Laptop, Ubuntu 16.04, installed through apt-get (version 2.8.6), kernel: 4.2.0-36-generic, Theme: numix, seems to fail on all themes though

If you need a log file, tell me where to find it and I can upload it.

**Comment by JosephMcc** [comment]
Hopefully you will get Cinnamon 3 soon. I used it since 16.04 was alpha/beta and never ran into this issue. It's no guarantee it will fix but development has moved on to the newer version and it's possible that it's no longer an issue.

**Comment by Vahan86** [comment]
@PiMaker, is this still an issue for you with Cinnamon 3.8?

**Comment by PiMaker** [comment]
It's been more than 2 years... I don't even remember what issue I was having back then 😅 Haven't actually been using Cinnamon for quite some time now.

Anyway, thanks for coming back to this (I guess?), I'll close the issue since I don't think it is relevant any more.
