### ISSUE TITLE
cinnamon crashes when using any chromium-based browser

### ISSUE THREAD

**Issue by moore-bryan** [linuxmint/Cinnamon#5414]
Running Linux Mint Debian Edition, 3.16.0-4-amd64, cinnamon crashes into fallback mode when I launch any Chromium-based browser (Chrome or Opera Developer); this happens within minutes of launching the chromium-based browser.

**Comment by clefebvre** [comment]
We believe this issue is fixed. Please test against the latest Cinnamon version (3.6). If the issue happens again, create a new issue and add a stracktrace.
