### ISSUE TITLE
Crashs with 3 Monitors

### ISSUE THREAD

**Issue by Zomono** [linuxmint/Cinnamon#5415]
Linux Mint 18 Cinnamon 64Bit
Cinnamon 3.0.6
Kernel 4.4.0-28-generic
Nvidia Geforce GTX 560 Ti 
Driver: Nvidia Binary driver 367.27

Monitor-Setup1: LG 1920x1080*, Phillips 1280x1024
Monitor-Setup2: LG 1920x1080*, Phillips 1280x1024, Toshiba 1920x1080
*Main-Monitor

With Setup1 Cinnamon works fine, but if i try to apply Setup2 Cinnamon crashs immediately. Cinnamon tries to recover itself, but it fails and it ask me to try it again. But this way it takes no effect. strg+alt+esc doesn't work too.
I have to restart it by ctrg+alt+backspace or by rebooting.

**Comment by clefebvre** [comment]
We believe this issue is fixed. Please test against the latest Cinnamon version (3.6). If the issue happens again, create a new issue and add a stracktrace.
