### ISSUE TITLE
Cinnamon starts taking 100% cpu on fullscreen apps

### ISSUE THREAD

**Issue by SethDusek** [linuxmint/cinnamon#5416]
[Here](https://i.imgur.com/2ln1z5E.png) is a picture of cinnamon taking up 87.8% cpu while playing broforce. This often makes the system unusable, and this insane amount of cpu usage sometimes even locks up my system completely.

Version: Cinnamon 3.0.6
Drivers: Nvidia-364 with nvidia-prime 
Mint version: Linux mint 18 (happens on 17 too btw)
Fullscreen redirection is off btw, if that makes a difference

**Comment by kolorafa** [comment]
Try restarting cinnamon (alt+f2  type r and enter) no need to close windows

For me, after some time simple by running glxgears on fullscreen (fullhd) get cinnamon up to 95%
After restarting cinnamon it goes down to 17% (after closing glxgeras goes down to 7% as i have some windows open)

Arch + Cinnamon 3.0.7
nvidia-340xx
CPU xeon 2.3GHz

**Comment by SethDusek** [comment]
@kolorafa Yeah but that isn't a permanent solution, and I can see how that can become annoying having to do that every time

**Comment by Vahan86** [comment]
@SethDusek, is this still an issue in Cinnamon 3.6?

**Comment by eCyclops** [comment]
Certainly I have issues with Cinnamon maximizing processor use. In my case, the full-screen app was a screensaver left for two weeks. Cinnamon 3.8.9

**Comment by SethDusek** [comment]
> @SethDusek, is this still an issue in Cinnamon 3.6?

Hi, I saw this issue after a long time, and I'm sorry to say but I can't be of much help anymore. I no longer have the hardware that I had when I made this post, and I've also migrated to KDE due to unrelated reasons. I can close this if the devs would like.
