### ISSUE TITLE
Instances of launchers applet

### ISSUE THREAD

**Issue by heberjeur** [linuxmint/Cinnamon#5417]
When I remove all instances of launchers, it will be deactivated and then I add launchers applet, an other void instance, will be added that I can't remove it, the problem that instances will be added instance+1 without the possibility to reset to instance 1 only
![capture du 2016-07-02 17-35-52](https://cloud.githubusercontent.com/assets/11852634/16541472/d8dab228-407b-11e6-942f-2701e2a593a5.png)

**Comment by collinss** [comment]
Could you explain how you are removing them? Is it through the context menu, or settings, or does it do it with both? This might help track down the problem a little faster. Also, is it re-adding the previous instances to the panel, or do they only show up in the settings?

**Comment by Feuerfuchs** [comment]
I noticed the same issue while working on my applet.

As far as I can tell, this seems to be an issue with the cinnamon control center. Here are my observations:
- If I remove an instance using the context menu entry, it is removed from the panel. However, if I subsequently add a new instance and I open the applet settings, an additional non-existent instance is listed. I can repeat this as often as I want, another instance tab will be added every time.
- If I remove an instance using the "remove" button in the settings, both applet and tab disappear. If I then leave the applet settings and re-enter them (without closing the control center!), the removed instance tab is back (but not the applet).
- The issue fixes itself as soon as I close the control center

Hope that helps! :)

**Comment by heberjeur** [comment]
-I can't add the launcher to panel from the menu(right click to add not drag and drop)
-when I right click for exemple to add htop from the panel, I have a new firefox and nemo in the panel 
-The reset to default from panel launchers not work to me
-When I add a new launcher, I have two zones of launcher , in the right and in the left, and when I right click to remove them, I still have the space of the new added in the panel, I can remove this zone only in edition mode of the panel 
-The space of the second zone of launchers don't remove automaticelly when the new zone of lanchers is void, I can only remove them by right click in edition mode of the panel
:before
![capture du 2016-09-17 09-30-21](https://cloud.githubusercontent.com/assets/11852634/18607339/e1a8cf98-7cc1-11e6-8054-460802035158.png)
:after
![capture du 2016-09-17 09-34-25](https://cloud.githubusercontent.com/assets/11852634/18607338/e1a7d7dc-7cc1-11e6-86d1-dbbb7b48e900.png)


-I'm using the latest version of cinnamon 3.0.7
-If you want to receive any file I will send that to you , or you can see that by using teamviewer.
