### ISSUE TITLE
Wallpaper is to much zoomed in when one screen is as vertical

### ISSUE THREAD

**Issue by kermit007** [linuxmint/cinnamon#5418]
When one of screens is set as vertical the wallpaper use to get crazy. When the vertical one does its best and scales the height of given wallpaper, the second one (horizontal) gets extra-zoomed in.
When you first change the wallpaper the horizontal one is OK. But after login out and in or reboot you have situation like in attachment.

My observation is that the change is somehow connected to the fact that on the second screenshot we can see that bugged wallpaper on the right is the same width as the left one. Obviously its cut to fit the horizontal one. It's like the wallpaper is saved somewhere as this vertical one and then used on both screens.
But why every first set of wallpaper works fine during one session?

EDIT: Let me tell that the vertical screen can't have any icon placed above the level of horizontal one. You can see this also on the screenshot - the icon is on the maximum possible level there. If another issue should be opened - let me know.

EDIT2: If I want to set the wallpaper correctly again, I have set another one first and then the chosen one. Otherwise, I mean, when trying to set the same wallpaper - nothing changes.

![issue_first](https://cloud.githubusercontent.com/assets/18303951/16542368/f91e6966-40a4-11e6-9a55-946ea8d9b3f0.png)
![issue_after](https://cloud.githubusercontent.com/assets/18303951/16542369/fd1d0842-40a4-11e6-918b-0fa7cb91b70d.png)

**Comment by kermit007** [comment]
My observation is that the change is somehow connected to the fact that on the second screenshot we can see that bugged wallpaper on the right is the same width as the left one. Obviously its cut to fit the horizontal one. It's like the wallpaper is saved somewhere as this vertical one and then used on both screens.
But why every first set of wallpaper works fine during one session?

**Comment by Vahan86** [comment]
@kermit007, is this still an issue for you with Cinnamon 4.2?
