### ISSUE TITLE
Window Manager: Placement mode

### ISSUE THREAD

**Issue by Generator** [linuxmint/Cinnamon#542]
Like in Compiz: Place Windows, users can select the windows placement mode,  Cascate, Centered, Smart, Maximized...
One workaround is devilspie, but if implemented would be nice

**Comment by Anachron** [comment]
This has been implemented as of
https://github.com/leigh123linux/muffin/commit/43d5e6fe4ec489fef6acc08479691b6eeb5230d1

But I think muffins version included in Cinnamon is older than that. 
@mtwebster when do you expect a new Cinnamon-Release?

**Comment by mtwebster** [comment]
It will be *around* May (no fixed date)

**Comment by Anachron** [comment]
Thanks for the info! 
Will this be selectable with a dropdown menu in the "Windows"-Settings or only via `gsettings`?

**Comment by mtwebster** [comment]
We'll add a setting in Windows

**Comment by maninak** [comment]
I've looked everywhere for a workaround/hacked implementation of Compiz's "smart placement" of windows, where it will put them where there's open space etc. Sorely needed on a laptop mainly handled with the trackpad and an awesome feature to boot.

Would love to see it officially integrated, but until then if someone has found a way to bolt that feature in manually, please let me know.

**Comment by adam900710** [comment]
+1 for compiz/xfce4/openbox "smart placement".
Current muffin "auto" is only smart when there is enough open space.
And if there is, it just stack winodows into left up corner.

But compiz/xfce4/openbox's "smart placement" is *MUCH MUCH MUCH MUCH* smarter than that.
It will place window to ensure least coverage with others.

For me that's almost a killer feature.

**Comment by adam900710** [comment]
Any update?

**Comment by JosephMcc** [comment]
Not as far as I know
