### ISSUE TITLE
gcolor2, gcolor3 eyedropper not working in Mint 18 Cinnamon

### ISSUE THREAD

**Issue by vassilisw** [linuxmint/Cinnamon#5421]
As the title says, **gcolor2 and 3 eyedropper is not working**. It always returns black. I think it has do to with mint itself and not gcolor since they work on other distros and mint 17.
Tested on Mint 18 Sarah Cinnamon
This always happens

**Comment by JosephMcc** [comment]
Just tested gcolor2 on Cinnamon under Mint 18 and it seems to work fine. There is no gcolor3 package in the repos.

**Comment by vassilisw** [comment]
I was testing on a virtual box where it does not work! Sorry guys.
