### ISSUE TITLE
UI: Mint 18 Sarah Cinnamon buttons, do not have margins on dialogs

### ISSUE THREAD

**Issue by vassilisw** [linuxmint/Cinnamon#5422]
Check the screen shots to see what I mean: [Dialogs on Mint 18 with Mint X](http://imgur.com/y56BukA),
I think it's a little bit annoying to interact with [this](http://i.imgur.com/Fhmoq7Y.png) kind of buttons layout, instead of [this](http://i.imgur.com/CflEGYS.png).

**Comment by JosephMcc** [comment]
This has nothing to do with Cinnamon. That is how those dialogs are now designed in Gtk.
