### ISSUE TITLE
Mint 17, segmentation fault on load

### ISSUE THREAD

**Issue by meron1122** [linuxmint/Cinnamon#5425]
In last update from repo:
```
deb http://ppa.launchpad.net/gwendal-lebihan-dev/cinnamon-nightly/ubuntu trusty main
deb-src http://ppa.launchpad.net/gwendal-lebihan-dev/cinnamon-nightly/ubuntu trusty main
```
Cinnamon:
```
mer@mer-Precision-M4600 ~ % cinnamon --version
Cinnamon 3.0.6
```
Gives me segmentation fault on load after login :
```
mer@mer-Precision-M4600 ~ % cat .xsession-errors 
/etc/mdm/Xsession: Beginning session setup...
localuser:mer being added to access control list
Script for none started at run_im.
Segmentation fault
```
What's more log you need?

**Comment by JosephMcc** [comment]
Not sure what is causing the segfault but you should stop using the Cinnamon nightly builds on Mint 17. Cinnamon 3.0 is not officially supported and it could break at anytime. That PPA also includes things like MDM which are updated for Mint 18 and I'm not sure all of those changes are compatible with Mint 17.

**Comment by sakuraiben** [comment]
Uninstalled Cinnamon and installed kde-full and it works like a charm.  Seems like I broke the settings for the desktop environment some how.  Still looking for a solution for cinnamon if possible though.

**Comment by JosephMcc** [comment]
Did you try reinstalling Cinnamon 2.8?
