### ISSUE TITLE
Shortcuts got stuck

### ISSUE THREAD

**Issue by hxingpax** [linuxmint/cinnamon#5427]
After the recent updates, shortcuts get stuck randomly.
e.g.
System does not response to Ctrl + Alt + t and Win + e at the moment I press. But, a random time later, tons of terminals and Home folders pop up.

Do not know how it happens , seems like has something to do with my recently packages updates.

**Comment by Vahan86** [comment]
@hxingpax, is this issue still relevant to Cinnamon 4.2?
