### ISSUE TITLE
Horizontal scrolling above sound applet moves to next song

### ISSUE THREAD

**Issue by MavropaliasG** [linuxmint/Cinnamon#5428]
Hello,

Vertical scrolling on the sound applet increases or reduces the sound volume, could we have horizontal scrolling to skip to next or previous track ?

**Comment by clefebvre** [comment]
https://github.com/linuxmint/Cinnamon/commit/117d0c2e03d168ce9301d2f0cb7c724c29297bb1

**Comment by germanfr** [comment]
@clefebvre That is causing issues with the touchpad, because it never scrolls perfectly vertical, it always has some horizontal scrolling and accidentally moves to the next song when changing the volume.
