### ISSUE TITLE
Strange behaviour when clicking "All Windows" button while many windows are opened

### ISSUE THREAD

**Issue by nurgasemetey** [linuxmint/cinnamon#5429]
Hello guys,

Here is there screenshot:

![Windows list](http://i.imgur.com/Se82QZC.png)

As you can see, the beginning of headings are not seen.

There are many windows opened also there are 5 workspaces.

![Workspace list](http://i.imgur.com/hvS0LrZ.png)

System specs:
- Cinnamon 3.0.6
- Linux Mint 18
- Nvidia 361.42

**Comment by Vahan86** [comment]
@nurgasemetey, is this still an issue in Cinnamon 4.2?

**Comment by nurgasemetey** [comment]
@Vahan86 I am not using Cinnamon 4.2 yet, so I don't know whether it is still issue or not

**Comment by icarter09** [comment]
@nurgasemetey can you update this ticket with new screenshots and the steps necessary to reproduce the issue? The original screenshots you provided are no longer present. Thanks.

**Comment by nurgasemetey** [comment]
Can we close issue, because I updated cinnamon version
