### ISSUE TITLE
Add "Recent apps" to cinnamon Menu.

### ISSUE THREAD

**Issue by alxgvr** [linuxmint/Cinnamon#5430]
Hi. We have "recent documents" folder in Menu.
Would be great if we also will able to see last used apps.

**Comment by lestcape** [comment]
Gnome Shell have a feature to count the app usage. This was ported and then removed from the cinnamon source some years ago and could be used for what you want also. Is necessary a way to save this data, as was removed the code there are not a way.

**Comment by Vahan86** [comment]
https://github.com/linuxmint/Cinnamon/issues/97
