### ISSUE TITLE
Bug with filemanager.

### ISSUE THREAD

**Issue by alxgvr** [linuxmint/Cinnamon#5433]
Have noticed a bug.

When some folder in FM is opened, and you change your icon theme in settings - your FM will crash if you press "back" arrow or open random folder. It happens after icon theme being changed.

**Comment by GLolol** [comment]
Assuming you're using Cinnamon's Nemo file manager, this should be reported at https://github.com/linuxmint/nemo/issues

**Comment by alxgvr** [comment]
Done.
