### ISSUE TITLE
LM 18: keypad not initialized correctly

### ISSUE THREAD

**Issue by Mintulix** [linuxmint/Cinnamon#5434]
On session start the internal keypad on my keyboard (Samsung notebook series 7) is shown as num-lock=true, but I have to turn num-lock off and on again to get numbers while typing in any application.

**Comment by Mintulix** [comment]
I found a solution: "sudo apt install numlockx" and mark the numlock checkbox in the MDM options. I think numlockx has to be installed by default (was it in earlier versions?).

**Comment by JosephMcc** [comment]
I've seen this issue come up several times. On my own machine I have to hit the numlock button once after doing the initial install. It always stays on after that. It's the same for me in other DE's I've tried in Mint as well so I'm not sure Cinnamon actually has anything to do with this.
