### ISSUE TITLE
Suspend-resume cycle multiple issues

### ISSUE THREAD

**Issue by Queeq** [linuxmint/cinnamon#5436]
Hi all,
My system is the following:

```
System:    Host: queeq-laptop Kernel: 4.4.14 x86_64 (64 bit gcc: 5.3.1)
           Desktop: Cinnamon 3.0.6 (Gtk 3.18.9-1ubuntu3) Distro: Linux Mint 18 Sarah
Machine:   System: SAMSUNG product: 940X3L v: P05AFD
           Mobo: SAMSUNG model: NP940X3L-K01US v: SGL8558A1O-C01-G001-S0001+10.0.10240
           Bios: American Megatrends v: P05AFD.043.151016.PS date: 10/16/2015
CPU:       Dual core Intel Core i7-6500U (-HT-MCP-) cache: 4096 KB
           flags: (lm nx sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx) bmips: 10368
           clock speeds: max: 3100 MHz 1: 478 MHz 2: 845 MHz 3: 499 MHz 4: 494 MHz
Graphics:  Card: Intel Sky Lake Integrated Graphics bus-ID: 00:02.0
           Display Server: X.Org 1.18.3 drivers: intel (unloaded: fbdev,vesa) Resolution: 3200x1800@60.00hz
           GLX Renderer: Mesa DRI Intel HD Graphics 520 (Skylake GT2)
           GLX Version: 3.0 Mesa 11.2.0 Direct Rendering: Yes
```

After resuming from suspend the following issues appear:
1. `G2Touch Multi-Touch by G2TSP` touchscreen stops working. It's still visible in `xinput`. Reloading `hid_multitouch` kernel module has no effect. `xinput enable <id>` doesn't work either. There seemed to be similar bug in upstream that was fixed long time ago but unfortunately I can't find where I saw it.
2. Some applications seem to lose HiDPI setting (interface elements become tiny) if (re)started after the laptop had been resumed from suspend. Examples are:
   - Libreoffice
   - Owncloud client
   - Virtualbox
   - Skype

**Comment by MavropaliasG** [comment]
Please try to install latest stable kernel and report if problems persist.

**Comment by Queeq** [comment]
Booted with 4.4.0-28-generic kernel. Both problems do persist. BTW, I also use linux-firmware 1.158 as my Atheros QCA6174 wireless card doesn't work otherwise.

It seems, however, that the second issue is not connected with suspend, but with something else (uptime?). Logging off/on helps to resolve it. I will test further.

**Comment by EcmaXp** [comment]
This issue can be found on other sites.

- https://forums.opensuse.org/showthread.php/524480-Touchpad-stops-working-after-1-minutes
- https://ask.fedoraproject.org/en/question/111734/touchpad-not-working/

I have a touchscreen that uses "Multi-Touch by G2TSP", and I have the same problem in Windows. Therefore, this problem is not a kernel problem, but rather a problem with the device itself.

Turn on the program that you can draw and try drawing yourself after one minute. After a little delay, it will be displayed as painted.

**Comment by icarter09** [comment]
@Queeq are you still experiencing this issue?

**Comment by Queeq** [comment]
Yes, but I haven't upgraded that laptop for ages.

**Comment by icarter09** [comment]
@Queeq what version of Mint and Cinnamon are you currently running?

**Comment by Queeq** [comment]
Linux Mind 18.3 Sylvia
Cinnamon 3.6.7+sylvia

I plan to upgrade it when next LTS comes out. Unless you really want to dig
into this issue, we can close it as it doesn't bother me much. I can always
open another issue if it persists in the new version.

сб, 7 дек. 2019 г. в 04:56, Isaac Carter <notifications@github.com>:

**Comment by icarter09** [comment]
@Queeq no worries and thank you. I was going to suggest that same idea.
