### ISSUE TITLE
Panel Disappears with XWinWrap running

### ISSUE THREAD

**Issue by feren** [linuxmint/Cinnamon#5437]
Whilst using Shantz's XWinWrap tool, the panel usually goes behind the xwinwrap window making it disappear completely meaning that you have to then use keyboard shortcuts to access applets, etc.

**Comment by JosephMcc** [comment]
https://github.com/linuxmint/Cinnamon/issues/5622

**Comment by feren** [comment]
Oops, forgot about that one.
