### ISSUE TITLE
Error messages when opening "Avilable desklets (online)" or "Avilable themes (online)"

### ISSUE THREAD

**Issue by surenenfiajyan** [linuxmint/cinnamon#5438]
When I opened "Avilable desklets (online)" or "Avilable themes (online)" for the first time, my screen was "bombarded" with nonsense error messages. This also happens when I refresh the list.

![screenshot from 2016-07-10 17-24-57](https://cloud.githubusercontent.com/assets/13224708/16713937/ad1cf5b4-46c6-11e6-9fe7-ca16e0009ac1.png)

Discovered in Mint 17.3 and 18.
I don't think it's a good idea to handle errors in such a way.

**Comment by NikoKrause** [comment]
I can't reproduce this. Is this still an issue?
If yes, how to reproduce?

**Comment by surenenfiajyan** [comment]
@NikoKrause Maybe it's fixed in the latest Mint (18.1), I'll try some day. But it can be also from the country, so in this case the problem is this "aggressive" way of handling errors.

**Comment by JosephMcc** [comment]
Yes, it can still happen.

**Comment by Vahan86** [comment]
@surenenfiajyan, is this still an issue for you with Cinnamon 4.2?

**Comment by Vahan86** [comment]
@icarter09, can we close this issue since there is no response from OP?
