### ISSUE TITLE
Active applet dialog prevent lock of screen after suspension

### ISSUE THREAD

**Issue by MavropaliasG** [linuxmint/Cinnamon#5441]
If I have the sound apple open (meaning I clicked on it and the dialog is open) or notes or calendar or network manager ( I believe it can be replicated with any applet) cause the computer not to lock the screen after it is resumed from suspension. While it suspends successfully, when it is resumed the screen is unlocked.

Linux mint 17.3 with Cinnamon 2.8.8.

**Comment by mswiszcz** [comment]
#1430
