### ISSUE TITLE
Manage workspace (Expo) has glitchy window behavior when hovering mouse over it or click+dragging window to another workspace

### ISSUE THREAD

**Issue by jessedubord** [linuxmint/Cinnamon#5442]
When you enter Expo ("Manage Workspaces" as it's called in the workspace applet) the window layout moves the app windows when your mouse hovers over it. Problem is, some window jerkily move behind other windows, instead of staying in place while your mouse hovers over to select the desired window.

Similarly, when you click+drag a window to another workspace, the windows in the destination workspace re-position themselves, but some windows instantly jump behind other windows.

To reproduce:
(1) Open Expo/Workspace manager
(2) Hover mouse over workspace OR click+drag window to another workspace

Actual result:
Window positioning is glitchy - some windows instantly move behind others.

Expected result:
Window positioning is balanced, smooth, and doesn't glitch and put some app windows behind others.

Reproduce:
Always

Details:
Bug discovered on Linux Mint 18 x64 (Ubuntu-base), Cinnamon 3.0.2 desktop environment.

**Comment by kulga** [comment]
Same environment
(*Bug discovered on Linux Mint 18 x64 (Ubuntu-base), Cinnamon 3.0.2 desktop environment.*)

Glitchy click dragging with higher cpu usage as well. Didn't occur once I dropped down the number of windows / decreased cpu usage.

http://i.imgur.com/LFcevOC.gif (GIF image)

And weird glitchy behavior of some windows on expo (in this case the **Image Viewer**)
![](http://i.imgur.com/qbzaDty.jpg)

**Comment by jessedubord** [comment]
That's exactly the problem. Thanks for the screenshot, kulga. :)
