### ISSUE TITLE
Scaling in cinnamon panel applets

### ISSUE THREAD

**Issue by kzemis** [linuxmint/Cinnamon#5446]
Hi

It is possible to scale cinnamon panel, but this scaling do not affect applet sizes in panel (for example, menu@cinnamon.org, calendar@cinnamon.org..etc)

It could be good to have some panel applet scaling (manual and/or automatic) because on screens with big resolutions it is not very friendly. At least for official cinnamon applets..

**Comment by brownsr** [comment]
@kzemis , there is an existing panel setting 'Allow Cinnamon to scale panel text and icons according to the panel width'.  You may have this turned off.

**Comment by Schleehauf** [comment]
Since the feature is present this issue/feature request should be marked as _closed_.
