### ISSUE TITLE
Reproducible Desktop Lock-Up Debugging w/Eclipse and IntelliJ

### ISSUE THREAD

**Issue by Ansury** [linuxmint/cinnamon#5448]
Identified a reproducible problem with the Mint Cinnamon desktop locking up when hitting a breakpoint debugging with Eclipse or IntelliJ. When I say it's locking up, I mean mouse clicks are completely inoperable (even on the Mint panel), but the mouse cursor still moves. Keyboard is unresponsive, except for some OS-level shortcuts like Alt-Tab. Alt-Tab looks like it's working, but selecting another window doesn't actually focus or activate the window (only the Alt-Tab selector popup works). I can only recover using Ctrl-Alt-ESC to restart Cinnamon. Everything proceeds fine after that. 

Debugging and breakpoints work fine everywhere else as far as I can tell except when the breakpoint is inside an anon inner class or lambda. 

Public git repo with a fairly simple example project causing this: 
https://bitbucket.org/jfxexamples/eclipseminttest

**Linux Mint 17.3 AND a totally new install of Mint 18 - both behave the same
Eclipse Neon 4.6.0  OR  InteliJ CE - issue occurs in both
Java 8 (1.8.0_92) - Oracle JDK (Using JavaFX)**

Code sample below (you'll have to grab the rest of the project files to run it): 

```
public class SampleController {

   @FXML
   private TabPane tabPane;

   public void createTab() {

      Tab tab = new Tab("New tab");//Breakpoint here does NOT freeze desktop

//      tab.setOnCloseRequest(e -> {
//         System.out.println("bleh");//Breakpoint here, freezes desktop
//      });
      tab.setOnCloseRequest(new EventHandler<Event>(){
          @Override public void handle(Event e){
             System.out.println("bleh");//Breakpoint here, also freezes desktop
          }
      });

      tabPane.getTabs().add(tab);//Breakpoint here does NOT freeze desktop
      int index = tabPane.getTabs().size() - 1;
      tabPane.getSelectionModel().select(index);
   }
}
```

**Comment by icarter09** [comment]
@Ansury are you still experiencing this issue?
