### ISSUE TITLE
LM18 log in bug

### ISSUE THREAD

**Issue by ReksioCroft** [linuxmint/Cinnamon#5449]
everytime i boot in linux mint 18, it shows the desktop image but no icons. I can't do anything. I must press ctrl+alt+backspace to log out and log in to start using the os(after that it works perfect). Even when i installed the os, it blocked and cinnamon go in emergency mode. Nothing like that happend in linux mint 17.3 . Please fix this bug.
( I use a laptop with nvidia gt-520m graphic card with proprietary driver v361.42-0ubuntu2, no external monitor connected )

**Comment by punkofnewsociety** [comment]
same crap with v367 driver
does it touch xorgconf file ? guys help to get rid of this emergency mode

**Comment by Vahan86** [comment]
@ReksioCroft, is this still an issue for you with Cinnamon 3.6?

**Comment by JosephMcc** [comment]
Closing due to lack of response and info to really do anything with.
