### ISSUE TITLE
Desktop freeze during tray menu update

### ISSUE THREAD

**Issue by wvandelli** [linuxmint/cinnamon#5451]
Hello,

  this is a follow up of owncloud/client#4990. The observation is a regular desktop freeze, lasting for a couple of seconds. This was traced down to the owncloud client applet updating the internal state of the tray menu instance during file synchronisation.
The diagnosis was verified running a modified owncloud client with a minimal (stateless) tray menu.

Arch Linux x64
Cinnamom 3.0.5
Owncloud Client 2.2.2

Interestingly, two very similar systems show different behaviours which seem to correlate to different tray menu styles (see https://github.com/owncloud/client/issues/4990#issuecomment-231352983)

Thanks
     Wainer

**Comment by lestcape** [comment]
Apparently this was improved in the client side and now it`s better. @wvandelli can you confirm that?

The indicators use the DbusMenuItems ids to find an id of an item between all updates cycles and the unmatched id items will be destroyed also if they exist in the next cycle, but with a different id.

So, if in some indicator client after perform an update cycle, we read different ids for the same items we are forced to destroy it and then they will create again with a different identification. If they have the same id we don't need to destroy it.

In cinnamon/gnome shell we used Clutter. In clutter you can not paint any component if are not visible and are not in the stage, all menu creation and destruction will occurs when the menu it's visible to the user and this will create that menu boxes change his size constantly and this cause the sensation of a flicker.

Will be good then if the indicators clients will avoid the unnecessary updates and if his ids will not be reassign, to not force cinnamon to destroy it and create it again when they are visibles by the users.
