### ISSUE TITLE
power settings not launching

### ISSUE THREAD

**Issue by mykeET** [linuxmint/Cinnamon#5452]
Power settings not launching after update. Cannot launch from power applet or from Cinammon System settings. Linux Mint 18.

Start-Date: 2016-07-14  19:51:55
Commandline: /usr/sbin/synaptic --hide-main-window --non-interactive --parent-window-id 54525981 -o Synaptic::closeZvt=true --progress-str Please wait, this can take some time --finish-str Update is complete --set-selections-file /tmp/tmpz6vwwo1v
Requested-By: myke (1000)
Install: xapps-common:amd64 (1.0.0, automatic)
Upgrade: language-pack-gnome-en:amd64 (1:16.04+20160415, 1:16.04+20160627), pix-data:amd64 (1.0.5+sarah, 1.0.6+sarah), language-pack-en:amd64 (1:16.04+20160415, 1:16.04+20160627), ecryptfs-utils:amd64 (111-0ubuntu1, 111-0ubuntu1.1), upower:amd64 (0.99.4-2ubuntu0.2, 0.99.4-2ubuntu0.3), dkms:amd64 (2.2.0.3-2ubuntu11, 2.2.0.3-2ubuntu11.1), mint-artwork-common:amd64 (2.0.5, 2.0.6), pix:amd64 (1.0.5+sarah, 1.0.6+sarah), language-pack-gnome-en-base:amd64 (1:16.04+20160415, 1:16.04+20160627), gir1.2-upowerglib-1.0:amd64 (0.99.4-2ubuntu0.2, 0.99.4-2ubuntu0.3), libupower-glib3:amd64 (0.99.4-2ubuntu0.2, 0.99.4-2ubuntu0.3), xviewer:amd64 (1.0.5+sarah, 1.0.6+sarah), language-pack-en-base:amd64 (1:16.04+20160415, 1:16.04+20160627), libecryptfs1:amd64 (111-0ubuntu1, 111-0ubuntu1.1)
End-Date: 2016-07-14  19:52:37

**Comment by shafter** [comment]
i confirm. if i try to start the power manager in terminal i get the error: segment fault

**Comment by mykeET** [comment]
issue fixed after update
