### ISSUE TITLE
Add ability to hide window labels on panels

### ISSUE THREAD

**Issue by KamranMackey** [linuxmint/Cinnamon#5454]
Since Windows gives you the ability to hide window labels (it's enabled by default and fairly useful). I was wondering if the ability to hide window labels in Cinnamon could be implemented. Would make panels look less cluttered if people want to hide window labels.

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
