### ISSUE TITLE
Impossible to apply "on scroll" action when a menu is open

### ISSUE THREAD

**Issue by DG-Tal** [linuxmint/Cinnamon#5455]
This might be the intended behavior, but when a cinnamon menu is open, you can't pass a "on scroll " command (like adjusting the volume or shading/adjusting opacity on a windows) to any other element of the interface.

This is pretty minor bug, but I think it would be great polishing to allow these kind of actions with a menu open.

Edit:Cinnamon version 3.0.7

**Comment by JosephMcc** [comment]
The cause of this is the same as https://github.com/linuxmint/Cinnamon/issues/5295
