### ISSUE TITLE
Brightness gets resets on shutdown or restart

### ISSUE THREAD

**Issue by sayyaff** [linuxmint/Cinnamon#5456]
The brightness should not get reset on shutdown or restart. When the user sets his brightness it should stick to the level user has set, But currently it resets the brightness when after a restart

**Comment by mykeET** [comment]
Same thing used to happen to me on Linux Mint 17.3. I upgraded to Mint 18 and problem solved.

**Comment by JosephMcc** [comment]
I'd like for the OP to confirm this so it could be closed. He provides no information on Cinnamon version or even the OS being run.

**Comment by Raijukami2** [comment]
Ah yes. I know how to fix this.
Open up a terminal and paste this:
sudo add-apt-repository ppa:nrbrtx/sysvinit-backlight && sudo apt-get update && sudo apt-get install sysvinit-backlight
It does fix it in 17.3, I cannot say in 18.

**Comment by sayyaff** [comment]
@Raijukami2 Thank you for clearing this up it works according to the fix you have given
