### ISSUE TITLE
Trying out on-screen-keyboard messes up window maximization

### ISSUE THREAD

**Issue by marko-avlijas** [linuxmint/cinnamon#5457]
There are 3 options for OSK layout and it's accessible from Menu->Preferences->Accessibility. I tried them out and choose one (the default one, touch) and closed the preferences/accessibility window. 

Cinnamon still operates as if OSK is on and maximizes windows only half way. Still haven't rebooted, sure hope it will go away.

Cinnamon version: which ever is the latest one available in mint 18 repos.
Google doesn't tell me quickly how to look that up.

**Comment by JosephMcc** [comment]
You can find your cinnamon version listed in Cinnamon-settings->System info or by typing `cinnamon --version` in a terminal.

**Comment by icarter09** [comment]
@marko-avlijas are you still experiencing this issue?
