### ISSUE TITLE
Cinnamon menu applet: right-click produces excessively short context menu, if application list is long

### ISSUE THREAD

**Issue by ghost** [linuxmint/cinnamon#5461]
To reproduce:
- Open Mint Menu;
- right-click an item (as against a category);
- the menu containing 'add to panel' and 'add to desktop' is either (1) so small that only one line shows at a time, or (2) not visible - save for a fragment of a scrollbar - or (3) displayed as it should be, i.e. in full.

Tested with these desktop themes: Linux Mint; Cinnamon.

What should happen: the whole menu should appear, i.e. scenario 3 should always obtain.

Can people reproduce this?

Mint 18 Cinnamon x64.

**Comment by JosephMcc** [comment]
I can't. It seems to working fine here.

**Comment by ACinnamonUserInUK** [comment]
Thanks for testing, Joseph. I myself have just now tried changing icon theme, border theme and mouse theme, and I still get the same result with some of the menu entries. Please see screenshot, in which you should look under 'account details': in the screenshot, I've just right clicked on it. The same situation obtains with, at least, all entries in that column that begin with 'a'.

![screenshot-area-2016-07-17-195714](https://cloud.githubusercontent.com/assets/9998846/16902529/4e15ac58-4c59-11e6-8da2-1a9b0d1ac750.png)

I wonder whether panel settings might be making a difference.

**Comment by JosephMcc** [comment]
Have you made some type of modifications to the menu applet? Your favorites icons, for example, aren't sized the same as mine. I should also mention I don't think I have anywhere near the amount of things installed as you.

**Comment by ACinnamonUserInUK** [comment]
I have not modified the code of the menu applet, unless it was via a desktop theme and, as I said, this problem occurs even when using the inbuilt themes. I have used the in-built menu editor to removed a few entries from the menu and to add the occasional entry.

Perhaps I should add that the version of MintMenu on my system is 5.7.2 and that a description that it gives of itself, via Synaptic, is 'Advanced MATE menu'. Is all that as it should be on Mint 18 Cinnamon?

**Comment by JosephMcc** [comment]
Cinnamon doesn't use Mint Menu at all. You will notice the description even points out it's for the Mate desktop. Cinnamon uses it's own menu applet.

**Comment by ACinnamonUserInUK** [comment]
Ah - my mistake. I think I had Mint Menu installed for when I trying to
use it with Cairo Dock, or something. I've uninstalled it (Mint Menu, I
mean). Still: the original problem - with the menu that *is* in Cinnamon
- remains.

**Comment by JosephMcc** [comment]
Are you using any type of custom settings for things like font scaling? Also check in ~/.xsession-errors after you do a restart of your machine and reproduce this problem. Is there anything that looks like it could be related to the menu?

**Comment by ACinnamonUserInUK** [comment]
Font scaling setting (in Settings - Fonts): 1.0.

~/.xsession-errors:

    initctl: Unable to connect to Upstart: Failed to connect to socket
    /com/ubuntu/upstart: Connection refused


    sys:1: PyGIWarning: Nemo was imported without specifying a version
    first. Use gi.require_version('Nemo', '3.0') before import to ensure
    that the right version gets loaded.

    /usr/lib/python2.7/dist-packages/syncthing_gtk/notifications.py:16:
    PyGIWarning: Notify was imported without specifying a version first.
    Use gi.require_version('Notify', '0.7') before import to ensure that
    the right version gets loaded.


    Cjs-Message: JS WARNING:
    [/home/[redacted]/.local/share/cinnamon/applets/capture@rjanja/applet.js
    1279]: anonymous function does not always return a value


    [93m[WARN 01:40:38.461939][0m [desktop-file-service:72] X-Cinnamon
    is not understood


None of this looks to me as though it is likely to be related to the
menu problem - but I am not really in a position to know.

**Comment by ACinnamonUserInUK** [comment]
UPDATE:

I tried the 'restore system configuration' option within the menu editor. Result: CInnamon crashed, and, when it restarted, gave me a bottom panel that I did not have before and that I could not remove and on which right-clicking on items did nothing.

Also relevant: I find that if, in Mint Menu, I _search_ for items, then, in the results list, right-click works again - and so I can once more, e.g. add launchers to the destkop.

**Comment by ACinnamonUserInUK** [comment]
This problem persists on Mint 18.1 Cinnamon.


Mint 18.1 x64.
Cinnamon 3.2.6.

**Comment by CottonEaster** [comment]
This still happens in Mint 19 (and gets in the way of things I want to do). It seems also to have been reported as #7427, as well.

**Comment by clefebvre** [comment]
I can't reproduce this issue.

**Comment by smurphos** [comment]
Mmm - this issue is still present in 4.2 & 4.4.  To reproduce you need to find a combination of display 
 and theme settings that result in a menu size that is very close to the vertical resolution of the screen. The people reporting it with stock themes are likely forcing HIDPI on resolutions that don't meet the threshold for auto-HIDPI. Another way is on a relatively low resolution display to up the Text-Scaling factor significantly. Certain theme characteristics can also trigger it.

Anyway my issue on is still open - https://github.com/linuxmint/cinnamon/issues/7427

**Comment by icarter09** [comment]
@smurphos this was closed because the original reporter of the issue is no longer present and no one could reproduce the issue. If you think your ticket (#7427) will suffice in its place, then I'll leave it closed. If not, just let me know and I'll reopen it.

**Comment by LinuxOnTheDesktop** [comment]
1) This issue needs retitling: for, we've discovered it is a problem with HiDPI at certain resolutions.
2) The problem persists on Mint 19.3.
3) Since in Mint 19.3 the 'Cinnmenu' extension no longer works, there is - to my knowledge - no longer a workaround for this problem. So I think the issue needs re-opening.

**Comment by smurphos** [comment]
It's not HIDPI specific, that's just one way to manifest the issue. See https://forums.linuxmint.com/viewtopic.php?p=1727864#p1727864 if you want Cinnamenu in 4.4
