### ISSUE TITLE
freezing panel/taskbar

### ISSUE THREAD

**Issue by ZacDiggum** [linuxmint/cinnamon#5463]
Hi,
I'm using MEGAsync client on Linux Mint 18 with Cinnamon 3.0.7. I posted an issue regarding the indicator freezing the taskbar at the [MEGAsync github page](https://github.com/meganz/MEGAsync/issues/23). I think the problem might rather be with Cinnamon instead of MEGAsync. You'll find the discussion in the provided link.

**Comment by Vahan86** [comment]
@ZacDiggum, is this still an issue in Cinnamon 3.6?

**Comment by Vahan86** [comment]
@JosephMcc, can we close this issue?

**Comment by Vahan86** [comment]
@icarter09, since there is no response from OP, can we close the issue?
