### ISSUE TITLE
Lose of focus name when saving a document after creating a folder

### ISSUE THREAD

**Issue by artik** [linuxmint/Cinnamon#5464]
While saving a document, if I create a folder the focus name is lost, and the quick search appear, instead of keeping the focus on the name. We have a re-select the name if we want to change it (or change it before creating a folder)

![screenshot](https://cloud.githubusercontent.com/assets/1015856/16918522/02de58d6-4d06-11e6-89bb-ace7a6a23707.png)

**Comment by JosephMcc** [comment]
That dialog is provided by Gnome's gtk2 toolkit. It isn't a part of Cinnamon or developed by us. Since most dev goes towards gtk3 now I would be surprised if this is ever fixed.
