### ISSUE TITLE
Left panel in nemo doesn't expand after reduction

### ISSUE THREAD

**Issue by artik** [linuxmint/Cinnamon#5465]
When nemo is opened, if I reduce the window, the left panel becomes thin. If I expand again, it stays thin, and I have to open it again manually :

Before reducing size:
![screenshot](https://cloud.githubusercontent.com/assets/1015856/16918612/74bd632a-4d06-11e6-9696-6252f724e382.png)

Reduced:
![screenshot](https://cloud.githubusercontent.com/assets/1015856/16918623/841fa15c-4d06-11e6-9174-5ca677505039.png)

Re-opened:
![screenshot](https://cloud.githubusercontent.com/assets/1015856/16918635/9623b4d8-4d06-11e6-9ef9-3362130d1e67.png)

The left panel shoul be size fixed in all cases (like previous versions of mint)

**Comment by JosephMcc** [comment]
This is a Nemo issue: https://github.com/linuxmint/nemo/issues
