### ISSUE TITLE
"Timed out stopping" processes when I shutdown / reboot Mint

### ISSUE THREAD

**Issue by artik** [linuxmint/cinnamon#5466]
When I shutdown Mint, I always have to wait few processes to stop. the problem is these processes don't shutdown by themselves and I need to wait the time out (2minutes) got get my computer shutting down / rebooting.

I use Mint as fully encrypted. I think the main issue is here.

![9aea55e1-dff9-4d48-bf4a-7268950c82d7](https://cloud.githubusercontent.com/assets/1015856/16918801/5fcd19e6-4d07-11e6-89db-d5657b8034c7.jpg)

**Comment by Vahan86** [comment]
@artik, does this issue still relevant to Cinnamon 3.6?

**Comment by mockdeep** [comment]
I see a lot of timeouts too when shutting down. Probably 50% or more of the time. Not quite the same error, but looks similar:

![img_20180331_155405](https://user-images.githubusercontent.com/80543/38168264-e61c1f36-3579-11e8-99f8-60564d0430a6.jpg)

I saw this fairly often on 18.1 and recently did a fresh install with 18.3 and I'm still seeing the issue.

**Comment by icarter09** [comment]
@artik are you still experiencing this issue?

**Comment by artik** [comment]
Hi @icarter09 Problem solved! It was a md, smd, or mdm issue, don't remember the name. Something quite low in the boot process, and has been fixed in the meanwhile ;)
