### ISSUE TITLE
Add a sound effect for notifications

### ISSUE THREAD

**Issue by ruscur** [linuxmint/Cinnamon#5467]
Notifications are meant to notify the user of something, and there (seems to be) no built-in audio for this, and there's no entry for it in the Sound Effects menu.  Users should be able to opt-in to having a sound of their choice play when a notification is sent.

**Comment by ruscur** [comment]
I'd be happy to work on this myself if someone could point me in the right direction.

**Comment by JosephMcc** [comment]
Was just thinking about this yesterday. When I saw your feature request figured I might as well go ahead and do it.
