### ISSUE TITLE
cinnamon-settings: disable opening items by single click

### ISSUE THREAD

**Issue by f2404** [linuxmint/Cinnamon#5470]
Is this possible? I'm used to double click opening items, Nemo is configured this way, and I'm always forgetting that the Settings app opens items by a single click (which may lead to unintentional settings change by the second click after the first one has opened an item).

**Comment by JosephMcc** [comment]
I don't see this happening. You can't really compare nemo and cinnamon settings on this. In nemo you can select an item and then perform other actions on it like rename, multi-select, etc. In cinnamon settings you can't. So single click would select it but not do anything or just be ignored. That would just be strange. These are more like a button and behave more like one. It would also be inconsistent with how this works in any other DE that I can remember.
