### ISSUE TITLE
[3.0.7] Touchpad freezes randomly

### ISSUE THREAD

**Issue by wunderlich** [linuxmint/cinnamon#5471]
I am using the following system:
- Linux Mint 18 Cinnamon 64-Bit
- Cinnamon Version 3.0.7
- Thinkpad T440s

I just installed Linux Mint 18 and recognized, that the touchpad of my Thinkpad randomly freezes. Sometimes after some minutes, sometimes after hours. I am still able to push it down (the whole T440s's touchpad can be pushed to perform a left-click) and the trackpoint still works.

When i call

```
sudo modprobe -r psmouse
sudo modprobe psmouse
```

the touchpad works again. Restarting Cinnamon has no effect.

I'm not sure if this an Cinnamon-issue. But i had no problems using Linux Mint 17.3.

**Comment by Vahan86** [comment]
@wunderlich, is this still an issue for you with Cinnamon 3.6?

**Comment by Vahan86** [comment]
@JosephMcc, can we close this issue since there is no response from OP for a long time?

**Comment by wunderlich** [comment]
Sorry, I forgot to answer. The problem still exists with Linux Mint 19 Cinnamon and Cinnamon 3.8.9.

It still can be fixed calling

```
sudo modprobe -r psmouse
sudo modprobe psmouse
```

after the touchpad stops working.

**Comment by icarter09** [comment]
@wunderlich are you still experiencing this issue?

**Comment by wunderlich** [comment]
I don't have this notebook anymore. Unfortunately I can't test it …

**Comment by icarter09** [comment]
@wunderlich no worries and thanks for the update.
