### ISSUE TITLE
"Perform lid-closed...monitors attached" always turns off external monitors

### ISSUE THREAD

**Issue by tarocco** [linuxmint/cinnamon#5474]
When "Perform lid-closed action even with external monitors attached" is enabled under `System Settings > Power Management > Power` and the "When the lid is closed" action is set to "Do nothing", it stops showing any picture on its own LCD and the external monitor.

When this option is disabled, the external monitor stays on as expected. I feel like this is a bug because I cannot find any other options in System Settings that would have an effect on this behavior.

Is there something I'm missing or has something been made to reuse this setting inappropriately?

```
tarocco@tko-usb:~$ cinnamon --version
Cinnamon 3.0.7
tarocco@tko-usb:~$ uname -a
Linux tko-usb 4.6.0-040600-generic #201606100558 SMP Fri Jun 10 10:01:15 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

Help appreciated, thanks!

**Comment by Vahan86** [comment]
@tarocco, is this still an issue for you in Cinnamon 4.2?
