### ISSUE TITLE
[cinnamon-settings-user] Import avatar from Gravatar

### ISSUE THREAD

**Issue by KoczurekK** [linuxmint/Cinnamon#5475]
Hi!

Importing avatars from Gravatar would be nice feature as some people (like me) like to have one avatar for everything. It also isn't that hard to implement, because getting Gravatar image in Python is quite easy.

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
