### ISSUE TITLE
All applets settings are set to default on second monitors when a fullscreen game disable it

### ISSUE THREAD

**Issue by DG-Tal** [linuxmint/cinnamon#5476]
cinnamon 3.0.7
The game tested is killing floor, this bug only apply to games with similar fullscreen behavior.

When the game go into fullscreen mode, only the primary monitor is enabled (the other act as if he was disconnected). When the screen get re-enabled, the applets are reloaded with their default settings. 

Panels on the primary monitor are not affected.

**Comment by Vahan86** [comment]
@DG-Tal, is this still an issue for you with Cinnamon 3.6?
