### ISSUE TITLE
Remember window positions per monitors connected.

### ISSUE THREAD

**Issue by donquixote** [linuxmint/Cinnamon#5477]
I have a notebook with two extra monitors connected to it.

Sometimes I disconnect the external monitors, work with the laptop only, then reconnect them again.
Sometimes I disconnect the external monitors by accident, and immediately reconnect.

After reconnecting the monitors, windows are in different places than before.
E.g. before my browser was on an external monitor, and the terminal was on the notebook monitor.
Afterwards, they are vice versa.

Proposed solution:

Whenever a monitor is disconnected: For each window,
1. If no part of this window was on the disconnected monitor, do nothing.
2. Otherwise, remember the position of this window for the combination of monitors connected until just now.
   - If any position was previously remembered for this window for a different monitor combination, continue remembering this too. (This means more than one position can be remembered for one window)
   - If any position was previously remembered for this window for the same monitor combination, overwrite this position.
3. Move this window to one of the remaining monitors, the same way this is already happening now.

Whenever a window is moved by the user:
1. Forget any remembered position for this window.
2. Move it to the designated position.

Whenever a monitor is (re)connected: For each window,
1. Check if a remembered position exists for this window for this monitor combination.
   - If so, move the window to the remembered position.  
     It is now safe to forget this position, but it does not really matter.
   - If not, leave the window in place.

**Comment by siriux** [comment]
I'm interested on this too.

**Comment by sergem155** [comment]
That would be a great feature.

**Comment by mavo** [comment]
Pls do this!

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.

**Comment by dosmanak** [comment]
@JosephMcc does that mean it was implemented?

**Comment by alfonso-soto** [comment]
This will be awesome. Really interested.

**Comment by dosmanak** [comment]
I fixed a quick script that uses wmctrl and xwininfo to save/restore window arrangement. In case you wanna try I pushed it. https://github.com/dosmanak/wmsavior
