### ISSUE TITLE
Linux Mint 18 Problem Report Tool

### ISSUE THREAD

**Issue by gh4snow** [linuxmint/Cinnamon#5481]
It would be nice if Linux Mint 18 had a problem report tool that users could just click & be able to report a problem & have it be directed to the appropriate development folks.

**Comment by JosephMcc** [comment]
This is the place to report issues/requests for Cinnamon. Not for Linux Mint itself. You can submit ideas for Linux Mint as a whole here: https://community.linuxmint.com/
