### ISSUE TITLE
Linux Mint 18 Cinnamon Desktop 

### ISSUE THREAD

**Issue by gh4snow** [linuxmint/Cinnamon#5482]
My primary display is 1600x1200. Displays 2 & 3 are 1680x1050 rotated counter-clockwise.
I am using a background image /w mosaic pattern.
After a reboot, everything is A-OK. 
But after a power off reboot, displays 2 & 3 are not full screen.
I must open system configuration + display, & then manually apply the desktop.
After reboot, everything is A-OK.
But after a power off reboot, displays 2 & 3 are once again not full screen.
Using 2 AMD Radeon HD6450 Display Adapters /w Dell displays.
Linux Mint 18 Cinnamon x64 edition.
All hardware works fine with MSFT Win 7 Pro x64.

**Comment by JosephMcc** [comment]
Your description is confusing. You say it's fine after a reboot and then it's not after a reboot. You need to explain that a bit better.

**Comment by gh4snow** [comment]
Note the words "Power Off" vs just a "reboot".
It doesn't restore settings after a power off, power on reboot.

**Comment by two-dogs** [comment]
@gh4snow , there is 'suspend/hibernate/shutdown' and 'return from suspend/hibernate and boot-process' , your issues are all related to return from  suspend/hibernate, yes?

**Comment by gh4snow** [comment]
NO. Displays work fine when you click on restart.
When shutdown (power off), then power on & PC is booted, displays 2 & 3  are not set to full screen.
I don't use suspend/hibernate.
