### ISSUE TITLE
[AMD] Youtube fullscreen + inactivity = blocked video

### ISSUE THREAD

**Issue by marko-avlijas** [linuxmint/Cinnamon#5483]
If I watch a youtube video fullscreen and leave long enough for computer to start screen saver  or locks the computer then video is blocked. Clicking on screen plays/pauses youtube video. I can hear the new sound, but image is frozen and it doesn't react to mouse input.

It doesn't react to CTRL+F2, r  either.
I can not restart cinnamon with `cinnamon --replace` but at least I get an error message:

> Failed to connect to Mir: Failed to connect to server socket: No such file or directory
> Unable to init server: Could not connect: Connection refused
> Window manager error: Unable to open X display.

I don't know what to do so I just type reboot. :(
I can provide my configuration details if needed, but I need instructions on how to do it.

I can provide my configuration and more details if there is interest.

My power settings are:

> Turn off the screen when inactive for: 15 minutes
> Suspend when inactive for: Never

**Comment by marko-avlijas** [comment]
I didn't get this for long time, but I do get this regularly when I leave delugeweb open in one of firefox tabs. Delugeweb has memory leeks which cause whole system to eventually become unresponsive.

I think this is not an issue with Cinnamon. Sorry to spam with non issues.

**Comment by JosephMcc** [comment]
Thanks for following up.
