### ISSUE TITLE
[user@cinnamon.org] Question/FeatureRequest: Round/Circle User Icon

### ISSUE THREAD

**Issue by NikoKrause** [linuxmint/Cinnamon#5486]
Hey,

is it possible to make the user icon (not the border around the user icon but the user icon itself) round? 

I know I could take a picture and make it round with gimp, but that's not what I mean. 
I really mean, I'll choose any picture I want, and it will be shown as round (like in WhatsApp)?

I tried to change the 'stylesheet.css' (like described as here: https://www.abeautifulsite.net/how-to-make-rounded-images-with-css):

```
.user-icon {  
  border-radius: 50%;
}
```

but this doesn't work.

**Comment by RavetcoFX** [comment]
Where do you want to see a round user icon? the login screen, lock screen, user applet??

**Comment by NikoKrause** [comment]
@RavetcoFX
Yes, I mean the (login, lock screen) user@cinnamon.org applet.

**Comment by feren** [comment]
@RavetcoFX 
It would also be nifty to use such functionality in your own applets for Cinnamon
