### ISSUE TITLE
Dropbox and Genymotion popup menus does not renders on Cinnamon

### ISSUE THREAD

**Issue by BloodShura** [linuxmint/Cinnamon#5488]
**Cinnamon 3.0.6 on Fedora 23**

I have seen related issues to this, but most (if not all) of them relate to the Dropbox icon not showing on the tray at startup.

But, my problem is that the context popup menu, when clicking on the Dropbox icon on the system tray, **does not renders**:

![Dropbox](http://pix.toile-libre.org/upload/original/1469566949.png)

I noticed that this also happens when right-clicking in an emulated device on Genymotion:

![Genymotion](http://pix.toile-libre.org/upload/original/1469566971.png)

I've tested it also on GNOME, KDE and MATE, and it works alright.
Do anyone knows any workaround, or why specifically this happens?

**Comment by two-dogs** [comment]
@BloodShura  , what theme being used? one of the default themes?

**Comment by BloodShura** [comment]
@two-dogs Currently it's Windows 10 Light, but it happens on any theme: Adwaita, Traditional, Vertex, w/e...

**Comment by itzexor** [comment]
It could be an issue with the qt5 gtk rendering support changes that happened recently with qt 5.7, if you have that version installed.

**Comment by two-dogs** [comment]
@BloodShura  is it a qt5 app?

**Comment by BloodShura** [comment]
@two-dogs According to [Dropbox's help page](https://www.dropbox.com/en/help/3), yes.

**Comment by BloodShura** [comment]
@itzexor I read about it, well... so the only solution for now, would be recompiling Cinnamon and removing that line which changes the qt5's environment variable? :|

**Comment by two-dogs** [comment]
@BloodShura  look at fedora's equiv to qt5ct plugin, it should force qt5 to kick in where a qt5 instance needs it
and i use the OpenSuse equiv of qt5ct on Cinnamon, works well on everything i use and i use alot of kf5

**Comment by BloodShura** [comment]
@two-dogs Just installed qt5ct via DNF (newer yum). Also restarted my laptop. Nothing changed: the popups still are not rendered, and even changing the theme in qt5ct's interface do not change anything at all, including the Dropbox's settings GUI :(

**Comment by two-dogs** [comment]
@BloodShura  dont you need to add a env variable somewhere?

if you execute any qt5 app from terminal  do you see the plugin kickin? should

**Comment by BloodShura** [comment]
@two-dogs Oh, yes! Apparently, by doing "export QT_STYLE_OVERRIDE=gtk2" or even "export QT_STYLE_OVERRIDE=adwaita", as suggested on the mentioned issues, the popup then works as expected.
I'll try adding this line to $/.bashrc and see if then the Dropbox popup gets fixed (I don't know which one is actually loaded first by the system/Cinnamon).

**Comment by BloodShura** [comment]
Okay, just setting QT_STYLE_OVERRIDE in .bashrc did not work out.
So what I did:
- opened "Session Applications" menu
- changed the command executed by Dropbox from "dropbox start -i" to "export QT_STYLE_OVERRIDE=fusion && dropbox start -i":
![image](http://pix.toile-libre.org/upload/original/1469588937.png)

Now, Dropbox popup menu works as expected. Still it is not a global solution...

**Comment by leigh123linux** [comment]
@BloodShura 

There is a fixed cinnamon-session package in updates-testing that fixes the override issue

https://bodhi.fedoraproject.org/updates/FEDORA-2016-71e70311b7


http://pkgs.fedoraproject.org/cgit/rpms/cinnamon-session.git/plain/fix_qt_override.patch?h=f25

**Comment by two-dogs** [comment]
its easier on OpenSuse-TW , someone did a good job of packaging qt5ct,
did it work? my qt applets tend render well on the panel, there is this other enable that has to happen or maybe it does not,  in the panel config . @BloodShura
