### ISSUE TITLE
Location bar disappeared in File->Open in gedit, firefox, meld and other application

### ISSUE THREAD

**Issue by dreamworkerln** [linuxmint/Cinnamon#5491]
Linux Mint 18 Cinnamon:
In File->Open button "type a file name" disappeared in gedit, firefox and other application.
This button allow always show Location bar, instead pressing Ctrl+L every time.
Howto always show Location bar in File->Open dialog ? Thanks.

Was
![ad1058ec-54d4-11e6-881c-bb95b6ad09f9](https://cloud.githubusercontent.com/assets/3149061/17225348/9f33c6e6-5515-11e6-8859-c852a28f4b7e.png)

Now
![8eda7010-54d4-11e6-8e8d-a5d00da7cd5e](https://cloud.githubusercontent.com/assets/3149061/17225357/a7146d98-5515-11e6-8008-1213307b03d6.png)

**Comment by JosephMcc** [comment]
This has nothing to do with Cinnamon/Nemo. Those dialogs are provided by gtk and not something developed by the Mint team. You can use the forums or #linuxmint-help on IRC for support questions.
