### ISSUE TITLE
Bottom panel on a secondary monitor limits the y-coords tooltips and menus can show at on the primary monitor

### ISSUE THREAD

**Issue by Spiffyk** [linuxmint/cinnamon#5492]
I have got a sort of dual monitor setup as seen in the picture. (The built-in laptop monitor is set to primary)
![My monitor setup](https://cloud.githubusercontent.com/assets/2039454/17230304/b368c930-551b-11e6-970a-d5cb495df81e.png)

When I add a bottom panel to the secondary monitor, some things on the primary one start behaving strangely. This is most apparent when a tooltip shows up above the bottom line of the secondary monitor. Right-click menus tend to show up above the panel only, too.
![Reproduction of the bug](https://cloud.githubusercontent.com/assets/2039454/17230502/c8e55098-551c-11e6-9919-965eacd35589.png)

Once I remove the bottom panel from the secondary monitor, the problem goes away.

Also, this affects more elements than just tooltips and menus. It also causes similar problems with certain programs running in Wine, such as FL Studio, which refuses to maximize in the full height of the primary monitor.

My laptop is a Lenovo Y700, the 15" version with an nVidia GTX 960M with Linux Mint 18, fully updated.

**Comment by icarter09** [comment]
@Spiffyk are you still experiencing this issue?

**Comment by Vahan86** [comment]
@icarter09, can we close this issue?
