### ISSUE TITLE
Mouse multiple left-click behavior

### ISSUE THREAD

**Issue by noreasternhumidity** [linuxmint/cinnamon#5493]
```
$ inxi -Fxz
System:    Host: travel Kernel: 4.4.0-31-generic x86_64 (64 bit gcc: 5.3.1)
           Desktop: Cinnamon 3.0.7 (Gtk 3.18.9-1ubuntu3.1)
           Distro: Linux Mint 18 Sarah
Machine:   System: Dell (portable) product: Latitude E6420 v: 01
           Mobo: Dell model: 0X8R3Y Bios: Dell v: A22 date: 08/12/2015
CPU:       Dual core Intel Core i7-2640M (-HT-MCP-) cache: 4096 KB
           flags: (lm nx sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx) bmips: 11174
           clock speeds: max: 3500 MHz 1: 1101 MHz 2: 1774 MHz 3: 2746 MHz
           4: 950 MHz
Graphics:  Card: Intel 2nd Generation Core Processor Family Integrated Graphics Controller
           bus-ID: 00:02.0
           Display Server: X.Org 1.18.3 drivers: intel (unloaded: fbdev,vesa)
           Resolution: 1600x900@60.00hz
           GLX Renderer: Mesa DRI Intel Sandybridge Mobile
           GLX Version: 3.0 Mesa 11.2.0 Direct Rendering: Yes
Audio:     Card Intel 6 Series/C200 Series Family High Definition Audio Controller
           driver: snd_hda_intel bus-ID: 00:1b.0
           Sound: Advanced Linux Sound Architecture v: k4.4.0-31-generic
Network:   Card: Intel Wireless 7260 driver: iwlwifi bus-ID: 02:00.0
           IF: wlp2s0 state: up mac: <filter>
Drives:    HDD Total Size: 120.0GB (55.0% used)
           ID-1: /dev/sda model: Samsung_SSD_850 size: 120.0GB
Partition: ID-1: / size: 108G used: 60G (58%) fs: ext4 dev: /dev/sda1
           ID-2: swap-1 size: 2.40GB used: 0.00GB (0%) fs: swap dev: /dev/sda5
RAID:      No RAID devices: /proc/mdstat, md_mod kernel module present
Sensors:   System Temperatures: cpu: 55.0C mobo: N/A
           Fan Speeds (in rpm): cpu: N/A
Info:      Processes: 187 Uptime: 31 min Memory: 945.7/7863.0MB
           Init: systemd runlevel: 5 Gcc sys: 5.4.0
           Client: Shell (bash 4.3.421) inxi: 2.2.35 

```

The USB mouse left-click behavior is glitchy and unpredictable on different computers and with different brands of wired mice.  Single left-clicks sometimes behave as double left-clicks. Programs on the Desktop sometimes open more than one instance.  Panel at bottom of screen may minimize, then maximize a window, when I intend to minimize it, or even the other way around.  Also happens within programs (native Linux as well as Windows programs in Crossover Linux).  At the very worst, left-clicks sometimes happen just when I hover.  So now I am cautious with hovering, especially over any Remove or Delete buttons in my programs. 

I am patient but sometimes this causes unintended problems.

All mouse settings are default, no unusual software or modifications.  Never touched accessibility settings.  I regularly use Suspend to turn off computer.  Reboot doesn't seem to solve this though.  This seems to have started late in Mint 17.3 or early in Mint 18.  I have included the inxi output if that helps at all.

**Comment by irrenhaus3** [comment]
This bug still exists in Cinnamon 3.4.6, on Kernel 4.13.0. Same situation as the OP; the default mouse settings haven't been changed and no additional software modifying the mouse has been installed.  
It happens quite often that a second click registers immediately after the first one which causes windows to maximize when the intent was to drag them, and gets in the way of many mouse-centered GUI applications. The mouse in use is a Logitech USB mouse, and unfortunately I don't have mouses from other manufacturers to compare it to. However, on my laptop's touchpad, I haven't observed this behaviour yet.

**Comment by icarter09** [comment]
@irrenhaus3 are you still experiencing this issue?

**Comment by irrenhaus3** [comment]
@icarter09 Haven't experienced it in a long time; currently running Cinnamon 4.2.4, all input devices behave well.  
I should also mention that the mouse I was talking about here eventually broke - but it's a long time ago, so I can't pinpoint the timeframe. Just know that there is a possibility that it might have been broken hardware in the first place. ^^

**Comment by icarter09** [comment]
@irrenhaus3 thanks for the update. I'm going to close this ticket out. If you do happen to experience the issue again, just open a new ticket and reference back to this one if you want. Thanks.
