### ISSUE TITLE
Yubico

### ISSUE THREAD

**Issue by gh4snow** [linuxmint/Cinnamon#5496]
To use Yubico U2F device, the user must install libu2f-host packages, but
+after doing so, the user still does not see the USB device displayed anywhere.
+In Windows 7 Pro, it appears under "Devices & Printers".
+Seems to me it should appear under "System_Settings/Hardware/Yubico" ???

**Comment by xenopeek** [comment]
There is no control module for the system settings for Yubico devices that I can find; Yubico only provide standalone programs. Thus this wouldn't be an issue with the Cinnamon desktop environment itself as much as a support request for how to use Yubico devices on Linux Mint, right? If correct please close this issue and ask for support on the Linux Mint forums instead: https://forums.linuxmint.com/

See also https://www.yubico.com/faq/enable-u2f-linux/. You can install yubikey-neo-manager from Software Manager. If you search for other guides on using Yubikey on Linux it looks complex to set up.
