### ISSUE TITLE
Touch Screen support.

### ISSUE THREAD

**Issue by deepsidhu1313** [linuxmint/Cinnamon#5497]
I have a laptop with touch screen. May i request to improve the support for touch screens with features like "pinch-to-zoom" and "scrolling". As i tried to scroll using my touch screen on a document i was unable to do so. I know cinnamon is pure desktop experience, but adding few optional features can help users like me with hybrid devices.

**Comment by xenopeek** [comment]
You need to install touchegg for multitouch gesture support. You need to configure the gestures yourself AFAIK. For a GUI to configure gestures there is touchegg-gce but you have to compile it yourself: https://github.com/Raffarti/Touchegg-gce. An article about it: https://www.linux.com/learn/how-configure-touchscreen-linux. For further support with setting it up you could take the question to the forums: https://forums.linuxmint.com/

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
