### ISSUE TITLE
Allow panels to behave like desklets

### ISSUE THREAD

**Issue by andrew-w-sherman** [linuxmint/Cinnamon#5498]
There is currently no way to make panels always show while allowing windows to pass into the space occupied by the panel. This makes configs like mine (pictured) somewhat cumbersome. Is there any easy way to create an option to have a panel act like a desklet (such that it doesn't interfere with windows, stays at the bottom, and only interacts when directly clicked on)? The panel staying below other windows could be a nice feature to have in general, I think, and vastly expand customization options with (hopefully) not a lot of effort. Additionally, and this is a smaller point, is there a way to make panels persist under a full screened window? I have a transparent terminal window that I fullscreen frequently, and to have the panel visible in the same way the desklet is would be very convenient. A desklet that could contain applets would solve both of these problems at once.

![screenshot from 2016-07-30 00 50 37](https://cloud.githubusercontent.com/assets/6710925/17268172/11ba4db8-55f0-11e6-81e6-785882f666e7.png)

**Comment by SerafDosSantos** [comment]
There is actually a way. In "System Settings" > "Panels" in "Settings" section of the selected panel, the option "Auto-hide panel" select "Intelligently hide panel".

I think that's what you're looking for.

Cheers!

**Comment by andrew-w-sherman** [comment]
Intelligently hide panel helps to some extent, but ideally I'd like the equivalent of intelligently hide, except such that I could still see and click the icons even when a window overlaps.

**Comment by feren** [comment]
I get where your coming from with the idea
PS: It would also be nice to make panels float on screen and go to minimum width like in KDE and have those as options in Panel Settings @SerafDosSantos

**Comment by JosephMcc** [comment]
It seems to me like the best solution for what you want would actually be a custom desklet. Panels work the way they do for a reason. For example they set something called "struts" on your screen. The entire purpose of that is to limit where things can be placed. It's the reason that a window doesn't cover your panel when it is maximized for example. When you take away those sorts of things it really isn't a panel anymore and something like a desklet would more likely fit your needs.

**Comment by JosephMcc** [comment]
I'm going to close this since I don't think it's something we would be implementing. A panel is no longer a panel in the case you mentioned. A desklet could likely do what you want and something could surely be done via a third party extension. I just don't see us doing it.
