### ISSUE TITLE
Spanned Wallpaper with multiple resolutions doesn't scale correctly.

### ISSUE THREAD

**Issue by Draconicrose** [linuxmint/cinnamon#5501]
I have two monitors, one with a resolution of 1280x1024 and the other 1920x1080. I'm using a wallpaper that is 9372x2880. On Windows the wallpaper spans fine for both monitors, but on Mint the primary monitor (1080p) has background bars above and below the image, as shown in the attachment, while the secondary monitor only has one at the bottom. (in blue for demonstration purposes)
![screenshot from 2016-07-30 20-10-32](https://cloud.githubusercontent.com/assets/17189964/17272576/b9cd2d26-5691-11e6-9587-6faceda3bfc5.png)

**Comment by skylarmt** [comment]
+1.  Spanned backgrounds should be cropped to the correct aspect ratio before being displayed.

It should work like the Zoomed setting, except across all displays, not just one.

**Comment by bmonteirog** [comment]
+1

**Comment by tristan-shelton** [comment]
I also have the same issue, except that I have two monitors in landscape and one in portrait which is considerably taller than the other two. Spanned mode leaves big empty bars on the portrait monitor.

**Comment by CEatonTX** [comment]
I have a perfectly sized wallpaper that is not scaled correctly on span, leaving large black bars on each size.  Two monitors set at  1280x1024 (5:4) side by side. I set a wallpaper that is 2560x2048 and choose span, and I get :
![screenshot from 2018-07-10 10-41-53](https://user-images.githubusercontent.com/36697853/42521218-e7293064-842d-11e8-9a33-06e8c035b597.png)

**Comment by skylarmt** [comment]
@CEatonTX, your wallpaper is the same ratio as one of your monitors.  Make it the same size as your whole desktop, not 2x the size of a single monitor.  If your wallpaper is 2560x1024 it'll work.

**Comment by CEatonTX** [comment]
@skylarmt Thank you very much, that fixed it.  I don't know why that did not click in my head.

**Comment by icarter09** [comment]
@Draconicrose are you still experiencing this issue?

**Comment by Draconicrose** [comment]
I've stopped using a spanned wallpaper so I don't know if this issue has been resolved.

**Comment by icarter09** [comment]
@Draconicrose no worries and thanks for the update.

Does anyone else on this ticket have any updates to provide? Thanks.

**Comment by pcurie** [comment]
> +1. Spanned backgrounds should be cropped to the correct aspect ratio before being displayed.
> 
> It should work like the Zoomed setting, except across all displays, not just one.
> 
> It's a hassle to manually crop background images to the exact display size, especially with a slideshow.

The issue as described here is still present in mint 20 beta, automatic spanning would be awesome.

**Comment by fde-capu** [comment]
I use Cinnamon on Debian Buster; +1. Please zoom taking maximum monitor square, crop and set. I would be happy to make the algorithm in case someone takes the time to give a starting point (I am not used to interact with the official repositories).

**Comment by BenjD90** [comment]
The issue is still present, maybe Cinnamon should provide a new "mode" of "Picture aspect" to do "Spanned zoom" to do what @skylarmt said :

> Spanned backgrounds should be cropped to the correct aspect ratio before being displayed
