### ISSUE TITLE
Spices.py :  Maybe Shell Injection with a filename

### ISSUE THREAD

**Issue by TheRegRunner** [linuxmint/cinnamon#5502]
## File

/usr/share/cinnamon/cinnamon-settings/bin/Spices.py
## Line  487-489

...
tool = "/usr/share/cinnamon/cinnamon-settings/bin/installSchema.py %s" % (os.path.join(dirname, file.filename))
command = "%s %s" % (launcher, tool)
os.system(command)

**Comment by xenopeek** [comment]
I couldn't manage to get it to run a command as root. I tried with , ; | || && <() $() and a second command and all were run as the user themselves and not as root.

**Comment by icarter09** [comment]
@xenopeek can this ticket be closed?

**Comment by xenopeek** [comment]
Yes, closing it. The code quoted above is no longer present in the source nor are os.path or os.system used in the mentioned files.
