### ISSUE TITLE
Suspend is not Working on Pavilion TS14

### ISSUE THREAD

**Issue by favric** [linuxmint/Cinnamon#5506]
I've made a clear install of Mint 18 in my 2 years old pavilion (dual boot with Windows 10).

Suspend doesn't works, when i suspend or close the screen, the monitor turns off, but all the lights seem to be on, and the computer keeps working (the HDD remains hot as if it was on normal use).

Intel Core i5 4200U 1.60GHz  with ATI RADEON HD 8670

Thanks for your help.

**Comment by xenopeek** [comment]
This isn't an issue with Cinnamon itself but with Linux Mint 18 and your particular hardware. This issue can be closed.

Please ask for support with solving the suspend not working for your hardware on Linux Mint 18 on the Linux Mint forums: https://forums.linuxmint.com/
