### ISSUE TITLE
Window buttons get stuck in Cinnamon panel when click is interpreted as drag&drop

### ISSUE THREAD

**Issue by basic6** [linuxmint/cinnamon#5507]
It happens a _lot_ that clicking on a window button in the Cinnamon panel is treated like a drag&drop operation, even though the mouse button is not held while moving the mouse. Just like during a drag&drop operation, that window button follows the mouse cursor (within the panel). And every now and then, a window button gets stuck even after clicking on the panel again - which is what happened here. It's a very awkward and annoying bug.

Please see the attached screenshot. The window button of a browser window got stuck behind that of another browser window and it's impossible to get rid of it. It also makes it difficult to read the other window button.

![cinnamon tasklist fail and cursor grab workspace 12_003 2](https://cloud.githubusercontent.com/assets/2535481/17325397/a6d19eca-58ab-11e6-94fd-3f3258b4a2df.png)

Also, the mouse cursor was a cross in this case.

Another important aspect of this bug is that certain other windows don't work while this is going on. For example, the "Add applets to the panel" window is basically frozen. The cursor does not blink, it's not possible to scroll or click or do anything except close the window. The same goes for dconf-editor. Although it's somehow (with luck) possible to open the menu and click on "About" (but the menu item is not highlighted on hover), it's not possible to do anything with the window because clicking on elements simply does not work. It seems like something is still grabbed, blocking certain applications.
Also affected: gedit
Usually, when something in Cinnamon gets stuck so that the mouse does not work anymore, either Alt + Tab or Ctrl + Alt + F2 (and back) will make it work again. But not in this case.

**Comment by vranki** [comment]
Still happening (randomly) on cinnamon 3.2.8.

**Comment by icarter09** [comment]
@vranki are you still experiencing this issue?

**Comment by vranki** [comment]
I don't use Cinnamon anymore. If nobody else suffers from this anymore, i think the bug can be closed.

**Comment by icarter09** [comment]
@vranki thanks for the update.
