### ISSUE TITLE
[FEATURE REQUEST] Implement Windows "Aero" like transparency

### ISSUE THREAD

**Issue by Anti-Ultimate** [linuxmint/Cinnamon#5510]
like this
http://images.dailytech.com/nimage/Windows_7_Aero_Glass_Shadows_Wide.jpg

For instance, I think window title bars should be transparent. Can this be done with GTK though?

**Comment by JosephMcc** [comment]
https://github.com/linuxmint/Cinnamon/issues/2083

**Comment by Anti-Ultimate** [comment]
Yes, thank you for closing this because it's a duplicate of a three year old bug report with 2 comments and a typo in the title.

**Comment by JosephMcc** [comment]
Sorry but a duplicate is a duplicate. The fact that it only has two comments doesn't mean anything except that there either isn't much interest or it's not something that is likely to be implemented.
