### ISSUE TITLE
Changing Keyboard Shortcuts Resets Desktop Wallpaper

### ISSUE THREAD

**Issue by anniesbbs** [linuxmint/Cinnamon#5513]
Changing Keyboard Shortcuts Resets Desktop Wallpaper

1. VERSION - Linux Mint 18 x64 Cinnamon 3.0.7

2. Steps to reproduce:
     1. Set desired wallpaper
     2. Open Keyboard options > Shortcuts
     3. Create or change any shortcut
     4. The desktop wallpaper will change to the default, fresh install wallpaper

3. RESULT - Keyboard shortcut is created/changed and works, desktop background wallpaper changes to fresh install default.

4. EXPECTED - Only create or change a keyboard shortcut.

5. OCCURRENCE - Always.

**Comment by xenopeek** [comment]
I can't reproduce this on Linux Mint 18 x64 Cinnamon 3.0.7. Can you try creating a new user account, logging in to that, and trying to reproduce it from there? To determine if this is a system-wide issue or only an issue with your user account (in which case things like applets, extensions or themes might play into the cause).

**Comment by zosy** [comment]
same issue to me
i reinstall brand new linuxmint 18,all default settings,trying add short cut, though not reset wallpaper, but the log same generate in to .xsession-error:

(cinnamon:7148): St-CRITICAL **: st_widget_get_theme_node called on the widget [0x5652c5d42010 StScrollView.popup-sub-menu] which is not in the stage.

(cinnamon:7148): St-CRITICAL **: st_widget_get_theme_node called on the widget [0x5652c5d1c340 StScrollView.popup-sub-menu] which is not in the stage.

(cinnamon:7148): St-CRITICAL **: st_widget_get_theme_node called on the widget [0x5652c96dc830 StScrollView.popup-sub-menu] which is not in the stage.

linuxmint18 show is issue not frequency, i have tryed lot of time, when you add the 7 and 8 or 10 shortcut maybe, then click Add, interface will not responding about 2 seconds, the errors show up, although not reset the wallpaper, but i still think some wrong with it , and ENV s are differents,such as fedora 24, centos 7 and debian 8.5, cause shows reset wallpaper bug.

**Comment by JosephMcc** [comment]
https://github.com/linuxmint/Cinnamon/issues/3953
