### ISSUE TITLE
Per monitor HiDPI settings

### ISSUE THREAD

**Issue by donquixote** [linuxmint/Cinnamon#5514]
See also #3455 "More granular HiDPI settings" and #5477 "Remember window positions per monitors connected."

I (most of the time) work with 3 monitors: A small full-HD notebook monitor + 2 much bigger external monitors attached.

With native resolution, the fonts and everything on the notebook monitor are much too small compared to the external monitors.

Typically I put a terminal on the notebook monitor, and zoom it to around ~200% to make it readable.
(I suppose that others might desire a different zoom level.)

A more comfortable and universal solution would be to set a zoom level / HiDPI ratio per monitor.

Ideally, this should be saved separately per combination of connected monitors. E.g. the notebook standalone should use native resolution, but the notebook + these specific two external monitors should use 200% HiDPI on the notebook display.

**Comment by JosephMcc** [comment]
Not sure why you opened another issue for this when it could have been added to https://github.com/linuxmint/Cinnamon/issues/3455

If you actually read that thread you see that per monitor HiDPI settings simply aren't possible at this point in time.

**Comment by donquixote** [comment]
Well, at least in my own projects I prefer to have distinct requests in separate issues. Ideally, the starting post and the title should generally cover the complete intent of the issue. Things that go beyond the initial intent often better fit in distinct issues, imo.

Even if an issue is not currently technically possible to solve, the issue still has the purpose of documenting a user need, and also telling other visitors (possibly coming from search engines) that this has been requested, and why it is currently not going to happen.

But this is not my project by any means, so I won't make a big fuss about how issues are organized.

--------------

Btw I don't really care whether it is using any gtk-level HiDPI tech or just scaling fonts and toolbar sizes. But I don't even know if the latter can be configured per monitor currently.
