### ISSUE TITLE
Unable to get ordered windows list

### ISSUE THREAD

**Issue by DurandA** [linuxmint/Cinnamon#5516]
Using `wmctrl -l` the windows list is not ordered according to the _windows-list_ cinnamon applet.

I quickly checked https://github.com/linuxmint/Cinnamon/blob/master/files/usr/share/cinnamon/applets/window-list%40cinnamon.org/applet.js but I don't think we can get the ordered list from outside. This feature is necessary to enable `Win + 1...9` raising window shortcut.

**Comment by xenopeek** [comment]
Do you know of a desktop environment where `wmctrl -l` lists the windows according to the order on the panel's window list? I tried KDE, MATE and Xfce and `wmctrl -l` doesn't work like this on any of them. I think you expect too much from wmctrl.

See the linked issue which I think is  feature request that covers what you want to achieve. If you agree please close this issue.

**Comment by dandv** [comment]
Looks like this issue is a blocker for the [$100 bounty](https://github.com/linuxmint/Cinnamon/issues/3883#issuecomment-243874387) I've posted.

**Comment by mainmachine** [comment]
The alt-tab switchers seem to know what order the tabs are ordered, wonder where it's getting it's data...?
