### ISSUE TITLE
Snap to another window (groupable windows)

### ISSUE THREAD

**Issue by kulga** [linuxmint/Cinnamon#5520]
When a window is near another, it has "Edge resistance" so that you can neatly align them.
As a feature request, it would be great to allow them to stay aligned, grouping them in a sense (perhaps with a keyboard shortcut while dragging them together)

As a poorly done example

![](http://i.imgur.com/4AMFI3A.gif)

It'd need to be a "weak bond", 
staying together when a window is
- minimized
- changing workspaces
- dragged around screen
- gaining / losing focus

Breaking when a window is
- maximized
- closed
- tiled

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
