### ISSUE TITLE
[Fetaure request] Support for shortening file names on Desktop

### ISSUE THREAD

**Issue by lisuml** [linuxmint/Cinnamon#5521]
Currently there is no possibility to automatically hide part of the files / directories names when the name is too long, which cause some inconveniences when arranging desktop icons.

**Comment by JosephMcc** [comment]
That is actually handled by Nemo not Cinnamon: https://github.com/linuxmint/nemo/issues
There are already multiple open issues regarding Nemos handling of desktop icons there so you could probably do a search and add this to one of those.
