### ISSUE TITLE
Panel: window with urgency hint set is not blinking when desktop is selected

### ISSUE THREAD

**Issue by f2404** [linuxmint/cinnamon#5523]
If I set `gtk_window_set_urgency_hint()` for a terminal window, issue `sleep 5 && echo -e "\007\c"` command there and switch to another window, the terminal window button on the panel will start blinking after 5 seconds. However, if I do not switch to another window but just click desktop, the terminal window will lose the focus but the button won't blink.
See also https://bugzilla.xfce.org/show_bug.cgi?id=9928#c22 and https://bugzilla.xfce.org/show_bug.cgi?id=9928#c23.
Thanks.

**Comment by icarter09** [comment]
@f2404 are you still experiencing this issue?

**Comment by f2404** [comment]
I've stopped using Cinnamon, feel free to close the issue.

**Comment by icarter09** [comment]
@f2404 thanks for the update.
