### ISSUE TITLE
Finer control over scaling on small, higher res displays

### ISSUE THREAD

**Issue by petebachant** [linuxmint/Cinnamon#5526]
Sorry if this is already possible, but I really like the feature in Windows 10 where apps on my 14" 1080p display will automatically scale windows and fonts by 125%, and when I drag them back to my 24" 1080p display, they are normal size again. It seems the auto scaling only works for 4k displays?

**Comment by leigh123linux** [comment]
What you want isn't possible as gtk doesn't allow it, you would need to file a bug against gtk here

https://bugzilla.gnome.org
