### ISSUE TITLE
Mint-Y: bar colours inverted in touchpad setting window

### ISSUE THREAD

**Issue by ACinnamonUserInUK** [linuxmint/Cinnamon#5528]
Please see attached screenshot (which is also here: https://i.imgur.com/9Eix8l5.png). Within the screenshot, contrast the second slider with the first. Something strange and confusing is going on!
![imgur-2016_08_06-05 05 41](https://cloud.githubusercontent.com/assets/9998846/17454587/bbe8d1d0-5b93-11e6-8400-b0f97978fe6b.png)

**Comment by JosephMcc** [comment]
This has nothing to do with the theme. It's a known bug in cinnamon settings that is on our roadmap to fix.
