### ISSUE TITLE
Mint-Y theme: hard to see which button is highlighted on the shutdown menu

### ISSUE THREAD

**Issue by ACinnamonUserInUK** [linuxmint/Cinnamon#5529]
The menu I have in mind is the one that appears when one presses the power button (on a laptop) or selects 'quit' from the MintMenu. The overly subtle highlighting - which does matter because it indicates what will happen if the user presses return - varies with 'Control' theme. With the Mint-Y theme, the highlighting is, to me at least, too subtle.

I would attach a screenshot, but Mint's inbuilt function for that, and indeed a third-party tool that I use, have trouble taking a shot whilst Mint's shutdown dialogue box is open. Still, to reproduce the issue, all ones needs to do is to select the Mint-Y Control theme, then start shutdown, and then move between the buttons with the cursor keys.

**Comment by JosephMcc** [comment]
This has nothing to do with Cinnamon since changing the theme fixes it. Your issue is with the theme. And the highlighting effect is unlikely to be changed in the theme if I'm being honest.

**Comment by ACinnamonUserInUK** [comment]
Joseph:

> This has nothing to do with Cinnamon since changing the theme fixes it.

ah; I forgot that there was https://github.com/linuxmint/mint-y-theme. Apologies.

>  And the highlighting effect is unlikely to be changed in the theme if I'm being honest.

The dominant colour of various themes, such as Mint-X Blue, does make the highlighting more visible. Still: if the problem is somewhat theme independent, then might this be the right place to file a bug report after all?

**Comment by JosephMcc** [comment]
I meant it was unlikely to be changed in the Mint-Y theme. The gtk theme you use has total control over the highlighting effect of those buttons, not cinnamon.
