### ISSUE TITLE
change gnome interface scaling-factor does not work on HiDpi screen

### ISSUE THREAD

**Issue by gbuntu127** [linuxmint/Cinnamon#5530]
I just installed linux mint 18 with the following version info:
          
          $ inxi -S
          System:    Kernel: 4.4.0-31-generic x86_64 (64 bit) Desktop: Cinnamon 3.0.7
          Distro: Linux Mint 18 Sarah
          
          $ gnome-shell --version
          GNOME Shell 3.18.5

          $ lspci -v | grep VGA
          00:02.0 VGA compatible controller: Intel Corporation Haswell-ULT 
          Integrated Graphics Controller (rev 09) (prog-if 00 [VGA controller])

          $ xdpyinfo | grep -B 2 resolution
             screen #0:
             dimensions:    2560x1600 pixels (677x423 millimeters)
             resolution:    96x96 dots per inch
where the physical dimension of my screen is not correct as I am using a macbook with 13" screen

My machine is a macbook with HiDPI, the screen resolution is 2560x1600, which causes the window and fonts to be too small.  When I tried to scale the gnome's interface to scale 2 (which worked perfectly in Mint 17), the command does not take effect:
          
           sudo gsettings set org.gnome.desktop.interface scaling-factor 2

Using gnome-tweak-tool to set the screen scale does not work neither. Using xrandr only causes blurr effect. 

There are some related bugs I found [here](https://bugzilla.gnome.org/show_bug.cgi?id=763989), and [here](http://askubuntu.com/questions/783250/how-to-adjust-window-decoration-and-font-size-settings-in-xenial)[I have tried all the suggestions in that page], this [one](https://bugs.openjdk.java.net/browse/JDK-8160194) might be loosely related. 

I am not sure if you can help in Cinnamon, hope someone can point me direction to change the scale correctly. Thanks.

**Comment by gbuntu127** [comment]
just want to add that changing the font size scale does not have any effect neither
             
                sudo gsettings set org.gnome.desktop.interface text-scaling-factor 2

**Comment by mtwebster** [comment]
org.**cinnamon**.desktop
