### ISSUE TITLE
Lost milestones

### ISSUE THREAD

**Issue by StexoO** [linuxmint/Cinnamon#5535]
Hi !

I really like Cinnamon, but according to https://github.com/linuxmint/Cinnamon/releases the actual available version is the 3.0.7, so will the versions 2.2 and 2.6 be released one day, according to https://github.com/linuxmint/Cinnamon/milestones ?

:trollface:

**Comment by JosephMcc** [comment]
2.2 and 2.6 were both released. As far as I know we don't use that milestone feature. I'll have to admit I've never even looked at it before.
