### ISSUE TITLE
Don't prompt me to pick a user to login with when there's only one user

### ISSUE THREAD

**Issue by dandv** [linuxmint/Cinnamon#5537]
I've just installed Mint 18 Cinnamon and created a user for myself. There are no other users on my machine.

After booting, Mint prompted me to pick a user to login with, but there's only one user, so that doesn't make sense.

Would it be possible to just prompt for the password of the only one user instead, when logging in?

**Comment by JosephMcc** [comment]
This isn't a Cinnamon issue and belongs probably belongs here: https://github.com/linuxmint/mdm/issues

MDM usually pre-selects the last user when logging in. At least it does here.

**Comment by dandv** [comment]
@JosephMcc: this only happened on the very first login after installing. It doesn't happen after resuming from standby. I haven't tested restarts or logging out.
