### ISSUE TITLE
Inverted slider color for key repeat speed

### ISSUE THREAD

**Issue by dandv** [linuxmint/Cinnamon#5540]
The repeat speed should be colored green from "Slow" to the thumb position, instead of from the thumb position to "Fast".

![image](https://cloud.githubusercontent.com/assets/33569/17572176/06bf02fc-5f08-11e6-9945-2e984a819040.png)

Same issue with the mouse pointer sensitivity:

![image](https://cloud.githubusercontent.com/assets/33569/17578338/866d124e-5f3c-11e6-9520-2c999d90b8ba.png)

**Comment by JosephMcc** [comment]
There is an open issue for this somewhere even though I can't find it at the moment. Regardless this is on our roadmap to fix.

**Comment by JosephMcc** [comment]
This is fixed now in git master.
