### ISSUE TITLE
Ghost grey translucent rectangle after taking screenshot

### ISSUE THREAD

**Issue by dandv** [linuxmint/cinnamon#5541]
After taking a screenshot using Alt+Print Screen (leave `Screenshot` open), I often see a grey translucent rectangle of the window I took a screenshot of:

![Screenshot leftover](https://cloud.githubusercontent.com/assets/33569/17572176/06bf02fc-5f08-11e6-9945-2e984a819040.png)

I've seen this problem in Unity on Ubuntu 16.04 as well.

**Comment by feren** [comment]
I see that bug too, It's most likely a bug to do with `gnome-screenshot` and not something Linux Mint can fix unless they create a fork of it or something like that...

**Comment by dandv** [comment]
This is https://bugs.launchpad.net/ubuntu/+source/gnome-screenshot/+bug/1526082

**Comment by mainmachine** [comment]
Needs to be reported here: https://github.com/GNOME/gnome-screenshot

**Comment by feren** [comment]
@mainmachine They don't have an issues panel... :/

**Comment by dandv** [comment]
https://github.com/GNOME/gnome-screenshot/pull/2

They probably follow [a policy like KDE's](https://github.com/KDE/krusader/pull/1) where you're not supposed to actually *use* GitHub, but just mirror the repo to it. I personally think that's the project shooting itself in the foot. Everyone and their cat is on GitHub, and people quickly run into the [PITA threshold](https://wiki.dandascalescu.com/essays/pita-threshold) when they try contributing elsewhere, so good luck getting new contributors. :-1:

**Comment by mainmachine** [comment]
> shooting itself in the foot

I think Gnome's pretty established at this point. :laughing: 

They've made the decision to develop the way they do, and their methods have produced one of the most popular open source DE's for almost 20 years now...

This should be closed unless someone wants to contribute upstream to the Gnome project - in which case it should be closed.

**Comment by dandv** [comment]
> They've made the decision to develop the way they do, and their methods have produced one of the most popular open source DE's for almost 20 years now...

Those methods worked for the same reason caves worked to keep us dry - because there wasn't anything better at the time.

**Comment by mainmachine** [comment]
Fair point, although I can't say my methods work for everyone, or that any other particular method would work for me. That said, good engineering persists, regardless of the method which produces it.

Here's a great, basic overview of Cinnamon, and it's relation to the Gnome Shell: http://developer.linuxmint.com/projects.html

I know it's basic, and I'm not trolling you - if you consider the roots of Cinnamon, how it kind of piggybacks on Gnome/GTK, the seeming lack of a "center" to report bugs, contribute, etc. will be more clear.

**Comment by icarter09** [comment]
@dandv are you still experiencing this issue?

**Comment by dandv** [comment]
Sorry that I can't test, I'm no longer using Cinnamon.

**Comment by icarter09** [comment]
@dandv no worries and thanks for the update.
