### ISSUE TITLE
Can't easily tell on vs off state in toggle buttons

### ISSUE THREAD

**Issue by dandv** [linuxmint/Cinnamon#5543]
Quick, is this on or off?

![image](https://cloud.githubusercontent.com/assets/33569/17578949/4b890bf8-5f44-11e6-86bf-bab44cf44db4.png)

The UX of toggle switches is a very well researched topic - see [Should a toggle button show its current state or the state to which it will change?](http://ux.stackexchange.com/questions/1318/should-a-toggle-button-show-its-current-state-or-the-state-to-which-it-will-chan/40954#40954) on UX.StackExchange. Also, [Are on/off switches acceptable in desktop UI](http://ux.stackexchange.com/questions/43888/are-on-off-switches-acceptable-in-desktop-ui).

Proposals:

1. Spell out "on" and "off", like in the Networking window: 

  ![Spell out on and off in toggle switch](https://cloud.githubusercontent.com/assets/33569/17579036/68e51f60-5f45-11e6-9489-6b812b2f1821.png)

  This would also resolve the UI/UX inconsistency between the Networking dialog and the apples with the list of wireless networks. Still, it's unclear whether "on" and "off" represent the action, or the state. The UX.SE post goes into detail about that.
2. A design where "on" and "off" are outside the button leaves no room for ambiguity:

  ![Move labels outside the button](https://cloud.githubusercontent.com/assets/33569/17579022/453a2010-5f45-11e6-82b8-4d6febed9f4c.png)

**Comment by JosephMcc** [comment]
We've had this conversation in IRC already. We don't "spell it out" so to speak because those switches are just an image asset and using yes/no completely ignores translations besides English. The switches in the network dialog are supplied by a different toolkit then the ones in Cinnamon menus so we just match them up best we can. As far as I know under non-english translations they show the I/0 thing as well.

**Comment by dandv** [comment]
> We don't "spell it out" so to speak because those switches are just an image asset and using yes/no completely ignores translations besides English.

How do translations deal with the Networking window on/off switch?

  ![Spell out on and off in toggle switch](https://cloud.githubusercontent.com/assets/33569/17579036/68e51f60-5f45-11e6-9489-6b812b2f1821.png)

**Comment by JosephMcc** [comment]
As I noted in the previous post, as far as I know they use the I and O, the same as Cinnamon. Cinnamon supports the same in the cinnamon theme. A US/English and an international style so you can supply both and it will use the correct one based on locale. We just don't bother in our own themes and use the same one regardless.

Depending on the gtk theme the ones you see in places like the network dialog can also be images. It's really up to the theme. What we do in Cinnamon is just match the ones provided by other toolkits that we have no control over for consistency.
