### ISSUE TITLE
Clearly actionable "Same version is available in a software channel"

### ISSUE THREAD

**Issue by dandv** [linuxmint/Cinnamon#5544]
Same version is available in a software channel

You are recommended to install the software from the channel instead.

**Comment by JosephMcc** [comment]
You need to describe what your talking about better if you want this to stay open. As it is I have no idea what you are talking about.

**Comment by dandv** [comment]
This was a mistake, sorry. I never file bugs like this.

FYI, https://wiki.dandascalescu.com/bugs
