### ISSUE TITLE
color calibration affects keyboard lag (really!) 

### ISSUE THREAD

**Issue by iplayfast** [linuxmint/cinnamon#5547]
when running
tail -f .xsession-errors
whenever I get a keyboard lag I also get
(cinnamon-settings-daemon:12052): color-plugin-WARNING **: failed to connect to device: Failed to connect to missing device /org/freedesktop/ColorManager/devices/cups_Samsung_ML_1670_Series

If I go into the color calibrator, the printer is there sometimes, and then disappears.
If it's there it says that the printer is uncalibrated, and using a default gray. (It is a black and white printer)

I don't know what the color calibration is trying to do, since the printer works fine. But it looks like it is missing something and timing out. While it is searching the keyboard is stuck.

Not sure what the fix is, but at least this should give a clue as to one of the lag problems.

**Comment by icarter09** [comment]
@iplayfast are you still experiencing this issue?

**Comment by Vahan86** [comment]
@icarter09, can we close the issue since there is no response from OP?
