### ISSUE TITLE
Explain in the README where to file bugs

### ISSUE THREAD

**Issue by dandv** [linuxmint/Cinnamon#5549]
I've been using Mint on and off and have been trying to help Cinnamon since 2012. I'm a seasoned GitHub contributor, but just an intermediate Linux user. I lack knowledge of Linux internals and components, but I do want to help by providing [high-quality bug reports](https://wiki.dandascalescu.com/bugs), with precise reproduction steps and screenshots.

Unfortunately my overall impression from filing issues here has been rather negative. Quite often, I'm slapped over the wrist and told that the bug doesn't belong here, sometimes [very rudely](https://github.com/linuxmint/Cinnamon/issues/1546#issuecomment-11706144).

While I may have a thick skin and stick around, other users will probably just leave to a friendlier community.

## Proposal

My suggestion is to describe in [the README](https://github.com/linuxmint/Cinnamon/blob/master/README) where to file various bug categories. Note that it's [not always easy to figure out what the source of a bug is](https://github.com/linuxmint/Cinnamon/issues/5545#issuecomment-239210819), even for more experience contributors, so this section would definitely help new users.

**Comment by Piiit** [comment]
I think this is a good idea. The problem on GitHub is that projects are separate. I suggest to create a LinuxMint General Repository for bugreports that aren't easily categorized by non-experts and where we could put issues about Mint that do not belong to a certain project. Or a General Mint documentation project. The current pdf is not really helpful and not complete. Some projects point to this PDF, but are not described there.

**Comment by leigh123linux** [comment]
@ I'm a rude bastard sometimes.

**Comment by leigh123linux** [comment]
@dandv sorry I was rude.

P.S I'm a fedora contributor and nothing to do with mint.

**Comment by JosephMcc** [comment]
> Unfortunately my overall impression from filing issues here has been rather negative. Quite often, I'm slapped over the wrist and told that the bug doesn't belong here

I'm sorry if you've had some negative responses, that shouldn't happen, but in most cases your issue will simply be closed and you will be pointed to the proper place. If you take offense to that I'm not really sure what to say. The response might be terse when closing it but you have to realize how many of them I sometimes am going through.

**Comment by Piiit** [comment]
@JosephMcc I think to help you and produce less wrong or wrongly-placed bug reports good README files per project could be helpful. There some people would already understand where to put reports or could try some beta-testing by their own... without asking developers that are already busy enough with expert stuff :-)

**Comment by dandv** [comment]
Ok, so where so I file a bug with the Cinnamon Spices website? It looks like it doesn't load any stylesheet.

https://cinnamon-spices.linuxmint.com/applets/view/16

![image](https://cloud.githubusercontent.com/assets/33569/17957708/bc76bc34-6a48-11e6-9fd0-04fa385ad5cb.png)

**Comment by JosephMcc** [comment]
@dandv There is no need. This is an already know issue and on our roadmap as something that needs to fixed.

**Comment by JosephMcc** [comment]
Just for general information, this page lists most of the Mint projects along with links to the relevant github pages: http://developer.linuxmint.com/projects.html

**Comment by Vahan86** [comment]
https://github.com/linuxmint/Cinnamon/pull/5640

**Comment by JosephMcc** [comment]
Yes. And some further info on the spices site design: http://segfault.linuxmint.com/2016/09/design-team-working-on-spices-website/
