### ISSUE TITLE
Cinnamon flickers after suspend/resume

### ISSUE THREAD

**Issue by Piiit** [linuxmint/Cinnamon#5550]
This bug is similar to #5293, but not the same. 

Everything works fine, before going into suspend/resume. Then I get screen flickering when I try to switch windows with ALT+TAB or try to open Dropdown-menues or other overlaying artifacts.

The following screen flickering image shows what I mean:
![vlcsnap-2016-08-12-14h51m07s674](https://cloud.githubusercontent.com/assets/6096063/17622749/886e5038-609c-11e6-89c7-11aa7fd18b04.png)

This effect is just a really short time, then it disappears again. I work for some seconds without issues, then flickering starts again for 1 sec....

Maybe this bug is related to mdm, because when I restart mdm, it works again until next suspend/resume.

Please note, that this problem never happened with Linux Mint Cinnamon 17.3...

----
My configuration is as follows:

```
$ cat /usr/share/X11/xorg.conf.d/20-intel.conf
Section "Extensions"
        Option "XVideo" "Disable"
EndSection

Section "Device"
   Identifier  "Intel Graphics"
#Driver  "modesetting"
   Driver      "intel"
   Option      "AccelMethod" "sna"
   Option      "TearFree" "true"
   Option      "DRI" "true"
   # VideoRam 461632   # sometimes (before updating the bios) it is useful
EndSection

$ uname -a
Linux fuchur 4.4.9-040409-generic #201605041832 SMP Wed May 4 22:34:16 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

Linux Mint 18 64bit
Cinnamon 3.0.7

```
$ lspci -v -nn
00:02.0 VGA compatible controller [0300]: Intel Corporation 4th Gen Core Processor Integrated Graphics Controller [8086:0416] (rev 06) (prog-if 00 [VGA controller])
	Subsystem: CLEVO/KAPOK Computer 4th Gen Core Processor Integrated Graphics Controller [1558:5455]
	Flags: bus master, fast devsel, latency 0, IRQ 28
	Memory at f7800000 (64-bit, non-prefetchable) [size=4M]
	Memory at e0000000 (64-bit, prefetchable) [size=256M]
	I/O ports at f000 [size=64]
	Expansion ROM at <unassigned> [disabled]
	Capabilities: <access denied>
	Kernel driver in use: i915
	Kernel modules: i915
```

**Comment by leigh123linux** [comment]
looks like an intel driver issue, restarting mdm restarts X.

**Comment by lestcape** [comment]
Piiit could be related with this: https://github.com/linuxmint/Cinnamon/issues/4747 ?

**Comment by Piiit** [comment]
@JosephMcc It is an intel driver (kernel) issue: Since the last firmware update it works well without any issues.

@lestcape It is not related I think to #4747... Never had any corrupted images or icons.

**Comment by JosephMcc** [comment]
@Piiit I'm going to go ahead and close this. If it's your own issue you can close any time.
