### ISSUE TITLE
Lock screen appears twice after suspend

### ISSUE THREAD

**Issue by rootext** [linuxmint/Cinnamon#5553]
Linux Mint 18 Cinnamon 3.0.7.
Steps to reproduce:
- Wait until session  is suspended
- Unlock session
- Wait 2-5 seconds and session is locked automatically the second time

**Comment by JBYoshi** [comment]
Can reproduce. Same version, with all available updates applied.

**Comment by mainmachine** [comment]
I've seen this before, but since I always install cinnamon on top of some Ubnutu, so just assumed it was a duplicate setting from LXDE or MATE...

**Comment by rootext** [comment]
It hasn't been reproduced in Linux Mint  18.1 with Cinnamon 3.2 since release day.
