### ISSUE TITLE
Cinnamon crashes while Kerbal Space Program starting

### ISSUE THREAD

**Issue by ghost** [linuxmint/Cinnamon#5554]
When I launching a native version of KSP (https://kerbalspaceprogram.com/en/), Cinnamon crashes or goes unusable (windows have no frames, can't close windows, etc).

Hardware: Intel HD graphics 4000, 2 monitors with different resolution.
 Linux Mint 17.3 x64, Cinnamon 2.8.8

console output (replaced then started KSP):

> kirill@RERE-pc ~ $ cinnamon --replace
> Cjs-Message: JS LOG: About to start Cinnamon
> St-Message: cogl npot texture sizes SUPPORTED
> Cjs-Message: JS LOG: Cinnamon started at Sun Aug 14 2016 12:15:37 GMT+0300 (MSK)
> Cjs-Message: JS LOG: network applet: Cannot find connection for active (or connection cannot be read)
> openGL version 3.0 Mesa 10 detected (GL Cogl Driver)
> MetaSyncRing disabled: couldn't find required GL extensions, or the minimum safe openGL version was not met
> Cjs-Message: JS LOG: network applet: Found connection for active
> Window manager warning: Log level 16: Native children wider or taller than 65535 pixels are not supported
> Window manager warning: Log level 6: The program 'cinnamon' received an X Window System error.
> This probably reflects a bug in the program.
> The error was 'BadAlloc (insufficient resources for operation)'.
>   (Details: serial 10714 error_code 11 request_code 12 (core protocol) minor_code 0)
>   (Note to programmers: normally, X errors are reported asynchronously;
>    that is, you will receive the error a while after causing it.
>    To debug your program, run it with the GDK_SYNCHRONIZE environment
>    variable to change this behavior. You can then get a meaningful
>    backtrace from your debugger if you break on the gdk_x_error() function.)
> Trace/breakpoint trap

dmesg:

> [36011.676598] traps: cinnamon[15421] trap int3 ip:7ff747b09c13 sp:7ffe567f67c0 error:0

**Comment by leigh123linux** [comment]
Can you reproduce this issue with any free game? as I doubt any dev will want to pay for some lame game.

**Comment by sleeply4cat** [comment]
No, sorry. Only this game causes this issue, and only in window mode. I can perform some tests if needed.

**Comment by davidson16807** [comment]
>lame game

Boo!

**Comment by clefebvre** [comment]
We believe this issue is fixed. Please test against the latest Cinnamon version (3.6). If the issue happens again, create a new issue and add a stracktrace.
