### ISSUE TITLE
Audio Stutters When Opening Windows Or Switching Workspaces

### ISSUE THREAD

**Issue by SerafDosSantos** [linuxmint/Cinnamon#5555]
![screenshot from 2016-08-14 15-56-35](https://cloud.githubusercontent.com/assets/3285430/17651565/c23e8c64-6237-11e6-839c-0ecf78c2b36e.png)

As the title says; I'm mainly using Rhythmbox.

**Comment by JosephMcc** [comment]
I haven't tried to reproduce this but you have sound effects enabled for things like mapping windows and switching workspaces?

**Comment by SerafDosSantos** [comment]
Oh yes. Might be it. Let me check and see how it behaves for a couple of hours. I switched off some sound effects.

**Comment by SerafDosSantos** [comment]
Yup, it was the sound effects. With some off, the problem disappears.

What might cause the problem of the sound effects making playing audio stutter I don't know though. It appeared a few days ago. I installed and removed a few things, along some updates lately...

Shall we close this issue?

**Comment by JosephMcc** [comment]
Unless I am misunderstanding it makes sense. If you are playing music with Rhythmbox and then open a window or switch workspaces, Cinnamon plays a sound effect. It makes sense that would interfere with your music playing.

If you feel the problem is sorted, then yes, please close the issue.

**Comment by SerafDosSantos** [comment]
But it didn't use to make the music stutter. I usually would hear the sound effects along with/over the music.

Closing.

**Comment by f2404** [comment]
@SerafDosSantos Have you changed or updated anything related to sound system (pulseaudio, alsa) recently?
As I understand, it's a matter of proper sound mixer configuration that allows sounds from different sources to be played simultaneously.
