### ISSUE TITLE
Switch among windows with Super+numbers / Win+1, 2, 3 etc

### ISSUE THREAD

**Issue by dandv** [linuxmint/Cinnamon#5561]
These keyboard shortcut have saved me tons of time over the years, and I find it surprising that such a popular desktop environment like Cinnamon doesn't implement them by default. I have my file manager always open as the first window, my terminal window as #2, IDE as #3, browser as #4.

Assigning manually Win+1/2/3/etc. is a non-starter, because it will always launch a new instance of the app. Some apps might have a "one instance only" option, but that's the exception, and even then, you'll see the flicker of the new instance being launched and then killed.

PS: I've [asked on the forums](https://forums.linuxmint.com/viewtopic.php?f=208&t=227762), and [on Unix&Linux.SE](http://unix.stackexchange.com/questions/303628/switch-among-windows-with-supernumbers-win1-2-3-etc), but no luck.

**Comment by mainmachine** [comment]
I rely on Super+$(type search term), which is one thing that appealed to me about Cinnamon coming from Windows several years back, but I'm not familiar with these key combos - do they open a new instance of the applications you listed, or do they switch between them, like an app specific alt-tab?

**Comment by dandv** [comment]
Super + <search term> means releasing Super.

Super+1 means holding Super while pressing 1. If you switch between the same few apps all the time (e.g. a browser and an IDE or code editor) and have other apps in the background (music player, system monitor and whatnot), you'll wonder how you've ever lived without the ability to instantly switch to any window you want. Alt+Tabbing past the apps you don't want to switch to, takes several times longer.

That keyboard shortcut saves me probably 5 seconds per minute on the average, so ~40 minutes a day.

If you use any apps that have an option to launch only one instance, e.g. [Double Commander](http://doublecmd.sourceforge.net/) as your file manager, you can try out the shortcut already. Unity also implements it.

**Comment by mainmachine** [comment]
This is one reason why I prefer any application that has internal tabbing, so I can manage multiple instances of say a terminal emulator in a single taskbar instance - this keeps alt-tab fairly slim for me, among other benefits. There are also a ton of different options for alt-tab behavior which might be more appealing to you than the traditional alt-tab. I use "Timeline (3D)" which looks quite nice and is very quick to get to what you want to get to (also a native part of Cinnamon).

If you're looking for Windows 7 workflow parity, Cinnamon is about the closest you'll get, KDE is probably second, but you may have to look beyond the defaults.

**Comment by dandv** [comment]
I just want to switch to my file manager with Win+1, my IDE with Win+2, and my todo app with Win+3.

**Comment by dandv** [comment]
Is it possible to create an applet or extension to do this?

**Comment by mainmachine** [comment]
I'm sure it's possible, although as you've seen, the default behavior in cinnamon for a launcher hotkey combo is to launch a new instance of the application if it's already open, rather than switch to an existing instance of the application.

I guess you're trying to keep parity with your workflow from Win 7 (correct me if I'm wrong), but I think what you'll find is there are other workflows which don't exist on that platform that you might like better, for instance, multiple workspaces. I typically have an email client, web browser (or two), and a terminal app open, and additionally skype, file manager, and sometimes word processor, spreadsheet or some other apps open. If I need to run a VM for some application, I switch to the secondary workspace and launch it there, along with a terminal, so the VM/terminal combo is on the second workspace, and my main workspace is the stuff I need to do the majority of my work. Easy ALT+CTRL+L/R arrow to switch between them.

You could bind the Super+1, etc to several workspaces, then have your applications on each of these. There is even a gnome extension to auto open whatever apps were open when you shutdown, although I can't remember what it's called...

**Comment by mainmachine** [comment]
Here's where you would set the Super+X keys to tie to each workspace easily:

![screenshot from 2016-08-22 00-22-34](https://cloud.githubusercontent.com/assets/12385366/17843655/a23ee2d4-67fe-11e6-889d-c2b7aabcc6e8.png)

I know it's not exactly what you're looking for, but it is an alternative you might find useful.

**Comment by dandv** [comment]
> I guess you're trying to keep parity with your workflow from Win 7 (correct me if I'm wrong)

I'm trying to keep parity with my workflow from Unity.

I very much welcome workspaces being a native feature in DEs (vs. Windows, where I used tools like [Virtual Dimension](https://sourceforge.net/projects/virt-dimension/)), and I've been using Ctrl+Alt+arrows to switch among workspaces.

What I want is to switch as quickly as possible among a small set of applications - mainly file manager, text editor, TODO/GTD tool, IDE and maybe browser.

I tried splitting those apps one per workspace, and that worked somewhat. Is there a way to disable the sliding animation when switching among workspaces, [as with Compiz in Ubuntu](http://askubuntu.com/questions/58553/turning-off-the-transition-animation-when-changing-workspaces-in-compiz-gnome2)?

It's a little artificial, still. With one window per workspace, I no longer see the other windows I had open next to it. I use workspaces to switch context, e.g. between coding and answering emails, but copy/pasting a snippet of code from my text editor into the IDE is part of the same context, and so is adding a TODO item while coding.

BTW, [KDE has this feature](http://askubuntu.com/questions/813262/which-desktop-environments-allow-switching-among-windows-with-supernumbers/813575#813575).

**Comment by xenopeek** [comment]
Related issues are #5516, #4557 and #3883.

**Comment by JosephMcc** [comment]
The other issues are close enough to close this as a duplicate.

**Comment by dandv** [comment]
Oddly enough, there are at least two applets that claim to do this, and an entire [thread on the forum](https://forums.linuxmint.com/viewtopic.php?f=90&t=214043&p=1116679&hilit=keyboard+shortcut+applet#p1116679). I'm surprised nobody has suggested them so far.

1. [Window List with App Grouping](https://cinnamon-spices.linuxmint.com/applets/view/16) - [doesn't handle unpinning though](https://github.com/jake-phy/WindowIconList/issues/147)
2. [Window List with Hotkey](https://cinnamon-spices.linuxmint.com/applets/view/217) - [newly broken apparently](https://github.com/HenryNugraha/Window-List-Hotkey/issues/2)

**Comment by mainmachine** [comment]
> It's a little artificial, still. With one window per workspace, I no longer see the other windows I had open next to it. I use workspaces to switch context, e.g. between coding and answering emails, but copy/pasting a snippet of code from my text editor into the IDE is part of the same context, and so is adding a TODO item while coding.

My solution to this is to use the "Always on Visible Workspace" option from the windows header right click menu. 

AFAIK extensions and applets are written in JS for Cinnamon, so if you know JS, then you could look at making this functionality, or contributing to one of these applets that *almost* does what you want - or fork it and do that...

**Comment by dandv** [comment]
I've just posted a [$100 bounty](https://github.com/linuxmint/Cinnamon/issues/3883#issuecomment-243874387) to have this issue solved.

**Comment by dandv** [comment]
> AFAIK extensions and applets are written in JS for Cinnamon, so if you know JS

I know JS, but I think the code is way too complicated, [over 1300 lines](https://github.com/HenryNugraha/Window-List-Hotkey/blob/master/Window-List-Hotkey%40HenryNugraha/applet.js) to assign shortcuts to windows?!

**Comment by mainmachine** [comment]
How many lines should it take? :wink: 

Honestly, having never delved into the code of a DE I wouldn't know how complex it would be, but I would not be surprised if there's a lot in there you wouldn't expect on the outset.

The [Sane Menu](https://github.com/nooulaif/cinnamon-sane-menu/blob/master/applet.js) replacement is 2775 lines - is that to much or to little? Without delving into the code, I couldn't judge whether it's efficiently coded or not, or if there are features and provisions that aren't obvious bby what I expect it to do.

**Comment by ChrisAntaki** [comment]
@dandv I found a partial solution. If you install the "wmctrl" program, you can use it to switch to already opened programs. For instance, `wmctrl -x -a "Chrome"` gives focus to Chrome, and `wmctrl -x -a "Terminal"` gives focus to the Terminal. After finding these working commands, I assigned them to Keyboard Shortcuts. An image of the shortcuts screen is attached. Hope this helps!

![screenshot from 2017-05-03 10 48 50](https://cloud.githubusercontent.com/assets/1216762/25674074/7c7aa5a2-2fee-11e7-9170-e234af4c7047.png)

**Comment by ChrisAntaki** [comment]
You can also open the program as a fallback, if switching to it fails. For example: `wmctrl -x -a "Terminal" || gnome-terminal`

**Comment by ChrisAntaki** [comment]
If you'd like to switch to the program, or open the program if it wasn't already, the solution is a bit more involved.
1) Create an executable `.sh` file that contains an expression like `wmctrl -x -a "Terminal" || gnome-terminal`.
2) Create a Keyboard Shortcut and set its command to the `.sh` file's absolute path.

**Comment by nirrub** [comment]
You can map Super + Num with the use of this thing:
https://github.com/mkropat/jumpapp
So you can do something like map Super + 1 to "jumpapp nemo" so that it either raises the file manager window or launches it if it's closed.

**Comment by xueeinstein** [comment]
My solution is to use customized tools [run-or-raise](https://github.com/xueeinstein/dotfiles/blob/master/bin/run-or-raise) and [switch-windows](https://github.com/xueeinstein/dotfiles/blob/master/bin/switch-windows). 

__run-or-raise__ either active the already opened application window or directly open a new application session if it doesn't open yet. 

__switch-windows__ support to switch windows using shortcuts like `Super + k` and `Super + j` in the Awesome window manager.

![screenshot from 2018-05-13 11-08-54](https://user-images.githubusercontent.com/3424201/39963460-099945a2-569e-11e8-8f73-14c44bb94f4b.png)

**Comment by xdavidliu** [comment]
> My solution is to use customized tools [run-or-raise](https://github.com/xueeinstein/dotfiles/blob/master/bin/run-or-raise) and [switch-windows](https://github.com/xueeinstein/dotfiles/blob/master/bin/switch-windows).
> 
> **run-or-raise** either active the already opened application window or directly open a new application session if it doesn't open yet.
> 
> **switch-windows** support to switch windows using shortcuts like `Super + k` and `Super + j` in the Awesome window manager.
> 
> ![screenshot from 2018-05-13 11-08-54](https://user-images.githubusercontent.com/3424201/39963460-099945a2-569e-11e8-8f73-14c44bb94f4b.png)

This works perfectly.

**Comment by smurphos** [comment]
Grouped Window List in Cinnamon 4.x has native support for this with pinned applications.

**Comment by nof8** [comment]
Seems like it was broken in Linux Mint 19.3 :(

**Comment by agalitsyn** [comment]
I confirm, updated to 19.3 yesterday and it no longer working

**Comment by frostfred** [comment]
Yep, 19.3 broke this hotkeys

**Comment by xenopeek** [comment]
Locking this issue as #9028 is opened for this on 19.3.
