### ISSUE TITLE
What's the blessed/official wiki?

### ISSUE THREAD

**Issue by dandv** [linuxmint/Cinnamon#5563]
https://community.linuxmint.com/idea/view/79 is now down (see below) but IIRC, the old wiki was closed.

Should we use the wiki here on GitHub? I'm looking for / to contribute to articles like "List of differences between Cinnamon and Unity".

![image](https://cloud.githubusercontent.com/assets/33569/17728425/03314e72-6414-11e6-96c7-57d0adf3de44.png)

**Comment by DirkHaar** [comment]
+1
We need a Wiki, definitely. At least for promotion reasons, but also to get our things done (and don't let archwiki and ubuntuusers do it; the German site already denies any entries about Mint and archives them).

**Comment by clefebvre** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.

**Comment by dandv** [comment]
> Your suggestion was reviewed.

I'm curious what the result of the review was.
