### ISSUE TITLE
cinnamon-json-makepot -j / -js parameter discrepancy

### ISSUE THREAD

**Issue by ncelerier** [linuxmint/Cinnamon#5567]
Hello, 

There is a minor problem with cinnamon-json-makepot.py about the -j / -js / --js parameter.

The usage says that you can use either -js or --js:

```
Usage:

cinnamon-json-makepot -i | -r | [-js] <potfile name>

-js, --js - Runs xgettext on any javascript files in your directory before [...]
```

And then an option on the parser is added:
`
parser.add_option("-j", "--js", action="store_true", dest="js", default=False)
`

You can see that there is a discrepancy between usage (says you can use -js) and the parser option (says you can use -j). 

Indeed, running:
`
cinnamon-json-makepot -js fileName
`

Will display the usage and this line: 
`
cinnamon-json-makepot.py: error: no such option: -s
`

This should be fixed. The problem is that some scripts are already using the "wrong' -j option. 
1. Does the script need to handle -j and -js as well ? 
   Pros: Backward compatible with existing scripts. 
   Cons: Two parameters have the same purpose.
2. Does the script need to handle only -js, the correct option ?
   Pro: Only one parameter for a given purpose.
   Cons: Scripts need to be adapted.
3. Does the script need to handle only -j ? 
   Pro: Backward compatible with existing scripts.
   Cons: None ?

I feel like proposal 3 is the best. What do you think ?

**Comment by NikoKrause** [comment]
I think it's just a typo, i.e. it has to be `-j` or `--js`

**Comment by collinss** [comment]
This is indeed a typo in the usage text. However, once https://github.com/linuxmint/Cinnamon/pull/7149 is merged, it wont be an issue anymore. The cinnamon-json-makepot will be replaced by the more aptly named cinnamon-xlet-makepot. The usage information will be auto-generated (so no typo). The usage of the -j option will be reversed (the default is now to scan all .js files).

Note: cinnamon-json-makepot can still be called (so as not to break existing scripts that call it), but it will now merely be a wrapper around cinnamon-xlet-makepot. The new script will also scan python files by default if they exist (this behavior can be disabled similar to the scanning of javascript files).
