### ISSUE TITLE
No system sound [LinuxMint 18 x64 / Cinnamon 3.0.7]

### ISSUE THREAD

**Issue by f3l1x** [linuxmint/Cinnamon#5568]
Hi. I have a problem with system sounds.

```
Device: Dell XPS L521X
Host: XPS-L521X Kernel: 4.5.4-040504-generic x86_64 (64 bit)
Desktop: Cinnamon 3.0.7  Distro: Linux Mint 18 Sarah
```

No sound on startup, no sound on workspace switch etc.

![sound_001](https://cloud.githubusercontent.com/assets/538058/17792404/cb7d7486-65a0-11e6-896e-61035b220dec.png)

It's default settings, but not sound came out.  Youtube is working, also VLC etc. But no system sounds.

Have you guys any ideas how to fix it? Thank you.

**Comment by xenopeek** [comment]
Can you try creating a new user account, logging in to that, and retesting if the problem also occurs there? To determine if this is a system-wide issue or only a problem with your own user account.

**Comment by uaflyer** [comment]
Might not be related, but I have similar issue on a Dell desktop with an Intel sound card.
Created test account, no joy

**Comment by xenopeek** [comment]
@uaflyer so sound works, it's just the Cinnamon system sounds that aren't audible?

**Comment by f3l1x** [comment]
@xenopeek No cinnamon system sound. Create a new test account didn't help. 

Maybe there might be a problem. I had a previous version 17.3 or what and I've used a update script to migrate to 18. It wasn't a clean installation.

**Comment by uaflyer** [comment]
@xenopeek No sound at all and this was a clean install.  I don't feel like blowing it up again, but may need to do that

**Comment by uaflyer** [comment]
I finally figured it out using more than one machine.  (this might seem like stupid stuff )
1) During install, you must check the install proprietary drivers.  I found I would get no sound support anywhere without it

2) If you find the sound works in other profiles, delete the alsa directory in your home folder (hidden)  You can logout and it will work upon login.

I did at least a dozen rebuilds over the weekend for several reasons.  I did both upgrades of 17.3 and scratch installs.  Once I noticed that sound works in Mate and not Cinnamon, I tracked it down to the bad alsa profile in home.  Again, without the proprietary drivers in use, (maybe it doesn't use them, it just triggers something else that helps) I could not get any sound on and Intel card.  Hope this helps some folks )

**Comment by E3V3A** [comment]
I can confirm this weird issue! 

Although I'm running on Virtualbox, the login sound plays right after login, but after that, the sound is totally dead. Here are the relevant outputs:

```bash
# lspci

00:05.0 Multimedia audio controller: Intel Corporation 82801AA AC'97 Audio Controller (rev 01)
```

```bash
# aplay -l

**** List of PLAYBACK Hardware Devices ****
card 0: I82801AAICH [Intel 82801AA-ICH], device 0: Intel ICH [Intel 82801AA-ICH]
  Subdevices: 0/1
  Subdevice #0: subdevice #0

# aplay -L

default
    Playback/recording through the PulseAudio sound server
null
    Discard all samples (playback) or generate zero samples (capture)
pulse
    PulseAudio Sound Server
sysdefault:CARD=I82801AAICH
    Intel 82801AA-ICH, Intel 82801AA-ICH
    Default Audio Device
front:CARD=I82801AAICH,DEV=0
    Intel 82801AA-ICH, Intel 82801AA-ICH
    Front speakers
surround21:CARD=I82801AAICH,DEV=0
    Intel 82801AA-ICH, Intel 82801AA-ICH
    2.1 Surround output to Front and Subwoofer speakers
surround40:CARD=I82801AAICH,DEV=0
    Intel 82801AA-ICH, Intel 82801AA-ICH
    4.0 Surround output to Front and Rear speakers
surround41:CARD=I82801AAICH,DEV=0
    Intel 82801AA-ICH, Intel 82801AA-ICH
    4.1 Surround output to Front, Rear and Subwoofer speakers
surround50:CARD=I82801AAICH,DEV=0
    Intel 82801AA-ICH, Intel 82801AA-ICH
    5.0 Surround output to Front, Center and Rear speakers
surround51:CARD=I82801AAICH,DEV=0
    Intel 82801AA-ICH, Intel 82801AA-ICH
    5.1 Surround output to Front, Center, Rear and Subwoofer speakers
iec958:CARD=I82801AAICH,DEV=0
    Intel 82801AA-ICH, Intel 82801AA-ICH
    IEC958 (S/PDIF) Digital Audio Output
dmix:CARD=I82801AAICH,DEV=0
    Intel 82801AA-ICH, Intel 82801AA-ICH
    Direct sample mixing device
dsnoop:CARD=I82801AAICH,DEV=0
    Intel 82801AA-ICH, Intel 82801AA-ICH
    Direct sample snooping device
hw:CARD=I82801AAICH,DEV=0
    Intel 82801AA-ICH, Intel 82801AA-ICH
    Direct hardware device without any conversions
plughw:CARD=I82801AAICH,DEV=0
    Intel 82801AA-ICH, Intel 82801AA-ICH
    Hardware device with all software conversions
```

I've also installed `pavucontrol` and `mpg123` player to help, but nothing comes out. 

There are also some `pulseaudio` files here: 
```bash
# ls -1 /etc/pulse/

client.conf
daemon.conf
default.pa
system.pa
```
Tried edit some according to various older solutions, but that didn't help either.

@uaflyer Where was your alsa profile? I don't seem to have one., so I wonder if you did, what it was called, because it probably override one of the system ones:
```bash
# find /etc/ -iname "*alsa*"

/etc/modprobe.d/alsa-base.conf
/etc/init/alsa-utils.conf
/etc/default/alsa
/etc/rc6.d/K01alsa-utils
/etc/init.d/alsa-utils
/etc/rc1.d/K01alsa-utils
/etc/apm/scripts.d/alsa
/etc/apm/suspend.d/80alsa
/etc/apm/resume.d/20alsa
/etc/rcS.d/S02alsa-utils
/etc/rc0.d/K01alsa-utils
```

So, audio is working right after bootup/login, but not after... So perhaps it is some system service that starts after. How to test? Any suggestions?

**Comment by E3V3A** [comment]
This is the relevant log immediately after login. As you can see, before logging out the system tried to play the logout sound as well. (But this was never heard.)

```
# cat /var/log/syslog

Nov 22 10:26:52 xxxx cinnamon-session[1683]: WARNING: t+1718.58202s: Playing logout sound '/usr/share/mint-artwork-cinnamon/sounds/logout.ogg'
Nov 22 10:27:22 xxxx cinnamon-session[1683]: WARNING: t+1748.60755s: Finished playing logout sound

Nov 22 10:27:58 xxxx cinnamon-session[3172]: WARNING: t+22.13230s: Playing logout sound '/usr/share/mint-artwork-cinnamon/sounds/logout.ogg'
Nov 22 10:28:28 xxxx cinnamon-session[3172]: WARNING: t+52.16779s: Finished playing logout sound
...
Nov 22 10:28:37 xxxx systemd[1]: Reached target Sound Card.
...
Nov 22 10:28:58 xxxx pulseaudio[1993]: [pulseaudio] alsa-util.c: Disabling timer-based scheduling because running inside a VM.
Nov 22 10:28:58 xxxx pulseaudio[1993]: [pulseaudio] sink.c: Default and alternate sample rates are the same.
...
Nov 22 10:28:58 xxxx org.gtk.vfs.AfcVolumeMonitor[1951]: Volume monitor alive
...
Nov 22 10:28:59 xxxx cinnamon-killer-daemon: Bound Cinnamon restart to <Control><Alt>Escape.
Nov 22 10:29:01 xxxx pulseaudio[1993]: [alsa-sink-Intel ICH] alsa-sink.c: ALSA woke us up to write new data to the device, but there was actually nothing to write.
Nov 22 10:29:01 xxxx pulseaudio[1993]: [alsa-sink-Intel ICH] alsa-sink.c: Most likely this is a bug in the ALSA driver 'snd_intel8x0'. Please report this issue to the ALSA developers.
Nov 22 10:29:01 xxxx pulseaudio[1993]: [alsa-sink-Intel ICH] alsa-sink.c: We were woken up with POLLOUT set -- however a subsequent snd_pcm_avail() returned 0 or another value < min_avail.
...
Nov 22 10:29:23 xxxx pulseaudio[1993]: [pulseaudio] bluez5-util.c: GetManagedObjects() failed: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
```

**Comment by E3V3A** [comment]
and:
```bash
# inxi -Fxz
...
Audio:     Card Intel 82801AA AC'97 Audio Controller driver: snd_intel8x0 ports: d100 d200 bus-ID: 00:05.0
           Sound: Advanced Linux Sound Architecture v: k4.4.0-47-generic
```

**Comment by E3V3A** [comment]
For any *VirtualBox* users: 

I bypassed the sound problem described above, by *not* using the AC97 Controller, and instead use the _Intel HD Audio_  in VB.

However, the original problem why AC97 sound works on login and not later is not resolved. There is a suspicion of an error in the file: `/etc/modprobe.d/alsa-base.conf`.
```
# Is this a spelling error? Perhaps it should be:  "intel8x0" (without "m").
options snd-intel8x0m index=-2
```

**Comment by gcjuan** [comment]
`sudo apt install libcanberra-pulse` solves it in my case (this library controls system sound in Linux Mint)

**Comment by f3l1x** [comment]
I think we can close it now. Do you agree guys?

**Comment by E3V3A** [comment]
Can someone please check my previous post, if that is still true (wrong option in `alsa-base.conf`)?

**Comment by clefebvre** [comment]
https://github.com/linuxmint/Cinnamon/commit/fb0b7e4ea2e3c3af52243f405772aa6718b2e876

**Comment by ALTracer** [comment]
Installed Linux Mint 19 Cinnamon on a Core i5-4440 machine (ASUSTeK Z87M-PLUS), Pulseaudio mixer shows only IEC958. 
````
$ grep snd-intel /etc/modprobe.d/alsa-base.conf
options snd-intel8x0m index=-2
$ modinfo snd-intel8x0m
...modemcard
$ modinfo snd-intel8x0
 ...soundcard
````
Are you sure we modprobe the right driver?

**Comment by E3V3A** [comment]
...I'm pretty sure we modprobe wrong driver.
