### ISSUE TITLE
Issue with change of the theme when use Accessibility -> Visual Aids -> "High contrast" option

### ISSUE THREAD

**Issue by Vahan86** [linuxmint/Cinnamon#5571]
To reproduce the issue do the following:

1. Choose the theme other than Mint X, for instance Mint Y.

![1](https://cloud.githubusercontent.com/assets/12819058/17810541/dabfc9ec-662e-11e6-94cd-14508ada7d12.png)

2. Go to System Settings -> Accessibility -> Visual -> Visual Aids and enable the "High contrast" option

![2](https://cloud.githubusercontent.com/assets/12819058/17810504/97672d48-662e-11e6-9735-14b176344d0f.png)

3. After appropriate changes disable the option.
4. The system changes the theme to Mint X, even if before the theme was Mint Y.
5. After changing the theme to Mint X, in System Settings -> Themes window it still shows Mint Y as a chosen theme.

![3](https://cloud.githubusercontent.com/assets/12819058/17810513/acbdae6a-662e-11e6-8147-d26fdc9aba99.png)

After enabling and disabling the High Contrast option, it should change back the current theme which was chosen before (in our case Mint Y).

**Comment by Vahan86** [comment]
@JosephMcc, duplicate of https://github.com/linuxmint/Cinnamon/issues/2533

**Comment by JosephMcc** [comment]
@Vahan86 since this is your own issue, you have the ability to close it.
