### ISSUE TITLE
"Input Method" and "Languages" sections should be opened in parent window.

### ISSUE THREAD

**Issue by Vahan86** [linuxmint/Cinnamon#5572]
The most sections of System Settings are opened in main (parent) window. But "Input Method" and "Languages" sections are opened in new window.

It would be nice if these two sections also will be opened in the main window to keep the same "behavior" for all sections of System Settings.

**Comment by JosephMcc** [comment]
This has been discussed before. Everyone agrees this would be nice but there are technical reasons why it isn't the case. Those two items are external applications that are actually shared among the different desktop environments supported on Linux Mint. They aren't actually a part of the cinnamon settings code base.
