### ISSUE TITLE
Tray icons stop updating once they get hidden

### ISSUE THREAD

**Issue by Feuerfuchs** [linuxmint/cinnamon#5573]
I recently created a successor to the popular applet "System Tray Collapsible" since it hasn't been updated for 2 years now. While working on the functionality that lets the user hide certain icons, I came across one problem that has turned out to be a major headache: As soon as I hide tray icons, they stop updating. It doesn't even matter how I achieve that – it happens if I call hide(), set the actor's width to 0, or even if I remove it from its parent actor.

Fortunately, I found a way to hide icons without them stopping updating, but I don't like that solution at all because it's rather nasty. Here's the code: https://github.com/Feuerfuchs/Collapsible-Systray-Cinnamon-Applet/blob/f04012dbcbd4f71edba7b82ad718ddba2bb34db5/collapsible-systray%40feuerfuchs.eu/applet.js#L695-L719

So there are three methods that work: 
- For icons that never change: Remove the icon from its parent and re-add it if the user expands the tray.
- For ones that do change: Hide the associated GtkWindow that actually displays the icon and show it if the user expands the tray. Some icons don't like that method at all, such as Chromium (which turns into a quarter disk or vanishes completely).
- For our special snowflake, Pidgin: Same as 2, but the GtkWindow only must become visible if the expand animation has already finished, or else it stops updating

**Comment by Feuerfuchs** [comment]
I just noticed something. The file /src/cinnamon-embedded-window.c contains a comment about a problem with Clutter. The [respective file in the Gnome Shell repository](https://github.com/GNOME/gnome-shell/blob/master/src/shell-embedded-window.c) had the same comment, but then [a commit was made that removes workarounds](https://github.com/GNOME/gnome-shell/commit/d212d574669ef842cb39a0a0f7a7fa066656528c) for said problem as it had been fixed.
So since these now unnecessary workarounds are still present in Cinnamon, isn't it possible that they are the reason for the strange behavior of tray icons?

**Comment by JosephMcc** [comment]
You could try the change from gnome shell then rebuild and test.

**Comment by Feuerfuchs** [comment]
I absolutely would if I didn't have exams currently, sorry. :/ But I have absolutely zero experience working on Cinnamon itself and my computer isn't set up properly.

**Comment by Feuerfuchs** [comment]
So I took a look at the instructions about how to build Cinnamon, and it was way easier than I thought. I tried if the above change fixes the issue — it doesn't.

**Comment by lestcape** [comment]
In cinnamon_gtk_embed_get_preferred_width and cinnamon_gtk_embed_get_preferred_height:

https://github.com/linuxmint/Cinnamon/blob/master/src/cinnamon-gtk-embed.c#L129
https://github.com/linuxmint/Cinnamon/blob/master/src/cinnamon-gtk-embed.c#L150

The gtk embed actors are set to height=0 and width=0 is they are not visible and this will occurs in an allocation only. So if actors are hidden when they are allocate in the stage, they will set at size 0,0. Then, when they are show, probably is not called a re-layout, and then the icons will continuously with the size 0,0 and that' s mean hidden from the user. This also is probably relate with some problems on the cinnamon status icons support and the impossibility of do anything without call a re-layout.

**Comment by lestcape** [comment]
@Feuerfuchs ande yes, they change the things to call a reallocation when actors are mapped and unmapped. An actors are mapped when they are in the stage and they are visible, so this gnome shell path will fix the problem i think.

**Comment by icarter09** [comment]
@Feuerfuchs are you still experiencing this issue?

**Comment by Vahan86** [comment]
@icarter09, can we close the issue?
