### ISSUE TITLE
some panel applet icons don't scale correctly when switching hidpi mode

### ISSUE THREAD

**Issue by danboid** [linuxmint/cinnamon#5574]
I'm running Cinnamon 3.0.7 under Mint 18. When I switch hidpi mode from single to double (or vice versa), the panel applet icons for the update manager and the bluetooth applet don't get scaled correctly. Instead they are cropped so the full icon isn't displayed. The workaround is to restart cinnamon from the troubleshoot menu but if thats the only way to fix this then the restart should be done automatically when the user switches hidpi mode.

**Comment by Vahan86** [comment]
@danboid, is this still an issue for you in Cinnamon 3.6?

**Comment by Vahan86** [comment]
@JosephMcc, can we close this issue since there is no response from OP for a long time?

**Comment by Vahan86** [comment]
@icarter09, can we close this issue?
