### ISSUE TITLE
Disappears horisontal panel

### ISSUE THREAD

**Issue by Da4HuK** [linuxmint/Cinnamon#5575]
I use Cinnamon 3.0.7
If move panel to left side and than move it back to donw, after it panel disappears.
Only menu icon is vissible. See screenshot.
![pannel desappers](https://cloud.githubusercontent.com/assets/3855068/17832115/fc5d76d2-6703-11e6-9487-81faec793276.png)
Sometimes I observe issue after move pannel to left or right side.

To recover visibility of panel swtitch panel to auto hide mode and switch it always show panel.

**Comment by NikoKrause** [comment]
Moving horizontal/vertical panels has improved since 3.0.7.
I haven't seen this behaviour and I have moved panels a lot.
If you can reproduce it still in Cinnamon 3.6.7 let us know how to reproduce it, this issue will then be reopened
