### ISSUE TITLE
Menu Applet: Allow the user to make it use the theme's menu.png file if that exists in the theme

### ISSUE THREAD

**Issue by feren** [linuxmint/Cinnamon#5576]
Pretty much what it says on the title, if I use any Cinnamon theme on a Cinnamon for Ubuntu PPA, you can use the theme's menu icon if you disable 'Use Custom Icon' whilst if you do the same in Linux Mint, it just gives you the Linux Mint icon regardless of theme... Would be nice for it to use the theme's menu.png file is there is a menu.png file in the theme folder...

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
