### ISSUE TITLE
Tray icon highlight biggest than vertical panel width

### ISSUE THREAD

**Issue by Da4HuK** [linuxmint/Cinnamon#5577]
After move panel to rigth side I observe that tray icon highlight biggest than vertical panel width. Aee screenshot: 
![tray icons hightlight](https://cloud.githubusercontent.com/assets/3855068/17832166/444de1d8-6705-11e6-86c7-1a584fb68cf4.png)

To recover hidhlighting swtitch panel to auto hide mode and switch it always show panel.

**Comment by feren** [comment]
How did you get the panel on the right?

**Comment by JosephMcc** [comment]
Vertical panels are now supported in git master Cinnamon.

**Comment by feren** [comment]
Oh ok

**Comment by JosephMcc** [comment]
According to your screenshot you are running git cinnamon in Mint17.3. Is that the case? If so, Cinnamon 3.0+ is not supported in Mint versions earlier than 18.

**Comment by feren** [comment]
@JosephMcc When would this version of Cinnamon hit Romeo?

**Comment by JosephMcc** [comment]
The only way to really get these before the Cinnamon 3.2 release is to use the cinnamon nightly builds ppa on Mint or build yourself from github. Beware that you are using a development branch in that case and things can break.

**Comment by feren** [comment]
> nightly builds ppa on Mint

Where would that PPA be, I've tried Romeo, but haven't got any updates?

**Comment by Da4HuK** [comment]
Yes, this is Mint 17.3
I install cinnamon from nightly build.
Can you send me link with Cinnamon compatibility information?

**Comment by feren** [comment]
@Da4HuK 
BTW, if you want to upgrade to 18, just look at the Linux Mint Blog on the How To Upgrade To Linux Mint 18 article...

**Comment by Da4HuK** [comment]
No thanks :)
Unfortunately currently Mint 18 is  unstable :(

**Comment by JosephMcc** [comment]
Well so is the cinnamon nightly build.

**Comment by feren** [comment]
@Da4HuK 
1. Your running it in a VM so it shouldn't make too much of a difference to Windows 7
2. Like @JosephMcc said, SO ARE NIGHTLY BUILDS...

**Comment by JosephMcc** [comment]
Quick follow up. You need to run a version of the Linux Mint cinnamon theme that is updated for the vertical panels. You can build it from here: https://github.com/linuxmint/cinnamon-themes
