### ISSUE TITLE
Spacing issue on Vertical Panels

### ISSUE THREAD

**Issue by feren** [linuxmint/Cinnamon#5583]
Basically, it's a bit hard to describe, basically, the applets are too close to each other on vertical panels unlike horizontal ones, e.g: Horizontal:
![screenshot from 2016-08-20 19-18-32](https://cloud.githubusercontent.com/assets/11057934/17833379/ef99eb18-670a-11e6-85cd-f2dbe40b8690.png)
...and then Vertical:
![screenshot from 2016-08-20 19-20-17](https://cloud.githubusercontent.com/assets/11057934/17833390/257786b4-670b-11e6-87f4-f641de1646a8.png)

**Comment by JosephMcc** [comment]
This is a theme problem. Vertical panels have been in Cinnamon for like 3 days. It will take time.
