### ISSUE TITLE
Floating and minimum-sized panels

### ISSUE THREAD

**Issue by feren** [linuxmint/Cinnamon#5585]
It would be cool to have an option (like in KDE) to resize the panel to the minimum width of the panel and also possibly make it float in a way that'd then mean the panel would be slightly away from the screen side it's on (e.g: If it was on the bottom, then allow it to be spaced from the bottom of the screen itself to give it that illusion of floating on the screen (similar to RocketDock's (either that dock or Nexus dock (I think that's what its called (they're both for Windows though)) Spacing option where it's slightly away from where it's connected to))

**Comment by Sunderland93** [comment]
Yeah, that's be cool!

**Comment by lestcape** [comment]
1-Resize the panel to the minimum width of the panel: Is a clear request. +1 for the request.

2-Float the panel anywhere you want it to on the screen: This is not a clear request, because the panels have priority over windows and also they are used to define how the windows are maximized. Do you want something like desklets but with an inverted deep relative to de windows? Anyway, if this is the case, -1 for it.

**Comment by feren** [comment]
@lestcape _I was thinking kinda like KDE where you can move the panel on any part of the screen part it's connected to (and possibly even make it move away slightly from the screen itself which could then give way for theme designs such as round corners on all four corners of the panel, etc)_ (I'll make it clearer in the first comment), also, about the windows, can't you do something like intellihide when a window is maximized and the panel is not actually fully connected to the screen (has a space between it and the side of the screen you put the panel (as an option))?

Though, you just gave me an idea, could applets possibly be desklets similar to how they can be on KDE? There again, something like that can be discussed about in another issue...

**Comment by feren** [comment]
This is what I mean about it 'floating', notice how it's given that screen edge, but it's not actually connected to that screen edge but is seperated slightly?
![image](https://cloud.githubusercontent.com/assets/11057934/17861916/852f6572-6882-11e6-81c0-1027d8f41a42.png)

**Comment by feren** [comment]
Of course, Suggestion No 2 in this doesn't actually HAVE to be in Cinnamon, but would be nice to have nonetheless and may possibly set Cinnamon apart feature-wise compared to other DEs which I don't think have that feature...

**Comment by lestcape** [comment]
@feren yes, but i don't see the utility of the floating panels. In my personal opinion this just will be annoying. If this will be an easy thing i don't see a problem as will be optional, but this feature involves several things. Redefine the panels involve change the interaction with the layout manager. So, i think that the utility of this, need to justify the change, if you want to be take seriously. Actually, i don't see how this will help, but maybe you can see how. I don't think that will be a good reason say: "others  won't have it". I think this is a rason to not do it (i.e: several people think that this is not necessary).

**Comment by lestcape** [comment]
Other thing that you mention, could be, as for example:
1- A little separation of the panel (I don't like that, because reduce my desktop space, but is not difficult as move the panel where you want).
2-
 - Applets that have the desklets ability’s: https://cinnamon-spices.linuxmint.com/applets/view/194
 - Desklets that also have Applets ability’s: https://cinnamon-spices.linuxmint.com/desklets/view/18
 - Desklets that can converted on an Applets or again to a Desklets: https://cinnamon-spices.linuxmint.com/desklets/view/12

**Comment by JosephMcc** [comment]
I wouldn't hold my breath on getting floating panels implemented. That sort of functionality is what desklets are for and they are designed for this purpose unlike the panels.

In reality if you want a dock like panel, the way you show in your screenshot, why not just use a dock? You could also likely do this by way of a cinnamon extension if you really wanted it.

**Comment by lestcape** [comment]
I agree with @JosephMcc but, if i will include something in cinnamon relate with a Desklet ability i will add the @collinss idea of Raise Desklets: https://github.com/collinss/Cinnamon-Soundbox/blob/master/2.8/desklet.js#L128

**Comment by feren** [comment]
@lestcape Like I said earlier, it doesn't matter that much if it didn't get included in Cinnamon, it was just simply a feature idea like KDE's minimal panel size that would be nifty to then see...

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.

**Comment by Lisoveliy** [comment]
Has this feature already been implemented or is it planned?
