### ISSUE TITLE
cinnamon-settings and adwaita.xml failed

### ISSUE THREAD

**Issue by cronolio** [linuxmint/cinnamon#5586]
os: gentoo 
cinnamon 3.0.7
gentoo use [patch](https://gitweb.gentoo.org/repo/gentoo.git/tree/gnome-extra/cinnamon/files/cinnamon-2.8.0-background.patch)

when i run cinnamon-settings
Loading Backgrounds module
Failed to read filename from /usr/share/backgrounds/gnome/adwaita-timed.xml: list index out of range
Failed to detect mimetype for None: execv() arg 2 must contain only strings

yes. i'm was reproduce it on cinnamon distro: install gnome-backgrounds and drop adwaita.xml into /usr/share/cinnamon-background-properties. looks like [cs_backgrounds.py](https://github.com/linuxmint/Cinnamon/blob/master/files/usr/share/cinnamon/cinnamon-settings/modules/cs_backgrounds.py) was trying work with xml as with regular image file

**Comment by werfu** [comment]
Cinnamon 3.0.7 here on Arch though, same issue happening. My desktop background is also corrupted but the selected wallpaper do get displayed correctly on the lock screen though.

**Comment by marc2377** [comment]
Same issue here with Cinnamon 3.2.4, 3.4.1 and bleeding-edge git version as well. Currently working with Nemo 3.4.2 on Arch Linux 64 bits.

**Comment by sparkasaurusRex** [comment]
My fix was to change `cs_backgrounds.py` line `773` to 
```
if len(staticNode) > 0 and staticNode[-1].tag == "size":
```
Before the change, there were no Adwaita backgrounds at all within cinnamon-settings/backgrounds. Now the background shows up and works as expected.

**Comment by mammo0** [comment]
@sparkasaurusRex thanks for this fix!

**Comment by ranolfi** [comment]
@icarter09, will this fix be implemented in the source code?

**Comment by icarter09** [comment]
@ranolfi thanks for the update because I thought it was already implemented. I take it you are still having this issue?

**Comment by ranolfi** [comment]
I am indeed, @icarter09. This has not been pulled into the main repo.

**Comment by icarter09** [comment]
@ranolfi feel free to put a PR together containing this fix

**Comment by ranolfi** [comment]
Will do - unless of course @sparkasaurusRex wants to do the honors! :)

**Comment by icarter09** [comment]
No worries. I'm a fan of whatever it takes to make Mint and Cinnamon better. :)

@ranolfi if you do happen to do it, make sure to tag this issue in the PR.

**Comment by sparkasaurusRex** [comment]
Thanks @ranolfi I can make a PR. Not sure why I didn't do that when I found the fix.

**Comment by icarter09** [comment]
@sparkasaurusRex no worries and thanks for doing that.

**Comment by eli-schwartz** [comment]
Cool, thanks for submitting a PR. ;)

I just uploaded the fixed package to archlinux's community repository, so within the next couple of hours (depending on when your current mirror syncs) you can get the fix by running:

`pacman -Syu 'cinnamon>=4.4.3-1'`
