### ISSUE TITLE
Allow applets to turn into boxed desklets

### ISSUE THREAD

**Issue by feren** [linuxmint/Cinnamon#5587]
Kinda like KDE where if you drag an applet onto the desktop, it turns into a desklet, would it be possible to do something similar to Cinnamon in the near future?

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
