### ISSUE TITLE
Mint 18: Update Manager creates objects with wrong ownership

### ISSUE THREAD

**Issue by Cos-mo** [linuxmint/Cinnamon#5590]
Test system: LM 18 Cinnamon 64 bit. Fresh installation, no previous home content used.

Doing a refresh of the update manager creates in ~/.cache the folder dconf with the file user, both with wrong ownership by root.

Steps to reproduce:
Install the system and boot into.
~.cache does exist with the sub-folders fontconfig and wallpaper othe with correct ownership.
Open the update manager and select the policy: Still the same content for .cache.
Do a refresh in the update manager: the folder dconf with root ownership gets created. No other action has been taken, no switch of mirrors or anything else.

Conclusion: the bug is caused by the update manager.

**Comment by JosephMcc** [comment]
Would you please close this issue and move it here: https://github.com/linuxmint/mintupdate

It likely effects all Mint desktops and isn't specific to Cinnamon.
