### ISSUE TITLE
[Windows preview] Showing media controls when hovering a music or video player. 

### ISSUE THREAD

**Issue by Vahan86** [linuxmint/Cinnamon#5594]
Would be great if hovering a music or video player will show media controls directly in windows preview.

**Comment by mainmachine** [comment]
Doesn't this already happen in the audio applet?

Although I guess not when you hover, but it's similar...

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
