### ISSUE TITLE
nemo with hicolor symbols

### ISSUE THREAD

**Issue by oldtomdevel** [linuxmint/Cinnamon#5596]
When "Settings -> Themes -> Symbols" set to "hicolor", Nemo does not show text content within the symbol even though this feature was activated in Nemo's settings.
This is true for LM18 and LM17.3 with Cinnamon 64bit.

**Comment by JosephMcc** [comment]
Do you mean the text that shows up in the icons for things like text files in Nemo?

**Comment by oldtomdevel** [comment]
just to make the bug report clearer...
+ use nemo to show the content of a folder which contains at least one simple text file that is not empty.
+ set nemo to symbol view not detailed view
+ within nemo set "settings -> preview -> text files -> show text in symbols" to "always" or "local files"
+ in case that "Cinnamon settings -> Themes -> Symbols" is set to e.g. "Mint-X-Aqua", nemo shows the beginning of the text file content within the symbol as it was set in nemo settings i.e. the feature works.
+ however,  in case that "Cinnamon settings -> Themes -> Symbols" is set to e.g. "hicolor", nemo does not show any text file content within the symbol although this is required by nemo settings i.e. the feature does not work - this is the bug.

**Comment by JosephMcc** [comment]
Thanks for providing more info. The option to "show text in icons" or symbols died with gtk3.14. That means that option no longer works in LMDE2 or Mint18. We forgot to remove the option from the settings. It is now gone in git master and won't be there anymore in Cinnamon 3.2.
