### ISSUE TITLE
Rubbish bin applet on panel opens Nautilus

### ISSUE THREAD

**Issue by Fjodor42** [linuxmint/Cinnamon#5598]
...which then commences battle with Nemo for the root window: Both display icons, but Nautilus takes over background.

Obviously, Gnome is installed on my machines, which I'm not sure the Rubbish bin applet anticipates.

**Comment by xenopeek** [comment]
The trash applet uses code `Gio.app_info_launch_default_for_uri(this.trash_directory.get_uri(), null);` to launch the default application registered to handle the specified uri. In this case it must be Nautilus that is registered as such.

Installing just Nautilus and running it on Linux Mint 18 Cinnamon doesn't cause such problems that I could reproduce.

**Comment by Fjodor42** [comment]
Thank you for replying,

Do you happen to know how I could go about changing those defaults?

**Comment by xenopeek** [comment]
Some Googling around the below is one way I think to do it. There is possibly an easier way using some graphical program but I couldn't find it.

Check whether the following command replies "nautilus.desktop":
`xdg-mime query default inode/directory`

If so you can change it to Nemo with:
`xdg-mime default nemo.desktop inode/directory`

If that command gives and error first run and then try again:
`mkdir -p ~/.local/share/applications`

**Comment by Fjodor42** [comment]
Thank you - that seems to work beautifully :-)

**Comment by Fjodor42** [comment]
I'll leave it to the maintainers to decide whether something should be done to detect such things and offer to change it, whether to implement a better way to set such defaults, or whether to close this Issue.

**Comment by Vahan86** [comment]
I have installed Nautilus alongside Nemo. After clicking on trash applet icon on panel it was opened in Nemo. I have tested it in Cinnamon 3.0.7.

**Comment by JosephMcc** [comment]
I get the same results as @Vahan86 on Mint with nautilus installed. It opens Nemo, not nautilus.

**Comment by xenopeek** [comment]
I couldn't reproduce it either just with installing Nautilus. But I don't doubt there is a way Nautilus becomes the default. The issue at hand is that there is no obvious way to set that default mime handler for inode/directory back to Nemo.

**Comment by Fjodor42** [comment]
A bit more background: My systems are Ubuntu 16.04 with packages from the glebihan unstable repo. Nautilus was probably installed well in advance of Cinnamon and Nemo.

I agree with xenopeek that the issue is one of controlling default apps for mime types...

**Comment by Coeur-Noir** [comment]
Kind of same problem here.

Ubuntu 16.04 Unity, then I've installed Cinammon from embrosyn ppa. I use another session for Cinnamon, not tha same as Unity.

In Cinnamon session, if I click on trash panel applet  it opens Nautilus instead of Nemo. And desktop background is handled by Nautius then after.

Illustration : http://disq.us/p/1eap04v
