### ISSUE TITLE
add shortcuts will  reset srcreen wallpaper to default

### ISSUE THREAD

**Issue by zosy** [linuxmint/Cinnamon#5599]
bug
1.add custom shortcuts will reset srcreen wallpaper to default

.xsession-errors(lots of)

(cinnamon:1364): St-CRITICAL **: st_widget_get_theme_node called on the widget [0x55559e223e40 StScrollView.popup-sub-menu] which is not in the stage.

(cinnamon:1364): St-CRITICAL **: st_widget_get_theme_node called on the widget [0x5555a0bfc250 StScrollView.popup-sub-menu] which is not in the stage.

(cinnamon:1364): St-CRITICAL **: st_widget_get_theme_node called on the widget [0x55559faf5b50 StScrollView.popup-sub-menu] which is not in the stage.

ENV
1.OS fedora 24 x86_64
2.DE cinnamon-3.0.7-1.fc24.x86_64
**i have tested in centos 7 1511 x86_64/ cinnamon 2.8.8 ( installed from epel) also have this bug  too. [important]**

reproduce
1.custom wallpaper
2.system settings->keyboard->shortcuts->custom shorcuts->add custom shortcut

type  name and command , click Add  bug will shows. to add the first shortcut sometimes ok,but add the second one,and the third one  and ....... will happens.

**Comment by JosephMcc** [comment]
https://github.com/linuxmint/Cinnamon/issues/5513
