### ISSUE TITLE
Rethink displaying an email in for applets

### ISSUE THREAD

**Issue by dandv** [linuxmint/Cinnamon#5601]
This

![image](https://cloud.githubusercontent.com/assets/33569/17997465/9c3e6eae-6b23-11e6-9a9f-87c0d3a54e79.png)

led to this:

![image](https://cloud.githubusercontent.com/assets/33569/17997456/899ab258-6b23-11e6-94ba-3b64a842b18a.png)

That email address supposedly identifies the applet, but perhaps a (short) URL would be better.

**Comment by JosephMcc** [comment]
I'm probably being dense but I don't understand what you are reporting at all? What exactly the issue is. Sorry if it's obvious and I'm just missing something.

**Comment by JosephMcc** [comment]
Someone just pointed out to me what you are talking about it here. That isn't an email address but an applet identifier. Not sure there is really any good reason to display it in the applets settings page though.

**Comment by itzexor** [comment]
we could just remove it or prepend it with UUID:

**Comment by JosephMcc** [comment]
Done https://github.com/linuxmint/Cinnamon/commit/75e5eb6bed4c08713a1b7c397185dd0f5d1cfa41
