### ISSUE TITLE
Battery Indicator Of Wireless Computer Accessories Can Be Faulty

### ISSUE THREAD

**Issue by SerafDosSantos** [linuxmint/Cinnamon#5602]
I bought a new Logitech Wireless Mouse M320 and the battery indicator in the power management settings indicates it at 0% even when it's a new battery.

Not so sure also: should I see the power manager applet for the mouse battery? I know it is in a panel as I have highlight it but I'm using Mint on a desktop, I see nothing from that applet.

**Comment by JosephMcc** [comment]
I'm going to mark this as a bug though I'm not sure how much can be done. The settings can only show what the hardware provides. My Logitech mouse and keyboard always show 60 and 40% respectively.

**Comment by mainmachine** [comment]
I think for Logitech you might need Solaar installed...?

I have Solaar installed on several machines, and this works with my Logitech m510 wireless mouse and K400 wireless keyboard/trackpad combo - don't know if it's just coincidence that I have Solaar installed and my battery indicators work, but you might try installing it and see if it fixes the problem for you...

**Comment by JosephMcc** [comment]
I don't have solaar installed currently and my M510 always shows 55% so it might actually make a difference.

**Comment by SerafDosSantos** [comment]
My M320 isn't supported by solaar. But the M510 is. With solaar I get a notification when the mouse is powered on.

**Comment by SerafDosSantos** [comment]
Oh, and I hadn't seen the addition to the sys tray.

Now there's an addition as a battery icon in the tray and I can see that the battery is at 70% through solaar's panel.

But still in mint's power management panel, on the battery section, it says 0%.

**Comment by Vahan86** [comment]
@SerafDosSantos, is this still an issue for you with Cinnamon 3.6?

**Comment by leigh123linux** [comment]
There is nothing that can be done within cinnamon code to fix the value returned by upower.
