### ISSUE TITLE
Keyboard freezing...  Old Issue, but I found the cause

### ISSUE THREAD

**Issue by iplayfast** [linuxmint/Cinnamon#5604]
The cause is the color plugin, trying and failing to configure the color for a printer. My printer is a samsung ml-1670
When the freeze happens I get

(cinnamon-settings-daemon:5397): color-plugin-WARNING **: failed to connect to device: Failed to connect to missing device /org/freedesktop/ColorManager/devices/cups_Samsung_ML_1670_Series

After it times out, the keyboard is back.

If I delete the printer, things are fine, but something triggers the printer to be found again and the cycle repeats.

Please look into this, as it's been plaguing cinnamon since 17.

**Comment by JosephMcc** [comment]
Please add your info to https://github.com/linuxmint/Cinnamon/issues/5547

**Comment by iplayfast** [comment]
Sorry forgot that I already added 5547.
