### ISSUE TITLE
Nemo opens Trash in two-pane mode; one pane is not Trash

### ISSUE THREAD

**Issue by bjd-pfq** [linuxmint/Cinnamon#5606]
Nemo / Trash:

I normally have nemo in two -panel mode.

Now when when I click on Trash, I also get a two-pane nemo, one pane is thrash,
the other $HOME.

This is nutty and confusing.
When I open Trash, it should always just display that, and nothing else, regardless
of whether I have nemo open two panes for regular directories.

**Comment by JosephMcc** [comment]
Could you please move this issue to https://github.com/linuxmint/nemo/issues
