### ISSUE TITLE
After resuming from Suspend, most icons gone and barely any text is visible

### ISSUE THREAD

**Issue by feren** [linuxmint/Cinnamon#5607]
After suspending on Cinnamon 3.0.7 Unstable and then resuming, well, I'll let the screenshots speak for themselves:
![screenshot from 2016-08-28 19-09-13](https://cloud.githubusercontent.com/assets/11057934/18035759/b76779e6-6d53-11e6-8caa-fc34f2d99b95.png)
![screenshot from 2016-08-28 19-09-34](https://cloud.githubusercontent.com/assets/11057934/18035758/b7651ffc-6d53-11e6-9101-fe11945a70ce.png)
Also, it isn't just custom applets affected:
![screenshot from 2016-08-28 19-12-07](https://cloud.githubusercontent.com/assets/11057934/18035757/b76480ce-6d53-11e6-8738-dac65a56901b.png)

Though, any other apps (Nemo, etc) are not harmed by this bug in any way, shape or form...
- Cinnamon version: `cinnamon 3.0.7`
- Steps To Reproduce:
1. Suspend the PC
2. Leave it suspended for a while (or at least I did)
3. Resume it
4. Wait for the lock screen to show while Cinnamon functions normally despite the glitches in icon and text
5. Unlock the User

Restarting Cinnamon fixes it for that session, but still, it NEEDS to be fixed though

**Comment by feren** [comment]
Ok, so that you know which Cinnamon version is running, I checked in the Update Manager by enabling the 'Old Version' column and it says Cinnamon is currently '3.0.7-20160826040203-xenial' on my machine...

**Comment by feren** [comment]
Should I update or leave it as it currently is at for this issue?

**Comment by sprintcowboy** [comment]
I have this problem also.
but it is not at ever wake up.
It has also at times effected the unlock screen date and time with missing text.
I do have the Intel Iris Pro, not sure if it is recognizing it is the problem

**Comment by Pjotr123** [comment]
Do you mean "ordinary" suspend (suspend-to-ram) or hibernation (suspend-to-disk)?

**Comment by sprintcowboy** [comment]
In my case its suspend-to-ram.
I don't use hibernation, it just doesn't work properly.
I had to install deconf editor to change when the battery is critically low to suspend instead of the default hibernate.
For some reason the option is not in the power management settings in mint 18.
Here is a screen shot of mint 17.3 
![screenshot from 2016-07-07 15-44-26](https://cloud.githubusercontent.com/assets/1295589/18059293/5f1578ae-6de6-11e6-92ca-aa99a4193295.png)

**Comment by feren** [comment]
Ordinary suspend-to-ram

**Comment by feren** [comment]
Also, just in, but one of the guys that's trying my OS is having a similar bug but with Nemo (feren OS is based off of Linux Mint 18.0 and uses Cinnamon Stable):
![image](https://cloud.githubusercontent.com/assets/11057934/18233223/d57afe5a-72d8-11e6-84a3-dd5818830afb.png)

**Comment by Piiit** [comment]
Got the same problem with other tools now: WEKA which is a JAVA application.

![arbeitsflache 1_033](https://cloud.githubusercontent.com/assets/6096063/18384862/5adb4f52-768d-11e6-8059-d2ba2888e6af.jpg)

Big parts of the GUI are missing, when I move over them, they appear and stay again.

**Comment by hyOzd** [comment]
I'm also having this problem after upgrading to Linux mint 18. It doesn't happen after each suspend though. Sometimes its only the cinnamon, but I've also had the problem occur with other applications.

Cinnamon 3.0.7
Intel HD 4600 Graphics

![brokencinnamon](https://cloud.githubusercontent.com/assets/1479166/19143592/a2cbdc16-8bad-11e6-96ab-8906353c04f0.png)

**Comment by hyOzd** [comment]
Now I'm having this problem on Mint 17.3, cinnamon 2.8.8. This one is a laptop with Intel HD 4400 Graphics.

![screenshot from 2016-10-18 21 41 35](https://cloud.githubusercontent.com/assets/1479166/19491735/b9a81822-957c-11e6-8a72-4fed7eaec0e2.png)

**Comment by leigh123linux** [comment]
@feren Have you reported this issue against the Intel driver? as I doubt it's a cinnamon related.

**Comment by rik-shaw** [comment]
I can confirm this bug using Cinnamon 3.0.7, Ubuntu 16.04, intel graphics (Lenovo Thinkpad x230).  It is quite random (maybe 1 in 10 times?)  Also, sometimes active window will be transparent (can't see anything) with a black border.  Is the maybe muffin related?  I do not see the problem in other desktops.

**Comment by feren** [comment]
@JosephMcc Shall we have the 'Bug Reproduced' tag here? (Many people can confirm the bug)

**Comment by Redsandro** [comment]
Cofirmed.

@feren 9 out of 10 times I can successfully run `r` to restart Cinnamon as a workaround. E.g.:

<kbd>Alt</kbd> + <kbd>F2</kbd>, <kbd>r</kbd>, <kbd>Enter</kbd>

(Tremendously annoying, but better than nothing.)

**Comment by feren** [comment]
@Redsandro Ways of restarting Cinnamon:
Most Common: <kbd>Ctrl</kbd> + <kbd>Alt</kbd> + <kbd>Esc</kbd>
Simpler Way (Your way): <kbd>Alt</kbd> + <kbd>F2</kbd>, <kbd>r</kbd>, <kbd>Enter</kbd>
Good old Terminal way: <kbd>Ctrl</kbd> + <kbd>Alt</kbd> + <kbd>T</kbd>, <kbd>cinnamon --replace</kbd>, <kbd>Enter</kbd>

**Comment by chrisonhub** [comment]
I see this bug in Linux Mint 17.3 when using any of the 4.4 kernel series.  Currently on 4.4.0-45 to avoid the nosy cow bug, but might have to roll back to the 3.13 kernel series if this bug continues.

Intel graphics on my laptop.  scrambled or missing text after resuspend, sometimes after fast-user-switching between accounts.  restarting cinnamon fixes the bug, but wife and kids aren't going to want to learn how to do this.

**Comment by Redsandro** [comment]
@chrisonhub Intel, interesting, I should point out I have intel graphics too, and kernel 4.4.0-45 too. But I did have this issue for a long time, possibly as long as the first kernel that came out with Mint 18. I did _not_ have this problem with Mint 17.x.
 
@feren thanks, I didn't know about <kbd>Ctrl</kbd> + <kbd>Alt</kbd> + <kbd>Esc</kbd>

**Comment by chrisonhub** [comment]
I think I just found the equivalent bug in the Ubuntu tracker:
[https://bugs.launchpad.net/ubuntu/+source/xserver-xorg-video-intel/+bug/1573959](https://bugs.launchpad.net/ubuntu/+source/xserver-xorg-video-intel/+bug/1573959)

Interestingly, that bug refers to 4.4.0-21-generic kernel....

In the thread, people have suggested to remove xserver-xorg-video-intel,
and instead use the built in modesetting driver - does anyone know how to do this?

When I looked at Synaptic, the version I have installed is the:
`xserver-xorg-video-intel-lts-vivid - 2:2.99.917-1~exp1ubuntu2.2~trusty1`

in the description of the "xenial" version (same version number) says:

`The use of this driver is discouraged if your hw is new enough (ca.
2007 and newer). You can try uninstalling this driver and let the
server use it's builtin modesetting driver instead.`

Is anyone brave enough to try removing the driver?  
Is there an easier way to tell Mint to use the 'modesetting' driver instead?

**Comment by Redsandro** [comment]
Good find @chrisonhub 

This won't look good on my cv, but I'm too dependent on my work laptop to dare to try this right now. :angel: 

This bug is annoying but at least the workaround (restarting cinnamon) is reliable and doesn't even shut down any running apps.

**Comment by chrisonhub** [comment]
@Redsandro you wouldnt have had this issue with LM 17.x as they shipped with 3.13 or 3.19 kernels.  Unless you specifically updated to the 4.4 series, that is.

3.13 is ancient, but still supported for a while yet and doesnt have this bug.  I wont be upgrading to LM 18 until this bug gets fixed - oh, and also the one where your mouse cursor is invisible after user switch (again an Intel driver bug).  I saw similar graphical issues when i tested Ubuntu MATE 16.04 and the Ubuntu bug has people commenting from elementaryOS too, so it appears that the whole 16.04 and derivatives are affected.

We might have a long wait - it needs fixing upstream in Ubuntu, then backporting to Ubuntu16.04.x and then Clem and the team need to incorporate it into a LM 18.x

I might have to stick with LM17.3 for a while yet!!

**Comment by chrisonhub** [comment]
I found a suggestion on askubuntu on this topic (there are lots of open bugs for this problem - this has been a "known" but not fixed issue for a long time....)
http://askubuntu.com/questions/764361/some-icons-and-text-randomly-become-invisible-after-waking-up-from-sleep-ubuntu?noredirect=1&lq=1

this suggests to add the following line to /etc/environment
`COGL_ATLAS_DEFAULT_BLIT_MODE=framebuffer`

https://wiki.archlinux.org/index.php/intel_graphics#Font_and_screen_corruption_in_GTK.2B_applications_.28missing_glyphs_after_suspend.2Fresume.29

I am testing it now, with kernel 4.4.0-45 and LM17.3

**Comment by chrisonhub** [comment]
something else for people to try when using LM 18 is to update the graphics drivers with this PPA.  Supposedly helps people on Ubuntu 16.04 and 16.10:

https://launchpad.net/~oibaf/+archive/ubuntu/graphics-drivers

`sudo add-apt-repository ppa:oibaf/graphics-drivers
sudo apt-get update`

**Comment by chrisonhub** [comment]
Not sure its an improvement.  wake from suspend worked a few times, user switching was ok too, but then a wake from suspend showed me my desktop picture, dimmed with gray (ie the lock screen) but didnt provide a password prompt.  I couldnt switch to another TTY so had to hard-reset.  

I am back on 3.19 without the BLIT_MODE change.

For people on 16.04 or LM18, they might want to try updated graphic drivers:
https://launchpad.net/~oibaf/+archive/ubuntu/graphics-drivers

`sudo add-apt-repository ppa:oibaf/graphics-drivers
sudo apt-get update`

Please report back if this helps.

**Comment by feren** [comment]
@/all Moving this to https://github.com/linuxmint/Cinnamon/issues/3442

**Comment by geek1011** [comment]
@chrisonhub Removing the xserver-xorg-video-intel package worked for me.

**Comment by nikhilw** [comment]
This is what happens to my setup every few wake ups later. I do not have a nvidia card, so hardware drivers issue seemed unlikely. I first thought it happened every time I started a music player (clementine, mostly), but now I am not very sure. Sometimes restarting cinnamon helps (alt+f2, type r and hit enter) sometimes even that does not work and a full reboot is required.

**Comment by ip413** [comment]
the same problem here, but not every time and on **Mate** not **Cinnamon**; once on four, five times.
Config:
Thinkpad T-430s
Release Linux Mint 18 Sarah 64-bit
Kernel Linux 4.4.0-21-generic x86_64
MATE 1.14.1
3rd Gen Core processor Graphics Controller version 0.9  Driver: "i915"

**Comment by donkeyDau** [comment]
Same here with ElementaryOS running Pantheon ... Seems to be something more fundamental ...

**Comment by feren** [comment]
Just amping up the title to UPSTREAM ISSUE to reflect the confirmation about this bug upstream...

**Comment by cursande** [comment]
Cinnamon 3.2.7
18.1 serena
CPU: Intel Core i5-3320M CPU @ 3.3GHz
GPU: Mesa DRI Intel(R) Ivybridge Mobile 

Similar problems to above, icons are fine yet glyphs just don't render for some reason. Resetting cinnamon alone doesn't fix it, only rebooting has helped so far

**Comment by PaymaanJ** [comment]
press Alt+F2 and enter r
cinnamon refreshes, I have the same issue specially when I suspend at high ram usage (like too many chrome tabs are running)

**Comment by GiantCrocodile** [comment]
This worked for me @PaymaanJ. I just noticed this issue after doing updates and upgrading to Linux kernel v4.4.0-98.

This seem to be related to specific kernel versions or updated kernel dependencies.

**Comment by PaymaanJ** [comment]
@GiantCrocodile I am glad it worked for you. I am stuck at mint 17 and kernel 4.4.060  I suppose.

**Comment by vigilantesculpting** [comment]
I know this is an old issue, but I'm seeing this on linux mint 22.
Happens fairly regularly when switching users (this is the family computer).
Restarting Cinnamon with Alt-F2 "r" works.

Did anyone ever see a more permanent fix for this?


System:
  Kernel: 6.8.0-51-generic arch: x86_64 bits: 64 compiler: gcc v: 13.3.0 clocksource: tsc
  Desktop: Cinnamon v: 6.2.9 tk: GTK v: 3.24.41 wm: Muffin v: 6.2.0 tools: cinnamon-screensaver
    vt: 7 dm: LightDM v: 1.30.0 Distro: Linux Mint 22 Wilma base: Ubuntu 24.04 noble
Machine:
  Type: Desktop System: MSI product: MS-7A62 v: 1.0 serial: <superuser required>
  Mobo: MSI model: Z270 GAMING M3 (MS-7A62) v: 1.0 serial: <superuser required>
    uuid: <superuser required> UEFI: American Megatrends v: 1.10 date: 02/07/2017
CPU:
  Info: quad core model: Intel Core i7-7700 bits: 64 type: MT MCP smt: enabled arch: Kaby Lake
    rev: 9 cache: L1: 256 KiB L2: 1024 KiB L3: 8 MiB
  Speed (MHz): avg: 884 high: 1200 min/max: 800/4200 cores: 1: 808 2: 800 3: 801 4: 1024 5: 800
    6: 800 7: 1200 8: 841 bogomips: 57600
  Flags: avx avx2 ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx
Graphics:
     Device-1: NVIDIA GM204 [GeForce GTX 970] vendor: ASUSTeK driver: nvidia v: 550.120 arch: Maxwell
    pcie: speed: 2.5 GT/s lanes: 16 ports: active: none off: DVI-I-1 empty: DP-1,DVI-D-1,HDMI-A-1
    bus-ID: 01:00.0 chip-ID: 10de:13c2 class-ID: 0300
  Display: x11 server: X.Org v: 21.1.11 with: Xwayland v: 23.2.6 driver: X: loaded: nouveau
    unloaded: fbdev,modesetting,vesa failed: nvidia gpu: nvidia,nvidia-nvswitch display-ID: :0
    screens: 1

**Comment by chrisonhub** [comment]
Best to open a new bug report, or comment on one which is active (ie open)
