### ISSUE TITLE
Multiple Rows of Workspaces

### ISSUE THREAD

**Issue by hoodie** [linuxmint/Cinnamon#561]
It's been brought up on the [release page](http://cinnamon.linuxmint.com/?p=182#comment-2071),  many people would like to see the ability to arrange workspaces in 2 dimensions ( columns and rows ). Just added it as an issue so it can be handled properly like a feature request.

**Comment by eric-tucker** [comment]
Since Cinnamon still doesn't have this built in as of today's date, is it safe to assume this is never going to be integrated?

Also, there doesn't appear to be a way to rebind the shortcut for going to the next work space up/down in Ubuntu Cinnamon.  Only left/right.  Very annoying.

Why is the default horizontal workspaces anyway?  Horizontal workspaces make little sense with dual monitors and (IMO) confuse things more than they help.  A dual monitor desktop environment lends to a vertical workspace arrangement (1 column) much better.

**Comment by sglass68** [comment]
I'm interested in coding this up if someone gives me a few pointers. Somehow I have ended up with cinnamon and this feature is a big regression for me.

**Comment by bittner** [comment]
I second @et304383. I see more value in vertical workspaces, especially with a multi-monitor setup.

Any update on when vertical workspace support is going to land in Cinnamon?

**Comment by jonorthwash** [comment]
@hernejj's 2D workspace grid applet allows for this, though there's a minor bug recently with the animations because cinnamon cut support for the up/down animations.  But it does do vertical switching.

**Comment by bittner** [comment]
@jonorthwash Is this identical to the [Workspace grid extension](https://cinnamon-spices.linuxmint.com/extensions/view/31) available from _System Settings_ > _Extensions_? If not, will this be included in the official extensions anytime soon?

The former is obviously from another developer. I found 2 repositories:

- https://github.com/daemonl/cinnamon-workspace-grid
- https://github.com/hernejj/workspace-grid-cinnamon-applet

**Comment by jonorthwash** [comment]
The one I was referring to is currently listed as "Workspace grid (2D) and switcher", and is available through the "available applets (online)" section of the applets.  Here's information on it:
https://cinnamon-spices.linuxmint.com/applets/view/116

I wasn't aware of the workspace grid extension.  I'll have to check that out!

**Comment by jonorthwash** [comment]
Hmm, the extension doesn't really seem to do anything...  It doesn't seem to provide new keyboard shortcuts in any stable way, or adjust how the pager displays things.

**Comment by hernejj** [comment]
In the past the CInnamon devs have rejected the idea of a 2D workspace switcher. This is why I wrote the applet. It is not perfect but it does work.

How about it devs? Any chance of real 2D workspace grid? This feature is a must have for me, and unfortunately things keep changing that make it harder to keep my applet working. If Cinnamon (or the Gnome 3 base Cinnamon is built on) eventually loses support for vertical switching all together then I'm afraid I (and perhaps many others) will be forced to abandon Cinnamon in favor of a desktop environment that allows this feature. I really like Cinnamon and don't want to have to switch :(

**Comment by zaxebo1** [comment]
i too support this feature request. 
2D wirkspace grid (rows and columns) is implemented in mate desktop, and for many users (including me) without this feature it is very difficult to switch to cinnamon.
Plz implement as soon as possible.
Thanks in advance

**Comment by bartszu** [comment]
Well I don't know, here is how I do it in Mate.

![image](https://user-images.githubusercontent.com/8744067/31918159-22be5dcc-b853-11e7-9ebc-d5fee6a394cf.png)

**Comment by jonorthwash** [comment]
@bartszu, your screenshot doesn't show a 2D workspace grid.  And this thread (and repo) is about cinnamon.

**Comment by bartszu** [comment]
Well yes it is not Cinammon shot, I posted to indicate that there is many ways of using workspaces. I am not using workspace switcher at all. I just right click on title bar and send app to one of 99 workspaces I have there. You could have 1000000 of workspaces if you wish even on very weak machine, they are just numbers. I switch between them using Cairo Dock simply if I will send Xed and XTerminal and Calculator to workspace 66, if I select one of those apps I will be moved to workspace 66. If in the same time I have SMPlayer on workspace 87 if I will select it I will go to workspace 87, of course.

**Comment by bartszu** [comment]
Both title bar and dock allow you to move app to any workspace you wont, or attach it to every workspace you go, so move app to always active workspace. Sorry maybe it is useless but I don't think workspace switcher is good solution at all in any form.

![screenshot at 2017-10-24 00-32-45](https://user-images.githubusercontent.com/8744067/31920808-3fdfcf8e-b863-11e7-8126-f6615b34d9d3.png)
![screenshot at 2017-10-24 02-28-57](https://user-images.githubusercontent.com/8744067/31920810-410eee4e-b863-11e7-8973-75157db6abbe.png)

**Comment by jonorthwash** [comment]
> I don't think workspace switcher is good solution at all in any form.

@bartszu, as with most tools, a workspace switcher solves a problem for those who have it.  If you don't have this problem and use other tools to solve related problems, that's fine—but failure to acknowledge that others could possibly have a different problem than you is narrow-minded, and blurting out that your opinions are the only ones that matter in all of Open Source is a tad arrogant.  These qualities are prevalent in Open Source, but don't command much respect and won't get you far.  I don't hold any of this against you, and hope that you won't take me pointing it out personally—I just hope you take this to heart for future interactions.

As for my use case, the workspace switcher for me is, about 95% of the time, simply an indicator of which workspace I'm on, and (when designed to my liking) an indicator of which workspaces have things on them.  I tend to keep a 5-column, 2-row grid of workspaces, and can navigate to each one with alt-ctrl-[number] keyboard shortcuts, as well as alt-ctrl-[arrow] to go to adjacent ones.  Add shift, and the window ends up on that workspace.

The specifics of this use case are probably pretty rare, but the elements of the tool are general enough that they probably cover many other use cases that many other users might prefer.  Hopefully someone who understands the relevant parts of the Cinnamon codebase can work on this particular element of the tool.

**Comment by deepfire** [comment]
@bartszu,
> Sorry maybe it is useless but I don't think workspace switcher is good solution at all in any form.

Indeed -- the setup you've posted looks really hard to use.

The 2D workspace grid is a tremendously positive change from that, though -- and that's why we want it!

It better facilitates the spatial memory/perception that we humans have.

**Comment by bartszu** [comment]
@deepfire 
>  It engages the spatial memory/perception that we humans have.

If you think so its, hard to discuss with neuro - science.
Sorry you guys right.
I am not even a contributor to it :(

**Comment by DaveShuckerow** [comment]
Any updates on this?  Cinnamon is really great, but I have trouble organizing myself without a second dimension of workspaces.

**Comment by JosephMcc** [comment]
Thank you for your suggestion. See https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html for information on how we handle feature requests.

**Comment by giuse** [comment]
Any chance of reopening this discussion with the hindsight of two more years?

As many pointed out, the 2D arrangement of workspaces is extremely intuitive, a fact recognized with decades of adoption in most DEs. I understand being of the personal opinion that such a feature is not critical, but we know it constitutes a deal breaker for people used to it. @hernejj 's applet has been a life saver for *seven years* now, so you should have the data to objectively decide whether this feature is important for your users. Unfortunately it lacks the polish and customization of a native feature (graphics, transition effects, shortcuts, etc.). Please understand that the applet download numbers still hide the people who avoided cinnamon for the lack of this feature, and that a much larger slice would have been swearing by it right now if only they were ever exposed to it.

**Comment by DarrenCook** [comment]
I just switched someone from Mint 18 xfce to Mint 20 Cinnamon, having heard it offered more graphical bells and whistles. The first thing they asked for was the workspace switcher. The second thing was how to get two rows. I was hoping there might be an advanced configuration option hidden somewhere, so a bit surprised reading this thread that it is simply not an option.

(The applet URL tells me the site is down for maintenance all week, so haven't had chance to check that out yet; if it doesn't do the job, this may turn out to be an unexpected deal breaker, and we'll be upgrading to Xfce !)
