### ISSUE TITLE
Can't boot with notebook monitor and external monitor

### ISSUE THREAD

**Issue by quevon24** [linuxmint/cinnamon#5610]
I've been trying to boot linux mint 18 cinnamon on my notebook with notebook monitor and external monitor(hdmi) using nvidia-340 driver but the screen turns black and i can't get into mint, but if i power off the pc, unplug the hdmi monitor and turn on my notebook it boot fine, i also tried using nvidia-304, with this the pc boot fine with the monitor plugged but i can't use the panel, i just can't click on it on any option (menu option, clock, etc). The only one working fine is the xserve-xorg-video-nouveau. How can i fix this using the nvidia-340 driver? Or it's mint problem?

**Comment by Vahan86** [comment]
@quevon, does this issue still relevant to Cinnamon 3.6?

**Comment by Vahan86** [comment]
@icarter09, can we close this issue since there is no response from OP?
