### ISSUE TITLE
After suspend/resume some menue items are gone

### ISSUE THREAD

**Issue by Piiit** [linuxmint/Cinnamon#5611]
![menu_028](https://cloud.githubusercontent.com/assets/6096063/18079296/21e9c160-6e90-11e6-9b8c-8cb4772aacc2.jpg)

As you can see some menue items (near "Büro" and "Grafik") are gone after suspend/resume. 
When I reboot the are back again. It does not happen after all suspend/resume actions, but only some times.

LM18 64bit
Cinnamon 3.0.7
Linux 4.4.9

**Comment by JosephMcc** [comment]
https://github.com/linuxmint/Cinnamon/issues/5607
