### ISSUE TITLE
After suspend/resume some applications show parts of their GUI in black 

### ISSUE THREAD

**Issue by Piiit** [linuxmint/Cinnamon#5612]
![posteingang - gmail konto - mozilla thunderbird_029](https://cloud.githubusercontent.com/assets/6096063/18079484/4c25655a-6e91-11e6-858a-5122c07e9d0c.jpg)

When I move the mouse pointer to a GUI item it gets updated. When I resize the whole Thunderbird window everything gets updated again, but when I move the window by clicking and holding down the mouse button on the window title bar, the whole window gets black again until I release the mouse button.

I have Thunderbird minimized in tray during suspend / resume. Maybe that makes some difference...
Restarting Thunderbird solves the problem, but restarting Cinnamon does **not** solve it.

LM18 64bit
Cinnamon 3.0.7
Thunderbird 45.2.0

**Comment by JosephMcc** [comment]
Have you tried it under other DE's to see if it's a Cinnamon problem or possible a Thunderbird issue?

**Comment by Piiit** [comment]
@JosephMcc I will try... However, it worked under LM17.3...

**Comment by JosephMcc** [comment]
It could be a Cinnamon issue. Was it the same Thunderbird version?

**Comment by Cos-mo** [comment]
Does the problem show, if you run TB without extensions?

Menu icon -> help icon -> restart with deactivated add-ons.

**Comment by Piiit** [comment]
@JosephMcc It was the TB version of LM17.3 standard repositories...

**Comment by Piiit** [comment]
@Cos-mo It makes no difference if add-ons are active or not.

**Comment by Piiit** [comment]
@JosephMcc It does currently only happen with TB.

**Comment by Cos-mo** [comment]
Open in TB preferences -> advanced -> general -> switch hardware-acceleration. Does this change anything?

**Comment by Piiit** [comment]
Tried it with hardware-acceleration turned off. Makes no difference. 

However, I think it is related to #5607. It always happens when icons disappear... but I cannot reproduce it with certainty, it happens sometimes. Now it was not happening for several days.

**Comment by Piiit** [comment]
Got the same problem with other tools now: WEKA which is a JAVA application.

![arbeitsflache 1_033](https://cloud.githubusercontent.com/assets/6096063/18384862/5adb4f52-768d-11e6-8059-d2ba2888e6af.jpg)

Big parts of the GUI are missing, when I move over them, they appear and stay again.

**Comment by Piiit** [comment]
Got finally some evidence that it is definitively not only Thunderbird. 

See the screenshot (it is WEKA, a JAVA application):
 
![auswahl_033](https://cloud.githubusercontent.com/assets/6096063/18432042/3c00a082-78e0-11e6-857f-34a2694c205a.jpg)


ps. Since it does no longer only belong to Thunderbird, I change the issue title...

**Comment by Piiit** [comment]
@JosephMcc It does also happens with XFCE, not only a Cinnamon issue....

**Comment by JosephMcc** [comment]
If I was making a random guess I would think it was some sort of driver issue.

I'm going to close this since it doesn't look like a Cinnamon bug. If someone discovers different it can always be reopened.
