### ISSUE TITLE
Tray icon for Shutter is too big and too close to other icons

### ISSUE THREAD

**Issue by Piiit** [linuxmint/Cinnamon#5613]
![auswahl_030](https://cloud.githubusercontent.com/assets/6096063/18079658/31ebbfe4-6e92-11e6-9e21-991e3a5950e4.jpg)

Tray icon for Shutter is too big and too close to other icons

LM18 64bit
Cinnamon 3.0.7
Shutter 0.93.1

Panel of Cinnamon set to something like 
  - Take my own size settings
  - Always show panel
  - Allow Cinnamon to adapt icons

**Comment by JosephMcc** [comment]
We already have an issue for reporting systray icon issues: https://github.com/linuxmint/Cinnamon/issues/481
