### ISSUE TITLE
Arrange Icons in the raster on Cinnamon Desktop without sorting them - Feature request

### ISSUE THREAD

**Issue by hubertmeier** [linuxmint/Cinnamon#5614]
If i want to align the icons on the desktop, i can them rearrange only when i click "Schreibtisch alphabetisch sortieren". I want align the icons at the raster without sorting them ...

Thank you

**Comment by JosephMcc** [comment]
This handled by nemo, so belongs here: https://github.com/linuxmint/nemo
Make sure and do a search there because there are already a number of issues dealing with the layout of icons on the desktop.
