### ISSUE TITLE
Add more combinations for Switching to Another Keyboard Layout

### ISSUE THREAD

**Issue by pretodor** [linuxmint/Cinnamon#5615]
If you go to 'Keyboard -> Layouts -> Options... -> Switching to another layout', you'll notice that 'Win+Shift' is missing from the list. I would like to request the devs add it as a possible keyboard combination.

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
