### ISSUE TITLE
Title bar settings not universally honoured

### ISSUE THREAD

**Issue by Fjodor42** [linuxmint/Cinnamon#5617]
I have 3 buttons on the left-hand-side of the title bar.

The following is a, probably incomplete, list of applications that do not seem to honour that setting:
- gnome-calculator
- eog
- gedit

Screenshots attached of gnome-terminal which does the right thing, and gnome-calculator, which doesn't.
![screen002](https://cloud.githubusercontent.com/assets/1410995/18162073/ec80527c-7034-11e6-95f8-bf434f6c414c.png)
![screen001](https://cloud.githubusercontent.com/assets/1410995/18162074/ec828fc4-7034-11e6-89a3-397741b350f3.png)

**Comment by Fjodor42** [comment]
Hmmm, incidentally, it would seem that ```import``` from ImageMagick cannot see the Cinnamon tool bar - perhaps that should also be reported as an Issue?

**Comment by Pjotr123** [comment]
What Mint version and what Cinnamon version are you using? Note that in Mint 18 you're supposed to use the default X-apps, which do submit themselves to the general settings:
https://www.linuxmint.com/rel_sarah_cinnamon_whatsnew.php

**Comment by JosephMcc** [comment]
@Pjotr123 We get bug reports from a lot of non Mint Cinnamon users here. Even in Mint this is valid with applications like Calculator.

**Comment by JosephMcc** [comment]
I could have sworn there was already an open issue for this problem but I can't find it now.

**Comment by feren** [comment]
There is a fix for it, but **it needs to be implemented into Cinnamon Settings for it to work**:
There's a dconf value called `org.cinnamon.desktop.interface gtk-decoration-layout` and that is what controls window button layouts in headerbars on Cinnamon

**Comment by Coeur-Noir** [comment]
Ubuntu 16.04 here with Unity.
Cinnamon installed from embrosyn ppa.
CSD windows do not have buttons on left : 
![capture du 2017-01-15 17-47-18](https://cloud.githubusercontent.com/assets/1895947/21964369/bbf676b4-db4a-11e6-9fad-38621bbe511d.png)

**Comment by clefebvre** [comment]
Fixes:

https://github.com/linuxmint/cinnamon-desktop/commit/2c67d16f5a62f95c20a7ea7f19a1315c774f56a4
https://github.com/linuxmint/muffin/commit/89d1f65a48b7f978506d5de475dd5f58197efd79
https://github.com/linuxmint/cinnamon-settings-daemon/commit/073fa6de7c06fee23d5d740af7cfbeff4ca4a597
https://github.com/linuxmint/Cinnamon/commit/5c9848a48da3387825f627117ad58521474e0b2e
