### ISSUE TITLE
"All types" in Bluetooth dialog makes it hard to set up new devices

### ISSUE THREAD

**Issue by dandv** [linuxmint/Cinnamon#5620]
Is it possible to be more specific about the detected Bluetooth devices? Maybe at least display the manufacturer based on the first three bytes of the MAC address?

Or display the MAC, even if cryptic, because the user might recognize one or two bytes from somewhere else where they might have seen it while pairing (e.g. in a car).

![image](https://cloud.githubusercontent.com/assets/33569/18191376/a6fc030a-707e-11e6-8b5f-bcff825fa558.png)

**Comment by mainmachine** [comment]
This probably needs to be moved to [here](https://github.com/linuxmint/blueberry).

Good point - [Blueman](https://github.com/blueman-project/blueman) shows quite a bit more information, which can make the pairing process easier.

**Comment by JosephMcc** [comment]
@mainmachine is correct. This isn't Cinnamon specific. That is a general Mint tool.
