### ISSUE TITLE
Panel disappears on use of XWinWrap and/or other full screen wallpaper apps

### ISSUE THREAD

**Issue by feren** [linuxmint/Cinnamon#5622]
Unlike GNOME, Unity, etc, when XWinWrap is run in Cinnamon, soon enough the panel will disappear after normal Cinnamon usage behind the XWinWrap application and possibly also do the same thing with other applications that are newer than it that are used for the same job...

**Comment by feren** [comment]
Steps to reproduce:
1. Get Shantz XWinWrap and MPlayer and get this script ( http://gnome-look.org/content/show.php/Video+Wallpaper?content=128535 ) (or you could get feren OS and launch the 'Video Wallpaper' application in a Live CD to save time)
2. Run the script, and open a compatible Video file
3. Try to use Cinnamon for as long as you can before the panel goes under XWinWrap...

PS: I've tried all XWinWrap arguments on the script but every time it simply does the same thing over and over again...

**Comment by JosephMcc** [comment]
That thing has been updated in years. Not too worried about supporting it.

**Comment by feren** [comment]
Ok
