### ISSUE TITLE
[Feature Request] Allow Cinnamon to run with other window managers

### ISSUE THREAD

**Issue by feren** [linuxmint/Cinnamon#5623]
I know Muffin is a good window manager, but it would be nice if you could use Cinnamon with other window managers (e.g: Compiz, KWin, etc) without Cinnamon instantly closing when you try to run those window managers on Cinnamon as replacing Muffin with that window manager you run for the session.

Basically, what I'm asking is whether you can make Cinnamon function with any window manager (most other DEs can do the same thing) and as an added bonus, also possibly make an area in Settings to change the Cinnamon window manager like in LM Mate...

**Comment by JosephMcc** [comment]
That isn't really possible. Cinnamon is a compositor plugin for muffin. It would essentially have to be rewritten to allow that.

**Comment by feren** [comment]
Oh ok, I personally thought at first it was it's own Panel given how it layers on top of Nemo and manages windows in it, etc

**Comment by feren** [comment]
Though, @JosephMcc , would it be possible to make Muffin able to work if there's another window **decorator** decorating windows (e.g: Emerald)?

Kinda like the Compiz Window Decoration plugin where any window decorator can then decorate Compiz (Default is gtk-window-decorator)
