### ISSUE TITLE
Themes, Desktop background & Icons Not Working in Gentoo Cinnamon

### ISSUE THREAD

**Issue by ouchekkir** [linuxmint/Cinnamon#5630]
*_The Problems is: *_
1- Desktop theme and icons turned to the old look : 

https://s15.postimg.io/jxlclxebv/Screenshot_from_2016_09_02_19_34_40.png

2- Desktop background isn’t working and turned to black : 

https://s22.postimg.io/hghqzbt81/Screenshot_from_2016_09_02_19_36_02.png

3- Switching themes, icons, colors, cursors from `Menu>Preference>System Settings` isn’t reflecting the changes.

4- Power Management does Not Working .

--------- Any idea ? that's happens after the update .
--------- My configurations : Laptop i5 - 4GB RAM - ATI Graphique Cart - Gentoo Linux OS with Cinnamon Desktop.

**Comment by Vahan86** [comment]
@JosephMcc, can we mark this issue as a bug?

**Comment by JosephMcc** [comment]
Sure though I wonder about this even being a problem on our side. There are no other reports of this. And we are talking about a DIY distro here so there are a lot of variables involved.

**Comment by Vahan86** [comment]
@ouchekkir, is this still an issue for you with Cinnamon 3.6?
