### ISSUE TITLE
Some shortcuts to take screenshots are not working

### ISSUE THREAD

**Issue by Odyseus** [linuxmint/Cinnamon#5634]
Some shortcuts to take screenshots are not working

Hello, everybody.

The keyboard shortcuts **Shift+Print** (Take a screenshot of an area) and **Ctrl+Shift+Print** (Copy a screenshot of an area to clipboard) they work sporadically. The **Print** key some times needs to be pressed 2/3 (some times even more) times consecutively while holding **Shift** for the mouse cursor to enter into selection mode.

#### Some notes

- Using `gnome-screenshot -a` on a terminal works 100% of the time. Although, a warning message can be seen on the terminal *(** Message: Unable to select area using GNOME Shell's builtin screenshot interface, resorting to fallback X11.)*.
- In the live system these shortcuts have the same problem. But I only tested the live system on a VirtualBox virtual machine.
- If I assign a new custom keyboard shortcut to run the `gnome-screenshot -a` command, it has the exact same problem than the default shortcut.
- If I assign a new custom keyboard shortcut to run a script file containing the `gnome-screenshot -a` command, it has the exact same problem than the default shortcut.

### My system information
- **Operating System:** Linux Mint 18 Cinnamon 64-bit
- **Cinnamon Version:** 3.0.7
- **Linux Kernel:** 4.4.0-21-generic
- **Processor:** AMD Phenom(tm) II X4 955 Processor × 4
- **Memory:** 6.8 GiB
- **Hard Drives:** 1936.6 GB
- **Graphics Card:** NVIDIA Corporation G94 [GeForce 9600 GT]

**Comment by xenopeek** [comment]
Related to #3981 (which notes a related issue in MATE).

Some observations about shift+print on Linux Mint 18 Cinnamon 3.0.7:
- Hold down shift key and quickly/shortly tap the print key seems to always work. A longer press of the print key doesn't always work.
- If the desktop has input focus (click on it to give it focus) but no icon on it is selected/highlighted, shift+print always works regardless how long you press the print key. If an icon on the desktop is selected/highlighted it doesn't always work unless you only quickly/shortly tap the print key.
- It doesn't work at all if you have opened a menu.

A possible workaround reported on the forums is to bind the keyboard shortcut to a custom script that inserts a short delay:
```
#!/bin/sh

sleep 0.125
gnome-screenshot --area
```

**Comment by JosephMcc** [comment]
I'm going to go ahead and close this one as a duplicate. The issue linked by xenopeek gives pretty much all the same info.

**Comment by Odyseus** [comment]
Hello, g@ys.

**xenopeek:** Thanks for the link and the workarounds. I can confirm that the script with the delay works 100% of the time. The other workarounds also worked on some degree, but they are kind of annoying to take into account and use them on a daily basis. Thanks again.

**JosephMcc:** Very sorry for wasting your time with a known issue. It seems that I didn't do a very good job at searching for this. I will be more careful in the future and search more thoroughly the current issues before reporting here. Thanks, JosephMcc.

**Comment by JosephMcc** [comment]
It isn't always easy to find duplicates. I get help from others locating them and sometimes just remember there is one, so I know what I'm look for beforehand.
