### ISSUE TITLE
Gdebi showing a strange line instead of dependencies when overlay scrollbar effect is turned on

### ISSUE THREAD

**Issue by surenenfiajyan** [linuxmint/Cinnamon#5635]
Gdebi doesn't properly show dependencies when overlay scrollbar effect is turned on.
![screenshot from 2016-09-03 01-07-58](https://cloud.githubusercontent.com/assets/13224708/18223382/f400dcb8-71c6-11e6-86c1-e2fc134a1e36.png)

**Comment by JosephMcc** [comment]
This is an issue with GDebi, not with Cinnamon.

**Comment by surenenfiajyan** [comment]
@JosephMcc As far as I know, overlay scrollbar is a Cinnamon specific feature. This problem isn't present in Mate. This bug disappeared in Cinnamon only when I turned off overlay scrollbar effect. I don't think it's a good idea to blame the Gdebi tram when some enabled Cinnamon effect breaks it.

**Comment by JosephMcc** [comment]
> As far as I know, overlay scrollbar is a Cinnamon specific feature.

Overlay scrollbars are not a cinnamon feature. They are a feature of gtk. We just added a setting so that they could be disabled. Maybe Mate disables them by default.

**Comment by surenenfiajyan** [comment]
@JosephMcc OK.
