### ISSUE TITLE
Sound output changes when primary monitor is turned off

### ISSUE THREAD

**Issue by filippeof** [linuxmint/Cinnamon#5637]
When i connect my laptop through HDMI to an external monitor using mirror display option, whenever i either try to turn the primary display off or close the lid, the sound device output changes from the HDMI output to the laptop speakers built-in audio.
Tested with Fedora 24+ cinnamon 3.0.7

**Comment by clefebvre** [comment]
This looks like an upstream issue in pulseaudio. Please report it to pulseaudio directly.
