### ISSUE TITLE
Please, include Global Menu applet in Cinnamon officialy.

### ISSUE THREAD

**Issue by alxgvr** [linuxmint/Cinnamon#5638]
I would like to ask developers to include this Global Menu applet to official Cinnamon aplets set (preinstalled).
Global_AppMenu https://github.com/lestcape/Global-AppMenu

MATE devs already did it with TopMenu, and it is great!

Many users want to have Unity\MacOS experience with global menu.
Cinnamon already have Window Buttons applet (buttons on pannel), so in conjunction with global menu applet and feature to hide maximized window headbar (I would like to ask devs to implement this feature in Muffin settings also, or as an apllet like Maximus) it would be just fantastic! It is very handy on laptops with small screens (rational use of display space), and esthetically.

It will make Cinnamon DE more customizable.

![gmenu1](https://cloud.githubusercontent.com/assets/19569543/18227950/c2063734-723f-11e6-9a7b-9d9a83065673.png)
![gmenu2](https://cloud.githubusercontent.com/assets/19569543/18227951/c733b6aa-723f-11e6-9ce8-76ad7922de7c.png)

**Comment by mtwebster** [comment]
https://github.com/linuxmint/Cinnamon/issues/551
https://github.com/linuxmint/Cinnamon/issues/3032

This isn't something we're interested in for Cinnamon as a stock applet, as stated previously in these other issues.  To be honest, it's in the best place it could be - the developer can fix and update whenever he wants, not just major Cinnamon releases - this is the whole point of having a third-party applet community and a *trivial* way of installing these applets and extensions.

There are a number of very active developers who publish some really cool stuff for Cinnamon - I don't want to take away their control of their own product.

**Comment by lestcape** [comment]
Hey @mtwebster, i will be happy to donate my project, because my works it's for users not for me, also i don't like to use a global menu for myself...

There are better reasons of why add this on cinnamon it's not a good idea, as the support in Fedora, Arch and other distros... But probably, the most important reason is that: This is not in the way of how is the Cinnamon desktop conception.
