### ISSUE TITLE
xlet-settings: Avoid the usage set_center_widget or force gkt to be greater or equeals than 3.12

### ISSUE THREAD

**Issue by lestcape** [linuxmint/Cinnamon#5639]
With the change of @collinss  this was introduced:

https://github.com/linuxmint/Cinnamon/blob/master/files/usr/share/cinnamon/cinnamon-settings/xlet-settings.py#L143

set_center_widget it's since gtkmm 3.12:
https://developer.gnome.org/gtkmm/stable/classGtk_1_1Box.html#ae3204f9a5204aa56f8a509bf07d05dd3

Traceback (most recent call last):
  File "/usr/share/cinnamon/cinnamon-settings/xlet-settings.py", line 367, in <module>
    window = MainWindow(xlet_type, *sys.argv[2:])
  File "/usr/share/cinnamon/cinnamon-settings/xlet-settings.py", line 78, in __init__
    self.build_window()
  File "/usr/share/cinnamon/cinnamon-settings/xlet-settings.py", line 143, in build_window
    toolbutton_box.set_center_widget(self.stack_switcher)
AttributeError: 'Box' object has no attribute 'set_center_widget'

**Comment by JosephMcc** [comment]
Yes. Cinnamon now requires at least gtk3.12. Cinnamon 3.2 will is not supported on Mint17 or Trusty. Actually Cinnamon 3.0 isn't officially supported either, I just don't think there is anything stopping it from working.
