### ISSUE TITLE
Gtk and AccountsService version warnings

### ISSUE THREAD

**Issue by brmmm3** [linuxmint/Cinnamon#5643]
When calling cinnamon-accounts-service.py from command line the following warnings appear:

/usr/share/cinnamon/cinnamon-settings-users/cinnamon-settings-users.py:5: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk, GObject, Gio, GdkPixbuf, AccountsService
/usr/share/cinnamon/cinnamon-settings-users/cinnamon-settings-users.py:5: PyGIWarning: AccountsService was imported without specifying a version first. Use gi.require_version('AccountsService', '1.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk, GObject, Gio, GdkPixbuf, AccountsService

The attached patch fixes this.

Best regards,

Martin

[avoid_version_warning.diff.zip](https://github.com/linuxmint/Cinnamon/files/454402/avoid_version_warning.diff.zip)

**Comment by JosephMcc** [comment]
Can you make a proper Pull Request for it?

**Comment by lestcape** [comment]
The same for cinnamon-desktop-editor

**Comment by JosephMcc** [comment]
This actually shows up in a number of places. It's just a matter of locating all of them and cleaning it up.

**Comment by JosephMcc** [comment]
These were fixed by https://github.com/linuxmint/Cinnamon/commit/c2d73f606112b147f54d0f8db8de5a66ed9f0fd7
