### ISSUE TITLE
Missing reference in cinnamon-desktor-editor

### ISSUE THREAD

**Issue by lestcape** [linuxmint/Cinnamon#5644]
Please see: After the @collinss change cinnamon-desktor-editor was not updated.

There are then a missing reference of (XletSettingsWidgets):
https://github.com/linuxmint/Cinnamon/blob/master/files/usr/share/cinnamon/cinnamon-desktop-editor/cinnamon-desktop-editor.py#L19

The import of this package is for used the old class called  (Factory):
https://github.com/linuxmint/Cinnamon/commit/3478db2822d2f4c839c7d0ef7b517f0aa1d50bae#diff-e6d00cf758bec27aaf340773f60a3ce7L45

The  (Factory) class it's now called (JSONSettingsHandler) and XletSettingsWidgets it's now called (JsonSettingsWidgets) and it's here:
https://github.com/linuxmint/Cinnamon/blob/master/files/usr/share/cinnamon/cinnamon-settings/bin/JsonSettingsWidgets.py#L18

**Comment by collinss** [comment]
@lestcape I submitted a pr the other day that should address this.

**Comment by lestcape** [comment]
Thanks. @collinss.
