### ISSUE TITLE
Automatic changing of screen brightness depending on AC/batteryello,

### ISSUE THREAD

**Issue by thelordharry** [linuxmint/cinnamon#5646]
Hello.

A feature request please.

In Cinnamon, it would be great to have a feature where screen brightness automatically changes, depending on whether the machine is running on AC or battery.

For example, when the power lead is plugged in, the brightness is at 100%. When the power lead is removed and the machine is then running on battery, it would drop to something lower, of your choice, like 50/60%.

I used to be able to get around this in Linux Mint 17.3 by following these instructions:

https://ubuntuforums.org/showthread.php?t=2165826

But since I've updated to Linux Mint 18, this workaround no longer works. 

Besides, I think it would be a cool thing to have in Cinnamon anyway.

Thank you for your consideration.

**Comment by igordovgaluk** [comment]
+1

**Comment by suzsuzuki** [comment]
+1

**Comment by suzsuzuki** [comment]
+1

**Comment by intervisionlord** [comment]
Please add this feature...

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
