### ISSUE TITLE
Moving menu target creates zombie menu item

### ISSUE THREAD

**Issue by maharvey** [linuxmint/cinnamon#5652]
If I remove the target of a menu item, the item becomes invisible in the menu editor, even through it still exists in the menu. It appears that gnome or cinnamon is automatically disabling and hiding the menu item if the target is missing. The problem is that you move the location of an installed program, you now have a zombie menu item that cannot be deleted and cannot be edited to point to new item.

Reproduce:
1. Install telegram to some location & run it. Telegram creates a menu item in the Internet section. (example was installed to ~/Downloads/Telegram/)
2. Move the Telegram install directory to a different path. The gnome menu item is still there, but now click on it does nothing. Launching the menu editor applet it cannot see the Telegram menu entry. I also tried installing menulibre and it also cannot see the menu entry. (example: mv ~/Downloads/Telegram ~/bin/Telegram)
4. Created a symlink in the original location. The menu item now works again, and the menu item is now visible to the menu editor and to menulibre. (example: ln -s ~/bin/Telegram ~/Downloads/Telegram)

Found on Fedora 22 (x86-64) running Cinnamon 2.6.13

**Comment by icarter09** [comment]
@maharvey are you still experiencing this issue?

**Comment by Vahan86** [comment]
@icarter09, can we close this issue?
