### ISSUE TITLE
Sound applet doesn't control USB headset volume automatically

### ISSUE THREAD

**Issue by miskebekelniu** [linuxmint/Cinnamon#5653]
Hi,

I have this sort of setup - USB headset (Beyerdynamic MMX2) is connected to my monitor (Dell P2314H) via USB. The monitor is then connected via HDMI and USB to my laptop (Dell Latitude E5550). The additional connection (the USB one) from monitor to laptop is because of monitor has USB hub function - I have connected my mouse (Logitech m325) usb bluetooth dongle to it and also my headset. The mouse functions fine, I even get the battery status - so works the same as connected directly. 

Routine is this - come to my workstation, connect hdmi and usb from monitor to the laptop and then power on the laptop. So when turn on youtube after this - the sound is coming from headphones as expected, but if I press 'Volume Up' or 'Volume Down' on keyboard - the sound in heaphones doesn't change, because it controls laptop speakers sound. I have to open sound applet and select output device with the mouse, to be able to control the heaphones sound.

I consider this a bug of sound applet, since the system is playing the output through heaphones just fine, only sound control device doesn't change 'automagically'

**Comment by christophra** [comment]
This seems to be the same bug as https://github.com/linuxmint/Cinnamon/issues/5031 and https://bugs.launchpad.net/linuxmint/+bug/1326590. Interesting because on Launchpad it's said to have a fix comitted from 2014 but that doesn't seem to be in later releases.

**Comment by JosephMcc** [comment]
Looks like a duplicate.
