### ISSUE TITLE
monitors.xml does not update monitor configuration from proprietary driver

### ISSUE THREAD

**Issue by Redsandro** [linuxmint/cinnamon#5654]
When you change the order of monitors in `nVidia Server Settings`, _for example by necessity because the default [MST](https://en.wikipedia.org/wiki/DisplayPort#Multiple_displays_on_single_DisplayPort_connector) displays on a HiDPI panel are reversed_, the change is not propagated to `~/.config/monitors.xml`.

This causes both halfs of a wallpaper to be reversed on a HiDPI MST monitor.

Workaround: Manually updating `~/.config/monitors.xml`, logging out/in, re-pick wallpaper.

**Comment by icarter09** [comment]
@Redsandro are you still experiencing this issue?

**Comment by Redsandro** [comment]
@icarter09 I was still experiencing multiple long standing issues, probbly also this one, so I have retired the nvidia hardware a couple of months ago. AMD drivers have MST build in. I have no way to test this specific anymore. Similar to #6218.

**Comment by leigh123linux** [comment]
Cinnamon-settings display tool (even gnome display tool) has always been like this, its only useful for the open source drivers.
