### ISSUE TITLE
Time zone gets changed in coffee shops with a router in a different locale

### ISSUE THREAD

**Issue by noreasternhumidity** [linuxmint/cinnamon#5657]
It seems I didn't have this issue with Windows, but that a few versions ago.  The time is correct at home, but out at public access points, the time can be inaccurate.  I can only think this is due to their router being in different locale.  For me it is two hours ahead.  Sometimes it self-corrects after I have been connected a while.  Not sure if this can be addressed.

**Comment by noreasternhumidity** [comment]
Hmm.  Just figured out that my bios (HW) clock has been off by a couple hours.  So in some public places the clock is unable to synchronize online, hence it used incorrect bios time.

I don't recall having to adjust the HW clock in Windows as long as the SW clock is correct, but with Linux I needed to run "hwclock -w" as superuser to synchronize the HW clock to the software clock.

**Comment by JosephMcc** [comment]
Not sure this is really an issue with Cinnamon in that case.

**Comment by noreasternhumidity** [comment]
Just a different approach I suppose.  But it seems like something is unfinished.  Maybe there could be a slider button, to control update to the bios.  Maybe just underneath the Date & Time/Network Time slider, contingent on a successful return from Date & Time/Network Time.  If both are enabled, and no successful return, then bios does not get updated.  Just thinking, not really a feature request.

**Comment by noreasternhumidity** [comment]
P.S. the opposite seems to happen automatically already.  IE software clock gets updated by hardware clock on reboot (until Network Time updates software clock).  So why not provide the option to automatically correct an erroneous HW clock upon successful update from Network Time.

**Comment by NikoKrause** [comment]
Do you have a LinuxMint/Windows dual boot?

**Comment by Vahan86** [comment]
@noreasternhumidity, is this still an issue in Cinnamon 4.2?
