### ISSUE TITLE
Linux Mint 18 x64 - Cinnamon custom .desktop entries not working

### ISSUE THREAD

**Issue by Geyup** [linuxmint/Cinnamon#5658]
I noticed a few strange things when trying to work with, or create new .desktop files.

If I move as example gimp.desktop from /usr/share/applications to /home/foo/.local/share/applicatons
the .desktop file still works and shows in the menu.

If however I wanted to rename it, two things I'm noticing, when you right click the file and click rename, then the name is highlighted, if I then only remove the name and put in another name, then you end up with a .desktop named like this;

gimp.desktop.desktop

In order to properly rename it, you have to erase everything, and just type in 'gimp' and then the name ends up becoming 'gimp.desktop'. This behaviour needs to be fixed.

Now when I've renamed the .desktop file the 'NAME=' section no longer displays the name in the menu, instead, the name you've renamed the .desktop file, is now what appears in the Cinnamon menu entry.

Next I copied gimp.desktop to /home/foo/.local/share/applications and edited it for conky like below and it will not appear in the menu...

[Desktop Entry]
Version=1.0
Type=Application
Name=Conky
GenericName=Light Weight System Monitor For X
Comment=System Monitor
Exec=/home/foo/.conky/conky.sh
Icon=/home/foo/.icons/anycolor/128x128/apps/conky.png
Terminal=false
Categories=System;
StartupNotify=true

**Comment by Odyseus** [comment]
Hello, @Geyup.

Change the **Exec=** line to:
```bash
Exec=sh "/home/foo/.conky/conky.sh"
```

The path to a file is not considered a valid command by the menu. I think that this is a know issue, but I'm not sure. What I'm sure of is that in XFCE and KDE, for example, your desktop file is shown as it is.

**Comment by Geyup** [comment]
@Odyseus I originally just left the Exec=conky and it should of at least shown the entry in the menu.

Nothing works, I can't create a custom desktop file...

**Comment by Geyup** [comment]
I switch it around to make it even simpler, keepassx is really simple like this and it still doesn't show in the menu;

[Desktop Entry]
Name=Conky
GenericName=System Monitor
Exec=sh "/home/foo/.conky/conky_start.sh"
Icon=/home/foo/.icons/AwOken/clear/128x128/apps/conky.png
Terminal=false
Type=Application
Categories=Utility;

**Comment by Odyseus** [comment]
@Geyup: I don't know what to tell you. A desktop file placed on **/home/foo/.local/share/applicatons** folder with the following content:
```bash
[Desktop Entry]
Version=1.0
Type=Application
Name=Conky
GenericName=Light Weight System Monitor For X
Comment=System Monitor
Exec=sh "/home/foo/.conky/conky.sh"
Icon=/home/foo/.icons/anycolor/128x128/apps/conky.png
Terminal=false
Categories=System;
StartupNotify=true
```
... works just fine for me. It only takes a couple of seconds to appear in the Cinnamon menu.

![Image](https://dl.dropboxusercontent.com/u/5194280/VariousFiles/ScreenShotForGitHubIssue5658.png)

**Comment by Geyup** [comment]
Sure I know what this is, I've been doing it like 15 years, that is why I reported this.

Taking an original .desktop out of /usr/share/applications and moving it to /home/foo/.local/share/applications works!

The problem seems to be if I create an original, for some reason it's not working, also what's with the weird file renaming as I mentioned...

This is also on a clean fresh install of Mint 18 Cinnamon too

**Comment by Geyup** [comment]
@Odyseus are you using Mint 18 x86_64?

Also what permissions do you have on the file? I'm assuming 644?

Just to make sure I'm not loosing my mind LOL

I copied and pasted what you showed me to;

/home/foo/.local/share/applications/conky.desktop

[Desktop Entry]
Version=1.0
Type=Application
Name=Conky
GenericName=Light Weight System Monitor For X
Comment=System Monitor
Exec=sh "/home/sar/.conky/conky.sh"
Icon=/home/sar/.icons/AwOken/clear/128x128/apps/conky.png
Terminal=false
Categories=System;
StartupNotify=true

I still see NOTHING! :(

Errr

**Comment by Geyup** [comment]
OK sheesh adding the .desktop to /user/share/applications is working, so permission problem, group, etc., what?

**Comment by Odyseus** [comment]
@Geyup: That's the thing. I don't copy any .desktop file from nowhere. I just create an empty file on **/home/foo/.local/share/applications**, name it test.desktop, open it with a text editor and paste the content and save. A couple seconds later the entry on the menu appears.

> also what's with the weird file renaming as I mentioned

That's a nemo thing. That's why I don't use it, not even by accident (LOL). It display .desktop files with the name from **Name=** instead the real file name. I use SpaceFM.

> are you using Mint 18 x86_64?

Exactly so.

> Also what permissions do you have on the file? I'm assuming 644?

Also correct.

I just tested it using nemo.
- I went to **/home/foo/.local/share/applications**, right click and created a new empty document.
- I opened with my text editor and pasted this.
```bash
[Desktop Entry]
Version=1.0
Type=Application
Name=Conky created with nemo
GenericName=Light Weight System Monitor For X
Comment=System Monitor
Exec=sh "/home/foo/.conky/conky.sh"
Icon=/home/foo/.icons/anycolor/128x128/apps/conky.png
Terminal=false
Categories=System;
StartupNotify=true
```
- Saved and closed.
- I renamed the file and added the .desktop extension.
- A couple of seconds later, the entry shows on the menu.

**Comment by Geyup** [comment]
Well I was copying the files out of /usr/share applications to try them.

I just created an empty file too...

But this now appears to be like some permission problem, because they don't load from my $HOME but work from /usr/share/applications.

I just copied the one I made, conky.desktop from /usr/share/applications to /home/foo/.local/share/applications to see if it work this time, but still nothing...

Do you have to be a member of any group?

**Comment by Odyseus** [comment]
> Do you have to be a member of any group?

I don't thing so. My user is member of standard groups.

```bash
myusername: myusername adm cdrom sudo dip plugdev lpadmin sambashare
```

**Comment by Geyup** [comment]
Ok, I thought you said the entry appears right away for you?

I had to log out and back and now finally it's showing... Hmm odd

And for the naming, ok Nemo...

I guess we can close this...

SORRY MINT!
