### ISSUE TITLE
Do not autoload all side page from the SettingStack at once (Test targent: The sound module).

### ISSUE THREAD

**Issue by lestcape** [linuxmint/Cinnamon#5659]
I think, the cinnamon settings it's pretty nice and also faster right now, as never before was...

But, just there are one slow module, the sound module. This not mean a big deal, but i think it's the perfect candidate to apply this idea. Please see how on buildLayout function, all sidepage are loaded at once, and probably this is not necessary at this time and could not be necessary loaded the sound effect sidepage if user are not interesting in effects. Anyway they are  loaded...

So, i realize an experiment and I commented all code associate with a different sidepage of the primary one except the class objects needed to load the module.

Then i open again the audio module, an the improve it's in my appreciation amassing!! 

**Edit:**
There are then two possible better ways:
1- Load the first side page only and the others, when user want to see the others.
2- Load the first side page only and the others, on idle.

Regards.

**Comment by JosephMcc** [comment]
The biggest problem with this idea is that you are going to take the performance hit somehow. If it isn't in the initial load it's going to show up in page switching. I would much prefer the initial load be a bit slower and then get smooth interaction once the module is open.

Maybe you can come up with a clever way around this but Gtk can get unhappy if you don't set up and load all the interface elements in the right order and at the right time.

Btw, if you have many themes installed (like I always end up with for testing), the themes module is much worse when it comes to initial load times.

**Comment by lestcape** [comment]
@JosephMcc you are right, this will not involved a lost less time, just split the time between the side pages stack. 

Where the cinnamon dev's apply a similar ideas, and they considerer this a good practice?
1- In the cinnamon menu for loads items, where was apply the point 1, load the other items in idle.
2- In the cinnamon menu where was move the mouse release to mouse press only because cause the sensation of it's more faster.
3- In cinnamon-settings where also exist a module pre-load.

I'm convinced that this not go to any place, and there are not really increased of performance, but it's most soft for users...

Note: I have only the cinnamon theme, not others, so sure you are right and probably it's another target where can be apply this idea.

**Comment by lestcape** [comment]
Well, in this case you will not gain performance if you want to access of all sidepage, but if you want only the first, why you need to load the others?

**Comment by collinss** [comment]
When a user open the settings, how do we know which module(s) he will load? The most common use case is right after install, when the user will probably be using multiple pages. Even if that's not the case, I still agree with @JosephMcc for the same reasons he gave. A slight delay in opening might make the user think his computer is slow, while a delay in transition will more likely seem like the program is buggy.

**Comment by lestcape** [comment]
@collinss ok... 

I disagree, with both then, about ensure that will be a noticeable a delay in a transition... 
Also and in additional way, the transition some time help to hide an slow loaded if it's thinking in that way.

I'm pretty sure this can be enhanced to not get the impression of it's slow. Of course, will needed several test with several condition to ensure that always is causing the impression of it's faster.

**Comment by lestcape** [comment]
@collinss also see that the point 2 it's complete **unrelated with transitions**: "2- Load the first side page only and the others, on idle.".
