### ISSUE TITLE
systray applet acting weird

### ISSUE THREAD

**Issue by Alkaris** [linuxmint/Cinnamon#5661]
I'm having some stupid weird bug out of nowhere with the systray applet on the menu bar where it's displaying an icon for System Tray and I can't get rid of it because there is no Configure options for it, and it's messing with the other apps icons where I can't move them around becuase it wants to drag the whole thing.

This issue just suddenly cropped up today when I had to reboot, and I was greeted by this annoying issue with the icons that display on there.

See I get this weird clipboard-like icon there that's persistent and won't go away which was never there before inbetween the other app icons. I tried to remove systray applet and then re-adding but this doesn't fix it.

![shutter__2016yyy_ 9_09-09-16__02_42_17_am](https://cloud.githubusercontent.com/assets/6682988/18359020/18829b8e-7637-11e6-86be-d19ceaf8abcd.png)

It's so stupid that this applet doesn't have any configure options for it, and can't remove it's stupid icon thing. Let alone move around each individual icon to where I want them like I could before. I tried to also use another applet called System Tray Collapsible, but because of systray applet bug, I can't even move the icons into it to collapsible tray area because it's preventing me from moving them.

**Comment by mainmachine** [comment]
Which icon in that screen capture are you referring to?

**Comment by Alkaris** [comment]
@mainmachine I thought I already said in my post which icon. The one that looks like a weird clipboard-like icon in the middle there to the left of the Steam icon applet.

**Comment by JosephMcc** [comment]
Individual applications usually control weather or not they will display in the systray in their own preferences.

We have an open issue for systary icon problems: https://github.com/linuxmint/Cinnamon/issues/481

**Comment by mainmachine** [comment]
@Alkaris - I thought that's the one you meant, just wanted to be sure.

AFAIK that is for the ```indicator-cpufreq``` gnome applet. It shows CPU frequency and depending on CPU allows setting power/performance behavior. Do you have this installed?

**Comment by Alkaris** [comment]
@mainmachine I don't seem to have it installed, I did before, but I removed it, or at least I thought I did completely remove it.
