### ISSUE TITLE
Dahsed line in System Settings window

### ISSUE THREAD

**Issue by Vahan86** [linuxmint/Cinnamon#5662]
Dashed line appears in System Settings window during scroll down.

![screenshot from 2016-09-09 01-18-31 2](https://cloud.githubusercontent.com/assets/12819058/18367586/efe128bc-762c-11e6-8579-554b0b5b2d59.png)

**Comment by Cos-mo** [comment]
This is a "feature" (so to speak) of GTK 3.18.

At now there is only a workaround available, to get rid of them, see http://blog.linuxmint.com/?p=3035#comment-130076, but it does not work for applications, which run in root context (like synaptic).

**Comment by Odyseus** [comment]
Hello, everybody.

These doted lines should be automatically removed/hidden when the option **Overlay scroll bars (logout required)** is disabled. Or even better, add an option to remove those dotted lines to the **Effects** section.

**Comment by leigh123linux** [comment]
@Odyseus 

Try looking in the effects settings! 
There is a option to disable Overlay scroll bars and if thats not good enough go and whine at whatever theme provider you use as it isn't a cinnamon issue!

**Comment by Odyseus** [comment]
@leigh123linux

>Try looking in the effects settings!
There is a option to disable Overlay scroll bars and if thats not good enough go and whine at whatever theme provider you use as it isn't a cinnamon issue!

Did you actually read my message!?!? Or you let your fingers do all the talking/thinking?

And I already *wined to myself* and added the CSS tweak linked by @Cos-mo to my own theme. Which is the following code:
```css
.undershoot.top,
.undershoot.right,
.undershoot.bottom,
.undershoot.left {
	background-image: none;
}
```

**Comment by JosephMcc** [comment]
I'm going to close this before things go any further.

@Vahan86 Those are a new thing in Gtk3.18 and not Cinnamons doing.

**Comment by Vahan86** [comment]
Ok.
@JosephMcc, I applied your instructions to get rid of dashed lines in Cinnamon settings and it works fine for me. Thanks a lot!
