### ISSUE TITLE
Antergos [Arch]: Cannot add applets to panel

### ISSUE THREAD

**Issue by mabod** [linuxmint/cinnamon#5665]
Hi,
I have a freshly install Antergos Linux using cinnamon 3.0.7-1. I can not add applets to the panel. Only the default applets show up.

The applet list dialog suggests that there is an issue by showing a red circle icon next to the applet I try to install. But I can not find any error message in the logs. In fact, glass.log shows that the applet was loaded like here in this example with workspace-switcher:

`info t=2016-09-09T10:54:48.612Z 0 applet already loaded
info t=2016-09-09T10:54:48.854Z Loaded applet workspace-switcher@cinnamon.org in 244 ms
info t=2016-09-09T10:54:48.882Z Hiding systray: network
info t=2016-09-09T10:54:48.883Z Adding systray: pamac-tray (24x24px)
info t=2016-09-09T10:54:48.884Z Adding systray: blueberry-tray.py (24x24px)
info t=2016-09-09T10:54:50.385Z Resized pamac-tray with normalized size (22x22px)
info t=2016-09-09T10:54:50.386Z Resized blueberry-tray.py with normalized size (22x22px)`

Afterwards the start menu in the panel is moved to the right side. I have to restore the default settings to get a correctly ordered panel back.

I have no clue what is going on or how to debug this further.

Matthias

**Comment by mabod** [comment]
I found a workaround: I can add new applets to the panel by adding them to the cinnamon->enabled-applets key with dconf-editor. I appended workspace-switcher@cinnamon.org to that value which adds the applet to the far right side of the panel. I could then move the applet to the left by normal means. 

The value in dconf->cinnamon->enabled-applets now is:

['panel1:left:0:menu@cinnamon.org:0', 'panel1:left:2:workspace-switcher@cinnamon.org:12', 'panel1:left:1:panel-launchers@cinnamon.org:1', 'panel1:left:4:window-list@cinnamon.org:2', 'panel1:right:0:removable-drives@cinnamon.org:3', 'panel1:right:2:keyboard@cinnamon.org:4', 'panel1:right:3:systray@cinnamon.org:7', 'panel1:right:4:power@cinnamon.org:8', 'panel1:right:5:network@cinnamon.org:6', 'panel1:right:6:sound@cinnamon.org:9', 'panel1:right:7:calendar@cinnamon.org:10', 'panel1:right:8:settings@cinnamon.org:11']

Matthias

**Comment by mabod** [comment]
The issue is dconf-editor->cinnamon->next-applet-id: [Antergos User Forum](https://forum.antergos.com/topic/4825/cinnamon-applets-not-showing-up/10) The value is '0' after a fresh install but should be 12 (= number of installed applets +1)

**Comment by nocive** [comment]
i can also confirm this on a fresh installation. dconf workaround solved the issue for me.

**Comment by bentolor** [comment]
Can Confirm both. Bug & Workaround.

Dear Antergos-Devs: The only thing required to fix this issue is to preset `org.cinnamon.next-applet-id` to match the predefined amount of applets.

**Comment by bentolor** [comment]
If i get it right the problem lies in https://github.com/Antergos/Cnchi/blob/0b03d460fc4a9ab7f2cf1527dc89426b66dc4424/scripts/set-settings#L92 
There Antergos defines the default set of plugins with their ids, but misses to define the `next-applet-id` value, no?

**Comment by bentolor** [comment]
I added a merge request at the antergos project. This bug report probably can be closed as this issue is out f scope of the cinnamon project (unless they aim to get rid of this somehow strange property).

**Comment by Vahan86** [comment]
@mabod, is this still an issue for you with Cinnamon 4.2?

**Comment by mabod** [comment]
Wow. I opened this in 2016! What a surprise ;-)
I do not use cinnamon anymore but I believe the issue was fixed before I moved away.

**Comment by bentolor** [comment]
@Vahan86 IIRC this was an Antergos-specific issue of Cinnamon installations via the Antergos installer Cinchi.

The Antergos project has been retired in the meantime and is no longer publicly available, so this issue can be closed safely. Actually it was also fixed upstream via my patch.
