### ISSUE TITLE
Feature Request: Graphical Theme editor for cinnamon

### ISSUE THREAD

**Issue by hubertmeier** [linuxmint/Cinnamon#5666]
i like Cinnamon with the Windows-like-desktop, but i would like to change some small things, like the spaces between the icons on the bar (Leiste) or the color / transparency. I can change the whole style but not single elements. There is a css-file with such settings, but there a so much settings which are not clear for the standard user ...

the same for the desktop (icon size, space between the icons, Arrangement in the raster without alphebetically sorting ...), but this is nemo, right ?

**Comment by JosephMcc** [comment]
https://github.com/linuxmint/Cinnamon/issues/3356
