### ISSUE TITLE
Dangerous get_file_contents_utf8_sync vs we have not other good option.

### ISSUE THREAD

**Issue by lestcape** [linuxmint/Cinnamon#5667]
There are not an asynchronous version of: get_file_contents_utf8

I think that will be good provide one, also get_file_contents_utf8_sync is used  inside the cinnamon code. I know there are a big difference of where get_file_contents_utf8_sync is used in one place or in another. And it's not a big deal when is used for example when the applet is loading, but could be a big problem if it' used to load a file when the file content is changed.

**Comment by mtwebster** [comment]
This is a demo, loading about a 64k text file every second repeatedly then performing other tasks in a terminal. (It's about a 12mb file, sorry)

https://dl.dropboxusercontent.com/u/8201170/cinnamon-20160913-1.webm

Note, if I tried a ridiculously large file size, there was a freeze.  I tried an 80mb file to test out garbage collection - just handling the return data on this is what probably causes it.

Garbage collection appears to work fine.

**Comment by lestcape** [comment]
Well, i don't think that will be common load more than 1mb. Yes i agree which you, transfer the data to the javascript objects maybe it`s the problem, like this is not an asynchronous operation.

Anyway, you can test the same to compare your solution which the gnome one:
https://people.gnome.org/~gcampagna/docs/Gio-2.0/Gio.DataInputStream.read_until_async.html

The problem with the gnome one, it's how decode the string from the utf-8 encode inside cjs.

**Comment by lestcape** [comment]
@mtwebster thank for that.

**Comment by lestcape** [comment]
@mtwebster taking a look from cinnamon code:
https://github.com/linuxmint/Cinnamon/search?l=javascript&q=get_file_contents_utf8_sync&type=Code&utf8=%E2%9C%93


Where i think is needed your new function with more priority is here:
https://github.com/linuxmint/Cinnamon/blob/4de283cda710011de0bdf8c76d9916f1865e5bae/js/ui/settings.js#L588

I will try to create a pull request when i have a chance, to not bothering much.

Again thanks.

**Comment by lestcape** [comment]
@mtwebster i think, the deprecate mark would not be apply, because there are context where it's really  difficult replace the get_file_contents_utf8_sync by get_file_contents_utf8, because will involved a complete different scenario.

For example, if i replace all occurrence of get_file_contents_utf8_sync inside the setting.js file, then a lot of extensions will crash as actually they are binding and they are using the settings properties directly after the build the settings. As the settings will be loaded asynchronous, really the settings will not be ready and all this calls will fail.

We can also emit a signal and connect all cinnamon default extension to that signals, but all three-party extension will fail...

If this also will be done and all extensions will be fixed to work properly, there are another problem... Some extension will be rendered without apply the current style (because maybe some of them depend of the settings properties) and the desktop will be show really more faster than before, but after show it probably you will see how some extensions will change his representation as they receive in that moment a settings-ready signal and will preform the update of his components.

I really don't know if it's a priority a faster load on the cinnamon session start or will be more important show all at once also it`s more slow.

What do you consider will be the right way here?

**Comment by mtwebster** [comment]
You're right... I've been looking at this for a bit - I don't think we can really replace synchronous reading during cinnamon startup, or when an applet is added.

I deprecated it mainly to discourage people from using it if they read the docs.

I'm working on a couple changes to settings.js that eliminates the file load after a dbus update signal, and instead just updates the cached value to the new value received.  I've also eliminated the file monitor in settings.js... I figure, if dbus doesn't work for updating, Cinnamon probably isn't running, so it doesn't matter anyhow.  If someone's running cinnamon settings without Cinnamon running, the setting file will still be updated, so everything is still fine.  We use GDBusProxy in cinnamon-settings, which keeps track of name changes for dbus services (if you restart cinnamon, the proxy will attach itself to the new process automagically, and the existing setting pipe will continue working.)

I was trying to imagine how it would look for all the applets on my panels to show up randomly and in no particular order - I'm not sure I'd like it (it reminds me a little of Windows, for one thing).  I was probably going to leave it for now.

**Comment by lestcape** [comment]
@mtwebster, just an idea:

If the GDDBus service could run for example inside cinnamon-settings-daemon (and not inside cinnamon) and the cinnamon main thread it's a client like will be cinnamon-settings (both keeps track of name changes), you really will not need to thinking in efficiency. Also you could have all client that you want of the Dbus service and all IO operation will occur out of the cinnamon compositor thread and of course with an appreciable performance improved.

I really don't know how you can released a server (cinnamonDbus) from the IO operations, as the server it's the only one that always it's running (client not necessary), or you only have a plan of release the monitor only? Remove the monitor it's possible, but will be the cause of you will not have a way to inject a setting change writing the json directly...

Is complex....

**Comment by dodona2** [comment]
I also get a 'MetaSyncRing disabled: couldn't find required GL extensions, or the minimum safe openGL version was not met' when starting/running cinnamon.
