### ISSUE TITLE
[BUG] Changing the dconf setting controlling enabled applets in Cinnamon so applets have different Setting UIDs can cause crashes

### ISSUE THREAD

**Issue by feren** [linuxmint/Cinnamon#5669]
- The first glitch causes the first panel to get filled up with a blank space
- The second glitch is that if you hover over (if not already crashed) the blank space, it instantly crashes resulting in Fallback Mode...

**Comment by feren** [comment]
UPDATE: Here's the Cinnamon output of when it gets filled and then when it crashes:
```
(cinnamon:18463): Clutter-WARNING **: Attempting to add actor of type 'CinnamonGenericContainer' to a container of type 'StBoxLayout', but the actor has already a parent of type 'StBoxLayout'.
Window manager warning: Log level 8: cinnamon_tray_manager_manage_stage: assertion 'manager->priv->stage == NULL' failed

(cinnamon:18463): Clutter-CRITICAL **: clutter_actor_add_child: assertion 'child->priv->parent == NULL' failed

(cinnamon:18463): St-CRITICAL **: st_theme_context_get_for_stage: assertion 'CLUTTER_IS_STAGE (stage)' failed
Window manager warning: Log level 8: g_object_get: assertion 'G_IS_OBJECT (object)' failed

(cinnamon:18463): St-CRITICAL **: st_icon_set_gicon: assertion 'G_IS_ICON (gicon)' failed

(cinnamon:18463): Clutter-WARNING **: Failed to set the markup of the actor 'ClutterText': Error on line 1: Entity did not end with a semicolon; most likely you used an ampersand character without intending to start an entity - escape ampersand as &amp;

(cinnamon:18463): St-CRITICAL **: st_icon_set_gicon: assertion 'G_IS_ICON (gicon)' failed

(cinnamon:18463): Clutter-WARNING **: Attempting to add actor of type 'CinnamonGenericContainer' to a container of type 'StBoxLayout', but the actor has already a parent of type 'StBoxLayout'.

(cinnamon:18463): Clutter-WARNING **: Attempting to add actor of type 'CinnamonGenericContainer' to a container of type 'StBoxLayout', but the actor has already a parent of type 'StBoxLayout'.

(cinnamon:18463): St-CRITICAL **: st_theme_context_get_for_stage: assertion 'CLUTTER_IS_STAGE (stage)' failed
Window manager warning: Log level 8: g_object_get: assertion 'G_IS_OBJECT (object)' failed

(cinnamon:18463): St-CRITICAL **: st_theme_context_get_for_stage: assertion 'CLUTTER_IS_STAGE (stage)' failed
Window manager warning: Log level 8: g_object_get: assertion 'G_IS_OBJECT (object)' failed

(cinnamon:18463): Clutter-WARNING **: Spurious clutter_actor_allocate called for actor 0x55e9fb0aba70/StIcon which isn't a descendent of the stage!


(cinnamon:18463): Json-CRITICAL **: json_object_get_object_member: assertion 'node != NULL' failed
Window manager warning: Log level 6: /build/glib2.0-7IO_Yw/glib2.0-2.48.1/./glib/gmem.c:130: failed to allocate 2106988691456 bytes
Trace/breakpoint trap (Crashes here)
```

**Comment by feren** [comment]
And for reference, the dconf setting...
Before the change: `['panel1:left:0:slingshot@jfarthing84:24', 'panel1:left:1:WindowListGroup@jake.phy@gmail.com:25', 'panel1:right:0:notifications@cinnamon.org:4', 'panel1:right:4:inhibit@cinnamon.org:29', 'panel1:right:2:keyboard@cinnamon.org:7', 'panel1:right:3:removable-drives@cinnamon.org:6', 'panel1:right:5:a11y@cinnamon.org:28', 'panel1:right:6:user@cinnamon.org:5', 'panel1:right:7:show-hide-applets@mohammad-sn:23', 'panel1:right:8:weather@mockturtl:26', 'panel1:right:9:MessagingMenuV3@blub:27', 'panel1:right:10:systray@cinnamon.org:12', 'panel1:right:11:network@cinnamon.org:9', 'panel1:right:12:sound@cinnamon.org:10', 'panel1:right:13:power@cinnamon.org:11']`
After the change (post crash): `['panel1:left:1:WindowListGroup@jake.phy@gmail.com:44', 'panel1:left:0:slingshot@jfarthing84:47', 'panel1:right:0:keyboard@cinnamon.org:7', 'panel1:right:3:removable-drives@cinnamon.org:6', 'panel1:right:4:notifications@cinnamon.org:4', 'panel1:right:5:show-hide-applets@mohammad-sn:42', 'panel1:right:6:weather@mockturtl:43', 'panel1:right:7:MessagingMenuV3@blub:23', 'panel1:right:8:systray@cinnamon.org:36', 'panel1:right:9:network@cinnamon.org:9', 'panel1:right:10:sound@cinnamon.org:10', 'panel1:right:11:power@cinnamon.org:11', 'panel1:right:0:user@cinnamon.org:48', 'panel1:right:0:a11y@cinnamon.org:49', 'panel1:right:0:inhibit@cinnamon.org:50', 'panel1:right:0:ScreenShot+RecordDesktop@tech71:52']`

**Comment by feren** [comment]
Affects:
- Cinnamon
- Linux Mint 18 and forks
- Live Sessions and Installed System ones

**Comment by JosephMcc** [comment]
Just to clarify, the "After the change" is what you changed it to?

Why are manually changing it?

**Comment by feren** [comment]
1. Yeah
2. I'm not myself changing it but a program that runs the gsettings command to change the panel config to that when changing themes (aka: Themer on feren OS) to a applet configuration made to save the user the time of doing it themselves, still, wasn't expecting it to have such a glitch when doing something simple as that...

**Comment by feren** [comment]
...it affects EVERYONE using Themer too though

**Comment by JosephMcc** [comment]
So setting up and configuring applets works fine with Cinnamons built in tools but your custom application breaks it? How is that a Cinnamon bug?

Btw, look at the modified gsettings key you posted. Just how many applets do you think can be at panel1:right:0?

**Comment by feren** [comment]
If you want, I can drop the Gambas executable of feren Themer from 2016.2 so you can see the bug for yourself, but...
- You'd need Applets like Window List with App Grouping, Weather, Slingshot, Screenshot and Inhibit Applet too for it to work properly otherwise it'll just fail to load applets geniunely
- Also, you'd need gambas3 from The Gambas Team PPA...

**Comment by feren** [comment]
I was thinking that it was Cinnamon given the output of Cinnamon with the bug...

**Comment by feren** [comment]
BTW, how many actually can? Not sure here (I thought it was infinite given it works anyway after restarting Cinnamon)

**Comment by feren** [comment]
Also, just for last debugging purposes, what is a Trace/Breakpoint trap?

**Comment by lestcape** [comment]
Hey @feren, if you want to crash cinnamon there are more than 1000 ways to do it... Here you can see some of them: http://www.imdb.com/title/tt1105711/ i.e. Cinnamon can die like you or me, we are not perfect, as cinnamon also is not.

So, if you want to crash cinnamon you can do it and this not mean a problem...

Not feel bad, you are not the only one that probably don't understand that. This is one more thing of why handle a project like Cinnamon it's really complex. There are situations where some Cinnamon code was updated and only this fact is the cause of a Cinnamon crash, just because an unsupported extension is running in the new version. This is also the cause that you can modify the desktop like you want, because all cinnamon code it's exposed and can be modify if you create an extension for that.

If you have a lot of money, then you have more chance to be stolen, if you let others modify your main code as they want, sure you will be more vulnerable to crash.

There is no solution that can cover all  modification of the cinnamon code, because are endless, and will always a problem. You need to know how to live with this.

**Comment by matcheydj** [comment]
Themed panel device lease he based

**Comment by feren** [comment]
@lestcape Though, I'm just wondering, for if I ever fork Cinnamon, what is 'Trace/Breakpoint trap'?

**Comment by lestcape** [comment]
@feren there are not a thing like that, but there are ways to test individual packages (it's pretty difficult) and for more common test you can use Melange Cinnamon Debugged ()click on panel), or see the log files, or execute cinnamon --replace &

**Comment by feren** [comment]
@lestcape Oh ok, it's just that that was the last line of output on the 'cinnamon --replace' command when it crashed in the first place, so I was curious whether you knew what it meant or not...

**Comment by lestcape** [comment]
There are not allays a directly implication of the output with the real problem. In your particular case one way to fix your code could be:

1- Set in gsettings the same that gsettings have,
2- Set X=1
3- if not error, change only X values and set the gsettings
4- Set X = X + 1
5- if not finished goto 3

This will help you to find your real problem.

**Comment by matcheydj** [comment]
Hi linuxmint/Cinnamon,

I'd like to add you to my professional network on LinkedIn.

- David

Confirm that you know David: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=UxgrnwyR&invitationId=6188766498966818816&trk=eml-guest-invite-cta&trkEmail=eml-invite_guest-null-2-null-null-0%7Eitucqfuk%7Ekz








You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-itucqfuk-kz&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQEjiuSzhny0nAAAAVeLqwM7gRECRv2q4e1IfQGkVsOgFxGXdrI4SDv2QsncjwgXTww_bq7EZsM3x8ilyHizLw6Qamex5eIUFgWB_xW66AeL3AYLLwT8llIv-6m7zVNYctGWKlMcLKFmuVJvD4JMhw4qteyjDerm-RgaXG8icPKxpSGR9UO06ynG7eubcmSG77Sb&eid=0-itucqfuk-kz


This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-itucqfuk-kz&a=customerServiceUrl&ek=invite_guest

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by lestcape** [comment]
@JosephMcc see this, and please remove the comment after this if you considered, because anyone can just click on this, even unintentionally.

**Comment by JosephMcc** [comment]
@lestcape Done ;)

**Comment by feren** [comment]
Ok, little update, I had the bug, except this time, Cinnamon didn't crash when I hovered over the applet, here's my observations:
 - There's an applet bigger than the screen on the panel which could be why it was always crashing when trying to hover over it
 - Because of that, it fills the screen, so I couldn't actually see which applet it was
 - It had no visible icon nor text...

**Comment by matcheydj** [comment]
David Matchey would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=UxgrnwyR&invitationId=6188766498966818816&trk=eml-first_guest_reminder_01-hero-121-accept_text&trkEmail=eml-first_guest_reminder_01-hero-121-accept_text-null-1hluyg%7Eiu4ibpbu%7E2u

View David Matchey&#39;s profile: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=UxgrnwyR&invitationId=6188766498966818816&trk=eml-first_guest_reminder_01-hero-3-profile_text&trkEmail=eml-first_guest_reminder_01-hero-3-profile_text-null-1hluyg%7Eiu4ibpbu%7E2u





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=1hluyg-iu4ibpbu-2u&t=lun&midToken=AQFmrFVhGEd36Q&ek=first_guest_reminder_01&li=123&m=unsub&ts=HTML&eid=1hluyg-iu4ibpbu-2u&loid=AQHNaRUyKsPdJAAAAVex_fPvELR9Zzf8hatzptm-by_BiIY3EH1CR3w7HBkbjcHND3kG-HwKDRepk4ax1zyM09IBQdfsf3b7RDG2AClyEhWfc8C70M9gCA09EL56lk90zVPLlJKVZaNRNDioCeUZHt3cUZPMVwIoCSrfo2Xxw71FDoEm-4Lq0_EGET-OC94TWbCQ

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=1hluyg-iu4ibpbu-2u&a=customerServiceUrl&ek=first_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.
