### ISSUE TITLE
Please add emojis

### ISSUE THREAD

**Issue by LinuxHax00r** [linuxmint/Cinnamon#5672]
NO DESCRIPTION NEEDED ITS AN OBVIOUS FEATURE THAT ONLY THOU ART MISSING

**Comment by JosephMcc** [comment]
Emojis? Where? And for what?

**Comment by LinuxHax00r** [comment]
THERE is no way to type emojis like you can in macos and windows, its such an obvious feature that thou so called coders have neglected to add

**Comment by JosephMcc** [comment]
> its such an obvious feature that thou so called coders have neglected to add

Enough of this. A good number of people dedicate a lot of time and effort working to improve the Mint projects for everyone. These types of disrespectful comments aren't going to tolerated.
