### ISSUE TITLE
(Next version urgent) Please include youtube downloader

### ISSUE THREAD

**Issue by LinuxHax00r** [linuxmint/Cinnamon#5673]
this way we can downloadeth youtube videos animes ecetera without looking at ads, this is a very easy thing to do all thou need to do is sudo apt-get install youtube-dl

**Comment by RavetcoFX** [comment]
This has nothing to do with cinnamon, and will probably never happen please close

**Comment by LinuxHax00r** [comment]
@RavetcoFX WHY DID YOU CLOSE THIS I said it was needed for the next version

**Comment by LinuxHax00r** [comment]
@JosephMcc and @RavetcoFX are the reason linux sucks in many ways, I hope botheth of thour computers blow up

**Comment by JosephMcc** [comment]
@RavetcoFX  didn't, I did. This has nothing to do with Cinnamon and doesn't belong here.
