### ISSUE TITLE
Some desktop icons are half size on a HiDPI screen.

### ISSUE THREAD

**Issue by BaraVaq** [linuxmint/Cinnamon#5676]
Hi,
Some icons such as Synaptic look half size on a HiDPI screen in Debian testing (as of today). 
Also it is impossible to resize it. 
Cinnamon 3.0.7-1
Thank you.

**Comment by leigh123linux** [comment]
What gtk3 version is Debian testing using?

**Comment by BaraVaq** [comment]
In Debian testing it is 3.21.5-3.
This problem also exists in Debian Stable with Cinnamon 3.0.4 where the version is 3.14.5-1.

**Comment by JosephMcc** [comment]
See if changing icon themes makes a difference. As of gtk3.14 icon themes are much pickier about the sizes they are allowed to use.

It sounds like some of the icons show at the proper size and some do not. That would lead me to believe the icon theme is the issue.

**Comment by BaraVaq** [comment]
In gnome-shell they are ok.

**Comment by Vahan86** [comment]
@BaraVaq, does this issue still relevant to Cinnamon 3.4?

**Comment by JosephMcc** [comment]
Closing due to age and lack of feedback on newer versions.
