### ISSUE TITLE
Make cinnamon menu icon accept gifs please

### ISSUE THREAD

**Issue by LinuxHax00r** [linuxmint/Cinnamon#5678]
it is doltish that thou cannot make the icon for the cinnamon menu animated. Please fix this asap

![image](http://orig09.deviantart.net/2832/f/2010/181/d/e/chibi_rika_animation_by_bitter_bell.gif)

**Comment by JosephMcc** [comment]
https://github.com/linuxmint/Cinnamon/issues/4339

**Comment by LinuxHax00r** [comment]
Look at thou @JosephMcc censoring more of thy ideas, thou art no better thanst than the Chinese communist leader Mao Zedong
