### ISSUE TITLE
The package gir1.2-gda is required and is missing?

### ISSUE THREAD

**Issue by lestcape** [linuxmint/Cinnamon#5685]
Maybe, gir1.2-gda  is required as a dependency of the cinnamon package, but is missing:

cinnamon --replace
Cjs-Message: JS LOG: About to start Cinnamon
St-Message: cogl npot texture sizes SUPPORTED
Cjs-Message: JS LOG: Cinnamon started at Tue Sep 13 2016 06:57:09 GMT-0500 (CDT)
Cjs-Message: JS LOG:  Gda Library not found install gir1.2-gda package
Cjs-Message: JS LOG: network applet: Cannot find connection for active (or connection cannot be read)
openGL version 3.3 detected (GL3 Cogl Driver)
MetaSyncRing disabled: couldn't find required GL extensions, or the minimum safe openGL version was not met
Cjs-Message: JS LOG:  Gda Library not found install gir1.2-gda package
Cjs-Message: JS LOG:  Gda Library not found install gir1.2-gda package
Cjs-Message: JS LOG:  Gda Library not found install gir1.2-gda package
Cjs-Message: JS LOG: Invalid network device type, is 14
Cjs-Message: JS LOG: network applet: Found connection for active

**Comment by JosephMcc** [comment]
@lestcape I don't have that package installed or have those errors. Could it be coming from a third party xlet?

**Comment by lestcape** [comment]
@JosephMcc I'm always install the same things in all computers that i used... This is what report an HP Core 2 Desktop PC, with onboard intel graphics...

cinnamon --replace
Cjs-Message: JS LOG: About to start Cinnamon
St-Message: cogl npot texture sizes SUPPORTED
Cjs-Message: JS LOG: Cinnamon started at Tue Sep 13 2016 13:59:30 GMT-0500 (CDT)
Cjs-Message: JS LOG: network applet: Cannot find connection for active (or connection cannot be read)
openGL version 2.1 Mesa 11 detected (GL Cogl Driver)
MetaSyncRing disabled: couldn't find required GL extensions, or the minimum safe openGL version was not met
Window manager warning: Log level 16: STACK_OP_REMOVE: window 0x5a not in stack
Cjs-Message: JS LOG: Invalid network device type, is 14
Cjs-Message: JS LOG: network applet: Found connection for active

As you see, nothing about gda. gir1.2-gda packages is not installed here, but it's installed gir1.2-gdata-0.0

I will see later in the computer where i found this problems, that it's an AMD Phenom X6 with an ATI onboard cart...

Both computer have ubuntu 16.04 with the unestable ppa. The difference it's, that this computer is updated from ubuntu 14.04 and the other it's a clean installation.

It's strange what happens.

**Comment by lestcape** [comment]
@JosephMcc this is caused by this applet: https://github.com/jake-phy/WindowIconList
But i don't know why not occurs in my another computer...

Thanks.

**Comment by dodona2** [comment]
got it without the WindowIconList applet.
mint:18.1
ubuntu:18.1 (Serena)
kernel:Linux XXXX 4.4.0-57-generic
Cinnamon 3.2.7
