### ISSUE TITLE
Hidpi with multi-monitor

### ISSUE THREAD

**Issue by hidekin** [linuxmint/Cinnamon#5689]
Hi , 
I'm using a monitor in 3840x2160 and second one in 1920x1200. Is there any plan to support Hidpi only on the UHD monitor and not the second one ? Unity support that so I wondered if there was plan for that in cinnamon :D 

Thank you very much

**Comment by JosephMcc** [comment]
> Unity support that so I wondered if there was plan for that in cinnamon :D 

Really? I assume you have actually tried it and it works properly?

**Comment by hidekin** [comment]
yes I used it for a few days last time I used it, you go to displays configuration  in unity and you can scale the screen resolution per monitor.

**Comment by JosephMcc** [comment]
> I think on linux it's the only DE that support scaling per monitor, it would be nice to have it elsewhere than on unity :D

That's because X doesn't support it. Were the applications and mouse cursor properly scaled? Did gtk3 apps actually use the proper scale factor on each monitor?

**Comment by hidekin** [comment]
If I remember well it was the case or at least not noticable. 
If X doesn't support it do they already use mir in unity ? or do they scale with xrandr ?
I used this command line with xrandr in i3 and worked but it's not as good as in unity so maybe they tweak something in xrandr that I don't know about. 

xrandr --output DP-0 --primary --preferred --auto --output HDMI-0 --auto --scale 1.8x1.8 --right-of DP-0 --scale 1.5x1.5

The scaling is working but it's blurry on the lower resolution screen with xrandr. It's a lot better with unity.

**Comment by JosephMcc** [comment]
Linking this issue to the already open one asking for better HiDPI settings. Would prefer to keep them all in one place

https://github.com/linuxmint/Cinnamon/issues/3455
