### ISSUE TITLE
Nemo Unreliable

### ISSUE THREAD

**Issue by TheFunkyPresident** [linuxmint/Cinnamon#5693]
I run Cinnamon 3.0.7 on Arch Linux on a ThinkPad T450s.
The default filemanager Nemo takes up to two minutes to open and is unrealiably slow. Browsing the filesystem takes extremely long and while waiting Nemo is unresponsive.

**Comment by mainmachine** [comment]
Do you have any mapped drives or network shares in your fstab that could be slow to access and cause this behavior?

**Comment by TheFunkyPresident** [comment]
Well yes there is a network drive in fstab, that is currently inactive. I check it out and write back in minute. thanks

**Comment by TheFunkyPresident** [comment]
removing the network share from the fstab didn't solve the problem

**Comment by mainmachine** [comment]
Any  thing there that's mounted that might cause slowdown? Multiple drives, slow mechanical drives, anything like that? USB storage devices attached...?

**Comment by mainmachine** [comment]
> removing the network share from the fstab didn't solve the problem

Just to be clear, you removed (or commented) this entry, then did umount on the drive, or rebooted?

**Comment by TheFunkyPresident** [comment]
yes i removed the entry and rebooted.
i have 64gb sd card permanently attached, but i does not seem to cause the trouble.

**Comment by TheFunkyPresident** [comment]
also browsing files with the terminal or with dolphin is super fast.

**Comment by Vahan86** [comment]
I think this issue is related to Nemo and should belong here: https://github.com/linuxmint/nemo/issues

**Comment by JosephMcc** [comment]
@Vahan86 is right. This does belong on the Nemo repo that he linked. Honestly not sure this is even really a feature request or bug report but more a support forum type of question.

**Comment by mainmachine** [comment]
@JosephMcc - agreed, is more of a support question

@TheFunkyPresident - unless someone can reproduce your problem, then it can't be classed as a bug with Cinnamon (or Nemo, really). It's safe enough to purge cinnamon and reinstall, maybe that's your best bet - start again with a clean installation. Also, other GTK based DE's may have settings that conflict or interact with Cinnamon, so if you've got others installed then that might be a factor...?
