### ISSUE TITLE
Option to freeze desktop position when zoomed in

### ISSUE THREAD

**Issue by arkmch** [linuxmint/Cinnamon#5694]
I use destkop zoom to magnify small-sized wine games windows (diablo 2 and starcraft). It would be useful to be able to freeze the position of the game window after the desktop has been zoomed in. (In compiz there is an option to lock zoom area, which does the same.)

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
