### ISSUE TITLE
Hide individual tray icons

### ISSUE THREAD

**Issue by skoskav** [linuxmint/Cinnamon#5696]
![systray-skype-issue](https://cloud.githubusercontent.com/assets/6530368/18558229/9c7800c4-7b72-11e6-9131-0247b5ffec20.png)

In this case, I'm unable to hide Skype's icon from the panel. If I were to right-click it at the top of the panel, I have the option to "Remove this applet." Unfortunately this will actually remove the System Tray applet, which includes other icons like the Update Manager's.

I would like to have an option to hide each individual application icon that puts itself into the System Tray. Of course there would have to be a way to un-hide icons as well.

**Comment by JosephMcc** [comment]
Applications usually have a setting in there preferences of weather or not they use a systray icon. Why do you need to do it from the applet?

**Comment by Odyseus** [comment]
Hello, everybody.

@skoskav: You could use [Collapsible Systray applet](https://cinnamon-spices.linuxmint.com/applets/view/265). This applet is an updated and more stable version of another applet called **System Tray Collapsible**.

As a side note from a newbie (me). You have to remove the default systray applet and then place the **Collapsible Systray** applet in the panel.

**Comment by skoskav** [comment]
Ah, thank you so much. It seems to do what I wanted.

Though I still think that this feature is useful enough that it should be built in to Cinnamon. I recall both Xfce and Windows 7 being able to control the tray icons.

**Comment by lestcape** [comment]
@skoskav not, there are not south thing like that generally. 

I have not really an example or cases, but...

In my opinion, this is not possible because if the main application think that his icon is exported to the sys-tray, hi is in different state and then could work different. If we hide the icon, the main app could continue thinking that it's there...

There are not a general external behavior to prevent the main app about his systray icon are not wanted.

Regards.

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.

**Comment by carsten88** [comment]
![Image](https://github.com/user-attachments/assets/8336c81a-cd32-4ce9-9cf7-8490b48a792d)
I think this old thread still has some relevance today. Just want that intel icon gone.
