### ISSUE TITLE
cinnamon-settings doesn't exist

### ISSUE THREAD

**Issue by Newbie9999** [linuxmint/Cinnamon#5699]
When I'm choosing "settings" after click right mouse button on my menu, there's an error "can't run 'cinnamon-settings applets menu@cinnamon.org 0' (there's no such file)" or something that is translated like that (picture attached). So it is when I try to open any applets settings.
I tried 
gdb python
run /usr/bin/cinnamon-settings
but here's what I get:
(gdb) run /usr/bin/cinnamon-settings
Starting program: /usr/bin/python /usr/bin/cinnamon-settings
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/i386-linux-gnu/libthread_db.so.1".
/usr/bin/python: can't open file '/usr/bin/cinnamon-settings': [Errno 2] No such file or directory
[Inferior 1 (process 28546) exited with code 02](gdb) 

Is there a way to reinstall cinnamon-settings or something? Thanks a lot
![2016-09-18 13 03 25](https://cloud.githubusercontent.com/assets/22273240/18614891/6c28a880-7da0-11e6-9b31-d68af2928e98.png)

**Comment by mainmachine** [comment]
It's fairly safe to do a cinnamon purge and then reinstall, which should get you a clean install with your existing settings.

I don't know if this is a problem on mint, like if there are things dependent on Cinnamon - I have done this on several Ubuntu versions, where Cinnamon is installed as a secondary DE, and thus nothing in the base install would be dependent on it.

**Comment by JosephMcc** [comment]
What output do you get if you run `cinnamon-settings` from a terminal?

**Comment by Vahan86** [comment]
@JosephMcc, can we close the issue?
