### ISSUE TITLE
The size of power manager applet icon remains the same during change of panel height. 

### ISSUE THREAD

**Issue by Vahan86** [linuxmint/Cinnamon#5700]
When change the height of panel ("Allow Cinnamon to scale panel text and icons according to the panel heights" option is enabled) the icons of all panel applets are scaled besides power manager applet icon.

![untitled](https://cloud.githubusercontent.com/assets/12819058/18615234/5b1581fa-7db2-11e6-8c24-6de49900bd9a.png)

**Comment by JosephMcc** [comment]
I can reproduce this on git master.

**Comment by brownsr** [comment]
This affects much more than just the power applet, a number of other applets are also affected.  It's because of the implementation of on_panel_height_changed.  I'll pick this up.

**Comment by Vahan86** [comment]
Issue https://github.com/linuxmint/Cinnamon/issues/3292
