### ISSUE TITLE
Documentation needed

### ISSUE THREAD

**Issue by axos88** [linuxmint/Cinnamon#5702]
Need to write some javadoc here, as this class does not appear on the api documentation page currently.

https://github.com/linuxmint/Cinnamon/blob/master/js/ui/popupMenu.js#L627
https://github.com/linuxmint/Cinnamon/blob/864f632aeca48099a563aa0a8c66387d866b423e/js/ui/popupMenu.js#L627

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
