### ISSUE TITLE
LinuxMint 18: Cinnamon Crash - segfault libgdk-3

### ISSUE THREAD

**Issue by ximex** [linuxmint/Cinnamon#5704]
Hello,
I installed Linux Mint 18 with Cinnamon on my notebook.
Some days later, cinnamon crashes on startup and couldn't fix it. I got this error message in the logs if i try to restart cinnamon:

```
[  918.768192] cinnamon[3894]: segfault at e8 ip 00007f2cde8ee5b2 sp 00007ffc924
bdbb8 error 4 in libgdk-3.so.0.1800.9[7f2cde8b1000+d4000]
```

Edit:
I have an onboard intel and an extern nvidia graphics card (optimus)

**Comment by rbieb** [comment]
Same issue here.

Dell XPS 13 9350
Intel graphics, no external nvidia card. Issue happened right after logging in.

**Comment by jersten** [comment]
I too am experiencing this:

```
# journalct | grep cinnamon
Oct 22 13:50:50 j-UX305UA kernel: cinnamon[2648]: segfault at e8 ip 00007f6ac7a685b2 sp 00007fff7fe456c8 error 4 in libgdk-3.so.0.1800.9[7f6ac7a2b000+d4000]
Oct 22 13:52:01 j-UX305UA kernel: cinnamon[2748]: segfault at e8 ip 00007f8c756ef5b2 sp 00007fff01ec9728 error 4 in libgdk-3.so.0.1800.9[7f8c756b2000+d4000]
Oct 22 13:54:32 j-UX305UA kernel: cinnamon[2896]: segfault at e8 ip 00007f3bf8c305b2 sp 00007ffd2447d848 error 4 in libgdk-3.so.0.1800.9[7f3bf8bf3000+d4000]
```

~/.cinnamon/glass.log (glass.log.last is identical)
```
info t=2016-10-22T17:54:30.514Z Cinnamon.AppSystem.get_default() started in 108 ms
info t=2016-10-22T17:54:30.519Z loading user theme: /usr/share/themes/Linux Mint/cinnamon/cinnamon.css
info t=2016-10-22T17:54:30.540Z added icon directory: /usr/share/themes/Linux Mint/cinnamon
info t=2016-10-22T17:54:30.609Z PlacesManager: Updating devices
info t=2016-10-22T17:54:30.630Z loaded at Sat Oct 22 2016 13:54:30 GMT-0400 (EDT)
info t=2016-10-22T17:54:31.012Z Loaded applet menu@cinnamon.org in 380 ms
info t=2016-10-22T17:54:31.019Z Loaded applet show-desktop@cinnamon.org in 6 ms
info t=2016-10-22T17:54:31.055Z Role locked: panellauncher
info t=2016-10-22T17:54:31.055Z Loaded applet panel-launchers@cinnamon.org in 34 ms
info t=2016-10-22T17:54:31.067Z Loaded applet window-list@cinnamon.org in 11 ms
info t=2016-10-22T17:54:31.078Z Role locked: notifications
info t=2016-10-22T17:54:31.083Z Loaded applet notifications@cinnamon.org in 15 ms
info t=2016-10-22T17:54:31.106Z Loaded applet user@cinnamon.org in 22 ms
info t=2016-10-22T17:54:31.117Z Loaded applet removable-drives@cinnamon.org in 9 ms
info t=2016-10-22T17:54:31.162Z Loaded applet keyboard@cinnamon.org in 44 ms
info t=2016-10-22T17:54:31.223Z Loaded applet network@cinnamon.org in 58 ms
info t=2016-10-22T17:54:31.253Z Loaded applet sound@cinnamon.org in 29 ms
info t=2016-10-22T17:54:31.271Z Loaded applet power@cinnamon.org in 17 ms
info t=2016-10-22T17:54:31.281Z Loaded applet systray@cinnamon.org in 9 ms
info t=2016-10-22T17:54:31.300Z Loaded applet calendar@cinnamon.org in 18 ms
info t=2016-10-22T17:54:31.309Z Loaded applet windows-quick-list@cinnamon.org in 8 ms
info t=2016-10-22T17:54:31.309Z AppletManager.init() started in 679 ms
info t=2016-10-22T17:54:31.313Z Cinnamon took 936 ms to start
```

I tried what the previous user said to moved ~/.cinnamon; cinnamon still refused to start.

I should also note that I had no issues pre-update or install.

**Comment by jersten** [comment]
Ok, further update to this; I decided to `strace -f -s 10000 -p $(pidof mdm)`; and seen the following:

```
read(13, "\n(cinnamon-settings-daemon:2075): dconf-WARNING **: failed to commit changes to dconf: GDBus.Error:org.gtk.GDBus.UnmappedGError.Quark._g_2dfile_2derror_2dquark.Code17: Cannot open dconf database: invalid gvdb header\n", 256) = 216
read(13, 0x7fffd871a330, 256)           = -1 EAGAIN (Resource temporarily unavailable)
geteuid()                               = 1000
setresuid(-1, 0, -1)                    = 0
getegid()                               = 1000
setresgid(-1, 128, -1)                  = 0
select(14, [6 13], NULL, NULL, NULL)    = 1 (in [13])
geteuid()                               = 0
getegid()                               = 128
geteuid()                               = 0
setresgid(-1, 1000, -1)                 = 0
setresuid(-1, 1000, -1)                 = 0
read(13, "\n(cinnamon-settings-daemon:2075): dconf-WARNING **: failed to commit changes to dconf: GDBus.Error:org.gtk.GDBus.UnmappedGError.Quark._g_2dfile_2derror_2dquark.Code17: Cannot open dconf database: invalid gvdb header\n", 256) = 216
read(13, 0x7fffd871a330, 256)           = -1 EAGAIN (Resource temporarily unavailable)
geteuid()                               = 1000
setresuid(-1, 0, -1)                    = 0
getegid()                               = 1000
setresgid(-1, 128, -1)                  = 0
select(14, [6 13], NULL, NULL, NULL)    = 1 (in [13])
geteuid()                               = 0
getegid()                               = 128
geteuid()                               = 0
setresgid(-1, 1000, -1)                 = 0
setresuid(-1, 1000, -1)                 = 0
```

I removed dconf settings: `rm -rf ~/.config/dconf`

Cinnamon was able to start without issue.

**Comment by jersten** [comment]
After further experimenting with this; there is a bug in how cinnamon interacts with dconf. Once I've setup my configuration in cinnamon settings and rebooted cinnamon has crashed; removal of dconf fixes the issue.

**Comment by jersten** [comment]
I tried to make `user` (dconf) immutable to prevent further corruption. But, on boot dconf settings daemon maxes out CPU.

So the tldr is; dconf keeps getting corrupt somehow.

**Comment by kazaore** [comment]
I am seeing the same behaviour on a new Linux Mint 18 install on my desktop: 

````
[  826.335747] cinnamon[2200]: segfault at e8 ip 00007f4ace44e5b2 sp 00007ffdaee11688 error 4 in libgdk-3.so.0.1800.9[7f4ace411000+d4000]
[  832.831949] cinnamon[5635]: segfault at e8 ip 00007f8b472175b2 sp 00007ffeb43a3f78 error 4 in libgdk-3.so.0.1800.9[7f8b471da000+d4000]
````
I am running the 4.4.0-47 kernel and an integrated Intel video card.  

Removing the `~/.config/dconf` folder does allow cinnamon to start.

**Comment by desbma** [comment]
I am hit by this bug too, on Arch Linux with Cinnamon 3.2.1.

**Comment by Electron-libre** [comment]
Same here Arch Linux / Cinnamon ( Latest available packages ).
```
 VGA compatible controller: Intel Corporation 4th Gen Core Processor Integrated Graphics Controller (rev 06)
```

Removing ~/.config/dconf/user is a workaround until the next session.

**Comment by leigh123linux** [comment]
@Electron-libre Try deleting /run/user/1000/dconf/user (change UID to suit) as well.

**Comment by karlgray** [comment]
I had the same problem. removing ~/.config/dconf sorted it out.
I suspect it might be the temperature monitoring applet?

**Comment by tcuje** [comment]
Same issue here. Bug is triggered on shutdown or when I restore applications from the shortcut tray, especially Telegramm Desktop Client.

**Comment by desbma** [comment]
This bug is still occurring frequently on at least 2 of my systems: approximately once a month (with a boot every day or less).
I use Btrfs snapshots to restore the previous `~/.config/dconf/user` file and every times that fixes it until next occurrence.
I use Arch Linux and all packages are up to date.

Can I do something to help the developers fix it?
Post the corrupted `~/.config/dconf/user` file? 
Attach gdb when the crash occurs?

Thanks

**Comment by desbma** [comment]
With Cinnamon 3.4.x I did not reproduce the bug after months of use.

It is most likely fixed.

**Comment by Adrien-Luxey** [comment]
Bug still happens with Cinnamon 3.6.7 (though less often):

    [   41.726704] cinnamon[3910]: segfault at 18 ip 00007fc1f1dd7580 sp 00007ffd6ae9e080 error 4 in libgtk-3.so.0.1800.9[7fc1f1a42000+71a000]

Works fine after restarting Cinnamon. The bug often happens at boot, sometimes at shutdown and at random times.

Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz
VGA compatible controller: Intel Corporation Sky Lake Integrated Graphics (rev 07) (prog-if 00 [VGA controller])
Kernel 4.15.0-36-generic x86_64
