### ISSUE TITLE
Change resolution from 1920x1080 (16:9) to 800x600 (4:3) back to 1920x1080 (16:9) not working

### ISSUE THREAD

**Issue by schlegel11** [linuxmint/cinnamon#5707]
If I change the resolution in cinnamon-settings from 1920x1080 (16:9) to 800x600 (4:3) everything is working.
But if I want to change it from 800x600 (4:3) back to 1920x1080 (16:9) I get a tiled frozen cinnamon screen.
![img_20160919_143627](https://cloud.githubusercontent.com/assets/5841076/18633737/1285f718-7e7e-11e6-8642-a5ba196ebbfa.jpg)

I can only move the mouse pointer. The whole cinnamon is frozen and I have to power off the computer manually.
To resolve these issue I have to edit the "~/.config/monitors.xml" and reset the height and width tags.

I use a "Samsung P2770HD" monitor with an Intel 4600 graphics unit.

**Comment by Vahan86** [comment]
https://github.com/linuxmint/Cinnamon/issues/4072

**Comment by Vahan86** [comment]
@schlegel11, is this still an issue for you with Cinmamon 3.4?

**Comment by schlegel11** [comment]
Hi,
yep it's still an issue so I can reproduce it even with my installed cinnamon 3.4.6

**Comment by Vahan86** [comment]
@schlegel11, is this issue still relevant to Cinnamon 4.4?

**Comment by schlegel11** [comment]
@Vahan86 no the issue seems resolved in cinnamon 4.4.5.

**Comment by Vahan86** [comment]
@schlegel11, thanks for your reply.

**Comment by schlegel11** [comment]
It's the least I can do :smiley:
