### ISSUE TITLE
TeamViewer Affected Bug: 'Hidden' screen glitches on Cinnamon 3.0

### ISSUE THREAD

**Issue by feren** [linuxmint/Cinnamon#5708]
(By 'hidden', I mean that the glitches are only visible on the TeamViewer panel whilst on the victim machine, you can't see any glitches on screen whatsoever)

Basically, on TeamViewer, Cinnamon 3.0 onwards, there's a pain in the bum bug that seems to make everything disappear unless you move your mouse enough now and then, and it's not even rare either, it's quite annoying trying to deal with this bug when TeamViewer-ing Cinnamon, and it's not only feren OS affected, I've once even tried Ubuntu with a Cinnamon 3.0 PPA originally to find the same bug, here's a screenshot of somehow getting the glitch on screen without it disappearing when I try to take a screenshot: **(Notice the clipping on the folders on the desktop and also some hidden things as well (Slingshot 3rd Party was also open BTW and the panel was also visible before the bug)**
![cinnamon bug](https://cloud.githubusercontent.com/assets/11057934/18637503/878a3136-7e84-11e6-96d3-dbde9017acb1.png)

**Comment by feren** [comment]
Affects:
 - Cinnamon 3.0.X
 - Linux Mint 18 and pretty much every Ubuntu distro you can name that has Cinnamon 3.0 on it one way or another
 - TeamViewer

**Comment by JosephMcc** [comment]
Please add this to the existing bug about teamviewer and cinnamon: https://github.com/linuxmint/Cinnamon/issues/5508

**Comment by feren** [comment]
Oh ok, saw that one, but it seemed too vague and seemed almost like it was to do with File Transfer instead

**Comment by JosephMcc** [comment]
It's fine. But if there are bugs using TeamViewer with Cinnamon I would prefer to keep them all in one place instead of scattered everywhere. If someone gets the chance to look into it, it's easier to find the relevant info posted by users.
