### ISSUE TITLE
VLC Always on top not working

### ISSUE THREAD

**Issue by sandipkc7** [linuxmint/Cinnamon#5709]
I have installed Cinnamon 3.0 on Unbutu mate 16.04. The feature of VLC Always on TOP is not working anymore. When I switch to gnome, I can use this feature. Let me know if you need any information about collecting logs. I don't know how to generate logs for cinnamon.

**Comment by JosephMcc** [comment]
Not really a VLC user. Should the effect of the VLC setting be the same as when you right click the titlebar and choose "Always on top"?

**Comment by sandipkc7** [comment]
Thank you, its working with right click at Title bar.
Thank you again.
