### ISSUE TITLE
Alt + Right Click moves the whole window. Mint 18 - Sarah

### ISSUE THREAD

**Issue by peterchaula** [linuxmint/Cinnamon#5712]
I am on Mint 18 - Sarah. My IDE has a shortcut assigned to **Alt + Mouse Right  Click**. I tried looking for the shortcut to reassign it but I can't find it anywhere.

**Comment by JosephMcc** [comment]
You can choose the modifier for moving windows in Cinnamon-settings->Windows->Behavior "Special key to move and resize windows". You can even disable it completely. It does sometimes need a Cinnamon restart or log in/out to fully take effect.
