### ISSUE TITLE
Doesn't resume from hibernate when hibernate caused by lid 

### ISSUE THREAD

**Issue by thb42** [linuxmint/Cinnamon#5713]
I get the following error in my boot log when my laptop goes to hibernate by closing the lid.
**kernel: [drm:drm_framebuffer_remove [drm]] _ERROR_ failed to reset crtc ffff8800aa81f000 when fb was deleted**
 **kernel: [drm:drm_plane_force_disable [drm]] _ERROR_ failed to disable plane with busy fb**

The boot happens as usual, but instead of showing the lock screen, the display went black, like it is off, even no backlight.
This doesn't happen when I hibernate my laptop via the start menu.
This doesn't happen with other desktop environments (e.g. xfce) so I assume it is related to cinnamon.
The errors above doesn't appear in the boot log when it resumes successfully (e.g. hibernate caused by start menu).

Im running 
CPU: Intel Core i7-3520M (with integrated graphic chip) 
Arch Linux:  4.7.4-1-ARCH,
Cinnamon: cinnamon 3.0.7-1
Grapics driver: xf86-video-intel 1:2.99.917+703+g15c5ff1-1
Xorg: xorg-server 1.18.4-1

**Comment by Vahan86** [comment]
@thb42, is this still an issue for you with Cinnamon 3.4?

**Comment by thb42** [comment]
Unfortunately yes, it is still an issue. But I'm not sure wheter the error log above is related to this issue.
The last occurence of this message in my logs is from july, although my computer still has this problem. Currently im running cinnamon 3.4.6.

**Comment by leigh123linux** [comment]
The error message indicates a driver issue.
