### ISSUE TITLE
Re: USB sticks become read-only #3446

### ISSUE THREAD

**Issue by kronolio** [linuxmint/Cinnamon#5714]
Looks like it not work again. On gentoo and cinnamon 18.
USB sticks become read-only
udisks create /media/$USER/qwe123/ with root as ownership
I uncoment "user_allow_other" in /etc/fusc.conf it is not help me

**Comment by JosephMcc** [comment]
As was noted in the original issue, if this is a problem on our side in most likely belongs with Nemo https://github.com/linuxmint/nemo/issues

**Comment by pradacr** [comment]
SD cards (USB sticks) mount as read only, other users report this bug but not all people. I have to open it using "sudo nemo" every time, not good because it unlocks everything.
