### ISSUE TITLE
Invisible task bar (under fullscreen window) should not capture mouse clicks

### ISSUE THREAD

**Issue by jondo** [linuxmint/Cinnamon#5716]
I am using "FreeRDP version 1.1.0-beta1 (git n/a)" on LinuxMint 18 Cinnamon 64-Bit.

My Cinnamon desktop has an always visible task bar at the bottom, as usual.
When I now open a FreeRDP fullscreen session, this Cinnamon task bar correctly becomes hidden, but it wrongly still captures and processes the mouse events in the bottom area, as if it were on top of the RDP session.

My workaround: Setting the task bar to auto-hide. Then this bug is only triggered when I touch the lower screen border, which is still unpleasant.

I have also filed this as https://github.com/FreeRDP/FreeRDP/issues/3510, because I do not know whether FreeRDP or Cinnamon is responsible. The corresponding FreeRDP source seems to be [here](https://github.com/FreeRDP/FreeRDP/blob/90b3bf4891e426d422ddb0581560450013832e5e/client/X11/xf_window.c#L212).

**Comment by sqwish** [comment]
I am not sure if this is a related bug or a new bug, but when I have kodi running full screen on a second monitor (via HDMI on an intel gpu) the Cinnamon task bar is gone on the first monitor (my laptop screen) for that desktop and receives no mouse clicks. If I change to another desktop then the taskbar reappears and behaves as normal. Switch back to the desktop with kodi full screen on monitor two and the taskbar is still hidden. Related or a separate bug issue?

**Comment by JosephMcc** [comment]
@sqwish Out of curiosity, what OS and Cinnamon version are you running?

**Comment by sqwish** [comment]
I am using Mint 18 with Cinnamon version 3.0.7

**Comment by mtwebster** [comment]
I suspect the original issue should be fixed by this commit: https://github.com/linuxmint/muffin/commit/d78829c47400bed8b6241e3b799fa87f80be4c34 (in git master, not in a release yet)

@sqwish I don't believe this is related, can you open a new bug report?

**Comment by mtwebster** [comment]
@jondo could you go into cinnamon-settings->General, and turn *on* "Disable compositing for fullscreen windows" - does the panel still take events under your fullscreen window?

**Comment by JosephMcc** [comment]
@sqwish https://github.com/linuxmint/Cinnamon/issues/5460

**Comment by jondo** [comment]
@mtwebster, turning this option on fixes this issue for me - thank you very much!
