### ISSUE TITLE
Opensuse Tumbleweed: Cinnamon crashed when system update

### ISSUE THREAD

**Issue by wenshizhang** [linuxmint/Cinnamon#5717]
Hi,
Cinnamon version is 3.0.6, every time when system got update, cinnamon cannot start. The weird thing is I cannot find any error about desktop in syslog, they just cannot work.

**Comment by two-dogs** [comment]
https://gist.github.com/anonymous/2ddc2416120b017022934bd60fe17b80

@wenshizhang  i am also on tw, i am using the factory repo for cinnamon, not seeing issues.

X11_Cinnamon_Factory ~ http://download.opensuse.org/repositories/X11:/Cinnamon:/Factory/openSUSE_Factory/

**Comment by Vahan86** [comment]
@wenshizhang, is this still an issue for you with Cinnamon 3.4?

**Comment by two-dogs** [comment]
Still using tumbleweed with factory cinnamon repo and issue free

**Comment by clefebvre** [comment]
We believe this issue is fixed. Please test against the latest Cinnamon version (3.6). If the issue happens again, create a new issue and add a stracktrace.
