### ISSUE TITLE
printscreen - Cinnamon

### ISSUE THREAD

**Issue by autsajder** [linuxmint/cinnamon#5718]
Hi. 

On 2 different computers i coudn`t use the printscreen button in Linux Mint 18 Cinnamon. Either picture coudn`t be saved or opened.

**Comment by steebchen** [comment]
Just FYI: \` is an accent used for á or à or wrapped around words like this `to highlight code`. When using words like "do not" you should use a normal apostrophe: don't.

**Comment by icarter09** [comment]
@DevR00kie are you still experiencing this issue?

**Comment by DevR00kie** [comment]
@icarter09 I'm using Linux Mint 19.2 with Cinnamon Version 4.2.4 now. Still facing the same issue (print button does nothing although alt+print works)

**Comment by icarter09** [comment]
@DevR00kie thanks for the update.

**Comment by dandv** [comment]
@autsajder: can you clean up your OP please? Have a descriptive bug title, not just "print screen - Cinnamon". This is the Cinnamon bug tracker, no need to repeat that. Also *what about* Print Screen? No need to start with "Hi", fix the apostrophes etc.

**Comment by icarter09** [comment]
@DevR00kie are you still experiencing this issue? I'm unable to reproduce it using Mint 20.1 with Cinnamon 4.8.6. Thanks.
