### ISSUE TITLE
mintmenu: Arrows no longer work after tabbing out of the search text field

### ISSUE THREAD

**Issue by Piiit** [linuxmint/Cinnamon#5719]
Steps to reproduce:

1. Open mintmenu in Cinnamon
2. press TAB
3. try to choose an application with keyboard arrows

It does no longer work to choose apps with the keyboard. After clicking on the searchfield again, keyboard navigation works again.

**Comment by JosephMcc** [comment]
You don't need to use tab. You can simply start navigating with the arrow keys

**Comment by Piiit** [comment]
@JosephMcc Hi, I suggest to reopen this issue, because...

- It is not only the graphical issue like described in #5333
- It means generally, that if you open the menu and press incidentally the wrong button you end up in a state where keyboard navigation no longer works as intended 
- It does not matter if you need TAB or not, or if you can navigate without pressing TAB... It would have been the same bugreport if you end up in a "undefined/inconsistent navigation state" by pressing any non-ascii button on your keyboard

I suggest to ignore TAB and all other keys that are not needed to navigate with keyboard, or even better (if this is possible) to let keyboard events bubble up to Cinnamon (Xserver, or whatever tool handles those... don't know). For instance, to allow a workspace switch during an open Cinnamon menu.

**Comment by JosephMcc** [comment]
The main reason I closed it is because it is still related. What ends up happening is we have similar/related issues spread around in a bunch of different places. If someone looks into this I would prefer they can see all the issues in one go so it can be fixed properly.

In this case you might be right though so I'll reopen it.

**Comment by JosephMcc** [comment]
On git master, tab actually works but there is no highlight effect being applied to the menu items so you have no idea where you are.
