### ISSUE TITLE
Main Cinnamon Menu items scroll

### ISSUE THREAD

**Issue by fu-sen** [linuxmint/Cinnamon#5721]
When scroll through the items in the Main Cinnamon Menu,
Remain afterimage of icons and items are momentarily down.
However, the afterimage will disappear immediately.

![screenshot from 2016-09-25 11-59-18](https://cloud.githubusercontent.com/assets/5434159/18812863/1363ff88-831d-11e6-99c6-a3a95bad0ca9.jpg)

This is easy to reproduce and to slow scroll by moving the cursor to the upper and lower ends of the item.
It was confirmed by Cinnamon of Linux Mint 18 and LMDE2.

This has been reported in the Japanese forum of Linux Mint Japan,
so I was able to reproduce it, it reported bug:
http://forums.linuxmint-jp.net/viewtopic.php?t=1716 (Japanese)

**Comment by JosephMcc** [comment]
I can reproduce this on Mint18 with git master.

**Comment by JosephMcc** [comment]
Fixed by https://github.com/linuxmint/Cinnamon/commit/3e90a2c5eaf44429c2ed13b2df02ea665ed95c09
