### ISSUE TITLE
Cannot delete invalid items from the Cinnamon menu using the menu editor in Mint 18

### ISSUE THREAD

**Issue by ghost** [linuxmint/cinnamon#5722]
So I installed WINE and then installed a Windows program which placed entries in the Wine/Programs/NAME menu location.  I then uninstalled WINE and deleted the .wine folder.  Now I'm left with entries in the menu, and they cannot be deleted even though the editor claims they can be.

One of the folders cannot be deleted even though it has no subfolders or items in it because "delete" is grayed out.

The items inside the folders cannot be deleted even though "delete" is not grayed out because the button simply doesn't delete the item.  If I change the path to something valid, it will save it after clicking "OK", but then after I tell it to be deleted it will refuse to do so and when I check the path again it will have been restored to the original path.

**Comment by spicypixel-** [comment]
I know this not ideal but what's in your `~/.local/share/applications/wine `directory?

**Comment by Swiftpaw** [comment]
That immediately made those entries disappear from the menu, thanks!

Even so, obviously this is just a bug with the menu editor and should still be fixed.  I get the feeling someone might rewrite some or all of the editor soon anyway as it is clumsy and not as simple as it could be like other updated Gnome 3 apps are.

**Comment by icarter09** [comment]
@ghost are you still experiencing this issue?

**Comment by julianmacagno** [comment]
I experienced the same issue with Counter Strike 1.6 from Wine, and when I accessed the menu editor, the icon dissapeared. Maybe it reloaded the list of shortcuts and since it didn't find the CS shortcut, it didn't load it.
