### ISSUE TITLE
Network manager applet displays the unmanaged wired interfaces

### ISSUE THREAD

**Issue by artem-sidorenko** [linuxmint/Cinnamon#5726]
Observed behavior: NM applet of cinnamon displays the unmanaged interfaces, see screenshot below

[![Untitled.png](http://s9.postimg.org/pck8vunn3/Untitled.png)](http://postimg.org/image/t8xkru8mj/)

Output of nmcli:

``` bash
$ nmcli d
DEVICE      TYPE      STATE         CONNECTION 
wlp3s0      wifi      connected     Telekom    
enp0s25     ethernet  disconnected  --         
cdc-wdm2    gsm       unavailable   --         
docker0     bridge    unmanaged     --         
virbr0      bridge    unmanaged     --         
vboxnet0    ethernet  unmanaged     --         
vboxnet1    ethernet  unmanaged     --         
vboxnet2    ethernet  unmanaged     --         
vboxnet3    ethernet  unmanaged     --         
vboxnet4    ethernet  unmanaged     --         
vboxnet5    ethernet  unmanaged     --         
vboxnet6    ethernet  unmanaged     --         
vboxnet7    ethernet  unmanaged     --         
vboxnet8    ethernet  unmanaged     --         
vboxnet9    ethernet  unmanaged     --         
lo          loopback  unmanaged     --         
tun0        tun       unmanaged     --         
virbr0-nic  tun       unmanaged     --  
```

Expected behavior: NM applet of cinnamon should not display the unmanaged interfaces

Software versions:

``` bash
$ cat /etc/os-release 
NAME="Linux Mint"
VERSION="18 (Sarah)"
ID=linuxmint
ID_LIKE=ubuntu
PRETTY_NAME="Linux Mint 18"
VERSION_ID="18"
HOME_URL="http://www.linuxmint.com/"
SUPPORT_URL="http://forums.linuxmint.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/linuxmint/"
UBUNTU_CODENAME=xenial
$ dpkg -l | grep cinnamon-common
ii  cinnamon-common                               3.0.7+sarah                                all          Cinnamon desktop (Common data files)
```

Ways to reproduce:
- Install Virtualbox
- `File -> Preferences -> Network -> Host-only Networks`
- Add some networks
- Start some VM

or

`ip link add dev vm1 type veth peer name vm2`

**Comment by willydee** [comment]
Same for running a docker-compose project with many services: the list of wired connections gets longer than the screen height due to a multitude of unmanaged interfaces shown, and the only managed wired interface is off-screen and cannot be reached.

**Comment by mf-lit** [comment]
Same issue here, results in my wireless connections being pushed off the bottom of the screen

**Comment by josevavia** [comment]
Any update on this? It is especially annoying with big docker-compose projects like willydee said

**Comment by Wirone** [comment]
Cinnamon 3.6.7 on Ubuntu 16.04 here, I got this issue too. My ethernet connections' list is so long it doesn't fit on the screen and I don't see on/off control. Any chances for newer version for Xenial?

**Comment by nocive** [comment]
Unbelievable how this is still an issue in most linux distros.
With the advent of docker driven development environments this is a very serious usability issue (see screenshot) and yet nothing has been done in >3 years.

How hard can it be to, for example, add a new option to `NetworkManager.conf` similar to unmanaged-devices enabling the user to exclude interfaces from nm-applet?

![screenshot from 2018-11-07 16-18-49](https://user-images.githubusercontent.com/651121/48140336-d6be9f00-e2a8-11e8-899f-167e6018b9df.png)

- Ubuntu bug report: https://bugs.launchpad.net/ubuntu/+source/network-manager/+bug/1458322

**Comment by Wirone** [comment]
Still experiencing it on Ubuntu 18.04.

**Comment by miraculixx** [comment]
There is a Gnome shell extension that supposedly solves this. Anybody know if/how to install this with Cinnamon or MATE? https://github.com/linniksa/nm-hide-unmanaged-gnome-shell-extension

**Comment by nocive** [comment]
For those interested, there's an easy fix for the cinnamon network applet that I also shared in the ubuntu bug report: https://github.com/linuxmint/Cinnamon/commit/3e366ce3f5cfe118ae1ab594bf2ce8c7872d8b4d

**Comment by Wirone** [comment]
Today I've updated to Cinnamon 4.0 using [this tutorial](http://ubuntuhandbook.org/index.php/2018/11/install-cinnamon-desktop-4-0-ubuntu-18-04/), BUT I DON'T RECOMMEND IT. Cinnamon was unstable, some applets were not loaded, I ended up with purging apt repository, went back to Cinnamon 3.6, had to log in using Gnome, enable `embrosyn` PPA and update to 3.8 again..... :roll_eyes: And everything because I didn't see @nocive's comment.

**Comment by Wirone** [comment]
I confirm, fix from @nocive's comment works like w charm! (requires restarting user session)

THANKS!

**Comment by mtwebster** [comment]
@Wirone I can guarantee you this change was not the cause of your issues.

That fix is also flawed, there is a better fix in the latest cinnamon release (4.0.2)

**Comment by Wirone** [comment]
@mtwebster - I've added new PPA and updated Cinnamon with dependencies. Nothing more, so most probably it caused my problems.

After upgrading to 4.0 I had issue with restarting computer ("failed deactivating swap" for >10 minutes, then freezed), after restart system was working on Kubuntu and Ubuntu (not Unity). On Cinnamon I didn't have "Start" applet (windows-like), I couldn't launch some applications including software & updates, I had to purge PPA from CLI but it restored Cinnamon to 3.6 which wasn't working at all (couldn't log in, had to update from regular Ubuntu).

I'll wait for 4.0 from `embrosyn`...

**Comment by nocive** [comment]
@Wirone you're most welcome! And thank you as well for your comment, it's gratifying to know I was able to help someone else with the same problem as mine. Cheers!

**Comment by nocive** [comment]
@mtwebster it may very well be flawed but it's a very pragmatic and easy to apply fix that anyone can easily apply as opposed to, you know, updating your entire system (and potentially break it) for the sake of fixing one desktop applet.

**Comment by ntc2** [comment]
Upstream bug report: https://gitlab.freedesktop.org/NetworkManager/NetworkManager/issues/107.
