### ISSUE TITLE
GTK 3.22 breaks Cinnamon ~/Desktop re-paint

### ISSUE THREAD

**Issue by geckolinux** [linuxmint/Cinnamon#5731]
Hello, there is a really bad regression in the Cinnamon desktop with GTK 3.22 (on openSUSE Tumbleweed). I depend on the workflow of saving in-progress documents and downloads to my ~/Desktop and then working on them from there. Now, this update has completely broken the desktop icon functionality, since the Desktop (rendered with Nemo) no longer re-paints correctly. When a desktop icon is selected, the selected color remains after clicking other icons. The drag-select rectangle color also remains on the screen. I am attaching a screenshot.

The Nemo file manager in a separate window still works correctly.

I have tried with the default Adwaita GTK theme and with all of the other GTK themes I have installed, and they all act the same.

![screenshot from 2016-09-27 06-51-57](https://cloud.githubusercontent.com/assets/2692138/18876989/5f275bca-8491-11e6-84a7-5ee50ef2c911.png)

**Comment by JosephMcc** [comment]
This is a Nemo issue. Are you running the latest git builds? I thought it had been fixed.
https://github.com/linuxmint/nemo/issues/1231

**Comment by geckolinux** [comment]
@JosephMcc  Thanks for confirming. No, I'm not running git builds, openSUSE only packages the stable release, currently at 3.0.6. Would it be possible to tag a new release for Nemo? This is going to start affecting a lot of users as GTK 3.22 becomes more common.
