### ISSUE TITLE
[Feature request] Make Alt+F2 menu more usable

### ISSUE THREAD

**Issue by nullptrT** [linuxmint/Cinnamon#5732]
Cinnamon is nearly perfect for me, but I wished the Alt+F2 menu would have the functionality like in kde-plasma.

**Comment by JosephMcc** [comment]
Could you please just add to the already open feature request: https://github.com/linuxmint/Cinnamon/issues/2366

**Comment by nullptrT** [comment]
Sorry, I searched the issues for Alt+F2
