### ISSUE TITLE
Unclickable floating windows, renders but mouse register event under the window.

### ISSUE THREAD

**Issue by kolorafa** [linuxmint/cinnamon#5733]
I have a problem with 2 "non windowed" floating types rendering correctly windows.
- The floating "actual task" from Time Doctor Pro
  ![](http://kolorafa.firehost.pl/test/snapshot-2016-09-27-20-26-50.png)
- The floating TeamViewer controls that appear on the right of the screen
  ![](http://4.bp.blogspot.com/-glOnkFYrj1w/VFtmIx6AevI/AAAAAAAAUzg/KiTRBCMS-Og/s1600/teamviewer10-filebox-dropbox-etc.png)

After some random task, still unknown, they still show and render correctly, they are updated normally, but if you click on them, you are actually clicking on the window/desktop behind it.

They don't register in alt+tab, wmctrl -l, ctrl+alt+down.
They render on top on all workspaces, but the window order is like even behind desktop.
I can hide and show this Time Doctor window from main app window, and they still are "unclickable".

There is also one app that also behave somehow similar, but that window is normal window managed by window manager. The "kadu" communication app, every time I switch workspace, the window still renders on the same location, but the window is like 20px down, if you want to click any button even X to close window, you need to aim 20px down, if you hover any icon 20px down they correcty highlight.
Also every time you switch workspace the window is going 20px more down, so after 5switch it is down by 100px (i didn't count, more or less). But that might not be related, but still it's strange.

**Comment by kolorafa** [comment]
OS: Arch Antergos + Cinnamon
Cinnamon 3.0.7

Problem occur on multiple computers (all Antergos+Cinnamon).

**Comment by itzexor** [comment]
With up-to-date Arch Linux and Cinnamon git master:
I tried to reproduce the issue with the TeamViewer control window, but I couldn't. I assume the situation you hit this with is the cinnamon machine being remote controlled? If you can figure out the event that triggers this, I will try again. I did get some warnings in the log when starting and closing TeamViewer:

> Window manager warning: Window 0x6000002 (TeamViewer) sets an MWM hint indicating it isn't resizable, but sets min size 1 x 1 and max size 2147483647 x 2147483647; this doesn't make much sense.
> Window manager warning: Log level 8: meta_display_register_x_window: assertion 'g_hash_table_lookup (display->window_ids, xwindowp) == NULL' failed
> Window manager warning: Log level 8: meta_display_unregister_x_window: assertion 'g_hash_table_lookup (display->window_ids, &xwindow) != NULL' failed

I was able to reproduce the issue with Kadu controls being offset. It affects the entire window including the window chrome. Considering that it affects the chrome, I assume this probably is a muffin issue...

I didn't try Time Doctor because that requires an account.

**Comment by kolorafa** [comment]
Time Doctor and Teamviewer, i don't use it often, but it's happening 10% of times, sometimes i notice it after 1min of "opeening and closing random windows" because i was about it use it, sometimes it glitch after a few hours or days or I just notice it later ...

I might have some ideas how to try to reproduce it, i will try them more over the weekend.

**Comment by kolorafa** [comment]
Found a way to reproduce it.

I did download & run http://pinemup.sourceforge.net/

opened terminal, typed java -jar pinemup.jar

2 notes that i did store show on screen and terminal gets blured (deselected)
right after that, all my windows are unclickable, like clicking on desktop
the only way to get back to terminal is to click on the note that did show

Can you reproduce the same?
Thanks for you hard work.

**Comment by icarter09** [comment]
@kolorafa are you still experiencing this issue?

**Comment by kolorafa** [comment]
No longer using cinnamon, so can't tell, assuming it's fixed.
