### ISSUE TITLE
network-manager applet height > screen size

### ISSUE THREAD

**Issue by mythreal** [linuxmint/Cinnamon#5736]
So the network manager applet height is far greater than the screen height. No way to scroll down to see VPN setting.

I have 2 wireless cards. One external. My router is far, so I use the external one with the large antenna. There are so many connection options for both cards that the VPN on off selection is far below the screen height. Tried a `ifconfig card down` but network-manager applet keeps it populated regardless of status. I have a very large screen to. I think the best option would be to wrap each connection in a scroller and set the scrollers height = (#-of-connections / screen-height) - padding and other things like toggle buttons.

**Comment by JosephMcc** [comment]
https://github.com/linuxmint/Cinnamon/issues/5660
