### ISSUE TITLE
[REGRESSION] Cinnamon audio applet switching default input doesn't work

### ISSUE THREAD

**Issue by geckolinux** [linuxmint/cinnamon#5738]
Hello,

I have a standard fare USB headset (with separate audio device). When I try to set it as the default input source in the Cinnamon 3.0.7 audio applet, it no longer works, and I have to switch the stream using pavucontrol.

Thanks.

**Comment by Vahan86** [comment]
@geckolinux, does this issue still relevant to Cinnamon 4.2?

**Comment by geckolinux** [comment]
I'm not using Cinnamon 4.2 yet, but I haven't seen this bug for a while.
