### ISSUE TITLE
Multi-row arrangement and configurable size for indicator icons on panel

### ISSUE THREAD

**Issue by asoltesz** [linuxmint/Cinnamon#5743]
It would be great to be able to configure the indicator icons smaller than the application icons/labels to separate them more naturally (better discoverability)

Since a fully loaded desktop may have a lot of indicator icons, it would be nice if the indicator area could arrange the indicator icons into multiple rows (when the indicator icons are configured to a small size and the panel is tall). This would leave more space for the application icons/labels which comes in handy when one has a lot of applications open on a desktop.

**Comment by lestcape** [comment]
I think multi-row arrangement will be more easy after remove the boxpointer. At less for indicators it's difficult currently. Anyway, this will be break the rule of expand applets to the panel height, as is not possible with two rows. Anyway, i see this as an interesting request.

**Comment by opticyclic** [comment]
Another use case for multiple rows is to enable the date to be displayed under the time like in Windows.

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
