### ISSUE TITLE
Allow Theme-maker to make the panel go opaque when a window is maximized

### ISSUE THREAD

**Issue by feren** [linuxmint/Cinnamon#5746]
What I'm saying, is it would be nice if you can allow a Cinnamon theme author to add an option in their theme's CSS's panel section where you can make panels opaque on whatever colour it has if **windows are maximized**. Like the Windows Vista devs rightly said when they did it in Vista, making the panel opaque can reduce distractions, and even elementary OS, Chrome/Chromium OS, etc have that option in their distro(s)!

It would be nice to be able to allow the theme author to add a variable in the Panel CSS of their theme that makes the panel go opaque when a window is maximised, and given that Cinnamon is a Muffin plugin, it would be quite easy to then get when a window is maximised in Cinnamon code...

**Comment by germanfr** [comment]
I wrote an extension for this: [https://github.com/germanfr/cinnamon-transparent-panels](https://github.com/germanfr/cinnamon-transparent-panels). This can be closed.

It turns the panels transparent by itself when no maximized window is present. But the most interesting feature is that it **lets the themers** who support it to style it however they want through CSS. Also it is the **user's choice** to enable/disable it.

**Comment by feren** [comment]
No offense, but could this be possibly be discussed about as a possible pre-installed extension to Cinnamon?
