### ISSUE TITLE
Cinnamon 3.0.7 Severe Crashing

### ISSUE THREAD

**Issue by borhansci** [linuxmint/Cinnamon#5752]
Cinnamon crashing in my Linux Mint 18 to the point that everything is completely freezed and I am unable to touch anything, even opening the terminal. Crashes are random and not related to a specific event.

Here is my hardware info:

https://gist.github.com/borhansci/9b9e03c877c65b13fc15e8aec13500de

And the contents of ".xsession-errors" file:

https://gist.github.com/borhansci/5192d0483c518f0af3d1881fb751a30d

**Comment by leigh123linux** [comment]
```
(nemo:2879): GVFS-WARNING **: can't init metadata tree /home/cyber/.local/share/gvfs-metadata/root: open: Permission denied
```

Fix the ownership and perms for /home/cyber/.local/share/gvfs-metadata/root  first then post .xsession-errors file again

```
sudo chown cyber:cyber /home/cyber/.local/share/gvfs-metadata/root
chmod 600 /home/cyber/.local/share/gvfs-metadata/root
```

**Comment by borhansci** [comment]
I will try that and check if it will eliminate the problem

**Comment by leigh123linux** [comment]
Does ubuntu use /var/log//messages for system logging, if so look there for errors related to vmware.
I doubt the theme warnings in .xsession_errors related to vmware is enough to crash cinnamon.

**Comment by borhansci** [comment]
I couldn't find "/var/log/messages" file. However, I couldn't find anything interesting in "/var/log/syslog"

**Comment by borhansci** [comment]
**UPDATE**
It looks like "VMware Workstation Pro 12.5" is the cause of the crash, also, I noticed that running VMware on a separate workspace fix the issue.

**Comment by borhansci** [comment]
**UPDATE**
VMware Tools is the cause of the problem and running VMware Workstation on a separate workspace doesn't solve the issue

**Comment by clefebvre** [comment]
We believe this issue is fixed. Please test against the latest Cinnamon version (3.6). If the issue happens again, create a new issue and add a stracktrace.
