### ISSUE TITLE
The network manager applet doesn't provide captive portal detection

### ISSUE THREAD

**Issue by marmistrz** [linuxmint/cinnamon#5756]
[https://blogs.gnome.org/dcbw/2015/02/16/networkmanager-for-administrators-part-1/](This) gnome blog post claims that the Gnome Shell supports it and NM provides support for this.

**Comment by Piiit** [comment]
@marmistrz Have you tried https://launchpad.net/capnet-assist/+announcement/14440? Maybe this could be a starting point to implement this functionality...

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
