### ISSUE TITLE
AMDGPU-PRO RX4XX Black Screeen After Login

### ISSUE THREAD

**Issue by double-facepalm** [linuxmint/Cinnamon#5759]
Hi Everyone,

There is multiple users reporting black screen on AMDGPU-PRO drivers with the latest RX400 series cards.

https://forums.linuxmint.com/viewtopic.php?f=208&t=228943&hilit=amdgpu+pro+cinnamon

Mate + all other software / games work perfectly fine so I presume this is a Cinnamon bug.

Thanks in advance for fixing!

O.

**Comment by JosephMcc** [comment]
https://github.com/linuxmint/Cinnamon/issues/5698

**Comment by double-facepalm** [comment]
Could we please re-open this till it's clear whether it's a driver issue or Cinnamon bug? This case (#5759) is more generic than #5698. I find it shocking that 2 months after the official release of these cards it's still not working. I don't even know whether to blame AMD for the drivers or Cinnamon team for utter lack of response. Meanwhile, more people complain:

https://forums.linuxmint.com/viewtopic.php?f=208&t=228943&hilit=amdgpu+pro+cinnamon
