### ISSUE TITLE
[Bug?] Cinnamon crashes on login after removing all shortcuts from main panel.

### ISSUE THREAD

**Issue by fosspill** [linuxmint/Cinnamon#5760]
Hello!

Sadly I'm unable to provide a lot of information, however, I'm wondering if anyone is able to reproduce or confirm that this is a known issue:

1) Remove all shortcuts from panel one by one
2) Log in just to have cinnamon crash

**Comment by JosephMcc** [comment]
What do you mean by shortcuts?

**Comment by oleerik** [comment]
![signal](https://cloud.githubusercontent.com/assets/1491401/19104132/2c677bca-8adb-11e6-9f34-5f244f6f157d.jpeg)

These icons. If you remove the last one left cinnamon will not start again.

**Comment by JosephMcc** [comment]
Ok, the the panel launchers. Thanks for clarifying.

**Comment by Cos-mo** [comment]
I cannot confirm. I removed all applets from the panel, logged out and back in: Cinnamon runs fine.
Tested with Cinnamon 3.0.7 on LM 18.

**Comment by oleerik** [comment]
Thank you all so far.

Any tips regarding logs that might reveal what causes the crash ?

**Comment by Odyseus** [comment]
Hello, everybody.

@Cos-mo: I think that what @oleerik is talking about is removing all the launchers from inside the launchers applet and not removing all the applets from the panel.

Either way, I can't reproduce the Cinnamon crash in neither Cinnamon 2.8.6 (Mint 17.3) nor Cinnamon 3.0.7 stable and nightly (Mint 18). I removed all launchers from the launchers applet and logged off and back in. No Cinnamon crash. Then I proceeded by removing all applets from the panel, logged off and logged back in. Again, no crash.

**oleerik**, you could provide the content of the following log files:
- /home/user_name/.xsession-errors
- /home/user_name/.cinnamon/glass.log
- /var/log/syslog
- /var/log/Xorg.0.log

**Do not post the content of those files directly inside your comment.** Create a [gist](https://gist.github.com/) for each file and then post the links to those gists.

You should also post some basic information about your system. As a bare minimum, the output of the `inxi -Sx` command.

**Comment by JosephMcc** [comment]
Normally when Cinnamon crashes it will give you an idea of why .xsession-errors. That is usually the first place you want to look. You can also use something like pastebin to post the output from those files here.

**Comment by clefebvre** [comment]
We believe this issue is fixed. Please test against the latest Cinnamon version (3.6). If the issue happens again, create a new issue and add a stracktrace.
