### ISSUE TITLE
Dropbox and Mega.nz indidcators are gone in Mint 18.

### ISSUE THREAD

**Issue by alxgvr** [linuxmint/Cinnamon#5761]
Did upgrade from Linux Mint 17.3 to 18 on desktop computer via mintupgrade.
Dropbox indicator is gone from pannel.

Dropbox is running, up to date. But idicator is not displayed.
I tryed to reinstall it, turn it off and on "dropbox stop" and "dropbox start", mouse click it in Menu.
Nothing helped...

Same for Mega.nz sync client.

How to make indidcator appear again?

Cinnamon desktop.

**Comment by Odyseus** [comment]
Hello, @alxgvr.

This might be related to  [#4396](https://github.com/linuxmint/Cinnamon/issues/4396) and  [#2846](https://github.com/linuxmint/Cinnamon/issues/2846).

**Comment by alxgvr** [comment]
Oh, I am stupid... 

System tray applet was absent...
Added to the panel - now OK.

Thanks :)

**Comment by Odyseus** [comment]
> System tray applet was absent...

LOL. It can happen to anybody.

As a side note. When you solved an issue that you opened here on GitHub, you can close the issue yourself. This can help the collaborators that sometimes have to check hundred of issues.
