### ISSUE TITLE
Bug with multiple separator applets

### ISSUE THREAD

**Issue by alxgvr** [linuxmint/Cinnamon#5762]
Hi. Wanted to separate my System Tray from other aplets (like keyboard layout, sound, date...)
Added one separator from the right side. 
Then tried to add separator from the left side (at the left have window list applet). 
But Cinnamon crashed. 
After restart can not place it before System tray (at the left side). Doing this in Panel Edit Mode by hold-and-drag with mouse pointer. 
In Settings (Applets list) only one item of Spacer applet displayed, and order is not changable (in XFCE, for instance, you can rearange applets order in Settings menu)

![screenshot from 2016-10-05 01-43-58](https://cloud.githubusercontent.com/assets/19569543/19095211/3c6a39f6-8a9d-11e6-8631-79005bdb0fc3.png)

**Comment by NikoKrause** [comment]
@alxgvr 
Which window border theme are you using?

**Comment by Cos-mo** [comment]
I cannot confirm. I am able to set a separator at both sides of the tray without any crash.
I admit, this is a little bit tricky. I had to place at first the separator on the right side, than i was able to place the other one on the left side of the tray.

Tested with Cinnamon 3.0.7 on LM 18.

**Comment by alxgvr** [comment]
@NikoKrause Ambiance-Flat-Green. Controls: Mint-Y; Desktop: Mint-Y Dark.

**Comment by alxgvr** [comment]
Оk, now I have that mess... 

![screenshot from 2016-10-06 00-51-56](https://cloud.githubusercontent.com/assets/19569543/19133127/66eb4e5a-8b5f-11e6-85bf-f9a05202ed22.png)

Two dropbox icons overlap update manager icon, mega icon is out of the borders...
Applets behavior is unpredictable.

**Comment by NikoKrause** [comment]
@alxgvr 
Have you tried to reset you panels settings?
