### ISSUE TITLE
desktop icons show double when moved - Nemo bug

### ISSUE THREAD

**Issue by jlynton** [linuxmint/Cinnamon#5763]
Mint 18 cinammon.

When I move an icon on the desktop it becomes double (two of the same icon), this can, but does not always, happen with folders or files. The same happens if I move a file or folder from a folder to the desktop. The icon is doubled, it has one 'real' (active, clickable, selectable) icon, plus a 'ghost' icon that looks identical but cannot be manipulated.

Occasionally this can be fixed by selecting the desktop and pressing F5, otherwise I can only tidy up by logging out the in again.

This behaviour only occurs when dropping files onto the desktop itself, if I move a file or folder to the desktop folder in nemo, it appears correctly on the desktop.

I tried to delete ~/.config/nemo/desktop-metadata, but that did not help. I have also toggled the keep desktop icons aligned, but that did not help.

At least one other person has reported this behaviour, as can be seen at https://forums.linuxmint.com/viewtopic.php?f=208&t=229665&p=1217977#p1217977

**Comment by lestcape** [comment]
There are a possibility that two or more different programs are managing the desktop at the same time. This happens to me also some times, I'm thinking that could be in my case Nemo and Nautilus. Another possibility could be  several instances of Nemo. Nemo need to have only one instance, with several windows, but only one process.
 I think that both cases can be checked when the problem occurs, and if you see more than one process, you can kill one of them to see if this is the problem.

**Comment by jlynton** [comment]
Thank you for your reply, letscape.

I have followed your advice, and you are right, in my case there were two instances of Nemo running. I killed one of them (the one occupying less memory), and the desktop looked normal again.
This of course begs the question, "How can I stop the second instance of Nero starting?"

**Comment by jlynton** [comment]
Thank you for your reply letscape.

After some experimentation following your advice, I have found that if I use the Dropbox tray icon to open the Dropbox folder, or open a folder using the 'files' icon next to 'Menu' in the panel, or open one from 'Places' in the Menu itself, it starts a second instance of Nemo which causes the desktop icon problem. Killing the second Nemo solves it, until of course, I open a folder again using one of the described methods.

It is easy enough to kill a second Nemo, but I suppose this is a cinnamon bug that use of the panel to open a folder is spawning a second instance of Nemo, or is there a way to tell it not to?

**Comment by lestcape** [comment]
My intention was only clarify where the problem occurs, to help a little, but i think i can not help to real resolved it. This is a bug, yes apparently it's but a bug of Nemo, not Cinnamon. I hope some one with the skill in Nemo, would help to fix it.

**Comment by jlynton** [comment]
Thank you very much for your help, letscape, it has been most useful in identifying the nature of the bug! As you will see, I have edited the title to reflect this.

**Comment by JosephMcc** [comment]
Nemo bugs should really go here https://github.com/linuxmint/nemo/issues

**Comment by jcolding** [comment]
Short term solution : pkill nemo
