### ISSUE TITLE
Auto-hidden panel flashes intermittently

### ISSUE THREAD

**Issue by CottonEaster** [linuxmint/Cinnamon#5766]
I reported (issue #[5158](url=https://github.com/linuxmint/Cinnamon/issues/5158)) that my top panel, which is set to auto-hide, flashed - dropped down and back up again very quickly - intermittently on alt-tab. I closed the issue because, having uninstalled a program, the problem seemed to disappear. I spoke to soon - and the problem does not, at least now, correlate much with alt-tabbing (though it does seem to happen less often since I increased my RAM). I can't see anything in the Cinnamon or other log that seems relevant.

Mint 18 x64 Cinnamon
Kernel: 4.4.0-38-generic
Packages: 3349
Shell: /bin/bash
Resolution: 1280x800
DE: Cinnamon
WM: Mutter (Muffin)
WM Theme: NJ_desktop_theme (SimpleX-Grayscale_NJ)
Theme: Mint-Y [GTK2/3]
Icons: Paper [GTK2/3]
Font: Noto Sans UI 11 [GTK2/3]
CPU: Intel Core2 Duo T7500 (2) @ 2.2GHz
GPU: Intel Integrated Graphics
Memory: 3068MB / 7974MB

**Comment by Vahan86** [comment]
@CottonEaster, is this still an issue for you in Cinnamon 3.6?

**Comment by CottonEaster** [comment]
I am happy to say that it is not.
