### ISSUE TITLE
Chromium not showing in Window list applet

### ISSUE THREAD

**Issue by buzz** [linuxmint/Cinnamon#5767]
Sometimes, not always, when I start a Chromium session the new window is not present in the Cinnamon window list applet. It shows up in the Windows quick list applet though. Usually I start Chromium through a terminal window.

Screenshot: https://i.imgur.com/YUIs1R2.png

I can enable "Use system title bar and borders" in Chromium but it doesn't change the behaviour. Moving the window to another workspace doesn't fix it either. I can add another browser tab and move this tab out of the Chromium window so Chromium spawns another browser window. Then this new window actually shows up in the window list.

I could imagine this could be also a bug in Chromium but I'm not sure. Seems to be some kind of race condition as it randomly fails.

Chromium is the only application that does this. But I found an issue for Spotify that seems to be similar (#4858).

I see this bug already for many versions of Cinnamon.

Cinnamon 3.0.7
Chromium 53.0.2785.143 (64-bit)
Arch Linux 4.7.6 x86_64

Steps to reproduce:
* Open Chromium in console by typing `chromium <Enter>`

**Comment by itzexor** [comment]
I have the same setup, except I use cinnamon-git (from a custom version of the AUR PKGBUILDs), and I haven't seen this happen. There was a bug that caused this with Steam chat windows when it didn't set the window title quick enough, but that has been fixed for most of this year. It's probably not related to that, but when that happened there was errors in .xsession-errors (or possibly in ~/.cinnamon/glass.log) that pointed me to the cause. Is there any errors that show up when Chromium starts and doesn't show in the window list?

**Comment by buzz** [comment]
Indeed, something interesting in `.xsession-errors`:

```
Window manager warning: CurrentTime used to choose focus window; focus window may not be correct.
Window manager warning: Got a request to focus 0x3000002 (Untitled -) with a timestamp of 0.  This shouldn't happen!
```
(This is appended to `.xsession-errors` when Chromium shows in the window list.)

I had to close Chromium and start it again and the third time it didn't show in the window list. The log says:

```
Window manager warning: CurrentTime used to choose focus window; focus window may not be correct.
Window manager warning: Got a request to focus 0x3c00002 (New Tab - ) with a timestamp of 0.  This shouldn't happen!
Cjs-Message: JS LOG: Invalid or null signal handler id used when attempting to .disconnect from an object.
== Stack trace for context 0xdfecb0 ==
overrideGObject/GObject.Object.prototype.disconnect@/usr/share/cinnamon/js/ui/overrides.js:101
AppMenuButton.prototype.destroy@/usr/share/cinnamon/applets/window-list@cinnamon.org/applet.js:426
AppMenuButton.prototype.onFocus@/usr/share/cinnamon/applets/window-list@cinnamon.org/applet.js:461
MyApplet.prototype._onFocus@/usr/share/cinnamon/applets/window-list@cinnamon.org/applet.js:980

Cjs-Message: JS LOG: Invalid or null signal handler id used when attempting to .disconnect from an object.
== Stack trace for context 0xdfecb0 ==
overrideGObject/GObject.Object.prototype.disconnect@/usr/share/cinnamon/js/ui/overrides.js:101
AppMenuButton.prototype.destroy@/usr/share/cinnamon/applets/window-list@cinnamon.org/applet.js:427
AppMenuButton.prototype.onFocus@/usr/share/cinnamon/applets/window-list@cinnamon.org/applet.js:461
MyApplet.prototype._onFocus@/usr/share/cinnamon/applets/window-list@cinnamon.org/applet.js:980
```

**Comment by efournival** [comment]
Same setup as you (Arch, everything up to date) and I cannot reproduce it.

Do you have the same problem if launched from the menu rather than from a shell?

**Comment by buzz** [comment]
@efournival Yes, also happens sometimes when I start from menu.

**Comment by buzz** [comment]
But I'm using devilspie. It causes the browser window to be placed on workspace 1 upon start.
When I deactivate devilspie everything seems to work. But still a bug, right?

Are there any alternatives to devilspie on Cinnamon? I use it to automate certain tedious window management tasks like moving my browser window to workspace 1.

**Comment by buzz** [comment]
I'm closing this. Seems to be related to devilspie. I switched to devilspie2 keeping the same behaviour. Window list works for me now. Thanks.
