### ISSUE TITLE
Cinnamon unable to update from cinnamon-nightly repo; unavailable dependencies.

### ISSUE THREAD

**Issue by Co6aka** [linuxmint/Cinnamon#5768]
A few days ago Cinnamon became unable to update from the cinnamon-nightly repo: 

The following packages have been kept back:
   cinnamon (3.0.7-20161003040018-xenial => 3.0.7-20161007040011-xenial)
   cinnamon-common (3.0.7-20161003040018-xenial => 3.0.7-20161007040011-xenial)
   cinnamon-screensaver (3.1.0-20161003013004-xenial => 3.1.0-20161007013005-xenial)
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.

Unmet and unavailable depends are...
libcjs0-libmozjs-24-0
gir1.2-xapp-1.0
...neither of which are available in Xenial (Xubuntu 16.04)

**Comment by NikoKrause** [comment]
I had the same problem, but I couldn't fix it, so I downgraded to cinnamon stabile.

**Comment by itzexor** [comment]
libxapp is a new dependency for Cinnamon and I don't think it has been added to the nightly build script yet. I'm not sure about the libmozjs one, I don't think that one has been changed.

**Comment by Co6aka** [comment]
For libmozjj, I have "libmozjs-24-0v5" version "24.2.0-3ubuntu2" installed. As I wrote, Cinnamon from the nightly PPA was upgradeable/installable until a few days ago, so something was changed; check the diffs.

For libxapp, it kinda doesn't make any sense to add a new dependency without adding it to the build script and repo; ya can't install and test Cinnamon without it; sorta defeats the entire purpose. ;)

**Comment by NikoKrause** [comment]
I tried to build xapps myself. I had conflicts with xapps-common. After uninstalling them, which also uninstalled pix and ?xviewer?, I was able to install the newest xapps from github, but I still had no option to install gir1.2-xapp-1.0

I think собака is right, the ppa cinnamon nightly doesn't make much sense if it uninstalls cinnamon. At least there should be another ppa or some instructions of how to get this new libxapp.

But maybe there are some more technical difficulties, why they don't do that. I don't know.

**Comment by JosephMcc** [comment]
The cinnamon nightly ppa is clearly marked as unstable. As far as I know it is maintained by a single developer. He doesn't have to maintain or keep it working. It's a convenience for us and anyone who wants to test the latest builds. I asked him if he could add the required xapp stuff. He said he would but devs have lives too :) This should be fixed at some point.

@NikoKrause You tried building and installing this https://github.com/linuxmint/xapps

**Comment by NikoKrause** [comment]
@JosephMcc 
Yes, that's the one I tried to build. But I must say, that it was my very first library/project, I tried to build.
After running `./autogen.sh` a few times and getting rid of all the errors by installing all the needed packages, it said something like `You successfully build xapp. Now run make.`
I ran `make`. And after that `sudo checkinstall`. At his step I had some conflicts with `xapps-common`, which I deleted, along with `pix` and some other XApp-Applications.
After that `checkinstall` was able to succeed. 
Then I searched for `gir1.2-xapp` in synaptic, but there was none.

So I gave up. Like I said. It was my very first attempt on building a deb-package. And probably I have forgotten somehing or made something wrong.

**Comment by JosephMcc** [comment]
@NikoKrause 
If you are building a deb, you can run `dpkg-buildpackage` in the xapps folder. When it's done building, `cd ..` and run `sudo dpkg -i *.deb`.

**Comment by NikoKrause** [comment]
@JosephMcc 
Thanks. That worked great! Cinnamon nightly ppa is working again, after building xapps (successfully) ;)

**Comment by WandWorks** [comment]
@NikoKrause et. al., if you don't have GPG set up, you can run `sudo dpkg-buildpackage -us  -uc`

**Comment by cburlacu** [comment]
@JosephMcc Thanks for the workaround.

Still, it would be nice to work out-of-the-box :)

**Comment by belandsoft** [comment]
I can't compile this package on my Ubuntu 16.10 due to dependencies incompatibility, please can someone upload the compiled gir1.2-xapp-1.0.deb package? Thanks a lot.

**Comment by Co6aka** [comment]
**_"The cinnamon nightly ppa is clearly marked as unstable."_**

What does that have to do with any of this? An issue was/is being reported by testers of the latest development build. Are you suggesting that testers shouldn't use unstable ppas and unstable builds? Perhaps there's some valid point to that concept, but it escapes me completely.

**_"As far as I know it is maintained by a single developer. He doesn't have to maintain or keep it working."_**

Testers are people who are ALSO donating their time and effort to the cause by testing and reporting, and as you wrote "it's a convenience for us and anyone who wants to test the latest builds" so having a working ppa is important. More than one developer is working on the Cinnamon project, thus maintaining the ppa should be a project-wide concern, so why has doing so been left solely to Clem? Nobody can help him out?

**_"He said he would but devs have lives too"_**

Testers have lives too. What does this have to do with reporting of issues and resolving them? Perhaps testers should stop testing and reporting, and leave all of that work to the devs? Again, the validity escapes me.

**Comment by mainmachine** [comment]
@Co6aka - I think the point is that the ppa maintainer is the one who needs to include the additional packages (xapp) so that users of that ppa can have an easier experience.

Reporting it here will not get the ppa updated, as the ppa maintainer is not being notified here.

Can you contact the nightly ppa maintainer and request they include xapp packages in the ppa?

**Comment by mainmachine** [comment]
@Co6aka - which ppa are you using? I don't see it referenced here - is it this one: https://launchpad.net/~gwendal-lebihan-dev/+archive/ubuntu/cinnamon-nightly

**Comment by JosephMcc** [comment]
First, let me be clear. I'm not even pretending to speak for @glebihan who's ppa that is.

> Are you suggesting that testers shouldn't use unstable ppas and unstable builds? Perhaps there's some valid point to that concept, but it escapes me completely.

No, but they should realize that things won't always work as expected.

> Testers are people who are ALSO donating their time and effort to the cause by testing and reporting, and as you wrote "it's a convenience for us and anyone who wants to test the latest builds" so having a working ppa is important. More than one developer is working on the Cinnamon project, thus maintaining the ppa should be a project-wide concern, so why has doing so been left solely to Clem? Nobody can help him out?

You are obviously missing a few things here. The first is that clem has nothing to do with that PPA. It was set up and maintained by a dev who happens to work on the Mint project. As far as I know that PPA is not nor ever has been an official "Mint" thing. If he wants to continue to maintain and support it, that's totally up to him. I for one am thankful that he has for as long as he has. There are other ways to use the latest versions from git as well as easy ways to get around the current issues with the PPA.

Input from testers who use the latest builds is always welcome but really has nothing to do with the particular issue at hand.

> Testers have lives too. What does this have to do with reporting of issues and resolving them? Perhaps testers should stop testing and reporting, and leave all of that work to the devs? Again, the validity escapes me.

Again the dev who set that up doesn't have to do it. In all honesty this issue doesn't even belong here. It should be filed against the PPA since it isn't even an official thing.

**Comment by JosephMcc** [comment]
Thanks to @glebihan I believe this should be fixed now.
