### ISSUE TITLE
Settings doesn't show up in Activities or on dock

### ISSUE THREAD

**Issue by nathan-b** [linuxmint/Cinnamon#5772]
I just installed Cinnamon on Arch. When I click "Activities" on the menu, I don't get settings. When I click the power menu in the upper right and click the settings icon, nothing happens.

I can run cinnamon-settings on the command line and have the settings app appear though.

I had a previous install of Cinnamon a few months ago, so this new install may have picked something up in my homedir that led to this weird behavior.

**Comment by brownsr** [comment]
on the command line     cinnamon-settings power   may well give you a traceback.  If it does, and you can post it here, it may help.  I presume you are meaning the power applet, the settings are launched from this by clicking on 'Power Settings', not an icon.  If I am not understanding what you are doing then a screenshot would help.

**Comment by nathan-b** [comment]
It's the weirdest thing...I don't know if Cinnamon updated and changed its appearance or if my greeter was doing something weird. But now Cinnamon looks completely different and the settings app is back. I wish I could better describe what happened. I'm almost wondering if my greeter was launching another DE instead of Cinnamon somehow.

In any case, the problem is solved. Sorry for the weird bug.
