### ISSUE TITLE
[BUG] Dialog gets softlocked when choosing an image for any menu applet

### ISSUE THREAD

**Issue by feren** [linuxmint/Cinnamon#5774]
How to reproduce:
1. Try to configure 'Menu' in Cinnamon Unstable
2. Change the custom icon
3. Try to open the new icon in the dialog, the icon is now changed, but now the dialog is effectively softlocked and won't close when clicking on 'Cancel'...

**Comment by JosephMcc** [comment]
I can reproduce this. I does close using the dialogs close button though.

**Comment by feren** [comment]
For some reason, once, I was unable to close it without closing the parent window... :/

**Comment by zquestz** [comment]
Yeah and escape works too, but I can also reproduce this.

**Comment by feren** [comment]
(Fixed by Odyseus in Cinnamon 3.2.2)
