### ISSUE TITLE
[Feature Request] Allow user to change Muffin window decorator

### ISSUE THREAD

**Issue by feren** [linuxmint/Cinnamon#5775]
Unlike the other Request of changing Window Managers, this is a request to be able to change the window **decorator** in Muffin with Dconf Editor to something like Emerald or the likes if those decorators are installed for example...

**Comment by mtwebster** [comment]
Not possible with Cinnamon/Muffin

**Comment by feren** [comment]
Oh ok

**Comment by cinnamoner** [comment]
Too bad.

**Comment by feren** [comment]
@mtwebster Now thinking about it, would it be possible to add alpha to Muffin's window decorator if a theme uses transparent images/colours on its background (something similar happened with Compiz lately)
