### ISSUE TITLE
Individual Wallpaper  & Desklets Per Desktop

### ISSUE THREAD

**Issue by BrokenCanoe** [linuxmint/Cinnamon#5779]
As per other windows managers (XFCE, KDE4 etc), please allow for the setting of individual wallpapers and widgets/desklets per desktop. This allows for greater delineation between virtual desktops and their applicable workflows.

**Comment by JosephMcc** [comment]
https://github.com/linuxmint/Cinnamon/issues/1774 and https://github.com/linuxmint/Cinnamon/issues/4251
