### ISSUE TITLE
3840x1080 wallpaper loses definition upon restart

### ISSUE THREAD

**Issue by pasimko** [linuxmint/Cinnamon#5781]
I have to change the wallpaper to something different, then change it back to fix this issue.

**Comment by JosephMcc** [comment]
Could you explain what you mean by "loses definition"?

**Comment by leigh123linux** [comment]
Can you post the output for these commands

```
xrandr
```
and

```
gsettings list-recursively org.cinnamon.desktop.background
```

**Comment by pasimko** [comment]
This problem has stopped occurring. I am unsure of what caused it.
