### ISSUE TITLE
Behaviour of pointer size option in "Mouse and Touchpad" setting not working

### ISSUE THREAD

**Issue by vinf100** [linuxmint/Cinnamon#5785]
I decided to change the pointer size, but it did not work. When moving the slider, the size does not change, but when the slide reaches a certain point to the right, it changes all of a sudden, and then does not grow if moved further right. It is as if there are only two sizes, and there is only one point on the slider which triggers the change.

**Comment by leigh123linux** [comment]
I believe cursor size is theme dependent, try other themes.

**Comment by JosephMcc** [comment]
In my case when using DMZ-White or Adwaita cursor themes I get 3 different sizes.

**Comment by Odyseus** [comment]
Hello, everybody.

This isn't really a Cinnamon issue. Like **leigh123linux** said, the one responsible of setting the actual size of the cursor is the cursor theme itself. This behaviour isn't exclusive to Cinnamon, all desktop environments that I used do the same (at least XFCE, Mate and KDE do that). In fact, the cursor theme might not change the cursor size at all. Some cursor themes use the cursor size setting to pack different cursor themes in the same theme. For example, I have a cursor theme that has only three sizes, but each size has 11 (eleven) cursor themes.

![tweaked](https://cloud.githubusercontent.com/assets/3822556/19650607/433da586-99e0-11e6-8cf4-87d79031b544.gif)
