### ISSUE TITLE
Selection of items

### ISSUE THREAD

**Issue by SamBurgos** [linuxmint/Cinnamon#5787]
First of all, feel free to change the name since to be honest I don't know how to call it

**Description:** Going back to business, I am using Cinnamon 3.0.7 and after an update I saw Cinnamon on this state:

![workspace 1_032](https://cloud.githubusercontent.com/assets/1509924/19323987/9eabb7d6-907c-11e6-9bc8-33f273dad8f4.png)

When I try to select any elements on the desktop, Cinnamon leaves them on the state I put on the screenshot (I am selecting "Plantilla Recibos.ods" but I tried to select some others as well), when I select an item and try to select another one I have the following behaviour:

![workspace 1_033](https://cloud.githubusercontent.com/assets/1509924/19324026/d19f3ba4-907c-11e6-8a20-ee84d0dc2900.png)

**How to reproduce:** It was quite weird to have this, after an upgrade in which many of the packages related to GTK upgraded to version 3.22 this problem started; many of my packages were on GTK 3.20, maybe if you try to upgrade them you could see them because I am not sure if things will be the same on a fresh installation

**Information of the system:**
![system info_034](https://cloud.githubusercontent.com/assets/1509924/19324152/5b7d6aee-907d-11e6-9070-ee0b2dce6641.png)

If you need more information I can provide it, for now those are the only symptoms I have experienced so far

**Comment by leigh123linux** [comment]
If your using gtk-3.22 your hitting this issue

https://github.com/linuxmint/nemo/issues/1231

and it's fixed in nemo git (that's where this report should be).

https://github.com/linuxmint/nemo/pull/1235

**Comment by SamBurgos** [comment]
My apologies then, if you wish to close it go ahead, I never expected that this problem can be open already
