### ISSUE TITLE
Dragging an item out of Trash always ends up on Desktop

### ISSUE THREAD

**Issue by nick-s-b** [linuxmint/Cinnamon#5788]
Test system:
```
System:    Kernel: 4.4.0-42-generic x86_64 (64 bit) Desktop: Cinnamon 3.0.7   Distro: Linux Mint 18 Sarah
```

1) Drag an item into Trash (e.g. drag an item from Desktop and drop it onto Trash icon)
2) Double click on Trash icon to open it in Nemo
3) Drag the item you just deleted and drop it onto one the places in the sidebar (say Documents) to undelete it
![bug cinnamon](https://i.imgur.com/a5QS1O7.jpg)
4) Item will be moved from the Trash onto the Desktop, not Documents as the user intended

This bug is really annoying and I've misplaced few files because of it. Thankfully, it doesn't result in data loss.

**Comment by leigh123linux** [comment]
This isn't a bug, nemo will restore the file to it's original location.

**Comment by JosephMcc** [comment]
Issues with nemo should go here: https://github.com/linuxmint/nemo/issues

**Comment by leigh123linux** [comment]
@JosephMcc 

I see little point in moving the issue to nemo as gvfsd-trash controls this
