### ISSUE TITLE
resize menu-applet, when hiding favBox

### ISSUE THREAD

**Issue by NikoKrause** [linuxmint/cinnamon#5791]
(1) When hiding the favoritesBox or
(2) When favBox is hidden and you hide category/application icons

The menu does not resize the height. 
Only when you restart Cinnamon the resizing is done.

**Comment by JosephMcc** [comment]
I can't reproduce this on git master. Changing the setting to show/hide favorites resized the menu vertical size.

**Comment by NikoKrause** [comment]
Okay, I can't reproduce (2) but (1) is still valid.
A little bit more information about (1).

The favBox has to be visible, when you (re-)start Cinnamon. And the height of the categoriesBox shouldn't be higher as the height of the favBox.

So in the **left** picture you see how it looks like, when you start cinnamon and the favBox is shown.
In the **middle** picture you see how it looks like, when you hide the favoritesBox, but don't restart Cinnamon.
And in the **right** picture you see how it looks like, after you have hidden the favBox and restarted Cinnamon. The height has changed.
![bildschirmfoto vom 2016-10-24 11-44-05](https://cloud.githubusercontent.com/assets/8415124/19641357/a6c6e48c-99e0-11e6-9693-ccbc30d2f6de.png)

The menu should resize, i.e. get from left picture to right picture, without having to restart Cinnamon.


If the favBox is hidden in the first place, i.e. when you (re-)started Cinnamon, the menu resizes as it should, when you check the box for hiding/showing the favBox.

**Comment by Vahan86** [comment]
@NikoKrause, is this issue still relevant to Cinnamon 4.4?

**Comment by NikoKrause** [comment]
I still can't reproduce it, but it's not a big issue anyway. You don't hide and unhide favorites that often
