### ISSUE TITLE
[Idea] Battery percentage in the lock screen, lock screen plugins

### ISSUE THREAD

**Issue by marmistrz** [linuxmint/Cinnamon#5794]
KDE shows the battery percentage in the lock screen. Cinnamon not.

It may be good idea to do this in a modular way so that 3rd party plugins are allowed.

**Comment by anandrkris** [comment]
Cinnamon screensaver is getting revamped with some new features.
https://github.com/linuxmint/Cinnamon/issues/3369
https://github.com/linuxmint/Cinnamon/issues/3469

**Comment by anandrkris** [comment]
There seems to be a power widget as well.
https://github.com/linuxmint/cinnamon-screensaver/commit/1d24e41b919b8cdf43f2a5012c99965b87349478

**Comment by marmistrz** [comment]
It'd be nice to have the battery percentage instead of the icon (at least optionally). I'm the one of those folks who prefer a number than an icon for this ;)

**Comment by JosephMcc** [comment]
Belongs at https://github.com/linuxmint/cinnamon-screensaver
