### ISSUE TITLE
Mouse speed settings do nothing

### ISSUE THREAD

**Issue by geckolinux** [linuxmint/cinnamon#5796]
Hi, I'm running Cinnamon 3.0.7 on openSUSE Tumbleweed. The Cinnamon Control Center mouse speed settings don't work for mice. I tried it with a Logitech M310 wireless USB mouse and an older Logitech M-UAL120 wired USB  mouse, and the speed is way too fast and can't be changed via the Cinnamon control center. Using the same openSUSE Tumbleweed kernel with Gnome and and older openSUSE Leap system with KDE are successfully able to adjust the mouse speed.

The laptop's trackpad speed, on the other hand, can be successfully adjusted with Cinnamon.

Related #4343?

**Comment by HerHde** [comment]
Ahoj,
I've switched from Linux Mint 17.1 to 18.1 with Cinnamon 3.2.7 and my touchpad seems quite slow since then. The touchpad sensitivity settings make no notable difference.
Swiping from left to right for example moves my mouse only 3/4 of the screens width, but on the max setting (without acceleration) I'd expect more than the full width.

Greetings
~HerHde

**Comment by HerHde** [comment]
Okay, a new insight:
With a second display attached the touchpad speed is very high, sensitivity settings make no difference.
The relative speed seems to be the same, with one swipe the cursor moves ~3/4 of the 3520px width.

**Comment by pale2hall** [comment]
I'm having a similar issue on 18.04
Linux Mint 18.3 Sylvia  

Could the issue be an older kernel?  4.15.0-22  This is the only one that seems to run well with multiple monitors and my internal Nvidia graphics card with proprietary drivers.

**Comment by Vahan86** [comment]
@geckolinux, is this still an issue for you in Cinnamon 4.2?

**Comment by geckolinux** [comment]
I'm not using Cinnamon 4.2, but I believe it was a problem with the switch to libinput.
