### ISSUE TITLE
Ubuntu 16.10 appearance issues

### ISSUE THREAD

**Issue by belandsoft** [linuxmint/Cinnamon#5797]
After upgrading my Ubuntu from 16.04 to 16.10 I have a lot of graphical issues. All window's text area are transparent (gedit text backgorund is transparent), update-manager package details area is totally black. Most of all buttons/selector text label are fused (eg. FileEditWindowInfo), ON/OFF switching buttons inside cinnamon preferences control panel are incorrectly rendered and so on.....

**Comment by leigh123linux** [comment]
This issue sounds like a gtk mismatch with whatever theme your using.

**Comment by belandsoft** [comment]
I'm using Nadia-Dark theme. I will try with another theme and let you know.

Il ven 14 ott 2016, 10:15 leigh123linux <notifications@github.com> ha
scritto:

**Comment by Odyseus** [comment]
Hello, everybody.

 @belandsoft: Ubuntu 16.10 comes with Gnome 3.20 and some apps are based on 3.22 ([see release notes](https://wiki.ubuntu.com/YakketyYak/ReleaseNotes/UbuntuGNOME#Select_GNOME_changes_since_Ubuntu_16.04_LTS)). Cinnamon is based on Gnome 3.18 and all of its official themes only have support for 3.18 (even all of the themes published on [Spices](https://cinnamon-spices.linuxmint.com/)). You will have to use the default Adwaita or a custom theme specifically designed to work on Gnome 3.20+.

**Comment by leigh123linux** [comment]
I was referring to gtk themes, if your using gtk-3.20 then you need a theme that supports it.
If you use a gtk-3.18 based theme with gtk-3.20 you will get messed up menu bars.

![screenshot-window-2016-10-14-095823](https://cloud.githubusercontent.com/assets/1299302/19381737/f47e3426-91f4-11e6-9cd3-50fdcffa4614.png)
