### ISSUE TITLE
Applets that exist on a removed panel show as error state in Applet Settings

### ISSUE THREAD

**Issue by itzexor** [linuxmint/Cinnamon#5805]
1) ~~when removing applets that have keybinds (all applets probably, but can't easily see it with others), they aren't ever actually destroyed and can still be activated by the hotkey
   -menu applet and systray applet will no longer work properly after they have been removed once
   -applies to removing a panel as well
   -cinnamon must be restarted to fix this state~~
 -the keybind issue with the menu applet is fixed in pull request #5877, and i can no longer reproduce the systray issue

2) when applets exist in the config on panels that have been removed, they are shown as error state in applet manager and cannot be added or removed from any panels by the buttons.
   -right clicking the applet in cinnamon-settings applets does allow you to remove all instances

3) ~~there is no way to remove single instances of certain applets as they have no remove option on the applet context menu
   -applies to at least the window list and panel launchers applets~~
   -fixed in master, thanks @JosephMcc 

I have been trying to track down how to fix these issues for some time now, and I have made little to no progress so I'm opening an issue here. I'm not even sure how many of these are reproducible outside of my setup.

**Comment by itzexor** [comment]
Update on #3, there is a way to remove those applets with panel edit mode enabled. Weird that the remove option is inconsistent though when panel edit mode is off.

**Comment by Cos-mo** [comment]
At least partially I confirm:

After adding a new instance for the panel launcher applet I tried to remove it by opening the settings for this applet, selected the instance to remove and clicked the button to remove.
Now I go back to the applet dialog and open the settings for that applet again: The previously deleted instance does get shown in the dialog, although only one instance does actually exist in the panel. At the end all ever created instances remain in the settings dialog as fake instances.

Problem exists with Mint 18. In Mint 17.2 all works as expected.

**Comment by JosephMcc** [comment]
I added a couple of PR's to make it easier to remove single instances of the window list and panel launcher applets.

**Comment by JosephMcc** [comment]
Okay 3 is fixed now. Both the window list and panel launcher applets have the standard context menu items in there menus.

**Comment by itzexor** [comment]
Thanks for fixing that up, Joseph. I haven't had a chance to have a look at that yet, but it should be a lot more consistent now. Once I check it out I'll modify the main comment to better reflect the status of this issue.
