### ISSUE TITLE
New feature proposal: Percentage label in sound applet

### ISSUE THREAD

**Issue by Jackneill** [linuxmint/Cinnamon#5809]
Currently while you are adjusting the volume you can't see the exact value, only when you finished can you hover over it, so the popup label appears. It'd be nice to have a label between the sound icon and the bar indicating the volume in percentage. If the devs nod to this, i'd be interested in implementing it.

**Comment by Jackneill** [comment]
@clefebvre

**Comment by efournival** [comment]
+1

**Comment by NikoKrause** [comment]
@Jackneill 
Feel free to implement this and creating a pull request. I would like that feature.
The sound-applet is currently using an `PopupSliderMenuItem`, which is defined in `/usr/share/cinnamon/js/ui/popupMenu.js`.

You could use this as base and create a new item, e.g. call it `PopupSliderValueMenuItem`, which is the same as `PopupSliderMenuItem`, but shows the value of the slider next to the icon (as you proposed).

This new slider could also be used in the power-applet, to show the value of the brightness slider.

**Comment by NikoKrause** [comment]
@Jackneill 
Forget my previous comment. It has do be done differently.
Did you thought about something like that:
![bildschirmfoto vom 2016-10-21 17-55-13](https://cloud.githubusercontent.com/assets/8415124/19604899/a00b5e8c-97b7-11e6-875b-36d680844e7c.png)

**Comment by NikoKrause** [comment]
@mtwebster 
Could the jumping of the popup menu be prevented?
Just adding leading spaces to the `0%` till `99%` don't solve the problem, when you change the font.

**Comment by NikoKrause** [comment]
@mtwebster 
Based on your code (https://github.com/mtwebster/Cinnamonitor/blob/master/applet.js#L82) @itzexor came up with this solution https://github.com/NikoKrause/Cinnamon/commit/fec5afe3cebbbd59e71c9fa225473450fc345711

It got better, but still has some flaws with some themes, when it has to show the 100%
![bildschirmfoto vom 2016-10-23 00-50-30](https://cloud.githubusercontent.com/assets/8415124/19623045/09d2e3ea-98bb-11e6-9c4b-d1f35175ec7e.png)

Do you have any good ideas?

**Comment by mtwebster** [comment]
Disable ellipsizing:

this._outputVolumeSection.label.clutter_text.ellipsize = Pango.EllipsizeMode.NONE;

Tested on your branch, seemed to work (slider didn't resize)

**Comment by mtwebster** [comment]
Btw, it's better if this is handled all inside of the VolumeSlider class:

```
diff --git a/files/usr/share/cinnamon/applets/sound@cinnamon.org/applet.js b/files/usr/share/cinnamon/applets/sound@cinnamon.org/applet.js
index 90e4d1d..d7e9d82 100644
--- a/files/usr/share/cinnamon/applets/sound@cinnamon.org/applet.js
+++ b/files/usr/share/cinnamon/applets/sound@cinnamon.org/applet.js
@@ -108,10 +108,19 @@ VolumeSlider.prototype = {
             this.icon = new St.Icon({icon_name: this.app_icon, icon_type: St.IconType.FULLCOLOR, icon_size: 16});
         }
 
+        this.label = new St.Label({ text: "" });
+
         this.removeActor(this._slider);
         this.addActor(this.icon, {span: 0});
+        this.addActor(this.label, {span: 0});
         this.addActor(this._slider, {span: -1, expand: true});
 
+        let layout = this.label.create_pango_layout("100%");
+        let w, h;
+        [w, h] = layout.get_pixel_size();
+        this.label.set_width(w);
+        this.label.clutter_text.ellipsize = Pango.EllipsizeMode.NONE;
+
         this.connectWithStream(stream);
     },
 
@@ -167,6 +176,8 @@ VolumeSlider.prototype = {
         }
         this.setValue(value);
 
+        this.label.set_text(percentage);
+
         // send data to applet
         this.emit("values-changed", iconName, percentage);
     },
```

**Comment by NikoKrause** [comment]
@mtwebster 
Thanks for your help.
What do you think about this https://github.com/NikoKrause/Cinnamon/commit/4674615f3485a8741569c7a695cefb1016d3e619 solution?

The `%` sign for `100%` was a little bit cut off in some themes. 
This solution https://github.com/NikoKrause/Cinnamon/commit/4674615f3485a8741569c7a695cefb1016d3e619 is not perfect, but I think it looks in most of the cases better (I tried only the default themes).
But i would like to here your opinion on that, before creating a pull request.
Also do you think, it would be better, to make this feature optional or not?

**Comment by NikoKrause** [comment]
It has been discussed to remove this option _#lessoptionsforeverything_
I'm going to make a PR to revert this, but I'll reference the commits for this implementation, if some **third-party applet** developer wants to add this option in his applet (feel free to use it):

(1) initial commit: https://github.com/NikoKrause/Cinnamon/commit/4674615f3485a8741569c7a695cefb1016d3e619
(2) follow up commit to get rid of warnings: https://github.com/linuxmint/Cinnamon/commit/f9f9b23dc484b97469c5f191f586cf0717de6f45

**Comment by Vahan86** [comment]
@NikoKrause, WHY???

**Comment by NikoKrause** [comment]
There shouldn't be too many options for every little piece in Cinnamon.
Hence the discussion was either to get this feature removed or integrated by default (means adding this feature, but not as option in the settings).

I think the main reason was, that people wouldn't set the volume they need, but the volume they like the numbers of, e.g. 40, 45, ... or only even numbers. Probably for some other reasons too.

Or do you have a really good reason, why this feature is needed and why the tooltip doesn't suffice?

**Comment by Vahan86** [comment]
I agree with you that to have separate option in System Settings for this small feature is not a good idea. And I am for integrating this feature by default.

What we have for now?

![22](https://cloud.githubusercontent.com/assets/12819058/20188245/45585d48-a791-11e6-96a9-12aa9e80d831.png)

And what we can have after implementation of your feature? Something like this, right?

![333](https://cloud.githubusercontent.com/assets/12819058/20188292/77d28c62-a791-11e6-9cee-b3e79fd88105.png)

**So, for me your commit is a pure design improvement.** It's not a new option. Because we have already tooltip which shows the volume in percentage. So, sorry but your argument that "people wouldn't set the volume they need, but the volume they like the numbers of, e.g. 40, 45, ... or only even numbers" it's not so strong, because the same situation can be also now with the tooltip.

**Comment by NikoKrause** [comment]
It's not on me to decide.

**Comment by Vahan86** [comment]
@NikoKrause in any case thanks a lot for your effort. 
@clefebvre, @mtwebster, @JosephMcc, please if it possible discuss one more time before rejecting this design improvement commit (https://github.com/linuxmint/Cinnamon/issues/5809#issuecomment-259765063).

Thank you in advance.

**Comment by JosephMcc** [comment]
Speaking only for myself, I don't care weather we have that label or not. I adjust the slider to where it sounds right. That percentage has no relevance. My argument was, if it fits into the design and looks nice (which it does), either have it or not. I don't think we need every tiny thing like this to be an optional setting to turn on and off.

**Comment by NikoKrause** [comment]
That's an old picture. It looks like this:
![bildschirmfoto vom 2016-11-10 22-17-44](https://cloud.githubusercontent.com/assets/8415124/20194986/fbc71742-a794-11e6-947c-52e0194a44f1.png)

**Comment by NikoKrause** [comment]
Oh no, it's already anounced o.O
http://news.softpedia.com/news/cinnamon-3-2-desktop-environment-now-available-with-support-for-vertical-panels-510028.shtml

> support for displaying percentage next to the volume slider
