### ISSUE TITLE
Wine Taskbar Icons

### ISSUE THREAD

**Issue by kantlivelong** [linuxmint/Cinnamon#581]
Ive noticed that applications running in wine show the incorrect icon in the taskbar yet show the correct icon in other things (like AWN dock). Instead of showing the running application in wine they just show the wine glass.

**Comment by manjukirans** [comment]
This is a considerably serious issue since many people would run multiple Wine applications simultaneously. After searching a lot, and trying all the suggestions, there is still no improvement. The issue needs to be reopened.

**Comment by igordovgaluk** [comment]
the issue still not fixed Cinnamon 2.4.7,  wine-1.7.38
@mtwebster could you please reopen the issue to get the issue resolved.

**Comment by simonwiles** [comment]
Only just come across this, but I think it might be a more general issue.  I'm currently running Firefox Developer Edition along side the stable release channel, and although the `.desktop` file for Firefox-DE has the correct (blue) icon, and this works in docks, kupfer etc., the Cinnamon window-list applet still shows the theme icon for Firefox.  It ought to respect the `.desktop` file, right?  Seems to be the same problem with wine applications.

**Comment by gstavi** [comment]
Maybe that will help:

I had similar issue with Notepad++ under wine under ubuntu with gnome-desktop.
Correct Notepad++ icon would show in 'Applications' menu/launcher but Alt-Tab showed default wine icon.

The solution I found:
My Notepad++ executable is called npp.exe.
Under ~/.local/share/applications I had a shortcut called npp.desktop with reference to correct icon.

I RENAMED npp.desktop TO npp.exe.desktop AND PROBLEM SOLVED.

It seems that Alt-Tab takes the "process name" and uses it to lookup a desktop file for the icon. Make sure the desktop file name matches the process name.

Perhaps this lookup procedure should have the ability to strip common windows extensions (namely .exe) from the name.
