### ISSUE TITLE
Huge inhibit applet

### ISSUE THREAD

**Issue by germanfr** [linuxmint/Cinnamon#5810]
The inhibit applet has an entry in the menu that is bigger than the other. It goes back to normal once you click on it. It's not a theme issue because it happens with every theme. Here are some screenshots:

![screenshot from 2016-10-16 20-27-05](https://cloud.githubusercontent.com/assets/10391266/19419806/a26a0ede-93df-11e6-896b-f6cde6d96918.png)![screenshot from 2016-10-16 20-28-32]
(https://cloud.githubusercontent.com/assets/10391266/19419805/a26081c0-93df-11e6-857d-92598c708c1c.png)
_Cinnamon default theme and New-Minty theme_

The only difference my inexperienced eyes can see between the two menu items there, is that the first inherits from `PopupBaseMenuItem` (and does more things) and the second is just an instance. I don't know if that's what makes the difference.

I know this is not a priority, but it may be interesting to be fixed one day :)

Version: Cinnamon 3.0.7

**Comment by JosephMcc** [comment]
Once you click on the menu item it restores itself back to the proper size and then is fine until you resart Cinnamon again. It's something to do with the icon that sometimes show on that menu item. Removing it solves the issue. I'll see if I can figure out a fix for it.

**Comment by germanfr** [comment]
Do you mean this icon? 
![screenshot from 2016-10-17 15-53-09](https://cloud.githubusercontent.com/assets/10391266/19441565/67792dda-9486-11e6-838f-e900ad0ae2d9.png)
When it appears it seems to restore its normal size. I haven't clicked on it in the screenshot.

**Comment by JosephMcc** [comment]
Yep, that one.

**Comment by JosephMcc** [comment]
Bit of follow up. I think I have a fix for this. I'll make a PR a little later.
