### ISSUE TITLE
Awkward desktop behavior (nemo related)

### ISSUE THREAD

**Issue by telmotrooper** [linuxmint/Cinnamon#5811]
Just installed Antergos with Cinnamon 3.0.7 today and noticed an annoying issue. It's kinda hard to explain, but when I try dragging stuff around the desktop it leaves garbage behind.

Took a picture to make it easier to understand: https://i.imgur.com/IbKwYmS.png

I noticed someone already mentioned this issue in the Antergos forum ([here](https://forum.antergos.com/topic/5190/odd-desktop-behavior)) and another person replied it's a Nemo issue that has already been fixed but hasn't gone to the main branch yet. Considering that when I kill nemo the issue stops that's probably true, but I wasn't sure in which repository I should file this issue, since it directly affects Cinnamon users.

Also every time I run nemo I get these errors before the program shows up:

> (nemo:3529): Gtk-WARNING **: Theme parsing error: gtk.css:650:14: not a number
> 
> (nemo:3529): Gtk-WARNING **: Theme parsing error: gtk.css:650:14: Expected a string.
> 
> (nemo:3529): Gtk-WARNING **: Theme parsing error: gtk.css:653:17: Expected a string.
> 
> (nemo:3529): Gtk-WARNING **: Theme parsing error: gtk.css:847:14: not a number
> 
> (nemo:3529): Gtk-WARNING **: Theme parsing error: gtk.css:847:14: Expected a string.
> 
> (nemo:3529): Gtk-WARNING **: Theme parsing error: gtk.css:850:17: Expected a string.
> 
> (nemo:3529): Gtk-WARNING **: Theme parsing error: gtk.css:1238:14: not a number
> 
> (nemo:3529): Gtk-WARNING **: Theme parsing error: gtk.css:1238:14: Expected a string.
> 
> (nemo:3529): Gtk-WARNING **: Theme parsing error: gtk.css:1242:17: Expected a string.
> 
> (nemo:3529): Gtk-WARNING **: Theme parsing error: gtk.css:2776:8: not a number
> 
> (nemo:3529): Gtk-WARNING **: Theme parsing error: gtk.css:2776:18: Using Pango syntax for the > font: style property is deprecated; please use CSS syntax
> 
> (nemo:3529): Gtk-WARNING **: Theme parsing error: gtk.css:2781:8: not a number
> 
> (nemo:3529): Gtk-WARNING **: Theme parsing error: gtk.css:2781:18: Using Pango syntax for the > font: style property is deprecated; please use CSS syntax
> 
> (nemo:3529): Gtk-WARNING **: Theme parsing error: gtk.css:5700:12: not a number
> 
> (nemo:3529): Gtk-WARNING **: Theme parsing error: gtk.css:5700:12: Expected a string.
> 
> (nemo:3529): Gtk-WARNING **: Theme parsing error: gtk.css:5721:18: not a number
> 
> (nemo:3529): Gtk-WARNING **: Theme parsing error: gtk.css:5721:18: Expected a string.
> 
> (nemo:3529): Gtk-WARNING **: Theme parsing error: gtk.css:5823:12: Expected a string.
> 
> (nemo:3529): Gtk-WARNING **: Theme parsing error: gtk.css:5825:16: not a number
> 
> (nemo:3529): Gtk-WARNING **: Theme parsing error: gtk.css:5825:16: Expected a string.
> 
> (nemo:3529): Gtk-WARNING **: Theme parsing error: gtk.css:5982:12: not a number
> 
> (nemo:3529): Gtk-WARNING **: Theme parsing error: gtk.css:5982:12: Expected a string.

**Comment by JosephMcc** [comment]
https://github.com/linuxmint/nemo/issues/1316
