### ISSUE TITLE
Objects and selection box on desktop stick

### ISSUE THREAD

**Issue by ase1590** [linuxmint/Cinnamon#5812]
- When moving icons, a duplicate non-clickable image of the icon is left behind

- when the click and drag selection box is used, an image of it will be left behind

Here is a photo of what is happening:
![stuck desktop](https://cloud.githubusercontent.com/assets/4335469/19441649/038cdab8-944c-11e6-8397-cb41e6d08a78.png)

**Comment by JosephMcc** [comment]
https://github.com/linuxmint/Cinnamon/issues/5811
https://github.com/linuxmint/nemo/issues/1316
