### ISSUE TITLE
Renamable Window List Items

### ISSUE THREAD

**Issue by neilunderwood** [linuxmint/Cinnamon#5815]
Is it possible to add a feature to the Window List that allows you to right-click and rename open windows?

I have multiple remote desktop sessions open constantly.  Instead of each one reading "ScreenConnect - ...", if I could simply right-click and choose rename so that it would instead read something like "Candy's Desktop" so that when not focused I know exactly which one to click on without using expo or Alt-Tab it would be awesome.  See screenshot here for example:

![screenshot from 2016-10-18 08 50 13](https://cloud.githubusercontent.com/assets/619619/19485429/069176be-9510-11e6-835a-3608c0bb36ef.png)

Not sure if this is possible or worth the effort but it sounds awesome in my head.

**EDIT**
And I apologize if this is not the proper forum for feature requests.

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
