### ISSUE TITLE
LinuxMint18 - Cinnamon crashes when using nvidia driver

### ISSUE THREAD

**Issue by gavinB-orange** [linuxmint/Cinnamon#5817]
A brand new Mint18 install using cinnamon 3.0.7. 

Graphics:  Card: NVIDIA GM107GL [Quadro K620]
           Display Server: X.Org 1.18.4 drivers: nvidia,vesa,nouveau (unloaded: fbdev)
           Resolution: 2560x1600@0.00hz
           GLX Renderer: N/A GLX Version: N/A

If I use the recommended nvidia-361 driver (361.42-0ubuntu2) cinnamon always crashes after login.

There is no issue when using nouveau.

.xsession-errors has : 
(cinnamon-settings-daemon:2259): color-plugin-WARNING **: failed to get edid: unable to get EDID for output

(cinnamon-settings-daemon:2259): color-plugin-WARNING **: unable to get EDID for xrandr-default: unable to get EDID for output

(cinnamon-settings-daemon:2259): color-plugin-WARNING **: failed to reset xrandr-default gamma tables: gamma size is zero

(cinnamon:2387): Clutter-CRITICAL **: Unable to initialize Clutter: Unable to initialize the Clutter backend
Window manager error: Unable to initialize Clutter.
/usr/lib/blueberry/blueberry-tray.py:5: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk, Gdk, GnomeBluetooth, Gio
/usr/lib/blueberry/blueberry-tray.py:5: PyGIWarning: GnomeBluetooth was imported without specifying a version first. Use gi.require_version('GnomeBluetooth', '1.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk, Gdk, GnomeBluetooth, Gio

*\* (gnome-panel:2392): WARNING **: Failed to register client: GDBus.Error:org.gnome.SessionManager.AlreadyRegistered: Unable to register client
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
sys:1: PyGIWarning: Nemo was imported without specifying a version first. Use gi.require_version('Nemo', '3.0') before import to ensure that the right version gets loaded.

*\* (cinnamon-killer-daemon:2407): WARNING **: Binding '<Control><Alt>Escape' failed!

(gnome-panel:2392): Gtk-CRITICAL **: gtk_widget_get_preferred_height_for_width: assertion 'width >= 0' failed

(gnome-panel:2392): Gtk-WARNING **: gtk_widget_size_allocate(): attempt to allocate widget with width -1 and height 24

**Comment by leigh123linux** [comment]
You have configured nvidia wrong as you have loaded incompatible modules, you need to blacklist nouveau.


```
Display Server: X.Org 1.18.4 drivers: nvidia,vesa,nouveau (unloaded: fbdev)
```

**Comment by gavinB-orange** [comment]
Thanks for the info.

Shouldn't the driver-manager tool handle that?

**Comment by gavinB-orange** [comment]
nouveau is already blacklisted - in /etc/modprobe.d/nvidia-graphics-drivers.conf

**Comment by leigh123linux** [comment]
Blacklisting there doesn't prevent initramfs image from loading it especially when it's built in.

**Comment by unoexperto** [comment]
> Blacklisting there doesn't prevent initramfs image from loading it especially when it's built in.

@leigh123linux What is the solution then ?

**Comment by leigh123linux** [comment]
Adding modprobe.blacklist=nouveau to the kernel boot options should work for most distros

https://forums.linuxmint.com/viewtopic.php?t=238719

**Comment by leigh123linux** [comment]
Broken drivers can't be fixed within cinnamon code.
