### ISSUE TITLE
[Improvement] Better window list applet boxes width scaling

### ISSUE THREAD

**Issue by efournival** [linuxmint/Cinnamon#5819]
Following the discussion on PR #5369:

I'm suggesting an improvement over the computation of the window list applet box width.
Currently, this width is fixed (150 px), I propose to calculate it using:
- text scaling factor;
- the height of the panel IF 'allow Cinnamon to resize text and icons...' is checked in its settings.

Currently, here is how it looks on my setup:
![capture du 2016-06-11 23-57-27](https://cloud.githubusercontent.com/assets/5874026/15987660/ee838058-301f-11e6-8c84-5dddbbc7333f.png)
(definitely too narrow)

What do you think about it?
Of course, I would gladly code it.

**Comment by NikoKrause** [comment]
@efournival 
I don't see the difference. Could you show pictures, which compare the changes?

**Comment by efournival** [comment]
Sorry that wasn't clear: this is a screenshot of the situation I want to fix.
Currently, I'm hard changing the width in the code of `applet.js` as a workaround.

**Comment by NikoKrause** [comment]
Could you show your hardcoded changes against the current situation?

**Comment by efournival** [comment]
I've proposed this commit a while ago: https://github.com/linuxmint/Cinnamon/pull/5369/commits/dbcbf46767ec16ed8f58e7dfd2af7ca593a04d91

But then realized the issue is tied with my DPI settings, the text scaling parameter (mine is set to 1.2) and the fact I've modified the height of my panel.

**Comment by NikoKrause** [comment]
I think it's a matter of taste. Some like the window list smaller and some like it wider.
So just changing the fixed size is no solution.
If you want to compute the width, depending on the settings, and if the computation is well done, it could be better than a fixed size.
So it would be worth trying. But that's just my opinion.

The other solution could be to make a checkbox "Use custom width", which activates a slider to set the width. But as JosephMcc said, he's not a big fan of too much customization.
So I would give the first idea a try, before thinking about a slider.

**Comment by efournival** [comment]
Yeah of course this old proposed code is not a good solution.

However, while it looks fine without any scaling, it definitely looks too narrow when you don't have the original settings. 
That's why I'm proposing to add some scaling logic for the width too (tied to the activation of 'allow Cinnamon to resize text and icons...' in the panel settings).

**Comment by NikoKrause** [comment]
> That's why I'm proposing to add some scaling logic for the width too (tied to the activation of 'allow Cinnamon to resize text and icons...' in the panel settings).

Sounds good to me. At least I think it's worth trying.

**Comment by brownsr** [comment]
I can't reproduce this in the development version.   Or at least I can only generate something that looks something getting towards your screenshot if:

1) the window list applet is put in the left box.  
2) The exiting configuration option 'Window buttons can have different sizes and use the entire space available' is not used.

I suggest you experiment with putting the window list in the central box (turn on edit mode, drag and drop), and/or turning on this existing configuration option (right click menu on the applet).  

Let us know how it goes.

**Comment by efournival** [comment]
My setup is almost identical to the default one you can find on a regular installation of Linux Mint. In my case, I've got the default panel from a normal installation of Cinnamon under ArchLinux (last release).
I've only added some launchers right after the menu.

Here is how to reproduce it:
- text scaling 1.2
- use a custom panel size (in the panel settings)
- panel height set to almost the half of the bar
- allow Cinnamon to resize text and icons

Consequence: the window boxes are not well scaled horizontally

**Comment by JosephMcc** [comment]
> 2) The exiting configuration option 'Window buttons can have different sizes and use the entire space available' is not used.

That's more of a workaround than a real fix for the issue. That just makes the applet ugly, imho.

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.

**Comment by cweiske** [comment]
What happened to this suggestion? Was it dropped? The problem does still exist 9 years later in Debian 13 with Cinnamon 6.4.10.
