### ISSUE TITLE
menu-applet: places/recent files shown in AllApplicationsCategory bug (and solution?!)

### ISSUE THREAD

**Issue by NikoKrause** [linuxmint/Cinnamon#5820]
Try following steps:
(1) Open menu and navigate to **Places** or **Recent files** category.
(2) Close the menu, while the category from step (1) is still hovered.
(3) Open the menu again, press right and go to the very bottom of the AllApplications box. The items, which are stored in the category, which was hovered in (1), are now in the AllApplicationsCategory.

![bildschirmfoto vom 2016-10-20 20-08-44](https://cloud.githubusercontent.com/assets/8415124/19572206/a9118a8a-9701-11e6-971b-75e1ab591463.png)

This could be solved by changing `false` to `true` in this line: https://github.com/linuxmint/Cinnamon/blob/master/files/usr/share/cinnamon/applets/menu%40cinnamon.org/applet.js#L1373

Please also note, that in this line https://github.com/linuxmint/Cinnamon/blob/master/files/usr/share/cinnamon/applets/menu%40cinnamon.org/applet.js#L2533, there is no parameter given to the method `this._clearAllSelections()`.

Every other parameter, which is given to the `_clearAllSelections` methods, is set to `true`, except the one, which creates the problem, and the one, which has given no parameter at all.
Because of that I'm not sure if the parameter in the `_clearAllSelections` method is even needed.

Could someone look into this, please?

**Comment by efournival** [comment]
Which version of Cinnamon are you using?

I cannot reproduce it with Cinnamon 3.0.7 under ArchLinux.

**Comment by NikoKrause** [comment]
I tested this with Cinnamon nightly.

But this is also an issue in Cinnamon 2.8 and 3.0. stable.
In 3.0.7 stable after closing and opening the menu again, press only up (not right). Then you'll see it.

**Comment by efournival** [comment]
Reproduced!
I was performing the steps with my mouse, which seems to prevent this issue from happening.

**Comment by JosephMcc** [comment]
I can reproduce this as well.
