### ISSUE TITLE
Status area applets malfunction

### ISSUE THREAD

**Issue by marmistrz** [linuxmint/Cinnamon#5828]
I use Gajim as my XMPP client. When I change the Gajim icon theme (from within the app), its status area icon is cropped. Besides, sometimes the icon is not updated (I can't find out a rule for it)

This doesn't happen on KDE. 

Does Cinnamon use xembed for the system tray or what?

**Comment by JosephMcc** [comment]
We already have numerous issues open about the systray applet. Could you please just add your info to this one: https://github.com/linuxmint/Cinnamon/issues/481
