### ISSUE TITLE
LM18 doesn't show brightness tab in power management

### ISSUE THREAD

**Issue by x33k** [linuxmint/cinnamon#5831]
There are only two tabs in power management, "Power" & "Batteries" on my laptop. It's suppose to have a "Brightness" tab which is missing. It's seems some laptops are having this issue of detecting proper hardware. Two of my laptop is affected. Another Dell laptop is showing the tab just fine. 
I have tried clean install and update but nothing changes. I found a dirty fix in mint forum (Link: https://forums.linuxmint.com/viewtopic.php?t=208111) but this doesn't work on LM18. 

Affected system info: 
1. Asus Laptop
2. K84HR Motherboard (with latest BIOS v. 205)
3. Core i3 2.3GHz, AMD Radeon HD GPU

**Comment by JosephMcc** [comment]
I can reproduce this on my System76 oryx pro. The function keys for brightness don't work either. The following error is logged every time the media key is used:
```
(cinnamon-settings-daemon:1873): media-keys-plugin-WARNING **: Failed to get old screen percentage: GDBus.Error:org.gtk.GDBus.UnmappedGError.Quark._csd_5fpower_5fmanager_5ferror.Code0: csd-backlight-helper failed: Could not get or set the value of the backlight: No backlight devices present
```

**Comment by nephiw** [comment]
@JosephMcc the System76 Oryx Pro problem is two fold. You can fix the keyboard (and applet) problem by edit this file:  `/etc/default/grub`

I used this command: `sudo vi /etc/default/grub`

And remove this kernel flag from the `GRUB_CMDLINE_LINUX_DEFAULT`:

`acpi_backlight=vendor`

Save the file, and then run this command:

`sudo update-grub`

Then restart - your keyboard shortcuts should start working... unfortunately I have not figured out how to turn the brightness tab back on or if it is related.

**Comment by JosephMcc** [comment]
@nephiw thank you that did do the trick to get the keys working. I would like to point out that it works under Mate without this though. Which means we could probably be doing something better.

**Comment by CottonEaster** [comment]
On my system too the brightness tab - the one for dimming-on-inactivity on battery power - has suddenly disappeared, though the dimming still occurs. (Also, my laptop's special keys do work.) It may be related that NetworkManager has stopped showing any wifi-signal percentages.

Mint 18.2 on ThinkPad X1.

**Comment by CottonEaster** [comment]
The Power-Management-Brightness tab was restored when I reinstalled `xserver-xorg-video-intel'. However, I thought that Mint recommended that one _remove_ that package . .

**Comment by icarter09** [comment]
@x33k are you still experiencing this issue?

**Comment by Vahan86** [comment]
@icarter09, can we close this issue since there is no response from OP?
