### ISSUE TITLE
Polish Colemak not detected by Cinnamon Settings

### ISSUE THREAD

**Issue by marmistrz** [linuxmint/Cinnamon#5832]
Under Arch, Polish Colemak resides under: `/usr/share/X11/xkb/symbols/pl`
```
// Polish Colemak
// by Tomek Piotrowski <>
//
partial alphanumeric_keys
xkb_symbols "colemak" {
    include "us(colemak)"
    name[Group1]= "Polish (Colemak)";

    key <AB01> { [            z,            Z,       zabovedot,        Zabovedot ] };
    key <AB02> { [            x,            X, 	        zacute,           Zacute ] };
    key <AB03> { [            c,            C,          cacute,           Cacute ] };
    key <AC01> { [            a,            A,         aogonek,          Aogonek ] };
    key <AC03> { [            s,            S,          sacute,           Sacute ] };
    key <AC07> { [            n,            N,          nacute,           Nacute ] };
    key <AC08> { [            e,            E,         eogonek,          Eogonek ] };
    key <AC10> { [            o,            O,          oacute,           Oacute ] };
    key <AD07> { [            l,            L,         lstroke,          Lstroke ] };

    include "level3(ralt_switch)"
};
```

Unfortunately, it's not shown by the keyboards layout selection dialog. KDE detects it, OTOH.

**Comment by NikoKrause** [comment]
@marmistrz 
It's the same issue, which is discussed here https://github.com/linuxmint/Cinnamon/issues/5697
The **Polish (Colemak)** layout is stored in the `evdev.extras.xml` file in `/usr/share/X11/xkb/rules`.
Unfortunately right now it's not possible in Cinnamon to get the extra layouts, which are stored in this file, shown in the keyboard gui.
I had a detailed discussion with @clefebvre about this issue, which you can read in the above referenced issue.

**Comment by JosephMcc** [comment]
Could you please just add your info to the issue linked by @NikoKrause above so we can keep them all in one place.
