### ISSUE TITLE
Desktop icons hidden after external monitor unplug

### ISSUE THREAD

**Issue by r0tek** [linuxmint/cinnamon#5836]
Hi.
I am using linux mint 18 cinnamon edition (3.07 version).

I used to work on two monitors (laptop + external one).
I've noticed that when I plug off my external monitor my desktop icons are not displayed.

Even if i restart my computer, they are stilll gone.

It doesn't matter what my desktop settings are (show desktop icons on all monitors or show desktop icons on main monitor only), but I've noticed that when i change between these settings for the fragment of second i can see some of my desktop icons mixing into desktop, after that only documents (dokumenty) icon remain.

![desktop](https://cloud.githubusercontent.com/assets/18442234/19628441/21571b78-995e-11e6-8ed2-4569f3ca7ae4.png)
Desktop = Pulpit in my language

**Comment by Vahan86** [comment]
@r0tek, is this still an issue for you with Cinnamon 3.8?

**Comment by r0tek** [comment]
@Vahan86 I am currently working on mint 18.3, cinnamon 3.6.6, that is lo longer happening :)

**Comment by Vahan86** [comment]
@JosephMcc, can we close this issue?
