### ISSUE TITLE
Memory leak in Cinnamon 3.0.7?

### ISSUE THREAD

**Issue by nick-s-b** [linuxmint/Cinnamon#5843]
`Kernel: 4.4.0-45-generic x86_64 (64 bit) Desktop: Cinnamon 3.0.7   Distro: Linux Mint 18 Sarah`

Last week I noticed that cinnamon process was using 1.5GB of RAM before I restarted it. Since then, I've been logging cinnamon process and have been collecting memory usage every 5min. Here's the data if anyone's interested: http://pastebin.com/GAP8zgAv (1st column - unix time, 2nd column memory use in bytes).

Today, I've noticed that my cinnamon process is using roughly 722MB of RAM... which is on the high end given how most of the time it doesn't cross 300MB. I plotted the data with gnuplot and this is what the memory use looks like:

![Cinnamon mem use](https://i.sli.mg/bUiP53.png)

I'm not exactly sure what those steep memory jumps correspond to. I'm also not sure how to figure out what's causing this. If anyone has any suggestions or wants me to provide logs, please let me know and be specific please.

**Comment by Vahan86** [comment]
Issue https://github.com/linuxmint/Cinnamon/issues/3796

**Comment by nick-s-b** [comment]
@Vahan86 Thanks! Yeah, looks like a known issue without any real fixes.

FWIW, here's what 11 days of cinnamon memory use look like (all the data I have). Dips are reboots or cinnamon process restarts.

![cinnamon mem](https://i.sli.mg/zXCbyy.png)

**Comment by JosephMcc** [comment]
Please add your info to the existing issue.
