### ISSUE TITLE
[feature request] global menu/locally integrated menus

### ISSUE THREAD

**Issue by Gibbz** [linuxmint/Cinnamon#5846]
I love using the locally integrated menu's (or LIM) on unity due to my low res laptop screen and how much space it saves and how neat it makes the desktop. Also noticed KDE are adding them too.
Id like to put in a request to see these added to cinnamon desktop.

Screen shot here:
http://www.webupd8.org/2014/02/ubuntu-1404-gets-locally-integrated.html

I noticed this plugin add the global menu version, but not the locally integrated ones:
http://www.omgubuntu.co.uk/2016/10/global-menu-applet-linux-mint-cinnamon

Is a LIM possible with a plugin?

**Comment by JosephMcc** [comment]
Please use the search function. This has been requested before and not something we are interested in.

https://github.com/linuxmint/Cinnamon/issues/5638
https://github.com/linuxmint/Cinnamon/issues/5769

**Comment by lestcape** [comment]
Here an off-key patch for gnome shell mutter: https://github.com/jsparber/mutter-hide-legacy-decorations/blob/master/hideTitlebar.patch

So, difficult it's not. Unrelated with the cinnamon conception, yes, it's.
