### ISSUE TITLE
Tooltip overlays buttons

### ISSUE THREAD

**Issue by vlad1777d** [linuxmint/Cinnamon#5851]
Hello dear friends.

In sound applet when you place cursor on player's buttons or on volume slider, appeared tooltip overlays and hides from user much space from button, on which he pointed by cursor.

I suggest to move pinning of tooltip from left-top side of cursor to right-bottom, than it will not hide needed information from user:
![2016-10-25 22-20-02](https://cloud.githubusercontent.com/assets/12682937/19701287/687e8602-9b03-11e6-911d-d2b58eb53d0d.png)
![2016-10-25 22-20-19](https://cloud.githubusercontent.com/assets/12682937/19701286/685185c6-9b03-11e6-9d38-ec88db3ed3d3.png)

Also if you tooltip appeared, you moved cursor (and don't crossed button's borders), tooltip stays on it's place and hides many needed information:
![2016-10-25 22-39-09](https://cloud.githubusercontent.com/assets/12682937/19701502/5a8cb676-9b04-11e6-8f45-fc17f1fbddc1.png)
![2016-10-25 22-39-28](https://cloud.githubusercontent.com/assets/12682937/19701501/5a86f10a-9b04-11e6-9a03-dacc0f3e3e31.png)

If to pin tooltip to right-bottom side of cursor, than instead such last extreme case, we would get maximally such overlaying, as on first two screenshots.

System: Debian unstable x64 Cinnamon.
Cinnamon's version: 3.0.7-2 from Debian's repository.

Best regards,
Vladislav

**Comment by lestcape** [comment]
Also are behind the popup menu with the boxpointer change...
