### ISSUE TITLE
Close the lid incorrect working on Arch Linux

### ISSUE THREAD

**Issue by HamonTeacher** [linuxmint/cinnamon#5853]
**Problem 1**:
When I close the lid of my laptop - the cinnamon send the command to sleep. This happens even in the case of the ban on sleep mode when you close the lid. Even when the connected power source. This is not a system error, because on other DE all right. This problem continue 4 months. Help or tell me how to solve the problem!

**Problem 2**:
After the laptop is sent to sleep mode, when I try to Wake it up, see only a black screen (backlight turned on), but to include it for further work does not work, I have to repeatedly switch to other terminals using ctrl+alt+F1(F2-F6). But if I send to sleep mode by closing the lid while connected to a power source, even switching to other terminals can not run the image on the screen. I have to urgently restart the laptop.

**Arch Linux
Cinnamon**

**Comment by icarter09** [comment]
We believe this issue is fixed. Please test against the latest Cinnamon version (4.2). 

https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/
