### ISSUE TITLE
Counter of Items in Trash Not Updated

### ISSUE THREAD

**Issue by SerafDosSantos** [linuxmint/Cinnamon#5857]
![screenshot from 2016 10 26 15 27 23](https://cloud.githubusercontent.com/assets/3285430/19742040/49310c6e-9b91-11e6-8b94-49e9132eb7f0.png)

Noticed lately:

Once items are deleted in the trash folder, the item counter at the bottom is not updated.

Mint 18, Cinnamon 3.0.7

**Comment by JosephMcc** [comment]
This is an issue with nemo so please report it here: https://github.com/linuxmint/nemo/issues
