### ISSUE TITLE
After increasing padding-top labels are moved to top

### ISSUE THREAD

**Issue by vlad0337187** [linuxmint/cinnamon#5858]
Hello dear friends.

After increasing "padding-top", labels are moved to top, I expected that they'll move to bottom because distance from top of widget to label must be increased.
![2016-10-27 00-28-10](https://cloud.githubusercontent.com/assets/12682937/19745853/43a95b84-9bdc-11e6-987e-d0c74927fad1.png)

If I make: "padding-top: 0px;" and start increasing padding-bottom, than labels are moving to top anyway. 
If I increase both parameters - label is moving to top and distances of both parameters are added.

System: Debian unstable x64 Cinnamon.
Cinnamon's version: 3.0.7-2 from Debian's repository.

Best regards, 
Vladislav.

**Comment by JosephMcc** [comment]
I just ran into this one as well while working on updating our cinnamon themes for 3.2.

**Comment by icarter09** [comment]
@vlad0337187 are you still experiencing this issue?

**Comment by vlad0337187** [comment]
@icarter09 , no, seems, everything is well now.

**Comment by icarter09** [comment]
@vlad0337187 thanks for the update.
