### ISSUE TITLE
Desktop icons jump at (re-)start of Cinnamon, if top-panel/left-panel is used

### ISSUE THREAD

**Issue by NikoKrause** [linuxmint/Cinnamon#5863]
If you use a top-panel or a left-panel and you start/restart Cinnamon, you can see how the desktop icons jump.

At first they have the position, they would have, if you only used bottom-panel.
Then at the next moment Cinnamon remembers: "Oh wait, there is a top-panel. I have to move the desktop icons a little but down."

That's how it looks like at start (The computer icon touches the top-panel.):
![bildschirmfoto vom 2016-10-27 13-40-33](https://cloud.githubusercontent.com/assets/8415124/19765898/3568d0a8-9c4b-11e6-8ec8-fc897e6e97f4.png)

**Comment by leigh123linux** [comment]
@NikoKrause It's the wrong place for this issue, file it against nemo instead.

**Comment by NikoKrause** [comment]
Mea culpa. https://github.com/linuxmint/nemo/issues/1328
