### ISSUE TITLE
Power Managemet Applet not picking up laptop battery

### ISSUE THREAD

**Issue by johnamagee** [linuxmint/cinnamon#5864]
I'm not sure if this is a power management applet issue or a power management issue, but when I boot into my laptop and have the Logitech M510 wireless mouse receiver plugged into a USB port, the power management app/applet does not see the laptop's battery.  I then don't see the correct battery information in the applet on my task tray.  If I unplug the charging cable, the laptop battery is then seen by the system and the applet will show the correct battery information.  This happens even if the laptop isn't plugged in charging on first boot.  It will only show the M510 mouse battery, but if I plug the charger in, the battery is seen and the applet shows the correct information (shows the M510 mouse battery and the laptop battery).

Dell Inspiron 7537
Linux Mint 18 Cinnamon 3.0.7 64-bit
Linux Kernel 4.4.0-45-generic
Intel Core i7-4510U CPU

I installed the TLP battery optimization packages and the Touchpad-Indicator app.

Thanks.

**Comment by leigh123linux** [comment]
Post the output for

```
upower -d
```

**Comment by johnamagee** [comment]
Here is the output, four different scenarios.

**FIRST BOOT, CHARGER IN, MOUSE IN:**

	Device: /org/freedesktop/UPower/devices/line_power_AC
	  native-path:          AC
	  power supply:         yes
	  updated:              Fri 28 Oct 2016 07:53:21 AM CDT (78 seconds ago)
	  has history:          no
	  has statistics:       no
	  line-power
		warning-level:       none
		online:              no
		icon-name:          'ac-adapter-symbolic'

	Device: /org/freedesktop/UPower/devices/mouse_0003o046Do1025x0004
	  native-path:          /sys/devices/pci0000:00/0000:00:14.0/usb2/2-2/2-2:1.2/0003:046D:C52B.0003/0003:046D:1025.0004
	  vendor:               Logitech, Inc.
	  model:                M510
	  serial:               8CE19F7C
	  power supply:         no
	  updated:              Fri 28 Oct 2016 07:53:22 AM CDT (77 seconds ago)
	  has history:          yes
	  has statistics:       no
	  mouse
		present:             yes
		rechargeable:        yes
		state:               discharging
		warning-level:       none
		percentage:          55%
		icon-name:          'battery-good-symbolic'
	  History (charge):
		1477659202	0.000	unknown
	  History (rate):
		1477659202	0.000	unknown

	Device: /org/freedesktop/UPower/devices/DisplayDevice
	  power supply:         no
	  updated:              Fri 28 Oct 2016 07:53:22 AM CDT (77 seconds ago)
	  has history:          no
	  has statistics:       no
	  unknown
		warning-level:       none
		icon-name:          ''

	Daemon:
	  daemon-version:  0.99.4
	  on-battery:      no
	  lid-is-closed:   no
	  lid-is-present:  yes
	  critical-action: HybridSleep

**FIRST BOOT, CHARGER IN, MOUSE OUT:**

	Device: /org/freedesktop/UPower/devices/line_power_AC
	  native-path:          AC
	  power supply:         yes
	  updated:              Fri 28 Oct 2016 07:58:50 AM CDT (12 seconds ago)
	  has history:          no
	  has statistics:       no
	  line-power
		warning-level:       none
		online:              no
		icon-name:          'ac-adapter-symbolic'

	Device: /org/freedesktop/UPower/devices/DisplayDevice
	  power supply:         no
	  updated:              Fri 28 Oct 2016 07:58:50 AM CDT (12 seconds ago)
	  has history:          no
	  has statistics:       no
	  unknown
		warning-level:       none
		icon-name:          ''

	Daemon:
	  daemon-version:  0.99.4
	  on-battery:      no
	  lid-is-closed:   no
	  lid-is-present:  yes
	  critical-action: HybridSleep

**FIRST BOOT, CHARGER OUT, MOUSE IN:**

	Device: /org/freedesktop/UPower/devices/line_power_AC
	  native-path:          AC
	  power supply:         yes
	  updated:              Fri 28 Oct 2016 07:56:34 AM CDT (14 seconds ago)
	  has history:          no
	  has statistics:       no
	  line-power
		warning-level:       none
		online:              no
		icon-name:          'ac-adapter-symbolic'

	Device: /org/freedesktop/UPower/devices/mouse_0003o046Do1025x0004
	  native-path:          /sys/devices/pci0000:00/0000:00:14.0/usb2/2-2/2-2:1.2/0003:046D:C52B.0003/0003:046D:1025.0004
	  vendor:               Logitech, Inc.
	  model:                M510
	  serial:               8CE19F7C
	  power supply:         no
	  updated:              Fri 28 Oct 2016 07:56:35 AM CDT (13 seconds ago)
	  has history:          yes
	  has statistics:       no
	  mouse
		present:             no
		rechargeable:        yes
		state:               unknown
		warning-level:       none
		percentage:          0%
		icon-name:          'battery-missing-symbolic'
	  History (charge):
		1477659395	0.000	unknown
	  History (rate):
		1477659395	0.000	unknown

	Device: /org/freedesktop/UPower/devices/DisplayDevice
	  power supply:         no
	  updated:              Fri 28 Oct 2016 07:56:35 AM CDT (13 seconds ago)
	  has history:          no
	  has statistics:       no
	  unknown
		warning-level:       none
		icon-name:          ''

	Daemon:
	  daemon-version:  0.99.4
	  on-battery:      no
	  lid-is-closed:   no
	  lid-is-present:  yes
	  critical-action: HybridSleep

**FIRST BOOT, CHARGER OUT, MOUSE OUT:**

	Device: /org/freedesktop/UPower/devices/line_power_AC
	  native-path:          AC
	  power supply:         yes
	  updated:              Fri 28 Oct 2016 08:01:14 AM CDT (55 seconds ago)
	  has history:          no
	  has statistics:       no
	  line-power
		warning-level:       none
		online:              no
		icon-name:          'ac-adapter-symbolic'

	Device: /org/freedesktop/UPower/devices/DisplayDevice
	  power supply:         no
	  updated:              Fri 28 Oct 2016 08:01:14 AM CDT (55 seconds ago)
	  has history:          no
	  has statistics:       no
	  unknown
		warning-level:       none
		icon-name:          ''

	Daemon:
	  daemon-version:  0.99.4
	  on-battery:      no
	  lid-is-closed:   no
	  lid-is-present:  yes
	  critical-action: HybridSleep

**Comment by leigh123linux** [comment]
It would appear to be a upower issue as it doesn't see the battery, cinnamon uses upower to get this info.

**Comment by Vahan86** [comment]
@johnamagee, is this still an issue in Cinnamon 3.8?

**Comment by icarter09** [comment]
Please troubleshoot and find the exact cause of the problem. You can reopen the issue if the responsible component proves to be Cinnamon.

http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/
