### ISSUE TITLE
Windows List: unnecessary "[ ]" symbols in title of minimized window's item.

### ISSUE THREAD

**Issue by Vahan86** [linuxmint/Cinnamon#5865]
When the window is under the focus the title of window's item in Windows List is displayed correctly. But when the window is minimized, unnecessary [ ] symbols are added into the title of the window.

When the windows are under the focus:

![1](https://cloud.githubusercontent.com/assets/12819058/19797464/48c17d06-9cfc-11e6-85c0-42d58d71c180.png)

When the windows are minimized:

![2](https://cloud.githubusercontent.com/assets/12819058/19797697/b60c3904-9cfd-11e6-96dc-b43339119321.png)

**Comment by leigh123linux** [comment]
+1 for keeping the hidden window brackets.

**Comment by Vahan86** [comment]
Honestly, never thought that these symbols mean that the window is minimized/hidden.

**Comment by Fjodor42** [comment]
FWIW, I find the brackets extremely useful in mentally sorting windows into "open" and "minimised", so I'd be sad if they were to disappear, and do believe they are there for that exact purpose.

**Comment by JosephMcc** [comment]
This has been discussed internally before and I don't think they are going anywhere.

**Comment by andresdelfino** [comment]
I'd be interested in writing a patch for this if having this setting available as a non-default could be accepted :)

**Comment by Fjodor42** [comment]
Just chiming in again.

As stated, I rely on the brackets, bus since  I'm all for choice, I think having the brackets removed per a non-default setting would be just fine, although I don't really have any say in the matter, other than here, voicing my support.
