### ISSUE TITLE
Desktop zoom - window display size

### ISSUE THREAD

**Issue by kaefert** [linuxmint/cinnamon#5866]
When using the desktop zoom on the Cinnamon Desktop (2.8.6-1ubuntu1) on my Ubuntu 16.04 certain Windows behave badly:

A maximized mate-terminal window will only be displayed on the physical display it is maximized on, other displays that show portion of screen that without zoom where displayed on that screen display either the background or if windows are open behind this maximized mate-terminal window than those will be shown.

A firefox window will always only display exactly in the portion of display it was originally displayed on, with everything that should display outside of that area (because of the zoom) just cut away.

Also I've commented on the issue https://github.com/linuxmint/Cinnamon/issues/5163 closed because of the original reporters lack of response with an explanation how to reproduce that issue. Maybe someone with the permissions to do so can reopen it.

**Comment by Vahan86** [comment]
@kaefert, is this still an issue for you with Cinnamon 3.8?

**Comment by kaefert** [comment]
I'm sorry, I only have Cinnamon 3.6.7 on my Linux Mint 18.3 laptop, and I won't have access to my work computer with 3 physical screens on 8th of January again, but I think it's running the same desktop version.

**Comment by icarter09** [comment]
@kaefert are you still experiencing this issue? Also let me know if #5163 is still an issue and I'll reopen it. Thanks.

**Comment by kaefert** [comment]
hello @icarter09 ! Sorry but I hardly ever use Cinnamon anymore. I still have it on my office machine, but I don't remember experiencing any issues with desktop zoom on there lately.

I will check when I'm in the office next time, maybe later this week or next Tuesday by the latest - and report back then.

**Comment by icarter09** [comment]
@kaefert thanks for the update. Just whenever you can test it again would be great. Thanks.

**Comment by kaefert** [comment]
@icarter09 Okey so I just tested this issue on my Linux Mint 19.1 Cinnamon 4.0.10 Kernel 4.15.0-70 system.
I could not reproduce any of the issues described in the first post by me with firefox & mate-terminal.
