### ISSUE TITLE
OpenGL Apps Stuttering - AMDGPU-PRO RX-400 (Mint 18)

### ISSUE THREAD

**Issue by double-facepalm** [linuxmint/Cinnamon#5867]
This might be actually a driver problem - AMD admit some issues in their release notes. I've just installed AMDGPU-PRO 16.40 (RX480). It has fixed the black-screen problem which is great. However, I noticed OpenGL benchmarks don't run properly. Compared to when run under MATE, the benchmarks seem to have lower quality display output and also stutter (have micro lags). It affects both Heaven and Valley benchmarks (but it's more noticable on Heaven which runs in window mode by default). Strangely enough, the score of the benchmarks is not affected. I'll test some games too to see if gameplay is affected.

I'll also open this with AMD. Hope we'll have a fix soon so I can return to using Cinnamon. 

O.

**Comment by JosephMcc** [comment]
You can't really compare Cinnamon to Mate in these cases. One is 3d accelerated and one is not. A better comparison would be with gnome-shell.

**Comment by double-facepalm** [comment]
Why not. No matter what the technology is behind the interface the content of the window should run equally well. If Unigine Heaven runs smoothly in a window on MATE i expect the same in Gnome / Cinnamon. Whether the window and desktop is 2D or 3D should not matter.

I've just re-tested with AMDGPU-PRO 16.50, RX480, Unigine Heaven Extreme HD (Windowed). Both MATE and Cinnamon get the same result (50.6 fps) but in Cinnamon the motion stutters so if feels like the benchmark is doing 15 fps.

**Comment by leigh123linux** [comment]
There nothing we can do to compensate for crappy drivers, you will need to report it to AMD so they can investigate and fix.
