### ISSUE TITLE
(Default) Cursor theme bugs or theme choosers handling of the cursor theme

### ISSUE THREAD

**Issue by NikoKrause** [linuxmint/Cinnamon#5868]
The Cinnamon Theme Chooser doesn't handle the cursor themes properly.

The default cursor theme is DMZ-White.
If you choose another cursor theme, for example DMZ-Black, then some applications still use DMZ-White cursors.

To name an example:
You can test it with the KDE game KPatience (`apt install kpat`). (I think KDE applications in general have this problem, but I haven't tested it.) 

The steps to reproduce the bug are:
(1) Choose another cursor theme, e.g. DMZ-Black
(2) Open KPatience.
(3) If you move the mouse cursor in and out of the KPatience application, you see how the cursor changes from DMZ-black (outside the app) and DMZ-White (inside the app).

I think the source of this problem is the `default` folder in `/usr/share/icons`.
It contains a symbolic link `index.theme`, which points to `/usr/share/icons/DMZ-White/cursor.theme`.

The theme chooser should change this symbolic link, when the cursor theme was changed.

The same holds for cursor themes, which are installed locally into `~/.icons` folder.
But there it doesn't suffice to create a `default` folder in `~/.icons` and put a symbolic link into it.
The local `default` folder must contain symbolic links to the whole local cursor theme.
(Downside of that is, that the theme chooser shows a cursor theme, which is called `default`).

EDIT: I think this has to do with QT-Apps. e.g. TeXStudio has this problem too.

**Comment by leigh123linux** [comment]
This link will explain how qt gets the cursor theme.

http://www.systutorials.com/4068/configuring-mouse-cursor-style-for-qt-applications-in-gnome-mate-desktop/

In fedora we have

```
$ ls -al '/usr/share/icons/default/index.theme' 
-rw-r--r-- 1 root root 30 Feb  4  2016 /usr/share/icons/default/index.theme
```
```
cat /usr/share/icons/default/index.theme
[Icon Theme]
Inherits=Adwaita
```

creating  ~/.icons/default/index.theme and setting an override works fine (even qt5).

```
cat ~/.icons/default/index.theme
[Icon Theme]
Inherits=mate
```

**Comment by NikoKrause** [comment]
@leigh123linux 
I'm not sure if you agree with me, that this is a bug.
Or if you want to tell me, that it is not a bug.

I think the Cinnamon theme chooser should be able to handle the cursor theme, so the chosen cursor theme is shown also in QT apps.
Or do you want to tell, that this is not possible to implement?

**Comment by leigh123linux** [comment]
I disagree with this, changing theme shouldn't require root perms and would be system wide

> I think the source of this problem is the default folder in /usr/share/icons.
It contains a symbolic link index.theme, which points to /usr/share/icons/DMZ-White/cursor.theme.

> The theme chooser should change this symbolic link, when the cursor theme was changed.

I agree there is an issue setting this but any solution would need to be user only/

**Comment by NikoKrause** [comment]
Okay, now I got it. I wasn't sure about that. I just tried to explain, what the problem was, and what I thought, could be a solution.

I think you are right, that the solution should be locally/user only.

But I don't know how the theme chooser handles the cursor themes. So I hope, that somebody (with skills :) comes up with a solution for that.

**Comment by NikoKrause** [comment]
Possible solution:

```
if(cursor_theme_changes) {
    if(CURSOR_THEME is locally installed, i.e. in `~/.icons/CURSOR_THEME`) {
        create/change symbolic link:
        `ln -s ~/.icons/CURSOR_THEME ~/.icons/default`
    } else {
        create/change symbolic link: 
        `ln -s /usr/share/icons/CURSOR_THEME/cursor.theme ~/.icons/default/index.theme`
    }
}
```

**Comment by NikoKrause** [comment]
fixed by https://github.com/linuxmint/Cinnamon/commit/0d16e60d29628eee1e53b4823d8ed95c91985e55

**Comment by PS1Online** [comment]
@NikoKrause This: 0d16e60 doesn't fix the issue.
