### ISSUE TITLE
Openrc

### ISSUE THREAD

**Issue by robin0800** [linuxmint/Cinnamon#5870]
Will Cinnamon have support for "openrc" it appears to have "dbus" problems at the moment, of course works fine in "sysdemd "

**Comment by leigh123linux** [comment]
You have filed your issue against the wrong package, it's cinnamon-settings-daemon, cinnamon-session and cinnamon-screensaver that would need to have support added.
I have no interest in adding openrc support, it's not even packaged by most distro's so it's unlikely to be added by the small cinnamon dev team.

**Comment by robin0800** [comment]
Actually there is a fix for this 
gsettings set org.cinnamon.desktop.session screensaver-uses-logind false
gsettings set org.cinnamon.desktop.session session-manager-uses-logind false
gsettings set org.cinnamon.desktop.session settings-daemon-uses-logind false
