### ISSUE TITLE
Cursor size change depending of application with 4K screens

### ISSUE THREAD

**Issue by aleixmorgadas** [linuxmint/Cinnamon#5879]
Hello community.

I'm running the system with a 4K screen with a resolution to 1920x1080, with this configuration the cursor size starts to behave badly.
When the cursor is above a gnome application it becomes bigger than usual (normally toolbar), and when it's placed at body becomes a normal cursor.

I attach some pictures to see the difference
![gedit_1](https://cloud.githubusercontent.com/assets/5518197/19836924/7f479c1c-9eae-11e6-88fb-b1d63ae8f356.png)
![gedit_2](https://cloud.githubusercontent.com/assets/5518197/19836926/85532db0-9eae-11e6-985a-d62f94485d30.png)

System: Debian 8.6 x86 stable
Cinnamon version: Cinnamon 2.2.16
Laptop: Lenovo Y50 with 4K Screen

**Comment by leigh123linux** [comment]
Try

```
gsettings set org.gnome.desktop.interface scaling-factor 1
```

**Comment by aleixmorgadas** [comment]
Hello,

It doesn't solve the issue. I've used them with and without being root.

**Comment by JosephMcc** [comment]
That is a pretty old version of Cinnamon. I doubt any of the devs are running it. Version 3.2 is almost ready to go.

**Comment by aleixmorgadas** [comment]
I've installed testing packages and it has solved the issue.

Version 3.0.7-2
