### ISSUE TITLE
[Feature Request] Window Rules

### ISSUE THREAD

**Issue by feren** [linuxmint/Cinnamon#5880]
It would be neat to have a Window Rules feature similar to KDE where you can make rules for window that match certain criteria in Muffin with features such as keep window below, force on all desktops, and so on automatically to make things easier in certain situations for users.

If you want to know what I mean, get KDE, then go into System Settings in KDE > Window Management > Window Rules > Make New Rule and you'll get a feeling of this feature request in that window...

**Comment by JosephMcc** [comment]
https://github.com/linuxmint/muffin/issues/121
