### ISSUE TITLE
Cinnamon crash in g_desktop_app_info_get_is_hidden()

### ISSUE THREAD

**Issue by nathan-b** [linuxmint/Cinnamon#5882]
Seemingly randomly (I was using the menu editor to add a program to the menu), I had a cinnamon crash and restart. I'm running Arch Linux on a dual-monitor setup. I have not yet managed to reproduce the issue.

(The crash is in cinnamon-menu-e. I hope this is the correct place to report the bug.)

I've attached the stacktrace as a text file. 

Some searching found [this bug](https://bugzilla.redhat.com/show_bug.cgi?id=1359121) in the RedHat tracker, which is potentially relevant. 

[boom.txt](https://github.com/linuxmint/Cinnamon/files/562245/boom.txt)

**Comment by clefebvre** [comment]
Should be fixed by https://github.com/linuxmint/cinnamon-menus/commit/7516e8d138072d167ea93b37a2ffcbcf5b250756
