### ISSUE TITLE
Fonts just breaking

### ISSUE THREAD

**Issue by tiikeri** [linuxmint/cinnamon#5885]
No idea why or how this is happening, Mint 18. 
![screenshot from 2016-10-31 16-52-48](https://cloud.githubusercontent.com/assets/12941327/19871296/a8aa2dea-9f8a-11e6-983a-fb0b104d845d.png)

**Comment by sumanguru** [comment]
I've actually had this happen to me yesterday with no obvious reasons(Arch x64)

**Comment by sumanguru** [comment]
Now that I think of it, sometimes hovering over the text would temporarily fix it but after reboot I haven't seen it happen again

**Comment by abdupattoh** [comment]
This is happening to me too.  LM18 Cinnamon 64 / Intel Video

I tried to add a photo of it, but it is the same as shuaimiaomi's photo.  Just missing letters all over the place.  Sometimes a cinnamon restart helps, sometimes not. 

Chrome does not seem to be affected by this, other apps are.



![missing text cinnamon smalller2](https://cloud.githubusercontent.com/assets/5295899/21254015/5f623696-c384-11e6-994f-5e739e7ac14c.jpg)

**Comment by Piiit** [comment]
Have you guys tried to edit `/etc/environment` to add the following line:
```
COGL_ATLAS_DEFAULT_BLIT_MODE=framebuffer
```

Maybe this solves your problem...


I think this are some good places to start debugging this issue:
 - https://bugs.freedesktop.org/show_bug.cgi?id=88584
 - https://wiki.archlinux.org/index.php/intel_graphics#Tear-free_video <-- see Font and screen corruption in GTK+ applications (missing glyphs after suspend/resume)

**Comment by sumanguru** [comment]
The COGL_ATLAS fix didn't work for me at least. Currently trying the fix described by Arch wiki but bc the bug manifests so rarely for me it'll take a while to figure out if it works

**Comment by Vahan86** [comment]
@tiikeri, is this issue still relevant to Cinnamon 3.8?

**Comment by Vahan86** [comment]
@JosephMcc, since there is no response from OP, can we close the issue?
