### ISSUE TITLE
more privacy options

### ISSUE THREAD

**Issue by NikoKrause** [linuxmint/Cinnamon#5886]
The privacy settings could be more flexible.

It has only the option "Remember recent files"
If you turn it off, it is turned off for everything, i.e. for nemo-sidebar, menu-applet and recent-applet

Some people may want the recent files to be shown in nemo-sidebar but not in the menu-applet.

So if you turn on "Remember recent files" there should appear three more switches:
_Show remembered files in nemo-sidebar_
_Show remembered files in menu-applet_
_Show remembered files in recent-applet_

**Comment by JosephMcc** [comment]
I think it was intentionally done this way to keep it simple. It's been awhile though.

**Comment by NikoKrause** [comment]
It is simple. 

If you turn off "Remember recent files" then it should be turned off for everything as it is.
If you turn on "Remember recent files" then it should be turned on, then the three switches appear, which are turned on by default. And if somebody wants to change that, he gets the chance to do it.

**Comment by JosephMcc** [comment]
> It is simple.

Really? No kidding.

Simplicity is about more than just the user facing side of things. It's also about things that have to be added, maintained, and then worked around for future changes on the dev side. We aren't generally in the habit of adding a setting for every tiny little thing. It isn't just a matter of adding a couple of extra settings here. This same argument could be made for a lot of options we don't implement. We try to add settings/customizations where we feel they are really needed or there is a lot of demand. Keep the large majority of users happy. Our intention is not to have a KDE like level of customization.

Not saying that this couldn't or shouldn't be implemented but I've heard your "it's simple" argument too many times for a lot of different things. If we went with that every time our code would be a lot less friendly to work with.

**Comment by NikoKrause** [comment]
@JosephMcc 
> I've heard your "it's simple" argument too many times for a lot of different things. If we went with that every time our code would be a lot less friendly to work with.

I wasn't aware, that I said "it's simple" that often. I'm sorry for that. I agree with you, when you say that too much customization is not and shouldn't be the style of cinnamon.
I tried to create pull/feature requests for stuff I thought cinnamon would benefit from, which I personally would use on my own and of which I thought other users would also like.

Till now nobody complaint about that. Everybody could have told me his opinion about my work and my feature/pull requests could have been rejected. 

If I look back at my work I:
(1) added option to peek at desktop
(2) added opion to use uppercase letters in keyboard applet
(3) added icons in some context menus
(4) Tried to fix some bugs in the menu applet
(5) tried to rewrite the key-navigation code in the menu applet (in a way, which I thought would make it easier to maintain it in the future)
(6) tried to improve key-navigation and therefore added new keybindings for that
(7) used new existing mouse cursor icons for drag&drop in the menu and tried to find out if it is possible to create new ones, which would have been added to the cursor theme.
(8) added option in sound applet to show percentage besides volume slider

The new option (1) was considered by clem. He accepted it.
(2) is questionable if it is needed.
(3) as I saw it, it was already planned to add more icons in the context Menus
(4) bug fixes are a main goal, i think?
(5) and (6) is questionable, if the code is really easier to read and maintain and if I added too many keys to the key-navigation 
(7) it was definitely over the top trying to add a new cursor, which doesn't exist in every cursor theme. I didn't know before, that it would cause so much trouble. I have learned from that.
(8) that is questionable too and it's not merged yet, so still can be rejected.

As you have already noticed I still have a lot to learn and I tried to help to improve cinnamon with most of my requests. I'm not always aware, which one of my requests are hard to maintain in the long run. And I'm sorry for that.
I relied therefore, that clem, who is in charge if a new request is accepted or not, would stop me, if I would have done something stupid or if I added unneccessary options. I think I shouldn't rely on that in the future.

And my other reports were suggestions/ideas of what I thought was worth to discuss about and what I thought could might wake your interest. And I'm also sorry if I brought something up, what wasn't worth a discussion.

And when I brought up the simple argument it wasn't my intention to say,  that it is simple to implement and to maintain. I know it is not, because I also failed often, if I tried to do something. The reason why I started here, was because I used and liked Cinnamon a lot and wanted to give something back. Also I wanted to improve my programming skills in a project, which is actually used. And I learned a lot from you and everyone else here. I'm sorry if I annoyed you or somebody else with my questions and my lack of knowledge.

Sometimes when I think about how I would implement a feature, I think that's too hard for me. Sometimes I think, that is easy to do. Sometimes it is, but sometimes it isn't, because I ran into problems I haven't thought about or because it didn't worked as I expected. 
In this case I thought it would be easy to implement. And with that I didn't wanted to say, that it should be implemented. That was something I wanted to discuss beforehand. I wanted to get opinions about it, if it's something cinnamon would benefit from or if it's something, what would speak against the (KISS)policy of cinnamon. I thought creating an issue request here would have been the right place.

**Comment by JosephMcc** [comment]
First let me apologize for my communication skills or lack thereof. The "it's simple" thing wasn't targeted at you specifically. It's something that has been said by a lot of people over time. This is the place to discuss ideas and suggestions and feel free to do so. Most of that comment was just commentary on our approach to things and why some things don't get implemented even if they seem straightforward at first.

Second, don't let any of my comments discourage you. Your contributions and work are very welcome. It's always nice to see new people contributing. Especially when they are interested in fixing up things that no one else is focusing on. In fact you should have received an invite to our internal slack channel for Mint development.

I fully understand the learning on the go approach. I started the same way. A cinnamon user who wanted to see some improvements and was willing to help out. If it wasn't for the existing devs having the patience to answer questions and point me in the right direction, I'm not sure how far I would have gotten.

One thing I have learned along the way. Never be afraid to share your ideas. Sometimes they get shot down, sometimes they are wanted, and sometimes, through discussion and refinement they turn from something that may have been rejected into something everyone wants :)

**Comment by NikoKrause** [comment]
I see now, that I have understood your sentences "I think it was intentionally done this way to keep it simple" and "I've heard your "it's simple" argument too many times for a lot of different things" wrong.
I'm glad we were able to solve our miscommunication.

**Comment by lestcape** [comment]
@NikoKrause I think you are worng...

Your idea will be nice, if cinnamon will have a way for register applet activities (like roles).

For example, you can use a setting file for declared an applet activities, the possible activities could be a list of global settings activities, then on start, you read the settings f the applets an register the applet in that activity.

Then we can create a function in cinnamon Dbus to query for activities and report for any changes.

Otherwise you will have a settings option for an applet that also the user could remove... And action for an specific program that also it's not working? Thats why i say you are wrong...

**Comment by NikoKrause** [comment]
You two are probably right. This would make it unnecessarily complicated.
Also having an option for the recent-applet seems pointless.
Better stick to the KISS principle. Keep it simple, stupid!
Or something like that xD
I'm closing this one.

**Comment by lestcape** [comment]
I don't want to say this in that way (but you say it). Yes it unnecessarily complicated as we have the extension settings, this have not sense to me, but well @NikoKrause. Do you know that we can create our settings plungings? You can create one if you want. One thin that i don't like it it' s that not exist a way to load a plugins form the user domain. this need to be set as a root, but well...
