### ISSUE TITLE
Nemo video thumbnails upside down

### ISSUE THREAD

**Issue by darrenhopkinson** [linuxmint/Cinnamon#5888]
[Apologies if this is the wrong method for reporting bugs - if so please let me know the correct way]

Running Linux Mint 18 and using Nemo to browse videos, I find that the thubnails are always shown upside down. Playing the videos with VLC always plays them with the correct orientation (although they are upside down if played in the "Videos" application).

I can provide an example video if necessary (7.7MB) although attaching videos here is disallowed.

Note that the source of the videos is the Nexus 5x phone, which is known to use uncommon metadata for encoding photo/video orientation (see https://productforums.google.com/forum/#!topic/nexus/eGbLbf9ytS8)

**Comment by JosephMcc** [comment]
This probably should go on the nemo issue tracker: https://github.com/linuxmint/nemo/issues
