### ISSUE TITLE
wishlist: autoraise option in window manager

### ISSUE THREAD

**Issue by MHellmund** [linuxmint/Cinnamon#589]
It's great to have sloppy focus and focus-follows-mouse. But I think they make
more sense together with an "autoraise after xxx milliseconds" option.

**Comment by pixunil** [comment]
Works since `2.4` and still in `2.6`, also via `cinnamon-settings` GUI.
Only the `auto-raise-delay` value isn't configurable, maybe we can now use a revealer for that.

**Comment by JosephMcc** [comment]
The are mostly configurable in cinnamon settings now.
