### ISSUE TITLE
Panel loses (some) settings after secondary display is disabled and re-enabled.

### ISSUE THREAD

**Issue by sustained** [linuxmint/cinnamon#5896]
I decided to write a [little shell script](https://gist.github.com/sustained/0da4531bc8ba912e706d24a7d34ef8ce) to toggle my secondary monitor on/off because... I felt like it.

When I disable the secondary display and then re-enable it, my panel loses some settings.

**Menu Instance**
1. The "text" reverts to "Menu"
2. The "enable filesystem entry" reverts to off.

**Workspace Switcher Instance**
1. The "type of display" reverts to "a visual representation".

All of the other changes I've made to the secondary display's panel seems to persist.

**Comment by itzexor** [comment]
I think this may be fixed in master already. If you want, you can try this and see if it fixes it for you.
https://github.com/linuxmint/Cinnamon/commit/14c434732aa080ec1d7d1fcac5686bf0bdfd47c1

**Comment by Vahan86** [comment]
@sustained, is this still an issue in Cinnamon 3.8?

**Comment by sustained** [comment]
Wow, what an old issue! I'm not sure.

I can't check right now as I'm away for Christmas, I'll try to remember to check when I get back.

**Comment by Vahan86** [comment]
@JosephMcc, since there is no response from OP for a long time, can we close this issue?
