### ISSUE TITLE
usb mouse buttons stop working

### ISSUE THREAD

**Issue by ccurvey** [linuxmint/Cinnamon#5897]
I have a recurring (and frequent) issue with Cinnamon on a laptop when using a USB mouse.  Quite often, the mouse buttons stop responding.  (Or the mouse seems to think that the left button is being held down, when it is not.) The mouse continues to move the pointer, but I can't click on anything.  I get out of the situation by doing ctrl-alt-f6 to black out the screen, then ctrl-alt-f7 to go back into Cinnamon.

I do not get his problem with working with the built-in touchpad & buttons, and I have tried several mice -- all of them have the same issue.  I don't see any details in the logs about this, but it could be that I'm not looking in the right logs.  (I actually suspect that Cinnamon does not know that anything is wrong.)

Let's see -- details.  I'm running Cinnamon on top of Ubuntu.  I've had the issue with both 16.04 and 16.10.

**Comment by leigh123linux** [comment]
This is more likely to be a kernel or system package at fault, not cinnamon.

**Comment by mainmachine** [comment]
Yeah, don't see how that could be a cinnamon issue. Haven't seen this with a dozen different mice and track pads - I'm daily user for several years on about 5 dedicated machines, and many more that have come and gone.

**Comment by ccurvey** [comment]
Fair enough.   Of course, my vendor says "We haven't gotten any reports of this on Unity."  Any ideas where I might look to see if there's an error logged?  syslog and kern.log are clean...

**Comment by leigh123linux** [comment]
@ccurvey 

See if dmesg has it

```
dmesg
```

**Comment by ccurvey** [comment]
I gave up and switched to MATE.
