### ISSUE TITLE
Copy / paste the actual applet configuration

### ISSUE THREAD

**Issue by tobia** [linuxmint/cinnamon#5900]
I have two main panels in my two monitor setup, set up so that they are as similar as possible.

When I change something in one panel, I use "Modify panel" > "Copy / Paste applet configuration" in the panel's context menu to replicate the change on the other panel. 

But this action only seems to create applets in their default configuration. Then I have to manually replicate my changes on the other panel, or use "Export to a file" / "Import from a file" from each applet's configuration screen, if the changes are not trivial (for example, the list of launchers!)

I think it would be more useful if the "Copy / Paste applet configuration" copied the actual applet configurations, instead of creating applets in their default state.

I'm using Mint 18 64bit.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
