### ISSUE TITLE
Fan speed maxed out

### ISSUE THREAD

**Issue by pasimko** [linuxmint/Cinnamon#5902]
Linux Mint 18
intel i5-6500, default drivers
inxi -Fxz output is:
`System:    Host: Paul-desktop Kernel: 4.4.0-43-generic x86_64 (64 bit gcc: 5.4.0)
           Desktop: Cinnamon 3.0.7 (Gtk 3.18.9-1ubuntu3.1) Distro: Linux Mint 18 Sarah
Machine:   Mobo: ASUSTeK model: B150 PRO GAMING/AURA v: Rev X.0x
           Bios: American Megatrends v: 0303 date: 10/26/2015
CPU:       Quad core Intel Core i5-6500 (-MCP-) cache: 6144 KB
           flags: (lm nx sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx) bmips: 25536
           clock speeds: max: 3600 MHz 1: 800 MHz 2: 800 MHz 3: 800 MHz 4: 800 MHz
Graphics:  Card: Intel Sky Lake Integrated Graphics bus-ID: 00:02.0
           Display Server: X.Org 1.18.3 drivers: intel (unloaded: fbdev,vesa)
           Resolution: 1920x1080@60.00hz, 1920x1080@60.00hz
           GLX Renderer: Mesa DRI Intel HD Graphics 530 (Skylake GT2)
           GLX Version: 3.0 Mesa 11.2.0 Direct Rendering: Yes
Audio:     Card Intel Sunrise Point-H HD Audio driver: snd_hda_intel bus-ID: 00:1f.3
           Sound: Advanced Linux Sound Architecture v: k4.4.0-43-generic
Network:   Card: Intel Ethernet Connection (2) I219-V driver: e1000e v: 3.2.6-k bus-ID: 00:1f.6
           IF: enp0s31f6 state: up speed: 100 Mbps duplex: full mac: <filter>
Drives:    HDD Total Size: 240.1GB (21.3% used) ID-1: /dev/sda model: PNY_CS2211_240GB size: 240.1GB temp: 30C
Partition: ID-1: / size: 205G used: 33G (17%) fs: ext4 dev: /dev/sda1
           ID-2: swap-1 size: 17.05GB used: 0.01GB (0%) fs: swap dev: /dev/sda5
RAID:      No RAID devices: /proc/mdstat, md_mod kernel module present
Sensors:   System Temperatures: cpu: 29.8C mobo: 27.8C
           Fan Speeds (in rpm): cpu: 0
Info:      Processes: 218 Uptime: 2 days Memory: 1894.2/15927.2MB Init: systemd runlevel: 5 Gcc sys: 5.4.0
           Client: Shell (bash 4.3.421) inxi: 2.2.35 
`

**Comment by leigh123linux** [comment]
This isn't a cinnamon issue (I would blame the kernel or gpu driver).

At these temps the fans should be idling (low)

```
System Temperatures: cpu: 29.8C mobo: 27.8C Fan Speeds (in rpm): cpu:
```

Does the fan speed issue still happen with a single monitor? (maybe the GPU is struggling to drive 2).
```
Resolution: 1920x1080@60.00hz, 1920x1080@60.00hz
```

**Comment by pasimko** [comment]
I should have mentioned that these are my case fans. I am not sure how fast my CPU fan is spinning.
I also use an integrated GPU.

**Comment by leigh123linux** [comment]
So why do you think this issue is cinnamon related?
