### ISSUE TITLE
Menu search shows "recent" files that have been deleted/renamed.

### ISSUE THREAD

**Issue by bkjohnson** [linuxmint/Cinnamon#5903]
Deleting or renaming a file doesn't remove it from the menu's list of recent files.  Here's an example where I've deleted several screenshots from the Pictures directory and they still show up when I search for `screenshot`

![broken_search](https://cloud.githubusercontent.com/assets/2008881/20026601/701736b4-a2cb-11e6-9b66-c9b68e9bebc0.png)

If I try to click on a file that no longer exists nothing happens which is another bad thing.  I would at least expect to see something like a red border around the item or a little message that says "File no longer exists".

I found #3537 which seemed like a similar issue, but apparently it was fixed which makes me think this is the result of something else.

**Comment by NikoKrause** [comment]
I tackled this issue a few days ago.
https://github.com/linuxmint/Cinnamon/pull/5887

**Comment by bkjohnson** [comment]
Closing this as it appears to be fixed.  Thanks @NikoKrause!.

**Comment by NikoKrause** [comment]
@JosephMcc 
This issue can be opened again.
This commit https://github.com/linuxmint/Cinnamon/commit/f82ce69466705dc8117c9fc336a5b50032a93a8f caused a regression. (I.e. the issue appears in Cinnamon 3.2.8 again)
My fix/workaround has been deleted. Now this issue exists again.
