### ISSUE TITLE
Cinnamon crashing at boot, asking to restart.

### ISSUE THREAD

**Issue by kolorafa** [linuxmint/Cinnamon#5907]
After saying "yes" cinnamon runs normally, no problems.
It happens every time.

No errors in .cinnamon/glass.log and .cinnamon/glass.log.last

Found in journal:
http://pastebin.com/mk9Mrx0g

OS: Arch Antergos

**Comment by JosephMcc** [comment]
Do you have an ~/.xsession-errors by chance? If so, check there.

**Comment by kolorafa** [comment]
Found like:
http://pastebin.com/ANh0gnxu

and a lot of other errors related to other apps:
https://dl.dropboxusercontent.com/u/54627341/cinnamon-errors/.xsession-errors.old
https://dl.dropboxusercontent.com/u/54627341/cinnamon-errors/.xsession-errors

I saw that it did make coredump, but i don't know where it is saved.

**Comment by JosephMcc** [comment]
Do you have a lot of applications autostarting? If so try disabling them. Also disable any 3rd party desklets or applets just to help narrow things down.

**Comment by kolorafa** [comment]
I did disable all apps from autostart and re-enabled half and half, and no error. So it's fixed?

(Maybe they start with different order? Even my syncthing icon is showing. but it was randomly showing before)

My autostart:
http://kolorafa.firehost.pl/test/snapshot-2016-11-07-20-15-00.png
