### ISSUE TITLE
Date and time settings segfaults when opening

### ISSUE THREAD

**Issue by runfalk** [linuxmint/cinnamon#5913]
I installed Linux Mint 18 yesterday and have issues with the date and time settings. When the icon is clicked the window instantly closes. Running the calendar settings module from the terminal reveals the following error message (translated by me from Swedish locale)

```
$ cinnamon-settings calendar -v
(cinnamon-settings.py:3997): datetime-cc-panel-WARNING **: could not get proxy for DateTimeMechanism: Error when calling StartServiceByName for org.cinnamon.SettingsDaemon.DateTimeMechanism: GDBus.Error:org.freedesktop.DBus.Error.Spawn.ExecFailed: Failed to execute program org.cinnamon.SettingsDaemon.DateTimeMechanism: Permission denied

(cinnamon-settings.py:3997): GLib-GIO-CRITICAL **: g_dbus_proxy_call_sync_internal: assertion 'G_IS_DBUS_PROXY (proxy)' failed
Segmentation fault
```
This issue seems similar, but is slightly different to, #4522.

The only thing that makes my installation deviate slightly from the norm is that I configured my update manager to automatically install packages from all levels (the advanced user option).

**Comment by icarter09** [comment]
We believe this issue is fixed. Please test against the latest Cinnamon version (4.2). 

https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/
