### ISSUE TITLE
Screen lock not working when start menu is open

### ISSUE THREAD

**Issue by spilot** [linuxmint/Cinnamon#5914]
I'm using Cinnamon 3.0.7 and cinnamon-screensaver 3.0.1 on Fedora 24. The following bug occurs on multiple systems: When the start menu is open and I close the lid of my laptop, the laptop enters standby as usual but is not locked when opened again.
When the start menu is closed, everything is working as usual.

I was able to reproduce this issue on a different laptop with the same software installed.

**Comment by leigh123linux** [comment]
I have noticed the issue as well.

**Comment by JosephMcc** [comment]
https://github.com/linuxmint/cinnamon-screensaver/issues/93
