### ISSUE TITLE
Keyboard applet failing

### ISSUE THREAD

**Issue by sc954rr** [linuxmint/Cinnamon#5915]
Arch linux running Cinnamon 3.2.0-1 upgrade is giving an error traced back to keyboard applet error loading. Here is the exact message from the glass.log

error t=2016-11-08T14:26:29.316Z [Applet "keyboard@cinnamon.org"]: Error importing applet.js from keyboard@cinnamon.org
error t=2016-11-08T14:26:29.316Z Could not load applet keyboard@cinnamon.org

**Comment by NikoKrause** [comment]
https://github.com/linuxmint/Cinnamon/issues/5911

**Comment by sc954rr** [comment]
I installed the xapps files but I am still having the same problem with keyboard applet, do I have to relink something or reinstall cinnamon update?

**Comment by NikoKrause** [comment]
I'm not sure, if that solves your problem, but the https://github.com/linuxmint/flags repo is also a new dependency.
