### ISSUE TITLE
Screen will not lock 3.2.0-1 update

### ISSUE THREAD

**Issue by sc954rr** [linuxmint/Cinnamon#5916]
Arch linux running Cinnamon 3.2.0-1 after upgrade unable to lock the screen with CTL + L or clicking the "lock screen" icon from menu.  After clicking Ok button box disappears but screen doesn't lock

**Comment by Kalagon** [comment]
Same here, the error I get is "(cinnamon-screensaver:2488): GLib-GIO-ERROR **: Settings schema 'org.cinnamon.desktop.screensaver' does not contain a key named 'logout-enabled'"

**Comment by leigh123linux** [comment]
https://github.com/linuxmint/Cinnamon/issues/5912

**Comment by leigh123linux** [comment]
It because arch hasn't updated screensaver package

**Comment by Teejer** [comment]
Running Arch with LTS kernel having the same issue. Here is the output of journalctl when I try to lock the screen. As a temporary work around I'm using dm-tool lock.


Nov 08 08:25:37 workstation systemd-coredump[3056]: Process 3051 (cinnamon-screen) of user 1000 dumped core.
                                               
                                               Stack trace of thread 3051:
                                               #0  0x00007f9af53ddff1 n/a (libglib-2.0.so.0)
                                               #1  0x00007f9af53df047 g_log_default_handler (libglib-2.0.so.0)
                                               #2  0x00007f9af53df354 g_logv (libglib-2.0.so.0)
                                               #3  0x00007f9af53df55f g_log (libglib-2.0.so.0)
                                               #4  0x00007f9af59f8239 n/a (libgio-2.0.so.0)
                                               #5  0x00007f9af59f8841 n/a (libgio-2.0.so.0)
                                               #6  0x00007f9af59fc333 g_settings_get_value (libgio-2.0.so.0)
                                               #7  0x00007f9af59fd3db g_settings_get_boolean (libgio-2.0.so.0)
                                               #8  0x00000000004152da n/a (cinnamon-screensaver)
                                               #9  0x00007f9af56d434b g_type_create_instance (libgobject-2.0.so.0)
                                               #10 0x00007f9af56b61fb n/a (libgobject-2.0.so.0)
                                               #11 0x00007f9af56b7c0d g_object_newv (libgobject-2.0.so.0)
                                               #12 0x00007f9af56b83c4 g_object_new (libgobject-2.0.so.0)
                                               #13 0x0000000000415512 gs_prefs_new (cinnamon-screensaver)
                                               #14 0x000000000040a585 n/a (cinnamon-screensaver)
                                               #15 0x00007f9af56d434b g_type_create_instance (libgobject-2.0.so.0)
                                               #16 0x00007f9af56b61fb n/a (libgobject-2.0.so.0)
                                               #17 0x00007f9af56b7c0d g_object_newv (libgobject-2.0.so.0)
                                               #18 0x00007f9af56b83c4 g_object_new (libgobject-2.0.so.0)
                                               #19 0x000000000040a9b2 gs_monitor_new (cinnamon-screensaver)
                                               #20 0x0000000000409d43 main (cinnamon-screensaver)
                                               #21 0x00007f9af48b9291 __libc_start_main (libc.so.6)
                                               #22 0x0000000000409e69 _start (cinnamon-screensaver)
                                               
                                               Stack trace of thread 3053:
                                               #0  0x00007f9af497848d poll (libc.so.6)
                                               #1  0x00007f9af53d8786 n/a (libglib-2.0.so.0)
                                               #2  0x00007f9af53d8b12 g_main_loop_run (libglib-2.0.so.0)
                                               #3  0x00007f9af59be316 n/a (libgio-2.0.so.0)
                                               #4  0x00007f9af54000d5 n/a (libglib-2.0.so.0)
                                               #5  0x00007f9af4683454 start_thread (libpthread.so.0)
                                               #6  0x00007f9af49817df __clone (libc.so.6)
                                               
                                               Stack trace of thread 3054:
                                               #0  0x00007f9af48dfe38 vfprintf (libc.so.6)
                                               #1  0x00007f9af49918f5 __vasprintf_chk (libc.so.6)
                                               #2  0x00007f9af541cfb9 g_vasprintf (libglib-2.0.so.0)
                                               #3  0x00007f9af53f7dad g_strdup_vprintf (libglib-2.0.so.0)
                                               #4  0x00007f9af53f7e69 g_strdup_printf (libglib-2.0.so.0)
                                               #5  0x00007f9af59b7185 g_dbus_message_to_blob (libgio-2.0.so.0)
                                               #6  0x00007f9af59ab98c n/a (libgio-2.0.so.0)
                                               #7  0x00007f9af59ace06 n/a (libgio-2.0.so.0)
                                               #8  0x00007f9af59afe13 g_dbus_connection_send_message_with_reply (libgio-2.0.so.0)
                                               #9  0x00007f9af59b01ba n/a (libgio-2.0.so.0)
                                               #10 0x00007f9af59b2945 g_dbus_connection_call (libgio-2.0.so.0)
                                               #11 0x00007f9aeaf493bf n/a (libdconfsettings.so)
                                               #12 0x00007f9af53d843a g_main_context_dispatch (libglib-2.0.so.0)
                                               #13 0x00007f9af53d87f0 n/a (libglib-2.0.so.0)
                                               #14 0x00007f9af53d889c g_main_context_iteration (libglib-2.0.so.0)
                                               #15 0x00007f9aeaf494bd n/a (libdconfsettings.so)
                                               #16 0x00007f9af54000d5 n/a (libglib-2.0.so.0)
                                               #17 0x00007f9af4683454 start_thread (libpthread.so.0)
                                               #18 0x00007f9af49817df __clone (libc.so.6)
                                               
                                               Stack trace of thread 3052:
                                               #0  0x00007f9af497848d poll (libc.so.6)
                                               #1  0x00007f9af53d8786 n/a (libglib-2.0.so.0)
                                               #2  0x00007f9af53d889c g_main_context_iteration (libglib-2.0.so.0)
                                               #3  0x00007f9af53d88e1 n/a (libglib-2.0.so.0)
                                               #4  0x00007f9af54000d5 n/a (libglib-2.0.so.0)
                                               #5  0x00007f9af4683454 start_thread (libpthread.so.0)
                                               #6  0x00007f9af49817df __clone (libc.so.6)

**Comment by Kalagon** [comment]
Oh, completely missed that... thank you.

**Comment by Teejer** [comment]
Interesting. You are right Arch hasn't updated the cinnamon-screensaver package to 3.2

**Comment by zquestz** [comment]
Correct, but the fix is included in this bug report -> https://github.com/linuxmint/Cinnamon/issues/5920#event-852359736
