### ISSUE TITLE
popup-menu bug

### ISSUE THREAD

**Issue by CosmicTachyon** [linuxmint/Cinnamon#5917]
I updated to Cinnamon 3.2 on Arch Linux. I have noticed that when applying third-party themes (numix in my case) the colour and transparency of the pop-up menu remains unchanged. I think the origin of this issue comes from a change in the new `Cinnamon/data/theme/cinnamon.css` file, in which `PopupMenu (popupMenu.js)` uses `.menu` instead of `.popup-menu` and `.popup-menu-boxpointer`. So in my case the popup-menu in Cinnamon 3.2 is not compatible with some existing third-party themes.

**Comment by leigh123linux** [comment]
The third-party themes will need to fix this and become compatible with cinnamon, not the other way round.

**Comment by clefebvre** [comment]
Yes, this is correct.

You need to add .menu to the theme to support Cinnamon 3.2.

Also please keep .popup-menu and .popup-menu-boxpointer in there, so that your new theme is backward compatible with Cinnamon 3.0 and prior versions.

**Comment by CosmicTachyon** [comment]
Copy that. Thank you.
