### ISSUE TITLE
Panel theme regression in 3.2.0

### ISSUE THREAD

**Issue by zquestz** [linuxmint/Cinnamon#5918]
Just updated my Arch install to Cinnamon 3.2.0 and it seems there was a regression in panel backgrounds. No matter what I do, I get the default grey with an outline. I am using the Minty theme and should have a black background on my panels. Here is a screenshot:

http://imgur.com/A5dIzXG

I tested several themes and they all seem to have this issue, any help would be greatly appreciated!

**Comment by leigh123linux** [comment]
Use the default theme till the third-party themes add support for 3.2.0.

https://github.com/linuxmint/Cinnamon/issues/5917

p.s please close this issue

**Comment by zquestz** [comment]
Thank you. This is exactly what I needed.

**Comment by zquestz** [comment]
For those that find this closed issue. Adding the following to `.themes/Minty/cinnamon.css` made it not look terrible.

```
.menu {
	-arrow-border-radius: 3px;
	-arrow-background-color: rgba(0,0,0,0.85);
	-arrow-border-width: 1px;
	-arrow-border-color: rgba(255,255,255,0.1);
	-arrow-base: 21px;
	-arrow-rise: 10px;
	-boxpointer-gap: 3px;
	background-color: black;
	min-width: 100px;
}
```
