### ISSUE TITLE
Panel applets can not be configured

### ISSUE THREAD

**Issue by raqua** [linuxmint/Cinnamon#5923]
Version: Cinnamon 3.2.0 on Arch Linux
When I right click on any applet and try to access its configuration, nothing happens.

**Comment by leigh123linux** [comment]
It works fine.
Arch linux has botched their 3.2.0 cinnamon packages, post the output for the equivalent command.

```
$ rpm -qa cinnamon\* nemo\* cjs\* *\xapps\* muffin\* |sort
cinnamon-3.2.1-1.fc25.x86_64
cinnamon-control-center-3.2.0-1.fc25.x86_64
cinnamon-control-center-filesystem-3.2.0-1.fc25.x86_64
cinnamon-desktop-3.2.0-2.fc25.x86_64
cinnamon-desktop-devel-3.2.0-2.fc25.x86_64
cinnamon-menus-3.2.0-1.fc25.x86_64
cinnamon-menus-devel-3.2.0-1.fc25.x86_64
cinnamon-screensaver-3.2.0-1.fc25.x86_64
cinnamon-session-3.2.0-1.fc25.x86_64
cinnamon-settings-daemon-3.2.0-1.fc25.x86_64
cinnamon-translations-3.0.3-1.fc25.noarch
cjs-3.2.0-1.fc25.x86_64
cjs-devel-3.2.0-1.fc25.x86_64
muffin-3.2.0-1.fc25.x86_64
muffin-devel-3.2.0-1.fc25.x86_64
nemo-3.2.0-1.fc25.x86_64
nemo-compare-3.2.0-1.fc25.noarch
nemo-devel-3.2.0-1.fc25.x86_64
nemo-dropbox-3.0.0-2.fc25.x86_64
nemo-extensions-3.2.0-1.fc25.x86_64
nemo-fileroller-3.2.0-1.fc25.x86_64
nemo-image-converter-3.2.0-1.fc25.x86_64
nemo-preview-3.2.0-1.fc25.x86_64
nemo-python-3.2.0-1.fc25.x86_64
xapps-1.0.2-1.fc25.x86_64
xapps-devel-1.0.2-1.fc25.x86_64
```

**Comment by raqua** [comment]
Cinnamon menus is still on 3.0.2, could that be the culprit ? 

yaourt -Qs | grep "cinnamon\|xapps\|nemo\|cjs\|muffin" | sort 
community/cinnamon 3.2.1-1
community/cinnamon-control-center 3.2.0-1
community/cinnamon-desktop 3.2.0-1
community/cinnamon-menus 3.0.2-1
community/cinnamon-screensaver 3.2.0-1
community/cinnamon-session 3.2.0-1
community/cinnamon-settings-daemon 3.2.0-1
community/cinnamon-translations 3.2.0-1
community/cjs 3.2.0-1
community/muffin 3.2.0-1
community/nemo 3.2.0-1
community/xapps 1.0.2-1
local/cinnamon-bluetooth 3.8.2-1
local/mint-cinnamon-themes 2016.05.03-1

**Comment by leigh123linux** [comment]
I don't think cinnamon-menus would cause this, can you post ~/.cinnamon/glass.log and ~/.xsession-errors
Also what cinnamon theme?, have you tried the default?

**Comment by raqua** [comment]
I was using Linux Mint theme, but switching to default theme did not help.
Attached are the requested logs. 

[logs.zip](https://github.com/linuxmint/Cinnamon/files/580691/logs.zip)

**Comment by bendovercz** [comment]
Can confirm. Even clicking `Configure` button in `Applets` does nothing.  

~/.cinnamon/glass.log and ~/.xsession-errors do not change when clicking that button.

**Comment by JosephMcc** [comment]
Try running `xlet-settings applet window-list@cinnamon.org` in a terminal. See what the errors are.

**Comment by bendovercz** [comment]
`Traceback (most recent call last):
  File "/usr/share/cinnamon/cinnamon-settings/xlet-settings.py", line 9, in <module>
    from JsonSettingsWidgets import *
  File "/usr/share/cinnamon/cinnamon-settings/bin/JsonSettingsWidgets.py", line 2, in <module>
    from SettingsWidgets import *
  File "/usr/share/cinnamon/cinnamon-settings/bin/SettingsWidgets.py", line 8, in <module>
    import dbus
ImportError: No module named 'dbus'`

**Comment by JosephMcc** [comment]
No problem. At least we know what the issue is.
