### ISSUE TITLE
(cinnamon-screensaver:32039): GLib-GIO-ERROR **: Settings schema 'org.cinnamon.desktop.screensaver' does not contain a key named 'logout-enabled'

### ISSUE THREAD

**Issue by MikeDacre** [linuxmint/Cinnamon#5925]
I am running Arch Linux with Cinnamon 3.2.1 and for some reason the screensaver has just stopped working. I tried deleteing my `.config` folder, my `.local` folder, and my `.cinnamon` folder, and then completely uninstalling and reinstalling cinnamon, deleting all old config files but the problem persists:

The screensaver or lock screen never start, and when I try to invoke `cinnamon-screensaver` from a shell, I get this error:

    (cinnamon-screensaver:32039): GLib-GIO-ERROR **: Settings schema 'org.cinnamon.desktop.screensaver' does not contain a key named 'logout-enabled'

And this core dump:

    Process 32039 (cinnamon-screen) of user 62149 dumped core.
    
    Stack trace of thread 32039:
    #0  0x00007fceb9c76ff1 n/a (libglib-2.0.so.0)
    #1  0x00007fceb9c78047 g_log_default_handler (libglib-2.0.so.0)
    #2  0x00007fceb9c78354 g_logv (libglib-2.0.so.0)
    #3  0x00007fceb9c7855f g_log (libglib-2.0.so.0)
    #4  0x00007fceba291239 n/a (libgio-2.0.so.0)
    #5  0x00007fceba291841 n/a (libgio-2.0.so.0)
    #6  0x00007fceba295333 g_settings_get_value (libgio-2.0.so.0)
    #7  0x00007fceba2963db g_settings_get_boolean (libgio-2.0.so.0)
    #8  0x000000000041521a n/a (cinnamon-screensaver)
    #9  0x00007fceb9f6d34b g_type_create_instance (libgobject-2.0.so.0)
    #10 0x00007fceb9f4f1fb n/a (libgobject-2.0.so.0)
    #11 0x00007fceb9f50c0d g_object_newv (libgobject-2.0.so.0)
    #12 0x00007fceb9f513c4 g_object_new (libgobject-2.0.so.0)
    #13 0x0000000000415452 gs_prefs_new (cinnamon-screensaver)
    #14 0x000000000040a4c5 n/a (cinnamon-screensaver)
    #15 0x00007fceb9f6d34b g_type_create_instance (libgobject-2.0.so.0)
    #16 0x00007fceb9f4f1fb n/a (libgobject-2.0.so.0)
    #17 0x00007fceb9f50c0d g_object_newv (libgobject-2.0.so.0)
    #18 0x00007fceb9f513c4 g_object_new (libgobject-2.0.so.0)
    #19 0x000000000040a8f2 gs_monitor_new (cinnamon-screensaver)
    #20 0x0000000000409c83 main (cinnamon-screensaver)
    #21 0x00007fceb9152291 __libc_start_main (libc.so.6)
    #22 0x0000000000409daa _start (cinnamon-screensaver)
    
    Stack trace of thread 32083:
    #0  0x00007fceb91acd00 malloc (libc.so.6)
    #1  0x00007fceb9c76b99 g_malloc (libglib-2.0.so.0)
    #2  0x00007fceb9cb5773 g_variant_type_new_dict_entry (libglib-2.0.so.0)
    #3  0x00007fceb9caa060 g_variant_builder_end (libglib-2.0.so.0)
    #4  0x00007fceb9cab603 n/a (libglib-2.0.so.0)
    #5  0x00007fceb9caba72 g_variant_new_va (libglib-2.0.so.0)
    #6  0x00007fceb9cabf9d g_variant_builder_add (libglib-2.0.so.0)
    #7  0x00007fceba2500eb g_dbus_message_to_blob (libgio-2.0.so.0)
    #8  0x00007fceba24498c n/a (libgio-2.0.so.0)
    #9  0x00007fceba245e06 n/a (libgio-2.0.so.0)
    #10 0x00007fceba248e13 g_dbus_connection_send_message_with_reply (libgio-2.0.so.0)
    #11 0x00007fceba2491ba n/a (libgio-2.0.so.0)
    #12 0x00007fceba24b945 g_dbus_connection_call (libgio-2.0.so.0)
    #13 0x00007fcead21d3bf n/a (libdconfsettings.so)
    #14 0x00007fceb9c7143a g_main_context_dispatch (libglib-2.0.so.0)
    #15 0x00007fceb9c717f0 n/a (libglib-2.0.so.0)
    #16 0x00007fceb9c7189c g_main_context_iteration (libglib-2.0.so.0)
    #17 0x00007fcead21d4bd n/a (libdconfsettings.so)
    #18 0x00007fceb9c990d5 n/a (libglib-2.0.so.0)
    #19 0x00007fceb8f1c454 start_thread (libpthread.so.0)
    #20 0x00007fceb921a7df __clone (libc.so.6)
    
    Stack trace of thread 32067:
    #0  0x00007fceb921148d poll (libc.so.6)
    #1  0x00007fceb9c71786 n/a (libglib-2.0.so.0)
    #2  0x00007fceb9c71b12 g_main_loop_run (libglib-2.0.so.0)
    #3  0x00007fceba257316 n/a (libgio-2.0.so.0)
    #4  0x00007fceb9c990d5 n/a (libglib-2.0.so.0)
    #5  0x00007fceb8f1c454 start_thread (libpthread.so.0)
    #6  0x00007fceb921a7df __clone (libc.so.6)
    
    Stack trace of thread 32066:
    #0  0x00007fceb921148d poll (libc.so.6)
    #1  0x00007fceb9c71786 n/a (libglib-2.0.so.0)
    #2  0x00007fceb9c7189c g_main_context_iteration (libglib-2.0.so.0)
    #3  0x00007fceb9c718e1 n/a (libglib-2.0.so.0)
    #4  0x00007fceb9c990d5 n/a (libglib-2.0.so.0)
    #5  0x00007fceb8f1c454 start_thread (libpthread.so.0)
    #6  0x00007fceb921a7df __clone (libc.so.6)

Everything was working fine until very recently. My hard drive started dying a few weeks ago though, and I copied everything over to a new hard drive with `dd-rescue` from a rescue disc. At the same time I tried to clean up some of my config files, but I have just been having so many little issues, and then on my last upgrade a few days ago, this error started and I just cannot get rid of it.

Thanks for your help!

**Comment by JosephMcc** [comment]
https://github.com/linuxmint/Cinnamon/issues/5920

**Comment by MikeDacre** [comment]
Thanks, sorry I didn't see that. The issue is actually fixed now in the latest cinnamon package updates released today to the Arch repos.
