### ISSUE TITLE
Show more than 20 recent files - would like opinions from other devs!

### ISSUE THREAD

**Issue by AlbertJP** [linuxmint/Cinnamon#5928]
The current limit for the amount of "recent files" in the menu is 20 (see js/misc/docInfo.js). This generally means that only the files from the last few days are found, which I find quite inconvenient at times.

I am considering a solution such as:
- including more recent files (50 or 100?)
- allowing the search function to search through all recent files rather than just the top 20

It was limited to 20 in d5ff93e034d46aedf2c7f29252f19db9608bd194 because looking up thumbnails was too expensive. But since that lookup has been removed, I'm wondering whether a limit to 20 is still necessary.

Do you have any opinions about these solutions?

**Comment by lestcape** [comment]
I think also that the expensive functionality could be moved to c class if will be needed again. 

Also i think for your case 1, that will be good create only one instance of the docInfo and add this instance to the cinnamon main class, this information cloud be share then with others extensions, without duplicate the enforce.

If this is too much, and for your seconds solution case, another possibility could be use MAX_RECENT_FILES as a object variable and allow modify his value as a dependency of what the client want and not fix it to 50 or 100...
