### ISSUE TITLE
Desktop zoom - Option to configure filtering (disable anti-aliasing)

### ISSUE THREAD

**Issue by tobia** [linuxmint/cinnamon#5929]
As a UI developer, I find the desktop zoom feature very useful: it lets me look closer at the pixel rendering of parts of UI without having to physically move closer to the monitor.

But there is one feature that other OSes have that I'm missing: the possibility to configure (or disable) the filtering used by the zoom popup. Right now Desktop zoom seems to be using some kind of default bilinear or bicubic filtering, which is probably appropriate for a casual user. But as a UI development tool, it would be more useful to have no filtering at all, so that one can look at the individual pixels.

Compare the current Desktop zoom feature (right) with the traditional `xzoom` utility (left) that does not apply any filtering:

![zooms](https://cloud.githubusercontent.com/assets/48756/20181905/3f07e9e4-a760-11e6-9217-9eed3e4f767a.png)

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.

**Comment by LeonFedotov** [comment]
@icarter09 can you link to the issue i would love to follow this because i really need this feature to work

**Comment by formicant** [comment]
Has this feature been implemented?
Linux Mint 21 still uses bilinear scaling when zooming.

**Comment by phoboslab** [comment]
@icarter09 can you please tell us how is this implemented and how to enable it? There's no setting for the filter in Accessibility and I cannot see a settings key either.

```
$ gsettings list-keys org.cinnamon.desktop.a11y.magnifier
brightness-blue
brightness-green
brightness-red
color-saturation
contrast-blue
contrast-green
contrast-red
cross-hairs-clip
cross-hairs-color
cross-hairs-length
cross-hairs-opacity
cross-hairs-thickness
invert-lightness
lens-mode
lens-shape
mag-factor
mouse-tracking
screen-position
scroll-at-edges
show-cross-hairs
```
