### ISSUE TITLE
Main menu background no longer themable [3.2.1]?

### ISSUE THREAD

**Issue by petrucci4prez** [linuxmint/Cinnamon#5934]
Using Cinnamon 3.2.1 on Arch. It seems it is no longer possible to separately theme the main menu applet's background using .menu-background; instead it takes the theme of .menu like all the other applet popup menus. This seems like a bug as the .menu-background style class is still in menu@cinnamon.org/applet.js, but for some reason is being ignored. This could break many 3rd party themes that attempt to theme the main menu differently than the applet popup menus.

Downgrading to cinnamon 3.0.x resolves the problem. Looking Glass inspector on 3.2.1 shows "StBin.menu bottom" instead of "StBin.popup-menu-boxpointer popup-menu menu-background" on 3.0.x. Perhaps .menu-background isn't being properly applied now that .popup-menu-boxpointer is gone in 3.2.x?

**Comment by leigh123linux** [comment]
3rd party themes will need to adapt or die.

**Comment by NikoKrause** [comment]
@leigh123linux 
That's not helping him and he's not saying that he doesn't want to adapt his theme.
He's asking if it is possible to theme the menu-applet differently from the other applets.
It's needed for example in the CinnXP theme, which by the way didn't used boxpointers before.
So that's a legitimate question.

**Comment by JosephMcc** [comment]
I have a feeling I know what's happening here. I'll look into it over the weekend and see if I can make sure there is a way in place for you to do what you want. Can you show some sort of screenshot of what your trying to do?

**Comment by lestcape** [comment]
I agree with @NikoKrause and also with @leigh123linux both things are true!!!

**Comment by louisgv** [comment]
Just some screenshot on my issue.
What I want it to look like:
![image](https://cloud.githubusercontent.com/assets/6723574/20290328/6560c71e-aaad-11e6-9bb0-db6b7d6f0f03.png)

What it looks like after update:
![image](https://cloud.githubusercontent.com/assets/6723574/20290400/b07b6696-aaad-11e6-9a29-bca1bc78ef77.png)

**Comment by JosephMcc** [comment]
There is already a PR waiting to fix this.

**Comment by feren** [comment]
I hope it gets merged... I really miss that feature, and even that could seriously affect Cinnamon's reputation

**Comment by feren** [comment]
@JosephMcc Erm, the picture of the vertical panels seems misleading, given you got rid of the box-pointers, and this image was made before the removal of those:
https://www.linuxmint.com/rel_serena_cinnamon_whatsnew.php
