### ISSUE TITLE
Please, bring back box pointers

### ISSUE THREAD

**Issue by germanfr** [linuxmint/Cinnamon#5935]
With all due respect, I think this is a bad decision. It was a very good looking feature that was already implemented, now removed for unknown reasons. It was already removable through themes.

At least bring it back as an option. I know you don't want options for tiny things, but this is not a tiny thing. It is something that standed out and defined a Cinnamon for me in a very good sense.

**Comment by NikoKrause** [comment]
I don't think that's ging to happen:

> It isn’t possible to support box pointers. I know it sounds like a small change that could be optional, but it’s actually quite big and we can’t just “enable it”.

http://blog.linuxmint.com/?p=3144#comment-133169

**Comment by germanfr** [comment]
But the option was already available. Themes could chose if they showed it or not. What a pity.

**Comment by irwtdvoys** [comment]
The DE just feel unfinished now, all the boxes sitting uncomfortably close or a pixel over what you clicked on =/

**Comment by collinss** [comment]
If I could have supported both options I would have. However, theming them out is awkward and very difficult to make look good. In addition, the code for the box pointers was incredibly complex. Removing them gave us substantial gains in performance, maintainability and themability. Removing features is always a tough call, but I feel this is the better path long term.

**Comment by lestcape** [comment]
I'm agree with @collinss Please see this example below...

The menu it's without text (no "menu"), only the image in the bottom left corner.... See the box pointer in action how it's reference the incorrect applet.

![captura de pantalla de 2016-11-11 12-42-29](https://cloud.githubusercontent.com/assets/1389572/20226078/46f8ba82-a80c-11e6-820f-1c472f6af1d6.png)

**Comment by germanfr** [comment]
I would say that's because the pop-up menu is misplaced. I would expect it to appear over the other bar, even without the box pointer.

**Comment by lestcape** [comment]
@germanfr ofcourse and then transparent themes will need to be rethinking not? I have to confess, maybe you are right, i have not the skills about that, I'm not an artist like probably you are, thats probably why i dislike gnome shell and also it's more important to me the functionality that the aesthetic.

**Comment by JosephMcc** [comment]
These aren't coming back as an option. Their is a lot of code surrounding those and having them as an option would be a mess to deal with.

Both @collinss and @lestcape are correct. We have been planning to remove these for awhile and when the vertical panels were merged they were broken in some cases and it finally proved the catalyst to get it done.

**Comment by germanfr** [comment]
OK I'll close this. I understand the incompatibility with the new ones. Although I must say there are some themes that lost their sense, like those with transparent panels :(

**Comment by vassilisw** [comment]
The "box pointers" were not only esthetic! 
Now you **can't tell for witch applet a box is opened**. At least place a caption in the popup box.
I think that the UI in the 18 series is being destroyed.

**Comment by JosephMcc** [comment]
The applets actually support a :checked style class now so the applet the menu is coming from will be highlighted. Much the same as work in any application window. Themes just need to add support.

**Comment by vassilisw** [comment]
Fair enough. 
If someone decides to add extra shadow for the panel, or tweak it (using the theme conf files).. will those boxes sit comfortably? 
At least give an option to increase the distance from the panel or something.
Anyway I still believe that cinnamon was better looking having those pointers and I am sure I am not the only one.

**Comment by JosephMcc** [comment]
That's fair enough. Panel shadows shouldn't interfere with the panel.
