### ISSUE TITLE
Arch Linux Black Screen

### ISSUE THREAD

**Issue by sirx** [linuxmint/Cinnamon#5941]
Hello I am using Arch Linux and today I updated my System and apparently there was also a Cinnamon update in it.

However after I rebooted the screen just stays black for me, the 2d version btw just works fine, but is not what I want to use.

I tried it with the proprieatry nvidia driver and with the free nouveau driver to see if it makes a difference, same result with both drivers.

Someone experiencing similar issues on Arch?

**Comment by leigh123linux** [comment]
If an Arch update breaks your system it's their issue to fix it, please close and file your issue at arch bug tracker instead.

P.S Nvidia works fine with cinnamon-3.2.x
