### ISSUE TITLE
Window List Application Menu Item order changed

### ISSUE THREAD

**Issue by derlucas** [linuxmint/Cinnamon#5950]
After an update of my Manjaro Linux Desktop somehow the order of the Menu Items in the Window List Menu (right click on a Window) have changed. The "Close X" option used the be on the lowest location. Now there the is "Settings ->" Submenu which is pretty annoying.
Is there a way of changing the order back how it was before?

![1479034327](https://cloud.githubusercontent.com/assets/1943040/20245070/1330ac7c-a998-11e6-9e9e-8b7e922b440c.png)

I already tried different themes, but the order does not change.

**Comment by NikoKrause** [comment]
The preferences submenu is new. It contains the items "About", " Configure" and "Remove".
In the past, there was only the " Configure" item at the top.
I don't know for sure, but I think the new submenu was placed at the bottom to be consistent with other applets.

The order can't be changed by themes. You have to change the applet code for that. If you are eager to change it for yourself I can tell you how it's done. Let me know.

**Comment by JosephMcc** [comment]
This was changed partly because pretty much every other applet has those options at the bottom. More options were also added to make it possible to actually remove a single particular instance of the window list which wasn't possible before.

**Comment by derlucas** [comment]
Yes please tell me where i can find the information to change this. I breaks my UX and its very annoying. The Closing Option should be on the bottom where it used to be like always.

**Comment by NikoKrause** [comment]
@derlucas 
The safest way is to copy the folder of the window-list applet `/usr/share/cinnamon/applets/window-list@cinnamon.org` to your local directory `~/.local/share/cinnamon/applet/window-list@cinnamon.org`.
(1) The terminal command for that is:
```
cp -r /usr/share/cinnamon/applets/window-list@cinnamon.org/ ~/.local/share/cinnamon/applets/
```

Now you open the file `applet.js` in `~/.local/share/cinnamon/applet/window-list@cinnamon.org`
(2) (If you are using Xed as your editor...) The terminal command for that is:
```
xed ~/.local/share/cinnamon/applets/window-list@cinnamon.org/applet.js 
```

(3)
In the `applet.js` file you just have to move the following two lines (linenumber 890 and 891)
```js
        let subMenu = new PopupMenu.PopupSubMenuMenuItem(_("Preferences"));
        this.addMenuItem(subMenu);
```

The order of `this.addMenuItem` in the code decides about the order of the items in the context menu of the applet.
So if you want to put the "Preferences" submenu to the top, move the following to lines before the line number 767:  `// Move to monitor`

The results looks like this (the below code starts at linenumber 759):
```js
    _populateMenu: function() {
        let mw = this.metaWindow;
        let item;
        let length;

        let subMenu = new PopupMenu.PopupSubMenuMenuItem(_("Preferences"));
        this.addMenuItem(subMenu);

        // Move to monitor
        if ((length = Main.layoutManager.monitors.length) == 2) {
```

Now just save the file and restart Cinnamon (CTRL+ALT+ESC) or restart your pc.

If you ever detect problems in the future (with this applet) or if you want to get the latest window-list applet version after a cinnamon update, you can just delete the local folder and repeat the above mentioned steps:
```
rm -r ~/.local/share/cinnamon/applets/window-list@cinnamon.org/
```

**Comment by derlucas** [comment]
Perfect. Working fine! Thanks!

**Comment by geckolinux** [comment]
I still think usability is more important than consistency. How often do most people access the preferences? Maybe once during the entire life of the system? But the close button is used all the time. So I think **Close** should be the first in order.

**Comment by NikoKrause** [comment]
If you use window-list applet on a top panel the last button gets the first and vice versa.
A similar issue holds for vertical panels.
