### ISSUE TITLE
NVIDIA 304.132 and Cinnamon (GeForce 7025).

### ISSUE THREAD

**Issue by Edgarkhxz7** [linuxmint/Cinnamon#5952]
I want to report a bug, I installed Linux Mint 18 and 17.2 and 17.3 Cinnamon, after installing the recommended driver (NVIDIA 304.132) and rebooting, the desktop doesn't launch and goes in Fallback mode instead, with MATE environment it works properly (At least on Linux Mint 17.3 and Linux Mint 18)

**Comment by JosephMcc** [comment]
Cinnamon is know to have issues with the Nvidia 304 driver.
Please add your info to https://github.com/linuxmint/Cinnamon/issues/5548
See also https://github.com/linuxmint/mintupdate/issues/187
