### ISSUE TITLE
open context menu on highligted window button in window-list applet unhighligts button

### ISSUE THREAD

**Issue by NikoKrause** [linuxmint/Cinnamon#5953]
Not sure what causes the bug, but it seems to happen in all themes.
I'm using the Mint-Y theme. The button of the window, which has the focus, is highlighted with a green line at the bottom. If I open the context menu of the window-list applet on this button, the green line disappears. And it doesn't come back if you close the context menu.

**Comment by JosephMcc** [comment]
https://github.com/linuxmint/Cinnamon/issues/5862

**Comment by NikoKrause** [comment]
Oh sorry, I definitely should google, before posting o.O
