### ISSUE TITLE
openSUSE Tumbleweed Cinnamon upgrade to 3.2.1 = no mouse

### ISSUE THREAD

**Issue by geckolinux** [linuxmint/Cinnamon#5954]
Hi there, I added X11:Cinnamon:Current to test it on my openSUSE Tumbleweed system, and upgraded from 3.0.7 to 3.2.1. So far, it seems quite issue-free, with one big exception: My USB mouse was not moving after upgrade. Fortunately my laptop's trackpad was still working, so I was able to open the mouse settings. I finally realized that the mouse acceleration slider was all the way to the left, which is apparently OFF. So after increasing it, the USB mouse now moves and works normally. But I didn't have it set that way before, so there must be some kind of setting that didn't get smoothly upgraded.

Related bug:
https://bugzilla.opensuse.org/show_bug.cgi?id=1009934

**Comment by leigh123linux** [comment]
I have done several upgrades and a clean install and haven't seen this issue on mint or fedora.
Can you reproduce the issue?  if not please close this report.

**Comment by XRevan86** [comment]
If you move it back to the left, USB mouse gets disabled again?
I'm using Cinnamon in a VM, so there are… complications in reproducing this :-).
VirtualBox's USB-mouse emulation works as expected though.

**Comment by geckolinux** [comment]
@XRevan86 
> If you move it back to the left, USB mouse gets disabled again?

No, it still continues to move as expected.

@leigh123linux  OK, I'll close this bug if you're confident that it won't hit a lot of people.
