### ISSUE TITLE
[Cinnamon 3.2] Window List applet "Preferences" in wrong order

### ISSUE THREAD

**Issue by geckolinux** [linuxmint/Cinnamon#5955]
Hello,

With the upgrade to Cinnamon 3.2, the Window List applet now shows context menu **Preferences** in first order instead of last order as it was on 3.0. This is a regression in my opinion, because the **Preferences** option is used much less than the **Close** option, which should have first priority.

Thanks!

![screenshot from 2016-11-13 20-06-00](https://cloud.githubusercontent.com/assets/2692138/20250463/04c84f60-a9dd-11e6-8ceb-5053b1a4665b.png)

**Comment by JosephMcc** [comment]
https://github.com/linuxmint/Cinnamon/issues/5950
