### ISSUE TITLE
Popup Menu :: Submenus :: Style Class Names Are Inconsistent

### ISSUE THREAD

**Issue by lots0logs** [linuxmint/Cinnamon#5956]
While working on documenting the structure of the menus (as it relates to theme development) I noticed that both `submenu` and `sub-menu` are used in style class names.  PR incoming....

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
