### ISSUE TITLE
"Lock computer when entering to the sleep mode" - does not work

### ISSUE THREAD

**Issue by DeadBread** [linuxmint/Cinnamon#5960]
I use Cinnamon 3.0.7 with Ubuntu 16.04
After "sudo apt upgrade" Cinnamon stopped locking the session after entering the sleep mode, even though all the checkmark in screensaver setting menu are on. 
When I try it with Unity it works fine.
What am I to do? What am I doing wrong?

**Comment by JosephMcc** [comment]
You have to provide more info than this. What was upgraded? Where do you install Cinnamon from? Is it from a PPA?

**Comment by DeadBread** [comment]
Yes, I've installed Cinnamon from PPA
Many things were updraded including:
cinnamon-session:amd64 (3.0.1-1~xenial0, 3.2.0-1~xenial0)
libcinnamon-menu-3-0:amd64 (3.0.2-1~xenial0, 3.2.0-1~xenial0)
gir1.2-cinnamondesktop-3.0:amd64 (3.0.2-1~xenial1, 3.2.0-1~xenial0)
cinnamon-session-common:amd64 (3.0.1-1~xenial0, 3.2.0-1~xenial0)
cinnamon-settings-daemon:amd64 (3.0.1-1~xenial0, 3.2.0-1~xenial0)
cinnamon-control-center-data:amd64 (3.0.1-1~xenial0, 3.2.0-1~xenial0)
cinnamon-l10n:amd64 (3.0.3-1~xenial0, 3.2.1-1~xenial0)

I listed everything of what was updated which contained the word "cinnamon".

**Comment by JosephMcc** [comment]
It looks like you need to contact the PPA maintainer. You have some package upgraded to 3.2 but I don't see others like cinnamon itself or cinnamon-screensaver which have some new dependencies. They may need some additional things added to the PPA.

**Comment by JosephMcc** [comment]
I'm closing this since it doesn't look your Cinnamon is properly updated. Some of the PPA's Ubuntu users are using have since been updated with all of the new dependencies.

**Comment by DeadBread** [comment]
Yes, you were right to close it. Thanx for your response. I' msorry for bothering you
