### ISSUE TITLE
Telegram Icon is not shown in the panel

### ISSUE THREAD

**Issue by Gameranand** [linuxmint/Cinnamon#5964]
I recently updated to Cinnamon 3.2 and now the Telegram icon in the panel is not showing, in its place its just showing blank space and when I click that black space then telegram options come.

I have already tried reinstallation of Telegram and removing and readding Systray Applet.

![image](https://cloud.githubusercontent.com/assets/11816991/20300665/28a552b0-ab46-11e6-852c-dcd0695a1905.png)

**Comment by JosephMcc** [comment]
https://github.com/linuxmint/Cinnamon/issues/5176

**Comment by Gameranand** [comment]
I already tried the re installation method. It didn't work. That is why I opened a issue. Please reopen it.

**Comment by JosephMcc** [comment]
> Please reopen it. 

Even if the solution posted in the other issue doesn't solve the issue for you, it's still a duplicate. You can add your info to the other issue.

**Comment by Gameranand** [comment]
OK. I'll do that. Thanks.

**Comment by Gameranand** [comment]
Anyway I found the alternative solution for the time being.

dbus-launch ~/.softwares/Telegram/Telegram start & disown
