### ISSUE TITLE
The design of Keboard Layouts window should be improved.

### ISSUE THREAD

**Issue by Vahan86** [linuxmint/Cinnamon#5967]
I think the design of Keyboard Layouts window should be improved and get more compact and polished look.

![433](https://cloud.githubusercontent.com/assets/12819058/20318008/f2d3e9e4-ab81-11e6-86bd-6260e7b11101.png)

**Comment by JosephMcc** [comment]
Wasted space isn't a good enough argument on this one :)
The size is tied to the other tabs, "Typing", and "Shortcuts". All three share the same size. If you have ideas to make it more "polished" feel free to share those.

**Comment by Vahan86** [comment]
@JosephMcc, agree with you. Honestly I didn't take into consideration the fact that all three tabs share the same size and window size cannot be changed during switching of those tabs.

**Comment by NikoKrause** [comment]
There are new options in 3.2:
![bildschirmfoto vom 2016-11-15 23-04-42](https://cloud.githubusercontent.com/assets/8415124/20326357/ad3791e0-ab88-11e6-9e9b-cd795f8249ba.png)
So it's not (totally) unused ;)
