### ISSUE TITLE
Cinnamon widgets unable to gain focus

### ISSUE THREAD

**Issue by germanfr** [linuxmint/Cinnamon#5968]
After these steps cinnamon is unable to give focus to the menu search input and Cinnamon dialog buttons become unresponsive to clicks.
 1. In the menu: add program to panel.
 2. In the panel launcher: **remove launcher shortcut**.
 3. Open the menu and try to search. Open any applet's about dialog and try to close it.

This is on Cinnamon 3.2.1

**Comment by JosephMcc** [comment]
I can reproduce this.

**Comment by JosephMcc** [comment]
Here are the errors thrown when doing this http://pastebin.com/aQzhpddF

**Comment by vladimir-didenko** [comment]
Looks like duplicate for https://github.com/linuxmint/Cinnamon/issues/5937
