### ISSUE TITLE
Window List menu - usability regression with top panel

### ISSUE THREAD

**Issue by gwvr** [linuxmint/cinnamon#5969]
I'm in the habit of closing windows by right clicking on the panel window list to open the menu and then clicking `close`. Under previous versions of Cinnamon this required the minimum of mouse mileage. With the panel at the bottom, close was the bottom (first) item on the menu, and with the panel at the top it was the top (still first) item. I found this particularly useful for closing unfocused windows quickly, but now the extra mouse mileage makes this much more fiddly.

With Cinnamon 3.2.1+betsy and the panel at the bottom `preferences` is the first item in the list and `close` is second.
With the panel at the top `preferences` is the last item in the list and `close` is second last.

This is both inconsistent with previous versions, and interferes with my workflow. I know it seems minor, but I'm finding it *really* annoying.. Please could the order of the menu items be either reverted or made customisable?

Old behaviour:
![cinnamon_panel_window_list_menu_old](https://cloud.githubusercontent.com/assets/2746263/20322097/ac5fa802-ab6f-11e6-84bd-72383247b492.png)

New behaviour:
![cinnamon_panel_window_list_menu_new](https://cloud.githubusercontent.com/assets/2746263/20322125/c2df7d50-ab6f-11e6-98b4-69a05c1f0c4f.png)

**Comment by leigh123linux** [comment]
Get used to it as it isn't going to be reverted.

https://github.com/linuxmint/Cinnamon/issues/5935

**Comment by Piiit** [comment]
You could use middle mouse click to close windows from taskbar quickly. I think that is the fastest way afaik.

**Comment by Piiit** [comment]
@leigh123linux I think you thought of boxpointers, but that is not the issue here. He talks about "Close" being the closest menuitem to the taskbar, in order to reach it faster than all other items. Which IMO makes perfect sense, because it is the most used function in this menu I guess.

I would create the menu as follows (smaller number means closer to the taskbar):
1) Close
2) Close Others
3) Close All
4) Minimise
5) Maximise
6) Move to...
7) Visible on ...
8) Preferences...

What do you think?

ps. About my previous comment: Middle-mouse click to close must be configured for the panel... right-click > Preferences > ...

**Comment by leigh123linux** [comment]
@Piiit Your right.

**Comment by lots0logs** [comment]
Perhaps the order of menu items should be reversed for top panels (that way the order of items relative to the panel itself is the same for top & bottom panels)

**Comment by gwvr** [comment]
@leigh123linux in reference to your previous deleted comment, you're all heart ;-)
I wasn't even sure what a box pointer is.. I now understand why you've ripped them out, but that's a separate issue.

@Piiit thanks for reminding me about the middle-click to close functionality - I'd long forgotten about that.

I think that Piiit's suggested menu item order is pretty sensible, as is the older ordering.

**Comment by germanfr** [comment]
I've submitted a pull request for this. It looks like this:
![screenshot from 2016-11-16 17-16-38](https://cloud.githubusercontent.com/assets/10391266/20358023/8dc5bb3c-ac2a-11e6-8612-9de4dbe18560.png)

**Comment by gwvr** [comment]
@germanfr That looks good!

I notice that I'm missing a couple of the menu list icons (`close all` and `minimise`).
I'm using Betsy with the Mint-X Window borders, icons and controls, but I guess I'm missing some of the bleeding edge package updates (not to mention Mint-Y because Betsy)?

**Comment by icarter09** [comment]
We believe this issue is fixed. Please test against the latest Cinnamon version (4.2). 
If the issue happens again, create a new issue and add the output of "cinnamon-settings sound".
