### ISSUE TITLE
Segfault in Cinnamon 3.0.7 when starting new session

### ISSUE THREAD

**Issue by jnpwly** [linuxmint/Cinnamon#5970]
For about the last week, whenever I log into my machine, the new Cinnamon session fails to start correctly, and I see a message, "Cinnamon just crashed. You are currently running in Fallback Mode. Do you wish to restart Cinnamon?" Answering "Yes" never seems to succeed.

Having tried this a few times, dmesg gives the following output:

```
[ 3524.674247] cinnamon[2759]: segfault at 0 ip 00007f320f32c4be sp 00007ffc07d93e20 error 4 in libc-2.23.so[7f320f29f000+1bf000]
[ 4205.448304] cinnamon[5101]: segfault at 0 ip 00007f5805e864be sp 00007ffd00866df0 error 4 in libc-2.23.so[7f5805df9000+1bf000]
[ 4273.563079] cinnamon[5716]: segfault at 0 ip 00007f7dbbcd34be sp 00007ffce7c52a50 error 4 in libc-2.23.so[7f7dbbc46000+1bf000]
[ 4733.032865] cinnamon[6645]: segfault at 0 ip 00007f93b46a14be sp 00007ffd2cf09510 error 4 in libc-2.23.so[7f93b4614000+1bf000]
[ 4810.044946] cinnamon[6906]: segfault at 0 ip 00007fd96d30a4be sp 00007fff7b0f6670 error 4 in libc-2.23.so[7fd96d27d000+1bf000]
[ 4815.100088] cinnamon[6937]: segfault at 0 ip 00007fc5cf63b4be sp 00007ffd44f8d4d0 error 4 in libc-2.23.so[7fc5cf5ae000+1bf000]
```

I would guess that there are more details that could be obtained from a suitable log file... I'm afraid I don't know which.

Using Linux Mint 18 'Sarah' (Cinnamon 64-bit)

```
jon@black ~ $ /usr/bin/cinnamon --version
Cinnamon 3.0.7
jon@black ~ $ uname -a
Linux black 4.4.0-47-generic #68-Ubuntu SMP Wed Oct 26 19:39:52 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
jon@black ~ $
```

With suitable direction, I can provide whatever additional information is needed.

**Comment by mtwebster** [comment]
You can check the contents of `~/.xsession-errors` - it may have something pertinent.

What video driver do you use?  What version of mdm are you running?

**Comment by jnpwly** [comment]
Thanks, @mtwebster, for pushing me in the proper direction.

```
jon@black ~ $ /usr/sbin/mdm --version
MDM 2.0.10
```

I am using the NVIDIA driver; specifically, nvidia-304. It appears to be soemthing like version 304.132, since the following directories exist:

```
/var/lib/dkms/nvidia-304
/var/lib/dkms/nvidia-304/304.132
/var/lib/dkms/nvidia-304/kernel-4.4.0-45-generic-x86_64
/var/lib/dkms/nvidia-304/kernel-4.4.0-47-generic-x86_64
/var/lib/dkms/nvidia-304/304.132/4.4.0-45-generic
/var/lib/dkms/nvidia-304/304.132/4.4.0-47-generic
/var/lib/dkms/nvidia-304/304.132/build
/var/lib/dkms/nvidia-304/304.132/source
...
```

My ~/.xsession-errors is attached. I don't know that it shows a great deal of useful info though. The only Cinnamon related thing is to do with not being able to bind a certain key combination. Hmm?

[xsession-errors.txt](https://github.com/linuxmint/Cinnamon/files/593390/xsession-errors.txt)

**Comment by clefebvre** [comment]
It's an issue with NVIDIA 304.132 afaik. The solution is to downgrade to 304.114.

More details at https://forums.linuxmint.com/viewtopic.php?f=49&t=233050&p=1238112#p1238112.

**Comment by jnpwly** [comment]
Perfect, many thanks, @clefebvre

**Comment by spaceone** [comment]
I have the same issue on linuxmint 18.3. Is there any other solution thatn installgin NVIDIA 304.114 (which is not available anymore in the package lists). Nouveou is also crashing with other problems. Would installing linuxmint 19 help?
