### ISSUE TITLE
No icons on main monitor with Cinnamon 3.2.1

### ISSUE THREAD

**Issue by Wini-Buh** [linuxmint/Cinnamon#5973]
I have a two monitor solution (both monitor with the same resolution). After the update of Cinnamon (trough mindUpdate) from 3.0.7 to 3.2.1 all icons on desktop on the main monitor are gone. 

The content of the Desktop directory is still there, means I see the documents, etc. that were placed on the desktop on the main monitor. I could place all documents, etc on the desktop on the main monitor... logout and after logged in, the the desktop on the main monitor is empty again. This also happens to new created content, which is located on the desktop on the main monitor. 

The same also happens to icons from the system i.e. the trash... In the settings the trash is on, but there is no icon on the main desktop... I need to switch off and on again to see it (until the next time I logged out and logged in).

IOW... this means the desktop will be empty after each login but NOT after login if the desktop was locked.

I did not made any changes in the preferences of the desktop after the update and I don't have any extension, applets, etc. installed (except the ones coming directly with Cinnamon).

**Addendum**:
The behavior is easily reproducible. Install LMDE2 into a virtual machine (I used VirtualBox 5.0) setup your emulated hardware before you start the installation. 
- Define a setup with two monitors and start the installation... After the installation is finished DO NOT update your installation trough mindUpdate !  Instead configure your two monitor solution (for example right monitor is the main screen and disable screen mirroring). 
- Create two empty documents on the desktop (for example "right desktop" and "left desktop") and place one document on left and the other on the right monitor. Logout and login and check if the documents are still on their desktop. 
- Now start the update with mindUpdate and update all to the latest versions.
- After Update is finished restart the system to activate the updated installation
Maybe you need to setup the monitor configuration again (at least I needed to do so). Logoff and Login and now all icons on the main desktop are gone.

If you you have problems with the presentation of the GUI inside the virtual machine after the update to the latest versions, try to restart Cinnamon with Ctrl-Alt-Esc (for me it worked).

I hope this helps to show/solve the problem.

**Comment by leigh123linux** [comment]
Please refile the issue against nemo as that draws desktop icons
