### ISSUE TITLE
No visual indication of selected option when using keyboard.

### ISSUE THREAD

**Issue by SteegHobland** [linuxmint/Cinnamon#5980]
When tabbing through checkboxes or pull-down menus, the currently selected one is **not** highlighted, outlined, or otherwise visually indicated. This makes it difficult to set things in the GUI without using a pointing device.

**Comment by Odyseus** [comment]
Hello, @SteegHobland.

This is more of a theme issue than Cinnamon's. If you switch the controls to use Adwaita, you will see that checkboxes, etc. are highlighted when one navigates through them with the keyboard.
