### ISSUE TITLE
Remove Pithos from the can't seek list.

### ISSUE THREAD

**Issue by JasonLG1979** [linuxmint/cinnamon#5983]
Pithos can't actually seek but it does provide a valid mpris:length in the metadata and a valid Position prop and we workaround SetPosition Method calls. 

The sort term solution to showing track time info for Pithos in your applet is to remove Pithos from the can't seek list.

The long term solution is to not depend on the CanSeek prop to determine if the track time info is shown and instead check if a player provides a valid mpris:length in the metadata and a valid Position prop. And use CanSeek to toggle if the widget can be interacted with.

**Comment by JasonLG1979** [comment]
Update: Pithos ofc still can't actually seek, but it can and does always report a valid Position and  mpris:length. That is what *should* matter as far as when/if to show the position.

I recently changed the logic in https://github.com/eonpatapon/gnome-shell-extensions-mediaplayer to the above mentioned behavior; i.e. CanSeek toggles the sensitivity of the slider not the visibility. As long as a player can give a position and  mpris:length the time slider is shown. You should consider something similar. White/Blacklist are not the way to go here. They are not very maintainable...

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
