### ISSUE TITLE
cs_backgrounds.py - LMDE 2 - No wallpapers shown after Sept 12 2016 changes.

### ISSUE THREAD

**Issue by rwpreece** [linuxmint/Cinnamon#5986]
In Cinnamon Settings, the Backgrounds settings window does not display any wallpapers.  If I run cinnamon-settings from a terminal and use the Backgrounds settings, when selecting one of the folders to view the available wallpapers, a "Failed to convert <filename>... width" for each file in the selected folder.

It looks like the changes implemented on Sept 12, 2016 may be the cause.  If I use the cs_backgrounds.py from Setp 11, 2016, it works and wallpapers are displayed.

I suspect it's in the "_image_to_pixbuf(self, img)" code.

I suspect there is some dependency missing in my installation of LMDE 2.  I freshly installed it yesterday (November 18th) and then applied all the updates.  

Let me know if you have any questions.

Thanks,
Roger

**Comment by itzexor** [comment]
There is a PR open #5979 to fix this.

**Comment by rwpreece** [comment]
Thank you sir. Sorry to bother you. I must have over looked that one when
I  searched for a bug having already  been logged  for this.
