### ISSUE TITLE
Shut down and restart doesn't work only come up a dialog

### ISSUE THREAD

**Issue by LeaderSoul** [linuxmint/Cinnamon#5988]
Hello
I am very beginner in this things. I installed ubuntu yesterday on my computer because windows 10 said good bye :P and I thought if I use ubuntu will be better. But when I installed Cinnamon after ubuntu install then I can't shutdown or restart my computer.
When I click to Shutdown, Restart, Power off or/and Quit button then I get this only:
https://www.youtube.com/watch?v=mPjQkPQrZBg&feature=youtu.be

I followed this tutorial: http://www.omgubuntu.co.uk/2016/04/how-to-install-cinnamon-3-0-on-ubuntu
I read that I must run this command if I want fix this issue:

gsettings set org.cinnamon.desktop.session settings-daemon-uses-logind true
gsettings set org.cinnamon.desktop.session session-manager-uses-logind true
gsettings set org.cinnamon.desktop.session screensaver-uses-logind false

But didn't fixed...
I use Ubuntu 16.04 xenial (x86-64) and Cinnamon 3.2.1.

**Comment by JosephMcc** [comment]
At least at some point that PPA wasn't fully up-to-date for Cinnamon3.2. Taking a quick look it seems to have all the required things now. Make sure you are fully updated and restart your system.

**Comment by Vahan86** [comment]
@JosephMcc, can we close the issue?
