### ISSUE TITLE
[Bug] Panel Completely click-through in 3.2

### ISSUE THREAD

**Issue by feren** [linuxmint/Cinnamon#5989]
In Cinnamon 3.2, for some reason, in its current state, the panel is completely click-through and just sends clicks to the Nemo desktop window instead...
Repositories used that have the same bug:

- Gwendal Le Hiban Unstable
- Changing 'official-package-repositories' to point to Serena's repositories

Not affected: Cinnamon 3.0
The panel will still work nonetheless, I can still use keyboard shortcuts and the applet menus still work...
UPDATE: The default applets don't help either

**Comment by feren** [comment]
Video: https://www.dropbox.com/s/e2lh4xu6r92zys4/Bug.mp4

**Comment by feren** [comment]
...also, windows themselves aren't affected, though, on the first upgrade of Cinnamon, the windows couldn't even be clicked on...

**Comment by JosephMcc** [comment]
https://github.com/linuxmint/Cinnamon/issues/5984
