### ISSUE TITLE
Time on the panel is not updated immediately after resuming from suspend

### ISSUE THREAD

**Issue by marmistrz** [linuxmint/Cinnamon#5990]
Today after resuming my laptop from suspend, the time was stuck of the value before suspend. After ~1 minute the time was updated properly.

Probably the time should be force updated after waking up from suspend.

If you let me know where the relevant functionality resides, I can make a pull request.

**Comment by JosephMcc** [comment]
https://github.com/linuxmint/Cinnamon/issues/5386
