### ISSUE TITLE
[Question] Differentiating Popup Menu and Menu Appearance in 3.2

### ISSUE THREAD

**Issue by feren** [linuxmint/Cinnamon#5992]
This is related to the borders bug, but is there still a way to theme Menus (Cinnamon Menu, CinnXPStarkMenu, etc) differently to Popup Menus in Cinnamon?

**Comment by feren** [comment]
If someone could point me a way to do so if there is, it'll help a lot with patching some themes for 3.2...

**Comment by JosephMcc** [comment]
See https://github.com/linuxmint/Cinnamon/issues/5934
This isn't really a support forum.
