### ISSUE TITLE
Desktop Settings Reads 'DesktopSettings'

### ISSUE THREAD

**Issue by feren** [linuxmint/Cinnamon#5993]
Desktop Settings in the desktop right-click context menu says 'DesktopSettings' in 3.2

**Comment by JosephMcc** [comment]
I can't reproduce this here and that menu actually comes from Nemo.

**Comment by feren** [comment]
Odd, when I changed the repositories of LM 18.1 to Serena to do some testing to help Cinnamon 3.2 become stable, it said 'DesktopSettings' on the Nemo right-click menu, nevermind, downgraded back to Sarah repositories now...

**Comment by leigh123linux** [comment]
@JosephMcc  you either have old nemo version or your local isn't set  en_GB

**Comment by JosephMcc** [comment]
That certainly isn't my locale :)
It isn't a Cinnamon issue in any case and thanks for the fix.

**Comment by feren** [comment]
Thanks.

**Comment by feren** [comment]
Can this be reopened? I'm getting this bug on the latest Serena Packages on Locale en_gb:
![screenshot from 2016-12-10 10-19-25](https://cloud.githubusercontent.com/assets/11057934/21072671/28185dee-bec2-11e6-875c-8802808366f2.png)

**Comment by feren** [comment]
...same with Nemo when Desktop Icons are enabled...

**Comment by leigh123linux** [comment]
No you can't reopen it!, be patient, stop spamming us and wait for the next nemo release!

https://github.com/linuxmint/nemo/commit/b6560b20624f2079b35e0503a9e3d0cc3e659bc6

**Comment by feren** [comment]
Oh ok, sorry...
PS: Would this be on LM 18.1 sir?
