### ISSUE TITLE
Applet vertical aligment problem

### ISSUE THREAD

**Issue by kolorafa** [linuxmint/Cinnamon#5994]
After last updated the whole applet content did somehow get "pushed" down, icons are sticking to the bottom of the screen.

![](http://kolorafa.firehost.pl/test/snapshot-2016-11-21-21-56-04.png)

There is too much space at the top and to little at the bottom.

The strange part is that the second applet on second screen looks more or less normal.

Good looking (second panel):
![](http://kolorafa.firehost.pl/test/snapshot-2016-11-21-22-01-09.png)

The main panel (with wrong spacing):
![](http://kolorafa.firehost.pl/test/snapshot-2016-11-21-22-01-44.png)

**Comment by kolorafa** [comment]
The menu looks like ......


![](http://kolorafa.firehost.pl/test/snapshot-2016-11-21-22-06-27.png)

**Comment by JosephMcc** [comment]
You need to provide better info. Which update to what? What theme are you using? Do you still have the issue when using the default Cinnamon theme? A good number of things changed in Cinnamon3.2.

**Comment by kolorafa** [comment]
I'm using the default theme that is provided on Arch linux

Numix-Frost-Light
Adwaita
...
Numix-Frost

And after last updates (i didn't exactly look what did update ...) but everything looks horrible :/

**Comment by kolorafa** [comment]
I see .. i did switch to numix-frost for borders and  'cinnamon' for desktop and looks way better, i need to look more into it..

**Comment by JosephMcc** [comment]
Themes need some updating for 3.2. You need to make sure it's reported to the theme dev.
