### ISSUE TITLE
Add .odt thumbnail option to nemo in Linux Mint 18.1

### ISSUE THREAD

**Issue by freemangilgamesh** [linuxmint/Cinnamon#5995]
The only software that creates thumbnails for .odt file is ooo-thumbnailer and it's quiet buggy that I had to work around it to get it display thumbnails  https://forums.linuxmint.com/viewtopic.php?f=47&t=234142

Please include this option in nemo by  default.

<a href='https://postimg.org/image/rp059qrrf/' target='_blank'><img src='https://s17.postimg.org/pkfs8nq4v/Screenshot_from_2016_11_21_23_34_12.png' border='0' alt='Screenshot from 2016-11-21 23-34-12'/><br /><a target='_blank' href='https://postimage.org/'>image upload no compression</a><br /><br />

<a href='https://postimg.org/image/fayi1r5nd/' target='_blank'><img src='https://s4.postimg.org/lonl50ajh/eeee.png' border='0' alt='eeee'/><br /><a target='_blank' href='https://postimage.org/'>upload pictures</a><br /><br />

**Comment by JosephMcc** [comment]
This isn't the place for posting Nemo issues. Please don't jump around every Mint repo asking for 3rd party stuff to be included by default.

**Comment by freemangilgamesh** [comment]
you tell the Mint team about it sir! This github is quite confusing!
