### ISSUE TITLE
windows change Monitor after standby - Dual Monitor

### ISSUE THREAD

**Issue by ikarus13** [linuxmint/cinnamon#6006]
After wake up the system from suspend the application windows change from left to right Monitor.
After long searching i found the reason: My main monitor is a Samsung T260 and when i change the menu entry (monitor settings) mode from video to monitor everything works fine. I think, the reason ist, it now faster comes up. If it is to slow cinnamon can't place the window on the properly monitor because its not available. I think, cinnamon shoult wail a little bit longer before replace the app window.
Hope this discription (in very bad english, sorry for that) helps other people with the same problem.
This error appears in cinnamon 2.8.6 and cinamon 3

**Comment by icarter09** [comment]
@ikarus13 are you still experiencing this issue?

**Comment by Vahan86** [comment]
@icarter09, can we close this issue?
