### ISSUE TITLE
Unable to open applet config

### ISSUE THREAD

**Issue by hillexed** [linuxmint/Cinnamon#6008]
I just updated to Cinnamon 3.2.2, and I went to configure a new window list applet I installed, but when I clicked the "Configure" button in the Applets menu nothing popped up. 

To try and find an error message, I ran the Applets menu from the terminal:
```$ cinnamon-settings applets
Loading Applets module

(cinnamon-settings.py:4434): Gtk-WARNING **: Symbolic icon pan-down-symbolic-ltr of size 16 is in an icon theme directory of size 128 
```

This seems like a normal warning message to me, and everything works as normal - I can install applets, scroll, add them to the panel, etc.
When I click the "Configure" button, however, it outputs this:
```
Traceback (most recent call last):
  File "/usr/share/cinnamon/cinnamon-settings/xlet-settings.py", line 3, in <module>
    import gi
ImportError: No module named 'gi'
```

and the configuration window does not appear. I'm running LMDE 2, having updated via the update manager.

**Comment by Odyseus** [comment]
Hello, @hillexed.

Look at this two issues with your exact same problem (#4906 and #4421). You might find a solution in there.

**Comment by leigh123linux** [comment]
Is python-gi installed?, it's a listed requirement.

https://github.com/linuxmint/Cinnamon/blob/master/debian/control#L89

Also have you been mucking around with python env (overridden system python?).

**Comment by hillexed** [comment]
Python-gi and other requirements are all installed. Thanks for those issues; thanks to them, I think I found the problem: in addition to the `python` installed through apt-get, I also use [Anaconda](https://www.continuum.io/downloads) for scientific computing, which inserts itself into the PATH as the default `python3`. `/usr/bin/python3` still exists, but since it's not being used, cinnamon-settings probably isn't finding python-gi and the other modules needed to run.  

Editing the first line of `/usr/share/cinnamon/cinnamon-settings/xlet-settings.py` to `!/usr/bin/env python2` (since python2 isn't touched by anaconda) fixes the problem.

Anaconda is commonly used for scientific computing; it's a shame that cinnamon breaks simply by following their instructions to install it. It would be nice if there was some way of specifying /usr/bin/python3 to be used, but that probably alienates any users with non-standard python installations. Hmm.

Thanks!

**Comment by leigh123linux** [comment]
Anaconda has no right to replace system python, the issue is their broken software.

**Comment by hillexed** [comment]
@leigh123linux just to clarify - it doesn't replace the system python, it just prepends its folder to $PATH so the environment uses anaconda's python instead of /usr/bin/python. That PR should fix all issues for good and allow anaconda and cinnamon to peacefully coexist once again.

Thanks again for all the help!

**Comment by lestcape** [comment]
@hillexed this is not only move a line, this is decide which python version will be execute, this is: change the logical of the python base string encode for mention one important thing, cinnamon don't use anaconda's python, and not care abut it... The anaconda can do his things in a good way, if they want to coexist with other software if they don't want that, and you have a problem with it, open an issue in the anaconda side, not here. I don't see here anything wrong.
