### ISSUE TITLE
Cinnamon Settings Backgrounds

### ISSUE THREAD

**Issue by theoar** [linuxmint/Cinnamon#6009]
I have one problem with Cinnamon Setting Backgrounds. 
Everything is ok, except of displaying the miniatures of wallpapers.
Cinnamon version: 3.2.1

![zrzut ekranu z 2016-11-23 23 28 54](https://cloud.githubusercontent.com/assets/6282165/20580762/9dc7ec58-b1d4-11e6-890e-43e8560344ee.png)

**Comment by JosephMcc** [comment]
This is already fixed in git master. Hopefully you will see an update go out soon.
