### ISSUE TITLE
Calendar applet gets stuck open in panel

### ISSUE THREAD

**Issue by Austint30** [linuxmint/Cinnamon#6012]
I found an issue with the Calendar applet where the menu would get stuck open after clicking and moving the cursor back and forth between the menu and the panel. The applet starts creating more menu backgrounds that cannot be closed. The only way to temporarily fix the issue is by restarting cinnamon.

Picture:
http://i.imgur.com/aTCevHR.png

**Comment by leigh123linux** [comment]
What cinnamon version?

**Comment by Austint30** [comment]
I am using 17.3 64 bit.

**Comment by JosephMcc** [comment]
That's not the Cinnamon version :)
17.3 has a version of Cinnamon a good bit older than the current one. Menus have been completely rewritten since then and I can't reproduce this.
