### ISSUE TITLE
Suggestion, re power management applet: double-click to toggle

### ISSUE THREAD

**Issue by ghost** [linuxmint/cinnamon#6019]
It would be intuitive, and usefully quick, to be able to toggle power management (and notifications?) by double-clicking the power management applet.

Mint 18 x64 Cinnamon 3.0.7.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
