### ISSUE TITLE
[Feature Request] Optional Panel Blur BG (without the image overlay)

### ISSUE THREAD

**Issue by feren** [linuxmint/Cinnamon#6025]
It'd be nice to be able to blur whatever is behind the panel in Cinnamon **without using bumpmaps**, even if it was optional...

**Comment by JosephMcc** [comment]
If you're going to open so many issues, please learn to use the search function.
https://github.com/linuxmint/Cinnamon/issues/3466

**Comment by feren** [comment]
Sorry, forgot about this one... (BTW, if the feature is secretly in Cinnamon, how come it won't work anymore in 3.0 if you use the code on a panel?)
