### ISSUE TITLE
The autohide panel option can not be controlled outside of the panel.

### ISSUE THREAD

**Issue by lestcape** [linuxmint/Cinnamon#6028]
When we set a panel autohide option, We will think that our panel will be visible when an applet popup menu it's open. This will work, if the mouse cause an open state change on the popup menu, but not if this is because a key combination trigger the open state change of the popup.

One solution to this problem could be: use the popupmenu launcher and if it's an instance of an applet, then localize the panel where the instance it's located. Change the panel._mouseEntered value to true and then update again the panel visibility whatever a popup menu will be opened. But this work-flow will only solved this specific problem.

There are a lot of scenarios where the panel will need to be forced for an specific state (show or hidden), that's can not be then only a responsibility of the panel it self. In some cases, the extension that trigger a popupmenu open action, it's the only one that know what it's the aspect behaviour of a panel and have not a good way to tell him about that.

**Comment by JosephMcc** [comment]
Don't see any reason you couldn't add public functions to show/hide the panels if you have use for them.

**Comment by lestcape** [comment]
Yes i have used for that: https://github.com/lestcape/Global-AppMenu/issues/42

**Comment by ashpynov** [comment]
One of scenario is:

I want to have auto-hide panel (well the intellihide panel) with full main menu opened automaticaly. But I want that will not prevent panel hiding since no submenu i opened. And it will hide as soon as sumenu is closed and mouse out of main menu.
