### ISSUE TITLE
Power Off displays on lockscreen

### ISSUE THREAD

**Issue by dk-zero-cool** [linuxmint/cinnamon#6029]
Cinnamon is starting to become the only stable desktop left that does not look and feel to much like 1995. Gnome Shell get's worse with each update and Unity have never worked. I really don't have much issue with Cinnamon except for one thing. I normally lock my computers by keyboard shutcuts, mostly because the lock screen has always powered off my displays. This has been a great feature, especially for my desktop with multiple displays attached. It's a fast way to turn things off and then quickly back on with a tap on a keyboard button or a touch with the mouse. 

This is sadly not working with Mint. I was hoping for this in the last release, but still nothing. Is there any chance that this could be added?

**Comment by Salamandar** [comment]
+1 !
The new sound shortcuts on lockscreen are really great, please continue with that :)

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
