### ISSUE TITLE
Right click behaves like left click on Fedora 25

### ISSUE THREAD

**Issue by aries1980** [linuxmint/Cinnamon#6030]
Hi,

I recently upgraded to Fedora 25 and might right click started to behave like left click in all applications. If I switch to Gnome, the right click works as expected.

The following packages are installed:

cinnamon-menus-3.2.0-1.fc25.x86_64
cinnamon-session-3.2.0-1.fc25.x86_64
cinnamon-control-center-3.2.0-1.fc25.x86_64
cinnamon-screensaver-3.2.6-1.fc25.x86_64
cinnamon-settings-daemon-3.2.0-1.fc25.x86_64
cinnamon-control-center-filesystem-3.2.0-1.fc25.x86_64
cinnamon-desktop-3.2.1-2.fc25.x86_64
cinnamon-3.2.2-1.fc25.x86_64
cinnamon-translations-3.2.0-1.fc25.noarch

If I use libinput-debug-events, the events are separate for the two clicks:

 event4 	POINTER_BUTTON   +14.63s	BTN_RIGHT (273) pressed, seat count: 1
 event4 	POINTER_BUTTON   +14.74s	BTN_RIGHT (273) released, seat count: 0
 event4 	POINTER_BUTTON   +16.28s	BTN_LEFT (272) pressed, seat count: 1
 event4 	POINTER_BUTTON   +16.37s	BTN_LEFT (272) released, seat count: 0

What else shall I try?

Thanks, Janos

**Comment by leigh123linux** [comment]
What device?

**Comment by aries1980** [comment]
Asus N550JK, touchpad.

Device:           ETPS/2 Elantech Touchpad
Kernel:           /dev/input/event4
Group:            8
Seat:             seat0, default
Size:             99.90x66.22mm
Capabilities:     pointer 
Tap-to-click:     disabled
Tap-and-drag:     enabled
Tap drag lock:    disabled
Left-handed:      disabled
Nat.scrolling:    disabled
Middle emulation: disabled
Calibration:      n/a
Scroll methods:   *two-finger edge 
Click methods:    *button-areas clickfinger 
Disable-w-typing: enabled
Accel profiles:   none
Rotation:         n/a

Device:           ETPS/2 Elantech Touchpad
Kernel:           /dev/input/event4
Group:            8
Seat:             seat0, default
Size:             99.90x66.22mm
Capabilities:     pointer 
Tap-to-click:     disabled
Tap-and-drag:     enabled
Tap drag lock:    disabled
Left-handed:      disabled
Nat.scrolling:    disabled
Middle emulation: disabled
Calibration:      n/a
Scroll methods:   *two-finger edge 
Click methods:    *button-areas clickfinger 
Disable-w-typing: enabled
Accel profiles:   none
Rotation:         n/a

**Comment by leigh123linux** [comment]
So it's a buttonless touchpad?, this update might help.

https://bodhi.fedoraproject.org/updates/FEDORA-2016-f8effad0bd

**Comment by aries1980** [comment]
It solved the probem. Thank you so much!
