### ISSUE TITLE
A gap in the vertical panel, when the horizontal one is set to autohide

### ISSUE THREAD

**Issue by ExpressCard** [linuxmint/Cinnamon#6031]
Hi there, I've just come across this issue. When I enable the vertical and horizontal panel and set the horizontal one to autohide, there's always a gap at the place, where two panels cross each other, when the horizontal panel is hidden. I did not have this problem with MATE desktop, though, therefore I consider this a bug. See the attached pictures bellow.
![shown](https://cloud.githubusercontent.com/assets/24259552/20733771/8cb99996-b695-11e6-8084-385d9e6eb5c9.png)
![hidden](https://cloud.githubusercontent.com/assets/24259552/20733779/920d86aa-b695-11e6-874e-25ccde3f24d2.png)

**Comment by lestcape** [comment]
See the next 5 comments: https://github.com/linuxmint/Cinnamon/pull/4996#issuecomment-207847965

**Comment by ExpressCard** [comment]
Thanks for your reply.
