### ISSUE TITLE
[Feature Request] User Image as optional icon for the user Applet

### ISSUE THREAD

**Issue by feren** [linuxmint/cinnamon#6033]
It would be nice for an option on user@cinnamon.org to have the user's image (where applicable) as the icon for the user applet rather than the user icon of the system's icon set...

**Comment by NikoKrause** [comment]
I don't get, what is requested?

**Comment by feren** [comment]
Basically, if you turned on an option that'd be made if this was a feature, **the applet's icon on the panel would be of the User's Picture rather than** the same-old user icon you get from your icon set...

**Comment by leigh123linux** [comment]
You can already set this to use whatever .png image you want by clicking on the icon which opens the settings.

**Comment by feren** [comment]
@leigh123linux I don't mean that image, I mean the icon that's on the panel itself.

**Comment by leigh123linux** [comment]
I doubt they will change the current symbolic icon.

@clem ^^?

**Comment by feren** [comment]
@leigh123linux @clefebvre I mean maybe as an option to change it to your user picture...

**Comment by NikoKrause** [comment]
@feren 
You mean like the sound-applet shows the album cover in the panel, when the option is activated?

**Comment by feren** [comment]
@NikoKrause Yeah

**Comment by feren** [comment]
@NikoKrause Shall we have this reopened with the Feature Request tag, or is this going to be a quick easy addition to Git Cinnamon?

**Comment by NikoKrause** [comment]
This is something I should be able to implement, I think.
I'm not sure though if this feature should be implemented.
You have to ask the Cinnamon devs, if they think it's something they want to or not.

**Comment by feren** [comment]
@NikoKrause It'd be a simple as something like (if ~/.face exists) or (if ~/.face.icon exists) > Change the Applet icon to the image it found...

**Comment by NikoKrause** [comment]
It's not a question about, if this feature is easy to implement or not. It's a question about, if this feature is wanted/needed in Cinnamon.
I don't think that there are a lot of people, if any, who would use it.

**Comment by feren** [comment]
Shall we have this reopened so the developers notice this and think about it?

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
