### ISSUE TITLE
[Welcome Screen] Position of tooltips should be fixed.

### ISSUE THREAD

**Issue by Vahan86** [linuxmint/Cinnamon#6035]
When you hover over the mouse pointer on link-icon (New features, Documentations, Apps, etc.) the tooltip appears which is too far from the mouse pointer and selected icon. 

![welcome screen_010](https://cloud.githubusercontent.com/assets/12819058/20795977/6534b262-b7ed-11e6-9227-7b70cdc317c8.png)

**Comment by JosephMcc** [comment]
Not sure exactly why this happens but it isn't a Cinnamon issue. Tested in Mate and it behaves strangely there as well.

**Comment by Vahan86** [comment]
Well, in that case I will open this issue here: https://github.com/linuxmint/mintwelcome/issues .
