### ISSUE TITLE
Please remove "synaptic" as search term (key word) for the Mouse and Touchpad tool

### ISSUE THREAD

**Issue by Pjotr123** [linuxmint/Cinnamon#6036]
When I want to launch Synaptic Package Manager, I type "synaptic" in the menu search field of Cinnamon. But number one in the search results is always the "Mouse and touchpad" application, and Synaptic is always second. So rather often, I mistakenly launch the mouse and touchpad app.

The root of the problem is, that the word "synaptic" is hardcoded in Cinnamon, as one of the searchable key words for the tool for mouse and touchpad:
https://translations.launchpad.net/linuxmint/latest/+pots/cinnamon/en_GB/+translate?batch=10&show=all&search=synaptic

Please remove this small annoyance....

**Comment by leigh123linux** [comment]
You could try using a different search term i.e package

**Comment by germanfr** [comment]
As a solution for you, you can remove that term on your computer.
Edit `/usr/share/applications/cinnamon-settings-mouse.desktop` and replace `Keywords=mouse;touchpad;synaptic;double-click;` with `Keywords=mouse;touchpad;double-click;` on [line 224](https://github.com/linuxmint/Cinnamon/blob/master/files/usr/share/applications/cinnamon-settings-mouse.desktop#L224) and/or in your system language.

Hope it helps.

**Comment by clefebvre** [comment]
hi @Pjotr123 

I think you raised a valid point, and the solution for it would be to sort results by relevance and not just alphabetically. Typically here, synaptic would show above mouse/touchpad as it would match on name rather than on keywords.

That said, the way the menu is implemented, it doesn't currently sort results, it actually hides and filters items in the already populated list. We would lose performance and we would need to implement the menu differently to achieve this.

After talking with the team we thought this wasn't worth fixing, at least not for now and not just for this reason.

**Comment by NikoKrause** [comment]
@Pjotr123 
Maybe you want to try Same Menu in the meantime. It's the same menu, only uses a different search function.
https://cinnamon-spices.linuxmint.com/applets/view/258

**Comment by NikoKrause** [comment]
https://github.com/linuxmint/Cinnamon/issues/4053

**Comment by Pjotr123** [comment]
Thanks for responding! I've solved it for myself like this:
sudo sed -i 's/synaptic/sc/g' /usr/share/applications/cinnamon-settings-mouse.desktop

If you want to tackle the German localization as well, do this:
sudo sed -i 's/Synaptic/sc/g' /usr/share/applications/cinnamon-settings-mouse.desktop

This changes the key word "synaptic" (German: "Synaptic") into "sc". Me happy now.  :-)

**Comment by mxa** [comment]
Just because it isn't mentioned here: [Synaptics](https://en.wikipedia.org/wiki/Synaptics) is a popular manufacturer for track pads. That's why when you start to type it you get the mouse and track pad properties. It's not a bug.

**Comment by Pjotr123** [comment]
@mxa: respectfully, I don't agree.... practically everybody will use the menu query "mouse" or "touchpad", in order to get to the Mouse and Touchpad tool. In real life, nearly no-one will ever use the query "synaptic" for that. It's simply useless.

Whereas, again in real life, nearly *everybody* will be bothered by the annoyance that Synaptic Package Manager (a much used tool) isn't the first result for the query "synaptic".

So I regard this a as a usability bug of the "paper cut" category. Which could be solved easily, by simply removing the term "synaptic" from /usr/share/applications/cinnamon-settings-mouse.desktop....  :-)

**Comment by germanfr** [comment]
I don't think removing the synaptic keyword is the solution. Then there would be other keywords that don't please one user or another.

Also removing it would not fix your issue. They would still show in alphabetical order, and mouse comes before Synaptic.
