### ISSUE TITLE
Window List Applet doesn't work.

### ISSUE THREAD

**Issue by Athenacle** [linuxmint/Cinnamon#6037]
I'm a Gentoo user. Yesterday I updated my cinnamon desktop from 3.0.7 to 3.2.0. 
First time I login into cinnamon, there is a notification that tell me some applet start with failure.
After I reset all the applet settings, the error remain exists.
I checked Looking Glass, it said:
...
error t=2016-12-02T06:45:11Z No signal 'window-skip-taskbar-changed' on object 'MetaScreen'
error t=2016-12-02T06:45:11Z [Applet "window-list@cinnamon.org"]: Failed to evaluate 'main' function on applet: window-list@cinnamon.org/3
error t=2016-12-02T06:45:11Z Could not load applet window-list@cinnamon.org
...

[Here](https://gist.github.com/Athenacle/fde7cd1fc796a6e4b3381b268b931932) is the file ~/.cinnamon/glass.log stored at gist/github.com

What is the matter in this applet?  I don't know whether this is a common thing or just happened to me, could anyone help me? Thank you.

**Comment by Odyseus** [comment]
Hello, @Athenacle.

It seems that you might not have installed the correct muffin version. The "window-skip-taskbar-changed" signal was introduced in a recent muffin's version.

**Comment by Athenacle** [comment]
@Odyseus , thanks, It works.....
I just forget to update the muffin...
