### ISSUE TITLE
Windows decorations don't adapt to DPI scaling

### ISSUE THREAD

**Issue by christophra** [linuxmint/Cinnamon#6038]
I have not found any open or closed issues with this, so I hope this is approprate to report as an issue.
Steps to reproduce:
1) Laptop with high DPI display
2) Switch to external monitor with normal DPI
(as primary display, other one is off)
3) Cinnamon scales the panel appropriately and the cursor (after waiting a bit), but window decorations remain at 2x scale until Cinnamon is restarted. The same happens with the "Panel edit mode" button when you right-click on the panel, but the rest of the menu is adapted to the new scaling.
[simmel_inxi_Fxz.txt](https://github.com/linuxmint/Cinnamon/files/627115/simmel_inxi_Fxz.txt)
![cinnamon-hidpi-decorations](https://cloud.githubusercontent.com/assets/16286813/20833897/48713b46-b892-11e6-95f3-01007ffb3b92.png)

**Comment by leigh123linux** [comment]
The windows decorations are  muffin not cinnamon.

**Comment by christophra** [comment]
Sorry, I didn't know that. I'll move the issue over there.

**Comment by christophra** [comment]
(What about the panel?)

**Comment by leigh123linux** [comment]
The panel is cinnamon.

@mtwebster 
Is this a known issue?

**Comment by JosephMcc** [comment]
https://github.com/linuxmint/Cinnamon/issues/3194
