### ISSUE TITLE
Vertical Panel / 24 hour bug

### ISSUE THREAD

**Issue by monark88** [linuxmint/Cinnamon#6039]
24 hour time format won’t change to 12 hour in vertical panel mode

To reproduce: Change panel to vertical panel, then change clock from 24 hour to 12 hour, the clock will display in 24 hour format still. If you change panel to horizontal, time will be correct, change back to vertical and it changes back to 24 hour format, but settings still say 12 hour

**Comment by JosephMcc** [comment]
This is the intentional behavior right now. A vertical panel can only handle a limited label length. The clock is one of the applets that could still be improved for integration with the vertical panels.

**Comment by monark88** [comment]
I see and understand.  Users with vertical panels may also want a ridiculously long date/time format (e.g. %A, %d %b %Y %l:%M %p).  So the applet just checks if in vertical, then keep 24hr.

Following what you were saying, I was able to go to:

/usr/share/cinnamon/applets/calendar@cinnamon.org/applet.js

and changed
` label_string = now.toLocaleFormat("%H%n%M"); // this is all that will fit in a vertical panel with a typical default font`

to
` label_string = now.toLocaleFormat("%I%n%M"); `

But I see what you are saying. With vertical panels, need to regulate what formatting is possible

**Comment by JosephMcc** [comment]
To allow other formats we would need to figure out an intelligent way to handle them. In many cases text style applets aren't allowed on vertical panels. For now this was an easy way to allow the date applet to be displayed.
