### ISSUE TITLE
Screen Tearing Issue.

### ISSUE THREAD

**Issue by shovoncs** [linuxmint/Cinnamon#6040]
@#It only happens in Linux mint cinnamon. On mate and other DE works fine.
Sample of bug:
[https://m.youtube.com/watch?v=96GJE08Knjg](url)
Tested under haswell i5 processor, Intel HD 4600 graphics.
With compiz , Compton it is just perfect . But cinnamon uses other composition as I know. So please fix this issue.

**Comment by JosephMcc** [comment]
https://github.com/linuxmint/Cinnamon/issues/3423
https://github.com/linuxmint/Cinnamon/issues/3355
