### ISSUE TITLE
Cinnamon logo?

### ISSUE THREAD

**Issue by oberon2007** [linuxmint/Cinnamon#6041]
This is probably not a very good place for this issue, just I could not find a better one, sorry! :wink: 
For a while I have been trying to find a Cinnamon logo but I could never find any but the "LM" and the "Mate" ones.
Is there maybe a logo around that I have missed? Or are there any plans to create one?
It would be great to have one available for creating wallpapers and stuff ...

**Comment by ManIVIctorious** [comment]
http://segfault.linuxmint.com/2016/09/design-team-working-on-spices-website/

**Comment by oberon2007** [comment]
Great! Thank you for the link.
