### ISSUE TITLE
[Feature Request] Official Show/Hide Applets applet

### ISSUE THREAD

**Issue by feren** [linuxmint/Cinnamon#6042]
There's an unofficial applet that does a good job, but it has its own problems in random times where it breaks until Cinnamon is restarted, so it'll be really cool if you could make an official Cinnamon Applet that shows & hides Applets similar to the way it worked in Windows XP's System Tray with some of the icons being hidden...

**Comment by JosephMcc** [comment]
https://github.com/linuxmint/Cinnamon/issues/6042

**Comment by feren** [comment]
@JosephMcc You linked to this exact issue...

**Comment by JosephMcc** [comment]
Oops, fixed.

**Comment by feren** [comment]
Ok, thanks... Couldn't find that issue when I tried searching for something along the lines of it...
