### ISSUE TITLE
Global unity-like menu and window buttons.

### ISSUE THREAD

**Issue by stunito0o0o0** [linuxmint/Cinnamon#6044]
Hello,
first I want to apologize if this is not the right place to put this, I am new to the github and linux world.
So I've been using Ubuntu for a couple of months, but then I found out about the mint distro with the cinnamon DE and I absolutely loved it... Everything is perfect so far except for the lack of unity-like global menu and window buttons. They are really helpful, especially when the window is maximized. I tried to resolve my problem by downlaoding 3rd party applets for the buttons, a global menu(@lestcape) and tried to configure them so they are as much as possible unity-like looking, but there are still problems. The buttons are sometimes glitchy, and the menu, well its awesome, but it doesn' work under root privileges.... So i basicly have to disable the menu applet everytime i open synaptic (to make the original menu show up) and then reanable it again once i'm done working under root. All this is annoying and it ruins the whole idea of having a replacement for the unity-like global menu.
So basicly, I want to ask you put a option for a unity-like global menu and buttons in the next cinnamon release. I heard that the cinnamon is the most customizable DE so I hope that I can enjoy one more cusomatization in the near future.
Thank you all in advance for the great work :).

**Comment by Vahan86** [comment]
Issues https://github.com/linuxmint/Cinnamon/issues/5638, https://github.com/linuxmint/Cinnamon/issues/5769, https://github.com/linuxmint/Cinnamon/issues/5846

**Comment by lestcape** [comment]
@stunito0o0o0, please close this thread.

- I don't know how resolve the root problem, i will try to find a way to do that, but i can not promise anything.
- I also are working trying to read the metacity xml and then create the buttons for that (also i can not promised anything about that, like this is a task of a low level windows manager and i'm trying to do that in java script.
- I open a pull request in cinnamon (at muffin level) to allow remove the title bar when an application will maximized like you want. https://github.com/linuxmint/Cinnamon/pull/5961
