### ISSUE TITLE
strange RAM issue 

### ISSUE THREAD

**Issue by xeon-zolt** [linuxmint/Cinnamon#6047]
i was using cinnamon the ram usage by cinnamon was around 300 mb 
after that i ran a game with wine i felt no difference in PC performance 
after some minutes of closing the game the ram performance started to degrade i checked ram using system monitor it was 1.7gb ( too much its not windows right )
after that i ran restart cinnamon and ram was back to normal
![screenshot from 2016-12-04 20-42-48](https://cloud.githubusercontent.com/assets/4529442/20867287/a4334caa-ba66-11e6-98ad-9d235568ca9f.png)

after restarting cinnamon via terminal as PC was hanging too much

![screenshot from 2016-12-04 20-44-25](https://cloud.githubusercontent.com/assets/4529442/20867292/cfe30336-ba66-11e6-8864-70f7db50e357.png)

**Comment by JosephMcc** [comment]
So we can keep these reports together, could you please add your info to https://github.com/linuxmint/Cinnamon/issues/3796

Thanks.
