### ISSUE TITLE
[Bug] On Screen Keyboard is behind Applet Menus

### ISSUE THREAD

**Issue by feren** [linuxmint/cinnamon#6048]
Pretty Self-explanatory: (You can't click the keys covered by Cinnamon Menu)
![screenshot from 2016-12-04 17-16-21](https://cloud.githubusercontent.com/assets/11057934/20867862/96874122-ba45-11e6-90ee-fb082b74702a.png)

**Comment by feren** [comment]
@JosephMcc BTW, the menu in the screenshot is the stock Cinnamon Menu, it's just missing an icon...

**Comment by icarter09** [comment]
We believe this issue is fixed. Please test against the latest Cinnamon version (4.2). 

https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/
