### ISSUE TITLE
Vertical panels' applet order on Cinnamon 3.2 is broken when using RTL system language

### ISSUE THREAD

**Issue by eladhen** [linuxmint/Cinnamon#6049]
On Cinnamon 3.2, when setting the system language to Hebrew (a Right to Left language), and switching to a vertical panel, the order of the applets is pretty broken. The Mint menu and the app launchers are set on lower half of the panel, with the launchers set under the menu.

screenshots:
![2016-12-03 21-15-45](https://cloud.githubusercontent.com/assets/12398651/20868270/413eb2f2-ba60-11e6-96c6-a7fd9cc1e037.png)

![2016-12-03 21-16-53](https://cloud.githubusercontent.com/assets/12398651/20868268/413ca96c-ba60-11e6-9180-bd759711c8d7.png)

The windows list applet appears *under* those two, pushing them up as windows appear:

screenshot:
![2016-12-03 21-25-15](https://cloud.githubusercontent.com/assets/12398651/20868269/413dcb9e-ba60-11e6-9a42-95475c871c32.png)

This was tested on Linux Mint Cinnamon 18.1 Beta and on LMDE2 Cinnamon.

**Comment by JosephMcc** [comment]
Thanks for the report. As far as I know none of the devs uses Cinnamon with a RTL language and we get very little feedback on these issues.

**Comment by eladhen** [comment]
I'm not a developer, but I'll gladly help if you tell me what to do. I have a testing laptop so I will gladly test whatever you want.

**Comment by JosephMcc** [comment]
@eladhen Are you running 64-bit Mint 18.1? I'll post some updated debs for you test if you're willing to try them out.

**Comment by eladhen** [comment]
I am running the 64bit version. How can I get these debs?

**Comment by eladhen** [comment]
Yes, I'll gladly test them.

**Comment by JosephMcc** [comment]
@eladhen You can grab them here: https://dl.dropboxusercontent.com/u/71834451/share/cinnamon-deb.tar.gz

Extract the folder, then in Nemo right click the cinnamon-deb folder and choose "Open in Terminal".
You can then install them by running `sudo dpkg -i *.deb`

You'll need to restart Cinnamon for the changes to take effect.

**Comment by eladhen** [comment]
It seems to work. Anything you want me to test with this?

![2016-12-06 08-45-06](https://cloud.githubusercontent.com/assets/12398651/20917201/bfc3505e-bb98-11e6-9d29-07f7151e8804.png)
![2016-12-06 08-46-16](https://cloud.githubusercontent.com/assets/12398651/20917206/c5346faa-bb98-11e6-9481-62ade8f99545.png)

I got some dependency errors while installing. You can see them in the attached txt file.
[cinnfixinstalation.txt](https://github.com/linuxmint/Cinnamon/files/633200/cinnfixinstalation.txt)

**Comment by JosephMcc** [comment]
Nope. Thanks for testing. I tested it the best I could and everything seemed ok, just wanted some confirmation from someone who was more accustomed to working with RTL languages.

Sorry about the dependency errors. I always install the *-dbg packages. You should be able to fix them by running `sudo apt-get -f install`

**Comment by JosephMcc** [comment]
The fix for this is merged now. Thanks again for testing it.

**Comment by eladhen** [comment]
Thank you for your quick response and fix. I would gladly help test anything related to RTL.

**Comment by JosephMcc** [comment]
Feel free to post bugs you find with RTL. As I said we get very little feedback from users about this.

@brownsr deserves credit for the fix. He did the original vertical panel work and fixed this as well.

**Comment by eladhen** [comment]
Great. Is there a way I can help with translations? In Hebrew it's generally OK, but some stuff is missing, and some stuff is kinda spotty...

**Comment by JosephMcc** [comment]
I've not done any translations but apparently they are done here: https://translations.launchpad.net/linuxmint/latest/+lang/he

**Comment by eladhen** [comment]
Thanks.

**Comment by eladhen** [comment]
This bug or something pretty similar is now in Mint 18.2 (and hence in Cinnamon 3.4.6). When I change my system language to Hebrew the vertical panels become messed up. 

Here is how my panels are set up with English as the language:

![screenshot from 2017-11-10 12-53-10](https://user-images.githubusercontent.com/12398651/32655792-d441226a-c617-11e7-8b0d-0599d9a0dcc5.png)
 
And here is how it becomes if I switch my system language to Hebrew:

![2017-11-10 12-51-16](https://user-images.githubusercontent.com/12398651/32655829-fdc3aa40-c617-11e7-8bb8-748c1f31ced2.png)
