### ISSUE TITLE
Bug when going into "edit panel" mode + wish for cinnamon improvement

### ISSUE THREAD

**Issue by helgen77** [linuxmint/Cinnamon#6050]
if i go into "edit panel mode" (my linux isnt in native english but i think you get my point) where i can drag around items on the taskbar, it frequently crash. This is not a big issue in practical terms but should be fixed in a professional and popular distro like linux mint.

There are also several plugins that do not seem to be compatible with linux mint 18.

And with that out of the way id also suggest an option for future development of cinnamon:

While there is a plugin similar to the software called "plank" (that creates a bottom panel similar to osx) a much greater improvement would be to be able to add separate taskbars and adjust width on them. This can be done in xfce and i think also in mate and it makes more sense, and many just happen to like setting the desktop up this way.

**Comment by JosephMcc** [comment]
Could you post a copy of your .xsession-errors after it crashes?

**Comment by Vahan86** [comment]
@JosephMcc, can we close the issue?
