### ISSUE TITLE
Icons or whole desktop freeze when changing monitor configuration

### ISSUE THREAD

**Issue by xhpohanka** [linuxmint/cinnamon#6053]
I use Cinnamon 3.2.1 (Arch) on Lenovo T460p and often connect one or two external monitors. When workspace settings change icons move to main monitor but remains inaccessible. I also cannot draw selection rectangle on desktop. Restarting Cinnamon surprisingly does not help. When I restart lightdm with monitors connected, everything works as expected.

**Comment by JosephMcc** [comment]
Does it work if you kill and restart Nemo?

**Comment by xhpohanka** [comment]
Funny, I cannot reproduce it now. I will try later...

**Comment by xhpohanka** [comment]
Now I got it and yes, restarting Nemo helped...

**Comment by feren** [comment]
About the Desktop Freezes, as long as it isn't too long, from what I've seen, that's normal for it to freeze for a bit, and it's because of X resizing from what I know...

**Comment by Vahan86** [comment]
@xhpohanka, is this still an issue in Cinnamon 4.2?

**Comment by xhpohanka** [comment]
@Vahan86 not anymore, I will close it...
