### ISSUE TITLE
Cinnamon 3.2.2 Theme Fixes (in changelog) Don't Seem To Have Changed Anything

### ISSUE THREAD

**Issue by feren** [linuxmint/Cinnamon#6056]
I was looking at the changelog for 3.2.2 and saw that the ability for separate menu themes for Menus and Popup Menus was brought back, but I'm on 3.2.2 and don't see any difference on Menus and Popup Menus on themes that rely on it such as CinnXP, are the tags still different for (Main) Menus?

**Comment by JosephMcc** [comment]
https://github.com/linuxmint/Cinnamon/commit/0ac6f0d52caecb5028125e0f20c38fa8e403def6
They should use `menu-background`

**Comment by feren** [comment]
@JosephMcc Ok, thanks, I will tell some of the people that need to know this about this issue so they can fix it for their themes...
