### ISSUE TITLE
Please add 'disable screen rotation' setting

### ISSUE THREAD

**Issue by dcrystalj** [linuxmint/Cinnamon#6059]
i have lenovo yoga 2 pro with screen rotation accelometer feature. It became automatic based on accelometer in version 3.2 and now i cannot disable or i cannot find a way to disable it. I have tried with disabling in keyboard shortucts but does not help

**Comment by leigh123linux** [comment]
Try running this as standard user

```
gsettings set org.cinnamon.settings-daemon.peripherals.touchscreen orientation-lock  true
```

**Comment by dcrystalj** [comment]
woow i think it's working, thank you!!!, how did you find this settings exists? I couldn't google it :-1:

**Comment by leigh123linux** [comment]
I'm familiar with the code.
Perhaps it would be worth adding a setting to settings to make it easier to disable.

**Comment by dcrystalj** [comment]
nice! I just want to mention that on my yoga there is special key to disable/enable rotation which is by default same as ctrl+o. Do you have any idea how to bind it to correct thing?

**Comment by leigh123linux** [comment]
I think additional coding/backporting will be required for keybinding support.

https://github.com/GNOME/gnome-settings-daemon/commit/76b548e3dd4c52455e9c2684d2e64e41b9c5cd84

Cinnamon-settings-daemon currently has none

**Comment by dcrystalj** [comment]
Thank you

**Comment by brianjmurrell** [comment]
Thanks for all of this.  Screen rotation on a laptop is hideous.  Especially where it rotates 90, 180, even 270 degrees on a hair trigger but absolutely refuses to come back to 0 without opening up the Displays setting widget and trying to navigate it when things are 90 degrees off.

**Comment by venik212** [comment]
Sadly, the key on the side of the Yoga 2 Pro does not work, at least not under lubuntu/cinnamon 18...

**Comment by dcrystalj** [comment]
well its working for me. button and everything... some times it gets broken but after reboot its fine.

specs:
```
Cinnamon 3.2.8
Ubuntu 16.10
```

**Comment by venik212** [comment]
We can't all be as lucky.  However, using dconf Editor to disable screen rotation worked for me, so I am happy.

**Comment by leigh123linux** [comment]
@venik212 Did you try changing the keybinding to match you switch key code?

**Comment by venik212** [comment]
We must be using different cinnamons, since I see no such setting in cinnamon-settings general tab.

**Comment by leigh123linux** [comment]
I use 3.2.8

![screenshot from 2017-03-21 05-45-08](https://cloud.githubusercontent.com/assets/1299302/24134137/0bb18bee-0dfa-11e7-9271-156307251f91.png)

**Comment by venik212** [comment]
I am using Cinnamon 3.2.1, which does NOT have the "Disable automatic screen rotation" button.  
I am using cinnamon on top of Lubuntu, and I guess I shall wait until the Gods of Ubuntu provide an updated Cinnamon-- I am not keen on updating behind the back of the OS.

**Comment by Redsandro** [comment]
> Screen rotation on a laptop is hideous. Especially where it rotates 90, 180, even 270 degrees on a hair trigger but absolutely refuses to come back to 0

:joy: 

I have the same problem. Also a Lenovo Yoga laptop here. I have to say that rotation on Windows seems fine. So it's probably a dev that thought: If you rotate the laptop by 20 degrees, it's not because you're moving your legs (_lap_top), but because you want to rotate the screen 90 degrees!
The tipping point should be very clearly near 90 degrees.

Anyway, I really want this rotation at least for 180 degrees because I'm often using the screen flipped over say 200 degrees (backwards) and put it on a table to watch Netflix.

Hence, like on some Android versions, I'd like the option to indicate which rotations should be allowed/disallowed.

**Comment by dlenski** [comment]
Came here after Googling "cinnamon prevent screen rotation". Both the `gsettings` CLI _and_ the "general" setting shown by @leigh123linux work for me. (Cinnamon 4.2.4)

I do think it'd make more sense to have this setting in the Display section of cinnamon-settings, though.

**Comment by JosephMcc** [comment]
> I do think it'd make more sense to have this setting in the Display section of cinnamon-settings, though.

It is in newer Cinnamon versions
