### ISSUE TITLE
Bottom Panel does not respect font sizes (it's a big issue on 4K / high DPI screens) Cinnamon 3.0.7

### ISSUE THREAD

**Issue by nick-s-b** [linuxmint/cinnamon#6060]
Hi all,
After upgrading my monitor, I have an issue with bottom Panel and Menu being unreadable due to extremely small fonts. I've adjusted font sizes in the Font panel of System Settings and every part of Cinnamon UI seems to respect it well. But bottom Panel, Notifications and Task Switcher do not. Panel one bothers me the most.
For example, look at this picture:

![https://i.imgur.com/e3gi0a0.jpg](https://i.imgur.com/e3gi0a0.jpg)
[Bigger size](https://i.imgur.com/e3gi0a0.jpg)

While the text in the background, rendered by the browser, is perfectly readable, the text in the Menu is very small. I've failed to find a way to enlarge it. 

I've tried various themes but they don't make any difference. Is there a way to enlarge this text?

**Comment by Odyseus** [comment]
Hello, @nick-s-b.

Have you tried the **Font scaling factor** setting on the **Font settings** section on **System Settings** > **Fonts**? This setting scales up/down the fonts of Cinnamon's UI.

The panel is a special case. If you have the option **Use customized panel size...** and or **Allow Cinnamon to scale panel text and icons...** enabled on your panel settings, then the **Font scaling factor** setting is ignored and the scaling is handled by other means.

**Comment by nick-s-b** [comment]
@Odyseus thank your helping! If I've tried scaling factor in the past and didn't like it because everything was scaled (including my terminal which I prefer to keep at a certain size because font is bitmapped). I'd like to avoid that font scaling factor at all costs. 
Yes, I do have "Allow Cinnamon to scale panel text and icons" enabled because the Panel just looks weird without it. 
I guess I'll just use other means to start applications since this doesn't seem to be easily fixable.

**Comment by JosephMcc** [comment]
The scaling should "just work". I just tried it here changing my User interface scaling to double and everything doubled including panels, menu, and notifications.

**Comment by Vahan86** [comment]
@nick-s-b, does this issue still relevant to Cinnamon 4.2?

**Comment by nick-s-b** [comment]
@Vahan86 Not as big of an issue as before. There have been some improvements along the way.

**Comment by Vahan86** [comment]
@nick-s-b, thanks for the update.

**Comment by JosephMcc** [comment]
In the next version of Cinnamon it's elements like the taskbar will now follow the font set for the desktop in the font settings.
