### ISSUE TITLE
Screen displays upside down on Mint 18.1

### ISSUE THREAD

**Issue by jrouman** [linuxmint/Cinnamon#6062]
On an HP 340 G1 laptop, the desktop on Cinnamon Mint 18.1 Beta come up upside down.  It can be corrected using the Display dialog (tricky since the display is rotated and mouse directions are backwards) and clicking Apply creates a correct .config/monitor.xml file.  However, this file does not seem to be read on reboot because the display will often (not always, unfortunately) come up rotated 180 degrees.  This occurs both on a clean boot from a USB drive and a hard drive install.

00:02.0 VGA compatible controller: Intel Corporation Haswell-ULT Integrated Graphics Controller (rev 09) (prog-if 00 [VGA controller])
	Subsystem: Hewlett-Packard Company Haswell-ULT Integrated Graphics Controller
	Control: I/O+ Mem+ BusMaster+ SpecCycle- MemWINV- VGASnoop- ParErr- Stepping- SERR- FastB2B- DisINTx+
	Status: Cap+ 66MHz- UDF- FastB2B+ ParErr- DEVSEL=fast >TAbort- <TAbort- <MAbort- >SERR- <PERR- INTx-
	Latency: 0
	Interrupt: pin A routed to IRQ 44
	Region 0: Memory at b2000000 (64-bit, non-prefetchable) [size=4M]
	Region 2: Memory at a0000000 (64-bit, prefetchable) [size=256M]
	Region 4: I/O ports at 5000 [size=64]
	Expansion ROM at <unassigned> [disabled]
	Capabilities: [90] MSI: Enable+ Count=1/1 Maskable- 64bit-
		Address: fee0200c  Data: 4122
	Capabilities: [d0] Power Management version 2
		Flags: PMEClk- DSI+ D1- D2- AuxCurrent=0mA PME(D0-,D1-,D2-,D3hot-,D3cold-)
		Status: D0 NoSoftRst- PME-Enable- DSel=0 DScale=0 PME-
	Capabilities: [a4] PCI Advanced Features
		AFCap: TP+ FLR+
		AFCtrl: FLR-
		AFStatus: TP-
	Kernel driver in use: i915
	Kernel modules: i915

**Comment by leigh123linux** [comment]
File your issue against the Intel driver
