### ISSUE TITLE
LM18 media keys don't work, but work when screen is locked on 18.1

### ISSUE THREAD

**Issue by aedrax** [linuxmint/cinnamon#6063]
Media keys such as play/pause and skip don't work at all in LM18, and in the 18.1 beta they only work when the screen is locked. I tried it using Spotify, but was able to reproduce the behavior in every media player I could think of.

**Comment by Vahan86** [comment]
@aedrax, is this still an issue in Cinnamon 4.2?

**Comment by Vahan86** [comment]
@icarter09, can we close this issue since there is no response from OP?
