### ISSUE TITLE
Blue bars appearing at top and bottom of monitors

### ISSUE THREAD

**Issue by ase1590** [linuxmint/Cinnamon#6065]
So I recently noticed that my desktop had odd blue borders around the top of Monitor 1 and at the bottom of Monitor 2. The monitors themselves do not show this for the most part, but there is certainly a single row of pixels at the top of monitor 1 that are blue. 

Using the _Show all workspaces_ hot corner shows that there are indeed rather thick blue lines being rendered off screen. 

I have attached a screenshot of the blue bars appearing. 
![screenshot from 2016-12-06 21-42-15](https://cloud.githubusercontent.com/assets/4335469/20954145/5c5de888-bbfe-11e6-84d5-096af9d4ef5c.png)

**Comment by ase1590** [comment]
I also noted that conky had shifted downward by a number of pixels, forcing me to modify the config to move it up about 10 pixels so it was not off screen. it seems cinnamon for some reason is rendering itself off screen.

**Comment by mainmachine** [comment]
Ya know... that blue looks an AWFUL lot like the default color used BEHIND the wallpaper, at least that's what I've seen on my Cinnamon on Ubuntu-MATE installations...

Take a look at the desktop background settings, change to a background image that's smaller than your actual display resolution, and set "picture aspect" to centered.

I don't see why this should affect Conky though.

**Comment by ase1590** [comment]
@mainmachine the fact that conky has shifted makes me think that the screen coordinates themselves have somehow shifted by some number of pixels, leading to seeing the what is in fact the default desktop colors. I don't think cinnamon is rendering the desktop wallpapers properly.

**Comment by mainmachine** [comment]
Did you update the system prior to seeing this?

*Something* must have happened to cause this, assuming everything was working "before"...

**Comment by ase1590** [comment]
Alright, update. I seem to have cured the problem. The problem started after upgrading my system. After thinking about the monitor positions shifting conky, I started wondering if it was more related to the display server than cinnamon. 

Upon changing my dual monitor positions in `cinnamon-settings display` and changing it back, the problem had removed itself. 

It seems it was likely an xorg/mesa update that caused the issue to begin with. 

**redoing the monitor layout cured it.**
