### ISSUE TITLE
Add The Option Of Multiple Rows Of Text In Applets

### ISSUE THREAD

**Issue by opticyclic** [linuxmint/Cinnamon#6071]
As per here in the forums https://forums.linuxmint.com/viewtopic.php?p=1246989

I find it convenient in Windows to check the date by quickly glancing at the clock in the taskbar because it has the time on top and the date underneath.
I can't seem to do this in the default calendar applet.

If I use a custom date format e.g. `%A %B %e, %H:%M` I can get the date next to the time, however, I want it stacked under it.

Can you add the option of more than one row of text to an applet.

**Comment by JosephMcc** [comment]
https://github.com/linuxmint/Cinnamon/issues/5743 is close enough that we probably don't need both.
