### ISSUE TITLE
Applet dialog box not being centered

### ISSUE THREAD

**Issue by stunito0o0o0** [linuxmint/Cinnamon#6078]
Hello, I am using the weather applet by mockturtl with a 7 day forecast and I have put it in the center of the panel, but the dialog box is not centered. I know it is not a big deal, but it annoys me lol. I tried to report the problem to the applet creator [as per this thread](https://github.com/mockturtl/cinnamon-weather/issues/170#issuecomment-265989623), but he says that cinnamon is responsible for the layout. I am using Mint 18 and I tried to make a fresh install on a virtual machine and download the applet again just to make sure that it is not from an update or theme or something. 
Any help will be appreciated, thanks.

**Comment by leigh123linux** [comment]
Can you reproduce the issue using the default cinnamon theme?

**Comment by stunito0o0o0** [comment]
[Yes](https://github.com/mockturtl/cinnamon-weather/issues/172)

**Comment by JosephMcc** [comment]
If this is on Mint18/Cinnamon 3.0 it is no longer relevant since these have been completely redone.

**Comment by stunito0o0o0** [comment]
I see, so I will have to upgrade to mint 18.1?

**Comment by JosephMcc** [comment]
The menus are now centered on applets in horizontal panels as long as there is enough room.
