### ISSUE TITLE
Custom keybindings suddenly stop working

### ISSUE THREAD

**Issue by blistovmhz** [linuxmint/Cinnamon#6079]
Not at all sure how to reproduce the issue. 
I originally created a binding (ctrl+print) to call "gnome-screenshot -a". It worked fine for a few days, then all of a sudden quit working. Not throwing any error. Changing the binding does not have any affect. Changing the command run to anything else, does work.. Same command on another machine works fine with the same binding. On the affected machine, I can modify the existing binding to run any other command (with or without modifiers (eg: -a) and it works fine. 
I don't believe it has anything to do with the command being run, but rather a config issue.

**Comment by Odyseus** [comment]
Hello, @blistovmhz.

> I don't believe it has anything to do with the command being run, but rather a config issue.

It is most likely to be that exact command the cuplprit. There are several issues (#5263, #3981) reporting problems with that exact command and its keybindings. You will find in those issues some workarounds.

**Comment by blistovmhz** [comment]
You're absolutely correct. Saw in #3981 that shift+print does work, but only if you hit print lightning fast. Solves my issue. Thanks.
