### ISSUE TITLE
Settings url [idea]

### ISSUE THREAD

**Issue by ondrejkolin** [linuxmint/cinnamon#6081]
Devs of Elementary OS designed an url pattern system for settings. What you guys say on this?

https://docs.google.com/document/d/1N0uqNtVXEFn3cLgNMeN75mP_dpMpCco-7uw5PKow-_Q/edit

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
