### ISSUE TITLE
[Feature Request] Option to open the image being displayed in Photo Frame Desklet 

### ISSUE THREAD

**Issue by abatistas1709** [linuxmint/cinnamon#6085]
That would be great if it was possible to open the image being displayed in Photo Frame Desklet.

**Comment by luisgutz** [comment]
on the current version, Photo Frame can now open the image being displayed.
However, it always uses xdg, when it would be better if it could launch the default app.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
