### ISSUE TITLE
Qt 5.7 still loads default style

### ISSUE THREAD

**Issue by Arquanite** [linuxmint/Cinnamon#6087]
Every app build with Qt 5.7 using Qt Creator looks really bad (even on Mint 18.1). Why this isn't fixed for this long?
Screenshot with sample app
![zrzut ekranu z 2016-12-11 13-40-03](https://cloud.githubusercontent.com/assets/15730544/21080178/e0ee281c-bfa8-11e6-8454-d7ae5cc88e3b.png)

**Comment by leigh123linux** [comment]
File your issue against cinnamon-session instead.
