### ISSUE TITLE
Option for change tray icon size

### ISSUE THREAD

**Issue by varlesh** [linuxmint/Cinnamon#6088]
By default for Cinnamon used 16px icons for tray - native symbolic and for 3-d party apps. But mostly others DE and apps use 22px and 24px by default...
Yes, i know available option for change panel size - but this not work correctly for 3-d party apps.
For example, 
![image](https://cloud.githubusercontent.com/assets/8083855/21088744/8f5546f4-c04b-11e6-9b44-2df82b83e7e1.png)
mintupdate, diodon, indicator-kdeconnect, telegram not change icon size.
If enable option "change panel size with text" - 3-d party icons icons change size, but font very big on panel.
![image](https://cloud.githubusercontent.com/assets/8083855/21088821/2508d404-c04c-11e6-9807-838782bfac29.png)
Will be good if you added option for change icon size for tray apps (without text)

**Comment by varlesh** [comment]
It's not bug issue - it's enhancement :) 
On Gnome used too 16px icons for tray too, but available extension for change icon size https://extensions.gnome.org/extension/1031/topicons/

**Comment by varlesh** [comment]
I know it's [my problem](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/issues/216), but please not ignore this issue, because i'm must port over 600 icons for cinnamon only :(
Maybe anybody found another solution?

**Comment by JosephMcc** [comment]
https://github.com/linuxmint/Cinnamon/issues/4723
