### ISSUE TITLE
Mint 17 and 18 Network settings window cuts off bottom in Cinnamon

### ISSUE THREAD

**Issue by T0T3NK0PF** [linuxmint/cinnamon#6092]
Hi guys, When opening the network settings panel to display LAN connections the window always cuts off the controls part at the bottom. as shown below in Cinnamon

![screenshot from 2016-12-14 07-49-08](https://cloud.githubusercontent.com/assets/24560595/21171034/f231fb1e-c1d1-11e6-94be-0be4b1069370.png)

where it should be displayed like this instead

![screenshot from 2016-12-14 07-49-34](https://cloud.githubusercontent.com/assets/24560595/21171057/1c510476-c1d2-11e6-9644-272f0ddd1070.png)

This issue was also present in Mint 17+
When using a Wifi network only the settings dialog box displays correctly on opening. This appears to only effect Opening the settings panel with LAN settings...

Can you maybe set a minimum dialog box height size ?
thanks

**Comment by SerafDosSantos** [comment]
I have this problem on my side also on Mint 18 and had it on Mint 17. Although I don't often use the Network Settings, it is a little prob that should be corrected...

**Comment by Slept-Warrior** [comment]
This bug still exist, is there any quick fix?

**Comment by Vahan86** [comment]
I can't reproduce the issue, it works fine for me in Cinnamon 4.4.5.

@T0T3NK0PF, is this still an issue for you with Cinnamon 4.4?

**Comment by Vahan86** [comment]
@icarter09, can we close this issue since there is no response from OP?

**Comment by Vahan86** [comment]
@icarter09, can we close this issue since there is no response from OP?
