### ISSUE TITLE
[feature request] resizing menu

### ISSUE THREAD

**Issue by blyatman66** [linuxmint/Cinnamon#6094]
make the menu so that when the favourites are removed from it that it automatically resizes, meaning that people who have docks for their favourites don't end up with menus like this 
![menu](https://cloud.githubusercontent.com/assets/22215004/21191806/41511396-c21e-11e6-89e2-80e113c07af1.png)

**Comment by Odyseus** [comment]
Hello, @blyatman66.

That's most likely Cinnamon 3.0.7 or older. The menu applet in the current Cinnamon from this repository has hundred of improvements, among which is counted a better resizing of the menu once the favorites box is hidden.

**Comment by JosephMcc** [comment]
It does handle this better now.
