### ISSUE TITLE
Close button on notifications

### ISSUE THREAD

**Issue by robrobinbin** [linuxmint/Cinnamon#6100]
Clicking on a notification sometimes dismisses the notification (eg. `notify-send "test"`) and sometimes initiate an action (eg. clicking on a slack notification opens the slack app).

When a high number of notifications of the second kind are generated, this can be annoying: it's hard to interact with the area underneath the notifications, you either have to wait for each notification to dismiss itself or deal with the other application constantly popping up.

I propose adding close buttons to notifications (a la gnome shell)

Notification can further be improved by letting the user change their position, like discussed in other issues on this site.

**Comment by hegerj** [comment]
Rather than close button I'd like to close notifications with right click. Or ideally both.

**Comment by Slater91** [comment]
This is one major issue to me in terms of usability: with frequent notifications turning up, selecting items below them (i.e. browser tabs) is problematic and requires me to wait for the notification to disappear, which is very annoying. Allowing one to dismiss notifications by right clicking on them and/or using a "close" button would make the process much easier and render the notification much less obtrusive.

**Comment by owencm** [comment]
The lack of close button is a priority bug for the Chrome team (I am the PM for our notifications features).

Since we switched to Cinnamon notifications we've had a number of user complaints and are considering reverting due to issues including this one.

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.

I do believe one of the devs is currently looking into implementing this.

**Comment by rangelfinal** [comment]
Any news or workarounds for this?

**Comment by itzexor** [comment]
i have some work on it here but it's not ready yet (though it does work as is)
https://github.com/itzexor/Cinnamon/tree/notif-close-1

**Comment by itzexor** [comment]
The close button was implemented in #7336
