### ISSUE TITLE
Cannot unlock lock-screen

### ISSUE THREAD

**Issue by zagortenay333** [linuxmint/Cinnamon#6102]
I'm using mint `18.1`.

After locking the screen I cannot unlock anymore, neither with enter nor by clicking the unlock icon.

I have to click the switch user icon and log in that way.

**Comment by leigh123linux** [comment]
Please file your issue against screensaver

https://github.com/linuxmint/cinnamon-screensaver/issues

**Comment by zagortenay333** [comment]
Oh srry.
