### ISSUE TITLE
WLAN passwords in Linux Mint 18.1 Cinnamon restricted to 37 characters

### ISSUE THREAD

**Issue by steffzahn** [linuxmint/cinnamon#6103]
Oddly Linux Mint 18.1 cuts WLAN passwords longer than 37 characters. If the password is longer, then only the last 37 characters are used, which will then not match the correct password, and the WLAN connect will fail. At least in the Linux Mint 17.3 release this used to work, at least up to 50 characters.

**Comment by Vahan86** [comment]
@steffzahn, is this still an issue for you in Cinnamon 4.2?

**Comment by steffzahn** [comment]
@Vahan86 I cannot say, since I switch to Ubuntu last year, and moreover my password is now shorter than 37 characters, so I can't even say if the problem is visible in Ubuntu.

**Comment by Vahan86** [comment]
@steffzahn, thank you for your reply.

@icarter09, can we close the issue?
