### ISSUE TITLE
Themes broken!

### ISSUE THREAD

**Issue by StewartLittle** [linuxmint/Cinnamon#6104]
Hi,

 With the 3.2 update of cinnamon - a few themes aren't displaying correctly on the platform, the menu especially StarkMenu use to have a theme along with the main desktop theme but now the main menu is now grey as well as the date section for the calender. 

I don't know if this was already reported but it may need looking into at some point, these themes which I'm describing are at this website here http://b00merang.weebly.com/redmond-collection.html 

I would appreciate some response when possible.....

Stewart L.

**Comment by JosephMcc** [comment]
https://github.com/linuxmint/Cinnamon/issues/5917
https://github.com/linuxmint/Cinnamon/issues/5934
