### ISSUE TITLE
Cinnamon Crash after install the nvidia-340 driver

### ISSUE THREAD

**Issue by ghost** [linuxmint/Cinnamon#6105]
I use Linux Mint 18.1 Serena. After a fresh install, I decided to install the nvidia-340 driver for my GT 820M card. After restart, cinnamon crashed and it asks me if I want to restart cinnamon or not. On Mint 18 I installed the driver without any problem

**Comment by leigh123linux** [comment]
Your card requires the newer driver not the legacy driver!

**Comment by gebal** [comment]
@ghost try this: "make sure to reboot+login+logout+login after you install your drivers/kernels."

more info: https://forums.linuxmint.com/viewtopic.php?f=49&t=233050&sid=a06a3054a536c4e8f3b847aaa44cc2e9&start=60#p1252629
