### ISSUE TITLE
Crash message loop immediately after login

### ISSUE THREAD

**Issue by Joe-Merten** [linuxmint/Cinnamon#6106]
Quite fresh installed 18.1 64 bit cinnamon on a acer notebook (nvidia graphics).
After each login, I got a crash message (graphical dialog, see attached screenshot). Translation: "Cinnamon is just crashed. You are now in fallback mode. Want to restart cinnamon?"
dmesg: "[   62.537240] cinnamon[1757]: segfault at 0 ip 00007ffbf075c4be sp 00007ffdc245a9a0 error 4 in libc-2.23.so[7ffbf06cf000+1bf000]"

If a click "No", then the system seems to operate normally. If I click "yes" instead, then the crash message appears again (and again ...) until I finally click "No".

![crash-message](https://cloud.githubusercontent.com/assets/6552470/21289750/3abfbb0c-c4a5-11e6-83e9-6fbc8362740d.png)

**Comment by JosephMcc** [comment]
Could you post the output of ~/.xsession-errors after this happens?

**Comment by leigh123linux** [comment]
Can you also post the output for /var/log/Xorg.0.log

**Comment by Joe-Merten** [comment]
[xsession-errors.txt](https://github.com/linuxmint/Cinnamon/files/659151/xsession-errors.txt)
[Xorg.0.log.txt](https://github.com/linuxmint/Cinnamon/files/659152/Xorg.0.log.txt)

**Comment by leigh123linux** [comment]
Nvidia 304.132 is known to be broken, it require root permissions for 3D to work

https://bugs.launchpad.net/ubuntu/+source/nvidia-graphics-drivers-304/+bug/1639180
https://devtalk.nvidia.com/default/topic/974456/linux/f24-permission-problems-/
https://devtalk.nvidia.com/default/topic/968892/geforce-7300le-with-304-132-glxinfo-fails-now-with-quot-x-error-of-failed-request-badvalue-quot-

304.134 fixes the issue

https://devtalk.nvidia.com/default/topic/981836

**Comment by Joe-Merten** [comment]
I ran in this issue also during installation; booting from live cd, before switching to nvidia proprietary driver. But however, I'd just tried to switch back to nouveau driver and the issue disappears.
Trying to install a newer driver:
- after `apt-get update && apt.get upgrade` & reboot, I'm still on 304.132
- `apt-get install nvidia-367` also won't change the active driver
What's the official Cinnamon way to get a more recent driver?

**Comment by leigh123linux** [comment]
367 doesn't support your card.
Maybe it would possible to downgrade to 304.131, see

https://bugs.launchpad.net/ubuntu/+source/nvidia-graphics-drivers-304/+bug/1639180/comments/17

**Comment by Joe-Merten** [comment]
I'd followed the referenced steps:
- sudo apt-get remove nvidia*
- sudo apt-get autoremove
- sudo apt-get install nvidia-304=304.131-0ubuntu3

and now I'm on 304.131.
The issue is now gone, much thanks for your support.

**Comment by gebal** [comment]
I get the same behaviour as described by OP, independently of the nvidia version; I've tried 367.57, 340.98, 304.132 and also downgrading to 304.131 as described above. The result is each time the same: Cinnamon crashing right after login, as described above.
I have a Quadro NVS 5400M (GF108M) GPU, on a Lenovo T430 laptop. It's a fresh installation of Mint 18.1.
I attach the outputs of /var/log/Xorg.0.log and ~/.xsession-errors that I got with the 367.57 driver, the others look similar as far as I can tell after a quick glance.

[Xorg.0.log-367.57.txt](https://github.com/linuxmint/Cinnamon/files/661893/Xorg.0.log-367.57.txt)
[xsession-errors-367.57.txt](https://github.com/linuxmint/Cinnamon/files/661894/xsession-errors-367.57.txt)

**Comment by gebal** [comment]
Before I was using Mint 17.3 on the same hardware and had no problems; unfortunately I can't recall which version of the driver I was using, but it was for sure a proprietary nvidia driver (most likely whichever was marked as "recommended" in the driver manager).

**Comment by leigh123linux** [comment]
@gebal  You are using intel not nvidia

P.S Having a broken graphics driver is nothing to do with cinnamon, cinnamon requires working X to function.
Please re-file you issue against 

https://github.com/linuxmint/ubuntu-drivers-common

**Comment by gebal** [comment]
I just found the solution to my issue on the Linux Mint forums:
https://forums.linuxmint.com/viewtopic.php?f=49&t=233050&sid=a06a3054a536c4e8f3b847aaa44cc2e9&start=60#p1252629

Apparently nvidia-prime fails to select the card on the first login after installation & reboot. Another logout & login fixes it, quote: "make sure to reboot+login+logout+login after you install your drivers/kernels."

Worked for me, I'm now using nvidia-367.57 without problems.
