### ISSUE TITLE
Where to submit probable UI bug

### ISSUE THREAD

**Issue by MGarvinNYC** [linuxmint/cinnamon#6107]
I have just installed Cinnamon 18 on a couple systems, and witnessed the same UI bug on both.  Also exhibited with 18.1.  Version 17.x runs with no problems.

Nutshell: Clicking in an inactive area of a window (such as clicking too far down when trying to move the window), locks the left mouse button.  Evidently the driver is still handling events, as the cursor can be moved, and the right mouse button functions.

In fact, right-clicking the same window to bring up a context menu (and then just dismissing it) will fix the problem.  ctl-alt-esc also fixes it, as expected.

I have confirmed that fresh installs of v17.2 and 17.3 on the same systems do not exhibit the problem.

Please advise if there is a better place to submit this, or if there is a known fix.

**Comment by JosephMcc** [comment]
I can't reproduce this at all. Are there particular windows it happens on, or all?

**Comment by MGarvinNYC** [comment]
Hi Joseph,

It occurs on main windows. Just confirmed on /Home and on an open Chrome browser window. On the /Home window, I can click just to the right of 'help' in the top menu. That locks up the left mouse button. Most of the time, using the right mouse button to bring up a context menu will restore functionality to the left mouse button, even if the context menu is just dismissed. 

I thought that this may be caused by the wireless mouse (a normal Logitech model, nothing weird). But I just tried it with a wired Microsoft mouse--same results.  It seems unlikely to be a low-level driver issue anyway, as the cursor still moves, and functionality can be restored.

This is the same on two different systems with different hardware.

The problem does not occur with Mint Cinnamon 17.x (I just confirmed with 17.3 on the same hardware), and does not occur with other Linux versions that I've tried.

It looks to me like something was changed in the UI code since v17.  Is it possible to trace the execution path for a left-click in the area that I described (right of the 'help' menu, for ex) to see if there is some path that could go astray?

I've also seen a couple "Could not grab your mouse" messages with v18. Not often, and not synchronous with the problem above, but perhaps related.

**Comment by MGarvinNYC** [comment]
A couple other comments, possible clues:

I realized that Cinnamon 17.x allowed moving a window by dragging from anywhere at the top of the window. This is not the case with the problematic v18.x installs. The window can be moved only by dragging from the very top 'title' area (similar to the way that the 'Welcome' window works). Clicking anywhere under that precipitates the lock.  So there must be a difference in the way that mouse clicks are handled in the two areas of the window. That seems like a major clue...?

This does not appear to happen consistently in Mate 18.1 (though I've seen something similar a couple times).  In fact, Mate 18.1 allows moving the window from any point at the top, just as Cinnamon 17.x did. So there must be a difference in the way that mouse events are routed in Cinnamon vs Mate.

When I did see this in Mate, the Welcome window still happened to be open, with the lower right corner visible.  I was able to unclick the checkbox marked "show at startup."  So button clicks are still getting routed, in some obscure way.  But just not registering to most of the places they should.

This seems even more odd after experimenting with it.  I hope it can be corrected, as I do like Cinnamon 18 in other respects.

**Comment by Odyseus** [comment]
Hello, everybody.

I cannot reproduce this issue on any Cinnamon version and with any application toolkit (mainly gtk2, gtk3, Qt4 and Qt5).

@MGarvinNYC: Do you by any change have any desklet placed on your desktop? I have experienced a similar behavior, but it was always when there was a desklet placed directly behind the mouse cursor.

**Comment by MGarvinNYC** [comment]
"@Odyseus : Do you by any change have any desklet placed on your desktop? "

It's certainly behaving like that, but no. I wish there was a more direct explanation.  This is something that occurs right off the bat with the new Cinnamon 18 and 18.1 installations, and it can occur with just a single window open.  I've tried a couple times now with the same, repeatable results.

At first I thought that mouse left-button clicks were completely dead, but I've noticed that they are routed.  Just not where I'd expect them to go.  I opened an Emacs window, and though the desktop seemed to be otherwise stalled, mouse events were still getting routed to the Emacs window.

Since this did not occur in Cinnamon 17.x, I was looking for something that could have changed between 17 and 18.

**Comment by JosephMcc** [comment]
Well the entire base Mint is built on is changed between 17 and 18.

**Comment by MGarvinNYC** [comment]
Oh, I guess I shouldn't be too optimistic about a fix then, especially in that you haven't been able to reproduce it.  I have seen numerous mentions of "Could not grab your mouse," which could conceivably be related (it does look like something is grabbing mouse events).  Do you know if there is a normal cause, or a fix for that?  

Also, is there a difference between routing of mouse events from the very top (title bar) vs the rest of the header?

I've tried a few different Linux versions to see if this could be caused by the change in kernel.  I have seen a couple very sporadic things that look similar with Mate, and with Ubuntu, but they do not seem to happen often at all.  But I'm quite attached to Cinnamon's desktop, so I'm holding out hope that I can find what is causing this.

Thanks to all for looking at this.  Appreciated.

**Comment by icarter09** [comment]
@MGarvinNYC are you still experiencing this issue?
