### ISSUE TITLE
MintMenu: bottom of window extends off the screen

### ISSUE THREAD

**Issue by ACinnamonUserInUK** [linuxmint/Cinnamon#6110]
On my system the MintMenu extends, slightly, off the bottom of the screen, cutting off half of the text that describes each item. I would give a screenshot, only, having tried to do so with the program Shutter, the MintMenu has got frozen on the screen and is obscuring stuff I need to take the screenshot.

So I had to force Cinnamon to restart within five minutes of upgrading to 18.1 - which is a shame.

Perhaps the problem is that the menu is ignoring the (enlarged) size of the panel from which the MintMenu drops down.

Mint 18.1 x64.
Cinnamon 3.2.6.

**Comment by ACinnamonUserInUK** [comment]
OK, I've got a screenshot now (though I've removed the right-hand side of the screen):

![untitled](https://cloud.githubusercontent.com/assets/9998846/21297419/7e3f3bfa-c577-11e6-8cfd-c2404a3e6657.png)

Note the vertically truncated text at the bottom.

**Comment by JosephMcc** [comment]
Remove a couple of categories. There is nothing in place limiting the number of categories you show but also nothing to deal with a user adding more than will actually fit on the screen. Curious, what is the screen resolution?

**Comment by ACinnamonUserInUK** [comment]
Hi Joseph

The screen resolution is '1280 x 800 (16:10).

The categories do not seem deletable from within the Menu Editor.

Also: 'There is [. .] nothing to deal with a user adding more than will actually fit on the screen' - hmm. Shouldn't there be?

**Comment by JosephMcc** [comment]
The problem is that it would require the adding of a scrollbar like we do for the applications. Someone would need to come up with a neat way to do so.

**Comment by ACinnamonUserInUK** [comment]
Thank you for the information.

That menu is meant to be Mint's main program launcher (though I myself use a dock, mostly). So, in my view, having it display properly (as I would put it) should be a priority.

**Comment by ACinnamonUserInUK** [comment]
Also: hold on, what? There _is_ a scrollbar. It's for the right-most column, which isn't exactly where the problem lies, but the problem does lie just _beneath_ that column . . (Recall the screenshot and my description of it.) So it seem to me that the problem is simply that t_he window - the window itself - is to large. I think that (as I said already) the problem may be caused by MintMenu not taking into account the size of my panel._

Forgive me if I miss something . .

**Comment by JosephMcc** [comment]
It does display properly in most cases. The fact that no one has really complained about this even though it's always been that way shows how big of an issue it is.

**Comment by ACinnamonUserInUK** [comment]
There is [this complaint](https://forums.linuxmint.com/viewtopic.php?t=92001) (which isn't by me). So, added to mine, that makes two. However: sanity is not statistical; I stand by my comment that the menu is the main launcher and hence that it is important to get it right. If the response is: well, it only goes wrong for a few people, well, I feel that this a little harsh on them.

Ultimately, though, the problem is cosmetic, I admit.

**Comment by leigh123linux** [comment]
@ACinnamonUserInUK  is 4% statistical enough for you?

http://www.w3schools.com/browsers/browsers_display.asp

This issue is already on the roadmap

https://github.com/linuxmint/Roadmap

"hidpi issues: top of mint menu is cut off in HiDPI (1920×1280)"

It named wrong, 1920×1280 doen't qualify to be called HIDPI

**Comment by NikoKrause** [comment]
@JosephMcc 
> The problem is that it would require the adding of a scrollbar like we do for the applications. Someone would need to come up with a neat way to do so.

You mean a scrollbar for categories box?

You'll still get the same problem, if you have to many favorites.

**Comment by JosephMcc** [comment]
Yeah, I know. Putting scrollbars in each "box" would just look horrible as well.

**Comment by ACinnamonUserInUK** [comment]
**About the mention of this problem in the 'road map'.** That mention is actually of a _similar_ but not identical problem (though the two problems may share a cause). For, the problem mentioned in the map is that the _top_ of the menu is cut off, at a resolution of the _1920×1280_ (which is [a resolution used by some 31%?](http://www.w3schools.com/browsers/browsers_display.asp)). The problem that _I_ have is that the _bottom_ of the menu is cut off, at a resolution of _1280x800_ (which is a resolution reportedly used by some 4%).

I thought I should point this (the foregoing discrepancy) out. Perhaps the map should be amended.

**Comment by JosephMcc** [comment]
It's the exact same root cause. The one in the roadmap shouldn't even be there. That complaint was about running in HiDPI mode on a 1080p screen. Which means a resolution of 960x540. Not really worried about it displaying properly on a size that small.

**Comment by ACinnamonUserInUK** [comment]
I can no longer reproduce the problem, with any desktop theme. However, it seems to me that I saw the problem recently. So, perhaps the problem is intermittent - or depends on a variety of factors.

**Comment by JosephMcc** [comment]
As explained here and in the other issue, the size of the menu is up to the user. Place more categories or favorites in it than will fit on your screen and this will happen. It's just the current way the menu is designed. We don't put any limit because there are a lot of differing factors involved. There are other menus on the spices site that may better suit your needs.

There is already an entry in the Roadmap to look at a new design for the menu.

**Comment by ACinnamonUserInUK** [comment]
I note your comment, Joseph - but I thought I should add that, actually (sorry!), I do still have the problem with one, theme, namely, Mint-Y. See the truncated text at the very bottom of the following image (the vertical truncation of which is _not_ an artefact of the screenshot).

![image](https://cloud.githubusercontent.com/assets/9998846/26171827/dd7aa2ec-3b35-11e7-91fb-9bfef092bb4a.png)

(I am not trying to re-open this thread. I recognise and welcome the fact that MintMenu will be redesigned.)

**Comment by JosephMcc** [comment]
Different themes use different spacing/padding values which can cause the difference.
