### ISSUE TITLE
Vertical panel pops on and off under certain conditions

### ISSUE THREAD

**Issue by Mintulix** [linuxmint/Cinnamon#6111]
Put a (new) vertical panel to the left side, setting "smart hide" (or what's it called in English) with none or little show and hide delay.
Open a small/normal sized terminal (not fullscreen) with a blinking cursor. Move this window to the left until it overlaps the left panel a bit -> the panel is now steadily hiding and showing in the frequency of the cursor.

**Comment by JosephMcc** [comment]
I can reproduce this. It's bizarre. It's almost like the terminal window focuses and unfocuses when the cursor blinks. It's like watch the blinker in my car.
