### ISSUE TITLE
Desktop icons and trash are missing partly or completely most of the time.

### ISSUE THREAD

**Issue by HoracioDos** [linuxmint/cinnamon#6113]
Desktop icons and trash are missing partly or completely most of the time while using and external monitor. The external monitor is set as Primary Display.

To fix this, I have to click "Show desktop icons on primary monitor only" and disable and re enable "Trash ON" after every boot.

System:    Host: U47VC Kernel: 4.4.0-53-generic x86_64 (64 bit gcc: 5.4.0)
Desktop: Cinnamon 3.2.6 (Gtk 3.18.9-1ubuntu3.1) dm: mdm Distro: Linux Mint 18.1 Serena

Graphics:  Card-1: Intel 3rd Gen Core processor Graphics Controller bus-ID: 00:02.0 chip-ID: 8086:0166
Card-2: NVIDIA GF117M [GeForce 610M/710M/810M/820M / GT 620M/625M/630M/720M] bus-ID: 01:00.0 chip-ID: 10de:1140
Display Server: X.Org 1.18.4 driver: nvidia Resolution: 1366x768@60.00hz, 1920x1080@60.00hz
GLX Renderer: GeForce GT 620M/PCIe/SSE2 GLX Version: 4.4.0 NVIDIA 340.98 Direct Rendering: Yes

![desktop](https://cloud.githubusercontent.com/assets/4549674/21318289/51a910aa-c5e7-11e6-9bc9-f8e3d2b99f18.png)

**Comment by HoracioDos** [comment]
I didn't find this issue earlier. It may be related.
Desktop Icons Disappear on Multi-Monitor #5978

**Comment by Vahan86** [comment]
@HoracioDos, is this still an issue in Cinnamon 4.2?

**Comment by HoracioDos** [comment]
It's not an issue in Cinnamon 4.2.4. It's an old issue. It was for Linux Mint 18.1 Serena
