### ISSUE TITLE
Panel was unusable after upgrade to Cinnamon 18.1 - needed panel reset to defaults

### ISSUE THREAD

**Issue by abdupattoh** [linuxmint/Cinnamon#6114]
I had an applet on my panel called window-list-with-app-grouping when I upgraded from Cinnamon 18 to 18.1

After upgrade the panel was inactive, and I had no way in the UI to deal with the issue.   Thankfully I had gnome-do on my system, and was able to access cinnamon settings that way, to reset the panel.  This was not an obvious way to handle the situation.

Perhaps there should have been a warning or something about what to do when you have an non-responsive panel, and it feels like an applet should not have the power to render the panel and menu unusable...  Perhaps a cinnamon "safe mode" is needed with all standard applets?

**Comment by JosephMcc** [comment]
We've had multiple complaints about that applet from people upgrading Mint. There is only so much we can do about 3rd party applets. I think in the future part of our notes for upgraders should be to disable all 3rd party applets.

For future reference, you can always `ctrl+alt+t` to open a terminal and access cinnamon settings with `cinnamon-settings`.

**Comment by mcarans** [comment]
App grouping should be added to the default window list so that an applet is not needed. It is a common feature in desktops. It would make Cinnamon perfect!
