### ISSUE TITLE
Screesaver Shows Wrong Number of Notification

### ISSUE THREAD

**Issue by ttjimera** [linuxmint/Cinnamon#6116]
Coming out from suspend, the screesaver tells me that I have 3 notifications when in fact I had none.

**Comment by ManIVIctorious** [comment]
I have also experienced this, although this is an issue with [cinnamon-screensaver,](https://github.com/linuxmint/cinnamon-screensaver/issues) not cinnamon itself and therefore should be closed here and reopened in the appropriate location

**Comment by mtwebster** [comment]
This is because I think currently Cinnamon forgets all notifications coming back from suspend, while the screensaver doesn't.  I'll consider having it mimic Cinnamon's behavior.

The screensaver counter also *only* counts notifications received since locking/activation of the screensaver, *not* including how many you may have had prior to locking.

**Comment by ttjimera** [comment]
I just tested Cinnamon notification. I have 4 notifications in the Notification applet before suspend. Coming back from suspend I have exactly the same 4 notifications. So I do not think Cinnamon forgets all notifications after suspend. 

I am also suspecting the screensave counts notification differently. How? I do not know. But the 3 notifications could be one from Network-Manager about my wifi having been re-established and two from VPN app (PIA) telling me the VPN is disconnected and then reconnected. I usually get these 3 notifications coming out of suspend. However, only the one from Network-Manager will appear in Notification applet. The other two are just transient notification which I think are from the VPN app itself.

Anyway, as suggested by ManIVIctorious, I will close the issue here and reopen it under the screensaver project. Thanks.
