### ISSUE TITLE
cinnamon-screensaver lock function

### ISSUE THREAD

**Issue by egrist** [linuxmint/Cinnamon#6119]
I'm using displaymanager lightdm, but when I lock the computer it calls the cinnamon lock function.

I'm using virtualbox with windows 10 for office administration, the problem is when I enter my password in cinnamon lock-screen the password is also entered into the windows machine. Had to change my domain admin password twice already since I randomly send that password to people on the skype for business chat windows when I log in to cinnamon.

I've been trying for hours to find a work-around but haven't found one. Currently I just add a custom keyboard shortcut to run dm-tool lock. But that doesn't exec automatically after X minutes of inactivity, gotta press the button.

Using Fedora 25 with cinnamon-desktop-3.2.1-2.fc25.x86_64 and lightdm-1.18.2-1.fc25.x86_64

**Comment by leigh123linux** [comment]
Does this update help?

https://bodhi.fedoraproject.org/updates/FEDORA-2016-7c71cb2887

also you have filed the issue in the wrong place

https://github.com/linuxmint/cinnamon-screensaver/issues

**Comment by egrist** [comment]
cinnamon-screensaver-3.2.9-1.fc25.x86_64 works great now, thanks. Apologies for posting in the wrong place.
