### ISSUE TITLE
Software Sources window does not maximise

### ISSUE THREAD

**Issue by ACinnamonUserInUK** [linuxmint/Cinnamon#6121]
That the window does not maximise - has no maximise button - is an irritation.

![image](https://cloud.githubusercontent.com/assets/9998846/21413368/944a0de8-c7ee-11e6-8278-1568cc2f52ae.png)

**Comment by ACinnamonUserInUK** [comment]
I tried to edit the post above - before pressing 'submit' - to say the following (but it did not work): I am using a custom theme, but with a normal theme, the window still lacks a maximise button.

**Comment by JosephMcc** [comment]
This has nothing to do with Cinnamon at all. The window is not re-sizable by design.

**Comment by ACinnamonUserInUK** [comment]
JospehMcc: if indeed the window is designedly not maximisable, and that design has nothing to do with Cinnamon, then could you point me to where I should ask for that to be changed? Thank you.

**Comment by JosephMcc** [comment]
https://github.com/linuxmint/mintsources
