### ISSUE TITLE
No solution available for app grouping in Mint 18.1/Cinnamon 3.2

### ISSUE THREAD

**Issue by mcarans** [linuxmint/Cinnamon#6122]
Now that the applet Windows List with App Grouping breaks with Mint 18.1/Cinnamon 3.2, app grouping should be added to the default window list so that an applet is not needed. Prior to 18.1, installing the applet was a solution. Now that this is no longer a solution, this feature needs to be built in and not reliant on 3rd party code.

**Comment by JosephMcc** [comment]
You already made this comment in every other issue having to do with the window list. We don't need this one as well.

**Comment by mcarans** [comment]
Ok thank you. Keep up the great work.
