### ISSUE TITLE
Add Slingscold- like launcher option to Cinnamon 's hot corners  

### ISSUE THREAD

**Issue by freemangilgamesh** [linuxmint/Cinnamon#6123]
#I suggest you add Slingscold- like launcher option to Cinnamon 's hot corners , maybe with scopes too, for those who hate clicking just like myself http://www.noobslab.com/2015/03/slingscold-launcher-fixed-for-all.html

or:  http://gamblisfx.com/install-slingscold-application-launcher-on-ubuntu-16-04-xenial-xerus/

<a href='https://postimg.org/image/c561bjdtf/' target='_blank'><img src='https://s29.postimg.org/c561bjdtf/Screenshot_from_2016_12_22_22_31_49.png' border='0' alt='postimage'/></a>

This feature with window list with application grouping would make Cinnamon the most complete desktop ever fashioned.

BTW it's very responsive on Linux Mint 18.1 guys!!

**Comment by JosephMcc** [comment]
I don't see that being added by default. An extension could do it though.
