### ISSUE TITLE
CPU hungry after update 

### ISSUE THREAD

**Issue by dk-zero-cool** [linuxmint/Cinnamon#6124]
So I went from Mint 18.0 to 18.1 and found something interesting. Cinnamon in 17.x and 18.0 stayed between 2%-7% of the active CPU usage in idle mode _(When I did not use the computer)_. After updating to 18.1 this went up to 20%-22% and after the latest update of cinnamon to 3.2.7 _(Used during the screenshot)_ it went even higher to over 40%. This is constant usage. The total CPU usage went from 8%-10% in Mint 17.x and 18.0 to 20%-35% in Mint 18.1 with latest updates. The CPU Fan has also increased it's constant speed do to this fact. 

I love this desktop, but it would be great to get this issue fixed in a very near future. I have 1 desktop and two laptops with Mint 18.1. All having this issue. 

![screenshot from 2016-12-23 00-43-05](https://cloud.githubusercontent.com/assets/1395583/21444047/ec446f46-c8a9-11e6-9692-d600078f065d.png)

**Comment by wduqu001** [comment]
I am also using Linux mint 18.1 on a Desktop and a laptop and I could not reproduce this issue.
![cinnamontop](https://cloud.githubusercontent.com/assets/11710288/21445742/f2fa82cc-c8a3-11e6-9615-6669d717cee1.png)

@dk-zero-cool try disabling extensions, desklets and effects. And, take a look at the log with the Cinnamon's looking glass Debugger (the shortcut is Super + L) to see if there is anything abnormal in there. 
Also, to simplify things, you can use the follows command to show you how much CPU each cinnamon process is taking.

```ps -eo pcpu,pid,args | sort -r -k1 | grep cinnamon```

**Comment by dk-zero-cool** [comment]
__Debugger Log__
```
info t=2016-12-23T00:13:35Z Cinnamon.AppSystem.get_default() started in 978 ms
info t=2016-12-23T00:13:35Z loading user theme: /usr/share/themes/Mint-Y/cinnamon/cinnamon.css
info t=2016-12-23T00:13:35Z added icon directory: /usr/share/themes/Mint-Y/cinnamon
info t=2016-12-23T00:13:35Z PlacesManager: Updating devices
info t=2016-12-23T00:13:35Z loaded at Fri Dec 23 2016 00:13:35 GMT+0100 (CET)
info t=2016-12-23T00:13:36Z Loaded applet menu@cinnamon.org in 793 ms
info t=2016-12-23T00:13:36Z Loaded applet WindowListGroup@jake.phy@gmail.com in 136 ms
info t=2016-12-23T00:13:36Z Role locked: notifications
info t=2016-12-23T00:13:36Z Loaded applet notifications@cinnamon.org in 44 ms
info t=2016-12-23T00:13:36Z Loaded applet user@cinnamon.org in 59 ms
info t=2016-12-23T00:13:37Z Loaded applet removable-drives@cinnamon.org in 13 ms
info t=2016-12-23T00:13:37Z Loaded applet keyboard@cinnamon.org in 82 ms
info t=2016-12-23T00:13:37Z Loaded applet network@cinnamon.org in 221 ms
info t=2016-12-23T00:13:37Z Loaded applet sound@cinnamon.org in 157 ms
info t=2016-12-23T00:13:37Z Loaded applet power@cinnamon.org in 58 ms
info t=2016-12-23T00:13:37Z Loaded applet systray@cinnamon.org in 12 ms
info t=2016-12-23T00:13:37Z Loaded applet calendar@cinnamon.org in 30 ms
info t=2016-12-23T00:13:37Z AppletManager.init() started in 1655 ms
info t=2016-12-23T00:13:37Z Cinnamon took 2892 ms to start
info t=2016-12-23T00:13:38Z Hiding systray: network
info t=2016-12-23T00:13:54Z Adding systray: mintupdate.py (24x24px)
info t=2016-12-23T00:13:56Z Resized mintupdate.py with normalized size (22x22px)
```

__PS Ouput__
```
37.2  2131 cinnamon --replace
 0.0  2258 cinnamon-screensaver
 0.0  2144 /usr/bin/python3 /usr/bin/cinnamon-killer-daemon
 0.0  2129 /usr/bin/python3 /usr/bin/cinnamon-launcher
 0.0  2122 /usr/lib/x86_64-linux-gnu/cinnamon-settings-daemon/csd-printer
 0.0  2000 /usr/lib/x86_64-linux-gnu/cinnamon-settings-daemon/cinnamon-settings-daemon
 0.0  1973 /usr/bin/dbus-launch --exit-with-session /usr/bin/im-launch cinnamon-session-cinnamon
 0.0  1970 /usr/bin/ssh-agent /usr/bin/dbus-launch --exit-with-session /usr/bin/im-launch cinnamon-session-cinnamon
 0.0 19162 grep --color=auto cinnamon
 0.0  1901 cinnamon-session --session cinnamon
```

Don't really have any 3'rd party desklet's or extensions installed. Disabling effects made no difference.

**Comment by JosephMcc** [comment]
I see window list with app grouping in your a list of applets. A lot of people are having issues with it in Cinnamon 3.2. Maybe try removing it.

**Comment by dk-zero-cool** [comment]
Simply removing this applet from the panel worked. Thanks, glad this was an applet issue, it allows me to continue using cinnamon 3.2 rather than downgrading.
