### ISSUE TITLE
Remove title from window list applet

### ISSUE THREAD

**Issue by dk-zero-cool** [linuxmint/Cinnamon#6126]
I have been using a 3'rd party window list applet to avoid the titles and only have the icons displayed. After upgrading to the latest cinnamon, it can no longer be used, at least not until it gets updated as well. Could we get an option to remove the title from the native window list instead?

**Comment by mdchaves** [comment]
https://github.com/linuxmint/Cinnamon/issues/67

**Comment by JosephMcc** [comment]
Please use https://github.com/linuxmint/Cinnamon/issues/67 so we can keep this all in once place.
