### ISSUE TITLE
Add alarm clock option to time applet or desklet on Cinnamon

### ISSUE THREAD

**Issue by freemangilgamesh** [linuxmint/cinnamon#6127]
I suggest you add an  alarm clock option to time applet on Cinnamon. Something like this Ubuntu applet https://apps.ubuntu.com/cat/applications/alarm-clock-applet/

**Comment by lestcape** [comment]
I agree with this. I think most of code of the calendar applet could be used to set the alarm in one specific day.

I also want to implement this for Sticky Notes Desklet. So, the notes can be used as an alarm with a note and user could configured his alarms using the calendar to select the day and another more easy implementation to set hours and minutes. Probably a settings to repeat the alarm, following some criteria base on calendar rules.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
