### ISSUE TITLE
Folders and Desktop icons, as well as the file explorer changes into a different design when I change the cinnamon startup to SOME audio files.

### ISSUE THREAD

**Issue by greybatter97** [linuxmint/cinnamon#6128]
I recently made a clean install of Linux Mint 18 Sarah Cinnamon Edition and added my personal jazz onto it. However, when I changed the Cinnamon startup sound into something different, the Desktop icons (Folders, Computer, Trash, etc...), as well as the file explorer; Nemo, changed into a different design. But it didn't changed it in the taskbar, the system menu or the file explorer as Root; as seen in this screenshot: http://i.imgur.com/IAzpS8y.png

I did two or three clean installs and it did the same this: I changed the startup sound and it did the same thing.

However, I recently saw a forum concerning the issue and it turns out that changing the Cinnamon startup sound into SOME audio file, it causes this problem, as I observed it on a Linux Mint 18 Sarah Cinnamon Edition Live CD where I changed the Cinnamon startup sound to the same audio file, and it did the same.

I did fixed the bug using a different audio, but I was told to report it to you guys. I would be thankful to you if you know how to fix this bug. It might be a simple bug.

**Comment by Vahan86** [comment]
@greybatter97, is this still an issue for you in Cinnamon 4.2?
