### ISSUE TITLE
Cinnamon 3.2.7 screensaver issue

### ISSUE THREAD

**Issue by michael7890** [linuxmint/Cinnamon#6129]
I know there has been lots of effort put into resolving problems with recent memory leaks occurring in the latest versions of Cinnamon (starting, from what I can tell, with 3.2.4). These happily seem to have been largely resolved; with recent files turned off, during a week of heavy work load, RAM usage has never risen above 200 on my desktop and seems to settle at an average of 150-180, which is great.

However, the latest version of Cinnamon - 3.2.7 which rolled out yesterday - has a problem with the screen saver lock, in that the screen saver lock does not lock the screen. To put it less absolutely, I have not found a way of making it work. This is extremely unfortunate so (assuming I have not overlooked some new setting I cannot decipher) I thought it best to make draw attention to this issue right away.   

Thanks and a Merry Christmas to everyone :-)

**Comment by leigh123linux** [comment]
cinnamon-screensaver-3.2.12 should fix the issue.

And you report should have been reported here instead

https://github.com/linuxmint/cinnamon-screensaver/issues

**Comment by michael7890** [comment]
Thanks for the quick comment, and sorry about posting in the wrong place :-)
