### ISSUE TITLE
Samba network file sharing in Mint 18.1 not being prompted to install like it used to be

### ISSUE THREAD

**Issue by Swiftpaw** [linuxmint/Cinnamon#6132]
Did this feature get dropped, or is the fact that you don't get a prompt asking if you want to install Samba when you go to Sharing Options for a folder intentional?  Instead when you try to share a folder without Samba installed, you get a cryptic error about a file permission issue.  It used to prompt you to install Samba so that it was all easy peasy.  Please make Samba file sharing easy once more by including that installation hook for new users once again, and thanks for being awesome! :wolf:

**Comment by leigh123linux** [comment]
You have filed your issue against the wrong package, refile against nemo.


https://github.com/linuxmint/nemo/issues
