### ISSUE TITLE
How to disable user switching in cinnamon?

### ISSUE THREAD

**Issue by Tomek-1** [linuxmint/cinnamon#6136]
Hi all,

I'd like to disable user switching option for all users.

In a pure gnome it only needs, to set two following keys in dconf database:

> dconf write /org/gnome/desktop/lockdown/disable-user-switching true
> dconf write /org/gnome/desktop/screensaver/user-switch-enabled false

and works as needed.

For the cinnamon I added two more keys:

> dconf write /org/cinnamon/desktop/lockdown/disable-user-switching true
> dconf write /org/cinnamon/desktop/screensaver/user-switch-enabled false

   
but it does not help - user switching is still available.
It seems that cinnamon ignores that keys.

Regards,

My system:

Debian 8.6 (Jessie)
Kernel:  4.8.11-1-bpo8+1 amd64
Cinnamon: 3.0.4-2-bpo8+1 (jessie-backports)

**Comment by DVeris** [comment]
I have the same problem.
it is bug

**Comment by DVeris** [comment]
System:    Host: ilya-HP-G72-Notebook-PC Kernel: 4.4.0-53-generic x86_64 (64 bit gcc: 5.4.0)
           Desktop: Cinnamon 3.2.7 (Gtk 3.18.9-1ubuntu3.2)
           Distro: Linux Mint 18.1 Serena

**Comment by DVeris** [comment]
dconf write /org/cinnamon/desktop/screensaver/user-switch-enabled false
Switch users button are still available

**Comment by leigh123linux** [comment]
@mtwebster screensaver seems to ignore the key.

**Comment by Tomek-1** [comment]
The workaround is to rename or delete file:

/usr/bin/gdmflexiserver

Of course if you use GDM.

Regards.


2017-04-15 9:24 GMT+02:00 DVeris <notifications@github.com>:

**Comment by icarter09** [comment]
@Tomek-1 can you check if this issue was fixed from the merged PR?  If not, then feel free to reopen this issue. Thanks.
