### ISSUE TITLE
cinnamon-settings crashes with Python 3.6

### ISSUE THREAD

**Issue by besser82** [linuxmint/Cinnamon#6144]
## Description of problem:

* cinnamon-settings crashes with Python 3.6
***
## Version-Release number of selected component (if applicable):

* cinnamon-3.2.7 with python-3.6.0
***
## How reproducible:

  100%
***
## Steps to Reproduce:

1. Build and install cinnamon using Python 3.6
2. Invoke /usr/bin/cinnamon-settings
3. *BANG!*
***
## Actual results:

```
cinnamon-settings
Traceback (most recent call last):
  StepsFile "/usr/bin/cinnamon-settings", line 26, in <module>
    os.execvp("/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", ("",) + tuple(sys.argv[1:]))
  File "/usr/lib64/python3.6/os.py", line 559, in execvp
    _execvpe(file, args)
  File "/usr/lib64/python3.6/os.py", line 583, in _execvpe
    exec_func(file, *argrest)
ValueError: execv() arg 2 first element cannot be empty
```
***
## Expected results:

* Doesn't crash.
***
I came across this when testing recent cinnamon on Fedora Rawhide;  there's already [a hackish solution](http://pkgs.fedoraproject.org/cgit/rpms/cinnamon.git/tree/hack_python36.patch) for this problem [in the bugreport for Fedora](https://bugzilla.redhat.com/show_bug.cgi?id=1408987).

Are there any better ideas, how to solve it?

**Comment by mtwebster** [comment]
Hackish is in already.

https://github.com/linuxmint/Cinnamon/commit/3936ac1e355e9a5f1c2edd1aae4e6da9d2855f45
