### ISSUE TITLE
multiple instances of Orca support program show up in Pulseaudio volume control

### ISSUE THREAD

**Issue by noreasternhumidity** [linuxmint/cinnamon#6145]
I have upgraded to Linux Mint 18.1 (serena).  There are a handful of small issues which may or may not be due to this.  One of which is that I noticed an audio support program (don't know which off the top of my head) for Orca was cluttering up the Playback window.  I removed this with APT and it also uninstalled Orca.

Also now I am seeing that Pulseaudio volume control shows a mysterious instance of Firefox Audio stream, yet nothing is streaming at this moment.

**Comment by noreasternhumidity** [comment]
P.S. the Firefox %CPU has been higher than usual too lately.

**Comment by real-or-random** [comment]
Are the streams also shown in pavucontrol? If yes, it's most likely not a problem in Cinnamon.

**Comment by icarter09** [comment]
Please troubleshoot and find the exact cause of the problem. You can reopen the issue if the responsible component proves to be Cinnamon.

http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/.
