### ISSUE TITLE
Improve prioritization of results in menu search

### ISSUE THREAD

**Issue by geoffm** [linuxmint/Cinnamon#6146]
When I write "panel" because I want to open the panel I expect to be picked as the priority result that would open if I hit enter, not having to cycle through to open "panel" which is proposed at the end. ![if i write panel shouldn t it propose the thing called panel first](https://cloud.githubusercontent.com/assets/901518/21575454/460bbf1c-ceda-11e6-9dc4-66a36f6a91fb.png)
perhaps it is just a matter of displaying first the ones that have the query in their launcher name as opposed to those that have it just in their description.

**Comment by ManIVIctorious** [comment]
Please search if your issues are already reported by other people. This is basically a duplicate of issue #4053 and also related to #1220 and #1320.

**Comment by geoffm** [comment]
thanks. it's disapointing that the issue has been reported 2 years ago and it doesn't seem like things are going to change. I guess I'll be using synapse to launch my apps.
