### ISSUE TITLE
Menu - applets are not visible when mouse hovers over them

### ISSUE THREAD

**Issue by Tracey-Lowndes** [linuxmint/cinnamon#6147]
Since I upgraded to Linux Mint 18.1 Cinnamon in Virtualbox (the latest version), whenever I hover my mouse over the categories "Administration", "Preferences", "Accessories" and "All Applications" the list of applets in these categories does not appear. When I hover my mouse over an applet, I can't see the icon and name, but I can see the text at the bottom.

I have attached screenshots of the problem.

![virtualbox linux mint 18 cinnamon menu 1](https://cloud.githubusercontent.com/assets/13526121/21579577/9927ceee-cfb0-11e6-8762-c03ea6d7db77.png)

![virtualbox linux mint 18 cinnamon menu 2](https://cloud.githubusercontent.com/assets/13526121/21579579/a803ccc4-cfb0-11e6-93bf-7d9f58c76c03.png)

**Comment by Vahan86** [comment]
@Tracey-Lowndes, is this still an issue for you with Cinnamon 4.2?

**Comment by Vahan86** [comment]
@icarter09, can we close the issue since there is no response from OP?
