### ISSUE TITLE
Add Unity scopes to Cinnamon menu

### ISSUE THREAD

**Issue by freemangilgamesh** [linuxmint/Cinnamon#6149]
I suggest you add scoped to Cinnamon menu just like on Ubuntu for esthetic and practical reasons.

**Comment by leigh123linux** [comment]
For practical reasons I will close this request

unity-scopes isn't available on LMDE of any other distro.

**Comment by brownsr** [comment]
http://www.networkworld.com/article/2873192/opensource-subnet/what-the-heck-are-ubuntu-unitys-scopes.html

@freemangilgamesh Few Cinnamon developers will be Unity users, so I think you will have to spell out just what functionality it is you are wanting, how you would want to use it, and preferably what it would let you do that you can't do now.  That might give us some chance of working out if there is something in your request that might be useful to a significant proportion of our users.

**Comment by freemangilgamesh** [comment]
this is what I'm talking about https://github.com/linuxmint/Cinnamon/issues/6150

**Comment by leigh123linux** [comment]
-1 to anything that resembles the crap from Windoze.

**Comment by freemangilgamesh** [comment]
Man stop swearing and respect us! Ur not the smartest, ok!!

**Comment by freemangilgamesh** [comment]
We had enough of your Cycloptic comments!!!

**Comment by leigh123linux** [comment]
@freemangilgamesh Perhaps you should learn English, crap is slang not a swear word!

https://en.oxforddictionaries.com/definition/crap

**Comment by freemangilgamesh** [comment]
yeah I love you too! looooooooooool

**Comment by freemangilgamesh** [comment]
PS crap according to ur source:  " vulgar slang "

**Comment by freemangilgamesh** [comment]
perhaps they should add an option "to fuck you" to cinnamon desktop so that we can smell ur "crap"
 PS I spit on u pirate!

**Comment by freemangilgamesh** [comment]
Pirate pirate flipping pirate balalala balalla pirate!

**Comment by leigh123linux** [comment]
Picking on peoples disabilities is classed as 'hate crime' in the UK and isn't tolerated.
I've had to endure a lifetime of peoples abuse for being different, I didn't pick on you for looking and behaving like a total Muppet!

**Comment by clefebvre** [comment]
OK, please, can we stop this.

Brahim, this isn't just an avatar, you're touching something personal here.

Leigh, there's no way Brahim could have known. I'm sure he didn't mean to hurt you.

Brownsr is spot on. It's always interesting to debate the addition of new features but please don't assume we know how things work in other systems.

Let's keep this one closed and we can continue this on https://github.com/linuxmint/Cinnamon/issues/6150.

I'll remove all personal comments over there though. I can see the misunderstanding. This is a platform for issues and suggestions though, not one to fight with one another.
