### ISSUE TITLE
Add bookmarks for website to Cinnamon menu

### ISSUE THREAD

**Issue by freemangilgamesh** [linuxmint/Cinnamon#6150]
I suggest you add an option to add bookmarks to Cinnamon menu just like we do with Ubuntu scopes

<a href='https://postimg.org/image/dmlzcg4q7/' target='_blank'><img src='https://s27.postimg.org/dmlzcg4q7/bookmarks.png' border='0' alt='postimage'/></a>

**Comment by Cobinja** [comment]
This still doesn't explain it to non-Unity users.
Do you want Firefox-like bookmarks in the menu or what is it that you want? Please be specific.

**Comment by freemangilgamesh** [comment]
yes but you can add the option to choose default browser and apps! and BTW you can add a toggle to turn this option on and off and maybe add RSS notification too

**Comment by freemangilgamesh** [comment]
users can choose their default browser and apps. an RSS, weather gadget, netspeed, etc could be useful too

**Comment by Cobinja** [comment]
So you want Windows-like tiles?
That would be overkill for a menu. If any 3rd-party applet implements it, ok.
But probably (and hopefully) not in the builtin one.

**Comment by freemangilgamesh** [comment]
Just suggesting bro!

**Comment by freemangilgamesh** [comment]
Cobinja who is this guy with the avatar of a pirate he keeps picking on me for suggesting this?

**Comment by freemangilgamesh** [comment]
leigh123linux would u please stop downrating my issues and being rude to me for no clear reason!!! You chose a pirate as an avatar an I chose a puppet! What's all the racket about!!

**Comment by clefebvre** [comment]
Show a video of this in action if possible.

**Comment by freemangilgamesh** [comment]
I mean something like this: <a href='https://postimg.org/image/kbw5g7n61/' target='_blank'><img src='https://s28.postimg.org/kbw5g7n61/windows_10_start_menu_run_command.jpg' border='0' alt='postimage'/></a>

**Comment by freemangilgamesh** [comment]
@leigh123linux: I'm so sorry I thought it is just an avatar and I would never attack people for such things. Thought you were playing till Clement commented on the issue. No offense intended Sir and you are a genius and I think everybody knows this since you are a developer and that's what counts. Peace and love and happy new year sir!

**Comment by lestcape** [comment]
@clefebvre: https://github.com/The-Panacea-Projects/Gnomenu

Browser providers:
Chromium: https://github.com/The-Panacea-Projects/Gnomenu/blob/master/webChromium.js
Epiphany: https://github.com/The-Panacea-Projects/Gnomenu/blob/master/webEpiphany.js
Firefox: https://github.com/The-Panacea-Projects/Gnomenu/blob/master/webFirefox.js
GoogleChrome: https://github.com/The-Panacea-Projects/Gnomenu/blob/master/webGoogleChrome.js
Midori: https://github.com/The-Panacea-Projects/Gnomenu/blob/master/webMidori.js
Opera: https://github.com/The-Panacea-Projects/Gnomenu/blob/master/webOpera.js
Thumbnail: https://github.com/The-Panacea-Projects/Gnomenu/blob/master/workspaceThumbnail.js

**Comment by lestcape** [comment]
@freemangilgamesh i think this will be a nice feature that also don't saturate the menu if will be added as an option and will create an specially category in the menu (like occurs in Gnomenu). In this way, will not use resources as will be optional. For a normal usage, this will required only one "if" (a conditional evaluation of the condition) and not more than that... I don't see why several people down-vote this, but of course, the opinion of other people are also important...

**Comment by JosephMcc** [comment]
I can only say why I down voted it. In my opinion there is no place in Cinnamons menu for the tiles shown in the Windows menu or in the posted mockups.

**Comment by lestcape** [comment]
@JosephMcc of course not and i agree with you... Windows menu or the posted mockups are not displayed according of how is displayed the cinnamon menu... Certainly Cinnamon Menu has nothing to be with the windows 10 menu and i think will never be in this way... But this not need to be displayed in this way... Another thing to take in consideration will be the number of menu categories... As they have not an scroll, have a lot of categories will be a kill for display the menu in a short resolutions. But as gnomenu it's in the roadmap, if will be implemented this is another point to take in consideration if this feature will persist or not.

**Comment by freemangilgamesh** [comment]
slingshot is a good contender for the crown https://cinnamon-spices.linuxmint.com/applets/view/197

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
