### ISSUE TITLE
Cinnamon menu background color in v3.2 (Linux Mint 18.1)

### ISSUE THREAD

**Issue by marbul** [linuxmint/Cinnamon#6153]
This is regarding the menu that appears when you press the Super (Windows) key in Linux Mint 18.1.

The menu background color does not change any more from the default gray when specified with a custom theme.  This occurs only in Linux Mint 18.1 with Cinnamon 3.2.  It worked fine in Linux Mint 18 with Cinnamon 3.0 and earlier.

In my custom cinnamon.css file, I have the following:

/* ===================================================================
 * Panel (panel.js)
 * ===================================================================*/

#panel {
    color: #ffffff;
    background-gradient-start: rgba(20,20,20,0.5);
    background-gradient-end: rgba(0,0,0,0.5);
    background-gradient-direction: vertical;
    font-size: 9pt;
    font-weight: normal;
    height: 25px;
    box-shadow: 0px 0px 2px 2px rgba(0,0,0,0.7);
    background-color: rgba(0,0,0,0.35);
} 

I thought this would change the background color to a dark glass look, and it used to in Cinnamon 3.0 but it does not in Cinnamon 3.2.

The other menu panel elements are correctly themed, it just seems to be the background color.

Has this value changed or is this a bug?

**Comment by JosephMcc** [comment]
https://github.com/linuxmint/Cinnamon/issues/5917
and fixed by
https://github.com/linuxmint/Cinnamon/pull/5948
