### ISSUE TITLE
[Feature Request] Window tiling and snapping should have a configurable grid size

### ISSUE THREAD

**Issue by imarkskinner** [linuxmint/Cinnamon#6159]
So that's a hard one to explain in just a few words. Currently window snapping and tiling is restricted to a 2x2 grid like so.
![screenshot from 2017-01-03 20-02-08](https://cloud.githubusercontent.com/assets/1920963/21621129/90c85764-d1ef-11e6-91be-9339a839b9a3.png)
Well I think it would be a fantastic idea if you could configure this to a different size grid say 4x4 and you could do something like this.
![screenshot from 2017-01-03 20-06-07](https://cloud.githubusercontent.com/assets/1920963/21621261/17c6168e-d1f0-11e6-93d9-e41ddd35944b.png)
If you so desired. 

One probably wouldn't want to open that many blank terminals but humour the example.

**Comment by JosephMcc** [comment]
This really belongs under Muffin. Also it could probably just be added to this request: https://github.com/linuxmint/muffin/issues/124
