### ISSUE TITLE
Desktop background not displaying correctly

### ISSUE THREAD

**Issue by Tracey-Lowndes** [linuxmint/Cinnamon#6161]
When I open Linux Mint 18.1 Cinnamon in Virtualbox (the latest version), the desktop background doesn't display correctly - the colour is wrong. If I try to correct the mistake by rebooting Cinnamon, Virtualbox then crashes with an error message. If I try again, the same happens. Sometimes it takes several attempts before I can finally get the correct background colour.

Here are some screenshots:

The desktop background error:

![virtualbox linux mint 18 1 cinnamon desktop background error](https://cloud.githubusercontent.com/assets/13526121/21622541/e20125b0-d1f5-11e6-9987-13fa26d382ca.png)

The error message that appears when Virtualbox crashes:

![cinnamon reboot error message](https://cloud.githubusercontent.com/assets/13526121/21622584/2ba062d0-d1f6-11e6-8d47-baa189a18c7f.png)

I'm not sure whether this is a Cinnamon problem or a Virtualbox problem. I don't have Linux Mint installed on an actual computer, only in a virtual machine, so I can't check this problem on actual hardware.

**Comment by clefebvre** [comment]
Hi,

Make sure to upgrade all muffin packages to their latest version (3.2.2 at the moment).

And then, open a terminal and type:

`gsettings set org.cinnamon.muffin background-transition fade-in`

That should solve the color issue.

Can you tell us which version of Virtualbox this is?

**Comment by frasca** [comment]
I am using VirtualBox 5.1.12 (on OS X 10.11.6), and was experiencing this issue.

The above setting has resolved the problem for me.

**Comment by JosephMcc** [comment]
@frasca Are you using Mint18 as well?

**Comment by Tracey-Lowndes** [comment]
@clefebvre I'm using version 5.0.30 of Virtualbox.

**Comment by frasca** [comment]
@JosephMcc I was using Mint 18.1 (happens with a clean install)

I have another Mint 18.0 VM that does not have this problem.

**Comment by DanielKoohmarey** [comment]
@clefebvre Recently installed Linux Mint 18.1 and had the same issue after a fresh install, your fix worked for me as well. (VirtualBox 5.1.18 / Windows 10)

**Comment by mcwinson** [comment]
@clefebvre Thanks! Your fix worked on Mint 18.1 (upgraded from 17.3) in VirtualBox 5.1.22 on a Windows 7 host.

**Comment by stillmattwest** [comment]
Didn't work for me. Got a "No such key 'background-transition' error

**Comment by JosephMcc** [comment]
This requires muffin3.2.2

**Comment by TecMunky** [comment]
Also - this is a per user setting.
Is there any way to make this global?
If I wanted to back this out, or make other adjustments, where would I look for optional arguments.

I tried to install the muffin docs, but that didn't work.

**Comment by gercannon** [comment]
Thanks, the fix worked for me running Cinnamon on Ubuntu rather than Mint.

**Comment by dsagit** [comment]
Linux Mint 19.3 guest was seeing the same thing and the workaround from clefevbre fixed it

**Comment by pcanterino** [comment]
I was facing this problem in Linux Mint 19 Cinnamon in VirtualBox. clefebvre's workaround worked for me.

I would also suggest to re-open this issue as it is not fixed out of the box.

**Comment by Blinkenn** [comment]
> gsettings set org.cinnamon.muffin background-transition fade-in  

this worked for me on an LMDE 2 VM, running Virtualbox 5.2.18, that I upgraded to LMDE 3, with Win 10 host.

**Comment by BigSaucy** [comment]
'gsettings set org.cinnamon.muffin background-transition fade-in'

clefebvre's workaround worked for me on Linux Mint 19 Cinnamon in VirtualBox 5.2.18 hosted with MacOS 10.13.6

**Comment by Blinkenn** [comment]
'gsettings set org.cinnamon.muffin background-transition fade-in'

this also worked for me on LMDE 3 "Cindy" in Virtualbox 6.0.2 today, hosted on Win10 Enterprise.

**Comment by bartvanandel** [comment]
If you don't like the fade-in effect, you can also use:
`gsettings set org.cinnamon.muffin background-transition none`

To list all possible values, run:
`gsettings range org.cinnamon.muffin background-transition`

The offending value (and, on my machine, the only other one) seems to be `blend`.

**Comment by andrewpayne68** [comment]
Had zero issues with any of my Mint installs (Windows 10 1909 Host/VBox 6.0.14) until I installed Linux Mint Debian Edition (LMDE) Cindy. Found this article and the command 
`gsettings set org.cinnamon.muffin background-transition fade-in` 
fixed this for me perfectly - many thanks @clefebvre !
