### ISSUE TITLE
error message has spelling mistake

### ISSUE THREAD

**Issue by bigrick1** [linuxmint/Cinnamon#6165]
Linux Mint - Sarah 18, Cinnamon desktop 3.0.7, 32 bit
kernal - 4.4.0-51-generic
when creating a shortcut with the desktop launcher, I got the msg:
"Can't find dsbudget.conf. Make sure you are using a luncher shortcut which sets the current directory, or run .exe on a directory that contains the conf file."
It seems that it should be "launcher"
![error-msg](https://cloud.githubusercontent.com/assets/24917708/21645936/76a4348c-d2d7-11e6-89a8-e1ad7f54b738.png)

**Comment by leigh123linux** [comment]
It's not from cinnamon

```
[leigh@localhost Cinnamon-3.0.7]$ grep luncher -r
[leigh@localhost Cinnamon-3.0.7]$
```
