### ISSUE TITLE
possible bug crashing cinnamon dektop when saving from text editor

### ISSUE THREAD

**Issue by bigrick1** [linuxmint/Cinnamon#6166]
Linux Mint - Sarah 18, Cinnamon desktop 3.0.7, 32 bit
kernal - 4.4.0-51-generic
Possible bug:
I created the file 'dsbudget.desktop' with Text Editor and put in /usr/share/applications
I edited it by the file manager: Files -> File System -> usr -> share -> applications
Then right click on the file dsbudget.desktop open with -> other application -> Text Editor
After I made some changes, I saved the file. The window abruptly crashes.
I then get the message "Cinnamon just crashed. You are currently running in Fallback Mode. Do you want to restart Cinnamon?"
I answer Yes and then Cinnamon restarts and the text editor opens again with the file open and the changes saved.
Every time I use this method Cinnamon crashes. Should a password window pop-up if this is an issue with user rights in the directory?

Using nano in the Terminal to edit and save the file did not cause the desktop to crash.
But, when making a change I do get the message "Warning: Modifying a file which is not locked, check directory permission?"
I am able to use the file as expected. So I am not clear as to what problem I am creating or if this is a possible bug.

**Comment by clefebvre** [comment]
We believe this issue is fixed. Please test against the latest Cinnamon version (3.6). If the issue happens again, create a new issue and add a stracktrace.
