### ISSUE TITLE
Menu app description overflows the menu

### ISSUE THREAD

**Issue by zagortenay333** [linuxmint/cinnamon#6167]
On cinna `3.2`

If the font-size increases or the padding gets reduced, the app description text will overflow:
![workspace 4_001](https://cloud.githubusercontent.com/assets/11144630/21646651/41f94492-d297-11e6-954c-1d2aa6df98f7.png)

The way the height is calculated is kinda weird:
https://github.com/linuxmint/Cinnamon/blob/634a88df55aff5bc9acb647d162f20647660a5dd/files/usr/share/cinnamon/applets/menu%40cinnamon.org/applet.js#L2879

**Comment by icarter09** [comment]
@zagortenay333 are you still experiencing this issue?

**Comment by zagortenay333** [comment]
No, It's been 82 years since I used cinnamon.
