### ISSUE TITLE
Power applet: changing display setting takes effect only after restaring Cinnamon . .

### ISSUE THREAD

**Issue by CottonEaster** [linuxmint/Cinnamon#6169]
. . and there was subsequent weirdness in the form of the brightness constantly decreasing, but that latter problem may owe to my attempts to get my system adjusting brightness on resume and and at-boot-depending-on-power-status, etc.

By 'changing display setting' I mean (at least): changing the applet from showing only a percentage to showing a percentage and an estimated time remaining (and by 'at least' I mean: that was the setting change that I had the problem with; I didn't try others).

Mint 18.1 x64.

**Comment by ACinnamonUserInUK** [comment]
Please disregard the above. I was getting confused between the _tooltip_ and the actual panel text . .

**Comment by ACinnamonUserInUK** [comment]
But there is the brightness weirdness, which I can now specify: every time I hover over the brightness applet, the screen brightness decreases! What?!

**Comment by CottonEaster** [comment]
Possibly the problem was with scripts that I run. At any rate, this particular problem has not reoccured.
