### ISSUE TITLE
Vertical Panel and Hotcorner icon overlap

### ISSUE THREAD

**Issue by anandrkris** [linuxmint/Cinnamon#6170]
Steps to reproduce:
1. Add a vertical panel 
2. Enable Hot corners with icon visible 

You will see overlap of hot corner icon over panel. I guess icon should be off by width of panel.

**Comment by JosephMcc** [comment]
For me this has nothing to do with a vertical panel. It even happens with just a top panel. It seems like the placement ignore the panels completely.

**Comment by anandrkris** [comment]
Yes realized that later - with bottom panel too. :smiley:

**Comment by JosephMcc** [comment]
This is no longer issue. These were an old leftover we inherited from Gnome. There was no neat way to make these work with all the possible panel layouts in Cinnamon. After chatting about this with the other devs we actually decided to remove them.
