### ISSUE TITLE
Network Manager Applet IPv4 manual address to automatic (DHCP) switch breaks default route

### ISSUE THREAD

**Issue by benoitmartin88** [linuxmint/cinnamon#6172]
Using a wired connection (eth0) in manual IPv4 addressing (with defined address, netmask and gateway) and switching back to automatic mode (DHCP), the manually set route still remains (default route is wrong).

Steps to reproduce:

1. Set manual address
address: 192.168.1.42
netmask: 255.255.255.0
gateway: 192.168.1.1

2. Apply and force change
hit apply button
turn wired interface off, than on -> manual address is applied
check ip route: 
```
$ip route
default via 192.168.1.1 dev eth0  proto static  metric 1024 
169.254.0.0/16 dev eth0  scope link  metric 1000 
192.168.1.0/24 dev eth0  proto kernel  scope link  src 192.168.1.42
```
Everything is OK.

3. Set automatic (DHPC)

4. Apply and force change
hit apply button
turn wired interface off, than on
check ip route:
```
$ip route
default via 192.168.1.1 dev eth0  proto static  metric 1024 
169.254.0.0/16 dev eth0  scope link  metric 1000 
192.168.1.0/24 dev eth0  proto kernel  scope link  src 192.168.1.32
```

Here default route is wrong. It should have been **192.168.1.254** (set by DHCP server) not **192.168.1.1** 

Solution:

1. Go back to manual configuration and delete all the fields (address, netmask and gateway)
2. Do not apply and switch to automatic (DHCP) and hit apply
3. Turn wired interface off, than on -> Everything works as expected

Configuration:
LMDE2 fully updated as of 05/01/2017

**Comment by Vahan86** [comment]
@benoitmartin88, is this still an issue in Cinnamon 4.2?

**Comment by Vahan86** [comment]
@icarter09, can we close the issue since there is no response from OP?
