### ISSUE TITLE
avatar is blurred on lockscreen

### ISSUE THREAD

**Issue by igordovgaluk** [linuxmint/Cinnamon#6173]
user's avatar is blurred on lockscreen.
cinnamon 3.2.7 (Mint 18.1)

when avatar was set the selected image had 1000x1000 pixels.
maybe internally in cinnamon the reduced image is stored that is too small for the lockscreen.

**Comment by JosephMcc** [comment]
Could you please move this here: https://github.com/linuxmint/cinnamon-screensaver/issues
Since the lock screen is completely new it would be nice to keep these gathered together.

**Comment by igordovgaluk** [comment]
looks like same as https://github.com/linuxmint/cinnamon-screensaver/issues/187
