### ISSUE TITLE
A further security measure for encrypted Home directory

### ISSUE THREAD

**Issue by icefapper** [linuxmint/Cinnamon#6174]
Hello, and thanks a lot for all you have done!
I couldn't come up with a better repository to file this issue (which is more of a suggestion), so I would be glad indeed knowing where else I should file this issue in.
We all know Linux mint can be installed such that the Home folder is encrypted; this is an exceptionally useful feature, ensuring that most of the users data will be out of the reach of someone who has stolen/confiscated their machine.
In my case at least, this was the case.
I had chosen an arguably strong password, and had chosen to encrypt my Home folder while I was installing LM 18.1.
I'm not going to get into details, but when my laptop was confiscated by the police last week, I was sure they won't be able to access my data.

They indeed weren't. Not without knowing the password, at the very least.

So they came back to me and threatened me into tell them the password. I told them the wrong password for several times, but I was finally made to tell them the true password.

While I appreciate the feature I'm asking is somewhat weird, I still believe it would be worth considering:
 
My suggestion is, what about letting a user log in, even after entering the wrong password, but limiting their access to the computer's resources without them knowing it? 

That way, an intruder who tries to log into a confiscated computer will be able to log in, but all he will find is an empty Home directory, etc. etc.

There can even be an "Intruder Account Settings" specifically tailored to let the user choose whether an intruder, or someone who has logged in with a wrong password, can access the internet, printer,     you name it.

That might sound a bit funny to those in countries with more humane governments, but would be a great security boon to those in less humane ones.

Thanks a lot, in advance.

**Comment by leigh123linux** [comment]
This isn't something that can be added to cinnamon source code.
I also doubt it's within the scope of any current Linuxmint package, maybe you should ask at ubuntu instead (mint uses this a their base).


P.S I understand the need and I also understand the negatives.

1. If a government gets hold of the PC they wouldn't be that dumb to miss the encrypted data and just torture/hold the person till they reveal the password.
2. Why make it easier for 'kiddie fuckers' to hide their perversions and escape justice.

**Comment by clefebvre** [comment]
Hi,

I can understand why you would want such personal protection but that goes beyond the scope of our project.

If your data is personal to the point where nobody should be able to access it, even in cases where they are able to obtain the password from you, then you need to booby trap it and think of a way for it to get destroyed when that password is used without your consent.

That's not something we do though.
