### ISSUE TITLE
No desktop text

### ISSUE THREAD

**Issue by LEGOlord208** [linuxmint/Cinnamon#6175]
Suddenly, this!
![image](https://cloud.githubusercontent.com/assets/12830969/21716719/8040bf02-d40c-11e6-849c-2e3eb141c94d.png)

Additional info:

 - Restarted Cinnemon (Alt+F2 and 'r')

 - Couldn't take screenshot with the usual PrntScr shortcut

 - Text gone with the screenshot tool as well until hover.

I'm now going to restart my PC

**Comment by JosephMcc** [comment]
Did a restart fix the issue? If so has it come back?

**Comment by LEGOlord208** [comment]
Yes thank you, never had the issue since =)

**Comment by JosephMcc** [comment]
Ok, I'm going to close this but it can always be reopened if the issue reoccurs.
