### ISSUE TITLE
Error cinnamon-settings, ValueError: execv() arg 2 first element cannot be empty

### ISSUE THREAD

**Issue by JoseluCross** [linuxmint/Cinnamon#6176]
Hello, today after update all my installed packages (I am using Arch Linux) cinnamon-settings didn't start. I tried to start it in the console and I got this track information error:

Traceback (most recent call last):
  File "/usr/bin/cinnamon-settings", line 26, in <module>
    os.execvp("/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", ("",) + tuple(sys.argv[1:]))
  File "/usr/lib/python3.6/os.py", line 559, in execvp
    _execvpe(file, args)
  File "/usr/lib/python3.6/os.py", line 583, in _execvpe
    exec_func(file, *argrest)
ValueError: execv() arg 2 first element cannot be empty

I changed this line and I substituded it for ***os.execvp("/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", ("sound",) + tuple(sys.argv[1:]))*** and it started but I suppose that isn't the right solution.

**Comment by Odyseus** [comment]
Hello, @JoseluCross.

That's due to Python 3.6. It's already fixed on [Cinnamon's code](https://github.com/linuxmint/Cinnamon/commit/3936ac1e355e9a5f1c2edd1aae4e6da9d2855f45).

**Comment by JoseluCross** [comment]
Ok, thank you very much
