### ISSUE TITLE
variant name in keyboard@cinnamon.org shortened to two letters

### ISSUE THREAD

**Issue by jonorthwash** [linuxmint/Cinnamon#6179]
As of an upgrade from Cinnamon 3.0 to 3.2, three letter language codes in the keyboard layout indicator are being shortened to two letters.  E.g., "nor" and "nob" both show up as "no" (and if used together, they seem to get numbers, like no¹ and no²).

Note that this is with the new option "Show the layout name instead of the group name when using text to represent a layout" (unlocalised "keyboard-layout-prefer-variant-names") option enabled—which I believe was the only option previously.

**Comment by jonorthwash** [comment]
I guess it's probably a change to `get_variant_label_for_group()`, but I'm not sure where that's defined.

**Comment by mikhail-ekzi** [comment]
@jonorthwash here it is https://github.com/linuxmint/xapps/blob/master/libxapp/xapp-kbd-layout-controller.c, which is wrapping libxapp

**Comment by jonorthwash** [comment]
Thanks @mikhail-ekzi.  Anyone know why this change was made?  I assume that reverting it isn't the best way to fix it...

**Comment by mtwebster** [comment]
https://github.com/linuxmint/xapps/commit/2ed3c476d8dbdb38ad4b31d12ec3c3d2b6374366

I actually couldn't get 3-letter "nor" or "nob" out of anything - Norwegian layouts always come back "no", though I can reproduce the issue, and this should take care of it.  Could be it was changed upstream (in xkb?)  What layouts are you expecting it on?

I think I kept it limited to two originally so I could have better layout consistency between the various users of this keyboard layout indicator (cinnamon applet uses it, also the screensaver), but having tested with 3, they seem to handle it fine.

**Comment by jonorthwash** [comment]
For day-to-day usage, I've made some custom layouts that cover most of the languages I type commonly.

Your reasoning actually sounds good, but it sounds like these other indicators are improperly shortening it too, then.  Perhaps Cinnamon could lead the way and leave the decision about 2- or 3-letter abbreviations to the user, at least in this situation?
