### ISSUE TITLE
Keyboard layout applet misbehaves

### ISSUE THREAD

**Issue by DavidNemeskey** [linuxmint/Cinnamon#6181]
There are two issues I've found with it, both quite serious:
1. I cannot change languages with the mouse (by first clicking on the applet, then the language). The keyboard shortcut works.
2. ~~I created another user account. The keyboard layout applet is on the panel by default, but it is invisible. When I check its placement via the Applets window, it seems to be hiding behind / overlapping with other applets. However, I could not make it appear neither by removing the other applets, nor by removing and adding the layout applet itself back.~~

**Comment by NikoKrause** [comment]
Regarding No. 2
How many languages were added in the new account? It only shows up, when there is more than 1 language.

**Comment by DavidNemeskey** [comment]
@NikoKrause Of course, you are right: English was the only layout. Added Hungarian, and the applet now shows up on the panel.

While this is not relevant to the current issue, I find it very odd that language support and keyboard layouts are in separate programs. They should be accessible from each other (at least the layouts from language support), as they tackle basically the same problem (reading / writing). Also, Language support doesn't even show up in Settings?

**Comment by NikoKrause** [comment]
Changing languages in the applet works as expected. Unless you don't provide any information on how to reproduce it, I'll close this for now. If the issue still persists, this can be reopened later, when more info is provided.
