### ISSUE TITLE
[feature request][power manager] On-dock power management

### ISSUE THREAD

**Issue by elegantandrogyne** [linuxmint/cinnamon#6186]
Add a third column with separate screen-off/sleep times and button/lid actions relating to docked laptops.

Rationale:

Some laptops behave differently on dock and on AC or battery power, hence require specific power management options.

For example, the IBM/Lenovo Advanced Dock 2503 and Advanced Mini Dock 2504 have parallel ports, with a nasty issue: every time a docked laptop (Thinkpads T6x and W500 are affected, more probably so) loses external power, it crashed and has to be power-cycled. The catch: while on 2504 you need to be extra careful not to disconnect the AC power, the 2503 has an internal power supply which turns itself off automatically when a laptop is undocked, turned off or goes on standby. Every time the laptop goes on standby, it freezes, so it's crucial to prevent the laptop from going on standby on dock.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
