### ISSUE TITLE
Cinnamon - Nvidia driver

### ISSUE THREAD

**Issue by donnsd** [linuxmint/cinnamon#6187]
Cinnamon does not preserve the xkb options settings during a suspend-resume cycle when using the Nvidia driver.  The xkb user options are preserved when using the nouveau driver.  I have done a new install of Mint KDE with Nvidia and Mint Mate with Nvidia, they seem to work fine.  The issue seems to be in cinnamon, though I don't understand why nouveau works and Nvidia doesn't.  You should be able to reproduce the problem.  With a working cinnamon system, install the Nvidia driver (driver manager is fine), restart, login, type setxkbmap -query, the terminate option should be set, do suspend-resume, type setxkbmap -query, the terminate option will be cleared.
Thanks, Don

**Comment by Vahan86** [comment]
@donnsd, is this still an issue in Cinnamon 4.2?

**Comment by Vahan86** [comment]
@icarter09, can we close the issue since there is no response from OP?
