### ISSUE TITLE
[Feature Request] Window list should be able to ignore / blacklist certain programs

### ISSUE THREAD

**Issue by imarkskinner** [linuxmint/Cinnamon#6188]
This might be a very subjective suggestion but I feel it would be good if some programs could be excluded from the window list and the windows quick list. By excluded I mean to not appear in the window list despite being open.

Thoughts?

**Comment by JosephMcc** [comment]
Thank you for your suggestion. See https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html for information on how we handle feature requests.
