### ISSUE TITLE
Crash on shutdown

### ISSUE THREAD

**Issue by HerHde** [linuxmint/Cinnamon#6190]
Ahoj,
my Cinnamon often crashes, when I shut down my notebook. Cinnamon restarts in failsafe mode and the system shuts down after a while, therefore it is not critical.

I'm running Cinnamon 3.2.7 on Linux Mint 18.1. Any additional info needed?

Greetings
~HerHde

**Comment by JosephMcc** [comment]
After it crashes and restarts in fallback mode, check your xsession-errors. There will often be a clue as to what the problem is.

**Comment by clefebvre** [comment]
We believe this issue is fixed. Please test against the latest Cinnamon version (3.6). If the issue happens again, create a new issue and add a stracktrace.
