### ISSUE TITLE
tagging

### ISSUE THREAD

**Issue by icefapper** [linuxmint/Cinnamon#6193]
It would be great if a "tagging" mechanism could be incorporated into Linux mint's file/folder manager. That way, several "tags" can be attributed to a file/folder (possible via the properties dialog box).

Then, much like a "Tree view" sidebar will let the user have a high level view of the directory structure, a "Tag view" (which possible augments other view types, rather than replace them) will let them view only the elements that have a certain tag associated with them. 

Among advantages this has over the traditional "same things in a folder with a relevant name" approach is that more than a single tag can be associated with a single elements.

Thank you.

**Comment by JosephMcc** [comment]
This belongs to Nemo: https://github.com/linuxmint/nemo/issues
