### ISSUE TITLE
Add keyboard layout for application

### ISSUE THREAD

**Issue by rizado** [linuxmint/cinnamon#6195]
Now is two variants for using keyboad layouts - global and different layout for any window.
Please add capability to set keyboard layout for application - when I have some windows of one application (for example, Firefox, Thunderbird etc.), it's good to use the same layout for all application windows.
Now for this I use third-part switcher (gxkb).
Thanks!

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
