### ISSUE TITLE
Crash on Background Wallpaper change

### ISSUE THREAD

**Issue by boardpusher** [linuxmint/Cinnamon#6196]
After removing the Pictures folder from locations for wallpaper slideshow, system instantly crashed. Everytime I enter "Change Desktop Background", either the screen freezes after it shows thumbnails of backgrounds, or it instantly restarts the system. My system:

 

System:    Host: Minus Kernel: 4.4.0-59-generic x86_64 (64 bit gcc: 5.4.0)
           Desktop: Cinnamon 3.2.7 (Gtk 3.18.9-1ubuntu3.1) dm: mdm Distro: Linux Mint 18.1 Serena
Machine:   System: Gigabyte product: N/A Chassis: type: 3
           Mobo: Gigabyte model: 970A-DS3P v: x.x Bios: American Megatrends v: FC date: 06/01/2015
CPU:       Hexa core AMD FX-6350 Six-Core (-MCP-) cache: 12288 KB
           flags: (lm nx sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm) bmips: 49427
           clock speeds: min/max: 1400/4100 MHz 1: 1400 MHz 2: 1400 MHz 3: 1400 MHz 4: 2000 MHz
           5: 2500 MHz 6: 1400 MHz
Graphics:  Card: Advanced Micro Devices [AMD/ATI] Device 67df bus-ID: 01:00.0 chip-ID: 1002:67df
           Display Server: X.Org 1.18.4 drivers: ati,amdgpu (unloaded: fbdev,vesa,radeon)
           Resolution: 1920x1080@119.98hz, 1920x1080@60.00hz
           GLX Renderer: AMD Radeon RX 470 Graphics
           GLX Version: 4.5.13462 - CPC 16.50.5 Direct Rendering: Yes
Audio:     Card-1 Advanced Micro Devices [AMD/ATI] Device aaf0
           driver: snd_hda_intel bus-ID: 01:00.1 chip-ID: 1002:aaf0
           Card-2 Advanced Micro Devices [AMD/ATI] SBx00 Azalia (Intel HDA)
           driver: snd_hda_intel bus-ID: 00:14.2 chip-ID: 1002:4383
           Sound: Advanced Linux Sound Architecture v: k4.4.0-59-generic
Network:   Card: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller
           driver: r8169 v: 2.3LK-NAPI port: d000 bus-ID: 03:00.0 chip-ID: 10ec:8168
           IF: enp3s0 state: up speed: 1000 Mbps duplex: full mac: <filter>
Drives:    HDD Total Size: 515.1GB (8.6% used)
           ID-1: /dev/sda model: ADATA_SP550 size: 240.1GB serial: 2G1020004142
           ID-2: /dev/sdb model: Crucial_CT275MX3 size: 275.1GB serial: 16401429549B
Partition: ID-1: / size: 200G used: 23G (12%) fs: ext4 dev: /dev/sda2
           ID-2: swap-1 size: 21.44GB used: 0.00GB (0%) fs: swap dev: /dev/sda3
RAID:      System: supported: N/A
           No RAID devices: /proc/mdstat, md_mod kernel module present
           Unused Devices: none
Sensors:   System Temperatures: cpu: 29.4C mobo: N/A gpu: 45.0
           Fan Speeds (in rpm): cpu: N/A
Repos:     Active apt sources in file: /etc/apt/sources.list.d/amdgpu-pro.list
           deb [ trusted=yes ] file:/var/opt/amdgpu-pro-local/ ./
           Active apt sources in file: /etc/apt/sources.list.d/google-chrome.list
           deb [arch=amd64] http: //dl.google.com/linux/chrome/deb/ stable main
           Active apt sources in file: /etc/apt/sources.list.d/official-package-repositories.list
           deb http: //packages.linuxmint.com serena main upstream import backport
           deb http: //mirror.lstn.net/ubuntu xenial main restricted universe multiverse
           deb http: //mirror.lstn.net/ubuntu xenial-updates main restricted universe multiverse
           deb http: //mirror.lstn.net/ubuntu xenial-backports main restricted universe multiverse
           deb http: //security.ubuntu.com/ubuntu/ xenial-security main restricted universe multiverse
           deb http: //archive.canonical.com/ubuntu/ xenial partner
           Active apt sources in file: /etc/apt/sources.list.d/steam.list
           deb [arch=amd64,i386] http: //repo.steampowered.com/steam/ precise steam
           deb-src [arch=amd64,i386] http: //repo.steampowered.com/steam/ precise steam
Info:      Processes: 227 Uptime: 12 min Memory: 2426.3/20110.7MB
           Init: systemd v: 229 runlevel: 5 default: 2 Gcc sys: 5.4.0
           Client: Unknown python2.7 client inxi: 2.2.35

**Comment by clefebvre** [comment]
We believe this issue is fixed. Please test against the latest Cinnamon version (3.6). If the issue happens again, create a new issue and add a stracktrace.
