### ISSUE TITLE
System Wide Display Settings

### ISSUE THREAD

**Issue by imarkskinner** [linuxmint/cinnamon#6197]
So @clefebvre  you said it yourself a few years back 
![screenshot-area-2017-01-12-204335](https://cloud.githubusercontent.com/assets/1920963/21907679/6c02cb24-d908-11e6-9fa0-f7ef7c88a980.png)

Here's the rest of it http://segfault.linuxmint.com/2015/08/configuring-the-mdm-login-screen-for-multiple-monitors/

I'm mostly looking at the bit that reads "With that said though, I wouldn’t mind if we could add a feature to these. Say a little button to “Apply to Xorg configuration”. Or in the login screen configuration tool, to “Apply current monitor settings to MDM”."

Personally I think it should be in the display settings an option for "Apply settings system wide", just thinking that the mention of Xorg or MDM might just confuse people who don't know what that means.

I put this under Cinnamon in general because I suppose until you know where this button is going I can't complain about a specific part of the Cinnamon experience. 

I wish I was a coder and could help, alas I'm not, I can't even successfully configure my own Xorg which led me down this rabbit hole (and xrandr commands aren't seeming to work properly in MDM for me), all I can do is remind you of what you once thought would be a good idea and keep my fingers crossed that you still do.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
