### ISSUE TITLE
Add restart network manager option to network applet

### ISSUE THREAD

**Issue by freemangilgamesh** [linuxmint/Cinnamon#6198]
I suggest you add a "restart network manager" to network applet. It saves us the hassle of restarting the whole system.

**Comment by hannesfrank** [comment]
:+1:

Meanwhile you can use `sudo service network-manager restart` instead of a system restart.

**Comment by ManIVIctorious** [comment]
Btw, on a systemd distribution the command would be `systemctl restart NetworkManager`
