### ISSUE TITLE
[Feature request] Remove the redundant HDD icon next to 'File System' in the 'Computer' window

### ISSUE THREAD

**Issue by chrBrd** [linuxmint/Cinnamon#6200]
Is there a purpose to it? I've just spent hours 'troubleshooting' its existence on a single-drive build as it doesn't exist on my multi-boot, multi-partitioned, multi-drive work machine and I thought it was a bug or potentially symptomatic of of a drive fault.

From my perspective it seems both redundant and a little confusing ('File System' would serve the same purpose on its own), although I appreciate it may well serve a function I was too myopic to notice.

**Comment by leigh123linux** [comment]
You have filed the issue in the wrong place. please refile it

https://github.com/linuxmint/nemo
