### ISSUE TITLE
Background reverts to default on certain events in Ubuntu 16.04

### ISSUE THREAD

**Issue by williamtwomey** [linuxmint/Cinnamon#6202]
DISTRIB_DESCRIPTION="Ubuntu 16.04.1 LTS"
cinnamon       2.8.6-1ubunt

Running full disk encryption rather than just having home folder encrypted. 

I've noticed the following events cause my wallpaper to go back to Ubuntu's default:

1. Calendar reminder pops up from evolution

2. Plugging in my phone (Nexus 5X) and the file browser pops up

I see the following in /var/log/syslog when this happens

Jan 13 17:14:27 E6540 org.gtk.vfs.Daemon[2054]: Error 1: Get Storage information failed.
Jan 13 17:14:27 E6540 org.gtk.vfs.GPhoto2VolumeMonitor[2054]: (process:2140): GVFS-GPhoto2-WARNING **: device (null) has no BUSNUM property, ignoring
Jan 13 17:14:27 E6540 dbus[1277]: [system] Activating via systemd: service name='org.freedesktop.hostname1' unit='dbus-org.freedesktop.hostname1.service'
Jan 13 17:14:27 E6540 systemd[1]: Starting Hostname Service...
Jan 13 17:14:27 E6540 dbus[1277]: [system] Successfully activated service 'org.freedesktop.hostname1'
Jan 13 17:14:27 E6540 systemd[1]: Started Hostname Service.
Jan 13 17:14:30 E6540 colord-sane: io/hpmud/pp.c 627: unable to read device-id ret=-1

I'm happy to provide any information I can to help narrow this down.

**Comment by JosephMcc** [comment]
https://github.com/linuxmint/Cinnamon/issues/3953
