### ISSUE TITLE
[LM18] ALC 889 not showing up in sound settings

### ISSUE THREAD

**Issue by bitboy85** [linuxmint/Cinnamon#6204]
I think the issue is the same as in Ubuntu 16.04 http://askubuntu.com/questions/762414/problems-with-audio-device-alc-889-ubuntu-16-04

It was working fine in LM 17.

**Comment by leigh123linux** [comment]
File your issue against the kernel instead.

**Comment by bitboy85** [comment]
I'm not sure if it is a kernel issue. Have a look at this link. Executing the command will show up the card in the sound panel (but without icon).
https://www.marcus-povey.co.uk/2016/10/27/ubuntu-16-04-sound-fixes-for-intel-hda-azalia/
With pavucontrol it is also possible to set it as output (with sorround issues).

**Comment by leigh123linux** [comment]
That still isn't a cinnamon issue, seems like ubuntu have busted pulseaudio.
