### ISSUE TITLE
Automatic mnemonics "feature" is broken

### ISSUE THREAD

**Issue by geoffm** [linuxmint/Cinnamon#6206]
Summary:
- Make the keyboard shortcuts display all the time OR, at least, make the "automatic mnemonics" work by fixing the description so we can understand, and making it actually work when we active/deactivate it
- remove the 2 seconds wait before "mnemonics" are displayed when user presses Alt

Explanation:
There's this useless and unproductive "feature" where the menu keyboard shortcuts (underlined letter) are hidden until 2 seconds after the user hits Alt. They should be shown all the time so people can know keyboard shortcuts exist (a skill that is more and more disapearing unfortunately) and can use them when they need to. 
In dconf there's this option "automatic mnemonics" (/org/cinnamon/desktop/interface/automatic-mnemonics).
It's description which goes "Whether mnemonics should be automatically shown and hidden when the user presses the Alt key." is unclear. Setting it to true or false doesn't changte anything.
Also, even if for some reason you really really want the "mnemonics" to be hidden, there is absolutely no reason to wait for 2 seconds before showing them when  the user presses ALT.

**Comment by JosephMcc** [comment]
You're complaining in the wrong place. It behaves that way due to changes in gtk and not something we can really control in Cinnamon. If you play around a bit you find they behave slightly differently in gtk2, gtk3, and qt applications.
