### ISSUE TITLE
Chameleonic Cinnamon theme

### ISSUE THREAD

**Issue by freemangilgamesh** [linuxmint/Cinnamon#6208]
what about a chameleonic Cinnamon theme that match the wallpaper and GTK theme just like they have on Microslop Windblows!!

something like this http://www.webupd8.org/2012/06/elegance-colors-cool-chameleonic-gnome.html

and this http://www.omgubuntu.co.uk/2012/05/chameleonic-ambiance-script-matches-gtk-theme-to-your-wallpaper and this  http://satya164.deviantart.com/art/Cinnamon-Minty-Colors-304552689

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
