### ISSUE TITLE
Ctrl+Alt+L does not work with desktop item selected

### ISSUE THREAD

**Issue by LEGOlord208** [linuxmint/Cinnamon#6210]
Like the title says. You can't have selected a desktop item for Ctrl+Alt+L to work. It's supposed to lock the screen ;)

**Comment by JosephMcc** [comment]
It seems to work fine here. Please add some info like cinnamon and nemo version and the OS you are running.

**Comment by LEGOlord208** [comment]
And yet again I embarresed myself - Suddenly everything works again... I really wish GitHub would let you remove issues :|
