### ISSUE TITLE
Start menu items flickering

### ISSUE THREAD

**Issue by legolord208** [linuxmint/Cinnamon#6211]
When hovering and moving, the start menu items flicker.
https://youtu.be/H7quFvLu1fc

Please ignore the unprofessional and annoying desktop flicker (when the whole screen flickers). That is just OBS. Focus on the menu items.

On Linux Mint 18

**Comment by AugustZellmer** [comment]
Oh yeah I'd noticed this too.
Not a huge problem, but definitely not a good thing.

**Comment by JosephMcc** [comment]
I can reproduce this.

**Comment by JosephMcc** [comment]
This should now be fixed in git master.
