### ISSUE TITLE
Cannot right-click a panel when the 'Save Screenshot' is open

### ISSUE THREAD

**Issue by DG-Tal** [linuxmint/cinnamon#6213]
cinnamon version: 3.0.7

Step to reproduce:
1.Press the PrintScreen button
2. Right click a blank spot on a panel

Right-clicking icons on the panel or other things on the desktop work as intended.

**Comment by icarter09** [comment]
@DG-Tal are you still experiencing this issue?

**Comment by JosephMcc** [comment]
I can't reproduce this anymore. It seems to work fine here now.

**Comment by Vahan86** [comment]
I can't reproduce the issue as well, it works fine for me in Cinnamon 4.4.5.
