### ISSUE TITLE
Unable to connect to WPA Enterprise (WPA-802.1x) WLAN

### ISSUE THREAD

**Issue by paulmenzel** [linuxmint/Cinnamon#6215]
Using Ubuntu 16.04 with the package *cinnamon-control-center* 3.2.0-1, it’s impossible to connect to a WPA Enterprise WLAN, in this case an Eduroam network.

Clicking on the play button, a spinner starts, but nothing happens. On the console the following is printed.

```
GLib-GObject-WARNING **: g_object_set_valist: object class 'CcNetworkPanel' has no property named 'parameters'
```

This can be worked around, by using the dialog for hidden networks.

**Comment by JosephMcc** [comment]
https://github.com/linuxmint/Cinnamon/issues/3623

**Comment by paulmenzel** [comment]
@JosephMcc, I looked at issue #3623 before creating this issue, and I am think it’s about a different issue, as it’s about a segmentation fault, which I don’t get. So in my opinion, it’s not a duplicate.

Addtionally testing Ubuntu 16.10 with Cinnamon 3.2.2, the behavior is reproducible. The spinner just keeps on turning when clicking on the play symbol next to the WLAN name.

In the background the command below is executed.

```
python2 /usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py network connect-8021x-wifi /org/freedesktop/NetworkManager/Devices/0 /org/freedesktop/NetworkManager/AccessPoint/227
```

**Comment by paulmenzel** [comment]
@JosephMcc, I looked at issue #3623 before creating this issue, and I am think it’s about a different issue, as it’s about a segmentation fault, which I don’t get. So in my opinion, it’s not a duplicate.

Addtionally testing Ubuntu 16.10 with Cinnamon 3.2.2, the behavior is reproducible. The spinner just keeps on turning when clicking on the play symbol next to the WLAN name.

In the background the command below is executed.

```
python2 /usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py network connect-8021x-wifi /org/freedesktop/NetworkManager/Devices/0 /org/freedesktop/NetworkManager/AccessPoint/227
```

**Comment by paulmenzel** [comment]
Running the command below manually, and trying to connect to the WPA Enterprise (WPA-802.1x) WLAN the same error is shown.

```
$ python2 /usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py network connect-8021x-wifi /org/freedesktop/NetworkManager/Devices/0 /org/freedesktop/NetworkManager/AccessPoint/227
/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py:608: Warning: g_object_set_valist: object class 'CcNetworkPanel' has no property named 'parameters'
```

**Comment by JosephMcc** [comment]
I know, but the root problem is the same. I'd like to keep them together so we have as much of the info together as possible.
