### ISSUE TITLE
Open file vs Execute file 

### ISSUE THREAD

**Issue by AugustZellmer** [linuxmint/Cinnamon#6217]
This is a feature request. Do with it whatever you'd like.

With Cinnamon, say I have a shell script or some other plaintext executable, and it's NOT set to be executable at the moment. When I right click it, Cinnamon give me the option to open it with Text Editor, or to Open with -> other text editors. This is all great.

Now I set the plaintext to be executable. I right click it, and I have the option to "Open" it, as in run it, or to Open with -> other text editors. I no longer have the option to open it with Text Editor. This is unintuitive. It should give me three options: Run, Open with Text Editor, or Open with -> other text editors. 

Just a thought. Thanks for your time.

**Comment by ChrisJAllan** [comment]
There is an option for whether to open, execute, or ask for executable files, but a right-click option would be very nice. Even more so for .desktop files, which it doesn't give an option for at all.

**Comment by JosephMcc** [comment]
This issue belong with Nemo since it handles that: https://github.com/linuxmint/nemo/issues

**Comment by AugustZellmer** [comment]
My mistake. Thanks for the help!
