### ISSUE TITLE
add "Multihoming" to Cinnamon network manager to connect to the strongest network

### ISSUE THREAD

**Issue by freemangilgamesh** [linuxmint/cinnamon#6220]
Just like on Android's "smart internet switch", I suggest you add the option to switch between multiple network connections at one time. It should automatically switch between two-or more- Internet connections whenever one of them goes down.

**Comment by belandsoft** [comment]
I totally agree

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
