### ISSUE TITLE
Many Qt apps' Hidpi support seems to be broken.

### ISSUE THREAD

**Issue by eladhen** [linuxmint/Cinnamon#6227]
Desktop: Cinnamon 3.2.7  Distro: Linux Mint 18.1 Serena

On MInt 18 I got decent Hidpi support and integration from Qt apps like calibre, VLC, Krita and others. Now these apps seem not to adhere to the Hidpi settings of the desktop, as can be seen in the screenshots. This makes them nearly unusable on a 1080p 13.3" display. I have a suspicion this has something to do with the newer version of Qt or KDE supported... 

VLC besides Nemo:
![vlc](https://cloud.githubusercontent.com/assets/12398651/22398634/84c6536c-e595-11e6-8b65-ebc5221467c2.png)

Krita 3.0 besides Nemo (not Krita 2.9 from the repos):
![krita](https://cloud.githubusercontent.com/assets/12398651/22398644/8c2136b8-e595-11e6-9444-145c9d8618c6.png)

Calibre next to Nemo:
![calibre](https://cloud.githubusercontent.com/assets/12398651/22398654/b46f410a-e595-11e6-908a-70e53395af2d.png)

**Comment by eladhen** [comment]
This seems to be a problem in my installation alone. I tried Mint Cinnamon 18.1 in a virtual machine and I don't get this problem. I'm still not sure how to address this issue, but it seems not to be a general bug...

**Comment by eladhen** [comment]
Ok, just tried another VM of 18.1 and the bug exists there, so this seems more prevalent than I thought...

**Comment by leigh123linux** [comment]
We had a similar issue on fedora

https://bugzilla.redhat.com/show_bug.cgi?id=1381828

**Comment by eladhen** [comment]
Here it is on a freshly installed Mint Cinnamon 18.1 VM:

![virtualbox_linux mint 18 1 cinnamon_01_02_2017_12_32_22](https://cloud.githubusercontent.com/assets/12398651/22503506/b76b30ac-e87a-11e6-917a-a1e5d0153627.png)

**Comment by leigh123linux** [comment]
There is nothing that can be done on the cinnamon side to fix the qt5 issue, please file the issue against qt5-base or whatever ubuntu called it at launchpad bug tracker.

**Comment by eladhen** [comment]
I'm not a developer, But I don't get this problem on Mint Xfce 18.1, and not even on all instances of Mint Cinnamon 18.1, so it seems it has something to do with the implementation of Cinnamon...

**Comment by leigh123linux** [comment]
@eladhen XFCE doesn't use the qgnomeplatform package so is unaffected.

**Comment by eladhen** [comment]
Is there any hope of this being fixed in the foreseeable future? I'm really desperate... :(

**Comment by leigh123linux** [comment]
@eladhen Mint can't fix it as the qt5 packages are from ubuntu repo, the issue needs reporting at launchpad bug tracker and fixing there.

**Comment by eladhen** [comment]
Well I'd gladly report if I knew where...

Be that as it may, I've found out that setting Text Scaling Factor to 1.5 actually makes these Qt apps scale. the intervals 1.0–1.4 don't affect these apps. This is an acceptable workaround for my laptop (1.5 scaling is ok on it). On my desktop this is still problematic, as the best scaling for it is around 1.3, but I can live with the problem for the time being. If you could point me to the right direction I'd gladly report the bug in the correct place.

**Comment by leigh123linux** [comment]
Use the bug link on http://packages.ubuntu.com/source/xenial/qtbase-opensource-src
