### ISSUE TITLE
Black box appears around mouse cursor when taking a screenshot

### ISSUE THREAD

**Issue by crydalch** [linuxmint/Cinnamon#6229]
Cinnamon is leaving a black box around the cursor, when a screenshot is taken. I'm seeing this with Mint 18.1, Cinnamon 3.2.7; it doesn't happen when I use other methods for taking screenshots (gnome screenshot, gimp, maim...). It was working in 17.3.

Run this command to see the problem:
`dbus-send --session --type=method_call --dest=org.Cinnamon /org/Cinnamon org.Cinnamon.Screenshot boolean:true boolean:true string:/tmp/test.png`

It originally came up here: [https://github.com/rjanja/desktop-capture/issues/62
](https://github.com/rjanja/desktop-capture/issues/62)

Thanks!

**Comment by JosephMcc** [comment]
I can reproduce this.

**Comment by leigh123linux** [comment]
@JosephMcc Can you test my PR to confirm it fixes the issue please?

**Comment by JosephMcc** [comment]
@leigh123linux seems to fix the issue for me as well.

**Comment by crydalch** [comment]
Thank you everyone!!!
