### ISSUE TITLE
Removable drives applet enhancements suggestion

### ISSUE THREAD

**Issue by kennethso168** [linuxmint/cinnamon#6231]
1. Nemo can distinguish between internal (with "Unmount" option) and external (with "Safely remove drive" option) drives. However, both are listed in the applet. Maybe the applet should only show the external drives? Since "removable drives" seems external to me.
2. When clicking the "eject" icon in nemo for an external drive, a "safely remove drive" is performed. However, when clicking the "eject" icon in the applet, only an "unmount" is done and the drive is not safely removed. I am not sure if there is any real difference between the two, or any consequence of unplugging an unmounted external USB drive without safely removing it. But I think it is better to standardardize the behaviour between nemo and the applet. Thank you.
(System: Linux Mint 18.1, Cinnamon version 3.2.7)

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
