### ISSUE TITLE
crash on startup

### ISSUE THREAD

**Issue by rcrath** [linuxmint/Cinnamon#6232]
I get a crash on startup for cinnamon.  Fallback does not seem to work either.  It might have something to do with a second display getting disconnected while the laptop was hibernating.  Attaching the coredump from journalctl
[journalctl-cin-crash.txt](https://github.com/linuxmint/Cinnamon/files/740628/journalctl-cin-crash.txt)

**Comment by rcrath** [comment]
I've done a little research and it might be related to the intel graphics card.  no such trouble on the nvidia machine that I also updated.

**Comment by rcrath** [comment]
Still unable to run cinnamon after update to 3.28.  Seems like it might be a video card issue as Cinnamon is running fine on my desktop.  Let me know if I can supply any more info plz.

**Comment by clefebvre** [comment]
We believe this issue is fixed. Please test against the latest Cinnamon version (3.6). If the issue happens again, create a new issue and add a stracktrace.

**Comment by rcrath** [comment]
All good on 3.6.6  Thank you!
