### ISSUE TITLE
Default Sound Device Randomly Chosen After Reboot.

### ISSUE THREAD

**Issue by 1Crimson1** [linuxmint/Cinnamon#6233]
Linux Mint 18.1 Cinnamon 3.2.7
Kernel 4.4.0-59-generic
Intel Core i5-4690K
8GB DDR3 RAM
GeForce GTX 970
Creative Sound Blaster Recon3D Fatal1ty Champion

I have an ASUS 24" monitor hooked up and a Sony Bravia TV, both of which have speakers, and a sound card. After every reboot, I have to manually go into settings--->sound--->and select which sound device is actually on. This seems to happen consistently when I use one device, shut down, turn the last used sound device off, then reboot. The Sony is my main screen and sound device, but Linux Mint is still sending signals to the last used sound device. Perhaps adding a default sound device slider/button would solve this.

**Comment by clefebvre** [comment]
This is upstream from Cinnamon. It looks like a pulseaudio issue.
