### ISSUE TITLE
Delay and lag of brightness OSD with keyboard shortcuts

### ISSUE THREAD

**Issue by Piiit** [linuxmint/Cinnamon#6235]
Pressing FN+Brightness INC/DEC shows the OSD with around 3 seconds delay. The level widget does not update immediately, but if I press brightness increase several times, it jumps up to the final level, not showing intermediate steps. The whole cinnamon desktop is lagging during this operation for around 5 seconds. The brightness itself updates without lag.

Cinnamon 3.2.7
LM 18.1 64bit
Linux 4.4.9
Intel i915 graphics

Please note: If I press FN+Brightness several times with around 1sec pause between, everything works as it should. The main problem occurs while keeping the button pressed... The FN+volume control works without any issue.

**Comment by Piiit** [comment]
@JosephMcc Hi, with Cinnamon 3.4.1 and kernel 4.8.0 this issue seems to be gone. However, I do not know if the kernel update or the cinnamon update solved it.

**Comment by JosephMcc** [comment]
Glad it's sorted. Since it's been open for almost 6 months with not a single other report, I'm going to go ahead and close it.

**Comment by Piiit** [comment]
Ok.

Am 13.06.2017 9:32 nachm. schrieb "JosephMcc" <notifications@github.com>:
