### ISSUE TITLE
trash applet improvements to match default applet behavior

### ISSUE THREAD

**Issue by cruftytheclown** [linuxmint/cinnamon#6238]
When you click on the Trash applet, instead of opening the trash, it should show a menu with the items:  Empty Trash, Open Trash. (And those menu items should be removed from the right click menu.) That would bring it in line with how the default applets work.

Further suggestions: make it so double clicking on it opens the trash, and make it an option to remove the "Open Trash" menu item.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
