### ISSUE TITLE
Main Cinnamon menu suggestions

### ISSUE THREAD

**Issue by cruftytheclown** [linuxmint/cinnamon#6239]
Straight to the point, this is a mockup of my suggestions: ![menubasicfinal](https://cloud.githubusercontent.com/assets/25500496/22578052/c42d9874-e993-11e6-8cc6-b02f41b5c75f.png)
In my 2nd post below I explain the reasons for these changes and why they are beneficial.

Edit: below is my original post, but JosephMcc pointed out some flaws with the ideas in it, so I came up with a new idea in my 2nd post below which is summarized in the graphic above.
...

IMO, the locations of the buttons for the favorites and quit options could be greatly improved. Also, the entire menu is a bit too large due to the current layout and excess spacing.

The favorites are way at the top, far away from your mouse cursor every time you click the LM menu. The quit button is located in the most prime real estate of the entire menu, yet the user only clicks it once per session.

[EDIT: actually, skip to my 2nd post, below, where I have a better suggestion. JosephMcc pointed out a couple reasons why my first idea was flawed.]

My suggested solution involves moving the favorites and quit options somewhere else, which I will explain below. But for starters, I turn them off to get the menu closer to how I'd want it.

When you turn off 'show favorites and quit options' there is too much empty spacing on the main cinnamon menu. There is a big pointless gap to the left of the category menu items. There is also a large rectangle of empty space in the bottom left of the menu.

My suggestions are:
- remove the gap on the left so that the menu items are closer to the left edge of the screen
- bottom align the category menu so there isn't a large empty rectangle space anymore, which also requires you to reduce the height of the 2nd menu column (where the program launching icons are) to equal the height of how many categories you have (so that there is no empty space above the category menu either)

- then take the old favorites and quit options area, and rotate it 90 degrees counter clockwise and jam it onto the bottom of the menu. And scale the spacing down on it just a tad so it fits nicely.

Now you don't have excess gaps and blank rectangle areas, your favorites are in the prime real estate immediately next to your mouse cursor every time you click the LM menu, and the quit button is off to the right where you will use it less frequently than you use your favorites or even the rest of the menu most likely. And the whole menu is tighter and less bulky.

It would look roughly like this (but of course the favorites and quit options would look nicer than this): 
![menu](https://cloud.githubusercontent.com/assets/25500496/22546658/fda8b166-e90b-11e6-830f-42b2a7db59e0.png)

**Comment by JosephMcc** [comment]
> The favorites are way at the top, far away from your mouse cursor every time you click the LM menu. The quit button is located in the most prime real estate of the entire menu, yet the user only clicks it once per session.

You're ignoring the fact that the menu can be placed on any screen edge. The machine I'm on right now has the menu located at the top so your argument doesn't work.

>bottom align the category menu so there isn't a large empty rectangle space anymore

There isn't a big empty rectangle. That area is used to provide additional info when hovering over an icon for an application.

> then take the old favorites and quit options area, and rotate it 90 degrees counter clockwise and jam it onto the bottom of the menu. And scale the spacing down on it just a tad so it fits nicely.

You can't really scale it down so if fits nicely. It can hold an arbitrary number of favorites so you could easily end up with a very wide menu with a bunch of empty space on the left side. That would be horrible if you placed the menu anywhere on the right side of the screen.

> When you turn off 'show favorites and quit options' there is too much empty spacing on the main cinnamon menu

Yeah, there is an open issue for this already.

**Comment by cruftytheclown** [comment]
> You're ignoring the fact that the menu can be placed on any screen edge. The machine I'm on right now has the menu located at the top so your argument doesn't work.

My argument doesn't cover all cases, but it still works. Menu on the bottom is the default. The argument still applies to the menu on the bottom.

> There isn't a big empty rectangle. That area is used to provide additional info when hovering over an icon for an application.

No, there is, see: 
![rectangle](https://cloud.githubusercontent.com/assets/25500496/22548658/8c766cb8-e915-11e6-8410-a87a539cc11b.png)

> You can't really scale it down so if fits nicely. It can hold an arbitrary number of favorites

Oh hmm, yes I overlooked that.  Well, come to think of it now that I look at it, everything about the menu seems to have been designed for it to be in the top left corner. For the top left corner, the favorites are in a great place, the quit button is not in a bad place, there isn't an empty rectangle space to have to traverse, the program descriptions are way off to the bottom instead of creating a gap right next to the panel, the program categories are grouped together first, with the admin, prefs, and places beyond them, and the search box is right there.

My first idea in my image in the first post isn't good enough since it doesn't consider the various menu locations or additional favorites.

But since the menu can be placed in so many locations, it shouldn't be designed (and it clearly is imho) to only be best from the top left corner - doubly so when you consider that the default location is the bottom left corner.

Ok, well here is my new idea, starting from the current cinnamon main menu,
1. divorce the 'quit options' buttons from the favorites, and remove them. But otherwise leave the favorites just how they are now.
2. put the 'quit options' buttons (but in simple black on transparent style graphics) horizontally next to the search box, a spot which is currently empty
3. shorten the right menu item column to be no taller than the left category column (to eliminate the empty space I circled in red above)
4. arguably, when the menu is on the bottom panel (not when it's on the top), put All Applications at the bottom, and put Admin, Prefs, and Places at the top above the program categories. Also, put the search box and quit buttons line at the bottom of the menu, and put the program descriptions at the top.
(5. fix the left side spacing when favorites are hidden, but like you said there is an open issue for that already)

This image shows the changes including change number 4 (the flipping from top to bottom of certain elements), but, you could imagine it without change number 4 as well, and it would also work. Note that when the menu is on the top panel, those elements would be where they are currently, not flipped like this.
![menu2](https://cloud.githubusercontent.com/assets/25500496/22551597/54b9c500-e923-11e6-8722-f66963077526.png)

Hopefully I haven't overlooked anything else. I think this would be a significant improvement for the menu when it's on the bottom panel, while also being only a minor change to the menu when it's on the top panel.

**Comment by germanfr** [comment]
Sorry but this layout you proposed feels like everything is out of place to me. Some things are aligned to bottom and other to top. And I don't think the overall experience would increase with this change (and I'm of those who has a lazy hand). This is why.

There's no point on moving the search bar to the bottom. You don't ever need to click it since it has the focus automatically. The distance to the apps is the same (search vs description). 

Also there's no such improvement on moving the favs down because it's not a fast action (not even with that change) because opening the menu is still where most time is spent. For more common and fast actions you should use the panel launchers.

The only drawback I see to the current layout is that the categories are between me and the apps, and I have to avoid them with the mouse or it will go crazy auto changing to some category, because there's no way to disable that. But everything feels placed in harmony right now.

**Comment by xenopeek** [comment]
> bottom align the category menu so there isn't a large empty rectangle space anymore

Just my 2 cents but the number of categories depend on the installed programs. Say you don't play games and need no graphics tools. The menu should shrink because of that? Similarly if you have a lot of different programs installed there will be more categories than shown in your menu. I don't think the menu should grow or shrink based on the number of categories.

**Comment by JosephMcc** [comment]
>  I don't think the menu should grow or shrink based on the number of categories.

Currently it has to. If not we would have to put some sort of scrollbar right in the center of the menu to allowing scrolling the Categories if they don't fit. Really would rather avoid that.

**Comment by cruftytheclown** [comment]
You bring up a good point xenopeek, which is that I didn't account for the possibility of there being fewer categories.

I see that on a fresh install, it's the 'favorites and quit options' column that is pushing the menu to be taller than what the categories need, resulting in the extra space below the categories. Among other things, I want to 'fix' that extra space issue. It's a space that doesn't negatively affect the menu when on the top panel, but that I feel negatively affects it when on the bottom panel.

The weird thing, and I apologize if there's already an open issue for this, is that when you disable 'Show favorites and quit options', that now hidden column still pushes the menu to be taller than the categories column needs, keeping that empty space under the categories. So that part of it is a simple fix (conceptually. idk how simple it is in the code).  [The current work-around is to unfavorite the favorites before hiding them. The end user won't realize that, rather, they will think there is some 'minimum menu height' causing the extra height.]

In the case where the user keeps the favorites shown, then even after that simple fix was done, there will be extra space under the categories if the favorites are taller than the categories. So what I now propose is that the categories be 'vertically panel aligned', such that when the menu is on the top panel the categories would be as they are now, but when the menu is on the bottom panel, the categories would sink as if by gravity to the bottom of the menu, putting the empty space above the categories instead of below them.

With images, let me show you **two versions** of my updated ideas then. One version moves the quit,login,lock buttons, so they will still appear even when the user hides the favorites, and the other version keeps them in the favorites column but flips the order when on the bottom panel so that the quit button is always furthest away from the LM menu button regardless of if the menu is on the top or bottom panel.

(And never mind what I previously said about the height of the right app menu item column, its height would continue to be governed however it is currently.)

**Version with quit buttons moved:**
All the images in this version show the new quit,logout,lock buttons location.

The below image shows:
- favorites are bottom aligned because menu is on bottom panel
- extra empty favorite area box extends to the top of the menu, the height of menu is dictated by the categories since they are taller here
![bottom quit moved cat taller than favs](https://cloud.githubusercontent.com/assets/25500496/22616232/55aa4caa-ea77-11e6-933b-1d7a8aa34d12.png)

The below image shows:
- the favorites are taller than the categories here. Favs will push the height until the max height and then the fav icons will start shrinking to fit in the max height.
- Menu items are bottom aligned because menu is on bottom panel
![bottom quit moved fav taller than cats](https://cloud.githubusercontent.com/assets/25500496/22616234/55afb898-ea77-11e6-8363-e72fb0a3d0ad.png)

The below image shows:
- favorites are hidden
- bottom aligned menu items since menu is on bottom panel
![bottom quit moved hidden favs](https://cloud.githubusercontent.com/assets/25500496/22616233/55af2d06-ea77-11e6-966a-8ea80a24ec6f.png)

The below image shows:
- here the categories are taller than the favorites. Favorites are top aligned because menu is on top panel
![top quit moved cat taller than favs](https://cloud.githubusercontent.com/assets/25500496/22616235/55b34c74-ea77-11e6-9772-2a4797f72bff.png)

The below image shows:
- favorites are hidden. Note quit buttons are still accessible in new spot.
![top quit moved favs hidden](https://cloud.githubusercontent.com/assets/25500496/22616237/55b68a42-ea77-11e6-871c-564479f36d0a.png)

The below image shows:
- favorites are taller than categories here
- menu items are top aligned because menu is on top panel
- top menu looks almost the same as currently, just with quit buttons moved to new spot.
![top quit moved favs taller than cats](https://cloud.githubusercontent.com/assets/25500496/22616236/55b45768-ea77-11e6-8a33-1c9bd50e635a.png)


**Other version, with quit buttons still in the favorites column:**

The below image shows:
- bottom aligned menu items because menu is on bottom panel
- favorites and quit buttons location are swapped because menu is on bottom panel
- quit buttons stay top aligned, favorites buttons stay bottom aligned with gap between them if there are hardly any favorites.
- here the categories column is taller than favorites column and so is dictating the height of the menu
![bottom quit not moved cats taller than favs](https://cloud.githubusercontent.com/assets/25500496/22616241/61a4b52c-ea77-11e6-9a1e-e676a321a7cd.png)

The below image shows:
- here the favorites column is taller than the categories and is dictating the height of the menu (if lots more favorites were added, then just how it works currently, the menu would only get a bit taller before the favorite icons began to shrink to fit)
- menu items are bottom aligned because menu is on bottom panel
![bottom quit not moved fav taller than cats](https://cloud.githubusercontent.com/assets/25500496/22616238/61a284fa-ea77-11e6-8bd2-940c327cfd9a.png)

The below image shows:
- favorites are hidden
- menu items are bottom aligned because menu is on bottom panel
![bottom quit not moved hidden favs](https://cloud.githubusercontent.com/assets/25500496/22616242/61a5924e-ea77-11e6-9053-e248b9e1624a.png)

The below image shows:
- quit buttons are bottom aligned, and favorites are top aligned, because menu is on top panel
- menu height is dictated by categories height since it is taller here, and quit buttons stay aligned to the bottom of the full height of the menu.
- menu items are top aligned because menu is on top panel
![top quit not moved cats taller than favs](https://cloud.githubusercontent.com/assets/25500496/22616240/61a4cd82-ea77-11e6-8d79-ff62ad3c45a1.png)

The below image shows:
- after these changes, top menu still looks the same in this case
![top quit not moved favs taller than cats](https://cloud.githubusercontent.com/assets/25500496/22616239/61a4c53a-ea77-11e6-8417-6709013d7d3b.png)

**Comment by xenopeek** [comment]
I can't say any of the alternatives jump out to me as visually more pleasing. Would perhaps the simpler alternative be to merge the lock / logout / shutdown buttons into one button. I think there is a feature request for that though I can't find it right now.

**Comment by JosephMcc** [comment]
It's actually in the roadmap to adapt this type of layout: https://raw.githubusercontent.com/The-Panacea-Projects/Gnomenu/master/Screenshot.png

**Comment by cruftytheclown** [comment]
> I can't say any of the alternatives jump out to me as visually more pleasing

None of them are intended to be visually more pleasing. They are intended to be more functional and to improve the mechanics of the user interaction with them when on the bottom panel. Imo, nobody would design the menu the way it is now if they had designed it for the bottom left corner.

> It's actually in the roadmap to adapt this type of layout: https://raw.githubusercontent.com/The-Panacea-Projects/Gnomenu/master/Screenshot.png

Interesting. Well, what I want to communicate is that I think what would be very cool and perhaps unique for Cinnamon, is if the placement of the elements on that menu was done in relation to the relative location of the menu button. You can see just a bit of what I mean in my images above.

So for that gnome screenshot, what I mean is, "Recent" is closest to the menu button. The power button is far away from the menu button. So you would have a dynamic menu which could appear in 8 different ways (top left, top right, right top, right bottom, bottom right, bottom left, left bottom, left top - and if it's in between then whichever is closest). It wouldn't come off as 8 different menus, it would feel like the menu feels the same no matter where it is, with the mouse moving distances from the menu button to the menu elements always being similar.
If the best spot for "Recent" is closest to the menu button, then that should always be true no matter where the menu is on the panels.

That way, not only _could_ you place the menu anywhere around the edges of the screen, but it would actually be dynamically optimized for all those spots.

**Comment by SamuelMiller** [comment]
Thanks cruftytheclown for posting such a detailed feature request. I strongly support your suggestions. The main reason why I don't currently use Cinnamon, and instead default to Mate or XFCE, is because of the layout of its start menu (e.g., the placement and limited space of favorites).

**Comment by bittner** [comment]
I fully support @cruftytheclown's idea of placing favorites (including "power off" actions) at the bottom of the menu. As far as I can tell this is also on [some roadmap](https://raw.githubusercontent.com/The-Panacea-Projects/Gnomenu/master/Screenshot.png), as mentioned by @JosephMcc.

In addition, I would like to suggest to get rid of the 3 options (favorites) "Quit", "Logout" and "Lock screen" and replace them by a single option "Quit" that pops up a dialog having "Shutdown", "Restart", "Suspend", "Logout" and "Switch User" available. Or simply pop up the ["Power Button" menu](https://github.com/linuxmint/cinnamon-session/issues/92) of cinnamon-session.

3 Options Difficult to Choose From
-----------

Let me explain the issue: I've seen that the 3 options constitute a (tremendous) usability hurdle and (constant) irritation for new users. I've noticed this myself, and I've seen this with my wife and my kids -- the 3 different options, having scary icons, make it difficult to make the right, safe choice.

Can anyone share which file needs to be modified to remove those items, and replace them by a single one that pops up, say, the session "power button" menu?

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.

**Comment by sergioad** [comment]
I personally would love to see something like the Brisk menu with a Cinnamon spin
