### ISSUE TITLE
Toggle between worspaces with a keyboard shortcut

### ISSUE THREAD

**Issue by jlnknz** [linuxmint/Cinnamon#6240]
**Feature request**
Add a keyboard shortcut possibility for switching from current workspace to the last visited one. If the user hits this shortcut again, he will come back to the first workspace (i.e. this is not a full history, it just remembers the last visited workspace)

He could then toggle from workspace 7 to 14 and 14 ot 7 with a single keyboard shortcut, say CTRL-ALT-ENTER for example.

What do you think? Worth it?

(I had a look at the code to see if this feature does not already exist. Sorry if I missed it)

**Use case**
User has 16 workspaces. His email client is on workspace 7 and his IDE on workspace 14. He clicks workspace 7 to check something in an email, he then must go back to workspace 14 to correct his code.

He could use the "Switch to workspace 7" and "Switch to workspace 14" keybord shortcuts, but he still needs to remember the number of the workspaces (7 and 14).

**Implementation**
From what I have (quickly) see, it would be enough to alter the 2 following files for implementinig this feature:
- files/usr/share/cinnamon/cinnamon-settings/modules/cs_keyboard.py
- js/ui/windowManager.js

Correct? I can give it a try if that's ok (although this is the first I would have been playing with Cinnamon's code)

**Comment by JosephMcc** [comment]
https://github.com/linuxmint/Cinnamon/issues/5114 is asking for similar functionality if you could just add your info to that one.
