### ISSUE TITLE
option to hide app description area in main Cinnamon menu

### ISSUE THREAD

**Issue by cruftytheclown** [linuxmint/cinnamon#6241]
suggestion: add an option to the main Cinnamon menu options to hide the app description area (at the bottom of the menu where it shows the name of the the app you are hovering over in the menu, and the description of the app)

Selecting this new hide option would collapse the wide short rectangle area where the name and description are displayed; it would not just hide the text and keep that area blank.

Reason: at least eventually, some users know what the programs are, they don't need or look at this description display so it just becomes visual noise and wasted space for some users. It would be nice to have the option to hide it.

**Comment by xenopeek** [comment]
I don't agree this option is needed but you can easily remove it yourself. Cinnamon applets, like the menu, are just JavaScript files and can easily be modified. For your suggestion you need to edit the file `/usr/share/cinnamon/applets/menu@cinnamon.org/applet.js` as root (for example with the command `gksudo xed /usr/share/cinnamon/applets/menu@cinnamon.org/applet.js`) and find for the line `section.actor.add_actor(this.selectedAppBox);` in that file and comment it out (prefix the line with two forward slashes `//`). After saving the file and restarting Cinnamon your menu no longer shows name or description of the highlighted menu entry.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
