### ISSUE TITLE
enable adding places to favorites in menu

### ISSUE THREAD

**Issue by cruftytheclown** [linuxmint/cinnamon#6242]
When you right click on most items in the main Cinnamon menu it lets you add to panel or add to desktop. But there is no right click for the Places (Downloads, Documents, etc) for you to add those to the favorites.

Not sure if it is a bug or a missing feature. If it is a missing feature, I'm suggesting it.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
