### ISSUE TITLE
Sound applet should not show Launch player when Control Players off

### ISSUE THREAD

**Issue by cruftytheclown** [linuxmint/Cinnamon#6243]
When you turn off "Control Players" in the Sound applet config, the Sound applet should no longer show "Launch player > "  but it does.

(Or, if you disagree with that, then I am suggesting a new option to hide "Launch player >" in the Sound applet.)

**Comment by xenopeek** [comment]
I don't think the two settings should necessarily be connected (why can't I launch a music player from the sound menu if I don't want to control it from there) and I'm unsure as to how many users would want this label removed from their sound menu anyway. But again, it can be done by a quick edit (turning it into an option that can be toggled will be more work; an exercise for the reader).

Edit the file `/usr/share/cinnamon/applets/sound@cinnamon.org/applet.js` as root (for example with the command `gksudo xed /usr/share/cinnamon/applets/sound@cinnamon.org/applet.js`) and find the following 4 lines of code and comment them out (prefix each line with two forward slashes `//`). After saving the file and restarting Cinnamon your sound menu no longer shows the Launch player option.

```
       // The launch player list
        this._launchPlayerItem = new PopupMenu.PopupSubMenuMenuItem(_("Launch player"));
        this.menu.addMenuItem(this._launchPlayerItem);
        this._updateLaunchPlayer();

        //between these two separators will be the player MenuSection (position 3)
        this.menu.addMenuItem(new PopupMenu.PopupSeparatorMenuItem);
```

**Comment by cruftytheclown** [comment]
The two settings do _appear_ intrinsically connected, and the persistence of the "Launch Player >" menu item when you turn off Control Players _appears_ to be an oversight (why would I want to launch a music player from the sound menu if I have chosen not to control it from there).  This can be observed: with Control Players enabled, when you launch a player the Launch Player item disappears and is replaced by the player control area.  When you hit x to quit player, the player control area disappears and is replaced by the Launch Players menu item.

If they were not connected, you would expect the Launch Players item to remain. If it's just a launcher why can't I use it to launch a 2nd player app.

So the Launch Players item appears to be part of the Control Players feature, hence why I posted the issue.
