### ISSUE TITLE
touchpad: continue moving cursor when near edge when selecting

### ISSUE THREAD

**Issue by cruftytheclown** [linuxmint/cinnamon#6244]
When you are drawing a selection box with the touchpad, when your finger reaches the edge of the touchpad you can't make the selection box any bigger. It should slowly continue to move the mouse cursor when you are near the edge so you can make the box bigger.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
