### ISSUE TITLE
Theme category titles seem clickable in Themes window

### ISSUE THREAD

**Issue by cruftytheclown** [linuxmint/Cinnamon#6246]
The Themes window lists 5 categories of themes (Window borders, Icons, etc), and when you hover the mouse over them they highlight. But when you click on them, nothing happens.
I clicked and double clicked on them and was fairly convinced that the Themes window just doesn't work. Then I figured out that you have to click on the preview pictures on the right side.

I think that either the title rows should not highlight when you mouse over them (so they won't seem like giant clickable buttons) Or clicking on them should open the sub window that shows the theme choices.

**Comment by JosephMcc** [comment]
That is the behavior throughout cinnamon settings and in most GtkListBoxes and isn't going to change. A themes can choose to override this if it wants.
