### ISSUE TITLE
Basic Themes settings to choose entire theme

### ISSUE THREAD

**Issue by cruftytheclown** [linuxmint/cinnamon#6247]
Currently you can choose each of the 5 areas of your theme, but I think it would be better if you could _also_ set your entire theme at once.

I would alter the Themes window by putting all 5 of the theme area preview images at the bottom in a single row. Then, above that I would add a new "basic" settings for themes which would set all 5 theme areas at once, bundled into overall theme combos. When you select one of these theme combos, all 5 preview images would change. (If you changed a single theme area below, then the "basic" combo choice would change to "new theme combo, unsaved".)

The basic theme combos choices would be like this:
Default
Dark
Light
User Saved no1
User Saved no2 (etc)
Funky Orange
Rainbow
etc...

For the theme areas of Window borders, Icons, Controls, Mouse Pointer, Desktop, the basic theme combos would be, for example:
Default = Mint-X, Mint-X, Mint-X, DMZ-White, Linux Mint
Dark = Mint-Y-Dark, Mint-X, Mint-Y-Dark, DMZ-White, Mint-Y-Dark
Light = Mint-X, Mint-X, Mint-X, DMZ-White, Mint-X
"My fave look" = (whatever 5 things the user chose and saved. They named and saved this combo.)
"coffee style" = (whatever 5 things the user chose and saved for this)
Funky Orange =  Aging Gorilla, Mint-X-Orange, Mint-X-Orange, DMZ-Black, Mint-X Orange
Rainbow = Metabox, Mint-X-Red, Mint-X-Blue, Adwaita, Mint-X-Purple
etc...

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
