### ISSUE TITLE
Segfault using ClutterGst in desklet 

### ISSUE THREAD

**Issue by Zac610** [linuxmint/cinnamon#6252]
I am developing some multimedia desklet [here](https://github.com/Zac610/CinnamonMediaDesklets/tree/master/AudioStream%40zac), waiting to be stable before submitting it into cinnamon-spices-desklets repository.

I am having problems if I use ClutterGst, as if my desklet calls `ClutterGst.init()`, it works, but Cinnamon crashes when i log-out, log-in, with the desklet active and I try to open any other window.

The error in the last line of /var/log/kern.log is: 
> Jan 29 18:22:10 lightning kernel: [   88.833615] cinnamon[1931]: segfault at 10 ip 00007fdd1d496d44 sp 00007ffc66bc4190 error 4 in libpthread-2.23.so[7fdd1d48d000+18000]

If I comment out the `init` call it works without any problems (but I cannot use ClutterGst functions).

Any suggestions on how to solve this?

**Comment by Vahan86** [comment]
@Zac610, is this still an issue for you in Cinnamon 4.2?

**Comment by Vahan86** [comment]
@icarter09, can we close this issue since there is no response from OP?
