### ISSUE TITLE
Some ways to close menu doesn't respect Animations Status

### ISSUE THREAD

**Issue by feren** [linuxmint/Cinnamon#6254]
If you turn off Animations in Menu Settings, and then open menu followed by clicking outside the menu, you'll notice the closing of the menu is animated whereas the trigger says it should do the opposite...

Related to this bug but also affects mainstream Cinnamon Menu: https://github.com/NikoKrause/CinnVIIStarkMenu/issues/20
Cinnamon Version: 3.2.7

**Comment by NikoKrause** [comment]
It also happens, when the Escape button is pressed.

**Comment by feren** [comment]
@JosephMcc Any chance of marking this as a bug?

**Comment by JosephMcc** [comment]
I can no longer reproduce this on git master.

**Comment by feren** [comment]
@JosephMcc Ok, which version will whatever fixed this be in the LM Repositories once it's released?
