### ISSUE TITLE
Do nothing on lid close results in suspend instead.

### ISSUE THREAD

**Issue by jonorthwash** [linuxmint/cinnamon#6255]
Refiling the issue https://github.com/linuxmint/cinnamon-control-center/issues/154 as directed.

These issues seem to be related: https://github.com/linuxmint/Cinnamon/issues/3327 and https://github.com/linuxmint/Cinnamon/issues/3054 .

In the control panel, when lid close action is set to do nothing, the machine suspends on lid close instead.  This was a problem for me for quite a while in previous versions (2.x?), but seemed to be fixed for the last year or so.  In a recent upgrade to Cinnamon 3.2.7, as part of a periodic dist-upgrade in debian unstable (which brought with it a new kernel and a number of other things), it appears to have reverted.

**Comment by Vahan86** [comment]
Can't reproduce this issue in Cinnamon 4.2. Works fine for me.
