### ISSUE TITLE
Cinnamon(?) - Sometimes all the windows are transparent, must restart Cinnamon

### ISSUE THREAD

**Issue by ab-oc** [linuxmint/Cinnamon#6258]
LM 18.1 64bit
Cinnamon 3.2.7

Sometimes, all the windows are displayed permanently transparent. The same transparent if you hover with your mouse the "show desktop". 
There is no other way to as to restart cinnamon...

For now, I didn't get an Idea how to reproduce that bug. Sometimes an afternoon is completely without this bug, and the other afternoon it's twice or more...

Regards

Andreas

**Comment by JosephMcc** [comment]
https://github.com/linuxmint/Cinnamon/issues/6234
