### ISSUE TITLE
[CPU] Constant workload on one thread

### ISSUE THREAD

**Issue by deekej** [linuxmint/Cinnamon#6259]
Hello guys,

I'm using Cinnamon 3.2.8, and recently I started to notice that `cinnamon --replace` process is constantly utilizing around 30% of CPU workload on one thread.

I'm running the Cinnamon in Fedora, under LightDM.

I tried to remove the applets that are marked as "highly CPU demanding" (using system calls) and restarting Cinnamon (and whole system later), but it was without any effect. I could still about 30% utilization of the CPU thread.

I will gladly provide any additional info you need, but you will have to direct me for that (tell me what do you actually need to solve this).

Best regards,

Dee'Kej

**Comment by leigh123linux** [comment]
Post

`~/.xsession-errors`

and the http link for

`upload-system-info`

**Comment by deekej** [comment]
I'm sorry for the noise. I've just found out the cause of this...

I'm using SpiderOakGroups, which runs somehow under cinnamon process. (It has its own cinnamon-like tray icon, etc.). Suddenly, SpiderOak started to backup a lot of files recently, which was causing cinnamon to have higher CPU usage and slow itself down.

When I launch it the SpiderOakGroups process via `dbus-launcher`, it spawns in its own process and cinnamon is running fine.

Maybe this will help anyone.
