### ISSUE TITLE
Panel disappears when using recordmydesktop

### ISSUE THREAD

**Issue by GM-Script-Writer-62850** [linuxmint/Cinnamon#626]
i was going to record a bug when i encountered this
using a ubuntu 12.04 on a  AMD A-3500 APU with the open source driver (it runs circles around fglrx)
anyway i installed recordmydesktop vie software center so i could record bug #624
i opened record my desktop hoping it would not have a tearing issues line it does on my 10.04 install with a nvidia driver
i clicked record and there went my panel
not know the keyboard shortcut to stop the recording i restarted lightdm via command line (ctrl+alt+t)

**Comment by benmccann** [comment]
This is happening on Linux Mint 17.2 as well. @mtwebster can you please reopen the bug so that folks can provide details?

**Comment by benmccann** [comment]
The `recordmydesktop --no-frame` option runs it just from the command line with no UI, so it works since it avoids creating any UI which is what's causing the problem.

**Comment by fchevitarese** [comment]
So the solution is to use without gui because there's no fix or ppl from cinnamon dont want to fix it ?

**Comment by pviotti** [comment]
This is still an issue on Cinnamon 2.8.6 (Ubuntu 15.10).
I confirm that [SimpleScreenRecorder](http://www.maartenbaert.be/simplescreenrecorder/) is a valid alternative to RecordMyDesktop.
