### ISSUE TITLE
Idea to help with creating a new custom category

### ISSUE THREAD

**Issue by TopView** [linuxmint/cinnamon#6260]
The genesis for this idea comes from this problem as described in this post and my recent solution there:  https://forums.linuxmint.com/viewtopic.php?t=233946

==> The specific idea I have for you is to **include a few tips when one goes to set a custom menu icon** to help the user get it right, as follows:

* Icon can be png or jpg (or ?) 
* must be owned by root, 
* must be located in the following subdirectories (tree):  ________ 
* Suggested size is:  (64 or 256 bits square?)

I'm not sure of all of the answers to these tips, but a start would to simply have a little dialog to read before selecting the icon file.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
