### ISSUE TITLE
New theme makes it difficult to read firefox input controls

### ISSUE THREAD

**Issue by libregeek** [linuxmint/Cinnamon#6262]
The new Cinnamon theme (which got updated by default) makes it difficult to read the input and select box controls in Mozilla Firefox. The location bar is also hardly readable. This issue occurred soon after the last Cinnamon upgrade. See the two screenshots from Fedora 25.

Cinnamon version details are as follows:
cinnamon-settings-daemon-3.2.1-1.fc25.x86_64
cinnamon-control-center-filesystem-3.2.1-1.fc25.x86_64
cinnamon-session-3.2.0-1.fc25.x86_64
cinnamon-translations-3.2.2-1.fc25.noarch
imsettings-cinnamon-1.7.2-1.fc25.x86_64
cinnamon-control-center-3.2.1-1.fc25.x86_64
cinnamon-desktop-3.2.4-1.fc25.x86_64
cinnamon-menus-3.2.0-1.fc25.x86_64
cinnamon-screensaver-3.2.13-2.fc25.x86_64
cinnamon-3.2.8-11.fc25.x86_64

![selection_525](https://cloud.githubusercontent.com/assets/145110/22827619/d3d9eb7a-efbe-11e6-9b52-3692bdfa9f4a.png)
![selection_524](https://cloud.githubusercontent.com/assets/145110/22827620/d3da23c4-efbe-11e6-9431-12a6f48146a5.png)

**Comment by leigh123linux** [comment]
This isn't set by linuxmint. We changed the default theme in fedora cinnamon.
You need to file the issue against fedora firefox at redhat bugzilla as it is the package at fault.

**Comment by leigh123linux** [comment]
@besser82 ^^

**Comment by JosephMcc** [comment]
I was just discussing this besser82 the other day. Dark themes do not play nice in many situations. Browsers are always an issue, like shown above. Qt apps that pull theming from the gtk2 theme can also have these issues. You will run into them sometimes in places like VLC dialogs.
