### ISSUE TITLE
When using ZSH as the main shell, environmental variables from .zshenv are not used

### ISSUE THREAD

**Issue by marmistrz** [linuxmint/Cinnamon#6263]
In particular, I learn Rust and in my `.zshenv` I add `~/.cargo/bin` to my `PATH`. The Rust plugin for VSCode uses some of the apps from there. 

Unfortunately, apps launched via alt+f2 or the menu do not take this configuration into account.

For reference: https://github.com/KalitaAlexey/vscode-rust/issues/59

**Comment by leigh123linux** [comment]
I don't see how  your rust issue is caused by cinnamon package

**Comment by marmistrz** [comment]
The Rust issue is just an example. The problem is that I set my environmental variables just as I should in my shell of choice. But when I invoke programs through Cinnamon, these settings are ignored. If I launch programs directly through the shell, then the programs get the correct environment.

**Comment by leigh123linux** [comment]
Did you use chsh to set the login shell?

**Comment by marmistrz** [comment]
Yes

**Comment by JosephMcc** [comment]
https://github.com/linuxmint/Cinnamon/issues/6070
