### ISSUE TITLE
Screen inverts on start up (~10-20% of time) on  18.1

### ISSUE THREAD

**Issue by WCSPNG** [linuxmint/Cinnamon#6264]
I've recently installed 18.1. About 10-20% of time screen will appear inverted on start up. I can correct the issue for the session by using "xrandr --output eDP1 --rotate normal" but the issue persists.

**Comment by JosephMcc** [comment]
Did you try turning on "Disable automatic screen rotation" in Cinnamon settings->General?

**Comment by WCSPNG** [comment]
Thanks for the tip Joseph. I've disabled it now. I'll see if it makes the difference. Cheers.

**Comment by JosephMcc** [comment]
Any follow up on this? I'd like to close it if your issue is solved.

**Comment by WCSPNG** [comment]
Hi JosephMcc. It's been a week now and no re-occurrence of the issue, That must have been the issue. Thanks very much!
