### ISSUE TITLE
While deleting items from the cinnamon app launcher menu editor, cinnamon crashes frequently.

### ISSUE THREAD

**Issue by cjonesweb** [linuxmint/Cinnamon#6268]
I installed Simon Tatham's portable puzzle collection via Synaptic package manager. It dumped launchers for all the puzzles in the 'Games' folder. I like to categorize my apps, so I made a new sub-folder called 'Portable Puzzles' and began the tedious process of copying and pasting the launchers into the new folder. I then had to delete the items from the original folder. Interestingly,  and this may be a separate issue, pasting the items into the new folder caused a dupe to be created in the parent folder. While deleting the launcher items and their dupes, Cinnamon crashes repeatedly and has to be restarted.

**Comment by clefebvre** [comment]
We believe this issue is fixed. Please test against the latest Cinnamon version (3.6). If the issue happens again, create a new issue and add a stack trace.
