### ISSUE TITLE
Consider patching /etc/pulse/daemon.conf to `flat-volumes = no`

### ISSUE THREAD

**Issue by dg1727** [linuxmint/Cinnamon#6269]
This issue is similar to #5123.  My issue was fixed by editing `flat-volumes` to `no` (and removing the semicolon that comments out that line by default :-) in /etc/pulse/daemon.conf, whereas the reporter of issue #5123 tried that and it didn't work, so I opened a different issue.  

My problem was that changing the volume in VLC's UI changed the computer's master volume & vice versa.  I found this very annoying.  Also, sometimes the VLC volume & Linux master volume would get out of sync with each other, meaning non-repeatable behavior, which was even more annoying.  

https://wiki.archlinux.org/index.php/PulseAudio says that Arch Linux has patched the config option from `yes` to `no`, and they give a use case where the patch is even more important than it was for me.  I suggest that Linux Mint make the same patch.  

LMDE2 Cinnamon 64-bit, `pulseaudio` APT package version 7.1-2~bpo8+1
The same problem happened when I was using the non-backports package version that's the default for this distro.

**Comment by leigh123linux** [comment]
Linuxmint doesn't package pulseaudio, if you want this change you will need to request it at ubuntu bug tracker.

**Comment by dg1727** [comment]
Fixed in Ubuntu 15.04 Vivid in package version 1:6.0-0ubuntu4
https://bugs.launchpad.net/ubuntu/+source/pulseaudio/+bug/1424195

Debian bug is open https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=541538
