### ISSUE TITLE
Modifier key to invert the sense of "Edge resistance with other windows"

### ISSUE THREAD

**Issue by dg1727** [linuxmint/Cinnamon#6272]
In "System Settings" > Windows > Behavior tab, the bottom option is "Edge resistance with other windows" [ON/OFF].  

Suggestion:  Add a modifier key (Shift, Ctrl, whatever) which, while a window is being moved, inverts the sense of that "Edge resistance" option.  

I assume you'll want a line-item there like "Modifier to invert whether edge resistance is enabled", similar to the "Modifier" setting in the Window Tiling window.  I imagine that an inapt choice of "Edge resistance" modifier could conflict with the Window Tiling modifier.  (I tried the Window Tiling options briefly and I still have them enabled, but I'm not a big fan of them and not familiar with them.)  

I'd like edge resistance to be **available** all the time, but there is only a minority of times when I want to **use** it.  A modifier key would be much more convenient than having to open a System Settings window to switch edge resistance on or off.  

Cinnamon 3.2.7

**Comment by JosephMcc** [comment]
Thank you for your suggestion. See https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html for information on how we handle feature requests.
