### ISSUE TITLE
When switching workspaces, OSD & sound aren't consistent - applet vs. keyboard shortcut

### ISSUE THREAD

**Issue by dg1727** [linuxmint/Cinnamon#6273]
In "System Settings" there are a couple of settings about workspace switching:  
- Workspaces > OSD tab 
- Sound > Sound Effects tab > Effects section > "Switching workspace" 

These are honored when the user switches between workspaces by clicking in the workspace-switcher applet in the Panel.  But when a keyboard shortcut is used to switch workspaces, the OSD isn't shown & the sound isn't played.  

I think a better UI would be to have the OSD and the switching sound be according to "System Settings," regardless whether the graphical applet or a key combination was used.  

Cinnamon 3.2.7

**Comment by JosephMcc** [comment]
It works fine here regardless of the method I use.

**Comment by dg1727** [comment]
Yes, the OSD & sound work for me if I use e.g. Ctrl-Alt-Right & Ctrl-Alt-Left to switch sequentially between workspaces.  

But if I use e.g. Ctrl-NumPad3 to jump directly to a workspace, then the OSD isn't shown & the sound isn't played.

**Comment by JosephMcc** [comment]
Ok. I can reproduce that.

**Comment by JosephMcc** [comment]
This should have been fixed by https://github.com/linuxmint/Cinnamon/commit/869eb468497fd734b8e47c94ddd5706528fcfeba
