### ISSUE TITLE
Workspace switcher:  Different background color for workspaces that have no apps

### ISSUE THREAD

**Issue by dg1727** [linuxmint/Cinnamon#6274]
Feature request:  The workspace-switching applet (in the Panel) should show a different background color on workspaces that have no visible windows AND no minimized windows.  This would be helpful when a user is about to log out & wants to check for applications that are still running.  

Cinnamon 3.2.7

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.

**Comment by NikoKrause** [comment]
You can use the following shortcut to check for running applications on workspaces, before logging out:

![](http://gateway.ctsltd.net/imglib/keyboard_ctrl_alt_up.jpg)
