### ISSUE TITLE
Cinnamon defaults to 1080i instead of 1080p

### ISSUE THREAD

**Issue by geeMc** [linuxmint/cinnamon#6277]
When starting Cinnamon (be it through a random login manager or directly), the screen resolution always defaults to 1080i instead of 1080p on a 4K Sony Bravia television (KD-55XD8599). XFCE4 defaults to 1080p, so the problem doesn't seem related to Xorg. 

System:
Intel Core i5-4590 (Intel HD 4600) with xf86-video-intel
Arch Linux (4.9.7-1-ARCH) (tried with different kernels though)
Cinnamon 3.2.8, Xorg 1.19
Resolutions up to 4096x2160p24 and 3840x2160p30 work (tested)

I can manually change to 1080p with xrandr, but ofcourse that's not persistent.
 I've attached my Xorg config file and the xrandr output, although I don't see anything wrong with them.

I've attached a textfile with the latest output of my Xorg.0.log, the output of xrandr and the contents of my xorg.conf file. There are no further files in /etc/X11/xorg.conf.d.
[info.txt](https://github.com/linuxmint/Cinnamon/files/772608/info.txt)

Edit: 
I have put the `    Option	   "ModeValidation"	"AllowNonEdidModes"` directive in my xorg.conf for testing. It doesn't make any difference.

If you need any more information, please let me know.

**Comment by Fathardie** [comment]
Having the same issue. Another report: https://bugs.launchpad.net/linuxmint/+bug/1596388

**Comment by Vahan86** [comment]
@geeMc, is this still an issue for you with Cinnamon 4.4?

**Comment by Vahan86** [comment]
@icarter09, can we close this issue since there is no response from OP?

**Comment by Vahan86** [comment]
@icarter09, can we close this issue since there is no response from OP?

**Comment by Vahan86** [comment]
@icarter09, can we close this issue since there is no response from OP?
