### ISSUE TITLE
Maybe someday a 2D layout for the Applications menu

### ISSUE THREAD

**Issue by dg1727** [linuxmint/Cinnamon#6279]
Calm down, I've read #3729

- I'm not suggesting exactly the same thing as in that issue.  
- I don't expect this to be implemented soon - #6239 is still in progress, for instance.  
- I'm going to make a forum thread referencing this issue, due to the tentative nature of any discussions about this.  I thought that, if this idea is ever on the verge of being implemented, it will be less work for those discussing it if the existing threads are easier to find.  

My idea is to have an option to show the application icons as a 2D list of icons & names.  The list would scroll (in one dimension) like the existing 1D list does, rather than having pages as shown at the beginning of #3729.  This would address the start of https://github.com/linuxmint/Cinnamon/issues/3729#issuecomment-65895022 "as we add new applications, it creates more and more pages."

As for the later statement in that same comment, "our brain is faster in identify items displaced in a sequential list arrangement as opposed to in a 2d grid:"  
- Once someone gets used to what is in a given category, I think that person can find a given item faster by remembering approximately where it is in 2D than by having to scroll sequentially through a 1D list.  A user could start with the list in 1D when they install Cinnamon, then switch to 2D when they want faster access to apps-menu items.  
- I have noticed that many users, especially nontechnical ones, put shortcuts to {documents & applications} all over their computer's desktop (a 2D arrangement) even though their DE has a way to put the same shortcuts into a 1D menu.  
- I think "just a quick glimpse to have a good idea of all the applications within a given category" would still be true of a 2D arrangement; even more so when the 2D list has more icons than a 1D list does.  
- "I'm pretty sure most users use mouse. And the Cinnamon menu is great for navigation using mouse" - The mouse is well suited to 2D navigation.  Also, a text-driven search feature (https://github.com/linuxmint/Cinnamon/issues/3729#issuecomment-65872804) often requires the user to take his/her hand off the mouse (or use the non-mouse hand, which may be doing something else), and sometimes that's inconvenient.  

The approach of adding a 2D option without changing anything else about the current UI (including when the 2D option is in use - hover autoscroll, logout button, favorites, etc.) would, I believe, address almost all of the items in Garibaldo's other comment https://github.com/linuxmint/Cinnamon/issues/3729#issuecomment-65884936 and JosephMcc's comment https://github.com/linuxmint/Cinnamon/issues/3729#issuecomment-65887765

I do suggest an **option** for bigger icons (not necessarily huge ones) for users who have the screen space.  And users may want to be able to resize the 2D view (number of icons in width & height) interactively.  

Like several of those who commented on #3729, I don't want the Windows 8.1 look.

**Comment by JosephMcc** [comment]
There is already a "Main Cinnamon menu suggestions" issue. You linked to it. I don't think we need another one opened. You could just post this in that one.
