### ISSUE TITLE
VirtualScreen: Virtualbox in Fullscreen Goes to Top On ScreenChange

### ISSUE THREAD

**Issue by H8to** [linuxmint/cinnamon#6281]
### cinnamon --version
Cinnamon 3.2.8

### My hotkeys
`CTRL + ALT + ArrowKey`: Switch between the virtual screens

### Bug Description
On VirtualScreen1 Virtualbox is open with FullscreenMode enabled
On VirtualScreen2 anything can be opened

### Expected
When I `ALT + TAB` to another application on VirtualScreen1 e.g. to Firefox and switch the VirtualScreen forth and back Firefox should be the application on top of VirtualScreen1.

### The bug
Virtualscreen1 instead will push Virtualbox's Fullscreen to the top and show this instead of Firefox after switching to Virtualscreen2 and back to Virtualscreen1.

Let me know if this issue is not stated precisely enough. :) 

Any way to fix this? :1st_place_medal:

**Comment by H8to** [comment]
Is it legitimate to ask for an update on this bug? 

Any idea where to look for the bug and fix it myself?

Thanks in advance :smile:

**Comment by Vahan86** [comment]
@H8to, is this still an issue in Cinnamon 4.2?

**Comment by H8to** [comment]
@Vahan86 Sorry, switched to i3 about a year ago 😅

**Comment by icarter09** [comment]
@H8to no worries and thanks for the update.
