### ISSUE TITLE
In Panel, submenus of right-click menus should open on hover

### ISSUE THREAD

**Issue by dg1727** [linuxmint/Cinnamon#6284]
(...or should at least have an option to do so)

This issue is relevant to all desktop themes that ship with Cinnamon 3.2.7 in LMDE2 (those themes are "cinnamon", "Linux Mint," and the Mint-X color variations).  I suppose spices (3rd-party themes) could change how the submenus open, but I think a lot of users will just use one of the included themes.  

Right-clicking a button in the window-list applet produces a pop-up menu with options like Preferences (which is a submenu), Restore, etc.  The issue is that the submenus open only on click, not on hover.  This seems to affect all Panel applets that have right-click menus with submenus (Launchers & the sound indicator, for instance).  

Most pop-up menus elsewhere have their submenus open on hover.  This includes the "Move to Another Workspace" submenu of the Cinnamon window manager's window-operations menu (sometimes found at the upper-left corner of windows).  

Users have commented [ http://github.com/linuxmint/Cinnamon/issues/3729#issuecomment-65884936 and #1465] that they really like the autoscroll feature of the desktop's main apps menu.  I think having "submenus of right-click menu open on hover" would be the same idea.

**Comment by JosephMcc** [comment]
Themes cannot control this. I don't see this happening either. They don't work the same as a Gtk menu and the behavior doesn't need to be the same. I don't want these randomly sliding open and closed and moving the other menu items around while I move my mouse inside the menu.
