### ISSUE TITLE
Window-list applet:  Option to put new buttons near existing instances of same app

### ISSUE THREAD

**Issue by dg1727** [linuxmint/Cinnamon#6285]
It would be nice if the window-list applet (in the Panel) had an option so that any new button defaults to being placed just to the right (or the left, per user preference) of the rightmost (leftmost) existing button that was opened by the same executable.  

This wouldn't involve adding any pop-up menus to the window-list buttons.  The software is already capable of reordering window-list buttons, since drag-and-drop is allowed.  So I assume the suggested enhancement would be feasible.  

Cinnamon 3.2.7

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
