### ISSUE TITLE
System Settings:  Window-titlebar settings change should be reflected immediately

### ISSUE THREAD

**Issue by dg1727** [linuxmint/cinnamon#6286]
In System Settings, Themes sub-app, selecting a Controls theme changes the color of window titlebars, but (unlike "Window borders" themes selected in this same window) this isn't reflected in the window titlebars themselves (of other windows) until a reboot.  

The change is also not reflected in the "Window borders" thumbnails (in the same window & in its graphical pop-up menu), even after a reboot.  

Cinnamon 3.2.7

**Comment by JosephMcc** [comment]
> In System Settings, Themes sub-app, selecting a Controls theme changes the color of window titlebars, but (unlike "Window borders" themes selected in this same window) this isn't reflected in the window titlebars themselves (of other windows) until a reboot.

This has always been a bit spotty and is controlled by muffin. It doesn't require a reboot when it doesn't take effect. Just a log in/out or a cinnamon restart.

> The change is also not reflected in the "Window borders" thumbnails (in the same window & in its graphical pop-up menu), even after a reboot.

Not going to happen. Thats just an image being shown there. It uses whatever the theme supplies.

**Comment by icarter09** [comment]
We believe this issue is fixed. Please test against the latest Cinnamon version (4.2). 

If the issue happens again, create a new issue and add the output of "cinnamon-settings sound".
