### ISSUE TITLE
Selection rectangle on desktop can be hard to see

### ISSUE THREAD

**Issue by dg1727** [linuxmint/Cinnamon#6287]
... for instance, with the default light-green color theme & the light-green areas of the Lilac backdrop.  

Maybe in the future the selection rectangle can be drawn so that it contrasts (moderately) with the backdrop no matter what the backdrop looks like.  

I know that there is other graphical feedback of a mouse-drag on the backdrop (namely, what icons get selected).  

Cinnamon 3.2.7

**Comment by dg1727** [comment]
Controls theme is Mint-X; backdrop is from the Serena distro release.

**Comment by JosephMcc** [comment]
This has nothing to do with Cinnamon. It's controlled by Nemo, which draws the desktop window, and your gtk theme.
