### ISSUE TITLE
OpenVPN can restart only with 'service openvpn --full-restart' after disconnection

### ISSUE THREAD

**Issue by ACinnamonUserInUK** [linuxmint/Cinnamon#6288]
**The scenario**

I use OpenVPN on my computer (not router) to use a virtual private network (VPN). I use that VPN on a Windows computer without incident (though not via OpenVPN). On Mint, the VPN connects at boot and all works, until I change network or the computer suspends, i.e. until the present network connection is disrupted. Once it is disrupted, it seems that only 'sudo service openvpn' --full-restart (or perhaps the systemd equivalent, if I understand correctly . . ) will restore the connection.

**The problem**

Surely the reconnection should occur automatically.

Perhaps the problem is with my particular system. Or perhaps the fault lies with my VPN provider or with the OpenVPN software. I find the problem hard to diagnose exactly - partly because my system has many an if-up and if-down file, though I think the same would hold for a fresh install.

I would be happy to submit some relevant logs.

**Comment by leigh123linux** [comment]
File your issue against NetworkManger instead.
