### ISSUE TITLE
Will KWIN work for Cinnamon

### ISSUE THREAD

**Issue by nirajbhagchandani** [linuxmint/Cinnamon#6292]
Hello Cinnamon Team,
Greets!!

Well, compiz does not work in Cinnamon Desktop Environment as there might be some issues. So, I found alternative package for compiz ie. KWIN. 
So, if I want to install KWIN on Cinnamon, then can I run KWin Successfully on Cinnamon? 

I am using Linux Mint 18. (Cinnamon Desktop Environment)
Regards,
Niraj Bhagchandani.

**Comment by JosephMcc** [comment]
No.

**Comment by leigh123linux** [comment]
>  Well, compiz does not work in Cinnamon Desktop Environment as there might be some issues

Cinnamon uses muffin as compositing manager only, all other compositing programs are redundant!
