### ISSUE TITLE
Bug: intelligent panel hide + full screen movie on secondary display

### ISSUE THREAD

**Issue by brub2** [linuxmint/cinnamon#6293]
I use a script to launch Kodi full screen on my secondary display (which is below the primary in my setup, nvidia proprietary driver). Even if my primary desktop has no windows at all, the panel hides. In fact, the bug is not 100% reproductible but happens most of the time. I have the same trouble if I play (on the secondary display) a full screen movie with smplayer, but strangely it's ok with xplayer or a LibreOffice fullscreen window. Here is my kodi script if it helps. 

`#!/bin/bash

move_and_fullscreen(){
  NAME='Kodi'

  while [ -z "`wmctrl -l | grep \"$NAME\"`" ]
  do
      sleep 1
  done

  wmctrl -r "$NAME" -b remove,maximized_vert; wmctrl -r "$NAME" -b remove,maximized_horz

  wmctrl -r "$NAME" -b toggle,fullscreen
  wmctrl -r "$NAME" -b add,sticky
}

move_and_fullscreen &
AE_SINK=ALSA exec kodi`

**Comment by Vahan86** [comment]
@brub2, is this still an issue in Cinnamon 4.2?

**Comment by brub2** [comment]
It seems ok, but I don't have the same setup now (no nvidia and secondary monitor on the left or right side, not below).
