### ISSUE TITLE
Recent Documents Applet: Wrong Positioning Of Menu

### ISSUE THREAD

**Issue by gh9000** [linuxmint/Cinnamon#6295]
* Tested on Arch Linux (Cinnamon 3.2.8-1 - current version)

The current version of the **Recent Documents Applet** does not position the menu correctly when the applet icon is clicked.

**Expected Behavior:** The menu should appear directly below, above or beside the applet's icon, depending on where the user has his panel. No portion of the menu should be hidden by the panel.

**Actual Behavior:** The menu always appears in the upper-left corner of the display, regardless of panel position and location of the applet's icon. When the user's panel is positioned at the top of the display, the issue is compounded as the Recent Documents menu actually gets positioned under the panel, partially obscuring the list of items. Depending on the number of items in the menu and the width of the panel, the entire menu may be obscured.

The problem appears to be the 'container' hierarchy used in creating the menu drop-down.

I've attached a sample patch file showing the code that I've used to get things working:
[recent_applet_git_patch.zip](https://github.com/linuxmint/Cinnamon/files/784828/recent_applet_git_patch.zip)

**Comment by gh9000** [comment]
Tested and working.

Thank you for the quick response.

**Comment by JosephMcc** [comment]
Favorite kind of bug reports. The ones that contain a fix. Makes it easy :)
Thank you.
