### ISSUE TITLE
Bad UI on taskbar "Close All" context item can cause data loss

### ISSUE THREAD

**Issue by deutrino** [linuxmint/cinnamon#6297]
Right-clicking a window item in the taskbar pops up a context menu. "Close all" is an item.

**Problems**

1. Some people (including myself) may interpret this to mean "close all windows/instances of the selected program." I've made this mistake several times now and I've been a software engineer for over a decade, so it's probably safe to assume others are making it as well.
2. Once clicked, there is no confirm dialog _and_ no feedback to indicate that anything is happening. Cinnamon simply begins closing every open window immediately. If a system is memory-constrained, swapping in pages sufficient to close the windows can cause a delay where, without feedback, it seems that nothing is happening.

**Suggestions**

* Consider whether "close all" (meaning close _every_ open window) is appropriate or necessary as a context menu item on every individual window widget in the taskbar. The functionality of the button appplies to _all_ open windows - why is it a context item on widgets for individual windows? I can understand in the case of "close others" but not in the case of "close all" as currently implemented.
* Consider renaming "close all" so that its function is more apparent from the name.
* Consider replacing or changing "close all" with a function which closes all open windows of the program related to the selected window widget.
* Add a confirmation dialog in either case.

**Comment by icarter09** [comment]
@deutrino are you still experiencing this issue?

**Comment by deutrino** [comment]
I switched to Ubuntu and GNOME 3 last time I reinstalled my machine so I can't verify whether it's been fixed or not.
