### ISSUE TITLE
Multimedia keys (on keyboard) don't reset screensaver timeout

### ISSUE THREAD

**Issue by dg1727** [linuxmint/cinnamon#6300]
I'm using `xscreensaver` (APT package version 5.30-1+deb8u2); 
- neither `cinnamon-screensaver` 
- nor APT package `cinnamon-screensaver-x-plugin`.  

But I've done a Web search for whether this is a known issue with XScreenSaver, and I didn't find anything.  

I tested as follows, but the same thing would probably be found with a screensaver timeout of 1 minute:  
1.  Set screensaver timeout to 10 minutes.  
2.  At T = 0, move the mouse to reset the screensaver timeout.  
3.  At T = 5minutes, use the keyboard multimedia keys (e.g., decrease & increase volume).  In the case of the volume keys, Cinnamon displays an OSD [on-screen display] momentarily.  
4.  At T = 10minutes, the screensaver will activate, even though it wasn't supposed to until T = 15minutes.  I wonder if Cinnamon is consuming the keypresses so that the screensaver doesn't detect the keyboard activity at T = 5minutes?  

(XScreenSaver is configured [step 1 above] using the `xscreensaver-demo` command.)  

/usr/bin/cinnamon 3.2.7 on LMDE 2 "Betsy" Cinnamon 64-bit.

**Comment by icarter09** [comment]
@dg1727 are you still experiencing this issue?

**Comment by Vahan86** [comment]
@icarter09, can we close the issue since there is no response from OP?
