### ISSUE TITLE
Icons for the "Picture aspect" settings for background wallpaper

### ISSUE THREAD

**Issue by dg1727** [linuxmint/Cinnamon#6301]
Feature request:  (in existing file `cs_backgrounds.py`)

On the "System Settings" > Backgrounds > Settings tab, there is an option "Picture aspect."  Of the 7 values here, 5 aren't clearly distinguishable by name (Mosaic, Scaled, Stretched, Zoom, Spanned).  

If the user were to try to identify these by trial-and-error:  
a.  It adds time & complexity to the task of selecting a desktop background; 
b.  Some users will probably forget right away what the words mean; 
c.  The user might have to select wallpapers with certain kinds of aspect ratio and/or resolution (smaller/larger/taller/wider than the screen[s]) to understand the difference between the options, and the aspect-ratio requirements in turn may affect which image the user wants to use.  

So I suggest a graphical menu like the ones in the Themes sub-app (Themes tab).  Each item in this "Picture aspect" menu would be a static predefined picture, **not** a preview of the selected backdrop:  
- As noted in point (c) above, the selected backdrop might not show the difference between certain of the "Picture aspect" modes.  
- Generating a preview of the selected backdrop might be slow.  

My current /usr/bin/cinnamon version is 3.2.7

**Comment by dg1727** [comment]
The preview of the monitor sizes & locations should probably be generated from the user's desktop settings - otherwise the user wouldn't recognize it.  The sample wallpaper, though, could be a predefined bitmap of e.g. 64x64 pixels.

**Comment by JosephMcc** [comment]
I don't see the reason for adding this much complexity. Those options are fairly standard across all desktops.
