### ISSUE TITLE
Options to sort backdrop wallpaper gallery by size or aspect ratio

### ISSUE THREAD

**Issue by dg1727** [linuxmint/Cinnamon#6302]
Feature request:  (in existing file `cs_backgrounds.py`) 

On the "System Settings" > Backgrounds > Images tab, it would be nice to have options to sort the thumbnails so that, on each gallery page, the following kinds of backdrops are at the beginning, _and_ other backdrops are indicated obviously (e.g., their descriptive text is shaded differently):  
- Backdrops whose width & height are a whole-number multiple (can be 1:1) of the desktop size; 
- Backdrops whose width & height are a whole-number multiple or submultiple of the desktop size; 
- Backdrops that are the same aspect ratio as the desktop, even if not a whole-number multiple/submultiple of the desktop size.  

This might be done by adding, at the top of the window, a listbox like:  
###### Sort by Resolution:  
- No Sorting 
- Integer x Desktop Size
- Integer or 1/integer x Desktop Size
- Aspect Ratio = Desktop
- Aspect Ratio (tallest first) 
- Aspect Ratio (widest first) 

("x" is a multiplication symbol) 

"Aspect Ratio (--- first)" is different than the other options:  
- Insert a blank thumbnail (clearly labeled) that's the same aspect ratio as the user's desktop, and sort the gallery page's thumbnails (including that one) by aspect ratio.  
- Images at one end of the sorted list will have a taller aspect ratio than the desktop, and images at the other end of the list will have a wider aspect ratio than the desktop.  
- The aspect ratio of each image should be stated as a number so the user can tell what images are equivalent in aspect ratio.  
- These modes are helpful because sometimes a picture differs by one pixel in width or height from the desktop aspect ratio.  

My current /usr/bin/cinnamon version is 3.2.7

**Comment by JosephMcc** [comment]
I don't think there is any reason to make it this complicated. The whole idea when we did the new background setting was to try and keep it simple.
