### ISSUE TITLE
In panel edit window itself, state which panel is being edited

### ISSUE THREAD

**Issue by dg1727** [linuxmint/Cinnamon#6304]
In the "System Settings" Panel sub-app (existing file `cs_panel.py`):  

Currently, the panel that's being edited turns a different color (orange on my screen).  The user can edit a different panel by clicking "Previous panel" and "Next panel" buttons.  

The user might not notice which panel has turned a different color.  Also, there is no identification in the panel edit window itself as to which panel is being edited.  

Suggestion:  Add a thumbnail (possibly centered between the existing "Previous panel" and "Next panel" buttons) which shows the entire desktop.  The panel that's being edited would be highlighted in a high-contrast way; for example, the desktop background is neutral, panels not being edited are black, and the panel being edited is red.  The ratio of panel width to screen size would be exaggeratedly big in the thumbnail.  

At a minimum, it would be nice to have a text field in the edit window (maybe in the top middle as suggested above), with the monitor name & whether the panel being edited is @ top, bottom, left, or right.  

I'm using /usr/bin/cinnamon 3.2.7

**Comment by brownsr** [comment]
This has alerted me to a number of themes not having the panel highlighting working as intended.  I will get those corrected.

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
