### ISSUE TITLE
with touchscreen two finger tap not triggering context menu on empty desktop area

### ISSUE THREAD

**Issue by hubbyist** [linuxmint/Cinnamon#6305]
In chrome and some other applications two finger tapping on touchscreen is opening right context menu. But after clicking "show desktop" and tapping with two finger to any empty area nothing happens. But if I drag while holding my finger a selection rectangle forms. Also I couldn't find a way to trigger right click menu by using touch screen in nautilus as well. I am using an ASUS TP500L.

**Comment by leigh123linux** [comment]
Post some proper system info!!

**Comment by hubbyist** [comment]
Will do when I reach my computer later today. Sorry for the missing info.

**Comment by JosephMcc** [comment]
You never even gave basic info like OS or cinnamon version. The last can be obtained by running `cinnamon --version` in a terminal.
