### ISSUE TITLE
org.cinnamon.desktop.sound event-sounds always gets disabled

### ISSUE THREAD

**Issue by geckolinux** [linuxmint/Cinnamon#6306]
Hi, it appears that every time Cinnamon starts it sets dconf `org.cinnamon.desktop.sound event-sounds` to `false`, which prevents things like Empathy instant messenger notification sounds from working. I have verified that my notification volume in Cinnamon Sounds is at 100%.

**Comment by JosephMcc** [comment]
I can reproduce this on Mint with git master. A Cinnamon restart doesn't do it but a full restart of the machine does.

In the future bug reports that don't include basic info like distro and cinnamon version are going to be closed.

**Comment by geckolinux** [comment]
Sorry about that. Cinnamon 3.2.8 on openSUSE Tumbleweed.

**Comment by JosephMcc** [comment]
It's fine but we have far too many bug reports open here that just don't provide even basic information to go on. Cinnamon relies on enough upstream parts that troubleshooting can be a pain if you don't even know where to begin or in tracking down what might be responsible.

**Comment by JosephMcc** [comment]
I had the chance to look into this. That key is tied to our accessibility settings. If you open cinnamon settings->Accessibility and go to the Keyboard page you can turn on "Enable audio alerts". That setting will stay consistent across reboots.
