### ISSUE TITLE
Rename "Windows" control panel to e.g. "Window Manager"

### ISSUE THREAD

**Issue by dg1727** [linuxmint/Cinnamon#6307]
Suggestion:  Rename the "Windows" control panel (file `cs_windows.py`) to, for example, "Window Manager".  (The filename itself doesn't have to be changed - just the name in the GUI.)  

Using phrases like "Windows control panel" in discussions with non-technical people is just too likely to sound like a reference to a competing OS.  

Other Linux desktop environments use the term "Window Manager" for their equivalent applets.  Although "Window Manager" is somewhat of a Linux/Unix jargon term, at least it's well understood among many Linux users, and inexperienced users will very likely find out what it means once they've browsed Web forums a few times.  

(This control panel is accessible from Apps menu > Preferences > Windows and from Apps menu > Preferences > System Settings > Preferences section > Windows.)  

I'm using /usr/bin/cinnamon version 3.2.7.

**Comment by leigh123linux** [comment]
Get real!

> Using phrases like "Windows control panel" in discussions with non-technical people is just too likely to sound like a reference to a competing OS.
