### ISSUE TITLE
In Applications menu, add Eject right-click option for removable drives in Places

### ISSUE THREAD

**Issue by dg1727** [linuxmint/Cinnamon#6308]
In the Applications menu, Places section, right-clicking the icon of a removable drive should offer an option to Eject the drive.  

This would be more accessible than the "removable drives" indicator which can appear somewhere else in the Panel.  (I'm using mostly default settings of the "cinnamon" theme for my Panels, and currently the "removable drives" indicator icon is much smaller & less noticeable than the Places drive icons.)  

In case new users are wondering what this "Places" section is:  If I right-click the Applications menu applet in a Panel, the right-click menu has a Configure... option which opens a window called Menu.  On the "Menu" tab of this window, there's an option for "Show bookmarks and places" which, if enabled, puts a Places section (folder icon) in the Applications menu.  

I'm using Cinnamon 3.2.7

**Comment by NikoKrause** [comment]
I'm not sure the menu is the right place for that.
Also placing it in the rightclick menu isn't really obvious.
An eject icon on the button would be more visible, wouldn't it?

**Comment by JosephMcc** [comment]
This seems like overkill. It's already available in the Removable drives applet, the desktop, and the Nemo sidebar.
