### ISSUE TITLE
On ArchLinux: Cinnamon 3.2.8 + Nvidia 378.13 is dysfunctional

### ISSUE THREAD

**Issue by akhilsbehl** [linuxmint/Cinnamon#6311]
As soon as Cinnamon starts, it says, 'Cinnamon has crashed, you are in fallback mode, want to restart.' Restarting just goes back to the same dialog. How can I help debug?

**Comment by leigh123linux** [comment]
378.13 works fine with cinnamon as long as you install the driver correctly

https://paste.fedoraproject.org/paste/b5HQ4zp~aiIq-IMpIOpysl5M1UNdIGYhyRLivL9gydE=/raw

**Comment by akhilsbehl** [comment]
Umm... okay. Can you explain _installed it badly_? What can I do to make sure that it is installed correctly. All I know, I installed it using my distro's official package manager.

Closing it before any conversation is a little heavy handed, don't you think?

**Comment by leigh123linux** [comment]
@akhilsbehl Just because the nvidia package was supplied by the distro's official package manager doesn't mean it works.
I suggest you file a bug against Arch nvidia.

> Closing it before any conversation is a little heavy handed, don't you think?


Why the hell should we waste our time answering arch nvidia issues?
