### ISSUE TITLE
a white line appear in the right of the desktop

### ISSUE THREAD

**Issue by lancelock** [linuxmint/Cinnamon#6326]
Hello
when a window is on focus, there will be a white line in the right of the desktop

if there is no window on focus,the withe line will not appear

i dont want this line,how can i hide it when i focus on any windows?

**Comment by JosephMcc** [comment]
Please provide some useful info. Distro, Cinnamon version (can be obtained with `cinnamon --version`), and maybe a screenshot of the problem. I haven't seen anything like this.

**Comment by lancelock** [comment]
Sorry,I have find the reason.it's caused by the theme.i will close the issue.

发自我的 iPhone
