### ISSUE TITLE
Desktop files have double translations for some languages

### ISSUE THREAD

**Issue by scootergrisen** [linuxmint/cinnamon#6327]
I wonder why for some translations like danish there are both "da" and "da_DK" in the desktop files.

Example:
https://github.com/linuxmint/Cinnamon/blob/master/files/usr/share/applications/cinnamon-settings-applets.desktop#L25-L26

I don't see this in other non-cinnamon desktop files i have on my system. In those files there is only the "da" ones.

Have the translations been added directly into the desktop files or are the desktop files generated from some code and if so where is the code that generates the desktop files and where does it get "da" and "da_DK" from?

I'm think about deleting all the "da_DK" ones.

**Comment by JosephMcc** [comment]
Is there some harm in having them both?

**Comment by scootergrisen** [comment]
You could also ask are there any reason to have both "da" and "da_DK".
If the strings are identical the answer is no as far as i know.
I don't think it would make a difference for the user if "da_DK" is there or not. The user would get the same string. File size would be smaller though without "da_DK".
And where does "da_DK" come from? Who knows. It just seems to be copied blindly from "da" and assume its correct.
Maybe not a problem for "da" and "da_DK" but check out spanish. Are they really all correct. Seems like "es" is the only spanish translation and its just blindly being copied to multiple "es_*" without knowing if they are correct or not.
```
Comment[es]=Administrar applets de Cinnamon
Comment[es_419]=Administrar applets de Cinnamon
Comment[es_AR]=Administrar applets de Cinnamon
Comment[es_CL]=Administrar applets de Cinnamon
Comment[es_CO]=Administrar applets de Cinnamon
Comment[es_CR]=Administrar applets de Cinnamon
Comment[es_DO]=Administrar applets de Cinnamon
Comment[es_EC]=Administrar applets de Cinnamon
Comment[es_ES]=Administrar applets de Cinnamon
Comment[es_GT]=Administrar applets de Cinnamon
Comment[es_HN]=Administrar applets de Cinnamon
Comment[es_MX]=Administrar applets de Cinnamon
Comment[es_NI]=Administrar applets de Cinnamon
Comment[es_PA]=Administrar applets de Cinnamon
Comment[es_PE]=Administrar applets de Cinnamon
Comment[es_PR]=Administrar applets de Cinnamon
Comment[es_SV]=Administrar applets de Cinnamon
Comment[es_US]=Administrar applets de Cinnamon
Comment[es_UY]=Administrar applets de Cinnamon
Comment[es_VE]=Administrar applets de Cinnamon
```

Lets say there was no danish translation at all. Then there would be no reason to have:
```
Comment=Manage Cinnamon applets
Comment[da]=Manage Cinnamon applets
Comment[da_DK]=Manage Cinnamon applets
```

**Comment by jony0008** [comment]
@scootergrisen I think it shouldn't be both "da" and "da_DK", it makes it a lot more confusing, sometimes double work for translators and it is just doesn't make any sense to have them both.

**Comment by icarter09** [comment]
@scootergrisen is this issue still present in Cinnamon 4.2.4?

**Comment by scootergrisen** [comment]
Looks good.
