### ISSUE TITLE
Hot Corners doesn't work while dragging files.

### ISSUE THREAD

**Issue by AugustZellmer** [linuxmint/cinnamon#6328]
I have one of my hot corners set to go to the desktop on hover.

Let's say I'm dragging some file from a full-screen application onto my desktop. In my mind, I should be able to drag the file, hover over the hot corner, have the window minimize, and drop the file on my desktop; all without releasing the mouse button. 
Current hot corners implementation doesn't let me do this. Hot corners cannot be used while dragging a file.
Is this a bug or designed this way on purpose? I can always write a quick app to add this functionality, but I figured maybe it should just be part of hot corners. What do you guys think?

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
