### ISSUE TITLE
Annoying selection behavior with text fields

### ISSUE THREAD

**Issue by julienfalque** [linuxmint/Cinnamon#6330]
When you want to select text in a text field with the mouse, if you move the pointer above or below the text field, the selection will always be respectively the left part or the right part of the text.

For example, it often happens to me when I want to change the URL in the address bar of my browser. Say I'm on `http://foo/foo` and want to go to `http://foo/bar`, I start the selection after the last `/` and move to the right to select `foo`. If I go above the text field, the selection becomes `http://foo/` and if I don't see it immediatly, I start typing a wrong address, which is quite annoying.

**Comment by Odyseus** [comment]
Hello, @julienfalque.

What you describe is a gtk3 feature, not Cinnamon's. If you move the cursor up while you try to select, it will select all up to the beginning of the text field. If you move the cursor down, it will select everything up to the end of the text field.

**Comment by julienfalque** [comment]
Thank you for your answer @Odyseus. If it's a feature, is there a way to disable it then?

**Comment by JosephMcc** [comment]
as @Odyseus pointed out this is how it works in gtk and has nothing to do with Cinnamon.
