### ISSUE TITLE
Cinnamon NetworkManager applet pops up WiFI security password prompt on disconnect

### ISSUE THREAD

**Issue by geckolinux** [linuxmint/cinnamon#6331]
Hi, the Cinnamon NetworkManager applet poorly handles dropped WiFI connections. I connect to a weak WiFI network with intermittent signal loss. Every time the connection drops, the Cinnamon NetworkManager pops up the password dialog again. The expected behavior would be for it silently fail and keep trying to reconnect without bothering the user. It appears that it assumes the connection failed due to the WiFI security password being wrong, when in reality the signal is just too weak to establish or maintain a connection.

I'm running  Cinnamon 3.2.8 on openSUSE Tumbleweed.

Thanks!

**Comment by leigh123linux** [comment]
I believe the password dialog is part of nm-applet, not cinnamon.

**Comment by geckolinux** [comment]
I should clarify that the usability problem isn't just that it pops up the password dialog, but it actually waits for the user to click it before trying to re-connect again. So if this happens while the user is away and expecting the system to finish some network-related task or connect remotely to the system, it will disconnect and never try to reconnect again until the user returns.

**Comment by Vahan86** [comment]
@geckolinux, is this still an issue for you with Cinnamon 4.4?

**Comment by geckolinux** [comment]
Hi, sorry I'm running Cinnamon on openSUSE Leap now, which doesn't have Cinnamon 4.4 yet.

**Comment by KAMI911** [comment]
I have this problem with Linux Mint 19.3 w Cinnamon.

**Comment by saisons** [comment]
I have this problem on Linux Mint 20 Cinnamon version 4.6.7 kernel 5.4.0-58-generic
It happens with varying frequency. Only started in the last week or so after running some updates. It's a very frustrating bug.

**Comment by GNL10** [comment]
I have the problem too on Linux Mint 20 Cinnamon version 4.6.7 with kernel 5.4.0-58-generic

**Comment by bassborg** [comment]
I'm suddenly experiencing this issue multiple times a day. Is it related to a recent kernel update?
I'm also using Linux Mint 20 Cinnamon version 4.6.7 with kernel 5.4.0-58-generic.

Symptom: wifi signal is reported as being 0%, then a network dialog box appears which you need to click in order to reconnect.

**Comment by zakjakub** [comment]
Same problem, Linux Mint 20 Cinnamon, different kernels from 5.4.

Computer is unusable due to this bug. 

Found somebody some work-around?? I tried i.e. to disable power management of WiFi card but without success.

**Comment by geckolinux** [comment]
My only suggestion for now would be to remove the Cinnamon applet for NetworkManager and try the normal Gnome `nm-applet`.

**Comment by bassborg** [comment]
It's weirdly inconsistent. Some days it happens several times, other times the wifi drops and reconnects immediately (according to popups in Chrome) but it doesn't drop out long enough to prompt the dialog box.

**Comment by Lurux** [comment]
Just a heads up, this is most likely not linked to Cinnamon, as several users (including myself) are experiencing the same problem on XFCE and MATE. Has the issue been reported on the main Linux Mint repo ?

I'm currently using an up to date Linux Mint 19.3 XFCE computer which has this problem, and the following command seems to be a temporary solution: `sudo service network-manager restart`
However, I heard the problem re-appears after a certain time or after rebooting.

Maybe this is due to nm-applet or a recent kernel / driver update ?

**Comment by zakjakub** [comment]
You're right, it looks like problem with `network-manager`, not Cinnamon (I tried to use another applet and problem persisted).

It looks fixed by upgrading kernel to 5.8

**Comment by Lurux** [comment]
@zakjakub That's good to know. I hope this will soon get fixed in the 5.4 branch.

**Comment by saisons** [comment]
For what it's worth, about a week after I posted this, absent any intervention to fix it or any updates that I can think of, I noticed a marked drop off in this issue. In the last week I've applied a few updates, including to Mint itself, and since those this hasn't reoccurred, and I've noticed that I'm getting a new "It's ok, your internet connection has been restored" pop up occasionally, without the connection dropping like it was. 

I'm currently running Linux Mint 20.1 Cinnamon 4.8.5 Linux Kernel 5.4.0-60 Generic

**Comment by bassborg** [comment]
I have noticed the problem happening less as well, and was hopeful it had been resolved, although had been seeing the occasional  messages in Chrome saying internet disconnected/has been restored.

Anyway I just saw this happen again, you can see it dropped and reconnected twice in a row before it fialy spat the dumy and threw up the dialogue box (Mint 20.1 Cinnamon 4.8.6 Kernel 5.4.0-62-generic):

12:11:36 kernel: wlo1: Limiting TX power to 20 (20 - 0) dBm as advertised by [router]
12:11:36 kernel: wlo1: associated
12:11:36 kernel: wlo1: RX AssocResp from [router] (capab=0x1431 status=0 aid=2)
12:11:36 kernel: wlo1: associate with [router] (try 1/3)
12:11:36 kernel: wlo1: authenticated
12:11:36 kernel: wlo1: send auth to [router] (try 1/3)
12:11:36 kernel: wlo1: authenticate with [router]
12:11:26 kernel: wlo1: Connection to AP [router] lost
12:11:25 kernel: wlo1: associated
12:11:25 kernel: wlo1: RX AssocResp from [router] (capab=0x1431 status=0 aid=2)
12:11:25 kernel: wlo1: associate with [router] (try 1/3)
12:11:25 kernel: wlo1: authenticated
12:11:25 kernel: wlo1: send auth to [router] (try 1/3)
12:11:25 kernel: wlo1: authenticate with [router]
12:11:22 kernel: wlo1: Connection to AP [router] lost
12:10:33 kernel: wlo1: Limiting TX power to 20 (20 - 0) dBm as advertised by [router]
12:10:33 kernel: wlo1: associated
12:10:33 kernel: wlo1: RX AssocResp from [router] (capab=0x1431 status=0 aid=2)
12:10:33 kernel: wlo1: associate with [router] (try 1/3)
12:10:33 kernel: wlo1: authenticated
12:10:33 kernel: wlo1: send auth to [router] (try 1/3)
12:10:33 kernel: wlo1: authenticate with [router]
12:10:32 kernel: wlo1: Connection to AP [router] lost
12:09:09 kernel: wlo1: Limiting TX power to 20 (20 - 0) dBm as advertised by [router]
12:09:08 kernel: wlo1: associated
12:09:08 kernel: wlo1: RX AssocResp from [router] (capab=0x1431 status=0 aid=2)
12:09:08 kernel: wlo1: associate with [router] (try 1/3)
12:09:08 kernel: wlo1: authenticated
12:09:08 kernel: wlo1: send auth to [router] (try 1/3)
12:09:08 kernel: wlo1: authenticate with [router]
12:09:07 kernel: wlo1: Connection to AP [router] lost

**Comment by NikoKrause** [comment]
I had this issue as well in Mint 20. It was pretty annoying. Especially when typing, i sometimes got interrupted 2-3 times within a few minutes.

The problem seems to be gone since I upgraded from Kernel 5.4 to 5.8 with Mints Update Manager.

**Comment by leigh123linux** [comment]
This was never a cinnamon issue, try filing it against nm-applet or the kernel.
