### ISSUE TITLE
Software Manager keeps giving me not responding message everytime the application opens.

### ISSUE THREAD

**Issue by Kamlorn3955** [linuxmint/Cinnamon#6332]
Everytime I try to use Software Manager it locks up and stops responding. I have already Sudo purged it. and sudo apt-get install mintinstall to reinstall it. Ive restarted and shut down my computer as well. Everything else seems to be running fine.

**Comment by leigh123linux** [comment]
Not a cinnamon issue


https://github.com/linuxmint/mintinstall/issues
