### ISSUE TITLE
what is the compositor of cinnamon?

### ISSUE THREAD

**Issue by lancelock** [linuxmint/Cinnamon#6333]
i dont like the shadow style of default,how can i set it or how can i change the default compositor?

**Comment by JosephMcc** [comment]
There is nothing you can do from the user side.

**Comment by Odyseus** [comment]
Hello, everybody.

@lancelock: There is an extension that will be available soon on the Spices website that will allow you to modify the shadow of the window decorations and/or even remove it completely. It will be called **Custom Shadows**.
