### ISSUE TITLE
Cinnamon crashes when opening player via panel applet

### ISSUE THREAD

**Issue by TheGohan1905** [linuxmint/Cinnamon#6337]
When the window effects are disabled, if you try to open banshee, vlc or even xplayer via sound menu applet it crashes Cinnamon, asking if i want to reset it. The real cause is those window effects, I've tested it. It happens all the time if they're disabled. It should open normally the player.
Using Mint 18.1 Cinnamon

**Comment by JosephMcc** [comment]
https://github.com/linuxmint/Cinnamon/issues/5977
