### ISSUE TITLE
[FEATURE REQUEST] Remove dependency on network-manager

### ISSUE THREAD

**Issue by RyanNerd** [linuxmint/Cinnamon#6339]
There are a number of issues with `network-manager` (especially with xenial/16.04 listed below). 
Allow users to select what network manager they want to use -- for example `wicd`.
Unfortunately `network-manager` and `wicd` [do not play nicely with each other](http://askubuntu.com/questions/877319/restarting-network-manager-hangs-system).
I was surprised when I issued the command `apt-get purge network-manager` that cinnamon also got purged. 

Problems with `network-manager` with suggestions to use `wicd` or a different manager instead:
https://ubuntuforums.org/showthread.php?t=2331202
https://bugzilla.kernel.org/show_bug.cgi?id=191601
https://ubuntuforums.org/showthread.php?t=2331202
https://forums.opensuse.org/showthread.php/514061-Problems-with-Intel-7260-WiFi-card-(Solved)

**Comment by leigh123linux** [comment]
The 4 bugs/issues you link to are firmware issues not network-manager.
If you want to use wicd feel free, just disable network-manager

`systemctl disable NetworkManager.service`
