### ISSUE TITLE
NetworkManager applet should display connection name instead of SSID

### ISSUE THREAD

**Issue by real-or-random** [linuxmint/cinnamon#6340]
I have several NetworkManager connections with the same SSID (but different credentials). However,
I cannot distinguish them in the NetworkManager applet. In fact, only one shows up when the SSID is discovered. The others only show up when I click "Known networks".

Meta bug: #2746

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
