### ISSUE TITLE
NetworkManager should not silently unset non-displayed fields when editing connection

### ISSUE THREAD

**Issue by real-or-random** [linuxmint/Cinnamon#6341]
This is the same problem as one that  nm-connection-editor had:
https://bugzilla.gnome.org/show_bug.cgi?id=777225

So I won't explain it again here. Note that this has security implications. Removing attributes such as "subject-match" makes the client vulnerable to man-in-the-middle attacks, and the user does not even notice.

Metabug: #2746

**Comment by leigh123linux** [comment]
cinnamon-control-center does the network settings

https://github.com/linuxmint/cinnamon-control-center
