### ISSUE TITLE
Network manager applet constant connecting icon even when connected

### ISSUE THREAD

**Issue by piotrekkr** [linuxmint/cinnamon#6342]
Hi,

I have wired connection active by default on my computer.  For some time now after login to my profile network manager applet icon is always like this:

![applet_nm](https://cloud.githubusercontent.com/assets/503782/23698353/8980bd92-03eb-11e7-9154-c37595def9ec.png)

even when I'm already connected to internet and everything works. When I turn off wired connection and turn on again, icon is back to normal. It happens only after login when I'm automatically connected to internet.

How can I fix it?

**Comment by JosephMcc** [comment]
Please supply basic info like distro and cinnamon version.

**Comment by piotrekkr** [comment]
Sorry, I forgot about it:

```
$ cinnamon --version
Cinnamon 3.2.7

$ uname -a
Linux piotrek-Vostro-2520 4.4.0-64-generic #85-Ubuntu SMP Mon Feb 20 11:50:30 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

$ cat /etc/issue
Linux Mint 18.1 Serena
```

**Comment by d3xter** [comment]
@piotrekkr Do you have specified a custom DNS-Server for that connection?

I get the same behavior when connecting to my wireless network and having 8.8.8.8 as my DNS-Server.

**Comment by d3xter** [comment]
So I've tried to diagnose the problem further.

Starting up with Wireless disabled and enable it afterwards -> shows the connecting icon constantly.
When disabling and enabling Wireless, the first couple of tries it works only every second attempt,
after some time it works always.

If my Wireless is enabled when starting cinnamon, the connected icon is shown,
but still, after disabling/enabling the Wireless, it works 50% of the time at the beginning and works completely after some time.

So I guess there must be a race-condition somewhere.

**Comment by Vahan86** [comment]
@piotrekkr, is this still an issue for you in Cinnamon 4.2?

**Comment by piotrekkr** [comment]
@Vahan86 I think that it's fixed on newest linux mint cinnamon.
