### ISSUE TITLE
keyboard shortcuts/layouts

### ISSUE THREAD

**Issue by ekaj113** [linuxmint/cinnamon#6344]
no matter which keyboard layout I have selected, when I try to do a keyboard shortcut (not for programs) it only recognizes it for the layout that is on the top of the layout list, not for the keyboard layout that is selected.

**Comment by JosephMcc** [comment]
Please supply basic info like distro and cinnamon version.

**Comment by ekaj113** [comment]
Sorry about that. I cant get that much exacts right now, but the best I believe I can remember is Rafael and the most updated public version. I will check exacts when I can

**Comment by pols12** [comment]
I encounter the same bug, which seems to be [present in Gnome since 2009](https://bugzilla.gnome.org/show_bug.cgi?id=602137).

I use Cinnamon 3.2.7 on Debian 9.0

**Comment by icarter09** [comment]
Please troubleshoot and find the exact cause of the problem. You can reopen the issue if the responsible component proves to be Cinnamon.

http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/.

**Comment by pols12** [comment]
Have you tried to reproduce it?

1. Open Keyboard settings, go to Layouts tab and click on + button to add a second layout. E.g. at home, I have added `French (Bépo, ergonomic, Dvorak way)` (my first one was `French (variant)`).
2. Go to Shortcuts tab. Look for a shortcut using a layout-dependant key. E.g. at home, my shortcut for “Show the desktop” is “Super+D” and the D key is different on Bépo layout.
3. Press the shortcut to test it. Then enable the second layout (you can use Keyboard applet in board panel). E.g. at home, I have enabled Bépo layout.
4. Press the shortcut to test it, it does not work. E.g. pressing Super+D does not do anything.
5. Press the same keys than before enabling second layout → it still produce the behavior whereas the layout has been changed. E.g. pressing Super+I (I key with Bépo is on the same place than D key with Variant).
6. In Keyboard settings, Layouts tab, click on second layout. Then press the ^ button to push it as the first layout of the list.
7. Press the shortcut to test it: now it works well. E.g. pressing Super+D on Bépo well displays the desktop.

Actual result: shortcuts are based on 1st layout in the layout list.

Expected result: shortcut should be based on actually enabled layout.

**Comment by icarter09** [comment]
@pols12 is this problem unique to Cinnamon? You said it has been present in Gnome since 2009 and the tickets you referenced to equally say that the problem is with Gnome. That is why it was closed out since it seems to be a problem with Gnome.

**Comment by pols12** [comment]
I’m not sure to well understand the link between Cinnamon and Gnome: if the bug would be fixed in Gnome, would the fix automatically imported to Cinnamon?

Besides, since it concerns Keyboard settings, should it report to Cinnamon/Gnome Settings Daemon project instead?

Thanks for your help to correctly report this issue.
