### ISSUE TITLE
"Connection Etablished" notification message not fully translated

### ISSUE THREAD

**Issue by seigneurfuo** [linuxmint/Cinnamon#6352]
I used Cinnamon with the French translation, and when I disconnect my network card, the notification message is not fully translated.

System: Manjaro (Arch based system)
Cinnamon: 3.2.8

![image](https://cloud.githubusercontent.com/assets/20669563/23826769/1c5c44be-06a4-11e7-9753-60476ea61ba5.png)

**Comment by NikoKrause** [comment]
Which Distribution (Mint 17.2, Arch, Fedora 25, etc...) do you use?

**Comment by seigneurfuo** [comment]
I'am using Manjaro. (Arch based)

**Comment by NikoKrause** [comment]
It's properly translated here in Linux Mint. You properly miss some translation package.

**Comment by NikoKrause** [comment]
The file, where this is translated, is called `nm-applet.mo`.
In LinuxMint it's located in `/usr/share/locale-langpack/fr/LC_MESSAGES/nm-applet.mo`

**Comment by NikoKrause** [comment]
`nm-applet` is part of the `network-manager-gnome` package.
```
sudo apt install network-manager-gnome
```

**Comment by leigh123linux** [comment]
Arch use sane package names

https://www.archlinux.org/packages/extra/x86_64/nm-connection-editor/

**Comment by seigneurfuo** [comment]
I have both nm-applet and nm-connection-editor installed.
Now, I'am running Cinnamon 3.4.3 and I have the same issue with the translation.

**Comment by NikoKrause** [comment]
Can you upload your nm-applet.mo file?

**Comment by seigneurfuo** [comment]
Translation file for nm-connection-editor: /usr/share/locale/fr/LC_MESSAGES/nm-applet.mo

[nm-applet.mo.zip](https://github.com/linuxmint/Cinnamon/files/1187025/nm-applet.mo.zip)

**Comment by NikoKrause** [comment]
Okay, I converted your .mo file to a .po file. It does not contain the Strings in your screenshot at all.
I assume Arch provides a newer or older version. You'll need to read out the Arch guys

**Comment by NikoKrause** [comment]
I looked at the gnome upstream package. It provides the translations correctly. There's going something wrong between the source code and the end result package.
Please get in touch with the arch packager.
According to this website https://www.archlinux.org/packages/extra/x86_64/nm-connection-editor/
the last packager is Jan Alexander Steffens <jan.steffens@gmail.com>

**Comment by NikoKrause** [comment]
Related problem https://github.com/linuxmint/nemo-extensions/issues/229#issuecomment-319059914

**Comment by NikoKrause** [comment]
There's nothing we can do about it. It's something, which has to be fixed by the arch packager.
