### ISSUE TITLE
Set As Default makes no difference with xreader 

### ISSUE THREAD

**Issue by noreasternhumidity** [linuxmint/Cinnamon#6353]
This might be due to recent updates, or my willingness to update to everything new.  :)

When I double-click a PDF from my administrative account, the Imagemajick program opens it.  I try to change the default to xreader, and "Set As Default" doesn't replace Imagemagick.

I back up one directory and open the directory as Root.  Then I double click on the same PDFs as Root.  Xreader is the default application, as expected.  In my profile it is not, and I can't seem to change it.

**Comment by JosephMcc** [comment]
https://github.com/linuxmint/Cinnamon/issues/6347
