### ISSUE TITLE
SimpleScreenRecorder in Fedora 25 Cinnamon

### ISSUE THREAD

**Issue by bionan** [linuxmint/Cinnamon#6358]
I tried the SSR in Gnome and KDE and it worked perfectly well.

When I run SSR on Cinnamon the result is not the best, with the screen blinking when moving a window (please, [see video](https://www.youtube.com/watch?v=-VRPcP0wB2c&feature=youtu.be)).

However, if I run SSR in Cinnamon **with software rendering**, the recording is perfect ...

What could be the cause of the problem and how to solve it?

Thank you

**Comment by Cyborgscode** [comment]
screengabbng under cinnamon is a pain. using ffmpeg to record the desktop is next to impossible, but works great under gnome/X11 . Under wayland it's a mess anywhere ;)

**Comment by bionan** [comment]
Hello,
With the upgrade to Fedora 26 everything worked fine.
