### ISSUE TITLE
Some icons in the panel appear blurry when using the Mint-x or y icons with the Mint-y desktop theme

### ISSUE THREAD

**Issue by matteocoder** [linuxmint/cinnamon#6361]
It happens to the battery icon and, a little less noticeably, to the notification count number.
This is what it is like when the battery is discharging
![screenshot from 2017-03-15 17-43-36](https://cloud.githubusercontent.com/assets/22897138/23960140/6619bae0-09a7-11e7-9e69-74d44bb57478.png)
and this when it is being charged
![screenshot from 2017-03-15 17-42-01](https://cloud.githubusercontent.com/assets/22897138/23960180/868a4128-09a7-11e7-8e84-c06032c92067.png)

This issue appears on both a 1600x900 screen and a 1280x800 one.

**Comment by JosephMcc** [comment]
I have to admit I'm having a bit of a hard time spotting the issue in your screenshot.

**Comment by matteocoder** [comment]
Thanks for responding! Yes, it is not super noticeable, but the icon definitely appears blurry next to the sound and network icons. Is there something more I can do to help resolve the issue?

**Comment by Vahan86** [comment]
@matteocoder, does this issue still relevant to Cinnamon 4.2?

**Comment by matteocoder** [comment]
Hello @Vahan86 , I am using the Linux Mint 19.3 Cinnamon beta and the problem looks to be solved thanks to the new battery icon. I have not used Mint for a couple of years, and I had a very good impression of the refined visual experience. Kudos to you guys!

**Comment by Vahan86** [comment]
@matteocoder, thanks for your reply.
