### ISSUE TITLE
after login shutdown - restart -suspend actions from login screen fall to a black screen with mouse pointer

### ISSUE THREAD

**Issue by gahi** [linuxmint/Cinnamon#6362]
Hi, 
Tried this with two installations on different pcs of **linux mint 18.1 cinnamon 64bit** (one was fresh install the other upgrade from 17.3). Both act the same way.
Asked a friend to try it with the same result. It seems a bug independent of graphics adapter - login screen theme.

To reproduce it:
1. Reboot (Before you login shutdown - restart - suspend from login screen works fine)
2. Login with any user account
3. Logoff or lock screen or switch user
4. From login screen try to shutdown or restart the pc
You end up with a black screen and a mouse pointer, pc never shuts down or restarts. So you have to use ctrl+alt+f2 to log on terminal and run shutdown -r now... this way the pc shuts down normally.

Seems something that has to do with the move from upstart to systemd on 18.1
Shutdown, restart etc work fine from cinnamon while logged. The bug is at the login screen and only if you first log to cinnamon.

**Comment by mabod** [comment]
Are you using mdm as login manager? If yes, this bug might be related to yours: https://github.com/linuxmint/mdm/issues/130

**Comment by leigh123linux** [comment]
Cinnamon doesn't handle login or lock functions
