### ISSUE TITLE
Can't add properties to command in Launcher Properties

### ISSUE THREAD

**Issue by mxa** [linuxmint/Cinnamon#6365]
I have a launcher that is
`/usr/local/bin/Appfolder/app -- %u`

but i'd like it to be 
`QT_IM_MODULE=xim /usr/local/bin/Appfolder/app -- %u`
However, it doesn't allow me to submit that change

**Comment by Odyseus** [comment]
Hello, @mxa.

Try with the following command:

```bash
sh -c "QT_IM_MODULE=xim /usr/local/bin/Appfolder/app -- %u"
```

**Comment by mxa** [comment]
That seems to work, but why do I have two launchers after doing this? (Both with the changed line) If i try to delete one of them, both are gone.
