### ISSUE TITLE
mint 18 screensaver wont start

### ISSUE THREAD

**Issue by Neobondjames** [linuxmint/Cinnamon#6366]
when I wait for the screensaver to start it doesn't actually start it just shows the wallpaper instead. I chose the wormhole screen saver but it did the same thing no matter hat screen saver I pick it doesn't work. I even uninstalled then reinstalled and it didn't fix it :(

**Comment by leigh123linux** [comment]
You have filed the issue in the wrong place/

https://github.com/linuxmint/cinnamon-screensaver/issues
