### ISSUE TITLE
Can't Use Both Right and Left Clicks in Games

### ISSUE THREAD

**Issue by mhsabbagh** [linuxmint/Cinnamon#6367]
Hello.

Cinnamon prevents from using the right click and left click for mouse at the same time in games. For example, if you tried to install the "teeworlds" game, and tried to hook (using right click) and shoot (using left click) at the same time, you will notice that only one of them may work at the same time. This doesn't happen at all on other desktop interfaces. They both can work at the same time.

This bug also happens on Steam (DOTA 2), probably other possible games.

The problem is caused because of the "Emulate middle click by clicking both left and right buttons" option which is enabled by default in mouse settings. If this option is disabled by default, the bug would be fixed.

**Comment by JosephMcc** [comment]
> The problem is caused because of the "Emulate middle click by clicking both left and right buttons" option which is enabled by default in mouse settings. If this option is disabled by default, the bug would be fixed.

That is the reason the option exists. If one setting "just worked" for everyone there wouldn't be a setting. We are of course open to reviewing the defaults. The fact that only one person has mentioned this means the default we are currently using is probably fine.
