### ISSUE TITLE
Cinnamon on Arch dumped core

### ISSUE THREAD

**Issue by Xarin** [linuxmint/Cinnamon#6369]
I had noticed that I had an extra "internet" entry in my menu so I removed it with Menu Editor. This immediately caused cinnamon to crash and I now get this error after reboot. Any help would be appreciated.

`Mar 21 15:23:33 systemd-coredump[1661]: Process 1600 (cinnamon) of user 117879 dumped core.

                                                       Stack trace of thread 1600:
                                                       #0  0x00007f334d35ea10 raise (libc.so.6)
                                                       #1  0x00007f334d36013a abort (libc.so.6)
                                                       #2  0x00007f334d95e345 g_assertion_message (libglib-2.0.so.0)
                                                       #3  0x00007f334d95e3da g_assertion_message_expr (libglib-2.0.so.0)
                                                       #4  0x00007f334c724fed n/a (libcinnamon-menu-3.so.0)
                                                       #5  0x00007f334c724c48 n/a (libcinnamon-menu-3.so.0)
                                                       #6  0x00007f334c725164 n/a (libcinnamon-menu-3.so.0)
                                                       #7  0x00007f334c72574b gmenu_tree_load_sync (libcinnamon-menu-3.so.0)
                                                       #8  0x00007f334efd2ea3 n/a (libcinnamon.so)
                                                       #9  0x00007f334dc3334b g_type_create_instance (libgobject-2.0.so.0)
                                                       #10 0x00007f334dc151fb n/a (libgobject-2.0.so.0)
                                                       #11 0x00007f334dc16c0d g_object_newv (libgobject-2.0.so.0)
                                                       #12 0x00007f334dc173c4 g_object_new (libgobject-2.0.so.0)
                                                       #13 0x00007f334efd3865 cinnamon_app_system_get_default (libcinnamon.so)
                                                       #14 0x00007f33478ff1c8 ffi_call_unix64 (libffi.so.6)
                                                       #15 0x00007f33478fec2a ffi_call (libffi.so.6)
                                                       #16 0x00007f334d0cef21 n/a (libcjs.so.0)
                                                       #17 0x00007f334d0d0475 n/a (libcjs.so.0)
                                                       #18 0x00007f334ca0e89c n/a (libmozjs-24.so)
                                                       #19 0x00007f334ca0f851 n/a (libmozjs-24.so)
                                                       #20 0x00007f334ca17e78 n/a (libmozjs-24.so)
                                                       #21 0x00007f334ca18f8b n/a (libmozjs-24.so)
                                                       #22 0x00007f334cac743d _ZN2JS8EvaluateEP9JSContextNS_6HandleIP8JSObjectEENS_14CompileOptionsEPKtmPNS_5ValueE (libmozjs-24.so)
                                                       #23 0x00007f334cac754e _ZN2JS8EvaluateEP9JSContextNS_6HandleIP8JSObjectEENS_14CompileOptionsEPKcmPNS_5ValueE (libmozjs-24.so)
                                                       #24 0x00007f334d0c25d6 gjs_eval_with_scope (libcjs.so.0)
                                                       #25 0x00007f334d0bc363 gjs_context_eval (libcjs.so.0)
                                                       #26 0x00007f334efd0dbf n/a (libcinnamon.so)
                                                       #27 0x00007f334ed1395b meta_plugin_manager_new (libmuffin.so.0)
                                                       #28 0x00007f334ed10787 meta_compositor_manage_screen (libmuffin.so.0)
                                                       #29 0x00007f334ed258e3 n/a (libmuffin.so.0)
                                                       #30 0x00007f334ed324a2 meta_run (libmuffin.so.0)
                                                       #31 0x000000000040175d n/a (cinnamon)
                                                       #32 0x00007f334d34b511 __libc_start_main (libc.so.6)
                                                       #33 0x000000000040184a n/a (cinnamon)

                                                       Stack trace of thread 1604:
                                                       #0  0x00007f334d6dc756 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
                                                       #1  0x00007f334481e4e0 PR_WaitCondVar (libnspr4.so)
                                                       #2  0x00007f334cb29c0e n/a (libmozjs-24.so)
                                                       #3  0x00007f3344823d6c n/a (libnspr4.so)
                                                       #4  0x00007f334d6d62e7 start_thread (libpthread.so.0)
                                                       #5  0x00007f334d41754f __clone (libc.so.6)

                                                       Stack trace of thread 1601:
                                                       #0  0x00007f334d40d67d poll (libc.so.6)
                                                       #1  0x00007f334d9377a6 n/a (libglib-2.0.so.0)
                                                       #2  0x00007f334d9378bc g_main_context_iteration (libglib-2.0.so.0)
                                                       #3  0x00007f334d937901 n/a (libglib-2.0.so.0)
                                                       #4  0x00007f334d95f175 n/a (libglib-2.0.so.0)
                                                       #5  0x00007f334d6d62e7 start_thread (libpthread.so.0)
                                                       #6  0x00007f334d41754f __clone (libc.so.6)

                                                       Stack trace of thread 1603:
                                                       #0  0x00007f334d40d67d poll (libc.so.6)
                                                       #1  0x00007f334d9377a6 n/a (libglib-2.0.so.0)
                                                       #2  0x00007f334d9378bc g_main_context_iteration (libglib-2.0.so.0)
                                                       #3  0x00007f333cb914bd n/a (libdconfsettings.so)
                                                       #4  0x00007f334d95f175 n/a (libglib-2.0.so.0)
                                                       #5  0x00007f334d6d62e7 start_thread (libpthread.so.0)
                                                       #6  0x00007f334d41754f __clone (libc.so.6)

                                                       Stack trace of thread 1605:
                                                       #0  0x00007f334d6dc756 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
                                                       #1  0x00007f334481e4e0 PR_WaitCondVar (libnspr4.so)
                                                       #2  0x00007f334cb9dbab n/a (libmozjs-24.so)
                                                       #3  0x00007f3344823d6c n/a (libnspr4.so)
                                                       #4  0x00007f334d6d62e7 start_thread (libpthread.so.0)
                                                       #5  0x00007f334d41754f __clone (libc.so.6)

                                                       Stack trace of thread 1602:
                                                       #0  0x00007f334d40d67d poll (libc.so.6)
                                                       #1  0x00007f334d9377a6 n/a (libglib-2.0.so.0)
                                                       #2  0x00007f334d937b32 g_main_loop_run (libglib-2.0.so.0)
                                                       #3  0x00007f334df1d446 n/a (libgio-2.0.so.0)
                                                       #4  0x00007f334d95f175 n/a (libglib-2.0.so.0)
                                                       #5  0x00007f334d6d62e7 start_thread (libpthread.so.0)
                                                       #6  0x00007f334d41754f __clone (libc.so.6)
Mar 21 15:23:43 eb2-2204-lin00 systemd[1]: Started Process Core Dump (PID 1706/UID 0).
Mar 21 15:23:43 eb2-2204-lin00 systemd-coredump[1707]: Process 1699 (cinnamon) of user 117879 dumped core.

                                                       Stack trace of thread 1699:
                                                       #0  0x00007f8ee03b2a10 raise (libc.so.6)
                                                       #1  0x00007f8ee03b413a abort (libc.so.6)
                                                       #2  0x00007f8ee09b2345 g_assertion_message (libglib-2.0.so.0)
                                                       #3  0x00007f8ee09b23da g_assertion_message_expr (libglib-2.0.so.0)
                                                       #4  0x00007f8edf778fed n/a (libcinnamon-menu-3.so.0)
                                                       #5  0x00007f8edf778c48 n/a (libcinnamon-menu-3.so.0)
                                                       #6  0x00007f8edf779164 n/a (libcinnamon-menu-3.so.0)
                                                       #7  0x00007f8edf77974b gmenu_tree_load_sync (libcinnamon-menu-3.so.0)
                                                       #8  0x00007f8ee2026ea3 n/a (libcinnamon.so)
                                                       #9  0x00007f8ee0c8734b g_type_create_instance (libgobject-2.0.so.0)
                                                       #10 0x00007f8ee0c691fb n/a (libgobject-2.0.so.0)
                                                       #11 0x00007f8ee0c6ac0d g_object_newv (libgobject-2.0.so.0)
                                                       #12 0x00007f8ee0c6b3c4 g_object_new (libgobject-2.0.so.0)
                                                       #13 0x00007f8ee2027865 cinnamon_app_system_get_default (libcinnamon.so)
                                                       #14 0x00007f8eda9531c8 ffi_call_unix64 (libffi.so.6)
                                                       #15 0x00007f8eda952c2a ffi_call (libffi.so.6)
                                                       #16 0x00007f8ee0122f21 n/a (libcjs.so.0)
                                                       #17 0x00007f8ee0124475 n/a (libcjs.so.0)
                                                       #18 0x00007f8edfa6289c n/a (libmozjs-24.so)
                                                       #19 0x00007f8edfa63851 n/a (libmozjs-24.so)
                                                       #20 0x00007f8edfa6be78 n/a (libmozjs-24.so)
                                                       #21 0x00007f8edfa6cf8b n/a (libmozjs-24.so)
                                                       #22 0x00007f8edfb1b43d _ZN2JS8EvaluateEP9JSContextNS_6HandleIP8JSObjectEENS_14CompileOptionsEPKtmPNS_5ValueE (libmozjs-24.so)
                                                       #23 0x00007f8edfb1b54e _ZN2JS8EvaluateEP9JSContextNS_6HandleIP8JSObjectEENS_14CompileOptionsEPKcmPNS_5ValueE (libmozjs-24.so)
                                                       #24 0x00007f8ee01165d6 gjs_eval_with_scope (libcjs.so.0)
                                                       #25 0x00007f8ee0110363 gjs_context_eval (libcjs.so.0)
                                                       #26 0x00007f8ee2024dbf n/a (libcinnamon.so)
                                                       #27 0x00007f8ee1d6795b meta_plugin_manager_new (libmuffin.so.0)
                                                       #28 0x00007f8ee1d64787 meta_compositor_manage_screen (libmuffin.so.0)
                                                       #29 0x00007f8ee1d798e3 n/a (libmuffin.so.0)
                                                       #30 0x00007f8ee1d864a2 meta_run (libmuffin.so.0)
                                                       #31 0x000000000040175d n/a (cinnamon)
                                                       #32 0x00007f8ee039f511 __libc_start_main (libc.so.6)
                                                       #33 0x000000000040184a n/a (cinnamon)

                                                       Stack trace of thread 1703:
                                                       #0  0x00007f8ee0730756 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
                                                       #1  0x00007f8ed78724e0 PR_WaitCondVar (libnspr4.so)
                                                       #2  0x00007f8edfb7dc0e n/a (libmozjs-24.so)
                                                       #3  0x00007f8ed7877d6c n/a (libnspr4.so)
                                                       #4  0x00007f8ee072a2e7 start_thread (libpthread.so.0)
                                                       #5  0x00007f8ee046b54f __clone (libc.so.6)

                                                       Stack trace of thread 1701:
                                                       #0  0x00007f8ee046167d poll (libc.so.6)
                                                       #1  0x00007f8ee098b7a6 n/a (libglib-2.0.so.0)
                                                       #2  0x00007f8ee098bb32 g_main_loop_run (libglib-2.0.so.0)
                                                       #3  0x00007f8ee0f71446 n/a (libgio-2.0.so.0)
                                                       #4  0x00007f8ee09b3175 n/a (libglib-2.0.so.0)
                                                       #5  0x00007f8ee072a2e7 start_thread (libpthread.so.0)
                                                       #6  0x00007f8ee046b54f __clone (libc.so.6)

                                                       Stack trace of thread 1700:
                                                       #0  0x00007f8ee046167d poll (libc.so.6)
                                                       #1  0x00007f8ee098b7a6 n/a (libglib-2.0.so.0)
                                                       #2  0x00007f8ee098b8bc g_main_context_iteration (libglib-2.0.so.0)
                                                       #3  0x00007f8ee098b901 n/a (libglib-2.0.so.0)
                                                       #4  0x00007f8ee09b3175 n/a (libglib-2.0.so.0)
                                                       #5  0x00007f8ee072a2e7 start_thread (libpthread.so.0)
                                                       #6  0x00007f8ee046b54f __clone (libc.so.6)

                                                       Stack trace of thread 1702:
                                                       #0  0x00007f8ee046167d poll (libc.so.6)
                                                       #1  0x00007f8ee098b7a6 n/a (libglib-2.0.so.0)
                                                       #2  0x00007f8ee098b8bc g_main_context_iteration (libglib-2.0.so.0)
                                                       #3  0x00007f8ec9dce4bd n/a (libdconfsettings.so)
                                                       #4  0x00007f8ee09b3175 n/a (libglib-2.0.so.0)
                                                       #5  0x00007f8ee072a2e7 start_thread (libpthread.so.0)
                                                       #6  0x00007f8ee046b54f __clone (libc.so.6)

                                                       Stack trace of thread 1704:
                                                       #0  0x00007f8ee0730756 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
                                                       #1  0x00007f8ed78724e0 PR_WaitCondVar (libnspr4.so)
                                                       #2  0x00007f8edfbf1bab n/a (libmozjs-24.so)
                                                       #3  0x00007f8ed7877d6c n/a (libnspr4.so)
                                                       #4  0x00007f8ee072a2e7 start_thread (libpthread.so.0)
                                                       #5  0x00007f8ee046b54f __clone (libc.so.6)`

Thanks!

**Comment by leigh123linux** [comment]
The backtraces are useless without the debugging symbols, without additional info this issue will be closed.
