### ISSUE TITLE
Bug when authenticating password

### ISSUE THREAD

**Issue by GabrielMGitHub** [linuxmint/Cinnamon#6370]
I installed Linux mint but had not updated, when opening the application manager asks to enter the password if you enter the correct password the program opens, if you enter the wrong password asks to retype the password. However when updating the system when opening the application manager asks to enter the password if you enter the correct password the program opens, if you enter the wrong password the window disappears and does not ask to retype the password. It happens with mintinstall and set-defalt-locate. etc.

Use Linux Mint: 18.1 Cinnamon

**Comment by leigh123linux** [comment]
Cinnamon isn't responsible for polkit or gksu issues, re-file the issue against mintinstall for now.

> It happens with mintinstall and set-defalt-locate.

https://github.com/linuxmint/mintinstall/issues
