### ISSUE TITLE
Panel show and hide delay: increment and decrement icons malfunction

### ISSUE THREAD

**Issue by ACinnamonUserInUK** [linuxmint/Cinnamon#6374]
When using either my touchpad or my mouse, the increment and decrement buttons for both the 'show panel' and the 'hide panel' delay malfunction: the numbers (the delay settings) seem to jump around on their own. Strange. See if you can reproduce?

Mint 18.1 x64.

**Comment by brownsr** [comment]
Yes, I can see that.  Seems to happen most often with rapid consecutive presses.

**Comment by ACinnamonUserInUK** [comment]
So . . is someone going to investigate and hopefully fix the relevant code?

**Comment by JosephMcc** [comment]
> So . . is someone going to investigate and hopefully fix the relevant code?

Nope.

**Comment by ACinnamonUserInUK** [comment]
> Nope.

Er, say what? Do I misunderstand the point of a bugtracker?

Perhaps you thought I was being pushy. I did want want to give a little
encouragement - because I've noticed some bugs get identified and then
left without so much as a statement of intent-to-fix.

**Comment by JosephMcc** [comment]
Ehh... that was meant to be a little tongue in cheek. Although just because someone doesn't tell you that it is being worked on, doesn't mean it isn't. And it's only been opened for a whole 2 days.

**Comment by brownsr** [comment]
@ACinnamonUserInUK Can you confirm what version of Cinnamon you are using ? It would help if you could. Are you on the latest production version, the nightly PPA used for testing, or ...

**Comment by ACinnamonUserInUK** [comment]
Cobinja: I am on the latest production version.

```
~ $ cinnamon --version
Cinnamon 3.2.7
```
