### ISSUE TITLE
Set gconf values when theme is changed

### ISSUE THREAD

**Issue by theel0ja** [linuxmint/Cinnamon#6377]
This while using Mint-Y as theme and Numix-Circle as icon pack.

![image](https://cloud.githubusercontent.com/assets/5832930/24304428/fb5bda18-10c1-11e7-8350-7df18bb514a4.png)

**Comment by NikoKrause** [comment]
Check if there is `/desktop/cinnamon/interface/icon_theme` value

**Comment by theel0ja** [comment]
There isn't.
![image](https://cloud.githubusercontent.com/assets/5832930/24321073/f4a9c678-114b-11e7-9718-ccac44259773.png)

**Comment by JosephMcc** [comment]
Try using dconf-editor. Gconf is old and unused.
