### ISSUE TITLE
Multiple Screensavers Run In Cinnamon

### ISSUE THREAD

**Issue by napperley** [linuxmint/Cinnamon#6379]
Every time a screensaver is exited it continues to run and use around 100% of a CPU core. So if 2 screensavers are exited then there are 2 instances of the screensaver running when it should have exited straight away. Looks as though this problem started after a recent Linux Mint 17.3 software update (major regression) yesterday (24 March 2017). Below is a screenshot showing the problem:

![multiple screensavers running in cinnamon](https://cloud.githubusercontent.com/assets/3538279/24316573/e2a013da-1153-11e7-869e-3b1c7a84ef36.png)

If the screensavers continue to run with too much CPU usage (%) then it causes serious strain on CPU fans, and generates too much heat.

**Comment by LoganS1** [comment]
I second this problem as I noticed this on my machine too
![screenshot from 2017-04-02 15-47-23](https://cloud.githubusercontent.com/assets/21230472/24590924/b81ab278-17bb-11e7-8a1c-3df77b5472ee.png)

**Comment by JosephMcc** [comment]
https://github.com/linuxmint/Cinnamon/issues/6135
