### ISSUE TITLE
Sometimes after resuming from suspend cinnamon gets stuck at lock screen without displaying password box

### ISSUE THREAD

**Issue by Barteks2x** [linuxmint/Cinnamon#6380]
Sometimes (I can't see a clear pattern) when I resume from suspend there is no way for me to get back into the session. Everything is stuck at the lock screen with current time shown, and nothing else. I can move mouse cursor around and time updates correctly, but the password box never appears, no matter what I do. Starting another x server works fine. Starting another X server from tty works fine.

**Comment by leigh123linux** [comment]
File your issue here instead

https://github.com/linuxmint/cinnamon-screensaver/issues
