### ISSUE TITLE
Mint18.1- crash with high CPU and RAM consumption

### ISSUE THREAD

**Issue by karentow** [linuxmint/Cinnamon#6381]
Mint 18.1 64-bit fresh install. Booting machine into MDM login screen.
About 40% of the time, after inputing password, the screen goes black with just mouse pointer visible.
When I ssh into the machine I can see many "cinnamon --replace" processes consuming 100% CPU and RAM usage increasing about 200MB/s

![cinnamon 1 after logging in 2017-03-25 23-19-30](https://cloud.githubusercontent.com/assets/26680057/24326730/2bae709c-11b5-11e7-91dd-42346c59e881.png)
After a few minutes, when all available RAM and swap get used up, Cinnamon crashes and loads GUI with notification it crashed, is running in fallback mode and ask me if I want to restart it.
RAM usage drops but CPU usage stays high.
![cinnamon 2 after crash 2017-03-25 23-22-42](https://cloud.githubusercontent.com/assets/26680057/24326731/2bae8078-11b5-11e7-886e-3105f444c1b2.png)
It ignores request to restart.
After killing all user's processes with killall  the next logging attempt usually (not always) is fine.

System:    Host: nuc Kernel: 4.8.0-42-generic x86_64 (64 bit) Console: tty 0 Distro: Linux Mint 18.1 Serena
Machine:   Mobo: Intel model: NUC7i3BNB v: J22859-303
           Bios: Intel v: BNKBL357.86A.0042.2017.0303.1854 date: 03/03/2017
CPU:       Dual core Intel Core i3-7100U (-HT-MCP-) cache: 3072 KB 
           clock speeds: max: 2400 MHz 1: 700 MHz 2: 666 MHz 3: 600 MHz 4: 2400 MHz
Graphics:  Card: Intel Device 5916
           Display Server: X.org 1.18.4 drivers: intel (unloaded: fbdev,vesa)
           tty size: 144x31 Advanced Data: N/A out of X
Audio:     Card Intel Device 9d71 driver: snd_hda_intel Sound: ALSA v: k4.8.0-42-generic
Network:   Card-1: Intel Ethernet Connection (4) I219-V driver: e1000e
           IF: eno1 state: down mac: f4:4d:30:6b:6d:52
           Card-2: Intel Device 24fd driver: iwlwifi
           IF: wlp58s0 state: up speed: N/A duplex: N/A mac: f8:63:3f:0f:da:f7
Drives:    HDD Total Size: NA (-) ID-1: /dev/nvme0n1 model: N/A size: 512.1GB
Partition: ID-1: / size: 19G used: 5.8G (33%) fs: ext4 dev: /dev/nvme0n1p3
           ID-2: /boot size: 465M used: 85M (20%) fs: ext4 dev: /dev/nvme0n1p2
           ID-3: /home size: 422G used: 177M (1%) fs: zfs dev: N/A
           ID-4: swap-1 size: 20.48GB used: 0.00GB (0%) fs: swap dev: /dev/nvme0n1p4
RAID:      No RAID devices: /proc/mdstat, md_mod kernel module present
Sensors:   System Temperatures: cpu: 55.5C mobo: N/A
           Fan Speeds (in rpm): cpu: N/A
Info:      Processes: 602 Uptime: 2 min Memory: 632.9/15936.5MB Init: systemd runlevel: 5
           Client: Shell (bash) inxi: 2.2.35

**Comment by OK2AMA** [comment]
Hi, I have same problem. ( Ubuntu 16.04, new instalation, and I install cinnamon - it did't working - also high consumption RAM/SWAP and CPU usage ).  I installed also LXDE and It working ok.

**Comment by Wiadomy** [comment]
Hi, the same here.
Linux Mint 18.1, installed few months ago.
Every time after few hours from startup, process "cinnamon --replace" starts to eat more than 90% of ram (15GB). Cinnamon freezes quickly and the only way left is restart. If I try to kill proccess, cinnamon crashes. I'm using only cinnamon.

**Comment by myb120** [comment]
I have a similar problem by it's with cinnamon creating multiple processes. 9 of which are at top of cpu usage. The top one using ~500% of cpu (I've got 8 cores). The remaining 8 cinnamon process using between 75-35% of cpu.

I have been able to kill the processes and cinnamon --replace & then cpu usage returns to normal but returns when I reboot. Could this be related?

**Comment by clefebvre** [comment]
We believe this issue is fixed. Please test against the latest Cinnamon version (3.6). If the issue happens again, create a new issue.
