### ISSUE TITLE
 Add 'shut down laptop when lid is closed' option to Cinnamon

### ISSUE THREAD

**Issue by freemangilgamesh** [linuxmint/cinnamon#6382]
Unlike mate, Cinnamon lack the option to 'shut down laptop when lid is closed' and it is very useful when someone is in a hurry. I suggest you add it to Cinnamon power setting.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
