### ISSUE TITLE
Applet from the tutorial Cinnamon/docs/reference/cinnamon-tutorials/write-applet.xml not working

### ISSUE THREAD

**Issue by hethkar** [linuxmint/Cinnamon#6389]
https://github.com/linuxmint/Cinnamon/blob/master/docs/reference/cinnamon-tutorials/write-applet.xml
I followed the instructions from - http://developer.linuxmint.com/reference/git/cinnamon-tutorials/write-applet.html and copied the code for the applet. 
After adding the applet to the panel and when i click on it i get - Execution of x Failed : Cannot convert string to array of 'utf8' 
Also is it supposed to show an icon in the panel ? I get a empty space for the panel icon.
Desktop: Cinnamon 3.2.7  Distro: Linux Mint 18.1 Serena

**Comment by Odyseus** [comment]
@hethkar.

Already reported (#6329) and fixed. You can see the corrected version of the documentation by opening **Devhelp** (installed by the package **devhelp** on Linux Mint). I don't know if this fix is in Cinnamon 3.2.7. I'm using Cinnamon 3.2.8 from this repository.

**Comment by JosephMcc** [comment]
As noted, this is already fixed on git master.
