### ISSUE TITLE
can't disable a keyboard shortcut on linux mint 18

### ISSUE THREAD

**Issue by gaboalonso** [linuxmint/cinnamon#6390]
Hello all,

Previously I've added a keyboard shortcut (ctrl + shift + t) to toggle the touchpad on and off using Menu -> Keyboard -> Shortcuts -> System -> Touchpad on/off. I'm trying to disable them because it interferes with browser's reopen tab shortcut. Tried to disable them with backspace. It shows "unassigned" but they are still active. Even tried setting a different shortcut, so now I have a new one but the old ones are still working.

Tried restarting Cinnamon, and then restarting the machine, nothing works.

System Specs:

OS:
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=18.1
DISTRIB_CODENAME=serena
DISTRIB_DESCRIPTION="Linux Mint 18.1 Serena"
NAME="Linux Mint"
VERSION="18.1 (Serena)"
ID=linuxmint
ID_LIKE=ubuntu
PRETTY_NAME="Linux Mint 18.1"
VERSION_ID="18.1"
HOME_URL="http://www.linuxmint.com/"
SUPPORT_URL="http://forums.linuxmint.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/linuxmint/"
VERSION_CODENAME=serena
UBUNTU_CODENAME=xenial
64 bit

System:
	Manufacturer: Dell Inc.
	Product Name: Inspiron 5558
	Version: 01

Thanks and regards,
Gabriel.

**Comment by icarter09** [comment]
@gaboalonso are you still experiencing this issue?
