### ISSUE TITLE
Add different icon for when connected to VPN while on wifi

### ISSUE THREAD

**Issue by RayBB** [linuxmint/cinnamon#6391]
Currently on Linux mint there are two different icons for when you're connected via Ethernet or via wifi.
Once you connect to a VPN it just shows the Ethernet icon with a lock regardless of weather you're on wifi or a wired connection. 
It would be nice to add a wifi icon with a lock like Ubuntu has.

![image](https://cloud.githubusercontent.com/assets/921217/24579711/6c17e740-16c8-11e7-9e8b-091d32eb61b4.png) ![image](https://cloud.githubusercontent.com/assets/921217/24579729/af086b92-16c8-11e7-807e-db88a21ceea1.png)

**Comment by NicoWeio** [comment]
> It would be nice to add a wifi icon with a lock like Ubuntu has.

As far as I can tell, Ubuntu (GNOME) doesn't have that either:
[Their icon theme](https://packages.ubuntu.com/xenial/all/gnome-icon-theme-symbolic/filelist ) only has 'vpn' and 'vpn-acquiring'.
I like the idea, though.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
