### ISSUE TITLE
When i open applet on bar i can't see preview window's application

### ISSUE THREAD

**Issue by pyroxar** [linuxmint/Cinnamon#6396]
When i open menu or calendar applet or others applets on taskbar in cinnamon i can't see preview open applications.
Normally after mouse roll-over on application i can see its window preview.

**Comment by sandeeproy** [comment]
Ok, here to solve the window preview.
Goto Menu < Preferences < Applets < Search " Window List" < Right Click on "Window List"; Select "Configure" < Enable "Show window thumbnails on hover"

May be that's what you was looking for, I'm not sure though.

**Comment by JosephMcc** [comment]
This isn't a bug. When you have a menu open, either a cinnamon menu, or an application menu, it has the focus/grab. That's just the way it works.

**Comment by pyroxar** [comment]
I think that when i have opened applet in cinnamon, this should show window thumbnails on hover.
Opening applet can't blocked other applets.
