### ISSUE TITLE
Network Settings panel does not grow vertically when resized

### ISSUE THREAD

**Issue by nick-s-b** [linuxmint/Cinnamon#6400]
Steps to reproduce:

1) Open System Settings and choose Network
2) Scale the window to expand it
3) Notice that the left column, where network interfaces, VPNs reside, does not grow vertically while the right one does grow horizontally.

Expected behavior:
Grow the left column vertically to expose more interfaces. When you have a lot of them, you'd expect that resizing the window would show more of them and not just show the blank background.

Thank you so much!

Versions:

      Kernel: 4.10.6-1-ARCH x86_64 (64 bit) Desktop: Cinnamon 3.2.8  Distro: Arch Linux

**Comment by JosephMcc** [comment]
Think this is the same problem as https://github.com/linuxmint/Cinnamon/issues/4886
