### ISSUE TITLE
SMB bookmarks are not opend from places menu if not aready mounted

### ISSUE THREAD

**Issue by daschuer** [linuxmint/cinnamon#6406]
I have notice this some times ago and the issue still persists in Mint 18.1. 

A workaround is to register nemo as file uri handler 

```
xdg-mime default nemo.desktop x-scheme-handler/file
``` 

this should not be required

**Comment by daschuer** [comment]
What was the issue here for closing it?

**Comment by icarter09** [comment]
@daschuer did your PR not fix this issue?

**Comment by daschuer** [comment]
Ups, of cause. Sorry for the noise.

**Comment by icarter09** [comment]
@daschuer no worries. If the PR didn't the issue, I would have reopened the ticket. Thanks for following up.
