### ISSUE TITLE
Window icons from panel colliding with applet icons in system tray

### ISSUE THREAD

**Issue by hethkar** [linuxmint/Cinnamon#6413]
I haven't counted the number of windows i opened but it was too many, and when that happened the icons from panel were moving behind the applet icons in the system tray.
Desktop: Cinnamon 3.2.7  Distro: Linux Mint 18.1 Serena
https://i.imgur.com/6Pow7F6.gif
https://i.imgur.com/gIUVZlS.png

**Comment by JosephMcc** [comment]
https://github.com/linuxmint/Cinnamon/issues/5042
