### ISSUE TITLE
After suspend desktop background missing

### ISSUE THREAD

**Issue by mikeglaz** [linuxmint/Cinnamon#6414]
I have Ubuntu 16.10 with Cinnamon 3.2.8-1~yakkety0.  After my laptop wakes up from suspend the desktop background is gone. I then have to go to Background -> Settings and set Picture aspect to 'No Picture' and then back to 'Centered'.  Also, the desktop freezes sometimes and I have to do a hard reboot.

**Comment by BZS008** [comment]
Same here, using Linux Mint 17 with Cinnamon 2.2.16. I am having this problem since I performed a driver update for my GeForce GTX 460M

**Comment by Hworden** [comment]
I'm seeing a similar issue on my desktop. Have you guys found a solution?

**Comment by leigh123linux** [comment]
Without logging I will be closing this report in seven days!
