### ISSUE TITLE
Autocompletion in Nemo's location bar should be case insensitive

### ISSUE THREAD

**Issue by rdiez** [linuxmint/Cinnamon#6416]
When autocompleting a file path in the location bar, the matching should be case-insensitive, like in Dolphin File Manager and many others. Or at least there should be an option to turn the matching to case insensitive.

I recently filed a similar bug for Thunar:
https://bugzilla.xfce.org/show_bug.cgi?id=12747
They have made a patch, which may give some insight about how to implement this.

**Comment by JosephMcc** [comment]
This belongs here: https://github.com/linuxmint/nemo/issues
