### ISSUE TITLE
remember windows order on workspaces

### ISSUE THREAD

**Issue by calestyo** [linuxmint/Cinnamon#6418]
Hey.

Windows, shown in the window list applet have some order. The user can drag & drop them in the window list (though that seems to be still buggy as well) and change that order.

However, when cinnamon e.g. crashes (and is restarted), then any changes to that order are lost and the windows return in the order (I assume) as they were created.

Would be nice, if the re-ordering is remembered.

Cheers,
Chris.

**Comment by JosephMcc** [comment]
I'm marking this as a feature request but I'm not sure if it's even possible. Even if we stored the order somehow in the window list it would be lost by a cinnamon restart.

**Comment by merli-matthews** [comment]
I would like this. I have different workspaces for different projects, with different windows open in each workspace. Would be GREAT to have them repopulate into the correct workspaces please :)

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.

**Comment by NikoKrause** [comment]
Try this: https://cinnamon-spices.linuxmint.com/applets/view/273
