### ISSUE TITLE
No printer settings (Cinnamon running in Fedora 25)

### ISSUE THREAD

**Issue by bionan** [linuxmint/Cinnamon#6420]
The printer settings do not appear in the system settings. How to make them appear. I'm using CINNAMON in Fedora 25 (please, [see this image](http://picpaste.com/Selec____o_183-DCeVRm4M.png))
The printer settings appear in KDE e and Gnome.
Thank for any help.

**Comment by leigh123linux** [comment]
Install system-config-printer


```
sudo dnf install system-config-printer
```

**Comment by JosephMcc** [comment]
Can this be closed?

**Comment by leigh123linux** [comment]
@JosephMcc I believe it can.

@bionan  feel free to reopen if the above command doesn't sort your issue.

**Comment by bionan** [comment]
Thank you! It's worked.
