### ISSUE TITLE
Non-congruent Cinnamon screensaver and lockscreen

### ISSUE THREAD

**Issue by ahdr** [linuxmint/Cinnamon#6422]
The screensaver and lockscreen clock doesn't share the same position from the left edge so that it creates a uniform appearance. In LM 18.1 the new 3.2 screensaver has the clock shifted too far right. Additionally, the icon symbols for the 'unlock' and 'switch user' button lack inner spacing (padding) and should be scaled down.

**Comment by JosephMcc** [comment]
> The screensaver and lockscreen clock doesn't share the same position from the left edge so that it creates a uniform appearance.

You lost me here. You're talking like there are two different things.

**Comment by leigh123linux** [comment]
@JosephMcc  neither are related to cinnamon, can we close it?

**Comment by JosephMcc** [comment]
Probably. It should really be on Cinnamon screensaver. I was just a bit confused on what was even meant by that sentence. I didn't want to have it moved and then turn around and close it on cinnamon-screensaver :)

**Comment by ahdr** [comment]
@JosephMcc They are
