### ISSUE TITLE
Inconsistent FN Shortcut behavior with focused menus

### ISSUE THREAD

**Issue by linusg** [linuxmint/cinnamon#6425]
Recently, I noticed some in my opinion strange behavior in Cinnamon. When I use the FN shortcuts for example to set the volume or display brightness of my laptop, this does not work the same way for all applications when the focus is on some menu (the one just below the window top frame, e.g. File, Edit, etc.). What I found so far:

Rhytmbox, Nemo, PyCharm, Terminal, Gimp, Pix, Cheese, LMMS, VLC, Inkscape, FileZilla, ...most applications:

- Menu stays open and focused and shortcut press is ignored

Firefox, editor that ships with Wine:

- Menu gets closed and shortcut action is performed

Electron-based applications, e.g. Skype for Linux, Atom:

- Menu stays open and focused and shortcut action is performed

Are all of these desired behavior? I think with the electron apps it's fine since they use some kind of self-drawn menu, it does not match the window theme. But when using a 'native' application, I find it rather confusing that the FN shortcuts are not performed when a menu is open. And what about FF? The menu there looks quite native, but it closes when open and a FN shortcut is performed.

Hopefully someone can clarify this!

```
$ cinnamon --version
Cinnamon 3.2.7
```

**Comment by Vahan86** [comment]
I have similar issue with FN shortcuts to set display brightness when Menu is open. In this case the FN shortcuts don't work, at the same time the FN shortcuts to set the volume work as expected.
Cinnamon 3.2.7

**Comment by linusg** [comment]
It's been one year, still experiencing this in the newest Cinnamon, updates installed. Will anyone look into it probably this year? :confused:

**Comment by Vahan86** [comment]
> I have similar issue with FN shortcuts to set display brightness when Menu is open. In this case the FN shortcuts don't work, at the same time the FN shortcuts to set the volume work as expected.
> Cinnamon 3.2.7

The issue still exists in Cinnamon 4.2.4
