### ISSUE TITLE
NetworkManager not shows connections

### ISSUE THREAD

**Issue by igordovgaluk** [linuxmint/cinnamon#6429]
NetworkManager applet not shows connections. See the screenshot. The laptop is connected to Ethernet and WiFi. Cinnamon 3.2.7
![image](https://cloud.githubusercontent.com/assets/4215041/24900106/614e447c-1eab-11e7-96a8-b47044f4c4c5.png)

Network Settings show all connection properly.

Steps:
1. Move the panel to secondary monitor (in my case external one connected to laptop)
2. Turn off the  secondary monitor
3. Turn on the  secondary monitor

**Comment by BandonRandon** [comment]
I've also experienced this when moving between networks. (ie, from coffee shop back to home) without doing a full reboot of my machine.  My common solution has been to kill and then relaunch network manager.

**Comment by Blabeen** [comment]
Similar here, but in my case after I close then open the lid (Turn off/on the monitor) Wifi is off, icon shows disconnected network  and unable to turn on Wifi again without rebooting. Dell 7537

**Comment by CottonEaster** [comment]
I have this situation too - in that, when I move my laptop from place to place (without a reboot), the list of available networks is greatly impoverished. (The problem is slightly exacerbated by #7094.)

**Comment by Vahan86** [comment]
@igordovgaluk, is this still an issue in Cinnamon 4.4?

**Comment by igordovgaluk** [comment]
@Vahan86 I do not use Cinnamon anymore

**Comment by Vahan86** [comment]
@igordovgaluk, thanks for your reply.

@BrookeDot, @Blabeen, is this still an issue for you with Cinnamon 4.4?
