### ISSUE TITLE
Add "running indicator" to starter icons in panel

### ISSUE THREAD

**Issue by mabod** [linuxmint/Cinnamon#6433]
I was using plank until recently. But now I started to use a vertical cinnamon panel instead. There is one feature from plank which I am missing though: An indicator next to the starter icon of an application that is showing if the application is already running. In plank this indicator is a small dot left hand side of the icon. Multiple dots for multiple running instances of the application. I believe Unity has something similar.

This indicator comes in very handy. It prevents me from starting the app twice instead of bringing the existing instance to the front.

Another nice to have:

Along with this "running indicator" plank is also by default not starting a new instance when the application is already running. Instead it just brings the existing instance to the front. To start a new instance you need to hold the shift key while clicking the starter. 

Please see this screenshot as example: 
https://media-cdn.ubuntu-de.org/wiki/attachments/18/50/plank_nontransparent.png

Matthias

**Comment by JosephMcc** [comment]
A dock behaves differently out of need. We have a separate panel-launcher and window-list applet. A dock does not. This is the sort of thing probably better handled by third party xlet.
