### ISSUE TITLE
WiFi Connect button does not actually connect

### ISSUE THREAD

**Issue by igordovgaluk** [linuxmint/cinnamon#6434]
On a Network settings dialog WiFi Connect button for a visible network, that was not saved/connected, does not actually connect. Although the connect progress indicator starts spinning.

Network administration reported that there was no connect request sent to the network infrastructure.

I was able to connect to the network by using 'Connect to a Hidden Network' and typing SSID and Auth parameters (WPA2 Ent) manually.

Cinnamon 3.2.7, kernel 4.4.0-66-generic

**Comment by Chris00** [comment]
I have the same issue with *new networks*.  If I switch to, say, Gnome and connect, then I can also connect in Cinnamon.  Connecting to new networks does not happen so often but, when one needs to, this bug is very annoying.

Cinnamon 3.2.7, kernel 4.11.6

**Comment by wesdawg** [comment]
https://github.com/linuxmint/Cinnamon/issues/6215

**Comment by dstathis** [comment]
I have also run in to this problem. I am running cinnamon 3.6.6 on fedora 27.

When I click a network to attach to, there is no visible indication that anything at all happened. If I log out, log in to gnome, then log back in to cinnamon, everything works.

**Comment by leigh123linux** [comment]
@dstathis Your issue isn't related and will be fixed in cinnamon-3.6.6-10.fc27

**Comment by leigh123linux** [comment]
@dstathis  Can you test https://koji.fedoraproject.org/koji/buildinfo?buildID=1006242 (cinnamon-3.6.6-10.fc27)

**Comment by dstathis** [comment]
@leigh123linux That one works thanks!

**Comment by Chris00** [comment]
FYI, the issue persists in Cinnamon 3.8.8.

**Comment by icarter09** [comment]
@Chris00 are you still experiencing this issue?

**Comment by Chris00** [comment]
I'll try to check ASAP (I do not connect so much often to new networks).

**Comment by Chris00** [comment]
I now run Cinnamon 4.2.4.  I checked with a _WAP2 Personal_ network and it works fine.  I'll check with a _WPA2 Enterprise_ network soon.

**Comment by Chris00** [comment]
Tested with _WPA Entreprise_ and, besides the fact that the network settings panel opens and one has to select again the access point to connect, the right window opens to fill the authentication credentials and then the connection succeeds.

**Comment by icarter09** [comment]
@Chris00 thanks for following up on this.
