### ISSUE TITLE
Keyboard layout for Menu same as in last application

### ISSUE THREAD

**Issue by igordovgaluk** [linuxmint/cinnamon#6435]
keyboard layout for Menu is switched to the one used in the most recently used application.
Cinnamon 3.2.7
![image](https://cloud.githubusercontent.com/assets/4215041/24950908/4580ef58-1f7b-11e7-84e2-3e3c9c0a86c5.png)

Use case scenario:
user enters text using local language (language 2) in a text editor. Then opens a menu to start new application.
Most application titles are in English. So user needs to switch to English (lang 1). In most cases wrong (unexpected) layout is noticed after the typing has started. So the user should clear the entered text, change the language, and type again.

As a used I expect menu will use its own last used layout.

**Comment by tallanvor** [comment]
+1 
I have same bug.
Debian 8 / Cinnamon 2.2.16
Antegros Linux / Cinnamon 3.4.2

**Comment by tallanvor** [comment]
Any news?

**Comment by rizado** [comment]
+1
Mint Cinnamon 18.2, Cinnamon 3.4.6.

**Comment by icarter09** [comment]
#6344

**Comment by icarter09** [comment]
Please troubleshoot and find the exact cause of the problem. You can reopen the issue if the responsible component proves to be Cinnamon.

http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/.
