### ISSUE TITLE
Time Display With Vertical Taskbar

### ISSUE THREAD

**Issue by inferno596** [linuxmint/Cinnamon#6437]
When I have the taskbar on vertically, on the left or right side of my screen, the clock doesn't fit onto the taskbar, one digit is cut off, and there's no way to change the time size or increase the length of the taskbar. Picture attached. I reproduced this with and without UI scaling on both a 4k and 1080p monitor. Not showing the 0 before the 6 would also be highly appreciated. 

![screenshot from 2017-04-13 18-36-26](https://cloud.githubusercontent.com/assets/19422700/25027120/5f5efea8-2078-11e7-9b6d-7dce41665b8d.jpg)

**Comment by JosephMcc** [comment]
https://github.com/linuxmint/Cinnamon/issues/6137

**Comment by justinkterry** [comment]
Why can't you just change : in the clock strftime time to \n and vice versa when going from vertical to horizontal? Other people have been complaining about this, this is a complete fix for the problem and would be very easy to implement.
