### ISSUE TITLE
window-list: inactive at terminal edge if in a panel with border on the opposing side

### ISSUE THREAD

**Issue by brownsr** [linuxmint/Cinnamon#6440]
Issue found in master, not checked to see if present in production 3.2.
If you have a panel with border on the inward facing edge, then the terminal edge side becomes unreactive in the window list.  There appears to be a strip of unreactive pixels at the edge of the screen.

**Comment by JosephMcc** [comment]
Making sure I understand correctly. If say you have a panel at the bottom of the screen. It has a border on the top edge of the panel. Then it leaves an apparent border at the bottom that does react to clicks?

**Comment by brownsr** [comment]
It leaves an unreactive strip, yes. Perhaps I should post a picture, that
might be clearer.

**Comment by JosephMcc** [comment]
Could you post an example of the css you're using?

**Comment by brownsr** [comment]
Will do that tonight , at work right now

**Comment by brownsr** [comment]
.panel-top {
    border-left : 1px;
    border-right: 1px;
    border-top: 0px;
    border-bottom: 1px;
    border-color: rgba(179,0,0,0.8);
    background-gradient-direction: horizontal;
    background-gradient-start: rgba(51,51,51,1);
    background-gradient-end: rgba(51,51,51,0.8);
	border-radius: 0px 0px 8px 8px;
}
.panel-bottom {
    border-left : 1px;
    border-right: 1px;
    border-top: 1px;
    border-bottom: 0px;
    border-color: rgba(179,0,0,0.8);
    background-gradient-direction: horizontal;
    background-gradient-start: rgba(51,51,51,1);
    background-gradient-end: rgba(51,51,51,0.8);
    border-radius: 8px 8px 0px 0px;

}
.panel-left {
    margin-top: 30px;
    margin-bottom: 30px;
    border-left : 0px;
    border-right: 1px;
    border-top: 1px;
    border-bottom: 1px;
    border-color: rgba(179,0,0,0.8);
    background-gradient-direction: vertical;
    background-gradient-start: rgba(51,51,51,1);
    background-gradient-end: rgba(51,51,51,0.8);
    border-radius: 0px 8px 8px 0px;
}
.panel-right {
    margin-top: 30px;
    margin-bottom: 30px;
    border-left : 1px;
    border-right: 0px;
    border-top: 1px;
    border-bottom: 1px;
    border-color: rgba(179,0,0,0.8);
    background-gradient-direction: vertical;
    background-gradient-start: rgba(51,51,51,1);
    background-gradient-end: rgba(51,51,51,0.8);
    border-radius: 8px 0px 0px 8px;
}

Theme BelaLugosi.
