### ISSUE TITLE
Some text becomes invisible in High Contrast mode

### ISSUE THREAD

**Issue by nkreer** [linuxmint/Cinnamon#6451]
![virtualbox_linux mint_16_04_2017_12_11_12](https://cloud.githubusercontent.com/assets/15277434/25070434/50e289da-229e-11e7-88ef-b747b22ffdf0.png)

**Comment by leigh123linux** [comment]
If mintupdate has missing text it's mintupdate issue.

https://github.com/linuxmint/mintupdate/issues

**Comment by nkreer** [comment]
@leigh123linux I believe it's a cinnamon edition, the text is, of course, still there when the element isn't selected.
