### ISSUE TITLE
Screenshot area too large with GNOME apps

### ISSUE THREAD

**Issue by theel0ja** [linuxmint/Cinnamon#6455]
Taking screenshots with GNOME Screenshot / Scrot have problem taking screenshots of GNOME Apps (like GNOME Calculator). 

![GNOME Calculator](https://cloud.githubusercontent.com/assets/5832930/25097939/486bf298-23af-11e7-81c2-12dcfb7e6a52.png)

Ubuntu GNOME haven't this problem.

EDIT: Problem occurs also on Ubuntu upstream's `gnome-screenshot`.
EDIT: Unity [don't have this problem](https://www.kotilinux.org/wp-content/uploads/2017/02/gnome-tweak-tool-Ulkoasu.png), so it will not be "only non-GNOME desktop environment problem".
EDIT: Ubuntu MATE has the problem.

**Comment by theel0ja** [comment]
Seems to be fixed on 19.1, at least for the calculator.

![screenshot_20181227_180010](https://user-images.githubusercontent.com/5832930/50486162-43c8f800-0a01-11e9-828a-a173c51789c9.png)

**Comment by jaszhix** [comment]
Fixed in 4.0.
