### ISSUE TITLE
Wrong path in cinnamon-polkit-gnome-authentication-agent-1.desktop on Stretch

### ISSUE THREAD

**Issue by Trucido** [linuxmint/Cinnamon#6463]
This probably isn't a bug for current LMDE2 or LinuxMIit but is something to be aware of on subsequent releases and perhaps put in place some better future proofing since the Gnome folks always seem to be breaking stuff.

Problem:
In Debian/testing(stretch) a race condition occurs with cinnamon-session starting up before `polkit-gnome-authentication-agent-1` is loaded due to a exec path change. This causes early services to not connect properly. This is sort of a bug in cinnamon because it provides the file `cinnamon-polkit-gnome-authentication-agent-1.desktop` which it calls during it's start up.
Details:
-display manager starts up (lightdm in this case)
-cinnamon-session loads
-cinnamon attempts to early-launch `/usr/lib/polkit-gnome-authentication-agent-1` but file not found.
-Other services like gnome-keyring, gvfs, etc start up but some before the polkit agent is loaded (the gnome one is in xdg/autostart but it needs to be loaded early in the session.)

Solution:
`"Exec=/usr/lib/polkit-gnome-authentication-agent-1"` needs to be changed to the new location:
`"Exec=/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1"`

Either cinnamon should fork it's own polkit agent, or somehow future proof any subsequent path changes (perhaps execute a script to somehow find it's location).

Further details:
Debian 9 "Stretch" ("testing", currently feature frozen to be stable in the near future)
```
Package: cinnamon
Version: 3.2.7-2
```
```
Package: cinnamon-session
Version: 3.2.0-4
```
```
Package: cinnamon-settings-daemon
Version: 3.2.1-3
```
```
Package: cinnamon-desktop-data
Version: 3.2.4-4
```
etc, the list goes on but that's probably more than enough details. I'll report this to Debian packagers as well.

**Comment by leigh123linux** [comment]
This is a Debian issue

https://anonscm.debian.org/git/pkg-cinnamon/cinnamon.git/tree/debian/patches/add_policykit-1-gnome_to_session

**Comment by leigh123linux** [comment]
@maxyz @marga-debian 

https://anonscm.debian.org/git/pkg-cinnamon/cinnamon.git/tree/debian/patches/add_policykit-1-gnome_to_session#n104

https://anonscm.debian.org/cgit/pkg-utopia/policykit-gnome.git/tree/debian/polkit-gnome-authentication-agent-1.desktop

**Comment by marga-debian** [comment]
Hi!

In the future, please report bugs like this through the Debian bug interface.

There was a small mess with the polkit agent location in stretch, in which the GNOME maintainers changed its location and made the agent not start inside GNOME, without warning us.  After we discussed this, this was reverted. But unfortunately we failed to see the note that the package with the right location had been uploaded and so we failed to drop our patch, which ended up trying to start a service that is no longer there.

I will make an upload that reverts our patch and just lets the GNOME agent start.

The part that I'm less sure about is how is it that this is causing a raise condition.  The polkit agent is started automatically, what problems are you actually seeing?
