### ISSUE TITLE
"apt-key remove" functionality doesn't seem to work in Software Sources 

### ISSUE THREAD

**Issue by noreasternhumidity** [linuxmint/Cinnamon#6464]
Probably not a big issue, but I seemed to have a persistent key in my Software Sources / Authentication Keys manager.  I had installed the Opera web browser and then removed it.  There was a key left behind found and tried to remove using the Software Sources manager.  It looked like it was deleted, but then came back later. 

Then I found that the key hadn't been deleted at all (there were actually two of them), using "apt-key list".  In addition there are some other important Ubuntu keys which just don't show up in the Software Sources manager.

So if I have any issues or questions about keys on my system, I will probably be using the "apt-key list" and "apt-key remove" commands too.

**Comment by noreasternhumidity** [comment]
Okay, the "apt-key" list command doesn't permanently remove an authentication key either.  What did it for me was searching my HDD in Nemo for Opera files.  One of them was a text file that had a long encoded key in it.  After I deleted that file, the unwanted auth keys stayed away.

**Comment by noreasternhumidity** [comment]
One last thing - I've only had this happen with programs outside of the repository.  This happened with Opera (installed with a .deb file), and Bitcoin ([installed with a PPA](https://community.linuxmint.com/tutorial/view/903)).

**Comment by JosephMcc** [comment]
This repo is for Cinnamon specifically. This belongs here: https://github.com/linuxmint/mintsources/issues
