### ISSUE TITLE
Idea: Profiles (as in E17)

### ISSUE THREAD

**Issue by dalcde** [linuxmint/Cinnamon#647]
It would be nice to allow "profiles" as found in E17 (http://www.bodhilinux.com/e17guide/e17guideEN/profiles.html). By activating a profile, a pre-defined set of themes, applets and extensions and settings will be loaded. For example, there might be a "GNOME" profile to load certain themes, applets and extensions and then choose the "flipped" panel setting. This can be facilitated by a PPA by using suitable dependencies.

**Comment by Vahan86** [comment]
It would be nice to have this implemented. +1

**Comment by JosephMcc** [comment]
Thank you for your suggestion. See https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html for information on how we handle feature requests.

**Comment by timmie** [comment]
@JosephMcc 
seems that the development team will process the request.
Please also consider different energy profiles (balanced, performance, battery saver) as used by other operating systems.
