### ISSUE TITLE
Nvidia driver black screen can't login after installation

### ISSUE THREAD

**Issue by PIERREZZZZ7** [linuxmint/Cinnamon#6470]
A friend of mine just made a clean install of mint cinnamon and obviously it requires drivers now we both have almost no knowledge of linux so he went to drivers click on recommended driver for his 1070 nvidia applied and restarted. When he restarted all he gets is the nvidia screen He can't even reach the login screen.
He is not capable of opening his terminal 
He is not capable of logging in
He is capable of clicking ALT + CTRL things that would get TTY i think it's called sorry if i mess a couple of words it's been a long day like a login screen and he can't type anything and CTRL + ALT + F7 shows letters on his top left which he can use the directional keys sorry we are both big noobs and If someone can help out that would be great

**Comment by leigh123linux** [comment]
You need to ask on the forum as your issue isn't related to cinnamon.

https://forums.linuxmint.com/
