### ISSUE TITLE
When waking up from suspend the time shown by the calendar applet may take long to get updated

### ISSUE THREAD

**Issue by marga-debian** [linuxmint/Cinnamon#6473]
This is a difference I've noted in 3.2, but I'm not sure if it was already happening with 3.0 or not.

Sometimes, when coming back from suspend, the time displayed by the calendar applet on the panel can take very long to get updated.

I guess we are all pretty much used to the screensaver displaying the wrong time for a second right after waking up from suspend, but that one gets updated pretty quickly. The issue with the calendar applet can take very long to update, in the order of tens of seconds.

It's pretty confusing because it's so long that I can already be doing stuff (having forgotten that the machine is freshly woken up) and look at the time and see a completely different time and be like WAT?

It was reported to Debian at:
http://lists.alioth.debian.org/pipermail/pkg-cinnamon-team/attachments/20170322/7e695e4a/attachment.html

**Comment by marga-debian** [comment]
I just did a bunch of tests for this.  Out of 5 wake-ups, 3 were not visibly affected. One took around 11 seconds to update, updating around the :30 second, the last one took around 45 seconds to update, updating around the :45 second.  Given this, I'm not sure the second it updates matters at all.

**Comment by igordovgaluk** [comment]
@marga-debian i believe it is poor UX provided by the system when user needs to wait unknown period of time to get valid time stamp. It may not be important for the user the time to take a cup of coffee. But when user has a work use case (e.g. is waiting for a meeting at work) it is important to have correct time visualization all the time, immediately after resuming the device.

**Comment by mtwebster** [comment]
Looks to be fixed by the commits referenced here: https://github.com/linuxmint/Cinnamon/issues/6780#issuecomment-343608005
