### ISSUE TITLE
Save workspaces for next boot

### ISSUE THREAD

**Issue by alc59** [linuxmint/Cinnamon#6478]
Would it be possible to save my workspaces to be opened on boot
thank you
cinnamon 18.1 serena

**Comment by Wiadomy** [comment]
Agreed, that would be nice. Upvote.

**Comment by dynamikspeed** [comment]
I would like to see this too.

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
