### ISSUE TITLE
MTP-device problem

### ISSUE THREAD

**Issue by nerox8664** [linuxmint/cinnamon#6483]
I have default settings in 'Preferred applications' -> 'Devices' tab (~ i have russian locale) for MTP device -- 'Ask on connect'. But, when i plug my mtp device, nemo window is opening automatically without any question.

**Comment by icarter09** [comment]
@nerox8664 are you still experiencing this issue?

**Comment by Vahan86** [comment]
@icarter09, can we close this issue?
