### ISSUE TITLE
Cinnamon 3.2.8 - javascript doesn't work in Firefox or Chrome

### ISSUE THREAD

**Issue by jad3675** [linuxmint/cinnamon#6492]
This problem only appears to only occur on my main computer, Dell Inspiron 7378. This issue both in Fedora and Mint. Quite simply, any controls rendered in javascript don't work. Page load fine. 

I first noticed this while using the web GUI of our corporate monitoring platform, sliders to adjust a viewable timeslice do not slide.
This issue is also apparent on the website fc-moto.de. There's a drop down menu on the right hand side of the page to choose language and country. Neither of these controls work in Cinnamon on my inspirion using either Chrome, Firefox or Vivaldi. They do, however, work in KDE and Mate using the same browsers.

**Comment by leigh123linux** [comment]
It works ok here on my F26 development install

![screenshot from 2017-04-28 15-38-21](https://cloud.githubusercontent.com/assets/1299302/25533599/153873c4-2c29-11e7-997c-77a6fe254632.png)

```
$ inxi -GS
System:    Host: localhost.localdomain Kernel: 4.11.0-0.rc7.git0.1.fc26.x86_64 x86_64 (64 bit)
           Desktop: Cinnamon 3.2.8  Distro: Fedora release 26 (Twenty Six)
Graphics:  Card: NVIDIA GK106 [GeForce GTX 660]
           Display Server: Fedora X.org 119.3 drivers: nvidia (unloaded: modesetting,fbdev,vesa,nouveau)
           Resolution: 3840x2160@60.00hz
           GLX Renderer: GeForce GTX 660/PCIe/SSE2
           GLX Version: 4.5.0 NVIDIA 381.09
```
```
$ rpm -qa cinnamon\* cjs\* muffin\* |sort
cinnamon-3.4.0-0.2.20170426git067e1da.fc26.x86_64
cinnamon-applet-blueberry-1.1.10-3.fc26.noarch
cinnamon-control-center-3.4.0-0.1.20170420gitf992a30.fc26.x86_64
cinnamon-control-center-filesystem-3.4.0-0.1.20170420gitf992a30.fc26.x86_64
cinnamon-desktop-3.4.0-0.1.20170421git75d297a.fc26.x86_64
cinnamon-desktop-devel-3.4.0-0.1.20170421git75d297a.fc26.x86_64
cinnamon-menus-3.2.0-2.fc26.x86_64
cinnamon-menus-devel-3.2.0-2.fc26.x86_64
cinnamon-screensaver-3.4.0-0.1.20170421git358369e.fc26.x86_64
cinnamon-screensaver-unsupported-3.4.0-0.1.20170421git358369e.fc26.noarch
cinnamon-session-3.4.0-0.1.20170423gitd87d97d.fc26.x86_64
cinnamon-settings-daemon-3.4.0-0.6.20170423git358e90c.fc26.x86_64
cinnamon-settings-daemon-devel-3.4.0-0.6.20170423git358e90c.fc26.x86_64
cinnamon-themes-2016.12.07-2.fc26.noarch
cinnamon-translations-3.2.2-2.fc26.noarch
cjs-3.4.0-0.1.20170426git16347ea.fc26.x86_64
cjs-devel-3.4.0-0.1.20170426git16347ea.fc26.x86_64
muffin-3.2.1-2.fc26.x86_64
muffin-devel-3.2.1-2.fc26.x86_64
```

**Comment by jad3675** [comment]
Thanks, I'll try it from F26 then and post the results.

Here's what I'm currently running on F25
System:    Host: agostini Kernel: 4.10.11-200.fc25.x86_64 x86_64 (64 bit) Desktop: Cinnamon 3.2.8
           Distro: Fedora release 25 (Twenty Five)
Graphics:  Card: Intel Device 5916
           Display Server: Fedora X.org 119.3 drivers: modesetting,intel (unloaded: fbdev,vesa)
           Resolution: 1920x1080@60.05hz, 1920x1080@60.00hz, 1920x1080@60.00hz
           GLX Renderer: Mesa DRI Intel HD Graphics 620 (Kabylake GT2) GLX Version: 3.0 Mesa 13.0.4

cinnamon-3.2.8-18.fc25.x86_64
cinnamon-applet-blueberry-1.1.10-3.fc25.noarch
cinnamon-control-center-3.2.1-1.fc25.x86_64
cinnamon-control-center-filesystem-3.2.1-1.fc25.x86_64
cinnamon-desktop-3.2.4-1.fc25.x86_64
cinnamon-menus-3.2.0-1.fc25.x86_64
cinnamon-screensaver-3.2.14-0.4.20170308git39da3f0.fc25.x86_64
cinnamon-session-3.2.0-1.fc25.x86_64
cinnamon-settings-daemon-3.2.1-1.fc25.x86_64
cinnamon-translations-3.2.2-1.fc25.noarch
cjs-3.2.0-1.fc25.x86_64
muffin-3.2.1-1.fc25.x86_64

**Comment by leigh123linux** [comment]
F25 also works

```
$ inxi -GS
System:    Host: localhost.localdomain Kernel: 4.10.12-200.fc25.x86_64 x86_64 (64 bit)
           Desktop: Cinnamon 3.2.8  Distro: Fedora release 25 (Twenty Five)
Graphics:  Card: NVIDIA GK106 [GeForce GTX 660]
           Display Server: Fedora X.org 119.3 drivers: nvidia (unloaded: modesetting,fbdev,vesa,nouveau)
           Resolution: 3840x2160@60.00hz
           GLX Renderer: GeForce GTX 660/PCIe/SSE2
           GLX Version: 4.5.0 NVIDIA 375.39
```
```
$ rpm -qa cinnamon\* cjs\* muffin\* |sort
cinnamon-3.2.8-18.fc25.x86_64
cinnamon-applet-blueberry-1.1.10-3.fc25.noarch
cinnamon-control-center-3.2.1-1.fc25.x86_64
cinnamon-control-center-devel-3.2.1-1.fc25.x86_64
cinnamon-control-center-filesystem-3.2.1-1.fc25.x86_64
cinnamon-desktop-3.2.4-1.fc25.x86_64
cinnamon-desktop-devel-3.2.4-1.fc25.x86_64
cinnamon-menus-3.2.0-1.fc25.x86_64
cinnamon-menus-devel-3.2.0-1.fc25.x86_64
cinnamon-screensaver-3.2.14-0.4.20170308git39da3f0.fc25.x86_64
cinnamon-screensaver-unsupported-3.2.14-0.4.20170308git39da3f0.fc25.noarch
cinnamon-session-3.2.0-1.fc25.x86_64
cinnamon-settings-daemon-3.2.1-1.fc25.x86_64
cinnamon-settings-daemon-devel-3.2.1-1.fc25.x86_64
cinnamon-translations-3.2.2-1.fc25.noarch
cjs-3.2.0-1.fc25.x86_64
cjs-devel-3.2.0-1.fc25.x86_64
muffin-3.2.1-1.fc25.x86_64
muffin-devel-3.2.1-1.fc25.x86_64
```

**Comment by jad3675** [comment]
No dice on Fedora 26. Same issue on the same hardware. Is this is a graphics driver issue? How can I troubleshoot further?

John

**Comment by xephon2** [comment]
@jad3675 Any messages in the browser console (Press **F12** and reload page)?

**Comment by jad3675** [comment]
Great idea.

From Chrome that doesn't work:
![image](https://cloud.githubusercontent.com/assets/928013/25909165/44b5d29a-357a-11e7-9552-c383fdc6b6f6.png)


From Chrome on a Win10 laptop that does work:
![image](https://cloud.githubusercontent.com/assets/928013/25909186/58b7288e-357a-11e7-862b-cfee497f0664.png)

**Comment by icarter09** [comment]
We believe this issue is fixed. Please test against the latest Cinnamon version (4.2). 

If the issue happens again, create a new issue and add the output of "cinnamon-settings sound".
