### ISSUE TITLE
I cannot disable hibernate on my 64-bit Linux Mint 18.1 KDE desktop system

### ISSUE THREAD

**Issue by otto9G9otto** [linuxmint/Cinnamon#6493]
I tried to disable hibernate by going to System Settings/Power Management and clearing the box for "suspend session".  I also un-checked the Screen Energy Saving box. My system still goes into hibernation after one hour. I also tried executing the script described [here](https://sites.google.com/site/easylinuxtipsproject/bugs#TOC-Disable-hibernation-suspend-to-disk-only-necessary-in-Linux-Mint-) in terminal, but got the following error message:
`mv: cannot stat '/etc/polkit-1/localauthority/50-local.d/com.ubuntu.enable-hibernate.pkla': No such file or directory
`

**Comment by leigh123linux** [comment]
If you have a kde issue file the report at ubuntu launchpad or whatever they call there bugtracker!
