### ISSUE TITLE
URL shortcut not visibles in desktop

### ISSUE THREAD

**Issue by bionan** [linuxmint/Cinnamon#6496]
When dragging to the desktop a url from the address bar of a browser the shortcut of that address is not visible. However when opening the desktop through Nemo it turns out that the shortcut has been created.
I am using Cinnamon 3.2.8 on Fedora 25.

**Comment by irishbandit** [comment]
Seeing the same thing with regular files on desktop and application shortcuts. 
org.gnome.Calculator.desktop
inxi -Fxxx
Desktop: Cinnamon 3.4.0 (Gtk 3.22.11) dm: lightdm Distro: Ubuntu 17.04

see also post
https://github.com/linuxmint/nemo/issues/1490

**Comment by mtwebster** [comment]
880502f2320895a8c
