### ISSUE TITLE
"The name org.cinnamon.SettingsDaemon was not provided by any .service files"

### ISSUE THREAD

**Issue by telmotrooper** [linuxmint/Cinnamon#6509]
Since one my last full system updates on Arch/Antergos my Cinnamon suddenly started showing some ackward issues.

1. My desktop background is gone and all it shows is a black filling the screen. I can even click other backgrounds on 'Change Desktop Background' but nothing happens when I click them.

2. I can't open my 'Power Management' dialog. If I run 'cinnamon-settings' and click the option the console prints: 

>[telmo@Telmo-PC ~]$ cinnamon-settings
>Loading Power module
>Traceback (most recent call last):
>  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 552, in button_press
>    self.side_view_nav(widget, None, category)
>  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 112, in side_view_nav
>    self.go_to_sidepage(cat, filtered_path)
>  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 125, in go_to_sidepage
>    sidePage.build()
>  File "/usr/share/cinnamon/cinnamon-settings/bin/SettingsWidgets.py", line 123, in build
>    self.module.on_module_selected()
>  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_power.py", line 115, in >on_module_selected
>    device_types = [x[UP_TYPE] for x in self.csd_power_proxy.GetDevices()]
>  File "/usr/lib/python2.7/site-packages/gi/overrides/Gio.py", line 172, in __call__
>    None)
>GLib.Error: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name >
>org.cinnamon.SettingsDaemon was not provided by any .service files (2)
>

3. When the screensaver is supposed to show up, the screen goes all black instead.

Does anyone have any ideia what might be happening? Oh, I forgot to mention I have a NVIDIA card and I currently have the NVIDIA 378.13-6 driver installed.

**Comment by itzexor** [comment]
Probably due to a partial upgrade. Not all of the components have been released for 3.4 yet.

**Comment by telmotrooper** [comment]
Nevermind, noticed some of my Cinnamon packages were taken from the Antergos repository and some from one of Arch's, so I just installed the most updated version of all Cinnamon components and it's back working.

**Comment by vasiliyb** [comment]
@telmotrooper i may have run into the same situation :(  do you mind sharing the apt commands you ran to resolve?  Thank you!

**Comment by telmotrooper** [comment]
@vasiliyb I actually use pacman instead of apt, just had to download all Cinnamon packages from the same repository (I had a few from 'antergos' and a few from 'community'.

It's probably not gonna help you, but I did the following:

> sudo pacman -S antergos/cinnamon
sudo pacman -S antergos/cinnamon-control-center
sudo pacman -S antergos/cinnamon-desktop
sudo pacman -S antergos/cinnamon-menus
sudo pacman -S antergos/cinnamon-screensaver
sudo pacman -S antergos/cinnamon-session
sudo pacman -S antergos/cinnamon-settings-daemon
sudo pacman -S antergos/cinnamon-translations

**Comment by devillarry** [comment]
i just upgraded my system 16.10 to 17.04 . 
My desktop background is gone and all it shows is a black filling the screen. I can even click other backgrounds on 'Change Desktop Background' but nothing happens when I click them.

any solution?

**Comment by mcraveiro** [comment]
I had exactly the same problem on Debian testing; in my case, it seems ```cinnamon-settings-daemon``` is not starting when the session starts. I fixed it manually for now by running it on a terminal...

**Comment by sridharswain** [comment]
Delete `~/.config/autostart/cinnamon-settings-daemon-xrandr.desktop` and `restart`
`rm ~/.config/autostart/cinnamon-settings-daemon-xrandr.desktop` and restart

**Comment by therajat08** [comment]
> Delete `~/.config/autostart/cinnamon-settings-daemon-xrandr.desktop` and `restart`
> `rm ~/.config/autostart/cinnamon-settings-daemon-xrandr.desktop` and restart

please tell how do i restart this file

**Comment by NikoKrause** [comment]
Restart the computer
