### ISSUE TITLE
Cinnamon 3.4.0 crashes during auto-completion in run Dialog.

### ISSUE THREAD

**Issue by vladimir-didenko** [linuxmint/Cinnamon#6512]
After upgrading to 3.4.0 I can easily reproduce Cinnamon crash using follow steps:

1. Start run dialog using Alt + F2
2. In run dialog enter "gno".
3. Press tab. Command will be completed to "gnome-"
4. Press tab again. Cinnamon will crash.

**Comment by vladimir-didenko** [comment]
After downgrading to cjs-3.2 I doesn't see crash anymore.

**Comment by leigh123linux** [comment]
It works here, I have this warning

```
Cjs-Message: JS WARNING: [/usr/share/cinnamon/js/ui/runDialog.js 268]: reference to undefined property this._oldText
```

**Comment by JosephMcc** [comment]
Works fine here as well, no crashes. I get the same warning as leigh123linux. Please provide basic info like distro and where you installed Cinnamon from.

**Comment by vladimir-didenko** [comment]
I maintain Cinnamon in Alt Linux so I build it itself. 

I was able to bisect exact place in runDialog.js where crash happens - runDialog.js:103
```javascript
let fileEnum = file.enumerate_children('standard::name,standard::type', Gio.FileQueryInfoFlags.NONE, null);
```

Below is backtrace for crash but it doesn't look useful
```
Program received signal SIGSEGV, Segmentation fault.
0x00007f6e37b0050d in numAllocations (this=0x7ffdb3f6c6e0) at /usr/src/debug/libmozjs38-38.2.1/js/src/jit/JitFrames.cpp:2085
2085        return instruction()->numOperands();
#0  0x00007f6e37b0050d in numAllocations (this=0x7ffdb3f6c6e0) at /usr/src/debug/libmozjs38-38.2.1/js/src/jit/JitFrames.cpp:2085
#1  HandleExceptionIon (overrecursed=0x7ffdb3f6c5d6, rfe=0x7ffdb3f6cda0, frame=..., cx=0x92c030) at /usr/src/debug/libmozjs38-38.2.1/js/src/jit/JitFrames.cpp:449
#2  js::jit::HandleException (rfe=0x7ffdb3f6cda0) at /usr/src/debug/libmozjs38-38.2.1/js/src/jit/JitFrames.cpp:790
#3  0x00007f6e2ccd7162 in ?? ()
#4  0x0000000000000000 in ?? ()
```

**Comment by leigh123linux** [comment]
@vladimir-didenko install the cjs debug symbols as it might help the backtrace

**Comment by vladimir-didenko** [comment]
@leigh123linux  It is already installed but for some reason doesn't show cjs part of stack.

**Comment by vladimir-didenko** [comment]
I was able to identify that problem was in libmozjs38 build - you need to disable some optimizations when use latest gcc. If someone will face with the same problem there is a link showing how to fix problem

http://git.altlinux.org/people/cow/packages/?p=libmozjs38.git;a=commitdiff;h=c83815111c4c305ae0e49552ed37069b9824c55a
