### ISSUE TITLE
Screen brightness keyboard shortcuts not working

### ISSUE THREAD

**Issue by viggy96** [linuxmint/Cinnamon#6516]
Unable to control screen brightness via keyboard shortcuts. Using the slider in the power applet works, however. 

Ubuntu 16.04.2 LTS
Lenovo ThinkPad W540
Cinnamon 3.4.0

**Comment by leigh123linux** [comment]
Do you mean the dedicated laptop keys brightness control?

> brightness via keyboard shortcuts

**Comment by viggy96** [comment]
Not just the dedicated keys, no combination of keys works for changing the screen brightness. I have tried changing the key combination, then restarting Cinnamon, but it doesn't work. 

Also, this problem first appeared on the last Cinnamon 3.2.x version.

**Comment by bendovercz** [comment]
Can confirm same issue. Brightness control does not work with Fn + function key. However it does work in power applet slider. Reverting to 3.2.8 solves the issue.

**Comment by leonardoam** [comment]
Same issue here, but in my case it's the keyboard volume keys that doesn't work. I've tried reassigning the shortcuts again to these special functions and it still doesn't work.

It's also happening with the function keys for sleeping and blocking screen, and most of shortcuts (like Ctrl + Alt + L).

I'm running Antergos 16.7 and Cinnamon 3.4.0. My keyboard is a Dell WK636p

**Comment by morph027** [comment]
Same here....

Log while pressing keys:

```Mai 11 15:55:12 morph-envy kernel: atkbd serio0: Use 'setkeycodes e02b <keycode>' to make it known.
Mai 11 15:55:13 morph-envy kernel: atkbd serio0: Unknown key pressed (translated set 2, code 0xab on isa0060/serio0).
Mai 11 15:55:13 morph-envy kernel: atkbd serio0: Use 'setkeycodes e02b <keycode>' to make it known.
Mai 11 15:55:13 morph-envy kernel: atkbd serio0: Unknown key released (translated set 2, code 0xab on isa0060/serio0).
Mai 11 15:55:13 morph-envy kernel: atkbd serio0: Use 'setkeycodes e02b <keycode>' to make it known.
Mai 11 15:55:13 morph-envy kernel: atkbd serio0: Unknown key pressed (translated set 2, code 0xab on isa0060/serio0).
Mai 11 15:55:13 morph-envy kernel: atkbd serio0: Use 'setkeycodes e02b <keycode>' to make it known.
Mai 11 15:55:13 morph-envy kernel: atkbd serio0: Unknown key released (translated set 2, code 0xab on isa0060/serio0).
Mai 11 15:55:13 morph-envy kernel: atkbd serio0: Use 'setkeycodes e02b <keycode>' to make it known.
Mai 11 15:55:24 morph-envy blueman-mechanism[5401]: Exiting
Mai 11 15:56:09 morph-envy kernel: atkbd serio0: Unknown key pressed (translated set 2, code 0xab on isa0060/serio0).
Mai 11 15:56:09 morph-envy kernel: atkbd serio0: Use 'setkeycodes e02b <keycode>' to make it known.
Mai 11 15:56:09 morph-envy kernel: atkbd serio0: Unknown key released (translated set 2, code 0xab on isa0060/serio0).
Mai 11 15:56:09 morph-envy kernel: atkbd serio0: Use 'setkeycodes e02b <keycode>' to make it known.
Mai 11 15:56:10 morph-envy kernel: atkbd serio0: Unknown key pressed (translated set 2, code 0xab on isa0060/serio0).
Mai 11 15:56:10 morph-envy kernel: atkbd serio0: Use 'setkeycodes e02b <keycode>' to make it known.
Mai 11 15:56:10 morph-envy kernel: atkbd serio0: Unknown key released (translated set 2, code 0xab on isa0060/serio0).
Mai 11 15:56:10 morph-envy kernel: atkbd serio0: Use 'setkeycodes e02b <keycode>' to make it known.
```

**Comment by rpbaptist** [comment]
I have been troubleshooting this issue today until I just thought to switch to Gnome3 to test if it was working there.

`acpi_listen` does show the keys are registered:

```
video/brightnessdown BRTDN 00000087 00000000
 PNP0C14:00 000000d0 00000000
video/brightnessup BRTUP 00000086 00000000
 PNP0C14:00 000000d0 00000000
```

**Comment by dr0bz** [comment]
Here is what i get when trying to adjust the brightness with special keys.

csd-media-keys[9190]: Failed to get old screen percentage: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.cinnamon.SettingsDaemon was not provided by any .service files

T460s, Cinnamon 3.4

**Comment by mtwebster** [comment]
Did you reboot after upgrading?  You need to be sure you have cinnamon-settings-daemon 3.4 installed and running.

**Comment by mtwebster** [comment]
Ah nevermind, I there is a regression on our side, working on it getting fixed.

**Comment by clefebvre** [comment]
https://github.com/linuxmint/cinnamon-settings-daemon/commit/e3ea5e55a8541e82f898336a9a52db059021d6df

**Comment by morph027** [comment]
Build fixed version:

```bash
mkdir /tmp/cinnamon-settings-daemon
docker run --rm -it -v /tmp/cinnamon-settings-daemon/:/build -w /build ubuntu:xenial /bin/bash
apt-key adv --keyserver keyserver.ubuntu.com --recv EA1FE56966DFE684
cat > /etc/apt/sources.list.d/embrosyn-ubuntu-cinnamon-xenial.list << EOF
deb http://ppa.launchpad.net/embrosyn/cinnamon/ubuntu xenial main
deb-src http://ppa.launchpad.net/embrosyn/cinnamon/ubuntu xenial main
EOF
apt-get update
apt-get install git-core -y
git clone https://github.com/linuxmint/cinnamon-settings-daemon
cd cinnamon-settings-daemon
apt-get -y build-dep cinnamon-settings-daemon -y
dpkg-buildpackage
exit
sudo dpkg -i ../cinnamon-settings-daemon_3.4.0_amd64.deb 
```

Or grab pre-built: http://download.morph027.de/cinnamon-settings-daemon_3.4.0_amd64.deb

**Comment by morph027** [comment]
Ok, for non-Mint users, embrosyn's PPA is updated too...I love community-driven stuff ;)

**Comment by dr0bz** [comment]
@morph027, thanks! Are you sure embrosyn's PPA is updated?

**Comment by morph027** [comment]
Hm...not really...there was an update named 3.4.0-1, but you're right, hotkeys aren't working ;) My package works...

**Comment by rpbaptist** [comment]
@morph027 I like how you start a docker instance for this. Great usage of docker.

@clefebvre Thanks for the fast fix!

**Comment by morph027** [comment]
@rpbaptist 

> @morph027 I like how you start a docker instance for this. Great usage of docker.

Love it too, no need to mess up systems anymore ;)

**Comment by Trismegistos84** [comment]
I have same problem on Debian. Cinnamon 3.2.7.

Is there specific info which versions are affected?
