### ISSUE TITLE
Cinnamon 3.4.0 - Cannot move desktop icons

### ISSUE THREAD

**Issue by FireStarW** [linuxmint/Cinnamon#6517]
Using ubuntu 17.04, cinnamon from this ppa (https://launchpad.net/~embrosyn/+archive/ubuntu/cinnamon)

Desktop icons are able to be dragged and dropped into different positions before this cinnamon version, I can no longer do this in 3.4.0, and there is no setting anywhere related to this I can find.

**Comment by leigh123linux** [comment]
To disable,  right click on desktop and you will see a desktop option, uncheck the 'auto arrange' checkbox.

**Comment by leigh123linux** [comment]
Nemo draws the desktop, if you still can't move icons after unchecking  'auto arrange' you can open a issue against nemo.

https://github.com/linuxmint/nemo/issues
