### ISSUE TITLE
The old 'malicious client' bug resurfaces

### ISSUE THREAD

**Issue by ACinnamonUserInUK** [linuxmint/Cinnamon#6520]
I get the above message, sometimes, when resuming from suspend. Perhaps the new lockscreen causes it.

_This is a security problem_, because it is a crying wolf. That is: this error message arises nearly always bogusly, and so no-one will ever take it seriously; hence, if the message is ever _true_, people will ignore it.

Mint 18.1 x64 Cinnamon 3.2.7.

**Comment by mtwebster** [comment]
Can you explain?  I have no idea what you're talking about.

**Comment by ACinnamonUserInUK** [comment]
Please see, say, this: https://duckduckgo.com/?q=linux+mint+malicious+client+evesdropping&t=lm&ia=web

**Comment by leigh123linux** [comment]
It's not coming from cinnamon code.

```
[leigh@localhost Cinnamon-3.4.0]$ grep -i  malicious -r
src/cinnamon-recorder.c:       * should avoid problems with malicious symlinks.
```

**Comment by ACinnamonUserInUK** [comment]
[It would seem to be a `gksu' problem](https://ubuntuforums.org/showthread.php?t=1180786). However, something in Cinnamon, or Mint more widely, might be the promimate cause of the problem (i.e. might be setting `gksu' off).

**Comment by ACinnamonUserInUK** [comment]
I am unsure where on the web to file a bug report against `gksu`.

**Comment by leigh123linux** [comment]
@ACinnamonUserInUK  maybe here

https://github.com/linuxmint/libgksu/issues
