### ISSUE TITLE
[Super/Windows] not opening menu after updart to 3.4.0

### ISSUE THREAD

**Issue by mythreal** [linuxmint/Cinnamon#6522]
I updated to Cinnamon 3.4.0 tonight and after the right Super/Windows key doesn't open the menu. Went into settings/keyboard/shortcuts but couldn't find anything that might work like the suggested answer from **anandrkris** https://github.com/linuxmint/Cinnamon/issues/630

I only have a left super key. Don't know if that makes a difference.

Also desktop icon labels are gone. I cant move items on the desktop either. Thought it might be a theme issue but switched to the default theme and nothing changed.

Just ran cinnamon --replace and this was the output

Cjs-Message: JS LOG: About to start Cinnamon
St-Message: cogl npot texture sizes SUPPORTED
Cjs-Message: JS LOG: Cinnamon started at Fri May 12 2017 00:05:34 GMT-0600 (MDT)
Cjs-Message: JS LOG: network applet: Cannot find connection for active (or connection cannot be read)
Cjs-Message: JS LOG: network applet: Cannot find connection for active (or connection cannot be read)
Cjs-Message: JS LOG: network applet: Cannot find connection for active (or connection cannot be read)
Cjs-Message: JS WARNING: [/usr/share/cinnamon/desklets/photoframe@cinnamon.org/desklet.js 67]: Too many arguments to method Gio.File.monitor_directory: expected 2, got 3
Cjs-Message: JS WARNING: [resource:///org/cinnamon/cjs/modules/tweener/tweener.js 545]: reference to undefined property properties[istr].arrayIndex
openGL version 3.1 detected (GL3 Cogl Driver)
Window manager warning: Log level 16: STACK_OP_REMOVE: window 0x282 not in stack
Window manager warning: Log level 8: Source ID 11 was not found when attempting to remove it

Also I think it is reverting to fallback mode.

**Comment by ManIVIctorious** [comment]
For the icons: right click on Desktop, go to Desktop and disable auto arrange, this is just a bit bad choice for standard settings... 

For the menu shortcut, don't know (haven't upgraded yet) but try rightclick the menu and click configure, the per applet shortcuts have always been in their respective settings dialogue

**Comment by JosephMcc** [comment]
For one, it isn't reverting to fallback mode judging by your logs.

> For the icons: right click on Desktop, go to Desktop and disable auto arrange, this is just a bit bad choice for standard settings...

From my understanding this is set by default because otherwise you get a mess when upgrading. I'm not a fan of that particular setting personally but there is a reason for it.

Also, when posting bug reports, please at least include the distro you are using.

**Comment by mythreal** [comment]
ManIVIctorious, Thanks that fixed the positioning of the icons but still have no labels. What folders and files are what if you know what I mean. Just the icons.

JosephMcc,  There were many times that I ran --replace and rebooted to sort this out. There was a popup that said I was running in fallback mode several times but not every time. 

Running Ubuntu 16.04. Using Nvidia binary driver - version 375.39 (proprietary, tested), in case that helps?

As far as the menu I figured it out just now. The Menu cog was gone. Everything else in the panel was working just fine so I went looking for it. I was using Configurable Menu before update and it is broken now. I had forgotten that I was using it and upon adding the native menu back to the panel the menu works as expected. That was complete late night operator error. Sorry for that!

**Comment by JosephMcc** [comment]
Cool, closing this then. If you have issues with Nemo, which handles the desktop, they should be here: https://github.com/linuxmint/nemo/issues.

**Comment by JosephMcc** [comment]
I saw another Ubuntu user mention that they had no font configured for the desktop after they upgraded. Setting one fixed the problem for them so maybe check that.

**Comment by mythreal** [comment]
JosephMcc, That was exactly the problem. No font set. Many thanks to you all for your help! This is why I love the linux community!
