### ISSUE TITLE
File Manager Feature Request

### ISSUE THREAD

**Issue by dynamikspeed** [linuxmint/Cinnamon#6523]
1. In Windows explorer I dragged folders with the right mouse button held down this would provide me with the context menu and give me options to copy, move etc. Useful if you want to move a folder instead of clicking Cut and then Paste.
2. In Windows explorer left clicking the text on a folder once lets you rename it. This would be useful instead of having to right click > rename or pressing F2.
3. In Windows explorer I can start a folder name with _ and it moves to the front of the folder list when it is arranged by name. This is useful when you have lots of folders and want to prioritise certain ones to the front of the folder list. I tried this in Mint and it just goes on the next letter after _ and arranges it like that. The numbers work such as 1. 2. 3. but _ and symbols would be useful as it is in Windows.

I keep trying to do the above in Mint and failing so it would be amazing if these features could be added to the File Manager. ￼ :+1:

**Comment by JosephMcc** [comment]
Nemo is the File manager used in Cinnamon. Requests for it belong here: https://github.com/linuxmint/nemo/issues

**Comment by dynamikspeed** [comment]
Thanks, i will log it on there.
