### ISSUE TITLE
Cinnamon 3.4: people will be thrown by unmovable icons . .

### ISSUE THREAD

**Issue by ACinnamonUserInUK** [linuxmint/Cinnamon#6527]
. . and will struggle to find a way to allow them to be moved. First I checked the right-click desktop context menu, and didn't (in the top level menu . .) see what I sought. Then I looked in Nemo's options, and that was no help. Then I found it.

Some sort of message, in release documentation but also, I suggest, the first few times one tries to move icons (or something like that) is in order, I suggest. Otherwise people will get frustrated - within seconds of trying the (generally admirable) new version of Cinnamon.

**Comment by JosephMcc** [comment]
Again: https://github.com/linuxmint/nemo/issues/108#issuecomment-301262447
This doesn't belong here anyway since it's a nemo issue.
