### ISSUE TITLE
Cinnamon 3.4 feature request: control over the spacing of the desktop grid

### ISSUE THREAD

**Issue by ACinnamonUserInUK** [linuxmint/Cinnamon#6528]
I'd like my icons lined up by the grid. Yet, given the particular nature of the grid, I can't have the icons where I want them. For I want them flush with the horizontal edges of the screen. This situation is somewhat frustrating. Why can't the grid have some preset sizes, rather than just one size? Or is there in fact an option to customize the grid, and I just can't find it?

Thanks for your time.

**Comment by mtwebster** [comment]
https://github.com/linuxmint/nemo/issues/108#issuecomment-301262447

**Comment by JosephMcc** [comment]
Ah, there you go. This isn't a Cinnamon issue anyway.

**Comment by ACinnamonUserInUK** [comment]
Dear all

mtwebster wrote: What that means is you'll never be able to get the grid to fill the entire available real estate unless it's the primary (or only) monitor.

The desktop in question _is_ the primary and indeed only monitor on the computer. But perhaps I miss something in 'linuxmint/nemo#108 (comment)', for I am afraid I couldn't see what I was being directed towards there. Was it the video on that page? I found that video (or my admittedly small-ish laptop screen) too small to see properly.
