### ISSUE TITLE
Cinnamon 3.4.0: Disable touchpad while typing' still does not work, unfortunately

### ISSUE THREAD

**Issue by ACinnamonUserInUK** [linuxmint/Cinnamon#6529]
Unfortunately, the System Settings option 'Disable touchpad while typing'  still does not work (i.e. did not work on the previous version of Cinnamon and does not work now). In order to disable the touchpad whilst typing, I have to

- Install the package `xserver-xorg-input-synaptics-lts-xenial`
- Run the following on every boot, and as root: 
```
killall syndaemon >/dev/null 2>/dev/null || true
sleep 0.2
syndaemon -i 0.03 -d || true
```

Linux Mint 18.1 x64.

**Comment by leigh123linux** [comment]
The code responsible is in cinnamon0settings-daemon
