### ISSUE TITLE
Feature request: could we have a 'log off' item in the power-off-button-generated shutdown menu, please?

### ISSUE THREAD

**Issue by ACinnamonUserInUK** [linuxmint/Cinnamon#6530]
The Mint Menu offers an icon for logging off. So does the users applet. However, when I press the shutdown button on my laptop, the resulting window does not offer logoff. Also, I'd like it not to offer hibernation, whilst retaining the option to hibernate in other ways. One-stop solution: a system setting GUI that allowed one to determine what appears in this menu.

Apologies if I overlook some existing way of doing this and/or if I file this request in the wrong place.

**Comment by GabrielMGitHub** [comment]
The logout button is not in power/exit, but in "Logout".
It does not make any sense what you asked for, nor does windows work that way.

**Comment by ACinnamonUserInUK** [comment]
I am afraid that I disagree! I do so for two reasons.

1. Does it not make some sense to have everything to do with ending a user session - shutdown, restart, suspend, and logout - available in one menu? (At least, if the user so wishes it - configurability would be nice here. Please note also that I am not asking for 'log out' to be removed from any existing menu.)

3. My Windows _does_ work that way: it has one menu that offers shutdown etc. _and_ log out. Admittedly though I am using the ClassicShell program.

**Comment by ManIVIctorious** [comment]
I have to agree, always found the separation of logout and shutdown unnecessarily confusing...

**Comment by leigh123linux** [comment]
cinnamon-session is responsible for the dialogs

**Comment by bittner** [comment]
Let me mention, I have described a similar issue with the separation of "Quit", "Logout" and "Lock screen" in https://github.com/linuxmint/Cinnamon/issues/6239#issuecomment-337666292. My concern is that those are unnecessarily represented in the Cinnamon menu.

I feel, the "Quit" option in the menu should correspond to the user action "Now I press the power button" (to shut down the computer, or log out, or whatever to stop what I'm currently doing). Hence, having "Log out" also in that dialog wouldn't certainly hurt.

Follow up in https://github.com/linuxmint/cinnamon-session/issues/92.
