### ISSUE TITLE
System-Monitor does not show CPU-Time correctly

### ISSUE THREAD

**Issue by BA-Bartsch** [linuxmint/Cinnamon#6531]
(Linux Mint 18, 64 Bit, Cinnamon 3.0.7)
I am running 8 Threads in parallel and monitoring them with System-Monitor (german: Systemüberwachung). The used CPU-Time (german: CPU-Zeit) increases at 8x speed (which is okay). After a while it shows in german e.g. 2T15h which means 2 Days and 15 hours. But waiting longer will reset Days to 0.

I guess the problem is, that DAYS and HOURS are computed correctly, but WEEKS, MONTHS and YEARS are ignored and not printed. This is really annoying, because I am running processes for a very long time.

Benjamin

**Comment by JosephMcc** [comment]
Cinnamon has no system monitor application. I can only assume you are talking about gnome-system-monitor which is not part of Cinnamon or developed and maintained by Mint. You need to file this bug against gnome-system-monitor upstream.
