### ISSUE TITLE
Scale window navigation add keyboard shortcuts

### ISSUE THREAD

**Issue by androidfred** [linuxmint/cinnamon#6533]
STEPS TO REPRODUCE
Enter Scale (usually `ctrl + alt + down`)
Press `tab`, `alt + tab`, `ctrl + tab`, `j`, `k`, `l` or `;`

EXPECTED RESULT
Navigates between windows

ACTUAL RESULT
Nothing happens (the only means to navigate between windows in Scale are the arrow keys)

**Comment by MrElectroNick** [comment]
@androidfred tab switches between displays and arrows switch between windows in each display.

**Comment by androidfred** [comment]
@MrElectroNick Wow, thanks for the quick reply.

I'm afraid, as described, after entering Scale, pressing any of the described (including `tab`) does nothing in my case.

Arrows do switch between windows after entering Scale, but it would be nice if `tab`, `alt + tab`, `ctrl + tab`, `j`, `k`, `l` and `;` could be used as well to switch between windows after entering Scale.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
