### ISSUE TITLE
Keep windows' shadows when tiling/snapping on edges and corners

### ISSUE THREAD

**Issue by ThanosApostolou** [linuxmint/Cinnamon#6534]
It would be really nice if windows' shadows were shown even after tiling. If you don't want to make this behaviour default, then it would be nice at least to add an option for it. This is the default behaviour at KDE/kwin, Xfce/xfwm4, mate+compiz, Gnome+Shelltile extension... It is really hard for the eye to understand where the one window ends and where the other begins, as well as which one is currently selected (you need to look at the titlebar). If you see the difference at the screenshots below:
**Manually moved at edges:**
![screenshot from 2017-05-15 17-55-56](https://cloud.githubusercontent.com/assets/21288843/26063954/3387f17a-3998-11e7-9fe5-906e889bbc1c.png)

**Using tiling at edges:**
![screenshot from 2017-05-15 17-56-11](https://cloud.githubusercontent.com/assets/21288843/26063976/43501682-3998-11e7-9d18-ae155e558e58.png)

**Comment by JosephMcc** [comment]
Shadows being off is intentional. The lack of border between the windows is a bug in your theme.
![workspace 1_049](https://cloud.githubusercontent.com/assets/2231759/26068198/96235302-3951-11e7-9151-948016fec04a.png)

**Comment by ThanosApostolou** [comment]
@JosephMcc Can I enable the shadows somehow (maybe with a dconf setting) or is it hardcoded?

The only theme that I found which is working  properly is **vertex**. The most popular themes that I tried are affected from this (numix, arc, vimix, dark-aurora). Do I need to report this bug to all of these projects, or maybe is something that can be easily fixed from cinnamon (because cinnamon is the only Desktop Environment affected from such an issue)?

**Comment by JosephMcc** [comment]
Cinnamon is the only one affected because it's the only one using the metacity-3 theme for the window borders as far as I know. And yes, you should report the issue to the upstream themes.

**Comment by SE2Dev** [comment]
I have the same issue on Debian 9, except it applies to *all* themes.

**Comment by LinuxOnTheDesktop** [comment]
So far as I can tell, this is still a problem - and it really _is_ a problem - on Mint 20 Cinnamon,

**Comment by xsrvmy** [comment]
My two cents on this is that the shadows should be displayed because they function more as a focus indicator. It is hard to tell which window is focused unless your theme also has a different title bar color when the app is not in focus.
Additionally, themes that have a hard border actually cause old visual behaviour. The 1px border actually overlaps the other window, so when switching between them it looks like this border is shifting by 1px which drives me mad.
