### ISSUE TITLE
wifi adapter unavailable after restart os

### ISSUE THREAD

**Issue by m45rud** [linuxmint/Cinnamon#6535]
I have problem with my laptop. Sometimes the wifi adapater unavailable after restarting the system. But, this problem fix when I turn it off and turn it on manually without restarting it.

I'm using laptop:
- HP 14-d010TU
- Network card Ralink corp. RT3290 Wireless 802.11n 1T/1R PCIe
- Linux Mint 18 Cinnamon 64-bit
- CInnamon version 3.0.6
- Kernel version 4.4.0-21-generic

**Comment by two-dogs** [comment]
But, this problem fix when I turn it off and turn it on manually without restarting it. <-- explain this, you do what specifically?

**Comment by leigh123linux** [comment]
I doubt cinnamon is responsible for the issue, feel free to reopen if you can provide logs indicating cinnamon is at fault.
