### ISSUE TITLE
Separate left hand switch for mouse and touchpad

### ISSUE THREAD

**Issue by 1iquk** [linuxmint/cinnamon#6536]
I use a wireless mouse with my laptop and the buttons swapped around. 
When i take my laptop away and want to use the touchpad the tap works as a right click and not a left click. It takes some fiddling about to get it back to work as a left click.
Is there a way i can force the touchpad to always left click when i tap or can this be added in the settings?

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
