### ISSUE TITLE
Can't move window to left workspace only to right with keyboard shortcut

### ISSUE THREAD

**Issue by natanvarga** [linuxmint/Cinnamon#6540]
I can only move windows to the right workspace but not the left. The shortcut I have set up is Super+Shift+Left/Right. Works in one direction but not in the other. Been a longstanding issue now.

**Comment by JosephMcc** [comment]
Using the default keybinding, Shift+Ctrl+Alt Right or Left, both work fine.

**Comment by natanvarga** [comment]
To me, they switch to left/right workspace. Any other info I could provide?

**Comment by JosephMcc** [comment]
> To me, they switch to left/right workspace. Any other info I could provide?
 
I feel like I'm misunderstanding something. Isn't that what it's supposed to do? You are talking about the shortcut under Windows->Inter-workspace->Move window to left/right workspace?

**Comment by natanvarga** [comment]
Yeah, but instead of moving the window, the shortcuts move the focus to the left/right workspace and leave the window where it was

**Comment by JosephMcc** [comment]
It works correctly here. Maybe you should add some basic info like the distro and Cinnamon version you're using.

**Comment by natanvarga** [comment]
Cinnamon 3.4.0, just updated like two days ago. Distro is Manjaro Linux (Arch), kernel 4.11.1.

**Comment by Soulwest** [comment]
Same problem on Cinnamon 3.6.7 and kernel 4.10.0-42-generic in Linux Mint 18.3 Sylvia

**Comment by dlazerka** [comment]
Same problem, Linux Mint 18.3
This one doesn't work:
![image](https://user-images.githubusercontent.com/592184/38044676-5fc640c2-326f-11e8-98de-848b28eb19c3.png)
Shift-Super-Right works correctly.

**Comment by NikoKrause** [comment]
@dlazerka 
The shortcuts `Shift+Super+Left` and `Shift+Super+Right` are used as default in `Keyboard -> Shortcuts -> Windows -> Inter-monitor` 
Try to switch/change those.

**Comment by NikoKrause** [comment]
The problem here is, that you don't get a notification, that this shortcut is already used by default for another action.

**Comment by mtwebster** [comment]
This fix will prevent these collisions happening in the future, but will not correct existing accelerator collisions on users' systems.  However, once this patch is released, you'll be able to attempt to re-assign a non-working shortcut, and it should correctly pick up any previously-assigned actions.
