### ISSUE TITLE
window list thumbnails cannot be disabled

### ISSUE THREAD

**Issue by GetOperational** [linuxmint/Cinnamon#6542]
(system settings) > (applets) > (window list) > (configure) > (show windows thumbnails on hover): off

expected behavior: when hovering the mouse cursor over items in the taskbar, no thumbnails should appear
actual behavior: thumbnails appear regardless of setting

cinnamon 3.4.0.1 from ppa on ubuntu 17.04

**Comment by JosephMcc** [comment]
The same thumbnails appear either way? You don't get just the tooltip with the setting off?

**Comment by GetOperational** [comment]
If I use ubuntu 17.04 with the standard repo version of cinnamon 3.2.7 the thumbnail toggle works as expected.
If I use the ppa version of cinnamon 3.4.0.1 the toggle does nothing and thumbnails always appear.

**Comment by leigh123linux** [comment]
It works fine here.

**Comment by JosephMcc** [comment]
We are seeing multiple issues coming from Ubuntu users installing from a PPA. I'm starting to wonder if there is something wrong there. What PPA is it? For one there is no Cinnamon 3.4.0.1 so wonder what they might be changing.

**Comment by GetOperational** [comment]
looks like the version is 3.4.0-1~zesty0
https://launchpad.net/~embrosyn/+archive/ubuntu/cinnamon?field.series_filter=zesty

**Comment by JosephMcc** [comment]
Do you see any errors in ~/.xsession-errors when you change the setting?

**Comment by GetOperational** [comment]
If I open the settings dialog and change the thumbnail toggle ~/.xsession-errors does not change in size, so I assume it's not caching anything relevant to this bug.

The last few lines of that file are:
###!!! [Child][RunMessage] Error: Channel closing: too late to send/recv, messages will be lost
###!!! [Child][MessageChannel] Error: (msgtype=0x4600AE,name=PContent::Msg_ConsoleMessage) Channel closing: too late to send/recv, messages will be lost
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.

**Comment by JosephMcc** [comment]
I'm closing this. It seems to work as expected under both Mint and Fedora and you say it works fine in the version of Cinnamon in the Ubuntu repos.
