### ISSUE TITLE
Full-screen windows jump to foreground on another monitor

### ISSUE THREAD

**Issue by gima** [linuxmint/Cinnamon#6543]
## Bug

When a window is focused, all full-screen windows on *other* monitors jump to foreground (thus hiding windows that were in front of them).

> Video demonstration of bug: https://imgur.com/Lh2SOqj (or [cinnamon_fs_bug.zip](https://github.com/linuxmint/Cinnamon/files/1010726/cinnamon_fs_bug.zip))
> *^ Shows two monitors next to each other. Monitor on the right is only partly visible.*

## Affected programs
Assuming all full-screen windows, but these I tested:  
`xfce4-terminal`, `gnome-terminal`, `firefox`, `gedit`

Also `keepassx2`'s auto-type feature doesn't work, because it types into one of the fullscreen windows.

## How to reproduce

1) Open gnome-terminal<sup>*</sup> on monitor `A`
2) Open a filemanager<sup>*</sup> and move it on top of gnome-terminal
3) Open another filemanager<sup>*</sup> on monitor `B`
4) Make gnome-terminal<sup>*</sup> full-screen by pressing F11
5) Switch to the filemanager<sup>*</sup> of step2, so it' s now on top of gnome-terminal<sup>*</sup>
6) Click on the filemanager<sup>*</sup> on monitor `B`

Observe how gnome-terminal jumps to foreground, thus hiding windows that were in front of it.

<sup>*\*) I use filemanager and gnome-terminal to demonstrate, but other applications can be used as well.*</sup>

### System information

~~~
Distro: Arch Linux x86_64
kernel: 4.10.13-1
cinnamon: 3.2.8-1
cinnamon-desktop: 3.2.4-2
gtk3: 3.22.15-1
glib2: 2.52.2+1+gb8bd46bc8-1
muffin: 3.2.2-1
clutter: 1.26.2-1
clutter-gtk: 1.8.2-1
libgsystem: 2015.2+4+gd606bec-1
~~~

Cinnamon System Settings -> General -> "Disable compositing for full-screen windows" has no effect on the bug.

**Comment by gima** [comment]
This is probably a Window Manager bug, thus I re-filed this issue at linuxmint/muffin#286

**Comment by stevanmilic** [comment]
what's the solution @gima ?

**Comment by gima** [comment]
I don't seem to be able to reproduce this bug anymore (though with xfce4-terminal).
