### ISSUE TITLE
Missing translation

### ISSUE THREAD

**Issue by GabrielMGitHub** [linuxmint/Cinnamon#6544]
There is no "Are you want to restore all settings to default?" phrase to translate into the pt_BR language in the Launchpad.

pt_BR: Você deseja restaurar todas as configurações para o padrão?

![captura de tela de 2017-05-19 12-46-22](https://cloud.githubusercontent.com/assets/8754997/26256096/2f5704f4-3c92-11e7-8e94-90715655df85.png)
![captura de tela de 2017-05-19 12-46-38](https://cloud.githubusercontent.com/assets/8754997/26256097/2f58ec88-3c92-11e7-86e0-bd0160d92d6d.png)

**Comment by clefebvre** [comment]
Fixed in https://github.com/linuxmint/Cinnamon/commit/bec1a60ea29d3bc56a8f2af68607d5f6d74a32b3.
