### ISSUE TITLE
Update network time takes several minutes

### ISSUE THREAD

**Issue by germanfr** [linuxmint/Cinnamon#6552]
When I connect my computer to the Internet, time is not set, even though "network time" in settings is turned on. It takes like 5 minutes to trigger a re-sync. It would be desirable to do it right when a network connection is detected. 

It's very annoying because I can't use my computer each time I turn it on unless I manually adjust time, or I have to wait for magic to happen (and it takes minutes).

**Comment by leigh123linux** [comment]
What distro are you using?

**Comment by germanfr** [comment]
Manajro (Arch derived).

**Comment by leigh123linux** [comment]
It's a cinnamon-settings-daemon issue

https://github.com/linuxmint/cinnamon-settings-daemon/tree/master/plugins/datetime

I will probably close it there as well as it's archlinux's responsibility to add the support needed

**Comment by leigh123linux** [comment]
@clefebvre  would you agree it's the distro's responsibility?

**Comment by clefebvre** [comment]
It's definitely a CSD issue more so than a Cinnamon one... that said, I'd have to look into it to know what's at play here. I assume it's NTP and thus distro-related, but I'm not sure 100%.

**Comment by germanfr** [comment]
@clefebvre please, tell me if you finally find it's a distro issue. In that case I'd like to report it to them because it's a very annoying issue.
