### ISSUE TITLE
Expo icon looks like the icon for network-trying-to-connect

### ISSUE THREAD

**Issue by ACinnamonUserInUK** [linuxmint/Cinnamon#6553]
This unfortunate state of affairs, and the rationale for improving it (which boils down to: why not? it would be easy and a small good thing) was originally reported (by me) [here](https://github.com/linuxmint/cinnamon-spices-applets/issues/751#issuecomment-303205719).

But it boils down to this: on at least some icon sets - including I think inbuilt Cinnamon ones - the Expo icon looks like the trying-to-connect-to-network one; and so, at least if the network icon and the expo one are close together, glancing at one's panel - and glances are what panels are for - may cause confusion.

So, why not make the Expo icon a little more distinctive?

**Comment by JosephMcc** [comment]
The icon used by the network manager applet is up to the icon theme you use. We don't control that and honestly I don't really see this as being an issue. They don't look that much the same.

**Comment by Heavygrass** [comment]
@JosephMcc
> The icon used by the network manager applet is up to the icon theme you use.

I think @ghost means **Expo** applet uses a wrong icon.
Why does **Expo** applet uses the icon designed for network manager applet?

BTW, with yaru-cinnamon-dark theme **Expo** applet's icon is dark on dark background.
