### ISSUE TITLE
«Launch in Terminal» doesn't launch in preferred Terminal

### ISSUE THREAD

**Issue by in-in** [linuxmint/Cinnamon#6554]
I use Terminator as preferred terminal
![3cea2](https://cloud.githubusercontent.com/assets/8797432/26349792/ab544fc4-3fb9-11e7-81a7-d1ba0768e890.png)

But when I click on the Emacs icon in the menu, the editor opens in the gnome-terminal
![71f29](https://cloud.githubusercontent.com/assets/8797432/26349875/fc07380a-3fb9-11e7-9340-ecace39b3f02.png)
![abb76](https://cloud.githubusercontent.com/assets/8797432/26349883/fff4f416-3fb9-11e7-9bfe-c630cb9c085d.png)

I think «Launch in Terminal» option in menu item properties works wrong. BTW same for Vim icon.
![8f7f2](https://cloud.githubusercontent.com/assets/8797432/26350204/08ca563e-3fbb-11e7-86d0-8d16a70a8fd2.png)

How can I fix it?

**System**: Linux Mint 18.1 Cinnamon 64-bit
**Cinnamon**: 3.2.7

**Comment by JosephMcc** [comment]
Please use this already open bug: https://github.com/linuxmint/Cinnamon/issues/5269
