### ISSUE TITLE
terminal issue (maybe due to gconf version)

### ISSUE THREAD

**Issue by Gryffoon** [linuxmint/Cinnamon#6556]
I think this bug is due to the fact that cinammon uses gconf2 packages instead of dconf. Since it seems that Gconf is no more maintained.

While in root a gconf bug occurs when opening a simple programm like firefox

Here are the commands to reproduce the bug :

/> su

*ENTERING ROOT MODE*

/# firefox

(firefox-esr:1322): GnomeUI-WARNING **: While connecting to session manager:
None of the authentication protocols specified are supported.

(firefox-esr:1322): GConf-WARNING **: Client failed to connect to the D-BUS daemon:
Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.

(firefox-esr:1322): GConf-WARNING **: Client failed to connect to the D-BUS daemon:
Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.

(firefox-esr:1322): GConf-WARNING **: Client failed to connect to the D-BUS daemon:
Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.

(firefox-esr:1322): GConf-WARNING **: Client failed to connect to the D-BUS daemon:
Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
1494340068655	addons.productaddons	ERROR	Request failed certificate checks: [Exception... "SSL is required and URI scheme is not https."  nsresult: "0x8000ffff (NS_ERROR_UNEXPECTED)"  location: "JS frame :: resource://gre/modules/CertUtils.jsm :: checkCert :: line 145"  data: no]

Here you can see theses warnings, we can say that these are minor bugs, however... the shell is stopped. Even if you close firefox, the shell does not give you back the hand. So the only one solution is to make a CTRL+C to recover the hand to type any other command. If the commands are running through a shell script, the shell script stops and nothing can be done... This is why this is a major bug.

**Comment by leigh123linux** [comment]
Cinnamon uses dconf only.

P.S It's really dumb to run firefox as root!

**Comment by Gryffoon** [comment]
This was intended to make a test in order to investigate about this reccurent problem, so no it's not dumb at all. However it is dumb to make this remark.
