### ISSUE TITLE
Cinnamon 3.4 packages for Debian (and upcoming LMDE3?)

### ISSUE THREAD

**Issue by Trucido** [linuxmint/Cinnamon#6558]
Apologies if this is an inappropriate place to feature request and/or seek maintainer(s) but on Debian we still don't have anything newer than the jessie-equivalent builds (v3.2.x in Stretch, Sid, and even the Experimental/contrib repos), meanwhile Fedora's Cinnamon spin has cinnamon 3.4, as well as LinuxMint Sonya.  
After testing both, I feel they have much needed improvements and fixes which Debian would greatly benefit from (though I assume the current focus is on finalizing 3.4 for Sonya).  
  
With Stretch nearing release I understand it's probably frozen on 3.2.x but I assume LMDE3 will use 3.4 so it couldn't hurt to start working on some of the LMDE3 packages like cinnamon. Or at least some builds for Sid and/or Experimental repos?  
Stretch uses mostly the same underlying libs as Fedora25 so it shouldn't be too hard to build for, especially considering Debian is the parent distro of Ubuntu & LinuxMint which should be easier than building for Fedora (though I see mtwebster has done a great job on most of that work).  
  
If I could make heads or tails of the build process, deps, and toolchain requirements to produce consistent builds I would volunteer to maintain newer cinnamon builds for debian if no one else will but I've only managed to get nemo and some nemo-extensions to build so far.  
  
While the current 3.2.x versions are functional (for the most part) they still feel half-baked and unfinished compared to other foreign DE's like MATE. 3.4 seems to rely a bit less on Gnome3 and has many other fixes/improvements (like the half-broken notification support, indicators, HiDPI fixes for nemo, and the dozens of other issues seen in .xsession-errors/glass.log). Also, we don't have X-Apps, nemo-extensions, or Mint-Y-Icons but maybe that's asking too much (though I see Fedora has some of them). The equivalent X-Apps apps from MATE require too many deps unfortunately...  
Cherry picking a few packages from Betsy to stretch helps a little on theming but doesn't solve the above mentioned issues (or others I can't think of right now).  
  
We appreciate cinnamon being available in Debian, of course, but please don't neglect your parent distro for future versions!  
  
Thanks, and keep up the great work!

**Comment by leigh123linux** [comment]
@marga-debian  Can you answer the question above please?

**Comment by JosephMcc** [comment]
I know your looking for answers but we don't actually package things for distros outside of Mint. You need to contact the debian maintainers.

**Comment by marga-debian** [comment]
Hi!

I'm one of the cinnamon maintainers for Debian.  As you said, stretch is currently frozen and very near release, it will be released with 3.2 plus some fixes that were cherry picked from 3.4.

After stretch is released, we will upload 3.4 to unstable.  And we will almost certainly also backport it to stretch, through the backports repository.

It's not clear to me what you are asking exactly but you are welcome to discuss more in https://lists.alioth.debian.org/mailman/listinfo/pkg-cinnamon-team

Cheers.

**Comment by Trucido** [comment]
Sorry for the noise, I realized after the fact that this "issue" doesn't belong here.  
  
I had originally issued it here under false assumptions, hoping some fixes or packages might trickle downstream because:  
1). I assumed @clefebvre was involved in the Debian packaging since he primarily maintains the Debian fork of LinuxMint (LEDE, currently v2 based on Debian Jessie)  
2.) I assumed Debian's Cinnamon packages were ported from LEDE2 (Betsy), which would influence the downstream Debian packages if true.  
3.) I assumed some amount of packaging was done here since @mtwebster was listed in some of the Fedora25 Cinnamon spin source RPMs (which uses cinnamon 3.4), but I now see I was incorrect; he's listed due to some of their cherry picked patches.  
  
I'll direct all future distro-specific requests/questions/issues to the appropriate channels in the future, as I now see Debian has taken over the downstream packaging and LEDE requests/questions/issues likely belong on the linuxmint forums and not here.  
  
@marga-debian :  
Thanks for the reply, I'm glad to hear 3.4 will eventually make it to Debian. I realize Stretch isn't fully stabilized yet but there's several fixes/patches that probably should be included in the current 3.2.x packages at least.  
I'll post questions/suggestions to the mailing list (though it's very inconvenient due to all the spam there) and the bugs I've found to the bug tracker.  
I do share your team's pain building cinnamon since it's a huge dep headache with the explicitly versioned libs (or the changed names like libcjs0{e,f,etc}. It seems other distros like Fedora don't split out a lot of the cinnamon-specific libs which makes it easier, but obviously that's not the Debian way, though looking toward the future it would be helpful to have a more manageable dependency chain, perhaps with some libs slotted.

**Comment by leigh123linux** [comment]
> I do share your team's pain building cinnamon since it's a huge dep headache with the explicitly versioned libs (or the changed names like libcjs0{e,f,etc}. It seems other distros like Fedora don't split out a lot of the cinnamon-specific libs which makes it easier, but obviously that's not the Debian way

If I was to split the libs for fedora cinnamon it wouldn't be difficult.
I certainly wouldn't use the lame naming debian or mint uses, trying to version package names is lame and prone to breakage.

Fedora would use this for cjs split, names would be cjs and cjs-libs.
I would use fully versioned deps for libs requirement, so cjs package would require

Requires: cjs-libs = %{epoch}:%{version}-%{release}

Using versioned  requires and builddeps would help their mess.
currently cinnamon has a poorly versioned cjs build dep

https://github.com/linuxmint/Cinnamon/blob/master/debian/control#L11

So cinnamon could be built against cjs-3.4.0 but end up on someones PC who has cjs-3.2.0 installed

https://github.com/linuxmint/Cinnamon/blob/master/debian/control#L49

Fedora example:
Set a global cjs version

http://pkgs.fedoraproject.org/cgit/rpms/cinnamon.git/tree/cinnamon.spec#n4

Use it for the build requirement

http://pkgs.fedoraproject.org/cgit/rpms/cinnamon.git/tree/cinnamon.spec#n46

And for the requires (I don't rely on rpm autorequires)

http://pkgs.fedoraproject.org/cgit/rpms/cinnamon.git/tree/cinnamon.spec#n85

```
[leigh@localhost ~]$ rpm -q --requires cinnamon |grep cjs
cjs(x86-64) >= 3.4.0
libcjs.so.0()(64bit)
[leigh@localhost ~]$ rpm -q --provides cjs
cjs = 1:3.4.1-1.fc26
cjs(x86-64) = 1:3.4.1-1.fc26
libcjs.so.0()(64bit)
```

**Comment by Trucido** [comment]
> I certainly wouldn't use the lame naming debian or mint uses, trying to version package names is lame and prone to breakage.
  
> Using versioned requires and builddeps would help their mess.
currently cinnamon has a poorly versioned cjs build dep
  
Not sure where that originated from, probably linuxmint/ubuntu but on Debian it's just 'cjs' and 'libcjs0' with `cjs (>= 3.2)` and `libcjs0 (>= 2.0.0)`, with `cjs-3.2.0-3` depping on `libcjs0 (>= 2.4.1)` but I agree that one probably shouldn't be versioned by name upstream.  
  
However, some other packages ARE versioned by name such as libmozjs (even on Fedora, though I forget the equivalent names).  
That one in particular will need to be in Debian in the future (if 3.4 is to be backported) since the current stable/testing/sid/exp repos only have 24-0 and 185-1.0  
The ubuntu/linuxmint package of libmozjs-38.0 could potentially work if it didn't have an explicit dep on `libicu55 (>= 55.1-1~)` since Debian9 uses libicu57 (another bad name-versioned package) but I think the newer one might work fine (or need to be recompiled against it if it uses any of the shared libs).
  
I haven't had much time to inspect the current Debian source packages but I think they do similar package versioning (instead of name versioning) on the other cinnamon deps. Inspecting some more of the Fedora source packages, it seems they're loosely ported from LinuxMint 18.1 and 18.2? (with some modifications and patches).  
  
> So cinnamon could be built against cjs-3.4.0 but end up on someones PC who has cjs-3.2.0 installed
  
Yeah that's the main issue I was having while attempting a 3.4 build but if I attempt it again, I'll compare and modify the control/rules/etc.. files as well as maybe borrow some ideas/patches from Fedora (though the order in which to build each will take some deeper inspection and trial & error).  
  
Anyways, thanks for some insight on how Fedora does it @leigh123linux , I imagine the upcoming Fedora26 release will be a real pain in the butt (last I checked it was failing to compose for alpha, but so was the MATE spin).

**Comment by leigh123linux** [comment]
There is a build guide with the build order

http://developer.linuxmint.com/reference/git/cinnamon-tutorials/building.html

The fedora alpha cinnamon and mate spins failed to compose because of a missing f26-backgrounds package, we are fine for beta.

https://dl.fedoraproject.org/pub/fedora/linux/development/26/Spins/x86_64/iso/
