### ISSUE TITLE
Choice of 'preferred application' is ignored

### ISSUE THREAD

**Issue by ACinnamonUserInUK** [linuxmint/Cinnamon#6559]
To see / reproduce the problem

Some video player will be set as 'preferred application' for video. Try to change it. Notice in the preferred application window the preferred application gets reset after you try to change it.
Open a video. See how the change you tried to make has not stuck.

Given that sometimes a bug is the reason one wants to change a preferred application in the first place, this bug is rather trying. I need to use my Mint laptop for teaching in a few days time and two of the video players I have are buggy; they do not properly play the video that I need to play. Xplayer does play the video properly (hooray!) but I can't set it as the default application. (Boo!)

PS: If I report this in the wrong place, then I am sorry - but please note the following. I searched four of the Mint github subdomains (or whatever they are more properly called), found nothing, and so resorted to reporting here. I do think that it should be made easier to find the right place to report bugs. I think also that this bug has been reported before, but I can't see where. (Indeed, I think that a year or more ago I reported a version of this problem that beset pdf files.)

Mint 18.1 x64 Cinnamon 3.2.7

**Comment by JosephMcc** [comment]
I just tried this in Cinnamon3.4 and it worked perfectly. When changing it, double clicking a .mp4 opened in whatever app I chose. Firefox even offered to open it in whichever app I had set when I downloaded the video.

**Comment by JosephMcc** [comment]
Closing this since in my tests it works properly in Cinnamon3.4.
