### ISSUE TITLE
no spotify album covers in sound applet 

### ISSUE THREAD

**Issue by mabod** [linuxmint/Cinnamon#6560]
Hi,

the spotify album covers are not showing anymore in the sound applet. I am saying "not anymore" because it was working with my debian testing resp. LMDE installation but it is not working anymore after I migrated to Manjaro. 

Manjaro is using newer versions of spotify and cinnamon:
spotify 1.0.55.487-1
cinnamon 3.4.0-1.1

Matthias

**Comment by JosephMcc** [comment]
There is some info on spotify here: https://github.com/linuxmint/Cinnamon/issues/4783
Probably best to stick to that issue. Not sure there is much we can do. Spotify stuff isn't open source and it sounds like we might run into even more limitations: http://www.omgubuntu.co.uk/2017/04/spotify-web-player-linux-discontinued

**Comment by mabod** [comment]
The "more limitations" you are referring to are actually about the "spotify web player". I am talking about the spotify client app.

**Comment by mabod** [comment]
It is working now with cinnamon 3.4.1-1.1

Matthias

**Comment by benjaminwolkchen** [comment]
The issue is again showing up with cinnamon 4.4.8 on Linux Mint 19.3.
My system information: https://termbin.com/pgd1
And i use the Spotify .deb Package: https://www.spotify.com/de/download/linux/ (The Section titled: "Debian / Ubuntu")

The sound applet:
![spotify cinnamon issue](https://user-images.githubusercontent.com/42138517/77846854-3af14400-71b9-11ea-8f5a-9f876c9e4ad3.png)

**Comment by prcr** [comment]
> The issue is again showing up with cinnamon 4.4.8 on Linux Mint 19.3.

I have exactly the same problem.

```
$ cinnamon --version
Cinnamon 4.4.8
```

![image](https://user-images.githubusercontent.com/436692/79015307-69313500-7b64-11ea-8cc1-74466faa5bfd.png)

This was working a few weeks ago, I'm not sure what changed that could have caused this.

**Comment by rlbc** [comment]
I'm having the same problem lately. Cinnamon 4.4.8 and Spotify version 1.1.10.546.ge08ef575 installed via deb package.

As a bonus, Spotify starts a second process which doesn't close itself after I exit the application. I have to kill the process for a proper exit.

**Comment by telmotrooper** [comment]
Having the same issue here, I'm on Arch Linux with `Cinnamon 4.6.6` and `Spotify version 1.1.10.546.ge08ef575`.

**Comment by sojkin** [comment]
Same here. Cinnamon 4.6.7 and  Linux Mint 20 Ulyana

![Screenshot 2020-08-30 22:26:29](https://user-images.githubusercontent.com/2184760/91668829-08ed6080-eb10-11ea-9ab4-36c287b31fd9.png)
