### ISSUE TITLE
System Restart not works on first use, only second use reboots 

### ISSUE THREAD

**Issue by igordovgaluk** [linuxmint/Cinnamon#6561]
system not restarted when use Quit-Reboot first time.
On second use of Quit-Restart the system reboots. 

Cinnamon 3.2.7, Mint 18.1 , kernel 4.4.0-66

**Comment by igordovgaluk** [comment]
after investigation, the first reboot fails if HipChat client is started. It actually closes the HipChat. So the next Reboot works.

Though 'sudo reboot' and Reboot from login screen have no issues even if HipChat is running.

How HipChat prevents Cinnamon from reboot?

**Comment by JosephMcc** [comment]
Some apps can inhibit shutdown/logout if something needs to be dealt with. I'm not familiar with hipchat but text editors like xed or gedit will do this when you have an unsaved file open. It helps prevent you from shutting down, forgetting about it, and lose your work.
