### ISSUE TITLE
Desktop shown if reboot from login screen [security]

### ISSUE THREAD

**Issue by igordovgaluk** [linuxmint/Cinnamon#6562]
Steps:
1. login with a user A
2. choose Logout-Switch User
3. on the login screen choose Quit-Reboot

Expected result:
system reboots. 
Desktop and running apps of user A **are not shown** on the screen.

Actual result:
Desktop and running apps of user A are shown on the screen.
Then system reboots.

**Comment by JosephMcc** [comment]
The login screen (display manager) is not part of Cinnamon. Since you didn't say the distro and or display manager you are using, I'll just assume Mint and point you here: https://github.com/linuxmint/mdm/issues

**Comment by igordovgaluk** [comment]
@JosephMcc  i believe Cinnamon should hide the desktop anyway (e.g.with black screen).
