### ISSUE TITLE
Problems with 3 Monitors

### ISSUE THREAD

**Issue by D1Ck3n** [linuxmint/Cinnamon#6563]
Hello everybody,

I am trying to set up on my notebook (HP 650 G1) Linux Mint 18.1 Cinnamon and encounter the following problem:

If I have connected three monitors, graphic errors occur on the taskliste and the icons (see picture)
![vwd6eiek](https://cloud.githubusercontent.com/assets/28949322/26446115/1445b588-4143-11e7-9bd0-e58abe9c8216.png)

The notebook has the following (relevant) specifications:
CPU: Intel Core i5-4210M
GPU1: Intel HD Graphics 4600
GPU2: AMD Radeon HD 8750M
Kernel: 4.4.0-53
Cinnamon: 3.2.7

The device is plugged into an HP docking station and there are 3 monitors connected (1x DVI, 1x VGA, 1x DP).

I think there is a bug in Cinnamon

**Comment by JosephMcc** [comment]
https://github.com/linuxmint/Cinnamon/issues/5415
