### ISSUE TITLE
Find Files and Folders by Panel Starter

### ISSUE THREAD

**Issue by jepster** [linuxmint/Cinnamon#6564]
Once I was able to find my documents folder via the starter. Right now I cannot. Also any other files and folders. How can I enable the starter to be able to find files and folders again? Was this a feature which has been removed by an update?

**Comment by JosephMcc** [comment]
In cinnamon-settings->privacy make sure recents are enabled and in the settings for the menu, make sure show bookmarks and places is enabled.

**Comment by jepster** [comment]
This helps me a bit, since I can access recent files. But I cannot access any of my folders by this. On Mac I can just type the foldername in spotlight and I am able to quickly access it. Is such functionality also in cinnamon?

**Comment by Odyseus** [comment]
Hello, everybody.

@jepster: If you are talking about what I thing your are talking about, go to the Cinnamon menu applet settings window and enable the option called **Enable filesystem path entry in search box**. It will allow you to search files from the search entry on the menu applet.

**Comment by jepster** [comment]
@Odyseus: I have enabled this option. But I can only find my picture folder. Not my documents folder for example. See attached screenshots.

![arbeitsflache 1_018](https://cloud.githubusercontent.com/assets/628434/26505126/cf753478-4247-11e7-9873-25dc6c4bf05d.png)
![arbeitsflache 1_019](https://cloud.githubusercontent.com/assets/628434/26505127/cf7a25d2-4247-11e7-9311-b8c4146aba72.png)
![auswahl_020](https://cloud.githubusercontent.com/assets/628434/26505110/b7f48baa-4247-11e7-97fe-a07f0d5c1cf2.png)

**Comment by jepster** [comment]
Can you re-open this issue? I consider the current behavior a bug.
