### ISSUE TITLE
Background changes to noise after waking from sleep mode

### ISSUE THREAD

**Issue by vlad0337187** [linuxmint/cinnamon#6565]
Hello.

I have such each time I wake my PC from sleep mode:
![2017-05-26 00-12-56](https://cloud.githubusercontent.com/assets/12682937/26471010/8a596f0c-41a8-11e7-99c6-d5e409c5975d.png)
I use nvidia proprietary driver, recommended in driver-manager (nvidia-375).
After I change background (choose some image) - it looks normally.
Hope, this could be easily fixed.

Best regards,
Vladislav

**Comment by JosephMcc** [comment]
I think this is a problem specific to clutter and the nvidia driver. I have an idea of how we might fix it but I need to talk to some others that have more knowledge about some things.

A quick workaround is to restart cinnamon. You can do this by using Alt+F2 entering r in the dialog and hitting enter. That should refresh the background.

**Comment by scottgordon1259** [comment]
I had the same issue everyone kept telling me iytt was the driver or the card or whatever else. Dumped cinnamon and now using MATE  with zero issues and with the same kernel and the same video driver

**Comment by danchiba** [comment]
I'm also experiencing the same problem. In addition to the background, a similar thing happens when pressing Alt+Tab. My switcher style is set to coverflow, and the previews for all windows that have not been brought to the foreground since waking up are rendered as noise in the coverflow. When a particular window is selected it is rendered normally. Also, restarting cinnamon does not work for me as @JosephMcc suggested. I can only fix these problems by selecting the windows and changing the background.

**Comment by vlad1777d** [comment]
Can we send bugreport to Nvidia somehow ?

**Comment by JosephMcc** [comment]
What looks like the same issue affects gnome-shell. You can read about it if you want here: https://bugzilla.gnome.org/show_bug.cgi?id=739178

While the shell fix is not directly portable, we need to look at doing something similar.

**Comment by scottgordon1259** [comment]
yes  it has to be anything but cinnamon.  geez

**Comment by JosephMcc** [comment]
> yes it has to be anything but cinnamon. geez

What's the point of this exactly? There has been a rise in this sort of thing in our github issues. This is a place for reporting bugs and making feature requests. People who can provide information on a bug, help track down the cause, or maybe help find a solution are more than welcome.

What this isn't is a general discussion forum, the comments section of a blog, or reddit. People are going to start finding their posts deleted if they can't act with some decency and stick to providing information that is actually relevant to the issue at hand.

Apologies to the OP for the derail.

**Comment by scottgordon1259** [comment]
first off I was told  that it was the nvidia drivers, Then i was told the kernel is bad, then i was told my video card was bad ( NEW)  then I was told it was a bad install.  I uninstalled cinnamon  and installed MATE  with the same video card and the same driver, and the same kernel, guess what  no problems

thats the point , bTW not a derail pay attention to whats posted and you would not have to ask WHATS THE POINT

**Comment by vlad1777d** [comment]
@JosephMcc , thank you. 
I can't understand much in it, so I can only wait for developers's decision.

**Comment by icarter09** [comment]
@vlad0337187 are you still experiencing this issue? Also thank you for being appreciative and helpful during this issue thread. It's very much appreciated by the Linux Mint team.

**Comment by vlad0337187** [comment]
@icarter09 , no, it's absent in recent recent versions of Linux Mint.
I see some similar noise only in Atom text editor after waking from sleep, but it's not related to Cinnamon.

If nobody else have such issue, I think, it can be closed.

**Comment by fde-capu** [comment]
Here's my noise demo attached, and neofetch specs:

```
       _,met$$$$$gg.          fde-capu@N7FAA52318 
    ,g$$$$$$$$$$$$$$$P.       ------------------- 
  ,g$$P"     """Y$$.".        OS: Debian GNU/Linux 10 (buster) x86_64 
 ,$$P'              `$$$.     Kernel: 4.19.0-12-amd64 
',$$P       ,ggs.     `$$b:   Uptime: 6 days, 2 hours, 58 mins 
`d$$'     ,$P"'   .    $$$    Packages: 1992 (dpkg) 
 $$P      d$'     ,    $$P    Shell: bash 5.0.3 
 $$:      $$.   -    ,d$$'    Resolution: 3840x2160 
 $$;      Y$b._   _,d$P'      DE: Cinnamon 3.8.8 
 Y$$.    `.`"Y$$$$P"'         WM: Mutter (Muffin) 
 `$$b      "-.__              WM Theme: CBlack (CBlack) 
  `Y$$                        Theme: CBlack [GTK2/3] 
   `Y$$.                      Icons: ePapirus [GTK2/3] 
     `$$b.                    Terminal: xfce4-terminal 
       `Y$$b.                 Terminal Font: Iosevka Term SS04 Medium 8 
          `"Y$b._             CPU: Intel i7-6700 (8) @ 4.000GHz 
              `"""            GPU: NVIDIA GeForce GTX 970 
                              Memory: 12961MiB / 15980MiB 
```
I have just found out that the noise does not occur when the browser window is at least slightly transparent. So Cinnamon *is* refreshing the render, thou without app-specific request unless something has changed, so caches are preserved.
Somehow, if this defect was a feature, it would grant some degree of privacy when unlocking the screen in public.
Still, the looks are quite annoying.
![Screenshot from 2020-11-03 09-43-47](https://user-images.githubusercontent.com/52455203/97987444-0fbb7c80-1dba-11eb-9444-5c37cda2afd1.png)
