### ISSUE TITLE
Logout; login as different user; applets -> 'available applets (online)' produces error and consequent badness

### ISSUE THREAD

**Issue by ACinnamonUserInUK** [linuxmint/Cinnamon#6567]
Here's the error.

![image](https://cloud.githubusercontent.com/assets/9998846/26514517/dc836b34-4261-11e7-805f-ddedc9fd48ae.png)

Consequent (certainly subsequent, and I believe consequent) badness: error box could not be dismissed for about 30 seconds; buttons in settings window initially unresponse.

Mint 18.1 x64 Cinnamon 3.2.7

**Comment by JosephMcc** [comment]
Lets stick to this one: https://github.com/linuxmint/Cinnamon/issues/2215
