### ISSUE TITLE
Add gnome-shell overview extension to Cinnamon

### ISSUE THREAD

**Issue by freemangilgamesh** [linuxmint/Cinnamon#6568]
<a href='https://postimg.org/image/bjmdgu3tn/' target='_blank'><img src='https://s1.postimg.org/bjmdgu3tn/Screenshot_from_2017-05-27_14-39-18.png' border='0' alt='postimage'/></a>

I think this is very useful for those who want a clean and modern desktop! thnx

**Comment by leigh123linux** [comment]
This should be done in spices not cinnamon.
