### ISSUE TITLE
Borderlines are missing in LinuxMint

### ISSUE THREAD

**Issue by thegamblerrises** [linuxmint/Cinnamon#6570]
Mint version - LinuxMint 18.1 Cinnamon 64bit
Cinnamon Version - 3.2.7
Linux Kernel - 4.4.0.77-generic

All the 'separators' and 'borders' are missing, so there is no 'button' like effect. I only see texts. Look at the top left side of this image, "File", "Edit", "View" etc are all coming together. -> 

![screenshot from 2017-05-29 03-29-16](https://cloud.githubusercontent.com/assets/15961152/26532510/1c676556-4420-11e7-8284-592d0a694e72.png)

I am not sure exactly after what upgrade borders got vanished. And I am unable to get it back. Could you please help? Sometimes, it gets so hard to select any dropdown option as I see all options' texts and not sure which option is actually 'selected'.

**Comment by Odyseus** [comment]
Hello, @thegamblerrises.

Check you GTK3 version. If it is any other than 3.18.x, then your theme isn't compatible with that version of GTK3. You will have to search for a theme (just the Controls part) that it's specifically built for the GTK3 version that you have installed.

To check your GTK3 version just run `inxi -Sxx`. It will display the GTK3 version next to the desktop environment version.

**Comment by JosephMcc** [comment]
@Odyseus is correct. It looks like you updated to gtk3.20 or higher which is not at all recommended in Mint. In any case this isn't a Cinnamon issue.

**Comment by thegamblerrises** [comment]
Thanks. I found out the issue to be same. I installed [Arc theme](https://github.com/horst3180/Arc-theme)
