### ISSUE TITLE
Hyper-V invisibile cursor

### ISSUE THREAD

**Issue by kingcocomango** [linuxmint/cinnamon#6571]
Hello,

# Issue

Mouse point doesnt show up in cinnamon when running inside hyper-v

# Expected behaviour

That I can see my mouse pointer

# Solution

Automatically apply 
`gsettings set org.cinnamon.settings-daemon.plugins.cursor active false`
When cinnamon detects its in software rendering mode.

I believe this issue would happen in all software rendering modes, since afact it happens because cinnamon tries to render the mouse with hardware even if software mode. It just almost never shows up, because pretty much every cpu has a flyweight gpu in it.

Solution sourced from [here](https://social.technet.microsoft.com/Forums/windows/en-US/87e132b4-8133-4d65-8dd5-845077f35730/hyperv-issue-mouse-pointer-invisible-in-linux-mint-17-run-in-hyperv-of-windows-10?forum=winserverhyperv)

**Comment by icarter09** [comment]
@kingcocomango are you still experiencing this issue?
