### ISSUE TITLE
Cannot suspend to ram on lid close

### ISSUE THREAD

**Issue by dr0bz** [linuxmint/Cinnamon#6572]
Using Cinnamon 3.4.1.

On lid close it does not suspend and i get following:

`Mai 29 12:17:50 xmframe csd-power[2658]: couldn't sleep using UPower: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: Keine derartige Methode »Suspend«
Mai 29 12:17:51 xmframe systemd-logind[1104]: Lid opened.
Mai 29 12:17:51 xmframe repowerd[1102]: UPowerPowerSourceAndLid: change_upower(), lid_is_closed=false
`

**Comment by leigh123linux** [comment]
Please file the issue against cinnamon-settings-daemon

https://github.com/linuxmint/cinnamon-settings-daemon/issues
