### ISSUE TITLE
Remove app from panel is written in German

### ISSUE THREAD

**Issue by joedamarsio** [linuxmint/Cinnamon#6574]
Right clicking on a panel app, and then going to preferences, shows the option that usually reads something like 'Remove app from panel' actually reads 'leistenstarter entfernen'

I'm running Cinnamon 3.4.0 on Fedora 25, and the 'English, United Kingdom' language option.

![remove_panel_german](https://cloud.githubusercontent.com/assets/29088224/26621116/7a533fbe-45dd-11e7-8511-9e5be46b2003.png)

**Comment by leigh123linux** [comment]
This was fixed in cinnamon-trenslations-3.4.2

https://bodhi.fedoraproject.org/updates/FEDORA-2017-1ae435e0c0
