### ISSUE TITLE
Panel "Blocks" Context Menu Access

### ISSUE THREAD

**Issue by zephyr28** [linuxmint/Cinnamon#6576]
On the occasion that a context menu extends beyond the borders of a panel, the menu items there can not be selected.

While most applications, this isn't an issue because the context menus open away from the panel. However, in IntelliJ IDEA, for example, there are too many options:

![screenshot from 2017-05-31 19-53-44](https://cloud.githubusercontent.com/assets/24708466/26658910/1d9a295a-463b-11e7-8573-d2d5e40a9c55.png)

The `hide ignored files` menu option in the above screenshot can not be highlighted or selected with the mouse (only using the keyboard's arrow keys can select it).

**Comment by MrElectroNick** [comment]
@zephyr28 Please report it to JetBrains issue tracker here: https://youtrack.jetbrains.com/issues
I've experienced same behaviour with branch pop up menus at some point and they fixed it. It's not related to desktop environment

**Comment by JosephMcc** [comment]
Thanks for following up. We've seen a few bug reports that seem to only happen with these applications.
