### ISSUE TITLE
can not render scene in linux mint blender 2.78

### ISSUE THREAD

**Issue by foremancr** [linuxmint/Cinnamon#6577]
I have been trying to render a scene in blender for sometime but the blender crashes.  I have tried various version but nothing works.  I am using mint 18.1   64 bit.  I have a Nvidia 1070 video card with 32 Gb of ram.  This should be enough to run this software.  I have been using Linux Mint for sometime but in recent days this problem has been occurring.  I am also using linux blender 2.78c but it continues to crash.  I have removed linux mint from my computer and install ubuntu 64 and I have no problems rendering the same scene in blender.  It is the exact same setup with the same video drivers.  While in mint I have a error of cuda loading too slow and the software would soon crash after this.

**Comment by leigh123linux** [comment]
File your issue against ubuntu blender
