### ISSUE TITLE
Mintmenu graphical glitches while scrolling

### ISSUE THREAD

**Issue by martinprochazka** [linuxmint/Cinnamon#6578]
If you scroll programs in mintmenu by dragging the scrollbar some weird thing happens. Here you can see it, look at the bottom:

![some fragments left at the bottom](https://cloud.githubusercontent.com/assets/19396796/26722208/412bb6ae-478f-11e7-9b74-4fe55a731408.gif) 

This doesn't happen if you use scrollbar on your mouse. I have Cinnamon 3.2.7, version that came with Mint

**Comment by JosephMcc** [comment]
https://github.com/linuxmint/Cinnamon/issues/5721
