### ISSUE TITLE
Lowering brightness turns screen off

### ISSUE THREAD

**Issue by viggy96** [linuxmint/Cinnamon#6580]
Lowering the brightness once it is already at its minimum causes the screen to turn off. I'm pretty sure its Cinnamon, as the GNOME desktop does not do this.

OS: Ubuntu 16.04.2 LTS
Cinnamon 3.4.1, (from embrosyn stable PPA)

**Comment by xavierhd** [comment]
I thought I had this behavior too. But in fact, if I angle my screen right and with a lot of light, i can see very poorly the UI. This is still bad since it doesn't turn off the screen nor let the user use it.

**Comment by JosephMcc** [comment]
https://github.com/linuxmint/Cinnamon/issues/7080
