### ISSUE TITLE
JS ERROR: TypeError: ndata is undefined

### ISSUE THREAD

**Issue by two-dogs** [linuxmint/Cinnamon#6583]
System:    Host: linux-s4s1 Kernel: 4.11.3-1-default x86_64 (64 bit gcc: 7.1.1) Desktop: Cinnamon 3.4.1  dm: sddm,sddm Distro: openSUSE Tumbleweed

i am not sure how i trigger the error and i dont see any ill effect
from log;
https://gist.github.com/anonymous/dc69a4acc9c26a040427787182502691

**Comment by two-dogs** [comment]
@mtwebster thanks, that is quick service :+1:

**Comment by mtwebster** [comment]
Thanks for the reminder ;)  We have a new underlying JS version, and it generates a lot of warnings (behavior is unchanged, we just get our wrist slapped more)

**Comment by two-dogs** [comment]
i have a better one, scarier looking @mtwebster , will share here
