### ISSUE TITLE
accidentally delete-key no confirmation for moving to trash

### ISSUE THREAD

**Issue by LinuxZoo** [linuxmint/Cinnamon#6584]
Hello and thanks a lot for the ~only~ usable Linux GUI in 2017 :-)

But I think there is an 'issue' if someone (cat, woman, kids, me) press accidentally the delete-key and at the desktop a shortcut is marked, the file will moves without confirmation to the trash.

Maybe this will be detected or not - if to late - the file etc. is no longer in the Backups etc.

best regards

**Comment by JosephMcc** [comment]
You already posted in the open Nemo issue which was the proper place.
