### ISSUE TITLE
JS ERROR: GLib.Error g-invoke-error-quark

### ISSUE THREAD

**Issue by two-dogs** [linuxmint/Cinnamon#6586]
system info:
System:    Host: linux-s4s1 Kernel: 4.11.3-1-default x86_64 (64 bit gcc: 7.1.1) Desktop: Cinnamon 3.4.1  dm: sddm,sddm Distro: openSUSE Tumbleweed

cinnamon package info  https://gist.github.com/anonymous/abb7beb23c4f99f46815dcfe49f95722
cinnamon error https://gist.github.com/anonymous/bbd4c23cd2b1b23cebfcb8afcc0f351a

I am not sure if my /usr/lib64/libgtop-2.0.so.10 is the cause of the issue and i dont see ill effect.

**Comment by mtwebster** [comment]
One of your applets - probably a system monitor-type - is using GTop improperly, that applet needs to be fixed.  If for some reason it's cinnamonitor (which isn't on the Spices site) I've updated my repo for it and it can be updated also.

**Comment by two-dogs** [comment]
i think the issue is actually icing-task manager then, its the only thing i see complaining around the error

**Comment by jaszhix** [comment]
If you're seeing extra errors with ITM, I recommend upgrading it and your other xlets. That error shouldn't be caused by ITM though, which isn't using libgtop.

**Comment by two-dogs** [comment]
@jaszhix  my bad, i was wrong to blame the icing-taskbar
