### ISSUE TITLE
Last selected window not selected after workspace switch.

### ISSUE THREAD

**Issue by danchiba** [linuxmint/cinnamon#6587]
When I switch back to a workspace that I was working on, none of the windows are highlighted. Hitting Alt+Tab once results in the second-to-last window being selected, so I have to hit it twice (releasing the keys in between) to get back to the window I was working on.

This issue occurs intermittently, and I have not yet been able to narrow down the exact circumstances that cause it to occur.

**Comment by Cos-mo** [comment]
Which system / version.

I cannot reproduce this with Mint 18.2 beta 64 bit

**Comment by danchiba** [comment]
Oh sorry I forgot to add that information. It's Mint 18.1 64-bit with Cinnamon 3.2.7 and an Nvidia GeForce GT-610 graphics card. I also have a dual monitor setup. Either way, I don't think it's going to be easily reproduced unfortunately.

**Comment by Cos-mo** [comment]
Also with Mint 18.1 not reproducible here, but I do not have your graphics card and not a second monitor.

**Comment by icarter09** [comment]
@danchiba are you still experiencing this issue?
