### ISSUE TITLE
XTerm has the wrong icon in the window list.

### ISSUE THREAD

**Issue by scorpiosoft** [linuxmint/Cinnamon#6591]
XTerm does not use an official X Org icon.  It's a hideously ugly generic red X with a generic blue T on top of the X.  I can find no option anywhere to set/select an icon for an app.

![screenshot from 2017-06-08 12 44 01](https://user-images.githubusercontent.com/26280518/26942960-93d34372-4c49-11e7-968c-ee74399055eb.png)

In my launcher for XTerm, I can set whatever icon I want.  It's incongruous to have the window list look different from the launcher.  At a minimum give the option to make the window list icons match the launcher icons.

I am using the latest Cinnamon (2.8.6) available to an up-to-date Ubuntu 14.04.

FWIW, this is the first window manager I have ever used which uses that hideous icon.  All the other window managers have either used a generic icon, or the icon I put in the launcher.

**Comment by leigh123linux** [comment]
XTerm having a butt ugly icon isn't a cinnamon issue.

**Comment by scorpiosoft** [comment]
But Cinnamon can add the ability to make the window list icon match the launcher icon, or add the ability to edit window list icons.

**Comment by scorpiosoft** [comment]
This same kind of issue has been worked on in the past regarding Chrome/Chromium.

**Comment by leigh123linux** [comment]
The ugly icon is from whatever icon theme your using, you could use the menu editor to change the icon.
