### ISSUE TITLE
Main Cinnamon Menu sort search

### ISSUE THREAD

**Issue by janw-oostendorp** [linuxmint/Cinnamon#6592]
Not sure if this is the right repo, if not let me know.

Is it possible too rank search results on number of openings?
When I press the `super` and type `disp` and I open the _Display_ shortcut. Then that app should appear at the top next time I search `disp`.
Like [Albert](https://github.com/albertlauncher/albert) does. Not sure, but doesn't windows start menu also do this?

I've opened with the _Display_ pretty often but never even touched _Color_
![example search](https://user-images.githubusercontent.com/1026882/26971566-f5bd1314-4d0d-11e7-8874-fff3820182aa.png)

I couldn't find something like this in the settings, is it possible?

**Comment by imarkskinner** [comment]
Yeah, it's been asked over and over but never gets much attention. It's one of those stupid annoyances that most users have learned to live with.

https://github.com/linuxmint/Cinnamon/pull/848
https://github.com/linuxmint/Cinnamon/issues/2360
https://github.com/linuxmint/Cinnamon/issues/3644

**Comment by janw-oostendorp** [comment]
Also
#1320 
#4053

Really sad to see how old some of these requests are.
Don't need an other thread with the same stuff.
