### ISSUE TITLE
Working with Eclipse?

### ISSUE THREAD

**Issue by bernd-wechner** [linuxmint/Cinnamon#6594]
I'd like to consider contributing to Cinnamon but I can't seem to load the project in Eclipse. There's a .project file in the repo and I try to add it with "Import Projects from File System or Archive" and nothing is added. Also no errors reported not on screen or in the Error Log alas. Bizarre. I wonder if anyone has any experience with similar and what might be the underlying cause? 

I assume from the .project file (rightly or wrongly) that Cinnamon developers customarily work in Eclipse. I certainly do and would like to.

**Comment by JosephMcc** [comment]
Offhand I don't know of any of the devs who use eclipse. Most just use a text editor of choice and a terminal. In all honesty this probably hasn't been tested in a long time. The fact that no one has reported any issues with it makes me wonder how much people care that it even exists.

**Comment by bernd-wechner** [comment]
That's both surprising and encouraging. 

Surprising because I'm a little long in the tooth as a coder I guess and I wouldn't dream of leaving behind IDE features like autocompletion, code collapse, rapid navigation to declarations and a single keypress debugger that I can step through code with, examine the call stack and variables ... and I'm deeply embedded in this IDE with a number of projects I guess ... but I'm not judgemental either and I admire text editor coders (there are some cool editors out there that offer some, most possibly even all of that anyway while still wearing the humble name of text editor).

Encouraging, because it suggests the .project file is of no use to anyone and I can rebuild an eclipse project and possibly it would wash as a pull request if no-one's interested in the file.I admit I'm not sure if .project files have a broader use or significance than for the Eclipse IDE and that is possibility I am cautious of. 

Then again I could trash it, build a new one (takes a only a minute really and then check the differences.

Thanks for the update and insight into the dev culture. If anyone is using Eclipse of course, pipe up please.

**Comment by JosephMcc** [comment]
Considering that the .project file hasn't been touched since the initial creation of Cinnamon and it still has "gnome-shell" set in the name field, I would assume that no one really cares about this.

I doubt you would get much argument if you submit a PR for a working .project file. The only one I could see would be weather we should keep it all.

**Comment by bernd-wechner** [comment]
Cool. If existing devs are open to keeping the repo easy to access by all potential contributors and agree there's some value (if small given current base of Eclipse users in the dev team is apparently zero) I'll PR the .project update. It's not onerously bothersome and just means a newb who wants could clone the repo and open it Eclipse wittout bizarre errors.

The alternative, just nuking the .project file so at least no-one is getting misled is almost as good. Not stressed.
