### ISSUE TITLE
[FEATURE REQUEST] Add "paste into folder" operation to Quick Navigation menu items

### ISSUE THREAD

**Issue by ntkernel** [linuxmint/Cinnamon#6598]
When files/directories are previously copied, it would be nice if we can paste them into the folders
without opening the locations. Like in Win7/8.1/10.

![untitled](https://user-images.githubusercontent.com/11374581/26999227-dfb9a0b4-4dc6-11e7-9771-8cbb987038cd.png)

**Comment by leigh123linux** [comment]
You need to file the request against nemo.

**Comment by JosephMcc** [comment]
This works in the main views. Just not the sidebar.
