### ISSUE TITLE
New desktop features in Cinnamon 3.4 and launcher desklet

### ISSUE THREAD

**Issue by Cos-mo** [linuxmint/Cinnamon#6600]
Mint 18.2 beta Cinnamon 64 bit.

All the new features (grid, sorting and so on) do not work for the launcher desklet. This is a pity, as the launcher desklet does hardly differentiate from normal icons and reduces the enhancement of the new features (and / or the desklet).

Most likely this is merely a problem of the desklet itself, but as this is an official desklet, it should support the new Desktop features.

**Comment by JosephMcc** [comment]
While they may seem similar, they are two very separate things. They are not tied together in any way. Desklets have their own way of managing placement on the desktop. What you are asking for isn't really possible.
