### ISSUE TITLE
launcher icon size

### ISSUE THREAD

**Issue by clumsyfingers** [linuxmint/Cinnamon#6601]
just wondering why is const DEFAULT_ICON_SIZE = 20;
instead of 22 in /usr/share/cinnamon/applets/panel-launchers@cinnamon.org/applet.js
with 20 the launcher icons are blurry, 22 they are crisp and clear, and it doesent relly affect the panel either unless you are using a very thin panel. i thought i needed glasses until i discivered this tweak

**Comment by NikoKrause** [comment]
@clumsyfingers Can you create a pull request?

**Comment by JosephMcc** [comment]
Submitted a fix for this: https://github.com/linuxmint/Cinnamon/pull/7276
