### ISSUE TITLE
Password setting in account details

### ISSUE THREAD

**Issue by Cos-mo** [linuxmint/cinnamon#6609]
Mint 18.2 beta Cinnamon 64 bit

A new account (without admin-privileges), which (by default) has no password set, cannot create a password via account details. Even if the user defines a qualified new password and confirms it with a second entry, the OK button keeps grayed out - obviously because of the missing "old" password (which cannot be given, as it does not exist). This is obviously a limitation of the account detail dialog, not of the system itself, as the user can set a password easily on the command line.

As in Mint 18.2 a new account does no longer get added to the nopasswdlogin group (good change) it would be now an easy task, to create a new account and the new user could set up the password on its own. But this should be doable on the obvious graphical place (user applet -> account details) without the need to give the new user at first an advice, how to use the command line.

A consequential problem of this issue is, that a limited user cannot use the screensaver to lock his account. As long as no password is set the screensaver does never lock (not by timeout and not by shortcut do start the screensaver).

**Comment by Cos-mo** [comment]
Addition:

After having set the password for the limited account via passwd command it also impossible to remove it again. In difference to setting up a password this seems to be a limitation of the system, as the non-admin user cannot use passwd -d also.

But I do not see, why a limited user should not be allowed to remove the password again. If he is allowed to use his account without setting a password this does not make any sense to me. Having no user password in this case does also not affect the system at all, only his own data and privacy.

**Comment by icarter09** [comment]
@Cos-mo have you tested this out in the most recent versions? Mint 19.2 and Cinnamon 4.2.4
