### ISSUE TITLE
[Feature Request] Span Panel across Monitors Option

### ISSUE THREAD

**Issue by feren** [linuxmint/Cinnamon#6610]
What the title says. basically...

**Comment by mtwebster** [comment]
Panels have been implemented per-monitor.  This is far superior in every way.  I can't think of any reason to implement this (not even considering the development debt we'd incur for it.)

**Comment by gustavotrott** [comment]
I previously used Gnome with `dash-to-panel`, and the feature I miss the most is having a panel on every monitor, with each panel showing only the apps open on that monitor. 
It makes switching between programs much easier, without needing to return to the main screen every time. 

Having that feature here would be incredibly helpful.

**Comment by fredcw** [comment]
@gustavotrott 
> feature I miss the most is having a panel on every monitor, with each panel showing only the apps open on that monitor.

Can't you already do this? Add a panel with grouped-window-list applet on it to each monitor and in grouped-window-list applet settings: General>Behaviour>Show windows from other monitors>Only from monitors without a window list

**Comment by gustavotrott** [comment]
> [@gustavotrott](https://github.com/gustavotrott)
> 
> > feature I miss the most is having a panel on every monitor, with each panel showing only the apps open on that monitor.
> 
> Can't you already do this? Add a panel with grouped-window-list applet on it to each monitor and in grouped-window-list applet settings: General>Behaviour>Show windows from other monitors>Only from monitors without a window list

Yes, it worked perfectly. Thanks a lot!
