### ISSUE TITLE
Desktop background disappears

### ISSUE THREAD

**Issue by mikeglaz** [linuxmint/Cinnamon#6611]
When you extract a zipped file (i.e. .zip, .gz) and after 'Extraction completed successfully' you click on 'Show the Files' the desktop background reverts to the current Ubuntu Unity background.  You cannot change it at this point.  But a reboot fixes it.  However, if you click 'Quit' after 'Extraction completed successfully' this problem does not appear.

**Comment by JosephMcc** [comment]
When you click "Show the files", what file manager is being launched? If Nautilus is started it can control your background. That means the background drawn by Nautilus is covering the background drawn by Cinnamon. I believe there is a gsettings key for Nautilus that will allow you to turn this off.

**Comment by mikeglaz** [comment]
The only thing I found was in gnome-tweak-tools.  If you go to 'Desktop' and turn off 'Icons on Desktop' this solves the problem.  However, is it possible to have Archive Manager open up Nemo instead?

**Comment by JosephMcc** [comment]
In Cinnamon settings->Preferred Applications did you try setting the file manager to Nemo. I don't have nautilus here but I do have both Nemo and Caja installed. Changing it to Caja makes it use that.

**Comment by mikeglaz** [comment]
File Manager is not in Preferred applications

**Comment by JosephMcc** [comment]
Ah, ok. You didn't provide version info for anything. The setting was added in Cinnamon3.4 which allows you to control this.
