### ISSUE TITLE
OCR Feeder does not start from the menu

### ISSUE THREAD

**Issue by Cos-mo** [linuxmint/Cinnamon#6612]
Mint 18.2 beta Cinnamon 64 bit

After installing ocrfeeder the program does not start from the menu. The cause of the problem is not the application on its own, but the command line option -i, which gets added to the command during install. As soon as -i gets removed, the program launches as expected.

Comparing with Mint 17.3 / Cinnamon 2.8 shows, that there no option gets added to the command; in Mint 17.3 ocrfeeder launches from the menu without any problem.

I have no idea, why the option -i has been added to the command in Cinnamon now. This option is meant to add images at program launch, which have to be named also. The man page tells, that at least one named image is mandatory and this explains the issue. As the menu entry is supposed to get simply clicked the option -i does not make any sense.

**Comment by leigh123linux** [comment]
File the issue against ocrfeeder as they add -i

```
From: Alberto Garcia <berto@igalia.com>
Subject: Add code to the Exec key in order to open a file
Index: ocrfeeder/resources/ocrfeeder.desktop.in
===================================================================
--- ocrfeeder.orig/resources/ocrfeeder.desktop.in
+++ ocrfeeder/resources/ocrfeeder.desktop.in
@@ -4,7 +4,7 @@ Type=Application
 _Name=OCRFeeder
 _Comment=The complete OCR suite.
 TryExec=ocrfeeder
-Exec=ocrfeeder
+Exec=ocrfeeder -i %f
 Icon=/usr/share/ocrfeeder/icons/ocrfeeder.svg
 MimeType=image/bmp;image/gif;image/jpeg;image/jpg;image/pjpeg;image/png;image/tiff;
 Categories=Application;Office;
```
