### ISSUE TITLE
Vertical White Line on Cinnamon 3.4.1 - macOS-Sierra-Dark theme

### ISSUE THREAD

**Issue by ChristopherBare** [linuxmint/Cinnamon#6613]
There is a vertical white line is present on the opposite monitor that I am working on under cinnamon 3.4.1 with the macOS-Sierra-Dark theme. I have tried to change the theme and window settings, but nothing changes it. 
I have attached a screenshot of it if that helps:
![screenfetch-2017-06-14_14-40-55](https://user-images.githubusercontent.com/27033877/27152914-7f33b518-511d-11e7-8619-9af2065047d5.jpg)

**Comment by ChristopherBare** [comment]
It happens with all themes. Sorry for the bad wording.

**Comment by JosephMcc** [comment]
No problem. Just looking for clarification. I would have sworn that we saw this same issue in the past and it was sorted out.

**Comment by JosephMcc** [comment]
Ah here https://github.com/linuxmint/Cinnamon/issues/6326 and here https://github.com/linuxmint/Cinnamon/issues/5228
Read through the second one. If you are trying different Gtk themes make sure you log out and back in as the "desktop window" being talked about there may not properly update otherwise.

**Comment by ChristopherBare** [comment]
Thank you for the links to those, I applied the css to the nemo.css file under my current theme, but to no avail. The white line still remains.

**Comment by ChristopherBare** [comment]
The issue resolved itself somehow. I don't know what fixed it but evidently one of the recent updates did it. Update your stuff I guess.
