### ISSUE TITLE
An untranslatable string

### ISSUE THREAD

**Issue by otoman** [linuxmint/Cinnamon#6615]
In Cinnamon settings (module panel) is string "Panel %s:" where %s is height or width (in Czech _výška_ or _šířka_). Also there is string "Allow Cinnamon to scale panel text and icons according to the panel %s" and %s is the same (height or width) but in this case we need to translate it as _výšky_ or _šířky_. Can you please split these translations?

**Comment by NikoKrause** [comment]
I created a PR for that.

**Comment by otoman** [comment]
Thank you :)
