### ISSUE TITLE
microcode packages (intel-microde and amd64-microcode) thought

### ISSUE THREAD

**Issue by two-dogs** [linuxmint/Cinnamon#6617]
‎[01:39:51] ‎<‎pjotr‎>‎ Hello, I would like to discuss the microcode packages (intel-microde and amd64-microcode).
‎[01:40:10] ‎<‎pjotr‎>‎ In a few cases, installing the microcode package offered by Driver Manager, causes an unbootable system. It’s a risky package.
‎[01:40:24] ‎<‎pjotr‎>‎ Its description in Driver Manager is misleading, too: it reports that “this device isn’t working” when the microcode package isn’t installed. Obviously that’s untrue.
‎[01:40:41] ‎<‎pjotr‎>‎ Maybe it’s a good idea to remove this package from Driver Manager altogether, because it’s only seldom that the microcode in the BIOS isn’t sufficient.

all credit to pjotr (~pjotr@SpotChat...) , and i am not exactly sure where this issue/suggestion belongs but i have seen that from people who click on it, they wont believe that microcode is installed.

**Comment by Simon1NL** [comment]
I once suggested to someone having boot problems (fall back or crashes I'm not sure any more) to set that option to not be used and to my surprise the user reported next boot was okay.

**Comment by ManIVIctorious** [comment]
This is obviously a packaging/distribution issue and has nothing to do with the cinnamon desktop. Please file your issue to the linuxmint forum and close this one

**Comment by JosephMcc** [comment]
At the very least, move it here: https://github.com/linuxmint/mintdrivers
