### ISSUE TITLE
Onscreen keyboard: 2 is one too many

### ISSUE THREAD

**Issue by Cos-mo** [linuxmint/Cinnamon#6619]
Mint 18.2 beta Cinnamon 64 bit.

I see, that in 18.2 there is in addition to the old onscreen keyboard (I use this term for the one, which is already present in LM 18.1 and before) also onboard is installed by default (although the change-log does not tell anything about it).

This creates a problem: If I activate the onscreen keyboard with the respective accessibility option, I actually get now 2: the old one and onboard. As the old keyboard already occupies a great part of the screen, the onboard keyboard is always in the way to do any useful work. A setting to open only the one or other doesn't seem to exist. So the user has at first to close one of both, before he can do, what he needs to do.

Besides that I wonder, if the old keyboard is needed anymore at all. As onboard is not only less space consuming and can be moved, but is also far more powerful in configuration, there doesn't seem to be any need for the old keyboard. Also the login screen uses now onboard (perhaps the reason, why it is now by default installed?), the old keyboard should get removed.

In case this should not be doable out some reason, there should be at least an option in the accessibility settings to show only one keyboard.

Besides that it would be an enhancement for accessibility, if onboard could also directly be launched via menu (and of course as the only keyboard from the accessibility applet). Also the on-screen-keyboard applet needs some accommodations to let it run onboard only.

**Comment by leigh123linux** [comment]
https://github.com/linuxmint/Cinnamon/issues/6595

**Comment by JosephMcc** [comment]
> Besides that I wonder, if the old keyboard is needed anymore at all. As onboard is not only less space consuming and can be moved, but is also far more powerful in configuration, there doesn't seem to be any need for the old keyboard. Also the login screen uses now onboard (perhaps the reason, why it is now by default installed?), the old keyboard should get removed.

You need to keep in mind that these tools have a life outside of Mint. Just because Mint uses slick-greeter with Cinnamon doesn't mean it's used that way in other distros.
