### ISSUE TITLE
Accessibility: Wong and misleading translation in German

### ISSUE THREAD

**Issue by Cos-mo** [linuxmint/Cinnamon#6623]
Mint 18.2 beta Cinnamon 64 bit.

There is the option in the accessibility settings -> Mouse to simulate a secondary click by holding down the primary button.

In the German translation it says wrongly: Einen zweiten Klick auslösen. This means - retranslated - simulate a second(!) click. This is something quite different, meaning a kind of double click.

You could say instead: Einen sekundären Klick auslösen, but the word "sekundär" would in German language only be understood by a small minority. Better to understand would be to say: Einen Kontext-Klick auslösen (understandable, but strange wording) or Einen Rechts-Klick ausführen (well understandable, although for left-handed persons it would be just the opposite).

In any case: The current German translation is simply wrong.

**Comment by JosephMcc** [comment]
Translations are handled here: https://translations.launchpad.net/linuxmint/latest/+pots/cinnamon
