### ISSUE TITLE
Panel: no applets icons in vertical position

### ISSUE THREAD

**Issue by bionan** [linuxmint/Cinnamon#6625]
When the panel is vertical the applet icons disappear.
Please, see image.

[https://imagebin.ca/v/3QIH9iJ5xHYx](https://imagebin.ca/v/3QIH9iJ5xHYx)

**Comment by Cos-mo** [comment]
Which system, which version? I cannot reproduce it on LM 18.2 beta with default applets.

**Comment by germanfr** [comment]
Just disable "custom date format" in the calendar applet settings.
See this issue here #6109. It's the same problem.
