### ISSUE TITLE
Seamless auto-restart of cinnamon when user away/inactive and leaked RAM high

### ISSUE THREAD

**Issue by cmrdt** [linuxmint/Cinnamon#6628]
cinnamon maybe many windows, long session (several days), 
certain program/window combinations, media player playlist+repeats, use of transparency, auto-run-loop slideshows

over time somehow results in HUGE ram usage e.g. approx 1-9 GB of ram..
restarting of cinnamon reverts to lower ram state..
but after restart, transparency settings of windows are lost, 
taskbar-ordering of programs is changed, also, 

at times certain wine programs end-up in the wrong workspace

if smarter way to manage these problems.. , what could be improved
also maybe stress test of cinnamons, keyboard shortcuts of something to make
logging of (or temporary bypass of cinnamon-logs-size-limit) when cinnamon acting amok..

**Comment by JosephMcc** [comment]
There are already individual issues open addressing most of these things. If you have something to add to those then go ahead.
