### ISSUE TITLE
Any chance of official Global Menu?

### ISSUE THREAD

**Issue by viggy96** [linuxmint/Cinnamon#6629]
Saw on @lestcape that clement forked his stuff. (https://github.com/lestcape/Global-AppMenu) Will we ever get an official global menu for Cinnamon?

**Comment by JosephMcc** [comment]
> Saw on @lestcape that clement forked his stuff

@lestcape stuff was not forked by us.

> Will we ever get an official global menu for Cinnamon?

No. There are no plans to support this.

**Comment by JosephMcc** [comment]
Quick clarification. All the spices were forked by us but @lestcape stuff was removed at his request.
