### ISSUE TITLE
Gnome terminal won't launch

### ISSUE THREAD

**Issue by mellobob** [linuxmint/Cinnamon#6631]
From my account gnome-terminal (or gnome-terminal.real) will not launch. I get the following error (trimmed of duplicate gtk warnings):

: Gtk-WARNING **: Theme parsing error: gtk.css:199:22: Missing name of pseudo-class
Error constructing proxy for org.gnome.Terminal:/org/gnome/Terminal/Factory0: Error calling StartServiceByName for org.gnome.Terminal: GDBus.Error:org.freedesktop.DBus.Error.Spawn.ChildExited: Process org.gnome.Terminal exited with status 9

I've done some research and the suggestion is that there is locale problem. My locale shows as:
bob$ locale
LANG=en_US.UTF-8
LANGUAGE=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8

Gnome-terminal does work from other user accounts.

**Comment by leigh123linux** [comment]
It's a gnome-terminal issue.

**Comment by mellobob** [comment]
I don't disagree that it is a gnome issue. But, gnome-terminal is the default for cinnamon ... so, I do think there is a problem.

**Comment by leigh123linux** [comment]
Which version of Linuxmint are you using?

**Comment by mellobob** [comment]
I'm using Linux Mint 18.1 Serena . 

Gnome-terminal works in other user's environments. I think there is a config file of some kind in my directory that is buggering this up. I've deleted the .dbus directory and any local files I could find in .config. No differences made.

I've also remade my locale a number of times, both as root and user.

**Comment by leigh123linux** [comment]
File your issue against cinnamon-session

https://github.com/linuxmint/cinnamon-session/issues

I have seen this in fedora, I believe this pull helps this issue https://github.com/linuxmint/cinnamon-session/pull/91/commits/b92cc4ed3c71413a10f64a86e548d47133d203eb

Is system-wide locale UTF8?

**Comment by mellobob** [comment]
My user locale is all en_US.UTF-8. I just checked my /etc/default/locale:

cat /etc/default/locale
#  File generated by update-locale
LANG=en_US.UTF-8
LANGUAGE=en_US.UTF-8

So, that appears to be okay as well?

It really appears to me that the problem is in my user directory. I can launch the terminal fine as root:

  bob$ sudo gnome-terminal

Works as expected :)
