### ISSUE TITLE
add keyword filtering of alt+tab

### ISSUE THREAD

**Issue by cmrdt** [linuxmint/cinnamon#6633]
if could add esp if many windows present, 
(maybe partial /smart) keyboard filtering of windows (via graying out, similar to ffox tab-groups; or system-monitor app rapid-filtering)

maybe some combination of 

- process name
- window title
- command-line parameters

partial matching maybe for "Example Windowname"
- exam
- exmp
- win
- nam

maybe other filtering e.g.
- window size
- transparency
- ram/CPU usage (maybe conditional highlighting? formatting (color?) instead)
- all windows that are of same app-parent
- app responsiveness

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
