### ISSUE TITLE
Make menu also search display names or GenericName and Categories from .desktop files

### ISSUE THREAD

**Issue by stealz0ne** [linuxmint/cinnamon#6634]
When pressing the Menu key and typing in the text box, it appears that Menu only searches in the Name and Keywords (and Comment section) of the .desktop files of installed programs. However, it ignores info the GenericName and Categories tag.

I believe it is expected behavior by the users and developers that programs would be found by their generic name - and maybe Category and would be a quality of life upgrade especially for new users who do not know which program does what. 

Adding display names/GenericName and Categories to the search results in menu would make the quicklaunch function yield more - and more precise results, allow for better grouping and allow a wider array of search terms to lead you to your desired target program - especially if you want a broader search and dont know the exact term/name of what you're looking for.

**Comment by xenopeek** [comment]
A good example for this is HexChat. If you didn't know HexChat was your installed IRC client, you would expect to be able to find it by typing "IRC" in your menu but as that term is only in the GenericName and Categories fields (which the Cinnamon Menu doesn't search) it isn't found.

The relevant fields from the /usr/share/applications/hexchat.desktop file:

    Name=HexChat
    GenericName=IRC Client
    Comment=Chat with other people online
    Keywords=IM;Chat;
    Categories=GTK;Network;IRCClient;

The Cinnamon Menu doesn't currently search the GenericName ("display name" in Gnome terminology) or Categories fields. See https://github.com/linuxmint/Cinnamon/blob/master/files/usr/share/cinnamon/applets/menu%40cinnamon.org/applet.js#L3228.

I'm not quite sure on the code but I guess in https://github.com/linuxmint/Cinnamon/blob/master/src/cinnamon-app.c#L362 a function cinnamon_app_get_display_name needs to be added and used in above applet. GAppInfo has a function to get the name and display name of an application https://developer.gnome.org/gio/stable/GAppInfo.html#g-app-info-get-name.

**Comment by rik-shaw** [comment]
I do not see that Keywords are being searched (Cinnamon 3.6.7).  I thought there was an older issue I had submitted on that but can't find it.  Anyway, searching Name, Comment, Generic Name, Categories, and Keywords would all seem appropriate.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
