### ISSUE TITLE
Background changes to black after inserting USB

### ISSUE THREAD

**Issue by CaptainKirksChair** [linuxmint/Cinnamon#6635]
Whenever I insert a USB thumb drive, the desktop background dissolves to black. Restarting Cinnamon (Alt-F2) does not work. Restarting Xorg or restarting Cinnamon from tty do fix the immediate problem. Inserting the USB will cause the same problem again. Inserting USB devices (mouse, keyboard, printer, etc.) cause no problem.

My system:
`System:    Host: Kernel: 4.4.0-53-generic x86_64 (64 bit gcc: 5.4.0)
           Desktop: Cinnamon 3.2.7 (Gtk 3.18.9-1ubuntu3.2) Distro: Linux Mint 18.1 Serena
Machine:   System: Apple product: iMac9 1 v: 1.0
           Mobo: Apple model: Mac-F2218EA9 Bios: Apple v: IM91.88Z.008D.B08.0904271717 date: 04/27/09
CPU:       Dual core Intel Core2 Duo E8135 (-MCP-) cache: 6144 KB
           flags: (lm nx sse sse2 sse3 sse4_1 ssse3 vmx) bmips: 10612
           clock speeds: max: 2660 MHz 1: 1596 MHz 2: 2128 MHz
Graphics:  Card: NVIDIA C79 [GeForce 9400] bus-ID: 03:00.0
           Display Server: X.Org 1.18.4 drivers: nouveau (unloaded: fbdev,vesa) Resolution: 1680x1050@60.00hz
           GLX Renderer: Gallium 0.4 on NVAC GLX Version: 3.0 Mesa 11.2.0 Direct Rendering: Yes
Audio:     Card NVIDIA MCP79 High Definition Audio driver: snd_hda_intel bus-ID: 00:08.0
           Sound: Advanced Linux Sound Architecture v: k4.4.0-53-generic
Network:   Card-1: NVIDIA MCP79 Ethernet driver: forcedeth port: 21e0 bus-ID: 00:0a.0
           IF: enp0s10 state: down mac: <filter>
           Card-2: Broadcom BCM4322 802.11a/b/g/n Wireless LAN Controller driver: wl bus-ID: 04:00.0
           IF: wlp4s0 state: up mac: <filter>
Drives:    HDD Total Size: 320.1GB (8.4% used) ID-1: /dev/sda model: WDC_WD3200AAJS size: 320.1GB
Partition: ID-1: / size: 34G used: 6.0G (19%) fs: ext4 dev: /dev/sda5
           ID-2: /boot size: 969M used: 60M (7%) fs: ext4 dev: /dev/sda2
           ID-3: /home size: 256G used: 17G (7%) fs: ext4 dev: /dev/sda6
           ID-4: swap-1 size: 3.15GB used: 0.00GB (0%) fs: swap dev: /dev/sda4
RAID:      No RAID devices: /proc/mdstat, md_mod kernel module present
Sensors:   System Temperatures: cpu: 53.0C mobo: N/A gpu: 82.0
           Fan Speeds (in rpm): cpu: 1197
Info:      Processes: 193 Uptime: 22 min Memory: 1010.2/7728.3MB Init: systemd runlevel: 5 Gcc sys: 5.4.0
           Client: Shell (bash 4.3.481) inxi: 2.2.35  `

**Comment by leigh123linux** [comment]
Provide some logs that show the error otherwise I will have to close the issue as 'insufficient info'
