### ISSUE TITLE
Drag mode stuck after suspend/resume

### ISSUE THREAD

**Issue by amarao** [linuxmint/cinnamon#6637]
cinnamon: 3.2.7-2 (ubuntu zetsy)

After some normal work I've putted my laptop to sleep. Next morning after wake and unlocking (lock by cinnamon-screensaver) there was a cursor with icon with looked like 'item drag' in menu. That cursor was able to move but unable to click anywhere.

Here piece from .xsessions-errors:

(cinnamon-settings-daemon:2100): color-plugin-WARNING **: failed to reset xrandr-LVDS1 gamma tables: gamma size is zero
Cjs-Message: JS LOG: An active wireless connection, in infrastructure mode, involves no access point?
Cjs-Message: JS LOG: An active wireless connection, in infrastructure mode, involves no access point?
Cjs-Message: JS LOG: Removing a network device that was not added
Cjs-Message: JS LOG: Removing a network device that was not added
Cjs-Message: JS LOG: Invalid network device type, is 14
Cjs-Message: JS LOG: Invalid network device type, is 14
Cjs-Message: JS LOG: pushModal: invocation of begin_modal failed

(cinnamon:2324): Cjs-WARNING **: JS ERROR: TypeError: currentDraggable is null
_getEventHandlerActor/<@/usr/share/cinnamon/js/ui/dnd.js:56

(cinnamon:2324): Cjs-WARNING **: JS ERROR: TypeError: currentDraggable is null
_getEventHandlerActor/<@/usr/share/cinnamon/js/ui/dnd.js:56

(last message repeated thousands of times).

I killed cinnamon process from linux console and run cinnamon --replace to fix this.

**Comment by icarter09** [comment]
Mint 18.2 
cinnamon 3.4.6
64-bit

I'm not able to duplicate this error. I set the screenlock through cinnamon-screensaver and then allowed the lock out to occur and then came back to computer in different increments (5min, 15min, 30min, 1hr, 4hr). Each time the cursor did not change to another icon and was also able to click on wherever I choose. 

@amarao am I doing the steps you talked about correctly? If so, I'm wondering if this bug has been fixed and is no longer valid.

**Comment by amarao** [comment]
I'm now at cinnamon-screensaver 3.4.2-1 (cinnamon 3.4.6-1), I didn't saw that bug for a few months. Unfortunately, as always with such bugs, it's hard to say if it disappeared or not.

**Comment by icarter09** [comment]
Thanks for the update @amarao. Hopefully, it has been resolved.

**Comment by Vahan86** [comment]
@amarao, is this still an issue with Cinnamon 4.x?

**Comment by amarao** [comment]
I hadn't saw it for years, I'd say it resolved.
