### ISSUE TITLE
Shutdown and logout dialog prevent screensaver from locking

### ISSUE THREAD

**Issue by michael-schaller** [linuxmint/Cinnamon#6640]
If the shutdown or logout dialog is shown then the screensaver can't be locked via hotkey anymore and doesn't automatically lock anymore. I presume this is because these dialogs hold an X keyboard grab.

Edit:
Can the implementation of the shutdown and logout dialogs be changed to behave more like a Gtk Dialog with _NET_WM_STATE_ABOVE?

**Comment by NikoKrause** [comment]
It's a feature not a bug

**Comment by michael-schaller** [comment]
@NikoKrause Could you elaborate why you consider this a feature instead of a bug?

**Comment by michael-schaller** [comment]
Let me also give more context. One of our users reported that he wanted to suspend his machine via the shutdown dialog and he switched off his monitor while pressing the Suspend button. He only realized the following morning that he had missed the Suspend button and that the machine was unlocked the whole night because the screensaver couldn't automatically activate.

**Comment by JosephMcc** [comment]
> Could you elaborate why you consider this a feature instead of a bug?

It's not. The core problem is the same as other open issues where having a menu open prevents the lock screen from kicking in. These things essentially put a hold on anything else until they are dealt with.

**Comment by michael-schaller** [comment]
@JosephMcc I agree on that this is an issue with how top level windows and grabs work in X and the X developers made it clear that this can't be fixed. See this excellent and funny talk, specifically 31:40 for top level windows and grabs: https://www.youtube.com/watch?v=RIctzAQOe44

I'm not asking to fix X though. I'm asking to change the implementation of the shutdown and logout dialogs to behave more like a Gtk Dialog with _NET_WM_STATE_ABOVE.

**Comment by clefebvre** [comment]
hi @michael-schaller, there's an option in System Settings -> General, which lets you enable a timer for the shutdown dialog.

**Comment by michael-schaller** [comment]
@JosephMcc Thanks for the pull request. That was easier than I thought.

@clefebvre Thanks. That is indeed a viable workaround.
