### ISSUE TITLE
Blank screen at login screen if the computer is left on it.

### ISSUE THREAD

**Issue by alextpedro** [linuxmint/Cinnamon#6643]
If I leave the computer on after it reached the login screen, without actually logging in, the screen eventually goes blank. Moving the mouse or using the keyboard won't get me the screen back, not even typing my password and pressing enter. The only solution is to restart the system and login before the screen goes blank.

**Comment by leigh123linux** [comment]
File the issue against the login screen (mdm for 18.1 or less and slick-greeter for 18.2).
