### ISSUE TITLE
Screensaver / Lockscreen No Longer Engages When Lid Closed

### ISSUE THREAD

**Issue by AdmiralAsshat** [linuxmint/Cinnamon#6645]
Distro: Fedora 64-bit, Cinnamon Spin 
Kernel: 4.11.6-201.fc25.x86_64

After updating the latest Cinnamon packages, the lock screen has stopped working.

Here is what was updated from the `dnf history` log:

`    Upgraded cinnamon-3.4.1-2.fc25.x86_64                 @updates
    Upgrade           3.4.2-1.fc25.x86_64                 @updates
    Upgraded cinnamon-desktop-3.4.1-1.fc25.x86_64         @updates
    Upgrade                   3.4.2-1.fc25.x86_64         @updates
    Upgraded cinnamon-screensaver-3.4.0-1.fc25.x86_64     @updates
    Upgrade                       3.4.1-1.fc25.x86_64     @updates
    Upgraded cinnamon-session-3.4.0-6.fc25.x86_64         @updates
    Upgrade                   3.4.1-1.fc25.x86_64         @updates
    Upgraded cinnamon-settings-daemon-3.4.1-1.fc25.x86_64 @updates
`

I discovered after closing my laptop for the night and opening it the next morning that the lockscreen/screensaver had not engaged, and my laptop is still unlocked. Hotkey combinations (`Ctrl + Alt + L`) and manually selecting the "Lock Screen" button from the menu don't appear to do anything, either.

I don't see anything written to the `.xsession-errors` file when I try to manually lock the screen. Below is the only snippet I was able to find, which occurred when I closed the lid:

`(csd-power:2056): power-plugin-WARNING **: Could not connect to cinnamon-screensaver: Error calling StartServiceByName for org.cinnamon.ScreenSaver: GDBus.Error:org.freedesktop.DBus.Error.Spawn.ChildExited: Process org.cinnamon.ScreenSaver exited with status 1`

Please let me know if there's any other information I can provide.

EDIT: I did see #6640 and it may be related, but that issue seemed to only be when the screenlock was combined with the logout dialogue. I am unable to get the lockscreen to engage at all.

**Comment by leigh123linux** [comment]
Why report it here?, I deal with fedora issues on redhat bugzilla

Try updating

https://bodhi.fedoraproject.org/updates/FEDORA-2017-4349ca6a71

```
sudo dnf install python3-xapp
sudo dnf update
```

The first command is to install a missing dep for screensaver

https://bodhi.fedoraproject.org/updates/FEDORA-2017-105df1be27

If that fails to fix the issues post

```
cinnamon-screensaver-command -l
```

**Comment by AdmiralAsshat** [comment]
All good. python3-xapp and a reboot fixed it. I'll bookmark the bugzilla for next time. Thanks!
