### ISSUE TITLE
Impossible to disable XRandr plugin after Cinnamon 3.4 upgrade

### ISSUE THREAD

**Issue by dRaiser** [linuxmint/Cinnamon#6646]
Hi, I've upgraded Cinnamon to latest version and it's now impossible to disable XRandr plugin. In previous version it was possible to do like so:

`gsettings set org.cinnamon.settings-daemon.plugins.xrandr active false`

But currently, that key doesn't even exists and if it's added, it's ignored. Is there any way to disable xrandr support? I need it to ignore monitor hotplug events, to not let OS shuffle my windows everywhere when I use input switching.

**Comment by leigh123linux** [comment]
Try disabling the autostart file /etc/xdg/autostart/cinnamon-settings-daemon-xrandr.desktop (move, rename or delete it).

**Comment by dRaiser** [comment]
Renamed file, killed process and it worked! Thank you!

**Comment by philippludwig** [comment]
So this file does no longer exist, how can I disable it now? This is really annoying. My second monitor is on the left of my primary one, and when I configure this, after a few seconds cinnamon puts it back to the right.
