### ISSUE TITLE
Bluetooth Speaker -  auto connect and play from speaker

### ISSUE THREAD

**Issue by teamspoad** [linuxmint/cinnamon#6654]
MINT 18.2 x64 - 
Bluetooth speaker.  BOSE SOUNDLINK MINI

Desired action:  After initial BT speaker setup, when I power on my speaker, Linux should connect to bluetooth, and switch sound output to the speaker, and start playing from the new speaker (as it does in Windows)

Current Action:  I have to open bluetooth applet, select speaker to connect to, usually involves clicking on/off switch numerous times, then I open sound settings and switch output to the BT speaker (which sometimes doesn't show up at all, even thought it says connected, needing to restart entire proceedure until it is found).

It would also be nice to be able to set a personal nickname of the Bluetooth device, as some are just awful coded messes of model numbers and such.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
