### ISSUE TITLE
Huge icons in alt-tab dialog

### ISSUE THREAD

**Issue by ieowl** [linuxmint/Cinnamon#6655]
I'm getting huge icons in the alt-tab dialog, as seen here: 

https://i.imgur.com/Iua98Wm.png

I get this same behavior regardless of which GTK, desktop/cinnamon, or icon theme I use. Not unusable, but pretty garish and ugly and probably not intended.

I suspect this may be related to the high res, hidpi nature of my screen: I'm using a Chromebook Pixel which has a native resolution of 2560x1700, but I believe by default the effective resolution is half that (with scaling), so 1280x850.

Note that when I set it to thumbnails it looks fine, but personally I don't like that because they're small enough that I can't tell the difference between 2 windows that are largely the same color.

**Comment by mtwebster** [comment]
https://github.com/linuxmint/Cinnamon/commit/273aff4c6a7fa8ee6a70196d24e5ab9b39aa7e50

It was not the icons, but the rest of the alt-tab elements that were being sized incorrectly.
