### ISSUE TITLE
"Run with NVIDIA GPU" should be using Optirun on Optimus setups

### ISSUE THREAD

**Issue by stefanocorona12** [linuxmint/Cinnamon#6656]
Cinnamon 3.4.3 on Arch Linux

If I open the applications, right clicking on an application will allow me to "Run with the NVIDIA GPU".
Some applications are launching, others are crashing. If the application launches, it is not utilizing the Nvidia GPU. GNOME 3 has a working implementation of this.

**Comment by leigh123linux** [comment]
It currently uses optirun

https://github.com/linuxmint/Cinnamon/blob/master/files/usr/share/cinnamon/applets/menu%40cinnamon.org/applet.js#L173

If it crashes or fails to function it's an arch optirun issue not cinnamon
