### ISSUE TITLE
Alt+tab icon HIDPI scaling error on Cinnamon 3.4.2

### ISSUE THREAD

**Issue by mmirg** [linuxmint/Cinnamon#6657]
I'm experiencing an icon scaling error and resulting text misalignment when alt+tab is set to display icons (with or without window previews).  I've tested this behavior with a number of different icon sets in an attempt to verify that it was not an issue with icon incompatibility.  I did not see this behavior with Cinnamon 3.2.  User interface scaling is set to "auto" on my system and normally scales to "double Hi-DPI" on my 282 ppi display.

I'm running Gentoo (Funtoo) and Cinnamon was just upgraded to 3.4.  Component upgrade timings are somewhat off from Linux Mint, so for reference here are the upgrades that that came with the 3.4:  cinnamon 3.4.2, cinnamon-desktop 3.4.2, cjs 3.4.1, cinnamon-menus 3.4.0, cinnamon-settings-daemon 3.4.2, muffin 3.4.0 and nemo 3.4.4.  The image below illustrates the issue that I have encountered:

![alt_tab icon](https://user-images.githubusercontent.com/4317194/27667609-eb3b12ba-5c49-11e7-9c6a-8cc9fa4f3cbc.png)

**Comment by ieowl** [comment]
I opened #6655 2 days ago and it was fixed in commit [273aff4](https://github.com/linuxmint/Cinnamon/commit/273aff4c6a7fa8ee6a70196d24e5ab9b39aa7e50)

**Comment by mmirg** [comment]
Apologies for the duplicate issue.
