### ISSUE TITLE
alert when system strained, low on resources

### ISSUE THREAD

**Issue by cmrdt** [linuxmint/Cinnamon#6659]
e.g. if detect when 
- low on ram
- system janky/hanging, high latency, seems slow
- CPU/parts abnormal temp/voltages, overheating

notify the user, alert to relevant details(so dont go blindly), maybe provide mitigation options (? kill offending app, lower its priority, black/white-lists, timer-to-action, throttle app, shut down non-critical, restart cinnamon)

**Comment by JosephMcc** [comment]
If there was a tool like this it shouldn't be Cinnamon specific.
