### ISSUE TITLE
Notifications feature requests: Choose corner, display, stacking, etc.

### ISSUE THREAD

**Issue by killthealias** [linuxmint/cinnamon#6663]
For Cinnamon's notifications I would like to request the following features:  
**Choose which corner to display in**  
Allow us to choose which corner of our display the notifications will display in.  
**Display**  
Allow us to choose if notifications will appear on our primary display or all displays.  
**Stacking**  
Allow us to see multiple notifications in succession instead of switching to the new one immediately. 
**Dismiss**  
Allow us to dismiss a notification to clear screen space immediately instead of waiting for it to fade.

**Comment by Xeronel** [comment]
+1 for Dismiss. Having the notification sit in the way can make me get very impatient when I'm busy.

**Comment by JosephMcc** [comment]
You can dismiss notifications any time by simply clicking anywhere on them.

**Comment by killthealias** [comment]
No, that takes me to the application that sent the notification.

**Comment by JosephMcc** [comment]
Ah, you are correct.

**Comment by Hilyxx** [comment]
+1 killthealias 
I would like to able to disable/enable notifications for each program like gnome control center or pantheon settings

![notification-settings-details](https://user-images.githubusercontent.com/21991448/32886079-db088334-cabf-11e7-8d0f-eb2ec5a5c455.png)
![elementary-os-loki-notification-system](https://user-images.githubusercontent.com/21991448/32886080-db2b2b14-cabf-11e7-8118-509d325d7b34.jpg)

**Comment by pioneer** [comment]
+1 for choosing which corner to display in, as Cinnamon Tweaks extension no longer works in Cinnamon 3.6.

**Comment by pioneer** [comment]
Any idea how to patch the JS code until the issue is fixed?

**Comment by ltgouvea** [comment]
It would be nice to have keyboard shortcuts to dismiss notifications as well, I didn't find a way to configure it

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
