### ISSUE TITLE
Quick scrolling in applications sometimes causes temporary blackout screen flashes

### ISSUE THREAD

**Issue by TopView** [linuxmint/Cinnamon#6668]
A) How to observe this:

I started out with intermittent black flashing in FireFox that was annoying.  I noticed that it happened in every app that i scrolled in, not just FireFox.  Even as I scroll up and down here in FireFox I get black flashing within the main scroll sub-window.  

B) Another way to observe this (or a separate related screen artifact): 

1 Download [cinnamon english_18.0.pdf](https://www.linuxmint.com/documentation/user-guide/Cinnamon/english_18.0.pdf). 
2 Then open it with Evince Document Viewer.  
3 Now resize the window so there is some extra space around it on all 4 sides.  
4 Then quickly slide the scroll bar on the right from top to bottom, and back and forth, or up and down a few times.  As you do this watch the upper left of the window.  

From time to time I see an additional black frame around the window at the top and left of roughly 1 cm in width.

I didn't notice this happening in the previous version of cinnamon that I had used (2.?) on Debian Jessie.

I tried resetting cinnamon with `dconf reset -f /org/cinnamon/` but this did not fix the issues.

I also tried several themes but that also didn't affect this.

--------------

(I thought I read that some of the composting or something like that was re-written.  I don't really know how to look for this issue.  In my day I might have hooked up a hardware tracer to capture the code leading up to it.)

Love cinnamon!  Thank you for it.

-----------
My system:  `inxi -Fxz` gives me:

System:    Host: Love2d Kernel: 4.9.0-3-amd64 x86_64 (64 bit gcc: 6.3.0)
           Desktop: Cinnamon 3.2.7 (Gtk 3.22.11)
           Distro: Debian GNU/Linux 9 (stretch)
Machine:   Device: laptop System: Hewlett-Packard product: HP Pavilion dv7 Notebook PC v: Rev 1
           Mobo: Hewlett-Packard model: 3624 v: 18.51
           BIOS: Hewlett-Packard v: F.46 date: 08/25/2011
Battery    BAT0: charge: 29.4 Wh 100.0% condition: 29.4/40.0 Wh (74%)
           model: Hewlett-Packard Primary status: Full
CPU:       Dual core Intel Core2 Duo P8800 (-MCP-) cache: 3072 KB
           flags: (lm nx sse sse2 sse3 sse4_1 ssse3 vmx) bmips: 10639
           clock speeds: max: 2667 MHz 1: 1600 MHz 2: 1600 MHz
Graphics:  Card: Advanced Micro Devices [AMD/ATI] RV710/M92 [Mobility Radeon HD 4530/4570/545v]
           bus-ID: 01:00.0
           Display Server: X.Org 1.19.2 drivers: ati,radeon (unloaded: modesetting,fbdev,vesa)
           Resolution: 1600x900@59.98hz, 1920x1080@60.00hz
           GLX Renderer: Gallium 0.4 on AMD RV710 (DRM 2.48.0 / 4.9.0-3-amd64, LLVM 3.9.1)
           GLX Version: 3.0 Mesa 13.0.6 Direct Rendering: Yes
Audio:     Card-1 Advanced Micro Devices [AMD/ATI] RV710/730 HDMI Audio [Radeon HD 4000 series]
           driver: snd_hda_intel bus-ID: 01:00.1
           Card-2 Intel 82801I (ICH9 Family) HD Audio Controller
           driver: snd_hda_intel bus-ID: 00:1b.0
           Sound: Advanced Linux Sound Architecture v: k4.9.0-3-amd64
Network:   Card-1: Intel PRO/Wireless 5100 AGN [Shiloh] Network Connection
           driver: iwlwifi bus-ID: 02:00.0
           IF: wlan0 state: up mac: <filter>
           Card-2: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller
           driver: r8169 v: 2.3LK-NAPI port: 5000 bus-ID: 03:00.0
           IF: eth0 state: down mac: <filter>
Drives:    HDD Total Size: 500.1GB (55.7% used)
           ID-1: /dev/sda model: Samsung_SSD_850 size: 500.1GB
Partition: ID-1: / size: 30G used: 15G (49%) fs: btrfs dev: /dev/sda6
           ID-2: /var size: 5.0G used: 3.7G (76%) fs: btrfs dev: /dev/sda8
           ID-3: /home size: 57G used: 23G (41%) fs: btrfs dev: /dev/sda10
           ID-4: /tmp size: 3.0G used: 4.6M (1%) fs: ext2 dev: /dev/sda7
           ID-5: swap-1 size: 4.29GB used: 0.00GB (0%) fs: swap dev: /dev/sda5
Sensors:   System Temperatures: cpu: 65.0C mobo: N/A
           Fan Speeds (in rpm): cpu: N/A
Info:      Processes: 242 Uptime: 10 min Memory: 2232.6/7955.4MB
           Init: systemd runlevel: 5 Gcc sys: 6.3.0
           Client: Shell (bash 4.4.121) inxi: 2.3.5

**Comment by leigh123linux** [comment]
Try using the default PDF reader for mint (xreader) instead of evince and see if it reproduces.

> 2 Then open it with Evince Document Viewer.

**Comment by TopView** [comment]
@leigh123lin@ux, Thanks, and as I mentioned this happens in "every app that i scrolled in", so it's not just linked to the PDF reader.  Today I even saw an event where scrolling in one window, produce a black flash in an unrelated window.

(Debian does not have a package for xreader.  FWIW, I did try to build it but got too many errors.)

**Comment by leigh123linux** [comment]
You should report this to debian bug tracker as your using an old version that's unlikely to be fixed here as it's EOL

> Desktop: Cinnamon 3.2.7 (Gtk 3.22.11)
Distro: Debian GNU/Linux 9 (stretch)

If you can reproduce with cinnamon-3.4.x feel free to reopen.
