### ISSUE TITLE
[Nemo & Cinnamon Bug] On-Screen Keyboard causes Desktop Icons to lower on the screen

### ISSUE THREAD

**Issue by feren** [linuxmint/Cinnamon#6670]
**I wasn't sure which repo to put this issue in because, it's linked to Cinnamon 3.4's On-Screen Keyboard, AND Nemo 3.4's Desktop Process.** Basically, when I have the Desktop Icons sorted in Horizontal with Auto-arrange on, and then toggle on the "Virtual Keyboard", the Desktop Icons lower, followed by going back to where they were before when the Keyboard is deactivated...

**Comment by JosephMcc** [comment]
In 3.6 the keyboard is moved to the top and is supposed to affect the struts so those items aren't hidden when the keyboard is shown.
