### ISSUE TITLE
Please remove gksu dependency from Cinnamon

### ISSUE THREAD

**Issue by jbicha** [linuxmint/Cinnamon#6674]
gksu has been deprecated for years. It is better for app developers to use PolicyKit to only use elevated privileges for the specific actions they are needed.

gksu will be removed from Debian so it is important that Cinnamon stop using gksu soon.

The Debian maintainer identified several places in the code where gksu is being used.
https://bugs.debian.org/856699

See also https://github.com/linuxmint/Cinnamon/issues/3565

**Comment by lestcape** [comment]
@jbicha if is a priority to you: https://github.com/linuxmint/Cinnamon/pull/6336

**Comment by Fantu** [comment]
As reported by marga seems there are 4 things that still use pkexec:
1) Make /usr/bin/cinnamon-remove-application use polkit
2) Make /usr/sbin/mdmsetup use polkit (it's not part of this package)
3) Make /usr/share/cinnamon/cinnamon-settings/bin/installSchema.py and 
/usr/share/cinnamon/cinnamon-settings/bin/removeSchema.py use polkit
4) Make 
/usr/share/cinnamon/cinnamon-settings-users/cinnamon-settings-users.py 
use polkit

About the 4 I saw that there was already the polkit rules file about and fedora already use pkexec for it in its packages from long time, so I did a PR accepted for cinnamon 3.6.
About 2 seems that linux mint now use lightdm instead, so I suppose will be removed.
Remain the 1 and 3, I saw https://github.com/linuxmint/Cinnamon/pull/6336/files, need a rebase, I take a fast look and some things do not seem good to me like elseif of pkexec/gksu/kdesudo and the install of applet/extension I thing should be user only for security and stability reason (and admin permission not needed)
@clefebvre @maxyz @marga-debian @leigh123linux I not have good experience for optimal valuation and do the right and better thing probably, is there someone more expert that can take a look please?

**Comment by AsciiWolf** [comment]
Any news?

**Comment by Fantu** [comment]
Small update:
2) seems not needed anymore after migrate of lightdm
4) solved
other things about applets, spices ecc... seems still need changes:
https://github.com/linuxmint/Cinnamon/search?utf8=%E2%9C%93&q=gksu&type=

Someone more expert can do it please?

**Comment by eli-schwartz** [comment]
So 4) was resolved via #6827 which means I can drop that distro patching, but I think you still need to add e.g. `RequiredComponents=polkit-gnome-authentication-agent-1` to `files/usr/share/cinnamon-session/sessions/cinnamon*.session`

I cannot find one that cinnamon already includes or uses, except remnants in configure.ac from a cinnamon-polkit-agent removed in 2013.

**Comment by clefebvre** [comment]
https://github.com/linuxmint/Cinnamon/commit/596f495f8a9517e7d06646fa02fd6e680f666f54

**Comment by Fantu** [comment]
@clefebvre thanks
