### ISSUE TITLE
Right Click Breaks Screen Saver Lock Screen During Suspend

### ISSUE THREAD

**Issue by FeralBytes** [linuxmint/Cinnamon#6676]
```
 * Cinnamon v3.2.7
 * Distribution - Mint 18.1 x64-bit; Kernel 4.4.0-81-generic
 * Graphics hardware Nvidia 950M Driver 375.66
 ```

**Issue**
Screen saver is not locked upon resume from suspend when the right click menu is actively displayed in Nemo.
This is a security concern too. 

**Steps to reproduce**
1. Right click in Nemo file manager; put the laptop into suspend by shutting the screen. 
2. Open the laptop screen.
3. Observe that you can see your screen and that it is not locked.

**Expected behaviour**
During step 3 the screen should be locked any ways. 

**Other information**
It may require Cinnamon to force a left click on the desktop to prevent a right click menu context from blocking the screen saver from taking over the screen.

**Comment by leigh123linux** [comment]
The issue is misfiled, cinnamon-screensaver does the locking.
cinnamon 3.2.x is also EOL

**Comment by FeralBytes** [comment]
@leigh123linux refilled here: https://github.com/linuxmint/cinnamon-screensaver/issues/258
