### ISSUE TITLE
Allow delayed focus stealing based on user input

### ISSUE THREAD

**Issue by wrouesnel** [linuxmint/cinnamon#6678]
I normally have focus stealing allowed on my desktop because I find it can lead to me ignoring things happening in other windows or on other desktops.

But - this leaves me vulnerable to the "sudden pop up takes input" problem which is the main grudge point of focus stealing.

What I need is a middle-ground: I want to allow focus stealing, but ensure it doesn't intrude - I'd like to be able to configure focus stealing to be delayed while there's active input from the keyboard or mouse on a cooldown, defaulting to say 1000ms or so. And I'd like to prevent any input going to a window which is stealing focus on a cooldown as well - defaulting from say 1000ms with a range of 0 to infinity (i.e. require me to explicitly click the window title bar or something to enable input).

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
