### ISSUE TITLE
auto-save-session not working, ramps up CPU usage if selected

### ISSUE THREAD

**Issue by ouiliam** [linuxmint/Cinnamon#6681]
```
 * Cinnamon version 3.4.3
 * Distribution - Mint 18.2
 * Graphics Intel Atom Processor Z36xxx/Z37xxx drivers: intel (unloaded: fbdev,vesa)
 * 64 bit
 ```

**Issue**
when cinnamon's auto-save-session selected, does not work and CPU usage rises dramatically
(i also had gnome auto-save-session on)

**Steps to reproduce**
select in dconf-editor
reboot with apps in several workspaces open and they are not saved
CPU use ramps up

**Expected behaviour**
apps are brought back how they were before reboot
CPU use remains normal

**Other information**
Graphics:  Card: Intel Atom Processor Z36xxx/Z37xxx Series Graphics & Display
           Display Server: X.Org 1.18.4 drivers: intel (unloaded: fbdev,vesa)
           Resolution: 1366x768@59.99hz
           GLX Renderer: Mesa DRI Intel Bay Trail GLX Version: 3.0 Mesa 12.0.6

**Comment by JosephMcc** [comment]
I'm not sure what the cause of the CPU spiking is but session saving is not currently supported. There is a reason it isn't  exposed anywhere in the settings :) We have some open feature requests for things related to it but nothing is currently in the works.
