### ISSUE TITLE
Option to hide menu bar in applications

### ISSUE THREAD

**Issue by teejee2008** [linuxmint/Cinnamon#6682]
```
 * Cinnamon version : 3.4.3
 * Distribution - Mint 18.2
 * Graphics hardware *and* driver used: Intel Graphics Broadwell
 * 32 or 64 bit; 64
 ```

Please add an option to hide the application menu bar inside applications. This option can be used along with global menu applets to free up vertical space on the desktop.

Xfce provides options to hide the menu bar:
```bash
xfconf-query -c xsettings -p /Gtk/ShellShowsMenubar -n -t bool -s true
xfconf-query -c xsettings -p /Gtk/ShellShowsAppmenu -n -t bool -s true
```
Gnome Shell also has an option for this in ```~/.config/gtk-3.0/settings.ini```
```ini
[Settings]
gtk-shell-shows-app-menu=true
gtk-shell-shows-menubar=true
```
Something similar in Cinnamon would be nice.

**Comment by ghettoparazite** [comment]
Yes, please.

**Comment by JosephMcc** [comment]
This sort of thing has been requested before. We aren't interested in implementing it ourselves but patches would be considered depending on how much they effect and how much maintenance would be required.
