### ISSUE TITLE
[Feature Request] Automatic Restart of Cinnamon if crash is detected

### ISSUE THREAD

**Issue by feren** [linuxmint/Cinnamon#6683]
Basically, it'd be more seamless and nice if when Cinnamon Crashes, it automatically calls another 'cinnamon --replace' before exiting out, as well as then displaying a little error message saying what happened, as the average Joe would otherwise be wondering what happened if the Fallback Message doesn't appear for them, about why they're now on a GNOME 2 wannabe rather than their normal Cinnamon Desktop.

**Comment by JosephMcc** [comment]
This is asking for trouble. You could end up in a loop of cinnamon constantly restarting. Cinnamon shouldn't be crashing so often that this is needed. If it is the source of the issue needs to be troubleshot and hopefully solved.
