### ISSUE TITLE
Horizontal icon spacing on HiDPI displays is too large (2x)

### ISSUE THREAD

**Issue by squared9** [linuxmint/Cinnamon#6684]
```
 * Cinnamon version 3.44
 * Distribution - Mint 18.2
 * Graphics hardware: Intel Corporation Broadwell-U Integrated Graphics (rev 09)
                   intel(0): Using Kernel Mode Setting driver: i915, version 1.6.0 20151010
 * 64 bit
 ```

**Issue**
On a HiDPI (in my case 3200x1800) display horizontal icon spacing with auto align is double of what I would expect - please see:
http://imgur.com/a/usVyR

**Steps to reproduce**
Just switch HiDPI on, make sure auto align is on and do e.g. auto-arrange or move icons manually.

**Expected behaviour**
Icon spacing should be either reduced or made configurable. Currently HiDPI desktop's usability regressed comparing to older Cinnamon.

**Other information**
Please do not turn on icon auto-arrange by default, it changes desktop one is used to without any reason.

**Comment by JosephMcc** [comment]
> Please do not turn on icon auto-arrange by default, it changes desktop one is used to without any reason.

Not trying to sound offensive but not knowing the reason doesn't mean there isn't one. Having it enabled by default was needed to make things work for people upgrading from a previous version.

**Comment by mtwebster** [comment]
This issue was moved to linuxmint/nemo#1550
