### ISSUE TITLE
Linux Mint 144hz and 60hz dual monitors problem

### ISSUE THREAD

**Issue by medzernik** [linuxmint/Cinnamon#6685]
```
 * 3.2
 * Mint 18.2
 * Nvidia GTX 1060, nvidia 382 series (from PPA, also tried on official nvidia-375)
 * 64 bit
 ```

**Issue**
Compositor syncs all refresh rates to the lowest value if you have 2 monitors with different refresh rates, making games unplayable, moving windows around unusable.

**Steps to reproduce**
Get 2 monitors, one 144hz, second 60hz -> enable 144hz on the main monitor -> play a game (or try to move with windows)

**Expected behaviour**
The main monitor should have 144hz refresh rate, not some obscure 60hz trying to draw 144hz and coliding.

**Other information**

**Comment by JosephMcc** [comment]
https://github.com/linuxmint/Cinnamon/issues/6575
