### ISSUE TITLE
network@cinnamon.org List goes out of screen bounds, no scrollbar. 

### ISSUE THREAD

**Issue by deepsidhu1313** [linuxmint/Cinnamon#6686]
```
 * Cinnamon version 3.4.4 
 * Distribution - Mint 18.2
 * Graphics hardware Nvidia 920 M *and* driver used are Nviidia 375.66
 * 64 bit
* Screen Resolution 1366x768 (14")


 ```

**Issue**
* Network List goes beyond screen dimensions.
![screenshot nm](https://user-images.githubusercontent.com/7684338/27988644-5c35b8fe-63ec-11e7-8cb3-85432c0b592f.png)

* And shows mobile networks even the section(Mobile Broadband) is disabled.

**Steps to reproduce**
* Have more than 10 wireless access points & 10 Mobile Broadband Connections. I guess that will do it.

**Expected behaviour**
* There should be a scrollbar to show the list

**Other information**

**Comment by JosephMcc** [comment]
Thanks for reporting. We already have an open issue here: https://github.com/linuxmint/Cinnamon/issues/5660
