### ISSUE TITLE
Sound volume shows 0% when there is 20% volume. 

### ISSUE THREAD

**Issue by piotrekkr** [linuxmint/Cinnamon#6689]
```
 * Cinnamon 3.4.4
 * Distribution - Mint 18.2
 * 64 bit
 ```

**Issue**
When increasing sound volume  for first time after login, sound applet (?) (this thing that pops out when changing volume, forgot it's name) shows 0% volume, even when there is 20% sound volume set. Increasing sound few times more (like to 30-35%) fixes problem. 

**Steps to reproduce**
 * Login in, 
 * Use keyboard button for increasing volume once
 * Use button few times more

**Screenshots**
![screenshot from 2017-07-09 10-01-54](https://user-images.githubusercontent.com/503782/27992238-986840aa-648f-11e7-9c75-0cfec7ffac3b.png)
![screenshot from 2017-07-09 10-02-28](https://user-images.githubusercontent.com/503782/27992239-986d31fa-648f-11e7-92a4-8b534f603446.png)

**Comment by JosephMcc** [comment]
I just noticed this issue today.

**Comment by piotrekkr** [comment]
I'll add that sometimes when there is 0% volume and I'll hit volume down button few times and then volume up button once, popup suggest that there is few % volume set even when there is 0%. I think there should be:
 * volume above 0% => show green bar and white speaker with white arks
 * when 0%  => show no green bar and gray waves, but white speaker
 * muted => show no green bar, grey sound waves, grey speaker

Now it seems like when going from muted to 0% is shown as few % volume. Screenshots:

![screenshot from 2017-07-09 19-36-24](https://user-images.githubusercontent.com/503782/27996279-1c2db9ac-64df-11e7-87a5-29b4fdc2d009.png)
![screenshot from 2017-07-09 19-36-31](https://user-images.githubusercontent.com/503782/27996280-1c3040c8-64df-11e7-80b6-4ce5bbcf4759.png)
