### ISSUE TITLE
no mouse interaction with panel and menu

### ISSUE THREAD

**Issue by eldadroobol** [linuxmint/Cinnamon#6693]
```
 * Cinnamon version: 3.4.4
 * Distribution: Linux Mint 18.2 Cinnamon 64-bit
 * Graphics hardware: NVIDIA GeForce GTX 650 (version 304.135)
 * 64 bit
 ```

**Issue**
After upgrading from linux mint 18.1 to 18.2 I can no longer interact with my panel and menu.
Using the keyboard to access the menu works properly but no hover feedback is shown and clicking a mouse button does not do anything.

**Steps to reproduce**
Upgrade from 18.1 to 18.2 (this is a poor reproduction scenario since I have it on one machine only)

**Expected behaviour**
I should be able to use my mouse :)

**Other information**
This only happened on one machine.
Using a fresh user does not help which indicates to me that it is not the specific configuration of my user.
I upgraded a different machine, this has no issues at all.

**Comment by leigh123linux** [comment]
nvidia 304.135 isn't listed as supporting GeForce GTX 650

**Comment by eldadroobol** [comment]
And that was the issue appearantly. I'd had some issues with kernels and such after upgrading so appearantly I downgraded my driver during that confusion. That was not the resolution I expected, but thanks!  Driver  375.66 fixed it.
