### ISSUE TITLE
New windows in Firefox don't open maximized

### ISSUE THREAD

**Issue by ranolfi** [linuxmint/cinnamon#6695]
Using Cinnamon 3.4.3 in Arch Linux with Firefox 54.

I have Firefox in a maximized window. Whenever I open another (new) window, either with the Control + N shortcut or simply launching FF from the Menu, it opens in a non-maximized state (albeit taking the entire screen). In other words, it appears to be maximized, but really isn't.

This is an issue because the cursor changes to an expanding feature near the border of the screen when the window is not maximized, messing up navigation.

To be clear, this doesn't affect the first FF window lauched, only the subsequent ones.

The expect behavior is of course to launch all windows maximized, like the first one.

[edit] Expanding on why it messes up navigation, mainly:
- The scroll bar. If the window is maximized, you instinctively point your cursor to the rightmost side of the screen, click, and move your mouse. If the window isn't maximized, you're trolled instead.
- The close button: a similar issue occurs.

**Comment by marc2377** [comment]
Maybe related: #1199

**Comment by pols12** [comment]
> To be clear, this doesn't affect the first FF window lauched, only the subsequent ones.

My session often start with 3 windows (reopens old session), and they are never maximized.

**Comment by calestyo** [comment]
I have the same... seems to only happen with FF... and only with Cinnamon

**Comment by Vahan86** [comment]
I can't reproduce this issue. It works fine for me in Cinnamon 4.4.5.

@ranolfi, is this still an issue for you with Cinnamon 4.4?

**Comment by calestyo** [comment]
Here it's at least still at 4.2.4... cannot test the most recent version right now...

**Comment by leigh123linux** [comment]
This is a FF issue not cinnamon.

**Comment by calestyo** [comment]
> This is a FF issue not cinnamon.
See https://github.com/linuxmint/cinnamon/issues/6695#issuecomment-481746698 ... it appears to happen only with Cinnamon

**Comment by ranolfi** [comment]
@Vahan86: Fortunately, no - the reported issue has been fixed at some point.

I still note that when "dragging down" an open tab from an existing Firefox window, it opens the tab on a new, non-maximized window though. Of course, this is a different behaviour than the one I first reported.

FWIW, Chromium behaves as expected in this case, and launches the tab on a new maximized window.
