### ISSUE TITLE
Selecting "Follow link to original file" from an item in the Destop makes all icons disappear

### ISSUE THREAD

**Issue by marc2377** [linuxmint/Cinnamon#6696]
Cinnamon 3.4.3 on Arch Linux.

I have a symbolic links in my Desktop to various files.

Right-clicking one of them and clicking "Follow Link to original file" should open a new Nemo window with the desired location. However it refreshed the Desktop.

I tried a second time and now all my Desktop icons are gone.

Restarting Cinnamon from Melange doesn't fix the issue. Crashing Cinnamon also doesn't. Nor does restarting Nemo.

**Comment by sevenskull** [comment]
It started in Mint 18.2 (cinnamon), after the update from 18.1, when i do what is described by @marc2377 it tries to follow the file from the desktop, then crash.

**Comment by mtwebster** [comment]
Already fixed: https://github.com/linuxmint/nemo/issues/1549
