### ISSUE TITLE
Feature request: make the 'recent documents' applet more useful by adding 'open containing folder'

### ISSUE THREAD

**Issue by CottonEaster** [linuxmint/Cinnamon#6698]
The 'recent documents' applet - which, I believe, is built into Cinnamon - does not enable one to open the folder containing a recent document. That feature is available in, for instance, the Firefox download window - and it is very useful.

(This feature request was submitted initially to [linuxmint/cinnamon-spices-applets](https://github.com/linuxmint/cinnamon-spices-applets/issues/1026#issuecomment-315276222).)

**Comment by RealMtwebster** [comment]
ah yes, what a great idea
