### ISSUE TITLE
Overlay scrollbars is not in an obvious place in Settings and searching for 'overlay' or 'scroll' doesn't find it

### ISSUE THREAD

**Issue by CottonEaster** [linuxmint/Cinnamon#6701]
Settings at issue:

alt-tab;
disable compositing in full screen windows;
overlay scroll bars.

These exactly the sorts of settings people will use the search function to find - but, at present, to no avail.

```
 * Cinnamon version: 3.4.4.
 * Distribution - Mint 18.2
 ```

**Issue**

**Steps to reproduce**

**Expected behaviour**

**Other information**

**Comment by mtwebster** [comment]
Cinnamon settings->Effects

**Comment by CottonEaster** [comment]
If Mint aims to be an unusually accessible Linux distribution, then settings should be easy to find. Consider: if it is great when an intuitive search - a search for the word that occurs to one - finds the right setting within Settings, then what is it when that _fails_ to happen? Consider also that judicious adding of keywords - in some cases, merely _the very names_ (or partial names) _of the settings themselves_ - would achieve the better of those two outcomes.

We have here - in this precise case but also in very similar cases to do wth finding settings - an elementary way to make the use of the OS easier.

Surely you can just add a few words to a bit of code to make this happen. I do not see why you would not.
