### ISSUE TITLE
12 hour mode doesn't work properly with Russian locale

### ISSUE THREAD

**Issue by rizado** [linuxmint/cinnamon#6703]
```
 * Cinnamon version: 3.2 - 3.4.4
 * Distribution: Ubuntu 16.04.2, Fedora 26.
 * Hardware and driver independent
 * 32 or 64 bit: both
 ```
**Issue**
When I use 12-hour mode, Cinnamon doesn't display AM/PM mark in Russian locale, in English it works fine.

**Steps to reproduce**
1. Install Cinnamon.
2. Set custom format for time: %H:%M:%S %P
3. Switch between Russian and English locales some times.

**Expected behaviour**
I expect properly displaying of time with any locale. Why I cannot use 12 hour with Russian settings?

**Other information**
Please fix it.

**Comment by icarter09** [comment]
@rizado are you still experiencing this issue?

**Comment by Vahan86** [comment]
@icarter09, can we close the issue?
