### ISSUE TITLE
Thunderbird notification co-incided with my clicking a launcher on the panel. Result: system hang.

### ISSUE THREAD

**Issue by CottonEaster** [linuxmint/Cinnamon#6704]
```
 * Cinnamon 3.4.4
 * Distribution - Mint 18.2
 * Intel onboard graphics
 * 64 bit
 ```

**Issue**

Please see title

**Steps to reproduce**

It will be hard to reproduce, because the problem seemed to owe to my clicking on the (perfectly functional) launcher exactly when a notification arrived. Perhaps this situation, or a similar one, could be generated programmatically.

**Expected behaviour**

**Other information**

**Comment by itzexor** [comment]
I tried to reproduce this using `sleep 1; notify-send "test"` and clicking a panel launcher at the same time as the notification popped up. I wasn't able to reproduce it yet. Were you right clicking or left clicking the applet? Also is this the standard panel launcher applet or a third party one?

**Comment by CottonEaster** [comment]
Thank you for your work, itzexor.

I *left*-clicked the applet, I believe.

I _believe_ that the applet is third-party (although one cannot easily tell this from within Cinnamon - should I file a bug report for that? Certainly it is an infelicity). The applet is called 'command Launcher'. See [here](https://cinnamon-spices.linuxmint.com/applets/view/139). I am unsure which of my two instances of that launcher that I ran. Here is what each of them does.

**Command run by the *first* instance of command launcher applet**
`nohup xfce4-terminal --geometry 89x25+150+85 -x /usr/bin/myScripts/Update/update &`

**Command run by the *second* instance of command launcher applet**
`/opt/sublime_text/sublime_text -a ~/.conkyrc`

**Comment by itzexor** [comment]
All spices extensions are third party. I was testing with the stock panel-launchers@cinnamon.org applet. I will try again with Command Launcher.

**Comment by CottonEaster** [comment]
Thank you for investing the Command Launcher applet.

PS: Ah, something is an extension - and thus third-party - if it appears somewhere (anywhere) on the 'spices' website. OK. Yet, not all applets are third-party. (Hence your original question.) *My point was that it should be easier to tell the third-party from the inbuilt applets*. Still, I suppose that lock icon in the (unlabelled) colum in the Settings -> Applets menu does give one the answer, so long as one knows how to interpret that window. But I don't want to de-rail my own bug report . .

**Comment by itzexor** [comment]
I agree that it is a bit confusing to figure out exactly which are standard and which are third-party.

Unfortunately, I am still unable to reproduce this issue with the method described above and using Command Launcher to launce `xfce4-terminal` or `sublime_text`. Unless you can find a related error message or something, I'm not sure that I can figure this one out.

**Comment by CottonEaster** [comment]
OK, well I'll close the issue for now and try to re-open it if the problem recurrs. If it does recur I'll note the time and investigate what my logs contain for that time.

**Comment by mtwebster** [comment]
FYI, stock or standard applets will have a little lock symbol on their row in cinnamon settings.

**Comment by CottonEaster** [comment]
mtwebster: thanks, but I knew that already. I wrote the following above.

> Still, I suppose that lock icon in the (unlabelled) colum in the Settings -> Applets menu does give one the answer, so long as one knows how to interpret that window.
