### ISSUE TITLE
About menu of applet does not show version

### ISSUE THREAD

**Issue by mcarans** [linuxmint/Cinnamon#6705]
```
 * Cinnamon version 3.4.4
 * Distribution - Mint 18.2
 * Graphics hardware *and* driver used - Intel with Intel driver
 * 64 bit
 ```

**Issue**
The About menu of the applet Icing Task Manager does not show the version.

Jason Hicks author of the applet Icing Task Manager told me to open an issue here rather than on Cinnamon Spices. 

I said: "The About menu of Icing Task Manager should contain the current version number. At the moment it says: 2017-07-07 08:25:06 UTC which doesn't help much as when I updated from an older version the date did not change."

Jason said: "They changed this in Cinnamon. Please open an issue there."
https://github.com/linuxmint/cinnamon-spices-applets/issues/1035

**Steps to reproduce**
Go to About menu of Icing Task Manager

**Expected behaviour**
Shows a version

**Other information**

**Comment by jaszhix** [comment]
![screenshot from 2017-07-18 13-58-15](https://user-images.githubusercontent.com/6859057/28334653-67240068-6bc1-11e7-9603-81ba2354bf44.png)

It seems to be showing the version string for me on the git build.

**Comment by mcarans** [comment]
![noversionicing](https://user-images.githubusercontent.com/3799212/28351259-f2e4c96a-6c4e-11e7-9226-b74b9aa6115b.jpg)

I have attached what I see. There is no version just a date.

**Comment by NikoKrause** [comment]
The timestamp is the version.
If you install an applet (officially) through Cinnamon Settings, you'll see the timestamp.

If you press `last commit` on spices website https://cinnamon-spices.linuxmint.com/applets/view/269
You'll geht to the commit history https://github.com/linuxmint/cinnamon-spices-applets/commits/master/IcingTaskManager@json
There you see, currently the newest version is from 19 July.

Your about dialog says you are running an older version from 7 July.

So each update/commit on the spices repos is a new version, shown through the timestamp in the about dialog.

If you install an applet manually though, there is no timestamp to show. It shows instead a "version number", which the dev made on his own, if he made one. (And not every dev is creating or even updating version numbers)

So showing autogenerated timestamps for each applet is the new version number system in LM 18.2 Sonya.

**Comment by NikoKrause** [comment]
To update your applet go to System Settings -> Applets -> Available applets (online) 
There hit the "Refresh list" button and apply available updates. The timestamp should change to 19 July

**Comment by mcarans** [comment]
Thanks that all worked (the refresh list is not very obvious btw).

I would suggest having version strings perhaps in addition as it is easier and more intuitive to raise issues when you can specify a version rather than a timestamp.

**Comment by NikoKrause** [comment]
As I said. Versions are manual and rely on des to update it regularly. Timestamps are automatically generated and available for all spices. So those are more specific and reliable.

**Comment by mcarans** [comment]
I think it should be a basic requirement on devs to update the version number. If you cannot trust them to do that, can users trust the extensions that they write? 

Why not show both version and timestamp?

**Comment by jaszhix** [comment]
I think it might be helpful if people know what the date means. Up until now, I thought it was the install date of the applet, so I opened the referenced PR above. Adding "Last Published" before the date could help prevent confusion. I also prefer referencing semantically versioned things over dates - easier to remember.

**Comment by NikoKrause** [comment]
We show versions and timestamps in Cinnamon 3.6 now.
