### ISSUE TITLE
Feature Request: Better Method for Updating Spices

### ISSUE THREAD

**Issue by mfreeman72** [linuxmint/cinnamon#6706]
```
 * Cinnamon version 3.4.4
 * Distribution - Mint 18.2
 * Graphics hardware *and* driver used: AMD A8 (Radeon R5) and Open Source Mesa driver
 * 64 bit
 ```

**Issue**

Feature Request: Better Method for Updating Spices

It is currently a relatively involved process to keep Applets, Desklets, Extensions, and Themes updated. I would like to see any one of the following methods implemented to maintain an up-to-date feature set:

1. Test and then package up all of the Spices into .deb files in the Mint repositories, according to compatibility with Cinnamon version included in each supported Mint version. Any new updates get tested and updated in the repos so that they are updated through the standard packaging system. Users can have the option of installing and maintaining them system-wide through this method, or installing and maintaining them on a per-user-account basis using the current method. This packing can be done with volunteers, if necessary. Or perhaps run a community repository through the LM community website.

2. Include a section of the Mint Update tool that monitors the Spices website and offers updates to those that are installed on the currently logged-in user account, as well as an optional auto-update feature.

3. Create a Spices Update tool that runs on a per-user-account basis, rather than system-wide, that monitors the Spices website and offers updates to those that are installed on the user account, as well as an optional auto-update feature.

4. Have Cinnamon itself optionally check the Spices website for updates and automatically update them on a user-selected time interval.

**Comment by JosephMcc** [comment]
We have other open issues requesting this same thing. I'm going to close some of those and linked them to this one since it's a bit nicer.

This is something that gets discussed internally though I'm not sure if any decisions have been made. The solution should be cross distro though since Cinnamon is not limited to Mint or deb based distros in general.

**Comment by mfreeman72** [comment]
@JosephMcc Thank you, and I apologize. I did a search (although the search feature is not very intuitive on github), and did not see these. I'll be more careful next time.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
