### ISSUE TITLE
Scroll during windows expo does not work since LM 18.2 update

### ISSUE THREAD

**Issue by KevinNadaud** [linuxmint/Cinnamon#6707]
```
 * Cinnamon version 3.4.4
 * Distribution - Linux mint 18.2 Cinnamon (upgrade from 18.1 and 18)
 * Graphics hardware *and* driver used :  
Card: Intel Sky Lake Integrated Graphics bus-ID: 00:02.0 chip-ID: 8086:1916
Display Server: X.Org 1.18.4 drivers: (unloaded: fbdev,vesa) Resolution: 1920x1080@60.01hz
GLX Renderer: Mesa DRI Intel HD Graphics 520 (Skylake GT2)
GLX Version: 3.0 Mesa 12.0.6 Direct Rendering: Yes
 * 64 bit
 ```

**Issue**
Scroll during windows expo does not work. 
Expo being grey, and zoom of the windows does not occurs. Sometimes it is not possible to quit expo. Must relaunch cinnamon because expo does not switch of.

**Steps to reproduce**
Launch expo, scroll on a windows. The screen will be more grey and you need to relaunch cinnamon

**Expected behaviour**
The windows size must change and it should be possible to quit expo.

**Other information**

**Comment by itzexor** [comment]
Log out, then log in, so you get a clean session log. Reproduce the issue, and then upload `~/.xsession-errors` and `~/.cinnamon/glass.log`.

Before uploading them you may want to edit out any personal information that may exist in the log. I can't guarantee anything, but this may help us find the cause of the issue if there are any errors logged.

**Comment by itzexor** [comment]
It may also be worth trying to use modesetting driver instead of the intel driver. If you want to try that, additional details can be found here: https://www.linuxmint.com/rel_sonya_cinnamon.php under the `Cinnamon freezes when changing resolution (Intel GPU)` heading

**Comment by mtwebster** [comment]
Also, can you make another user and try to reproduce with clean settings?  Can't reproduce this here..

**Comment by itzexor** [comment]
We were able to reproduce this with scale view. If you want you can try this patch[1] to see if it helps your issue. Thanks.

[1] https://github.com/itzexor/Cinnamon/commit/35b7ed6ee4f87bb0a27a98a407cf895ff7ad8fe6

**Comment by KevinNadaud** [comment]
Here the log files.
[xsession-errors.txt](https://github.com/linuxmint/Cinnamon/files/1158309/xsession-errors.txt)
[glass.log.txt](https://github.com/linuxmint/Cinnamon/files/1158311/glass.log.txt)

I already remove the intel driver (I made the change with the 18.1 version). 

How can I apply the patch ?

**Comment by KevinNadaud** [comment]
I apply the patch, it works well. 
Thanks !

**Comment by itzexor** [comment]
Thanks for testing. You don't need to do anything more. You'll need to run the patched version until a fixed version is released, though.

I need to investigate it some more, as there are additional warnings, and prepare a patch for merge. I'll reference this issue whenever I get that done so you'll know when it's fixed in master.
