### ISSUE TITLE
Placement of applet icons on panel is erratic

### ISSUE THREAD

**Issue by kyphi** [linuxmint/cinnamon#6713]
```Cinnamon 3.4.4
    Linux Mint 18.2
    64 bit
    On 2 computers, one using the nouveau driver and the other using  the nvidia 340 driver with a nvidia   GTS 450 graphics card.
  ```

**Issue**
Arranging applet icons on the bottom panel is impossible because the Updater icon insists on remaining on the left of any added icons.

**Steps to reproduce**
Try it and see.  Independently substantiated by a fellow user.

**Expected behaviour**
That the Updater icon can be moved to a user-chosen location.

**Other information**
This can actually be accomplished if the panel is temporarily moved from the bottom of the screen to the top and then moved back to the bottom position once the task has been completed.

**Comment by icarter09** [comment]
@kyphi are you still experiencing this issue?

**Comment by Vahan86** [comment]
@icarter09, can we close the issue since there is no response from OP?
