### ISSUE TITLE
Tooltips: it would be good were they enlargabl

### ISSUE THREAD

**Issue by CottonEaster** [linuxmint/Cinnamon#6715]
```
 * Cinnamon version: 3.4.5.
 * Distribution: Mint 18.2
 * Intel onboard graphics
 * 64 bit
 ```

Perhaps I overlook some theme setting or other setting, but it seems to me that the size of (at least most) panel tooltips is fixed. Now, this is a problem for me because, with a slightly-larger than average pointer (that owes to my pointer theme) the pointer overlays tooltips, making the tooltips (1) hard to read, (2) look bad. I'll provide a video or screenshot if necessary.

EDIT: Or perhaps it is the _positioning_ of the tooltips that should be changed.

**Comment by CottonEaster** [comment]
Here is an example of the sort of thing that I think really should be avoided in a distribution that sets usability at a premium:

![image](https://user-images.githubusercontent.com/9998846/29582853-bf80745e-876d-11e7-965c-c236f752b5cd.png)

This occusion of the tooltip by the pointer occurs even when using the 'Cinnamon' desktop theme. Even were my pointer smaller, it would still look bad and make the tooltip hard to read.

**Comment by leigh123linux** [comment]
Rejercted!

**Comment by RealMtwebster** [comment]
Life is going to reject you @leigh123linux !
