### ISSUE TITLE
Need to customize system datetime formatting

### ISSUE THREAD

**Issue by mubat** [linuxmint/cinnamon#6716]
* **Cinnamon version:** Cinnamon 3.0.7
 * **Distribution:** Linux Mint 18
 * Intel Corporation Mobile 4 Series Chipset Integrated Graphics Controller (rev 09)
 * 64 bit

Mint Cinnamon has no functionality to customize datetime formatting for whole system. 

A lot of applications use system datetime format what I want to change to my preffered. But I can't do this using system settings.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
