### ISSUE TITLE
thumbnails previews move compat list titles

### ISSUE THREAD

**Issue by artik** [linuxmint/Cinnamon#6717]
```
 * Cinnamon 3.4.4
 * Mint 18.2
 * Geforce 1080 proprietary drivers
 * 64 bit
 ```

**Issue**

In the file browser, the generated icons move compat list titles: http://i.imgur.com/ohVr34W.png

**Steps to reproduce**

Create an image (long banner for example), and another one (high). The thumbail will make the titles not displayed properly.

**Expected behaviour**

Titles should be aligned

**Other information**

**Comment by leigh123linux** [comment]
File the issue against nemo.
