### ISSUE TITLE
The inbuilt launcher applet silently replaces user-choosen icons with icons from current them

### ISSUE THREAD

**Issue by CottonEaster** [linuxmint/Cinnamon#6718]
**What happens / to reproduce**: add an instance of the launcher applet to the panel; chose an icon for that instance - an icon not in the current icon theme; see what happens.

**What should happen**: either the user should be told the chosen icon has been rejected or the chosen icon should be accepted or (best?) the user should be told the chosen icon is not in the theme but offered the option to use it anyway.

Cinnamon: 3.4.4.

**Comment by JosephMcc** [comment]
Please use the included issue template.

**Comment by CottonEaster** [comment]
```
 * Cinnamon version: 3.4.4
 * Distribution - Mint 18.2
 * Intel on-board graphics; Mesa DRI Intel 965GM; Mesa 2.1
 * 64 bit
 ```

**Issue**

If I add an instance of the launcher applet to the panel, and then choose an icon for that instance - an icon not in the current icon theme - then the resulting icon is selected from the current icon theme nonetheless.

**Steps to reproduce**

Add an instance of the launcher applet to the panel; chose an icon for that instance - an icon not in the current icon theme; see what happens.

**Expected behaviour**

Do you mean 'expected' in the normative sense or alternatively in the predictive sense? I'll take you as intending the normative sense. So: either the user should be told the chosen icon has been rejected or the chosen icon should be accepted or (best?) the user should be told the chosen icon is not in the theme but offered the option to use it anyway.


**Other information**
