### ISSUE TITLE
Inbuilt launcher applet's launch-in-terminal option does not honour the terminal chosen in Preferred Applications 

### ISSUE THREAD

**Issue by CottonEaster** [linuxmint/Cinnamon#6719]
Mint 18.2.
Cinnamon 3.4.4

To see/reproduce: set the Preferred terminal to something other than Gnome; create a launcher; tell the launcher to use the terminal; run the launcher.

I imagine that this problem would be simple to fix.

**Comment by JosephMcc** [comment]
https://github.com/linuxmint/Cinnamon/issues/5269
