### ISSUE TITLE
[Feature Request] Allow Customisation of Cinnamon's Applet Menu Animation

### ISSUE THREAD

**Issue by feren** [linuxmint/Cinnamon#6725]
Basically, it would be nice to be able to change the animation when opening or closing a menu spawned by a Cinnamon Applet out-of-the-box in a way that's univeral towards all applets, in a similar fashion to how you can change the main Window Manager Animations in 'Effects'.

Some ideas for this:
Rise - The current one
Fade - A More Windows-esque Animation for Menus
Slide - An Animation based on the Slide animation from Windows 9X where the menu would rise from the summoned position until it reaches its height
Door - Comes up from the panel in a door fashion where open would be the "door" closing, and close would be it opening, but the "door" in question then being sideways

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
