### ISSUE TITLE
Exfat delete on my trash...bad idee

### ISSUE THREAD

**Issue by Mintactus** [linuxmint/Cinnamon#6730]
```
 * Cinnamon version (cinnamon --version)
Linux Mint 18.2
Nvidia 340.102
64 Bits
 ```

The "delete" option in the context menu of Nemo 3.4.6 when it's a exFAt rw mount partition do not delete the folder, they try to put it in my trash i think.

Try to delete a folder in a exFAT without via context menu without put it on your trash.

**Expected behaviour**

**Other information**

**Comment by leigh123linux** [comment]
Please file the issue against nemo
