### ISSUE TITLE
Desktop is blurred after crash + restart

### ISSUE THREAD

**Issue by Photon-GitHub** [linuxmint/Cinnamon#6733]
```
 * Cinnamon version 3.4.4
 * Distribution - Mint 18.2 Sonya
 * Graphics hardware *and* driver used - GTX 1080 Ti, latest proprietary drivers from NVidia (as provided in the driver manager: 381.22)
 * 64bit
 ```

**Issue**
After the restart that the screen is no longer sharp with clear edges (as prior to the crash) but blurred as if somebody applied a Gaussian blur filter to the whole desktop, opened programs and basically everything the display shows. Newly opened programs (after the crash has happened) have the same blurred appearance.

The bug happens always (after each crash of the Cinnamon desktop I experienced so far). 
After a reboot everything is displayed correctly once again.

**Steps to reproduce**
After a crash of the Cinnamon desktop use the option to restart it instead of going into fallback mode.

**Expected behaviour**
The desktop is not blurred.

**Other information**
The only option I have touched in the driver settings that could affect this is setting the antialiasing to 16x with override.

**Comment by mIwebster** [comment]
on behalf of all linux mint, this is unacceptable and I will make sure it is fixed for you

**Comment by leigh123linux** [comment]
You should check and fix your broken X driver.

```
after each crash of the Cinnamon desktop
```
