### ISSUE TITLE
Panel launcher allows same item to be edited in > 1 window; crash

### ISSUE THREAD

**Issue by CottonEaster** [linuxmint/Cinnamon#6734]
```
 * Cinnamon version:
 * Distribution - Mint 18.2
 * Intel onboard graphics 965GM Mesa 2.1 17.1.4
 * 64 bit
 ```

**Issue**

The panel launcher applet allows same item to be edited in > 1 window. By playing around with that - or a similar - scenario, and without doing anything too drastic, I managed to make the computer - or Cinnamon at least? - lock-up. I had to launch another tty and use it to reboot.

**Steps to reproduce**

I haven't managed to reproduce the crash, but the 'double editing' is easily reproducible and, I submit, should be prevented - partly because it may help forestall a crash.

**Comment by RealMtwebster** [comment]
Yes this is an issue for me as well, I will make sure to fix this soon
