### ISSUE TITLE
cinnamon-settings - Add column for currently assigned keyboard shortcuts

### ISSUE THREAD

**Issue by jcalbert** [linuxmint/cinnamon#6735]
```
 * Cinnamon version : 3.4.4
 * Distribution - Mint 18.2
 * 64 bit
 ```

**Issue**

I found customizing  keyboard shortcuts difficult.  In the Shortcuts tab of Keyboard settings, one has a single-column area (Tree View?) listing 'Keyboard shortcuts', and a second single-column area with a list of assigned 'Keyboard bindings'.  The latter is only revealed after selecting and item from the former.

![screenshot from 2017-07-27 12-32-40](https://user-images.githubusercontent.com/4261275/28682505-37a99ee0-72cb-11e7-8f10-089fca3ba9ad.png)

I think it would be better if there were a table-like layout, like this one from a video game:
![eljrgzw](https://user-images.githubusercontent.com/4261275/28682096-b39761ec-72c9-11e7-982f-d07a30118727.jpg)

I see two advantages:
1)  It would make it easier to avoid collisions (currently, one must guess-and-check).
2)  In many cases, I only know the shortcut by its binding.  For example, I know what "Alt+Tab" does, but I had to learn that the proper name is "Cycle through open windows" in order to re-assign that behavior.

**Comment by bk3468** [comment]
I agree.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
