### ISSUE TITLE
Cinnamon freezes occasionally when phone plugged in to USB

### ISSUE THREAD

**Issue by ropeladder** [linuxmint/cinnamon#6737]
```
 * Cinnamon version: 3.44
 * Distribution: Mint 18.2
 * Intel 2nd Gen Core Integrated Graphics
 * 64 bit
 ```

**Issue**
Cinnamon freezes occasionally when my phone (4th gen Moto G4) is plugged in via USB. I'm able to move the mouse and things keep running (music keeps playing, etc...) but it's like someone took a screenshot of the screen and I'm unable to click on anything or use the keyboard. (the only way the display changes at all is when I switch back and forth between the TTY and the GUI, redshift doesn't turn on immediately so the image changes color after a second after switching back to the GUI.

I'm unable to restart cinnamon using ALT-F2 + r.

So I've been restarting Cinnamon using the TTY, which is annoying because it closes all my windows. But the last time it happened I tried unplugging the phone and everything went back to normal. Hopefully that will work next time it happens.

**Steps to reproduce**
Plug in phone. (it has happened both when the phone is on 'charge only' and normal file browsing mode)
Wait. (I haven't noticed any particular behavior that prompts the freeze. Sometimes it's when I'm not even touching anything.)

Unplugging phone appears to restore things to normal.

**Expected behaviour**
Being able to click on things.

**Other information**

**Comment by icarter09** [comment]
@ropeladder are you still experiencing this issue?

**Comment by Vahan86** [comment]
@icarter09, can we close the issue?
