### ISSUE TITLE
Impossible to make any changes in menu

### ISSUE THREAD

**Issue by Dimasuch** [linuxmint/cinnamon#6738]
```
Mint 18.2 
Cinnamon 3.4.4 
64-bit
 
 ```
In a right mouse option on Menu - Configure - Open the menu editor.  Impossible to mark or unmark Item. Also it can be add your own item (launch app from custom places). After filled Launcher Properties menu appear "Cannot create the launcher at this location.  Add to the desktop instead?" 
I checked with mark/unmark "Launch in Terminal" result the same.
As well possible create custom menu item, but it can be delete. "Restore System Configuration" works properly.

**Comment by icarter09** [comment]
Mint 18.2
Cinnamon 3.4.6
64-bit

Not able to duplicate the problem of marking/unmarking an item. That appears to work correctly.

I am having problems after creating either a "New Item" or "New Menu", the option menu shows it has been created, but either is not appearing in the actually Mint Menu.
