### ISSUE TITLE
Why MDM (or other) store my user password to environment variable ?

### ISSUE THREAD

**Issue by lbngoc** [linuxmint/Cinnamon#6745]
```
 * Cinnamon version (cinnamon --version) 3.2.7
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)  Mint 18.1
 * 64 bit 
 * kernel 4.4.0-66-generic
 ```

**Issue**
After computer start and logged in, my current password was stored as plain text (!!!) to environment variable ($LANG & $MDM_LANG)

**Steps to reproduce**
- Start computer
- Login to current user

**Expected behaviour**
- $LANG and $MDM_LANG is same with `/etc/default/locale`
- The system SHOULD NOT store password as plain text in any case.

**Other information**
- When on MDM login screen, if I select language and login, $LANG and $MDM_LANG is set same with my selection. But it is only affect with this session.

**Comment by leigh123linux** [comment]
Wrong place for issue

https://github.com/linuxmint/mdm
