### ISSUE TITLE
Failure of mouse inversion (left to right) after upgrade to Cinnamon 3.4.4

### ISSUE THREAD

**Issue by Nokia808** [linuxmint/Cinnamon#6746]
```
 * Cinnamon version (3.4.4)
 * Distribution - (Fedora 26 X64 bit)
 * Graphics hardware *and* driver used (Intel Corporation HD Graphics 5500)
 * 64 bit
 ```

**Issue**
I'm left-handed user & already activated left handed user mouse support on Fedora 24. It was very O.K & effecting both mouse & touchpad (double touch & single touch).

After upgrade, left hand user mouse support NOT EFFECTIVE AT ALL NEITHER ON MOUSE NOR ON TOUCHPAD !!!!

Now mouse clicks are of right handed user & double touch of touch pad work as right click while single touch of touch pad works as left click (please not that both double touch & three touch are disabled by default from mouse setting). This position never altered by activating or deactivating of left mouse setting !!!

**Other information**
This happen only after upgrade from Fedora 24 to Fedora 26 (this mean only happen when upgrade to Cinnamon 3.4.4. Issue was not existing before upgrading to Cinnamon version 3.4.4. Mouse inversion option was very O.K on Fedora 24). 

Is it bug related to Cinnamon or to Fedora ??

**Comment by leigh123linux** [comment]
I'm unable to reproduce the issue on all current fedora releases including F28.

**Comment by Nokia808** [comment]
Hi.

Dear, did you examine issue using Fedora on Lenovo ThinkPad e550 ? I'm sure you did not. You examine issue using Fedora on other laptop ....

This bug it is hardware specific. I'm not engineer to know what is the problem exactly, but I have to inform you the following:

1) I have 3 personal laptop & additional laptop of my wife (totally 4). I examine Fedora on all these 4 laptop & it was ONLY existing on my Lenovo ThinkPad !!

2) this problem was 1st noticed by me on XFCE DE. I was liking to use XFCE Fedora not Cinnamon version. But due to 2 causes I switched to Cinnamon: 1st my CapsLock & NumLock have no LED & no indicator for them available on XFCE, 2nd cause is Left to Right switch of mouse not working on my Lenovo although it WORKING O.K ON OTHER LAPTOPS like my Hp laptop !!!! There are other bugs on XFCE that not existing on Cinnamon like entering password for wifi connection it will  be incorrect whatever I enter them correctly: I have to copy/past password from office doc. to wifi password field ... This only on XFCE on my Lenovo BUT NOT ON OTHER LAPTOP !!!!

So, it is hardware specific !! I'm already opened a bug on Redhat bug:
https://bugzilla.redhat.com/show_bug.cgi?id=1476586

Please read it carefully. Unfortunately, there is only one user suffer from it BUT ON GNOME DE not on Cinnamon so remain unconfirmed. However, as long as there is similar bug on GNOME, so at least you can trust me that I'm not layer .......

Best.

**Comment by leigh123linux** [comment]
If it is hardware specific I doubt the issue is within the cinnamon stack, it more likely to be

1. kernel driver
2. libinput / xorg-x11-drv-libinput

I might get the chance to test on a yoga 5xx when I see my friend in the next month.

**Comment by Nokia808** [comment]
Hi. Please re-open this bug. It is related to Cinnamon DE not to libinput. libinput working correctly. Please see final result of the following bug at Redhat bug tracker system:

https://bugzilla.redhat.com/show_bug.cgi?id=1476586

**Comment by leigh123linux** [comment]
No, you will need to file it here

https://github.com/linuxmint/cinnamon-settings-daemon/issues

and you will have to do a much better description as you never mentioned trackpoint once!!!!

**Comment by Nokia808** [comment]
I opened new bug:
https://github.com/linuxmint/cinnamon-settings-daemon/issues/197
