### ISSUE TITLE
Keyboard layout icon shows in tray only when its settings is open and layout order has been just changed

### ISSUE THREAD

**Issue by hanovruslan** [linuxmint/cinnamon#6748]
```
 * Cinnamon version 3.4.4
 * Ubuntu 16.04.2 LTS
 * VGA compatible controller Sky Lake Integrated Graphics i915
 * 64 bit
 ```

**Issue**

Keyboard layout icon shows in tray only when its settings is open and layout order has been just changed

**Steps to reproduce**
1. add keyboard-layout applet (it will not shows up but panel will blink )
1. click to menu
1. type `keyboard`
1. choose `keyboard layout`
1. open `Layouts` tab
1. add a layout if there is only one in the system
1. change order via click on `+` or `-` in the bottom of layouts lists area

for now you can see keyboard-layout applet
but almost any action in the desktop - run app, open new tab in some app window or something else makes applet disappear from tray

Also switch keyboard layout hotkey is not working while applet is missing in the tray

**Expected behaviour**

Shows all the time if added to panel

**Comment by NikoKrause** [comment]
The keyboard applet only shows up, if you have two or more languages in your keyboard layout.

**Comment by icarter09** [comment]
If @NikoKrause is correct, then it sounds like this is not an issue. Is that correct? If so, then should more be done to alert the user that two or more languages need to present for the keyboard layout to appear?

**Comment by hanovruslan** [comment]
Sorry, i really forget about that issue. Have reinstalled applets and this particular bug disappeared. But as you can see in description the problem took place for more then one language in the system - applet shows up but then somehow removes from panel

**Comment by collinss** [comment]
I cant reproduce this. Adding a second layout causes the applet to always show no matter what I do (it shows the flag, not the keyboard icon). Pressing the up and down arrows in settings doesn't make it disappear either. The only way I could get it to hide is by removing the second layout (by pressing the - button in the settings).

**Comment by dengiz** [comment]
I have two keyboard layouts and experience the same issue, and need to navigate to keyboard settings to make tray icon visible. How do you reinstall the default applets? Uninstall option is grayed out for keyboard applet.

**Comment by collinss** [comment]
@dengiz the default applets are all installed with Cinnamon itself. They are considered part of Cinnamon and shouldn't be removed separately, hence why that button is greyed out. If you removed the applet from the panel, you can get it back by simply re-adding it to the panel again.

**Comment by dengiz** [comment]
Sorry, my statement was not clear enough. I was trying to understand how @hanovruslan got rid of this problem. I tried removing the keyboard applet, restarting and adding keyboard applet back again but it had no effect. I also could not find a specific package that corresponds to default Cinnamon applets and I understand that there isn't any according to your explanation.

**Comment by icarter09** [comment]
@deniz-unal are you still experiencing this issue?

**Comment by Vahan86** [comment]
@icarter09, can we close the issue?
