### ISSUE TITLE
Feature Request: Screensaver message not limited to 50 characters

### ISSUE THREAD

**Issue by HoracioDos** [linuxmint/Cinnamon#6749]
Screensaver message is limited to 50 characters. It would be better at least 140 chars.

System:    Host: U47VC Kernel: 4.4.0-83-generic x86_64 (64 bit gcc: 5.4.0)
Desktop: Cinnamon 3.4.4 (Gtk 3.18.9) dm: lightdm Distro: Linux Mint 18.2 Sonya

**Comment by NikoKrause** [comment]
I would report it here https://github.com/linuxmint/cinnamon-screensaver/issues

**Comment by HoracioDos** [comment]
Can we delete this thread and report it where you had propused?

**Comment by NikoKrause** [comment]
It's not possible to delete an issue in GitHub. Closing here and open in the other repo should be enough.
