### ISSUE TITLE
Support for tiled monitors

### ISSUE THREAD

**Issue by infnty** [linuxmint/Cinnamon#6754]
Gnome currently has good out of box support for tiled (MST) monitors - like older 4K monitors and current generation of 5K monitors which run over two displayport cables. 

This feature is lacking in cinnamon - tiled monitors appear as two logical desktops spanning half the screen each with disadvantages like: panels span only half screen, windows maximize only on half screen, full screen browser windows don't work

From a quick search, on gnome side the work seems to have been done mostly on https://bugzilla.gnome.org/show_bug.cgi?id=750311 -  could this get backported to cinnamon code base?

**Comment by Linuxuser1986** [comment]
@mtwebster why did you delete my last concern?

**Comment by Linuxuser1986** [comment]
please @mtwebster

**Comment by leigh123linux** [comment]
File your request against cinnamon-desktop.

**Comment by infnty** [comment]
I don't really have time and no interest in this issue any more. If you
care about product quality please do so yourself instead of just closing
the bug!
