### ISSUE TITLE
Featuerrequest: Next background on desktop contextmenu

### ISSUE THREAD

**Issue by MegaV0lt** [linuxmint/Cinnamon#6756]
```
 * Cinnamon 3.4.4 (Gtk 3.18.9-1ubuntu3.3)
 * Distro: Linux Mint 18.2 Sonya
 * Graphics:  Card: Intel Atom Processor Z36xxx/Z37xxx Series Graphics & Display
           bus-ID: 00:02.0
           Display Server: X.Org 1.18.4 drivers: intel (unloaded: fbdev,vesa)
           Resolution: 1366x768@60.00hz
           GLX Renderer: Mesa DRI Intel Bay Trail
           GLX Version: 3.0 Mesa 17.0.7 Direct Rendering: Yes
 * 64 bit
 ```

**Featurerequest: "Next Background**

**Steps to reproduce**
If multi backgrounds are configured (slideshow) there is no easy possibility to just get the next (random) background via the contextmenu (Right click at desktop)

**Expected behavior**
Right click the desktop and select "Next background" from the menu. Desktop then has the new background

**Other information**
Have used that mechanism with wind0ws...

**Comment by leigh123linux** [comment]
Who gives a damn about some Windoze feature?, Why pollute Linux with this?

> Other information
Have used that mechanism with wind0ws...



-1 for this request

**Comment by itzexor** [comment]
This doesn't exist in nemo desktop, but there is an applet to do this for the panel called "Slideshow Controls" included with cinnamon.

**Comment by mtwebster** [comment]
There's already a feature request for this I believe (though for the life of me I can't find it now) - there are plans to make the slideshow easier to control, particularly from the command line or via dbus.

For now, create and edit the file: `~/.local/share/nemo/actions/next-background.nemo_action` and paste this into it:

```
[Nemo Action]
Name=Next wallpaper
Comment=If the desktop background slideshow is active, display the next image
Exec=dbus-send --print-reply --dest=org.Cinnamon.Slideshow /org/Cinnamon/Slideshow org.Cinnamon.Slideshow.getNextImage
Icon-Name=wallpaper
Selection=none
Extensions=any;
Conditions=gsettings org.cinnamon.desktop.background.slideshow slideshow-enabled;desktop;
```

It should show up in the desktop context menu.

**Comment by Linuxuser1986** [comment]
@mtwebster why did you delete my last concern?

**Comment by NikoKrause** [comment]
You can use the slideshow applet, which is already included in Cinnamon.
It you can use this 3rd party applet: https://cinnamon-spices.linuxmint.com/applets/view/291

**Comment by Linuxuser1986** [comment]
please @mtwebster

**Comment by JosephMcc** [comment]
Here is the related feature request https://github.com/linuxmint/nemo/issues/1258
