### ISSUE TITLE
Holographic effects

### ISSUE THREAD

**Issue by swedenfortrumpcom** [linuxmint/Cinnamon#6758]
```
 * Cinnamon version (5.0)
 * Distribution - (Linux)
 * Graphics hardware nvidio
 * 64 bit
 ```

**Issue**

make the system look cool and holographics, this should happen so that linux is popular and passes macos and windows in performance and sexy looks

**Expected behaviour**
look cool and holographic

**Other information**
how it needs to look

![image](https://user-images.githubusercontent.com/30671943/28896972-f226417c-779b-11e7-83c6-432398c7cdfa.png)

**Comment by leigh123linux** [comment]
Hell will freeze over first!

**Comment by swedenfortrumpcom** [comment]
@leigh123linux that wasnt conscrutive to to say "yuk" and close this, please reopen and haev conversatioon
