### ISSUE TITLE
quick access to favorites

### ISSUE THREAD

**Issue by neugear** [linuxmint/Cinnamon#676]
If the Windows key is held for 2 seconds, the menu will open with numbers on each favorite entry. If the number is pressed on the keyboard the appropriate program should start.

**Comment by dralley** [comment]
@JosephMcc This can probably be closed since the referencing PR claims it's already implemented

**Comment by JosephMcc** [comment]
You can navigate them with the keyboard but the original request is for showing numbers to launch each particular one. That isn't implemented.

**Comment by JosephMcc** [comment]
Thank you for your suggestion. See https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html for information on how we handle feature requests.
