### ISSUE TITLE
Please stop locking posts

### ISSUE THREAD

**Issue by swedenfortrumpcom** [linuxmint/Cinnamon#6761]
I wil make construcitve comments forom now on, please stop this dictatorship and molesting yuor power as admins :(

**Comment by swedenfortrumpcom** [comment]
also is there a plaece to talk to the leader of coding so I can personelay recmoned him to do things and talk about my posisition?

**Comment by swedenfortrumpcom** [comment]
pleese i have very good Iq it was rated at 189 and I have many good ideeas to share, if only you will listen and heed my commands we would get along, this is very important to me.

**Comment by leigh123linux** [comment]
Your ideas are too extreme for us.
You shouldn't have any difficulty forking and adapting cinnamon to your needs with your 189 IQ.

**Comment by swedenfortrumpcom** [comment]
@leigh123linux but my idaeas are so masterful that thay would efect every boy and girl and man and woman and other in a positive way to make them all use linux and once and for all kill the windflows where is stands!

**Comment by leigh123linux** [comment]
Linux will never be mainstream till manufacturers stop supplying PC's with default pre-installed Windows O/S.
It would be great to be offered a choice even if it was Windows or no O/S.



So you want to inflict linux on everyone?, your starting to sound like a dictator.
 
> that thay would efect every boy and girl and man and woman and other in **a positive way to make them all use linux and once and for all** kill the windflows where is stands!

Ever considered if Linux displaced windows all the malware and viruses would be re-targeted?

**Comment by swedenfortrumpcom** [comment]
i will politly tell you your argument is invalid with 1. Trump will purge windkloes from the world because its made by nsa muslims and linux is freedom like USA! and 2. linux cant get viruses only winhoes
