### ISSUE TITLE
Cinnamon freeze

### ISSUE THREAD

**Issue by swedenfortrumpcom** [linuxmint/Cinnamon#6762]
```
 * Cinnamon version I don't know
 * Distribution - mint 17.1
 * Graphics hardware nvidia
 * 64 bit
 ```

**Issue**
When I run some video gaems like steam the cinnamon will freeze

**Steps to reproduce**
Open geame like civilzatoin 4 anf plaey til crash

**Expected behaviour**

Don't crash

**Other information**
Fans get loud

Please don't lock this posts

**Comment by mtwebster** [comment]
You had your final chance in your last thread.  That sort of hateful language is unwelcome here, no matter how ineptly displayed.  You have also been reported for that post.  Please go away.
