### ISSUE TITLE
SysTray not working correctly, icons don't show.

### ISSUE THREAD

**Issue by androos** [linuxmint/Cinnamon#6764]
* Cinnamon version (3.2.0)
 * Distribution - (Sabayon)
 * 4.11.0-sabayon #1 SMP Wed Jul 26 12:57:06 UTC 2017 x86_64 AMD A8-3500M APU with Radeon(tm) HD Graphics AuthenticAMD GNU/Linux

**Issue**
1. Icons not show up at all – example Clementine tray symbol never shows.
2. Symbols not there when the app has started earlier than systray. 

**Steps to reproduce**
Start Clementine with systray icon enabled. See nothing in systray.
put some apps with systray icon in auto start, everytime they start earlier than systray it'snot there. 

**Expected behaviour**
To have an icon every single app that has an systray icon at any given time.

**Other information**
Cinnamon is a good idea, but it

**Comment by Linuxuser1986** [comment]
please @mtwebster

**Comment by androos** [comment]
Okay okay, the Clementine issue is solved. The Sound applet has an option to hide supported apps, that's defaults to on. So it was just hidden by default. But owncloud client doesn't show up on start up.

**Comment by leigh123linux** [comment]
owncloud/nextcloud is a known issue

https://github.com/linuxmint/Cinnamon/issues/6143
