### ISSUE TITLE
Xface auto-Login failed

### ISSUE THREAD

**Issue by irwinx** [linuxmint/Cinnamon#6770]
```
Xface
MINT 18.02
VMware on Windows10 host
64bit
 ```
**Issue:**
In the MINT Xface 18.02 setup options I chose "automatic login", but when the system is installed I was still asked to put in my user name and pw. To be more confusing the password didn't work,("invalid password").Then I switched to the text console to login but still can not login. But after I reboot it,it directly entered the desktop.

What happened?

**More info**
host info : windows 10 pro

**Comment by leigh123linux** [comment]
XFCE isn't part of cinnamon

**Comment by irwinx** [comment]
Sorry. I know that. But I really can't find  the xface page. Could you offer me a help hand?

**Comment by irwinx** [comment]
I am sorry for that. But I can not find a xface page. Could you please offer me a help hand?
发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: leigh123linux<mailto:notifications@github.com>
发送时间: 2017年8月4日 23:51
收件人: linuxmint/Cinnamon<mailto:Cinnamon@noreply.github.com>
抄送: irwinx<mailto:qwetakachihoxhic@outlook.com>; Author<mailto:author@noreply.github.com>
主题: Re: [linuxmint/Cinnamon] Xface auto-Login failed (#6770)


XFCE isn't part of cinnamon

―

**Comment by leigh123linux** [comment]
Try setting again using 'login window' tool from the apps menu, if it fails to set it refile the issue (see link).

https://github.com/linuxmint/lightdm-settings/issues
