### ISSUE TITLE
Wasted space in Nemo sidebar

### ISSUE THREAD

**Issue by trinistr** [linuxmint/Cinnamon#6775]
```
 * Cinnamon 3.4.4
 * Distribution - Mint 18.2
 * 64 bit
 ```

**Issue**

In default mode (I think it is called "Places" in English) Nemo sidebar has empty space on the right side, shortening the text. This space has constant width, making smaller sidebar look ugly.
![image](https://user-images.githubusercontent.com/6594487/28997716-c4ea9692-7a23-11e7-948a-2d90b23ca6ca.png)

**Expected behaviour**

Names of places would take up all available width and not get awkwardly cut.

**Comment by leigh123linux** [comment]
You are aware you can resize it?
As for the wasted space, this is reserved/used for the overlay scrollbar.

![screenshot from 2017-08-05 20-26-22](https://user-images.githubusercontent.com/1299302/28998159-67f80782-7a1c-11e7-946a-99d4f3df2fde.png)

**Comment by gabrielfern** [comment]
But the scrollbar dont need so much width

**Comment by leigh123linux** [comment]
The theme controls the width.
