### ISSUE TITLE
Clicked "Menu" prevents screen lock

### ISSUE THREAD

**Issue by titbang** [linuxmint/Cinnamon#6777]
```
 * Cinnamon version (cinnamon --version)
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
 * Graphics hardware *and* driver used
 * 32 or 64 bit
 ```
Fedora 26
Cinnamon 3.4.4

**Issue**

Clicked "Menu" prevents screen lock

**Steps to reproduce**

Enable Screen Locker from Screensaver settings, click Menu, then let idle.

**Expected behaviour**

Cinnamon should lock but it does not.

**Other information**

If the desktop is selected it seems to lock without issue.

**Comment by JosephMcc** [comment]
https://github.com/linuxmint/cinnamon-screensaver/issues/93
https://github.com/linuxmint/Cinnamon/issues/1430
