### ISSUE TITLE
Laptop USB mouse movement strange behaviour (stops)

### ISSUE THREAD

**Issue by weiju** [linuxmint/Cinnamon#6779]
```
 * Cinnamon version 3.4.4
 * Distribution - Mint 18.2
 * Graphics hardware *and* driver used nVidia Geforce GTX 1070 (mobile)
 * 64 bit
 * Asus ROG GL502VS-DS71
 ```
**Issue**

Mouse cursor occasionally stops moving, can be forced to move again by clicking right mouse button

**Steps to reproduce**

Boot laptop with USB devices plugged in (powered USB hub). Mouse does not move, keyboard works. After right-click mouse moves again. Use the keyboard, mouse stops again until right mouse
button is clicked.
Can be permanently fixed by unplugging USB and plugging it in again.

**Expected behaviour**

Mouse cursor should always move according to mouse movements

**Other information**

I did not previously see this behavior on the Cinnamon that was distributed with Mint 18.1.

**Comment by leigh123linux** [comment]
This is more likely a kernel issue or some other non-cinnamon component.
