### ISSUE TITLE
The calendar applet don't update seconds properly

### ISSUE THREAD

**Issue by seigneurfuo** [linuxmint/Cinnamon#6780]
```
 * Cinnamon version 3.4.3
 * Distribution - Manjaro Linux x64 bits
 * Intel 4th Gen Core Processor Integrated Graphics Controlle with Intel Nouveau Driver
 ```

**Issue**
The calendar applet don't update seconds properly.

![peek 07-08-2017 23-55](https://user-images.githubusercontent.com/20669563/29047447-ffb92f78-7bcb-11e7-85f2-c26d3243d1b1.gif) 
(Visual glitches due to of an incorrect screen capture settings)

**Steps to reproduce**
Just configure the calendar applet to display seconds.

**Comment by JosephMcc** [comment]
Seems to work fine here. Did you do the configuration in the Calendar applet settings?

**Comment by seigneurfuo** [comment]
After rebooting my compter it works fine. I dont know why.

**Comment by icarter09** [comment]
I'm not seeing any issue either. Should someone close out this issue?

**Comment by mtwebster** [comment]
This issue should have been fixed by these commits, anyhow:

https://github.com/linuxmint/cinnamon-desktop/commit/197f4ab88eed5a60ea10b5e89f64808dcf563e60
https://github.com/linuxmint/Cinnamon/commit/e1170004b71789be21b7851aed8933779b067018

I'm not certain about #6473, however.
