### ISSUE TITLE
Add CSS selector to panel if monitor has maximized window

### ISSUE THREAD

**Issue by theChrisliebaer** [linuxmint/cinnamon#6781]
**Feature Request (visuals only)**
Would it be possible to add a CSS selector to the panel if there is a maximized window on the same monitor? Having a theme with a transparent panel can look realy cool but if there is a maximized window it looks wierd if the wallpaper is shining through. The distinction should be made seperately for each monitor and only effect the panels on the same monitor.

The same behavior can be seen on Windows 7 if Aero is enabled. Maximizing a window on the same monitor the Windows Taskbar is on will remove all transparency.

**Expected behaviour**
If implemented correctly it would be possible to change the appearance of the panel if there is a maximzed window on the same screen.

````
#panelLeft.maximized {
/* less or even no transparency */
}

#panelLeft:not(.maximized) {
/* lot of transparency */
}

````

I'm not an expert with CSS so I don't know what the best way would be to provide this information inside the stylesheet, maybe a second pseudo class besides "dnd".

I quickly checked over the source code and it seems the correct place to implement this feature would be in the panel.js file. I'm not familiar with the code base, right now it doesn't seem like there are any callbacks that could be used to make the panel code itself perform this check. There is also a ``setPanelsOpacity`` method that could be used to get at least dynamic transparency but I'm not sure what this method is used for right now and it is also setting the opacity for all panels at the same time.

**Edit:** After checking the source code more deeply I think I could easily implement this myself. Please tell me if you consider this feature worth to be implemented within Cinnamon and I will have a look at it myself.

**Comment by germanfr** [comment]
Hey @Lupinus, check this out: [cinnamon-transparent-panels](https://github.com/germanfr/cinnamon-transparent-panels).
It's an extension that already implements that. It's probably not the most correct implementation, but it works.

**Comment by Lupinus** [comment]
@germanfr Yeah I actually found your extension while looking for example code. I mean it's pretty close but it doesn't differentiate between multiple screens and it is a bit different since it changes the panel by itself. I'd rather have Cinnamon expose this information to themes since the theme autor might actually be in a better position to adjust the style of the panel.

**Comment by germanfr** [comment]
@Lunipus yeah, multi screen support needs to be added. But it doesn't modify the panel in any way. It does just what you said, it adds a class so that themes can use it.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
