### ISSUE TITLE
Cinnamon (Mint 18.2) behaves weirdly after waking up from suspension

### ISSUE THREAD

**Issue by vamsibokam** [linuxmint/cinnamon#6796]
```
 * Cinnamon 3.4.6 
 * Distribution - (Mint 18.2)
 * Kernel: 4.4.0-91-generic x86_64 (64 bit gcc: 5.4.0)
* Graphics:  
           Card-1: Intel 3rd Gen Core processor Graphics Controller bus-ID: 00:02.0 chip-ID: 8086:0166
           Card-2: Advanced Micro Devices [AMD/ATI] Thames [Radeon HD 7550M/7570M/7650M]
   
 * 64 bit
 ```

**Issue**
After waking up from suspend mode, cinnamon does not work. I have attached few screenshots on how my desktop looks. Please refer to the screenshots attached below. Only restarting cinnamon brings it back to normal state.
Also normal system restart takes long time (It gets stuck at boot animation forever). I have to force shutdown and then reboot. 
**Note:** My libfreetype6:amd64 package is hold from upgrading. I use a previous version which is installed from my previous Mint 17.3 distribution. Its version is 2.5.2-1ubuntu2.8

**Steps to reproduce**
Just wake up from suspend mode.

**Expected behaviour**
None of the inputs like keyboard and mouse will be responded properly.

**Other information**
Screenshots of my desktop(Few names of windows are blurred):
![image](https://user-images.githubusercontent.com/5682349/29243398-c24dcd8a-7fbb-11e7-9bb2-88df731775aa.png)

![image](https://user-images.githubusercontent.com/5682349/29243402-d2fed336-7fbb-11e7-8544-31e8e51ed79c.png)

![screenshot from 2017-08-12 23-31-08](https://user-images.githubusercontent.com/5682349/29243419-127304c4-7fbc-11e7-861b-5a47a8c051c6.png)

**Comment by two-dogs** [comment]
@vamsibokam would you provide the output of 'inxi -Fxxr' please

**Comment by vamsibokam** [comment]
Output of inxi -Fxxr:

System:    Host: vamsi-Inspiron-5423 Kernel: 4.4.0-91-generic x86_64 (64 bit gcc: 5.4.0)
           Desktop: Cinnamon 3.4.6 (Gtk 3.18.9-1ubuntu3.3) dm: mdm
           Distro: Linux Mint 18.2 Sonya
Machine:   System: Dell (portable) product: Inspiron 5423 Chassis: type: 8
           Mobo: Dell model: 067CG0 v: A13 Bios: Dell v: A13 date: 05/18/2013
CPU:       Dual core Intel Core i5-3317U (-HT-MCP-) cache: 3072 KB
           flags: (lm nx sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx) bmips: 6784
           clock speeds: min/max: 800/2600 MHz 1: 1363 MHz 2: 799 MHz
           3: 923 MHz 4: 863 MHz
Graphics:  Card-1: Intel 3rd Gen Core processor Graphics Controller
           bus-ID: 00:02.0 chip-ID: 8086:0166
           Card-2: Advanced Micro Devices [AMD/ATI] Thames [Radeon HD 7550M/7570M/7650M]
           bus-ID: 02:00.0 chip-ID: 1002:6841
           Display Server: X.Org 1.18.4 drivers: ati,radeon,intel (unloaded: fbdev,vesa)
           Resolution: 1366x768@60.01hz
           GLX Renderer: Mesa DRI Intel Ivybridge Mobile
           GLX Version: 3.0 Mesa 17.0.7 Direct Rendering: Yes
Audio:     Card Intel 7 Series/C210 Series Family High Definition Audio Controller
           driver: snd_hda_intel bus-ID: 00:1b.0 chip-ID: 8086:1e20
           Sound: Advanced Linux Sound Architecture v: k4.4.0-91-generic
Network:   Card-1: Qualcomm Atheros AR9485 Wireless Network Adapter
           driver: ath9k bus-ID: 07:00.0 chip-ID: 168c:0032
           IF: wlan0 state: up mac: 84:4b:f5:0b:af:e1
           Card-2: Qualcomm Atheros AR8162 Fast Ethernet
           driver: alx port: d000 bus-ID: 09:00.0 chip-ID: 1969:1090
           IF: eth0 state: down mac: 78:45:c4:a2:6f:fc
           Card-3: Atheros usb-ID: 001-034 chip-ID: 0cf3:e004
           IF: null-if-id state: N/A speed: N/A duplex: N/A mac: N/A
Drives:    HDD Total Size: 532.1GB (61.8% used)
           ID-1: /dev/sda model: ST500LT012 size: 500.1GB serial: W3P94ZDF
           ID-2: /dev/sdb model: LITEONIT_LMT size: 32.0GB serial: TW04NG44550852BM0649
Partition: ID-1: / size: 179G used: 123G (73%) fs: ext4 dev: /dev/sda1
           ID-2: swap-1 size: 4.16GB used: 2.37GB (57%) fs: swap dev: /dev/sda5
RAID:      System: supported: N/A
           No RAID devices: /proc/mdstat, md_mod kernel module present
           Unused Devices: none
Sensors:   System Temperatures: cpu: 61.0C mobo: N/A gpu: N/A
           Fan Speeds (in rpm): cpu: N/A
Repos:     Active apt sources in file: /etc/apt/sources.list.d/nathan-renniewaldock-flux-xenial.list
           deb http://ppa.launchpad.net/nathan-renniewaldock/flux/ubuntu xenial main
           deb-src http://ppa.launchpad.net/nathan-renniewaldock/flux/ubuntu xenial main
           Active apt sources in file: /etc/apt/sources.list.d/official-package-repositories.list
           deb http://mirrors.ustc.edu.cn/linuxmint sonya main upstream import backport
           deb http://ftp.iitm.ac.in/ubuntu xenial main restricted universe multiverse
           deb http://ftp.iitm.ac.in/ubuntu xenial-updates main restricted universe multiverse
           deb http://ftp.iitm.ac.in/ubuntu xenial-backports main restricted universe multiverse
           deb http://security.ubuntu.com/ubuntu/ xenial-security main restricted universe multiverse
           deb http://archive.canonical.com/ubuntu/ xenial partner
Info:      Processes: 364 Uptime: 2 days Memory: 2594.7/3827.2MB
           Init: systemd v: 229 runlevel: 5 default: 2 Gcc sys: 5.4.0 alt: 4.8
           Client: Shell (bash 4.3.481 running in gnome-terminal-) inxi: 2.2.35

**Comment by mIwebster** [comment]
On behalf of linux mint I am so sorry you are having these issues, I will fix this as soon as possible

**Comment by icarter09** [comment]
@vamsibokam are you still experiencing this issue?

**Comment by Vahan86** [comment]
@icarter09, can we close the issue?

**Comment by vamsibokam** [comment]
Sure.
