### ISSUE TITLE
cinnamon-settings-daemon not running on startup

### ISSUE THREAD

**Issue by raphael141714** [linuxmint/Cinnamon#6799]
I'm running Cinnamon 3.2.7 on debian sid with linux 4.11.0-2-rt-amd64 on a GeForce GT 320M (nVidia legacy 340.102-2 drivers).

**Issue**
Strange problem of cinnamon-settings-daemon not launching on startup.
It stops the power management applet from running.
It stops the background to be changed to something else than the lightdm one.

**Steps to reproduce**
Simply restarting the entire system with something like "sudo shutdown now".
However, it doesn't occur 100% of the time:
I would say that 90% of my restarts result in cinnamon-settings-daemon not running.
I can relaunch the command `cinnamon-settings-daemon`, and then everything works fine.
I don't want to do a cron tab, as it seems quite dumb in this case.

**Expected behaviour**
Obviously, having cinnamon-settings-daemon running correctly.

**Other information**
None.

**Comment by leigh123linux** [comment]
c-s-d issue don't belong here, in fact why bug mint for a debian issue?

**Comment by leigh123linux** [comment]
You could have a broken symlink, without log output this is just a guess.

https://github.com/linuxmint/cinnamon-settings-daemon/issues/148

**Comment by raphael141714** [comment]
It's just a debian cinnamon bug
