### ISSUE TITLE
Moving windows in the window list is unreliable

### ISSUE THREAD

**Issue by leigh123linux** [linuxmint/Cinnamon#6807]
Bug forwarded from  https://bugzilla.redhat.com/show_bug.cgi?id=1481871

Description of problem:

I like to have windows listed in specific orders in the window list in the
Cinnamon dock.  Moving a window button in the window list is, at best,
unreliable, though it is possible with extreme patience.

Version-Release number of selected component (if applicable):

cinnamon-3.4.4-1.fc25.x86_64

How reproducible:

This is one of those frustrating things that works occasionally, but most of
the time does not.

Steps to Reproduce:
1. Start up multiple applications on one workspace
2. Attempt to move the button for one of those applications in the window list
   - Moving the button to the far left has proven particularly problematic, but
     even in between two other entries in the list is frustratingly difficult.

Actual results:

Window button will be moved to some random part of the list.  I've even seen a
move from index 1 (0-based) to index 5 when trying to move the window to index
0.

Expected results:

It should be possible to move a window button to any point in the window list
easily and clearly, without it jumping around randomly.

Additional info:

**Comment by MrElectroNick** [comment]
Can confirm that. Rarely use dnd in taskbar but in some cases it just doesn't work as expected. Not a big deal but annoying sometimes.
And it's not always reproducible on Cinnamon fresh start or after relogin.
I can only guess but might be related to memory use (maybe)
Most problematic is to put something on index [0] (as described above)

**Comment by itzexor** [comment]
I can't reproduce this, it seems to work fine on my end... Maybe it's theme related?

**Comment by RealMtwebster** [comment]
This is not an issue, delete this

**Comment by klmitch** [comment]
Why would you think this is not an issue?  It is certainly a difficulty for me.  More context:

On one workspace, I have 2 windows of different types (one gnome terminal, one firefox); moving them in the window list works fine.

In another workspace, I have 7 windows: 3 emacs, 2 gnome terminal, 2 git gui.  In that workspace, moving windows in the window list doesn't work.  I moved one emacs window to the end (extreme right) of the window list, and now cannot move it back; to get it where I want, I have to move all the other windows, one by one, to the end of the list.

Themes:

* Window borders: Anaconda
* Icons: gnome
* Controls: Adwaita
* Mouse Pointer: Adwaita
* Desktop: cinnamon

Cinnamon version: cinnamon-3.4.4-1.fc25.x86_64

And yes, I'm using the default window list, not a third-party version.

**Comment by itzexor** [comment]
Thanks for the details, using workspaces seems to be the key here. I don't normally use them, and it only breaks when you enable multiple.

**Comment by leigh123linux** [comment]
@klmitch Ignore the stray comment, I deleted his remark.

I've seen this happen locally without using workspaces.

**Comment by itzexor** [comment]
This could probably use a bit more refinement, but does anyone want to test this patch?

https://github.com/itzexor/Cinnamon/commit/c7120e737337b42a6ae6fafcd28ab2f72e294058

**Comment by itzexor** [comment]
That is most certainly less efficient than the original code, but I don't think I can skip hidden indices when using a while loop.

**Comment by klmitch** [comment]
FYI, I just updated to Fedora 26 with Cinnamon 3.6.0, and am still seeing the same behavior.
