### ISSUE TITLE
Make panel go above the Window

### ISSUE THREAD

**Issue by eudennis** [linuxmint/Cinnamon#6814]
I'm not sure if this is the best place for this, if not. Sorry. 

I was trying to make some modifications on the Cinnamon panel behavior, but I didn't figure out yet how to make it go above the Window like the XFCE panel does.

```
 * Cinnamon version (cinnamon --version)
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
 * Graphics hardware *and* driver used
 * 32 or 64 bit
 ```

**Issue**
Be able to place Window below the panel

**Steps to reproduce**
Create a panel and a windows ;)

**Expected behaviour**
When you use any window in fullscreen, the panel stay fixed. I want to get the panel on top of the window container.

**Other information**
Cinnamon 3.4.4
Gnome Ubuntu 17.04
64 bits

**Comment by leigh123linux** [comment]
Required info not provided!

**Comment by eudennis** [comment]
Actually this isn't an issue, that's why I didn't provided the required Info.

**Comment by NikoKrause** [comment]
I don't get it. Screenshot?

**Comment by eudennis** [comment]
![screenshot from 2017-08-22 16-45-26](https://user-images.githubusercontent.com/1117340/29584203-62de1d3c-8759-11e7-95d7-139858c3db87.png)

As you can see on the screenshot, the panel is above the window. But even on full screen, I cannot make the panel overlap the window.

**Comment by itzexor** [comment]
The panels should normally be hidden when in-fullscreen. Which application is the panel showing over when in fullscreen?

**Comment by eudennis** [comment]
I know that isn't the normal behavior, but I was looking for something like the "Don't reserve space on borders"

https://maketecheasier-2d0f.kxcdn.com/assets/uploads/2013/08/xfce-panel-preferences.png

**Comment by itzexor** [comment]
This is not supported, and would probably be pretty unusuable for most people if implemented without any other changes, but you can make it happen manually by entering a command like this into melange (super+L):

`Main.layoutManager._chrome.modifyActorParams(Main.panelManager.panels[1].actor, {affectsStruts: false})`

You'll have to change the `Main.panelManager.panels[1].actor` to the correct panel.

Doing this with a top panel will make the application titlebar inaccessible while maximized, and windows will go under the panel by default.

You are probably better off just using an autohiding panel if you want to make full use of the screen space, that automatically turns off struts.

**Comment by eudennis** [comment]
Wow! That's was exactly what I was looking for! Thanks

**Comment by eudennis** [comment]
In XFCE you can make the panel use just 20% of the screen width, or any value you want. But this is enough for me. Thanks :)

**Comment by eudennis** [comment]
What I should to to run this at boot?

**Comment by itzexor** [comment]
You can make a simple applet or extension to run that command

**Comment by itzexor** [comment]
There is a tutorial you can read by using the DevHelp application just look for "Cinnamon Tutorials". There is also a copy on the linuxmint developer website but it is currently out of date.

**Comment by JosephMcc** [comment]
We don't support partial width panels in Cinnamon and have no plans to as far as I know. In our configs the panel should always go below fullscreened windows.
