### ISSUE TITLE
Launcher item duplicates when options added

### ISSUE THREAD

**Issue by mxa** [linuxmint/cinnamon#6820]
```
 * Cinnamon 3.4.6
 * Mint 18.2
 * 64 bit
 ```

**Issue**
When adding options to the launcher like described in https://github.com/linuxmint/Cinnamon/issues/6365#issuecomment-287631274 the launcher duplicates. When deleting one of them, both are gone.

**Steps to reproduce**
Edit options for a launcher Icon

**Expected behaviour**
options are changed. That happens, but additionally there is a second one.

**Comment by RealMtwebster** [comment]
No it doesn't delete this

**Comment by mIwebster** [comment]
Great we will fix this as soon as possible

**Comment by icarter09** [comment]
@mxa are you still experiencing this issue?

**Comment by mxa** [comment]
Sorry, moved away from Cinnamon.

**Comment by icarter09** [comment]
@mxa no worries and thanks for the update.
