### ISSUE TITLE
Drag and Drop file from Nemo to desktop - Position adherence 

### ISSUE THREAD

**Issue by awunes** [linuxmint/Cinnamon#6826]
```
 * Cinnamon version (cinnamon --version): Cinnamon 3.2.7
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 18.1
 * Graphics hardware *and* driver used :
Graphics:  Card: NVIDIA G84 [GeForce 8600 GTS]
           Display Server: X.Org 1.18.4 drivers: nvidia (unloaded: fbdev,vesa,nouveau)
           Resolution: 1440x900@59.89hz, 1440x900@59.89hz
           GLX Renderer: GeForce 8600 GTS/PCIe/SSE2
           GLX Version: 3.3.0 NVIDIA 340.102
 * 64 bit
 ```

**Issue**

Icon position upon initial drop of file from Nemo to desktop. OR creating new folder/document.

When you first place an icon/file on the desktop it places it in the top left to bottom right column order according to first open space available instead of placing it where you either right clicked and selected "create new folder"/"create new document"  OR dropped the file from a file manager window such as nemo.

**Steps to reproduce**
Open nemo.
Click and drag a file from /home/[user] to desktop ***NOT /home/[user]/Desktop***
Upon release of left mouse button the icon/file will appear at the first open position of the aligned left columns.

**Expected behaviour**

Icon would be placed exactly where you let go. And not require a second click and drag/drop to correct position.

**Other information**
Mc from #linuxmint-dev on irc.spotchat.org suggested there is a option for "automatic placement" but that's in cinnamon 3.4 ... i'll have to upgrade and see if that helps.

**Comment by leigh123linux** [comment]
Issue moved to [linuxmint/nemo #1588](https://github.com/linuxmint/nemo/issues/1588) via [**ZenHub**](https://www.zenhub.com/)
