### ISSUE TITLE
Screen rotation does not rotate all input devices and needs custom settings

### ISSUE THREAD

**Issue by evilphish** [linuxmint/Cinnamon#6837]
* Cinnamon version (cinnamon --version)
3.4.6

 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
mint 18.2

 * Graphics hardware *and* driver used
intel HD620

 * 32 or 64 bit
64

**Issue**
Using cinnamon on a lenovo x1 yoga 2nd gen, while the automatic screen rotation with the help of iio-sensor-proxy works as expected, only the stylus gets rotated with the screen as well. Finger touch or any other pointing device still stays in normal orientation and is therefore unusable. The same happens if you do not use automatic rotation but rotate the display manually via the display settings or using xrandr from the command line.

In addition a "run on rotation" setting at least somewhere in dconf would be immensely helpful as it would allow toggling on or off the touchpad, launching other software, etc.

**Steps to reproduce**
Start cinnamon, rotate your display (either automatically or manually via display settings or xrandr). That's it.

**Expected behaviour**
All input pointing devices should rotate the same way as the display.

**Comment by leigh123linux** [comment]
Issue moved to [linuxmint/cinnamon-settings-daemon #188](https://github.com/linuxmint/cinnamon-settings-daemon/issues/188) via [**ZenHub**](https://www.zenhub.com/)
