### ISSUE TITLE
New smile feature

### ISSUE THREAD

**Issue by l405111** [linuxmint/Cinnamon#6838]
First of all, I'm sorry apologize for my English, I'm the Google Translate, I have been using Linux Mint for a few years, I want to see it become a swamp in the table, and when the smile, it would be a great thing, because the picture They are too often changed backroung. If you do that, it is very important as the last 
time a man sawsaw Linux Mint was version 3, too slow for yesterday and it was great :D :) 

Also this is from four? I did the Ubuntu and the red not being on the mouse point was very good.

Thanks and again sorry for apologize English

**Comment by JosephMcc** [comment]
I'm sorry but google translate made this something that doesn't actually make any sense. Because of that there isn't anything we can really do with it.
