### ISSUE TITLE
Enable moving mouse over entire edge of multiple monitors with different resolotions

### ISSUE THREAD

**Issue by TroyMass** [linuxmint/cinnamon#6839]
```
 * Cinnamon 3.4.6
 * Ubuntu 16.04.3 LTS
 * Intel integrated graphics i5-7300HQ
* Graphics driver /lib/modules/4.10.0-32-generic/kernel/drivers/gpu/drm/i915/i915.ko
 * 64 bit
 ```

**Issue**

When I have multiple monitors connected which have different resolutions, on the larger monitor, only part of the edge allows moving the mouse to the other monitor. This is probably related to the Display layout tool.

**Steps to reproduce**

1. connect 2 monitors
2. Use the "Display" configuration tool to arrange the monitors side-by-side
3. Set the resolution on one of the monitors to be taller than the other (ie. 2560x1440 on left, 1920x1080 on right)
4. Move the mouse to the top (and/or bottom) edge of the screen and move it back and forth between monitors.
5. You will find there are "walls" around part of the screen where the adjacent screen is not aligned preventing moving the mouse

**Expected behaviour**

Would like to have an option in the Display configuration tool to enable 100% of the edge to allow cursor movement across it. When the cursor moves between displays, its position should be computed using relative positioning instead of absolute positioning.

ie. if on the left screen the cursor was 936 pixels high on a 1440p tall screen, that is 936 / 1440 = 0.65. On the right screen that is 1080p tall it should end up at 0.65 * 1080 = 702 pixels from the bottom. 

The same rule should apply for vertically positioned screens.

**Comment by icarter09** [comment]
@TroyMass are you still experiencing this issue?
