### ISSUE TITLE
Applets Don't Allow Touch Screen Input

### ISSUE THREAD

**Issue by gbkelley** [linuxmint/Cinnamon#6842]
```
 * Cinnamon version 3.4.6
 * Distribution - Mint 18.2
 * Graphics hardware *and* driver used
 * 64 bit
 ```

**Issue**

Menu, Volume, Battery, Network Applets will not respond to touch screen input (taps or drag) if you launch by tapping. Menu launched by clicking with mouse or pressing menu button (Acer Switch Alpha 12 has this) then you can tap/drag in the menu area. Other applets no way to input unless you click on the icon in system tray first.

**Steps to reproduce**

Tap on Menu, Volume, Battery, Network Icon in System Tray/Panel then no tap input allowed in applet area. Click on icon first, tap then allowed

**Expected behaviour**

Touch Screen Taps work everywhere else, just not in these applets

**Other information**

Fresh install Acer Switch Alpha 12 (similar to Surface Pro)

**Comment by evilphish** [comment]
On a Lenovo X1 Yoga I can not reproduce this. Touch works everywhere. Same Cinnamon / Mint version. Can you get any output from evtest and xev when using touch?

**Comment by gbkelley** [comment]
With xev I get buttonpress events in most places but not tapping on the applet icons (Wifi, Vol, Batt)

**Comment by gbkelley** [comment]
Turns out to be touchegg - when it's running, can't tap in applet. When it isn't running, applet allows touch.
