### ISSUE TITLE
Better China Bug

### ISSUE THREAD

**Issue by l405111** [linuxmint/Cinnamon#6846]
Hi again friends there I'm sorry again apologize for my English, I'm still the Google Translate

The China bug language is not in the right way, too long and not right in the road. Can be fixed? yes, as the yolk made this translate very bad, so great time made by making the book short. I can help maybe? Everything fit correctly in the button bottom box? If this is not legal please make sure to tell me as I can be of help. Ok thanks for consideration again sorry again apologize for my English. :)

**Comment by itzexor** [comment]
We can't understand the translation. If you know a person who speaks english and chinese, ask them to translate.

谷歌翻译
我们无法理解翻译。 如果你知道一个说英文和中文的人，请他们翻译

**Comment by l405111** [comment]
:D good, I have a friend to traveling here from 香港 in seven months, they will say proper english to have tell you what better china bug translate is!
Ok thanks!

**Comment by l405111** [comment]
is this there news on @itzexor or could we translate from tommorow

**Comment by itzexor** [comment]
I'm sorry, I don't know what the original message means. We will have to wait.
