### ISSUE TITLE
It is possible to take screenshots from a locked screen

### ISSUE THREAD

**Issue by nick-s-b** [linuxmint/Cinnamon#6847]
```
* Cinnamon 3.4.4
* Arch
* Nvidia binary 384.59 
* 64 bit
 ```

**Issue**
If you have `gnome-screenshot` installed and have it assigned to a key, say PrintScreen, it can be invoked from a Locked Screen and it will write a file. I'm guessing you could hold it for a very long time and fill up the whole volume. Could that cause some security/instability  issues? I don't know. I haven't tried it.

**Steps to reproduce**
Double check that `gnome-screenshot` is installed and make sure it is assigned to a key like the default PrintScreen. Then lock the screen and press the assigned key.

**Expected behaviour**
You shouldn't be able to take screenshots of a locked screen.

**Other information**
I discovered this after I cleaned my keyboard and found a bunch of screenshots of the locked screen.

**Comment by leigh123linux** [comment]
File the issue against cinnamon-screensaver as that is responsible for locking.
