### ISSUE TITLE
Keyboard shortcut for status bar access

### ISSUE THREAD

**Issue by eudennis** [linuxmint/Cinnamon#6848]
```
 * Cinnamon version 3.4.6
 * Distribution - Gnome Ubuntu 17.04
 * Graphics hardware *and* driver used - Intel
 * 64 bits
 ```

**Issue**
Access the "system tray icons" (also know as status bar) with a keyboard shortcut.

**Steps to reproduce**
In Ubuntu Unity, I could do that with "Alt + F10", to focus on status bar and use keyboard to move throug itens

**Expected behaviour**
Press a combination of keys (maybe Alt + F10, just like Unity) to put focus on the applets icons, so I could use the keyboard to navigate in it.

**Other information**

**Comment by leigh123linux** [comment]
Why should we add it just because unity had it?

**Comment by eudennis** [comment]
Actually is not because Unity has it, but because it's useful for navigation without mouse. I was thinking that it could have something similar and I didn't found it.

**Comment by JosephMcc** [comment]
Thank you for your suggestion. See https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html for information on how we handle feature requests.
