### ISSUE TITLE
Effect curve for Maximising Windows can not be set

### ISSUE THREAD

**Issue by LingMan** [linuxmint/Cinnamon#6856]
```
 * Cinnamon version (cinnamon --version): 3.4.4
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...): Manjaro
 * Graphics hardware *and* driver used: AMD R9 390 with Radeon driver
 * 32 or 64 bit: 64bit
 ```

**Issue**
Under System Settings -> Effects -> Customize you can select a number of curves which determine how the effects are applied on the time axis. Selecting one curve for "Minimizing Windows" applies the same curve to "Maximising Windows". Selecting a curve for "Maximising Windows" appears to have no effect.

**Steps to reproduce**
Select for example easeOutInElastic for "Minimizing Windows" and easeInExpo for "Maximising Windows". Minimize and maximise a window a few times and you should clearly see that easeOutInElastic is applied in both cases.

**Expected behaviour**
Curves selected for "Maximising Windows" actually have an effect.

**Comment by JosephMcc** [comment]
I'm unable to reproduce this on the latest git master.

**Comment by LingMan** [comment]
The problem is still there on 3.4.6, I'll test 3.6.0 once it is available in my distribution's repositories.

**Comment by LingMan** [comment]
I'm afraid this report was invalid from the beginning. Maximizing is not the same as unminimizing. I was actually unminimizing, but there is no separate effect selection for unminimizing.
