### ISSUE TITLE
how to add launchers or icon to the second panel ?

### ISSUE THREAD

**Issue by lo2lo2a82** [linuxmint/Cinnamon#6857]
```
 * Cinnamon version (cinnamon 3.4.6-1)
 * Distribution - (Antergos)
 * Graphics hardware *and* driver used
 * 32 or 64 bit
 ```

**Issue**
cant add new icons or lanchuer on my second panel cant make the icons  move from the first panel to second 
and when adding lanucher from menu it add automaticly to the first panel 
what should i do ???

**Steps to reproduce**

**Expected behaviour**

**Other information**

**Comment by SerafDosSantos** [comment]
Add a launcher applet to the second panel and drag from the menu or the first panel the launchers to the second panel in the launcher applet.

**Comment by lo2lo2a82** [comment]
i found something called launchers draggable switch added it to the second panel ... thank you SerafDosSantos

**Comment by NikoKrause** [comment]
Please close the issue, of it's solved.
