### ISSUE TITLE
Cinnamon-screensaver bypassable in VMware Workstation

### ISSUE THREAD

**Issue by CatCookie** [linuxmint/Cinnamon#6859]
```
 * Cinnamon version 3.4.6
 * Distribution - Mint 18.2
 * Vmware Workstation 12.5.7 build-5813279 Pro
 * 64 bit
 ```

**Issue**
When resizing a locked VM window and going into fullscreen after that, the lock-screen still has focus, but has the size of the smaller, resized window.
Then you can paste commands into an open terminal (with middle mouse button) or copy information out of an open terminal. 
Keyboard focus is still on the lockscreen.

**Steps to reproduce**
* Open Terminal window
* Resize VM window
* Put VM in fullscreen again
* Paste 'killall cinnamon-screensaver <linebreak>' into open terminal. (middle mouse button)
-> Lockscreen bypassed

**Comment by leigh123linux** [comment]
The issue should have been filed against cinnamon-screensaver.

**Comment by CatCookie** [comment]
Sorry
