### ISSUE TITLE
Desktop icon disappear after a short while when I log in

### ISSUE THREAD

**Issue by sunnixx** [linuxmint/Cinnamon#6860]
```
 * Cinnamon version (3.4.6)
 * Distribution - (Ubuntu 16.04)
 * Graphics hardware *and* driver used
 * 64 bit
 ```

**Issue**
When I log in after a short while my desktop icons disappear. And to make them re-appear I need to go to desktop settings and toggle "don't show desktop icons" to "show desktop icons". After that the icons come back but then they overlap each other. 

**Steps to reproduce**

**Expected behaviour**

**Other information**

**Comment by leigh123linux** [comment]
Issue moved to [linuxmint/nemo #1593](https://github.com/linuxmint/nemo/issues/1593) via [**ZenHub**](https://www.zenhub.com/)
