### ISSUE TITLE
Unable to maximize window after tiling

### ISSUE THREAD

**Issue by dccannon** [linuxmint/Cinnamon#6861]
```
 * Cinnamon version: 3.4.6
 * Distribution: Linux Mint 18.2
 * Graphics hardware *and* driver used: NVIDIA GeForce GTX 950M / issue occurred with both the xserver-xorg-videa-nouveau and nvidia-375 drivers
 * 32 or 64 bit: 64 bit
 ```

**Issue**
If I have more than two windows open on a screen and I tile one of these windows (e.g., using Super+Left), then I become unable to ever maximize any of the three or more windows, neither by using the maximize button; by using combinations of Super+Up, Super+Left, etc.; nor by dragging the window to the top of the screen. 

I have enabled "Maximize, instead of tile, when dragging a window to the top edge" in the Window Tiling settings, and this has not changed the behavior. If I drag a window to the top, a transparent black box will fill the entire screen, but when I let go of the mouse, the window will fill only the area in which it is tiled, rather than the entire screen.

**Steps to reproduce**

1. Open three windows on the same screen. 
2. Tile one of the windows to the right, by selecting it and pressing Super+Right. 
3. Tile one of the other windows to the left, by pressing Super+Left.
3. Attempt to maximize any of the three windows.

**Expected behaviour**

In previous versions of Mint / Cinnamon, I could maximize a tiled window by Super + Left (if the window was tiled to the right) and then pressing Super + Up. Alternatively, I could maximize a tiled window by pressing the maximize button.

**Other information**

**Comment by lnikon** [comment]
In archlinux with Cinnamon of version 3.4.4 all works fine.

**Comment by mtwebster** [comment]
Are you sure you're not 'snapping' windows - have you messed with keybindings?

Snapping a window will cause it to occupy a tile region as if it were a panel or some other permanent thing.  That would prevent other windows from maximizing potentially.  Check your settings and keybindings.

This stuff code-wise hasn't been messed with in some time, so I suspect (at least initially) a configuration issue maybe.

Is there any thing in ~/.xsession-errors when you attempt to do this?

**Comment by dccannon** [comment]
Thank you both for your quick responses. 

I have not modified any keybindings, and I experience the same behavior when I drag the windows to the side of the screen (rather than using keyboard shortcuts). In the Window Tiling settings, I see an option for "Modifier to use for toggling between tile and snap mode," which is set to "Control." When I use the Ctrl+Super+Left to snap a window to the left, it seems to behave exactly the same way, and if set that option to "None," there is no change in behavior. 

In an attempt to rule out some configuration change that I made, I tried booting directly from the Linux Mint 18.2 Live USB, and I experience the exact same behavior. I have not yet a tried a different computer, but will try that next.

I see the following in my .xsession-errors while running on the Live USB, none of which seem to be related. No new errors are generated while I snap/tile windows:

```
$ cat .xsession-errors 
** Message: couldn't access control socket: /run/user/999/keyring/control: No such file or directory
** Message: couldn't access control socket: /run/user/999/keyring/control: No such file or directory
** Message: couldn't access control socket: /run/user/999/keyring/control: No such file or directory
[cinnamon-settings-daemon-smartcard] Failed to start: no suitable smartcard driver could be found
[cinnamon-settings-daemon-smartcard] Failed to start: no suitable smartcard driver could be found
Cjs-Message: JS LOG: About to start Cinnamon
St-Message: cogl npot texture sizes SUPPORTED
Cjs-Message: JS LOG: Cinnamon started at Tue Aug 29 2017 22:22:24 GMT+0000 (UTC)

(cinnamon:2071): St-WARNING **: Ignoring length property that isn't a number at line 1526, col 13
openGL version 4.3 detected (GL3 Cogl Driver)
MetaSyncRing disabled: couldn't find required GL extensions, or the minimum safe openGL version was not met
failed to create drawable
Cjs-Message: JS LOG: Invalid network device type, is 14

(cinnamon:2071): St-WARNING **: Ignoring length property that isn't a number at line 1526, col 13

(cinnamon:2071): St-WARNING **: Ignoring length property that isn't a number at line 1526, col 13
Window manager warning: Log level 16: STACK_OP_RAISE_ABOVE: sibling window 0x5000001 not in stack
nm-applet-Message: No keyring secrets found for <REDACTED>; asking user.
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
```

(Redacted only to remove the name of my wireless network.)

**Comment by dccannon** [comment]
Well, this is embarrassing. 

As I've been tinkering with it more, I think that I may have been inadvertently holding down the Ctrl key (i.e., doing Ctrl+Super+Left instead of just Super+Left) -- a habit I've probably picked up because I've had to switch back into Windows-land a lot this week, where that's the shortcut. 

Apparently once you "snap" a window with Ctrl+Super+Left, that window permanently occupies that space, and it becomes impossible to maximize other windows on top of it. Interestingly, if I change the "Modifier to use for toggling between tile and snap mode" settings, this doesn't seem to have any effect. Ctrl+Super+Left still "snaps" the window (causing it to permanently occupy the space), so I'm not sure that setting changes anything -- or perhaps it's being overriden by some other setting.

Anyway, looks like this one's user error. Thank you for your help!
