### ISSUE TITLE
Very dangerous bug !! tty terminal affected !!

### ISSUE THREAD

**Issue by Nokia808** [linuxmint/Cinnamon#6863]
```
 * Cinnamon version (I'm not sure but mostly 3.4.4 I'm now on 3.4.6 but I think that it happened on 3.4.4)
 * Distribution - (Fedora 26)
 * Graphics hardware: Intel Corporation HD Graphic 5500
 * 64 bit
 ```
Hi.

I suffered from a dangerous bug. I say dangerous because tty terminal NOT help me as workaround & being affected by it !! The case as following:

My Cinnamon was to sleep. Before became blank, pass in transparency state. I tried to touch touchpad to prevent it from sleep. However, I did not reach at transparency. I touched touchpad just when screen become blak (just after end of transparent stage), during 1st sec when screen became black, may be 1st 1/2 second from black screen.

The bug was in the forum that normal screen can not bring to be active in normal way: just blink for a 1/2 sec or 1 sec, then return black, remain black for about 30 sec (shorter / longer) then blink again. Press any key or mouse or touchpad were useless.

All above are easy, because user can bring tty then login then reboot & that is all. But what happened with me was that when I press Fn+Ctrl+Alt then F2, tty terminal became active BUT ALSO AFFECTED BY BLINKING !!!

I tried to return to Cinnamon by Fn+Alt then F1 but Cinnamon still suffering from blinking !!

I tried to restart Xorg by Ctl+Alt+Backspace but still in blinking (long black screen time then hust 1 sec blink then return to long black screen) !!

I observed that although tty terminal affected but even during in black screen of tty my typing entered in tty terminal.

I said to my self: O.K let me in tty terminal enter my user name then enter my password then use reboot command. But later on I had fear that this my be dangreous because tty terminal affected by blinking & this my break security of my password enterance, so I dicided to power off laptop by long pressing on "power" key of laptop, & indeed this what I did.

After power off laptop by long press of "power" key, I relaunched laptop ......

--------------------
I already post about this issue in Fedora community forum at this link:
https://www.forums.fedoraforum.org/showthread.php?t=315252

**Comment by leigh123linux** [comment]
Issue moved to [linuxmint/cinnamon-screensaver #240](https://github.com/linuxmint/cinnamon-screensaver/issues/240) via [**ZenHub**](https://www.zenhub.com/)
