### ISSUE TITLE
[Request] Alternative Alt+Tab Behaviour

### ISSUE THREAD

**Issue by H8to** [linuxmint/Cinnamon#6864]
```
 * Cinnamon version (Cinnamon 3.4.4)
 * Distribution - Arch Linux
 * 64 bit
 ```

**Issue**
The current Alt+Tab feautre moves minimized windows to the end of the switcher.

**Expected behaviour**
Often I want to switch back to previously minimized windows. It feels more consistent if the switcher does not move minimized windows to the back.

I fixed this in my local code but don't know how to write a proper patch that I could request to be merged, as it has to be included into the Alt+Tab settings page to be configurable.

**Other information**
The change I make to my code after each update:

> /usr/share/cinnamon/js/ui/appSwitcher/appSwitcher.js

```
function sortWindowsByUserTime(win1, win2) {
    let t1 = win1.get_user_time();
    let t2 = win2.get_user_time();
//    let m1 = win1.minimized;
//    let m2 = win2.minimized;
    return (t2 > t1) ? 1 : -1;
//    if (m1 == m2) {
//        return (t2 > t1) ? 1 : -1;
//    }
//    else {
//        return m1 ? 1 : -1;
//    }
}
```

I would be so glad, if somebody can help with his knowledge here :+1:

**Comment by bgstack15** [comment]
My recent pull request about appSwitcher modified 3 files: https://github.com/linuxmint/Cinnamon/pull/6938/files. Start with those files. If you give me a few days, I could attempt a patch/PR for you with your snippet.

**Comment by H8to** [comment]
Hey @bgstack15 
Cool!
I tried it myself and have tried the following edits:

/usr/share/glib-2.0/schemas/**org.cinnamon.gschema.xml**
```
<key type="b" name="alttab-minimized-aware">
    <default>true</default>
    <summary>Move minimized windows to the end of the appSwitcher</summary>
</key>
```
/usr/share/cinnamon/cinnamon-settings/modules/**cs_windows.py**
```
widget = GSettingsSwitch(_("Move minimized windows to the end of the alt-tab switcher"), "org.cinnamon", "alttab-minimized-aware")
            settings.add_row(widget)
```

/usr/share/cinnamon/js/ui/appSwitcher/**appSwitcher.js**
```
function sortWindowsByUserTime(win1, win2) {
    let t1 = win1.get_user_time();
    let t2 = win2.get_user_time();

    this.minimizedAwareAltTab = global.settings.get_boolean("alttab-minimized-aware");
    if (!this.minimizedAwareAltTab) {
      let m1 = win1.minimized;
      let m2 = win2.minimized;
      if (m1 == m2) {
          return (t2 > t1) ? 1 : -1;
      }
      else {
          return m1 ? 1 : -1;
      }
    }
    else {
      return (t2 > t1) ? 1 : -1;
    }
}
```
However, this leads to an unfunctional Window-Settings which will not open.
I'm quite sure this is caused by a missing translation, that I might have to add in the lang file?
On the other side I wonder, if this is really the cause. Do you see any issues in my code?

Thanks in advance! :)

**Comment by bgstack15** [comment]
You need to update your gsettings schema in use in your environment using `glib-compile-schemas /usr/share/glib-2.0/schemas`. See my blog post about this: https://bgstack15.wordpress.com/2017/10/19/cinnamon-adds-show-all-workspaces-setting-to-alt-tab-appswitcher/

**Comment by H8to** [comment]
Great! Works like a charm =) 
I'll try to create a pull request the next days :+1:

**Comment by clefebvre** [comment]
Merged.
