### ISSUE TITLE
desktop prefers downscaled backgroundimages if two screens with different resolutions are connected

### ISSUE THREAD

**Issue by Cyborgscode** [linuxmint/Cinnamon#6865]
```
3.4.6
Fedora 25
GTX 1050 with RPMFusion Nvidia drivers
64bit
https://bugzilla.redhat.com/show_bug.cgi?id=1487166
 ```

Short form:

2 displays connected, with 2 different resolutions.
When backgroundimage(bgi) is choosen in a desktopsession, it gets rendered correctly with fullhd resolution on the bug screen and a downscaled version on the other.

When cinnamon starts, it downscales the image for both displays to something not matching anywhere and no screen gets the correct resolution.

Obviosly, the correct behavior would be to not scale for the fullhd display, and create a scaled version for the smaller display, as it's  done, when the bgi is choosen on runtime.

Sidenote: if i reselect the same image after a reboot (when it's shown downscaled) it gets rendered correctly in full resoultion. so this bug only covers the startup phase of cinnamon.

**Comment by JosephMcc** [comment]
Looks the same as https://github.com/linuxmint/Cinnamon/issues/7035

**Comment by Cyborgscode** [comment]
usually, you close the newest bugreport, and not the one with the reference to redhat's bugtracker inside ;)
