### ISSUE TITLE
Attempting to connect to a PEAP-secured network causes infinite loading wheel

### ISSUE THREAD

**Issue by The-Fireplace** [linuxmint/Cinnamon#6868]
```
 * Cinnamon version 3.4.6
 * Distribution - Mint 18.2
 * AMD Radeon R6 Graphics, unknown driver(how do I find that out?)
 * 64 bit
 ```

**Issue**
When I attempt to connect to a wireless network secured with PEAP, it gives me  an infinite loading wheel.

**Steps to reproduce**
1.) Open the Network Manager
2.) Click the connect button for the network you are trying to connect to (It must be Dynamic WEP (802.1x) with PEAP authentication type)
3.) The connect button will turn into an infinite loading wheel

**Expected behaviour**
After clicking the button, I expect a login dialog to pop up so I can log in to the network.

**Other information**
I have tested this on 2 networks, both of which result in the same behavior.

**Comment by leigh123linux** [comment]
Issue moved to [linuxmint/cinnamon-control-center #180](https://github.com/linuxmint/cinnamon-control-center/issues/180) via [**ZenHub**](https://www.zenhub.com/)
