### ISSUE TITLE
Website improvements

### ISSUE THREAD

**Issue by Salvatos** [linuxmint/Cinnamon#687]
Hi, I just started using Cinnamon and I thought the website was a bit lacking in terms of info and features, so I'll just put my thoughts here. I'm liking Cinnamon itself so far :)

- You may want to link the github from the site. The Cinnamon community isn't really put forward as it stands, in my opinion.
- I think the login/register/search bar should be on every page, not just the addons. It's annoying to move to a page just to get a link to another page that should be part of a menu.
- The profile only allows Mint as a Distribution (not much of a concern, but why ask if there's no real choice? ;))

- Addons (extensions, themes, etc.):
-- Maybe the instructions should be at the top of the page rather than the bottom, since they're not very visible as is (though they weren't hard to spot in each addon's page)
-- More a question than a suggestion, but I'd like to know how the 5-star ratings translate into scores. Is 3-stars counted as +0 and higher or lower ratings impact the actual score?
-- I think comments should be dated and allow replies, like in the news entries.

- Sorting:
-- Not an urgent feature, but it would be nice to sort themes by color scheme (and be able to select more than one + transparency). This will help greatly when they reach the hundreds.
-- Extensions and applets could use some sorting as well based on the features they affect, or, perhaps easier, allow tag searching since they can include quite a variety of things. At the moment, someone looking for a specific feature has to skim through the entire catalog.

- The download page lists Ubuntu 11.10, so unless there's a particular reason it should be updated to 12.04 at some point (if the version number is even needed).

- Missing: a features/about page. Someone who comes onto the site with having just heard about Cinnamon has nothing but a single screenshot and a short sentence to learn what it's about. A rundown of its features and/or a comparison against other window managers (is that how these things are called?) would be helpful. I find it's always important to have plenty of screenshots available for things that rely strongly on appearance to appeal to their users.

- The news should probably be dated in the News and Home pages as well as their individual page. That's a great way to see if a project is alive and active at first glance and encourages newcomers.

- You could consider making a FAQ, though so far the Help tips and each page have done well in telling me most of what I wanted to know.

That's all I have so far, hopefully it will prove useful :)

**Comment by JosephMcc** [comment]
We have a git repo specifically for these types of issues now: https://github.com/linuxmint/mint-design
