### ISSUE TITLE
Restarting cinnamon breaks rendering of open tabs in firefox

### ISSUE THREAD

**Issue by SethosII** [linuxmint/Cinnamon#6874]
```
 * Cinnamon version (cinnamon --version): Cinnamon 3.4.6
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...): Mint 18.2
 * Graphics hardware *and* driver used:
lshw -class video
  *-display               
       description: VGA compatible controller
       product: Sky Lake Integrated Graphics
       vendor: Intel Corporation
       physical id: 2
       bus info: pci@0000:00:02.0
       version: 07
       width: 64 bits
       clock: 33MHz
       capabilities: pciexpress msi pm vga_controller bus_master cap_list rom
       configuration: driver=i915 latency=0
       resources: irq:280 memory:f0000000-f0ffffff memory:e0000000-efffffff ioport:e000(size=64) memory:c0000-dffff
 * 32 or 64 bit: 64 bit
 ```

**Issue**

Restarting cinnamon breaks the rendering of websites in open tabs in firefox. A white page with a circle is displayed instead of the content. Reloading open tabs doesn't help, only restarting firefox helps. Tabs opened after the restart of cinnamon are displayed normally.

**Steps to reproduce**

1. start firefox
2. restart cinnamon `Ctrl+Alt+Esc`/`Alt+F2, r`
3. open tab is not displayed correctly
4. try reloading the tab -> still doesn't work
5. open url in new tab -> works

**Expected behaviour**

The rendering of websites by firefox shouldn't be influenced by a restart of cinnamon.

**Other information**

Version of firefox: `Mozilla Firefox 55.0.2`.

The applets I'm using are [Icing Task Manger](https://cinnamon-spices.linuxmint.com/applets/view/269) and [Weather](https://cinnamon-spices.linuxmint.com/applets/view/17).

**Comment by clefebvre** [comment]
Confirmed. It looks like a regression in Firefox because according to the team it's happening not only in Mint but also in Fedora and people see it happen with either git master or 3.4.

**Comment by SethosII** [comment]
Fixed for me with Firefox 56.

**Comment by JosephMcc** [comment]
Yep this issue seems to be solved in newer Firefox versions.
