### ISSUE TITLE
Power management applet crashes

### ISSUE THREAD

**Issue by tcharding** [linuxmint/Cinnamon#6876]
```
 * Cinnamon 2.8.6
 * Ubuntu 16.04.3 LTS
 * 64 bit
```
Graphics
```
description: VGA compatible controller
product: Broadwell-U Integrated Graphics
vendor: Intel Corporation
physical id: 2
bus info: pci@0000:00:02.0
version: 08
width: 64 bits
clock: 33MHz
capabilities: msi pm vga_controller bus_master cap_list rom
configuration: driver=i915 latency=0
resources: irq:46 memory:f6000000-f6ffffff memory:e0000000-efffffff ioport:f000(size=64)
```

**Issue**

Power management applet (within System Settings) crashes when selected. Other settings function correctly, however, selecting power management causes the settings window to disappear. System crash notification comes up occasionally. 

**Steps to reproduce**

Open System Settings. Select `Power Management`.

**Expected behaviour**

Power management settings should be displayed.

**Other information**

**Comment by NikoKrause** [comment]
I'm not sure if I understand correctly, what you mean.
Do you mean:
* System Settings -> Applets -> Power Management:
![bildschirmfoto vom 2017-09-05 09-56-39](https://user-images.githubusercontent.com/8415124/30050975-a2fd82e6-9220-11e7-945e-e74873ac5873.png)
or
* System Settings -> Power Management:
![bildschirmfoto vom 2017-09-05 09-57-09](https://user-images.githubusercontent.com/8415124/30050988-ac8c70f6-9220-11e7-931b-5f5a00ee3fc5.png)

The first one is an applet and the second one is an application.

>System crash notification comes up occasionally.

What does the crash notification say?

**Comment by tcharding** [comment]
Sorry for not being clear. It is the second one, the application. 

 >> System crash notification comes up occasionally.

> What does the crash notification say?
I have not managed to get the notification again (got it once in the past). I just tried 10 times. Also selecting the battery icon in the panel and choosing `Power Settings` has no effect.

Anything else I can do to help trouble shoot, please ask.

thanks

**Comment by pimuzzo** [comment]
hi,
same issue on debian testing:
```
Loading Power module
Traceback (most recent call last):
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 553, in button_press
    self.side_view_nav(widget, None, category)
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 113, in side_view_nav
    self.go_to_sidepage(cat, filtered_path)
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 126, in go_to_sidepage
    sidePage.build()
  File "/usr/share/cinnamon/cinnamon-settings/bin/SettingsWidgets.py", line 123, in build
    self.module.on_module_selected()
  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_power.py", line 115, in on_module_selected
    device_types = [x[UP_TYPE] for x in self.csd_power_proxy.GetDevices()]
  File "/usr/lib/python2.7/dist-packages/gi/overrides/Gio.py", line 172, in __call__
    None)
GLib.Error: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.cinnamon.SettingsDaemon was not provided by any .service files (2)
```
Tell me how can I help you more.

**Comment by NikoKrause** [comment]
@tcharding 
Open a terminal and type `cinnamon-settings power`.
Then post the output.

@pimuzzo 
Your `cinnamon-settings-daemon` is not running, I think. What does ` pgrep -fa cinnamon-settings-daemon` say?

**Comment by NikoKrause** [comment]
@pimuzzo 
Maybe this one is related https://github.com/linuxmint/Cinnamon/issues/6799

**Comment by pimuzzo** [comment]
thanks @NikoKrause `cinnamon-settings-daemon` is not running, I'll take a look for the reason, output of pgrep is empty

**Comment by leigh123linux** [comment]
@pimuzzo your issue was fixed

https://github.com/linuxmint/cinnamon-session/commit/402355658665f5d544452e39902213c1d9027895

**Comment by leigh123linux** [comment]
@tcharding cinnamon-2.8 is EOL so there is no point in leaving the issue open.

You will need to DIY or update to 3.4

This may fix your issue

https://github.com/linuxmint/Cinnamon/issues/5410

**Comment by tcharding** [comment]
thanks @leigh123linux
