### ISSUE TITLE
Security Bug, view beyond lock screen in VM session.

### ISSUE THREAD

**Issue by kykrueger** [linuxmint/Cinnamon#6877]
```
 * Cinnamon version (cinnamon --version)
 * Distribution - Mint 8.0.7 'Sarah'
 * i5 7200U - InnoTek Systemberatung GmbH VirtualBox Graphics Adapter
 * 64 bit
 ```

**Issue**
One can see past lock screen when resizing a locked VM session.

**Steps to reproduce**
Lock screen in VM session. Resize the window to be smaller, and then full-screen.

**Expected behaviour**
When redrawing the UI, the desktop behind the lock screen renders before the lock screen. Allowing the user to see what is behind.

**Comment by leigh123linux** [comment]
https://github.com/linuxmint/cinnamon-screensaver/issues/239
