### ISSUE TITLE
Language and region selection in the language settings configuration are a mess

### ISSUE THREAD

**Issue by ErwinBaeyens** [linuxmint/Cinnamon#6880]
```
 * Cinnamon version - 3.4.6
 * Distribution - Fedora 25
 * Graphics hardware N/A
 * 64 bit
 ```

**Issue**

The Language an Region selection are a mess. When clicking the button to change the language and region settings in the system settings applet,  one is presented with an incomprehensible mess.  The presented list of languages and regions does not follow  logical sorting. The fact that a flag is include in the menu's makes this even worse, as the same flag is sometimes used for different languages.
As an example of some of the mess,  the list jumps from:
* English - Zimbabwe to Spanish, Castilian, Argentina (neither S nor C follow E in any common alphabet)
* cv, Russia - Welsh, United Kingdom
* Danish Danmark - German, Austria (English, Estonian, ...  should be in between these) 
* Spanish, Castilian, Venezuela -  Estonian, Estonia
* Estonian, Estonia - Basque, Spain
* ... you get the picture

Adding the flag icon, while a nice touch,  makes the list unnecessary large and it takes too much space on the screen

**Steps to reproduce**
Every time. Open System Settings -> Languages and try to change either language or region.

**Expected behaviour**
The presented list should be sorted by country, then by language. An alternative way could be to make the language dependant of the country that is selected.  E.g.:  Select Belgium in the Region and be presented with a list of Languages with the most common ones for that region on top.  This would make the selection more logical while still allowing for 'odd'  languages  for a region to be selected.

**Comment by leigh123linux** [comment]
Issue moved to [linuxmint/mintlocale #47](https://github.com/linuxmint/mintlocale/issues/47) via [**ZenHub**](https://www.zenhub.com/)
