### ISSUE TITLE
Resize icon is missing

### ISSUE THREAD

**Issue by mckatzenelson** [linuxmint/Cinnamon#6883]
```
 * Cinnamon version (cinnamon --version)
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
 * Graphics hardware *and* driver used
 * 32 or 64 bit
 ```

**Issue**
The item "resize" is missing from the context menu associated with the each icon on the desktop

**Steps to reproduce**
right-click on any icon on the desktop.

**Expected behaviour**
A menu should appear that lists "resize icon" as one of its items.

**Other information**

This is actually a very important function.   Leaving it out, makes the desktop less useful.

**Comment by NikoKrause** [comment]
Which Cinnamon version do you use? In Cinnamon 3.4 right-click on a free space on the desktop, there is an item `Desktop -> Icon Size -> Small/Normal/Bigger`

**Comment by mckatzenelson** [comment]
cinnamon-desktop 3.4.2,  it is the per-icon resizing item that is missing.

Previously, you could right-click on an icon and in the menu for that icon,  there was an item to resize that specific icon.

**Comment by leigh123linux** [comment]
That was removed in nemo-3.4
