### ISSUE TITLE
­[Feature Request] Allow Configuration Of Mouse Middle Click

### ISSUE THREAD

**Issue by SerafDosSantos** [linuxmint/Cinnamon#6887]
Is that feasible on a Debian system? On Ubuntu? Can it be done on Mint?

I would like to particularly set the mouse middle click like we can set actions to keyboard shortcuts.

Thanks for your frank responses.

**Comment by leigh123linux** [comment]
Closed as the issue belongs to cinnamon-settings-daemon

https://github.com/linuxmint/cinnamon-settings-daemon/issues

It would also help if you done some research (google) to see what you are asking is possible using evdev/libinput

https://wayland.freedesktop.org/libinput/doc/latest/

https://www.freedesktop.org/software/libevdev/doc/latest/

maybe search to see if other users have succeeded.
