### ISSUE TITLE
Panel sizing corrupted after changing screen resolution -- even after changing primary display to another monitor

### ISSUE THREAD

**Issue by chuckhacker** [linuxmint/cinnamon#6890]
```
 * Cinnamon version (cinnamon --version): Cinnamon 3.4.6
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...): Arch Linux, also Linux Mint 18.2 is affected (I dual boot Mint and Arch and they both have this same exact problem).
 * Graphics hardware *and* driver used: NVIDIA Quadro M2000M 4 GB and Intel HD 530 (Optimus)
 * 32 or 64 bit: 64bit

 ```

**Issue**

I'm using a Lenovo Thinkpad P50 laptop.

See screenshot:
https://imgur.com/a/dYIDZ

My system tray is cut off, as you can see the time and the system tray icons are halfway off the screen and are difficult to read/use.

**Steps to reproduce**

1. Start in 4K. Change 4K 15" laptop LCD display resolution to 1080p, problem occurs.
2. Move panel to external 1080p 21" monitor, problem still occurs.

**Expected behaviour**

System tray should appear scaled and translated properly.

**Other information**

Happy to test for you.

**Comment by itzexor** [comment]
Which cinnamon theme are you using? & does this occur with the default theme?

**Comment by chuckhacker** [comment]
Verified happening with Discreet-Flat and New-Minty in Arch. I can check later what theme I'm using in Mint (it is a different one -- I think the default Mint one?). Haven't tested with the default theme yet.

**Comment by chuckhacker** [comment]
Also, pressing ALT+F2, r, <ENTER> to restart Cinnamon in-place "solves" the issue in a band-aid way.

**Comment by RalfJung** [comment]
I am having the same problem on Debian, with whatever is the default theme there (called "Cinnamon" in the settings).

**Comment by icarter09** [comment]
@chuckhacker are you still experiencing this issue on the latest version of Cinnamon?
