### ISSUE TITLE
Encrypted system does not boot after kernel upgrade

### ISSUE THREAD

**Issue by Thunderlight1** [linuxmint/Cinnamon#6891]
```
 * Cinnamon version (cinnamon --version): **Cinnamon 3.4.6**
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...): **Linux Mint 18.2 Sonya**
 * Graphics hardware *and* driver used
 * 32 or 64 bit: **64-bit**
 ```

**Issue**
Installed my machine with the default encryption of the whole system, but not the home directory. After upgrading to a newer kernel with apt-get, it does not start anymore. It stops after I have entered the encryption password and confirming that the password is correct.
To have it start, I need to select the old kernel.
Tried to build ramdisk, but it did not help.

**Steps to reproduce**
Install a new Linux Mint 18.2 system with the option encrypt system.
Update the system and install a newer kernel.
Reboot system.
Enter encryption password.
Screen confirms the correct password.
System hangs.

**Expected behaviour**
System should start using the new selected kernel.

**Other information**
Workaround: You can start the system by selecting the old kernel at the grub menu.
Could not find any logs about this issue in /var/log directory.

**Comment by leigh123linux** [comment]
Not a cinnamon issue
