### ISSUE TITLE
Top-left corner will be blocked for mouse click while "Display" app is running.

### ISSUE THREAD

**Issue by SmilerCat** [linuxmint/Cinnamon#6892]
```
 * Cinnamon version (cinnamon --version): Cinnamon 3.4.6
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...): Linux Mint 18.2 Sonya
 * Graphics hardware *and* driver used: 
                        - Card: Intel Device 5912
                        - Display Server: X.Org 1.18.4 
                        - drivers: intel (unloaded: fbdev,vesa) 
                        - Resolution: 1920x1080@60.00hz
                        - GLX Renderer: Mesa DRI Intel Kabylake GT2 GLX 
                        - Version: 3.0 Mesa 17.0.7
 * 32 or 64 bit: 64bit
 ```

**Issue**
After starting "System Settings -> Display" an invisible area appears that locks the mouse cursor. Named as MetaWindowActor.

**Steps to reproduce**
Call up "Menu -> System Settings -> Display". In the background, an application / program can be launched, eg "xed". For best result - window maximized. Try click "File" or "Edit" menu.

**Expected behaviour**
Top-left corner (region [0, 0 X 266, 57]) will be blocked for mouse click while "Display" app is running.

**Other information**
more in screenshots
<details>
 <summary>"Display" maximized</summary>
<p><img src="https://user-images.githubusercontent.com/24717359/30274707-0a48a22c-9718-11e7-88e1-3f52d7a49ef1.png" alt="01_maximized_display" /></p>
</details>
<details>
 <summary>"Display" normal, XED maximized</summary>
<p><img src="https://user-images.githubusercontent.com/24717359/30274706-0a476056-9718-11e7-933a-50b7f0c91a9f.png" alt="02_normal_display" /></p>
</details>
<details>
 <summary>"Display" minimized</summary>
<p><img src="https://user-images.githubusercontent.com/24717359/30274708-0a4df1b4-9718-11e7-909d-75354fb2c3cd.png" alt="03_minimized_display" /></p>
</details>
So, while "Display" is running maximized or normal or minimized of the main window, top-left corner still broken.

P.S. 
    Sorry for my poor English.

**Comment by itzexor** [comment]
This is because it shows a label to identify the monitors in that position. In the current release there is a bug where the label doesn't show up properly but it is still there. That has already been fixed for the next release, but that area being blocked while "Display" is open is normal.

**Comment by itzexor** [comment]
![xed-and-display-label](https://user-images.githubusercontent.com/11601860/30409741-db038572-98bb-11e7-9432-24a4f9ae3ce5.png)
This thing ^

**Comment by SmilerCat** [comment]
Thanks
