### ISSUE TITLE
Drag&Drop windows in the Scale view

### ISSUE THREAD

**Issue by NicoWeio** [linuxmint/cinnamon#6895]
```
 * Cinnamon 2.4.8
 * Mint 17.1
 ```
I noticed I can drag&drop windows between monitors and workspaces in the workspaces view, I can't drag them at all in the expo view. Is that on purpose?

**Comment by brownsr** [comment]
@NicoWeio Could do with some clarification of what you are experiencing.  The workspace view is the expo view.  Do you perhaps mean 'scale' ?  If you can link to images of the two cases you are contrasting then that could help us to understand.

**Comment by brownsr** [comment]
OK, you do mean scale.  So you can move windows between monitors in the workspace view (expo) but can't do that in the scale view.  Got it.

**Comment by NicoWeio** [comment]
@JosephMcc @collinss Any updates/progress?

**Comment by gadass** [comment]
Hi @JosephMcc @collinss, I would just like to add that I also would like to see this feature in cinnamon.

**Comment by icarter09** [comment]
@collinss can this ticket be closed?

**Comment by collinss** [comment]
Yeah, though it should make it onto your list of ideas - it's a pretty good one.

**Comment by icarter09** [comment]
@collinss thanks. I'll close it out and document the feature request.

**Comment by NicoWeio** [comment]
@icarter09 
So where is that _list of ideas_? Do you keep track of feature requests internally? Because I can't find another place where this one is listed.
I wouldn't mind that – I'd just like to stay up to date.

**Comment by icarter09** [comment]
@NicoWeio I'm currently working through all the feature requests putting together a list of them to be added to the roadmap.
