### ISSUE TITLE
Please make it possible to enable keyboard lock notifications via OSD

### ISSUE THREAD

**Issue by rimas-kudelis** [linuxmint/Cinnamon#6896]
As keyboards without lock leds are gaining popularity, I think it would be great if the Cinnamon built-in OSD could be used to notify users of lock status changes. I myself am using a PC without a caps lock led, and have an external keyboard without one, but I sometimes accidentally press the Caps Lock key. It would be great if Cinnamon OSD could indicate such key presses for me.

**Comment by mtwebster** [comment]
Accessibility settings->Keyboard->Keyboard Indicators

**Comment by rimas-kudelis** [comment]
May I ask for this to be exposed in OSD settings as well? The idea of checking out accessibility settings never occurred to me.
