### ISSUE TITLE
Full screen should only hide the panel on the monitor showing full screen

### ISSUE THREAD

**Issue by rmwiseman** [linuxmint/cinnamon#6897]
```
 * Cinnamon 3.4.3
 * Mint 18.2
 * Intel Haswell-ULT Integrated Graphics Controller ("drivers: intel (unloaded: fbdev,vesa)")
 * 64 bit
 ```

**Issue**

When I make certain applications full screen, the panel is hidden on both my monitors even though the full-screen application only uses one monitor.  The result is that instead of the panel on the other monitor, I see a strip of the desktop background image.

This doesn't happen with YouTube videos but I was just watching a video [hosted elsewhere](http://wso2.com/library/articles/wso2con-2013-usa/keynote-apis-driving-the-stubhub-business/) (it uses Flash rather than HTML5 to deliver the video) and when I make it full-screen, the issue occurs.

It sometimes occurs with VirtualBox too, although there's an additional quirk, which is that the menu shown when you move to the top of the VM's screen actually appears in place of the other monitor's panel!

**Steps to reproduce**

Visit the URL above (the WSO2con one) with an external monitor connected (mine's above the primary one) and make it full-screen.  Once it is and has focus (i.e. has no window or panel in front of it) the panel on each monitor disappears, meaning that you can't use the start button or see/click any running program's icon.

**Expected behaviour**

Only the panel on the monitor currently showing full-screen is hidden.

**Other information**

I wasn't sure if this was a duplicate of issue #6293.

**Comment by icarter09** [comment]
@rmwiseman are you still experiencing this issue?

**Comment by rmwiseman** [comment]
> @rmwiseman are you still experiencing this issue?

I've just tried the video I originally linked and the issue did not occur, so I assume it has been fixed.  I'll close the issue now.  Thanks!
