### ISSUE TITLE
Cinnamon takes over Onboard dbus name

### ISSUE THREAD

**Issue by kozec** [linuxmint/Cinnamon#6899]
```
 * Cinnamon 3.4.3
 * Manjaro
 * Intel, intekl
 * 64 bit
 ```

**Issue**
Cinnamon seems to takes over Onboard dbus name, effectively preventing onboard from start

**Steps to reproduce**
run `onboard`

**Expected behaviour**
on-screen keyboard is shown

**Other information**
Tablet PC, no other keyboard is available.

**Comment by clefebvre** [comment]
Fixed in 3.6.

**Comment by kozec** [comment]
Thanks :)
