### ISSUE TITLE
[Feature request:] Allow sort by delay in Startup Applications

### ISSUE THREAD

**Issue by CottonEaster** [linuxmint/Cinnamon#6902]
```
 * Cinnamon version (cinnamon --version): 3.4.6
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 18.2
 ```

It would be useful, and intuitive, were it possible to sort the list of startup applications by delay.

**Comment by NeiroNx** [comment]
You may change it localy
https://github.com/linuxmint/Cinnamon/blob/master/files/usr/share/cinnamon/cinnamon-settings/modules/cs_startup.py#L444
Original
`        aname = a.app.name.lower()
        bname = b.app.name.lower()`
Needs
`        aname = a.app.delay
        bname = b.app.delay`

**Comment by CottonEaster** [comment]
Thanks but (1) that doesn't seem to work (perhaps I do something wrong, or need to log out), (2) what I think would be really good would be _a GUI option_ to toggle between sorting by name and sorting by delay. (My Python abilities are pretty much non-existent - though I have some experience in one or two other languages - so I can't propose a patch myself.)

**Comment by CottonEaster** [comment]
After restarting Cinnamon (via the panel GUI) I find that about half the list is ordered by startup delay, and other items aren't. Oh well.

**Comment by NeiroNx** [comment]
That code with buttons:
```
        self.sort_name=Gtk.Button.new_with_label(_("Sort by name"))
        self.sort_name.connect("clicked", lambda w:self.list_box.set_sort_func(self.sort_apps_name, None))
        box.add(self.sort_name)
        self.sort_delay=Gtk.Button.new_with_label(_("Sort by delay"))
        self.sort_delay.connect("clicked", lambda w:self.list_box.set_sort_func(self.sort_apps_delay, None))
        box.add(self.sort_delay)

    def add_row(self, row):
        self.list_box.add(row)

    def sort_apps_name(self, a, b, user_data):
        aname = a.app.name.lower()
        bname = b.app.name.lower()

        if aname < bname:
            return -1
        elif aname > bname:
            return 1
        else:
            return 0

    def sort_apps_delay(self, a, b, user_data):
        adelay = a.app.delay
        bdelay = b.app.delay

        if adelay < bdelay:
            return -1
        elif adelay > bdelay:
            return 1
        else:
            return 0
```

**Comment by clefebvre** [comment]
This is overkill.

Also, a good point from @itzexor:

> i think the list changing around when you change a setting is bad UX and the delay there isn't a guarantee of start order
