### ISSUE TITLE
cinnamon-settings : should allow tab selection of modules

### ISSUE THREAD

**Issue by jcalbert** [linuxmint/cinnamon#6904]
```
 * Cinnamon version 3.4.6
 * Distribution - Mint 18.2
 * GeForce GTX 960
 * 64 bit
 ```

**Issue**
After opening cinnamon-settings, a search box is focused and one is able to search for a module.  For example, typing 'keyb' yields this:
![screenshot from 2017-09-15 12-38-41](https://user-images.githubusercontent.com/4261275/30493860-dfcfa172-9a13-11e7-81ef-806322151a66.png)

Two desired behaviors:
1)  One should be able to navigate the results with `<Tab>` and `<Shift>+<Tab>`, and open a module with `<Return>`.
2)  `esc` should clear the search box.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
