### ISSUE TITLE
Allow natural scrolling for mouse (not only touchpad)

### ISSUE THREAD

**Issue by bittner** [linuxmint/Cinnamon#6906]
```
 * Cinnamon version: 3.2.7
 * Distribution: Ubuntu 17.04 Zesty
 * Graphics hardware *and* driver used -- n/a
 * 64 bit
 ```

**Issue**

The _System Settings_ > _Mouse and Touchpad_ dialog should also handle natural scrolling for for mice, not only for touchpoads. When I use a mouse I should be able to use the scroll-wheel as with natural scrolling.

This is somewhat a follow-up on issue #1930 and PR #1940.

**Steps to reproduce**

- On a Cinnamon desktop go to the System Settings (via the Menu / System Settings))
- In the System Settings go to "Mouse and Touchpad"
- Look for a "natural scrolling" or "Reverse scrolling direction" in the "Mouse" tab -- _it's not found_
- Look for a "natural scrolling" or "Reverse scrolling direction" in the "Touchpad" tab -- _it's there and affects only Touchpads, of course_

**Expected behaviour**

The _System Settings_ > _Mouse and Touchpad_ should have a general "Reverse scrolling direction", or also (a separate) one in the _Mouse_ section.

**Comment by leigh123linux** [comment]
This would have to be implemented to cinnamon-settings-daemon.

**Comment by bittner** [comment]
Thanks! See https://github.com/linuxmint/cinnamon-settings-daemon/issues/192

**Comment by robertzaccour** [comment]
Why was this closed? This is an important feature that I see no reason to not have. I would love to have "natural scrolling" for the mouse, that's the main reason I'm not currently using Cinnamon. Same for Mate. If this simple feature could be added it would be greatly appreciated. Thanks in advance.
