### ISSUE TITLE
Broken feature: Show desktop icons

### ISSUE THREAD

**Issue by djstarfox** [linuxmint/Cinnamon#6909]
```
 * Cinnamon version (cinnamon --version):  2.8.8
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...):  Centos Linux release 7.4.1708 (Core)
 * Graphics hardware *and* driver used:  Nvidia GeForce 650 Ti; Nvidia proprietary driver 384.69
 * 32 or 64 bit:  x86_64
 ```

**Issue**
Enabling "Show desktop icons" in the System Settings causes old windows to appear on screen but don't actually exist, numerous visual artifacts, and transparent selection rectangles to remain on screen. 

**Steps to reproduce**
Login to Cinnamon
Open "System Settings"
Open "Desktop"
Enable "Show desktop icons"
Use mouse to move the "System Settings" window somewhere else on screen.
A ghost window appears below in the original location of the System Settings window.  (This also happens to *ANY* application or opened window.) 

**Expected behaviour**
Moved or closed windows should not show their old location on screen.

**Other information**
Only workaround so far is to disable the setting "Show desktop icons".

**Comment by leigh123linux** [comment]
You will need to wait for me to update epel7 as there are  still some missing python requires needed for 3.4

https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2017-e7e0a85313

FYI it is an old (fixed) issue caused by gtk-3.22

https://github.com/linuxmint/Cinnamon/issues/5787
