### ISSUE TITLE
Multiple Icons after CentOS 7.4 Upgrade

### ISSUE THREAD

**Issue by taylorstrange** [linuxmint/Cinnamon#6911]
```
 * Cinnamon version (cinnamon-2.8.8-3.el7.x86_64)
 * Distribution - (CentOS 7.4)
 * Graphics hardware - Intel onboard and NVIDIA Graphicds Card
 * 64 bit
 ```

**Issue**
I upgraded from CentOS 7.3 to 7.4 earlier today.  Now when it loads Cinnamon (v2.8) it has 5 desktop icons for each file.  (5 Computer icons, 5 Trash Icons, etc...). They will go away when I highlight the icons but they come back when cinnamon is restarted.   I have tried switching to GNOME (which has no issues) and then back to cinnamon but the issue is still there.  I have also reinstalled cinnamon.  Also, closely related to the icon issue, when I draw a blue highlighting area on the desktop, the blue area stays on the screen over the desktop background rather than going away with a click.

**Steps to reproduce**
1.  Restart cinnamon or reboot.

**Other Information**
Cinnamon Packages Installed
cinnamon-translations-2.8.1-2.el7.noarch
cinnamon-settings-daemon-2.8.4-1.el7.x86_64
cinnamon-devel-doc-2.8.8-3.el7.noarch
cinnamon-menus-devel-2.8.0-2.el7.x86_64
cinnamon-menus-2.8.0-2.el7.x86_64
cinnamon-2.8.8-3.el7.x86_64
cinnamon-desktop-devel-2.8.1-1.el7.x86_64
cinnamon-control-center-2.8.0-2.el7.x86_64
cinnamon-control-center-devel-2.8.0-2.el7.x86_64
cinnamon-desktop-2.8.1-1.el7.x86_64
cinnamon-session-2.8.2-2.el7.x86_64
cinnamon-control-center-filesystem-2.8.0-2.el7.x86_64
cinnamon-applet-blueberry-1.1.15-5.el7.noarch
cinnamon-settings-daemon-devel-2.8.4-1.el7.x86_64
cinnamon-screensaver-2.8.0-4.el7.x86_64

**Comment by leigh123linux** [comment]
You will need to wait for me to update epel7 as there are  still some missing python requires needed for 3.4

https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2017-e7e0a85313

FYI it is an old (fixed) issue caused by gtk-3.22

https://github.com/linuxmint/Cinnamon/issues/5787

**Comment by mind04** [comment]
When you apply this https://github.com/linuxmint/nemo/commit/4e5a1037de0dc24e44a58e239e281b4c2d5740af.diff patch to nemo-2.8.7-1 the issue is resolved

**Comment by taylorstrange** [comment]
How do I go about applying that patch? @mind04

**Comment by mind04** [comment]
Here are rpms with the patch https://www.monshouwer.eu/download/MIND/ 
Feel free to use them if you trust my site as download location.

If you want to create your own rpms, use the source rpm for reference.
This is the nemo epel srpm + 1 file (nemo-redraw.patch) and one additional Patch line and a few changelog lines in the spec file.

Build the rpms yourself:
Download and install the epel nemo srpm, add the patch file from github, add the patch line in the spec file and build rpms.

**Comment by taylorstrange** [comment]
Seems no matter how I try when I attempt to manually patch the cinnamon nemo package it comes back with Hunk Load Errors.  Is there something I'm missing?

**Comment by magicpimple** [comment]
> Here are rpms with the patch https://www.monshouwer.eu/download/MIND/
Feel free to use them if you trust my site as download location.

I downloaded the RPMs and ran "sudo yum localinstall <PATH>/nemo-*  It fixed the issue for me.  Thanks for the link.
