### ISSUE TITLE
Version in `configure.ac`

### ISSUE THREAD

**Issue by Fjodor42** [linuxmint/Cinnamon#6916]
Seems that when v3.4.6 was tagged on August 9th, `configure.ac` was update to reflect that, but somehow that wasn't propagated to Master.

Whether this is intentional or not, I cannot say, but according to https://github.com/linuxmint/Cinnamon/blob/2bc11c8db34fef8cf2ac34370ecca6a2bf7af2ca/configure.ac#L2 , it still says 3.4.4...

**Comment by clefebvre** [comment]
That's ok, master is basically on 3.5, we don't necessarily tag unstable versions though, only when we need them.
