### ISSUE TITLE
How to restart cinnamon with command after it crash?

### ISSUE THREAD

**Issue by AlexHex7** [linuxmint/Cinnamon#6919]
```
 * Cinnamon 3.4.6
 * Distribution - (Mint 18.2.)
 * Graphics hardware *and* driver used
 * 64 bit
 ```

when it crash, we can click yes to restart it. But if I click No, then how can I restart it?
I try alr+f2 and r. But it says Error when getting information for file '/home/XXX/r': No such file or directory

And by the way, how to update cinnamon?

**Comment by clefebvre** [comment]
You can use cinnamon --replace.

Please use forums or IRC to seek help.
