### ISSUE TITLE
Can't shut down using keyboard

### ISSUE THREAD

**Issue by casper82** [linuxmint/Cinnamon#6920]
```
 * Cinnamon version: 3.4.6
 * Distribution: Mint 18.2   64 bit
 ```

**Issue**

Pressing Power key on keyboard opens Shutdown dialog box, but box is not 'active'. Pressing Enter key does nothing, and cannot switch selection with arrow keys (ie. to Restart or Hibernate etc). Only way to 'activate' box is to click on it with the mouse.

**Steps to reproduce**

**Expected behaviour**

**Other information**

Oddly, it does work properly if it's the very first thing done after startup.

Always worked on my Mint 17 Cinnamon install.

**Comment by hyperion0201** [comment]
Have you tried restart Cinnamon Desktop by logout and login again ? , I faced this problem before, but after a desktop restart or system restart, it worked. So u can try it. Good luck.

**Comment by casper82** [comment]
Thanks for your reply. I login and shut down the computer every day, but the problem has continued since my new install a week ago. It's not a big problem, if it's still an issue in December perhaps Mint 18.3 will fix it.

**Comment by leigh123linux** [comment]
File the issue against cinnamon-session.
