### ISSUE TITLE
System unlocked when resuming from suspend.

### ISSUE THREAD

**Issue by awnumar** [linuxmint/Cinnamon#6924]
```
 * Cinnamon version: Cinnamon 3.4.6
 * Distribution: Arch Linux
 * Graphics hardware: Intel Iris Plus Graphics 640
 * Intel Core i7-7560U 64-bit
 ```

**Issue**

When suspending the laptop by putting the lid down, and then resuming it, the system is unlocked.

**Steps to reproduce**

1. Put the lid down.
2. Wait.
3. Lift it again.

**Expected behaviour**

The system would be locked.

**Other information**

I'm running a Dell XPS 13 (9360), with Arch Linux installed via Antergos.

**Comment by awnumar** [comment]
Update: This is the output from `$ cinnamon-screensaver`:

```
/usr/share/cinnamon-screensaver/cinnamon-screensaver-main.py:86: Warning: g_base64_encode_step: assertion 'in != NULL' failed
  css = provider.to_string()
Cinnamon Screensaver support not found in current theme - adding some...
Trying to connect to logind...
A screensaver is already running!  Exiting...
```

**Comment by leigh123linux** [comment]
File the issue against cinnamon-screensaver.
