### ISSUE TITLE
Cinnamon 18.2 breaks down after opening some applications by wine.

### ISSUE THREAD

**Issue by VaGNaroK** [linuxmint/cinnamon#6925]
```
 Cinnamon version 3.4.6
 Linux Mint 18.2
 NVIDIA G92 [GeForce 9800 GT]
Display Server: X.Org 1.18.4 drivers: nouveau (unloaded: fbdev,vesa)
 GLX Renderer: NV92 GLX Version: 3.0 Mesa 17.3.0-devel - padoka PPA
64 bit OS System.

# Issue
Linux mint cinnamon 18.2 breaks down after opening some applications by wine. Every 2 open programs or more via wine the cinnamon appears a message asking if the user wishes to restart it.

**Comment by NikoKrause** [comment]
Which wine applications?

**Comment by VaGNaroK** [comment]
sometimes in rare cases the DE closes then I have to restart with the keys ctrl + alt + backspace, and also when I am using the fightcade emulator online game (running via wine version 2.16), I have tried other programs via wine and they work fine without closing or DE. I think it's something specific to the emulator that causes this. Sorry my bad English.

**Comment by Vahan86** [comment]
@VaGNaroK, is this still an issue for you with Cinnamon 4.2?

**Comment by VaGNaroK** [comment]
> @VaGNaroK, is this still an issue for you with Cinnamon 4.2?

no, in the latest versions of cinnamon has been fixed. now applications via wine work without breaking anything.

**Comment by Vahan86** [comment]
@icarter09, can we close the issue?
