### ISSUE TITLE
Cannot Go Fully Fullscreen With Cheese

### ISSUE THREAD

**Issue by SerafDosSantos** [linuxmint/Cinnamon#6928]
Linux Mint 18.2 Cinnamon

**Issue**

Although I select Fullscreen on Cheese, I always have the menu displayed on top. The webcam view does not display fullscreen as it should. Fullscreen works on Ubuntu 17.04.

**Steps to reproduce**

Go fullscreen through the menu.

**Expected behaviour**

To have a fullscreen view of the webcam.

**Comment by leigh123linux** [comment]
File the issue against muffin as cinnamon isn't responsible for window decoration.
