### ISSUE TITLE
Stuttering full-screen rendering on 4K Screen

### ISSUE THREAD

**Issue by RalfJung** [linuxmint/cinnamon#6935]
```
 * Cinnamon version 4.4.6
 * Distribution - Debian testing
 * Intel HD graphics P530 (Skylake GT2) with the Intel driver
 * 64 bit
 ```

**Issue**

Rendering is stuttering -- when there are full-screen animations, I can clearly see that they do not run at 60fps. This is probably due to the 4K resolution.

**Steps to reproduce**

* git clone git://ralfj.de/gltest.git
* cd gltest
* make
* ./glxtest
* Press F1 to go full-screen

**Expected behaviour**

The animation should be smooth, while it is not.

**Other information**

If I use a non-compositing window manager (I tried i3), the animation is perfectly smooth. Likewise if I change the screen resolution to 1920x1080.

4K videos on YouTube also seem fairly laggy, probably that's the same issue.

**Comment by icarter09** [comment]
@RalfJung are you still experiencing this issue?

**Comment by RalfJung** [comment]
I have stopped using Cinnamon a while ago, so I cannot tell - sorry.

**Comment by leigh123linux** [comment]
Don't expect smooth video playback @4k with a underpowered graphics card.

**Comment by RalfJung** [comment]
Well it's smooth on Windows, and without composition. So the graphics card isn't the problem...

**Comment by leigh123linux** [comment]
@RalfJung You can't compare Windoze to Linux as the drivers aen't equal!
