### ISSUE TITLE
Variable in translations

### ISSUE THREAD

**Issue by to-ba** [linuxmint/Cinnamon#6937]
**Issue**

Please add infos for variable to the translation files.
For a good translation it is often needed to know what kind of words will be shown for »%s«.
You can add infos for translators so we can see it on Launchpad.

Thanks.

https://translations.launchpad.net/linuxmint/latest/+pots/cinnamon

Example:
-This is a system %s and cannot be removed
-This %s is currently enabled
-This %s contains function calls that could potentially cause Cinnamon to crash or freeze. If you are experiencing crashes or freezing, please try removing this %s.
-You can remove individual instances by right clicking on an %s.
-Something went wrong while loading the %s %s.
-In order to view the list of available %ss you will need to download it.
-Refreshing the %s cache from the Cinnamon spices website
-Installing %s %s
-Uninstalling %s %s

**Comment by NikoKrause** [comment]
90% of those %s mean applet, desklet, extension or theme.

Those strings have to be changed though, because you can't translate them properly to other languages.

**Comment by to-ba** [comment]
@linuxmint

**Comment by NikoKrause** [comment]
Has been fixed now https://github.com/linuxmint/Cinnamon/commit/10fca757860f75250ee34cc7840a3ede62d98b61

**Comment by to-ba** [comment]
:-) nice
