### ISSUE TITLE
Cinnamon override touchpad xorg.confs & .xprofile settings

### ISSUE THREAD

**Issue by hxss** [linuxmint/Cinnamon#6941]
```
 * Cinnamon version 3.4.6
 * Distribution - Arch(4.12.13-1)
 * Graphics hardware Intel HD Graphics 515 
 * 64 bit
 ```

**Issue**
I want to enable libinput [software button areas](https://wayland.freedesktop.org/libinput/doc/latest/clickpad_softbuttons.html). This option is not available in Cinnamon touchpad settings. 

**Steps to reproduce**
So I create xorg.conf:
```
# cat /etc/X11/xorg.conf.d/10-touchpad.conf
Section "InputClass"
    Identifier "touchpad"
    MatchIsTouchpad "true"
    Driver "libinput"
        Option "ClickMethod" "buttonareas"
EndSection
```
but it did not work. Then I find out console command that can activate softbuttons instantly and add this command to my .xprofile:
```
# cat .xprofile 
xinput set-prop --type=int --format=8 'Synaptics TM2956-002' 'libinput Click Method Enabled' 1 0 &
```
but it did not work too! The last method, that take effect was to create new command in startup menu.

**Expected behaviour**
For example in xfce softbuttons enabled by default. But I can disable it by:
```
# cat /etc/X11/xorg.conf.d/10-touchpad.conf
Section "InputClass"
    Identifier "touchpad"
    MatchIsTouchpad "true"
    Driver "libinput"
        Option "ClickMethod" "none"
EndSection
```
And then enable again by:
```
# cat .xprofile 
xinput set-prop --type=int --format=8 'Synaptics TM2956-002' 'libinput Click Method Enabled' 1 0 &
```

Why Cinnamon ignore or override this settings?

**Comment by leigh123linux** [comment]
File the issue against cinnamon-settings-daemon.
