### ISSUE TITLE
[Feature Request] Possible Upstream Push of feren OS's Theme/Layout Saver/Loader

### ISSUE THREAD

**Issue by feren** [linuxmint/Cinnamon#6945]
For a while now, I've noticed how there's been a lack of such a feature as being able to Snapshot your Panel Configuration, Theme Configuration, Applets Configurations, Extensions Configurations and so on, and then be able to revert to that snapshot, so, recently, I managed to finish two bash scripts that provide a Basic UI and a BASH Script implementation of such a feature, and so far, it pretty much works.

What I'm getting to, is that, feren OS isn't as well-known as Mint, so why not give the users a feature they probably want, right on Upstream in Mint, making it more convenient to get the look they want from others, for example?

Now, you may be thinking, why? Well, KDE Plasma has such a feature in a type of file known as a "Look and Feel Pack", which provides most of these scripts' functionality, and it's proven quite successful...

Anyways, straight to the point, here's the Scripts themselves:
[Look and Feel for Cinnamon + Integration.zip](https://github.com/linuxmint/Cinnamon/files/1385627/Look.and.Feel.for.Cinnamon.Integration.zip)
Notes:
- The current Settings > Themes Edit is one-paged, so you'll have to copy the code right off of that one, to the Cinnamon Themes Window Code, for integration into your two-paged style
- Cinnamon gets restarted automatically when loading a snapshotted theme, because of how slow Cinnamon seems to be at getting used to all the changes, when not being restarted...
- You'll probably have to rename the backup folder on the scripts, as it's '~/.feren-layout-backups' on these scripts...

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
