### ISSUE TITLE
Missing sync indicators (round green when synced or blue when in progress) on folder icons in Dropbox, an on dropbox's icon in tray. 

### ISSUE THREAD

**Issue by eugenyho** [linuxmint/Cinnamon#6957]
```
 * Cinnamon version 3.4.6
 * Distribution - 18.2
*  intell e3-1200 v2/3rd gen core graphic controller
 * 64 bit
 ```

Missing sync indicators (round green when synced or blue when in progress) on folder icons in Dropbox, an on dropbox's icon in tray. 

Just fresh install

Dropbox icon in tray and folders icons must have small indicators in right bottom corner to indicate sync status.

When some changes was made only dropbox's icon in tray appear blue indicator, but after sync, no green round indicator is not appear. On dropbox's folders icon, nothing happened.

**Comment by leigh123linux** [comment]
Cinnamon or nemo code isn't responsible for this issue, nemo-dropbox provides the dropbox binary downloader program only.
As the tray icon and related code is provided by the downloaded code there is nothing we can do to fix it.

You will need to report the issue to dropbox.com

**Comment by leigh123linux** [comment]
It looks like dropbox removed the green indicator from the idle status icon.

```
~/.dropbox-dist/dropbox-lnx.x86_64-37.4.29/images/hicolor/16x16/status/dropboxstatus-idle.png 
```

**Comment by eugenyho** [comment]
Dear Scott

Yes, seems to be dropbox removed the green indicator from the idle status icon.
And about indicator at dropbox's folders. 
I installed an additional nemo-dropbox via apt-get and after the reboot the indicators appeared!
