### ISSUE TITLE
When removing disks using the "removable-drives" module, the removal notification is not displayed.

### ISSUE THREAD

**Issue by VAVUS7** [linuxmint/Cinnamon#6959]
```
 * Cinnamon version - 3.4.6
 * Distribution - Mint 18.2
 * 64 bit
 ```

**Issue**
When removing disks using the "removable-drives" module, the removal notification is not displayed.

**Comment by NikoKrause** [comment]
This info could be added here: https://github.com/linuxmint/Cinnamon/issues/5377
