### ISSUE TITLE
Cinnamon 2017-1025040019-xenial triggers uninstall of Cinnamon

### ISSUE THREAD

**Issue by dm2912** [linuxmint/Cinnamon#6961]
```
 * Cinnamon version (cinnamon --version) 3.6.0 Nightly
 * Distribution - Mint 18.2
 * 64b
 ```
**Issue**

Cinnamon 3.6.0 - 20171025040019-xenial is triggering uninstall of cinnamon

![screenshot from 2017-10-25 22-01-58](https://user-images.githubusercontent.com/25871666/32023095-331950ae-b9d0-11e7-9e6a-f42b135c8cea.png)

**Comment by dm2912** [comment]
Oh, if you let it roll it uninstalls Cinnamon.

Cinnamon then cant be reinstalled via Synaptic because of dependency issue (nemo 3.4.7 installed and it wants nemo 3.6)

**Comment by jaszhix** [comment]
You might want to install a fallback DE, like Mate. Run `sudo apt-get install -f`. If its just wanting to uninstall Cinnamon, press Y. Install xapps, then nemo, and then try installing Cinnamon and the rest of its packages, in that order. I was building from source though, so YMMV with the nightly PPA.

**Comment by dm2912** [comment]
Yeh, I installed XFCE and disabled auto-login prior to clicking yes. (and made a timeshift restore point)

Once Cinnamon went it flatly refused to reinstall Cinnamon via synaptic or via terminal. Nemo 3.4.7 Sonya is installed but weirdly it was insisting on Nemo 3.6 to install Cinnamon.

**Comment by jaszhix** [comment]
You need to specify the Nemo version so it installs it from the PPA. The dependencies changed for the 3.6 build process, and it may not be reflected in the nightly PPA yet.

```sudo apt-get install nemo=3.6.2```

Maybe @glebihan knows more.

**Comment by dm2912** [comment]
I've managed to solve it. Turns out it was simpler than that.

switched software sources mirror to default packages.linuxmint from the "local mirror" that it had recommended.

that triggered the cinnamon nightly from gwendal's ppa to add nemo, nemo data and cinnamon-common to its install instead of "remove cinnamon"
