### ISSUE TITLE
mintUpdate unusable

### ISSUE THREAD

**Issue by Corto-landese** [linuxmint/Cinnamon#6962]
```
 * Cinnamon version (3.4.6)
 * Linux-Mint 18.2
 * Intel skylake integrated graphic
 * 64 bit
 * kernel 4.8.0-53 generic
 ```

**Issue**
MintUpdate says 'impossible to read list of updates' and the terminal is no more accessible (so it's no more possible to type commands)

**Steps to reproduce**
Change '**French, France UTF-8**' to '**French (@euro), France**' and restart

**Expected behaviour**
normal behaviour

**Other information**
reset to '**French, France UTF-8**' (and restart) solve the problem

tested on 2 different PCs (desktop [Vorke V2] and laptop [Sony VAIO])

**Comment by feren** [comment]
Wrong Repo.
