### ISSUE TITLE
RGB colors across wake from suspend

### ISSUE THREAD

**Issue by raidermax** [linuxmint/Cinnamon#6963]
```
 * Cinnamon 3.4.6
 * Distribution - Mint 17.2
 * AMD 6570 mesa driver
 * 64bit
 ```

**Issue**
Upon resume from suspend, around 3/5 times the entire screen/Cinnamon DE is in some weird contrast mode where everything is pink/blue and hard to read.

**Steps to reproduce**
Not sure, happens occasionally when resuming from suspend mode. Must be something with my video hardware. If I log out and log back in the weird colors no longer appear.

**Expected behaviour**
The screen should not look like all weird like this. Please take a look below at the screenshots. Interestingly, when the issue occurs and I use the Prnt Scrn button to take a screenshot in Cinnamon, the screenshot does not have these weird effects.

**Other information**
https://i.imgur.com/q5g4LEV.jpg (please not I took this with a camera but the weird colors you see are from cinnamon and NOT the camera).
dmesg output: https://pastebin.com/tRwmTM1P

**Comment by leigh123linux** [comment]
Looks like a mesa driver issue.
