### ISSUE TITLE
Unable to tether via USB

### ISSUE THREAD

**Issue by joaoherberto** [linuxmint/Cinnamon#6966]
```
 * Cinnamon version 3.4.6
 * Distribution - Manjaro - Kernel 4.9.58-1-Manjaro
 * Graphics hardware nVIdia GeForce GTX 970 with nVidia Driver
 * 64 bit
 ```

**Issue**
USB Tethering fails after a minute of use because Modem Manager kicks in.

**Steps to reproduce**
Plug in Android phone, enable USB Tethering. After a minute or less, the network switches from USB Ethernet to Mobile Broadband, but internet is lost. THis is because the phone does all of the Authentication, but because ModemManager is on, it switches as if there was a SIM card to enable and configure

**Expected behaviour**
USB Tethering should remain on all of the time. 

**Other information**
In order for USB tethering to work, had to disable the service using systemctl. See link https://forum.manjaro.org/t/cinnamon-desktop-usb-tethering/33597

In my humble opinion, there should be an On/Off toggle for this feature.

**Comment by leigh123linux** [comment]
Try reporting the issue against networkmanager!
