### ISSUE TITLE
[Feature Request] Desktop Zoom Lens mode Lens shape toggle ability

### ISSUE THREAD

**Issue by Leon-Davison** [linuxmint/cinnamon#6967]
Accessibility - Visual - Desktop Zoom Lens mode Lens shape.

Requesting a feature to toggle between the Lens mode choices of Horizontal/Vertical Strip and Square shape using a similar keyboard modifier button and mouse combination.

With Desktop Zoom enabled. We use a modifier button (Disabled, Alt, Super, Control) and the mouse wheel to control Magnification levels. 

The remaining modifier buttons we have left to choose from, I would like them to switch between the different types of Lens shapes available. So change Mouse wheel modifier to Mouse wheel zoom modifier and create another Mouse wheel lens modifier that gives us this toggle ability.

I find Horizontal strip is excellent for reading long lines of text that stretch across the page but for smaller parts of a screen, like maybe UI actions (buttons, menus, file icons, etc) or where more direct precision is needed that the Square shape lens would be better to use and quicker to do the task.

Hopefully others will find this feature useful. 

Thank you.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
