### ISSUE TITLE
[3.6] cinnamon-settings: themes doesn't function if ~/.themes/ isn't present

### ISSUE THREAD

**Issue by leigh123linux** [linuxmint/Cinnamon#6972]
```
 * Cinnamon version = 3.6.0
 * Distribution - Fedora 28
 * Graphics hardware *and* driver used

Graphics:  Card: NVIDIA GK106 [GeForce GTX 660]
           Display Server: x11 (X.org 119.5 )
           drivers: nvidia (unloaded: modesetting,fbdev,vesa,nouveau)
           Resolution: 3840x2160@60.00hz
           OpenGL: renderer: GeForce GTX 660/PCIe/SSE2
           version: 4.5.0 NVIDIA 387.22

 * 64 bit
 ```

**Issue**

cinnamon-settings theme fails to run if ~/.themes/ isn't present

```
Loading Themes module
Traceback (most recent call last):
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 553, in button_press
    self.side_view_nav(widget, None, category)
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 114, in side_view_nav
    self.go_to_sidepage(cat, filtered_path)
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 128, in go_to_sidepage
    sidePage.build()
  File "/usr/share/cinnamon/cinnamon-settings/bin/SettingsWidgets.py", line 123, in build
    self.module.on_module_selected()
  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_themes.py", line 31, in on_module_selected
    self.spices = Spice_Harvester('theme', self.window)
  File "/usr/share/cinnamon/cinnamon-settings/bin/Spices.py", line 163, in __init__
    self._load_metadata()
  File "/usr/share/cinnamon/cinnamon-settings/bin/Spices.py", line 371, in _load_metadata
    extensions = os.listdir(directory)
OSError: [Errno 2] No such file or directory: '/home/leigh/.themes/'
```

creating ~/.themes/ fixes the issue

**Steps to reproduce**

1. rm -rf ~/.themes/
2. cinnamon-settings themes
3. crash

**Expected behaviour**

It shouldn't fail if ~/.themes/ isn't present

**Other information**

Life sucks.

**Comment by shawnfromnh1** [comment]
Well the themes folder is present and my cinnamon desktop in Suse and Antergos both do NOT have  working theme setting when the button is clicked. This is an active problem and needs a patch. You can easily verify it by installing the new cinnamon in anything but mint, Antergos is a quick install to try it out on. I opened the theme folder in etc/share/theme and all the themes were present in their folders so someone missed something during the upgrade or it may be a part in gnome that was upgraded that is causing the problem.

**Comment by NikoKrause** [comment]
What's the output, when you try to open cinnamon-settings in the terminal?

**Comment by JosephMcc** [comment]
This should have been fixed by https://github.com/linuxmint/Cinnamon/commit/60faa201c48a183a2f0630897a65d45ff6662f13#diff-bf163328c4714f377ee4f92191154ccc
