### ISSUE TITLE
Desktop icons huge after lock screen

### ISSUE THREAD

**Issue by Redsandro** [linuxmint/Cinnamon#6973]
* Cinnamon version `3.0.7`
 * Distribution - `Linux Mint 18 Sarah x64`
 * GPU - `GeForce GTX 970`
 * GPU Driver - `nVidia driver 384.66`
 * Monitor - `DELL UP2414Q` 2 x 1920x2160 [MFT](https://en.wikipedia.org/wiki/DisplayPort#Multi-Stream_Transport) (3840 x 4320)

**Issue**

Icons quadruple in size on a UHD HighRes Monitor when unlocking the screen.

![image](https://user-images.githubusercontent.com/1702193/32365273-7ba7d750-c079-11e7-8806-90b4c102135e.png)

**Steps to reproduce**

Icons are of a normal size on a fresh reboot.
Lock screen.
Unlock the next day.
Observe desktop icons quadrupled in size.

**Expected behaviour**

No changes in size

**Other information**

It feels like this isn't 100% guaranteed to happen; sometimes it doesn't when I unlock the screen directly. I have the feeling it happens often when I unlock the screen the next day. That means that I haven't fully understood the cause.

**Comment by leigh123linux** [comment]
1. nemo draws the desktop icons so your issue is misfiled.
2. cinnamon-3.0.x is EOL

**Comment by Redsandro** [comment]
@leigh123linux Thanks for clarifying. I guessed I confused the Ubuntu part (LTS) with Linux Mint (No LTS).
