### ISSUE TITLE
[MultiMonitor] Application windows rendered on secondary powered-off monitor

### ISSUE THREAD

**Issue by hackix** [linuxmint/Cinnamon#6974]
```
 * Cinnamon version (Cinnamon 3.2.7-4)
 * Distribution - (Debian 9)
 * AMD HD7990 + radeonsi / xserver-xorg-video-radeon 1:7.8.0-1+b1
 * libdrm-radeon1 2.4.74-1
 * 64 bit
 ```
**Issue**
Cinnamon seems not to handle powered-off monitors as expected in a dual-screen setup, when both are set 'active' in the settings.

**Steps to reproduce**
At least when previously shut down the system with application windows on the secondary monitor, those will start up and render on this monitor if set to 'active' in the settings menu, even if it is powered off, so one has to either power it on or use the "move to other screen" option on the task bar on the main screen.

**Expected behaviour**
When opening an application, it should render on the main monitor, along with other applications, if the secondary (or third, or lower) monitor is powered off, on which it would normally be rendered, if it was powered-on. 

Or, alternatively, it should render on the next lower-ranked, currently powered-on monitor - either monitor 1, then 2 and so on, in case the main monitor is powered-off.
Maybe a settings option, on which next-lower monitor - the first, or the largest availible - an application should be rendered in such cases, should be considered, too.

Nevertheless, the original application windows position settings should be restored and applied, as soon as the respective shut-off monitor(s) power-up again, if set to 'active' in the settings. 

This behavior should work fluently forth and backwards, to provide a high quality user experience and productivity in multi-monitor environments.

**Other information**

**Comment by leigh123linux** [comment]
Try cinnamon-3.6.x as the version your using is EOL.

**Comment by hackix** [comment]
Well, I'm using stable here, and that's what it's shipped with. I don't want to mess around with the guts of Debian - too much. Unless it's absolutely inevitable.

Apart from this, I've also made a few suggestions, which maybe have not been stated so far, and which go beyond simple bug fixing. 

Those might be worth consideration nonetheless...
