### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by akadark** [linuxmint/Cinnamon#6975]
```
 * Cinnamon version (cinnamon 64 bit version)
 * Distribution - (Mint 18.2)
 * Graphics hardware: HD Graphics 530, GTX 960M
 driver used: nvidumdx.dll 22.21.13.8205
 * 64 bit
 ```

**Issue**
installation freezes at the first page which has 'M' symbol and five dots. It moved at the first time but it will halt soon. But I can see next pages and use Mint with compatibility mode.

**Other information**
I think it is a Nvidia's graphics driver problem but I don't know how to fix it.

**Comment by leigh123linux** [comment]
Sorry this is a cinnamon issue.
