### ISSUE TITLE
system wide network  proxy

### ISSUE THREAD

**Issue by heiducteam** [linuxmint/cinnamon#6979]
```
 * Cinnamon version (cinnamon --3.4.6)
 * Distribution - (lmde2)
 * Graphics hardware *and* driver used
 * 64 bit
 ```

**Issue**

system wide network  proxy( manual or auto) isn't work, it's never been fine.

**Steps to reproduce**

**Expected behaviour**

**Other information**

**Comment by obliviateandsurrender** [comment]
@heiducteam  Hey, I remember it is not possible to change proxy in Mint from setting so I created a script for it. 
[Proxy Script](https://github.com/obliviateandsurrender/Proxy-Script-For-Linux-Mint-)
Lemme know if you face any problem with it.

**Comment by Vahan86** [comment]
@heiducteam, is this still an issue in Cinnamon 4.2?

**Comment by Vahan86** [comment]
@icarter09, can we close the issue since there is no response from OP?
