### ISSUE TITLE
empty blue screen after auto screen lock and twin view

### ISSUE THREAD

**Issue by daschuer** [linuxmint/Cinnamon#698]
I have cinnamon 1.4.0-UP3-0ubuntu1~recise1 running on a twin view setup with nvidia 295.40 driver on a DELL Latitude E6510

After automatic screen lock the main display becomes blue and the second display black. 
Moving the mouse, the mouse pointer appers on the blue main display and the second display shows the gnome-screensaver. I cannot enter the second display with the mouse. 
Typing the password and unlock is possible but without visual feedback. 

Sometimes i can manage to move the focus from the blue screen to the second screen.  Than the Unlock dialog appears. 

Manual lock gnome-screensaver-command -l works as desired. both displays are displaying the  gnome-screensaver
The unlock dialog is displayed on the focused screen.  It is also not possible to enter the other screen. 

Unity does not suffer this problem. I notice that the gnome-screensaver is only displayed on the focused display. the other display is entirely black. 

Maybe this bug depends on this issue
https://bugs.launchpad.net/ubuntu/+source/gnome-screensaver/+bug/71030

**Comment by eamonnkenny** [comment]
I can find the login window in the blue screen by moving my cursor to the middle of my left screen. The cursor changes from an arrow to a long capital I shape indicating that I'm in the password insertion box. Then I type my password and I'm in, but this is ridiculous. Also the proportion of my left screen covered in blue is equal to the size of the right screen. The blue screen is overlaid as a colour over the login prompt, its not that the login prompt isn't on top and isn't there. The login prompt is there and is usable, its just invisible (almost, except for the cursor). I'm using Debian 7 Wheezy and its been a problem for some time now.

**Comment by ManIVIctorious** [comment]
@eamonnkenny This Bug has been closed more than a year ago, if you experience similar behaviour chances are high, that it is caused by an absolute different problem, so please file a new bugreport.

Before that you should check if you are using the latest cinnamon version (2.6.13 at time of writing) and if not upgrade and check if the issue still persists
