### ISSUE TITLE
App grouping in windows list

### ISSUE THREAD

**Issue by gc-group** [linuxmint/Cinnamon#6980]
```
 * Cinnamon version 6.0.2 (it's for all versions of cinnamon)
 * Distribution - linux mint 18.2
 * Graphics hardware - Intel 2nd Generation Core Processor Family Integrated Graphics Controller 
 64 bit
 ```

**Issue**
Sometimes I use the same application in multiple Windows. I would like to display them in one button. This will help to save space on the panel and will look quite modern. It is about cinnamon

**Steps to reproduce**

Add to panel app grouping. (You can see it in KDE)

**Expected behaviour**

When a person imposes (pushes) on the program button on the panel to open a menu with thumbnails of the Windows. In one button you should see thumbnails of all open Windows in the program..

**Other information**

**Comment by JosephMcc** [comment]
We've already had tons of requests for this: https://github.com/linuxmint/Cinnamon/issues/67
A search will turn up plenty.

**Comment by gc-group** [comment]
I read this article and wish to inform you that I requested data for cinnamon. There is no such function
