### ISSUE TITLE
Wallpaper picker does not indicate the selected wallpaper

### ISSUE THREAD

**Issue by ghost** [linuxmint/cinnamon#6981]
```
Cinnamon 3.4.6
Mint 18.2
64-bit
 ```

**Issue**

The wallpaper picker window(s) does not indicate the currently selected file, which (i) is slightly counter-intuitive and (ii) can make tracking done problems such as the one I report [here](https://github.com/linuxmint/slick-greeter/issues/).

**Steps to reproduce**

Open the wallpaper picker via right-clicking desktop or via System Settings.

**Expected behaviour**

The currently selected file should be marked clearly.

**Other information**

I apologise if I file this report in the wrong place; it can be hard to find the right place.

Screenshot - which we might entitle, 'Find your current wallpaper!'
![image](https://user-images.githubusercontent.com/9998846/32409214-7ed61294-c19f-11e7-8dec-223398c1a941.png)

**Comment by LinuxOnTheDesktop** [comment]
>  JosephMcc added the NEEDS IMPROVEMENT label on 24 Nov 2017

Any chance of getting the improvement, please? (I would try to do it myself but my programming ability is nowhere near up to the job.)
