### ISSUE TITLE
Per-program window manager UI?

### ISSUE THREAD

**Issue by echuber2** [linuxmint/Cinnamon#6982]
Sorry, this isn't an issue so much as a feature inquiry. Is it possible to override the window manager (muffin?) per-program? For example, is it possible to design custom window chrome or otherwise hide it? My use case would be, suppose I want to design a custom GTK theme to go with a particular program like the Adaptive theme for Sublime Text.

**Comment by mtwebster** [comment]
You can override the GTK (controls) theme by providing an environment variable at launch time:

```
$ GTK_THEME="My Theme Name" <program>
```
Unfortunately there's no such facility for temporarily overriding the icon or window border theme, though it looks as though you can provide a `gtk-3.0/settings.ini` file in your gtk theme folder that would allow further customizing (including the setting a desired icon theme)

Unfortunately there's no way to override what muffin does to normal windows, or how it decorates them.

**Comment by echuber2** [comment]
Thanks, I may be able to do something with this.
