### ISSUE TITLE
GUI - feature request: notification when low on RAM

### ISSUE THREAD

**Issue by cmrdt** [linuxmint/Cinnamon#6983]
```
Cinnamon 3.4.6
Mint 18.2
64 bit
```

**Issue**
similar to how a notification popups  when a drive is running low on free-disc-space,
offer to close/restart program or alert 
  when a program is leaking huge amounts of ram
with optional whitelisting (permanently or for session only, esp if occurs frequently ,?view history)

and instead of only saying it's low on ram list the programs that are using alot of ram and offer to e..g poll its ram usage e.g. once every minute to debug memory leaks (to graph long-term ram usage trends)

**Comment by leigh123linux** [comment]
-1

Having a low RAM warning would be useless, Linux is designed to use all available RAM and free it when needed.

**Comment by cmrdt** [comment]
there's also the problem of multi-process apps e.g. web-browsers e.g. firefox/chromium, which complicates calculating ram usage

other than ram usage also what about program(s) using too much 
- CPU-time in a given period
- network bandwidth over time
- file I/O load writes (risk damaging SSDs)
- file I/O load read/writes (for slower HDD, debug slowness)


- use training to find typical usage to flag anomalities?

examples of programs that have used too much ram before
>5GB
- cinnamon, mdm, firefox, chromium, nemo, caribou(anomaly), gcc-programs
>1GB
- vlc(esp multiple instances where process remains but window closed, thus invisible without a task manager  thus not letting go of ram)

for computers without a SSD thus page-file uses a slower spinningHDD
when ram runs-out, the computer undergoes [thrashing](https://en.wikipedia.org/wiki/Thrashing_(computer_science))
a unpleasant experience where it almost completely looses responsiveness 
it would be better to avoid and prevent it before it happens

w7 does warn you when ram is low, but linux in extreme cases does (instead of BSOD, logs you out automatically ?MDM crash?)

whether to replace gnome-system-manager with better alternative
- maybe use of color/syntax-highlighting
- window-management(right-click program, select/view windows it uses, maximize/switch-to)
- set-auto-kill/restart/suspend-when-uses-too-much-resources
- using ideas from[kde's system monitor](https://www.kde.org/applications/system/ksysguard/) [process hacker](http://processhacker.sourceforge.net/) or [process explorer](https://technet.microsoft.com/en-us/sysinternals/bb896653.aspx), note they also show i/o basic graphs (no distinguish contiguous vs random)
