### ISSUE TITLE
Network-manager applet spams .xsession-errors heavily

### ISSUE THREAD

**Issue by cmrdt** [linuxmint/Cinnamon#6991]
```
Cinnamon 3.4.6
Mint 18.2 64-bit
intel graphics
64 bit
 ```

**Issue**

.xsession-errors very often filled with (this time ~4.6MB grep output)

`(nm-applet:2590): Gtk-CRITICAL **`     **×23877**
`(nm-applet:2590): Gtk-CRITICAL **: gtk_widget_destroy: assertion 'GTK_IS_WIDGET (widget)' failed`     **×23876**
`(nm-applet:2590): Gtk-WARNING **: Can't set a parent on widget which has a parent`     **×11940**
`(nm-applet:2590): nm-applet-CRITICAL **: get_menu_item_for_ap: assertion 'dup_data.hash != NULL' failed`     **×11658**
`(nm-applet:2590): Gtk-WARNING **: Theme parsing error: unity.css:49:10: 'start' is not a valid property name`     **×18**
```
(nm-applet:2590): Gtk-CRITIGtk-Message: (for origin information, set GTK_DEBUG): failed to retrieve property `GtkRange::activate-slider' of type `gboolean' from rc file value "((GString*) 0x7fe2d8887760)" of type `GString'
```
 **×1**
`(nm-applet:2590): Gtk-WARNING **: Can't set a pare`     **×1**
`(nm-applet:2590): Gtk-WARNING **: Can't set a parent on widget w`     **×1**

the last 3 above are malformed outliers, don't know why , are low memory events one of the possible causes?

---

![screenshot from 2017-11-06 18-37-35](https://user-images.githubusercontent.com/24411108/32469719-f2915f08-c321-11e7-9516-9c4029811333.png)
![screenshot from 2017-11-06 18-37-49](https://user-images.githubusercontent.com/24411108/32469720-f2cc9884-c321-11e7-9d16-1c71d0c898f8.png)
![screenshot from 2017-11-06 18-47-12](https://user-images.githubusercontent.com/24411108/32469943-0ee8e544-c323-11e7-8bca-b8adcec15983.png)

**Comment by leigh123linux** [comment]
nm-applet isn't part of cinnamon.

**Comment by cmrdt** [comment]
then where do i report because

![search_ _org_linuxmint_nm-applet_-_2017-11-07_16 44 36](https://user-images.githubusercontent.com/24411108/32505877-21e88c68-c3db-11e7-9186-a3940629acec.png)

**Comment by leigh123linux** [comment]
Look on launchpad for network-manager-applet

https://launchpad.net/ubuntu/+source/network-manager-applet/+bugs
