### ISSUE TITLE
Add a menu option on mounted devices to remount as R.O. / R/W label:"FEATURE REQUEST"

### ISSUE THREAD

**Issue by sverx** [linuxmint/Cinnamon#6996]
This is a feature request.

I love how Cinnamon makes external USB drives appear as icons on my desktop - said that, I'm wondering if it's possible to add a menu option on them such as "Remount R.O." when they're R/W and "Remount R/W" when they're R.O. - and if it could remember the setting across sessions would be pure gold.

I've seen it's a feature that would be helpful to many, at least all those who've been searching a solution (like me recently) to the problem of having an external backup disk (for pictures, for instance!) that you want to mount but being sure that you're not actually changing anything in there in any case.

As a workaround, I have added a line in my /etc/fstab
`UUID=0123456789ABCDEF /media/Maxtor_ro ntfs defaults,noauto,user,ro 0 0`
which works perfectly... but when I need instead to backup new pictures there, which happens once in a while, I have to comment that line - not a lot of work of course but that's something I can't ask anyone else in the house to do ;)

Hopefully other people here can see how this feature can be useful and 'upvote' it...

Thanks! You're doing a great work - thanks for making Cinnamon wonderful! :)

**Comment by leigh123linux** [comment]
Can you file the issue against nemo instead please.

**Comment by sverx** [comment]
Sure! Thanks!
