### ISSUE TITLE
cinnamon-settings-daemon/csd-keyboard process uses huge amount of RAM on every startup

### ISSUE THREAD

**Issue by brpaz** [linuxmint/Cinnamon#6997]
```
 * Cinnamon version 3.4.6
 * Distribution - Mint 18.3
 * Graphics hardware *and* driver used: nouveau
 * 64 bit
 ```

**Issue**

Hello.
Everytime I start my PC, the csd-keyboard process starts using lots of RAM in a very short time. I always have to kill the process manually and then it goes to normal. In extreme cases I found it using 15 GB Ram!!!

**Comment by leigh123linux** [comment]
File the issue against cinnamon-settings-daemon.
