### ISSUE TITLE
CSD-enabled apps unaffected by "action on title bar" setting

### ISSUE THREAD

**Issue by FistfulOfStars** [linuxmint/Cinnamon#6998]
```
 * Cinnamon 3.4.6
 * Mint 18.2 64-bit
 ```
**Issue**
Apps that use client-side decorations such as gnome-calculator and gedit don't respond to "action on title bar" settings in the "Windows" setting panel.

For example I have middle-click set to toggle always on top and scroll wheel set to adjust opacity. This works well with apps that don't use CSD but for apps that do it doesn't work.

**Steps to reproduce**
Set middle click and scroll wheel to most available settings in the "Windows" setting panel.

Test first on non-CSD application, then on app with CSD's enabled.

**Expected behaviour**
Actions should work on both CSD and non-CSD apps.

**Other information**
Apps with CSD always respond to double-click by maximizing, and right click always shows menu on CSD apps, regardless of setting.

**Comment by itzexor** [comment]
I don't know that there is a way to do this because, as the name suggests, the client (the application itself, or the toolkit it was built on) handles the titlebar. For normal server-side decorations the frame and title bar is created by the window manager.

**Comment by FistfulOfStars** [comment]
You would likely know better than I.

The only thing I'd add is that all of the same actions are still functional and available via the right clicking on the CSD title bar, so it would appear that the functionality is accessible somehow.

Regardless, it's unfortunate as this is one of my favorite features of Cinnamon.

**Comment by clefebvre** [comment]
https://github.com/linuxmint/cinnamon-settings-daemon/commit/fa55de663cac569099327bd236a3a1dc64aee1e5

**Comment by FistfulOfStars** [comment]
Much appreciated Clem.
