### ISSUE TITLE
Can't change window state with Wnck

### ISSUE THREAD

**Issue by gfreeau** [linuxmint/Cinnamon#700]
Using wnck with python, I was unable to change a window's state that has been maximized vertically. For example in cinnamon when you click and drag a window to the left or right, it snaps to 50% of the screen size.

Docs for reference: http://developer.gnome.org/libwnck/stable/WnckWindow.html

Using wnck_window_get_state, it shows that the state has changed WNCK_WINDOW_STATE_MAXIMIZED_VERTICALLY, wnck_window_is_maximized_vertically also returns true.

However calling wnck_window_unmaximize_vertically does not change the window state back to the default.

I think that https://github.com/paulswartz/gnome-shell-grid would be a great addition to cinnamon in future versions, a compiz like grid plugin is extremely useful, however once you snap a window with the mouse to the left or right, you are unable to use the keyboard bindings to move the windows. You can regain control by manually moving the window off the left or right slightly - this changes the state somehow (this must be in the cinnamon or gnome-shell code somewhere).

The following python code in the interpreter does not change the window state.

```bash
>>> import wnck
>>> screen = wnck.screen_get_default()
>>> w = screen.get_active_window()
>>> w.get_state()
<flags 0 of type WnckWindowState>
```

Then drag the terminal window to the right or left and snap it.

```bash
>>> w.get_state()
<flags WNCK_WINDOW_STATE_MAXIMIZED_VERTICALLY of type WnckWindowState>
>>> w.is_maximized_vertically()
True
>>> w.unmaximize_vertically()
>>> w.is_maximized_vertically()
True
>>> w.get_state()
<flags WNCK_WINDOW_STATE_MAXIMIZED_VERTICALLY of type WnckWindowState>
```

The state won't change. It will only change when you drag it off the snap.

This only affects the left and right snap, it does not affect maximized windows in cinnamon.

I'll also add that if you maximize the window vertically in python yourself using w.maximize_vertically(), without dragging and snapping with cinnamon, it works properly. So this issue seems to be in cinnamon or gnome-shell.

The issue is here: https://github.com/paulswartz/gnome-shell-grid/issues/6

There is an unmaximize decorator in the code that checks if the window is_maximized and applies unmaximize, but again this not affect windows snapped in cinnamon.

**Comment by Vahan86** [comment]
@JosephMcc, can we close the issue since there is no response from OP for a long time?
