### ISSUE TITLE
issue with overview mod

### ISSUE THREAD

**Issue by Hilyxx** [linuxmint/cinnamon#7002]
![image](https://user-images.githubusercontent.com/21991448/32611715-a0b66678-c566-11e7-9b02-92c0fca160db.png)

Cinnamon version (3.4.6)
 Distribution - (Mint 18.2)
 64 bit
 ```

**Issue**

In overview mod all unmaximize windows have an ugly black frame. 
Tested with GTK3 CSD applications (e.g nautilus) and vanilla applications ( cinnamon settings, nemo, xed....)

This issue is not a theme bug (tested with different themes)

**Comment by icarter09** [comment]
@Hilyxx are you still experiencing this issue?
