### ISSUE TITLE
Unexplained exclamation mark in power management applet

### ISSUE THREAD

**Issue by CottonEaster** [linuxmint/Cinnamon#7003]
```
 * Cinnamon version (cinnamon --version) 3.4.6
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 18.2
 * Graphics hardware *and* driver used:  Intel Corporation Mobile GM965/GL960 Integrated Graphics Controller (primary) (rev 0c); 2.1 Mesa 17.0.7

 * 32 or 64 bit: 64
 ```

**Issue**

Please see image inserted below.

![image](https://user-images.githubusercontent.com/9998846/32635753-740cc50c-c5a9-11e7-8a99-3cc63f28d527.png)

**Steps to reproduce**

I don't know. Nemo had hung - and put the following image in the panel - whilst copying a file from router-attached storage to a local drive.

![image](https://user-images.githubusercontent.com/9998846/32635782-9a921524-c5a9-11e7-8f0c-3f93823d8f8c.png)

Perhaps that had something to do with it.

**Expected behaviour**

I expected no exclamation mark - or at least some explanation of it.

**Other information**

 Kernel: 4.13.12-041312-generic

**Comment by mtwebster** [comment]
Try hovering on it for an explanation.

**Comment by CottonEaster** [comment]
Oh sorry: I didn't think of that, though I did have my pointer all over the applet - or so I thought.
