### ISSUE TITLE
cinnamon-settings-users all groups are listed twice

### ISSUE THREAD

**Issue by cronolio** [linuxmint/cinnamon#7005]
```
 * Cinnamon version (cinnamon --version)
Cinnamon 3.6.1
 * Distribution - (gentoo)
 * Graphics hardware *and* driver used
01:00.0 VGA compatible controller: NVIDIA Corporation GM107 [GeForce GTX 750 Ti] (rev a2)
	Subsystem: ASUSTeK Computer Inc. GM107 [GeForce GTX 750 Ti]
	Kernel driver in use: nvidia
	Kernel modules: nvidia_drm, nvidia
 * 32 or 64 bit
mix of

**Issue**
i'm have found that's in cinnamon 3.6.1 cinnamon-settings-users is shown groups twice. like "adm adm" 


**Steps to reproduce**
run "cinnamon-settings-users"
put password
click at user or go to groups tab
all groups are listed twice

**Expected behaviour**
all groups are listed once


**Other information**

**Comment by cronolio** [comment]
works for me without compat entries in /etc/nsswitch.conf
for example
passwd:      compat files
shadow:      compat files
group:       compat files
should be
passwd:      files
shadow:      files
group:        files

see also https://bugs.gentoo.org/627338

**Comment by JosephMcc** [comment]
I'm not seeing this in Mint.

**Comment by Vahan86** [comment]
@cronolio, is this still an issue in Cinnamon 4.4?

**Comment by cronolio** [comment]
> @cronolio, is this still an issue in Cinnamon 4.4?

currently my system is debian 10 with cinnamon 3.8.8. no problem with this here

**Comment by Vahan86** [comment]
@cronolio, thanks for the update.
@leigh123linux, @icarter09, can we close this issue?
