### ISSUE TITLE
fork mate main menu for Cinnamon (applications-places-system)

### ISSUE THREAD

**Issue by freemangilgamesh** [linuxmint/Cinnamon#7007]
<a href='https://postimg.org/image/3y4j2a4ol/' target='_blank'><img src='https://s18.postimg.org/3y4j2a4ol/app-menu-in-mate.png' border='0' alt='app-menu-in-mate'/></a>

**Comment by leigh123linux** [comment]
We already have a menu but your free to do whatever you like as a spice applet,
