### ISSUE TITLE
calendar@cinnamon.org crashes,  this.clock.set_format_string is not a function

### ISSUE THREAD

**Issue by nick-s-b** [linuxmint/Cinnamon#7009]
```
 * Cinnamon version (cinnamon --version)
Cinnamon 3.6.2

 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
Arch

 * Graphics hardware *and* driver used
Nvidia 387.22

 * 32 or 64 bit
64bit
 ```

**Issue**
After I updated my install today., I was greeted with that Cinnamon warning telling me some applets crashed. After looking at glass.log, I noticed that the default calendar/clock applet doesn't work anymore.

**Steps to reproduce**
Install new cinnamon. 

**Expected behaviour**
Show me the clock :)

**Other information**

error t=2017-11-12T19:02:48.297Z this.clock.set_format_string is not a function
trace t=2017-11-12T19:02:48.297Z 
<----------------
MyApplet.prototype._updateFormatString@/usr/share/cinnamon/applets/calendar@cinnamon.org/applet.js:125:13
MyApplet.prototype._onSettingsChanged@/usr/share/cinnamon/applets/calendar@cinnamon.org/applet.js:101:9
MyApplet.prototype.on_applet_added_to_panel@/usr/share/cinnamon/applets/calendar@cinnamon.org/applet.js:147:9
Applet.prototype.on_applet_added_to_panel_internal@/usr/share/cinnamon/js/ui/applet.js:360:9
addAppletToPanels@/usr/share/cinnamon/js/ui/appletManager.js:345:9
finishExtensionLoad@/usr/share/cinnamon/js/ui/appletManager.js:60:18
loadExtension@/usr/share/cinnamon/js/ui/extension.js:452:17
init@/usr/share/cinnamon/js/ui/appletManager.js:47:9
start@/usr/share/cinnamon/js/ui/main.js:493:5
@<main>:1:31
---------------->
error t=2017-11-12T19:02:48.298Z [Applet "calendar@cinnamon.org"]: Failed to load applet: calendar@cinnamon.org/13
error t=2017-11-12T19:02:48.299Z Could not load applet calendar@cinnamon.org

**Comment by itzexor** [comment]
Make sure your cinnamon-desktop is the latest version. I just installed the arch cinnamon packages and it's working for me.

**Comment by nick-s-b** [comment]
@itzexor thanks! I had a git version of cinnamon-desktop, for some reason, and now I've installed a packaged one instead of compiling the git one. It works! Thanks again.
