### ISSUE TITLE
problems with Adwaita-Dark in Manjaro

### ISSUE THREAD

**Issue by oberon2007** [linuxmint/Cinnamon#7011]
**Adwaita-Dark** with Archlinux packages **gnome-themes-standard 3.22.3** and **gtk 3.22.26** isn't showing any asset preview in the themes dialog.
Under 'window borders' only other installed themes are available. 

![adwaita_dark](https://user-images.githubusercontent.com/11800714/32706699-5faaf638-c81f-11e7-8f01-4a02285279e4.png)

Is this some kind of a packaging issue?

**Comment by oberon2007** [comment]
Looks like in general there is a problem with the automatic creation of 'Controls' preview.
**adapta-gtk-theme** preview for example shows up like this:

![screenshot from 2017-11-13 02-52-36](https://user-images.githubusercontent.com/11800714/32707763-04532248-c81e-11e7-9337-0dbad40e8fa6.png)

**Comment by oberon2007** [comment]
When I try to run `cinnamon-preview-gtk-theme` manually, a preview pops up in a borderless window and then it freezes like that and I have to terminate the script from the terminal.

![screenshot from 2017-11-13 03-07-40](https://user-images.githubusercontent.com/11800714/32708098-0e390fdc-c820-11e7-87c0-5c93d1b6f65c.png)

**Comment by oberon2007** [comment]
Ok. It seems cinnamon-preview-gtk-theme is just doing exactly what it's supposed to do 😉 
However, since I see that **gnome-themes-standard** is listed as a recommended dependency, I wonder how Adwaita-Dark is meant to be used with Cinnamon? Do we need to package themes with pre-made thumbnails? Also the problem remains that Adwaita-Dark doesn't appear to have matching window borders...

**Comment by oberon2007** [comment]
I figured out meanwhile:
* Adapta-theme includes the messed-up thumbnails already by default - so this is their issue obviously :wink:
* Adwaita seems to no longer include a metacity theme - so maybe it should just be removed from recommended dependencies.
In any case there is no issue with this in Cinnamon, sorry.

**Comment by leigh123linux** [comment]
You can resurrect adwaita  by adding muffin-adwaita.txt to force native

```
cat  /usr/share/themes/Adwaita/metacity-1/muffin-adwaita.txt'
native
```

**Comment by oberon2007** [comment]
Great. That's working nicely!
