### ISSUE TITLE
Security vulnerability: Lock screen does not lock full desktop

### ISSUE THREAD

**Issue by vascotenner** [linuxmint/Cinnamon#7012]
* Cinnamon 3.4.6
* Lubuntu artful 64-bit
* NVIDIA quadro M1200 with nvidia 384.90 driver

**Issue**
Security vulnerability: The lock screen only covers part of the desktop instead of full desktop (see screenshot attached). The windows react on mouse input. All information that can be displayed by using the mouse is exposed.

**Steps to reproduce**
* Suspend laptop with no mini-display port-vga adapter attached
* Attach mini-display port-vga adapter with monitor attached
* "unsleep" laptop (press powerbutton)

**Expected behaviour**
Lock screen prevents any data-exposure.

**Other information**
* Might be related to #5150. 
* Shall I open a CVE for this?

![screenshot from 2017-11-13 13-09-11](https://user-images.githubusercontent.com/3776190/32725228-90e7b0d8-c874-11e7-85a8-cb5685b7b2d9.png)

[xrandr.txt](https://github.com/linuxmint/Cinnamon/files/1466776/xrandr.txt)
[monitors.xml.txt](https://github.com/linuxmint/Cinnamon/files/1466777/monitors.xml.txt)
[w.txt](https://github.com/linuxmint/Cinnamon/files/1466778/w.txt)

**Comment by leigh123linux** [comment]
Should have filed the issue against cinnamon-screensaver, also can you reproduce the issue with cinnamon-screensaver-3.4.4 or cinnamon-screensaver-3.6.1?

**Comment by vascotenner** [comment]
Duplicate of: https://github.com/linuxmint/cinnamon-screensaver/issues/246
