### ISSUE TITLE
[Feature Request] Disable window selection in workspace changer

### ISSUE THREAD

**Issue by saif-ellafi** [linuxmint/cinnamon#7013]
Hi,

I am using Hot Corners to open full screen workspace changer, and use the mouse to hover the workspace I want to pick.

The annoying thing for me is that when I hover a desktop, I just want to click one and switch to that one. But instead, all windows in such desktop are shown and the one I click it brings such window front, where I just want to move to the desktop the way I left it.

It is an extra work to also pick the window I had open there.

I could not find any way to disable such behavior.

**Comment by JosephMcc** [comment]
There are a couple ways around this. You can use the arrow keys in workspace view to choose the workspace and hit enter. You can use the hotkeys for switching workspaces while on the desktop. You could also add the workspace applet and just use that. Given all the options I doubt this will get much traction.

**Comment by icarter09** [comment]
@collinss any update on this ticket?

**Comment by collinss** [comment]
Not really, no. I assigned myself to all these issues related to expo/scale because I was planning on making some improvements, but I never got to it. You can close all the feature requests and add them to your list.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
