### ISSUE TITLE
Cinnamon stutters after unlocking

### ISSUE THREAD

**Issue by DrDoctor13** [linuxmint/cinnamon#7014]
```
 * Cinnamon version (cinnamon --version): 3.6.2
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...): Manjaro
 * Graphics hardware *and* driver used: Nvidia GTX 970 - proprietary driver
 * 32 or 64 bit: 64 bit
 ```

**Issue**
Cinnamon will stutter after unlocking the desktop.

**Steps to reproduce**
-Lock the desktop
-Wait
-Unlock

**Expected behaviour**
Cinnamon shouldn't lag after unlocking

**Other information**
Restarting Cinnamon fixes the problem.

**Comment by icarter09** [comment]
Linux Mint 19.2
Cinnamon 4.2.4

I'm not able to reproduce this bug. But I'm also not using Manjaro.

@DrDoctor13 are you still experiencing this issue?
