### ISSUE TITLE
Feature request: Please sort the tray applet

### ISSUE THREAD

**Issue by ManuelSchneid3r** [linuxmint/cinnamon#7017]
```
Cinnamon 3.6.2
Arch
 ```
My tray bar is pretty long. The items are ordered randomly. It would be timesaving if the items would always have the same order. Maybe a lexical order of the app name would make sense.

**Comment by vladimir-didenko** [comment]
-1. At least it should be optional.

**Comment by ManuelSchneid3r** [comment]
@vladimir-didenko Why do you think it's a bad idea? Does it bother you if it is sorted instead of random?

**Comment by vladimir-didenko** [comment]
I like when when icons appear in tray in the  same order as application started. Starting applications manually allows me to order icons in specific order - colored icons first and then black/white. In this case panel looks more consistent for me. I am OK if requested feature will be implemented as option.

**Comment by ManuelSchneid3r** [comment]
Okay I see your point. But If the devs dont want to introduce an option I hope they decide to sort them. I think yours is a rare edge case. Probably most of the users have several autostart applications and immediately after login tray looks like this: 

![image](https://user-images.githubusercontent.com/3252315/32833520-6df8894e-c9ff-11e7-8e4e-b9a64bb55e0a.png)

**Comment by abdouskamel** [comment]
Putting it as an option would help both sides. There are surely a lot of people who would like to sort tray bar items.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
