### ISSUE TITLE
Lower buttons are not displayed in cinnamon-settings.py

### ISSUE THREAD

**Issue by Shatur95** [linuxmint/Cinnamon#7018]
```
 * Cinnamon version: 3.6.2
 * Distribution - Arch
 * Nvidia 765m, 387.22
 * 64 bit
 * GTK version: 3.22.26
 ```

**Issue**
In applets and themes menu lower buttons not displayed (used GTK3 theme is Adwaita):
<a target="_blank" href="https://itmages.ru/image/view/6253794/a55517dd"><img src="http://storage8.static.itmages.ru/i/17/1114/s_1510672759_7872455_a55517dd33.png" /></a><a target="_blank" href="https://itmages.ru/image/view/6253795/12703347"><img src="http://storage8.static.itmages.ru/i/17/1114/s_1510672759_2918039_1270334709.png" /></a><a target="_blank" href="https://itmages.ru/image/view/6253797/dc7f6ee3"><img src="http://storage8.static.itmages.ru/i/17/1114/s_1510672760_5471054_dc7f6ee33c.png" /></a>

I tried to change GTK3 theme to default fnome theme (Adwaita) and issue still present:
<a target="_blank" href="https://itmages.ru/image/view/6253798/ea1e594d"><img src="http://storage9.static.itmages.ru/i/17/1114/s_1510672760_6701078_ea1e594d10.png" /></a>
But if I use Ambiant-Mate theme buttons are displayed in applet menu but still hidden in themes menu:
<a target="_blank" href="https://itmages.ru/image/view/6253799/830f0bf6"><img src="http://storage9.static.itmages.ru/i/17/1114/s_1510672760_1880405_830f0bf618.png" /></a><a target="_blank" href="https://itmages.ru/image/view/6253800/c5355cde"><img src="http://storage1.static.itmages.ru/i/17/1114/s_1510672761_4483279_c5355cde14.png" /></a>

Maybe it caused by new GTK version?

**Comment by Odyseus** [comment]
Hello, @Shatur95.

```shell
System:    Kernel: 4.13.12-1-ARCH x86_64 bits: 64 gcc: 7.2.0
           Desktop: Cinnamon 3.6.2 (Gtk 3.22.26-1) dm: lightdm
           Distro: Arch Linux
```

Maybe your issue has nothing to do with the theme you are using. ***I can see all buttons at all times with both of the themes that I have installed in my Arch system (Adwaita (Light and Dark) and Greybird).***

![image](https://user-images.githubusercontent.com/3822556/32795316-116b324a-c94a-11e7-82e6-38a4557b85ad.png)

You could try launching any of the xlets managers from terminal and see if there are any errors reported.

```shell
$ cinnamon-settings applets
# or...
$ cinnamon-settings desklets
# or...
$ cinnamon-settings extensions
# or...
$ cinnamon-settings themes
```

**Comment by Shatur95** [comment]
I do not see anything suspicious...
```
[gena@Alienware-M15x ~]$ cinnamon-settings applets
Loading Applets module

(cinnamon-settings.py:2853): Gtk-WARNING **: Theme parsing error: <data>:1:41: The style property GtkWidget:wide-separators is deprecated and shouldn't be used anymore. It will be removed in a future version

(cinnamon-settings.py:2853): Gtk-WARNING **: Theme parsing error: <data>:1:41: The style property GtkWidget:wide-separators is deprecated and shouldn't be used anymore. It will be removed in a future version
[gena@Alienware-M15x ~]$ cinnamon-settings desklets
Loading Desklets module

(cinnamon-settings.py:2907): Gtk-WARNING **: Theme parsing error: <data>:1:41: The style property GtkWidget:wide-separators is deprecated and shouldn't be used anymore. It will be removed in a future version

(cinnamon-settings.py:2907): Gtk-WARNING **: Theme parsing error: <data>:1:41: The style property GtkWidget:wide-separators is deprecated and shouldn't be used anymore. It will be removed in a future version

(cinnamon-settings.py:2907): Gtk-WARNING **: Theme parsing error: <data>:1:41: The style property GtkWidget:wide-separators is deprecated and shouldn't be used anymore. It will be removed in a future version
[gena@Alienware-M15x ~]$ 
```
I tested with this your metacity+GTK3-theme configuration and issue still present:
<a target="_blank" href="https://itmages.ru/image/view/6254254/2b712d81"><img src="http://storage7.static.itmages.ru/i/17/1114/s_1510682552_6898968_2b712d8119.png" /></a>
It's so strange.

**Comment by Shatur95** [comment]
Oh, it's a Cinnamon bug!
This bug present only in Russian language. When I launching cinnamon-settings with en_US for example the bug goes away:
<a target="_blank" href="https://itmages.ru/image/view/6254285/6534cfe7"><img src="http://storage3.static.itmages.ru/i/17/1114/s_1510683375_8922076_6534cfe7ce.png" /></a>

**Comment by Shatur95** [comment]
I also noticed that cinnamon-settings have looks different in Russian language:
<a target="_blank" href="https://itmages.ru/image/view/6254880/c02cd122"><img src="http://storage1.static.itmages.ru/i/17/1114/s_1510701406_1503520_c02cd12283.png" /></a><a target="_blank" href="https://itmages.ru/image/view/6254879/81cd8b4a"><img src="http://storage1.static.itmages.ru/i/17/1114/s_1510701406_9806912_81cd8b4ab1.png" /></a>

**Comment by JosephMcc** [comment]
I have a suspicion what the problem might be. When you open the window and the buttons aren't showing, trying resizing the window to make it wider and see if they show up at some point.

**Comment by MrNanook** [comment]
It has to do with the description of an applet. The longest description has to be completely visible for the buttons to show up, by resizing. For me that's the "Settings API Demo".

I have the same issue in Dutch (haven't tried English).

**Comment by MrNanook** [comment]
I have the same issue in Dutch (haven't tried English).

@JosephMcc 

It has to do with the description of an applet. The longest description has to be completely visible for the buttons to show up, by resizing the window. For me that's the "Settings API Demo".

Extensions and Themes don't have this problem for me. 
In Extensions and Desklets the buttons disappear if there is no place for them.

**Comment by MrNanook** [comment]
I have the same issue in Dutch (haven't tried English). Using Arch/Manjaro, Numix-ArchBlue GTK theme with gtk3-mushrooms.

@JosephMcc 

It has to do with the description of an applet. The longest description has to be completely visible without word wrapping for the buttons to show up, by resizing the window. For me that's the "Settings API Demo".

Extensions and Themes don't have this problem for me. 
In Extensions and Desklets the buttons disappear if there is no place for them.

So slightly different problems compared to Shatur95.

**Comment by Shatur95** [comment]
@JosephMcc You are right! When I increased the window, buttons became visible.

**Comment by Shatur95** [comment]
Also the window does not save the size, and I need to resize window every time.

**Comment by MrNanook** [comment]
I have the same issue in Dutch (haven't tried English). Using Arch/Manjaro, Numix-ArchBlue GTK theme with gtk3-mushrooms/gtk3-classic.

@JosephMcc 

It has to do with the description of an applet. The longest description has to be completely visible without word wrapping for the buttons to show up, by resizing the window. For me that's the "Settings API Demo".

Extensions and Themes don't have this problem for me. 
In Extensions and Desklets the buttons disappear if there is no place for them.

So slightly different problems compared to Shatur95.

**Comment by jeweloper** [comment]
Same with German localization. It affects the applet and extension dialog.

**Comment by JosephMcc** [comment]
Yeah. We know what the problem is and we'll get this addressed.
