### ISSUE TITLE
Squished buttons in starter bar

### ISSUE THREAD

**Issue by kaymio** [linuxmint/Cinnamon#7022]
```
 * Cinnamon 3.6.2
 * Distribution - Arch
 * Graphics RX480 Mesa 17.2.5
 * 64 bit
 ```

**Issue**
![squished_icons](https://user-images.githubusercontent.com/22966929/32841283-32841368-ca1a-11e7-9ae8-852bbdf1bacd.png)
Program start buttons are squished vertically.

**Steps to reproduce**
Update from Cinnamon 3.6.0 to 3.6.2

**Expected behaviour**
Equal proportions of these buttons. 

**Other information**
I've to raise the cursor ~2 mm to reach the buttons from the bottom. If I change the size of the bar, the icons also get bigger but are still more broad than tall. Changing the icon theme doesn't do anything. This problem only occurs on my desktop, not on my laptop. (On my laptop, Cinnamon is crashing when starting Mendeley Desktop, but that is for another thread.)

**Comment by JosephMcc** [comment]
I've never seen this issue. What Cinnamon theme are you using?

**Comment by kaymio** [comment]
You pointed me into the right direction. Since 3.6.3 also the clock only shows hours. The problem seems to lie in the Desktop Theme Eleganse-dark. The starter panel is fixed with some others like qob, but the time/date is still not right.

eleganse-dark
![eledar_time](https://user-images.githubusercontent.com/22966929/33017025-0582e968-cdf1-11e7-9d91-4464557d0bb4.png)

cinnamon standard
![cinstan_time](https://user-images.githubusercontent.com/22966929/33017039-1570bcf6-cdf1-11e7-8427-6cf612243337.png)

qob, the new choice for me
![qob_time](https://user-images.githubusercontent.com/22966929/33017042-210d9ba6-cdf1-11e7-9219-baa9826aca84.png)

**Comment by JosephMcc** [comment]
Ok. Does it work properly with the stock "Cinnamon" theme? If the issue was with the theme, can we close this?

**Comment by kaymio** [comment]
Yes, thx for your participation.
