### ISSUE TITLE
calendar applets custom date-time-format is brocken

### ISSUE THREAD

**Issue by jeweloper** [linuxmint/Cinnamon#7037]
```
 * Cinnamon 3.6.3
 * Distribution Arch
 * Intel i5-6200U/HD520 / i915 (+mesa)
 * 64 bit
 ```

**Issue**
The custom date time format output of calendar@cinnamon applet is broken, since 3.6.3 update.
In a horizontal panel it shows only the time (in vertical mode - hour upon minute) regardless which custom date-time-format is set.

**Steps to reproduce**
Add calendar applet to a **horizontal** panel. Activate / switch the custom date time format option on the applet setting dialog.

**Expected behaviour**
Display date time in the custom format set in the applet setting dialog.

**Comment by Zerophase** [comment]
I have this issue as well.

**Comment by mtwebster** [comment]
https://github.com/linuxmint/Cinnamon/commit/e648f1e66e4523cacc059f1082302c0a6841c9c4
