### ISSUE TITLE
"Caps Lock Key is disabled" setting ignored

### ISSUE THREAD

**Issue by bluebear94** [linuxmint/cinnamon#7039]
```
 * Cinnamon version (cinnamon --version): 3.4.6
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...): Ubuntu 17.10
 * Graphics hardware *and* driver used: NVIDIA GeForce 930M / 384.90
 * 32 or 64 bit: 64 bit
 ```

**Issue**

The "Caps Lock key is disabled" settings is ignored, acting like the default behaviour.

**Steps to reproduce**

Keyboard > Keyboard Layout > Options

Select Caps Lock Key Behaviour > Caps Lock key is disabled

**Expected behaviour**

Caps Lock key should be disabled.

**Other information**

**Comment by icarter09** [comment]
Cinnamon 3.4.6
Linux Mint 18.2 
64bit

Just followed the steps in the ticket and not experiencing the expected behavior. Once "Caps Lock key is disabled" is selected, the Caps Lock key is properly disabled on my machine.

**Comment by bluebear94** [comment]
Hmm, the bug seems to depend on the distro then. It might be that some settings set differently in Mint than in Ubuntu affect the setting.

(By the way, with regular GNOME, the Caps Lock key is properly disabled.)

**Comment by JosephMcc** [comment]
I can't reproduce this with Mint18.3 and Cinnamon3.6 either. I'll try on 17.10 later.

**Comment by nanobitsoftware** [comment]
I can confirm that this bug affects me as well.

Cinnamon 3.6.6
NAME="Linux Mint"
VERSION="18.3 (Sylvia)"


In fact, changing it to ANY setting has no affect on caps lock behavior.

A work around, for now that works for me is, 
"setxkbmap -model pc105 -layout us -option caps:none" and setting it as  a startup as well, to persist across reboots.

**Comment by perlun** [comment]
Similar for me on Debian buster with Cinnamon 3.8.8. The UI has absolutely no effect, even after logging out and back in again.

`setxkbmap -option caps:none` has absolutely no effect. :cry: If I do `setxkbmap -model pc105 -layout us -option caps:none` instead, it kills the whole keymap switcher applet and I have to re-logon to get it back.

**Comment by perlun** [comment]
Correction: I had set the "Switching to another layout" to also use Caps Lock for switching. It seems these didn't play well together (which differs from GNOME, where I had to set them both).

If I remove the "Caps Lock is disabled" and _just_ use the "Switching to another layout" setting to let Caps Lock switch my layout => everything works great. :+1: Sorry for the noise.

**Comment by Vahan86** [comment]
I can't reproduce this issue in Cinnamon 4.4.8. 

@bluebear94, is this still an issue for you with Cinnamon 4.4?
