### ISSUE TITLE
Connecting to PPPOE from GUI don't work

### ISSUE THREAD

**Issue by Shatur95** [linuxmint/Cinnamon#7042]
```
 * Cinnamon version - 3.6.3
 * Distribution - Arch
 * 64 bit
 ```
**Issue**
With new version of NetworkManager (1.10) PPPOE connections doesn't work.
I added connection PPPOE connection:
<a target="_blank" href="https://itmages.ru/image/view/6264592/3dbf2cec"><img src="http://storage3.static.itmages.ru/i/17/1118/s_1511002495_8352762_3dbf2cec05.png" /></a>
But I can't connect to it from GUI. I can connect only to Automatic Ethernet connection:
<a target="_blank" href="https://itmages.ru/image/view/6264598/2ec2d784"><img src="http://storage9.static.itmages.ru/i/17/1118/s_1511002805_1573044_2ec2d7848e.png" /></a>
Also when I launching `cinnamon-settings network` with this Ethernet connection, I have some warnings in console:
```
$ cinnamon-settings network

(cinnamon-settings.py:6369): network-cc-panel-WARNING **: Error connecting to ModemManager: Ошибка вызова StartServiceByName для org.freedesktop.ModemManager1: GDBus.Error:org.freedesktop.systemd1.NoSuchUnit: Unit dbus-org.freedesktop.ModemManager1.service not found.
/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py:612: Warning: g_variant_get_type: assertion 'value != NULL' failed
  Gtk.main()
/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py:612: Warning: g_variant_type_is_subtype_of: assertion 'g_variant_type_check (type)' failed
  Gtk.main()
/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py:612: Warning: g_variant_get_boolean: assertion 'g_variant_is_of_type (value, G_VARIANT_TYPE_BOOLEAN)' failed
  Gtk.main()
```

Is this Cinnamon issue?

**Comment by Shatur95** [comment]
Also when I'm connected to PPPOE, cinnamon-settings crashes:
```
$ cinnamon-settings network
(cinnamon-settings.py:14696): network-cc-panel-WARNING **: Error connecting to ModemManager: Ошибка вызова StartServiceByName для org.freedesktop.ModemManager1: GDBus.Error:org.freedesktop.systemd1.NoSuchUnit: Unit dbus-org.freedesktop.ModemManager1.service not found.
/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py:148: Warning: g_object_get_is_valid_property: object class 'NMDevicePpp' has no property named 'hw-address'
  self.main_stack.set_visible_child_name("content_box_page")
*** Error in `/usr/bin/python2': double free or corruption (out): 0x00007fff8f77fb90 ***
Аварийный останов (стек памяти сброшен на диск)
```

**Comment by Shatur95** [comment]
@leigh123linux why you close this issue?

**Comment by leigh123linux** [comment]
Shouldn't you report your issue to 'flyspray' instead.

https://wiki.archlinux.org/index.php/Flyspray

cinnamon-control-center does the network settings.

**Comment by leigh123linux** [comment]
@Shatur95 

We are sick of dealing with arch issues due to bad packaging and the lack of debugging symbols means we're not interested!

> why you close this issue?

**Comment by Shatur95** [comment]
@leigh123linux are you sure? Cinnamon settings crashes with pppoe connection and don't allow configure it with new version of NetworkManager...

**Comment by leigh123linux** [comment]
Cinnamon isn't responsible for network settings, cinnamon-control-center does it.

```
cinnamon-control-center network
```

**Comment by Shatur95** [comment]
@leigh123linux Oh... Sorry for it! I will send issue to `cinnamon-control-center` repo. I think that caused by changes in new NetworkManager.

**Comment by ntblade** [comment]
Sorry to comment on an old issue but where should this bug be reported so it can be fixed please? The OP also posted in cinnamon-control-center but got nowhere

The DSL / PPPoE connections used to be available in Mint / Cinnamon from the nm applet but at some upgrade along the way it disappeared. I running a bare install of 19.2 and 19.3 on two systems and it's not there

Thanks

NTB
8o)

**Comment by unggulzmalqp** [comment]
on linux mint 19.3 you need to fill the PPP interface name with the name of parent interface to make it work. Already try it and it works on my laptop.

for reference: https://forums.linuxmint.com/viewtopic.php?p=1760566
