### ISSUE TITLE
GNOME Online Accounts and GNOME Calendar

### ISSUE THREAD

**Issue by szekeres2016** [linuxmint/Cinnamon#7043]
```
 * Cinnamon version 3.6
 * Distribution - (Mint 18.3 Beta)
 * 64 bit
 ```
Dear Cinnamon developers. I was excited to see there is now GNOME Online Accounts support in the new Cinnamon version. After testing it a bit I noticed that the file explorer integration is great, but other areas does not seem to work. I tried to install GNOME Calendar, but the Google Calendar events are not showing up. Is there any other package in need to be installed for thus functionality to work? Many thanks in advance!

**Steps to reproduce**
After logging in to Google account I've installed GNOME Calendar from the ubuntu repo, and even tried the flatpak flathub repo to test the latest version. No Google calendar event is showing up.

![kep](https://user-images.githubusercontent.com/20751590/32979863-03afa54e-cc5d-11e7-8b9d-ab18100930cf.png)

**Comment by collinss** [comment]
Hi @szekeres2016, the online accounts stuff was slipped in toward the end of the development cycle and it was mostly just a port of the gnome shell online accounts. It probably works with nemo (the file manager) because there weren't a lot of changes required to get it working. Integrating it into the calendar applet will most likely require a complete redesign of large parts of the applet, and will certainly take a lot more work. While I haven't heard anyone on the team talk about it yet, it will probably happen in due time.

**Comment by dm2912** [comment]
@szekeres2016 is referring to the actual gnome-calendar applet from ubuntu repos that the help on online accounts say it is compatible...

Ive just tested it. My google is setup in online accounts.
installed gnome-calendar version 3.20.4 in synaptic

and all my google calendar events are appearing in gnome calendar without any issues.

**Comment by dm2912** [comment]
@szekeres2016 click the calendar icoin to the top right of gnome-calendar (next to search) and hit calendar settings and check the google account is appearing there and is listed as "on"

Mine is coming over no problems>

**Comment by DanielRios549** [comment]
I don't have certain of it, but I think it will work if you install the package "evolution-data-server-online-accounts"

**Comment by fritzophrenic** [comment]
You need to enable syncing each calendar you want from Google. I'm not aware of how to get here other than a deep link, but this page lets you do that: https://calendar.google.com/calendar/syncselect

Annoyingly enough, I had to find that page by searching for calendars not syncing *in Windows*. https://answers.microsoft.com/en-us/windows/forum/apps_windows_10-outlook_cal-winpc/how-to-sync-all-shared-google-calendars-to-windows/b3561cd6-9ec1-4499-8de6-55d9e2a54d7f
