### ISSUE TITLE
Please improve _Take a screenshot_ on Print hot-key

### ISSUE THREAD

**Issue by rootext** [linuxmint/cinnamon#7045]
```
 * Cinnamon version (cinnamon --version) - Cinnamon 3.2.7
 * Distribution - Mint 17.1
 * Graphics hardware *and* driver used - 
 * 64 bit
 ```

**Issue**
By default Print key is bind to take a screenshot. It is a very useful feature.
However, to my mind, some things can be improved:
1. _Save Screenshot_ has an almost transparent overlay. It is okay if you've took one screenshot but it makes you screen completely gray or black if you adjacently press it a few seconds.
Please remove overlay or fix the second point
2. Number of opened _Save Screenshot_ is unlimited. It leads to the same result as in the first point.
Please limit number of simultaneously opened _Save Screenshot_ windows or debounce hot-key.

**Steps to reproduce**
Press Print key 5 second
or
 Your cat has sat on keyboard and pressed Print key

**Expected behaviour**
Please remove overlay or limit number of simultaneously opened _Save Screenshot_ windows or debounce hot-key.

**Other information**

**Comment by obliviateandsurrender** [comment]
Plus one more thing in order to take a partial screenshot we press Shift+PrtScr buttons. I have seen that I have to press this combination quite a few times in order to have it effect. (This keybinding works totally fine in my Ubuntu system though). Could there be a fix for this too?

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
