### ISSUE TITLE
Cinnamon 3.6.2 Touchpad 2 finger and 3 finger tap is reversed

### ISSUE THREAD

**Issue by greyseal96** [linuxmint/cinnamon#7048]
```
 * Cinnamon version (cinnamon --version)
**3.6.2**
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
**Arch**
 * Graphics hardware *and* driver used  
**VGA Controller**: VGA compatible controller: Intel Corporation 4th Gen Core Processor Integrated Graphics Controller (rev 06)
Driver: Not sure
**3D Controller**: NVIDIA Corporation GK106M [GeForce GTX 760M] (rev ff)
Driver: 387.22
 * 32 or 64 bit
**x64**
 ```

**Issue**
After recently upgrading to Cinnamon 3.6.2 the tap button settings on my touchpad are reversed: 2 finger click was mapped to the middle click action but now it is mapped to the right click action; and 3 finger click was mapped to the right click action but now it is mapped to the middle click action.

For example, here is the relevant output of ```synclient -l```:
```
    TapButton1              = 1
    TapButton2              = 3
    TapButton3              = 2
    ClickFinger1            = 1
    ClickFinger2            = 3
    ClickFinger3            = 2
```
And here is the relevant output of ```xinput --list-props 'ETPS/2 Elantech Touchpad'```
```
	Synaptics Tap Action (290):	2, 3, 0, 0, 1, 3, 2
	Synaptics Click Action (291):	1, 3, 2
```

Previously the tap button actions were not reversed.  They were something like the following:
```
TapButton1 = 1
TapButton2 = 2
TapButton3 = 3
```
I don't see a way in the Mouse and Touchpad section of the System Settings to get this fixed or reversed.  The closest thing that I could find was a setting called "Click actions" in the General section but I tried all of those settings and none of them got the assignments reversed.  Is this a temporary bug or the way that it will be going forward?  Also, what is the "supported" way to fix this?  I've been searching online and I've read that I can create a config file for libinput that will correct the settings.  I've also read that I need to use gsettings to fix this.  

**Steps to reproduce**

1. In Mouse and Touchpad under System Settings, Enable Touchpad.
2. Turn on Tap to click.
3. Set Click actions to "Automatic".
4. Try 2 finger and 3 finger tap. See that 2 finger tap is mapped to right click and 3 finger tap is mapped to middle click.
5. Try other settings for Click actions and see that the tap button settings are still the same.

**Expected behaviour**
2 finger tap mapped to middle button click and 3 finger tap mapped to right click or
```
TapButton1 = 1
TapButton2 = 2
TapButton3 = 3
```

**Other information**

**Comment by KevinNadaud** [comment]
Hi,
the bug seems to be similar to this one:
[https://github.com/linuxmint/cinnamon-control-center/issues/159](url).
To fix the trouble you can type this `synclient TapButton2=2 TapButton3=3`

**Comment by greyseal96** [comment]
Hi, thanks for responding.  This gave me some interesting results.  From the description in the [linked issue](https://github.com/linuxmint/cinnamon-control-center/issues/159), I initially thought that the command that I wanted was `synclient TapButton2=3 TapButton3=2`.  I set this and verified that the TapButton settings were correct in the loaded configuration:

    $ synclient -l | grep -i tap
        MaxTapTime              = 180
        MaxTapMove              = 175
        MaxDoubleTapTime        = 180
        SingleTapTimeout        = 180
        TapButton1              = 1
        TapButton2              = 3
        TapButton3              = 2
        TapAndDragGesture       = 1

But, when I tested the tap buttons, I still observed the incorrect behavior.  Just for fun, I thought that I'd try doing the opposite of what I thought was the right way and I entered `synclient TapButton2=2 TapButton3=3`.  I dumped the loaded configuration:

    $ synclient -l | grep -i tap
        MaxTapTime              = 180
        MaxTapMove              = 175
        MaxDoubleTapTime        = 180
        SingleTapTimeout        = 180
        TapButton1              = 1
        TapButton2              = 2
        TapButton3              = 3
        TapAndDragGesture       = 1

and I saw that the loaded configuration reflected what I'd entered.  However, this time, I noticed that the tap buttons were responding as I wanted.  Any idea why Synaptics is doing the opposite of what it should be doing?

Not sure if this matters or not but, according to my Xorg log, Xorg is using the Synaptics touchpad driver:

    $ grep -e "Using input driver '[A-Za-z]*'" /var/log/Xorg.0.log
        [    26.071] (II) Using input driver 'libinput' for 'Power Button'
        [    26.090] (II) Using input driver 'libinput' for 'Asus Wireless Radio Control'
        [    26.130] (II) Using input driver 'libinput' for 'Video Bus'
        [    26.171] (II) Using input driver 'libinput' for 'Video Bus'
        [    26.211] (II) Using input driver 'libinput' for 'Sleep Button'
        [    26.232] (II) Using input driver 'libinput' for 'ASUS USB2.0 Webcam: ASUS USB2.0'
        [    26.275] (II) Using input driver 'libinput' for 'Asus WMI hotkeys'
        [    26.311] (II) Using input driver 'libinput' for 'AT Translated Set 2 keyboard'
        [    26.340] (II) Using input driver 'synaptics' for 'ETPS/2 Elantech Touchpad'

Since I saw that Synaptics is the driver managing the touchpad, I thought that I'd try changing the custom settings in /etc/X11/xorg.conf.d/50-synaptics.conf. Here's a snippet from the relevant section:

    Section "InputClass"
        Identifier "touchpad catchall"
        Driver "synaptics"
        MatchIsTouchpad "on"
        Option "TapButton1" "1"
        Option "TapButton2" "3"
        Option "TapButton3" "2"
        Option "VertEdgeScroll" "on"
        Option "HorizEdgeScroll" "on"
        MatchDevicePath "/dev/input/event*"
    EndSection

The setting here doesn't seem to have any effect.  I've rebooted several times and no matter what the TapButton settings are, it's always `TapButton1=1 TapButton2=2 TapButton3=3`  So far, the only thing that's worked is manually setting the TapButton settings to the opposite of what they should be (as stated above) through synclient.  

Is this a bug or is there a way to permanently set the correct setting like through a config file or through dconf-editor?

**Comment by icarter09** [comment]
@greyseal96 are you still experiencing this issue?
