### ISSUE TITLE
[Feature Request] Add System-wide Install/Update Options for Applets and Extensions

### ISSUE THREAD

**Issue by feren** [linuxmint/Cinnamon#7052]
Basically, what the title says, as in, as well as giving the user the option to update or install an applet to their own user, it'd be nice for them to also have the option of doing so to the system-wide /usr/share/cinnamon/* directory...

**Comment by ManIVIctorious** [comment]
-1 You should never tamper with anything in your /usr/ directory (except /usr/local) since this is the domain of your system's package management and it would make completely uninstalling an application unnecessary complicated

**Comment by feren** [comment]
To be fair, firstly, only an Administrator would be able to do it, and secondly, you can easily implement a blacklist, so that you can block the Un-installation of Cinnamon's Pre-Installed Applets (Disable System-wide Uninstall for Spices Applets)

**Comment by mtwebster** [comment]
I'm going to close this, the more I think about it the less I want it to even have possibility of gaining traction.

If you want to pre-install extensions in /usr/share/cinnamon/* there's nothing stopping you.  If you want to update them, stick them in their own package so you can update at your own pace.  You don't need to own the directory to place or replace files there.  If you want the updater to be able to update them, then add them to the user skeleton files.

There are numerous ways to achieve this, without increasing complexity in cinnamon's code, or complexity in our bug reports (which are bad enough already without wondering about the reliability of the user's installation)

**Comment by NikoKrause** [comment]
I agree with mtwebster. I don't want to run third party applets as root.
