### ISSUE TITLE
Issue Cinnamon 3.6.4

### ISSUE THREAD

**Issue by gflaviosilva** [linuxmint/Cinnamon#7056]
```
 * Cinnamon version 3.6.4
 * Linux Mint 18.3 - Sylvia
 * Mesa DRI Intel(R) Ivybridge Mobile  - Intel Microcode V3.20170707.1~ubuntu16.04.0
 * 64 bit
 ```

**Issue**
I just received the "Cinnamon 3.6.4" update, I noticed that any Mint menu does not open anymore.

I tried via terminal to open the "cinnamon-settings" it returns the following error:

Traceback (most recent call last):
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 45, in <module>
    modules = map(__import__, mod_files)
  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_sound.py", line 689
    icon = iconTheme.load_icon("bluetooth", 32, 0)
       ^
IndentationError: expected an indented block

-----

I'm from Brazil!
Apologies for my English !!!!!

**Comment by mtwebster** [comment]
Check for a 3.6.5 either now or very soon...

https://github.com/linuxmint/Cinnamon/issues/7055
