### ISSUE TITLE
cs_sound Indentation Issue

### ISSUE THREAD

**Issue by matthew-williams** [linuxmint/Cinnamon#7057]
[cs_sound.py.tar.gz](https://github.com/linuxmint/Cinnamon/files/1488605/cs_sound.py.tar.gz)
```
 * Cinnamon version Cinnamon 3.6.4
 * Distribution - Mint 18.3
 * Graphics hardware *and* driver used
Not related
 * 64 bit
 ```

**Issue**
cinnamon-settings crashes on launch
`Traceback (most recent call last):
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 45, in <module>
    modules = map(__import__, mod_files)
  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_sound.py", line 689
    icon = iconTheme.load_icon("bluetooth", 32, 0)
`
When looking found the issue in the code shown in the screenshot attached.
![image](https://user-images.githubusercontent.com/6619443/33033289-281dc85e-cde1-11e7-9bd7-f994ab3d4ba5.png)
Changed it to:

![image](https://user-images.githubusercontent.com/6619443/33033382-6f9c0c86-cde1-11e7-9ea0-600a355f5d8e.png)

**Steps to reproduce**

`cinnamon-settings`

**Expected behaviour**

Launch cinnamon-settings

**Other information**
Resolved by changing the indent issue on line 689.

**Comment by mtwebster** [comment]
https://github.com/linuxmint/Cinnamon/issues/7055

**Comment by mtwebster** [comment]
3.6.5 released
