### ISSUE TITLE
Cinnamon settings crashes after upgrading to 3.6.4

### ISSUE THREAD

**Issue by Zerophase** [linuxmint/Cinnamon#7058]
```
 * Cinnamon version: 3.6.4
 * Distribution - Arch
 * Graphics: 660ti NVidia 387.22-5 
 * 64 bit
 ```

**Issue**
Cinnamon settings crashes right after being launched.

**Steps to reproduce**

1. Upgrade to the latest version of Cinnamon.
2. Open cinnamon-settings from terminal or start menu.
3. cinnamon-settings crashes.

**Expected behaviour**
cinnamon-settings opens.

**Other information**
Running the arc theme. 

Here's the trace log:

> (cinnamon-settings.py:13599): Gtk-WARNING **: Theme parsing error: gtk.css:6:18: The 'gtk-key-bindings' property has been renamed to '-gtk-key-bindings'
> Traceback (most recent call last):
>   File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 45, in <module>
>     modules = map(__import__, mod_files)
>   File "/usr/share/cinnamon/cinnamon-settings/modules/cs_sound.py", line 689
>     icon = iconTheme.load_icon("bluetooth", 32, 0)
>        ^
> IndentationError: expected an indented block

**Comment by mtwebster** [comment]
https://github.com/linuxmint/Cinnamon/issues/7055

**Comment by mtwebster** [comment]
3.6.5 released..
