### ISSUE TITLE
Can't open cinnamon-settings

### ISSUE THREAD

**Issue by jeweloper** [linuxmint/Cinnamon#7059]
```
 * Cinnamon 3.6.4
 * Distribution Arch
 * Intel i5-6200U/HD520 / i915 (+mesa)
 * 64 bit
 ```

**Issue**
Cinnamon-settings is exit with error message:
`$ cinnamon-settings`
`Traceback (most recent call last):`
`  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 45, in <module>`
`    modules = map(__import__, mod_files)`
`  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_sound.py", line 689`
`    icon = iconTheme.load_icon("bluetooth", 32, 0)`

**Steps to reproduce**
Run cinnamon-settings

**Expected behaviour**
No exits with error messages.

**Other information**
I think it is because line 688 in cs_sound.py starts with a tab.

**Comment by mtwebster** [comment]
duplicate: https://github.com/linuxmint/Cinnamon/issues/7055
