### ISSUE TITLE
Cinnamon feature: remove startmenu favorites apps

### ISSUE THREAD

**Issue by mileon** [linuxmint/Cinnamon#706]
Hello

I cannot remove a favorite app from the cinnamon startmenu. I know this is no real issue.  This function is not implented. Is it possible to add this function?

My system:
Mint Maya - Cinnamon 1.4 Up3

bye

**Comment by Grinnz** [comment]
:+1: I think a trashcan icon appearing when dragging favorites icons would be much more intuitive. Currently you have to drag it to somewhere on the menu outside of the favorites (dragging outside the menu does not work).
