### ISSUE TITLE
cinnamon-control-center 3.6.5-1

### ISSUE THREAD

**Issue by Bundy01** [linuxmint/Cinnamon#7060]
* Cinnamon version 3.6.4-1
 * Distribution - Arch
 * Graphics hardware *and* driver used: Intel
 * 64 bit

cinnamon-control-center 3.6.5-1 does not work. Cannot access settings on Archlinux x64. 
No problems on the version 3.6.3-1.

**Comment by mtwebster** [comment]
Please provide terminal output from running 'cinnamon-settings' and open this issue in the correct repo: https://github.com/linuxmint/cinnamon-control-center/issues

Also, please use the provided template
