### ISSUE TITLE
Cinnamon-control-center 3.6.5-1 does not work

### ISSUE THREAD

**Issue by Bundy01** [linuxmint/Cinnamon#7061]
* Cinnamon version 3.6.4-1
 * Distribution - Arch
 * Graphics hardware *and* driver used: Intel
 * 64 bit

cinnamon-control-center 3.6.5-1 does not work. Cannot access settings on Archlinux x64. 
No problems on the version 3.6.3-1.

**Comment by mtwebster** [comment]
https://github.com/linuxmint/Cinnamon/issues/7055
