### ISSUE TITLE
Some apps don't use GTK window decoration

### ISSUE THREAD

**Issue by eudennis** [linuxmint/Cinnamon#7062]
```
 * Cinnamon version 3.46
 * Distribution - Ubuntu 17.10
 * Graphics hardware *and* driver used
 * 64 bit
 ```

I'm using a theme called Vimix, but I not sure why some windows don't use the GTK window decoration. Any ideas how I can fix that on the theme?

**Comment by JosephMcc** [comment]
Some windows use client side decorations and those are drawn by gtk and the gtk theme. Others are provided by the window manager and use the metacity theme. You need a metacity (window border) theme to match your gtk theme.
