### ISSUE TITLE
Cinnamon crash in st_label_set_text() -> g_type_check_instance_cast()

### ISSUE THREAD

**Issue by KAMI911** [linuxmint/Cinnamon#7064]
```
 * Cinnamon version 3.6.5
 * Distribution - Mint 18.3 beta
 * Graphics hardware: 00:02.0 VGA compatible controller: Intel Corporation 4th Gen Core Processor Integrated Graphics Controller (rev 06)
* Driver from Padoka PPA:
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) Haswell Mobile 
OpenGL core profile version string: 4.5 (Core Profile) Mesa 17.3.0-rc4 - padoka PPA
OpenGL core profile shading language version string: 4.50
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

 * 64 bit
 ```
The Cinnamon UI stopped to work. Few minutes later it asked for restart Cinnamon.

https://gist.github.com/anonymous/3dece741e7071c696457d28cec142cf7

**Comment by clefebvre** [comment]
During the 18.3 BETA feedback, somebody reported this:

https://gist.github.com/anonymous/4f22e19d4fd3b2bbe9fdee6b1daf77fa

Happens randomly when executing this:

```
#!/bin/bash
# Refresh network connections
sudo service network-manager restart
sleep 10
exit
```

**Comment by KAMI911** [comment]
The only modification that I did (for 18.1) is this:
$ sudo cat /lib/systemd/system-sleep/network-manager-restart 
```
#!/bin/sh
set -e

if [ "$2" = "suspend" ] || [ "$2" = "hybrid-sleep" ]; then
    case "$1" in
        post) sleep 10 ; systemctl restart network-manager ;;
    esac
fi
```
This was because there wasn't any automated way to rescan WiFi-s after wakeup. But this crash happened during a regular session not after a wakeup.

**Comment by KAMI911** [comment]
I tried the script, and yes it crash the CInnamon, every time when I execute.

**Comment by tomc797** [comment]
I am encountering this bug since the release of mint 18.3.

Is there anything I can to do expedite the fix? GDB dumps? Testing patches?

**Comment by ircole** [comment]
Think found my problem.  I recently installed Docker and see some issues in the log regarding Docker and DNS the same time Cinnamon crashes.  Removed Docker and now can restart the network without Cinnamon crashing.

**Comment by attila123** [comment]
This problem still persists. My Cinnamon (3.6.7) crashes in AntergOS (Arch based distro) when I restart NetworkManager (I got here from https://github.com/linuxmint/Cinnamon/issues/7287). Yes, I use docker, and I don't want to uninstall it.
This is a 4 months old issue, please Cinnamon devs try to fix this!

**Comment by chpicolo** [comment]
3.6.7.
The last one found on Software Manager.

**Comment by attila123** [comment]
@chpicolo My problem was probably not related to yours because I use a laptop with integrated Intel graphics. Anyway, glad that you could solve your issue.

**Comment by chpicolo** [comment]
Okay. I did more tests. If I start the computer from cold start then log on - Cinnamon crashes.
But if I log out then log in again in "software rendering" mode (that forces Cinnamon to work properly) then restart the machine, I can log using the default mode without issues on Cinnamon.
It seems that Cinnamon should start in software rendering prior to restart in default mode to work on Intel Graphics.
Perhaps it need to load anything or fill any memory address with any specific value prior to be able to start Cinnamon in default mode properly.

**Comment by attila123** [comment]
@chpicolo What is your kernel version (uname -r)? I also have Intel Graphics in my laptop, I think, but I do not have this problem. So that's why think it may be a driver issue, which may be easily remedied by using a newer kernel. Are you familiar with updating your kernel or can you google that?

**Comment by TC68** [comment]
Hi

Linux Mint 18.3, Cinnamon 3.6.7, kernel 4.13.0-38

I was having this problem as well. Uninstalling Docky seems to have fixed it and I can now restart network-manager without crashing cinnamon. Stability issues with network-manager and my network card are another problem, but is what required me to be restarting network-manager on this machine. It is stable on my other computers.

Side note - I replaced Docky with a second panel and made it transparent - much more stable in general.
