### ISSUE TITLE
Stuck in boot logo and fan at maximum speed.

### ISSUE THREAD

**Issue by AlessandroBusolin** [linuxmint/Cinnamon#7065]
```
 * Cinnamon version (From 3.0.0 to the newest)
 * Distribution - (Linux Mint 18.x)
 *  Intel Corporation Mobile 4 Series  Chipset Integrated Graphics Controller, Intel Core 2 Duo CPU P8800 @ 2.66GHz x 2
 * 64 bit
 ```

**Issue**
Randomly the computer (when it is turning on) stucks in the boot logo and the computer's fan starts working at maximum speed.

**Steps to reproduce**
Unknow, because it appears randomly. (It appears in different Toshiba models)

**Expected behaviour**

**Other information**
With or without the microcode and with or without the kernel update. It seems works fine with other distribution, the issue showing itself only with Mint.

**Comment by leigh123linux** [comment]
Well you issue is before cinnamon even starts.

**Comment by AlessandroBusolin** [comment]
Where can I report the problem?

**Comment by leigh123linux** [comment]
Maybe at launchpad and file it against the kernel, it would also help if you posted some logs.

**Comment by AlessandroBusolin** [comment]
Thanks
