### ISSUE TITLE
Individual Icon resize missing, how do we get it back?

### ISSUE THREAD

**Issue by mckatzenelson** [linuxmint/Cinnamon#7067]
```
 * Cinnamon version (cinnamon --version)
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
 * Graphics hardware *and* driver used
 * 32 or 64 bit
 ```
Version 3.6.2-3.fc26

**Issue**
Previous versions of Cinnamon desktop provided an individual icon resize function in the context menu for each icon.

**Steps to reproduce**
Right click on any icon on the desktop

**Expected behaviour**
Resize should appear in the menu

**Other information**

I understand that this feature was dropped.

How do we petition to get it reinstated?

**Comment by leigh123linux** [comment]
Nemo draws the desktop not cinnamon.

**Comment by leigh123linux** [comment]
If you turn off desktop grid it will enable icon resizing but it's not supported and might have issues.

Type in terminal a normal user.

```
gsettings set org.nemo.desktop use-desktop-grid false
```

**Comment by mckatzenelson** [comment]
Thank you.

Its a little flaky, but serves the purpose.

The size for a soft link in the desktop folder, jumps from to tiny to 
medium to super-huge with nothing in between.  In other words there 
seems to be three sizes, far too small, medium and far too big.

But as I said, it meets the purpose.  I can leave a large icon on my 
desktop for something that I want to draw attention too.

in case it is of interest my use cases are:  (a)control systems, where I 
want to make it clear to a user which application they need to run, and 
(b) for myself as a reminder to return to or start work at a particular 
directory the next day.

**Comment by mckatzenelson** [comment]
Update on that,  resizing icons for individual files works as expected.  
It is only the file folder icon that seems to jump between three preset 
sizes.  Still, as noted before, that's good enough for my purposes.
