### ISSUE TITLE
Cinnamon clock

### ISSUE THREAD

**Issue by mckatzenelson** [linuxmint/Cinnamon#7068]
```
 * Cinnamon version (cinnamon --version)
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
 * Graphics hardware *and* driver used
 * 32 or 64 bit
 ```
Cinnamon desktop 3.6.2-3.fc26

**Issue**
The clock applet fails to process custom date format.   Given any valid format string, it displays two pairs of two digits, one on top of the other.

**Steps to reproduce**

Right click on the date-time in the systray,  select configure, then enable "use a custom date format".

The format string that is present as a default is sufficient to demonstrate the problem.   Optionally, try entering any valid date format string.

**Expected behaviour**
The clock-calendar in systray should display the date-time in the specified format. 

**Other information**

**Comment by leigh123linux** [comment]
Fix has already been released.

https://bodhi.fedoraproject.org/updates/FEDORA-2017-0c42661395
