### ISSUE TITLE
Wrong icon for online accounts

### ISSUE THREAD

**Issue by natanvarga** [linuxmint/Cinnamon#7069]
```
Cinnamon 3.6.5-1.1
Manjaro (Arch)
Intel HD 520
64 bit
 ```
In settings "Online Accounts" has the default icon no matter what icon theme I apply. Icon themes tried do contain an icon for gnome-online-accounts. Looks rather inconsistent and ugly now.

**Comment by JosephMcc** [comment]
We use a standard naming convention for the cinnamon settings icons. In this case `cs-online-accounts`. This was just released so gives themes a bit of a chance to add an icon or link for it.
