### ISSUE TITLE
Request: Individual Interface Scaling Per Monitor

### ISSUE THREAD

**Issue by lehitoskin** [linuxmint/Cinnamon#7070]
```
 * Cinnamon version (cinnamon --version) 3.4.6
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Gentoo
 * Graphics hardware *and* driver used
  - GTX 1080 Ti
  - nvidia-drivers-387.22
 * 32 or 64 bit - 64-bit
 ```

**Issue**
I have one 4K monitor as my main display and a 1080p monitor as my secondary. When I set the user interface scaling to 2x (Hi-DPI), everything on the 1080p monitor is outrageously ballooned. If I set the scaling to normal, everything on the 4K monitor is far too tiny to see. This would be alleviated if there was a way to set the user interface scaling per display, as is possible in Windows.

With such a change, it may be prudent to relocate the user interface scaling from General to Display, which would associate interface scaling to the per-monitor idea more easily.

**Comment by leigh123linux** [comment]
File the request against muffin.

**Comment by lehitoskin** [comment]
Thanks, will do.
