### ISSUE TITLE
Cannot add applets to panel

### ISSUE THREAD

**Issue by mabod** [linuxmint/Cinnamon#7081]
```
 * Cinnamon 3.6.2
 * Manjaro 17.1pre3 Hakoila
 * x86_64 Linux 4.14.2-1-MANJARO
 * GeForce GTX 750 Ti
 ```

**Issue**

Cannot add new applets to panel. 

**Steps to reproduce**
Right click on panel -> Select "Add applet to panel" (Applets zur Leiste hinzufügen) -> Dialog is poping up showing the list of applets, but

-> double clicking on an applet does not do anything
-> there is not "add" button in this dialog.

Several people in the manjaro forum have confirmed the issue: [Manjaro Forum](https://forum.manjaro.org/t/cinnamon-cannot-add-applet-to-panel/35284/5)

I have customiezd panels. I didnt touch the panels for a while now just to realize that it is not working anymore.

**Comment by JosephMcc** [comment]
https://github.com/linuxmint/Cinnamon/issues/7051

You need a newer version of Cinnamon. This has already been fixed.

**Comment by mabod** [comment]
I have the following cinnamon packages installed: 

```
cinnamon 3.6.6-1.1
cinnamon-control-center 3.6.5-1
cinnamon-desktop 3.6.2-1
cinnamon-menus 3.6.0-1
cinnamon-screensaver 3.6.1-1
cinnamon-session 3.6.0-1
cinnamon-settings-daemon 3.6.1-1
cinnamon-sounds 5.5-1
cinnamon-translations 3.6.2-1
cinnamon-wallpapers 20170621-1
manjaro-cinnamon-settings 20171113-1
```
But still I need to resize the dialog to make the Buttons visible. In fact I have to increase just the width of the dialog window. This is inconvenient. And for new cinnamon users I would even say it is annoying.

**Comment by leigh123linux** [comment]
@mabod  post a screenshot

> 
But still I need to resize the dialog to make the Buttons visible. In fact I have to increase just the width of the dialog window. This is inconvenient. And for new cinnamon users I would even say it is annoying.

**Comment by JosephMcc** [comment]
This issue is fixed by https://github.com/linuxmint/Cinnamon/commit/0a4f731578f2ca02aff88f201e6bb293ceba3132. It's up to your distro to get the fixed version to you.
