### ISSUE TITLE
cosmetic issue with Adapta theme and the applet dialog

### ISSUE THREAD

**Issue by mabod** [linuxmint/Cinnamon#7082]
```
 * Cinnamon 3.6.2
 * Manjaro 17.1pre3 Hakoila
 * x86_64 Linux 4.14.2-1-MANJARO
 * GeForce GTX 750 Ti
 * adapta-breath-theme 3.92.1.108-1
 * adapta-gtk-theme 3.92.1.108-1
 * adapta-maia-theme 3.92.1.108-1

 ```

**Issue**
With any of the Adapta themes applied: When in the "applet dialog" and I select one appelt and then I move the mosue over this selected applet the whole entry in the dialog turns white. No text discernible anymore. See the following screenshots:

Selected Applet entry: 

![bildschirmfoto vom 2017-11-26 15-29-48](https://user-images.githubusercontent.com/10911665/33240965-96ca3c8c-d2bf-11e7-94aa-c48161b23551.png)

Mouse over selected entry:

![bildschirmfoto vom 2017-11-26 15-29-45](https://user-images.githubusercontent.com/10911665/33240969-b0dd7382-d2bf-11e7-915c-1627ee3fbbf1.png)

**Other information**

This is issue does not happen in the screensaver dialog which shows a similar entry list but it also does happen in the Extensions dialog.

And I am not sure if this is actually a cinnamon issue or an issue with the Adapta theme. Lets see what the experts say.

**Comment by JosephMcc** [comment]
It's a theme issue. I tried it in several themes including Adwaita, Ambiance, Arc, and Mint-Y and all of them were fine.
