### ISSUE TITLE
Applet Window to small to show buttons

### ISSUE THREAD

**Issue by mabod** [linuxmint/Cinnamon#7083]
```
 * Cinnamon 3.6.6-1.1
 * Distribution -Manjaro 17.1pre3 Hakoila
 * x86_64 Linux 4.14.2-1-MANJARO
 ```

**Issue**

When I open the applet window the buttons do now show. I need to extend the width of the window by some ten pixel.

Applet window as it is created:

![bildschirmfoto vom 2017-11-26 18-34-47](https://user-images.githubusercontent.com/10911665/33242748-dc04476a-d2d9-11e7-8d30-1ce109a63274.png)

Applet window after increasing the width:

![bildschirmfoto vom 2017-11-26 18-35-05](https://user-images.githubusercontent.com/10911665/33242756-e890e34e-d2d9-11e7-8830-74976ce0987c.png)

**Other information**
```
10# pacman -Q | grep cinnamon
artwork-cinnamon-minimal 20170621-2
cinnamon 3.6.6-1.1
cinnamon-control-center 3.6.5-1
cinnamon-desktop 3.6.2-1
cinnamon-menus 3.6.0-1
cinnamon-screensaver 3.6.1-1
cinnamon-session 3.6.0-1
cinnamon-settings-daemon 3.6.1-1
cinnamon-sounds 5.5-1
cinnamon-translations 3.6.2-1
cinnamon-wallpapers 20170621-1
plymouth-theme-manjaro-cinnamon 2.0-4
```

**Comment by leigh123linux** [comment]
Your claim that your running cinnamon-3.6.6 is bullshit as the buttons no longer have text labels

![18-31-01](https://user-images.githubusercontent.com/1299302/33243137-16a9c888-d2d8-11e7-8139-ee10945c1593.jpg)

FTR it was fixed in cinnamon-3.6.4

https://github.com/linuxmint/Cinnamon/commit/0a4f731578f2ca02aff88f201e6bb293ceba3132

**Comment by mabod** [comment]
"[... ] bullshit [...]" --- This is unfriendly. Please consider changing down a gear. 

The cinnamon package has version 3.6.6.
The cinnamon-control-center package has version  3.6.5

These are the two packages I would consider as relevant for this issue. Is that wrong? May be. I am just a user.

**Comment by leigh123linux** [comment]
Cinnamon-settings is part of cinnamon (cinnamon-control-center isn't responsible).
Whatever you distro is distributing as cinnamon-3.6.6  is wrong/broken, you will need to file the issue with them.
