### ISSUE TITLE
 Restart the environment when changing the menu icon

### ISSUE THREAD

**Issue by ghost** [linuxmint/cinnamon#7084]
```
 * Cinnamon 3.6.6
 * Linux Mint 18.3 Sylvia
 * Nvidia g210 M, open source drivers
 * 64 bit
 ```

**Issue**

The problem is to restart the graphical environment by changing the icon to another in the menu item

**Steps to reproduce**

1. Create a new item in the menu, assign an icon and save the changes

2. Download the new icon and overwrite the old one.

3. We go to the item settings, click on the icon, click on the icon and at this point the environment is restarted.

**Expected behaviour**

The overwritten icon should automatically refresh, and you should not restart the environment when changing the icon.

**Other information**

Below you will find information discarded by the new bug reporting program in the new Linux Mint.

https://gist.github.com/anonymous/4b9d7145cc84280b99ae9a5b7b9d4634

**Comment by leigh123linux** [comment]
That isn't how it works, the gtk-update-icon-cache needs to be run to update the icon.

> The overwritten icon should automatically refresh, and you should not restart the environment when changing the icon.
