### ISSUE TITLE
[Online Accounts] Facebook doesn't get recognised as logged in

### ISSUE THREAD

**Issue by feren** [linuxmint/cinnamon#7087]
```
 * Cinnamon version 3.6.6
 * Distribution - Mint 18.3
 * Graphics hardware *and* driver used Intel
 * 32 or 64 bit 64 Bit
 ```

**Issue**

The issue is that Facebook Log in, doesn't get recognised by the Online Accounts Settings Page, so no matter how many times you log in and allow GNOME to access your profile, it'll always says the following in Terminal Output:
`(cinnamon-settings.py:5655): GoaBackend-WARNING **: Did not find email or username in JSON data`

**Steps to reproduce**

Try logging in with a Facebook Account through Online Accounts

**Expected behaviour**

System Settings will recognise the Log In, and would proceed to do whatever Facebook Accounts adds to the Experience of apps.

**Other information**
I originally wasn't going to report this, due to being unsure about it being Upstream, but, this person then also gave information about GNOME doing it fine in this post's comments section: https://plus.google.com/+UnBarbu/posts/cSba5XGiJsw

**Comment by icarter09** [comment]
@feren are you still experiencing this issue?

**Comment by feren** [comment]
I don't use Cinnamon enough to know if this problem still occurs, so I'll close the issue.
