### ISSUE TITLE
Feature Request: Color chooser for themes

### ISSUE THREAD

**Issue by Swiftpaw** [linuxmint/Cinnamon#7091]
Are there any plans to have a more dynamic support for colors and themes?  Right now for example, the Mint-Y theme lacks the color variants that the Mint-X themes enjoy.  If there was an ability to select the "main color" and/or other colors for any theme instead of requiring separate themes, I think that would be a neat feature, and would let you get rid of all those duplicate themes that merely have color differences.

Also, having a "master theme" selector could also be nice, instead of having to go through five different options just to change to a new theme (or new color).

Just some thoughts for you all!  Mint rocks, keep up the great work, love supporting you all! :wolf:

**Comment by JosephMcc** [comment]
> Are there any plans to have a more dynamic support for colors and themes? Right now for example, the Mint-Y theme lacks the color variants that the Mint-X themes enjoy. If there was an ability to select the "main color" and/or other colors for any theme instead of requiring separate themes, I think that would be a neat feature, and would let you get rid of all those duplicate themes that merely have color differences.

This isn't going to happen. There isn't an easy and straightforward way to do that with gtk3 themes. Mint-Y will get color variations at some point.

> Also, having a "master theme" selector could also be nice, instead of having to go through five different options just to change to a new theme (or new color).

Mate does it this way and I really dislike it. Not only that, judging by most of the screenshots I see people post, it seems mixing and matching is what a lot of users like to do.
