### ISSUE TITLE
Cinnamon 3.6.6 crash - _usr_bin_cinnamon.1000.crash

### ISSUE THREAD

**Issue by emeydoubletee** [linuxmint/Cinnamon#7092]
```
 * Cinnamon version 3.6.6
 * Distribution - Mint 18.3
 * Graphics hardware *and* driver used
   Graphics:  Card: NVIDIA GK104 [GeForce GTX 760 OEM] bus-ID: 01:00.0
                    Display Server: X.Org 1.18.4 drivers: nvidia (unloaded: fbdev,vesa,nouveau)
                    Resolution: 1920x1080@60.00hz, 1920x1080@60.00hz
                    GLX Renderer: GeForce GTX 760 (192-bit)/PCIe/SSE2
                    GLX Version: 4.5.0 NVIDIA 384.90 Direct Rendering: Yes
 * 64 bit
 ```

**Issue**
This must be something that occurred silently as there was nothing that I noticed out of the ordinary and I wouldn't have found out about if I didn't open `System Reports`. 

**Other information**
According to [https://gist.github.com/anonymous/089fb7195a4f54c4fd4d7adfce769953](https://gist.github.com/anonymous/089fb7195a4f54c4fd4d7adfce769953), whatever caused it has something to do with the following functions:

- `g_async_queue_pop_intern_unlocked()`
- `g_main_loop_run()`
- `_g_closure_invoke_va()`
- `g_signal_emit_valist()`

I never used hibernate or suspend on my machine.

**Comment by VaGNaroK** [comment]
My also appears this same problem in the system report and cinnamon breaks when I use some programs by wine.
