### ISSUE TITLE
Network Manager applet: wifi rescan gives little indication that it's working

### ISSUE THREAD

**Issue by ghost** [linuxmint/cinnamon#7094]
```
 * Cinnamon version (cinnamon --version) 3.6.6
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 18.3
 * Graphics hardware *and* driver used: Intel on-board graphics with 2.1 Mesa 17.0.7
 ```

**Issue**

The new - and admirable - 'rescan for wireless networks' option - gives no indication that it is working save a slight flicker in the wifi list.

**Steps to reproduce**

Click the option.

**Expected behaviour**

The button should flash or the window should visibly redraw; some sort of (more than negligible) indication should be given that the user's action has been acted upon.

**Other information**

**Comment by icarter09** [comment]
The "rescan for wireless networks" button has been removed. #8891
