### ISSUE TITLE
Controls in sound applet are squeezed

### ISSUE THREAD

**Issue by SethosII** [linuxmint/Cinnamon#7095]
```
Cinnamon 3.6.6
Mint 18.3
Intel HD 520 driver=i915
64 bit
```

**Issue**

Controls in sound applet are squeezed (vertical, most notably with the stop button which looks rectangular not square):

![sound-applet](https://user-images.githubusercontent.com/4445745/33388030-127ebde6-d52f-11e7-9321-49d6083fb37d.jpg)

**Steps to reproduce**

- open a media player
- click on the sound applet
- watch at the controls for the media player

**Expected behaviour**

The buttons should be higher to be properly scaled.

**Other information**

The issue occurred after switching from Mint 18.2 to 18.3 so I guess the new cinnamon version is to blame?

**Comment by clefebvre** [comment]
Thanks.

https://github.com/linuxmint/cinnamon-themes/commit/9ddc135c24d0f33c13b4a2c330ce3dcd851cfd46
https://github.com/linuxmint/Cinnamon/commit/7ea5ec059b131160d5e1df9209033fc683c3e202
