### ISSUE TITLE
Applet descriptions are cut off in cinnamon settings 

### ISSUE THREAD

**Issue by SethosII** [linuxmint/Cinnamon#7096]
```
Cinnamon 3.6.6
Mint 18.3
Intel HD 520 driver=i915
64 bit
```

**Issue**

The letter n is cut of at the end of the descriptions of applets in cinnamon settings. The description is correctly shown in the about page, see red lines in this picture:

![applet-description](https://user-images.githubusercontent.com/4445745/33389074-08bf1000-d532-11e7-8cb8-6106e183bf85.jpg)

**Steps to reproduce**

- open cinnamon settings
- go to applets
- look at the descriptions
- the letter n is cut off at the end of the descriptions

**Expected behaviour**

All of the description should be displayed.

**Other information**

I use the german locale. For english readers: look at the applet `Brightness and gamma applet`. The description of it ends with `screen` and is displayed as `scree` in the cinnamon settings applets page. The issue occurred after switching from Mint 18.2 to 18.3 so I guess the new cinnamon version is to blame?

**Comment by NikoKrause** [comment]
Confirmed

**Comment by NikoKrause** [comment]
Fix pull requested
