### ISSUE TITLE
Dark text on panel

### ISSUE THREAD

**Issue by eudennis** [linuxmint/Cinnamon#7098]
I'm trying to develop a light theme for Cinnamon with light panel. I still didn't find how to change those widget text colors in Cinnamon.css file - calendar and the counter of some applets. Anyone could help? :)

![screenshot from 2017-11-29 17-16-58](https://user-images.githubusercontent.com/1117340/33394430-744c0df4-d529-11e7-99fd-8433ff6ad60e.png)

**Comment by germanfr** [comment]
Try with this:
```css
.applet-label {
	color: #212121;
}
```

I suggest you to **start from** the default **theme** (copy from `/usr/share/cinnamon/theme`) or any other theme for a reference. Also, when you want to tweak something and you don't know the class, what I often do is **looking inside the source** of the applet or Cinnamon itself and search for the _class_ keyword. You can find that in `/usr/share/cinnamon/applets `and in `/usr/share/cinnamon/js/ui` respectively.

**Comment by eudennis** [comment]
Great to know! Now it worked :) Thanks!
