### ISSUE TITLE
Nvidia Prime logo seems stretched at Cinnamon 3.6.6

### ISSUE THREAD

**Issue by Leopard1907** [linuxmint/Cinnamon#7099]
```
 * Cinnamon version : Cinnamon 3.6.6
 * Distribution - Mint 18.3
 * Graphics hardware *and* driver used : Intel HD 630 - Mesa 17.3 - Padoka Stable PPA -- Nvidia GTX 1050 384.98 driver version
 * 64 bit
 ```

**Issue**

Nvidia Prime logo seems stretched at Cinnamon 3.6.6

There is not much provide here honestly. I was on 18.2 Cinnamon and upgraded my system to 18.3 via update manager.

It goes from this , to this. I added the what  change looks like with screenshots.

I'm on a 1920x1080 resulotion , 15.6 inch laptop.

**Steps to reproduce**

Cinnamon 3.6.6 and Nvidia Prime applet

**Expected behaviour**

Back to looking at 18.2's Cinnamon

**Other information**
![assdasdsad](https://user-images.githubusercontent.com/24878978/33395560-03e68a20-d557-11e7-93ab-c37cbb71867c.png)

**Comment by JosephMcc** [comment]
https://github.com/linuxmint/Cinnamon/issues/7086
