### ISSUE TITLE
Increase the size of Taskbar preview windows?

### ISSUE THREAD

**Issue by Lucapz** [linuxmint/Cinnamon#7102]
```
 * Cinnamon version - 3.6.6
 * Distribution - Linux Mint and Debian Cinnamon   64 bit
 * Graphics hardware - Nvidia 
 * 64 bit
 ```

**Issue**

Is it possible Increase the size of taskbar hover thumbnails as they are too small for my elderly Uncles?

Is their a template or something that can be edited?

Thanks

**Comment by JosephMcc** [comment]
I'm assuming you mean this as a feature request to add this functionality? This isn't really meant to be a support forum.

**Comment by Lucapz** [comment]
xenopeek did say to ask on here for feature request , sorry i didn't make that clear in my first post.

**Comment by itzexor** [comment]
I've been working on this for 3.8 in #7134

**Comment by Lucapz** [comment]
@itzexor 

Thank you ever so much , i really appreciate you working on this so quick.

**Comment by itzexor** [comment]
This is in master now.

**Comment by Lucapz** [comment]
Thank you again , you're awesome :)
