### ISSUE TITLE
Disable automatic screen rotation by default

### ISSUE THREAD

**Issue by librucha** [linuxmint/Cinnamon#7104]
Please disable automatic screen rotation in default settings.
I spent a lot of time by searching why my nb frame buffer is rotated each 60 sec.

Thanks

Libor

```
 * Cinnamon version (cinnamon --version)
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
 * Graphics hardware *and* driver used
 * 32 or 64 bit
 ```

**Issue**

**Steps to reproduce**

**Expected behaviour**

**Other information**

**Comment by leigh123linux** [comment]
Use the template next time.

**Comment by JosephMcc** [comment]
This is already done: https://github.com/linuxmint/cinnamon-settings-daemon/commit/af4a9be5beb9088362a7423625dfd5c9a8547f4c
