### ISSUE TITLE
How Do I change the name of workspaces by Bash

### ISSUE THREAD

**Issue by janw-oostendorp** [linuxmint/Cinnamon#7105]
_More a question then an issue, But in the readme I didn't see a support link._

I want to update the names of workspace by bash.

When I run:

    gsettings get org.cinnamon.desktop.wm.preferences workspace-names
    ['0 - Main', 'Project name', 'second project', 'other']

So I try to update that value with:

    gsettings set org.cinnamon.desktop.wm.preferences workspace-names "['0 - Main', 'rename', 'renamew', 'other']"

When I run the `get` afterwords it _does_ return the updated value. But I don't see the labels when I switch workspaces or whatever.

Is this some kind of "array" format that I'm entering wrong?
Or should this be done in a complete different way?

I'm running cinnamon on Ubuntu.

**Comment by NikoKrause** [comment]
I have 4 workspaces. If I want to call them
(1) MusicSpace
(2) DocumentSpace
(3) WORKSPACE 3 (default value)
(4) VideoSpace
the bash command is:
```
gsettings set org.cinnamon.desktop.wm.preferences workspace-names "['MusicSpace', 'DocumentSpace', '', 'VideoSpace']"
```

You have to restart Cinnamon after changing the names with the bash.
