### ISSUE TITLE
No RBGA Order options for moden panels in Font Settings

### ISSUE THREAD

**Issue by Redsandro** [linuxmint/Cinnamon#7107]
```
 * Cinnamon version 3.4.6
 * Distribution - Mint 18.3 x64
 ```

**Issue**

There are no _RBGA Order_ options for moden panels (Pentile, RGBG, OLED etc) in _Font Settings_.

Options:

![image](https://user-images.githubusercontent.com/1702193/33443115-0fda3e94-d5f7-11e7-92f5-7bb5c9a006cc.png)

Lenovo ThinkPad X1 Yoga OLED panel:

![image](https://user-images.githubusercontent.com/1702193/33443403-c5f87092-d5f7-11e7-8fe4-aa0dac18682c.png)

**Comment by leigh123linux** [comment]
fontconfig doesn't support these new methods

https://cgit.freedesktop.org/fontconfig/tree/src/fcname.c#n174

https://github.com/linuxmint/cinnamon-settings-daemon/blob/master/plugins/xsettings/csd-xsettings-manager.c#L573

If you want these new methods you will need to file an upstream request to  https://bugs.freedesktop.org/buglist.cgi?bug_status=__open__&no_redirect=1&order=Importance&product=fontconfig&query_format=specific

**Comment by Redsandro** [comment]
@leigh123linux would it be interesting to track the progress of upstream Harmony in this (or another) issue? The subpixel rendering does seem to improve.

Cinnamon issue #7107 (this page) < [fontconfig issue #106219](https://bugs.freedesktop.org/show_bug.cgi?id=106219) < [freetype2 issue #53749](https://savannah.nongnu.org/bugs/?53749)

**Comment by Lanchon** [comment]
FYI, the [2025 Lenovo Yoga 14"](https://psref.lenovo.com/Detail/Yoga_7_2_in_1_14AKP10?M=83JR0002US) with the 1920x1200 OLED panel keeps using a similar layout.

> 14" WUXGA (1920x1200) OLED 600nits (peak) / 400nits (typical) Glossy / Anti-fingerprint, 100% DCI-P3, 60Hz, Dolby Vision®, TÜV Low Blue Light, DisplayHDR™ True Black 500, Glass, OGM, 10-point Multi-touch

![Image](https://github.com/user-attachments/assets/a4dfde7e-f65c-42a7-a26a-bee6ecbd0124)
