### ISSUE TITLE
When setting date/time AM/PM indicator is missing when in 12 hour mode

### ISSUE THREAD

**Issue by TopView** [linuxmint/cinnamon#7108]
* Cinnamon version 3.2.7
 * Distribution - Debian Stretch 9.2
 * Graphics hardware *and* driver used: AMD/ATI RV710/M92 [Mobility Radeon HD 4530/4570/545v]
 * 64 bit

**Steps to reproduce**
Menu
System settings
Date & time
Unlock
Under Format, make sure 'Use 24h clock' is disabled,

**Expected behavior**
In Settings, the currently set AM or PM (or am/pm) should be displayed to the right of the hour:minute up/down adjusters.

**Comment by rizado** [comment]
https://github.com/linuxmint/Cinnamon/issues/6703 - the same problem? As I understood, AM/PM displays only for locales where 12-hour mode is default...

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
