### ISSUE TITLE
Menu applet width bug when pressing arrow keys

### ISSUE THREAD

**Issue by bastimeyer** [linuxmint/Cinnamon#7109]
```
 * Cinnamon version: 3.6.6
 * Distribution: Antergos
 * xf86-video-intel
 * 64 bit
 ```

**Issue**

The width of the popup of the default menu applet (menu@cinnamon.org) seems to be influenced by the X-coordinate of the mouse cursor when navigating through the menu via the arrow keys.
Having the mouse cursor inside the popup is working correctly, but when the menu is set to the left hand side of the screen and the mouse cursor has been moved to the right hand side, the width of the popup increases as soon as the first arrow up/down key is being pressed after opening the menu. When the cursor is touching the edge of the screen, favorite icons become smaller and start to disappear (when using the Adapta theme).

**Steps to reproduce**

1. Bottom panel
2. Menu applet on the left
3. Mouse cursor on the far right
4. Open menu via hotkey (eg. Super_L)
5. Press arrow up/down key
6. Menu width gets huge

**Other information**

This issue has occured in one of the recent patches from a couple of days ago (I just upgraded an hour ago). The overall issue is theme independent, as I've tested it with Adapta and the default cinnamon theme. The icons were only disappearing when using Adapta, probably because of some different spacing configuration.

```bash
$ pacman -Qo /usr/share/cinnamon/applets/menu@cinnamon.org/applet.js
/usr/share/cinnamon/applets/menu@cinnamon.org/applet.js is owned by cinnamon 3.6.6-1
```

**Comment by itzexor** [comment]
This should be fixed in the next release. Thanks for the report.
