### ISSUE TITLE
High cpu usage when moving mouse

### ISSUE THREAD

**Issue by Trevinlc1997** [linuxmint/cinnamon#7112]
*  Cinnamon 3.6.6
 * Fedora 27
 * Intel HD 4000 (i5-3317U CPU)
 * Intel Corporation 3rd Gen Core processor Graphics Controller (rev 09)

 * 64 bit

Just cinnamon uses really high CPU usage when I move my mouse around, below shows

**Steps to reproduce**
Shake your mouse like a mad man, or simply move it.

![screenshot from 2017-12-01 06-49-44](https://user-images.githubusercontent.com/24485362/33483552-f8344222-d663-11e7-919d-f71356ba9e44.png)

**Other information**
I don't think if this is helpful but heres my glxinfo.

[log.txt](https://github.com/linuxmint/Cinnamon/files/1521638/log.txt)

**Comment by leigh123linux** [comment]
I don't see much increase when moving the mouse.

![27](https://user-images.githubusercontent.com/1299302/33485063-e5cbe61a-d69c-11e7-8848-bbb4e054cfc0.jpg)

**Comment by gitman0** [comment]
i have the same issue. it goes to 29% just like your screenshot.

* Cinnamon 4.0.8
* Fedora 28
* Intel Core i7-8550U CPU
* Intel UHD Graphics 620 GPU

**Comment by wcork** [comment]
hate to resurrect this but, I have seen it too. When moving mouse over desktop as well.

**Comment by icarter09** [comment]
Linux Mint 192.
Cinnamon 4.2.4

I'm not able to reproduce this issue. Moved the mouse around a lot and saw no increase in the CPU usage.
