### ISSUE TITLE
System Settings Control Centre and Welcome Screen should behave the same way as Nemo when clicking icons 

### ISSUE THREAD

**Issue by EvoEvz** [linuxmint/Cinnamon#7113]
Linux Mint Cinnamon 18.3 Sylvia 64 bit

By default icons and files are double clicked to open them. The mouse is a pointer when items can be double clicked in this way. This behavior can be changed to single click in Nemo under Preferences / Behavior. The mouse turns into a hand when items can be single clicked.

When you open the System Settings Control Centre or the Welcome Screen, it does not matter what option is selected in Nemo (single or double click) the pointer always remains an arrow and the icons only ever open with a single click. I have seen a few new users try and double click on something on the Welcome screen because it looks like it's a double click only to be frustrated that it opens twice.

If the pointer is an arrow I expect to have to double click. In System Settings I find new users would double click and actually change a setting without knowing. The best example I can give is the Effects icon. Double click on that and you will almost definitely change a setting without knowing.

The behavior in System Settings Control Centre and the Welcome screen should reflect the same as Nemo when it comes to clicking. It should be consistent across the OS to avoid confusion.

Anyway it's a small issue but I feel this would be quite frustrating for users trying to learn Linux Mint.

Hopefully this can be resolved in a later release.

Many thanks

**Comment by leigh123linux** [comment]
This is the intended behaviour and isn't going to change.

**Comment by EvoEvz** [comment]
Ok well it's just a little confusing for new users. I wouldn't have thought it would be too hard to turn the pointer into a hand when hovering over icons in System Settings Control Centre and Welcome Screen. Anyway it was just a suggestion to make things a little more user friendly and consistent. Thanks.
