### ISSUE TITLE
power applet spamming log file with error message on laptop

### ISSUE THREAD

**Issue by jrsrjrsr** [linuxmint/cinnamon#7114]
```
 * Cinnamon version 3.6.6
 * Distribution - Mint 18.3
 * 64 bit
 ```

**Issue**
The power applet (power@cinnamon.org/applet.js) keeps printing messages like this to my ~/.cinnamon/glass.log file:

error t=2017-12-02T15:57:03.735Z /org/freedesktop/UPower/devices/battery_BAT0:=Sanyo DELL 00

Further, this happens every few minutes as the applet status changes.

**Steps to reproduce**
Occurs during normal operation on laptop.

**Expected behaviour**
This log message should only occur if there is really an error.  

**Other information**
I believe that the command that creates the error (Line 129:  global.logError(alias);) should really be located within the catch clause of the code above it.  That is, lines 128 and lines 129 should be swapped.  

The way the code is now, the logError() command occurs on every call to this code.  With the above swap of lines, it would only get called if the alias is malformed.

Hopefully, one of the maintainers can simply make this change; I do not know how to do so myself.

**Comment by icarter09** [comment]
Closing. PR that contained the fix was merged.
