### ISSUE TITLE
Cinnamon crash conistantly after last system update on Fedora 26 !

### ISSUE THREAD

**Issue by Nokia808** [linuxmint/Cinnamon#7120]
Hi. I'm on Fedora 26 X64 bit Cinnamon edition. Few minutes ago I updated my system receiving last 11 new update packages from Fedora repositories. They include new Cinnamon, Lightdm, & slickgreeting packages.

I updated from tty terminal. But after that my Cinnamon crash conistantly at each boot saying "Cinnamon crashed. It run now in fallback mode. Do you like to restart it". I tried to restart it but same crash reoccur !!

I tried to restart system from tty terminal but same error occur !! 

Please your kind help ! 

Now I'm on Cinnamon 3.6.6 10.fc26, Lightdm 1.25.0 1.fc26, & slick-greeter 1.1.3 1.fc26

Best.

**Comment by leigh123linux** [comment]
Post some logs showing the error otherwise I will have to close as insufficient info is provided.

**Comment by Nokia808** [comment]
Hi. Thank you very much for your kind rapid response.

Please just give me the commands for logs that you need so as to perform them & supply you by them.

Waiting your instructions !

**Comment by leigh123linux** [comment]
Attach  boot.txt 

```
journalctl -b0 >> boot.txt
```

**Comment by Nokia808** [comment]
I run this command. But I have 2 problems:

1) where can I obtained this "boot.txt", i.e: where it saved ??

2) HOW CAN I NAVIGATE TO IT'S LOCATION USING GUI ??? I do not see icon of "File" that can be clicked to see my home folders ....... 

Please I'm unfamiliar with this situation ! I did not pass before by such condition !

**Comment by Nokia808** [comment]
I can navigate using GUI by launching "nemo" from terminal:
$ nemo

Just now I remember this !

But where boot.txt file located

**Comment by leigh123linux** [comment]
The command dumps the the in the current directory

Run this as non root and it will be in your home user directory
```
cd ~
journalctl -b0 >> boot.txt
```

**Comment by Nokia808** [comment]
I found it. It was inside my home directory but I did not notice it due to 1) I did not think that it will stored inside home, but in folders located beyond home, 2) because I have a lot of files inside my home, so I did not see it .....

Take it. I attached it here.
[boot.txt](https://github.com/linuxmint/Cinnamon/files/1527247/boot.txt)

**Comment by leigh123linux** [comment]
You have a faulty monitoring applet installed causing the crash

```
Dec 04 11:46:34 localhost.localdomain systemd-coredump[1894]: Process 1562 (cinnamon) of user 1000 dumped core.
                                                              
                                                              Stack trace of thread 1562:
                                                              #0  0x00007fbd13440e51 _g_log_abort (libglib-2.0.so.0)
                                                              #1  0x00007fbd13441e8c g_log_default_handler (libglib-2.0.so.0)
                                                              #2  0x00007fbd1344211d g_logv (libglib-2.0.so.0)
                                                              #3  0x00007fbd1344228f g_log (libglib-2.0.so.0)
                                                              #4  0x00007fbce80725b1 _check_symbols (libnm-util.so.2)
                                                              #5  0x00007fbd1b77ad93 n/a (n/a)
```

**Comment by leigh123linux** [comment]
see https://bugzilla.redhat.com/show_bug.cgi?id=1517046

**Comment by Nokia808** [comment]
Thank you very much ! The problematic factor was a desklet called "simple-system-monitor@ariel".

I already filed it a bug report just few minutes about this issue.

**Comment by echin3** [comment]
Hi all! I am running into the same issue - cinnmon 3.6.6 on Fedora 25 (will be upgrading to 26 soon). I've basically removed all applets from the applet folder and some from the ~/.cinnamon/configs folder but it's still crashing. Any ideas? I see on cinnamon-spices an applet that was recently updated too (https://cinnamon-spices.linuxmint.com/applets/view/79) I moved it to my Desktop temporarily but no luck after a reboot.. ideas?

**Comment by leigh123linux** [comment]
@echin3 can you post some logging

**Comment by echin3** [comment]
Thanks!!
[boot.txt](https://github.com/linuxmint/Cinnamon/files/1532260/boot.txt)

**Comment by pmcneil** [comment]
Same as echin3 updated fedora 25 with cinnamon 3.6.6-10 and cinnamon crashes into fallback mode.

Dec 07 22:04:11 vserv2.nerderg.com audit[2333]: ANOM_ABEND auid=1000 uid=1000 gid=1000 ses=3 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 pid=2333 comm="cinnamon" exe="/usr/bin/cinnamon" sig=6 res=1
Dec 07 22:04:11 vserv2.nerderg.com abrt-hook-ccpp[2611]: Process 2333 (cinnamon) of user 1000 killed by SIGABRT - dumping core
[boot.txt](https://github.com/linuxmint/Cinnamon/files/1538800/boot.txt)
[systemInfo.txt](https://github.com/linuxmint/Cinnamon/files/1538802/systemInfo.txt)

I have also deleted the applets etc. from configs, and even removed the .cinnamon and .local/share/cinnamon, updated the NVidia driver, and re-installed cinnamon 3.6.6 - same problem.

**Comment by leigh123linux** [comment]
@pmcneil 

See

https://github.com/linuxmint/Cinnamon/issues/7122

**Comment by h0wdyd3wdy** [comment]
Hello,

I'm having this same problem.  It's been happening for several versions.  Please see attached log.

I'm not sure how to fix it?


[cinnamon-core-dump.txt](https://github.com/linuxmint/Cinnamon/files/1716177/cinnamon-core-dump.txt)

**Comment by echin3** [comment]
@h0wdyd3wdy, see #7122. I just upgraded to 27 and that was resolved, otherwise, I'm sure you can disable all of your 3rd party applets and pull the latest update for 25 f
