### ISSUE TITLE
Cinnamon consistent failing into fallback mode after update

### ISSUE THREAD

**Issue by echin3** [linuxmint/Cinnamon#7122]
Cinnamon 3.6.6 on Fedora 25 64 bit

Within the last few days, after a normal dnf upgrade, Cinnamon upgraded to 3.6.6. After this, trying to boot into my cinnamon desktop fails. Looks similar to issue #7120. Tried removing all applets from ~.local/share/cinnamon/applets and restarting computer, it still fails. I've also made a new user to try to copy over a default configuration over but even a new user fails to log into cinnamon normally.

Update to 3.6.6, have some faulty 3rd party applets, crash, try to remove applets from folder, restart, still crash.

Expected behavior is to be able to boot normally.

Similar to https://github.com/linuxmint/Cinnamon/issues/7120

Thank you guys!

**Comment by zerog2k** [comment]
i also have same issue. just started with recent dnf update a day or so ago...

```
Dec 05 16:02:36 possiblesoon-dl.mydomain cinnamon[11165]: JS LOG: Cinnamon started at Tue Dec 05 2017 16:02:36 GMT-0600 (CST)
Dec 05 16:02:37 possiblesoon-dl.mydomain tracker-extract[11183]: unable to create file '/run/user/1000/dconf/user': Permission denied.  dconf will not work properly.
Dec 05 16:02:37 possiblesoon-dl.mydomain /usr/libexec/gdm-x-session[10867]: openGL version 3.1 detected (GL3 Cogl Driver)
Dec 05 16:02:38 possiblesoon-dl.mydomain nemo-desktop[11211]: Allocating size to NemoWindowPane 0x5556863b6430 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
Dec 05 16:02:38 possiblesoon-dl.mydomain /usr/libexec/gdm-x-session[10867]: **
Dec 05 16:02:38 possiblesoon-dl.mydomain /usr/libexec/gdm-x-session[10867]: Cjs:ERROR:gi/object.cpp:632:bool object_instance_resolve_no_info(JSContext*, JS::HandleObject, bool*, ObjectInstance*, char*): assertion failed: (g_base_info_get_type(base_info) == GI_INFO_TYPE_INTERFACE)
Dec 05 16:02:38 possiblesoon-dl.mydomain audit[11165]: ANOM_ABEND auid=1000 uid=1000 gid=1000 ses=63 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 pid=11165 comm="cinnamon" exe="/usr/bin/cinnamon" sig=6 res=1
Dec 05 16:02:38 possiblesoon-dl.mydomain abrt-hook-ccpp[11438]: Process 11165 (cinnamon) of user 1000 killed by SIGABRT - dumping core
Dec 05 16:02:42 possiblesoon-dl.mydomain abrtd[922]: Size of '/var/spool/abrt' >= 1000 MB (MaxCrashReportsSize), deleting old directory 'ccpp-2017-12-05-15:54:54-9466'
```

I think it's related to this
Cjs:ERROR:gi/object.cpp:632:bool object_instance_resolve_no_info(JSContext*, JS::HandleObject, bool*, ObjectInstance*, char*): assertion failed: (g_base_info_get_type(base_info) == GI_INFO_TYPE_INTERFACE)
I've seen the other reports which state that it could be due to some bad cinnammon applets.
I'm not sure all of the possible places to check for cinnamon applets. I have looked here, but dont see any:
```
$ ls -tR .local/share/cinnamon
.local/share/cinnamon:
desklets  search_providers  applets  extensions

.local/share/cinnamon/desklets:

.local/share/cinnamon/search_providers:

.local/share/cinnamon/applets:

.local/share/cinnamon/extensions:

```

**Comment by leigh123linux** [comment]
@besser82  Is the anything we can do before F25 goes EOL?

```
Cjs:ERROR:gi/object.cpp:632:bool object_instance_resolve_no_info(JSContext*, JS::HandleObject, bool*, ObjectInstance*, char*): assertion failed: (g_base_info_get_type(base_info) == GI_INFO_TYPE_INTERFACE)
Aborted (core dumped)
```

**Comment by besser82** [comment]
@echin3 @zerog2k I'm on it to find a solution…

**Comment by leigh123linux** [comment]
@echin3 @zerog2k can you guys confirm removing the network applet from the panel using cinnamon-settings fixes the issue?

**Comment by MrHolle** [comment]
@leigh123linux I had the same problem after last fc25 update and removing the network applet solved the issue

**Comment by besser82** [comment]
@zerog2k @MrHolle You can find the fixed build for Cinnamon on Fedora 25 [on Bodhi](https://bodhi.fedoraproject.org/updates/FEDORA-2017-182e210fc5).  It will propagate to the regular updates repo within the next few days…

**Comment by echin3** [comment]
@besser82 @leigh123linux thanks! While upgrading to FC27 is what I ended up doing, I was able to spin up a VM, reproduce this issue and confirm the fix. Thank you!

**Comment by zerog2k** [comment]
Thanks all +1
