### ISSUE TITLE
Crash when installing CrossOver Linux 17.0.0 over 16.5.0

### ISSUE THREAD

**Issue by ovari** [linuxmint/Cinnamon#7123]
```
 * Cinnamon version: 3.6.6
 * Distribution: Mint 18.3
 * Graphics hardware *and* driver used: Intel Corporation Atom Processor Z36xxx/Z37xxx Series Graphics & Display
 * 64 bit
 ```

**Issue**
Installing CodeWeavers CrossOver Linux 17.0.0 over 16.5.0

**Steps to reproduce**
1. Download CrossOver Linux 17.0.0 downloaded from https://www.codeweavers.com/
2. Install 'crossover_17.0.0-1.deb' using GDebi Package Installer
3. Cinnamon crashes

**Expected behaviour**
No crash

**Other information**
[crash.tar.gz](https://github.com/linuxmint/Cinnamon/files/1533038/crash.tar.gz)

**Comment by clefebvre** [comment]
Closing as there is no stacktrace.
