### ISSUE TITLE
Show number of available updates in Settings>Applets>Download

### ISSUE THREAD

**Issue by sphh** [linuxmint/Cinnamon#7128]
```
 * Cinnamon version (cinnamon --version) 3.6.6
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 18.3 Cinnamon 64-bit
 ```

**Issue**

The previous version of `Settings>Applets` showed the number of available updates, whereas the new version (Mint 18.3) does not show them anymore.

**Steps to reproduce**

1. Start `Settings>Applets`
2. Switch to `Download`
3. `Refresh`
4. If there are any new applets, `Update all` becomes active, but does not show the number of available updates.

**Expected behaviour**

I would like to see the number of available updates somewhere. Another option would be to have a filter which shows only the updateable applets. (Thinking of it, that might be even the better option.)

**Other information**

The same behaviour might be found in `Settings>Desklets` and `Settings>Extension`, but I could not test it, because there were no updated desklets/extension.

**Comment by NikoKrause** [comment]
@collinss The number could be shown in the tooltip.

**Comment by NikoKrause** [comment]
@sphh For now you can sort by date. All applets with updates will appear at the top.

**Comment by collinss** [comment]
@NikoKrause sorting by date will show all recently updated applets, not just the ones installed. Unless you have every applet installed, sorting by 'Installed' should actually yield better results in most cases.
