### ISSUE TITLE
Adopting some of the GNOME animations and effects?

### ISSUE THREAD

**Issue by orschiro** [linuxmint/Cinnamon#7129]
Dear all, 

Recently I took a look at the latest GNOME release and some of their animations are very modern and pleasing, like the F11 full screen effect. 

Something that would greatly fit Cinnamon, too. :-) 

Is there any way we can take some of those animations, like the F11 and adopt it in Cinnamon?

**Comment by JosephMcc** [comment]
Thanks for the request. This is an area I plan to look into a bit.
