### ISSUE TITLE
There is no searchbar in overview mode

### ISSUE THREAD

**Issue by ashed** [linuxmint/cinnamon#7131]
```
 * Cinnamon version (cinnamon --version) - 2.8.8
 * Distribution - (Mint 17.3)
 * Graphics hardware *and* driver used xserver-xorg-video-nouveau v.1:1.0.10-1ubuntu2
 * 64 bit
 ```

**Issue**
There is no searchbar in overview mode

**Steps to reproduce**

**Expected behaviour**
Have a searchbar in overview mode to search title of opened app

**Other information**

**Comment by leigh123linux** [comment]
Can you try cinnamon-3.6.x as 2.8.8 is EOL

**Comment by icarter09** [comment]
@collinss any update on this ticket?

**Comment by collinss** [comment]
This sounds like a feature request to me.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
