### ISSUE TITLE
Why is so long time to shut down - 90 sec

### ISSUE THREAD

**Issue by HBartolin** [linuxmint/Cinnamon#7132]
```
 * Cinnamon 3.6.6
 * Mint 18.3
 * 64 bit
 ```

**Issue**
Is takes 90 sec when I go from user screen Menu -> Quit -> Shut Down. When I go from user screen Menu -> Logout -> Log Out it takes 1.5 sec and then Quit... -> Quit... -> Shut Down it takes 3 sec, witch is 4.5 sec in total.

**Expected behaviour**
Why is so different in time, 90 sec vs. 4.5 sec?

**Comment by Mek101** [comment]
Do you have the steam client installed?

**Comment by HBartolin** [comment]
I have it, I uninstalled it and nothing regarding elapsed time has happen. Still 90 s.

**Comment by ManIVIctorious** [comment]
Glad to hear your problem is resolved, but since it doesn't seem to be a cinnamon issue could you please close it?
