### ISSUE TITLE
Feature Enhancement - Improve the Open File Dialog box system wide

### ISSUE THREAD

**Issue by phd21** [linuxmint/Cinnamon#7133]
Dear Linux Mint Developers and contributors,

Feature Enhancement - Improve the Open File Dialog box system wide

First, thank you for providing all the wonderful editions of Linux Mint. I am not sure if this is the appropriate place to post this feature request or enhancement.

This would apply to any version of Cinnamon, Mate or Xfce.

I keep seeing posts on the Mint forums and elsewhere, where people trying to upload images to various websites (ebay, image sites, etc...) using various browsers cannot preview the images, or icons of them, which makes that very difficult. In my Linux Mint KDE systems the open file dialog box has always had the ability to preview images and other files, and the ability to adjust icon sizes with a slider, etc... This is true of most browsers installed on my KDE systems as well.  This would be good for the file managers as well. Can you please add these options to Cinnamon, Mate, and Xfce? You might even be able to use the code from KDE (open source), to make that easier to implement.

Thank you.

Best regards to all of you and yours,
Phil
phd21
![openfiledialog1](https://user-images.githubusercontent.com/6324548/33787820-0ca77d76-dc3d-11e7-8a7b-26401da83565.jpg)

**Comment by leigh123linux** [comment]
The Open File Dialog box system wide is part of GTK3 not cinnamon.

**Comment by phd21** [comment]
So where can I post the request for GTK3?

**Comment by leigh123linux** [comment]
Try launchpad or gnome bug tracker
