### ISSUE TITLE
Failed to install theme from the spices

### ISSUE THREAD

**Issue by germanfr** [linuxmint/Cinnamon#7135]
```
 * Cinnamon version 3.6.2
 * Distribution - Arch
 ```

**Issue**
Some themes fail to install, resulting in an error message that says:
> An error occurred during the installation of _${uuid}_. Please...
> Details: [Errno 2] No such file or directory: '/tmp/.../_${uuid}_'

I don't know the code enough to fix it, but I think the error comes from [here](https://github.com/linuxmint/Cinnamon/blob/60faa201c48a183a2f0630897a65d45ff6662f13/files/usr/share/cinnamon/cinnamon-settings/bin/Spices.py#L620). It is trying to copy the folder named with the theme _UUID_, but the problem is that **the folder inside `files/` doesn't match its _UUID_**. This seems to affect only themes, as there are no other xlets that meet this requirement currently in your servers.

**Expected behaviour**
I see three possible solutions:
 * If I'm right the _UUIDs_ for themes are provided by your server, so you could check that there.
 * Alternatively, check that once the cache is downloaded.
 * Fix the themes.

**Other information**
The following themes are affected:
```
Ambiance-Minty
Android-Holo
Blue-mint
CBlack
ChromeOS
Discreet-Flat
Faience
Spearmint-Leaf
Tyr-himinn
Tyr-jord
Vivaldi-ZorinOS
Windows-10
```
Here's a script to test affected themes:
```bash
#!/bin/bash
for f in *; do
	if [ -d "$f" ] && [ ! -d "$f/files/$f" ]; then
		echo "'$(ls $f/files/ | head -1)' doesn't match its UUID ($f)"
	fi
done
```

**Comment by NikoKrause** [comment]
Hey,
@nyrrad fixed this here: https://github.com/linuxmint/cinnamon-spices-themes/pull/292

Can you check. It seems to work here.

**Comment by germanfr** [comment]
I cannot check it right now, as the certificate seems to be broken (also on the website)
```
An error occurred while trying to access the server. Please try again in a little while.

Details: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)>
```

But yeah, that would work for now. The thing is that it could happen again in the future, but I guess that's up to the Mint team to have any check in their servers so that they provide the right uuid or something.

**Comment by nyrrad** [comment]
The servers are synced to the corresponding repos. This should be a pretty uncommon occurrence, hopefully.

**Comment by germanfr** [comment]
Well, I'll close this since it's already fixed and it isn't really a Cinnamon issue.
