### ISSUE TITLE
GTX1060 bad stuttering

### ISSUE THREAD

**Issue by gpujunkie** [linuxmint/Cinnamon#7136]
```
 * Cinnamon version - 3.6.6
 * Distribution - Arch Linux
 * Nvidia GTX 1060 with Nvidia Proprietary 387.34 from the Arch Repo
 * 64 bit
 ```

**Issue**
System freezes every few seconds for about half a second. Mouse cursor is unaffected.

**Steps to reproduce**
Use the system in any way

**Expected behaviour**
A smooth system, free of stuttering.

**Other information**
It is especially noticeable in games and while watching YouTube videos.

**Comment by leigh123linux** [comment]
Your issue doesn't reproduce here using 387.34 driver.

**Comment by MartinX3** [comment]
I can reproduce it.
Linux Mint 19 x64 Cinnamon
3.8.8
GTX 940MX
Nvidia 390 and 396

After the computer reach a certain temperature, the stuttering starts.
But it doesn't stop after laptop cools down.
Sound, 3D and Mouse are unaffected.
Only the desktop and 2D games are affected.

After logout and login, the bug stops and all is smooth again.
While logging of I get a "wait for cinnamon-session-manager to stop" message.

While it hangs ONE cpu thread reachs 100%

**Comment by MartinX3** [comment]
@leigh123linux
Still happening with Linux Mint 19.1 & Cinnamon 4
Graphics drivers 415.25-0ubuntu0~gpu18.04.1
