### ISSUE TITLE
Make possible to search in Toggle Scale or Windows Quick List

### ISSUE THREAD

**Issue by saaj** [linuxmint/cinnamon#7137]
Feature request
=============
It'll be really useful to search-as-you-type existing windows. Search interface can be similar to the search field in Menu applet or System Monitor. I see two possible place to implement this.
1) Toggle Scale (windows of current workspace)
2) Windows Quick List applet (all windows); would also need a hot key to activate

**Comment by icarter09** [comment]
@collinss any update on this issue or can the ticket be closed?

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
