### ISSUE TITLE
Fulscreen application on the second monitor always gets focus

### ISSUE THREAD

**Issue by LeosBitto** [linuxmint/cinnamon#7138]
```
 * Cinnamon 3.6.6
 * Mint 18.3
 * Intel HD Graphics 620
 * 64 bit
 ```
I have two monitors with a fullscreen application running on the second monitor. I do most of my work on the first monitor and I don't like the current behaviour which gives the focus to the fullscreen application on the second monitor every time I quit any application on the first monitor. I would expect the focus to be given to the most recently used application, which is exactly what happens without the fullscreen application on the second monitor. Examples of such fullscreen applications are VirtualBox, Remmina or Firefox (simply press F11).

**Comment by icarter09** [comment]
@LeosBitto is this a feature request or a bug?
