### ISSUE TITLE
Cinnamon desktop artifacts after new files are created/moved

### ISSUE THREAD

**Issue by nick-s-b** [linuxmint/Cinnamon#7139]
```
 * Cinnamon version (cinnamon --version)
Cinnamon 3.6.6
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
Arch
 * Graphics hardware *and* driver used
Nvidia 387.34
 * 32 or 64 bit
64bit 
```

**Issue**
After a new file is created on the desktop, there's some artifacting as you move your mouse around. It's a minor issue but it's annoying.
![https://i.imgur.com/bZqeR0L.png](https://i.imgur.com/bZqeR0L.png)

**Steps to reproduce**
Create a new file or move a new file that doesn't have an icon preview created onto the desktop. For example, here's a video of what happens when I create a new screenshot of the desktop:

![artifact](https://thumbs.gfycat.com/DapperPoisedIndochinesetiger-size_restricted.gif)
https://gfycat.com/gifs/detail/DapperPoisedIndochinesetiger

Then just hover your mouse over it after the preview was created. Artifacts disappear after you click the icon.

**Comment by leigh123linux** [comment]
Nemo draws the desktop.

**Comment by nick-s-b** [comment]
@leigh123linux Really? When Nemo dies, the desktop does not go away. I think that Nemo *used to* draw the desktop but it doesn't anymore. Can you please confirm this because I'd hate to file a bug in nemo tracker and it's a Cinnamon bug.

**Comment by JosephMcc** [comment]
Yes. Nemo handles it. The desktop handling is now just a separate process.
