### ISSUE TITLE
Gwenview loses decorations

### ISSUE THREAD

**Issue by jmgomezpoveda** [linuxmint/cinnamon#7140]
```
 * Cinnamon version 3.4.6-1
 * Distribution - Ubuntu 17.10
 * Intel HD 4600, Linux 4.13.0-19.22
 * 64 bit
 ```

**Issue**
After being in full screen mode, Cinnamon stops showing the title bar. The upstream developers have determined that this is an issue in the compositor (https://bugs.kde.org/show_bug.cgi?id=384925).

**Steps to reproduce**
1. Open an image in Gwenview.
2. Double click in the image to get into full screen.
3. Exit Gwenview.
4. Open Gwenview again.

**Expected behaviour**
The Gwenview application appears with its title bar.

**Other information**

**Comment by leigh123linux** [comment]
Your issue doesn't reproduce in cinnamon-3.6.6 using gwenview-17.08.1, feel free to reopen if you can reproduce using cinnamon-3.6.x (3.4.x is EOL).

**Comment by jmgomezpoveda** [comment]
I just upgraded to Cinnamon 3.6.6.1~artful0 and the issue also happens with the new version.

**Comment by leigh123linux** [comment]
And the gwenview version?

**Comment by icarter09** [comment]
@jmgomezpoveda are you still experiencing this issue?

**Comment by jmgomezpoveda** [comment]
Apologies, I can't confirm this, as I don't have Cinnamon installed anymore. Feel free to close the issue if it is not happening in your system.

**Comment by icarter09** [comment]
@jmgomezpoveda no worries and thanks for the update.
