### ISSUE TITLE
Please change text: update to refresh

### ISSUE THREAD

**Issue by to-ba** [linuxmint/Cinnamon#7143]
```
 * Cinnamon ≤ 3.6.6
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) all
 ```

**Issue**
In the panel applet for mintupdate you can use »Update« but in mintupdate is the text for the same function »Refresh«.

**Steps to reproduce**
Right click on the mintupdate icon in the panel.
Open mintupdate and have a look at the third button in the toolbar.

**Expected behaviour**
The text in the panel applet should also be »Refresh«.
Please change the text from »update« to »refresh«.
Users can think they are updating the system instead of refreshing/updating the repositories.

**Comment by leigh123linux** [comment]
Closed.

File it against the correct package.

https://github.com/linuxmint/mintupdate/issues
