### ISSUE TITLE
Cinnamon nightly for Fedora

### ISSUE THREAD

**Issue by SteveEbey73742** [linuxmint/Cinnamon#7144]
I would like to be able to test cinnamon on my Fedora 27.  Do you have a way to get nightly for Fedora?

**Comment by JosephMcc** [comment]
Sorry this isn't really the place for this type of support question. You would probably be better off asking on a Fedora forum.

**Comment by leigh123linux** [comment]
@besser82 Is it possible to automate copr for this?

**Comment by besser82** [comment]
@leigh123linux Well, one could do that…  I just need to come up with a plan for this, since we would need commit hooks in the linuxmint repos and all…

**Comment by leigh123linux** [comment]
@besser @clem might be able to help with the hooks
