### ISSUE TITLE
Audio problem with Firefox and Mint Cinnamon 18.3

### ISSUE THREAD

**Issue by signmeuptoo** [linuxmint/Cinnamon#7145]
```
 * Cinnamon version (cinnamon --version)
3.6.6
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
Mint 18.3
 * Graphics hardware *and* driver used
On die video: Intel 4690K Cpu
 * 32 or 64 bit
64 bit
 ```

**Issue**
When starting ANY youtube or any other audio item in firefox 57.0.1 the System Settings -> Sound -> Applications -> Firefox volume setting resets to ZERO. Even if FF is kept running, every time a youtube or other audio ends and a new item is chosen (new instance or not new instance, either), the volume for the afformentioned setting resets to ZERO and until I slide the slider back up, no audio is heard. This problem doesn't happen when using another browser such as Chromium. I have jack audio set to work, but it doesn't appear to be a jack audio problem because if Jack is disabled, it still happens.

**Steps to reproduce**
Install GNU/Linux Mint 18.3 Cinnamon, open firefox, go to youtube, and try and play any audio or video, volume starts at zero (firefox volume setting, not main volume), and keeps resetting to zero.

**Expected behaviour**
that the firefox volume should reappear with whatever setting was previously set, whether it be 0, 50, or 100 percent, NOT reset to zero by default.

**Other information**
Also, front headphones was not working on ASUS Z97 Pro motherboard audio until QasMixer was installed and that jack was manufally enabled (no settings appears with the stock Mint install).

**Comment by pyroxar** [comment]
Sorry. I couldn't reproduce this bug. Can you attach some images?
