### ISSUE TITLE
Laggy desktop envroiment after upgrade to 18.2/18.3 (only with NVIDIA Drivers)

### ISSUE THREAD

**Issue by Simonmicro** [linuxmint/Cinnamon#7146]
1) Appears under: Linux Mint 18.3 Sylvia
2) Appears after: Upgraded to 18.2 / 18.3 (both has the problem) and bring up the additional drivers from nvidia again.
3) Issue: The whole cinnamon desktop works directly after startup normally - But after switching to the nvidia-card and give it 2 minutes, the desktop (without the mouse) freezes every second for a shot period of time. Not bad if I do some officework, but inside a game or at youtube (only in windowed mode) VERY annoying!
4) Expected: No freezes like under Cinnamon 18.1.
5) How often?: Always if the NVIDIA-Card is selected (prime-select used) and the cinnamon-desktop used (under lxde the bug disappears).

NVIDIA 384 - I guess?
MSI GP60 2QE
NVIDIA 940m
Intel 4900HD - I guess?

**Comment by leigh123linux** [comment]
You have a nvidia issue not cinnamon.

**Comment by Simonmicro** [comment]
Sure? And why? After restart cinnamon (troubleshoot->restart cinnamon) the bug temorarly disappears. And the bug isn't existing under LXDE.
Sorry for my questions, but I want to know where specifically the bug is, so i can the the source by myself (and all the online How-to-fix-it doesn't work).

**Comment by leigh123linux** [comment]
LXDE would run fine with a nvidia issue as it's only 2D un-accelerated DE, Cinnamon needs 3D acceleration to function.
Try filing the issue against nvidia-prime at launchpad
