### ISSUE TITLE
Security - Bypass lock screen 

### ISSUE THREAD

**Issue by Gudio** [linuxmint/Cinnamon#7147]
```
 * Cinnamon version 3.4.6
 * Distribution Ubuntu 17.10
 * Graphics hardware *and* driver used GTX 860M nvidia-387
 * 64 bit
 ```

**Issue**
Plugging HDMI cable into the device with lower resolution on the lock screen and unplugging allows bypass the lock screen

**Steps to reproduce**
https://youtu.be/xN_cZHftL50

**Expected behaviour**
Lock screen should be kept

**Other information**
n/a

**Comment by leigh123linux** [comment]
Duplicate of https://github.com/linuxmint/cinnamon-screensaver/issues/246
