### ISSUE TITLE
Cinnamon 3.6 flashes after login on Lenovo P50 with nouveau driver

### ISSUE THREAD

**Issue by mielecmichal** [linuxmint/Cinnamon#7148]
```
 * Cinnamon version: 3.6.2
 * Distribution: Manjaro
 * Graphics hardware *and* driver used: Lenovo P50 noveau driver
 * 64 bit
 ```

**Issue**
I experience weird flashing after login in default mode. To fix this I have to reboot multiple times and after few tries it works normally, also software rendering mode works correctly.

**Here is video showing the problem:** https://youtu.be/E2IKETifGWs
**StackExchange containing lspci -v** : https://unix.stackexchange.com/questions/411571/cinnamon-3-6-flashes-after-start-on-lenovo-p50-with-nouveau-driver

**Steps to reproduce**
1. Install Manjaro with noveau driver on Lenovo P50 docked to docking station and plugged to 2 external monitors.
2. Turn on computer (lightdm works correctly)
3. Login to Cinnamon in default mode (not software rendering)
4. In 60% cases you see flashing cinnamon

**Expected behaviour**
Cinnamon should not flash :)

**Other information**
To make 2 monitors works correctly from unknown reasons I have to plug one by DVI to docking station and second one by HDMI directly to notebook port. Only then both monitors works..

**Comment by leigh123linux** [comment]
Your issue is caused by nouveau.
