### ISSUE TITLE
Mint can't Install to USB as primary HDD

### ISSUE THREAD

**Issue by jawhelan** [linuxmint/Cinnamon#7150]
```
 * Cinnamon version (cinnamon --version)
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
 * Graphics hardware *and* driver used
 * 32 or 64 bit
 ```

**Issue**
Got  a laptop with no HDD, wanted to install to the USB as primary drive for full install.

Mint will not see or install to usb

**Steps to reproduce**

boot to live usb with destination usb in other port.

**Expected behaviour**

should see the usb and install

**Other information**

was able to install lilbuntu, Lxle, pepermint and xbuntu? but not mint,    on dell latitude E5450

**Comment by leigh123linux** [comment]
File your non-cinnamon issue against ubiquity

https://github.com/linuxmint/ubiquity
