### ISSUE TITLE
Screen tearing taking place while screen capturing

### ISSUE THREAD

**Issue by zbandhan** [linuxmint/Cinnamon#7151]
```
 * Cinnamon version (3.6.6)
 * Distribution - (Mint 18.3)
 * Graphics: Card: Intel 2nd Generation Core Processor Family Integrated Graphics Controller
   bus-ID: 00:02.0
   Display Server: X.Org 1.18.3 drivers: intel (unloaded: fbdev,vesa)
   Resolution: 1366x768@60.07hz
   GLX Renderer: Mesa DRI Intel Sandybridge Mobile
   GLX Version: 3.0 Mesa 11.2.0 Direct Rendering:
 * 64 bit
 ```

**Issue**
can't capture video in Linuxmint 18.3 Cinnamon. Huge screen tearing problem is taking place with Kazam and OBS software that I have used to do that task.

I've tried to solve it with Clutter variable but no luck. :(
```
CLUTTER_PAINT=disable-clipped-redraws:disable-culling
CLUTTER_VBLANK=True
```

**Comment by leigh123linux** [comment]
You haven't proved it's a cinnamon issue, perhaps your hardware isn't up to running obs or Kazam + cinnamon.
I tried it here with obs and it works fine.
