### ISSUE TITLE
Caribou layout (keus and language)

### ISSUE THREAD

**Issue by joaojotta** [linuxmint/Cinnamon#7156]
```
 * cinnamon 3.6.7
 * Arch
 * Intel graphics
 * 64 bit
 ```

**I've set the on-screen keyboard to the bottom but now I can't see the options anywhere. I just can't find options to change the keyboad layout (keys and language)-**

How can I edit a config file? Is there one?

Thanks

**Comment by leigh123linux** [comment]
This isn't a cinnamon issue

https://wiki.gnome.org/Projects/Caribou/NewLayout
