### ISSUE TITLE
Desktop icon grid spacing and sizing issue.

### ISSUE THREAD

**Issue by ayanb1991** [linuxmint/Cinnamon#7159]
```
 * Cinnamon version (3.6.6)
 * Distribution - (Mint 18.3)
 * Intel
 * 64 bit
 * Resolution 1366 X 768
 ```

**Issue**
1. Desktop icon grid with icon size set to small needs more spacing. 
2. Making desktop icons small,  font-size of the icon label getting reduced.  (Should maintain the Desktop font- size from font-settings regardless whatever the desktop icon size).
3. If desktop icon label is big, text not wrapping to next line .

**Comment by leigh123linux** [comment]
Nemo draws the desktop icons not cinnamon.
