### ISSUE TITLE
font rendering issues

### ISSUE THREAD

**Issue by ayanb1991** [linuxmint/cinnamon#7160]
```
 * Cinnamon version (3.6.6)
 * Distribution - (Mint 18.3)
 * Intel
 * 64 bit
 * Resolution 1366 X 768 
 ```

**Issue**
Font rendering with default settings looks very dull in Linux Mint.  Can it be improved? Ubuntu fonts renders better than Noto Sans. Is it a font issue or any other anti aliasing setting that have to be improved. 

**Other information**
Cantarell fonts renders so well on fedora gnome.
Tried Overpass on xfce and it looked great.

**Comment by truesarang** [comment]
you can install latest freetype and it will look much better

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
