### ISSUE TITLE
Icons not selectable

### ISSUE THREAD

**Issue by lucamosca1** [linuxmint/Cinnamon#7165]
```
 * Cinnamon version (3.6.6 - Installed from embrosyn repo)
 * Distribution - (Ubuntu 16.04 64bits)
 * Graphics hardware *and* driver used
 * Intel Corporation 4th Gen Core Processor Integrated Graphics Controller (rev 06)
 * driver=i915
 * External monitor used as primary
 ```

When session starts
- I'm able to select any Icon I want on my desktop
Then I open a folder with double click
- I'm not able anymore to select and click on icons, if I double click on an icon, the action is reflected to a different ones (the one below or upper). It seems some icons are just drawed on desktop background.

**Other information**
Issue NOT reproducible with live session of linux mint 18.3

**Comment by JosephMcc** [comment]
Like your other issue this is probably an issue with Nautilus handling the desktop. Not a Cinnamon issue.
