### ISSUE TITLE
Desktop background not shown before doubleclick on a folder

### ISSUE THREAD

**Issue by lucamosca1** [linuxmint/Cinnamon#7166]
```
 * Cinnamon version (3.6.6 - Installed from embrosyn repo)
 * Distribution - (Ubuntu 16.04 64bits)
 * Graphics hardware *and* driver used
 * Intel Corporation 4th Gen Core Processor Integrated Graphics Controller (rev 06)
 * driver=i915
 * External monitor used as primary
 ```
When session starts
- I see no desktop wallpaper, just a black panel
Then I open a folder with double click
- The desktop backgound magically appear

**Other information**
Issue NOT reproducible with live session of linux mint 18.3

**Comment by pyroxar** [comment]
I haven't any bug like this. Maybe it isn't Cinnamon error but xserwer bugs on your hardware. If you want to check this to try to install arch Linux with cinnamon and tell us did you have this bug again. 
If you are a newbie you try to install manjaro.
https://manjaro.org/community-editions/

**Comment by lucamosca1** [comment]
Not reproducible with manjaro cinnamon live, tried now.

**Comment by pyroxar** [comment]
Can you install Manjaro on your hardware? Secondly, did you use Ubuntu with installed additionally cinnamon desktop on it or did you use Linux Mint cinnamon official release?

**Comment by lucamosca1** [comment]
Sorry but it's my working pc and I cannot reinstall OS. To resume
Ubuntu with additional ppa - Issue
Mint cinnamon live and manjaro live - No Issue

**Comment by JosephMcc** [comment]
This isn't a Cinnamon issue. The file manager has nothing to do with the desktop background. This sounds more like an issue with allowing Nautilus to handle the desktop.
