### ISSUE TITLE
Network manager has spurious networks listed

### ISSUE THREAD

**Issue by mcarans** [linuxmint/cinnamon#7167]
```
 * Cinnamon version (cinnamon --version)
3.6.7
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
Mint 18.3
 * Graphics hardware *and* driver used
Issue is with: USB-C hub with ethernet
 * 32 or 64 bit
64
 ```

**Issue**
![network](https://user-images.githubusercontent.com/3799212/34294399-a8e5e51c-e708-11e7-9e2e-880c567d8e3c.png)

The network applet initially shows just the "Wired" (and wireless) connection, but after a while 2 other connections show up "Ethernet" and "Realtek USB 10/100/1000 LAN". 

Commands like sudo lshw -C Network and ifconfig only show one ethernet network.

Unplugging and replugging the hub shows just the "Wired" connection.
 
**Steps to reproduce**
Leave Mint running for a while

**Expected behaviour**
Only the "Wired" connection should show.

**Other information**

**Comment by mcarans** [comment]
I see this in xsession-errors

```
Cjs-Message: JS LOG: Cinnamon started at Fri Dec 22 2017 08:22:48 GMT+0100 (CET)
Cjs-Message: JS LOG: network applet: Cannot find connection for active (or connection cannot be read)
Cjs-Message: JS LOG: network applet: Cannot find connection for active (or connection cannot be read)
openGL version 4.5 detected (GL3 Cogl Driver)
MetaSyncRing disabled: couldn't find required GL extensions, or the minimum safe openGL version was not met
failed to create drawable
Cjs-Message: JS LOG: Invalid network device type, is 13
Cjs-Message: JS LOG: Invalid network device type, is 14
Cjs-Message: JS LOG: network applet: Found connection for active
Cjs-Message: JS LOG: network applet: Found connection for active

(nm-applet:2467): nm-applet-CRITICAL **: get_menu_item_for_ap: assertion 'dup_data.hash != NULL' failed

(nm-applet:2467): nm-applet-CRITICAL **: get_menu_item_for_ap: assertion 'dup_data.hash != NULL' failed

(nm-applet:2467): nm-applet-CRITICAL **: get_menu_item_for_ap: assertion 'dup_data.hash != NULL' failed
```

**Comment by leigh123linux** [comment]
Post the output for this command after the second network appears

```
nmcli d
```

**Comment by mcarans** [comment]
I haven't seen this error since doing `modprobe -r cdc_ether` so that only by rtl8152 driver module is loaded, so will close for now.

**Comment by mcarans** [comment]
Issue has happened again. I ran the command @leigh123linux suggested:

```mcarans@Holly ~ $ nmcli d
DEVICE           TYPE      STATE        CONNECTION         
docker0          bridge    connected    docker0            
enx4ce173476d9a  ethernet  connected    Wired connection 1 
wlp58s0          wifi      unavailable  --                 
lo               loopback  unmanaged    --           ```

**Comment by icarter09** [comment]
Linux Mint 19.2
Cinnamon 4.2.4

I'm unable to reproduce this issue. 

@mcarans are you still experiencing this issue?

**Comment by mcarans** [comment]
I haven't seen this error for some time so will close.
