### ISSUE TITLE
Sudden and intermittent sound issues with Pulseaudio on 18.3 Cinnamon

### ISSUE THREAD

**Issue by emeydoubletee** [linuxmint/Cinnamon#7171]
**Cinnamon version (cinnamon --version)**

3.6.7

**Distribution - (Mint 17.2, Arch, Fedora 25, etc...)**

Mint 18.3

**Graphics hardware _and_ driver used**

    Graphics:  Card: NVIDIA GK104 [GeForce GTX 760 OEM] bus-ID: 01:00.0
               Display Server: X.Org 1.18.4 drivers: nvidia (unloaded: fbdev,vesa,nouveau)
               Resolution: 1920x1080@60.00hz, 1920x1080@60.00hz
               GLX Renderer: GeForce GTX 760 (192-bit)/PCIe/SSE2
               GLX Version: 4.5.0 NVIDIA 384.90 Direct Rendering: Yes

**32 or 64 bit**

64

**Issue**

One thing that I've noticed with 18.3 Cinnamon is that there's a prevalent
sudden intermittent loss of sound that I have never experienced with previous
versions. I've experienced it in the beta version while testing. But, I have
noticed that it still exists on the stable version even _after_ a clean
install.

**VLC Error output**

Audio output failed:
The audio device "default" could not be used:
Connection refused.

**Steps to reproduce**

The only step involved is opening VLC and playing audio/video.

**Reproduces How Often**

This happens suddenly and intermittently with no apparent triggers apart from
opening and closing of VLC.

I would have to run the script at least 3 to 4 times a day to temporarily resolve the issue.

**Workaround**

`Pavucontrol` is installed and it doesn't do anything to prevent sudden loss of sound.

The only workaround that works temporarily to resolve the issue is a script containing the following lines:

```sh
#!/usr/bin/env bash

pulseaudio -k
sudo alsa force-reload
```

![cli](https://user-images.githubusercontent.com/33206161/34401108-6ff036f8-eb55-11e7-9045-e89f50f7b190.gif)

**Expected behaviour**

No sudden or intermittent loss of sound

**Other information**

`.cinnamon/glass.log` **output**

    info t=2017-12-26T19:47:28.633Z Cinnamon.AppSystem.get_default() started in 88 ms
    info t=2017-12-26T19:47:28.637Z loading user theme: /usr/share/themes/Mint-Y-Dark/cinnamon/cinnamon.css
    info t=2017-12-26T19:47:28.654Z added icon directory: /usr/share/themes/Mint-Y-Dark/cinnamon
    info t=2017-12-26T19:47:28.732Z PlacesManager: Updating devices
    info t=2017-12-26T19:47:28.751Z loaded at Tue Dec 26 2017 12:47:28 GMT-0700 (MST)
    info t=2017-12-26T19:47:28.761Z Loaded applet systray@cinnamon.org in 8 ms
    info t=2017-12-26T19:47:28.991Z Loaded applet menu@cinnamon.org in 229 ms
    info t=2017-12-26T19:47:29.001Z Loaded applet show-desktop@cinnamon.org in 9 ms
    info t=2017-12-26T19:47:29.084Z Role locked: panellauncher
    info t=2017-12-26T19:47:29.085Z Loaded applet panel-launchers@cinnamon.org in 83 ms
    info t=2017-12-26T19:47:29.103Z Loaded applet window-list@cinnamon.org in 18 ms
    info t=2017-12-26T19:47:29.127Z Loaded applet keyboard@cinnamon.org in 23 ms
    info t=2017-12-26T19:47:29.136Z Role locked: notifications
    info t=2017-12-26T19:47:29.139Z Loaded applet notifications@cinnamon.org in 11 ms
    info t=2017-12-26T19:47:29.150Z Loaded applet removable-drives@cinnamon.org in 10 ms
    info t=2017-12-26T19:47:29.173Z Loaded applet user@cinnamon.org in 22 ms
    info t=2017-12-26T19:47:29.224Z Loaded applet network@cinnamon.org in 50 ms
    info t=2017-12-26T19:47:29.246Z Loaded applet power@cinnamon.org in 21 ms
    info t=2017-12-26T19:47:29.274Z Loaded applet calendar@cinnamon.org in 27 ms
    info t=2017-12-26T19:47:29.315Z Loaded applet sound@cinnamon.org in 40 ms
    info t=2017-12-26T19:47:29.337Z Loaded applet weather@mockturtl in 22 ms
    info t=2017-12-26T19:47:29.353Z Loaded applet workspace-switcher@cinnamon.org in 14 ms
    info t=2017-12-26T19:47:29.353Z AppletManager.init() started in 602 ms
    info t=2017-12-26T19:47:29.355Z Cinnamon took 823 ms to start
    info t=2017-12-26T19:47:29.890Z Hiding systray: network
    info t=2017-12-26T19:47:29.891Z Adding systray: redshift (24x24px)
    info t=2017-12-26T19:47:33.300Z Adding systray: blueberry-tray.py (24x24px)
    info t=2017-12-26T19:47:48.454Z Adding systray: mintupdate.py (24x24px)
    info t=2017-12-26T19:48:05.086Z PlacesManager: Updating devices
    info t=2017-12-26T20:32:27.610Z Hiding systray: vlc
    info t=2017-12-26T20:33:31.863Z Hiding systray: vlc
    info t=2017-12-26T20:39:16.442Z Hiding systray: vlc

**Screenshot**

Sound settings **before** the script is run

![sound_settings](https://user-images.githubusercontent.com/33206161/34401092-4b17f320-eb55-11e7-9905-e4cec5c8e82f.png)

Sound settings **after** the script is run
![sound_settings_after](https://user-images.githubusercontent.com/33206161/34401106-687334b6-eb55-11e7-8355-083be13d4ea1.png)

**Opening VLC**

![vlc](https://user-images.githubusercontent.com/33206161/34401076-2a462d06-eb55-11e7-8f9d-16bfa5a7fefb.gif)

**Comment by leigh123linux** [comment]
You will need to file the issue against pulseaudio of nvidia driver if it's HDMI.
