### ISSUE TITLE
Cinnamon does not support to switch to use a modem to connect to the Internet.

### ISSUE THREAD

**Issue by pyroxar** [linuxmint/Cinnamon#7173]
```
 * Cinnamon version (3.6.7)
 * Distribution - Mint 18.3
 ```

**Issue**
Cinnamon in system settings and network applet doesn't enable to switch to use a modem to connect to the Internet.

**Steps to reproduce**
Try to use a modem.

**Expected behaviour**
You can use the modem to connect to the Internet in easy graphics way.

**Other information**
Mate DE in Linux Mint has this feature.
![cinnamon does not show modem2](https://user-images.githubusercontent.com/23406555/34454586-bc668a76-ed6e-11e7-8e00-78bc3908c255.png)

![mate shows a modem2](https://user-images.githubusercontent.com/23406555/34454581-b34fe036-ed6e-11e7-88c2-21d3bcc54b44.png)

**Comment by leigh123linux** [comment]
The GUI window isn't part of the cinnamon code, it's nm-connection-editor.
As far as cinnamon it has 'mobile broadband' function.

![screenshot from 2018-02-12 18-44-18](https://user-images.githubusercontent.com/1299302/36113611-4783fac0-1025-11e8-8f7c-e7d220a225da.png)


Check that ModemManager is installed and the service is running.
