### ISSUE TITLE
 Can't copy the system information with information about a system in cinnamon settings.

### ISSUE THREAD

**Issue by pyroxar** [linuxmint/Cinnamon#7174]
```
 * Cinnamon version (3.6.7)
 * Distribution - (Mint 18.3)
 ```

**Issue**
Cinnamon system settings in information about the system do not allow to copy primary information in the labels.

**Steps to reproduce**
Try to copy a text in a label.

**Expected behaviour**
You should be able to copy this information for your comfort.

**Other information**
![inform](https://user-images.githubusercontent.com/23406555/34467169-68e5c386-eee9-11e7-8b61-f756112f6f52.png)

**Comment by JosephMcc** [comment]
Submitted a PR to implement this.
