### ISSUE TITLE
Ability to add a program to menu from window list?

### ISSUE THREAD

**Issue by orschiro** [linuxmint/cinnamon#7176]
Dear all, 

I was just facing this situation and recall that Ubuntu with Unity has/had a feature to easily add an "unknown" program to the menu by right mouse click on the left launcher panel icon.

In my case I ran a snap package for which there is no entry in the menu. Obviously, running the snap from the command line is inconvenient. 

I would find it logical and a sensible enhancement if I could do a right mouse click on the entry of the program in the window list and then select an option to add this program to the menu.

In my concrete example:

1. Right mouse click on "Writefull"
2. Select the option "Add to menu"

What do you think?

![image](https://user-images.githubusercontent.com/170947/34510688-7bc85b9e-f056-11e7-80b6-3f481ed7422c.png)

**Comment by pyroxar** [comment]
Yes. It's good idea.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
