### ISSUE TITLE
Text typed into gnome-terminal ends up in box on bottom-right of screen

### ISSUE THREAD

**Issue by CottonEaster** [linuxmint/Cinnamon#7177]
```
 * Cinnamon version (cinnamon --version) 3.6.7.
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 18.3
 * 32 or 64 bit: 64
 ```

**Issue**

Occasionally - often enough to irk -  text typed when gnome terminal ends up in box on bottom-right of screen.

**Steps to reproduce**

1. Open gnome terminal.
2. Click pointer outside terminal window.
3. Type some text.

**Expected behaviour**

Either the text should appear within the terminal and not in a strange box or at least there should be some explanation of the box. (I consulted an experienced Mint user, and he'd seen the box and didn't understand it either.)

**Other information**

It's hard to capture information about the box - about the process that runs it - because it disappears upon clicks. Nor does the box appear to _do_ anything.

**Comment by leigh123linux** [comment]
The box in box on bottom-right of screen is part of nemo.

https://github.com/linuxmint/nemo/issues/1073
