### ISSUE TITLE
Directly remove menu favourite with a right mouse click on the icon

### ISSUE THREAD

**Issue by orschiro** [linuxmint/Cinnamon#7178]
Dear all, 

I would like to suggest the following minor improvement to directly remove a favourite from the menu with a right mouse click. 

Looking forward to your thoughts.

![image](https://user-images.githubusercontent.com/170947/34552004-e1a8741c-f11e-11e7-9fdd-d05a88c92a10.png)

**Comment by NikoKrause** [comment]
Using rightclick to delete favorites would probably result in a lot of accidentally removed favorites. Having a right click menu in the favorites was discussed in the past. It would look ugly.

You have different choices:
(1) Right click menu in the applicationsbox, you can add/remove favorites there.
(2) Drag Favorite and Drop it over the Categories/Applications. I've implemented that the cursor changes to a pointing hand, to indicate, that you can remove favorites with Drag&Drop. I just realized, that this has broken in Cinnamon 3.6, i.e. the cursor doesn't change. I created a PR to fix this.
(3) You can use the Delete button (DEL) on your keyboard.

**Comment by NikoKrause** [comment]
You can read the discussion here: https://github.com/linuxmint/Cinnamon/issues/4000
