### ISSUE TITLE
Notifications don't respect user specified timeouts

### ISSUE THREAD

**Issue by tanderson-google** [linuxmint/Cinnamon#7179]
```
Cinnamon 3.4.6
Debian testing
 ```

**Issue**

Cinnamon should respect user-defined timeouts on notifications. https://developer.gnome.org/notification-spec/

A timeout of 0 should make a notification stay-on-screen, and a positive value specifies the screen-time in ms.

It looks like Cinnamon does try to respect the user timeout:
https://github.com/linuxmint/Cinnamon/blob/b1e0bc3921e9392518e92ec27b70362fcbb3549d/js/ui/notificationDaemon.js#L322
But the implementation has a bug because it doesn't seem to work.

**Steps to reproduce**

1. Launch Google Chrome
2. Enable native notifications by navigating to chrome://flags and setting #enable-native-notifications to "Enabled". Restart Chrome
3. Visit https://tests.peter.sh/notification-generator/#requireInteraction=true and click on "Display the notification"
Edit: These steps won't work any more because Chrome now sets the urgency to 2 (critical) to workaround the issue.

**Expected behaviour**

The notification should stay on the screen, but times out after ~5s.

**Comment by clefebvre** [comment]
This is by design.
