### ISSUE TITLE
Cinnamon can automatically modify the preferred application when new application is installed

### ISSUE THREAD

**Issue by s101d1** [linuxmint/Cinnamon#7180]
```
 * Cinnamon version (cinnamon --version): 3.6.7-1
 * Distribution: Antergos (Arch Linux)
 * Graphics hardware *and* driver used: Intel HD Graphics 5500
 * 32 or 64 bit: 64 bit
 ```

**Issue**
Cinnamon can automatically set preferred application to newly installed application. 

For example, after installing git-cola, the preferred application for "File Manager" was changed from Nemo to git-cola. This could produce misunderstanding for unsuspecting user, thinking the new installed application is messing the system.

**Steps to reproduce**
1. Install git-cola
2. Press `Super + E` shortcut key to launch file manager.
3. It will launch git-cola instead rather than the Nemo file manager.

**Expected behaviour**
Cinnamon should not set or change preferred application automatically when new application is installed. The preferred application setting should always be controlled or set manually by user.

**Comment by leigh123linux** [comment]
Perhaps Arch should set some defaults 

http://pkgs.fedoraproject.org/cgit/rpms/cinnamon-desktop.git/tree/x-cinnamon-mimeapps.list

@eli-schwartz

**Comment by s101d1** [comment]
So are you implying the arch linux package script should not modify the preferred application setting?

**Comment by leigh123linux** [comment]
@s101d1 No!

**Comment by eli-schwartz** [comment]
See for example https://bugs.archlinux.org/task/35528

This is not the fault of Arch Linux, rather the fault of XDG standards; essentially, unless you specify your preferred applications for every single mimetype, the system defaults will be used... but the system defaults are randomly selected via CSPRNG. And then re-selected every time the update-desktop-database command is re-run (which is normally done by your distro package manager whenever any software is installed which provides desktop files).

As @leigh123linux suggested, the proper solution (well, more of a bandaid over xdg which will probably never get fixed) would be for cinnamon to provide a desktop-environment specific mimeapps.list to provide sane system defaults for core functionality like the file browser.

But I think it would be best if Cinnamon itself provided this minimal mimeapps.list containing desktop-critical functionality, likely just the nemo.desktop stuff. Arch could ship that, and other distros which set more defaults could add their own additional definitions.
It is unarguable that every distro could use nemo as the default inode/directory handler when running Cinnamon as the current desktop. :smile:

**Comment by leigh123linux** [comment]
@clem ^^
