### ISSUE TITLE
Duplicate panel icons

### ISSUE THREAD

**Issue by ghost** [linuxmint/cinnamon#7181]
```
 * Cinnamon version (cinnamon --version) 3.6.7
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 18.3
 * 32 or 64 bit: 64
 ```

**Issue**

![image](https://user-images.githubusercontent.com/9998846/34635408-ccf03078-f286-11e7-9907-156436aa780b.png)

**Steps to reproduce**

Unknown. Occurs occasionally and, I think, with different applets.

**Other information**

If you tell me how to investigate with e.g. LookingGlass, then I will.

**Comment by icarter09** [comment]
Closing this issue since the original submitter of this ticket is no longer present on Github.
