### ISSUE TITLE
Cinnamon crash by NetworkManager

### ISSUE THREAD

**Issue by joeoo** [linuxmint/Cinnamon#7182]
```
 * Cinnamon 3.6.7

 * Arch
 * NVIDIA Driver Version: 340.104 GeForce 9800 GT                         
 * 64 bit multilib
 ```

For about six months now I have been struggling with this fucking problem of a NetworkManager, which every time with any sneeze throws X with the error Invalid MIT-MAGIC-COOKIE-1
And any GUI applications lost connect to X and can't run.

> Any service which run NetworkManager or itself

Log example:

```

Cjs-Message: JS LOG: Invalid network device type, is 14
Cjs-Message: JS LOG: Removing a network device that was not added

(cinnamon:58224): Clutter-CRITICAL **: clutter_layout_manager_get_child_meta: assertion 'CLUTTER_IS_LAYOUT_MANAGER (manager)' failed
Cinnamon warning: Log level 8: g_object_set: assertion 'G_IS_OBJECT (object)' failed
Cinnamon warning: Log level 8: g_object_set: assertion 'G_IS_OBJECT (object)' failed

(cinnamon:58224): Clutter-CRITICAL **: clutter_layout_manager_get_child_meta: assertion 'CLUTTER_IS_LAYOUT_MANAGER (manager)' failed
Cinnamon warning: Log level 8: g_object_set: assertion 'G_IS_OBJECT (object)' failed
Cinnamon warning: Log level 8: g_object_set: assertion 'G_IS_OBJECT (object)' failed
Cjs-Message: JS LOG: Invalid or null signal handler id used when attempting to .disconnect from an object.
== Stack trace for context 0x557b8f301000 ==
overrideGObject/GObject.Object.prototype.disconnect@/usr/share/cinnamon/js/ui/overrides.js:101:13
MyApplet.prototype._syncActiveConnections@/usr/share/cinnamon/applets/network@cinnamon.org/applet.js:1978:17
MyApplet.prototype._updateIcon@/usr/share/cinnamon/applets/network@cinnamon.org/applet.js:2216:13

Cjs-Message: JS LOG: NetworkManager is not running, hiding...

```

VideoProof:

[test.mp4.zip](https://github.com/linuxmint/Cinnamon/files/1608786/test.mp4.zip)
[mirror](https://transfer.sh/Z6hYi/test.mp4)

**Comment by leigh123linux** [comment]
I don't see how we can fix your issue here if Arch has fucked networkmanager, maybe disable the network applet till they fix it in Arch.

@eli-schwartz

**Comment by eli-schwartz** [comment]
Seems to be https://bugs.archlinux.org/task/56619

**Comment by leigh123linux** [comment]
@eli-schwartz shame the backtrace has missing symbols, the step to reproduce doesn't trigger anything here.

**Comment by eli-schwartz** [comment]
We're working on that, believe it or not!

But I hit a fatal blocker when trying to recompile with debug symbols myself. I can reliably get cinnamon to stop crashing if I try running a newly compiled js38 with debug symbols.
