### ISSUE TITLE
Cinnamon/Nemo 3.6 breaks desktop icons order

### ISSUE THREAD

**Issue by rizado** [linuxmint/Cinnamon#7183]
```
 * Cinnamon 3.6.x
 * Mint 18.3
 * Intel I915, default driver
 * 64 bit
 ```
**Issue**
Cimmanon 3.6 doesn't save icons placement for desktop. v. 3.4 works properly. Problem exists even on clean (just installed) system.

**Steps to reproduce**
1. Install Linux Mint Cinnamon 18.3.
2. Try to order desktop icons (dpn't use default order).
3. Logout and login again.
4. See icons order.

**Expected behaviour**
Icons position must be as I sorted.

**Other information**
Laptop model - Asus X75A TY117D.

**Comment by leigh123linux** [comment]
Nemo draws the desktop not cinnamon.
