### ISSUE TITLE
number of recent files

### ISSUE THREAD

**Issue by gabrielfern** [linuxmint/cinnamon#7185]
Hey, i'm looking for how to increase the number of recent files from 20 to whatever i want, the best would be if we had a option at privacy (system settings) as we have for the days we want the files to keep, i keep here this as a feature request (it would be awesome).

But, where can i edit to get the number that i want (some constant in a javascript file maybe)?

We can see the recent files at mint menu and the applet recent files, i think the two gets the info from the same source, right? the applets are:
menu@cinnamon.org
recent@cinnamon.org

I'm using linux mint 18.3 cinnamon

**Comment by itzexor** [comment]
The const that sets this is here: https://github.com/linuxmint/Cinnamon/blob/067e1dabe369ceb72de7558b1d63af826f748f8a/js/misc/docInfo.js#L14

It is set to 20 due to performance issues with a large number of recents when they change and force updates. It's probably not going to change on our end for the foreseeable future.

**Comment by gabrielfern** [comment]
@itzexor If you open a folder that is on desktop, it will appear at recent files in the menu, but if you go to the recent:/// path in nemo, it will not appear at there. If you open a folder with nemo windowed this will not appear as a recent file in the menu, which it is the expected. This seems to be a bug, should i open a new issue?

**Comment by Enjymon** [comment]
@gabrielfern From what I managed to unserstand, the lists get populated by different mechanisms. Nemo looks at the `atime` timestamps (accessed time) in a specified set of locations, whereas items in the 'Recent Files' menu are added when a graphical application is started to open a file (or directory in the case of Nemo).

@itzexor After restoring the file `/home/<user>/.local/share/recently-used.xbel` from a backup, the 'Recent Files' Menu list did not get updated. Is this list stored in a different file, or is there a way to actively update this list based on the file `recently-used.xbel` ?

**Comment by icarter09** [comment]
@itzexor is there any update for this ticket or can it be closed?

**Comment by itzexor** [comment]
Sorry to everyone for late responses:

@gabrielfern That sounds like it could be a bug in nemo, but I'm not sure how recents are handled there. nemo-desktop runs as a separate process these days so there could be some update call that is
not happening there.

@Enjymon Recent files in cinnamon itself (basically just panel and applets) are retrieved through gtk's recent manager, so it's up to gtk to detect when they change and let us know. Unless we have some code that is blocking that specific case from update, it should work if supported by gtk recent manager. I am not too familiar with that part of cinnamon's code though.

@icarter09 I would say yes. I don't believe there are plans to change the number of recents supported by cinnamon js code for now.

**Comment by icarter09** [comment]
@itzexor thanks. Even if there aren't any current plans to change the number of recents, I'll still add this feature request to the list.
