### ISSUE TITLE
Tap to click bugged

### ISSUE THREAD

**Issue by freezingpt** [linuxmint/Cinnamon#7188]
```
 * Cinnamon 3.4.6 (Gtk 3.18.9-1ubuntu3.3)
 * Distribution - x Mint 18.2 Sonya
 * Card-1: Intel Skylake Integrated Graphics, Card-2: NVIDIA GM107M [GeForce GTX 950M], Kernel: 4.13.0-26-generic x86_64 (64 bit gcc: 5.4.0)
 * 64 bit
 ```

**Issue**
So I installed new drivers update and when I use the touchpad the only way I can click something is by pressing in the touchpad, taping doesn't work. I booted a previous version of the drivers and they work fine.
Here is the bundle of drivers that I updated, one is the culprit.
![screenshot from 2018-01-10 20-26-37](https://user-images.githubusercontent.com/35309964/34794368-591691ec-f646-11e7-9c0f-2ad7ea32e567.png)

**Comment by leigh123linux** [comment]
Driver issue can't be fixed here
