### ISSUE TITLE
Mint 18.3 Cinnamon with 4.13.0-26 Breaks Power Statistics- Process

### ISSUE THREAD

**Issue by SCraigG** [linuxmint/Cinnamon#7189]
```
Kernel: 4.13.0-26-generic x86_64 (64 bit gcc: 5.4.0)
           Desktop: Cinnamon 3.6.7 (Gtk 3.18.9-1ubuntu3.3)
           Distro: Linux Mint 18.3 Sylvia
Graphics:  Card: NVIDIA G86M [Quadro NVS 140M] bus-ID: 01:00.0
           Display Server: X.Org 1.18.4 drivers: nouveau (unloaded: fbdev,vesa)
           Resolution: 1280x800@60.02hz
           GLX Renderer: NV86
           GLX Version: 3.0 Mesa 17.2.4 Direct Rendering: Yes
 ```

**Issue**

Running Linux Mint 18.3 Cinnamon. Attempting to run "Power statistics - Processor" errors out on "GDBus.error:org.freedsktop.UPower.GeneralError:cannot enable timerstats" and brings the system to its knees requiring a "Force Quit"of Power Statistics.

Reverting back to my previous kernel, 4.10.0-42 works OK.

**Steps to reproduce**

Run Power Statistics - Processor
100% repeatable

**Expected behaviour**

**Other information**

Evidently the Method for retrieving those stats has been removed from ubuntu kernels 4.11 & onwards and will not return.
See link:
[https://bugzilla.redhat.com/show_bug.cgi?id=1427621](url)

**Comment by leigh123linux** [comment]
Explain this



> Attempting to run "Power statistics - Processor"

And why you think I shouldn't close the issue?
