### ISSUE TITLE
The pulseaudio output device remains the HDMI output even if it's disconnected

### ISSUE THREAD

**Issue by marmistrz** [linuxmint/cinnamon#7193]
```
 * Cinnamon version: 3.6.7
 * Distribution: Arch
 * Graphics hardware *and* driver used: Intel modesetting, Intel HD Graphics 5th gen
 * 64 bit
 ```

**Issue**
The pulseaudio output device remains the HDMI output even if it's disconnected and there's no way to bring it back without pavucontrol.

**Steps to reproduce**
1. Connect a HDMI device, e.g. a tv set
2. Switch the audio output to HDMI
3. play some audio, e.g. the audio test
4. hear the tv set play the audio
5. disconnect the HDMI cable
6. open `pavucontrol` to see the output devices (make sure the laptop speakers are set as a fallback device)
7. play the audio test again

**Actual behaviour**
The playback device remains the HDMI output. Now, you have a reflexes exercise to switch back the output to the laptop speakers through pavucontrol. The Cinnamon sound applet doesn't even list the HDMI output, **there's no way to switch back to the laptop speakers.** through the Cinnamon settings app (that's the biggest problem)

**Expected behaviour**
the audio output is the laptop speakers OR at least it's possible to switch back to the laptop speakers

**Comment by JohnD28** [comment]
I have the same problem on Linux Mint + Cinnamon for years

**Comment by puenka** [comment]
I have just experienced the same issue. I would also suggest both improvements to the audio settings (i.e. that the auto switch back from HDMI audio works AND implementing more functionality from pavucontrol into the settings tab). 

I would even prefer replacing the audio settings tab with pavucontrol (as it works great for me on my xfce desktop), but I suppose that's not easily possible...

**Comment by marmistrz** [comment]
As a workaround - is there any way (command-line?) to set the output device for all applications (including the not running ones) to the Analog Stereo Output (non-HDMI one)?

**Comment by martinpescador** [comment]
Never had this issue before, but do now with a fresh/new install of 19. Terribly annoying.

**Comment by JohnD28** [comment]
No one seems to care...

**Comment by marmistrz** [comment]
Could anyone test this on 4.0.10 (or newer)? It looks to me that, even though the device remains HDMI, now the HDMI output stays there after the cable is disconnected, and, what's more, the the Analog Stereo gets correctly activated after a reboot.

**Comment by Vahan86** [comment]
@marmistrz, @martinpescador, @JohnD28, is this still an issue for you in Cinnamon 4.4?

**Comment by martinpescador** [comment]
> @marmistrz, @martinpescador, @JohnD28, is this still an issue for you in Cinnamon 4.4?

This is *not* an issue in Cinnamon 4.4!

**Comment by JohnD28** [comment]
I use GNOME now...

**Comment by marmistrz** [comment]
I don't currently have access to any audio-capable HDMI device. I'll be able to check in about 3 weeks.

**Comment by marmistrz** [comment]
This is no longer an issue :) Thanks a lot!
