### ISSUE TITLE
Option to "rotate"(invert) the panel 180º to switch applets position

### ISSUE THREAD

**Issue by ssspacez** [linuxmint/Cinnamon#7198]
**Feature request**
I would like to "rotate" the panel, like make the panel turn 180º and the applets from the left would go to the right and the applets from the right would go to the left side of the panel.

Probably "**invert panel**" would be a more accurate term.

**Comment by brownsr** [comment]
This can be achieved readily within a panel by turning on panel edit mode and moving the applets individually. If you mean to move the panel to the other side of a screen then that can also be achieved through 'modify panel'.  Both are accessed through right clicking an empty area of the panel.

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html
