### ISSUE TITLE
suggestion - mouse wheel on titlebar- take window to desktops

### ISSUE THREAD

**Issue by dobkeratops** [linuxmint/cinnamon#7202]
could we add an option for mouse-wheel events on the titlebar to trigger taking the current window to the next or previous workspaces; I've seen this in sawfish 

 - this allows rapid window organisation without needing to navigate menus or use hotkeys, and can be quite intuitive once your brain has associated mouse-wheel scrolling on the desktop with next/previous workspaces aswell. 
It's less fiddly than using toggling the 'sticky flag' , or navigating a menu to send to workspaces

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
