### ISSUE TITLE
Suggestion - Quick sound switcher like in Win10, Not yet native in GNU/Linux.

### ISSUE THREAD

**Issue by ijash** [linuxmint/Cinnamon#7203]
```
 * Cinnamon version (bundled with 18.02)
 * Distribution - (Mint 18.02)
 * nvidia GTX card
 * 64 bit
 ```
_please don't mind my current pc specs._

**Issue**
Hi, please implement this tool as a native cinnamon app.
https://github.com/yktoo/indicator-sound-switcher
this tool is natively available in windows 10. please make linux mint as the first distribution natively support sound switcher.
and (if possible) please make the gui for renaming each input/output.

**Steps to reproduce**
if i want to switch sound in cinnamon, i have to open settings.

**Expected behaviour**
would be better if you have quick switcher to switch between main speakers and headphones.

**Other information**
please check: 
[Yktoo Sound Switcher Indicator](https://yktoo.com/en/software/indicator-sound-switcher) - Sound input/output selector indicator for Ubuntu/Unity. https://github.com/yktoo/indicator-sound-switcher

**Comment by clefebvre** [comment]
This has been in Cinnamon for years.. you can right-click the applet and select an output device.
