### ISSUE TITLE
Mouse clicks get lost or are heavily delayed, spurious clicks happen

### ISSUE THREAD

**Issue by axel-h** [linuxmint/Cinnamon#7204]
Since start of 2018 I'm experiencing mouse clicks get lost or heavily delayed in Cinnamon, also spurious left-click happen. Moving the mouse around still forks fine, but the UI does not react to it, ie the mouse-over effects do not show up. Also, there are spurious left-clicks that make context menus pop up. Sometimes, right-clicks are not really lost, but it seem they are applied to some old position of the mouse pointer and the application that has been there receives the input. The keyboard still works fine and allows navigation. Just some Cinnamon related shortcuts do not work. E.g ALT+F2 does not bring up the input dialog to start an application.
As a wild guess, sometimes is feels as if starting Chromium (63.0.3239.84) might trigger this 
somehow. Or it's more likely to happen when Chromium runs. But this might just be coincidence.

I don't know how the input sub system works, but it seem the input queue is somehow broken or blocked. However, I could not find any messages in the syslog that might be related to this or that show some task is crashing. Things look as usual. Is there a way to debug this, by e.g. showing the input events or increase the log level?

Switching to a console using CTRL+ALT+F1 and then returning to Cinnamon with ALT+F8 seems to fix the issue and the mouse clicks works again. Looks like this resets some input queues? 

System:
* Cinnamon v3.6.7
* Mint 18.3, 64-bit 
* kernel 4.13.0-26-generic #29~16.04.2-Ubuntu
* X.Org 1.18.4
* Intel Broadwell-U Integrated Graphics, intel driver
* Mesa DRI Intel HD Graphics 5500 (Broadwell GT2) GLX Version: 3.0
* Mesa 17.2.4

**Comment by RyanNerd** [comment]
@axel-h I had a similar issue but I think this is because my touchpad may have a short or is malfunctioning. This command turns my touchpad off and the random mouse clicks also stopped (touchpad is of no use however):

`sudo modprobe -r psmouse`

Perhaps this may be of use to you.

**Comment by axel-h** [comment]
Interesting though about the origin, thanks! Will try this next time.

**Comment by icarter09** [comment]
@axel-h Are you still experiencing this issue?

**Comment by axel-h** [comment]
It's gone - but I've never figured out what really caused this and how to was resolved.

Case closed for now, can't be reproduced.

**Comment by joepastor** [comment]
I'm having the same issue. I updated the distro and still...
This is really happening.

**Comment by liberspirita-lisk** [comment]
fresh install cinnamon, i  have this issue

**Comment by mineland-0066** [comment]
installed pop os, working fine in the first day, the next day this happened. weird thing is that even by using a virtual mouse setup (like kdeconnect or gnomeconnect) still has the left mouse button not working, or in some cases it stays held down with no input of either mouse at all

**Comment by orbitalchicken** [comment]
I have the same problem with Linux Mint 20.2 installed on a 7 years old Panasonic C50. The mouse click stop working at random times.

**Comment by lacostenycoder** [comment]
I'm on Linux Mint 20.10 and my left mouse button freezes sometimes after sleep/hibernate. I've tried many things but so far only hard reboot works.

**Comment by fonziemedia** [comment]
Hey it's 2025 and I'm here because mouse clicks sometimes don't work. I'm starting to miss Windows 11..

**Comment by alosslessdev** [comment]
This happened to me while running netbsd on VirtualBox from the repos with docker installed so I had to execute the command sudo rmmod kvm_amd. After I ran startx on a fresh netbsd install and then closed it, it happened

**Comment by alosslessdev** [comment]
This happened to me while running netbsd on VirtualBox from the repos with docker installed so I had to execute the command sudo rmmod kvm_amd. After I ran startx on a fresh netbsd install and then closed it, it happened, maybe it's an Nvidia issue? Anyways I pressed ctrl-alt-f3 and got a virtual terminal after a few minutes, logged in through the terminal and ran htop and saw that xorg was maxing out one of the CPU cores.... I was able to get these Nvidia error messages by trying to start cinnamon again through a virtual terminal just running cinnamon from the terminal, after a while I got a lightddm login screen and all user space processes were killed, here's some logs: https://github.com/alosslessdev/nemoerror

I think it's caused by X11 

![Image](https://github.com/user-attachments/assets/c1a210b5-5d4f-4da3-a0bd-43195584da9d)
