### ISSUE TITLE
Suggestion - Let Cinnamon-Shell use GNOME-Shell theme

### ISSUE THREAD

**Issue by vm70** [linuxmint/Cinnamon#7205]
```
 * Cinnamon version 3.6.7
 * Antergos Linux
 * 64-bit 
 * Intel i3
```
There aren't many Cinnamon themes in comparison to the large number of GNOME-shell themes. How difficult would it be to make a program that converts the GNOME themes into Cinnamon themes, so that Cinnamon could use them? 
For example, you can use the GNOME-Shell theme for the color of the panels and the GTK+ theme for the on/off switches.
That way, the Cinnamon desktop will have a more unified look instead of 2 different (and sometimes clashing) themes.

**Comment by JosephMcc** [comment]
This just isn't going to happen. At least not by us. There are too many differences and it would also require us to update for any changes made to gnome shell every 6 months.
