### ISSUE TITLE
Laptop not displaying anything WHEN the lid is closed and then reopened later on.

### ISSUE THREAD

**Issue by Shmink** [linuxmint/Cinnamon#7207]
```
 * Cinnamon version: 3.6.7
 * Distribution: Mint 18.3
 * nVidia Geforce GT 740M - nvidia 384.111-0ubuntu0.16.04.1
 * 64 bit
 ```

**Issue**
When I close the lid on my laptop (Asus K56) and it's left long enough to go into a hibernation state or deeper then when I re-power on the laptop I enter my decryption password at boot and then nothing but a black screen. I can get around it for now by forcing a shut down using the power button and then turning it back on means that system works as expected then.

**Steps to reproduce**
With a laptop close the lid and leave it long enough to go into a hibernation. Lift the lid up and power it on again.

**Expected behaviour**
Expect to just have a black screen that never ends. Can be avoided if you shut down instead of just closing the lid however this wasn't an issue when I was using Mint 18.2

**Other information**
As mentioned I have a fully encrypted system that requires a password at boot to decrypt the system. This was done when I first installed the OS using the default options. I shouldn't imagine this would be the issue as it never has been for Mint 18.2 and previous version. Not sure what error logs I could share to shed more light on the issue but if there is feel free to ask and I'll fo it.

**Comment by shama404** [comment]
I see the same issue on my Dell i3558 as well.

**Comment by Shmink** [comment]
@shama404 What kernel are you on? Run `uname -r` will tell you. Someone mentioned in a reddit thread that they have the same issue but they assume it to be a 4.13 issue.

**Comment by tomatpasser** [comment]
I have the same problem, kernel 4.13.0-26-generic.
Lenovo Y500 laptop
Cinnamon 3.6.7
Linux Mint 18.3 Sylvia

**Comment by Shmink** [comment]
So I just booted into my laptop with kernel 4.10.x and the issue is no longer there. It seems to me that the issue is with kernel 4.13.x and not cinnamon. Closing this issue for that reason. Hopefully, newer kernels will fix the issue.
