### ISSUE TITLE
Cinnamon implicitly and invisibly locked Alt-0 to window switcher

### ISSUE THREAD

**Issue by trialism** [linuxmint/cinnamon#7215]
```
Cinnamon 3.6.6
Manjaro
Nvidia with latest stable proprietary driver, Virtualbox with intel driver
64 bit
 ```

**Issue**

I've no keyboard shortcuts set to Alt-0 - only in neovim but cinnamon still starts the window switcher with it. My window switchers are Super+Tab and Super+0(backward). Setting the switcher to Ctrl-based doesn't help.

**Steps to reproduce**
Install cinnamon packages on manjaro.

**Expected behaviour**
Cinnamon shouldn't do anything when pressing Alt-0.

**Other information**

**Comment by mainmachine** [comment]
This is probably a Manjaro packaging issue, or conflict with something else setting the shortcut. I can't reproduce with 3.6.7 Cinnamon on Ubuntu, and if it was a Cinnamon thing then I'd expect that I would experience the same hotkey binding, and I have nothing bound to alt-0.
