### ISSUE TITLE
Feature Request: Touch Screen features

### ISSUE THREAD

**Issue by ImperialPraetor** [linuxmint/Cinnamon#7218]
Cinnamon using 3.6
Drivers using: open source 
-----
I would like it if cinnamon had full touch screen functions I'm not sure if touch screen features was implemented in cinnamon but since touch screen is getting common please add this feature to the desktop so that it'll be compatible with touch screen monitors.

**Comment by mainmachine** [comment]
touch interaction already works as far as I've seen - what specifically so you think needs to change?

**Comment by ImperialPraetor** [comment]
I was not aware that touch functions were already added, if it has then this request could actually be closed then if there's nothing to do.

**Comment by mainmachine** [comment]
Yeah, give it a shot - I believe it's inherited from GTK upstream, but I could be wrong. My wife is running Cinnamon on an HP, and it all just works as far as I've seen, in Chrome, desktop interactions, etc.

Oh, and you can close this yourself if you like. :)

**Comment by JosephMcc** [comment]
Maybe you should try it before opening a feature request ;)
