### ISSUE TITLE
Feature requests: Android phone notifications

### ISSUE THREAD

**Issue by OmegaDOS** [linuxmint/Cinnamon#7219]
I would like smartphone notifications be available for cinnamon to match similar functions like Windows 10 has with the Android notifications which we can send messages, view messages and so on from the PC for our Android smartphone. I don't want to use KDE Connect but would like this to be built-in to the cinnamon desktop environment.

**Comment by mainmachine** [comment]
This works very well for this, I've used it with Cinnamon and it does what you're asking for:

https://github.com/hauckwill/linconnect-server

And why not use KDE connect for this - why do you want the Cinnamon devs to build it specifically...?

**Comment by clefebvre** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
