### ISSUE TITLE
Feature Request: Nemo changes

### ISSUE THREAD

**Issue by ImperialPraetor** [linuxmint/Cinnamon#7220]
I would like Nemo to have a ribbon on the top and then context menu on the sidebar to look slightly similar to the Explorer on Windows 10 it would be nice for some of us who transform his/her desktop to look like Windows 7 or 10 with themes and especially the StarkMenu.

**Comment by mainmachine** [comment]
I don't think you're going to find many people who want this feature added to Cinnamon - most of us prefer Cinnamon's to W10 paradigms.

**Comment by JosephMcc** [comment]
Sorry but our ultimate goal is not to make Cinnamon into a copy of windows.
