### ISSUE TITLE
Feature Request: Timeline for Cinnamon

### ISSUE THREAD

**Issue by OmegaDOS** [linuxmint/Cinnamon#7221]
Since Microsoft is doing Timeline for Windows 10 I would like Cinnamon to have a similar feature but our version will be open sourced. I would also like it if approved that third-party browsers would be allowed on the timeline. It would also be nice to see what we have done in the past just like Microsoft is doing with Timeline on Win10.

**Comment by bkmeneguello** [comment]
It already exists, for some good years, it's called [Zeitgeist](https://wiki.archlinux.org/index.php/Zeitgeist).

**Comment by clefebvre** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
