### ISSUE TITLE
Prefer 5GHz wireless band option in network manager

### ISSUE THREAD

**Issue by mcarans** [linuxmint/Cinnamon#7225]
```
 * Cinnamon version (cinnamon --version)
3.6.7
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
Mint 18.3
 * Graphics hardware *and* driver used
Issue is with: USB-C hub with ethernet
 * 32 or 64 bit
64
 ```

**Issue**
Currently it only seems possible to select a specific BSSID under identity. I could not find any option to simply prefer 5GHz over 2.4Ghz and by default it seems to try to connect to the 2.4GHz one if I don't set the BSSID. 

**Steps to reproduce**
Open settings for wifi. Under Identity it is possible to pick a BSSID but there doesn't seem to be any option to prefer 5GHz.

**Expected behaviour**
Tick a box to prefer 5GHz over 2.4GHz with corresponding behaviour. 

**Other information**
Is there an option to prefer 5GHz or any workaround?

**Comment by leigh123linux** [comment]
Sorry if you want this addition function you will need to file the issue against cinnamon-control-center or even NetworkManager.

**Comment by leigh123linux** [comment]
The easiest solution if possible is to rename the wifi types on the router

BSSID-2G
BSSID-5G

**Comment by mcarans** [comment]
Unfortunately the routers are in an office so I can't do that. I will file against cinnamon-control-center. Thanks @leigh123linux
