### ISSUE TITLE
Display messed up after switching users (even to the same user)

### ISSUE THREAD

**Issue by rmwiseman** [linuxmint/cinnamon#7227]
```
 * Cinnamon version 3.6.7
 * Distribution - Mint 18.3
 * Graphics hardware *and* driver used: Haswell-ULT Integrated Graphics Controller (no special drivers)
 * 64 bit
 ```

**Issue**

When I switch users, going back to an existing session has severe display issues: things become invisible.

This sounds similar to #7224 but I don't have to wait or anything: it's very simple for me to reproduce and happens every time.

**Steps to reproduce**

1. Log in.
2. Select "Switch User" from the session menu.
3. Log in again as the same user.

**Expected behaviour**

Everything is exactly as I left it.

**Other information**

Here are a couple of screen shots to show the main menu before and after.  (All I did was press the "Windows" button to open the menu; then I took a screen grab.)

Before:

![cinnamon-before-switch-user](https://user-images.githubusercontent.com/10866705/35333318-451136be-0106-11e8-82d0-c297ebe377bd.png)

After:

![cinnamon-after-switch-user](https://user-images.githubusercontent.com/10866705/35333335-4c8b5898-0106-11e8-9256-5d5096231df5.png)

The main menu isn't the only thing that's messed up either: the applet tray and session pop-up menu are illegible too, as are many other things.

**Comment by mtwebster** [comment]
Are you using lightdm/slick-greeter for the login manager or mdm?  Can you paste ~/.xsession-errors?

**Comment by G3rb** [comment]
Hi, Indeed, for my part (#7224 ) I have to wait a time (not defined yet). But the bug seems to be similar. On my side in addition to the menu problem (like you) all the cinnamon applet and nemo bug. Can you try it : just add an applet like "user applet" and add a folder on the desktop and try to open it when the problem occur. Like this I think we could see if it's the same problem.

**Comment by rmwiseman** [comment]
Thanks for the response @mtwebster; I _think_ I'm using lightdm/slick-greeter, though I'm not sure how to check!  The settings dialogue for the login window doesn't say which it is.  I have attached yesterday's .xsession-errors file, since that's when I last switched users:

[.xsession-errors](https://github.com/linuxmint/Cinnamon/files/1663091/my_.xsession-errors.txt)

(I had to rename it to allow the upload.)

@G3rb I'm not sure what you mean about adding an applet...  As I mentioned, my applets "tray" is also messed up after switching users:

![image](https://user-images.githubusercontent.com/10866705/35377969-0c97f82e-01a9-11e8-88e7-3b34eb71ade1.png)

Is that what you're asking me to check?

**Comment by G3rb** [comment]
@rmwiseman yes. Thanks. my .xsession-error has just nothing related to yours :-) If you want to be sure which session manager you are using just write "sudo service lightdm restart" or "sudo service mdm restart" in the terminal. It will close all sessions and restart the session manager.

**Comment by rmwiseman** [comment]
Thanks @G3rb.  I ran `sudo service lightdm status` and it indicated it's running, whereas `sudo service mdm status` indicated it wasn't.  So that answers that question!

**Comment by erzko** [comment]
Hi, I also have this problem.
My laptop is using Intel GM45 integrated graphics. Cinnamon version is the same.
Restarting with Ctrl-Alt-Esc fix it fairly well

**Comment by Vahan86** [comment]
@rmwiseman, is this still an issue for you with Cinnamon 4.2?

**Comment by rmwiseman** [comment]
> @rmwiseman, is this still an issue for you with Cinnamon 4.2?

Nope, all good here now, thanks, although I'm on Cinnamon 4.0.10 not 4.2.
