### ISSUE TITLE
hybrid sleep not working on lid close

### ISSUE THREAD

**Issue by maddler** [linuxmint/Cinnamon#7228]
```
 * Cinnamon version 3.6.7
 * Distribution - Fedora 27
 * VGA compatible controller: Intel Corporation Device 591b (rev 04)
 * 64 bit
 ```

**Issue**
Hybrid sleep is not working on lid close.

**Steps to reproduce**
Set "sleep" as defailt action in "power" settings
Enab;e hybrid sleep in settings
Close lid
Remove power supply
Reboot

**Expected behaviour**
Previous session should be restored.

**Other information**
After reboot everything is lost.
Hybrid sleep is working fine otherwise (e.g. via Shutdown Menu With Icons Cinnamon Applet)

**Comment by leigh123linux** [comment]
Works fine here in F28 and 27, does this command work to suspend cinnamon

```
systemctl hybrid-sleep
```

**Comment by leigh123linux** [comment]
Issue moved to [linuxmint/cinnamon-settings-daemon #214](https://github.com/linuxmint/cinnamon-settings-daemon/issues/214) via [**ZenHub**](https://www.zenhub.com/)
