### ISSUE TITLE
Power settings window, buttons hidden under menu bar, not possible to resize the window

### ISSUE THREAD

**Issue by kdeguy** [linuxmint/Cinnamon#7234]
```
 * Cinnamon KDE
 * 18.1 Serena
 * Integrated Graphic Intel HD4000
 * 64 bit
 ```
When one goes to "configure power settings" window, the buttons are hidden under the menu bar. It's not possible to resize or move up the Power Saving Manager window nor there is scroll bar on the side hence one cannot click on the buttons hidden underneath the menu bar. 

![bug1](https://user-images.githubusercontent.com/35903466/35487943-ee16b058-0481-11e8-8241-0aac80439cd5.png)

![bug2](https://user-images.githubusercontent.com/35903466/35487969-3ecbfdd2-0482-11e8-9e1c-bd19c0b2c9eb.png)

**Comment by itzexor** [comment]
This looks like an issue with KDE system settings not supporting lower resolution displays. This repository is for Cinnamon issues only. In addition, we don't actually develop KDE. This needs to be reported to KDE developers directly at https://bugs.kde.org/

If this does turn out to be a Mint-specific issue somehow, you should report it to our linuxmint repository here: https://github.com/linuxmint/linuxmint

Thanks.
