### ISSUE TITLE
Panel configuration remains very buggy

### ISSUE THREAD

**Issue by CottonEaster** [linuxmint/Cinnamon#7237]
```
 * Cinnamon version (cinnamon --version)  3.6.7.
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 18.3
 * Graphics hardware *and* driver used: Nvidia, with proprietary driver
 * 32 or 64 bit: 64
 ```

**Issue**

I have just now installed Mint on a desktop that hadn't had it before. Trying to create a top panel, and move the applets from the bottom panel to the top one, created all sorts of nastiness: bits of window paint on the screen, panel's not coming out of edit mode, pasting of applets not working . . Admittedly, the first time I tried I was installing Office 2013 via Crossover at the same time, but I tried again after rebooting and had many of the same problems.

I am sorry I am not managing to be more specific in my reporting of the problems, but there were so many - and I still have to sort it out properly. Admittedly, the fact that I find the panel UI unintuitive makes things does cloud the issue somewhat.

**Steps to reproduce**

**Expected behaviour**

**Other information**

**Comment by clefebvre** [comment]
Please troubleshoot and find the exact cause of the problem. You can reopen the issue if the responsible component proves to be Cinnamon.

http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/.
