### ISSUE TITLE
DPI control is insufficiently granular

### ISSUE THREAD

**Issue by CottonEaster** [linuxmint/Cinnamon#7243]
```
 * Cinnamon version (cinnamon --version)  3.6.7
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) 18.3
 * Graphics hardware *and* driver used: Intel HD graphics 620, on whatever driver Mint installs by default for that
 * 32 or 64 bit: 64
 ```

**Issue**

One of my computers - and it is a newly manufactured computer, a ThinkPad - has a 13.3" FHD screen and a native resolution of 1920 x 1080.

On that computer, at the default resolution, windows are much too small (and not really correctable via other settings) on 'normal' user interface scaling, but too large on Hi-DPI. (Also, a few reboots seem needed to avoid worse problems; see [this bug report](https://github.com/linuxmint/mintupdate/issues/314).)

So, being able to set DPI to, say, 150%, would be good. Presently the choices are only 100% and 200% (unless there is some magic to the DPI setting called 'auto').

**Steps to reproduce**

Install Mint Cinnamon on a system with a screen similar to the one described above; observe that things are much too small (for any eyes, I think); change the DPI to 'double'; observe that things are too large.

**Expected behaviour**

A more granular setting - ideally applied by default.

**Other information**

I can supply screenshots.

I might that the following. After rebooting a few times - and setting a 'high' DPI - Mint Cinnamon had the system in a usable state (albeit not one that takes best advantage of my screen resolution, since things are too large). This is more than can be said - though admittedly I rebooted fewer times whilst trying these configurations - of a load of other distributions and desktop environments that I tried.

**Comment by JosephMcc** [comment]
Maybe you did, but if not please try searching before opening new issues. This was just closed yesterday https://github.com/linuxmint/Cinnamon/issues/3455
