### ISSUE TITLE
FEATURE REQUEST: include numlockx by default

### ISSUE THREAD

**Issue by N6REJ** [linuxmint/Cinnamon#7244]
```
 * Cinnamon version (cinnamon --version)
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
 * Graphics hardware *and* driver used
 * 32 or 64 bit
 ```
18.3 64bit
**Issue**
by default numlockx is not included at install, so in the login-window applet you are unable to choose the numlock state.
Please include it by default

**Steps to reproduce**
go to login-window applet, try to turn on numlock

**Expected behaviour**

changes state.

**Other information**

**Comment by clefebvre** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
