### ISSUE TITLE
FEATURE REQUEST: Numeric display of volume level

### ISSUE THREAD

**Issue by N6REJ** [linuxmint/Cinnamon#7245]
```
 * Cinnamon version (cinnamon --version)
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
 * Graphics hardware *and* driver used
 * 32 or 64 bit
 ```
18.3 64 bit cinnamon
**Issue**
when changing volume with the keyboard the numerical level of the volume is not displayed.

**Steps to reproduce**
change volume by keyboard

**Expected behaviour**
numbers display showing the level 0-100

**Other information**

**Comment by clefebvre** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.

**Comment by raniesantos** [comment]
@clefebvre what happened to this issue? I feel like a lot of users would appreciate this.

**Comment by raniesantos** [comment]
Here is a rough image edit of what I mean, and what I think the person that originally posted this means.

![Screenshot from 2021-05-28 12-37-04](https://user-images.githubusercontent.com/8528269/119930122-6df7b900-bfb1-11eb-8154-f7b5973e8d75.png)
