### ISSUE TITLE
Settings window: a suggestion, to do with text sizes, for improving the user experience

### ISSUE THREAD

**Issue by CottonEaster** [linuxmint/Cinnamon#7247]
* Cinnamon 3.6.7
 * Distribution - Mint 18.3
 * 32 or 64 bit: 64

&nbsp;&nbsp;&nbsp;The user seeking desirable or perhaps even merely usable text sizes must look and know to look in multiple places. Such a user would be aided by adding a mention - and link? - _at_ `System Settings` - > `Fonts` -> `Text scaling factor`, _to_ `System Settings` - > `Accessibility` -> `Large text`.

&nbsp;&nbsp;&nbsp;Also: searching for 'scaling' in the Settings search box yields . . nothing. The same goes for the string 'dpi'.

**Comment by clefebvre** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
