### ISSUE TITLE
Wifi not working

### ISSUE THREAD

**Issue by vinayd1** [linuxmint/Cinnamon#7254]
```
 * Cinnamon - version 3.6.2
 * Distribution - Mint 18.3 'Sylvia'
 * Wireless - 802.11b/g/n 
 * 64 bit
 ```

Wifi is not working on my system.
Tried everything including restarting the network-manager and installing the wifi drivers manually

Laptop: HP Pavilion 15 bs-180tx
![screenshot from 2018-02-04 20-11-29](https://user-images.githubusercontent.com/30961698/35778679-a4577d7e-09e7-11e8-839c-532f84b79007.png)

**Comment by NikoKrause** [comment]
This is neither a bug report nor a feature request. What you are looking for is a support. Open HexChat. You'll find there some people, who are very helpful. You just need to be a little patient.
