### ISSUE TITLE
Moving relative symbolic links with NEMO results in broken links in the target directory

### ISSUE THREAD

**Issue by gitty3** [linuxmint/Cinnamon#7256]
```
 * Cinnamon version: 3.6.7
 * Distribution: Mint 18.3
 * Graphics hardware *and* driver used: RX580, amdgpu
 * 64 bit
 ```

When moving a relative symbolic link in NEMO via drag/drop or cut/copy/paste to another directory, the target path of the symbolic link is not correct any more after the move (i.e. "broken link").

**Steps to reproduce**
1) Create a file: touch link_target.txt
2) Create a relative symbolic link to it: ln -rs ./link_target.txt rel_symlink.txt
3) Create a subdirectory: mkdir targetdir
4) Move the file with NEMO to the targetdir
=> NEMO displays now "broken link", the relative path of the sym link is not adapted in any way

**Expected behaviour**
After the move, the relative path of the symbolic link should be adjusted automatically according to the new location in the target directory.
In case the link is broken already prior to moving the link, the link target path should be adjusted nevertheless in the same way for consistency reasons and in case the link target is just unavailable temporarily.

**Other information**
Using "mv" in the command line results in the same problem. To my knowledge, it is not possible to update the path of a symbolic link, it needs to be recreated and the original one needs to be deleted, hence an atomic operation does not seem possible in this case. Finally, it probably depends on capabilities of the file systems of the source and target directories, but I would think, the error cases are the same as today, when the relative path is not adjusted.

**Comment by leigh123linux** [comment]
You will need to file the issue against nemo.

**Comment by NikoKrause** [comment]
That's the normal behaviour of symbolic links. Do other file manager do what you want?

To be honest, I would be confused, if the relative symbolic link would change it's path.
What do you do, if the targetdir has also a (different) file called link_target.txt and you move the symbolic link into this directory? Etc.
