### ISSUE TITLE
Bluetooth applet causes high CPU usage

### ISSUE THREAD

**Issue by RyanNerd** [linuxmint/cinnamon#7258]
```
 * Cinnamon version (3.6.7)
 * Distribution - (Mint 18.3 Debian)
 * Graphics hardware *and* driver used: Nvidia-390 390.25-0ubuntu0-gpu16.04.1 NVIDIA binary driver version 390.25
 * 64 bit Intel Core i7 - HP Envy laptop
 ```

**Issue**
Anytime the Bluetooth applet is used cinnamon CPU usage skyrockets.

**Steps to reproduce**
1. In terminal run `top`
2. Note that the CPU % for cinnamon is 10% or less.
3. Click on the Bluetooth applet and make sure the Devices tab is selected.
4. Watch the CPU % for cinnamon go up around 80%+.
6. Using the Bluetooth applet turn Bluetooth off (or if you click on the Settings tab).
7. Note that CPU % for cinnamon drops down to 10% or less.
8. Using the Bluetooth applet turn Bluetooth back on (or click back on the Devices tab).
9. Note that CPU % for cinnamon skyrockets back to around 80%+

![image](https://user-images.githubusercontent.com/10543911/35825607-a1f6f94c-0a73-11e8-9a3e-459d99ccec52.png)

**Expected behaviour**

CPU % usage for cinnamon shouldn't be impacted by using Bluetooth

**Other information**
This is a recent and clean install of Linux Mint 18.3 to my new SSD. My previous install didn't have this issue but I was using Blueman and never used the "blueberry" applet before. 
I installed Blueman and using this instead of the applet the CPU usage problem does not occur.

**Comment by RyanNerd** [comment]
For anyone that is experiening this issue here's the work-around I am using:
1. Uninstall Bluetooth: Menu-->Bluetooth right click and uninstall (including uninstalling blueberry).
2. From the terminal 'sudo apt-get install blueman`
3. Menu --> Startup Applications->Add Application Bluetooth Manager.

Note: It appears that Blueberry is continually looking for Bluetooth signals. I noticed when I clicked on the Settings tab (changing from the list of Bluetooth devices) the Cinnamon CPU usage dropped down to normal levels. So this is likely a bug in the applet itself and not in Cinnamon per se. One of the features of LM 18.3 was that applets run in their own process so this may be a side effect of this new feature.

**Comment by JosephMcc** [comment]
> One of the features of LM 18.3 was that applets run in their own process so this may be a side effect of this new feature.

They certainly don't. It's something we would love to have but would require a huge redesign of Cinnamon.

**Comment by RyanNerd** [comment]
@JosephMcc I misinterpreted [this](https://www.linuxmint.com/rel_sonya_cinnamon_whatsnew.php)

> The various plugins of the settings daemon also now run in their own separate processes and are independent of each others. It is therefore now much easier to identify which plugin might be responsible for high memory or CPU usage, and when a plugin crashes it no longer affects the rest of the Cinnamon backend.

**Comment by plule** [comment]
Hello, I see this issue in Linux Mint 19 too, Cinnamon 3.8.8. I tried blueman as suggested by RyanNerd but could not get a decent configuration from it.

**Comment by RyanNerd** [comment]
@plule What Kernel version are you running? I am currently running on v4.17.10. Perhaps upgrading your kernel may solve the configuration issue.

**Comment by Chemah** [comment]
This happens when I connect a bluetooth USB antenna. My Linux Mint 19.1 Cinnamon works fine until an unpdate... 

![image](https://user-images.githubusercontent.com/19628446/63634498-f008c000-c61c-11e9-8754-1bce3c087617.png)

**Comment by RyanNerd** [comment]
@Chemah Upgrade to Mint 19.2 (if you can) as this has an [update that fixes this issue](https://github.com/linuxmint/blueberry/issues/55). This issue was tracked down to the _spinner_ from a [GTK bug](https://github.com/linuxmint/blueberry/pull/85) that takes up all the resources.

If you are unable to upgrade to 19.2 you can try to force the Blueberry component in LM to the latest version.
