### ISSUE TITLE
Idea: "add to startup" in menu and other stuff

### ISSUE THREAD

**Issue by redsun82** [linuxmint/Cinnamon#726]
In the old installations of mintMenu you could do more things on apps in the menu, like adding to startup or uninstalling. Is there a plan to put back those features? Right now I only get "add to {panel, desktop, favorites}".

Also an "Edit..." would be nice to direcly go to the properties of the launcher without navigating the edit menu window.

**Comment by JosephMcc** [comment]
Thank you for your suggestion. See https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html for information on how we handle feature requests.
