### ISSUE TITLE
Desktop wakes from sleep at wrong time

### ISSUE THREAD

**Issue by mellobob** [linuxmint/Cinnamon#7261]
```
 * Cinnamon version (cinnamon --version)  3.6.7.
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)  Mint 18.3
 * Graphics hardware *and* driver used - default intel i915
 * 32 or 64 bit  64
kernel 4.13.0-32-generic
 ```

**Issue**
 
My computer is a simple desktop (i5-4570 cpu), with a LED monitor.
I put the monitor to sleep using the following settings:

    Turn off screen when inactive: 15 min
    Suspend: Never
   Screensave is set to never lock, etc. 

During the day, I just need to move the mouse or hit a key to wake the screen.

But, at night, the darn computer always wakes up around 2 or 3 AM.

I think the problem is with a cron process. I currently have only one: 

    0 1 * * * /usr/bin/nice -n 19 /usr/bin/ionice -c2 -n7 /usr/bin/backintime backup-job >/dev/null 2>&1

But, I don't think this is the problem. Rather, it might be the plex media server. It runs scheduled tasks between 2am and 5am.

Interestingly, once the screen wakes it never goes back to sleep. I have added the following to my crontab:
  */10 2 * * * xset dpms force off

And it seems to help.

The ultimate solution is to run Mate instead of Cinnamon. No problems with that.

Sure would like to solve this.

**Steps to reproduce**

**Expected behaviour**

**Other information**

**Comment by leigh123linux** [comment]
You need to file this against cinnamon-settings-daemon
