### ISSUE TITLE
When switching off menu effects, panel effects are switched off too

### ISSUE THREAD

**Issue by vassilisw** [linuxmint/Cinnamon#7263]
```
 * Cinnamon version 3+
 * Distribution Mint 18+
 ```

**Issue**
When switching off the menu effects (for menu bar, right click menu, etc) from preferences, the panel's applets popup window effects (when clicking the volume applet for example) are gone too!

**Steps to reproduce**
Just switch off the menu effects from the preferences and click on panel applets (volume, calendar, etc).

**Expected behaviour**
As of cinnamon 2.6, 2.8 in LM 17.2 and 17.3, menu-bar effects state (on/off) does not affect the panel's applet effects. This is the right behaviour. Menu-bars and contextual menus _are totally separated from the cinnamon and the cinnamon panel_. The menu effects can be annoying and destructive but the panel applet's effects are enjoyable and good looking.

**Comment by leigh123linux** [comment]
Try providing exact versions next time

**Comment by JosephMcc** [comment]
This isn't a bug. It's the intentional behavior.
