### ISSUE TITLE
FONT and languages problem.

### ISSUE THREAD

**Issue by ijash** [linuxmint/Cinnamon#7265]
```
 * Cinnamon version (Cinnamon 3.6.7)
 * Distribution - (Mint 18.3)
 * Graphics hardware: Nvidia GTX 950
 * 64 bit
extra info: https://git.io/vAIjE
have tested both in virtual box and real pc
 ```

**Steps to reproduce**
fresh install 18.3

**Expected behaviour**
no squared symbol/code, font rendered exactly the font supposed to be

**Other information**
look at the screenshot.

![screenshot from 2018-02-10 02-38-43](https://user-images.githubusercontent.com/30673286/36046732-81834b06-0e0c-11e8-857a-61b9849cf2c7.png)

it's not just noto, mostly non-english fonts such as Tamil, Arab, Hebrew, Thai etc..

so, can't i just instal english-only linux mint?

**Comment by NikoKrause** [comment]
What's your output of:
```
dpkg -l | grep noto
```

**Comment by NikoKrause** [comment]
Also, what's the program in your screenshot called?

**Comment by ijash** [comment]
here : git.io/vALJu

the program:
it's system font setting. just type font in menu

**Comment by JosephMcc** [comment]
You probably don't need to open this in two separate places :) I'm closing this one, will leave the other open.

**Comment by NikoKrause** [comment]
My program looks different than yours. I don't have this "Search font name":
![screenshot-window-2018-02-09-214033](https://user-images.githubusercontent.com/8415124/36049129-fa281ed6-0de1-11e8-956d-fba411c47b07.png)

**Comment by ijash** [comment]
@NikoKrause it's on system settings>appearance>fonts

**Comment by NikoKrause** [comment]
Ah yes. Looks the same here.

**Comment by ijash** [comment]
@NikoKrause is your fonts got any problem?

**Comment by NikoKrause** [comment]
I changed it to Noto Sans Cham and it got very weird. I changed it pretty fast back to Noto Sans Regular.

**Comment by NikoKrause** [comment]
Which language/alphabet is Noto Sans Cham?
![screenshot-window-2018-02-09-222058](https://user-images.githubusercontent.com/8415124/36050653-9e8a20fa-0de7-11e8-81ec-8169ec786018.png)

I'll take a guess:
Your system seems to be English (mine is German), i.e. the system uses the roman alphabet.
And Noto Sans Cham has no characters for the roman letters and the system doesn't know what to show/use instead.
Have you tried to change your system to this language from Noto Cham and see if it still behaves weird?
