### ISSUE TITLE
Question - Tweaking Tooltip Position in Theme.

### ISSUE THREAD

**Issue by smurphos** [linuxmint/Cinnamon#7266]
```
Cinnamon version - 3.6.7
Distribution - Linux Mint 18.3 Sylvia
Card: Intel 2nd Generation Core Processor Family Integrated Graphics Controller
Display Server: X.Org 1.18.4 drivers: (unloaded: fbdev,vesa)
32 or 64 bit
 ```
Does not appear possible to use `margin:` or `margin-top:` etc in the  `#Tooltip{}` class to consistently adjust panel item tooltips position so there a separation between the tooltip and the panel irrespective of panel position

E.g using `margin: 2px` will push tooltips from top panel items down and left panels right giving a pleasing effect, but tooltips from bottom or right panel items are pushed into the panel. It appears that tooltips position are defined from top and left so `margin-bottom: `and `margin-right:` are ignored.

The effect I'm after is a consistent 2px or 0.2em gap between the panel and tooltip irrespective of panel position.

Is there an existing way to achieve this that I'm missing?

**Comment by NikoKrause** [comment]
Fixed by https://github.com/linuxmint/Cinnamon/pull/7388
