### ISSUE TITLE
Changing pdf default program does not work

### ISSUE THREAD

**Issue by SaeedFazlollahzadeh** [linuxmint/cinnamon#7268]
```
 * Cinnamon version (cinnamon --version)
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
 * Graphics hardware *and* driver used
 * 32 or 64 bit
 ```
Cinnamon 3.6.7
Mint 18.3 Sylvia
NVidia
64 bit
**Issue**
I tried to change pdf default program as non-root user but it did not change. As root user it changed pdf default program to "Document Viewer", but as non-root user (I have two users, Saeed and root) changes do not work.
I deleted defaults.list in /usr/share/applications and rebooted but still did not work.
As root user the changes work and pdf default program changes to Document Viewer, but as non-root user I still cannot change it.

**Steps to reproduce**

**Expected behaviour**
Expected to change pdf default program.

**Other information**

**Comment by icarter09** [comment]
@SaeedFazlollahzadeh are you stll experiencing this issue?
