### ISSUE TITLE
Login Loop as Guest in Virtualbox

### ISSUE THREAD

**Issue by BertN45** [linuxmint/Cinnamon#7271]
```
 * Guest OS - Mint 18.3
 * Host OS - Ubuntu 17.10 with propriety Nvidia driver 340 as proposed by Ubuntu
 * Virtualbox 5.6.2  
 * everything 64 bit

If I enable 3D acceleration in Virtualbox, Mint gets in a login loop, see the video. 
[Mint-Bug-Video-mp4.zip](https://github.com/linuxmint/Cinnamon/files/1714338/Mint-Bug-Video-mp4.zip)

.xsession-errors contains following text:
initctl: Unable to connect to Upstart: Failed to connect to socket /com/ubuntu/upstart: Connection refused
syndaemon: no process found
/etc/mdm/Xsession: Beginning session setup...
localuser:bertadmin being added to access control list
OpenGL Warning: Failed to connect to host. Make sure 3D acceleration is enabled for this VM.

**Comment by leigh123linux** [comment]
It's failing before cinnamon start up.

**Comment by BertN45** [comment]
As a user I do not care whether it is failing before cinnamon is started. YOUR Linux Mint SYSTEM failed. If the Mint project did make an error in the integration of the Linux kernel into their system; they should feel responsible for solving that problem.

**Comment by leigh123linux** [comment]
As a developer I only care about the cinnamon code and issues within it.

> OpenGL Warning: Failed to connect to host. Make sure 3D acceleration is enabled for this VM.

Looks more like a Vbox issue or their 'guest additions'

**Comment by BertN45** [comment]
OK you were right, see the next Oracle statement on their Download page.
Important: The Guest Additions which come with VirtualBox 5.2.6 and 5.1.32 do not work properly on Linux guests with 3D enabled. Here are updated versions for 5.2.6 and 5.1.32.
