### ISSUE TITLE
JavaEmbeddedFrame visible on taskbar

### ISSUE THREAD

**Issue by kaqqao** [linuxmint/Cinnamon#728]
As of Mint 13, running JDownloader (and probably other Java applications that have a tray icon) displays an additional window on the taskbar called JavaEmbeddedFrame. This frame is used by Java to display the tray icon. The frame can not be actually shown (only the taskbar icon is there) or closed. Additionally, attempting to close/hide it a couple of times, invariantly crashes Cinnamon completely. Running the very same version of JDownloader on Cinnamon 1.4 on Mint 12 did not display this frame.

**Comment by mrns76** [comment]
Your tip helped a lot!
Result: https://imgur.com/a/Q8TL7 (the number of windows does not matter)
Thank you!

**Comment by LiohMoeller** [comment]
I have tried to apply the instructions with the .desktop file on lm 19.2 cinnamon without success. Did you get it running on that version as well?

**Comment by xss** [comment]
@LiohMoeller: As far as I see, Mint 19.2 uses Cinnamon version 4.2. As I am using Cinnamon on Ubuntu 18.04 (and their software sources for Cinnamon seem to have dropped behind quite a lot), I am still running the rather ancient Cinnamon version 3.6.7. So, unfortunately, I cannot give you much advice as to whether or how it still works on your version.

I would, however, really hope that they didn't significantly change the way .desktop files work.

Possibly, the empty Java window has another WM_CLASS name now due to changes in Java versions or distributions. Maybe the instructions below help you when the annoying invisible Java window is open (as it's a hidden window, finding the WM_CLASS is not as straightforward as with a normal window, which would simply be issuing `xprop WM_CLASS` and then clicking on the window in question):

Open a terminal and list all windows currently in existence in your session:

    wmctrl -l

The result might look something like this:

    0x03c00003 -1 xss Desktop
    0x06400007  0 xss Software Updater
    0x05e0003a  0 xss JavaEmbeddedFrame visible on taskbar · Issue #728 · linuxmint/cinnamon - Mozilla Firefox
    0x06a00003  0 xss System Info
    0x06c01d68  0 xss xss@server: ~
    0x0700007a  0 xss JDownloader 2
    0x070000fc  0 xss JavaEmbeddedFrame

In that list, identify the hidden Java window (the obvious entry in my example) and then find its WM_CLASS via its window ID (first column from the above result). Still in the terminal, run:

    xprop WM_CLASS -id 0x070000fc

The result in my case:

    WM_CLASS(STRING) = "sun-awt-X11-XEmbeddedFramePeer", "JDownloader"

You likely wouldn't want to react to the more general entry `JDownloader` (the _real_ JDownloader window uses that, as well), but the other entry, in my case `sun-awt-X11-XEmbeddedFramePeer` (might be a different string for you if my suspicion is confirmed), is the one you want. Make sure to put that exact string (without the quotes) in your .desktop file on the appropriate line `StartupWMClass=` and restart Cinnamon. If .desktop files still work with this Cinnamon version, that should do it.

Good luck. Keep us updated. :)

**Comment by LiohMoeller** [comment]
Thanks for the hints, I am going to try it out and keep you updated.

**Comment by LiohMoeller** [comment]
Yes, the WM_CLASS is still the same: WM_CLASS(STRING) = "sun-awt-X11-XEmbeddedFramePeer", "JDownloader"

And I have created the .desktop file accordingly, still with no real effect. The only visible thing that has changed after reloading cinnamon is that the icon for the JavaEmbeddedFrame is now a gear and no longer the Java icon.

**Comment by Ammako** [comment]
This is still a thing

**Comment by clscndd** [comment]
> This is still a thing
> 
> The only real fix I could find: [jake-phy/WindowIconList#168 (comment)](https://github.com/jake-phy/WindowIconList/issues/168#issuecomment-495412661)
> 
> > thanks a lot, I just had the issue with windows-grouped-list. The workaround is quite similar:
> > in `/usr/share/cinnamon/applets/grouped-windows-list@cinnamon.org/appList.js`, replace:
> > ```
> >     shouldWindowBeAdded(metaWindow) {
> >         return (this.state.settings.showAllWorkspaces
> >             || metaWindow.is_on_all_workspaces()
> >             || metaWindow.get_workspace() === this.metaWorkspace)
> >         && !metaWindow.is_skip_taskbar()
> >         && (!this.state.settings.listMonitorWindows
> >             || this.state.monitorWatchList.indexOf(metaWindow.get_monitor()) > -1);
> >     }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > by
> > ```
> >     shouldWindowBeAdded(metaWindow) {
> >         return (this.state.settings.showAllWorkspaces
> >             || metaWindow.is_on_all_workspaces()
> >             || metaWindow.get_workspace() === this.metaWorkspace)
> >         && !metaWindow.is_skip_taskbar()
> >         && metaWindow.get_title() !== "JavaEmbeddedFrame"
> >         && (!this.state.settings.listMonitorWindows
> >             || this.state.monitorWatchList.indexOf(metaWindow.get_monitor()) > -1);
> >     }
> > ```

I face the same problem, this resolution looks promising. But I use Pop OS; is there any alternative to this directory/file in Ubuntu/Pop? I would like to try.

**Comment by BarbzYHOOL** [comment]
@clscndd found a solution?

**Comment by melvintj** [comment]
Issue still exist in ubuntu 22.04.

**Comment by FreePhoenix888** [comment]
Issue still exist in ubuntu 22.04.

Env info:
```
freephoenix888@FreePhoenix888:~$ npx envinfo
Need to install the following packages:
  envinfo@7.10.0
Ok to proceed? (y) y

  System:
    OS: Linux 6.2 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
    CPU: (12) x64 AMD Ryzen 5 2600 Six-Core Processor
    Memory: 11.13 GB / 15.55 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 18.17.1 - ~/.nvm/versions/node/v18.17.1/bin/node
    npm: 9.6.7 - ~/.nvm/versions/node/v18.17.1/bin/npm
  Managers:
    Apt: 2.4.10 - /usr/bin/apt
    Cargo: 1.72.0 - ~/.cargo/bin/cargo
    pip3: 22.0.2 - /usr/bin/pip3
  Utilities:
    CMake: 3.22.1 - /usr/bin/cmake
    Make: 4.3 - /usr/bin/make
    GCC: 11.4.0 - /usr/bin/gcc
    Git: 2.42.0 - /usr/bin/git
    Curl: 7.81.0 - /usr/bin/curl
  IDEs:
    Nano: 6.2 - /usr/bin/nano
    VSCode: 1.82.2 - /usr/bin/code
    Vim: 0.6.1 - /usr/bin/vim
  Languages:
    Bash: 5.1.16 - /usr/bin/bash
    Java: javac 21 - /usr/bin/javac
    Perl: 5.34.0 - /usr/bin/perl
    Python3: 3.10.12 - /usr/bin/python3
    Rust: 1.72.0 - /home/freephoenix888/.cargo/bin/rustc
  Browsers:
    Chrome: 117.0.5938.92

```

**Comment by campb223** [comment]
I found a fix which should work in LinuxMint, Pop_OS, etc. Consolidated steps based on previous comments:

1. Find the WM_CLASS of the icon that's appear in your dock. To do this run:
a. `wmctrl -l`
2. The results should look something like this:
```
0x03c00003 -1 xss Desktop
0x06400007  0 xss Software Updater
0x05e0003a  0 xss JavaEmbeddedFrame visible on taskbar · Issue #728 · linuxmint/cinnamon - Mozilla Firefox
0x06a00003  0 xss System Info
0x06c01d68  0 xss xss@server: ~
0x0700007a  0 xss JDownloader 2
0x070000fc  0 xss JavaEmbeddedFrame
```

3. In that list, identify the hidden Java window (the obvious entry in my example) and then find its WM_CLASS via its window ID (first column from the above result). Still in the terminal, run:
a. `xprop WM_CLASS -id 0x070000fc`

4. Now you should see a result like one of these:
a. `WM_CLASS(STRING) = "sun-awt-X11-XEmbeddedFramePeer", "JDownloader"`
b. `WM_CLASS(STRING) = "com-screenconnect-client-Program", "com-screenconnect-client-Program"`

5. In my case, it was the 2nd option but whatever you see there is what you'll need to use. 
6. Now we're going to create a .desktop file to hide this WM_CLASS using [this forum post](https://forums.linuxmint.com/viewtopic.php?f=208&t=103890&p=1430334#p1430334) as a guide. 
7. In terminal run:
a. `sudo nano /usr/share/applications/hide-JavaEmbeddedFrame.desktop`
b. In the editor paste this but be sure to use your WM_CLASS you found earlier:
```
[Desktop Entry]
Version=1.0
Name=Hide JavaEmbeddedFrame
Comment=Hide the invisible JavaEmbeddedFrame window created by some Java applications (like jDownloader) and visible in some docks or task lists/task bar applets
Terminal=false
Type=Application
NoDisplay=true
StartupWMClass=com-screenconnect-client-Program
```
8. Copy that file into your user folder as well:
a. `sudo cp /usr/share/applications/hide-JavaEmbeddedFrame.desktop ~/.local/share/applications/`
9. Restart your computer and you shouldn't see the icon when the program launches.
