### ISSUE TITLE
Desktop zoom is not fullscreen after pluging a monitor

### ISSUE THREAD

**Issue by Thy87** [linuxmint/cinnamon#7281]
```
 * Cinnamon version: 3.6.7
 * Distribution: Mint 18.3
 * Graphics hardware: Intel Atom Processor D4xx/D5xx/N4xx/N5xx Integrated Graphics Controller
 * Driver: intel-microcode version 3.20180108.0+really20170707ubuntu16.04.1
 * 32 bit
 ```

**Issue**
I have a notebook, I use an external screen which has a higher resolution.
I set the external monitor to be the only screen to use.
Once the monitor is pluged, when I zoom in, the magnifier is not in full-screen anymore.

To make the magnifier full-screen again, I have to go to "universal access" settings
and change the parameter "shape of the magnifier"

**Comment by icarter09** [comment]
@Thy87 is this a feature request or a bug?
