### ISSUE TITLE
Traceback cinnamon-launcher

### ISSUE THREAD

**Issue by ryanmusante** [linuxmint/Cinnamon#7289]
```
Cinnamon 3.6.6
Manjaro stable branch
NVIDIA 980M 
64 bit
 ```

**Issue**
Feb 14 18:28:26 xmg /usr/lib/gdm/gdm-x-session[1061]: Traceback (most recent call last):
Feb 14 18:28:26 xmg /usr/lib/gdm/gdm-x-session[1061]:   File "/usr/bin/cinnamon-launcher", line 53, in <module>
Feb 14 18:28:26 xmg /usr/lib/gdm/gdm-x-session[1061]:     os.execvp(FALLBACK_COMMAND, (FALLBACK_COMMAND,) + FALLBACK_ARGS)
Feb 14 18:28:26 xmg /usr/lib/gdm/gdm-x-session[1061]:   File "/usr/lib/python3.6/os.py", line 559, in execvp
Feb 14 18:28:26 xmg /usr/lib/gdm/gdm-x-session[1061]:     _execvpe(file, args)
Feb 14 18:28:26 xmg /usr/lib/gdm/gdm-x-session[1061]:   File "/usr/lib/python3.6/os.py", line 604, in _execvpe
Feb 14 18:28:26 xmg /usr/lib/gdm/gdm-x-session[1061]:     raise last_exc.with_traceback(tb)
Feb 14 18:28:26 xmg /usr/lib/gdm/gdm-x-session[1061]:   File "/usr/lib/python3.6/os.py", line 594, in _execvpe
Feb 14 18:28:26 xmg /usr/lib/gdm/gdm-x-session[1061]:     exec_func(fullname, *argrest)
Feb 14 18:28:26 xmg /usr/lib/gdm/gdm-x-session[1061]: FileNotFoundError: [Errno 2] No such file or directory
Feb 14 18:28:26 xmg cinnamon-launch[1264]: GtkDialog mapped without a transient parent. This is discouraged.

**Steps to reproduce**
unknown, happens randomly while screen is locked
cinnamon crashes, restart fallback mode

**Expected behaviour**

**Other information**

**Comment by leigh123linux** [comment]
The trace is because Manjaro have missed the fallback requirements

https://github.com/linuxmint/Cinnamon/blob/master/files/usr/bin/cinnamon-launcher#L6

X is probably crashing.

Feel feel to reopen if you can provide error logging showing the crash is in cinnamon code.
