### ISSUE TITLE
Cinnamon becomes completely unresponsive when "Drag and drop is not supported" appears

### ISSUE THREAD

**Issue by nick-s-b** [linuxmint/Cinnamon#7294]
```
 * Cinnamon version (cinnamon --version)
Cinnamon 3.6.7

 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
Arch

 * Graphics hardware *and* driver used
Nvidia 387.34 
 * 32 or 64 bit
64bit
 ```

**Issue**
Occasionally, when you drag a picture or a link out of a web browser onto the desktop (happens with both Chromium and Firefox), Cinnamon becomes completely unresponsive and a message like this pops up:

![](https://i.imgur.com/aqmMErc.jpg)
*"Drag and drop is not supported. And invalid type was used".*

Mouse pointer remains in the drag state and you cannot click anywhere to dismiss this popup. You can switch to other applications (Alt+Tab or whatever you have it set as works) but you cannot click on them. In fact, you cannot click anywhere.

Few minutes after this, Cinnamon crashes and the message pops up: "Cinnamon has crashed, would you like to restart it..." but you cannot click on anything since the mouse pointer state is still in the "grab/drag" mode.

Also, in this state, you cannot press Enter/Return so if you go to Terminal and attempt to restart Cinnamon through "cinnamon --replace", you can't since you cannot press the Enter key. Even the Space key doesn't work in this mode.

I've attempted to go into the console (enter/space key works in there) and have tried to restart Cinnamon through console but when Cinnamon loads up again, the mouse still remains in the drag mode even after the Cinnamon restart!

**Steps to reproduce**
I haven't been able to retrace steps and reproduce this reliably. It happens maybe once a week to me.

**Comment by leigh123linux** [comment]
Nemo draws the desktop not cinnamon.
