### ISSUE TITLE
Unable to select network audio device on "cinnamon-settings sound"

### ISSUE THREAD

**Issue by edaubert** [linuxmint/Cinnamon#7295]
```
 * Cinnamon 3.4.6
 * Linux Mint 18.2 (given by `cinnamon-settings info` but I am pretty sure I have done the update to 18.3)
 * 64 bit
 ```

**Issue**
I have 2 computers with one connected to my audio system.

I have followed some tutorials to enable audio network devices to be able to share this system and play every song on it no matter the computer playing.

After having enable the network audio devices, I am unable to manage them on `cinnamon-settings sound`.

**Steps to reproduce**
Basically I install `paprefs` and activate some options:
- on server side (the one directly connected to the audio system)
![network-access-server](https://user-images.githubusercontent.com/588130/36355664-0282d4f2-14e7-11e8-8f63-e257f6e81fdf.png)
- on client side (the one which needs to access the audio system through the server)
![network-access-client](https://user-images.githubusercontent.com/588130/36355662-01674f30-14e7-11e8-9736-85d8e4c8d4f6.png)

In addition I have copied the .pulse-cookie from server to client.
```
scp my-server:.pulse-cookie ~/.pulse-cookie
```
After restarting my session (I don't know if it is required) and using `pavucontrol`, I am able to manipulate network audio device on the client side but in `cinnamon-settings sound`, there is no way to manipulate them.
At the background, you can see the `pavucontrol` list of devices while at the foreground there is only my local audio device on `cinnamon-settings sound`.
![audio-devices-client-side](https://user-images.githubusercontent.com/588130/36355699-655009d8-14e7-11e8-8669-4e96b232a5e1.png)

**Expected behaviour**

What I was expecting is to see my network audio devices displayed on `cinnamon-settings sound`. so that I can use them without having to open an additional program (`pavucontrol`).

**Other information**

Looking on existing issues, I found https://github.com/linuxmint/Cinnamon/issues/7053 but I don't know if it is related and I can't update my system to test later version of cinnamon.

In addition I am able to see my bluetooth headphones:
![bluetooth-devices](https://user-images.githubusercontent.com/588130/36355733-fa47f172-14e7-11e8-926b-ecea1395b78a.png)

**Comment by icarter09** [comment]
@edaubert have you upgraded to the latest version of Cinnamon? And if so, does this issue still persist?

**Comment by edaubert** [comment]
Unfortunately I can't test it yet and I won't be able to do it before
several months.

When I will be able to look at it, I will check it and give you some
feedback.

Thanks for the great work.

Le mar. 10 juil. 2018 à 05:09, icarter09 <notifications@github.com> a
écrit :

**Comment by edaubert** [comment]
Hi,

After such a long time, I am able to confirm that the network devices now appears on `cinnamon-settings sound`.

Thanks a lot!
