### ISSUE TITLE
power@cinnamon.org applet doesn't recognize critical low battery power

### ISSUE THREAD

**Issue by andreabellitto** [linuxmint/cinnamon#7300]
```
 * Cinnamon version
3.6.7
 * Distribution
Ubuntu 17.10
 * Graphics hardware *and* driver used
Intel hd4000 integrated drivers + nvidia gtx860m 390.25
 * 32 or 64 bit
x64
 ```

**Issue**
Using power@cinnamon.org applet if the battery level goes down to a critical low level, it doesn't react notifing the user and doesn't react in any way eg. suspending or hibernating the pc, so the noteook will switch off without any notification and you will lost your work.
This is a very annoing bug, expecially when watcghing a fullscreen movie so the battery indicator on the system bar is hidden or when you are focused on some work and you doesn't keep attention on that area.

**Steps to reproduce**
Let the laptop battery discarge until the notebook will switchoff unaxpectly  

**Expected behaviour**

I will see a notification of critical low battery level, if I don't react the laptop automatically suspend or hibernate itself preventing any data loss.

**Other information**

**Comment by smurphos** [comment]
Not a solution to the issue as presented but you could use [BAMS](https://cinnamon-spices.linuxmint.com/applets/view/255),  [BAMS Github](https://github.com/linuxmint/cinnamon-spices-applets/tree/master/batterymonitor@pdcurtis) as an alternative to the stock power applet.

**Comment by Fornost461** [comment]
The following works for me, using **dconf Editor**.
Adjust the following parameters of the section **org.cinnamon.settings-daemon.plugins.power**:
- **use-time-for-policy**: whether to base behavior on estimated remaining time or on a percentage of the battery charge
- **critical-battery-action**: the action to perform
- **percentage-action**: the percentage at which action is taken
- **percentage-critical**: the percentage at which a notification appears
- **time-action**: the time at which action is taken
- **time-critical**: the time at which a notification appears

**Comment by icarter09** [comment]
@andreabellitto are you still experiencing this issue?

**Comment by andreabellitto** [comment]
> @andreabellitto are you still experiencing this issue?

I'm sorry, I don't use Cinnamon anymore.

**Comment by icarter09** [comment]
@andreabellitto no worries. Thanks for the update.

**Comment by Fornost461** [comment]
To solve this issue, I suggest adding access to these settings in the power management control center: this would be more user-friendly than dconf editor.

Or at least, I think you should use different defaults. I suggest the following defaults (in org.cinnamon.settings-daemon.plugins.power). They have been working well for me.

use-time-for-policy: false
percentage-low: 20
percentage-critical: 15
percentage-action: 10

(The problem with the current defaults is that they start the hibernation procedure way too late, so the laptop runs out of power before hibernation completes.)
