### ISSUE TITLE
Mouse Artefacts Cinnamon on HDMI with Intel Braswell N3150

### ISSUE THREAD

**Issue by rbo8383** [linuxmint/Cinnamon#7302]
```
 * Cinnamon version 3.6.7+sylvia
 * Distribution - (Mint 18.3)
 * Intel Braswell N3150 Cherryview i915
 * 64 bit
 ```

**Issue**
Mouse Artefacts mostly in Cinnamon Panel, Desktop, and application window titles on any HDMI port, but not on VGA ports on Intel Braswell N3150

**Steps to reproduce**
Trivial install

**Expected behaviour**
No Artefacts

**Other information**
# ---------------------------------------------------------------------------
Test 1: Vanilla 18.3 Cinnamon new install, kernel 4.10.0-38-generic

Test 1.1 using Default Cinnamon Session (assume hardware rendering):

-Mouse Artefacts mostly in Cinnamon Panel, Desktop, and application window titles
-No problems with KODI 17.6 (uses VAAPI / VPDAU)
-Problem only occurs on HDMI ports, regardless of monitor or hdmi cable
-No problems on VGA ports

Test 1.2 using Cinnamon Software Rendering Session :

-No Artefacts
-No problems with KODI (uses VAAPI / VPDAU)
-No problems on VGA ports

# ---------------------------------------------------------------------------
Test 2: Cinnamon 18.3 upgraded to the latest kernel 4.13.0-32-generic and mesa stack.

Mesa 17.2.8
XORG 1.18.4
X.Org Video Driver: 20.0
i915 1.6.0 20170619

Same test problems as in Test 1.1, and 1.2, with exact same results

# ---------------------------------------------------------------------------
Test 3: Cinnamon 18.3 on Intel Core I5-5200U / Broadwell Gen8 rev 9

Same Cinnamon tests as Test 1 and 2, WITHOUT ANY PROBLEMS

# ---------------------------------------------------------------------------
Conclusion :

Option 1 : Cinnamon wrong use of drivers as KODI works fine
OPtion 2 : i915 driver buggy for HDMI
OPtion 3 : Mesa / Graphics stack buggy
Option 4 : Intel Braswell firmware has HDMI flaw

Could be other things beyond my comprehension
Will submit logs / files needed when triaged

**Comment by leigh123linux** [comment]
Graphics driver issues aren't fixable within cinnamon code
