### ISSUE TITLE
Which variants of the Python module for pam integration is Cinnamon meant to support? 

### ISSUE THREAD

**Issue by eli-schwartz** [linuxmint/Cinnamon#7313]
https://github.com/linuxmint/Cinnamon/blob/2dc04b8a26fa7a672c579ed62a70dca6c6e4b295/files/usr/share/cinnamon/cinnamon-settings/modules/cs_user.py#L3-L6

AFAICT this is meant to support multiple variants of python2-pam, introduced in 768238facbbabed1e7f0182e3e6ccb119c85afdb as nothing but an import alias.

I don't think it makes much sense at all to attempt to support the same module under multiple names, as `import PAM` will never be exactly the same module as `import pam`...
Unless there is another version I'm unaware of -- I only know of the mysterious `PAM` module used in Debian which has no existing upstream, and several forks of https://atlee.ca/software/pam/ which provide python3 support.

I discovered this while trying to clean up the Arch Linux package, which uses the `pam` module from atlee.ca, not the `PAM` module in Debian.

Unfortunately, if that is what this is intended to deal with, it fails due to the fact that they have a very different API. The `PAM` module uses https://github.com/linuxmint/Cinnamon/blob/c71b0c257bc0d664f64b7fbf25622a1135112401/files/usr/share/cinnamon/cinnamon-settings/modules/cs_user.py#L349-L356

Whereas `pam` seems to expect `import pam; pam.authenticate(username, password, 'passwd')`

Obviously this doesn't work for us at all (and never did, I guess), but I thought I would ask here before simply deleting and replacing our python2-pam package. If the intent is to support both, you can check `hasattr(PAM, 'authenticate')` to see if you can use the (IMHO a lot cleaner) atlee.ca version.

**Comment by collinss** [comment]
When I first authored that change, I was attempting to make cinnamon settings work with both python2 and python3 to ease transition. However, I ended up doing a complete port, and cinnamon-settings now only uses python3, so we can probably remove the try/except entirely and just use the python3 version of pam.

**Comment by eli-schwartz** [comment]
This really has nothing to do with the python2 vs python3 versions, as there seems to be a Debian ticket open to provide a downstream python3 port for `PAM`, and `pam` was forked to provide python3 support long ago.

Unless you're suggesting that there is a python3 module available under `import pam` which has the same API as the python2 module from Debian available as `import PAM`?

In fact, the change I'm looking at was authored by @dalcde who seems to be a fellow Arch Linux user (in which case it would seem to very much be a failed attempt to support Arch Linux).

I'm sure I could provide a python3 version of either one in our repos, if I had to.

**Comment by leigh123linux** [comment]
I am using python3-pam for cinnamon git

https://src.fedoraproject.org/cgit/rpms/python-pam.git/tree/python-pam.spec

**Comment by eli-schwartz** [comment]
How can you even, considering that while it does implement support for `import pam as PAM; auth = PAM.pam()` it does not implement `auth.start('passwd')` or indeed any of this other boilerplate.

Other than moving `auth = PAM()` to `auth = PAM.pam()` (so that line now works), it does not implement `auth.start()`, `auth.set_item()`, or `auth.acct_mgmt()`, `PAM.PAM_USER`, or `PAM.PAM_CONV`, or `PAM.error`.

**Comment by eli-schwartz** [comment]
I've seen other projects try to support both, so there you have it. ^^
