### ISSUE TITLE
auto window scaling for hidpi breaks in portrait tablets

### ISSUE THREAD

**Issue by joequant** [linuxmint/Cinnamon#7317]
```
 * Cinnamon version (cinnamon --version) 3.6.6
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mageia cauldron
 * Graphics hardware *and* driver used Intel
 * 32 or 64 bit 64-bit
 ```

**Issue**
I have a 3000x2000 tablet and when it is in landscape mode, it appears properly in hidpi mode.  However when I change it to portrait mode 2000x3000, it goes out of hidpi mode if window scaling is set in auto.

Everything works when I switch windows scaling to HiDPI.  My suspicion is that the logic for Auto HiDPI breaks when it gets pushed into a 2000x3000 portrait display.

Let me know where I should be looking for the code since I think I can help fix it if I know where to look for.

**Steps to reproduce**

**Expected behaviour**

**Other information**

**Comment by leigh123linux** [comment]
Please file the issue against cinnamon-settings-daemon

https://github.com/linuxmint/cinnamon-settings-daemon/blob/master/plugins/xsettings/csd-xsettings-manager.c#L227
