### ISSUE TITLE
[Feature] Make virtual desktops orderable

### ISSUE THREAD

**Issue by tgaertner** [linuxmint/cinnamon#7319]
I would like to have a possibility to change the position of a virtual desktop in the Workspace overview. There could be an area next or inside the desktop-preview where you can drag it and move it to an other position.

**Comment by icarter09** [comment]
@collinss can this ticket be closed?

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
