### ISSUE TITLE
Fedora 27 Cinnamon fails to show desktop on latest kernels

### ISSUE THREAD

**Issue by brianread108** [linuxmint/Cinnamon#7323]
```
 * Cinnamon version (cinnamon --version)
3.6.7
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
Fedora 27 (fully up to date)
 * Graphics hardware *and* driver used
01:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Oland XT [Radeon HD 8670 / R7 250/350] [1002:6610] (prog-if 00 [VGA controller])
	Subsystem: Micro-Star International Co., Ltd. [MSI] Device [1462:3011]
	Flags: bus master, fast devsel, latency 0, IRQ 26, NUMA node 0
	Memory at d0000000 (64-bit, prefetchable) [size=256M]
	Memory at fdd80000 (64-bit, non-prefetchable) [size=256K]
	I/O ports at ee00 [size=256]
	[virtual] Expansion ROM at 000c0000 [disabled] [size=128K]
	Capabilities: <access denied>
	Kernel driver in use: radeon
	Kernel modules: radeon

 * 32 or 64 bit
64
 ```

**Issue**

When I use Kernel version 4.15.4-300.fc27.x86_64 or 4.15.6-300.fc27.x86_64 after logon the screens go blank, after a while the cursor moves to the centre of the primary screen but nothing else happens after that.
If I load Kernel 4.15.3-300.fc27.x86_64  then things work as normal (although it has gone quite slow for that last stage)

I tried Mate and also Openbox with the never kernels and they both work (although I could not logoff / reboot) from Mate.

**Steps to reproduce**
Boot from newer kernels  and logon into cinnamon

**Expected behaviour**
cinnamon desktop shows up.

**Other information**
Happy to provide more information as long as you tell me how to access it!

**Comment by leigh123linux** [comment]
You will need to report the issue against mesa-drivers or kernel at redhat bugzilla.

**Comment by brianread108** [comment]
Even though it works for Mate and Openbox?

**Comment by leigh123linux** [comment]
Mate and openbox don't depend on working 3d accelerated graphics to function.

**Comment by brianread108** [comment]
Ok, fine, I'll post a link to the bug here once I've done it.

**Comment by brianread108** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1551573
