### ISSUE TITLE
Cinnamon restoring monitors layout issue

### ISSUE THREAD

**Issue by kubaceg** [linuxmint/cinnamon#7324]
```
 * Cinnamon version: 3.6.7
 * Distribution - Mint 18.3
 * Graphics hardware *and* driver used: intel
 * 64 bit
 ```

**Issue**
I have 2nd monitor connected through ThinkPad USB 3.0 Ultra Dock (DisplayLink technology). After I turn on computer cinnamon has often (not every time) problems with enabling 2nd display. What is weird it works in few way:
- just after cinnamon starts, second display works in same layout as before,
- just after cinnamon starts, second display is disabled, I go into screens app and enable second screen, it works propertly,
- just after cinnamon starts,  second display is disabled, I go into screens app and enable second screen freezes I must restart X, and try setup layout again (sometimes few times)

**Steps to reproduce**

**Expected behaviour**
Just after cinnamon starts, second display works in same layout as before.

**Other information**

**Comment by mdphoto** [comment]
I have same bug with ThinkPad X220, Ultra Dock and VGA or display port.

**Comment by Vahan86** [comment]
@kubaceg, is this still an issue in Cinnamon 4.2?

**Comment by kubaceg** [comment]
Nope. I forgot about this bug so It's work fine :)
