### ISSUE TITLE
Consider bundling a better calculator with Mint

### ISSUE THREAD

**Issue by CottonEaster** [linuxmint/Cinnamon#7328]
I file this here because https://github.com/linuxmint/gnome-calculator had no 'issues' tab and I did not know where else to put this suggestion
```
 * Cinnamon version (cinnamon --version) 3.6.7
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 18.3
 * Graphics hardware *and* driver used: largely irrelevant
 * 32 or 64 bit: 64
 ```

**Issue**

The buttons on the gnome-calculator, especially the plus and multiply and divide buttons, are hard to distinguish one from another. This makes working with the calculator a pain, at least if one has no numeric keypad.

Screenshot:

![image](https://user-images.githubusercontent.com/9998846/37057756-48e460d2-2180-11e8-8367-10172cb6ddd5.png)

For comparison, here is the calculator bundled with Windows 8.1

![image](https://user-images.githubusercontent.com/9998846/37057955-eef89128-2180-11e8-819e-99015be6ffb0.png)

That Windows calculator too does has fairly indistinguishable keys, but it's definitely a (small-ish) step up from Mint's calculator in that respect.

I imagine there are some good FOSS calculators - ones that are better, in the basic usability respect that I am talking about, than the Gnome one and even the Windows one. If so, then you could use one of those better calculators instead of the Gnome one. Or perhaps you could tweak the Gnome one. (Different colours for the different buttons? Bigger buttons?)

Why does this matter? Well, it is a matter of basic usability, and I imagine we want to do at least as well as Windows.

**Comment by NikoKrause** [comment]
You can find a link to the GNOME bug tracker here: https://help.gnome.org/users/evolution/stable/problems-reporting-bugs.html.en

**Comment by CottonEaster** [comment]
Gnome itself seems to be up to version 6.6 of the calculator. 

![image](https://user-images.githubusercontent.com/9998846/37063924-05a89c9e-2193-11e8-9226-6508b36d3b57.png)


Mint has version 3.18.3. I suspect that if I file a bug against that version on the Gnome bug tracker (and thank you for the link), it will get no traction.

**Comment by NikoKrause** [comment]
The newest GNOME calculator version is 3.27.92 (to be seen here https://github.com/GNOME/gnome-calculator/releases)

The version 6.6.x refers to the gcalctool. See here: https://github.com/GNOME/gnome-calculator/blob/master/NEWS 
It says:
> Overview of changes in gnome-calculator 3.27.92
> ...
> Overview of changes in gcalctool 6.6.0

**Comment by leigh123linux** [comment]
Doesn't mint bundle their own version?

https://github.com/linuxmint/gnome-calculator

**Comment by CottonEaster** [comment]
I've filed a bug with gnome: https://bugzilla.gnome.org/show_bug.cgi?id=794140.
