### ISSUE TITLE
Feature proposal: Sound applet's tooltip should show "artist - title" in addition to "Volume: nn%"

### ISSUE THREAD

**Issue by sphh** [linuxmint/cinnamon#7334]
```
 * Cinnamon version: Cinnamon 3.6.7
 * Distribution: Linux Mint 18.3 Cinnamon 64-bit
 ```

**Issue**

The sound applet shows "Volume: xx%" in the tooltip, if you move the mouse cursor over it (_not_ clicking on the applet's icon).

It would be great, if it could show the currently played artist and title too.

**Motivation**

I know, there is the configuration option "Show song information on the panel", but this takes a lot of space.

I could click on the applet's icon to show the menu, but if I just want to have a quick glimpse at the artist and title, this requires two clicks (one to show and one to hide the menu).

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
