### ISSUE TITLE
Cinnamon frequently crashes while running vmware

### ISSUE THREAD

**Issue by maroc81** [linuxmint/cinnamon#7335]
```
 * Cinnamon version: 3.6.7
 * Distribution - Ubuntu 16.04
 * Nvidia 384.111
 * 64 bit
 ```

**Issue**
Cinnamon frequently crashes while I'm running vmware workstation pro 12.5.7 with a windows guest.  The amount of time between crashes can be a few hours or a few minutes.

**Steps to reproduce**
Run vmware workstation.  Wait for cinnamon to crash.

**Expected behaviour**
Cinnamon does not crash

**Other information**
Backtrace from ubuntu crash log with cinnamon debug packages installed:
https://gist.github.com/maroc81/6db2b8f0f3aef842253e0a336a6689fb

This may be related to #5752.

**Comment by maroc81** [comment]
Looking at the stacktrace, I may need to file this against cjs.

**Comment by icarter09** [comment]
@maroc81 are you still experiencing this issue? And did you ever file it against cjs?

**Comment by maroc81** [comment]
@icarter09 I upgraded to Ubuntu 18.04 and gnome shortly after this.  I never did file against cjs.
