### ISSUE TITLE
Open Applet with a Keyboard Shortcut - or Shell Command

### ISSUE THREAD

**Issue by jnvandermeer** [linuxmint/cinnamon#7337]
Dear all,

Is there a way to use a keyboard shortcut to pop open applets (now a mouse-only affair)? For example the windows-quick-list, or the sound settings would be great to have automatized this way.

If there is already a way to use bash commands to do stuff like this it'd be great, but I don't know if this is the case?

Thanks for your time
Johan

**Comment by collinss** [comment]
There is a way to do this, but the applet itself has to implement it. There are a few 3rd party applets that do this, and the menu applet does as well, but afaik it's the only stock applet that does. It probably wouldn't be too hard to implement in some of the other stock applets. Do you have any in particular that you would like to see added (other than the ones you already mentioned)? (*please note that there is no guarantee that this will actually be implemented as we get a lot of good feature requests, but limited time to work on them)

**Comment by jnvandermeer** [comment]
Dear Stephen,

Is it OK to answer like this?

For the Network applet it might also be nice. I thought therefore that if
there's a way to make it applet-agnostic, it might be more useful for any
other applets (maybe Remminna, even though it's probably not an applet...)
as well. Right now they are one of the few things in cinnamon that's not
accessible via shortcuts.

Thanks a lot for your time and fast reply!
Johan

**Comment by collinss** [comment]
There's not really an easy way to make this applet-agnostic. I'm sure it could be done, but it would almost certainly require changes to each of the applets, as well as substantial changes to cinnamon itself.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
