### ISSUE TITLE
Network manager applet in Cinnamon should have a scroll bar

### ISSUE THREAD

**Issue by mcvittal** [linuxmint/Cinnamon#7339]
This is more of a feature request than an issue, but its still frustrating. 

```
 * Cinnamon version (cinnamon --version) 3.4.6
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Debian
 * Graphics hardware *and* driver used - Intel Integrated graphics 
 * 32 or 64 bit - 64 bit
 ```

**Issue**

Occasionally, if I bring my laptop over to a friends apartment, there are a large number of networks available to connect to. Since the network applet has no scroll bar, the list of networks becomes larger than my vertical screen resolution, making it not possible to see the strongest networks in the list. 

**Steps to reproduce**

Open the network applet when there are lots of SSIDs available 

**Expected behaviour**

There should be a scroll bar, but instead there isnt so a lot of networks get cut off.

**Other information**

**Comment by JosephMcc** [comment]
https://github.com/linuxmint/Cinnamon/issues/5660
