### ISSUE TITLE
Feature Request: Show Virtual VLAN Connections in Network tray panel

### ISSUE THREAD

**Issue by vitalisator** [linuxmint/cinnamon#7344]
```
 * Cinnamon version 3.6.7
 * Distribution - 18.3
 * Graphics hardware - Intel Sky Lake Integrated Graphics
 * 64 bit
 ```

**Issue**
It is not possible to switch on/off the Virtual VLAN connections via network tray panel.

**Steps to reproduce**
1. add a new Virtual VLAN connection to NetworkManager (either CLI or GUI)
2. left mouse klick to  network system tray
3 the VLAN connection is absent, and can not be switched on or off

It is only possible to enable or disabel the VLAN Type connections via nmi-cli command

**Expected behaviour**
It should be possible to enable the visibility of virtual VLAN connections in network system tray.
i.e. with right mouse klick to network system tray -> Manage Virtual connections (on/off)
But that could be disabled by default.

**Other information**
One can switch the virtual VLAN connections via Systemsettings->Network.
But there is an bug that you can only disable the connection. After the VLAN connection is disabled once, it ca not be reenabled via the same way. The switcher element disappears.

**Comment by icarter09** [comment]
@vitalisator are you still experiencing this issue?

**Comment by vitalisator** [comment]
Yes, and same behavior under:
Cinnamon 4.2.4
Linux Mint 19.2 Tina

**Comment by leigh123linux** [comment]
The applet isn't meant to show VLAN so this isn't a bug.

https://github.com/linuxmint/cinnamon/blob/master/files/usr/share/cinnamon/applets/network%40cinnamon.org/applet.js#L18

**Comment by vitalisator** [comment]
ok, than please label this one as feature request.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
