### ISSUE TITLE
Desklet modifications not taken into account at reload

### ISSUE THREAD

**Issue by QuentinDanjou** [linuxmint/Cinnamon#7348]
```
 * 3.6.7
 * Mint 18.3
 * Intel integrated
 * 64 bit
 ```

**Issue**
After modifying a Desklet js file a reload of the desklet will use a 'buffered' version and not the new one until closing session.

**Steps to reproduce**
1- Modify a desklet.js file by adding a `global.log` for example.
2- Save the file
3- Add the "new" desklet to your workspace
4- Watch the missing log in Cinnemon debugger (Melange)

**Expected behaviour**
Should use the lastest version of code when adding it

**Other information**
The issue appeared after I switched from Mint 18.2 to Mint 18.3

**Comment by jaszhix** [comment]
This is a known issue with Cinnamon 3.6, its been fixed in Cinnamon 3.8.

**Comment by jaszhix** [comment]
@QuentinDanjou Do you have a link to the desklet you're developing?
