### ISSUE TITLE
Menu applet: vert align shutdown / logout / lock to bottom of menu

### ISSUE THREAD

**Issue by rik-shaw** [linuxmint/Cinnamon#7350]
```
 * Cinnamon version 3.6.7
 * Distribution - Ubuntu 18.04
 ```

**Issue**
If the number of "favorites" is relatively few but the number of categories of Cinnamon applications in the main menu grows, the shutdown / logout / lock icons float up the side of the menu applet.  I would think a better alignment would be to have favorites top-aligned and session icons bottom aligned, so if there were more categories than favorites the blank space would be in the middle of the favorites and session icons, not at the bottom.

![cinnamonmenu](https://user-images.githubusercontent.com/2560632/37345895-ff0d69f4-26de-11e8-8d4b-d63a86dcb03d.png)

**Comment by JosephMcc** [comment]
Thanks for the suggestions but I'd like to keep these all in one issue: https://github.com/linuxmint/Cinnamon/issues/6239

**Comment by rik-shaw** [comment]
@JosephMcc no problem!  Since this is referenced by that issue it should be OK in not getting lost.
