### ISSUE TITLE
Desktop Zoom Lens mode fuzzy (bilinear or cubic filtered?)

### ISSUE THREAD

**Issue by Siesh1oo** [linuxmint/cinnamon#7352]
When using the desktop zoom lens via Settings->Accesibility, the magnified screen content is unexpectedly fuzzy and low-contrast, even for integer magnification ratios (2, 4, 8 etc). Possibly the texture filter for upscaling is set to smoothing=interpolate between neighboring pixels?

```
 * Cinnamon version (cinnamon --version)
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
 * Graphics hardware *and* driver used
 * 32 or 64 bit
 ```

**Issue**

**Steps to reproduce**

**Expected behaviour**

**Other information**

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
