### ISSUE TITLE
"Cycle through open windows" and "Cycle backwards through open windows" do the same thing.

### ISSUE THREAD

**Issue by lrem** [linuxmint/cinnamon#7355]
```
 * Cinnamon version - Cinnamon 3.4.6
 * Distribution - Debian buster/sid
 * Graphics hardware *and* driver used - Quadro K1200 Driver Version: 384.98   
 * 64 bit
 ```

**Issue**
The direction of window traversal for both "Cycle through open windows" and "Cycle backwards through open windows" is the same.

**Steps to reproduce**
Bind "Cycle through open windows" to one key, "Cycle backwards through open windows" and press said keys a few times - there's no difference which one is pressed.

**Expected behaviour**
Keys would cycle windows in exactly opposite orders.

**Other information**

**Comment by icarter09** [comment]
We believe this issue is fixed. Please test against the latest Cinnamon version (4.2). 

If the issue happens again, create a new issue and add the output of "cinnamon-settings sound".
