### ISSUE TITLE
'Pick a font' shows unhelpful, rather strange search behaviour

### ISSUE THREAD

**Issue by CottonEaster** [linuxmint/Cinnamon#7357]
```
 * Cinnamon version (cinnamon --version): 3.6.7
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 18.3
 * Graphics hardware *and* driver used: NA
 * 32 or 64 bit: 64
 ```

**Issue**

'Pick a font' shows unhelpful, rather strange search behaviour.

**Steps to reproduce**

Search (System Settings -> Fonts -> [e.g.] Default Font) for 'Noto Sans UI'. Notice how one ends up, not at the font with that name, but with a font - some distance in the list from that font - with a similar name. Or try searching, with similar results, for 'Sans Regular'.

**Expected behaviour**

Searching should place the user at an entry that is a more exact match for the search string.

**Other information**

I apologise if I have reported this somewhere before. If I have, I can't find the report.

**Comment by JosephMcc** [comment]
The font chooser is supplied by Gtk. We have no control over it.

**Comment by CottonEaster** [comment]
OK - I'll file a bug with Gtk. For the font chooser really does not work well and thus gets in the way of doing stuff on Mint.

**Comment by leigh123linux** [comment]
@CottonEaster  Before wasting time filing an issue against some legacy/unsupported gtk version you should test with gtk-3.22 to confirm it still exists.

**Comment by CottonEaster** [comment]
It's not easy for me to try that later version of gtk, though. So: never mind.
