### ISSUE TITLE
upgrade

### ISSUE THREAD

**Issue by Kijedi** [linuxmint/Cinnamon#7362]
```
 * Cinnamon version (cinnamon --version)
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
 * Graphics hardware *and* driver used
 * 32 or 64 bit
 ```

**Issue**
An upgrade in the terminal does not update the GUI  for upgrade

**Steps to reproduce**

**Expected behaviour**

When i upgrade my packages through the terminal, the GUI version for upgrade should be updated that i have already upgraded the packages.

**Other information**

**Comment by NikoKrause** [comment]
I guess you're talking about mintupdate?
You need either to refresh mintupdate or wait till it refreshes on it's own.
The refresh rate can be set in Settings -> Auto-Refresh
