### ISSUE TITLE
Menu search: Keywords not matched IF exists in another App Name

### ISSUE THREAD

**Issue by rik-shaw** [linuxmint/cinnamon#7364]
```
 * Cinnamon version 3.6.7
 * Distribution - Ubuntu 16.04 / 18.04
 ```

**Issue**
When searching with the Main Menu, *sometimes* keywords are not matched.  It seems more common for keywords related to system settings items.  For example, words such as "tiling", "keyboard", or "control" are not matched if added to a desktop file's Keywords (simple to add such words to any /usr/share/applications/*.desktop file and then restart cinnamon).  But other such words like "foo" are also NOT matched (again after a restart of cinnamon).

In the following (for "Klavaro", a typing tutor):
```Keywords=keyboard;typing;tutor;CAI;tiling;foo;bob;```

ONLY the following are matched: typing, tutor, CAI, bob.
SO, the following are NOT matched: keyboard, tiling, foo

Is there maybe some "blacklist" of keywords somewhere or what else would be blocking these keywords from being matched?  Or???

**Comment by rik-shaw** [comment]
UPDATE: I believe I understand the problem better now.  IF there is a match found on a Application Name, then any results from other applications that have the word in Keywords are NOT included.

For example, if "foo" is added to Keywords for Klavaro, it will be found ONLY IF the game "swell FOOp" is not installed.  Once "swell FOOp" is installed, a search for "foo" will no longer return Klavaro.

**Comment by rik-shaw** [comment]
OK here is the problem: https://github.com/linuxmint/Cinnamon/blob/45339e811a694e101467a9cf6fcdd7fa6d82c899/files/usr/share/cinnamon/applets/menu%40cinnamon.org/applet.js#L3256

It seems that keywords and description are NOT searched if there is a positive result from "found by name".  This seems not right?  I would think it is good to return hits on keywords or description ALL the time, even if there is an app name hit?

**Comment by rik-shaw** [comment]
I modified the code for testing to basically ALWAYS search for keywords, by replacing

```if (!foundByname) {```
with
```if (pattern) {```
The problem is that a search for "foo" will now return from keywords correctly, but by being sorted alphabetically it will return Klavaro (with a keyword of "foo") ABOVE "Swell Foop" (a match on name).

So I am suspecting this is why Keywords weren't searched before IF there was an app name match.  I think the best would be to return all matches, but make sure the app name match is at the top of the list.  Possible?

**Comment by NikoKrause** [comment]
Ah yes, this is a can of worms. Your observations are right. It's a really long discussion about this going on: https://github.com/linuxmint/Cinnamon/issues/4053
Sorting menu entries is problematic right now.

**Comment by rik-shaw** [comment]
@NikoKrause thanks for the reference: indeed it seems important to have app name matches show up first, but really this is not the greatest solution if the user doesn't know the app name.  I am surprised no one else was concerned with the lost ability to search keywords or comments: the search results entirely depend now on what other apps are installed.

If a new app called "True IRC" is created, then Polari or any other IRC clients without IRC in the name will not be found anymore (but they WOULD be found if that app with IRC in the name wasn't installed).  

It seems that it can't be solved though without somehow tagging the results from the app name search which would then allow those ones to be put to the top of the list and still add additional hits from keywords or comments that would show below.

**Comment by NikoKrause** [comment]
I'm not a fan of the new method either. Therefore I didn't applied it to my CinnVIIStarkMenu applet.
This is a well known issue and sooner or later something will be done in this direction.

**Comment by NikoKrause** [comment]
Should be fixed by https://github.com/linuxmint/cinnamon/commit/a6738bd306180b4e2e668c90c1d7d5d6c0578906

**Comment by rik-shaw** [comment]
Yes, I can confirm that this has been addressed by the new updates.
