### ISSUE TITLE
Cinnamon always freezes after external monitor is unplugged or turned off via display settings.

### ISSUE THREAD

**Issue by orestarod** [linuxmint/Cinnamon#7365]
```
Cinnamon 3.6.6
Manjaro 17.1.6 Cinnamon community edition
Intel i7 5700HQ with HD Graphics 5600 GPU and
NVidia GTX 960M GPU
Using video-linux (open linux drivers)
64 bit
 ```

**Issue**
Cinnamon freezes completely when a plugged in second monitor is unplugged (issue happens on a laptop), and no action can be taken on the graphical environment. Suppose the external monitor is on the left, the primary monitor is on the right, and the external monitor has smaller resolution in width and height than the main. When the external monitor is unplugged, only the main monitor remains active, which was previously on the right side. Now, the main monitor is "split in half". On its left half, it shows the right side of what was on the external screen, before it was unplugged. On its right half, it shows the left side of what was on the main monitor, before the external monitor was unplugged. The two sides shown from the two screens are not shrinked, and thus extend beyond the monitor limits. Because the external left monitor had a smaller resolution, on the left half of the remaining main screen there is a blank area below its contents, equal in size with the difference in pixels between the external monitor and the main monitor. Switching to tty via keyboard is possible.

**Steps to reproduce**
Boot system and log into Cinnamon. Plug in external monitor. Unplug monitor, or disable it through the display settings. Cinnamon freezes as described above.

**Expected behaviour**
Cinnamon should not freeze after external monitor is unplugged or disabled through the display settings.

**Other information**
Will attach image next time I cause a crash. This behaviour has been present in older versions of Cinnamon too, on the same hardware.

**Comment by TheShed412** [comment]
I've been having a similar issue with multiple monitors. I've had this issue happen and a bunch of others. Currently my laptop refuses to sleep when the lid is closed. I just want to see if our issues can be combined in to one. Do you mind printing the inhibitors with `systemd-inhibit` and see if anything there is being listed as blocking?

**Comment by orestarod** [comment]
Issue fixed after latest update of Cinnamon and/or LightDM (both were updated at the same time so I cannot be sure which one fixed it).
