### ISSUE TITLE
Cannot uninstall flatpak directly from Cinnamon Menu

### ISSUE THREAD

**Issue by thecursedfly** [linuxmint/Cinnamon#7370]
```
 * Cinnamon version 3.6.7
 * Distribution - Mint 18.3
 * Intel graphics card (not relevant)
 * 64 bit
 ```

**Issue**

Using the Cinnamon Menu it's not possible to uninstall a flatpak application, unlike normal packages behavior.
Only the following message is provided: "this menu item is not assiciated to any package. Do you want to remove it from the menu anyway? No / Yes"

**Steps to reproduce**

Try to uninstall a flatpak application directly from the Cinnamon Menu

**Expected behaviour**

It is uninstalled; currently it's only possible to remove the menu entry.

**Comment by NikoKrause** [comment]
Hey, it was already reported somewhere else, but I can't find it right now.
It should be fixed in Mint 19.
