### ISSUE TITLE
18.3/3.6.6 Cinnamon Desktop Icon Size "Smaller" causes problems with positioning of items

### ISSUE THREAD

**Issue by Canule** [linuxmint/Cinnamon#7371]
```
 * Cinnamon version: cinnamon 3.6.6
 * Distribution: Similar behavior on multiple installations of Mint 18.3 x64
 * Graphics hardware *and* driver used: 1080p Intel i5 530 igHD/Nvidia 970/VMware Worsktation.tools 10.1.6<>Nvidia 650M
 ```

**Issue**
Only when the desktop icon size is set to "Smaller" items/folder/files get stacked.

**Steps to reproduce**
Set the desktop icons size to "**Smaller**", save files to desktop, rescale desktop or reboot
*Auto-arrange **off**
*Align to grid **on**

-Dragging items on top of each other manually(*once a folder is within the stack, dragged items can be added to the folder)
-Saving files to the desktop
-Rescale desktop (Virtual Machine full screen toggle for example)
-Booting the OS
[https://www2.pic-upload.de/img/35025531/stackedC.jpg](https://www2.pic-upload.de/img/35025531/stackedC.jpg)

**Expected behaviour**
Arrange icons across the desktop surface like "Normal" and "Larger" icon size behaves without Auto-arrange enabled.

**Other information**
*I was unable to take/manage a screenschot when the desktop context menu is open/displayed.

**Comment by leigh123linux** [comment]
Please file the issue against nemo as that draws the desktop.
