### ISSUE TITLE
[All official themes] text-decoration property on cinnamon-link class has no effect

### ISSUE THREAD

**Issue by Odyseus** [linuxmint/cinnamon#7372]
- Cinnamon version: 2.8.x to 3.6.x
- Distribution: Linux Mint 17.3 to 18.3

### Issue

The CSS `text-decoration` property defined in all the official Cinnamon themes (the default theme shipped with Cinnamon and the themes on the [linuxmint/mint-themes](https://github.com/linuxmint/mint-themes) repository) for the **cinnamon-link** class has no effect.

### Steps to reproduce

Use any of the official Linux Mint themes.

### Expected behavior

The URL defined in the website field for the xlets **About** dialog should be underlined.

### Other information

The **cinnamon-link** class is used in all **About** dialogs for xlets. All official themes set a style for this class like so (the `color` varies):

```css
.cinnamon-link {
    color: #0000ff;
    text-decoration: underline;
}
```

The style seems not to have any effect because the class **cinnamon-link** is applied to an [St.Button element](https://github.com/linuxmint/Cinnamon/blob/master/js/ui/modalDialog.js#L535).

Using the following CSS selector will apply the style correctly:

```css
.cinnamon-link StLabel {
    text-decoration: underline;
}

.cinnamon-link {
    color: #0000ff;
}
```

~~Or the **cinnamon-link** class could be defined in the [St.Label element](https://github.com/linuxmint/Cinnamon/blob/master/js/ui/modalDialog.js#L537) so the original style works as intended.~~ After some more testing, this doesn't seem like a good idea.

The fix will present a new *aesthetic problem*. In newer versions of Cinnamon, a tab character is applied to add indent to some of the text inside an **About** dialog. Decorating that text with an underline will result in underlining the tab character also.

![aboutdialog](https://user-images.githubusercontent.com/3822556/37595894-2133afc4-2b59-11e8-8d44-0a3d0ff0dcea.png)

**Comment by icarter09** [comment]
@Odyseus are you still experiencing this issue? If so, do you have any other thoughts on best possible solutions?

**Comment by Odyseus** [comment]
Hello, @icarter09:

This issue can be considered resolved since the **cinnamon-link** class isn't used anymore for the xlet's about dialogs (switched to a Gtk dialog in e530614656d6e36859bcf254d1ecf2f259f64875).

**Comment by icarter09** [comment]
@Odyseus thanks for the update and no worries on the late reply.
