### ISSUE TITLE
ubuntu bionic crash to greeter with login

### ISSUE THREAD

**Issue by irishbandit** [linuxmint/Cinnamon#7373]
```
Cinnamon 3.6.7 (Gtk 3.22.28) 
deb http://ppa.launchpad.net/gwendal-lebihan-dev/cinnamon-nightly/ubuntu bionic main
Kernel: 4.15.0-12-generic x86_64 bits: 64 
gcc: 7.3.0
Cinnamon 3.6.7 (Gtk 3.22.28) 
lightdm 
Ubuntu Bionic Beaver (development branch)

 ```

**Issue**
After upgrade to bionic could not login to cinnamon kept crashing back to login screen
errors reported in 
cinnamon-session[7991]: GLib-GIO-ERROR: t+0.01202s: Settings schema 'org.gnome.desktop.file-sharing' does not contain a key named 'enabled'#012aborting...

**Steps to reproduce**
try to login

**Expected behaviour**
desktop

**Other information**
after follwing the advice at 
https://askubuntu.com/questions/1012087/cinnamon-session-crashing-login-from-greeter
sudo apt-get purge gnome-user-share
problem is fixed.

**Comment by clefebvre** [comment]
https://github.com/linuxmint/cinnamon-session/commit/8955775fc881c3ac5ee4dc9e580a806aef81858d
