### ISSUE TITLE
inform user about smartd status

### ISSUE THREAD

**Issue by calestyo** [linuxmint/cinnamon#7383]
Hey.

This is a feature request for an official/included applet/extension/whatever that notifies the user of the system's devices SMART status.

I think for a desktop environment it's pretty important to notify the user about the SMART status, as most likely nothing like Icinga/Nagios (which would do the monitoring/notifying on larger clusters) runs and most users won't regularly read through all the syslogs.
Given it's importance (warning users about health problems of their storage devices), it should be included per default (though one should be able to disable it).

At least two approaches could be made:
a) use libatasmart4
b) rely on smartd performing the actual querying and just add a hook to /etc/smartmontools/run.d/ which invokes some notification inside cinnamon.

The advantage of (b) is that smartd allows quite some powerful control over what is actually checked (SMART offers different kinds of healt checks - not talking about the self-tests here) and even allows to manually map SMART attributes (for devices where strange attributes are used).
Offering this high level of control via GUI/libatasmart seems rather difficult.
The default config of smartd likely does something what a general check with libatasmart would do as well.

Another advantage of (b) is that there is one central point in the system which does the actual checks.
If cinnamon would do it's own direct checks, smartd might likely still run... and more unnecessary checks are sent to the disks.

Advantage of (a) is obviously that not further daemon is needed to run (which, I guess, runs however anyway per default on many distros).

Cheers,
Chris.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
