### ISSUE TITLE
Keyboard backlight bar vertically truncated

### ISSUE THREAD

**Issue by CottonEaster** [linuxmint/Cinnamon#7384]
```
 * Cinnamon version (cinnamon --version) 3.6.7.
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...): Mint 18.3
 * Graphics hardware *and* driver used: Mesa DRA Intel KabyLake GT1.5; 3.0 Mesa 17.2.8
 * 32 or 64 bit: 64
 ```

**Issue**

The keyboard backlight bar vertically truncated - see this image:

![image](https://user-images.githubusercontent.com/9998846/37753298-318af7f0-2d94-11e8-92d9-8dc7abdf0f31.png)

The problem (though I admit it is only a small problem) is constant.
**Steps to reproduce**

The problem may owe to my having enabled the 'Hi-DPI' setting. (See screenshot.)

**Expected behaviour**

The backlight bar should be fully visible.

**Other information**

Screen: 14.0" WQHD (2560x1440), IPS, on X1 Carbon.

**Comment by JosephMcc** [comment]
I have to admit you totally lost me here. I don't see what's wrong.

**Comment by CottonEaster** [comment]
@JosephMcc : sorry. I should have said: zoom in on the screenshot I provided. If you do, you will discover that, as I said, the backlight slider is vertically truncated. That is, it's bottom is missing.

**Comment by JosephMcc** [comment]
Sorry but no it isn't. Are you talking about the icon?

**Comment by CottonEaster** [comment]
You are right. I mean not the slider itself, narrowly construed but, yes, the icon.

**Comment by JosephMcc** [comment]
Ok. That's the way the icon is designed. There is no issue here. The slider is fine.

**Comment by CottonEaster** [comment]
Oh. I see. It does look like half of it is missing, doesn't it?
