### ISSUE TITLE
[cinnamon-settings, "Preferred Applications"] Add an "Other application..." option to the terminal dropdown

### ISSUE THREAD

**Issue by whitephoenix0** [linuxmint/Cinnamon#7392]
```
 * Cinnamon version (cinnamon --version)
3.6.7
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
Fedora 27
 ```

I've done a lot of configuration to the alacritty terminal and as such prefer to use it over the default terminal. I tried to change my preferred terminal in "Preferred Applications" but there was no option to pick another program. 

Every single other dropdown in the dialog (File Manager, Web, Music, Video, etc) allows choosing another program. For a terminal emulator, my only two options are the default GNOME terminal or xterm. It seems a bit silly to me that only one category doesn't have this option.

Screenshots: https://imgur.com/a/isQGy

**Comment by itzexor** [comment]
It works for me on arch using alacritty-git from AUR. How are you building/installing it? The provided [Alacritty.desktop](https://github.com/jwilm/alacritty/blob/master/Alacritty.desktop) file should be installed properly for it to show up in the list.

**Comment by whitephoenix0** [comment]
I was just compiling from source. That's good that it works with the proper .desktop, but I still think "Other application..." should be available like it is everywhere else

**Comment by JosephMcc** [comment]
> That's good that it works with the proper .desktop, but I still think "Other application..." should be available like it is everywhere else

The button for the terminal and the other buttons do not work the same internally. In the end I don't think any of them show you anything without properly installed desktop files so there is really no difference.
