### ISSUE TITLE
Cinnamon crashed

### ISSUE THREAD

**Issue by Wellifam** [linuxmint/Cinnamon#7403]
```
 * Cinnamon version (cinnamon --version)
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
 * 64 bit
 ```

**Issue**

Cinnamon crashes everytime I start the OS

===================================================================
 GDB Log                                                           
===================================================================
[New LWP 1688]
[New LWP 1689]
[New LWP 1691]
[New LWP 1690]
[New LWP 1696]
[New LWP 1692]
[New LWP 1698]
[New LWP 1693]
[New LWP 1694]
[New LWP 1695]
[New LWP 1697]
[New LWP 1818]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `cinnamon --replace'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f8e81700333 in ?? ()
[Current thread is 1 (Thread 0x7f8eacf18ac0 (LWP 1688))]

===================================================================
 GDB Backtrace                                                     
===================================================================
[New LWP 1688]
[New LWP 1689]
[New LWP 1691]
[New LWP 1690]
[New LWP 1696]
[New LWP 1692]
[New LWP 1698]
[New LWP 1693]
[New LWP 1694]
[New LWP 1695]
[New LWP 1697]
[New LWP 1818]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `cinnamon --replace'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f8e81700333 in ?? ()
[Current thread is 1 (Thread 0x7f8eacf18ac0 (LWP 1688))]
#0  0x00007f8e81700333 in  ()
#1  0x000056037a1f75a0 in  ()
#2  0x000056037a2335e0 in  ()
#3  0x3f8000003f800000 in  ()
#4  0x3f8000003f800000 in  ()
#5  0x0000000000000000 in  ()

===================================================================
 GDB Backtrace (all threads)                                       
===================================================================
[New LWP 1688]
[New LWP 1689]
[New LWP 1691]
[New LWP 1690]
[New LWP 1696]
[New LWP 1692]
[New LWP 1698]
[New LWP 1693]
[New LWP 1694]
[New LWP 1695]
[New LWP 1697]
[New LWP 1818]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `cinnamon --replace'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f8e81700333 in ?? ()
[Current thread is 1 (Thread 0x7f8eacf18ac0 (LWP 1688))]

Thread 12 (Thread 0x7f8e79dff700 (LWP 1818)):
#0  0x00007f8eaafe74d9 in syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
#1  0x00007f8eab55bcfa in g_cond_wait_until (cond=cond@entry=0x560378141c08, mutex=mutex@entry=0x560378141c00, end_time=end_time@entry=95398424) at /build/glib2.0-prJhLS/glib2.0-2.48.2/./glib/gthread-posix.c:1441
        now = {tv_sec = 80, tv_nsec = 398427573}
        span = {tv_sec = 14, tv_nsec = 999996427}
        sampled = 0
        res = <optimized out>
#2  0x00007f8eab4eb999 in g_async_queue_pop_intern_unlocked (queue=queue@entry=0x560378141c00, wait=wait@entry=1, end_time=end_time@entry=95398424) at /build/glib2.0-prJhLS/glib2.0-2.48.2/./glib/gasyncqueue.c:422
        retval = <optimized out>
        __func__ = "g_async_queue_pop_intern_unlocked"
#3  0x00007f8eab4ebfbb in g_async_queue_timeout_pop (queue=0x560378141c00, timeout=timeout@entry=15000000) at /build/glib2.0-prJhLS/glib2.0-2.48.2/./glib/gasyncqueue.c:543
        end_time = 95398424
        retval = <optimized out>
#4  0x00007f8eab53e60a in g_thread_pool_thread_proxy () at /build/glib2.0-prJhLS/glib2.0-2.48.2/./glib/gthreadpool.c:167
        pool = <optimized out>
        local_wakeup_thread_serial = <optimized out>
        last_wakeup_thread_serial = <optimized out>
        have_relayed_thread_marker = <optimized out>
        free_pool = <optimized out>
        task = 0x2
        pool = <optimized out>
#5  0x00007f8eab53e60a in g_thread_pool_thread_proxy (data=<optimized out>) at /build/glib2.0-prJhLS/glib2.0-2.48.2/./glib/gthreadpool.c:364
        free_pool = <optimized out>
        task = 0x2
        pool = <optimized out>
#6  0x00007f8eab53dbb5 in g_thread_proxy (data=0x56037a0f9280) at /build/glib2.0-prJhLS/glib2.0-2.48.2/./glib/gthread.c:780
        thread = 0x56037a0f9280
#7  0x00007f8eab2b76ba in start_thread (arg=0x7f8e79dff700) at pthread_create.c:333
        __res = <optimized out>
        pd = 0x7f8e79dff700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140249906804480, 9182224135158164056, 0, 140728467417903, 140249906805184, 94572899474256, -9191526279086675368, -9191699069017986472}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#8  0x00007f8eaafed41d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 11 (Thread 0x7f8e942a4700 (LWP 1697)):
#0  0x00007f8eab2bd360 in pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007f8e9cf216c0 in PR_WaitCondVar () at /usr/lib/x86_64-linux-gnu/libnspr4.so
#2  0x00007f8ea2e07eb1 in  () at /usr/lib/x86_64-linux-gnu/libjs.so.0
#3  0x00007f8e9cf270a8 in  () at /usr/lib/x86_64-linux-gnu/libnspr4.so
#4  0x00007f8eab2b76ba in start_thread (arg=0x7f8e942a4700) at pthread_create.c:333
        __res = <optimized out>
        pd = 0x7f8e942a4700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140250347882240, 9182224135158164056, 0, 140728467421807, 140250347882944, 1, -9191573714316105128, -9191699069017986472}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#5  0x00007f8eaafed41d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 10 (Thread 0x7f8e943a6700 (LWP 1695)):
#0  0x00007f8eab2bd360 in pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007f8e9cf216c0 in PR_WaitCondVar () at /usr/lib/x86_64-linux-gnu/libnspr4.so
#2  0x00007f8ea2e07eb1 in  () at /usr/lib/x86_64-linux-gnu/libjs.so.0
#3  0x00007f8e9cf270a8 in  () at /usr/lib/x86_64-linux-gnu/libnspr4.so
#4  0x00007f8eab2b76ba in start_thread (arg=0x7f8e943a6700) at pthread_create.c:333
        __res = <optimized out>
        pd = 0x7f8e943a6700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140250348939008, 9182224135158164056, 0, 140728467421807, 140250348939712, 1, -9191573854976284072, -9191699069017986472}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#5  0x00007f8eaafed41d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 9 (Thread 0x7f8e94427700 (LWP 1694)):
#0  0x00007f8eab2bd360 in pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007f8e9cf216c0 in PR_WaitCondVar () at /usr/lib/x86_64-linux-gnu/libnspr4.so
#2  0x00007f8ea2e07eb1 in  () at /usr/lib/x86_64-linux-gnu/libjs.so.0
#3  0x00007f8e9cf270a8 in  () at /usr/lib/x86_64-linux-gnu/libnspr4.so
#4  0x00007f8eab2b76ba in start_thread (arg=0x7f8e94427700) at pthread_create.c:333
        __res = <optimized out>
        pd = 0x7f8e94427700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140250349467392, 9182224135158164056, 0, 140728467421807, 140250349468096, 1, -9191573373403076008, -9191699069017986472}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#5  0x00007f8eaafed41d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 8 (Thread 0x7f8e944a8700 (LWP 1693)):
#0  0x00007f8eab2bd360 in pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007f8e9cf216c0 in PR_WaitCondVar () at /usr/lib/x86_64-linux-gnu/libnspr4.so
#2  0x00007f8ea2e07eb1 in  () at /usr/lib/x86_64-linux-gnu/libjs.so.0
#3  0x00007f8e9cf270a8 in  () at /usr/lib/x86_64-linux-gnu/libnspr4.so
#4  0x00007f8eab2b76ba in start_thread (arg=0x7f8e944a8700) at pthread_create.c:333
        __res = <optimized out>
        pd = 0x7f8e944a8700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140250349995776, 9182224135158164056, 0, 140728467421807, 140250349996480, 1, -9191573441585681832, -9191699069017986472}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#5  0x00007f8eaafed41d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 7 (Thread 0x7f8e94223700 (LWP 1698)):
#0  0x00007f8eab2bd360 in pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007f8e9cf216c0 in PR_WaitCondVar () at /usr/lib/x86_64-linux-gnu/libnspr4.so
#2  0x00007f8ea2e07eb1 in  () at /usr/lib/x86_64-linux-gnu/libjs.so.0
#3  0x00007f8e9cf270a8 in  () at /usr/lib/x86_64-linux-gnu/libnspr4.so
#4  0x00007f8eab2b76ba in start_thread (arg=0x7f8e94223700) at pthread_create.c:333
        __res = <optimized out>
        pd = 0x7f8e94223700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140250347353856, 9182224135158164056, 0, 140728467421807, 140250347354560, 1, -9191573646133499304, -9191699069017986472}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#5  0x00007f8eaafed41d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 6 (Thread 0x7f8e94ca9700 (LWP 1692)):
#0  0x00007f8eaafe174d in poll () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007f8eab51738c in g_main_context_iterate (priority=2147483647, n_fds=1, fds=0x7f8e840010c0, timeout=<optimized out>, context=0x560378426ab0) at /build/glib2.0-prJhLS/glib2.0-2.48.2/./glib/gmain.c:4135
        poll_func = 0x7f8eab526280 <g_poll>
        max_priority = 2147483647
        timeout = -1
        some_ready = <optimized out>
        nfds = 1
        allocated_nfds = 1
        fds = 0x7f8e840010c0
#2  0x00007f8eab51738c in g_main_context_iterate (context=context@entry=0x560378426ab0, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at /build/glib2.0-prJhLS/glib2.0-2.48.2/./glib/gmain.c:3835
        max_priority = 2147483647
        timeout = -1
        some_ready = <optimized out>
        nfds = 1
        allocated_nfds = 1
        fds = 0x7f8e840010c0
#3  0x00007f8eab51749c in g_main_context_iteration (context=0x560378426ab0, may_block=1) at /build/glib2.0-prJhLS/glib2.0-2.48.2/./glib/gmain.c:3901
        retval = <optimized out>
#4  0x00007f8e9864e28d in  () at /usr/lib/x86_64-linux-gnu/gio/modules/libdconfsettings.so
#5  0x00007f8eab53dbb5 in g_thread_proxy (data=0x56037841f990) at /build/glib2.0-prJhLS/glib2.0-2.48.2/./glib/gthread.c:780
        thread = 0x56037841f990
#6  0x00007f8eab2b76ba in start_thread (arg=0x7f8e94ca9700) at pthread_create.c:333
        __res = <optimized out>
        pd = 0x7f8e94ca9700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140250358388480, 9182224135158164056, 0, 140728467422255, 140250358389184, 94572902509232, -9191572345832150440, -9191699069017986472}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#7  0x00007f8eaafed41d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 5 (Thread 0x7f8e94325700 (LWP 1696)):
#0  0x00007f8eab2bd360 in pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007f8e9cf216c0 in PR_WaitCondVar () at /usr/lib/x86_64-linux-gnu/libnspr4.so
#2  0x00007f8ea2e07eb1 in  () at /usr/lib/x86_64-linux-gnu/libjs.so.0
#3  0x00007f8e9cf270a8 in  () at /usr/lib/x86_64-linux-gnu/libnspr4.so
#4  0x00007f8eab2b76ba in start_thread (arg=0x7f8e94325700) at pthread_create.c:333
        __res = <optimized out>
        pd = 0x7f8e94325700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140250348410624, 9182224135158164056, 0, 140728467421807, 140250348411328, 1, -9191573786793678248, -9191699069017986472}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#5  0x00007f8eaafed41d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 4 (Thread 0x7f8e97c28700 (LWP 1690)):
#0  0x00007f8eaafe174d in poll () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007f8eab51738c in g_main_context_iterate (priority=2147483647, n_fds=3, fds=0x7f8e880010c0, timeout=<optimized out>, context=0x560378142530) at /build/glib2.0-prJhLS/glib2.0-2.48.2/./glib/gmain.c:4135
        poll_func = 0x7f8eab526280 <g_poll>
        max_priority = 2147483647
        timeout = -1
        some_ready = <optimized out>
        nfds = 3
        allocated_nfds = 3
        fds = 0x7f8e880010c0
#2  0x00007f8eab51738c in g_main_context_iterate (context=0x560378142530, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at /build/glib2.0-prJhLS/glib2.0-2.48.2/./glib/gmain.c:3835
        max_priority = 2147483647
        timeout = -1
        some_ready = <optimized out>
        nfds = 3
        allocated_nfds = 3
        fds = 0x7f8e880010c0
#3  0x00007f8eab517712 in g_main_loop_run (loop=0x560378141ff0) at /build/glib2.0-prJhLS/glib2.0-2.48.2/./glib/gmain.c:4034
        __func__ = "g_main_loop_run"
#4  0x00007f8eabb159d6 in gdbus_shared_thread_func (user_data=0x560378142500) at /build/glib2.0-prJhLS/glib2.0-2.48.2/./gio/gdbusprivate.c:246
        data = 0x560378142500
#5  0x00007f8eab53dbb5 in g_thread_proxy (data=0x5603780b9140) at /build/glib2.0-prJhLS/glib2.0-2.48.2/./glib/gthread.c:780
        thread = 0x5603780b9140
#6  0x00007f8eab2b76ba in start_thread (arg=0x7f8e97c28700) at pthread_create.c:333
        __res = <optimized out>
        pd = 0x7f8e97c28700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140250408191744, 9182224135158164056, 0, 140728467420175, 140250408192448, 94572899476736, -9191565676284810664, -9191699069017986472}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#7  0x00007f8eaafed41d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 3 (Thread 0x7f8e95726700 (LWP 1691)):
#0  0x00007f8eab2bd360 in pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007f8e968fa48b in  () at /usr/lib/x86_64-linux-gnu/dri/r300_dri.so
#2  0x00007f8e968fa397 in  () at /usr/lib/x86_64-linux-gnu/dri/r300_dri.so
#3  0x00007f8eab2b76ba in start_thread (arg=0x7f8e95726700) at pthread_create.c:333
        __res = <optimized out>
        pd = 0x7f8e95726700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140250369386240, 9182224135158164056, 0, 140728467421007, 140250369386944, 0, -9191571037477737896, -9191699069017986472}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#4  0x00007f8eaafed41d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 2 (Thread 0x7f8e98429700 (LWP 1689)):
#0  0x00007f8eaafe174d in poll () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007f8eab51738c in g_main_context_iterate (priority=2147483647, n_fds=2, fds=0x7f8e900008e0, timeout=<optimized out>, context=0x560378141cf0) at /build/glib2.0-prJhLS/glib2.0-2.48.2/./glib/gmain.c:4135
        poll_func = 0x7f8eab526280 <g_poll>
        max_priority = 2147483647
        timeout = 3998
        some_ready = <optimized out>
        nfds = 2
        allocated_nfds = 2
        fds = 0x7f8e900008e0
#2  0x00007f8eab51738c in g_main_context_iterate (context=context@entry=0x560378141cf0, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at /build/glib2.0-prJhLS/glib2.0-2.48.2/./glib/gmain.c:3835
        max_priority = 2147483647
        timeout = 3998
        some_ready = <optimized out>
        nfds = 2
        allocated_nfds = 2
        fds = 0x7f8e900008e0
#3  0x00007f8eab51749c in g_main_context_iteration (context=0x560378141cf0, may_block=may_block@entry=1) at /build/glib2.0-prJhLS/glib2.0-2.48.2/./glib/gmain.c:3901
        retval = <optimized out>
#4  0x00007f8eab5174d9 in glib_worker_main (data=<optimized out>) at /build/glib2.0-prJhLS/glib2.0-2.48.2/./glib/gmain.c:5672
#5  0x00007f8eab53dbb5 in g_thread_proxy (data=0x5603780b90f0) at /build/glib2.0-prJhLS/glib2.0-2.48.2/./glib/gthread.c:780
        thread = 0x5603780b90f0
#6  0x00007f8eab2b76ba in start_thread (arg=0x7f8e98429700) at pthread_create.c:333
        __res = <optimized out>
        pd = 0x7f8e98429700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140250416584448, 9182224135158164056, 0, 140728467419823, 140250416585152, 0, -9191599764903368104, -9191699069017986472}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#7  0x00007f8eaafed41d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 1 (Thread 0x7f8eacf18ac0 (LWP 1688)):
#0  0x00007f8e81700333 in  ()
#1  0x000056037a1f75a0 in  ()
#2  0x000056037a2335e0 in  ()
#3  0x3f8000003f800000 in  ()
#4  0x3f8000003f800000 in  ()
#5  0x0000000000000000 in  ()
#0  0x00007f8e81700333 in  ()
#1  0x000056037a1f75a0 in  ()
#2  0x000056037a2335e0 in  ()
#3  0x3f8000003f800000 in  ()
#4  0x3f8000003f800000 in  ()
#5  0x0000000000000000 in  ()

**Comment by leigh123linux** [comment]
Basic info not provided.
