### ISSUE TITLE
Moving files from trash to desktop restores them

### ISSUE THREAD

**Issue by ManuelSchneid3r** [linuxmint/Cinnamon#7409]
Archlinux so everything on latest version

**Issue**
File is not moved to desktop

**Steps to reproduce**
Drag'n'drop file from trash to desktop

**Expected behaviour**
File is moved to desktop, but to whereever it has been before it was deleted. (standard restore procedure)

**Comment by leigh123linux** [comment]
file the issue against nemo and include the requested template info!!
