### ISSUE TITLE
Screenshot applet frequently scales incorrectly

### ISSUE THREAD

**Issue by CottonEaster** [linuxmint/Cinnamon#7410]
```
 * Cinnamon version (cinnamon --version): 3.6.7
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 18.3
 * Graphics hardware *and* driver used: not relevant, I think
 * 32 or 64 bit: 64
 ```

**Issue**

The (third-party) screenshot applet does not always scale properly. Screenshot (the tiny square - third icon from the right - is the camera icon for the screenshot applet - miniturarised!):

![image](https://user-images.githubusercontent.com/9998846/38049107-2e97e640-32bf-11e8-9719-edde33a78e27.png)

**Steps to reproduce**

The problem may be reproducable on Mint out of the box. If not, try enlarging the panel. If that still doesn't do it, go hiDPI.

**Expected behaviour**

The icon should scale properly, always.

**Other information**

The icon does occasonally - either immediately after adding to the panel, or after changing Cinnamon theme - scale correctly.

There's a bug report [on the applets site](https://cinnamon-spices.linuxmint.com/applets/view/35).

**Comment by NikoKrause** [comment]
The comments section on the applets site is for reviews/comments not for bug reports. (Nobody gets notifications there.)

There's an issue button on the applets site you linked. If you click this button, it will link you to the right place to report this issue to.

**Comment by CottonEaster** [comment]
Thanks. I've posted the report in the right place. However, I fear no-one will get a notification there either, or at least the author won't, because the author is listed as having no author assigned. Is there a more official screenshot applet, please?

**Comment by NikoKrause** [comment]
The spices applets are 3rd party applets.
It means that those applets are reviewed by the Linux Mint team, but they haven't been written by the Mint team but from 3rd party developers.
Some of those have no author though, because the author does no longer maintain it.

The official applets are those, which ship with Cinnamon itself and there's no Screenshot applet in it.
But I can recommend an unofficial Screenshot applet, which is my favorite and which I use on my own for over a year now:
https://github.com/rjanja/desktop-capture

**Comment by NikoKrause** [comment]
I checked desktop-capture, it suffers from the same fix, but I created a PR to fix it for desktop-capture. Should be merged in a few days.

**Comment by CottonEaster** [comment]
NikoKrause

I found the same line that you changed in `desktop-capture` within `ScreenShot` and I [replaced it with the correction you made to the former](https://github.com/rjanja/desktop-capture/pull/80) and it worked!

I would make a 'pull request' here, to, er, pull the fix into `ScreenShot`; but the 'pull' page has been baffled - I've never done a pull request before - and I do not know what to do.

I've taken the liberty
