### ISSUE TITLE
cinnamon-settings raises an error when loading Mouse and Touchpad

### ISSUE THREAD

**Issue by jonpoveda** [linuxmint/Cinnamon#7411]
```
 * Cinnamon version 3.4.6
 * Distribution - Arch (Antergos)
 * Graphics hardware Intel Corporation Device 591b and driver used VGA compatible controller
 * 64 bit
 ```

**Issue**
cinnamon-settings raises an error when loading 'Mouse and Touchpad' settings with 
the message: < KeyError: "unknown key: 'two-finger-click'" >

**Steps to reproduce**
Open a terminal and run `cinnamon-settings mouse`
OR
Open cinammon-settings and click on `Mouse and Touchpad`

**Expected behaviour**
Open mouse and touchpad configuration GUI

**Other information**
The requested key is not found on dconf.

[Full log](https://github.com/linuxmint/Cinnamon/files/1857391/issue.log)

**Comment by itzexor** [comment]
You are using mixed cinnamon versions. This is not supported. You need to be using cinnamon-settings-daemon 3.4.x with cinnamon 3.4.x, or upgrade to 3.6.x
