### ISSUE TITLE
Cinnamon Menu: Search keyboard navigation not working with search provider results

### ISSUE THREAD

**Issue by gkatev** [linuxmint/Cinnamon#7412]
```
 * Cinnamon version 3.6.7
 ```

When using the search function of the menu, you can use the arrow keys to navigate through the results. If all the results returned originate from search providers, the arrow keys do nothing. However, in the latter case, if you hover over one of the results with the mouse and the press an arrow key, the navigation works.

**Comment by smurphos** [comment]
Some added info:

In the scenario described above none of the search-provider results get selected hence can't be scrolled through by keyboard.

If you do the same in the [Stark menu](https://github.com/linuxmint/cinnamon-spices-applets/tree/master/CinnVIIStarkMenu%40NikoKrause)  which reports the number of results it doesn't include search-provider results in the count of results.
