### ISSUE TITLE
Missing localisation

### ISSUE THREAD

**Issue by Alan01** [linuxmint/cinnamon#7422]
```
 * Cinnamon version (cinnamon --version) 3.67
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 18.3
 * Graphics hardware *and* driver used Not relevant
 * 64 bit
 ```

**Issue**
When running Users and Groups, the phrase "Authentication is required to run the Users and Groups" is in English. This is due to the string not being localized in org.cinnamon.settings-users.policy. This actually goes for all org.cinnamon.settings... files in /usr/share/polkit-1/actions

**Steps to reproduce**

**Expected behaviour**

**Other information**

**Comment by icarter09** [comment]
@Alan01 are you still experiencing this issue?

**Comment by Alan01** [comment]
No, it's fixed.
