### ISSUE TITLE
Cinnamon-settings on Ubuntu 18.04 Bionic - Python error 'sys' 'module' object has no attribute 'setdefaultencoding'

### ISSUE THREAD

**Issue by Gargravarr2112** [linuxmint/Cinnamon#7423]
```
 * Cinnamon version (cinnamon --version): 3.6.7
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...): Ubuntu 18.04 alpha
 * Graphics hardware *and* driver used: Intel Ivy Bridge Integrated (HD Graphics 4000), stock driver from kernel 4.15.0-13
 * 32 or 64 bit: amd64
 ```
**Issue**

Fresh-installed Ubuntu 18.04 alpha to test on a spare computer. Installed Cinnamon from the Bionic repos. Looks like the stock Python2 with this release (2.7.14+) has removed the 'setdefaultencoding' function. Clicking the Settings icon in the menu does nothing, nor does invoking anything that opens the unified settings. Running `cinnamon-settings` from the command line gives:

`gargravarr@Eos:~$ cinnamon-settings
Traceback (most recent call last):
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 6, in <module>
    sys.setdefaultencoding('utf-8')  # noqa
AttributeError: 'module' object has no attribute 'setdefaultencoding'`

Commenting out the offending line in the above file results in the window loading and settings can be changed.

**Steps to reproduce**

1. install Ubuntu 18.04 from a daily ISO
2. fully update
3. install cinnamon and cinnamon-desktop-environment via APT
4. start a Cinnamon session from GDM
5. try anything that loads the Settings window

**Expected behaviour**

Settings window appears

**Other information**

Python versions: v2.7.14+ and 3.6.5rc1
Googling the function suggests its use has been deprecated for a while and should be avoided.

**Comment by mtwebster** [comment]
Cinnamon settings have been ported to python3 for the upcoming 3.8 release, and that stuff has been removed.  It saved us for a long time from needing a lot of ugly .encode/.decode garbage sprinkled everywhere.  You might try the nightly cinnamon ppa instead, for now.
