### ISSUE TITLE
copied contents from menu editor lost after closing window

### ISSUE THREAD

**Issue by illumilore** [linuxmint/cinnamon#7425]
```
 * Cinnamon version (cinnamon --version) Cinnamon 3.6.7

 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) mint 18.2
 * Graphics hardware *and* driver used
 * 32 or 64 bit
 ```

**Issue**

right click on menu > configure> open menu editor> select random launcher> properties> click on icon so browser window comes up> select the icon file> right click> copy location.
Now location is stored in clipboard.
Close out window, then hit cancel on launcher properties
Now location is wiped from clipboard.

**Steps to reproduce**

**Expected behaviour**

Contents from clipboard should not be wiped

**Other information**

**Comment by icarter09** [comment]
We believe this issue is fixed. Please test against the latest Cinnamon version (4.2). 

If the issue happens again, create a new issue and add the output of "cinnamon-settings sound".
