### ISSUE TITLE
enable remote desktop

### ISSUE THREAD

**Issue by brianjmurrell** [linuxmint/Cinnamon#7428]
```
 * Cinnamon version (cinnamon --version)
5.6.7
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
Fedora 27
 * Graphics hardware *and* driver used
 * 32 or 64 bit
N/A
 ```

**Issue**
There is no way to enable desktop sharing/remote desktop/VNC server/vino/etc.

**Steps to reproduce**
Open the Cinnamon menu
Search for "remote" and then "sharing"

**Expected behaviour**
Should see a systems settings/control application to enable desktop sharing such as GNOME has

**Other information**

**Comment by leigh123linux** [comment]
I used to port the sharing to cinnamon-control-center for fedora, @clefebvre rejected the idea so I dropped it.

**Comment by leigh123linux** [comment]
https://github.com/linuxmint/cinnamon-settings-daemon/pull/129

**Comment by brianjmurrell** [comment]
So why are we closing this ticket?

**Comment by leigh123linux** [comment]
@brianjmurrell because we don't  support gnome crapware.

see Clem's response to my pr https://github.com/linuxmint/cinnamon-settings-daemon/pull/129

**Comment by brianjmurrell** [comment]
At least you aren't biased.

But what does "gnome crapware" have to do with this ticket?  This ticket is about the lack of remote desktop functionality in Cinnamon.  Nowhere did it suggest that it should be resolved using "gnome crapware".  If leveraging "gnome crapware" is not a viable solution then another solution is needed.

But regardless, this ticket should stay opened until a solution is crafted, one way or another.  IMHO.

**Comment by mainmachine** [comment]
> such as GNOME has

*You* suggested that the solution should be similar to what Gnome does.

This is a feature request.

**Comment by brianjmurrell** [comment]
> You suggested that the solution should be similar to what Gnome does.

I suggested the *functionality* be similar; provided as an example of how it could/should work.  That in no way suggests that it needs to use "gnome crapware" to provide the functionality.

So yes, probably a feature request.

**Comment by leigh123linux** [comment]
Remote desktop code has no place within cinnamon code!!

**Comment by brianjmurrell** [comment]
Providing a remote desktop (i.e. VNC) "server" and a switch to enable it does, IMHO.

People using a Cinnamon desktop should have a setting in the Cinnamon settings manager to enable desktop sharing.  IMHO.

**Comment by leigh123linux** [comment]
@brianjmurrell  I don't see any benefit adding a link to some 'remote desktop program' to cinnamon-settings.
Any proper 'remote desktop program' should provide a menu entry, isn't that enough!
