### ISSUE TITLE
add coverflow option to Cinnamon hotcorners

### ISSUE THREAD

**Issue by freemangilgamesh** [linuxmint/cinnamon#7433]
I suggest you add a coverflow option to Cinnamon hotcorners just like the alt-tab shortcut

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
