### ISSUE TITLE
Calendar applet: forward and back buttons always bring up the same window

### ISSUE THREAD

**Issue by CottonEaster** [linuxmint/Cinnamon#7439]
```
 * Cinnamon version (cinnamon --version): 3.6.7
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...): 18.3
 * Graphics hardware *and* driver used
 * 32 or 64 bit: 64
 ```

**Issue**

Please see my title and also the next section.

**Steps to reproduce**

- Open the calendar applet by right-clicking it (on the panel) and selecting 'configure'.
- In the resulting window, click either the back or forward icons, as many times as you like.
- Result: a sliding animation to . . the same window.

**Expected behaviour**

If there is no other window to be disclosed via the arrow buttons, they should be absent or greyed out or (worst) give some sort of error signal when clicked.

**Other information**

**Comment by NikoKrause** [comment]
Screenshot?

**Comment by CottonEaster** [comment]
Video [here](https://app.box.com/s/22dbm4cuz6cf1xo5mek0xpwcawq7bm2h).

**Comment by smurphos** [comment]
I only get that if I've got multiple Calendars active. The button tooltip does say 'Next Instance' and 'Previous Instance' - it allows you to have different settings for different instances of the Calendar.

With only one Calendar active I see no forward or back button.

`gsettings get org.cinnamon enabled-applets | grep calendar` to check if you've got another instance lurking on a hidden panel.

**Comment by JosephMcc** [comment]
I see the same as @smurphos on git master.

**Comment by CottonEaster** [comment]
Those tooltips seem a bit missable (or at least I managed to miss them).

`gsettings get org.cinnamon enabled-applets | grep calendar` yields:

['panel2:left:0:menu@cinnamon.org:14', 'panel2:left:6:panel-launchers@cinnamon.org:16', 'panel2:left:5:removable-drives@cinnamon.org:19', 'panel2:left:2:user@cinnamon.org:20', 'panel2:right:12:calendar@cinnamon.org:21', 'panel2:left:9:expo@cinnamon.org:22', 'panel2:right:4:recent@cinnamon.org:23', 'panel2:left:7:show-desktop@cinnamon.org:24', 'panel2:right:8:inhibit@cinnamon.org:26', 'panel2:right:6:systray@cinnamon.org:28', 'panel2:right:5:sound@cinnamon.org:29', 'panel2:left:4:panel-launchers@cinnamon.org:30', 'panel2:right:3:notifications@cinnamon.org:31', 'panel2:right:7:xrandr@cinnamon.org:32', 'panel2:left:1:spacer@cinnamon.org:33', 'panel2:left:3:spacer@cinnamon.org:34', 'panel2:right:2:network@cinnamon.org:36', 'panel2:right:11:spacer@cinnamon.org:37', 'panel2:right:10:power@cinnamon.org:38', 'panel2:left:8:ScreenShot@tech71:40']
