### ISSUE TITLE
Drag and drop threshold setting (in System Settings): meaning unclear; items bounce out of bin

### ISSUE THREAD

**Issue by CottonEaster** [linuxmint/Cinnamon#7440]
```
 * Cinnamon version (cinnamon --version): 3.6.7.
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
 * Graphics hardware *and* driver used
 * 32 or 64 bit: 64
 ```

**Issue**

Howsoever I set the drag and drop threshold setting (in System Settings), dragging an item atop another - for instance, onto the rubbish bin, often does not work. Indeed, I do not understand what I am setting with that setting.

**Steps to reproduce**

Please see [video here](https://app.box.com/s/otv567sw7vn2wbj3kp1h6enve3ngg1gl). (It would be good were these videos directly embeddable in Github; as it is, I must use Box.)

**Expected behaviour**

Not the sort of 'bouncing' one sees in the video.
Also, the 'drag and drop threshold' setting should have some sort of explanation.

**Other information**

**Comment by leigh123linux** [comment]
You are clearly missing the target for the drop.

'drag and drop threshold' = pixel distance for cursor to activate drop (not file icon distance).

**Comment by CottonEaster** [comment]
> You are clearly missing the target for the drop, the cursor tip needs to hit the target.

Thanks, but I will not be the only person not to know that.

> 'drag and drop threshold' = pixel distance to activate drag.

Thanks, but that still is not very clear. Perhaps you mean the following: how many pixels the pointer must move before a clicked item is dragged. So - yes? - setting a high value will make accidental drags less frequent, whereas a low value will make drags begin sooner. So - further - the value has nothing to do with whether I can hit that darn rubbish bin.
