### ISSUE TITLE
Adjust recording time length for screen recorder

### ISSUE THREAD

**Issue by SteveEbey73742** [linuxmint/cinnamon#7441]
```
 * Cinnamon version 3.6.7
 * Distribution - Fedora 27
  * Nvidia GeForce GTX 970 4Gig Vram Proprietary 390.48
 * 64 bit
 ```

Unable to change length of recording made with screen recorder

**Steps to reproduce** Start recording, stops after 30 seconds.

**Expected behaviour**Need to change the length of the recording to allow unlimited

**Comment by icarter09** [comment]
@SteveEbey73742 what screen recorder are you using?

**Comment by smurphos** [comment]
If's it's Cinnamon's inbuilt recorder there is no 30 second limit in 4.2.4. There may well be limits if the default save location as limited free space.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
