### ISSUE TITLE
Focusing wrong window after closing another window

### ISSUE THREAD

**Issue by okmanek** [linuxmint/cinnamon#7445]
```
Cinnamon 3.4.6
Mint 18.2
Radeon HD 7750/8740 / R7 250E
64 bit
 ```

Focus doesn't work as intended.

2 monitors. Google chrome on 1 of them (set as primary). Other window opened on secondary monitor. I open next Google Chrome window by pressing ctrl + n. Then I close it. I expect focus to remain on father window which is another chrome -  but focus goes to terminal.

Focus should remembers which window spawned next window and return to that window.

**Comment by icarter09** [comment]
@okmanek are you still experiencing this issue?

**Comment by okmanek** [comment]
@icarter09 I can't really tell, I do not use Linux Mint any more

**Comment by icarter09** [comment]
@okmanek no worries and thanks for the update.
