### ISSUE TITLE
Cinnamon crash after install kernel 4.15

### ISSUE THREAD

**Issue by Gandalf888** [linuxmint/Cinnamon#7446]
Cinnamon version (cinnamon --version)
**Cinnamon 3.6.7**
Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
**No LSB modules are available.
Distributor ID:	LinuxMint
Description:	Linux Mint 18.3 Sylvia
Release:	18.3**
**Codename:	sylvia**
Graphics hardware *and* driver used
**Nvidia GeForce G210M**
32 or 64 bit
**64 bit**

**Issue**

After installation kernel 4.15.0-13, artifacts appear after running the UI, the graphical environment does not work stably. Wallpaper is not displayed, only black and white squares, window bars disappear, there is even a problem with rendering subtitles in windows dialogs.

**Steps to reproduce**

Install kernel 4.15.0-13 and reboot the computer.

**Expected behaviour**

Once installed, the Cinnamon kernel should display the wallpaper correctly and windows should be properly rendered.

**Other information**
I use open source drivers for graphic, I have not checked on proprietary drivers because I'm afraid that the system will not start. After restoring the kernel to version 4.13.0.-38, the environment starts correctly.

**Comment by leigh123linux** [comment]
kernel issues don't belong here.
