### ISSUE TITLE
Lock screen switches Keyboard layout

### ISSUE THREAD

**Issue by mxa** [linuxmint/Cinnamon#7453]
```
 * Cinnamon version 3.6.7
 * Distribution - Mint 18.3
 * 64 bit
 ```

I have two keyboard layouts. When switching it to layout B and the lock screen takes effect, the password has to be typed as if layout A would be active. It's not possible in the lock screen to change the keyboard layout.

There are a few very similar issues, but they are marked as resolved, so I am opening a new one.
https://github.com/linuxmint/Cinnamon/issues/3048

**Comment by mtwebster** [comment]
You should have an indicator on the left end of the password entry box, you can click that to change layouts.  It defaults to showing a flag icon related to the active layout region.

**Comment by mxa** [comment]
@mtwebster you're absolutely right, there is a flag and I can change the layout there. Must have been blind before, sorry for that.

**Comment by NikoKrause** [comment]
![screenshot-area-2018-04-10-152729](https://user-images.githubusercontent.com/8415124/38559598-bfe258ce-3cd3-11e8-9142-76f5997a98af.png)

**Comment by mxa** [comment]
What's the bash command to start the screensaver?

**Comment by mxa** [comment]
OK, so after further testing it's just a minor annoyance, not a big problem: The input method is always set to A, even when B was active before the lockscreen was started. It can be changed though as @mtwebster said, thus I'll just close this. Sorry for the noise and have a great day.

**Comment by mtwebster** [comment]
It’s actually intended to remember your lock screen layout regardless of the layout that was active prior to locking. Meaning, once you set it once in the lockscreen it should always use that layout there.  Upon unlocking, it should then restore the pre-lock layout that was active. 

Let me know if that isn’t the behavior you see.

**Comment by mxa** [comment]
Ah, OK, yes that's the behaviour. It's that complicated because I use two keyboards simultaneously

![photo_2018-04-10_17-33-39](https://user-images.githubusercontent.com/1220707/38566989-54048548-3ce5-11e8-82b6-363db2670ef2.jpg)

Ideally each keyboard would keep its layout and the OS would just remember which keyboard has which layout... I could just use the different keyboard If I type Korean or German :)
