### ISSUE TITLE
Calendar applet settings reset for external monitor

### ISSUE THREAD

**Issue by julienfalque** [linuxmint/Cinnamon#7454]
```
 * Cinnamon 2.8.6
 * Ubuntu 16.04 xenial (x86-64)
 ```

**Issue**

Settings for calendar applet on an external monitor are reset when the external monitor is disconnected in some conditions.

**Steps to reproduce**

* Have a panel on an external monitor;
* Add a calendar applet to it;
* Change the settings of the applet to whatever you want;
* Suspend or hibernate your system;
* Disconnect the external monitor;
* Resume your system;
* Reconnect the external monitor;
* At this point, settings of the calendar applet should have been reset to defaults.

**Expected behaviour**

The settings of the calendar applet should remain the same and not be reset to defaults.

**Comment by leigh123linux** [comment]
Cinnamon 2.8.6 is EOL, feel free to reopen if you can reproduce on 3.6.x

**Comment by julienfalque** [comment]
Ah sorry, didn't know that. Thanks for your quick answer.
