### ISSUE TITLE
Desktop wallpaper zoomed in after switching inputs on the screen

### ISSUE THREAD

**Issue by ErikEklund** [linuxmint/cinnamon#7458]
```
Mint 18.3
Cinnamon 3.6.7
Monitor: LG 34UM95
Graphics:  Card: Advanced Micro Devices [AMD/ATI] Hawaii XT [Radeon R9 290X]
           bus-ID: 01:00.0
           Display Server: X.Org 1.19.5 driver: N/A
           Resolution: 3440x1440@59.97hz
           GLX Renderer: AMD HAWAII (DRM 2.50.0 / 4.16.2-041602-generic, LLVM 5.0.0)
           GLX Version: 3.0 Mesa 17.2.8 Direct Rendering: Yes
```

**Issue**
After changing inputs on the screen Cinnamon is connected to and then changing back, the wallpaper is zoomed in.

The wallpaper fills the screen, with the middle part of the wallpaper filling the screen (approximately zoomed in 200%). Very pixelated. Also, every time this has happened, I get a black flickering triangle on the desktop that stays until reboot. I'm assuming the wallpaper is drawn outside of allocated memory.

**Steps to reproduce**
Set a desktop wallpaper. Change monitor input (in my case from Displayport to Thunderbolt. Target type or resolution does not seem to matter). Switch back to the input displaying Cinnamon. Observe desktop wallpaper being zoomed in.

**Expected behaviour**
Desktop wallpaper should stay the same, no flickering artifacts on screen.

**Other information**
Reproducible 100% of the time. Zoom persists through reboot. Selecting a different wallpaper and then the original one again corrects the issue.

**Comment by ErikEklund** [comment]
Update: I installed "amdgpu-pro" driver instead of "radeon", and the issue went away. It's probably because the new driver does not report weird resolutions to cinnamon while switching inputs anymore. Still, Cinnamon should probably handle the wallpaper scaling even if odd resolutions are used briefly.

**Comment by icarter09** [comment]
@ErikEklund do you feel this issue can be closed?
