### ISSUE TITLE
Screensaver / Screen lock gets activated while using external HID controller

### ISSUE THREAD

**Issue by KAMI911** [linuxmint/Cinnamon#7460]
* Cinnamon 3.6.7
* Mint 18.3
* 64 bit

External HID, a gamepad:
Bus 003 Device 106: ID 0810:e501 Personal Communication Systems, Inc. 

**Issue**
When I play with USB attached gamepad the screensaver/ lock gets activated after the defined period of time.

**Steps to reproduce**
* Set timpot of screensaver to 1 minute
* Play game with external gamepad
* Computer get locked after one minute

**Expected behaviour**
Do not lock the computer while using (playing) an external device.

**Comment by leigh123linux** [comment]
Please report it against cinnamon-settings-daemon

**Comment by KAMI911** [comment]
Issue is here: https://github.com/linuxmint/cinnamon-settings-daemon/issues/226
