### ISSUE TITLE
"Win" button issues in "Alt + F2" dialog

### ISSUE THREAD

**Issue by vladimir-didenko** [linuxmint/cinnamon#7461]
```
 * Cinnamon version 3.6.7
 * Distribution - Alt Linux Sisyphus (development branch)
 * 64 bit
 ```

**Issue**
I have switched from "Alt + Shift" to "Win + Space" shortcut for keyboard layout changing and faced with 2 issues in run (Alt + F2) dialog
* When you start run dialog and then press "win" button it immediately shows menu dialog. This behavior differs from normal mode when only button releasing shows menu dialog. So if I want to switch keyboard layout in Alt + F2 dialog I forced to press Esc button after "Win + space" shortcut.
* If you forgot to press space button in "Win + space" shortcut in run ("Alt + F2") dialog it triggers weird mode when it is not possible to close Alt + F2 dialog.

**Steps to reproduce**
Issue 1:
* Press "Alt + F2"
* Press "Win" button but don't release key
* Menu dialog will be shown immediately

Issue 2:
* Press "Alt + F2"
* Press "Win" button and release key
* Enter program name in opened menu
* Try to close Alt + F2 dialog - it is not possible

**Expected behaviour**
I expect that in Alt + F2 dialog "Win" button will never trigger Menu dialog.

**Comment by icarter09** [comment]
Cinnamon 3.6.7
Linux Mint 18.3 64 bit

Confirmed that both issues do occur when performing the steps to reproduce. One fix for Issue #2 is to click on Alt + F2 dialog box, which brings it into focus, then press "Esc". That will close out the dialog box.
