### ISSUE TITLE
[Feature Request] Native Custom Tiling [eg: 3 way split] 

### ISSUE THREAD

**Issue by jramapuram** [linuxmint/cinnamon#7467]
```
 * Cinnamon version (cinnamon --version) : 3.6.6
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) : Arch
 * Graphics hardware *and* driver used : nvidia-390.42
 * 32 or 64 bit : 64 bit
 ```

**Request** : allow for custom tiling or snap zones natively without resorting to things like wmctrl. On ultrawide monitors it's relatively easy to have 3 horizontally tiled windows. Supporting something like this would be immensely helpful.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
