### ISSUE TITLE
'accout details' entry in panel-applet user invisible

### ISSUE THREAD

**Issue by oberon2007** [linuxmint/Cinnamon#7469]
On Manjaro we experience a strange issue since our latest package update. Although no directly Cinnamon related packages were included in the update, but I was hoping that someone here could point me in a useful direction.
What happened is that the top entry in the user@cinnamon applet 'account details' is still functional but not displaying:

![screenshot_2018-04-15_21-15-28](https://user-images.githubusercontent.com/11800714/38782336-36a56e70-40f2-11e8-9e0d-5a83afc43f2f.png)

Any help would be greatly appreciated.

**Comment by JosephMcc** [comment]
We have an issue template so we can get valid info. Please use it.

**Comment by NikoKrause** [comment]
Please provide the informations asked in the template.
https://github.com/linuxmint/Cinnamon/blob/master/.github/ISSUE_TEMPLATE.md

And infos from `~/.cinnamon/glass.log` and output after you run
```
cinnamon --replace
```
in your terminal.

**Comment by oberon2007** [comment]
Wow! Did you have a bad day, @JosephMcc ?
Sure I can open a new issue, but the only additional information you will be able to see is Cinnamon version, which is the latest stable release.
Thank you, @NikoKrause for your more helpful answer. We may be able to find something there...

**Comment by oberon2007** [comment]
https://github.com/linuxmint/Cinnamon/issues/7471
