### ISSUE TITLE
Cinnamon had a serious internal error

### ISSUE THREAD

**Issue by NSnietol** [linuxmint/cinnamon#7470]
```
 * Cinnamon version (cinnamon --version) lightdm-xsession
 * Distribution - (Debian 9.4)
 * Graphics hardware *and* driver used
 *  64 bit
 ```

**Issue**
when I'm performing normal activities on my computer at any moment, that message appears.

**Steps to reproduce**

i can't , it just shows up
**Expected behaviour**

**Other information**
Debian 9.4 , message 
https://drive.google.com/file/d/1FdKC-1M0vDV9JZzSsPHYjN-RXMEtwr26/view?usp=sharing

**Comment by JosephMcc** [comment]
Check your ~/.xsession-errors. Normally when Cinnamon crashes it will give you a clue as to why. There isn't much we can do here if we don't get more info.

**Comment by Amosar** [comment]
I have the same issue on my computer sometimes cinnamon just crash without any reason:

## Computer info
linux mint 18.3 
cinnamon 3.6.7
Kernel x86_64 Linux 4.13.0-39-generic
[https://pastebin.com/Ymzg6X16](https://imgur.com/zbkw0ye)

## xsession-errors log
[https://pastebin.com/Ymzg6X16](https://pastebin.com/Ymzg6X16)

**Comment by icarter09** [comment]
@NSnietol or @Amosar are either of you still experiencing this issue?

**Comment by NSnietol** [comment]
Hi, currently I'm not using cinnamon.

**Comment by icarter09** [comment]
@NSnietol thanks for the update

**Comment by Amosar** [comment]
I'm no longer using cinnamon too :/

**Comment by icarter09** [comment]
@Amosar no worries and thanks for the update.
