### ISSUE TITLE
Too many opened apps causing overlapping on System Panel

### ISSUE THREAD

**Issue by KAMI911** [linuxmint/Cinnamon#7474]
* Cinnamon 3.6.7
 * Linux Mint 18.3
 * Vendor: Intel Open Source Technology Center (0x8086)
    Device: Mesa DRI Intel(R) Haswell Mobile  (0x416)
    Version: 17.2.8
    Accelerated: yes
    Video memory: 1536MB
    Unified memory: yes
    Preferred profile: core (0x1)
    Max core profile version: 4.5
    Max compat profile version: 3.0
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.1
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) Haswell Mobile 
OpenGL core profile version string: 4.5 (Core Profile) Mesa 17.2.8
OpenGL core profile shading language version string: 4.50
 * 64 bit

**Issue**
Opening too much applications causes overlapping on System Panel part of Panel:
![panel_mess](https://user-images.githubusercontent.com/5292264/38851117-b9254604-4214-11e8-8cf6-119347ac5968.png)

**Steps to reproduce**
Just open a few new windows. When you see only the icons of windows, instead of scrolling applications on panel (like tabs in the browser) the one gets overlapping icons on the right of the panel.

**Expected behaviour**
* Scrolling applications on panel (like tabs in the browser) or
* Grouping apps by type on Panel

**Comment by JosephMcc** [comment]
https://github.com/linuxmint/Cinnamon/issues/5042
A search will turn up both issues for both the problem and requests for fixes.
