### ISSUE TITLE
Grouping apps by type on Panel

### ISSUE THREAD

**Issue by KAMI911** [linuxmint/Cinnamon#7475]
* Cinnamon 3.6.7
 * Linux Mint 18.3
 * Vendor: Intel Open Source Technology Center (0x8086)
    Device: Mesa DRI Intel(R) Haswell Mobile  (0x416)
    Version: 17.2.8
    Accelerated: yes
    Video memory: 1536MB
    Unified memory: yes
    Preferred profile: core (0x1)
    Max core profile version: 4.5
    Max compat profile version: 3.0
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.1
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) Haswell Mobile 
OpenGL core profile version string: 4.5 (Core Profile) Mesa 17.2.8
OpenGL core profile shading language version string: 4.50
 * 64 bit

**Issue**
This a feature request to make settings for Grouping apps by type on Panel with these settings:
* None
* Automatic
* Enabled

**Expected behaviour**
* Grouping apps by type on Panel helps users to have more space on panel.

**Comment by JosephMcc** [comment]
Thanks for the request. Up to this point we've not planned on adding any sort of app grouping to the stock window list. This is a feature that has been requested and we are aware of it. In the mean time there are a couple of excellent window list applets available from cinnamon spices that add more capabilities.
