### ISSUE TITLE
Show-desktop applet broken?

### ISSUE THREAD

**Issue by JohnML1** [linuxmint/Cinnamon#7479]
john1@cinna
OS: Mint 18.3 sylvia
Kernel: x86_64 Linux 4.15.0-13-generic
Uptime: 27m
Packages: 2646
Shell: bash 4.3.48
Resolution: 1920x1080
DE: Cinnamon 3.6.7
WM: Muffin
WM Theme: Linux Mint (Mint-X)
GTK Theme: Mint-X-Aqua [GTK2/3]
Icon Theme: Mint-X-Teal
Font: Noto Sans 9
CPU: Pentium Dual-Core CPU E5200 @ 2.5GHz
GPU: Mesa DRI Intel(R) G33 
RAM: 947MiB / 3935MiB

 ```

**Issue**
see 
https://forums.linuxmint.com/viewtopic.php?f=208&t=266699&p=1459426#p1459426


**Steps to reproduce**
install applet, reboot


**Expected behaviour**



**Other information**

**Comment by JosephMcc** [comment]
It seems to be fine on git master.

**Comment by NikoKrause** [comment]
I guess you are running the Cinnamon nightly ppa?!

You need to update cjs: https://github.com/linuxmint/cjs
https://github.com/linuxmint/cinnamon-spices-applets/pull/1770#issuecomment-381439105

**Comment by JosephMcc** [comment]
Actually I would suggest not running the nightly ppa in Mint 18. We no longer worry about supporting the older version of Gtk in Mint 18 for new stuff. Things are very likely to break if you are running it.

**Comment by JohnML1** [comment]
never activated nightly builds but:

![bildschirmfoto vom 2018-04-18 12-18-59](https://user-images.githubusercontent.com/4930934/38926603-918f1b2a-4303-11e8-8d19-5265b404e745.png)
![bildschirmfoto vom 2018-04-18 12-20-45](https://user-images.githubusercontent.com/4930934/38926604-91ad9b4a-4303-11e8-8fe6-3675d4d8e0f2.png)

whats wrong with these ppa's?

**Comment by claudiux** [comment]
Hello @JohnML1,
You are using nightly builds (PPA of @glebihan). So, you need to install the last version of cjs.
`git clone https://github.com/linuxmint/cjs.git`
`cd cjs`
`./configure && make && sudo make install`
Then reboot the computer.

**Comment by NikoKrause** [comment]
You are using `cinnamon-nightly` as visible in your screenshot.

And as it's told in the ppa:
>This PPA contains nightly builds for the Cinnamon desktop environment.
>/!\ WARNING : Nightly builds are unstable, use only for debugging purposes /!\

**Comment by JohnML1** [comment]
thanks claudiux ... but no more adventures today.

Downgraded all nightly builds, cinnamon is ok again, i'm happy with that :-)

**Comment by JohnML1** [comment]
Hi NikoKrause

any idea where i get these nightly-builds ppa from?

copyq was the only one i remember?!

Shit happens !!

**Comment by claudiux** [comment]
Sure @JohnML1, it's more careful. I use it only in a virtual box to test my code and to see the evolution of Cinnamon.
