### ISSUE TITLE
Cannot mount or charge Android phone

### ISSUE THREAD

**Issue by CottonEaster** [linuxmint/Cinnamon#7481]
```
 * Cinnamon version (cinnamon --version): 3.6.7
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) 18.3
 * Graphics hardware *and* driver used
 * 32 or 64 bit: 64
 ```

**Issue**

My Lenovo ThinkPad Carbon X1 6th Generation cannot mount or charge my Android phone. Upon USB connection, (1) the phone does not report as charging - but still as discharging - and I see this on Mint:

![image](https://user-images.githubusercontent.com/9998846/38948166-a6d25c58-4336-11e8-9b79-eecafde41d20.png)

**Steps to reproduce**

Connect phone with USB. It makes no difference whether the phone has USB debugging enabled or whether I have installed `mtp-tools` `mtpfs` or `adb`. The Mint computer is on AC power.

**Expected behaviour**

Charging and, ideally (/with the right software installed) mounting.

**Other information**

- The laptop's BIOS is set to disable charging when the laptop is on battery - but it is on mains power.
- The phone charges and mounts on my Windows PC.

Apologies if I miss something.

EDIT: Also, I ended up with this, i.e. multiple instances of the same error window, which surely should not happen:

![image](https://user-images.githubusercontent.com/9998846/38948548-d8bd76f2-4337-11e8-90ea-7ebb014a47bc.png)

and some of those windows, individually, were hard to get rid off - even when I'd unplugged the phone. Also, I had more error windows that the screenshot shows; I thought to take the shot only after I had closed a few of them. EDIT: oh dear . . [please see this video](https://app.box.com/s/7iyjks5su8u9cd1rerikishea2ss0rnq).

**Comment by leigh123linux** [comment]
Cinnamon doesn't handle this.

**Comment by CottonEaster** [comment]
Thanks Leigh. What _does_ handle it, please?

**Comment by germanfr** [comment]
@CottonEaster check if Banshee is open. I had that phone and it was fully compatible, but there was a conflict with a Banshee mtp plugin or something similar.

**Comment by CottonEaster** [comment]
Thanks. So, should I report the problem [here](https://sourceforge.net/projects/libmtp/)? I note though that _the same OS (Mint 18.3 Cinnamon) handled the same phone on two other laptops_ (a Dell and an Acer).

**Comment by CottonEaster** [comment]
germanfr: thanks, but I do not use Banshee.

The phone, by the way, is the good ole Moto G First Generation.

I'll try booting a liveUSB of Mint and plugging the phone into that.

**Comment by CottonEaster** [comment]
On a Mint LiveUSB, the phone both mounts and charges.

**Comment by CottonEaster** [comment]
And now that I try the phone again in my normal Mint . . it mounts and charges. So we seem to have an intermittent problem.

**Comment by CottonEaster** [comment]
_I think the problem may have been two few 'inotify/max_user_watches'_, which caused other problems on my system, and caused problems on a previous system. So: _is there a case for Mint increasing the default value_ (which seems to be 8192)?

I have, now, this, in `/etc/rc.local`: 

`echo 1048576 > /proc/sys/fs/inotify/max_user_watches || true`
