### ISSUE TITLE
When is cinnamon 3.8 scheduled for release?

### ISSUE THREAD

**Issue by eli-schwartz** [linuxmint/Cinnamon#7484]
I've been updating various bits and pieces of the cinnamon ecosystem in Arch, but cjs 3.8 (which I've been looking forward to, as it's the last thing still using js38 in our repos and I'd like to drop it) seems to, unsurprisingly, be incompatible with cinnamon 3.6.7.

It runs fine with cinnamon-git from master, but I'm hesitant to upload that...

**Comment by itzexor** [comment]
3.8 is going to happen pretty soon... But all of these pull request need to be taken care of first so it'll probably be a little while. Clem has already started releasing some of the other dependencies for 3.8 as of yesterday
