### ISSUE TITLE
Cinnamon crash loop by adding launcher in menu editor

### ISSUE THREAD

**Issue by chepec** [linuxmint/Cinnamon#7489]
```
 * Cinnamon version 3.2.7
 * Distribution - Debian 9.4
 * Graphics card Radeon HD 6950 with ATI display driver `xserver-xorg-video-ati` version 7.8.0-1+b1
 * 64 bit system
 ```

Adding a new item (launcher) to the Menu editor GUI (`menulibre` version 2.0.7-1.1) immediately causes Cinnamon to crash. I had installed a new program in `/opt/` and was adding a menu item manually (I had filled out the command and chosen an icon, that's all).

The crash dialog box says "Cinnamon just crashed. You are currently running in Fallback mode. Do you want to restart Cinnamon?". Clicking "Yes" only leads to the dialog reappearing, over and over.

There's no panel, no start menu, and all keyboard shortcuts are not working. I cannot open a GUI terminal, but was able to SSH into the machine without issue.

I killed cinnamon via the SSH terminal, but after logging back in using the local GUI the same dialog box immediately reappears (before any desktop elements load) and keeps respawning as before.
The real clincher is that a reboot did not change anything - Cinnamon immediately crashes with the same symptoms as above. 

I'm completely flummoxed. How can `menulibre` crash the entire desktop environment? And how can it persist even after a reboot? Anyway, those are academic questions. More pressing, does anyone have any ideas on how to resolve this?

NB. Have been running Cinnamon for about a year now, and been running `menulibre` since before that (changed DE from Gnome to Cinnamon). Have definitely added menu items to Cinnamon before using `menulibre` GUI, but the last time was probably several months ago. This suggests a recent change in either `menulibre` or Cinnamon being the culprit? Also, I've purged `menulibre` and rebooted, but no joy.

**Comment by mtwebster** [comment]
Try deleting or renaming `~/.config/menus/cinnamon-applications.menu` to hopefully restore your desktop.

**Comment by mtwebster** [comment]
If that's insufficient, you can remove/rename the .desktop files in `~/.local/share/applications` as well.

That's typically where new entries are put, at least by our menu editor.  I'm unfamiliar with menulibre, but it has to follow certain rules anyhow.

**Comment by chepec** [comment]
@mtwebster Well, that was worthwhile advice! Thank you! I renamed `~/.config/menus/cinnamon-applications.menu` and rebooted, and everything appears back to normal.

If I might be a little greedy - any suggestions on how to edit the Cinnamon menu from here on? Is `cinnamon-menu-editor` perhaps a better tool than `menulibre`?
