### ISSUE TITLE
Please add support for the 'desktop-entry

### ISSUE THREAD

**Issue by elboulangero** [linuxmint/cinnamon#7492]
```
 * Cinnamon Cinnamon 3.6.7
 * Distribution Linux Mint 18.3 Sylvia
 * 64 bit
 ```

**Issue**

Assuming you're an application using [GApplication](https://developer.gnome.org/gio/stable/GApplication.html), then you're likely to send your notifications with `g_application_send_notification`. And if you provide a desktop file, then `g_application_send_notification` will [automatically set](https://github.com/GNOME/glib/blob/5c8b80c1e41028dd20d9390ea837b1a3793c5327/gio/gfdonotificationbackend.c#L266) the [desktop-entry hint](https://developer.gnome.org/notification-spec/#hints) for you.

I think the idea behind that is that the notification daemon has more flexibility: it can parse the desktop file, gets to know a few things about the application, and then just do the right things. Like deciding to use the `Icon` field in the desktop file, and display the application icon with the notification.

At least that's how it works with GNOME, and when I send a notification, GNOME displays the icon of my application. However I noticed that Cinnamon ignores the `desktop-entry` hint, hence the notification shows a default icon.

Do you have any plan do add support for this `desktop-entry` hint ?

Cheers,

  Arnaud

**Comment by elboulangero** [comment]
Sorry I opened the issue by mistake, before I finished to write it. Maybe that's why you closed it?

I edited the description now.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
