### ISSUE TITLE
cinnamon-settings: a single 404 while refreshing themes list causes multiple thumbnails to fail (incorrectly)

### ISSUE THREAD

**Issue by rmunn** [linuxmint/Cinnamon#7499]
```
 * Cinnamon version: 3.6.7
 * Distribution: Antergos (Archlinux variant that installs Cinnamon in initial install)
 * Graphics hardware *and* driver used: irrelevant to this issue
 * 64 bit
 ```

**Issue**

There appears to be a thumbnail .png file missing from http://cinnamon-spices.linuxmint.com/, specifically http://cinnamon-spices.linuxmint.com/uploads/themes/thumbs/Void.png returns a 404. This is causing #4429 to occur again. The reason I'm opening a new issue, though, rather than reopening #4429 is because the 404 on http://cinnamon-spices.linuxmint.com/uploads/themes/thumbs/Void.png is causing *all ten threads* to abort their downloads, rather than just the one thread that was downloading that URL. This results in ten dialog boxes popping up like the following:

![screenshot from 2018-04-23 12-58-34](https://user-images.githubusercontent.com/90762/39109222-2077d8ea-46f6-11e8-9b7a-f9095f3c5624.png)

The ten URLs that `cinnamon-settings` reported as having failed with a 404 are:

* http://cinnamon-spices.linuxmint.com/uploads/themes/thumbs/Void.png
* http://cinnamon-spices.linuxmint.com/uploads/themes/thumbs/Mint-Y-Yltra-Dark.png
* http://cinnamon-spices.linuxmint.com/uploads/themes/thumbs/Mint-Y-Blue.png
* http://cinnamon-spices.linuxmint.com/uploads/themes/thumbs/BelaLugosi.png
* http://cinnamon-spices.linuxmint.com/uploads/themes/thumbs/Railway.png
* http://cinnamon-spices.linuxmint.com/uploads/themes/thumbs/iOS-X.png
* http://cinnamon-spices.linuxmint.com/uploads/themes/thumbs/Numix-Cinnamon-Transparent.png
* http://cinnamon-spices.linuxmint.com/uploads/themes/thumbs/ScaleUp.png
* http://cinnamon-spices.linuxmint.com/uploads/themes/thumbs/Mint-XP-Homestead.png
* http://cinnamon-spices.linuxmint.com/uploads/themes/thumbs/Cinnamox-Rosso-Cursa.png

Of those ten URLs, only http://cinnamon-spices.linuxmint.com/uploads/themes/thumbs/Void.png is actually a 404; the other nine all work.

**Steps to reproduce**

1. Start `cinnamon-settings`.
1. Refresh the list of available themes.
1. Notice ten "HTTP 404" error dialogs pop up.

**Expected behaviour**

Only a single HTTP 404 error dialog would pop up, because only one of those URLs is actually missing. (Ideally, *no* error dialogs would pop up because the Void.png file is actually available).

**Other information**

Also reproduced on Linux Mint 18, running Cinnamon 3.2.7.

I've done a little digging into the `cinnamon-settings` source code, and it looks like the problem is in [the `Spices.py` code](https://github.com/linuxmint/Cinnamon/blob/432234afa63431123f13edac7b72c4c84599d69b/files/usr/share/cinnamon/cinnamon-settings/bin/Spices.py`). The `Spice_Harvester` class uses a thread pool to download the thumbnails, with up to 10 threads running. But the `abort_download` variable isn't stored on a per-thread basis, it's stored in the `self` instance that all 10 threads share. So when one `_url_retrieve` thread gets an HTTP 404 and sets `self.abort_download = ABORT_ERROR`, that causes *all ten* threads to exit the `while self.abort_download == ABORT_NONE` loop and raise a `KeyboardInterrupt`. Result: ten threads exit after a single 404, when nine of them would have succeeded.

So the "thread aborted" logic needs to use thread-local storage to keep track of errors like HTTP 404s, rather than storing those errors in the `self` instance that's shared by all ten threads. That would allow *only the failing thread* to be aborted.

**Comment by collinss** [comment]
Ok, it seems to me that there are 2 different things going on here. Aborting all downloads is actually intentional. If we don't have all the thumbnails, it's going to cause issues down the road, so the cache will need to be downloaded again anyway. However, the extra dialogs popping up is not necessary. I'll see what I can do to remove those.
