### ISSUE TITLE
Inactive OK button when creating new launcher with few commands

### ISSUE THREAD

**Issue by ntfs1984** [linuxmint/cinnamon#7501]
```
 * Cinnamon version - 3.6.6
 * Distribution - Manjaro
 * Graphics hardware - Intel Corporation HD Graphics 5300 (rev 09)
 * 32 or 64 bit - 64 bit
 ```
**Issue**

When creating new launcher - OK button is not active when command not found. 
It's good idea, but sometimes users want to use list of commands, variables setting etc, and in this case, OK button is inactive, despite of command are running and working from terminal.

**Steps to reproduce**

On desktop or in menu, click right button, choose "Create new launcher here", and then put some custom command in "Command" field. For example: GTK_CSD=0 gnome-disks
You will see that button OK is still not active.

![screenshot from 2018-04-24 12-23-38](https://user-images.githubusercontent.com/12632755/39178415-5b3cd31c-47ba-11e8-909d-5f71cc8eb4d3.png)

**Comment by icarter09** [comment]
Linux Mint 19.2
Cinnamon 4.2.4

I was able to reproduce this issue with the command listed in the **Steps to Reproduce**. @ntfs1984  do you have any other examples that produce the same result?

**Comment by smurphos** [comment]
The workaround for this issue is to use the format `sh -c 'some unrecognised command format'` as the launcher command.
