### ISSUE TITLE
Volume sound effect is hurting my ears

### ISSUE THREAD

**Issue by ssspacez** [linuxmint/Cinnamon#7502]
Cinnamon 3.6.7

When you **hover** the mouse cursor over the **sound icon and scroll**, the default sound effect **volume.oga** is played. The problem is if it's near 100% and you have your **headphones on** it can be quite annoying when you change it(test it and you will understand).

On Sound effects(configurations) screen there is a **more neutral** sound that could be used: **logout.ogg**.

How about changing to this one? It's much easier in the ears, or **another sound effect** that doesn't hurt the ears.

Thread: https://forums.linuxmint.com/viewtopic.php?f=29&t=268258

**Comment by leigh123linux** [comment]
You have a separate volume control  for sounds to control this.

**Comment by ssspacez** [comment]
I know that, I'm talking about changing the default sound effect to a better one.

**Comment by collinss** [comment]
The default sounds help give a disto a certain 'feel' when you boot up the first time. However, it's not that hard to change the sound effect to something else, disable it, or lower the volume on sound effects. If I'm not mistaken, it also changes from one distro to another, so this isn't really a cinnamon issue at all.
