### ISSUE TITLE
Large notifications lock window manager

### ISSUE THREAD

**Issue by ianbark** [linuxmint/Cinnamon#7509]
```
 * Cinnamon version 3.4.6
 * 64 bit
 ```

**Issue**
Notifications (the semi-transparent black ones) that are too tall for the screen lock up the window manager. The close button is hidden (below the screen), there is no obvious way of closing the notification, and it is near-impossible to switch focus to other windows.

**Steps to reproduce**
1. Run a program that produces an extremely long notification message (for example, if you have an IDE that produces a notification when compile fails, with the name of all the targets being compiled, compile several hundred targets with an error.)
2. Make sure the notification gets focus when it pops up 
3. It is now impossible to switch to other windows. Clicking on other windows does not bring them up. If the notification will go away when the notifying window is selected, it is impossible to select that window.
4. It is not possible to type anything
5. Clicking on Menu does not bring up the menu
6. Control-L does not lock the screen
7. Pressing Enter or ESC on the notification window does not close it.
8. Clicking on the notification does not close it.
9. Dragging the notification did not move it (I could not move it up so that I could get to the close button)
10. The only way I was able to get out of the problem was to alt-tab to the notifying window, which caused the notification to go away. Not sure if that was particular to my IDE or a general way of escaping from the lock up.

**Expected behaviour**
Able to close notification and/or interact with other windows. In particular, the close button should always be visible regardless of the length of the notification message.

**Other information**

**Comment by leigh123linux** [comment]
Can you reproduce with a program that doesn't abuse the notification system

> Steps to reproduce

    Run a program that produces an extremely long notification message (for example, if you have an IDE that produces a notification when compile fails, with the name of all the targets being compiled, compile several hundred targets with an error.)

**Comment by itzexor** [comment]
I recently committed a patch to Cinnamon to fix extreme lag on mouseover with very long notifications. But if this is not a libnotify notification it won't have any effect. Some applications generate their own notification windows and we can't control any of that.

**Comment by leigh123linux** [comment]
Here's the spec for notification

https://developer.gnome.org/notification-spec/

The notification isn't there for the IDE to dump it's load, I believe it should limit the notification to summary only.

**Comment by itzexor** [comment]
I also recently committed a patch to add a close button
