### ISSUE TITLE
Feature: "Fill window", "Fill window horizontally", "Fill window vertically"

### ISSUE THREAD

**Issue by slinkp** [linuxmint/Cinnamon#751]
These are three really nice keybindings in XFCE that aren't in Cinnamon (or Gnome 2 for that matter). 

They are like "Maximize window" (and the horizontal / vertical variants) except that the window only grows until it gets to the edge of another window.   (If there are no other windows, then it's the same as maximize.)

Really useful if you commonly like to have several windows using all available space without overlapping.

(I forget exactly where you go to set these in xfce; something like Settings -> Window Manager -> keybindings)

**Comment by Vahan86** [comment]
@JosephMcc , please see the comment posted above.

**Comment by JosephMcc** [comment]
What he is asking for still isn't possible in Cinnamon so the feature request is valid.

**Comment by JosephMcc** [comment]
Thank you for your suggestion. See https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html for information on how we handle feature requests.
