### ISSUE TITLE
A form of focus stealing across workspaces can't be disabled

### ISSUE THREAD

**Issue by shachaf** [linuxmint/cinnamon#7510]
The [window attention handler code](https://github.com/linuxmint/Cinnamon/blob/2cb31053f9324183b59e7279551b04c7d2458b81/js/ui/windowAttentionHandler.js#L45-L57), when a window in another workspace demands attention, either switches the current workspace to the window's workspace or moves the window to the current workspace (depending on a configuration flag). Either of these causes the window to effectively steal focus, regardless of the focus-stealing configuration: Rather than just showing a notification, it interrupts whatever the user is doing and becomes active. It would be nice to have a way to disable this behavior.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
