### ISSUE TITLE
Can't uninstall Flatpaks from the Cinnamon menu

### ISSUE THREAD

**Issue by eladhen** [linuxmint/Cinnamon#7519]
```
 * Cinnamon version 3.6.7
 * Distribution - Mint 18.3
 * Graphics hardware *and* driver used: Graphics:  Card: Advanced Micro Devices [AMD/ATI] Cape Verde XT [Radeon HD 7770/8760 / R7 250X]
           Display Server: X.Org 1.18.4 drivers: ati,radeon (unloaded: fbdev,vesa)
           Resolution: 1920x1080@60.00hz
           GLX Renderer: AMD CAPE VERDE (DRM 2.50.0 / 4.13.0-39-generic, LLVM 5.0.0)
           GLX Version: 3.0 Mesa 17.2.8
 * 64 bit
 ```

**Issue**
Trying to uninstall a Flatpak program from the menu (by right clicking and choosing uninstall) you get a message that this item isn't related to any package, and you are offered to just remove the item without uninstalling it.

**Steps to reproduce**
Opening the Cinnamon menu, choosing a program installed through Flatpak, right clicking it and choosing uninstall.

**Expected behaviour**
The program would be uninstalled.

**Other information**

**Comment by mtwebster** [comment]
Fixed by https://github.com/linuxmint/mint-common/commit/b150b835f4ae0e3b6dd758c3278e34149dd7fa4e and the additional flatpak support added to mintinstall.
