### ISSUE TITLE
No Sound HDMI Output

### ISSUE THREAD

**Issue by pavelkomarov** [linuxmint/Cinnamon#7520]
```
 * Cinnamon version 3.6.7
 * Distribution - Mint 17.3
 * Intel HD Graphics 5500 with Intel Corporation Broadwell-U Integrated Graphics (rev 09) (prog-if 00 [VGA controller])
 * 64 bit
 ```

**Issue**
I have been using Linux Mint since 2014 across four different computers and have never in all this time been able to output sound over HDMI. There are numerous issues on the linux mint forums about it (https://forums.linuxmint.com/viewtopic.php?t=242328, for example), but none have ever provided a solution that has worked for me.

**Steps to reproduce**
Install Linux Mint, plug your computer in to a TV via HDMI, and try to play a video. The picture will appear just fine, but audio will continue to come from the laptop.

**Expected behaviour**
Both audio and video should be output to the TV.

**Other information**
This might not be just a Cinnamon problem. I've heard whispers of this occurring with other distros, though a friend who uses Ubuntu claims he has not had this problem. If any of you know better than I which Mint subsystem should be responsible for this, tell me so I can migrate this issue to that repo instead.

**Comment by leigh123linux** [comment]
This is either a pulseaudio, alsa or kernel issue, not cinnamon.
