### ISSUE TITLE
(Per-app) mute notifs

### ISSUE THREAD

**Issue by Salamandar** [linuxmint/cinnamon#7525]
That'd be great to allow muting notifications ("for one hour, a day, forever,…"), and per-app.

**Comment by ManIVIctorious** [comment]
Especially a per application setting would be very nice

**Comment by Vahan86** [comment]
@icarter09, can we mark this issue as a feature request?

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
