### ISSUE TITLE
icons are not changed after selecting a new icon package

### ISSUE THREAD

**Issue by volker-raschek** [linuxmint/Cinnamon#7535]
```
 * Cinnamon 3.8.1
 * Arch Linux
 * VGA compatible controller: NVIDIA Corporation GF110 [GeForce GTX 570 Rev. 2] (rev a1) (prog-if 00 [VGA controller])
 * 64 bit
* nemo 3.8.1
 ```

**Issue**
After upgrading from version 3.6.x to 3.8.1, the icons in the left side of the file browser no longer change when Adawaita is selected as the control package. 

If you select a Mint-X package instead of Adawaita as control package, the icons in the left side of the file browser are displayed according to the icon package, but some menu buttons disappear in the header line.

The direction of the icons in the left side of the file browser depends on the selected control package and its relationship to the icon package. 

See my video, I want only to display Mint-X-Aqua Icons as Icons for my file browser in my main windows and my sidebar.

https://youtu.be/9cDjj2CWgMA

Volker

**Steps to reproduce**
Install Arch Linux and all installed packages from aur.

**Expected behaviour**
Display the correct selected icons packed in main windows and sidebar.

**Other information**
Installed Packages
Mint-X-Icons: https://aur.archlinux.org/packages/mint-x-icons/
Mint-X-Theme: https://aur.archlinux.org/packages/mint-x-theme/
Mint-Y-Icons: https://aur.archlinux.org/packages/mint-y-icons/
Mint-Y-Themes: https://aur.archlinux.org/packages/mint-y-theme/
Mint-Cinnamon-Themes: https://aur.archlinux.org/packages/mint-cinnamon-themes/

**Comment by NikoKrause** [comment]
@eli-schwartz The mint-x and mint-y themes (https://github.com/linuxmint/mint-themes) in Arch don't seem to be updated. The icon themes as well.

**Comment by NikoKrause** [comment]
@volker-raschek Except that your themes are not up to date, everything looks as expected.
Nemo changed the icons in the sidebar form fullcolor versions to symbolic icons.

**Comment by leigh123linux** [comment]
Arch will need to update to the latest mate-themes package as the ones your using lack gtk-3.22 support.

```
mint-y-icons-1.1.4-1.fc28.noarch
mint-y-theme-1.6.2-1.fc28.noarch
mint-themes-1.6.2-1.fc28.noarch
mint-themes-gtk3-1.6.2-1.fc28.noarch
mint-x-icons-1.4.7-1.fc28.noarch
```

@eli-schwartz theme packaging has changed for mint-themes, it now provides mint-y-theme and mint-themes-gtk3.

looking at my spec my help, at least it will provide a link to the source

https://src.fedoraproject.org/cgit/rpms/mint-themes.git/tree/mint-themes.spec

**Comment by leigh123linux** [comment]
@SamBurgos

Mint-X is part of mint-themes and has been updated for gtk-3.22

**Comment by eli-schwartz** [comment]
@SamBurgos No problem, we get when life interferes with stuff. :) I was just clarifying the situation here as I'm not directly responsible for packaging themes as well as the cinnamon packages in [community].

Looks like the simplest update path is to create a new AUR package mint-themes which provides, conflicts, and replaces the x and y theme packages. Then submit a merge request for the old packages so I can merge the comments and votes into the new pkgbase.

I'm not sure it is worth doing a split package, but that's your choice.

**Comment by SamBurgos** [comment]
@eli-schwartz No problem, I flagged the packages mint-y-themes and mint-cinnamon-themes in AUR and I will also try to create a new package that can merge and update the three of them later if possible, since currently they are split and I will have to make some new tests about it. If needed you can contact me to my email so that we don't spam the issue here (it is the same I have registered on the AUR site)

Kind regards

**Comment by SamBurgos** [comment]
Greetings @eli-schwartz  I wanted to let you know that I submitted the request for the required packages of Mint-X, Mint-Y and Cinnamon themes in the AUR, the new package is called mint-themes and with it I hope I am able to provide a single package for the three of them as upstream handles currently

If there is any need of me to do something else, please let me know. I wrote you on the email registered on your Github as well so my apologies for the spam. Kind regards

**Comment by volker-raschek** [comment]
@SamBurgos 
The same issue would be discussed on arch linux
https://bbs.archlinux.org/viewtopic.php?id=236463

**Comment by germanfr** [comment]
You just have to add this to your gtk.css file. No need to modify system icons @volker-raschek
```scss
.nemo-places-sidebar { -gtk-icon-style: regular; }
```

**Comment by volker-raschek** [comment]
Where is the storage location from the gtk.css file?
I can't find `gtk.css` file in my home directory `~`.

**Comment by eli-schwartz** [comment]
Maybe this will help: http://twicetwo.com/blog/linux/gtk/theme/customization/2016/05/04/per-user-gtk-customization.html

Though as mentioned above the themes should be updated now anyway.

**Comment by volker-raschek** [comment]
Hey @eli-schwartz ,
thanks for the link. 

I've created in the directory `~/.config/gtk-3.0` the `gtk.css` file with this content.
```css
/* Load the original theme */
@import url("/usr/share/themes/Mint-X-Aqua/gtk-3.0/gtk.css");

/* Override nemo settings */
.nemo-places-sidebar { -gtk-icon-style: regular; }
```
Now I get the right icons, but some icons are not available in mint-theme package. See my [screnshot](https://user-images.githubusercontent.com/18311012/39803384-300185fe-5371-11e8-8dbe-0043846c2904.png) and than the icons for an remote (ftp) folder.

Next, when I use my own `gtk.css` file, I can't select my own background, every time when I want to change my background I get a default grew background.
 
Is a general bugfix for the problem with the icons in the sidebar available or merged in any package, that I don't need to patch every system? 

Volker
