### ISSUE TITLE
Weird slider behaviour in audio settings

### ISSUE THREAD

**Issue by NicoWeio** [linuxmint/Cinnamon#7537]
```
 * Cinnamon 2.8.8
 * Mint 17.3
 * Graphics hardware *and* driver used
 * 32 or 64 bit
 ```

**Issue**

The volume sliders of the applications tab in the audio settings shows unexpected behavior:
Sliding it to the left end disables the switch on the right, but sliding it to the right again (with a continuous mouse-button press) would not re-enable the switch, but instead reset the slider to the left as soon as you release the mouse-button.

**Steps to reproduce**

Open Audio settings, select Applications tab, make sure some application is shown and drag the slider to the very left and to the very right. Then release the mouse button.

**Expected behaviour**

The slider and the switch next to it should work "normally"...

**Comment by JosephMcc** [comment]
This behaviour isn't reproducible in Cinnamon 3.8.
