### ISSUE TITLE
Unable to enable dark theme variants

### ISSUE THREAD

**Issue by testman42** [linuxmint/Cinnamon#7540]
```
 * Cinnamon 3.8.0
 * Fedora 28
 * 64 bit
 ```

**Issue**
![dark1](https://i.imgur.com/07v3OZe.png "")
![dark2](https://i.imgur.com/LOcn2sD.png "")

The toggle has no effect and does not persist. If I close `cinnamon-settings` and open it again, toggle is disabled again.

**Steps to reproduce**
- Open `cinnamon-settings`
- Click on "Themes"
- Click on "Settings"
- Click on "Use dark theme variant when available in certain application" toggle

**Expected behaviour**
Setting should take effect and save it's state

**Comment by JosephMcc** [comment]
This setting no longer exists in Cinnamon master and will disappear in one of the 3.8 updates.
