### ISSUE TITLE
Panel: All numbers do not display

### ISSUE THREAD

**Issue by the-slugging-chaos** [linuxmint/Cinnamon#7544]
```
 * Cinnamon 3.6.7
 * Linux Mint 18.3
 * Intel integrated graphics 
 * 64 bit
 ```

**Issue**
In the panel, all numbers dissapear. Other characters still show up as expected:
![image](https://user-images.githubusercontent.com/38981574/39629358-30cfc248-4fac-11e8-9c43-d97a38641281.png)

**Expected behaviour**
Numbers should be displayed as expected

**edit**

- [xsession-errors.txt](https://github.com/linuxmint/Cinnamon/files/1976552/xsession-errors.txt)
- there were no errors or warnings in looking glass

**Comment by Amosar** [comment]
To give more informations to the devs try to attach your log from ~/.xsession-errors and if you have any error in looking glass (right click on your panel>Troubleshoot>Looking Glass) then wait until a real cinnamon dev answer to your issue ^^

**Comment by the-slugging-chaos** [comment]
updated the main post :)

**Comment by NikoKrause** [comment]
1. Maybe it's a themeing issue: try changing themes
2. Maybe it's an applet issue: 
    * try to reset your applets (Rechtsklick auf Leiste -> Fehler suchen -> Alle Standardeinstellungen wiederherstellen)
    * if that doesn't help, try another calendar applet, e.g. https://cinnamon-spices.linuxmint.com/applets/view/108

**Comment by the-slugging-chaos** [comment]
Thanks, resetting the applets worked! :D
