### ISSUE TITLE
Panel auto stretches across all connected displays. no way to disable

### ISSUE THREAD

**Issue by mark4th** [linuxmint/Cinnamon#7548]
```
 * Cinnamon version (3.6.1-r4)
 * Distribution - (Gentoo)
 * Graphics hardware *and* driver used: nvida
 * 32 or 64 bit: 64 bit
 ```

**Issue**
When adding a new monitor the existing panel automatically stretches across both displays.  IF the second display is a lower resolution this puts the tray area in below the bottom of the second display and makes it inaccessible.

**Steps to reproduce**

**Expected behaviour**
Fully expect a panel to be restricted to the main display not automatically stretch across all displays.

**Other information**

**Comment by leigh123linux** [comment]
Feel free to reopen if you can reproduce the issue with a supported cinnamon version (3.8.0) as 3.6.x is EOL.
