### ISSUE TITLE
Blurry cinnamon desktop after restarting cinnamon(Alt F2)

### ISSUE THREAD

**Issue by WattanaGaming** [linuxmint/Cinnamon#7555]
```
 * Cinnamon version 3.6.7
 * Mint 18.3
 * Graphics hardware *and* driver used
 * 64 bit
 ```

**Issue**
Everything gets fuzzy and gives me an eyesore.
Changing graphic driver, purging and reinstalling cinnamon components doesnt seem to fix

**Steps to reproduce**
Press ALT+F2
Enter R and press enter again

**Expected behaviour**
The cinnamon desktop will restart and everything will get blurry and fuzzy.

**Other information**
I was using linux mint without reinstalling for quite a long time and i cant seem to find a way to fix this

**Comment by NikoKrause** [comment]
Can you show a screenshot?

**Comment by WattanaGaming** [comment]
I cant really take a screenshot because the flash effect updates everything on the screen :/
only the unupdated part of the screen gets extremely fuzzy

**Comment by leigh123linux** [comment]
@WattanaGaming  use scrot instead

**Comment by NikoKrause** [comment]
Or take a photo of your screen with a camera or smartphone

**Comment by JosephMcc** [comment]
Since the issue was reported against Cinnamon 3.6 and the OP didn't supply graphics hardware info which is probably quite important to this, I'm closing it. Follow questions have also gone unanswered.
