### ISSUE TITLE
Icons in notification applet in taskbar doesnt' change on notification

### ISSUE THREAD

**Issue by schlegel11** [linuxmint/Cinnamon#7556]
```
 * Cinnamon version 3.8.1
 * Distribution - Arch Linux (4.16.6-1-ARCH)
 * Intel Corporation Xeon E3-1200 v3/4th Gen Core Processor Integrated Graphics Controller
 * 64 bit
 ```

**Issue**
Cant see icon notifications in taskbar -> icons in notifications applet doesn't change
e.g. email received and thunderbird icon changes to icon with 1 inside or
pamac (package manager) icon doesn't change to red icon if an upgrade is available.

**Steps to reproduce**
I think its since I upgrade cinnamon to version 3.8.1.
On initial system boot it seems to work but after some time working on the system it doesn't.
I'm not sure how to reproduce the behaviour exactly.

**Expected behaviour**
see Issue

**Other information**
nothing

**Comment by Madh93** [comment]
Same problem here.

```
 * Cinnamon version 3.8.2
 * Distribution - Manjaro Linux (4.14.39-1-MANJARO)
 * Intel Core i7-7700 CPU @ 3.60GHz × 4 wth HD Graphics 630
 * 64 bit
```
In my case Telegram and Slack icons don't change when there're new notifications.

Temporary solution: restart cinnamon (`Ctrl+Alt+Esc`).

This fixes the problem during for a time, however it comes back again later.

**Comment by schlegel11** [comment]
I think it's working again completely since I updated to version "3.8.4":thumbsup:

**Comment by JosephMcc** [comment]
If it continues to work as expected, will you please close the issue?

**Comment by schlegel11** [comment]
Ah ok. I thought I should wait until someone can clearly confirm that the issue is fixed.
Can you confirm that the issue is fixed?
But anyway I can close the issue and if I see another behaviour reopen it later again.

**Comment by schlegel11** [comment]
Ok. No problemo. I will close it an we will see. But it looks good:wink:
Thanks for the work and effort.:relaxed:

**Comment by schlegel11** [comment]
OK. I have to reopen the issue.
I think it worked a little bit longer but just now I saw that I had some notifications but no changes of any icons in the notify applet.

**Comment by gkatev** [comment]
I can also confirm the problem persists.

**Comment by germanfr** [comment]
I'm having the same issue with the Telegram systray icon. It sometimes displays a (1) when I already read the messages and sometimes it doesn't show the (1): the icon doesn't always update. Restarting Cinnamon solves it temporarily. I'm on 3.8.4.

**Comment by jhquentin** [comment]
I have same problem

quentin@ntb-quentin ~ $ cinnamon --version
Cinnamon 3.8.4
quentin@ntb-quentin ~ $ cat /etc/redhat-release 
Fedora release 28 (Twenty Eight)

**Comment by schlegel11** [comment]
I'm not sure but I think that my tray icons work again.
I'm currently on cinnamon version 3.8.6.
Perhaps it's related to this [commit](https://github.com/linuxmint/Cinnamon/commit/3b74a69e85281a0e6a58d6685269c07a18385a64).

But I'm not sure ;)

**Comment by jhquentin** [comment]
I will hope, but I am not using panel autohide function.

**Comment by germanfr** [comment]
Me neither. 3.8.8

**Comment by JosephMcc** [comment]
Ok. I'm closing this. If anyone comes back and still has the issue, it can be reopened.
