### ISSUE TITLE
Feature request: way to revert to text boot (as Vs 'plymouth')

### ISSUE THREAD

**Issue by CottonEaster** [linuxmint/Cinnamon#7557]
```
Mint 18.3 Cinnamon
 ```

**Issue**

Try as I might I cannot get full or even full-ish boot messages to display, by default. (I know that I can, at least on shutdown as against boot, press a key to toggle the messages.) The program 'plymouth' seems to be the culprit, but removing its package does not seem an option and disabling it seems hard.

I apologise if I overlook some existing, easy way to get a textual boot on Mint Cinnamon.

**Other information**

There is [a program that seems able to disable plymouth](https://launchpad.net/plymouth-manager/+download) but I (and others) cannot get it to run.

**Comment by itzexor** [comment]
https://ubuntuincident.wordpress.com/2015/03/12/disable-quiet-splash-during-boot/

**Comment by itzexor** [comment]
Also this isn't a cinnamon issue. It's a grub/distro setting.

**Comment by CottonEaster** [comment]
Thanks to you both. However:

- I've tried to no avail what that link recommends.

So,

- should I post this report in . . actually, where?

**Comment by CottonEaster** [comment]
Ah, it was my mistake - sort of. I found that the program grub-customizer was not propagating my boot parameters to the particular line that was booting my kernel. I may file a bug report for that package. Once 'quiet splash' was removed from the line that actually did the booting, I got a verbose boot.

**Comment by CottonEaster** [comment]
Ah, it was my mistake - sort of. I found that the program grub-customizer was not propagating my boot parameters to the particular line that was booting my kernel. I may file a bug report for that package. Once 'quiet splash' was removed from the line that actually did the booting, I got a verbose boot.
