### ISSUE TITLE
Psi+ still steals focus on notification events (chat message, status changing)

### ISSUE THREAD

**Issue by dvdesolve** [linuxmint/Cinnamon#7558]
```
 * Cinnamon version 3.8.1
 * Distribution - Arch Linux
 * NVIDIA GTX 750 (binary driver), Intel HD Graphics 530 (xf86-video-intel driver)
 * 64-bit OS
 ```

**Issue**
Fixes for some apps in windowAttentionHandler.js has been added some years ago. However, current version of Psi+ (1.3.344.0.g64b0e61e) still suffers from that annoying bug - opened Psi+ windows steal focus on events despite of corresponding settings are disabled in program config

**Steps to reproduce**
1. Disable chat auto-raising on incoming messages and events in Psi+ settings and leave chat windows open
2. Just wait for your buddy to begin writing to you

**Expected behaviour**
In case of disabled auto-raising focus shouldn't be stealed, only notification should occur

**Comment by leigh123linux** [comment]
Add psi to the blacklist 'org.cinnamon demands-attention-ignored-wm-classes'

```
$ gsettings get org.cinnamon demands-attention-ignored-wm-classes
['skype', 'viber', 'quassel', 'retroshare', 'psi-plus', 'kvirc', 'pidgin']
```

**Comment by Ri0n** [comment]
Tested with simple Qt application with next code in its widget

```
    QTimer::singleShot(5000, [this](){
        QApplication::alert(this, 3000);
    });
    QTimer::singleShot(10000, [this](){
        raise();
        activateWindow();
    });
```

Both times the application was raised intercepting focus. Same code with any other Window Manager works as expected (no interception).

Basically it's a Cinnamon bug. No idea way Cinnamon developers think it's a feature.
