### ISSUE TITLE
Hot Corner: maximize window

### ISSUE THREAD

**Issue by ssspacez** [linuxmint/Cinnamon#7564]
I was testing another distro and it had the maximize window option for hot corners, I gave it a try and it was very handy, it improves the workflow. For Cinnamon: any plans of implementing this nice feature?

Related: https://github.com/linuxmint/Cinnamon/issues/1153 and https://github.com/linuxmint/Cinnamon/issues/2117

**Comment by germanfr** [comment]
You can already do that with the custom command option using this command:
```
wmctrl -r :ACTIVE: -b toggle,maximized_horz,maximized_vert
```

**Comment by ssspacez** [comment]
This command doesn't work, I've pasted it in the command box, and the rest after `-r` disappeared, and inside it was just `wmctrl -r`. Even when you type it, after  `:` the blinking cursor goes back to the beginning.

**Comment by germanfr** [comment]
You need to update to the latest version. That bug is already fixed.

**Comment by NikoKrause** [comment]
It's this issue:
https://github.com/linuxmint/Cinnamon/issues/7518
