### ISSUE TITLE
expo and overview animation time

### ISSUE THREAD

**Issue by CosmicTachyon** [linuxmint/cinnamon#7572]
This is a feature request. In `expo.js` and `overview.js` the animation time for showing all the workspaces and windows is set by the `ANIMATION_TIME` parameter. The default value for this animation time is set to 0.3 s (expo) and 0.25 s (overview). Currently, unticking the Effects in System Settings does not affect the above animation times. I find that by setting `ANIMATION_TIME` to nearly zero (0.01 s) it makes the displaying of the workspaces and widnow overview through hot corners snappier and appears more responsive. It would be nice if one of the options in the Effects menu was disabling the animation effects for showing all workspaces and windows overview. Thank you. I use Cinnamon 3.8.2 on Arch Linux.

**Comment by germanfr** [comment]
I'll add this to #7541

**Comment by germanfr** [comment]
This can be closed, it's already fixed in the latest version.

**Comment by JosephMcc** [comment]
This is the same as: https://github.com/linuxmint/cinnamon/issues/446

**Comment by CosmicTachyon** [comment]
Super! Thank you very much for implementing this!
