### ISSUE TITLE
nemo stops file transfer

### ISSUE THREAD

**Issue by illumilore** [linuxmint/Cinnamon#7574]
```
 * Cinnamon version (cinnamon --version) Cinnamon 3.6.7
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) 18.3
 * Graphics hardware *and* driver used nvidia 390
 * 32 or 64 bit 64bit
 ```

**Issue**
When transferring large files from a samba share, nemo will randomly stop transferring and freeze with no error messages.

**Steps to reproduce**

**Expected behaviour**

**Other information**

**Comment by JosephMcc** [comment]
This is an issue with nemo: https://github.com/linuxmint/nemo/issues
