### ISSUE TITLE
System Settings: pressing Window borders icon stalls, without busy pointer

### ISSUE THREAD

**Issue by CottonEaster** [linuxmint/Cinnamon#7575]
```
 * Cinnamon version (cinnamon --version) 3.6.7
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 18.3
 * Graphics hardware *and* driver used: Intel Kabylake GT1.5 3.0 Mesa 17.2.8
 * 32 or 64 bit: 64
 ```

**Issue**

Pressing the 'Window borders' icon (pictured) stalls, without busy pointer, after installing a new theme.

![image](https://user-images.githubusercontent.com/9998846/39961384-c4e5f12e-562c-11e8-98b1-1046459befe6.png)

**Steps to reproduce**

1. Install, say, the `arc-theme`.
2. Press the 'window borders' button. (Possibly for the problem to occur, the 'themes' window needs to be open already.

**Expected behaviour**

If the theme selector window cannot open almost instantly, then the pointer should show busy.

**Other information**

**Comment by JosephMcc** [comment]
The themes window is in need of a few tweaks. Thanks for the suggestion.
