### ISSUE TITLE
Icon theme does not apply

### ISSUE THREAD

**Issue by Sternobaldius** [linuxmint/Cinnamon#7579]
```
 * Cinnamon 3.6.7
 * Ubuntu 18.04 Desktop
 * NVIDIA G98M (I don't think driver is relevant)
 * 64 bit
 ```

**Issue**
Icon theme does not update.

**Steps to reproduce**
Change icon theme via Settings>Themes>Icons

**Expected behaviour**
Icon theme updates (e.g. to numix)

**Other information**
`apt-get` returns this:
```
Errors were encountered while processing:
 gir1.2-xkl-1.0:amd64
 gir1.2-gkbd-3.0:amd64
 cinnamon
 cinnamon-screensaver
 cinnamon-screensaver-x-plugin
```

Used `sudo apt install cinnamon` to install

When closing and re-opening the Themes Settings, the icon theme is still viewed (as e.g. numix) but the preview changed back to the default icon theme (Humanity)

EDIT: Button themes don't work either

**Comment by Sternobaldius** [comment]
Full output of apt-get (`sudo apt-get upgrade`):
[apt-get output.txt](https://github.com/linuxmint/Cinnamon/files/1998404/apt-get.output.txt)

**Comment by Sternobaldius** [comment]
Worked with `gnome-tweaks`.

**Comment by mtwebster** [comment]
gnome-tweaks should definitely not be needed here.

What is the result of `dpkg --list | grep cinnamon`?

Is csd-xsettings running? (`ps -A | grep csd`)

Also, uninstall nautilus or at the very least execute `gsettings set org.gnome.desktop.background show-desktop-icons false`

I would recommend a PPA if running cinnamon on Ubuntu (for example, `https://launchpad.net/~embrosyn/+archive/ubuntu/cinnamon`

**Comment by Sternobaldius** [comment]
Installing via PPA didn't help either.

**Comment by mtwebster** [comment]
Even after a reboot or at minimum log out and back in?  csd-xsettings *must* be running, if it's not, something is preventing it, or it's crashing.

Please post the output of `~/.xsession-errors` after a clean login.

Not sure why apt is failing, you can try `sudo apt-get install -f` to let it try to self-correct, or try to install the first failing package manually - `sudo apt-get install gir1.2-xkl-1.0`

**Comment by Sternobaldius** [comment]
`~/.xsession-errors` is not existant. 
`sudo apt-get install gir1.2-xkl-1.0` and `sudo apt-get install -f` don't work either.

**Comment by Sternobaldius** [comment]
I tried to start csd-xsettings manually, it returns 
```
...

(csd-xsettings:2266): xsettings-plugin-WARNING **: 16:41:31.814: You can only run one xsettings manager at a time; exiting
[cinnamon-settings-daemon-xsettings] Failed to start: Could not initialize xsettings manager.
```

**Comment by Sternobaldius** [comment]
Got the solution.
I couldn't start cinnamon directly at login, but it would work fine with `cinnamon --replace`. Therefore, I let Ubuntu launch gnome and configured `cinnamon --replace` to run automatically after login. This apparently caused some problems. 
I guess that installing via the PPA fixed my initial problem, so I can now just launch cinnamon instead of gnome and the Themes work correctly again.

**Comment by Sternobaldius** [comment]
> Therefore, I let Ubuntu launch gnome and configured cinnamon --replace to run automatically after login.
That solution was actually pretty crappy from the beginning.
