### ISSUE TITLE
Cannot edit custom launcher when Icon path is wrong

### ISSUE THREAD

**Issue by stamster** [linuxmint/cinnamon#7580]
```
 * Cinnamon 3.0.7
 * Distribution - 
Distributor ID:	LinuxMint
Description:	Linux Mint 18 Sarah
Release:	18
Codename:	sarah
 * Intel Corporation Mobile 4 Series Chipset Integrated Graphics Controller [8086:2a42] (rev 07)
 * amd64
 ```

I'm using simple custom launcher:

```
[Desktop Entry]
Version=1.0
Type=Application
Name=PhpStorm 2018
Icon=/home/user/PhpStorm-181.4892.97/bin/phpstorm.png
Exec="/home/user/PhpStorm-181.4892.97/bin/phpstorm.sh" %f
Comment=The Drive to Develop
Categories=Development;IDE;
Terminal=false
StartupWMClass=jetbrains-phpstorm
```

**Issue**

Accidentally I have provided wrong path for the icon. Apart from launcher correctly not showing icon any longer, Edit on that item does not work, no dialog box, nothing. 

So I guess error reporting or so is going bad here.

**Steps to reproduce**

Simply rename icon file on the file-system for some working launcher item, e.g. `icon.png` to `icon2.png` in order to make path wrong.

**Expected behaviour**
Dialog box showing normal screen where user is able to select new icon/other property and fix the issue.

**Other information**

Solution: I had to edit manually `~/.cinnamon/panel-launchers/`NAME`.desktop`, e.g. fixing the icon path.

**Comment by icarter09** [comment]
@stamster are you still experiencing this issue?

**Comment by Vahan86** [comment]
@icarter09, can we close this issue?
