### ISSUE TITLE
Computer acts as if shift, ctrl and q are pressed

### ISSUE THREAD

**Issue by CottonEaster** [linuxmint/Cinnamon#7583]
```
 * Cinnamon version (cinnamon --version) 3.6.7
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 18.3
 * Graphics hardware *and* driver used: Intel Kabylake GT1.5; 3.0 Mesa 17.2.8
 * 32 or 64 bit: 64
 ```

**Issue**

A few times a day, the computer acts as if the shift key is held down, or the control key, or the 'q' key. Indeed normally I'll have a problem with one key, which I can solve (note) by pressing the key, and then the problem shifts to another key in the set, though once I've run through all three keys, the problem abates.

The Google program KeyMon does not show any keys firing. There's no physical indication on the keyboard that the key is stuck (so far as I can tell). Limited testing with a Debian Live USB and a Windows Pre-Boot Environment does not reproduce the problem on those systems. 

The problem started about a month ago. The keyboard at issue is the one built into a ThinkPad X1 Carbon 6th generation

**Steps to reproduce**

With my setup, it seems I need merely to use the computer.

**Expected behaviour**

Obviously, none of this.

**Other information**

[A very similar problem has been reported on Ubuntu](https://ubuntuforums.org/showthread.php?t=1460150).

The problem I have seems to have begun at about the same time that [I plugged in an external monitor](https://github.com/linuxmint/Cinnamon/issues/7543) (though since then, I have not done that).

PS: Github periodically loses the caret in these input boxes, which makes things harder.

**Comment by leigh123linux** [comment]
Sorry this issue is unlikely to be within cinnamon stack, it could be kernel related.
