### ISSUE TITLE
Gross memory leak, possibly caused by cinnamon-settings daemon

### ISSUE THREAD

**Issue by CottonEaster** [linuxmint/Cinnamon#7585]
```
 * Cinnamon version (cinnamon --version) 3.6.7
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 18.3
 * Graphics hardware *and* driver used: on-chip Intel Kabylake
 * 32 or 64 bit: 64.
 ```

**Issue**

Suddenly I'd gone from _some 15% RAM usage - on a 16GB machine - to 97%_ (sic). The lack of available RAM made it hard to diagnose the problem (since, for one thing, System Monitor would not open), but when rebooting there was a message about the cinnamon settings daemon not responding.

This is a serious problem that affects my - one's - ability to use my computer. I didn't get a computer with 16GB of RAM to have to deal with this.

**Steps to reproduce**

Unknown.

**Other information**

I searched for similar issues on the bugtracker but to my surprise found none.

**Comment by leigh123linux** [comment]
Duplicate of https://github.com/linuxmint/Cinnamon/issues/6850
