### ISSUE TITLE
Windows application ("QuickLoad" via Wine) no longer visible on panel

### ISSUE THREAD

**Issue by antimatter84** [linuxmint/cinnamon#7586]
```
 * Cinnamon versions --> 3.6.7 + 3.8
 * Distributions --> Mint 18.1, Mint 18.3, Ubuntu Server with Cinnamon 3.8
 * Graphics hardware: Intel HD 630 with default Mint driver / Virtual Box graphics/driver
 * 64 bit
 ```

**Issue**
There is a ballistics software called "QuickLoad" which is probably programmed in Visual Basic 5. Although intended for Windows users it runs quite nicely with Wine, too. 

In Linux Mint 18.1 the application is not visible on the panel while running. Minimizing makes the application completely invisible. Restoring only works via Alt-Tab. I was able to reproduce this effect in Linux Mint 18.3 as well as in Ubuntu 18.04 Server with Cinnamon 3.8. Besides the current Wine version from the respective distro repositories I also tried Wine 3.0 (stable) and 3.8 (devel) from the WineHQ repository. The application was never visible on the panel.

It was visible in Linux Mint 17 Qiana.

**Steps to reproduce**
- get a standard installation of e.g. Mint 18.3 Cinnamon
- sudo apt install wine winetricks ttf-mscorefonts-installer
- open Wine Config dialog and let it configure the prefix, install gecko/mono libs if asked
- in winetricks, under "select default wineprefix" -> "install Windows DLL": tick "vb5run" and click OK.
- download the Quickload demo installer from here: https://reimer-johannsen.de/demoprogramm.htm
- run "wine qldemo.exe"

_Note:_ when asked for the installation path, don't accept the default as spaces make problems. Use something simple like "c:\quickload".
_Note:_ the installer might start searching for some INI file. Just click stop and the installer finishes.

- if all went well one should be able to launch Quickload from the desktop or the Wine menu.
- the main window of Quickload (yellow warning banner at the top) is not visible in the panel.

**Expected behaviour**
The application should be displayed in the panel.

**Other information**
Screenshots with Mint 17 Qiana and Mint 18.3 Sylvia are attached.
The Sylvia screenshot also shows the popular Windows tool "Dependency Walker" (including panel entry) for comparison. Apparently, the problem might be limited only to certain (VB5) applications.

![screen0026](https://user-images.githubusercontent.com/10585451/40238867-bd1c7ed6-5ab4-11e8-8bd1-3e0f71d3f898.png)
![screen0025](https://user-images.githubusercontent.com/10585451/40238868-bd38b290-5ab4-11e8-8a37-2b3d14997540.png)

**Comment by antimatter84** [comment]
By accident, I just found a workaround. After starting QuickLoad you can switch to another workspace and then back to previous one. Then the application is visible on the panel. Being a software developer myself this seems to be some minor bug.

**Comment by antimatter84** [comment]
I tested again with the new modern panel in Mint 19.1 Cinnamon. The application is also not shown in the new panel and the workaround (switching workspaces) no longer works.

**Comment by Vahan86** [comment]
@antimatter84, is this still an issue in Cinnamon 4.2?

**Comment by antimatter84** [comment]
The issue is gone. The application is correctly shown on the panel. 
If I recall correctly, that particular machine is now running Mint 19.2 Tina with the mentioned Cinnamon version 4.2.
