### ISSUE TITLE
After rebooting my headphone's sound balance is sometimes way to the right

### ISSUE THREAD

**Issue by C0rn3j** [linuxmint/cinnamon#7593]
```
 * Cinnamon version 3.8.3
 * Distribution - Arch
 * Graphics hardware *and* driver used - unrelated, happens on two desktops, one AMDGPU based one nvidia proprietary based
 * 64 bit
 ```

**Issue**

![image](https://user-images.githubusercontent.com/1641362/40356407-3b8208a2-5db9-11e8-8107-c3b3afc04e41.png)

**Steps to reproduce**

Unknown. Seems to happen rarely after rebooting.

**Expected behaviour**

Always have a 50/50 balance.

**Other information**

I never touch the balance settings other than to fix this issue.

This happens on two separate Arch boxes (two HyperX Cloud 2 headsets with identical firmware).

**Comment by C0rn3j** [comment]
Just had it happen again, which should tell you how frequently this occurs (and that I don't reboot often)

```
[0] % pacman -Q cinnamon
cinnamon 4.0.8-1
```

**Comment by icarter09** [comment]
@C0rn3j are you still experiencing this issue?

**Comment by C0rn3j** [comment]
I don't use Cinnamon anymore so might as well close it as nobody else complained.
