### ISSUE TITLE
Firefox fullscreens on secondary monitor in undesired situations

### ISSUE THREAD

**Issue by BNolet** [linuxmint/Cinnamon#7598]
```
 * Cinnamon version: 3.8.2
 * Distribution: Fedora 28
 * Graphics hardware: Intel HD, mesa-vulkan-drivers.x86_64
 * 64 bit
 ```

**Issue**
Undesired cases where Firefox (could be other apps but this is the only one I've found) goes fullscreen on a second monitor

**Steps to reproduce**
Case 1: Maximize Firefox (60, not tested on previous versions) on secondary screen, bring mouse to absolute top of screen and drag downwards.

Case 2: Browse to YouTube and open a video, fullscreen the video and then un-fullscreen the video

**Expected behaviour**
Case 1: Firefox window is dragged along with the mouse, allowing for full movement of the window

Case 2: Video just un-fullscreens without fullscreening Firefox
**Other information**
Cinnamon is awesome :) Keep up the good work!

**Comment by mtwebster** [comment]
I can't reproduce this (Though I'm currently on firefox beta - 61b7) - do any other programs behave this way?  Terminal, file manager, etc..?  I'm getting the exact 'expected' behavior regardless of primary or secondary monitor.

How is your monitor layout - primary left, secondary right? Or ?

**Comment by mtwebster** [comment]
If you go into customize.. is Titlebar in the lower left corner checked or unchecked?  I was told that the unchecked mode is pretty buggy right now. In my version it seems to be improved (I can't reproduce your cases at least,) but if checking that resolves this behavior for you I'd keep the titlebar enabled for the time being.

**Comment by BNolet** [comment]
Ah I didn't even think of that! Yes, the issue is the titlebar being unchecked. The issue does not occur with the titlebar being present. 

However, I'm gonna test this with the beta.

**Comment by BNolet** [comment]
Unfortunately this is present with 61.0b8 and 62.0a1 

The funky thing is that this doesn't happen with any other app. Maybe I should bring this over to Mozilla?

**Comment by mtwebster** [comment]
Weird.. I wonder if there's another setting or preference somewhere at play.  My libs are pretty close to yours on Fedora I think, but I suppose there could be some other variables at play as well.

I'm inclined to blame FF for this myself, or at least hold off for now, since the behavior is unique (and I can't reproduce it myself)

**Comment by mtwebster** [comment]
As for your first case - dragging down while maximized, I can reproduce something like this if I fullscreen firefox, and draw down the auto-hidden tabs bar.  Clicking and dragging down on that has no effect other than hiding that row once your mouse leaves it.  It could appear like what you're describing, but that's fullscreen mode.

I have trouble figuring out what makes that auto-hide occur.  Sometimes it doesn't, sometimes it does.  What keeps messing me up is firefox can still appear merely maximized, when in actuality it's fullscreen.

I still can't reproduce any thing with youtube, except, again, if I mistake fullscreen+autohidden top panel mode with maximized.

**Comment by BNolet** [comment]
Thanks for attempting to re-create it. I'm using the Fedora Cinnamon spin if that makes any difference. 

I've put an issue up on bugzilla and they'll do some testing there too I'm sure so for now. I'm not able to re-create this issue on another DE (I've tried Budgie now, since it's using some of the GNOME stack just as I believe Cinnamon is).

**Comment by mtwebster** [comment]
Turns out the behavior manifests only on monitors with no panels, which was keeping me from reproducing.

https://github.com/linuxmint/muffin/commit/edf0ce49e39b3dd85a3ee1110c83f8b9c46adfe8

**Comment by BNolet** [comment]
o.o wow! How long until this is pushed out to the public do you gather?

**Comment by mtwebster** [comment]
Once it's tagged for a new version (probably this week) the Fedora maintainer is pretty prompt generally about getting the new version out.

**Comment by BNolet** [comment]
Fantastic, I'll keep an eye out for it. Thank you :)
