### ISSUE TITLE
Firefox can't set delivery date for USPS Click-N-Ship

### ISSUE THREAD

**Issue by wtuthill** [linuxmint/Cinnamon#7599]
```
 * Cinnamon version (cinnamon --version) - 3.6.7
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) - 18.3
 * Graphics hardware *and* driver used  - 1050 nvidia, also in VMware Workstation
 * 32 or 64 bit - 64-bit Firefox 60.0.1
 ```

**Issue**
Certain drop-down menus do not select properly.

**Steps to reproduce**
Go to the US Postal Service  website, select Click-N-Ship, fill out required fields, and try to select a shipping date from the drop-down menu. The error message below appears, in red, on upper left.
! You must select a shipping date

**Expected behaviour**
Works in Chrome on Linux Cinnamon, and in Firefox for Windows. 64-bit.

**Other information**
Firefox 60.0.1+linuxmint1+sylvia

**Comment by leigh123linux** [comment]
firefox isn't part of cinnamon.
