### ISSUE TITLE
Unable to login to Cinnamon's page

### ISSUE THREAD

**Issue by xzj8b3** [linuxmint/Cinnamon#7600]
Cinnamon 3.8.2
Fedora 28 x64
Card-1: Intel Haswell-ULT Integrated Graphics Controller
Card-2: Advanced Micro Devices [AMD/ATI] Mars LE [Radeon HD 8530M / R5 M240]
Display Server: x11 (X.org 119.6 ) drivers: i915,radeon Resolution: 1366x768@60.00hz
[OpenGL:] renderer: Mesa DRI Intel Haswell Mobile version: 4.5 Mesa 18.0.2

[Cinnamon Spices](https://cinnamon-spices.linuxmint.com/auth/login)

[Error displayed with each social](http://i66.tinypic.com/2dqkqy0.jpg)

**Comment by leigh123linux** [comment]
What does this have to do with cinnamon?

**Comment by leigh123linux** [comment]
login works fine on spice site.

![screenshot from 2018-05-25 06-58-12](https://user-images.githubusercontent.com/1299302/40528507-2371cf40-5fe9-11e8-82ba-16e715434694.png)

**Comment by xzj8b3** [comment]
![schermata da 2018-05-23 17-54-03](https://user-images.githubusercontent.com/26720956/40580360-ee479a0c-613c-11e8-82ff-e87476c2cac6.png)

Fedora 28 x64
