### ISSUE TITLE
Jetbrains Toolsbox icon either missing icon, or not appearing at all

### ISSUE THREAD

**Issue by kauffy** [linuxmint/cinnamon#7604]
```
 * Cinnamon version 3.6.7
 * Distribution -Mint 18.3-ubu
 * Multiple - nVidia GTX960 with proprietary, AMD Radeon 7800 M with default
 * 64 bit
 ```

**Issue**
I have several installations of Mint matching the above (I think three of them are copies of one-another, and another is a wholly separate install). I do not know if this is a Jetbrains issue or a Cinnamon issue.
Machine 1 & 2) Even though Jetbrains toolbox is running, no icon appears in the system tray for it-- all other icons appear normally.
Machine 3) Jetbrains toolbox is running, and has a space in the system tray, but the icon is blank. I have checked the directory and the .svg file for the icon (at least, what I believe is its icon) has fully readable permits.
Machine 4-- a USB key install, separate from the others) Toolbox appears in the system tray properly, and as expected.

**Steps to reproduce**
Install and launch Jetbrains toolbox.

**Expected behaviour**
When toolbox is running, the system tray icon would appear, as well as animating on its activity.

**Other information**

**Comment by kauffy** [comment]
I found the correlated issue on Jetbrains' site, and a workaround is that when launching jetbrains-toolbox, do so with dbus-launch. This produces the expected/desired behavior from the system tray icon.

**Comment by jtsagata** [comment]
And the link to the workaround is ?

**Comment by kauffy** [comment]
To clarify: any command-line that calls the Toolbox (in your startup options, or in menus, etc.) should be changed to have `dbus-launch` in front of it. You have have to completely recreate some shortcuts-- I found that even though I could edit them, the changes were reverted as soon as I saved out.

**Comment by icarter09** [comment]
@kauffy are you still experiencing this issue?

**Comment by jtsagata** [comment]
There is no issue in the latest versions, at least for me.

**Comment by icarter09** [comment]
@jtsagata thanks for the update.
