### ISSUE TITLE
Missleading translation in Power Settings 

### ISSUE THREAD

**Issue by Ridderby** [linuxmint/Cinnamon#7605]
```
 * Cinnamon 3.6.7
 * Mint 18.3
 * 64 bit
 * Nvidia proprietary 
 ```

**Issue**
Translation of "Suspend when inactive for" in Power Settings has an miss leading translation in Swedish to something like "Lock screen when in active for". The translation uses a badly formed sentence indicating a copy/paste problem. 

In the Swedish version of the Power Settings it looks like the form allows you to adjusts when a monitor first blanks/locks and later are put into sleep which is not true. 

**Steps to reproduce**
 * Learn some Swedish :) 
 * Select Swedish translation in for Cinnamon
 * Start power settings. 

**Expected behaviour**
The form shall prompt correctly; "Låt datorn vila när den varit inaktiv i"

**Other information**
A Swedish speaking person that know the actual intent with the settings will see the problem immediately.

**Comment by collinss** [comment]
Translations are maintained by a community of volunteers on launchpad. We don't handle them directly. Please submit your corrections there. You can get more information on how to do so [here](https://linuxmint-translation-guide.readthedocs.io/).
