### ISSUE TITLE
keyboard layout switch not working

### ISSUE THREAD

**Issue by arndf** [linuxmint/Cinnamon#7606]
```
 * Cinnamon version 3.6.7
 * Distribution - Mint 18.3
 * Graphics hardware - sorry don't know 
 * and* driver used -  NVidia driver version 384.111
 *  64 bit
 ```

**Issue**

Switching keyboard layouts does not work.

**Steps to reproduce**

- add keyboard switcher to toolbar
- start Keyboard setting
- go to keyboard layouts
- click "+"
- add "Arabic azerty"

- choose Arabic in keyboard switcher

-> keyboard works arabic with issues, e.g. spaces on wrong side, but switcher still shows "German" 

- try to swich back to German: nothing happens. Still arabic
- only way to get German back: Keyboard setting, remove arabic layout
- German layout back, but Arabic still in keyboard switcher

- try to pick another layout (e.g. English) from settings
- not added to keyboard chooser, still shows German and Arabic

**Expected behaviour**

Keyboard chooser should display all layouts active in keyboard setting.
Keyboard chooser should show current chosen layout

**Other information**

Same function works just fine in Mint XFCE.

My first bug report, hope this is the right place. Thanks.

**Comment by icarter09** [comment]
Cinnamon version 3.6.7
Linux Mint 18.3

I tried to duplicate this issue, but had no luck. I was able to add several different keyboard layouts and saw that the change was reflected both in the keys being typed and in the toolbar. I was also able to switch back and forth between different keyboard layouts with no issue either. I performed tests through the "Keyboard" option in the menu and also through "Keyboard Settings" in the toolbar when right clicking the flag/language of the given selected keyboard layout.

**Comment by arndf** [comment]
Thanks for checking this!
After the last reboot this problem no longer occurs. Maybe it was connected with other issues, for example, later, evolution no longer started (segmentation fault), then I tried to log out, and the X-Server crashed, text cursor appeared but no prompt, irresponsive, so I hit reset.

I'll come back here if that issue appears again.
