### ISSUE TITLE
Power applet: bug report / feature request - give the applet a 'working' tooltip when it is calculating battery power

### ISSUE THREAD

**Issue by ghost** [linuxmint/cinnamon#7607]
```
 * Cinnamon version (cinnamon --version) 18.3
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 18.3
 * Graphics hardware *and* driver used: Intel Kabylake integrated GPU; 3.0 Mesa 17.2.8
 * 32 or 64 bit: 64
 ```

**Issue**

Sometimes, when my laptop is unplugged, the power applet's tooltip takes about a minute to show the estimated battery life. In the interval before that happens (and after removing the power cord), the tooltip reads, only, 'battery power'. (That is a sign that the computer has recognised that it is now running on battery. My Conky, and the firing of my udev rules, confirm the recognition of the new power state.)

**Steps to reproduce**

1. Run laptop on AC power.
2. Disconnect AC power.
3. Examine tool tip.
4. Due to the intermittent nature of the problem, repeat 1-3 if the reported behaviour does not occur.

**Expected behaviour**

It would be helpful, and would add polish, were the tooltip to say something like

> Battery power - calculating time left . .

**Other information**

- My laptop: Lenovo X1 Carbon 6th Generation. 
- I run tlp. I use tweaks from Powertop.
- I am happy to give further details if relevant.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
