### ISSUE TITLE
New feature request -- make alt+tab program centric

### ISSUE THREAD

**Issue by kaashmonee** [linuxmint/cinnamon#7609]
```
 * Cinnamon version (cinnamon --version) 3.6.7
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 18.3
 * Graphics hardware *and* driver used Intel integrated graphics
 * 32 or 64 bit, 64 bit
 ```

**Issue**
Currently alt+tab cycles through _all_ the possible windows that are open. I would like it to replicate the same function that existed in Unity, where alt+tab cycles through all the _programs_ that are open. Since alt+~ cycles through all the windows of a particular program already, I find that alt+tab's functionality is somewhat redundant.

**Steps to reproduce**
alt+tab, alt+~

**Expected behaviour**
Described above

**Other information**
Thank you very much!

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
