### ISSUE TITLE
Orphan dialog boxes not reachable from window tray or by alt-tabbing

### ISSUE THREAD

**Issue by autarkper** [linuxmint/Cinnamon#761]
There are some dialog boxes, which I call "orphaned", because they don't have a visible parent, that are very easily lost unless they are handled immediately; one example is the "System program problem detected" dialog. If such a dialog is obscured by other windows, you need to minimize or move those windows until you find the dialog, because it is not visible in the window tray and it does not show up when alt-tabbing.

**Comment by MarkJeronimus** [comment]
I see that this was fixed 12 years ago, but in my (somewhat old) Fedora 36, I'm plagued by this issue. Is there a setting that needs to be enabled to enjoy this fix?
