### ISSUE TITLE
Menu Editor may wipe cinnamon-applications.menu

### ISSUE THREAD

**Issue by irrenhaus3** [linuxmint/cinnamon#7610]
```
 * Cinnamon version 3.6.7
 * Distribution  - Mint 18.3
 * (Graphics information omitted)
 * 64bit system
 ```

**Issue**
When making changes to the Menu applet via the menu editor, the config file `~/.config/menus/cinnamon-applications.menu` may be truncated to a size of 0 bytes. This effectively removes any and all items from the menu; rm- or mv-ing the config file and then restarting cinnamon restores the menu to a vaid state.  

**Steps to reproduce**
Unknown, but related to making changes via the Menu editor; may be connected to the "Delete" button.

**Expected behaviour**
Changes are applied and stored in `~/.config/menus/cinnamon-applications.menu`, which is a valid XML file.

**Other information**
In the broken state of a 0-byte config file, the menu editor also doesn't open anymore (which means the user can't undo the breaking changes via the "Restore System Configuration" button).
See also: https://forums.linuxmint.com/viewtopic.php?t=161006

**Comment by icarter09** [comment]
@irrenhaus3 are you still experiencing this issue? If so, can you provide the steps to reproduce? Thanks.

**Comment by Vahan86** [comment]
@icarter09, can we close the issue since there is no response from OP?

**Comment by irrenhaus3** [comment]
Hi there, sorry for the late reply, I've been kinda busy over the month.
As of cinnamon 4.2.4, I don't experience the issue anymore (and haven't ever since that one occurrence, actually). 
However, I still don't know what the original cause was, only that it was related to deleting entries from the menu. The forum thread I linked in the OP contains some additional datapoints (e.g. someone tried to hide a menu entry with non-ASCII characters in it, after which the menu was in the same broken state as mine was), but whether any of those was the actual cause of the problem I can't say.
All useful additions to this post I could gather from skimming the old IRC chatlogs is this screenshot of what the menu looks like with a truncated config file: [https://i.imgur.com/ZhMxl4M.jpg](url)
So bottomline: Bug _may_ still exist, but if it does, I haven't seen it since.

**Comment by icarter09** [comment]
@irrenhaus3 no worries on the late reply and thanks for the update. I'm going to close this ticket since you are no longer experiencing the issue. If the issue does show back up, please do create a new ticket or I can reopen this ticket. Thanks.
