### ISSUE TITLE
Wrong driver loaded for Nvidia card

### ISSUE THREAD

**Issue by loceric** [linuxmint/Cinnamon#7611]
```
 * Cinnamon version (cinnamon 18.3)
 * Distribution - (Mint 18.3)
 * Graphics hardware (Nvidia), driver (nvidia-340)
 * 64 bit
 ```

**Issue**

I've been using a Nvidia card with the recommended driver, nvidia-340.

It worked smoothly until a recent update, after which applications constantly freeze the desktop and sometimes crash it.

Both `lsmod` and `glxinfo` show that the "nouveau" driver has been used, although the "Driver Manager" still displays "nvidia-340" as the current driver.

```
lsmod | grep nouveau

nouveau                1650688  3
mxm_wmi              16384  1 nouveau
wmi                        24576  2 mxm_wmi,nouveau
i2c_algo_bit           16384  2 nouveau,i915
ttm                         94208  1 nouveau
drm_kms_helper   167936  2 nouveau,i915
drm                        360448  8 nouveau,i915,ttm,drm_kms_helper
video                      40960  2 nouveau,i915

```

```
glxinfo | grep OpenGL

OpenGL vendor string: nouveau
OpenGL renderer string: NVA8
OpenGL core profile version string: 3.3 (Core Profile) Mesa 17.2.8
OpenGL core profile shading language version string: 3.30
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.0 Mesa 17.2.8
OpenGL shading language version string: 1.30
OpenGL context flags: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.0 Mesa 17.2.8
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.00
OpenGL ES profile extensions:

```

![bug](https://user-images.githubusercontent.com/30547385/40776348-1af3c486-64fd-11e8-8eb0-f6d6c1b2a1ee.png)

As the screenshot shows, the Driver Manager still shows "nvidia-340" as the current driver, although it isn't.

I have tried to re-select "nvidia-340", but the problem persists.

Could someone kindly shed some light on it? Thanks.

**Comment by leigh123linux** [comment]
Maybe 340.104 is failing to build the kernel module.
