### ISSUE TITLE
Cinnamon crash after writing in the launch menu in Hebrew

### ISSUE THREAD

**Issue by Motherboard** [linuxmint/Cinnamon#7613]
```
 * Cinnamon version Cinnamon 3.6.7
 * Distribution - Ubuntu 17.10
 * Graphics hardware *and* driver used - NVIDIA 1080ti with driver 390.59-0ubuntu0~gpu17
 * 64 bit
 ```

**Issue**

Cinnamon crashed when typing in the launch menu in hebrew:
Wrote 2 letters, seen the mistake, tried to delete the letters, but Cinnamon froze. After a while it switched to failsafe mode and asked to restart it. 
It also said it didn't have enough memory to create a bug report, but there were 3GB of RAM available (out of 16BG) and 10GB of swap, so I don't see why it had a problem creating the report.

**Steps to reproduce**
Open the launch menu, while in Hebrew keyboard layout
type צו (mu on english keyboards), then backspace.

**Expected behaviour**
Not crash

**Comment by icarter09** [comment]
Cinnamon 3.6.7
Linux Mint 18.3 64bit

Attempted to duplicate this issue, but had no luck. Performed the steps indicated and Cinnamon did not crash. Typed several lines in Hebrew keyboard layout and Cinnamon did not crash.

**Comment by Motherboard** [comment]
Hmm... Tried it myself again, and it didn't crash for me either now... I guess you can close it as non reproducible. Hopefully next time it crashes it'd be able to create a bug report so we'd have more data to work with to determine the cause of this.
