### ISSUE TITLE
Sometimes when I click on a opened program on my panel, it just closes without any notice

### ISSUE THREAD

**Issue by codefactry** [linuxmint/cinnamon#7616]
```
 * Cinnamon version (3.6.7)
 * Distribution - (Mint 18.3 64 bit)
 * I'm not using any external graphics card. It is a core i5 (1st generation) processor desktop 
 * 64 bit
 ```

**Issue**
**The issues is very disgusting. First see the attached image**
 
![untitled-1](https://user-images.githubusercontent.com/25224876/40889860-788fc7fe-678f-11e8-866a-9bc2a907a2fe.jpg)

It is just a screen shot of my taskbar/panel. Here you can see that I have opened several programs and directories on my PC. The issue is very strange. Suppose I am working on "Sublime Text"  and then after few minutes I click on "Firefox" or "Netbeans" on my taskbar/panel to work on them, but as soon as I click on it the program just closes without any notice. Then I've to re-open   "Firefox" or "Netbeans" and sometimes I just loss any changes that I've made there. 

It doesn't happen all the time but randomly. 

Point to be noted, this do not happen with "Firefox" or "Netbeans" only but with any programs. At first I thought it was a bug from Firefox. Then I discovered it happens with not only Firefox but with chrome, sublimetext or any other programs. 

I am very much annoyed by this behavior. 

**Other information**

I've come around a solve of this bug though it is just temporary not a real solution. 

![untitled-3](https://user-images.githubusercontent.com/25224876/40889972-f5dc93f8-6790-11e8-8e09-88a7d6cc1a3e.jpg)

From the panel settings if I increase the panel height from it's default height to a little more then the bug never arises. 

I think Mint team must fix this bug. Thanks you

**Comment by mtwebster** [comment]
To be honest, it sounds like you're maybe inadvertently middle-clicking on a window list item, which by default closes the program.  If you right-click, preferences->configure, you can disable this, perhaps that will solve your issue.  Are you on a laptop? Maybe you need to adjust button/touchpad settings?

Does anything show up in your `~/.xsession-errors` file when this sort of thing happens?

What cinnamon theme are you using?

**Comment by codefactry** [comment]
@mtwebste I also suspect that then can you tell me how shall I disable the middle mouse button's functionality?

**Comment by mtwebster** [comment]
As I said above, right-click the window list, Preferences->configure, uncheck "Middle click to close window"

**Comment by codefactry** [comment]
@mtwebster Thanks ... It has solved my problem

**Comment by Vahan86** [comment]
@icarter09, can we close this issue?
