### ISSUE TITLE
SDL apps changes monitor configuration

### ISSUE THREAD

**Issue by nico-onmap** [linuxmint/cinnamon#7618]
```
 * Cinnamon version 3.6.7
 * Distribution - Mint 18.3
 * Graphics hardware: intel core i5-4590 HD 4600 graphics
 * 64 bit
 ```

`inxi -G output:`

```
Graphics:  Card: Intel Xeon E3-1200 v3/4th Gen Core Processor Integrated Graphics Controller
           Display Server: X.Org 1.18.4 drivers: intel (unloaded: fbdev,vesa)
           Resolution: 1920x1080@60.00hz, 1920x1080@60.00hz
           GLX Renderer: Mesa DRI Intel Haswell Desktop GLX Version: 3.0 Mesa 17.2.8
```

**Issue**
I am running Linux Mint 18.3 with Cinamon on intel graphics (4th generation core i5-4590 with
Intel® HD Graphics 4600).

I have 2 full-HD monitors in extended mode, both at 1920 x 1080 resolution.

It's working perfectly until I start an SDL-based app, like scummvm, dosbox (both installed using apt-get install...). Whenever I switch one of these apps to fullscreen using alt+enter, it goes fullscreen, but the monitor configuration is changed to clone mode, without asking me anything.

When switching back to window mode, it stays in clone mode so I have to open the monitor preferences and set the mode to extended again.

**Steps to reproduce**
- you need two full-hd screens connected and the monitor config should be set to `extended` 
- Install dosbox: `sudo apt-get install dosbox`
- start the app
- press `alt+enter` to switch to fullscreen mode

The app switches to fullscreen but changes the monitor configuration to `clone`, so both monitors show the same display (dosbox in that case).

**Expected behaviour**
App should choose a monitor (the primary one ?) and only change the resolution of this monitor, and shouldn't alter the monitor configuration mode to `clone`.

Also, switching back to window mode (xwindow desktop) using `alt+enter` should get back to the previous state, ie: `extended` mode. It does not, it stays in `clone` mode.

**Other information**

**Comment by icarter09** [comment]
@nico-onmap are you still experiencing this issue?
