### ISSUE TITLE
terminology terminal emulator consistently segfaults when attempting to start a second tab

### ISSUE THREAD

**Issue by dstromberg** [linuxmint/Cinnamon#7620]
```
 * Cinnamon version (cinnamon --version)  3.4.6 and 3.8.3
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 18.2 and Mint 19 beta
 * Graphics hardware *and* driver used  RS780L [Radeon 3000]
 * 32 or 64 bit  64 bit in both cases
 ```

The subject line says most of it.
The version of terminology that comes with Mint 19 beta consistently segfaults when attempting to start a second tab. This happens whether I display to a virtualbox console (Mint 19 beta), or remote display tunneled over ssh to a Mint 18.2 system with physical frame buffer.

The error message looks like:
$ terminology
below cmd output started 2018 Wed Jun 06 11:47:06 AM PDT
ERR<3898>:ecore_system_upower modules/ecore/system/upower/ecore_system_upower.c:74 _on_low_battery_get_cb() Message error org.freedesktop.DBus.Error.InvalidArgs - No such property 'OnLowBattery'
Segmentation fault (core dumped)

**Steps to reproduce**
1) Start terminology from some other terminal emulator
2) Right click with mouse in terminology window
3) Select "New" option with left mouse button
4) Observe the segfault

**Expected behaviour**
Terminology should continue to run, but a second tab should be created.

**Other information**

**Comment by clefebvre** [comment]
This isn't related to Cinnamon.

https://bugs.launchpad.net/ubuntu/+source/terminology
