### ISSUE TITLE
Application switcher items are not properly selected

### ISSUE THREAD

**Issue by AvantR** [linuxmint/cinnamon#7623]
```
 * Cinnamon 3.8.3
 * Linux Mint 19 Tara 64 bit
 * Card: Intel HD Graphics 620
 * OpenGL: renderer: Mesa DRI Intel HD Graphics 620 (Kaby Lake GT2) version: 4.5 Mesa 18.0.0-rc5
 * Display Server: x11 (X.Org 1.19.6)
 ```

**Issue**
When you open app switcher (alt-tab) and the mouse pointer is already over that item, then this item is not selected.

**Steps to reproduce**
Open at least 3 windows, put the mouse pointer at the position of last item of application switcher, press alt-tab one time and hold tab to open app swithcer, click on the last item without moving your pointer. The item that gets focus is the second and not the last one.

**Expected behaviour**
The item that should get the focus should be the one that has the pointer already over it. 

**Other information**
For a better explanation see this video: https://www.youtube.com/watch?v=08SAV0iDEww

**Comment by icarter09** [comment]
@AvantR are you still experiencing this issue?

**Comment by AvantR** [comment]
> @AvantR are you still experiencing this issue?

Yes, it's still happening in Cinnamon 4.4.8 (mint 19.3)
