### ISSUE TITLE
It would be nice if it was adding defaulth!!!!

### ISSUE THREAD

**Issue by xzj8b3** [linuxmint/Cinnamon#7624]
[Extension Flipper](https://cinnamon-spices.linuxmint.com/extensions/view/36)

Not ' You can include it of defaulth?? It was one of the best extensions, it was handy cubic desktop that revolved!!!!

If it were possible it would be wonderful!!!

**Comment by clefebvre** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
