### ISSUE TITLE
Bluetooth audio device activation and deactivation

### ISSUE THREAD

**Issue by randomguy4567** [linuxmint/cinnamon#7626]
```
 * Cinnamon version (cinnamon --version)
    3.4.6
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
   Ubuntu 17.10
 * Graphics hardware *and* driver used
   Nvidia 1050 and driver 384.130
 * 32 or 64 bit
   64 bit
 ```
**Issue**
Sound does not switch correctly when activating and deactivating a bluetooth audio device.

**Steps to reproduce**
1) Using Blueman, pair with a bluetooth audio device. In this case I am pairing with a Bose headset.
2) Audio continues playing through main system speakers.
3) Select "Sound Settings" from the tray.
4) Observe that Bose headset is selected.
5) Click any other sound output device then click bose headset device, now output comes out of the Bose headset.
6) Turn the headset off, sound does not return to the previous audio device.

**Expected behaviour**
I expect once the headset is paired, if I turn it on it will start working, and if I turn it off, the sound will go back to the system speakers.

**Other information**

**Comment by icarter09** [comment]
@randomguy4567 are you still experiencing this issue? If so, have you tried using Blueberry instead?
