### ISSUE TITLE
Duplicate translation Timeshit

### ISSUE THREAD

**Issue by GabrielMGitHub** [linuxmint/Cinnamon#7631]
* Cinnamon version 3.8.4
 * Distribution - 19
 * Graphics hardware opensource
 * 64 bit

The application is with part of the wrong translation referring to pt_BR language. It has some parts of the language duplicated.

![captura de tela de 2018-06-09 09-28-43](https://user-images.githubusercontent.com/8754997/41191587-5d0e61c4-6bc8-11e8-8458-0e6a9064b7e3.png)
![captura de tela de 2018-06-09 09-28-58](https://user-images.githubusercontent.com/8754997/41191588-5d2f3f8e-6bc8-11e8-8820-a56a34c5ccc3.png)
![captura de tela de 2018-06-09 09-29-41](https://user-images.githubusercontent.com/8754997/41191589-5d4db784-6bc8-11e8-85df-a8a08a7e126e.png)

**Comment by NikoKrause** [comment]
This is upstream and need to be reported there: https://github.com/teejee2008/timeshift
