### ISSUE TITLE
Need to change the printer icon in the mint menu.

### ISSUE THREAD

**Issue by GabrielMGitHub** [linuxmint/Cinnamon#7632]
* Cinnamon version 3.8.4
 * Distribution - 19
 * Graphics hardware opensource
 * 64 bit
The printer icon is displayed correctly in the system settings, but in the menu the icon is different from the others.

![captura de tela de 2018-06-09 09-39-29](https://user-images.githubusercontent.com/8754997/41191687-b4051d64-6bc9-11e8-9433-a707179235fe.png)
![captura de tela de 2018-06-09 09-40-05](https://user-images.githubusercontent.com/8754997/41191688-b426a2b8-6bc9-11e8-87ca-552a1c3e23ec.png)

**Comment by NikoKrause** [comment]
The printer app in the menu is `system-config-printer` and it uses `Icon=printer`, which is a `devices` icon not an `apps` icon. This is upstream (https://github.com/zdohnal/system-config-printer/blob/master/system-config-printer.desktop.in) and can't be changed by Cinnamon itself.
 
If we change the devices icon in the Mint-Y icon theme to the apps icon version, the printer in the app itself, will look like the app icon in the second screenshot, which will look ugly/weird.

The cinnamon-settings in your second screenshot is using it's own icon `cs-printer`. It just calls the `system-config-printer` app, if you click on it. If you change the `cs-printer` icon to `printer`, then the cinnamon-settings won't look consistent.

**Comment by GabrielMGitHub** [comment]
@NikoKrause 
This way, in the application menu all the icons are the same in the format, this one and another one are different, they are removing the harmony. It looks like something badly made the way it is now.

**Comment by JosephMcc** [comment]
Thanks for the report but this isn't a Cinnamon issue. If this needs to be changed it's an icon theme problem.

**Comment by NikoKrause** [comment]
The only thing what you can do till then, is to change this icon on your own machine.
Open
```
sudo xed /usr/share/applications/system-config-printer.desktop 
```
and change the line
```
Icon=printer
```
to 
```
Icon=cs-printer
```

**Comment by GabrielMGitHub** [comment]
> The only thing what you can do till then, is to change this icon on your own machine.
Open
sudo
xed /usr/share/applications/system-config-printer.desktop 
and change the line
Icon=printer
to
Icon=cs-printer

This does not work as mentioned!

If it is possible by the correct icon in the settings panel, why can not it be placed in the menu mint since it is only an icon shortcut?

![captura de tela de 2018-06-10 15-16-37](https://user-images.githubusercontent.com/8754997/41204934-927abf02-6cc1-11e8-8b53-4aa31af13ef4.png)

Honestly Clem is much more malleable with these issues, if it continues like this I give up wasting my time to help.

**Comment by GabrielMGitHub** [comment]
@NikoKrause 
@clefebvre 

If you only change the icon in the shortcut menu mint, it will not change within the application, and if you make a shortcut through the menu linux mint will assume the same icon.

![captura de tela de 2018-06-10 15-29-13](https://user-images.githubusercontent.com/8754997/41205078-640c5714-6cc3-11e8-9b6a-cab78131883f.png)
![captura de tela de 2018-06-10 15-29-21](https://user-images.githubusercontent.com/8754997/41205079-642d9f0a-6cc3-11e8-87d4-eec1e68a705a.png)
![captura de tela de 2018-06-10 15-30-04](https://user-images.githubusercontent.com/8754997/41205080-644ea9f2-6cc3-11e8-90ba-307c17186c2f.png)
![captura de tela de 2018-06-10 15-30-13](https://user-images.githubusercontent.com/8754997/41205081-646dfe88-6cc3-11e8-9b1c-0f0c9f78743c.png)

This is the easiest solution linux mint should do.

**Comment by NikoKrause** [comment]
Thanks for the suggestion. Please create a Pull Request, so this can be merged and applied to Mint. Thank you.

**Comment by GabrielMGitHub** [comment]
@NikoKrause 

I would love to, but today burned my motherboard, if you could make the pull request, I would be very grateful.

Thank you.

**Comment by NikoKrause** [comment]
I can't because I don't know how to.
