### ISSUE TITLE
Need to change the Virtual Keyboard icon in the mint menu

### ISSUE THREAD

**Issue by GabrielMGitHub** [linuxmint/cinnamon#7633]
* Cinnamon version 3.8.4
 * Distribution - 19
 * Graphics hardware opensource
 * 64 bit

The Virtual Keyboard icon is different from the others.
It needs to be changed to be more cohesive.

![captura de tela de 2018-06-09 09-46-26](https://user-images.githubusercontent.com/8754997/41191761-6b21f8b4-6bca-11e8-99d4-ae385ca15d71.png)

**Comment by icarter09** [comment]
Cinnamon 3.8.7
Linux Mint 19 64bit
AMD Radeon 6520G

Verified that the "Virtual Keyboard" icon is still being set to the default icon.

**Comment by Vahan86** [comment]
The issue still exists in Cinnamon 4.4.
