### ISSUE TITLE
You can put more compact and smaller themes on the menu???

### ISSUE THREAD

**Issue by xzj8b3** [linuxmint/Cinnamon#7634]
It would be very nice to have the possibility to enable more compact themes, maybe a little ' transparency but with smaller menu sizes for small screens

[IMG]http://i67.tinypic.com/123xobd.jpg[/IMG]

On smaller monitors the menu looks giant and personally on any monitor I have always preferred a more compact and less voluminous style.... But I see were removed those few themes I used to have smaller dimensions and eleganti...se was possible ahhiungere something would be much appreciated!!!!!

**Comment by JosephMcc** [comment]
This isn't really a Cinnamon issue. Contact theme devs for this sort of thing.

**Comment by xzj8b3** [comment]
In fact it is not a problem but a suggestion ... Smaller themes have been removed ... But I think what would make happy many other users!
