### ISSUE TITLE
The User and Groups authentication window in the title part is without translation to pt_BR

### ISSUE THREAD

**Issue by GabrielMGitHub** [linuxmint/Cinnamon#7635]
Cinnamon version 3.8.4
 * Distribution - 19
 * Graphics hardware opensource
 * 64 bit

The User and Groups authentication window in the title part is without translation to pt_BR.

![captura de tela de 2018-06-09 19-52-41](https://user-images.githubusercontent.com/8754997/41196894-43d26c1e-6c22-11e8-9cfe-cecfaa8365fb.png)

**Comment by GabrielMGitHub** [comment]
@NikoKrause 
@clefebvre

Regarding question #7691 , it is not duplicated, as it has nothing to do with synaptics. If you refer to the "Users and Groups" authentication window located in the "org.cinnamon.settings-users" settings panel, the title is not translated.
![captura de tela de 2018-07-22 04-34-46](https://user-images.githubusercontent.com/8754997/43043362-aa0a304a-8d68-11e8-950a-8cb80b2da693.png)

If you had a little more attention and less criticism the project was going.

**Comment by JosephMcc** [comment]
Stop with the digs and insults. It's not going to be tolerated. If there is a bug we'd like to see it get fixed. But if you keep insulting people the issue will be locked.

**Comment by NikoKrause** [comment]
Fixed https://github.com/linuxmint/Cinnamon/pull/7763
