### ISSUE TITLE
Cinnamon ANIMATION_TIME Warning

### ISSUE THREAD

**Issue by rebelwocause** [linuxmint/cinnamon#7638]
```
 * Cinnamon 3.8.4
 * Distribution - Mint 19 Tara beta
 * 64 bit
 ```

**Issue**
.xsession-errors logged

(cinnamon:1173): Cjs-WARNING **: 12:20:06.286: Some code accessed the property 'ANIMATION_TIME' on the module 'overview'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.

(cinnamon:1173): Cjs-WARNING **: 12:20:23.967: Some code accessed the property 'ANIMATION_TIME' on the module 'appSwitcher3D'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.

**Steps to reproduce**
Happens using one of Coverflow app switcher, Expo or Scale views (not sure which one)

Cause seems to be in /usr/share/cinnamon/js/ui/overview.js 

// Time for initial animation going into Overview mode
const ANIMATION_TIME = 0.25;

**Expected behaviour**
No Warnings

**Comment by germanfr** [comment]
This can be closed, it's already fixed in the latest version.
