### ISSUE TITLE
Selectable Label background color with Mint-X-xxx Themes

### ISSUE THREAD

**Issue by rebelwocause** [linuxmint/Cinnamon#7640]
```
 * Cinnamon 3.8.4
 * Distribution - Mint 19 Tara beta
 * 64 bit
 ```

**Issue**
When using a Mint-X-??? Theme when selecting text in selectable labels the background color does not allow text to be seen

**Steps to reproduce**
Open Files/Nemo and open it's Help/About Dialog, then select text in one of the
labels - can not read as css background color not correct??
Mint-Y Theme appears to be ok.

**Other information**
Only seems to be gtk3 Mint-X- themes
can fix by adding css to ~/.config/gtk-3.0/gtk.css

label:selected,
label selection {
    background-color: @theme_selected_bg_color;
}

**Comment by JosephMcc** [comment]
Thanks. I'll look into that but it doesn't belong here. It isn't a Cinnamon issue and bug reports against the beta should be reported on the beta blog post.
