### ISSUE TITLE
change gtk3 sort-directories-first to true to match default nemo setting

### ISSUE THREAD

**Issue by jstnlth** [linuxmint/Cinnamon#7642]
```
 * Cinnamon version (cinnamon --version) Cinnamon 3.8.3
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 19
 * 64 bit
 ```
**Issue**
GTK3 apps (like thunderbird and LibreOffice) use the nautilus libraries to access files. While this necessarily will look different from nemo, at least we can start off with the same sorting by setting the gtk3 default to match the nemo default of sorting folders before files.
This issue was mentioned a number of times in the comments of Tara beta.

**Steps to reproduce**
Do a file - open from LibreOffice and notice that files and folders are mixed together.  The same folder opened in Nemo is sorted differently.

**Expected behaviour**
GTK3 apps should sort the same way as nemo sorts.  While keeping this setting in sync might be problematic, a simple .gschema.override could set the defaults to be nice.

**Other information**
Potential fix: (not sure what the best place to put this is.  Probably only useful for the Mint distribution, and not just cinnamon in general.) Cinnamon/debian/cinnamon.gsettings-override /usr/share/glib-2.0/schema/10_cinnamon.gschema.override
[org.gtk.Settings.FileChooser]
sort-directories-first = true

**Comment by JosephMcc** [comment]
This might not be a bad idea but we usually leave this sort of thing up to distros to do and not something we would do with Cinnamon directly.

**Comment by clefebvre** [comment]
We'll get this fixed in Mint itself.

**Comment by leigh123linux** [comment]
@clem You could make it default
