### ISSUE TITLE
Linuxmint 19 Beta installation issue ~ USB Installation ~ Unable to install with Encryption

### ISSUE THREAD

**Issue by Bara-Bus** [linuxmint/Cinnamon#7643]
```
 * Cinnamon version (cinnamon --version)
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
 * Graphics hardware *and* driver used
 * 32 or 64 bit
 ```

**Issue**
USB Installation ~ Unable to install with Encryption
Was unable to install on any USB stick using Encryption. Stalls during installation when using no encryption.

**Steps to reproduce**
Just tey to install on a USB. 

**Expected behaviour**
~~~~~~~


**Other information**
~~~~~~~

**Comment by JosephMcc** [comment]
This should be reported on the Mint blog for the beta release.
