### ISSUE TITLE
Nvidia X server settings 

### ISSUE THREAD

**Issue by andrej66659** [linuxmint/cinnamon#7645]
```
 * Cinnamon version 3.8.4
 * Distribution - Mint 19 Tara
 * GTX 1070 and driver used
 * 64 bit
 ```

**Issue**
Nvidia X server settings are reverting to default after a restart..

**Steps to reproduce**
Well i have 2 monitors and when i set which one to be my main screen and then when i restart it aint my main anymore so i have to set it again.

**Expected behaviour**
To save its settings

**Other information**
/

**Comment by redjaguar** [comment]
I had this trouble initially with Mint 18 and Cinnamon 3.6.7 and fixed it by running nvidia-settings as root and making sure the xorg.conf file was saved to /etc/X11/xorg.conf

**Comment by Vahan86** [comment]
@andrej66659, is this still an issue in Cinnamon 4.2?

**Comment by leigh123linux** [comment]
This was never a bug/issue
Don't use cinnamon-settings display to set anything when using nvidia as it overrides  /etc/X11/xorg.conf  , to fix delete ~/.config/monitors.xml
