### ISSUE TITLE
Windows not centered correctly

### ISSUE THREAD

**Issue by joaojotta** [linuxmint/Cinnamon#7647]
```
 * Cinnamon 3.8.4-1
 * Antergos
 * Intel graphics
 * 64 bit
 ```

**So, ~~the sound notifications, caps lock notification, num lock notification and so on are not appearing centered.
Also, some other~~ application windows do not get centered (like Firefox). Others do (like dconf editor).**

**For the Firefox window (and others) I'm using the Cinnamon shortcut "Windows>Positioning>Center window in screen". The sound thing is... well... you know how. (;**

Here's a screenshot with a grid wallpaper great to see the difference from left to right ~~(and the Plank dock is also good to see the sound notification)~~.

![screenshot from 2018-06-13 16-00-12](https://user-images.githubusercontent.com/11931285/41360182-04972774-6f24-11e8-846a-a8f0e32e5470.png)

Is there a fix for this?

Thanks you and sorry if this is duplicated. I did search but only found one from 2016.

**Comment by germanfr** [comment]
The notification is off-centered because of the theme (Arc) uses margins on it and shifts it to the right and to the bottom. That can be solved using another theme. These are actually two different issues.

**Comment by joaojotta** [comment]
Oh, cool. Haven't really noticed it since I always use Arc.
So it appears to be a theme-related issue. Not necessarily Arc as other themes react the same way.

Let's make this a "Window miss-alignment" then. (;

**Comment by JosephMcc** [comment]
Thanks for the report but we already have an open issue for this: https://github.com/linuxmint/Cinnamon/issues/5115

**Comment by joaojotta** [comment]
Exactly the one I saw... from 2016. Thought it was a different thing.
Thanks. (;
