### ISSUE TITLE
ui invisible elements

### ISSUE THREAD

**Issue by itsrave** [linuxmint/Cinnamon#7648]
```
 * Cinnamon version (cinnamon 3.4)
 * Distribution - Mint 17
 * Graphics hardware *and* driver used i cant check
 * 32 or 64 bit - 64
 ```

**Issue**

as in title
![image](https://user-images.githubusercontent.com/28827494/41382511-bb2ec3d2-6f6c-11e8-9d4b-7ffbd4412100.png)

**Comment by leigh123linux** [comment]
Cinnamon-3.4 is EOL, if you can reproduce with a supported version feel free to reopen.
