### ISSUE TITLE
Package Installer Does Not Prompt For Google Verification Code

### ISSUE THREAD

**Issue by calin-ciobanu** [linuxmint/Cinnamon#7649]
```
Cinnamon 3.6.7
Mint 18.3 Cinnamon
64 bits
 ```

**Package Installer Does Not  Prompt For Verification Code**

Enable google 2FA via pam (libpam-google-authenticator). Works on login, running commands with sudo, other applications requiring super user permissions (i.e. gparted) but when opening a deb file the Package Installer only prompts for Password (and skips the Verification Code). After entering the password the window closes and installation stops.

**Steps To Reproduce**:
- setup Google 2FA like described here https://askubuntu.com/questions/609117/how-to-setup-two-factor-authentication-in-ubuntu-for-ubuntu-users-using-google-a
- restart computer
- try to install a deb package by double clicking the file

NOTE: running `sudo dpkg -i file.deb` works as expected and verification code is required in the terminal.

**Expected Behaviour**:
- before prompting for password the verification code should be required

**Comment by clefebvre** [comment]
This should be against gdebi. Is this feature supported by Ubuntu's version of gdebi?? I don't think it's present in ours.
