### ISSUE TITLE
Sound-volume effect is not emitted when volume is greater than 100%

### ISSUE THREAD

**Issue by claudiux** [linuxmint/cinnamon#7650]
```
 * Cinnamon version 3.8.4
 * Distribution Mint 19 beta
 ```

**Issue**
Sound-volume effect is not emitted when volume is greater than 100%.
An error message appears in the .xsession-errors file whenever the volume slider crosses the 100% threshold:
```
(cinnamon:1848): St-CRITICAL **: 15:21:05.130: st_theme_context_get_for_stage: assertion 'CLUTTER_IS_STAGE (stage)' failed
Cinnamon warning: Log level 8: g_object_get: assertion 'G_IS_OBJECT (object)' failed
```

**Steps to reproduce**
Activate the volume sound effect in `cinnamon-settings sound`; verify that the "Effects volume" is not "muted".
Then, in a terminal: `tail -f ~/.xsession-errors`
Finally, modify the volume level by the sound applet.

**Expected behaviour**
That the volume effect is output regardless of the volume level.

**Other information**
In `/usr/share/cinnamon/js/ui/soundManager.js`, line 124:
`this.proxy.PlaySoundFileVolumeRemote(id, filename, volume + "");`
PlaySoundFileVolumeRemote doesn't seem to be present in this.proxy (same file, lines 8-31).

**Comment by mtwebster** [comment]
I can't seem to reproduce this - I get the sound effects regardless of my amplification level.

The proxy is fine - in our javascript bindings, `Remote` is appended to the name defined in the xml section to identify it as an asynchronous call vs synchronous (where `Sync` would be appended instead.)

Those warnings don't look directly related to sound either, if they're spamming when you attempt to adjust volume, it tells me more that there's some ui call failing which might be prevent the code from reaching the sound part..

Is this the stock sound applet you're using?  Or a 3rd party one?  What cinnamon theme are you using?  Does this happen with the stock Cinnamon or Linux Mint theme?

**Comment by claudiux** [comment]
I am using a fresh install of Linux Mint 19 beta in VirtualBox. The theme is LinuxMint (default). The maximum volume is set to 150%.
This is a random bug. If I restart Cinnamon, or if I change my theme (even if I use LinuxMint again) these warning messages disappear.

**Comment by DuMuT6p** [comment]
I confirm that this bug is still present. No sound effect when chaning volume above 100%. However I am not getting the errors in ~/.xsession-errors.

System information:
```
Cinnamon 3.8.9
Linux Mint 19 Tara
Freshly installed when 19 came out
With all updates as of today
```

**Comment by claudiux** [comment]
This bug is still present.
```
System info:    
Kernel: 4.18.0-13-generic x86_64 bits: 64 
Desktop: Cinnamon 4.0.8
wm: muffin
dm: LightDM 
Distro: Linux Mint 19.1 Tessa 
           base: Ubuntu 18.04 bionic
```

**Comment by claudiux** [comment]
This bug is still present in Linux Mint 19.2 Cinnamon 4.2.4.

**Comment by claudiux** [comment]
This bug is still present in Linux Mint 19.3 Cinnamon 4.4.5.

**Comment by mtwebster** [comment]
Still can't reproduce.

**Comment by JosephMcc** [comment]
Neither can I. It seems to work just fine here.

**Comment by claudiux** [comment]
Steps to reproduce (Mint 19.3 Cinnamon 4.4.5):

1. Open System Settings -> Sound -> Settings tab.
2. Set the maximum volume up to 120%.
3. Roll the mouse wheel on the icon of the Sound applet. The sound of the effect is audible up to 100% and becomes inaudible beyond 100%.

**Comment by smurphos** [comment]
I can't reproduce following those steps...

**Comment by claudiux** [comment]
(I don't know if that will help.) `sudo lshw -c sound` returns:

```
  *-multimedia:0            
       description: Audio device
       produit: Xeon E3-1200 v3/4th Gen Core Processor HD Audio Controller
       fabriquant: Intel Corporation
       identifiant matériel: 3
       information bus: pci@0000:00:03.0
       version: 06
       bits: 64 bits
       horloge: 33MHz
       fonctionnalités: pm msi pciexpress bus_master cap_list
       configuration: driver=snd_hda_intel latency=0
       ressources: irq:34 mémoire:f7d14000-f7d17fff
  *-multimedia:1
       description: Audio device
       produit: 8 Series/C220 Series Chipset High Definition Audio Controller
       fabriquant: Intel Corporation
       identifiant matériel: 1b
       information bus: pci@0000:00:1b.0
       version: 05
       bits: 64 bits
       horloge: 33MHz
       fonctionnalités: pm msi pciexpress bus_master cap_list
       configuration: driver=snd_hda_intel latency=0
       ressources: irq:33 mémoire:f7d10000-f7d13fff
```

**Comment by claudiux** [comment]
This problem is no longer present in Cinnamon 5.6.7.
