### ISSUE TITLE
Broken system tray icons

### ISSUE THREAD

**Issue by JackJohansson** [linuxmint/Cinnamon#7651]
```
 * Cinnamon version (cinnamon 3.8.3)
 * Distribution - (Mint 19)
 * 64 bit
 ```

**Issue**

I've installed multiple programs that have a system tray icon, and there's a problem with skype's icon in the system tray. Here's how the icon appears in the system tray:

https://imgur.com/JkLVT8c

I'm not very familiar with UI development, so I'm not sure if this problem is caused by skype or by linux mint. I've posted both on here and skype suport forums. If this is not caused by linux mint, please close this issue.

**Other information**

I've installed the skype from the software center.

**Comment by JosephMcc** [comment]
I don't use skype personally but a fix was done for the systray icon: https://github.com/linuxmint/Cinnamon/commit/1e933d3c3e7a405bdd3e0295284db8a55332e6ae

You need to include your cinnamon version in the issue template.

**Comment by JackJohansson** [comment]
@jeffkowalski Thank you, That was fast.

I've included the version. Will this patch be available through incoming updates?

**Comment by claudiux** [comment]
Hi @JackJohansson. 
Have you updated your packages ? The latest version of Cinnamon is 3.8.4, in which this fix is present.

**Comment by gitman0** [comment]
this fixed it for me on fedora 28, thanks!

it was not just a cinnamon problem. hopefully it doesn't regress when they fix it upstream.

reference:

https://answers.microsoft.com/en-us/skype/forum/skype_linux-skype_startms-skype_installms/system-tray-icon-in-xfce/d3f162bf-0bbf-481b-90a1-f43cae9a86cc

https://github.com/electron/electron/issues/12791

**Comment by JackJohansson** [comment]
@claudiux That fixed the issue. Thank you.
