### ISSUE TITLE
Cinnamon Window Focus Issue

### ISSUE THREAD

**Issue by Hordeking** [linuxmint/Cinnamon#7653]
```
 * Cinnamon version (3.6.7)
 * Distribution - (Mint 18.2 and 18.3)
 * 64 bit
 ```

**Issue**
Cinnamon seems to be having focus issues when logitech mouse is disconnected/turned off, then reconnected/turned back on.

Various issues, which I'm unable to specifically nail down, include being able to click the task bar to switch programs, but not click the programs windows when they're visible, not being able to change focus to elements in a program window that appears to be focused, unable to click drop menus from top, right clicks don't do anything, and I can't enter/select text in text boxes. I know the keyboard works because I can alt-tab between programs, and I can ctrl-alt-esc to possible restart cinnamon. Restarting the display manager service usually seems to help, but not in all cases.

These issues seem to be related, though independently appearing. So sometimes some of these issues appear and not others. The problems only started in the past two days (June 14 was when I first noticed them)

**Steps to reproduce**
Unplug logitech mouse dongle from usb. Reconnect it. Unfortunately, I have no other mice to test with.

**Expected behaviour**
Mouse should be able to click elements and change window focus.

**Other information**
 * Issue appears on Multiple machines.
 * Seems to stem from recent updates, but I'm unable to roll them back to confirm this.

**Comment by leigh123linux** [comment]
It was probably broken by a kernel update. this isn't something we can fix within the cinnamon code.

**Comment by Hordeking** [comment]
Looks like it's happening on different kernels, too. 4.4.0 and 4.13....

**Comment by leigh123linux** [comment]
In that case some other ubuntu base package has broken it, look in /var/log/dpkg.log for clues.

**Comment by Hordeking** [comment]
Seems to be present on Mint 19 Beta. I've gotten it down to a few things. I'm using a Logitech receiver. Paired to this same receiver are one M570 and one M325 mouse. If I'm using the M325, I don't see any issues. As soon as I turn on the 570, the problem manifests. When I then turn off the 325, the problem sticks (so it doesn't appear to be related to two mice being on at once). When I turn off the 570, the problem magically seems to go away.

When it's in this "focus stuck" mode, for instance, when my web browser is partially hidden by a nemo  window, a click on a neutral area of nemo, which would normally be directed to nemo and not do anything appears to be falling through to the browser window and clicking the elements in it, as if the browser has focus.

**Comment by Hordeking** [comment]
I intend to pick up another 570 today and see if the issue is the mouse itself. But the fact that we know that X is getting clicks from it leads me to think maybe it's an X problem.
