### ISSUE TITLE
"Display" settings module gnome_rr_config_load_current() assertion failure

### ISSUE THREAD

**Issue by bjorn-helgaas** [linuxmint/Cinnamon#7657]
```
 * Cinnamon 3.6.7
 * Ubuntu 18.04
 * Intel [8086:591b], Nvidia Quadro M1200 Mobile [10de:13b6]
 * 64 bit
 ```

**Issue**
The "System Settings" GUI Display module crashes.  Running by hand I saw this assertion failure:
```
$ /usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py
<select "Display" module>
**
CinnamonDesktop:ERROR:gnome-rr-config.c:666:gnome_rr_config_load_current: assertion failed: (gnome_rr_config_match (config, config))
Aborted (core dumped)
```
**Steps to reproduce**
This worked correctly with Ubuntu 18.04 and Cinnamon 3.6.7 installed out of the box, but it got broken as I switched between Cinnamon and the default Ubuntu desktop and between nouveau and the nvidia drivers.

I think what happened was that:

- The default 18.04 install used the nouveau driver.
- I installed the nvidia driver.  This adds /etc/modprobe.d/nvidia-graphics-drivers.conf, which blacklists nouveau.
- I removed the nvidia driver (but didn't *purge* it).  This leaves /etc/modprobe.d/nvidia-graphics-drivers.conf, so nouveau is still blacklisted.

That left me with neither nouveau nor the nvidia driver loaded, and this is when the Display settings stopped working.  Purging the nvidia driver removed /etc/modprobe.d/nvidia-graphics-drivers.conf, and then (after a reboot), the Display settings worked again.

**Expected behaviour**

The Display settings probably should not crash, even if neither video driver is loaded.

**Other information**
```
$ sudo apt install nvidia-driver-390
$ sudo apt remove nvidia-driver-390
$ sudo apt purge nvidia-driver-390
```

**Comment by leigh123linux** [comment]
Invalid, don't expect stuff to work with broken X.
