### ISSUE TITLE
cinnamon crshed

### ISSUE THREAD

**Issue by abdallahegy** [linuxmint/Cinnamon#7658]
```
 * Cinnamon version (cinnamon 3.6.7)
 * Distribution - (Mint 18.3)
 * Graphics hardware *amd radeon r4 * driver used
 * 64 bit
 ```

**when i set this command in terminal (sudo service network-manager restart)
the cinnamon crshed and report this messages  (Cinnamon just crashed. You are currently running in Fallback Mode.)**

how can this problem solved

**Comment by leigh123linux** [comment]
This is a duplicate report, I can't be bothered to search for the other issue as time is limited.
Also cinnamon-3.6.x is EOL.
