### ISSUE TITLE
Wrong date format in Calendar applet

### ISSUE THREAD

**Issue by sanjibukai** [linuxmint/Cinnamon#7659]
```
 * Cinnamon version 3.8.4
 * Distribution - Manjaro 4.16.14-2
 * 64 bit
 ```

**Issue**
Date format in the Cinnamon Calendar Applet use non coherent locales.
The month name stay in english.

**Steps to reproduce**
Set the date locale to (for example) french.
Use the following date format: `%A %e %B`

**Expected behaviour**
According to that format, the date should be displayed as following:
`mardi 19 juin` ( _mardi_ being tuesday and _juin_ being June)

Instead I got:
`mardi 19 June` where June is in english.

**Other information**
The system local is correctly defined as confirmed with the output of `date -u` which displays the date whole in french.

**Comment by NikoKrause** [comment]
Can't reproduce here on Mint19. It translates just fine.

**Comment by leigh123linux** [comment]
Post
```
locale
```

**Comment by sanjibukai** [comment]
I'm sorry but in the meantime I just changed the DE.
I cannot provide further information, but I had check some basic settings and didn't see anything wrong in the basics..
So, never mind, I hope it was something wrong in my side...
_Closing.._
