### ISSUE TITLE
Hibernation does not work Linux Mint 19 Beta.

### ISSUE THREAD

**Issue by Gandalf888** [linuxmint/Cinnamon#7660]
```
 * Cinnamon version (cinnamon --version)

CInnamon 3.8.4

 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)

No LSB modules are available.
Distributor ID:	LinuxMint
Description:	Linux Mint 19 Tara
Release:	19
Codename:	tara

 * Graphics hardware *and* driver used
Nvidia GeForce G210M

 * 32 or 64 bit

64 bit
 ```

**Issue**
System hibernation does not work. After hibernation is selected, the system behaves as if it was hibernating, but after starting the computer, there are no applications that were open before hibernation, there is also no message that the system is recovering from hibernate.

**Steps to reproduce**
* Installing Linux Mint
* Create 10 GB swap partition
* Hibernate computer
* Run computer

**Expected behaviour**
The system should be hibernated and after running the hibernate applications should run.

**Other information**
Hibernation has been tested on Ubuntu, Kubuntu, Lubuntu and Ubuntu Mate systems - it always worked. Kernel was not changed, the system worked with the kernel delivered from the repo, there were no problems with hibernation. The problem is under Linux Mint, which is based on Ubuntu. I have 4 GB RAM, the swap partition has 10 GB capacity. Under the Linux Mint 18.3 system there were no problems with hibernation.

**Comment by Gandalf888** [comment]
Additionally, after hibernation, the uptime command shows 0 minute, which means that the system is turned off, not hibernated

```text
 18:59:24 up 0 min,  1 user,  load average: 1,61, 0,43, 0,15

```

**Comment by Lavoista** [comment]
hi @howdev can you please guide us, which commands do we need to type?

**Comment by howdev** [comment]
put this file com.ubuntu.enable-hibernate.pkla in /etc/polkit-1/localauthority/50-local.d

[Re-enable hibernate by default]
Identity=unix-user:*
Action=org.freedesktop.upower.hibernate
ResultActive=yes

[Re-enable hibernate by default in logind]
Identity=unix-user:*
Action=org.freedesktop.login1.hibernate
ResultActive=yes

After you put this file, hibernate will be available in the GUI shutdown and in the Power settings where you can assign power button to it.

I don't know why this step is needed. it was working before without adding resume. but it doesn't resume from hibernate without this step. 
edit  /etc/default/grub 
GRUB_CMDLINE_LINUX=resume=UUID=put your swap partition uuid here
You can find the UUID in /etc/fstab

**Comment by Lavoista** [comment]
@howdev 
thanks! it works with a slight mod inside grub file (taken from [askubuntu](https://askubuntu.com/questions/196364/i-have-enabled-hibernate-but-it-isnt-working-what-can-i-do)), inside grub contents:
GRUB_DEFAULT=0
GRUB_HIDDEN_TIMEOUT=0
GRUB_HIDDEN_TIMEOUT_QUIET=true
GRUB_TIMEOUT=10
GRUB_DISTRIBUTOR=`lsb_release -i -s 2> /dev/null || echo Debian`
GRUB_CMDLINE_LINUX_DEFAULT="quiet splash resume=UUID=297a4bea-1cf7-4f15-b857-aa24abb64032"
GRUB_CMDLINE_LINUX=""

after this i executed: sudo update-grub
then login into desktop cinnamon, opened some programs, clicked the hibernate button, after power down, turn on again the machine, logged in back and the programs were in the state where i left them, so it works!!, thanks!!

**Comment by howdev** [comment]
@Lavoista I am glad can help you. it should work the same GRUB_CMDLINE_LINUX_DEFAULT or GRUB_CMDLINE_LINUX

**Comment by leigh123linux** [comment]
Issue moved to [linuxmint/linuxmint #36](https://github.com/linuxmint/linuxmint/issues/36) via [**ZenHub**](https://www.zenhub.com/)
