### ISSUE TITLE
Some BIOS settings are ignored or unstable with kernel 4.15 and greater

### ISSUE THREAD

**Issue by noreasternhumidity** [linuxmint/Cinnamon#7661]
```
 * Cinnamon version (cinnamon --version)
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
 * Graphics hardware *and* driver used
 * 32 or 64 bit

~ $ inxi -Fxz
System:    Host: travel Kernel: 4.15.0-23-generic x86_64 (64 bit gcc: 5.4.0)
           Desktop: Cinnamon 3.6.7 (Gtk 3.18.9-1ubuntu3.3)
           Distro: Linux Mint 18.3 Sylvia
Machine:   System: Dell (portable) product: Latitude E6420 v: 01
           Mobo: Dell model: 0X8R3Y Bios: Dell v: A24 date: 05/12/2017
CPU:       Dual core Intel Core i7-2640M (-HT-MCP-) cache: 4096 KB
           flags: (lm nx sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx) bmips: 11174
           clock speeds: max: 3500 MHz 1: 1824 MHz 2: 1298 MHz 3: 830 MHz
           4: 947 MHz
Graphics:  Card: Intel 2nd Generation Core Processor Family Integrated Graphics Controller
           bus-ID: 00:02.0
           Display Server: X.Org 1.18.4 drivers: intel (unloaded: fbdev,vesa)
           Resolution: 1600x900@60.00hz
           GLX Renderer: Mesa DRI Intel Sandybridge Mobile
           GLX Version: 3.0 Mesa 17.2.8 Direct Rendering: Yes
Audio:     Card Intel 6 Series/C200 Series Family High Definition Audio Controller
           driver: snd_hda_intel bus-ID: 00:1b.0
           Sound: Advanced Linux Sound Architecture v: k4.15.0-23-generic
Network:   Card: Intel Centrino Advanced-N 6205 [Taylor Peak]
           driver: iwlwifi bus-ID: 02:00.0
           IF: wlp2s0 state: up mac: <filter>
Drives:    HDD Total Size: 128.0GB (53.3% used)
           ID-1: /dev/sda model: Samsung_SSD_850 size: 128.0GB
Partition: ID-1: / size: 115G used: 62G (57%) fs: ext4 dev: /dev/sda1
           ID-2: swap-1 size: 2.56GB used: 0.00GB (0%) fs: swap dev: /dev/sda2
RAID:      No RAID devices: /proc/mdstat, md_mod kernel module present
Sensors:   System Temperatures: cpu: 60.0C mobo: N/A
           Fan Speeds (in rpm): cpu: N/A
Info:      Processes: 195 Uptime: 6:56 Memory: 1414.4/7855.8MB
           Init: systemd runlevel: 5 Gcc sys: 5.4.0
           Client: Shell (bash 4.3.481) inxi: 2.2.35 


 ```

**Issue**

My problems _that I noticed_ were:

**issue 1**) removable HDD not discovered when hot-plugged (Dell Latitude media bay, SATA bus), no drive recognized. Reboot with drive plugged in required.

**issue 2**) wireless settings in Dell BIOS go ignored:
   a) wireless switch (WLAN, WWAN, Bluetooth) -this is three checkboxes to configure each to be controlled by the physical switch on the right side of laptop.
   b) wireless enable (WLAN, WWAN, Bluetooth) -again, three checkboxes, these enable or disable each.

The resulting behaviors for issue 2  included physical wireless switch on right-hand side of laptop being enabled, even though I had it disabled in BIOS. Also wireless connectivity had dropouts.  

[I later attributed these wireless dropouts to wireless switch doing erroneous things if touched (it shouldn't be doing anything at all) and/or removal/insertion of secondary hard drive into media bay's SATA bus causing an interruption.]

The wireless devices I had disabled in the BIOS settings also remained up and running. This meant that the Bluetooth couldn't effectively be disabled at BIOS settings.

I have no idea what else may not be working correctly.

**Steps to reproduce**

Install and use newer 4.15 kernel.  This applies to both Linux Mint 18.3 and the newest beta 19 (base kernel for this "is" 4.15).  There is no behavior difference between the two.  It is related to the kernel as implemented in Linux Mint, so I am posting here.  (The "bug list" over at Kernel Archives says to only report kernel versions not packaged with a distro.)

For troubleshooting purposes I temporarily installed Ukuu and tried other kernel versions not available in the Linux Mint distro.  These ignored BIOS settings only manifest with 4.15 and greater, up through 4.17.  
Also 4.14 (not in the distro) doesn't exhibit these BIOS setting issues, although it breaks the Apt system and Software Manager until it is removed.

**Expected behaviour**

**Other information**

linux-firmware package is installed and up to date
intel-firmware package is installed and up to date (enabled in Driver Manager)

Software Manager - I click on Refresh and it says system is up to date

GRUB_CMDLINE_LINUX_DEFAULT="quiet splash acpi_osi=Linux"

Was using TLP.  Uninstalled that and retried.  This only improved issue 1, but not issue 2.

**Comment by clefebvre** [comment]
Please report this upstream, it's not related to Cinnamon.
