### ISSUE TITLE
Sound settings app crashes when USB sound device is connected

### ISSUE THREAD

**Issue by rbielefeld** [linuxmint/cinnamon#7662]
```
 * Cinnamon version 3.8.4
 * Distribution - Mint Cinnamon 19
 * Graphics hardware *and* driver used NVIDIA Corporation GF108GLM [NVS 5200M] NVIDIA
 * 64 bit
 ```

**Issue**
Sound settings crash when USB sound device is connected 

**Steps to reproduce**
Works fine with builtin device. Everytime the USB soundevice is connected.

**Expected behaviour**
Should open Dialog to configure devices

**Other information**
$ sudo cat /proc/asound/cards
 0 [PCH            ]: HDA-Intel - HDA Intel PCH
                      HDA Intel PCH at 0xf7730000 irq 30
 1 [Pro            ]: USB-Audio - FastTrack Pro
                      M-Audio FastTrack Pro at usb-0000:00:14.0-1, full speed
 2 [NVidia         ]: HDA-Intel - HDA NVidia
                      HDA NVidia at 0xf6080000 irq 17
reiner@reiner-Latitude-E6530:~$ sudo cat /proc/asound/devices 
  1:        : sequencer
  2: [ 1]   : control
  3: [ 1- 0]: digital audio playback
  4: [ 1- 0]: digital audio capture
  5: [ 1- 1]: digital audio playback
  6: [ 1- 1]: digital audio capture
  7: [ 1- 0]: raw midi
  8: [ 0]   : control
  9: [ 0- 0]: digital audio playback
 10: [ 0- 0]: digital audio capture
 11: [ 0- 0]: hardware dependent
 12: [ 0- 1]: hardware dependent
 13: [ 2]   : control
 14: [ 2- 3]: digital audio playback
 15: [ 2- 7]: digital audio playback
 16: [ 2- 8]: digital audio playback
 17: [ 2- 9]: digital audio playback
 18: [ 2- 0]: hardware dependent
 19: [ 2- 1]: hardware dependent
 20: [ 2- 2]: hardware dependent
 21: [ 2- 3]: hardware dependent
 33:        : timer
[errorlog.txt](https://github.com/linuxmint/Cinnamon/files/2116651/errorlog.txt)

**Comment by collinss** [comment]
Please run `cinnamon-settings sound` from a terminal and post any relevant output when it crashes.

**Comment by rbielefeld** [comment]
I attached the core file and the output of stderr. 

[core.gz](https://github.com/linuxmint/Cinnamon/files/2117920/core.gz)
[stderr.log](https://github.com/linuxmint/Cinnamon/files/2117921/stderr.log)

**Comment by rbielefeld** [comment]
I checked the Linux Mint 19 Mate Beta version and it works.

**Comment by leigh123linux** [comment]
I haven't noticed any issues using my USB soundcard (AudioLab 8200CD)

**Comment by Vahan86** [comment]
@rbielefeld, is this still an issue for you with Cinnamon 4.2?

**Comment by Vahan86** [comment]
@icarter09, can we close the issue since there is no response from OP?
