### ISSUE TITLE
Desktop freezes when moving files

### ISSUE THREAD

**Issue by sathiz1993** [linuxmint/cinnamon#7666]
```
 * Cinnamon version Cinnamon 3.6.7
 * Distribution - Linux Mint 18.3 Sylvia
 * Graphics driver - nvidia 384.130
 ```

**Issue**
While moving files from between drives,  cinnamon freezes the desktop as well as other apps running.

**Steps to reproduce**
Moving some large files between drives and try to access browser and some other application

**Comment by icarter09** [comment]
@sathiz1993 does Cinnamon ever recover from the freeze or does Cinnamon have to be restarted?

**Comment by sathiz1993** [comment]
@icarter09 It freezes and I wait for some time and do a restart for recovery.

**Comment by Vahan86** [comment]
@sathiz1993, is this still an issue for you with Cinnamon 4.2?

**Comment by Vahan86** [comment]
@icarter09, can we close this issue since there is no response from OP?
