### ISSUE TITLE
sorting widows function

### ISSUE THREAD

**Issue by gc-group** [linuxmint/cinnamon#7667]
```
 * cinnamon --3.6
 * Distribution - Mint 18.3
 * Intel HD grafics 3000 
 * 64 bit
 ```

Dear Cinnamon developers. I want to inform you that your desktop environment, as for me one of the best, if not for one THING — the lack of sorting Windows. 
 The absence of this option causes the panel to be filled with similar Windows that could be hidden when sorting. Such a function exists in the gnome 2 — mate fork, and as I know, cinnamon is a shell written in gnome 3, but with an interface close to gnome 2.  Plus, in gnome 3, the sorting function of Windows is present. I'd like to see this feature in cinnamon.
Thank you!

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
