### ISSUE TITLE
[FEATURE REQUEST]Add spinner indicator to network applet

### ISSUE THREAD

**Issue by pyroxar** [linuxmint/cinnamon#7671]
I have idea that Linux Mint team should add spinner indicator to network applet which should be shown when I click to refresh WiFi networks. i think that It will be very user friendly.

What do you think about this?
![image](https://user-images.githubusercontent.com/23406555/41933798-2a2a32cc-7985-11e8-89fa-3d2d5863f934.png)

**Comment by CottonEaster** [comment]
Compare #7094.

**Comment by icarter09** [comment]
Closing this ticket due to #8891.
