### ISSUE TITLE
[FEATURE REQUEST] Install SC Controller in system by default

### ISSUE THREAD

**Issue by pyroxar** [linuxmint/Cinnamon#7672]
I propose install SC Controller in system by default and add option in system settings to launch it. I mean option like wacom tablet. Did Linux Mint team may contact with SC Controller developers and recommend adding support for more game pads' configuration?

I propose add SC Controller like timeshift or redshift to system. It will be helpfully for players who play on Linux Mint.

What do you think about this?
![image](https://user-images.githubusercontent.com/23406555/41938830-7994be4a-7994-11e8-8dd6-f0aaf4e4012a.png)

**Comment by JosephMcc** [comment]
This isn't really a Cinnamon issue. It's more for a distro to include. Same as timeshift and redshift ;)

**Comment by leigh123linux** [comment]
@JosephMcc 
IMO it's down to the user to install additional software they want, not the distro or mint.
The users would bitch like hell if we included every package in the repo's and released a 26GB iso :-) 

> 
It's more for a distro to include.
