### ISSUE TITLE
Frequent Cinnamon crashes - no obvious cause or trigger

### ISSUE THREAD

**Issue by kauffy** [linuxmint/Cinnamon#7673]
```
 * Cinnamon 3.6.7
 * Distribution - Mint 18.3
 * Graphics:  Card-1: Intel Xeon E3-1200 v3/4th Gen Core Processor Integrated Graphics Controller
           bus-ID: 00:02.0 chip-ID: 8086:0412
           Card-2: NVIDIA GM206 [GeForce GTX 960] bus-ID: 01:00.0 chip-ID: 10de:1401
           Display Server: X.Org 1.18.4 driver: nvidia Resolution: 1920x1200@59.95hz, 2560x1080@60.00hz
           GLX Renderer: GeForce GTX 960/PCIe/SSE2 GLX Version: 4.6.0 NVIDIA 390.30 Direct Rendering: Yes

 * 64 bit
 ```

**Issue**
Cinnamon crashes frequently, seemingly with no cause. Sometimes, the idle desktop will just crash, although it does appear that it only happens when I am at the machine (that is, leaving the machine on overnight, I don't wake up to find it crashed).

This happens often when I am doing something innocuous, like scrolling in a webpage, or scrubbing a piece of video in VLC or Media Player.

Other times, it seems to happen when nothing's going on at all.

It affects only Cinnamon, and if I choose to restart when it asks, everything is back to exactly where it was, and if I repeat the action I had just been doing (that seemed to "cause" the crash), it will not cause the crash a second time. It happens once in a while if I launch a fullscreen game (e.g., The Long Dark, via native Steam)-- Cinnamon will crash behind it, but the game is entirely unaffected.

It's so prevalent, I thought I'd find many more people with the issue-- I'm just special, I guess.

**Steps to reproduce**

This is entirely unclear. It can happen a few times in an hour with no obvious cause, or it may go a day or two without happening.

This problem started a few weeks ago (perhaps a month by now), but it didn't _seem_ to correlate with any action, although it's possible that something in a repository updated (I keep everything up-to-date, I believe).

**Expected behaviour**

That Cinnamon won't crash.

**Other information**
Inxi dump:

```
System:    Host: mintos Kernel: 4.13.0-38-generic x86_64 (64 bit gcc: 5.4.0)
           Desktop: Cinnamon 3.6.7 (Gtk 2.24.30) dm: lightdm Distro: Linux Mint 18.3 Sylvia
Machine:   Mobo: MSI model: Z97 GAMING 5 (MS-7917) v: 1.0 Bios: American Megatrends v: V1.13 date: 02/16/2016
CPU:       Quad core Intel Core i7-4790K (-HT-MCP-) cache: 8192 KB
           flags: (lm nx sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx) bmips: 32000
           clock speeds: min/max: 800/4500 MHz 1: 1714 MHz 2: 1692 MHz 3: 1893 MHz 4: 1487 MHz 5: 1695 MHz
           6: 1447 MHz 7: 1959 MHz 8: 1904 MHz
Memory:    No dmidecode memory data: try newer kernel.
Graphics:  Card-1: Intel Xeon E3-1200 v3/4th Gen Core Processor Integrated Graphics Controller
           bus-ID: 00:02.0 chip-ID: 8086:0412
           Card-2: NVIDIA GM206 [GeForce GTX 960] bus-ID: 01:00.0 chip-ID: 10de:1401
           Display Server: X.Org 1.18.4 driver: nvidia Resolution: 1920x1200@59.95hz, 2560x1080@60.00hz
           GLX Renderer: GeForce GTX 960/PCIe/SSE2 GLX Version: 4.6.0 NVIDIA 390.30 Direct Rendering: Yes
Audio:     Card-1 Intel Xeon E3-1200 v3/4th Gen Core Processor HD Audio Controller
           driver: snd_hda_intel bus-ID: 00:03.0 chip-ID: 8086:0c0c
           Card-2 NVIDIA Device 0fba driver: snd_hda_intel bus-ID: 01:00.1 chip-ID: 10de:0fba
           Card-3 Intel 9 Series Family HD Audio Controller
           driver: snd_hda_intel bus-ID: 00:1b.0 chip-ID: 8086:8ca0
           Card-4 Logitech HD Pro Webcam C920 driver: USB Audio usb-ID: 003-024 chip-ID: 046d:082d
           Card-5 Logitech G430 Surround Sound Gaming Headset
           driver: USB Audio usb-ID: 003-003 chip-ID: 046d:0a4d
           Sound: Advanced Linux Sound Architecture v: k4.13.0-38-generic
Network:   Card: Qualcomm Atheros Killer E220x Gigabit Ethernet Controller
           driver: alx port: d000 bus-ID: 03:00.0 chip-ID: 1969:e091
           IF: enp3s0 state: up speed: 1000 Mbps duplex: full mac: 4c:cc:6a:0c:17:a7
           WAN IP: 172.118.150.223 IF: virbr0-nic ip-v4: N/A ip-v6: N/A
           IF: enp3s0 ip-v4: 192.168.0.7 ip-v6: fe80::5409:4ac1:2202:7e13
           IF: virbr0 ip-v4: 192.168.122.1 ip-v6: N/A
Drives:    HDD Total Size: 10758.1GB (59.4% used)
           ID-1: /dev/sda model: Samsung_SSD_850 size: 500.1GB serial: S2RANX0H523942P
           ID-2: /dev/sdb model: ST2000DX002 size: 2000.4GB serial: Z4Z7TJAZ
           ID-3: /dev/sdc model: SB2 size: 256.1GB serial: FF180771060806643036
           ID-4: USB /dev/sdd model: Expansion_Desk size: 8001.6GB serial: WCT01GRE
           Optical: /dev/sr0 model: HL-DT-ST BD-RE  WH16NS40 rev: 1.02 dev-links: cdrom,cdrw,dvd,dvdrw
           Features: speed: 48x multisession: yes
           audio: yes dvd: yes rw: cd-r,cd-rw,dvd-r,dvd-ram state: running
Partition: ID-1: / size: 31G used: 22G (74%) fs: ext4 dev: /dev/sdc1
           label: N/A uuid: f4926a48-cbc5-4cce-858b-14264e7bd789
           ID-2: /home size: 174G used: 133G (81%) fs: ext4 dev: /dev/sdc6
           label: N/A uuid: 86cbc072-c206-4261-b4cd-f3accc8f9789
           ID-3: /media/mintos/Seagate 8-TB size: 7.3T used: 4.2T (58%) fs: fuseblk dev: /dev/sdd2
           label: Seagate 8-TB uuid: 00904F14904F0F98
           ID-4: /media/mintos/Data size: 1.9T used: 1.5T (81%) fs: fuseblk dev: /dev/sdb2
           label: Data uuid: 02D66228D6621BE3
           ID-5: /mnt/oldvhds size: 100G used: 66G (66%) fs: fuse dev: /dev/fuse label: N/A uuid: N/A
           ID-6: swap-1 size: 33.00GB used: 0.00GB (0%) fs: swap dev: /dev/sdc5
           label: N/A uuid: bce06b64-1168-4803-a863-cc466463b853
RAID:      System: supported: linear multipath raid0 raid1 raid6 raid5 raid4 raid10
           No RAID devices: /proc/mdstat, md_mod kernel module present
           Unused Devices: none
Unmounted: ID-1: /dev/sda1 size: 0.47G label: Recovery uuid: 02ACC851ACC840C1
           ID-2: /dev/sda2 size: 0.10G label: N/A uuid: C2CA-13C5
           ID-3: /dev/sda3 size: 0.02G label: N/A uuid: N/A
           ID-4: /dev/sda4 size: 499.51G label: OS uuid: 120ED1470ED1248F
           ID-5: /dev/sdb1 size: 0.13G label: N/A uuid: N/A
           ID-6: /dev/sdd1 size: 0.13G label: N/A uuid: N/A
Sensors:   System Temperatures: cpu: 29.8C mobo: 27.8C gpu: 0.0:49C
           Fan Speeds (in rpm): cpu: N/A
Info:      Processes: 328 Uptime: 2 days Memory: 7940.3/32051.6MB
           Init: systemd v: 229 runlevel: 5 default: 2 Gcc sys: 5.4.0
           Client: Shell (bash 4.3.481 running in terminator) inxi: 2.2.35 

```

**Comment by BonsaiSage** [comment]
[crash.tar.gz](https://github.com/linuxmint/Cinnamon/files/2160418/crash.tar.gz)

I'm getting pretty much the same thing. Updated the system and rebooted, every time it announces that it has crashed and is now running in fallback mode.

no clue what to do

**Comment by tdjong** [comment]
Hi there,
I have the same thing. The problem started after an update this week.
[crash.tar.gz](https://github.com/linuxmint/Cinnamon/files/2169178/crash.tar.gz)

I have seen it before when trying a 4.15 kernel on Mint 18.3. Which is active again. I will choose an older kernel at boot. And report back here.
A clean boot of Mint 19 with kernel 4.15 does work.

**Comment by Altmann-ta** [comment]
I have the same issue, upgrading to kernel 5.15.49 makes my system hang on boot - fresh clean install.
Pardon my lack of info, im new to this...

CPU:
  Topology: Quad Core model: Intel Pentium N3530 bits: 64 type: MCP 
  L2 cache: 1024 KiB 
  Speed: 500 MHz min/max: 500/2582 MHz Core speeds (MHz): 1: 500 2: 500 
  3: 500 4: 500 
  Flags: 3dnowprefetch acpi aperfmperf apic arat arch_perfmon bts clflush 
  cmov constant_tsc cpuid cx16 cx8 de ds_cpl dtes64 dtherm dts epb ept erms 
  est flexpriority fpu fxsr ht ida lahf_lm lm mca mce mmx monitor movbe msr 
  mtrr nonstop_tsc nopl nx pae pat pbe pclmulqdq pdcm pebs pge pni popcnt 
  pse pse36 pti rdrand rdtscp rep_good sep smep ss sse sse2 sse4_1 sse4_2 
  ssse3 syscall tm tm2 tpr_shadow tsc tsc_adjust tsc_deadline_timer 
  tsc_known_freq tsc_reliable vme vmx vnmi vpid xtopology xtpr 
Graphics:
  Device-1: Intel Atom Processor Z36xxx/Z37xxx Series Graphics & Display 
  driver: i915 v: kernel 
  Display: x11 server: X.Org 1.19.6 driver: modesetting unloaded: fbdev,vesa 
  resolution: 1366x768~60Hz 
  OpenGL: renderer: Mesa DRI Intel Bay Trail v: 4.2 Mesa 18.0.5

**Comment by Soapux** [comment]
I'm also seeing these seemingly random crashes now.  I didn't see them in Cinnamon 3.8.9, but only after upgrading to Cinnamon 4+.  I'm on the nvidia drivers 415.25.

I see this message in my .xsession-errors.log:

Traceback (most recent call last):
  File "/usr/bin/cinnamon-launcher", line 55, in <module>
    os.execvp(FALLBACK_COMMAND, (FALLBACK_COMMAND,) + FALLBACK_ARGS)
  File "/usr/lib/python3.6/os.py", line 559, in execvp
    _execvpe(file, args)
  File "/usr/lib/python3.6/os.py", line 604, in _execvpe
    raise last_exc.with_traceback(tb)
  File "/usr/lib/python3.6/os.py", line 594, in _execvpe
    exec_func(fullname, *argrest)
FileNotFoundError: [Errno 2] No such file or directory
None: no process found

**Comment by leigh123linux** [comment]
Looking at the only usable crash.tar the issue is the graphics driver, not cinnamon.
