### ISSUE TITLE
Windows (occasionally) not appearing in workspaces or window switcher properly

### ISSUE THREAD

**Issue by ghost** [linuxmint/cinnamon#7675]
```
Kernel: 4.17.0-2-MANJARO x86_64
Distro: Manjaro Linux 17.1.10
Graphics: Intel UHD Graphics 620 driver: i915
 ```
I've used Cinnamon for 4 years, 4 months of which have been on my current computer, which I update frequently.  Somewhere in either the transition from 3.8.2 to 3.8.3, or 3.8.3 to 3.8.4, and I'm fairly sure it's the latter, I've started getting a few related bugs:
* window name appearing in the taskbar of all workspaces when I cycle through them with the keyboard shortcuts, but the window stays in the workspace I left it in as expected
* window name not appearing in the taskbar (of any workspace) when it's still open in a workspace
* window not alt-tabbable

Each of these conditions has happened a few times, and separately of each other.  I really wish I could give steps for reproduction.  I'll happily give more info if it's requested or test various things.

**Comment by ajnye** [comment]
When windows appear in the workspace, but not the taskbar, they can still be ctrl+alt+shift+arrow'd between the workspaces just fine, yet never appearing on the taskbar in any.

**Comment by icarter09** [comment]
Closing this issue since the original submitter of this ticket is no longer present on Github.
