### ISSUE TITLE
How to compile cinnamon

### ISSUE THREAD

**Issue by sguillia** [linuxmint/Cinnamon#7678]
```
 * Cinnamon version (Cinnamon 2.8.6)
 * Distribution - (Ubuntu 16.04.4 LTS)
 * Graphics hardware *and* driver used (not important)
 * 64 bit
 ```

**Issue**
I would like to contribute but compiling cinnamon is a nightmare to me.
I get errors everywhere that in sum take me hours.

**Steps to reproduce**
git clone https://github.com/linuxmint/Cinnamon
cd Cinnamon
./autogen.sh

**What happens**

#### a)
First `gtkdocize` is command not found and you have to spend 10 minutes searching for the package containing this because `apt search gtkdocize` throws nothing and `--disable-gtk-doc` seems ignored
Problem solved but loss of time

#### b)
```
Please add the files
  codeset.m4 gettext.m4 glibc21.m4 iconv.m4 isc-posix.m4 lcmessage.m4
  progtest.m4
from the /usr/share/aclocal directory to your autoconf macro directory
or directly to your aclocal.m4 file.
```
`AC_CONFIG_MACRO_DIR` pointed to the m4 directory so I've done:
```
cp /usr/share/aclocal/* m4/
```
Message still appears though, why?

#### c)
```
You will also need config.guess and config.sub, which you can get from
ftp://ftp.gnu.org/pub/gnu/config/.
```
Could this be automatized? Would patch be accepted?
Also the message should tell where I am supposed to put those files.

#### d)
```
configure: error: Package requirements [a gazillion packages] were not met
```
I've spent a lot of time using `apt search` before finding out that the `debian/control` file contains the name of the packages. Maybe there should be that information in an INSTALL.md file?

### e)
```
apt: libmuffin-dev is already the newest version (2.8.4-1).
```
So now I'm compiling https://github.com/linuxmint/muffin
```
$ cd muffin
$ ./autogen.sh
checking ...
./configure: line 17417: syntax error near unexpected token `0.8.0'
./configure: line 17417: `GNOME_DOC_INIT(0.8.0)'
```
Lines 17416 and 17417 of configure:
```
# Use gnome-doc-utils:
GNOME_DOC_INIT(0.8.0)
```
What should I do?

### f)
```
Requested 'cjs-1.0 >= 3.2.0' but version of cjs-1.0 is 2.8.0
```
Now compiling https://github.com/linuxmint/cjs
As usual, git clone, cd, autogen.sh
```
No package 'mozjs-52' found
```
Where the hell am I supposed to get this one.
- Existence of repositories like [this one](https://github.com/collinstocks/build-libmozjs/) show it isn't easy
- apt can't find version 52 of libmozjs
- adding the source "deb http://ftp.de.debian.org/debian sid main" as referenced here https://packages.debian.org/sid/libmozjs-52-dev doesn't work (apt updat ecomplains about public key not being available)
So I downloaded the .deb manually even if it isn't recommended
Package Installer says "Error: Dependency is not satisfiable: libmozjs-52-0 (= 52.3.1-7)"

I'm pretty sure it's a problem on my side rather than a problem in cinnamon. Compiling cinnamon should not take two working days.

Could you please tell me why I am struggling that much and how I could compile in order to contribute?

Thanks a lot.

**Comment by NikoKrause** [comment]
The command to compile Cinnamon and other Linuxmint apps is:
```
dpkg-buildpackage
```
It tells you, which packages are missing.

Alternatively you can use `mint-dev-tools`:
```
sudo apt install mint-dev-tools
```
After that run:
```
mint-dev-build
```

**Comment by leigh123linux** [comment]
Your issue belongs on a forum, not here.
Dev time is too precious to answer this, try reading.

http://developer.linuxmint.com/reference/git/cinnamon-tutorials/building.html

**Comment by leigh123linux** [comment]
Ubuntu 16.04.4 LTS is too old to include mozjs-52!

> No package 'mozjs-52' found

**Comment by brownsr** [comment]
git clone the repo
dpkg-buildpackage in the repo directory
change to directory above
sudo dpkg -i *.deb

If you want to start putting some changes together make sure you don't change master or it makes life harder.  git branch thingy  git checkout thingy   etc.etc.

We always welcome new developers.  Don't get discouraged if you are finding it hard to get around at first, it's a reasonably complex ecosystem, and it takes time to get used to what is where and how it all hangs together.  Don't hesitate to ask questions,

**Comment by leigh123linux** [comment]
@sguillia  cinnamon master requires Ubuntu 18, maybe updating to 18 and using a ppa to provide cinnamon base would be an easier option

https://launchpad.net/~embrosyn/+archive/ubuntu/cinnamon
