### ISSUE TITLE
Timeshift Settings Filters Summary doesn't update on filter include/exclude change

### ISSUE THREAD

**Issue by kklibo** [linuxmint/Cinnamon#7679]
```
 * Cinnamon 3.8.6
 * Mint 19
 * running in virtualbox
 * 64 bit
 ```

**Issue**
In the Timeshift->Settings->Filters tab, the Summary option doesn't reflect a filter's change from exclude to include mode until after the settings dialog is closed and reopened.

**Steps to reproduce**
1. In the TimeShift->Settings->Filters tab, add a new excluded folder (I used /home/user/Music).
2. View the Summary. The new folder should be listed without a + prefix.
3. Click the radio button to set the new folder to 'include'.
4. View the Summary again, and notice that the new folder is still displayed without a + prefix.
5. Close and reopen the Settings dialog, and view the Summary. The + prefix is now present for the new folder.

**Expected behaviour**
The + prefix should appear in the summary after the include/exclude setting is changed.

**Other information**
The include filter seems to actually back up the expected files when Timeshift is run, so this is probably just a local refresh issue.

**Comment by JosephMcc** [comment]
Thanks for the report but this needs to be filed against Timeshift. It really has nothing to do with Cinnamon.
