### ISSUE TITLE
Linux file system does not update automatically

### ISSUE THREAD

**Issue by EpilepticSoftware** [linuxmint/Cinnamon#7680]
```
 * Cinnamon 3.6.7
 * Linux Mint 18.3
 * AMD Radeon HD 6850 (intel-microcode driver) and Nvidia GTX 720 (Nvidia driver) 
 * 64 bit
 ```

**Issue**
My problem was that the file system in all programs (tested in Sublime, Atom, Visual Studio Code, Nemo, Thunar and Caja) was no longer updated automatically in all programs, I had to press F5 to refresh. 

**Steps to reproduce**
I do not know which event has triggered this.

**Expected behaviour**
Automatic file system refresh.

**Other information**
After moving all files out of the ~/.cinnamon/configs folder, it worked again.

These are the files I moved out of the configs folder :
[cinnamon-config.zip](https://github.com/linuxmint/Cinnamon/files/2152841/cinnamon-config.zip)

**Comment by JosephMcc** [comment]
There isn't much we can do unless you supply us with more information on how to reproduce this. If it happens again and you get more info I'll reopen it.
