### ISSUE TITLE
Support _GTK_HIDE_TITLEBAR_WHEN_MAXIMIZED property

### ISSUE THREAD

**Issue by memeplex** [linuxmint/Cinnamon#7681]
```
~:: uname -a
Linux carlos 4.14.52-1-MANJARO #1 SMP PREEMPT Tue Jun 26 15:24:31 UTC 2018 x86_64 GNU/Linux

~:: cinnamon --version
Cinnamon 3.8.6

~:: lspci | grep VGA
00:02.0 VGA compatible controller: Intel Corporation 2nd Generation Core Processor Family Integrated Graphics Controller (rev 09)

~:: pacman -Qs xf86-video-intel
local/xf86-video-intel 1:2.99.917+829+gd7dfab62-1 (xorg-drivers)
    X.org Intel i810/i830/i915/945G/G965+ video drivers
```
---
 
The _GTK_HIDE_TITLEBAR_WHEN_MAXIMIZED property is supported by Gnome and it's currently the only way AFAICS that allows a client ask the WM to remove its decorations. We are trying to implement a hide-titlebar-on-maximize mode for Emacs but when the client explicitly hides/shows its decorations bad things happen both under Gnome and under Cinnamon. For instance, if you maximize the window, then hide its decorations, then show them again, the window becomes invisible, probably because Cinnamon WM is trying to fit a full-sized undecorated window plus its restored decorations so yielding a geometry larger than the actual screen. The bottom line is that it's safer to politely request the WM to remove the decorations, but there is no way to do that in Cinnamon. Notice I'm not asking for a settings UI but just for honouring the _GTK_HIDE_TITLEBAR_WHEN_MAXIMIZED property.

**Comment by mtwebster** [comment]
The first concern would be, how does one unmaximize this window if there aren't any window controls (ignoring window list applet and shortcuts)?   I'm pretty sure that's why we no longer support it, though I could be wrong.

It looks like mutter (gnome's wm) has a preference to ignore these requests or not.  I suppose we could do the same, but we'd probably default it to ignore.

**Comment by memeplex** [comment]
I think this is client responsibility, at least that is the way Gnome is going (by interpreting the titlebar is "owned by the client"), I'm not saying Cinnamon should follow Gnome there but:

1. Since some clients would like to set this property to work under Gnome.
2. Since it's a standard gtk feature [1]

I would say that Cinnamon should honour it and let the client provide its own means of exiting the maximized state. This is not a problem for a client such as emacs, emacs users that know how to toggle a property from emacs customization UI will probably also know how to exit maximized state with their keyboards (or by toggling the property again); anyway, that's for emacs to decide. Other clients will go the pure CSD way or don't provide a hide-titlebar-on-maximize option at all. Again: I'm not asking for the WM to hide decorations on maximize on a general basis but on a per client basis, letting the client decide. Additionally, honouring the property will simplify extensions like [2] that are currently a messy hack (I'm not even sure why this extension is setting _GTK_HIDE_TITLEBAR_WHEN_MAXIMIZED at all, maybe because it was ripped of from its Gnome equivalent --that's quite a hack too-- but the workhorse of the extension is _MOTIF_WM_HINTS). 

---

[1] https://developer.gnome.org/gdk3/stable/gdk3-X-Window-System-Interaction.html#gdk-x11-window-set-hide-titlebar-when-maximized

[2] https://githu gdk_x11_window_se gdk_x11_window_set_hide_titlebar_when_maximizedt_hide_titlebar_when_maximizedb.com/linuxmint/cinnamon-spices-extensions/blob/master/cinnamon-maximus%40fmete/files/cinnamon-maximus%40fmete/extension.js#L565

**Comment by memeplex** [comment]
Another way to think about this is: nemo, terminal, firefox, all provide options to hide the menubar. The user that is willing to do that should also know how to undo it when needed. You're already allowing this feature for some clients, some of them show a popup explaining how to get the menu back, others don't, everything on a per client basis. Well, this is the same but for the titlebar.

**Comment by memeplex** [comment]
Another thing to consider: even if you want to play safe and remove control even for power users that explicitly enabled it from their own apps, you can avoid that relatively popular extensions hide decorations in the worst possible way: relying in many hacks and on a global basis.

**Comment by memeplex** [comment]
Great, thanks a lot!

**Comment by memeplex** [comment]
Sorry, would it be too much to ask for an option (just a gsettings option, no friendly UI) to set the _GTK_HIDE_TITLEBAR_WHEN_MAXIMIZED on every created window, in order to get this behavior globally? Many DEs allows something like that that: xfce, plasma, mate that I know of.

**Comment by memeplex** [comment]
Regarding the last comment, just for anyone that happens to end up here in the future I've created [maximal](https://github.com/memeplex/maximal), a simple python xlib utility that just sits there waiting for creation events and setting the ` _GTK_HIDE_TITLEBAR_WHEN_MAXIMIZED` according to some rules.
