### ISSUE TITLE
UX for renaming files is insanely confusing

### ISSUE THREAD

**Issue by samuela** [linuxmint/Cinnamon#7684]
```
 * Cinnamon version (cinnamon --version) 3.4.6
 * Distribution - Debian rodete
 * NVIDIA 1cb1
 * 64 bit
 ```

**Issue**
When attempting to rename files/folders in the file explorer, the rename button doesn't appear to do anything besides remove the selection from the selected file/folder. There's no cursor or text box whatsoever. If you begin typing it immediately replaces the original name.

**Steps to reproduce**
Open up file explore. Pick a file/folder. Right-click, select "Rename". Observe.

**Expected behaviour**
A text box of some kind.

**Other information**
n/a

**Comment by leigh123linux** [comment]
The issue should be filed against nemo.

**Comment by mtwebster** [comment]
Very likely a theme issue.  Adwaita gtk theme doesn't show a rename box/highlighting for the icon view.  Try a different theme.

![screenshot from 2018-07-02 15-41-20](https://user-images.githubusercontent.com/262776/42183110-8babca14-7e0e-11e8-9061-9de8e547b1ff.png)
![screenshot from 2018-07-02 15-39-46](https://user-images.githubusercontent.com/262776/42183112-8d6146e0-7e0e-11e8-993b-39b8cb369b67.png)

**Comment by samuela** [comment]
@mtwebster I'm using the default Cinnamon theme.

**Comment by mtwebster** [comment]
If you're running Cinnamon, change the 'controls' theme (GTK theme) not cinnamon.

**Comment by samuela** [comment]
@mtwebster Ah, yeah that seems to be the problem. Still, I'm not able to get a text box border.
