### ISSUE TITLE
Maven bug

### ISSUE THREAD

**Issue by FernandoCamp** [linuxmint/Cinnamon#7686]
```
 * Cinnamon 3.8.6
 * Distribution - (Linuxt Mint 19)
 * 64 bit
 ```

**Issue**

Since i updated to Linux Mint 19, i couldn't get my Maven Repositories. I done the same steps in Linux Mint 18.3 and worked alright.
When i searched for this problem, i realized that it was related to proxy issues. It's like the Network Settings were changed or something.

**Steps to reproduce**

Download any Maven project with Eclipse or mvn with terminal.

**Expected behaviour**

It's supposed to Download and put my project ready to go.

**Comment by leigh123linux** [comment]
Report the issue against Maven
