### ISSUE TITLE
Feature request (UI/UX): add notches to mouse, touchpad sliders

### ISSUE THREAD

**Issue by ghost** [linuxmint/cinnamon#7687]
```
 * Cinnamon version (cinnamon --version) 3.6.7
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 18.3
 * Graphics hardware *and* driver used. NA
 * 32 or 64 bit: 64
 ```
Without notches or some other indicator of the slider's graduations - or, without, I suppose an extremely granular slider (i.e. one that that can be dragged to any position one wants) it is hard to know how to operate the slider: one does not know how far to drag it in order to achieve a small increase. If one is having trouble with one's pointing device - and thus needs to change its settings! - the problem will be exacerbated.

This would be a small and I imagine easy-to-implement change, yet one with an ease-of-use pay-off.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
