### ISSUE TITLE
can not switch graphics via NVIDIA X Server settings

### ISSUE THREAD

**Issue by icove** [linuxmint/Cinnamon#7688]
```
 * Cinnamon version 3.8.6
 * Distribution - Mint 19
 * Graphics hardware NVIDIA Corporation GK107M [GeForce GT 650M] & Intel Corporation 3rd Gen Core processor Graphics Controller
 * 64 bit
 ```

**Issue**
I can not switch graphics card via NVIDIA X Server settings

**Steps to reproduce**
1. install the system
2. install nvidia driver 390 via driver manager
3. switch to intel graphics card via nvidia x server settings
3. lspci | grep VGA to check nvidia card, nvidia card still enabled.

**Expected behaviour**
nvidia card should be disabled.

**Other information**
I try it on linuxmint mate, problem still be reproduced.

**Comment by leigh123linux** [comment]
File the issue against the nvidia driver.

**Comment by icove** [comment]
One more thing, linuxmint 18.3 + nvidia-384 works ok
