### ISSUE TITLE
Add blacklist to the notification applet (media players flood it)

### ISSUE THREAD

**Issue by memeplex** [linuxmint/cinnamon#7690]
```
~:: uname -a
Linux carlos 4.14.52-1-MANJARO #1 SMP PREEMPT Tue Jun 26 15:24:31 UTC 2018 x86_64 GNU/Linux

~:: cinnamon --version
Cinnamon 3.8.6

~:: lspci | grep VGA
00:02.0 VGA compatible controller: Intel Corporation 2nd Generation Core Processor Family Integrated Graphics Controller (rev 09)

~:: pacman -Qs xf86-video-intel
local/xf86-video-intel 1:2.99.917+829+gd7dfab62-1 (xorg-drivers)
    X.org Intel i810/i830/i915/945G/G965+ video drivers
 ```

Each time a new song starts, many media players emit a desktop notification. I like such a behavior.

The notifications applet keeps the emitted notifications for later inspection. I like such a feature.

What I don't like is the notification applet constantly showing new notifications from the media player (spotify in my case). This makes me pay too much attention to a useless counter in the panel. And maybe when the counter becomes really meaningful I will ignore it as a consequence.

I toggled the "Ignore transient flag" but to no avail.

Could you add a blacklist to the applet? Maybe there is already one but only exposed as a gsettings options, isn't it?

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
