### ISSUE TITLE
Changed order of open windows in taskbar after standby or changed monitor setup

### ISSUE THREAD

**Issue by ghost** [linuxmint/cinnamon#7693]
```
 * Cinnamon version 3.8.6
 * Distribution - Linux Mint 19
 * Graphics hardware *and* driver used: Intel
 * 64 bit
 ```

**Issue**

After Standby the order of the open windows in the taskbar changes.

**Steps to reproduce**

Open some windows. Go into standby and start your system again.

**Expected behaviour**

Order of the windows in the taskbar should stay the same.

**Other information**

A second monitor is used with a laptop. Internal display of laptop is off. Same happens when switch from one monitor to two monitors setup.

**Comment by icarter09** [comment]
@sebastianbauer how are you running the "Standby" command?

**Comment by sebastianbauer** [comment]
@icarter09 Either with the shutdown dialog (from the menu) or the moon key on my external keyboard.

But it actually also happens after switching the monitor setup (From only external to external and internal and / or back).

**Comment by icarter09** [comment]
Closing this issue since the original submitter of this ticket is no longer present on Github.
