### ISSUE TITLE
Linux mint 19 Cinnamon  not booting after installing with UEFI bios

### ISSUE THREAD

**Issue by jeroenst** [linuxmint/Cinnamon#7700]
Cinnamon Mint 19

When installing Linux Mint 19 on a pc with uefi boot enabled, the system won't boot after installation. Only switching to legacy boot mode makes the system work.

I did a manual partition setup with a / partition of 130gb and a swap partition of 10gb

**Comment by JosephMcc** [comment]
Thanks for reporting but this isn't a Cinnamon issue. Would be better reported here: https://github.com/linuxmint/linuxmint/issues

**Comment by jeroenst** [comment]
Ok, created:

https://github.com/linuxmint/linuxmint/issues/25
