### ISSUE TITLE
Linux mint 19 Cinnamon installation seems to hang but actually works

### ISSUE THREAD

**Issue by jeroenst** [linuxmint/Cinnamon#7701]
When installing linux mint 19 the installer at some point is not responding (I think it's creating partitions).

It should show a message like Creating Partitions, please wait...

**Comment by JosephMcc** [comment]
Thanks but this isn't really a Cinnamon issue. Would be better reported here: https://github.com/linuxmint/linuxmint/issues

**Comment by jeroenst** [comment]
Ok, created:

https://github.com/linuxmint/linuxmint/issues/26
