### ISSUE TITLE
intel_pstate don't scale cpu frequency in Mint 19

### ISSUE THREAD

**Issue by connormclaud** [linuxmint/Cinnamon#7703]
```
 * Cinnamon version (cinnamon --version)
Cinnamon 3.8.6
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
Mint 19
 * Graphics hardware *and* driver used
Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
 * 32 or 64 bit
64 bit
 ```

**Issue**
I have HP Spectre Model 13-af009ur laptop. 
Once updated from Mint 18.3 to 19 I see a very slow response from OS.
So every single action takes very long time. After hours of debugging root cause found:

intel_pstate driver failed to scale CPU frequency and leave it at minimum (400 Mhz) no matter what.

As a workaround I disabled intel_pstate in grub config. acpi-cpufreq works fine, issue is gone.

**Steps to reproduce**
Install Mint 19 into HP Spectre Model 13-af009ur with Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz 

**Expected behaviour**
Adequate performance. intel_pstate should scale cpu frequency depending on system load.

**Other information**
I understand Mint is not responsible for the issue. It is Intel's kernel driver. Not sure where to file an issue for intel_pstate.

**Comment by JosephMcc** [comment]
Closing this since by your own admission it isn't Mint's problem and certainly isn't an issue with Cinnamon :)
