### ISSUE TITLE
software rendering mode cause excessive cpu usage on all threads on an i7.

### ISSUE THREAD

**Issue by bash64** [linuxmint/Cinnamon#7704]
```
 * Cinnamon version (cinnamon --version) 3.8.7
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) mint 19 cinnamon 64bit
 * Graphics hardware *and* driver used intel hd 4600, fbdev
 * 32 or 64 bit 64bit
 ```

**Issue**

when running in software rendering mode cinnamon uses excessive cpu usage.
on an i7 all 8 threads go to 40-60% when viewing any kind of graphics such as the resources tab on the system monitor or a video stream using firefox.

**Steps to reproduce**

force rendering mode. probably use nomodeset on the boot line is the easiest. 

**Expected behaviour**
unbelievable cpu usage on all 8 threads.

**Other information**
does not happen with normal video drivers.
only software rendering mode.

**Comment by jaszhix** [comment]
Software rendering forces the CPU to render everything - this should be expected. Its more of a fail-safe when driver issues occur, and not intended for normal use. Also, Firefox will use software video decoding, so that will further increase CPU usage.

**Comment by bash64** [comment]
This did not happen in any previous version of mint including mint 19 beta.
Right after upgrading to mint 19 full using the command lines provided this began to happen.

**Comment by jaszhix** [comment]
Why not use video drivers? If its related to that you could open an issue on the [Linux Mint repo](https://github.com/linuxmint/linuxmint/issues).

**Comment by bash64** [comment]
I use qemu with gpu passthru.
I must boot with no video drivers to do this achieve this.
It is important that the linux side is behaving normally, otherwise it impacts qemu.

**Comment by bash64** [comment]
I feel that cinnamon is the issue as the cinnamon --replace process is using the high cpu.

**Comment by bash64** [comment]
If need be I will install different version of mint to prove this is not normal.

**Comment by jaszhix** [comment]
Most of the guides for VFIO GPU pass-through recommend at least two GPUs - I wouldn't recommend using Cinnamon in software rendering mode in general. 

If its a performance regression, providing more data like logs (~/.xsession-errors), loaded xlets:

`gsettings get org.cinnamon enabled-applets && gsettings get org.cinnamon enabled-desklets && gsettings get org.cinnamon enabled-extensions`

would help. You indicated CPU usage goes away when a video driver is loaded, so it doesn't seem like one, but someone can correct me.

**Comment by bash64** [comment]
I was able to recreate the issue in two different situations. I don't know how I never noticed it before. I do have two gpus (nvidia/intel optimus). Optimus is special. You need to load with no video drivers (not even for the intel) for it to work with qemu.
This is closed for now.

**Comment by leigh123linux** [comment]
There is no need to install mint again, as it isn't cinnamon using all those threads (it's single thread only).

> If need be I will install different version of mint to prove this is not normal.
