### ISSUE TITLE
Launching Spotify makes panel disappear

### ISSUE THREAD

**Issue by bcagir** [linuxmint/cinnamon#7705]
```
System:    Host: berkay-ThinkPad-x230 Kernel: 4.15.0-20-generic x86_64 bits: 64 Desktop: Cinnamon 3.8.7
           Distro: Linux Mint 19 Tara
Graphics:  Card: Intel 3rd Gen Core processor Graphics Controller
           Display Server: x11 (X.Org 1.19.6 ) drivers: modesetting (unloaded: fbdev,vesa)
           Resolution: 1366x768@60.02hz
           OpenGL: renderer: Mesa DRI Intel Ivybridge Mobile version: 4.2 Mesa 18.0.0-rc5
 ```

**Issue**
Launching Spotify (installed from their repository, version `1.0.80.480.g51b03ac3`) makes the panel disappear.

**Steps to reproduce**
1. Install Spotify from original repositories.
2. Launch Spotify.

**Expected behaviour**
Expected behaviour is panel staying intact when Spotify is launched.

**Other information**
I'm using an external display every now and then, don't know if it would have an effect on this situation.

**Comment by jaszhix** [comment]
Can you attach your ~/.xsession-errors log while this occurs?

**Comment by berkaycagir** [comment]
The only output I see is this:

```
Cinnamon warning: Treating resize request of legacy application 0x6400001 as a fullscreen request
```

**Comment by jaszhix** [comment]
It also shows what applets are being loaded, can you attach the whole file?

**Comment by berkaycagir** [comment]
Sure, here it is.
[xsession-errors.txt](https://github.com/linuxmint/Cinnamon/files/2172633/xsession-errors.txt)

**Comment by JosephMcc** [comment]
The clue here is likely the fullscreen request.

**Comment by berkaycagir** [comment]
Yeah, but this didn't exist in the Mint 18.3 (which presumably has had Cinnamon 3.6.7 while I was using it) and Spotify versions I used are the same between 18.3 and 19.

**Comment by mtwebster** [comment]
There have been a lot of of changes made to improve fullscreen and panel behavior in 3.8, though I cannot reproduce this issue with spotify.

It appears that you have guake running by your log, can you terminate that and then try to reproduce the issue?

Also, does this happen whether you have a second monitor attached or not?  How are your panels set up? (panel top bottom, only bottom, etc.. )

**Comment by berkaycagir** [comment]
It still happens even without Guake running. I can provide the xsession-errors when Guake is off, if it'd help.

I just attached a monitor and it still happens in every configuration (computer only, mirror, extended, monitor only). I only have a top panel, but I also tried it with only a bottom panel and it still happens.

**Comment by jayypluss** [comment]
I'm also experiencing this problem. I too use an external display sometimes.
I have just seen this error in .xsession-errors log:

```
(cinnamon:878): Gtk-WARNING **: 20:45:46.090: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
Cinnamon warning: Treating resize request of legacy application 0x6000001 (Spotify) as a fullscreen request

** Message: 20:49:42.213: Unable to select area using GNOME Shell's builtin screenshot interface, resorting to fallback X11.
** Message: 20:49:45.977: Unable to use GNOME Shell's builtin screenshot interface, resorting to fallback X11.

(csd-media-keys:718): media-keys-plugin-WARNING **: 20:54:42.654: Unable to get default sink
Cjs-Message: 20:57:43.118: JS LOG: pushModal: invocation of begin_modal failed

```

I have noticed that when I press keyboard shortcut for panel menu it appears over spotify along with the panel but if I click anywhere on the panel it just closes again.

![image](https://user-images.githubusercontent.com/17395606/45522356-e03ff500-b798-11e8-8d92-c1f358bf90dd.png)

**Comment by mtwebster** [comment]
Still been unable to reproduce this.

Can anyone try making a new user account (for your computer, not spotify) and logging in as that account - does the issue still occur? (Trying to eliminate it potentially being user configuration-caused)

@jayypluss what type of monitor does this happen on?

**Comment by jayypluss** [comment]
@mtwebtester it happens on my laptop's display.

**Comment by Vahan86** [comment]
Can't reproduce this issue. Works fine for me in Cinnamon 4.2

**Comment by bcagir** [comment]
> Can't reproduce this issue. Works fine for me in Cinnamon 4.2

It's been ages since this issue was an _issue_, and even putting that aside this was an issue with Cinnamon 3.8.7; so I don't really understand what's the point of your comment.
