### ISSUE TITLE
Cursor with spinning wheel is white also with DMZ-Black cursor theme

### ISSUE THREAD

**Issue by SethosII** [linuxmint/Cinnamon#7707]
```
Cinnamon 3.8.7
Linux Mint 19
Intel HD 520 driver=i915
64 bit
 ```

**Issue**

If the cursor theme is DMZ-Black and the cursor with spinning wheel is displayed then the cursor is white.

**Steps to reproduce**

I noticed this behaviour when changing to a different folder in thunderbird.

**Expected behaviour**

The cursor should have the black theme also with the spinning wheel.

**Other information**

I tried to capture this with Kazam at 60 fps (native screen refresh rate) but the cursor is invisible on the recording during the change, so I can't provide screenshots/GIF/small video showing the behaviour.

**Comment by icarter09** [comment]
Cinnamon 3.8.7
Linux Mint 19 64bit
AMD Radeon HD 6520G

Changed the cursor theme to DMZ-Black and did not see the issue. Spinning wheel (loading) was displayed as black also. Switched back and forth between DMZ-Black and DMZ-White and was not able to duplicate this issue.

**Comment by SethosII** [comment]
Ok, I reset the dconf value and set it again to DMZ-Black and now the issue doesn't appear anymore.
