### ISSUE TITLE
Menu right-click 'Add to desktop' does nothing

### ISSUE THREAD

**Issue by govinda-lm** [linuxmint/Cinnamon#7709]
```
 * Cinnamon version 3.8.7
 * Linux Mint 19 64-bit
 * Radeon HD 7520G, driver=radeon
 * Toshiba Satellite C875D
 ```

**Issue**
Nothing seems to happen after clicking 'Add to desktop' from right-click option in main menu

**Steps to reproduce**
1. Open menu
2. Right-click on application, e.g. Firefox
3. Select 'Add to desktop'
4. Look for icon on desktop
5. Be disappointed

**Expected behaviour**
Desktop icon should appear that launches application

**Other information**
Glad to provide additional information upon request

**Comment by collinss** [comment]
Works fine for me. Do you have icons enabled for your desktop? (Settings -> Desktop -> Desktop Layout). If so, could you pastebin the contents of ~/.xsession-errors after reproducing the error. Also, check the contents of ~/Desktop/ to see if it's showing up there, but not on your desktop.

**Comment by govinda-lm** [comment]
> Do you have icons enabled for your desktop? (Settings -> Desktop -> Desktop Layout).

Now I do, thanks for the insight
