### ISSUE TITLE
Merge icons and taskbar in the Desktop panel

### ISSUE THREAD

**Issue by uncertainquark** [linuxmint/Cinnamon#7714]
```
 * Cinnamon version: 3.8
 * Distribution: Mint 19 (64 bit)
 ```

**Issue**
The pinned icons and the taskbar need to be merged into one, like Windows does since many versions now. It helps preserve usability while optimizing panel space. It is also worth noting that the current state essentially duplicates functionality of the cinnamon menu. So one of them is redundant.  

![04-mint-merged-taskbar](https://user-images.githubusercontent.com/22585732/42420472-05b7d882-82e4-11e8-8974-65495a6f557c.png)

If not by default, offer an option like KDE does.
 

**Steps to reproduce**
Open a pinned app

**Expected behaviour**
The taskbar entry should not be separate as it takes up extra screen space

**Comment by brownsr** [comment]
There are 3rd party applets that offer this functionality if required.  Cinnamon is a very open system as regards working with applets, if you want to install a window list applet that also includes launchers and remove the standard window list then you are free to do that.  I'd also note that screen space is not necessary a limitation, as you can place panels on any edge you wish.  And I do see what you mean about having your favourites in a panel launcher applet having similar functionality to the menu, but it does makes things more overt, and saves on clicks and eye movement if you use the same programs frequently.  You are also free to uninstall it if you just want to use the favourites functionality in the menu.

So thanks for your suggestion, but if I understand what you have said correctly, I think that the facility you are asking for is already there through the ability to mix and match standard and 3rd party applets, and to uninstall standard applets if required.

**Comment by JosephMcc** [comment]
This has been requested many, many times. A search will bring some up such as https://github.com/linuxmint/Cinnamon/issues/67
