### ISSUE TITLE
cups-browsed / cupsd causing high CPU usage / spikes with Mint 19

### ISSUE THREAD

**Issue by evilphish** [linuxmint/Cinnamon#7716]
* Cinnamon version (cinnamon --version)
3.8.7
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
Mint 19
 * Graphics hardware *and* driver used
Intel integrated HD 620 - not relevant - printer trouble
 * 32 or 64 bit
64 bit

**Issue**
I am unsure whether this is the right place for this. Should this rather be filed further upstream? (e.g. https://github.com/OpenPrinting/cups-filters)

Since the upgrade to Mint 19, either cupsd or cups-browsed cause severe CPU spikes every 20 to 30 seconds whenever cups-browsed is active. According to htop, `cupsd -l` spikes to 100% CPU usage for a few seconds in each interval with cups-browsed spiking to around 40% as well. This is enough to send the CPU temperature on my Lenovo Laptop upwards from ~40 °C to ~70 °C and in the process spooling up the system fan as well as producing minor hangs in the system responsiveness.

CPU usage with cups-browsed enabled:
![cups-browsed-on](https://user-images.githubusercontent.com/19637718/42450674-3fbebdec-8385-11e8-850d-71e06dca5f5c.png)

CPU usage with cups-browsed disabled or uninstalled:
![cups-browsed-off](https://user-images.githubusercontent.com/19637718/42450817-af6e5d8c-8385-11e8-9c35-41ebab3d57f2.png)

This problem does not occur if I disconnect from the network, which has around 60 printers discoverable. In the images above you can also see how the spike in network traffic coincides with the elevated CPU usage. To me it is not clear whether the culprit is cupsd or cups-browsed. Advice or guesses are very welcome!

**Steps to reproduce**
Connect to a network with a few printers, wait for about 2 minutes for the initial scanning to commence and finish. After that you get 100% CPU spikes every 20 to 30 seconds.

**Expected behaviour**
Cups / cups-browsed should not hog CPU to the point where excessive cooling is required.

**Other information**
Looking at the debug logs one can see that cups-browsed is querying a lot of printers repeatedly and then sending modification commands to cupsd which also show up in the corresponding cups access log. This basically goes on forever. With Mint 18.3 I also had cups-browsed installed and active. Without any real impact on average CPU usage. 

Also, as I said above, I am unsure as to whether this is a "Mint issue" in the sense that things worked fine with 18.3 or whether this should be taken to the authors of browsed and cupsd respectively.

**Comment by leigh123linux** [comment]
Issue moved to [linuxmint/linuxmint #35](https://github.com/linuxmint/linuxmint/issues/35) via [**ZenHub**](https://www.zenhub.com/)
