### ISSUE TITLE
Errors updating ubuntu-system-adjustments

### ISSUE THREAD

**Issue by mattsmi** [linuxmint/Cinnamon#7717]
```
 * Cinnamon version (cinnamon --version): 3.8.7
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...): Linux Mint 19
 * Graphics hardware *and* driver used
 * 32 or 64 bit: 64 bit
 ```
Updates for packages available this morning. I allowed them to update, then received the error: 
"E: ubuntu-system-adjustments: installed ubuntu-system-adjustments package post-installation script subprocess returned error exit status 1".

The other errors from the Update Manager are attached.
[Linux Mint pkg update ERROR.txt](https://github.com/linuxmint/Cinnamon/files/2178072/Linux.Mint.pkg.update.ERROR.txt)

**Comment by JosephMcc** [comment]
Thanks for the report but this isn't a Cinnamon issue. General Linux Mint issues should go here: https://github.com/linuxmint/linuxmint
