### ISSUE TITLE
'Open folder' of download, in Firefox: in the case of two filetypes, the files get run, rather than the containing folder opened

### ISSUE THREAD

**Issue by CottonEaster** [linuxmint/Cinnamon#7718]
```
 * Cinnamon version (nemo --version): 3.8.7
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 19
 * Graphics hardware *and* driver used: Intel UHD Graphics 620; 3.0 Mesa 18.0.5.
 * 32 or 64 bit: 64
 ```

**Preliminary note - on establishing responsibility and on understanding the bug**

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;The [bug reporting guidelines](https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/) say (in the 'when' section) that, for one thing, one should report a bug only when one is clear on the 'responsibility' for it (which I take it to mean: are you sure it is a bug with Mint and with the particular bit of Mint one is filing the report against?). I am unsure whether what I report here is a Mint bug and if it is whether it is a Cinnamon bug. Possibly the problem owes fully or partly to Firefox and/or PcManFm; please see **other information**, below. At ant rate, it seems to me that we have _(1) a bug of some sort, (2) an impediment for the user, (3) something that might well owe at least partly to Mint_.

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;The aforementioned guidelines say also (again in the 'when' section) that one should report only bugs that one well understands. As a non-developer, there is a limit to how well I can understand bugs. I have done my best.

**Issue**

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_When Firefox downloads a .deb or a .gz file, and subsequently I tell Firefox to open the folder - not to open the file - it . . opens the file._ That is: in the case of the .deb file, gdebi runs; in the case of the archive, the file-roller program runs.

**Steps to reproduce**

1. Click a download link in Firefox, and, when asked whether one wants to save or open, choose save. Screenshot: ![image](https://user-images.githubusercontent.com/9998846/42437500-33f29720-8355-11e8-8a8a-c738ea70cead.png)

2. When the download is complete, click the save icon in Firefox and then click the folder icon - screenshot: ![image](https://user-images.githubusercontent.com/9998846/42437571-699f5fde-8355-11e8-92c2-59db8156db8c.png)

3. Result (screenshot): ![image](https://user-images.githubusercontent.com/9998846/42437632-93eef1f0-8355-11e8-8749-13da9a8989c3.png)

(That package is merely illustrative. I do not have it installed.)

**Expected behaviour**

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;I expect the folder containing a .deb or a .gz file to be opened when I ask it to be opened.

**Other information**

- _On file browsers._ I have _PcManFM_ set as my default file browser. (I do not believe that Mint supports only Nemo - otherwise, why does Mint anything else as default? Also, I would use Nemo, which I like, were it not for the following problems: #1855; #1378; #1683.) Searching the PcManFM bug tracker (https://sourceforge.net/p/pcmanfm/bugs/search) for 'firefox' and separately for 'deb' seems to show nothing relevant. I have pcmanfm 1.2.5-3, which is the version in Mint's repositories.

- _Internet browsers, reproducibility therein._ The problem is not reproducible in Chrome, nor in the Chromium-based Iridium browser: in those browsers, the 'show in folder' feature for downloads does open the folder for .deb files. (I have not tested .gz files with these browsers.) So, is this a Firefox bug? I am unsure. I can find no report of the exact problem on the Firefox bugtracker, but there are some reports that have to do with downloading compressed files, viz.: https://bugzilla.mozilla.org/show_bug.cgi?id=1328728; https://bugzilla.mozilla.org/show_bug.cgi?id=366342; https://bugzilla.mozilla.org/show_bug.cgi?id=366325.

- _Logs_. I could find nothing relevant to the problem in my PC's logs - there seemed to be nothing on Firefox, Gdebi, or PcManFM.

- *My 'preferred applications' settings*: [here is a link to a screenshot of my 'preferred applications' settings](https://www.imgur.com/a/arB0gY2).

- _Extant but closed bug report_. Previously I reported this problem at https://github.com/linuxmint/nemo/issues/1893#issue. That report is now closed – for want, I take it, of sufficient information. I hope the present report rectifies that failing.

**Comment by JosephMcc** [comment]
As stated in the other issue, I don't see how this is a Cinnamon or Nemo issue. It doesn't happen when using Nemo, the file manager we support using with Cinnamon. It doesn't happen when using other browsers. It look like some sort of issue between Firefox and your file manager. Honestly Firefox looks like the problem. Just because you didn't find an existing bug for Firefox doesn't mean it isn't one. Very few people probably run the setup you are.

**Comment by CottonEaster** [comment]
> Firefox looks like the problem.

That may be the case. I will file a bug report with Firefox.

As to

> It doesn't happen when using Nemo, the file manager we support using with Cinnamon. It doesn't happen when using other browsers

and perhaps

> Very few people probably run the setup you are

- I refer you, if I may, to this previous remark of mine:

> I do not believe that Mint supports only Nemo - otherwise, why does Mint anything else as default? Also, I would use Nemo, which I like, were it not for the following problems: #1855; #1378; #1683

Let me add that the bugs to which I refer makes my laptop unusuable when I take it out of the house, if I use Nemo. Or at least that was the case on Mint 18; preliminary testing reveals that the problem persists, but in a reduced form, on Mint 19.
