### ISSUE TITLE
buttons under titlebar get hidden in some translations

### ISSUE THREAD

**Issue by tatramat** [linuxmint/Cinnamon#7719]
```
 * Cinnamon version (cinnamon --version)
Cinnamon 3.8.7

 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
Mint 19

 * Graphics hardware *and* driver used
intel graphics, i915, not relevant

 * 32 or 64 bit
64bit
 ```

**Issue**
In some translations where button titles are longer than in english, it can happen that the buttons list gets completely hidden if it doesn't fit in the window (its default size)
Resizing the window makes the buttons appear and disappear.
See screenshots for a clear picture.

**Steps to reproduce**
- Set system language to Czech
- open Update Manager Preferences
- resize the window manually back and forth

**Expected behaviour**
The default/minimum window size should be adjusted to the size of the controls inside

**Other information**
![default-size](https://user-images.githubusercontent.com/647533/42495038-32c4e682-8422-11e8-8905-b6134c0e8a53.png)
![after-resize](https://user-images.githubusercontent.com/647533/42495044-387eb544-8422-11e8-85db-39e6aaddae8d.png)

**Comment by JosephMcc** [comment]
Thanks for the report. We've run into this issue in other places. This isn't an issue with Cinnamon but in mintupdate itself. It would be better reported here: https://github.com/linuxmint/mintupdate/issues

Now that it's reported you don't need to open a new one :)

**Comment by tatramat** [comment]
okay, my lack of knowledge, thank you! :-)
