### ISSUE TITLE
Problem with network meneger

### ISSUE THREAD

**Issue by gc-group** [linuxmint/cinnamon#7721]
```
 * Cinnamon version 3.8.7
 * Distribution - Mint 19
 *Mesa DRI Intel(R) Sandybridge Mobile
 * 64 bit
 ```

Problem with `network@cinnamon.org.` I catch this bug for the 3rd time in a week. Look on screenshot
![screenshot 2018-07-10 22-26-36](https://user-images.githubusercontent.com/33377623/42552020-069fb674-84e3-11e8-9f96-15457c97bb3e.png)

I can not reproduce this bug. There is no interference in the operation of the system. Reboot can't help

I need a normal work

**Comment by icarter09** [comment]
@gc-group are you still experiencing this issue?

**Comment by Vahan86** [comment]
@icarter09, can we close this issue?
