### ISSUE TITLE
Can't type text while window preview is showing

### ISSUE THREAD

**Issue by eblis** [linuxmint/Cinnamon#7723]
```
 * Cinnamon version 3.8.7
 * Distribution - Mint 19
 * Intel GPU - Intel Corporation HD Graphics 620
 * 64 bit
 ```

**Issue**
Sometimes I select a window and start typing text, but leave my mouse hovering the taskbar and when the window preview for the app I'm currently hovering pops up I can no longer input text in my focused window.

For example I select Slack by clicking on it's application entry in the taskbar, then leave the mouse in the same location and start typing. If the window preview popup appears then it steals input and I can no longer type in Slack.

This used to work before updating to Linux Mint 19, Cinnamon 3.8.7.

**Steps to reproduce**
Select a window from taskbar where text can be written, leaving the mouse hovering the taskbar entry.

**Expected behaviour**
I should be able to type text without issues, even once the preview window pops up.

**Other information**
The same thing used to work fine in Mint 18.3, before upgrading.

**Comment by mtwebster** [comment]
Is this the stock window list or something downloaded?

**Comment by mtwebster** [comment]
If this is for CobiWindowList please open the issue here: https://github.com/linuxmint/cinnamon-spices-applets/issues

I can reproduce with that applet, not the stock one, however.

**Comment by mtwebster** [comment]
Next time please link that initially.  He's correct regarding 'popups' - I'm guessing that applet shows previews as popups so you can click on the preview to activate the window.  The stock window list treats them as tooltips instead (which do not take input.)  Still, I don't consider this a cinnamon bug, other than maybe a technical limitation with popups.
