### ISSUE TITLE
Usability: confusing user experience with Alt-Tab switcher in active monitor

### ISSUE THREAD

**Issue by memeplex** [linuxmint/cinnamon#7725]
```
~:: cinnamon --version
Cinnamon 3.8.6
~:: uname -a
Linux carlos 4.14.53-1-MANJARO #1 SMP PREEMPT Tue Jul 3 17:59:17 UTC 2018 x86_64 GNU/Linux
~:: lspci | grep VGA
00:02.0 VGA compatible controller: Intel Corporation 2nd Generation Core Processor Family Integrated Graphics Controller (rev 09)
~:: pacman -Qs video intel
local/xf86-video-intel 1:2.99.917+829+gd7dfab62-1 (xorg-drivers)
    X.org Intel i810/i830/i915/945G/G965+ video drivers
 ```

The current behavior of the alt-tab switcher is confusing when it's configured to be displayed in the active monitor (that is, the default configuration). The problem is with the definition of active monitor: it's not the monitor with the currently focused window but the monitor where the mouse pointer currently is (except in "mouse focus mode", which is not the default). It's more probable that you're interacting with the focused window, and thus looking at its monitor, than with the window which contains the mouse pointer. In my experience, the Alt-tab switcher is often opened in the monitor I'm not looking at, making the experience very confusing.

**Comment by memeplex** [comment]
>  It's more probable that you're interacting with the focused window, and thus looking at its monitor

To reinforce this, I point out the fact that the alt-tab switcher is invoked using the keyboard so you probably are not concerned with the mouse pointer at that moment (or you would have swicthed windows by other means).

**Comment by memeplex** [comment]
And even if you are using the mouse at the moment chances are that you've clicked somewhere in the window (cause there is not much you can do without clicking) and so focused it.

I might be overlooking something important, but IMO active monitor should be the one containing a the focused window, I'm unable to find any compelling reason to define it as the one containing the mouse pointer.

**Comment by memeplex** [comment]
Sorry I'm quoting the mutter documentation but AFAICS there is no equivalent for muffin.

I verified the definition of current monitor is what I had assumed:

https://developer.gnome.org/meta/stable/MetaScreen.html#meta-screen-get-current-monitor

> Gets the index of the monitor that currently has the mouse pointer.

If you're interested I could submit a PR doing something like the following:

1. get the current workspace from the screen
2. iterate over its windows
3. get the screen for the window with focus
4. if there is no focused window, default to screen.current_monitor (as now)

**Comment by memeplex** [comment]
Oh, maybe this from `global.display`:

https://developer.gnome.org/meta/stable/MetaDisplay.html#meta-display-get-focus-window

> Get our best guess as to the "currently" focused window (that is, the window that we expect will be focused at the point when the X server processes our next request).

Assuming it's also implemented in muffin.

That said, a new option could be added or this could be just a redefinition of "active monitor". As I've argued before I would just redefine it because I fail to see how using the mouse pointer criterion could be better (more intuitive, less surprising) than the current focused window criterion in any possible scenario (in which there is a focused window at all, of course).

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
