### ISSUE TITLE
Cinnamon Nemo -- Enable Renaming of "My Computer"

### ISSUE THREAD

**Issue by rjrich** [linuxmint/Cinnamon#7727]
```
 * Cinnamon version (cinnamon --version) = 3.8
 * Distribution - Linux Mint 19
 * Graphics hardware and driver - Nvidia GTX 1080Ti, Driver 390.67
 * 32 or 64 bit - 64 bit
 ```

**Issue**
Cannot rename "My Computer" in the navigation pane of Nemo.

**Steps to reproduce**
Persistent "feature". Not a bug.

**Expected behaviour**
Would like to be able to right-click and rename "My Computer" to a name of my choosing, such as "Computer", "File System", or the computer name of the computer.

**Other information**
None.

**Comment by JosephMcc** [comment]
Thanks for the request. We'll keep that in mind. I'm not sure this will get much priority. It's just more code complication for a very minimal gain.

**Comment by rjrich** [comment]
Joseph,

Thank you for replying to my request.

Perhaps it would be easier if the Cinnamon/Nemo developers could agree to
change the name of "My Computer" to something else (such as "Computer" or
"Devices") rather than making the renaming user-selectable.

"My Computer" sounds too much like a Microsoft Windows thing! ;=)

Thanks.

Best regards,

Rudy

**Comment by NikoKrause** [comment]
If you really want this to change, your biggest chances will be by creating a Pull Request.
Your suggestion then has to be reviewed and will either be accepted or declined.

I'll give you a jump start:
https://github.com/linuxmint/nemo/blob/master/src/nemo-places-sidebar.c#L738

**Comment by rjrich** [comment]
Thanks for the suggestion.

Unfortunately, I do not know enough about pull requests to request one or
to contribute code for the feature I am requesting for Cinnamon/Nemo.

I would hope that there would be some interest in changing the name of "My
Computer" in the navigation pane to something less reminiscent of Microsoft
Windows. I would suggest simply "Computer", "Devices", or "File System".

Thank you.

Sincerely,

Rudy Richardson

**Comment by NikoKrause** [comment]
There's a pen symbol at the top of the file; the tooltip says "Edit this file".

**Comment by rjrich** [comment]
Hi,

To which file are you referring? Is this about creating a pull request, or
is it about editing a configuration file for Nemo?

Thanks.

Rudy

**Comment by NikoKrause** [comment]
https://github.com/linuxmint/nemo/blob/master/src/nemo-places-sidebar.c#L738
