### ISSUE TITLE
Usability: new window in dual monitor configuration appears where less expected

### ISSUE THREAD

**Issue by memeplex** [linuxmint/cinnamon#7728]
```
~:: cinnamon --version
Cinnamon 3.8.6
~:: uname -a
Linux carlos 4.14.53-1-MANJARO #1 SMP PREEMPT Tue Jul 3 17:59:17 UTC 2018 x86_64 GNU/Linux
~:: lspci | grep VGA
00:02.0 VGA compatible controller: Intel Corporation 2nd Generation Core Processor Family Integrated Graphics Controller (rev 09)
~:: pacman -Qs video intel
local/xf86-video-intel 1:2.99.917+829+gd7dfab62-1 (xorg-drivers)
    X.org Intel i810/i830/i915/945G/G965+ video drivers
 ```

This is closely related to https://github.com/linuxmint/Cinnamon/issues/7725

Again, I think the problem is that active monitor is defined in a very unintuitive way, since most of the time the user sees as active the monitor with the focused window, not the one where he/she "forgot" the mouse pointer. So launching an app tends to make its window appear where it's less expected, since it's located where the mouse pointer is, not where focus is.

Why not adding a switch to the windows configuration: "active monitor is the one with focused window"? I still fail to see why someone would prefer the current behavior but in any case the backwards compatible option would be there.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
