### ISSUE TITLE
Per display scaling - Mint 19

### ISSUE THREAD

**Issue by dusansusic** [linuxmint/Cinnamon#7729]
* Cinnamon version (cinnamon --version):
Cinnamon 3.8.7

 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
Mint 19
 * Graphics hardware *and* driver used
Nvidia 1050
 * 32 or 64 bit
64Bit

We don't have a way to have different scaling on mixed monitors setup. Eg: My laptop has 4K display and I have external monitors with 1920x1200 Resolution. I am unable to set scaling factor only on external monitor without breaking (and making things a lot smaller) on 4K monitor.

**Steps to reproduce**
Attach monitor which has lower resolution.

**Expected behaviour**
Have per monitor scaling possibility.

**Comment by JosephMcc** [comment]
Thanks for the request but this isn't currently possible under X. It's one of the selling points of Wayland.
