### ISSUE TITLE
[Bug] "User interface scaling" does not scale minimize, maximize, and exit icons until reboot

### ISSUE THREAD

**Issue by sanecito** [linuxmint/Cinnamon#7735]
```
 * Cinnamon version (cinnamon --version): 3.8.7
 * Distribution - Mint 19
 * Graphics hardware *and* driver used: Advanced Micro Devices, Inc. [AMD/ATI] Hawaii PRO [Radeon R9 290/390] / "Kernel driver in use: radeon"
 * 64 bit
 ```

**Issue**
When changing "User interface scaling" in General > Desktop Scaling (i.e. Normal -> Double or vice versa) the initial scaling value is preserved for the minimize, maximize, and exit icons on the top right of any window until system reboot

For example, when switching from "Normal" to "Double" on a 4K monitor, said icons are still significantly small and don't seem to change in size while other iconography changes to be more readable. The same happens when going from "Double" to "Normal"; the minimize, maximize, and exit icons remain large while everything else shrinks.

**Steps to reproduce**
(Optional) Use a 4K monitor or one that would be best with "Double" to better see the effect
1. Modify "User interface scaling" from "Normal" to "Double" or from "Double" to "Normal" while keeping your eyes focused on the minimize, maximize, and exit icons
2. Note if they did not change
3. If they did not change, reboot your computer and it should now match the scale with all other iconography

**Expected behaviour**
Minimize, maximize, and exit icons change scale appropriately with other icons, etc

**Other information**
Using a dual monitor setup; a 22" 1080p and a 27" 4K. Not sure if this would have any bearing, but FYI.

**Comment by JosephMcc** [comment]
This is a known issue and can affect other various parts. A reboot is generally needed. Just a Cinnamon restart. Thanks for reporting this but we have other similar issues already opened around this same things.
