### ISSUE TITLE
[Enhancement Request] Make 'Auto' smart enough to scale dual+ monitors independently or allow for manual adjustment via GUI

### ISSUE THREAD

**Issue by sanecito** [linuxmint/Cinnamon#7737]
```
 * Cinnamon version (cinnamon --version): 3.8.7
 * Distribution - Mint 19
 * Graphics hardware *and* driver used: Advanced Micro Devices, Inc. [AMD/ATI] Hawaii PRO [Radeon R9 290/390] / "Kernel driver in use: radeon"
 * 64 bit
 ```

**Issue**
There is currently no way in a dual monitor setup to use "Double" for say, a 4K monitor, and "Normal" for say, a 1080p monitor. When using "Double" it applies to both monitors in a dual monitor setup which may be ideal for the 4K monitor, but not the 1080p monitor.

**Steps to reproduce**
1. Have a multi monitor setup wherein in the set of monitors there exists some monitor A with a max resolution different than some monitor B
2. Set to "Double"
3. Note how "Double is applied to both monitors which may make windows in a 4K monitor look nice, but windows in a 1080p monitor oversized

**Expected behaviour**
Proposed solutions:
1. 'Auto' can scale monitors independently. #7735 should be resolved before this as Auto does not seem to recognize and scale 4K monitors appropriately. Auto would recognize different monitors in a dual+ monitor setup may support different max resolutions and set 'Normal' or 'Double' scaling values accordingly
2. Move "Desktop Scaling" / "User interface scaling" to "Display" settings and have the "User interface scaling" dropdown between "Resolution" and "Rotation". Similar to how Resolution and Rotation have values dependent on upon the relevant, selected monitor, User interface scaling would also be separated by monitor. And as a bonus the locality of having "User interface scaling" under "Display" is arguably better than having it under "General".

Solution one assumes it's preferable to have a single manipulated value regardless of monitors. Solution two empowers the user to adjust as they best see fit and improves locality of this setting. There may be some third solution wherein there is a master toggle flipped to do a apply 'Auto', 'Normal', etc to all monitors to allow for a master type value or multiple independent values.

**Other information**
N/A

**Comment by JosephMcc** [comment]
It's not possible to scale monitors separately under X. It's one of the selling points of Wayland. Doing a search here for open and closed issue should turn up plenty of info.
