### ISSUE TITLE
Wine menus missing in Mint 19; fix included with report

### ISSUE THREAD

**Issue by CottonEaster** [linuxmint/Cinnamon#7738]
```
 * Cinnamon version (cinnamon --version) 3.8.7
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 19, upgraded in-place from 18.3
 * 32 or 64 bit: 64
 ```

**Issue**

There are several reports on the Internet (e.g. [here](https://old.reddit.com/r/linuxmint/comments/8wlhxx/is_the_wine_windows_program_loader_missing_from/)) of Wine menus disappearing from MintMenu and from Nemo's 'open with'.

The _fix_ - well, it worked for me and for at least one other person - is adapted from [here](https://linuxconfig.org/install-wine-on-ubuntu-18-04-bionic-beaver-linux) and goes as follows.

```
sudo dpkg --add-architecture i386 
wget -qO- https://dl.winehq.org/wine-builds/Release.key | sudo apt-key add -
sudo apt-add-repository 'deb http://dl.winehq.org/wine-builds/ubuntu/ artful main'
sudo apt-update && sudo apt upgrade
sudo apt dist-upgrade
```

I found I did not need the last step, but perhaps some might.

The problem seems to owe ultimately to Ubuntu.

**Comment by leigh123linux** [comment]
Wine is responsible for it's own desktop files and isn't something we can fix within cinnamon code.
