### ISSUE TITLE
Icon & thumbnail view in alt-tab: thumbnail is too small

### ISSUE THREAD

**Issue by memeplex** [linuxmint/Cinnamon#7739]
```
~:: cinnamon --version
Cinnamon 3.8.6
~:: uname -a
Linux carlos 4.14.53-1-MANJARO #1 SMP PREEMPT Tue Jul 3 17:59:17 UTC 2018 x86_64 GNU/Linux
~:: lspci | grep VGA
00:02.0 VGA compatible controller: Intel Corporation 2nd Generation Core Processor Family Integrated Graphics Controller (rev 09)
~:: pacman -Qs video intel
local/xf86-video-intel 1:2.99.917+829+gd7dfab62-1 (xorg-drivers)
    X.org Intel i810/i830/i915/945G/G965+ video drivers
 ```

I find the thumbnail too small in at least two senses:

1. The window containing it is quite bigger than the thumbnail itself, which is not only aesthetically questionable but also a waste of that window space.

2. The size makes it difficult to discern important features of the window and so to identify it. Many windows tend to look as a tainted light or dark blob.

Maybe the size is ok for the thumbnail-only alt-tab switcher, but in the icon+thumbnail switcher only just one thumbnail is visible at the same time and it gets a dedicated window, which is already big enough as pointed out in 1 above.

Here is a screenshot:

![screenshot from 2018-07-15 11-53-28](https://user-images.githubusercontent.com/2845433/42735250-093955c4-8827-11e8-9fe2-0da36a670116.png)

**Comment by JosephMcc** [comment]
Your theme is affecting that. There is no where near that much empty space on the Mint-Y themes.

**Comment by memeplex** [comment]
Ok, it's manjaro default theme (a variation of adapta), I will report it, could you give me some hint where to look at in the stylesheets?

**Comment by smurphos** [comment]
Mmm, I see similar sized  thumbnails in various themes including Mint-Y, Adapta, etc...

![screenshot-screen-2018-07-19-092428](https://user-images.githubusercontent.com/29017677/42930757-c7c1491e-8b35-11e8-967e-9d9e0067a8cc.png)
![screenshot-screen-2018-07-19-092454](https://user-images.githubusercontent.com/29017677/42930758-c7db794c-8b35-11e8-829f-e0e501bee03c.png)
![screenshot-screen-2018-07-19-092514](https://user-images.githubusercontent.com/29017677/42930759-c7f6bd60-8b35-11e8-9b64-1e837a521ede.png)

**Comment by memeplex** [comment]
I reported it to adapta tracker and they closed the issue saying it's not the theme:

https://github.com/adapta-project/adapta-gtk-theme/issues/712#issuecomment-406143531

**Comment by JosephMcc** [comment]
@smurphos I have no idea why you have all that extra padding around the thumbnails in Mint-Y. I have nothing like that here. Unless this is being affected by the screen res.

**Comment by smurphos** [comment]
It might be - I'll try to find a HDMI cable later and plug into my TV to see if it makes a difference.

**Comment by smurphos** [comment]
Does beg the question what would it look like on a 4K display? I suspect that the thumbnails may be cut-off by the width of the box - I think it's fixed at 256px in Mint Y?

Would be nice if the thumbnails scaled with the display resolution.
