### ISSUE TITLE
In move mode (alt-f7) shift-arrows behavior seems completely broken

### ISSUE THREAD

**Issue by memeplex** [linuxmint/cinnamon#7740]
```
~:: cinnamon --version
Cinnamon 3.8.6
~:: uname -a
Linux carlos 4.14.53-1-MANJARO #1 SMP PREEMPT Tue Jul 3 17:59:17 UTC 2018 x86_64 GNU/Linux
~:: lspci | grep VGA
00:02.0 VGA compatible controller: Intel Corporation 2nd Generation Core Processor Family Integrated Graphics Controller (rev 09)
~:: pacman -Qs video intel
local/xf86-video-intel 1:2.99.917+829+gd7dfab62-1 (xorg-drivers)
    X.org Intel i810/i830/i915/945G/G965+ video drivers
 ```
Maybe it's me that's not getting it, but the typical shift-arrows behavior that tries to move a window to align it with other ones, so as to visit less overlapping locations, works in an erratic way in Cinnamon.

It's hard to describe it since I don't really get the pattern, if any, but you can try it for yourself and in a few seconds you will see what I mean. Nevertheless, here is an example showing some of the weirdness:

1. In an empty workspace open two, say, terminals. Move one of them a bit to the left so that they are not perfectly aligned.
2. Select the one at the right and enter alt-f7 mode.
3. Press shift-left and the window will probably move to the right or to the bottom right of the screen.
4. Now press shift-left again and the window won't move.
5. Now press shift-right and the window keeps moving to the right, out of the screen.

In general:

* Windows quickly go out of the screen.
* Movement direction doesn't fit arrow direction.
* Doing the opposite action (say pressing left after right) doesn't revert to the previous state.
* It's hard to map actions to outcomes.

**Comment by icarter09** [comment]
@memeplex are you still experiencing this issue?

**Comment by Vahan86** [comment]
@icarter09, can we close the issue?
