### ISSUE TITLE
mint 19 wont install at all and kills  your dualboot system in the process

### ISSUE THREAD

**Issue by macro82** [linuxmint/Cinnamon#7741]
```

 * Distribution - Mint 19
64 bit
 ```

**Issue**

the installer crashes .grub2 won´t install and kills your dualboot system also in the process if your unlucky

https://forums.linuxmint.com/viewtopic.php?f=46&t=273377
https://forums.linuxmint.com/viewtopic.php?f=90&t=273058
https://forums.linuxmint.com/viewtopic.php?f=46&t=272991

**Steps to reproduce**
just try to install it

**Comment by clefebvre** [comment]
Hi @macro82,

Install without being connected to the Internet.

There are two issues at play, one on our side (which we fixed but we'll need to respin ISOs for it not to affect new installations) and one upstream in Ubuntu (which we're waiting on before respinning the ISOs).

**Comment by JosephMcc** [comment]
Closing this since it's answered and it isn't a Cinnamon issue. A better place for general Linux Mint issues is here: https://github.com/linuxmint/linuxmint/issues
