### ISSUE TITLE
Strange black blocks on background

### ISSUE THREAD

**Issue by rmwiseman** [linuxmint/Cinnamon#7743]
```
 * Cinnamon 3.8.7
 * Mint 19
 * Haswell-ULT Integrated Graphics Controller with the default driver that comes with Mint
 * 64 bit
 ```

**Issue**

It appears that if I plug in my external monitor before booting, everything is fine, but if I add it afterwards I (sometimes) get strange black blocks obscuring part of the background.  These only appear on my main (laptop) screen, it seems.

The location and presence of the black bits vary, sometimes flickering very rapidly, sometimes remaining static.  Sometimes the black is just where the window shadow should be.  Moving the mouse and especially moving windows around causes the black to change size and location.

I managed to get some screen grabs, which I've attached.  (I cropped them to remove my external monitor since there were no perceptible issues on there.  I also redacted a little content by blurring it.)

**Steps to reproduce**

I'm not sure how easy this is to reproduce, unfortunately, but it happened today and it happened the first time I used Mint 19, having never previously happened (and I've used Mint since release 16 I think).

**Expected behaviour**

Background doesn't have sections blacked out!

**Other information**

I have had issues previously where Mint freezes when an external monitor is connected (where it's in the middle of adjusting itself) but that seems monitor-dependent and hasn't happened for quite a while.

![screenshot from 2018-07-17 08-15-43](https://user-images.githubusercontent.com/10866705/42803483-fe07a2f0-899d-11e8-9d8b-4b72cc1803ba.png)
![screenshot from 2018-07-17 08-14-39](https://user-images.githubusercontent.com/10866705/42803484-fe249978-899d-11e8-87ef-b43cb1956783.png)
![screenshot from 2018-07-17 08-13-51](https://user-images.githubusercontent.com/10866705/42803485-fe3be240-899d-11e8-82e8-3870729a272e.png)
![screenshot from 2018-07-17 08-13-00](https://user-images.githubusercontent.com/10866705/42803486-fe539f20-899d-11e8-9d50-f3b836bd77f3.png)
![screenshot from 2018-07-17 08-13-27](https://user-images.githubusercontent.com/10866705/42803487-fe6ba232-899d-11e8-807f-c576515f8ccb.png)

**Comment by leigh123linux** [comment]
https://github.com/linuxmint/Cinnamon/issues/7665
