### ISSUE TITLE
feature request - hot corner -> lock screen option

### ISSUE THREAD

**Issue by f3spirit** [linuxmint/Cinnamon#7744]
Hi,
Under "Hot Corners" I would like to have the option to lock the screen.

I use Mint 19

_We have children at the place where I work, so if I go to the printer or something it would be nice to just be able to throw the mouse in one corner of the screen and have the screen locked already._

And is this the right place to make a request for "Hot Corners" or is "Hot Corners" developed elsewhere?

**Comment by leigh123linux** [comment]
Use the 'run command' option.

![screenshot from 2018-07-17 11-03-14](https://user-images.githubusercontent.com/1299302/42810937-1e11f3b2-89b1-11e8-829e-ced6505dcb5d.png)

**Comment by f3spirit** [comment]
Thank you,
it worked as you described
