### ISSUE TITLE
[Feature Request] Option to change mouse click behavior for panel applets

### ISSUE THREAD

**Issue by mfreeman72** [linuxmint/Cinnamon#7746]
```
 * Cinnamon 3.8.8
 * Distribution - Mint 19
 * Graphics hardware *and* driver used: AMD A8 APU (Radeon R5) running on the default open source AMD drivers
 * 64 bit
 ```

**Issue**
Switching from one panel applet drop-down menu to another takes too many clicks.

There used to be a Cinnamon extension (Cinnamon Tweaks by 0dyseus) that remedied this, but it is no longer developed/available and the version that is leftover on his github isn't compatible with the current Cinnamon version. This extension used to allow you to select either the default cinnamon behavior (one click opens a panel drop-down, clicking on another applet closes the drop-down, then you have to click another time to open the second applet's drop-down), the Gnome-like behavior (one click opens a panel drop-down, clicking on another applet closes the drop-down and immediately opens the second applet's drop-down), or the MacOS-like behavior (one click opens a panel drop-down, simply moving the mouse pointer to another applet without clicking closes the first applet's drop-down and opens the second applet's drop-down).

I personally get frustrated by the multiple clicks behavior of Cinnamon, and would like to have all of the above Cinnamon Tweaks click behavior options available natively in Cinnamon instead of having to rely on an extension that may or may not be there the next time Cinnamon gets an upgrade or the extension author gets upset and kills off all of his work (as apparently was the case with 0dyseus' extensions and applets).

**Steps to reproduce**
N/A

**Expected behaviour**
N/A

**Other information**

**Comment by JosephMcc** [comment]
Thanks for the request. It's unlikely you'll see an option for this behaviour. If anything, it would just be a change to how it works in general.
