### ISSUE TITLE
[BUG] Keyboard Backlight indicator is showing a random value

### ISSUE THREAD

**Issue by leonidasv** [linuxmint/cinnamon#7747]
```
 * Cinnamon version (cinnamon --version)
Cinnamon 3.8.6
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
Mint 19
 * 32 or 64 bit
64 bit
 ```

**Issue**

Keyboard Backlight % in Power Manager applet displays a random value (4294967295%) when > 0%.

**Steps to reproduce**

Go to Power Manager applet and try increasing "Keyboard backlight". 

**Expected behaviour**

Value shown should be accurate and ≤ 100%.

![bug](https://user-images.githubusercontent.com/17609157/42915043-063135f4-8aed-11e8-93b9-c815cc39cfe4.png)

**Comment by Vahan86** [comment]
@leonidasv, is this still an issue in Cinnamon 4.2?

**Comment by icarter09** [comment]
We believe this issue is fixed. Please test against the latest Cinnamon version (4.2). 

https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/

**Comment by Vahan86** [comment]
@icarter09, can we close this issue since there is no response from OP?

**Comment by Vahan86** [comment]
@icarter09, can we close this issue since there is no response from OP?
