### ISSUE TITLE
Nemo ignrores view settings

### ISSUE THREAD

**Issue by oldtomdevel** [linuxmint/Cinnamon#7749]
```
 * Cinnamon version 3.8.8
 * Distribution - Mint 19 Cinnamon 64bit
 * Graphics hardware *and* driver used: Intel Corporation HD Graphics 630
 * 64 bit
 ```

**Issue**
In Nemo settings, list view sorted according to names was selected.
However, when Nemo ist started by the menu shortcut "places->Downloads"
this setting is ignored and list view ist sorted according to dates.

**Steps to reproduce**
Nemo settings as described
(of course, individual folder settings are disabled i.e. all folder should open as set).
Start Nemo by the menu shortcut places->Downloads.

**Expected behaviour**
Nemo should always respect its settings.

**Other information**

**Comment by JosephMcc** [comment]
This should be reported here: https://github.com/linuxmint/nemo/issues
