### ISSUE TITLE
Nemo does not adapt icon sizes in icon view

### ISSUE THREAD

**Issue by oldtomdevel** [linuxmint/Cinnamon#7750]
```
 * Cinnamon version: 3.8.8
 * Distribution: Mint 19
 * Graphics hardware *and* driver used: Intel Corporation HD Graphics 630
 * 64 bit
 ```

**Issue**
I have defined a new mime type and a corresponding icon
in ~/.local/share/mime and ~/.local/share/icons , respectively.
However, my own icon is available in one size only.
Generally, Nemo shows the corresponing files in a correct manner
i.e. with correct file type and with correct icon.
In list view or compact view, Nemo adapts the icon to the applied 
zoom factor. That is, the icon is shown in the adequate size
even though there is only one definition file for the icon in one
single size. Therefore, Nemo zooms in or out the icon.
However, this does not work in Nemo's icon view. In that
view, Nemo shows the icon always in the size it was originally defined
i.e. Nemo does not adapt the icon to the current zoom factor.
But Nemo definitely has the ability to adapt the icon size 
as you can see in list view and compact view. 

**Steps to reproduce**
Define a new local mime type.
Define a corresponding new local icon
with one icon size only e.g. in ~/.local/share/icons/hicolor/32x32/mimetypes .
Update mime cache and icon cache.
Check Nemo's views.

**Expected behaviour**
Nemo should always adapt the icon size to the shown zoom factor
i.e. this should be true in each view.

**Other information**

**Comment by JosephMcc** [comment]
This should be reported here: https://github.com/linuxmint/nemo/issues
