### ISSUE TITLE
Cinnamon sound settings show non-existing SPDIF device

### ISSUE THREAD

**Issue by oldtomdevel** [linuxmint/Cinnamon#7751]
```
 * Cinnamon version: 3.8.8
 * Distribution: Mint 19
 * Graphics hardware *and* driver used: Intel Corporation HD Graphics 630
 * 64 bit
 ```

**Issue**
There are two issues which are probably connected with each other:
1. The Cinnamon sound settings always list the device "digital output SPDIF"
(originally a text in German, but here translated back to English).
However, the machine does not have such a device.
2. When I plug in an USB sound device (an Avantree Leaf Bluetooth/apt-x adapter
for use with apt-x headphones, the adapter registers and works like an USB
sound card), the Cinnamon sound settings list that device twice - namely as 
an additional analog device as expected and additionally as an SPDIF device. 
In fact, the USB device has nothing to do with SPDIF.
There is no difference between these two device entries, both work the same way. 
However, the same USB device on the same computer, but with Linux Mint 
Cinnamon 17.3 64bit, showed the device only with one entry as expected,
namely as an additional analog device.

**Steps to reproduce**
Look at devices list in sound settings.
Use an additional USB sound device.

**Expected behaviour**
1. Cinnamon should list only those output devices which really exist.
In case that the chip set offers an interface that is not used by the computer
and Cinnamon is not able to detect these circumstances, there should be an
option for the user to hide a device in the list.
2. This should be particularly true for additional USB sound devices.

**Other information**

**Comment by leigh123linux** [comment]
Almost all sound cards have digital output capability, to confirm run

```
aplay -l
```

I agree with you that describing all digital outputs as SPDIF isn't correct

**Comment by oldtomdevel** [comment]
This is not the point.

* Cinnamon sound settings usually show only the existing devices, in fact only the connected devices e.g. analog sound output is listed only when something is plugged in.
On my machine a "SPDIF device" is listed as build-in device even though there is no such device available. Even if this should be a translation issue (my machine runs with German language) and the device should be a general internal digital interface, this should not be listed as it is not available at all.

* Referring to the Avantree Leaf USB sound device, the command "aplay -l" lists only one additional device as expected when the USB device is plugged in. Only the cinnamon sound settings list two additional devices, one named "analog output Avantree Leaf" and the other named "digital SPDIF Avantree Leaf". This is not sensible, in particular bearing in mind that this device has no futher settings but is just a plug-in device for connecting a bluetooth/apt-x headset.

From my point of view, there is an issue with the cinnamon sound settings.

**Comment by collinss** [comment]
Cinnamon sound settings merely gets this information from pulse audio through cvc (cinnamon-volume-control: a fork of gvc which provides some convenience functions and an introspection layer allowing it to be accessed from multiple programming languages). We don't maintain pulse audio, so I'm not sure if there's anything we can do about that. Do you see the same issue with other desktops (i.e. Gnome shell)?

**Comment by leigh123linux** [comment]
@collinss  I agree with you that it isn't something that can or should be fixed within cinnamon.
