### ISSUE TITLE
Could not update ICEauthority on boot

### ISSUE THREAD

**Issue by Appalbarry** [linuxmint/Cinnamon#7753]
```
 * Cinnamon version (cinnamon --version) 3.8.7
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Linux Mint 19 Cinnamon
 * Graphics hardware *and* driver used Unsure
 * 32 or 64 bit 64 bit
Note: This system has run Mint for several years with no problems of any sort.

 ```
**Issue**
System will no longer boot. Displays dialog saying: 
**Could not update ICEauthority file /home/<user>/.ICEauthority**

**Steps to reproduce**
This was a  fresh install of v 19, perhaps two weeks old.
1) Copying files from secondary HDD to USB stick.
2) Nemo freezes part way through copy.
3) Opened System Monitor and killed the Nemo process.
4) Nemo would not open or launch
5) Rebooted system by choosing "Restart" from the shut down menu.
6) System did not boot to GUI, instead stopping with the "Could not update ICEauthority" Dialog.

**Expected behaviour**
System would reboot and Nemo would open normally

**Other information**
I have tried every suggested fix for this, including:
> chown username:groupname /home/username/.ICEauthority
> chmod 0600 /home/username/.ICEauthority

> sudo chown username:groupname /home

And  number of variations on those.
I have tried these from both the CTRL-ALT_F1 and CTRL-ALT_F2 terminal instances.
I have also tried booting from the GRUB recovery and booting from a previous kernel version.

None of these has worked.

**Comment by smurphos** [comment]
Take a look here - https://forums.linuxmint.com/viewtopic.php?p=1491794#p1491794

**Comment by Appalbarry** [comment]
Thanks , but I did work through all off those with no success.

Barry

**Comment by leigh123linux** [comment]
This issue  is nothing to do with the cinnamon code.
