### ISSUE TITLE
Improve "Snap"-logic (Windows Snap-like, if possible)

### ISSUE THREAD

**Issue by exetico** [linuxmint/cinnamon#7755]
_I tried to find the right place to sumbit feature-requests, so i hope that this is the right place! Aya._

**Request**
I would like to see the "Window"-snap feature improved, so it acts like the [Windows Snap](https://support.microsoft.com/en-us/help/4027324/windows-snap-your-windows)-assistant (launched with Windows 7, if i remember correctly).

I'm a huge fan of the Windows Snap-like logic, cause i allow me to:
- More windows around/resize them
- More them to a different monitor

This is done with the <kbd>⊞ Win</kbd>-key + <kbd>← / → / ↑ / ↓</kbd> (aka. Windows/Super-key + Arrow Left/Right/Up/Down).

Currently i need to manage multiple shortcuts, in order to resize windows at my desktop, and to move them to another monitor.

**Why?**
Well... I can surely manage the two shortcuts in my memory,  but now that my desktop-environment (at work) is powered by Windows, i would love to see that the build-in feature in Linux Mint worked just a bit "smarter". I sadly can't format my work desktop-environment :-1:

Let me know if i need to add other details. I'm on the latest version of Mint with Cinnamon.

**Comment by exetico** [comment]
Hi,

I thought that is was OK with my first description - but, sure! I'll give it another go.

Current Windows Snap:
Use Win/Super-key and arrows to both snap window to edge of screen, snapping it and move windows to other screens. (_If the window is next to the edge, by pressing fx. the right-key, the window will jump to the next screen_)

Current Cinnamon-shortcuts is very "limited", cause i need to use more shortcuts, to make the movements. So my wish was to have a "all-in-one" shortcut with some logic, what worked like the Windows Snap-feature, allowing me to use a single shortcut, and not multiple ones.

Is that just a bit better :-D? I'm not missing specific options - i'm looking for improvements of the existing ones.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
