### ISSUE TITLE
2x USB Sound Devices - 1 isnt usable (not visible), cant switch between them on the run

### ISSUE THREAD

**Issue by Delikt** [linuxmint/cinnamon#7756]
```
 * Cinnamon version (cinnamon --version)
Cinnamon 3.8.8
 * Distribution - (Mint 19)
 * Graphics hardware *and* driver used
Mesa 18.1.4 - AMD R9 Fury
 64 bit
 ```

**Issue**

Not sure im right place here (if not im sorry)

i have a problem with 2 USB Sound Devices.I want to use them on the same time to switch between them if i need. I have a 2.1 Speaker Device and a Headset Device all two plugged via USB (cause my integrated Sound card is crap)... So the Problem is i need to restart my Computer after plug In my Headset then it works and i see it under my Cinnamon Sound settings. But my other USB Device (Speakers) are gone there and also so in pavucontrol (what i installed to test). i can find the Device with aplay -l (its listed)... how can i enable all 2 on startup? I try other USB Ports, Turn Speakers ON/OFF reboot etc.
If i unplug the Headset and reboot.. my Speaker Device is back and working normally... any ideas?

**Steps to reproduce**
Plug-In 2 USB Sound devices

**Expected behaviour**
Switch them via "Sounds" from the System Settings if i need them ( its pulseaudio or?)

**Comment by Delikt** [comment]
`pulseaudio
E: [pulseaudio] pid.c: Daemon already running.
E: [pulseaudio] main.c: pa_pid_file_create() fehlgeschlagen.

aplay -l
**** Liste der Hardware-Geräte (PLAYBACK) ****
Karte 0: HDMI [HDA ATI HDMI], Gerät 3: HDMI 0 [HDMI 0]
  Sub-Geräte: 1/1
  Sub-Gerät #0: subdevice #0
Karte 0: HDMI [HDA ATI HDMI], Gerät 7: HDMI 1 [HDMI 1]
  Sub-Geräte: 1/1
  Sub-Gerät #0: subdevice #0
Karte 0: HDMI [HDA ATI HDMI], Gerät 8: HDMI 2 [HDMI 2]
  Sub-Geräte: 1/1
  Sub-Gerät #0: subdevice #0
Karte 0: HDMI [HDA ATI HDMI], Gerät 9: HDMI 3 [HDMI 3]
  Sub-Geräte: 1/1
  Sub-Gerät #0: subdevice #0
Karte 0: HDMI [HDA ATI HDMI], Gerät 10: HDMI 4 [HDMI 4]
  Sub-Geräte: 1/1
  Sub-Gerät #0: subdevice #0
Karte 0: HDMI [HDA ATI HDMI], Gerät 11: HDMI 5 [HDMI 5]
  Sub-Geräte: 1/1
  Sub-Gerät #0: subdevice #0
Karte 1: headset [Sennheiser USB headset], Gerät 0: USB Audio [USB Audio]
  Sub-Geräte: 1/1
  Sub-Gerät #0: subdevice #0
Karte 2: Device [USB Multimedia Audio Device], Gerät 0: USB Audio [USB Audio]   <----- the gone one
  Sub-Geräte: 1/1
  Sub-Gerät #0: subdevice #0

**Comment by Vahan86** [comment]
@Delikt, is this still an issue in Cinnamon 4.2?
