### ISSUE TITLE
[Feature Request] Whitelist/blacklist screen rotation positions

### ISSUE THREAD

**Issue by Redsandro** [linuxmint/cinnamon#7758]
```
 * Cinnamon version 3.8.8
 * Distribution - Mint 19
 * Graphics hardware: Intel HD Graphics 620; Driver: i915
 * ThinkPad X1 Yoga 64 bit
 ```

**Issue**

In a car/train/at home, with the *lap*top on your lap, moving your legs to change position so the laptop briefly angles above 20-something degrees triggers the screen to rotate 90 degrees and (hopefully) back again. This causes two near-second black screen moments. It also doesn't play nice with certain games.

**Steps to reproduce**

* Quick-ish-ly rotate the laptop sideways by 25 degrees
  * Observe how screen rotates 90 degrees.

**Feature request**

Like on some Android versions, I'd like the option to indicate which rotations should be allowed/disallowed. E.g. disallow 90 degrees left and 90 degrees right, but allow 180 degrees. This allows the typical 'flipping over' car usage, while preventing the accidental 90 degrees flips.

**Comment by cgarciaq** [comment]
If the lid position in 2-in-1 laptop/tablets would be detected and used, this problem could be avoided. Only rotating when the lid surpasses the 180º (otherwise, there is no sense rotating.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
