### ISSUE TITLE
Screen rotation is too sensitive

### ISSUE THREAD

**Issue by Redsandro** [linuxmint/Cinnamon#7759]
```
 * Cinnamon version 3.8.8
 * Distribution - Mint 19
 * Graphics hardware: Intel HD Graphics 620; Driver: i915
 * ThinkPad X1 Yoga 64 bit
 ```

**Issue**

Screen rotation activates on a metaphorical hairline. 

In a car/train/at home, with the *lap*top on your lap, moving your legs so the laptop briefly angles above 20-something degrees causes the screen to rotate 90 degrees **and not rotate back** when the laptop is horizontal again.

You have to manually rotate the laptop 90 degrees and back again to get the horizontal layout again. I don't know why, but this causes anger.

**Steps to reproduce**

* Quick-ish-ly rotate the laptop sideways by 25 degrees
  * Observe how screen rotates 90 degrees.
* Slow-ish-ly rotate the laptop back to a horizontal position
  * Observe how screen does not rotate back.

**Expected behaviour**

1. Not rotate the screen 90 degrees when the laptop is not even halfway there.
2. When it _is_ rotated 90 degrees, always rotate back in a horizontal position.

**Other information**

Rotating is perfected in Windows so much that Lenovo decided to _remove_ the button on the side that can enable/disable rotation.

I'm sure developers don't do this on purpose. I don't know what the technical construction is that implements this feature, but I'm assuming on some laptops (i.e. the ones that the developers of this feature own) it works better. So since on _some_ laptops it's clearly too sensitive, I think one solution would be to add a sensitivity option similar to the ones you have for mouse speed and mouse sensitivity.

It would also help to disable the 90 degrees rotation and only do 180 degrees rotation. I wrote a suggestion in https://github.com/linuxmint/Cinnamon/issues/7758.

**Comment by leigh123linux** [comment]
Sorry I don't think we can do within the cinnamon source code to fix your issue, try reporting it against iio-sensor-proxy

https://github.com/hadess/iio-sensor-proxy/issues
