### ISSUE TITLE
Fails to start with more than one X screen (AKA. Zaphod Mode)

### ISSUE THREAD

**Issue by lvella** [linuxmint/Cinnamon#776]
This bug, also present in Gnome 3 an Mutter (seen on Linux Mint 13), prevents the session from starting up properly when there is more than one X11 screen. Gnome's [bug #648156](https://bugzilla.gnome.org/show_bug.cgi?id=648156) has a full discussion on it and a proposed solution.

It seems that Gnome 3 developers felt it was unnecessary to support multiple X screens, since it is much easier to setup a desktop spanning through multiple displays using a single screen and xrandr. Illustrating this mindset, when I complained about the problem, someone in Gnome 3 IRC replied: "Why is the current solution not enough for you?"

But, as it is my case and the situation of the people who complained on bug #648156, multiple screens are useful beyond simply extending the desktop, and I use my second screen just to watch movies (I don't want my desktop on my TV). Following these special case scenarios, and facing the fact that it would be very hard do make Gnome 3 (and I assume the same holds for Cinnamon) to work with more than one screen, the proposed solution was to make the window mananager (mutter in their case, and muffin in our case) manage only one screen, and ignore the others, so we can do whatever we want with them.

Thus the actual issue here: make Cinnamon and muffin to use only one screen (properly), and ignore the others.

**Comment by JosephMcc** [comment]
Duplicate https://github.com/linuxmint/Cinnamon/issues/2181
