### ISSUE TITLE
[Suggestion] Add momentum to windows dragging

### ISSUE THREAD

**Issue by Simonmicro** [linuxmint/Cinnamon#7760]
Hi,
could you optionally add momentum to windows dragging? So if I throw my window up to the connected projector/screen they will slide a little bit further and (optionally too) dock directly to full- / half- screen mode?
That would be fantastic!
Best regards,
Simonmicro

**Comment by mtwebster** [comment]
This is a neat idea (I've actually thought about similar things in the past) but unfortunately, it would require an extraordinary amount of programming for little more than a neat effect.

It's not that the concept of intertial or momentum - whatever you'd like to call it - would be difficult to put into code (though hardly simple, either) but that this behavior would require us to work *against the grain* of much of the existing window management code and rules.

This is really something that would need to be planned for from the ground floor, not bolted on much, much later.
