### ISSUE TITLE
~/.local/share/icons path ignored by System Parameters theme settings

### ISSUE THREAD

**Issue by trochdewei** [linuxmint/Cinnamon#7761]
```
 * Cinnamon 3.8.7
 * Fedora 28
 * Card: Intel HD Graphics 620 driver: i915
 * 64 bit
 ```

Icon themes placed in ~/.local/share/icons does not show up in system parameters, but those in ~/.icons do

**Steps to reproduce**: place icon theme folder in ~/.local/share/icons

**Expected behavior**: ~/.local/share/icons path should not be ignored

I didn't try, but probably other folders ignored too (~/.local/share/themes, ~/.local/share/fonts)

**Comment by mtwebster** [comment]
We still look in ~/.themes and ~/.icons instead, I guess we missed that memo.

**Comment by vladimir-didenko** [comment]
Question: should this fix work with gtk2 applications? Because everything works fine except gtk2 that don't see themes from ~/.local/share/themes

**Comment by mtwebster** [comment]
Ah I forgot about gtk2 - I think it predates the whole .local thing.  You can try to make ~/.themes and ~/.icons a symlink of their .local/share equivalents.
