### ISSUE TITLE
Lock screen wont respond

### ISSUE THREAD

**Issue by Xenios91** [linuxmint/Cinnamon#7762]
```
 * Cinnamon version (3.6.7)
 * Distribution - (Mint 18.3)
 * Nvidia 9800GTX  xserver-xorg-video-nouveau 1:1.0.12-1build2
 *64 bit
 ```

**Issue**

Cannot get the login text field to appear from the lock screen

**Steps to reproduce**

If the system comes out of sleep mode or comes out of screen saver, the system will not show the text field to log back in when the mouse or keyboard has an event

**Expected behaviour**
The login text field should appear

**Other information**
System completely up to date as of July 21 2018

**Comment by Xenios91** [comment]
Further investigation shows it appears to be related to the graphics driver, when using thew nvidia proprietary driver, the issue goes away.

**Comment by leigh123linux** [comment]
Please file the issue against the screensaver

https://github.com/linuxmint/cinnamon-screensaver/issues
