### ISSUE TITLE
Stuck menu

### ISSUE THREAD

**Issue by neyesamu5** [linuxmint/Cinnamon#7764]
```
 * Cinnamon 3.8.8
 * Linux Mint 19
 * Intel Corporation Mobile 945GM/GMS, 943/940GML Express Integrated Graphics Controller
 * 32 bit
*Issue* 
In the menu I put a letter, I delete it and the results are stuck



**Steps to reproduce**

Put a letter

**Expected behaviour**

Stuck

**Other information**
None

**Comment by mtwebster** [comment]
Are there any warnings or errors in `~/.xsession-errors` when this happens?  Can you upload that file (or the relevant part at least) using dpaste or pastebin?

**Comment by smurphos** [comment]
Hi, I can reproduce this on Mint 19, Cinnamon 3.8.8 & 18.3 Cinnamon 3.6.7 (with stock theme).

There's no ./xsession-error output produced. Screen cast is from 3.8.8

![screencast-2018-07-23-073950](https://user-images.githubusercontent.com/29017677/43061091-aeb0493e-8e4b-11e8-830a-4aef2e5c2741.gif)
