### ISSUE TITLE
Cinnamon menu editor: when deleting an item, the window jumps back to the top . .

### ISSUE THREAD

**Issue by ghost** [linuxmint/cinnamon#7765]
. . which is a pain if one needs to delete several items next to each other (if they are some way down the list). I am unsure whether the jumping is intended - or at least known - behaviour, in which case this is a feature request; else it is bug report.

```
 * Cinnamon version (cinnamon --version) 3.8.8
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 19

 ```

**Issue**

Please see above.

**Steps to reproduce**

Open the menu editor. (I don't think it matters how.) Delete an item some way down the list.

**Expected behaviour**

No jumping!

**Comment by JosephMcc** [comment]
One of the devs is working an a rework of the menu editor at the moment. Not sue if this is still a problem in his branch. @collinss

**Comment by collinss** [comment]
I can't test that yet. It's a little bit too broken right now. I'll test it when I get it all put back together enough.

**Comment by icarter09** [comment]
@collinss can this ticket be closed?

**Comment by collinss** [comment]
Since the original reporter doesn't seem to be on github any more, I'll close it. If someone else has the same issue, they can open a new one.
