### ISSUE TITLE
Support advanced kbd configuration with either xmodmap or xkb

### ISSUE THREAD

**Issue by norbusan** [linuxmint/Cinnamon#7768]
```
 * Cinnamon version (cinnamon --version): 3.6.7
 * Distribution - Debian/unstable
 * Graphics hardware *and* driver used: nvidia 390.67
 * 64 bit
 ```

**Feature request**

While the current keyboard configuration is helpful in some ways, it does not allow for more specific configurations. I for example am using a Japanese keyboard and I want to remap `Hiragana_Katakana` to `Mode_switch`, including some other changes.

All the above changes can easily be done with a delayed Startup script that calls xmodmap, *BUT* all the configuration get lost during suspend/resume cycle, or any editing of the keyboard settings via the GUI.

Would it be possible to add to the GUI configuration a set of xmodmap style lines that are applied everytime the keyboard layout is reset? Maybe specific for the selected layout would be a plus, too.

Thanks a lot for consideration

Norbert

**Steps to reproduce**

- change keyboard mapping with xmodmap
- suspend and resume
- keyboard mapping is lost

**Expected behaviour**

- keyboard mapping is preserved

**Comment by leigh123linux** [comment]
Can you reproduce with cinnamon-3.8.x as your version is EOL.

**Comment by norbusan** [comment]
Indeed, after upgrading to Debian/experimental version of cinnamon (3.8) it seems to be fixed, or at least happening only more rarely. I will re-open or open new ticket if I see a consistent behavior. Thanks
