### ISSUE TITLE
Screen Brightness keeps Lowering Itself -> Cannot unlock

### ISSUE THREAD

**Issue by stellarpower** [linuxmint/cinnamon#7769]
```
 * Cinnamon version 3.8.8
 * Distribution - Tara
 * Graphics hardware *and* driver used - Using i7 internal graphics, can;t see any proprietary drivers
 * 32 or 64 bit - AMD64
 ```

**Issue**
In Cinnamon, if I change my brightness it keeps being lowered by one level until the screen is shut off. I don't know if this happens in response to a lack of activity or not as it continues regardless. Normally I can increase brightness and continue however after the screen locks I am unable to raise the brightness again and have had to killswitch several times, losing work.

**Steps to reproduce**
Update all packages (as of 23/07/18)
Leave the machine inactive for a while or change the brightness (I still haven't isolated the exact cause)
The brightness keeps being lowered every two minutes or so

Optionally leave the computer to lock and it is not unlockable. I can't change VT either.
In addition to this it seems that shutting the lid on my laptop is not triggering entering suspension when this used to work on Serena but I will file a separate bug once I know more about that

**Expected behaviour**
The screen should reduce in brightness if the computer is inactive for a few minutes, however should be raised again upon an input event. Only one change in brightness should be observed

Also I suggest allowing the screen brightness keyboard events to bypass the lock screen, and if at all possible, allow use of them in a VT outside of an X session, however I ken this isn't necessarily possible.

**Other information**

My laptop is an MSI GT72 Dragon Edition, I think.

**Comment by CottonEaster** [comment]
I have a somewhat similar problem on Mint 19 x64 Cinnamon, on a ThinkPad X1 Carbon Sixth Generation. What happens is, occasionally - and I have not detected a pattern, nor anything that seems relevant in the logs - on battery the screen brightness suddenty drops by 5%, and does not go back unless and until I tell it to, i.e. using the computer does not restore the previous brightness. Nor does the amount of brightness lost correspond to my 'dim on inactive' setting (which is enabled).

**Comment by stellarpower** [comment]
This is the output from dbus-monitor:

    signal time=1549673824.668868 sender=org.freedesktop.DBus -> destination=:1.100 serial=2 
    path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameAcquired
       string ":1.100"
    signal time=1549673824.668929 sender=org.freedesktop.DBus -> destination=:1.100 serial=4 
    path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameLost
       string ":1.100"
    
    
    method call time=1549673876.051550 sender=:1.43 -> destination=:1.39 serial=903 
    path=/org/cinnamon/SettingsDaemon/KeybindingHandler; 
    interface=org.cinnamon.SettingsDaemon.KeybindingHandler; member=HandleKeybinding
       uint32 48
    method call time=1549673876.051909 sender=:1.39 -> destination=:1.29 serial=192 
    path=/org/cinnamon/SettingsDaemon/Power; interface=org.cinnamon.SettingsDaemon.Power.Screen; 
    member=GetPercentage
    method return time=1549673876.051919 sender=:1.39 -> destination=:1.43 serial=193 
    reply_serial=903
    method return time=1549673876.059504 sender=:1.29 -> destination=:1.39 serial=212 
    reply_serial=192
       uint32 9
    method call time=1549673876.059951 sender=:1.39 -> destination=:1.29 serial=194 
    path=/org/cinnamon/SettingsDaemon/Power; interface=org.cinnamon.SettingsDaemon.Power.Screen; 
    member=StepUp
    signal time=1549673876.096738 sender=:1.29 -> destination=(null destination) serial=213 
    path=/org/cinnamon/SettingsDaemon/Power; interface=org.cinnamon.SettingsDaemon.Power.Screen; 
    member=Changed
    method return time=1549673876.096750 sender=:1.29 -> destination=:1.39 serial=214 
    reply_serial=194
       uint32 14
       int32 0
    method call time=1549673876.097054 sender=:1.39 -> destination=:1.43 serial=195 
    path=/org/Cinnamon; interface=org.Cinnamon; member=ShowOSD
       array [
          dict entry(
             string "icon"
             variant             string "display-brightness-symbolic"
          )
          dict entry(
             string "level"
             variant             int32 14
          )
          dict entry(
             string "monitor"
             variant             int32 0
          )
       ]
    method call time=1549673876.097247 sender=:1.43 -> destination=:1.29 serial=904 
    path=/org/cinnamon/SettingsDaemon/Power; interface=org.cinnamon.SettingsDaemon.Power.Screen; 
    member=GetPercentage
    method call time=1549673876.097705 sender=:1.43 -> destination=:1.29 serial=905 
    path=/org/cinnamon/SettingsDaemon/Power; interface=org.cinnamon.SettingsDaemon.Power.Screen; 
    member=GetPercentage
    method return time=1549673876.101514 sender=:1.43 -> destination=:1.39 serial=906 
    reply_serial=195
    method call time=1549673876.102396 sender=:1.43 -> destination=:1.39 serial=907 
    path=/org/cinnamon/SettingsDaemon/KeybindingHandler; 
    interface=org.cinnamon.SettingsDaemon.KeybindingHandler; member=HandleKeybinding
       uint32 48
    method return time=1549673876.102605 sender=:1.29 -> destination=:1.43 serial=215 
    reply_serial=904
       uint32 14
    method call time=1549673876.102652 sender=:1.39 -> destination=:1.29 serial=196 
    path=/org/cinnamon/SettingsDaemon/Power; interface=org.cinnamon.SettingsDaemon.Power.Screen; 
    member=GetPercentage
    method return time=1549673876.102662 sender=:1.39 -> destination=:1.43 serial=197 
    reply_serial=907
    method return time=1549673876.109401 sender=:1.29 -> destination=:1.43 serial=216 
    reply_serial=905
       uint32 14
    method return time=1549673876.119419 sender=:1.29 -> destination=:1.39 serial=217 
    reply_serial=196
       uint32 14
    method call time=1549673876.119695 sender=:1.39 -> destination=:1.29 serial=198 
    path=/org/cinnamon/SettingsDaemon/Power; interface=org.cinnamon.SettingsDaemon.Power.Screen; 
    member=StepUp
    signal time=1549673876.153147 sender=:1.29 -> destination=(null destination) serial=218 
    path=/org/cinnamon/SettingsDaemon/Power; interface=org.cinnamon.SettingsDaemon.Power.Screen; 
    member=Changed
    method return time=1549673876.153161 sender=:1.29 -> destination=:1.39 serial=219 
    reply_serial=198
       uint32 19
       int32 0
    method call time=1549673876.153450 sender=:1.39 -> destination=:1.43 serial=199 
    path=/org/Cinnamon; interface=org.Cinnamon; member=ShowOSD
       array [
          dict entry(
             string "icon"
             variant             string "display-brightness-symbolic"
          )
          dict entry(
             string "level"
             variant             int32 19
          )
          dict entry(
             string "monitor"
             variant             int32 0
          )
       ]
    method call time=1549673876.154471 sender=:1.43 -> destination=:1.29 serial=908 
    path=/org/cinnamon/SettingsDaemon/Power; interface=org.cinnamon.SettingsDaemon.Power.Screen; 
    member=GetPercentage
    method call time=1549673876.154947 sender=:1.43 -> destination=:1.29 serial=909 
    path=/org/cinnamon/SettingsDaemon/Power; interface=org.cinnamon.SettingsDaemon.Power.Screen; 
    member=GetPercentage
    method return time=1549673876.156217 sender=:1.43 -> destination=:1.39 serial=910 
    reply_serial=199
    method return time=1549673876.159904 sender=:1.29 -> destination=:1.43 serial=220 
    reply_serial=908
       uint32 19
    method return time=1549673876.169948 sender=:1.29 -> destination=:1.43 serial=221 
    reply_serial=909
       uint32 19
    
Seems that the origin is an invocation of a keybinding, not just a change of the brightness, and the process owning service 1.46 is cinnamon itself. This happens on a vanilla user account with the default settings applied.

Any steps on what more to debug from here would be appreciated.

Cheers

**Comment by icarter09** [comment]
Moss :) ...are you still experiencing this issue?

**Comment by stellarpower** [comment]
May need a bit of time to check - my display cable is loose so I've got no
screen right now. Some idiot put the power lines straight over the data
bus!! Ahahah, ohhhh deeear!

**Comment by icarter09** [comment]
@stellarpower I'm not able to reproduce this issue on my laptop. Let me know if there's anything you want me test or try out.
