### ISSUE TITLE
Sound amplification has no effect

### ISSUE THREAD

**Issue by ntblade** [linuxmint/cinnamon#7770]
```
 * Cinnamon version 3.8.8
 * Distribution - Mint 19 clean install
 * Graphics hardware Intel Corporation 2nd Generation Core Processor Family Integrated Graphics Controller
 * 64 bit
 ```

**Issue**

Sound, Settings, Amplification
Slider has no effect on output volume
Worked OK in 18.3

**Steps to reproduce**

**Expected behaviour**

**Other information**

**Comment by claudiux** [comment]
This slider has no direct effect on the output volume. It allows you to increase the volume up to the limit you set. Example: If you chose 120%, you can increase the volume up to 120% of the nominal volume of your sound card.

**Comment by icarter09** [comment]
@claudiux any update or status change on this ticket?

**Comment by claudiux** [comment]
@icarter09 This is not an issue, but the normal use of this slider. You can close it.

**Comment by ntblade** [comment]
Actually,
This is still the case in 19.2. Sliding the slider between 0 and 150% makes
no difference. If it does nothing why have it?

>

**Comment by claudiux** [comment]
@ntblade Adjust your volume to 75% using the "sound" applet. Drag this slider down to 50%. Then try increasing the volume using the "sound" applet. What happens?
