### ISSUE TITLE
Changing password with encrypted home directory is dangerous

### ISSUE THREAD

**Issue by laex333** [linuxmint/cinnamon#7772]
```
 * Cinnamon version 3.8.8 (cinnamon --version)
 * Distribution - (Mint 19)
 * 64 bit
 ```

**Issue**
I am an experienced computer user but admittedly no Linux guru, but still, I should definitely be able to do simple stuff in a simple way and without shutting myself out of my own system...:

If you chose to encrypt your dome directory during LM installation and later want to change your password, you cannot do that in Cinnamon (without command line and knowledge). See forum post: https://forums.linuxmint.com/viewtopic.php?f=90&t=274114

**Steps to reproduce**
Have home directory encrypted, go to LM user account details and change your password, log out and try to log in again >> impossible!
Obviously your user password has been changed correctly, but as the encryption password has not been changed ("Signature not found in user keyring..."), you cannot log in anymore...

_Changing username via terminal and $ passwd works, but this cannot be expected to be known and done by the average user._ UPDATE: Logging out and back in did work, but rebooting did result in very same "Signature not found..." loop!

**Expected behaviour**
Changing your password should definitely not lock you out of your own system IMHO.

This is dangerous for non gurus and at least very painful for experienced users like myself, so please find another solution here!

**Comment by xenopeek** [comment]
I can't reproduce this issue on a fully updated fresh install of Linux Mint 19 Cinnamon 64-bit (v2 ISO). It was installed with home directory encryption. Not entire disk encryption.

I tried two things:

1. Open Account Details from the menu, change password and then logout and log back in. That works. Restarted the machine and could still log in with the new password.
2. Open Account Details again and change the password to something else. Then without logging out restart the machine and could still log in with the newer password.

I may be an issues specific only to upgrading in place or something else may be in play. From what specific version of Linux Mint 18.x did you upgrade?

**Comment by laex333** [comment]
Thanks for looking into this, as I still don't a way to change my password!

I had LM 18.3 in its latest/updated version running before (but maybe my setup started already in LM 17, not sure anymore). I did a clean reinstall (via live usb stick) with formatting of the system partition but without altering/formatting the /home partition (to keep my data...)...

How can I be of assistance?
