### ISSUE TITLE
Screensaver segmentation faults when input received while active

### ISSUE THREAD

**Issue by mklauber** [linuxmint/Cinnamon#7773]
```
 * Cinnamon version (cinnamon --version): Cinnamon 3.8.8
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...): Linux Mint 19 Tara (upgraded from 18.3)
 * Graphics hardware *and* driver used: Macbook Pro 11,3 screen with  Mesa drivers
 * 32 or 64 bit: 64 bit
 ```

**Issue**
`cinnamon-screensaver` segmentation faults.  After fault, Lock screen button and keyboard combination does not work.  Running `cinnamon-screensaver` starts the process, and clicking the button or key combination locks the screen until the mouse is moved or keyboard touched.  running `cinnamon-screensaver --debug` results in the below.  Running `cinnamon-screensaver` as sudo does not segmentation fault, but does not respond to lock screen requests.  Running `sudo cinnamon-screensaver-command --lock` locks the screen, but it unlocks without prompting for passwords.  

**Steps to reproduce**
Uncertain.

**Expected behaviour**
The screen locks.

**Other information**

```
$ cinnamon-screensaver --version
cinnamon-screensaver 3.8.2
```

```
$ cinnamon-screensaver --debug
Debug mode active
Cinnamon Screensaver support not found in current theme - adding some...
Trying to connect to logind...
org.gnome.ScreenSaver is gone from the session bus
org.mate.ScreenSaver is gone from the session bus
Starting screensaver...
Successfully using logind
Found 1 Xinerama screens on display :0
Monitor 0 is 0,0 2560 x 1600
Cinnamon Screensaver compiled without Solaris Xinerama support
Scale factor of 1 applied.  Monitor 0 is 0,0 2560 x 1600
Stage.update_geometry - new backdrop position: 0, 0  new size: 2560 x 1600
monitorView: updating view state
monitorView: show wallpaper
manager: locking after delay ('lock-delay')
manager: user activity, waking
authClient: attempting to initialize
authClient: initialized
manager: locked, raising unlock widget
monitorView: updating view state
monitorView: show wallpaper
Segmentation fault


```

**Comment by leigh123linux** [comment]
Please file the issue against the screensaver

https://github.com/linuxmint/cinnamon-screensaver/issues
