### ISSUE TITLE
Update Manager welcome screen buttons not discoverable on small screen

### ISSUE THREAD

**Issue by alexsconway** [linuxmint/Cinnamon#7774]
```
 Cinnamon 3.8.8
 Mint 19
 MSI 135DX, Intel® GMA 3150 10" 1024 x 600
 32bit
 ```

**Issue**
The help and ok buttons on the update manager welcone screen are below the bottom of my monitor.
The gui is disabled except for these two buttons.
I cannot re-size the window small enough to be able to drag them into view.
The only way to view them is to plug in a bigger monitor.

**Expected behaviour**
the gui should resize or re-arrange itself so that all the buttons are visible

**Comment by collinss** [comment]
First of all, this is not a Cinnamon issue. The update manager is a separate project. Second, in the release announcement found [here](https://blog.linuxmint.com/?p=3597) it says that one of the system requirements for this version of Mint is "1024×768 resolution (on lower resolutions, press ALT to drag windows with the mouse if they don’t fit in the screen)". Per your listed specs above you are operating below the minimum system requirements, and so you have to settle for the provided work-around.
