### ISSUE TITLE
External monitor issues (not easily recognized, at detach locked session becomes unlocked)

### ISSUE THREAD

**Issue by andreabellitto** [linuxmint/cinnamon#7778]
```
 * Cinnamon version Cinnamon 3.8.7 from ppa:embrosyn/cinnamon 
 * Distribution - Ubuntu 18.04
 * Graphics hardware *and* driver used
MSI laptop GE-60 2PE
Kernel 4.17.x and Kernel 4.18.0_rc6
Intel HD4000 + Geforce GTX 860m, latest intel and nvidia driver from ubuntu repo and ppa:graphics-drivers/ppa
 * 64 bit
 ```

**Issue**
If I connect a monitor to the HDMI port the pc does't detect it, i need to start the process
`/usr/lib/x86_64-linux-gnu/cinnamon-settings-daemon/csd-xrandr &`
from terminal in order to made the pc detect the screen attachment. After that I can use the monitor normally, but if I lock the cinnamon session (password insert prompt screen with user session active) and then I remove the HDMI cable from the PC then the lock screen disappears and i can see desktop and I can open desktop files, but I can't switch between desktop workspaces (I have multipe ones).....
The first bug (display not detected) is annoing but not particular serious, but the session unlock one is so far serious!!!!

**Steps to reproduce**
- Start the pc without external screen attached
- Login into the user session
- Attach an external screen to the HDMI (and made it recognized by the workaround described before)
- Lock the user session and watch at the password prompt
- Unplug the HDMI cable
- You will see the lockscreen disappearing and desktop come up

**Expected behaviour**
First of all the screen should be detected without need of workarounds, second but most important a locked session MUST not be unlocked simply by unplug the HDMI cable

**Other information**

**Comment by icarter09** [comment]
@andreabellitto are you still experiencing this issue?

**Comment by Vahan86** [comment]
@icarter09, can we close the issue since there is no response from OP?
