### ISSUE TITLE
Touchpad settings reset after resuming from suspend enough times

### ISSUE THREAD

**Issue by flansuse** [linuxmint/cinnamon#7779]
```
 * Cinnamon version: 3.8.8
 * Distribution: Linux Mint 19 64-bit
 ```

**Issue**
After so many suspend-then-resume, the touchpad settings will randomly reset. 

**Steps to reproduce**
Use the system long enough, suspending and resuming, and eventually the touchpad settings will reset. If I disable the touchpad entirely in Settings > Mouse and Touchpad > Touchpad, it will re-enable itself eventually without warning. Not only annoying, but also causes mistakes in any application I am using.

**Expected behaviour**
When I disable the touchpad under Settings > Mouse and Touchpad > Touchpad, it should remain disabled permanently.

**Other information**
I never experienced this issue with Mint 18, 18.1, 18.2, and 18.3.

**Comment by Vahan86** [comment]
@flansuse, is this still an issue for you with Cinnamon 4.4?

**Comment by flansuse** [comment]
I must say, so far so good on Cinnamon 4.4.8.
