### ISSUE TITLE
Too many outdated or malfunctioning applets and exstensions the desktop will crash

### ISSUE THREAD

**Issue by xzj8b3** [linuxmint/Cinnamon#7781]
Cinnamon 3.8.8
Fedora 28 64 bit
Intel Haswell-ULT Integrated Graphics driver: i915 v: kernel 
Advanced Micro Devices [AMD/ATI] Mars LE [Radeon HD 8530M / R5 M240] driver: radeon 
radeon resolution: 1366x768~60Mesa DRI Intel Haswell Mobile v: 4.5 Mesa 18.0.5 

Applets and extensions too little updated, the desktop due to them crashes as soon as a malfunction is enabled forcing the utilities to a forced closure!!!!!

It would have been a nice desktop if they also had a serious support!!!!!
![p_20180729_142707_sres](https://user-images.githubusercontent.com/26720956/43366894-e2f0bdde-9344-11e8-8941-4eeeb920e986.jpg)

Would be handy a link to get more detailed information about aplets etc and report more quickly any problems with them!!!!!

**Comment by JosephMcc** [comment]
Report issues with the extensions in one of these places:
https://github.com/linuxmint/cinnamon-spices-applets
https://github.com/linuxmint/cinnamon-spices-themes
https://github.com/linuxmint/cinnamon-spices-desklets
https://github.com/linuxmint/cinnamon-spices-extensions

**Comment by xzj8b3** [comment]
@JosephMcc  Of course I do, but there will always be problems if they are updated every 4 months when it goes well!!!!
