### ISSUE TITLE
No brightness control in cinnamon-settings power

### ISSUE THREAD

**Issue by Hilyxx** [linuxmint/Cinnamon#7782]
Hello

I don't have brightness control in cinnamon-settings power. However the brightness applet works fine.

![capture d ecran du 2018-07-29 15 05 00](https://user-images.githubusercontent.com/21991448/43366974-e708da7c-9345-11e8-9694-f21d6fc1118d.png)

Linux mint 18.3
Cinnamon 3.6
Kernel 4.15.0-29
Macbook pro 2012

**Comment by Hilyxx** [comment]
It's not a linux mint bug but with xorg deb package.
xorg.conf was located in usr/share/doc instead of usr/share/X11/xorg.conf.d/ ????

**Comment by mtwebster** [comment]
This was fixed for 3.8: https://github.com/linuxmint/Cinnamon/commit/3cf2304f34742d0f2d267f3589556e9ba96a30b5#diff-bbda7e400d548d62418e6ba860693791

I'm not sure how xorg.conf is related - there usually isn't a file named 'xorg.conf' there - instead multiple separate files related to different i/o devices.

**Comment by Hilyxx** [comment]
I don't know.. I had a xorg.conf file in usr/share/doc path.... I put it in Xorg.conf.d folder, added line "Option "RegistryDwords" "EnableBrightnessControl=1" and brightness section appeared in power settings.
