### ISSUE TITLE
Cursor disappears after switch user and back

### ISSUE THREAD

**Issue by JonJFineman** [linuxmint/Cinnamon#7784]
```
 * Cinnamon version (cinnamon --version); Cinnamon 3.0.7
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...); Linux Mint 18 Sarah
 * Graphics hardware *and* driver used; Card: Intel Sky Lake Integrated Graphics
 * 32 or 64 bit; 64
 ```
**Issue**
After switching to another user and back the mouse cursor disappears. The mouse is still functional and the menus work. After locking and unlocking the screen the mouse cursor comes back.

**Steps to reproduce**
Control-Alt-Delete Switch user and log in. Then Control-Alt-Delete to switch back to first user and log in. The mouse cursor is not present. Via the menu lock screen, then unlock, the cursor will re-appear.

**Expected behaviour**
Cursor should not disappear.

**Other information**
$ inxi -Fxxrzc0
System:    Host: xyz Kernel: 4.4.0-130-generic x86_64 (64 bit gcc: 5.4.0)
           Desktop: Cinnamon 3.0.7 (Gtk 3.18.9-1ubuntu3.3) dm: mdm
           Distro: Linux Mint 18 Sarah
Machine:   Mobo: Intel model: NUC6i5SYB v: H81131-504
           Bios: Intel v: SYSKLi35.86A.0042.2016.0409.1246 date: 04/09/2016
CPU:       Dual core Intel Core i5-6260U (-HT-MCP-) cache: 4096 KB
           flags: (lm nx sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx) bmips: 7199
           clock speeds: min/max: 400/2900 MHz 1: 499 MHz 2: 506 MHz
           3: 499 MHz 4: 1138 MHz
Graphics:  Card: Intel Sky Lake Integrated Graphics
           bus-ID: 00:02.0 chip-ID: 8086:1926
           Display Server: X.Org 1.18.4 drivers: intel (unloaded: fbdev,vesa)
           Resolution: 1920x1080@60.00hz
           GLX Renderer: Mesa DRI Intel Iris Graphics 540 (Skylake GT3e)
           GLX Version: 3.0 Mesa 11.2.0 Direct Rendering: Yes
Audio:     Card Intel Sunrise Point-LP HD Audio
           driver: snd_hda_intel bus-ID: 00:1f.3 chip-ID: 8086:9d70
           Sound: Advanced Linux Sound Architecture v: k4.4.0-130-generic
Network:   Card-1: Intel Ethernet Connection I219-V
           driver: e1000e v: 3.2.6-k bus-ID: 00:1f.6 chip-ID: 8086:1570
           IF: eno1 state: down mac: <filter>
           Card-2: Intel Wireless 8260
           driver: iwlwifi bus-ID: 01:00.0 chip-ID: 8086:24f3
           IF: wlp1s0 state: up mac: <filter>
Drives:    HDD Total Size: 4500.9GB (27.5% used)
           ID-1: /dev/sda model: Crucial_CT500MX2 size: 500.1GB serial: 154210D45783
           ID-2: USB /dev/sdb model: My_Passport_25E2 size: 4000.8GB serial: 575832314437364637444A58-0:0
Partition: ID-1: / size: 46G used: 18G (41%) fs: ext4 dev: /dev/sda2
           ID-2: /boot size: 9.1G used: 742M (9%) fs: ext4 dev: /dev/sda1
           ID-3: /home size: 297G used: 175G (63%) fs: ext4 dev: /dev/sda7
           ID-4: swap-1 size: 16.00GB used: 0.01GB (0%) fs: swap dev: /dev/sda5
RAID:      System: supported: N/A
           No RAID devices: /proc/mdstat, md_mod kernel module present
           Unused Devices: none
Sensors:   System Temperatures: cpu: 59.0C mobo: 27.8C
           Fan Speeds (in rpm): cpu: N/A
Repos:     Active apt sources in file: /etc/apt/sources.list.d/google-chrome.list
           deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
           Active apt sources in file: /etc/apt/sources.list.d/official-package-repositories.list
           deb http://packages.linuxmint.com sarah main upstream import backport
           deb http://archive.ubuntu.com/ubuntu xenial main restricted universe multiverse
           deb http://archive.ubuntu.com/ubuntu xenial-updates main restricted universe multiverse
           deb http://archive.ubuntu.com/ubuntu xenial-backports main restricted universe multiverse
           deb http://security.ubuntu.com/ubuntu/ xenial-security main restricted universe multiverse
           deb http://archive.canonical.com/ubuntu/ xenial partner
Info:      Processes: 271 Uptime: 9 days Memory: 7759.3/15937.4MB
           Init: systemd v: 229 runlevel: 5 default: 2 Gcc sys: 5.4.0
           Client: Shell (bash 4.3.481 running in gnome-terminal-) inxi: 2.2.35

**Comment by leigh123linux** [comment]
Feel free to reopen if you can reproduce the issue in Mint 19 cinnamon-3.8.x as your version is EOL.

**Comment by JonJFineman** [comment]
So what, Linux Mint is abandoning the promise of long term support? Which Mint 18 is/was under???

**Comment by jaszhix** [comment]
@JonJFineman That's for security updates, which comes with the Ubuntu LTS. We don't have the resources to support every Cinnamon release within a five year period.
