### ISSUE TITLE
Ability to remove borders on specific windows

### ISSUE THREAD

**Issue by someguyss** [linuxmint/cinnamon#7785]
Is it possible to get this as a feature? Either a hotkey or simply being able to right click the titlebar and click 'remove' or similar would be enough (it wouldn't have to be saved as a permanent preference, only last until the window was closed or until another hotkey was pressed). Workarounds like Maximus are not convenient as either they do this universally for all windows, for all maximised windows or require you to sit down and list all the windows you want this done for.

This would be extremely useful for anyone who wants to play games as fullscreen games and Linux do **not** mix well (significant issues with both dual monitors and stealing the keyboard for a start). Regardless of that even on Windows, where these issues are not present, borderless windowed gaming is desirable in and of itself, in fact there exists a program specifically to provide it where the game does not.

Believe it or not the capability to do this easily is more or less a make-or-break issue for me and likely for anyone else who wants to make serious use of Cinnamon for gaming.

**Comment by someguyss** [comment]
>Have you tried Alt-F shortcut to full screen the active window?
This only works on firefox rather than games and still leaves a small bar along the top of the game.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
