### ISSUE TITLE
Icons not showins is systray

### ISSUE THREAD

**Issue by bonej079** [linuxmint/Cinnamon#7787]
```
 * Cinnamon version 3.8.8
 * Distribution - Mint 19
 * Graphics hardware *and* driver used: Nvidia + proprietary driver
 * 64 bit
 ```

**Issue**

The icons for the following applications do not show in the Systray:

Dropbox
Stacer
Jetbrains Toolbox

**Steps to reproduce**

Install the applications. 
On a restart, the application icons are missing in the systray. However, they still turn up in the systray. If you hover over the area where they should appear, a tooltip is shown with the application name. But you have to hover to find out which one it is.

**Expected behaviour**

The icons should appear in the system tray always.

**Other information**

**Comment by JosephMcc** [comment]
Thanks for reporting, but a search for the systray or you application names will turn up multiple issues already opened about this. Including this one: https://github.com/linuxmint/Cinnamon/issues/481
