### ISSUE TITLE
MintMenu: add to panel does not ask *which* panel

### ISSUE THREAD

**Issue by ghost** [linuxmint/cinnamon#7789]
```
 * Cinnamon version (cinnamon --version): 3.8.8
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 19
 * Graphics hardware *and* driver used
 * 32 or 64 bit: 64
 ```

**Issue**

MintMenu: add to panel does not ask *which* panel

**Steps to reproduce**

Have two panels. Find an app in Mint Menu. Use the 'add to panel' option. Hope the app gets pinned to the panel you want.

**Expected behaviour**

The user should be asked which panel to use - though I suppose this is a feature request, not a bug report.

**Other information**

**Comment by leigh123linux** [comment]
FTR can you use the proper names as mintmenu has nothing to do with cinnamon

https://github.com/linuxmint/mintmenu

It would make it easier to understand you if you just called it 'menu applet' !!

**Comment by CottonEaster** [comment]
@leigh123linux 

Thank you. So the report I filed pertains to something called 'the menu applet' - which is indeed part of Cinnamon - and not to 'MintMenu', which is part of Mate. Right.

**Comment by CottonEaster** [comment]
I add the following. When I add an applet, on my Mint 19.1 Cinnamon PC, which has a top and a bottom panel, the applet gets added to the top panel and . . _the right-hand side of the screen_, where a right panel would be were I to have one (which I don't), flashes.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
