### ISSUE TITLE
Mint Menu extends off the top of the screen

### ISSUE THREAD

**Issue by CottonEaster** [linuxmint/Cinnamon#7790]
```
 * Cinnamon version (cinnamon --version) 3.8.8.
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 19
 * Graphics hardware *and* driver used: Intel UHD Graphics 620; 3.0 Mesa 18.0.5
 * 32 or 64 bit: 64
 ```

**Issue**

![image](https://user-images.githubusercontent.com/9998846/43624872-de044c50-96e1-11e8-992c-75b8533b6c69.png)

**Steps to reproduce**

Possibly have my font and/or DPI settings? (Still, that does not really explain away the problem.) I can supply details upon request.

**Expected behaviour**

I should be able to see the top of the window. Or so it seems to me.

**Other information**

Screen resolution: 2560x1440

DPI: high.

I think that some time ago I reported a similar problem - about, that time, the _bottom_ of the menu missing. However, I have failed to locate that old bug report, I am afraid.

**Comment by JosephMcc** [comment]
It wasn't hard to find: https://github.com/linuxmint/Cinnamon/issues/6110
It's the exact same cause.
