### ISSUE TITLE
items restored from trash go to wrong directory when dragging using windows

### ISSUE THREAD

**Issue by illumilore** [linuxmint/Cinnamon#7794]
```
 * Cinnamon version (cinnamon --version)Cinnamon 3.8.8
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) 19
 * Graphics hardware *and* driver used          nvidia
 * 32 or 64 bit  64
 ```

**Issue**

Open up trash:/// in nemo and a 2nd nemo window. 
Drag item in trash to the 2nd nemo window.
Instead of dragged item being restored to the location in the 2nd window, it will instead be restored to its original location.

**Steps to reproduce**

**Expected behaviour**

For the dragged item to be moved to the directory path in the 2nd window it was dragged to from the trash.

**Other information**

**Comment by leigh123linux** [comment]
trash:/// is handled by gvfs, it can only restore to the original location, this is the expected behaviour.

**Comment by illumilore** [comment]
It is not expected behaviour for the user to have it act completely differently from all other drag and drop actions
