### ISSUE TITLE
Issue with occasional jerky, erratic touchpad movements

### ISSUE THREAD

**Issue by monerohelp** [linuxmint/cinnamon#7795]
* Cinnamon version 3.8.8
 * Mint 19
 * Intel Corporation UHD Graphics 620
 * 64 bit

Hi all, I am running Linux Mint 19 on my Asus Vivobook laptop (not using proprietary drivers) and I get this occasional issue where the touchpad is very erratic. It's sort of hard to explain... like when I try to move the mouse, sometimes it doesn't respond to the direction I'm moving it or its really jerky, just overall very erratic. It happens several times per day at completely random times but doesn't persist for too long, maybe a couple of minutes. It's not a HUGE issue, but annoying nonetheless. I read on the Linux Mint website under the Mint 19 release notes that there are touchpad issues and their solution is to install synaptics, which I did but the problem is still there. Any ideas on this? Please let me know if there is any additional information that you may need.

**Comment by monerohelp** [comment]
Anybody have some insight on this issue?

**Comment by icarter09** [comment]
@monerohelp are you still experiencing this issue?

**Comment by Vahan86** [comment]
@icarter09, can we close this issue since there is no response from OP?
