### ISSUE TITLE
Cinnamon randomly crashes

### ISSUE THREAD

**Issue by PhoenixStarEclipse** [linuxmint/Cinnamon#7798]
```
 * Cinnamon version: Cinnamon 3.6.6
 * Distribution - Gentoo
 * i7 8700k's integrated graphics card, i915  driver
 * 64 bit
 ```

**Issue**
Cinnamon randomly crashes when clicking on some button or pressing some shortcut like "Delete" to delete some files. After crashing, I'm taken back to the login interface provided by sddm. When I relogin, every program I ran is gone.

**Steps to reproduce**
Unknown.

**Expected behaviour**
Cinnamon should remain running.

**Other information**
[My /var/log/syslog](https://paste.ubuntu.com/p/Q3ctDnk3RB/)

**Comment by leigh123linux** [comment]
Cinammon-3.6.6 is EOL. try 3.8.x instead.
