### ISSUE TITLE
Blank Screen after loading mint Icon

### ISSUE THREAD

**Issue by ShawonPaul** [linuxmint/Cinnamon#7799]
```
 * Cinnamon version (cinnamon --18.1)
 * HP laptop ( Intel core-i3 @2.10GHz, 4 GB Ram) .

 * Dual boot (windows,Linux os ) using GNU GRUB version 2.02~beta2-36ubuntu3.2
 *  64 bit
 ```

**I have installed linux mint 18.1 (64-bit) alongside with windows 10(64-bit). Using 
 Dual boot os using GNU GRUB version 2.02~beta2-36ubuntu3.2

Recently, I can easily boot windows from booting loader. But when i tryied to boot linux mint. After selecting linux mint option ,only linux mint icon shows and loading for sometimes. There won't be no log-in screen for my user. After loading the icon, the screen of my laptop gone to blank. There noting appear in the screen. Only Power Off button from by laptop keyboard can shut down the laptop. 

**

**Steps to reproduce**

**Expected behaviour**

**Other information**

**Comment by JosephMcc** [comment]
Are you using Automatic login? If not and you aren't getting to the login screen, this isn't really a Cinnamon issue.
