### ISSUE TITLE
Taskbar does not move back automatically after remove external monitor

### ISSUE THREAD

**Issue by hxingpax** [linuxmint/Cinnamon#7802]
```

 * Cinnamon version: Cinnamon 3.8.8

 * Distribution: Mint 19 (Tara)

 * Graphics hardware *and* driver used:

            -display
             description: VGA compatible controller
             product: Crystal Well Integrated Graphics Controller
             vendor: Intel Corporation
             physical id: 2
             bus info: pci@0000:00:02.0
             version: 08
             width: 64 bits
             clock: 33MHz
             capabilities: vga_controller bus_master cap_list rom
             configuration: driver=i915 latency=0
             resources: irq:51 memory:a0000000-a03fffff memory:90000000-9fffffff ioport:3000(size=64) memory:c0000-dffff
        -multimedia:0
             description: Audio device
             product: Crystal Well HD Audio Controller
             vendor: Intel Corporation
             physical id: 3
             bus info: pci@0000:00:03.0
             version: 08
             width: 64 bits
             clock: 33MHz
             capabilities: bus_master cap_list
             configuration: driver=snd_hda_intel latency=0
             resources: irq:55 memory:a0c10000-a0c13fff

 * Architecture:        x86_64

 ```

**Issue**

If I move task bar into the other monitor screen when I plug an extra monitor, the task bar will not reset back automatically after I remove the extra monitor.

**Steps to reproduce**

1. Plug an extra monitor

2. Move the task-bar into the screen of the extra monitor

3. Do something

4. Remove the extra monitor

5. Now your task bar is gone, even after you rboot your system.

**Expected behaviour**

The taks bar should move back atomatically after I remove the extra monitor.

**Other information**

My Mint 19 runs on a Macbook, as the dominating mono OS.

**Comment by brownsr** [comment]
That is as intended. Panels on extra monitors are persistent to that monitor definition, so they will reappear if the monitor is replugged.  However I think you may be saying that you only had one panel, you moved it to a secondary monitor, removed that, and hence you were left with no panels on the remaining monitor and that caused you problems.  Is that correct ?  You can recover quite readily by right clicking on the desktop, choosing the desktop settings and then using the back arrow to navigate to the full settings, then choose the panel settings, and add a new one.  Or if you replug the monitor it should show where it was, and then you can move if to the primary monitor before you disconnect it again.

Regards

Simon

**Comment by hxingpax** [comment]
@brownsr Thanks, now my strategy is add an extra panel with only window list for the external monitor screen. It works fine anyway.

@mtwebster Thanks. The probleam for this hacking is, my Macbook has nearly the same target resolution (bigger than 2K but smaller than 4k) screen compare to my eternal monitor, except its physical size is much more smaller. If I set the external monitor as primary, strange resolutions will come up, hard to work with.

**Comment by mtwebster** [comment]
You can disable that strange behavior (sounds like hidpi auto-detection) from cinnamon-settings->General->User interface scaling.  You probably want it at Normal.

**Comment by hxingpax** [comment]
@mtwebster Helpful
