### ISSUE TITLE
Scaling issues after resolution change

### ISSUE THREAD

**Issue by Dmitry-Borodin** [linuxmint/Cinnamon#7804]
```
 * Cinnamon version 3.8.8
 * Distribution - Mint 19
 * Nvidia GTX 1050 mobile - driver 390.48-0Ubuntu3
 * 64 bit
 ```

**Issue**
Changing resolution between 4k-2k leading to scaling issues, until restart of the application
Including tray icons (until cinnamon is restarted)

**Steps to reproduce**
open applications (cinammon, double commander et.c.), change resolution to 2k - face the problem
Restart applications, switch back to 4k - face issues again.

**Expected behaviour**
Windows will reinitialized and scaled after new resolution is applied, like it works in KDE plasma 5.

**Other information**
Screen resolution is per configuration, so when I connect laptop to docking station (where I have 2k external displays and have my laptop resolution 2k) and disconnect back (4k screen) - I'm getting this problem each time.

![bar load](https://user-images.githubusercontent.com/11879032/44089450-1a5165ba-9fc7-11e8-9fc8-76eb28ec3ad9.png)

**Comment by JosephMcc** [comment]
https://github.com/linuxmint/Cinnamon/issues/3194
