### ISSUE TITLE
Broadcom 43142 bluetooth problem with first instalation

### ISSUE THREAD

**Issue by DeTNTonator** [linuxmint/Cinnamon#7805]
```
 * Cinnamon version (3.8.8)
 * Distribution - (Mint 19 Cinnamon) [also 17 and 18 both cinnamon]
 * bcm 43142 driver
 * 64 bit
 ```

**Issue**
& After installing or trying linux on hp pavillon with broadcom 43142 it is unable to use bluetooth, devices are not shown.

**Steps to reproduce**
(on hp pavillon 15 with broadcom 43142).
& Launch/Instal linux.

**Expected behaviour**
& No devices visible in default buetooth and bluetooth manager (bleuman) even if there are in range.
& Neither work after full setup of OS.

**Other information**
& Bluetooth starts working after removing bcmwl-kernel-source, then installing it and rebooting.

**Comment by leigh123linux** [comment]
Report it against the driver
