### ISSUE TITLE
Support the XDG Base Directory Specification

### ISSUE THREAD

**Issue by Soapux** [linuxmint/cinnamon#7807]
https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

Cinnamon 3.8 currently has files in ~/.cinnamon.  Following the spec makes doing backups easier if all configs are in one place.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.

**Comment by nicemicro** [comment]
I just wanted to report this, so instead I just came here to second this suggestion.

**Comment by kuator** [comment]
Bump

**Comment by DNM1008** [comment]
Is there an update to this?
