### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by LogX7** [linuxmint/Cinnamon#7809]
```
 * Cinnamon version 3.8.8
 * Distribution - Mint 19
 * Graphics hardware *and* driver used Nvidia GT740M driver 390
 * 64 bit
 ```

**Feature Request**
window bottom rounded corners

**Comment by leigh123linux** [comment]
This has been requested in the past and rejected.

**Comment by LogX7** [comment]
@leigh123linux  can i know why ?

**Comment by LogX7** [comment]
@collinss  i've been looking this for quite sometime now and yes the bottom rounded corners aren't supported by metacity, that's why i was wondering if i could do something to get it supported

**Comment by collinss** [comment]
Ah, well, I know metacity is included in muffin, but that's about as far as I can help you. I haven't really done anything with it (other than glancing at a metacity theme or 2). I do know that one of the devs has done some work on moving from metacity to gtk for drawing window borders, but I don't know what the status of that is or when/if it's going to make it in. It might provide more options than metacity in that regard as well.
