### ISSUE TITLE
Cinnamon takes a lot of time to login

### ISSUE THREAD

**Issue by jmssil** [linuxmint/Cinnamon#7811]
```
 * Cinnamon version (cinnamon --version): 3.8.8
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...): Linux Mint 19 Tara
 * Graphics hardware *and* driver used: NVIDIA G98 [Quadro NVS 295], nvidia-340
 * 64 bit
 ```

**Issue**

After login, Cinnamon takes 36 seconds to show an empty taskbar and the icons in the bar appear at 44 seconds.

**Steps to reproduce**

Boot Linux Mint. Login. Measure time to taskbar and time to taskbar with icons.

**Expected behaviour**

Show complete taskbar in less than 10 seconds.

**Other information**

$ grep "model name" /proc/cpuinfo 
model name	: Intel(R) Xeon(R) CPU           W3540  @ 2.93GHz
model name	: Intel(R) Xeon(R) CPU           W3540  @ 2.93GHz
model name	: Intel(R) Xeon(R) CPU           W3540  @ 2.93GHz
model name	: Intel(R) Xeon(R) CPU           W3540  @ 2.93GHz

$ grep "MemTotal" /proc/meminfo 
MemTotal:        6085196 kB

**Comment by JosephMcc** [comment]
Thanks for the report. This is something we are always looking to improve. It's also heavily dependent on hardware. On my system, Cinnamon does boot in less than 10 seconds.

**Comment by brownsr** [comment]
It's very heavily hardware dependent.  On my system (3 year old, fairly high spec Dell laptop with M.2 SSD, 2.3GHz i7) it's just under 5 seconds from login.  I strongly suspect that the main determinant is disk accesses

**Comment by jmssil** [comment]
What's your disk performance?

```
$ sudo hdparm -Tt /dev/sda

/dev/sda:
 Timing cached reads:   18366 MB in  1.99 seconds = 9227.01 MB/sec
 Timing buffered disk reads: 382 MB in  3.01 seconds = 126.83 MB/sec
```

**Comment by brownsr** [comment]
/dev/sda:
 Timing cached reads:   21182 MB in  1.99 seconds = 10621.68 MB/sec
 Timing buffered disk reads: 1582 MB in  3.00 seconds = 526.68 MB/sec

**Comment by leigh123linux** [comment]
Cinnamon starts ok here

```
/dev/nvme0n1:
 Timing cached reads:   9882 MB in  2.00 seconds = 4945.77 MB/sec
 Timing buffered disk reads: 3744 MB in  3.00 seconds = 1247.77 MB/sec
```
