### ISSUE TITLE
Any window frame or Nemo pop up menu (right click) opens with incorrect height and stuck on top of screen

### ISSUE THREAD

**Issue by jayypluss** [linuxmint/cinnamon#7812]
**System info** (screenfetch output)
![image](https://user-images.githubusercontent.com/17395606/44314236-cbb44b00-a3ec-11e8-8881-254dcf82bacd.png)

**Issue**
The pop up menu that opens when I right click on any program window frame or anywhere in Nemo file manager size is displayed incorrectly, with no sufficient height to display the options. It only happens in the primary display when I have a secondary HDMI display plugged in. If I disconnect the secondary display it doesn't happen.

Displays configurations: (HDMI resolution: 1920x1080)
![screenshot from 2018-08-19 20-09-46](https://user-images.githubusercontent.com/17395606/44314491-3d41c880-a3f0-11e8-882f-8a66ef7643b2.png)

**Steps to reproduce**
1. Plug in secondary display over HDMI
2. In primary display, right click (open pop up menu) on any program window frame or anywhere in Nemo file manager.

Reproduction:
![peek 2018-08-19 20-38](https://user-images.githubusercontent.com/17395606/44314466-e4723000-a3ef-11e8-8b55-eae49c698d16.gif)

**Expected behaviour**
The pop up menu should open with sufficient size to display at least a few options.

**Other information**
Also I use Tilix and when I open it, the height is also strange when using the two displays, that's the one app I have noticed does that.

![screenshot from 2018-08-19 20-13-59](https://user-images.githubusercontent.com/17395606/44314504-619da500-a3f0-11e8-8a3e-5af927c225cf.png)

**Comment by icarter09** [comment]
@jayypluss are you still experiencing this issue?

**Comment by Vahan86** [comment]
@icarter09, can we close the issue since there is no response from OP?
