### ISSUE TITLE
Desktop icons overlap others.

### ISSUE THREAD

**Issue by ChooChooAl** [linuxmint/Cinnamon#7813]
System:    Host: Mint Kernel: 4.10.0-38-generic x86_64 (64 bit gcc: 5.4.0)
           Desktop: Cinnamon 3.6.7 (Gtk 3.18.9-1ubuntu3.3) dm: lightdm Distro: Linux Mint 18.3 Sylvia
**Issue**
Icons for Home, Trash, and mounted drives overlap other icons I have on the desktop like launchers for games or home folder (Downloads, Pictures etc).
**Steps to reproduce**
Right click desktop and set desktop to align to grid, and vertical.   Add a few launchers etc along the top of the screen.   Go to settings->desktop and enable computer, trash, home and mounted volumes.   When I did this all 3 of them will overlap an already existing launcher.   If you move them and reboot they will overlap again.   Restarting Cinnamon does not make them overlap.
**Expected behaviour**
They should not overlap of course.
**Other information**
This did not happen on 17.3.     This does happen on 19.
I have asked a few people on the alt.os.linux-mint newsgroup and some do and do not have the issue.  I have also tried horizontal alignment and that just changes in which direction the overlap, as left side icons rather than icons above.
![desktop icons overlapping](https://user-images.githubusercontent.com/26556059/44369715-5eb0bc00-a4a5-11e8-9185-5e0c9eb970c5.png)
![desktop settings](https://user-images.githubusercontent.com/26556059/44369716-5eb0bc00-a4a5-11e8-8abe-0124dd0cb49b.png)

**Comment by leigh123linux** [comment]
Please file the issue against nemo

**Comment by ChooChooAl** [comment]
Thanks found issue #1674 that mentions this same issue.  
https://github.com/linuxmint/nemo/issues/1674
