### ISSUE TITLE
Samsung  Printer Drivers

### ISSUE THREAD

**Issue by pinnerite** [linuxmint/Cinnamon#7814]
```
 * Cinnamon version (cinnamon 3.6.7
 * Distribution - (Ubuntu 18.04
 * AMD/ATi HD4350
 * 64 bit
 ```

**Issue**
None of Samsung's UnifiedLinuxDriver installer will start under Cinnamon.
However they do under 'Mate'

**Steps to reproduce**
Go to https://www.bchemnet.com/suldr/suld.html
Then select Samsung Installer.

I tested versions 3.00.65 and 4.01.17 and 1.00.39

on two different ubuntu 18.04 / Cinnamon powered machines

**Expected behaviour**

The welcome screen /dialog  should come up but what comes up is a blank grey screen with only a ttle bar.

**Other information**

**Comment by leigh123linux** [comment]
There is nothing to fix within the cinnamon source code.

What is 'welcome screen /dialog'?

**Comment by pinnerite** [comment]
In desktops other than Cinnamon, starting up the driver install package opos up  welcome window/dialog bearing a welcome message and encouragement to accept the terms etc, before mpving on to the next window-full.

**Comment by leigh123linux** [comment]
running this from a terminal works ok here

```
sudo ./install.sh
```

it has a nasty gtk2 window

![1](https://user-images.githubusercontent.com/1299302/44425815-e1f50f00-a584-11e8-9c73-f0d539e47f7c.jpg)


```
$ inxi -S
System:
  Host: localhost.localdomain Kernel: 4.18.1-300.fc29.x86_64 x86_64 bits: 64 
  Desktop: Cinnamon 3.8.8 Distro: Fedora release 29 (Twenty Nine)
```
