### ISSUE TITLE
Edit "favorites" in Cinnamon menu broken or changed or ?

### ISSUE THREAD

**Issue by RPeters52** [linuxmint/Cinnamon#7815]
Cinnamon 3.8.8+tara
Linux Mint 19  64bit
CPU: Intel© Core™ i3-8100 CPU @ 3.60GHz × 5
Graphics:Intel Corporation Device 3e91 (prog-if 00 [VGA controller])
*-display                 
       description: VGA compatible controller
       product: Intel Corporation
       vendor: Intel Corporation
       physical id: 2
       bus info: pci@0000:00:02.0
       version: 00
       width: 64 bits
       clock: 33MHz
       capabilities: pciexpress msi pm vga_controller bus_master cap_list rom
       configuration: driver=i915 latency=0
       resources: irq:131 memory:a0000000-a0ffffff memory:90000000-9fffffff ioport:4000(size=64) memory:c0000-dfff
 
In the past, I could edit the "favorites" (far left bar) part of the Cinnamon Menu, by mouse-right-click on it.  That action would bring up options like "add" "delete", etc.  Now, absolutely NOTHING happens with a mouse-right-click.   Have you changed how one edits the favorites menu?  I looked fairly carefully and searched on the web and cannot seem to find it....

Everything else seems to to work!  I have edited the "main" menu moving items that were not "placed properly", did not want to be visible, etc.

I just checked on another computer, and mouse-right-click  "fails" for cinnamon 3.6.7/LM18.3.

**Comment by RPeters52** [comment]
OK, I found the add to favorites button...  And I found that I can drag and drop MOST of the buttons on favorites off of that menu.  HOWEVER, I cannot get rid of any of the bottom 3, particularly "logoff".  It is not a big deal, but it seems that one might be able to modify the "bottom 3"

**Comment by jaszhix** [comment]
Those are system buttons, not favorites - so can't be removed. If they could be removed it would make it difficult to log out or reboot through the interface.
