### ISSUE TITLE
Alt+Shift is bound to 'Move window' but does not show up in keyboard shortcuts settings pane

### ISSUE THREAD

**Issue by jameshiew** [linuxmint/Cinnamon#7817]
```
 * Cinnamon version (cinnamon --version)
Cinnamon 3.8.8
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
Manjaro 4.18.3, Ubuntu 18.04
 * Graphics hardware *and* driver used
N/A
 * 32 or 64 bit
64 bit
 ```

**Issue**
Holding down Alt+Shift acts like `Move window`, i.e. like when you hold down Alt+F7, but Alt+Shift does not show up in the bound keyboard shortcuts settings pane.

![screenshot from 2018-08-22 21-58-22](https://user-images.githubusercontent.com/2990876/44490681-e2f67100-a656-11e8-87a2-3293aba22cc3.png)

**Steps to reproduce**
Hold down Alt+Shift and you can move windows.

**Expected behaviour**
Alt+Shift would show up in the keyboard shortcuts settings pane alongside Alt+F7, so that it could be disabled or overridden if desired.

**Other information**

**Comment by mtwebster** [comment]
Alt-<mouse-drag> will allow you to move windows by default.  I think the shift as you're mentioning it is just along for the ride.

You can disable this behavior here (or change the modifier that is used):
![image](https://user-images.githubusercontent.com/262776/44490865-8af74480-a62d-11e8-925a-97d4f239ab78.png)

The difference with the keyboard shortcut you've shown is that that one initiates a move on your behalf - the window sticks to your mouse and you have merely to drag the mouse around.  The alt key method works only as long as you're holding down on the mouse (and is not considered a true keyboard shortcut, in this context.)

If I'm misunderstanding your report please let me know.

**Comment by jameshiew** [comment]
Thanks @mtwebster that was the issue! I wanted to use Alt+Shift+Button1 click to set multiple carets in IntelliJ, after disabling `Special key to move and resize windows` it worked.
