### ISSUE TITLE
Dock on top of fullscreen windows in Linux Mint 19 Cinnamon

### ISSUE THREAD

**Issue by Fainec** [linuxmint/Cinnamon#7818]
```
 * Cinnamon version: 3.8.6
 * Muffin version: 3.8.2
 * Distribution - Linux Mint 19
 * Graphics hardware: Intel Haswell-ULT Integrated Graphics Controller
 * 64 bit
 ```

**Issue**
Bug appears after upgrading from Linux mint 18.3 to Linux mint 19, both were using cinnamon destop.
Dock still over fullscreened window and not under.

**Steps to reproduce**
Get a video on youtube and put this video in fullscreen mode.

**Expected behaviour**
Expect to have fullscreen window without any dock

**Other information**
Tested with multiple docks: dockbarx, docky and cairo-dock

![capture du 2018-08-23 17-15-01](https://user-images.githubusercontent.com/11448695/44534569-6ddb7800-a6f8-11e8-9203-734171950b5c.png)
![capture du 2018-08-23 17-14-22](https://user-images.githubusercontent.com/11448695/44534657-96637200-a6f8-11e8-863a-fae94a8e323b.png)
![capture du 2018-08-23 17-13-59](https://user-images.githubusercontent.com/11448695/44534692-a9764200-a6f8-11e8-88c4-b262104eced8.png)

**Comment by jaszhix** [comment]
These docks are not a part of Cinnamon. Upgrading from 18.3 to 19 upgrades almost every package in your system, and without attaching logs (~/.xsession-errors, /var/log/syslog, etc), its not likely it could be determined if Cinnamon is at cause. Might try opening an issue with the maintainers of the docks you're using.

**Comment by Fainec** [comment]
There is nothing in these logfile.
I think if all the docks that worked perfectly well before upgrading, it's almost sure that it's cinnamon causing the problem. And I'm sure if I test with other docks the bug will remain.

Otherwise, I opened an issue on the dockbarx github and will do the same for the others.

**Comment by jaszhix** [comment]
You could also try testing in another DE and seeing if it occurs there. I don't see how Cinnamon could treat a window differently while full screen, though not really sure how those docks work. What I do know is they're out of process, and can only make setups more complicated and fragile.

**Comment by leigh123linux** [comment]
Report it against the dock program, most of them are unmaintained.
The change to newer gtk3 could have broken them.

**Comment by mtwebster** [comment]
We did make some changes to how fullscreen was handled and I'm looking into them regarding this.  I wouldn't bother with a report to dock devs at this point just yet

**Comment by uberRegenbogen** [comment]
I'm experiencing this without a dock.  Fullscreen apps are under panels and on-top apps.  My workaround is to set the fullscreen app to on-top.  This works, but is a bit of a nuisance.
