### ISSUE TITLE
High memory usage

### ISSUE THREAD

**Issue by tirolel** [linuxmint/Cinnamon#7822]
![screenshot from 2018-08-24 13-25-33](https://user-images.githubusercontent.com/6834419/44582432-ee09e800-a7a1-11e8-84a5-3a3f5cf1bd80.png)
```
 * Cinnamon version --> 3.6.7
 * Ubuntu 16.04
 * 00:02.0 VGA compatible controller: Intel Corporation Sky Lake Integrated Graphics (rev 06)
 * 64 bit
 ```

**Issue**
I have the issue that the ram usage is pretty high.

**Steps to reproduce**

**Expected behaviour**
well everything gets slower(laggy)

**Other information**

**Comment by leigh123linux** [comment]
https://github.com/linuxmint/Cinnamon/issues/6850

**Comment by Micopero** [comment]
https://github.com/linuxmint/Cinnamon/issues/6850?_pjax=%23js-repo-pjax-container#issuecomment-441359988

check this solution out.

**Comment by Micopero** [comment]
> I got a fix for a problem:
> 
> Problem: You get your System slower and slower by time to the extent that is unusable.
> (unless you restart Cinnamon by right clicking the taskbar and choosing Troubleshoot->Restart Cinnamon)
> 
> **My solution:** Was to remove desklets, the only desklets i used was **Analog Chronometer.**
> (restart cinnamon after applying the solution and see)
> 
> However, i like Analog Chronometer a lot as this was the best desktop clock i have ever used, so if the developer can fix the issue that would be very good as this is a really well-done desklet.

Check this solution out, i wrote it on #6850
