### ISSUE TITLE
Desktop switch not animated sometimes

### ISSUE THREAD

**Issue by ManuelSchneid3r** [linuxmint/cinnamon#7826]
```
Cinnamon 3.8.8
Arch
Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz IGP
i915
64 bit
```

**Issue**
The desktop switch is sometimes not animated.

**Steps to reproduce**
Switch desktop

**Expected behaviour**
Nice animations

**Other information**
[Video](https://youtu.be/NSMkup5tiwY)

**Comment by icarter09** [comment]
@ManuelSchneid3r are you still experiencing this issue?

**Comment by Vahan86** [comment]
@icarter09, can we close this issue since there is no response from OP?
