### ISSUE TITLE
cinnamon fails with libatk 2.29.2

### ISSUE THREAD

**Issue by joequant** [linuxmint/cinnamon#7828]
```
 * Cinnamon version (cinnamon --version) 3.8.8
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mageia
 * Graphics hardware *and* driver used Intel
 * 32 or 64 bit 64-bit


 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
 ```
[xsession-errors-1.txt](https://github.com/linuxmint/Cinnamon/files/2337429/xsession-errors-1.txt)

**Issue**
Cinnamon crashes with libatk1.0 2.29.2

**Steps to reproduce**

Update system to use libatk1.0 2.29.2 and cinnamon will crash

**Expected behaviour**

**Other information**

This looks like an upstream issue, but I wanted to report the problem so that people knows what the cause of the crashes are.

https://gitlab.gnome.org/GNOME/atk/issues/1

**Comment by joequant** [comment]
Just more information.  It appears that there was an internal API change in atk 2.29.2 and so using pygobject3 with a gtk compiled against 2.29.1 with a atk built after 2.29.2 will cause pygobject3 to 
fail with gtk objects.  Rebuilding gtk+3.0 against 2.29.2+ atk seems to fix the problem.

**Comment by icarter09** [comment]
@joequant can this ticket be closed? Thanks.
