### ISSUE TITLE
Sub-windows out of screen in Hi-DPI mode

### ISSUE THREAD

**Issue by hxingpax** [linuxmint/cinnamon#7834]
```
 * Cinnamon version 3.8.8

 * Distribution - Mint 19

 * Graphics hardware *and* driver used: 
-display
             description: VGA compatible controller
             product: Crystal Well Integrated Graphics Controller
             vendor: Intel Corporation
             physical id: 2
             bus info: pci@0000:00:02.0
             version: 08
             width: 64 bits
             clock: 33MHz
             capabilities: vga_controller bus_master cap_list rom
             configuration: driver=i915 latency=0
             resources: irq:51 memory:a0000000-a03fffff memory:90000000-9fffffff ioport:3000(size=64) memory:c0000-dffff

 * 64 bit

 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
 ```

**Issue**

I have my macbook pro Mint19 mono-installed.

Very offen, new generated sub-windows got out of screen, as a result I could not see the new generated sub-window, and had to kill the process & restart it.

I thought it might be relative to the Hi-DPI of macbook screen. Then I did some tests, and confirmed that yes it is, It's relative to Hi-DPI.

It also has a relationship with the extra screen (my extra screen is （DELL） U2717D 27) connected with my macbook. This problem will show up only if I turn Hi-DPI on, and have the extra screen connected.

**Steps to reproduce**

* `System settings` -> `General` -> `Desktop scaling` -> `User interface scaling` -> `Double(Hi-DPI)`

* connect the extra screen.

* Do somehing. e.g.
    
    In  Chrome, open a web, `Ctrl+d` bookmark added, click `More`, now you can not see the new generated window which is poped up but out of your screen.

**Expected behaviour**

**Other information**

**Comment by icarter09** [comment]
@hxingpax are you still experiencing this issue?

**Comment by hxingpax** [comment]
I ve sold the Macbook. Seems good on my XPS13.

**Comment by icarter09** [comment]
@hxingpax thanks for the update.
