### ISSUE TITLE
Popups applets fail after installing latest stable gtk+3.0

### ISSUE THREAD

**Issue by joequant** [linuxmint/Cinnamon#7835]
```
 * Cinnamon version (cinnamon --version) 3.8.8
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mageia Caldron
 * Graphics hardware *and* driver used - intel
 * 32 or 64 bit 64 bit
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
 ```
Cjs-Message: 17:52:49.092: JS WARNING: [/usr/share/cinnamon/js/ui/applet.js 109]: reference to undefined property "actor"
Cinnamon warning: Log level 128: posix_spawn avoided (automatic reaping requested) (fd close requested) 
Cinnamon warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x6400003 (Firefox Ni)
Cjs-Message: 17:53:42.966: JS WARNING: [/usr/share/cinnamon/js/misc/fileUtils.js line 210 > Function 43]: Too many arguments to function GLib.file_set_contents: expected 2, got 4
Cjs-Message: 17:54:42.970: JS WARNING: [/usr/share/cinnamon/js/misc/fileUtils.js line 210 > Function 43]: Too many arguments to function GLib.file_set_contents: expected 2, got 4
Cjs-Message: 17:55:42.973: JS WARNING: [/usr/share/cinnamon/js/misc/fileUtils.js line 210 > Function 43]: Too many arguments to function GLib.file_set_contents: expected 2, got 4
Cjs-Message: 17:56:42.976: JS WARNING: [/usr/share/cinnamon/js/misc/fileUtils.js line 210 > Function 43]: Too many arguments to function GLib.file_set_contents: expected 2, got 4
Cjs-Message: 17:57:42.979: JS WARNING: [/usr/share/cinnamon/js/misc/fileUtils.js line 210 > Function 43]: Too many arguments to function GLib.file_set_contents: expected 2, got 4

**Issue**

After loading RPM's with latest gtk+3.0, I'm no longer getting popups from applets

**Steps to reproduce**

Install latest gtk+3.0 3.22.30 compiled from source

**Expected behaviour**

popups should appear

**Other information**
Would like some more context to see help debug issue.  I suspect that there is version skew somewhere

**Comment by leigh123linux** [comment]
I don't have that old version of gtk3.
```
$ rpm -qa gtk3
gtk3-3.23.2-1.fc29.x86_64
```
What do you mean by popups? as I haven't noticed anything missing here.

**Comment by joequant** [comment]
The control panel applets don't seem to work.  Also, it looks like I have an old gtk+3.0.  Let me see what happens if I compile with newer versions.  I think I'm running to version skew.

**Comment by joequant** [comment]
Oh 3.22.30 is the latest stable version.  Where is Applet.Applet defined?

**Comment by leigh123linux** [comment]
So the error occurs when you try to use configure for any applets?

> The control panel applets don't seem to work

**Comment by joequant** [comment]
The issue might have something to do with a glib upgrade to 2.58 rather than the gtk+3.0 upgrade.

**Comment by joequant** [comment]
Also this error is appearing

Cjs-Message: 18:51:12.548: JS WARNING: [/usr/share/cinnamon/js/misc/fileUtils.js
 line 210 > Function 43]: Too many arguments to function GLib.file_set_contents:
 expected 2, got 4
Cjs-Message: 18:52:12.550: JS WARNING: [/usr/share/cinnamon/js/misc/fileUtils.js
 line 210 > Function 43]: Too many arguments to function GLib.file_set_contents:
 expected 2, got 4

**Comment by joequant** [comment]
Found the problem.  The hidden API change in atk between 2.29.1 and 2.29.2 causes breakage in a lot of python modules.  Recompiling Xapp fixes the problems
