### ISSUE TITLE
Nemo: frequent crashes

### ISSUE THREAD

**Issue by BillDietrich** [linuxmint/Cinnamon#7836]
I'm a n00b; sorry if I'm doing this wrong.

```
 * Cinnamon version 3.8.8
 * Distribution - Linux Mint 19 Tara
 * Graphics hardware *and* driver used: Intel Core Processor Integrated Graphics Controller
 * 64 bit
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
 ```

**Issue**
After doing a lot of downloading and/or a lot of moving files around, maybe from internal disk to USB disk or USB flash drive, Nemo crashes and restarts.

**Steps to reproduce**

**Expected behaviour**

**Other information**
[inxi.txt](https://github.com/linuxmint/Cinnamon/files/2343316/inxi.txt)
[trace.txt](https://github.com/linuxmint/Cinnamon/files/2343317/trace.txt)
[xsession-errors.txt](https://github.com/linuxmint/Cinnamon/files/2343318/xsession-errors.txt)
[xsession-errors-old.txt](https://github.com/linuxmint/Cinnamon/files/2343319/xsession-errors-old.txt)

**Comment by BillDietrich** [comment]
Sorry, instead of "Nemo crashes and restarts", should have said "Nemo crashes, and then I can launch Nemo again without any problem".

**Comment by leigh123linux** [comment]
Please move this to nemo

https://github.com/linuxmint/nemo/issues
