### ISSUE TITLE
Oversize icons on Linux Mint 19 Cinnamon edition with FreeCAD-0.17

### ISSUE THREAD

**Issue by neildarlow** [linuxmint/cinnamon#7840]
Cinnamon version - 3.8.8
Distribution - Linux Mint 19
Graphics - Optimus (Intel/NVidia) - NVidia 390.48 - xserver-xorg-video-intel 2:2.99.917+git20171229-1
64 bit

**Issue**
FreeCAD-0.17 from the freecad-maintainers/freecad-stable or AppImage download displays oversize icons with the Mint-Y theme under Cinnamon. Another user has confirmed that the problem does not exhibit under the XFCE edition. Also it appears to only happen with the Mint-Y theme. I have tested a number of alternate standard themes and the problem does not show.

**Steps to reproduce**
1) Install Linux Mint Cinnamon edition and select Mint-Y theme
2) Install FreeCAD-0.17 from freecad-maintainers/freecad-stable PPA or AppImage download
3) Start FreeCAD and observe the "Execute Macro" toolbar icon and Help Menu icons

**Expected behaviour**
The aforementioned icons (see attached screenshot) should be the same size as other icons.

**Other information**
FreeCAD version information:
OS: Linux Mint 19 Tara
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.17.13541 (Git)
Build type: None
Branch: releases/FreeCAD-0-17
Hash: 9948ee4f1570df9216862a79705afb367b2c6ffb
Python version: 2.7.15rc1
Qt version: 4.8.7
Coin version: 4.0.0a
OCC version: 7.3.0
Locale: English/UnitedKingdom (en_GB)

Screenshot exhibiting problem:
![screenshot from 2018-09-10 18-09-33](https://user-images.githubusercontent.com/6245505/45316710-b8018d80-b52f-11e8-98c4-9f1dacafbb17.png)

.xsession-errors file:
[xsession-errors.txt](https://github.com/linuxmint/Cinnamon/files/2367945/xsession-errors.txt)

**Comment by icarter09** [comment]
@neildarlow are you still experiencing this issue?

**Comment by neildarlow** [comment]
I'm on Linux Mint 19.2 with FreeCAD-0.18.4 and the issue isn't present any more. I switched to the Papirus icon theme some time ago to work around this. I guess it can be closed now.
