### ISSUE TITLE
Guake terminal cannot be added to startup application (disappears upon reboot)

### ISSUE THREAD

**Issue by marmistrz** [linuxmint/cinnamon#7848]
```
 * Cinnamon version: 3.8.8
 * Distribution: Arch
 * Graphics hardware *and* driver used: i5-5200U/modesetting
 * 64 bit
 * Attach /home/<username>/.xsession-errors
[.xsession-errors.txt](https://github.com/linuxmint/Cinnamon/files/2380540/default.xsession-errors.txt)

 ```

**Issue**
Guake terminal cannot be added to startup application (disappears upon restart)

**Steps to reproduce**
1. Install Cinnamon
2. Install Guake terminal
3. Add Guake terminal to start-up applications using the "add application" path

**Expected behavior**
After reboot the setting persists and guake is spawned upon login

** Actual behavior**
Upon next login, guake is missing from the start-up applications and doesn't start upon login

**Comment by mtwebster** [comment]
This behaves as expected for me.  I added it via 'Choose application', rebooted, it started when I logged in.

Can you run cinnamon-settings in a terminal and try to add it again?  I'm curious if something is failing to actually save the desktop file.

Is a desktop file being created in `~/.config/autostart`?

**Comment by marmistrz** [comment]
Yes, it's added, but disappears after a reboot (I'll check if a logout is enough).

``` $ cinnamon-settings
/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py:219: DeprecationWarning: Gtk.Widget.set_margin_right is deprecated
  self.stack_switcher.set_margin_right(n)
/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py:232: DeprecationWarning: Gtk.Window.set_has_resize_grip is deprecated
  self.window.set_has_resize_grip(False)
libgoa-backend-1.0.so.1: cannot open shared object file: No such file or directory
Failed to load module: /usr/lib/cinnamon-control-center-1/panels/libonline-accounts.so
Using pam module (python3-pampy)
/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py:423: DeprecationWarning: Gtk.Misc.set_alignment is deprecated
  widget.set_alignment(.5, .5)
Loading Startup Applications module
```

**Comment by marmistrz** [comment]
It was reproduced on a fresh Arch Linux install. What's interesting, if a custom command with the name `guake` is added, it disappears as well after a reboot. If I name the custom command `t guake`, it's ok.

So it looks like that the name `guake.desktop` is problematic

(I still need to check the logout thing)

**Comment by LinuxOnTheDesktop** [comment]
So far, I do _not_ have this problem on Mint 19.1 Cinnamon. That is: I can add a startup entry called 'guake' with the command 'guake' and that entry does persist. (I added the startup with a delay, though. I have not tested it without a delay.)

**Comment by Vahan86** [comment]
@marmistrz, is this still an issue in Cinnamon 4.4?

**Comment by marmistrz** [comment]
Yes, it is.

**Comment by Odyseus** [comment]
Hello, everybody.

This issue can be closed since this is not a Cinnamon issue, nor a Guake issue for that matter. [This is how Guake operates](https://github.com/Guake/guake/blob/master/guake/prefs.py#L216). If one has **Start Guake at login** disabled (unchecked) on Guake's settings, Guake will remove the file at **~/.config/autostart/guake.desktop** if it exists. This is the way that several applications deal with their auto start feature (Dropbox comes to mind). On the other hand, applications like Shutter just toggle the **X-GNOME-Autostart-enabled** on an existent .desktop file inside **~/.config/autostart**.

**Comment by spacer2010** [comment]
i use debian bookworm with gnome and have the same problem

**Comment by webaaz** [comment]
So what can we do?
