### ISSUE TITLE
All apps, but not favorite apps, disappear in Cinnamenu and regular menu after updates. 

### ISSUE THREAD

**Issue by MrLaramiw** [linuxmint/cinnamon#7849]
System:    Host: linux-blade Kernel: 4.15.0-34-generic x86_64
           bits: 64 gcc: 7.3.0
           Desktop: Cinnamon 3.8.9 (Gtk 3.22.30-1ubuntu1)
           Distro: Linux Mint 19 Tara
Machine:   Device: laptop System: Razer product: Blade v: 6.06 serial: N/A
           Mobo: Razer model: Razer serial: N/A
           UEFI: Razer v: 4.02 date: 02/22/2018
Battery    BAT0: charge: 68.5 Wh 100.0% condition: 68.5/70.2 Wh (98%)
           model: Razer Blade status: Discharging
CPU:       Quad core Intel Core i7-7700HQ (-MT-MCP-) 
           arch: Skylake rev.9 cache: 6144 KB
           flags: (lm nx sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx) bmips: 22464
           clock speeds: max: 3800 MHz 1: 3475 MHz 2: 3476 MHz 3: 3459 MHz
           4: 3411 MHz 5: 3440 MHz 6: 3443 MHz 7: 3540 MHz 8: 3467 MHz
Graphics:  Card-1: Intel Device 591b bus-ID: 00:02.0
           Card-2: NVIDIA GP106M [GeForce GTX 1060 Mobile] bus-ID: 01:00.0
           Display Server: x11 (X.Org 1.19.6 )
           drivers: modesetting,nouveau (unloaded: fbdev,vesa)
           Resolution: 1920x1080@60.05hz
           OpenGL: renderer: Mesa DRI Intel HD Graphics 630 (Kaby Lake GT2)
           version: 4.5 Mesa 18.0.5 Direct Render: Yes
Audio:     Card Intel CM238 HD Audio Controller
           driver: snd_hda_intel bus-ID: 00:1f.3
           Sound: Advanced Linux Sound Architecture v: k4.15.0-34-generic
Network:   Card: Intel Wireless 8260 driver: iwlwifi bus-ID: 3b:00.0
           IF: wlp59s0 state: up mac: <filter>
Drives:    HDD Total Size: 1024.2GB (9.7% used)
           ID-1: /dev/nvme0n1 model: SAMSUNG_MZVLW1T0HMLH size: 1024.2GB
Partition: ID-1: / size: 901G used: 77G (9%) fs: ext4 dev: /dev/dm-1
           ID-2: /boot size: 705M used: 221M (34%)
           fs: ext4 dev: /dev/nvme0n1p2
           ID-3: swap-1 size: 17.06GB used: 0.00GB (0%)
           fs: swap dev: /dev/dm-3

[syslog.zip](https://github.com/linuxmint/Cinnamon/files/2381797/syslog.zip)

 ```

**Issue**
After taking the most recent round of updates proposed by update manager, applet "Cinnamenu", and the standard mint menu only show favorite apps and no others. Apps can still be launched in terminal. Rolling back in timeshift does not solve the problem. 



**Other information**

**Comment by icarter09** [comment]
@MrLaramiw are you still experiencing this issue? If so, can you post the steps necessary to reproduce it? Thanks.

**Comment by Vahan86** [comment]
@icarter09, can we close the issue since there is no response from OP?
