### ISSUE TITLE
Keyboard applet icon container do not resize

### ISSUE THREAD

**Issue by mat-m** [linuxmint/Cinnamon#7856]
```
 * Cinnamon version :  Cinnamon 3.8.9
 * Distribution - Mint 19.0
 * 64 bit
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
 ```

**Issue**
Keyboard applet icon  in Panel is overlapped by the below one (Removable drives). When in Panel edit mode, we can easily see that the reserved space is too small for  the image.

**Steps to reproduce**
* Define more than one configuration in the keyboard/layout settings

**Expected behaviour**

**Other information**
Default state :
![overlap-keyboard_applet](https://user-images.githubusercontent.com/1039753/45600597-b5a3a580-b9ff-11e8-826b-ce8cf1f400f9.png)

Keyboard Applet while in Panel edit mode:
![overlap_kbd_edit](https://user-images.githubusercontent.com/1039753/45600601-c2c09480-b9ff-11e8-892c-add0bf8c6f63.png)

Removable drives while in Panel edit mode:
![overlap_rmv_edit](https://user-images.githubusercontent.com/1039753/45600608-d2d87400-b9ff-11e8-8a05-0e6cdc2290a6.png)

**Comment by germanfr** [comment]
That is the theme defining a fixed size for the icon. Use another theme.

**Comment by mat-m** [comment]
@germanfr : most custom themes get this wrong. Noted. I will report to the theme, then.
