### ISSUE TITLE
Default panel size is too small (for people with crap eyes).

### ISSUE THREAD

**Issue by juhanoi** [linuxmint/Cinnamon#7858]
```
 * Cinnamon version (cinnamon --version)
Cinnamon 3.8.8
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
Arch
 * Graphics hardware *and* driver used
NVIDIA 980 GTX, proprietary
 * 32 or 64 bit
64

 ```

**Issue**
Default panel size (25px) is too small (for people with crap eyes).

**Other information**
Please increase default panel size to 32 pixels so it is easier to see them.
It would also make raster icons scale better, because they are often 32x32 or 64x64 pixels size.

**Comment by leigh123linux** [comment]
Have you considered buying better glasses so you can see?, as the panel is correct for most users.

**Comment by juhani5** [comment]
go fuck yourself, leigh
you ended up changing it anyway
cinnamon = nigger project
