### ISSUE TITLE
Shutdown dialog missing buttons if other users are logged in

### ISSUE THREAD

**Issue by kokynator** [linuxmint/cinnamon#7861]
```
 * Cinnamon version (Cinnamon 3.8.9)
 * Distribution - (Mint 19)

**Issue**
I want to shutdown a PC while another user is still logged in. I get this* message but cannot select an action. No button visible in the dialog.
* check image below

**Steps to reproduce**
Login with second user then lock screen and login with your user and shutdown your PC.This dialog pops up.


**Expected behaviour**
Exactly how it works now but with visible buttons for popup confirmation.



**Other information**
screenshot: https://user-images.githubusercontent.com/14105721/45628212-e2090180-ba93-11e8-9beb-0001a8ffca09.jpg

**Comment by icarter09** [comment]
@kokynator are you still experiencing this issue?

**Comment by smurphos** [comment]
@icarter09 

There are a few issues here...

1) Out of the box current Mint versions don't actually prevent shutdown when there are multiple users logged in, which is undesirable if another logged in user has unsaved work.

This can be fixed - e.g. - https://forums.linuxmint.com/viewtopic.php?p=1638891#p1638891

2) With the tweak outlined in 1 applied, then attempting to shutdown from the login-screen produces the output as per the original issue raised. I've never seen it display that way without applying the tweak.

![screenshot-screen-2019-12-07-085656](https://user-images.githubusercontent.com/29017677/70371811-b0b26680-18cf-11ea-9ab4-0e2f03335f47.png)

In an ideal world the dialog should display correctly but ask for credentials to perform the action.

Having said all of that I don't think any of these problems are specific to Cinnamon. 1) Is a general Linux Mint issue. 2) Should be filed against slick-greeter....

**Comment by icarter09** [comment]
@smurphos sorry for not responding sooner. Saw this first thing this morning and forgot all about it.

Thanks for the insight on the issue and I completely agree with you. That being said, I can close this ticket and re-open it in the slick-greeter repo. Thoughts?

**Comment by smurphos** [comment]
No worries. Yep, I'd move it to slick-greeter
