### ISSUE TITLE
Nemo context ribbon doesn't have option to dismiss.

### ISSUE THREAD

**Issue by JLemur** [linuxmint/cinnamon#7865]
```
 * Cinnamon 3.6.7
 * Mint 18.3
 * 64 bit
 * Nemo 3.6.5
 ```

**Issue**
Nemo displays a ribbon at the top for certain scenarios, such as inserting an SD card with images.  The text in the ribbon is like "The media contains digital photos.  Open Shotwell Photo Manager"

This can be very helpful and useful when the user wants to open the recommended application, but there is no way to dismiss the ribbon if the user wants to just remain in Nemo.  The amount of space that the ribbon takes up in the viewing pane reduces the number of thumbnails or other details of the files that can be viewed at a time.  Thus I would like to submit an enhancement request that these ribbons include a way to dismiss them.

**Steps to reproduce**
Insert SD card with images.  The ribbon will appear at the top of Nemo where files are displayed.

**Expected behaviour**
The enhanced behavior would include a mechanism (like an "x" box) to close/dismiss the ribbon.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
