### ISSUE TITLE
Overview has too much spacing between windows

### ISSUE THREAD

**Issue by phocean** [linuxmint/cinnamon#7876]
The spacing between windows in overview mode is much too large.

As a result, windows are ridiculously small. The more windows you open, the worse it gets.

 For reference, gnome-shell has a nicer layout.

**Comment by germanfr** [comment]
This is already a work in progress.

**Comment by germanfr** [comment]
This can be closed, it's already fixed in the latest version.

**Comment by JosephMcc** [comment]
Cool thanks
