### ISSUE TITLE
wallpaper as slide presentation option not persisting 

### ISSUE THREAD

**Issue by sombriks** [linuxmint/Cinnamon#7878]
```
 * Cinnamon version (cinnamon --version) **3.8.8**
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) **Fedora 28**
 * Graphics hardware *and* driver used **Intel Corporation HD Graphics 620**
 * 32 or 64 bit **64 bits**
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
 ```

**Issue**

wallpaper as slide presentation option not persisting 

**Steps to reproduce**

- select a folder with wallpapers (ex. ~/Dropbox/wallpapers)
- in the background configuration check the slideshow option

everything will work, however if i restart the computer the option will set back to the single wallpaper mode

**Expected behaviour**

see steps to reproduce

**Other information**

none

**Comment by icarter09** [comment]
Cinnamon 3.8.9
Linux Mint 19 64bit

I was unable to reproduce this bug. Steps I performed were:
1. Create new directory on Desktop
2. Put images into directory
3. Set folder to be displayed for wallpaper
4. Set the background configuration to use slideshow option
When I restarted the computer, the slideshow option was still selected and the background was displaying in slideshow format.
@sombriks maybe upgrading Cinnamon will fix the issue. If that doesn't fix the issue, then it could be related to using Fedora.

**Comment by sombriks** [comment]
@icarter09 i just made a fresh fedora-cinnamon install (instead fedora gnome and cinnamon from repo) and me too did not was capable to reproduce the issue anymore.

it might be a very specific step on fedora, installing cinnamon from repositories.
