### ISSUE TITLE
Opening application menu crashes Cinnamon on musl-based distributions

### ISSUE THREAD

**Issue by demize** [linuxmint/cinnamon#7882]
```
 * Cinnamon version: 3.8.8
 * Distribution: Void Linux (musl)
 * Graphics hardware *and* driver used: Intel Corporation 3rd Gen Core processor Graphics Controller (kernel driver in use: i915)
 * 32 or 64 bit: 64-bit
 * No logs available (.xsession-errors is empty, Void Linux doesn't have a syslog by default)
 ```

**Issue**

When the application menu is set to show icons for applications, opening the application menu catastrophically crashes Cinnamon, This issue was originally reported to Void Linux in voidlinux/void-packages#10204.

**Steps to reproduce**

1. Install a musl-based distribution such as Void Linux
2. Install and launch Cinnamon
3. Try to open the application menu.

**Expected behaviour**

The application menu will open.

**Actual behavior**

Cinnamon crashes and restarts in a broken version of safe mode, with no UI elements available.

**Other information**

Turning off application icons in the application menu config (by right clicking the menu) is a viable workaround, as is installing and using the Papirus theme for application icons. The person who originally reported this issue tested multiple other icon themes to no avail.

**Comment by mtwebster** [comment]
Can you restart cinnamon from a terminal so we can get some logging?

```
cinnamon --restart
```

**Comment by mtwebster** [comment]
Can you try processing that with gdb?  I can't do much with it.

```
gdb cinnamon core.2028

# from within gdb,
thread apply all bt
```
Not sure how available debugging symbols are on that distro - that would be best to have (at least for clutter, gtk, cinnamon)

**Comment by demize** [comment]
Here's the backtrace it gave me: [gdb.txt](https://github.com/linuxmint/Cinnamon/files/2408364/gdb.txt).

**Comment by demize** [comment]
I installed all the debug symbols I could figure out based on the backtraces, and here's the new output: [gdb-withsymbols.txt](https://github.com/linuxmint/Cinnamon/files/2408371/gdb-withsymbols.txt)

Oddly enough, gdb doesn't seem to properly recognize the symbols for mozjs. Not sure why.

**Comment by demize** [comment]
Just checked to see, recent files is already disabled.

**Comment by mtwebster** [comment]
Is there anything at play limiting process memory?  One thing typical of opening the menu (with icons enabled) is a significant memory bump, the first time it's done.

I'm curious if the menu had only a few things in it, would it still crash?

**Comment by demize** [comment]
There shouldn't be anything limiting process memory; I haven't installed or configured anything to limit memory, and I don't believe Void would have any such limitations configured by default. Cinnamon works fine on the glibc version of Void as well (apparently; I haven't actually tried it myself, since I've only ever used the musl version) so it *could* be different behavior in memory allocation functions between musl and glibc (musl aims to be standards-conformant while glibc allows a lot that isn't standards-conformant, so it's possible that musl just doesn't like the way something's being done).

**Comment by marmistrz** [comment]
This may or may not be related: https://github.com/dino/dino/issues/365
This may be some gtk issue but I've never had the time to narrow it down.

**Comment by Vahan86** [comment]
@demize, is this still an issue for you with Cinnamon 4.2?

**Comment by Vahan86** [comment]
@icarter09, can we close this issue since there is no response from OP?

**Comment by kukku14** [comment]
This issue is still present with cinnamon 4.6.7 on musl

**Comment by icarter09** [comment]
@kukku14 could you open a new ticket about this issue? Thanks.
