### ISSUE TITLE
Command to select a specific keyboard layout?

### ISSUE THREAD

**Issue by lolmaus** [linuxmint/cinnamon#7884]
```
 * Cinnamon version - 3.8.9
 * Distribution - Mint 19
 * 64 bit
 ```

**Issue**

Unable to select a specific keyboard layout with a terminal command.

**Steps to reproduce**

Tried these:

* `gsettings set org.gnome.desktop.input-sources current 1`
* `gdbus call --session --dest org.gnome.Shell --object-path /org/gnome/Shell --method org.gnome.Shell.Eval "imports.ui.status.keyboard.getInputSourceManager().inputSources[1].activate()"`
* `setxkbmap` works, but it crashes the Cinnamon keyboard layout manager: the tray icon disappears and it is no longer possible to switch via configured hotkey.

**Comment by lolmaus** [comment]
Please. :sob:

**Comment by icarter09** [comment]
@lolmaus are you still experiencing this issue?

**Comment by lolmaus** [comment]
I've configured this with [xkb-switch](https://github.com/ierton/xkb-switch).

But I believe the OS should be capable of this natively.

**Comment by camypaj** [comment]
> ```
>  * Cinnamon version - 3.8.9
>  * Distribution - Mint 19
>  * 64 bit
> ```
> 
> **Issue**
> 
> Unable to select a specific keyboard layout with a terminal command.
> 
> **Steps to reproduce**
> 
> Tried these:
> 
>     * `gsettings set org.gnome.desktop.input-sources current 1`
> 
>     * `gdbus call --session --dest org.gnome.Shell --object-path /org/gnome/Shell --method org.gnome.Shell.Eval "imports.ui.status.keyboard.getInputSourceManager().inputSources[1].activate()"`
> 
>     * `setxkbmap` works, but it crashes the Cinnamon keyboard layout manager: the tray icon disappears and it is no longer possible to switch via configured hotkey.

Regarding the disappearing applet, I've had a similar experience, documented here:
https://github.com/linuxmint/cinnamon/issues/8257#issuecomment-563975832

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.

**Comment by eugrus** [comment]
Still not implemented?

There should be an equivalent to Gnome's
`gsettings set org.gnome.desktop.input-sources sources "[('xkb', 'us')]"`

**Comment by madhead** [comment]
Hey, I am not familiar with Cinnamon, and I guess it's APIs are not the same as in GNOME, but may be [my GNOME extension](https://github.com/madhead/shyriiwook) could be adopted somehow. The idea is to use the CJS APIs directly and expose a callable D-Bus interface…

**Comment by perdakovich** [comment]
`gdbus call --session --dest org.Cinnamon --object-path /org/Cinnamon --method org.Cinnamon.Eval 'imports.ui.keyboardManager.getInputSourceManager()._modifiersSwitcher(false);'`

**Comment by mtwebster** [comment]
That overkill, just use:
```
cinnamon-dbus-command ActivateInputSourceIndex n
```
where `n` is the index of the layout you want.
