### ISSUE TITLE
Alt+Shift, configured to switch keyboard layout, opens a menu instead

### ISSUE THREAD

**Issue by lolmaus** [linuxmint/cinnamon#7885]
* Cinnamon version: 3.8.9
 * Distribution: Mint 19
 * Graphics hardware: Intel 4000
 * 64 bit

**Issue**

<kbd>Alt</kbd>+<kbd>Shift</kbd>, configured to switch keyboard layout, opens a menu instead

**Steps to reproduce**

* In *Keyboard Options*, I've configured *Switching to another layout* to <kbd>Alt</kbd>+<kbd>Shift</kbd>.
* Open an app with a menu (File, Edit, View...)
* Press <kbd>Alt</kbd>+<kbd>Shift</kbd>.

**Expected behaviour**

Keyboard language changes, nothing else happens.

**Actual behavior**

Keyboard language changes, a File menu opens and steals focus.

**Other information**

Happens in [Electron-based apps](https://electronjs.org/apps) and probably others.

**Comment by icarter09** [comment]
@lolmaus are you still experiencing this issue?

**Comment by lolmaus** [comment]
This problem happens in one app and is probably caused by the app.
