### ISSUE TITLE
Applet icons

### ISSUE THREAD

**Issue by DanielRios549** [linuxmint/Cinnamon#7892]
```
 * Cinnamon version 3.8.9
 * Linux Mint 19 64 bit
 * NVIDIA GeForce GTX 750, driver Nvidia 396.54

 ```

**Issue**

Some system applets has an icon folder and the applet use this icon instead of icon theme one, notifications and blueberry, for exemple. I think it's a good idea, firstly try to use the icon from theme, and then, if there is no icon, use the icon inside the applet folder.

**Steps to reproduce**

Add an applet and, as the theme has an icon, use this icon, if does not, use the built-in one.

**Expected behaviour**

Preserve the icon theme identity.

**Comment by NikoKrause** [comment]
Oh, it does use the icons from the icon theme first and then those in your screenshot as fallback.
You're using the Mint-Y icon theme. This icon theme doesn't have those icons, so the fallback ones are used.

Or do you know of any icon theme, which has those icons and where those are not used?
