### ISSUE TITLE
Caps lock indicator required on hard disk unlock screen

### ISSUE THREAD

**Issue by XRayA4T** [linuxmint/cinnamon#7893]
* Cinnamon version 3.6.7
 * Distribution - Mint 18.3
 * Graphics hardware *and* driver used  - n/a
 * 64 bit

**Issue**

There is no caps lock indicator on the hard disk unlock screen like there is on the account login screen. If your keyboard has no indicator there is no way to know if you're missing the password because of having caps lock on.

**Steps to reproduce**
Have full disk encryption
Reboot
When password box for disk decrypt appears toggle caps lock

**Expected behaviour**

When caps lock is on there should be an indicator similar to the account login box

**Other information**

**Comment by icarter09** [comment]
@XRayA4T are you still experiencing this issue?

**Comment by Vahan86** [comment]
@icarter09, can we close the issue since there is no response from OP?
