### ISSUE TITLE
Setting up a hotkey to open the Start menu?

### ISSUE THREAD

**Issue by lolmaus** [linuxmint/Cinnamon#7894]
* Cinnamon version: `3.8.9`
 * Distribution: `Mint 19`

I've set up my Super (aka Windows) key to do something else. How do I configure another key (or key combination) to open the Start menu?

I've looked through available actions in Keyboard settings and failed to find the relevant one.

**Comment by mtwebster** [comment]
Right click on the menu applet in the panel itself and select Configure. Applets generally have their own settings.

**Comment by lolmaus** [comment]
@mtwebster Thank you, kind sir.
