### ISSUE TITLE
Core was generated by `cinnamon --replace'. Program terminated with signal SIGABRT, Aborted.

### ISSUE THREAD

**Issue by KID1944** [linuxmint/cinnamon#7898]
```
 * Cinnamon version 3.8.9
 * Distribution - Linux Mint 19 Cinnamon
 * Graphics hardware *and* driver used
    Advanced Micro Devices, Inc. [AMD/ATI] Carrizo
 * 

64 bit
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
 ```

**Issue**
Core was generated by `cinnamon --replace'.
Program terminated with signal SIGABRT, Aborted.

**Steps to reproduce**
crash.tar.gz](https://github.com/linuxmint/Cinnamon/files/2430241/crash.tar.gz)

**Expected behaviour**

**Other information**

**Comment by icarter09** [comment]
@KID1944 unsure of the file that you provided. Can you provide a list of steps to reproduce the issue? Thanks.

**Comment by KID1944** [comment]
Sorry im new to this 
Im having repeat crashes when i watch videos in firefox. I'm trying chromium now. So far I think i had one crash. I had this problem with LM 18.3 so I did a clean install of 19 same problem but more frequent.

**Comment by Vahan86** [comment]
@KID1944, is this still an issue for you with LM 19.3 (Cinnamon 4.4)?

**Comment by KID1944** [comment]
Good day

No. Since there were a few updates since then I havent had the issue Thanks
