### ISSUE TITLE
[Feature request] Configurable color of the missed notification applet

### ISSUE THREAD

**Issue by marmistrz** [linuxmint/cinnamon#7902]
Currently it's easily to miss that a notification has been missed. It would be easier if the applet were colorful.

**Comment by icarter09** [comment]
@marmistrz I take it that you missed a notification :). What part of the applet do you think should contain color and what color do you feel be most beneficial to the user?

**Comment by marmistrz** [comment]
:)
Well, I think both the icon and the text and the color should ideally be configurable. But I'd choose something about red.

**Comment by NikoKrause** [comment]
The applet is using symbolic icons. With symbolic icons you don't have much options to show colors, i.e. symbolic icons allow only 3 colors: red/orange/green
You have to add `class="error"`, `class="warning"` or `class="success"` in the svg itself.

Currently the applet uses 5 icons:
![screenshot-area-2018-10-16-135952](https://user-images.githubusercontent.com/8415124/47015274-d0775000-d14c-11e8-8691-4360a81a7f8c.png)

So orange is used for critical notifications. I don't think it's wanted to have red for normal notifications.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
