### ISSUE TITLE
Power applet doesn't show percentage if the panel is vertical

### ISSUE THREAD

**Issue by marmistrz** [linuxmint/Cinnamon#7904]
```
 * Cinnamon version: 3.8.9
 * Distribution - Arch
 ```
show percentage is enabled in the applet settings but no percentage is shown

as above. Now using just the cinnamon theme
![screenshot from 2018-09-30 17-45-57](https://user-images.githubusercontent.com/2914938/46259356-abda7180-c4d8-11e8-9822-3177fb9a0c0f.png)

**Comment by icarter09** [comment]
Cinnamon 3.8.9
Linux Mint 19 64bit

Was able to duplicate this issue. Verified that it is a bug.

**Comment by mtwebster** [comment]
By default, applets that can display both and icon and label automatically suppress the label in a vertical panel.  This is intentional behavior, as there is ordinarily no room for anything more than an icon.

**Comment by marmistrz** [comment]
Then this issue should read: the power management applet should provide a way to display percentage in vertical mode. Those images are useless to me in estimating, how much juice there's still remaining.
