### ISSUE TITLE
any way to completely remove / hide main menu icon from panel, but still show on keyboard hotkey?

### ISSUE THREAD

**Issue by bitoolean** [linuxmint/Cinnamon#7906]
```
 * Cinnamon version (cinnamon --version)
Cinnamon 3.8.9
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
Mint 19 Tara (the ISO said v2)

 * Graphics hardware *and* driver used
 * 32 or 64 bit
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
 ```
Intel Haswell-ULT Integrated Graphics Controller
drivers: modesetting (unloaded: fbdev,vesa)

**Issue**
Trying to hide Mint main menu icon from the panel, but still show it on hotkey.

**Steps to reproduce**
Choose "Use a custom icon" in the applet's settings, since that's the only thing that is close to what I'm trying to achieve, and remove the icon file path.

**Expected behaviour**
The applet not to affect the panel visually, as if it weren't there, but it still takes some space.
I realize this is nit-picking.

**Other information**
Is there any simple way that others already use to achieve this, or some simple trick in some config?
I'm a programmer, but I don't know Linux all that well like I know Windows, if that helps help more easily. Any suggestion is appreciated. Of course, this is not an urgent issue or anything.

The latest mint looks so elegant and beautiful. Thank you! The progress bar in the panel as well. Congratulations! I'm usually very practically inclined, but I see now what a difference the nice things make.

**Comment by JosephMcc** [comment]
You can hide the icon as noted. You could also create and empty icon. You could also use the "Text" setting with just blank spaces to create some padding. Those are really your only options.
