### ISSUE TITLE
Cinnamon Crashes After Change to Default Python 3

### ISSUE THREAD

**Issue by tkivisik** [linuxmint/cinnamon#7910]
```
 * Cinnamon version 3.6.7
 * Distribution - Mint 18.3
 * Graphics hardware:
    VGA compatible controller:
        Intel Corporation Haswell-ULT Integrated Graphics Controller (rev 09)
        driver=i915
 * 64 bit
 ```

From /home/user/.xsession-errors, not sure if related:
 ```
(csd-power:1736): GLib-GIO-CRITICAL **: g_dbus_proxy_get_object_path: assertion 'G_IS_DBUS_PROXY (proxy)' failed

(cinnamon:1958): St-WARNING **: Ignoring length property that isn't a number at line 1526, col 13
 ```
**Issue**
Cinnamon crashed after a restart following a change of default python3 version (from 3.5.2 to 3.6.6).

After a restart, there was no taskbar, no desktop background, common shortcuts didn't work (CTR-ALT-T didn't open a terminal), windows were not resizeable.

**Steps to reproduce**

1. Don't touch the original python (python 2.7.12, nor the python 3.5.2).
2. Install alternative python versions (3.6.6 and 3.7.0) to a system - https://stackoverflow.com/a/46258340/5264794
3. Use update-alternatives tool to manage default python3 version - https://unix.stackexchange.com/a/410851/130093
`sudo update-alternatives --install /usr/bin/python3 python3 /usr/local/bin/python3.6 2`
`sudo update-alternatives --install /usr/bin/python3 python3 /usr/local/bin/python3.7 3`
4. Change the default python3 version to 3.6 - `sudo update-alternatives --config python3`

**Expected behaviour**
No change in Cinnamon workings.

**Comment by mtwebster** [comment]
While the cinnamon process itself shouldn't be affected by anything specifically python-related, some supporting programs may be using python, and using /usr/local (or any location other than default system) as an alternate install location isn't supported by gobject-introspection.  You may have to completely clean out `/usr/local` before your system will start working again.

**Comment by mtwebster** [comment]
Clarification: You can install different versions of python freely, the important part is not changing the system default locations.  Introspection (`from gi.repository import ***`) is not smart enough to check across multiple locations.

**Comment by tkivisik** [comment]
mtwebster, does it mean that if I installed python3.6 and 3.7 into `/usr/bin` instead of `/usr/local`, switching to a newer version might still work?

*Recovery:* I managed to recover by using a virtual console (CTR-ALT-F6), I changed the default python3 back to 3.5 using `sudo update-alternatives --config python3`

**Comment by marcodsad** [comment]
* Cinnamon version 3.8.9
 * Distribution - Mint 19
 * Graphics hardware:
    01:00.0 VGA compatible controller: NVIDIA Corporation GK106GLM [Quadro K2100M] (rev a1) (prog-if 00 [VGA controller])
	Subsystem: Dell GK106GLM [Quadro K2100M]
	Flags: bus master, fast devsel, latency 0, IRQ 31
	Memory at f4000000 (32-bit, non-prefetchable) [size=16M]
	Memory at e0000000 (64-bit, prefetchable) [size=256M]
	Memory at f0000000 (64-bit, prefetchable) [size=32M]
	I/O ports at e000 [size=128]
	[virtual] Expansion ROM at 000c0000 [disabled] [size=128K]
	Capabilities: <access denied>
	Kernel driver in use: nvidia
	Kernel modules: nvidiafb, nouveau, nvidia_drm, nvidia

01:00.1 Audio device: NVIDIA Corporation GK106 HDMI Audio Controller (rev a1)

 * 64 bit

Hi, I'm resuming this thread as I just experienced exactly the same issue, but the answer by @mtwebster does not apply to my setup.

The problem can be reproduced exactly as the original poster described it. However, my python3.6 and python3.7 are in /usr/bin.

According to @mtwebster this should avoid Cinnamon crash, but it does not, at least on my machine Cinnamon crashes, rendering my laptop unusable.

Thanks.

**Comment by adamtimmins** [comment]
I've also observed this behavior doing the same as the above.

**Comment by mtwebster** [comment]
Is `/usr/bin/python3` a link to `/usr/bin/python3.6` (or .7 I suppose)?

does this work the same for you? (the warning is unimportant)
```
mtwebster:~> python3
Python 3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from gi.repository import Gtk
__main__:1: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
>>> 
```

**Comment by adamtimmins** [comment]
> Is `/usr/bin/python3` a link to `/usr/bin/python3.6` (or .7 I suppose)?
> 
> does this work the same for you? (the warning is unimportant)
> 
> ```
> mtwebster:~> python3
> Python 3.6.9 (default, Nov  7 2019, 10:44:02) 
> [GCC 8.3.0] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> from gi.repository import Gtk
> __main__:1: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
> >>> 
> ```

I've reverted back to 3.6.9 and cinnamon is working. I don't see any error as you describe.

**Comment by icarter09** [comment]
@tkivisik are you still experiencing this issue?

**Comment by neeraj9194** [comment]
I have face the same issue today after I installed a new python version and did ` update-alternatives` 
 to point to python 3.7 from 3.6.9.

**Comment by 0xDSousa** [comment]
Same issue here. Updated from 3.6 to 3.8 by changing the `python3` symbolic link in `/usr/bin` and Cinnamon stopped working.

Recovered by linking again with python3.6 and rebooting.

**Comment by leigh123linux** [comment]
> While the cinnamon process itself shouldn't be affected by anything specifically python-related, some supporting programs may be using python, and using /usr/local (or any location other than default system) as an alternate install location isn't supported by gobject-introspection. You may have to completely clean out `/usr/local` before your system will start working again.

cinnamon isn't usable if setproctitle is missing.

https://github.com/linuxmint/cinnamon/blob/master/files/usr/bin/cinnamon-launcher#L9

@mtwebster 
If non-default python3 doesn't provide it I would expect cinnamon to fail, can we close this self inflicted issue?

**Comment by leigh123linux** [comment]
There is nothing to fix in cinnamon. it's your python3 non-default package which is the issue, it doesn't provide any the required imports.

```
caroline@caroline-Lenovo-YOGA-510-14ISK:~$ dpkg -l python3-setproctitle
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                        Version Architecture       Description
+++-===========================-==================-==================-===========================================================
ii  python3-setproctitle:amd64  1.1.10-1build2 amd64              Setproctitle implementation for Python 3
caroline@caroline-Lenovo-YOGA-510-14ISK:~$ python3.6
Python 3.6.9 (default, Apr 18 2020, 01:56:04)
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import setproctitle
>>>
caroline@caroline-Lenovo-YOGA-510-14ISK:~$ python3.8
Python 3.8.0 (default, Oct 28 2019, 16:14:01)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import setproctitle
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'setproctitle'
>>> 
```
