### ISSUE TITLE
Feature Request - mouse Snap-To option...

### ISSUE THREAD

**Issue by invexx** [linuxmint/cinnamon#7912]
Snap-To feature just like in all Windows versions since 95.
![image](https://user-images.githubusercontent.com/26446962/46513063-19a5d680-c814-11e8-9dc6-6cf01be89777.png)

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
