### ISSUE TITLE
Account details cs_user.py choose picture error message

### ISSUE THREAD

**Issue by lehitoskin** [linuxmint/cinnamon#7918]
```
 * Cinnamon 3.8.8
 * Gentoo Linux
 * Nvidia 1080ti with x11-drivers/nvidia-drivers-410.57-r1
 * 64 bit
 ```

**Issue**
Selecting a picture from the "Account details" settings window and then choosing "Browse for more pictures..." brings up this error when running in the terminal:
```
Traceback (most recent call last):
  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_user.py", line 171, in _on_face_browse_menuitem_activated
    dialog.set_current_folder(self.accountService.get_home_dir())
TypeError: Argument 1 does not allow None as a value
```
There are no graphical indicators that something has gone wrong --- visually it looks like the "Browse for more pictures" button does nothing.

**Steps to reproduce**
* Open the Cinnamon settings window
* Open "Account details"
* Click on the picture box
* Select "Browse for more pictures..."

**Expected behaviour**
A open file dialog window should open, allowing me to choose the image I want as my picture.

**Other information**
I have installed all the latest Cinnamon-related packages in Portage.

**Comment by icarter09** [comment]
Cinnamon 3.8.9
Linux Mint 19 64bit

Was unable to duplicate this issue following the steps provided. When I select "Browse for more pictures", a file dialog window is opened (the expected behavior). 

@lehitoskin I would say that the issue is with Gentoo, but you said that you have all the latest Cinnamon-related packages in Portage.

**Comment by lehitoskin** [comment]
It's probable that the ebuilds haven't been updated to the latest version if Cinnamon yet. Will try again when v3.8.9 or higher is released.

**Comment by icarter09** [comment]
@lehitoskin can you update this ticket with your findings once you upgrade? Thanks.

**Comment by icarter09** [comment]
Cinnamon 4.0.9
Linux Mint 19.1 64bit

@lehitoskin Thanks for the update. I went through the steps to reproduce the issue and it still works as intended for me.

**Comment by icarter09** [comment]
We believe this issue is fixed. Please test against the latest Cinnamon version (4.2). 

https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/
