### ISSUE TITLE
Applet manager: when an update is available for an applet, it is unclear which applet the update is for

### ISSUE THREAD

**Issue by ghost** [linuxmint/cinnamon#7919]
```
 * Cinnamon version (cinnamon --version) 3.8.9
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 19
 * 32 or 64 bit: 64
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog: I attach the former
 ```

**Issue**

Please see [this video](https://app.box.com/s/i2gogx1s40agjkc3552b4t7hh9avtrx2) (on Box; file type isn't supported for attachment), showing the problem with discovering which applet will be updated.

**Steps to reproduce**

Perhaps as simple as: have an updatable applet; try to discover which one it is.

**Expected behaviour**

It should be evident which applet(s) will be updated.

**Other information**

There is some hesitation on my part in the video, because the UI confused me somewhat (even aside from the issue I report); please compare #7117.

[xsession-errors.txt](https://github.com/linuxmint/Cinnamon/files/2454677/xsession-errors.txt)

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
