### ISSUE TITLE
Screenshots by hotkey are not working anymore

### ISSUE THREAD

**Issue by ManuelSchneid3r** [linuxmint/Cinnamon#7921]
```
Cinnamon 3.8.9
Arch
Not graphics related
x64
 ```

**Issue**
All functionality regarding screenshots by hotkey is not working anymore. (full screen, region, to clipboard)

**Steps to reproduce**
Press "Print"

**Expected behaviour**
Screenshot saved somewhere in $HOME

**Other information**

**Comment by mtwebster** [comment]
Is gnome-screenshot installed?

**Comment by ManuelSchneid3r** [comment]
Thats it. Thank you and sorry for the noise.
