### ISSUE TITLE
[FEATURE REQUEST] Add configuration to window-list that will not minimize on click

### ISSUE THREAD

**Issue by hareldvd** [linuxmint/cinnamon#7922]
```
 * Cinnamon version - 3.8.9
 * Distribution - fedora 28
 * Graphics hardware *and* driver used
 * 64 bit
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
 ```

**Issue**
Feature request

Please add a feature to disable window minimize on second click on window list. Currently I go to applets.js file (/usr/share/cinnamon/applets/window-list@cinnamon.org) and manually remove the minimize operation in _toggleWindow function: 
```
    _toggleWindow(fromDrag){
//        if (!this._hasFocus()) {
            Main.activateWindow(this.metaWindow, global.get_current_time());
            this.actor.add_style_pseudo_class('focus');
//        } else if (!fromDrag) {
//            this.metaWindow.minimize();
//            this.actor.remove_style_pseudo_class('focus');
//        }
    }
```

**Steps to reproduce**
Become old enough to kill old habits.
Also I think it is a known usability issue but I can't remember where I saw it.

**Expected behaviour**
Click should be allowed to put the window forward only

**Other information**

**Comment by syvanpera** [comment]
I made a PR for this: #7925
