### ISSUE TITLE
 Sound settings crash with USB sound card

### ISSUE THREAD

**Issue by zrajna** [linuxmint/cinnamon#7924]
```
 * Cinnamon version: Cinnamon 3.8.9
 * Distribution: Mint 19
 * Graphics hardware *and* driver used: Intel HD 620
 * 64 bit
 * .xsession-errors attached
 * cinnamon-settings terminal output attached
 ```

**Issue**

Sound settings crash with USB sound card M-Audio Fast Track Pro selected as sink

**Steps to reproduce**

Open sound settings, select M-Audio Fast Track Pro (Channel A or B) as Device. No issues with pavucontrol though, sink selection works there as expected.
If M-Audio Fast Track Pro device is selected as default (e.g. with pavucontrol), the sound settings window crashes within a second from start.

**Expected behaviour**

Sound settings do not crash, M-Audio Fast Track Pro is selected as device (sink)

**Other information**

[.xsession-errors](https://github.com/linuxmint/Cinnamon/files/2467621/xsession-errors.txt)

[$ cinnamon-settings](https://github.com/linuxmint/Cinnamon/files/2467634/cinnamon-settings_output.txt)

```
$ inxi -Ax
Audio:     Card-1 Intel Sunrise Point-LP HD Audio
           driver: snd_hda_intel bus-ID: 00:1f.3
           Card-2 Midiman M-Audio Fast Track Pro
           driver: USB Audio usb-ID: 001-010
           Sound: Advanced Linux Sound Architecture v: k4.15.0-36-generic
 ```

This issue was not present in previous Cinnamon versions (Mint 17-18.3).

I have kept config files in /home from Mint 18.3, and installed Mint 19 on / recently. This update ended up in this issue.

**Comment by icarter09** [comment]
@zrajna are you still experiencing this issue?

**Comment by zrajna** [comment]
@icarter09 Thanks for looking into this, I do not experience the issue anymore.
(The workaround was to disable one of the two channels of the sound card completely, but now that I enabled both again, sounds settings did not crash.)
