### ISSUE TITLE
Cinnamon 3.6.7 was broken after updates

### ISSUE THREAD

**Issue by KeyJoo** [linuxmint/Cinnamon#7926]
# Cinnamon 3.6.7 was broken after updates

- Cinnamon version (Cinnamon 3.6.7)
- Distribution - (Mint 18.3)
- [Graphics hardware](https://gist.github.com/KeyJoo/d0d52c455612bd69dbeb2a6f81c8ebc8)
- 64 bit
- Attached [/var/log/syslog](https://gist.github.com/KeyJoo/deb0104e9b488cdc6b19b3066ec178ef)

**Steps to reproduce**

Try :warning: [install new cinnamon](https://github.com/linuxmint/Cinnamon/wiki/Trying-out-the-latest-Cinnamon-without-building-it.), no result.

**Expected behaviour**
:dart:  I want restore stable GUI of Cinnamon

**Other information**
:sos: Some buttons, inputs, scroll-bar, menu, pop-up list don't working no more ...

**Comment by jaszhix** [comment]
That repo stopped updating in July, there has been a lot of changes since then. Cinnamon 3.6 is the newest release available on Mint 18.3, you will need to upgrade Mint instead.

**Comment by KeyJoo** [comment]
I looking help for this issue.

**Comment by jaszhix** [comment]
You need to downgrade Cinnamon. Login using Mate. Run `sudo apt-get purge cinnamon* && sudo apt-get purge *cjs*`. Open software sources and disable the PPA. Refresh sources. Run `sudo apt-get install cinnamon`. 

Follow these instructions carefully: https://community.linuxmint.com/tutorial/view/2416

If you have any further trouble, you could try searching the [forums](http://forums.linuxmint.com/).
