### ISSUE TITLE
Crackling Audi / Microphone with ALC1120

### ISSUE THREAD

**Issue by master3553** [linuxmint/Cinnamon#7928]
> ```
>  * Cinnamon 3.8.9
>  * Mint 19
>  * Vega64 Open Source driver in 4.18.13
>  * x86_64
> ```
>  [syslog](https://github.com/linuxmint/Cinnamon/files/2470595/syslog.txt)
> **Issue**
> Crackling sound and microphone
> 
> **Steps to reproduce**
> Play any sound. Should occur after a few minutes.
> 
> **Expected behaviour**
> Sound should play fine.
> 
> **Other information**
> [devices](https://github.com/linuxmint/Cinnamon/files/2470605/devices.txt)

**Comment by master3553** [comment]
> ```
>  * Cinnamon 3.8.9
>  * Mint 19
>  * Vega64 Open Source driver in 4.18.13
>  * x86_64
> ```
>  [syslog](https://github.com/linuxmint/Cinnamon/files/2470595/syslog.txt)
> **Issue**
> Crackling sound and microphone
> 
> **Steps to reproduce**
> Play any sound. Should occur after a few minutes.
> 
> **Expected behaviour**
> Sound should play fine.
> 
> **Other information**
> [devices](https://github.com/linuxmint/Cinnamon/files/2470605/devices.txt)

**Comment by leigh123linux** [comment]
This isn't something which can be fixed within cinnamon code, I suggest you search google or ask on linuxmint forum.

```
Oct 11 22:16:52 arithmos kernel: [  947.090630] snd_hda_intel 0000:21:00.3: IRQ timing workaround is activated for card #1. Suggest a bigger bdl_pos_adj.
```
