### ISSUE TITLE
Theme Mint-Y - Invisible Border in Gnome Terminal

### ISSUE THREAD

**Issue by ppoteete** [linuxmint/cinnamon#7931]
```
Cinnamon 3.8.8
Linux Mint 19 Tara
Intel Corporation HD Graphics 520 (rev 07)
(over twenty computers experience this behaviour on assorted hardware)
 ```
**Issue**
The Gnome-Terminal border disappears entirely when using: "Text and Background Color" | Green on Black. When terminal windows overlap, as in my Linux Lab, it is difficult to quickly distinguish between output from various windows. This created a great deal of frustration for the students - some reverted to Mint 18.3, others used a different Debian-based Distro, or Arch to avoid the problem.

**Steps to reproduce**
In gnome-terminal, click Edit, Preferences, Colors (tab), and choose to NOT use the System Theme, but use "Green on Black" instead.

Open several terminal windows and begin your work. You will find that it is difficult to locate or distinguish one terminal of text from the other due to the missing border. (example screenshot attached from a new boot)

**Expected behaviour**
A thin border will be present on the window at all times.

**Other information**
I thought that this might be a feature until I discovered through my own use that the terminals became unusable in a production environment due to the lack of a discernable border. Changing the Theme to Mint-X for borders will correct this issue; however, this is a workaround that requires a previous theme.

Thank you for all you do!

![theme_terminal_issue](https://user-images.githubusercontent.com/36276704/46882196-52aa0080-ce3d-11e8-86ff-a45583be0c82.png)

**Comment by icarter09** [comment]
@ppoteete are you still experiencing this issue?

**Comment by JosephMcc** [comment]
Closing this for a couple reasons. It isn't a bug in Cinnamon at all. It's the design  of the Mint-Y theme. The entire reason we go through the trouble and effort of keeping the Mint-X theme up-to-date is so users who don't like the newer design can easily switch back the the older style. It's shipped in all new versions of Mint.
