### ISSUE TITLE
You can create an option to lock desklets and their relative location?

### ISSUE THREAD

**Issue by xzj8b3** [linuxmint/Cinnamon#7933]
You could create an option to lock Desklet on your desktop is annoying when on notebooks you accidentally hook up to the mouse or pad

 * Cinnamon version (3.8.9)
 * Distribution - (Fedora 29, beta x86-64)
 * Intel Haswell-ULT Integrated Graphicsdriver: i915 v: kernel
AMD Mars LE [Radeon HD 8530M / R5 M240
x11 server: Fedora Project X.org 1.20.1 driver: radeon

**Comment by JosephMcc** [comment]
Search can be your friend ;) https://github.com/linuxmint/Cinnamon/issues/3767

**Comment by xzj8b3** [comment]
Be is right the guy
