### ISSUE TITLE
Can you create a desklet or Applett connect to feedly??

### ISSUE THREAD

**Issue by xzj8b3** [linuxmint/cinnamon#7934]
Can you create a desklet or Applet connect to feedly offering the option to select the Preferred folder to display updates and the number of items to show??

 * Cinnamon version (cinnamon --3.8.9)
 * Distribution - (Fedora 29 beta x86-64.)
 *  Intel Haswell-ULT Integrated Graphics driver: i915 
 * x86-64
 
AMD Mars LE [Radeon HD 8530M / R5 M240] driver: radeon
Display: x11 server: Fedora Project X.org 1.20.1 driver: radeon 
1366x768~60Hz 
OpenGL: renderer: Mesa DRI Intel Haswell Mobile v: 4.5 Mesa 18.2.2

**Comment by icarter09** [comment]
@xzj8b3 feel free to post any general questions on the Linux Mint forums.

https://forums.linuxmint.com/
