### ISSUE TITLE
Gsconnect Can it be integrated??

### ISSUE THREAD

**Issue by xzj8b3** [linuxmint/cinnamon#7935]
Wonderful work with Cinnamon 3.8.9, I have not tried for a long time but much improved and we hope to continue...

You can create an extension like Gsconnect and  "Send to Disositivo " For Nemo which is very convenient for exchanging files and links with your Smartphone??? 

Cinnamon version (cinnamon --3.8.9)
Distribution - (Fedora 29 beta x86-64.)
Intel Haswell-ULT Integrated Graphics driver: i915
x86-64
AMD Mars LE [Radeon HD 8530M / R5 M240] driver: radeon
Display: x11 server: Fedora Project X.org 1.20.1 driver: radeon
1366x768~60Hz
OpenGL: renderer: Mesa DRI Intel Haswell Mobile v: 4.5 Mesa 18.2.2

**Comment by icarter09** [comment]
@xzj8b3 is this an issue or question about Cinnamon?

**Comment by xzj8b3** [comment]
> @ xzj8b3 è un problema o una domanda su Cinnamon?



Given currently I have on the notebook Fedora 31 and use Gsconnect 

I would like to install Cinnamon too soon, but how can I enable the extension to avoid messes given you write?? I've seen kdeconnect before already inserted or wrong?

**Comment by JosephMcc** [comment]
Someone would need to write an applet to support this functionality in Cinnamon. Thank you for the request.

**Comment by Banane84** [comment]
This could be a real improvment to decide people to switch to cinammon

**Comment by KAMI911** [comment]
I love this idea!
