### ISSUE TITLE
Highlighting text with the mouse pointer randomly skips or deselects

### ISSUE THREAD

**Issue by jameshiew** [linuxmint/Cinnamon#7951]
```
 * Cinnamon version (cinnamon --version)
3.6.7
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
Ubuntu 18.04.1 LTS
 * Graphics hardware *and* driver used
 * 32 or 64 bit
64 bit
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
Unsure if I can share
 ```

**Issue**
When trying to highlight/select a block of text with the mouse pointer, very often (within a second or two, most times) all selected text deselects. It happens in multiple programs e.g. the terminal, Visual Studio Code, IntelliJ IDEA, etc. This gives the impression of text selection 'skipping' i.e. some text deselecting and then new text becoming selected, within the text block you are trying to highlight, and makes it very difficult to highlight/select large blocks of text.

**Steps to reproduce**
Attempt to highlight some text with the mouse pointer by dragging the pointer over some text whilst holding the left mouse button down

**Expected behaviour**
Text dragged over with the mouse pointer should become highlighted/selected and remain that way

**Other information**
This only started happening recently - within the past couple of weeks.

**Comment by leigh123linux** [comment]
Have you tried using another mouse to confirm yours isn't dying?

**Comment by jameshiew** [comment]
Using another mouse seems to have solved the problem, thanks! Apologies for using the issues tracker as a help desk, I should've tried this first, it had nothing to do with Cinnamon.
