### ISSUE TITLE
[FEATURE REQUEST] gsconnect for cinnamon

### ISSUE THREAD

**Issue by gnurichard** [linuxmint/Cinnamon#7952]
I imagine, that all or almost everyone knows gsconnect, is an implementation of kdeconnect for gnome. I think it would be very useful and interesting to be able to port it to cinnamon, I think it would only be porting the gnome-shell addon or rewriting it, unfortunately I lack the knowledge to do it

**Comment by leigh123linux** [comment]
https://github.com/linuxmint/Cinnamon/issues/7935
