### ISSUE TITLE
Files missing from Desktop but are visible with "ls" command

### ISSUE THREAD

**Issue by hrutie** [linuxmint/Cinnamon#7953]
```
 * Cinnamon version (cinnamon --version)
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
 * Graphics hardware *and* driver used
 * 32 or 64 bit
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
 ```

environment:
Linux Mint 18.1 Cinnamon 64-bit, Cinnamon version 3.2.7, Linux Kernel 4.4.0-53-generic..
3 monitors.
cat /etc/linuxmint/info
RELEASE=18.1
CODENAME=serena
EDITION="Cinnamon 64-bit"
DESCRIPTION="Linux Mint 18.1 Serena"
DESKTOP=Gnome
TOOLKIT=GTK
NEW_FEATURES_URL=http://www.linuxmint.com/rel_serena_cinnamon_whatsnew.php
RELEASE_NOTES_URL=http://www.linuxmint.com/rel_serena_cinnamon.php
USER_GUIDE_URL=help:linuxmint
GRUB_TITLE=Linux Mint 18.1 Cinnamon 64-bit

** Steps to reproduce **
This is certainly not the only way to see the error.
In /home/oem/Desktop have about 100 files/folders visible on Desktop
Move cursor to unused area of Desktop on primary monitor and right-click.
Desktop layout popup becomes visible.
The choice to the right of "Desktop layout" is "Show desktop icons on all monitors".
Can see files/folders on primary monitor which is in the center.
Reboot.
After reboot can see only files/folders on left-most and right-most monitors.

Workaround:
Bring up Desktop layout and change option to "Show desktop icons on non-primary monitor(s) only" then change it to "Show desktop icons on all monitors" and the missing files/folder re-appear on primary monitor.

**Expected behaviour**
 Expect that when computer starts all files from Desktop are visible and match what one can see by doing "ls" in home directory

**Other information**
Don't know if there is something in the computer environment that helps cause the problem.

++++++

 /home/<username>/.xsession-errors

initctl: Unable to connect to Upstart: Failed to connect to socket /com/ubuntu/upstart: Connection refused
syndaemon: no process found
/etc/mdm/Xsession: Beginning session setup...
localuser:oem being added to access control list
** Message: couldn't access control socket: /run/user/1000/keyring/control: No such file or directory
** Message: couldn't access control socket: /run/user/1000/keyring/control: No such file or directory
** Message: couldn't access control socket: /run/user/1000/keyring/control: No such file or directory
SSH_AUTH_SOCK=/run/user/1000/keyring/ssh
cinnamon-session[1169]: WARNING: t+0.93020s: Failed to start app: Unable to start application: Failed to execute child process "indicator-sensors" (No such file or directory)
Cjs-Message: JS LOG: About to start Cinnamon
St-Message: cogl npot texture sizes SUPPORTED
Cjs-Message: JS LOG: Cinnamon started at Mon Oct 22 2018 20:28:19 GMT-0700 (PDT)
Nemo-Share-Message: Called "net usershare info" but it failed: 'net usershare' returned error 255: mkdir failed on directory /var/run/samba/msg.lock: Permission denied
net usershare: cannot open usershare directory /var/lib/samba/usershares. Error No such file or directory
Please ask your system administrator to enable user sharing.

Cjs-Message: JS LOG: network applet: Cannot find connection for active (or connection cannot be read)
openGL version 3.3 detected (GL3 Cogl Driver)
MetaSyncRing disabled: couldn't find required GL extensions, or the minimum safe openGL version was not met
failed to create drawable
Cjs-Message: JS LOG: Invalid network device type, is 14
Cjs-Message: JS LOG: network applet: Found connection for active
mintUpdate: no process found
~                                                                                                                                     
~                  
++++++

/var/log/syslog

Oct 22 09:04:41 freekbox anacron[798]: Job `cron.daily' terminated
Oct 22 09:04:41 freekbox anacron[798]: Normal exit (1 job run)
Oct 22 09:08:55 freekbox ntpd[963]: 91.189.89.199 local addr 192.168.1.106 -> <null>
Oct 22 09:08:56 freekbox ntpd[963]: 91.189.89.198 local addr 192.168.1.106 -> <null>
Oct 22 09:08:56 freekbox ntpd[963]: 45.63.20.61 local addr 192.168.1.106 -> <null>
Oct 22 09:14:36 freekbox systemd[1]: Starting Cleanup of Temporary Directories...
Oct 22 09:14:36 freekbox systemd-tmpfiles[3538]: [/usr/lib/tmpfiles.d/var.conf:14] Duplicate line for path "/var/log", ignoring.
Oct 22 09:14:36 freekbox systemd[1]: Started Cleanup of Temporary Directories.
Oct 22 09:17:01 freekbox CRON[3596]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Oct 22 09:53:33 freekbox dbus[768]: [system] Activating via systemd: service name='org.bluez' unit='dbus-org.bluez.service'
Oct 22 09:53:33 freekbox org.gnome.keyring.SystemPrompter[1597]: Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
Oct 22 09:53:35 freekbox org.gnome.keyring.SystemPrompter[1597]: Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
Oct 22 09:53:36 freekbox org.gnome.keyring.SystemPrompter[1597]: Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
Oct 22 09:53:36 freekbox org.gnome.keyring.SystemPrompter[1597]: Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
Oct 22 10:17:01 freekbox CRON[5256]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Oct 22 10:36:01 freekbox kernel: [ 5787.443060] [drm:cypress_dpm_set_power_state [radeon]] *ERROR* rv770_restrict_performance_levels_before_switch failed
Oct 22 11:17:01 freekbox CRON[6368]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Oct 22 12:17:01 freekbox CRON[6864]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Oct 22 13:17:01 freekbox CRON[7734]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Oct 22 14:17:01 freekbox CRON[8193]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Oct 22 15:04:54 freekbox kernel: [21922.023492] perf interrupt took too long (2504 > 2500), lowering kernel.perf_event_max_sample_rate to 50000
Oct 22 15:17:01 freekbox CRON[9288]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Oct 22 16:17:01 freekbox CRON[10128]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Oct 22 17:17:01 freekbox CRON[11015]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Oct 22 18:17:01 freekbox CRON[11487]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
"/var/log/syslog" [readonly] 1444 lines, 144652 characters

**Comment by leigh123linux** [comment]
Please report the issue against nemo.
