### ISSUE TITLE
Cinnamon does not initialize on secondary monitors after login

### ISSUE THREAD

**Issue by gkatev** [linuxmint/cinnamon#7958]
```
 * Cinnamon: 3.8.9
 * Distribution: Antergos
 * Radeon HD 7850 with amdgpu driver
 * 64 bit
 ```

**Issue**
For the past month or so, after logging into (not unlocking) my computer, my secondary monitors don't work and the desktop appears only on the primary one. Running a simple xrandr command enables them but it also causes some black artifacts around windows, as described in #7665. Running 'cinnamon --replace' fixes them.

It's likely that this is not a cinnamon problem, but combined with the artifact problem it seems possible. Is anyone else encountering a similar problem or should I look beyond cinnamon?

[xsession-errors.txt](https://github.com/linuxmint/Cinnamon/files/2514510/xsession-errors.txt)
[xorg.conf.txt](https://github.com/linuxmint/Cinnamon/files/2514511/xorg.conf.txt)

**Comment by icarter09** [comment]
@gkatev are you still experiencing this issue?

**Comment by gkatev** [comment]
No, I am not. It was fixed by itself.
