### ISSUE TITLE
Title bar buttons are not highlighted correctly when the shade button Is used

### ISSUE THREAD

**Issue by amangrewal** [linuxmint/cinnamon#7962]
```
 * Cinnamon version: 3.8.9
 * Distribution - Arch
 * Graphics hardware: Nvidia GeForce GTX 560 SE
 * Graphics driver: nouveau
 * 64 bit
 ```

**Issue**

Title bar buttons are not highlighted correctly when the shade button is used.
The button to the right of where the mouse is hovering is highlighted (see attached images).

Note that the button that the mouse is over will still be clicked, not the highlighted button. 
In other words, this does not make any buttons unclickable. It's just annoying.

**Steps to reproduce**

Add the shade title bar button to windows, and make sure there is at least one more button directly to the right of it.

**Other information**
![configuration1-left](https://user-images.githubusercontent.com/5739325/47610374-939b3b00-da21-11e8-95e4-1d3a9e12f2da.jpg)
![configuration1-right](https://user-images.githubusercontent.com/5739325/47610375-939b3b00-da21-11e8-9162-b6699aeed54f.jpg)
![configuration2-right](https://user-images.githubusercontent.com/5739325/47610376-939b3b00-da21-11e8-9e36-a917f496bf07.jpg)

**Comment by smurphos** [comment]
Can you reproduce this with a different Metacity (Window borders) theme? I'm using Cinnamox-Rhino (you can try it from the Add/Remove tab in the Themes settings module) and don't see any problem with shaded title bar button highlighting on 3.8.9.

**Comment by amangrewal** [comment]
I was not able to reproduce this with Cinnamox-Rhino or Adapta-Nokto. It might just have been an issue with never having picked a theme.

**Comment by amangrewal** [comment]
I tried some more themes. Some themes were missing icons, but none of the themes that displayed a button for shade had this problem.

**Comment by smurphos** [comment]
I guess it's a problem with the default Metacity theme provided by Arch. You should raise the issue with the Arch Cinamon maintainer/packager.

**Comment by amangrewal** [comment]
Issue submitted in the arch bug tracker (https://bugs.archlinux.org/task/60626).

I don't know what the SOP is here. Unless a maintainer wants to close it earlier, I'll close it once the issue is confirmed to be downstream.
