### ISSUE TITLE
[Feature Request]: window tiling automatic resize, highlighting in xreader and trash sound effect 

### ISSUE THREAD

**Issue by lalincedeldeserto** [linuxmint/cinnamon#7966]
Hi Linux Mint developers!! 

I have three suggestions (I'm referring to Cinnamon desktop):

1. Related to the desktop:
Add to window tiling this function: if you resize one of the windows, the other one will also resize automatically to void any overlap. (Such as Elementary OS 5 → https://youtu.be/Ih6ZGghiXjo?t=127).

2. Related to Xreader (pdf reader). Add a highlighter and the possibility to add comments.

3.  That's less important  
Add trash sound effect when it is emptied

Thank you all for the giant work you're doing!!  :wink:

**Comment by NikoKrause** [comment]
About 1:
That's something, which needs to be done in nemo: https://github.com/linuxmint/nemo

About 2:
https://github.com/linuxmint/xreader/pull/223

About 3:
I remember Windows had this o.O ;)

**Comment by lalincedeldeserto** [comment]
Thanks for replying :smiley:

**Comment by ManIVIctorious** [comment]
@nikokrause you are right about the points 2 and 3 but I am pretty sure everything tiling related should be assigned to muffin and/or cinnamon

**Comment by JosephMcc** [comment]
The window tiling thing has absolutely nothing to do with Nemo. It would be handled by Muffin. The last time I tried that feature in Mutter it was less than stellar. The performance and redraws when resizing was really poor.

**Comment by lalincedeldeserto** [comment]
@JosephMcc IMHO if the tiling window is unstable it's better to wait until there isn't a better solution :+1: 
Window tiling must be reactive. If it isn't, it's unusable.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
