### ISSUE TITLE
Hibernate does not work (must force power off and restart) on Dell Latitude E7440

### ISSUE THREAD

**Issue by christophe-dupriez** [linuxmint/Cinnamon#7968]
```
 * Cinnamon version : 3.4.6
 * Distribution - Mint 18.2
 * Graphics hardware *and* driver used: Computer is Dell Latitude E7440 (laptop)
 * 64 bit
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
 ```

**Issue**
SINCE LAST KERNEL UPDATE, if hibernation is requested (from start menu for instance), the power button remains ON and the only way to resume is to keep it pressed up to power down and restart.

**Steps to reproduce**
* Request "hibernate" from start menu.

**Expected behaviour**
Being able to resume

**Other information**
This behaviour is since last kernel update. A similar situation arise in January 2018 and was corrected at beginning of summer (at that time, the hibernate was powering off correctly but restart was freezing). The person working on this piece of code can ask me to test on DELL laptop Latitude E7440 !

**Comment by leigh123linux** [comment]
Your issue should be filed against the kernel not cinnamon.
