### ISSUE TITLE
[Feature Request] Implement a tray-icon allowing users to switch between Integrated and Dedicated AMD mobile cards

### ISSUE THREAD

**Issue by rdlf4** [linuxmint/Cinnamon#7988]
_Moderators: No, this has nothing to do with #7965_
I'm proposing Linux Mint enables a tray-icon that will:
A) Let the user set which mobile graphics card they'd like to use for whatever application; or
B) Application-Specific: Does not enable the dedicated card, unless the user specify which application(s) or game(s) they associate with option (B). The moment the user launches the application in question, Linux Mint will:
* Set the CPU Frequency scaling governor to PERFORMANCE;
* If Compiz is the current window manager, switch it to Marco+Compositing;
(NOTE: Mint will switch the window manager back to Compiz after the user-specified application has been exited or terminated)
* Offload the task to the dGPU with:
`xrandr --setprovideroffloadsink 1 0` ;
Execute: PRIME_DRI=1 %user-specified application or game%

Reference: https://forums.linuxmint.com/viewtopic.php?f=59&t=280918&p=1548712#p1548712

**Comment by JosephMcc** [comment]
It would make a lot more sense to submit this here: https://github.com/linuxmint/linuxmint

Things like switching between Marco and Compiz have absolutely nothing to do with Cinnamon.
