### ISSUE TITLE
[Feature Request] Different network icon between disabled wi-fi and not connected.

### ISSUE THREAD

**Issue by a-bentofreire** [linuxmint/cinnamon#7992]
```
 * Cinnamon 3.8.9 (Gtk 3.22.30) 
 * Linux Mint 19 Tara
 *  Card: Intel HD Graphics 520
 * 64 bit

 ```
**Issue**
The icon for wi-fi disabled and not connected to wi-fi is the same.  
Many times to save power when I'm working outside the office, I have to disable wi-fi,
and it's confusing when the wi-fi is enabled, I need wi-fi and wi-fi spot came down.  
Having different icons would be tremendously helpful.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
