### ISSUE TITLE
4.0 Menu power icons too small

### ISSUE THREAD

**Issue by dalu** [linuxmint/Cinnamon#7993]
```
 * Cinnamon 4.0.0
 * Archlinux
 * 64 bit
 ```

**Issue**

![screenshot from 2018-11-07 12-34-09](https://user-images.githubusercontent.com/2694548/48130762-fdbba780-e28d-11e8-8a9f-93a161825670.png)

The power off, switch user, log out, lock screen buttons/icons are too small.
It was better when they were aligned on the left side of the menu and they were bigger.

**Steps to reproduce**

Open the default menu on a 4k display

**Expected behaviour**

Larger buttons

**Other information**

**Comment by dalu** [comment]
As a temporary workaround one could edit line 899 of `/usr/share/cinnamon/applets/menu@cinnamon.org/applet.js`

```ts
let icon_size = 24;
```

which is just the right size if you ask me, 16 is too small and 32 too big.

**Comment by setsunati** [comment]
I don't like the power icons being moved to top right position. Please keep it to bottom left like before. Or allow us to configure positions of power icons on Cinnamon Menu so i can configure power icons to to show on bottom left like before.

**Comment by leigh123linux** [comment]
I am locking this issue as we don't need drozens of addition comments.
This is being worked on.

**Comment by NikoKrause** [comment]
Changed in Cinnamon 4.0.1
