### ISSUE TITLE
Cinnamon crash/ issues after running infinite loop script

### ISSUE THREAD

**Issue by LightningProd** [linuxmint/cinnamon#7994]
```
 * Cinnamon 3.8.9
 * Linux Mint 19 Cinnamon (upgraded from 18.3)
 * AMD A4-1200 APU, default (Xorg?) driver
 * 64 bit
 ```

**Issue**

After running a bash script with an infinite loop, Cinnamon crashed and was bug-filled on the next startup.

I got redirected to a text-only screen (like tty1) but it wasn't a bash terminal - although I could type.
After about 30 seconds, I got redirected to the login screen.

After signing in (to the Cinnamon DE), I started having weird issues. The mouse grabbed one of my desklets and moved it, although my mouse cursor was on the opposite side of the screen. The <kbd>Up</kbd>, <kbd>Down</kbd>, <kbd>Left</kbd>, and <kbd>Right</kbd> keys started behaving wierd, as if I was holding down the <kbd>Fn</kbd> key (I was not).

**How I caused it**

I ran the script below, while attempting to select the terminal and press CTRL+C (because I was working on a similar script, but it had a bug).

**Steps to reproduce**

Put this is a bash script called `test.sh`:

```
while :
do
xdotool mousemove 740 460
echo "Please wait..."
done
```

and run it (`bash test.sh`).

**Expected behaviour**

Cinnamon gets slow, but still runs.

**Other information**

System logs:
[syslog.2.gz](https://github.com/linuxmint/Cinnamon/files/2560011/syslog.2.gz)
[syslog.3.gz](https://github.com/linuxmint/Cinnamon/files/2560012/syslog.3.gz)
[syslog.4.gz](https://github.com/linuxmint/Cinnamon/files/2560013/syslog.4.gz)
[syslog.5.gz](https://github.com/linuxmint/Cinnamon/files/2560014/syslog.5.gz)
[syslog.6.gz](https://github.com/linuxmint/Cinnamon/files/2560015/syslog.6.gz)
[syslog.7.gz](https://github.com/linuxmint/Cinnamon/files/2560016/syslog.7.gz)

**Comment by jaszhix** [comment]
This script seems to keep the cursor tied to a particular part of the screen, but nothing else happens for me except the terminal being flooded. Ctrl + c regains control, and Cinnamon didn't crash. I'm running Cinnamon 4.0.0. I don't see any segfaults in your logs.
