### ISSUE TITLE
Can I hide the session buttons in the Cinnamon 4.0 menu applet?

### ISSUE THREAD

**Issue by Darthpenguin** [linuxmint/Cinnamon#7995]
```
 * Cinnamon 4.0.0
 * Distribution: Arch
 * Intel Graphics
 * 64 bit
 ```

**Issue**
More like a feature request or help coding.
I would like to remove the logoff, shutdown, switch user, etc. from the Cinnamon 4.0 Menu applet. I have copied the applet from /usr/share/cinnamon/applets/menu@cinnamon.org/ to ~/.local/share/cinnamon/applets/menu@cinnamon.org/. I can uncomment everything between line 2630 and 2715 in applet.js to hide everything except the "Quit" button. I have tried commenting out other lines of code but I cannot seem to hide the Quit button without crashing the applet.

A setting option to hide the buttons would be great or even just a pointer on how I can edit the js code myself would be awesome.

**Comment by NikoKrause** [comment]
Changed in Cinnamon 4.0.1
