### ISSUE TITLE
 Keyboard repeat phantom keystroke

### ISSUE THREAD

**Issue by zxfghwr** [linuxmint/cinnamon#8002]
```
 * Distribution - LMDE 64 bit with the latest update:
Linux 4.9.0-8-amd64 #1 SMP Debian 4.9.110-3+deb9u6 (2018-10-08) x86_64 GNU/Linux

 ```

**Issue**
Phantom keystroke like theseeeeeeeeeeeeeeeeeeeeeeeeeee

**Steps to reproduce**
It happens randomly after typing and keeps repeating until you press another key.

**Expected behaviour**
The same keyboard was used in a Linux Mint Cinnamon edition install with no issue. I start getting these phantom keystrokes after I had a fresh Linux Mint LMDE install on a new harddrive.

**Other information**
Found a similar bug report online under ubuntu source that is supposedly fixed back in 2006. Don't know why it reappeared in LMDE.
https://bugs.launchpad.net/ubuntu/+source/linux-source-2.6.15/+bug/39315

**Comment by claudiux** [comment]
Also in Linux Mint 19 with Cinnamon 3.8, on some computers.

**Comment by icarter09** [comment]
@claudiux is this still an issue?

**Comment by claudiux** [comment]
@icarter09 Not for Mint 19.2 with Cinnamon 4.2 or 4.4. For LMDE, I don't know.

**Comment by icarter09** [comment]
@claudiux thanks for the update.
