### ISSUE TITLE
Application Icons are too close when 16px is chosen for right area of taskbar

### ISSUE THREAD

**Issue by JpegXguy** [linuxmint/cinnamon#8007]
```
 * Cinnamon 4.0.0
 * Manjaro 18
 * VGA compatible controller [0300]: Intel Corporation Haswell-ULT Integrated Graphics Controller [8086:0a16] (rev 0b), so driver is i915
 * 64 bit
 ```

In cinnamon 4.0.0 in the new settings for the task bar there is a setting for the left, center, and right areas of the bar. 

If you choose 16px for the right area (where the icons for applets reside, in my case) then the program icons come too close to each other.

Notice here in the far left: (The icons are transmission-gtk and pamac-tray)

Before:
![taskbar before](https://user-images.githubusercontent.com/29687487/48265874-5ded4d80-e436-11e8-985a-38e912d84ef1.png)

After:
![taskbar now](https://user-images.githubusercontent.com/29687487/48265875-5ded4d80-e436-11e8-9acc-1e9616b5a5ea.png)

**Comment by icarter09** [comment]
@JpegXguy are you still experiencing this issue?

**Comment by JpegXguy** [comment]
Everything's been good for a while. Running cinnamon 4.4.3 by now
