### ISSUE TITLE
Display settings: Not possible to mirror and extend simultaneously

### ISSUE THREAD

**Issue by Arpy222** [linuxmint/cinnamon#8011]
```
 * Cinnamon 3.8.9
 * Linuxmint 19
 * Nvidia GTX960, nvidia driver 396
 * 64 bit
 ```

**Issue**
Hi!
I have 3 active displays, 1 TV, and two monitors.
I like to mirror the TV with one of the monitor, and then extend the other monitor next to it.
When I'm dragging the icon of displays, It's not possible to put one on another (so mirror), when both displays are active.

**Steps to reproduce**
Starting point:
![image](https://user-images.githubusercontent.com/10313156/48307059-4355ca00-e545-11e8-8878-313ea4fa94b8.png)

I woud like to mirror the green with the orange one, but it is not possible to pull on that, when the display is active.
One possible workaround:
1. Disable display green, then save.
2. Pull display green onto display orange, then save.
3. Enable back again display green, and save.

Final outcome:
![image](https://user-images.githubusercontent.com/10313156/48307082-ea3a6600-e545-11e8-9363-9618c067f2e7.png)
In this case, if I would click on the icon of display green, then it would instantly jump off from display orange, so this state is not really managed respectfully (but at least it works).

**Comment by icarter09** [comment]
@Arpy222 are you still experiencing this issue?

**Comment by Vahan86** [comment]
@icarter09, can we close the issue since there is no response from OP?

**Comment by Arpy222** [comment]
I have just tested on Linux Mint 19.3, and the issue is still present. :-/
