### ISSUE TITLE
Icon Picker in Xlet settings fails with png icons and display issue.

### ISSUE THREAD

**Issue by smurphos** [linuxmint/Cinnamon#8012]
```
 * Cinnamon version  4.0.0
 * Distribution - Manjaro (testing - package version 4.0.0-1.2)
 * Device-1: Intel 2nd Generation Core Processor Family Integrated Graphics 
  driver: i915 v: kernel 
  Display: x11 server: X.Org 1.20.3 driver: intel unloaded: modesetting 
  tty: N/A 
  OpenGL: renderer: Mesa DRI Intel Sandybridge Mobile v: 3.3 Mesa 18.2.4 
 * 64 bit
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
 ```
.xsession-error - `Cinnamon warning: Log level 128: posix_spawn avoided (automatic reaping requested) (fd close requested)` on opening xlet configuration.

`Cjs-Message: 05:28:44.172: JS WARNING: [/usr/share/cinnamon/js/misc/fileUtils.js line 210 > Function 514]: reference to undefined property "iconTheme"` on restarting Cinnamon when an problematic icon has been applied.

**Issue**

Using the new icon picker to set a custom icon for the stock menu applet or for Cinnamenu.

1) Icon picker allows selection of both svg and png format icons. Some png format icons fail to apply, svg appear to be OK. Attached are two that fail to apply. The icon doesn't change in the panel once selected and after a Cinnamon restart no icon is displayed.

2) If a custom icon has successfully been set, when the xlet settings are opened again the settings GUI does not display the custom icon, but displays a place-holder.

**Steps to reproduce**

Attached are two icons that consistently fail to apply, but are available to choose in the icon picker. Both are from the root of `/usr/share/icons/`

**Expected behaviour**

Icons should apply, or not compatible icons should not be available to select.

**Other information**
Icons that fail attached.

`/usr/share/icons/manjaro-shiny.png`
`/usr/share/icons/menu-maia.png`

Panel size is 30px - icons set to scale optimally to panel size. I've tested a few different panel settings and it doesn't appear to affect the issue.

Is this because the icons are outside of an defined icon theme and just sat in the root of `/usr/share/icons/` ? Should the picker be saving the pull path to the icon chosen? I note from the xlet stored settings that only the icon name is stored, not the full path.

[Icons.zip](https://github.com/linuxmint/Cinnamon/files/2569082/Icons.zip)

**Comment by mtwebster** [comment]
This I believe has been fixed in xapps: https://github.com/linuxmint/xapps/commit/c8d54a2420cfe2ec1028e22e40764b510da62bb3
