### ISSUE TITLE
REMEMBER STATE OF (primary button @ mouse menu) : Desktop : Icon Size setting!

### ISSUE THREAD

**Issue by aspadistra** [linuxmint/cinnamon#8014]
REMEMBER STATE OF (primary button @ mouse menu) : Desktop : Icon Size setting!
People have to reajust the icon size if there is some snafu and they just do not fit ...
It happens every boot. 
There is no CONTROL PANEL SETTING for "Icons Autorefresh" and "Default Size" 

```
 * Cinnamon version (cinnamon --version) == Cinnamon 3.6.7
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) 
 * Graphics hardware *and* driver used ... 
 * 32 or 64 bit : 64 Bit
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
 ```

**Issue**

REMEMBER STATE OF (primary button @ mouse menu) : Desktop : Icon Size setting!
People have to reajust the icon size if there is some snafu and they just do not fit ...
It happens every boot. 
There is no CONTROL PANEL SETTING for "Icons Autorefresh" and "Default Size" 

**System as it is**

-Computer-
Processor		: 4x Intel(R) Core(TM) i3-2120 CPU @ 3.30GHz
Memory		: 8078MB (2369MB used)
Operating System		: Linux Mint 18.3 Sylvia
User Name		: not root !
Date/Time		: Sun 11 Nov 2018 09:27:09 AM PST
-Display-
Resolution		: 1024x768 pixels
OpenGL Renderer		: Mesa DRI Intel(R) Sandybridge Desktop 
X11 Vendor		: The X.Org Foundation
-Multimedia-
Audio Adapter		: HDA-Intel - HDA Intel PCH
-Input Devices-
 Power Button
 Power Button
 Lite-On Technology Corp. USB Multimedia Keyboard
 Lite-On Technology Corp. USB Multimedia Keyboard
 PIXART USB OPTICAL MOUSE
 HDA Intel PCH Front Mic
 HDA Intel PCH Rear Mic
 HDA Intel PCH Line
 HDA Intel PCH Line Out
 HDA Intel PCH Front Headphone
 HDA Intel PCH HDMI/DP,pcm		: 3=
-Printers-
No printers found
-SCSI Disks-
ATA WDC WD5000BPVX-0
ATA Faspeed F510-120
Generic- Compact Flash
Generic- Multi-Card

-Display-
Resolution		: 1024x768 pixels
Vendor		: The X.Org Foundation
Version		: 1.18.4
-Monitors-
Monitor 0		: 1024x768 pixels
-Extensions-
BIG-REQUESTS
Composite
DAMAGE
DOUBLE-BUFFER
DPMS
DRI2
GLX
Generic Event Extension
MIT-SCREEN-SAVER
MIT-SHM
Present
RANDR
RECORD
RENDER
SECURITY
SGI-GLX
SHAPE
SYNC
X-Resource
XC-MISC
XFIXES
XFree86-DGA
XFree86-VidModeExtension
XINERAMA
XInputExtension
XKEYBOARD
XTEST
XVideo
-OpenGL-
Vendor		: Intel Open Source Technology Center
Renderer		: Mesa DRI Intel(R) Sandybridge Desktop 
Version		: 3.0 Mesa 18.0.5
Direct Rendering		: Yes

**Comment by icarter09** [comment]
@aspadistra are you still experiencing this issue?

**Comment by JosephMcc** [comment]
I'm closing this one. Maybe it's just me but I don't actually even understand what the issue is. We would need a bit better explanation.
