### ISSUE TITLE
OS doesn't determine if headphones were ejected during sleep

### ISSUE THREAD

**Issue by ntfs1984** [linuxmint/cinnamon#8016]
```
 * Cinnamon version 3.8.8
 * Distribution - Mint 19 Tara
 * Intel graphics
 * 64 bit

 ```

**Issue**
Operating system doesn't determine if sound output was changed in sleep mode

**Steps to reproduce**

1. Plug headphones into notebook or some device with internal speakers and headphones jack. Sound will be output in headphones;
2. Put device into sleep mode (close lid of notebook);
3. Unplug headphones from jack;
4. Return device from sleep;
5. Sound output will be still via headphones, not internal speakers.

**Expected behaviour**

Operating system should determine if headphones were unplugged, and then back sound output to internal speakers. At least sound settings plugin should display all output devices and let switch it manually.

**Other information**
To be honest I'm not sure if it's Mint's or Cinnamon's specific issue, it can be also pulseaudio's bug. 
BTW, pulseaudio restart didn't help.
So any suggestion including shell script will be helpful, because for now only one way to fix this issue - completely reboot device.

**Comment by icarter09** [comment]
Cinnamon 3.8.9
Linux Mint 19 64bit

@ntfs1984 I'm not able to reproduce this issue with the steps you provided. I also tested out plugging the headphones in during sleep mode, and the headphones would be recognized by Mint. I was using the Sound applet to verify the testing and not PulseAudio. 
Can you test this out using the Sound applet? I think your suggestion of it being a PulseAudio bug might be correct.
