### ISSUE TITLE
Mouse is too slow

### ISSUE THREAD

**Issue by mondalaci** [linuxmint/cinnamon#8029]
```
 * Cinnamon version: 3.8.9
 * Distribution: Mint 19
 * Graphics hardware *and* driver used: Geforce GTX 970, Nvidia driver 410.73
 * 64 bit
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog: 
 ```
[.xsession-errors.txt](https://github.com/linuxmint/Cinnamon/files/2589080/default.xsession-errors.txt)

I've just upgraded to Linux Mint 19, featuring a new Cinnamon version. Previously, my mouse speed settings were fine. Now, the pointer is too slow.

In the "Mouse and Touchpad" settings, changing the acceleration setting actually changes mouse speed, but I can't feel any change when tweaking the sensitivity setting. No matter how I set the sliders, my mouse is too slow.

**Comment by NikoKrause** [comment]
Can you try:
```
apt install xserver-xorg-input-synaptics
```
Then log out and log back in.

**Comment by mondalaci** [comment]
I did as you suggested, and the issue still persists. I should note that I'm using a Logitech G502 mouse.

**Comment by NikoKrause** [comment]
https://bbs.archlinux.org/viewtopic.php?id=221980

**Comment by mondalaci** [comment]
I've already been there, and gave a try to the `xinput` utility. I could set the same thresholds as via the Cinnamon settings UI, and got the same results.

**Comment by Vedrillan** [comment]
I confirm that the sensitivity setting in Cinnamon does not work with the Logitech G502, however it is possible to adjust it with the DPI mode change buttons on the mouse. First click on G9 bellow the wheel then G7/G8 to rise or lower the DPI.

So it might not even be an issue with Cinnamon but with whatever control the mouse settings, it probably have a conflict between software sensitivity and hardware DPI modes, maybe it can not manage both, but I do not know how to confirm that.

**Comment by icarter09** [comment]
@mondalaci are you still experiencing this issue?

**Comment by mondalaci** [comment]
@icarter09 I'm not sure because I'd have to downgrade to a previous Cinnamon version to compare the mouse speed of the two versions. In any case, my mouse speed feel fine now. I'm on Cinnamon 4.2.4.

**Comment by JosephMcc** [comment]
Ok, going to close this for now then.
