### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by Zielony20** [linuxmint/Cinnamon#8030]
```
 * Cinnamon version (cinnamon --version)
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
 * Graphics hardware *and* driver used
 * 32 or 64 bit
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
 ```
I have installed Mint 19 mate and then I decide to change on cinnamon so I installed package mint-meta-cinnamon and I'm not having a system program to making screenshots now but when I change on mate it appears.

**Issue**

**Steps to reproduce**

**Expected behaviour**

**Other information**

**Comment by NikoKrause** [comment]
The application you are searching for is called GNOME screenshot.
