### ISSUE TITLE
Program "Take screenshots" is missing in menu after install Cinnamon by package

### ISSUE THREAD

**Issue by Zielony20** [linuxmint/cinnamon#8031]
```
 * Cinnamon version : 3.8.9
 * Distribution : Linux Mint 19 MATE
 * Graphics hardware *and* driver used : meaningless
 * 64 bit
 
 ```

**Issue**
Program to making screenshots is missing in the menu after type name.
"Take Screenshots" in polish is "Pobieranie zrzutu ekranu"

![zrzut ekranu z 2018-11-16 22-47-23](https://user-images.githubusercontent.com/20991683/48649335-9c64a880-e9f2-11e8-8a9c-9a66c974bade.png)

**Steps to reproduce**
Install Linux Mint 19 MATE (language polish)
Install mint-meta-cinnamon
Change graphic environment to Cinamon
Type in search menu name of a program ("Take Screenshots")

**Expected behaviour**
A program is not showing in the menu.

You can also change graphic environment to Mate, find an icon of this program and move into some folder then change to Cinamon and drop this icon from folder to desktop. It will begin invisibly.

**Other information**

**Comment by icarter09** [comment]
@Zielony20 "Take Screenshots" looks to be renamed to "Screenshot". Is "Screenshot" the program that was missing?
