### ISSUE TITLE
[Feature Request] Services Manager GUI like SystemdGenie would be nice.

### ISSUE THREAD

**Issue by setsunati** [linuxmint/cinnamon#8039]
https://github.com/KDE/systemdgenie
https://i.imgur.com/HFUC7JN.png

Would like Cinnamon team develop their own GUI like this so we don't have to mess around with terminal to configure services and other stuff if we happen to need to configure services and other stuff. :)

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
