### ISSUE TITLE
Custom hotkeys/global shortcuts sometimes don't work

### ISSUE THREAD

**Issue by ManuelSchneid3r** [linuxmint/Cinnamon#8054]
```
* Cinnamon 4.0.1
* arch 64 bit
 ```

**Issue**
See title

**Steps to reproduce**
Set a hotkey, e.g. Ctrl+Super+Space for play/pause mpris. Hit it.

**Expected behaviour**
When hitting the combi music should play/pause.

**Other information**
I assume MPRIS/dbus not to be the problem since using the sound applet works fine.

**Comment by leigh123linux** [comment]
mpris is handled by https://github.com/linuxmint/cinnamon-settings-daemon/issues

**Comment by leigh123linux** [comment]
No, open another issue.
Next time don't mention media keys or mpris if you want it to remain open!
