### ISSUE TITLE
Why is 'date and time' part of language, and not region?

### ISSUE THREAD

**Issue by stolsvik** [linuxmint/Cinnamon#8069]
```
 * Cinnamon version: Cinnamon 3.8.9
 * Distribution: Linux Minut 18.3 Sylvia
 ```

**Issue**
I am Norwegian. I want the English language (US), but I want numbers, currency, measurements AND date&time to be displayed in Norwegian (_formatted_ in Norwegian styles). This is all-ok, except for date&time, since that is attached to the Language setting, not Region. So now I have weeks beginning on Sunday, dates formatted like crazy and general annoyance.

I fail to see that this is logical - why is not date and time a part of Region, when Numbers, Currency, Measurements are?

**Steps to reproduce**
Go into Setting, look at the "Language" section. Observe that Language encompasses Language, interface AND date and time. Observe that Region encompasses everything that is regional, except for the obvious "date and time".

**Expected behaviour**
Date and time should be a part of Region (along with numbers, currency, measurements).

**Comment by JosephMcc** [comment]
The Language settings are actually supplied by Cinnamon. They are provided by a Mint specific tool. This issue really belongs here: https://github.com/linuxmint/mintlocale
