### ISSUE TITLE
Request to make each workspace customizable

### ISSUE THREAD

**Issue by BugQContri** [linuxmint/cinnamon#8072]
```
 * * Distribution - (Mint 19.0)
  * 64 bit
  ```
**Issue**
I used until now LM KDE because the activities there suite very much my working style of having one activity for each project I am working on. Each activity has project specific transparent desktop folders with all the important links, files and folders. Additionally sometimes one or the other widget is added to an activity as it is needed. Each activity has a different background. Thus all activities are easy to be recognized and customized to my needs.

Now I am testing LM 19.0 Cinnamon and had to learn that it is not possible to have different backgrounds and have different folder (desklets) on each workspace. I was VERY much surprised because the great concept of having multiple workspaces for multiple different task requires as a  must such a customization possibility.

**Expected behaviour**
Enable each workspace to be customized with different background and different set of desklets to adjust to different work.

**Other information**
If needed I can be reached for discussion. First by email next by Skype

**Comment by BugQContri** [comment]
In the LM Forum the thread "Cinnamon Workspaces - What are they good for?" [https://forums.linuxmint.com/viewtopic.php?f=208&t=284986&view=unread&sid=d532e9ec1bb9882557ab779baa90ac59#p1575375](url)
there are screen shots to be seen which shows how different Cinnamon Backgrounds can be set for different workspaces. This is unfortunately only valid for XFCE flavor fo LM 19.0

Enabling different backgrounds and different set-up with desklets would boost the LM Cinnamon flavor really forward.

**Comment by baditaflorin** [comment]
I would also find value in this

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
