### ISSUE TITLE
Gaps around panel-popup-windows when using arc-theme

### ISSUE THREAD

**Issue by astier** [linuxmint/Cinnamon#8087]
```
 * Cinnamon version 4.0.3
 * Distribution - Arch
 * Graphics hardware: Intel HD 5300, Modesetting
 * 64 bit
 ```

**Issue**
I am not sure if this is a cinnamon or arc-theme issue but when I use the arc-theme for the panel/desktop then the panel-windows which pop up (like the menu or calendar) have 
a gap between themselves and the panel (see attached image).

**Steps to reproduce**
1. Install arc-theme
> pacman -S arc-gtk-theme

or
> apt install arc-theme
2. Open in the menu the Themes-Settings
3. Choose Arc-Dark as the Desktop-Theme
4. Click on the menu- or calendar-button on the panel
5. Observe the gap between the respective window and the panel

**Expected behavior**
There should be no gap between the windows and the panel.

**Comment by leigh123linux** [comment]
File the issue against the theme.
