### ISSUE TITLE
Cinnamon menu search box behaves differently when menu is set to open with mouse-over.

### ISSUE THREAD

**Issue by Ferroin** [linuxmint/Cinnamon#8088]
```
 * Cinnamon version: 4.0.3
 * Distribution: Gentoo ~amd64
 * GPU: NVIDIA GeForce GTX 1060 using NVIDIA proprietary driver version 415.18
 * 64-bit
 ```

**Issue**

If 'Open the menu when I move my mouse over it' is enabled, then the cinnamon menu will not focus the search box when opened, and will not automatically clear any previous search query, independent of how the menu was actually opened.

**Steps to reproduce**

1. Enable 'Open the menu when I move my mouse over it.' in the menu settings.
2. Open the Cinnamon menu by any means, and observe that the search box is not auto-focused.
3. Select the search box, type something in, and close the menu.
4. Re-open the menu and observe that the search box is defocused again, but still contains the search query from step 2.

**Expected behaviour**

The search box is automatically focused when the menu is opened (or at least, when it's opened with a hotkey), and is automatically cleared when the menu closes, all independent of whether 'Open the menu when I move my mouse over it' is set or not.

**Other information**

I don't follow Cinnamon development very closely, but it looks to me like the menu got redesigned and this behavior just got changed by accident during the redesign.

Regardless, it's a significant issue for people who previously interacted with the menu primarily through the keyboard.

**Comment by brownsr** [comment]
Works fine for me, so can't reproduce.  That's on  Cinnamon 4.0.3 as well, however I have muffin built from the latest master, and I see from a recent commit that the latest version of muffin was not mandated in the build.  I suggest ensuring that you have the matching 4.0.3 version of muffin just in case that is the cause of the problem.

**Comment by leigh123linux** [comment]
Works fine here

```
$ rpm -q cinnamon muffin
cinnamon-4.0.3-1.fc29.x86_64
muffin-4.0.3-1.fc29.x86_64
```

**Comment by Ferroin** [comment]
I've got 4.0.3 for both here, though I've got varying other 4.0.x versions of some of the other components, not sure if that's significant or not (I've just got the newest versions Gentoo has ebuilds for for all of them):

```
$ eix -c -I cinnamon
[I] gnome-extra/cinnamon (4.0.3{tbz2}@2018-11-29): A fork of GNOME Shell with layout similar to GNOME 2
[I] gnome-extra/cinnamon-control-center (4.0.0{tbz2}@2018-11-29): Cinnamons's main interface to configure various aspects of the desktop
[I] gnome-extra/cinnamon-desktop (4.0.1(0/4){tbz2}@2018-11-29): A collection of libraries and utilites used by Cinnamon
[I] gnome-extra/cinnamon-menus (4.0.0{tbz2}@2018-11-29): Cinnamon's library for the Desktop Menu fd.o specification
[I] gnome-extra/cinnamon-screensaver (4.0.1{tbz2}@2018-11-29): Screensaver for Cinnamon
[I] gnome-extra/cinnamon-session (4.0.0{tbz2}@2018-11-29): Cinnamon session manager
[I] gnome-extra/cinnamon-settings-daemon (4.0.2{tbz2}@2018-11-29): Cinnamon's settings daemon
Found 7 matches
$ eix -c -I muffin
[I] x11-wm/muffin (4.0.3{tbz2}@2018-11-29): Compositing window manager forked from Mutter for use with Cinnamon
```

**Comment by Zerophase** [comment]
It happens if "Open the menu when I move my mouse over it" is enabled. The search field does not get auto focused if that option is enabled. Also does not clear the text input.

**Comment by Ferroin** [comment]
Just checked, and that appears to be the case here too, I'm only seeing it here if I've got that option enabled, regardless of whether I use the mouse to open the menu or not.

Nice catch @Zerophase, I hadn't thought to check that.

**Comment by Ferroin** [comment]
Updated title and original issue description to be more specific about the exact issue.

**Comment by NikoKrause** [comment]
That has been reported in the beta issues tracker. I've created a fix for it: https://github.com/linuxmint/Cinnamon/pull/8117/files

This hopefully gets into Cinnamon 4.0.6.

For now deleting 6 lines in `/usr/share/cinnamon/applets/menu@cinnamon.org/applet.js` as in the link above should fix this problem.
