### ISSUE TITLE
Can't "Toggle vertical maximization" with Super+Z

### ISSUE THREAD

**Issue by Ynzl** [linuxmint/Cinnamon#8093]
```
 * Cinnamon version (cinnamon --version)
Cinnamon 3.8.9
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
Ubuntu 18.04.1
 * Graphics hardware *and* driver used
Mesa DRI Intel(R) UHD Graphics 620 (Kabylake GT2)
00:02.0 VGA compatible controller: Intel Corporation UHD Graphics 620 (rev 07)
 * 32 or 64 bit
64bit
 ```

**Issue**
I want to set "Toggle vertical maximization" to Super+z but it doesn't work, both through the GUI and dconf.

Other shortcuts work. (I tried Super+U, Super+. and various others)

On the otherhand Super+z does work for other command. (I tried "Maximize Window")

**Steps to reproduce**
Set the shortcut in Keyboard->Shortcuts->Windows->"Toggle vertical maximization" to Super+Z

**Expected behaviour**
When pressing Super+Z the window should span the whole vertical space. Instead nothing happens.

**Other information**
I actually encountered this problem before when I was using Linux Mint (version 16 to 18) on another computer and couldn't fix it then either.

**Comment by claudiux** [comment]
Super + z works fine for me. Please, check if this shortcut is not already used (possibly by an applet that you have installed).

**Comment by Ynzl** [comment]
Okay I found the problem.

The offending applet is the Icing Task Manager which has a "Global hotkey to show the order of apps" with the default Super+`
Once I unassigned this hotkey, the vertical maximization with Super+Z worked.

Thanks for the help.
