### ISSUE TITLE
Grouped Window List: indicators of pinned/open/focused windows

### ISSUE THREAD

**Issue by MasterGeekMX** [linuxmint/Cinnamon#8102]
```
 * Cinnamon version: Cinnamon 4.0.2
 * Distribution - Fedora 29
 * Graphics: Intel Corporation 2nd Generation Core Processor Family Integrated Graphics Controller (rev 09)
 * 64 bit
 * [xsession-errors.gz](https://github.com/linuxmint/Cinnamon/files/2645036/xsession-errors.gz)
 ```

**Issue**

There is no indicator to distinguish if an icon represents a pinned app, an open window, or a focused window

![imagen](https://user-images.githubusercontent.com/10291989/49460550-2cf30500-f7b7-11e8-9a61-fbcde193b4ea.png)
*in order: pinned, background, focused*

**Expected behaviour**

Some sort of hinting should indicate if a windo is focused, minimized/out of focus, or unopened but pinned.

Icing Task manager shown as an example:

![imagen](https://user-images.githubusercontent.com/10291989/49460459-f917df80-f7b6-11e8-90e2-08544d4fbd94.png)
*in order: pinned, background, focused*

**Comment by brownsr** [comment]
It's a theme issue, for instance here is a change I made to two themes recently for exactly this reason.  https://github.com/linuxmint/cinnamon-spices-themes/commit/20149c0451cdf3e7c950db50f9f004ec8a0570da    
Many themes will not have been updated for Cinnamon 4.0 grouped window list yet.  If this is a theme that is either a core mint theme or in the spices repository please let me know.

Regards

Simon

**Comment by MasterGeekMX** [comment]
@jaszhix @brownsr I use the theme Adapta Nokto Eta, found in the Cinnamon spcies but pre-loaded with Fedora Cinnamon Spin.

A refresh of the theme cache and update fixed it.
