### ISSUE TITLE
[Feature request] An option to disable the 19.1 "compact taskbar" only for the selected applications

### ISSUE THREAD

**Issue by fermmm** [linuxmint/cinnamon#8104]
Add an option when left clicking on an opened application in the window list:  "disable compact view for this application", that option should bring back the classic window list for that application only (with the title of the window and grouping disabled).

**Why?**

The extra interaction cost of hovering the mouse, waiting and clicking the sub-instance is annoying for some applications like nemo where we do this very often because we work with multiple folders at the same time, this is also something I never liked about MS Windows.
Also the "middle click to close" feature that I love from Mint is not as comfortable as before with the compact view, this is another disadvantage of it.
The compact view is good for most applications when multiple instances are not needed. The idea is to have the best of both worlds instead of being forced to choose between one or the other.

**Edit:**
Example image I did with gimp to show what I mean (it looks ugly because I did it fast):
![49532795-17a3d680-f89c-11e8-9367-c055eaaa3818](https://user-images.githubusercontent.com/3660373/49602031-3bcbea00-f966-11e8-9c60-3e478060d88a.png)

**Comment by NikoKrause** [comment]
Have you tried the grouped window list? I'm not sure, what you asking for, but this applet is very customizable. E.g. you can choose to not group the apps:
![screenshot-cinnamon-2018-12-05-133057](https://user-images.githubusercontent.com/8415124/49513882-a875b480-f892-11e8-8a4e-774f5f670b99.png)

And there's a plenty more options, which you can customize to your liking.

**Comment by fermmm** [comment]
> Have you tried the grouped window list? I'm not sure, what you asking for, but this applet is very customizable. E.g. you can choose to not group the apps:
> ![screenshot-cinnamon-2018-12-05-133057](https://user-images.githubusercontent.com/8415124/49513882-a875b480-f892-11e8-8a4e-774f5f670b99.png)
> 
> And there's a plenty more options, which you can customize to your liking.

My english is not so good sorry.
What I suggest is like that applet, but I need the title of the window in the taskbar (like in the old taskbar), otherwise I see 2 icons of nemo and I don't know which folder it belongs to. But for the other applications I don't need the window title in the taskbar because I only open a single instance.
I hope you understand what I mean.

**Comment by fermmm** [comment]
I've made this to show you exactly what I mean, it looks ugly because I did it fast but this is the idea: 
![feature](https://user-images.githubusercontent.com/3660373/49532795-17a3d680-f89c-11e8-9367-c055eaaa3818.png)

**Comment by Isakku** [comment]
This should be an optional option in the config, not by default. Quite unusual.

**Comment by fermmm** [comment]
> This should be an optional option in the config, not by default. Quite unusual.

By default it should be disabled for all apps, (compact for all apps).

**Comment by petermoo** [comment]
One of the reasons I removed windows, and one of the reasons my friends are impressed by Linux Mint Cinnamon is the title next to the icon for any application with more than one instance. Nemo and Web browser are the most common. I would be happy to disable the icon only view for any one of the following. If not, I guess I will stay with LM 19 until 19 expires.
* Everything
* Any application with more than one instance
* Selected applications

**Comment by collinss** [comment]
The old window list is still available in the latest version, and in Mint 19.1, you can even switch back to it right from the welcome screen.

**Comment by smurphos** [comment]
And the grouped window list applet has albeit disabled by default various options for labels.

**Comment by clefebvre** [comment]
If I'm interpreting this correctly, what's being asked here is a grouping-blacklist, i.e. a list of apps which don't group in GWL. Right-click a group -> Ungroup. Right-click an ungrouped "group" -> "group"... and the option to show labels for ungrouped apps.

**Comment by clefebvre** [comment]
It's a good idea for 19.2.

**Comment by fermmm** [comment]
> If I'm interpreting this correctly, what's being asked here is a grouping-blacklist, i.e. a list of apps which don't group in GWL. Right-click a group -> Ungroup. Right-click an ungrouped "group" -> "group"... and the option to show labels for ungrouped apps.

Exactly, and the option to show labels for ungrouped apps should not affect apps that are opened in a single instance.

It is difficult for me to think of a good label for the toggle option, "group" and "ungroup" I think it does not make a reference to the fact that the effect is permanent.
I'm not an expert in writing but I think something like "group application" and "ungroup application" could be better because when the word "application" is used it says that it affects the application and so it may be better understood that the action continues the next time that application is opened.

**Comment by fermmm** [comment]
> This should be an optional option in the config, not by default. Quite unusual.

Maybe if is activated for nemo by default could be a good idea, as long as people does not get confused and feel good about it, you need very specific QA tests to figure that out.

**Comment by fermmm** [comment]
> > If I'm interpreting this correctly, what's being asked here is a grouping-blacklist, i.e. a list of apps which don't group in GWL. Right-click a group -> Ungroup. Right-click an ungrouped "group" -> "group"... and the option to show labels for ungrouped apps.
> 
> Exactly, but showing the "ungrouped" app's multiple instances as equal icons with nothing that differentiates them, without a label, does not makes much sense to me. That is why I think of both things as a single toggle option.
> 
> It is difficult for me to think of a good label for the toggle option, "group" and "ungroup" I think it does not make a reference to the fact that the effect is permanent.
> I'm not an expert in writing but I think something like "group application" and "ungroup application" could be better because when the word "application" is used it says that it affects the application and so it may be better understood that the action continues the next time that application is opened.
> 
> Also an option to disable/enable grouping for all applications could be nice because that almost brings back the old taskbar without an ugly "use the old taskbar" option.

**Comment by petermoo** [comment]
Nemo by default sounds good as the title is the location and is the unique identifier, not the icon.

**Comment by fermmm** [comment]
> It's a good idea for 19.2.

@clefebvre Please don't forget to consider this idea for 19.2

**Comment by foxsam21** [comment]
Looks like it wasn't included. Maybe just adding a small number (like it does already to count the windows grouped together) to the icon to differentiate without spelling out the window name would help keep it streamlined and still have seperate icons.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
