### ISSUE TITLE
Titlebar close button sometimes doesn't change colour to match Mint-Y theme in Mint 19.1 Beta (Cinnamon 4)

### ISSUE THREAD

**Issue by PlanetLinux98** [linuxmint/cinnamon#8110]
```
 * Cinnamon version 4.0
 * Mint 19.1 Beta
 * Intel Inegrated HD 620 Graphics
 * 64-bit
 ```
**Issue**
When changing the control theme and icon theme to the various Mint-Y colours in Mint 19.1 beta, the close button in the titlebar (which is supposed to match the theme highlight colour) does not change most of the time, usually staying the default green.

**Steps to reproduce**
Open Settings > Themes and make sure the Mint-Y or Mint-Y Dark Window Title theme is selected then choose a different-coloured Mint-Y theme for the main window content.

**Expected behaviour**
More often than not, the close button in the titlebar retains its green colour instead of changing to match the rest of the theme.

**Other information**
(None)

**Comment by NikoKrause** [comment]
Try to change Mint-Y-color-Dark -> Mint-Y-color -> Mint-Y-color-Dark -> Mint-Y-color  -> Mint-Y-color-Dark -> Mint-Y-color ->  ...

**Comment by PlanetLinux98** [comment]
It seems to eventually work after ranging the theme around a bit and then back.

**Comment by ckristi** [comment]
You could probably work around the issue by doing a cinnamon restart (alt+f2->type 'r' and press enter) after changing the theme.

**Comment by smurphos** [comment]
Another workaround is to briefly switch to another window controls theme and back again after selecting the controls theme.

**Comment by PlanetLinux98** [comment]
Thanks for all the suggestions;  they seem to work. I'm just hoping they'll get it fixed up by official release.

**Comment by NikoKrause** [comment]
Better report it here: https://github.com/linuxmint/mint-19.1-beta

**Comment by PlanetLinux98** [comment]
Thanks

**Comment by JosephMcc** [comment]
Closing this since it's an old issue and have it seen it in newer versions.
