### ISSUE TITLE
Mouse gets stuck between panels

### ISSUE THREAD

**Issue by Leon422** [linuxmint/Cinnamon#8114]
```
 * Cinnamon version (cinnamon --version): 3.8.9
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 19
 * Graphics hardware *and* driver used: Intel HD 5550, default driver
 * 32 or 64 bit: 64 bit
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog: 
[syslog.tar.gz](https://github.com/linuxmint/Cinnamon/files/2654990/syslog.tar.gz)


 ```

**Issue**
I have two panels, one in the bottom of the screen and the other one on the left side of the screen. If I try to move the mouse between the two panels (aka in the corner) I can't, it gets stuck. I have to first move the mouse from the panel to outside the panel, and then I can move the mouse to the other panel.

**Steps to reproduce**

Try to move the mouse between two panels that are directly touching each other.

**Expected behaviour**

The mouse shouldn't get stuck.

**Other information**

N/A

**Comment by NikoKrause** [comment]
Can you try to enable the option `Allow the pointer to pass through the edges of panels` at the very bottom of panel settings.

**Comment by Leon422** [comment]
> Can you try to enable the option `Allow the pointer to pass through the edges of panels` at the very bottom of panel settings.

Oh my god, how did I miss that? It works now. Thanks and sorry for wasting your time

**Comment by NikoKrause** [comment]
No problem
