### ISSUE TITLE
Dropdown panel stuck down after resume from suspend

### ISSUE THREAD

**Issue by ghost** [linuxmint/cinnamon#8122]
```
 * Cinnamon version (cinnamon --version) 3.8.9
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 19
 * Graphics hardware *and* driver used: 3.0 Mesa 18.0.5. Intel UHD Graphics 620
 * 32 or 64 bit: 64
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
 ```

**Issue**

Dropdown panel stuck down after resume from suspend. Image:

![image](https://user-images.githubusercontent.com/9998846/49704258-aac86d80-fc08-11e8-8c0c-02b0bf98fb2f.png)

**Steps to reproduce**

Unknown.

**Expected behaviour**

Dropdown panel should disappear when pointer not over it.

**Other information**

Restarting Cinnamon solved the problem.

xsession-errors: attached. (You might want to advise people that this file is hard to attach - on pain of people not doing it.)
[xsession-errors.txt](https://github.com/linuxmint/Cinnamon/files/2661125/xsession-errors.txt)

**Comment by icarter09** [comment]
Closing this issue since the original submitter of this ticket is no longer present on Github.
