### ISSUE TITLE
Touch pad not working

### ISSUE THREAD

**Issue by Sam1766** [linuxmint/cinnamon#8128]
A few weeks ago after loading an update, my touch pad stopped working.  The touchpad worked correctly until this update.  Sorry, I didn't record any details on the update.  I loaded Touch Pad Indicator, which recognises the touch pad, but doesn't fix the issue.  After looking through all the blogs, I was unable to find any solutions.  I believe the Synaptics driver is the correct driver.  Please see details below: 

sam@sam-ThinkPad ~ $ cinnamon --version
Cinnamon 3.6.7

sam@sam-ThinkPad ~ $ inxi
CPU~Quad core Intel Celeron N2920 (-MCP-) speed/max~627/1999 MHz Kernel~4.15.0-42-generic x86_64 Up~9 min Mem~874.0/3692.1MB HDD~500.1GB(5.1% used) Procs~205 Client~Shell inxi~2.2.35  
sam@sam-ThinkPad ~ $ xinput
⎡ Virtual core pointer                    	id=2	[master pointer  (3)]
⎜   ↳ Virtual core XTEST pointer              	id=4	[slave  pointer  (2)]
⎜   ↳ Logitech USB-PS/2 Optical Mouse         	id=10	[slave  pointer  (2)]
⎜   ↳ Synaptics s3203_ver5                    	id=14	[slave  pointer  (2)]
⎣ Virtual core keyboard                   	id=3	[master keyboard (2)]
    ↳ Virtual core XTEST keyboard             	id=5	[slave  keyboard (3)]
    ↳ Power Button                            	id=6	[slave  keyboard (3)]
    ↳ Video Bus                               	id=7	[slave  keyboard (3)]
    ↳ Power Button                            	id=8	[slave  keyboard (3)]
    ↳ Sleep Button                            	id=9	[slave  keyboard (3)]
    ↳ Integrated Camera: Integrated C         	id=11	[slave  keyboard (3)]
    ↳ AT Translated Set 2 keyboard            	id=12	[slave  keyboard (3)]
    ↳ ThinkPad Extra Buttons                  	id=13	[slave  keyboard (3)]
sam@sam-ThinkPad ~

**Comment by icarter09** [comment]
@Sam1766 was the update related to upgrading Cinnamon or Linux Mint?

**Comment by Sam1766** [comment]
Hi Isaac,

 

Thanks for getting back to me.  I am using Linux Mint.

 

Sam

**Comment by icarter09** [comment]
@Sam1766 what version of Linux Mint are you on? The most current version of Cinnamon is 4.0.8 and Linux Mint is 19.1.

**Comment by icarter09** [comment]
@Sam1766 I did some googling on Win10 Ed machines BIOS, and it appears you can get to the BIOS, but it requires you to go through some 'Control Panel' options first. That might explain why you weren't able to get to the BIOS through any key stroke combinations.

**Comment by Sam1766** [comment]
Hi Issac,

 

Thanks for the note.  The “Control Panel”  (Settings) option is available on my other Win 10 Home machines.  The Win 10 Education Version is missing this boot from USB Drive via The Recovery option.  That’s the root of the problem.  Is it possible to use the GRUB Loader to boot from the USB Drive?

 

 

Best,

Sam

**Comment by icarter09** [comment]
@Sam1766 https://blog.viktorpetersson.com/2014/07/29/how-to-boot-from-usb-with-grub2.html
Hopefully that link can guide you on how to boot GRUB from USB.

**Comment by Sam1766** [comment]
Isaac,

 

Thanks for the link.  I give it a try.

 

 

Sam
