### ISSUE TITLE
Wrong hard-coded skype systray icon dimensions

### ISSUE THREAD

**Issue by rascasoft** [linuxmint/cinnamon#8129]
```
 * Cinnamon 3.8.9
 * Linux Mint 19 Tara
 * Intel Corporation 4th Gen Core Processor Integrated Graphics Controller, Driver i915
 * 64 bit
 ```

**Issue**

Skype systray icon, created by the skypeforlinux process, is displayed wrongly (a small truncated square) in Cinnamon.

**Steps to reproduce**

Just launch skypeforlinux.

**Expected behavior**

The icon should be in the correct dimensions.

**Other information**

Looking at /usr/share/cinnamon/applets/systray\@cinnamon.org/applet.js, line 344 we have:
```
        if (["skypeforlinux"].indexOf(role) != -1) {
            icon.set_size(16, 16);
            global.log("Resize " + role + " with hardcoded size (" + icon.get_width() + "x" + icon.get_height() + "px)");
```
Now, apart fromthe unusual "if" based upon the specific application, we have hard-coded values and in my case these should be instead "32, 32".
I'm using a 4k display and a scaling factor on 1, but I don't think this has a lot to deal with the problem.
There should be a dynamic way to set the icon dimensions.

**Comment by icarter09** [comment]
@rascasoft  are you still experiencing this issue?

**Comment by rascasoft** [comment]
@icarter09 no, not experiencing this anymore.

**Comment by icarter09** [comment]
@rascasoft thanks for the update.

**Comment by rascasoft** [comment]
Thanks to you for the interest shown.

**Comment by icarter09** [comment]
@rascasoft can you provide a screen capture of what you are seeing? Thanks.
