### ISSUE TITLE
Panels: Panel configuration window remains on old panel when one adds a new panel

### ISSUE THREAD

**Issue by ghost** [linuxmint/cinnamon#8136]
```
 * Cinnamon version (cinnamon --version) 3.8.9
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 19.0 - and Mint 19.1 beta.

 ```

**Issue**

The panel configuration window remains on the old panel when one adds a new panel.

**Steps to reproduce**

1. Have one panel.
2. Add a new panel.
3. Adjust some setting for the panel and discover one is altering the _old_ panel.

**Expected behaviour**

It would be more intuitive in this circumstance for the window's settings to switch to the _new_ panel.

**Other information**

If one's panels are hidden, it is hard to see which one is selected (selected within the panel edit window).

**Comment by icarter09** [comment]
Closing this issue since the original submitter of this ticket is no longer present on Github.
