### ISSUE TITLE
if fall thorugh in /usr/bin/cinnamon-settings

### ISSUE THREAD

**Issue by wickedmic** [linuxmint/Cinnamon#8140]
I  was looking at the python code in [files/usr/bin/cinnamon-settings](https://github.com/linuxmint/Cinnamon/blob/3478db2822d2f4c839c7d0ef7b517f0aa1d50bae/files/usr/bin/cinnamon-settings) and in line 7 it looks like there starts a block of if-elif-else. But in line 9 there is an if instead of an elif statement.

I tracked this back to commit [3478db2822d2f4c839c7d0ef7b517f0aa1d50bae](https://github.com/linuxmint/Cinnamon/commit/3478db2822d2f4c839c7d0ef7b517f0aa1d50bae#diff-b01896b6df354b6e872891030f800f52L7) where the diff also suggests that the if in line 7 should be a elif.

In the current master, which is f84d52b, the code is still unchanged.

This might be no issue or even intentional. I just started to look into the code, so I don't know. But if it is intentional, I would try to make that more clear by separating the if blocks by a blank line or at least put a comment there.

**Comment by clefebvre** [comment]
It doesn't cause any issue but I don't think it's intentional. Do you want to open a pull request to fix it? Let me know otherwise if you want me/us to commit that change.

**Comment by wickedmic** [comment]
I have no pull request prepared. I just stumbled over this, while trying to figure out why "Region & Language"-Panel is missing in my Debian installation.

I'm totally fine if you fix this. Just wanted to be nice and point it out, since these kind of bugs are sometimes hard to find.

**Comment by clefebvre** [comment]
Cinnamon doesn't provide a locale config tool. In Mint it's mintlocale which is responsible for doing that, for all DEs (Cinnamon, MATE and Xfce).
