### ISSUE TITLE
"Disable compositing for full-screen windows" not working on wine fullscreen games

### ISSUE THREAD

**Issue by str225** [linuxmint/Cinnamon#8153]
```
 * Cinnamon version: Cinnamon 4.0.5
 * Distribution: Manjaro
 * Graphics hardware *and* driver used: i915 intel graphics hd 620
 * 64 bit
```
[.xsession-errors.txt](https://github.com/linuxmint/Cinnamon/files/2687634/xsession-errors.txt)

**Issue**
With "Disable compositing for full-screen windows" option enabled: The option is working fine on native linux games, but the compositor is not being disabled on fullscreen wine games unless i enable a virtual desktop on wine. I could guess that the compositor was not disabled because the gameplay was really choppy on osu!, and i didn't have this issue on other DEs that have a similar option like gnome and budgie.

**Comment by jaszhix** [comment]
Hi, this is an issue I have reproduced myself as well. It doesn't belong here though, its a Muffin issue.

One possible work around is disabling the vblank option while playing the game.

**Comment by jaszhix** [comment]
Kamino closed and cloned this issue to [linuxmint/muffin](https://github.com/linuxmint/muffin/issues/400)
