### ISSUE TITLE
Remember Window Last Position

### ISSUE THREAD

**Issue by Alkaris** [linuxmint/Cinnamon#8154]
```
 * Cinnamon 3.8.9
 * Distribution - Linux Mint 19
 * ASUS NVIDIA GTX 1070 - Nvidia proprietary 410.78
 * 64bit
 ```

This is a feature that has been missing from Linux Mint, is having windows remembering the last position they were at before being closed and keeping them there between reboots. This should be added to the Windows Behaviour in System Preferences. I shouldn't have to rely on installing a third-party software like gDevilSpie just to remember window positions between reboots. It's rather annoying after a while having to keep reorganising window positions between each system reboot. There is the `Location of newly opened windows` in Windows Behaviour, but this doesn't work, this doesn't save or remember the last position of a window when it was last opened. It needs to be a separate thing from this. Some applications have it built-in to remember where they were positioned on the screen last, but this doesn't apply to every window application ever, compared to some other desktop managers they have it built-in, or use Compiz, but with Linux Mint at least on Cinnamon doesn't use Compiz.

**Comment by leigh123linux** [comment]
The apps should do this not cinnamon.
