### ISSUE TITLE
Clock doesn't scale correctly to fit panel

### ISSUE THREAD

**Issue by Soapux** [linuxmint/cinnamon#8157]
```
 * Cinnamon 4.0.8
 * LinuxFromScratch
 * Nvidia Geforce 650 Ti with Nvidia 410.73
 * 64 bit
 ```

After upgrade to Cinnamon 4.0.8 from 3.8.8, the clock in my vertical panel is very small size.  It looks about 22px size.  My other icons by the clock were also the same small size.  So I went to panel settings, then changed the "Bottom panel zone icon size" to "Scale to panel size optimally".  This fixed the volume, network, and user icon, but not the clock size.

**Comment by invexx** [comment]
Go to Panel Settings and change Top, Center and Bottom panel zone icon size.

**Comment by Waterwalker7** [comment]
Hi there Thanks for your reply. Perhaps i didn't explain what I was after
correctly. It's not the icon size but the text fonts i.e. in the
screenshot, the 57% and 8.52(time) fonts on my panel that I would like to
increase please? I read somewhere online that this can be done through the
cinnamon.css file but this is a read only file so I cannot save any changes
to it.

Many thanks again

John

**Comment by invexx** [comment]
I edited cinnamon.css some time ago. You have to open it as an administrator. Just right click on the directory where cinnamon.css is located and select Open as Root and then open cinnamon.css.

**Comment by Waterwalker7** [comment]
Many thanks I'll give it a go then :)

**Comment by icarter09** [comment]
@Waterwalker7 were you able to resolve the issue?

**Comment by smurphos** [comment]
https://forums.linuxmint.com/viewtopic.php?p=1573846#p1573846

**Comment by JosephMcc** [comment]
This is the same as: https://github.com/linuxmint/cinnamon/issues/8260

**Comment by Waterwalker7** [comment]
Many thanks Joseph, It worked for me
