### ISSUE TITLE
User level option to disable window edge-tiling (aka aero snap)

### ISSUE THREAD

**Issue by ghost** [linuxmint/Cinnamon#816]
A cinnamon settings level option to disable this feature would be useful, as some users find it annoying.  It's currently only possible to disable (afaik) via gconf-editor.

**Comment by tripleee** [comment]
In my limited experience (Debian Jessie Cinnamon Live CD) the shift key does not seem to disable edge tiling.  Also, I was unable to find a configuration option to change this -- [Launchpad bug #1082696](https://bugs.launchpad.net/linuxmint/+bug/1082696) alleges that there should be a key `org.cinnamon.overrides` in `gsettings` but it doesn't seem to exist here (any longer?)

**Comment by Tectract** [comment]
How do I disable ALL WINDOW SNAPPING OF ANY KIND!? Why is this so hard? I don't want windows to snap to any edge. Ever.

**Comment by mtwebster** [comment]
It's a matter of providing the best experience and not inundating users with a million options they don't need.  You can already easily disable window 'tiling' (aero-style), I'm fairly sure in 3.0 you'll be able to disable the edge-resistance type snapping as well (where window edges try to align themselves with other window edges during dragging).

**Comment by Tectract** [comment]
"Maximize if screen edge hit" was causing snapping. When I try to move a window, guess what I want it to do?

**Comment by mtwebster** [comment]
This is the control you want maybe?
![image](https://cloud.githubusercontent.com/assets/262776/14121389/4430c6c2-f5c5-11e5-9d06-63dd9bb47cab.png)
