### ISSUE TITLE
[Feature request] Set critical battery level percentage and more actions on that state

### ISSUE THREAD

**Issue by ninosanta** [linuxmint/cinnamon#8164]
```
 * Cinnamon version:  4.0.8
 * Distribution: Linux Mint 19.1 64 bit
 ```

**Issue**
It is not possible to set a different percentage and a different action when the laptop is running on critical battery level? Even for the low battery level because changing the critical setting may influence low level if these two levels are too close

**Steps to reproduce**
Mint Menu -> Preferences -> Power Management -> Power Tab -> Extra Options ->  When the battery is critically low -> [Do nothing, Shutdown Immediately] 

**Expected behaviour**
Availability of more options, such as a **Suspend** option because the Immediate shutdown in some case could be a very aggressive solution. Furthermore the critical level percentage is important, for example some older batteries have a very fast discharge rate with steps of 20% and could pass from 20 to 0% immediately

**Other information**
For instance, I'd like to set the critical level to 15%, low to 25% and suspension as critical action

**Comment by icarter09** [comment]
@ninosanta I think this is a good idea and noticed this myself before coming across this ticket. Can you provide me a list of what options you think would be beneficial to the user? Thanks.

**Comment by ninosanta** [comment]
@icarter09,
this is what KDE provides:
![screenshot](https://user-images.githubusercontent.com/38584348/50396666-aa34e880-076b-11e9-938a-c287db6e1aff.png)
and I think is more than sufficient and not very far from what Cinnamon Power Management provides right now...another possibility is to take inspiration from XFCE's power management which is a bit more elaborate.
I think users will appreciate either some sorta of persistent notifications on low and critical level

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
