### ISSUE TITLE
Menu applet on bottom panel extends off top of screen: Mint 19.1

### ISSUE THREAD

**Issue by CottonEaster** [linuxmint/Cinnamon#8168]
```
 * Cinnamon version (cinnamon --version) 4.0.8
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 19.1
 * Graphics hardware *and* driver used: 3.0 Mesa 18.0.5; Intel UHD Kabylake 620
 * 32 or 64 bit: 64
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog: attached the former, but I had to change the file name
[xsession.txt](https://github.com/linuxmint/Cinnamon/files/2699444/xsession.txt)

 ```

**Issue**

![image](https://user-images.githubusercontent.com/9998846/50294165-3940b880-046d-11e9-9219-866387a36625.png)

**Steps to reproduce**

Install the menu on the bottom panel (top-panel seems unaffected). One may need to have a lot of software installed. One may need a high-resolution screen and to have on Mint HiDPI enabled.

**Expected behaviour**

Menu items should not be truncated and I should be able to see the menu search box.

**Other information**

My system is hi-DPI with a resolution of 2560x1440.

Cf. here: https://github.com/linuxmint/mintmenu/issues/202

**Comment by leigh123linux** [comment]
I don't consider 2560x1440 hidpi, once scaled it equals a pathetic 1280x720.
This isn't enough for all the extra menu categories you have added.

**Comment by CottonEaster** [comment]
I have seventeen categories, compared to nine (or eight, depending on how one counts) in a fresh 19.1 install. I am not aware of having added many extra menu categories; so, I think that installing applications may have added them automatically.

So, is your view the following? It is alright for the menu's search box to be off-screen, and items to be truncated, so long as the cause is either (a) the users having installed many applications or (b) the user adding categories? I find that view questionable, especially in form _a_.

**Comment by CottonEaster** [comment]
Here is a fix for any one else who has the problem: in the options for the Menu, disable 'show category icons'. Looks like a bug to me.

**Comment by CottonEaster** [comment]
And I still see the following, i.e. almost nothing, when I right-click an application in the menu (which I thought I had reported previously, but ten minutes of searching failed to disclose an existing report):

![image](https://user-images.githubusercontent.com/9998846/50302816-2638e300-0483-11e9-9458-4b5810cee136.png)

(I would scale the image down, were it to come from a Hi-DPI system . .)

And, to repeat, all that I have done, to my knowledge, is install some applications.
