### ISSUE TITLE
'Pin to panel' not always displayed

### ISSUE THREAD

**Issue by CottonEaster** [linuxmint/Cinnamon#8169]
```
 * Cinnamon version (cinnamon --version) 4.0.8
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 19.1
 * Graphics hardware *and* driver used: 3.0 Mesa 18.0.5; Intel UHD Kabylake 620
 * 32 or 64 bit: 64
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog: attached the former, but I had to change the file name
[xsession.txt](https://github.com/linuxmint/Cinnamon/files/2699444/xsession.txt)

 ```

**Issue**

When I run the default System Monitor, or KsysLog, and right click the respective icon in my bottom panel, sometimes - not always - no 'pin to panel' option is displayed. Screenshot:

![image](https://user-images.githubusercontent.com/9998846/50294487-e1ef1800-046d-11e9-9482-3b77ddaaa3eb.png)

**Steps to reproduce**

Uncertain. Try running the above apps a few times and looking at the relevant right-click menu. Also, one may need hiDPI.

**Expected behaviour**

Pinning to panel should be available/visible always (so long as one has not already pinned the item).

**Other information**

Sometimes, and for the apps in question, the pin option *is* displayed.

**Comment by jaszhix** [comment]
If they don't have a .desktop file associated with them - usually found in ~/.local/share/applications or /usr/share/applications, then they cannot be pinned. We call these "window-backed" apps - windows that have no application association - usually portable apps. 

For those windows the "Create shortcut" option appears, which generates a .desktop file, places it in ~/.local/share/applications, and names it based on the process name. You can then find it by going to that directory or searching for it in the menu. From there, the resulting file can have its name and icon customized manually, or be deleted.

There is currently some issues with Flatpak/Snap apps that don't get an association when their deb version is present on the system. This is being tracked in #7974.

**Comment by CottonEaster** [comment]
@jaszhix

&nbsp;&nbsp;&nbsp;&nbsp;Thanks. So, Cinnamon is unable to pin some apps, but, for those apps, it does offer a 'create shortcut' option? OK. Does that aforementioned option allow pinning _after_ the intervening step? _Please explain._ Please include in your explanation an account of _why such fairly standard apps as the ones that I mentioned - and which I did not install via either Flatpak or Snap - are affected._

&nbsp;&nbsp;&nbsp;&nbsp;If I fail to understand, then somehow I failed to grasp your explanation. (Sorry if I am overly defensive. I am after a decent user experience and there is a limit to my technical knowledge.)
