### ISSUE TITLE
Pinned apps on panel jitter when one moves them: Mint 19.1

### ISSUE THREAD

**Issue by ghost** [linuxmint/cinnamon#8171]
```
 * Cinnamon version (cinnamon --version) 4.0.8
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 19.1
 * Graphics hardware *and* driver used: 3.0 Mesa 18.0.5; Intel UHD Kabylake 620
 * 32 or 64 bit: 64
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog: attached the former, but I had to change the file name
[xsession.txt](https://github.com/linuxmint/Cinnamon/files/2699549/xsession.txt)

 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
 ```

**Issue**

Please see video here [link removed, because accidentally I overwrote the video with another one, and my cloud provider throws an error when I try to retrieve the old version]

(Only the first minute or so, during which I dragged an applet first with the mouse then with the touchpad, is relevant. The video continues because I could not stop recording and then Cinnamon crashed.)

**Steps to reproduce**

Seemingly: pin apps; drag one of them.

**Expected behaviour**

No jitter. It's offputting.

**Comment by jaszhix** [comment]
Thanks. What is the size of your panel set to? And the icon size of the panel zone GWL is located in?

**Comment by CottonEaster** [comment]
Panel height: 38.
Icon size (of all panel zones): 'scale to panel size optimally'.

**Comment by icarter09** [comment]
Closing this issue since the original submitter of this ticket is no longer present on Github.
