### ISSUE TITLE
Panel Settings window: scrolling with mouse wheel often affects the icon size slider

### ISSUE THREAD

**Issue by ghost** [linuxmint/cinnamon#8172]
```
 * Cinnamon version (cinnamon --version) 4.0.8
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 19.1
 * Graphics hardware *and* driver used: 3.0 Mesa 18.0.5; Intel UHD Kabylake 620
 * 32 or 64 bit: 64

**Issue**

In the Panel Settings window, scrolling withthe  mouse wheel often affects the icon size slider, i.e. changes one's settings. Video [here](https://app.box.com/s/gh597maiotiek9zj6dne7vmgd8j3wez1).

**Steps to reproduce**

1) Open Panel Settings window. (I mean the window one reaches via Settings -> Panel.)
2) Scroll up and down it, a bit, with the mouse wheel.
3) Observe how likely as not a slider gets moved.


**Expected behaviour**

Scrolling through a window should not change settings.

**Other information**

Mint 19.0 had this problem.

Other Mint windows - ones with sliders - may have the same problem.

This problem is an inconvenience to the user.

**Comment by smurphos** [comment]
This a feature not an inconvenience. The scroll wheel will move the slider only when the mouse is hovering over the slider. The slider will be highlighted to give a visual clue when this action is possible.

**Comment by smurphos** [comment]
No the highlighting is there currently - but it is too subtle on current Mint-Y. It is more apparent on Mint-Y-Dark. It is also dependent on theme support. Adapta's GTK theme for example doesn't highlight that widget on hover at all. I'll fix that.

**Comment by icarter09** [comment]
@smurphos can this ticket be closed?

**Comment by smurphos** [comment]
@icarter09 I think so - if anything it was a theme issue and with current Mint-Themes I think the visual cue that the widget is active is adequate. I never did get round to fixing Adapta though will add that to my todo wishlist...
