### ISSUE TITLE
Inbuilt video recorder goes very wrong - on Mint 19.1

### ISSUE THREAD

**Issue by CottonEaster** [linuxmint/Cinnamon#8173]
```
 * Cinnamon version (cinnamon --version) 4.0.8
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 19.1
 * Graphics hardware *and* driver used: 3.0 Mesa 18.0.5; Intel UHD Kabylake 620
 * 32 or 64 bit: 64
 ```

**Issue**

The inbuilt video recorder will not stop, stalls computer and then crashes Cinnamon - on Mint 19.1.

**Steps to reproduce**

Start the recorder, via shift-control-alt-r.
Record.
Try to stop the recorder by using the same keyboard shortcut.

**Expected behaviour**

Stoppable recording, no stalls, no crash.

**Other information**

This is a regression, I think; it's been a while since I used the recorder in 19.0, but, when I did, it worked.

This bug makes providing bug reports harder.

**Comment by leigh123linux** [comment]
https://github.com/linuxmint/Cinnamon/issues/8156
