### ISSUE TITLE
Changing the symbolic icon size setting has no effect

### ISSUE THREAD

**Issue by ghost** [linuxmint/cinnamon#8174]
```
 * Cinnamon version (cinnamon --version) 4.0.8
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 19.1
 * Graphics hardware *and* driver used: 3.0 Mesa 18.0.5; Intel UHD Kabylake 620
 * 32 or 64 bit: 64
 ```

**Issue**

Changing the symbolic icon size setting has no effect. I'd attach a video, but so doing would crash my computer - see #8173 .

**Steps to reproduce**

Settings -> Panel Setting ->Symbolic icon size adjustments - drag slider with mouse or use the arrow keys to change the value.

**Expected behaviour**

The slider should work.

**Other information**

Restarting Cinnamon did not help.
Rebooting the computer did not help.
[xsession.txt](https://github.com/linuxmint/Cinnamon/files/2699793/xsession.txt)

**Comment by icarter09** [comment]
Closing this issue since the original submitter of this ticket is no longer present on Github.
