### ISSUE TITLE
Bug / feature request (Mint 19.1): return key does nothing when one item found in Settings

### ISSUE THREAD

**Issue by ghost** [linuxmint/cinnamon#8175]
```
 * Cinnamon version (cinnamon --version) 4.0.8
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 19.1
 * Graphics hardware *and* driver used: 3.0 Mesa 18.0.5; Intel UHD Kabylake 620
 * 32 or 64 bit: 64
 ```

**Steps to reproduce**

Open Settings.
Type something e.g. 'panel' in the box.
A single result is shown.
Press <return>.

**Expected behaviour**

The single found result of the search should act as though clicked upon. What actually happens: nothing.

**Other information**

Having things behave as I propose would be intuitive and a time-saver. Put otherwise: the current behaviour is counter-intuitive and wastes time.

**Comment by icarter09** [comment]
@CottonEaster I'm not able to duplicate this issue. Whenever I press the return key (Enter), then the given selection in the search results for Settings or whatever I search on, the item is activated. Are you still experiencing this issue?

**Comment by CottonEaster** [comment]
Yes, I still experience the issue. (Thanks for the response.)

**Comment by icarter09** [comment]
@CottonEaster no problem. Also I forgot to say that I'm also using Cinnamon 4.0.1 and Linux Mint 19.1 64bit.

**Comment by CottonEaster** [comment]
So you have Mint 19.1, as I do, but a version of Cinnamon _earlier_ than mine? (For, I see:
```
$ cinnamon --version
Cinnamon 4.0.8

$ cat /etc/*-release
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=19.1
DISTRIB_CODENAME=tessa
DISTRIB_DESCRIPTION="Linux Mint 19.1 Tessa"
[. . .]
```
)

**Comment by icarter09** [comment]
@CottonEaster that was my bad. I meant to edit that post to "4.0.8", but then the dogs started barking and I got caught up in taking care of them and completely forgot to come back and edit the post.
