### ISSUE TITLE
Bug / feature request (Mint 19.1): moving the pointer over symbolic icons yields inconsistent behaviour

### ISSUE THREAD

**Issue by ghost** [linuxmint/cinnamon#8176]
```
 * Cinnamon version (cinnamon --version) 4.0.8
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 19.1
 * Graphics hardware *and* driver used: 3.0 Mesa 18.0.5; Intel UHD Kabylake 620
 * 32 or 64 bit: 64
 ```

**Issue**

I have these symbolic icons on the right of my tray:

![screenshot from 2018-12-20 17-21-02](https://user-images.githubusercontent.com/9998846/50300260-cc80ea80-047b-11e9-83e5-32c663eae8c8.png)

If I move the pointer over those icons, moving the pointer from left to right, then the following happens. The icons become highlighted, one by one - _until_ I hit the system tray - which is not distinguished visually from the others (not in respects other than what I am pointing out). The _system tray_ icons do _not_ get highlighted, even though they are clickable. Once the pointer passes the system tray - once it it is once again over applet icons - the highlighting resumes. ~~Also: the tooltips for the system tray icons are a different colour, and have a different box size, to the applet icons.~~ **EDIT:** The tooltip inconsistency owed to a third-party theme.

**Steps to reproduce**

Please see above.

**Expected behaviour**

Consistent highlighting would be _much_ better.

**Other information**

I would attach a video, but the video recorder is broken (see #8173).

**Comment by smurphos** [comment]
Your choice of enable indicator support or not in Cinnamon General Settings will affect if the tooltip and context menus for system tray icons are themed by the Cinnamon theme or the GTK theme. 

I don't think it's technically possible to apply any hover effect to the icons themselves as they are not under the control of the Cinnamon theme, and they are not applets in themselves - the tray as a whole is the applet. A hover effect can be applied to the system tray as a whole in the theme, whether that's desirable or not is a design decision for the individual theme.

**Comment by icarter09** [comment]
@smurphos any update on this ticket?

**Comment by smurphos** [comment]
Hi, it can be closed - it was a theme issue and not a problem out of the box in 4.4
