### ISSUE TITLE
System freeze sending email with Thunderbird after upgrade to 19.1

### ISSUE THREAD

**Issue by wyse92** [linuxmint/Cinnamon#8177]
```
 * Cinnamon version 19.1
 * Distribution - Mint 19.1
 * Graphics hardware Nvidia geforce FX1080 driver Nvidia 390 Intel Core i7-7700K bits: 64 Kaby Lake  
 * 64 bit
 * [xsession-errors.txt](https://github.com/linuxmint/Cinnamon/files/2699976/xsession-errors.txt)

**Issue**
After upgrading from 19.0 cinnamon (with out problem) and installing "apt install p7zip-full va-driver-all xul-ext-lightning" cause using calendar.

The system freeze when sending an Email with (Thunderbird 60.2.1 64 bits), but no problem receiving mails. Hard reboot required (waiting is useless).

**Steps to reproduce**
Simply send an email

**Expected behaviour**
 No freeze :)


**Other information**

**Comment by jaszhix** [comment]
Sounds like a segfault. If you open `mintreport` (System Reports in the menu), do you see an entry for Cinnamon? If so select it, click "Pastebin", and please attach it here. Thanks.

**Comment by wyse92** [comment]
hi jaszhix,
thanks for your help.
This morning (for me) the problem disappeared ? Don't know why because I had been able to reproduce the problem several times after many reboot (and with many different mails).

I write down your proposal about a segfault (seems to be a good idea) and I’ll come back if the problem happens again, and I thank you.

**Comment by mattsmi** [comment]
> Sounds like a segfault. If you open `mintreport` (System Reports in the menu), do you see an entry for Cinnamon? If so select it, click "Pastebin", and please attach it here. Thanks.
System Report only has a Crash for Cinnamon dated 14 December 2018. I don't have one since the upgrade.
I too am having the system freeze solid after sending email in Thunderbird. Nothing I can do to fix it.
I go into Command Line mode and kill off things, but nothing allows me to regain control, until I kill Cinnamon, which of course kills the session.
Any ideas on how to resolve, please?
Cheers
PS Great work!

**Comment by wyse92** [comment]
Hi, sorry no thing new, the problem totally disappeared for me and don't know why.

**Comment by kryukov54** [comment]
Hi,
I have the same problem. Killing thunderbird does not help. Killing cinnamon-seession restart cinnamon without problem. No message in System Report in Dec. 6, 2019.

**Comment by wyse92** [comment]
Hi, this problem came back but only once a week now.
I have no more information about that ??
