### ISSUE TITLE
Panel options: gratuitiously confusing; a fix

### ISSUE THREAD

**Issue by ghost** [linuxmint/cinnamon#8178]
```
 * Cinnamon version (cinnamon --version): 4.0.8
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...): Mint 19.1
 * Graphics hardware *and* driver used: irrelevant
 * 32 or 64 bit: 64

**Issue**

Consider the menu generated by right-clicking a panel. That menu contains this entry: 'modify panel'. The same menu contains this entry: 'panel settings' (not to mention 'panel edit mode'). Evidently, the co-existence of these two options is confusing - at least to anyone who was not privy to the design of the interface.

**Steps to reproduce**

1. Right-click a panel.
2. Be (gratuitously) confused by the options.


**Expected behaviour**

Options should be reasonably clear so long as there is no good reason why they should not be. (To paraphrase Einstein: matters should be as complicated as they need to be, and no more so.)

**Other information**

The fix - an improvement, anyway - is: change the menu text 'modify panel' to 'modify this panel' (i.e. add the demonstrative 'this'). You will have to ammend translations accordingly (but that is a poor reason for not making the change). You might think also about rewording 'panel options'.

The foregoing does not count as a technical bug. Yet, I am a Mint user and, partly because of my linguistic expertise, I suspect that I have a handle on what others will find helpful. (Still, I admit the following - and I do so with respect for the time, expertise and achievement of Mint's admirable programmers, and in acknowledgement of the difficulty of achieving a working union between the Linux kernel, Ubuntu and Mint. Frankly: were Mint to have fewer problems, then each such problem would exercise me less.)

**Comment by CottonEaster** [comment]
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Upon reflection, I think that the problems are as follows.

1. 'Panel settings' overlaps semantically with, 'Modify panel': both options will be changing the panel. But . .
2. Is it _the_ panel? What _is_ 'the' panel? Is it the current panel - the one that the user clicked on, or, perhaps, a currently highlighted panel? Or is it rather all panels?
3. Via 'panel settings' one can alter the current panel but, also, other panels. (My suggestions below should clarify this niggle.)
4. 'Modify' panel includes the rather drastic 'remove panel', which isn't really a modification of the panel (but rather the panel's elimination).

For a certain type of logical mind, these problems _are_ problems, though you are right in saying that clicking around does clarify matters.

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;If it were up to me, I'd have something like the following as the menu that one gets when right-clicking a panel.

-- This panel --
Add applet(s)
Arrange applets [this being what at present is called 'edit panel']
Move panel
Remove panel
Copy applet configuration
Clear all applets

-------------

Change sizes (of this and other panels)
Add a panel
Themes
System settings
Troubleshoot Cinnamon
