### ISSUE TITLE
Cinnamon 4.0.8 menu and panel text size can't be adjusted

### ISSUE THREAD

**Issue by Waterwalker7** [linuxmint/Cinnamon#8181]
Hi Have just installed Cinnamon 19.1 desktop 4.0.8. Works like a dream ...except the font size in both panel and menu are very small about 22-24 pix. The menu is also not Bold as it was in Cinnamon 19. 

Have tried adjusting the font size and text scaling factor in font selection configure system fonts, am able to increase the font size in the panel, but not the menu or drop down menus in Firefox and then LibreOffice only opens in half size.

The old system where Cinnamon adjusted the icons and fonts proportional to the panel height worked much better. Many thanks

**Comment by xenopeek** [comment]
Panel text size to be configurable was already being considered for 19.2. Thanks for reporting though! For now I'd suggest to ask on the forums (section https://forums.linuxmint.com/viewforum.php?f=211) as likely somebody there can help you edit your theme to change the text size manually that way for now.
