### ISSUE TITLE
GWL - moved apps don't appear as open when moved to another workspace

### ISSUE THREAD

**Issue by fusentast** [linuxmint/Cinnamon#8190]
```
 * Cinnamon version 4.08
 * Distribution - Mint 19.1
 * nvidia gtx 760 driver 390.77
 * 64 bit

[xsession-errors.zip](https://github.com/linuxmint/Cinnamon/files/2703800/xsession-errors.zip)


 
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
 ```

**Issue**
If any application is moved to another workspace than the workspace it is spawned in, then I'm not able to get a preview of that application, when hovering on applications icon in taskbar in other work spaces than the workspace it has been moved to.
It doesn't appear to be active either - unless switching to the actual workspace it has been moved to.

**Steps to reproduce**
open any program - move program to another work space, and watch the active indicator for that program disappears in the taskbar, and hovering doesn't produce a miniature.

**Expected behaviour**
Like other programs in several work spaces: To show miniature when mouse pointer is hovering.
When the function "show windows from all work spaces" is on that is.

**Other information**
**Same behaviour is confirmed on a live cd Linux Mint 19.1 Cinnamon 64 on another pc.**

Also some programs for example Libreoffice Writer icon will stick to task bar even after program is closed. Only way to remove sticky unpinned icon is to restart Cinnamon.

Some programs when moved will show up in taskbar as active in some work spaces  and not in others.

Resetting Cinnamon clears all issues!

**Comment by stephan-dev** [comment]
I still have this bug in 2023 (`cinnamon 4.4.8`). When moving a window to other workspace in the quickest manner : click and hold title bar, then right or left keyboard arrow.

Workaround : not doing it this way, but only by right-clicking title bar and choosing workspace to move to.
