### ISSUE TITLE
Panel settings: 'next panel' and 'previous pane' have almost no visual effect when panels are hidden

### ISSUE THREAD

**Issue by ghost** [linuxmint/cinnamon#8197]
```
 * Cinnamon version (cinnamon --version) 4.0.8
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 19.1
 * Graphics hardware *and* driver used: Intel UHD 620; 3.0
 Mesa 18.0.5
 * 32 or 64 bit: 64
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
[xs.txt](https://github.com/linuxmint/Cinnamon/files/2705699/xs.txt)
 ```

**Issue**

In a certain circumstance, the following obtains. In Panel Settings, it is hard to see which panel one is switching to - using 'next panel' or 'previous pane' - or indeed configuring. The circumstance is: the user is working with two panels and both are hidden (each panel having been set to ‘Auto-hide’ or ‘intelligently hide’). For, the only indication in that circumstance that one has switched to / is configuring some particular panel, is a very thin bar at the top or (depending on the panel position) bottom of the screen.

**Steps to reproduce**

Have a top and bottom panel, both set to hide.
Right-click a panel (when it is visible) and select 'panel settings'.
Click ‘next panel’ or ‘previous panel’.

**Expected behaviour**

Ideally, one should be able to see which panel one is configuring. (True, if one got to the configuration window via say the top panel, then that is the one that one is configuring. But what if one leaves the computer for a while, or uses the 'previous' and 'next' buttons?) Perhaps the thin line could be thickened. Or perhaps the panels should unhide when been configured (as they do when applets are being added).

**Other information**

The problem seems to have no dependence upon themes, except that some themes leave a _coloured_ (none-white) line when hidden, which makes it slightly easier to determine which panel one is configuring.

**Comment by icarter09** [comment]
@smurphos is this still an issue?

**Comment by smurphos** [comment]
Debatable - I'm not sure if the behaviour has changed since this issue was raised but an auto hidden panel will show itself for a few seconds when using the next/previous panel function in 4.4 which obviates part of the issue as raised. 

But I think the suggestion that the panel should stay unhidden when being configured is a valid feature-request and would improve usability across a variety of themes.
