### ISSUE TITLE
[SUGGESTION] - Cinnamon 4.0.x menu - hardcode fixed size for favorite and system box icon size.

### ISSUE THREAD

**Issue by smurphos** [linuxmint/cinnamon#8198]
```
 * Cinnamon version 4.0.8
 * Distribution - Mint 19.1
 * Graphics hardware *and* driver used
  Device-1: Intel 2nd Generation Core Processor Family Integrated Graphics 
  vendor: Hewlett-Packard driver: i915 v: kernel bus ID: 00:02.0 
  chip ID: 8086:0116 
  Display: x11 server: X.Org 1.19.6 driver: modesetting unloaded: fbdev,vesa 
  resolution: 1366x768~60Hz 
  OpenGL: renderer: Mesa DRI Intel Sandybridge Mobile v: 3.3 Mesa 18.0.5 
  compat-v: 3.0 direct render: Yes 
 *64 bit
 ```

**Issue**

Now that the menu favorites box is scrollable and has a user configurable minimum height it seems anachronistic to continue to shrink the icon size for situations where the number of favorites exceeds an arbitrary number based on the screen dimensions and resolution. It looks particularly odd in Mint-Y with the large padding around a tiny icon. I've got 16 favorites in this screenshot - 1366 x 768 resolution.

![screenshot-screen-2018-12-23-072413](https://user-images.githubusercontent.com/29017677/50381650-281dc480-0684-11e9-9006-abfc16751b9e.png)

Locally on my  machine I've tried 32, 24,and 22 as hardcoded sizes. The latter does not distinguish enough between the favorites box and the other menu icons but both 24 and 32 are pleasing to the eye in a variety of themes. I think I prefer 32 overall.

**Steps to reproduce**

Add more than about 10 favorites on a moderate screen resolution.

**Expected behaviour**

There is no need to shrink icons with a scrollable favorites box.

**Other information**

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
