### ISSUE TITLE
Adding PPA always activates PPA-sources invisibly

### ISSUE THREAD

**Issue by Mintulix** [linuxmint/Cinnamon#8200]
* Cinnamon version (cinnamon --version)
4.0.8

 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
LM 19.1, bug since LM 19

 * Graphics hardware *and* driver used
doesn't matter

 * 32 or 64 bit
64 bit

 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
 -

**Issue**
When a PPA is added in application sources, the PPA itself is added in the list of PPAs and also the PPA-source is added.
Default behavier is: PPA ist activated (checkbox), and the PPA-source is deactivated. But when you click OK to refresh the application sources and close the sources window and open it again, both PPA checkboxes are marked - the PPA itself and the PPA-sources.

**Steps to reproduce**
Add PPA in application sources, e.g. ppa:teejee2008/ppa.
Look at checkboxes: teejee2008 is active, teejee2008 (sources) is inactive.
Click OK to refresh the sources and close the sources window.
Open sources window again and look at the teejee2008 PPA checkboxes: both are active now.

**Expected behaviour**
PPA should stay active by default, PPA (sources) should stay unmarked/inactive by default.

**Other information**

**Comment by leigh123linux** [comment]
This has nothing to do with cinnamon code.

**Comment by Mintulix** [comment]
@leigh123linux 
So please give me a clue where to place it.

**Comment by leigh123linux** [comment]
Try https://github.com/linuxmint/mintsources/issues
