### ISSUE TITLE
Use a different icon in startup settings

### ISSUE THREAD

**Issue by NicoWeio** [linuxmint/cinnamon#8209]
```
Cinnamon 4.0.8 on Linux Mint 19.1
 ```
I've got a little suggestion for the startup settings window.
IMO the button on the bottom with this gear-icon does not do a good job at representing its function, executing the selected startup program, but rather appears as if it would open some kind of settings menu. My suggestion would be the use of a "play" button instead.

**Steps to reproduce**

Launch `cinnamon-settings startup`, select a program from the list and see the button beneath the list.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
