### ISSUE TITLE
Window position not remembered across workspaces

### ISSUE THREAD

**Issue by tamland** [linuxmint/Cinnamon#821]
When using Firefox session saving and placing different windows on different workspaces: after reopening Firefox, windows are opened in previous position, but all in the current workspace. They are not moved to the correct workspace (where it was when quitting Firefox), like in gnome 2.

**Comment by nshobe** [comment]
Same issue in Chromium, haven't checked other apps yet. Still persists in --versoin 2.4.8. 

$ uname -a
Linux 4.0.1-1-ARCH #1 SMP PREEMPT Wed Apr 29 12:00:26 CEST 2015 x86_64 GNU/Linux

**Comment by JosephMcc** [comment]
Thank you for your suggestion. See https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html for information on how we handle feature requests.
