### ISSUE TITLE
Different gap size between icon and label on new Cinnamon panel

### ISSUE THREAD

**Issue by antimatter84** [linuxmint/Cinnamon#8211]
```
 * Cinnamon version: 4.0.8
 * Distribution - Mint 19.1
 * Graphics hardware *and* driver used: Integrated Intel Core i5 M450 - standard distro driver
 * 32 or 64 bit: --> 64
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog --> ok.
 ```

**Issue**
Distance between label text and icon on the new panel have different distance. Some applications label is positioned with a larger, odd-looking gap. Screenshot of panel is attached. Applications from left to right: Firefox, Telegram Desktop, Nemo, LO Writer, Frescobaldi, Calculator, xed, Mint updater.

Applications with too large gap: Telegram, Nemo (maybe there are more)

**Steps to reproduce**
Open the applications from the paragraph "Issues".

**Expected behaviour**
All applications in the panel have the same gap between icon and label.

[xsession-errors.txt](https://github.com/linuxmint/Cinnamon/files/2712763/xsession-errors.txt)
![auswahl_002](https://user-images.githubusercontent.com/10585451/50485177-8cc67f80-09f4-11e9-8a98-912181a93dfb.png)

**Comment by smurphos** [comment]
This issue needs to be filed against https://github.com/linuxmint/mint-themes

It's a bug in both Mint-Y and Mint-X.

`.grouped-window-list-item-box` is inheriting `text-align: center;` from `.applet-box`

Adding `text-align: left;` to `.grouped-window-list-item-box` in cinnamon.css is one potential fix.

@JosephMcc
