### ISSUE TITLE
Feature request: open new app instance with left click in Grouped window list applet

### ISSUE THREAD

**Issue by TrickMe** [linuxmint/cinnamon#8212]
Cinnamon 4.0.8+tessa
Mint 19.1
Radeon Rx 570, mesa 18.3.x padoka
64 bit
 
**Expected behaviour**

Open a new instance of an application listed in the "Grouped window list"-applet not only by middle-click, but also optionally by left clicking on the icon.

**Other information**

Effectively replacing the launcher applet with Grouped window list.
Please also make running applications more visible in the applet icon, especially when minimised.

**Comment by brownsr** [comment]
Control-click also works.  The visibility of running applications will depend on how the theme treats it, so which theme are you using ?

**Comment by TrickMe** [comment]
Theme:
Desktop: Linux Mint

but Mint-X and Cinnamon also show no clearly visible indication of a running minimized app.
only Mint-Y shows a green bar underneath the icon.
Maybe just use some (minimum ~1/16 of the icon res on each side if forced) padding around the icons and tone the transparent area more or less, depending on the status of the app. Right now there is no tone at all if minimized.

You can set middle click to open a new instance of any app in the GWL configuration/General, pinned or not, I would like an option to set the same behavior to simple left click.

**Comment by icarter09** [comment]
@TrickMe did @brownsr comment help you to get past the issue you were experiencing?

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.

**Comment by TrickMe** [comment]
Thanks for reviewing my request.
Sorry for my delayed response, I was on vacation.
