### ISSUE TITLE
Icon grid: adjusting horizontal grid spacing changes icon size

### ISSUE THREAD

**Issue by CottonEaster** [linuxmint/Cinnamon#8227]
```
 * Cinnamon version (cinnamon --version): 4.0.8
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 19.1
 * Graphics hardware *and* driver used: Intel UHD Graphics 620 3.0 Mesa
 * 32 or 64 bit: 64
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog

 ```

**Issue**

Adjusting horizontal grid spacing changes the size of desktop icons.

**Steps to reproduce**

Have some (many? I have nine) icons on the desktop. Move the slider labelled - by tooltip - as 'adjust horizontal grid spacing' - randonmly. See that the size of the icons changes.

**Expected behaviour**

The icon size should not change. For, the slider at issue is meant to be about the alignment grid, not the size of icons. If it is inevitable - for some reasn - that icon size is affected, the user should (it seems to me) be made aware of that fact.

**Comment by smurphos** [comment]
If this is a bug it should be filed against https://github.com/linuxmint/nemo as nemo-desktop controls the desktop.

I can't reproduce this.

Try deleting `~/.config/nemo/desktop-metadata`, then restart Cinnamon with Ctrl-Alt-Esc. Does the issue still occur?

**Comment by leigh123linux** [comment]
File the issue against nemo!
