### ISSUE TITLE
Mint 19.1 screensaver freeze with kernel 4.18

### ISSUE THREAD

**Issue by linux-man** [linuxmint/Cinnamon#8228]
* Cinnamon version 4.0.8
 * Distribution - Mint 19.1 64 bit
 * Graphics hardware Nvidia 930MX with 390.77-0ubuntu0.18.04.1 driver

Mint 19.1 screensaver freeze with kernel 4.18

Lock cinnamon
Wait some time (1-2 hours)
try to unlock

The clock had stopped working some time ago and there is no response.
Had to change to a terminal to reboot system.

**Comment by linux-man** [comment]
Ir looks like the same happens with 4.15 default kernel.

**Comment by leigh123linux** [comment]
screensaver isn't part of cinnamon, also I doubt it's responsible for the freeze.
Try looking at xorg logs and other logging for clues.
