### ISSUE TITLE
sudo password is typed as characters of asteriks

### ISSUE THREAD

**Issue by meysam81** [linuxmint/Cinnamon#8232]
```
 * Cinnamon version (4.0.8)
 * Distribution - (Mint 19.1)
 * Graphics hardware Nvidia *and* Intel
 * 64 bit
 ```

**Issue**
in the new linux mint 19.1 Tessa, after running a sudo command for the first time (when it is asking for a password), the typing password is types as characters of asteriks (*), which wasn't the case before.

**Comment by leigh123linux** [comment]
I believe ubuntu changed something in sudo config.

**Comment by Odyseus** [comment]
Hello, everybody.

@meysam81: You can get rid of those asterisks by removing the **/etc/sudoers.d/0pwfeedback** file.

**Comment by tkivisik** [comment]
If deleting seems too scary:
`sudo nano /etc/sudoers.d/0pwfeedback`
From:
`Defaults pwfeedback`
To:
`Defaults !pwfeedback`

**Comment by claudiux** [comment]
Commenting the line also do the trick.

**Comment by smurphos** [comment]
> I believe ubuntu changed something in sudo config.

No it's added by mintsystem - https://github.com/linuxmint/mintsystem/commit/ffad4cc9ea5ee2b8541d28bc74f613fe70ff72b2

As any update to the mintsystem package will recreate the original /etc/sudoers.d/0pwfeedback the best way to change the behaviour is by adding another override file.

`echo 'Defaults !pwfeedback'|sudo tee /etc/sudoers.d/9_no_pwfeedback`
