### ISSUE TITLE
Colour profile for monitor unloadable

### ISSUE THREAD

**Issue by ghost** [linuxmint/cinnamon#8233]
```
 * Cinnamon version (cinnamon --version): Cinnamon 4.0.8
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 19.1
 * Graphics hardware *and* driver used: Intel UHD Graphics 620 3.0 Mesa
 * 32 or 64 bit: 64
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
 ```

**Issue**

I cannot make to load or setup a colour profile for my monitor, even though I have a profile file that used to work.

**Steps to reproduce**

Screenshot:

![image](https://user-images.githubusercontent.com/9998846/50548744-13c06580-0c4a-11e9-9a90-873b86f0c76e.png)

Settings -> Colour -> lists no devicces. 'Add Device' has no monitor option. Nor does the 'add profile' button offer anything (it shows no profiles). Nor does dragging a monitor colour profile - that I had working on a previous Mint install, somehow - work. That profile is a .icc file. Double clicking the file results in a prompt asking me what I wish to open the file file with - and I do not know what to choose, if indeed anything on my system would be the right choice.

**Expected behaviour**

It should be easy to install a colour profile for one's monitor or at the least, if extra software is needed, the user should be told so.

**Other information**

I have the problem on my main Mint install. Yet, I find also that, on a fairly clean install of Mint 19.1 Cinnamon, in Virtual Box (on Windows), a monitor entry does show up and it does offer various profiles. Screenshot:

![image](https://user-images.githubusercontent.com/9998846/50548822-17a0b780-0c4b-11e9-882b-211c8db09c65.png)

I saw that the virtual install had `colord` whereas the real install did not; but install that package on the latter, while it did alter the colour profile dialog, did not help me install my profile.

Installing `gnome-colour-manager` (which was absent from both systems) looked hopeful but failed to import my profile file (a file created especially for my machine and its display).

**Comment by CottonEaster** [comment]
The problem could be the one - upstream, it seems - described [here](https://bugs.freedesktop.org/show_bug.cgi?id=82770).

**Comment by icarter09** [comment]
Closing this issue since the original submitter of this ticket is no longer present on Github.
