### ISSUE TITLE
Google Earth freezing OS 

### ISSUE THREAD

**Issue by gjzega** [linuxmint/Cinnamon#8237]
Google Earth has crashed my Linux Mint 19, 64 bit, Cinnamon 3.8.9 THREE times so that the system would NOT reboot.  I had to reinstall the OS each  time. SONY VAIO VPCZ2190X
Google Earth would load and run for a few days- weeks but it was always running when the computer froze to make a reboot impossible.
  In over 30 years I have never had a program crash a computer by corrupting the BOOT.
Is Google trying to screw Linux with a NO-REBOOT?.. 

 * Cinnamon version (cinnamon --version)
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
 * Graphics hardware *and* driver used
 * 32 or 64 bit
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
 ```

**Issue**



**Steps to reproduce**



**Expected behaviour**



**Other information**

**Comment by leigh123linux** [comment]
Go and bug google.
