### ISSUE TITLE
application installed by flatpak is not executed

### ISSUE THREAD

**Issue by hudsonfas** [linuxmint/Cinnamon#8239]
```
 * Cinnamon 3.8.8
 * Ubuntu 18.10 cosmic (x86-64)
 * Intel Corporation HD Graphics 620
 ```

**Issue**
After installed by flatpak (sudo flatpak install flathub org.videolan.VLC), VLC is not executed
```
~$ flatpak run org.videolan.VLC
VLC media player 3.0.5 Vetinari (revision 3.0.5-1-0-g653c0c1ca8)
[000000000081a010] main libvlc: Running vlc with the default interface. Use 'cvlc' to use vlc without interface.
Gtk-Message: Failed to load module "appmenu-gtk-module"

(vlc.bin:2): GLib-GIO-ERROR **: Settings schema 'org.cinnamon.desktop.interface' is not installed
```
the same thing happens when executing Shotcut and Openshot via flatpak

Flatpak version: 1.0.6

Flatpak VLC, Openshot and Shotcut work on Ubuntu Desktop  and Gnome Desktop

**Steps to reproduce**
$ sudo apt -y install flatpak
$ sudo flatpak install flathub org.videolan.VLC
$ flatpak run org.videolan.VLC

**Other information**

**Comment by icarter09** [comment]
Cinnamon 4.0.8
Linux Mint 19.1 64bit

@hudsonfas I'm not able to duplicate this issue on Linux Mint. I went through the steps to reproduce, but VLC started and ran just fine on the last step.

**Comment by pyroxar** [comment]
I can't reproduce this bug. Linux Mint 19 Cinnamon.

**Comment by mtwebster** [comment]
Sounds like you need to install the 'cinnamon-desktop-data' package (part of cinnamon-desktop)  I'm not certain how you're running cinnamon though if this is the case.

Do you have xdg-desktop-portal-gtk installed?

**Comment by jaszhix** [comment]
Sounds familiar to https://github.com/linuxmint/Cinnamon/issues/7974#issuecomment-435155790. This is probably happening because the deb version of VLC is installed.

**Comment by icarter09** [comment]
@hudsonfas I performed the steps with both OpenShot and Shotcut. Both worked as well for me.

**Comment by hudsonfas** [comment]
thank you guys

after removing flatpak applications and uninstalling and reinstalling
flatpak, everything is now working.


Em dom, 6 de jan de 2019 às 02:28, claudiux <notifications@github.com>
escreveu:

**Comment by hudsonfas** [comment]
after removing flatpak applications (i had **system** flatpak apps and *user* flatpak apps) and uninstalling and reinstalling deb flatpak and install my **user only** apps, everything is now working.
