### ISSUE TITLE
[Feature Request] MacOS X Expose (Keyboard and mouse remapping)

### ISSUE THREAD

**Issue by oxoocoffee** [linuxmint/cinnamon#8240]
```
 * Cinnamon 4.0.8
 * Distribution Mint 19.1
 * NVIDIA UNIX x86_64 Kernel Module  415.25  Wed Dec 12 10:22:08 CST 2018
 * 64 bit
 ```

**Missing**
Missing Better Expose Configuration (Mouse and Keyboard)

**Other information**
I just switched from 18 to 19 Mint. On mint 18 I used compiz to configure various options. I understand from my reading that compiz is not working under Mint 19.

What I loved in previous version that I could assign extra mouse buttons to enable Expose so I could quickly see all workspaces by clicking extra button. I did checked System Settings -> Mouse and Track Pad or Workspaces for such options. It is something I use on my Mac OS X all the time.

Also in current 19.1 I can only use Control-Alt+{Left, Right) buttons to toggle between workspaces. I did see some other people complaining about it. Again in System Preferences -> Keyboard -> Workspaces there are "Switch to left and right" that could be remapped. But there is no Up/Down option.

Perhaps I am missing some other settings since I am new to 19.1. I did google and asked on IRC and no one knows.

**Comment by icarter09** [comment]
@oxoocoffee Are you not able to create a custom shortcut for the Up/Down option?

**Comment by oxoocoffee** [comment]
@icarter09 I can click on "Add custom shortcut". A pop up dialog shows up. I am not sure what command I should add. Perhaps it would be possible to make this searchable combo box? I am wondering why both options are not listed under Workspaces? I think they should be there and by default unassigned?

As far as mouse button mapping to Expose is this a good thread? Or should I open separate case? For which extension/plugin?

**Comment by mtwebster** [comment]
You mentioned compiz, are you sure you don't mean to be using Mate?  Cinnamon doesn't use a separate window manager, and also only supports a single 'row' of workspaces (out of the box) and the up/down shortcuts are repurposed to open expo/overview modes.

**Comment by oxoocoffee** [comment]
@mtwebster Yes I did use Mate 18. I decided to update and switch to Cinnamon 19. I guess it is my fault not checking in more detail. Now that I am here what are my options?
Since I am all setup and it took me couple of full days to rebuild all my git/sources/etc, Is there an easy way to switch to Mate 19 and possibly uninstall all Cinnamon? I could leave Cinnamon for testing if there are some changes coming. Are there any plans to allow better mouse/keyboard configurations? Or I have to switch to Mate? Does Mate 19 supports compz?

**Comment by oxoocoffee** [comment]
I was wondering if such option will be considered in near future. Else If I would like to contribute where would I start? What would be a good place to add this so it could be considered for PR?

**Comment by oxoocoffee** [comment]
Looking at code I am considering adding such option to eater cs_workspaces.py or cs_mouse.py. Before I will do it what would be the best place to add this. Would such PR be accepted?
I am thinking adding drop box with mouse buttons (Disable, Btn1, Btn2, Btn3, etc) and assign it to Show All Workspaces like it is in HotCorners. Also another drop box to assign another free mouse btn with option to show all applications (Shift-Control-Down). This is a nice feature I am missing from my Mac OS X.

**Comment by icarter09** [comment]
@oxoocoffee did you ever submit the PR you mentioned? The only way to know if it would be accepted is to submit it. If you haven't submitted the PR, then I'll close this ticket out and add the feature request to a list being created for roadmapping future functionality.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
