### ISSUE TITLE
symbolic links seems to be not working without relative in the new mint 19.1

### ISSUE THREAD

**Issue by meysam81** [linuxmint/Cinnamon#8243]
```
 * Cinnamon version (4.0.8)
 * Distribution - (Mint 19.1)
 * Nvidia GeForce & Intel
 * 64 bit
 ```

**Issue**
In the new release of linux mint 19.1, it seems that I can no longer create a symbolic link to a file without specifying --relative option. It seemed to be working before, but not now apparently.

**Comment by leigh123linux** [comment]
File the issue against nemo.

https://github.com/linuxmint/nemo
