### ISSUE TITLE
Feature Request: Tabbed windows

### ISSUE THREAD

**Issue by stellarpower** [linuxmint/cinnamon#8250]
Not sure if this is the place for feature requests, so if not I will happily move elsewhere.

I have just downloaded the gTile spice and am very much looking forward to using it, however one thing that would really help my workflow would be to have tabbed windows.

What I mean by this is just as Nemo and firefox can tab different pages within the same program, I would love to be able to tab the windows of different applications into one parent window, and switch between them quickly - something like [this](https://imgur.com/a/70b1c9R):

For example, if I am working on some web development, I may divide my screen into four sections, with a terminal in the bottom-left, my text editor in the bottom-right, a firefox window in the top-right with documentation and searches for what I'm developing. Now say I'd like to see how my website looks in multiple browsers, so I have Chrome, Firefox, and an Android Emulator open. I can snap all these windows into the top-left corner, but to switch between them in the menu bar, and if I have a number of firefox windows open for other purposes, it can take a while to find the one I want. It'd be great if I could drag those windows into one container, and have a tabbed interface for them, so I can click between similar related applications quickly and easily. 

Questions include how minimal this interface would be - minimise and quit buttons for the whole group would be useful, but if they occur on top of the buttons for the individual window, it an look a bit chaotic, as in the screenshot. However now apps expect to be able to draw in their title bars, so it's probably not a good idea to get rid of the individual windows' title bars; the positioning of the tabs (top, bottom, side?); drop-down menus for renaming, closing, etc.

Thanks

**Comment by icarter09** [comment]
@stellarpower 
 1. Yes this is the correct place for feature requests.
 2. Your github profile pic is beyond awesome!

**Comment by stellarpower** [comment]
Glad I'm not the only one who appreciates a bit of Moss in this Sheldon-dominated world!
