### ISSUE TITLE
Panel: 1px line at bottom/top

### ISSUE THREAD

**Issue by MegaV0lt** [linuxmint/Cinnamon#8253]
```
 * Cinnamon 4.08
 * Mint 19.1
 * Graphics hardware *and* driver used
   Device-2: NVIDIA GP107 [GeForce GTX 1050 Ti] driver: nvidia v: 390.87
 * 64 bit
 ```

**Issue**
a small line of 1px shows at bottm of the panel and at top of top panel
Theme :
![auswahl_20190103_12 51 03](https://user-images.githubusercontent.com/2804301/50636421-49b95e80-0f56-11e9-9276-f707005c42c6.jpg)

**Other information**
Tryed to make a screenshot, but is very hard to see.
![auswahl_20190103_12 44 24](https://user-images.githubusercontent.com/2804301/50636445-5e95f200-0f56-11e9-89fe-7b703f2dd61c.jpg)

**Comment by jaszhix** [comment]
I can reproduce this when enabling the transparent panels extension. I would file the issue [here](https://github.com/germanfr/cinnamon-transparent-panels).
