### ISSUE TITLE
Inconsistent application title placement

### ISSUE THREAD

**Issue by eblis** [linuxmint/Cinnamon#8256]
```
 * Cinnamon version 4.0.8
 * Distribution - Mint 19.1
 * Intel CPU and GPU
 * 64 bit
 ```

**Issue**
I have 3 separate monitors with each monitor running an instance of Group Window List with basically the same settings, albeit different pinned applications.
Although the middle monitor is configured as the main one usually when I start applications they appear on the left-most monitor instead (not a big issue).
However when moving the applications back to the main monitor the taskbar entry for the application remains on the left-most monitor, even though the application is maximized on the middle monitor. So I have to look at my left-most monitor to control an application visible on my middle monitor. When switching to another Workspace (than the one where I originally started the application) the application correctly shows on the middle monitor Group Window List.

**Steps to reproduce**
Have 3 monitors, left, center, right with a Group Window List configured for each of them.
Configure center monitor as the main one.
Start an application which starts on the left monitor.
Move the application to the center monitor.
The application window moves, but it's title in the Group Window List applet does not, it remains in the Group Window List applet from the left-most monitor.

**Expected behaviour**
The application title in the taskbar should move as well.

**Comment by jaszhix** [comment]
Fixed in #8192.
