### ISSUE TITLE
Calendar applet do not scale with panel height

### ISSUE THREAD

**Issue by HenryJk** [linuxmint/cinnamon#8260]
```
 * Cinnamon 4.0.8
 * Distribution - Mint 19.1
 * Nvidia GeForce 940MX *and* nvidia-driver 415
 * 64 bit
 ```

**Issue**
Official calendar applet text do not scale with panel height, making it laughably small on big panel.

**Steps to reproduce**
Add calendar applet to panel, enlarge panel.

**Expected behaviour**
Calendar applet fonts should scale with panel, just like in linux mint 19.

**Other information**
![screenshot from 2019-01-04 15-01-42](https://user-images.githubusercontent.com/25541369/50677052-ad18be80-1032-11e9-9cdf-bd973e623bea.png)

**Comment by cardsurf** [comment]
Below is a workaround that worked for me:
1. In `~/.themes/[ThemeName]/cinnamon/cinnamon.css`file increase value of `font-size` parameter in `#panel` section.
2. Restart Cinnamon.

**Comment by HenryJk** [comment]
> Below is a workaround that worked for me:
> 
> 1. In `~/.themes/[ThemeName]/cinnamon/cinnamon.css`file increase value of `font-size` parameter in `#panel` section.
> 2. Restart Cinnamon.

That is exactly what I did, but I still feel it is a bug that needs fixing, instead of relying end user for workarounds.

**Comment by mbward** [comment]
What's the current status?

**Comment by smurphos** [comment]
Fixed / non-issue since Cinnamon 4.4.x - panel font sizes can be adjusted as the end-user sees fit in Panel Settings.

**Comment by icarter09** [comment]
The calendar applet looks like it's not picking up changes to the panel font sizes.

**Comment by JosephMcc** [comment]
This is working for me both changing the font size in the panel settings or by changing the size of the default font in the font settings.

**Comment by icarter09** [comment]
Nm.  I'm an idiot and didn't realize the importance of "Right Zone" on the Panel settings.
