### ISSUE TITLE
[FEATURE REQUEST] Remove from Favorites

### ISSUE THREAD

**Issue by JustinOros** [linuxmint/cinnamon#8262]
**Feature Request**

Add option "Remove" when user secondary-mouse-clicks on a Favorite in Menu.

**Comment by brownsr** [comment]
An application can already be removed from favourites by highlighting it in favourites and hitting the delete key.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
