### ISSUE TITLE
[FEATURE REQUEST] Auto-Update

### ISSUE THREAD

**Issue by JustinOros** [linuxmint/cinnamon#8263]
**Feature Request**

It needs to be even easier for non tech-savvy users to enable the auto-update feature.

Please add a single checkbox item in the Welcome Menu: "Install Updates automatically".

**Comment by JosephMcc** [comment]
This isn't an issue for Cinnamon. Suggestions and bugs for Mint in general should go to: https://github.com/linuxmint/linuxmint/issues
