### ISSUE TITLE
Windows Key + Directional key window resizing not always sizing precisely

### ISSUE THREAD

**Issue by tkivisik** [linuxmint/Cinnamon#8264]
```
* Cinnamon version - 4.0.8
* Distribution - Mint 19.1
* Graphics:
  Device-1: Intel Haswell-ULT Integrated Graphics vendor: Lenovo 
  driver: i915 v: kernel bus ID: 00:02.0 
  Display: x11 server: X.Org 1.19.6 driver: modesetting unloaded: fbdev,vesa 
  resolution: 1920x1080~60Hz 
  OpenGL: renderer: Mesa DRI Intel Haswell Mobile v: 4.5 Mesa 18.0.5 
  direct render: Yes 
* 64 bit
 ```

**Issue**
Windows Key + Directional key window resizing ending up with a hole between two windows.

**Steps to reproduce**
Open a terminal (CTRL ALT T)
Move it to the left top corner (WIN Left Arrow, WIN Up Arrow)
Open a second terminal (CTRL ALT T)
Move it to the top right corner (WIN Right Arrow, WIN Up Arrow)
Extend the top right terminal along the whole right side of the screen (Win Down Arrow)
==> See that the right terminal got reduced in width.

**Expected behaviour**
When two windows are resized using windows key + directional key, then they should nicely come together.

**Other information**
I tried to replicate it with a Google Chrome window. The steps to reproduce it did not work.

**Comment by jaszhix** [comment]
https://github.com/linuxmint/muffin/issues/396
