### ISSUE TITLE
Skype icon in the system tray is very small and does not scale with panel.

### ISSUE THREAD

**Issue by yesint** [linuxmint/Cinnamon#8270]
```
 * Cinnamon version 4.0.8
 * Distribution - Mint 19.1
  * 64 bit
 ```

**Issue**

Skype icon in the system tray is very small and does not scale with panel. 
![screenshot from 2019-01-07 14-40-39](https://user-images.githubusercontent.com/14368585/50771556-42ae8b00-128b-11e9-8887-33b1104c3d29.png)

**Steps to reproduce**

Just start skype on hi-dpi screen.

**Expected behaviour**

Skype icon should respect the panel size and be the same size as other system tray icons.

**Other information**
The file /usr/share/cinnamon/applets/systray@cinnamon.org/applet.js, line 268 reads:
```
if (["skypeforlinux"].indexOf(role) != -1) {
            let size = 16 * global.ui_scale;
            icon.set_size(size, size);
```
I tried to change 16 to 32 but instead of larger icon I've got two icons side by side (attached).
![screenshot from 2019-01-07 14-40-06](https://user-images.githubusercontent.com/14368585/50771575-51953d80-128b-11e9-830f-2bdb1acce4c7.png)

**Comment by clefebvre** [comment]
Hi @yesint, there's nothing we can do to fix this. Skype's sysicon only works in 16px, that's why we have that code in place and prevent it from scaling. This needs to be fixed upstream I'm afraid.

**Comment by yesint** [comment]
Is it possible to add a custom rule to put some extra padding around this small icon? The problem on hi-dpi screens is to hit it by mouse because it is tiny and squeezed between other icons.
