### ISSUE TITLE
[FEATURE REQUEST] Make tiny skype icon easier to interact with

### ISSUE THREAD

**Issue by yesint** [linuxmint/cinnamon#8271]
Skype icon in the system tray is always 16 px and apparently it is only possible to fix upstream (#8270 ). The problem on hi-dpi screens is to hit this icon by mouse because it is tiny and squeezed between other icons.

Is it possible to add some extra padding around this small icon so that it is centered in the rectangular area, which scales with the panel?

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
