### ISSUE TITLE
[FEATURE REQUEST] Bing daily picture support

### ISSUE THREAD

**Issue by lucamosca1** [linuxmint/cinnamon#8272]
Would be great to have support for bing daily picture as a lock screen. Gnome already handle this via proper extension

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
