### ISSUE TITLE
[FEATURE REQUEST] Shutdown command to be improved in login screen

### ISSUE THREAD

**Issue by lucamosca1** [linuxmint/cinnamon#8273]
If I want to shutdown my computer from initial login screen, the confirmation is still old-looking (is it the one from ubuntu-unity?)

**Comment by lalincedeldeserto** [comment]
Yes it is

**Comment by lalincedeldeserto** [comment]
I think that if you want to change the initial login screen you should replace it with another one. In other terms: you are using a display manager (it should be lightdm). If you want something different, try installing another dm. Search into Wikipedia display manager and you'll see the common dm. If you don't want lightdm, remove it following ubuntu guides.

**Comment by JosephMcc** [comment]
This isn't a Cinnamon issue but instead one for slick-greeter.
