### ISSUE TITLE
Regression in tiling for windows that prefer certain sizes, like xterm

### ISSUE THREAD

**Issue by amaurea** [linuxmint/Cinnamon#8274]
```
 * Cinnamon version 4.0.8
 * Distribution - Arch
 * Intel integrated graphics: HD Graphics 620, driver i915
 * 64 bit
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog

[xsession-errors.txt](https://github.com/linuxmint/Cinnamon/files/2737155/xsession-errors.txt) (probably not relevant, but attached as requested)

 ```

**Issue**

In recent versions of cinnamon, some tiling operations leave gaps between tiles for some windows. I've only noticed this happening with xterm, and I assume that it has to do with xterm wanting the window to have a width and height that matches the character size. However, this only happens for some tiling operations, and it used to not happen at all, so this is clearly an avoidable issue.

**Steps to reproduce**

1. Starting from an empty desktop, span an xterm window:

![cinnamon_tiling1](https://user-images.githubusercontent.com/3407492/50837670-7f968280-135c-11e9-86a8-2b88d412ec9d.png)

2. Tile the window to the left.

![cinnamon_tiling2](https://user-images.githubusercontent.com/3407492/50837692-8cb37180-135c-11e9-9454-a12c13e090d1.png)

3. Spawn another xterm.

![cinnamon_tiling3](https://user-images.githubusercontent.com/3407492/50837705-96d57000-135c-11e9-9991-58b4f3e1e19d.png)

4. Tile it to the right. Notice that the windows tile smoothly, with no gap between.

![cinnamon_tiling4](https://user-images.githubusercontent.com/3407492/50837731-a81e7c80-135c-11e9-80d9-373869486e11.png)

5. Tile the right window upwards, to make it cover only the top-right quarter of the screen. Even though this should only change the height, not width of the window, the width ends up shrinking slightly, leaving a gap between this window and the one to the left.

![cinnamon_tiling5](https://user-images.githubusercontent.com/3407492/50837796-d0a67680-135c-11e9-90ae-f438bd976844.png)

(It's possible to get rid of this gap by then tiling the window to the left, and then to the right again, but it's annoying to have to do this, especially since this used to work)

**Expected behaviour**

There should be no gap between the left and the right window.

**Other information**

As I said this used to work, so this is a regression. I don't know exactly which version it appeared in, but I've only had this problem for a few months.

**Comment by jaszhix** [comment]
https://github.com/linuxmint/muffin/issues/396
