### ISSUE TITLE
Create a new launcher is broken

### ISSUE THREAD

**Issue by ocafebabe** [linuxmint/Cinnamon#8275]
```
 * Cinnamon version - 4.0.9
 * Distribution - Mint 19.1
 * Graphics hardware *and* driver used - N/A
 * 64 bit
 ```

**Issue**

I'm trying to create a new custom launcher but nothing happens!

**Steps to reproduce**

Right-click on the desktop and then click on "Create a new launcher here..."

**Expected behaviour**

Launcher Properties window

**Other information**

A Python stacktrace is generated in the xsession-errors log every 
time I repeat the action:
```python
Traceback (most recent call last):
  File "/usr/share/cinnamon/cinnamon-desktop-editor/cinnamon-desktop-editor.py", line 422, in <module>
    Main()
  File "/usr/share/cinnamon/cinnamon-desktop-editor/cinnamon-desktop-editor.py", line 356, in __init__
    editor = LauncherEditor(self.orig_file, self.nemo_launcher_cb, self.dest_dir)
  File "/usr/share/cinnamon/cinnamon-desktop-editor/cinnamon-desktop-editor.py", line 75, in __init__
    self.check_custom_path()
  File "/usr/share/cinnamon/cinnamon-desktop-editor/cinnamon-desktop-editor.py", line 226, in check_custom_path
    self.item_path = os.path.join(util.getUserItemPath(), os.path.split(self.item_path)[1])
  File "/usr/lib/python3.6/posixpath.py", line 107, in split
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by bitstrings** [comment]
Maybe this is related, but "path=" in a desktop file is ignored.

**Comment by ocafebabe** [comment]
This seems to be a regression bug with 4.0.9 because I tested the same action on a vanilla installation of Mint 19.1 (Cinnamon 4.0.8) and it worked perfectly!

**Comment by luke2136** [comment]
Mint 19.1 same issue...occurred after 4.09 upgrade yesterday Jan. 8
tested on second machine with 4.08 worked fine, then upgraded it to 4.09...and does not work.

**Comment by Niel0** [comment]
Same here, LM 19.1 was working fine with 4.0.8 allowing the creation of desktop launchers, Cinnamon updated to 4.0.9 earlier today (9 January) and I can no longer create a desktop launcher bu right clicking and choosing "create a new launcher here". If I choose an application from the mintmenu and choose "Add to Desktop" then a launcher is created OK.

**Comment by tonywhelan** [comment]
Same issue here. Fresh install is ok but if upgrading from tara to tessa the 'Create desktop launcher' feature does not work.

**Comment by garypigott39** [comment]
Same here

**Comment by phamtrongthang123** [comment]
Same too. Fresh install and nothing happens if click on "create a new launcher here"

**Comment by smurphos** [comment]
Until as and when a Cinnamon update is pushed including https://github.com/linuxmint/Cinnamon/commit/c42a03a01e988ad6160187c7697425cd99992f08 you can apply the fix to Cinnamon 4.0.9 by applying the attached patch
[cinnamon-desktop-editor-c42a03a.py.patch.zip](https://github.com/linuxmint/Cinnamon/files/2781704/cinnamon-desktop-editor-c42a03a.py.patch.zip)

In a terminal window....

`wget https://github.com/linuxmint/Cinnamon/files/2781704/cinnamon-desktop-editor-c42a03a.py.patch.zip`

`unzip cinnamon-desktop-editor-c42a03a.py.patch.zip`

`sudo patch /usr/share/cinnamon/cinnamon-desktop-editor/cinnamon-desktop-editor.py < cinnamon-desktop-editor-c42a03a.py.patch`

**Comment by Mario156090** [comment]
> Until as and when a Cinnamon update is pushed including [c42a03a](https://github.com/linuxmint/Cinnamon/commit/c42a03a01e988ad6160187c7697425cd99992f08) you can apply the fix to Cinnamon 4.0.9 by applying the attached patch
> [cinnamon-desktop-editor-c42a03a.py.patch.zip](https://github.com/linuxmint/Cinnamon/files/2781704/cinnamon-desktop-editor-c42a03a.py.patch.zip)
> 
> In a terminal window....
> 
> `wget https://github.com/linuxmint/Cinnamon/files/2781704/cinnamon-desktop-editor-c42a03a.py.patch.zip`
> 
> `unzip cinnamon-desktop-editor-c42a03a.py.patch.zip`
> 
> `sudo patch /usr/share/cinnamon/cinnamon-desktop-editor/cinnamon-desktop-editor.py < cinnamon-desktop-editor-c42a03a.py.patch`

You are a genius, it's work for me.

**Comment by Wikinaut** [comment]
I confirm, that the patch fixes the issue.

**Comment by leoperria** [comment]
It worked for me as well ! thanks

**Comment by titsbetter** [comment]
Thanks much smurphos, it Now works fine.

**Comment by Techbane** [comment]
`patching file /usr/share/cinnamon/desktop-editor/cinnamon-desktop-editor.py`
`Hunk #1 FAILED at 223.`
`patch: **** Can't reopen file /usr/share/cinnamon/desktop-editor/cinnamon-desktop-editor.py : No such file or directory`

I'm not particularly Linux literate yet, but it seems out of the ordinary for this file to be _missing_

**Comment by junchaozhang** [comment]
It work for me, thx!

**Comment by amarilis** [comment]
It worked for me as well ! thanks

**Comment by smurphos** [comment]
The patch/workaround should be obsolete now with Cinnamon 4.0.10 having been released.

**Comment by oldgranola** [comment]
I am running Cinnamon 4.0.10 however I still have this problem so its not fixed. BTW, the patch did not work
