### ISSUE TITLE
Touchpad tap click not working on login screen

### ISSUE THREAD

**Issue by shrinathk** [linuxmint/Cinnamon#8280]
```
 * Cinnamon version (cinnamon --version) - Cinnamon 3.8.9

 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) - Mint 19

 * Graphics hardware *and* driver used:
VGA compatible controller: Intel Corporation HD Graphics 520 (rev 07).
Subsystem: Dell Skylake GT2 [HD Graphics 520].
Kernel driver in use: i915.

 * 32 or 64 bit - 64 bit

 * Attach /home/<username>/.xsession-errors, or /var/log/syslog - Will add if required.
 ```

**Issue**
On the login screen (where the username shows up and asks us the password), unable to use touchpad to single tap and open the "Quit" dialog to shutdown the system. The touchpad single tap works fine once logged into the Cinnamon desktop.

**Steps to reproduce**
Turn on the system. Wait for login screen. Do not login. Try to use touchpad to click the "Quit" icon on the top right.

**Expected behaviour**
Touchpad tap should work on the login screen.

**Other information**
Using Dell 5559 laptop, default themes. Did not make any major changes to the standard desktop.

**Comment by clefebvre** [comment]
Hi @shrinathk, this isn't related to Cinnamon. It's system-wide and it has to do with Xorg itself.

Can you try this? https://www.reddit.com/r/linuxmint/comments/90ngor/taptoclick_using_touchpad_is_not_working_on/

**Comment by dipenSan** [comment]
Hi, I'm facing same problem too on my Acer laptop. I'm using Linux mint 19.1 cinnamon 4.0. once login to desktop single touchpad tap works fine but not working on login screen. Then now it's clear that this is not excepted behaviour.
