### ISSUE TITLE
Removing Window-List applet via Applet Settings GUI also removes all instances of the Grouped-Window-List

### ISSUE THREAD

**Issue by smurphos** [linuxmint/cinnamon#8282]
```
 * Cinnamon version 4.0.9
 * Distribution - Mint 19.1
 * Graphics hardware *and* driver used
Graphics:
  Device-1: Intel 2nd Generation Core Processor Family Integrated Graphics 
  vendor: Hewlett-Packard driver: i915 v: kernel bus ID: 00:02.0 
  chip ID: 8086:0116 
  Display: x11 server: X.Org 1.19.6 driver: modesetting unloaded: fbdev,vesa 
  resolution: 1366x768~60Hz 
  OpenGL: renderer: Mesa DRI Intel Sandybridge Mobile v: 3.3 Mesa 18.0.5 
  compat-v: 3.0 direct render: Yes 
 * 64 bit
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
 ```

**Issue**
Removing the window-list applet via the Applet's Settings module removes all instances of GWL from all panels. The reverse is not true. Removing the window-list applet via right click on the applet does not have this affect.

**Steps to reproduce**
Add one or more instances of GWL to any panel and one or more instances of the window-list to a panel.
Remove the window-list via the remove button in the Applet GUI. Observe all instances of GWL also being removed.

No xsession-errors output is noted with this action.

**Expected behaviour**
Removing with window-list applet should have no impact on any instances of the grouped-window-list

**Other information**
Behaviour is 100% reproducible - also tried on a fresh user account. Originally reported by another user here https://forums.linuxmint.com/viewtopic.php?p=1578025#p1578025 and subsequently reproduced.

**Comment by Odyseus** [comment]
Hello, everybody.

I was able to reproduce this. The problem seems to exist in the [**disable_extension** method of the **Spice_Harvester** class](https://github.com/linuxmint/Cinnamon/blob/master/files/usr/share/cinnamon/cinnamon-settings/bin/Spices.py#L777):

The following condition is problematic:

```python
for enabled_extension in enabled_extensions:
    if uuid not in enabled_extension: # This condition is problematic.
        new_list.append(enabled_extension)
```

The following condition works:

```python
for enabled_extension in enabled_extensions:
    if uuid != enabled_extension.split(":")[3]: # This condition works.
        new_list.append(enabled_extension)
```

The following condition might also work (not tested):

```python
for enabled_extension in enabled_extensions:
    if uuid not in enabled_extension.split(":"):
        new_list.append(enabled_extension)
```

@collinss ?
