### ISSUE TITLE
In workspace overview, allow rearranging workspaces

### ISSUE THREAD

**Issue by Axelderan** [linuxmint/cinnamon#8283]
In the workspace overview, it is possible to drag windows from one workspace to another.  This is quite nice.  It is a much better default behavior than on MacOS where one cannot do this in a simple way.  On the Mac, instead one can rearrange workspaces by clicking and dragging.

Why not have both?  In the workspace overview, perhaps when holding shift, clicking and dragging could rearrange the workspaces themselves with all their contents.  Or as a purely keyboard shortcut, ctrl+shift+alt+arrow is currently unbound and analogizes nicely with the same keyboard shortcut when not in the workspace overview.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
