### ISSUE TITLE
LMDE3 Cinnamon 4.0.9 cinnamon-settings power crash and power applet unable to get battery state.

### ISSUE THREAD

**Issue by smurphos** [linuxmint/cinnamon#8285]
```
 * Cinnamon version 4.0.9
 * Distribution - LMDE3
 * Graphics hardware *and* driver used
Graphics:  Card: InnoTek Systemberatung VirtualBox Graphics Adapter
           bus-ID: 00:02.0 chip-ID: 80ee:beef
           Display Server: X.Org 1.19.2 drivers: modesetting (unloaded: fbdev,vesa)
           Resolution: 1360x768@59.80hz
           GLX Renderer: Chromium
           GLX Version: 2.1 Chromium 1.9 Direct Rendering: Yes
 * 64 bit
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
 ```

**Issue**
The power settings module is crashing in LMDE3 following update to Cinnamon 4.0.9. I've reproduced this issue in a Virtualbox install - however a couple of users on bare-metal have also reported it at the Mint forum - see https://forums.linuxmint.com/viewtopic.php?f=247&t=285476. On the same hardware in another virtualbox install main edition 19.1 is not showing the problem. The power applet is also unable to detect a battery state. Both worked fine on Cinnamon 3.8.6.

LMDE
```
UPower client version 0.99.4
UPower daemon version 0.99.4
```
Mint 19.1
```
UPower client version 0.99.7
UPower daemon version 0.99.7
```

Please see pastebin link for output of cinnamon-settings power, upower -e, upower -d, xsession-errors and syslog. I've got no mintreport in LMDE to get a crash log

https://pastebin.com/4eQqrKK2

**Steps to reproduce**

Launch power settings from menu, power applet or via cinnamon-settings power

**Expected behaviour**

No crash.

**Other information**

**Comment by smurphos** [comment]
Can be resolved by manually installing the following from the buster repos.

libupower-glib3_0.99.9-2
gir1.2-upowerglib-1.0_0.99.9-2

**Comment by smurphos** [comment]
upower_0.99.9-2 is also needed to allow the power applet to display the power state in its pop-up menu.

**Comment by mhd-malek** [comment]
> upower_0.99.9-2 is also needed to allow the power applet to display the power state in its pop-up menu.

The 3 packages already installed and same problem

**Comment by pioruns** [comment]
Confirming. Using real hardware, fresh install LMDE Cindy.

[cinnamon-settings power.txt](https://github.com/linuxmint/Cinnamon/files/2896892/cinnamon-settings.power.txt)
[neofetch.txt](https://github.com/linuxmint/Cinnamon/files/2896893/neofetch.txt)

Any word on progress here? I don't want to manually install packages from sid, any chance for these versions to land in Cindy?

**Comment by MS3FGX** [comment]
Confirming issue on Thinkpad T400, updated today and power applet says "Unknown" for current status.

Output of "cinnamon-settings power" identical to @pioruns

**Comment by pioruns** [comment]
" Assignees
No one assigned
Labels
None yet
Projects
None yet
Milestone
No milestone "

Any updates on this yet?

**Comment by smurphos** [comment]
@clefebvre - you were asking for diagnostics for someone with this issue on the Mint blog comments

**Comment by clefebvre** [comment]
Thanks @smurphos, I'll look into this.

**Comment by pioruns** [comment]
It's been a month, can anyone look into this?

**Comment by pioruns** [comment]
" Assignees
No one assigned
Labels
None yet
Projects
None yet
Milestone
No milestone "

Still no one assigned, no action taken...

**Comment by mtwebster** [comment]
This was fixed: https://github.com/linuxmint/cinnamon-settings-daemon/commit/4842c2d8013577ff323732f0a384815a4a150afa

I overlooked this report, sorry.  I'll see if an update can be pushed out.

**Comment by pioruns** [comment]
Wow, thank you! Let's wait and see it pushed to our systems now.

**Comment by watuLammini** [comment]
Sorry to bother, but got the same issue... Any development yet?

**Comment by Coren** [comment]
I confirm this workaround on LMDE 3.
Rebuilding and installing upower 0.99.10 package from Buster to LMDE 3 solve this issue.

**Comment by pioruns** [comment]
Any news, hello? Can this be fixed for everybody? :[
