### ISSUE TITLE
cinnamon froze when the screen was locked

### ISSUE THREAD

**Issue by asimsalam** [linuxmint/Cinnamon#8287]
```
 * Cinnamon version (cinnamon --version)
Cinnamon 4.0.9


 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=19.1
DISTRIB_CODENAME=tessa
DISTRIB_DESCRIPTION="Linux Mint 19.1 Tessa"
 * Graphics hardware *and* driver used
Nvidia GM107M[GeForce GTX 960M], DisplayLink 4.4
 * 32 or 64 bit
64 bit
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
 ```

**Issue**
The screen was locked for an hour and seemingly froze at some point. I had to restart cinnamon.
Stack trace:
https://termbin.com/l44w
crash.tar.gz is too large to be allowed to be attached here.
[xsession-errors.zip](https://github.com/linuxmint/Cinnamon/files/2752445/xsession-errors.zip)
[syslog.zip](https://github.com/linuxmint/Cinnamon/files/2752446/syslog.zip)

**Steps to reproduce**
sporadic

**Expected behaviour**
Should not freeze

**Other information**

**Comment by jaszhix** [comment]
Which version of the Nvidia driver are you on?

**Comment by asimsalam** [comment]
Sorry, I forgot put it in there, didn't I.
Here it is:

sudo nvidia-smi      
Sat Jan 12 13:12:15 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 390.77                 Driver Version: 390.77                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 960M    Off  | 00000000:02:00.0 Off |                  N/A |
| N/A   38C    P0    N/A /  N/A |    507MiB /  4046MiB |      6%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1286      G   /usr/lib/xorg/Xorg                           339MiB |
|    0      1751      G   cinnamon                                      94MiB |
|    0     12212      G   ...quest-channel-token=6355496306852678289    70MiB |
+-----------------------------------------------------------------------------+

**Comment by jaszhix** [comment]
Ok, can you upgrade to the 390.87 and see if it still occurs? That's out of date.

**Comment by asimsalam** [comment]
Its a bit strange. nvidia-smi reported 390.77 but the Driver manager shows 390.87 is in use. Not sure which one to trust?
Also, I added the PPA repo after which options for 396.54, 410.78 and 415.25 have been enabled.
Let me know if you would like to upgrade to one of those.
![screenshot from 2019-01-12 13-54-08](https://user-images.githubusercontent.com/24684098/51078900-ff309400-1671-11e9-92b5-36e77f217f3d.png)

**Comment by jaszhix** [comment]
nvidia-smi should be accurate, being a part of the driver, but you can find out definitively by running `glxinfo | grep OpenGL`.
 
I was curious about 390.xx because its what's available in the bionic repos, but its actually legacy now. 410.93 is the current long-lived driver, and 415.25 is the current short-lived. It's a shame we can't have users set up with the newest LTS driver without adding PPAs. I've been using 415.xx when testing the Nvidia driver with muffin.

**Comment by asimsalam** [comment]
sudo glxinfo | grep OpenGL | egrep version
OpenGL core profile version string: 4.6.0 NVIDIA 390.77
OpenGL core profile shading language version string: 4.60 NVIDIA
OpenGL version string: 4.6.0 NVIDIA 390.77
OpenGL shading language version string: 4.60 NVIDIA
OpenGL ES profile version string: OpenGL ES 3.2 NVIDIA 390.77
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20

Would you like me to move to/try 415.25 instead?

**Comment by jaszhix** [comment]
Sure, thanks.

**Comment by asimsalam** [comment]
Will do and update you.
