### ISSUE TITLE
Icons leave original positions after external monitor is attached and then removed

### ISSUE THREAD

**Issue by ghost** [linuxmint/cinnamon#8288]
```
 * Cinnamon version (cinnamon --version) 4.0.9
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 19.1
 * Graphics hardware *and* driver used: Intel UHD 620 (Kabylake) 3.0 Mesa 18.0.5.
 * 32 or 64 bit: 64
 * Attach /home/<username>/.xsession-errors
[xsesh.txt](https://github.com/linuxmint/Cinnamon/files/2752469/xsesh.txt)

, or /var/log/syslog
 ```

**Issue**

When I connect my laptop to an external monitor, and mirror displays, and then disconnect the external monitor, the icons do not return to where they were. When subsequently I press F5, the icons move to a closer approximation of how they were originally, but not a perfect one. Cue much rearranging by the user.

**Steps to reproduce**

1. Connect laptop to an external monitor (details below).
2. Mirror displays.
3. Disconnect the external monitor.
4. Press F5.

Screenshot of _my icons in their original state_:
![before scaled](https://user-images.githubusercontent.com/9998846/51077969-f22d9800-16a5-11e9-9793-6baa3d3d42e9.png)

Screenshot of the _icons after disconnecting the external monitor_:

![after scaled](https://user-images.githubusercontent.com/9998846/51077986-3b7de780-16a6-11e9-88b3-753ab0715477.png)

Screenshot of the icons after subsequently (i.e. post-disconnect) _pressing F5_:
![after refresh scaled](https://user-images.githubusercontent.com/9998846/51077995-6c5e1c80-16a6-11e9-93d3-19aee6ae65d6.png)

(Sorry about the green redactions.)

**Expected behaviour**

The icons should return to how they before the external monitor was attached.

**Other information**

* The resolution of my main - 14" - screen is 2560x1440. (Hence I have scaled down my screenshots.)
* I have Mint's HiDPI setting forced on.
* The resolution of the external monitor is 1920x1200 and it is 22".
* xserver-xorg-video-intel is _not_ installed.
* The external monitor was connected via a VGA cable combined with a VGA-to-HTMI adaptor. Soon I will be able to test with a DVI-to-HDMI cable.

**Comment by CottonEaster** [comment]
I tried attaching the same external monitor with a different type of cable, namely a DVI-to-HTMI adaptor. Result: the problem with icons still occured; and I had the following new problems. A window asking for a confirmation about change to display settings appeared, only, on the monitor that I had not been using (cf. #7917 and even #8279?); and at one point parts of the screen started flashing (though I am confident there is nothing wrong with any of my display hardware).

As things stand, it is hard to use Cinnamon with an external monitor (or at least with the external monitor that I have). I am sure that some people would be pleased were getting this stuff workingto be a priority for Mint 19.2.
