### ISSUE TITLE
[Feature request] - GWL - Right click option to duplicate/edit associated desktop file for pinned apps.

### ISSUE THREAD

**Issue by smurphos** [linuxmint/cinnamon#8289]
This has come up quite frequently over at the Mint forum. Folks find it a bit difficult to grasp why they can't right click and 'edit launcher' on a pinned app as they could with a panel launcher to change the command or modify the icon and the workarounds are a bit onerous and not intuitive to the average user.

I'm guessing it would be technically feasible to have this functionality for pinned apps with an edit function duplicating the associated desktop file into an appropriate location in ~/.cinnamon/configs or similar, linking the pinned app to the new .desktop file and using the existing edit launcher dialog to give the user access to this functionality. Something for 4.2 perhaps?

@jaszhix

**Comment by jaszhix** [comment]
GWL already has this functionality in a limited form, they just need to click "Create shortcut" on a window-backed app. It doesn't allow much customization, it will name it after the process. I was thinking about this a couple weeks ago and think a front-end for this would be a good idea. E.g., it could launch a small GTK thread that uses xapps icon chooser.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
