### ISSUE TITLE
All elements in qt apps suddenly become smaller

### ISSUE THREAD

**Issue by CottonEaster** [linuxmint/Cinnamon#8293]
```
 * Cinnamon version (cinnamon --version): Cinnamon 4.0.9
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 19.1
 * Graphics hardware *and* driver used: Intel UHD Graphics 620 3.0 Mesa
 * 32 or 64 bit: 64
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
[xsesh.txt](https://github.com/linuxmint/Cinnamon/files/2753490/xsesh.txt)

 ```

**Issue**

Sometimes and for no apparent reason, fonts and icons in qt apps - apps such as ksystemlog, virtualbox and angrysearch - become very small.

**Steps to reproduce**

Unknown, but having Hi-DPI enabled may be necessary. (My Hi-DPI is forced on in Mint's Settings - because while I deem my display Hi-DPI, Cinnamon does not.) Still, the last time that I tried simply to use qt apps under Hi-DPI, everything in them was too small, i.e. I had the same problem that I have now, but constantly. So I was forced to find some solution myself, and I found one in the form of Kvantum. But it seems now that this workaround is breaking periodically. One might say that the problem owes to Kvantum, and in a sense it does; but Kvantum is a workaround for the problem I have on Cinnamon. Now, that original problem may owe to qt5 itself rather than to Mint; but qt apps abound, and Cinnamon users - who have Hi-DPI - need to be able to use those apps.

**Expected behaviour**

Sizing should be consistent and reasonable.

**Other information**

#3663 may relate to my issue.

Restarting Cinnamon does not fix the problem. Rebooting does. Logging off and on again I have not yet tried.

**Comment by leigh123linux** [comment]
Report the issue against QT5.
