### ISSUE TITLE
[EDIT]"Show all windows": the position of a window is drawn outside its shape - found the steps to reproduce!!! 👍 

### ISSUE THREAD

**Issue by lalincedeldeserto** [linuxmint/cinnamon#8304]
* Cinnamon version: 4.0.9
 * Distribution - Mint 19.1
 * Graphics hardware *and* driver used: Intel Haswell-ULT Integrated Graphics 
 * 32 or 64 bit: 64 bit

Issue:

Everytime windows minimized in the system tray (after the 3 steps) are drawn outside their boxes launching the overview "Show all windows" callable with ctrl + alt + down shortcut. 

Steps to reproduce: 

1. Open any application with a GUI.
2. Press the maximize button for two times and reduce the window in the system tray.
3. Press Ctrl + Alt + Down to see the issue.

Frequency:
This happens every time I do all these operations. 

Graphics:
  Device-1: Intel Haswell-ULT Integrated Graphics vendor: Hewlett-Packard 
  driver: i915 v: kernel bus ID: 00:02.0 
  Display: x11 server: X.Org 1.19.6 driver: intel resolution: 1366x768~60Hz 
  OpenGL: renderer: Mesa DRI Intel Haswell Mobile v: 4.5 Mesa 18.0.5 
  direct render: Yes 

This is a screenshot. The problem, in this case, is that Firefox is outside the shape in which you press the cross to close its window. 

![schermata del 2019-01-10 19-00-54](https://user-images.githubusercontent.com/33136381/51258070-6075a180-19a9-11e9-9433-9178331e5d01.png)

schermata del 2019-01-16 16-28-12
![immagine](https://user-images.githubusercontent.com/33136381/51671143-8e21a280-1fc8-11e9-9229-11e9e8522e00.png)

I never had this bug in previous versions, so I think something happened with Cinnamon 4.0.9

**Comment by lalincedeldeserto** [comment]
Just now
![schermata del 2019-01-16 16-28-12](https://user-images.githubusercontent.com/33136381/51259230-032f1f80-19ac-11e9-8f26-9243d97ff6ba.png)
Never had this bug in previous versions

**Comment by Hilyxx** [comment]
Hello 

Me too...
This bug is recurrent and appear randomly 

Linux mint 19.1
cinnamon 4.0.9

![capture d ecran du 2019-01-31 14 49 30](https://user-images.githubusercontent.com/21991448/52059437-24763b00-256a-11e9-9b7c-ecb4e69a445b.png)

**Comment by Hilyxx** [comment]
I can to confirm this bug with these steps...

My graphic card is an Intel HD Graphics 4000 with xorg video intel 2.99.917 and xorg-core 1.19.6

**Comment by lalincedeldeserto** [comment]
> I can to confirm this bug with these steps...
> 
> My graphic card is an Intel HD Graphics 4000 with xorg video intel 2.99.917 and xorg-core 1.19.6

I think the problem is related to different Intel graphics cards. I tried the same steps on my brother's laptop too and appears the same issue. (In his laptop there's an intel graphic card, and in this moment I can't remember the name, but when he comes back home - now he's at school :joy: - I'll write it soon).

**Comment by lalincedeldeserto** [comment]
Graphics:
  Device-1: Intel Atom/Celeron/Pentium Processor x5-E8000/J3xxx/N3xxx 
  Integrated Graphics 
  vendor: Acer Incorporated ALI driver: i915 v: kernel bus ID: 00:02.0 
  Display: x11 server: X.Org 1.19.6 driver: modesetting unloaded: fbdev,vesa 
  resolution: 1366x768~60Hz 
  OpenGL: renderer: Mesa DRI Intel HD Graphics 405 (Braswell) 
  v: 4.5 Mesa 18.0.5 direct render: Yes

**Comment by lalincedeldeserto** [comment]
Graphics:
  Device-1: Intel Atom/Celeron/Pentium Processor x5-E8000/J3xxx/N3xxx 
  Integrated Graphics 
  vendor: Acer Incorporated ALI driver: i915 v: kernel bus ID: 00:02.0 
  Display: x11 server: X.Org 1.19.6 driver: modesetting unloaded: fbdev,vesa 
  resolution: 1366x768~60Hz 
  OpenGL: renderer: Mesa DRI Intel HD Graphics 405 (Braswell) 
  v: 4.5 Mesa 18.0.5 direct render: Yes

**Comment by Hilyxx** [comment]
Cinnamon 3.8 with same intel driver doesn't have this issue.... I've tested with a nonconventional method to replace cinnamon 4 wokspace.js by 3.8 version. NO issue... This bug is probably located in workspace.js

**Comment by lalincedeldeserto** [comment]
@Hilyxx great job, now I'd like to give a quick look to the code and see where are the differences. 

That's my idea:
1. Back up the file version 4.0
2. Replace each piece of code, one at a time and restore it if there isn't any change.
Then if the bug is visible, it's possible to start making some hypothesis.

**Comment by Hilyxx** [comment]
linux mint team has improved significantly workspace.js code. This one is based on new changes introduced by gnome 3.26.  

I can't to fix this bug myself, I'm not a developer. 
However this issue is very frustrating

**Comment by lalincedeldeserto** [comment]
> linux mint team has improved significantly workspace.js code. This one is based on new changes introduced by gnome 3.26.
> 
> I can't to fix this bug myself, I'm not a developer.
> However this issue is very frustrating

I can't solve this issue because I'm studying the basics of computer science and at the moment I haven't enough experience to solve this sort of problems. The team worked a lot to improve workspace.js and I think that they will handle that file again at the right moment.

**Comment by lalincedeldeserto** [comment]
Hi @Hilyxx, a friend suggested to me to switch "Cinnamon" into "Cinnamon (Software Rendering)" modality.
The problem doesn't appear!! So another possible cause might be something related to the hardware. Because we have Intel Graphics (and it's possible we have the same or similar ISA →Istruction Set Architecture). 
I asked into the forum if someone had the same problem as me. No one seemed to have.
So at the moment, I found a new possible reason: the GPU. I don't know if the problem is the kernel now. Or something else. Before Cinnamon 4.0.9 with version 3.8, we didn't have problems with "show all windows" modality.
We can only give observations and hope :innocent:

**Comment by jaszhix** [comment]
This might be fixed by https://github.com/linuxmint/muffin/pull/405. I haven't reproduced this myself on Nvidia or Intel.

If anyone feels comfortable testing a build from that PR, you can get it here.

https://github.com/linuxmint/muffin/files/2771929/muffin-4.0.6-405-8a8227658bda7a582e0e2e33beaaac900653fce6.tar.gz

**Comment by Hilyxx** [comment]
@jaszhix tested with your build..this bug isn't resolved...

![capture d ecran du 2019-02-12 22 25 50](https://user-images.githubusercontent.com/21991448/52668974-45993d00-2f15-11e9-92ac-240c590b9f0f.png)

**Comment by Hilyxx** [comment]
This is a link for a video showing this issue

[https://youtu.be/wlD63DuaVk0](url)

**Comment by lalincedeldeserto** [comment]
@jaszhix thank you, now I try the build on my machine. :smiley: 
@Hilyxx I've just given you a like on Youtube :+1: 
 Are you using Pantheon? Or have you tweaked Cinnamon?

**Comment by lalincedeldeserto** [comment]
@jaszhix I tried installing in a usb live system but it's too difficult for me because there are some variables to set and in the log file gcc doesn't recognize -V flag
[configure_command.txt](https://github.com/linuxmint/Cinnamon/files/2859834/configure_command.txt)
[config.log](https://github.com/linuxmint/Cinnamon/files/2859835/config.log)
I want to retry later on a physical installed system, because I don't know what command can solve the problem.
