### ISSUE TITLE
Default settings idea: Dragging window to the top-edge should maximize, tiling sound-effects should be disabled #215 

### ISSUE THREAD

**Issue by DougBeney** [linuxmint/cinnamon#8307]
Hello,
I am not sure if this is the best location to discuss default settings in Linux Mint / the Cinnamon Desktop.

I believe that dragging a window to the top of the screen and having the window maximize is what most users expect - I believe that is the default in Windows. Perhaps then "Maximize, instead of tile, when dragging a window to the top edge" should be enabled by default.

Also, I believe that the sound-effects for window tiling don't serve a purpose.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.

**Comment by BoQsc** [comment]
Still not fixed or have been dones anything about this very important issue. @icarter09
