### ISSUE TITLE
[Feature request] Lock screen as music full screen mode

### ISSUE THREAD

**Issue by gagaringambit** [linuxmint/Cinnamon#8308]
Having recently switched to Cinnamon from KDE, after Mint dropped KDE support, one of the very few things I miss from KDE is a full screen music player mode, which I was able to setup through widgets. However, I see that the functionality is actually there in the Cinnamon lock screen, but it's just a bit sort of getting there.

Therefore, I suggest a few minor modifications to the lock screen, such as:
- Give the option to make artist, album, song title and media controls constantly visible
- Make artist, album, and song information font and position customisable
- Make album art position and size customisable

And with these rather simple modifications, the lock screen can be turned into an alternative music control/full screen mode :)

**Comment by leigh123linux** [comment]
File the request against cinnamon-screensaver instead.
