### ISSUE TITLE
A way to switch between Modern and Traditional layout through System Settings

### ISSUE THREAD

**Issue by nick-s-b** [linuxmint/cinnamon#8310]
```
 * Cinnamon version (cinnamon --version)
Cinnamon 4.0.9
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
Arch
 * Graphics hardware *and* driver used
Nvidia
 * 32 or 64 bit
64-bit
 ```

**Issue**
Currently, there is no way to switch between Modern and Traditional layouts on non-LinuxMint distros since they don't ship `mintwelcome`. I just wanted to try the new layout but wasn't able to find an easy way to do it. Unless this is a LM-exclusive feature, I think the most natural way to switch between the two should be a preference inside of System Settings. Thanks!

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
