### ISSUE TITLE
Open in Terminal sometimes not working

### ISSUE THREAD

**Issue by tkivisik** [linuxmint/Cinnamon#8313]
```
System:
  Kernel: 4.18.0-13-generic x86_64 bits: 64 compiler: gcc 
  v: 7.3.0 Desktop: Cinnamon 4.0.9 Distro: Linux Mint 19.1 Tessa 
  base: Ubuntu 18.04 bionic 
Machine:
  Type: Laptop System: LENOVO product: 20ARA15K00 v: ThinkPad T440s 
  serial: <filter> 
  Mobo: LENOVO model: 20ARA15K00 v: 0B98401 PRO serial: <filter> 
  UEFI: LENOVO v: GJET99WW (2.49 ) date: 06/05/2018 
CPU:
  Topology: Dual Core model: Intel Core i5-4200U bits: 64 type: MT MCP 
  arch: Haswell rev: 1 L2 cache: 3072 KiB 
  flags: lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx bogomips: 18357 
  Speed: 798 MHz min/max: 800/2600 MHz Core speeds (MHz): 1: 798 2: 798 
  3: 798 4: 798 
Graphics:
  Device-1: Intel Haswell-ULT Integrated Graphics vendor: Lenovo 
  driver: i915 v: kernel bus ID: 00:02.0 
  Display: x11 server: X.Org 1.19.6 driver: modesetting unloaded: fbdev,vesa 
  resolution: 1920x1080~60Hz 
  OpenGL: renderer: Mesa DRI Intel Haswell Mobile v: 4.5 Mesa 18.0.5 
  direct render: Yes 
Info:
  Init: systemd runlevel: 5 Compilers: gcc: 7.3.0 Shell: bash v: 4.4.19 
  inxi: 3.0.27
 ```

`tail -f .xsession-errors` while I was trying to open a terminal via the mouse dropdown menu.
> (nm-applet:2020): Gtk-CRITICAL **: 21:44:40.064: gtk_widget_destroy: assertion 'GTK_IS_WIDGET (widget)' failed 
> (nm-applet:2020): Gtk-WARNING **: 21:44:40.069: Can't set a parent on widget which has a parent
> (csd-power:1863): GLib-GIO-CRITICAL **: 21:44:55.241: g_dbus_proxy_get_object_path: assertion 'G_IS_DBUS_PROXY (proxy)' failed

**Issue**
Terminal does not open when I click 'Open in Terminal' from a mouse drop down menu in a folder window.

**Steps to reproduce**
Not sure, sorry.

**Expected behaviour**
Terminal window opens.

**Other information**
CTRL-ALT-T opens the terminal. Terminal is also opened when clicking 'Open as Root' from a mouse drop down menu. Creating a new folder from that menu also works.

When I closed all the terminal windows I had open (3 were open). Then opening using 'Open as Root' started to work again, and continued to work to even open a second, third and fourth terminal.

**Comment by leigh123linux** [comment]
open-terminal is part of nemo.

https://github.com/linuxmint/nemo/issues
