### ISSUE TITLE
Select monitor for each workspace

### ISSUE THREAD

**Issue by brunoribeiro94** [linuxmint/cinnamon#8319]
**Issue**

I have two monitor 17", I'd like know if is possible make this settings.

Ex:
Monitor 1 | Show WORKSPACE 1 Monitor 2 | Show WORKSPACE 2

I tryed in display settings, I not found this option that I desire.

Maybe some software can do this ?

My OS: Linux Mint 18.1 Cinnamon 64-bit

**Comment by pyroxar** [comment]
Good idea.

**Comment by pyroxar** [comment]
Hi @collinss 
You work now about workspace? Did you see it? What you think?

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
