### ISSUE TITLE
Have option to view as thumbnails in File Open dialogue

### ISSUE THREAD

**Issue by EvoEvz** [linuxmint/cinnamon#8320]
* Distribution - Mint 19.1
 * 64 bit

No option to view as thumbnails in the File Open dialogue

I believe this effects all users

**Comment by pyroxar** [comment]
You mean view of this:
![obraz](https://user-images.githubusercontent.com/23406555/52011356-04963700-24d8-11e9-8f96-93ccaf2c9290.png)
and you want can have option to display icons in grid?

**Comment by EvoEvz** [comment]
No I mean this and we want to have the option to show files in thumbnail and/or icon, list compact etc as you can in Nemo

![image](https://user-images.githubusercontent.com/34127249/55386771-f027f680-557b-11e9-8184-4957887e1ffa.png)

**Comment by leigh123linux** [comment]
The File Open dialogue is provided by GTK itself, it isn't something we can fix.
