### ISSUE TITLE
Minimised window not getting back up if animations are 0 ms

### ISSUE THREAD

**Issue by Wotac** [linuxmint/Cinnamon#8322]
```
 * Cinnamon version 3.8.8
 * Distribution - Debian Unstable
 * Graphics hardware *and* driver used - Mesa DRI Intel(R) Ivybridge Mobile
 * 32 or 64 bit - 64 bit
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog - no errors
 ```

**Issue**
When I set the animations to 0 ms in Effects settings --> Customise, it stops animating the actions but they also stop working correctly. I noticed that when I minimise a window and then try to get it back it won't show even though it's the active window now. I have Plank dock installed so I have tried clicking an icon to bring it back or Alt+Tab, the window is invisible even though it's the top window. I even bound a key combo for raising windows but it doesn't help here, neither does Always on top keybind. The way to get it back is to start tiling it like with Super + side arrows. Then it shows up again. This doesn't sound like it would be intentional. Raising animation speed to 50 ms fixes this. Also Mapping windows effect produces the newly opened terminal window half-outside the screen area if animations are 0 ms. These effects need some animation time or they stop acting correctly. They don't just do their job instantly.

**Steps to reproduce**
Lower the Effects --> Customise --> Minimising windows to 0 ms, then minimise a window. It won't come back up again. You have to either close it and open again or tile it to get it showing.

**Expected behaviour**
Being able to see the window again when it's selected instead of being hidden forever.

**Other information**
I haven't reported issues before so I apologize if there's not enough information. I'm using a Lenovo Thinkpad X230 with integrated Intel graphics. I tried to search for an existing issue but couldn't find it, but it's possible I didn't think of the right search word. If this behaviour is not unintentional then everything is fine, at least now I know how to fix them.

**Comment by jaszhix** [comment]
I added a fix for this in #8290 that will skip the effect if the time is 0ms. In the meantime setting the delay to 1ms should give you the same effect without triggering the bug.
