### ISSUE TITLE
PgUp PgDn not working intermittently

### ISSUE THREAD

**Issue by kaymio** [linuxmint/cinnamon#8327]
```
 * Cinnamon version 4.0.9
 * Distribution - Arch
 * Graphics hardware *and* driver used RX480 with mesa 18.3.1
 * 64 bit
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
 ``` neither available on my system

**Issue**
PgUp and PgDn keys (mostly) don't work for scrolling in browsers or in the terminal emulator output.
 E.g. the output of 'less' or journalctl can't be scrolled with PgX, though Shift+PgX works for going up
and down earlier outputs. When logged in via another TTY (without cinnamon or X), the output of
journalctl can be scrolled with with those keys, no problem. When in a terminal emulator under cinnamon, 
scrolling (mostly) doesn't work. I say mostly, because sometimes, for no apparent reason it works, for a
while. It also stops working for no apparent reason, without any reboot or logout in between. Though 
pressing these keys does something under Cinnamon. E.g. when pressing those keys while writing this 
text, the blue border of this text box disappears while one of those keys is held down. Home and End keys 
work as they should, jumping to start or end of the file/site/text. Line by line with the cursor keys works also.

This problem came about at the end of 2018, but was present before the step to version 4.

**Steps to reproduce**
no idea


**Expected behaviour**
Being able to scroll pages in browser and terminal emulator with PgUp and PgDn, uninterruptedly.


**Other information**

**Comment by progulin** [comment]
Hi,

I have exactly the same problem ... 

PgUp/Dn stop to work unexpectedly in Cinnamon session.
Logout/Login fix the problem. But it happens several times a day.

Virtual keyboard does not react on PgUp/Dn, but cursor of Terminal window blink on each pressing PgUp/Dn.

PgUp/Dn on NumPad stll works fine.
PgUp/Dn in new TTY (Ctrl+Alt+F1) still works fine.

Hot change keyboard (USB, PS/2) does not fix problem, i.e. it's software problem.

System info uploaded here: https://gist.github.com/progulin/a1c65c114638b6462d7389346f220871

Regards,
Pavel.

**Comment by wilhelmy** [comment]
I have the same problem on OpenSuSE Tumbleweed (which is rolling release just like Arch) / X11 / notion. Seems to be an X11 problem, since it affects all software. Keypresses on PgUp/PgDn don't show up as "KeyPress/KeyRelease" pair in xev like all other keys, only as "KeymapNotify".

**Comment by kaymio** [comment]
I posted a bug report on Gitlab:

[Xorg Gitlab](https://gitlab.freedesktop.org/xorg/lib/libxkbfile/issues/4)

Maybe you (@progulin @wilhelmy ) could add your specs to the thread.

**Comment by progulin** [comment]
Hi!
"Wire Quit" helps me. :)
https://github.com/wireapp/wire-desktop/issues/2056

**Comment by wilhelmy** [comment]
Aha! Messing around with the wire window seems to help, indeed.

**Comment by icarter09** [comment]
@kaymio are you still experiencing this issue?

**Comment by wilhelmy** [comment]
I just tested and Wire seem to have fixed their bug.

**Comment by kaymio** [comment]
No, I don't do any more.
