### ISSUE TITLE
Recent documents applet ::: selectively remove items from the list [Feature Request]

### ISSUE THREAD

**Issue by Sadi58** [linuxmint/cinnamon#8330]
```
 * Cinnamon 4.0.9
 * Mint 19.1
 ```
I think it could be very useful if the "Recent documents" applet dropdown list included checkboxes to select and remove items from the list - for privacy, getting rid of unresponsive ones that no longer exist, etc. ( _if its cost is justifiable of course_ ; -)

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
