### ISSUE TITLE
Segfault on image of width 32767

### ISSUE THREAD

**Issue by sguillia** [linuxmint/Cinnamon#8334]
**Issue**

Cinnamon segfaults when opening a valid image of size 32767 x 559
Reproducibility 100%

**Steps to reproduce**

1. Download the image
2. Open it
3. Maximize it

**WARNING**: Save your data before...

**Expected behaviour**

Image opens and I can look at it

**Actual behaviour**

Cinnamon segfaults, session logs out.

**Other information**

Image viewer : default one (`eog`)<br>
I didn't made such an image on purpose. This crash made me lose all my data, including private tabs, unsaved gedit notes, unsaved libreoffice documents, ... For once it is reproducible but I probably won't use cinnamon anymore.

Here is the actual image, generated by graphviz:
![callgraph](https://user-images.githubusercontent.com/15984272/51628949-acdf5500-1f46-11e9-80cf-067fa1257cb0.png)

I cannot join `.xsession-errors` because it is 87M ...

I will provide more information if you give me the command to retrieve them

```
$ file ./callgraph.png 
./callgraph.png: PNG image data, 32767 x 559, 8-bit/color RGB, non-interlaced

$ cinnamon --version
Cinnamon 3.2.7

$ uname -v
#1 SMP Debian 4.9.110-3+deb9u6 (2018-10-08)

$ uname -m  
x86_64

$ ls -hl ~/.xsession-errors
-rw------- 1 sigui sigui 87M Jan 23 19:30 /home/sigui/.xsession-errors

$ tail -16 ~/.xsession-errors
Using method `randr'.
1
Cjs-Message: JS LOG: About to start Cinnamon
St-Message: cogl npot texture sizes SUPPORTED
Cjs-Message: JS LOG: Cinnamon started at Wed Jan 23 2019 19:22:44 GMT+0100 (CET)
Cjs-Message: JS LOG: network applet: Cannot find connection for active (or connection cannot be read)
openGL version 4.5 detected (GL3 Cogl Driver)
MetaSyncRing disabled: couldn't find required GL extensions, or the minimum safe openGL version was not met
Cjs-Message: JS LOG: Invalid network device type, is 14
Cjs-Message: JS LOG: network applet: Found connection for active

(nemo:449): Gtk-WARNING **: Allocating size to NemoWindowPane 0x55587365d300 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
Cjs-Message: JS LOG: Removing an access point that was never added
Cjs-Message: JS LOG: Removing an access point that was never added
Cjs-Message: JS LOG: Removing an access point that was never added
Cjs-Message: JS LOG: Removing an access point that was never added

$ sudo lshw -C display
  *-display                 
       description: VGA compatible controller
       product: HD Graphics 520
       vendor: Intel Corporation
       physical id: 2
       bus info: pci@0000:00:02.0
       version: 07
       width: 64 bits
       clock: 33MHz
       capabilities: pciexpress msi pm vga_controller bus_master cap_list rom
       configuration: driver=i915 latency=0
       resources: irq:130 memory:e0000000-e0ffffff memory:d0000000-dfffffff ioport:f000(size=64) memory:c0000-dffff

$ sudo dmesg
[956359.486462] cinnamon-launch[32127]: segfault at 0 ip 00007f6b554b0e19 sp 00007fffb72604a0 error 4 in libgtk-3.so.0.2200.11[7f6b551ce000+700000]
[956418.838945] cinnamon-launch[32413]: segfault at 0 ip 00007fbf56588e19 sp 00007ffec9808610 error 4 in libgtk-3.so.0.2200.11[7fbf562a6000+700000]
[956467.612070] cinnamon-launch[32750]: segfault at 0 ip 00007fece0016e19 sp 00007ffd72cf3ce0 error 4 in libgtk-3.so.0.2200.11[7fecdfd34000+700000]
[...]
```

**Comment by jaszhix** [comment]
Which distribution, graphics driver? Please look at the issue template.

**Comment by thorsummoner** [comment]
this thread came up in a google search for `"cinnamon-launch" "segfault at 0"`, I'm trying to identify why my desktop is crashing to lightdm; these dmesg lines likely correlate with my crashes, hope thes log entries help

```
[ 9650.801022] cinnamon-launch[10074]: segfault at 0 ip 00007f59eb0ebfd9 sp 00007ffdb98c2290 error 4 in libgtk-3.so.0.2200.30[7f59eae08000+6f1000]
[ 9650.801029] Code: 5c 41 5d c3 0f 1f 00 66 2e 0f 1f 84 00 00 00 00 00 8b 35 b2 20 62 00 31 d2 31 c0 e9 b1 1b da ff 90 53 48 89 fb e8 47 fe ff ff <48> 8b 3b 48 89 c6 e8 6c 0b da ff 48 8b 40 18 48 85 c0 74 06 48 89 
[10604.158890] cinnamon-launch[12166]: segfault at 0 ip 00007fd678466fd9 sp 00007ffde623aaf0 error 4 in libgtk-3.so.0.2200.30[7fd678183000+6f1000]
[10604.158896] Code: 5c 41 5d c3 0f 1f 00 66 2e 0f 1f 84 00 00 00 00 00 8b 35 b2 20 62 00 31 d2 31 c0 e9 b1 1b da ff 90 53 48 89 fb e8 47 fe ff ff <48> 8b 3b 48 89 c6 e8 6c 0b da ff 48 8b 40 18 48 85 c0 74 06 48 89 
```

**Comment by jaszhix** [comment]
There's not enough info here for any action to be taken. If you're using Mint, check `mintreport`. Especially since this segfault is occurring in GTK we need to know what distribution you're using. Feel free to re-open when you can provide all required info.

**Comment by sguillia** [comment]
Thank you, I will upgrade then.

**Comment by sguillia** [comment]
What version is not supported? Debian Stretch, or Cinnamon 3.2?

Can I have the latest version of Cinnamon on Debian Stretch, without switching to LMDE3?

Is there a list of the versions of Cinnamon that are still supported, with the end date of their support?

I just want to not have this issue anymore

Thanks a lot

**Comment by leigh123linux** [comment]
@sguillia  We don't support either.

> What version is not supported? Debian Stretch, or Cinnamon 3.2?

Any version older than what's included in lmde or mint latest release is unlikely to receive any support so could be considered EOL. 

> Is there a list of the versions of Cinnamon that are still supported, with the end date of their support?
