### ISSUE TITLE
Recover from a segfault

### ISSUE THREAD

**Issue by sguillia** [linuxmint/cinnamon#8335]
This is a feature request.

Is there any way that Cinnamon could recover from a segfault?

Like when I restart cinnamon with `Alt+F2` then `r`, it restarts without killing all user processes (firefox, gedit, ...).

Or like any segfault: it is not supposed to bring the whole system down.

This would highly increase Cinnamon reliability.

**Comment by jaszhix** [comment]
As far as I'm aware, at least on the debian based distributions I've used, it should fallback to a Mate session. If this isn't happening you might be missing some dependencies.

**Comment by sguillia** [comment]
Hi @jaszhix, how could I know what dependencies could be missing?

**Comment by jaszhix** [comment]
I don't know anything about [your environment](https://github.com/linuxmint/Cinnamon/blob/master/.github/ISSUE_TEMPLATE.md). You should have mate-panel or gnome-panel installed.

If it is occurring still, it would be a good idea to try to capture a gdb trace during the segfault.

**Comment by sguillia** [comment]
At the time of posting I took the assumption that Cinnamon has no fallback in case of segfault
  - no matter what caused it, may it be null pointer dereference like in #8334 or a kill-induced signal)
  - no matter what environment

So I will post environment asap.

Would it be interesting to have a gdb trace of a segfault induced by the `kill` command? 
If so, do you have any useful link about how to capture a gdb trace of cinnamon since it's not a 'lambda' program?

I made this issue to improve Cinnamon but I'm no expert at debugging desktop environments

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
