### ISSUE TITLE
Nvidia Driver 390 does not work in 1080 with LM 19.1

### ISSUE THREAD

**Issue by windyweather** [linuxmint/cinnamon#8338]
```
 * Cinnamon version (cinnamon --version)
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 19.1
 * Graphics hardware *and* driver used GTX 1050 390
 * 32 or 64 bit 64
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog 
Live DVD not possible
 ```

**Issue**
 Using Core i5-4570 with GTX 1050 connected to a Vizio 4K TV for display through Denon  receiver.
Works fine with LM 18.3 using nviida-384 driver. I use it in 1080 HD however since 4K support is not really there. Can't make text / panel big enough to read even on 65" TV. So fine. Works great.

Just tried to install LM 19 using Live Stick - OK... What do you call it? Ha Ha Cinnamon Stick by the way. Ha Ha again.

**Steps to reproduce**
Use LM 19.1 Live Stick to attempt to install on above hardware.
Observe that it immediately comes up in 4K, but text is too small to read and adjustments are not sufficient to make it large enough to be useful.

Attempt to set 1080. Notice that the text is blurred. See attached pictures.
Use driver manager to use Nvidia 390 driver. No change. No ability to reboot of course since this is a Livestick.

**Expected behaviour**
4K and 1080 should work with this HW / SW. 
Text should be clear in 1080. - It was clear with LM 18.3 - worked fine with Nvidia 384 driver.
It should be possible to make text and panel large enough to function in 4K. But 4K is useless on 65" TV from across the room without a telescope.
![lm19_1_1080_fail_20190123_121730](https://user-images.githubusercontent.com/4505159/51700042-0d13dc80-1fc3-11e9-9df1-059cafb7f92c.jpg)

**Other information**

**Comment by 0lzi** [comment]
Don't the drivers require a reboot for it to work as intended?

**Comment by windyweather** [comment]
Well, as I said. Can't "Reboot" the live DVD [aka Stick] now can I? And not going to commit to the install unless I see the graphics working. Have we updated the driver in the Live DVD so that I should try it again? 4K not a priority for Linux Mint?

**Comment by leigh123linux** [comment]
Without a reboot the nouveau module loaded at bootup will block nvidia module from loading.

**Comment by brownsr** [comment]
can you set to hidpi (settings, general) on install ?

**Comment by windyweather** [comment]
brownsr? What does hidpi mean? How do I collect it?

leigh123linux - Uh. Is there something I don't understand? How could I reboot the LIVE STICK and expect the new driver to be there? Doesn't the LIVE STICK use a RAM disk and when you reboot you get the original data from the STICK again?

Well close this is you want to, but I guess that means that you folks don't care about 4K support on NVIDIA, or maybe other graphics hardware?
If there is some other information that you would like me to gather I'd be happy to try. But I need to understand what you want. I have no idea what hidpi is or how to get it.

Thanks, ww

**Comment by leigh123linux** [comment]
@windyweather The only issue you have is your refusal to do a proper install.

**Comment by brownsr** [comment]
@windyweather 4k works fine on mint 19.1 and with that nvidia driver version 390 you mention. I have used it that way myself. Your specific hardware I don't think any of us can comment on. Hidpi is a mode that scales up the user desktop so that it will look like a 1080p screen on a 4k monitor. It uses the extra resolution to add detail to the icons and fonts, adding clarity without making everything look smaller. That sounds like what you may want. Open up the settings, choose general, then choose hidpi. As others have already commented, you may need to complete your install before being able to reboot into different drivers.

**Comment by windyweather** [comment]
I don't know what it's called, but like I said, I'm running 18.3 in 1080 mode now. ANd both 1080 and 4K modes work fine with 18.3. Just to remind us. ANd they worked fine on the LIVE DVD - not stick back in the day.

Well, to do a full install of 19.1, I''d have to change my hardware with a Sacrificial System Drive to do a full install. If 19.1 is not going to work, then I don't want to have to reinstall the current 18.3 which is working fine. I assumed that is why we have a LIVE STICK. To allow me to try the system and confirm it works before the FULL INSTALL.
I'll just hang with 18.3 if we aren't going to fix the LIVE STICK to properly support Nvidia with 4K. But who knows, this ticket has taken so long that it's probably been updated and working now for all I know.

Have a great day. Someday I'll try it again.
