### ISSUE TITLE
ALT+Escape messes up screen

### ISSUE THREAD

**Issue by autarkper** [linuxmint/Cinnamon#834]
By accident I discovered the ALT+Escape meta keybinding, which could work as an alternative to the ALT+Tab task switcher, as it outlines and brings the next window to the front. However, after circling through the workspace windows a few rounds, the screen becomes badly messed up.
Screen shot: http://imagebin.org/217859

Apart from that, I find the window-frame outline feature useful, and would like to see it in the ALT+Tab task switcher. Where do I find the code for that?

**Update**: I initially wrote: "At one occasion it also seemed to pick up a window from another workspace." I no longer think that is what happened; it is rather an effect of the window outlines being drawn in an offset position.

**Comment by dalcde** [comment]
Removed in git master
