### ISSUE TITLE
Group window list applications right click Preferences > About, does not show the application's about.

### ISSUE THREAD

**Issue by wyattbiker** [linuxmint/Cinnamon#8350]
```
 * Cinnamon version (4.0.8)
 * Distribution - (Mint19.1,)
 * Graphics hardware *and* driver used 
 * 64 bit
 
**Issue**
Added **Grouped Window List** applet to Panels. When applications are either pinned or opened, and one right clicks for context menu over an application, the Preferences are about the **Grouped Window List** applet and not about the application (E.g. Chrome,  Files, etc) on the panel.

**Expected behaviour**
Context menu Preferences of an application docked on the Panel should be about the Application.

**Comment by jaszhix** [comment]
This is intended behavior, preferences always refer to the applet's own preferences. If you right click the other applets, this is the same case, so special casing this for GWL would be inconsistent. It's not possible to do this in any case because we have no knowledge of the application's API.

**Comment by wyattbiker** [comment]
I understand what you are saying but I think it would be nice if you provided at least the properties ability right there on the Context of the icon. Basically it would be whatever Nemo does with .desktop. It would be a convenience option instead of hunting around for where the app is executed from. Also I hope Menu developers add same feature. Thanks!

![screenshot from 2019-01-30 11-12-26](https://user-images.githubusercontent.com/930478/51995254-5ca14f00-2480-11e9-8b37-28f4264d7b08.png)
