### ISSUE TITLE
power@cinnamon.org Bug of the icon when battery have critically low level.

### ISSUE THREAD

**Issue by pyroxar** [linuxmint/cinnamon#8353]
```
 * Cinnamon version (cinnamon --version) Cinnamon 4.0.9
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Linux Mint 19.1
 ```

**Issue**
When battery have critically low level, on one moment applet show wrong battery icon after attach power cable.

**Steps to reproduce**
attach power cable when battery have critically low level.

**Expected behaviour**
Icon of the battery should be immediately good.

**Other information**
![bateria](https://user-images.githubusercontent.com/23406555/52011048-44a8ea00-24d7-11e9-9bf4-ceabec5a0ef6.gif)

**Comment by icarter09** [comment]
Linux Mint 19.2
Cinnamon 4.2.4

I'm unable to reproduce this issue. Steps performed:
 1. Let battery reach critically low level.
 2. Verified that the critically low level icon was displaying.
 3. Connected power supply 
 4. Icon then changed to the critically low level battery charging.

**Comment by pyroxar** [comment]
This bug doesn't exist again.
