### ISSUE TITLE
[Feature Request] dragging text and files fro ma window to another minimized window by hovering over the panel

### ISSUE THREAD

**Issue by logxseven** [linuxmint/cinnamon#8355]
```
 * Cinnamon version 3.8.9
 * Distribution - Mint 19
 * Graphics hardware *and* driver used
 * 64 bit
 ```
it would be nice to see an option to drag things (text, files ... etc) from a window to another by accessing the second window by hovering (while dragging) over that window's panel item.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
