### ISSUE TITLE
[Feature request] Make "Play backgrounds as slideshow" remembrable after version upgrade of Cinnamon

### ISSUE THREAD

**Issue by Nokia808** [linuxmint/cinnamon#8356]
```
 * Cinnamon version (4.0.8)
 * Distribution - (Fedora 28 X64 Cinnamon edition)
 * Graphics hardware *and* driver used: Intel Corporation HD Graphics 5500 (+ Radeon R7 M265 2GB as dedicated VGA)
 * 64 bit
 ```

I'm using multiple images as backgrounds for my PC DE. I use "Play backgrounds as slideshow" option. But when I receive new version of Cinnamon, this option will switched off without my intention & I have to re-enable it every time I received new Cinnamon version.

Can you make the setting of this option saved as it without change across new version upgrade of Cinnamon DE ?

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
