### ISSUE TITLE
[Feature request] Make Cinnamon remember & start from last slide reached in previous session

### ISSUE THREAD

**Issue by Nokia808** [linuxmint/cinnamon#8357]
```
 * Cinnamon version (4.0.8)
 * Distribution - (Fedora 28 X64 Cinnamon edition.)
 * Graphics hardware *and* driver used: Intel Corporation HD Graphics 5500 (+ Radeon R7 M265 2GB)
 * 64 bit
 ```

Dear, I'm using multiple images as backgrounds for my PC using "Play backgrounds as slide-show" option. The number of images is very huge. It is 636 ! I got them from:

https://forums.fedoraforum.org/showthread.php?314913-Gimp-Package-For-ALL

Indeed they are very very nice ! But unfortuantly I can not enjoy them perfectly using option "Play backgrounds as slide show" due to fact that when I power off my PC then relaunched it again, it will start from 1st image while in the previous session it reached, say as ex., to 50th image.

It will be very useful if you can make Cinnamon remember last image reached in slide show in previous session so as to start from it in next session.

Best.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
