### ISSUE TITLE
FR: Better Wallpaper Slideshows on multi monitor set-ups

### ISSUE THREAD

**Issue by acornforth** [linuxmint/cinnamon#8359]
```
 * Cinnamon version 4.0.9
 * Distribution - Mint 19.1
 ```
Actually this is more like a suite of suggestions to improve the wallpaper slideshow experience with multiple monitors.
### some facts:
1 Some wallpaper images are designed to span multiple monitors (with same dimensions, eg 3840x1200) others are not.
2 Some wallpapers come as a pair of images for display on left & right monitors
3 Everything above should also be considered with respect to 3 or 4 monitor set-ups...
4 some images work best with scale, others with stretch etc
5 not everyone using multi-monitor set-ups has identical monitors, resolution, or even the same orientation.
6 there is currently no easy way to select multiple image folders to be including in the slide show. or a subset of images within the default artwork folders to include or exclude.

### I propose:
each wallpaper image should have its own settings (config file, or sqlite, or something....):
- which scale/stretch mode to use
- whether to span the image over multiple monitors,
- (un)suitable for use on portrait orientation
- whether there is a 'partner' image to prefer on the other monitor (and which monitor this image prefers to be on)
- whether to be included in any current slideshow.

Wallpaper picker should allow selection of multiple folders to include in the slide show, this in combination with per-image exclusion flag, means i can have all the beautiful mint artwork i like from all versions included in my slideshow (without creating a new folder full of sym-links), and exclude the images i prefer not to include. (without removing them from their default locations).

### also
this is just a nice to have....
what about an option to have each monitor's slideshow independent? for those with varying sizes and orientations of monitor, theres no reason the timings or image selections have to be the same.... even better if there was a way to mix and match between this behaviour , and that made possible by the above suggestions!

**Comment by JosephMcc** [comment]
Thanks for the detailed feature request. However, this goes above and beyond something we would want to implement. Not only would it be a lot of work to do on our side, it would also be a lot of work for a user to actually use. Too much for the very small numbers of users that would make use of it.
