### ISSUE TITLE
Network Settings windows size

### ISSUE THREAD

**Issue by 0lzi** [linuxmint/cinnamon#8360]
```
 * Cinnamon version (Cinnamon 4.0.9)
 * Distribution - (Mint 19.1 )
 * Graphics hardware Nvidia GTX 960 driver used 4.15.27
 * 64 bit

[xsession-errors.txt](https://github.com/linuxmint/Cinnamon/files/2821162/xsession-errors.txt)
**Issue**
When selecting Network settings from panel

[image](https://user-images.githubusercontent.com/4409144/52117317-58ee0380-260b-11e9-8cbb-e1f4d2481dbd.png)

The network settings window is not sized properly to fit all the information as show below.

[image](https://user-images.githubusercontent.com/4409144/52117370-74590e80-260b-11e9-9ed5-764e4885609c.png)

Also after resizing and closing the same window opens rather than the previously resized window.


**Steps to reproduce**
1. Click network icon from panel
2. Click network settings


**Expected behaviour**
1. Click network icon from panel
2. Click network setting
3. Network settings windows displays all the information without needing to resize.
4. If the window is resized upon closing and re-opening Network settings the same size window is displayed from previous state


**Other information**
not sure if you would tag as bug or feature request

**Comment by pyroxar** [comment]
I confirm this bug:
![obraz](https://user-images.githubusercontent.com/23406555/52138512-a723f680-264d-11e9-9976-70b197848f4e.png)

**Comment by morteryler** [comment]
No one will fix this problem, so here's a solution for you:
Open /usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py
Replace:
`self.window.resize(WIN_WIDTH, use_height)`
To:
`self.window.resize(WIN_WIDTH, 500)`
Fixes on any resolution

**Comment by smurphos** [comment]
@morteryler  - that's a fudge rather than a fix - and causes other settings module whose natural height is 
 not 500px to open at a fixed height.

**Comment by 0lzi** [comment]
> No one will fix this problem, so here's a solution for you:

Im no programmer but there must be something that decides that this particular settings window opens that size. so must be a way to resize it and to save that state.

**Comment by claudiux** [comment]
(Just a temporary patch.) Replace in `/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py` the `maybe_resize` function by this one:
```

    def maybe_resize(self, sidePage):
        m, n = self.content_box.get_preferred_size()

        # Resize vertically depending on the height requested by the module
        use_height = WIN_HEIGHT
        total_height = n.height + self.bar_heights + WIN_H_PADDING
        if not sidePage.size:
            # No height requested, resize vertically if the module is taller than the window
            if total_height > WIN_HEIGHT:
                use_height = total_height
        elif sidePage.size > 0:
            # Height hardcoded by the module
            use_height = sidePage.size + self.bar_heights + WIN_H_PADDING
        elif sidePage.size == -1:
            # Module requested the window to fit it (i.e. shrink the window if necessary)
            use_height = total_height
            if len(sys.argv) > 0 and sys.argv[1] == "network":
                use_height = 350

        self.window.resize(WIN_WIDTH, use_height)
```

**Comment by smurphos** [comment]
@claudiux that works great without impacting on other modules window sizes but the height for the network window does need to be 500 to avoid launching with unnecessary scroll bars.

**Comment by claudiux** [comment]
@smurphos just change `use_height = 350` by `use_height = 500` if you want. But on my computer, scroll bars are always present.

**Comment by akred** [comment]
Hi everyone,

Do you know if a fix is planned for a next version ?

Thanks

**Comment by mtwebster** [comment]
This has been fixed for a while, it will be in the next version: https://github.com/linuxmint/cinnamon-control-center/commit/18bd8a14196a97a0cf47b73d54b5f25027426942

Sorry I never saw this bug to tag it.

**Comment by akred** [comment]
I guess we cannot fix it in the current version (except with the workaround above) ?
I tried to find the "network.ui" file, but I think it's for the next version :)

Thanks for the update

**Comment by qeala** [comment]
I used this: 
        if self.window.get_title() == 'Network':
          use_height = 500

**Comment by qeala** [comment]
I used this:
    if self.window.get_title() == 'Network':
        use_height = 500
