### ISSUE TITLE
Clock desklet: no transparency option

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/cinnamon#8363]
```
 * Cinnamon version (cinnamon --version): 4.0.9
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 19.1
 * Graphics hardware *and* driver used: Intel UHD Graphics 620; Mesa 3
 * 32 or 64 bit: 64
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
 ```
So far as I can see, the inbuilt clock desklet has no transparency option, which I find strange and a considerable drawback. So this is a feature request.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.

**Comment by prateekamana** [comment]
+1

**Comment by Stormtamer1981** [comment]
The Issue still persists in August 2023. Please fix this issue! The Transparency for the Desklets is still not fixed, that appears unprofessional regarding the outstanding work for Cinnamon itself.

We have so many Desklets all suffering from this issue, and i have no glue, why it is so hard to fix for the maintainers?

**Comment by schorschii** [comment]
You can disable the border and header (= "decoration") globally for all desklets if you don't like it. Isn't this what you are looking for?
![1](https://github.com/linuxmint/cinnamon/assets/17480795/ec6bed67-d771-403b-9903-d0f02e908c9b)

Some desklets even offer to adjust this individually, as my Host Check does, but indeed not the inbuilt digital clock.
![2](https://github.com/linuxmint/cinnamon/assets/17480795/551d268c-b9c7-48cd-8a00-1582e78454d7)

**Comment by Stormtamer1981** [comment]
@schorschii I really admire your Host-Check-Widget as well as the clock. Thanks for showing the "hide decoration" feature, but i need the label especially for host check. I would like to see a native transparency option for svg.

Great work my friend, but please improve it.

**Comment by Stormtamer1981** [comment]
@schorschii ach ja und Grüße nach Dresden aus Dresden. Darfst mir gerne deutsch antworten/schreiben!

LG
Micha

**Comment by Stormtamer1981** [comment]
![2023-08-14_07-58](https://github.com/linuxmint/cinnamon/assets/141587682/e2118e1a-d6b4-49f6-a596-5e174ef1465c)

**Comment by schorschii** [comment]
> Thanks for showing the "hide decoration" feature, but i need the label especially for host check. 
> I would like to see a native transparency option for svg.

I don't really understand what you mean with this. Transparency for the green/red background? Can you please elaborate?

Still writing in English here so that others/ Mint maintainers can comprehend the conversation.

Georg

**Comment by Stormtamer1981** [comment]
The Host Check Box and the lower rectangle would be great to see without black background according to the Clock Widget being not either.

**Comment by schorschii** [comment]
So, you can simply enable the "Hide decorations" switch and the black background will be gone. Where exactly is the problem with my Host Check desklet? I understand that feature request for the clock desklet. But what is the issue with the Host Check desklet?

**Comment by Stormtamer1981** [comment]
Hiding the Decoration will disable the entire "Host-Label", you should be familiar with this? After loosing the label, it is not usable to me anymore. The Label is vital for better overview!

**Comment by Stormtamer1981** [comment]
![2023-08-14_21-58](https://github.com/linuxmint/cinnamon/assets/141587682/47706c12-94e4-4824-9b57-07085a7d9023)

System-Settings --> Desklets --> General Settings --> Design of Desklets --> Framing and Header(title)

**Comment by schorschii** [comment]
> Hiding the Decoration will disable the entire "Host-Label"

You mean the desklet label / desklet title.

> After loosing the label, it is not usable to me anymore.

This is the point which was not clear in your previous comments. Now, I understand what you mean... But I don't think this would look nice. It would look like the label/title is detached from the desklet body.

The question is, why exactly is it then not useable for you anymore? You may look for an option to display a custom text instead of the IP address to check? Please be more verbose so that we do not need to guess.

> you should be familiar with this?

:roll_eyes:

**Comment by schorschii** [comment]
@Stormtamer1981 ?

**Comment by dkrulewich1** [comment]
I know this is a closed thread.  And for the most part the "hide decorations" switch solved my problem.  My suggestion is that the default behaviors be more configurable to allow a selected background color, pattern, image, transparency level, etc.  Of course, individual desklets could override, but a more rich set of default options would be pleasant, imo.
