### ISSUE TITLE
[Feature request] Independant monitor scaling settings

### ISSUE THREAD

**Issue by StaphSynth** [linuxmint/cinnamon#8364]
macOS allows you to independently set desktop scaling on a per-monitor basis. I'd love to see this feature on Mint :)

**Comment by vladipus** [comment]
I'm all for this aswell. I heard it's available in Wayland only, thereby no proprietary NVIDIA support. =(

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
