### ISSUE TITLE
Rubbish bin applet throws error

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/Cinnamon#8372]
```
 * Cinnamon version (cinnamon --version): 4.0.9
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 19
 * Graphics hardware *and* driver used: Intel onboard graphics, Mesa 3
 * 32 or 64 bit: 64
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
[x.txt](https://github.com/linuxmint/Cinnamon/files/2839555/x.txt)

 ```

**Issue**

Clicking the rubbish pin applet yields:

![image](https://user-images.githubusercontent.com/47056543/52394065-ec5a8500-2aa0-11e9-86b8-649454e68331.png)

**Steps to reproduce**

Add rubbish pin applet to a panel. Click it.

**Expected behaviour**

The bin should open.

**Other information**

```
$  xdg-mime query default inode/directory
nemo.desktop

![image](https://user-images.githubusercontent.com/47056543/52394142-380d2e80-2aa1-11e9-9c16-a83168fdee26.png)

Cf. #5598

I have Dolphin installed, and I used to have PcManFM and PCManFM-qt.
```

**Comment by leigh123linux** [comment]
Try inmstalling the missing dep listed in image one, there isn't anything to fix within cinnamon.

**Comment by LinuxOnTheDesktop** [comment]
`libexo-helpers` (a dependency of xfce4-terminal) is installed. Re-installing that package did not help. My system has no `/usr/lib/x86_64-linux-gnu/xfce4/exo-1 folder.

Might this be a Nemo rather than a Cinnamon problem? It seems to me that some sort of protocol setting has got messed up.

It would be nice were I to get the trash can working. Here is why. I am trying to use the trash can icon for a side panel containing mainly folder shortcuts. I am using a side panel because of the trouble I have had using icons on Cinnamon desktop (the main but not only problem being that connection to an external monitor rearranged them). Getting the side panel to look as I wanted it required the experimental 'Simple Dock' theme. And now . . the rubbish bin does not work.

I cannot reproduce the trash can problem on a fresh install;

**Comment by LinuxOnTheDesktop** [comment]
**I have located the source of the problem.** My `/.config/mimeapps.list` contained a line starting `inode/directory=` followed by a list of various file manager that did not include nemo - but changing that made no difference. The same file contains:

`x-scheme-handler/trash=exo-file-manager.desktop
`
Modifying that last line fixed the problem.  Might Cinnamon have caused this problem?
