### ISSUE TITLE
Pressing any key on the login field for a long time causes the login functionality to cease.

### ISSUE THREAD

**Issue by hlascelles** [linuxmint/cinnamon#8374]
```
 * Cinnamon version
Cinnamon 3.8.9
 * Distribution
RELEASE=19
CODENAME=tara
EDITION="Cinnamon"
DESCRIPTION="Linux Mint 19 Tara"
DESKTOP=Gnome
TOOLKIT=GTK
NEW_FEATURES_URL=http://www.linuxmint.com/rel_tara_cinnamon_whatsnew.php
RELEASE_NOTES_URL=http://www.linuxmint.com/rel_tara_cinnamon.php
USER_GUIDE_URL=help:linuxmint
GRUB_TITLE=Linux Mint 19 Cinnamon
 * Graphics hardware *and* driver used
02:00.0 VGA compatible controller: NVIDIA Corporation GK106GL [Quadro K4000] (rev a1)
Display Server: x11 (X.Org 1.19.6 ) driver: nvidia 
 * 64 bit
 ```

**Issue**
Holding down a key on the login screen for a long time causes Cinnamon login to be unusable.

**Steps to reproduce**
Lock your workstation. Ensure pressure is left on some char key (eg space bar, M, Z etc...). Wait for an hour.

On return, the password field will show lots of hidden password char dots (as you would expect). However, the password field will be unresponsive. Using CTRL-A to capture and clear the field will not produce any effect. The mouse will still move.

**Expected behaviour**
Mint should stop accepting input into the password field after ~200 characters, and offer a button that should instantly clear the input field (and a pop-up balloon to indicate what is going on perhaps?).

**Other information**
This could happen if something is placed on a keyboard accidentally. I was unable to revive the login screen functionality and had to perform a power off.

**Comment by 0lzi** [comment]
Not 100% sure but i believe this would be a LighDM issue over a Cinnamon issue ?

**Comment by hlascelles** [comment]
I may close this one, as I can't reproduce now. Will reopen if I get more information!
