### ISSUE TITLE
grouped-window-list: keeping focus when closing window

### ISSUE THREAD

**Issue by linux-man** [linuxmint/Cinnamon#8375]
```
 * Cinnamon 4.0.9
 * Mint 19.1
 * Intel
 * 64 bit
 ```

**Issue**
When closing the last grouped window by middle-click or clicking on the thumbnail (x), it's necessary to hover the cursor over other(s) visible thumbnail for them to disapear. Before that, desktop is irresponsive.

**Steps to reproduce**
Open 2 Firefox windows
Hover Icon to show thumbnails
Click close (x) of the right thumbnail

**Expected behaviour**
After "closing the thumbnail", others thumbnails should fade-out if the cursor is not over them.

**Comment by claudiux** [comment]
Not sure this feature request is proposing progress. I appreciate being able to close several windows without having to re-fly the icon. Or it has to be an option in the preferences.

**Comment by linux-man** [comment]
I agree with you, but the need to move the cursor over another thumbnail to unblock the desktop feels like a bug. At the least, grouped-window-list should lose focus if the user clicks on another area.

**Comment by jaszhix** [comment]
I think this happens when a window opens a child dialog asking to confirm closing - such as Firefox when the option is enabled. The menu is supposed to close once the window is deleted, but that is blocked by the confirmation dialog.

**Comment by linux-man** [comment]
Sorry, nothing to do with child windows. It's the applet that captured the mouse and don't release it because it probably thinks that the mouse is still over a thumbnail.

**Comment by jaszhix** [comment]
Ah, sorry, was misunderstanding - I see what you mean. I think we don't need a new setting for this, but we should be checking if the cursor is actually hovering inside the menu, if it's not close it.
