### ISSUE TITLE
Desktop item sort mode is not saved

### ISSUE THREAD

**Issue by GuidoBartoli** [linuxmint/cinnamon#8378]
```
 * Cinnamon version = 4.0.9
 * Distribution = Linux Mint 19.1
 * Graphics hardware = ACER TravelMate integrated graphics
 * 64 bit
 ```

**Issue**
When customizing the current monitor layout, if a sorting mode other than "name" is selected for items, that value is not maintained, because if you reopen the same menu, the value is always reset to "name"

**Steps to reproduce**
1. Right click on desktop
1. Choose "Customize"
1. Change "Sort items by" to "Size", "Type" or "Date"
1. Close window
1. Right click on desktop
1. Choose "Customize"
1. "Sort items by" is reset to "Name"

**Expected behaviour**
"Sort items by" should remember the previous value

**Comment by icarter09** [comment]
Linux Mint 19.2
Cinnamon 4.2.4

Was able to reproduce this issue.

**Comment by claudiux** [comment]
@GuidoBartoli This is a bug of nemo, not Cinnamon. You should close this issue and open a new issue in linuxmint/nemo.

**Comment by GuidoBartoli** [comment]
Ok, I will move it there, thank you!
