### ISSUE TITLE
Cinnamon crash when STOPPING a screen recording, tested on 4 computers

### ISSUE THREAD

**Issue by charlie-ogier** [linuxmint/cinnamon#8380]
* Distribution - (Mint 19.1)
 * 64 bit

**Issue**
Cinnamon crashes when stopping a screen recording [Ctrl]+[Alt]+[Shift]+R
The system halts for a 3 or 4 seconds and then the message asking if you would like to restart Cinnamon appears, all is fine after that.

**Steps to reproduce**
[Ctrl]+[Alt]+[Shift]+R
[Ctrl]+[Alt]+[Shift]+R

**Other information**
This has been tested on 4 machines as detailed in the attached syslog files
[Acer E1-570 syslog.txt](https://github.com/linuxmint/Cinnamon/files/2847936/Acer.E1-570.syslog.txt)
[Dell XPS M1330 syslog.txt](https://github.com/linuxmint/Cinnamon/files/2847937/Dell.XPS.M1330.syslog.txt)
[Intel NUC syslog.txt](https://github.com/linuxmint/Cinnamon/files/2847938/Intel.NUC.syslog.txt)
[Zoostorm i7 syslog.txt](https://github.com/linuxmint/Cinnamon/files/2847939/Zoostorm.i7.syslog.txt)

**Comment by smurphos** [comment]
#8156 

This is already fixed but it doesn't look like the fix wasn't merged in time for 4.0.9

**Comment by ishidex2** [comment]
What recording software do you use?

**Comment by jaszhix** [comment]
SimpleScreenRecorder and OBS are good alternatives.

**Comment by spont4e** [comment]
I have the same problem.
Cinnamon version: **4.0.10**

**Comment by brunofunnie** [comment]
Same issue here using a Thinkpad T480 clean install of Linux Mint 19.1

**Comment by haoyun** [comment]
Same here with Thinkpad X1 extreme, Fedora 30, and Cinnamon 4.0.10.

**Comment by JosephMcc** [comment]
As pointed out above this does appear to be fixed on Cinnamon master.
