### ISSUE TITLE
File removed from the 'recently used files' in Menu isn't synchronized with Nemo 'used recently' list of files

### ISSUE THREAD

**Issue by lalincedeldeserto** [linuxmint/cinnamon#8384]
```
Cinnamon 4.0.9
Linux Mint 19.1 Tessa
 ```

I activated this option:
gsettings set org.cinnamon.desktop.privacy remember-recent-files true
In this way in the menu appears an additional filed 'recently file used' where all the files opened recently are listed. 

The issue: when a recent file is deleted, its link it's not removed. I can remove it manually.

If you open Nemo file manager and click on the field recently used, the recent file removed isn't listed instead. →this should be the right behavior for the menu.

I think the easiest thing to do is to synchronize Menu list when Nemo recently used list changes.

(This is a sort of [#FEATURE REQUEST] in a bug report. If you want I write it as a pull request but it is strongly related to the bug.)

Another thing that might improve the interactivity with the user I think is to add the option to remove a single element from Menu list doing a right click on it and click on the added option "remove from the list".

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
