### ISSUE TITLE
Cinnamon high CPU usage after several hours of work

### ISSUE THREAD

**Issue by eugeneseppel** [linuxmint/Cinnamon#8385]
```
 * Cinnamon version 3.6.7
 * Distribution - Ubuntu 18.04 LTS
 * Graphics hardware *and* driver used -- Intel Corporation UHD Graphics 620, i965
 * 32 or 64 bit
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
 ```

**Issue**
Cinnamon high CPU usage after several hours of work
These typical applications are used: Slack, Firefox, Brave (Chromium), IDEA, Gkrellm, Kate, Skype

**Steps to reproduce**
Work for several hours
cinnamon process should not consume more then 5%

**Expected behaviour**
cinnamon process consumes 50% of one CPU (8 threads Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz)

**Other information**
There are no ways to diagnose why process consume so much time -- no logs, nothing in Looking glass.

**Comment by eugeneseppel** [comment]
[xsession-errors.log](https://github.com/linuxmint/Cinnamon/files/2851841/xsession-errors.log)
[Xorg.0.log](https://github.com/linuxmint/Cinnamon/files/2851849/Xorg.0.log)

**Comment by leigh123linux** [comment]
3.6.7 is EOL, update to 4.0.x

**Comment by teo1978** [comment]
I have the same issue with 4.4.8.

CPU consumption is too high from the very beginning (often around 10% when doing absolutely nothing), but it does get worse over time, to the point that after several hours it's often above 50% or more and renders the whole system unusable.
