### ISSUE TITLE
Panels, applets: cannot see where spacer has been placed

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/cinnamon#8387]
```
 * Cinnamon version (cinnamon --version) 4.0.9
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 19.1
 * Graphics hardware *and* driver used: Intel onboard Mesa 3
 * 32 or 64 bit
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
 ```

**Issue**

When I add a spacer to my panel, there is no sign of it - until I enter 'edit' mode on panel (as against whatever mode adding applets counts as). See video (not attachable to this bug report, sadly) [here on Box](https://app.box.com/s/j880ovneuzf8dfkjwo2usrydqjozofqw).

**Steps to reproduce**

Have panel. Add spacer. But the problem may be theme dependent.

**Expected behaviour**

I should in some way, while adding applets, be able to see where the spacer applet has gone.

**Other information**

The video recorder is *still* broken. That means, every time I make a video to report a bug, I have to Raise Elephants to use my system again.

**Comment by morteryler** [comment]
Unfortunately, this problem and the new linux mint, the developers will fix all the bugs of the year two)))

**Comment by JosephMcc** [comment]
This really could be better.

To record video use something like simplescreenrecorder. It's far better.

**Comment by LinuxOnTheDesktop** [comment]
Screen recording: thanks for the recommendation. But I think you should either remove the inbuilt recorder or else stop it behaving so disastrously. (At present I do not recall exacty what the problem with the recorder was, but it was a serious problem - a crash or hang or a refusal to stop recording.) If it's installed by default, then it shouldn't be almost totally broken.

**Comment by JosephMcc** [comment]
Oh it's less than fantastic. I can't argue that. I don't think most people even realize it's there. But again that's unrelated to the issue. Was just offering you up something I use that I know works far better.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
