### ISSUE TITLE
Panel-launcher applet, feature request: make horizontal spacing alterable

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/cinnamon#8388]
```
 * Cinnamon version (cinnamon --version): 4.0.9
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) 19.1
 * Graphics hardware *and* driver used: Intel onboard Mesa 3
 * 32 or 64 bit: 64
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
 ```

**Issue**

This:

![image](https://user-images.githubusercontent.com/47056543/52600210-ccd1ac80-2e52-11e9-99ae-4e13a88a58fc.png)

The spacing between the different launchers - the three leftmost icons - is too small. (The Netflix icon has more horizontal space around it, but that is by accident of that particular icon. For its part, the screenshot icon - the rightmost icon - is not a launcher.) I could use multiple instances of the launcher applet, but that would be wasteful and inconvenient.

**Steps to reproduce**

Have panel. Add launcher applet. Use latter to add >1 launcher.

**Expected behaviour**

It would be good were the spacing between launchers configurable. Yet, so far as I can tell, it is not (not even by adding 'spacers', because the spacer applet can only be placed between applets . .).

**Other information**

**Comment by smurphos** [comment]
Panel Launcher spacing/padding is currently hardcoded by your choice of cinnamon desktop theme.

If you use pinned apps with the grouped-window-list as an alternative to panel-launchers icon spacing is configurable.

**Comment by LinuxOnTheDesktop** [comment]
> If you use pinned apps with the grouped-window-list as an alternative to panel-launchers icon spacing is configurable.

True, but I'm using the panel in question solely for _folder_ shortcuts (and I am doing that because attaching an external monitor, and indeed changing icon spacing, messes up - rearranges - any icons that I have on the desktop).

> Panel Launcher spacing/padding is currently hardcoded by your choice of cinnamon desktop theme.

I would consider hacking the theme, but since I have three panels, I'd be adjusting the spacing on all of them, which I do not really want.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
