### ISSUE TITLE
Startup applications: initially empty window when try to add an entry

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/cinnamon#8389]
```
 * Cinnamon version (cinnamon --version) 4.0.9
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 19.1
 * Graphics hardware *and* driver used: Intel onboard Mesa 3
 * 32 or 64 bit: 64
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
 ```

**Issue**

![image](https://user-images.githubusercontent.com/47056543/52603876-ac105380-2e60-11e9-9945-3a105156980b.png)

Note that _the bottom of the screenshot is the bottom of the screen_.

**Steps to reproduce**

On my system - details below - simply opening Startup Application (in any which way) and trying to add an entry. I can scroll to entries.

**Expected behaviour**

The user should not be phased and then have to scroll to see anything in the 'add entry' window. It does irritate after a while.

**Other information**

My screen resolution: 2560x1440.
HiDPI: force enabled.

**Comment by JosephMcc** [comment]
Wait so you are running an effective resolution of 1280x720?

**Comment by LinuxOnTheDesktop** [comment]
If a native resolution of 2560x1440 combined with a user interface scaling setting of 'Double (Hi-DPI)' results in an effective resolution of 1280x720, then yes.

**Comment by JosephMcc** [comment]
Thanks for the answer. That doesn't even meet Mint's bare minimum of 768. If you are going to run at such a low res you're going to have to deal with some issues like this. It isn't ideal but it's still usable and we aren't going to focus effort on this.

**Comment by LinuxOnTheDesktop** [comment]
OK. It might be an idea to add a note about this - about Hi-DPI - to the system requirements document.

**Comment by LinuxOnTheDesktop** [comment]
And with the only scaling options being 1x and 2x, without using 2x then everything is tiny on my system. I can increase font and icon sizes, but some things remain too small. For instance, even if I set the window title bar font to 20px, then titlebar buttons remain very small. So I submit that we do have a problem here.

**Comment by JosephMcc** [comment]
Those are totally unrelated issues and there are already open reports about them.
