### ISSUE TITLE
Missing launcher icons

### ISSUE THREAD

**Issue by Futureknows** [linuxmint/Cinnamon#8393]
```
 * Cinnamon version 4.0.8
 * Distribution - Fedora 29
 * Intel GPU with native
 * 64bit

Where does Cinnamon store the panel icon shortcuts? 

After doing some cleanup to free space I lost about a dozen custom panel launchers I had created on the taskbar. Where I can look to recover these launcher shortcuts?

**Comment by morteryler** [comment]
This is in the file $HOME/.cinnamon/configs/grouped-window-list@cinnamon.org/3.json
Inside the file section pinned-apps in it "value"
There are simply listed files desktop. They are on the path: $HOME/.local/share/applications/

**Comment by jaszhix** [comment]
They are located in the directory @morteryler pointed out, but in GWL settings the pinned apps can consist of Cinnamon's global favorites list that the menu uses with the "Pin system favorites" option. This is less prone to losing pinned applications when removing GWL instances and clearing Cinnamon configuration files.
