### ISSUE TITLE
Feature request: Adjacent windows resize together

### ISSUE THREAD

**Issue by txtad** [linuxmint/cinnamon#8394]
```
 * Cinnamon version: N/A
 * Distribution: N/A
 * Graphics hardware *and* driver used: N/A
 * 32 or 64 bit: N/A
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog: N/A
 ```

**Issue**

I often use the ability to quickly size a window to 1/2 or 1/4 screen along with other windows. Sometimes I need one slightly larger than the one next to it, but not overlapping. It would be nice to be able to somehow grab both window edges at the same time and resize them both at the same time, one getting wider (or taller), while the other gets narrower (or shorter) to accommodate.

**Steps to reproduce**

Place two windows on the screen. Windows-key+left arrow on one to move and expand it to fill the left half of the screen, windows-key+right arrow on the other to move and expand it to fill the right half of the screen.

**Expected behaviour**

Somehow, grab the edge of each window that is adjacent to the other and drag left or right to resize them both at the same time.

**Other information**

**Comment by brownsr** [comment]
You can sort-of do this. Assuming a two window case.   Tile one pressing ctrl, then just maximise the other within the space that is left.  Now if you move the boundary they both adjust together (once you release the mouse from the boundary drag)

**Comment by txtad** [comment]
I am not able to recreate that behavior.

**Comment by brownsr** [comment]
Tile one, pressing control when the snap dialog comes up.  Do not tile the other one, just put it in about the right place and use the second button on the top right of the window to expand it to fill the available space

**Comment by txtad** [comment]
Getting the Windows in place is easy enough with snapping, though I've never seen this alleged snap dialog, but adjusting them afterwards is what I'm after.

**Comment by claudiux** [comment]
Yes @brownsr !!! I didn't know this trick. It works very well !

**Comment by Odyseus** [comment]
Hello, everybody.

@txtad: When you are tiling a window, do not let go of the mouse button. A dialog will appear informing you that you can press and hold <kbd>Control</kbd> to enter *snap mode*. You just have to press and hold <kbd>Control</kbd> **BEFORE** you let go of the mouse button to tile a window.

If you have several windows rised (all opened windows that are not minimized) at the moment of entering *snap mode*, all those windows will be automatically tiled together. If you resize any of those tiled windows, the rest of the tiled windows will resize too, keeping them all *snapped*.

P.S.: The <kbd>Control</kbd> key could be any other modifier. It's configuration is found in **System Settings** > **Window Tiling** > **Modifier to use for toggling between tile and snap mode**.

**Comment by txtad** [comment]
Interesting. I've never seen that dialog before as I've never dawdled that long when sizing windows. Now the earlier suggestions make more sense.

However, even when entering snap mode via the control key, I'm not seeing any affect on other windows on the screen. Is it possible that this behavior is different on a multi-monitor (I have three) desktop?

**Comment by ManIVIctorious** [comment]
The snapping mode only affects the size of maximized windows.

**Comment by astier** [comment]
The snap mode doesn't work for me. The dialog window pops up. I press control. I let go the mouse button. The window which is was holding with the mouse snaps. The other window does nothing.

The behavior I need is that when two windows are ALREADY snapped, one to the left the other to the right, you should be able to resize one horizontally and the other should be resized automatically by cinnamon such that both windows don't overlap. This feature can be found in gnome.

**Comment by brownsr** [comment]
The exact behaviour you are after is not supported.  But please refer back
to my earlier reply, there is a workaround.

**Comment by astier** [comment]
Your method above works. However, afterwards it is not possible for me to maximize windows because they get tiled automatically. Also I can now only snap windows into one area with correct window size. If I try to snap windows into the first tile area the window does not have the right window size but rather fills again the half of the screen. Also its a pain to redo this process if I need to change the ratio again. I would love to see the feature as described in the original post. gnome and budgie can do that. cinnamon should also be able to do this. This is the only feature which I am missing currently from cinnamon.

**Comment by astier** [comment]
A simpler solution could be an option in the system settings which would allow to specify the ratio how big the two tiling areas are. This would be enough for me and probably not that difficult to implement.

**Comment by Zahrun** [comment]
I also would appreciate a better window tiling and resizing in Linux Mint. I love the distro but this is a must-have for my workflow. If this feature is not directly implemented in Linux Mint, a port of the ShellTile GNOME Shell extension as a Cinnamon Spices extension would totally fit the need as well.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
