### ISSUE TITLE
Thunderbolt second monitor not detected

### ISSUE THREAD

**Issue by madmaxrichter** [linuxmint/Cinnamon#8407]
```
 * Cinnamon version (4.0.9)
 * Distribution - (Mint 19.1)
 * Intel UHD Graphics 620 with i915 driver
 * 64 bit
 ```
 [syslog.zip](https://github.com/linuxmint/Cinnamon/files/2883523/syslog.zip)
 [xsession-errors.zip](https://github.com/linuxmint/Cinnamon/files/2883524/xsession-errors.zip)
 [Xorg.0.log](https://github.com/linuxmint/Cinnamon/files/2883516/Xorg.0.log)

**Issue**
I am using a Dell XPS 13 (9370) connected to a Caldigit TS3 Plus thunderbolt dock. On this dock I have two monitors connected. One is connected to the display port of the dock, the second one is connected to an USB-C Thunderbolt port using an USB-C to mini DP adapter.

The second monitor is only detected, when I *first* plug in the adapter and *then* plug in the the cable to the adapter. This also only works when the system has booted *and* I am logged in. When the second monitor is not detected, it is not showing in `lsusb`. I already disabled thunderbolt security completely in UEFI. Once the monitor has been detected it is also working during boot, when I restart the system.

**Steps to reproduce**
Attach thunderbolt monitor to dock before powering on the machine.

**Expected behaviour**
Second monitor is also detected when it is attached before boot.

**Comment by leigh123linux** [comment]
Cinnamon code isn't responsible for you issue, try filing it against the kernel instead.

**Comment by madmaxrichter** [comment]
Thanks for the quick reply. I filed a kernel bug: [Bug 202639](https://bugzilla.kernel.org/show_bug.cgi?id=202639)
