### ISSUE TITLE
Terminal apps cannot be launched from desktop

### ISSUE THREAD

**Issue by oberon-manjaro** [linuxmint/Cinnamon#8408]
```
 * Cinnamon version 4.0.8
 * Distribution - Mint 19.1 aswell as Manjaro
 ```

**Issue**
Desktop launchers for terminal applications like for example htop are not working.
**.xsession-errors** says
``Error opening terminal: unknown``

**Steps to reproduce**
create desktop launcher for example by right-clicking a menu entry and selection 'Add to desktop' or copy/link a launcher for a terminal app from **/usr/share/applications**
Opening the application from the menu works fine while clicking the desktop icon does nothing

**Comment by oberon-manjaro** [comment]
Or should I rather open this issue for **nemo** ?

**Comment by smurphos** [comment]
It's already open in nemo - https://github.com/linuxmint/nemo/issues/2009

**Comment by oberon-manjaro** [comment]
Ah ok thanks! So, closing here.
