### ISSUE TITLE
[Feature Request] Middle-click notification applet to clear notifications.

### ISSUE THREAD

**Issue by Draconicrose** [linuxmint/cinnamon#8413]
I would like to be able to middle-click the notification applet to clear all the notifications without having to mouse over to the clear notifications button.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
