### ISSUE TITLE
When I move the mouse over sometimes the app GUI disapears  I'believe it's a Cinnamon thing not exclusive of Mint 19.1 Cinnamon

### ISSUE THREAD

**Issue by titojff** [linuxmint/cinnamon#8414]
Linux Mint 19.1 Cinnamon 4.0.9
NVIDIA Corporation GP106 [GeForce GTX 1060 3GB] - nvidia driver 415
64 bit
Attached  /var/log/syslog

When I move the mouse over sometimes the GUI interface disapears, there's a video link.

https://youtu.be/3MwKWQfCERA

I'believe it's a Cinnamon thing not exclusive of Mint 19.1 Cinnamon

Currently using 4.15.0-45-generic
tested also on 4.18.0-15
It happens also on another PC with Intel processor (Pentium Haswell w/ integrated graphics)
[syslog.txt](https://github.com/linuxmint/Cinnamon/files/2890415/syslog.txt)

**Comment by jaszhix** [comment]
Please attach the output of these commands:

`glxinfo | grep OpenGL`
`env | grep CLUTTER`
`env | grep CINNAMON`
`cat ~/.xsession-errors`
`dpkg -l muffin`

Thanks.

**Comment by titojff** [comment]
All commands output  separated in one file 

[output.txt](https://github.com/linuxmint/Cinnamon/files/2894920/output.txt)

**Comment by loop10** [comment]
I just reproduced this with two completely different computers:

 Before and after a fresh mint 19.1 install. With different video drivers (Nvidia 390, nouveau, Nvidia 340 and "Intel Corporation Device 3e9b prog-if 00 VGA controller" on a System76 laptop. 

This happens mostly as I drag a window (say a firefox window) to a 2nd monitor. I have tried different monitors. Different connections (DVI, HDMI). With and without cinnamon windows effects. None of this changes anything. I see this with different programs besides firefox. But I found one way to "fix it": running  glxgears continuously (on either monitor). 

It's quite annoying as windows (or window "parts") partly or completely dispensary at times and reappear randomly (typically as you select or move an unrelated window). I am adding the results of jaszhix commands 2019-02-23-output.txt . I am not able to view titojff video linked above. All computers have all the latest updates (including the fresh install).

Thank you...

[2019-02-23-output.txt](https://github.com/linuxmint/Cinnamon/files/2897130/2019-02-23-output.txt)

**Comment by titojff** [comment]
> I just reproduced this with two completely different computers:
> 
> Before and after a fresh mint 19.1 install. With different video drivers (Nvidia 390, nouveau, Nvidia 340 and "Intel Corporation Device 3e9b prog-if 00 VGA controller" on a System76 laptop.
> 
> This happens mostly as I drag a window (say a firefox window) to a 2nd monitor. I have tried different monitors. Different connections (DVI, HDMI). With and without cinnamon windows effects. None of this changes anything. I see this with different programs besides firefox. But I found one way to "fix it": running glxgears continuously (on either monitor).
> 
> It's quite annoying as windows (or window "parts") partly or completely disappear at times and reappear randomly (typically as you select or move an unrelated window). I am adding the results of jaszhix commands 2019-02-23-output.txt . I am not able to view titojff video linked above. All computers have all the latest updates (including the fresh install).
> 
> Thank you...
> 
> [2019-02-23-output.txt](https://github.com/linuxmint/Cinnamon/files/2897130/2019-02-23-output.txt)

I just fixed the video link

**Comment by jaszhix** [comment]
Both of you are using the Nvidia 390.xx driver branch, which Nvidia no longer supports. I recommend using the new LTS driver (410) or 415.

https://launchpad.net/~graphics-drivers/+archive/ubuntu/ppa

**Comment by leigh123linux** [comment]
@jaszhix 390.xx is very much supported by nvidia till the the end of 2022

https://nvidia.custhelp.com/app/answers/detail/a_id/3142

That said any pascal owner stupid enough to use the 390.xx driver  deserves to have issues!

**Comment by titojff** [comment]
this also happens on another pc I have with intel processor with integrated graphics

**Comment by titojff** [comment]
this also happens on another pc I have with intel processor with integrated graphics

**Comment by titojff** [comment]
@jaszhix how do you install another branch of muffin?

**Comment by leigh123linux** [comment]
@titojff Can you reproduce it using another app?,  I have seen many vlc issues similar to the video you posted.

**Comment by titojff** [comment]
it happens not only with vlc
also with trasmission-gtk xed and others

**Comment by leigh123linux** [comment]
Maybe Mint's base is rotten, have you tried mesa and xorg HWE packages to see if it helps?
I don't have the issue here and doubt the issue is within the cinnamon/muffin code.

```
$ inxi -GS
System:
  Host: leigh.computer-desktop Kernel: 5.0.0-0.rc6.git1.2.fc30.x86_64 x86_64 
  bits: 64 Desktop: Cinnamon 4.0.8 Distro: Fedora release 30 (Thirty) 
Graphics:
  Device-1: NVIDIA GP107 [GeForce GTX 1050 Ti] driver: nvidia v: 418.43 
  Display: x11 server: Fedora Project X.org 1.20.3 driver: nvidia 
  unloaded: fbdev,modesetting,nouveau,vesa resolution: 3840x2160~60Hz 
  OpenGL: renderer: GeForce GTX 1050 Ti/PCIe/SSE2 v: 4.6.0 NVIDIA 418.43
```

**Comment by jaszhix** [comment]
I stand corrected 390.xx is supported until 2022. The official Ubuntu PPA has a newer version that might work better though (390.87). I would only use that branch if your GPU lost support in the 410.xx series, such as Fermi GPUs.

**Comment by jaszhix** [comment]
@titojff You will need to compile Cinnamon and its dependencies. The muffin PR links to a couple Cinnamon PRs it requires. I can build some binaries later if anyone wants to test it.

**Comment by titojff** [comment]
@loop10  running glxgears works for me too, is there a way of running it hidden?

**Comment by leigh123linux** [comment]
@titojff Perhaps setting nvidia to 'prefer maximum performance' in setting would have the same affect.

**Comment by loop10** [comment]
leigh123linux: thank you for the suggestion but setting NVIDIA Xserver Settings "PowerMizer" to "prefer maximum performance" does not help.

Running glxgears all the time had down sides: shutter-0.94 fails to capture the screen.
I also have the issue with Intel video on a laptop, so the NVIDIA card or driver are not the main suspects.

**Comment by titojff** [comment]
I'm currently instaling Siduction Cinnamon which is based on Debian Sid I'll let you know if it still happens...

**Comment by titojff** [comment]
Debian sid stil uses cinnamon 3.8.8 so it does not happen

**Comment by loop10** [comment]
My own video. After all Mint Cinnamon updates on 2019-03-05 and a reboot:
https://colororange.com/bug.mp4
The exact behaviour varies, sometimes part of the window is OK. This happens often as I move a window to the 2nd terminal (I filmed that). It happens rarely on the 1st terminal.

**Comment by titojff** [comment]
I'm using Mint 19.2 and it's fixed

Thanks
