### ISSUE TITLE
[Feature request]: Web browser integration to support playback controls

### ISSUE THREAD

**Issue by sandy-rao** [linuxmint/cinnamon#8416]
```
 * Cinnamon version (cinnamon --version) N/A
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) N/A
 * Graphics hardware *and* driver used N/A
 * 32 or 64 bit N/A
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog N/A
 ```

**Issue**
I propose to develop a solution similar to kde-plasma-browser-integration that enables you to play/pause/skip tracks playing in the web browser using system tray or using media-keys/ global shortcuts.

[See a demo](https://www.youtube.com/watch?v=WGhrR1HsCOM) of feature already in kde.

**Steps to reproduce**
No support to popular media websites playing audio/video on browsers like firefox/chrome.

**Expected behaviour**
To develop a solution that allows you to control playback in web browser using system tray / media shortcuts.

**Other information**

**Comment by ManIVIctorious** [comment]
I am not absolutely sure, but AFAIK kde as well as cinnamon have full playback control utilizing „MPRIS2“.

To my understanding this must be fixed by the spplication developer (Firefox/chrome/you name it) by implementing remote control over mpris

**Comment by sandy-rao** [comment]
I browsed through the [github repo for the project](https://github.com/KDE/plasma-browser-integration/tree/master/extension)  and I do see MPRIS being used.
Could you or someone with more technical skills than me, have a look and say if the repo could be forked and changes made to include similar functionality in cinnamon.

**Comment by ManIVIctorious** [comment]
I think you got me wrong, Cinnamon already uses MPRIS (in version 2 I think) but neither does Firefox nor Chrome/ium, so these are the programs which need to be patched.
When the MPRIS support is in the applications Cinnamon (as well as KDE) should be able to control their media out of the box

**Comment by sandy-rao** [comment]
Kde already supports via browser plugins (whose sourcecode is in the github repo) as well as a linux host program(package called plasma-browser-integration) for popular browsers. 

1. [firefox](https://addons.mozilla.org/en-US/firefox/addon/plasma-integration/)
2. [chrome/chromium](https://chrome.google.com/webstore/detail/plasma-integration/cimiefiiaegbelhefglklhhakcgmhkai)

What I was wondering is, since the plugins use MPRIS and as you say cinnamon already supports MPRIS, would it be too hard to fork the plugins in the [github repo](https://github.com/KDE/plasma-browser-integration/tree/master/extension).

Would you say this is out of the scope for the cinnamon project?

**Comment by shamoi** [comment]
I suggest this repository: [https://github.com/beingmohit/browser-playerctl](url) . Been using it with Youtube for two weeks now. Playback controls can be manipulated with from either your sound applet and your multimedia keys depending of your keyboard.

**Comment by Lt-Mayonesa** [comment]
Hey, i have also implemented a solution to this [https://lt-mayonesa.github.io/browser-mpris2/](https://lt-mayonesa.github.io/browser-mpris2/) (both of this repos are actually forks of [otommod's](https://github.com/otommod/browser-mpris2)).

Mine works with any media playing in the browser by default. just like kde's.

I would be really happy if you could check it out, cheers.

**Comment by ManIVIctorious** [comment]
This looks very promising, mind to update this thread when its signed by Mozilla? Would really like to try it but I do not like unsafe sources on my pc

**Comment by Lt-Mayonesa** [comment]
@ManIVIctorious It's done! Both native and extension can be downloaded from the releases page. :smiley:

**Comment by ManIVIctorious** [comment]
Disclaimer: Sorry for spamming this thread...
@Lt-Mayonesa finally got the time to try your addon and I have to say it is AWESOME, it even supports multiple tabs 😍
Thank you so much for this!

Just a side note:
I am not on a debian based distro and it took me a few minutes to get it working, maybe you should add the post hook commands
`browser-mpris2 --init-firefox "browser-mpris2@lt-mayonesa.github.io"` (and the one for chrome)
to your Readme file.

**Comment by Lt-Mayonesa** [comment]
Thanks @ManIVIctorious! :heart: (and again sorry for the spam). I'll be sure to add that to the docs :)

Also, if you happen to find any bugs or come up with any ideas for improvements please submit them as issues in the repo. I'll be happy to look at them
