### ISSUE TITLE
Make dependency on NetworkManager optional

### ISSUE THREAD

**Issue by andy-vetrov** [linuxmint/Cinnamon#8418]
Please, make dependency on NetworkManager optional.

I wrote small patch for Arch Linux, which removes this dependency and they work. Modified package available in Arch Linux User Repository (AUR) and named cinnamon-slim:
https://aur.archlinux.org/packages/cinnamon-slim/

Please, add this functionality in upstream. I don't need NetworkManager installed on my PC - connman work perfect, but NM - no.

**Comment by leigh123linux** [comment]
This isn't going to happen, it would also break several applets and cause crashes.

**Comment by andy-vetrov** [comment]
No breaked applets, no crashes, no NetworkManager ;-) Cinnamon stable as rock.
