### ISSUE TITLE
Decreasing boottime

### ISSUE THREAD

**Issue by wanttoreportabug** [linuxmint/Cinnamon#8420]
```
 * Cinnamon version no idea... latest. 
 * Mint 19.1 Cinnamon
 * Xorg 1.19.6 (Intel ivybridge Mobile 3.0 Mesa 18.2.2
 * 64 bit

 ```

**Issue**
I noticed a decrease in boottime for Linux Mint 19.1. I am using the mint logo with the 5 dots that turn green (when startup) as benchmark. After i installed 19.1 the black screen with only cursor appeared after 2 white dots turned green (2 seconds). Then it takes about 1 second until the normal screen appears. Now after several update / upgrades i notice that it takes 7 white dots (5 + 2 in the next cycle = 7 seconds) to turn green before the black screen with only cursor appears. Then it takes about 2 seconds for the normal screen (desktop) appears. This is a significant slowdown in bootup time. I use an intel I3 processor and an SSD on this laptop (ASUS X200CA). To check my findings it i took another laptop with I3 processor and an SSD and did a "clean" install from the 19.1 .iso and indeed it showed 2 dots turn green and so on. After a full update it also showed 7 dots turning green so the slowdown seems consistant. Now, in normal use you dont notice this, Mint 19.1 is quick as ever to respond so no problem there.

**Steps to reproduce**
Take a system and install the mint19.1 iso as downloaded
When ready count the number of dots below the mint logo that turn from  white to green. It will be 1 dot for every second (so in my case 2 seconds)
Do a full update and upgrade of the system to the latest version (apt-get update && apt-get dist-upgrade -y)
Reboot the system and again count the dots. In my case it is now 7 dots = 7 seconds.

**Expected behaviour**
 1 second more delay after an upgrade ?

**Other information**
Nope, think my point is clear, love Mint and am using it since version 9.0

**Comment by leigh123linux** [comment]
Boot time has nothing to do with cinnamon.
