### ISSUE TITLE
Expose desktop does not redraw correctly 

### ISSUE THREAD

**Issue by jfmoulin** [linuxmint/Cinnamon#8422]
When exposing my desktops via hot-corner the  desktops are not properly redrawn and show blurry patches in place of the opened windows. Playing Videos are shown static (always?)

![desktop_expose](https://user-images.githubusercontent.com/2844284/53342627-b75a8900-390e-11e9-919e-1bd1da7bcda2.jpg)

My setup: 
Mint 19.1 64 bits
Cinnamon 4.0.9
uname -a:
Linux johndoe 4.15.0-45-generic #48-Ubuntu SMP Tue Jan 29 16:28:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

NVIDIA-driver-390.77

**Comment by jaszhix** [comment]
https://github.com/linuxmint/Cinnamon/issues/8304

**Comment by jfmoulin** [comment]
Hello,

2020 almost gone now, but my problem is still floating around.
It now impacts me much more in a special case: using the Atom editor to work on Julia code, the REPL gets blurred and never gets restored. This means that I loose the possibility to interact with my code and have to relaunch and reproduce the session which is at best a pain in the neck but more often plain impossible...
BTW, I updated the system quite a bit since the original post:
Linux johndoe 5.4.0-56-generic #62-Ubuntu SMP Mon Nov 23 19:20:19 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
