### ISSUE TITLE
.desktop launcher does not honor Path= statement

### ISSUE THREAD

**Issue by jjberk** [linuxmint/cinnamon#8425]
```
Cinnamon 4.0.9
Linux Mint 19.1 Cinnamon 64  bit

**Issue**
Clicking on the desktop icon with the following .desktop file:

   [Desktop Entry]
   Name=Bkh
   Exec=/home/public/Documents/ACCOUNT/bkh.pl
   Comment=Boekhouding
   Terminal=false
   Type=Application
   Path=/home/public/Documents/ACCOUNT/

opens my (perl) script, but the current directory is my home directory.
It seems the Path= statement is not honored.

**Steps to reproduce**
Make a desktop launcher and look  at the working directory.

**Expected behaviour**
Execute the application with a working directory as specified in the Path statement.

**Other information**
The same .desktop file executes properly under Linux Mint 19 with Cinnamon 3.8.9

**Comment by Solus32** [comment]
I have the same problem with .desktop file

The problem appears with

Cinnamon 4.0.9
Linux Mint 19.1 Cinnamon 64 bit

[Desktop Entry]
Version=1.0
Name[es]=Actualizar Sistema
Comment[es]=Actualizar el sistema
Exec=/usr/local/bin/actualizacion-automatica
Icon=/home/solus/Imágenes/actualizar_sistema_icono_v2.png
Terminal=true
Type=Application
Categories=Utility;Application;

The same .desktop file executes properly under XFCE, and Ubuntu 18.04.

**Comment by smurphos** [comment]
@Solus32 yours is a different problem  albeit I suspect the ultimate cause is the same. For a workaround to your issue pending this being fixed see https://github.com/linuxmint/nemo/issues/2009

**Comment by smurphos** [comment]
@jjberk this probably should be filed as an issue against Nemo as nemo-desktop handles launching of desktop launchers.

**Comment by jjberk** [comment]
smurfos: Thanks. Done.
leigh123linux: I'm sorry for that stupid typo.  Thanks for correcting.

**Comment by zorbakus** [comment]
Having the same issue with a portable program. It starts in the home directory, and creates its config files there, instead of actual path where the executable is.

[Desktop Entry]
Version=1.0
Encoding=UTF-8
Name=Powder Toy
Type=Application
Comment=Physics sandbox game
Categories=Game;Simulation
Icon=powdertoy.png
Exec='/home/username/Games/the-powder-toy/powder64'
Path=/home/username/Games/the-powder-toy

**Comment by Solus32** [comment]
@smurphos Thank you so much for the workaround.

**Comment by xenopeek** [comment]
Retested on Linux Mint 20 Cinnamon and wasn't reproducible on that. See my comment on the same issue for Nemo: https://github.com/linuxmint/nemo/issues/2078#issuecomment-650800960. If any are still affected by this see the test in that comment and please comment there if you can reproduce it with that on Cinnamon 4.6.6 + Nemo 4.6.4.
