### ISSUE TITLE
(Some) "appindicator" systray icons duplicate on activity

### ISSUE THREAD

**Issue by rik-shaw** [linuxmint/cinnamon#8426]
```
 * Cinnamon version (cinnamon --version)
Cinnamon 4.0.9

 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
Ubuntu 18.04.2

 * Attach /home/<username>/.xsession-errors, or /var/log/syslog

diodon (when copying something):
Cjs-Message: 12:49:22.089: JS LOG: [LookingGlass/info] Adding indicator: Diodon

skypeforlinux (when running as appindicator - see below - and changing "status"):
Cjs-Message: 12:56:51.864: JS LOG: [LookingGlass/info] Adding indicator: Skype1
Cjs-Message: 12:56:52.381: JS LOG: [LookingGlass/error] [IndicatorActor] Unable to lookup icon for Skype1_4-panel
Cjs-Message: 12:56:52.456: JS LOG: [LookingGlass/error] [IndicatorActor] Unable to lookup icon for Skype1_4-panel
Cjs-Message: 12:56:52.523: JS LOG: [LookingGlass/error] [IndicatorActor] Unable to lookup icon for Skype1_4-panel
Cjs-Message: 12:56:52.588: JS LOG: [LookingGlass/error] [IndicatorActor] Unable to lookup icon for Skype1_4-panel
```

**Issue**
Diodon, a clipboard manager, duplicates its tray icon every time something is added to the clipboard.  See the above output from tail -f .xsession-errors
Right now I have 10 diodon icons in my tray because I have copied something 9 times this session!

skypeforlinux when run for appindicator support this way:
```
 env XDG_CURRENT_DESKTOP=Unity skypeforlinux
```
also has the same issue (if you change the "status" of skype, the icon is duplicated each time).  The reason for running skypeforlinux with appindicator support is to get a larger icon in the tray plus to standardize right click / left click for the icon to match other indicator consistency, as per this issue: https://github.com/linuxmint/Cinnamon/issues/7588#issuecomment-458144910

 Without running as an "indicator" the skypeforlinux icon is NOT duplicated.  See above for .xsession-errors output

**Other information**
Maybe this is a "cjs" issue instead of for cinnamon according to the above .xsession-errors line?

**Comment by rik-shaw** [comment]
Update: by disabling "appindicator support" in Cinnamon diodon and skypeforlinux no longer get duplicated when changing status (even retaining the "GTK_CURRENT_DESKTOP=unity" for skype to allow the larger icon to be used).  So the bug is certainly somewhere in Cinnamon's appindicator support.

For those wanting to test the fix, you can use this command:
```
gsettings set org.cinnamon enable-indicators false
```

**Comment by vladimir-didenko** [comment]
I started to see this issue on latest master, previously (on 4.0.9) it worked as expected for me.

**Comment by Xeronel** [comment]
Same issue here.

Setting this as @rik-shaw suggested does fix the problem for me.
gsettings set org.cinnamon enable-indicators false

I was experiencing the issue with Discord and the latest release of Cinnamon.

**Comment by vincent-ledu** [comment]
Hello,

are you speaking about this kind of bug ?
![image](https://user-images.githubusercontent.com/7086413/71204850-766aa100-22a1-11ea-952b-87943e1e178d.png)
I think I'm experiencing same issue.

**Comment by mtwebster** [comment]
@vincent-ledu what distro and version of cinnamon?  And are you using the tray applet with indicator support enabled?

**Comment by vincent-ledu** [comment]
Here is info I can produce: 
```
$ cat /etc/os-release
NAME="Linux Mint"
VERSION="19.3 (Tricia)"
ID=linuxmint
ID_LIKE=ubuntu
PRETTY_NAME="Linux Mint 19.3"
VERSION_ID="19.3"
HOME_URL="https://www.linuxmint.com/"
SUPPORT_URL="https://forums.ubuntu.com/"
BUG_REPORT_URL="http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/"
PRIVACY_POLICY_URL="https://www.linuxmint.com/"
VERSION_CODENAME=tricia
UBUNTU_CODENAME=bionic
```
```
$ cinnamon --version
Cinnamon 4.4.5
```

> And are you using the tray applet with indicator support enabled?

I don't remember to have changed it (I don't know what is it). It is disabled in System Settings > General > Miscellaneous Opetions > Enable Support blablabla

So, I probably not on the good issue. Should I create a new one named: "Duplicate Systray icons" (just to  check if i used the goods technical words)

thanks

**Comment by mtwebster** [comment]
If you control-right-click on one of these repeated icons, does it popup a menu saying 'Remove XApp Status Applet'?  or just the normal icon's menu?

Can you paste what you get when you run:
```
gsettings get org.cinnamon enabled-applets | tr ',' '\n'
```
in a terminal

Thanks

**Comment by mtwebster** [comment]
also, did you upgrade to 19.3 or do a clean install?

**Comment by vincent-ledu** [comment]
> If you control-right-click on one of these repeated icons, does it popup a menu saying 'Remove XApp Status Applet'? or just the normal icon's menu?

yes, it says: "Remove XApp Status Applet"

> 
> Can you paste what you get when you run:
> 
> ```
> gsettings get org.cinnamon enabled-applets | tr ',' '\n'
> ```

'panel1:left:0:menu@cinnamon.org:37'
 'panel1:left:1:show-desktop@cinnamon.org:38'
 'panel1:left:2:grouped-window-list@cinnamon.org:39'
 'panel1:right:11:systray@cinnamon.org:40'
 'panel1:right:12:keyboard@cinnamon.org:41'
 'panel1:right:13:notifications@cinnamon.org:42'
 'panel1:right:14:removable-drives@cinnamon.org:43'
 'panel1:right:15:network@cinnamon.org:44'
 'panel1:right:16:sound@cinnamon.org:45'
 'panel1:right:17:power@cinnamon.org:46'
 'panel1:right:18:calendar@cinnamon.org:47'
 'panel1:right:9:xapp-status@cinnamon.org:49'
 'panel1:right:8:xapp-status@cinnamon.org:50'
 'panel1:right:7:xapp-status@cinnamon.org:51'
 'panel1:right:6:xapp-status@cinnamon.org:52'
 'panel1:right:5:xapp-status@cinnamon.org:53'
 'panel1:right:4:xapp-status@cinnamon.org:54'
 'panel1:right:3:xapp-status@cinnamon.org:55'
 'panel1:right:2:xapp-status@cinnamon.org:56'
 'panel1:right:0:blueberry@cinnamon.org:58']

> 
> in a terminal
> 
> Thanks


> also, did you upgrade to 19.3 or do a clean install?

an upgrade today, from tina (19.2)

**Comment by vincent-ledu** [comment]
ok, I think i understand.

when 19.3 just opened, it ask to add Xapp status applet.
I added, as it told me (I'm a good boy :) ) but nothing appear in systray.
As I'm stupid, i click a lot, then give up.
and after a restart... plenty of icon in my systray.

fixed by removing xapp-status, then add only once.

thank a lot for your quick replies, which help me to recover a proper pane.
