### ISSUE TITLE
Cinnamon crashes when I try to compress or uncompress files or folders in terminal with file-roller

### ISSUE THREAD

**Issue by andy-vetrov** [linuxmint/Cinnamon#8427]
Arch Linux x64
Cinnamon version 4.0.9
File-roller version 3.30.1
[xsession-errors.txt](https://github.com/linuxmint/Cinnamon/files/2910198/xsession-errors.txt)

Cinnamon crashes when I try to compress or uncompress files or folders in terminal with file-roller (file-roller -h or file-roller -d or file-roller -f commands). From GUI all works normally.

**Comment by leigh123linux** [comment]
File your issue against  file-roller at archlinux bug tracker.

**Comment by andy-vetrov** [comment]
I found source of this bug. This is Muffin v 4.0.6. When I rollback to 4.0.5 all bugs gone.
