### ISSUE TITLE
System Monitor: CPU graph colors beyond CPU4 are the same

### ISSUE THREAD

**Issue by veikk0** [linuxmint/Cinnamon#8432]
```
 * Cinnamon version: latest, up-to-date one provided with 19.1 (not on my Cinnamon machine right now, will update exact version later)
 * Distribution - Mint 19.1 64-bit
 * Graphics hardware: AMD Radeon RX 470, default OSS drivers
 ```

**Issue**
In Cinnamon's System Monitor, the graph colors for CPU cores beyond CPU4 are all the same, reddish orange color. In the default view where CPU usage is drawn as just a bunch of lines this isn't very noticeable since that view is quite confusing and hard to read on high core count systems anyway and color doesn't complicate it much, but when changing to the stacked area chart the problem becomes more apparent. On a system with an 8-core 16-thread CPU, System Monitor looks like this:

![system-monitor](https://user-images.githubusercontent.com/7808922/53587987-78d60000-3b94-11e9-965a-7076136aff1b.png)

(One can fix this oneself by setting the CPU colors manually but they should have unique colors by default.)

**Steps to reproduce**

Open System Monitor on a machine with more than 4 logical cores and set it to stacked chart mode (Preferences -> Resources -> Draw CPU chart as stacked area chart).

**Expected behaviour**

Cores beyond 4 should all have their own, at least somewhat distinct colors.

**Other information**

The equivalent piece of software on the MATE desktop doesn't seem to have this issue. All the cores are different colors there. It doesn't have stacked chart mode however.

**Comment by JosephMcc** [comment]
Thanks for the report but that application has nothing to do with Cinnamon. Mint Cinnamon ships with gnome-system-monitor and bugs with it should be reported to them. I believe Mate develops and ships its own version of this.
