### ISSUE TITLE
Window cropped on some programs

### ISSUE THREAD

**Issue by lucaslira95** [linuxmint/cinnamon#8434]
```
OS: Mint 19.1 tessa
 Kernel: x86_64 Linux 4.15.0-45-generic
 Uptime: 1h 33m
 Packages: 2262
 Shell: bash
 Resolution: 1366x768
 DE: Cinnamon 4.0.9
 WM: Muffin
 WM Theme: Mint-Y-Dark (Mint-Y)
 GTK Theme: Mint-Y [GTK2/3]
 Icon Theme: Mint-Y
 Font: Noto Sans 9
 CPU: Intel Core i3-5005U @ 4x 1.9GHz [45.0°C]
 GPU: Mesa DRI Intel(R) HD Graphics 5500 (Broadwell GT2) 
 RAM: 800MiB / 3865MiB

 ```

**Issue**
Everytime I boot the OS, I open Chrome and the window is cropped 1/4 of the screen, this happens with the default file explorer too...

**Steps to reproduce**
Just reboot OS and try to open your browser or another program 

**Expected behaviour**
Program window cropped 1/4 of screen

**Image**
https://imgur.com/t5lXUJ2

**Syslog**
[syslog.txt](https://github.com/linuxmint/Cinnamon/files/2917818/syslog.txt)

**Comment by VladimirBelyakof** [comment]
I confirm issue

```
NAME=Fedora
VERSION="29 (Twenty Nine)"
ID=fedora
PLATFORM_ID="platform:f29"

```

**Comment by lucaslira95** [comment]
I don't presenced this problem anymore, if someone can confirm the bug is fixed, then, may be worth closing the thread...

**Comment by lucaslira95** [comment]
> I confirm issue
> 
> ```
> NAME=Fedora
> VERSION="29 (Twenty Nine)"
> ID=fedora
> PLATFORM_ID="platform:f29"
> ```

Are you still having this problem?

**Comment by VladimirBelyakof** [comment]
> > I confirm issue
> > ```
> > NAME=Fedora
> > VERSION="29 (Twenty Nine)"
> > ID=fedora
> > PLATFORM_ID="platform:f29"
> > ```
> 
> Are you still having this problem?

No
