### ISSUE TITLE
All Sound stops working, intermittently

### ISSUE THREAD

**Issue by HydrocarbonPrimate** [linuxmint/Cinnamon#8440]
Cinnamon 3.8.9

Linux mint 19 Cinnamon 
4.15.0-45-generic
Panasonic CF-52 Toughbook
Intel© Core™ i5 CPU       M 520  @ 2.40GHz × 2

I'm having complete audio drop-out issues after some recent updates, it was totally fine before and I have been looking into it, it seems to happen about 20-30 minutes after a reboot and ALL audio drops out, I have tried reloading ALSA and Pulse audio, I've tried changing a couple of lines in Pulse config to no avail,  (its generating a log somewhere) I have tried everything, the only thing that fixes audio is a reboot OR reloading kernel modules: sudo modprobe snd-hda-intel followed by ALSA force reload, which does not work without reloading the aforementioned kernel modules. 

Everything from syslog seem to be not relevant, what I mean is everything "grepped" from syslog regarding ALSA, Pulse and CX20584 (my integrated / onboard soundcard) is all old, no new events at dropout times. 

Its very odd and I thought it might be related to temperature of laptop, however cputemps are only 43 Degrees, It seems that after audio has dropped out the first time, and i reload kernel driver it lasts maybe 2 minutes before another dropout, I'm not sure if this is a hardware or software issue. 

`charlie@CF-52:~$ lspci -v | grep -A7 -i "audio"
00:1b.0 Audio device: Intel Corporation 5 Series/3400 Series Chipset High Definition Audio (rev 06)
	Subsystem: Matsushita Electric Industrial Co., Ltd. 5 Series/3400 Series Chipset High Definition Audio
	Flags: bus master, fast devsel, latency 0, IRQ 31
	Memory at eb120000 (64-bit, non-prefetchable) [size=16K]
	Capabilities: <access denied>
	Kernel driver in use: snd_hda_intel
	Kernel modules: snd_hda_intel

00:1c.0 PCI bridge: Intel Corporation 5 Series/3400 Series Chipset PCI Express Root Port 1 (rev 06) (prog-if 00 [Normal decode])
charlie@CF-52:~$ `

**Comment by leigh123linux** [comment]
I have removed your enormous pastes as it's unreadable!, use attachment or pastebin in future.
The issue is more likely to be in alsa, pulseaudio or the kernel, please file your issue at ubuntu bug tracker instead.

**Comment by HydrocarbonPrimate** [comment]
Thats great, thanks for your help! really fucking helped!   

eat a dick

**Comment by leigh123linux** [comment]
Shame your not local as I would shove that stinking laptop up your rectum sideways!

**Comment by brownsr** [comment]
@HydrocarbonPrimate I really don't now why you reacted so abusively to a volunteer team member like Leigh.  As he said, if it is a software issue (and it is 'if', it may yet be hardware) it isn't something this project can help with, it's almost certainly an upstream issue as nothing in this project has much to do with low-level audio interfacing.  Upstream developers will not look here for any bug reports, so you need to refile your bug report at the ubuntu bug tracker site.  I appreciate this looks like your first ever issue raised on github, if so you need to be aware that each project looks after its own bug reports, and as a community project you have your part to play too, and that includes filing your bug reports somewhere else if you are redirected.  Leigh took the trouble to read your report, tell you the most likely subsystems, and where to file it.  He even said please.
