### ISSUE TITLE
Audicious : sound icon not visible

### ISSUE THREAD

**Issue by Zefling** [linuxmint/cinnamon#8442]
```
 * Cinnamon version 4.0.9
 * Linux Mint 19.1 Tessa
 * 770 GTX with nouveau
 * 64 bit
 ```

**Issue**
Sound icon is the same gray as the software :
![selection_048](https://user-images.githubusercontent.com/3032555/53699761-1b3bf080-3dec-11e9-8d4e-a58defb86dbf.png)
![selection_049](https://user-images.githubusercontent.com/3032555/53699763-1ecf7780-3dec-11e9-8a4d-0ea477b61cf8.png)

**Steps to reproduce**
Just install and launch Audicious.

**Expected behaviour**
That the icon is the same color as the others.

**Comment by icarter09** [comment]
I installed Audacious and did notice that the sound icon is a lighter shade the other icons. That being said, I don't believe this is the fault of Cinnamon, but rather Audacious. 

Please test this out on another DE. You can reopen the issue if the responsible component proves to be Cinnamon.
