### ISSUE TITLE
Return back button on settings

### ISSUE THREAD

**Issue by freeseacher** [linuxmint/cinnamon#8444]
```
 * Cinnamon version (cinnamon --version)
Cinnamon 4.0.9

 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
Mint 19.1
 * Graphics hardware *and* driver used
NA
 * 32 or 64 bit
64
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
 ```

**Issue**
My usual way to edit cinnamon settings was 
* right click on desktop
* open background settings
* press back button 
* here it is settings for system. 
Usually i'm interested in monitor settings or so. 

**Steps to reproduce**

**Expected behaviour**
Back button exists. but it doesn't 
Any way how can i return back button 

**Other information**
![default](https://user-images.githubusercontent.com/289277/53728118-f777b980-3e82-11e9-91d4-800516bb22d1.png)

**Comment by apandada1** [comment]
Proposed solution - Instead of a back button, put a settings icon there. Then it will always work as a handy shortcut to go back to system settings.
This way, every individual settings remain a standard app, but it also allows to browse all settings, which enriches the user experience.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
