### ISSUE TITLE
Allow to hide applications and applets/panel item as `Sound`, `Power` in a submenu

### ISSUE THREAD

**Issue by evandrocoan** [linuxmint/cinnamon#8449]
```
 * Cinnamon version 4.0.9
 * Distribution - Mint 19.1
 * Graphics hardware
Graphics:  Device-1: VMware SVGA II Adapter driver: vmwgfx v: 2.14.0.0 bus ID: 00:0f.0 
           chip ID: 15ad:0405 
           Display: x11 server: X.Org 1.19.6 driver: vmware unloaded: fbdev,modesetting,vesa 
           resolution: 1916x969~60Hz 
           OpenGL: renderer: SVGA3D; build v: 3.3 Mesa 18.2.2 compat-v: 3.1 direct render: Yes 
 * 64 bit
 ```

Allow to hide applications and applets/panel item as `Sound`, `Power` in a submenu:

![image](https://user-images.githubusercontent.com/5332158/54080418-d6252c00-42cd-11e9-9c6b-4f0624062ad0.png)

This is very similar as:
1. https://github.com/mate-desktop/mate-panel/issues/889 Hide system tray icon, providing more space on the panel

**Comment by Mr-Pyro** [comment]
I too would like this feature.

**Comment by Odyseus** [comment]
Hello, everybody.

In case that you didn't know, there are third-party applets that can achieve what it is requested in this issue. The [Hideable applets](https://cinnamon-spices.linuxmint.com/applets/view/293) and [Drawer (show/hide applets)](https://cinnamon-spices.linuxmint.com/applets/view/169) applets can be used to hide applets. And the [Collapsible Systray](https://cinnamon-spices.linuxmint.com/applets/view/265) applet is used to replace the Cinnamon System Tray applet with one with the capability to selectively hide applications' icons.

With regards to this feature request, I also would like to see it implemented by default in Cinnamon.

**Comment by evandrocoan** [comment]
@Odyseus, did you installed any of these?

Hide Applets is the one from where I took the first screenshot. Hide Applets does not do hide things correctly as Drawer and the Windows Built-in system tray does.

Drawer definitely does not work right. It only hides what it does feel like. I cannot add what would like to hide. Most times, it does not hide anything.

XFCE has one "Drawer" which actually allow me to hide what I want to. Its only problem is that is cannot hide Wine applications tray icons and other panel items.

Also, both XFCE "Drawer" and Cinnamon Drawer, hide things horizontally, not vertically as the image on the first post.

**Comment by Odyseus** [comment]
Hello, @evandrocoan.

> ...did you installed any of these?

Yes. I have been using **Drawer (show/hide applets)** and **Collapsible Systray** for more than three years now without any problems.

> Drawer definitely does not work right...

You just need to use your crystal ball (LOL). I also had problems at understanding how it works. **Drawer (show/hide applets)** automatically hides the applets that are placed to the left of it.

> ...Hide Applets does not do hide things correctly...

And it never will. Simply because Cinnamon doesn't provide a *menu like* container that can hold applets in a functional way like panels do. The **Hideable applets** applet does the best it can do with the tools at hand without having to write thousands of lines of code.

I witnessed a discussion some years ago between Cinnamon developers about an idea of implementing such containers. But there is so much that a team of developers that can be counted with the fingers of one hand can do.

**Comment by evandrocoan** [comment]
> But there is so much that a team of developers that can be counted with the fingers of one hand can do.

I agree. This is why I think it does not worth much using Cinnamon. While Microsoft has thousands of employers working full time in fixing and optimizing Windows interface, Cinnamon as an open source project can only count with volunteers limited free time. Therefore, to build some desktop environment optimized and fancy like Windows, would be a really hard task.

At home, I use Windows and it has almost a 1% CPU usage footprint, with low memory usage. While at the same time, it is fancy as Cinnamon is. However, Cinnamon uses much more memory, CPU, and has several usability bugs Windows does not have. That is why I am switching to XFCE. By default, it has a low CPU and memory usage, but almost the same usability bugs as Cinnamon. Therefore, would be easier to fix XFCE other than Cinnamon. Although, I will not have a fancy desktop environment for Linux as Windows does.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
