### ISSUE TITLE
Make search provider icons distribution independent

### ISSUE THREAD

**Issue by Fabian42** [linuxmint/cinnamon#8455]
This is an enhancement suggestion, but I don't know how to tag it as such.

The "[apt](https://github.com/linuxmint/cinnamon/tree/master/docs/search-providers-examples/apt%40cinnamon.org)" and "[Wikipedia](https://github.com/linuxmint/cinnamon/tree/master/docs/search-providers-examples/wikipedia%40cinnamon.org)" search providers are missing items on Debian, resulting in an empty image for all Wikipedia search results and a "forbidden" icon for all apt search results.

This behaviour should get changed so that the items always work, for example by falling back an icon included in the folder in case of Wikipedia and/or the standard package manager in case of apt.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
