### ISSUE TITLE
Getting rid of CTRL-ALT-A shortcut

### ISSUE THREAD

**Issue by Davidbrcz** [linuxmint/cinnamon#8456]
```
 * Cinnamon version
Cinnamon 3.6.7
 * Distribution 
Ubuntu 18.04
 * Graphics hardware *and* driver used
GeForce GTX 1050 Ti with Nvidia proprietary drivers Version: 390.116 
 * 32 or 64 bit
64 bits
 ```

**Issue**
I'm using Emacs and when I press CTRL-ALT-A, Cinnamon hijacks the keys and does something weird with my terminals. It bring them all on my current workspace, but there are also some blank ones without anything inside. Pressing again CTRL-ALT-A makes them all disappear.

**Steps to reproduce**
Press CTRL-ALT-A

**Expected behaviour**
Shortcut is not hijacked or can be disabled.

**Comment by icarter09** [comment]
We believe this issue is fixed. Please test against the latest Cinnamon version (4.2). 

https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/
