### ISSUE TITLE
Cinnamon highly loads my CPU after installing nvidia driver

### ISSUE THREAD

**Issue by kolayne** [linuxmint/cinnamon#8457]
```
 * Cinnamon 4.0.9
 * Distro: Linux Mint 19.1 Tessa, base: Ubuntu 18.04 bionic; Kernel: 4.15.0-46-generic x86_64
 * Device-2: NVIDIA GM108M [GeForce 940MX]
 * 64 bit
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
 ```

**Issue**
After installing nvidia driver for my graphic card, cinnamon strongly loads my cpu. It loads much more while playing videos, opening windows and even just typing text!

**Steps to reproduce**
Install nvidia-driver-390

![Screenshot from 2019-03-12 15-08-12](https://user-images.githubusercontent.com/23319866/54203621-a485ae00-44e3-11e9-877c-0dcdc8fe42cb.png)
![Screenshot from 2019-03-12 15-16-02](https://user-images.githubusercontent.com/23319866/54203622-a5b6db00-44e3-11e9-89a2-f2fc4b4e25c5.png)

[syslog.txt](https://github.com/linuxmint/cinnamon/files/2957006/syslog.txt)
[xsession-errors.txt](https://github.com/linuxmint/cinnamon/files/2957007/xsession-errors.txt)

**Comment by leigh123linux** [comment]
File your issue against ubuntu nvidia package.

P.S I didn't even bother looking at your 100000 line syslog.
