### ISSUE TITLE
Feature Request: Change Monitor Refresh Rate in Display Settings

### ISSUE THREAD

**Issue by mindinsomnia** [linuxmint/cinnamon#8458]
It is a common feature of most desktop environments on Linux and other operating systems to include in their display settings an option to view/change the current monitor refresh rate. Currently Mint still does not provide this UI option. This UI would be very beneficial to Mint, as checking and/or changing one's display resolution and refresh rate is often one of the first tasks any user performs upon installing a new OS. In the time since this feature was first requested, monitors with refresh rates higher than 60hz have become very common.

High refresh rate monitors are especially common amongst gamers. Given the increasing popularity of gaming on Linux, and Mint now becoming a recommended "go to distro for beginners" for gamers (and even being recommended by Linus himself from Linus Tech Tips recently), it would be excellent to have this functionality in Mint's display settings before the next wave of new Mint users arrive.

Is there currently an ETA on this functionality? If not, is it possible to establish one or work out a plan for this feature? Is this functionality difficult to add for any particular reason?

I know this feature has been requested multiple times in the past, but there has been no progress on the matter in that time, so I felt it might be best to create a new Issue than revive a dead one.

I took the liberty of creating a mockup for the UI of this feature for roughly what is required. Does anyone have any thoughts on this?

![mock-up-refresh-rate-ui](https://user-images.githubusercontent.com/15921126/54247731-27634300-458e-11e9-84f5-9290b13e8fe2.jpg)

**Comment by Sojiro84** [comment]
As a recent convert to Linux, this was confusing for me as well. Not having a option to set a refresh rate at the display settings.

It should be added since, well, since it makes sense to have it and many people have higher then 60Hz monitors these day's.

I run a script at login to do it now, since after a restart, it defaults back to 60Hz, but a permanent solution would be swell.

**Comment by Nowaker** [comment]
+1. I recently switched from KDE to Cinnamon on my Arch Linux, and now my main monitor runs at 60 Hz instead of 240 Hz. I have a 3 monitor setup, with side monitors at 60 Hz, and the main at 240 Hz. KDE handles this correctly OOTB.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.

**Comment by ccase01** [comment]
> As a recent convert to Linux, this was confusing for me as well. Not having a option to set a refresh rate at the display settings.
> 
> It should be added since, well, since it makes sense to have it and many people have higher then 60Hz monitors these day's.
> 
> I run a script at login to do it now, since after a restart, it defaults back to 60Hz, but a permanent solution would be swell.

I am having difficulty doing this.  I have ASUS pg279Q trying to set it to run at 165.

**Comment by Nowaker** [comment]
It's finally in!

![image](https://user-images.githubusercontent.com/611746/84079617-7c178880-a9a0-11ea-8b7f-076d42e8b9ff.png)

Using Cinnamon 4.6.2 on Arch.
