### ISSUE TITLE
Accessibility: With High Contrast ON, same icon is used for both Show Desktop and Files

### ISSUE THREAD

**Issue by zpangwin** [linuxmint/cinnamon#8461]
```
 * Nemo version (nemo --version) nemo 4.0.6
 * Is issue with desktop or windowed nemo? windowed
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 19.1 Cinnamon x64
 * Graphics hardware *and* driver used
$ inxi -F | grep -i Graphics -A 2
Graphics:  Device-1: NVIDIA GM204 [GeForce GTX 970] driver: nouveau v: kernel 
           Display: x11 server: X.Org 1.19.6 driver: nouveau unloaded: fbdev,modesetting,vesa resolution: 1920x1080~60Hz 
           OpenGL: renderer: NV124 v: 4.3 Mesa 18.2.2 
 * 32 or 64 bit: 64-bit
 ```

Using Linux Mint 19.1 Cinnamon x64; I update my software pretty much daily. I am using the default theme (Mint-Y) and have default Font settings (scaling=1.0).

**Issue**
When using the "High Contrast" mode in Accessibility settings, the panel icons for "Show Desktop" and "Files" (Nemo) are identical, making it difficult for the uninitiated and the forgetful.

**Steps to reproduce**
0. Using 50" LG TV as Display via HDMI if it matters. The system defaulted me to 1920x1080 and I think that resolution looks good on this display.
1. Menu > Preferences > Accessibility > High Contrast = ON
2. The icons look the same and the only way to tell them apart is either via prior knowledge or hovering to see the tooltip text.
3. Have your Grandmother / elderly mother / etc who are more used Windows then try to open a File Manager without help. Odds are good that they'll click the "Show Desktop" icon expecting it to open a File Manager and then be surprised that "nothing happens".

**Expected behaviour**
The show desktop launcher should not display folder icon in High Contrast mode. Personally, I think leaving the regular "Show Desktop" icon and only using the High Contrast icon for "Files" (Nemo) makes sense, but you don't like that idea/not feasible, then a separate distinct icon would be fine too.

**Other information**
I honestly am not entirely sure if this is a Nemo issue, a Cinnamon issue, a GTK issue, a cross-app one, or something else entirely. Cinnamon seemed the most likely but if I apologize if this was added to the wrong place by mistake.

**Comment by zpangwin** [comment]
![uh which-folder-icon](https://user-images.githubusercontent.com/29719631/54400262-62ea3400-4698-11e9-8c77-d79e7347d66e.png)

**Comment by clefebvre** [comment]
Hi @zpangwin, this is a GNOME issue and it should be reported upstream against the hicolor icon theme. The choice of icons for these two separate names (and thus apps/actions) is dictated by the icon theme.

**Comment by zpangwin** [comment]
thanks, sorry for the false positive. will create with gnome team when I get time
