### ISSUE TITLE
[WISH] Button in the network menu to turn off Ethernet

### ISSUE THREAD

**Issue by Chris00** [linuxmint/cinnamon#8463]
* Cinnamon version (cinnamon --version)
Cinnamon 3.8.8
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
Debian testing/unstable
 * Graphics hardware *and* driver used
Intel Corporation Ethernet Connection (4) I219-V (rev 21)
 * 32 or 64 bit
64
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
 *Not relevant*

**Wish**

A button added to the Network Manager dropdown menu to activate/deactivate Ethernet (just as there is one for _Wireless_ and _Mobile Broadband_) would be useful.  Indeed, the Ethernet controller may consume up to 5 Watts significantly reducing battery life (at the moment I do `ifconfig eth0 down` but a button would be more convenient).  An added bonus would be to be offered the choice to turn on/off that button automatically when plugin in/off the power cord.

**Comment by leigh123linux** [comment]
If Debian is missing 'Wired' in the drop down menu I suggest you file an issue at the Debian bug tracker.

![Screenshot from 2019-03-17 20-00-58](https://user-images.githubusercontent.com/1299302/54497226-df2a8480-48ef-11e9-8c14-209157fd6cb9.png)

**Comment by Chris00** [comment]
I'm not speaking of the menu entry but the on/off button to the right.

**Comment by leigh123linux** [comment]
It's a toggle switch!

![Screenshot from 2019-03-17 20-17-42](https://user-images.githubusercontent.com/1299302/54497391-fd917f80-48f1-11e9-990f-9f3b3b3791c1.png)

**Comment by Chris00** [comment]
The toggle button indeed appears when an Ethernet cable is connected.  What I would like is that is keeps being there when it is not — so the card can easily be deactivated in order to save power.
