### ISSUE TITLE
Sound applet should play sound when slider is adjusted

### ISSUE THREAD

**Issue by wyattbiker** [linuxmint/cinnamon#8464]
```
Cinnamon 4.0.9
LM 1.9
 ```

**Issue**
https://github.com/linuxmint/cinnamon/blob/master/files/usr/share/cinnamon/applets/sound%40cinnamon.org/applet.js

See sound applet panel. When sliding scrollbar it should play a sound.  This way user does not have to Launch settings. Thanks!

![image](https://user-images.githubusercontent.com/930478/54497522-0bcfa380-48d2-11e9-86c3-6dc6493440da.png)

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
