### ISSUE TITLE
[Feature Request] Fullscreen to new workspace

### ISSUE THREAD

**Issue by hoshsadiq** [linuxmint/cinnamon#8469]
Would be nice to have an option to move application to a completely new workspace when it goes to full screen. Once the application gets out of full screen, the newly created workspace gets fully destroyed. This is similar in behaviour to what macOS does when maximizing. However, in this case, it's a distinct function from maximizing. Happy to add more information.

**Comment by JosephMcc** [comment]
I'll be honest. I hate this behavior. I've used other DE's that do this and it drives me completely nuts :)

**Comment by hoshsadiq** [comment]
I guess this would have to an option that's disabled by default. Anyway, the maximise button is separate from the full screen above (unlike macOS which requires holding alt to maximise using the same butting or something to that effect).

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
