### ISSUE TITLE
Cinnamon won't prompt me to save unsaved files in editors

### ISSUE THREAD

**Issue by divijan** [linuxmint/cinnamon#8470]
```
 * Cinnamon version (cinnamon --version) 4.0.9
 * Distribution - Arch
 * Graphics hardware *and* driver used - Intel HD Graphics 3000 or, from lspci -v Intel Corporation 2nd Generation Core Processor Family Integrated Graphics Controller, driver: i915
 * 64 bit


 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
 ```

**Issue**
Cinnamon won't prompt me to save any unsaved files when shutting down the computer

**Steps to reproduce**
1. Open any file in Geany or LibreOffice
1. Modify it, but don't save changes
1. Power off the computer from Cinnamon menu

**Expected behaviour**
Cinnamon should ask whether I want to save changes I made to the files

**Other information**
[.xsession-errors renamed for github](https://github.com/linuxmint/cinnamon/files/2999030/xsession-errors.txt)

**Comment by 0lzi** [comment]
Do these Applications ( Geany or LibreOffice ) ask you to save changes if for example you modify then click (x) to close the application without powering off?

**Comment by icarter09** [comment]
@divijan did @0lzi comment help you solve this issue?
