### ISSUE TITLE
grub2 ignores /etc/default/grub settings

### ISSUE THREAD

**Issue by oz42** [linuxmint/cinnamon#8472]
* Cinnamon 4.0.9
 * Mint 19.1 x64

grub-efi-amd64 ignores /etc/default/grub settings:
```
GRUB_DEFAULT=2
# GRUB_TIMEOUT_STYLE=hidden
GRUB_TIMEOUT=3
```

Timeout is still at 30 seconds. I have tried both update-grub (what's this?) and update-grub2

**Comment by oz42** [comment]
GRUB_TIMEOUT_STYLE=hidden is commented out. No idea why it is displayed with large font and without '#'

**Comment by claudiux** [comment]
Did you do a `sudo update-grub` after modifying `/etc/default/grub` ?

FYI a single `#` create a level 1 title (with large font). Please use the 'Insert code' tool and the 'Preview' tab.

**Comment by oz42** [comment]
As I wrote, I have tried both update-grub2 and update-grub

**Comment by JosephMcc** [comment]
I'm closing this since the issue shouldn't be related to Cinnamon at all. It doesn't stop you from discussing it.

A better place for general mint bugs would be here: https://github.com/linuxmint/linuxmint/issues

The Mint forums might actually be the best place to get help with this sort of issue.
