### ISSUE TITLE
Circumflex and accents do not work properly with Swiss French keyboard layout

### ISSUE THREAD

**Issue by domeckert** [linuxmint/cinnamon#8474]
```
 * Cinnamon version 4.0.9
 * Distribution - Mint 19.1
 * Graphics hardware *and* driver used: Intel Corporation UHD Graphics 620, Default driver
 * 64 bit
 ```

**Issue**
Circumflex and accents do not work properly with Swiss French keyboard layout. 

**Steps to reproduce**
To get the "e" with circumflex ("ê"), I need to press "^" and then "e"; instead, I get "^e".

**Comment by NikoKrause** [comment]
It works here. Tried with LibreOffice Writer pressing the red button (see below image) and then `e`, I get `ê` .
![screenshot-window-2019-04-21-002600](https://user-images.githubusercontent.com/8415124/56463001-96715a00-63cc-11e9-986b-9ecf48e4a288.png)

Are you sure you're using "French (Switzerland)" (Französisch (Schweiz)).

**Comment by domeckert** [comment]
Still doesn't work here. The keyboard layout is set and the other keys are working correctly. Just tried with LibreOffice and get the same as before.
![Screenshot from 2019-04-21 16-37-01](https://user-images.githubusercontent.com/47885645/56471527-e7786100-6453-11e9-950f-bba250cf73dc.png)

**Comment by NikoKrause** [comment]
Photo of your keyboard?
