### ISSUE TITLE
PDF/Images archives on desktop don't align

### ISSUE THREAD

**Issue by wolnerberg** [linuxmint/cinnamon#8475]
```
 * Cinnamon version 4.0.10 (all 4.X.X series too)
 * Distribution - Mint 19.1 (all 4.X.X series too)
 * Graphics hardware *and* driver used Intel Corporation Haswell-ULT Integrated Graphics Controller (using generic driver)
 * 64 bit
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
no erros
 ```

**Issue**
PDF and image archives on desktop don't align icons. They align on first use, but, on restart or log off, don't align.

**Steps to reproduce**
Put some pdf /images archives on desktop and restarting computer/session some times.

**Expected behaviour**
On put the pdfs/images on desktop, all is ok. But on restart computer or session, the icons on desktop don't align.

**Other `information**`
Image of problem here: https://photos.app.goo.gl/PhBfTvRsSig5AxxDA

**Comment by icarter09** [comment]
Linux Mint 19.2
Cinnamon 4.2.4

I'm not able to reproduce this issue. I also have several image and pdf files on my desktop and have not noticed them realigned after a restart.

@wolnerberg are you still experiencing this issue?
