### ISSUE TITLE
gnome-terminal removes space af

### ISSUE THREAD

**Issue by Redsandro** [linuxmint/cinnamon#8476]
I have no idea where to post this issue. GNOME is [very clear](https://wiki.gnome.org/Apps/Terminal/ReportingBugs) in explaining non-GNOME-devs need to report this to their distro's tracker. They list Linux Mint [over here](https://wiki.gnome.org/Bugsquad/TriageGuide/NonGnome#Bug_trackers_for_distributions), but when I [go there](https://bugs.launchpad.net/linuxmint) and log in I cannot see or open issues. Here on Github I see no place for GNOME apps. Please be respectful of the confusion, and kindly place a link to the right location if this is the wrong place.

---

On Linux Mint 19 Cinnamon 3.8.9, running `gnome-terminal` version `3.28.1-1ubuntu1mint2`, some emoji symbols take up zero space.

Copy this text:

> ```
> # icon: 📎 [paperclip]
> # icon: ✉️ [envelope]
> # icon: 📩 [arrow]
> ```

Paste it in `geany`:

![image](https://user-images.githubusercontent.com/1702193/55092206-6cb96180-50b2-11e9-88e0-d7652fa94aec.png)

Paste it in `gnome-terminal`:

![image](https://user-images.githubusercontent.com/1702193/55092301-a2f6e100-50b2-11e9-9bd1-3e4db9f75bb2.png)

See the space after the envelope icon.

With characters, you can see this even better:

![image](https://user-images.githubusercontent.com/1702193/55092554-0c76ef80-50b3-11e9-8902-fbfe70a392b8.png)

**Comment by JosephMcc** [comment]
You can report this here if you like but my guess is that this is a problem in gnome-terminal itself: https://github.com/linuxmint/linuxmint

It isn't a Cinnamon specific problem though.

**Comment by Redsandro** [comment]
> It's not a gnome-terminal or vte problem, but a problem with your font. It displays ✉️ as a wide character (width 2) using emoji presentation, but this character is narrow (width 1).

https://gitlab.gnome.org/GNOME/gnome-terminal/issues/187#note_657460

The problem appears to be with the monospace regular font.
