### ISSUE TITLE
[feature request] screen annotation tool

### ISSUE THREAD

**Issue by tethragon** [linuxmint/cinnamon#8484]
I use Linux mint 19.1 (cinnamon) for my work at home. I also use it at school (I am a teacher) for educational purposes. Unfortunatelly there is not a single one screen annotation tool for annotating the screen. I read recently that such a tool was released for gnome shell ( https://www.omgubuntu.co.uk/2019/03/draw-on-your-screen-ubuntu-linux ). Since annotating the screen is a very usefull feature for education I hope that cinnamon developers could also implement it for cinnamon

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
