### ISSUE TITLE
Cinnamon 19.1 Software Rendering Mode Only with VirtualBox 6.0.4

### ISSUE THREAD

**Issue by StevenBBryant** [linuxmint/cinnamon#8489]
```
 * Cinnamon version (cinnamon --version): 19.1
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...): Cinnamon 19.1
 * Graphics hardware *and* driver used: VirtualBox
 * 32 or 64 bit: 64-Bit
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
 ```

**Issue**
The primary issue is that I cannot remove the "Running in Software Rendering Mode" message from my Cinnamon installation. I have clicked the 3D Acceleration button on the display tab of the VirtualBox 6.0.4.  I have also run the VirtualBox Guest Extensions 6.0.4.  If I run the VBGE more than once, I am unable to get the screen to properly render when in VGA. I can get it to render in SVGA, but in that case I still get the software rendering messages.

Notes that this problem does not occur on my Ubuntu 18.04 and Linux Mint Mate 19.1 installations that were performed using the same process. I have been able to reinstall both of these other systems fine. It is only Cinnamon that I can't seem to get beyond this point.  Because this has been reported previously on various blog sites, I believe that it is either user error on my part, or is related to the Cinnamon implementation.

Here is some information about the installation:
=========================================================
System:
  Host: myUserName-VirtualBox Kernel: 4.15.0-47-generic x86_64 bits: 64 
  compiler: gcc v: 7.3.0 Desktop: Cinnamon 4.0.10 wm: muffin dm: LightDM 
  Distro: Linux Mint 19.1 Tessa base: Ubuntu 18.04 bionic 
Machine:
  Type: Virtualbox System: innotek product: VirtualBox v: 1.2 
  serial: <filter> Chassis: Oracle Corporation type: 1 serial: <filter> 
  Mobo: Oracle model: VirtualBox v: 1.2 serial: <filter> BIOS: innotek 
  v: VirtualBox date: 12/01/2006 
Battery:
  ID-1: BAT0 charge: 49.0 Wh condition: 50.0/50.0 Wh (100%) volts: 10.0/10.0 
  model: innotek 1 serial: N/A status: Unknown 
CPU:
  Topology: Quad Core model: Intel Core i7-8650U bits: 64 type: MCP 
  arch: Kaby Lake rev: A L2 cache: 8192 KiB 
  flags: lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 bogomips: 16895 
  Speed: 2112 MHz min/max: N/A Core speeds (MHz): 1: 2112 2: 2112 3: 2112 
  4: 2112 
Graphics:
  Device-1: InnoTek Systemberatung VirtualBox Graphics Adapter 
  vendor: VMware driver: N/A bus ID: 00:02.0 chip ID: 80ee:beef 
  Display: x11 server: X.Org 1.19.6 driver: vesa unloaded: fbdev,modesetting 
  alternate: vboxvideo resolution: 1024x768~61Hz 
  OpenGL: renderer: llvmpipe (LLVM 6.0 256 bits) v: 3.3 Mesa 18.0.5 
  compat-v: 3.0 direct render: Yes 
Audio:
  Device-1: Intel 82801AA AC97 Audio vendor: Dell driver: snd_intel8x0 
  v: kernel bus ID: 00:05.0 chip ID: 8086:2415 
  Sound Server: ALSA v: k4.15.0-47-generic 
Network:
  Device-1: Intel 82540EM Gigabit Ethernet driver: e1000 v: 7.3.21-k8-NAPI 
  port: d010 bus ID: 00:03.0 chip ID: 8086:100e 
  IF: enp0s3 state: up speed: 1000 Mbps duplex: full mac: <filter> 
  Device-2: Intel 82371AB/EB/MB PIIX4 ACPI type: network bridge 
  driver: piix4_smbus v: N/A port: d200 bus ID: 00:07.0 chip ID: 8086:7113 
Drives:
  Local Storage: total: 20.00 GiB used: 7.36 GiB (36.8%) 
  ID-1: /dev/sda vendor: VirtualBox model: VBOX HARDDISK size: 20.00 GiB 
  speed: 3.0 Gb/s serial: <filter> 
Partition:
  ID-1: / size: 19.56 GiB used: 7.36 GiB (37.6%) fs: ext4 dev: /dev/sda1 
Sensors:
  Message: No sensors data was found. Is sensors configured? 
Repos:
  No active apt repos in: /etc/apt/sources.list 
  Active apt repos in: /etc/apt/sources.list.d/official-package-repositories.list 
  1: deb http://packages.linuxmint.com tessa main upstream import backport #id:linuxmint_main
  2: deb http://archive.ubuntu.com/ubuntu bionic main restricted universe multiverse
  3: deb http://archive.ubuntu.com/ubuntu bionic-updates main restricted universe multiverse
  4: deb http://archive.ubuntu.com/ubuntu bionic-backports main restricted universe multiverse
  5: deb http://security.ubuntu.com/ubuntu/ bionic-security main restricted universe multiverse
  6: deb http://archive.canonical.com/ubuntu/ bionic partner
  7: deb https://download.virtualbox.org/virtualbox/debian bionic contrib
Info:
  Processes: 183 Uptime: 3m Memory: 3.85 GiB used: 599.4 MiB (15.2%) 
  Init: systemd v: 237 runlevel: 5 Compilers: gcc: 7.3.0 alt: 7 Shell: bash 
  v: 4.4.19 running in: gnome-terminal inxi: 3.0.27 
==============================================================

**Steps to reproduce**
Create VM - enable 3D Acceleration
Installed Linux Mint on VB 6.0.4.
Perform updates
Reboot
Install Virtual Box Guest Extensions from within Cinnamon
Reboot

**Expected behaviour**
I would expect the software rendering message to go away.

**Other information**

**Comment by StevenBBryant** [comment]
Adding syslog:
[syslog.txt](https://github.com/linuxmint/cinnamon/files/3036870/syslog.txt)

**Comment by claudiux** [comment]
## Virtualbox settings: 
### System/Processor

Check "Enable PAE/NX"

### Display/Screen
Check "Enable 3D Acceleration"

Uncheck "Enable 2D Video Acceleration"

Then run your virtual machine.

## In the virtual machine
`sudo apt-get remove virtualbox-guest-utils`

Then, "insert guest addons CD".

Do not auto run. Open the CD contents in a terminal, then:
`sudo ./VBoxLinuxAdditions.run`

Restart your virtual machine.

**Comment by StevenBBryant** [comment]
Unfortunately, this did not resolve the issue.  Attempted a fresh install using the settings and sequence below. Interestingly, after doing this sequence the screen is simply black after looking into Cinnamon. Yet, in the “Preview” area of the VM manager, it appears to show a thumbnail view of that should be displayed on Cinnamon.

My steps:

  1.  Create new VM Guest System named “Cinnamon”.  4GB RAM, 20GB Disk, 4 processors, Enabled PAE/NX , 128MB Video Memory, VBoxVGA (graphics controller), and 3D Acceleration. 2D is left unchecked.
  2.  Install Mint using default options. Have tried with and without 3rd party software installation. Doing it now, without.
  3.  [Optional] Here I have tried two cases: performing system updates vs not performing system updates.
  4.  Performed the apt-get remove statement, but it doesn’t look like anything was removed:
Reading package lists… Done.
Building dependency tree
Reading state information … Done
Package ‘virtualbox-guest-utils’ is not installed, so not removed
0 upgraded, 0 newly installed, 0 to remove and 341 not upgraded

  1.  Installed the Guest Additions CD (selected ‘cancel’ instead of ‘run).
  2.  Perform sudo reboot
  3.  Screen is black. However, the Preview area of the VM Manager app shows a thumbnail view.

I’m happy to try to troubleshoot further if there are additional suggestions. I’m afraid I’m not sure how to proceed from here.

**Comment by StevenBBryant** [comment]
Update: Runs on Laptop Monitor alone, but not through graphics-card based docking station.

I think I've been able to successfully troubleshoot the problem; which is partially good news. My laptop was running through a graphics card enabled docking station. For some reason, the Cinnamon implementation isn't happy with this configuration, which works with Ubuntu and Mint Mate. Interestingly, once I disconnected my laptop from the docking station, Cinnamon performed as expected on the laptop's display.

I don't know what specifically is the limiting factor in this configuration.  Happy to troubleshoot further if you can tell me what information you need.

**Comment by StevenBBryant** [comment]
Update 2: Works fine under VMWare. This suggests the problem is with VirtualBox and beyond the scope of the Cinnamon team for complete resolution.

A few lessons learned:
- In VMWare, scrolling does not work with a Logitech USB mouse if the "Smooth Scrolling" option is enabled in the host system. Turning this off ill enable scrolling in the guest system.
- The combination of Cinnamon, VirtualBox, and an eGPU (specifically the Lenovo Graphics Dock) may not work. (I say "may not", because it certainly could be something on my end). In this case, move to a different Linux Mint edition (eg, Mate) or to a different VM Manager (eg, VMWare).

**Comment by StevenBBryant** [comment]
I'm going to close this out. If we want to open a new one associated with eGPUs with VirtualBox, we should do so under it's own issue ID.

Thank you to the Mint Development Team! Appreciate your product and your nudge that helped me to resolve this issue.
