### ISSUE TITLE
[feature request] - Make it optional to have back buttons in every settings window

### ISSUE THREAD

**Issue by apandada1** [linuxmint/cinnamon#8490]
```
 * Cinnamon version - 4.0.10
 * Distribution - Mint 19.1
 * Graphics hardware *and* driver used - Intel Corporation Skylake GT2 [HD Graphics 520]
 * 64 bit
```

**Issue**
When a particular settings is opened (say `applets`) from `system settings`, there is a back button to go back. However, when `applets` is opened from menu, there is no back button. 
![mint](https://user-images.githubusercontent.com/3063132/55461135-5448ca00-5611-11e9-8e25-a6b89912f9d5.png)

**Steps to reproduce**
Open any settings directly from menu, it won't have the back button.

**Expected behaviour**
Each setting should have a back button to go to system settings irrespective of how they were opened.

**Other information**
This feature was available in older versions of Cinnamon (at least in Mint 18.2), and it was very helpful to be able to go back and forth between different settings without having to separately search for them in the menu or to open system settings.

**Comment by Odyseus** [comment]
Hello, @apandada1.

This was already reported in #8444. And the change was introduced in #8146, where it is explained the motive of the change.

**Comment by apandada1** [comment]
Ok. Can any option (need not be default) be provided to include the back button in every window? Sure, it will make some applications not look like standalone. But it will certainly

**Comment by apandada1** [comment]
Can some option (need not be default) be provided to include the back button in every window? Sure, it will make some applications not look like standalone. But it will certainly enrich the user experience (at least for many users).

**Comment by feren** [comment]
I'd say turn this issue into a feature request in that case about the option in DCONF Editor to restore the original behaviour to see how many people support such an idea...

**Comment by JosephMcc** [comment]
Odyseus gave a good answer here. There is already an open issue to bring this back. This has been discussed by the devs and we will see what happens but it won't come back as some optional setting. It will either be there or it won't.

**Comment by freeseacher** [comment]
please let it be.
