### ISSUE TITLE
Menus flicker when "Fly down, up" effects style is set

### ISSUE THREAD

**Issue by bbbco** [linuxmint/cinnamon#8491]
```
 * Cinnamon version (cinnamon --version)
 ** Cinnamon 4.0.10
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
 ** Mint 19.1 Cinnamon
 * Graphics hardware *and* driver used
 ** Radeon HD 5000/6000/7350/8350 Series
 ** driver=radeon
 * 32 or 64 bit
 ** 64 bit
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
 ```

**Issue**
After upgrading to LM 19.1 (from 18.2/3), menus sporadically flicker when clicked (either left or right clicked) when the "Effects on menus" is enabled and "Effects Style" is set to "Fly down, up".

See attached screencast GIF courtesy of `peek`.
![Peek 2019-04-03 11-30](https://user-images.githubusercontent.com/30680/55492922-0b3f4880-5606-11e9-90de-04b8a8b56596.gif)

Note, that menu bar panels are not affected as seen in the screencast. Also, this issue doesn't just occur in context menus (via right click), but also in application menus.

I have also tested the other effect styles, and they all seem to work normally. This is the only effect that seems to be affected.

**Steps to reproduce**

* Click Start Menu > (Search for and open) Effects
* Ensure "Effects on menus" is enabled
* Ensure "Effects style" is set to "Fly down, up"
* Try clicking on normal menus and notice that they sporadically flicker away and back. Also notice that it is difficult to select menu options with this happening.

**Expected behaviour**
* When the "Fly down, up" menu effect is enabled:
  * Menus retain their rendering and do not flicker 
  * Menu options are able to be selected without issues

**Other information**

**Comment by mabod** [comment]
I can confirm this behaviour:

* Cinnamon 4.0.10
* Manjaro testing
* nvidia 418.xx

**Comment by JosephMcc** [comment]
This should be fixed now on cinnamon master
