### ISSUE TITLE
grouped windows list - thumbnails disappearing

### ISSUE THREAD

**Issue by mygrandmawheels** [linuxmint/cinnamon#8498]
```
 * Cinnamon 4.0.10
 * Distribution - Linux Mint 19.1 Tessa 
 * nvidia gtx 750 ti - nvidia driver 390
 * 64 bit
 ```

**Issue**
in some circumstances, fixed thumbnails on grouped windows list disappear, preventing from use them as quick-launch shortcut

**Steps to reproduce**
open normally an app launching from GWL thumbnail, for example Nemo; it opens the Home dir.
Now open another Nemo session with right click over the same GWL thumbnail, popup appear, choose "Home" another time.
Click on the first Nemo session opened, and close the window.
Now click on the second Nemo session: the thumbnail on GWL toolbar disappear until I logoff-login again. 

**Expected behaviour**
If I have fixed thumbnails on the GWL, it must be at least one of them in the bar.

**Other information**
same problem with other app, for example Firefox

**Comment by jaszhix** [comment]
Are you using the nightly PPA?

**Comment by mygrandmawheels** [comment]
No, I only update Linux Mint regularly as the new updates are available

**Comment by mygrandmawheels** [comment]
Oops! I’m new to this,I closed erroneously!

**Comment by mygrandmawheels** [comment]
Anyway,no, I only update my Linux mint regularly when an update is available

**Comment by ACheshirov** [comment]
I have the same problem. I couldn't reproduction the bug but sometimes thumbnails just disappear and I have to restart Cinnamon in order to fix it.

**Comment by icarter09** [comment]
@ACheshirov @mygrandmawheels are either of you still experiencing this issue?
