### ISSUE TITLE
Black screen after login in public Wifi which requires authentication

### ISSUE THREAD

**Issue by andreikop** [linuxmint/cinnamon#8504]
```
 * Cinnamon 3.6.7
 * Linux Mint 18.3 Sylvia
 * 64 bit
Wifi card:           
       description: Wireless interface
       product: Wireless 8265 / 8275
       vendor: Intel Corporation
       physical id: 0
       bus info: pci@0000:03:00.0
       logical name: wlp3s0
       version: 78
       serial: e4:70:b8:b5:70:0c
       width: 64 bits
       clock: 33MHz
       capabilities: bus_master cap_list ethernet physical wireless
       configuration: broadcast=yes driver=iwlwifi driverversion=4.10.0-38-generic firmware=22.391740.0 ip=192.168.43.153 latency=0 link=yes multicast=yes wireless=IEEE 802.11
       resources: irq:132 memory:f1200000-f1201fff

 ```
I tried to boot my laptop in a cafe which has "public" wifi but asks for authentication in a browser when user tries to open some web site.
After login I see just black screen and movable cursor.

The problem is very critical, because it makes a laptop totally unusable. And it is almost impossible to diagnose it. I guessed right that this is Wifi problem because I've already had this problem once in the other cafe and it disappeared after I returned home.

Which information I can provide to help to diagnose the problem?

**Comment by icarter09** [comment]
We believe this issue is fixed. Please test against the latest Cinnamon version (4.2). 

https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/
