### ISSUE TITLE
[feature request] Add applet password entry field

### ISSUE THREAD

**Issue by nmate91** [linuxmint/cinnamon#8505]
```
 * Cinnamon version (4.0.10)
 * Distribution - (Mint 19.1)
 ```

**Issue**
In applets, you cannot create a password entry field, just a simple entry.
https://github.com/linuxmint/Cinnamon/wiki/Applet,-Desklet-and-Extension-Settings-Reference

For example, this feature would be nice here:

![image](https://user-images.githubusercontent.com/20420558/55809425-31715680-5ae6-11e9-8d0c-75db7df11a6d.png)

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
