### ISSUE TITLE
Network settings window content does not resize vertically together with window

### ISSUE THREAD

**Issue by jm4R** [linuxmint/cinnamon#8507]
```
 * Cinnamon version 4.0.10
 * Distribution - Mint 19.1
 * Graphics hardware *and* driver used NVidia GTX 1060
 * 64 bit
 ```

**Issue**

Network settings window content does not resize vertically together with window. It starts with initial size that hides most of its content.

**Steps to reproduce**

Open "Network settings" from tray icon.

**Expected behaviour**

Content of window should be resized together with the window. The initial height of window should be greater to show all information.

**Other information**
None

**Comment by smurphos** [comment]
Duplicate #8360
