### ISSUE TITLE
Cinnamon does not update workspace names to match changes in Dconf until cinnamon is restarted

### ISSUE THREAD

**Issue by BeatLink** [linuxmint/cinnamon#8508]
**Issue**
Cinnamon does not update workspace names on change of  org.cinnamon.desktop.wm.preferences workspace-names in dconf or gsettings.

**Steps to reproduce**
Run `gsettings set org.cinnamon.desktop.wm.preferences workspace-names "['hello', 'world']"` in a terminal

**Expected behaviour**
* Dconf settings are updated
* Cinnamon updates the workspace names according to dconf schema description (names in excess are ignored, unspecified names are replaced with the default "Workspace N"

**Actual Behavior**
* Dconf settings are updated
* Cinnamon does not update the workspace names unless it is restarted either by logging out or restarting cinnamon itself. 

**Other information**
The number of workspaces, managed by `org.cinnamon.desktop.wm.preferences num-workspaces` is automatically updated in real time.

**Comment by clefebvre** [comment]
I think that's ok. Put together there's a cost involved in listening to changes when it comes to the performance of the DE. If a listener isn't necessary for the DE to work properly we shouldn't add it.

**Comment by BeatLink** [comment]
It does add a useful feature however. Not to mention, the number of workspaces is already polled for changes.
