### ISSUE TITLE
Linux Mint 19.1 Tessa 64-bit - Frozen - Also effecting Boot Options - Hardware Issue?

### ISSUE THREAD

**Issue by bridgetsarah** [linuxmint/cinnamon#8510]
```
 * Cinnamon version (Linux Mint 19.1 Tessa 64-bit )
 * AMD A10-4655M APU with Radeon(tm) HD Graphics × 4 
 * 64 bit
 * 8GB Ram
[syslog.txt](https://github.com/linuxmint/cinnamon/files/3076072/syslog.txt)


 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
 ```

**Issue**
I was using Microsoft Visual Studio and Chrome, as per normal nothing out of normal. Had left my machine for a few minutes back and forward, sat down with daughter to return and then I started hearing this noise. Came into room to find noise coming from laptop as well as the screen frozen, gridlines on both screens which seemed like a GUI issue..

https://twitter.com/BridgetSarah2/status/1116976267599937537 (Video of it happening, and listen to audio please)

My machine is setup to duel boot, Windows 10 and Linux this version,  and grub always comes on and so i select mint.. This time when I did try to login, it froze, then I tried going into bios options.. and this is where it went weird. My Bios was only reading 4GB out of 8GB.

So  at this point tried booting windows.. also issues would not logon at all, kept freezing.  I then unscrewed the back panel to see if memory had over heated, removed and put back in and seems to been okay since apart from HPs recovery software forcing a recovery setup.

After that tried almost every key on my keyboard to boot Linux, and eventually showed up as "Linux Ubuntu".. and then gave me the option of Grub to boot Linux mint. 

Could you please look into this as its the most weirdest issue I've ever come across. 

**Other information**

**Comment by bridgetsarah** [comment]
[syslog.txt](https://github.com/linuxmint/cinnamon/files/3076077/syslog.txt)

**Comment by bridgetsarah** [comment]
![20190413_110815](https://user-images.githubusercontent.com/37039357/56078333-b4442b00-5dde-11e9-8e62-75412cd8a380.jpg)
![20190413_101800](https://user-images.githubusercontent.com/37039357/56078334-b60dee80-5dde-11e9-9154-cac271bd92a3.jpg)
![20190413_102253](https://user-images.githubusercontent.com/37039357/56078335-b73f1b80-5dde-11e9-8d06-7c1a37c83e09.jpg)
![20190413_102619](https://user-images.githubusercontent.com/37039357/56078336-b8704880-5dde-11e9-9730-409a800cb513.jpg)

**Comment by leigh123linux** [comment]
Looks like you need to boot Windows O/S and clean the affected drive, if it's defined in /etc/fstab it will cause linux bootup issues.

```
Apr 13 11:13:07 bridgetsarah udisksd[965]: The disk contains an unclean file system (0, 0).
Apr 13 11:13:07 bridgetsarah udisksd[965]: Metadata kept in Windows cache, refused to mount.
Apr 13 11:13:07 bridgetsarah udisksd[965]: Falling back to read-only mount because the NTFS partition is in an
Apr 13 11:13:07 bridgetsarah udisksd[965]: unsafe state. Please resume and shutdown Windows fully (no hibernation
Apr 13 11:13:07 bridgetsarah udisksd[965]: or fast restarting.)
Apr 13 11:13:07 bridgetsarah ntfs-3g[9179]: Version 2017.3.23 integrated FUSE 28
Apr 13 11:13:07 bridgetsarah ntfs-3g[9179]: Mounted /dev/sda4 (Read-Only, label "", NTFS 3.1)
Apr 13 11:13:07 bridgetsarah ntfs-3g[9179]: Cmdline options: rw,nodev,nosuid,uid=1000,gid=1000,uhelper=udisks2
Apr 13 11:13:07 bridgetsarah ntfs-3g[9179]: Mount options: rw,nodev,nosuid,uhelper=udisks2,allow_other,nonempty,relatime,ro,default_permissions,fsname=/dev/sda4,blkdev,blksize=4096
```

**Comment by JosephMcc** [comment]
Closing this since it doesn't really seem like a Cinnamon issue. It's a weird one, I'll say that :) But it seems more like a hardware issue.
