### ISSUE TITLE
[Feature Request] Auto switch between dark and light theme for sunshine/sunset

### ISSUE THREAD

**Issue by kelebek333** [linuxmint/cinnamon#8511]
Hi, could you add automatic theme switch feature for sunshine and sunset?

![light-dark](https://user-images.githubusercontent.com/1300133/56085070-0704fd80-5e46-11e9-81aa-044eeb6b8b16.png)

**Comment by invexx** [comment]
That would be useful if it was geolocation aware, imho. Just like Redshift is.

**Comment by kelebek333** [comment]
> That would be useful if it was geolocation aware, imho. Just like Redshift is.

Switching with sunset and sunrise always may not be suitable.

Developers can look at this application to get inspired. https://github.com/C2N14/AutomaThemely
