### ISSUE TITLE
When will he support Wayland Cinnamon? (curiosity)

### ISSUE THREAD

**Issue by xzj8b3** [linuxmint/cinnamon#8512]
For information purposes, when will Wayland Cinnamon be supported?? Is something already planned for a primary test on Fedora?

**Comment by leigh123linux** [comment]
Cinnamon doesn't have any wayland support, even if it did don't expect me to enable it in fedora.
I have absolutely zero interest in a protocol that has so many shortcomings.

**Comment by xzj8b3** [comment]
> Cannella non ha alcun supporto via terra, anche se non si aspettava che io lo abilitassi in fedora. 
> Ho assolutamente zero interesse per un protocollo che ha così tanti difetti.

Well, it'll get better.

In fact I'm also thinking about Mint Debian for the future, only newer Kernels with my hardware run better and Fedora is more up to date, indeed I really appreciate its continuous expansion of proprietary repositories that never have any 'conflict!!!!!

**Comment by leigh123linux** [comment]
@xzj8b3  There is only one safe media/proprietary repo for Fedora, users that stray away from rpfusion repo should expect issues.

> In fact I'm also thinking about Mint Debian for the future,


LOL, the Debian base is rotten to the core with it's ancient package versions and broken policies.

**Comment by xzj8b3** [comment]
> @ xzj8b3 C'è un solo repository sicuro / repository proprietario per Fedora, gli utenti che si allontanano dal repository di rpfusion dovrebbero aspettarsi dei problemi.
> 
> > In effetti sto pensando anche a Mint Debian per il futuro,
> 
> LOL, la base Debian è marcio fino al midollo con le sue antiche versioni dei pacchetti e le politiche non funzionanti.

Well we'll see Fedora 30 will also bring Deepin that I'd like to try, but to me Cinnamon won me over already from its first betas and install it on Fedora is a moment and it's fine!!!

We'll see what happens Fedora is not bad at all and has a very active team at every report of problems, I really like that!!!

**Comment by JosephMcc** [comment]
Closing this since it isn't really an issue and the question was answered.

**Comment by giaur500** [comment]
I agree. You want to die with Xorg together. We must let you to do that. When it happens (soon), still there are alternatives.
