### ISSUE TITLE
Cinnamon desktop still broken in Fedora 29

### ISSUE THREAD

**Issue by drmcnelson** [linuxmint/cinnamon#8514]
```
 * Cinnamon version (cinnamon --version)  muffin 4.0.7-1.fc29
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)  Fedora 29
 * Graphics hardware *and* driver used     Intel Corporation Xeon E3-1200 v2/3rd Gen Core processor Graphics Controller (rev 09)
 * 32 or 64 bit    64bit
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
[xsession-errors.txt](https://github.com/linuxmint/cinnamon/files/3078030/xsession-errors.txt)
 ```

**Issue**
After running for some time, the desktop and contents of windows become sluggish and video becomes jumpy.

After  alt-f2 and "r",  the system runs normally for a while.

**Steps to reproduce**
Use cinnamon desktop as usual,  open a few windows.  It seems to happen for any mix of windows. 

However, just now, the mix was evince, two xterms, one nemo, one libre calc, one thunderbird, and one firefox.   The mouse and scrolling as jumpy everywhere and in a firefox window with youtube showing france 24, the video was jumpy.

Alt-f2 took a few minutes to produce the terminal window prompt.  Entering "r" however returned the system to normal.

**Expected behaviour**
Should continue to operate smoothly.

**Other information**

**Comment by JosephMcc** [comment]
I know this is probably a frustrating issue for you. However it seems not many are suffering from it and I've never seen it personally. This makes it very hard for us to troubleshoot and try to improve. And you aren't providing  with enough useful information.

**Comment by drmcnelson** [comment]
I figured out how to send the reset from the command line, so that is my 
work around.

If you look back through the bug reports, you can see that it has been 
going on for a very long time and through multiple releases.

If you give me specific commands to dump logs for you, I am happy to 
send them.
