### ISSUE TITLE
[Feature request] Hide startup applications window like in OSX (solution provided)

### ISSUE THREAD

**Issue by fermmm** [linuxmint/cinnamon#8518]
I have to close 8 of my startup applications' windows when booting Mint, I have to close them one by one at least I boot twice a day. I need them to open "closed to the tray icon", I don't want them appearing all at once on startup. This makes me feel I'm using an OS that is not made with much love. Some applications has a "start closed to tray" setting that only works on the Microsoft Windows port of the application.

In OSX you have a "hide" checkbox in the startup applications menu. Something like that on Cinnamon would be great (see my solution below).

![3-Macs-Login-Items-](https://user-images.githubusercontent.com/3660373/56165442-5e6fae80-5fa9-11e9-95b0-7b43b8d5ea67.png)

**Solution:**
I coded a script to do this and then I understood why this is not yet implemented as an OS feature, it's more complicated than it seems: Some applications like slack, opens a splash screen, if my script closes the splash screen then the application does not start, if hides the splash screen instead of closing it, then the application window appears and it's not hidden, so only the second screen that opens should be closed for that specific application. Also some other applications like teamviewer cannot be closed, only hidden, otherwise the tray icon does not appear, other applications can't be hidden because will not appear anymore, other applications like steam opens many windows.

I solved all the issues with my script but with a cost: It's not as simple as in OSX, you need to specify as an argument when running the script if your application has a splash screen, and also if you want it to be closed or hidden, one works for some applications and not the others, so you must do one trial and error attempt before getting it to work for some applications. The good news is that 80% of the applications I've tried used the same configuration without the need of trial and error.
[This is my script with more information](https://askubuntu.com/a/1133211/943954)

This is over complicated to the final user compared to OSX, you would have 3 checkboxes instead of 1: "Close window after run" that shows: "Skip splash screen" and "Hide instead of close", not perfect but it's better than having to close all the windows every day.
If this gets fixed it would be the first distro to fix it.

**Comment by smurphos** [comment]
I think you need to review the command line options for the applications you are autostarting to see if the applications offers a command line option to open in the background or open to tray and if it does use that options  as your autostart command.

E.g I have Chrome in my startups (to get Gmail and Calendar notifications)  with `google-chrome-stable --no-startup-window` Failing that some apps will offer options in their preferences to open minimised or to the tray.

How to review what command line options are available to use in your autostarting applications? Normally either via  `<command>  --help` or `man <command>`

Slack for example offers a -u or --startup option. On linux it opens it to the tray and minimised with no splash screen.

**Comment by fermmm** [comment]
> I think you need to review the command line options for the applications you are autostarting to see if the applications offers a command line option to open in the background or open to tray and if it does use that options as your autostart command.
> 
> E.g I have Chrome in my startups (to get Gmail and Calendar notifications) with `google-chrome-stable --no-startup-window` Failing that some apps will offer options in their preferences to open minimised or to the tray.
> 
> How to review what command line options are available to use in your autostarting applications? Normally either via `<command> --help` or `man <command>`
> 
> Slack for example offers a -u or --startup option. On linux it opens it to the tray and minimised with no splash screen.
@smurphos 
Slack has this parameters but not the other applications I run on startup. Also the user should not be investigating parameters to be able to achieve this.

**Comment by JosephMcc** [comment]
Thanks for the request but I think you've seen for yourself how difficult this is. Things like this end up being even more complicated to implement and keep working for all the various apps that people use then it is for a user just to close them :) Applications themselves really need to support this.
