### ISSUE TITLE
[Feature request] Tweak the start menu sort

### ISSUE THREAD

**Issue by jontymorris** [linuxmint/cinnamon#8519]
```
 * Cinnamon 4.0.10
 * Distribution - Mint 19.1
 * 64 bit
 ```

Hello, I have some feedback on the start menu. I love the overall experience but would like to recommend a tweak to how the start menu search results are sorted. I've noticed that the first result isn't always relevant to what I'm searching for.

Let's say you have Visual Studio Code installed and added to your start menu. In a rush, you tap the super key and type in 'Visual', in an attempt to find 'Visual Studio Code'. However, the first result in the start menu is 'Effects'. 

I understand that the Effects program must have 'Visual' as an alias, and it seems the search results are ordered alphabetically.

So what if we tweaked it so the alphabetical order is kept, but the item with the best match is selected instead of the first item at the top. (In my example, keep Effects at the top but have Visual Studio Code the selected option)

**Comment by NikoKrause** [comment]
@germanfr :)

**Comment by JosephMcc** [comment]
Thank you for the suggestion. This is an area we are always looking at improving but can be complicated to do without effecting the menu performance.
