### ISSUE TITLE
Problem after changing font size

### ISSUE THREAD

**Issue by pmarcelll** [linuxmint/Cinnamon#852]
After changing the font size in Cinnamon Settings, the font size of the desktop icon text doesn't change, only after moving the cursor over them/clicking them.

I'm using Cinnamon 1.4.0-UP3-20120630044007-precise nightly build on Maya 64bit.

**Comment by Vahan86** [comment]
I have changed Desktop font size  in Cinnamon Settings->Fonts and the size of desktop icon text changed correctly. I have tested it in Cinnamon 3.0.7. 

@JosephMcc  can we close this issue?

**Comment by JosephMcc** [comment]
Yep, just tested and it works fine for me as well.
