### ISSUE TITLE
Grouped window lists: "squeezed" and misplaced app icons

### ISSUE THREAD

**Issue by CtrlZmaster** [linuxmint/cinnamon#8522]
```
 * Cinnamon version - 4.0.10
 * Distribution - Fedora 29 64-bit
 * Graphics hardware - Intel HD4600 (i915 driver)
 * Theme: Matcha Azul
 * Icons: Paper
 ```

**Issue**
Icons on a vertical panel are not centered and have wrong aspect ratio - width seems reduced.

**Steps to reproduce**
Create a vertical panel, expand the size to 60. Add Grouped window list applet and move its placement within the panel - icons will distort.

**Expected behaviour**
Icons of the applet should be sized and placed similarly as other applet icons (show desktop button for example).

**Other information**
You can see the issue here:
![Screenshot](https://user-images.githubusercontent.com/32680880/56395570-66df1800-623b-11e9-92cc-7e65b4e3aff8.png)

**Comment by smurphos** [comment]
Report to the theme author - it's a theme issue.

**Comment by smurphos** [comment]
To add - if you want to a quickfix for the issue pending the author updating the theme locate this section in the themes cinnamon.css and remove the `padding: 0 8px;` line

```
.grouped-window-list-item-box {
  font-weight: normal;
  background-image: none;
  padding: 0 8px;
  transition-duration: 100;
  color: rgba(182, 187, 191, 0.95);
  border: 0 solid transparent;
}
```

**Comment by CtrlZmaster** [comment]
Thanks, the quick fix worked. I'm closing this issue here and will open it in Matcha's repo.
