### ISSUE TITLE
Internet connection over Wi-Fi randomly stops working on my Mid-2012 MacBook Pro

### ISSUE THREAD

**Issue by wifisucks** [linuxmint/cinnamon#8525]
```
 * Cinnamon 4.0.8
 *Mint 19.1 Tessa
 * Intel Graphics 4000 (integrated), default out-of-the-box driver 
 * 64-bit
 * 
[syslog.txt](https://github.com/linuxmint/cinnamon/files/3101371/syslog.txt)
[xsession-errors.txt](https://github.com/linuxmint/cinnamon/files/3101372/xsession-errors.txt)

 ```

**Issue**
I have a Mid-2012 Non-Retina MacBook Pro. I used the proprietary driver called "bcmwl-kernel-source" Version 6.30.223.271 for the Airport Extreme Wireless Card I have. When I'm connected to a known trouble-free wireless network, the internet connection just completely disappears randomly. The MacBook is still connected to the network during these internet outages.

**Steps to reproduce**
Install Mint on this MacBook model, install the proprietary driver, and connect to a wireless network.

**Comment by icarter09** [comment]
@wifisucks are you still experiencing this issue?
