### ISSUE TITLE
Small clicking area of the closing icon on the title-bar

### ISSUE THREAD

**Issue by dawidd4** [linuxmint/cinnamon#8526]
**Issue**
I don't know if it is a Cinnamon issue, I tested it on MATE.
There is a margin around the CLOSE button. It's a bit uncomfortable when a window is maximized and you move the cursor to the top right corner and try to close the window.
[pic.jpg](https://www.wykop.pl/cdn/c3201142/comment_QPelyvLQbO0aNuo9UiPBxHpNLtT5yjpV.jpg)

Example of a fixed title-bar:
[JSFiddle](https://jsfiddle.net/kardaw/kqznrt5d/49/)

Even there is a workaround in the options, this could be by default.

**Comment by JosephMcc** [comment]
This is just down to the theme being used. It isn't any type of setting in Cinnamon.
