### ISSUE TITLE
Power applet gives non-sane value, while powertop gives sane value

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/cinnamon#8530]
```
 * Cinnamon version (cinnamon --version): 4.0.10
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 19.1
 * Graphics hardware *and* driver used: Intel UHD Graphics 620 3.0 Mesa
 * 32 or 64 bit: 64
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
 ```

**Issue**

Please see this screenshot, showing the applet reporting >100 hours of battery life:

![image](https://user-images.githubusercontent.com/47056543/56626451-9d50d480-6639-11e9-9181-60094dd562ce.png)

**Steps to reproduce**

Disconnect AC power. Look at applet. Compare powertop.

**Expected behaviour**

Either a messaging to the effect that no data is yet available or else a sane value.

**Other information**

After about a minute, the applet reports what powertop reports. Still, the initial misinformation is a blemish.

ThinkPad X1CG6. Kernel:  5.0.8-050008-generic

**Comment by leigh123linux** [comment]
Check the output for

```
upower -d
```

if  it matches the applet you can close this issue and refile it against upower.
FTR powertop output is irrelevant, cinnamon uses upower.

**Comment by LinuxOnTheDesktop** [comment]
&nbsp;&nbsp;&nbsp;&nbsp;Thank you, Leigh

&nbsp;&nbsp;&nbsp;&nbsp;My first test - of both the Mint applet _and_ upower - saw both of them reporting an utterly unrealistic 26 hours of battery life.

&nbsp;&nbsp;&nbsp;&nbsp;I would report that state of affairs as a bug report against upower but I cannot find upower's bugtracker. Might you advise?

&nbsp;&nbsp;&nbsp;&nbsp;I wonder also whether some sort of sanity check on the part of Mint's applet might not be in order.

**Comment by NikoKrause** [comment]
I think this is the bug tracker: https://gitlab.freedesktop.org/upower/upower/issues

**Comment by JosephMcc** [comment]
Closing this since it's apparently a upower issue. Please report to them.
