### ISSUE TITLE
Please update fwupdmgr so as to fix problem with its old version

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/cinnamon#8533]
```

 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 19.1
 * 32 or 64 bit :64

 ```

**Issue**

&nbsp;&nbsp;&nbsp;&nbsp;There is a fairly serious bug with the version of `fwupdmgr` offered currently by Mint. That bug has been fixed in  `fwupdmgr`. Please see [here](https://github.com/hughsie/fwupd/issues/1139) on all that. You will see in that bug report that the maintainer of  `fwupdmgr` asked me to ask you to update your version of  `fwupdmgr`. That is what I do here. Thanks.

**Comment by leigh123linux** [comment]
File the issue against linuxmint.

https://github.com/linuxmint/linuxmint/issues
