### ISSUE TITLE
Pinned icons are not synchronized in others workspaces after changes

### ISSUE THREAD

**Issue by medmedin2014** [linuxmint/cinnamon#8534]
```
 * Cinnamon 4.0.10
 * Distribution - Mint 19.1
 * 64 bit
 ```

**Issue**
After adding new pinned windows from menu or modifying the order of pinned apps by moving them by mouse inside grouped list windows applet, the change is not reflected to others work spaces.

**Steps to reproduce**

**Expected behaviour**

**Other information**

**Comment by Zorandon** [comment]
This bug is still present in Cinnamon 4.2.2. It is important to note though that a new order of icons (or added icons) is correctly represented on on all workspaces after a logout/login.
