### ISSUE TITLE
Better implementation of jump lists to recent files in the desktop [Feature request]

### ISSUE THREAD

**Issue by Tyco72** [linuxmint/cinnamon#8537]
(Mint 19.1 Cinnamon)
The implementation of jump lists to recent opened files with an application, through the applet "Grouped window list" doesn't allow to use the lists efficiently and extensively as they should. It would be great if the following improvements would be implemented. 
The jump lists are an essential tool for users who work daily on many files and open them with different applications:
 
1) The jump lists should track the recent opened files independently by the default program associated to each file type. Example: if you open .jpg files with different photo editors, the file names should appear in the jump lists of all the photo editors, which were used to open them. The entries should not appear only in the jump list for the default program. It is a crucial aspect.

2) It should be possible to pin favorites items on the top of the list.

3) It would be nice if you could select the preference to expand by default the list of recent files in the context menu. So you can quickly open/close files with only 2 clicks. (There are users which work with the jump lists very intensively:) )

4) It should be possible to delete single items in the jump list. It would be also very useful, that when deleting an item, the last item which slid out of the list, re-enter on the bottom of the list.

5) It should be possible to enable/disable the jump lists directly in the standard panel, without to have to rebuild/ reconfigure the whole panel using the 'Grouped window' applet. It is not nice to switch off the "panel launchers", because only on it you can directly edit the launch commands of the applications. (Or also could be added the ability to edit the launch command for pinned apps in the grouped-window-list)

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.

**Comment by Tyco72** [comment]
Thank you for the good news. I am looking forward to get effective jump lists on Linux

**Comment by Rik44444** [comment]
Hi, how has this developed in the past 6 years? Has the functionality matured?
