### ISSUE TITLE
[FR] Please to add application spread function/option for modern look

### ISSUE THREAD

**Issue by pyroxar** [linuxmint/cinnamon#8539]
**Issue**
If I have open a multiple windows' one application, for example nemo, when I clicked to taskbar then maximize the last window only. If I want choose another windows than the last I must go mouse to taskbar and select another window.
![obraz](https://user-images.githubusercontent.com/23406555/56865843-cf17c180-69d2-11e9-8c71-9d1be441aac8.png)
On my laptop screen (1920×1080) this way is very uncomfortable for my because my laptop is small but screen have big resolution.

In my opinion good new feature to add will be application spread function.
Example of this, this was worked great for me.
https://youtu.be/NxD_kWK8A5M?t=78
![obraz](https://user-images.githubusercontent.com/23406555/56866042-61b96000-69d5-11e9-9d79-5129c3ec5f54.png)
Like this but only for the selected application:
![obraz](https://user-images.githubusercontent.com/23406555/56866079-b4931780-69d5-11e9-83f2-c8277d137b14.png)

@jaszhix what you think about this?

**Other information**
In the with nemo example when I use nemo can't see any details in windows to select. It is very uncomfortable.
![syf](https://user-images.githubusercontent.com/23406555/56865998-b8726a00-69d4-11e9-984d-4b3d15798b12.png)

**Comment by mtwebster** [comment]
One existing option, alt-~ opens an alt-tab switcher for all windows of a particular application only.

**Comment by pyroxar** [comment]
Are you sure?
![obraz](https://user-images.githubusercontent.com/23406555/56869509-fe91f280-6a01-11e9-8f50-9ba9686fdf92.png)

**Comment by JosephMcc** [comment]
The hotkey shown by mtwebster works fine here on git master. Brings up only other windows for the currently active application window.

**Comment by pyroxar** [comment]
In my opinion application spread like in the Unity's Ubuntu will be very great function for everone.
In Unity in the Ubuntu 14.04 and the 16.04, was better for me
![obraz](https://user-images.githubusercontent.com/23406555/56869889-4404ee80-6a07-11e9-8483-fd4c2f978af3.png)

than Ubuntu 19.04+ with GNOME:
![obraz](https://user-images.githubusercontent.com/23406555/56869879-1c158b00-6a07-11e9-9a7a-3ef69be603bf.png)

Preview is too small for me.

**Comment by pyroxar** [comment]
When i click first time then last open window is restored. When i click second time then show all windows of one type. This is very helpful.
![obraz](https://user-images.githubusercontent.com/23406555/56870896-9f8aa880-6a16-11e9-9372-cf17c3fb7fa6.png)

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
