### ISSUE TITLE
Option to turn off lower half tiling.

### ISSUE THREAD

**Issue by damian101** [linuxmint/cinnamon#8541]
```
 * Cinnamon version (4.0.10)
 * Distribution - (Reborn OS)
 * NVIDIA Corporation GP104GLM [Quadro P4000 Mobile]; nvidia-dkms 418.56
 * 64 bit
 ```
I would like to have the option to prevent a window from being tiled when I move it to the bottom.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
