### ISSUE TITLE
Cinnamon alpha, small regression: coverflow 3d

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/cinnamon#8543]
**EDIT: closed; re-filed at https://github.com/linuxmint/alpha-testing/issues/9**

 * Cinnamon version (cinnamon --version) 4.0.10
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 19.1
 * Graphics hardware *and* driver used: Intel UHD Graphics 620 3.0 Mesa 18.2.8
 * 32 or 64 bit: 64
[x.txt](https://github.com/linuxmint/cinnamon/files/3133685/x.txt)

**Issue**

When coverflow-3d is activated via alt-tab, and I moved through windows, strange things happened. It is hard to describe - is Mint's video-recorder working again yet?

**Steps to reproduce**

Unknown: now that I press alt-tab again, everything works, even when I toggle the alt-tab mode from coverflow-3d and back again. I could try again after a reboot.

**Expected behaviour**

**Other information**

Mint's Vsync method: 'Presentation Time'.

**Comment by LinuxOnTheDesktop** [comment]
I've re-opened this because the following just occured on Mint 19.3.

While the program Grub-Customizer was saving changes, I alt-tabbed, using Coverflow3d, and the switcher froze when showing a small version of a terminal. (I did have a terminal window open.) I could not switch to the terminal or to any other program. I had to open a tty and reboot using it. I did try to replicate the bug - though as you can imagine, given the application involved and what it (the Grub Customizer) was doing, I was reluctant so to do. The one time I tried that reproduction, though, it failed, i.e. I could not reproduce the problem.

**Comment by leigh123linux** [comment]
If the issue doesn't reproduce there is little or no point in reopening.
