### ISSUE TITLE
[Suggestion] Have delete button in window switcher change red when hovering (see screenshot)

### ISSUE THREAD

**Issue by PowerUser64** [linuxmint/cinnamon#8545]
```
 * Cinnamon version - 4.0.10
 * Distribution - Mint 19.1
 ```

**Issue**
The delete window button at the bottom of the window/desktop switcher looks the same whether there is a window being held over it or not

**Steps to reproduce**
Drag any window over the close window button at the bottom of the window/desktop switcher (ctrl + alt + up)

**Suggestion**
It would be nice if the button changed color to red when there is a window being held above it, so you can tell at a glance that you are hovering over a button that will close your window.

**Screenshots (before and after)**

What it is now:
![DeleteButton-LinuxMintSeggustion](https://user-images.githubusercontent.com/24578572/57005547-a851ba80-6b8d-11e9-8afb-fe8d5ef7b08d.png)

(Roughly) what I am suggesting:
![Suggested-DeleteButton-LinuxMintSeggustion](https://user-images.githubusercontent.com/24578572/57005548-a851ba80-6b8d-11e9-9836-e1bb1156bdc5.png)

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
