### ISSUE TITLE
Problem snapping Settings windows, when HiDPI enabled

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/cinnamon#8548]
```
 * Cinnamon version (cinnamon --version) 4.0.10
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 19.1
 * Graphics hardware *and* driver used: machine (1) Intel UHD Graphics 620, 3.0 Mesa; machine (2) VirtualBox Graphics Adapter
 * 32 or 64 bit: 64
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
 ```

**Issue**

When HiDPI is enabled: the Settings -> Themes window (on machines 1 and 2) and its 'parent', i.e. the Settings window (on machine 1 but not machine 2) will snap to the top and bottom of the screen but not to the sides; no snapping rectangle appears for those sides. When HiDPI is disabled, all snapping works.

**Steps to reproduce**

Enable HiDPI.
Open System Settings (in any which way).
Try to snap that menu (using any method) to first the left side of the screen and then the right side.
Open the themes window (/version of the Settings window) and try to snap it (using any method) to the left and right sides of the screen.

**Expected behaviour**

All snapping should work.

**Other information**

Computer 2 has a resolution of  2560x1440 and has HiDPI enabled in Mint's settings.

Computer 2 has a resolution of 1920x1200 and is not HiDPI, but I enabled HiDPI on that system for testing purposes.

If the video recorder is fixed, I will make a video showing the problem,

**Comment by JosephMcc** [comment]
This is not an issue. A window can only tile if it's allowed to be resized to fit in the zone you are trying to tile it in. Your "testing" set up creates a ridiculously small effective resolution so the window simply cannot be resized to fit.
