### ISSUE TITLE
Applet sound@cinnamon.org - Make volume bar vertical

### ISSUE THREAD

**Issue by yuriescl** [linuxmint/cinnamon#8551]
```
Cinnamon 4.0.10
Mint 19.1 64bit
Applet: sound@cinnamon.org (default)
NVIDIA 390.116 (proprietary)
 ```

**Issue**

The current volume control is horizontal:
![current](https://user-images.githubusercontent.com/26092447/57529758-11fb6280-730c-11e9-83db-5640d74c65c3.png)

**Steps to reproduce**

Play media using Spotify or VLC and open the sound applet to adjust the volume or pause/play the media.

**Expected behaviour**

It's counter-intuitive to have a horizontal volume bar because users usually expect the horizontal bar to contain the current position of the media being played. I always end up changing the volume because I think I'm changing the position of the music I'm listening to.

This format is more visually intuitive:

![suggested](https://user-images.githubusercontent.com/26092447/57529895-5e46a280-730c-11e9-893c-3ba8e42f15b0.png)

So I suggest either making the bar vertical and adding an horizontal position control (to select the media position), or just making the bar vertical and removing the horizontal bar.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
