### ISSUE TITLE
gnome-terminal tabs not changing through pull down menu

### ISSUE THREAD

**Issue by fusentast** [linuxmint/cinnamon#8552]
```
Cinnamon version 4.0.10
Mint 19.1  
Nvidia Gtx 760,* driver used: 390.116
[xsession-errors.zip](https://github.com/linuxmint/cinnamon/files/3166816/xsession-errors.zip)
64 bit
 ```
Description:
When using multiple tabs in Gnome-Terminal I'm able to shift through tabs with ALT+number.
But when using pull down menu to the far right, and choosing another tab, it doesn't change tab.

**Steps to reproduce**
Open Gnome-Terminal and open another tab in that terminal, and try to change tab through pull down menu.

**Expected behaviour**
Change tab like the keyboard shortcut ALT+number does.

**Other information**

**Comment by JosephMcc** [comment]
You are right this does not work but I think is not a Cinnamon issue in any way. Likely needs to be reported upstream to Ubuntu.
