### ISSUE TITLE
Vertical panel ignores display date

### ISSUE THREAD

**Issue by sparkasaurusRex** [linuxmint/cinnamon#8554]
![image](https://user-images.githubusercontent.com/8961915/57575699-6b46bd00-7404-11e9-8ad1-55b7a2e957e2.png)

When using a horizontal panel the day of the week is not displayed even though the "Display the date" setting is on. Also, the time is awkwardly broken up to two lines. I know it is hard to fit the entire word "Wednesday" in limited horizontal space, but it could be abbreviated or there could be an option to increase the panel size to allow the date and time to fit nicely.

**Comment by smurphos** [comment]
?
Maximum default panel width and Custom Date Format %H:%M
![screenshot-area-2019-05-12-044525](https://user-images.githubusercontent.com/29017677/57577526-e3e36300-7470-11e9-9fc5-532573b2447e.png)

**Comment by sparkasaurusRex** [comment]
Oh, if this is a bug I can give you info about my system. 
```
 * Cinnamon version 4.0.10
 * Distribution - Arch
```
The maximum panel width still puts the hour on top and doesn't show the day of the week at all.

**Comment by smurphos** [comment]
Yeah, without hacking the panel.js to increase the maximum panel width you can't get the full date and time in there on 4.0.10 but you can at least set a custom Date/Format as outlined to have the time correctly formatted on a max width vertical panel.  It's a workaround.

**Comment by sparkasaurusRex** [comment]
Thanks for your help! I didn't realize these settings were in the calendar applet. I managed to fit in the day of the week by adding newlines.
```%a%n%m/%d%n%l:%M```
My problem now is that the text is not centered, but I can live with it.
![image](https://user-images.githubusercontent.com/8961915/57578274-a9140780-743d-11e9-9d9a-c17c621bd4e3.png)

**Comment by smurphos** [comment]
Nice catch on %n as a newline - I'd forgotten that.

The text-alignment you could workaround by including a space or two in your custom format or by tweaking the cinnamon.css.

Editing or adding this to the cinnamon.css would probably do the trick for most themes.
```
.applet-box.vertical {
  text-align: center; }
.applet-box.vertical .applet-label {
  padding: 0; }
```

**Comment by sparkasaurusRex** [comment]
Looks great now, thanks!
