### ISSUE TITLE
Each workspace with its own background

### ISSUE THREAD

**Issue by Lehmeiers** [linuxmint/cinnamon#8559]
```
 * Cinnamon version 4.0.10

It would be great if I could deposit any desktop with its own wallpaper. This would make it clear at a glance which side you are on.

**Comment by smurphos** [comment]
Whilst I agree this would be nice to have as a native feature, you can implement this with a simple bash script.  

E.g. https://github.com/smurphos/nemo_actions_and_cinnamon_scripts#workspace-background-switcher 

https://github.com/smurphos/nemo_actions_and_cinnamon_scripts/blob/master/.local/bin/workspace_background_switcher.sh

**Comment by Lehmeiers** [comment]
I'll try to install it.
But why is not it installed by default?

**Comment by JosephMcc** [comment]
This has been requested plenty of times. There is still at least one open issue asking for it: https://github.com/linuxmint/cinnamon/issues/8072

**Comment by Lehmeiers** [comment]
I'm having trouble installing it in my Manjaro.
But if I see it right I have to change it directly in the script. Unfortunately that is not very comfortable.
Maybe you can include this in the desktop changer.
