### ISSUE TITLE
Each desktop with its own links, programs, folders, etc.

### ISSUE THREAD

**Issue by Lehmeiers** [linuxmint/cinnamon#8560]
* Cinnamon version 4.0.10

It would be good if I could document each workspace with different programs, folders, etc.
So a better work would be possible because I have all Prorgamme etc, which maybe I need for office, video editing, Internet etc together. This makes better use of the individual work surface and remains clear.

**Comment by JosephMcc** [comment]
Probably better to just add this to already open and similar issues: https://github.com/linuxmint/cinnamon/issues/8072
