### ISSUE TITLE
Previous sessions are not restored after a reboot

### ISSUE THREAD

**Issue by Lehmeiers** [linuxmint/cinnamon#8561]
* Cinnamon version 4.0.10

It is sad that after booting the previous session is not restored automatically.
Manmuß every time program again start by hand.
It would be a good thing if this worked.

The startup file is here a bit unwieldy because it can change. For example, more Internet, video editing, etc.

**Comment by JosephMcc** [comment]
The request for restoring previous sessions has been around for awhile but at the moment is not being worked on. It isn't a simple thing to get working properly.
