### ISSUE TITLE
System information with copy function

### ISSUE THREAD

**Issue by Lehmeiers** [linuxmint/cinnamon#8562]
* Cinnamon version 4.0.10

It would be nice if you could not only call up the system information (Settings => System Information), but also copy it, then inserting it into a post would be much easier.

Therefore, I would like to ask for this improvement

**Comment by smurphos** [comment]
This was added to System Reports (mintreport) a little while ago and should be in the next release. 
https://github.com/linuxmint/mintreport/commit/e557c9c15d50ea021b8757340f67aa65e8e84b51

**Comment by JosephMcc** [comment]
To be fair, since the OP didn't bother to fill out the issue template and we don't know what distro they are on, mintreport may be of no use to them.
