### ISSUE TITLE
Some feedback about Cinnamon 4.x

### ISSUE THREAD

**Issue by IvoAndonov** [linuxmint/cinnamon#8563]
In Cinnamon 3.8 and older versions the text in tray (such as calendar, kb layout) was resized according to the panel size which was a very convenient feature.
In Cinnamon 4.x I noticed you have removed that feature and the text remains microscopic (12px or so) no matter what size the user has set for the panel. I for one set my panel to 50px height. With 12px text size it's ugly, at the very least. IDK why you did that. Removing features indicates bad attitude towards the users and I'm not the only one who thinks so - I know that for a fact. But I'm a stubborn donkey and I don't give up until I get what I want, especially when it comes to Cinnamon. Which I did (screenshot). But I don't understand why do you have to remove features in the first place and make us use bruteforce in order to have a good looking panel?

If you're planning to turn Cinnamon into a clone of Gnome3 where one can't change even the simplest things, then tell us now, so that we can start looking for a DE whose developers don't impose their vision on the users (needless to say which OS that reminds me of) or at least blacklist cinnamon's updates.

![cinnamon-4-0](https://user-images.githubusercontent.com/41172201/57589053-ed2f0700-7526-11e9-9bda-e9c294c12c10.png)

**Comment by JosephMcc** [comment]
Thanks for the feedback but I don't get the attitude. The way the panel works was changed in 4.0. It was nothing to do with feature removal. Constructive feedback is always welcome but the rest just isn't needed.

There are also other related issues already open like this one: https://github.com/linuxmint/cinnamon/issues/8260
