### ISSUE TITLE
when start firefox it only goes to the linux mint website

### ISSUE THREAD

**Issue by lankfor1** [linuxmint/cinnamon#8564]
```
 * Cinnamon version (cinnamon --version)
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
 * Graphics hardware *and* driver used
 * 32 or 64 bit
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
 ```

**Issue**

**Steps to reproduce**

**Expected behaviour**

**Other information**

**Comment by JosephMcc** [comment]
This has nothing to do with Cinnamon. On a default installation of Mint Firefox has the the Mint website set as the home page. You can just change this.
