### ISSUE TITLE
Pointer gets trapped temporarily in panel

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/cinnamon#8565]
```
 * Cinnamon version (cinnamon --version) 4.0.10
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 19.1
 * Graphics hardware *and* driver used: Intel UHD Graphics 620 3.0 Mesa 18.2.8
 * 32 or 64 bit: 64
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
 ```

**Issue**

The pointer gets trapped temporarily in a side panel, even when the panel is not visible. Please see [this video here (box, .ogv)](https://app.box.com/s/qgb1fjzfd0nmhzfufu3973uxwo481k7a).

**Steps to reproduce**

Uncertain. Perhaps: create side-panel; set it to autohide; when the panel is visible, move the pointer around inside it; when the panel is hidden, move the pointer around where the panel would be were the panel visible.

Please see also the 'Further information' section.

**Expected behaviour**

The pointer should not get stuck.

**Other information**

The settings of the side panel:

![Panel settings](https://user-images.githubusercontent.com/47056543/57592119-e7d4bb00-752c-11e9-9ea8-57a93bcb9890.png)

The sticking happens even in VirtualBox (Linux Mint host, Windows guest) when VirtualBox is full screen.

I have two further panels - a top one and a bottom one - both set to autohide.

EDIT: the problem persits into the current (May 13th) alpha version of Mint.

**Comment by smurphos** [comment]
I get this is I've got the preference (right at the bottom of the panel settings GUI) `Allow the pointer to pass through the edges of panels` unchecked. If it's checked no such issue.

![screenshot-window-2019-05-14-070141](https://user-images.githubusercontent.com/29017677/57674212-86891680-7616-11e9-8161-d62d7ed79466.png)

**Comment by LinuxOnTheDesktop** [comment]
Thank you. Here is why I did not think of that option.

(1) I tend to forget what that option means.

(2) Unless I use the <atl> key, that option is in a portion of the window that I cannot see because it is off the bottom of the screen. Still, the vertical scroll bar does indicate - I notice now - that some of the window is hidden.

I submit that both of these things are suboptimal.

Enabling the option does seem to solve the problem.

**Comment by JosephMcc** [comment]
Ok, it seems you found the setting that fixes your issue.
