### ISSUE TITLE
[Feature-Request] Allow one to remove power / shutdown button from Cinnamon menu for standard users

### ISSUE THREAD

**Issue by savaged** [linuxmint/cinnamon#8566]
```
 * Cinnamon 4.0.10
 * Distribution - Mint 19
 ```

**Feature Request**
I would like to prevent my children from powering off our Linux Mint 19 desktop pc. I have them set-up as standard users. I would like them to log off but not shutdown. I can't find where to set this just for standard users or on each user account.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.

**Comment by angerangel** [comment]
Me too. Sometime the power off button should be only on some users

**Comment by leigh123linux** [comment]
You can add a rule to polkit

https://forums.fedoraforum.org/showthread.php?313889-Disabling-shutdown-restart-for-a-user
