### ISSUE TITLE
desktop crash

### ISSUE THREAD

**Issue by laragoza** [linuxmint/cinnamon#8571]
* Cinnamon version (cinnamon --version)
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
 * Graphics hardware *and* driver used
 * 64 bit
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog

===================================================================
 GDB Log                                                           
===================================================================
[New LWP 2865]
[New LWP 2842]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/lib/xorg/Xorg -core :0 -seat seat0 -auth /var/run/lightdm/root/:0 -noliste'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00005617087dc5b3 in miPointerGetPosition ()
[Current thread is 1 (Thread 0x7fd07e7aa700 (LWP 2865))]

===================================================================
 GDB Backtrace                                                     
===================================================================
[New LWP 2865]
[New LWP 2842]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/lib/xorg/Xorg -core :0 -seat seat0 -auth /var/run/lightdm/root/:0 -noliste'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00005617087dc5b3 in miPointerGetPosition ()
[Current thread is 1 (Thread 0x7fd07e7aa700 (LWP 2865))]
#0  0x00005617087dc5b3 in miPointerGetPosition ()
#1  0x00007fd080efd1d5 in ?? () from /usr/lib/x86_64-linux-gnu/nvidia/xorg/nvidia_drv.so
#2  0x00007fd07e7a85bc in ?? ()
#3  0x0000561708aa87a0 in micmapScrPrivateKeyRec ()
#4  0x00005617092fc550 in ?? ()
#5  0x00005617094e4000 in ?? ()
#6  0x0000000000000000 in ?? ()

===================================================================
 GDB Backtrace (all threads)                                       
===================================================================
[New LWP 2865]
[New LWP 2842]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/lib/xorg/Xorg -core :0 -seat seat0 -auth /var/run/lightdm/root/:0 -noliste'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00005617087dc5b3 in miPointerGetPosition ()
[Current thread is 1 (Thread 0x7fd07e7aa700 (LWP 2865))]

Thread 2 (Thread 0x7fd088a11600 (LWP 2842)):
#0  __lll_lock_wait () at ../sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:135
No locals.
#1  0x00007fd0860f6098 in __GI___pthread_mutex_lock (mutex=0x561708a88100) at ../nptl/pthread_mutex_lock.c:113
        ignore1 = <optimized out>
        ignore2 = <optimized out>
        ignore3 = <optimized out>
        id = 2842
        type = 1
        __PRETTY_FUNCTION__ = "__pthread_mutex_lock"
        id = <optimized out>
#2  0x00005617087f17a0 in input_lock ()
No symbol table info available.
#3  0x00005617086c649b in ?? ()
No symbol table info available.
#4  0x00005617087dbb08 in ?? ()
No symbol table info available.
#5  0x000056170876c864 in ?? ()
No symbol table info available.
#6  0x0000561708693d01 in ?? ()
No symbol table info available.
#7  0x0000561708681c5a in ?? ()
No symbol table info available.
#8  0x000056170869a500 in ?? ()
No symbol table info available.
#9  0x0000561708695b9f in ?? ()
No symbol table info available.
#10 0x0000561708696117 in ?? ()
No symbol table info available.
#11 0x000056170869709c in ?? ()
No symbol table info available.
#12 0x000056170877ceaa in ?? ()
No symbol table info available.
#13 0x000056170877d3f3 in ?? ()
No symbol table info available.
#14 0x00005617087aaef2 in ?? ()
No symbol table info available.
#15 0x00005617087d2bb9 in ?? ()
No symbol table info available.
#16 0x00005617087d2d49 in mieqProcessInputEvents ()
No symbol table info available.
#17 0x00005617086cbb39 in ProcessInputEvents ()
No symbol table info available.
#18 0x0000561708689e11 in ?? ()
No symbol table info available.
#19 0x000056170868dee0 in ?? ()
No symbol table info available.
#20 0x00007fd085d1cb97 in __libc_start_main (main=0x561708677b50, argc=11, argv=0x7ffca617cd88, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffca617cd78) at ../csu/libc-start.c:310
        self = <optimized out>
        __self = <optimized out>
        result = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {0, 3114591705668159688, 94656925236064, 140723095063936, 0, 0, 8713934801234200776, 8698238705829447880}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x7fd088826733 <_dl_init+259>, 0x7fd088814438}, data = {prev = 0x0, cleanup = 0x0, canceltype = -2004719821}}}
        not_first_call = <optimized out>
#21 0x0000561708677b8a in _start ()
No symbol table info available.

Thread 1 (Thread 0x7fd07e7aa700 (LWP 2865)):
#0  0x00005617087dc5b3 in miPointerGetPosition ()
No symbol table info available.
#1  0x00007fd080efd1d5 in ?? () from /usr/lib/x86_64-linux-gnu/nvidia/xorg/nvidia_drv.so
No symbol table info available.
#2  0x00007fd07e7a85bc in ?? ()
No symbol table info available.
#3  0x0000561708aa87a0 in micmapScrPrivateKeyRec ()
No symbol table info available.
#4  0x00005617092fc550 in ?? ()
No symbol table info available.
#5  0x00005617094e4000 in ?? ()
No symbol table info available.
#6  0x0000000000000000 in ?? ()
No symbol table info available.
#0  0x00005617087dc5b3 in miPointerGetPosition ()
#1  0x00007fd080efd1d5 in ?? () from /usr/lib/x86_64-linux-gnu/nvidia/xorg/nvidia_drv.so
#2  0x00007fd07e7a85bc in ?? ()
#3  0x0000561708aa87a0 in micmapScrPrivateKeyRec ()
#4  0x00005617092fc550 in ?? ()
#5  0x00005617094e4000 in ?? ()
#6  0x0000000000000000 in ?? ()
```
 * Cinnamon version (cinnamon --version)
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
 * Graphics hardware *and* driver used
 * 32 or 64 bit
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
 ```

**Issue**

**Steps to reproduce**

**Expected behaviour**

**Other information**

**Comment by clefebvre** [comment]
There are no symbols in the stack trace, so it's not useful to understand what's happening. Install the debug packages for Cinnamon (cinnamon-dbg) to help generating proper stacks next time you see a crash. I'm surprised mintreport didn't complain about this..

**Comment by clefebvre** [comment]
Was that a crash of the driver itself? It doesn't seem to be muffin.so/cinnamon?
