### ISSUE TITLE
Feature request: keyboard shortcuts for panels

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/cinnamon#8579]
```
 * Cinnamon version (cinnamon --version) 4.0.10
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 19.1
 * Graphics hardware *and* driver used: Intel UHD Graphics 620 Mesa 3
 * 32 or 64 bit: 64
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
 ```

**Issue**

&nbsp;&nbsp;&nbsp;&nbsp;It would be good (**I**) were there a keyboard shortcut to show a hidden panel, (**II**) were it possible to move between panel items using the arrow keys. If, vis-a-vis **I**, the panel was visible already, then the keyboard shortcut could select the panel, such that one could then use the arrow keys, as in **II**.

&nbsp;&nbsp;&nbsp;&nbsp;At present, using a hidden panel to launch or switch to an application requires the following:
1. moving the pointer to the panel area;
2. waiting until the panel shows (although, admirably, that delay is customisable already);
3. moving the pointer to the right place on the panel;
4. clicking.

By contrast, if **I** and **II** were implemented, then the steps required for the action would be:
1'. press key-combination to show / select panel;
2'. use the arrow keys to select required panel element;
3'. press `return` or `space` or else click.

1'-3' would be faster than 1-4, especially if, so to speak, step 0 was: have hands on keyboard.

&nbsp;&nbsp;&nbsp;&nbsp;It is true that already one can assign keyboard shortcuts to applications, and there is alt-tab and there is expo. Yet, the features I request would still be useful, I think. For those features are not exact duplicates of the existing ones. Moreover, I think that making Cinnamon a little more keyboard-centred in this way would make it more attractive to a certain type of user.

**Steps to reproduce**

**Expected behaviour**

**Other information**

To my knowledge - and I did consult other people about this - the functionality I request is not available already.

EDIT: One might compare the following from the release notes of Firefox 67.0.

> Keyboard accessibility has improved in the latest version of Firefox. Toolbar and toolbar overflow menu are both fully keyboard accessible: keyboard users can now access add-ons, the downloads panel, the overflow, Page actions and Firefox menus, and much more.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
