### ISSUE TITLE
[Cinnamon 4] Nemo Side Panel Inconsistent Right Click Menu Heights

### ISSUE THREAD

**Issue by hellofolks** [linuxmint/cinnamon#8580]
```
 * Cinnamon 4.0.10
 * 5.1.3-arch1-1-ARCH
 * Intel Corporation 3rd Gen Core processor Graphics Controller (rev 09)
 * intel(0): Using Kernel Mode Setting driver: i915, version 1.6.0 20190207
 * x64
 * xsession-errors and preview attached
 ```

**Issue**

 - Nemo 4.0.6 side panel **right click menu** shows **inconsistent
   height**

**Steps to reproduce**

 - Open Nemo 4.0.6
 - Click randomly right mouse button on side panel
   entries

**Expected behaviour**

 - Consistent menu heights

**Other information**

![preview](https://user-images.githubusercontent.com/42659704/58131454-66191780-7c27-11e9-8fe2-3c6f344c5cd3.gif)

[xsession-errors.txt](https://github.com/linuxmint/cinnamon/files/3204577/xsession-errors.txt)

**Comment by leigh123linux** [comment]
https://github.com/linuxmint/nemo/issues/2118
