### ISSUE TITLE
How to write custom desklet 

### ISSUE THREAD

**Issue by Mracobes9** [linuxmint/cinnamon#8587]
Hi. Where can i find docs or guide for desklet development ?

**Comment by Hultan** [comment]
I am very new to Cinnamon development myself so I am not sure, but this page is the best source I have found:

http://developer.linuxmint.com/reference/git/cinnamon-tutorials/extension-system.html

**Comment by Odyseus** [comment]
Hello, everybody.

@Mracobes9 and @Hultan: for an updated documentation, install the packages `devhelp` and `cinnamon-doc`. Then open **Devhelp** from your applications menu. It not only contains a more up-to-date documentation that the one on-line, but also has documentations about the **St** library and Cinnamon's JavaScript modules.

For documentation about GObject libraries (Clutter, GLib, Gio, etc.), exists [this on-line documentation](https://lazka.github.io/pgi-docs/) that can also be [downloaded for off-line use](https://github.com/lazka/pgi-docs) as a static HTML site, and also can be downloaded as [Devhelp books](https://github.com/pygobject/pgi-docs-devhelp).

**Comment by JosephMcc** [comment]
For now the best resources are what was shown here and by looking at existing desklets.
