### ISSUE TITLE
Scale and Expo are Choppy while changing focus

### ISSUE THREAD

**Issue by sunboy2** [linuxmint/Cinnamon#859]
In the scale and expo view, when I klick on a window that was not in focus before I activated the scale/expo effect, zooming back to the desktop will stutter a bit. This gets more visible on a weak graphic card. (On  Geforce 8300 GS it is very obvious in the expo effect).
I know that problem from kde, where serval effects are choppy when they are executed during a focus change.

**Comment by pixunil** [comment]
@linuxmint - close reminder
