### ISSUE TITLE
Trash should be under Places in the Cinnamon menu

### ISSUE THREAD

**Issue by damian101** [linuxmint/cinnamon#8591]
```
 * Cinnamon version 4.0.10-2
 * Distribution - Reborn OS (Arch based)
 * Nvidia Quadro P4000, nvidia-dkms 430.14-6
 * 64 bit
 ```
In the Cinnamon menu I miss the trash under "Places".
If there would be a "Trash" entry in the Cinnamon menu you could also open the trash by searching for it in the Cinnamon menu, which Windows users might be used to.

**Comment by SketchNI** [comment]
This would be more appropriate under the [nemo](https://github.com/linuxmint/nemo) repository as that is where `Places` is read from.

**Comment by damian101** [comment]
@SketchNI I disagree, you could change the default  filemanager (it doesn't quite work with Dolphin and Caja, #8584 ) or even uninstall Nemo, and accessing Places through the Cinnamon menu would still work, they would just open in the different default file manager.

**Comment by SketchNI** [comment]
I did make a (seemingly incorrect) assumption as I have added directories to the My Computer section of nemo and had those appear in the Places menu
    	
    	

    	Regards,Denver Freeburn(Sent from iOS)
    
  




On Fri, May 31, 2019 at 5:53 PM +0100, "damian101" <notifications@github.com> wrote:












@SketchNI I disagree, you could change the default  filemanager (it doesn't quite work with Dolphin and Caja, #8584 ) or even uninstall Nemo, and accessing Places through the Cinnamon menu would still work, they would just open in the different default file manager.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
