### ISSUE TITLE
Cinnamon 4 segfault error 6 in libmuffin.so

### ISSUE THREAD

**Issue by Redsandro** [linuxmint/cinnamon#8592]
* Cinnamon version 4.0.10
* Distribution - Mint 19.1 64 bit
* GeForce GTX 970 with nvidia proprietary driver 396.54
* [xsession-errors.txt](https://github.com/linuxmint/cinnamon/files/3232140/xsession-errors.txt)
* [syslog.txt](https://github.com/linuxmint/cinnamon/files/3232150/syslog.txt) (snippet)

**Issue**

After upgrading from Linux Mint 19 to 19.1 via the Update Manager, Cinnamon will crash and fall back to MATE software rendering immediately after login or `cinnamon --replace`.

**Steps to reproduce**

`cinnamon --replace` will throw a variant of `segfault at 28 ip 00007efd6c300fe2 sp 00007ffeccaa2fe0 error 6 in libmuffin.so.0.0.0[7efd6c2b2000+bd000]`

**Other information**

I've tried the following:

* Change the nvidia 396 to the latest 430 driver
* Change nvidia to nouveau
* remove `~/.local/share/cinnamon`
* remove `~/.config/cinnamon-session`
* `gsettings reset-recursively org.cinnamon`
* apt purge cinnamon && apt install cinnamon

__I have upgraded 3 machines from Linux Mint 19 to 19.1 over the past two weeks. The other two had no problems.__ I'm running out of ideas to remedy this.

```
$ cat /var/log/syslog | grep segfault
May 29 09:42:11 MyComputer kernel: [   62.040088] cinnamon[4896]: segfault at 28 ip 00007f61047c0fe2 sp 00007ffedc2f4ee0 error 6 in libmuffin.so.0.0.0[7f6104772000+bd000]
May 29 09:42:26 MyComputer kernel: [   76.828817] cinnamon[7586]: segfault at 28 ip 00007fe2f70bcfe2 sp 00007fffe351a2e0 error 6 in libmuffin.so.0.0.0[7fe2f706e000+bd000]
May 29 09:42:29 MyComputer kernel: [   79.271145] cinnamon[7855]: segfault at 28 ip 00007f474ccc5fe2 sp 00007fff547bade0 error 6 in libmuffin.so.0.0.0[7f474cc77000+bd000]
May 29 09:59:55 MyComputer kernel: [   33.233614] cinnamon[4096]: segfault at 28 ip 00007ff0afa91fe2 sp 00007ffdd8de8770 error 6 in libmuffin.so.0.0.0[7ff0afa43000+bd000]
May 29 10:00:01 MyComputer kernel: [   38.572137] cinnamon[4400]: segfault at 28 ip 00007f1b3e125fe2 sp 00007ffcdacf14c0 error 6 in libmuffin.so.0.0.0[7f1b3e0d7000+bd000]
May 29 10:08:34 MyComputer kernel: [  551.911075] cinnamon[1563]: segfault at 28 ip 00007f94f0698fe2 sp 00007ffc46a69650 error 6 in libmuffin.so.0.0.0[7f94f064a000+bd000]
May 29 10:12:16 MyComputer kernel: [   41.911771] cinnamon[5022]: segfault at 28 ip 00007fb5cbf7ffe2 sp 00007fffa4db7ea0 error 6 in libmuffin.so.0.0.0[7fb5cbf31000+bd000]
May 29 10:19:34 MyComputer kernel: [  480.653011] slick-greeter[3225]: segfault at 20 ip 00007f406485cf2f sp 00007ffd2525de58 error 4 in libgobject-2.0.so.0.5600.4[7f4064827000+52000]
May 29 10:19:51 MyComputer kernel: [  497.685621] cinnamon[3985]: segfault at 28 ip 00007fabca823fe2 sp 00007ffdf67eabd0 error 6 in libmuffin.so.0.0.0[7fabca7d5000+bd000]
May 29 10:22:39 MyComputer kernel: [   30.800196] cinnamon[4031]: segfault at 28 ip 00007f7cf6bbdfe2 sp 00007ffdf598b650 error 6 in libmuffin.so.0.0.0[7f7cf6b6f000+bd000]
May 29 10:37:20 MyComputer kernel: [  911.254675] cinnamon[8534]: segfault at 28 ip 00007fa8a585dfe2 sp 00007ffcb6279f00 error 6 in libmuffin.so.0.0.0[7fa8a580f000+bd000]
May 29 10:38:58 MyComputer kernel: [ 1009.890883] cinnamon[14283]: segfault at 28 ip 00007f517ceaffe2 sp 00007ffc7bb31a10 error 6 in libmuffin.so.0.0.0[7f517ce61000+bd000]
May 29 11:14:29 MyComputer kernel: [ 3140.783825] cinnamon[25653]: segfault at 28 ip 00007f5e7c496fe2 sp 00007fff0dfd0680 error 6 in libmuffin.so.0.0.0[7f5e7c448000+bd000]
May 29 11:16:40 MyComputer kernel: [ 3271.094470] cinnamon[29185]: segfault at 28 ip 00007f6bf4360fe2 sp 00007ffdb8613520 error 6 in libmuffin.so.0.0.0[7f6bf4312000+bd000]
May 29 11:25:03 MyComputer kernel: [   51.065526] cinnamon[4353]: segfault at 28 ip 00007ff5dcd3dfe2 sp 00007ffd0eb182f0 error 6 in libmuffin.so.0.0.0[7ff5dccef000+bd000]
May 29 11:39:12 MyComputer kernel: [  899.528644] cinnamon[11700]: segfault at 28 ip 00007f3d7586dfe2 sp 00007ffc08d3a490 error 6 in libmuffin.so.0.0.0[7f3d7581f000+bd000]
May 29 11:47:52 MyComputer kernel: [ 1420.246736] cinnamon[23459]: segfault at 28 ip 00007ff5d04e8fe2 sp 00007ffe3210dbf0 error 6 in libmuffin.so.0.0.0[7ff5d049a000+bd000]
May 29 11:50:52 MyComputer kernel: [ 1599.899977] cinnamon[30638]: segfault at 28 ip 00007f36ce769fe2 sp 00007ffd952f1600 error 6 in libmuffin.so.0.0.0[7f36ce71b000+bd000]
May 29 11:50:58 MyComputer kernel: [ 1605.625551] cinnamon[30732]: segfault at 28 ip 00007fc030b63fe2 sp 00007fff87de4c10 error 6 in libmuffin.so.0.0.0[7fc030b15000+bd000]
May 29 11:52:00 MyComputer kernel: [ 1667.457626] cinnamon[32010]: segfault at 28 ip 00007fd37108afe2 sp 00007fff07900520 error 6 in libmuffin.so.0.0.0[7fd37103c000+bd000]
May 29 13:02:04 MyComputer kernel: [   70.753330] cinnamon[6019]: segfault at 28 ip 00007efd6c300fe2 sp 00007ffeccaa2fe0 error 6 in libmuffin.so.0.0.0[7efd6c2b2000+bd000]
```

**Comment by Redsandro** [comment]
Update: I did

```
apt get install gnome-shell gnome 
```

And now I am running a gnome-shell ubuntu session on `gdm`.
Cinnamon is still not working when I click the little session-selector.

I also created a new user with an empty profile, and Cinnamon is not working for that user either.

**Comment by Redsandro** [comment]
I'm sorry, can't afford to keep my computer in this broken state so I will now downgrade to Linux Mint 19.0.

## Synposis:

* Update 19.0 to 19.1: Cinnamon not working :no_entry_sign: 
* Clean install 19.1: Cinnamon not working :no_entry_sign: 
* Clean install 19.0: Cinnamon working! :heavy_check_mark: 

Two out of three machines upgraded fine without an issue.

#### This machine:  :no_entry_sign: 

* Intel© Core™ i7-3770 CPU @ 3.40GHz × 4
* NVIDIA Corporation GM204 [GeForce GTX 970]

#### Successful machine 1 (desktop):

* Intel (to be edited)
* Nvidia (to be edited)

#### Successful machine 2 (laptop):

* Intel (to be edited)
* Intel Graphics (to be edited)

What information can I provide in hindsight that may be valuable?

---

Clean installs are never fun, because you have to google all the issues to get it working. 19.0 was a record with only two issues for me. I'll document them here so I don't have to google next time I have to revert to a fresh 19.0 installation.

* [Fix slow boot due to wrong resume device](https://askubuntu.com/a/1013935)
* [Fix slow boot due to searching disks for unexisting btrfs](https://unix.stackexchange.com/a/443272)
* Reinstall and reconfigure favorite packages.

**Comment by Redsandro** [comment]
I'm wondering if this is similar to #8185

**Comment by clefebvre** [comment]
@Redsandro can we get a stack trace for this? (you can mintsources for this).

**Comment by jaszhix** [comment]
This might be fixed by https://github.com/linuxmint/muffin/pull/507.

**Comment by Redsandro** [comment]
@clefebvre I apologize, I installed Linux Mint 19.0 before there was any heat on this issue.

I retried using the Live image, but it both 19.0 and 19.1 only boot in safe mode, so that doesn't differentiate anything.

**Comment by clefebvre** [comment]
I'll close this for now. We can't identify the issue without a trace.

**Comment by BerekHalfhand** [comment]
I'm having a similar issue, in addition to freezes when inactive for 30minutes. What info can i provide? How to get a trace?
