### ISSUE TITLE
Blurred and doubled system tray icons

### ISSUE THREAD

**Issue by basilky** [linuxmint/cinnamon#8595]
```
 * Cinnamon version  4.0.10
 * Distribution - Mint 19.1
 * Mint Y Teal theme
 * Intel integrated graphics
 * 64 bit
 ```
Some system tray icons look ugly on the panel. The icon of Telegram client is blurred while that of Pcloud and Whatdesk is doubled.
![Screenshot from 2019-05-31 23-27-03](https://user-images.githubusercontent.com/22705230/58726152-99655e80-83fe-11e9-9d5d-c3cf241bd0ad.png)

**Comment by icarter09** [comment]
@basilky are you still experiencing this issue?

**Comment by basilky** [comment]
@icarter09 I'm not currently using any of the above applications. So, I can't check it now. I think there were some work in cinnamon to improve this. So, this might already be fixed.
