### ISSUE TITLE
[suggestion] no change Brightness while charge in Laptop

### ISSUE THREAD

**Issue by dipenSan** [linuxmint/cinnamon#8597]
Linux mint 19.1 cinnamon DE.

do not change the brightness when power adapter is plugged in or plugged out. The brightness goes to 100% when I plugged in or out AC power to laptop. Which is annoying. And this is fixed in windows 10 recent update. Can it be fix in Cinnamon too ?

**Comment by JosephMcc** [comment]
It doesn't work using the settings in Cinnamon Settings->Power Management on the "Brightness" tab?

**Comment by dipenSan** [comment]
Oh yes, when I disabled "on battery, dim the screen when inactive" option and then re enable this option , now not changing brightness.  !!

Ok,thank you.
