### ISSUE TITLE
Cinnamon forces me to have pulseaudio running

### ISSUE THREAD

**Issue by marmistrz** [linuxmint/cinnamon#8598]
* Cinnamon version: 4.0.10
 * Distribution: Arch
 * 64 bit

**Issue**
I have a laptop without working speakers. As a result, the device rarely has any output device connected. 

The service `pulseaudio` was already disabled, but it was started by Cinnamon nevertheless. I stopped it using `systemctl stop --user pulseaudio`, but Cinnamon persistently starts pulseaudio if it's not running.

**Steps to reproduce**
1. `systemctl stop --user pulseaudio`

**Expected behaviour**
Cinnamon should respect the users decision not to have pulseaudio running

**Actual behavior**
Cinnamon starts pulseaudio after it has been stopped.

**Other notes**
Is it reasonable for cinnamon to start pulseaudio if it's marked as disabled in systemd?

**Comment by clefebvre** [comment]
Cinnamon is a pulseaudio client, so it needs the service to run. I guess it's PA itself which starts its service when queried over dbus... this isn't a bug.
