### ISSUE TITLE
cinnamon --replace removes window decorations

### ISSUE THREAD

**Issue by mondalaci** [linuxmint/cinnamon#8604]
* Cinnamon version: 4.0.10
* Distribution: Mint 19.1
* Graphics hardware *and* driver used: GeForce GTX 970, driver version 430.14
* 64 bit
* [This is the .xsession-errors](https://github.com/linuxmint/cinnamon/files/3256665/xsession-errors.before.txt) when I run `cinnamon --replace`
* [This is the .xsession-errors](https://github.com/linuxmint/cinnamon/files/3256666/xsession-errors.after.txt) of the new session after killing `cinnamon-session` from virtual terminal and making my desktop usable again.

**Issue**

When running `cinnamon --replace`, the window decorations disappear, the windows from all workspaces get stacked together, and the desktop becomes useless. The following was displayed in the console (but usually nothing gets displayed in the console):

> (cinnamon:2583): dbind-WARNING **: 12:01:38.395: Couldn't register with accessibility bus: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.

**Steps to reproduce**

Run `cinnamon --replace`

**Expected behaviour**

I'd expect Cinnamon to restore with all the window decorations, workspaces and able to interact with the desktop.

**Other information**

This used to work in previous Cinnamon version. Not sure exactly which version I was running before.

**Comment by JosephMcc** [comment]
This should be fixed on git master.
