### ISSUE TITLE
[Support Request] - Style selectors for window-list-box hover - Grouped Window List

### ISSUE THREAD

**Issue by nelwa** [linuxmint/cinnamon#8607]
```
 * Cinnamon version (cinnamon --4n)
 * Distribution - (Mint 19.1.)
 * Nvidia
 * 64 bit

How can I target the popup in the screenshot to either style it, or hide it?

![Screenshot-from-2019-06-05-19-36-58](https://user-images.githubusercontent.com/40694/58979007-625fc600-87cd-11e9-9956-d0e4c0199dfc.png)

I have tried these:
`.grouped-window-list-item-box:active {
   border-color: rgba(0, 0, 0, 0); 
}
.grouped-window-list-item-box:checked {
   border-color: rgba(0, 0, 0, 0); 
}
.grouped-window-list-item-box:running {
   border-color: rgba(0, 0, 0, 0); 
   background: red;
}
.grouped-window-list-item-box:hover {
   border-color: rgba(0, 0, 0, 0); 
}
   
.window-list-item-box:hover	{ 
 background-color: rgba(20,20,20,0.02);
        border-radius: 0px;
	color: #fff;
}`

without success.  Please help.

**Comment by jaszhix** [comment]
You want to style `grouped-window-list-thumbnail-menu` I think. 

Use the Melange dev tool to inspect Cinnamon UI elements.

- Super + L
- Click the eye dropper button in the bottom left corner.
- Press ctrl to let events pass through. Navigate to the menu you want to inspect. In this case hover over an app button in GWL.
- Press ctrl again, and you can see the way the elements are structured in the layout, and grab their class names by hovering over them. Clicking an element will show the object's state.

**Comment by nelwa** [comment]
Thank you so much for the Melange dev tool suggestion, I've never heard of it before now.
The element is targeted with `grouped-window-list-thumbnail-menu` but I can't hide it...how can I completely hide or disable it?

**Comment by jaszhix** [comment]
No problem. You can change the opacity to `0`, but the element will still be blocking input. Support for disabling the thumbnail menu would need to be added in the JS code.

**Comment by nelwa** [comment]
Ok, in which JS file can I start looking?

**Comment by nelwa** [comment]
opacity:0 doesn't work...

**Comment by jaszhix** [comment]
files/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/menus.js
files/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/appGroup.js

It might be a good idea for the non-grouped mode when thumbnails are disabled and labels are on, but I don't think it will be as functional as it should be outside that situation with no thumbnail menu.

**Comment by nelwa** [comment]
Thank you so much!  I've commented out line 499 in appGroup.js:

`this.initThumbnailMenu();` to `//this.initThumbnailMenu();`
