### ISSUE TITLE
[Feature Request] Option to lock windows ordering on panel

### ISSUE THREAD

**Issue by anjari** [linuxmint/cinnamon#8608]
```
 * Cinnamon version: 4.0.10
 * Distribution: Manjaro (Arch Linux) 64 bit
 ```

Can we have option to lock the position or ordering of [opened/pinned windows on the panel](https://i.imgur.com/0etmyJo.jpg)? I often accidentally drag a window to left/right when trying to click it which results in changed position of the window on panel.

The option can be a simple checkbox in the context menu of the panel (similar to "Panel Edit Mode" checkbox).

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
