### ISSUE TITLE
[Feature Request] New Hotkeys: "Cycle through open windows IN CURRENT WORKSPACE" and "Cycle backwards through open windows  IN CURRENT WORKSPACE"

### ISSUE THREAD

**Issue by martinandersen3d** [linuxmint/cinnamon#8609]
**Issue**
In keyboard settings, there is only the option to "Cycle through open windows",
and this one cycles through ALL programs in ALL workspaces.

**Steps to reproduce**
Alt+Tab

**Expected behaviour**

I would like to suggest two new hotkeys:
- "Cycle through open windows IN CURRENT WORKSPACE"
- "Cycle backwards through open windows  IN CURRENT WORKSPACE"

**Other information**
![image](https://user-images.githubusercontent.com/19984581/59044046-aa3e2600-887d-11e9-8b98-aadedb3cf5b1.png)

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
