### ISSUE TITLE
Feature request (?): drag file items onto folders in panels

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/cinnamon#8615]
```
 * Cinnamon version (cinnamon --version): 4.0.10
   - Please specify if you are using the daily builds PPA (https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds): no.
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 19.1
 * Graphics hardware *and* driver used: not relevant
 * 32 or 64 bit: 64
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
 ```

**Issue**

I have a file on the desktop. I try to drag it to a panel. When I try to drop the file onto one of the folders, nothing happens.

**Steps to reproduce**

**Expected behaviour**

I'd expect or at least like to be able to drop a file (or folder) onto a panel folder, thereby moving the file.

**Other information**

Is the problem that the folders on the panel are 'launchers'? Is there any current way of making the drag-and-drop work?

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
