### ISSUE TITLE
Editing hidden panels: the red line showing which panel is at issue seems too thin to be usable

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/cinnamon#8616]
```
 * Cinnamon version (cinnamon --version) 4.0.10
   - Please specify if you are using the daily builds PPA (https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds). No.
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) 19.1
 * Graphics hardware *and* driver used: Intel UHD Graphics 620; 3.0 Mesa 18
 * 32 or 64 bit: 64
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
 ```

**Issue**

When using the panel configuration window (pictured below), and where the panel in question is hidden (set to auto-hide), a thin red line indicates which panel is being edited. 

![image](https://user-images.githubusercontent.com/47056543/59141583-84ad3b80-89a7-11e9-92b4-fa4819e3db49.png)

The line appears at the screen edge where the panel appears. On my system, with three hidden panels, this line is very hard to see and hence I cannot know which panel I am editing.

I am not managing to capture the red line in screenshots, for some reason.

**Steps to reproduce**

Have three hidden panels. Try to edit one of them.

**Expected behaviour**

A more visible indication of which panel is being edited. A thicker line - three times as thick, perhaps? - would do it.

**Other information**

**Comment by JosephMcc** [comment]
The proper solution would probably be to just unhide the panel when it's being edited.

**Comment by itzexor** [comment]
This change makes it just show briefly when it is initially highlighted, which is the best solution I can think of. Changing the width of the hidden panel would complicate the clipping and tweening code, and always showing it would prevent testing of autohide settings.

**Comment by LinuxOnTheDesktop** [comment]
Excellent - though I don't think the change has readed the main or even the alpha Cinnamon (the PPA) yet.

[This problem](https://github.com/linuxmint/alpha-testing/issues/21) seems of a similar sort.

**Comment by Odyseus** [comment]
Hello, everybody.

@LinuxOnTheDesktop: Look at the reference just above **itzexor** message. The fix hasn't been merged yet.
