### ISSUE TITLE
Keyboard shortcuts for Workspaces not functioning as configured/expected

### ISSUE THREAD

**Issue by dharmit** [linuxmint/cinnamon#8622]
```
 * Cinnamon version (cinnamon --version)

$ cinnamon --version
Cinnamon 4.0.10

 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
Fedora 30

 * Graphics hardware *and* driver used
 * 32 or 64 bit

64 bit
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
 ```

**Issue**
I did a fresh install of Fedora 30 (Cinnamon spin) on my laptop. I configured `Super+1` through `Super+4` to switch to Workspaces 1 through 4. However, pressing `Super+2` opens terminal (earlier `Super+2` opened email but I deleted Thunderbird) and `Super+3` opens Home folder. `Super+1` and `Super+4` do nothing.

**Steps to reproduce**
Set shortcuts for Workspaces in Keyboard -> Shortcuts -> Workspaces -> Direct Navigation

**Expected behaviour**
Switching between workspaces should work fine. And it does work fine on my another laptop with Fedora 30 and Cinnamon

**Other information**
There seems to be some default setting somewhere that's causing this issue. But in the Keyboard -> Shortcuts menu, I don't see any. Could this be coming from somewhere else?

[xsession-errors.txt](https://github.com/linuxmint/cinnamon/files/3271105/xsession-errors.txt)

**Comment by dharmit** [comment]
If instead of `Super` key I use `Ctrl+Alt` combination, it works. That is, `Ctrl+Alt+1`, `Ctrl+Alt+2`, `Ctrl+Alt+3` and `Ctrl+Alt+4` help me switch to workspaces 1, 2, 3 and 4 respectively.

**Comment by dharmit** [comment]
Is this not the right place to raise such issues/questions?

**Comment by smurphos** [comment]
Super + number are hard coded Grouped Window List applet shortcuts. I guess you are using the applet on one machine and not the other.

**Comment by dharmit** [comment]
> Super + number are hard coded Grouped Window List applet shortcuts. I guess you are using the applet on one machine and not the other.

That was indeed the case with the new system. Disabling the said applet fixed it. Thanks for your help!
