### ISSUE TITLE
'Grouped Window List': user is nudged towards accidentally removing the applet from the panel

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/cinnamon#8634]
```
* Cinnamon version (cinnamon --version) 4.0.10
   - Please specify if you are using the daily builds PPA (https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds). yes
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 19.1
 * Graphics hardware *and* driver used: Intel UHD 620 Mesa 3
 * 32 or 64 bit: 64
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
 ```

**Issue**

There is a menu one reaches thusly: right-click a panel icon that is managed by the Grouped Window List applet, then click 'Preferences'. That menu contains an item comprising this text: 'Remove "Grouped window list'. Now:

* that removal item is immediately below a menu item called 'Configure...' ;
* the pointer ends up over that removal item (it does on my system anyway);
* if the user is hunting for the options for the applet in question (against other panel options), she will be minded to click anything that mentions 'grouped window list';
* the removal of the applet occurs without confirmation.

**Steps to reproduce**

See above.

**Expected behaviour**

It should be less easy to accidentally remove the applet from the panel. A confirmation dialog might be the simplest solution.

**Comment by clefebvre** [comment]
A global confirmation dialog to remove any applet could work.

**Comment by LinuxOnTheDesktop** [comment]
Marvellous! However: seeing that there was an update today to the Mate-menu package, I installed the update, restarted Cinnamon, choose to remove the Grouped Window List and . . (1) that applet disappeared immediately, (2) when I re-added it, the applet window showed a red exclamation mark, together with a tooltip that said that something had gone wrong and that I short report the problem.

**Comment by LinuxOnTheDesktop** [comment]
Also, I find the following. When I run ksyslog, it appears in my panel - in the Grouped Window List - but has no 'pin to panel' menu item. xed, on the other hand, shows the pin option. Perhaps the problem owes to my Grouped Window List configuration being nuked. Anyhow, I think I'll just restore `/` from backup. If that doesn't work, I'll try restoring some `/home` stuff.

**Comment by LinuxOnTheDesktop** [comment]
(I closed this issue by mistake. So I re-opened it.)

**Comment by LinuxOnTheDesktop** [comment]
Please advise how to restore my panel configuration or rather my Grouped Window List configuration. (I have the Grouped Window List on one panel. I have two other panels. The two other panels are fine.)  I tried restoring `/` using Timeshift - it did not work. I restored (from rclone backup) `~/.cinnamon` and `~/.config` - and that did not work either.

**Comment by LinuxOnTheDesktop** [comment]
Also: why not add a separator between the menu item 'Configure' and the menu item 'Remove [. .]'? This seems to be the sort of job the separator is for.
