### ISSUE TITLE
19.1 Cinnamon 32-bit won't update

### ISSUE THREAD

**Issue by gb-dursley** [linuxmint/cinnamon#8635]
```
 * Cinnamon version (cinnamon --version)
 * 32 - bit
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog ???

 ```
**Background
Installed from current 32-bit .iso image on DVD onto an old F-J Amilo 1818 laptop as dual boot with existing Mint 18.3 that is problem-free apart from antique Wine.

**Issue**
Initial Update from First Steps window - Update Manager fails with two notifications in separate windows:
1)
  Update error:-
    E: gconf2 : dependency problems _(about 10 identical entries)_
2)
  Errors were encountered while processing:
   libwebkitgtk-4.0-37:i386

Synaptic Package Manager shows libwebkitgtk-4.0-37 as the only broken package. 

**Steps to reproduce**
Run Package Manager _(takes about 20 minutes to download and run!)_

**Expected behaviour**
Update Manager runs flawlessly.

**Other information**
Please don't offer possible solutions requiring use of Terminal - I'm too old!

**Comment by JosephMcc** [comment]
I'm closing this since it doesn't seem to be a cinnamon issue. It's honestly a little hard to know given you didn't even fill out the issue template. This sounds like the type of issue that would be best solved by asking for help on the Linux Mint forums.
