### ISSUE TITLE
System tray hides icons, fails to launch properly

### ISSUE THREAD

**Issue by Yournished** [linuxmint/cinnamon#8637]
```
 * Cinnamon 3.8.8
 * Debian testing
 * Integrated graphics
 * 64 bit
 ```

**Issue**

Something went wrong while loading systray@cinnamon.org. Please make sure you are using the latest version, then report the issue to the developers.

**Steps to reproduce**

Go to Cinnamon menu
Type Applets
Open Applets
Go to Manage tab
Find System tray
Disable
Enable
It has a stop icon
Mouse over
See message tooltip with error

**Other information**

Also won't show some icons like Nextcloud client and Pragha won't properly integrate into volume button, flag randomly switches to smaller icons sometimes.
[xsession-errors.txt](https://github.com/linuxmint/cinnamon/files/3284167/xsession-errors.txt)

**Comment by leigh123linux** [comment]
Feel free to reopen if you can reproduce on a supported cinnamon version.
