### ISSUE TITLE
Grouped Window List: juddering when moving items

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/cinnamon#8639]
```
 * Cinnamon version (cinnamon --version) 4.0.10
   - Please specify if you are using the daily builds PPA (https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds): yes, but problem predates the alpha.
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 19.1.
 * Graphics hardware *and* driver used: Intel UHD Graphics 620 3.0 Mesa 18.2.8.
 * 32 or 64 bit: 64
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
 ```

**Issue**

When dragging items within the Grouped Window List applet, they judder from one position to another. That looks bad and makes the applet harder to use.

**Steps to reproduce**

Try dragging an item around a bit.
I'd attach a video but the Mint video tool remains broken (will hang the PC), so far as I know.

**Expected behaviour**

No juddering. Implementing some sort of threshold would do it, I imagine.

**Other information**

This is a cosmetic issue that many people will run into and it does not make the OS look good. Or so it seems to me.

**Comment by JosephMcc** [comment]
I see what you mean here. It's very minor but would be nice if it was a bit smoother looking.

**Comment by LinuxOnTheDesktop** [comment]
One can underestimate the effect that such problems, especially in concert (i.e. when the user encounters multiple such problems) upon the user. Also and as I said: this particular problem is not wholly cosmetic.
