### ISSUE TITLE
Sound Applet fails to keep player running on the background / in tray

### ISSUE THREAD

**Issue by Danko8321** [linuxmint/Cinnamon#864]
I couldn't help to notice that when the notification area icon is enabled on Banshee it doesn't automatically merge with the Sound Applet until the Shell is restarted. I was informed that this was unnecesary because the Notification area applet could be (and it was on Lisa) replaced by the Sound applet on Cinnamon and the Music Player extension on Gnome Shell. I tried to do this and noticed that the Sound applet fails to actually keep banshee running if the Notification area Icon is disabled and. So, what we have here is mostly aesthetic issue, but I feel it should get filed. 

Cinnamon version: 1.4-UP3

OS: Linux Mint 13

How to reproduce this issue: Open up banshee; if the notification area extension is enabled, you'll inmediately see the banshee icon there. If Cinnamon restarted, notification icon will go away and merge with Sound applet. If notification area disabled, banshee dies when closed instead of running on the background.

**Comment by dalcde** [comment]
I'm pretty sure this no longer happens on Cinnamon 2.4. Can someone confirm?
