### ISSUE TITLE
Traditional layout option

### ISSUE THREAD

**Issue by greenpeteuk** [linuxmint/cinnamon#8641]
I hope this is the right place to ask this...

Will the ability to choose the traditional layout be kept indefinitely?

I find the new layout undesirable and love(d) Cinnamon for the way it was, somewhat unique and not following the trends but leading them.

Apologise if this is not the right place for such questions.

Thank-you in advance :-)

**Comment by JosephMcc** [comment]
I assume you are talking about the ability to switch easily to this layout in mintwelcome. There are no plans to remove this nor are there any to remove the ability to get back to the old layout manually.

**Comment by greenpeteuk** [comment]
That's great to know, thank you!
