### ISSUE TITLE
no sound icon in system tray

### ISSUE THREAD

**Issue by illumilore** [linuxmint/cinnamon#8642]
```
 * Cinnamon version (cinnamon --version)
Cinnamon 4.0.10

   - Please specify if you are using the daily builds PPA (https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds).
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
Mint 19.1
 * Graphics hardware *and* driver used
 * 32 or 64 bit
nvidia 1050ti 64 bit
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
Cjs-Message: 17:36:33.231: JS LOG: About to start Cinnamon
Cjs-Message: 17:36:33.378: JS LOG: [LookingGlass/info] Cinnamon.AppSystem.get_default() started in 146 ms
Cjs-Message: 17:36:33.383: JS LOG: [LookingGlass/info] loading default theme
Cjs-Message: 17:36:33.739: JS LOG: [LookingGlass/info] PlacesManager: Updating devices
St-Message: 17:36:33.763: cogl npot texture sizes SUPPORTED
Cjs-Message: 17:36:33.782: JS LOG: [LookingGlass/info] loaded at Fri Jun 14 2019 17:36:33 GMT-0600 (MDT)
Cjs-Message: 17:36:33.782: JS LOG: Cinnamon started at Fri Jun 14 2019 17:36:33 GMT-0600 (MDT)
Cjs-Message: 17:36:33.826: JS LOG: [LookingGlass/info] ExtensionSystem started in 2 ms
Cjs-Message: 17:36:33.826: JS LOG: [LookingGlass/info] DeskletManager started in 2 ms
Cjs-Message: 17:36:33.826: JS LOG: [LookingGlass/info] SearchProviderManager started in 0 ms
openGL version 3.1 detected (GL3 Cogl Driver)
Cjs-Message: 17:36:34.164: JS LOG: [LookingGlass/info] Loaded applet user@cinnamon.org in 82 ms
Cjs-Message: 17:36:34.182: JS LOG: [LookingGlass/info] Loaded applet separator@cinnamon.org in 18 ms
Cjs-Message: 17:36:34.203: JS LOG: [LookingGlass/info] Loaded applet removable-drives@cinnamon.org in 20 ms
Cjs-Message: 17:36:34.263: JS LOG: [LookingGlass/info] Loaded applet spacer@cinnamon.org in 60 ms
Cjs-Message: 17:36:34.264: JS LOG: [LookingGlass/info] Loaded applet spacer@cinnamon.org in 2 ms
Cjs-Message: 17:36:34.264: JS LOG: [LookingGlass/info] Loaded applet spacer@cinnamon.org in 0 ms
Cjs-Message: 17:36:34.265: JS LOG: [LookingGlass/info] Loaded applet separator@cinnamon.org in 0 ms
Cjs-Message: 17:36:34.265: JS LOG: [LookingGlass/info] Loaded applet spacer@cinnamon.org in 0 ms
Cjs-Message: 17:36:34.265: JS LOG: [LookingGlass/info] Loaded applet spacer@cinnamon.org in 0 ms
Cjs-Message: 17:36:34.266: JS LOG: [LookingGlass/info] Loaded applet spacer@cinnamon.org in 2 ms
Cjs-Message: 17:36:34.295: JS LOG: [LookingGlass/info] Loaded applet show-desktop@cinnamon.org in 28 ms
Cjs-Message: 17:36:34.296: JS LOG: [LookingGlass/info] Loaded applet show-desktop@cinnamon.org in 0 ms
Cjs-Message: 17:36:34.308: JS LOG: [LookingGlass/info] Role locked: notifications
Cjs-Message: 17:36:34.319: JS LOG: [LookingGlass/info] Loaded applet notifications@cinnamon.org in 22 ms
Cjs-Message: 17:36:34.342: JS LOG: [LookingGlass/info] Loaded applet workspace-switcher@cinnamon.org in 24 ms

Cjs-Message: 17:36:34.391: JS LOG: [LookingGlass/info] Loaded applet calendar@cinnamon.org in 48 ms
Cjs-Message: 17:36:34.396: JS LOG: [LookingGlass/info] Role locked: tray
Cjs-Message: 17:36:34.399: JS LOG: [LookingGlass/info] Loaded applet systray@cinnamon.org in 8 ms
Cjs-Message: 17:36:34.449: JS LOG: [LookingGlass/info] Loaded applet redshift@marvel4u in 50 ms
Cjs-Message: 17:36:34.571: JS LOG: [LookingGlass/info] Role locked: panellauncher
Cjs-Message: 17:36:34.806: JS LOG: [LookingGlass/info] Loaded applet panel-launchers@cinnamon.org in 358 ms
Cjs-Message: 17:36:34.807: JS LOG: [LookingGlass/info] Loaded applet panel-launchers@cinnamon.org in 0 ms
Cjs-Message: 17:36:34.807: JS LOG: [LookingGlass/info] Loaded applet panel-launchers@cinnamon.org in 0 ms
Cjs-Message: 17:36:34.884: JS LOG: [LookingGlass/info] Loaded applet placesCenter@scollins in 78 ms
Cjs-Message: 17:36:34.885: JS LOG: [LookingGlass/info] Loaded applet panel-launchers@cinnamon.org in 0 ms
Cjs-Message: 17:36:35.067: JS LOG: [LookingGlass/info] Loaded applet window-list@cinnamon.org in 182 ms
Cjs-Message: 17:36:35.068: JS LOG: [LookingGlass/info] Loaded applet window-list@cinnamon.org in 2 ms
Cjs-Message: 17:36:35.089: JS LOG: [LookingGlass/info] Error getting Cinnamon backlight power settings true,,Error: GDBus.Error:org.gtk.GDBus.UnmappedGError.Quark._csd_5fpower_5fmanager_5ferror.Code0:
Cjs-Message: 17:36:35.098: JS LOG: [LookingGlass/info] Loaded applet window-list@cinnamon.org in 30 ms
Cjs-Message: 17:36:35.100: JS LOG: [LookingGlass/info] Upgrading settings for weather@mockturtl
Cjs-Message: 17:36:35.100: JS LOG: [LookingGlass/info] Settings successfully upgraded for weather@mockturtl
Cjs-Message: 17:36:35.114: JS WARNING: [/usr/share/cinnamon/js/misc/fileUtils.js line 210 > Function 235]: reference to undefined property "provider"
Cjs-Message: 17:36:35.133: JS LOG: [LookingGlass/info] Loaded applet weather@mockturtl in 34 ms
Cjs-Message: 17:36:35.160: JS LOG: [LookingGlass/info] Loaded applet network@cinnamon.org in 28 ms
Cjs-Message: 17:36:35.200: JS LOG: Unknown network device type, is 14
Cjs-Message: 17:36:36.433: JS LOG: [LookingGlass/info] Loaded applet CinnVIIStarkMenu@NikoKrause in 1272 ms
Cjs-Message: 17:36:36.433: JS LOG: [LookingGlass/info] AppletManager started in 2650 ms
Cjs-Message: 17:36:36.436: JS LOG: [LookingGlass/info] Cinnamon took 3206 ms to start
Cjs-Message: 17:36:37.158: JS LOG: [LookingGlass/info] Adding systray: audacious (24x24px)
Cjs-Message: 17:36:37.158: JS LOG: [LookingGlass/info] Resized audacious with normalized size (24x24px)
Cjs-Message: 17:36:37.161: JS LOG: [LookingGlass/info] Adding systray: kdocker (24x24px)
Cjs-Message: 17:36:37.161: JS LOG: [LookingGlass/info] Resized kdocker with normalized size (24x24px)
Cjs-Message: 17:36:37.164: JS LOG: [LookingGlass/info] Adding systray: mintupdate.py (24x24px)
Cjs-Message: 17:36:37.164: JS LOG: [LookingGlass/info] Resized mintupdate.py with normalized size (24x24px)
Cjs-Message: 17:36:37.166: JS LOG: [LookingGlass/info] Adding systray: /modules/kdeconnect/devices/0ea15721bad1fca9 (24x24px)
Cjs-Message: 17:36:37.166: JS LOG: [LookingGlass/info] Resized /modules/kdeconnect/devices/0ea15721bad1fca9 with normalized size (24x24px)
Cjs-Message: 17:36:37.168: JS LOG: [LookingGlass/info] Adding systray: nxclient.bin (24x24px)
Cjs-Message: 17:36:37.169: JS LOG: [LookingGlass/info] Resized nxclient.bin with normalized size (24x24px)
Cjs-Message: 17:36:37.170: JS LOG: [LookingGlass/info] Hiding systray: network
Cjs-Message: 17:36:37.518: JS LOG: [LookingGlass/info] weather@mockturtl#18: Weather Information refreshed

(cinnamon:25986): Cjs-WARNING **: 17:38:30.396: JS ERROR: TypeError: metaWindow.get_compositor_private(...) is null
_onWindowMonitorChanged@/usr/share/cinnamon/applets/window-list@cinnamon.org/applet.js:1099:14


(cinnamon:25986): Cjs-WARNING **: 17:38:30.397: JS ERROR: TypeError: metaWindow.get_compositor_private(...) is null
_onWindowMonitorChanged@/usr/share/cinnamon/applets/window-list@cinnamon.org/applet.js:1099:14


(cinnamon:25986): Cjs-WARNING **: 17:38:30.397: JS ERROR: TypeError: metaWindow.get_compositor_private(...) is null
_onWindowMonitorChanged@/usr/share/cinnamon/applets/window-list@cinnamon.org/applet.js:1099:14

 ```

**Issue**
In cinnamon, after an update from 4.0.9 i guess, the sound icon for the system tray volume is gone. When trying to add new applets, there is no entry for sound icons.

**Steps to reproduce**

**Expected behaviour**

**Other information**

**Comment by germanfr** [comment]
There is no trace of the sound applet in your log. Make sure it is in one of your panels. Go to `System Settings > Applets` and check the sound applet is enabled.

**Comment by germanfr** [comment]
Also, post the output of `find /usr/share/cinnamon/applets/`.

**Comment by illumilore** [comment]
There doesn't seem to be any sound applet in the applets menu in system settings. There was one that was in the download tab but that one doesn't show up.

/usr/share/cinnamon/applets/
/usr/share/cinnamon/applets/window-list@cinnamon.org
/usr/share/cinnamon/applets/window-list@cinnamon.org/applet.js
/usr/share/cinnamon/applets/window-list@cinnamon.org/settings-schema.json
/usr/share/cinnamon/applets/window-list@cinnamon.org/metadata.json
/usr/share/cinnamon/applets/panel-launchers@cinnamon.org
/usr/share/cinnamon/applets/panel-launchers@cinnamon.org/applet.js
/usr/share/cinnamon/applets/panel-launchers@cinnamon.org/settings-schema.json
/usr/share/cinnamon/applets/panel-launchers@cinnamon.org/metadata.json
/usr/share/cinnamon/applets/on-screen-keyboard@cinnamon.org
/usr/share/cinnamon/applets/on-screen-keyboard@cinnamon.org/applet.js
/usr/share/cinnamon/applets/on-screen-keyboard@cinnamon.org/metadata.json
/usr/share/cinnamon/applets/on-screen-keyboard@cinnamon.org/icons
/usr/share/cinnamon/applets/on-screen-keyboard@cinnamon.org/icons/on-screen-keyboard-symbolic.svg
/usr/share/cinnamon/applets/on-screen-keyboard@cinnamon.org/icons/on-screen-keyboard-disabled-symbolic.svg
/usr/share/cinnamon/applets/inhibit@cinnamon.org
/usr/share/cinnamon/applets/inhibit@cinnamon.org/applet.js
/usr/share/cinnamon/applets/inhibit@cinnamon.org/metadata.json
/usr/share/cinnamon/applets/inhibit@cinnamon.org/icons
/usr/share/cinnamon/applets/inhibit@cinnamon.org/icons/inhibit-symbolic.svg
/usr/share/cinnamon/applets/inhibit@cinnamon.org/icons/inhibit-active-symbolic.svg
/usr/share/cinnamon/applets/show-desktop@cinnamon.org
/usr/share/cinnamon/applets/show-desktop@cinnamon.org/applet.js
/usr/share/cinnamon/applets/show-desktop@cinnamon.org/settings-schema.json
/usr/share/cinnamon/applets/show-desktop@cinnamon.org/metadata.json
/usr/share/cinnamon/applets/trash@cinnamon.org
/usr/share/cinnamon/applets/trash@cinnamon.org/applet.js
/usr/share/cinnamon/applets/trash@cinnamon.org/metadata.json
/usr/share/cinnamon/applets/expo@cinnamon.org
/usr/share/cinnamon/applets/expo@cinnamon.org/applet.js
/usr/share/cinnamon/applets/expo@cinnamon.org/settings-schema.json
/usr/share/cinnamon/applets/expo@cinnamon.org/metadata.json
/usr/share/cinnamon/applets/expo@cinnamon.org/icons
/usr/share/cinnamon/applets/expo@cinnamon.org/icons/cinnamon-expo-symbolic.svg
/usr/share/cinnamon/applets/user@cinnamon.org
/usr/share/cinnamon/applets/user@cinnamon.org/applet.js
/usr/share/cinnamon/applets/user@cinnamon.org/stylesheet.css
/usr/share/cinnamon/applets/user@cinnamon.org/settings-schema.json
/usr/share/cinnamon/applets/user@cinnamon.org/metadata.json
/usr/share/cinnamon/applets/user@cinnamon.org/icons
/usr/share/cinnamon/applets/user@cinnamon.org/icons/logout-symbolic.svg
/usr/share/cinnamon/applets/user@cinnamon.org/icons/switch-user-symbolic.svg
/usr/share/cinnamon/applets/separator@cinnamon.org
/usr/share/cinnamon/applets/separator@cinnamon.org/applet.js
/usr/share/cinnamon/applets/separator@cinnamon.org/metadata.json
/usr/share/cinnamon/applets/workspace-switcher@cinnamon.org
/usr/share/cinnamon/applets/workspace-switcher@cinnamon.org/applet.js
/usr/share/cinnamon/applets/workspace-switcher@cinnamon.org/settings-schema.json
/usr/share/cinnamon/applets/workspace-switcher@cinnamon.org/metadata.json
/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org
/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/applet.js
/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/utils.py
/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/menus.js
/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/appGroup.js
/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/appList.js
/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/settings-schema.json
/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/constants.js
/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/metadata.json
/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/icons
/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/icons/x-office-database-symbolic.svg
/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/icons/x-office-math-symbolic.svg
/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/icons/news-symbolic.svg
/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/icons/store-symbolic.svg
/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/icons/screenshot-fullscreen-symbolic.svg
/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/icons/window-new-symbolic.svg
/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/icons/pin-symbolic.svg
/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/icons/screenshot-window-symbolic.svg
/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/icons/view-private-symbolic.svg
/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/icons/screenshot-area-symbolic.svg
/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/icons/unpin-symbolic.svg
/usr/share/cinnamon/applets/calendar@cinnamon.org
/usr/share/cinnamon/applets/calendar@cinnamon.org/calendar.js
/usr/share/cinnamon/applets/calendar@cinnamon.org/applet.js
/usr/share/cinnamon/applets/calendar@cinnamon.org/settings-schema.json
/usr/share/cinnamon/applets/calendar@cinnamon.org/metadata.json
/usr/share/cinnamon/applets/network@cinnamon.org
/usr/share/cinnamon/applets/network@cinnamon.org/applet.js
/usr/share/cinnamon/applets/network@cinnamon.org/metadata.json
/usr/share/cinnamon/applets/network@cinnamon.org/icons
/usr/share/cinnamon/applets/network@cinnamon.org/icons/network-wireless-signal-ok-secure-symbolic.svg
/usr/share/cinnamon/applets/network@cinnamon.org/icons/network-wireless-signal-excellent-secure-symbolic.svg
/usr/share/cinnamon/applets/network@cinnamon.org/icons/network-wireless-signal-good-secure-symbolic.svg
/usr/share/cinnamon/applets/network@cinnamon.org/icons/network-wireless-signal-none-secure-symbolic.svg
/usr/share/cinnamon/applets/network@cinnamon.org/icons/network-wireless-signal-weak-secure-symbolic.svg
/usr/share/cinnamon/applets/recent@cinnamon.org
/usr/share/cinnamon/applets/recent@cinnamon.org/applet.js
/usr/share/cinnamon/applets/recent@cinnamon.org/metadata.json
/usr/share/cinnamon/applets/settings@cinnamon.org
/usr/share/cinnamon/applets/settings@cinnamon.org/applet.js
/usr/share/cinnamon/applets/settings@cinnamon.org/metadata.json
/usr/share/cinnamon/applets/power@cinnamon.org
/usr/share/cinnamon/applets/power@cinnamon.org/applet.js
/usr/share/cinnamon/applets/power@cinnamon.org/settings-schema.json
/usr/share/cinnamon/applets/power@cinnamon.org/metadata.json
/usr/share/cinnamon/applets/removable-drives@cinnamon.org
/usr/share/cinnamon/applets/removable-drives@cinnamon.org/applet.js
/usr/share/cinnamon/applets/removable-drives@cinnamon.org/metadata.json
/usr/share/cinnamon/applets/slideshow@cinnamon.org
/usr/share/cinnamon/applets/slideshow@cinnamon.org/applet.js
/usr/share/cinnamon/applets/slideshow@cinnamon.org/metadata.json
/usr/share/cinnamon/applets/slideshow@cinnamon.org/icons
/usr/share/cinnamon/applets/slideshow@cinnamon.org/icons/slideshow-pause-symbolic.svg
/usr/share/cinnamon/applets/slideshow@cinnamon.org/icons/slideshow-play-symbolic.svg
/usr/share/cinnamon/applets/slideshow@cinnamon.org/icons/slideshow-disabled-symbolic.svg
/usr/share/cinnamon/applets/scale@cinnamon.org
/usr/share/cinnamon/applets/scale@cinnamon.org/applet.js
/usr/share/cinnamon/applets/scale@cinnamon.org/settings-schema.json
/usr/share/cinnamon/applets/scale@cinnamon.org/metadata.json
/usr/share/cinnamon/applets/scale@cinnamon.org/icons
/usr/share/cinnamon/applets/scale@cinnamon.org/icons/cinnamon-scale-symbolic.svg
/usr/share/cinnamon/applets/keyboard@cinnamon.org
/usr/share/cinnamon/applets/keyboard@cinnamon.org/applet.js
/usr/share/cinnamon/applets/keyboard@cinnamon.org/metadata.json
/usr/share/cinnamon/applets/menu@cinnamon.org
/usr/share/cinnamon/applets/menu@cinnamon.org/applet.js
/usr/share/cinnamon/applets/menu@cinnamon.org/settings-schema.json
/usr/share/cinnamon/applets/menu@cinnamon.org/metadata.json
/usr/share/cinnamon/applets/a11y@cinnamon.org
/usr/share/cinnamon/applets/a11y@cinnamon.org/applet.js
/usr/share/cinnamon/applets/a11y@cinnamon.org/metadata.json
/usr/share/cinnamon/applets/blueberry@cinnamon.org
/usr/share/cinnamon/applets/blueberry@cinnamon.org/applet.js
/usr/share/cinnamon/applets/blueberry@cinnamon.org/metadata.json
/usr/share/cinnamon/applets/blueberry@cinnamon.org/icons
/usr/share/cinnamon/applets/blueberry@cinnamon.org/icons/blueberry-applet-connected-symbolic.svg
/usr/share/cinnamon/applets/blueberry@cinnamon.org/icons/blueberry-applet-symbolic.svg
/usr/share/cinnamon/applets/blueberry@cinnamon.org/icons/blueberry-applet-disabled-symbolic.svg
/usr/share/cinnamon/applets/settings-example@cinnamon.org
/usr/share/cinnamon/applets/settings-example@cinnamon.org/CustomWidget.py
/usr/share/cinnamon/applets/settings-example@cinnamon.org/applet.js
/usr/share/cinnamon/applets/settings-example@cinnamon.org/settings-schema.json
/usr/share/cinnamon/applets/settings-example@cinnamon.org/metadata.json
/usr/share/cinnamon/applets/systray@cinnamon.org
/usr/share/cinnamon/applets/systray@cinnamon.org/applet.js
/usr/share/cinnamon/applets/systray@cinnamon.org/metadata.json
/usr/share/cinnamon/applets/spacer@cinnamon.org
/usr/share/cinnamon/applets/spacer@cinnamon.org/applet.js
/usr/share/cinnamon/applets/spacer@cinnamon.org/settings-schema.json
/usr/share/cinnamon/applets/spacer@cinnamon.org/metadata.json
/usr/share/cinnamon/applets/notifications@cinnamon.org
/usr/share/cinnamon/applets/notifications@cinnamon.org/applet.js
/usr/share/cinnamon/applets/notifications@cinnamon.org/settings-schema.json
/usr/share/cinnamon/applets/notifications@cinnamon.org/metadata.json
/usr/share/cinnamon/applets/notifications@cinnamon.org/icons
/usr/share/cinnamon/applets/notifications@cinnamon.org/icons/normal-notif-symbolic.svg
/usr/share/cinnamon/applets/notifications@cinnamon.org/icons/low-notif-symbolic.svg
/usr/share/cinnamon/applets/notifications@cinnamon.org/icons/critical-notif-symbolic.svg
/usr/share/cinnamon/applets/notifications@cinnamon.org/icons/empty-notif-symbolic.svg
/usr/share/cinnamon/applets/notifications@cinnamon.org/icons/alt-critical-notif-symbolic.svg
/usr/share/cinnamon/applets/nvidia-prime@cinnamon.org
/usr/share/cinnamon/applets/nvidia-prime@cinnamon.org/applet.js
/usr/share/cinnamon/applets/nvidia-prime@cinnamon.org/metadata.json
/usr/share/cinnamon/applets/nvidia-prime@cinnamon.org/icons
/usr/share/cinnamon/applets/nvidia-prime@cinnamon.org/icons/prime-applet-nvidia-symbolic.svg
/usr/share/cinnamon/applets/nvidia-prime@cinnamon.org/icons/prime-applet-intel-symbolic.svg
/usr/share/cinnamon/applets/nvidia-prime@cinnamon.org/icon.png
/usr/share/cinnamon/applets/windows-quick-list@cinnamon.org
/usr/share/cinnamon/applets/windows-quick-list@cinnamon.org/applet.js
/usr/share/cinnamon/applets/windows-quick-list@cinnamon.org/metadata.json
/usr/share/cinnamon/applets/windows-quick-list@cinnamon.org/icons
/usr/share/cinnamon/applets/windows-quick-list@cinnamon.org/icons/windows-quick-list-symbolic.svg
/usr/share/cinnamon/applets/xrandr@cinnamon.org
/usr/share/cinnamon/applets/xrandr@cinnamon.org/applet.js
/usr/share/cinnamon/applets/xrandr@cinnamon.org/stylesheet.css
/usr/share/cinnamon/applets/xrandr@cinnamon.org/metadata.json

**Comment by JosephMcc** [comment]
sound@cinnamon.org is part of the default install and you do seem to missing it somehow

**Comment by JosephMcc** [comment]
I'm going to close this since the applet you want is included in a default install. Somehow yours is missing and we have no what to troubleshoot what might have happened.
