### ISSUE TITLE
Cinnamon Crashes After Change to Default Python 3 despite Python is in system default location

### ISSUE THREAD

**Issue by marcodsad** [linuxmint/cinnamon#8649]
```
 Cinnamon version 3.8.9
Distribution - Mint 19
Graphics hardware:
01:00.0 VGA compatible controller: NVIDIA Corporation GK106GLM [Quadro K2100M] (rev a1) (prog-if 00 [VGA controller])
Subsystem: Dell GK106GLM [Quadro K2100M]
Flags: bus master, fast devsel, latency 0, IRQ 31
Memory at f4000000 (32-bit, non-prefetchable) [size=16M]
Memory at e0000000 (64-bit, prefetchable) [size=256M]
Memory at f0000000 (64-bit, prefetchable) [size=32M]
I/O ports at e000 [size=128]
[virtual] Expansion ROM at 000c0000 [disabled] [size=128K]
Capabilities: 
Kernel driver in use: nvidia
Kernel modules: nvidiafb, nouveau, nvidia_drm, nvidia
01:00.1 Audio device: NVIDIA Corporation GK106 HDMI Audio Controller (rev a1)

64 bit

 ```

**Issue**

Cinnamon crashed after a restart following a change of default python3 version (from 3.6.8 to 3.7.3).

After a restart, there was no taskbar, no desktop background, common shortcuts didn't work (CTR-ALT-T didn't open a terminal), windows were not resizeable. The whole system becomes essentially unusable.

Hi, I'm aware this thread has been closed [elsewhere](https://github.com/linuxmint/cinnamon/issues/7910), but the solution suggested there does not work for my issue, and the conditions of my issue contradict the answer provided to close the previous thread. 

In the previous thread, according to @mtwebster: "You can install different versions of python freely, the important part is not changing the system default locations. Introspection (from gi.repository import ***) is not smart enough to check across multiple locations."

i.e., installing python alternatives in the default locations should avoid Cinnamon crash. However, at least in my case, installing in default location still crashes Cinnamon, rendering my laptop unusable.

Thanks.

journalctl -b 0 -p 0..3 log for the crashing session
[cinna-log_Z.txt](https://github.com/linuxmint/cinnamon/files/3300046/cinna-log_Z.txt)

**Steps to reproduce**

1. Don't touch the original python (python 2.7.15).
2. Install alternative python versions (3.6.8 and 3.7.3) to a system
3. Use update-alternatives tool to manage default python3 version -
[link](https://jcutrer.com/linux/upgrade-python37-ubuntu1810 
)
4. sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.6 8
5. sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.7 3
6. Change the default python3 version to 3.6 - sudo update-alternatives --config python3

**Expected behaviour**

No changes expected.

**Other information**

**Comment by leigh123linux** [comment]
Feel free to reopen if you can produce on current cinnamon-4.x.x
