### ISSUE TITLE
No option to unhide systray icons

### ISSUE THREAD

**Issue by illumilore** [linuxmint/cinnamon#8652]
```
 * Cinnamon version (cinnamon --version)
Cinnamon 4.0.10
   - Please specify if you are using the daily builds PPA (https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds).
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
mint 19.1

 * Attach /home/<username>/.xsession-errors, or /var/log/syslog

Cjs-Message: 08:59:59.536: JS LOG: [LookingGlass/info] Hiding systray: audacious
Cjs-Message: 09:00:02.286: JS LOG: [LookingGlass/info] Hiding systray: audacious
Cjs-Message: 09:00:06.325: JS LOG: [LookingGlass/info] Hiding systray: audacious

 ```

**Issue**
When cinnamon starts, a systray icon for audacious is present, but if cinnamon restarts, then the icon disappears, the logs saying it is being hidden, and there seems to be no option to make it show, and no options for systray in general. 

**Steps to reproduce**
**Expected behaviour**
For the icon to not be hidden by default and for there to be an option to unhide it.

**Other information**
The logs also say network is hidden but it is not.
Cjs-Message: 08:59:47.801: JS LOG: [LookingGlass/info] Hiding systray: network

**Comment by icarter09** [comment]
@illumilore check to see if the `Hide system tray icons for compatible players` is enabled prior to Cinnamon restarting.

**Comment by illumilore** [comment]
> @illumilore check to see if the `Hide system tray icons for compatible players` in the Sound applet configuration is enabled prior to Cinnamon restarting.

That fixed it, thanks. I was expecting the setting for that to be in the system tray options
