### ISSUE TITLE
Cinnamon crashes when trying to edit panel

### ISSUE THREAD

**Issue by illumilore** [linuxmint/cinnamon#8653]
```
 * Cinnamon version (cinnamon --version)  Cinnamon 4.0.10
   - Please specify if you are using the daily builds PPA (https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds).
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)  mint 19.1
 * Graphics hardware *and* driver used  nvidia 430.26
 * 32 or 64 bit 64

 ```

**Issue**

When right clicking on a panel, and then hitting edit panel mode toggle, cinnamon freezes

**Other information**
Cjs-Message: 13:19:01.854: JS LOG: [LookingGlass/info] weather@mockturtl#18: Weather Information refreshed
Cjs-Message: 13:34:16.685: JS LOG: [LookingGlass/info] weather@mockturtl#18: Weather Information refreshed
Cjs-Message: 13:49:31.715: JS LOG: [LookingGlass/info] weather@mockturtl#18: Weather Information refreshed
Cinnamon warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x7c00010 (Inbox - zo)
Cinnamon warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x7c00010 (Inbox - zo)
Cinnamon warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x7c00010 (Inbox - lu)
Cjs-Message: 13:58:45.731: JS LOG: [LookingGlass/info] Adding systray: /modules/kdeconnect/devices/f950ad2121b8cb0c (24x24px)
Cjs-Message: 13:58:45.733: JS LOG: [LookingGlass/info] Resized /modules/kdeconnect/devices/f950ad2121b8cb0c with normalized size (24x24px)
(cinnamon:31529): Cjs-CRITICAL **: 14:03:46.284: Object Cinnamon.GenericContainer (0x55a15c135b90), has been already finalized. Impossible to set any property to it.
== Stack trace for context 0x55a157dd94c0 ==
#0 0x55a158731d70 i   /usr/share/cinnamon/js/misc/fileUtils.js line 210 > Function:369 (0x7f4801e71340 @ 91)
#1 0x7ffd4cba6e70 b   self-hosted:918 (0x7f48640e5560 @ 394)
#2 0x55a158731ce0 i   /usr/share/cinnamon/js/ui/overrides.js:51 (0x7f48640c8780 @ 44)
#3 0x55a158731c40 i   /usr/share/cinnamon/js/ui/overrides.js:83 (0x7f48640c8ab0 @ 36)
#4 0x55a158731bb8 i   /usr/share/cinnamon/js/ui/panel.js:1626 (0x7f485571bab0 @ 30)
#5 0x7ffd4cba9e60 b   resource:///org/cinnamon/cjs/modules/signals.js:142 (0x7f48640d6ef0 @ 386)
#6 0x55a158731b28 i   /usr/share/cinnamon/js/ui/popupMenu.js:868 (0x7f485574a918 @ 56)
#7 0x55a158731a90 i   /usr/share/cinnamon/js/ui/popupMenu.js:860 (0x7f485574a890 @ 42)
#8 0x55a158731a00 i   /usr/share/cinnamon/js/ui/popupMenu.js:152 (0x7f485573bde0 @ 21)
#9 0x7ffd4cbab810 I   self-hosted:918 (0x7f48640e5560 @ 394)

(cinnamon:31529): Cjs-CRITICAL **: 14:03:46.284: Object Cinnamon.GenericContainer (0x55a15c256b90), has been already finalized. Impossible to set any property to it.
== Stack trace for context 0x55a157dd94c0 ==
#0 0x55a158731d70 i   /usr/share/cinnamon/js/misc/fileUtils.js line 210 > Function:369 (0x7f4801e71340 @ 91)
#1 0x7ffd4cba6e70 b   self-hosted:918 (0x7f48640e5560 @ 394)
#2 0x55a158731ce0 i   /usr/share/cinnamon/js/ui/overrides.js:51 (0x7f48640c8780 @ 44)
#3 0x55a158731c40 i   /usr/share/cinnamon/js/ui/overrides.js:83 (0x7f48640c8ab0 @ 36)
#4 0x55a158731bb8 i   /usr/share/cinnamon/js/ui/panel.js:1626 (0x7f485571bab0 @ 30)
#5 0x7ffd4cba9e60 b   resource:///org/cinnamon/cjs/modules/signals.js:142 (0x7f48640d6ef0 @ 386)
#6 0x55a158731b28 i   /usr/share/cinnamon/js/ui/popupMenu.js:868 (0x7f485574a918 @ 56)
#7 0x55a158731a90 i   /usr/share/cinnamon/js/ui/popupMenu.js:860 (0x7f485574a890 @ 42)
#8 0x55a158731a00 i   /usr/share/cinnamon/js/ui/popupMenu.js:152 (0x7f485573bde0 @ 21)
#9 0x7ffd4cbab810 I   self-hosted:918 (0x7f48640e5560 @ 394)

(cinnamon:31529): Cjs-CRITICAL **: 14:03:46.284: Object Cinnamon.GenericContainer (0x55a15c257b10), has been already finalized. Impossible to set any property to it.
== Stack trace for context 0x55a157dd94c0 ==
#0 0x55a158731d70 i   /usr/share/cinnamon/js/misc/fileUtils.js line 210 > Function:369 (0x7f4801e71340 @ 91)
#1 0x7ffd4cba6e70 b   self-hosted:918 (0x7f48640e5560 @ 394)
#2 0x55a158731ce0 i   /usr/share/cinnamon/js/ui/overrides.js:51 (0x7f48640c8780 @ 44)
#3 0x55a158731c40 i   /usr/share/cinnamon/js/ui/overrides.js:83 (0x7f48640c8ab0 @ 36)
#4 0x55a158731bb8 i   /usr/share/cinnamon/js/ui/panel.js:1626 (0x7f485571bab0 @ 30)
#5 0x7ffd4cba9e60 b   resource:///org/cinnamon/cjs/modules/signals.js:142 (0x7f48640d6ef0 @ 386)
#6 0x55a158731b28 i   /usr/share/cinnamon/js/ui/popupMenu.js:868 (0x7f485574a918 @ 56)
#7 0x55a158731a90 i   /usr/share/cinnamon/js/ui/popupMenu.js:860 (0x7f485574a890 @ 42)
#8 0x55a158731a00 i   /usr/share/cinnamon/js/ui/popupMenu.js:152 (0x7f485573bde0 @ 21)
#9 0x7ffd4cbab810 I   self-hosted:918 (0x7f48640e5560 @ 394)

(cinnamon:31529): Cjs-CRITICAL **: 14:03:46.284: Object Cinnamon.GenericContainer (0x55a15a366b70), has been already finalized. Impossible to set any property to it.
== Stack trace for context 0x55a157dd94c0 ==
#0 0x55a158731d70 i   /usr/share/cinnamon/js/misc/fileUtils.js line 210 > Function:369 (0x7f4^C^C

**Comment by Hultan** [comment]
I am getting pretty much the same error on a freshly installed (~ 2 days) Linux Mint 19.1 (Cinnamon 4.0.10) when switching the panel edit mode on or off. When I turn it on I get about 15+  errors like this, and the same when I turn it off.

`(cinnamon:1841): Cjs-CRITICAL **: 21:07:02.473: Object Cinnamon.GenericContainer (0x55f7e47907a0), has been already finalized. Impossible to set any property to it.
== Stack trace for context 0x55f7e0fa34b0 ==
#0 0x7ffd1ace2690 b   /usr/share/cinnamon/js/misc/fileUtils.js line 210 > Function:369 (0x7f4d247089a0 @ 91)
#1 0x7ffd1ace2760 b   self-hosted:918 (0x7f4da86e5560 @ 394)
#2 0x55f7e196f3d0 i   /usr/share/cinnamon/js/ui/overrides.js:51 (0x7f4da86c8780 @ 44)
#3 0x55f7e196f330 i   /usr/share/cinnamon/js/ui/overrides.js:83 (0x7f4da86c8ab0 @ 36)
#4 0x55f7e196f2a8 i   /usr/share/cinnamon/js/ui/panel.js:1626 (0x7f4da801bab0 @ 30)
#5 0x55f7e196f1d8 i   resource:///org/cinnamon/cjs/modules/signals.js:142 (0x7f4da86d6ef0 @ 386)
#6 0x55f7e196f148 i   /usr/share/cinnamon/js/ui/popupMenu.js:868 (0x7f4da804a918 @ 56)
#7 0x55f7e196f0b0 i   /usr/share/cinnamon/js/ui/popupMenu.js:860 (0x7f4da804a890 @ 42)
#8 0x55f7e196f020 i   /usr/share/cinnamon/js/ui/popupMenu.js:152 (0x7f4da803bde0 @ 21)
#9 0x7ffd1ace6b40 b   self-hosted:918 (0x7f4da86e5560 @ 394)
`

My inxi information:

`inxi -Fxz
System:
  Host: CURIE Kernel: 4.15.0-55-generic x86_64 bits: 64 compiler: gcc 
  v: 7.4.0 Desktop: Cinnamon 4.0.10 Distro: Linux Mint 19.1 Tessa 
  base: Ubuntu 18.04 bionic 
Machine:
  Type: Desktop Mobo: MSI model: Z270 GAMING PRO (MS-7A59) v: 1.0 
  serial: <filter> UEFI: American Megatrends v: 2.70 date: 06/30/2018 
CPU:
  Topology: Quad Core model: Intel Core i7-7700K bits: 64 type: MT MCP 
  arch: Kaby Lake rev: 9 L2 cache: 8192 KiB 
  flags: lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx bogomips: 67200 
  Speed: 800 MHz min/max: 800/4500 MHz Core speeds (MHz): 1: 800 2: 800 
  3: 800 4: 800 5: 800 6: 800 7: 800 8: 800 
Graphics:
  Device-1: AMD Ellesmere [Radeon RX 470/480/570/570X/580/580X] 
  vendor: Sapphire Limited Nitro+ driver: amdgpu v: kernel bus ID: 01:00.0 
  Display: x11 server: X.Org 1.19.6 driver: amdgpu,ati 
  unloaded: fbdev,modesetting,radeon,vesa 
  resolution: 1920x1080~60Hz, 1920x1080~60Hz, 1920x1080~60Hz 
  OpenGL: renderer: Radeon RX 580 Series (POLARIS10 DRM 3.23.0 
  4.15.0-55-generic LLVM 8.0.0) 
  v: 4.5 Mesa 19.0.2 direct render: Yes 
Audio:
  Device-1: Intel 200 Series PCH HD Audio vendor: Micro-Star MSI 
  driver: snd_hda_intel v: kernel bus ID: 00:1f.3 
  Device-2: AMD Ellesmere [Radeon RX 580] vendor: Sapphire Limited 
  driver: snd_hda_intel v: kernel bus ID: 01:00.1 
  Device-3: Logitech type: USB 
  driver: hid-generic,snd-usb-audio,usbhid,uvcvideo bus ID: 2-6:2 
  Sound Server: ALSA v: k4.15.0-55-generic 
Network:
  Device-1: Intel Ethernet I219-V vendor: Micro-Star MSI driver: e1000e 
  v: 3.2.6-k port: f000 bus ID: 00:1f.6 
  IF: enp0s31f6 state: up speed: 1000 Mbps duplex: full mac: <filter> 
  IF-ID-1: tun0 state: unknown speed: 10 Mbps duplex: full mac: N/A 
Drives:
  Local Storage: total: 3.41 TiB used: 1.12 TiB (32.8%) 
  ID-1: /dev/nvme0n1 vendor: Samsung model: SSD 960 EVO 250GB 
  size: 232.89 GiB 
  ID-2: /dev/sda vendor: Western Digital model: WD20EZRZ-00Z5HB0 
  size: 1.82 TiB 
  ID-3: /dev/sdb vendor: Samsung model: SSD 850 EVO 1TB size: 931.51 GiB 
  ID-4: /dev/sdc vendor: Samsung model: SSD 850 EVO 500GB size: 465.76 GiB 
Partition:
  ID-1: / size: 915.40 GiB used: 357.09 GiB (39.0%) fs: ext4 dev: /dev/sdb2 
Sensors:
  System Temperatures: cpu: 29.8 C mobo: 27.8 C gpu: amdgpu temp: 38 C 
  Fan Speeds (RPM): N/A gpu: amdgpu fan: 821 
Info:
  Processes: 306 Uptime: 1h 33m Memory: 31.37 GiB used: 4.27 GiB (13.6%) 
  Init: systemd runlevel: 5 Compilers: gcc: 7.4.0 Shell: bash v: 4.4.20 
  inxi: 3.0.27 
`

**Comment by icarter09** [comment]
@Hultan i'm seeing the same stack trace that you have posted. 
@illumilore Cinnamon does not crash when I toggle the `Panel edit mode`, but it does block most actions since Cinnamon is expecting me to edit the panel.

**Comment by icarter09** [comment]
@Hultan and @illumilore: are either you still experiencing this?

**Comment by Hultan** [comment]
Personally no, I think I got this on my main machine when I was trying out Mint on that for a couple of weeks this summer. Now I don't run Mint anymore on that machine anymore, so I can't provide anymore information than the above.

**Comment by icarter09** [comment]
@Hultan thanks for the update. I just retested this issue and no longer see the stacktraces that were mentioned in this ticket when I toggle the panel's edit mode.
