### ISSUE TITLE
LM 19.1 Fails to install on ZOTAC system

### ISSUE THREAD

**Issue by windyweather** [linuxmint/cinnamon#8654]
```
 * Cinnamon version (cinnamon --version) unknown since system will not boot - whatever is supplied on LM 19.1 live install.
   - Please specify if you are using the daily builds PPA (https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds). Released LM 19.1 x64 ISO as of 20 June 2019
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint Cinnamon 19.1 Live USB Stick
 * Graphics hardware *and* driver used  Zotac with Intel Atom CPU D2700, with Nvidia GF119M [Geforce GT 520M] - Model on back of system shows - Zotac Model ID-80
 * 32 or 64 bit - 64bit / 4GB RAM, / 64GB Sata SSD
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog - Not possible. System is not usable since graphics on boot of stick do not work.
 ```

**Issue**
Trying to install LM 19.1 from USB live stick created 20 June 2019.
Video fails. Displays entire screen of random colored squares.

see pictures here of video, system, and LM 18.3 system information screen.
https://photos.app.goo.gl/FF4mcwrabPF9F5sD7

**Steps to reproduce**
Create 19.1 usb stick.
Insert the stick in the ZOTAC system.
Boot it.
Observe messed up video.
Reboot system to LM 18.3 system on SSD.
Observe that this works just fine.

**Expected behaviour**
19.1 should support Zotac with Intel Atom CPU D2700, with Nvidia GF119M [Geforce GT 520M] - as reported by the working LinuxMint 18.3 system that runs very nicely on the hardware.

**Other information**
Stick is fine. I booted it on another system which has Intel processor and Nvidia 1050 graphics card. It came right up and showed LM desktop with Install Linux Mint option. Test system was using dual 2K monitors via Display Port. Worked fine.
Failing Zotac system was connected to 1080 monitor using HDMI.

**Comment by JosephMcc** [comment]
Since this is also happening in other Ubuntu based distros, I don't think Cinnamon is really the issue here.

**Comment by windyweather** [comment]
Look. I'm no expert on what part of what this should be reported to. So you guys did promote this to the correct Ubuntu tracker, right? Not just drop it on the floor? 
Thanks a ton.

**Comment by icarter09** [comment]
@windyweather Ubuntu will want some necessary info for the bug report that you will be the best person to provide that to them. Here are some links to help you out.  

https://help.ubuntu.com/community/ReportingBugs

https://wiki.ubuntu.com/Bugs/FindRightPackage
