### ISSUE TITLE
How the webview engine is lightweight?

### ISSUE THREAD

**Issue by DaniellMesquita** [linuxmint/cinnamon#8656]
Cinnamon elements are in HTML, CSS and JS.
How the browser engine is lightweight unlike Chromium/Gecko?

**Comment by JosephMcc** [comment]
I'm closing this since it really isn't an issue. I suppose the short answer would be because Cinnamon isn't a web browser. Just because it happens to use JS to implement some things doesn't make the same.

**Comment by DaniellMesquita** [comment]
> I'm closing this since it really isn't an issue.

Issues are also used for discussions and questions,.

> I suppose the short answer would be because Cinnamon isn't a web browser. Just because it happens to use JS to implement some things doesn't make the same.

It also renders CSS.
