### ISSUE TITLE
Smartphone with huge number of files in one directory causes I/O errors, can't be accessed

### ISSUE THREAD

**Issue by BillDietrich** [linuxmint/cinnamon#8657]
Distro: Linux Mint 19.1 Tessa base: Ubuntu 18.04 bionic Kernel: 4.15.0-52-generic x86_64 bits: 64 compiler: gcc v: 7.3.0 Desktop: Cinnamon 4.0.10

**Issue**

I have a smartphone (Samsung Galaxy 8+) that has a ridiculous number of photo and video files (maybe 15,000 of them) in the DCIM/Camera directory.

If I plug the camera via USB into my Mint system, the camera mounts (as MTP device) and I can navigate to the Camera directory, using either Nemo or CLI.  But then trying to view the filenames in the directory fails, both in Nemo and in CLI (ls command).  They each hang for maybe 5 minutes and then say something like "I/O error reading directory '.' " (in CLI) or various equivalent error dialogs (in Nemo).

If I plug the camera into a Windows 10 system, I am able to view the filenames in the DCIM/Camera directory using the file explorer, and move files from camera to PC in batches of 1000 or so.  Occasionally the file explorer complains about not being able to display all 15,000 filenames, and nothing is fast about the process, but it does work and I am able to move files across.

**Comment by JosephMcc** [comment]
This doesn't really seem like a Cinnamon related issue. I'd be curious if it works in any other Linux distro/DE
