### ISSUE TITLE
System Info application's "Upload system information" button

### ISSUE THREAD

**Issue by BillDietrich** [linuxmint/cinnamon#8658]
Kernel: 4.15.0-52-generic x86_64 bits: 64 compiler: gcc v: 7.3.0 Desktop: Cinnamon 4.0.10 
Distro: Linux Mint 19.1 Tessa base: Ubuntu 18.04 bionic

**Issue**

In the System Info application, what does the "Upload system information" button do, and why is it there ?  There is no Help or description of it in the application.  Is the user given a chance to confirm before the upload takes place ?  Where does the information go ?  Can the user delete it later ?

Some people consider this a privacy violation, even though the tool-tip says "no personal information included".  Perhaps this whole feature should be removed.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
