### ISSUE TITLE
apt get: too many errors. (gconf2)

### ISSUE THREAD

**Issue by two-dogs** [linuxmint/cinnamon#8660]
```
 * Cinnamon version (linuxmint 19.1 cinnamon 64bit)
   
**Issue**
saw same errors shown on the forum posts provided

https://forums.linuxmint.com/viewtopic.php?f=90&t=296589#p1649754
https://forums.linuxmint.com/viewtopic.php?f=46&t=296232

**Steps to reproduce**

install linuxmint-cinnamon-64bit 19.1 and ran on virtual (qemu)

**Expected behaviour**

error free upgrade

**Other information**
many more people describing exact same issue via irc linuxmint-help

**Comment by leigh123linux** [comment]
Sorry I fail to see what a broken Ubuntu package has to do with the cinnamon code.
If you can demonstrate an actual issue within cinnamon feel free to reopen,

P.S Using forum links is lame,

**Comment by two-dogs** [comment]
@leigh123linux , yea, thats it, i'll put it where it belongs, mintupdate and reference this one , the lame issue

**Comment by leigh123linux** [comment]
@two-dogs  The issue isn't lame, expecting us to navigate to other sites is.
