### ISSUE TITLE
Cinnamon + Mate Both random restarting for no reason.

### ISSUE THREAD

**Issue by bridgetsarah** [linuxmint/cinnamon#8663]
```
 * Cinnamon version (cinnamon --version) Tessa (Latest)
   - Please specify if you are using the daily builds PPA (https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds).
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Tessa Cinnamon Edition 19 (Latest)
 * Graphics hardware *and* driver used
 * 32 or 64 bit (64 btt)
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
 ```

**Issue**
Hello, I started having issues with my Linux Mate originally on same laptop yesterday.  Laptop would just restart for no reason and so I thought maybe I had issues with the drive, so tried to fsck it and wasn't able because the drive was mounted. 

So I though okay I'll just do a clean wipe and go back to using the Mint Cinnamon Edition..  and I thought it would stop the restarting but seems to be it hasn't. I've updated APT and can't find anything else wrong with it. 

It just randomly restarts for no reason, 

**Steps to reproduce**

**Expected behaviour**
Should not randomly restart between editions. 
[syslog.txt](https://github.com/linuxmint/cinnamon/files/3326227/syslog.txt)

**Other information**

**Comment by brownsr** [comment]
Doesn't seem that likely to be a Cinnamon or Mate issue.  Also consider a hardware fault, overheating, motherboard cracks, capacitors approaching end of life, that sort of thing.  Suggest looking for support on the forums or on IRC as well.

**Comment by JosephMcc** [comment]
Yeah, this doesn't look like a Cinnamon related issue at all.
