### ISSUE TITLE
apt upgrade doesn't work on fresh installs

### ISSUE THREAD

**Issue by rubinlinux** [linuxmint/cinnamon#8664]
```
 * Cinnamon version (cinnamon --version)
Cinnamon 3.8.8
   - Please specify if you are using the daily builds PPA (https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds).
no

 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
mint 19
 * Graphics hardware *and* driver used
several different
 * 32 or 64 bit
64 bit
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
not related
 ```

**Issue**
apt upgrade produces the following error
dpkg: dependency problems prevent processing triggers for gconf2:
 gconf2 depends on default-dbus-session-bus | dbus-session-bus; however:
  Package default-dbus-session-bus is not installed.
  Package dbus-user-session which provides default-dbus-session-bus is not configured yet.
  Package dbus-session-bus is not installed.
  Package dbus-user-session which provides dbus-session-bus is not configured yet.
  Package dbus-x11 which provides dbus-session-bus is not configured yet.

(continues for several pages see https://gist.github.com/rubinlinux/ba806dae98ab3676c3887a9c0567d46a )

**Steps to reproduce**
Fresh install from linuxmint-19-cinnamon-64bit-v2.iso (Re-downloaded a fresh copy to ensure it was not corrupt, same problem)

Open the terminal

$ sudo -s
# apt update
(runs)
# apt upgrade
runs for a while then fails with the gconf2 errors mentioned above

**Expected behaviour**
packages to get upgraded to current versions and upgrade completes without error

**Other information**
I have reproduced this on 2 separate machines (one a laptop, one a VM). and with 2 separately downloaded copies of the ISO.

I am able to work-around the problem this way:

run aptitude

press 'e' to evalutae
press 'g' to go

apptitude will tell you it has fixed some broken packages. Hit enter ("OK")

press 'g' again, it will start running updates and complete

**Comment by leigh123linux** [comment]
Closed #8660
