### ISSUE TITLE
Update icon appears cut in Cinnamon if resolution is downscaled

### ISSUE THREAD

**Issue by kryssb** [linuxmint/cinnamon#8666]
Cinnamon 4.0.10
Standard Linux Mint distribution 19.1, 64 bit edition
Laptop Dell XPS 9365 (2-in-1)
lspci -vnn | grep VGA
00:02.0 VGA compatible controller [0300]: Intel Corporation Device [8086:591e] (rev 02) (prog-if 00 [VGA controller])
00:13.0 Non-VGA unclassified device [0000]: Intel Corporation Sunrise Point-LP Integrated Sensor Hub [8086:9d35] (rev 21)

**Issue**

The system update systray icon appears correctly if the display works in full resolution, but it's cut if it works in low-res modes. 

**Steps to reproduce**

With the laptop in full resolution, go to Monitor and set resolution to 1920x1080 and accept the new resolution. From that point on, only the left-upper corner of the systray update icon will be updated, with the remaining part not drawn or showing an old image.

**Expected behaviour**

The icon should scale correctly in all resolutions.
The attached files show the icon appearing small but correctly drawn in 3200x1800 and badly drawn in 1920x1080 (the icon is white in the top-left corner because I took the snapshot during a search for updates), with the rest being still "green".
![sysupdate-1920x1080-v1](https://user-images.githubusercontent.com/52244188/60179575-48d6fa80-981e-11e9-9a50-f16ff0d8b799.png)
![sysupdate-3200x1800](https://user-images.githubusercontent.com/52244188/60179576-496f9100-981e-11e9-9d9b-c6c6c6acc442.png)

**Other information**

**Comment by kryssb** [comment]
![sysupdate-1920x1080-v2](https://user-images.githubusercontent.com/52244188/60186539-4a0f2400-982c-11e9-8b52-ccf0bd613f50.png)

It is even more clear in this picture: part of the icon is not refreshed. Also, it seems that the problem affects the bluetooth icon as well.

**Comment by JosephMcc** [comment]
This is a known issue with the systray when changing resolutions. It's also being discussed here so I'm going to go ahead and close this one: https://github.com/linuxmint/cinnamon/issues/8725
