### ISSUE TITLE
Dual Display Overlap

### ISSUE THREAD

**Issue by minecraftchest1** [linuxmint/cinnamon#8670]
```
 * Cinnamon version (cinnamon --version)
   - Please specify if you are using the daily builds PPA (https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds).
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
 * Graphics hardware *and* driver used
 * 32 or 64 bit
 ```
sys info:
System:    Host: Jackson-Wyatt Kernel: 4.15.0-20-generic x86_64 bits: 64 compiler: gcc v: 7.3.0 
           Desktop: Cinnamon 4.0.8 wm: muffin dm: LightDM Distro: Linux Mint 19.1 Tessa 
           base: Ubuntu 18.04 bionic 
Machine:   Type: Portable System: Dell product: Latitude XT v: N/A serial: <filter> Chassis: 
           type: 8 serial: <filter> 
           Mobo: Dell model: 0Y041C serial: <filter> BIOS: Dell v: A09 date: 01/12/2010 
Battery:   ID-1: BAT0 charge: N/A condition: 37.3/42.2 Wh (89%) volts: 7.8/11.1 
           model: Sanyo DELL H986H9 serial: <filter> status: Charging 
CPU:       Topology: Dual Core model: Intel Core2 Duo U7700 bits: 64 type: MCP arch: Core Merom 
           rev: D L2 cache: 2048 KiB 
           flags: lm nx pae sse sse2 sse3 ssse3 vmx bogomips: 5333 
           Speed: 700 MHz max: 800 MHz Core speeds (MHz): 1: 700 2: 700 
Graphics:  Device-1: AMD RS600M [Radeon Xpress 1250] vendor: Dell driver: radeon v: kernel 
           bus ID: 01:05.0 chip ID: 1002:7942 
           Display: x11 server: X.Org 1.19.6 driver: ati,radeon unloaded: fbdev,modesetting,vesa 
           resolution: 1920x1080~60Hz 
           OpenGL: renderer: ATI RS600 v: 2.1 Mesa 18.2.2 direct render: Yes 
Audio:     Device-1: AMD SBx00 Azalia vendor: Dell driver: snd_hda_intel v: kernel bus ID: 00:14.2 
           chip ID: 1002:4383 
           Sound Server: ALSA v: k4.15.0-20-generic 
Network:   Device-1: Broadcom Limited NetXtreme BCM5756ME Gigabit Ethernet PCI Express 
           vendor: Dell driver: tg3 v: 3.137 port: ee00 bus ID: 09:00.0 chip ID: 14e4:1674 
           IF: enp9s0 state: up speed: 1000 Mbps duplex: full mac: <filter> 
Drives:    Local Storage: total: 74.53 GiB used: 40.19 GiB (53.9%) 
           ID-1: /dev/sda vendor: Toshiba model: MK8009GAH size: 74.53 GiB speed: <unknown> 
           serial: <filter> 
Partition: ID-1: / size: 70.13 GiB used: 39.38 GiB (56.2%) fs: ext4 dev: /dev/dm-0 
           ID-2: swap-1 size: 2.75 GiB used: 832.0 MiB (29.6%) fs: swap dev: /dev/dm-1 
Sensors:   System Temperatures: cpu: 80.0 C mobo: N/A sodimm: 71.0 C 
           Fan Speeds (RPM): cpu: 2399 
Repos:     Active apt repos in: /etc/apt/sources.list 
           1: deb http: //download.virtualbox.org/virtualbox/debian raring contrib
           2: deb http: //download.virtualbox.org/virtualbox/debian quantal contrib
           3: deb http: //download.virtualbox.org/virtualbox/debian precise contrib
           4: deb http: //download.virtualbox.org/virtualbox/debian lucid contrib non-free
           5: deb http: //download.virtualbox.org/virtualbox/debian wheezy contrib
           6: deb http: //download.virtualbox.org/virtualbox/debian jessie contrib
           7: deb http: //download.virtualbox.org/virtualbox/debian squeeze contrib non-free
           Active apt repos in: /etc/apt/sources.list.d/google-chrome.list 
           1: deb [arch=amd64] http: //dl.google.com/linux/chrome/deb/ stable main
           Active apt repos in: /etc/apt/sources.list.d/official-package-repositories.list 
           1: deb http: //packages.linuxmint.com tessa main upstream import backport
           2: deb http: //archive.ubuntu.com/ubuntu bionic main restricted universe multiverse
           3: deb http: //archive.ubuntu.com/ubuntu bionic-updates main restricted universe multiverse
           4: deb http: //archive.ubuntu.com/ubuntu bionic-backports main restricted universe multiverse
           5: deb http: //security.ubuntu.com/ubuntu/ bionic-security main restricted universe multiverse
           6: deb http: //archive.canonical.com/ubuntu/ bionic partner
           Active apt repos in: /etc/apt/sources.list.d/skype-stable.list 
           1: deb [arch=amd64] https: //repo.skype.com/deb stable main
           Active apt repos in: /etc/apt/sources.list.d/teamviewer.list 
           1: deb http: //linux.teamviewer.com/deb stable main
Info:      Processes: 212 Uptime: 14h 56m Memory: 2.68 GiB used: 2.28 GiB (85.1%) Init: systemd 
           v: 237 runlevel: 5 Compilers: gcc: 7.3.0 alt: 7 Client: Unknown python3.6 client 
           inxi: 3.0.27 
-------------------------------------------------------------
**Issue**
Whenever I have an external monitor connected to my Dell Latitude XT in an extended display configuration, my external display shows on half of the monitor, and my laptop display shows on both my laptop, and my monitor. My corsur selects about 3 to six inches to the left of where it is displayed. When my displayes are mirrored, or my laptop display turned off via configuration, everything works as expected.

**Steps to reproduce**
Use problmatic configuration explained above.

**Expected behaviour**
No issues

**Other information**
Has issues on both of my latitude xt's.
Display cable/port makes no difference.
Photos will be atached later.
Edit:
Doesen't have issues in cinnamon fallback.

**Comment by icarter09** [comment]
@minecraftchest1 are you still experiencing this issue? If so, what OS and Cinnamon version are you  using? Thanks.

**Comment by minecraftchest1** [comment]
Hi. Just got an email from this thread. I am currently not using Mint on the device in question anymore. However, a can reinstall and test.
