### ISSUE TITLE
languages in system settings can't open

### ISSUE THREAD

**Issue by sduqlsc** [linuxmint/cinnamon#8671]
```
 * Cinnamon version (cinnamon --version) 3.6.7
   - Please specify if you are using the daily builds PPA (https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds). no
 * Distribution - CentOS Linux release 7.6.1810 (Core)
 * Graphics hardware *and* driver used - AMD Rx550
 * 32 or 64 bit - 64 bit
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog

 ```

**Issue**

utf_8.py:16:decode:UnicodeDecodeError: 'utf8' codec can't decode byte 0xe5 in position 1071: invalid continuation byte

/usr/bin/python2 /usr/lib/linuxmint/mintlocale/mintlocale.py

utf_8.py:16:decode:UnicodeDecodeError: 'utf8' codec can't decode byte 0xe5 in position 1071: invalid continuation byte

Traceback (most recent call last):
  File "/usr/lib/linuxmint/mintlocale/mintlocale.py", line 980, in <module>
    MintLocale(show_input_methods)
  File "/usr/lib/linuxmint/mintlocale/mintlocale.py", line 588, in __init__
    self.build_lang_list()
  File "/usr/lib/linuxmint/mintlocale/mintlocale.py", line 811, in build_lang_list
    locales = locales.decode('utf-8')
  File "/usr/lib64/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe5 in position 1071: invalid continuation byte

Local variables in innermost frame:
input: 'aa_DJ\naa_DJ.iso88591\naa_DJ.utf8\naa_ER\naa_ER.utf8\naa_ER.utf8@saaho\naa_ER@saaho\naa_ET\naa_ET.utf8\naf_ZA\naf_ZA.iso88591\naf_ZA.utf8\nam_ET\nam_ET.utf8\nan_ES\nan_ES.iso885915\nan_ES.utf8\nar_AE\nar_AE.iso88596\nar_AE.utf8\nar_BH\nar_BH.iso88596\nar_BH.utf8\nar_DZ\nar_DZ.iso88596\nar_DZ.utf8\nar_EG\nar_EG.iso88596\nar_EG.utf8\nar_IN\nar_IN.utf8\nar_IQ\nar_IQ.iso88596\nar_IQ.utf8\nar_JO\nar_JO.iso88596\nar_JO.utf8\nar_KW\nar_KW.iso88596\nar_KW.utf8\nar_LB\nar_LB.iso88596\nar_LB.utf8\nar_LY\nar_LY.iso88596\nar_LY.utf8\nar_MA\nar_MA.iso88596\nar_MA.utf8\nar_OM\nar_OM.iso88596\nar_OM.utf8\nar_QA\nar_QA.iso88596\nar_QA.utf8\nar_SA\nar_SA.iso88596\nar_SA.utf8\nar_SD\nar_SD.iso88596\nar_SD.utf8\nar_SY\nar_SY.iso88596\nar_SY.utf8\nar_TN\nar_TN.iso88596\nar_TN.utf8\nar_YE\nar_YE.iso88596\nar_YE.utf8\nas_IN\nas_IN.utf8\nast_ES\nast_ES.iso885915\nast_ES.utf8\nayc_PE\nayc_PE.utf8\naz_AZ\naz_AZ.utf8\nbe_BY\nbe_BY.cp1251\nbe_BY.utf8\nbe_BY.utf8@latin\nbe_BY@latin\nbem_ZM\nbem_ZM.utf8\nber_DZ\nber_DZ.utf8\nber_MA\nber_MA.utf8\nbg_BG\nbg_BG.cp1251\nbg_BG.utf8\nbho_IN\nbho_IN.utf8\nbn_BD\nbn_BD.utf8\nbn_IN\nbn_IN.utf8\nbo_CN\nbo_CN.utf8\nbo_IN\nbo_IN.utf8\nbokmal\nbokm\xe5l\nbr_FR\nbr_FR.iso88591\nbr_FR.iso885915@euro\nbr_FR.utf8\nbr_FR@euro\nbrx_IN\nbrx_IN.utf8\nbs_BA\nbs_BA.iso88592\nbs_BA.utf8\nbyn_ER\nbyn_ER.utf8\nca_AD\nca_AD.iso885915\nca_AD.utf8\nca_ES\nca_ES.iso88591\nca_ES.iso885915@euro\nca_ES.utf8\nca_ES@euro\nca_FR\nca_FR.iso885915\nca_FR.utf8\nca_IT\nca_IT.iso885915\nca_IT.utf8\ncatalan\ncrh_UA\ncrh_UA.utf8\ncroatian\ncs_CZ\ncs_CZ.iso88592\ncs_CZ.utf8\ncsb_PL\ncsb_PL.utf8\ncv_RU\ncv_RU.utf8\ncy_GB\ncy_GB.iso885914\ncy_GB.utf8\nczech\nda_DK\nda_DK.iso88591\nda_DK.iso885915\nda_DK.utf8\ndanish\ndansk\nde_AT\nde_AT.iso88591\nde_AT.iso885915@euro\nde_AT.utf8\nde_AT@euro\nde_BE\nde_BE.iso88591\nde_BE.iso885915@euro\nde_BE.utf8\nde_BE@euro\nde_CH\nde_CH.iso88591\nde_CH.utf8\nde_DE\nde_DE.iso88591\nde_DE.iso885915@euro\nde_DE.utf8\nde_DE@euro\nde_LU\nde_LU.iso88591\nde_LU.iso885915@euro\nde_LU.utf8\nde_LU@euro\ndeutsch\ndoi_IN\ndoi_IN.utf8\ndutch\ndv_MV\ndv_MV.utf8\ndz_BT\ndz_BT.utf8\neesti\nel_CY\nel_CY.iso88597\nel_CY.utf8\nel_GR\nel_GR.iso88597\nel_GR.iso88597@euro\nel_GR.utf8\nel_GR@euro\nen_AG\nen_AG.utf8\nen_AU\nen_AU.iso88591\nen_AU.utf8\nen_BW\nen_BW.iso88591\nen_BW.utf8\nen_CA\nen_CA.iso88591\nen_CA.utf8\nen_DK\nen_DK.iso88591\nen_DK.utf8\nen_GB\nen_GB.iso88591\nen_GB.iso885915\nen_GB.utf8\nen_HK\nen_HK.iso88591\nen_HK.utf8\nen_IE\nen_IE.iso88591\nen_IE.iso885915@euro\nen_IE.utf8\nen_IE@euro\nen_IN\nen_IN.utf8\nen_NG\nen_NG.utf8\nen_NZ\nen_NZ.iso88591\nen_NZ.utf8\nen_PH\nen_PH.iso88591\nen_PH.utf8\nen_SG\nen_SG.iso88591\nen_SG.utf8\nen_US\nen_US.iso88591\nen_US.iso885915\nen_US.utf8\nen_ZA\nen_ZA.iso88591\nen_ZA.utf8\nen_ZM\nen_ZM.utf8\nen_ZW\nen_ZW.iso88591\nen_ZW.utf8\nes_AR\nes_AR.iso88591\nes_AR.utf8\nes_BO\nes_BO.iso88591\nes_BO.utf8\nes_CL\nes_CL.iso88591\nes_CL.utf8\nes_CO\nes_CO.iso88591\nes_CO.utf8\nes_CR\nes_CR.iso88591\nes_CR.utf8\nes_CU\nes_CU.utf8\nes_DO\nes_DO.iso88591\nes_DO.utf8\nes_EC\nes_EC.iso88591\nes_EC.utf8\nes_ES\nes_ES.iso88591\nes_ES.iso885915@euro\nes_ES.utf8\nes_ES@euro\nes_GT\nes_GT.iso88591\nes_GT.utf8\nes_HN\nes_HN.iso88591\nes_HN.utf8\nes_MX\nes_MX.iso88591\nes_MX.utf8\nes_NI\nes_NI.iso88591\nes_NI.utf8\nes_PA\nes_PA.iso88591\nes_PA.utf8\nes_PE\nes_PE.iso88591\nes_PE.utf8\nes_PR\nes_PR.iso88591\nes_PR.utf8\nes_PY\nes_PY.iso88591\nes_PY.utf8\nes_SV\nes_SV.iso88591\nes_SV.utf8\nes_US\nes_US.iso88591\nes_US.utf8\nes_UY\nes_UY.iso88591\nes_UY.utf8\nes_VE\nes_VE.iso88591\nes_VE.utf8\nestonian\net_EE\net_EE.iso88591\net_EE.iso885915\net_EE.utf8\neu_ES\neu_ES.iso88591\neu_ES.iso885915@euro\neu_ES.utf8\neu_ES@euro\nfa_IR\nfa_IR.utf8\nff_SN\nff_SN.utf8\nfi_FI\nfi_FI.iso88591\nfi_FI.iso885915@euro\nfi_FI.utf8\nfi_FI@euro\nfil_PH\nfil_PH.utf8\nfinnish\nfo_FO\nfo_FO.iso88591\nfo_FO.utf8\nfr_BE\nfr_BE.iso88591\nfr_BE.iso885915@euro\nfr_BE.utf8\nfr_BE@euro\nfr_CA\nfr_CA.iso88591\nfr_CA.utf8\nfr_CH\nfr_CH.iso88591\nfr_CH.utf8\nfr_FR\nfr_FR.iso88591\nfr_FR.iso885915@euro\nfr_FR.utf8\nfr_FR@euro\nfr_LU\nfr_LU.iso88591\nfr_LU.iso885915@euro\nfr_LU.utf8\nfr_LU@euro\nfran\xe7ais\nfrench\nfur_IT\nfur_IT.utf8\nfy_DE\nfy_DE.utf8\nfy_NL\nfy_NL.utf8\nga_IE\nga_IE.iso88591\nga_IE.iso885915@euro\nga_IE.utf8\nga_IE@euro\ngalego\ngalician\ngd_GB\ngd_GB.iso885915\ngd_GB.utf8\ngerman\ngez_ER\ngez_ER.utf8\ngez_ER.utf8@abegede\ngez_ER@abegede\ngez_ET\ngez_ET.utf8\ngez_ET.utf8@abegede\ngez_ET@abegede\ngl_ES\ngl_ES.iso88591\ngl_ES.iso885915@euro\ngl_ES.utf8\ngl_ES@euro\ngreek\ngu_IN\ngu_IN.utf8\ngv_GB\ngv_GB.iso88591\ngv_GB.utf8\nha_NG\nha_NG.utf8\nhe_IL\nhe_IL.iso88598\nhe_IL.utf8\nhebrew\nhi_IN\nhi_IN.utf8\nhne_IN\nhne_IN.utf8\nhr_HR\nhr_HR.iso88592\nhr_HR.utf8\nhrvatski\nhsb_DE\nhsb_DE.iso88592\nhsb_DE.utf8\nht_HT\nht_HT.utf8\nhu_HU\nhu_HU.iso88592\nhu_HU.utf8\nhungarian\nhy_AM\nhy_AM.armscii8\nhy_AM.utf8\nia_FR\nia_FR.utf8\nicelandic\nid_ID\nid_ID.iso88591\nid_ID.utf8\nig_NG\nig_NG.utf8\nik_CA\nik_CA.utf8\nis_IS\nis_IS.iso88591\nis_IS.utf8\nit_CH\nit_CH.iso88591\nit_CH.utf8\nit_IT\nit_IT.iso88591\nit_IT.iso885915@euro\nit_IT.utf8\nit_IT@euro\nitalian\niu_CA\niu_CA.utf8\niw_IL\niw_IL.iso88598\niw_IL.utf8\nja_JP\nja_JP.eucjp\nja_JP.ujis\nja_JP.utf8\njapanese\njapanese.euc\nka_GE\nka_GE.georgianps\nka_GE.utf8\nkk_KZ\nkk_KZ.pt154\nkk_KZ.utf8\nkl_GL\nkl_GL.iso88591\nkl_GL.utf8\nkm_KH\nkm_KH.utf8\nkn_IN\nkn_IN.utf8\nko_KR\nko_KR.euckr\nko_KR.utf8\nkok_IN\nkok_IN.utf8\nkorean\nkorean.euc\nks_IN\nks_IN.utf8\nks_IN.utf8@devanagari\nks_IN@devanagari\nku_TR\nku_TR.iso88599\nku_TR.utf8\nkw_GB\nkw_GB.iso88591\nkw_GB.utf8\nky_KG\nky_KG.utf8\nlb_LU\nlb_LU.utf8\nlg_UG\nlg_UG.iso885910\nlg_UG.utf8\nli_BE\nli_BE.utf8\nli_NL\nli_NL.utf8\nlij_IT\nlij_IT.utf8\nlithuanian\nlo_LA\nlo_LA.utf8\nlt_LT\nlt_LT.iso885913\nlt_LT.utf8\nlv_LV\nlv_LV.iso885913\nlv_LV.utf8\nmag_IN\nmag_IN.utf8\nmai_IN\nmai_IN.utf8\nmg_MG\nmg_MG.iso885915\nmg_MG.utf8\nmhr_RU\nmhr_RU.utf8\nmi_NZ\nmi_NZ.iso885913\nmi_NZ.utf8\nmk_MK\nmk_MK.iso88595\nmk_MK.utf8\nml_IN\nml_IN.utf8\nmn_MN\nmn_MN.utf8\nmni_IN\nmni_IN.utf8\nmr_IN\nmr_IN.utf8\nms_MY\nms_MY.iso88591\nms_MY.utf8\nmt_MT\nmt_MT.iso88593\nmt_MT.utf8\nmy_MM\nmy_MM.utf8\nnan_TW.utf8@latin\nnan_TW@latin\nnb_NO\nnb_NO.iso88591\nnb_NO.utf8\nnds_DE\nnds_DE.utf8\nnds_NL\nnds_NL.utf8\nne_NP\nne_NP.utf8\nnhn_MX\nnhn_MX.utf8\nniu_NU\nniu_NU.utf8\nniu_NZ\nniu_NZ.utf8\nnl_AW\nnl_AW.utf8\nnl_BE\nnl_BE.iso88591\nnl_BE.iso885915@euro\nnl_BE.utf8\nnl_BE@euro\nnl_NL\nnl_NL.iso88591\nnl_NL.iso885915@euro\nnl_NL.utf8\nnl_NL@euro\nnn_NO\nnn_NO.iso88591\nnn_NO.utf8\nno_NO\nno_NO.ISO-8859-1\nnorwegian\nnr_ZA\nnr_ZA.utf8\nnso_ZA\nnso_ZA.utf8\nnynorsk\noc_FR\noc_FR.iso88591\noc_FR.utf8\nom_ET\nom_ET.utf8\nom_KE\nom_KE.iso88591\nom_KE.utf8\nor_IN\nor_IN.utf8\nos_RU\nos_RU.utf8\npa_IN\npa_IN.utf8\npa_PK\npa_PK.utf8\npap_AN\npap_AN.utf8\npl_PL\npl_PL.iso88592\npl_PL.utf8\npolish\nportuguese\nps_AF\nps_AF.utf8\npt_BR\npt_BR.iso88591\npt_BR.utf8\npt_PT\npt_PT.iso88591\npt_PT.iso885915@euro\npt_PT.utf8\npt_PT@euro\nro_RO\nro_RO.iso88592\nro_RO.utf8\nromanian\nru_RU\nru_RU.iso88595\nru_RU.koi8r\nru_RU.utf8\nru_UA\nru_UA.koi8u\nru_UA.utf8\nrussian\nrw_RW\nrw_RW.utf8\nsa_IN\nsa_IN.utf8\nsat_IN\nsat_IN.utf8\nsc_IT\nsc_IT.utf8\nsd_IN\nsd_IN.utf8\nsd_IN.utf8@devanagari\nsd_IN@devanagari\nse_NO\nse_NO.utf8\nshs_CA\nshs_CA.utf8\nsi_LK\nsi_LK.utf8\nsid_ET\nsid_ET.utf8\nsk_SK\nsk_SK.iso88592\nsk_SK.utf8\nsl_SI\nsl_SI.iso88592\nsl_SI.utf8\nslovak\nslovene\nslovenian\nso_DJ\nso_DJ.iso88591\nso_DJ.utf8\nso_ET\nso_ET.utf8\nso_KE\nso_KE.iso88591\nso_KE.utf8\nso_SO\nso_SO.iso88591\nso_SO.utf8\nspanish\nsq_AL\nsq_AL.iso88591\nsq_AL.utf8\nsq_MK\nsq_MK.utf8\nsr_ME\nsr_ME.utf8\nsr_RS\nsr_RS.utf8\nsr_RS.utf8@latin\nsr_RS@latin\nss_ZA\nss_ZA.utf8\nst_ZA\nst_ZA.iso88591\nst_ZA.utf8\nsv_FI\nsv_FI.iso88591\nsv_FI.iso885915@euro\nsv_FI.utf8\nsv_FI@euro\nsv_SE\nsv_SE.iso88591\nsv_SE.iso885915\nsv_SE.utf8\nsw_KE\nsw_KE.utf8\nsw_TZ\nsw_TZ.utf8\nswedish\nszl_PL\nszl_PL.utf8\nta_IN\nta_IN.utf8\nta_LK\nta_LK.utf8\nte_IN\nte_IN.utf8\ntg_TJ\ntg_TJ.koi8t\ntg_TJ.utf8\nth_TH\nth_TH.tis620\nth_TH.utf8\nthai\nti_ER\nti_ER.utf8\nti_ET\nti_ET.utf8\ntig_ER\ntig_ER.utf8\ntk_TM\ntk_TM.utf8\ntl_PH\ntl_PH.iso88591\ntl_PH.utf8\ntn_ZA\ntn_ZA.utf8\ntr_CY\ntr_CY.iso88599\ntr_CY.utf8\ntr_TR\ntr_TR.iso88599\ntr_TR.utf8\nts_ZA\nts_ZA.utf8\ntt_RU\ntt_RU.utf8\ntt_RU.utf8@iqtelif\ntt_RU@iqtelif\nturkish\nug_CN\nug_CN.utf8\nuk_UA\nuk_UA.koi8u\nuk_UA.utf8\nunm_US\nunm_US.utf8\nur_IN\nur_IN.utf8\nur_PK\nur_PK.utf8\nuz_UZ\nuz_UZ.iso88591\nuz_UZ.utf8@cyrillic\nuz_UZ@cyrillic\nve_ZA\nve_ZA.utf8\nvi_VN\nvi_VN.utf8\nwa_BE\nwa_BE.iso88591\nwa_BE.iso885915@euro\nwa_BE.utf8\nwa_BE@euro\nwae_CH\nwae_CH.utf8\nwal_ET\nwal_ET.utf8\nwo_SN\nwo_SN.utf8\nxh_ZA\nxh_ZA.iso88591\nxh_ZA.utf8\nyi_US\nyi_US.cp1255\nyi_US.utf8\nyo_NG\nyo_NG.utf8\nyue_HK\nyue_HK.utf8\nzh_CN\nzh_CN.gb18030\nzh_CN.gb2312\nzh_CN.gbk\nzh_CN.utf8\nzh_HK\nzh_HK.big5hkscs\nzh_HK.utf8\nzh_SG\nzh_SG.gb2312\nzh_SG.gbk\nzh_SG.utf8\nzh_TW\nzh_TW.big5\nzh_TW.euctw\nzh_TW.utf8\nzu_ZA\nzu_ZA.iso88591\nzu_ZA.utf8\n'
errors: 'strict'

**Steps to reproduce**
try to remove ibus & ibus pinyin then desktop ui was lost , so re-install ibus series.

**Expected behaviour**

**Other information**

**Comment by leigh123linux** [comment]
Can you file the issue at Redhat bugzilla as epel is using and EOL version of mintlocale.
