### ISSUE TITLE
Vertical scrolling through a Cinnamon settings window can unintentionally change settings

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/cinnamon#8673]
```
 * Cinnamon version (cinnamon --version) 4.0.10
   - Please specify if you are using the daily builds PPA (https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds). I am using the PPA.
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 19.1
 * Graphics hardware *and* driver used: not relevant.
 * 32 or 64 bit: 64
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
 ```

**Issue**

Vertical scrolling can accidentally alter values in settings windows.

**Steps to reproduce**

Open a Cinnamon settings window that either contains >0 horizontal sliders, or that has values alterable via up and down arrow buttons. The mouse setting window is an example. Scroll up and down the window use a mouse wheel or on a touchpad via edge-scrolling or two-finger scrolling. Let the pointer stray over the occupied part of the window. You may not even have to do that last part on purpose . . :).

**Expected behaviour**

If my pointer strays over one of the alterable items, I change a value inadvertently.

**Other information**

Some of the windows at issue lack a 'reset to default' option. So if I one does not know what the value was before, then one cannot revert the unintended change.

I have 'horizontal scrolling' disabled in the mouse settings. Surely that should mean that at least the horizontal sliders don't move when I do not want them to, i.e. am scrolling throw a page?

**What should happen**

If horizontal scrolling is disabled, horizontal sliders should not behave in the way I have described.

Even when such scrolling is enabled would not the following be a good idea?

If the user is scrolling vertically through a window, when the pointer encounters a field that can be changed via, er, scrolling, the pointer could be paused for a moment and the value that the user is about to (perhaps inadvertently) change could be flashed. That should work also for the non-slider fields (the fields with up and down arrows) that I mentioned.

An additional or alternative fix: provide a 'reset to defaults' button on every settings page - or perhaps a 'reset to previous values' button.

I appreciate that implementing any or all of this might be a pain. However, irrevocably changing settings one does not mean to change - that's a pain too.

**Comment by LinuxOnTheDesktop** [comment]
To get a sense for this issue, and how it is a serious problem, try the following.

Open an image file with the Pix program. Then use the menu on the right to select 'resize'. If you screen is like mine (a laptop screen with scaling set to double because of HiDPI) you will need to scroll down to get to the 'OK' (i.e. execute) button. See how easy it is, if one scrolls down with the mouse wheel (or touchpad) to accidentally end up merily spinning the 'aspect ratio' button - and not know what it was before.

If this report should be filed elsewhere (with Gnome's GTK?) then let me know. I want to get something done about this.

**Comment by JosephMcc** [comment]
Unfortunately you're asking a bit too much here :) That's just they way those widgets work. Even if we could, or wanted, to change the behavior we couldn't do it everywhere.
