### ISSUE TITLE
Even with 80% connection, sometimes disconnects and asks for password again

### ISSUE THREAD

**Issue by DaniellMesquita** [linuxmint/cinnamon#8676]
Is it related with the network applet?

**Comment by leigh123linux** [comment]
It isn't cinnamon, it's likely to be much lower level than networkmanager.
Maybe it's a bad wifi kernel module .

**Comment by clefebvre** [comment]
When it's something at kernel level or driver level, you can usually find relevant information with the "dmesg" command in a terminal.
