### ISSUE TITLE
4.2.0 - unable to change desktop background

### ISSUE THREAD

**Issue by IvoAndonov** [linuxmint/cinnamon#8677]
* Cinnamon version (4.2.0)
   - Please specify if you are using the daily builds PPA (https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds): don't know. Whatever Arch repo brings, that's what I'm using.
 * Distribution - Arch Linux
 * Graphics hardware *and* driver used: GTX 1050 Ti 4GB, driver 430.26.
 * 64 bit
 
[xsession-errors.zip](https://github.com/linuxmint/cinnamon/files/3343471/xsession-errors.zip)

Attach /home/<username>/.xsession-errors, or /var/log/syslog
 ```

**Issue**
Unable to change desktop background



**Steps to reproduce**
Right click on the desktop and then click on "change background". Nothing happens.


**Expected behaviour**
Clicking on "change background" should bring up the window for adding images as background.


**Other information**
Restarting the DE and the distro didn't help fixing the problem.

**Comment by clefebvre** [comment]
I see two errors, both need to be fixed by Arch though, they're not on our side. You're missing the tinycss module and the GOA lib:

ModuleNotFoundError: No module named 'tinycss'
Failed to load module: /usr/lib/cinnamon-control-center-1/panels/libonline-accounts.so

**Comment by eli-schwartz** [comment]
Uh.
#8678
https://bugs.archlinux.org/task/63047
https://bugs.archlinux.org/task/63049

Please do your due diligence for a distro issue.

As for the goal thing, it's an optdepend and failure to install via just means that the cinnamon-control-center applet won't load.
