### ISSUE TITLE
4.2.0 - unable to add applets to the panel

### ISSUE THREAD

**Issue by IvoAndonov** [linuxmint/cinnamon#8678]
* Cinnamon version (4.2.0)
   - Please specify if you are using the daily builds PPA (https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds): don't know. Whatever Arch repo brings, that's what I'm using.
 * Distribution - Arch Linux
 * Graphics hardware *and* driver used: GTX 1050 Ti 4GB, driver 430.26.
 * 64 bit
 
[xsession-errors.zip](https://github.com/linuxmint/cinnamon/files/3343478/xsession-errors.zip)

**Issue**
unable to add applets to the panel

**Steps to reproduce**
1. Right click on the panel, choose "add applets". Nothing happens.
2. Open Menu and type "applets". Click on the "applets" icon. Nothing happens.
3. Reboot system and repeat steps 1 and 2. Still nothing happens.

**Expected behaviour**
Either step should bring up the applets manager.

**Other information**

**Comment by leigh123linux** [comment]
Report the issue to arch, they have a missing dependency!

```
Traceback (most recent call last):
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 724, in <module>
    window = MainWindow()
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 305, in __init__
    for module in modules:
  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_themes.py", line 6, in <module>
    from CinnamonGtkSettings import CssRange, CssOverrideSwitch, GtkSettingsSwitch, PreviewWidget, Gtk2ScrollbarSizeEditor
  File "/usr/share/cinnamon/cinnamon-settings/bin/CinnamonGtkSettings.py", line 6, in <module>
    import tinycss
ModuleNotFoundError: No module named 'tinycss'
```

**Comment by leigh123linux** [comment]
@eli-schwartz  ^^

**Comment by eli-schwartz** [comment]
https://bugs.archlinux.org/task/63047
`pacman -Syu 'cinnamon>=4.2.0-2'` -- this was fixed several hours ago, shortly after the initial release.
