### ISSUE TITLE
Keyboard shortcuts for Log out and Shut down do not work in Arch Linux

### ISSUE THREAD

**Issue by pawanneupane** [linuxmint/cinnamon#8680]
I'm using Arch Linux with Cinnamon 4.2.0 on HP Pavilion 14 Notebook. It has Intel 3rd Gen Core Processor Graphics Controller and open source driver installed with the system.

The issue I'm experiencing is that the keyboard shortcuts for Log out and Shut down do not work at all, regardless of whether I use the default shortcuts (Ctrl+Alt+Del and Ctrl+Alt+End) or try some other keybindings.

I was able to bring up the shutdown dialog by creating a custom keyboard shortcut with the command "cinnamon-session-quit --poweroff". The same command works fine when run in the terminal too.

However, when I run "cinnamon-session-quit --logout" in the terminal, I get the following error:

```
(cinnamon-session-quit:5959): GLib-GIO-CRITICAL **: 21:11:54.838: g_dbus_proxy_call_sync_internal: assertion 'parameters == NULL || g_variant_is_of_type (parameters, G_VARIANT_TYPE_TUPLE)' failed

** (cinnamon-session-quit:5959): WARNING **: 21:11:54.838: Failed to call logout

(cinnamon-session-quit:5959): GLib-CRITICAL **: 21:11:54.838: g_variant_unref: assertion 'value != NULL' failed
```

Is there a way to resolve this issue so that I can get the keyboard shorcuts for Log out and Shut down under Keyboard->Shortcuts->System to work without having to run their respective commands in the terminal or creating custom shortcuts for them?

**Comment by yparitcher** [comment]
this is an issue with cinnamon-session:
see https://github.com/linuxmint/cinnamon-session/issues/127, i think there is a fix in https://github.com/linuxmint/cinnamon-session/pull/128

**Comment by pawanneupane** [comment]
Okay. Thank you.

**Comment by eli-schwartz** [comment]
I can confirm the fix and after updating the Arch Linux package for cinnamon-session to 4.2.1 (released with this bugfix), this issue is resolved.

**Comment by pawanneupane** [comment]
> I can confirm the fix and after updating the Arch Linux package for cinnamon-session to 4.2.1 (released with this bugfix), this issue is resolved.

The keyboard shortcut for logging out has started working after updating cinnamon-session to 4.2.1. So I'm closing this issue.
