### ISSUE TITLE
Cpu Temperature indicator and Multi-Core System Monitor refuse to load in 4.2

### ISSUE THREAD

**Issue by Zerophase** [linuxmint/cinnamon#8681]
```
 * 4.2
 * Distribution - Arch Linux
 * Nvidia 430.26 and gtx 660ti
 * 64 bit
 *  [glass.log, but the log dates are far out of date](https://pastebin.com/6CmKTLUb)
```

**Issue**

Cpu Temperature indicator and Multi-Core System Monitor no longer load after the update to 4.2

**Steps to reproduce**
1. Install CPU temperature Indicator and / or Multi-Core System Monitor
2. signout and back into Cinnamon to see them not load, and receive a warning message.

**Expected behaviour**
Both applets load and no notification from Cinnamon about problems with startup.

**Comment by Odyseus** [comment]
Hello, @Zerophase.

Report issues with third party xlets in the correct repositories. For applets go [here](https://github.com/linuxmint/cinnamon-spices-applets); read and fill out the issue template.
