### ISSUE TITLE
Segfault in cinnamon when editing menu item or creating launcher

### ISSUE THREAD

**Issue by matthbak** [linuxmint/cinnamon#8683]
```
 * Cinnamon version (cinnamon --version)

$ cinnamon --version
Cinnamon 4.0.10

   - Please specify if you are using the daily builds PPA (https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds).

No

 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)

$ lsb_release -d
Description:	Linux Mint 19.1 Tessa

 * Graphics hardware *and* driver used

# Macbook pro 2017

$ lspci -k -s 00:02.0
00:02.0 VGA compatible controller: Intel Corporation Device 5926 (rev 06)
	Subsystem: Apple Inc. Device 0174
	Kernel driver in use: i915
	Kernel modules: i915

 * 32 or 64 bit

$ dpkg-architecture -q DEB_HOST_ARCH
amd6

 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
 ```

**Issue**

Segfault is logged in syslog when attempting to edit menu:
```
Jul 02 09:45:31 matthbak-lap3 kernel: cinnamon-deskto[8929]: segfault at 0 ip 00007f8f8b4844c0 sp 00007ffd06139978 error 4 in libglib-2.0.so.0.5600.4[7f8f8b449000+114000]
Jul 02 09:45:31 matthbak-lap3 kernel: Code: 66 2e 0f 1f 84 00 00 00 00 00 48 83 ec 08 e8 c7 f4 fd ff 85 c0 0f 94 c0 48 83 c4 08 0f b6 c0 c3 66 2e 0f 1f 84 00 00 00 00 00 <0f> be 17 b8 05 15 00 00 84 d2 74 24 0f 1f 40 00 89 c1 48 83 c7 01
```

**Steps to reproduce**
Happens with any of the following:

* Right-click configure menu on desktop
* Right-click on desktop create new launcher
* When using cinnamon-menu-editor from terminal and create new item or menu

**Expected behaviour**

New menu item dialogue appears.

**Other information**

**Comment by matthbak** [comment]
[syslog.txt](https://github.com/linuxmint/cinnamon/files/3349269/syslog.txt)

**Comment by clefebvre** [comment]
Can you use mintreport to get a stack trace?

**Comment by matthbak** [comment]
[crash.tar.gz](https://github.com/linuxmint/cinnamon/files/3354507/crash.tar.gz)

**Comment by matthbak** [comment]
This is from the edit menu.
[crash.tar.gz](https://github.com/linuxmint/cinnamon/files/3354512/crash.tar.gz)

Seems these might be separate issues?

**Comment by matthbak** [comment]
ps I am still having this issue. Can you shed any light? Thanks.

**Comment by icarter09** [comment]
@matthbak are you still experiencing this issue? Thanks.
