### ISSUE TITLE
Custom Shortcut For "Grouped window list"

### ISSUE THREAD

**Issue by blueray453** [linuxmint/cinnamon#8684]
I am currently using -
_Linux Mint 19.1 Tessa 
Cinnamon 4.0.10 wm_

I am using **Grouped window list** by default.

When a group of window is open and i right click, it has option for **close all** and **close others**.

![Screenshot from 2019-07-03 14-25-18](https://user-images.githubusercontent.com/855297/60576508-5ef53580-9d9f-11e9-89d9-305da17ce378.png)

I need to assign shortcut for these two commands. How can I do that?

**Comment by smurphos** [comment]
You can't assign shortcuts directly to grouped window list options. But you can script equivalent functions which you can link to keyboard shortcuts, nemo right click context menu as a custom action, or a desktop/menu/panel launcher.

See https://github.com/smurphos/nemo_actions_and_cinnamon_scripts/blob/master/.local/share/nemo/actions/scripts/close_windows.sh for an example to get you started. As written it provides a close all windows, and a close all windows in current workspace function. I use it with a pair of nemo actions that appear in the desktop right click context menu - https://github.com/smurphos/nemo_actions_and_cinnamon_scripts#close-windows-actions

**Comment by JosephMcc** [comment]
As noted this isn't possible but smurphos shows how to get what you probably want.
