### ISSUE TITLE
Feature Request: Import/export keyboard shortcut settings

### ISSUE THREAD

**Issue by coreyfarrell** [linuxmint/cinnamon#8686]
```
 * Cinnamon version 4.0.10
 * Distribution - Fedora 30
 * Intel Corporation UHD Graphics 620, default driver
 * 64 bit
 ```

**Issue**
I do a clean install of Fedora about every 12 months instead of upgrading so I keep my system relatively clean.  It would be very nice if the keyboard configuration panel offered import/export buttons.  I've tried accomplishing this with `dconf dump` however global keyboard settings are stored under many different keys.

This request could be applied to most/all cinnamon-settings panels, though for me the keyboard shortcuts are by far the most important.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.
