### ISSUE TITLE
No seekbar in the Sound applet for some applications

### ISSUE THREAD

**Issue by basilky** [linuxmint/cinnamon#8690]
```
 * Cinnamon 4.0.10
 * Distribution - Mint 19.1
 * 64 bit
 ```
 There is a seekbar in the Sound applet when using applications like Rhythmox and VLC media player, so that I can easily control the player even when it is closed. But this is not present for applications like Audacious and Xplayer. I'm not sure whether this is something that the application should support or a bug in the Sound applet.

**Comment by germanfr** [comment]
The seek bar wan't showing in Audacious due to a bug in their MPRIS implementation. we now gracefully handle it.

Xplayer is blacklisted in the sound applet because it didn't properly support seeking from the MRPIS interface. I just tried it again with xplayer 2.0.1 and it still does not work. I get this exception when I try to set the position value:

```
Cinnamon warning: Log level 8: g_variant_new_object_path: assertion 'g_variant_is_object_path (object_path)' failed

(cinnamon:8828): Cjs-WARNING **: 18:24:59.833: JS ERROR: Exception in callback for signal: drag-end: Error: Array element (type interface) may not be null
_pack_variant@resource:///org/cinnamon/cjs/modules/overrides/GLib.js:156:9
_init/this.Variant._new_internal@resource:///org/cinnamon/cjs/modules/overrides/GLib.js:260:16
_proxyInvoker@resource:///org/cinnamon/cjs/modules/overrides/Gio.js:66:21
_makeProxyMethod/<@resource:///org/cinnamon/cjs/modules/overrides/Gio.js:112:16
_setPosition@/home/german/.local/share/cinnamon/applets/sound@cinnamon.org/applet.js:384:13
anonymous/Seeker/<@/home/german/.local/share/cinnamon/applets/sound@cinnamon.org/applet.js:255:42
_emit@resource:///org/cinnamon/cjs/modules/signals.js:142:27
Slider.prototype._endDragging@/usr/share/cinnamon/js/ui/slider.js:141:13


```

**Comment by basilky** [comment]
Xplayer was replaced by Celluloid, whch supports MPRIS.
