### ISSUE TITLE
Build for cinnamon 4.2 doesn't work with removed .la files

### ISSUE THREAD

**Issue by joequant** [linuxmint/cinnamon#8691]
I'm building packages for cinnamon and this involves removing .la files.  This works for 4.0.10, but in 4.2 the build tries to build libcinnamon.la which fails because of a lack of libmuffin-clutter-0.la

I can try fixing this problem, but would like some pointers.
```
make[3]: Leaving directory '/home/joe/local2/bench/mgarepo/cinnamon/BUILD/cinnam
on-4.2.0/src'
make[3]: Entering directory '/home/joe/local2/bench/mgarepo/cinnamon/BUILD/cinnamon-4.2.0/src'
  CCLD     libcinnamon.la
/usr/bin/grep: /usr/lib64/muffin/libmuffin-clutter-0.la: No such file or directo
ry
/usr/bin/sed: can't read /usr/lib64/muffin/libmuffin-clutter-0.la: No such file 
or directory
libtool:   error: '/usr/lib64/muffin/libmuffin-clutter-0.la' is not a valid libt
ool archive
make[3]: *** [Makefile:1150: libcinnamon.la] Error 1
```

**Issue**

Package cinnamon packages without .la files

**Steps to reproduce**
Create muffin files without .la files.  Building cinnamon 4.2  works for 4.0.10

**Expected behaviour**

**Other information**

**Comment by leigh123linux** [comment]
I don't have any issue here building cinnamon-4.2.0, I delete the muffin .la files

```
%build
%configure --disable-static \
           --enable-startup-notification=yes \
           --disable-silent-rules \
           --enable-gtk-doc \
           --disable-clutter-doc \
           --disable-wayland-egl-platform \
           --disable-wayland-egl-server \
           --disable-kms-egl-platform \
           --disable-wayland \
           --disable-native-backend

%make_build V=1

%install
%make_install

# Create a dummy themes directory so that cinnamon settings will see
# the Adwaita fallback theme which has been removed from gnome-themes-standard
mkdir -p %{buildroot}/%{_datadir}/themes/Adwaita/metacity-1/
cp %{SOURCE1} %{buildroot}/%{_datadir}/themes/Adwaita/metacity-1/

#Remove libtool archives.
find %{buildroot} -name '*.la' -exec rm -f {} ';'
```

https://kojipkgs.fedoraproject.org//packages/cinnamon/4.2.0/2.fc31/data/logs/x86_64/build.log

**Comment by joequant** [comment]
Yes.  Noticed that.  Can't figure out what it works for you.

Not sure what is going on, but it may be that there is some race condition in the build.

**Comment by joequant** [comment]
The one difference is that Mageia has --no-undefined

This might be causing the build to recurse and look for other la files

**Comment by joequant** [comment]
found the problem.  I didn't get rid of all my libmuffin.la files.  Closing

**Comment by joequant** [comment]
Thanks!!!
