### ISSUE TITLE
Settings not working in mint

### ISSUE THREAD

**Issue by jamieduk** [linuxmint/cinnamon#8694]
I use linux mint Cinnamon 4.0.10 Distro: Linux Mint 19.1 Tessa 
  base: Ubuntu 18.04 bionic  64 bit KDE and settings have stopped displaying from settings nothing opens and it logs out after some time randomly how can i use command line to fix it so settings work so i can open power settings and screen saver settings other settingsin general when they stop working please?

**Comment by clefebvre** [comment]
open a terminal and type: cinnamon-settings.

Paste the output here.
