### ISSUE TITLE
The mintUpdate icon does not appear when system start

### ISSUE THREAD

**Issue by marcogiannini** [linuxmint/cinnamon#8695]
The mintUpdate icon does not appear when system start. The icon is as if it were invisible. If I right-click on where the icon should be, the mintUpdate menu appears. To make the icon reappear I have to restart cinnamon from the special function integrated in the troubleshooting
```
* Cinnamon 4.2.0
* Linux Mint 19.1 (With Tina repositories set manually)
* nvidia 390.x
* 64 bit

![Schermata del 2019-07-06 22-27-49](https://user-images.githubusercontent.com/4943897/60760898-96810d80-a03d-11e9-8301-78ea52c5fa49.png)
[xsession-errors.txt](https://github.com/linuxmint/cinnamon/files/3365002/xsession-errors.txt)

**Comment by claudiux** [comment]
Same issue.

**Comment by kelebek333** [comment]
You can try to apply following temp fix. 

Open /usr/share/cinnamon/applets/systray@cinnamon.org/applet.js file.

`sudo xed /usr/share/cinnamon/applets/systray@cinnamon.org/applet.js`

Find following line,

`const NO_RESIZE_ROLES = ['shutter', 'filezilla'];`

and add mintupdate.py and save applet.js file.

`const NO_RESIZE_ROLES = ['shutter', 'filezilla', 'mintupdate.py'];`

If you are using uget, edit the file as follows.

`const NO_RESIZE_ROLES = ['shutter', 'filezilla', 'mintupdate.py', 'uget-gtk'];`

**Comment by kelebek333** [comment]
You can try to apply following temp fix. 

Open /usr/share/cinnamon/applets/systray@cinnamon.org/applet.js file.

`sudo xed /usr/share/cinnamon/applets/systray@cinnamon.org/applet.js`

Find following line,

`const NO_RESIZE_ROLES = ['shutter', 'filezilla'];`

and add mintupdate.py and save applet.js file.

`const NO_RESIZE_ROLES = ['shutter', 'filezilla', 'mintupdate.py'];`

If you are using uget or telegram-desktop, edit the file as follows for bad looking systray icons.

`const NO_RESIZE_ROLES = ['shutter', 'filezilla', 'mintupdate.py', 'uget-gtk', 'telegramdesktop'];`

**Comment by kelebek333** [comment]
I was able to solve this issue by resetting the all dconf settings and reinstalling cinnamon-common  package (reset for edited files) with following commands. 

```
dconf reset -f /
apt reinstall cnnamon-common
```

**Comment by kelebek333** [comment]
I was able to solve this issue by resetting all dconf settings and reinstalling cinnamon-common  package (reset for edited files) with following commands. 

```
dconf reset -f /
apt reinstall cinnamon-common
```

**Comment by marcogiannini** [comment]
The bug is still present in Beta release

**Comment by clefebvre** [comment]
Do you guys have indicators enabled in the Cinnamon settings?

**Comment by marcogiannini** [comment]
Yes, the "notification area" applet is enabled. I tried reinstalling Mint 19.2 Beta from scratch and the bug is still present.

**Comment by kelebek333** [comment]
My settings is; indicators disabled and panel height 32.

**Comment by kelebek333** [comment]
I downgrade mintupdate to 5.4.7/tina and there is no issue with this. I think, this is not a Cinnamon issue. Issue related with MintIpdate's updates.

**Comment by kelebek333** [comment]
I manually downgrade mintupdate to 5.4.7/tessa and there is no issue with this. I think, this is not a Cinnamon issue. Issue related with MintUpdate's updates.

**Comment by clefebvre** [comment]
@kelebek333 and 5.4.8 is buggy?

Do you know how to bisect? If so can you identify the offending commit?

**Comment by claudiux** [comment]
For info, here a part of my .xsession-errors file:
```
Cjs-Message: 16:02:01.181: JS LOG: [LookingGlass/info] Cinnamon took 2574 ms to start
Cjs-Message: 16:02:01.248: JS LOG: Unknown network device type, is 14
Cjs-Message: 16:02:01.677: JS LOG: [LookingGlass/info] Hiding systray: network
/usr/share/cinnamon-screensaver/cinnamon-screensaver-main.py:86: Warning: g_base64_encode_step: assertion 'in != NULL' failed
  css = provider.to_string()
Cjs-Message: 16:02:19.630: JS LOG: [LookingGlass/info] Adding systray: mintupdate.py (24x24px)
Cjs-Message: 16:02:19.631: JS LOG: [LookingGlass/info] Resized mintupdate.py with normalized size (24x24px)

```

Mintupdate is here, but no icon is displayed:

![mintupdate-missing-icon](https://user-images.githubusercontent.com/33965039/61720305-ced75a00-ad66-11e9-8938-6d3aa5f02296.png)

**Comment by clefebvre** [comment]
yeah, you can see the top right part of it somehow.

**Comment by kelebek333** [comment]
> @kelebek333 and 5.4.8 is buggy?
> 
> Do you know how to bisect? If so can you identify the offending commit?

I install mintupdate 5.4.8/tina and hold it. There is same issue with 5.4.8.

>             # Starts the blinking
>             self.application.set_status("", _("Checking for updates"), "mintupdate-checking", not self.application.settings.get_boolean("hide-systray"))
>             Gdk.threads_leave()

Maybe, there's a problem with the hiding mechanism.

**Comment by kelebek333** [comment]
I downgrade Cinnamon 4.2.x/tina to Cinnamon 4.0.x/tessa on my system. In this case, I have observed that the update manager issue persists.

![cinnamon-4 0-mintupdate-5 5 4 8](https://user-images.githubusercontent.com/1300133/61747327-4aa4c700-ada6-11e9-80ca-cee12dfc6097.png)
![cinnamon-4 0-mintupdate-5 5 5 0](https://user-images.githubusercontent.com/1300133/61747331-4c6e8a80-ada6-11e9-8db5-360f2f867167.png)

**Comment by NikoKrause** [comment]
@kelebek333 It's not a Cinnamon issue. It's an mintupdate issue. I found the responsible commit and a fix will be ready soon.

If you wanna try, re-add the following 3 lines (lines 1232 till 1234) to your `mintUpdate.py` file: https://github.com/linuxmint/mintupdate/commit/1b332f7cb8977d0e1df0c7dd8b51783970a35828#diff-a865656bf15d1ec483a023744089ed17L1232

**Comment by kelebek333** [comment]
@NikoKrause , thanks you, issue is solved by way you show.

Actually, I realized it wasn't a Cinnamon problem. I was just trying to eliminate the possibilities with different versions.

**Comment by NikoKrause** [comment]
@kelebek333 Thanks for confirming. Actually it was your observation that 5.4.7 was fine, which helped solving this issue.

**Comment by claudiux** [comment]
This works now like a charm.

_Three lines of code are missing and everything is depopulated._

Thank you @NikoKrause.

**Comment by clefebvre** [comment]
https://github.com/linuxmint/mintupdate/commit/e6a6f21cc60f63da1f2a74f14754f1508e306bc4 in 5.5.1

**Comment by Scrat-fflm** [comment]
Hello, this is Scrat at FFLM.

My laptop has Linux Mint 19.2 x64, Cinnamon 4.2.3, mintupdate 5.5.4.
Sorry, but applying the patch suggested by NikoKrause (adding 3 lines to mintUpdate.py) does not solve the problem. The problem appears always randomly: sometimes the icon is shown, sometimes (very often) it is not.
The workaround is restarting Cinnamon: it always restores the icon.
Here is the link of my last post on FFLM (in french):
https://forum-francophone-linuxmint.fr/viewtopic.php?f=23&t=13598&p=155575#p155575
