### ISSUE TITLE
Linux Mint only boots when moving the mouse

### ISSUE THREAD

**Issue by SoulInfernoDE** [linuxmint/cinnamon#8697]
Hello there,
i have a weird issue with some of my laptops. Especially with my Dell Inspiron N5050.

I am using Linux Mint 19.1  with Cinnamon 4.0.10 64bit version.

**Issue**

Linux Mint 19.1 Cinnamon only boots when moving the mouse either on the usb port or on the internal touchpad of the laptop.

With my second laptop - a lenovo thinkpad - it speeds up loading the desktop. Without moving mouse cursor or touching the touchpad it takes up to ten minutes to boot to the desktop.

**Steps to reproduce**

I don't know yet. But in fact this happens to many of laptops i installed this should be a bug.

**Expected behaviour**

Linux start up fast until desktop reached.

**Other information**

I am using the newest kernel build with ukuu. I know this could be kind of a problem but so far i could fix all problems caused due to new kernels myself. I find actual kernels more stable and faster. Navigating through files is very fast that's why i want those new kernels to work with cinnamon and mint.
It really works very well - but this mouse bug is the only confusing part about linux mint at the moment which i couldn't fix.

System report attached:::
[HardInfo report](https://owncloud.damnserver.com/index.php/s/R2S6teiyyE8gLa3/download)

**Comment by leigh123linux** [comment]
Slow boot is down to the kernel not cinnamon.

**Comment by SoulInfernoDE** [comment]
with other desktops it works but not eith cinnamon
