### ISSUE TITLE
Feature request: More list columns for Nemo

### ISSUE THREAD

**Issue by ParaDice13** [linuxmint/cinnamon#8698]
So far, Nemo's list view mode only has a very limited number of very general attributes by which we can sort files:

![Screenshot from 2019-07-07 21-42-21](https://user-images.githubusercontent.com/52176040/60773360-9a2b9780-a104-11e9-9f07-bd48aa8d7ef6.png)

I'd love to see more attributes specific to certain file extensions, images and videos in particular. For instance, it would be awesome to be able to sort images by EXIF data such as image size (in px), shutter time, aperture or (star) rating.

Did I overlook anything or is there currently no way to get Nemo to do this? If not: let's have it!  :D

[To give a little balance to the intentionally demanding tone above: Nemo is imho the most advanced and feature-complete file explorer out there. BIG kudos to the devs!]

**Comment by mtwebster** [comment]
The nemo-media-columns extension might do what you need it to.  You didn't mention your distribution, but it should be available anywhere nemo is.  That adds a large number of media-related columns.  Be warned, there is a performance hit when this is enabled.

Once installed, you can manage it from Preferences->Plugins

Also, you don't need to use the preferences window you show above, visible columns can be changed by right-clicking a column header in the view itself.

**Comment by ParaDice13** [comment]
Thanks, I seem to have overlooked that! Works great, thanks for pointing me in the right direction!

@Preferences: I'm aware of that, I just thought that the preferences view showed better what I meant. ;)
