### ISSUE TITLE
[Question] Is there a source of the basic Cinnamon webview engine that renders CSS/JS?

### ISSUE THREAD

**Issue by DaniellMesquita** [linuxmint/cinnamon#8699]

**Comment by DaniellMesquita** [comment]
Reference: https://github.com/linuxmint/cinnamon/issues/8656

**Comment by mtwebster** [comment]
Cinnamon uses js for running much of the desktop's ui (panels, applets, etc..).  It does this thru gobject introspection bindings (cjs/gjs) to use C libraries.  It currently uses MozJS/spidermonkey.  You could replace JS with any other language, however, and the capabilities remain more or less the same.

The CSS is used to theme these elements, but the use of it is independent of any particular language - much of cinnamon is also written in C, as is the themed widget toolkit used.  CSS just happens to be the most effective means of applying theme elements.  This is also the case with Gtk as well (which has nothing to do with JS, but can be used by JS via introspection).
