### ISSUE TITLE
Cinnamon uses software rendering mode on VirtualBox even with Guest Additions and 3D acceleration

### ISSUE THREAD

**Issue by sergiomt** [linuxmint/cinnamon#8700]
```
 * Cinnamon version 3.6.7
 * VirtualBox 5.2.30
 * Guest CentOS 7.6.1811 
 * Host Windows 10
 * 64 bits
 ```
I've got a CentOS 7.6.1811 guest running on Windows 10 and VirtualBox 5.2.30 with 3D Acceleration enabled.

The Linux guest has VirtualBox Guest Additions of the same version installed.

I had to install specific versions of kernel-headers and kernel-devel for 3.10.0-957.5.1 because the default yum install kernel-headers kernel-devel was installing headers for a slightly different version and vboxadd setupcomplained about it.

Now, despite I have followed every possible step found in instructions and forums, Cinnamon 3.6.7 continues using software rendering mode with nothing but a line at glass.log reading:

`error t=... Cinnamon Software Rendering Mode Enabled`

And at .xsession-errors there are two lines:
```
openGL version 2.1 Mesa 18 detected (GL Cogl Driver)
MetaSyncRing disabled: couldn't find required GL extensions, or the minimum safe openGL version was not met
```

Cinnamon boots with LightDM.

The interesting fact is that in the same VirtualBox I have another guest running the same OS but with VirtualBox Guest Additions 5.2.18 and it works fine. These other VM was created before VirtualBox was upgraded from 5.2.18 to 5.2.30.

Is there any way to debug Cinnamon in order to determine why is it still using software rendering mode?

**Comment by clefebvre** [comment]
This isn't an issue with Cinnamon, it's an issue with the 3d acceleration on the system. You can use inxi -Gxx to check the difference between the two environments.

Other than that, also make sure you're running the Cinnamon session, not the Cinnamon2d session, from LightDM.
