### ISSUE TITLE
Can't stick some apps on a specific workspace

### ISSUE THREAD

**Issue by sbraaa** [linuxmint/cinnamon#8703]
I'm using Linux MInt 19.1 with Cinnamon 4.0.10 
Some apps (actually Firefox, SlimJet and Opera) when launched are visibile on all workspace for default.
If I try to stick them on a specific workspace but It doesn't work!
Obviously I've tried to set correctly the panel (show in all workspace -> disabled) but those apps still remains visibile on all workspaces.

**Comment by icarter09** [comment]
We believe this issue is fixed. Please test against the latest Cinnamon version (4.2). 
If the issue happens again, create a new issue and add the output of "cinnamon-settings sound".
