### ISSUE TITLE
Skype tray icon repeated

### ISSUE THREAD

**Issue by SamBurgos** [linuxmint/cinnamon#8704]
```
 * Cinnamon version: Cinnamon 4.2.0 
 * Distribution; Manjaro (and probably Arch Linux)
 * Graphics hardware *and* driver used: Intel HD Graphics 5500
 * 64 bit
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
 ```

**Issue**
On a Cinnamon 4.2.0 installation the Skype tray icon is repeated several times when started

**Steps to reproduce**
It is hard to give some steps because happens almost randomly (and I wasn't able to take a screenshot properly to showcase it) but so far the process I stumble with is the following:
1. Install Skype for Linux (must use the deb)
2. On Cinnamon Settings turn on the option "enable indicator support"
3. Restart the machine or turn it on
4. Open Skype

**Expected behaviour**
Only one tray icon/indicator of Skype is available

**Actual behaviour**
There are a lot of tray icon/indicator of Skype
**EDIT:** Added the actual behaviour
![Cinnamon Skype](https://user-images.githubusercontent.com/1509924/60981531-be999680-a2f3-11e9-85cc-f84bacf8853f.png)

**Other information**
Besides Skype I have used WhatsApp and Bitwarden as other Electron applications and so far only Skype is giving me this behaviour (if someone else have another Electron app so we can check if the issue is from Cinnamon, Skype or Electron it would be truly appreciated). Doing a "cinnamon --restart" or "Alt + F2" then "r" makes it appear only once

Before the restart
[xsession-errors.tar.gz](https://github.com/linuxmint/cinnamon/files/3378086/xsession-errors.tar.gz)

After the restart
[xsession-errors1.tar.gz](https://github.com/linuxmint/cinnamon/files/3378111/xsession-errors1.tar.gz)

Cinnamon general settings
![Cinnamon info](https://user-images.githubusercontent.com/1509924/60979984-dcb1c780-a2f0-11e9-9692-17a9e3a710cb.png)

**Comment by SamBurgos** [comment]
Greetings, adding even more information I manage to also replicate this issue with a Remmina build that includes AppIndicator, adding another screenshot

![RemminaIndicator](https://user-images.githubusercontent.com/1509924/61256076-8eedf280-a728-11e9-8c26-e50d6088311d.png)

So far the only workaround for me to use the apps and prevent this issue is to disable support for appindicators in Cinnamon, then everything is fixed

![IndicatorOff](https://user-images.githubusercontent.com/1509924/61256221-25baaf00-a729-11e9-8a5b-e50e3655459c.png)

![AllAppsInfo](https://user-images.githubusercontent.com/1509924/61256229-2eab8080-a729-11e9-98ff-47ecbb53bdab.png)

I attach other 2 xsession-errors files which contemplates the issue and gives some more description (in all xsessions attachments you can look for either "skype" or "remmina"

[xsession-errors2.tar.gz](https://github.com/linuxmint/cinnamon/files/3394593/xsession-errors2.tar.gz)

[xsession-errors3.tar.gz](https://github.com/linuxmint/cinnamon/files/3394605/xsession-errors3.tar.gz)

Also, this happens with any icon theme (on my installation I have tested Suru++ and Mint-Y in any of its variants)

**Comment by LinuxOnTheDesktop** [comment]
The same problem can beset Dropbox, as reported [here](https://github.com/linuxmint/alpha-testing/issues/8).
