### ISSUE TITLE
Using the numpad to control the mouse not working after startup

### ISSUE THREAD

**Issue by Numnumberry** [linuxmint/cinnamon#8706]
```
 * Cinnamon version 4.0.10
   - not using daily builds PPA
 * Distribution - (Mint 19.1)
 * 64 bit

**Issue**

After setting up the number pad to move the mouse and click using the '5' key, it will not work after startup.

**Steps to reproduce**

1) Set up the numpad to be able to control the mouse. See that it works.
2) Reboot the system.
3) See that the numpad will not move/click the mouse.
4) Can get it to work by entering the "Accessibility" menu and then closing the menu (you do not need to click anything within the menu) then the numpad will work again.

**Expected behaviour**

Expected the numpad to control the mouse immediately after powering on machine.

**Comment by icarter09** [comment]
@Numnumberry where are you setting up the numpad to use the mouse?

**Comment by Numnumberry** [comment]
I set this up under Accessibility, Mouse, under Mouse Keys I select
"Control the pointer using the keypad"

The issue seems to be random, that is, it will sometimes work when I power
on the computer, but sometimes it will not and I need to open the
Accessibility window to trigger it to work.

**Comment by icarter09** [comment]
@Numnumberry thanks. I'll test this out tonight.

**Comment by icarter09** [comment]
Linux Mint 19.2
Cinnamon 4.2.4

I just tested it out and wasn't able to reproduce the issue. But you did say it was random so that could be the case.

**Comment by Numnumberry** [comment]
thanks for looking into it though, if I recall correctly, the numpad would
sometimes start working by itself with me waiting for maybe 10 minutes, so
maybe there is some process that needs to kick in, but then again sometimes
it seemed to never start working until I opened the Accessibility window,
which started whatever process/initialization. thanks though

**Comment by icarter09** [comment]
@Numnumberry no problem. Do you think this ticket should be left open or closed?

**Comment by Numnumberry** [comment]
I just tested 3 times and could not get it to replicate, I guess close it,
it is not a huge issue, just a minor annoyance everyone once in a while
when I used to code with that computer everyday, I keep it up to date so
maybe something fixed it
