### ISSUE TITLE
[Feature Request] Sticky entries in "recent documents" (or increasing the list)

### ISSUE THREAD

**Issue by laex333** [linuxmint/cinnamon#8709]
```
 * Cinnamon version 4.0.10
 * Mint 19.1 64 bit
 ```

I need to have a couple (maybe around ten) of files always at my fingertips. I like to open them via the home button and then typing the name of the file... My problem is that the "recently used files" list is not long enough to keep my regularly needed documents available.

I did quite some research, but at the moment it seems impossible to increase the length of the list (tried also Dconf-editor etc.), nor can I make entries "sticky" so they are not kicked out so soon...

I found two solutions, but both are not perfect:
a) Create one starter for each regularly needed document. I find this relatively laborious and it creates many additional menu entries.
b) As described in https://forums.linuxmint.com/viewtopic.php?t=93354: Manually edit recently-used.xbel and make it immutable:
$ chattr +i /home/YOURUSER/.local/share/recently-used.xbel
Unfortunately this way "recently documents" looses its original meaning all together.

Two suggestions/ideas for great improvement:
a) Make it possible to have sticky entries in the list.
b) Make it possible to increase the length of the list so the files are not kicked out so quickly.

Other solutions more than welcome - thank you!
Best regards
laex

**Comment by clefebvre** [comment]
Hi @laex333 we're planning this for the xmas release (19.3 with cinnamon 4.4). The WIP is called starred/favorite items. You'll be able to favorite files and folders and access them easily from a variety of applications.

**Comment by laex333** [comment]
Great news! Thanks a lot for the quick and clear answer, Clem - bravo!
