### ISSUE TITLE
Infos about applets in Cinnamon Settings are not up to date

### ISSUE THREAD

**Issue by claudiux** [linuxmint/cinnamon#8712]
```
 * Cinnamon version 4.0.10 and 4.2.0 (_nightly build_)
 * Distribution Mint 19.1
 ```
**Issue**
The Download page of Cinnamon Settings Applets ~~(or Desklets or Extensions or Themes)~~ is never up to date. Unable to update any ~~xlet~~ applet or view any new ~~xlet~~ applet.

_Applets sorted by date:_
![Applets_Date](https://user-images.githubusercontent.com/33965039/61097085-2bc73c00-a45a-11e9-893e-c269d37d4701.png)

These informations are not updated for at least a month, comparing with the _Latest Applets_ page (https://cinnamon-spices.linuxmint.com/applets/latest).

**Steps to reproduce**
Cinnamon 4.0: `cinnamon-settings applets` then click the Download tab. The list is sorted by Popularity. Look at the stars. (SpicesUpdate has 20 stars; it has 23 stars on the page https://cinnamon-spices.linuxmint.com/applets/view/309)

Try to refresh the list. No change is made.

Sort the list by date. No new applets are displayed.

Cinnamon 4.2: `cinnamon-settings applets -t download -s popularity` and `cinnamon-settings applets -t download -s date`. Same observations.

**Expected behaviour**
Infos become again up to date.

**Other information**
The json file https://cinnamon-spices.linuxmint.com/json/applets.json is not up to date. Maybe a stopped service?

~~This bug also affects desklets and extensions. Curiously, not themes.~~

The spices-notifier@germanfr and SpicesUpdate@claudiux, which are using this json file to get infos, are also affected.

**Comment by claudiux** [comment]
The file https://cinnamon-spices.linuxmint.com/json/applets.json has not been updated since June 3, 2019.

All other files are up to date.

![IndexOfJson](https://user-images.githubusercontent.com/33965039/61346864-ea200200-a85a-11e9-9401-de65aed6e022.png)

**Comment by claudiux** [comment]
Always nothing: https://cinnamon-spices.linuxmint.com/json/

**Comment by clefebvre** [comment]
Fixed.

**Comment by claudiux** [comment]
Many thanks @clefebvre !
