### ISSUE TITLE
keyboard not working for normal user

### ISSUE THREAD

**Issue by jeroendiederen** [linuxmint/cinnamon#8714]
```
 * Cinnamon version (cinnamon --version)
   - Please specify if you are using the daily builds PPA (https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds).
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
 * Graphics hardware *and* driver used
 * 32 or 64 bit
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
 ```

**Issue**
If I login from lightDM as myself (the administrator), the keyboard is working properly. If I however logout and login as a 'normal' user (my son's account), then after logging into gnome session the keyboard no longer works. Logging out to lightdm will give me a non-working keyboard. I need on screen keyboard to login as administrator and then when it opens a new gnome session as administrator the keyboard works fine again.

**Steps to reproduce**

**Expected behaviour**

**Other information**

**Comment by clefebvre** [comment]
Does it happen with other sessions or only with cinnamon?

**Comment by jeroendiederen** [comment]
I tried LXDE and then it works fine. It seems to be cinnamon specific.

**Comment by jeroendiederen** [comment]
Please close this bug report. It was my mistake. I had F6 MacBook key pressed and lit. After pressing F6 I could use the keyboard with the normal user. Sorry for the inconvenience. Regards, Jeroen
