### ISSUE TITLE
Keyboard key "/?" not working on a HP elitebook 830 G5

### ISSUE THREAD

**Issue by edsenabr** [linuxmint/cinnamon#8728]
* Cinnamon version (cinnamon --version)
   - Cinnamon 3.6.7 (3.6.7-8ubuntu1)
 * Distribution - Ubuntu 18.04.2
 * 64 bit
**Issue**
I've just added cinnamon packages to an existing Ubuntu 18.04.2 installation, running on a HP Elitebook 830 G5 laptop, but it's behaving wrong when it comes to the keyboard recognition: Both at console and gnome3 the key "/?" is working properly, however on cinnamon it is producing the "+" character. 

**Steps to reproduce**
Install cinnamon on a HP Elitebook 830 laptop

**Expected behaviour**
The key "/?" should be working out of the box, as it does on gnome3 and console.

**Comment by brownsr** [comment]
As you have installed without going through the installation dialogue (if you install from ISO), perhaps the keyboard layout picked up by Cinnamon does not match yours. I'd suggest going into the keyboard settings, and adding another setting that looks as if it matches yours.  The list to the left allows up to 4 layouts.  There is a button that shows the key layout so you can see how it compares to yours. The top entry is the active one.  There is a keyboard applet you can install to allow easy switching.  Also worth looking at languages, locale to see if that looks right.

If this doesn't help I would suggest the forums or the IRC support channel.  You may find someone who has met this before. As this report is on an older version of Cinnamon, and a specific laptop, and directly on Ubuntu then it won't be feasible for a developer to reproduce as it isn't a combination we will have to hand.

**Comment by edsenabr** [comment]
I've updated my cinnamon to 4.0.9 (actually removed the previous one and installed v 4.0.9) and the same problem persists. It's not a matter of layout selection, but wrong detection of the pressed key,
