### ISSUE TITLE
[Feature Request] File type exclusion in the recent documents from menu

### ISSUE THREAD

**Issue by SonephetR2** [linuxmint/cinnamon#8730]
```
Linux Mint 19.1 64 bit, Cinnamon 4.0.9
```

Currently, by default, the Recent Documents from the (Cinnamon) menu displays up to 20 recently accessed files or folders, typically resulting in a motley assortment of images, scripts, debian packages, documents and folders. I believe it would be useful to be able to exclude some file types from the log as users such as myself typically use Recent Documents with the intention to access only specific types of files – only documents for instance –, and it would be not to have to sift through a list of miscellaneous files and folders hoping that any desired file is still among the twenty most recently accessed files.

I tried looking whether I could find an opportunity for a crude hack and, as I understand it, `docInfo.js` controls what appears in the recently accessed files of the menu. [On line 37](https://github.com/linuxmint/Cinnamon/blob/067e1dabe369ceb72de7558b1d63af826f748f8a/js/misc/docInfo.js#L37), I see a `get_mime_type()`, so maybe, once mime_type is fetched, there could be a sift, with a variety of "if mime_type is X, then exclude" tests. `/home/<user>/.local/share/recently-used.xbel` would then not be populated with files from the excluded file types... Unfortunately, that's about as far as can I get with my paucity of coding skills.

The Menu > Preferences > Privacy GUI interface could offer a quick and convenient access to blacklisting by offering the possibility to "Prevent logging for the following file types:", say for Folders, Audio, Video, Images, Spreadsheets, Presentations, PDFs, Ebooks, Text documents, Scripts/Executables. By excluding non relevant types, a programmer would be able to see only Scripts, an accountant only Spreadsheets and PDFs, a graphic designer only image files...

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.

**Comment by SonephetR2** [comment]
@socketbox Thanks for the pointer! An URI-based solution is better that having nothing at all. gtk-recent-scrubber work is coded for Python2 however. Have you updated it (or expanded it) for use with Python3? I updated `except ValueError, err` to `except ValueError as err`, `gtk` to `gi`, `urllib` to `urllib.request ` and `urllib.pathname2url` to `urllib.request.pathname2url`, added an .encode('utf-8'), removed deprecated 'U' mode in `rU`. That solved most but not all of the error codes. Anything else I should be doing to make this work?
