### ISSUE TITLE
[Feature Request] Add a GUI selection when pressing "SuperKey + P" for switching displays/monitors

### ISSUE THREAD

**Issue by KenWeiLL** [linuxmint/cinnamon#8733]
Pressing "SuperKey + P" on Windows shows this:
https://lookimg.com/images/2019/07/21/nu0Id.jpg

Pressing "SuperKey + P" on Debian 10 KDE shows this:
https://lookimg.com/images/2019/07/21/nuThv.jpg

Pressing "SuperKey + P" on Ubuntu GNOME shows this:
https://lookimg.com/images/2019/07/21/nudjE.jpg

But on Cinnamon, pressing "SuperKey + P" shows nothing to select. It just applies the setting immediately. It doesn't display a selection on what monitor/screen you want to display.

I hope Cinnamon will also have the option to let users select what settings they want to select.

I tested this even on Cinnamon 4.2.2 that comes with Linux Mint 19.2 Beta and still, pressing "SuperKey + P" won't display anything for the user to select what settings.

**Comment by VaGNaroK** [comment]
wow!! this is interesting.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
