### ISSUE TITLE
Package not installable on Debian 10 due to missing dependency

### ISSUE THREAD

**Issue by Saphar** [linuxmint/cinnamon#8735]
```
 * Cinnamon version (cinnamon --version)
   - 4.2 (build on Debian 10)
 * Distribution - Debian 10
 * 64 bit
 ```

**Issue**
Build package doesn't install because of missing dependency. Dependency 'gnome-icon-theme-symbolic' is now provided by 'adwaita-icon-theme' as stated here:

[https://packages.debian.org/buster/gnome-icon-theme-symbolic](url)

**Steps to reproduce**
Build on Debian 10 (or testing) and try to install package.

**Expected behaviour**
Package would install as dependencies can be met from repositories.

**Comment by claudiux** [comment]
Also, the `streamer` package (another dependency) does not exist for Debian 10.

**Comment by icarter09** [comment]
@claudiux any update on this?

**Comment by claudiux** [comment]
@icarter09 This issue is still present.

**Comment by clefebvre** [comment]
Hi,

Cinnamon should work anywhere, but please be aware that each distribution has its own packaging. What's in debian/ is there for convenience but it's Mint's package, not Debian's.

PS: Afaik gir1.2-timezonemap-1.0 also is missing in Debian.
