### ISSUE TITLE
Option for limiting the menu's width

### ISSUE THREAD

**Issue by Z7QsbkpL5T** [linuxmint/cinnamon#8742]
```
 * Cinnamon 4.2.3
   - No
 * Arch Linux
 * Intel HD Graphics 630, modesetting
 * 64 bit
 ```

**Issue**
The menu becomes unnecessarily wide whenever there're entries with really long names, causing it to look something like this.
![image](https://user-images.githubusercontent.com/49502778/62064070-aa93e580-b25e-11e9-8fa9-231751b74a4c.png)

**Steps to reproduce**
Add such an entry to your menu with the method of your choice. (e.g. using the menu editor)

**Expected behaviour**
Those entries' names get truncated to a length controlled by an option (which does not exist as the moment)

**Other information**
This applies to both categories and applications entries

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
