### ISSUE TITLE
Feature Request: Desktop Zoom - add option to configure lens size

### ISSUE THREAD

**Issue by bluebyte255** [linuxmint/cinnamon#8743]
Requesting an option to configure lens size when lens shape is set to 'square'. There is no GUI for that yet.

btw: is there a cli command or config file option available to change the size manually?

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
