### ISSUE TITLE
Wine application, particularily League of Legends, stealing focus despite that setting being disabled

### ISSUE THREAD

**Issue by MortalGoddess** [linuxmint/cinnamon#8744]
```
 * Cinnamon 4.2.2
 * Manjaro
 * AMD RX580 and Ellesmere Radeon RX open source driver (up to date)
[xsession-errors.zip](https://github.com/linuxmint/cinnamon/files/3444710/xsession-errors.zip)



 * 64 bit
ZIP Attached
 ```

**Issue**
League of legends running in wine steals focus while launching, and will change workspaces if I receive a message.

**Steps to reproduce**
Launch league of legends, start typing on another application, and your mouse focus will be stolen. If you have someone message you, your entire workspace will swap to have the focus stolen by the application.

**Expected behaviour**
A notification to show that I have a message in League, at most. Otherwise nothing.

**Other information**
Wine prefix is running a patched GlibC as well as the AUR package of wine-lol to play after changes made in 9.10 of the game. Information from the prefix available on request.
The settings prevent focus stealing is turned on
The setting for window focus mode is set to click
Bring windows which require attention to the current workspace is turned off.

**Comment by icarter09** [comment]
@MortalGoddess have you tested this out in other desktop environments?

**Comment by MortalGoddess** [comment]
Yeah, the issue persists with XFCE as well. It seems to be a wine/League thing and not just the DE. 

Still rather frustrating

**Comment by icarter09** [comment]
@MortalGoddess I'm going to close this ticket since it seems to not be a Cinnamon-specific issue. Here is a link to open an issue with Wine.

https://bugs.winehq.org/
