### ISSUE TITLE
No theme changes after a PR

### ISSUE THREAD

**Issue by Bundy01** [linuxmint/cinnamon#8747]
```
 * csd version (4.2.2-1)
 * Distribution - (Arch)
 * Graphics hardware *and* driver used
 * 64 bit
 ```

**Issue**

Hi,

I hope I'm in the right place:)
After a PR, the theme changes are not applied on **cinnamon-spices.linuxmint.com**. 

According to one contributor (claudiux, whom I thank), it would be enough to add a question mark at the end of the download URL.

Would it be possible to make this modification to eliminate this problem?

The link of the discussion: https://github.com/linuxmint/cinnamon-spices-themes/issues/580

Thank you.

**Steps to reproduce**

To each PR

**Comment by leigh123linux** [comment]
It looks like this PR addresses the issue.

https://github.com/linuxmint/cinnamon/pull/8746

**Comment by Bundy01** [comment]
Hi,
I thought the problem had been solved because the PR #8746  was closed but it persists. Why not accept it?

**Comment by icarter09** [comment]
@Bundy01 are you still experiencing this issue?

**Comment by Bundy01** [comment]
Hi,

the problem is fixed with the applet "Spices Update" but I haven't done a test since with the manual method in the Cinnamon settings.

**Comment by icarter09** [comment]
@Bundy01 no worries. I'm going to close this issue then since it's been addressed. Thanks for the update.

**Comment by claudiux** [comment]
@icarter09 This issue is not fixed in Cinnamon. The PR #8746 was rejected by @clefebvre. So, I have adapted Spices Update.
