### ISSUE TITLE
Desktop system icons move when restarting computer

### ISSUE THREAD

**Issue by danostg** [linuxmint/cinnamon#8749]
```
 * Cinnamon version (cinnamon --version) 
4.0.10

 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
Mint  19.1

 * Graphics hardware *and* driver used
Intel Corporation 4th Generation Core Processor Family Integrated Graphics Controller
 64 bit


 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
 ```/home/dan/.xsession-errors
/var/log/syslog
[syslog.2.gz](https://github.com/linuxmint/cinnamon/files/3455219/syslog.2.gz)

**Issue**
Desktop system icons move when restarting computer


**Steps to reproduce**
Place icons:  Home, Computer, Trash, etc., wherever you want them, turn off computer, turn on computer, those icons will sometimes stay where they were, and will sometimes be placed in another location. Sometimes ontop or under user application icons.


**Expected behaviour**
icons should be left where I placed them, this is an issue only with  Mint 19.1


**Other information**

**Comment by icarter09** [comment]
We believe this issue is fixed. Please test against the latest Cinnamon version (4.2). 
If the issue happens again, create a new issue and add the output of "cinnamon-settings sound".

**Comment by smurphos** [comment]
@icarter09 you may want to review you copy/paste response to remove the reference to cinnamon-settings sound - ;-)

I haven't been able to reproduce this issue either, but it still comes up regularly as a problem on the Mint forums for 4.2.4 users.

**Comment by icarter09** [comment]
@smurphos :) will do

Thanks for the update as well. Can you send me a link to the where this is being brought up in the forums? I'm not able to reproduce it, but would like to see what everyone is saying in reference to the issue.

**Comment by smurphos** [comment]
Sure - a few examples - https://forums.linuxmint.com/viewtopic.php?f=208&t=305496
https://forums.linuxmint.com/viewtopic.php?f=208&t=305695
https://forums.linuxmint.com/viewtopic.php?f=47&t=293835
