### ISSUE TITLE
mint-upgrade-info: checkbox lags

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/cinnamon#8752]
mint-upgrade-info has no bug tracker so I will file this here.

The 'I understand the risk' checkbox is, somewhat ironically, very laggy on my system. i.e. toggling it on or off takes a few seconds. This does not reassure the user.

I did not see anything that looked relevant in my logs.

mint-upgrade-info v. 1.1.3.

OS: Linux Mint 19.1 Tessa x86_64 
Host: 20KHCTO1WW ThinkPad X1 Carbon 6th 
Kernel: 5.2.5-050205-generic 
Uptime: 1 day, 2 hours, 37 mins 
Packages: 3166 (dpkg), 6 (flatpak), 6 (snap) 
Shell: bash 4.4.20 
Resolution: 2560x1440 @ 60.01Hz 
DE: Cinnamon 4.2.3 
WM: Mutter (Muffin) 
WM Theme: Mint-Y-Dark-trans (Mint-Y-Dark-BB_hack) 
Theme: Mint-Y-Dark [GTK2/3] 
Icons: Paper [GTK2/3] 
Terminal: xfce4-terminal 
Terminal Font: InconsolataGo 12 
CPU: Intel i7-8550U (8) @ 4.000GHz 
GPU: Intel UHD Graphics 620 
Memory: 2591MiB / 15927MiB 
Disk (/dev/nvme0n1p4): 17G / 40G (45%) 
Disk (/dev/nvme0n1p2): 188G / 405G (49%) 
Disk (udev): 0 / 7.8G (0%) 

EDIT: also, one of the package downloads - for `inxi` - failed. Or at least it did initially: it may have succeded at the end of the download process - I could not really tell because the details window closed so slowly.

FURTHER EDIT: and at the end of the process the UpdateManager showed a load of updates that had already - just now - been installed, until I refreshed the window. Also: synaptic (so this may not be your fault) showed a changes window - for a config file - wherein the business part of the window, which shows the changes in the file, was unchangeably tiny, making the window hard to use.

**Comment by icarter09** [comment]
@LinuxOnTheDesktop how often has this occurred to you? I've never noticed any lag on the checkbox.

**Comment by LinuxOnTheDesktop** [comment]
> how often has this occurred to you? I've never noticed any lag on the checkbox.

It happened, so far as I remember, only when I tried to update to Mint 19.2 from Mint 19.1. However, I seem to recall that I had to perform that process at least twice - and each time, I experienced the lag. Note that my computer is HiDPI. (For, that seems to be the cause of some problems.)

**Comment by icarter09** [comment]
@LinuxOnTheDesktop were you able to pinpoint as an HiDPI issue?

**Comment by LinuxOnTheDesktop** [comment]
No, I was not. For, I did not disable HiDPI scaling before I ran the 19.2 - 19.3 updater.

**Comment by LinuxOnTheDesktop** [comment]
The upgrade from 19.2 to 19.3 showed the same problem, but to a reduced extent.

**Comment by JosephMcc** [comment]
Yeah, there is some lag when checking the checkbox but I don't see that being related to Cinnamon in any way.

**Comment by LinuxOnTheDesktop** [comment]
So: if the user experience is to be improved, then a report should be filed either against some other component of Mint or else against something upstream. Which?

**Comment by JosephMcc** [comment]
I don't know the exact cause of the slow selection but it should probably be filed against mintupdate. It certainly isn't an issue with Cinnamon. To be fair though I don't think much time will be spent on it.

**Comment by joakweb** [comment]
I know this is closed but I just wanted to let the team know that this is still happening, to the point I though the checkbox was even disabled and something was wrong with my system, while trying to upgrade to Linux Mint 21.2 Victoria.
