### ISSUE TITLE
19.2 upgrade broke password keyring/online accounts

### ISSUE THREAD

**Issue by lightray22** [linuxmint/cinnamon#8753]
Linux Mint 19.2 (upgraded from 19.1), cinnamon 4.2.3.  Not using the daily PPA.  NVIDIA proprietary driver 430 from http://ppa.launchpad.net/graphics-drivers/ppa/ubuntu.  MX150 on a laptop with Intel graphics.  64 bit.  

Issue is that immediately after the upgrade, my nextcloud bookmark in nemo and all my email accounts in evolution no longer work.  Nemo says invalid credentials.  Evolution says "The reported error was “Failed to authenticate: Failed to obtain an access token for “...”: Failed to retrieve credentials from the keyring”.  The online accounts app says credentials have expired. Removing/adding them again has no effect.  Opening the "passwords and keys" app, the keyring is present and unlocked, and the passwords are there.  I've rebooted several times.

The password manager appears to be seahorse 3.20.0-5, I don't remember if I installed this or if it came with Mint.

**Comment by raybeck95** [comment]
After force reinstalling gnome-keyring and removing dbus-user-session as mentioned in https://askubuntu.com/questions/898694/gnome-keyring-daemon-not-starting-up-properly .... it appears to be working in evolution/online accounts but not nemo. Not sure why.  Maybe this is just a Ubuntu issue?

**Comment by icarter09** [comment]
@lightray22 were you able to resolve your issue?

**Comment by lightray22** [comment]
No changes.  Still does not work in Nemo - it will not open Webdav shares with saved passwords.  Does seem to work fine in evolution after taking the steps mentioned above after the upgrade.

**Comment by icarter09** [comment]
@lightray22 have you tested this against Ubuntu?

**Comment by lightray22** [comment]
Not directly.  I do have one machine that I've upgraded from 18.10 to 19.04 to 19.10 and it also has weird issues with gnome-keying, such as refusing to remember samba passwords.

**Comment by icarter09** [comment]
I've experienced the gnome-keyring a few time before. For me, it was an issue with Chromium and Chrome.

**Comment by lightray22** [comment]
I solved the issue on the Ubuntu install by running the following...

sudo dpkg --purge --force-depends gnome-keyring ubuntu-keyring
rm -Rf ~/.local/share/keyring
sudo apt install gnome-keyring ubuntu-keyring

**Comment by icarter09** [comment]
@lightray22 thanks for the update. Do you feel this ticket can be closed now?

**Comment by lightray22** [comment]
Yes. Probably a Ubuntu issue.
