### ISSUE TITLE
Cinnamon Crashing after upgrade from 19.1 to 19.2

### ISSUE THREAD

**Issue by hasezoey** [linuxmint/cinnamon#8754]
```
 * Cinnamon version (cinnamon --version) 4.2.3
   - using Linux Mint 19.2 default PPA's
 * Distribution - Mint 19.2 (just upgraded)
 * AMDGPU (build in) (2 Display)
 * 64 bit
 * [.xsession-errors](https://gist.github.com/hasezoey/ccd354fdc9e8529d3fef49d6a2b088bf)
 ```

**Issue**

Cinnamon is crashing after lightdm login & after "do you want to restart cinnamon"

**Steps to reproduce**

(upgraded from 19.1 to 19.2), it just crashes, i havnt done anything since the update

EDIT: now i have done:
- installed kernel 5.0.0-23 & -20 from mintupdate
- rebooted into -23
- removed 5.0.21 kernel that was installed from ukuu
- got and update for the kernel, updated it
- restarted system multiple times
-> still same error

**Expected behaviour**

Work without Crashes

**Other information**

Kernel 5.0.21
`uname -a` `Linux Meicoo-Linux 5.0.0-23-generic #24~18.04.1-Ubuntu SMP Mon Jul 29 16:12:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

PS: if someone has a better name for this issue, please change it

**Comment by leigh123linux** [comment]
Sorry there is nothing to do within cinnamon that will fix the crappy radeon driver, try reporting it to ubuntu kernel or mesa.

```
cinnamon: ../src/gallium/drivers/radeonsi/si_state_viewport.c:239: si_emit_guardband: Zusicherung »left <= -1 && top <= -1 && right >= 1 && bottom >= 1« nicht erfüllt.
```

**Comment by hasezoey** [comment]
@leigh123linux i think i have the new amdgpu driver installed & using it, not the old radeon driver, or am i missing something?

lsmod:
```
Module                  Size  Used by
xt_CHECKSUM            16384  1
ipt_MASQUERADE         20480  3
devlink                65536  0
xt_tcpudp              20480  15
ip6t_rpfilter          16384  1
ip6t_REJECT            16384  2
nf_reject_ipv6         20480  1 ip6t_REJECT
ipt_REJECT             16384  4
nf_reject_ipv4         16384  1 ipt_REJECT
xt_conntrack           16384  18
aufs                  249856  0
ebtable_nat            16384  1
ebtable_broute         16384  1
bridge                167936  1 ebtable_broute
stp                    16384  1 bridge
llc                    16384  2 bridge,stp
ip6table_nat           16384  1
nf_nat_ipv6            16384  1 ip6table_nat
overlay               110592  0
ip6table_mangle        16384  1
ip6table_raw           16384  1
ip6table_security      16384  1
iptable_nat            16384  1
nf_nat_ipv4            16384  2 ipt_MASQUERADE,iptable_nat
nf_nat                 36864  2 nf_nat_ipv6,nf_nat_ipv4
nf_conntrack          135168  5 xt_conntrack,nf_nat,nf_nat_ipv6,ipt_MASQUERADE,nf_nat_ipv4
nf_defrag_ipv6         24576  1 nf_conntrack
nf_defrag_ipv4         16384  1 nf_conntrack
iptable_mangle         16384  1
iptable_raw            16384  1
iptable_security       16384  1
ebtable_filter         16384  1
ebtables               36864  3 ebtable_nat,ebtable_filter,ebtable_broute
ip6table_filter        16384  1
ip6_tables             32768  6 ip6table_filter,ip6table_raw,ip6table_nat,ip6table_mangle,ip6table_security
iptable_filter         16384  1
bpfilter               24576  0
intel_rapl             24576  0
x86_pkg_temp_thermal    20480  0
intel_powerclamp       20480  0
coretemp               20480  0
kvm_intel             237568  0
nls_iso8859_1          16384  1
kvm                   626688  1 kvm_intel
8250_dw                20480  0
crct10dif_pclmul       16384  1
crc32_pclmul           16384  0
ghash_clmulni_intel    16384  0
snd_hda_codec_realtek   114688  1
snd_hda_codec_generic    77824  1 snd_hda_codec_realtek
ledtrig_audio          16384  2 snd_hda_codec_generic,snd_hda_codec_realtek
snd_hda_codec_hdmi     53248  2
snd_hda_intel          40960  5
snd_hda_codec         131072  4 snd_hda_codec_generic,snd_hda_codec_hdmi,snd_hda_intel,snd_hda_codec_realtek
aesni_intel           372736  0
snd_usb_audio         233472  2
snd_hda_core           86016  5 snd_hda_codec_generic,snd_hda_codec_hdmi,snd_hda_intel,snd_hda_codec,snd_hda_codec_realtek
snd_usbmidi_lib        36864  1 snd_usb_audio
snd_seq_midi           20480  0
snd_hwdep              20480  2 snd_usb_audio,snd_hda_codec
aes_x86_64             20480  1 aesni_intel
joydev                 28672  0
snd_seq_midi_event     16384  1 snd_seq_midi
crypto_simd            16384  1 aesni_intel
cryptd                 24576  3 crypto_simd,ghash_clmulni_intel,aesni_intel
snd_rawmidi            36864  2 snd_seq_midi,snd_usbmidi_lib
glue_helper            16384  1 aesni_intel
intel_cstate           20480  0
snd_seq                69632  2 snd_seq_midi,snd_seq_midi_event
snd_pcm               102400  5 snd_hda_codec_hdmi,snd_hda_intel,snd_usb_audio,snd_hda_codec,snd_hda_core
intel_rapl_perf        16384  0
snd_seq_device         16384  3 snd_seq,snd_seq_midi,snd_rawmidi
input_leds             16384  0
snd_timer              36864  2 snd_seq,snd_pcm
idma64                 20480  0
virt_dma               20480  1 idma64
snd                    86016  27 snd_hda_codec_generic,snd_seq,snd_seq_device,snd_hda_codec_hdmi,snd_hwdep,snd_hda_intel,snd_usb_audio,snd_usbmidi_lib,snd_hda_codec,snd_hda_codec_realtek,snd_timer,snd_pcm,snd_rawmidi
mei_me                 40960  0
intel_lpss_pci         20480  0
intel_wmi_thunderbolt    20480  0
soundcore              16384  1 snd
intel_pch_thermal      16384  0
mei                   102400  1 mei_me
intel_lpss             16384  1 intel_lpss_pci
mac_hid                16384  0
sch_fq_codel           20480  3
acpi_pad              184320  0
parport_pc             36864  1
ppdev                  24576  0
lp                     20480  0
parport                53248  3 parport_pc,lp,ppdev
ip_tables              32768  5 iptable_filter,iptable_security,iptable_raw,iptable_nat,iptable_mangle
x_tables               40960  18 ebtables,ip6table_filter,xt_conntrack,ip6table_raw,iptable_filter,iptable_security,ip6t_rpfilter,xt_tcpudp,ipt_MASQUERADE,xt_CHECKSUM,ip6_tables,ipt_REJECT,iptable_raw,ip_tables,ip6table_mangle,ip6table_security,ip6t_REJECT,iptable_mangle
autofs4                45056  2
btrfs                1167360  2
xor                    24576  1 btrfs
zstd_compress         163840  1 btrfs
raid6_pq              114688  1 btrfs
libcrc32c              16384  3 nf_conntrack,nf_nat,btrfs
dm_mirror              24576  0
dm_region_hash         20480  1 dm_mirror
dm_log                 20480  2 dm_region_hash,dm_mirror
vfio_pci               49152  0
irqbypass              16384  2 vfio_pci,kvm
vfio_virqfd            16384  1 vfio_pci
vfio_iommu_type1       28672  0
vfio                   32768  2 vfio_iommu_type1,vfio_pci
hid_generic            16384  0
usbhid                 53248  0
hid                   126976  2 usbhid,hid_generic
amdgpu               3497984  13
chash                  16384  1 amdgpu
mxm_wmi                16384  0
amd_iommu_v2           20480  1 amdgpu
gpu_sched              32768  1 amdgpu
i2c_algo_bit           16384  1 amdgpu
ttm                   102400  1 amdgpu
drm_kms_helper        180224  1 amdgpu
syscopyarea            16384  1 drm_kms_helper
sysfillrect            16384  1 drm_kms_helper
sysimgblt              16384  1 drm_kms_helper
fb_sys_fops            16384  1 drm_kms_helper
r8168                 524288  0
drm                   479232  8 gpu_sched,drm_kms_helper,amdgpu,ttm
ahci                   40960  4
libahci                32768  1 ahci
wmi                    28672  2 intel_wmi_thunderbolt,mxm_wmi
pinctrl_sunrisepoint    28672  0
video                  49152  0
pinctrl_intel          28672  1 pinctrl_sunrisepoint
```

**Comment by hasezoey** [comment]
Note:
i reinstalled Linux Mint 19.2, still having the issue
but i noticed switching VSync-Method from "Presentation Time" to "-" or backwards, fixes it, but is annoying and not always working ...

**Comment by Jusix** [comment]
This is an serious issue, I just suffered from the same problem. I don't get why the issue is closed. CInnamon doesn't work with the best open source graphic driver available at the moment and the devs don't even care?

**Comment by hasezoey** [comment]
i dont know what happened but:
i dont know what i have done since my last update, only that i have disabled Privacy->Show Recent accessed documents
and after 1 or 2 reboots later, it didnt crash anymore...

**Comment by Jusix** [comment]
For me removing xserver-xorg-hwe-18.04 fixed it. But Mint 19.1 runned flawless with HWE stack.

**Comment by hasezoey** [comment]
> For me removing xserver-xorg-hwe-18.04 fixed it.

i dont have/had this installed

**Comment by Jusix** [comment]
Sadly the problem returned today and installing xserver-xorg-hwe-18.04 fixed it, so it doesn't seem to be the problem but reinstalling xorg components seems to fix it temporarily.

**Comment by ttshaw1** [comment]
I also have this problem, Linux Mint 19.2 Cinnamon, tried a few different kernels. You guys probably already know this but selecting software rendering at the login screen keeps from having to use fallback desktop mode. 

Any idea whether this is a driver issue that will affect other applications or an issue solely with Cinnamon?

**Comment by leigh123linux** [comment]
@ttshaw1 Cinnamon 3D needs a fully functional driver to function, if the driver crashes or misbehave cinnamon will crash.
I would expect and 3D accelerated apps to do the same (firefox with  gpu acceleration).

**Comment by hasezoey** [comment]
> Any idea whether this is a driver issue that will affect other applications or an issue solely with Cinnamon?

at least for me, in fallback mode, vivaldi(browser), discord, steam & virt manager just worked normal, but cinnamon was in fallbackmode so it didnt have all the functionality (but these programs just worked fine)

**Comment by ttshaw1** [comment]
@leigh123linux In Cinnamon software rendering mode, I've tried both FreeCAD and KiCAD's PCBNew with OpenGL canvas. Both are working fine, no issues at all with the graphics driver. Does setting Cinnamon to software rendering somehow force software rendering for other applications? If not it really seems like the problem is isolated to Cinnamon.

**Comment by ttshaw1** [comment]
Good news. I was able to get a much better understanding of the problem. I have a dual monitor setup. Cinnamon is crashing when the secondary one is moved to a certain amount left of the primary one. The cutoff is somewhere around where the monitors are positioned in the image, though the secondary can be above or below the primary. If the secondary is to the right of a certain vertical line, cinnamon works fine. To the left, it crashes every time. I tried switching which of my monitors was the primary and the behavior is the same.
@hasezoey @Jusix can you confirm?
@leigh123linux This points strongly towards a Cinnamon issue in my mind. Would you please consider reopening the issue?
![image](https://user-images.githubusercontent.com/40922470/62837437-56650a00-bc3d-11e9-9588-5b44095b5afd.png)

**Comment by hasezoey** [comment]
@ttshaw1 cant confirm because i have my second montior always on the left (both aligned to bottom)
![Bildschirmfoto vom 2019-08-11 19-43-11](https://user-images.githubusercontent.com/10911626/62837486-4adf0680-bc70-11e9-85cc-bc23a6b73302.png)

and like i said in https://github.com/linuxmint/cinnamon/issues/8754#issuecomment-518319997, i dont have a crash anymore... (still using the *exactly* same system (note: i have 2 GPU's, AMD vega 64, which is my main, and Nvidia GTX 1080, disabled and only used in Windows VM))

**Comment by ottomated** [comment]
@ttshaw1 I seem to be able to replicate your issue exactly. Having my second monitor to the left causes the same crash: `cinnamon: ../src/gallium/drivers/radeonsi/si_state_viewport.c:239: si_emit_guardband: Assertion `left <= -1 && top <= -1 && right >= 1 && bottom >= 1' failed.`

However, it seems like this crash only appears on cinnamon's launch: if I rearrange my monitors normally after that, it works fine: 
![Screenshot](https://user-images.githubusercontent.com/31470743/62838042-c074b380-bc2b-11e9-9205-b20756f8cb3c.png)

**Comment by ttshaw1** [comment]
@ottomated Yeah, it seems like Cinnamon crashes only when it's **started** with a bad monitor placement, whether it's starting on boot or restarted manually later on.

I've been playing around with these steps and the problem is totally repeatable.
1. Put your secondary monitor far right and restart so Cinnamon works on boot
2. Move the secondary far left into a position where you'd expect a Cinnamon crash
3. Run `cinnamon --replace` in the terminal

Result: Cinnamon crashes with the same error `cinnamon: ../src/gallium/drivers/radeonsi/si_state_viewport.c:239: si_emit_guardband: Assertion left <= -1 && top <= -1 && right >= 1 && bottom >= 1' failed.`

Doing the opposite, with the secondary far left on boot, moving it right, and starting Cinnamon results in a perfectly fine DE.

**Comment by leigh123linux** [comment]
@ttshaw1 sorry I disagree, it's more likely to be mesa/driver

https://bugs.launchpad.net/ubuntu/+source/gnome-shell/+bug/1837087

**Comment by Jusix** [comment]
@leigh123linux But mesa doesn't got updated with Mint 19.1 -> 19.2, so why does this issue only occurs on 19.2?

**Comment by Colanderr** [comment]
I ran into this issue even on a 19.2 fresh install, but I migrated my home folder from my old machine (19.1), could this be a problem with some kind of a config file from the 19.1 installation?

**Comment by KuJo-Ger** [comment]
I have the same problem after upgrading from Linux Mint Cinnamon 19.1 to 19.2. Every time I restart the system the Cinnamon Desktop crashed.

Curious: I often clicked "Restart" in the crash dialog. Cinnamon crashed again and again. But sometime after 10, 15 or 20 restarts Cinnamon started.

However, this is of course not a solution. So I tried different kernels, uninstalled the Padoka stable PPA for Mesa and tried different things that could have caused it. Without success.

I also connected a second monitor. It is (so far) located on the left side of my main monitor and has been configured accordingly in the system settings. After I found this entry here I simply disconnected my 2nd monitor (pulled the monitor cable out of the monitor). And since then there is no crash at system start anymore!

Of course this is not a permanent solution either. But since I don't need my second monitor so urgently, I can live with this workaround for now. In the long run, however, I would like to put the monitor back into operation.

**Comment by ttshaw1** [comment]
Problem is persisting with Mesa 19.0.8-0ubuntu0~18.04.1. I also put in a bug report with Mesa [here](https://bugs.freedesktop.org/show_bug.cgi?id=111372). Feel free to add to it.

**Comment by DocSchwarz** [comment]
19.0.8 seems to have fixed the problem for me. Keeping my fingers crossed tho.

**Comment by KuJo-Ger** [comment]
Additional info to my contribution above ( https://github.com/linuxmint/cinnamon/issues/8754#issuecomment-520860691 ):

I have currently installed MESA 19.1.2 via the Padoka Stable PPA and with this the error occurs.

**Comment by leigh123linux** [comment]
https://github.com/linuxmint/cinnamon/issues/8710
