### ISSUE TITLE
19.2 workspace-switcher does not display visual window indicators on small panels

### ISSUE THREAD

**Issue by Nebelkind** [linuxmint/cinnamon#8755]
```
  Cinnamon version  4.2.3
  Distribution Mint 19.2
  64 bit
  ```

**Issue**
As of the 19.2 update the cinnamon workspace-switcher in the panel  does not show visual representations of the opened windows anymore if the panel size is lower then 26px but displays the only the number of the workspace instead (removing and re-adding the applet results in a "something went wrong" warning in these situations) 

**Steps to reproduce**
**S**et panel height to somewhere between 20px-25px,
**C**onfigure workspace switcher to show visual window representations,
**L**ook at the workspace-switcher applet on the panel
**R**emove and afterwards add the applet to the panel to see the warning

**Expected behaviour**
One would expect the visual window representations to work down to the smalest offered Panel size of 20px (like in 19.1 and before)

**Comment by brownsr** [comment]
It's by design in a recent change, so not a fault.  It cuts over to numbers when the graph shown is judged too small to be useful.  However I can see you might find the cutover point a little early, so I will experiment to see if a change would help.

Regards

Simon

**Comment by Nebelkind** [comment]
Thanks for looking into it. Had been using it on 23px panel height for quite some time and never felt it lacking. Main usefulness for me always was that it reminds me I have windows open on this or that workspace with a single glance and the numbers unfortunately do not help there.

**Comment by gerard87** [comment]
Same here, i'm using size 24 with a 1680x1050 resolution monitor and visual representation is perfectly functional and useful. Now it force me to choose between increase the size to 26 or loose the feaure. So, +1 to see the feature come back again, thanks.

**Comment by radiolabworks** [comment]
+1 here too.  I updated four systems to 19.2 and lost the visual on three of them.  Some were at 25 and needed to be set to 26 after reading this.  A note would have been most useful on the configure window for the switcher that indicates a size 26 or greater is required to allow displaying of the visual representations in the Panel Configuration. I would opt for returning it back as my original setting were useful at 25 for sure.
