### ISSUE TITLE
[Feature Request] Static sort order for Alt + Tab, Show windows

### ISSUE THREAD

**Issue by Adrian-Bielefeldt** [linuxmint/cinnamon#8758]
Currently, when pressing Alt + Tab, the windows are shown ordered by most recently used. I would like an option to disable this and simply order them by how they appear on the task bar.

Same goes for the order when using the Show Windows feature.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
