### ISSUE TITLE
Desktop icons rearange on cinnamon restart

### ISSUE THREAD

**Issue by TrickMe** [linuxmint/cinnamon#8762]
Cinnamon 4.2.3+tina
Mint 19.2
64 bit

**Issue**
Desktop Icons rearrange after cinnamon restart, if grid spacing is reduced too much.

**Steps to reproduce**
Right click on cinnamon desktop --> Customize
Drag the slider on the bottom of the window a little to the left (about 10 steps).
Switch some of the desktop icons on the top left-hand side of the desktop.
Log off and log in again.
The icons will be switched back to their original location.

**Comment by icarter09** [comment]
Linux Mint 19.2
Cinnamon 4.2.4

I was not able to reproduce this issue.

**Comment by icarter09** [comment]
We believe this issue is fixed. Please test against the latest Cinnamon version (4.2). 
If the issue happens again, create a new issue and add the output of "cinnamon-settings sound".
