### ISSUE TITLE
Feature: Separate screensaver (lock screen) timer for A/C and Battery power

### ISSUE THREAD

**Issue by TrickMe** [linuxmint/cinnamon#8763]
Cinnamon 4.2.3+tina
Mint 19.2
64 bit

**Expected behaviour**
Like in Power Management, I would like to set different delays for locking my Notebook on Battery Power and A/C.
Also please consider putting a separate lock screen timer to Power management, since auto-locking the screen when leaving, with separate timers for A/C and battery, somehow fall in the same "what does my notebook do, when I'm leaving it for a few minutes?" category.

A checkbox for every event (screensaver, turn off screen, suspend/sleep) to lock the computer on event separately would be nice.

**Other information**
Please consistently unify "sleep", "suspend" (to RAM or to Disk?) or maybe even use "hibernate" for more clarity.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
