### ISSUE TITLE
Black Screen After Login

### ISSUE THREAD

**Issue by bonej079** [linuxmint/cinnamon#8764]
```
 * Cinnamon version 4.2.3
 * Linux Mint 19.2
 * Nvidia Driver  430
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
 ```

**Issue**

After login, Cinnamon presents a black screen.

**Steps to reproduce**

After inputting username and password at login screen, you are presented with a black screen. Mouse is still visible and can be moved around. This happened *after upgrading to Linux Mint 19.2. 

Installed Mate and logged into Mate with no issues.

**Expected behaviour**

Show the Cinnamon Desktop with menu, etc.

**Other information**

[xsession-errors.txt](https://github.com/linuxmint/cinnamon/files/3467072/xsession-errors.txt)

**Comment by leigh123linux** [comment]
Provide xsession-errors for cinnamon login, the log provided is useless as it's for Mate.

**Comment by bonej079** [comment]
Sorry about that.

[xsession-errors.txt](https://github.com/linuxmint/cinnamon/files/3467125/xsession-errors.txt)

**Comment by leigh123linux** [comment]
Try removing these applets

bbcwx@oak-wood.co.uk
diskspace@schorschii
and skype1
[LookingGlass/info] Adding indicator: Skype1

**Comment by bonej079** [comment]
I uninstalled Skype. I removed the folders for bbcwx and diskspace from ~/.cinnamon and ~/.local/share/cinnamon/desklets but the problem is still there :(

I am attaching the new xsession-errors.

[xsession-errors.txt](https://github.com/linuxmint/cinnamon/files/3467277/xsession-errors.txt)

**Comment by leigh123linux** [comment]
Can you post /var/log/Xorg.0.log please?

**Comment by bonej079** [comment]
Sure. Attached.

[Xorg.0.log](https://github.com/linuxmint/cinnamon/files/3467435/Xorg.0.log)

**Comment by leigh123linux** [comment]
The xorg log looks ok

**Comment by claudiux** [comment]
@bonej079 Maybe trying to rename the `~/.config/gtk-3.0/gtk.css` file, if it exists:
`mv ~/.config/gtk-3.0/gtk.css ~/.config/gtk-3.0/gtk.css_OLD`
Then, log off and log on you.

Idem with the directory `~/.local/share/gnome-shell`, if it exists.

**Comment by bonej079** [comment]
@claudiux None of them exist - neither gtk.css nor gnome-shell

**Comment by bonej079** [comment]
I had another look at the xsession-errors file. I noticed that it seems that there is an infinite loop in Cinnamon. The following line is repeated endlessly.

(cinnamon:4067): Clutter-WARNING **: 13:06:38.176: clutter-actor.c:10055: Actor 'StBoxLayout' tried to allocate a size of -20.00 x 0.00

Hope this helps in debugging.

**Comment by bonej079** [comment]
Ok. Solved the culprit. Removed all custom extensions (bbcwx, collapsible-systray, diskspace, googleCalendar and soundBox). Restarted. And it worked. 

Latest xsession-errors:

[xsession-errors.txt](https://github.com/linuxmint/cinnamon/files/3476063/xsession-errors.txt)

Thanks for the help.
