### ISSUE TITLE
Dropbox daemon download during upgrade from 19.1 to 19.2

### ISSUE THREAD

**Issue by alextakitani** [linuxmint/cinnamon#8766]
``` 
 * Cinnamon 4.2.3
 * Mint 19.2
 * Radeon 5770 / AMD JUNIPER
 * 64 bit
 ```

**Issue**

During upgrade from Mint 19.1 to 19.2, having Dropbox installed, the installer
asks to download the Dropbox daemon.
If you don't go to details and answer the prompt the installer will "hang" waiting.

![Screenshot from 2019-08-05 07-54-08](https://user-images.githubusercontent.com/105376/62465983-9c662d80-b766-11e9-8780-dcd7752293b0.png)

**Steps to reproduce**

Install 19.1, install dropbox, upgrade to 19.2

**Expected behavior**

It should answer yes automatically or advise the user before.

**Other information**

**Comment by leigh123linux** [comment]
Please file the issue against mintupdate.

https://github.com/linuxmint/mintupdate/issues
