### ISSUE TITLE
Feature request/suggestion: touchpad gestures to switch workspace

### ISSUE THREAD

**Issue by Rysher** [linuxmint/cinnamon#8767]
```
 * Cinnamon version 4.2.3
   - Please specify if you are using the daily builds PPA (https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds): NO.
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Linux Mint 19.2
 * Graphics hardware *and* driver used nVidia 1070ti propriatery 430.40 driver from nVidia graphics ppa
 * 64 bit
 ```

**Issue**
This is a feature request, not an issue: I would very much like to see the ability to control workspace switching using touchpad gestures such as 3 fingers swipe left -> switch to left workspace.
3 finges swipe right -> switch to right workspace
3 fingers up -> workspace overview
3 fingers down -> open windows overview

basically emulate a 3 finger swipe as a Ctrl+alt press and the direction of the swipe should be translated to the arrow key.
Or to make it short - create a touchpad experience parity with Apple Mac OS X, which was actually the ONLY good thing about macbooks and OS X that Linux Mint doesn't have

**Comment by smurphos** [comment]
As long as your touchpad can provide the system with a unique button code for a three fingered gesture you could achieve this easily using a combination of xbindkeys and xdotool.

My doesn't - 2 fingers up / down give the same button code as my mouse wheel (testing with the application xev) - no output at all from a three fingered gesture. 

You might find this useful - it's a small script that allows mousewheel / 2 finger touchpad scrolling to switch workspaces, but only when the pointer is on the desktop. It uses the aforementioned tools. 

https://forums.linuxmint.com/viewtopic.php?p=1518233#p1518233

**Comment by Rysher** [comment]
@smurphos never heard of those but I believe I could easily learn everything needed to follow your advice, thanks!
However, Mint's banner has ease-of-use-by-point-and-click written all over it, specially for novice users and linux-newcommers, if you tell this to these people they'll be heading streight back to Windows or Mac. bear that in mind.

**Comment by brownsr** [comment]
It's potentially possible @Rysher but probably a lot more work than you might imagine.  I've been musing on whether to plunge into some touch enabling work, so will bear it in mind.

Regards

Simon

**Comment by Rysher** [comment]
@brownsr I'm a web developer, though an entirely different field, I am still aware of the large pile of coding and research ahead for the developer that will pick up the task, you will definately have my appreciation in advance for even considering starting this project, and of thousands of people like me.

For what it's worth - you definately SHOULD plunge into touch-enabling work ;)

**Comment by smurphos** [comment]
@Rysher - came across this earlier. Not tried it myself but looks promising - https://github.com/bulletmark/libinput-gestures

**Comment by icarter09** [comment]
@Rysher did the github gestures that @smurphos suggested help?

**Comment by Rysher** [comment]
@icarter09 I wish I could tell you. Unfortunately even though Linux Mint has warm place in my heart I switched to Pop! OS on all of my machines not long after smurphos posted his suggestion.
I did went over that repo he linked, never got around to trying it.
Even if it did work - for anyone who's even just a bit less tech-savvy than me it would be way too complex to do, to a point of just letting it go. So at best this is just a step in the right direction (assuming it works).

**Comment by icarter09** [comment]
@Rysher no worries and thanks for the update. 

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.

**Comment by Rysher** [comment]
Hello again @icarter09 
I've recently returned to Linux Mint (Cinnamon, 19.2, 64 bit), and since this issue has never escaped my memory I decided to give it a go. It works perfectly fine, with negligable effect on resource utilization (which was my biggest concern). I would highly suggest (if it fits with the LM dev team's roadmap) that this would be the base of your work to enable this natively out of the box for Linux Mint 20.04...since I imagin that for 19.3 it's already too late.

If this interests you. I will also add a little feedback - as lovable as the ability to switch workspaces in a Linux DE of any kind just like the famous macbook touchpad experience - it is still far less snappy than what a new-comming mac user would expect...or even those poor MS Windows survivors that escaped to the safe lands of Linux Mint.
Moreover, a GUI tool to tweak its settings (I've had to edit the .conf file) is a must have for non tech-savvy users since this is aimed mainly at Gnome which alligns its workspaces vertically as opposed to Cinnamon's horizontal allignment, If I may suggest - These tweakable options should be added to the touchpad settings menu in Cinnamon.
I've never used Mate or XFCE desktops so I have no insight regarding those DE's.

I truely hope you'd find this review and insight useful in your development.
If you wish to contact me regarding this (or any oher non-related desired feedback on Cinnamon) feel free to contact me.

**Comment by dominik59** [comment]
For those who want to have nice out-of-the-box gestures i advice to install https://github.com/Hikari9/comfortable-swipe . It's a program which works very smoothly and allows to switch between workspaces without any lag. It's a shame that it can't be built in Cinnamon as default :/

**Comment by Rysher** [comment]
@dominik59 
completely un-necessary as libinput-gestures does the job flawlessly and is almost completely distro-agnostic, the installation is prety much the same, and relies on similar dependencies.
PLUS - ubuntu is a shit-distro when it comes to desktop.

**Comment by McNugget6750** [comment]
> For those who want to have nice out-of-the-box gestures i advice to install https://github.com/Hikari9/comfortable-swipe . It's a program which works very smoothly and allows to switch between workspaces without any lag. It's a shame that it can't be built in Cinnamon as default :/

Works like a charm on Ubuntu 21.10 running Cinnamon-Desktop! Thank you for the tip!
libinput-gestures doesn't exist in my apt-get library.
