### ISSUE TITLE
Idea / Feature Request - Cinnamon Desktop Themes Font Scaling

### ISSUE THREAD

**Issue by smurphos** [linuxmint/cinnamon#8772]
Noting that 'text-size to be configurable in panel zones?' is still on the Roadmap but not highlighted for Cinnamon 4.4 / Mint 19.3, and having recently upgraded from a laptop with a 1366 x 768 15.6" display to a laptop with a 1920 x 1080 15.6" display I've got the following suggestion.

**Issues**

Hardcoded font sizes in the Cinnamon theme in general makes it difficult to create themes that are usable on all sub HIDPI combinations of resolution/display size.. Current end-user workarounds by setting general font sizes a bit smaller than comfortable and then using Text Scaling to increase the font-size globally  are not very intuitive to newer (and some not so new) users.

The most common complaint is that panel font sizes in particular are not re-sizeable, but people complain about other UI elements controlled by the Desktop theme as-well on high resolution small physical dimension screens.

**Proposed Solution**

- Amend the theme parser to allow for a local cinnamon-override.css file that would work in a similar way to how `~/.config/gtk-3.0/gtk.css` works

- Amend all the Mint shipped themes to use scale-able font-size (em or percentage) declarations throughout the Cinnamon theme except in stage {} which would have a pt definition. There would likely be some other tweaks needed to some padding and margin declarations to use scalable units - the calendar in particular can be a bit tricky.

- Encourage third party theme contributors to do the same

- Add to the Font Selection GUI a switch to override the Cinnamon theme and then chose a Font Family and base Font Size for the Cinnamon Desktop theme. These settings would be written to the proposed cinnamon-override.css file as css in stage {}.

- Add to the Panel GUI a switch to a switch to override the Cinnamon theme and then choose a font size for the active panel. These would also be written to the proposed cinnamon-override.css as css in  panel-top {}, panel-bottom {} etc as a hard-coded font-size overriding the themes scale-able fonts.

**Comment by JosephMcc** [comment]
Maybe the most practical solution here would be using em in the themes themselves. I know that you've worked with themes enough to know that if we had configurable font sizes (a lot of work to implement) that it would probably lead to some weird things happening. Like the calendar applet you mentioned.

**Comment by JosephMcc** [comment]
Whoops, hit the wrong button :)

**Comment by smurphos** [comment]
@JosephMcc - maybe you can enlighten me to something I've not been able to figure out. If I load a theme where all font-sizes are declared in em what is em actually scaling against?

E.g in the absence of any font declaration in stage{} or a font-size=1em set in stage cinnamon seems to default to 1em=10pt at the default text scaling factor.  If you set font-size=12pt in stage, then the rest of theme scales at 1em=12pt

Where does the default 1em=10pt come from and is is something that could be made an end-user accessible setting?

**Comment by smurphos** [comment]
Something else that I don't quite get is that if I set font-sizes in px they are scaled up by 1.3333 when they are displayed. This seems to be irrespective of display resolution. I'm trying to figure out what's going on in https://github.com/linuxmint/cinnamon/blob/master/src/st/st-theme-node.c now ;-)

**Comment by smurphos** [comment]
And I've just come across this for Gnome Shell, which If I read right will facilitate  end-user settings for Gnome Shell font family if not font-size - https://gitlab.gnome.org/GNOME/gnome-shell/merge_requests/486/commits?commit_id=f28f041a95dca2709ee43bdaa4762487588e3246

I guess that also answers my question as to where the defaut 10pt comes from - probably - https://github.com/linuxmint/cinnamon/blob/master/src/st/st-theme-context.c#L45

**Comment by JosephMcc** [comment]
https://github.com/linuxmint/cinnamon/pull/9057

In testing this works quite well and just follows the default font set in the settings. It can still be overridden by your cinnamon themes css. So current themes will work just like now until the current hard coded fonts are removed. This will allow all sizing in the theme to be done by em so they stay relative to the user selected size.

**Comment by smurphos** [comment]
Thanks for looking at this Joseph. This sounds like an ideal way forward. I'll figure out how to set up a testing environment to test your branch in the next few days and have a play around.

**Comment by smurphos** [comment]
Closed by #9057 ;-)
