### ISSUE TITLE
Touchpad tap-to-click doesn't work after some time

### ISSUE THREAD

**Issue by bgemmill** [linuxmint/cinnamon#8776]
```
 * Cinnamon version (cinnamon --version)
Cinnamon 4.2.3
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
Mint 19.2
 * Graphics hardware *and* driver used
Intel Iris Graphics 540, Skylake chip
KMS and i915
 * 32 or 64 bit
64 bit
 ```

**Issue**

On a Dell XPS 13 9350, with Kernel 5.0.0-23-generic, when tap-to-click is enabled in cinnamon, after a few hours of use tap-to-click will cease to work.

If I go into cinnamon's touchpad preferences in this state (without changing anything), the tap-to-click option will still appear enabled and will work again for a few hours until this step needs repeating.

**Steps to reproduce**

Enable touchpad tap-to-click, and use the computer for a few hours.

**Expected behaviour**

Tap-to-click continues working throughout the user session.

**Other information**

I have not noticed this effect in 4.18.0-25-generic, which means it may not be a cinnamon issue, but I'm interested in what cinnamon does when that option is toggled so I can dig more into this.

**Comment by leigh123linux** [comment]
Report the issue against 5.0.0-23-generic at ubuntu launchpad

**Comment by bgemmill** [comment]
@leigh123linux Can you please point me to what cinnamon does when that option is toggled so I can give more color when reporting there?

**Comment by bgemmill** [comment]
Reported on launchpad here:
https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1839327

**Comment by leigh123linux** [comment]
It toggles a gsetting for cinnamon-settings-daemon

https://github.com/linuxmint/cinnamon/blob/master/files/usr/share/cinnamon/cinnamon-settings/modules/cs_mouse.py#L94

cinnamon-settings-daemon can use either libinput or xorg synaptics 

https://github.com/linuxmint/cinnamon-settings-daemon/blob/master/plugins/mouse/csd-mouse-manager.c#L69
