### ISSUE TITLE
[Feature request]: window switching per screen tile

### ISSUE THREAD

**Issue by Axelderan** [linuxmint/cinnamon#8791]
Hi,

I use Cinnamon's tiling functionality very often.  I find it's the perfect balance of stacking and tiling WMs.

I like how alt-tab cycles through all windows in a workspace in recently-used order.  This allows me to juggle between window focus nicely as I move back and forth between two applications.

One of the nice bits of workflow that Cinnamon supports is keeping two windows open side by side, each taking half the screen.  (more generally, it supports quarter-tiling the screen, but that's not a terribly important detail)

Fairly often, I'll have one side of the screen have something like a PDF programming book open, and the other a terminal where I'm coding along with the exercises.  Then, I'll want more detail from the official docs for the language/library and I'll open Firefox.  The natural place to put Firefox is where the book is.  I'll switch between the terminal, the book, and the browser at various times.

Workspaces are fantastic, and I'll rarely end up with even 6 windows open in a single workspace.  But occasionally I find it would be convenient to have a function analogous to alt-tab, but which works on a per-tile basis.  So given the example above, I could switch between all windows on the left side, without having to remember where things are in the full alt-tab stack.

This is admittedly a minor piece of ergonomics, but I think it fits in naturally with the rest of the feature-set of Cinnamon.  It even has the perfect key combinations unreserved:
  `super`+`tab`:  switch windows within current tile
  `super`+`shift`+`tab`: switch windows within the current tile in reverse

This is the perfect key combination because it takes part of the `alt`-`tab` key combination, which is for a related tabbing feature, and it takes part of the `super`+`arrow` functionality, which is relatedly for window tiling.  Plus it's short and easy.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
