### ISSUE TITLE
Linux Crash - Mint 18.3 - Stable Version - All Updates Applied - Konqueror 4.14.16

### ISSUE THREAD

**Issue by distantlightning** [linuxmint/cinnamon#8792]
While experimenting with File Managers I was attempting to open a newly installed instance of Konqueror (Version 4.14.16 - from the software manager repository.) It, of course opens in a Web Browser format. Clicking "Home Folder" from the opening page (not restoring the previous session) presented an error: "There appears to be a configuration error. You have associated Konqueror with inode/directory, but it cannot handle this file type." As I have not used Konqueror in a while, I was searching the web for instructions on how to open it in File Manager mode and also to work around the above issue. I found the following command:

kfmclient openProfile filemanagement

Running this command in the terminal opened Konqueror in the file manager mode. 

Now the interesting part. I clicked the small home icon to the left side of the main Konqueror window. See the attached JPG of this window:

![Konqueror Window](https://user-images.githubusercontent.com/53980478/62826233-e8a9d700-bb85-11e9-9916-bcdb5750ee06.jpeg)

Konqueror started spawning new windows in machine gun style, all over the screen and Mint crashed almost immediately, prompting me to run in the fallback once or restart. It would not restart. So, I had to shut the system down by power off.

I thought this might be a fluke. So, I restarted everything, followed the above steps clicking the same home icon. That seemed to work. So, I clicked the bookmark icon (top one) and it immediately crashed again, same as above. This can be repeated at will.

Reproduction is easy: Install Konqueror from repository, enter above command, click icons to left in Konqueror window.

I am sure this is a Konqueror problem. But, it shouldn't crash the OS.

I am glad to answer questions. But, I hope it's easy to reproduce.

Mint Linux 18.3 - VirtualBox 6.0.10

```
 * Cinnamon version (cinnamon --version)
   - Please specify if you are using the daily builds PPA (https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds).
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
 * Graphics hardware *and* driver used
 * 32 or 64 bit
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
 ```

**Issue**

**Steps to reproduce**

**Expected behaviour**

**Other information**

**Comment by icarter09** [comment]
@distantlightning did you open up a bug ticket for Konqueror?

https://bugs.kde.org/enter_bug.cgi?format=guided&product=konqueror
