### ISSUE TITLE
Flatpak package of the Brackets from flathub doesn't have a icon.

### ISSUE THREAD

**Issue by kacperpaczos** [linuxmint/cinnamon#8795]
Icon in the menu is showing good, but in menu it doesn't.
Where application bar try to find the icons?
I can't this information in the code of this applet.

Great mystery to me is why icon of the bracket is showing correctly in menu applet.

![obraz](https://user-images.githubusercontent.com/23406555/63061863-00bb8680-bef7-11e9-992f-7c0a022735b7.png)

https://github.com/flathub/io.brackets.Brackets/issues/3

**Comment by mtwebster** [comment]
This seems to be cinnamon's app system not being able to match up the running program with its .desktop file.  It seems specific to electron apps, they don't set a fallback icon on the window itself like most other apps do.

**Comment by pyroxar** [comment]
It's the same problem on flatpak package of steam, but only when steam is configuring or updating:
A few screenshot here:
![obraz](https://user-images.githubusercontent.com/23406555/63086276-cfbb7000-bf4f-11e9-9a41-76229b0e260a.png)
![obraz](https://user-images.githubusercontent.com/23406555/63086279-d34ef700-bf4f-11e9-8360-2477c3a91dd1.png)
![obraz](https://user-images.githubusercontent.com/23406555/63086284-d649e780-bf4f-11e9-9c2f-d84d14336e34.png)
Normal window of the client of steam looks good.
![obraz](https://user-images.githubusercontent.com/23406555/63086407-1610cf00-bf50-11e9-8c42-74d753ce7e30.png)
It's the issue on steam github:
https://github.com/ValveSoftware/steam-for-linux/issues/6063

**Comment by pyroxar** [comment]
Geogebra from flathub doesn't have a icon, icons is only when i have install geogebra from *deb package.
![obraz](https://user-images.githubusercontent.com/23406555/63089458-35abf580-bf58-11e9-9017-e10536546e51.png)

**Comment by pyroxar** [comment]
Stacer is a electron app, installed from deb and appimage file have icon:
![obraz](https://user-images.githubusercontent.com/23406555/63090115-8886ac80-bf5a-11e9-8c45-9190be39f26c.png)

**Comment by pyroxar** [comment]
I think that Linux Mint Cinnamon have totally mess with icons.
When I have brackets, menu and mintinstall are showing a icon.
When I have WPS Office mintinstall doesn't (support icon remote) show a icon but menu applet and app list show the icon of WPS Office correctly.
https://github.com/flathub/com.wps.Office/pull/39#event-2555161861 
https://github.com/linuxmint/mintinstall/issues/258

**Comment by pyroxar** [comment]
I founded a new issue:
When you want remove a app using menu applet (app -> right click -> remove), window which is showing when app is removing haven't icon:
![obraz](https://user-images.githubusercontent.com/23406555/63090865-e1574480-bf5c-11e9-93ef-2c5aeccc0000.png)
@mtwebster Can you show me where is code which generate pkgcache in mintinstall? I can't find this. Linux Mint have totally mess with icons.

**Comment by mtwebster** [comment]
The issue with anything during runtime is an issue with our window tracking.  The remove app icon issue is the same bug as I mentioned previously.

The WPS office problem is that we don't have support for 'remote' IconKinds.  Possibly I didn't have any examples to test at the time I wrote this, I don't know.  The runtime getter is here: https://github.com/linuxmint/mintcommon/blob/master/usr/lib/python3/dist-packages/mintcommon/installer/pkgInfo.py#L243

I can add remote icons, but I need to download it when building the cache, not at runtime.

**Comment by mtwebster** [comment]
I was mistaken - we are actually using mintinstall to get icons still for whatever reason.  I'll see about changing that to use the appstream api, and finishing that implementation to support remote icons.

**Comment by pyroxar** [comment]
I updated the mintcommon to 2.0.5, refresh cache and sadly mintinstall is still no showing the wps office icon.

> pyroxar@zero:~$ mintinstall
> MintInstall: Detected system architecture: 'x86_64'
> Installer: User pkgcache is most recent, using it.
> MintInstall: Deleting old screenshots
> MintInstall: No new reviews
> 
> ** (mintinstall.py:3909): WARNING **: 19:17:01.181: Found icon of unknown type, skipping it: unknown
> Installer: Generating new pkgcache
> Installer: flatpak - metadata for remote 'flathub' has been updated. Comparing appstream timestamps...
> Installer: flatpak - no new appstream data for remote 'flathub', skipping download
> Installer: Processing Flatpaks for cache took 2581.170 ms
> Installer: Processing APT packages for cache took 2026.196 ms
> Installer: User pkgcache is most recent, using it.
> Full installer startup took 15213.971 ms
> MintInstall: Deleting old screenshots
> MintInstall: No new reviews
> 
> ** (mintinstall.py:3909): WARNING **: 19:17:15.790: Found icon of unknown type, skipping it: unknown

In another bugs to no changes.

**Comment by mtwebster** [comment]
You'd need to update mintinstall to git master in order to see the changes to flatpak icons.  The mintcommon update was made for a different issue.

**Comment by pyroxar** [comment]
OK, it work, one done. Thanks.
