### ISSUE TITLE
[Feature request] Touch Screen rotation with easy blocking system 

### ISSUE THREAD

**Issue by cgarciaq** [linuxmint/cinnamon#8797]
I think 2-in-1 support can be greatly improved in Cinnamon/Linux Mint. Specifically, the touch screen with rotation capabilities. This is how I would like to work, which I think would be desirable for the vast majority of users:

- The **touch** screen should **rotate along** with the screen (I could probably tag this more as a bug than as a feature request). 

- There should be an applet or an easy way to **block the screen rotation**. For instance, I am using the tablet in the bed reading and maybe writing with the pen, and I start to roll over the bed and read upside down... in this situation, I want to be able to block the rotation, allowing me to move freely, but I don't want to go to a settings menu.

- For 2-in-1s, it would be wonderful, IMHO, if screen **rotation only happened when the lid has surpassed the 180º**. Otherwise, I am working with it as a laptop and probably I do not need it to rotate (and is probably annoying).

- There should be a quick way to **disable the touch screen** (disable fingers touch, not stylus touch). This way, I can write to the screen with the stylus without having to worry about my palm touching it.

I have found a script (magick-rotation) that implements some of these features: it rotates the touch screen along with the screen AND it allows me to disable the touch screen (fingers, not pen). But it does not allow me to block the screen rotation nor is able to detect the lid position and use it, and it interferes with the settings menu controlling the screen rotation, rendering it useless. IMHO, all of this should be integrated in Cinnamon.
 
 ```
 * Cinnamon version: 4.2.3 (not using daily builds)
 * Distribution - Mint 19.2
 * Graphics hardware *and* driver used: Intel HD Graphics 615 (found in a Dell XPS 13 9365 2-in-1)
 * 64 bit
  ```

**Comment by ovari** [comment]
https://github.com/linuxmint/cinnamon/issues/7757

**Comment by ovari** [comment]
Could another option with value `Automatic` be available in the `Rotation` drop-down box in the `Display` window?

![image](https://user-images.githubusercontent.com/17465872/64072399-e04e4300-ccd0-11e9-97ba-3c88482bf53f.png)

What do you think?

Thank you

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
