### ISSUE TITLE
Touchpad on/off setting doesn't persist

### ISSUE THREAD

**Issue by stolendata** [linuxmint/cinnamon#8805]
```
 * Cinnamon version (cinnamon --version)

   4.2.3

 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)

   Mint 19.2

 * 32 or 64 bit

   64
```
**Issue**

   Disabling the laptop's touchpad - whether via keyboard shortcut, or in the "Mouse and Touchpad" configuration panel - isn't persistent. The touchpad is enabled again when booting up.

**Steps to reproduce**

   Disable touchpad and reboot.

**Expected behaviour**

   Touchpad should be disabled.

**Comment by claudiux** [comment]
How to disable the Touchpad when the mouse is plugged and enable it when the mouse is unplugged:

Use `lsusb` (from the `usbutils` package) in verbose mode to determine the _idVendor_ and _idProduct_ of your mouse:

`lsusb -v` 

Then, create the `/etc/udev/rules.d/20-mouse.rules` file, which must contain these lines (replace 18f8 and 0f97 by your own values):

```
SUBSYSTEMS=="usb", ATTRS{idVendor}=="18f8" ATTRS{idProduct}=="0f97", ACTION=="add", RUN+="/usr/bin/synclient TouchpadOff=1", RUN+="/sbin/modprobe -r psmouse"
KERNEL=="mouse[0-9]*", SUBSYSTEM=="input", ACTION=="remove", RUN+="/sbin/modprobe psmouse", RUN+="/usr/bin/synclient TouchpadOff=0"
```

Then restart the `udev` service:

`sudo service udev restart`

or reboot if any.

N.B Replace `psmouse` by the module-driver of your touchpad.

**Comment by JosephMcc** [comment]
I can't reproduce this issue here. Turning it off in the system settings still works after a reboot.

**Comment by icarter09** [comment]
@stolendata you still experiencing this issue?

**Comment by stolendata** [comment]
@icarter09 Yes, the problem persists - the bug isn't solved - but I can work around it using @claudiux' fix.

**Comment by icarter09** [comment]
Cinnamon 4.8.6
Mint 20.1

I'm not able to reproduce this issue. Disabling the touchpad setting persisted after reboot.
