### ISSUE TITLE
no hiDPi support for other APPs (Realvnc, Shotcut, Openshot, Xnview, Gimp ...)

### ISSUE THREAD

**Issue by hubertmeier** [linuxmint/cinnamon#8809]
Linux Mint 19.2 with a 28 inch / 4k Display. HiDPI is set, fonts are then reduced to 0.8.

Cinnamon and all APPs related to linuxmint are ok (nemo etc ...) but other APPs like shotcut, openshot, realvnc, Xnview, Gimp (especially icons), VLC, are very difficult to read, only with a magnifying glass ;-))

Is there a solution which works system-wide or has every programmer to do this for his software ?

I built this system for 4k-Video but the Videocut-software is not really useable. 

Thank you

**Comment by calestyo** [comment]
This also affects Java applications... a solution could be, that  cinnamon exports the GDK_SCALE env var (e.g. =2) when it detects HiDPI res.

**Comment by calestyo** [comment]
Problem though is, that applications that already look fine, are doubled as well... :-/

**Comment by JosephMcc** [comment]
This isn't really a Cinnamon issue. Some apps like Gimp use a UI toolkit that doesn't support HiDPI.
