### ISSUE TITLE
cinnamon crashes with zh non-UTF-8 encodings

### ISSUE THREAD

**Issue by joequant** [linuxmint/cinnamon#8811]
```
 * Cinnamon version (cinnamon --version)

4.2.0

   - Please specify if you are using the daily builds PPA (https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds).
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)

Mageia cauldron

 * Graphics hardware *and* driver used

intel laptop

 * 32 or 64 bit

64 bit
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
 ```
Cjs-Message: 13:16:02.466: JS LOG: [LookingGlass/info] Loaded applet notificatio
ns@cinnamon.org in 82 ms
dbus[18025]: arguments to dbus_message_iter_append_basic() were incorrect, assertion "_dbus_check_is_valid_utf8 (*string_p)" failed in file dbus-message.c line 2766.
This is normally a bug in some application using the D-Bus library.

**Issue**

Cinnamon will crash on startup when processing a non UTF-8 locale.  (Chinese using Big-5 encoding).  What appears to be happening is that cinnamon is sending data down dbus and this data is being trapped as non UTF-8 compliant.

This issue only started to appear in the last week, and may be because we are pulling in new dbus libraries that are checking strings for UTF-8 compliance.

**Steps to reproduce**

**Expected behaviour**

**Other information**

**Comment by joequant** [comment]
More information.  This seems to have something to do with atk-bridge.  Version 2.32.0 does not cause problems, but version 2.33.91 does.

**Comment by joequant** [comment]
Thread 1 "cinnamon" received signal SIGABRT, Aborted.
0x00007f4ae7719de0 in raise () from /lib64/libc.so.6
(gdb) where

#0  0x00007f4ae7719de0 in raise () at /lib64/libc.so.6
#1  0x00007f4ae7701548 in abort () at /lib64/libc.so.6
#2  0x00007f4ae6263e0d in  () at /lib64/libdbus-1.so.3
#3  0x00007f4ae6284bdb in  () at /lib64/libdbus-1.so.3
#4  0x00007f4ae62769e9 in dbus_message_iter_append_basic () at /lib64/libdbus-1.so.3
#5  0x00007f4ae78db909 in spi_object_append_desktop_reference () at /lib64/libatk-bridge-2.0.so.0
#6  0x00007f4ae78e0bb1 in append_cache_item () at /lib64/libatk-bridge-2.0.so.0
#7  0x00007f4ae793d0b0 in g_hash_table_foreach () at /lib64/libglib-2.0.so.0
#8  0x00007f4ae78e0d1e in impl_GetItems () at /lib64/libatk-bridge-2.0.so.0
#9  0x00007f4ae78ea871 in handle_message () at /lib64/libatk-bridge-2.0.so.0
#10 0x00007f4ae627b37d in  () at /lib64/libdbus-1.so.3
#11 0x00007f4ae626c3f4 in dbus_connection_dispatch () at /lib64/libdbus-1.so.3
#12 0x00007f4ae6236445 in message_queue_dispatch () at /lib64/libatspi.so.0
#13 0x00007f4ae794dba5 in g_main_context_dispatch () at /lib64/libglib-2.0.so.0
#14 0x00007f4ae794df18 in g_main_context_iterate.isra () at /lib64/libglib-2.0.so.0
#15 0x00007f4ae794e1ca in g_main_loop_run () at /lib64/libglib-2.0.so.0
#16 0x00007f4ae7f61aba in meta_run () at /lib64/libmuffin.so.0
#17 0x000000000040268d in main ()
(gdb) quit

**Comment by icarter09** [comment]
@joequant are you still experiencing this issue? If so, could you provide the steps to reproduce? Thanks.

**Comment by joequant** [comment]
It appears to work with libatk 2.34.1  

Closing.
