### ISSUE TITLE
Dual monitor, Nemo hides

### ISSUE THREAD

**Issue by Cornell737** [linuxmint/cinnamon#8815]
``
 * Cinnamon version (cinnamon --version)  4.2.3
   - Please specify if you are using the daily builds PPA (https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds).
   - Update manager's using the out-of-the-box repositories
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) 
Kernel: 4.15.0-58-generic x86_64 bits: 64 Desktop: Cinnamon 4.2.3 Distro: Linux Mint 19.2 Tina
 * Graphics hardware *and* driver used
Graphics:  Device-1: Advanced Micro Devices [AMD/ATI] Trinity [Radeon HD 7480D] driver: radeon v: kernel 
           Display: x11 server: X.Org 1.19.6 driver: ati,radeon unloaded: fbdev,modesetting,vesa 
           resolution: 1280x1024~60Hz, 1600x900~60Hz
 * 32 or 64 bit: 64 bit
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog

[syslog.1.log](https://github.com/linuxmint/cinnamon/files/3535560/syslog.1.log)

(it's syslog.1.log because the site won't allow uploading a *.1 file. And it's syslog.1 because syslog rotated to syslog.1 overnight.)
 ```

**Issue**
Using dual monitors: when there was but one Nemo window open,
on the secondary monitor, moving the cursor from the primary to the
secondary monitor to the Nemo window... the Nemo window 
disappeared, hid.  When moving cursor back to primary, Nemo
window reappeared. I could repeatedly make the window disappear
by trying to move the cursor back to it.  

Once I opened a second Nemo window, on the primary monitor, the
first window stopped disappearing.

Behaviour has been normal since.

**Steps to reproduce**
-Fresh install of Mint 19.2.
(Note physical right hand monitor is interpreted to be on the left and primary)
-Menu/Preference/Display to make left hand monitor primary.
-Update manager to bring it up to date.
-Open Nemo and Hexchat, windows open on primary monitor.
-Drag Nemo window to secondary monitor.
-Return cursor to primary, get into Hexchat, #linuxmint-help chatroom.
-Move cursor to Nemo on secondary monitor... it hides.
-Move away, it returns.

**Expected behaviour**
I expect the Nemo window to not disappear.

**Other information**
Note that right hand monitor is VGA, left hand is DVI-D, don't know if that matters.

**Comment by icarter09** [comment]
@Cornell737 are you still experiencing this issue?

**Comment by Cornell737** [comment]
No, I'm not.  Since reporting this, I've re-installed Tina, and replaced a monitor.  I don't know which, if either, corrected the problem.

**Comment by Cornell737** [comment]
Actually, the "re-install" was a fresh install, instead of an upgrade.
