### ISSUE TITLE
grouped-window-list bindAppKey() silently overrides standard keyboard shortcut settings？

### ISSUE THREAD

**Issue by Campanula** [linuxmint/cinnamon#8816]
<Super+N> launchs the N-th app on panel:
 
https://github.com/linuxmint/cinnamon/blob/1956f9db3979df0a1c8bf1c71cc3c53bbce74ac6/files/usr/share/cinnamon/applets/grouped-window-list%40cinnamon.org/applet.js#L509

while I set <Super+N> to switch to N-th workspace in standard keyboard shortcut settings.
It doesn't work because bindAppKey() overrides my keybind.

Could we add a option to custom the `leader key` to launch the N-th app or just turn it off?

--------------------------------
my distribution:
Manjaro Linux
Cinnamon 4.2.3

**Comment by k1pp13** [comment]
I have the same request. I use <Super+N> from 1 through 5 to open various apps. Kindly make this feature a choice.

**Comment by k1pp13** [comment]
I doubt this is encouraged, but I 'fixed' the problem by commenting out this code:

`for (let i = 1; i < 10; i++) {`
        `    this.bindAppKey(i);`
`}`

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.

**Comment by Campanula** [comment]
https://github.com/linuxmint/cinnamon/blob/d1882d309882d91afd6f4929ace06c12af47e7e7/files/usr/share/cinnamon/applets/grouped-window-list%40cinnamon.org/applet.js#L456

Have we prepared a switch (UI setting) for it ?
