### ISSUE TITLE
Alt-F2 ('runner') duplicates command under a certain condition

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/cinnamon#8819]
```
 * Cinnamon version (cinnamon --version): 4.2.3
   - Please specify if you are using the daily builds PPA (https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds): no.
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...): Mint 19
 * Graphics hardware *and* driver used: Intel UHD Graphics 620 3.0 Mesa 19.0.8
 * 32 or 64 bit: 64
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
 ```

**Issue**

An intuitive way of trying to execute an alt-F2 command does not execute the command but instead duplicates the text of the command.

**Steps to reproduce**

1. Have text on the clipboard such that the text is pastable with the mouse.
2. Alt-F2.
3. Move pointer over alt-F2 box. Right-click and select paste; at this point the clipboard text appears in the alt-F2 box.
4. Press enter on the keyboard - irrespective of where the pointer is, but when the F2 box is _not_ focused, i.e. lacks a caret.
5. Result: the pasted text in the F2 box gets duplicated. That is: if one had pasted 'nemo' into the box, one ends up, not running nemo, but with this in the box: `nemonemo` (sic).

**Expected behaviour**

The text entered should be executed, i.e. parsed as a command (if possible) and executed.

**Other information**

I reproduced the problem with these themes: Mint-Y-Grey; Cinnamon.

Other open issues filed under alt-F2: #4591 (bug reproduced); #5321; #5937; #7461; #7959; #8593.
Closed feature requests for alt-F2: #2223; #2366; #3130; #5732.

EDIT: for those wanting an alt-F2 replacement that seems to work, a program called 'gmrun' is in the Mint repositories.

**Comment by JosephMcc** [comment]
I can't reproduce this. The first problem I have with the steps you provide is that the run dialog is always focused. How are you getting it to lose focus, not show the caret?

**Comment by LinuxOnTheDesktop** [comment]
I'm afraid I don't understand. (i) At what stage in my 1-5 does the dialog need to become unfocused?

On my system the dialogue becomes unfocused part way through step 3, namely, when I put the pointer over the 'paste' option in the context menu. (I say 'my system' but I've changed my main system to use a different command runner - one that works! But I reproduced the problem just now on a Mint VM that I have.)

**Comment by JosephMcc** [comment]
Umm... Step 4. How do I press enter with it unfocused/without a caret? That never happens here except while the copy/paste menu is open.

**Comment by LinuxOnTheDesktop** [comment]
> 4. Press enter on the keyboard - irrespective of where the pointer is, but when the F2 box is not focused, i.e. lacks a caret.

Ah yes: sorry. Here, I find the following. After the paste (= after step 3), _the ALT-F2 box loses its caret but still accepts input_ (and does the strange duplication of the input). That happens in the VM and - I find, now that I've removed my customisation - on native Mint.
