### ISSUE TITLE
Standby wakeup user session crash

### ISSUE THREAD

**Issue by MartinX3** [linuxmint/cinnamon#8820]
```
 * Cinnamon version 4.2.3
 * Distribution - Linux Mint 19.2
 * Nvidia GTX940MX + Driver v430.40
 * 64 bit
 * Logs -> https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1818974
 ```

**Issue**
Waking up from standby let the BPfilter message last longer than usual and after that I get a normal login screen, without my user session.

**Steps to reproduce**
It happens rarely and I made logs for every incident in the launchpad bug tracker.
I assume it happens far more often with my external usb 3 HDD/SSD SATA docking station attached with my HDD.

PS: I use a ThinkPad T460P with the ThinkPad Docking Station.

**Expected behaviour**
Waking up with attached external HDD and logging into my user session.

**Other information**
My hardware informations:
https://termbin.com/r2wh

My try to locate the bug, thought it may be in the kernel:
https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1818974

Maybe it is caused by the nvidia driver.

Other maybe related bug reports by me:
https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1837547
https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1820243
https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1781904

**Comment by leigh123linux** [comment]
There isn't anything to fix within cinnamon code that can make it survive after a X server crash.
