### ISSUE TITLE
Port/enable fractional DPI scaling support, now that it's supported by GNOME 3

### ISSUE THREAD

**Issue by sparky222b** [linuxmint/cinnamon#8835]
```
 * Cinnamon version  4.2.3
 * Distribution Mint 19.2 x64
 ```

**Issue**
Cinnamon has lacked support for fractional DPI scaling since inception, allowing people to pick only normal (1.0x) and double (2.0x) DPI scales. This appears to be an oft-requested feature, but the answer of the Cinnamon developers always seems to be that support for that doesn't exist in the underlying technologies (GTK, etc).

As of GNOME 3.22, this is no longer the case - GNOME Shell now has native support for exactly that ([Merge Request](https://gitlab.gnome.org/GNOME/gnome-shell/merge_requests/5/diffs), [Phoronix](https://www.phoronix.com/scan.php?page=news_item&px=GNOME-3.32-Fractional-Scaling)). 

As this is a core quality-of-life issue for the increasing number of users living on 4K+ displays, I wonder if it would now be possible to incorporate support for this, given that the upstream packages seem to have solved the problem.

Thanks!

**Comment by collinss** [comment]
Please see my comment here https://github.com/linuxmint/cinnamon/issues/8833#issuecomment-527499825. Implementing this feature is going to take a _huge_ amount of work.

**Comment by sparky222b** [comment]
Thanks @collinss, that's understandable.

There seems to be some chatter around the web about being able to use various workarounds with X11 and GNOME 3 ([1](https://www.linuxuprising.com/2019/04/how-to-enable-hidpi-fractional-scaling.html), [2](https://github.com/alex-spataru/HiDPI-Fixer)); do you know if this is relevant to Cinnamon at all, even if it's buggy?

**Comment by collinss** [comment]
> do you know if this is relevant to Cinnamon at all, even if it's buggy?

I don't know, but it sounds like both cases are quite buggy and terrible on performance. I can't speak for the rest of the team, but I would prefer to wait until we can do this right, and I'm guessing they will too.

**Comment by alikopat** [comment]
When I turn on the Hi-DPI, everything becomes so big and my pc becomes unusable. So I just added this command to my startup applications. It gives me 1.6x scale I think. So why not? Can't you use the same system and add an option to Display Settings that we can set fractional scaling and you do the rest in the background.

xrandr --output DVI-0 --scale 1.25x1.25

**Comment by NikoKrause** [comment]
Cinnamon 4.6 will introduce fractional scaling.

https://blog.linuxmint.com/?p=3858
