### ISSUE TITLE
App icons in panel do not refresh (regression from Mint 19.1)

### ISSUE THREAD

**Issue by darrenhopkinson** [linuxmint/cinnamon#8837]
```
 * Cinnamon 4.2.3
 * Linux Mint 19.2
 * Intel graphics
 * 64 bit
 ```

**Issue**
Application icons in the cinnamon panel and task switcher do not refresh correctly when changed programmatically. This is a regression from Mint 19.1.
Restarting cinnamon using the 'r' command correctly updates the icon in both the panel and the task switcher, demonstrating that this is likely to be a refresh issue.

**Steps to reproduce**
Can be reproduced using a Java application which calls the setIconImage() method of the AWT class JFrame.java.
Reproducible using both java-1.11.0-openjdk-amd64 and java-8-oracle.
This used to work correctly with identical application and Java runtime in Mint 19.1, suggesting it is a regression in Cinnamon.

**Expected behaviour**
Panel icon for the application is updated immediately with the png image specified in the call to setIconImage().

**Other information**

**Comment by pyroxar** [comment]
I will try reproduce this, do you tell me which application i should use? It might be third party application.

**Comment by darrenhopkinson** [comment]
Thanks for your reply. I'm using an application I built myself. I believe that this would be reproducible with any java app which has a call to JFrame.setIconImage().

**Comment by pyroxar** [comment]
Upload source code your app/simple example app to github, I will compile it (if you can, please give me instruction) and test on my computers.

**Comment by darrenhopkinson** [comment]
[IconTest.jar.tar.gz](https://github.com/linuxmint/cinnamon/files/3586483/IconTest.jar.tar.gz)

Created and attached example app (IconTest.jar.tar.gz). Run using:

$ java -jar IconTest.jar

Please let me know if you have any trouble reproducing the problem.

**Comment by darrenhopkinson** [comment]
Any success reproducing this bug?

**Comment by pyroxar** [comment]
Yes, I can reproduce this bug. 

Your application work fine on my Lenovo ThinkPad with Linux Mint 19 with Cinnamon 3.8.9.
Your application can't change the image on Linux Mint 19.2 with Cinnamon 4.2.4 (on Lenovo IdeaPad).

I don't have any computer now with Linux Mint 19.1.

**Comment by darrenhopkinson** [comment]
I just retested this on the BETA Release of Linux Mint 19.3 “Tricia” Cinnamon.

The bug still happens.

**Comment by pyroxar** [comment]
Make issuse in Linux Mint 19.3 beta repo.

**Comment by pyroxar** [comment]
https://github.com/linuxmint/mint19.3-beta

**Comment by darrenhopkinson** [comment]
Done: https://github.com/linuxmint/mint19.3-beta/issues/25
