### ISSUE TITLE
Menu applet doesn't use the timeshift policykit to run the app.

### ISSUE THREAD

**Issue by pyroxar** [linuxmint/cinnamon#8842]
```
 * Cinnamon version (cinnamon --version): Cinnamon 4.2.4
 * Distribution: Linux Mint 19.2 
 ```

**Issue**
Menu applet doesn't use the timeshift policykit to run the app.

**Steps to reproduce**
Launch the timeshift from menu:
![image](https://user-images.githubusercontent.com/23406555/64459689-c78ec480-d0f8-11e9-9722-e493e85062b9.png)

**Expected behaviour**
Menu applet should use the timeshift's policykit:
![image](https://user-images.githubusercontent.com/23406555/64459754-f5740900-d0f8-11e9-9d35-b623466b98a2.png)

**Other information**

**Comment by clefebvre** [comment]
That's an issue in timeshift, not Cinnamon.

/usr/share/applications/timeshift.desktop defines its Exec as timeshift-launcher instead of pkexec timeshift.
