### ISSUE TITLE
Windows Quick List applet does not close properly

### ISSUE THREAD

**Issue by dutta64** [linuxmint/cinnamon#8843]
```
 * cinnamon 4.2.4
 * 5.2.11-1-Manjaro
 ```

**Issue**

Closing the applet while it is already open still leaves a menu/popup open.

**Steps to reproduce**

Click the applet to open it, click it again to try and close it.

**Expected behaviour**

The applets popup menu(s) should close.

**Comment by icarter09** [comment]
@dutta64 did your PR fix this issue? If so, can you close the ticket? Thanks.
