### ISSUE TITLE
[Feature Request] Remove Snap Package directly from the Start menu.

### ISSUE THREAD

**Issue by VaGNaroK** [linuxmint/cinnamon#8846]
Linux mint has the option to remove .deb programs from the official repository and in flatpak format directly from the menu. Most programs installed via snap do not have this option. Would you add snap programs removal via home menu?

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
