### ISSUE TITLE
Cinnamon for FreeBSD

### ISSUE THREAD

**Issue by zetrotrack000** [linuxmint/cinnamon#8850]
Hi
Kindly release cinnamon for FreeBSD.

PS: I don't know whether it is proper forum to request this feature, so, apologies in advance.
Regards

**Comment by clefebvre** [comment]
Hi @zetrotrack000,

It's not really the right place for this. Cinnamon aims to be compatible with as many Linux distributions as possible. That could extend to BSDs, but it's not really clear to me if it's currently compatible with FreeBSD and how much work would be involved for this to happen. If it's feasible, we'd be happy to support it, but any hurdles on the way would need to be identified by FreeBSD maintainers using issues such as this one and solutions should be brought using pull requests.

**Comment by zetrotrack000** [comment]
Kindly guide me towards the right forum, so I can place a request there.
Thanks

**Comment by leigh123linux** [comment]
> Hi
> Kindly release cinnamon for FreeBSD.

Why would LinuxMint package cinnamon for any other distro, I doubt Clem has the time to do a 'LinuxMint BSD edition' in addition to his current workload.

> 
> PS: I don't know whether it is proper forum to request this feature, so, apologies in advance.
> Regards

What is wrong installing cinnamon yourself?

https://www.2daygeek.com/install-xfce-mate-kde-gnome-cinnamon-desktop-environment-on-freebsd/

or ask

https://forums.freebsd.org/

**Comment by zetrotrack000** [comment]
Cinnamon 2.4 is available in FreeBSD repo. New version needs to be ported.

**Comment by clefebvre** [comment]
@zetrotrack000 I'd suggest you contact the people who maintain Cinnamon in FreeBSD so they upgrade their version to the newest one. If they encounter issues or incompatibilities they'll post issues here for us to look at.

**Comment by zetrotrack000** [comment]
> @zetrotrack000 I'd suggest you contact the people who maintain Cinnamon in FreeBSD so they upgrade their version to the newest one. If they encounter issues or incompatibilities they'll post issues here for us to look at.

ok, thanks a lot.
