### ISSUE TITLE
[FEATURE] Integration with florence On Screen Keyboard

### ISSUE THREAD

**Issue by jcpunk** [linuxmint/cinnamon#8851]
```
 * Cinnamon version (cinnamon --version)   -  4.2.4
 * Distribution - Fedora 30
 ```

**Issue**
The caribou On Screen Keyboard isn't seeing much development these days.  Florence seems to integrate with gnome-shell acceptably.  Might this be an alternative?  Could this be a wedge to permit making the OSK a bit more interchangeable down the road?

There don't seem to be all that many fully interchangeable OSKs out there...

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
