### ISSUE TITLE
Fedora 30 unable to launch "Favorite Applications"

### ISSUE THREAD

**Issue by xzj8b3** [linuxmint/cinnamon#8854]
```
 With Fedora 30 it seems impossible to set "Preferred Applications" the corresponding item in the menu generates the following error:

https://bugzilla.redhat.com/show_bug.cgi?id=1752134As

 a result it is impossible to set up the most used applications ..... It also seems to be updated very little Cinnamon from the repositories of Fedora, too bad because one of its best features was undoubtedly to be constantly improved and updated, feature should be reflected in any distribution on which you want to install it!!!

**Comment by leigh123linux** [comment]
Clode #8853

**Comment by leigh123linux** [comment]
> 
>  a result it is impossible to set up the most used applications ..... It also seems to be updated very little Cinnamon from the repositories of Fedora, too bad because one of its best features was undoubtedly to be constantly improved and updated, feature should be reflected in any distribution on which you want to install it!!!
> 

Your comment about lack of fedora updates is pure rubbish, where did you dream up that crap?
I'm currently up to date with what Linuxmint has published!!

**Comment by xzj8b3** [comment]
> > di conseguenza è impossibile impostare le applicazioni più utilizzate ..... Sembra anche che sia stato aggiornato pochissimo Cinnamon dai repository di Fedora, peccato perché una delle sue migliori funzionalità era senza dubbio da migliorare e aggiornare costantemente, caratteristica 

I always find a great 'courtesy every time you comment here .... I have not used Cinnamon for a long time, but given its use since its first beta seen I always liked it once did many more updates ...

However I have never seen great evolutions, in fact every time the text there is something does not start, Applet, Widget and Desklet always the same of which many updates date back to five months ago if not more .... what a pity a similar decline seen had started so well pleasing to many!!!!!
