### ISSUE TITLE
"Upload system information" button appears to not work, but is actually just slow

### ISSUE THREAD

**Issue by kj800x** [linuxmint/cinnamon#8857]
```
https://termbin.com/3gf9
 * cinnamon-control-center: 4.2.2+tina
 * Distribution: Mint 19.2 Cinnamon
 * Graphics Card: NVIDIA GeForce RTX 2070
 * Graphics Driver: nvidia-430
 * 64 bit
 ```

**Issue**
`Upload system information` button in `System Info` takes a significant amount of time (9 seconds on my machine), and provides no user feedback while it's in progress to show that something is happening.

This is on a relatively fresh install of 19.2 (keeping my old `/home` directory). I basically installed my graphics drivers, VSCode, and google-chrome, and then ran into this bug.

![ezgif-4-a86a89eee454](https://user-images.githubusercontent.com/1657142/64916086-1ca78780-d744-11e9-91b5-00923fa79976.gif)

Potentially related to linuxmint/cinnamon-control-center#209, but there's not enough information in that issue to tell.

**Steps to reproduce**
* Open System Info
* Click `Upload system information`

**Expected behavior**
Either the webpage with the system dump is opened faster, or there is some sort of loading state to indicate that the dump has started.

**Comment by pyroxar** [comment]
I can reproduce this bug.

**Comment by icarter09** [comment]
I'm able to duplicate this issue as well. I think the best solution would be to indicate to the user that the system dump has started.
