### ISSUE TITLE
Touchpad unpredictably clicks when typing in Linux Mint - Dell Latitude 7480

### ISSUE THREAD

**Issue by TranNgocKhoa** [linuxmint/cinnamon#8858]
```
 * Cinnamon version (cinnamon --version)
   Cinnamon 4.2.4
 * Distribution - Linux Mint 19.2
 * Graphics hardware *and* driver used: Intel HD Graphics 620
 * 32 or 64 bit: 64 bit
 * Model: Dell Latitude 7480
 ```

**Issue**
Mouse in touchpad unpredictably clicks when typing.

**Steps to reproduce**
Each time I press and hold these keys: L Ctrl, R Ctrl, L Shift, R Shift, Fn, L Alt, Up, Right, Left, Down, the mouse is also clicked unpredictably .

**Expected behaviour**
There isn't any click behavior when I typing.

** Additional **
There is a same problem in Linux Mint forum: https://forums.linuxmint.com/viewtopic.php?t=301788

**Comment by icarter09** [comment]
@TranNgocKhoa can you provide steps for me to try and reproduce this issue? I see you did provide steps, but I'm not exactly sure on order of keys or combination of keys. Thanks.

**Comment by TranNgocKhoa** [comment]
> @TranNgocKhoa can you provide steps for me to try and reproduce this issue? I see you did provide steps, but I'm not exactly sure on order of keys or combination of keys. Thanks.
The issue is rarely happening after I change driver to `synaptics`. But it still happend. You can reproduce by these steps:
- Open a text editor and set windows size to maximize. Ensure that you open a long text file.
- Put the editor cursor in your editor, near windows bottom bound.
- Put mouse cursor in your editor, near windows top bound.
- Press and hold Ctrl key 10s, then quickly press about 30 times, then press and hold 10s.
- Repeat

If the issue happen, you will se editor cursor now jumped to the top.

**Comment by icarter09** [comment]
@TranNgocKhoa I tried the steps you provided, but had no luck in reproducing the issue.

**Comment by TranNgocKhoa** [comment]
> @TranNgocKhoa I tried the steps you provided, but had no luck in reproducing the issue.

which model are you using?

**Comment by icarter09** [comment]
I tried it on 3 different mice:
 1) Keyscaper 110 Wireless mouse TM096G
 2) PocketMouse 72114
 3) GE Optical Mouse 99912

**Comment by TranNgocKhoa** [comment]
> I tried it on 3 different models:
> 
> 1. Keyscaper 110 Wireless mouse TM096G
> 2. PocketMouse 72114
> 3. GE Optical Mouse 99912

@icarter09 I'm so sorry because I provided miss information. I mean mouse is touchpad.
Sorry again. I will update issue

**Comment by collinss** [comment]
@TranNgocKhoa Could you check if it still does it in a different desktop environment, or in fallback? You can access fallback by opening melange (<super>+L) and then going to actions->Crash Cinnamon down in the bottom-right corner of the window. To get back, just click the restart cinnamon button in the dialog that pops up.

**Comment by TranNgocKhoa** [comment]
> @TranNgocKhoa Could you check if it still does it in a different desktop environment, or in fallback? You can access fallback by opening melange (+L) and then going to actions->Crash Cinnamon down in the bottom-right corner of the window. To get back, just click the restart cinnamon button in the dialog that pops up.

@collinss I tried with another Desktop Enviroment is Deepin and I haven't faced this problem. With Melange, I switched to Crash Cinammon but the problem still there.

**Comment by icarter09** [comment]
@TranNgocKhoa are you still experiencing issues with the touchpad?

**Comment by TranNgocKhoa** [comment]
> @TranNgocKhoa are you still experiencing issues with the touchpad?

@icarter09 No, Too sad to say that I switched to Ubuntu

**Comment by icarter09** [comment]
@TranNgocKhoa no worries and thanks for the udpate. I'm going to close this ticket. If you do start using Mint again and experience this issue, just create a new ticket or I can reopen this one. Thanks.
