### ISSUE TITLE
Libreoffice window tiling to right and left not working on low resolution laptop screens (lower than 1400 horizontal pixels)

### ISSUE THREAD

**Issue by gydeak** [linuxmint/cinnamon#8863]
Cinnamon 4.2.4, Linux mint cinnamon 19.2 64bit, Intel Corporation Mobile 4 Series Chipset Integrated Graphics Controller i915 driver.
 * Cinnamon version (cinnamon --version)
   - Please specify if you are using the daily builds PPA (https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds).
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
 * Graphics hardware *and* driver used
 * 32 or 64 bit
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
 ```

**Issue**



**Steps to reproduce**



**Expected behaviour**



**Other information**

**Comment by icarter09** [comment]
@gydeak can you provide the steps to reproduce this issue? Thanks.

**Comment by gydeak** [comment]
Hello!

Default Linux Mint 19.2 Cinnamon 64bit installation on Acer TM 5730 and
Lenovo X230 both with intel integrated graphics. After removing libreoffice
gtk3 and installing gtk2 everything OK. There wasn't any other steps.

György


Carter <notifications@github.com> ezt írta (időpont: 2019. nov. 5., K 4:58):

**Comment by JosephMcc** [comment]
This is a natural limitation of tiling. If a window cannot be resized to fit within one-half of the screen then it will not tile.

**Comment by gydeak** [comment]
Dear Joseph!

For my wife, who is an art historian and writes her new book it was a
regression from Linux Mint 17. It depends on Your point of view. For me -
professional classical musician - after spending several hours searching
the web for solution it was also a regression. Fortunatelly I could find
the solution.

Thank You for your work!

György


JosephMcc <notifications@github.com> ezt írta (időpont: 2019. nov. 5., K
15:26):
