### ISSUE TITLE
AMD Vega graphics causes failure when trying to install

### ISSUE THREAD

**Issue by Flintols** [linuxmint/cinnamon#8864]
```
 * Cinnamon version (cinnamon --version) - Cinnamon
   - Please specify if you are using the daily builds PPA (https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds).
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)  - Mint 19
 * Graphics hardware *and* driver used  - AMD RADEON VEGA 8 GRAPHICS
 * 32 or 64 bit - 64 bit
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog - can't do it, unable to get that far
 ```

**Issue**
I recently became the proud owner of the kickstarter build of a UDOO BOLT V8, which has the embedded V1605 micro in it. I wanted to load Mint on it, so downloaded the most recent build from the site and tried to get it installed. (They have Ubuntu 18/19 running, so I expected this to work.) I was unable to get the install to function. Ended up I installed Ubuntu, hoping that one day there would be a Mint version that would install and work with it. So far I have not read of anyone working on it. 

**Steps to reproduce** 
Load build on USB stick, put stick in usb slot, start computer (with AMD Vega GPU).

**Expected behaviour**
Install would recognize the processor and change the mode to allow the install to continue.

**Other information**
link:
https://www.udoo.org/docs-bolt/Operating_Systems/Linux/index.html

**Comment by leigh123linux** [comment]
Sorry this isn't something that can be addressed within cinnamon code.
I doubt this will be address within the Mint-19 release cycle due to it's older ubuntu base, maybe @clefebvre  can add more info.
