### ISSUE TITLE
[cinnamon-settings] Preferred Applications sections isn't showing up: UnboundLocalError: local variable 'description' referenced before assignment

### ISSUE THREAD

**Issue by alicavus** [linuxmint/cinnamon#8872]
```
 * Cinnamon version (cinnamon --version): 4.2.2
   - Please specify if you are using the daily builds PPA (https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds).
 * Distribution : Arch Linux
 * Graphics hardware *and* driver used: Intel Corporation Atom/Celeron/Pentium Processor x5-E8000/J3xxx/N3xxx Integrated Graphics Controller - mesa
 * 32 or 64 bit: 64bit
 ```

**Issue**
Preferred Applications sections isn't showing up

**Steps to reproduce**
Start System Setttings Control Center (cinnamon-settings)
Click on "Preferred Applications"
There is nothing showing up

**Expected behaviour**
Show options for  "Preferred Applications"

**Other information**
`cinnamon-settings 2> cinnamon.log` : [cinnamon.log](https://github.com/linuxmint/cinnamon/files/3654403/cinnamon.log)
[Screenshot from 2019-09-25 22-26-45](https://user-images.githubusercontent.com/7072295/65632980-889eb100-dfca-11e9-9775-48c435fd6f04.png)
[Screenshot from 2019-09-25 22-28-39](https://user-images.githubusercontent.com/7072295/65633050-bb48a980-dfca-11e9-9de1-152a44d05491.png)

**Comment by alicavus** [comment]
Is this same issue with https://github.com/linuxmint/cinnamon/issues/8853 ? I'm with latest updates.

**Comment by leigh123linux** [comment]
> Is this same issue with #8853 ? I'm with latest updates.

Yes.

@eli-schwartz  ^^ Can you patch till the next release please?

**Comment by eli-schwartz** [comment]
@leigh123linux,

Thanks for alerting me, I've uploaded a fixed package.

@alicavus,

The fixed version is now uploaded to [community]. Depending on when your mirror syncs, it may take an hour or two to become available for you. You can check if your mirror has it (and install it if it is available) with the following command:
`pacman -Syu 'cinnamon>=4.2.4-2'`
