### ISSUE TITLE
HiDPI: panel icons have the wrong spacing - for various third party applications

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/cinnamon#8875]
```
 * Cinnamon version (cinnamon --version)
   - Please specify if you are using the daily builds PPA (https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds).

Cinnamon 4.2.4 (which is not a daily build)
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 19.2
 * Graphics hardware *and* driver used: Intel UHD Graphics 620; Mesa
 * 32 or 64 bit: 64.

 ```

**Issue**

There are multiple open Cinnamon bugs reports (e.g. [this one](https://github.com/linuxmint/cinnamon/issues/8223) and [this one](https://github.com/linuxmint/cinnamon/issues/8129) and [this one](https://github.com/linuxmint/Cinnamon/issues/7435)) about Cinnamon displaying icons incorrectly sized or incorrectly spaced. Here is a screenshot of an example, the program in question being called 'Strawberry' (and the icon in question is that one that looks like a strawberry).

![image](https://user-images.githubusercontent.com/47056543/65717180-a33f5b80-e098-11e9-96ab-c9137c766995.png)

I know you are working on panel icons. Will your work fix third-party panel icons, though?

**Steps to reproduce**

Install and run one of the affected applications, e.g. Strawberry or Flameshot or Rainlendar. One can have the problem with Dropbox too, but not if one manages to determine - and so doing is not easy - the right version of the package to install.

**Expected behaviour**

Icons that one can see clearly and use easily.

**Comment by icarter09** [comment]
@LinuxOnTheDesktop I'm attempting to reproduce this issue. I've installed Flameshot, but not seeing any issues. Can you provide a screen capture of what Flameshot looks like for you? Thanks.

**Comment by LinuxOnTheDesktop** [comment]
These days at least, Flameshot's panel icon is relatively unproblematic. [Screenshot](https://i.postimg.cc/kXZSh0cX/flameshot.png). Try Strawberry (pictured above): that's much worse.

**Comment by icarter09** [comment]
@LinuxOnTheDesktop 

![screenshot](https://user-images.githubusercontent.com/4397312/70379416-5975bb80-18fa-11ea-821d-da3d54f2d154.png)

**Comment by LinuxOnTheDesktop** [comment]
Some limited testing suggests that _Hi-DPI_ being enabled causes the problem. For, when I disabled Hi-DPI the Strawberry icon was fine. I tried a few themes and that made no difference (except that sometimes having done that I had to restart Cinnamon in order to see the icon at all).

**Comment by LinuxOnTheDesktop** [comment]
On Mint 19.3

The Strawberry icon, with HiDPI enabled:

![image](https://user-images.githubusercontent.com/47056543/71272480-83dc6580-234b-11ea-9541-0602b373136c.png)

The same icon, with HiDPI disabled, but without having restarted Cinnamon:

![image](https://user-images.githubusercontent.com/47056543/71273171-b5553100-234b-11ea-9cad-be298fbf4193.png)

The same icon, with HiDPI disabled, having restarted Cinnamon:

![image](https://user-images.githubusercontent.com/47056543/71273568-d0c03c00-234b-11ea-9c01-c4fa75dd5e5a.png)

**Comment by LinuxOnTheDesktop** [comment]
I am not seeing this problem on Mint 20 with Cinnamon 4.6.7 - but that might be because I am not using the problematic applications. Closing for now.
