### ISSUE TITLE
[Regression] Horizontal scroll direction reversed

### ISSUE THREAD

**Issue by rcrath** [linuxmint/cinnamon#8877]
* Cinnamon version (cinnamon --version)

```
$ cinnamon --version
Cinnamon 4.2.4
```

   - Please specify if you are using the daily builds PPA (https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds).
no
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
Manjaro, stable channel, up-to-date
 * Graphics hardware *and* driver used

Version | 390.129-7
-- | --
Description | NVIDIA drivers for linux.
NVIDIA Corporation GK208B [GeForce GT 710]

 * 32 or 64 bit
64 bit

 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
 ```attached```
[xsession-errors.log](https://github.com/linuxmint/cinnamon/files/3664883/xsession-errors.log)
yes

**Issue**

after recent update (within past two month at longest) Horizontal scroll changed behavior from moving the window (old behavior) to moving the content of the window ("natural" scrolling) for horizontal scroll only.  Vertical has a setting for natural or not and follows it. Natural scrolling is turned off there.  The setting either needs to be include horizontal scrolling, or horizontal needs its own setting.  right now horizontal is natural and vertical is not. Horizontal has no setting for the scroll behavior.

**Steps to reproduce**

turn horizontal scroll on in  touchpad settings, scroll horizontally.

**Expected behaviour**
Window moves over content rather than content moving.

**Other information**
thank you!

**Comment by rcrath** [comment]
[xsession-errors.log](https://github.com/linuxmint/cinnamon/files/3664899/xsession-errors.log)

**Comment by rcrath** [comment]
seems cured after last update. closing.

**Comment by svyotov** [comment]
Same bug on
> cinnamon --version
Cinnamon 5.6.5
