### ISSUE TITLE
Severe graphical glitches with the free radeon driver and xorg

### ISSUE THREAD

**Issue by dikonov** [linuxmint/cinnamon#8878]
```
 * Cinnamon version (cinnamon --version)
Cinnamon 4.2.4
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
ALTLinux Sysiphus (development brunch)
 * Graphics hardware *and* driver used
[AMD/ATI] Turks XT [Radeon HD 6670/7670]  - the only video card in my desktop system
free radeon driver  (radeon.ko)
* 32 or 64 bit
64
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
 nothing even remotely related could be found in any logs.
* My versions of xorg and xorg-radeon:
   - xorg-server-1.20.5
   - xorg-drv-radeon-19.0.1
   - linux kernel 4.19.72

**Issue**
Almost every small menu, dialog widow, floating tips and notification boxes are drawn with severe graphical distortions (see attached pictures). In many cases it is impossible to read the names of menu items and buttons, so the user does not know what is being pressed ! This issue affects all software run under cinnamon regardless of toolkits.  

Big menus and dialogs appear normal. 

**Steps to reproduce**
Nothing special. Simply run cinnamon using xorg and the radeon free driver and dread the look. 

**Expected behaviour**
Normal readable GUI

**Other information**
The same (or similar looking) problem exibited itself back in 2014 in the same system with older versions of cinnamon and everything else. It seemed to go away soon, but now it is back and worse than ever. This is a developing regression with every new update of my system. First, the systray icons began to appear garbled. Second, (couple of months later) the tooltips and notifications became unreadable. Two days ago, when  xorg-drv-radeon package got updated, the menus and dialogs became garbled too. 

The issue happens ONLY in cinnamon. Mate DE draws well in the same system (compiz worked too). I suspect that the cinnаmon compositor is broken.
 
![grfbug0](https://user-images.githubusercontent.com/4271322/65819957-d6feba80-e22b-11e9-8009-5a2c319fb84c.png)
![grfbug1](https://user-images.githubusercontent.com/4271322/65819963-dcf49b80-e22b-11e9-877d-a542cf1568b3.png)
![grfbug2](https://user-images.githubusercontent.com/4271322/65819964-e251e600-e22b-11e9-8603-ef8445af8a9c.png)
![grfbug3](https://user-images.githubusercontent.com/4271322/65819965-e67e0380-e22b-11e9-8ae9-635c09643bc6.png)

**Comment by dikonov** [comment]
I have just noticed that running bare muffin wm without cinnamon gets rid of the graphical glitches. It is impossible to test all apps because muffin lacks basic functions necessary to start applications from bare desktop, but at least nemo help menu and its dialogs become normal. The glitches return as soon as cinnamon --replace is run.

**Comment by leigh123linux** [comment]
Have you reported the issue against your distro radeon driver as it's unlikely to be a cinnamon issue, does gnome-shell do the same?

**Comment by dikonov** [comment]
Yes, 
https://bugzilla.altlinux.org/show_bug.cgi?id=29773
https://forum.altlinux.org/index.php?topic=43067.0

but I am sure that it is _not_ a driver issue. The ALTLinux maintainers suggested it too.

1) All other compositors, DE and WMs work flawlessly with the same hardware, kernel and driver. The glitches disappear immediately when I stop cinnamon and run another compositor/WM (even muffin). They return after cinnamon --replace.
2) I chose this videocard for the best level of support by the free radeon driver available at the time (and for being fanless). It has been working perfectly well for years except one similar issue back in 2014 that went away with an update within a week. The hardware itself is tried and rock-solid. 

It may happen that cinnamon is ill-adapted to some gradual changes in the driver/kernel (e.g. some hidden defaults got "optimized"). The problem only occurs in small.rectangular areas ocupied by menus, tips, dialogs. The bad thing is that the size of affected GUI elements has been gradually increasing with each new update of cinnamon + driver for many months. I ignored it while it only concerned small icons and did not affect productivity.

**Comment by dikonov** [comment]
* If the rectangle is close to a square is shape (e.g. all menu points have short names) it is less likely to be affected. Wider menus suffer more.

**Comment by dikonov** [comment]
* Running Cinnamon in "2D" mode does not rid it of the bug. The problem persists and looks identical when I login using the software rendering option in the dm (LightDM in my case).  
* I tried to switch clutter backends and drivers using the options and environment variables described at https://developer.gnome.org/clutter/stable/running-clutter.html. I tried x11, wayland, gsk, eglnative backends and gl3, gl, gles2 drivers. Nothing changed, except cinnamon refused to run with the gles2 driver.  --sync, --synch, CLUTTER-VBLANK have no effect on the bug either.

Here is a long debug produced with cinnamon --cogl-debug=all --replace > cinnamon.debug

[cinnamon.debug.tar.gz](https://github.com/linuxmint/cinnamon/files/3675063/cinnamon.debug.tar.gz)

It corresponds to a few seconds while I open 1 badly drawn menu (towards the end of the recorded debug output). The bad menu is the Nemo help menu. The nemo window  was opened before restartting cinnamon.

**Comment by dikonov** [comment]
I was wrong telling that this bug never occurs outside of cinnamon. Sorry. 
It turned out that Gnome3 is also affected, but the chance to see the problem is much less.  The new attachments (grfbug-gno3-1...3.png) show the differences between cinnamon (affected), gnome3 (partially affected) and mate (completely free of the bug). 
![grfbug-gno3-1](https://user-images.githubusercontent.com/4271322/65970970-27665a00-e470-11e9-866f-ce2b38073820.png)
![grfbug-gno3-2](https://user-images.githubusercontent.com/4271322/65970971-27665a00-e470-11e9-9e80-a958c9994a33.png)
![grfbug-gno3-3](https://user-images.githubusercontent.com/4271322/65970972-27665a00-e470-11e9-8953-9d5ad723a580.png)

**Comment by dikonov** [comment]
This appears to be fixed by installing a newer kernel.
