### ISSUE TITLE
Middle click on titlebar lowers a window

### ISSUE THREAD

**Issue by IvoAndonov** [linuxmint/cinnamon#8879]
```
 * Cinnamon version (cinnamon --version): 4.2.4
   - Please specify if you are using the daily builds PPA (https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds): IDK. Whatever Arch's repo has - this is what I use.
 * Distribution - Arch Linux.
 * Graphics hardware *and* driver used nVidia 435.21
 * 64-bit
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
[home_xsession-errors.zip](https://github.com/linuxmint/cinnamon/files/3672074/home_xsession-errors.zip)


 ```

**Issue**
Middle click on titlebar lowers/minimizes the window.
I downloaded dconf-editor and the default value is 'none' and yet it doesn't seem to work and middle clicking on titlebar still lowers/minimizes the window to the panel. Works on any program, including Firefox. Using the command in the first step to reproduce doesn't change anything and the window still get lowered/minimized.

**Steps to reproduce**
1. Use dconf-editor or type in terminal "gsettings set org.gnome.desktop.wm.preferences action-middle-click-titlebar 'none' " in order to disable middle click.
2. Middle click on titlebar of any window that has such a bar. The window goes down directly.

**Expected behaviour**
Using the default setting (which is 'none') shouldn't lower/minimize the window.

**Other information**
Kernel version is 5.3.1 - in case you need it.

**Comment by smurphos** [comment]
You could always just use the Cinnamon GUI to change the setting. Windows settings module Titlebar tab.

![screenshot-window-2019-09-30-191817](https://user-images.githubusercontent.com/29017677/65904825-21607280-e3b7-11e9-9e88-c51c50c10bc5.png)

Or if you want to use dconf-editor or gsettings the correct key is `org.cinnamon.desktop.wm.preferences action-middle-click-titlebar`

![screenshot-window-2019-09-30-192129](https://user-images.githubusercontent.com/29017677/65904973-8d42db00-e3b7-11e9-9540-56a894faaec4.png)

**Comment by germanfr** [comment]
It won't work if it is a window with headerbars (GNOME-like, CSD). Related to linuxmint/muffin#528.

**Comment by IvoAndonov** [comment]
> You could always just use the Cinnamon GUI to change the setting. Windows settings module Titlebar tab.

I didn't know about that way, so thanks. But that begs for another bug report cuz apparently the GUI setting (menu "Windows") somehow overrides the default setting from dconf-editor which is "none". In menu "Windows" the default was "lower" until I changed it and it stopped happening. As I described above, I tried setting it to "none" through dconf-editor and it didn't work. Which only means that settings from menu "Windows" override/disregard the settings from dconf-editor.

**Comment by smurphos** [comment]
As per my original reply you are looking at the wrong key in dconf-editor. The correct key is 

`org.cinnamon.desktop.wm.preferences action-middle-click-titlebar`

not

`org.gnome.desktop.wm.preferences action-middle-click-titlebar`

The default for the former is lower.

**Comment by JosephMcc** [comment]
I think the problem here has been described and a solution provided.
