### ISSUE TITLE
System hang after bluetooth controller reconnect

### ISSUE THREAD

**Issue by howdev** [linuxmint/cinnamon#8881]
```
 * Cinnamon version (4.2.3)
   - Please specify if you are using the daily builds PPA (https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds).
 * Distribution - (19.2)
 * 64 bit
 ```

**Issue**
PS4 controller powersave auto disconnect. After resume connection. System freeze. require reboot

**Steps to reproduce**
Turn on PS4 controller connects using bluetooth with Steam running.
Wait for controller powersave auto turn off. 
Turn on controller pressing on button
After reconnect system hang. 
Not sure if happens everytime.

**Expected behaviour**
resume connection without freezing system

**Other information**
[bluetooth-controller.log](https://github.com/linuxmint/cinnamon/files/3680017/bluetooth-controller.log)

**Comment by icarter09** [comment]
@howdev have you tested this with other bluetooth items besides the PS4 controller?

**Comment by howdev** [comment]
yes I have been using other bluetooth devices like headset.

It seems the controller connection is working ok now with the Steam update

**Comment by icarter09** [comment]
@howdev thanks for the update. Do you think this issue can be closed now?

**Comment by howdev** [comment]
yes can be closed
