### ISSUE TITLE
Display scaling respect for QT

### ISSUE THREAD

**Issue by vladipus** [linuxmint/cinnamon#8887]
Shouldn't the HiDPI display scaling also repect QT applications? A keepassxc, for example doesn't work well for me, unless I also set QT_SCREEN_SCALE_FACTORS="2;2"

**Comment by leigh123linux** [comment]
Qt5 normally auto-detects this, if it isn't working it's Qt5 that's broken not cinnamon.

**Comment by vladipus** [comment]
I would argue that, since this is specifically related to 2x scaling in the Cinnamon's settings. That is, it doesn't work on many apps, actually, including the QT one. Steam, as an example, requires GDK_SCALE to be set explicity, before running. Why can't cinnamon itself set this value to 2?
