### ISSUE TITLE
GDK_SCALE is not set, when HiDPI scaling is used.

### ISSUE THREAD

**Issue by vladipus** [linuxmint/cinnamon#8888]
Even when the scaling is set in the settings, some apps (like Steam, and VLC) don't work as expected and require setting the GDK_SCALE=2 value, which is not very user-friendly. It would be great, if the Cinnamon's settings could set this variable itself, when using the 2x scaling.

**Comment by leigh123linux** [comment]
Steam uses gtk2 which doesn't support scaling and the same could apply to vlc if it's version 2, if its version 3 you need working Qt5 scaling.

**Comment by vladipus** [comment]
I can't understand why can't GDK_SCALE be set to 2, when the global scaling is set in the Settings.

**Comment by vladipus** [comment]
Steam actually supports the scaling. That's why the GDK_SCALE fixes the issue.

**Comment by clefebvre** [comment]
I can't reproduce this.. Steam looks tiny for me in HiDPI, with or without GDK_SCALE=2.

Also, this shouldn't affect GTK2 afaik.

**Comment by vladipus** [comment]
Make sure you have the correct command to run the client:
`sh -c 'STEAM_FRAME_FORCE_CLOSE=1 GDK_SCALE=2 steam' %U`

**Comment by omnicortex** [comment]
No solution?
