### ISSUE TITLE
Non-existent panel flashes when updating applets

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/cinnamon#8889]
```
 * Cinnamon version (cinnamon --version) 4.2.4
   - Please specify if you are using the daily builds PPA (https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds)
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 19.2
 * Graphics hardware *and* driver used: Intel 3rd Gen Core processor Graphics Controller
 * 32 or 64 bit: 64
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
 ```
[xsesh.txt](https://github.com/linuxmint/cinnamon/files/3698378/xsesh.txt)

**Issue**

When updating an applet, the wrong panel flashes when the update is complete. Or rather a non-existent panel flashes - a right-hand panel, which I used to have but no longer have. I do have top and bottom panels.

**Steps to reproduce**

Lack right panel - but, perhaps, add one and then remove it.
Update applet.

**Expected behaviour**

The correct panel area should flash.

**Other information**

I see the behaviour on two computers, both on Mint 19.2 Cinnamon.

**Comment by icarter09** [comment]
@LinuxOnTheDesktop does this occur with any applet that is receiving an update?

**Comment by LinuxOnTheDesktop** [comment]
I believe so. However, at present I have no applets that are non-current and so I cannot check.

**Comment by icarter09** [comment]
Thanks. I'll try to remember to check for this the next time I have one that needs updating.

**Comment by LinuxOnTheDesktop** [comment]
Well, thank you. But do please note the steps to reproduce that I gave above.

**Comment by claudiux** [comment]
@LinuxOnTheDesktop You can use Spices Update to request the renewal of some applets.

**Comment by LinuxOnTheDesktop** [comment]
@claudiux 

Thanks, but: I know; I use that applet - the applet that updates other applets - already; the reason I cannot test at the moment is that all my updates are up to date (and not that I lack a means of updating them).

**Comment by claudiux** [comment]
@LinuxOnTheDesktop Open the settings of Spices Update, then the Applets tab. Check both checkboxes of an applet then click on the refresh button.

**Comment by LinuxOnTheDesktop** [comment]
@Claudix: OK, I did that but again nothing happened and again I think the reason is that all my applets are up to date.

**Comment by LinuxOnTheDesktop** [comment]
As it happens, just now an update arrived via the Spices Update applet. I installed it, using Spices Update (or rather using Spices Update for the initial steps, which are the ones that it handles for the user). The update was for the Places applet. There was no erroneous flashing. So, perhaps, that flashing occurs only with particular updates. I seem to recall that most of my previous updates were for the Spices Update itself. So, that applet is a plausible candidate for being the cause of the problem.

**Comment by claudiux** [comment]
No, Spices Update isn't the cause of this problem: it uses the Cinnamon's mechanisms to install the Spices.

**Comment by claudiux** [comment]
OK, I understand what is causing your problem.

If you add an applet using a right-click on a panel and 'Add an applet...', then this panel is selected.

If you add an applet using System Settings -> Applets, your first panel (the one that was created when Cinnamon was first started) is selected. Spices Update uses this method.

In both cases, you can change of panel using the 'Previous Panel' and 'Next Panel' buttons of the Manage tab.

**Comment by LinuxOnTheDesktop** [comment]
Thanks, Claudix. Yet, I am unsure I understand. This bug report is about the flashing of a panel area when there is no panel there. For: I have a top panel and a bottom panel and no other panels (though in the past I had left and right panels in addition to top and bottom ones). When I add an applet to the top panel, the right panel flashes - or rather, the right-panel area flashes; for, there is no actual panel there. More accurately: I have at least sometimes seen this behaviour. Prompted by other contributions to this thread, I am trying to narrow down the circumstances under which the problem - the flashing of a _non-existent_ panel - occurs.

**Comment by claudiux** [comment]
@LinuxOnTheDesktop Can you copy here the contents of `/org/cinnamon/panels-enabled` using `dconf-editor`, please? The value is `['1:0:top', '2:0:bottom', '3:0:right']` for my Cinnamon 4.2.4.

**Comment by LinuxOnTheDesktop** [comment]
'Do not change your value'? What, after I have pasted it here? Or: ever?

The value I have is: `['1:0:top', '3:0:bottom']`

I have never edited those values by hand.

**Comment by claudiux** [comment]
Never, unless you want to swap 1 and 3 to swap your panels. (I have never done that.)

The panel 2 is missing. What happens when you click 3 times on the 'Next panel' button? Is the missing panel showing up?

**Comment by LinuxOnTheDesktop** [comment]
Thanks. It seems that Cinnamon has misnumbered my panels.

No, when I do that the missing panel does not show up.

Can you suggest a fix (for my immediate problem)?

**Comment by LinuxOnTheDesktop** [comment]
Let me add: I just installed (rather than updated) an applet, namely the Calendar applet - and the non-existent right-panel flashed.

**Comment by claudiux** [comment]
To suggest you a fix I need to know if, after adding a third panel, this one is named 2 or 4 in `/org/cinnamon/panels-enabled`.

**Comment by LinuxOnTheDesktop** [comment]
Thank you very much, claudiux. I added a left panel. Now the dconf line reads:

`['1:0:top', '3:0:bottom', '2:0:left']`

**Comment by claudiux** [comment]
OK. I will try to write a general fix. But if you want to solve your problem:

1. Enter in 'Panel Edit mode'.
2. Move all your applets from the bottom panel to the left panel.
3. Exit from  'Panel Edit mode'.
4. Remove your bottom panel.
5. Move your left panel to the bottom side.

**Comment by claudix** [comment]
Please, somebody mentioned my username accidentally from this thread and I'm getting notifications about it. Could you please remove my reference from your comments? Thank you!

**Comment by LinuxOnTheDesktop** [comment]
Clau**: I don't understand. Are you asking anyone who has posted in this thread to remove mentions of your username? I can do that. But aren't you getting notifications from this thread anyway, because you are one of the main participants in the thread?

I implemented your suggested fix. org-cinnamon-panels-enabled now reads: `['1:0:top', '2:0:bottom']` I added two applets to my top panel. On both occasions there was a flash - and a much wider one than before - from, again, a non-existent right-panel. (The 'next panel' procedure reveals only two panels.)

I note also the following. After I first added the left panel (well, first added it as a result of discussion in this thread), my bottom panel stopped hiding - or rather showing - properly. That is: when the bottom panel was set to 'intelligently hide' or to 'auto-hide', when some applications were maximised, the panel would not appear. (And, previously, that problem had not existed.) Having applied your attempted fix and removed the left panel and restarted the computer, that problem seems gone.

**Comment by claudix** [comment]
I'm not! My username is "claudix" but there's somebody here called "claudiux"! Somebody misspelled the latter username in a comment 😁

**Comment by claudiux** [comment]
@LinuxOnTheDesktop I forgot the step:

6. Reload Cinnamon or Log off/Log on.

(For claudix, edit this comment: https://github.com/linuxmint/cinnamon/issues/8889#issuecomment-549566026.)

**Comment by claudiux** [comment]
Aaaargh! I can't reproduce this issue on my own computer. I'll try on a virtual machine...

Is your ghost panel really flashing? (How many times?). Or just changing of colour until you close the Settings window?

**Comment by LinuxOnTheDesktop** [comment]
Yes: flashing, i.e. a vertical bar appears, persists for perhaps a third of a second, and then disappears. And that happens only once. The vertical bar is undifferentiated, i.e. has nothing on it and seems uniform in colour (though perhaps there is some shading).

**Comment by LinuxOnTheDesktop** [comment]
An update: I created a new user account (because something messed up the old one); the new user account has never had a right panel (and I did not copy dconf or, to my knowledge, cinnamon settings from one user to the other); when adding an applet a non-existent right panel still flashes.

**Comment by claudiux** [comment]
I don't know what is the source of this problem.

**Comment by LinuxOnTheDesktop** [comment]
The problem persists in Mint 19.3.

**Comment by LinuxOnTheDesktop** [comment]
The problem persists on Mint 20 - at least on one machine (that was upgraded from Mint 19.3). I will check with other computers.

**Comment by LinuxOnTheDesktop** [comment]
I have not seen this problem, on either of my Mint PCs, with Mint 20.2 (or indeed, perhaps, Mint 20.1). So: closing.
