### ISSUE TITLE
Alt+F2 command prompt doesn't know of executables

### ISSUE THREAD

**Issue by dtrunk90** [linuxmint/Cinnamon#889]
I just downloaded Eclipse for JavaEE Developers, unpacked it into ~/.bin/eclipse and added this into the path environment variable:

```
$ echo $PATH
/usr/lib/lightdm/lightdm:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/home/danny/.bin:/home/danny/.bin/android-sdk-linux/tools:/home/danny/.bin/android-sdk-linux/platform-tools:/home/danny/.bin/eclipse
```

Running eclipse from terminal works great, but trying to run from the Alt+F2 command prompt it just says "Command not found".

EDIT: Running Cinnamon 1.4 on Ubuntu 12.04

**Comment by eliasdorneles** [comment]
I have the same problem, and defining in ~/.profile doesn't help. =/

Have been trying to debug this since several days, can't seem to figure out.
Any idea on where I could look into the code for the Run dialog thing?

Cinnamon 2.8.8 here.

**Comment by eliasdorneles** [comment]
To be clear, it only fails for things I have in `~/bin`.

I've created a simple `itworks` file and placed into `~/bin` and another `globalitworks` into `/usr/bin`, both just open `zenity` showing a message.
I've tried several combinations (.profile, .bash_profile, only one, only the other, both) and none of that works.

**Comment by eliasdorneles** [comment]
So, I finally got it working by switching `/bin/sh` symbolic link to point to `/bin/bash` instead of `/bin/dash`.
Sadly, no better workaround than this.
