### ISSUE TITLE
sudo apt-get install "The list of sources could not be read."

### ISSUE THREAD

**Issue by kichererbsen** [linuxmint/cinnamon#8890]
* Cinnamon version - Cinnamon 4.2.3
 * Distribution - mint 19.2
 * 64 bit
 

I was trying to download programs using the command line, but it wasnt working, i ran sudo apt-get update and got this 

E: Malformed line 2 in source list /etc/apt/sources.list.d/riot-im.list (type)
E: The list of sources could not be read.

the software manager (i guess its related to this) opens, but then just says 'generating cache, one moment' which just stays like that

i opened the program 'software sources' from the menu, and when i change something, it says i should update the APT cache, when i click okay it says 

'Failed to load the package list

This is a serious problem. Try again later. If this problem appears again, please report an error to the developers.'
more details
E:Malformed line 2 in source list /etc/apt/sources.list.d/riot-im.list (type), E:The list of sources could not be read.'

from what i understand, theres a error in the sources list, i tried looking online about how to remake the sources list, but either didnt understand or could not get it to work (commands produced errors/not understood)

this error is new - i only installed mint last week, and the command line for programs did work for at least a few days
i was trying to download Riot messanger the other day, it didnt work, but i guess the 'riot-im' part in the sources list is referring to this program, i dont know why exactly

does anyone have any advice? would be greatly appreciated!

**Comment by leigh123linux** [comment]
Try asking on linuxmint forum.

**Comment by clefebvre** [comment]
The error is visible in the output:

`E:Malformed line 2 in source list /etc/apt/sources.list.d/riot-im.list`

Fixing or removing that line should solve the issue.
