### ISSUE TITLE
[Feature request] More friendly Workspaces

### ISSUE THREAD

**Issue by Pance21** [linuxmint/cinnamon#8892]
```
 * Cinnamon version (cinnamon --version)
   - Please specify if you are using the daily builds PPA (https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds).
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
 * Graphics hardware *and* driver used
 * 32 or 64 bit
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
 ```

I'm using Mint 19.2 (64 bit) ... and recently I thought about using Workspaces. Let me explain, I'm a freelance programmer, and I would like to setup work for each of my clients in different Workspaces. Ideally, each Workspace should have it's own desktop background, and programs that already have workspace concepts built-in, should work with the global Desktop Workspaces. For example, the text editor Geany uses "Projects", and when I open it in Workspace 1, all is fine. But when I open Geany in Workspace 2, it cannot find the last project. I have to manually select the project. The same issue with Visual Studio Code... it opens fine with the most recent Workspace in Workspace 1. But when I open VSC in Workspace 2, there is no default VSC workspace. Very frustrating.

Ideally, I would like Workspaces to be more customizable, with their own settings, and remember those settings inbetween reboots.

Thanks

Pance.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
