### ISSUE TITLE
[FR] Please to add settings for cinnamon control center to control redshift.

### ISSUE THREAD

**Issue by pyroxar** [linuxmint/cinnamon#8895]
Linux Mint attach the redshift as default application to adjustment of the screen in night.
Redshift have only basic options to control himself (I mean app indicator): enable/disable, suspend for, auto start. 
![obraz](https://user-images.githubusercontent.com/23406555/66482500-5f3e5480-eaa3-11e9-8a14-353bbe265d1c.png)

Cinnamon should have settings of a redshift in the cinnamon control center based on opportunities a redshift to control it.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
