### ISSUE TITLE
Rise of the Tomb Raider has a transparent border in fullscreen

### ISSUE THREAD

**Issue by logan001** [linuxmint/cinnamon#8900]
```
 * Cinnamon version 4.2.4
 * Distribution  Arch
 * Graphics nvidia 970 driver 435.27.00
 * 64 bit
 * xsession-errors has the same two lines every time i start the game

> Cinnamon warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x8c00027 (Rise of th)
> Cinnamon warning: Treating resize request of legacy application 0x8c00027 (Rise of th) as a fullscreen request

 ```

**Issue**
As the title says: the game have a 2 pixel right and bottom transparent border as in i can see the desktop background image. there is no task bar in the border just the background.

![Screenshot_20191012_174452](https://user-images.githubusercontent.com/6472378/66703149-23f88b80-ed18-11e9-9acc-6357eaea1823.png)

**Steps to reproduce**
Start steam run Rise of the Tomb Raider

**Expected behaviour**
To go full screen 1920x1080

**Other information**
Use to work without an issue
KDE has no issue full screen.

**Comment by smurphos** [comment]
Hi this is a duplicate of https://github.com/linuxmint/muffin/issues/530

@logan001 - there are workarounds outlined in the linked iasue.

**Comment by logan001** [comment]
yeap seems to be the same issue and the workaround is working
thank you
