### ISSUE TITLE
Feature request: button on window titlebar to send to another monitor

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/cinnamon#8901]
**Feature request**

Please consider having by default, or at least allowing the user to add, a button on the titlebar of any given window that sends the window to another monitor. I discover that there are keyboard shortcuts to do such things but others may not be aware of these (as I was not) and even if they are they may forget the key combination. Surely users should be helped to avoid the floundering around that can occur with multi-monitor setups.

**Other information**

I think that Windows - and other Linux DEs? - implement this feature already.

I tried to post this request in the 'ideas' section of the community website but, even after logging in, I could search existing ideas but not find a way to create a new idea.

**Comment by JosephMcc** [comment]
Thanks for the request but I doubt you will see this one. We will likely make the move to using the gtk theme to draw window borders at some point and this won't really be doable.

**Comment by LinuxOnTheDesktop** [comment]
Ah. So, no DEs that work like that - that use GTK themes to draw borders - have or allow the 'send to other monitor' option? Perhaps they do not.
