### ISSUE TITLE
If you change theme to new, then new theme isn't installed for flatpak apps

### ISSUE THREAD

**Issue by pyroxar** [linuxmint/cinnamon#8906]
```
 * Distribution - GNU/Linux Mint 19.2
 ```

**Issue**
If you change theme to new, then new theme isn't installed for flatpak apps. You must install another new app form flathub by mintinstaller to install the new theme.

**Steps to reproduce**
Install app from faltub.
Change theme.
App will use default theme because new theme is not installed.

**Expected behaviour**

**Other information**
![obraz](https://user-images.githubusercontent.com/23406555/67016142-05b7d480-f0f8-11e9-81ca-a7c73cc9ff96.png)
![obraz](https://user-images.githubusercontent.com/23406555/67016072-e1f48e80-f0f7-11e9-8e77-319defe0f2d6.png)
![obraz](https://user-images.githubusercontent.com/23406555/67015619-13208f00-f0f7-11e9-8689-a48d91ab589c.png)
![obraz](https://user-images.githubusercontent.com/23406555/67015804-68f53700-f0f7-11e9-8a39-b20937fe2c4f.png)

**Comment by clefebvre** [comment]
True, though it would be overkill to update flatpak on theme change. This is a limitation with the current design.
