### ISSUE TITLE
Linux Mint 19.1 Will not Shutdown or Restart

### ISSUE THREAD

**Issue by nohad123** [linuxmint/cinnamon#8908]
```
 * Cinnamon version (cinnamon --version) 4.2.4
   - Please specify if you are using the daily builds PPA (https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds).
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 19.2
 * Graphics hardware *and* driver used Intel© Core™ i7-8565U CPU @ 1.80GHz × 4, Intel Corporation Device 3ea0 (prog-if 00 [VGA controller])
 * 32 or 64 bit 64 bit
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
 ```
sudo lshw
[sudo] password for nohad:           
nohad-blade-stealth         
    description: Notebook
    product: Blade Stealth (RZ09-02812W52)
    vendor: Razer
    version: 1.04
    serial: BY1909A57601490
    width: 64 bits
    capabilities: smbios-3.2 dmi-3.2 smp vsyscall32
    configuration: boot=normal chassis=notebook family=1A581000 Razer Blade Stealth sku=RZ09-02812W52 uuid=33386665-3638-3763-3464-393234333663
  *-core
       description: Motherboard
       product: LY310
       vendor: Razer
       physical id: 0
     *-firmware
          description: BIOS
          vendor: Razer
          physical id: 0
          version: 1.02
          date: 01/09/2019
          size: 64KiB
          capacity: 15MiB
          capabilities: pci upgrade shadowing cdboot bootselect socketedrom edd int13floppy1200 int13floppy720 int13floppy2880 int5printscreen int14serial int17printer acpi usb biosbootspecification uefi
     *-memory
          description: System Memory
          physical id: 23
          slot: System board or motherboard
          size: 16GiB
        *-bank:0
             description: Row of chips LPDDR3 Synchronous 2133 MHz (0.5 ns)
             product: K4EBE304EB-EGCG
             vendor: Samsung
             physical id: 0
             serial: 55000000
             slot: ChannelA-DIMM0
             size: 8GiB
             width: 64 bits
             clock: 2133MHz (0.5ns)
        *-bank:1
             description: Row of chips LPDDR3 Synchronous 2133 MHz (0.5 ns)
             product: K4EBE304EB-EGCG
             vendor: Samsung
             physical id: 1
             serial: 55000000
             slot: ChannelB-DIMM0
             size: 8GiB
             width: 64 bits
             clock: 2133MHz (0.5ns)
     *-cache:0
          description: L1 cache
          physical id: 2d
          slot: L1 Cache
          size: 256KiB
          capacity: 256KiB
          capabilities: synchronous internal write-back unified
          configuration: level=1
     *-cache:1
          description: L2 cache
          physical id: 2e
          slot: L2 Cache
          size: 1MiB
          capacity: 1MiB
          capabilities: synchronous internal write-back unified
          configuration: level=2
     *-cache:2
          description: L3 cache
          physical id: 2f
          slot: L3 Cache
          size: 8MiB
          capacity: 8MiB
          capabilities: synchronous internal write-back unified
          configuration: level=3
     *-cpu
          description: CPU
          product: Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
          vendor: Intel Corp.
          physical id: 30
          bus info: cpu@0
          version: Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
          slot: U3E1
          size: 3200MHz
          capacity: 4600MHz
          width: 64 bits
          clock: 100MHz
          capabilities: x86-64 fpu fpu_exception wp vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d arch_capabilities cpufreq
          configuration: cores=4 enabledcores=4 threads=8
     *-pci
          description: Host bridge
          product: Intel Corporation
          vendor: Intel Corporation
          physical id: 100
          bus info: pci@0000:00:00.0
          version: 0b
          width: 32 bits
          clock: 33MHz
        *-display
             description: VGA compatible controller
             product: Intel Corporation
             vendor: Intel Corporation
             physical id: 2
             bus info: pci@0000:00:02.0
             version: 00
             width: 64 bits
             clock: 33MHz
             capabilities: pciexpress msi pm vga_controller bus_master cap_list rom
             configuration: driver=i915 latency=0
             resources: irq:147 memory:ab000000-abffffff memory:40000000-4fffffff ioport:4000(size=64) memory:c0000-dffff
        *-generic:0
             description: Signal processing controller
             product: Xeon E3-1200 v5/E3-1500 v5/6th Gen Core Processor Thermal Subsystem
             vendor: Intel Corporation
             physical id: 4
             bus info: pci@0000:00:04.0
             version: 0b
             width: 64 bits
             clock: 33MHz
             capabilities: msi pm cap_list
             configuration: driver=proc_thermal latency=0
             resources: irq:16 memory:ad310000-ad317fff
        *-generic:1
             description: Signal processing controller
             product: Intel Corporation
             vendor: Intel Corporation
             physical id: 12
             bus info: pci@0000:00:12.0
             version: 30
             width: 64 bits
             clock: 33MHz
             capabilities: pm msi cap_list
             configuration: driver=intel_pch_thermal latency=0
             resources: irq:16 memory:ad327000-ad327fff
        *-usb
             description: USB controller
             product: Intel Corporation
             vendor: Intel Corporation
             physical id: 14
             bus info: pci@0000:00:14.0
             version: 30
             width: 64 bits
             clock: 33MHz
             capabilities: pm msi xhci bus_master cap_list
             configuration: driver=xhci_hcd latency=0
             resources: irq:127 memory:ad300000-ad30ffff
           *-usbhost:0
                product: xHCI Host Controller
                vendor: Linux 5.0.0-31-generic xhci-hcd
                physical id: 0
                bus info: usb@1
                logical name: usb1
                version: 5.00
                capabilities: usb-2.00
                configuration: driver=hub slots=12 speed=480Mbit/s
              *-usb:0
                   description: USB hub
                   product: USB2.0 Hub
                   vendor: VIA Labs, Inc.
                   physical id: 1
                   bus info: usb@1:1
                   version: 3.b4
                   capabilities: usb-2.10
                   configuration: driver=hub slots=4 speed=480Mbit/s
                 *-usb:0
                      description: USB hub
                      product: USB 2.0 Hub
                      vendor: Terminus Technology Inc.
                      physical id: 2
                      bus info: usb@1:1.2
                      version: 1.11
                      capabilities: usb-2.00
                      configuration: driver=hub maxpower=100mA slots=4 speed=480Mbit/s
                    *-usb
                         description: Audio device
                         product: USB PnP Audio Device
                         vendor: JMTek, LLC.
                         physical id: 3
                         bus info: usb@1:1.2.3
                         version: 1.00
                         capabilities: usb-1.10 audio-control
                         configuration: driver=usbhid maxpower=100mA speed=12Mbit/s
                 *-usb:1
                      description: Audio device
                      product: Razer Nari
                      vendor: Razer
                      physical id: 4
                      bus info: usb@1:1.4
                      version: 1.00
                      capabilities: usb-1.10 audio-control
                      configuration: driver=usbhid maxpower=100mA speed=12Mbit/s
              *-usb:1
                   description: USB hub
                   product: USB2.0 Hub
                   vendor: VIA Labs, Inc.
                   physical id: 2
                   bus info: usb@1:2
                   version: d.a0
                   capabilities: usb-2.10
                   configuration: driver=hub slots=4 speed=480Mbit/s
                 *-usb:0
                      description: USB hub
                      product: USB2.0 Hub
                      vendor: VIA Labs, Inc.
                      physical id: 2
                      bus info: usb@1:2.2
                      version: d.a0
                      capabilities: usb-2.10
                      configuration: driver=hub slots=4 speed=480Mbit/s
                    *-usb:0
                         description: Mass storage device
                         product: External HDD
                         vendor: Western Digital
                         physical id: 1
                         bus info: usb@1:2.2.1
                         logical name: scsi1
                         version: 1.75
                         serial: 57442D575846304135393036313335
                         capabilities: usb-2.00 scsi emulated scsi-host
                         configuration: driver=usb-storage maxpower=2mA speed=480Mbit/s
                       *-disk
                            description: SCSI Disk
                            product: 5000BEV External
                            vendor: WD
                            physical id: 0.0.0
                            bus info: scsi@1:0.0.0
                            logical name: /dev/sdb
                            version: 1.75
                            serial: WD-WXF0A5906135
                            size: 465GiB (500GB)
                            capabilities: partitioned partitioned:dos
                            configuration: ansiversion=4 logicalsectorsize=512 sectorsize=512 signature=000c7a46
                          *-volume
                               description: HPFS/NTFS partition
                               physical id: 1
                               bus info: scsi@1:0.0.0,1
                               logical name: /dev/sdb1
                               capacity: 465GiB
                               capabilities: primary bootable
                    *-usb:1
                         description: Mouse
                         product: Razer Lancehead Tournament Edition
                         vendor: Razer
                         physical id: 2
                         bus info: usb@1:2.2.2
                         version: 2.00
                         capabilities: usb-2.00
                         configuration: driver=usbhid maxpower=500mA speed=12Mbit/s
                    *-usb:2
                         description: Mouse
                         product: Razer Firefly
                         vendor: Razer
                         physical id: 3
                         bus info: usb@1:2.2.3
                         version: 2.00
                         capabilities: usb-2.00
                         configuration: driver=usbhid maxpower=500mA speed=12Mbit/s
                 *-usb:1
                      description: Keyboard
                      product: Razer BlackWidow
                      vendor: Razer
                      physical id: 4
                      bus info: usb@1:2.4
                      version: 2.00
                      capabilities: usb-2.00
                      configuration: driver=usbhid maxpower=500mA speed=12Mbit/s
              *-usb:2
                   description: Mass storage device
                   product: USB DISK 2.0
                   physical id: 3
                   bus info: usb@1:3
                   logical name: scsi0
                   version: 1.00
                   serial: 07AA08011D51D611
                   capabilities: usb-2.00 scsi emulated scsi-host
                   configuration: driver=usb-storage maxpower=200mA speed=480Mbit/s
                 *-disk
                      description: SCSI Disk
                      product: USB DISK 2.0
                      physical id: 0.0.0
                      bus info: scsi@0:0.0.0
                      logical name: /dev/sda
                      version: PMAP
                      size: 7640MiB (8011MB)
                      capabilities: removable
                      configuration: logicalsectorsize=512 sectorsize=512
                    *-medium
                         physical id: 0
                         logical name: /dev/sda
                         size: 7640MiB (8011MB)
              *-usb:3
                   description: Video
                   product: Integrated Camera
                   vendor: Azurewave
                   physical id: 6
                   bus info: usb@1:6
                   version: 18.13
                   serial: 200901010001
                   capabilities: usb-2.01
                   configuration: driver=uvcvideo maxpower=500mA speed=480Mbit/s
              *-usb:4
                   description: Keyboard
                   product: Razer Blade
                   vendor: Razer
                   physical id: 8
                   bus info: usb@1:8
                   version: 2.00
                   capabilities: usb-2.00
                   configuration: driver=usbhid maxpower=500mA speed=12Mbit/s
              *-usb:5
                   description: Human interface device
                   product: Touchscreen
                   vendor: ELAN
                   physical id: 9
                   bus info: usb@1:9
                   version: 57.02
                   capabilities: usb-2.00
                   configuration: driver=usbhid maxpower=100mA speed=12Mbit/s
              *-usb:6
                   description: Bluetooth wireless interface
                   vendor: Intel Corp.
                   physical id: a
                   bus info: usb@1:a
                   version: 0.02
                   capabilities: bluetooth usb-2.00
                   configuration: driver=btusb maxpower=100mA speed=12Mbit/s
           *-usbhost:1
                product: xHCI Host Controller
                vendor: Linux 5.0.0-31-generic xhci-hcd
                physical id: 1
                bus info: usb@2
                logical name: usb2
                version: 5.00
                capabilities: usb-3.00
                configuration: driver=hub slots=6 speed=5000Mbit/s
              *-usb:0
                   description: USB hub
                   product: USB3.0 Hub
                   vendor: VIA Labs, Inc.
                   physical id: 1
                   bus info: usb@2:1
                   version: 3.b4
                   capabilities: usb-3.10
                   configuration: driver=hub slots=4 speed=5000Mbit/s
                 *-usb
                      description: Generic USB device
                      product: USB 10/100/1000 LAN
                      vendor: Realtek
                      physical id: 3
                      bus info: usb@2:1.3
                      version: 30.00
                      serial: 000001
                      capabilities: usb-3.00
                      configuration: driver=r8152 maxpower=288mA speed=5000Mbit/s
              *-usb:1
                   description: USB hub
                   product: USB3.0 Hub
                   vendor: VIA Labs, Inc.
                   physical id: 2
                   bus info: usb@2:2
                   version: d.a5
                   capabilities: usb-3.00
                   configuration: driver=hub slots=4 speed=5000Mbit/s
                 *-usb:0
                      description: Generic USB device
                      product: Dell USB3.0 Dock
                      vendor: DisplayLink
                      physical id: 1
                      bus info: usb@2:2.1
                      version: 31.05
                      serial: 1409100014B
                      capabilities: usb-3.20
                      configuration: driver=usbfs maxpower=8mA speed=5000Mbit/s
                 *-usb:1
                      description: USB hub
                      product: USB3.0 Hub
                      vendor: VIA Labs, Inc.
                      physical id: 2
                      bus info: usb@2:2.2
                      version: d.a5
                      capabilities: usb-3.00
                      configuration: driver=hub slots=4 speed=5000Mbit/s
                 *-usb:2
                      description: Audio device
                      product: Dell USB3.0 Dock
                      vendor: DisplayLink
                      physical id: 3
                      bus info: usb@2:2.3
                      version: 31.05
                      serial: 1409100014
                      capabilities: usb-3.20 audio-control
                      configuration: driver=cdc_ncm maxpower=8mA speed=5000Mbit/s
        *-memory UNCLAIMED
             description: RAM memory
             product: Intel Corporation
             vendor: Intel Corporation
             physical id: 14.2
             bus info: pci@0000:00:14.2
             version: 30
             width: 64 bits
             clock: 33MHz (30.3ns)
             capabilities: pm cap_list
             configuration: latency=0
             resources: memory:ad320000-ad321fff memory:ad326000-ad326fff
        *-network DISABLED
             description: Wireless interface
             product: Intel Corporation
             vendor: Intel Corporation
             physical id: 14.3
             bus info: pci@0000:00:14.3
             logical name: wlo1
             version: 30
             serial: d4:3b:04:04:ea:52
             width: 64 bits
             clock: 33MHz
             capabilities: pm msi pciexpress msix bus_master cap_list ethernet physical wireless
             configuration: broadcast=yes driver=iwlwifi driverversion=5.0.0-31-generic firmware=43.95eb4e97.0 latency=0 link=no multicast=yes wireless=IEEE 802.11
             resources: irq:16 memory:ad31c000-ad31ffff
        *-serial:0
             description: Serial bus controller
             product: Intel Corporation
             vendor: Intel Corporation
             physical id: 15
             bus info: pci@0000:00:15.0
             version: 30
             width: 64 bits
             clock: 33MHz
             capabilities: pm bus_master cap_list
             configuration: driver=intel-lpss latency=0
             resources: irq:16 memory:72000000-72000fff
        *-serial:1
             description: Serial bus controller
             product: Intel Corporation
             vendor: Intel Corporation
             physical id: 15.1
             bus info: pci@0000:00:15.1
             version: 30
             width: 64 bits
             clock: 33MHz
             capabilities: pm bus_master cap_list
             configuration: driver=intel-lpss latency=0
             resources: irq:17 memory:72001000-72001fff
        *-communication
             description: Communication controller
             product: Intel Corporation
             vendor: Intel Corporation
             physical id: 16
             bus info: pci@0000:00:16.0
             version: 30
             width: 64 bits
             clock: 33MHz
             capabilities: pm msi bus_master cap_list
             configuration: driver=mei_me latency=0
             resources: irq:156 memory:ad323000-ad323fff
        *-pci:0
             description: PCI bridge
             product: Intel Corporation
             vendor: Intel Corporation
             physical id: 1c
             bus info: pci@0000:00:1c.0
             version: f0
             width: 32 bits
             clock: 33MHz
             capabilities: pci pciexpress msi pm normal_decode bus_master cap_list
             configuration: driver=pcieport
             resources: irq:122
        *-pci:1
             description: PCI bridge
             product: Intel Corporation
             vendor: Intel Corporation
             physical id: 1c.4
             bus info: pci@0000:00:1c.4
             version: f0
             width: 32 bits
             clock: 33MHz
             capabilities: pci pciexpress msi pm normal_decode bus_master cap_list
             configuration: driver=pcieport
             resources: irq:123 ioport:3000(size=4096) memory:ac000000-ad0fffff ioport:80000000(size=301989888)
           *-display
                description: 3D controller
                product: GP108M [GeForce MX150]
                vendor: NVIDIA Corporation
                physical id: 0
                bus info: pci@0000:02:00.0
                version: a1
                width: 64 bits
                clock: 33MHz
                capabilities: pm msi pciexpress cap_list rom
                configuration: driver=nouveau latency=0
                resources: irq:146 memory:ac000000-acffffff memory:80000000-8fffffff memory:90000000-91ffffff ioport:3000(size=128) memory:ad000000-ad07ffff
        *-pci:2
             description: PCI bridge
             product: Intel Corporation
             vendor: Intel Corporation
             physical id: 1d
             bus info: pci@0000:00:1d.0
             version: f0
             width: 32 bits
             clock: 33MHz
             capabilities: pci pciexpress msi pm normal_decode bus_master cap_list
             configuration: driver=pcieport
             resources: irq:124 ioport:5000(size=8192) memory:94000000-aa0fffff ioport:50000000(size=570425344)
           *-pci
                description: PCI bridge
                product: JHL6340 Thunderbolt 3 Bridge (C step) [Alpine Ridge 2C 2016]
                vendor: Intel Corporation
                physical id: 0
                bus info: pci@0000:03:00.0
                version: 02
                width: 32 bits
                clock: 33MHz
                capabilities: pci pm msi pciexpress normal_decode bus_master cap_list
                configuration: driver=pcieport
                resources: irq:16 ioport:5000(size=4096) memory:94000000-aa0fffff ioport:50000000(size=570425344)
              *-pci:0
                   description: PCI bridge
                   product: JHL6340 Thunderbolt 3 Bridge (C step) [Alpine Ridge 2C 2016]
                   vendor: Intel Corporation
                   physical id: 0
                   bus info: pci@0000:04:00.0
                   logical name: /dev/fb0
                   version: 02
                   width: 64 bits
                   clock: 33MHz
                   capabilities: pci pm msi pciexpress normal_decode bus_master cap_list fb
                   configuration: depth=32 driver=pcieport mode=3840x2160 visual=truecolor xres=3840 yres=2160
                   resources: iomemory:1f10-1f0f irq:16 memory:aa000000-aa0fffff
                 *-generic
                      description: System peripheral
                      product: JHL6340 Thunderbolt 3 NHI (C step) [Alpine Ridge 2C 2016]
                      vendor: Intel Corporation
                      physical id: 0
                      bus info: pci@0000:05:00.0
                      version: 02
                      width: 32 bits
                      clock: 33MHz
                      capabilities: pm msi pciexpress msix bus_master cap_list
                      configuration: driver=thunderbolt latency=0
                      resources: irq:16 memory:aa000000-aa03ffff memory:aa040000-aa040fff
              *-pci:1
                   description: PCI bridge
                   product: JHL6340 Thunderbolt 3 Bridge (C step) [Alpine Ridge 2C 2016]
                   vendor: Intel Corporation
                   physical id: 1
                   bus info: pci@0000:04:01.0
                   version: 02
                   width: 64 bits
                   clock: 33MHz
                   capabilities: pci pm msi pciexpress normal_decode bus_master cap_list
                   configuration: driver=pcieport
                   resources: iomemory:51510-5150f irq:126 ioport:5000(size=4096) memory:94000000-a9efffff ioport:50000000(size=570425344)
              *-pci:2
                   description: PCI bridge
                   product: JHL6340 Thunderbolt 3 Bridge (C step) [Alpine Ridge 2C 2016]
                   vendor: Intel Corporation
                   physical id: 2
                   bus info: pci@0000:04:02.0
                   version: 02
                   width: 64 bits
                   clock: 33MHz
                   capabilities: pci pm msi pciexpress normal_decode bus_master cap_list
                   configuration: driver=pcieport
                   resources: iomemory:1f10-1f0f irq:18 memory:a9f00000-a9ffffff
                 *-usb
                      description: USB controller
                      product: Intel Corporation
                      vendor: Intel Corporation
                      physical id: 0
                      bus info: pci@0000:3b:00.0
                      version: 02
                      width: 32 bits
                      clock: 33MHz
                      capabilities: pm msi pciexpress xhci cap_list
                      configuration: driver=xhci_hcd latency=0
                      resources: irq:128 memory:a9f00000-a9f0ffff
                    *-usbhost:0
                         product: xHCI Host Controller
                         vendor: Linux 5.0.0-31-generic xhci-hcd
                         physical id: 0
                         bus info: usb@3
                         logical name: usb3
                         version: 5.00
                         capabilities: usb-2.00
                         configuration: driver=hub slots=2 speed=480Mbit/s
                    *-usbhost:1
                         product: xHCI Host Controller
                         vendor: Linux 5.0.0-31-generic xhci-hcd
                         physical id: 1
                         bus info: usb@4
                         logical name: usb4
                         version: 5.00
                         capabilities: usb-3.00
                         configuration: driver=hub slots=2 speed=5000Mbit/s
        *-pci:3
             description: PCI bridge
             product: Intel Corporation
             vendor: Intel Corporation
             physical id: 1d.4
             bus info: pci@0000:00:1d.4
             version: f0
             width: 32 bits
             clock: 33MHz
             capabilities: pci pciexpress msi pm normal_decode bus_master cap_list
             configuration: driver=pcieport
             resources: irq:125 memory:ad200000-ad2fffff
           *-storage
                description: Non-Volatile memory controller
                product: Lite-On Technology Corporation
                vendor: Lite-On Technology Corporation
                physical id: 0
                bus info: pci@0000:3c:00.0
                version: 01
                width: 64 bits
                clock: 33MHz
                capabilities: storage pm msi pciexpress msix nvm_express bus_master cap_list
                configuration: driver=nvme latency=0
                resources: irq:16 memory:ad200000-ad203fff
        *-isa
             description: ISA bridge
             product: Intel Corporation
             vendor: Intel Corporation
             physical id: 1f
             bus info: pci@0000:00:1f.0
             version: 30
             width: 32 bits
             clock: 33MHz
             capabilities: isa bus_master
             configuration: latency=0
        *-multimedia
             description: Audio device
             product: Intel Corporation
             vendor: Intel Corporation
             physical id: 1f.3
             bus info: pci@0000:00:1f.3
             version: 30
             width: 64 bits
             clock: 33MHz
             capabilities: pm msi bus_master cap_list
             configuration: driver=snd_hda_intel latency=32
             resources: irq:167 memory:ad318000-ad31bfff memory:ad100000-ad1fffff
        *-serial:2 UNCLAIMED
             description: SMBus
             product: Intel Corporation
             vendor: Intel Corporation
             physical id: 1f.4
             bus info: pci@0000:00:1f.4
             version: 30
             width: 64 bits
             clock: 33MHz
             configuration: latency=0
             resources: memory:ad322000-ad3220ff ioport:efa0(size=32)
        *-serial:3 UNCLAIMED
             description: Serial bus controller
             product: Intel Corporation
             vendor: Intel Corporation
             physical id: 1f.5
             bus info: pci@0000:00:1f.5
             version: 30
             width: 32 bits
             clock: 33MHz
             configuration: latency=0
             resources: memory:fe010000-fe010fff
  *-power UNCLAIMED
       physical id: 1
  *-network:0
       description: Ethernet interface
       physical id: 2
       logical name: enx34298f746bcc
       serial: 34:29:8f:74:6b:cc
       size: 10Mbit/s
       capacity: 1Gbit/s
       capabilities: ethernet physical tp mii 10bt 10bt-fd 100bt 100bt-fd 1000bt 1000bt-fd autonegotiation
       configuration: autonegotiation=on broadcast=yes driver=r8152 driverversion=v1.09.9 duplex=half link=no multicast=yes port=MII speed=10Mbit/s
  *-network:1
       description: Ethernet interface
       physical id: 3
       logical name: enx9cebe817d41f
       serial: 9c:eb:e8:17:d4:1f
       capabilities: ethernet physical
       configuration: broadcast=yes driver=cdc_ncm driverversion=22-Aug-2005 firmware=CDC NCM ip=192.168.0.107 link=yes multicast=yes

**Issue**
In the last couple of iterations my lap top will not shutdown nor will it reboot.  Have to manually press the off button.

**Steps to reproduce**
Reproduce on my hardware only.
Not an intermittent problem but a permanent problem.

**Expected behaviour**
Laptop should shut down/reboot properly using the appropriate buttons.

**Other information**
Razer Lap Top
[syslog.txt](https://github.com/linuxmint/cinnamon/files/3743718/syslog.txt)
[xsession-errors.txt](https://github.com/linuxmint/cinnamon/files/3743731/xsession-errors.txt)

**Comment by N1vBruno** [comment]
I'm not a developer nor do I speak for anyone at Linux Mint, but as an average user I think this is specific to you and not an issue with Cinnamon (could be something you installed or have setting up, idk). You should try to search for help in [Mint](https://forums.linuxmint.com/) or others forums.

But maybe an update to Mint 19.2 and/or to a newer kernel (if available in Mint repositories) could fix your problem.

And as a workaround you could try these commands in terminal: **shutdown now** and **shutdown -r now** (this one for rebooting), so maybe you don't have to press the off button.

**Comment by icarter09** [comment]
@nohad123 did @N1vBruno suggestion of using the terminal cmds provide a work-around for you? I agree that an upgrade would be in your best interest to solve this problem as well.

**Comment by nohad123** [comment]
Hello, neither of the terminal commands work.  Sorry for my mistake but I am on 19.2.  This problem only started happening with the latest software and latest kernels.  I think it was after a Kernel update that it started but I did not make a note of the Kernel number.  I have been using Linux Mint for years without this issue.

**Comment by icarter09** [comment]
@nohad123 thanks for the update. You could always roll back the kernel version if need be.

**Comment by N1vBruno** [comment]
Well, you can go to the Update Manager -> View -> Linux Kernels, than you can see which kernel you are using and upgrade to a newer one (or rollback to an older kernel if you are already with the newest). Maybe you have both, so you can choose which one to boot in the Grub menu.

The commands returns any errors? There are [others](https://www.2daygeek.com/6-commands-to-shutdown-halt-poweroff-reboot-the-linux-system/) you could try, including some with force variables.
