### ISSUE TITLE
Feature Request - Sound Applet: Add Volume Percentage

### ISSUE THREAD

**Issue by trymeouteh** [linuxmint/cinnamon#8909]
Please add option to show the volume percentage in the sound applet in the panel.

And to show the volume percentage in the volume icon that appears when you increase/decrease the volume using the keyboard.

**Comment by aleex5** [comment]
I would very much like this change to be made, it is quite uncomfortable and useless for the percentage of the volume to appear in a pop-up message
I prefer a thousand times a number that is always shown

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.

**Comment by raniesantos** [comment]
@icarter09 whatever happened to this? I actually want this.

Either on the applet or on the OSD.

There's a post on the forums on how to edit osdWindow.js to show the percentage (but it's not perfect) so people actually want this or something similar to this.

**Comment by raniesantos** [comment]
@icarter09 any updates on this issue?

**Comment by icarter09** [comment]
The volume percentage appears if you enable `Show volume in tooltip` in the Sound settings.

**Comment by raniesantos** [comment]
@icarter09 but that's just a tooltip, that's different.

The issue above specifically refers to having the number always visible without the need to hover over anything.

**Comment by raniesantos** [comment]
Here is a rough image edit of what I mean, and what I think the person that originally posted this means.

![Screenshot from 2021-05-28 12-37-04](https://user-images.githubusercontent.com/8528269/119930221-9a133a00-bfb1-11eb-86fd-7a6947f3a741.png)

**Comment by raniesantos** [comment]
@icarter09 nothing? no further comments after I clarified it?

**Comment by raniesantos** [comment]
@icarter09 feedback?

**Comment by raniesantos** [comment]
@icarter09 hello?
