### ISSUE TITLE
a working VNC Server is missing

### ISSUE THREAD

**Issue by hubertmeier** [linuxmint/cinnamon#8910]
* Distribution - (Mint 19.2)
64bit

Hi,

i am missing a VNC Server Support, vino seems no more to be supportet (when i start vino manually the screen is only exported with 1920x1080, My Desktop is 3840x2160, i see only a quarter of the screen, left-top-quarter. I tried all alternatives, none of them work correctly. Vino seems to work but only with this strange resolution and after configuring with dconf-Editor and after starting it manually.

A graphical remote access to this machine would be absolutely necessary ... and older versions of mint had VNC-Server-Support. RDP would also be ok ...

Thank you

**Steps to reproduce**

**Expected behaviour**

**Other information**

**Comment by clefebvre** [comment]
You can try Nomachine. That said this is beyond the scope of the project, especially here in Cinnamon.
