### ISSUE TITLE
a working VNC Server Support is missing

### ISSUE THREAD

**Issue by hubertmeier** [linuxmint/cinnamon#8911]
* Distribution - (Mint 19.2)

a working VNC-Server Support is missing since Mint 19. Vino seems to work but i can see in the client only 1920x1080 which is the top-left quarter from the 4k 3840x2160 Screen. Sadly unusable.

Configuring is very hidden (dconf-Editor), no autostart.

all alternatives does not seem to work correctly, only vino with the issues work ...

a graphical remote acces per VNC (or RDP) is absolutely necessary.

Thank you

**Steps to reproduce**

**Expected behaviour**

**Other information**

**Comment by leigh123linux** [comment]
Does vino manage to work with gnome-shell 4K?, IMO this is likely to be a limitation of VNC/RDP

**Comment by hubertmeier** [comment]
Sorry, i can't say anything to vino/gnome-shell but the realvnc-server on the raspberry 4 works very good in 4k, RDP under Windows too ...

**Comment by clefebvre** [comment]
https://github.com/linuxmint/cinnamon/issues/8910
