### ISSUE TITLE
External keyboard with numpad causing keyboard layout getting messed when being unplugged from laptop

### ISSUE THREAD

**Issue by xtremebiker** [linuxmint/cinnamon#8912]
```
 * Cinnamon 4.2.4
 * Mint 19.2
 * (GLX_MESA_query_renderer):
    Vendor: Intel Open Source Technology Center (0x8086)
    Device: Mesa DRI Intel(R) UHD Graphics (Whiskey Lake 3x8 GT2)  (0x3ea0)
    Version: 19.0.8
    Accelerated: yes
    Video memory: 3072MB
    Unified memory: yes
    Preferred profile: core (0x1)
    Max core profile version: 4.5
    Max compat profile version: 3.0
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) UHD Graphics (Whiskey Lake 3x8 GT2) 
OpenGL core profile version string: 4.5 (Core Profile) Mesa 19.0.8
OpenGL core profile shading language version string: 4.50
 * 64 bit
 * /home partition was encrypted with the tools given by Mint at installation time
 ```

**Issue**
Having one laptop with Spanish keyboard layout and an external wireless keyboard plugged, when Block num is switched on in the keyboard and I plug it out, the laptop keys are not properly mapped anymore. Some character keys in the keyboard are mapped as numbers. This is not happening when using MATE.

**Steps to reproduce**
In a laptop with no numpad (spanish layout) plug an external wireless keyboard (spanish layout) that has numpad. Enable the Bloq num in the external keyboard and unplug it.

**Expected behaviour**
The system should automatically switch to no-numpad layout when unplugging the keyboard.

**Other information**

Related: https://askubuntu.com/questions/202452/why-is-my-laptop-keyboard-messed-up-after-plugging-an-external-keyboard

**Comment by icarter09** [comment]
@xtremebiker thanks for providing the link. Did the one comment about `plugged my external keyboard in again and pressed the numlock key to turn numlock off` fix your issue?

**Comment by xtremebiker** [comment]
@icarter09 yes it does. Also I can execute an on-screen keyboard and disable it from there. Once done, it workarounds the issue.

**Comment by icarter09** [comment]
@xtremebiker can this ticket be closed?

**Comment by xtremebiker** [comment]
@icarter09 I guess the proper behaviour would be to have the OS set the laptop keyboard layout when the external keyboard gets unplugged, instead of the end user having to switch to no-numlock status. This is especially annoying when you bring the laptop somewhere out of home and you find it with the wrong layout, even when you restart it.

**Comment by xtremebiker** [comment]
@icarter09 I got this issue in MATE too. So not a cinnamon specific issue, you can close it if you consider.

**Comment by icarter09** [comment]
@xtremebiker thanks for the update.
