### ISSUE TITLE
Disabling "recent files" freezes the whole system

### ISSUE THREAD

**Issue by IvoAndonov** [linuxmint/cinnamon#8916]
```
 * Cinnamon version (4.2.4)
   - Please specify if you are using the daily builds PPA (https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds). No.
 * Distribution - (Arch)
 * Graphics hardware *and* driver used - nvidia 435.21
 * 
[xsession-errors.zip](https://github.com/linuxmint/cinnamon/files/3768827/xsession-errors.zip)
64 bit
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
 ```

**Issue**
Disabling "recent files" freezes the whole system

**Steps to reproduce**
Go to Settings --> Privacy --> click on "remember recent files" in order to disable the feature.

**Expected behaviour**
Disabling "remember recent files" shouldn't freeze the whole system.

**Other information**
Only hard reset fixes the problem - the on/off button on the PSU.

**Comment by icarter09** [comment]
Linux Mint 19.2
Cinnamon 4.2.4

Just tried to reproduce this issue, but was unable. System did not lock up after disabling the `remember recent files` option.

**Comment by icarter09** [comment]
@IvoAndonov you still experiencing this issue?

**Comment by IvoAndonov** [comment]
> @IvoAndonov you still experiencing this issue?

No, not anymore. Since Cinnamon updated to 4.4.0 (right now it's 4.4.3) this doesn't happen anymore.
