### ISSUE TITLE
[Feature Request] Startup Applications: Option to set on which workspace an application opens

### ISSUE THREAD

**Issue by Butterfly1984** [linuxmint/cinnamon#8920]
```
 * Cinnamon version 4.2.4
 * Distribution - Mint 19.2 - 64 bit
 * Graphics hardware GeForce GT 740 and driver used 4.6.0 NVIDIA 430.50


 ```

**Issue**
I have about 15 applications set up in Startup Applications, half of them are supposed to open on Workspace 1, which it does, but the other half are meant to open on a specific Workspace, while preferably not stealing focus of other opened active windows i'm currently using.

**Steps to reproduce**
Set up some Startup Applications, they all open on Workspace 1, no matter on which Workspace any specific application was closed last time.

**Expected behaviour**
- Option in "Edit Startup Application" menu to select which workspace an application is opened (drop down menu "Workspace 1-2-3-4?")
- Preferably combined with a checkbox "prevent focus stealing and/or prevent switching to the workspace where this specific Startup Application is opened"

**Other information**
Would also be a great option to have in application launchers, like the checkbox "Launch in terminal?" we have now, also a drop down menu "launch on specific workspace" and "prevent focus stealing"

**Comment by smurphos** [comment]
Whilst waiting for this feature to (maybe) be implemented you can do this via a bash script to launch your apps and move them to the appropriate workspace as they open. The script you would run from Startup applications.

See this Mint forum thread for a bit of discussion and some code snippets that you might find helpful...
https://forums.linuxmint.com/viewtopic.php?f=90&t=287930

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
