### ISSUE TITLE
Doubling (even tripling) of the menubar in LibreOffice

### ISSUE THREAD

**Issue by MenthaSuaveolens** [linuxmint/cinnamon#8924]
Cinnamon-version = Cinnamon 4.2.4
Linux mint Cinnamon = 19.2
Clean install
LibreOffice = 6.0.7.3

**Issue**
open new file with writer
insert object = formula => formula-application opens
     select any kind of formula
     close the formula-application (click in the right side of the area)
After the closing of the formula-application, the menu-bar is doubled

**Steps to reproduce**
Can be reproduced anytime
![DoubleMenuBar](https://user-images.githubusercontent.com/47174957/67661157-c5125380-f960-11e9-9a10-4e8d1b93c7ea.png)

**Expected behaviour**

**Other information**

**Comment by MenthaSuaveolens** [comment]
Sorry, not a cinnamon-issue.

**Comment by mandrael** [comment]
I have the same issue with both the normal and the flatpak installation. If I use an ubuntu ppa with 6.3 I get an awful gray old Windows interface, but the menu bar issue isn't existent.
Cinnamon Mint 19.3

**Comment by MenthaSuaveolens** [comment]
> I have the same issue with both the normal and the flatpak installation. If I use an ubuntu ppa with 6.3 I get an awful gray old Windows interface, but the menu bar issue isn't existent.
> Cinnamon Mint 19.3

Hi, Michael, in the mean time, the bug is reported in the LO-bugzilla: https://bugs.documentfoundation.org/show_bug.cgi?id=128491

The bug seems to be related to the extension LanguageTool
