### ISSUE TITLE
Inconsistent Account details menu

### ISSUE THREAD

**Issue by RatchetMiles** [linuxmint/cinnamon#8925]
```
 * Cinnamon version 4.2.4
 * Distribution - Linux Mint 19.2 Cinnamon Edition
 * Graphics hardware and driver used - RTX 2060 on Nvidia Drivers 430.26
 * 64 bit
 ```

**Issue**
The Account details menu is very inconsistent in that sometimes it will be blank, and other times it will be properly populated with user details. No pattern or particular trigger, it just happens or doesn't.

![Untitled](https://user-images.githubusercontent.com/7415684/67731342-b7f07580-f9ef-11e9-88b4-46438ea0305c.png)

**Steps to reproduce**
No particular step other than to go to account details through any means.

**Expected behaviour**
Account details should always be populated with user details.

**Other information**
Running a custom kernel based on 5.3.6.
Also tested on generic kernels that ship with Mint.
[xsession-errors.txt](https://github.com/linuxmint/cinnamon/files/3781386/xsession-errors.txt)

**Comment by icarter09** [comment]
@RatchetMiles did @claudiux suggestion help fix your issue?

**Comment by icarter09** [comment]
Linux Mint 19.2
Cinnamon 4.2.4

I'm unable to reproduce this issue. I'll keep trying over the next couple of days to see if I can reproduce it, and if so, try to find the exact steps to always make it occur.

**Comment by claudiux** [comment]
@icarter09 It seems that this issue can be closed.
