### ISSUE TITLE
Impress displays undefined column in presentation mode

### ISSUE THREAD

**Issue by MenthaSuaveolens** [linuxmint/cinnamon#8926]
```
 * Cinnamon version (cinnamon --version)
 Cinnamon 4.2.4
 * Distribution - LM 18 - LM19
 * Graphics hardware *and* driver used
inxi -G
Graphics:
  Device-1: Intel Atom/Celeron/Pentium Processor x5-E8000/J3xxx/N3xxx 
  Integrated Graphics 
  driver: i915 v: kernel 
  Display: x11 server: X.Org 1.19.6 driver: modesetting unloaded: fbdev,vesa 
  resolution: 1366x768~60Hz 
  OpenGL: renderer: Mesa DRI Intel HD Graphics 400 (Braswell) 
  v: 4.5 Mesa 19.0.8 
 ```

**Issue**
While presenting an impres-presentation, a white column appears on the left of the presentation-screen. When one toggles the screens (with button underneath in the presenter-console) an "undefined" column appears on the right of the laptop-screen. It looks that a vertical stripe of 10 pixels of the background-image is displayed. In both cases a part of the screen isn't covered by the presentation. The impress-presentation runs fine on other desktop-environments.

**Steps to reproduce**
Always

**Expected behaviour**
Cover the entire screen. The white column is very annoying for the audience.
Attached screenshot was taken after toggling the screens.

![PresentationMode](https://user-images.githubusercontent.com/47174957/67777249-c1b2c100-fa61-11e9-9f01-eee7a9e89126.jpg)

**Other information**

**Comment by icarter09** [comment]
@MenthaSuaveolens see if upgrading the version of LibreOffice to v.6.2.8 fixes this problem. This might be related to #8935.

**Comment by MenthaSuaveolens** [comment]
> @MenthaSuaveolens see if upgrading the version of LibreOffice to v.6.2.8 fixes this problem. This might be related to #8935.

No, It is still the case with this version 6.3.2.2 - Build ID: 1:6.3.2-0ubuntu0.18.04.1~lo1

**Comment by icarter09** [comment]
@MenthaSuaveolens have you submitted this bug into LibreOffice? This bug may not be a Cinnamon issue.

**Comment by icarter09** [comment]
Linux Min 19.2 
Cinnamon 4.2.4

Was able to reproduce this issue.

**Comment by MenthaSuaveolens** [comment]
> @MenthaSuaveolens have you submitted this bug into LibreOffice? This bug may not be a Cinnamon issue.

I filed a bug-report in LO as well: https://bugs.documentfoundation.org/show_bug.cgi?id=128852

**Comment by MenthaSuaveolens** [comment]
![Schermafdruk van 2019-11-16 09-57-53](https://user-images.githubusercontent.com/47174957/69005127-9cf19100-091d-11ea-882d-919a4918158e.png)

**Comment by MenthaSuaveolens** [comment]
The issue is still present on LinuxMint 19.3. 
 Version of LO = Versie: 6.4.3.2 Build ID: 747b5d0ebf89f41c860ec2a39efd7cb15b54f2d8 CPU-threads: 2; Besturingssysteem: Linux 5.3; UI-render: standaard; VCL: gtk3; **Flatpak** Locale: nl-BE (nl_BE.UTF-8); UI-taal: nl-NL Calc: threaded

**Comment by MenthaSuaveolens** [comment]
The issue is still present on LinuxMint 20.1
Version of LO = Versie: 6.4.4.2 Build ID: 1:6.4.4-0ubuntu0.20.04.1 CPU-threads: 2; Besturingssysteem: Linux 5.4; UI-render: standaard; VCL: x11
![Schermafdruk van 2020-07-17 18-46-31](https://user-images.githubusercontent.com/47174957/87812251-2c11c880-c860-11ea-8dcf-985caf66e7d4.png)

**Comment by MenthaSuaveolens** [comment]
The issue hasn't been solved. Tested with Linux Mint 20 Cinnamon - Cinnamon 4.6.7 - Kernel 5.4.0-47-generic
Tested with LO Version: 6.4.5.2 Build ID: 1:6.4.5-0ubuntu0.20.04.1
and with LO Version: 7.0.1.2 Build ID: 7cbcfc562f6eb6708b5ff7d7397325de9e764452

This problem is not only related to LibreOffice but as well to Calligra Stage. You get the same kinds of artifacts when presenting with the Calligra Suite.

In LO if you switch screen (by means of the LO Presentation-console), the artifacts appear on the screen of your laptop. Where the artifact is on the right side of the screen (in normal presentation-mode), the artifact shows up on the left side on the laptop-screen after toggling the presentation-screen.

**Comment by MenthaSuaveolens** [comment]
Tested again with LM 20.1

I didn't install the software, but ran the software from a live-usb-stick

LM 20.1 XFCE : No problem
LM 20.1 Mate : No problem
LM 20.1 Cinnamon : Again the 10 pixel wide vertical artefact on the presentation-screen (or on the laptop-screen if both screens are toggled during the presentation)
![Screenshot from 2021-01-09 16-00-55](https://user-images.githubusercontent.com/47174957/104102787-cf3b1c00-529e-11eb-8117-2011c5cfaeb2.png)
![Screenshot from 2021-01-09 16-01-18](https://user-images.githubusercontent.com/47174957/104102791-d4986680-529e-11eb-9254-cae08789e6f9.png)
