### ISSUE TITLE
Please add switch-to-workspace-{up,down} to cinnamon settings

### ISSUE THREAD

**Issue by google-feinberg** [linuxmint/cinnamon#8932]
The addition of

[("Switch to up workspace"), MUFFIN_KEYBINDINGS_SCHEMA, "switch-to-workspace-up", "workspaces"],
[("Switch to down workspace"), MUFFIN_KEYBINDINGS_SCHEMA, "switch-to-workspace-down", "workspaces"],

to the #Workspaces section of /usr/share/cinnamon/cinnamon-settings/modules/cs_keyboard.py would make NxN grid-switching keyboard-configurable in the keyboard settings module.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
