### ISSUE TITLE
Impress playing video takes full screen

### ISSUE THREAD

**Issue by MenthaSuaveolens** [linuxmint/cinnamon#8935]
```
 * Cinnamon version (cinnamon --version) Cinnamon 4.2.4
   - Please specify if you are using the daily builds PPA (https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds).
 * Distribution - Mint18 and Mint19
 * Graphics hardware *and* driver used
inxi -G
Graphics:
  Device-1: Intel Atom/Celeron/Pentium Processor x5-E8000/J3xxx/N3xxx 
  Integrated Graphics 
  driver: i915 v: kernel 
  Display: x11 server: X.Org 1.19.6 driver: modesetting unloaded: fbdev,vesa 
  resolution: 1366x768~60Hz 
  OpenGL: renderer: Mesa DRI Intel HD Graphics 400 (Braswell) 
  v: 4.5 Mesa 19.0.8
 * 32 or 64 bit
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
 ```

**Issue**
Imbed a video into LibreOffice-presentation. Start presentation => video takes full screen

**Steps to reproduce**

**Expected behaviour**
Video should be confined to rectangle into the screen 

**Other information**
Bug was reported in LO: https://bugs.documentfoundation.org/show_bug.cgi?id=122181

Problem has been solved on more recent Ubuntu-versions. Still a problem on LinuxMint.

**Comment by icarter09** [comment]
Linux Mint 19.2
Cinnamon 4.2.4

The issue here is that the current version of LibreOffice installed on Mint is v6.0.7, which contains the bug indicated in this ticket. This is the version also referenced in the bug report on the LibreOffice site. I was able to fix this issue by upgrading to a newer version of LibreOffice (in this case it was v6.2.8). Until the version of LibreOffice is upgraded on Mint, then this issue will persist. Easy fix is just update LibreOffice yourself until then.

@MenthaSuaveolens let me know if that fixes your problem.

**Comment by leigh123linux** [comment]
None of this can be fixed within cinnamon code

@clefebvre  Is Mint due a LibreOffice update

**Comment by MenthaSuaveolens** [comment]
> Linux Mint 19.2
> Cinnamon 4.2.4
> 
> The issue here is that the current version of LibreOffice installed on Mint is v6.0.7, which contains the bug indicated in this ticket. This is the version also referenced in the bug report on the LibreOffice site. I was able to fix this issue by upgrading to a newer version of LibreOffice (in this case it was v6.2.8). Until the version of LibreOffice is upgraded on Mint, then this issue will persist. Easy fix is just update LibreOffice yourself until then. You will have to download a newer version off of LibreOffice's site since using Mint's Software Manager will direct you to the v6.0.7 version of LibreOffice.
> 
> @MenthaSuaveolens let me know if that fixes your problem.

I'm using Version: 6.3.2.2 Build ID: 1:6.3.2-0ubuntu0.18.04.1~lo1 The problem has not been solved in this version. Playing the same presentation in a recent Ubuntu-version runs fine however?
