### ISSUE TITLE
Cinnamon-settings sound: Output device is nothing/null after I remove HDMI cable. (would be better to revert to default sound).

### ISSUE THREAD

**Issue by kevin-foster** [linuxmint/cinnamon#8941]
```
 * Cinnamon version (cinnamon --version): **4.0.10**
   - Please specify if you are using the daily builds PPA (https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds).  **NO**
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)  **Linux Mint 19.1 Tessa**
 * Graphics hardware *and* driver used  **Device: GPU: Mesa DRI Intel(R) Ivybridge Mobile.  Driver: ?**
 * 32 or 64 bit **64-bit**
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog  **N/A**
 ```

**Issue**

When I use an HDMI cable to watch a video on my television, I manually set the sound output to the HDMI device in sound settings (`cinnamon-settings sound`). After I remove it, the HDMI device disappears, but my sound output doesn't revert to the default ("Speakers Built-in Audio").  I discovered I needed only click the relevant icon in the applet, but only after some head scratching. (It was a day later, and the setting is persistent across reboots). It would be an improvement to either (a) revert the sound setting to default after HDMI device disappears, or alternately (b) indicate clearly when there is no audio output device selected. This could be done via a changed icon in system tray, and a prominently displayed message in the app ("There is no output device selected currently.") Thanks for your consideration.

Settings after HDMI removed:
![Settings after HDMI removed](https://i.imgur.com/mstq9Ul.png)

Desired behavior after HDMI removed:
![Desired behavior after HDMI removed](https://i.imgur.com/1WNziOT.png)

**Steps to reproduce**

1. Connect an HDMI source and redirect audio/video to the external device.

2. Remove HDMI cable/device.

3. Play audio.

**Expected behaviour**

Audio from built-in laptop speaker.

**Other information**

My laptop is a Lenovo X230.

**Comment by leigh123linux** [comment]
-1 to changing this as it would break my media pc setup every time the TV goes to standby mode.
It would also do the same to my to my workstation.

**Comment by shanmukhateja** [comment]
Could you try the work mentioned in this [link](https://gitlab.freedesktop.org/pulseaudio/pulseaudio/issues/259#note_13419) and report back the result?

Steps:

1. Open `/etc/pulse/default.pa` on text editor:
 `sudo gedit /etc/pulse/default.pa`

2. Locate the line `load-module module-stream-restore` inside the file and replace it with `load-module module-stream-restore restore_device=false`

3. Restart your computer and try again.

My reasoning behind this is the fact that PulseAudio is the software that detects and configures audio devices in Linux. So, if it would be a PA's fault for not switching over.

There are older issues with similar problems going as far as 2016.

[Original Link] (https://bugs.freedesktop.org/show_bug.cgi?id=96211)
[Upstream] (https://gitlab.freedesktop.org/pulseaudio/pulseaudio/issues/185)

**Comment by icarter09** [comment]
@kevin-foster did @shanmukhateja comment help to fix the issue?

**Comment by kevin-foster** [comment]
@icarter09 Haven't had time to try it yet---will report back.

**Comment by kevin-foster** [comment]
@shanmukhateja thanks. This seems to have worked. Should I follow up by reporting to PulseAudio?

**Comment by shanmukhateja** [comment]
Yes, I would recommend a follow up to PulseAudio devs. It is better if they know about this bug so it can be addressed proper way rather relying on a workaround which might fail in the near future.

**Comment by icarter09** [comment]
@kevin-foster if you feel this has been addressed, can you close out this ticket? Thanks.
