### ISSUE TITLE
Feature Request: allow better customization of special key / modifier instead of limited drop-down

### ISSUE THREAD

**Issue by systemdarena** [linuxmint/cinnamon#8942]
```
Cinnamon 4.2.4
 ```
This is a feature request for Cinnamon's Settings GUI. Instead of a drop-down menu for selecting a modifier key it would be nice to have a customizable key combo selector like in the Keyboard Shortcuts section.

I noticed this when trying to change the Desktop Zoom Mouse wheel modifier. There is a drop-down provided with only \<Alt\>, \<Super\>, and \<Control\> listed. I had issue with those interfering with other uses, so wanted a different option. After looking in the source, I found that it essentially just runs gsettings set org.cinnamon.desktop.wm.preferences mouse-button-zoom-modifier. I was able to change it to '\<Super\>\<Shift\>' without any issue.

The same drop-down is also under Windows, Behavior tab, for "Special key to move and resize windows".

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
