### ISSUE TITLE
OnScreenKeyboard (virtual kayboard) semantic error

### ISSUE THREAD

**Issue by muncha** [linuxmint/cinnamon#8943]
```
 * Cinnamon version (cinnamon --version)
   - Cinnamon 4.2.4
   - Not using the daily builds PPA
 * Manjaro Linux 
 * Graphics hardware *and* driver used
   - Intel Corporation UHD Graphics 620
   - i915
 * 64 bit
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
   - Irrelevant. I am not reporting an error in operation.
 ```

**Issue**
The keys of the OnScreenKeyboard applet that switch between layouts / views are semantically incorrect.
On the view of the onScreenKeyboard applet, there are 3 layouts available - an alpha layout, a numeric layout and a symbol layout. On the alpha layout there are keys to switch to the other two layouts. The key to switch to the numeric layout is labeled "123" The key to the symbol layout is labeled "{#*" In the symbol layout, neither the character { nor * are present. They are available in the numeric layout.
The same key is available in the numeric layout to switch to the symbol layout.

**Steps to reproduce**
  - Open the keyboard
  - click the "{#*" key to switch to the symbol layout
  - look for either the { character or the * character
  - leave dissatisfied.

**Expected behaviour**
For the key that switches to the symbol layout to have characters on it that are in the symbol layout.

**Comment by icarter09** [comment]
@muncha does pressing the "Shift" key on the OnScreenKeyboard not take you to the rest of the symbols?
