### ISSUE TITLE
Mint Cinnamon 19.2 Missing Metacity Mini-Icon Support

### ISSUE THREAD

**Issue by cwchaban** [linuxmint/cinnamon#8948]
Cinnamon 4.2.4
Mint Cinnamon 19.2
AMD 2400G amdgpu
Multiarch

**Issue**
Themes where the <icon> tag is used in metacity do not display an icon in the specified area. ie. menu button.

**Steps to reproduce**
All such themes are affected.

**Expected behaviour**
Show the appropriate application icon.

**Other information**
This bug has been present since the 19.2 beta.
https://github.com/smurphos/Window_Borders_Mint_19/issues/9
From what little I have found, there is no interest in support for mini-icons in the title bar. Which I find strange for a distribution which is though of as a good alternative for Windows users.
Personally, I love Mint Cinnamon, but the lack of response to this issue in particular has kept me from recommending upgrading to 19.2.

**Comment by cwchaban** [comment]
The previous report did not display the tag name which is ICON.

**Comment by JosephMcc** [comment]
There isn't much interest because over the long run we will probably drop support for metacity themes entirely. Not many DE's still support them and I'm not sure most themes even support the mini-icon anymore.

**Comment by cwchaban** [comment]
I find this a little confusing.
METACITY themes are used in Mint 19.2.
The specifications for metacity define an ICON tag which is used for displaying an application's icon.
This is a bug.
The uncertain future of metacity themes is not relevant. The code was there in Mint 19.1 and has been removed. The fact that few developers use the feature does not no developers use it. The referenced link shows someone is using the feature. I use it in my themes.
The Cinnamon panel now more than ever looks an acts like the Windows 7 Aero taskbar. The Mint developers went to all the trouble to fork most of the Gnome apps to support the look they were trying to achieve. To make it easier for ex-windows users to become accustomed to a Linux desktop environment. The very reason I recommend Mint to new Linux users.
I would very much like to hear what Clem has to say on the topic because I am having hard time believing the responses to this bug.

**Comment by xss** [comment]
@JosephMcc wrote:
> There isn't much interest because over the long run we will probably drop support for metacity themes entirely. Not many DE's still support them and I'm not sure most themes even support the mini-icon anymore.

If not metacity themes, then what kind of themes should we use? And more importantly to me: What kind of themes do support the application icon (mini-icon) to display?

My use-case: Apart from mere aethetics of those icons, I find it a horrible and confusing situation to have some password dialog pop up without any hint as to which application wants which password and why. Simply displaying the Thunderbird icon in the popup window's title bar would make things much clearer, as it **should** be.
