### ISSUE TITLE
Grouped window list, thumbnails are not aligned with their taskbar entries

### ISSUE THREAD

**Issue by Mikaka27** [linuxmint/cinnamon#8949]
```
 * Cinnamon version: Cinnamon 4.2.4
   - Not using ppa
 * Distribution - Mint 19.2
 * Nvidia Geforce GTX 1660 Ti on 440.26 driver
 * 64 bit
 * [xsession-errors.txt](https://github.com/linuxmint/cinnamon/files/3833987/xsession-errors.txt)
 ```

**Issue**
Thumbnails for windows do not stay aligned with taskbar "entry" that you hover on to get them in Grouped Window List.

**Steps to reproduce**
1. Enable window titles on taskbar:
![1](https://user-images.githubusercontent.com/9214100/68635477-f52d2b00-04f8-11ea-9e7a-2427cfd4d32f.png)
2. Open a pinned application from the taskbar, and hover over it, you can see that thumbnail is in correct place:
![2](https://user-images.githubusercontent.com/9214100/68635505-0fff9f80-04f9-11ea-894c-e7341fd99892.png)
3. Now open a pinned application that is on the left side of previously opened application:
![3](https://user-images.githubusercontent.com/9214100/68635527-2574c980-04f9-11ea-9c26-98b18093ba8d.png)
4. Hover over the first application opened, you can see that although the taskbar "entry" was shifted right when another application opened, the thumbnail stayed where it was before, in fact it will stay there for as long as this window is open, regardless of other windows being opened/closed:
![4](https://user-images.githubusercontent.com/9214100/68635598-6076fd00-04f9-11ea-9418-e532786edf9a.png)
5. Try it the other way around this time, first open a lot of applications, and hover over last of them:
![5](https://user-images.githubusercontent.com/9214100/68635637-7edcf880-04f9-11ea-833d-23b5091c0a35.png)
6. Now close all the applications except last one (the one on the far right), and hover over it, now thumbnail is in incorrect place again, it stayed where the application was first opened:
![6](https://user-images.githubusercontent.com/9214100/68635686-9fa54e00-04f9-11ea-9851-a453d1d4b03b.png)

**Expected behaviour**
Thumbnails should always be aligned to their taskbar entries.

**Comment by mtwebster** [comment]
Already fixed by: https://github.com/linuxmint/cinnamon/commit/b43465e80cc61626a385cdc0fa2778cfb4717b0d
