### ISSUE TITLE
&nbsp tag visible in system settings

### ISSUE THREAD

**Issue by Mikaka27** [linuxmint/cinnamon#8953]
```
 * Cinnamon version: Cinnamon 4.2.4
   - Not using ppa
 * Distribution - Mint 19.2
 * GTX 1660 Ti on 440.26 driver
 * 64 bit
 * No .xsession-errors file present
 ```

**Issue**
&nbsp tag is visible in system settings on "Accounts and groups" item.
This happens in polish version of linux mint.

**Steps to reproduce**
1. Open system settings:
![1](https://user-images.githubusercontent.com/9214100/68638089-c1560380-0500-11ea-84a2-19a592749b60.png)

**Expected behaviour**
&nbsp should be rendered, instead of shown as text.

**Comment by mtwebster** [comment]
What language is this in?

**Comment by mtwebster** [comment]
Nevermind, I found it - this is a translation problem - just a space should be used there - it should be addressed in this coming release, but the original translation should be fixed:

https://translations.launchpad.net/linuxmint/latest/+pots/cinnamon/pl/327/+translate?field.alternative_language=&field.alternative_language-empty-marker=1
