### ISSUE TITLE
Feature request: Ablity to completely deactivate mouse acceleration with a single button.

### ISSUE THREAD

**Issue by damian101** [linuxmint/cinnamon#8958]
At the moment you can deactivate mouse acceleration by drawing the mouse acceleration slider to the far left. But that makes the mouse very slow, which is a problem as the mouse sensitivity slider doesn't work on any of my systems (#8808).
You can completely deactivate mouse acceleration by creating the file `/usr/share/X11/xorg.conf.d/50-mouse-acceleration.conf` with the follwing content:
```
Section "InputClass"
    Identifier "My Mouse"
    Driver "libinput"
    MatchIsPointer "yes"
    Option "AccelProfile" "flat"
    Option "AccelSpeed" "0"
EndSection
```
This not only leads to disabled mouse acceleration but also a mouse speed that is similar (if not identical) to the one I have in Windows, KDE Plasma and the Deepin Desktop environment where it is possible to deactivate mouse acceleration with a single button. Having a uniform mouse speed across different systems is very nice. 
Turning mouse acceleration completely off might also decrease input lag.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
