### ISSUE TITLE
FEATURE REQUEST - Screen recorder - more prebuilt options for pipeline and a GUI to manage them

### ISSUE THREAD

**Issue by smurphos** [linuxmint/cinnamon#8963]
It would be nice if there were a few more pre-defined options for the screen-recorders pipeline to facilitate recording with alternative codecs and file formats - e.g H264 in MP4 or MKV, XVID/AVI, Animated GIF along with a GUI to manage them and the default save location.

**Comment by claudiux** [comment]
Waiting it, I use [vokoscreen](apt://vokoscreen).

**Comment by icarter09** [comment]
#7441

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
