### ISSUE TITLE
Periodically QT apps lose Hi-DPI scaling

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/cinnamon#8970]
```
 * Cinnamon version (cinnamon --version) 4.2.4
   - Please specify if you are using the daily builds PPA (https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds). No.
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 19.2
 * Graphics hardware *and* driver used: Intel onboard; Mesa
 * 32 or 64 bit: 64

 ```

**Issue**

Periodically, QT applications such as KeePassXC, Ksystemlog, RcloneBrowser and AngrySearch lose the HiDPI scaling that I have set in Mint. The following shell code, which I run via con every minute, fixes the problem and indeed nearly always in such a way that the problem does not arise.

```
DPI_KEY='org.cinnamon.desktop.interface'
DPI_LEAF='scaling-factor'
VALUE_DESIRED=2
gsettings set "$DPI_KEY" "$DPI_LEAF" "$VALUE_DESIRED"
```

I note also that the key in question _reports_ the desired value even when apps are scaling wrongly; but setting the desired value does - temporarily - fix the problem.

GTK applications do not have the problem.

I have had this problem since I got my HiDPI computer about a year ago. Possibly something in my setup is to blame; to get the QT apps to scale at all I need this:

```
/etc/profile.d/qt-fixes.sh
-------------------------------
export QT_AUTO_SCREEN_SCALE_FACTOR=1 # honor screen DPI
export QT_QPA_PLATFORMTHEME=qt5ct
```

**Steps to reproduce**

Perhaps the following.

Install a QT app (or two) on a HiDPI computer with scaling set to 2.
Get Cinnamon to scale those apps (using the /etc/profile hack mentioned above)
Wait.

**Expected behaviour**

QT apps should not lose their scaling.
Ideally, one would not have to force the scaling in the first place, either.

**Other information**

OS: Linux Mint 19.2 Tina x86_64 
Host: 20KHCTO1WW ThinkPad X1 Carbon 6th 
Kernel: 5.3.9-050309-generic 
Uptime: 11 hours, 53 mins 
Packages: 3120 (dpkg), 14 (flatpak), 4 (snap) 
Shell: bash 4.4.20 
Resolution: 2560x1440 @ 60.01Hz 
DE: Cinnamon 4.2.4 
WM: Mutter (Muffin) 
WM Theme: N_Cinn (N_Cinn) 
Theme: Mint-Y-Dark [GTK2/3] 
Icons: Paper [GTK2/3] 
Terminal: gnome-terminal 
CPU: Intel i7-8550U (8) @ 4.000GHz 
GPU: Intel UHD Graphics 620 

EDIT: screenshot of KeePassXC when it is affected.
![2019-11-20_02-10](https://user-images.githubusercontent.com/47056543/69204214-2da6b780-0b3e-11ea-8ded-0d84b76b3fbb.png)

**Comment by leigh123linux** [comment]
File the issue against QT5

**Comment by clefebvre** [comment]
First thing to check is to make sure no other settings daemon is running.

I would suggest to put traces in https://github.com/linuxmint/cinnamon-settings-daemon/blob/master/plugins/xsettings/csd-xsettings-manager.c#L618 and https://github.com/linuxmint/cinnamon-settings-daemon/blob/master/plugins/xsettings/csd-xsettings-manager.c#L670 to monitor when the Cinnamon Settings Daemon is setting the values and to make sure it doesn't revert back to non-HiDPI. Alternatively you could kill csd_xsettings to rule the fact that it's responsible for reverting the value.

Write a script also to monitor the Gdk value directly to see if another process is modifying it.

**Comment by leigh123linux** [comment]
@clefebvre  I really don't think the issue is in cinnamon stack, earlier qt5 versions had broken hidpi support.
My qt5 apps have been working fine with hidpi for many releases.

**Comment by LinuxOnTheDesktop** [comment]
@clefebvre

> First thing to check is to make sure no other settings daemon is running.

That is a separate point from the one in your next paragraph, right? If is, how do I do that, i.e. how do I check whether no other settings daemon is running? What other such daemon might be running? Or is the issue another _instance_ of Cinnamon Settings Daemon?

As to the traces: I will attempt that once I have the time (though it may be beyond me).

> Write a script also to monitor the Gdk value directly to see if another process is modifying it.

That I could do. Still, and as said: when my current script tries to read the current value, the value is reported as being what it should be.

@leigh123linux: I fear I do not understand. Do you think the problem is with the qt5 software, or not?
