### ISSUE TITLE
Feature Request: Sound Applet: Add/Remove favorite output devices

### ISSUE THREAD

**Issue by trymeouteh** [linuxmint/cinnamon#8974]
I like to use my speakers and a headset and switch back and forth between them. To change between my speakers and headset I need to click on the Sound Applet, click on Sound Settings, select the output device and then close the Sound Settings window.

I would like to see a feature that will allow you to click on the Sound Applet, and then click on the output device you want to use. To add/remove devices to this list you should be able to add them within the Sound Settings and even rename the output devices for the favourite list to be able to have more generic names such as "Speakers" and "Headset".

I think this will make a better UX design when it comes to switching between favorite sound output devices.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
