### ISSUE TITLE
Improvement idea: Automatic shutdown to the shutdown menu

### ISSUE THREAD

**Issue by ArttoA** [linuxmint/cinnamon#8975]
It is a good thing to have the shutdown-menu in Cinnamon pop up, when physical power button is pressed. There are currently 4 choices: Shut down, Suspend, Cancel, Reboot.

May I suggest adding a fifth option: timed shutdown.
There could be a cell, where you can either enter exact time or select after how many minutes/hours the automatic shutdown would happen. And after setting the time you could then press the button called "Shutdown (timed)". And after pressing it there could be or could not be a timer running somewhere on the system tray or panel, and the computer would shut itself down after the set time.

**Comment by claudiux** [comment]
@ArttoA Please see Settings -> General -> Miscellaneous Options. There is an option `Enable timer when logging out or shutting down`.

**Comment by JosephMcc** [comment]
I think the solution pointed out by claudiux covers most of what you're asking for here.
