### ISSUE TITLE
Improvement idea: HDD/SSD problems

### ISSUE THREAD

**Issue by ArttoA** [linuxmint/cinnamon#8976]
There is the gnome-disks application in Linux Mint, from where you can check the situation of the current OS disk condition (e.g. Assessment: Disk is OK).

Wouldn't it be wonderful to have this implemented in this way, that when computer boots up, Mint checks from the gnome-disks about the health of the disk (in the background, invisibly, of course), and in case the disk is OK, nothing should happen. But when there are bad blocks on the disk, Cinnamon desktop (or other desktops in Mint) could warn the user via Notification, that there are bad blocks on the drive and it would be a good idea to replace the disk soon, in order to not run the risk of losing data (files). 
And in order that the notification would not pop up every time, it could have a tick box, where you can select "don't notify me about this anymore".

Same story with checking the USB-drives - when USB or external hard drive inserted and auto-mounted, the disk-check with the notification could also pop up, if there is any data about the bad blocks regarding this drive.

**Comment by JosephMcc** [comment]
Thanks for idea and it will be considered. I'm closing this here since it sounds more like a Mint improvement, not a Cinnamon specific one.
