### ISSUE TITLE
Changing Web browser in Preferred Applications doesn't work 100%

### ISSUE THREAD

**Issue by Sadi58** [linuxmint/cinnamon#8982]
```
 * csd version: 4.2.2+tina
 * Distribution: Mint 19.2
 * 64 bit
 ```
**Issue**
In System Settings, changing the default web browser in Preferred Applications does not work for all cases, e.g. clicking url links in Thunderbird and some other apps continue to use the original default, i.e. Firefox.

**Steps to reproduce**
1. In default setup,  enter this terminal command: `xdg-settings get default-web-browser`, which should return: `firefox.desktop`.
2. Open **System Settings** and change the default **Web** browser in **Preferred Applications** to something else instead of Firefox.
3. Click any url link in **Thunderbird** (still opens in **Firefox**), or enter this terminal command: `**xdg-settings get default-web-browser**` (still returns `firefox.desktop`.

**Expected behaviour**
When user changes default web browser, it should change in all cases.

**Other information**
Using terminal command `xdg-settings set default-web-browser` (followed by another web browser's ".desktop" file) does the trick.

**Comment by icarter09** [comment]
#7591

**Comment by icarter09** [comment]
Linux Mint 19.2
Cinnamon 4.2.4

I'm not able to reproduce this. Steps were:
 1. `xdg-settings get default-web-browser` returned `brave-browser.desktop`
 2. Opened **System Settings** and changed **Web** to Chromium.
 3. `xdg-settings get default-web-browser` returned `chromium-browser.desktop`

**Comment by Sadi58** [comment]
@icarter09 Strange.
Initially, I could see the change in System Settings, when I click html files it would open in my chosen web browser, etc. - only sticking to the default setting in some cases (e.g. url links).
Now, I change the setting in System settings, I close the window and open System Settings again; I see my change didn't stick at all.
Nothing like this hapens in Text Editor, for example.
Maybe I have a permissions problem in system file for the default web browser?

**Comment by icarter09** [comment]
@Sadi58 any luck on this issue? Figured that nothing has changed, but just wanted to touch to base.

**Comment by Sadi58** [comment]
@icarter09 Strange, but this time for the better. ;-)
Meanwhile I uninstalled Chromium browser, installed Vivaldi, and then installed Chromium again.
Now it works as it should.
I didn't do anything else in particular to address this issue.
It was a strange individual and one-off bug bite I guess - sorry for taking your time, and thanks a lot for your attention.

**Comment by icarter09** [comment]
@Sadi58 no worries. Glad everything is working for you now.
