### ISSUE TITLE
Terminal window - paste using keyboard

### ISSUE THREAD

**Issue by Pance21** [linuxmint/cinnamon#8985]
I'm using Mint 19.2 (64 bit) - but this is probably true for all Linux versions.

I'm used to using keyboard shortcuts, like Ctrl-C and Ctrl-V, which work fine everywhere except in the Terminal window. For example, the paste shortcut - Ctrl-V - does nothing. Luckily, there is the mouse functionality with right-click and paste. 

But it would be nice if Ctrl-V worked too.

Thanks.

**Comment by JosephMcc** [comment]
Closing this since it's unrelated to Cinnamon. Paste in gnome-terminal Shift+Ctrl+V
