### ISSUE TITLE
Nemo - advanced search

### ISSUE THREAD

**Issue by Pance21** [linuxmint/cinnamon#8986]
I'm using Mint 19.2 (64 bit), and Nemo 4.2.3.

It would be nice if Nemo had advanced search options like date, and search file contents.

Thanks

**Comment by JosephMcc** [comment]
Thanks for the suggestion. Nemo has it's own repo for issues and a quick search there already turns up a bunch of requests for improved search features: https://github.com/linuxmint/nemo/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+search
