### ISSUE TITLE
Mouse pointer - disappear while typing

### ISSUE THREAD

**Issue by Pance21** [linuxmint/cinnamon#8987]
I'm using Mint 19.2 (64 bit).

I've noticed many times that the mouse pointer interferes (ie it covers up text) while typing some text. It would be nice if the pointer disappeared, so I can type without having to move it out of the way. And then when I move the mouse, the pointer should re-appear.

This used to work many years ago in WordPerfect - if anyone remembers that word processor. It was a great feature.

**Comment by clefebvre** [comment]
That's application specific afaik. Gnome-terminal does that if I remember well.

**Comment by Pance21** [comment]
yes, the terminal does make the mouse disappear while typing. It would be nice if this was a feature of all the gui apps.

Pance
