### ISSUE TITLE
[Feature Request] Change sorting of windows in window selection screen

### ISSUE THREAD

**Issue by BeayemX** [linuxmint/cinnamon#8991]
**Cinnamon version (cinnamon --version)**
OS: Mint 19.2 tina, 64 Bit
DE: Cinnamon 4.2.4

**Issue**
The window selection screen arranges the windows by most recently focused. When working with multiple non-fullscreen windows, it is possible that the windows jump around quite a lot when entering the window selection screen.

Gnome Shell arranges the windows by their placement on the screen, regardless of when they have been focused.

**Steps to reproduce**
1. Arrange three windows like this 
![image](https://user-images.githubusercontent.com/3453076/70000649-b91b4200-155b-11ea-955e-0b1c5994acee.png)

2. Select different windows
3. Enter the window selection screen
4. See that windows jump around quite a lot

**Expected behaviour**
It would be great for the windows to respect the positioning on the screen for the placement in the window selection screen.
If the sorting by most recently focused is desired, an option to change this behaviour would be appreciated.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
