### ISSUE TITLE
The screensaver only repaints when the clock repaints

### ISSUE THREAD

**Issue by JustinSpedding** [linuxmint/cinnamon#8992]
```
 * Cinnamon version: 4.2.4
 * Distribution: Linux Mint 19.2
 * Graphics: Nvidia GTX 1080 w/ 435.21 drivers. vsync is disabled in cinnamon in favor of the compositioning pipeline in the nvidia settings.
 * 32 or 64 bit: 64
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
 ```

**Issue**

When I lock the screen and try to log back in, sometimes the screen only repaints when the clock repaints. By this, I mean that I would start typing my password in, but the dots in the password textbox only update once a second when the clock displays the new second, instead of on every keystroke.

This happens when using either a single monitor or multiple monitors. However, if you have multiple monitors, it also waits for a clock repaint to move the login overlay to the monitor where the cursor is located. So, if I move my mouse cursor to the other monitor, it will not move the login window over to the other monitor immediately like it should. Instead, it waits until the clock updates.

This happens most, but not all of the time that I use the lock screen. If it does happen, it will continue to repaint once per second until I unlock it. I have not yet determined a consistent pattern for why it sometimes it has a low refresh rate, but other times updates normally. I think it might have something to do with my graphics settings, but I am not sure.

**Steps to reproduce**

1) lock your screen
2) attempt to type a password to get back in
3) sometimes it will only repaint anything on the screen once per clock repaint

**Expected behaviour**

The password box should update with every keystroke.

**Other information**

**Comment by JustinSpedding** [comment]
Also, this issue started when I updated to Linux Mint 19.2.

**Comment by icarter09** [comment]
Linux Mint 19.2
Cinnamon 4.2.4

I've attempted to reproduce this several times, but haven't had any luck so far. I plan to test it out more to see if I can reproduce the issue.

**Comment by JustinSpedding** [comment]
Here is a video of it happening: https://drive.google.com/file/d/1AEVYN8AOxGH5SnRQ8PYM-QTsbgw-B3Hz/view?usp=sharing

Sorry for taking it with my phone. I do not know how to record the screen when the screensaver is up.

Also, I noticed that it happens a bit more often after the computer wakes up from sleep and/or the screen was off due to inactivity for a while.

**Comment by icarter09** [comment]
@JustinSpedding no worries on using your phone and thanks for taking the time to do that. 

I'll let you know if I'm able to reproduce it.

**Comment by mtwebster** [comment]
It can be fairly reliably reproduced with xrandr actions while the screensaver is active - a monitor turning off for powersave, unplugging/replugging, etc..  Pretty sure it's not the screensaver (at least not the change that caused the regression), but possibly muffin.  You can run 4.4 screensaver in 4.0 cinnamon/muffin and the issue does not occur.

**Comment by Kidlike** [comment]
This issue also happens for me. I don't know if it's the screensaver or muffin, but it's quite annoying. Initially I thought that my computer froze, but it's just the input prompt not showing the entered characters...

**Comment by mtwebster** [comment]
@Kidlike what version of muffin?

**Comment by Kidlike** [comment]
@mtwebster muffin @ 4.4.1

**Comment by mtwebster** [comment]
4.4.2 is out, try updating to that and let me know.  I added a fix that solved it for me, but I've yet to hear feedback from anyone else.

**Comment by leigh123linux** [comment]
https://bodhi.fedoraproject.org/updates/FEDORA-2020-0d74795eed

**Comment by Kidlike** [comment]
Thanks @mtwebster @leigh123linux :)

I've been using the linked update for a day, and so far so good. I will post again in a few days with an update :)

**Comment by JustinSpedding** [comment]
I have also been using the updated version, and have not experienced the issue since.

**Comment by Kidlike** [comment]
This issue hasn't occurred again for me since the update :)

Also, no other side effects! :tada:

**Comment by mtwebster** [comment]
Ok I'm going to call this fixed, thanks for reporting back.
