### ISSUE TITLE
GUI log-in wallpaper-less black desktop requiring cinnamon restart

### ISSUE THREAD

**Issue by Bednar87** [linuxmint/cinnamon#8998]
Cinnamon version (cinnamon --version) **Cinnamon 4.4.3**
Please specify if you are using the daily builds PPA (https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds). **No**
Distribution - (Mint 17.2, Arch, Fedora 25, etc...) **Arch**
Graphics hardware and driver used **Vega 64 Mesa 19.2.6**
32 or 64 bit **64 bit**
Attach /home//.xsession-errors, or /var/log/sysl xsession-errors.txt **Done**

[xsession-errors.log](https://github.com/linuxmint/cinnamon/files/3923894/xsession-errors.log)
[xsession-errors-old.log](https://github.com/linuxmint/cinnamon/files/3923896/xsession-errors-old.log)

[journalctl.log](https://github.com/linuxmint/cinnamon/files/3923912/journalctl.log)
[Xorg.0.log](https://github.com/linuxmint/cinnamon/files/3923918/Xorg.0.log)
[Xorgold.0.log](https://github.com/linuxmint/cinnamon/files/3923923/Xorgold.0.log)

**Issue**

After logging in through lightdm, I am briefly greeted by a pseudo splash screen with just the wallpaper and then soon after I get a black screen with icons on the desktop but no panel. I need to run cinnamon --replace & disown   which properly (re)starts the desktop. This is 100% reproducible as it happens every time.

Any pointers appreciated.

**Comment by icarter09** [comment]
@eli-schwartz

**Comment by leigh123linux** [comment]
Cinnamon isn't  even trying to start as X is failing, try fixing your graphics driver issue.

```
cinnamon-session[1189]: WARNING: t+3958.66463s: Application 'cinnamon-settings-daemon-orientation.desktop' killed by signal 15
Gdk-Message: 19:56:31.414: cinnamon-session: Fatal IO error 11 (Resource temporarily unavailable) on X server :0.
```
