### ISSUE TITLE
[NEXT] [Feature Request] Needed cinnamon-settings-lockdown

### ISSUE THREAD

**Issue by claudiux** [linuxmint/cinnamon#8999]
```
 * Cinnamon version: NEXT
 ```

**Issue**
Administrators can not set easily all lockdown parameters present in `org.cinnamon.desktop.lockdown`:

- disable-application-handlers
- disable-command-line
- disable-lock-screen
- disable-log-out
- disable-printing
- disable-print-setup
- disable-save-to-disk
- disable-user-switching

**Steps to reproduce**
Nothing appears about lockdown in System Settings, Admin section.

**Expected behaviour**
- Have an interface for administrators in System Settings to set these values. 

- Maybe have the ability to make templates applicable to non-administrator users, to a group of users, to new users, to particular users etc.

- That Cinnamon (including xlets) take into account these parameters.

**Other information**
A tool existed for Gnome: [pessulus](https://gitlab.gnome.org/Archive/pessulus).

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
