### ISSUE TITLE
Clock from Gnome 2

### ISSUE THREAD

**Issue by LinuxJedi** [linuxmint/Cinnamon#90]
One of the most missed features by me and several other developers is the clock from Gnome 2.  You could add multiple timezones to it and instantly see the weather in all the locations.  Very useful when you have a distributed team.

My boss blogged about the lack of this feature in Unity and Gnome 3 here: http://inaugust.com/post/106

We will blog about it, have your babies (if that was physically possible), etc.. if you please bring back something similar in Cinnamon.

**Comment by JosephMcc** [comment]
Thank you for your suggestion. See https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html for information on how we handle feature requests.
