### ISSUE TITLE
Clipping Icons on right hand panel

### ISSUE THREAD

**Issue by BreimerR** [linuxmint/cinnamon#9000]
```
 * Cinnamon version (cinnamon --version)
 * Distribution -  Linux mint 19.2
 * Intel core i7 with Nvidia 930 on Nvidia 430 graphics driver
 * 64 bit
 * 
 ```

**Issue**
I am experiencing icon clipping on the right side of my panel 

**Steps to reproduce**
Not so sure on reproducing it yet occurs once in a while 

**Other information**
Requires cinnamon restart to resolve

**Comment by mtwebster** [comment]
Can you do a screenshot next time it happens?  Thanks

**Comment by icarter09** [comment]
@BreimerR you still experiencing this issue?
