### ISSUE TITLE
error open cinnamon-settings themes

### ISSUE THREAD

**Issue by stinerd** [linuxmint/cinnamon#9005]
```

```
> cinnamon-settings themes
> libgoa-backend-1.0.so.1: cannot open shared object file: No such file or directory
> Failed to load module: /usr/lib/cinnamon-control-center-1/panels/libonline-accounts.so
> True
> Using pam module (python3-pampy)
> /usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py:429: DeprecationWarning: Gtk.Window.set_wmclass is deprecated
>   self.window.set_wmclass(wm_class, wm_class)
> Loading Themes module
> Traceback (most recent call last):
>   File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 730, in <module>
>     window = MainWindow()
>   File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 434, in __init__
>     self.go_to_sidepage(cat, path, user_action=False)
>   File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 191, in go_to_sidepage
>     sidePage.build()
>   File "/usr/share/cinnamon/cinnamon-settings/bin/SettingsWidgets.py", line 123, in build
>     self.module.on_module_selected()
>   File "/usr/share/cinnamon/cinnamon-settings/modules/cs_themes.py", line 113, in on_module_selected
>     widget.sync_initial_switch_state()
>   File "/usr/share/cinnamon/cinnamon-settings/bin/CinnamonGtkSettings.py", line 194, in sync_initial_switch_state
>     if editor.get_declaration(self.selector, decl_name):
>   File "/usr/share/cinnamon/cinnamon-settings/bin/CinnamonGtkSettings.py", line 114, in get_declaration
>     rs = self.get_ruleset(selector)
>   File "/usr/share/cinnamon/cinnamon-settings/bin/CinnamonGtkSettings.py", line 105, in get_ruleset
>     if rs.selector.as_css() == selector_css:
> AttributeError: 'ImportRule' object has no attribute 'selector
```

```

**Comment by leigh123linux** [comment]
What dstro and system arch?

**Comment by mtwebster** [comment]
What cinnamon version?  Your 'xapps' package needs updated.
