### ISSUE TITLE
Cinnamon doesn't unredirect fullscreen windows

### ISSUE THREAD

**Issue by user1-github** [linuxmint/cinnamon#9006]
```
 * Cinnamon version (4.4.3)
 * Distribution - (Mint 19.3 Beta)
 * AMD Radeon RX 580, Mesa 19.3.0-rc6 - kisak-mesa PPA
 * 64 bit
 * [xsession-errors.txt](https://github.com/linuxmint/cinnamon/files/3934072/xsession-errors.txt)


 ```

**Issue**
It seems that fullscreen unredirection doesn't work even if "disable compositing for full-screen windows" is enabled in system settings. This causes stuttering in games.

**Steps to reproduce**
Enter any game, make sure vsync is disabled in game and you'll see that there is no screen tearing.

**Comment by icarter09** [comment]
@user1-github thanks for reporting this. Can you reopen this issue in the Mint 19.3 Beta repo? Thanks.

https://github.com/linuxmint/mint19.3-beta/issues

**Comment by user1-github** [comment]
@icarter09 Reopened.

**Comment by icarter09** [comment]
@user1-github thanks. I'm going to close this ticket.
