### ISSUE TITLE
Grouped Window List got Super + <number> hotkeys removed

### ISSUE THREAD

**Issue by Hunman** [linuxmint/cinnamon#9008]
```
 * Cinnamon version: 4.4.3
 * Distribution: Arch Linux 64 bit
 ```

**Issue**
The hotkeys seem to have been removed in the 94719c2cf1525f17b38bc7356d46d5b6bb5eab59 commit

**Comment by leigh123linux** [comment]
This isn't a bug.

**Comment by Hunman** [comment]
Will it be readded either in the same or a replacement applet?

**Comment by leigh123linux** [comment]
I don't believe there any plans to readd  them or replace the applet.
