### ISSUE TITLE
Is "Cinnamenu" applet is obsolete now ?

### ISSUE THREAD

**Issue by Nokia808** [linuxmint/cinnamon#9009]
```
 * Cinnamon version (4.4.2)
   - Please specify if you are using the daily builds PPA (https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds).
 * Distribution - (Fedora 30.)
 * Graphics hardware *and* driver used
 * 64 bit
 ```

**Issue**
Today I received Cinnamon version 4.4.2

**Steps to reproduce**
After restarting my system the following error message appeared which said like this: "Cinnamon loaded okay but it seem that some applet not working ...."
After examine my applets, I noticed that all of them working except only one: "Cinnamenu"
I tried to file a bug about it, but I noticed that it is not existing in:
https://cinnamon-spices.linuxmint.com/applets

Please you recommendation: remove it or it will received udate & why not appearing in:
https://cinnamon-spices.linuxmint.com/applets

Is it obsoleting now?

**Expected behaviour**

**Other information**
Sorry for that, but it is the only place when I can asking about this issue because "Cinnamenu" not appearing on "Search" this site:
https://cinnamon-spices.linuxmint.com/applets

**Comment by leigh123linux** [comment]
Yes it's a dead applet so you will need to remove it.

https://github.com/linuxmint/cinnamon-spices-applets/commit/576ca0a9bbd264fbbc9b00c00057973d0b131541

FYI applet issues should be reported against the applet

https://github.com/linuxmint/cinnamon-spices-applets/issues

**Comment by claudiux** [comment]
@Nokia808 If you have Cinnamenu already installed, you can still use it replacing the contents of the `/.local/share/cinnamon/applets/Cinnamenu@json/metadata.json` file by:
```
{
  "uuid": "Cinnamenu@json",
  "name": "Cinnamenu",
  "description": "A flexible menu providing formatting options, web bookmarks, open window lookup, and search provider support with fuzzy searching.",
  "max-instances": 2,
  "version": "4.1.3",
  "multiversion": true,
  "website": "https://github.com/linuxmint/cinnamon-spices-applets/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+Cinnamenu%40json",
  "comments": "Made possible thanks to the efforts of contributors to the Cinnamon menu, Gnomenu, and the contributors to projects they derived from.",
  "cinnamon-version": [
    "3.2",
    "3.4",
    "3.6",
    "3.8",
    "4.0",
    "4.2",
    "4.4
  ],
  "last-edited": 1575937168
```
