### ISSUE TITLE
[Feature Request] Mixed toggle-cycle click action in Grouped Window List

### ISSUE THREAD

**Issue by pponsv** [linuxmint/cinnamon#9011]
```
 * Cinnamon version: Cinnamon 4.2.4
 * Distribution: Mint 19.2 Tina
 ```
**Issue**
There are two distinct (left) click action settings in the Grouped Window List applet: 'Toggle activation of last focused window' and 'Cycle windows'. Those two work as intended. However, a mix of those two would be the most productive, especially when working with a fullscreen application and a terminal (having some of those open at the same time), for example. 

**Steps to reproduce**

**Expected behaviour**
The desired behaviour would be:

IF not focused:
-toggle to last focused
IF focused
-cycle windows (ideally in order of last usage, but the current cycle order would also be fine)

Then, a single left click on the window group from a fullscreen window would focus to the last focused window and subsequent clicks would cycle them.

**Other information**

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
