### ISSUE TITLE
[Feature Request] Run apps on specific GPU for discrete GPUs

### ISSUE THREAD

**Issue by RBFraphael** [linuxmint/cinnamon#9014]
I'm not sure if this is the right place for this (or in Cinnamon repo)...

Ubuntu 19.10 comes with a context menu on Gnome Shell that shows up an option to select which GPU I want to run that application (I think this option only sets DRI_PRIME environment variable to 1 for that application) on discrete GPU system (like mine).

My request is about adding something like that option on all .desktop files' context menu and files with permission to run as program (the X permission). So, users who have this double GPU system can run games and apps on dedicated graphics card more easy than now (for this, now, I need to open terminal and manually set DRI_PRIME=1 and run my app/file).

Thanks! :)

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
