### ISSUE TITLE
cinnamon: Rename some keyboard shortcut key labels, some are ambiguous.

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/cinnamon#9020]
Might I note that [this problem](https://github.com/linuxmint/cinnamon-settings-daemon/issues/275) - to do with a keyboards shortcut being wrongly recorded - persists into 19.3 Cinnamon? Instructions to reproduce are included in the original bug report.

Cinnamon 4.4.2 (on the beta; but, as I say, this bug is in 19.2 as well).

**Locale**:
```
mint@mint:~$ locale
LANG=C.UTF-8
LANGUAGE=
LC_CTYPE="C.UTF-8"
LC_NUMERIC="C.UTF-8"
LC_TIME="C.UTF-8"
LC_COLLATE="C.UTF-8"
LC_MONETARY="C.UTF-8"
LC_MESSAGES="C.UTF-8"
LC_PAPER="C.UTF-8"
LC_NAME="C.UTF-8"
LC_ADDRESS="C.UTF-8"
LC_TELEPHONE="C.UTF-8"
LC_MEASUREMENT="C.UTF-8"
LC_IDENTIFICATION="C.UTF-8"
LC_ALL=
```

**Comment by mtwebster** [comment]
I've transferred this as it won't hold up the release, but I'll revisit and see about putting some aliases on a few of the key labels.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
