### ISSUE TITLE
Cinnamon sound applet not returning to normal after closing media-playing tab in Chrome

### ISSUE THREAD

**Issue by mfreeman72** [linuxmint/cinnamon#9022]
```
 * Cinnamon version: Cinnamon 4.2.4
 * Distribution - Linux Mint 19.2
 * Graphics hardware: AMD A8 GPU with Radeon R5 *and* driver used: Open Source AMD driver
 * 64 bit
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
 ```

**Issue**
While running Chrome, a page that plays media causes the sound applet to turn into a CD-shaped icon with the title of the playing media (which is expected). However, even after that page is closed and no media is playing, the applet remains a CD shape and does not return to the normal speaker-shaped icon. If I open the menu, it is still in its media player mode with the label, "Chrome - Stopped" at the top. I can no longer access any of my audio players through the menu until I competely quit Chrome, which means I cannot both fully use my sound applet and have Chrome set to allow background processes to run (such as notifications, Hangouts, or other Chrome apps) at the same time. My recommendation: When Chrome indicates that it is stopped, return the applet to its normal configuration.

**Steps to reproduce**
1. Open Chrome.
2. Open a media-playing page in a new tab (such as Youtube) and play media.
3. Observe the applet's icon is now a CD.
3. Stop playing media and close the media-playing tab, but still have Chrome or Chrome's background processes running.
4. See the applet not change back to normal.

**Expected behaviour**
After closing a media-playing Chrome tab or window, the applet should return to its normal state.

**Other information**

**Comment by icarter09** [comment]
Linux Mint 19.2 64bit
Cinnamon 4.2.4
Chrome v79.0.3945.79
Brave v1.1.21 Chromium: 79.0.3945.79

I'm not able to reproduce this issue. I do see that the Sound applet shows "(browser)-Stopped", even though I have closed out the tab that was running the audio. But I'm still able to access and use all the other media players that I have installed.

**Comment by mfreeman72** [comment]
What I meant was that the Sound Applet's "Launch Player" menu was no longer accessible. I could of course get to audio players through the normal application menu, and they will show up in the sound applet then. In this case, it's not a matter of things being made impossible, but things being made less convenient. For now, I've solved the problem by turning off Chrome's access to media controls. Not an ideal solution, but it works for the time being until a fix is found.

**Comment by smurphos** [comment]
I can reproduce this in 4.4.8 as-well with the same workaround. The problem is that the Open Player and Quit Player buttons are missing, although i guess that might be intentional if the Quit button would kill the browser entirely if present. Is annoying though as it blocks opening another music player via the applet.

**Comment by smurphos** [comment]
This upstream Chromium bug report appears relevant -it appears that there is a failure to de-register as as a player when an audio playing tab is closed - https://bugs.chromium.org/p/chromium/issues/detail?id=1016161

**Comment by smurphos** [comment]
I've tested several browser based media players in Chrome and their integration with the sound applet is poor. Play and pause work fine, but skip forward and back don't and if you stop playback with the Sound applet it can't be restarted. I think ideally Chrome and Chromium should be blacklisted in the applet so they don't integrate at all.

**Comment by icarter09** [comment]
@smurphos should this be a feature request to blacklist Chrome and Chromium?

**Comment by smurphos** [comment]
Sorry for delayed reply - yep a feature request to blacklist Chrome / Chromium and Chromium based or even better (and probably easier to maintain) the ability for users to blacklist individual players from the applet config.
