### ISSUE TITLE
Cinnamon:HiDPI Cinnamon components do not scale with font scaling

### ISSUE THREAD

**Issue by netjerykhet** [linuxmint/cinnamon#9023]
Using Gnome's 2x scaling is not suitable for HiDPI because windows consume far too much screen real estate, which defeats the purpose of having 4k screens because the screen is forced into displaying quad HD resolution in an ultra HD frame. The only viable alternative is to use Cinnamon's font scaling, which works very well in the new Cinnamon when nothing else in the UI is considered however small icons do not scale with the UII font, which makes a lot of visual prompts ineffective because they appear almost as dots.

When Gnome's 2x scaling is not being used and font scaling is, small icons should scale with the UI font. A workaround for control buttons on windows is to use a metacity 3 theme as these themes will scale window control buttons with the titlebar font but these themes do not affect Cinnamon's other icons, and they are not in good supply thus choices are limtied.

![A Screenshot from 2019-12-15 12-10-16](https://user-images.githubusercontent.com/3529932/70856867-45ecd500-1f38-11ea-8100-45fb6fa9f252.png)

In the image above, the window control buttons are correctly scaled by a metacity 3 theme but nemo's statusbar, navigation bar, and all other small icons are not so scaled. There is no simple way to increase the icon sizes without having to learn both css and image manipulation.

![B Screenshot from 2019-12-15 12-12-52](https://user-images.githubusercontent.com/3529932/70856888-a1b75e00-1f38-11ea-8bec-0b3bd886f757.png)

The image above is a zoomed view of nemo's statusbar icons. The icons are not scaled but there is significant unused real estate around the icons.

![C Screenshot from 2019-12-15 12-20-39](https://user-images.githubusercontent.com/3529932/70856901-cc091b80-1f38-11ea-93fe-156ef5425137.png)

The image above uses an exaggerated font scaling of 2.7 to highlight the lack of scaling in small icons. In addition, the panel width for displayed window titles does not scale, making the classic panel almost unusable on HiDPI screens.

**Comment by leigh123linux** [comment]
Font scaling isn't meant to scale icons.

**Comment by netjerykhet** [comment]
Well, I guess that fixes the problem of icons not scaling at all.

**Comment by JosephMcc** [comment]
I'm going to close this. What you're essentially asking is for the font scaling to provide fractional scaling of the UI. For what you want to work it would have to be done in Gtk which is out of our control.
