### ISSUE TITLE
The option to remove overlay scroll bars seems to have been removed in Mint 19.3

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/cinnamon#9027]
```
 * Cinnamon version (cinnamon --version) 4.4.5
   - Please specify if you are using the daily builds PPA (https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds). no
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) 19.3
 * Graphics hardware *and* driver used: Intel onboard
 * 32 or 64 bit: 64
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
 ```

**Issue**

On two 19.3 installations (both upgraded from 19.2), I cannot find the option to disable overlay scroll bars. The settings search function finds nothing (but then again it has very few keywords, for some reason - and so probably could not find the relevant setting on 19.2 either). I looked under Effects, which is where the Internet seems to tell me the setting should be, but it is not there. Nor is it anywhere else I looked.

**Steps to reproduce**

Try to find the scroll bar option.

**Expected behaviour**

I should be able to find that option.

**Other information**

**Comment by Odyseus** [comment]
Hello, @LinuxOnTheDesktop.

That setting has been moved a couple of Cinnamon versions ago. Look in **System Settings** > **Themes** > **Settings** > **Scrollbar behaviour**.

> The settings search function finds nothing...

If you mean the search field found at the top of the **System Settings** window, that field only searchs inside that window, not inside individual settings modules.

**Comment by LinuxOnTheDesktop** [comment]
@Odyseus 

Thank you; you enabled me to find the setting.

@JosephMcc: seemingly the existing search functionality leaves users often unable to find what they seek.

**Comment by LinuxOnTheDesktop** [comment]
Sorry to go on. but on one of my Mint 20 Cinnamon PCs, the scrollbar option seems to be missing. Cf. #9540: for, in fact, `apt install python3-tinycss2` _solves_ that problem.

However:  Mint Sources > Maintenance > [either Foreign Packages option] _does not respect the disabling of overlay scrollbars_.
