### ISSUE TITLE
The Word "Normal" Appears In Window Borders that Don't Use System Borders

### ISSUE THREAD

**Issue by dmutters** [linuxmint/cinnamon#9030]
Linux Mint Cinnamon 19.3 (64-bit)
Cinnamon 4.4.5

Themes:
  Window borders: Mint-Y-Dark
  Icons: Mint-X-Grey
  Controls: Mint-Y-Dark-Red
  Mouse Pointer: DMZ-White
  Desktop: Numix-Cinnamon-Transparent

Applets:
  Calendar
  Grouped Window List
  Keyboard
  Menu
  Network Manager
  Notifications
  Power Manager
  Removable Drives
  Show Desktop
  Sound
  Spacer
  System Tray
  XApp Status Applet
  
How to Reproduce the Problem:
1. Start with Linux Mint 19.2 (Cinnamon 64-bit).  
2. Install the affected apps.  The apps where the problem occurs seem to all be from 3rd party PPAs or otherwise side-loaded, such as Google Chrome Browser (http://dl.google.com/linux/chrome/deb/), Steam (steampowered.com), and Slack (https://packagecloud.io/slacktechnologies/slack/debian/), so the 2nd step is to install these PPAs (if available) and their apps.  
3. Upgrade to Linux Mint 19.3 (Cinnamon 64-bit).  The problem first appeared immediately after I upgraded from Mint 19.2 to 19.3, using the built-in GUI.  It is, however, possible that this problem occurs in a clean 19.3 installation, as well.
4. Reboot.
5. Open the aforementioned apps.

Expected Result:
Apps should appear as they did, before the upgrade, without "Normal" in faint white letters, in the upper-right of the window border.

What Actually Happened:
"Normal" appears in white, low-resolution print, behind or below the "Minimize", "Resize", and "Close" buttons, in the Window borders of these apps.

The problem appears to be mostly consistent among GUI apps installed from a PPA or otherwise side-loaded, such as Steam, Google Chrome, and Slack.  The issue does not appear in apps that came with Mint, as far as I can tell, nor does it appear in a few other side-loaded apps, such as VirtualBox, Krita, and Code42 CrashPlan.  The common factor may be that the apps where the problem appears draw their own window borders, instead of using system borders.

![Chrome](https://user-images.githubusercontent.com/8835007/71205228-d25c0800-2256-11ea-8e0c-dc492ca8e788.png)
![Slack](https://user-images.githubusercontent.com/8835007/71205229-d2f49e80-2256-11ea-9986-6cd0cbffaf6d.png)
![Steam](https://user-images.githubusercontent.com/8835007/71205230-d2f49e80-2256-11ea-8b79-b2dc288f6f83.png)

**Comment by dmutters** [comment]
I recently spotted a couple errors in ~/.xsession-errors that might be relevant:

`Cjs-Message: 10:34:17.785: JS LOG: [LookingGlass/error] unable to lookup icon for Slack1_1-panel
Cjs-Message: 10:34:17.798: JS LOG: [LookingGlass/error] unable to lookup icon for Slack1_1-panel`

File attached.
[xsession-errors.txt](https://github.com/linuxmint/cinnamon/files/4055197/xsession-errors.txt)

**Comment by smurphos** [comment]
Hi - see https://www.reddit.com/r/linuxquestions/comments/ex4kdy/indicator_on_top_right_stating_normal_appeared/

**Comment by dmutters** [comment]
Thanks, smurphos.  That fixed it for me.
