### ISSUE TITLE
Freezing: Mint Report: CPU 100%

### ISSUE THREAD

**Issue by ChickenSoupDiet** [linuxmint/cinnamon#9031]
For approximately the past 3 weeks our computers have been constantly freezing every couple of minutes. Today I checked with htop and noticed the Mint Report program had the CPU pegged at 100%. When I killed the MR my system stopped glitching. I checked on my wife's computer and the same thing is happening with the same end to the freezing when I killed MR. I removed MR from starting when the computer starts so I don't have to deal with it again. I hope someone can trace the MR problem and correct the excessive CPU use.

```
 * Cinnamon version (cinnamon --version)
   - Please specify if you are using the daily builds PPA (https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds).
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
 * Graphics hardware *and* driver used
 * 32 or 64 bit
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
 ```

**Issue**

**Steps to reproduce**

**Expected behaviour**

**Other information**

**Comment by leigh123linux** [comment]
Closed, file it against mintreport

https://github.com/linuxmint/mintreport/issues
