### ISSUE TITLE
Feature request: make GWL (even) less twitchy, via an 'invisible bridge'

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/cinnamon#9032]
```
 * Cinnamon version (cinnamon --version) 4.4.5
   - Please specify if you are using the daily builds PPA (https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds). No
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 19.3

 ```

**Issue**

There is a bug report entitled, 'Grouped Window List: window thumbnails are hard to use because they disappear immediately when the pointer leaves them' (#8796). That report is closed and indeed the problem is less acute than it used to me. However: in that report, mtwebster wrote that 'down the road', he might consider 'track[ing] pointer movement and basically creat[ing] an invisible 'bridge' between panel item and thumbnail' so as to further tackle the problem. Hence this feature request.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
