### ISSUE TITLE
Renaming Network Connections doesn't update until reboot

### ISSUE THREAD

**Issue by JustinOros** [linuxmint/cinnamon#9033]
```
 * Cinnamon version (4.4.5)
 * Distribution - (Mint 19.3)
 * 64 bit
 ```

**Issue**
When you rename a Network Connection, the old name is still displayed in the Notification Tray area, when the Network Manager applet icon is clicked. (however, rebooting will display the new connection name)

**Steps to reproduce**
Network Connections > + > Create > Save
Click on new connection to set the focus to it (e.g. Ethernet connection 1)
Click Sprocket icon to Edit connection
Change Connection name from "Ethernet connection 1" to anything else > Save
Close the Network Connections window
Click on the Network Manager applet icon in the Notification Area
Observe the original name of "Ethernet connection 1" is still displayed versus the new name 

**Expected behaviour**
The new Network Connection name should be displayed after a connection is renamed (without the need to reboot)

**Other information**
System:    Host: JustinsLinuxPC Kernel: 5.1.11 x86_64 bits: 64 compiler: gcc v: 7.4.0 
           Desktop: Cinnamon 4.4.5 wm: muffin dm: LightDM Distro: Linux Mint 19.3 Tricia 
           base: Ubuntu 18.04 bionic 
Machine:   Type: Desktop System: Dell product: OptiPlex 790 v: 01 serial: <filter> Chassis: 
           type: 3 serial: <filter> 
           Mobo: Dell model: 0J3C2F v: A01 serial: <filter> BIOS: Dell v: A18 date: 09/24/2013 
CPU:       Topology: Quad Core model: Intel Core i7-2600 bits: 64 type: MT MCP arch: Sandy Bridge 
           rev: 7 L2 cache: 8192 KiB 
           flags: lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx bogomips: 54280 
           Speed: 2395 MHz min/max: 1600/3800 MHz Core speeds (MHz): 1: 2449 2: 2881 3: 2544 
           4: 2083 5: 2789 6: 2192 7: 2422 8: 1925 
Graphics:  Device-1: Intel 2nd Generation Core Processor Family Integrated Graphics vendor: Dell 
           driver: i915 v: kernel bus ID: 00:02.0 chip ID: 8086:0102 
           Display: x11 server: X.Org 1.19.6 driver: modesetting unloaded: fbdev,vesa 
           resolution: 1920x1080~60Hz, 1920x1080~60Hz 
           OpenGL: renderer: Mesa DRI Intel Sandybridge Desktop v: 3.3 Mesa 19.0.8 compat-v: 3.0 
           direct render: Yes 
Audio:     Device-1: Intel 6 Series/C200 Series Family High Definition Audio vendor: Dell 
           driver: snd_hda_intel v: kernel bus ID: 00:1b.0 chip ID: 8086:1c20 
           Sound Server: ALSA v: k5.1.11 
Network:   Device-1: Intel 82579LM Gigabit Network vendor: Dell driver: e1000e v: 3.2.6-k 
           port: 3080 bus ID: 00:19.0 chip ID: 8086:1502 
           IF: eno1 state: up speed: 1000 Mbps duplex: full mac: <filter> 
           IF-ID-1: gpd0 state: down mac: N/A 
           IF-ID-2: virbr0 state: down mac: <filter> 
           IF-ID-3: virbr0-nic state: down mac: <filter> 
Drives:    Local Storage: total: 298.09 GiB used: 196.74 GiB (66.0%) 
           ID-1: /dev/sda vendor: Seagate model: ST3320413AS size: 298.09 GiB speed: 6.0 Gb/s 
           serial: <filter> 
Partition: ID-1: / size: 284.64 GiB used: 196.72 GiB (69.1%) fs: ext4 dev: /dev/dm-0 
           ID-2: swap-1 size: 7.89 GiB used: 20.0 MiB (0.2%) fs: swap dev: /dev/dm-1 
Sensors:   System Temperatures: cpu: 35.0 C mobo: N/A 
           Fan Speeds (RPM): N/A 
Repos:     No active apt repos in: /etc/apt/sources.list 
           No active apt repos in: /etc/apt/sources.list.d/bablu-boy-nutty-bionic.list 
           No active apt repos in: /etc/apt/sources.list.d/brave-browser-release-bionic.list 
           No active apt repos in: /etc/apt/sources.list.d/elementary-os-stable-bionic.list 
           No active apt repos in: /etc/apt/sources.list.d/enpass.list 
           No active apt repos in: /etc/apt/sources.list.d/google-chrome.list 
           No active apt repos in: /etc/apt/sources.list.d/insync.list 
           No active apt repos in: /etc/apt/sources.list.d/linuxuprising-java-bionic.list 
           No active apt repos in: /etc/apt/sources.list.d/microsoft-prod.list 
           Active apt repos in: /etc/apt/sources.list.d/nilarimogard-webupd8-bionic.list 
           1: deb http: //ppa.launchpad.net/nilarimogard/webupd8/ubuntu bionic main
           2: deb-src http: //ppa.launchpad.net/nilarimogard/webupd8/ubuntu bionic main
           Active apt repos in: /etc/apt/sources.list.d/official-package-repositories.list 
           1: deb https: //mirrors.syringanetworks.net/linuxmint-packages tricia main upstream import backport
           2: deb http: //mirror.os6.org/ubuntu bionic main restricted universe multiverse
           3: deb http: //mirror.os6.org/ubuntu bionic-updates main restricted universe multiverse
           4: deb http: //mirror.os6.org/ubuntu bionic-backports main restricted universe multiverse
           5: deb http: //security.ubuntu.com/ubuntu/ bionic-security main restricted universe multiverse
           6: deb http: //archive.canonical.com/ubuntu/ bionic partner
           Active apt repos in: /etc/apt/sources.list.d/signal-xenial.list 
           1: deb [arch=amd64] https: //updates.signal.org/desktop/apt xenial main
           No active apt repos in: /etc/apt/sources.list.d/slack.list 
           Active apt repos in: /etc/apt/sources.list.d/spotify.list 
           1: deb http: //repository.spotify.com stable non-free
           Active apt repos in: /etc/apt/sources.list.d/teams.list 
           1: deb [arch=amd64] https: //packages.microsoft.com/repos/ms-teams stable main
           No active apt repos in: /etc/apt/sources.list.d/virtualbox.list 
           No active apt repos in: /etc/apt/sources.list.d/vscode.list 
           No active apt repos in: /etc/apt/sources.list.d/webupd8team-java-bionic.list 
           No active apt repos in: /etc/apt/sources.list.d/ytvwld-asciiquarium-bionic.list 
Info:      Processes: 339 Uptime: 21h 43m Memory: 15.54 GiB used: 7.34 GiB (47.2%) Init: systemd 
           v: 237 runlevel: 5 Compilers: gcc: 7.4.0 alt: 5/7/8 Client: Unknown python3.6 client 
           inxi: 3.0.32

**Comment by leigh123linux** [comment]
> ```
>  * Cinnamon version (4.4.5)
>  * Distribution - (Mint 19.3)
>  * 64 bit
> ```
> 
> **Issue**
> When you rename a Network Connection, the old name is still displayed in the Notification Tray area, when the Network Manager applet icon is clicked. (however, rebooting will display the new connection name)
> 
> **Steps to reproduce**
> Network Connections > + > Create > Save
> Click on new connection to set the focus to it (e.g. Ethernet connection 1)
> Click Sprocket icon to Edit connection
> Change Connection name from "Ethernet connection 1" to anything else > Save
> Close the Network Connections window
> Click on the Network Manager applet icon in the Notification Area
> Observe the original name of "Ethernet connection 1" is still displayed versus the new name
> 
> **Expected behaviour**
> The new Network Connection name should be displayed after a connection is renamed (without the need to reboot)
> 
Cinnamon uses NetworkManager for it's networking so if you rename your connection you need to restart it.

```
sudo systemctl restart NetworkManager
```
