### ISSUE TITLE
Feature Request: Viewing/Adding Appointments in Calendar Applet

### ISSUE THREAD

**Issue by mfreeman72** [linuxmint/cinnamon#9034]
* Cinnamon version: 4.4.5
 * Distribution - Linux Mint 19.3

**Issue**
The current calendar applet is not as functional as calendar applets in other DE's. I would like to request the ability to click the time in the Cinnamon panel to pull up the calendar (as it does now), but allow the user to select a specific date (rather than just have today's date highlighted), then, below the calendar, list appointments for whatever date is highlighted. This feature was present back when Linux Mint used Gnome 2, which used Evolution for the calendaring task. Instead of using Evolution, the Cinnamon Calendar applet could use any combination of flexible solutions for the task: Evolution, Gnome Calendar, Google Calendar (sync'd through GOA), Thunderbird/Lightning, and/or local or online iCal or CSV files. In addition to viewing files, it would be nice to have the option of clicking an "Add" or "+" button to bring up a form to fill in details for new appointments, for calendar sources that allow it.

**Comment by Nebelkind** [comment]
I would like to support the request. It is a very useful and convenient feature Cinnamon is currently missing.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.

**Comment by mfreeman72** [comment]
Any news on the progress of this? It's been a year and a half since I made this feature request (and many, MANY years since I and many others have asked for this feature in various places), and I haven't seen any indication of whether or not this is being considered.

**Comment by mfreeman72** [comment]
Anything yet? It would be nice to know of any progress toward this feature.
