### ISSUE TITLE
System Reports: A minor wording issue

### ISSUE THREAD

**Issue by Sadi58** [linuxmint/cinnamon#9036]
```
 * Cinnamon version 4.4.5
 * Distribution - Mint 19.3
 * 64 bit
 ```

**Issue**
When there is something for the user to review, a little warning icon tries to catch user's attention with a tooltip message that reads: _Some **problems** were detected which require your attention._
For instance, in the case of availability of Linux Mint 19.3 the button at the bottom also contained this text: _Ignore this **problem**._
![Screenshot from 2019-12-18 20-10-39](https://user-images.githubusercontent.com/6375934/71252097-1cb3b680-2335-11ea-8dfa-8b032ddfa001.jpg)
**Expected behaviour**
I think the word **problem(s)** is not good for all cases. Perhaps the word **issue(s)** could be better.

**Comment by leigh123linux** [comment]
Filed against wrong package. 

https://github.com/linuxmint/mintreport/issues
