### ISSUE TITLE
Feature Request: Add classic mintmenu to Cinnamon desktop

### ISSUE THREAD

**Issue by ybolu** [linuxmint/cinnamon#9037]
```
 * Cinnamon version 4.4)
 * Distribution - Mint 19.3
 ```
A Feature Request:
Is it possible to integrate classic mintmenu in Cinnamon desktop or improve cinnamon menu as mintmenu? I find mintmenu more efficient, convenient, customizable and comfortable compared to cinnamon menu. 
For example, a large and customizable favorites section of mintmenu is very helpful, and you can have only the shutdown button, on the other hand cinnamon menu has a very weak favorites section and you must have either all system buttons or none. I think there is no need to explain every difference between the menus.
With every new release I check Cinnamon but the cinnamon menu makes me to stay with Mate.
Thanks.

**Comment by JosephMcc** [comment]
Thanks for the request. Mintmenu can't be integrated directly in Cinnamon. But we are always open to suggestions for the existing menu. Also check the third party menu applets available on the cinnamon spices site.
