### ISSUE TITLE
[Feature Request] Nemo - BitLocker Support

### ISSUE THREAD

**Issue by cihanisma** [linuxmint/cinnamon#9041]
## Summary
Linux has capability to browse `LUKS` encrypted partitions. However although required tools are ready as open source, there is no File Manager currently supports to browse `BitLocker` encrypted volumes. But there is a way for **Nemo** to have this feature and be the **first** to **overcome** this issue.

## Tools
[https://github.com/Aorimn/dislocker](https://github.com/Aorimn/dislocker)
[https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=dislocker-noruby](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=dislocker-noruby) [even less dependency]

## Steps

    lsblk -lno NAME,FSTYPE
lists **BitLocker** type partitions.

    dislocker /dev/$partition -u -- path_to_mount
mounts the encrypted partition. Here **Nemo** asks for `-u password`.

    sudo umount path_to_mount

Nemo ejects partition with right click or eject symbol.

**Comment by leigh123linux** [comment]
File your issue against nemo!
