### ISSUE TITLE
Menu applet: empty context menu (*without* HiDPI)

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/cinnamon#9045]
```
 * Cinnamon version (cinnamon --version) Cinnamon 4.4.5
   - Please specify if you are using the daily builds PPA (https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds). No
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) 19.3
 * Graphics hardware *and* driver used: Intel integrated 3rd gen.; mesa
 * 32 or 64 bit: 64
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
 ```

**Issue**

When I right-click an application within the main menu, the submenu that should appear does not appear. See screenshot - which shows what happens when I right-click 'applets'.

![image](https://user-images.githubusercontent.com/47056543/71312929-56fe8000-2429-11ea-98bb-f90411d67884.png)

Another screenshot, showing the result of the same action, but this time using all-standard themes:
![image](https://user-images.githubusercontent.com/47056543/71312965-b2307280-2429-11ea-9de6-67a48b8e7359.png)

**Steps to reproduce**

Unknown, but may have to do with screen resolution - see my specs, below.

It does not seem to matter *which* application I right-click - the result is always the same, i.e. wrong.

**Expected behaviour**

The menu should appear.

**Other information**

I thought there was an existing report on this but I cannot find it.

My specs:

OS: Linux Mint 19.3 Tricia x86_64
Host: 2325L19 ThinkPad X230
Kernel: 5.3.15-050315-generic
Uptime: 30 mins
Packages: 3323 (dpkg), 4 (flatpak), 7 (snap)
Shell: bash 4.4.20
Resolution: 1366x768 @ 60.02Hz [this system is _not_ Hi-DPI]
DE: Cinnamon 4.4.5
WM: Mutter (Muffin)
Icons: Paper [GTK2/3]
Terminal: gnome-terminal
CPU: Intel i5-3320M (4) @ 3.300GHz
GPU: Intel 3rd Gen Core processor Graphics Controller
Memory: 1082MiB / 7779MiB
Disk (/dev/sda2): 18G / 52G (37%)

On another computer, with a 2560x1440 screen and with Hi-DPI scaling enabled, I do not have the problem.

**Comment by icarter09** [comment]
@LinuxOnTheDesktop You are correct that is related to your screen resolution. I'm able to reproduce this issue and the screenshot when using lower resolutions then what I use by default.

**Comment by LinuxOnTheDesktop** [comment]
Curiously, though, the effective resolution of the HiDPI system - both horizontally and vertically - is less than that of the system on which I have the problem (and I do not have the problem on the HiDPI system - well, not at present; I have had it, on 19.2, in the past).

**ThinkPad X1**
Hi-DPI scaling: on
Resolution, horizontal: 2560
Resolution, vertical: 1440
Resolution, horizontal,effective (i.e. halved because of the scaling): 1280
Resolution, vertical (i.e. halved because of the scaling): 720
Has the problem? **No**

**ThinkPad X230**
Hi-DPI scaling: off
Resolution, horizontal: 1366
Resolution, vertical: 768
Has the problem? **Yes**

A third system: **Dell T1650, runing Mint Cinnamon 19.3 in a VM**
Hi-DPI scaling: off (the resolution is fairly high but the monitor is large)
Resolution, horizontal: 2560
Resolution, vertical: 1440
Has the problem? **No**

Mint 19.3 Cinnamon reslution requirements are (I believe): 1024×768. The affected machine - the X230 meets these. The X1 does not, if one is going by the _effective_ scaling.

**Comment by LinuxOnTheDesktop** [comment]
I can no longer reproduce this, on a non-HiDPI system. (I have not re-tested on a Hi-DPI system. But this bug report is for the former.) The version of Cinnamon on which I tried to reproduce it was 4.4.8 (whereas I reported the bug against Cinnamon 4.4.5).
