### ISSUE TITLE
Feature Request: create customizing option for entries in menu->Places and in Nemo sidebar

### ISSUE THREAD

**Issue by oldtomdevel** [linuxmint/cinnamon#9049]
When upgrading from Linux Mint 19.2 and Cinnamon 4.2.4 to Linux Mint 19.3 and Cinnamon 4.4.5, the mint menu received additional entries in the Places section, namely "Desktop", "Home" and "Connect to...".
This may be beneficial for some people, but other might consider those new entries as unnecessary and annoying. Therefore, it would be nice to have a customizing option in order to choose the entries in "Places" which come additionally to the Nemo bookmarks.
A similar situation is given for the sidebar in Nemo. There are not only Nemo's bookmarks but also the entries "Home" and "Desktop". Again, an option to cutomize the entries would be very much appreciated.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
