### ISSUE TITLE
GWL: Duplicated entry when app executed via terminal

### ISSUE THREAD

**Issue by Mikaka27** [linuxmint/cinnamon#9054]
```
 * Cinnamon version: Cinnamon 4.4.5
   - Not using ppa
 * Distribution - Mint 19.3
 * Nvidia Geforce GTX 1660 Ti on 440.44 driver
 * 64 bit
 ```
[xsession-errors.txt](https://github.com/linuxmint/cinnamon/files/3997915/xsession-errors.txt)

**Issue**
Duplicated entry on grouped window list for firefox installed via snap package.

**Steps to reproduce**
1. Open firefox normally (via pinned shortcut) on grouped window list
![1](https://user-images.githubusercontent.com/9214100/71407657-f5fac600-263b-11ea-9bb6-a4204dccfc34.png)
You can see that running firefox instance is properly connected to it's entry on GWL (ie there's only one firefox there).

2. Close the firefox and run it via terminal with "snap run firefox".
![2](https://user-images.githubusercontent.com/9214100/71407703-1c206600-263c-11ea-9f2c-221cb7965e94.png)

3. Now there are two firefox entries on GWL, somehow it didn't find itself there, and created a new entry.
![3](https://user-images.githubusercontent.com/9214100/71407739-30646300-263c-11ea-820b-7e9664d9d307.png)

**Expected behaviour**
Application should always be connected to it's pinned shortcut on GWL, regardless of the way it's executed.

**Other information**
I think it may be related with this issue (as to why I saw 2 firefox entries there):
https://github.com/linuxmint/cinnamon/issues/8950

**Comment by icarter09** [comment]
Mint 20 64bit
Cinnamon v4.6.7

I was unable to reproduce this issue. @Mikaka27 are you still experiencing this issue? Thanks.
