### ISSUE TITLE
Run Dialog: Entering an empty command no longer opens the File Manager

### ISSUE THREAD

**Issue by aaronmdjones** [linuxmint/cinnamon#9055]
For several years now I have relied upon the behaviour where `Alt+F2 Return` would open your File Manager (e.g. Nemo). This appears to have been broken by commit e0c0a8fc2e0e. Is this intentional?

**Comment by smurphos** [comment]
Looks like it - the behaviour you relied on was regarded as a bug here - https://github.com/linuxmint/cinnamon/issues/8593

You've still got the default keyboard shortcut for opening nemo - <Super>+e

**Comment by aaronmdjones** [comment]
I remapped my (only) `Super` key to `Context`, as my laptop keyboard lacks a dedicated `Context` key and I use the context ("right-click") menu on files a lot.

`Alt+F3` doesn't appear to be used for anything, so I'll use that if indeed this was never intended to be a Thing.
