### ISSUE TITLE
Super+number doesn't work anymore

### ISSUE THREAD

**Issue by MythikAngel** [linuxmint/cinnamon#9056]
```
 * Cinnamon version (cinnamon --version)
   - 4.4.3
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
    - Both Linux Mint 19.3 and Manjaro Cinnamon 18.1.4-191210
 * 32 or 64 bit
   - 64bit
 ```

**Issue**

In Mint 19.2 (Cinnamon version 4.2.3) I regularly use the keyboard shortkey Super (the button with the Windows flag on it) + a number to open the corresponding program in the panel. For example, Super+1 opens the first program, Super+2 the second etc.

However, this doesn't seem to work anymore in Linux Mint 19.3 Cinnamon. Super+a number seems to act as just a normal number keypress. It also doesn't work in the Cinnamon version of Manjaro Linux.

**Steps to reproduce**

Press super + a number key (for example 1)

**Expected behaviour**
The corresponding program in the panel would open

**Comment by leigh123linux** [comment]
Closed #9028
