### ISSUE TITLE
GWL: super-space yields visual artefacts 

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/cinnamon#9067]
```
 * Cinnamon version (cinnamon --version) 4.4.6
   - Please specify if you are using the daily builds PPA: no.
     (https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds).
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 19.3
 * Graphics hardware *and* driver used: Intel & Mesa
 * 32 or 64 bit: 64
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
 ```

**Issue**

Pressing super-space a few times yielded this:

![image](https://user-images.githubusercontent.com/47056543/71549234-ee2b8080-29b1-11ea-8227-771a9948c4f7.png)

i.e. two tooltips, and a thumbnail - and for several seconds all of that was stuck on the screen. After a while, the thumbnail disappeared, but the tooltips did not.

**Steps to reproduce**

Use GWL.
Press super-space several times.

**Expected behaviour**

Thumbnails should disappear when their timeout is reached or at least when super-space is pressed again. Tooltips should not be persistent.

**Other information**

The Cinnamon (Looking Glass) log seemed to contain nothing relevant.

OS: Linux Mint 19.3 Tricia x86_64 
Host: 20KHCTO1WW ThinkPad X1 Carbon 6th 
Kernel: 5.3.18-050318-generic 
Uptime: 5 hours, 27 mins 
Packages: 3190 (dpkg), 14 (flatpak), 4 (snap) 
Shell: bash 4.4.20 
Resolution: 2560x1440 @ 60.01Hz 
DE: Cinnamon 4.4.6 
WM: Mutter (Muffin) 
WM Theme: N_Cinn (N_Cinn) 
Theme: Mint-Y-Dark [GTK2/3] 
Icons: Paper [GTK2/3] 
Terminal: gnome-terminal 
CPU: Intel i7-8550U (8) @ 4.000GHz 
GPU: Intel UHD Graphics 620 

**Configuration info, if applicable**

[gwl_settings.json.txt](https://github.com/linuxmint/cinnamon/files/4007434/gwl_settings.json.txt)

**Comment by smurphos** [comment]
I can reproduce this intermittently. Opening GWLs config, making some change and closing it again seems to cure it for the rest of the session.

**Comment by mtwebster** [comment]
partially fixed, leaving this open
