### ISSUE TITLE
VirtualBox: symbolic panel icons do not heed their size setting

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/cinnamon#9069]
```
 * Cinnamon version (cinnamon --version) 4.4.6
   - Please specify if you are using the daily builds PPA: no.
     (https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds).
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 19.3, in VirtualBox 6.1.0 on Windows 10
 * Graphics hardware *and* driver used: VirtualBox; on the Windows host PC, Nvidia.
 * 32 or 64 bit: 64
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
 ```

**Issue**

Symbolic panel icons are too small; telling the system to englarge them does nothing, even after restarting Cinnamon. Screenshot (containing further configuration information, and - bottom right - showing the symbolic icons):

![image](https://user-images.githubusercontent.com/47056543/71560498-8ed97900-2a62-11ea-85a5-54505784db05.png)

**Steps to reproduce**

Run Mint 19.3 in VirtualBox. Try to change size of the panel's symbolic icons. However: the problem may depend on screen resolution (note:Hi-DPI scaling is not enabled) or upon something else. The installation at issue is fairly vanilla, though it was upgraded, in-place, from Mint 19.2.

**Expected behaviour**

Sumbolic icons should be an appropriate size or at least changeable to such a size.

**Comment by Odyseus** [comment]
Hello, @LinuxOnTheDesktop.

Did you changed that value in the right place? In your screenshot, you are changing the symbolic icon size for the left panel zone. You should switch to the right panel zone and change the symbolic icon size there.

**Comment by LinuxOnTheDesktop** [comment]
Oh. My mistake. I am sorry for wasting your time. Thank you, @Odyseus.
