### ISSUE TITLE
Themes module in cinnamon-settings doesnt't open

### ISSUE THREAD

**Issue by AdrianTwo** [linuxmint/cinnamon#9073]
```
 * Cinnamon version: Cinnamon 4.4.6
   -  Regular one from Mint 19.3 release
 * Linux Mint Cinnamon 19.3
 * Nvidia GTX 1050 and Nvidia Driver 440.44
 * 64 Bit
 ```

**Issue**
The themes module in the settings can't be opened anymore. When trying to open the themes module, the cinnamon-settings window freezes and doesn't respond anymore. This issue appeared after updating Linux Mint Cinnamon from 19.2 to 19.3. The following output is generated, when trying to open the themes module from the command line:

 ```
adrianone@adrian-linux-pc:~$ sudo cinnamon-settings themes
[sudo] Password for adrianone: 
True
Using PAM module (python3-pam)
Loading Themes module
[Errno 2] File or directory not found: '/home/adrianone/.themes/vimix-doder/metadata.json'
Skipping vimix-doder: there was a problem trying to read metadata.json


[...] Same errors, only with different themes.


[Errno 2] File or directory not found: '/home/adrianone/.themes/vimix-ruby/metadata.json'
Skipping vimix-ruby: there was a problem trying to read metadata.json
Traceback (most recent call last):
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 726, in <module>
    window = MainWindow()
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 431, in __init__
    self.go_to_sidepage(cat, path, user_action=False)
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 188, in go_to_sidepage
    sidePage.build()
  File "/usr/share/cinnamon/cinnamon-settings/bin/SettingsWidgets.py", line 213, in build
    self.module.on_module_selected()
  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_themes.py", line 160, in on_module_selected
    self.refresh()
  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_themes.py", line 192, in refresh
    self.refresh_chooser(payload)
  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_themes.py", line 245, in refresh_chooser
    if os.path.exists(theme_path):
  File "/usr/lib/python3.6/genericpath.py", line 19, in exists
    os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
 ```
**Steps to reproduce**
Opening the themes module in any way (with the gui or the terminal).
**Expected behaviour**
The window should open and themes, icons, cursors, etc. should be able to changed.
**Other information**
Everything is updated.

**Comment by claudiux** [comment]
@AdrianTwo Try this:
``` 
cp /home/adrianone/.themes/vimix-ruby/cinnamon/metadata.json /home/adrianone/.themes/vimix-ruby/metadata.json
cinnamon-settings themes
```
 (without sudo).

**Comment by AdrianTwo** [comment]
> @AdrianTwo Try this:
> 
> ```
> cp /home/adrianone/.themes/vimix-ruby/cinnamon/metadata.json /home/adrianone/.themes/vimix-ruby/metadata.json
> cinnamon-settings themes
> ```
The command didn't work, because in my themes a `metadata.json` doesn't exist. I also tried to open those settings with Spices Update applet, but that also didn't work.

**Comment by claudiux** [comment]
@AdrianTwo Then, try to create the `/home/adrianone/.themes/vimix-ruby/metadata.json` file containing:
```
{
  "last-edited": 1577659316
}
```

**Comment by AdrianTwo** [comment]
@claudiux I tried this, and removed all other theme-directories, but I still get the Python Errors. Only the error about files not found disappeared.

**Comment by claudiux** [comment]
@AdrianTwo Where can I find the zip file for this theme, please?

**Comment by claudiux** [comment]
@AdrianTwo Maybe related? https://github.com/linuxmint/cinnamon/issues/9044

**Comment by AdrianTwo** [comment]
@claudiux Yes, it is the same issue and I think it got solved there

**Comment by claudiux** [comment]
@AdrianTwo I think you can close this issue now: https://github.com/linuxmint/cinnamon/releases/tag/master.mint19
