### ISSUE TITLE
Regression: Alt+F2 misbehaves on invalid command

### ISSUE THREAD

**Issue by hayounav** [linuxmint/cinnamon#9075]
```
 * Cinnamon version : 4.4.6
   - Please specify if you are using the daily builds PPA: No
 * Distribution: Mint 19.3
 * Graphics hardware *and* driver used (Output of lshw -numeric -C display): 
       description: VGA compatible controller
       product: Xeon E3-1200 v3/4th Gen Core Processor Integrated Graphics Controller [8086:412]
       vendor: Intel Corporation [8086]
       physical id: 2
       bus info: pci@0000:00:02.0
       version: 06
       width: 64 bits
       clock: 33MHz
       capabilities: msi pm vga_controller bus_master cap_list rom
       configuration: driver=i915 latency=0
       resources: irq:27 memory:f7800000-f7bfffff memory:e0000000-efffffff ioport:f000(size=64) memory:c0000-dffff

 * 64 bit
 ```

**Issue**
This is a regression between 4.4.5 and 4.4.6.
If you open Alt+F2 overlay and execute an invalid command, the overlay gets "stuck".
This overlay only intercepts mouse actions on the panel and panel applets, but not other applications.
The overlay does not intercept keyboard events.
Alt+F2 does not work anymore once the overlay got stuck.
The only way I found to get rid of this is to logout and log in (I don't know how to restart cinnamon using only the keyboard).

**Steps to reproduce**
Alt+F2
Try to execute any invalid command (e.g. `ecmas` instead of `emacs`)

**Expected behaviour**
An error message, like it used to.

**Other information**
I assume all the `GLib-GObject-CRITICAL` errors at the end of the log are the relevant bits, but I included the log of a whole session, just in case.
[issue.log](https://github.com/linuxmint/cinnamon/files/4009231/issue.log)

**Comment by smurphos** [comment]
I can reproduce this.

@hayounav - In the meantime keyboard shortcut Ctrl-Alt-Esc will restart Cinnamon to get out of the stuck entry.
