### ISSUE TITLE
(ALT + F2) Run window is broken 

### ISSUE THREAD

**Issue by gustavomassa** [linuxmint/cinnamon#9076]
* Cinnamon version (cinnamon --version) - 4.4.6
 * Distribution - Mint 19.3
 * Graphics hardware *and* driver used - Nvidia GTX 1070 - version 430.50-0ubuntu0.18.04.2
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
[xsession-errors.txt](https://github.com/linuxmint/cinnamon/files/4011159/xsession-errors.txt)
![screen](https://user-images.githubusercontent.com/16235598/71601920-6e79ef00-2b34-11ea-8bc9-a84af595c0fa.png)

**Issue**
ALT + F2 run menu is broken after typing anything.

**Steps to reproduce**
Press ALT + F2, then type "Downloads" and hit ENTER, the window should get stuck forever, you need to kill cinnamon and start again.

**Comment by claudiux** [comment]
@mtwebster Sorry, but your commit only fixes partially this bug. If the path doesn't exist, an error message appears and the user can not close this ALT-F2 window.

**Comment by mtwebster** [comment]
That works fine for me.  If I type gibberish into the entry, it gives an error but allows me to fix or cancel.

**Comment by claudiux** [comment]
Yes, I can fix the text. To cancel, I must press the Esc key. By clicking on the "-" button or elsewhere on the screen, the ALT-F2 window remains visible and Cinnamon appears frozen.

**Comment by JosephMcc** [comment]
It's always been this way. You needed 'Esc' to close. The icon is just that, not a button.

**Comment by gustavomassa** [comment]
Thank you for the fast commit. I did not know that UI logic was written in js, I just edited my /usr/share/cinnamon/js/ui/runDialog.js, I can confirm that the commit fixed the issue.
