### ISSUE TITLE
https://cinnamon.linuxmint.com/ certificate problem

### ISSUE THREAD

**Issue by Neustradamus** [linuxmint/cinnamon#9078]
-> https://cinnamon.linuxmint.com/

Certificate problem.

**Comment by leigh123linux** [comment]
@clefebvre

**Comment by Neustradamus** [comment]
Already solved?

It is better to close a ticket when it is solved not before.

**Comment by leigh123linux** [comment]
@Neustradamus  I closed it because it isn't a cinnamon issue.

**Comment by Neustradamus** [comment]
Where we can publish problem of the website? ;)
Before it, it is better to do not close this ticket...

**Comment by leigh123linux** [comment]
@Neustradamus Stop the spam, Clem is on holiday and will fix it when he returns!

**Comment by clefebvre** [comment]
Hi @Neustradamus, I'm on it.

Where did you find the link to this domain? It shouldn't exist anymore... 

PS: For global Mint issues you can use github.com/linuxmint/linuxmint.
