### ISSUE TITLE
Expand max-workspaces number limit from 36 to 56. Don't judge me :)

### ISSUE THREAD

**Issue by MaDDmin** [linuxmint/cinnamon#9082]
```
Cinnamon 4.4.6
Linux Mint 19.3
Intel Corporation Device 3ea0 (prog-if 00 [VGA controller])
Intel© Core™ i7-8565U CPU @ 1.80GHz × 4 (64 bits)
```

**Issue**

I want my system to remember my 56 workspaces. It lets me work with them but next time I reboot their number go back to 36.

**Steps to reproduce**

Trivial.

**Expected behaviour**

It should be expected to keep having 56 workspaces after a reboot.

**Other information**

Also, this number can't be established manually with dconf nor gsettings:
`gsettings set org.cinnamon.desktop.wm.preferences num-workspaces 56`
produces this output:
`The provided value is outside of the valid range`

**Comment by mtwebster** [comment]
Edit (as root): `/usr/share/glib-2.0/schemas/org.cinnamon.desktop.wm.preferences.gschema.xml`

Look for 'num-workspaces', change range max from 36 to 56 or whatever, save, run:
```
glib-compile-schemas /usr/share/glib-2.0/schemas
```

You'll need to do this after any muffin update for now.

**Comment by MaDDmin** [comment]
Thanks a lot, @mtwebster! That was exactly the solution I was looking for.
