### ISSUE TITLE
Systray & Xapp icons dual monitor setup

### ISSUE THREAD

**Issue by iongigi** [linuxmint/cinnamon#9083]
```
 * Cinnamon 4.4.6
    Linux Mint 19.3 64bit

 ```

**Issue**
I have dual monitor setup: 2560x1440 (as primary) and  1920x1080
When I click (or right click) on primary display on an icon from tray (update manager,whatsapp desktop etc), a blank menu is open with an arrow at the bottom. The menu is open about 300px above the panel. If I place the mouse cursor over the arrow the menu is displayed after 5 seconds. 

On the second monitor everything works as expected.
Also, if I set the other monitor as primary, everything works as expected.

Other icons (bluetooth) shows menu but with the same distance from panel, (printers,keyboard works ok)

**Configuration info, if applicable**
If this bug report is related to an Applet, Desklet or Extension, please paste (or use a pastebin service) the offending extension's settings, if it has any.  You can obtain this by opening its configuration, clicking the 'hamburger' button in the upper-right corner of the window, and selecting "Export to a file". **Please be sure to review the contents and remove any personal data it may contain.**

```

Please paste here

```

**Comment by mtwebster** [comment]
Couple of questions to help me reproduce this:

- What is the monitor arrangement?  primary on left or right?
- What is the alignment of the monitors?  Is the top edge of the smaller monitor aligned with the top edge of the large?  Or bottom with bottom? Or somewhere in between?
- I assume this is a bottom panel that it's occurring on?

Thanks

**Comment by iongigi** [comment]
Hello,
Primary is on left. The monitors are pretty much aligned , both are 27 inch. 
This behavior appears also when I use laptop's display(HD resolution) with the monitor with 2k resolution
I think this video will help: [http://83.103.240.34/video.html](url)

**Comment by iongigi** [comment]
I misinterpreted your question about aligning monitors. I was thinking of physical alignment(!?!!)  not in the display panel. After I aligned them down it goes well
