### ISSUE TITLE
[Feature Request] Display mode switcher box

### ISSUE THREAD

**Issue by genjuurou** [linuxmint/cinnamon#9088]
```
 * Cinnamon version (cinnamon --version) 4.4.6
 * Distribution - Linux Mint 19.3
 ```

**Feature**
Add display mode switcher box to switch display mode action [called "Re-detect display devices" in keyboard shortcuts] (super + p).

**Description**
Currently user needs to go through all modes (and apply them one by one) to select desirable one. Creating display mode switcher box will allow user to get straight to the desirable mode. I attach examples from other DEs below:

Gnome display mode switcher - (super + p) causes cycling through all modes (without applying them).
![gnome_display_switcher](https://user-images.githubusercontent.com/54631723/71725291-a1bdc600-2e33-11ea-8601-5d1a9e03f324.png)

KDE display mode switcher - (super + p) shows display switcher box in which user can select desirable mode (using mouse or keyboard).
![kde_display_switcher](https://user-images.githubusercontent.com/54631723/71725316-b5692c80-2e33-11ea-8c39-83132f6e83ec.png)

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.

**Comment by cookyt** [comment]
Did anything ever come of this FR? I want the same thing, and would like to know if there's a setting I need to enable, or if I sound find a different work-around.
