### ISSUE TITLE
Feature request (or possibly bug): require confirmation for removing a panel

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/cinnamon#9092]
```
 * Cinnamon version (cinnamon --version): 4.4.6
   - Please specify if you are using the daily builds PPA: no
     (https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds).
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 19.3
 * Graphics hardware *and* driver used: Irrelevant
 * 32 or 64 bit: 64
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
 ```

**Issue**

Am I right in thinking that, by design, no confirmation is needed to remove a panel? So, one can have a load of applets, carefully arranged and configured and then in one mis-click - all gone?

**Steps to reproduce**

Create new panel. Add applet(s). Click 'remove' in panel context menu,

**Expected behaviour**

Being asked for confirmation.

**Other information**

I can reproduce the current behaviour on two systems.

**Comment by JosephMcc** [comment]
Well it isn't a bug but certainly a decent suggestion. There is currently only a confirmation if you remove the last panel and will leave yourself with none. Closing this since it falls in the feature request category. Thank you.
