### ISSUE TITLE
System tray hides icons, fails to launch properly

### ISSUE THREAD

**Issue by brennie** [linuxmint/cinnamon#9097]
* Cinnamon version: 4.0.10 (from Ubuntu Eoan repo)
 * Distribution - Ubuntu 19.10
 * Intel integrated graphics
 * 64 bit

* Relevant bit of .xsession-errors:

```
Cinnamon warning: Log level 8: g_object_get: assertion 'G_IS_OBJECT (object)' failed
Cjs-Message: 15:53:49.410: JS LOG: [LookingGlass/info] Reloading applet: keyboard@cinnamon.org/5
Cjs-Message: 15:53:49.411: JS LOG: [LookingGlass/info] Reloading applet: notifications@cinnamon.org/6
Cjs-Message: 15:53:49.412: JS LOG: [LookingGlass/info] Reloading applet: removable-drives@cinnamon.org/7
Cjs-Message: 15:53:49.413: JS LOG: [LookingGlass/info] Reloading applet: user@cinnamon.org/8
Cjs-Message: 15:53:49.413: JS LOG: [LookingGlass/info] Reloading applet: network@cinnamon.org/9
Cjs-Message: 15:53:49.414: JS LOG: [LookingGlass/info] Reloading applet: power@cinnamon.org/11
Cjs-Message: 15:53:49.415: JS LOG: [LookingGlass/info] Reloading applet: calendar@cinnamon.org/12
Cjs-Message: 15:53:49.415: JS LOG: [LookingGlass/info] Reloading applet: sound@cinnamon.org/13
Cinnamon warning: Log level 8: cinnamon_tray_manager_manage_stage: assertion 'manager->priv->stage == NULL' failed
Cjs-Message: 15:53:49.689: JS LOG: Unknown network device type, is 14

(csd-power:7288): power-plugin-CRITICAL **: 15:53:49.703: abs_to_percentage: assertion 'max > min' failed
Cinnamon warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x62000f8 (xsession-e)
```

**Issue**
This is a dupe of #8637

When adding the system tray applet, the following error appears in a cancel icon in the applet:

```Something went wrong while loading systray@cinnamon.org. Please make sure you are using the latest version, then report the issue to the developers.```

**Steps to reproduce**

Go to Cinnamon menu
Type Applets
Open Applets
Go to Manage tab
Find System tray
Disable
Enable
It has a stop icon
Mouse over
See message tooltip with error

**Expected behaviour**

The systray should work.

**Comment by icarter09** [comment]
Cinnamon 4.4.8
Mint 19.3
64bit

Followed the steps and verified that the issue still exists.

**Comment by TitaniumCoder477** [comment]
Also reproduced on:
Cinnamon 4.4.8
Ubuntu 20.04 focal (x86-64)
64bit

**Comment by queenkjuul** [comment]
I am also able to reproduce this on:

Ubuntu 20.10 x86_64
Cinnamon 4.6.7

With Intel i915 graphics driver on HD5500 gpu
