### ISSUE TITLE
Feature request: in some fashion, combine the two lots of notification settings

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/cinnamon#9098]
```
 * Cinnamon version (cinnamon --version) 4.4.8
   - Please specify if you are using the daily builds PPA: no
     (https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds).
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 19.3
 * Graphics hardware *and* driver used
 * 32 or 64 bit
 ```

Say you want to change a setting for notifications. Is the setting you want (let's say it is 'ignore transient notifications) in the configuration menu of the notification applet? Is the setting instead in System Settings -> Notifications? Are you even aware that there are two lots of settings?

Here's a screenshot of the two settings windows, when they are placed side by side:
![image](https://user-images.githubusercontent.com/47056543/72022501-7f2f1100-3268-11ea-9a6a-eec91f063873.png)

If the two lots of settings can't or should not be unified - and one is for an applet, after all - then at least have a link, in the applet's settings, to the system settings, and - at least if the notifications applet is in use? - vice-versa.

**Comment by claudiux** [comment]
The `Media keys OSD size` parameter seems do not have effect.

**Comment by LinuxOnTheDesktop** [comment]
@claudiux 

It does have an effect on the two systems I've tried it on - each setting within that option produces a different effect.

Anyhow, that's a separate topic, no?

**Comment by Odyseus** [comment]
Hello, everybody.

@LinuxOnTheDesktop: In my opinion, those settings are right where they belong. What the applet called **Notifications** actually is is a *notifications tray*. The two options that the applet contains are related to the applet itself, not the notifications themselves in the global sense.

A shortcut to **System Settings** > **Notifications** either in the applet context menu, its settings window or both wouldn't hurt.

I think that if anything needs to be fixed, it should be the name of the applet itself (from **Notifications** to **Notifications tray**). Dumbed down *Gnome nomenclature* is fine for newbies, until it causes more *damage* than good.

@claudiux: The setting that you mention (**Media keys OSD size**) works normally in my LM 19.3 (Cinnamon 4.4.8) system. Maybe you are using a Cinnamon theme that hardcodes the size for the `osd-window` class (just a *shot in the dark*...I don't know if that would actually cause the issue that you are experiencing)?

**Comment by claudiux** [comment]
@Odyseus Yes, you're right. I thought that this parameter acted on the size of the multimedia icons (representing keys) which appear in a notification when changing the song, and not on the size of the icons which appear on the screen when you press one of the multimedia keys of the keyboard.

@LinuxOnTheDesktop Sorry for polluting this issue.
