### ISSUE TITLE
Feature Request: Use Variety to manage backgrounds

### ISSUE THREAD

**Issue by BeatLink** [linuxmint/cinnamon#9099]
A suggestion of mine, rather than having the backgrounds settings in cinnamon-settings, you could instead install variety by default and use that to manage the backgrounds. Variety supports automatic downloading of images from different sources, a clock, effects, quotes and tons more. It would ease development by eliminating the need for an in house background manager.

**Comment by leigh123linux** [comment]
I'm -1 for this change as I don't want to rely on a third-party package.
Maybe adding an option to disable cinnamon backgrounds would be a better option, that would give users the choice to use third-party background packages.

**Comment by BeatLink** [comment]
I'm okay with the ability to disable the cinnamon backgrounds, or better yet move it to a separate package like cinnamon-settings-backgrounds

**Comment by leigh123linux** [comment]
> I'm okay with the ability to disable the cinnamon backgrounds, or better yet move it to a separate package like cinnamon-settings-backgrounds
I don't want an additional package, FYI  the backgrounds are part of c-s-d.

https://github.com/linuxmint/cinnamon-settings-daemon/tree/master/plugins/background

**Comment by BeatLink** [comment]
ohh okay, thanks

**Comment by brownsr** [comment]
I can't see us wanting to move a core part of Cinnamon functionality to a third party package that is not under our control.  Third party packages often struggle to be consistently maintained over time, or development might go off on a route that could make it incompatible.  And as you can see from Leigh's link, that section of code has been unchanged for nearly two years, so it's currently pretty stable, and we like stability ;-)

**Comment by BeatLink** [comment]
Ahh okay.

**Comment by BeatLink** [comment]
I was  wondering if its possible, as an alternative, to install variety by default?

**Comment by JosephMcc** [comment]
No need to reopen this. Installing a package by default would be something for distros to decide. Not as part of Cinnamon itself.
