### ISSUE TITLE
Feature Request: Add Dock option for cinnamon panels that dynamically scale width

### ISSUE THREAD

**Issue by BeatLink** [linuxmint/cinnamon#9100]
A suggestion to add a dock option to cinnamon's panel settings. When activated, the panel will dynamically adjust its width to fit its contents, like other docks such as docky, or plank dock or cairo dock.

**Comment by brownsr** [comment]
The panel already does this, it's just that where the side and centre panels are all opaque and the same colour it is not visible.  However if you install a theme that has transparent side panels you will see this in action.  Try my 'simpledock' theme in the Spices themes, for example.

Regards

Simon

**Comment by LinuxOnTheDesktop** [comment]
'The panel already does this'. One problem is: one cannot make transparency a per panel setting.

**Comment by BeatLink** [comment]
I'm kindly requesting that this issue be reopened, This is a highly requested feature that is already supported on several other desktop environments including Gnome, KDE, Enlightenment and XFCE.

Solving this via themes drastically limits the number of themes available for those who want this functionality. Themes should be focused on a desktop environment's appearance and be agnostic as to whether the UI element is a panel or a dock.
