### ISSUE TITLE
Feature Request: Add API/SDK for lockscreen widgets

### ISSUE THREAD

**Issue by BeatLink** [linuxmint/cinnamon#9101]
As there are dedicated SDks and repositories for applets, desklets and extensions, it would be cool if there was an API or SDK for lockscreen widgets, along with updatable repositories.

**Comment by leigh123linux** [comment]
What's SDK go to do with cinnamon or it's applets, desklets and extensions?
They are all jscript.

**Comment by BeatLink** [comment]
Ahh, well i meant having an option in cinnamon-settings to download, enable and disable the widgets, along with a repo. There was also a js cinnamon api that needed to be imported by applets that stated certain functions to use to enable, disable and start the applets if i recall.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
