### ISSUE TITLE
Black bar above cinnamon panel

### ISSUE THREAD

**Issue by genjuurou** [linuxmint/cinnamon#9108]
```
 * Cinnamon version (cinnamon --version): 4.4.8
   - Please specify if you are using the daily builds PPA: No
 * Distribution: Linux Mint 19.3
 * Graphics: Intel HD 3000 *and* Driver: i915
 * 64 bit
 ```

**Issue**
While using external screen in "only external display" mode hovering over icons on panel causes 1px black bar to appear.

![cinnamon_panel_bug](https://user-images.githubusercontent.com/54631723/72208699-4ed4b600-34a6-11ea-9f6f-f502b8c0d3ae.png)

**Steps to reproduce**
1. Turn on laptop without external display connected
2. Log in
3. Connect external display
4. Press (super + p) to navigate to "only external display" mode
5. Hover over the icon

**Expected behaviour**
No black bar like in other display modes.

**Other information**
This issue happens only if external display is not connected while turning on laptop and only in "only external display" mode. Sometimes connecting it before logging in (on greeter or splash screen) can cause this behaviour too.

**Comment by icarter09** [comment]
Cinnamon 4.4.8
Mint 19.3
64bit

I'm not able to reproduce this issue. I'm using a VGA connector for the external monitor to the laptop. I also tinkered with Panel height and symbolic icon size to see if either of them would help to recreate the issue. 

@genjuurou let me know if there is any settings that you want me to try out or adjust.
