### ISSUE TITLE
Error launching cinnamon display settings.

### ISSUE THREAD

**Issue by Maybegus** [linuxmint/cinnamon#9110]
I am running linux mint 19.3 64 bit on my laptop with a usb c dock attached with a hdmi monitor connected to that. Whenever i try to run cinnamon-settings i get this back:

$ cinnamon-settings display
True
Using PAM module (python3-pam)
Loading Display module
**
CinnamonDesktop:ERROR:../../libcinnamon-desktop/gnome-rr-config.c:666:gnome_rr_config_load_current: assertion failed: (gnome_rr_config_match (config, config))
Aborted (core dumped)

i am using
cinnamon 4.4.5

**Comment by icarter09** [comment]
@Maybegus do you get this error when the laptop is not using the dock?
