### ISSUE TITLE
Drifting Icons on Desktop

### ISSUE THREAD

**Issue by rosenbergd** [linuxmint/cinnamon#9113]
## Setup

 - Cinnamon version: 4.4.8
 - Distribution: Linux Mint 19.3
 - Graphics hardware and driver: GTX 1050 with Nvidia Proprietary Drivers v440.44 with Cuda 10.2.89
 - Architecture: 64 bit

## Issue

On the desktop, when there is an image or other icon that is significantly wider than its height, on restart, the icon drifts when refreshing the desktop (with each refresh, the icon strays further and further from its original position until it's dragged back into place manually)

## Steps to reproduce

Put an image that's very wide so that it is bigger than the maximum text length that fits on a line (on the desktop), then restart and press F5 multiple times, it will move with each refresh

## Expected behaviour

The icon should not try to escape me, there is no escape! (this is most likely due to icon slot sizes on the desktop not handling an icon that is too wide)

**Comment by KMetalmind** [comment]
I can confirm this still happens from Mint 20.03 to Mint 21.1. It not only happens with images, it happens with any icon that is a preview (for example, .pdf .ods etc). They don't need to be wide, just not be a normal icon. I have an .ods whose preview has less width and height, but it still moves with each refresh.

**Comment by rosenbergd** [comment]
I've noticed that this issue is now worse, I'm now on Mint 20.3 and it seems like anything that has a preview as an icon has this issue, at least for me.

**Comment by rosenbergd** [comment]
This issue seems to be in nemo-desktop from the research I've done, here are 2 issues on the nemo repo related to this:

- [Nemo Issue #3088 - The thumbnail of the image files are pushed](https://github.com/linuxmint/nemo/issues/3088)
- [Nemo Issue #2678 - Refreshing the desktop with thumbnail width larger than the grid cell size causes the icon to move left
](https://github.com/linuxmint/nemo/issues/2678)
