### ISSUE TITLE
drag and drop from one smb share to another does not work

### ISSUE THREAD

**Issue by illumilore** [linuxmint/cinnamon#9114]
```
 * Cinnamon version (cinnamon --version)
Cinnamon 4.4.8

   - Please specify if you are using the daily builds PPA
     (https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds).
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
mint 19.3
 * Graphics hardware *and* driver used
 * 32 or 64 bit
nvidia 64 bit  440
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
 ```

**Issue**
When dragging a file from one smb folder window to another smb share, it will think the file is a folder and say there was an error reading the folder ... not a directory

**Steps to reproduce**

**Expected behaviour**

**Other information**

**Configuration info, if applicable**
If this bug report is related to an Applet, Desklet or Extension, please paste (or use a pastebin service) the offending extension's settings, if it has any.  You can obtain this by opening its configuration, clicking the 'hamburger' button in the upper-right corner of the window, and selecting "Export to a file". **Please be sure to review the contents and remove any personal data it may contain.**

```

Please paste here

```

**Comment by claudiux** [comment]
I can't reproduce this issue on Cinnamon 4.4.8 (Mint 19.3).
