### ISSUE TITLE
Problem with Workspaces in Cinnamon (started with Mint 19.3)

### ISSUE THREAD

**Issue by hjanni** [linuxmint/cinnamon#9115]
```
 * Cinnamon version 4.4.8
   - daily builds PPA :no 
 * Distribution - Mint 19.3
 * Nvidia RTX 2070 super
 * 64 bit
```
Issue:
There is a problem where application closed in a workspace appears still active/open in other workspaces

Condition: Two monitors and "workspaces on primary monitor" enabled.
System Settings - Workspaces - Settings -> Only use workspaces on primary monitor (requires Cinnamon restart). 
I believe reason for error is the "workspaces on primary monitor" setting.
If I disable this then workspaces works correctly.

**Steps to reproduce**
1. Go to workspace 2 
2. Open Nemo or any application
3. Close the same
4. Go to workspace 1 and you will see application still appears active/open

**Comment by icarter09** [comment]
Cinnamon 4.4.8

I'm not able to reproduce this issue. I enabled the Workspace setting, restarted Cinnamon, performed the steps to reproduce, but the application was not active/open in Workspace 1. Tried this on several different applications.
