### ISSUE TITLE
Window preview still open after switching workspace

### ISSUE THREAD

**Issue by parnikkapore** [linuxmint/cinnamon#9116]
```
 * Cinnamon 4.4.8
 * Mint 19.3
 * Intel internal graphics
 * 64 bit
 * Classic-style window list applet
 ```

**Issue**
When the window preview is open, switching to another workspace with ctrl-alt-arrow will not close the preview, leaving a "ghost preview".

**Steps to reproduce**
1. Minimize all windows. *This glitch does not occur if any windows are visible.*
2. Hover over a window entry on the panel to make the window preview/tooltip appear.
3. Without moving the mouse, press `Ctrl`+`Alt`+`[Right arrow]` to switch to another workspace.

The window preview will stay visible until you nudge the mouse.

**Expected behaviour**
The window preview closes when navigating to a different workspace.

**Comment by NicoWeio** [comment]
Can't reproduce 🤔

**Comment by icarter09** [comment]
Cinnamon 4.4.8
Mint 19.3
64bit

I'm not able to reproduce this issue either
