### ISSUE TITLE
Maximized firefox is showing a black space

### ISSUE THREAD

**Issue by s1-ranjan** [linuxmint/cinnamon#9117]
I disabled the title-bar of the Firefox and tried to maximised it but it leaves behind a black area please have a look in the attached image.
![Screenshot from 2020-01-16 16-14-34](https://user-images.githubusercontent.com/20767253/72518968-78158d80-387c-11ea-82e1-db6f1d20d37a.png)

```
 * Cinnamon version (cinnamon --version)
   - Please specify if you are using the daily builds PPA
     (https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds).
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
 * Graphics hardware *and* driver used
 * 32 or 64 bit
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
 ```

**Issue**

**Steps to reproduce**

**Expected behaviour**

**Other information**

**Configuration info, if applicable**
If this bug report is related to an Applet, Desklet or Extension, please paste (or use a pastebin service) the offending extension's settings, if it has any.  You can obtain this by opening its configuration, clicking the 'hamburger' button in the upper-right corner of the window, and selecting "Export to a file". **Please be sure to review the contents and remove any personal data it may contain.**

```

Please paste here

```

**Comment by leigh123linux** [comment]
Closed cinnamon-spices-themes/issues/608
