### ISSUE TITLE
corrupted / distorted tooltips after latest update

### ISSUE THREAD

**Issue by tethragon** [linuxmint/cinnamon#9124]
```
* Host: george-Satellite-L655 Kernel: 5.3.0-26-generic x86_64 bits: 64 compiler: gcc 
           v: 7.4.0 Desktop: Cinnamon 4.4.8 wm: muffin dm: LightDM Distro: Linux Mint 19.3 Tricia 
           base: Ubuntu 18.04 bionic 
 * Device-1: AMD Madison [Mobility Radeon HD 5650/5750 / 6530M/6550M] 
           vendor: Toshiba America Info Systems driver: radeon v: kernel bus ID: 01:00.0 
           chip ID: 1002:68c1 
           Display: x11 server: X.Org 1.20.5 driver: ati,radeon unloaded: fbdev,modesetting,vesa 
           resolution: 1366x768~60Hz 
           OpenGL: renderer: AMD REDWOOD (DRM 2.50.0 / 5.3.0-26-generic LLVM 9.0.1) 
           v: 3.3 Mesa 20.0.0-devel (git-d8a3501 2020-01-18 bionic-oibaf-ppa) compat-v: 3.1 
           direct render: Yes 
 ```

**Issue**
Tooltips are corrupted

**Steps to reproduce**
Hover mouse over buttons and wait for tooltip appearence

**Expected behaviour**
Tooltips should not be corrupted

**Other information**

**Configuration info, if applicable**
FULL System info: https://termbin.com/tzn3

```

```

Screen casting of the problem: https://youtu.be/iutIwrM_Lz0

**Comment by smurphos** [comment]
You've got a non official mesa installed via PPA which is quite possibly part of the issue. I suggest you need to revert to stock and if you are still having an issue ask for help on the Mint forums.

There are other 19.3 users on the Mint forums with AMD graphics reporting this with the  HWE graphics stack and the solution that seems to work for them is downgrading to the LTS graphic stack via `apt install xserver-xorg xserver-xorg-video-all`. But I'm not sure if that will work whilst you got the PPA active.

**Comment by tethragon** [comment]
@smurphos 

Problem started after the system update while using **official** mesa
I have installed unofficial lastest MESA trying to solve the problem.
Trust me.

**Comment by tethragon** [comment]
I confirm problem solved after downgrading to the LTS graphic stack using:
`apt install xserver-xorg xserver-xorg-video-all`
I also posted in mesa bugs forum, so the issue could be fixed without reverting to LTS graphic stack

**Comment by claudiux** [comment]
@tethragon If your problem is solved, can you close this issue, please?
