### ISSUE TITLE
Graphics Drivers corrupted when update for 19.2 to 19.3

### ISSUE THREAD

**Issue by piFrog** [linuxmint/cinnamon#9125]
```
 * Cinnamon version (cinnamon --version)
   Host: Linux-Mint Kernel: 4.15.0-74-generic x86_64 bits: 64 compiler: gcc v: 7.4.0 
           Desktop: Cinnamon 4.2.4 wm: muffin dm: LightDM Distro: Linux Mint 19.2 Tina 
           base: Ubuntu 18.04 bionic 
 * Graphics:  Device-1: NVIDIA GF108 [GeForce GT 620] vendor: eVga.com. driver: nvidia v: 390.116 
           bus ID: 01:00.0 chip ID: 10de:0f01 
           Display: x11 server: X.Org 1.19.6 driver: nvidia 
           unloaded: fbdev,modesetting,nouveau,vesa resolution: 1920x1080~60Hz 
           OpenGL: renderer: GeForce GT 620/PCIe/SSE2 v: 4.6.0 NVIDIA 390.116 direct render: Yes 
 * 64 bit
 * Attached: System Report of 19.2 system before installing 19.3
19.3 INSTALL FUNCTIONED FINE UNTIL THE LATEST UPDATE (I INSTALLED THE UPDATE ON 01/18/2020) AFTER RE-BOOT GRAPHICS WAS IN SOME KIND OF DEFAULT - 
 ```
ALL I CAN PROVIDE IS THE SYSTEM REPORT OF THE 19.2 SYSTEM, SEE BELOW

SYSTEM_REPORT
System:    Host: Linux-Mint Kernel: 4.15.0-74-generic x86_64 bits: 64 compiler: gcc v: 7.4.0 
           Desktop: Cinnamon 4.2.4 wm: muffin dm: LightDM Distro: Linux Mint 19.2 Tina 
           base: Ubuntu 18.04 bionic 
Machine:   Type: Desktop Mobo: ASUSTeK model: M5A78L-M/USB3 v: Rev X.0x serial: <filter> 
           BIOS: American Megatrends v: 1801 date: 11/12/2013 
Battery:   Device-1: hidpp_battery_0 model: Logitech Marathon Mouse/Performance Plus M705 
           serial: <filter> charge: 55% status: Discharging 
CPU:       Topology: 6-Core model: AMD FX-6300 bits: 64 type: MCP arch: Bulldozer 
           L2 cache: 2048 KiB 
           flags: lm nx pae sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm bogomips: 42190 
           Speed: 3872 MHz min/max: 1400/3500 MHz Core speeds (MHz): 1: 3928 2: 3886 3: 4018 
           4: 3928 5: 1914 6: 1438 
Graphics:  Device-1: NVIDIA GF108 [GeForce GT 620] vendor: eVga.com. driver: nvidia v: 390.116 
           bus ID: 01:00.0 chip ID: 10de:0f01 
           Display: x11 server: X.Org 1.19.6 driver: nvidia 
           unloaded: fbdev,modesetting,nouveau,vesa resolution: 1920x1080~60Hz 
           OpenGL: renderer: GeForce GT 620/PCIe/SSE2 v: 4.6.0 NVIDIA 390.116 direct render: Yes 
Audio:     Device-1: AMD SBx00 Azalia vendor: ASUSTeK M4A785TD driver: snd_hda_intel v: kernel 
           bus ID: 00:14.2 chip ID: 1002:4383 
           Device-2: NVIDIA GF108 High Definition Audio vendor: eVga.com. driver: snd_hda_intel 
           v: kernel bus ID: 01:00.1 chip ID: 10de:0bea 
           Sound Server: ALSA v: k4.15.0-74-generic 
Network:   Device-1: Qualcomm Atheros AR9287 Wireless Network Adapter driver: ath9k v: kernel 
           port: dc00 bus ID: 02:00.0 chip ID: 168c:002e 
           IF: wlp2s0 state: down mac: <filter> 
           Device-2: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet 
           vendor: ASUSTeK P8P67 and other motherboards driver: r8169 v: 2.3LK-NAPI port: e800 
           bus ID: 04:00.0 chip ID: 10ec:8168 
           IF: enp4s0 state: down mac: <filter> 
           Device-3: Ralink RT5572 Wireless Adapter type: USB driver: rt2800usb bus ID: 1-2:2 
           chip ID: 148f:5572 
           IF: wlx9cefd5ffcae4 state: up mac: <filter> 
Drives:    Local Storage: total: 931.51 GiB used: 17.58 GiB (1.9%) 
           ID-1: /dev/sda vendor: Toshiba model: DT01ACA100 size: 931.51 GiB speed: 3.0 Gb/s 
           serial: <filter> 
Partition: ID-1: / size: 915.89 GiB used: 17.58 GiB (1.9%) fs: ext4 dev: /dev/sda1 
USB:       Hub: 1-0:1 info: Full speed (or root) Hub ports: 6 rev: 2.0 chip ID: 1d6b:0002 
           Device-1: 1-2:2 info: Ralink RT5572 Wireless Adapter type: Network driver: rt2800usb 
           rev: 2.0 chip ID: 148f:5572 
           Hub: 2-0:1 info: Full speed (or root) Hub ports: 6 rev: 2.0 chip ID: 1d6b:0002 
           Hub: 3-0:1 info: Full speed (or root) Hub ports: 3 rev: 1.1 chip ID: 1d6b:0001 
           Hub: 4-0:1 info: Full speed (or root) Hub ports: 3 rev: 1.1 chip ID: 1d6b:0001 
           Device-2: 4-2:2 info: Logitech Illuminated Keyboard type: Keyboard,Mouse 
           driver: hid-generic,usbhid rev: 2.0 chip ID: 046d:c318 
           Hub: 5-0:1 info: Full speed (or root) Hub ports: 3 rev: 1.1 chip ID: 1d6b:0001 
           Hub: 6-0:1 info: Full speed (or root) Hub ports: 3 rev: 1.1 chip ID: 1d6b:0001 
           Device-3: 6-3:2 info: Logitech Unifying Receiver type: Keyboard,Mouse,HID 
           driver: logitech-djreceiver,usbhid rev: 2.0 chip ID: 046d:c52b 
           Hub: 7-0:1 info: Full speed (or root) Hub ports: 2 rev: 1.1 chip ID: 1d6b:0001 
           Hub: 8-0:1 info: Full speed (or root) Hub ports: 2 rev: 2.0 chip ID: 1d6b:0002 
           Device-4: 8-1:2 info: MediaTek Samsung SE-208 Slim Portable DVD Writer 
           type: Mass Storage driver: usb-storage rev: 2.0 chip ID: 0e8d:1806 
           Hub: 9-0:1 info: Full speed (or root) Hub ports: 2 rev: 3.0 chip ID: 1d6b:0003 
Sensors:   System Temperatures: cpu: 38.0 C mobo: 25.0 C gpu: nvidia temp: 43 C 
           Fan Speeds (RPM): cpu: 1771 case-1: 1713 gpu: nvidia fan: 65% 
           Voltages: 12v: 12.11 5v: N/A 3.3v: 3.32 vbat: N/A 
Repos:     No active apt repos in: /etc/apt/sources.list 
           Active apt repos in: /etc/apt/sources.list.d/google-chrome.list 
           1: deb [arch=amd64] http: //dl.google.com/linux/chrome/deb/ stable main
           Active apt repos in: /etc/apt/sources.list.d/google-earth-pro.list 
           1: deb http: //dl.google.com/linux/earth/deb/ stable main
           Active apt repos in: /etc/apt/sources.list.d/official-package-repositories.list 
           1: deb http: //packages.linuxmint.com tina main upstream import backport #id:linuxmint_main
           2: deb http: //archive.ubuntu.com/ubuntu bionic main restricted universe multiverse
           3: deb http: //archive.ubuntu.com/ubuntu bionic-updates main restricted universe multiverse
           4: deb http: //archive.ubuntu.com/ubuntu bionic-backports main restricted universe multiverse
           5: deb http: //security.ubuntu.com/ubuntu/ bionic-security main restricted universe multiverse
           6: deb http: //archive.canonical.com/ubuntu/ bionic partner
Info:      Processes: 235 Uptime: 10m Memory: 11.71 GiB used: 1.78 GiB (15.2%) Init: systemd 
           v: 237 runlevel: 5 Compilers: gcc: 7.4.0 alt: 7 Client: Unknown python3.6 client 
           inxi: 3.0.32 

```

**Comment by leigh123linux** [comment]
The issue isn't within cinnamon, please refile it against https://github.com/linuxmint/linuxmint/issues
