### ISSUE TITLE
"File Selection" Dialog Window Won't Display Thumbnails

### ISSUE THREAD

**Issue by FDragoness** [linuxmint/cinnamon#9130]
SYSTEM:
Linux Mint 19.3 Cinnamon (64-bit)

PROBLEM DESCRIPTION:

When browsing normally via the Nemo file explorer window (i.e. by going to the taskbar at the bottom of the screen and opening a new file-browse window) I am able to switch between different file views, including "icon view". (Note: "Icon view" displays thumbnails.)

However, when a file-selection dialog window is open it *only* displays files in "list view". There is no option to change the file view to "icon view" in file-selection dialog windows.  Using the Ctrl + 1 keyboard shortcut (to show "icon view", i.e thumbnails) that works in Nemo does not have any effect in a file-selection dialog window.  This is problematic when trying to visually find and select a particular picture in a folder with many pictures.

Image of Nemo File Explorer Window: https://i.postimg.cc/Xq8462cP/Explorer-Window.png (Can view files as thumbnails.)
**VS**
Image of File-Selection Dialog Window: https://i.postimg.cc/tghccszS/File-sele ... Window.png (Cannot view files thumbnails.)

**Comment by JosephMcc** [comment]
The file chooser dialog is provided by the toolkit that the application uses. It's not under our control.

**Comment by FDragoness** [comment]
> The file chooser dialog is provided by the toolkit that the application uses. It's not under our control.

Who should I contact then?

I understand that Linux Mint relies on and brings together components from other parts of the Linux community but that not important.  I know enough to know that an OS is built on layers and surely something can be programmed that would ensure basic functionality (such as the ability to switch to thumbnail view) regardless of what program is calling the file-selection dialog.  If programs want to individualize the selection dialog, then they should be allowed to do that--but without interfering/compromising basic functionality that should always be present.  

I don't know much about programming but that's my feedback for what it's worth.  If the Mint development team is interested in improving the GUI, I'd work on fixing this.  If this forum isn't the appropriate place for this issue, then maybe you could forward the bug/problem to the appropriate group?  

I'm just an end-user.  I don't really know where to post bugs/problems or make suggestions.  This place was the most appropriate from what I could find.   

Kind regards and thanks.

**Comment by ManIVIctorious** [comment]
Well, the toolkit providing this functionality is GTK3, developed by the GNOME project. In this particular case there is nothing the Mint developers can do to fix this for you. You will have to file a bug report to them (though their user experience decitions are somewhat special...)
