### ISSUE TITLE
Non-system hard drives not displaying inside file-selection or directory-selection windows.

### ISSUE THREAD

**Issue by FDragoness** [linuxmint/cinnamon#9131]
SYSTEM:
Linux Mint 19.3 Cinnamon (64-bit)

PROBLEM DESCRIPTION:

When inside a program (e.g. Thunderbird, Virtual Box, etc.) and trying to select a file or to indicate a particular directory for a program, a select-file or select-directory dialog window appears. On the left-hand-side of that window, I can see my UserName home directory as well as an my "Computer". If I click on "Computer", it navigates me to the system root directory. 

The problem is that my other internal hard drives are not displaying in the selection window.  The selection window also does not display "recent places".   This makes navigating to the desired file or folder on the non-system drive extremely cumbersome.  

There are currently only two ways that I know of to navigate to a non-system drive from inside a file/folder-selection dialog window--and both ways are very cumbersome:
Method #1: Select  "Computer" (i.e. Root) > media > MyUsername > DesiredHardDrive  .
Method #2: Locate the file or directory in a regular Nemo window, select the path using Ctrl+L and copy it.  Switch to the file/directory selection window, press Ctrl+L, paste the path into the box that appears, press enter to jump to the desired directory.  (Alternatively, paste the path into the "File name" box and pressing enter also jumps you to the desired directory).

**See image of problem:** https://i.postimg.cc/43FR1hNr/edit.jpg

The image shows the Nemo Explorer window open (which shows all the drives connected to the computer in its left pane) and an instance of VirtualBox open from which I've opened a file-selection dialog window.  As you can see, except for "Computer" (which brings me to root) and Home directories, the other drives are not listed in the left-pane of the dialog window.  The only way to navigate to a non-system drive is to use Method #2 (see above).

**Comment by JosephMcc** [comment]
Again see: https://github.com/linuxmint/cinnamon/issues/9130

Also please use the provided issue template when opening issues.
