### ISSUE TITLE
Suspend does Restart instead

### ISSUE THREAD

**Issue by easyt50** [linuxmint/cinnamon#9139]
```Mint 19.3 64 bit

Mint 19.3 64 bit
    Kernel 5.0.0-37
When I request the system to suspend, it performs a restart instead.

 * Cinnamon version (cinnamon --version)
   - Please specify if you are using the daily builds PPA
     (https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds).
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
 * Graphics hardware *and* driver used
 * 32 or 64 bit
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
 ```

**Issue**

**Steps to reproduce**

**Expected behaviour**

**Other information**

**Configuration info, if applicable**
If this bug report is related to an Applet, Desklet or Extension, please paste (or use a pastebin service) the offending extension's settings, if it has any.  You can obtain this by opening its configuration, clicking the 'hamburger' button in the upper-right corner of the window, and selecting "Export to a file". **Please be sure to review the contents and remove any personal data it may contain.**

```

Please paste here

```

**Comment by icarter09** [comment]
Cinnamon 4.4.8
Kernel 5.3.0-28

I'm not able to reproduce this issue. Suspend performs as expected and does not Restart the computer.
