### ISSUE TITLE
Native Linux games don't launch (19.3 Cinammon)

### ISSUE THREAD

**Issue by xTrEIX** [linuxmint/cinnamon#9143]
Hello, I'm new on Github, so I don't know if I'm in the right section.

I can't to run natives Linux games, while I have no problems using Steam Play with Proton, but as soon as I try to launch a native Linux game bought on Steam or GOG, nothing happens, if I open the .sh file via the terminal, exemple, Blade Runner, here's what I got :

```
alex@alex-AB350-Gaming-3:~$ '/media/alex/SSHD Seagate/GOG/Blade Runner French/start.sh'

Running Blade Runner (French)

Starting ScummVM

/media/alex/SSHD Seagate/GOG/Blade Runner French/game/scummvm/scummvm_x86_64: error while loading shared libraries: libSDL2_net-2.0.so.0: cannot open shared object file: No such file or directory

Done.
```

I went through the forums and helpers to try to fix this problem with "libSDL2_net-2.0.so.0", I found some solutions but when I install the packages, but apparently I already have everything to install and the latest packages

```
alex@alex-AB350-Gaming-3:~$ sudo apt install libsdl2-2.0-0:i386

[sudo] alex's password:

Reading package lists... Done

Construction of the dependency tree

Reading status information... Done

libsdl2-2.0-0:i386 is already the most recent version (2.0.8+dfsg1-1ubuntu1.18.04.4).

0 updated, 0 newly installed, 0 to remove and 0 not updated.
```

Unless you need another package to install, well, I don't know how to do it, I could use some help, thanks.

I use AMDGPU 64 bits, last Mesa version, Kernel 5.3.0

My complete system info :

https://termbin.com/ra22

**Comment by leigh123linux** [comment]
This isn't related to cinnamon.
Try install the missing dep, you need to install libsdl2-net-2.0-0

https://packages.ubuntu.com/disco/libsdl2-net-2.0-0
