### ISSUE TITLE
Window preview stucked after forcibly closed app

### ISSUE THREAD

**Issue by dron23** [linuxmint/cinnamon#9144]
```
 * Cinnamon version: 4.4.6 (not using PPA)
 * Distribution: Fedora release 31
 * Graphics hardware:
    * Intel Corporation Xeon E3-1200 v3/4th Gen Core Processor Integrated Graphics Controller (rev 06)
    * xorg-x11-drv-intel-2.99.917-43.20180618.fc31.x86_64
 * 64 bit
 ```

**Issue**
Window preview is stucked after application is forcibly closed.

**Steps to reproduce**
 * open terminal app, make its window active
 * move cursor to its toolbar icon to display window preview
 * press Ctrl+d to close terminal app
 * preview is collapsed to its title but still visible (and hides windows under it, see screenshot)

![stucked_preview](https://user-images.githubusercontent.com/7817118/73259909-1254ca00-41c9-11ea-8341-f882e60da2c9.png)

**Expected behaviour**
Window preview should disappear in this case.

**Comment by icarter09** [comment]
Cinnamon 4.4.8

I'm not able to reproduce this issue. When I pressed `Ctrl+d`, the window preview disappeared as expected.

**Comment by dron23** [comment]
Interesting. I Will try to upgrade to 4.4.8 and let you know.

**Comment by dron23** [comment]
Yep, Cinnamon 4.4.8 is not affected by this issue. Thanks!
