### ISSUE TITLE
Tiling and resizing windows

### ISSUE THREAD

**Issue by FatBirdie** [linuxmint/cinnamon#9155]
```
 * Cinnamon version 4.4.8
 * Distribution - Mint 19.3
 ```

Tiling windows with keyboard shortcuts are absolutely lovely on Cinnamon, specially on a 21:9 monitor as it pretty much eliminates the need for a secondary monitor but I would like to see some an improvement when resizing tiled windows. Although there is snapping going on when window borders are pulled together (which in it self is very nice for resizing), it would be nice to see a feature that allows for automatically resizing with one pull of the mouse cursor. If for example one window is tiled to the left and one to the right of the screen, perhaps holding down alt/ctrl/super key while resizing could allow for the two window borders to both follow the resize at the same time.
I hope I'm making any sense. If not, I'll be happy to clarify further.

**Comment by claudiux** [comment]
@FatBirdie Try this tip:
Open two windows. Drag one of them, pressing Ctrl, to the left side of your screen. Maximize the other window. The two become joined. Move using mouse the right border of the first window, then release the mouse button. Both are resized.

**Comment by FatBirdie** [comment]
Hm, tiling a window to left as you say and pressing maximize for another does not join them for me. Maximizing a window after another has been tiled to left just maximizes it over the whole screen.
If I tile a window to the left and another to the right, both seem to be maximized within their tile, but if I go for any of the borders at the center of the screen I can only grab one of the windows at a time.

**Comment by claudiux** [comment]
Please take a look at https://github.com/linuxmint/cinnamon/issues/8394.

**Comment by FatBirdie** [comment]
Yeah, that worked but it doesn't work when tiling to corners.
Tiling in Cinnamon is easy with just super+right/left/left+up/right+down etc and appreciated, but this seems like its made with only mouse in mind... Thanks for your input although the functionality wasn't very satisfactory. To limited and to cumbersome. I hope there will be improvements.

Cheers!

**Comment by claudiux** [comment]
**ctrl**+super+right/left/left+up/right+down does the job for me.

**Comment by FatBirdie** [comment]
That does work, but the second window still has to be maximized and it would be much nicer if all could be done with the keyboard like if it was possible to do ctrl+super+left and ctrl+super+right and from with that, snapping the windows.

As well, it only seems possible to snap while tiling two horizontal or two vertical windows, not if for example one window is put to the left, another to upper right and a third to lower right.

**Comment by claudiux** [comment]
You're right. This is a feature request.

@icarter09 What do you think about this?

**Comment by FatBirdie** [comment]
@claudiux excellent! :)

**Comment by astier** [comment]
The only important missing feature for me which would be really helpful. Even windows 10 can do that.

**Comment by mtwebster** [comment]
This shouldn't be an issue anymore as of Cinnamon 5.4
