### ISSUE TITLE
[Xlets settings system][TreeListWidgets.py] Misbehavior of list widget

### ISSUE THREAD

**Issue by Odyseus** [linuxmint/cinnamon#9157]
> Cinnamon version: 4.4.8
> Distribution: Linux Mint 19.3

Every change made to the list widget (toggling a boolean, moving an item, etc.) clears the list model and destroys and recreates the tree.

A faster way to see the issue is by experiencing it. [Here](https://github.com/linuxmint/cinnamon/files/4173100/settings-example%40cinnamon.org.txt) is a settings file for the `settings-example@cinnamon.org` applet with about 60 items added to the list widget. Upon importing it, trying to move the last item on the list more than once is practically impossible.

I tracked the problem to the [`list_changed`](https://github.com/linuxmint/cinnamon/blob/master/files/usr/share/cinnamon/cinnamon-settings/bin/TreeListWidgets.py#L320) method. When the changes in the list are [saved to the applet settings file](https://github.com/linuxmint/cinnamon/blob/master/files/usr/share/cinnamon/cinnamon-settings/bin/TreeListWidgets.py#L330), the [`on_setting_changed`](https://github.com/linuxmint/cinnamon/blob/master/files/usr/share/cinnamon/cinnamon-settings/bin/TreeListWidgets.py#L333) method is executed. And there is where the tree is recreated from scratch.

I managed to work around this issue by simply preventing the reconstruction of the tree when `list_changed` is called, but I prefer that the experts decide how to fix it.

```patch
--- a/files/usr/share/cinnamon/cinnamon-settings/bin/TreeListWidgets.py
+++ b/files/usr/share/cinnamon/cinnamon-settings/bin/TreeListWidgets.py
@@ -103,6 +104,7 @@ class List(SettingsWidget):
     def __init__(self, label=None, columns=None, height=200, size_group=None, dep_key=None, tooltip=""):
         super(List, self).__init__(dep_key=dep_key)
         self.columns = columns
+        self.saving_changes = False
 
         self.set_orientation(Gtk.Orientation.VERTICAL)
         self.set_spacing(0)
@@ -318,6 +320,7 @@ class List(SettingsWidget):
         return None
 
     def list_changed(self, *args):
+        self.saving_changes = True
         data = []
         for row in self.model:
             i = 0
@@ -329,8 +332,12 @@ class List(SettingsWidget):
 
         self.set_value(data)
         self.update_button_sensitivity()
+        self.saving_changes = False
 
     def on_setting_changed(self, *args):
+        if self.saving_changes:
+            return
+
         self.model.clear()
         rows = self.get_value()
         for row in rows:

```
[TreeListWidgets.py.patch.zip](https://github.com/linuxmint/cinnamon/files/4173132/TreeListWidgets.py.patch.zip)

Pinging @collinss.

**Comment by claudiux** [comment]
Thank you @Odyseus ! The use of lists becomes much easier with these changes.

**Comment by collinss** [comment]
@Odyseus https://github.com/linuxmint/cinnamon/pull/9158

Similar to yours but it works for all unbound settings types (just in case).

**Comment by Odyseus** [comment]
> ...but I prefer that the experts decide how to fix it.

That statement always proves me right. The experts always have a more elegant way of doing things.

Thank you very much, @collinss. :+1:
