### ISSUE TITLE
Indicators same as in Windows and Manjaro

### ISSUE THREAD

**Issue by hxyb63b3** [linuxmint/cinnamon#9166]
```
 * Cinnamon v4.4.8
 * Linux Mint 19.3
 * Nvidia driver 435.21
 * 64 bit
 ```
Greetings! I recently tried Manjaro with cinnamon and I noticed that the indicators work like in Windows, contrary to Mint.
Without activating the indicator support, in Mint the left and right click do the same, open the menu. In Manjaro, as in Windows, the right click opens the menu and the left click directly maximizes the application. 
Is there a way to do this in Mint? Thanks.

**Comment by Iglu47** [comment]
Menu **->** (category) Preference **->** System Settings _(Control Center)_ (also it usually in favorite by default) **->** (category Preferences) Windows **->** first tab "Titlebar" (custom it how you _wish_)
