### ISSUE TITLE
Numbers are unreadable

### ISSUE THREAD

**Issue by awnumar** [linuxmint/cinnamon#9167]
```
 * Cinnamon version: Cinnamon 4.4.8
 * Distribution - Manjaro 18.1.5
 * Graphics: Intel Iris Plus 640 with i915 driver
 * 64 bit
 ```

**Issue**

The numbers are almost unreadable in the taskbar, especially on the time and date display and calendar. I have attached images.

The font was replaced with a weird black gradient thing.

![IMG_20200216_154441](https://user-images.githubusercontent.com/8942495/74607957-19d70700-50d5-11ea-9534-b1e7e93e1fb8.jpg)
![IMG_20200216_154450](https://user-images.githubusercontent.com/8942495/74607959-1c396100-50d5-11ea-8fef-267e2ab38a1a.jpg)

**Comment by JosephMcc** [comment]
Have you tried using a different theme? I've never seen anything like this and I'm wondering if this is an issue with the theme used in Manjaro. Try switching to the default cinnamon theme and see if the issue still exists.

**Comment by awnumar** [comment]
Changing the theme fixed the issue, thanks. Not sure why a static theme suddenly broke though (numix).
