### ISSUE TITLE
Alt-tab, coverflow 3d: system hangs

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/cinnamon#9172]
```
 * Cinnamon version (cinnamon --version) 4.4.8
   - Please specify if you are using the daily builds PPA: no
     (https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds).
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 19.3
 * Graphics hardware *and* driver used: Intel 3rd Gen Core processor Graphics Controller; 3.0 Mesa 19.2.8
 * 32 or 64 bit: 64
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
[xsession-errors.txt](https://github.com/linuxmint/cinnamon/files/4215077/xsession-errors.txt)

 ```

**Issue**

Occasionally alt-tab hangs the whole system, such that only the pointer can move; it is possible to open tty but not to do anything else. (Possibly Cinnamon would restart, had I bound that to a hotkey, which I have not). The problem occurs only when using coverflow3D - which is the alt-tab mode that I find most useful. Also, it happens on this computer (a ThinkPad X230) and not my other Mint computer (a ThinkPad X1 Carbon Sixth Generation).

**Steps to reproduce**

Alt-Tab, rapidly and repeatedly. You may need a graphics setup similar to mine.

**Expected behaviour**

No hang.

**Other information**

I had thought I had reported this problem before but I cannot find an existing report. I did find some similar reports: 316; 3275; 4388.

The problem has existed for approximate one year, and on different Linux kernels.

The afffected system:

Lenovo ThinkPad X230
OS: Linux Mint 19.3 Tricia x86_64 
Host: 2325L19 ThinkPad X230 
Kernel: 5.3.0-28-generic 
Uptime: 8 mins 
Packages: 3396 (dpkg), 4 (flatpak), 7 (snap) 
Shell: bash 4.4.20 
Resolution: 1366x768 @ 60.02Hz 
DE: Cinnamon 4.4.8 
WM: Mutter (Muffin) 
WM Theme: Mint-Y-Dark (N_cinn) 
Theme: Mint-Y-Dark [GTK2/3] 
Icons: Paper [GTK2/3] 
Terminal: gnome-terminal 
CPU: Intel i5-3320M (4) @ 3.300GHz 
GPU: Intel 3rd Gen Core processor Graphics Controller 
Memory: 1752MiB / 7779MiB 
Disk (/dev/sda2): 18G / 52G (37%)

**Comment by LinuxOnTheDesktop** [comment]
I just had this again. I was watching a video in Chrome. The video continued to play, but in alt-tab mode, and I could not leave that mode. I took a screenshot but I could not save the screenshot anywhere. I used a tty to kill Chrome but I remained stuck in alt-tab mode. I had to reboot.

Could we have the 'bug' label on this, please? It is a pretty gross bug and anyone who has it on their system is going to find it pretty depressing.

**Comment by LinuxOnTheDesktop** [comment]
This just happened again, on Mint 20. It occured when I alt-tabbed when uninstalling a program via MintMenu.

**Comment by LinuxOnTheDesktop** [comment]
It happened again. I had to reboot. I have found [a thread on the forum](https://forums.linuxmint.com/viewtopic.php?t=86925) that includes the following descriptions of the problem (or of its impact). Each it from a different poster.

- 'utterly irritating and sending my workflow down the drain. After years, ALT+TAB is a twitch reaction. It's impossible not to do it.'
- ' a huge annoyance'
- 'very annoying'
- 'HIGHLY annoying' (_sic_)
- 'ridiculous' (spelling corrected)
- 'absolutely terrible'

The thread dates from _2011_.

**Comment by mtwebster** [comment]
When this happens, does .xsession-errors show anything at all? You can check .xsession-errors.old to see the previous session's log (since you have to log out/in to escape the freeze).

I have a few ideas on this but there's not enough data to act on right now.

**Comment by LinuxOnTheDesktop** [comment]
Thank you.  I have enabled cover-flow-3d on my laptops and I am trying to reproduce the problem. If I manage to do that, I will post xsession-errors.old. If, after a week, I do not manage to reproduce it - for something that changed in the meantime might have fixed the problem - then I will (happily!) close this issue.

**Comment by LinuxOnTheDesktop** [comment]
I reproduced the problem and restarted via tty. I attach a photograph of the frozen desktop and also `.xsession-errors.old`.

![IMG_20210219_150757](https://user-images.githubusercontent.com/47056543/108522685-03095880-72c5-11eb-881a-5b63ee63b53f.jpg)
[xsession-errors.txt](https://github.com/linuxmint/cinnamon/files/6010921/xsession-errors.txt)

**Comment by mtwebster** [comment]
Does this seem to happen around when a window may be closing or a new one opening? Or can you simply, at any idle moment, alt-tab and have this occur?

**Comment by mtwebster** [comment]
Can you try this?

[appSwitcher3D.zip](https://github.com/linuxmint/cinnamon/files/6011624/appSwitcher3D.zip)

Unzip the file then:
```
# back the original up
sudo cp /usr/share/cinnamon/js/ui/appSwitcher/appSwitcher3D.js /usr/share/cinnamon/js/ui/appSwitcher/appSwitcher3D.js.bak
# copy the new one into the system folder
cp appSwitcher3D.js /usr/share/cinnamon/js/ui/appSwitcher
```
and restart cinnamon.

I can only theorize *why* it's occurring, but the fix is simple enough.

Thanks

**Comment by LinuxOnTheDesktop** [comment]
I have tested this a few times on one computer and there was no hang. I will test it later today on another computer. It is looking as though you did a good job (but I will report back about the other computer).

**Comment by LinuxOnTheDesktop** [comment]
To quote myself:

> I will test it later today on another computer.

It works on the other computer. This bug seems fixed.

**Comment by lucianojulio2** [comment]
Este bug continua no Mint 22.3 utilizando o Coverflow 3D.

Configurações do System:
  Kernel: 6.17.0-35-generic arch: x86_64 bits: 64 compiler: gcc v: 13.3.0 clocksource: tsc
  Desktop: Cinnamon v: 6.6.7 tk: GTK v: 3.24.41 wm: Muffin v: 6.6.3 vt: 7 dm: LightDM v: 1.30.0
  Distro: Linux Mint 22.3 Zena base: Ubuntu 24.04 noble
  Machine:
  Type: Desktop Mobo: ASUSTeK model: Rampage III GENE 
  CPU: Info: quad core model: Intel Core i7 975 bits: 64 
  Speed (MHz): avg: 3237 high: 3471 min/max: 1600/3334 boost: 
  Graphics:  Device-1: NVIDIA TU106 [GeForce RTX 2060 Rev. A] driver: nvidia v: 595.71.05 arch: 
  Display: x11 server: X.Org v: 21.1.11 with: Xwayland v: 23.2.6 driver: X: loaded: nvidia
  Monitor-1: DP-1 mapped: DP-0 note: disabled pos: primary,bottom-l
    model: LG (GoldStar) ULTRAWIDE serial: <filter> res: 3440x1440 hz: 160 dpi: 109
    size: 800x330mm (31.5x12.99") diag: 867mm (34.1") modes: max: 3440x1440 min: 640x480
  Monitor-2: HDMI-A-1 mapped: HDMI-0 note: disabled pos: top-right model: Samsung LF24T35
    serial: <filter> res: 1080x1920 hz: 60 dpi: 92 size: 297x528mm (11.69x20.79") diag: 606mm (23.9")
    modes: max: 1920x1080 min: 640x480
  API: EGL v: 1.5 hw: drv: nvidia platforms: device: 0 drv: nvidia device: 2 drv: swrast gbm:
    drv: nvidia surfaceless: drv: nvidia x11: drv: nvidia inactive: wayland,device-1
  API: OpenGL v: 4.6.0 compat-v: 4.5 vendor: nvidia mesa v: 595.71.05 glx-v: 1.4
    direct-render: yes renderer: NVIDIA GeForce RTX 2060/PCIe/SSE2
  API: Vulkan v: 1.3.275 layers: 9 surfaces: xcb,xlib device: 0 type: discrete-gpu driver: N/A
    device-ID: 10de:1f08 device: 1 type: cpu driver: N/A device-ID: 10005:0000
Audio:
  Device-1: Intel 82801JI HD Audio vendor: ASUSTeK driver: snd_hda_intel v: kernel
