### ISSUE TITLE
How to define custom Desktop theme?

### ISSUE THREAD

**Issue by m-kru** [linuxmint/cinnamon#9177]
Is there any tutorial on how to define custom Desktop theme for Cinnamon?
![cinnamon_nordic](https://user-images.githubusercontent.com/26227737/74848184-bbf62980-5337-11ea-93a5-cb4fbabc4969.png)

**Comment by JosephMcc** [comment]
Not really that I know of. The best thing to do is pick a theme that is similar to what you want and just experiment with it. Make changes and see what it does.
