### ISSUE TITLE
looking for Cinnamon .deb for Ubuntu 19.10

### ISSUE THREAD

**Issue by aplatypus** [linuxmint/cinnamon#9179]
Hi -- I want to find a source for a DEB (or PPA) to install Cinnamon v4.4 on Ubuntu 19.10.

I am getting pretty regular freeze and cinnamon restarts on Ubunto 19.10 Eoan from Cinnamon v4.0, which is the version in the Ubuntu Universe.  This is happening too frequently for me to let it go now.

```
 * Cinnamon version (cinnamon --version)
   - Cinnamon 4.0.10  (Ubuntu universe)
 * Ubuntu 19.10
 * Nvidia with latest supported Nvidia driver from Ubuntu
 ```

**Issue**

- Cannot find repository for Eoan
- Latest release in the   `ppa:embrosyn/cinnamon`  repository
  - is for: Ubuntu 19.04 Disco
  - https://launchpad.net/~embrosyn/+archive/ubuntu/cinnamon

**Steps to reproduce**

Added the embrosyn repo.  

 - Is there a different PPA for Ubuntu 10.10?

```
sudo add-apt-repository ppa:embrosyn/cinnamon
sudo apt-get update
```
- Reports that nothing is configured for Eoan ...
- Also the latest Cinnamon release there is 4.2

```
Ign:7 http://ppa.launchpad.net/embrosyn/cinnamon/ubuntu eoan InRelease
Err:8 http://ppa.launchpad.net/embrosyn/cinnamon/ubuntu eoan Release                 
  404  Not Found [IP: 91.189.95.83 80]
Get:10 http://security.ubuntu.com/ubuntu eoan-security/main amd64 DEP-11 Metadata [204 B]
Get:11 http://security.ubuntu.com/ubuntu eoan-security/universe amd64 DEP-11 Metadata [1,664 B]
Get:12 http://security.ubuntu.com/ubuntu eoan-security/universe DEP-11 48x48 Icons [7,098 B]
Get:13 http://security.ubuntu.com/ubuntu eoan-security/universe DEP-11 64x64 Icons [6,242 B]
Reading package lists... Done                                             
E: The repository 'http://ppa.launchpad.net/embrosyn/cinnamon/ubuntu eoan Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```
-  Is there a solution?
-  Is there a way I can install Cinnamon 4.4 so that I can testt the current version on this Laptop?Ign:7 http://ppa.launchpad.net/embrosyn/cinnamon/ubuntu eoan InRelease
Err:8 http://ppa.launchpad.net/embrosyn/cinnamon/ubuntu eoan Release                 
  404  Not Found [IP: 91.189.95.83 80]
Get:10 http://security.ubuntu.com/ubuntu eoan-security/main amd64 DEP-11 Metadata [204 B]
Get:11 http://security.ubuntu.com/ubuntu eoan-security/universe amd64 DEP-11 Metadata [1,664 B]
Get:12 http://security.ubuntu.com/ubuntu eoan-security/universe DEP-11 48x48 Icons [7,098 B]
Get:13 http://security.ubuntu.com/ubuntu eoan-security/universe DEP-11 64x64 Icons [6,242 B]
Reading package lists... Done                                             
E: The repository 'http://ppa.launchpad.net/embrosyn/cinnamon/ubuntu eoan Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

Hope there's way forward.  Many thanks, aplatypus

**Comment by JosephMcc** [comment]
Sorry but we don't support any ppa's for those Ubuntu releases and I don't happen to know of any.
