### ISSUE TITLE
Failed to execute child process “xdg-open” | Fresh Arch/Cinnamon install.

### ISSUE THREAD

**Issue by Chudz** [linuxmint/cinnamon#9180]
Cinnamon 4.4.8 (Not using PPA)
Arch
Nvidia
64 bit

home/<username>/.xsession-errors
`Internal error:   Could not resolve keysym XF86FullScreen
[cinnamon-settings-daemon-smartcard] Failed to start: no suitable smartcard driver could be found
[cinnamon-settings-daemon-smartcard] Failed to start: no suitable smartcard driver could be found
Clutter-Message: 21:52:04.888: Sync method: PRESENTATION TIME

** (nemo-desktop:815): WARNING **: 21:52:04.942: Current gtk theme is not known to have nemo support (CBlack) - checking...
Cjs-Message: 21:52:05.008: JS LOG: About to start Cinnamon
Cjs-Message: 21:52:05.033: JS LOG: [LookingGlass/info] Cinnamon.AppSystem.get_default() started in 24 ms
** Message: 21:52:05.035: nemo-desktop: session is cinnamon, establishing proxy
Cjs-Message: 21:52:05.036: JS LOG: [LookingGlass/info] loading user theme: /home/chudz/.themes/CBlack/cinnamon/cinnamon.css
Cjs-Message: 21:52:05.044: JS LOG: [LookingGlass/info] added icon directory: /home/chudz/.themes/CBlack/cinnamon
Cinnamon warning: Log level 128: posix_spawn avoided (fd close requested) 
Cjs-Message: 21:52:05.099: JS LOG: [LookingGlass/info] PlacesManager: Updating devices
Cjs-Message: 21:52:05.103: JS LOG: [LookingGlass/info] loaded at Sat Feb 22 2020 21:52:05 GMT+0000 (GMT)
Cjs-Message: 21:52:05.103: JS LOG: Cinnamon started at Sat Feb 22 2020 21:52:05 GMT+0000 (GMT)
Cjs-Message: 21:52:05.113: JS LOG: [LookingGlass/info] ExtensionSystem started in 0 ms
Cjs-Message: 21:52:05.113: JS LOG: [LookingGlass/info] DeskletManager started in 0 ms
Cjs-Message: 21:52:05.113: JS LOG: [LookingGlass/info] SearchProviderManager started in 0 ms
openGL version 3.1 detected (GL3 Cogl Driver)
Cjs-Message: 21:52:05.148: JS LOG: [LookingGlass/info] Loaded applet show-desktop@cinnamon.org in 18 ms
Cjs-Message: 21:52:05.170: JS LOG: [LookingGlass/info] Loaded applet calendar@cinnamon.org in 22 ms
Cjs-Message: 21:52:05.178: JS LOG: [LookingGlass/info] Loaded applet removable-drives@cinnamon.org in 8 ms
St-Message: 21:52:05.182: cogl npot texture sizes SUPPORTED
Cjs-Message: 21:52:05.194: JS LOG: [LookingGlass/info] Loaded applet keyboard@cinnamon.org in 16 ms
Cjs-Message: 21:52:05.201: JS LOG: [LookingGlass/info] Loaded applet xapp-status@cinnamon.org in 6 ms
Cjs-Message: 21:52:05.204: JS LOG: [LookingGlass/info] Role locked: tray
Cjs-Message: 21:52:05.205: JS LOG: [LookingGlass/info] Loaded applet systray@cinnamon.org in 4 ms
Cinnamon warning: Log level 128: posix_spawn avoided (automatic reaping requested) (fd close requested) 
Cjs-Message: 21:52:05.216: JS LOG: [LookingGlass/info] Loaded applet printers@cinnamon.org in 12 ms
Cjs-Message: 21:52:05.221: JS LOG: [LookingGlass/info] Role locked: notifications
Cjs-Message: 21:52:05.225: JS LOG: [LookingGlass/info] Loaded applet notifications@cinnamon.org in 8 ms
Cjs-Message: 21:52:05.246: JS LOG: [LookingGlass/info] Loaded applet power@cinnamon.org in 22 ms
Cjs-Message: 21:52:05.253: JS LOG: [LookingGlass/info] Role locked: panellauncher
Cjs-Message: 21:52:05.254: JS LOG: [LookingGlass/info] Loaded applet grouped-window-list@cinnamon.org in 8 ms

(csd-power:645): power-plugin-CRITICAL **: 21:52:05.274: abs_to_percentage: assertion 'max > min' failed
Cjs-Message: 21:52:05.295: JS LOG: [LookingGlass/info] Loaded applet sound@cinnamon.org in 40 ms
Cjs-Message: 21:52:05.308: JS LOG: [LookingGlass/info] Loaded applet network@cinnamon.org in 14 ms
Cjs-Message: 21:52:05.374: JS LOG: [LookingGlass/info] Loaded applet menu@cinnamon.org in 66 ms
Cjs-Message: 21:52:05.374: JS LOG: [LookingGlass/info] AppletManager started in 272 ms
Cjs-Message: 21:52:05.376: JS LOG: [LookingGlass/info] Cinnamon took 368 ms to start
Cjs-Message: 21:52:05.387: JS LOG: Unknown network device type, is 14
Cjs-Message: 21:52:05.660: JS LOG: [LookingGlass/info] Hiding systray: network
cinnamon-session[573]: WARNING: t+8.16983s: Detected that screensaver has appeared on the bus
Cinnamon warning: Log level 128: posix_spawn avoided (automatic reaping requested) (fd close requested) 
Cinnamon warning: Log level 128: posix_spawn avoided (automatic reaping requested) (fd close requested) 
Cjs-Message: 21:52:19.502: JS LOG: error: Execution of 'xdg-open http://www.foragoodstrftime.com/' failed:: Failed to execute child process “xdg-open” (No such file or directory)
Cinnamon warning: Log level 128: posix_spawn avoided (fd close requested) 
Cinnamon warning: Log level 128: posix_spawn avoided (fd close requested) 
Cinnamon warning: Log level 128: posix_spawn avoided (fd close requested) 
Cinnamon warning: Log level 128: posix_spawn avoided (fd close requested) `

**Issue**
Unable to load links to default browser

**Steps to reproduce**
Go to customizing the date/time in the bottom panel and then click the button "show Information on date format syntax" or clicking url links in Discord or other apps just does nothing.

**Expected behaviour**
Load up the clicked link or button in web browser.

**Other information**
Using Firefox it is currently set as the default program for Web.

**Comment by leigh123linux** [comment]
This is a Arch packaging issue so report it to them instead.

```
Failed to execute child process “xdg-open” (No such file or directory)
```

**Comment by leigh123linux** [comment]
@eli-schwartz  ^^

**Comment by eli-schwartz** [comment]
Duplicate of https://bbs.archlinux.org/viewtopic.php?id=253110

The OP fixed their problem by *reinstalling* xdg-utils, which was installed but presumably was broken somehow.
