### ISSUE TITLE
Wifi Panel Displays "More" after clicking More dropdown

### ISSUE THREAD

**Issue by mjeriefr** [linuxmint/cinnamon#9187]
Opening the wifi panel shows the closest ~6 wifi networks, as well as a "More" button. Upon clicking the More button, it displays all visible wifi networks, and partway down the list it still displays the More button inside of the list. 

Screenshot:
![image](https://user-images.githubusercontent.com/6463169/75612298-66601080-5adf-11ea-859f-e1faf060763f.png)

Cinnamon version 4.4.8 on Mint 19.3

Related to #5064, but not the same.

**Comment by JosephMcc** [comment]
I want to make sure I understand. The "More" is an expandable menu item that can be closed. It shouldn't hide when you open it. That would make you unable to close it again unless I'm missing something.

**Comment by mjeriefr** [comment]
Hmm, I see what you mean about needing to close the menu item. Perhaps the close/collapse/hide button should go below the complete list of wifi networks in a slightly different font, or indented. As it is now, it looks like there is a wifi network with the name of "More" that you could try to connect to. Here is a better screenshot. 

![more](https://user-images.githubusercontent.com/6463169/75613049-a2e33a80-5ae6-11ea-98f8-4f1cbbef7925.png)

**Comment by JosephMcc** [comment]
Thank you for clarifying so I know I understand correctly. What you see is pretty much how submenus work in Cinnamon. I do think you have some good suggestions though and we can keep those in mind. I'm going to go ahead and close this since it isn't really a bug.

**Comment by mjeriefr** [comment]
Thanks for keeping it in mind!
