### ISSUE TITLE
Change the browser in the `Menu` from `Firefox` to `Web`

### ISSUE THREAD

**Issue by ovari** [linuxmint/cinnamon#9191]
```
 * Cinnamon version: 4.4.8
 * Distribution: Mint 19.3
 * 64-bit
 ```

**Issue**

Change the browser in the `Menu` from [Firefox](https://www.mozilla.org/firefox/) to [Web](https://wiki.gnome.org/Apps/Web/).

**Steps to reproduce**

1. Install `GNOME Web` from the `Software Manager`.
> You may install Web from the software repositories of most Linux operating systems, where it is normally packaged as "epiphany-browser" or "epiphany".
https://wiki.gnome.org/Apps/Web/
2. In `Preferred Applications`, changes the `Web` application from `Firefox Web Browser` to `Web`.
3. Referring to the image below of the `Menu`, how can the `Firefox Web Browser` items be changed to `Web`? i.e. 
a) Firefox icon
b) Firefox link
c) `Firefox Web Browser` text
d) `Browse the World Wide Web` text
![Menu](https://user-images.githubusercontent.com/17465872/75839114-16a18200-5e1c-11ea-8d5e-296137cafe98.png)

Thank you

**Expected behaviour**

Be able to change the web browser in the Linux Mint Menu.

**Comment by Odyseus** [comment]
Hello, @ovari.

That section of the menu is the favorites box. You can add/remove items to/from there. You can drag them out of the box to remove them or drag them in to add them. You can also add/remove items to/from the favorites box from the items context menu.

**Comment by ovari** [comment]
Thank you.

Tried right-clicking on the icon and nothing showed to delete them.

**Comment by Odyseus** [comment]
> You can also add/remove items to/from the favorites box from the items context menu.

I was referring to the items in the menu, not inside the favorites box. For example, right click on the item **Internet** > **Firefox Web Browser**. If Firefox is already a favorite, it will offer you to remove it, else it will offer you to add it. The same goes for any other item inside any other category.

**Comment by Odyseus** [comment]
> You can also add/remove items to/from the favorites box from the items context menu.

@ovari: I was referring to the items in the menu, not inside the favorites box. For example, right click on the item **Internet** > **Firefox Web Browser**. If Firefox is already a favorite, it will offer you to remove it, else it will offer you to add it. The same goes for any other item inside any other category.
