### ISSUE TITLE
Applet not loading

### ISSUE THREAD

**Issue by isandeman** [linuxmint/cinnamon#9194]
```
 * Cinnamon version Cinnamon 4.4.8
 * Distribution - Mint 19.3
 * 64 bit

**Issue**
Applet not loading.
Error shown in logs with "String buffer too small" message.

[xsession-errors.log](https://github.com/linuxmint/cinnamon/files/4292284/xsession-errors.log)

**Comment by brownsr** [comment]
There's not enough information here for us to assess.  Please attach the relevant section of the log.

Regards

Simon

**Comment by isandeman** [comment]
I wouldn't know what the relevant section is. I could only guess my mentions to the calendar@cinnamon.org reference, as below.
Let me know what information you'd require and where I can get it.

`
> Cjs-Message: 22:23:29.596: JS LOG: [LookingGlass/error] buffer too small
> Cjs-Message: 22:23:29.596: JS LOG: [LookingGlass/trace] 
> <----------------
> init/Date.prototype.toLocaleFormat@/usr/share/cinnamon/js/ui/environment.js:151:16
> _getCalendarDayAbbreviation@/usr/share/cinnamon/applets/calendar@cinnamon.org/calendar.js:104:9
> _buildHeader@/usr/share/cinnamon/applets/calendar@cinnamon.org/calendar.js:252:35
> Calendar@/usr/share/cinnamon/applets/calendar@cinnamon.org/calendar.js:176:9
> CinnamonCalendarApplet@/usr/share/cinnamon/applets/calendar@cinnamon.org/applet.js:56:30
> main@/usr/share/cinnamon/applets/calendar@cinnamon.org/applet.js:211:12
> createApplet@/usr/share/cinnamon/js/ui/appletManager.js:581:18
> addAppletToPanels@/usr/share/cinnamon/js/ui/appletManager.js:356:22
> finishExtensionLoad@/usr/share/cinnamon/js/ui/appletManager.js:95:14
> Extension.prototype._init/<@/usr/share/cinnamon/js/ui/extension.js:277:17
> ---------------->
> Cjs-Message: 22:23:29.601: JS WARNING: [/usr/share/cinnamon/js/misc/fileUtils.js line 210 > Function 146]: reference to undefined property "clock"
> Cjs-Message: 22:23:29.601: JS LOG: [LookingGlass/error] 
> [calendar@cinnamon.org]: this.clock is undefined
> [calendar@cinnamon.org]: Failed to load applet: calendar@cinnamon.org/16
> Cjs-Message: 22:23:29.601: JS LOG: [LookingGlass/trace] 
> <----------------
> _updateFormatString@/usr/share/cinnamon/applets/calendar@cinnamon.org/applet.js:146:13
> _onSettingsChanged@/usr/share/cinnamon/applets/calendar@cinnamon.org/applet.js:107:9
> on_applet_added_to_panel@/usr/share/cinnamon/applets/calendar@cinnamon.org/applet.js:168:9
> on_applet_added_to_panel_internal@/usr/share/cinnamon/js/ui/applet.js:375:9
> addAppletToPanels@/usr/share/cinnamon/js/ui/appletManager.js:397:9
> finishExtensionLoad@/usr/share/cinnamon/js/ui/appletManager.js:95:14
> Extension.prototype._init/<@/usr/share/cinnamon/js/ui/extension.js:277:17
> ---------------->
> Cjs-Message: 22:23:29.677: JS LOG: [LookingGlass/info] Role locked: panellauncher
> Cjs-Message: 22:23:29.681: JS LOG: [LookingGlass/info] Loaded applet panel-launchers@cinnamon.org in 92 ms
> Cjs-Message: 22:23:29.681: JS LOG: [LookingGlass/error] 
> [calendar@cinnamon.org]: Applet calendar@cinnamon.org: Could not create applet object.
> [calendar@cinnamon.org]: Error importing applet.js from calendar@cinnamon.org
> Cjs-Message: 22:23:29.681: JS LOG: [LookingGlass/trace] 
`

**Comment by icarter09** [comment]
@isandeman are you still experiencing this issue?

**Comment by isandeman** [comment]
@icarter09 no, it is working fine for quite some time.
