### ISSUE TITLE
Search bar in file dialog

### ISSUE THREAD

**Issue by Atalanttore** [linuxmint/cinnamon#9195]
Please add a search bar for file names in the current directory and subdirectories in the file dialog.

Windows has been offering such a useful feature for a long time.

Screenshot of File Dialog in Windows (see the search bar at the top right):
![Image of File Dialog in Windows](https://www.homeandlearn.uk/images/python_forms/dialog_open.png)

**Comment by leigh123linux** [comment]
GTK3 provides the file dialog, file your issue there

https://gitlab.gnome.org/GNOME/gtk/issues

**Comment by Atalanttore** [comment]
@leigh123linux Thanks for the link.

**Comment by Atalanttore** [comment]
@leigh123linux The GTK3 file dialog supports recursive search through subdirectories only on platforms that provide a system indexer API.
See: https://gitlab.gnome.org/GNOME/gtk/issues/2499

Does Linux Mint have a system indexer API?
