### ISSUE TITLE
Application icon not showing in panel after moving to another workspace

### ISSUE THREAD

**Issue by ariasmn** [linuxmint/cinnamon#9200]
```
 * Cinnamon version - 4.4.8
 * Distribution - Mint 19.3
 * Graphics hardware *and* driver used - Could reproduce the problem in several machines. UHD 620, HD520, SVGA3D in VirtualBox.
 * 32 or 64 bit - 64 bit
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog - Seems like there are no related errors in the logs. The tail content of each:

.xsession-errors
Cjs-Message: 14:40:51.015: JS LOG: [LookingGlass/info] Adding systray: mintupdate.py (24x24px)
Cjs-Message: 14:40:51.022: JS LOG: [LookingGlass/info] Resized mintupdate.py with normalized size (24x24px)
Cjs-Message: 14:41:04.875: JS LOG: [LookingGlass/info] Adding systray: mintreport (24x24px)
Cjs-Message: 14:41:04.877: JS LOG: [LookingGlass/info] Resized mintreport with normalized size (24x24px)

(tray.py:2343): Gdk-CRITICAL **: 14:41:04.884: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
Cjs-Message: 14:42:15.915: JS LOG: [LookingGlass/info] Adding systray: mintupdate.py (24x24px)
Cjs-Message: 14:42:15.920: JS LOG: [LookingGlass/info] Resized mintupdate.py with normalized size (24x24px)
Cjs-Message: 14:42:20.020: JS LOG: [LookingGlass/info] Adding systray: mintupdate.py (24x24px)
Cjs-Message: 14:42:20.022: JS LOG: [LookingGlass/info] Resized mintupdate.py with normalized size (24x24px)

/var/log/syslog
Mar  9 14:40:41 osboxes pulseaudio[1298]: [pulseaudio] bluez5-util.c: GetManagedObjects() failed: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
Mar  9 14:40:58 osboxes dbus-daemon[629]: [system] Activating via systemd: service name='org.freedesktop.PackageKit' unit='packagekit.service' requested by ':1.63' (uid=0 pid=2248 comm="/usr/bin/gdbus call --system --dest org.freedeskto" label="unconfined")
Mar  9 14:40:58 osboxes systemd[1]: Starting PackageKit Daemon...
Mar  9 14:40:58 osboxes PackageKit: daemon start
Mar  9 14:40:58 osboxes dbus-daemon[629]: [system] Successfully activated service 'org.freedesktop.PackageKit'
Mar  9 14:40:58 osboxes systemd[1]: Started PackageKit Daemon.
Mar  9 14:43:20 osboxes gnome-terminal-[1569]: g_menu_insert_item: assertion 'G_IS_MENU_ITEM (item)' failed
Mar  9 14:44:19 osboxes pulseaudio[1298]: [alsa-sink-Intel ICH] alsa-sink.c: ALSA woke us up to write new data to the device, but there was actually nothing to write.
Mar  9 14:44:19 osboxes pulseaudio[1298]: [alsa-sink-Intel ICH] alsa-sink.c: Most likely this is a bug in the ALSA driver 'snd_intel8x0'. Please report this issue to the ALSA developers.
Mar  9 14:44:19 osboxes pulseaudio[1298]: [alsa-sink-Intel ICH] alsa-sink.c: We were woken up with POLLOUT set -- however a subsequent snd_pcm_avail() returned 0 or another value < min_avail.

 ```

**Issue**
When dragging to move a window between workspaces (don't know if there is an specific name for this action), the window icon on the panel won't show. The first time moving to a certain workspace would work, but not after that.

**Steps to reproduce**

1. Grab an open application window with the mouse (left click)
2. Press the right/left arrow or a number (1-4) to move to another workspace.
3. Now that the application is moved to the desired workspace, the application icon won't show in the workspace's panel.

**Expected behaviour**
The icon should render in the workspace's panel.

**Other information**
I found about the current behaviour today after updating my work's computer to LM 19.3. Today when I got home I couldn't reproduce the error in a VM with LM 19.1 and Cinnamon 4.0.8. After updating it, I could reproduce the issue.
There is a video showing the strange behaviour: https://imgur.com/a/xQRtEXW

**Comment by TheJuiceFR** [comment]
I also get this behavior, at this point we can assume that it is unrelated to hardware. 

This bug is very annoying as it makes windows completely inaccessible if they are minimized.

**Comment by TheJuiceFR** [comment]
I've found a workaround. By going into the configuration menu for the window list applet, and toggling the 'show windows from all workspaces' option and toggling it back, it fixes any missing windows.

This doesn't prevent this from happening again, however.

**Comment by marmistrz** [comment]
I'm affected too. Another quick workaround is to restart Cinnamon with alt+f2, "r", but it's not a great workaround. :P 

This doesn't prevent this from happening again too.

**Comment by TechnologyMan101** [comment]
I can confirm that this is happening on Linux Mint 20 with Cinnamon 4.6.7 too.

[](https://termbin.com/wp7l) This is my system info.

**Comment by OrdoFlammae** [comment]
This is happening to me too. Interesting fact though: it only happens when dragging the window. If you use the predefined keybinding Ctrl+Shift+Alt+Left Arrow, it works fine.

**Comment by OrdoFlammae** [comment]
This bug also only appears when using the Grouped Window List applet - the old applet doesn't have any issues whatsoever for me.

**Comment by gadass** [comment]
@OrdoFlammae and @ariasmn, I made a commit https://github.com/linuxmint/cinnamon/pull/9819/commits/306bda5c56f555f1a7ffacc7e00980ea9116da08 to try to solve this issue. Can you use the latest commit in your applet and see if it solves the problem?

**Comment by OrdoFlammae** [comment]
@gadass, I applied the commit and restarted Cinnamon using Alt+F2. It didn't work. I'm not sure if that's because I need to do something else to get Cinnamon to actually apply the code, or if it's because the code doesn't work, since I'm not used to editing Cinnamon code.

**Comment by gadass** [comment]
@OrdoFlammae thanks for testing. I'm concluding that this commit seems to work only with cinnamon 4.6.7. Could you please tell me the cinnamon version that you are using?

**Comment by OrdoFlammae** [comment]
4.8.3

**Comment by ariasmn** [comment]
@gadass Sorry, I switched DEs a while ago so I can't test. I'll try to set-up a VM this weekend and report back to you ASAP. Thanks!

**Comment by OrdoFlammae** [comment]
I can't find the code that handles dragging to another workspace with the mouse. I'm wondering if the problem springs from the fact that the two types of switching (keyboard-shortcut v.s. dragging) are handled differently somehow.

**Comment by gadass** [comment]
@OrdoFlammae I think the problem is specific to the GWL applet. To test this you can use the window list applet, active the "Show windows from all workspaces" and move the app window to another workspace using the mouse-press with arrow or numeric keys.

**Comment by gadass** [comment]
thanks @ariasmn and don't worry, do it when you have time :).

**Comment by OrdoFlammae** [comment]
@gadass, yes, the problem is specific to the GWL applet, but I think it's because dragging+arrows uses a different event/set of events, tries to move the window to the workspace on its own (breaking something that wouldn't have been broken with the old applet), etc. It seems to me as if this is simply the GWL applet highlighting a latent bug that was already there. But I don't know a ton about the code, so I could be completely off.

**Comment by gadass** [comment]
@OrdoFlammae I see your point. I'm not sure, but try to look at "shiftWindowToWorkspace" function  located in 
/usr/share/cinnamon/js/ui/windowManager.js.  Besides that, I will install the LM 20.1 in a VM (cinnamon version 4.8.3) and try to help with this.

**Comment by gadass** [comment]
@OrdoFlammae I applied the commit https://github.com/linuxmint/cinnamon/commit/306bda5c56f555f1a7ffacc7e00980ea9116da08 in a fresh installation of LM 20.1 (cinnamon 4.8.3) and solves the issue described in this ticket (please see the video). If your issue is different from the one described, would be nice to make a video showing this new bug occurring.

https://user-images.githubusercontent.com/38897885/104044927-9165c700-51bc-11eb-814c-6e479cd60051.mp4

**Comment by OrdoFlammae** [comment]
@gadass, you're turning on "show windows from all workspaces" beforehand. I don't have this setting on (however, I have confirmed that when the setting is on, the bug doesn't appear with the patched code).

**Comment by OrdoFlammae** [comment]
> @OrdoFlammae I see your point. I'm not sure, but try to look at "shiftWindowToWorkspace" function located in
> /usr/share/cinnamon/js/ui/windowManager.js. Besides that, I will install the LM 20.1 in a VM (cinnamon version 4.8.3) and try to help with this.

Yes, that's what I'm saying, the keybinding Ctrl+Shift+Alt+Arrow is handled there, but the dragging behavior doesn't trigger any of that (from what I can tell by searching multiple keywords in the codebase).

**Comment by gadass** [comment]
@OrdoFlammae I made a new commit 627768e, could you please test if it solves this issue?
