### ISSUE TITLE
Cedilla (ç) as Enter for spanish keyboards

### ISSUE THREAD

**Issue by ajr-dev** [linuxmint/cinnamon#9201]
It would be nice to have an option on the `keyboad layout options` to have the cedilla key (`ç`) as `Enter` while `Alt+ç` would still be `}` and `Enter` would also be `Enter`. This is because cedilla is a french letter not used in spanish and modern laptops in spain have the enter in the place where full keyboard usually have the cedilla. So when using a laptop and an external keyboard it's difficult to get accustomed to have to reach further for the enter in one of them.

**Comment by mikaku** [comment]
> This is because cedilla is a french letter not used in spanish and modern laptops in spain have the enter in the place where full keyboard usually have the cedilla.

That's false, the cedilla key `ç` is a letter used in the Catalan language, the same for the mid-point (*punt volat* in Catalan), and others. All these keys have existed in Spanish/Catalan keyboards since the first day, and they will continue exist.

**Comment by NikoKrause** [comment]
Changing a keyboard layout is not something, which can be controlled by cinnamon or by Linux Mint. The right place for such requests is mentioned here:
https://github.com/linuxmint/cinnamon/issues/5366#issuecomment-224757555
