### ISSUE TITLE
[Double Hi-DPI] Keyboard layout - Flag icon size too small and is changing the size on hover

### ISSUE THREAD

**Issue by fladson** [linuxmint/cinnamon#9208]
```
 * Cinnamon 4.4.8
   - No daily builds PPA
 * Mint 19.3
 * Intel HD Graphics 620 vendor: Lenovo driver: i915
 * 64 bit
 ```

**Issue**
* The keyboard flag is too small on original state
![Screenshot from 2020-03-17 10-19-27](https://user-images.githubusercontent.com/554507/76841586-46e41a00-6839-11ea-8eca-cf5f0fad11b3.png)

* It gets bigger on hover
![Screenshot from 2020-03-17 10-20-12](https://user-images.githubusercontent.com/554507/76841598-4b103780-6839-11ea-8018-1adfd30dc0e3.png)

**Steps to reproduce**
* Set UI scaling to Double (Hi-DPI)
* Add a new keyboard layout and keep switching between them on the panel

**Expected behaviour**
It should be bigger on original state and not change on hover.

**Comment by nazar1ua** [comment]
@fladson I'm sorry, but this issue isn't fixed

**Comment by nazar1ua** [comment]
@clefebvre this issue isn't fixed

**Comment by nazar1ua** [comment]
I have a fix: comment line 33 in `/usr/share/cinnamon/applets/keyboard@cinnamon.org/applet.js`

**Comment by cvetan** [comment]
This is still issue and even on regular scaling with 100%. Linux Mint 21.3
