### ISSUE TITLE
Feature Request: Shift modifier for window tiling

### ISSUE THREAD

**Issue by unlocomqx** [linuxmint/cinnamon#9209]
```
 * Cinnamon version: Cinnamon 4.0.10
 * Distribution - Mint
 ```

It would be great to have a modifier for tiling to fill the available space
For example, when you left or right tile using the mouse, you press `shift` to tile up to the next window instead of 50%
It's would be very similar to pressing shift when resizing a window

I always use my monitor like this: 30% IDE, 70% browser so I would tile my IDE to the left then resize it to 30%, then tile the browser to the right while holding shift to fill remaining space instead of just 50%

I hope it makes sense, I can add a screenshot if needed

**Comment by icarter09** [comment]
@unlocomqx screenshots are very much appreciated and always helpful.

**Comment by unlocomqx** [comment]
In the current case, I tile like this (using the right edge)
![1 1](https://user-images.githubusercontent.com/793712/77223316-b751aa80-6b5b-11ea-8364-d8c2517ed0e3.png)

**Current result**
![2](https://user-images.githubusercontent.com/793712/77223328-cdf80180-6b5b-11ea-8069-8987db7a09c4.png)

**Desired result** (using shift modifier)
![3](https://user-images.githubusercontent.com/793712/77223356-0a2b6200-6b5c-11ea-8395-2ac317aee8f9.png)

By pressing Shift, the tile preview and the tiled window would fill the available space similarly to resizing and holding shift (the window is resized up to the next window)

**Comment by unlocomqx** [comment]
In win10, the available space is filled by default (without pressing shift)
I think it's more intuitive that way

**Comment by unlocomqx** [comment]
I closed this issue because a button modifier is not necessary for filling available screen width. Most desktops do it that way anyway.

**Comment by mtwebster** [comment]
You can 'snap' a window - identical to tiling, but remaining windows will be sized to the remaining monitor space.  This may be useful.

Take a window, ctrl-super-left, it is now tiled to the left.  Note that now if you drag another window to the non-tile area and maximize it, it will maximize only into that remaining space.  You can resize the tiled window, and the maximized window will resize to the change.

**Comment by unlocomqx** [comment]
I used snapping a lot (ctrl while tiling), it's very useful! However, when you have a third window that you want maximized, it's becomes a bit annoying. Filling available space and resizing side by side windows together is better imo
