### ISSUE TITLE
support for hidden menu bar

### ISSUE THREAD

**Issue by brainchild0** [linuxmint/cinnamon#9211]
A favorite personal feature of Ubuntu Unity and Compiz was the option to keep the menubar of all windows completely hidden until the cursor rolled over the application title bar, in which case the menu names would appear superimposed over the titlebar. 

This effect offered superior optimization of the space inside a window, without employing the OSX-style solution of maintaining a shared menu bar at the top of the desktop outside of the window with which a menu corresponds.

Would such a feature be considered in Cinnamon?

**Comment by JosephMcc** [comment]
Thanks for the feedback but there are currently no plans to implement something like this.
