### ISSUE TITLE
taskbar sound setting and alsamixer settings do not corrospond right

### ISSUE THREAD

**Issue by iconberg** [linuxmint/cinnamon#9213]
```
 * Cinnamon version 4.4.8
   - version from https://linuxmint.com/download.php
 * Distribution - 5.3.0-42-generic #34~18.04.1-Ubuntu SMP Fri Feb 28 13:42:26 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
* Graphics:  Device-1: NVIDIA driver: nvidia v: 435.21 
           Display: x11 server: X.Org 1.20.5 driver: nvidia unloaded: fbdev,modesetting,nouveau,vesa 
           resolution: 1280x1024~60Hz, 1920x1080~60Hz 
           OpenGL: renderer: GeForce GTX 1660 Ti/PCIe/SSE2 v: 4.6.0 NVIDIA 435.21 
 * 64 bit

~$ inxi -A
Audio:     Device-1: Intel 82801JI HD Audio driver: snd_hda_intel 
           Device-2: NVIDIA driver: snd_hda_intel 
           Sound Server: ALSA v: k5.3.0-42-generic 
 ```

Using the slider control in the taskbar sound setting do not change the slider controls correctly in alsamixer and vice versa. For example if slide down the volume in taskbar sound setting to 1, PCM, Front, Surround, ... all jumping to 100. 

**Steps to reproduce**
- open alsamixer and tune down all sliders to 0
- slide taskbar sound setting to 1 -> all alsamixer, PCM, Front, ... -> jumping to 100
- slide taskbar sound setting to 100 -> alsamixer master just goes to 75

**Expected behaviour**
Sliding taskbar sound setting to 50 should set alsamixer master also to 50,
all other alsamixer sliders should not change in this way, cause they should just controlled by alsamixer master slider.

**Other information**
I came on this bug cause i search for the cause why i got crackling sounds if a new sound is played. I had no such issue on my older mint install. There are no crackling sounds.

Same slider problem in older installation with the settings but no crackling sounds
~ $ uname -a
Linux leatsink 4.15.0-88-generic #88-Ubuntu SMP Tue Feb 11 20:11:34 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

~ $ inxi -A
Audio:     Card-1 NVIDIA Device 1aeb driver: snd_hda_intel Sound: ALSA v: k4.15.0-88-generic
           Card-2 Intel 82801JI (ICH10 Family) HD Audio Controller driver: snd_hda_intel

Video that shows the problem:
[audio_control_bug.mp4.tar.gz](https://github.com/linuxmint/cinnamon/files/4365291/audio_control_bug.mp4.tar.gz)

**Comment by leigh123linux** [comment]
Taskbar  sound controls pulseaudio settings not alsa!

**Comment by iconberg** [comment]
> Taskbar sound controls pulseaudio settings not alsa!

Why are then alsamixer settings are changed!? Is taskbar sound control changing pulseaudio, and pulseadio is changing alsamixer?

**Comment by collinss** [comment]
Pulseaudio can indeed control Alsa. It uses Alsa as a backend for handling device drivers, etc. The purpose of Pulseaudio is to handle all the low-level stuff like Alsa so individual implementations (such as applications and DEs) don't have to worry about it. Try installing the Pulse Audio Volume Control app (`sudo apt-get install pavucontrol`) and see if that has the same behavior as the Cinnamon sound settings. If so, then it's coming from Pulseaudio itself, and is therefore most likely intended behavior (and is outside the scope of this project in any case). If you don't see the same behavior, then we can look at what we're doing differently.

**Comment by iconberg** [comment]
Pulseaudio and taskbar sound control are corresponding each other. If i set pavucontrol to 75%, taskbar sound control are at 75% and vice versa.

If i use pulseaudio to adjust volume then alsamixer settings are misbehave/are wrong like using the taskbar sound control. For example alsamixer Master volume starts to rise first if pavucontrol is set to 17%. 
Setting pavucontrol to 1% already let pcm rise to 40 for example. At 3% most mixer settings are at 100%, front is at 100% if pavucontrol is at 18%.

**Comment by collinss** [comment]
Ok, since pavucontrol has the same behavior, it means that behavior is coming from pulseaudio and is not something we can control. Also, I suspect that it's intended behavior anyway (probably to make it sound more natural). If you are using pulse audio, it is usually recommended that you control everything through pulse audio and not through alsa directly.

**Comment by iconberg** [comment]
I found this bug at https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=818228, guess it the same problem.
