### ISSUE TITLE
Pinned apps can not be moved to the left location in the panel

### ISSUE THREAD

**Issue by rvreugde** [linuxmint/cinnamon#9215]
```
 * Cinnamon version: **4.4.8**
   - **No nightly builds**
 * Distribution: Mint 19.3 (Tricia)
 * Graphics hardware *and* driver used
`Graphics:  Device-1: Intel UHD Graphics 620 vendor: Hewlett-Packard driver: i915 v: kernel bus ID: 00:02.0 
           Device-2: Advanced Micro Devices [AMD/ATI] Lexa XT [Radeon PRO WX 3100] vendor: Hewlett-Packard driver: amdgpu 
           v: kernel bus ID: 01:00.0 
           Display: x11 server: X.Org 1.19.6 driver: amdgpu,ati,modesetting unloaded: fbdev,vesa 
           resolution: 1920x1080~60Hz, 1920x1080~60Hz 
           OpenGL: renderer: Mesa DRI Intel UHD Graphics 620 (Kabylake GT2) v: 4.5 Mesa 19.2.8 direct render: Yes 
`
 * 32 or **64 bit**
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
[xsession-errors.zip](https://github.com/linuxmint/cinnamon/files/4367824/xsession-errors.zip)
 ```

**Issue**
My pinned apps appear in the center of my panel and can not be moved to the left side. I use the "Grouped Window List" applet.
![Selection_546](https://user-images.githubusercontent.com/38208623/77292948-987d2080-6ce1-11ea-8611-89abd5b67ab6.png)

**Steps to reproduce**
* Remove panel
* Create a new panel
* Pinned apps appear in the center

**Expected behaviour**
* Pinned apps to the right side, near the menu button (like with older versions of Cinnamon)
* Opened apps to the right near the pinned apps

**Other information**
* I use the "Grouped Window List" app
* Is there an alternative to the "Grouped Window List" in Mint 19.3?

**Configuration info, if applicable**
If this bug report is related to an Applet, Desklet or Extension, please paste (or use a pastebin service) the offending extension's settings, if it has any.  You can obtain this by opening its configuration, clicking the 'hamburger' button in the upper-right corner of the window, and selecting "Export to a file". **Please be sure to review the contents and remove any personal data it may contain.**

```

Please paste here

```

**Comment by itzexor** [comment]
It sounds like the GWL applet is in the center panel box. Did you try enabling panel edit mode and dragging it to the left box? Right click an empty space on the panel and toggle panel edit mode then you can move the entire applets around to rearrange them.

**Comment by icarter09** [comment]
Mint 20 64bit
Cinnamon v4.6.7

I tried to duplicate this issue, but was unable to. @rvreugde are you still experiencing this issue?
