### ISSUE TITLE
Window move, minimise and restore

### ISSUE THREAD

**Issue by R0CKH0PP3R** [linuxmint/cinnamon#9216]
```
Cinnamon 4.4.8
Mint 19.3 & LMDE4
Nvidia & Intel graphics
64 bit
Video: https://youtu.be/1M8nNiKJnis
```
**Issue**
When only a single window is displayed it becomes glitchy after being moved, minimised and restored. As shown in the video, all works as expected until after the window is moved. The issue isn't unique to 21:9 resolutions or the Nvidia driver - the same behaviour occurs on my Intel laptop. The issue also occurs on the recent LMDE4, as well as Linux Mint 19.3 as captured.

**Steps to reproduce**
Open a single window. e.g. Nemo.
Move it to the right.
Minimise it.
Restore it.
Place mouse cursor over restored window.

**Expected behaviour**
I would expect it to behave as it did before the window was moved to the side.

**Other information**
All Cinnamon settings _should_ be at defaults on Mint 19.3, installed on Nvidia desktop. 
All settings _were_ at defaults on LMDE, running from Live media on Intel laptop.

**Comment by R0CKH0PP3R** [comment]
This is still an issue in LMDE5 beta.

**Comment by Secret-chest** [comment]
Cannot repro in LM 20.3

**Comment by R0CKH0PP3R** [comment]
Appears to be related to window effects. 
More info with regard to cinnamon in LMDE5 beta: https://github.com/linuxmint/lmde-5-cinnamon-beta/issues/10

**Comment by R0CKH0PP3R** [comment]
Finally, this appears to be resolved in Mint 21 Beta. Same hardware.
