### ISSUE TITLE
Add/Remove languages for flatpak

### ISSUE THREAD

**Issue by ovari** [linuxmint/cinnamon#9227]
```
 * Cinnamon 4.4.8
 * Distribution - Mint 19.3
 ```

**Issue**

Languages can be added/removed using Linux Mint's `Language Settings` 

![image](https://user-images.githubusercontent.com/17465872/77881675-3016dc00-72ab-11ea-9973-640902db08de.png)

When languages are added/removed, would Linux Mint please automatically add/remove languages for flatpak.

For example, by running this command automatically:
````
flatpak config --set languages 'en;fr;ar'
flatpak update
````
Will cause Flatpak to install translations and dictionaries for English, French and Arabic.

Not sure what the command is to remove flatpak languages; however, could that also happen when languages are removed?

Thank you

**Other information**

Support for spelling and grammar checkers for languages other than English<br>
https://gitlab.gnome.org/GNOME/geary/-/issues/765<br>
https://gitlab.gnome.org/GNOME/geary/-/issues/765#note_753999

**Comment by leigh123linux** [comment]
File the issue against mintlocale

https://github.com/linuxmint/mintlocale/issues

**Comment by ovari** [comment]
Done at https://github.com/linuxmint/mintlocale/issues/72

Thanks
