### ISSUE TITLE
Green Screen after Suspend on AMD 3200G

### ISSUE THREAD

**Issue by windyweather** [linuxmint/cinnamon#9232]
```
Processor: AMD Ryzen 3 3200G with Radeon Vega Graphics × 4
Sys Motherboard: ASRock Desk Mini A300
 * Cinnamon version (cinnamon --version) 4.4.8
   - Please specify if you are using the daily builds PPA NOPE
     (https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds).
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) 19.3
Fully updated as of 3 April 2020, 
KERNEL: 5.3.0-45-generic
 * Graphics hardware *and* driver used Advanced Micro Devices, Inc. [AMD/ATI] Picasso
 * 32 or 64 bit 64
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
 ```

**Issue**
About half the time, restoring from suspend, the screen is green and the system cannot be accessed. It is apparently running, based on flashes of hard drive LED.
Only way to recover is to long press power to shut off and reboot.

**Steps to reproduce**

(1) run system as normal
(2) suspend system
(3) Sometime later, short press power to wake system. Leave monitor on during suspend. Of course monitor will go to power save mode.
(4) About 1/2 the time observe solid green screen on HD monitor.

**Expected behaviour**
System should restore to working state with normal graphics usage.

**Other information**

[syslog suspendbug.tar.gz](https://github.com/linuxmint/cinnamon/files/4428377/syslog.suspendbug.tar.gz)
![20200403_082919](https://user-images.githubusercontent.com/4505159/78379949-00f0bb00-7588-11ea-93e7-4a2870f81470.jpg)

```

**Comment by leigh123linux** [comment]
Report it against mesa drivers.
