### ISSUE TITLE
Can't use Super L key in xbindkeys if already used for Cinnamon Menu

### ISSUE THREAD

**Issue by telmotrooper** [linuxmint/cinnamon#9249]
```
 * Cinnamon version: 4.4.8
 * Distribution: Arch (kernel 5.6.3-zen)
 * Graphics hardware *and* driver used: NVIDIA GeForce GT 1030 with nvidia-dkms 440.82-1
 * 64 bit
 ```

**Issue** / **Steps to reproduce**

When Cinnamon menu is setup to use Super L as the key to trigger it (default behavior), this key won't work well in xbindkeys shortcuts. E.g. using Super L + F7 in `xbindkeys` only works the second time you press F7 while holding Super L.

Example .xbindkeysrc file:
```
"xdotool key --clearmodifiers XF86AudioPrev"
  Mod2 + Mod4 + F7 + Release
```

If we right-click Cinnamon menu, click `Super L` and unassign it pressing `Backspace`, the `xbindkeys` shortcut using Super works fine.

**Expected behaviour**

There should be a way to both trigger Cinnamon menu with Super L and still use it in shortcuts in `xbindkeys`.

**Comment by mtwebster** [comment]
This isn't possible as both cinnamon and xbindkeys use the same mechanism to provide a global keybinding.

**Comment by telmotrooper** [comment]
@mtwebster Couldn't the Cinnamon Menu be triggered by a shortcut defined in the Keyboard application? I believe that would fix the issue, though I do not know the inner workings of the Menu applet to know how much of a code change that would imply.
