### ISSUE TITLE
Client-side decoration (CSD)

### ISSUE THREAD

**Issue by m-kru** [linuxmint/cinnamon#9256]
Are there any plans to add support for using CSD instead of traditional Title Bars? If such option was configurable it would be more easier to provide consistent themes.

**Comment by clefebvre** [comment]
CSD are supported by muffin already.

**Comment by m-kru** [comment]
@clefebvre I have probably constructed my question in a wrong way. What I mean is that top bar looks different for different programs and system windows. Example:
Evince
![evince](https://user-images.githubusercontent.com/26227737/79645356-17fdf280-81af-11ea-85b7-ae3df9bb5b7a.png)
System Settings:
![settings](https://user-images.githubusercontent.com/26227737/79645366-25b37800-81af-11ea-92ab-8d13921409dc.png)
Nemo:
![nemo](https://user-images.githubusercontent.com/26227737/79645371-2ba95900-81af-11ea-83f2-6e74b1f075c7.png)

What I head in mind was rather a configuration, that would make cinnamon closely related applications use CSD.

**Comment by clefebvre** [comment]
Ah ok. I think Evince is definitely the odd one out here. Most apps use traditional layouts, whether that's with titlebars (like xreader) or headerbars which don't try to reinvent the wheel (like blueberry, gnome-calculator etc..).

**Comment by clefebvre** [comment]
Themes should also provide similar looking GTK headerbars and metacity titlebars. We provide two themes here: Mint-X and Mint-Y, they make GTK and Metacity bars look almost identical.

**Comment by clefebvre** [comment]
![image](https://user-images.githubusercontent.com/1138515/79671000-d07f6280-81be-11ea-9a0e-0673a1aaa7d3.png)

**Comment by m-kru** [comment]
@clefebvre there is one problem with using Mint-Y for me. There is one application, namely terminal emulator, where I would like to have dark title bar. Is there any way to modify the metacity-3 to add an exception for application?

**Comment by JosephMcc** [comment]
@m-kru There is really nothing we can do to force an application to use a header bar or not based on some configuration setting. That is totally up to the application and it's developer, not us. Some apps apps provide this kind of setting themselves but I don't think it's all that many.
