### ISSUE TITLE
Resume from hibernate cinnamon became slow

### ISSUE THREAD

**Issue by howdev** [linuxmint/cinnamon#9269]
```
 * Cinnamon version 4.2.4
 * Distribution - Mint 19.2
 * Graphics hardware GTX 1060
 * 64 bit
 ```

**Issue**
Resume from hiberate, cinnamon performance reduced. Moving windows is lagging
Restart cinnamon solve the issue.

**Steps to reproduce**
hibernate and resume

**Expected behaviour**
performance normal

**Other information**
Issue does not exist prior to cinnamon 4. Cinnamon 3 was working fine
```

**Comment by leigh123linux** [comment]
Feel free to reopen if you can prove it's cinnamon i.e provide logs that prove it.

**Comment by howdev** [comment]
Are we normal users supposed to help you debug?

**Comment by howdev** [comment]
It is developers job to find out the problem. Users only reporting it. 
Nevertheless, I already proved is Cinnamon. It is the Vsync methods. It was lagging when resume from hibernate, if I changed vsync to none or fallback without restarting cinnamon, the performance returned to normal

**Comment by howdev** [comment]
Logs does not always show errors, you should know that.

**Comment by smurphos** [comment]
> Are we normal users supposed to help you debug?

As one 'normal user' (is there such a thing) to another the answer is yes of course it's the users responsibility to help debug

https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/

**Comment by howdev** [comment]
@smurphos  normal users does not know anything about debug or progam. The responsibility is just expecting every user to have developement level. All the bugs I reported, always has the developer initiate the thinking and asks for further information if needed, and not in this case where you let the user do the debug and you just do the coding.

**Comment by mankinskin** [comment]
Can this be reopened?
