### ISSUE TITLE
Cinnamon crashes when starting XCOM: Enemy Unknown

### ISSUE THREAD

**Issue by jug007** [linuxmint/cinnamon#9272]
* Cinnamon version: Cinnamon 4.4.8
 * Distribution: Linux Mint 19.3 Cinnamon edition 64bit
 * Graphics hardware: Nvidia GTX 1080
 *Graphics driver:  440.82
 * [xsession-errors.log](https://github.com/linuxmint/cinnamon/files/4535337/xsession-errors.log)

**Issue**
When starting XCOM: Enemy Unknown (2012) from Steam, Cinnamon crashes and asks to be restarted.

**Steps to reproduce**
Start XCOM: Enemy Unknown via Steam

**Expected behaviour**
Cinnamon should not crash

**Other information**
As this crash is 100% reproducable on my end, please just ask if there is any debug logs or anything I could make.

**Comment by clefebvre** [comment]
Install cinnamon-dbg and get the stack trace from mintreport.

**Comment by jug007** [comment]
https://termbin.com/vv6b
http://motofckr9k.ddns.net/m/crash.tar.gz

This is what you meant I hope.

**Comment by clefebvre** [comment]
Yes

**Comment by jug007** [comment]
Just tried the new update and I can confirm that Cinnamon doesn't crash anymore when starting XCOM Enemy Unknown

**Comment by jug007** [comment]
@mtwebster  Actually, it just doesn't crash *ever* time now. It just crashed again.
Here is an updated crashreport
https://termbin.com/vbjf
http://motofckr9k.ddns.net/m/crash2.tar.gz

**Comment by mtwebster** [comment]
Hi,

Did you re-build muffin to get the update?  Just want to be sure before I dig into this again.

**Comment by jug007** [comment]
I didn't re-build muffin. There was an update from the repo that had this issue in the changelog. I installed it an restarted the machine.
```
motofckr9k@motofckr9k-mint-desktop:~$ muffin --version
muffin 4.4.2
Copyright © 2001-2011 Havoc Pennington, Red Hat, Inc., und andere
Dies ist freie Software; schauen Sie in den Quelltext, um weitere Informationen zu erhalten.
Es besteht KEINE Garantie auf MARKTREIFE oder EIGNUNG für einen BESTIMMTEN ZWECK.
motofckr9k@motofckr9k-mint-desktop:~$ 
```

**Comment by jug007** [comment]
Oh nevermind actually. There was an update but it had a change for another issue with shadows. Sorry about that.

**Comment by jug007** [comment]
Okay yeah. It doesn't seem to crash anymore. The version number is still on 4.4.2, but I installed the master packages from here: https://github.com/linuxmint/muffin/releases/tag/master.mint19

**Comment by mtwebster** [comment]
Ok good, I was getting worried :)
