### ISSUE TITLE
Calculator shortcut key spawns new instance instead of revealing the existing one.

### ISSUE THREAD

**Issue by ijash** [linuxmint/cinnamon#9281]
```
 * Cinnamon 4.4.8 not daily build
 * Distribution - (Mint 19.03)
 * 64 bit
 ```

**Issue**
I am launching `gnome-calculator` with <kbd>Cal</kbd> shortcut button.
But, every time i press <kbd>Cal</kbd>, new `gnome-calculator` window spawned. I don't want this behaviour.

**Steps to reproduce**
press or hold <kbd>Cal</kbd> button and `gnome-calculator` shows.

**Expected behaviour**
I am expecting the <kbd>Cal</kbd> button launches `gnome-calculator` on first try. Then, when <kbd>Cal</kbd> is pressed again, it will reveal the existing window, and so on and so forth.

**Other information**
I've found, using dconf editor can customize the desktop.
So far, I also found the path to execute the `gnome-calculator` which is:

```
org.cinnamon.desktop.default-applications.calculator exec 'gnome-calculator'
```
I use dconf editor such as this:
[![img from askubuntu][2]][2]

So far, what I need is to change the **Custom value** with the proper command to check the existing calculator window and reveal it.
What is the command(or script maybe) to reveal forward existing `gnome-calculator`window? If it doesn't exist, simply spawn one.

Also, I've been asking in askubuntu. As this user said:
![image](https://user-images.githubusercontent.com/30673286/80806738-acbc1380-8be5-11ea-8dc7-d8e13a27f12b.png)
It was default behavior in ubuntu. (_I cannot confirm that because i don't use ubuntu_)

Is this a bug or it is intended to be like that? because, as per this posting time, [this](https://github.com/linuxmint/cinnamon/issues/8904) issue is still opened and I conclude, it may be bad for user experience.

If this not a bug, please consider this as an enhancement for next version. And that applies to other apps too( _such as when opening spotify link to an app, it spawns new window instead of the existing._)

Thanks in advance.

  [2]: https://i.stack.imgur.com/2c8gU.png

**Comment by mtwebster** [comment]
You can make a custom shortcut to do this:
```
xdotool search --class gnome-calculator windowactivate || gnome-calculator
```
We generally leave the behavior up to the app to decide.  They can focus an existing window or spawn a new one.  Gnome-calculator specifically wants to open a new instance, which is why this behavior occurs.  Other things like xed/gedit bring up the existing window.

I haven't investigate the behavior on ubuntu (gnome-shell or unity?) so I'm not sure how they're handling this.

**Comment by ijash** [comment]
@mtwebster Hi sir, your command worked. Thanks for that!
anyway, I am posting this to gnome calculator issue page. Hoping they will fix this behavior.

**Comment by bagratte** [comment]
> Gnome-calculator specifically wants to open a new instance, which is why this behavior occurs.

Yep, there's an open issue on gnome-calculator too: https://gitlab.gnome.org/GNOME/gnome-calculator/-/issues/165

**Comment by ijash** [comment]
> > Gnome-calculator specifically wants to open a new instance, which is why this behavior occurs.
> 
> Yep, there's an open issue on gnome-calculator too: https://gitlab.gnome.org/GNOME/gnome-calculator/-/issues/165

I have comprehensive workaround here: https://unix.stackexchange.com/questions/583754/how-to-focus-program-window-instead-of-spawning-new-one-if-its-already-open/583926#583926

maybe helps.
