### ISSUE TITLE
Mint 19.3 Cinamon 64bit - built in graphic driver does not recognize GPU connected via riser cable

### ISSUE THREAD

**Issue by hungnguyen286** [linuxmint/cinnamon#9282]
My computer using Phanteks Universal Vertical GPU Bracket (https://www.amazon.com/Phanteks-PH-VGPUKT_02-Universal-Vertical-Pci/dp/B07MW73HTJ) to connect GPU with motherboard.
However when I try to install Linux Mint 19.3 Cinamon version - after select Install Linux Mint option, my screen totally blank forever (Windows 10 installation works fine since I plan to have a dual boot OS).
Thus I guess that the built-in graphic driver in the installation media have no driver for riser cable.
Appreciate is this issue will be fixed in next Cinamon release.

**Comment by GeorgelT** [comment]
can you try booting with nomodeset flag. Also what GPU are you using. It might be newer than the driver on the ISO.

I was initially thinking it was the riser, but if it works in windows then it's a driver issue more than a hardware issue.

**Comment by leigh123linux** [comment]
Please report the issue against the kernel.
