### ISSUE TITLE
Menu option to only search by application names

### ISSUE THREAD

**Issue by GeorgelT** [linuxmint/cinnamon#9290]
Hello, not sure if this is the right place for this, but it's become increasingly frustrating to search in the launcher when there are multiple apps with very similar command line. 

Is there a way for the search to prioritize actual names first and commands later?
As an example, searching for "steam" lists not only steam, but also all the installed games for steam in alfabetical order. If you see in the screenshot none of the listings actually contain steam in the name.
![menu search](https://i.imgur.com/KVa8YVZ.png)

This makes it difficult to start, in this case steam, just by typing. One has to also go down the list to the desired entry.

Not sure if this is a bug or desired outcome.
For info, I'm running Mint Cinnamon 19.2 up to date.

**Comment by cyan-lime** [comment]
A big problem with the menu search in Cinnamon is that it doesn't attempt to prioritize more relevant results at all. In fact, it simply lists all the apps that match your search string (whether in the name or the description) in alphabetical order, and then automatically selects the very first entry on the list.

In my opinion a much more desirable behaviour would be to first prioritize matches at the beginning of the application's name, then matches in the name overall, then matches in the description after that. This would give Cinnamon's menu much more utility as a quick application launcher, much like the GNOME overview search, the KDE menu search, or Xfce's Whisker Menu search. As it stands, if you try to use the Cinnamon menu search like this you'll end up with the wrong application popping up very frequently.

**Comment by NikoKrause** [comment]
Fixed by https://github.com/linuxmint/cinnamon/commit/a6738bd306180b4e2e668c90c1d7d5d6c0578906
