### ISSUE TITLE
Alpha PPA - Cinnamon crashing on logging in

### ISSUE THREAD

**Issue by smurphos** [linuxmint/cinnamon#9295]
```
 * Cinnamon version cinnamon/bionic,now 4.4.8-unstable-202005091620~ubuntu18.04.1 amd64
   - Alpha PPA - Yes
 * Distribution - Mint 19.3
 * Graphics hardware *and* driver used
steve@steve-VirtualBox:~/Desktop$ inxi -Gxxxz
Graphics:  Device-1: VMware SVGA II Adapter driver: vmwgfx v: 2.15.0.0 bus ID: 00:02.0 chip ID: 15ad:0405 
           Display: x11 server: X.Org 1.20.5 driver: vmware unloaded: fbdev,modesetting,vesa resolution: 1920x1080~60Hz 
           OpenGL: renderer: SVGA3D; build v: 2.1 Mesa 19.2.8 direct render: Ye
 * 64bit
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
 ```

**Issue**

Cinnamon is crashing on login after applying current updates from PPA. mintmenu is also failing to load on the mate-panel fallback
**Steps to reproduce**
Login
**Expected behaviour**
No Crash
**Other information**
This install is pretty much vanilla.

Crash report - https://termbin.com/nd4e
~/.xsession-errors - https://termbin.com/b2f2
/var/log/syslog - https://termbin.com/s2xkl

**Configuration info, if applicable**
If this bug report is related to an Applet, Desklet or Extension, please paste (or use a pastebin service) the offending extension's settings, if it has any.  You can obtain this by opening its configuration, clicking the 'hamburger' button in the upper-right corner of the window, and selecting "Export to a file". **Please be sure to review the contents and remove any personal data it may contain.**

```

Please paste here

```

**Comment by smurphos** [comment]
Looking at the GDB Backtrace I suspect this has something to do with the new GPU offload support https://github.com/linuxmint/xapps/commit/dcb600595dcc6a5ffab3219405e4f5d3d895995e
@mtwebster

**Comment by mtwebster** [comment]
Fixed here: https://github.com/linuxmint/xapps/commit/1d6d97981fda590318b5002e9a56de53bb19abb0

I messed up the "Fixes" link - I'm failing all over here.

Thanks
