### ISSUE TITLE
Cinnamon 4.6: Configuration section of applets can't open

### ISSUE THREAD

**Issue by kelebek333** [linuxmint/cinnamon#9305]
```
 * cinnamon-control-center version : 4.6.0
 * Distribution - Ubuntu 20.04 base
 * Graphics hardware *and* driver used : nvidia-340
 *  64 bit
 ```

**Issue**

Configuration section of applets can't open on Cinnamon settings 4.6 version.

**Steps to reproduce**

Open any applet and click configuration button.

**Expected behaviour**

**Other information**

```
(xlet-settings.py:24322): dbind-WARNING **: 21:26:31.599: Couldn't register with accessibility bus: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
Traceback (most recent call last):
  File "/usr/share/cinnamon/cinnamon-settings/xlet-settings.py", line 17, in <module>
    from JsonSettingsWidgets import *
  File "/usr/share/cinnamon/cinnamon-settings/bin/JsonSettingsWidgets.py", line 332, in <module>
    globals()["JSONSettings"+widget] = json_settings_factory(widget)
  File "/usr/share/cinnamon/cinnamon-settings/bin/JsonSettingsWidgets.py", line 313, in json_settings_factory
    class NewClass(globals()[subclass], JSONSettingsBackend):
KeyError: 'SoundFileChooser'
```

**Comment by mtwebster** [comment]
Can you show `dpkg --list | grep cinnamon` just to be sure all of the cinnamon packages are the same version?

**Comment by matheuscg** [comment]
I have the same problem running Cinnamon 4.6.0 on Arch Linux. I have to manually update cinnamon-menus to 4.6.0, but the problem persists.

**Comment by kelebek333** [comment]
> Can you show `dpkg --list | grep cinnamon` just to be sure all of the cinnamon packages are the same version?

I am using "Daily Build Linux Mint PPA". Output of the command is below.

`dpkg --list | grep cinnamon
ii  cinnamon                             4.6.0-unstable-202005131312~ubuntu20.04.1      amd64        Modern Linux desktop
ii  cinnamon-common                      4.6.0-unstable-202005131312~ubuntu20.04.1      all          Cinnamon desktop (Common data files)
ii  cinnamon-control-center              4.6.0-unstable-202005121540~ubuntu20.04.1      amd64        utilities to configure the Cinnamon desktop
ii  cinnamon-control-center-data         4.6.0-unstable-202005121540~ubuntu20.04.1      all          configuration applets for Cinnamon - data files
ii  cinnamon-core                        2020.04.22                                     all          Cinnamon desktop environment - essential components
ii  cinnamon-desktop-data                4.6.0-unstable-202005121249~ubuntu20.04.1      all          Common files for Cinnamon desktop apps
ii  cinnamon-l10n                        4.6.0-unstable-202005121118~ubuntu20.04.1      all          Translation files for the Cinnamon desktop
ii  cinnamon-screensaver                 4.6.0-unstable-202005121306~ubuntu20.04.1      amd64        Cinnamon screen saver and locker
ii  cinnamon-session                     4.6.0-unstable-202005121259~ubuntu20.04.1      amd64        Cinnamon Session Manager - Minimal runtime
ii  cinnamon-session-common              4.6.0-unstable-202005121259~ubuntu20.04.1      all          Cinnamon Session Manager - common files
ii  cinnamon-settings-daemon             4.6.0+ulyana                                   amd64        daemon handling the Cinnamon session settings
ii  gir1.2-cinnamondesktop-3.0           4.6.0-unstable-202005121249~ubuntu20.04.1      amd64        Introspection data for CinnamonDesktop
ii  libcinnamon-control-center1:amd64    4.6.0-unstable-202005121540~ubuntu20.04.1      amd64        utilities to configure the Cinnamon desktop
ii  libcinnamon-desktop4:amd64           4.6.0-unstable-202005121249~ubuntu20.04.1      amd64        Cinnamon library for loading .desktop files
ii  libcinnamon-menu-3-0                 4.6.0-unstable-202005121247~ubuntu20.04.1      amd64        Cinnamon implementation of the freedesktop menu specification
ii  libcscreensaver0:amd64               4.6.0-unstable-202005121306~ubuntu20.04.1      amd64        library and introspection data used by cinnamon-screensaver
ii  mint-info-cinnamon                   2020.04.06                                     all          Necessary information about the Linux Mint release and edition.
ii  mint-meta-cinnamon                   2020.04.22                                     all          Set of packages installed by default in the Cinnamon edition of Linux Mint`

**Comment by kelebek333** [comment]
> Can you show `dpkg --list | grep cinnamon` just to be sure all of the cinnamon packages are the same version?

I am using "Daily Build Linux Mint PPA". Output of the command is below.


```
dpkg --list | grep cinnamon
ii  cinnamon                             4.6.0-unstable-202005131312~ubuntu20.04.1      amd64        Modern Linux desktop
ii  cinnamon-common                      4.6.0-unstable-202005131312~ubuntu20.04.1      all          Cinnamon desktop (Common data files)
ii  cinnamon-control-center              4.6.0-unstable-202005121540~ubuntu20.04.1      amd64        utilities to configure the Cinnamon desktop
ii  cinnamon-control-center-data         4.6.0-unstable-202005121540~ubuntu20.04.1      all          configuration applets for Cinnamon - data files
ii  cinnamon-core                        2020.04.22                                     all          Cinnamon desktop environment - essential components
ii  cinnamon-desktop-data                4.6.0-unstable-202005121249~ubuntu20.04.1      all          Common files for Cinnamon desktop apps
ii  cinnamon-l10n                        4.6.0-unstable-202005121118~ubuntu20.04.1      all          Translation files for the Cinnamon desktop
ii  cinnamon-screensaver                 4.6.0-unstable-202005121306~ubuntu20.04.1      amd64        Cinnamon screen saver and locker
ii  cinnamon-session                     4.6.0-unstable-202005121259~ubuntu20.04.1      amd64        Cinnamon Session Manager - Minimal runtime
ii  cinnamon-session-common              4.6.0-unstable-202005121259~ubuntu20.04.1      all          Cinnamon Session Manager - common files
ii  cinnamon-settings-daemon             4.6.0+ulyana                                   amd64        daemon handling the Cinnamon session settings
ii  gir1.2-cinnamondesktop-3.0           4.6.0-unstable-202005121249~ubuntu20.04.1      amd64        Introspection data for CinnamonDesktop
ii  libcinnamon-control-center1:amd64    4.6.0-unstable-202005121540~ubuntu20.04.1      amd64        utilities to configure the Cinnamon desktop
ii  libcinnamon-desktop4:amd64           4.6.0-unstable-202005121249~ubuntu20.04.1      amd64        Cinnamon library for loading .desktop files
ii  libcinnamon-menu-3-0                 4.6.0-unstable-202005121247~ubuntu20.04.1      amd64        Cinnamon implementation of the freedesktop menu specification
ii  libcscreensaver0:amd64               4.6.0-unstable-202005121306~ubuntu20.04.1      amd64        library and introspection data used by cinnamon-screensaver
ii  mint-info-cinnamon                   2020.04.06                                     all          Necessary information about the Linux Mint release and edition.
ii  mint-meta-cinnamon                   2020.04.22                                     all          Set of packages installed by default in the Cinnamon edition of Linux Mint
```

**Comment by kelebek333** [comment]
I switched to ulyana repository and restart cinnamon, but the issue continues.

```
dpkg --list | grep cinnamon
ii  cinnamon                             4.6.0+ulyana                              amd64        Modern Linux desktop
ii  cinnamon-common                      4.6.0+ulyana                              all          Cinnamon desktop (Common data files)
ii  cinnamon-control-center              4.6.0+ulyana                              amd64        utilities to configure the Cinnamon desktop
ii  cinnamon-control-center-data         4.6.0+ulyana                              all          configuration applets for Cinnamon - data files
ii  cinnamon-core                        2020.04.22                                all          Cinnamon desktop environment - essential components
ii  cinnamon-desktop-data                4.6.0+ulyana                              all          Common files for Cinnamon desktop apps
ii  cinnamon-l10n                        4.6.0                                     all          Translation files for the Cinnamon desktop
ii  cinnamon-screensaver                 4.6.0+ulyana                              amd64        Cinnamon screen saver and locker
ii  cinnamon-session                     4.6.0+ulyana                              amd64        Cinnamon Session Manager - Minimal runtime
ii  cinnamon-session-common              4.6.0+ulyana                              all          Cinnamon Session Manager - common files
ii  cinnamon-settings-daemon             4.6.0+ulyana                              amd64        daemon handling the Cinnamon session settings
ii  gir1.2-cinnamondesktop-3.0           4.6.0+ulyana                              amd64        Introspection data for CinnamonDesktop
ii  libcinnamon-control-center1:amd64    4.6.0+ulyana                              amd64        utilities to configure the Cinnamon desktop
ii  libcinnamon-desktop4:amd64           4.6.0+ulyana                              amd64        Cinnamon library for loading .desktop files
ii  libcinnamon-menu-3-0                 4.6.0+ulyana                              amd64        Cinnamon implementation of the freedesktop menu specification
ii  libcscreensaver0:amd64               4.6.0+ulyana                              amd64        library and introspection data used by cinnamon-screensaver
ii  mint-info-cinnamon                   2020.04.06                                all          Necessary information about the Linux Mint release and edition.
ii  mint-meta-cinnamon                   2020.04.22                                all          Set of packages installed by default in the Cinnamon edition of Linux Mint


```

**Comment by kelebek333** [comment]
Yes, issue solved by this commit. https://github.com/linuxmint/cinnamon/pull/9306
