### ISSUE TITLE
Menu Editor not opening

### ISSUE THREAD

**Issue by bescott9944** [linuxmint/cinnamon#9318]
```
Cinnamon 4.6.0
 * Cinnamon version (cinnamon --version)
   - Please specify if you are using the daily builds PPA
     (https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds).
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
******************************************************************************************
[xsession-errors.tar.gz](https://github.com/linuxmint/cinnamon/files/4640494/xsession-errors.tar.gz)


System:    Kernel: 5.4.41-1-lts x86_64 bits: 64 compiler: gcc v: 10.1.0 Desktop: Cinnamon 4.6.0 
           Distro: Arch Linux 
Machine:   Type: Desktop Mobo: Gigabyte model: GA-78LMT-USB3 v: x.x serial: <filter> BIOS: Award v: F4 
           date: 10/19/2012 
CPU:       Topology: 6-Core model: AMD Phenom II X6 1045T bits: 64 type: MCP arch: K10 L2 cache: 3072 KiB 
           flags: lm nx pae sse sse2 sse3 sse4a svm bogomips: 32543 
           Speed: 804 MHz min/max: 800/2700 MHz Core speeds (MHz): 1: 804 2: 804 3: 804 4: 3153 5: 804 
           6: 3149 
Graphics:  Device-1: AMD Caicos XT [Radeon HD 7470/8470 / R5 235/310 OEM] vendor: Dell driver: radeon 
           v: kernel bus ID: 01:00.0 
           Display: x11 server: X.Org 1.20.8 driver: ati,radeon unloaded: fbdev,modesetting,vesa 
           resolution: 1920x1080~60Hz 
           Message: Unable to show advanced data. Required tool glxinfo missing. 
Audio:     Device-1: AMD SBx00 Azalia vendor: Gigabyte driver: snd_hda_intel v: kernel bus ID: 00:14.2 
           Device-2: Sunplus Innovation Lihappe8 Webcam L0485A2SP type: USB driver: snd-usb-audio,uvcvideo 
           bus ID: 2-1:2 
           Sound Server: ALSA v: k5.4.41-1-lts 



 * Graphics hardware *and* driver used
 * 32 or 64 bit
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
 ```

**Issue**
Got new updates from Arch of Cinnamon and now when I right click on the Menu Icon to bring up the sub menu with 3 items and one being the "configure..."... I click on it and hard drive lights flashes and nothing happens. The "Menu Config use to open and now it does not"...
Can not get to the menu editor either.
I have several systems that got a update of cinnamon the other day and it is the same on them all. 
Also I have 3 EndeavourOS (Arch based) Cinnamon desktop that are doing the same thing...

**Steps to reproduce**
yes... See above

**Expected behaviour**

config menu to open, does not.
[xsession-errors.tar.gz](https://github.com/linuxmint/cinnamon/files/4640517/xsession-errors.tar.gz)

**Other information**

**Configuration info, if applicable**
If this bug report is related to an Applet, Desklet or Extension, please paste (or use a pastebin service) the offending extension's settings, if it has any.  You can obtain this by opening its configuration, clicking the 'hamburger' button in the upper-right corner of the window, and selecting "Export to a file". **Please be sure to review the contents and remove any personal data it may contain.**

```

Please paste here
[xsession-errors.tar.gz](https://github.com/linuxmint/cinnamon/files/4640519/xsession-errors.tar.gz)


```

**Comment by leigh123linux** [comment]
https://github.com/linuxmint/cinnamon/issues/9305
