### ISSUE TITLE
I can not configure GWL

### ISSUE THREAD

**Issue by SAnrusReg** [linuxmint/cinnamon#9323]
Hello.
 * Cinnamon version (cinnamon --version) - 4.0.10
   - Please specify if you are using the daily builds PPA - no
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) - Linux Mint 19.1 Cinnamon
 * Graphics hardware *and* driver used - Intel Corporation HD Graphics 630
 * 32 or 64 bit - 64
 
Two programs under the “wine”: AkelPad and Total Commander. I put the first with the help of the installer, the second I copy the directory as is. He added both programs to the main menu and to the grouped windows list (GWL). When AkelPad launches, the launch icon coincides with the icon of the launched window, and the window of the launched Total Commander is added to all programs running under the "WINE" program. Tell me how to configure Total Commander so that he behaves the same as AkelPad. Thanks for the help.
![GWL1](https://user-images.githubusercontent.com/65653150/82433214-3010ac80-9aa2-11ea-84f3-af350ce8d569.png)
![GWL2](https://user-images.githubusercontent.com/65653150/82433226-343cca00-9aa2-11ea-98aa-f76ccb97419a.png)

**Comment by icarter09** [comment]
@SAnrusReg you still experiencing this issue?
