### ISSUE TITLE
LMDEv4 with Automount & NFSv3 : Spit Cinnamon environment

### ISSUE THREAD

**Issue by JeSuisEnPanne** [linuxmint/cinnamon#9324]
* Cinnamon version : Cinnamon 4.4.8
   - Please specify if you are using the daily builds PPA : No
 * Distribution : LMDE v4
 * Graphics hardware : Advanced Micro Devices, Inc. [AMD/ATI] Baffin [Radeon RX 460]
 * 64 bit
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog :
[syslog.txt](https://github.com/linuxmint/cinnamon/files/4657880/syslog.txt)
[syslog.1.txt](https://github.com/linuxmint/cinnamon/files/4657883/syslog.1.txt)
[xsession-errors.txt](https://github.com/linuxmint/cinnamon/files/4657887/xsession-errors.txt)
[xsession-errors.old.txt](https://github.com/linuxmint/cinnamon/files/4657888/xsession-errors.old.txt)

How are you today?

I installed Automount and Autofs on my LMDE version 4 distribution.
I configured the /etc/auto.master file.
Here is a configuration line for this file:
[auto.master.txt](https://github.com/linuxmint/cinnamon/files/4657969/auto.master.txt)

OK, here is the Internet file:
[Internet.txt](https://github.com/linuxmint/cinnamon/files/4657976/Internet.txt)

OK, here is my autofs.conf file:
[autofs.txt](https://github.com/linuxmint/cinnamon/files/4657876/autofs.txt)

Well, everything is going very well.
My network works with NFS and Nemo.

I manage to completely spit out the Cinnamon desktop, just modify the auto.master file like this:
[auto.master.bug.txt](https://github.com/linuxmint/cinnamon/files/4657981/auto.master.bug.txt)

I save the "auto.master" file.
I do under a Terminal the command: `/etc/init.d/autofs restart`
Here is the Windows X "Cinnamon" system to spit.

Bye

**Comment by icarter09** [comment]
@JeSuisEnPanne what exactly is the issue you are experiencing?
