### ISSUE TITLE
Volume adjustments from hotkeys does not display volume percentage

### ISSUE THREAD

**Issue by tdeeb** [linuxmint/cinnamon#9327]
```
 * Cinnamon version 4.4.8
 * Distribution - Linux Mint 19.3 Tricia
 * Nvidia GeForce RTX 2060
  - Driver: nvidia-driver-435.21-0ubuntu0.18.04.2
 * 64 bit
 ```

**Issue**
Increasing or lowering the sound volume with Volume up or Volume down hotkeys does not display the exact volume percentage. As shown in the screenshot below, there is a bar representing the volume, but the exact percentage is not shown and thus ambiguous.

![VolumeDisplay](https://user-images.githubusercontent.com/1388037/82615560-401baf80-9bba-11ea-8147-8c3cbf1f14ab.png)

**Steps to reproduce**
Press the Volume up or Volume down hotkey to increase/lower the sound volume and observe that the volume percentage is not shown.

**Expected behaviour**
The value of the current volume is shown in percent. For example, if the volume is at 25% and it's raised, it should show that the volume is now at 30%.

**Other information**
N/A

**Configuration info, if applicable**
N/A

**Comment by smurphos** [comment]
Hi, if you want to modify your install yourself to add this feature - https://forums.linuxmint.com/viewtopic.php?p=1762715#p1762715

**Comment by tdeeb** [comment]
That worked like a charm; thank you!

**Comment by acmpo6ou** [comment]
This is a possible solution to https://github.com/linuxmint/cinnamon/issues/12535
