### ISSUE TITLE
Can't open themes from system settings

### ISSUE THREAD

**Issue by SteveM2020** [linuxmint/cinnamon#9329]
Cinnamon 19.3 64bit

Don't know anything about a graphic driver and hardware
```
 * Cinnamon version (cinnamon --version)
   - Please specify if you are using the daily builds PPA
     (https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds).
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
 * Graphics hardware *and* driver used
 * 32 or 64 bit
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
 ```
dbus-update-activation-environment: setting DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
dbus-update-activation-environment: setting DISPLAY=:0
dbus-update-activation-environment: setting XAUTHORITY=/home/steve/.Xauthority
dbus-update-activation-environment: setting GTK_MODULES=gail:atk-bridge
dbus-update-activation-environment: setting QT_ACCESSIBILITY=1
dbus-update-activation-environment: setting CLUTTER_IM_MODULE=xim
dbus-update-activation-environment: setting LANG=en_CA.UTF-8
dbus-update-activation-environment: setting GDM_LANG=en_CA
dbus-update-activation-environment: setting DISPLAY=:0
dbus-update-activation-environment: setting MANDATORY_PATH=/usr/share/gconf/cinnamon.mandatory.path
dbus-update-activation-environment: setting XDG_GREETER_DATA_DIR=/var/lib/lightdm-data/steve
dbus-update-activation-environment: setting USER=steve
dbus-update-activation-environment: setting DESKTOP_SESSION=cinnamon
dbus-update-activation-environment: setting QT4_IM_MODULE=ibus
dbus-update-activation-environment: setting DEFAULTS_PATH=/usr/share/gconf/cinnamon.default.path
dbus-update-activation-environment: setting PWD=/home/steve
dbus-update-activation-environment: setting HOME=/home/steve
dbus-update-activation-environment: setting QT_ACCESSIBILITY=1
dbus-update-activation-environment: setting XDG_SESSION_TYPE=x11
dbus-update-activation-environment: setting XDG_DATA_DIRS=/usr/share/cinnamon:/usr/share/gnome:/home/steve/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share:/var/lib/snapd/desktop
dbus-update-activation-environment: setting XDG_SESSION_DESKTOP=cinnamon
dbus-update-activation-environment: setting GTK_MODULES=gail:atk-bridge
dbus-update-activation-environment: setting SHELL=/bin/bash
dbus-update-activation-environment: setting XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
dbus-update-activation-environment: setting QT_IM_MODULE=ibus
dbus-update-activation-environment: setting XMODIFIERS=@im=ibus
dbus-update-activation-environment: setting IM_CONFIG_PHASE=1
dbus-update-activation-environment: setting GPG_AGENT_INFO=/run/user/1000/gnupg/S.gpg-agent:0:1
dbus-update-activation-environment: setting SHLVL=1
dbus-update-activation-environment: setting LANGUAGE=en_CA:en
dbus-update-activation-environment: setting GDMSESSION=cinnamon
dbus-update-activation-environment: setting LOGNAME=steve
dbus-update-activation-environment: setting DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
dbus-update-activation-environment: setting XDG_RUNTIME_DIR=/run/user/1000
dbus-update-activation-environment: setting XAUTHORITY=/home/steve/.Xauthority
dbus-update-activation-environment: setting XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session0
dbus-update-activation-environment: setting XDG_CONFIG_DIRS=/etc/xdg/xdg-cinnamon:/etc/xdg
dbus-update-activation-environment: setting PATH=/home/steve/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
dbus-update-activation-environment: setting GTK_IM_MODULE=xim
dbus-update-activation-environment: setting _=/usr/bin/dbus-update-activation-environment
** Message: 11:50:23.244: couldn't access control socket: /run/user/1000/keyring/control: No such file or directory
** Message: 11:50:23.244: couldn't access control socket: /run/user/1000/keyring/control: No such file or directory
[cinnamon-settings-daemon-smartcard] Failed to start: no suitable smartcard driver could be found
[cinnamon-settings-daemon-smartcard] Failed to start: no suitable smartcard driver could be found
cinnamon-session[1417]: WARNING: t+4.25421s: Failed to start app: Unable to start application: Failed to execute child process “mail-notification” (No such file or directory)
cinnamon-session[1417]: WARNING: t+4.29599s: Failed to start app: Unable to start application: Failed to execute child process “/usr/bin/mailnag” (No such file or directory)
Clutter-Message: 11:50:27.468: Sync method: PRESENTATION TIME
Cjs-Message: 11:50:27.742: JS LOG: About to start Cinnamon
** Message: 11:50:28.595: nemo-desktop: session is cinnamon, establishing proxy
Cjs-Message: 11:50:29.017: JS LOG: [LookingGlass/info] Cinnamon.AppSystem.get_default() started in 1274 ms
Cjs-Message: 11:50:29.029: JS LOG: [LookingGlass/info] loading user theme: /usr/share/themes/Mint-Y-Dark/cinnamon/cinnamon.css
Cjs-Message: 11:50:29.048: JS LOG: [LookingGlass/info] added icon directory: /usr/share/themes/Mint-Y-Dark/cinnamon
Cjs-Message: 11:50:29.258: JS LOG: [LookingGlass/info] PlacesManager: Updating devices
Cjs-Message: 11:50:29.278: JS LOG: [LookingGlass/info] loaded at Sun May 24 2020 11:50:29 GMT-0600 (MDT)
Cjs-Message: 11:50:29.278: JS LOG: Cinnamon started at Sun May 24 2020 11:50:29 GMT-0600 (MDT)
Cjs-Message: 11:50:29.325: JS LOG: [LookingGlass/info] ExtensionSystem started in 0 ms
Cjs-Message: 11:50:29.325: JS LOG: [LookingGlass/info] DeskletManager started in 0 ms
Cjs-Message: 11:50:29.325: JS LOG: [LookingGlass/info] SearchProviderManager started in 0 ms
openGL version 3.3 detected (GL3 Cogl Driver)
MetaSyncRing disabled: couldn't find required GL extensions, or the minimum safe openGL version was not met
Cjs-Message: 11:50:29.478: JS LOG: [LookingGlass/info] Adding indicator: nm-applet
Cjs-Message: 11:50:29.583: JS LOG: [LookingGlass/info] Loaded applet show-desktop@cinnamon.org in 94 ms
Cjs-Message: 11:50:29.595: JS LOG: [LookingGlass/info] Loaded applet removable-drives@cinnamon.org in 12 ms
Cjs-Message: 11:50:29.645: JS LOG: [LookingGlass/info] Loaded applet calendar@cinnamon.org in 50 ms
St-Message: 11:50:29.654: cogl npot texture sizes SUPPORTED
Cjs-Message: 11:50:29.664: JS LOG: [LookingGlass/info] Loaded applet xapp-status@cinnamon.org in 18 ms
Cjs-Message: 11:50:29.671: JS LOG: [LookingGlass/info] Role locked: tray
Cjs-Message: 11:50:29.679: JS LOG: [LookingGlass/info] Loaded applet systray@cinnamon.org in 14 ms
Cjs-Message: 11:50:29.704: JS LOG: [LookingGlass/info] Loaded applet printers@cinnamon.org in 26 ms
Cjs-Message: 11:50:29.759: JS LOG: [LookingGlass/info] Loaded applet keyboard@cinnamon.org in 54 ms
Cjs-Message: 11:50:29.776: JS LOG: [LookingGlass/info] Loaded applet workspace-switcher@cinnamon.org in 18 ms
Cjs-Message: 11:50:29.828: JS LOG: [LookingGlass/info] Loaded applet power@cinnamon.org in 52 ms
Cjs-Message: 11:50:29.843: JS LOG: [LookingGlass/info] Role locked: panellauncher
Cjs-Message: 11:50:29.904: JS LOG: [LookingGlass/info] Loaded applet grouped-window-list@cinnamon.org in 74 ms

(csd-power:1690): power-plugin-CRITICAL **: 11:50:30.044: abs_to_percentage: assertion 'max > min' failed
Cjs-Message: 11:50:30.103: JS LOG: [LookingGlass/info] Loaded applet sound@cinnamon.org in 198 ms
Cjs-Message: 11:50:30.190: JS LOG: [LookingGlass/info] Hiding indicator (role already handled): nm-applet
Cjs-Message: 11:50:30.199: JS LOG: [LookingGlass/info] Loaded applet network@cinnamon.org in 96 ms
Cjs-Message: 11:50:30.533: JS LOG: [LookingGlass/info] Loaded applet menu@cinnamon.org in 334 ms
Cjs-Message: 11:50:30.534: JS LOG: [LookingGlass/info] AppletManager started in 1256 ms
Cjs-Message: 11:50:30.538: JS LOG: [LookingGlass/info] Cinnamon took 2794 ms to start
Cjs-Message: 11:50:30.561: JS LOG: Unknown network device type, is 14
Cjs-Message: 11:50:30.937: JS LOG: [LookingGlass/info] Adding systray: input-method (24x24px)
Cjs-Message: 11:50:30.937: JS LOG: [LookingGlass/info] Resized input-method with normalized size (24x24px)
cinnamon-session[1417]: WARNING: t+9.98078s: Detected that screensaver has appeared on the bus
Cjs-Message: 11:50:34.036: JS LOG: [LookingGlass/info] PlacesManager: Updating devices
Cjs-Message: 11:50:49.250: JS LOG: [LookingGlass/info] Adding XAppStatusIcon: mintUpdate.py (org.x.StatusIcon.PID-2039-0)

(cinnamon:1836): Gtk-WARNING **: 11:50:54.903: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
Cjs-Message: 11:51:08.558: JS LOG: [LookingGlass/info] Adding XAppStatusIcon: mintreport (org.x.StatusIcon.PID-2168-0)

**Issue**
Can't open themes from system settings

**Steps to reproduce**
Go to System settings/ themes and click

**Expected behaviour**
Expected app to open so I could make adjustments to my theme

**Other information**
Found what looks to be a problem in cinnamon settings
[error.pdf](https://github.com/linuxmint/cinnamon/files/4674166/error.pdf)

**Configuration info, if applicable**
If this bug report is related to an Applet, Desklet or Extension, please paste (or use a pastebin service) the offending extension's settings, if it has any.  You can obtain this by opening its configuration, clicking the 'hamburger' button in the upper-right corner of the window, and selecting "Export to a file". **Please be sure to review the contents and remove any personal data it may contain.**

```

Please paste here

```

**Comment by leigh123linux** [comment]
Post
```
ls -al /home/steve/.cache/cs_themes/
```

**Comment by SteveM2020** [comment]
steve@steve-linux:~$ ls -al /home/steve/.cache/cs_themes/
ls: cannot access '/home/steve/.cache/cs_themes/': No such file or directory

**Comment by leigh123linux** [comment]
Post

```
ls -al /home/steve/.cache
```

**Comment by SteveM2020** [comment]
steve@steve-linux:~$ ls -al /home/steve/.cache/cs_themes/
ls: cannot access '/home/steve/.cache/cs_themes/': No such file or directory
steve@steve-linux:~$ clear

steve@steve-linux:~$ ls -al /home/steve/.cache
total 308
dr-xrwxr-x  33 steve sudo    4096 Mar  6 16:42 .
drwxr-xr-x  60 steve steve   4096 May 24 11:56 ..
dr-xrwxr-x   2 steve steve   4096 Mar  6 13:20 babl
dr-xrwxr-x   3 steve steve   4096 Feb 27 12:23 BraveSoftware
dr-xrwxr-x   3 steve steve   4096 Feb 26 22:10 cinnamon-settings.py
dr-xrwxr-x   2 steve steve   4096 Feb 26 21:08 cs_backgrounds
dr-xrwxr-x   8 steve steve   4096 Feb 28 07:06 evolution
dr-xrwxr-x   2 steve steve   4096 Mar  3 20:05 filezilla
dr-xrwxr-x   3 steve steve   4096 Feb 26 20:44 flatpak
drwxr-xr-x   2 steve steve  16384 May  8 07:12 fontconfig
dr-xrwxr-x   3 steve steve   4096 Feb 28 12:58 gegl-0.3
dr-xrwxr-x   2 steve steve   4096 Feb 28 07:58 gnome-calculator
dr-xrwxr-x   2 steve steve   4096 Mar  1 15:24 gnome-screenshot
dr-xrwxr-x   3 steve steve   4096 Feb 27 13:33 google-chrome
drwx------   2 steve steve   4096 May 18 08:10 gstreamer-1.0
dr-xrwxr-x   3 steve steve   4096 Mar  5 07:51 ibus
dr-xrwxr-x 257 steve steve   4096 Mar  6 07:46 mesa_shader_cache
dr-xrwxr-x   3 steve steve   4096 Feb 26 22:38 mintinstall
dr-xrwxr-x   3 steve steve   4096 Feb 26 21:10 mozilla
dr-xrwxr-x   2 steve steve   4096 Feb 26 20:44 obexd
dr-xrwxr-x   4 steve steve   4096 Feb 27 13:14 opera
dr-xrwxr-x   2 steve steve   4096 Feb 29 13:15 qBittorrent
-rw-rw-rw-   1 steve steve 165196 Feb 27 14:32 qt_compose_cache_little_endian_aaa642a1efb049fba8d6ca0c8d22ff0a
dr-xrwxr-x   2 steve steve   4096 Mar  5 12:32 qtshadercache
dr-xrwxr-x   3 steve steve   4096 Mar  1 21:34 rhythmbox
dr-xrwxr-x   4 steve steve   4096 Mar  8 19:24 thumbnails
dr-xrwxr-x   4 steve steve   4096 Feb 26 22:38 thunderbird
dr-xrwxr-x   3 steve steve   4096 Mar  1 11:59 torbrowser
dr-xrwxr-x   3 steve steve   4096 Feb 29 14:00 transmission
dr-xrwxr-x   3 steve steve   4096 Feb 27 06:47 vivaldi
dr-xrwxr-x   2 steve steve   4096 Feb 26 21:08 wallpaper
dr-xrwxr-x   2 steve steve   4096 Feb 29 07:10 wine
dr-xrwxr-x   3 steve steve   4096 Feb 26 21:15 xreader
dr-xrwxr-x   3 steve steve   4096 Feb 27 17:54 yelp
steve@steve-linux:~$

**Comment by SteveM2020** [comment]
sorry

steve@steve-linux:~$ ls -al /home/steve/.cache
total 308
dr-xrwxr-x  33 steve sudo    4096 Mar  6 16:42 .
drwxr-xr-x  60 steve steve   4096 May 24 11:56 ..
dr-xrwxr-x   2 steve steve   4096 Mar  6 13:20 babl
dr-xrwxr-x   3 steve steve   4096 Feb 27 12:23 BraveSoftware
dr-xrwxr-x   3 steve steve   4096 Feb 26 22:10 cinnamon-settings.py
dr-xrwxr-x   2 steve steve   4096 Feb 26 21:08 cs_backgrounds
dr-xrwxr-x   8 steve steve   4096 Feb 28 07:06 evolution
dr-xrwxr-x   2 steve steve   4096 Mar  3 20:05 filezilla
dr-xrwxr-x   3 steve steve   4096 Feb 26 20:44 flatpak
drwxr-xr-x   2 steve steve  16384 May  8 07:12 fontconfig
dr-xrwxr-x   3 steve steve   4096 Feb 28 12:58 gegl-0.3
dr-xrwxr-x   2 steve steve   4096 Feb 28 07:58 gnome-calculator
dr-xrwxr-x   2 steve steve   4096 Mar  1 15:24 gnome-screenshot
dr-xrwxr-x   3 steve steve   4096 Feb 27 13:33 google-chrome
drwx------   2 steve steve   4096 May 18 08:10 gstreamer-1.0
dr-xrwxr-x   3 steve steve   4096 Mar  5 07:51 ibus
dr-xrwxr-x 257 steve steve   4096 Mar  6 07:46 mesa_shader_cache
dr-xrwxr-x   3 steve steve   4096 Feb 26 22:38 mintinstall
dr-xrwxr-x   3 steve steve   4096 Feb 26 21:10 mozilla
dr-xrwxr-x   2 steve steve   4096 Feb 26 20:44 obexd
dr-xrwxr-x   4 steve steve   4096 Feb 27 13:14 opera
dr-xrwxr-x   2 steve steve   4096 Feb 29 13:15 qBittorrent
-rw-rw-rw-   1 steve steve 165196 Feb 27 14:32 qt_compose_cache_little_endian_aaa642a1efb049fba8d6ca0c8d22ff0a
dr-xrwxr-x   2 steve steve   4096 Mar  5 12:32 qtshadercache
dr-xrwxr-x   3 steve steve   4096 Mar  1 21:34 rhythmbox
dr-xrwxr-x   4 steve steve   4096 Mar  8 19:24 thumbnails
dr-xrwxr-x   4 steve steve   4096 Feb 26 22:38 thunderbird
dr-xrwxr-x   3 steve steve   4096 Mar  1 11:59 torbrowser
dr-xrwxr-x   3 steve steve   4096 Feb 29 14:00 transmission
dr-xrwxr-x   3 steve steve   4096 Feb 27 06:47 vivaldi
dr-xrwxr-x   2 steve steve   4096 Feb 26 21:08 wallpaper
dr-xrwxr-x   2 steve steve   4096 Feb 29 07:10 wine
dr-xrwxr-x   3 steve steve   4096 Feb 26 21:15 xreader
dr-xrwxr-x   3 steve steve   4096 Feb 27 17:54 yelp
steve@steve-linux:~$

**Comment by leigh123linux** [comment]
sudo shouldn't own anything in your home directory

```
dr-xrwxr-x 33 steve sudo 4096 Mar 6 16:42 .
```

Can you post

```
ls -l /home
```

and

```
ls -la /home/steve
```

**Comment by SteveM2020** [comment]
steve@steve-linux:~$ ls -l /home
total 4
drwxr-xr-x 60 steve steve 4096 May 24 11:56 steve
steve@steve-linux:~$ 
______________________________
steve@steve-linux:~$ ls -la /home/steve
total 87248
drwxr-xr-x 60 steve steve     4096 May 24 11:56  .
drwxr-xr-x  3 root  root      4096 Feb 26 20:36  ..
drwx------  3 steve steve     4096 Feb 27 23:05  .adobe
drwxrwxr-x  9 steve steve     4096 Apr  4 12:05  .atom
-rw-------  1 steve steve     7987 May 24 13:29  .bash_history
-rw-r--r--  1 steve steve      220 Feb 26 20:36  .bash_logout
-rw-r--r--  1 steve steve     3771 Feb 26 20:36  .bashrc
drwxrwxr-x  2 steve steve     4096 Feb 28 09:03  bin
drwxrwxr-x  4 steve steve     4096 Mar  2 19:08 'Bob Serling'
dr-xrwxr-x 33 steve sudo      4096 Mar  6 16:42  .cache
-rwxrwxr-x  1 steve steve 81928836 Nov  1  2018  chatplug
drwxrwxr-x  5 steve steve     4096 Feb 26 21:08  .cinnamon
drwxr-xr-x 50 steve steve     4096 May 23 10:18  .config
drwxrwxr-x  4 steve steve     4096 Mar 12 09:40  .crossftp
drwx------  3 steve steve     4096 Mar 26 07:44  .dbus
drwxr-xr-x  2 steve steve     4096 May 24 12:39  Desktop
drwxr-xr-x 12 steve steve     4096 May 20 15:26  Documents
drwxr-xr-x  8 steve steve     4096 May  9 20:04  Downloads
drwxr-xr-x  4 steve steve     4096 Apr  4 10:21  .dvdcss
drwxrwxr-x  3 steve steve     4096 Apr  2 15:46  eclipse
drwxrwxr-x  6 steve steve     4096 Apr  2 15:46  .eclipse
drwxrwsr-x  7 steve steve     4096 Mar 16 03:22  eclipse-installer
drwxrwxr-x  4 steve steve     4096 Apr  3 13:51  eclipse-workspace
drwxrwxr-x  3 steve steve     4096 Feb 27 10:34  Environment
-rw-rw-r--  1 steve steve  4170824 Apr 26 21:15  Firefox_wallpaper.png
drwxrwxr-x  2 steve steve     4096 Feb 28 09:03  Foxit
drwx------  3 steve steve     4096 Apr 21 15:15  .gconf
drwxr-xr-x 24 steve steve     4096 May 11 08:21  .gimp-2.8
drwx------  3 steve steve     4096 Feb 28 09:03  .gnome
drwx------  4 steve steve     4096 Feb 27 11:06  .gnome2
drwx------  2 steve steve     4096 Feb 27 11:06  .gnome2_private
drwx------  3 steve steve     4096 Feb 27 17:51  .gnupg
-rw-r--r--  1 steve steve      245 May 24 11:56  .gtkrc-2.0
-rw-r--r--  1 steve steve      516 Feb 26 20:36  .gtkrc-xfce
-rw-r--r--  1 steve steve        5 Apr  8 19:51  homebusiness-websites.com
drwxrwxr-x  3 steve steve     4096 May 16 13:12  html
-rw-------  1 steve steve    24316 May 24 11:50  .ICEauthority
drwxrwxr-x  2 steve steve     4096 Feb 26 21:04  .icons
drwxr-xr-x  2 steve steve     4096 Apr  1 14:49  .idlerc
drwxrwxr-x  3 steve steve     4096 Mar  4 10:59  .java
drwxrwxr-x  2 steve steve     4096 Mar 14 09:31  Kate
drwx------  3 steve steve     4096 Feb 28 08:38  .kde
-rw-------  1 steve steve       28 Mar  4 12:54  .lesshsQ
drwxrwxr-x  3 steve steve     4096 Feb 26 21:32  .linuxmint
drwxr-xr-x  3 steve steve     4096 Feb 26 20:36  .local
drwx------  3 steve steve     4096 Feb 27 23:05  .macromedia
drwxrwxr-x  4 steve steve     4096 May 18 19:06  media
drwx------  6 steve steve     4096 Mar 14 10:41  .mozilla
-rw-rw-r--  1 steve steve   956325 May 19 14:18  mozilla.pdf
-rwxrwxr-x  1 steve steve  1885935 Nov  1  2018  node_sqlite3.node
drwxrwxr-x  3 steve steve     4096 Feb 28 14:14  .notable
-rw-rw-r--  1 steve steve      298 Feb 28 14:12  .notable.json
drwxrwxr-x  3 steve steve     4096 Feb 28 09:03  opt
drwxrwxr-x  6 steve steve     4096 Apr 16 13:18  .p2
drwxrwxr-x  4 steve steve     4096 Apr 26 20:34  papers
drwxr-xr-x  5 steve steve     4096 May 12 18:42  Pictures
drwx------  3 steve steve     4096 Feb 27 06:47  .pki
-rw-r--r--  1 steve steve      807 Feb 26 20:36  .profile
drwxr-xr-x  4 steve steve     4096 May  1 07:25  Public
drwxrwxr-x  3 steve steve     4096 Mar  6 20:34  qt
drwxr-xr-x  3 steve steve     4096 Mar 30 18:31  snap
drwxrwxr-x  8 steve steve     4096 Mar  5 23:00  SoftMaker
drwx------  2 steve steve     4096 Mar 26 15:51  .ssh
-rw-r--r--  1 steve steve        0 Feb 26 20:48  .sudo_as_admin_successful
drwxrwxr-x  2 steve steve     4096 Apr  2 15:51  .swt
drwxrwxr-x  3 steve steve     4096 Mar 25 15:08  Telegram
drwxr-xr-x  2 steve steve     4096 Feb 28 09:05  Templates
drwxrwxr-x  2 steve steve     4096 Feb 26 21:04  .themes
drwx------  4 steve steve     4096 Apr 25 19:43  .thumbnails
drwx------  6 steve steve     4096 Feb 26 22:38  .thunderbird
drwxrwxr-x  3 steve steve     4096 Apr  2 15:50  .tooling
drwxrwxr-x  3 steve steve     4096 Feb 28 08:28  .var
drwxr-xr-x 22 steve steve     4096 May 23 20:41  Videos
drwxrwxr-x  3 steve steve     4096 Feb 28 10:26  Waterfox
-rw-r--r--  1 steve steve      170 Mar  5 20:15  .wget-hsts
drwxr-xr-x  4 steve steve     4096 Apr 12 20:22  .wine
-rw-------  1 steve steve       56 May 24 11:50  .Xauthority
-rw-rw-r--  1 steve steve      131 Mar  5 07:56  .xinputrc
-rw-------  1 steve steve    42672 May 24 13:26  .xsession-errors
-rw-------  1 steve steve     9891 May 24 11:48  .xsession-errors.old
steve@steve-linux:~$

**Comment by leigh123linux** [comment]
Ok try
```
sudo chown steve:steve /home/steve/.cache
chmod 755 /home/steve/.cache
```

cinnamon-settings themes should work after that

**Comment by SteveM2020** [comment]
It's working. Thank you, I appreciate it.
