### ISSUE TITLE
Little noise in earphone when charging

### ISSUE THREAD

**Issue by OnlineLearningTutorials** [linuxmint/cinnamon#9331]
After a recent update my earphone make little buzz sound, so it irritate me listen video I thought that it was my earphone problem but second earphone make same noise. But when light goes off it work just fine. It make little noise only when charging, I don't know which package is responsible for that. This problem occurs after updating my system in approx last 10-20 days.

**Comment by leigh123linux** [comment]
Try another kernel, either way it isn't a cinnamon issue.

**Comment by leigh123linux** [comment]
It might be a hardware issue ie; a broken capacitor

**Comment by OnlineLearningTutorials** [comment]
Hardware issue, electricity problem, noise occurred only when my room fan is on, connected same board with my laptop adapter. Thanks
