### ISSUE TITLE
Need pinch to zoom gesture for touchpad

### ISSUE THREAD

**Issue by Niru2169** [linuxmint/cinnamon#9332]
I'd be very happy if we could pinch to zoom and many other touchpad gestures which could make things easier.

**Comment by kelebek333** [comment]
Hi,

You can try to install libinput-gestures-cinnamon package from my PPA. This is a meta package for modified version of libinput-gestures (for Cinnamon desktop) and gestures (GUI for libinput-gestures) 

```
sudo add-apt-repository ppa:kelebek333/inceayar
sudo apt-get update
sudo apt install libinput-gestures-cinnamon
```

You can change settings with Gestures (GUI) after installation.

**Comment by Niru2169** [comment]
> Hi,
> 
> You can try to install libinput-gestures-cinnamon package from my PPA. This is a meta package for modified version of libinput-gestures (for Cinnamon desktop) and gestures (GUI for libinput-gestures)
> 
> ```
> sudo add-apt-repository ppa:kelebek333/inceayar
> sudo apt-get update
> sudo apt install libinput-gestures-cinnamon
> ```
> 
> You can change settings any way you want with Gestures (GUI) after installation.
> 
> ![gestures-gui-cinnamon](https://user-images.githubusercontent.com/1300133/83080076-03522b80-a086-11ea-9e58-d61e08b87f6a.png)
Whoa! Thanks
