### ISSUE TITLE
[feature request] file selector dialog - support for webp format

### ISSUE THREAD

**Issue by IvoAndonov** [linuxmint/cinnamon#9335]
```
 * Cinnamon version (cinnamon --version) - 4.6.1.
   - Please specify if you are using the daily builds PPA: No.
 * Distribution - Arch
 * Graphics hardware *and* driver used: GTX 1050 Ti, 440.82
 * 64 bit
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
 ```
[xsession-errors.zip](https://github.com/linuxmint/cinnamon/files/4698439/xsession-errors.zip)

**Issue**
File selector dialog doesn't display a thumbnail preview for WEBP images

**Steps to reproduce**
Go to any website that can receive images, such as imgur. Click "browse..." and navigate to a directory with a webp image in it. Click just once on the webp image - no thumbnail will be displayed.

For comparison, navigate to a directory with a png image in it and click that image - a preview of the png image will be displayed to the right.

See the attached screenshots for better understanding what I'm talking about.

**Expected behaviour**
A thumbnail preview should be displayed for webp images.

**Other information**
![file-selector-png](https://user-images.githubusercontent.com/41172201/83198378-bafb4200-a147-11ea-8e49-4101a74d422a.png)
![file-selector-webp](https://user-images.githubusercontent.com/41172201/83198379-bc2c6f00-a147-11ea-9246-e239ca9b7a09.png)

my sysinfo in case you need it:
[rado@arch]: ~>$ sysinfo
 rado@arch
 OS: Arch Linux 
 Kernel: x86_64 Linux 5.6.14-arch1-1
 Uptime: 1d 21h 54m
 Packages: 1079
 Shell: bash
 Resolution: 1920x1080
 DE: Cinnamon 4.6.1
 WM: Muffin
 WM Theme: Mint-Y-Brownish-v4.3_for-Cinnamon_by-Valso (Cinnamox-Rhino)
 GTK Theme: Mint-Y-Brownish-v4.3_for-Cinnamon_by-Valso [GTK2/3]
 Icon Theme: Humanity-Dark
 Font: Noto Sans Bold 10
 Disk: 1,2T / 1,5T (76%)
 CPU: Intel Core i7-4770 @ 8x 3.9GHz [28.0°C]
 GPU: GeForce GTX 1050 Ti
 RAM: 3995MiB / 32037MiB

**Comment by JosephMcc** [comment]
Issues with this dialog get brought to us a lot :) We have nothing to do with this. That dialog is supplied by Gtk so any issues with it need to filed with the GNOME Gtk project.

**Comment by IvoAndonov** [comment]
Oh. I didn't know that. Then I apologize for bothering you with this and thanks for the info. :)
