### ISSUE TITLE
Cinnamon incompatible with remote desktop connection via xrdp?

### ISSUE THREAD

**Issue by skibum1981** [linuxmint/Cinnamon#934]
It seems I cannot get Cinnamon to load when I use xrdp.  Cinnamon is the default window manager on Linux Mint 13 AFAIK, but when I log in via remote desktop connection, I get something that looks a lot like gnome2 as the window manager....

**Comment by epicstar** [comment]
Linux Mint 17.1's Cinnamon crashes with sesman-xvnc via rdp still...

**Comment by anton-johansson** [comment]
Anyone has a solution or workaround for this? I know other desktop environments, such as MATE works with XRDP, but I'd rather not switch desktop environment. :(

**Comment by Vahan86** [comment]
@skibum1981, is this still an issue for you with Cinnamon 3.0?

**Comment by Vahan86** [comment]
@JosephMcc, can we close the issue?

**Comment by maldag** [comment]
Will there be an improvement for this? I'm using Cinnamon 3.2 with Mint 18.1 x64 with xRDP and it is still not connecting via rdp.

**Comment by gitjaala** [comment]
Using Cinnamon 3.2.7 - same problem still. Use fallback mode, but keyboard does not work, for instance letter "s" means same as "windows button" - cannot work with.

**Comment by mcellos** [comment]
a some problem

**Comment by joseortiz3** [comment]
same problem. I can connect, but goes back to fallback mode after crash. Linux Mint 18.3

**Comment by hiro7281** [comment]
I still experience same problem. Is there any plan to fix this?

**Comment by dexter74** [comment]
Fix ?

**Comment by gitgt** [comment]
RDP from Windows or from Mint to Mint works for me in Mint 19.2 via Xorg.  
Also desktop sharing works using RDP to console or vnc-any if VNC server running on Mint (even if vino is installed, vino-server or some other server must run). 
Only issue I see is that apart from xrdp also xorgxrdp must be installed. I think it's a dependency in Ubuntu but just recommended in Mint. So this is WFM.
If this doesn't work for someone, please provide exact details.
