### ISSUE TITLE
No panel icons in Cinnamon 4.6.1

### ISSUE THREAD

**Issue by drmoose** [linuxmint/cinnamon#9340]
* Cinnamon 4.6.1
 * ArchLinux
 * GeForce GTX 1060 6GB using nvidia-dkms driver
 * 64 bit

**Issue**

Panel icons do not render for me on Cinnamon 4.6.1, including the window list, menu, and tray applets (although programs that provide their own icon in the system tray still display). The speaker icon is also missing from the popup when pressing the volume up/down keys 

Using a foreground `cinnamon --replace` to get logs, I see many instances of this warning:

```
Cinnamon warning: Log level 8: gtk_icon_theme_choose_icon_for_scale: assertion 'scale >= 1' failed
```

Thinking this might have something to do with my icon theme ("adwaita") I tried several others to no effect. 

**Steps to reproduce**

Installing cinnamon 4.6.1 seems to be enough. Nothing else has changed, and it reproduces on a brand new home folder. Rolling back to 4.4.8 (the most recent version I have cached) makes icons once again visible.

Sorry about the scant details here, but I don't even know where to begin troubleshooting this kind of problem.

**Comment by chmat0s** [comment]
I have same problem, Arch Linux with Cinnamon and Intel graphic. Intel Corporation Skylake GT2 [HD Graphics 520]

**Comment by mtwebster** [comment]
Hi, are either of these instance in hidpi? Or just normal resolution/scale?

Is there a cinnamon-monitors.xml in your ~/.config folder? If so, try temporarily renaming it and logging out and back in.

**Comment by drmoose** [comment]
I run at 1x scaling on my desktop. My laptop is hidpi but I held off upgrading it due to this problem. I'll install the update later tonight to see whether it's different.

On the desktop, there is no cinnamon-monitors.xml, but I have cinnamon-xrandr turned off because of #6515 (which seems to be nvidia's fault rather than cinnamon's, but xrandr makes it worse)

Here's the dconf dump, minus irrelevant stuff (panels, keyboard settings, etc) for brevity

```ini
[/]
active-display-scale=1
enable-looking-glass-logs=false

[cinnamon-session]
prefer-hybrid-sleep=false
quit-delay-toggle=true
quit-time-delay=60

[desktop/a11y/applications]
screen-keyboard-enabled=true
screen-magnifier-enabled=true
screen-reader-enabled=false

[desktop/a11y/magnifier]
lens-mode=true
mag-factor=1.0

[desktop/interface]
clock-show-date=true
clock-use-24h=false
cursor-blink-time=1200
cursor-size=24
gtk-theme='Adwaita-dark'
icon-theme='gnome'
scaling-factor=uint32 1
text-scaling-factor=1.0
toolkit-accessibility=true

[desktop/media-handling]
autorun-never=false

[desktop/wm/preferences]
button-layout='menu:minimize,maximize,close'
focus-mode='mouse'
min-window-opacity=30
num-workspaces=4
theme='NumixDarkRed'
workspace-names=@as []

[muffin]
button-layout='menu,shade:minimize,maximize,close'
placement-mode='pointer'
resize-threshold=24
tile-hud-threshold=25

[settings-daemon/peripherals/keyboard]
delay=uint32 500
numlock-state='on'
repeat=true
repeat-interval=uint32 30

[settings-daemon/peripherals/mouse]
double-click=400
drag-threshold=8
locate-pointer=true
motion-threshold=1

[settings-daemon/peripherals/touchpad]
horizontal-two-finger-scrolling=true
motion-threshold=1
natural-scroll=false
vertical-edge-scrolling=false

[settings-daemon/peripherals/touchscreen]
orientation-lock=false

[settings-daemon/peripherals/wacom/9ef8b276dbe54d20abfb392e128bf048-usb:056a:0015]
area=[-1, -1, -1, -1]
[settings-daemon/plugins/xrandr]
active=false

[settings-daemon/plugins/xsettings]
antialiasing='rgba'
buttons-have-icons=true
hinting='full'
menus-have-icons=true
rgba-order='rgba'

[theme]
name='Discreet-Flat'
symbolic-size-16=16
symbolic-size-22=22
symbolic-size-24=22
symbolic-size-32=30
symbolic-size-48=42
theme-cache-updated=1590837898
```

**Comment by drmoose** [comment]
To check hidpi, I updated my laptop to 4.6.2 and it worked on the first try, even if I turned scaling off. Comparing my desktop to laptop (which I try to keep as similar as possible) revealed that my desktop had `/usr/lib/cinnamon-settings-daemon/csd-xsettings` blacklisted in pacman.  Removing that rule and reinstalling cinnamon fixed my machine.

I haven't the slightest recollection of why I did that in the first place. It might've been a guesswork attempt to find a workaround for #6515 that I just never undid. Sorry to have bothered you.

Unsure of the etiquette here since _my_ problem is solved but @chmat0s hasn't had an opportunity to reply. I guess I'll close & @chmat0s can reopen if it turns out to not be similar weird pacman settings.

**Comment by chmat0s** [comment]
Hi,
drmoose reopen this issue please. 

Hi,
mtwebster, I dont use hidpi and I dont have cinnamon-monitors.xml in my ~/.config folder
I update to Cinnamon 4.6.2 but problem still presist.
There is my dconf dump /org/cinnamon/

[/]
alttab-switcher-delay=100
alttab-switcher-enforce-primary-monitor=true
alttab-switcher-style='timeline'
applet-cache-updated=1591091076
command-history=['caribou-preferences ', 'caribou', 'gnome-control-center', 'cinnamon-menus', 'cinnamon-control-center', 'cinnamon-session', 'cinnamon-settings-daemon', 'nemo', 'gnome-tweak-tool', 'gdm3setup', 'gnome-clocks ', 'gcalccmd ', 'nemo-terminal', 'gnome-terminal --window-with-profile=desktop-term --geometry=80x45+250+75 &', 'gnome-terminal --window-with-profile=trans777 --geometry 67x35+220+50 &', 'gnome-terminal --window-with-profile=DesktopConsole_1 --title=DesktopConsole_1', 'devilspie ', 'devilspie\ngnome-terminal --window-with-profile=DesktopConsole', 'devilspie gnome-terminal --windows-with-profile=DesktopConsole', 'devilspie', 'gnome-terminal --title="Set what you want."', 'gnome-control-center ', 'zeitgeist-datahub', '/usr/bin/VBoxClient-all', 'gnome-terminal --role=borderless --window-with-profile=DesktopConsole --hide-menubar', 'gnome-tweak-tool ', 'tsclient', 'vino', 'tsclient ', 'gnome-user-share', '/home/chmatos/.cache/obexd/ ', 'remmina ', 'xfreerdp ', 'pyvenv ', 'nemo -q', 'gnome-terminal', 'xterm ', 'xterm', 'dbus-launch gnome-terminal', 'cinnamon-screensaver', 'steam ', 'python-pyvmomi', 'bash -c "cinnamon-screensaver-command -l; xset dpms force off;"', ' cinnamon-screensaver', 'p7zip-giu', '7zr ', 'exiv2 ', 'gstpw ', 'gstpw', 'exit', 'leafpad ', 'pulseaudio-equalizer', 'qpaeq', 'gnome-terminal ', 'x-terminal-emulator', 'clac', 'calc', 'e', 'g', '541', '5411', 's', 'sw', 'r']
desklet-cache-updated=1558420586
desklet-snap-interval=25
desktop-effects=false
desktop-effects-close-effect='scale'
desktop-effects-close-time=250
desktop-effects-close-transition='easeInBack'
desktop-effects-map-effect='scale'
desktop-effects-map-time=250
desktop-effects-map-transition='easeOutSine'
desktop-effects-maximize-effect='scale'
desktop-effects-maximize-time=100
desktop-effects-maximize-transition='easeInBack'
desktop-effects-minimize-effect='scale'
desktop-effects-minimize-time=250
desktop-effects-minimize-transition='easeInSine'
desktop-effects-on-dialogs=false
desktop-effects-on-menus=false
desktop-effects-style='scale'
desktop-effects-tile-effect='scale'
desktop-effects-tile-time=100
desktop-effects-tile-transition='easeInBack'
desktop-effects-unmaximize-effect='scale'
desktop-effects-unmaximize-time=100
desktop-effects-unmaximize-transition='easeOutBounce'
device-aliases=['/org/freedesktop/UPower/devices/battery_BAT1:= G71C000G7310']
enable-vfade=true
enabled-applets=['panel1:left:0:menu@cinnamon.org:0', 'panel1:left:2:workspace-switcher@cinnamon.org:21', 'panel1:right:7:power@cinnamon.org:11', 'panel1:right:8:network@cinnamon.org:9', 'panel1:right:9:show-desktop@cinnamon.org:18', 'panel1:right:5:keyboard@cinnamon.org:62', 'panel1:right:6:sound@cinnamon.org:74', 'panel1:left:1:panel-launchers@cinnamon.org:127', 'panel1:right:3:systray@cinnamon.org:134', 'panel1:right:2:notifications@cinnamon.org:135', 'panel1:left:3:window-list@cinnamon.org:139', 'panel2:right:0:calendar@cinnamon.org:144']
enabled-desklets=@as []
enabled-extensions=@as []
extension-cache-updated=1591080429
favorite-apps=['nemo.desktop', 'cinnamon-settings.desktop', 'audacious.desktop', 'pavucontrol.desktop', 'virtualbox.desktop']
hotcorner-layout=['gnome-terminal:true:200', 'scale:false:0', 'scale:false:0', 'desktop:false:0']
next-applet-id=145
next-desklet-id=20
no-adjacent-panel-barriers=true
overview-corner=['expo:false:false:0', 'scale:false:false:0', 'scale:false:false:0', 'expo:true:false:0']
panel-edit-mode=false
panel-launchers=['DEPRECATED']
panel-zone-icon-sizes='[{"panelId":1,"left":0,"center":0,"right":24},{"left":0,"center":0,"right":0,"panelId":2}]'
panel-zone-symbolic-icon-sizes='[{"panelId":1,"left":28,"center":28,"right":16},{"left":28,"center":28,"right":28,"panelId":2}]'
panel-zone-text-sizes='[{"panelId":1,"left":0,"center":0,"right":0},{"left":0,"center":0,"right":0,"panelId":2}]'
panels-autohide=['1:false', '2:false', '3:false']
panels-enabled=['1:0:bottom', '2:1:bottom']
panels-height=['1:33', '2:33', '3:25']
panels-hide-delay=['1:0', '2:0', '3:0']
panels-resizable=['1:true', '2:true', '3:false']
panels-scale-text-icons=['1:true', '2:true', '3:true']
panels-show-delay=['1:0', '2:0', '3:0']
workspace-osd-duration=400
workspace-osd-x=50
workspace-osd-y=50

[cinnamon-session]
quit-delay-toggle=false
quit-time-delay=60

[desklets/launcher]
launcher-list=['11:viber.desktop', '12:viber.desktop']

[desktop/a11y/applications]
screen-keyboard-enabled=true
screen-magnifier-enabled=false
screen-reader-enabled=false

[desktop/a11y/keyboard]
bouncekeys-delay=300
mousekeys-accel-time=300
mousekeys-enable=false
mousekeys-init-delay=300
mousekeys-max-speed=273
slowkeys-delay=300
stickykeys-enable=false
togglekeys-enable=false

[desktop/a11y/magnifier]
mag-factor=1.0

[desktop/a11y/mouse]
dwell-click-enabled=false
dwell-threshold=10
dwell-time=1.2
secondary-click-enabled=false
secondary-click-time=1.2

[desktop/applications/terminal]
exec='gnome-terminal'

[desktop/background]
color-shading-type='solid'
picture-options='zoom'
picture-uri='file:///usr/share/backgrounds/gnome/LightWaves.jpg'
primary-color='#000000000000'
secondary-color='#5789ca'

[desktop/background/slideshow]
delay=15
image-source='xml:///usr/share/gnome-background-properties/gnome-backgrounds.xml'
random-order=true
slideshow-enabled=false

[desktop/interface]
clock-show-date=true
clock-show-seconds=true
cursor-blink-time=1200
cursor-size=23
first-day-of-week=1
font-name='Sans 11'
gtk-theme='Adwaita'
icon-theme='clarity-canus'
scaling-factor=uint32 0
text-scaling-factor=1.1000000000000001
toolkit-accessibility=true

[desktop/keybindings]
custom-list=['custom0', 'custom2', 'custom5', 'custom6', 'custom1', 'custom3']
looking-glass-keybinding=['<Super>g']
show-desklets=@as []

[desktop/keybindings/custom-keybindings/custom0]
binding=['<Super>x']
command='/home/chmatos/Soft/VNC-Viewer-5.2.3-Linux-x64'
name='Real VNC'

[desktop/keybindings/custom-keybindings/custom1]
binding=['<Super>d']
command='nemo /home/chmatos/Downloads'
name='Folder Downloads'

[desktop/keybindings/custom-keybindings/custom2]
binding=['<Super>a']
command='nemo /home/chmatos/Dokumenty/TUX'
name='Folder Tux'

[desktop/keybindings/custom-keybindings/custom3]
binding=['<Super>s']
command='nemo /home/chmatos/Screenshot'
name='Screenshot'

[desktop/keybindings/custom-keybindings/custom5]
binding=['<Super>w']
command='nemo /home/chmatos/Working'
name='Folder Working'

[desktop/keybindings/custom-keybindings/custom6]
binding=['<Primary><Alt>Delete']
command='gnome-system-monitor'
name='System monitor'

[desktop/keybindings/media-keys]
area-screenshot=['<Shift>Print']
area-screenshot-clip=@as []
audio-forward=['XF86AudioForward']
audio-rewind=['XF86AudioRewind']
calculator=['XF86Calculator', '<Super>c']
logout=@as []
media=['XF86AudioMedia']
next=['XF86AudioNext']
pause=['XF86AudioPause']
play=['XF86AudioPlay']
previous=['XF86AudioPrev']
screensaver=['<Super>l', 'XF86ScreenSaver']
screenshot=['Print']
shutdown=['XF86PowerOff']
stop=['XF86AudioStop']
terminal=['<Super>y', '<Super>z']
volume-down=['XF86AudioLowerVolume']
volume-up=['XF86AudioRaiseVolume']
window-screenshot=['<Primary><Shift>Print']

[desktop/keybindings/wm]
move-to-workspace-left=['<Primary><Shift>Left']
move-to-workspace-right=['<Primary><Shift>Right']
panel-run-dialog=['<Alt>F2', '<Super>r']
push-tile-left=@as []
push-tile-right=@as []
show-desktop=@as []
switch-to-workspace-down=@as []
switch-to-workspace-left=['<Super>Left']
switch-to-workspace-right=['<Super>Right']
switch-to-workspace-up=['<Alt>F1']

[desktop/media-handling]
autorun-never=false
autorun-x-content-ignore=@as []
autorun-x-content-open-folder=@as []
autorun-x-content-start-app=['x-content/unix-software']

[desktop/notifications]
fade-opacity=40

[desktop/privacy]
recent-files-max-age=-1

[desktop/screensaver]
ask-for-away-message=false
date-format=' %A %e. %B %Y %n TÝDEN %V %n DEN %j %n UNIX TIME %s'
default-message='TUX'
font-message='Ubuntu 45'
layout-group=1
lock-delay=uint32 0
lock-enabled=false
screensaver-name=''
screensaver-webkit-theme='webkit-stars@cinnamon.org'
time-format='%H:%M:%S %Z'
use-custom-format=true
xscreensaver-hack='flyingtoasters'

[desktop/session]
idle-delay=uint32 0
session-manager-uses-logind=true

[desktop/sound]
event-sounds=false

[desktop/wm/preferences]
action-double-click-titlebar='toggle-maximize'
action-middle-click-titlebar='lower'
action-right-click-titlebar='menu'
action-scroll-titlebar='shade'
focus-mode='click'
min-window-opacity=10
mouse-button-modifier='<Alt>'
num-workspaces=4
theme='B-theme'
titlebar-font='Sans Bold 12'
workspace-names=@as []

[keybindings]
custom-list=@as []

[muffin]
button-layout='menu:minimize,maximize,close'
desktop-effects=false
edge-tiling=true
legacy-snap=false
placement-mode='center'
resize-threshold=24
snap-modifier='Control'
tile-hud-threshold=25
tile-maximize=false
workspace-cycle=false

[settings-daemon/peripherals/keyboard]
delay=uint32 500
numlock-state='on'
repeat-interval=uint32 30

[settings-daemon/peripherals/mouse]
custom-acceleration=false
custom-threshold=true
double-click=400
drag-threshold=8
left-handed=false
locate-pointer=false
middle-button-enabled=false
motion-acceleration=4.1027837259100641
motion-threshold=1
natural-scroll=false

[settings-daemon/peripherals/touchpad]
disable-while-typing=true
horiz-scroll-enabled=true
motion-threshold=1
natural-scroll=false
scroll-method='two-finger-scrolling'
tap-to-click=true
three-finger-click=3
touchpad-enabled=true
two-finger-click=0

[settings-daemon/peripherals/touchscreen]
orientation-lock=true

[settings-daemon/plugins/mouse]
active=true

[settings-daemon/plugins/power]
button-power='shutdown'
critical-battery-action='nothing'
idle-brightness=5
idle-dim-battery=true
idle-dim-time=90
lid-close-ac-action='nothing'
lid-close-battery-action='nothing'
lid-close-suspend-with-external-monitor=false
lock-on-suspend=true
sleep-display-ac=900
sleep-display-battery=3600
sleep-inactive-ac-timeout=0
sleep-inactive-battery-timeout=0

[settings-daemon/plugins/xsettings]
antialiasing='rgba'
buttons-have-icons=true
hinting='full'
menus-have-icons=true

[theme]
name='cinnamon'
symbolic-relative-size=0.67000000000000004
theme-cache-updated=1591080112

Thank you

**Comment by chmat0s** [comment]
Any recommendation what I can try?

**Comment by mtwebster** [comment]
@chmat0s Do you get the same warning in your `~/.xsession-errors` as @drmoose ?

- Check that all your versions are the same for cinnamon packages (4.6.xx)  - particularly cinnamon-session, cinnamon-settings-daemon, cinnamon, cinnamon-desktop, muffin.

- Are the processes `csd-xrandr` and `csd-xsettings` running?

**Comment by chmat0s** [comment]
Hi mtwebster,
Thank you very much! Now it is ok.

My csd-xrandr and csd-xsettings was not running. I check versions and I had cinnamon-desktop-git I replace with cinnamon-desktop. 

[2020-06-05T14:49:18+0200] [ALPM] removed cinnamon-desktop-git (285.4218548-1)
[2020-06-05T14:49:18+0200] [ALPM] installed cinnamon-desktop (4.6.0-1)

After reboot panel icons are back.

Thank you for your support!

**Comment by drmoose** [comment]
Thanks again @mtwebster for your help, and the Cinnamon team, for maintaining what may be the last remaining good desktop environment on any OS.
