### ISSUE TITLE
Ability to make window resize target bigger

### ISSUE THREAD

**Issue by mbalsam-refind** [linuxmint/cinnamon#9341]
```
Cinnamon 4.4.8
 ```
When i want to resize a window i move the mouse to the right edge of the window and do a left-click.  The cursor changes the icon to resize the window. 

Issues: On a very high res screen there the size of the area that triggers the icon change is very small.  How do  you make it so it gives a larger target area within i can left click. 

Note: this is not just the area to resize the window. Some programs, e.g. JetBrains ryder, have split windows where this window resize target is also used.. 

Thanks

**Comment by mbalsam-refind** [comment]
Note:  I did try to change the  windows > behavior > Window Drag/resize threshold to 54 and it has little effect

**Comment by smurphos** [comment]
Hi,

Try `dconf write /org/cinnamon/muffin/draggable-border-width 20` in a terminal.

Default value for this key is 10 (px). Valid range is 0 to 64 (px). It's not exposed in the GUI.

Note you can also access the menu with the resize option via right click anywhere in a  window-titlebar, or with keyboard shortcut Alt-F8

**Comment by JosephMcc** [comment]
As noted by smurphos there is a setting for this it just isn't exposed in the Cinnamon settings gui. You can use dconf to set it.
