### ISSUE TITLE
check your video drivers - your system is currently running without video hardware acceleration 

### ISSUE THREAD

**Issue by mbalsam-refind** [linuxmint/cinnamon#9342]
```
Cinnamon 4.4.8
Linux Mint 19.3 Tricia \n \l

System:
  Host:  Kernel: 5.3.0-51-generic x86_64 bits: 64 compiler: gcc 
  v: 7.5.0 Desktop: Cinnamon 4.4.8 wm: muffin 4.4.2 dm: LightDM 1.26.0 
  Distro: Linux Mint 19.3 Tricia base: Ubuntu 18.04 bionic 
Machine:
  Type: Desktop System: Dell product: Precision T3600 v: 01 serial: <filter> 
  Chassis: type: 7 serial: <filter> 
  Mobo: Dell model: 0PTTT9 v: A01 serial: <filter> BIOS: Dell v: A06 
  date: 10/25/2012 
CPU:
  Topology: Quad Core model: Intel Xeon E5-1620 0 bits: 64 type: MT MCP 
  arch: Sandy Bridge rev: 7 L2 cache: 10.0 MiB 
  flags: lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx bogomips: 57465 
  Speed: 1568 MHz min/max: 1200/3800 MHz Core speeds (MHz): 1: 1262 2: 1257 
  3: 1245 4: 1257 5: 1309 6: 1295 7: 1379 8: 1595 
Graphics:
  Device-1: NVIDIA GP107GL [Quadro P600] driver: nouveau v: kernel 
  bus ID: 03:00.0 chip ID: 10de:1cb2 
  Display: x11 server: X.Org 1.19.6 driver: nouveau 
  unloaded: modesetting,vesa alternate: fbdev 
  resolution: 3840x2160~60Hz, 2560x1440~60Hz 
  OpenGL: renderer: llvmpipe (LLVM 9.0 256 bits) v: 3.3 Mesa 19.2.8 
  compat-v: 3.1 direct render: Yes 
```
Every time I reboot I get the messages 

check your video drivers - your system is currently running without video hardware acceleration 

I found a posting online that i should switch to the opensource drivers. and i did.  

It did not help the problem. 

My system appears to be using the nouveau drivers.   After i click Launch Driver manager, i get to a screen that lets me select my video drivers.  If i select 

nvidea-driver-400 or xserver-xorg-video-nouveau, i get the same result.

**Comment by mbalsam-refind** [comment]
Another potential related problem.  When the system sleeps, i wake it, but it only displays one monitor.  Sometimes i have to login and reboot.

**Comment by mbalsam-refind** [comment]
So i reinstalled with the nvidea driver and now i see this

raphics:
  Device-1: NVIDIA GP107GL [Quadro P600] driver: nvidia v: 440.59 
  bus ID: 03:00.0 chip ID: 10de:1cb2 
  Display: x11 server: X.Org 1.19.6 driver: none FAILED: nvidia 
  unloaded: modesetting,nouveau,vesa alternate: fbdev 
  resolution: 2560x1440~60Hz, 3840x2160~60Hz 
  OpenGL: renderer: llvmpipe (LLVM 9.0 256 bits) v: 3.3 Mesa 19.2.8 
  compat-v: 3.1 direct render: Yes 

DOES FAILED indicate that it did not work?

**Comment by leigh123linux** [comment]
Sorry this isn't a cinnamon issue, try using linuxmint forum instead for help with broken video driver.

**Comment by leigh123linux** [comment]
> DOES FAILED indicate that it did not work?

Yes.
