### ISSUE TITLE
Cinnamon logout and shutdown display bug

### ISSUE THREAD

**Issue by daddy33** [linuxmint/cinnamon#9343]
Hello,

I just upgraded to manjaro testing branch to give cinnamon 4.6 a try. I have noticed the following cosmetic (little) bug in the logout and shutdown/restart dialog? At the end of the text, there is "[nnbsp]". I have tested various themes and I am using french as a locale. Is it happening with other locales than french?
![Capture d’écran du 2020-05-30 19-02-17](https://user-images.githubusercontent.com/9918544/83335105-b3a07980-a2aa-11ea-820f-19113a2c0bdd.png)

Thanks.

**Comment by icarter09** [comment]
@daddy33 I'm using the english locale and not noticing the issue.

**Comment by mtwebster** [comment]
This was an issue mainly with French translations, fixed in the latest release.
