### ISSUE TITLE
Date and Time Settings causes system freeze when invalid year is entered

### ISSUE THREAD

**Issue by aviatorgeek** [linuxmint/cinnamon#9345]
Kernel: 4.15.0-101-lowlatency x86_64 bits: 64 compiler: gcc v: 7.5.0 
           Desktop: Cinnamon 4.2.4 wm: muffin dm: LightDM Distro: Linux Mint 19.2 Tina 
           base: Ubuntu 18.04 bionic 

Device-1: Intel 3rd Gen Core processor Graphics vendor: ASUSTeK driver: i915 v: kernel 
           bus ID: 00:02.0 chip ID: 8086:0166 
           Device-2: NVIDIA GF108M [GeForce GT 635M] vendor: ASUSTeK driver: nvidia v: 390.132 
           bus ID: 01:00.0 chip ID: 10de:0de3 
           Display: x11 server: X.Org 1.19.6 driver: modesetting,nvidia 
           unloaded: fbdev,nouveau,vesa resolution: 1920x1080~60Hz, 1920x1080~60Hz, 1920x1200~60Hz 
           OpenGL: renderer: GeForce GT 635M/PCIe/SSE2 v: 4.6.0 NVIDIA 390.132 direct render: Yes 

...

**Issue**

(Context: I intentionally entered a very long digit string for the year in the Date and Time Settings control panel to see how it handled validation (just looking for an example of the behavior for an application that I'm writing) and this happened...).

Upon entering an invalid string of decimal digits in the Date and Time Settings control panel, the panel froze and soon causes issues in other applications (firefox stopped responding, etc.)

**Steps to reproduce**

- Save any data you don't want to lose in open applications...
- "Mint" menu -> Preferences -> Date & Time
- press "Unlock", enter password for administrator privilege
- disable "Network Time" if enabled
- enter long digit string in "Year"
- press "Lock" to apply changes

**Expected behaviour**

Should not attempt to change the year if the entered value is clearly invalid (e.g. overflows, or perhaps if its other than exactly 4 digits, etc.) There may be additional factors taken into account during validation so as not to "break" the underlying implementation...

**Other information**

If any additional information is needed I will try to provide. The issue seems easy enough to reproduce however...

**Comment by icarter09** [comment]
Mint 19.3 64bit
Cinnamon v4.6.4

I'm not able to reproduce this issue. The `Year` field no longer allow for manual text input. 

@aviatorgeek can you retest this issue once you upgrade? Thanks.
