### ISSUE TITLE
Feature Request: Ability to override panel theme font

### ISSUE THREAD

**Issue by mfreeman72** [linuxmint/cinnamon#9353]
```
 * Cinnamon version - 4.4.8
 * Distribution - Linux Mint 19.3
 ```

**Issue**
Currently, fonts are hardcoded into the panel theme CSS files and cannot be changed without digging into the CSS and editing it by hand. Often, this results in the fonts in the panel theme looking out of place with the user's desktop font choices. I would like to see the Font Settings dialog have the option to override the panel font with the user's font choice, not the theme creator's. This would be a very simple way to give the user more freedom and control in theming their system.
```

**Comment by smurphos** [comment]
Hi, this is already in Cinnamon 4.6.x (as long as the theme supports it) - https://github.com/linuxmint/cinnamon/pull/9057

**Comment by brownsr** [comment]
A number of the 3rd party themes have had their hard coded fonts changed.  After Cinnamon 4.6 they should use the default font.  If you find one that does not, please let me know.

Regards

Simon
