### ISSUE TITLE
"User folders update" became "unavailable in "Startup applications"

### ISSUE THREAD

**Issue by Nokia808** [linuxmint/cinnamon#9354]
```
 * csd version: 4.4.0
 * Distribution: Fedora 32 Cinnamon edition
 * Graphics hardware *and* driver used: 
 * 64 bit
 ```

**Issue**
Hi. I'm a Fedora Linux 32 X64 bit Cinnamon edition.
Cinnamon DE version on my system is 4.4.8

I'm on Fedora since Fedora 24. I'm upgraded my system, all the past years, using command line through tty terminal as following:
from 24 to 26
from 26 to 28
from 28 to 30
from 30 to 32

There was "user folder update" enabled by default in "Startup application". This remain across Fedora versions. After upgrading to Fedora 32 was also existing overs weeks till before few hrs when I tried to disable it in the hope to make my Cinnamon DE loaded faster at system start (launching my laptop). After disabling "user folder update", I restart my laptop. I did not see any improvement in loading time. So, I decided to re-enable it again. But when I found it as in the following screenshot: became "Unavialable" & when I tried "Edit" to see what became I saw what you see now ! What has been happened ??

![start-up](https://user-images.githubusercontent.com/25375330/84191452-08e94180-aa88-11ea-9f49-0728be14a2ee.png)

**Comment by leigh123linux** [comment]
post
```
rpm -q xdg-user-dirs-gtk
```

**Comment by Nokia808** [comment]
Hi. Output bellow:

```
$ rpm -q xdg-user-dirs-gtk
xdg-user-dirs-gtk-0.10-17.fc32.x86_64
```

**Comment by leigh123linux** [comment]
post
```
ls ~/.config/autostart/
```

does it appear after running this?
```
rm ~/.config/autostart/user-dirs-update-gtk.desktop
```

**Comment by Nokia808** [comment]
$ ls ~/.config/autostart/
blueberry.desktop          user-dirs-update-gtk.desktop
caribou-autostart.desktop  vmware-user.desktop
gnome-keyring-ssh.desktop  website.i2pd.i2pd.desktop
plank.desktop

I run "rm ~/.config/autostart/user-dirs-update-gtk.desktop" then open "Startup applications" & yes it re-appearing again ! - see screenshot:

![corrected](https://user-images.githubusercontent.com/25375330/84196050-21108f00-aa8f-11ea-8464-544b7094df52.png)

Thank you. What was this ?

By the way, I'm on English default locale & not like to change it. So, can I disable "user folder update" without any adverse effects ?

**Comment by leigh123linux** [comment]
cinnamon-settings "Startup applications" puts an edited version /etc/xdg/autostart/*.desktop in  ~/.config/autostart/ as an override.
The above command deleted the override so default /etc/xdg/autostart/user-dirs-update-gtk.desktop takes over.
I don't know why  ~/.config/autostart/user-dirs-update-gtk.desktop was corrupt but it's doubtful it was cinnamon responsible.

**Comment by leigh123linux** [comment]
> By the way, I'm on English default locale & not like to change it. So, can I disable "user folders update" without any adverse effects ?

```
rpm -q --info xdg-user-dirs-gtk
Name        : xdg-user-dirs-gtk
Version     : 0.10
Release     : 17.fc32
Architecture: x86_64
Install Date: Wed 06 May 2020 18:39:32 BST
Group       : Unspecified
Size        : 195771
License     : GPL+
Signature   : RSA/SHA256, Fri 31 Jan 2020 23:26:31 GMT, Key ID 6c13026d12c944d0
Source RPM  : xdg-user-dirs-gtk-0.10-17.fc32.src.rpm
Build Date  : Fri 31 Jan 2020 07:44:47 GMT
Build Host  : buildvm-05.phx2.fedoraproject.org
Packager    : Fedora Project
Vendor      : Fedora Project
URL         : http://freedesktop.org/wiki/Software/xdg-user-dirs
Bug URL     : https://bugz.fedoraproject.org/xdg-user-dirs-gtk
Summary     : Gnome integration of special directories
Description :
Contains some integration of xdg-user-dirs with the gnome
desktop, including creating default bookmarks and detecting
locale changes.
```
It applies locale changes to the default home user folders  names e:g Documents, Desktop, Music, Pictures, Videos, Downloads and Public

**Comment by Nokia808** [comment]
So, as long as user do not change locale, there is no adverse effects. The adverse effects will be just not changing names of these default folders into language of new locale ...

**Comment by Nokia808** [comment]
Thank you too much for the kind support you offered me !

**Comment by leigh123linux** [comment]
> So, as long as user do not change locale, there is no adverse effects. The adverse effects will be just not changing names of these default folders into language of new locale ...

I think it runs once only after each locale change so there is little resources overhead.
