### ISSUE TITLE
how to disable right super triggering the applications menu?

### ISSUE THREAD

**Issue by tensorfoo** [linuxmint/cinnamon#9357]
Is there a way to tell Right-Super not to pop up the applications menu? I have a hardware keyboard macro which uses super+fn+key to send a mouse click event and it works fine but cinnamon pops up the apps menu as well. I don't mind it doing that for left super but i'd like to disable it for right super which is what i'd like to use for defining the keyboard macros.  

I've investigated this behaviour and I noticed the stock ubuntu 20.04 DE does not behave this way when you hit right super. It's definitely a bug to pop up the menu especially because there is no way to change it, the cinnamon-settings keyboard doesn't allow you to assign or re-assign the application menu keybinding. If the user could simply set the keybinding to only left super in the bindings, it wouldn't be an issue.

**Comment by mtwebster** [comment]
Right-click the menu applet itself, 'Configure', click the "Super R" binding and hit backspace to clear it.

**Comment by tensorfoo** [comment]
thankyou @mtwebster, appreciate the headsup.
