### ISSUE TITLE
[calendar@cinnamon.org] Incorrect time and date present on vertical panel

### ISSUE THREAD

**Issue by mubat** [linuxmint/cinnamon#9361]
```
 * Applet name: calendar@cinnamon.org
 * Cinnamon version: Cinnamon 4.4.8
 * Distribution: Linux Mint 19.3 Tricia
 * Using Nvidia driver 440.82
 * 64 bit
[syslog.txt](https://github.com/linuxmint/cinnamon/files/4764419/syslog.txt)
[xsession-errors.txt](https://github.com/linuxmint/cinnamon/files/4764421/xsession-errors.txt)

 ```
There is no Date information presents on vertical panel
![image](https://user-images.githubusercontent.com/3623986/84380543-2cc79700-abf0-11ea-909f-dd21806173fe.png)

My configuration
![image](https://user-images.githubusercontent.com/3623986/84380734-8760f300-abf0-11ea-9104-8c21f5d5b2a1.png)

**Comment by icarter09** [comment]
That setting is in reference to the calendar applet when you are viewing via clicking on the date/time.

**Comment by mubat** [comment]
@icarter09 but how then to show date on the panel?

**Comment by icarter09** [comment]
https://github.com/linuxmint/cinnamon/issues/8554
