### ISSUE TITLE
[USABILITY ISSUE] Terminal cannot be removed from the favorite apps bar

### ISSUE THREAD

**Issue by k3VTSjczL3** [linuxmint/cinnamon#9363]
```
 * Cinnamon version : Cinnamon 4.4.8
   - Please specify if you are using the daily builds PPA
   No I'm not using any PPA
 * Distribution - (Mint 19.3)
 * Graphics hardware *and* driver used : Intel Corporation HD Graphics 5500
 * 64 bit
 ```
**Issue**
The terminal app (bash frontend) cannot be removed from the favorite apps bar. The option to remove it is not active in the context menu but it still is there.

**Steps to reproduce**

1. Click on Mint Menu
2. Find Terminal from Administration sub-menu
3. Right-click on it
4. You will see 'Add to favorites' instead of 'Remove from favorites while the Terminal is still on favorites

![terpro](https://user-images.githubusercontent.com/58479925/84463630-e6128500-ac61-11ea-866a-41c3db7fa16c.png)

**Expected behaviour**
Terminal should not remain in favorites bar when the option 'Add to favorites' shows

**Other information**
This issue does not appear in Fedora 32 Cinnamon. I have not tested other distros.

**Comment by mshmm** [comment]
I have the same issue here on Linux Mint 19.3 Cinnamon 4.4.8.

**Comment by smurphos** [comment]
Interesting bug. It's caused by gnome-terminal shipping two desktop files - /usr/share/applications/org.gnome.Terminal.desktop and /usr/share/applications/gnome-terminal.desktop

The former is set in dconf as a default favorite, but it's the latter that populates the menu entry.

Workaround - just click and drag the default icon out of favourites

**Comment by k3VTSjczL3** [comment]
> Interesting bug. It's caused by gnome-terminal shipping two desktop files - /usr/share/applications/org.gnome.Terminal.desktop and /usr/share/applications/gnome-terminal.desktop
> 
> The former is set in dconf as a default favorite, but it's the latter that populates the menu entry.
> 
> Workaround - just click and drag the default icon out of favourites

thanks, that worked. will it be fixed in the next update?

**Comment by smurphos** [comment]
I'll check if the issue still exists in Mint 20 and if so will put in PR to make ensure the default favourite matches the correct .desktop file.

**Comment by smurphos** [comment]
It's not a problem in Mint 20 - gnome-terminal only has one .desktop file
