### ISSUE TITLE
Linux kernel 5.3.0-62-generic and 5.4.0-37-generic causes the screen to turn off briefly before turning back on

### ISSUE THREAD

**Issue by ovari** [linuxmint/cinnamon#9368]
```
 * Cinnamon version: 4.4.8 and 4.6
 * Distribution - Mint 19.3 Cinnamon 64-bit and Mint 20 beta Cinnamon
 ```

**Issue**

`Linux kernel 5.4.0-37-generic`

Upgrading the Linux kernel from the 5.3 to 5.4 branch now causes strange effects.

Upgrading the Linux kernel in the 5.3 branch to 5.3.0-62-generic now causes strange effects.

The screens turn off briefly before turning back on when a USB device is inserted or removed. It also happens in other seemingly random times.

Happens whenever starting and stopping a YouTube video or a Celluloid mp4.

This effect occurs with both Linux Mint 19.3 Cinnamon 64-bit and Linux Mint 20 beta, which are installed on 2 different laptop computers.

Thank you

**Comment by leigh123linux** [comment]
You need to report the issue against the kernel.

**Comment by ovari** [comment]
Thank you for your reply. Can you please advise where issues against the kernel are submitted? Thank you once again.

**Comment by leigh123linux** [comment]
Try https://wiki.ubuntu.com/Kernel/Bugs

**Comment by ovari** [comment]
Should the 5.3 kernel be available in Linux Mint 20 via the `Update Manager` → `Menu Bar` → `View` → `Linux Kernels` → `Kernels` window? Thank you

**Comment by ovari** [comment]
Reinstalled Linux Mint 20 Cinnamon beta.
* Displays correctly stays on when USB are inserted or removed.
* Display stays on correctly when starting a YouTube video when only the laptop monitor is being used, i.e. the external HDMI monitor is not attached.
* Displays briefly turn off then turn on when starting a YouTube video with there are _2 monitors_, i.e. laptop monitor and external HDMI monitor. Could this be a bug in Linux Mint updated Display manager?

**Comment by leigh123linux** [comment]
Can you post some system info 

```
inxi -GSC
```

and attach these files

```
~/.xsession-errors
```
and

```
/var/log/Xorg.0.log
```

**Comment by ovari** [comment]
````
$ inxi -GSC
System:
  Host: b-HP-Stream-Laptop-11-ak0xxx Kernel: 5.4.0-37-generic x86_64 
  bits: 64 Desktop: Cinnamon 4.6.3 Distro: Linux Mint 20 Ulyana 
CPU:
  Topology: Dual Core model: Intel Celeron N4000 bits: 64 type: MCP 
  L2 cache: 4096 KiB 
  Speed: 796 MHz min/max: 800/2600 MHz Core speeds (MHz): 1: 1797 2: 1839 
Graphics:
  Device-1: Intel UHD Graphics 605 driver: i915 v: kernel 
  Display: x11 server: X.Org 1.20.8 driver: modesetting unloaded: fbdev,vesa 
  resolution: 1366x768~60Hz, 1920x1080~60Hz 
  OpenGL: renderer: Mesa Intel UHD Graphics 600 (GLK 2) v: 4.6 Mesa 20.0.4 
````

**Comment by ovari** [comment]
[Xorg.0.log](https://github.com/linuxmint/cinnamon/files/4776156/Xorg.0.log)

**Comment by ovari** [comment]
Sorry, `~/.xsession-errors` not found or does not exist.

**Comment by leigh123linux** [comment]
> Sorry, `~/.xsession-errors` not found or does not exist.

That file should definitely exist on Linux Mint 20 Cinnamon beta, it's a hidden file in your home folder. 
The log posted doesn't show any issue.

**Comment by ovari** [comment]
Do these help?
[.xsession-errors](https://github.com/linuxmint/cinnamon/files/4779731/xsession-errors.txt)
[.xsession-errors.old](https://github.com/linuxmint/cinnamon/files/4779733/xsession-errors.old.txt)

**Comment by ovari** [comment]
This problem is now happening with kernel: 5.3.0-62-generic on Linux Mint 19.3 Cinnamon 64-bit.

Is the problem:
`Cinnamon warning: Log level 16: Called enable_unredirect_for_screen while unredirection is enabled.`

Attached: [.xsession-errors](https://github.com/linuxmint/cinnamon/files/4863180/xsession-errors.txt)

Unfortunately, both 5.3 and 5.4 kernel branches are no longer working correctly.

@leigh123linux can this please be fixed? Thank you

**Comment by ovari** [comment]
Closing as further testing seems to show that the cause is not the kernel nor Linux Mint. Thank you
