### ISSUE TITLE
Workspace label stays on screen

### ISSUE THREAD

**Issue by eiabea** [linuxmint/cinnamon#9372]
```
 * Cinnamon version: 4.6.3
 * Distribution: 5.4.44-1-MANJARO
 * Graphics hardware *and* driver used: Intel 3rd Gen Core processor Graphics Controller, i915
 * 32 or 64 bit: 64bit
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
 ```

**Issue**

Switching between workspaces shows the label of the workspace in the middle of the screen, when the option `Enable workspace OSD` is enabled in the `Workspaces`-settings. This label stays on screen and when switching to the next workspace that label appears on top and also stays on screen.

**Steps to reproduce**

1. Enable `Enable workspace OSD` option in the `Workspaces` Setting
2. Switch workspaces

**Expected behaviour**

Label should disappear shortly after switching to a workspace

**Workaround**

1. Disable `Enable workspace OSD`
2. Restart cinnamon or reboot

**Comment by mtwebster** [comment]
https://github.com/linuxmint/cinnamon/pull/9360

Fixed in next point release
