### ISSUE TITLE
custom keyboard shortcuts don't work until logout

### ISSUE THREAD

**Issue by dpirch** [linuxmint/cinnamon#9375]
```
 * Cinnamon 4.6.3 (from ppa) (same issue with 4.4.8 from ubuntu 20.04)
 * Ubuntu 20.04
 * Mesa DRI Intel(R) HD Graphics 4600 (HSW GT2)
 * 64 bit
 ```
**Issue**
When adding custom keyboard shortcuts or editing existing ones (either command or shortcut), the change does not become active immediately, but only after logging out and in again.

**Steps to reproduce**
- run cinnamon-settings, go to Keyboard > Shortcuts > Custom Shortcuts
- click "Add custom shortcut", type e.g. Name: "test", Command: "gedit", click "Add"
- assign keybinding by clicking on an "unassigned" row, press e.g. Super+F8, close window

**Expected behaviour**
the shortcut is active immediately, i.e. pressing Super+F8 launches gedit

**Actual behaviour**
the shortcut does not work - it only works after the next login.

**Other information**
Keyboard shortcuts other than custom shortcuts are apparently updated immediately.

**Comment by mtwebster** [comment]
As a workaround until this is fixed, you can restart cinnamon to update the shortcuts (it's quicker than logging out) - alt-f2, then type r in the box, and enter.

**Comment by mtwebster** [comment]
Fixed in current release: https://github.com/linuxmint/cinnamon/commit/4531ff5e9f967ce9051124519b9a9daca12e21ea
