### ISSUE TITLE
Cinnamon slowing down over time

### ISSUE THREAD

**Issue by Lurux** [linuxmint/cinnamon#9376]
* Cinnamon version: 4.4.8
* Please specify if you are using the daily builds PPA: No
* Distribution: Linux Mint 19.3 (more details below)
* Graphics hardware *and* driver used: Nvidia graphics card, several drivers used (see below)
* 32 or **64 bit**
* Attach [/home/username/.xsession-errors](https://termbin.com/4a5e) or /var/log/syslog
* More details: [Linux Mint forums](https://forums.linuxmint.com/viewtopic.php?f=208&t=306515)

**Issue**

When I install Linux Mint, Cinnamon starts in less than 10 seconds (from the time I hit enter on the login prompt to the time the desktop appears). After a few months use, it is not uncommon to wait up to 30 seconds for Cinnamon to start, but the logs still say Cinnamon starts in less than 10 seconds.

I experienced this on several installs, across several computers - Always Linux Mint 19.X, Nvidia graphics card, with various Nvidia drivers fetched through the drivers tool.

On this install (Cinnamon 4.4.8, LM 19.3, Nvidia driver 440), Cinnamon currently takes 20 seconds to start, but the logs says it takes 6198 ms.

Do note the problem also appears with a freshly created user, with no external applets or startup applications. I don't know if the problem belongs to Cinnamon or Linux Mint.

I thought this was linked to #9373, but completely removing all flatpak apps and flatpak itself from the system didn't solve the problem. The reason for this slowdown is unknown as of now.

This problem _only_ occurs in Cinnamon: XFCE or my custom Openbox install remain unaffected.

**Steps to reproduce**

- Install Linux Mint Cinnamon 19.X
- Time Cinnamon startup using a stopwatch
- Use for a few month
- Cinnamon is significantly slower to start now

**Expected behaviour**

Cinnamon should not slow down that drastically over this period of time.

**Other information**

Recap: Cinnamon startup slows down over time, but this slowdown is not reflected in the logs. This is verified on several systems running Linux Mint Cinnamon 19.X. The problem may or may not be linked to LM itself, and only affects Cinnamon.

**Configuration info, if applicable**

The problem applies regardless of external applets or startup applications, even with a freshly created user with default settings.

**Comment by Nokia808** [comment]
@Lurux 
I'm wars than you - see https://github.com/linuxmint/cinnamon/issues/9356

I'm also, noticed that the Cinnamon DE becoming slower & slower over time, but in my case, slowness develop more rapidly - just 2 weeks after system upgrade Cinnamon started to slow ...

**Comment by Lurux** [comment]
@Nokia808 I haven't measured the exact time so it might be weeks tbh

**Comment by Lurux** [comment]
I don't know if this will be efficient but I'd like to bump this issue because I'm still experiencing the problem and no solution have been found as of now.

I hope someone will be able to help with this issue, as I'm not the only person affected...

**Comment by leigh123linux** [comment]
I can't reproduce the issue on my 3 month old fedora-34 installations.

AMD Ryzen 5 3600 with nvidia 465.27

```
Clutter-Message: 17:14:09.545: Sync method: PRESENTATION TIME
Failed to rename ‘/home/leigh/.abrt/spool’ to ‘/home/leigh/.cache/abrt/spool’: No such file or directory
Failed to play sound: Sound disabled
Cjs-Message: 17:14:09.670: JS LOG: About to start Cinnamon
Cjs-Message: 17:14:09.725: JS LOG: [LookingGlass/info] Cinnamon.AppSystem.get_default() started in 53 ms
Cjs-Message: 17:14:09.729: JS LOG: [LookingGlass/info] loading user theme: /usr/share/themes/Mint-Y-Dark-Aqua/cinnamon/cinnamon.css
Cjs-Message: 17:14:09.743: JS LOG: [LookingGlass/info] added icon directory: /usr/share/themes/Mint-Y-Dark-Aqua/cinnamon
Cjs-Message: 17:14:09.909: JS LOG: [LookingGlass/info] loaded at Mon May 17 2021 17:14:09 GMT+0100 (British Summer Time)
Cjs-Message: 17:14:09.909: JS LOG: Cinnamon started at Mon May 17 2021 17:14:09 GMT+0100 (British Summer Time)
Cjs-Message: 17:14:09.915: JS LOG: [LookingGlass/info] ExtensionSystem started in 0 ms
Cjs-Message: 17:14:09.915: JS LOG: [LookingGlass/info] DeskletManager started in 0 ms
Cjs-Message: 17:14:09.915: JS LOG: [LookingGlass/info] SearchProviderManager started in 0 ms
openGL version 3.1 detected (GL3 Cogl Driver)
** Message: 17:14:09.948: nemo-desktop: session is cinnamon, establishing proxy
Cjs-Message: 17:14:09.974: JS LOG: [LookingGlass/info] Loaded applet show-desktop@cinnamon.org in 30 ms
Cjs-Message: 17:14:09.976: JS LOG: [LookingGlass/info] Role locked: tray
Cjs-Message: 17:14:09.977: JS LOG: [LookingGlass/info] Loaded applet systray@cinnamon.org in 3 ms
St-Message: 17:14:10.002: cogl npot texture sizes SUPPORTED
Cjs-Message: 17:14:10.012: JS LOG: [LookingGlass/info] Loaded applet removable-drives@cinnamon.org in 35 ms
Cjs-Message: 17:14:10.060: JS LOG: [LookingGlass/info] Loaded applet weather@mockturtl in 48 ms
Cjs-Message: 17:14:10.079: JS LOG: [LookingGlass/info] Loaded applet calendar@cinnamon.org in 19 ms
Cjs-Message: 17:14:10.094: JS LOG: [LookingGlass/info] Loaded applet keyboard@cinnamon.org in 15 ms
Cjs-Message: 17:14:10.119: JS LOG: [LookingGlass/info] Loaded applet printers@cinnamon.org in 25 ms
Cjs-Message: 17:14:10.125: JS LOG: [LookingGlass/info] Role locked: notifications
Cjs-Message: 17:14:10.132: JS LOG: [LookingGlass/info] Loaded applet notifications@cinnamon.org in 13 ms
Cjs-Message: 17:14:10.138: JS LOG: [LookingGlass/info] Loaded applet xapp-status@cinnamon.org in 6 ms
Cjs-Message: 17:14:10.153: JS LOG: [LookingGlass/info] Loaded applet power@cinnamon.org in 15 ms
Cjs-Message: 17:14:10.159: JS LOG: [LookingGlass/info] Role locked: panellauncher
Cjs-Message: 17:14:10.161: JS LOG: [LookingGlass/info] Loaded applet grouped-window-list@cinnamon.org in 8 ms

** (csd-power:1843): CRITICAL **: 17:14:10.173: abs_to_percentage: assertion 'max > min' failed
Cjs-Message: 17:14:10.193: JS LOG: [LookingGlass/info] Loaded applet sound@cinnamon.org in 32 ms
Cjs-Message: 17:14:10.208: JS LOG: [LookingGlass/info] Loaded applet network@cinnamon.org in 15 ms
Cjs-Message: 17:14:10.278: JS LOG: Unknown network device type, is 14
Cjs-Message: 17:14:10.286: JS LOG: Unknown network device type, is 29
Cjs-Message: 17:14:10.286: JS LOG: Unknown network device type, is 13
Cjs-Message: 17:14:10.286: JS LOG: Unknown network device type, is 18
Cjs-Message: 17:14:10.386: JS LOG: [LookingGlass/info] Loaded applet menu@cinnamon.org in 178 ms
Cjs-Message: 17:14:10.386: JS LOG: [LookingGlass/info] AppletManager started in 476 ms
Cjs-Message: 17:14:10.388: JS LOG: [LookingGlass/info] Cinnamon took 718 ms to start
Cjs-Message: 17:14:10.656: JS LOG: [LookingGlass/info] Hiding systray: network
Cjs-Message: 17:14:10.753: JS LOG: [LookingGlass/info] [weather@mockturtl#14]: Weather Information refreshed
```

Intel Celeron J4105

```
/etc/X11/xinit/xinitrc-common: line 31: xrdb: command not found
/etc/X11/xinit/xinitrc-common: line 45: xmodmap: command not found
Warning:          Could not resolve keysym XF86FullScreen
Clutter-Message: 14:54:15.264: Sync method: PRESENTATION TIME
Failed to play sound: Sound disabled
Cjs-Message: 14:54:15.675: JS LOG: About to start Cinnamon
Cjs-Message: 14:54:15.838: JS LOG: [LookingGlass/info] Cinnamon.AppSystem.get_default() started in 155 ms
Cjs-Message: 14:54:15.852: JS LOG: [LookingGlass/info] loading user theme: /usr/share/themes/Mint-Y-Dark-Aqua/cinnamon/cinnamon.css
Cjs-Message: 14:54:15.885: JS LOG: [LookingGlass/info] added icon directory: /usr/share/themes/Mint-Y-Dark-Aqua/cinnamon
** Message: 14:54:16.017: nemo-desktop: session is cinnamon, establishing proxy
Cjs-Message: 14:54:16.634: JS LOG: [LookingGlass/info] loaded at Wed May 19 2021 14:54:16 GMT+0100 (British Summer Time)
Cjs-Message: 14:54:16.634: JS LOG: Cinnamon started at Wed May 19 2021 14:54:16 GMT+0100 (British Summer Time)
Cjs-Message: 14:54:16.652: JS LOG: [LookingGlass/info] ExtensionSystem started in 1 ms
Cjs-Message: 14:54:16.653: JS LOG: [LookingGlass/info] DeskletManager started in 1 ms
Cjs-Message: 14:54:16.653: JS LOG: [LookingGlass/info] SearchProviderManager started in 1 ms
openGL version 4.6 detected (GL3 Cogl Driver)
MetaSyncRing disabled: couldn't find required GL extensions, or the minimum safe openGL version was not met
Cjs-Message: 14:54:16.888: JS LOG: [LookingGlass/info] Loaded applet show-desktop@cinnamon.org in 138 ms
Cjs-Message: 14:54:16.899: JS LOG: [LookingGlass/info] Loaded applet removable-drives@cinnamon.org in 10 ms
Cjs-Message: 14:54:16.950: JS LOG: [LookingGlass/info] Loaded applet calendar@cinnamon.org in 51 ms
Cjs-Message: 14:54:17.061: JS LOG: [LookingGlass/info] Loaded applet weather@mockturtl in 111 ms
Cjs-Message: 14:54:17.068: JS LOG: [LookingGlass/info] Role locked: tray
Cjs-Message: 14:54:17.073: JS LOG: [LookingGlass/info] Loaded applet systray@cinnamon.org in 12 ms
St-Message: 14:54:17.085: cogl npot texture sizes SUPPORTED
Cjs-Message: 14:54:17.113: JS LOG: [LookingGlass/info] Loaded applet keyboard@cinnamon.org in 39 ms
Cjs-Message: 14:54:17.135: JS LOG: [LookingGlass/info] Loaded applet xapp-status@cinnamon.org in 22 ms
Cjs-Message: 14:54:17.190: JS LOG: [LookingGlass/info] Loaded applet printers@cinnamon.org in 54 ms
Cjs-Message: 14:54:17.201: JS LOG: [LookingGlass/info] Role locked: notifications
Cjs-Message: 14:54:17.214: JS LOG: [LookingGlass/info] Loaded applet notifications@cinnamon.org in 24 ms
Cjs-Message: 14:54:17.237: JS LOG: [LookingGlass/info] Loaded applet power@cinnamon.org in 23 ms
Cjs-Message: 14:54:17.276: JS LOG: [LookingGlass/info] Role locked: panellauncher
Cjs-Message: 14:54:17.282: JS LOG: [LookingGlass/info] Loaded applet grouped-window-list@cinnamon.org in 45 ms

** (csd-power:1095): CRITICAL **: 14:54:17.310: abs_to_percentage: assertion 'max > min' failed
Cjs-Message: 14:54:17.372: JS LOG: [LookingGlass/info] Loaded applet sound@cinnamon.org in 90 ms
Cjs-Message: 14:54:17.464: JS LOG: [LookingGlass/info] Loaded applet network@cinnamon.org in 92 ms
Cjs-Message: 14:54:17.720: JS LOG: [LookingGlass/info] Loaded applet menu@cinnamon.org in 256 ms
Cjs-Message: 14:54:17.721: JS LOG: [LookingGlass/info] AppletManager started in 1085 ms
Cjs-Message: 14:54:17.727: JS LOG: [LookingGlass/info] Cinnamon took 2052 ms to start
Cjs-Message: 14:54:17.750: JS LOG: Unknown network device type, is 14
Cjs-Message: 14:54:17.764: JS LOG: Unknown network device type, is 29
Cjs-Message: 14:54:18.069: JS LOG: [LookingGlass/info] Hiding systray: network
Cjs-Message: 14:54:18.125: JS LOG: [LookingGlass/info] [weather@mockturtl#21]: Weather Information refreshed
```

**Comment by Lurux** [comment]
> I can't reproduce the issue on my 3 month old fedora-34 installations.
> 
> ```
> - snip -
> ```

You need to measure with a stopwatch - you can't trust the timing in the logs, it seems like the Cinnamon startup is actually delayed on Linux Mint.

I plan on doing a more thorough investigation soon and report back on the results.

In the meantime, I can confirm Cinnamon takes 15+ seconds to start on a fresh Mint 20.1 install. My machine has an intel core i7 (can't tell the generation right now), 16 GB of RAM, and a standard HDD.

Are you using an SSD ? The problem might be greatly lowered on these new, faster drives.

**Comment by Lurux** [comment]
@leigh123linux

**Comment by leigh123linux** [comment]
I use nvme drives on the ryzen machine and ssd on the intel machine.

```
$ inxi -D
Drives:    Local Storage: total: 3.53 TiB used: 2.09 TiB (59.1%) 
           ID-1: /dev/nvme0n1 vendor: Samsung model: MZVLW256HEHP-00000 size: 238.47 GiB 
           ID-2: /dev/nvme1n1 vendor: Crucial model: CT500P1SSD8 size: 465.76 GiB 
           ID-3: /dev/sda vendor: Western Digital model: WD30EZRX-00SPEB0 size: 2.73 TiB 
           ID-4: /dev/sdb vendor: Samsung model: SSD 830 Series size: 119.24 GiB
```

```
$ inxi -D
Drives:    Local Storage: total: 465.76 GiB used: 294.59 GiB (63.2%) 
           ID-1: /dev/sda vendor: Samsung model: SSD 850 EVO 500GB size: 465.76 GiB 
```

**Comment by Lurux** [comment]
I suspect the problem might be specific to HDDs, pretty much everything becomes instantaneous on SSDs anyways (even windows :wink:).

Once again, this issue is rather outdated so I'll do more exhaustive testing and report back on the results :slightly_smiling_face:

**Comment by Lurux** [comment]
Interestingly enough, Cinnamon takes 10 seconds to load on a crappy laptop I tested this on. This is significantly faster than the time it takes on my main machine, but is still a lot compared to other desktops I tested on this. I'll investigate more tomorrow, and will have access to my main machine after that.

**Comment by Nokia808** [comment]
@Lurux 
Hi dear. Now I'm on Fedora 34 X64 bit Cinnamon edition, & my Cinnamon version currently is 4.8.6 

To be of useful comment I like, 1st to say the following:
My system RAM before upgraded to 34 was just 8GB. At that time copy/past an archive file of 5.4BG from my laptop built-in HDD to externally connected Samsung 870 EVO SSD set in original ORICO external enclosure supporting SATA3 (5Gib/sec) connected to my built-in laptop USB 3.0 port was taking 55 seconds. After upgraded my system to Fedora 34 with I tested this process with same 8GB RAM & it was the same (55 seconds). Then I upgraded my RAM to be now 16GB. The same copy/past process now taking ONLY 14 seconds ! My laptop now very fast BUT loading time of my Cinnamon is really killer: 50 seconds (this is exclusive of booting time, this is pure Cinnamon loading time) ! So, this obsolutly that there is a big defect in Cinnamon with huge memory leak ! I was - & still - living with this killing loading time since Fedora 24, but my system needing either Cinnamon or GNOME because my laptop have no CapsLock nor NumLock LED & these only 2 DE that has indicators for those ! Certainly Cinnamon lighter than GNOME. But this loading time really killing !

My system details are:
Fedora 34 X64 bit Cinnamon edition on Lenovo ThinkPad e550 with Intel core i7 5500 CPU @ 2.40 GH X 2, RAM = 16 GB DDR3L, HHD = 1 TB (Ext4 file system format), Hybrid (Switchable) VGA: shared "Intel Corporation HD Graphic 5500" + dedicated 2 GB "Radeon R7 M265"

**Comment by Lurux** [comment]
Closing this for now as it is old and outdated, but Cinnamon's startup performance could still be improved IMO. Will report back if I ever have the time to investigate this more thoroughly.

**Comment by Nokia808** [comment]
@Lurux 
Why you closed this issue ! It is still existing & very annoying !! If issue still existing why close it !! 
I'm on Cinnamon 5.0.5 & still suffering from it ....

This is one of the most important bugs in Cinnamon. Unfortunately, my laptop CapsLock & NumLook have no LED. This what enforced me to remain sticky with Cinnamon DE. Cinnamon - other than this bug - is a great DE.  But this bug is very bad ! It should given the priority not close it !

**Comment by Lurux** [comment]
@Nokia808, the main reason I closed this is because I no longer see Cinnamon's startup slowing down over time - Cinnamon now just takes a while to load from the start, making this issue kinda outdated. Is this not the case for you ?

I also intend to open a new issue at some point with fresh and exhaustive information, which will hopefully get more visibility.

**Comment by Nokia808** [comment]
@Lurux 
I informed you: I'm still suffering from this issue !! Not only I'm, but so many peoples also ! The problem is that this issue is happening on some machines while not with others !! In all cases the hardware are safe & not defected .....
