### ISSUE TITLE
Workplace name indicator remains on screen FOREVER

### ISSUE THREAD

**Issue by dikonov** [linuxmint/cinnamon#9392]
```
 * Cinnamon version (cinnamon --version)   Cinnamon 4.6.3
 * Distribution - ALTLinux Sisyphus (rolling)
 * Graphics hardware *and* driver used   Radeon Turks (Macbook Pro 2011), radeon free
 * 64 bit
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
nothing there. 
```

**Issue**
The workplace notification that appears after switching workplaces does not go away and stays on screen FOREVER until reboot or Cinnamon session restart. It floats above other windows in the middle of the screen and makes it impossible to continue one's work. This happens independently of what applet I choose to switch workplaces.

See screenshot.
![Sticky_workplace#_message](https://user-images.githubusercontent.com/4271322/85305333-97f94f00-b4b5-11ea-909b-e74a60a1db41.jpg)

**Comment by icarter09** [comment]
Cinnamon 4.8.6
Mint 20.1 64bit

I'm not able to reproduce the issue. @dikonov are you still experiencing this? Thanks.
