### ISSUE TITLE
Sound applet does not show album cover with Spotify

### ISSUE THREAD

**Issue by walamana** [linuxmint/cinnamon#9394]
```
 * Cinnamon 4.4.8
 * Distribution - Ubuntu 20.04
 * GTX 960 - nvidia-driver-440
 * 64 bit
 ```

**Issue**

The sound applet does not show the album cover, when Spotify is running. Instead it shows the default optical disc icon.

**Steps to reproduce**
- Create a new panel
- Add the sound applet
- Play a track in Spotify (tested in v1.1.26.501)
- The album cover is not shown when opening the applet

**Expected behaviour**

Spotify seems to provide an invalid cover url (starting with open.spotify.com), which seems they have  removed. Instead the applet should replace "open.spotify.com" with "i.scdn.co" and not replace "image" or "thumb" in the url with anything. The name is now capitalized.
I tried this with a copy of the preinstalled applet and replaced this in the _setMetadata function and it showed the correct album cover: 
```javascript
if ( this._name === "Spotify") {
    artUrl = artUrl.replace("open.spotify.com", "i.scdn.co") // 1.1.26.501
}
```

**Comment by Saphieron** [comment]
Have a similar behaviour with 
- Cinnamon: 4.6.6
- Spotify: 1.1.10.546.ge08ef575
- Linux Mint 20

Neither the icon in the panel nor the image in the opened sound applet shows the current album cover.

**Comment by DanforthPennyrose** [comment]
Can confirm as well. Cover icon of the sound applet, disc image when applet is expanded and album art on lock screen all disappeared (around January).

- OS: Linux Mint 19.3 Cinnamon

- Cinnamon version: 4.4.8

- Kernel version: 5.3.0-53-generic x86_64

- Spotify version: 1.1.10.546.ge08ef575

**Comment by klutzer** [comment]
Confirmed the same behaviour in Linux Mint 20 Cinnamon.

- Cinnamon version: 4.6.7
- Kernel version: 5.4.0-52-generic
- Spotify version: 1.1.42.622.gbd112320
