### ISSUE TITLE
ACPI BIOS Error and Blank Driver Manager after installing Nvidia drivers

### ISSUE THREAD

**Issue by Numnumberry** [linuxmint/cinnamon#9403]
* Linux Mint 20 Cinnamon
 * GeForce GTX 960

**Issue**
After a fresh install then installing nvidia-driver-440, any additional boot afterward will give an error "ACPI BIOS Error (bug): Could not resolve symbol [...], AE_NOT_FOUND (...)" and then finish booting after a second or two. After changing back to xserver-xorg-video-nouveau and restarting, trying to open driver manager will result in no options being displayed in the window. To revert the issue, "sudo apt-get purge nvidia*" can be ran.

**Steps to reproduce**
1) Install linux mint 20, note how on first boot (and any afterward) there is no ACPI BIOS errors
2) Go into driver manager and switch to nvidia-driver-440 and restart, note the ACPI BIOS errors
3) Go into driver manager and switch back to xserver-xorg-video-nouveau and restart, note the ACPI errors are still present
4) Go into driver manager and note how no options are displayed
5) Run "sudo apt-get purge nvidia*" and restart
6) Note the ACPI BIOS errors are now gone
7) Go into driver manager and note that everything is set back to default

**Expected behaviour**
1) Installing nvidia-driver-440 causes no errors
2) Switching back to the default driver does not cause the driver manager to be blank

**Other information**
Motherboard: Asrock Z370M Pro4
This was also reproduced on a Huawei Matebook X Pro 2018

**Comment by leigh123linux** [comment]
This is either a bios bug or a nvidia issue, try reporting it to nvidia.

https://forums.developer.nvidia.com/c/gpu-unix-graphics/linux/148
