### ISSUE TITLE
Certain apps, like Firefox and Calculator, have a dead zone for window border buttons (minimize, maximize, close), especially when window is maximized

### ISSUE THREAD

**Issue by pansailor** [linuxmint/cinnamon#9406]
```
Cinnamon - v4.4.8 (not using PPA)
Distribution - Mint 19.3
Graphics - Intel Corporation Skylake GT2 [HD Graphics 520], driver i915
64 bit

 ```

**Issue**

When using a maximized Firefox window without a title bar, you cannot click the 'close' button by bringing your mouse all the way to the top-right corner.

This makes it difficult to quickly close the window with a mouse, as you have to aim for the 'close' button (as well as the 'minimize' or 'maximize' buttons) if you want to click it.

Instead, the very top-right corner of the screen has a dead space, where clicking does nothing.

This is inconsistent with how easy it is to click tabs (when using tabs-on-top) by bringing your mouse up to the very top of the screen.

**Steps to reproduce**

- Open Firefox
- Customize menu > deselect Title Bar
- Move mouse to top-right corner
- Cannot click close button

**Expected behaviour**

Moving the mouse to the top-right corner should bring your mouse right on top of the 'close' button. Additionally, keeping your mouse at the top of the screen, and then moving in line with the 'maximize' and 'minimize' buttons, should allow you to click them.

**Comment by JosephMcc** [comment]
Cinnamon has no control over this. In the applications you are talking about those elements are controlled by the application.
