### ISSUE TITLE
Allow GUI manipulation of panel/menu font-family

### ISSUE THREAD

**Issue by AKushWarrior** [linuxmint/cinnamon#9413]
I'm on Cinnamon 4.4.8, with Ubuntu as the underlying distro. This is a feature request, so it (shouldn't) matter.

Essentially, I would like the ability to easily manipulate the font-family inside of the panels/menu. Currently, the only way to do this is hacky (manipulate the theme settings manually), and painful for every tiny edit. It would be great if:
 a) the panels/menu inherited from the global font settings by default
 b) panels/menu font were configurable through the panel settings

These behaviors seem more user-friendly than silently assigning a random font and then letting users hack around to get the desired behavior.

**Comment by smurphos** [comment]
Hi - this feature was implemented with Cinnamon 4.6.x

**Comment by AKushWarrior** [comment]
That... would explain why I don't have it.

Is this version of cinnamon available through apt?

**Comment by AKushWarrior** [comment]
Just checked; it definitely isn't. Apt says that the latest version is 4.4.8-4, and I have cinnamon installed through apt. Is there a better way to install it?

**Comment by AKushWarrior** [comment]
(I closed because my questions are irrelevant to the original topic. If anyone could spare some guidance as to my last two comments, it would be greatly appreciated!)

**Comment by smurphos** [comment]
Hi, unfortunately as far as i know there isn't a PPA currently offering stable Cinnamon to Focal Users. If you want the latest Cinnamon then your choices are Mint, or a rolling release distro - e.g. Arch or Manjaro, build yourself, or experiment with adding some Mint repositories to your software sources.  If you are using the Ubuntu Cinnamon Remix then perhaps suggest to the dev team that they ought to consider back-porting Cinnamon 4.6.

**Comment by AKushWarrior** [comment]
Ah. Given that this is my work computer, I probably shouldn't mess around with non-PPA, as much as I want to. 

I'll file some issues with PPAs. With any luck, an update will come within a month or so. Cheers, and thanks for the help.
