### ISSUE TITLE
Cinnamon crashes whenever I switch to NVIDIA On-Demand mode with prime applet

### ISSUE THREAD

**Issue by fabiomargarido** [linuxmint/cinnamon#9420]
```
 * Cinnamon version (cinnamon --version): 4.6.6
   - Please specify if you are using the daily builds PPA: no
 * Distribution - Mint 20
 * Graphics hardware *and* driver used: GeForce GT 630M with proprietary driver v390
 * 64 bit
 ```

**Issue**
Whenever I switch to NVIDIA On-Demand mode with prime applet, Cinnamon crashes instantly on restart. Both Intel and NVIDIA modes work fine.

**Steps to reproduce**
Click NVIDIA prime applet, choose "Switch to: NVIDIA On-Demand", logout and log back in.

**Expected behaviour**
Cinnamon should load correctly running on Intel hardware and then present an option to run with NVIDIA on right-click.

Crash report: https://termbin.com/7gs0
Local files: [crash.tar.gz](https://github.com/linuxmint/cinnamon/files/4857867/crash.tar.gz)

**Comment by firewiremb** [comment]
Same Problem here:

Crash report: https://termbin.com/fdmo
Local files: [crash.tar.gz](https://github.com/linuxmint/cinnamon/files/4904406/crash.tar.gz)

**Comment by igorVinicius** [comment]
The same here. First upgraded from Mint 19.3. I also tried the clean install, but it is still crashing.

**Comment by mtwebster** [comment]
Unfortunately the minimum driver for on-demand support is 435.17.  We're adding a version check to disable this.
https://github.com/linuxmint/nvidia-prime-applet/commit/e9af2c9bca0f948c9ebe31a427e860a4b5697b23
