### ISSUE TITLE
Feature Request: Add a shortcut for opening system monitor in the CTRL-ALT-DELETE dialogue box.

### ISSUE THREAD

**Issue by rtevans01** [linuxmint/cinnamon#9423]
This is the [window](https://imgur.com/vGoVKC4) I'm talking about. If a shortcut was added for opening the Gnome system monitor, I think it would be a good addition to the other buttons.

The feedback I've received about this idea from other Mint users is it would make Mint look too much like Windows. IMHO, yes this would be true, but we shouldn't strive to be separatists if that is the case. Yes I know it's possible to add a separate key binding for opening the system monitor but I think it makes sense to have a shortcut button since it would be convenient(why not?) and **intuitive** for new users coming from Windows.

**Comment by leigh123linux** [comment]
I'm -1 for this change.

**Comment by sallywoog** [comment]
You can do it yourself with Keyboard shortcut settings

CTRL+SHIFT+ESC if you really want

**Comment by caelwithcats** [comment]
I created a ctrl alt del menu application: https://github.com/caelwithcats/ctrl-alt-del-cinnamon. You will need to add it to the shortcuts

**Comment by HenryJk** [comment]
System Monitor is by default ctrl+alt+esc on windows. If you want it you can easily create your own shortcut on cinnamon settings. Pretty sure the reason this isn't enabled by default is because cinnamon desktop doesn't always come with gnome-system-monitor. Arch for example, don't have it installed by default.

**Comment by sallywoog** [comment]
> System Monitor is by default ctrl+alt+esc on windows. If you want it you can easily create your own shortcut on cinnamon settings. Pretty sure the reason this isn't enabled by default is because cinnamon desktop doesn't always come with gnome-system-monitor. Arch for example, don't have it installed by default.

CTRL+SHIFT+ESC

**Comment by HenryJk** [comment]
> > System Monitor is by default ctrl+alt+esc on windows. If you want it you can easily create your own shortcut on cinnamon settings. Pretty sure the reason this isn't enabled by default is because cinnamon desktop doesn't always come with gnome-system-monitor. Arch for example, don't have it installed by default.
> 
> CTRL+SHIFT+ESC
> 
> easy remembered as it's the "vertical" vulkan pinch on the left side of the Keyboard or your hand looks like the OK sign or rabbit sign

Yea, sleepy brain talking, I even have it setup as ctrl+shift+esc on my cinnamon desktop, but mistake were made.

**Comment by caelwithcats** [comment]
I do not know why everyone hates this idea, Ctrl+alt+delete is one of the most useful shortcuts when a program is freezing your computer. +1

**Comment by leigh123linux** [comment]
> I do not know why everyone hates this idea, Ctrl+alt+delete is one of the most useful shortcuts when a program is freezing your computer. +1

Linux user lives matter more!

**Comment by sallywoog** [comment]
> > I do not know why everyone hates this idea, Ctrl+alt+delete is one of the most useful shortcuts when a program is freezing your computer. +1
> 
> Linux users matter more!

Linux Lives Matter

**Comment by HenryJk** [comment]
> I do not know why everyone hates this idea, Ctrl+alt+delete is one of the most useful shortcuts when a program is freezing your computer. +1

I mean there is no one stopping you from changing it yourself in the shortcut menu. This is not windows, you don't like something you change it.

**Comment by rtevans01** [comment]
As I said in my OP, I know you can make a shortcut to open the system monitor and I agree it's not exactly related to the other buttons. I just think it would be simpler and more intuitive(coming from Windows) to have it under CTRL-ALT-DELETE.

My current shortcut is CTRL-ALT-X and I'm not sure if this is by default or if this was transferred from my previous installation since I remember inputting that key combination as a shortcut. CTRL+SHFT+ESC kind of strains the hand a bit IMHO.

If a different distro uses Cinnamon and it doesn't have Gnome System Monitor installed by default, I think it would be their responsibility to either get rid of the shortcut or have a system monitor installed by default.

**Comment by sallywoog** [comment]
"and I agree it's not exactly related to the other buttons" and that's why NO

**Comment by JosephMcc** [comment]
I'm closing this. We always keep these ideas in mind but the system monitor isn't a part of Cinnamon and a user or distro could include any one they wanted or not include one at all.
