### ISSUE TITLE
Feature Request: Workspace switcher window icons.

### ISSUE THREAD

**Issue by nervecenter** [linuxmint/cinnamon#9425]
Commonly seen in workspace switchers under various desktops, including XFCE, KDE, etc. Makes the switcher wonderfully readable at a glance. Not sure how much more detail I can provide given how commonplace of a feature it is. I'd simply ask that the icons are either configurable, or that the chosen defaults make them decently large, even when the window is sized strangely, such as a thin, tall portrait orientation.

**Comment by xenopeek** [comment]
Duplicate of #7320
