### ISSUE TITLE
Feature Request: Workspace switcher draggable windows.

### ISSUE THREAD

**Issue by nervecenter** [linuxmint/cinnamon#9426]
Commonly seen in workspace switchers under various desktops, including XFCE, KDE, etc. Can reduce or even eliminate the need for taking extra steps to use Expo. Like my other request, I'm not sure how much more detail I can provide given how commonplace of a feature it is. Even some tiny third-party GNOME workspace switchers implement it, amazingly.

**Comment by xenopeek** [comment]
This is tied to a possible future implementation of #7320.
