### ISSUE TITLE
Cinnamon startup application doesn't honour desktop file "Path" clause in .desktop files

### ISSUE THREAD

**Issue by 3-14152898** [linuxmint/cinnamon#9427]
Using cinnamon 4.4.8+debbie on LMDE 4 (Debbie), 64 bits, no PPA. Graphics hardware not relevant.

**Issue**

The "Path" clause in .desktop files used by the "Startup applications" tool is not honoured, which has been confirmed by at least one person on Linux Mint forums (https://forums.linuxmint.com/viewtopic.php?p=1827933#p1827933). In case the application doesn't run or exits with an error message, the error message is nowhere to be found in any log (.xsessionerrors, user log or system log).

**Steps to reproduce**

* Add any application to the Startup list (binary application path irrelevant whether relative or absolute)
* Manually edit the file to add a "Path=" key to the file to change the startup location
* Restart

**Expected behaviour**

The application should run from the given location *or* log any error.

**Other information**

The attempt was centred on running conky with a configuration path relative to the current process directory (which should have been set from the desktop file's "Path=" key). No trace of any error message could be found in .xsessionerrors, user log and system log, which resulted in hours wasted in troubleshooting — not that I bother that much but it's frustrating to not know where to start just because logs are empty...

**Comment by xenopeek** [comment]
This is reproducible with Cinnamon 4.6.6 on Linux Mint 20.

What I did was create a file `test.sh` in ~/Documents with this in it:
```
#!/bin/bash
zenity --info --title "Test" --text "$PWD"
```
Made the file executable and then added it through Startup Applications with a few seconds startup delay. Then I edited the created .desktop file in ~/.config/autostart and inserted a line `Path=/tmp`.

Logging out and back in the zenity dialog pops up showing "/home/username" and not "/tmp" as it should have.
