### ISSUE TITLE
Swapping Muffin with i3-wm

### ISSUE THREAD

**Issue by RafaelSundorf** [linuxmint/cinnamon#9428]
```
 * Cinnamon version (cinnamon --version) -> 4.4.8
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) -> Linux Mint 19.3 Tricia
 * Graphics hardware *and* driver used -> Intel HD Graphics 620
 * 32 or 64 bit -> 64 bit
 ```

**Issue**

I've already searched through the internet but I couldn't find any way which is still applicable to swap out muffin with i3-wm, is there still a way to do this without recompiling cinnamon to use a different window manager? It would be great if it would be easy but that's maybe just wish thinking.

Thanks for your Time

**Comment by JosephMcc** [comment]
Sorry but no. Cinnamon is a plugin for muffin and can't work without it.
