### ISSUE TITLE
[Feature request] Allow users to move windows across multiple monitors by using keyboard shortcut

### ISSUE THREAD

**Issue by mendel5** [linuxmint/cinnamon#9431]
**Problem**
Many operating systems support a feature where by pressing the keys `Windows` + `arrow key` the user is able to move a window to a certain position within the monitor (e.g. right half, top left corner, etc.). This feature is already supported by Linux Mint 20 Cinnamon.

However in Windows 10 it is also possible to move a window from one monitor to another monitor when using this shortcut on a multi monitor setup. Unfortunately this feature is not supported in Linux Mint 20 Cinnamon.

**Description**
Assume that I have two monitors, a left one and a right one. The window is on the right half of the left monitor. When I press the keys `Windows` + `arrow right` I want the window to go from the right half of the left monitor to the left half of the right monitor.

Here is a video where it is shown on Windows 10: https://www.youtube.com/watch?v=HBkUG3OLbtw&t=124

**Solution**
It would be nice if it was possible on Linux Mint to move a window from the right half of the left monitor to the left half of the right monitor when using a multi monitor setup by pressing `Windows` + `arrow right` (and other directions as well).

**Comment by xenopeek** [comment]
Cinnamon 4.6 supports this. Configure the keyboard shortcuts as you want:

![image](https://user-images.githubusercontent.com/21159972/86528708-e392fc00-beaa-11ea-9d6c-6e7d3eb3c173.png)

**Comment by mendel5** [comment]
@xenopeek Thanks for the quick reply, I will try this!
