### ISSUE TITLE
Clutter.Actor filling .xsession-errors with deallocation errors

### ISSUE THREAD

**Issue by bonesmoses** [linuxmint/cinnamon#9432]
```
 * Cinnamon version: 4.6.6
 * Distribution: Mint 20
 * Graphics hardware: nVidia 980ti using nvidia-driver-440
 * 64 bit
 * Cannot attach `.xsession-errors`, as it is 100MB and growing
 ```

**Issue**

The `.xsession-errors` file appears to be rapidly accumulating errors such as the following:

```
(cinnamon:1970): Cjs-CRITICAL **: 17:26:09.983: Object Clutter.Actor (0x556af8783bb0), has been already deallocated - impossible to access to it. This might be caused by the fact that the object has been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs
== Stack trace for context 0x556af7091010 ==
#0 0x556af7364df8 i   /usr/share/cinnamon/js/misc/fileUtils.js line 210 > Function:110 (0x7ff0977021a8 @ 697)
#1 0x556af7364d28 i   self-hosted:251 (0x7ff1040bd9a0 @ 223)
#2 0x556af7364c90 i   /usr/share/cinnamon/js/misc/fileUtils.js line 210 > Function:75 (0x7ff0978a2890 @ 70)
#3 0x556af7364be0 i   /usr/share/cinnamon/js/misc/fileUtils.js line 210 > Function:63 (0x7ff0978a26f8 @ 37)
#4 0x556af7364b20 i   self-hosted:914 (0x7ff1040e6670 @ 346)
```

This happens infinitely. At the time of this bug report, the log has reached 134k of these errors since it started. Date unknown, as the `.xsession-errors` log does not contain date information.

It appears the code path here is not properly catching this exception in order to understand the deallocation has already occurred, and to adjust associated reference counts to avoid issuing the same call.

**Steps to reproduce**

It is unknown how the system reached this state.

**Expected behaviour**

No errors flooding the log.

**Comment by mtwebster** [comment]
Can you provide your full .xsession-errors up to the point it begins repeating itself with these warnings?

**Comment by bonesmoses** [comment]
I should have copied the file I had. Rebooting fixed it, and it hasn't recurred since then.

The only error after that was:

```
Cinnamon warning: Log level 128: posix_spawn avoided (fd close requested) (child_setup specified) 
```

But I got rid of the CPU desklet and that went away too.
