### ISSUE TITLE
Context menu for popmenu child

### ISSUE THREAD

**Issue by PierrePharel** [linuxmint/cinnamon#9433]

**Comment by kameshkotwani** [comment]
You're supposed to tell here something.

**Comment by PierrePharel** [comment]
I thought the title spoke for itself, but ok. Then, is it possible that the popupMenu items have a context menu (dev applet) ?

**Comment by xenopeek** [comment]
popupMenu can have submenus but not context menus. See the Cinnamon Javascript Reference Manual section in devhelp (install package cinnamon-doc).
