### ISSUE TITLE
Datum: fractional scaling on Lenovo ThinkPad X1 Carbon 6th generation works (too) poorly

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/cinnamon#9441]
```
 * Cinnamon version (cinnamon --version) 4.6.6
   - Please specify if you are using the daily builds PPA: I am not.
     (https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds).
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 20
 * Graphics hardware *and* driver used: Intel UHD Graphics 620; Mesa 4.6.
 * 32 or 64 bit: 64.
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
[xsession-errors.txt](https://github.com/linuxmint/cinnamon/files/4901090/xsession-errors.txt)
 ```

**Issue**

I tried 175% and 149% (_sic_). The latter would have transformed how I can use this computer - it made things a really good size. But using either of those fractional scaling settings made the scrolling in many applications, e.g. SublimeText and, especially, Firefox, unusuably stuttery - slow and with a marked, nasty, visual effect.

**Steps to reproduce**

1. Have a Lenovo ThinkPad X1 Carbon 6th Generation ('X1CG6').
2. Enable Hi-DPI.
3. Enable first the one and then the other of the fractional scaling values I mentioned above, testing scrolling.

**Expected behaviour**

Usuable scrolling on a fractional setting that allows me to use my high-resolution display as if it were not a low-resolution display (!).

**Other information**

Screen resolution: 2560x1440 (@ 60.01Hz).
Screen size (its diagonal): 14 inches.

I realise that the problem may be upstream from you.

**Comment by paravz** [comment]
Fractional scaling of 150% on a 4K monitor is very noticeably laggy and unusable for me, looks similar to this report.

I have reverted to Double(HiDPI) User Interface Scale and reduced "Fonts Settings > Text scaling factor" to 0.9

HW: Intel Corporation UHD Graphics 630 (Mobile) (i915)
OS: Fedora 32, Cinnamon 4.6.5

**Comment by LinuxOnTheDesktop** [comment]
The changelog for a recent update - I have, now, Cinnamon 4.6.7 - seemed set to offer more sensible scaling percentages. Yet, the list of available scales that I see continues to read: 200%; 175%; _149_% (1712 x 963); 125%; 100%; _74_%.

**Comment by JosephMcc** [comment]
This is unfortunately a current limitation of how this works. Some people it seems to work ok for but on some hardware it doesn't. The performance is terrible for me on my own machines but I don't think under x11 there is another option currently.
