### ISSUE TITLE
Desktop icon freeze 

### ISSUE THREAD

**Issue by zacharias25** [linuxmint/cinnamon#9446]
```
 * XFCE version 
   
 * Distribution - Linux mint 20
 Device-1: Intel 3rd Gen Core processor Graphics vendor: Lenovo driver: i915 v: kernel 
           bus ID: 00:02.0 chip ID: 8086:0166 
           Display: x11 server: X.Org 1.20.8 driver: modesetting unloaded: fbdev,vesa 
           resolution: 1366x768~60Hz 
           OpenGL: renderer: Mesa DRI Intel HD Graphics 4000 (IVB GT2) v: 4.2 Mesa 20.0.8 
           compat-v: 3.0 direct render: Yes 
 ```

**Issue**

Desktop icon freeze for a moment of time

**Steps to reproduce**
For example, you have to right click the mouse but no response even you do it for many times and freezes for a moment before it respond and back to normal

**Expected behaviour**
Behavior not always but during cut/copy/paste a file.

**Other information**

**Configuration info, if applicable**
If this bug report is related to an Applet, Desklet or Extension, please paste (or use a pastebin service) the offending extension's settings, if it has any.  You can obtain this by opening its configuration, clicking the 'hamburger' button in the upper-right corner of the window, and selecting "Export to a file". **Please be sure to review the contents and remove any personal data it may contain.**

```

Please paste here

```

**Comment by leigh123linux** [comment]
cinnamon doesn't draw desktop icons, nemo does that for cinnamon.
As you provide no useful info other than you running xfce I'm closing this misfiled issue.
