### ISSUE TITLE
Blank icon for "Disks" (gnome-disks) in "System Settings".

### ISSUE THREAD

**Issue by DorianB2017** [linuxmint/cinnamon#9449]
```
 * Cinnamon version (cinnamon --version) - 4.6.6
   - Please specify if you are using the daily builds PPA - No
     (https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds).
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) - Mint 20.0
 * Graphics hardware *and* driver used
 * 32 or 64 bit - 64 bit
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
 ```

**Issue**
After upgrading from Linux Mint v.19.3 to Linux Mint v.20.0, an empty/a blank icon for "Disks" (gnome-disks) appears in "System Settings" (for all icon themes - Adwaita, Gnome-* , Hicolor, Numix* , etc., except the Mint-X* and Mint-Y* themes).
Please fix this bug, too.

For exemple:
- the Gnome/Gnome-colors-common icon theme:
![Captură de ecran din 2020-07-12 21-56-39a](https://user-images.githubusercontent.com/30018486/87254428-46782a80-c48b-11ea-8c75-fe30768ec8c4.png)

- the Numix theme:
![Captură de ecran din 2020-07-12 22-03-24](https://user-images.githubusercontent.com/30018486/87254502-db7b2380-c48b-11ea-8041-656c05597ae3.png)

**Comment by xenopeek** [comment]
I can reproduce that. Switched icon theme to Adwaita and Disks doesn't show its icon in System Settings but it does have an icon in the menu and on the panel when running.

**Comment by Odyseus** [comment]
Hello, everybody.

The icon used there is called "gnome-disks" (it was changed several monthds ago by 40a33842f2d820c11657bcb3a610601abe77a8ec). The commit message reads:

> The "disks" name doesn't exist in all themes, whereas gnome-disks is
> supported in Mint-X, Mint-Y and in hicolor for any other theme that
> doesn't have their own.

The problem seems to be that the hicolor icon theme doesn't ship that icon anymore.

Ping @mtwebster.
