### ISSUE TITLE
Wrong power values for mouse in cinnamon taskbar

### ISSUE THREAD

**Issue by DamianMalik** [linuxmint/cinnamon#9453]
```
 * Cinnamon version 4.4.8
 * Distribution - Mint 19.3 
 * 64 bit
 ```
![Bildschirmfoto vom 2020-07-13 21-10-47](https://user-images.githubusercontent.com/31533791/87345830-f6639b80-c550-11ea-9de9-a49fd8a8645f.png)

**Issue**
Cinnamon Taskbar shows wrong energy values for Logitech Performance MX Mouse. 
While Power Management window shows correct values (mouse nearly full loaded), taskbar indicates only 10% energy for mouse. But mouse is completely full loaded. 

**Expected behaviour**
Same values in taskbar and in energy menu.

```

**Comment by mtwebster** [comment]
Hi, mice and other peripherals usually don't report the proper percentage of their battery.  Instead they report things like 'battery good' or 'full'.  For instance my mouse always shows 55% for some reason. This was addressed in some recent changes:
https://github.com/linuxmint/cinnamon/commit/0fb3ed79a3270a96483a62b404935d354eab01b1
https://github.com/linuxmint/cinnamon/commit/63d68255bec1eed949ac43629805c640b1d2bdce
https://github.com/linuxmint/cinnamon/commit/f739133cce690413d80a34f298a04f173a35f3bb

The icon will no longer be in the mouse battery row, it will only say 'battery good'. These types of devices will no longer display on the panel at all (although they will still show up in the popup menu if there are other devices for it to display on the panel).

I believe the first change is in the current 4.8 cinnamon release.
