### ISSUE TITLE
restore indicator support 

### ISSUE THREAD

**Issue by brainchild0** [linuxmint/cinnamon#9455]
From a [posting in the Mint Forums](https://forums.linuxmint.com/viewtopic.php?p=1835348), I learned that indicator support has been  withdrawn unannounced (commit eb7f2235debcd3baf36d2d94a23465158b8bdafc).

Indicators provided an alternative to status notifications, offering  a clean, uniform, and unintrusive presentation. Although I had always felt that some of their limitations were too extreme, I would have preferred to see them improved, or even kept the same, rather than abandoned.

Support for indicators was [announced as a new feature in  Mint 17.3 (Rosa)](https://www.linuxmint.com/rel_rosa_cinnamon_whatsnew.php). It seems strange and unfortunate to find them removed.

**Comment by mtwebster** [comment]
It was removed from Cinnamon because it was added to the XApp status applet instead, starting with https://github.com/linuxmint/xapps/commit/0a27c6a333f8aed1c9f514566751c85252f42df3.

It was noted here: https://www.linuxmint.com/rel_ulyana_cinnamon_whatsnew.php under XApp Improvements.

**Comment by brainchild0** [comment]
The only part of the referenced section that is plausibly related to notifiers and indicators reads as follows:

> To guarantee better support for modern Electron apps and indicators XappStatusIcon received mouse wheel support and SNI (StatusNotifier, libIndicator) support.

Aside from confusion about the comment directing attention specifically to Electron applications, it leaves me with little or no practical information about the removal of the particular option from *System Settings*, or whether or how I may recover use of indicators on the desktop.
