### ISSUE TITLE
Ability to replace window manager

### ISSUE THREAD

**Issue by sallywoog** [linuxmint/cinnamon#9456]
Ability to replace window manager

I want to be able to replace Muffin with another window manager

**Comment by mtwebster** [comment]
This is not possible, muffin is used only as a library by cinnamon - they're functionally a single entity.  You'd have to use a more traditional desktop like mate or xfce to have this capability.

**Comment by sallywoog** [comment]
Isn't modularity and replacability a desirable design feature of Linux/Unix?

**Comment by leigh123linux** [comment]
> I read others also want to use other window managers, they cannot because of this bad design decision imo of Cinnamon

We inherited the design from gnome-shell/mutter and it isn't going to change.
