### ISSUE TITLE
KeePassXC installed from PPA shows blank status icon (using Cinnamon)

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/cinnamon#9459]
```
 * Cinnamon version (cinnamon --version) Cinnamon 
   - Please specify if you are using the daily builds PPA: no
     (https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds).
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 20
 * Graphics hardware *and* driver used: Intel UHD Graphics 620; Mesa 20.0.8
 * 32 or 64 bit: 64
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
[xsession-errors.txt](https://github.com/linuxmint/cinnamon/files/4922817/xsession-errors.txt)

I attach my xsession-errors. It has stuff about the icon in question in it.
 ```

**Issue**

Recently the icon for the latest version of KeePassXC (2.6.0, installed via Focal PPA) was appearing as a tiny blank slither. Now, after removing my systtray and - with some diffculty - re-adding it to a panel, I see a space of the right size but with no icon in it. Clicking the space where the image should be opens KeePassXC. Changing themes and icon scaling settings did not help.

**Steps to reproduce**

Uncertain but try just installing the version of KeePassXC at issue and using its settings to tell it to show a tray icon.

**Expected behaviour**

A visible icon of the right size.

**Other information**

Compare [this old Mint issue](https://github.com/linuxmint/cinnamon/issues/5932).
See [this old KeePassXC bug report ](https://github.com/keepassxreboot/keepassxc/issues/467)- which blames Cinnamon.
See also [this recent KeePassXC bug report](https://github.com/keepassxreboot/keepassxc/issues/4963), which blames QT for what is at least apparently a different icon problem.

The Looking Glass log seems to show nothing relevant.

**Comment by LinuxOnTheDesktop** [comment]
I seem to have fixed this - by, possibly, removing an old launcher from MintMenu. Still, I do not think Mint should allow the problem to occur in the first place.

**Comment by xenopeek** [comment]
On Linux Mint 20 I can't reproduce this. Can you reproduce this issue? (e.g. uninstall keepassxc, disable the PPA, install it anew, test icons, enable the PPA again, upgrade, test icons again) If so can you add some screenshot or screencast (peek is handy program for that) to show the issue, that's always useful for graphical issues. Can you also reproduce it without Cinnamon daily build?

I installed keepassxc 2.4 from the official repository first, toggled "show a system tray icon" in settings and after pressing OK the icon shows up. Added the PPA and upgraded to 2.6 and after restarting keepassxc it uses all the new icons as far as I can see.

I don't think this is related to the old Mint issue (was about 4x icon size) or to the old KeePassXC bug report (twas about MATE) or the recent KeePassC bug report (was about missing icons in the program's UI).

Screenshots below showing all icons working in both versions. The variable here could be what themes you are using? I tested with default Mint-Y for window borders/icons/controls and Mint-Y-Dark for desktop.

With 2.4:
![image](https://user-images.githubusercontent.com/21159972/87516957-7c313500-c67e-11ea-8a67-f03c2860b891.png)

With 2.6:
![image](https://user-images.githubusercontent.com/21159972/87516973-85ba9d00-c67e-11ea-8e4c-d3ba8d491b4d.png)

**Comment by LinuxOnTheDesktop** [comment]
I have changed the title of this report so as to remove its mention of daily builds. For as I mentioned in my first post I am not using those builds.

Themes: when I had the problem I tried multiple stock themes including Mint-X and Mint-Y and Mint-Y-Dark and one non-stock theme and I still had the problem. Admittedly though the themes that I varied were all icon themes.

I appreciate your work greatly xenopeek. Yet, having somehow got the icon working properly again, I am loathe to mess with it. I could try to reproduce the problem in a VM. Certainly I will do that if I encounter the problem again. I notice already though the following. On one computer that has never had the problem all is perfect with the KeePassXP icon. Yet on the computer that had the problem there is still something odd about the icon, namely, it is has too little space to its left and right.

**Comment by xenopeek** [comment]
> I have changed the title of this report so as to remove its mention of daily builds. For as I mentioned in my first post I am not using those builds.

Apologies, I read it wrong.

I understand your reluctance to try and break something that now works.

**Comment by abashmakov** [comment]
Hello.

I can reproduce this behaviour if keepassxc's options "Minimize window after unlocking database" and "Hide window to system tray when minimized" are checked (they are in "General"). You need to lock and unlock the database. When icon disappears I have this in ~/.xsession-errors:

** (xapp-sn-watcher:39535): WARNING **: 23:00:00.566: No pixmaps to use

![2020-08-02_23-10](https://user-images.githubusercontent.com/46067602/89131445-845df100-d515-11ea-8fcb-a1eb46431c0b.png)

The workaround with icon disappearance is to uncheck "Hide window to system tray when minimized" and icon appears immediately after applying settings.

The other option ("Minimize window after unlocking database") is responsible for very slow unlocking database: around 15-20 seconds.

I am on LM20 at the moment, but I've observed such behaviour in cinnamon in archlinux.

I have both these issues only in Cinnamon. In XFCE keepassxc works without issues.

**Comment by LinuxOnTheDesktop** [comment]
@abashmakov 
Do you still have the problem? With KeePassXC 2.6.1, and Cinnamon 4.6.7, I myself no longer do. If you still do, the bug - which I (as the opener) am now closing - should be re-opened.
