### ISSUE TITLE
System Info: privacy and speed problem

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/cinnamon#9460]
```
 * cinnamon-control-center version: 4.6.1
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...): Mint 20
 * Graphics hardware *and* driver used: irrelevant
 * 32 or 64 bit: irrelevant
 ```

**Issue**

When you tell the System Info program to upload the info it uploads lots more than it shows in its window and the generation and/or uploading is slow.

**Steps to reproduce**

Open the System Info program (via Settings).
See a small amount of data.
Click 'Upload system information' (though you don't know where it will upload to).
Wait.
See that you have posed some seventy lines of data - as against the six you see in the window - to a website that you may never have heard of.

**Expected behaviour**

The user should know what they are uploading and to where. And if the upload will take a while the user should be given some indication of that.

**Other information**

I tried to look up the System Info tool in the user guide for Mint 20 but I could not find the guide.

I see though that 'termbin' deletes posts after a month. That is something. I could not see how to delete a post immediately, though.

**Comment by leigh123linux** [comment]
I think your being petty filing this issue.
The upload uses inxi which provides much more info than the cinnamon-settings info

https://github.com/linuxmint/xapps/blob/master/scripts/upload-system-info

As for providing info to where it's uploaded depends on the distro used, cinnamon has no way to know this on many distros.

https://github.com/linuxmint/xapps/blob/master/scripts/pastebin

The data is anonymized so I don't see the issue.

https://paste.centos.org/view/170861d7

**Comment by smerdysmerdy** [comment]
Does it offer a preview on what it uploads? If not, it should, full disclosure
