### ISSUE TITLE
Cinnamon crash : DBus connection lost

### ISSUE THREAD

**Issue by Swaphelaer** [linuxmint/cinnamon#9461]
Running Linux Mint 20 (upgraded from 19.3)
Both my host and virtualbox-run version crash after several hours.
Left Melange open to see what happens.
I only get this line :

warning t=1970-01-01T01:00:00Z ================ DBus connection lost ===============

Cinnamon asks to restart (running in fallback) and everything chugs along for hours.

Relevant line from syslog::system :
 
traps: cinnamon[2311] trap int3 ip:7f7afd4720d5 sp:7ffc218e9a20 error:0 in libglib-2.0.so.0.6400.3[7f7afd436000+84000]

Systemd-coredump :

Process 2311 (cinnamon) of user 1000 dumped core.

Stack trace of thread 2311:
#0  0x00007f7afd4720d5 n/a (libglib-2.0.so.0 + 0x580d5)
linuxmint/cinnamon-desktop#1  0x00007f7afd473159 g_log_default_handler (libglib-2.0.so.0 + 0x59159)
linuxmint/cinnamon-desktop#2  0x00007f7afd47339c g_logv (libglib-2.0.so.0 + 0x5939c)
linuxmint/cinnamon-desktop#3  0x00007f7afd473583 g_log (libglib-2.0.so.0 + 0x59583)
linuxmint/cinnamon-desktop#4  0x00007f7afd13bba7 wrapped_gobj_toggle_notify (libcjs.so.0 + 0x46ba7)
linuxmint/cinnamon-desktop#5  0x00007f7afd144698 _ZN11ToggleQueue13handle_toggleEPFvP8_GObjectNS_9DirectionEE (libcjs.so.0 + 0x4f698)
linuxmint/cinnamon-desktop#6  0x00007f7afd14471f _ZN11ToggleQueue18idle_handle_toggleEPv (libcjs.so.0 + 0x4f71f)
linuxmint/cinnamon-desktop#7  0x00007f7afd46be8e g_main_context_dispatch (libglib-2.0.so.0 + 0x51e8e)
linuxmint/cinnamon-desktop#8  0x00007f7afd46c240 n/a (libglib-2.0.so.0 + 0x52240)
linuxmint/cinnamon-desktop#9  0x00007f7afd46c533 g_main_loop_run (libglib-2.0.so.0 + 0x52533)
linuxmint/cinnamon-desktop#10 0x00007f7afdaac64a meta_run (libmuffin.so.0 + 0x4e64a)
linuxmint/cinnamon-desktop#11 0x000055e1d0deaafc main (cinnamon + 0x2afc)
linuxmint/cinnamon-desktop#12 0x00007f7afd2180b3 __libc_start_main (libc.so.6 + 0x270b3)
linuxmint/cinnamon-desktop#13 0x000055e1d0deac1e _start (cinnamon + 0x2c1e)

Stack trace of thread 2316:
#0  0x00007f7afd1de376 futex_wait_cancelable (libpthread.so.0 + 0x10376)
linuxmint/cinnamon-desktop#1  0x00007f7afa19b4d8 n/a (libmozjs-52.so.0 + 0x1ce4d8)
linuxmint/cinnamon-desktop#2  0x00007f7afa19b7a5 n/a (libmozjs-52.so.0 + 0x1ce7a5)
linuxmint/cinnamon-desktop#3  0x00007f7afa61b20c n/a (libmozjs-52.so.0 + 0x64e20c)
linuxmint/cinnamon-desktop#4  0x00007f7afa643349 n/a (libmozjs-52.so.0 + 0x676349)
linuxmint/cinnamon-desktop#5  0x00007f7afd1d7609 start_thread (libpthread.so.0 + 0x9609)
linuxmint/cinnamon-desktop#6  0x00007f7afd313103 __clone (libc.so.6 + 0x122103)

Stack trace of thread 2323:
#0  0x00007f7afd1de376 futex_wait_cancelable (libpthread.so.0 + 0x10376)
linuxmint/cinnamon-desktop#1  0x00007f7afa19b4d8 n/a (libmozjs-52.so.0 + 0x1ce4d8)
linuxmint/cinnamon-desktop#2  0x00007f7afa19b7a5 n/a (libmozjs-52.so.0 + 0x1ce7a5)
linuxmint/cinnamon-desktop#3  0x00007f7afa61b20c n/a (libmozjs-52.so.0 + 0x64e20c)
linuxmint/cinnamon-desktop#4  0x00007f7afa643349 n/a (libmozjs-52.so.0 + 0x676349)
linuxmint/cinnamon-desktop#5  0x00007f7afd1d7609 start_thread (libpthread.so.0 + 0x9609)
linuxmint/cinnamon-desktop#6  0x00007f7afd313103 __clone (libc.so.6 + 0x122103)

Stack trace of thread 2313:
#0  0x00007f7afd30696f __GI___poll (libc.so.6 + 0x11596f)
linuxmint/cinnamon-desktop#1  0x00007f7afd46c1ae n/a (libglib-2.0.so.0 + 0x521ae)
linuxmint/cinnamon-desktop#2  0x00007f7afd46c2e3 g_main_context_iteration (libglib-2.0.so.0 + 0x522e3)
linuxmint/cinnamon-desktop#3  0x00007f7afd46c331 n/a (libglib-2.0.so.0 + 0x52331)
linuxmint/cinnamon-desktop#4  0x00007f7afd495931 n/a (libglib-2.0.so.0 + 0x7b931)
linuxmint/cinnamon-desktop#5  0x00007f7afd1d7609 start_thread (libpthread.so.0 + 0x9609)
linuxmint/cinnamon-desktop#6  0x00007f7afd313103 __clone (libc.so.6 + 0x122103)

Stack trace of thread 2322:
#0  0x00007f7afd1de376 futex_wait_cancelable (libpthread.so.0 + 0x10376)
linuxmint/cinnamon-desktop#1  0x00007f7afa19b4d8 n/a (libmozjs-52.so.0 + 0x1ce4d8)
linuxmint/cinnamon-desktop#2  0x00007f7afa19b7a5 n/a (libmozjs-52.so.0 + 0x1ce7a5)
linuxmint/cinnamon-desktop#3  0x00007f7afa61b20c n/a (libmozjs-52.so.0 + 0x64e20c)
linuxmint/cinnamon-desktop#4  0x00007f7afa643349 n/a (libmozjs-52.so.0 + 0x676349)
linuxmint/cinnamon-desktop#5  0x00007f7afd1d7609 start_thread (libpthread.so.0 + 0x9609)
linuxmint/cinnamon-desktop#6  0x00007f7afd313103 __clone (libc.so.6 + 0x122103)

Stack trace of thread 2332:
#0  0x00007f7afd1de376 futex_wait_cancelable (libpthread.so.0 + 0x10376)
linuxmint/cinnamon-desktop#1  0x00007f7afa19b4d8 n/a (libmozjs-52.so.0 + 0x1ce4d8)
linuxmint/cinnamon-desktop#2  0x00007f7afa19b7a5 n/a (libmozjs-52.so.0 + 0x1ce7a5)
linuxmint/cinnamon-desktop#3  0x00007f7afa61b20c n/a (libmozjs-52.so.0 + 0x64e20c)
linuxmint/cinnamon-desktop#4  0x00007f7afa643349 n/a (libmozjs-52.so.0 + 0x676349)
linuxmint/cinnamon-desktop#5  0x00007f7afd1d7609 start_thread (libpthread.so.0 + 0x9609)
linuxmint/cinnamon-desktop#6  0x00007f7afd313103 __clone (libc.so.6 + 0x122103)

Stack trace of thread 2318:
#0  0x00007f7afd1de376 futex_wait_cancelable (libpthread.so.0 + 0x10376)
linuxmint/cinnamon-desktop#1  0x00007f7afa19b4d8 n/a (libmozjs-52.so.0 + 0x1ce4d8)
linuxmint/cinnamon-desktop#2  0x00007f7afa19b7a5 n/a (libmozjs-52.so.0 + 0x1ce7a5)
linuxmint/cinnamon-desktop#3  0x00007f7afa61b20c n/a (libmozjs-52.so.0 + 0x64e20c)
linuxmint/cinnamon-desktop#4  0x00007f7afa643349 n/a (libmozjs-52.so.0 + 0x676349)
linuxmint/cinnamon-desktop#5  0x00007f7afd1d7609 start_thread (libpthread.so.0 + 0x9609)
linuxmint/cinnamon-desktop#6  0x00007f7afd313103 __clone (libc.so.6 + 0x122103)

Stack trace of thread 2314:
#0  0x00007f7afd30696f __GI___poll (libc.so.6 + 0x11596f)
linuxmint/cinnamon-desktop#1  0x00007f7afd46c1ae n/a (libglib-2.0.so.0 + 0x521ae)
linuxmint/cinnamon-desktop#2  0x00007f7afd46c533 g_main_loop_run (libglib-2.0.so.0 + 0x52533)
linuxmint/cinnamon-desktop#3  0x00007f7afd6c3eda n/a (libgio-2.0.so.0 + 0x11eeda)
linuxmint/cinnamon-desktop#4  0x00007f7afd495931 n/a (libglib-2.0.so.0 + 0x7b931)
linuxmint/cinnamon-desktop#5  0x00007f7afd1d7609 start_thread (libpthread.so.0 + 0x9609)
linuxmint/cinnamon-desktop#6  0x00007f7afd313103 __clone (libc.so.6 + 0x122103)

Stack trace of thread 2321:
#0  0x00007f7afd1de376 futex_wait_cancelable (libpthread.so.0 + 0x10376)
linuxmint/cinnamon-desktop#1  0x00007f7afa19b4d8 n/a (libmozjs-52.so.0 + 0x1ce4d8)
linuxmint/cinnamon-desktop#2  0x00007f7afa19b7a5 n/a (libmozjs-52.so.0 + 0x1ce7a5)
linuxmint/cinnamon-desktop#3  0x00007f7afa61b20c n/a (libmozjs-52.so.0 + 0x64e20c)
linuxmint/cinnamon-desktop#4  0x00007f7afa643349 n/a (libmozjs-52.so.0 + 0x676349)
linuxmint/cinnamon-desktop#5  0x00007f7afd1d7609 start_thread (libpthread.so.0 + 0x9609)
linuxmint/cinnamon-desktop#6  0x00007f7afd313103 __clone (libc.so.6 + 0x122103)

Stack trace of thread 2317:
#0  0x00007f7afd1de376 futex_wait_cancelable (libpthread.so.0 + 0x10376)
linuxmint/cinnamon-desktop#1  0x00007f7afa19b4d8 n/a (libmozjs-52.so.0 + 0x1ce4d8)
linuxmint/cinnamon-desktop#2  0x00007f7afa19b7a5 n/a (libmozjs-52.so.0 + 0x1ce7a5)
linuxmint/cinnamon-desktop#3  0x00007f7afa61b20c n/a (libmozjs-52.so.0 + 0x64e20c)
linuxmint/cinnamon-desktop#4  0x00007f7afa643349 n/a (libmozjs-52.so.0 + 0x676349)
linuxmint/cinnamon-desktop#5  0x00007f7afd1d7609 start_thread (libpthread.so.0 + 0x9609)
linuxmint/cinnamon-desktop#6  0x00007f7afd313103 __clone (libc.so.6 + 0x122103)

Stack trace of thread 2320:
#0  0x00007f7afd1de376 futex_wait_cancelable (libpthread.so.0 + 0x10376)
linuxmint/cinnamon-desktop#1  0x00007f7afa19b4d8 n/a (libmozjs-52.so.0 + 0x1ce4d8)
linuxmint/cinnamon-desktop#2  0x00007f7afa19b7a5 n/a (libmozjs-52.so.0 + 0x1ce7a5)
linuxmint/cinnamon-desktop#3  0x00007f7afa61b20c n/a (libmozjs-52.so.0 + 0x64e20c)
linuxmint/cinnamon-desktop#4  0x00007f7afa643349 n/a (libmozjs-52.so.0 + 0x676349)
linuxmint/cinnamon-desktop#5  0x00007f7afd1d7609 start_thread (libpthread.so.0 + 0x9609)
linuxmint/cinnamon-desktop#6  0x00007f7afd313103 __clone (libc.so.6 + 0x122103)

Stack trace of thread 2315:
#0  0x00007f7afd30696f __GI___poll (libc.so.6 + 0x11596f)
linuxmint/cinnamon-desktop#1  0x00007f7afd46c1ae n/a (libglib-2.0.so.0 + 0x521ae)
linuxmint/cinnamon-desktop#2  0x00007f7afd46c2e3 g_main_context_iteration (libglib-2.0.so.0 + 0x522e3)
linuxmint/cinnamon-desktop#3  0x00007f7af5ead99d n/a (libdconfsettings.so + 0xa99d)
linuxmint/cinnamon-desktop#4  0x00007f7afd495931 n/a (libglib-2.0.so.0 + 0x7b931)
linuxmint/cinnamon-desktop#5  0x00007f7afd1d7609 start_thread (libpthread.so.0 + 0x9609)
linuxmint/cinnamon-desktop#6  0x00007f7afd313103 __clone (libc.so.6 + 0x122103)

Stack trace of thread 2335:
#0  0x00007f7afd1de376 futex_wait_cancelable (libpthread.so.0 + 0x10376)
linuxmint/cinnamon-desktop#1  0x00007f7afa19b4d8 n/a (libmozjs-52.so.0 + 0x1ce4d8)
linuxmint/cinnamon-desktop#2  0x00007f7afa19b7a5 n/a (libmozjs-52.so.0 + 0x1ce7a5)
linuxmint/cinnamon-desktop#3  0x00007f7afa61b20c n/a (libmozjs-52.so.0 + 0x64e20c)
linuxmint/cinnamon-desktop#4  0x00007f7afa643349 n/a (libmozjs-52.so.0 + 0x676349)
linuxmint/cinnamon-desktop#5  0x00007f7afd1d7609 start_thread (libpthread.so.0 + 0x9609)
linuxmint/cinnamon-desktop#6  0x00007f7afd313103 __clone (libc.so.6 + 0x122103)

Stack trace of thread 2326:
#0  0x00007f7afd1de376 futex_wait_cancelable (libpthread.so.0 + 0x10376)
linuxmint/cinnamon-desktop#1  0x00007f7afa19b4d8 n/a (libmozjs-52.so.0 + 0x1ce4d8)
linuxmint/cinnamon-desktop#2  0x00007f7afa19b7a5 n/a (libmozjs-52.so.0 + 0x1ce7a5)
linuxmint/cinnamon-desktop#3  0x00007f7afa61b20c n/a (libmozjs-52.so.0 + 0x64e20c)
linuxmint/cinnamon-desktop#4  0x00007f7afa643349 n/a (libmozjs-52.so.0 + 0x676349)
linuxmint/cinnamon-desktop#5  0x00007f7afd1d7609 start_thread (libpthread.so.0 + 0x9609)
linuxmint/cinnamon-desktop#6  0x00007f7afd313103 __clone (libc.so.6 + 0x122103)

Stack trace of thread 2327:
#0  0x00007f7afd1de376 futex_wait_cancelable (libpthread.so.0 + 0x10376)
linuxmint/cinnamon-desktop#1  0x00007f7afa19b4d8 n/a (libmozjs-52.so.0 + 0x1ce4d8)
linuxmint/cinnamon-desktop#2  0x00007f7afa19b7a5 n/a (libmozjs-52.so.0 + 0x1ce7a5)
linuxmint/cinnamon-desktop#3  0x00007f7afa61b20c n/a (libmozjs-52.so.0 + 0x64e20c)
linuxmint/cinnamon-desktop#4  0x00007f7afa643349 n/a (libmozjs-52.so.0 + 0x676349)
linuxmint/cinnamon-desktop#5  0x00007f7afd1d7609 start_thread (libpthread.so.0 + 0x9609)
linuxmint/cinnamon-desktop#6  0x00007f7afd313103 __clone (libc.so.6 + 0x122103)

Stack trace of thread 2331:
#0  0x00007f7afd1de376 futex_wait_cancelable (libpthread.so.0 + 0x10376)
linuxmint/cinnamon-desktop#1  0x00007f7afa19b4d8 n/a (libmozjs-52.so.0 + 0x1ce4d8)
linuxmint/cinnamon-desktop#2  0x00007f7afa19b7a5 n/a (libmozjs-52.so.0 + 0x1ce7a5)
linuxmint/cinnamon-desktop#3  0x00007f7afa61b20c n/a (libmozjs-52.so.0 + 0x64e20c)
linuxmint/cinnamon-desktop#4  0x00007f7afa643349 n/a (libmozjs-52.so.0 + 0x676349)
linuxmint/cinnamon-desktop#5  0x00007f7afd1d7609 start_thread (libpthread.so.0 + 0x9609)
linuxmint/cinnamon-desktop#6  0x00007f7afd313103 __clone (libc.so.6 + 0x122103)

Stack trace of thread 2330:
#0  0x00007f7afd1de376 futex_wait_cancelable (libpthread.so.0 + 0x10376)
linuxmint/cinnamon-desktop#1  0x00007f7afa19b4d8 n/a (libmozjs-52.so.0 + 0x1ce4d8)
linuxmint/cinnamon-desktop#2  0x00007f7afa19b7a5 n/a (libmozjs-52.so.0 + 0x1ce7a5)
linuxmint/cinnamon-desktop#3  0x00007f7afa61b20c n/a (libmozjs-52.so.0 + 0x64e20c)
linuxmint/cinnamon-desktop#4  0x00007f7afa643349 n/a (libmozjs-52.so.0 + 0x676349)
linuxmint/cinnamon-desktop#5  0x00007f7afd1d7609 start_thread (libpthread.so.0 + 0x9609)
linuxmint/cinnamon-desktop#6  0x00007f7afd313103 __clone (libc.so.6 + 0x122103)

Stack trace of thread 2333:
#0  0x00007f7afd1de376 futex_wait_cancelable (libpthread.so.0 + 0x10376)
linuxmint/cinnamon-desktop#1  0x00007f7afa19b4d8 n/a (libmozjs-52.so.0 + 0x1ce4d8)
linuxmint/cinnamon-desktop#2  0x00007f7afa19b7a5 n/a (libmozjs-52.so.0 + 0x1ce7a5)
linuxmint/cinnamon-desktop#3  0x00007f7afa61b20c n/a (libmozjs-52.so.0 + 0x64e20c)
linuxmint/cinnamon-desktop#4  0x00007f7afa643349 n/a (libmozjs-52.so.0 + 0x676349)
linuxmint/cinnamon-desktop#5  0x00007f7afd1d7609 start_thread (libpthread.so.0 + 0x9609)
linuxmint/cinnamon-desktop#6  0x00007f7afd313103 __clone (libc.so.6 + 0x122103)

Stack trace of thread 129954:
#0  0x00007f7afd30696f __GI___poll (libc.so.6 + 0x11596f)
linuxmint/cinnamon-desktop#1  0x00007f7afb9816fd send_dg (libresolv.so.2 + 0xa6fd)
linuxmint/cinnamon-desktop#2  0x00007f7afb97ec44 __GI___res_context_query (libresolv.so.2 + 0x7c44)
linuxmint/cinnamon-desktop#3  0x00007f7afb97f8ee __res_context_querydomain (libresolv.so.2 + 0x88ee)
linuxmint/cinnamon-desktop#4  0x00007f7a69490171 _nss_dns_gethostbyname4_r (libnss_dns.so.2 + 0x4171)
linuxmint/cinnamon-desktop#5  0x00007f7afd2f83ff gaih_inet (libc.so.6 + 0x1073ff)
linuxmint/cinnamon-desktop#6  0x00007f7afd2f9f49 __GI_getaddrinfo (libc.so.6 + 0x108f49)
linuxmint/cinnamon-desktop#7  0x00007f7afd65e881 n/a (libgio-2.0.so.0 + 0xb9881)
linuxmint/cinnamon-desktop#8  0x00007f7afd65ac62 n/a (libgio-2.0.so.0 + 0xb5c62)
linuxmint/cinnamon-desktop#9  0x00007f7afd4961d4 n/a (libglib-2.0.so.0 + 0x7c1d4)
linuxmint/cinnamon-desktop#10 0x00007f7afd495931 n/a (libglib-2.0.so.0 + 0x7b931)
linuxmint/cinnamon-desktop#11 0x00007f7afd1d7609 start_thread (libpthread.so.0 + 0x9609)
linuxmint/cinnamon-desktop#12 0x00007f7afd313103 __clone (libc.so.6 + 0x122103)

Stack trace of thread 2324:
#0  0x00007f7afd1de376 futex_wait_cancelable (libpthread.so.0 + 0x10376)
linuxmint/cinnamon-desktop#1  0x00007f7afa19b4d8 n/a (libmozjs-52.so.0 + 0x1ce4d8)
linuxmint/cinnamon-desktop#2  0x00007f7afa19b7a5 n/a (libmozjs-52.so.0 + 0x1ce7a5)
linuxmint/cinnamon-desktop#3  0x00007f7afa61b20c n/a (libmozjs-52.so.0 + 0x64e20c)
linuxmint/cinnamon-desktop#4  0x00007f7afa643349 n/a (libmozjs-52.so.0 + 0x676349)
linuxmint/cinnamon-desktop#5  0x00007f7afd1d7609 start_thread (libpthread.so.0 + 0x9609)
linuxmint/cinnamon-desktop#6  0x00007f7afd313103 __clone (libc.so.6 + 0x122103)

Stack trace of thread 2329:
#0  0x00007f7afd1de376 futex_wait_cancelable (libpthread.so.0 + 0x10376)
linuxmint/cinnamon-desktop#1  0x00007f7afa19b4d8 n/a (libmozjs-52.so.0 + 0x1ce4d8)
linuxmint/cinnamon-desktop#2  0x00007f7afa19b7a5 n/a (libmozjs-52.so.0 + 0x1ce7a5)
linuxmint/cinnamon-desktop#3  0x00007f7afa61b20c n/a (libmozjs-52.so.0 + 0x64e20c)
linuxmint/cinnamon-desktop#4  0x00007f7afa643349 n/a (libmozjs-52.so.0 + 0x676349)
linuxmint/cinnamon-desktop#5  0x00007f7afd1d7609 start_thread (libpthread.so.0 + 0x9609)
linuxmint/cinnamon-desktop#6  0x00007f7afd313103 __clone (libc.so.6 + 0x122103)

Stack trace of thread 2328:
#0  0x00007f7afd1de376 futex_wait_cancelable (libpthread.so.0 + 0x10376)
linuxmint/cinnamon-desktop#1  0x00007f7afa19b4d8 n/a (libmozjs-52.so.0 + 0x1ce4d8)
linuxmint/cinnamon-desktop#2  0x00007f7afa19b7a5 n/a (libmozjs-52.so.0 + 0x1ce7a5)
linuxmint/cinnamon-desktop#3  0x00007f7afa61b20c n/a (libmozjs-52.so.0 + 0x64e20c)
linuxmint/cinnamon-desktop#4  0x00007f7afa643349 n/a (libmozjs-52.so.0 + 0x676349)
linuxmint/cinnamon-desktop#5  0x00007f7afd1d7609 start_thread (libpthread.so.0 + 0x9609)
linuxmint/cinnamon-desktop#6  0x00007f7afd313103 __clone (libc.so.6 + 0x122103)

Stack trace of thread 129953:
#0  0x00007f7afd30696f __GI___poll (libc.so.6 + 0x11596f)
linuxmint/cinnamon-desktop#1  0x00007f7afb9816fd send_dg (libresolv.so.2 + 0xa6fd)
linuxmint/cinnamon-desktop#2  0x00007f7afb97ec44 __GI___res_context_query (libresolv.so.2 + 0x7c44)
linuxmint/cinnamon-desktop#3  0x00007f7afb97f8ee __res_context_querydomain (libresolv.so.2 + 0x88ee)
linuxmint/cinnamon-desktop#4  0x00007f7a69490171 _nss_dns_gethostbyname4_r (libnss_dns.so.2 + 0x4171)
linuxmint/cinnamon-desktop#5  0x00007f7afd2f83ff gaih_inet (libc.so.6 + 0x1073ff)
linuxmint/cinnamon-desktop#6  0x00007f7afd2f9f49 __GI_getaddrinfo (libc.so.6 + 0x108f49)
linuxmint/cinnamon-desktop#7  0x00007f7afd65e881 n/a (libgio-2.0.so.0 + 0xb9881)
linuxmint/cinnamon-desktop#8  0x00007f7afd65ac62 n/a (libgio-2.0.so.0 + 0xb5c62)
linuxmint/cinnamon-desktop#9  0x00007f7afd4961d4 n/a (libglib-2.0.so.0 + 0x7c1d4)
linuxmint/cinnamon-desktop#10 0x00007f7afd495931 n/a (libglib-2.0.so.0 + 0x7b931)
linuxmint/cinnamon-desktop#11 0x00007f7afd1d7609 start_thread (libpthread.so.0 + 0x9609)
linuxmint/cinnamon-desktop#12 0x00007f7afd313103 __clone (libc.so.6 + 0x122103)

Stack trace of thread 2325:
#0  0x00007f7afd1de376 futex_wait_cancelable (libpthread.so.0 + 0x10376)
linuxmint/cinnamon-desktop#1  0x00007f7afa19b4d8 n/a (libmozjs-52.so.0 + 0x1ce4d8)
linuxmint/cinnamon-desktop#2  0x00007f7afa19b7a5 n/a (libmozjs-52.so.0 + 0x1ce7a5)
linuxmint/cinnamon-desktop#3  0x00007f7afa61b20c n/a (libmozjs-52.so.0 + 0x64e20c)
linuxmint/cinnamon-desktop#4  0x00007f7afa643349 n/a (libmozjs-52.so.0 + 0x676349)
linuxmint/cinnamon-desktop#5  0x00007f7afd1d7609 start_thread (libpthread.so.0 + 0x9609)
linuxmint/cinnamon-desktop#6  0x00007f7afd313103 __clone (libc.so.6 + 0x122103)

Stack trace of thread 2319:
#0  0x00007f7afd1de376 futex_wait_cancelable (libpthread.so.0 + 0x10376)
linuxmint/cinnamon-desktop#1  0x00007f7afa19b4d8 n/a (libmozjs-52.so.0 + 0x1ce4d8)
linuxmint/cinnamon-desktop#2  0x00007f7afa19b7a5 n/a (libmozjs-52.so.0 + 0x1ce7a5)
linuxmint/cinnamon-desktop#3  0x00007f7afa61b20c n/a (libmozjs-52.so.0 + 0x64e20c)
linuxmint/cinnamon-desktop#4  0x00007f7afa643349 n/a (libmozjs-52.so.0 + 0x676349)
linuxmint/cinnamon-desktop#5  0x00007f7afd1d7609 start_thread (libpthread.so.0 + 0x9609)
linuxmint/cinnamon-desktop#6  0x00007f7afd313103 __clone (libc.so.6 + 0x122103)

Stack trace of thread 2334:
#0  0x00007f7afd1de376 futex_wait_cancelable (libpthread.so.0 + 0x10376)
linuxmint/cinnamon-desktop#1  0x00007f7afa19b4d8 n/a (libmozjs-52.so.0 + 0x1ce4d8)
linuxmint/cinnamon-desktop#2  0x00007f7afa19b7a5 n/a (libmozjs-52.so.0 + 0x1ce7a5)
linuxmint/cinnamon-desktop#3  0x00007f7afa61b20c n/a (libmozjs-52.so.0 + 0x64e20c)
linuxmint/cinnamon-desktop#4  0x00007f7afa643349 n/a (libmozjs-52.so.0 + 0x676349)
linuxmint/cinnamon-desktop#5  0x00007f7afd1d7609 start_thread (libpthread.so.0 + 0x9609)
linuxmint/cinnamon-desktop#6  0x00007f7afd313103 __clone (libc.so.6 + 0x122103)

**Comment by icarter09** [comment]
@Swaphelaer are you still experiencing this issue? Thanks.
