### ISSUE TITLE
Better search for Cinnamon?

### ISSUE THREAD

**Issue by asamolion** [linuxmint/cinnamon#9464]
```
 * Cinnamon version 4.6.6
 * Distribution - Linux Mint 20 x86_64
 * Graphics hardware - AMD ATI Radeon 540X with default AMD driver
 * 64 bit
 ```

**Issue**
The search in Cinnamon's menu is quite lackluster.
I can type the letters "displa" in the search bar and it will still rank "Display" as the 2nd option, with "Colors" being the first option.
The search for other stuff also shows similarly random results.
The cause may be outlined here: https://www.reddit.com/r/linuxmint/comments/hpp2ab/better_search_for_cinnamon/fxti781/

**Steps to reproduce**
Simply type "displa" in the cinnamon menu search and see the order of results.

**Expected behaviour**
If I type "displa" the most matching application should be first, in this case that would be "Display"

**Other information**
Screenshot
![image](https://user-images.githubusercontent.com/14261053/87756940-39f52880-c823-11ea-9152-7c095761a35c.png)

**Comment by smerdysmerdy** [comment]
How about a better menu too

**Comment by NikoKrause** [comment]
Fixed by https://github.com/linuxmint/cinnamon/commit/a6738bd306180b4e2e668c90c1d7d5d6c0578906
