### ISSUE TITLE
Graphical glitches/Artifacts when display settings change

### ISSUE THREAD

**Issue by Saphieron** [linuxmint/cinnamon#9465]
```
 * Cinnamon version 4.6.6
   - Not using daily builds PPAs
 * Distribution - (Mint 20)
 * Graphics hardware *and* driver used: result from inxi -G
    - Graphics:  Device-1: Intel UHD Graphics 620 driver: i915 v: kernel 
           Display: x11 server: X.Org 1.20.8 driver: intel resolution: 2560x1440~60Hz 
           OpenGL: renderer: Mesa Intel UHD Graphics 620 (KBL GT2) v: 4.6 Mesa 20.0.8

 * 64 bit
 * Attached .xsession-errors and /var/log/syslog below


```

**Issue**
When either disconnecting an external screen, changing the fractional scaling, allowing the automated rotate function change the screen orientation or restarting cinnamon with the panel's troubleshooting->restart Cinnamon button the complete desktop including the wallpaper background, all windows, panels and other GUI elements contain weird graphical glitches. two screenshots are attached 

**Steps to reproduce**
Change any settings to the current display setup or restart cinnamon. 

**Expected behaviour**
No graphical glitches should appear. All fonts and symbols should remain the same and the desktop wallpaper should show no glitches.

**Other information**
Additional infos:
Lenovo Thinkpad X1 yoga 3rd gen
Using https://github.com/erpalma/throttled to undervolt laptop during battery operation to reduce thermal issues and increase battery-life. Was not a problem in Mint 19.3. No undervolting on AC, current setting for battery is 
```
        [UNDERVOLT.BATTERY]
        # CPU core voltage offset (mV)
        CORE: -50
        # Integrated GPU voltage offset (mV)
        GPU: -40
        # CPU cache voltage offset (mV)
        CACHE: -50
        # System Agent voltage offset (mV)
        UNCORE: -50
        # Analog I/O voltage offset (mV)
        ANALOGIO: 0
```
EDIT: Additionally, sometimes the glitches can be removed by resizing a window alone, but cinnamon GUI elements such as icons/font in the panel keep the glitches.

[syslog2020-07-17.txt](https://github.com/linuxmint/cinnamon/files/4937240/syslog2020-07-17.txt)
[xsession-errors.txt](https://github.com/linuxmint/cinnamon/files/4937241/xsession-errors.txt)
![Screenshot from 2020-07-17 12-10-26](https://user-images.githubusercontent.com/9096218/87777735-5052b280-c82a-11ea-9706-9e7c67f2b8bc.png)
![Screenshot from 2020-07-17 12-10-38](https://user-images.githubusercontent.com/9096218/87777739-5183df80-c82a-11ea-8095-085a9628e388.png)
![Screenshot from 2020-07-17 12-37-24](https://user-images.githubusercontent.com/9096218/87777743-52b50c80-c82a-11ea-8d29-667f7d0eaaf5.png)

**Comment by Saphieron** [comment]
This problem appears to continue existing in 4.6.7 and  Kernel 5.4.0-54-generic.

**Comment by leigh123linux** [comment]
This is a graphics driver issue, perhaps you should try the modesetting driver instead.

```
$ inxi -G
Graphics:
  Device-1: Intel UHD Graphics 605 driver: i915 v: kernel 
  Display: x11 server: Fedora Project X.org 1.20.9 driver: modesetting 
  unloaded: fbdev,vesa resolution: 3840x2160~60Hz 
  OpenGL: renderer: Mesa Intel UHD Graphics 600 (GLK 2) v: 4.6 Mesa 20.2.2
```
