### ISSUE TITLE
Allow custom EDID files and/or custom resolution/timing entry via Display applet

### ISSUE THREAD

**Issue by smerdysmerdy** [linuxmint/cinnamon#9466]
Allow custom EDID files via Display settings app

I need to use a custom EDID file for resolutions from a monitor with fried EDID board, currently it cannot get the correct values and would like to upload a stored copy and use that instead

EDID is the VESA standard on how a monitor communicates supported resolutions and timings

https://en.wikipedia.org/wiki/Extended_Display_Identification_Data

At the very least, allow custom resolution and timing entry

**Comment by leigh123linux** [comment]
I consider this out of cinnamon's scope, you will need to edit xorg config files manually.

**Comment by smerdysmerdy** [comment]
How about a tool then?

**Comment by smerdysmerdy** [comment]
Why can we at least not be able to enter manual settings overriding the discovered ones?

**Comment by leigh123linux** [comment]
Try  https://kodi.wiki/view/Creating_and_using_edid.bin_via_xorg.conf#Configure_xorg_to_read_custom_EDID_file

**Comment by smerdysmerdy** [comment]
> Try https://kodi.wiki/view/Creating_and_using_edid.bin_via_xorg.conf#Configure_xorg_to_read_custom_EDID_file

Thanks, would be nicer to just be able to enter a resolution and refresh in the Display settings app
