### ISSUE TITLE
Pinned application icon open but unfocused indistinguishable from not open

### ISSUE THREAD

**Issue by php4fan** [linuxmint/cinnamon#9469]
**Steps to reproduce:**

- pin Gedit to the panel (could use any other application)

Case 1:

- open Gedit
- minimize it or give focus to some other window

Case 2:

- don't open Gedit, and if you have any Gedit windows open, close them

**Expected behavior:**

Gedit's icon in Panel should look different in case 1 and case 2. You should be able to tell whether you have any window of that application open or not.

**Observed behavior:**

there's no difference whatsoever between case 1 and 2. You can tell if the window corresponding to a panel icon is currently focused, but if it isn't, you can't tell whether it has any windows open or not.

**Comment by JosephMcc** [comment]
The stock Cinnamon theme needing improvement is a good point. That's something I'll look at this dev cycle.
