### ISSUE TITLE
Feature Request (sound@cinnamon.org) Play sound when adjusting volume on the traybar

### ISSUE THREAD

**Issue by silocoder** [linuxmint/cinnamon#9472]
LM 20
Cinnamon 4.6.6

Play sound when adjusting volume on the traybar sound icon.  Maybe have a small beep play or something to that effect.

![image](https://user-images.githubusercontent.com/57298274/87897195-8c4b6a80-ca18-11ea-86de-923bb23dc4da.png)

Currently the only way to hear it is to go into settings (or use they sound hotkeys of the computer)

**Comment by ssmid** [comment]
Assuming the volume is changed via scrolling on the icon, the feature is already in place. Issue can be closed.
