### ISSUE TITLE
Switching workspaces no longer producing sound (switch.oga)

### ISSUE THREAD

**Issue by dannn-o** [linuxmint/cinnamon#9475]
Cinnamon 4.4.8
NOT using 'daily builds PPA'
Mint 19.3 (64-bit)
Graphics - Intel HD Graphics 630 (i915 driver)
Audio - Intel 200 Series PCH HD Audio (Alsa sound server)

**Issue**
Up until recently, switching workspaces (I normally use the "Workspace switcher" applet) would be accompanied by the 'swoosh' sound.  However, it no longer makes the sound, and restarting Linux Mint has not had any effect.  I checked in the Sound system settings, and switch.oga is displaying correctly for the "Switching workspace" sound, and it plays normally as expected when clicked.

**Steps to reproduce**
I tried both clicking different workspaces in the "Workspace switcher" applet in the tray, and also switched workspaced by using CTRL + ALT + left arrow / right arrow.  No sound is heard.

**Expected behaviour**
The switch.oga sound file (swooshing sound) should play as the workspace is switched.

**Other information**
Other system sounds do not seem to be affected and play normally.  For example, plugging in a
USB flash drive triggers the "Inserting a device" (plug.oga) sound file to play, etc.

**Comment by ItzSwirlz** [comment]
For Ubuntu Cinnamon Remix, this is fine. Are your sounds turned on and configured correctly?

**Comment by dannn-o** [comment]
Thanks for your comment.  As I mentioned, the switch.oga sound file is configured correctly for the "Switching workspace" sound, it can be heard fine when played manually in the "Sound" configuration menu, it had been working successfully up until somewhat recently, and other sounds are playing successfully (again, "Inserting a device" was mentioned specifically, and the "login.oga" sound played when "Starting Cinnamon" is another example).

**Comment by ItzSwirlz** [comment]
Huh. I'll have to test in unstable, maybe the code is incorrect?

**Comment by dannn-o** [comment]
Not sure what you mean by "unstable"?  I tried searching through GitHub to see if I might identify a recent change affecting the workspace switching or sound creating code that is involved.  I didn't have any luck, but admit I may not have done the most effective searches.  If it wasn't a recent code change causing this to stop working, I don't know where to look locally on my computer for another potential cause.

**Comment by ItzSwirlz** [comment]
Sorry-in non tech terms I'll look at Cinnamon 4.6.6 and see if the problem persists.

**Comment by dannn-o** [comment]
I'm guessing you are running Ubuntu 20.04?  Again, the sound had been working before (with Cinnamon 4.4.8).  I have Ubuntu Studio with 20.04 installed on another computer in the house, and I replaced the DE with Cinnamon from the repos (v 4.4.8)...I don't use multiple workspaces on that machine, but could easily test it.  I just don't know what going through that effort will tell us about the defect, whether the sound works or not.

**Comment by dannn-o** [comment]
I've also posted to the Linux Mint forums regarding this issue:
[https://forums.linuxmint.com/viewtopic.php?f=48&t=326351](https://forums.linuxmint.com/viewtopic.php?f=48&t=326351)

In my subsequent testing, I've discovered that the workspace OSD duration is also misbehaving and not respecting the setting values.  Seems there is something wrong with the internals for the workspace switching function.

**Comment by dannn-o** [comment]
A-HA!! I found something that might shed a bit of light on this problem. I noticed some older bug reports (see, for example #6944) that involved the workspace OSD being affected (improperly) by the Cinnamon Windows Effects settings. So, I gave a try to disabling the Window Effects, and sure enough, the OSD duration is now behaving properly again and recognizing setting changes that I make.

The only bummer is, the switch.oga sound is still not playing when workspaces are switched. But, I'm wondering if there was a somewhat-recent code change that regressed the fix from the earlier bug reports, and might also be affecting the sound event?

**Comment by dannn-o** [comment]
Just realized I've done most of my posting in the Mint forum mentioned above.  A new finding:  After the computer boots and autologon finishes, the switch.oga sound and OSD duration do not work.  If I restart Cinnamon using CTRL + ALT + ESC, then both the switch.oga sound and OSD duration start working correctly.  NOTE:  restarting Cinnamon using ALT + F2, then "r", does NOT seem to fix the problem.

**Comment by dannn-o** [comment]
I'm closing this issue as I believe I've resolved it.  You can see the forum thread mentioned earlier for full details, but the root cause appears to be that the login option somehow got changed from "Cinnamon (Default)" to "Cinnamon (Software Rendering)".  That, somehow, causes the switch.oga audio problem, as well as the OSD duration issue.  Switching back to "Cinnamon (Default)" appears to have fixed the problem.
