### ISSUE TITLE
Feature Request: Alt-Tab shows windows directly instead of preview

### ISSUE THREAD

**Issue by lauchpeter** [linuxmint/cinnamon#9478]
```
 * Cinnamon 4.6.6
 * Linux Mint 20 64 bit
 ```

If there was an option to disable the preview when tabbing between windows, it would be much easier to determine the right terminal of the 3+ that currently are opened. So, you Alt-Tab and the first window is shown, when you Alt-Tab again it disappears in favor of the next, and so on.

I am not sure though, if I am at the right place here. If not, I am sorry.

**Comment by smurphos** [comment]
Hi @lauchpeter - this feature already exists. Menu > Preferences > Windows > Alt-Tab > set Switcher Style to Window Preview (no icon). The 'previews' in this mode are the actual window at is full size and position.

**Comment by ssmid** [comment]
Oh, sorry for bothering you... Next time I'll take a closer look before I ask for a feature. But thanks for your reply!
