### ISSUE TITLE
"cinnamon-settings themes" fails with "OSError: [Errno 5] Input/output error'"

### ISSUE THREAD

**Issue by fifthrider** [linuxmint/cinnamon#9485]
```
 * Cinnamon version 4.6.6
   - I am not using the daily builds PPA.
 * Distribution - Mint 20, upgraded from Mint 19.3
 * Graphics hardware *and* driver used - Ryzen 2400G APU (technical details below:)
           AMD Raven Ridge [Radeon Vega Series / Radeon Vega Mobile Series] 
           driver: amdgpu v: kernel bus ID: 38:00.0 chip ID: 1002:15dd 
           Display: x11 server: X.Org 1.20.8 driver: modesetting unloaded: fbdev,vesa 
           alternate: ati tty: N/A 
           OpenGL: renderer: AMD RAVEN (DRM 3.35.0 5.4.0-42-generic LLVM 10.0.0) 
           v: 4.6 Mesa 20.0.8 direct render: Yes 
 * 64 bit
 * Nothing in xsession-errors or syslog corresponding to event.  (Reproducing issue does not generate output in either.)
 ```

**Issue**
_Apologies in advance if this is filed with the wrong bug tracker; if I am reading [the projects list](https://projects.linuxmint.com/cinnamon/) correctly, this is related to cinnamon rather than cinnamon-control-center ("Cinnamon Control Center is a fork of GNOME Control Center. The official control center of Cinnamon in [sic] Cinnamon Settings, which is written in python and part of Cinnamon itself.")_

Since upgrading to Mint 20, the Themes menu does not open.  Launching it from the cinnamon-settings GUI or from the Mint menu fails silently.  Attempting to open it manually with "cinnamon-settings themes" produces the following output in the terminal:

>/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py:426: DeprecationWarning: Gtk.Window.set_wmclass is deprecated
  self.window.set_wmclass(wm_class, wm_class)
Traceback (most recent call last):
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 730, in <module>
    window = MainWindow()
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 431, in __init__
    self.go_to_sidepage(cat, path, user_action=False)
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 188, in go_to_sidepage
    sidePage.build()
  File "/usr/share/cinnamon/cinnamon-settings/bin/SettingsWidgets.py", line 212, in build
    self.module.on_module_selected()
  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_themes.py", line 49, in on_module_selected
    self.spices = Spice_Harvester('theme', self.window)
  File "/usr/share/cinnamon/cinnamon-settings/bin/Spices.py", line 176, in __init__
    self._load_cache()
  File "/usr/share/cinnamon/cinnamon-settings/bin/Spices.py", line 499, in _load_cache
    self.index_cache = json.load(f)
  File "/usr/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
OSError: [Errno 5] Input/output error'

**Steps to reproduce**
Either select "Themes" in the cinnamon-settings GUI or manually run "cinnamon-settings themes"

**Expected behaviour**
Themes menu should open.

**Other information**
Possibly related, since this appears to involve python: I experienced other python-related errors after upgrading, which I was able to resolve by installing the python-is-python3 package.

**Comment by ItzSwirlz** [comment]
I got ya... wait-after installing that python package it worked? Or is this a missing dependency for Cinnamon?

**Comment by fifthrider** [comment]
Thanks for the quick reply--

The python-is-python3 package just adds a symlink to point /usr/bin/python to python3; it was necessary to make youtube-dl continue to run after the upgrade.  I only mention it here because the package description warns that "[i]t may improve compatibility with other modern systems, whilst breaking some  obsolete or 3rd-party software."  I did not notice this issue until after I installed python-is-python3, so I don't know whether it is related.  I suspect, however, that "cinnamon-settings themes" might be expecting Python 2.7.

**Comment by ItzSwirlz** [comment]
Yep, that would likely do it-but the error came from Python3.8.

I'll try to reproduce if I can in a VM or something and take a closer look-I wouldn't be surprised if this was a regression or python devs doing what they do-breaking comparability.

**Comment by fifthrider** [comment]
Gotcha; thanks.

**Comment by mtwebster** [comment]
Try deleting the `~/.cinnamon/spices.cache` folder.

Are you able to open the applet, desklet and extension settings?

**Comment by fifthrider** [comment]
Applet, desktop, and extension settings were unaffected.  However, deleting spices.cache seems to have fixed Themes.  Thanks!
