### ISSUE TITLE
gnome-font-viewer hangs

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/cinnamon#9492]
```
 * Cinnamon version (cinnamon --version): 4.6.6.
   - Please specify if you are using the daily builds PPA: no
     (https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds).
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 20
 * Graphics hardware *and* driver used: Intel 3rd Gen Core processor Graphics Controller & 3.0 Mesa 20.0.8; and whatever VirtualBox (on Windows) uses.
 * 32 or 64 bit: 64. (Mint 20 is 64-bit only.)
 * Attach /home/<username>/.xsession-errors, or [[/var/log/syslog]]
[xsession-errors.txt](https://github.com/linuxmint/cinnamon/files/4985115/xsession-errors.txt) (and there are a lot of errors recorded in there . .)

 ```

**Issue**

The gnome-font-viewer hangs - fails to respond - on launch and eventually produces a 'not responding' message.
I see this behaviour on an almost fresh install on a VM and also on a ThinkPad running Mint natively. (Well: only the former produces the not-responding message, but there was a hang on both.)

**Steps to reproduce**

Open the main Cinnamon menu.
Type 'font'.
Select 'fonts' (which runs `gnome-font-viewer %u`).
See the window appear and wait a few seconds.
Try to close the window.

**Expected behaviour**

No hang.

**Other information**

When and only whjen I run `gnome-font-viewer %u` from terminal, a window pops up saying, 'This font could not be displayed: /home/nicholas/<my username>/%u': No such file or directory'. But perhaps that is expected. However, after closing that message window, I can use the application, i.e. it does not hang.

EDIT: Problem confirmed on another setup (this last one being a fast ThinkPad).

**Comment by leigh123linux** [comment]
How is it cinnamon's fault if some crappy gnome app fails?

Go and bug the app instead

https://bugs.launchpad.net/ubuntu/+source/gnome-font-viewer

**Comment by LinuxOnTheDesktop** [comment]
Strictly, you are right. On the other hand, do you want to bundle an app that hangs on launch? Suppose someone new to Linux hears about Mint and tries Mint and Cinnamon, and then tries to look at her fonts and . . ? Certainly someone should file an app against the gnome product.

**Comment by smurphos** [comment]
> EDIT: There is [an existing report filed against the package on the Ubuntu bug tracker](https://bugs.launchpad.net/ubuntu/+source/gnome-font-viewer/+bug/1845362). It seems reasonable for me to request that, _if and when the bug is fixed, you update your version of the package_.

Just for info they are one and the same - there is no Mint version of this particular package - it comes directly from the Focal repos so if and when there is a fix it will be offered to Mint users without any action from the Mint development team.

```
steve@steve-Inspiron-5580:~$ apt list gnome-font-viewer
Listing... Done
gnome-font-viewer/focal,now 3.34.0-2 amd64 [installed]
```
