### ISSUE TITLE
Refresh on Update Manager does not trigger list of available updates

### ISSUE THREAD

**Issue by nlanfran** [linuxmint/cinnamon#9493]
* System: Kernel: 5.4.0-42-generic x86_64 bits: 64 compiler: gcc v: 9.3.0 Desktop: Cinnamon 4.6.6 
                 wm: muffin dm: LightDM Distro: Linux Mint 20 Ulyana base: Ubuntu 20.04 focal

* CPU:      Topology: Quad Core model: Intel Core i5-4460 bits: 64 type: MCP arch: Haswell rev: 3 
                 L2 cache: 6144 KiB 
                 flags: avx avx2 lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx bogomips: 25585 
                 Speed: 1212 MHz min/max: 800/3400 MHz Core speeds (MHz): 1: 1199 2: 1215 3: 1337 
                 4: 1280 

 * Distribution - Mint 20

 * Graphics:  Device-1: Intel Xeon E3-1200 v3/4th Gen Core Processor Integrated Graphics 
                     vendor: ASUSTeK driver: i915 v: kernel bus ID: 00:02.0 chip ID: 8086:0412 
                     Display: x11 server: X.Org 1.20.8 driver: modesetting unloaded: fbdev,vesa 
                     resolution: 1920x1080~60Hz 
                    OpenGL: renderer: Mesa DRI Intel HD Graphics 4600 (HSW GT2) v: 4.5 Mesa 20.0.8 
                    compat-v: 3.0 direct render: Yes 
 * 64 bit

**Issue**
On Update Manager, clicking on Refresh does not update the cache, and normal system updates are not found (no updates for 2 weeks). In order to receive system updates, I have to go to Software Sources, click on restore the default settings, click OK to update the APT cache, then go back to Update Manager, and the system updates will be listed.

**Steps to reproduce**
Open Update Manager, click on Refresh and no 'Downloading package information' (or any other APT cache update) can be seen

**Expected behaviour**
Update Manager should periodically trigger list of available updates. Same when clicking on Refresh. 

**Other information**
Linux Mint 20 was upgraded from Linux Mint 19.3 via official procedure, no problems during update

**Comment by JosephMcc** [comment]
I don't know if this is even still an issue but if it is, you should open it here: https://github.com/linuxmint/mintupdate/issues

It has nothing to do with Cinnamon.
