### ISSUE TITLE
New user dialog (cinnamon-settings-users) hangs if the username already exists

### ISSUE THREAD

**Issue by mtwebster** [linuxmint/cinnamon#9494]
```
 * 4.6.*
 * Mint 20
 * 64 bit
```

**Issue**
Attempt to create a new user.  If you use an existing name and try to add it, the dialog hangs, you must close it with X and open a new one.

```


Traceback (most recent call last):
  File "/usr/share/cinnamon/cinnamon-settings-users/cinnamon-settings-users.py", line 884, in on_user_addition
    new_user = self.accountService.create_user(username, fullname, account_type)
gi.repository.GLib.Error: act_user_manager_error: GDBus.Error:org.freedesktop.Accounts.Error.UserExists: A user with name 'mtwebster' already exists (1)
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 144, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_share_cinnamon_cinnamon-settings-users_cinnamon-settings-users.py.0.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/share/cinnamon/cinnamon-settings-users/cinnamon-settings-users.py", line 884, in on_user_addition
    new_user = self.accountService.create_user(username, fullname, account_type)
gi.repository.GLib.Error: act_user_manager_error: GDBus.Error:org.freedesktop.Accounts.Error.UserExists: A user with name 'mtwebster' already exists (1)
```

A couple of options:
- Use self.accountService.get_user() to see if the name exists already
- Try to create_user() and catch the UserExists error.

In both cases you need to allow the user to try again, which means instead of using dialog.run() and blocking for a response code, we just show() the dialog, connect to the 'response' signal, and check for uniqueness before closing the dialog.  Some sort of error message would be appropriate also (we can handle more than just this error if necessary, we need to see what other ways it can be broken).

**Comment by ItzSwirlz** [comment]
I'll look at Cinnamon 4.8 to see if I can reproduce this
