### ISSUE TITLE
Nemo bookmarks keep refreshing to top of the list. Gif attached

### ISSUE THREAD

**Issue by silocoder** [linuxmint/cinnamon#9498]
LM 20, Cinnamon 4.6.6, Nemo 4.6.4
Scroll bookmarks and they will then reset to Home. Sometimes within a couple of secs other times in few more. 
It is just annoying behavior that sometime gets in the way when trying to view properties or even click on some bookmark. Any idea what could be causing and why?

![Peek 2020-07-30 15-42](https://user-images.githubusercontent.com/57298274/88967401-c409ac00-d27b-11ea-9b14-0a1a410aa71b.gif)

**Comment by icarter09** [comment]
@silocoder please reopen this issue in Nemo. Thanks.
