### ISSUE TITLE
Draws garbage instead of window shadow when window resized "too large"

### ISSUE THREAD

**Issue by teo1978** [linuxmint/cinnamon#9500]
```
 * Cinnamon version (cinnamon --version) 4.4.8
   - Please specify if you are using the daily builds PPA - No
     (https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds).
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Ubuntu 20.04
 * Graphics hardware *and* driver used 
```
Intel Corporation 3rd Gen Core processor Graphics Controller
NVIDIA Corporation GF117M [GeForce 610M/710M/810M/820M / GT 620M/625M/630M/720M]
```
No idea about the driver as it doesn't show up in System Info

 * 3
[xsession-errors.txt](https://github.com/linuxmint/cinnamon/files/5006410/xsession-errors.txt)
64 bit 
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
 ```

**Issue**

**Steps to reproduce**

- Pick a window, for example a Gedit or terminal window
- Resize it horizontally to make it wider
- move it to the left so most of it is outside the screen
- Resize it further horizontally to the right to make it gigantically wide
- Repeat until issue is observed

**Expected behaviour**

Obvious

**Observed behaviour**

The shadow next to the right edge of the window starts to look like random garbage:

![image](https://user-images.githubusercontent.com/542107/89024955-464eaa80-d326-11ea-93f3-32f10215c115.png)

If you move the window, it will become more obvious:

![image](https://user-images.githubusercontent.com/542107/89024981-55355d00-d326-11ea-9c7e-2d0703a7d1b5.png)

Instead of a shadow, a thin vertical slice of the background that the window was on when resizing it is shown and remains stick to the window edge.

**Other information**

**Comment by JosephMcc** [comment]
Certain apps had bugs that caused them to request textures too large for a lot of video hardware to handle. This would crash the desktop. Because of that we had to put limits on this which I think is around 2x the current screen size. In real and practical use this is a non issue.

**Comment by teo1978** [comment]
That's stupid. Put  all the limits you want, but then just take them into account and draw something else there.

> In real and practical use this is a non issue.

If that was the case I wouldn't have faced it. I only use my computer for real and practical uses. 

But anyway, I don't care because I have abandoned Cinnamon and moved to something else, as I guess anybody would do for any "real and practical use".
