### ISSUE TITLE
"Fallback mode" prompt shows up on first display even if turned off, so you can't see it

### ISSUE THREAD

**Issue by teo1978** [linuxmint/cinnamon#9504]
I have an external monitor connected to my laptop and it's set up as the only monitor. So, my normal configuration is: built-in display switched off, and external display as the only one.

Something crashed and I had to force-power down my laptop. I don't know what it was and that's besides the point of this issue.

At the next boot, the login screen showed up as usual on the laptop's builtin display (with the external display acting as extension of the desktop, as per an unrelated well-known bug), I entered my password and logged in into Cinnamon as usual.

The laptop's built-in display turned off as expected, and then I waited for the external monitor to turn on and for the desktop to show up there.

I waited forever, nothing. The external monitor didn't even turn on.

So then I disconnected the external monitor, and the builtin screen turned on automatically, and to my surprise there was a prompt there that said something like:
```
You are running in fall-back mode [whatever the fuck that is]. If you suspect that bla bla bla, you can disable applets and whatever.
```
There was a checkbox for disabling applets or something, which I didn't check, and one or two buttons, I clicked on "Continue" or something like that.

Then Cinnamon started normally, and then when I connected the external monitor , it switched to external-monitor-only as expected and everything is working normally.

**The issue here** is that that "fallback mode" prompt was being "virtually shown" on a monitor that was not turned on.
BOTH monitors were off.

Obviously when you show a prompt you need to make sure that at least one monitor is on and that you show it on one that is on (assuming you cannot apply the normal configuration).

It seems the sequence of events went something like this:
1 - login screen appeared on builtin display, with both displays on in "extended desktop" mode
2 - I logged in
3 - builtin display turned off as required by my external-display-only configuration
4 - the fallback-mode prompt was displayed on the now-turned-off builtin monitor before the other was ever turned on.

That sequence is obviously wrong. Either you can turn back on the display when you are going to display the prompt, or turning off the builtin display must wait until you have made sure that you don't need to display the prompt.

You don't just leave the user with no display turned on and an invisible prompt that asks for their input to continue.

**Comment by icarter09** [comment]
@teo1978 are you still using Cinnamon? I believe you aren't any longer, but wanted to make sure. Thanks.

**Comment by teo1978** [comment]
Indeed I'm not
