### ISSUE TITLE
Allow adding multiple instances of the System Tray applet

### ISSUE THREAD

**Issue by ParticleMon** [linuxmint/cinnamon#9509]
The System Tray applet can be added to only one panel.

This behavior is acceptable with a single monitor. But with multiple monitors, this behavior can result in poor UX, such as relative to applications that minimize to the tray.

Restoring from the tray an application minimized on a non-primary monitor restores it to the primary monitor instead of, as desired, the monitor on which it was minimized.

**Comment by JosephMcc** [comment]
Unfortunately because the way the system tray works there can only currently be a single instance of it.
