### ISSUE TITLE
Sound tray icon can't tell if it's muted now when music player is launched.

### ISSUE THREAD

**Issue by snorez** [linuxmint/cinnamon#9513]
```
 * Cinnamon version (Cinnamon 4.6.6)
 * Distribution - (Linux Mint 20)
 * Graphics hardware *and* driver used
Graphics:  Device-1: Intel HD Graphics 630 vendor: Lenovo driver: i915 v: kernel bus ID: 00:02.0 
           chip ID: 8086:591b 
           Device-2: NVIDIA GP107M [GeForce GTX 1050 Ti Mobile] vendor: Lenovo driver: nvidia 
           v: 440.100 bus ID: 01:00.0 chip ID: 10de:1c8c 
           Display: x11 server: X.Org 1.20.8 driver: modesetting,nvidia 
           unloaded: fbdev,nouveau,vesa resolution: 1920x1080~60Hz 
           OpenGL: renderer: GeForce GTX 1050 Ti/PCIe/SSE2 v: 4.6.0 NVIDIA 440.100 
           direct render: Yes 
 * 64 bit
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
 ```

**Issue**
When the music player(Rhythmbox) is launched, the sound tray icon is changed too. Then I don't know if it is muted or not now.

**Steps to reproduce**
Launch rhythmbox, then mute.

**Expected behaviour**
I wonder if it's possible to not change the sound tray icon when music player is launched.

**Other information**

**Comment by cgohier** [comment]
It can be disabled. Right-click on the sound tray icon, and select 'Configure...'. 
Then, disable the 'Control Players' option.

You won't be able to control the player from the icon anymore, except you can set the middle-click to 'Toggle Play/Pause'.

**Comment by snorez** [comment]
@cgohier Yeah, how could I miss that option, lol. Thanks a lot.
