### ISSUE TITLE
Manjaro cinnamon

### ISSUE THREAD

**Issue by lorenzoTecchio** [linuxmint/cinnamon#9519]
Ho I have manjaro why it is not updated to the minimum version 4.4.6 and is still at the 2019 version. @clefebvre ?

**Comment by ItzSwirlz** [comment]
We are not in charge of that, that is your distributions maintainers job. They either have not worked on it yet, you haven't upgraded, or there is a problem preventing work from actually happening.

Manjaro is based on Arch which is already up to date.

TL;DR: Close this issue, it is not our responsibility, you either need to upgrade your system to latest versions or your distro maintainers for this hasn't done it yet.

**Comment by leigh123linux** [comment]
Go and bug manjaro instead!
