### ISSUE TITLE
feature request - scripted addition/removal of applets on panel

### ISSUE THREAD

**Issue by noreasternhumidity** [linuxmint/cinnamon#9520]
Cinnamon = or GT 4.4.8 
(Linux Mint 19.3 and later)
 ```
**Issue**

Feature request - scripted addition/removal of applets on panel.  Something I can do using a bash script.  This is one issue I can't seem to resolve using brute force tactics.  Maybe it is using GVFS?

**Expected behaviour**

Run a custom bash script to manage machine and new or existing user accounts.  I'd like it to at least manage user applets.  The bash script is used during computer setup, but also could be used any other time to restore/normalize expected custom settings, programs, and behaviors.  If it helps, I could store a copy of the applets to be activated in a relative directory with the bash file.

**Other information**

I'm a bit OCD  :)

Thanks for reading

**Comment by mtwebster** [comment]
I can maybe just use this on your source machine (when you get a setup just how you want it):
```
dconf dump /org/cinnamon/ > dump
```
then on the targets,
```
dconf load /org/cinnamon/ < dump
```

The dump is text so you can prune out sections you may want to omit (that dump includes a lot of misc. session configuration also).  You can use dconf-editor to browse this store.

**Comment by noreasternhumidity** [comment]
Thanks for that!  I will post back after I have a chance to try it out.

**Comment by noreasternhumidity** [comment]
P.S. sorry for the code-formatted OP.  Apparently my original use of the "greater than" symbol in the first line triggered it for the whole post.

**Comment by noreasternhumidity** [comment]
Just leaving a note to say thank you, it worked great!

**Comment by icarter09** [comment]
@noreasternhumidity can this ticket be closed?
