### ISSUE TITLE
GNOME Tweaks 3.34.0 title bar is transparent when launched on Linux Mint/Cinnamon

### ISSUE THREAD

**Issue by silocoder** [linuxmint/cinnamon#9521]
I was asked to also report this issue here.

https://gitlab.gnome.org/GNOME/gnome-tweaks/-/issues/302#note_890687

**Comment by mtwebster** [comment]
Titlebar issue aside, why are you even running this in cinnamon?  It's only useful with gnome-shell.

**Comment by mtwebster** [comment]
Looks ok for me - this is Adwaita theme:

![image](https://user-images.githubusercontent.com/262776/90210725-c6602000-ddbc-11ea-854d-680de186b1af.png)

**Comment by silocoder** [comment]
I was desperate looking for someway to adjust scroll speed. Found a way, but is there an alternative to this I should be using? Does System Settings cover the same stuff? 

And I am also confused. What is Cinnamon based on? Is it now Gnome GTK? Thanks!

**Comment by mtwebster** [comment]
Cinnamon uses the same toolkits (for the most part) that gnome-shell uses, but the settings, while most are probably duplicate in function, are stored under a different path (for example, a given setting path might be org.gnome.desktop.interface.blah, but in cinnamon it starts with org.cinnamon, instead).  Assuming that program modifies dconf settings, it would be modifying things that cinnamon doesn't actually pay attention to.

Assuming you mean mouse or touchpad scroll speed, it doesn't look like that's currently configurable in cinnamon.  We can look into implementing that.

You won't do any harm trying to change things in that tweak tool - at worst it won't do anything.  I've never looked under its hood, and there are other ways to modify device behavior.  I'm not sure why you have the titlebar issue, but I assume the program still works.

**Comment by silocoder** [comment]
Would be nice if Cinnamon had smooth scrolling and mouse/trackpad scroll speed adjustments.  Now it is choppy. I am sure this is another major request. Especially trackpads and mouse like the Apple Magic Mouse which is what I am using. I read somewhere that smooth scrolling is being worked on. https://www.linux-magazine.com/Online/News/Linux-to-Get-High-Resolution-Wheel-Scrolling and https://who-t.blogspot.com/2020/04/high-resolution-wheel-scrolling-in.html Maybe you are aware of it.

**Comment by JosephMcc** [comment]
Closing this since it doesn't look like the actual issue is a problem.
