### ISSUE TITLE
Titlebar isnt effected by theme change and wrong plaicment of icons when plaiced on the left of window.

### ISSUE THREAD

**Issue by tetoNidan** [linuxmint/cinnamon#9522]
So the title pretty much explains it pretty well. The window titlebar that holds the close,maximize,minimize: the settings from themes wont change button color of close.
Also when moving the close,min,max icons to the left they are out of order. They should be close,maximum,minimum: to match the reverse of the icon in the theme icon. Taking the ability for us to choose was kind of a dick move!

Cinnamon Version: 4.6.7

No PPA added. Brand new install of Mint 20 64 bit yesterday.

Native GPU driver None installed.

```
 * Cinnamon version (cinnamon --version)
   - Please specify if you are using the daily builds PPA
     (https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds).
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
 * Graphics hardware *and* driver used
 * 32 or 64 bit
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
 ```

**Issue**

**Steps to reproduce**

**Expected behaviour**

**Other information**

**Configuration info, if applicable**
If this bug report is related to an Applet, Desklet or Extension, please paste (or use a pastebin service) the offending extension's settings, if it has any.  You can obtain this by opening its configuration, clicking the 'hamburger' button in the upper-right corner of the window, and selecting "Export to a file". **Please be sure to review the contents and remove any personal data it may contain.**

```

Please paste here

```

**Comment by mtwebster** [comment]
Use dconf-editor to change the layout:
![image](https://user-images.githubusercontent.com/262776/90282103-cf440680-de3b-11ea-8c13-d8bfca17753c.png)
We removed it because it was overkill for 99% of users.

The other issue you'll need to provide more specifics.  Pictures would be nice.

If you want to share your opinions of things we do, you can do it in a more civil manner, please.

**Comment by tetoNidan** [comment]
The min,max,close was a deal breaker! After 20 years of using linux and having the freedom to choose what was and has always been the exact reverse of the normal button layout mirrored perfectly for the left side! You basically broke 20 years of UI design in your convenience effort and made window basic memory action's impossible. That would have been enough to abandon cinnamon if it wasn't for the dconf hack.

Jumping through dconf is not the ease of use I would have hoped for but I'll take that as a hack over nothing.

The other issue I really dont care about that much TBH it was more of a heads up kind of thing.

**Comment by mtwebster** [comment]
So it sounds like you really would just like an additional preset (I've always used right-hand layout so I have no opinions on the left one).  I don't really have an issue adding that.  So close, maximize, minimize (left-to-right)?

Being able to have complete granular control over each button is the overkill part.  It wasn't about 'convenience' (notice we didn't actually remove the functionality), it was about what we feel is most useful to users.

**Comment by tetoNidan** [comment]
Yeah that's right. If you go to settings->Themes->Window Borders

There you will see the default from the dawn of time; well at least in every system Ive had since 2008. I use the logical mirrored reverse of that.

Once upon a time I would use gsettings set org.gnome.desktop.wm.preferences button-layout 'close,maximize,minimize:'

IMHO consistency is important and if your going to have icons shown a certain way in your settings and then not have the same behavior or even the ability to recreate the same behavior is extremely frustrating especially when you have had no issues changing these things in the past and have to my knowledge been close,max,min which is not only aesthetically pleasing but far more functional as the window manager remembers the windows size and the minimize button will be used far more frequently than the maximize button. And logically you want the close button to be as far from use as possible to prevent accidental closings. That leaves the least used maximize in the center.  

In fact one of the very things that sold me on cinnamon was the ability to just go into the settings and move these exact things around. Something that you had to have ccsm, gconf, etc for previously on most distros.
