### ISSUE TITLE
Remote access artefacts with Cinnamon on Manjaro

### ISSUE THREAD

**Issue by mozo78** [linuxmint/cinnamon#9528]
* Cinnamon version v.4.6.6
 * Distribution - (Manjaro Cinnamon)
 * Graphics hardware *and* driver used - Intel Graphics HD 2000, Mesa 20.1.3

Hello,
I have big problems with heavy artefacts when I access a computer with Cinnamon remotely, no matter VNC, TeamViever, AnyDesk, etc and it's nearly impossible to do any work. Actually it's a Manjaro installation but I think it's a problem with Cinnamon and that's why I ask here. If I install Linux Mint Cinnamon, there's no problems. What I'm missing? Here's a short video of the problem:

https://youtu.be/4TAMl1gD8Mo

Given we can't stop Muffin, the only solution I found is to uninstall video drivers and use CPU acceleration but it isn't very nice option you know.

**Steps to reproduce**
Start a remote session.

**Expected behaviour**
Smooth experience with no artefacts.

**Comment by icarter09** [comment]
Cinnamon 4.6.7
Mint 20 64bit

I've used VNC quite a bit with this machine and haven't experienced what your video was showing. Have you tried using another DE to see if the same problem appears? Thanks.

**Comment by mozo78** [comment]
Yes, the same is present in KDE. I found the problem though. Switched to uxa and everything is fine.

**Comment by claudiux** [comment]
@mozo78 Great! Can you close this issue, please?
