### ISSUE TITLE
Allow non-urgent notifications to be displayed over full screen apps

### ISSUE THREAD

**Issue by Snugface** [linuxmint/cinnamon#9529]
```
 * Cinnamon 4.6.7
 * Artix(Arch without systemd), last updated 08/16/2020
 * GeForce GTX 1050 Mobile; FOSS driver(mesa, xf86-video-nouveau)
 * 64 bit
 * No relevant errors present
 ```

**Issue**
Only urgent notifications are being displayed in full screen

**Steps to reproduce**
Start a fullscreen application; use notify-send to send non-urgent notifications like so:
`mplayer -fs "https://upload.wikimedia.org/wikipedia/commons/9/9e/0762_Spinning_Levers_04_45_20_00_3mb.webm"; sleep 10s; notify-send test`

**Expected behaviour**
Allow all notifications to be displayed over full screen apps by either:
 - Introducing a toggle option "Display only urgent notifications in fullscreen", that can be toggled off
 - Introducing an extension akin to Gnome's [Fullscreen Notifications](https://extensions.gnome.org/extension/1610/fullscreen-notifications/)

**Other information**
Please! It's a disaster. There are so many applications that produce non-urgent notifications. And I spend so much time in fullscreen; not seeing notifications is troublesome.
And this seems to stretch quite far back; as far as 2012 it seems. The emphasis was mostly on low-battery warnings. Which are now, thanks to you, addressed.
But it would be great just to have a single simple option that would allow to control this behavior.

**Comment by ItzSwirlz** [comment]
Okay is this a feature request? I'm sure this could be part of customization or extra configuration.

And there is no need to call this a disaster. If it's non-urgent then it's intended but if it's classified as non-urgent when it IS urgent then bring it up here.

**Comment by Snugface** [comment]
It is a feature request, yes.
Unfortunately I found no way to add the corresponding label to it.

And it is not an urgent matter, nor is it something critical.
Though it would be nice to get this implemented soon

**Comment by Ammako** [comment]
I want this. Doesn't seem excessively difficult to implement, so I'm going to look into it.

If one really needs this right now, a quick and dirty fix is to edit `/usr/share/cinnamon/js/ui/messageTray.js#L1047` changing `false` to `true`. It'll get overwritten with Cinnamon updates, but at least it'll work until a proper option can be added.

**Comment by Snugface** [comment]
Much obliged for the quickfix offered.
I got used to this over time, but nevertheless - I am pleased to see someone else who regards this as an actual issue.

**Comment by Ru-Tao** [comment]
> If one really needs this right now, a quick and dirty fix is to edit `/usr/share/cinnamon/js/ui/messageTray.js#L1047` changing `false` to `true`. It'll get overwritten with Cinnamon updates, but at least it'll work until a proper option can be added.

Has the line changed since? It's been almost 3 years since this reply, and I can't seem to find what to change, help would be greatly appreciated. 

Cinnamon 6.0.4

**Comment by Ru-Tao** [comment]
Never mind, it looks like the line number has changed to ```/usr/share/cinnamon/js/ui/messageTray.js#L1012```.
The line itself is 
```Main.layoutManager._chrome.modifyActorParams(this._notificationBin, { visibleInFullscreen: false });``` 
if it changes again anytime in the future.

**Comment by rcalixte** [comment]
Has anyone here found an application or browser where the notifications didn't show over them in fullscreen? In my testing, I've had inconsistent results with Chromium but other browsers have been better (Firefox, LibreWolf, Vivaldi, etc.)
