### ISSUE TITLE
windows settings - please bring back menu button in windows title

### ISSUE THREAD

**Issue by oldtomdevel** [linuxmint/cinnamon#9539]
In Cinnamon 4.2.4 for LM19.2 the window settings allowed to choose quite freely which buttons I prefer in the windows title bar. It was possible to distribute buttons for menu, minimize, maximize, close, fixing and roll in/out on the left or on the right of the title bar.
Now, in Cinnamon 4.6.6 for LM20, the possibilities are unfortunately much more restricted. I can now choose between certain pre-defined orders only, namely right, left, Gnome and Mac. But non of those orders contains a button for the windows menu. I always used a theme that included a button for the window menu and I used that button often. When I try to use my old theme in LM20, the button for the windows menu is just not shown.
As I cannot see a reason for that restriction, I would like to suggest that Cinnamon comes back to the possibilities of Cinnamon 4.2.4. so that I can have more buttons in the windows title bar than just for minimize, maximize and close.

**Comment by smurphos** [comment]
Hi @oldtomdevel, pending any response from the team you can still make customised button layouts via the command line or with dconf-editor e.g to have the menu button on the left and minimise, maximise and close on the right

`dconf write /org/cinnamon/desktop/wm/preferences/button-layout "'menu:minimize,maximize,close'"`

**Comment by JosephMcc** [comment]
You can use the method shown by smurphos above for now but I don't think those options are coming back in the gui.
