### ISSUE TITLE
Sub menu shows all items

### ISSUE THREAD

**Issue by zfr77** [linuxmint/cinnamon#9546]
* Cinnamon version (cinnamon --version)
Cinnamon 4.4.8

 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
Linux Mint 19.3 Tricia

 * Graphics hardware *and* driver used
GeForce GTX 970
Driver Version: 450.66
64 bit

**Issue**
Going immediately (or very quickly) to a submenu after the Menu is opened causes all items to be displayed there.
(See attached screenshot)

**Steps to reproduce**
- Place mouse pointer at the location where the submenu (any submenu: Accesories, Games, Administration, Preferences... etc) is located when the menu is opened.
- Press the windows button to have the menu appear
- The menu will appear, and if your pointer is in the right position, the submenu should be opened. Except that it will have all items listed.

**Expected behaviour**
Only the sub menu items should be displayed.

![menu](https://user-images.githubusercontent.com/29925765/91451256-2783fb00-e875-11ea-8c32-305fae1deac0.png)

**Comment by smurphos** [comment]
This can be reproduced on Current Cinnamon 4.6.7

**Comment by icarter09** [comment]
Tested and verified that PR does resolve this issue.

**Comment by zfr77** [comment]
Thanks.
