### ISSUE TITLE
Unexpected logout in Cinnamon

### ISSUE THREAD

**Issue by haggen88** [linuxmint/cinnamon#9549]
```
Linux Mint 20  x86_64
Cinnamon 4.6.7
Kernel: 5.4.0-42-generic 
No daily builds PPA
Graphics:  Device-1: Intel 3rd Gen Core processor Graphics vendor: Dell driver: i915 v: kernel 
           bus ID: 00:02.0 chip ID: 8086:0166 
           Display: x11 server: X.Org 1.20.8 driver: modesetting unloaded: fbdev,vesa 
           resolution: 1366x768~60Hz 
           OpenGL: renderer: Mesa DRI Intel HD Graphics 4000 (IVB GT2) v: 4.2 Mesa 20.0.8 
           compat-v: 3.0 direct render: Yes 

 ```
**Issue**

I have experienced at least 4 unexpected Linux Mint session crashes in the last month.
The first 3 were while watching some videos from Firefox [I thought that Firefox 79/80 was bugging the session],
and the last one was while looking for a file in Nemo. I have no problems with memory shortage or processor overload.
The last error occurred at 15:30.

xsession-errors:          https://pastebin.com/10VP9YZz
xsession-errors.old :   https://pastebin.com/EpPAb33c
system logs:                https://pastebin.com/JF0CTvzh

**Comment by icarter09** [comment]
@haggen88 are you able to provide any steps to reproduce this issue? I've tried watching some videos in Firefox, but have not experienced any unexpected logouts. Thanks.

**Comment by haggen88** [comment]
The problem occurred randomly. I cannot establish more precisely the conditions in which this bug is generated. The problem is not Firefox, other times it happened to me after performing maintenance with BleachBit 4.0.

Currently I use kernel 5.4.0-48 and Cinnamon 4.6.7 and [for now] I have not had this problem again.

**Comment by haggen88** [comment]
I just had another unexpected shutdown after cleaning my system with BleachBit ... I suspect that cleaning the languages ["Localizations"] causes the problem.

![q](https://user-images.githubusercontent.com/68134588/102933811-c31f2400-4481-11eb-95ca-c8cda112b86d.png)

Currently I use kernel 5.8.0-33-generic and cinnamon 4.6.7

**Comment by haggen88** [comment]
I upgraded to BleachBit 4.4.2 [Mint 20.2/Kernel 5.13] and have not had this bug again.
I proceed to close it

**Comment by haggen88** [comment]
I upgraded to BleachBit 4.4.2 [Mint 20.2/Kernel 5.13] and have not had this bug again.
I proceed to close it
