### ISSUE TITLE
Random freezes in Mint 19.3

### ISSUE THREAD

**Issue by RagnarAsm** [linuxmint/cinnamon#9551]
System reports: https://termbin.com/yccm
[crash.tar.gz](https://github.com/linuxmint/cinnamon/files/5146757/crash.tar.gz)

We experience random crashes on a new desktop AMD Ryzen-Radeon CPU. Usually, the graphics freeze up and keyboard always freezes. Mouse pointer can often move but is inactive. Most of the time, the platform works well but this freezing cannot be linked with any specific process, and occurs sometimes with days apart or twice a day.

We include reports from your 'System Reports' program, see links above. Can you see what is wrong?

Best regards, Ragnar

**Comment by Behoston** [comment]
Same with Radeon 5700XT and Ryzen 3600 on Mint 20. 
Similar issues:
https://github.com/linuxmint/cinnamon/issues/3275
https://github.com/linuxmint/cinnamon/issues/2946
https://github.com/linuxmint/cinnamon/issues/8861
but still no fix :-1:

**Comment by icarter09** [comment]
Have either you upgraded to Mint 20? If so, have you experienced the problem there as well? Thanks.

**Comment by RagnarAsm** [comment]
Still 19.3 here, but original reply (Mateusz) indicates he tried Mint 20
also with same problem. Thank you for looking into this.

fös., 2. okt. 2020 kl. 03:09 skrifaði Isaac Carter <notifications@github.com

**Comment by Behoston** [comment]
Yup, clean install of 20 and same problem. On mate i noticed problem only
once (mate installed on 20 cinnamon, maybe on 20 mate will be 100% ok).
Problem appears mostly on Google maps

sob., 3.10.2020, 12:06 użytkownik RagnarAsm <notifications@github.com>
napisał:

**Comment by icarter09** [comment]
Thanks. Can you either of you provided the steps to produce (if there are any)? Thanks.

**Comment by MhSav** [comment]
I have this problem after switching user - keyboard not responding, mouse only moving, no button click response.
But it appears randomly, not after each user switching.
Also, after user logout from all sessions there are staying processes running under this user.

**Comment by Behoston** [comment]
I have good news. On mate we have same problem but less often :P
We found solution - install radeon drivers from AMD website and problem gone (works since 2 weeks).
On kernel 5.8 you will have new AMD driver integrated, it also may fix the problem.

**Comment by RagnarAsm** [comment]
Hi all - you were correct. It was sufficient to upgrade from Mint 19 to 20
with kernel 5.4.0-53 - I assume an AMD radeon driver update was included in
that upgrade. Great news - desktop has been running non-stop for over two
weeks now.

þri., 27. okt. 2020 kl. 16:59 skrifaði Mateusz Legięcki <
notifications@github.com>:

**Comment by dandv** [comment]
> Usually, the graphics freeze up and keyboard always freezes. Mouse pointer can often move but is inactive.

How long are these freezes? Short stutters like in #9628, or longer?

**Comment by RagnarAsm** [comment]
Freezes were Lee permanent. Note that issue is now permanently resolved
with the upgrade.


Þann sun., 24. jan. 2021, 04:37 Dan Dascalescu skrifaði <
notifications@github.com>:
