### ISSUE TITLE
Bluetooth dialog does not folllow themes>window borders

### ISSUE THREAD

**Issue by kbmaniac** [linuxmint/cinnamon#9555]
```
 * Cinnamon version (cinnamon --version)
   - Please specify if you are using the daily builds PPA
     (https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds).
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
 * Graphics hardware *and* driver used
 * 32 or 64 bit
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
 ```

**Issue**
The Bluetooth dialog does not folllow themes>window borders

**Steps to reproduce**
Set theme > window borders to mint-X
Open the bluetooth dialogue

**Expected behaviour**
The bluetooth dialogue to follow the system theme for window borders

**Other information**

**Configuration info, if applicable**
If this bug report is related to an Applet, Desklet or Extension, please paste (or use a pastebin service) the offending extension's settings, if it has any.  You can obtain this by opening its configuration, clicking the 'hamburger' button in the upper-right corner of the window, and selecting "Export to a file". **Please be sure to review the contents and remove any personal data it may contain.**

```

Please paste here

```

**Comment by JosephMcc** [comment]
On windows like the bluetooth app the window borders are drawn by the Gtk (controls) theme so changing the window border theme has no effect. More and more applications are going that direction and at some point that ability to set a separate window border theme will likely go away in Cinnamon.

**Comment by sirnacnud** [comment]
This is still the case with the bluetooth app. The fix is to change Themes->Controls to match the theme selected for Window borders, then the bluetooth app will draw the window border correctly.
