### ISSUE TITLE
Feature Request: Replace Reboot with Restart in Update Tool or Menu

### ISSUE THREAD

**Issue by ashleybarz** [linuxmint/cinnamon#9561]
I've installed Linux Mint and helped guide a few people on how to use it initially. They're using Cinnamon and both my friends have asked the same question. How do I reboot? Where is the reboot button, not understanding the restart and reboot are interchangeable. Would it all be possible to have a more consistent indication of what is to be done after updates are complete?

**Comment by NikoKrause** [comment]
https://www.lifewire.com/reboot-vs-reset-4157868
