### ISSUE TITLE
[Feature request] An easy to use GUI task scheduler

### ISSUE THREAD

**Issue by grenvol** [linuxmint/cinnamon#9566]
The Cinnamon desktop environment lacks a task scheduler.

It's a modern and basic feature that is present in most serious desktop environments like Windows. Cinnamon should definitely add it, especially If It wants to cater to ex-Windows users. It also makes administrating a lot easier

**Comment by MegaV0lt** [comment]
I suggest to add an Button "Taskmanager" in the Crtl-Alt-Del Dialog:
![image](https://user-images.githubusercontent.com/2804301/93076231-511b8f80-f687-11ea-8eaf-37f0a51ac739.png)

The Button then can call the system task manager app.

Bonus: It should be configurable somwhere

**Comment by Odyseus** [comment]
Hello, everybody.

@MegaV0lt: **grenvol** is talking about a task **scheduler** ([see image](https://user-images.githubusercontent.com/3822556/93113645-d3a84d00-f68f-11ea-9f40-48f7162b8486.png)), not a task **manager**.

**Comment by JosephMcc** [comment]
We have no current plans for something like this that I know of. Even if we did it is an application, not really part of Cinnamon and would be better as an XApp for use with any desktop environment.
