### ISSUE TITLE
Panel sometimes shows only app(s) related to a workspace that I'm not using at the moment

### ISSUE THREAD

**Issue by curtisgibby** [linuxmint/cinnamon#9567]
```
 * cinnamon-control-center version 4.6.2
 * Distribution - Mint 20.0
 * Graphics hardware - Intel Corporation HD Graphics 630
 * 64 bit
 ```

**Issue**

Panel sometimes shows only the app(s) related to a workspace that I'm not using at the moment. That is, I'll be in Workspace 1, but the Panel will show the app(s) that I've got open in Workspace 2. This happens several times a day since I upgraded to Mint 20 from Mint 17, where I never saw this problem.

(Updated with an example screenshot below)

**Steps to reproduce**

Unknown.

**Expected behavior**

Panel shows the app(s) related to a workspace that I'm using at the moment.

**Other information**

To get out of this behavior, I have to switch to the workspace containing the apps that I'm currently seeing in the Panel (Workspace 2), then back to the original desktop (Workspace 1).

**Comment by icarter09** [comment]
@curtisgibby any luck on figuring on the steps to reproduce this?

**Comment by curtisgibby** [comment]
Nope, it's sporadic. The next time I see this behavior, I'll definitely try to figure out what I was doing just beforehand.

**Comment by curtisgibby** [comment]
One other interesting note that may help diagnose the problem: every time the "wrong" workspace's apps show up, they're always from the _same_ wrong workspace.

- Workspace 1 sometimes shows Workspace 2's panels
- Workspace 3 sometimes shows Workspace 2's panels
- Workspace 1 _never_ shows Workspace 3's panels
- Workspace 3 _never_ shows Workspace 1's panels

**Comment by TechnologyMan101** [comment]
It happened to me only once and I was deliberately lagging out the computer by switching workspaces rapidly for a while.

**Comment by curtisgibby** [comment]
@ronyala I think your conjecture is correct -- the problem does appear to be caused by rapidly jumping back and forth between workspaces. I can never get it to occur if I slow down my shortcut keypresses to trigger "Switch to Left Workspace" / "Switch to Right Workspace", but I can consistently make it happen if I push `Ctrl+Alt+Left` or `Ctrl+Alt+Right` more than once in rapid succession. Good detective work! :detective:

**Comment by curtisgibby** [comment]
Glad to see it fixed! Any idea when it might land?
