### ISSUE TITLE
Cinnamon crashes when changing task bar to show text next to icon

### ISSUE THREAD

**Issue by CWM030** [linuxmint/cinnamon#9570]
```
 * Cinnamon version 4.48
   - Please specify if you are using the daily builds PPA NO.
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) OPEN SUSE
 * Graphics hardware *and* driver used
CPU: Intel i5 670 (4) @ 3.459GHz 
                                                       GPU: Intel Core Processor 
                                                       Memory: 1935MiB / 7746MiB 

 * 32 or 64 bit ---- 64 bit



 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
 ```
No protocol specified
gpg-connect-agent: no gpg-agent running in this session
gpg-connect-agent: no gpg-agent running in this session
No protocol specified
No protocol specified
gnome-keyring-daemon: insufficient process capabilities, insecure memory might get used
gnome-keyring-daemon: insufficient process capabilities, insecure memory might get used
gnome-keyring-daemon: insufficient process capabilities, insecure memory might get used
No protocol specified
No protocol specified
No protocol specified
No protocol specified
No protocol specified
No protocol specified
No protocol specified
No protocol specified
No protocol specified
No protocol specified
No protocol specified
No protocol specified
No protocol specified
No protocol specified
No protocol specified
No protocol specified
No protocol specified
No protocol specified
No protocol specified
No protocol specified
No protocol specified
No protocol specified
No protocol specified
No protocol specified
No protocol specified
No protocol specified
No protocol specified
No protocol specified
No protocol specified
No protocol specified
No protocol specified
No protocol specified
No protocol specified
No protocol specified
No protocol specified
No protocol specified
No protocol specified
No protocol specified
No protocol specified
[cinnamon-settings-daemon-smartcard] Failed to start: no suitable smartcard driver could be found
No protocol specified
No protocol specified
No protocol specified
[cinnamon-settings-daemon-smartcard] Failed to start: no suitable smartcard driver could be found
No protocol specified
No protocol specified
No protocol specified
No protocol specified
Cinnamon warning: Log level 128: unsetenv() is not thread-safe and should not be used after threads are created
No protocol specified
No protocol specified
Tracker-Message: 18:26:49.443: Set scheduler policy to SCHED_IDLE
Tracker-Message: 18:26:49.443: Set scheduler policy to SCHED_IDLE
Tracker-Message: 18:26:49.443: Setting priority nice level to 19
Tracker-Message: 18:26:49.443: Setting priority nice level to 19
No protocol specified
No protocol specified
No protocol specified
Clutter-Message: 18:26:49.514: Sync method: PRESENTATION TIME
No protocol specified
No protocol specified
No protocol specified
No protocol specified

** (nemo-desktop:28575): WARNING **: 18:26:49.685: Current gtk theme is not known to have nemo support (Menta) - checking...
No protocol specified
No protocol specified
No protocol specified
No protocol specified
Cjs-Message: 18:26:49.936: JS LOG: About to start Cinnamon
No protocol specified
** Message: 18:26:49.995: nemo-desktop: session is cinnamon, establishing proxy
No protocol specified
Cjs-Message: 18:26:50.020: JS LOG: [LookingGlass/info] Cinnamon.AppSystem.get_default() started in 83 ms
Cjs-Message: 18:26:50.027: JS LOG: [LookingGlass/info] loading user theme: /usr/share/themes/Mint-Y-Dark-Blue/cinnamon/cinnamon.css
Cjs-Message: 18:26:50.043: JS LOG: [LookingGlass/info] added icon directory: /usr/share/themes/Mint-Y-Dark-Blue/cinnamon

(tracker-miner-fs:28571): Tracker-CRITICAL **: 18:26:50.085: Could not request DBus name 'org.freedesktop.Tracker1.Miner.Files': D-Bus service name:'org.freedesktop.Tracker1.Miner.Files' is already taken, perhaps the application is already running?
Cinnamon warning: Log level 128: posix_spawn avoided (fd close requested) 
Cjs-Message: 18:26:50.328: JS LOG: [LookingGlass/info] PlacesManager: Updating devices
Cjs-Message: 18:26:50.343: JS LOG: [LookingGlass/info] loaded at Thu Sep 10 2020 18:26:50 GMT-0500 (CDT)
Cjs-Message: 18:26:50.343: JS LOG: Cinnamon started at Thu Sep 10 2020 18:26:50 GMT-0500 (CDT)
Cjs-Message: 18:26:50.354: JS LOG: [LookingGlass/info] ExtensionSystem started in 1 ms
Cjs-Message: 18:26:50.354: JS LOG: [LookingGlass/info] DeskletManager started in 1 ms
Cjs-Message: 18:26:50.354: JS LOG: [LookingGlass/info] SearchProviderManager started in 1 ms
openGL version 2.1 Mesa 20 detected (GL Cogl Driver)
MetaSyncRing disabled: couldn't find required GL extensions, or the minimum safe openGL version was not met
Cjs-Message: 18:26:50.494: JS LOG: [LookingGlass/info] Loaded applet calendar@cinnamon.org in 99 ms
Cjs-Message: 18:26:50.521: JS LOG: [LookingGlass/info] Loaded applet show-desktop@cinnamon.org in 27 ms
Cjs-Message: 18:26:50.529: JS LOG: [LookingGlass/info] Loaded applet separator@cinnamon.org in 8 ms
Cjs-Message: 18:26:50.540: JS LOG: [LookingGlass/info] Loaded applet removable-drives@cinnamon.org in 11 ms
Cjs-Message: 18:26:50.570: JS LOG: [LookingGlass/info] Loaded applet keyboard@cinnamon.org in 30 ms
St-Message: 18:26:50.579: cogl npot texture sizes SUPPORTED
Cjs-Message: 18:26:50.592: JS LOG: [LookingGlass/info] Loaded applet workspace-switcher@cinnamon.org in 22 ms
Cjs-Message: 18:26:50.600: JS LOG: [LookingGlass/info] Loaded applet xapp-status@cinnamon.org in 7 ms
Cjs-Message: 18:26:50.609: JS LOG: [LookingGlass/info] Role locked: notifications
Cjs-Message: 18:26:50.635: JS LOG: [LookingGlass/info] Loaded applet notifications@cinnamon.org in 35 ms
Cjs-Message: 18:26:50.642: JS LOG: [LookingGlass/info] Role locked: tray
Cjs-Message: 18:26:50.646: JS LOG: [LookingGlass/info] Loaded applet systray@cinnamon.org in 11 ms
Cinnamon warning: Log level 128: posix_spawn avoided (automatic reaping requested) (fd close requested) 
Cjs-Message: 18:26:50.677: JS LOG: [LookingGlass/info] Loaded applet printers@cinnamon.org in 31 ms
Cjs-Message: 18:26:50.720: JS LOG: [LookingGlass/info] Loaded applet power@cinnamon.org in 42 ms
Cjs-Message: 18:26:50.759: JS LOG: [LookingGlass/info] Role locked: panellauncher
Cjs-Message: 18:26:50.763: JS LOG: [LookingGlass/info] Loaded applet grouped-window-list@cinnamon.org in 43 ms

(csd-power:28469): power-plugin-CRITICAL **: 18:26:50.807: abs_to_percentage: assertion 'max > min' failed
Cjs-Message: 18:26:50.857: JS LOG: [LookingGlass/info] Loaded applet sound@cinnamon.org in 94 ms
Cjs-Message: 18:26:50.879: JS LOG: [LookingGlass/info] Loaded applet network@cinnamon.org in 22 ms
Cjs-Message: 18:26:51.167: JS LOG: [LookingGlass/info] Loaded applet menu@cinnamon.org in 288 ms
Cjs-Message: 18:26:51.168: JS LOG: [LookingGlass/info] AppletManager started in 825 ms
Cjs-Message: 18:26:51.173: JS LOG: [LookingGlass/info] Cinnamon took 1237 ms to start
Cinnamon warning: Log level 128: posix_spawn avoided (automatic reaping requested) (fd close requested) 
Cjs-Message: 18:26:51.220: JS LOG: Unknown network device type, is 14
Cinnamon warning: Log level 128: posix_spawn avoided (automatic reaping requested) (fd close requested) 
Cjs-Message: 18:26:51.495: JS LOG: [LookingGlass/info] Adding systray: flameshot (24x24px)
Cjs-Message: 18:26:51.496: JS LOG: [LookingGlass/info] Resized flameshot with normalized size (24x24px)
Cinnamon warning: Log level 128: posix_spawn avoided (automatic reaping requested) (fd close requested) 
Cinnamon warning: Log level 128: posix_spawn avoided (automatic reaping requested) (fd close requested) 
No protocol specified
No protocol specified
Cjs-Message: 18:26:54.339: JS LOG: [LookingGlass/info] Hiding systray: network
No protocol specified
No protocol specified
No protocol specified
No protocol specified
cinnamon-session[28375]: WARNING: t+6.97435s: Detected that screensaver has appeared on the bus
No protocol specified
No protocol specified
error: : cannot open
error: : cannot open
error: : cannot open
Cjs-Message: 18:26:57.561: JS LOG: [LookingGlass/info] Adding systray: telegramdesktop (24x24px)
Cjs-Message: 18:26:57.562: JS LOG: [LookingGlass/info] Resized telegramdesktop with normalized size (24x24px)
No protocol specified
No protocol specified
No protocol specified
No protocol specified
[28777:28777:0910/182826.792626:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.
[28779:28796:0910/182827.346079:ERROR:nss_util.cc(283)] After loading Root Certs, loaded==false: NSS error code: -8018
Fontconfig error: Cannot load default config file: No such file: (null)
[0910/183028.496429:ERROR:nacl_helper_linux.cc(308)] NaCl helper process running without a sandbox!
Most likely you need to configure your SUID sandbox correctly
No protocol specified
No protocol specified
No protocol specified
No protocol specified
[29256:29256:0910/183030.791261:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.
[29259:29270:0910/183031.333753:ERROR:nss_util.cc(283)] After loading Root Certs, loaded==false: NSS error code: -8018
No protocol specified
No protocol specified
No protocol specified
No protocol specified
[0910/183144.220111:ERROR:nacl_helper_linux.cc(308)] NaCl helper process running without a sandbox!
Most likely you need to configure your SUID sandbox correctly
Cinnamon warning: Log level 128: posix_spawn avoided (fd close requested) 
No protocol specified
No protocol specified
No protocol specified
No protocol specified
No protocol specified
No protocol specified

**Issue**
Cinnamon crashes when changing task bar to show text next to icon

**Steps to reproduce**
Right click a icon on your tool bar.. Go to preferences, configure, panel, and change the 1st toggle box to say APPLICATION NAME

**Expected behaviour**
 The tool bar changes the buttons only to show application name but the tool bar freezes up and you cannot click on anything no buttons on the tool bar, start menu is dead but the clock is still keeping up with time. I had to ctrl alt backspace and re log in to get a perfect working system. 

**Other information**

**Configuration info, if applicable**
If this bug report is related to an Applet, Desklet or Extension, please paste (or use a pastebin service) the offending extension's settings, if it has any.  You can obtain this by opening its configuration, clicking the 'hamburger' button in the upper-right corner of the window, and selecting "Export to a file". **Please be sure to review the contents and remove any personal data it may contain.**

```

Please paste here

```

**Comment by icarter09** [comment]
Cinnamon 4.6.7
Mint 20 64bit

I'm not able to reproduce this issue. Changed the setting to `Application name`. Everything still worked fine.
