### ISSUE TITLE
Can't seem to edit settings for Screenshot grabber (e.g. "include pointer" and default save path)

### ISSUE THREAD

**Issue by teo1978** [linuxmint/cinnamon#9575]
I report this here because there's no "Issues" tab in https://github.com/linuxmint/gnome-screenshot

If I run gnome-screenshot from scratch (as opposed to using the keyboard shortcuts), there's a nice checkbox that says "include pointer". I want that to be checked by default, so that, when I take a screenshot using the PrintScreen key or a cropped screenshot with shift+PrintScreen, the pointer is included. In general I always want the pointer in my screenshot (I would even argue that that should be the default).

However, that is not remembered. After I use that once, nex time I take a screenshot with the keyboard shortcuts, it will not include the pointer. And next time I run Screenshot from scratch, the checkbox won't be selected.

So the next step is to look for a setting, but nowhere in the application's window can I find any link to any kinf of settings. Either this application doesn't have any settings (which would be stupid, there are lots of things you should be able to configure; this is one, another is the default folder to save screenshots to), or it lacks a discoverable access to them. Usually applications have a main menu, and somewhere in some of the menus there's a "Preferences" or "Settings" item. I see none of these in Screenshot.

Hopefully there does exist some place where these settings are defined, such as a configuration file that one can edit, or using another system-wide application to change system settings, but either way I should be able to find them through the application.

**Comment by icarter09** [comment]
@teo1978 Try using `dconf-editor` to change the settings for `org.gnome.gnome-screenshot`.

**Comment by teo1978** [comment]
Why have you closed this?

Such basic settings should be accessible through the application's interface in an easy, user-friendly, discoverable and error-safe way. You know, like settings of usable applications.

**Comment by leigh123linux** [comment]
> Why have you closed this?
> 
> Such basic settings should be accessible through the application's interface in an easy, user-friendly, discoverable and error-safe way. You know, like settings of usable applications.

I agree,  you file the issue against the offending program.

https://gitlab.gnome.org/GNOME/gnome-screenshot/-/issues

**Comment by NikoKrause** [comment]
Hey, sorry for not mentioning it. GNOME is hosting they're project on Gitlab. See link above.
Also this issue has been labeled with "CLOSE IF NO RESPONSE". There was no response for over a month. Closed the issue. Boom. Response within a month. Anyway. There's nothing, what we can do here anyway, since the screenshot tool is not a Mint project, but a GNOME project.

**Comment by teo1978** [comment]
Doesn't Mint maintain a forked version? https://github.com/linuxmint/gnome-screenshot

I remember installing it because it had some issue fixed, I don't remember which one. 

I gave up reporting upstream issues to Gnome long ago, it's a waste of time.

Anyway I'm no longer using Cinnamon either.

**Comment by NikoKrause** [comment]
I think it's not actively mainted. It's just the upstream app with a few mint patches. It's not a real fork like xed or xreader, which have a different design & features in mind. The gnome screenshot stays as close as possible to upstream. It doesn't implement new features.
