### ISSUE TITLE
Cinnamon 4.6.7 - Unable to access applets server

### ISSUE THREAD

**Issue by IvoAndonov** [linuxmint/cinnamon#9577]
* Cinnamon version - 4.6.7
  IDK what a daily build is. I use whatever comes from Arch repos.
 * Distribution - Arch.
 * Graphics hardware *and* driver used GTX 1050 Ti, 450.66
 * 64 bit
  
[xsession-errors.txt](https://github.com/linuxmint/cinnamon/files/5215085/xsession-errors.txt)

**Issue**
For a few days when I try to refresh cache of applets I get this message saying something like "Unable to connect to the server, please try again later. Details:" but no details are actually written.

**Steps to reproduce**
Right click on the panel, click on "applets" and go to "download" tab to get the note that the cache is old and needs to be refreshed. Confirm to refresh it and almost instantly you'll see the message it can't connect to the server.

**Expected behaviour**
Refreshing cache should work, giving access to the list of available applets.

**Other information**
I tried changing the mirror to something else, hoping that this would fix this problem, but that changed nothing - I'm still unable to connect to the applets server (I think the name of that server was cinnamon spices or smth).
I also searched on the internet and it seems other people had the same problem in 2018 but unfortunately their solution didn't fix it for me. One of the users there said (back in 2018) that nobody's using Python version higher than 3.8.3. But my python version is 3.8.5 which could be the cause of the problem. Unfortunately I know nothing of programming or python, so IDK what to do to fix it for myself.

**Comment by IvoAndonov** [comment]
Nvm, I found out why it won't connect. You can delete this issue.

**Comment by Fjodor42** [comment]
Incidentally, I cannot connect either, which has worked fine up until I tried yesterday (cannot remember the last time I refreshed the cache, though).

Could I ask you what was wrong in your case, @IvoAndonov?

**Comment by IvoAndonov** [comment]
> Incidentally, I cannot connect either, which has worked fine up until I tried yesterday (cannot remember the last time I refreshed the cache, though).
> 
> Could I ask you what was wrong in your case, @IvoAndonov?

Ofc. It turns out that they're migrating cinnamon spices to a new server and will be online some time next week. If you open cinnamon spices in the browser, you'll see a nearly emptiy website. After clicking on "Applets" you'll see the message that they're moving to a new server. That's why we can't connect. And that's why I closed the issue with a note that it can be deleted. ;)
