### ISSUE TITLE
linux mint laptop bug report daemon crashing and same is my HP desktop 

### ISSUE THREAD

**Issue by freddylupin** [linuxmint/cinnamon#9587]
===================================================================
 Info                                                              
===================================================================
           PID: 1194 (csd-automount)
           UID: 1000 (snowden)
           GID: 1000 (snowden)
        Signal: 11 (SEGV)
     Timestamp: Sat 2020-09-05 02:46:39 EEST (1 weeks 6 days ago)
  Command Line: /usr/lib/x86_64-linux-gnu/cinnamon-settings-daemon/csd-automount
    Executable: /usr/lib/x86_64-linux-gnu/cinnamon-settings-daemon/csd-automount
 Control Group: /user.slice/user-1000.slice/session-c2.scope
          Unit: session-c2.scope
         Slice: user-1000.slice
       Session: c2
     Owner UID: 1000 (snowden)
       Boot ID: 97cc051eeee9437bab5710775c6636b2
    Machine ID: b76cc7b1bbdc489e93909d2043031de8
      Hostname: snowden-E402SA
       Storage: /var/lib/systemd/coredump/core.csd-automount.1000.97cc051eeee9437bab5710775c6636b2.1194.1599263199000000000000.lz4
       Message: Process 1194 (csd-automount) of user 1000 dumped core.
                
                Stack trace of thread 1194:
                #0  0x000055bbf324c430 n/a (csd-automount + 0x6430)
                #1  0x00007f8bdcc4ba28 n/a (libglib-2.0.so.0 + 0x52a28)
                #2  0x00007f8bdcc4ae8e g_main_context_dispatch (libglib-2.0.so.0 + 0x51e8e)
                #3  0x00007f8bdcc4b240 n/a (libglib-2.0.so.0 + 0x52240)
                #4  0x00007f8bdcc4b533 g_main_loop_run (libglib-2.0.so.0 + 0x52533)
                #5  0x00007f8bdd2e037d gtk_main (libgtk-3.so.0 + 0x24e37d)
                #6  0x000055bbf324b947 n/a (csd-automount + 0x5947)
                #7  0x00007f8bdc8f10b3 __libc_start_main (libc.so.6 + 0x270b3)
                #8  0x000055bbf324baae n/a (csd-automount + 0x5aae)
                
                Stack trace of thread 1243:
                #0  0x00007f8bdc9df96f __GI___poll (libc.so.6 + 0x11596f)
                #1  0x00007f8bdcc4b1ae n/a (libglib-2.0.so.0 + 0x521ae)
                #2  0x00007f8bdcc4b533 g_main_loop_run (libglib-2.0.so.0 + 0x52533)
                #3  0x00007f8bdcea2eda n/a (libgio-2.0.so.0 + 0x11eeda)
                #4  0x00007f8bdcc74931 n/a (libglib-2.0.so.0 + 0x7b931)
                #5  0x00007f8bdc129609 start_thread (libpthread.so.0 + 0x9609)
                #6  0x00007f8bdc9ec103 __clone (libc.so.6 + 0x122103)
                
                Stack trace of thread 1252:
                #0  0x00007f8bdc9df96f __GI___poll (libc.so.6 + 0x11596f)
                #1  0x00007f8bdcc4b1ae n/a (libglib-2.0.so.0 + 0x521ae)
                #2  0x00007f8bdcc4b2e3 g_main_context_iteration (libglib-2.0.so.0 + 0x522e3)
                #3  0x00007f8bd9fb099d n/a (libdconfsettings.so + 0xa99d)
                #4  0x00007f8bdcc74931 n/a (libglib-2.0.so.0 + 0x7b931)
                #5  0x00007f8bdc129609 start_thread (libpthread.so.0 + 0x9609)
                #6  0x00007f8bdc9ec103 __clone (libc.so.6 + 0x122103)
                
                Stack trace of thread 1241:
                #0  0x00007f8bdc9df96f __GI___poll (libc.so.6 + 0x11596f)
                #1  0x00007f8bdcc4b1ae n/a (libglib-2.0.so.0 + 0x521ae)
                #2  0x00007f8bdcc4b2e3 g_main_context_iteration (libglib-2.0.so.0 + 0x522e3)
                #3  0x00007f8bdcc4b331 n/a (libglib-2.0.so.0 + 0x52331)
                #4  0x00007f8bdcc74931 n/a (libglib-2.0.so.0 + 0x7b931)
                #5  0x00007f8bdc129609 start_thread (libpthread.so.0 + 0x9609)
                #6  0x00007f8bdc9ec103 __clone (libc.so.6 + 0x122103)
===================================================================
 GDB Log                                                           
===================================================================
[New LWP 1194]
[New LWP 1243]
[New LWP 1252]
[New LWP 1241]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/lib/x86_64-linux-gnu/cinnamon-settings-daemon/csd-automount'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000055bbf324c430 in ?? ()
[Current thread is 1 (Thread 0x7f8bdb853a80 (LWP 1194))]

===================================================================
 GDB Backtrace                                                     
===================================================================
[New LWP 1194]
[New LWP 1243]
[New LWP 1252]
[New LWP 1241]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/lib/x86_64-linux-gnu/cinnamon-settings-daemon/csd-automount'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000055bbf324c430 in ?? ()
[Current thread is 1 (Thread 0x7f8bdb853a80 (LWP 1194))]
#0  0x000055bbf324c430 in ?? ()
#1  0x00007f8bdcc4ba28 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007f8bdcc4ae8e in g_main_context_dispatch () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007f8bdcc4b240 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007f8bdcc4b533 in g_main_loop_run () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007f8bdd2e037d in gtk_main () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#6  0x000055bbf324b947 in ?? ()
#7  0x00007f8bdc8f10b3 in __libc_start_main (main=0x55bbf324b770, argc=1, argv=0x7ffd561af918, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffd561af908) at ../csu/libc-start.c:308
#8  0x000055bbf324baae in ?? ()

===================================================================
 GDB Backtrace (all threads)                                       
===================================================================
[New LWP 1194]
[New LWP 1243]
[New LWP 1252]
[New LWP 1241]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/lib/x86_64-linux-gnu/cinnamon-settings-daemon/csd-automount'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000055bbf324c430 in ?? ()
[Current thread is 1 (Thread 0x7f8bdb853a80 (LWP 1194))]

Thread 4 (Thread 0x7f8bdb012700 (LWP 1241)):
#0  0x00007f8bdc9df96f in __GI___poll (fds=0x55bbf4487d90, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
        resultvar = 18446744073709551100
        sc_cancel_oldtype = 0
        sc_ret = <optimized out>
#1  0x00007f8bdcc4b1ae in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#2  0x00007f8bdcc4b2e3 in g_main_context_iteration () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#3  0x00007f8bdcc4b331 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#4  0x00007f8bdcc74931 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#5  0x00007f8bdc129609 in start_thread (arg=<optimized out>) at pthread_create.c:477
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140238651467520, 5619217621584880288, 140726048060446, 140726048060447, 140726048060592, 140238651464832, -5553837029744270688, -5553852573707099488}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
#6  0x00007f8bdc9ec103 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.

Thread 3 (Thread 0x7f8bd9fa5700 (LWP 1252)):
#0  0x00007f8bdc9df96f in __GI___poll (fds=0x55bbf44a95c0, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
        resultvar = 18446744073709551100
        sc_cancel_oldtype = 0
        sc_ret = <optimized out>
#1  0x00007f8bdcc4b1ae in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#2  0x00007f8bdcc4b2e3 in g_main_context_iteration () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#3  0x00007f8bd9fb099d in ?? () from /usr/lib/x86_64-linux-gnu/gio/modules/libdconfsettings.so
No symbol table info available.
#4  0x00007f8bdcc74931 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#5  0x00007f8bdc129609 in start_thread (arg=<optimized out>) at pthread_create.c:477
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140238634243840, 5619217621584880288, 140726048059950, 140726048059951, 140726048060096, 140238634241152, -5553840682077085024, -5553852573707099488}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
#6  0x00007f8bdc9ec103 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.

Thread 2 (Thread 0x7f8bda801700 (LWP 1243)):
#0  0x00007f8bdc9df96f in __GI___poll (fds=0x55bbf4498340, nfds=2, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
        resultvar = 18446744073709551100
        sc_cancel_oldtype = 0
        sc_ret = <optimized out>
#1  0x00007f8bdcc4b1ae in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#2  0x00007f8bdcc4b533 in g_main_loop_run () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#3  0x00007f8bdcea2eda in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
No symbol table info available.
#4  0x00007f8bdcc74931 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#5  0x00007f8bdc129609 in start_thread (arg=<optimized out>) at pthread_create.c:477
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140238643009280, 5619217621584880288, 140726048060878, 140726048060879, 140726048061024, 140238643006592, -5553838120129092960, -5553852573707099488}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
#6  0x00007f8bdc9ec103 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.

Thread 1 (Thread 0x7f8bdb853a80 (LWP 1194)):
#0  0x000055bbf324c430 in ?? ()
No symbol table info available.
#1  0x00007f8bdcc4ba28 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#2  0x00007f8bdcc4ae8e in g_main_context_dispatch () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#3  0x00007f8bdcc4b240 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#4  0x00007f8bdcc4b533 in g_main_loop_run () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#5  0x00007f8bdd2e037d in gtk_main () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
No symbol table info available.
#6  0x000055bbf324b947 in ?? ()
No symbol table info available.
#7  0x00007f8bdc8f10b3 in __libc_start_main (main=0x55bbf324b770, argc=1, argv=0x7ffd561af918, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffd561af908) at ../csu/libc-start.c:308
        self = <optimized out>
        result = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {94265726528144, 5619217621584880288, 94265726515840, 140726048061712, 0, 0, -5619977134936251744, -5553851237811576160}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x1, 0x7ffd561af918}, data = {prev = 0x0, cleanup = 0x0, canceltype = 1}}}
        not_first_call = <optimized out>
#8  0x000055bbf324baae in ?? ()
No symbol table info available.
#0  0x000055bbf324c430 in ?? ()
#1  0x00007f8bdcc4ba28 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007f8bdcc4ae8e in g_main_context_dispatch () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007f8bdcc4b240 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007f8bdcc4b533 in g_main_loop_run () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007f8bdd2e037d in gtk_main () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#6  0x000055bbf324b947 in ?? ()
#7  0x00007f8bdc8f10b3 in __libc_start_main (main=0x55bbf324b770, argc=1, argv=0x7ffd561af918, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffd561af908) at ../csu/libc-start.c:308
#8  0x000055bbf324baae in ?? ()

**Comment by leigh123linux** [comment]
The yemplate is there for a reason, USE IT!

**Comment by freddylupin** [comment]
want deleted my account this forum please

**Comment by leigh123linux** [comment]
> want deleted my account this forum please

This isn't a forum!, it's a service provide by our github/microsoft overloads, so ask them instead!
