### ISSUE TITLE
Allow "Open dialog boxes" to accept URLs

### ISSUE THREAD

**Issue by tikajr** [linuxmint/cinnamon#9588]
I can confirm this is a feature on windows 10, but don't recall if it's possible on lower versions.

Basically, you click "upload" on a website and the cinamon/nemo "open file" dialog opens. It's possible to paste _filepaths_ into the address bar (which incidentally is hidden unless you press alt-f2 (i think)). However it's not possible to past _URLs_. 

The workflow on windows is something like this:

1. right click on picture, "copy location"
2. click "upload" on whatever the website is. "Open file" dialogue opens
3. Paste the copied url into the "path" box, press enter
4. All of the relevant downloading and uploading is automated in the background.

In comparison, the workflow on linux is more like this:

1. right click on picture, "Save"
2. Navigate file tree to find a location to save the picture
3. click "upload" on whatever the website is. "Open file" dialogue opens.
4. Navigate file tree to find the picture you saved
5. Upload file to website

The problem here is that on linux, currently i am required to "save" a picture which I don't actually want to save. The only reason I am saving it is so that I can upload it somewhere else.

This is just one example of the dodgy workflow. The generic feature which would solve this (and other related cases), would simply be to allow the "open file" dialogue to accept URLs. (I say "simply" with respect to the feature, not with respect to the development work involved, which is probably more involved than one might assume)

**Comment by JosephMcc** [comment]
This gets brought up over and over. Those dialogs aren't provided by Nemo or Cinnamon. They are handled by the toolkit the application is written in. We don't have any control over this.

**Comment by tikajr** [comment]
@JosephMcc where should I go to request this feature?

**Comment by JosephMcc** [comment]
To be honest I'm not totally sure. It depends on the toolkit the app is written in and the url case seems a little specific to a browser. Maybe the your browser of choice? Sorry I don't have a better answer I just know it's out of our control.
