### ISSUE TITLE
Single quote was ignored in cinnamon-settings.py which make application using xdg-su with many arguments failed.

### ISSUE THREAD

**Issue by kevinsmia1939** [linuxmint/cinnamon#9590]
```
This issue effects both cinnamon 4.6.7 and latest master.lmde4
This package is from openSUSE Cinnamon Factory.
https://build.opensuse.org/package/show/X11:Cinnamon:Factory/cinnamon

openSUSE Tumbleweed

Operating System: openSUSE Tumbleweed 20200917
Kernel Version: 5.8.7-1-default
OS Type: 64-bit
Processors: 8 × Intel® Core™ i7-3770 CPU @ 3.40GHz
Memory: 7.5 GiB of RAM
Graphics Processor: Mesa DRI Intel® HD Graphics 4000
 ```
I am the maintainer of Cinnamon DE in openSUSE.
I was trying to update Cinnamon package for openSUSE Tumbleweed
This is my package that I was working on: https://build.opensuse.org/package/show/home:andythe_great:branches:X11:Cinnamon:Factory/cinnamon
Which I will submit to: https://build.opensuse.org/package/show/X11:Cinnamon:Factory/cinnamon

In openSUSE, we use YaST to configure some settings. We decide to patch this file.
https://github.com/linuxmint/cinnamon/blob/master/files/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py

So that some of the setting will be redirect to YaST settings.
For example, the printer setting is,

`   [_("Printers"),                      "system-config-printer",               "cs-printer",            "hardware",       _("printers, laser, inkjet")],`
which becomes as such.
`    [_("Printers"),                      "xdg-su -c '/sbin/yast2 printer'",          "cs-printer",            "hardware",       _("printers, laser, inkjet")],`

However, upon clicking Printer setting in cinnamon-settings, the error is shown as below.

```
kev@linux:~> cinnamon-settings
Using pam module (python3-pampy)
xdg-su: unexpected argument 'printer''
Try 'xdg-su --help' for more information.
```
This is not an issue with YaST printer, since it can be reproduce with this.

`    [_("Printers"),                      "xdg-su -c 'nemo -c'",          "cs-printer",            "hardware",       _("printers, laser, inkjet")],`

```
kev@linux:~> cinnamon-settings
Using pam module (python3-pampy)
xdg-su: unexpected option '-c''
Try 'xdg-su --help' for more information.
```
However, running `xdg-su -c '/sbin/yast2 printer' `or `xdg-su -c 'nemo -c'` inside terminal work normally.
This suggest that the single quote was ignored somehow which become something like `xdg-su -c /sbin/yast2 printer` which `xdg-su` does not understand.
Nemo have nothing to do with printer but this can be reproduce by having many arguments inside the quote ('  ').

This can be test by modifying `/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py ` direclty.
I expect that the single quote should not be ignore. Or have the behaviour change, what should be done in this case? 

Thank you.

**Comment by shenlebantongying** [comment]
I think i know the problem:

The things we changed are `STANDALONE_MODULES`.

it then goes to

https://github.com/linuxmint/cinnamon/blob/d8d92ca59184d12b1541cffb883fe467706c8745/files/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py#L324-L327

Under the hood, the `SAModule` is actually

https://github.com/linuxmint/cinnamon/blob/f86c22c1f9094dbf934dbd31cb180b4d6587af66/files/usr/share/cinnamon/cinnamon-settings/bin/SettingsWidgets.py#L287-L298

Note that: `name = self.name.replace("pkexec ", "") `

So the problem is that its actually become part of the `pkexec`

pkexec can also be used to launch gui apps, its looks like

https://askubuntu.com/questions/1042344/i-need-an-equivalent-of-gksu-in-18-04

 However, I dont know for sure one might have to tinker the polkit to make it work properly.

**Comment by shenlebantongying** [comment]
![image](https://user-images.githubusercontent.com/20123683/107398051-41d12e80-6acd-11eb-971d-fe61cc2452d0.png)

The pkexec was changed to replace gtksu, i think they function somehow the same right?

Did you try not using `xdg-su -c` at all?

**Comment by shenlebantongying** [comment]
the Python's split() function devide the '/sbin/yast2 printer' into ` '/sbin/yast2` and `printer'`

Then Popen treat them as separate arguments

**Comment by shenlebantongying** [comment]
So, we just change 216 line of usr/share/cinnamon/cinnamon-settings/bin/SettingsWidgets.py

to `split(' ',2)`

and change `"xdg-su -c '/sbin/yast2 printer'"` to `"xdg-su -c /sbin/yast2 printer"`

**Comment by shenlebantongying** [comment]
I don't think this is an upstream problem, since yast use a weird way to invoke command i.e. `yast printer` rater than `yast --printer`
