### ISSUE TITLE
[Feature Request] Add support for applets that you can type in the panel

### ISSUE THREAD

**Issue by ItzSwirlz** [linuxmint/cinnamon#9600]
Feature Request: Add support for applets you can type in the panel.

I was doing my UCR work and I asked others what Cinnamon spices they'd like to see and one suggested being able to run a bash command from terminal.

So I went through src files looking for stuff, and the closest I found was PopupMenu but you couldn't find a physical applet that let you type something in a box or something and then the applet does it's thing.

So what I'm suggesting: TextBoxApplet

A TextBoxApplet is a box which can be customized by the applet that will do something while, during, or when input into the applet after or during typing.

Other options (which can also be added as a TextBoxApplet, or an ExtendedTextBoxApplet) is an applet MenuItem that when clicked will open a TextBotApplet on the side or wherever possible (if out of room, sticking out of the panel) and can have a Text Box there.

This idea can grow on, so what do you guys think?

I'd help but I'm sort of just starting learning the Spices/its Documentation

**Comment by simonwiles** [comment]
A bit like <kbd><kbd>Alt</kbd> + <kbd>F2</kbd></kbd>?

**Comment by ItzSwirlz** [comment]
Yeah, like Alt+f2-but you could do it in terminal.

I could make an applet (or Cinnamon DE could) but theres no such applet that is similar to work with it.

**Comment by mtwebster** [comment]
I'm not really sure I get this.  The alt-f2 menu works like a shell prompt. The drawback for it is you can only do alt-f2 to bring it up.

Typing in the panel itself is out of the question I think - there are technical issues that I don't think can be overcome (or are not worth the cost - being able to type in the panel has never been a consideration).  What's wrong with just making an applet that pops up an entry where you can type?

Consider that you'd essentially have the same amount of effort regardless - clicking on the applet icon to bring up the popup vs clicking in the panel. Using a shortcut key to bring up the popup vs a shortcut to focus the panel's entry.  In either case the popup entry is focused and you can type immediately. 

Something like the "Internet Search Box" applet would be a decent starting point maybe.

**Comment by ItzSwirlz** [comment]
Yeah-like that-an internet search box would be great to start with. Sort of like Alt + F2 in the panel

**Comment by NikoKrause** [comment]
https://cinnamon-spices.linuxmint.com/applets/view/226

**Comment by NikoKrause** [comment]
https://cinnamon-spices.linuxmint.com/applets/view/185

**Comment by ItzSwirlz** [comment]
No-No applets have been created yet that does anything similar.

So in the panel, there is a text box.

The text box is like a normal one, click it, you can type, and then another button to execute the typed item.

**Comment by mtwebster** [comment]
I mentioned the Internet Search Box applet previously, as a sample applet you could modify - that's the closest you're going to get to what you're after. It's not something we're interested in implementing in the panel directly.

**Comment by NikoKrause** [comment]
Ok. @ItzSwirlz  If you're interested in creating such an applet, your best starting point would be to modify the Internet Search Box Applet. Shouldn't be too hard to do it.

**Comment by ItzSwirlz** [comment]
That would be correct - I want to test it out first.

But would it make sense to have a JS applet tool for that? (part of the toolkit in js/ folder)
