### ISSUE TITLE
Mint 20 Cinnamon fails to boot with HDMI cable connected

### ISSUE THREAD

**Issue by morvael** [linuxmint/cinnamon#9601]
Cinnamon version (cinnamon --version) **4.6.7**
Please specify if you are using the daily builds PPA **No**
Distribution - (Mint 17.2, Arch, Fedora 25, etc...) **Mint 20**
Graphics hardware *and* driver used **NVIDIA GTX 1650, Radeon iGPU disabled in BIOS, Lenovo Legion 5 15ARH05, driver nvidia-driver-450 450.66-0ubuntu0.20.04.1**
32 or 64 bit **64**

**Issue**
When Linux boots with HDMI cable connected to external monitor, it hangs as soon as splash screen should be displayed. When I let it boot without cable connected, it boots normally, and I can connect the cable afterwards and use two monitors normally.

**Expected behaviour**
System boots normally with HDMI connected.

Checked https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1874194 but removing quiet splash doesn't help in my case.

**Comment by leigh123linux** [comment]
This isn't cinnamon issue if it dies before the login screen (DM).

Maybe related to https://forums.developer.nvidia.com/t/geforce-gtx-1050-ti-mobile-doesnt-recognise-hdmi-port-and-dp-port-hicups-with-external-monitor/155633

**Comment by morvael** [comment]
Not the same issue as it works normally after login screen appears. But can't be connected during boot.

**Comment by leigh123linux** [comment]
> Not the same issue as it works normally after login screen appears. But can't be connected during boot.

File the issue here https://github.com/linuxmint/linuxmint/issues

**Comment by leigh123linux** [comment]
See this guide regarding 'external monitor'  configuration.

https://rpmfusion.org/Howto/Optimus

**Comment by morvael** [comment]
IMHO disabling iGPU in BIOS should make the laptop more akin to a desktop computer, with just the discrete GPU from NVIDIA present, and thus without requiring Optimus to switch. Also, this laptop laptop is not using the common Intel iGPU + NVIDIA configuration, on which Optimus focuses, but a Radeon iGPU + NVIDA.

**Comment by leigh123linux** [comment]
Maybe try nvidia 440.82 if it's still available in the repo.
