### ISSUE TITLE
Unlike Calendar/other Applets, Main Cinnamon Menu Applet doesn't slowly rise up but instantly pops up

### ISSUE THREAD

**Issue by ItzSwirlz** [linuxmint/cinnamon#9605]
```
 * Cinnamon version 4.6.7
 * Ubuntu Cinnamon Remix 20.10 Groovy (Beta, essentially)
 * Intel Core i5 7th Gen, 8 GB RAM 1 TB TOSHIBA Hard Disk
 *  64 bit
 ```

**Issue**
When you cilck the Calendar Applet, for example:
You will see the UI of the applet rising up above/next to the panel until it's fully loaded. There is an animation for it.

However, when you click the default Main Cinnamon Menu Applet, there is no animation, it just pops up/down.

**Steps to reproduce**
Click the Cinnamon Menu Applet /shrug

**Expected behaviour**
There should be an animation when opening the applet.

**Other information**
None

**Configuration info, if applicable**
It's default settings, nothing here

**Comment by brownsr** [comment]
There is an option in the menu configuration (right click on the menu applet) to turn animations on or off.  It looks like the default is to have them off, but if you want them on, you can just select this option.

Regards

Simon

**Comment by ItzSwirlz** [comment]
UCR doesn't change the config of applets.

So I guess it's a packaging thing or can be changed manually?

But also maybe it should be default aswell to have animation enabled.

**Comment by mtwebster** [comment]
The default behavior is intentional (no animation) - this was done for performance reasons, to have the primary menu be instantly available.
