### ISSUE TITLE
Shutting down and Restarting takes over a minute

### ISSUE THREAD

**Issue by kameshkotwani** [linuxmint/cinnamon#9608]
**Issue**
There is some process which is delaying the shutdown and restart process. While shutting down, there is a message in log, "waiting for process crond" and it takes over a minute to respond.

**Steps to reproduce**

- Update your linux mint to latest kernel.

- Shut down the OS.

**Expected behaviour**
The laptop/desktop should shutdown within 10-15 seconds.

**Other information**
I have attached my laptop info and also the photo of the log where the shutdown gets stuck for over a minute.
![cinnamon-issue](https://user-images.githubusercontent.com/36355951/94828480-24a59880-0427-11eb-9574-71776408673d.png)
![1601565423502](https://user-images.githubusercontent.com/36355951/94828822-7fd78b00-0427-11eb-83f7-72c37460b807.jpg)

**Comment by leigh123linux** [comment]
It isn't cinnamon's job to stop system processes, logind or systemd should handle it.
Please file the issue on this link https://github.com/linuxmint/linuxmint/issues

**Comment by kameshkotwani** [comment]
Done!
