### ISSUE TITLE
Feature request: Applet/Extension/Theme updater to have a "changelog" feature so we can check the update before accepting it

### ISSUE THREAD

**Issue by sanawu** [linuxmint/cinnamon#9612]
Feature request: Applet/Extension/Theme updater to have a "changelog" feature so we can check the update before accepting it

mintupdate has a changelog pane

applet,themes,extension updater has no changelog pane for updates, just a button

I want to review changes before deciding

**Comment by NikoKrause** [comment]
You can always review changes on the website itself. Every spice has a "Last commit" entry. If you click on the linked number there, you see all chommits specific to this applet etc.

For example:
https://cinnamon-spices.linuxmint.com/applets/view/12

**Comment by sanawu** [comment]
That's what I want to avoid, having to spin up a browser, mintupdate has a changelog pane, so why not keep consistency in the interface?

**Comment by claudiux** [comment]
@sanawu You can use the Spices Update applet, which gives you the description of each update. https://cinnamon-spices.linuxmint.com/applets/view/309

**Comment by sanawu** [comment]
> @sanawu You can use the Spices Update applet, which gives you the description of each update. https://cinnamon-spices.linuxmint.com/applets/view/309

I would rather not thanks

**Comment by sanawu** [comment]
> @sanawu You can use the Spices Update applet, which gives you the description of each update. https://cinnamon-spices.linuxmint.com/applets/view/309

PLEASE STOP ADVERTISING YOUR APPLET IN BUG REPORTS

**Comment by collinss** [comment]
@sanawu Please stop being rude to people who are just trying to help. What you're asking for is way over the top imo. As previously mentioned, there are several options to achieve what you want already. If you don't like those, you're welcome to implement your own solution, but I don't see anyone jumping through hoops to give you what you want - especially with an attitude like that.

**Comment by sanawu** [comment]
Fine, keep your rotting applets, many are dead anyway, sitting there spamming your update applet in bugs, really, what utter trash

Time to move on from Cinnamon DE then toodles
