### ISSUE TITLE
Adding a Duration and Album to the Music folder

### ISSUE THREAD

**Issue by Ubuntu-2020** [linuxmint/cinnamon#9616]
In the **Nemo** file Manager **Linux Mint 20 Cinnamon**, we can select a **List View**.
We can also add the columns we need. But the item **Duration** and **Album** is missing from this list:
![Linux-Mint-20-Cinnamon-Nemo-List View](https://user-images.githubusercontent.com/65112331/95204192-6b5f0e00-07ec-11eb-9d1b-5989d60bdffa.gif)

Here is an example of a similar list in **Windows**:
![windows-10-select-detail-columns](https://user-images.githubusercontent.com/65112331/95204229-75810c80-07ec-11eb-82ec-69fc82dc9802.png)

So please add the item **Duration** and **Album**.
I suggest adding the **Duration** and **Album** columns to the table in the **Music folder** by default.

In **Windows** if you make a table view in the **Music folder** you can see that the **Album** is enabled by default:
![Windows-Explorer-Columns](https://user-images.githubusercontent.com/65112331/95206274-2ab4c400-07ef-11eb-9bf1-4ec3be55dd8a.png)

**Comment by icarter09** [comment]
@Ubuntu-2020 this feature request should be taken up in Nemo, not Cinnamon
