### ISSUE TITLE
Adding a Dimensions to the Pictures folder

### ISSUE THREAD

**Issue by Ubuntu-2020** [linuxmint/cinnamon#9617]
In the **Nemo** file Manager **Linux Mint 20 Cinnamon**, we can select a **List View**.
We can also add the columns we need. But the item **Dimensions** is missing from this list:
![Linux-Mint-20-Cinnamon-Nemo-List View](https://user-images.githubusercontent.com/65112331/95204192-6b5f0e00-07ec-11eb-9d1b-5989d60bdffa.gif)

Here is an example of a similar list in **Windows**:
![windows-10-select-detail-columns](https://user-images.githubusercontent.com/65112331/95204229-75810c80-07ec-11eb-82ec-69fc82dc9802.png)

So please add the item **Dimensions**.
I suggest adding the **Dimensions** column to the table in the **Pictures folder** by default.

In **Windows** if you make a table view in the **Pictures folder** you can see that the **Dimensions** is enabled by default:
![Windows-Explorer-Columns-Pictures](https://user-images.githubusercontent.com/65112331/95206709-add61a00-07ef-11eb-9580-a80b165dbabe.png)

**Comment by icarter09** [comment]
@Ubuntu-2020 this feature request should be taken up in Nemo, not Cinnamon.
