### ISSUE TITLE
Cinnamon crashes to fallback mode on clicking applet icon

### ISSUE THREAD

**Issue by sanawu** [linuxmint/cinnamon#9620]
For further details see this bug https://github.com/linuxmint/muffin/issues/571

**Comment by GuiMarthe** [comment]
It seems like this is related to the issue #9618 I posted  right?

**Comment by sanawu** [comment]
It's in a different library so it's not the same issue

Yours is in libmuffin-cogl-0.so

mine is segfaulting in libmuffin-clutter-0.so

**Comment by icarter09** [comment]
@sanawu I'm going to close this ticket since it's just being used as a reference to another ticket.
