### ISSUE TITLE
Lock Desklets in Place

### ISSUE THREAD

**Issue by mfreeman72** [linuxmint/cinnamon#9622]
```
 * Cinnamon version 4.6.7
 * Distribution - Linux Mint 20 Cinnamon
 * Graphics hardware *and* driver used - AMD Radeon R5 - Open Source Radeon driver
 * 64 bit
 ```

I've recently noticed a problem on Linux Mint 20, where if I'm simply moving my mouse pointer, usually over the desklet's position (but sometimes even with the mouse in a completely different part of the screen), the desklet decides to unexpectedly attach to the mouse and moves with it. This happens with or without clicking, and often when interacting with a window that's on top of the desklet, which brings the desklet on top of the window I'm interacting with until I've placed the desklet again. It would be really great to have the option to just lock them down, and allow them to only move when initially placing them or editing their configuration. That would be my preferred mode of operation for the desklets I use. Or, alternatively it could be user-lockable on a per-desklet basis.

**Comment by GangsterGranule** [comment]
Hi,
Just wanted to add a small video (see attached) to help reproduce/identify/correct this very annoying problem.
Hope it will be usefull.

https://user-images.githubusercontent.com/77329011/104305842-7e5d3a80-54cd-11eb-98c2-484e1b2dc14f.mp4

**Comment by mfreeman72** [comment]
Yes, that's how it happens for me as well, although, at least for me, the mouse doesn't even have to be over the desklet, although that's the most common situation. In some instances, it's all the way on the other side of the screen from it, and suddenly it starts moving with my mouse, but across the screen from it.

**Comment by hash** [comment]
When is desklet moved outside the screen the only option to bring it back is to export via Desklets > manage > settings.
Then reimport settings to fresh copy.

**Comment by claudiux** [comment]
This bug is still present in Cinnamon 4.8.6.

**Comment by bluepostit** [comment]
> This bug is still present in Cinnamon 4.8.6.

Yes, for me too.

**Comment by mfreeman72** [comment]
Yes. Still present. Happens to me on almost a daily basis. Extremely annoying bug! Please fix it!

**Comment by icarter09** [comment]
I'm also noticing that I'm sometimes able to click through a window and do something with the desklet. In this case, it was me clicking a link that was on the desklet. @mfreeman72 do you have `Snap desklets to grid` enabled? Just establishing what settings might be off/on. Thanks.

**Comment by claudiux** [comment]
@icarter09 I have `Snap desklets to grid` enabled. I'll try disabling it.

**Comment by mfreeman72** [comment]
I've had snap to grid turned off for quite a while, but I've seen this happen with i that setting both on and off. Doesn't seem to make a difference.

**Comment by icarter09** [comment]
I figured that setting didn't make a difference, but always good to rule that out. If anyone is able to come up with a set of steps to reproduce this, please post them. I've been able to duplicate the issue several times, but not sure of the exact steps. Thanks.

**Comment by mfreeman72** [comment]
For me, it's fairly random. There's not a specific thing that seems to make it happen more than anything else, other than I think it happens more often when a window is open. I haven't seen it happen when a program isn't running with an open window. I know it always happens as I'm moving my mouse around the screen, but it doesn't matter when or what I'm running or where my mouse is. If a desklet is placed on the right side of the desktop, I can be moving my mouse around over on the left side, nowhere near where the desklet is placed, and the desklet will pop up over the window of the currently running program and move in sync with my mouse, but not attached to it. My mouse will be moving around the left side of the screen, and the desklet will be moving parallel to the mouse, but over on the right side of the screen. So for me, it's not a matter of the mouse moving over some element of the desklet that triggers it. It also isn't connected to a mouse click. Just moving the mouse around without clicking causes it to happen.

**Comment by ipimpat** [comment]
I'm using a dual screen setup and for me it happens when the cursor is on opposite monitor, but the same cords as the desklet.

![dual screen desklet grapping](https://user-images.githubusercontent.com/450038/111074290-a0c9ff00-84e2-11eb-880a-594c72bd393b.png)

**Comment by mfreeman72** [comment]
An amendment to my comment above... I have now seen this happen without a window open.

I still think the best short-term fix would be to include an option in the Desklets "General Settings" tab to lock a desklet to a user-defined position on the screen and not allow it to move until it is being configured. Only allow movement when configuring the specific desklet, such as while the configuration window is open.

**Comment by Ducvoccer** [comment]
This bug is still present in Cinnamon 4.8.6.

**Comment by icarter09** [comment]
I recently put a [PR](https://github.com/linuxmint/cinnamon/pull/10107) for `Snap desklets to grid` not working correctly. Doing some testing with that PR applied, I was still able to get the desklet to move unexpectedly when `Snap desklets to grid` was disabled, but wasn't able to duplicate the issue when it was enabled, which means it could use some more testing. If anyone could assist in testing this, it would be much appreciated. Thanks in advance.

**Comment by neofeo** [comment]
+666 votes to this!!

**Comment by icarter09** [comment]
@neofeo do you still experience the issue when `Snap desklets to grid` is enabled?

**Comment by neofeo** [comment]
Yes, cinnamon 4.8.6

**Comment by gskerry** [comment]
+1 Cinnamon 4.8.6

**Comment by nurekpodwodny** [comment]
I encounter this a lot, too. I noticed some desklets  (e.g. Clock) may show up over a Chromium window as well - I suppose this way applet  may take focus and stick to the mouse pointer. 
Majority of this happens however without applet visible on the top of a window.
Is it a Clutter bug?

**Comment by infusixllc** [comment]
Can someone indicate where the coordinate's are stored so that I can rescue my desklets that have now gone off the side of the screen when I accidentally clicked when they moved off due to this issue?

**Comment by TheMaligator** [comment]
```gsettings get org.cinnamon enabled-desklets```
will give the coordinates of the desklets, for me it was
```['system-monitor-graph@rcassani:8:15:240', 'system-monitor-graph@rcassani:9:15:105', 'quoteOfTheDay@tinnu:12:30:60']```
then, just copy those coordinates, and run this command:
```gsettings set org.cinnamon enabled-desklets "<the coordinates>"```
with my coordinates command was
```gsettings set org.cinnamon enabled-desklets "['system-monitor-graph@rcassani:8:15:240', 'system-monitor-graph@rcassani:9:15:105', 'quoteOfTheDay@tinnu:12:30:60']"```
i just made a bash alias for this command and put it in `~/.bash_aliases`
also you might have to restart cinnamon for the desklets to move back to their original position, it's not ideal, but it does the job...

**Comment by mockturtl** [comment]
I'm on Cinnamon 5.2.7, but I've hit this bug dozens of times since 2017(?), on a 4k display.  :sweat_smile:  Typically I have Chrome docked to the right side of the screen, and clicks pass through to a desklet underneath.  It sometimes feels like there's an offset of a few hundred pixels between where I clicked and where the desklet received the event.

https://github.com/linuxmint/cinnamon/issues/9622#issuecomment-1179688901 is a good workaround to reset the arrangement. 

I almost always experience a secondary bug -- after a desklet has "magnetized" to my cursor, and let go somewhere else on the screen, no desklets respond to any click events until I restart Cinnamon.

**Comment by mfreeman72** [comment]
> I would argue this should not be closed. The bug that causes the desklets to get picked up for no reason still exists even if you can now lock them. This is more of a workaround than a fix.

I agree. This is a bug that still exists in Cinnamon, even if it can be worked around. This should be fixed in Cinnamon itself, and not something the user should have to issue commands to repair. Even if the fix is to lock them down, it should be included as an option directly in Cinnamon, and should the user choose to not lock down their desklet, the bug should still not occur.

**Comment by B4rabbas** [comment]
Issue isn't fixed, I can reproduce it on LM 21...
