### ISSUE TITLE
installation failure with secure boot off

### ISSUE THREAD

**Issue by oz42** [linuxmint/cinnamon#9623]
Mint Ulyana

With secure boot on, the USB drive could not boot.

With secure boot off, installation went smooth.

Except for the well known Realtek 8822CE bug: Wifi goes offline after several minutes, then ny FireTV in same network goes offline too.

Anyway, installation continues. Then it tries to install the secure boot compatible grub setup and fails.

So:
secure boot on: installation fails
secure boot off: installation fails

**Comment by leigh123linux** [comment]
This isn't a cinnamon issue.

https://github.com/linuxmint/linuxmint/issues

**Comment by oz42** [comment]
Ah, there is the "core stuff" site. Thank you for the link, it seems to be hard to find.
