### ISSUE TITLE
[Suggestion] Replace gnome-screenshot by ksnip

### ISSUE THREAD

**Issue by Nokia808** [linuxmint/cinnamon#9626]
I would like to suggest on you to use ksnip as the default screenshot tool for Cinnamon DE instead the current gnome-screenshot.

ksnip is very useful & beautiful application which allow user to edit their screenshots & annotating them.

Ksnip repository:
https://github.com/ksnip/ksnip

**Comment by NikoKrause** [comment]
Thanks for your feedback. I don't think the default will be changed. Ksnip is Qt-based, iirc there are not much QT-based default apps in Mint. Also it's a little bit of an overkill for the average users.
