### ISSUE TITLE
New feature requirement : adding translation of applets descriptions in the applets list

### ISSUE THREAD

**Issue by InfoLibre** [linuxmint/cinnamon#9629]
* Cinnamon version 4.6.7
* I don't use the daily builds PPA
* Distribution - Mint 20 Cinnamon

**Issue**

In the Applets management, when we download for the first time the applets list, their description is in english in the "Download" tab,even if we installed LM  in french. Is it possible to show their description in french (or another installed language) ?

![en anglais](https://user-images.githubusercontent.com/3955499/95636101-8486e980-0a8e-11eb-8dfd-f3a85d12a929.png)

**Comment by InfoLibre** [comment]
Same feature requirement for the desklets list and the extensions list.

**Comment by NikoKrause** [comment]
This has been implemented in https://github.com/linuxmint/cinnamon/commit/628a5540f74d6273baafb9c2874d617a4b9cee9a and will appear with Cinnamon 5.0 / Mint 20.2
