### ISSUE TITLE
Wrong french translation in the Calendar Applet

### ISSUE THREAD

**Issue by InfoLibre** [linuxmint/cinnamon#9630]
* Cinnamon version 4.6.7
* I don't use the daily builds PPA
* Distribution - Mint 20 Cinnamon

**Issue**

In the Calendar applet, there's a mistake in the french translation :
Utiliser un format de date **personalisé** -> Utiliser un format de date **personnalisé**

![Capture d’écran du 2020-09-25 22-06-08](https://user-images.githubusercontent.com/3955499/95636771-4d193c80-0a90-11eb-88f6-953083962991.png)

**Comment by NikoKrause** [comment]
Thanks. Can you please submit the correct version directly here:

https://translations.launchpad.net/linuxmint/latest/+pots/cinnamon/fr/+translate?batch=10&show=all&search=un+format
