### ISSUE TITLE
Cinnamon Desktop Bug - Windows Button + Taking Screenshot

### ISSUE THREAD

**Issue by ShlomiRex** [linuxmint/cinnamon#9631]
```
Cinnamon 4.6.7
Mint 20.04
NVIDIA GTX 970, driver: 450.66
X.Org server
64 bit
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
I can't replicate the bug and also extract the file (keyboard is stuck after bug)
 ```

**Issue**
I wanted to take a picture of area while studying.
I accidentally pressed Windows key and also pressed the 'Take Screenshot Of An Area' shortcut (Shift + PrintScreen)
The entire display got green.
I can do this multiple times. I can't seem to press anything on the keyboard except Escape key
Restarting the PC fixes this

**Steps to reproduce**
* Press Windows Key
* Press Take picture of an area shortcut on keyboard (default is Shift + PrntScrn)

**Expected behaviour**
Not make display green

**Other information**
I managed to take a picture of the display while having this bug (Print Screen)
I also took with my phone
Because it is green in the screenshot that means it's the desktop environment, or display manager, i don't really know

** Images **

![IMG_20201010_190622](https://user-images.githubusercontent.com/17744127/95660032-df235280-0b2d-11eb-8dc8-22be9d924ad3.jpg)

![Screenshot from 2020-10-10 19-06-10](https://user-images.githubusercontent.com/17744127/95660028-d3379080-0b2d-11eb-9e19-9d82616f3f29.png)

**Comment by mtwebster** [comment]
Fixed by https://github.com/linuxmint/cinnamon-desktop/commit/b6df83fcded6059be76b96462acd7da55e89ee83
