### ISSUE TITLE
Cursor rotates when loading Redshift 

### ISSUE THREAD

**Issue by jakoblm** [linuxmint/cinnamon#9633]
```
 * Cinnamon 4.6.7
   - no PPA used
 * Linux Mint 20, LMDE 4
 *  Graphic Hardware:
    1) Intel Core i7-2620M: i915
    2) Nvidia GTX 970: nvidia-driver 450
 * 64 bit
 ```

**Issue**
Since Cinnamon version 4.6.7 (in LMDE 4 and LM 20) I have observed that during the automatic start of Redshift the mouse pointer changes into a clockwise rotating circle for about 5-10 seconds - i.e. changes to the status "busy". The GUI is already ready for use, but this rotating mouse pointer suggests that the startup process is not yet complete. If I don't let Redshift load automatically at startup, the mouse is shown as a normal pointer.

The same happens when I manually start Redshift while the system is running. Sometimes the rotating mouse pointer only appears when I move the mouse to the menu bar. 

**Steps to reproduce**
Activate Redshift in autostart and reboot the system (Linux Mint 20 or LMDE 4). Pay attention to the mouse pointer. 

Or start Redshift manually while the system is running. Pay attention to the mouse pointer. The mouse pointer may need to be on the menu bar.

**Expected behaviour**
The mouse pointer does not change its appearance when Redshift is started. 

**Configuration info, if applicable**
Other applets are: volume control, network, power management, time. 
It does not matter which command I use to start Redshift: 
1) redshift-gtk 
2) redshift-gtk -l latitude:longitude -t 6500:3700

```

**Comment by jakoblm** [comment]
Addition: I have activated the automatic user login on my systems.

**Comment by mtwebster** [comment]
Hi, can you try something:

Copy the file `/usr/share/applications/redshift-gtk.desktop` to `~/.local/share/applications`
```
cp /usr/share/applications/redshift-gtk.desktop ~/.local/share/applications
```

Then open that file with the text editor, and the very last line should read `StartupNotify=true` - comment that out by putting a # in front of it:
```
# StartupNotify=true
```
Then see if the icon still changes.
