### ISSUE TITLE
Many apps ignoring font settings

### ISSUE THREAD

**Issue by heliommsfilho** [linuxmint/cinnamon#9640]
```
 * Cinnamon version 20 Ulyana
```

**Issue**

I installed Linux Mint yesterday and noticed that many apps (including Linux Mint system apps) are not respecting my font configuration. I defined Roboto 10 like default font, but as you can see in the images many apps keeps using a whatever other larger font while file manager and settings uses the correct font.

[Image](https://imgur.com/kqMnY8u)

**Comment by mtwebster** [comment]
The two windows that appear to not be respecting the font size settings necessarily run as a different (root) user and aren't ones you'll typically use often.  Regardless they should respect the font settings, and they do for me. I'm not sure what is causing your issue.

How did you install this font, just downloading and placing some files - if so, where? Or was there a package you installed? The install location may be a factor.

**Comment by heliommsfilho** [comment]
Thank you for your reply @mtwebster. I installed those fonts downloading directly from Google's site and double-clicking the .ttf file. So, the font was installed in **~/.local/share/fonts**.

After copying to **/usr/share/fonts/truetype** solved the problem.
