### ISSUE TITLE
Bug with rtw_pci driver

### ISSUE THREAD

**Issue by kindoflew** [linuxmint/cinnamon#9641]
```
 * Cinnamon version: 4.6.7
 * Distribution: Mint 20
 * Graphics hardware and driver used: Intel Corporation Device 8a56, driver: i915
 * Wi-fi hardware and driver: RTL8723DE, driver: rtwpci
 * 64 bit
I have Mint running on an HP 15 laptop.

 ```

**Issue**
- Wi-fi will abruptly cut out, CPU usage becomes high

**Steps to reproduce**
- None, it randomly happens after different amounts of internet use. Reboot fixes, but eventually happens again

**Expected behaviour**
- To not lose wi-fi signal

**Other information**
After a lot of googling the issue seems to be with the rtw_pci driver. So far, every time it has happened my logs show something like:
rtw_pci 0000:01:00.0: failed to poll offset=0x5 mask=0x2 value=0x0
rtw_pci 0000:01:00.0: mac power on failed
rtw_pci 0000:01:00.0: failed to power on mac
rtw_pci 0000:01:00.0: leave idle state failed
rtw_pci 0000:01:00.0: failed to leave isp state
rtw_pci 0000:01:00.0: failed to leave idle state

other rtw_pci logs that come up often is:

WARNING: CPU: 7 PID: 0 at drivers/net/wireless/realtek/rtw88/tx.c:162 rtw_tx_report_purge_timer+0x25/0x60 [rtw88]
and
rtw_pci 0000:01:00.0: failed to send h2c command

I don't know if those are related. This was happening before the previous kernel update, but only after prolonged sleep (a day or two away from my laptop). Since the update yesterday it has happened 3 times I believe.

**Comment by leigh123linux** [comment]
Report the issue against the kernel at ubuntu launchpad.
