### ISSUE TITLE
Window capture : top corners are wrongly cut

### ISSUE THREAD

**Issue by InfoLibre** [linuxmint/cinnamon#9649]
```
 * Cinnamon version 4.6.7
No PPA
 * Mint 20 Cinnamon
 * 64 bit
 ```

**Issue**
When I take a screenshot of a window with Cinnamon Screenshot, the two top corners are wrongly cut in the resulting file.

![96354688-ae1cc200-10d9-11eb-8507-8dc27cb36b6f](https://user-images.githubusercontent.com/3955499/96354755-66e30100-10da-11eb-90d1-1dadf76026b6.png)

**Steps to reproduce**
Open a Terminal window (Administration - Terminal in Mint Menu). Take a screenshot of this window with Cinnamon Screenshot.

**Expected behaviour**
The two top corners of the picture should be round, with transparency. The colour of the background shouldn't appear around these corners.
Pictures created with Cinnamon Screenshot have a transparency layer but it seems that it isn't enough, there's another problem in the corners.

**Comment by InfoLibre** [comment]
And with some windows, there's a big border around the screenshot. Example : Disks.

![Disques_001](https://user-images.githubusercontent.com/3955499/97713432-1c8d5700-1ac0-11eb-839c-49ba3f45ab40.png)

**Comment by NikoKrause** [comment]
What do you mean by Cinnamon Screenshot? Where do I find it and how do I take a screenshot with it?

**Comment by InfoLibre** [comment]
This Cinnamon tool :

![Capture d’écran du 2020-11-02 08-38-00](https://user-images.githubusercontent.com/3955499/97841769-c9e1b400-1ce6-11eb-8e7c-b0189085dab2.png)

**Comment by leigh123linux** [comment]
That tool is part of gnome-screenshott cinnamon.

**Comment by InfoLibre** [comment]
But I've got this problem with all other screenshot tools I tried.
So, it could be a Cinnamon bug.

**Comment by NikoKrause** [comment]
This is not a CinnamonTool, this is Gnome Screenshot.
https://gitlab.gnome.org/GNOME/gnome-screenshot/-/issues

**Comment by NikoKrause** [comment]
What are all other screenshot tools?

**Comment by InfoLibre** [comment]
I tried with Flameshot, Shutter.

**Comment by leigh123linux** [comment]
> I tried with Flameshot, Shutter.

Have you tested the tools in another DE?

**Comment by InfoLibre** [comment]
No, I'm using only Cinnamon. This bug is annoying and very old. It's impossible to make screenshots under LM and you can find now several website showing LM documentations with these ugly screenshots.

With Shutter :

![test  En fonction  - Oracle VM VirtualBox_001](https://user-images.githubusercontent.com/3955499/97850083-d4567a80-1cf3-11eb-9168-4b48023981cc.png)

It's worse than with Gnome Screenshot because the picture doesn't have a transparent layers.

**Comment by leigh123linux** [comment]
Screenshots are working fine here.

![screenshot-window-2020-11-02-092045](https://user-images.githubusercontent.com/1299302/97851139-e2ed6380-1cec-11eb-8876-b102016d7c8e.png)

**Comment by InfoLibre** [comment]
Of course, if you take a screenshot with square corners :smile:

**Comment by InfoLibre** [comment]
Same bug with Kazam : https://bugs.launchpad.net/kazam/+bug/1900284

**Comment by leigh123linux** [comment]
Screenshot programs use the window dimensions, they don't account for rounded corners.
You will need to use another program to edit the image to round the corners.

**Comment by InfoLibre** [comment]
It's a joke ?
With old LM versions, all screenshot software did not have all this problem with corners and with borders.
And give this answer to macOS or Windows users, they will laugh.
Same with MATE : https://github.com/linuxmint/mint20-beta/issues/8

**Comment by NikoKrause** [comment]
Does it happen in Ubuntu/GNOME?
Speaking of older Mint versions, which were fine: which Mint version exactly? Are you sure you had the same theme in those older Mint versions?

**Comment by InfoLibre** [comment]
I don't use Ubuntu. But the bug is in Linux Mint, you can verify it.

**Comment by NikoKrause** [comment]
It sure is in Mint. The question though is, is the issue specific to Mint or is it inherited by Ubuntu / Debian, etc. 

Also:
Speaking of older Mint versions, which were fine: which Mint version exactly? Are you sure you used the same theme in those older Mint versions?

**Comment by InfoLibre** [comment]
A screenshot with Gnome Screenshot in ubuntu-20.04.1-desktop-amd64.iso :

![Capture d’écran du 2020-11-02 14-23-43](https://user-images.githubusercontent.com/3955499/97872931-2230aa00-1d17-11eb-91fa-51bdfe097a5c.png)

Corners are rounded, transparent layer, no wrong borders.
