### ISSUE TITLE
Favourites don't appear in menu because menu doesn't resize automatically

### ISSUE THREAD

**Issue by EvoEvz** [linuxmint/cinnamon#9662]
```
 * Cinnamon version (cinnamon --version): 4.6.7
   - Please specify if you are using the daily builds PPA: Just downloaded the iso
     (https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds).
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 20
 * Graphics hardware *and* driver used: Intel Corporation Skylake GT2 [HD Graphics 520]
 * 32 or 64 bit: 64
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog: N/A
 ```

Adding a favourite to the menu adds it but you can't see it because the height does not increase. Would easily catch out a newby newby. They would be like "It doesn't work"

**Steps to reproduce**
Add a favourite to the default menu and you will see what I mean

**Expected behaviour**
You should be able to see the new favourite without having to work out that it is the height that needs adjusting

**Other information**
N/A

**Configuration info, if applicable**
If this bug report is related to an Applet, Desklet or Extension, please paste (or use a pastebin service) the offending extension's settings, if it has any.  You can obtain this by opening its configuration, clicking the 'hamburger' button in the upper-right corner of the window, and selecting "Export to a file". **Please be sure to review the contents and remove any personal data it may contain.**

N/A

Please paste here

```

**Comment by NikoKrause** [comment]
You can scroll the favorites. You can also navigate down with the arrow keys on your keyboard.
