### ISSUE TITLE
(regression) JS enviorment set to LTR when using an RTL language (Ex. Hebrew)

### ISSUE THREAD

**Issue by ronyala** [linuxmint/cinnamon#9663]
```
 * Cinnamon version (cinnamon --version) 4.6.7
   - Please specify if you are using the daily builds PPA yes
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) LM 20
 ```

**Issue**

The desktop is set to an LTR interface despite using an RTL language.

**Steps to reproduce**

Update to the latest daily build version.

**Expected behaviour**

RTL interface when using an RTL language.

**Other information**

This happened when I updated my system today.
I did some digging around and I found out that `St.Widget.get_default_direction()` in javascript returns  `St.TextDirection.LTR` instead of `St.TextDirection.RTL`.

~~This is most likely caused by commit 34c4737de5de3fd1941cedd0d454dec47dcbf7e6.~~

**Comment by leigh123linux** [comment]
I doubt it's that commit as you running an older version, that change is in 4.7.0 only

```
$ cinnamon --version
Cinnamon 4.7.0
```

**Comment by leigh123linux** [comment]
The last cinnamon build in the ppa was 20201015 https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds

**Comment by ronyala** [comment]
@leigh123linux you are correct.
I compiled the cinnamon repo after various commits from the last week and this issue actually happens since commit 438e63733f7a397d51acb17b6099e200af42b4b9.
I am unfamiliar with the Meson build system, do I don't know if I can help more then that

**Comment by mtwebster** [comment]
Hi, what does the following return?
```
python3
>>> from gi.repository import Gtk
>>> Gtk.Widget.get_default_direction()
```
and
```
dpkg --list | grep cinnamon
```
and
```
dpkg --list | grep libgtk-3-0
```
I can't get this to reproduce with Hebrew.  The direction is dictated by translations (a magic string is translated one way or another), and this happens in gtk (St uses their value).  Have you added any PPAs lately?

**Comment by ronyala** [comment]
```
python3
>>> from gi.repository import Gtk
>>> Gtk.Widget.get_default_direction()
```
returns `<enum GTK_TEXT_DIR_RTL of type Gtk.TextDirection>`.
Note that at least inside the cinnamon javascript enviorment (tested inside one of the applets), it does return LTR,
`global.log(Gtk.Widget.get_default_direction() === Gtk.TextDirection.LTR)` returned `true`.

```
dpkg --list | grep cinnamon
```
returns
```
ii  cinnamon                                      4.6.7                                 amd64        Modern Linux desktop
ii  cinnamon-common                               4.6.7                                 all          Cinnamon desktop (Common data files)
ii  cinnamon-control-center                       4.6.2+ulyana                          amd64        utilities to configure the Cinnamon desktop
ii  cinnamon-control-center-data                  4.6.2+ulyana                          all          configuration applets for Cinnamon - data files
ii  cinnamon-control-center-dbg                   4.6.2+ulyana                          amd64        utilities to configure the Cinnamon desktop - debug symbols
ii  cinnamon-desktop-data                         4.6.4+ulyana                          all          Common files for Cinnamon desktop apps
ii  cinnamon-l10n                                 4.6.2                                 all          Translation files for the Cinnamon desktop
ii  cinnamon-screensaver                          4.6.0+ulyana                          amd64        Cinnamon screen saver and locker
ii  cinnamon-session                              4.6.2+ulyana                          amd64        Cinnamon Session Manager - Minimal runtime
ii  cinnamon-session-common                       4.6.2+ulyana                          all          Cinnamon Session Manager - common files
ii  cinnamon-settings-daemon                      4.6.4+ulyana                          amd64        daemon handling the Cinnamon session settings
ii  gir1.2-cinnamondesktop-3.0                    4.6.4+ulyana                          amd64        Introspection data for CinnamonDesktop
ii  libcinnamon-control-center1:amd64             4.6.2+ulyana                          amd64        utilities to configure the Cinnamon desktop
ii  libcinnamon-desktop-dbg:amd64                 4.6.4+ulyana                          amd64        Cinnamon library for loading .desktop files - debug symbols
ii  libcinnamon-desktop-dev                       4.6.4+ulyana                          amd64        Cinnamon library for loading .desktop files - development files
ii  libcinnamon-desktop4:amd64                    4.6.4+ulyana                          amd64        Cinnamon library for loading .desktop files
ii  libcinnamon-menu-3-0                          4.6.1+ulyana                          amd64        Cinnamon implementation of the freedesktop menu specification
ii  libcinnamon-menu-3-0-dbg                      4.6.1+ulyana                          amd64        Cinnamon implementation of the freedesktop menu specification
ii  libcinnamon-menu-3-dev                        4.6.1+ulyana                          amd64        Cinnamon implementation of the freedesktop menu specification
ii  libcscreensaver0:amd64                        4.6.0+ulyana                          amd64        library and introspection data used by cinnamon-screensaver
ii  mint-info-cinnamon                            2020.04.06                            all          Necessary information about the Linux Mint release and edition.
```
The `cinnamon` and `cinnamon-common` shown in the output are compiled to commit 438e637, not from daily-builds.
```
dpkg --list | grep libgtk-3-0
```
returns
```
ii  libgtk-3-0:amd64                              3.24.20-0ubuntu1                      amd64        GTK graphical user interface library
ii  libgtk-3-0:i386                               3.24.20-0ubuntu1                      i386         GTK graphical user interface library
```
No, I did not add any PPAs recently.

Just to clarify, the interface inside apps themselves _is_ RTL and texts are in Hebrew correctly, it is only the cinnamon desktop itself (window buttons, applets...) that is Left to Right.

**Comment by mtwebster** [comment]
What version of cjs is on your system? For some reason the build on the ppa hasn't updated since we made some major changes to it (new version of mozjs).

If it's still 4.6 can you build it from git master?

**Comment by ronyala** [comment]
Built cinnamin 4.7 with cjs 4.7 , did not fix the problem

**Comment by leigh123linux** [comment]
Can you post the output for 'locale' command.

**Comment by ronyala** [comment]
```
LANG=he_IL.UTF-8
LANGUAGE=he_IL
LC_CTYPE="he_IL.UTF-8"
LC_NUMERIC=he_IL.UTF-8
LC_TIME=he_IL.UTF-8
LC_COLLATE="he_IL.UTF-8"
LC_MONETARY=he_IL.UTF-8
LC_MESSAGES="he_IL.UTF-8"
LC_PAPER=he_IL.UTF-8
LC_NAME=he_IL.UTF-8
LC_ADDRESS=he_IL.UTF-8
LC_TELEPHONE=he_IL.UTF-8
LC_MEASUREMENT=he_IL.UTF-8
LC_IDENTIFICATION=he_IL.UTF-8
LC_ALL=
```

**Comment by mtwebster** [comment]
I managed to reproduce this on a live cd, thankfully

**Comment by mtwebster** [comment]
Hi, this should be fixed by: https://github.com/linuxmint/cinnamon/commit/4e1a35d6624ee697853363a154550efb298ce2bb
(Only one line affects this issue, the other is minor that I noticed while doing this).

Cinnamon has its translation domain set both in the C layer and js layer. The incorrect name was affecting the C layer, which ended up putting us in a default locale, while the correct name in the js layer still allowed translations to work correctly.

If you want to try these fixes to confirm it, you can close the bug.  Thanks!

**Comment by ronyala** [comment]
Yep, That fixed it!
Regarding the fact that it was on live cd, perhaps it also fixed some much older cases of cinnamon being stuck in LTR when in live cd or after install, but I have my doubts.

And on an unrelated Note regarding `mint-build`, when I was compiling cinnamon 4.7, `mint-build` decided to purge the `cinnamon` package from my system without permission or any notification, which would've broken it if I wouldn't have noiteced it before restarting `cinnamon`. Perhaps `mint-build` shouldn't have the power to remove packages without asking?
