### ISSUE TITLE
Button "Calibrate" in Preferences - Colors doesn't work

### ISSUE THREAD

**Issue by InfoLibre** [linuxmint/cinnamon#9665]
```
 * Cinnamon version 4.6.7
 * No PPA
 * Mint 20 Cinnamon
 * 64 bit
 ```

**Issue**
I calibrated my screen with a Spider 2.
When I plug the spider2, the button **Calibrate** in **Preferences - Colors** doesn't work. Nothing happens, I must manually start DisplayCAL. Same bug if I choose a scanner and click on **Calibrate** button.

![Capture d’écran du 2020-10-20 17-41-20](https://user-images.githubusercontent.com/3955499/96610143-97ee4c00-12fb-11eb-828a-2eb7860df8a1.png)

**Expected behaviour**

After clicking on the button **Calibrate** in **Preferences - Colors**, DisplayCAL or something else should start.

**Comment by InfoLibre** [comment]
**Show details** button works now in Linux Mint Cinnamon 21.

I can't test **Calibrate** button because I don't have Spider 2 anymore. But is Calibrate button still here? I can't see it, even for scanner.

**Comment by mtwebster** [comment]
The calibrate tool is no longer available:
https://github.com/linuxmint/cinnamon-control-center/issues/263
