### ISSUE TITLE
Us who require more than 4 keyboards for inputting/language bar still need a fix (on going issue since 2010)

### ISSUE THREAD

**Issue by tpkyteroo** [linuxmint/cinnamon#9684]
```
 * Cinnamon version (cinnamon --version)
   - Please specify if you are using the daily builds PPA
     (https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds).
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
 * Graphics hardware *and* driver used
 * 32 or 64 bit
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
 ```

**Issue**
Sorry, but no logs because this issue is an issue on intolerance of people who need more than 4 keyboards. We used to have 9 and now limited to only 4?

**Steps to reproduce**
Install OS and then go to menu and find that you can only + 4 keyboards max! 

**Expected behaviour**
The 9 keyboards to be allowed (like it was ages ago). Tolerance for Polyglotters, linguist, missionaries, seminary students, Europeans who speak more than 4 languages, and duolingo users so that we can get our 9 keyboards back! Sure, I'd use 12 (windows and mac both allow 12 keyboards), but right now I'd settle for 9 - that we used to have. 

Many thanks! 
.ps We users have nicely and politely tried to get help in this regard in 2010, 2014, 2017 only to be ignored. At least one person permanently switched to Windows. I'm sure that person was forced to switch to Mac (due to windows blue screen issues.) I can't afford a mac. I would love some tolerance here. 

**Other information**

**Configuration info, if applicable**
If this bug report is related to an Applet, Desklet or Extension, please paste (or use a pastebin service) the offending extension's settings, if it has any.  You can obtain this by opening its configuration, clicking the 'hamburger' button in the upper-right corner of the window, and selecting "Export to a file". **Please be sure to review the contents and remove any personal data it may contain.**

```

Please paste here

```

**Comment by leigh123linux** [comment]
See

https://askubuntu.com/questions/21842/why-is-there-a-4-layouts-limit-for-keyboards/21844#21844


and possible solution


https://itectec.com/ubuntu/ubuntu-cant-add-more-than-four-keyboard-layouts/

**Comment by tpkyteroo** [comment]
The problem was that someone DID change it to ONLY allow 4 keyboards. How do I know this? WAY back in the day, when I was on Ubuntu, we DID have 9 keyboards! I know, because I had all 9 installed on my OS. I forget what flavor Ubuntu was called back then. Sorry! Thanks though! This was before 2010. I was apart of the argument as to why we needed to keep 9 keyboards, but one person was vehemently against it, due to programming headaches, which I do understand. I get it! Thanks again! I'll just have to save for a Mac.
