### ISSUE TITLE
Chromium based Browsers messed up after suspend

### ISSUE THREAD

**Issue by geeks-r-us** [linuxmint/cinnamon#9690]
* Cinnamon 4.6.7
- http://ppa.launchpad.net/linuxmint-daily-build-team/daily-builds/ubuntu focal main

*Desktop*
* Graphics: 
  - Nvidia 1080TI with Driver Version: 450.80.02
* System: 64bit
  - AMD Ryzen 7 1700X Eight-Core Processor  
  - 32 GB Ram

*Thinkpad P52*
* Graphics: 
  - Nvidia Quadro P2000 with Driver Version: 450.80.02
* System: 64bit
  - Intel Xeon E-2176M
  - 32 GB Ram

**Issue**
After system suspend Chromium based browsers are messed up and needs to be restarted.
Same behavior on both systems.

![image](https://user-images.githubusercontent.com/19502312/98347133-4d691100-2017-11eb-8ade-811f33b9f558.png)

Tested so far with:
* Chromium
* Vivaldi
* Chrome
* Brave 

**Steps to reproduce**
* Open Chromium based Browser
* Suspend system
* Wake up again

**Expected behaviour**
Browser works without restart as before system suspend. Should look like this:
![image](https://user-images.githubusercontent.com/19502312/98350565-cff3cf80-201b-11eb-8d07-f57c9437e148.png)

**Comment by fmeneuhe** [comment]
What happens if you disable the hardware acceleration from your browser?

**Comment by geeks-r-us** [comment]
This seems to prevemt the issue
