### ISSUE TITLE
Menu improvment : recently used apps

### ISSUE THREAD

**Issue by MajorGrubert** [linuxmint/Cinnamon#97]
It could be usefull to add a category in menu "recently used apps" (excluding apps in favorites and in launcher).

It could be a category or just icons added in favorite, just like this extension for GS does : https://extensions.gnome.org/extension/75/smart-launcher/ 
It adds 2 icons in favorites for app recently used (the "2" should be set by user / gsetting)

**Comment by mat-m** [comment]
So it is in MATE for Mint 18.3. Any target for Cinnamon ?

**Comment by JosephMcc** [comment]
Thank you for your suggestion. See https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html for information on how we handle feature requests.
