### ISSUE TITLE
Feature Request : Open path in Nemo from the menu on pressing Enter.

### ISSUE THREAD

**Issue by cassepipe** [linuxmint/cinnamon#9702]
***Using***
 * Cinnamon version 4.6.7*
 * Distribution - Mint 20 Ulyana*

**Issue** (?)
When you enter a path in the cinnamon menu, it does not open it.

**(Humble) feature request**
When you enter a path in the Cinnamon menu and press Enter, it could open that location in Nemo.
It could even allow for path completion on pressing tab just like a shell.
If the path is not an absolute path it could default on the home directory as the start of the path.

Thanks for all your hard work and for taking the time to read this.

**Comment by Lurux** [comment]
Ugh I can do that on 19.3, you just need to enable the option under "menu" in the applet preferences

**Comment by cassepipe** [comment]
Cinnamon, you never ceases to impress me.
It even takes path relative to the home folder <3

Indeed all you have to do is right-click on the menu applet -> Configure.. -> Switch to the menu tab -> Under the behavior section
is "Enable filesystem path entry in search box"

At that point, it would be really greedy to ask for tab completion after entering the first "/". I am closing that one.

Thanks @Lurux
