### ISSUE TITLE
Graphical incoherence in window's buttons

### ISSUE THREAD

**Issue by GabiBCN** [linuxmint/cinnamon#9703]
```
 * Cinnamon version
4.6.7+ulyana (last version in Linux Mint 20) (November 14th 2020)
 ```

**Steps to reproduce**
The preinstalled version of Firefox, Epiphany (GNOME web) from the software centre, the official Chromium for Linux Mint (downloaded from official Linux Mint's blog) and default Cinnamon's position of minimize, expand and close buttons are in pretty different positions, and very few programs respect custom icons.

**Other information**
I have checked for updates.

**Comment by Lurux** [comment]
This issue is related to client-side decoration, I'm afraid the Cinnamon team can't do much about it
