### ISSUE TITLE
More than 20 % of Cinnamon users dislike the notifications system

### ISSUE THREAD

**Issue by GabiBCN** [linuxmint/cinnamon#9712]
https://www.reddit.com/r/linuxmint/comments/jtpa0u/what_do_you_think_about_cinnamons_notification/
There should be an easy to find do not disturb button, a way to store notifications in the inbox (useful when you have a lot accumulated; I hate it when I have recieved multiple messages and I have to close notifications one by one taking to much time) and a bigger discard button, in my opinion.

**Comment by Krafting** [comment]
I agree, cinnamon notification are basics but could be way better.

**Comment by NikoKrause** [comment]
More than 77% of Cinnamon users like the notifications system

**Comment by Lurux** [comment]
I love how constructive and positive this issue is.

If you just want to complain why not just go back to the forums ?

**Comment by GabiBCN** [comment]
> I love how constructive and positive this issue is.
> 
> If you just want to complain why not just go back to the forums ?

I'm sorry. I didn't want to seem rude, but I think it was contructive and my intention was not to complain for fun at all.
By the way, and don't get me wrong, I don't want to argue, you aren't being pretty positive and constructive with your sarcastic comment. 🙁

**Comment by icarter09** [comment]
@GabiBCN your comment was not taken as being rude or nonconstructive. Thank you for bring it to our attention that there is a set of users that would like the Notifications to be improved upon. The Mint team have been in talks on how better to improve the Notifications. Do not let others stop you from creating feature requests or issues in the future. Thanks.

**Comment by Lurux** [comment]
> I'm sorry. I didn't want to seem rude, but I think it was contructive and my intention was not to complain for fun at all.
> By the way, and don't get me wrong, I don't want to argue, you aren't being pretty positive and constructive with your sarcastic comment. slightly_frowning_face

Yeah sorry I was upset for personal reasons. I still think the issue could have been phrased more positively, but I answered just as negatively as you did and that was bad on me. Sorry 'bout that !

> @GabiBCN your comment was not taken as being rude or nonconstructive. Thank you for bring it to our attention that there is a set of users that would like the Notifications to be improved upon. The Mint team have been in talks on how better to improve the Notifications. Do not let others stop you from creating feature requests or issues in the future. Thanks.

Sorry for answering a bit hardly, I just want to make clear I did not intend to invalidate @GabiBCN's propositions, only the way he expressed the issue.
