### ISSUE TITLE
Cinnamon 4.8 breaks media keys

### ISSUE THREAD

**Issue by atiredman** [linuxmint/cinnamon#9732]
```
 * Cinnamon version: 4.8.0
 * Distribution: Arch
 * Graphics hardware *and* driver used: NVIDIA GeForce GTX 1660 Ti Mobile, driver version 455.45.01-2
 * 32 or 64 bit: 64 bit
 ```

**Issue**
Since upgrading to Cinnamon 4.8.0 media keys no longer have any effect in media players. I have tested play, pause, stop, forward, and backward in 3 different media players (Lollypop, Celluloid/MPV, and Pragha) clicking the media keys brings up an on screen display indicating no media is playing. 

As I do get an indicator when clicking the media keys I suspect the issue is not with the media keys themselves but with Cinnamon not detecting media is playing. Downgrading to Cinnamon 4.6.7 fixes this issue and media keys can control playback.

**Steps to reproduce**
Upgrade to Cinnamon 4.8.0, open some media and attempt to use media keys to control it.

**Expected behaviour**
Media keys can be used to control media.

**Other information**
Laptop is a Lenovo Y540

**Comment by ItzSwirlz** [comment]
Okay-I have a feeling it's a possible but extremely unlikely regression of this-did you built cinnamon-settings-daemon 4.8.1 or after this commit? https://github.com/linuxmint/cinnamon-settings-daemon/commit/7daaa5c58181430ef7d8b63b73c2a5a8d8d4a442

I can't find anything else with media keys that were updating in between 4.6.7 and 4.8.
