### ISSUE TITLE
add scaling up to 300% for 13 inch 4k displays

### ISSUE THREAD

**Issue by ppapachiou** [linuxmint/cinnamon#9744]
System:    Kernel: 5.8.0-31-generic x86_64 bits: 64 compiler: N/A Desktop: Cinnamon 4.6.7 
           wm: muffin dm: LightDM Distro: Linux Mint 20 Ulyana base: Ubuntu 20.04 focal 
Machine:   Type: Laptop System: Dell product: XPS 13 9380 v: N/A serial: <filter> Chassis: 
           type: 10 serial: <filter> 
           Mobo: Dell model: 0KTW76 v: A00 serial: <filter> UEFI: Dell v: 1.11.0 date: 07/06/2020 
Battery:   ID-1: BAT0 charge: 47.2 Wh condition: 48.6/52.0 Wh (93%) volts: 8.5/7.6 
           model: SMP DELL G8VCF6C serial: <filter> status: Discharging 
CPU:       Topology: Quad Core model: Intel Core i7-8565U bits: 64 type: MT MCP arch: Kaby Lake 
           rev: C L2 cache: 8192 KiB 
           flags: avx avx2 lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx bogomips: 31999 
           Speed: 700 MHz min/max: 400/1400 MHz Core speeds (MHz): 1: 700 2: 700 3: 700 4: 700 
           5: 700 6: 700 7: 700 8: 700 
Graphics:  Device-1: Intel UHD Graphics 620 vendor: Dell driver: i915 v: kernel bus ID: 00:02.0 
           chip ID: 8086:3ea0 
           Display: x11 server: X.Org 1.20.8 driver: modesetting unloaded: fbdev,vesa 
           resolution: 1280x720~60Hz 
           OpenGL: renderer: Mesa Intel UHD Graphics 620 (WHL GT2) v: 4.6 Mesa 20.0.8 
           direct render: Yes 
Audio:     Device-1: Intel Cannon Point-LP High Definition Audio vendor: Dell 
           driver: snd_hda_intel v: kernel bus ID: 00:1f.3 chip ID: 8086:9dc8 
           Sound Server: ALSA v: k5.8.0-31-generic 
Network:   Device-1: Qualcomm Atheros QCA6174 802.11ac Wireless Network Adapter 
           vendor: Bigfoot Networks Killer 1435 Wireless-AC driver: ath10k_pci v: kernel 
           port: efa0 bus ID: 02:00.0 chip ID: 168c:003e 
           IF: wlp2s0 state: up mac: <filter> 
           IF-ID-1: docker0 state: down mac: <filter> 
Drives:    Local Storage: total: 476.94 GiB used: 96.41 GiB (20.2%) 
           ID-1: /dev/nvme0n1 vendor: Samsung model: PM981 NVMe 512GB size: 476.94 GiB 
           speed: 31.6 Gb/s lanes: 4 serial: <filter> 
Partition: ID-1: / size: 176.66 GiB used: 96.34 GiB (54.5%) fs: ext4 dev: /dev/nvme0n1p3 
Sensors:   System Temperatures: cpu: 38.0 C mobo: N/A 
           Fan Speeds (RPM): cpu: 0 fan-2: 0 
Repos:     No active apt repos in: /etc/apt/sources.list 
           Active apt repos in: /etc/apt/sources.list.d/additional-repositories.list 
           1: deb [arch=amd64] https: //download.docker.com/linux/ubuntu focal stable
           Active apt repos in: /etc/apt/sources.list.d/devolo-updates.list 
           1: deb http: //update.devolo.com/linux/apt/ stable main
           Active apt repos in: /etc/apt/sources.list.d/google-chrome.list 
           1: deb [arch=amd64] http: //dl.google.com/linux/chrome/deb/ stable main
           Active apt repos in: /etc/apt/sources.list.d/kismet.list 
           1: deb https: //www.kismetwireless.net/repos/apt/release/focal focal main
           Active apt repos in: /etc/apt/sources.list.d/microsoft-edge-dev.list 
           1: deb [arch=amd64] http: //packages.microsoft.com/repos/edge/ stable main
           Active apt repos in: /etc/apt/sources.list.d/nextcloud-devs-client-focal.list 
           1: deb http: //ppa.launchpad.net/nextcloud-devs/client/ubuntu focal main
           Active apt repos in: /etc/apt/sources.list.d/official-package-repositories.list 
           1: deb http: //packages.linuxmint.com ulyana main upstream import backport
           2: deb http: //archive.ubuntu.com/ubuntu focal main restricted universe multiverse
           3: deb http: //archive.ubuntu.com/ubuntu focal-updates main restricted universe multiverse
           4: deb http: //archive.ubuntu.com/ubuntu focal-backports main restricted universe multiverse
           5: deb http: //security.ubuntu.com/ubuntu/ focal-security main restricted universe multiverse
           6: deb http: //archive.canonical.com/ubuntu/ focal partner
           Active apt repos in: /etc/apt/sources.list.d/slimbook-slimbook-focal.list 
           1: deb http: //ppa.launchpad.net/slimbook/slimbook/ubuntu focal main
           Active apt repos in: /etc/apt/sources.list.d/softmaker.list 
           1: deb http: //shop.softmaker.com/repo/apt wheezy non-free
           Active apt repos in: /etc/apt/sources.list.d/spotify.list 
           1: deb http: //repository.spotify.com stable non-free
           Active apt repos in: /etc/apt/sources.list.d/team-xbmc-ppa-focal.list 
           1: deb http: //ppa.launchpad.net/team-xbmc/ppa/ubuntu focal main
           Active apt repos in: /etc/apt/sources.list.d/teamviewer.list 
           1: deb https: //linux.teamviewer.com/deb stable main
Info:      Processes: 292 Uptime: 5m Memory: 15.29 GiB used: 1.67 GiB (10.9%) Init: systemd v: 245 
           runlevel: 5 Compilers: gcc: 9.3.0 alt: 9 Client: Unknown python3.8 client inxi: 3.0.38

**Comment by mtwebster** [comment]
Hi, I uploaded some packages here:
https://www.dropbox.com/sh/krvfw58fk1mu04o/AADPEmJcZAK-tJWLFDsO49M2a?dl=0

Download them all to a folder. I'm not sure what you have installed so I would set the -dbg and -dev packages aside unless the installation complains about them being missing. (If you just install everything, it may force you to install a number of additional packages you didn't need).

Once it's all installed you should be able to set global and fractional scaling up to 3x. You need to log out and back in before attempting to use it.

Let me know how it works or if you have issues. Remember if something goes horribly wrong, delete ~/.config/cinnamon-monitors.xml and log out/in.

This only increases the hard limit to 3x - I'm not sure if there's need to go higher at this point (for future-proofing), but I'm still considering it.

**Comment by ppapachiou** [comment]
I installed all the packages except for the dev ones.  Logout out and then in, and I was able to select 300% which worked fine.
The sweet-spot for my needs is at 275^.  I will take some time using this scaling and get back to you.

Thanks a lot,
Panayiotis

**Comment by NikoKrause** [comment]
Are you using Mint-Y icons? Do they look blurry with 300%?

**Comment by ppapachiou** [comment]
> Are you using Mint-Y icons? Do they look blurry with 300%?

I use Mint-Y icons and they look  sharp enough to me.

**Comment by ppapachiou** [comment]
I have a problem with the pointer size.  The largest setting provides a small pointer  I think it should provide for at least twice as large pointers.

**Comment by JosephMcc** [comment]
I'm a little curious here. Your screen resolution says it's only 1280x720 unless I'm missing something. I'm curious what the actual resolution is you are trying to scale up from.

**Comment by ppapachiou** [comment]
> I'm a little curious here. Your screen resolution says it's only 1280x720 unless I'm missing something. I'm curious what the actual resolution is you are trying to scale up from.

I was running at the lower resolution as I did not have the option for up to 300%.  The following is while running the 3x scaling:
System:    Kernel: 5.8.0-33-generic x86_64 bits: 64 compiler: N/A Desktop: Cinnamon 4.6.7 
           wm: muffin dm: LightDM Distro: Linux Mint 20 Ulyana base: Ubuntu 20.04 focal 
Machine:   Type: Laptop System: Dell product: XPS 13 9380 v: N/A serial: <filter> Chassis: 
           type: 10 serial: <filter> 
           Mobo: Dell model: 0KTW76 v: A00 serial: <filter> UEFI: Dell v: 1.11.0 date: 07/06/2020 
Battery:   ID-1: BAT0 charge: 24.6 Wh condition: 42.7/52.0 Wh (82%) volts: 7.4/7.6 
           model: SMP DELL G8VCF6C serial: <filter> status: Discharging 
CPU:       Topology: Quad Core model: Intel Core i7-8565U bits: 64 type: MT MCP arch: Kaby Lake 
           rev: C L2 cache: 8192 KiB 
           flags: avx avx2 lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx bogomips: 31999 
           Speed: 700 MHz min/max: 400/1400 MHz Core speeds (MHz): 1: 700 2: 700 3: 700 4: 700 
           5: 700 6: 700 7: 700 8: 700 
Graphics:  Device-1: Intel UHD Graphics 620 vendor: Dell driver: i915 v: kernel bus ID: 00:02.0 
           chip ID: 8086:3ea0 
           Display: x11 server: X.Org 1.20.8 driver: modesetting unloaded: fbdev,vesa 
           resolution: 3840x2160~60Hz 
           OpenGL: renderer: Mesa Intel UHD Graphics 620 (WHL GT2) v: 4.6 Mesa 20.0.8 
           direct render: Yes
