### ISSUE TITLE
Graphical Glitch

### ISSUE THREAD

**Issue by linusrg1** [linuxmint/cinnamon#9749]
```
 * Cinnamon version (cinnamon --version)
   - Please specify if you are using the daily builds PPA
     (https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds).
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 20
 * Graphics hardware *and* driver used Nvidia 1660 super
 * 32 or 64 bit 64 bit
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
 ```

**Issue**
When watching youtube in firefox if not in fullscreen desktop bleeds through to the video

**Steps to reproduce**
Watch youtube video in not full screen that has a large portion of black.

**Expected behaviour**
Cannot see background through video

**Other information**

**Configuration info, if applicable**
If this bug report is related to an Applet, Desklet or Extension, please paste (or use a pastebin service) the offending extension's settings, if it has any.  You can obtain this by opening its configuration, clicking the 'hamburger' button in the upper-right corner of the window, and selecting "Export to a file". **Please be sure to review the contents and remove any personal data it may contain.**

```

Please paste here

```

**Comment by ItzSwirlz** [comment]
Can you add a little bit more information? Do you minimize firefox?

**Comment by icarter09** [comment]
I'm not able to reproduce this issue. Watched several videos on youtube in Firefox and had no bleed through.
