### ISSUE TITLE
Running cinnamon-session triggers kernel crash with immediate reboot

### ISSUE THREAD

**Issue by dikonov** [linuxmint/cinnamon#9752]
```
 * Cinnamon version (cinnamon --version)  
     4.6.7
 * Distribution 
     ALTLinux P9, Sisyphus
 * Graphics hardware *and* driver used
     Intel UHD 630 9bc5    (i915)
 * 32 or 64 bit
    64
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
    .xsession-errors contains:

libva error: /usr/lib64/dri/i965_drv_video.so init failed
[3571:3571:1206/135917.074113:ERROR:vaapi_wrapper.cc(541)] vaInitialize failed: unknown libva error
[3571:3571:1206/135917.076827:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.

 ```

**Issue**
Executing cinnamon-session (or startcinnamon) causes and immediate halt of the whole OS and reboot. Other DEs (mate, gnome, enlightenment) work well.

**Steps to reproduce**
Try to start cinnamon.

**Other information**
This is likely to be caused by another bug in the i915 kernel driver. I would be happy, if cinnamon becomes more stable and resilient to such problems, like other DEs already are.
```

**Comment by leigh123linux** [comment]
4.6.7 works fine here using the Intel driver.
Perhaps you should file the issue at the ALTLinux bug tracker.

**Comment by dikonov** [comment]
Already there [Bug 39391](https://bugzilla.altlinux.org/show_bug.cgi?id=39391), but it seems to be a twofold problem of the kernel driver for intel graphis i915 and cinnamon. The driver crashes the kernel and cinnamon does something unusual that triggers the crash. Other DEs, including gnome-shell and mate are not affected.

**Comment by dikonov** [comment]
There are many different intel graphics chips. Most work properly. This particular one is called 9bc5 and is part of a new 2020 motherboard MSI MEG z490i Unify.
