### ISSUE TITLE
Screenshot issues

### ISSUE THREAD

**Issue by Salamandar** [linuxmint/cinnamon#9759]
```
 * Cinnamon 4.8.0
 * Manjaro
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
 ```

**Issue**

Screenshot with shortcut does not work :
* shitf-printscreen works, but it puts the screenshot in the clipboard instead of Pictures directory
* Other shortcuts do not work

This issues is kinda new because it worked some days ago. Also, I just installed Manjaro Cinnamon and the issue is here on the new installation.

Here is the `tail -f .xsession-errors` while doing some shortcuts :
```
# prscreen
** (csd-media-keys:22271): WARNING **: 17:41:42.017: Error calling method GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: La méthode « Repeat » n’existe pas

# shift-prscreen
** (csd-media-keys:22271): WARNING **: 17:41:35.339: Unable to grab the keyboard/mouse prior to running: gnome-screenshot --area --clipboard

# ctrl-prscreen
** (csd-media-keys:22271): WARNING **: 17:41:58.015: Error calling method GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: La méthode « Shuffle » n’existe pas

# alt-prscreen
** Message: 17:43:44.764: Unable to use GNOME Shell's builtin screenshot interface, resorting to fallback X11.

```

**Comment by Salamandar** [comment]
Also, when I go in settings > shortcuts, all is as expected. I also can change the shortcuts (by pressing shift-prscreen for example) but it doesn't help.

**Comment by mtwebster** [comment]
cinnamon-settings-daemon 4.8 needs to be rebuilt against cinnamon-desktop 4.8

**Comment by Salamandar** [comment]
Is it something I can do ? The package for cinnamon-settings-daemon is 4.8.1-1 here.

**Comment by mtwebster** [comment]
You could I imagine, but you're better off telling your maintainer there maybe, so it can be fixed

**Comment by mtwebster** [comment]
Ok cool
