### ISSUE TITLE
Feature request: Gestures

### ISSUE THREAD

**Issue by GabiBCN** [linuxmint/cinnamon#9760]
https://blog.elementary.io/multitouch-gestures-in-elementary-os-6/

Elementary OS is going to implement gestures by tweaking Touchegg (to make its interface look cleaner), and I feel a little jealous XD. Gestures make people feel like more comfortable, and are one of the reasons why people use Mac OS.

Thanks for your attention.

**Comment by KevinNadaud** [comment]
It seems this feature is also is gnome using few things:
[https://extensions.gnome.org/extension/4033/x11-gestures/](https://extensions.gnome.org/extension/4033/x11-gestures/) 
[https://github.com/JoseExposito/touchegg](https://github.com/JoseExposito/touchegg) 
I do not know if it can be easily transpose to cinnamon.

**Comment by Secret-chest** [comment]
Should be closed as they were added in Victoria.
