### ISSUE TITLE
4.8.2 doesn't use bold fonts

### ISSUE THREAD

**Issue by IvoAndonov** [linuxmint/cinnamon#9766]
Cinnamon version: 4.8.2
        Please specify if you are using the daily builds PPA: IDK - whatever comes from Arch repository, that's it.
    Distribution - (Arch)
    Graphics hardware and driver used: GTX 1660 Ti, driver version 450.57
    Architecture: 64-bit

**Issue**
This problem is present ever since updating to 4.8.0. I thought I could fix it myself but I couldn't.
I've set all fonts in the system to be bold, desktop included, but they're no longer bold for the desktop:

![2020-12-11_17-56-02](https://user-images.githubusercontent.com/41172201/101925748-e2dd5f00-3bda-11eb-823b-3953a0ee9358.png)

I tried to fix it by editing /home/rado/.config/gtk-3.0/gtk.css and setting "font-weight: bold;" and restarting Cinnamon but it didn't work. My custom text outlining is still working but fonts being bold - doesn't.
I also tried deleting everything in /tmp and /.cache, even updated icons cache - still no change.

**Steps to reproduce**
1. Set desktop fonts to bold.
2. Update Cinnamon 4.6.4 to 4.8.0 and reboot.

**Expected behaviour**
When a bold font is set, the characters of icons on the desktop should become thicker (bold).

**Other information**

[xsession-errors.txt](https://github.com/linuxmint/cinnamon/files/5680230/xsession-errors.txt)

**Comment by bongochong** [comment]
Noticed this after upgrading Fedora's Cinnamon spin yesterday. Came here to create a new issue myself. Glad someone got to it first.

**Comment by mmatis** [comment]
Performed the same steps as IvoAndonov including editing the theme itself with the same result. I am on Linux Mint 20.1.

**Comment by IvoAndonov** [comment]
This DE is going from bad to worse. With update 4.8.6 now all bold fonts in terminal disappeared as well. It's like someone from the developers wants to enforce on us thin fonts. What's next? No bold fonts for the clock?

**Comment by bongochong** [comment]
>With update 4.8.5 now all bold fonts in terminal disappeared as well... 
I would imagine that this is a separate issue with whatever terminal emulator you're using. I use Terminator and bold fonts are displayed properly.
