### ISSUE TITLE
Running cinnamon-session triggers kernel crash with immediate reboot

### ISSUE THREAD

**Issue by dikonov** [linuxmint/cinnamon#9769]
```
* Cinnamon version (cinnamon --version)  
     4.6.7
 * Distribution 
     ALTLinux P9, Sisyphus
 * Graphics hardware *and* driver used
     1) Intel UHD 630 9bc5    (i915, kernels 5.4.81, 5.4.82)
     2) Nvidia RTX2070         (nvidia binary driver 450.80.02)

     motherboard: MSI MEG z490i Unify
     CPU intel 10700
 * 32 or 64 bit
    64
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
    .xsession-errors contains:
   The crash happens in such a way that no logs are being saved or shown.
```

**Issue**
Executing cinnamon-session (or startcinnamon) causes and immediate halt of the whole OS and reboot. Other DEs (mate, gnome, enlightenment) work well.
This happens with two entirely different GPUs and unrelated drivers: 
- i915 from kernel  (Intel UHD 630 **9bc5**)
- nvidia blob 450.80.02    (RTX2070)
The difference is that intel crashes immediately on cinnamon launch. Nvidia crashes in the same way when I try to change GTK theme.  Mate and Gnome-shell do not crash. 

I observed the crash on Linux kernels 5.4.81 and 5.4.82.

**Steps to reproduce**
Run cinnamon using the same or similar hardware.

**Other information**
The reason for closing the duplicate bug #9752 seems invalid to me because the crash happens with different video drivers but only in cinnamon. 

Please, consider the possibility of some cinnamon component doing nasty things to video drivers.

**Comment by leigh123linux** [comment]
Your report is useless without a backtrace and logging.
