### ISSUE TITLE
Redshift does not work and searching on the web turns up multiple complaints about this or some similar issue in recent Mint versions.

### ISSUE THREAD

**Issue by CJSHayward** [linuxmint/cinnamon#9772]
```
 * Cinnamon version (cinnamon --version)
4.6.7
   - Please specify if you are using the daily builds PPA
     (https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds).
No.
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
Mint 20
 * Graphics hardware *and* driver used
On-motherboard graphics card on Intel I7 7th gen. I haven't observed graphics flukes.
 * 32 or 64 bit
64
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
 ```
Side note that may merit its own issue: my version of Chrome has a file chooser that does not show dotfiles, at least not as I could tell at a glance. I copied ~/.xsession-errors to /tmp/xsession-errors, tried to upload that, got an error message saying it was an unsupported file type, and renamed it to /tmp/xsession-errors.txt. **This is painful UX.**

[xsession-errors.txt](https://github.com/linuxmint/cinnamon/files/5686244/xsession-errors.txt)

**Issue**

redshift-gtk does nothing that I can discern. redshift when run displays the following and then hangs:

```
$ redshift
Trying location provider `geoclue2'...
Using provider `geoclue2'.
Using method `randr'.
Waiting for initial location to become available...
Location: 41.85 N, 88.08 W
```

**Steps to reproduce**

On Mint 20 Cinnamon, and from my web search on versions as far back as 17.x, redshift is inoperable. There's software there, and I can execute it, but I have so far managed *neither* to adjust my screen's color temperature, nor to get the *redshift-gtk* UI to display, *nor* to get redshift visible as a listed available app to cairo-dock 3.4.1.

**Expected behaviour**

Expected behavior is that I can add redshift-gtk to my dock, and click on it, and get UI to configure it to my tastes, or barring that run redshift from the command and possibly a custom launcher.

In addition, I would like the program to serve its purpose of selectively delivering a lower color temperature at times there wouldn't be much natural light (or perhaps other preferences as selected in redshift-gtk UI).

**Other information**

Some of the pages that have come up include:

https://itsfoss.com/install-redshift-linux-mint/ (says to install geoclue-2.0; this was already installed on my system)
https://www.reddit.com/r/linuxmint/comments/gclq39/how_to_manually_adjust_redshift_intensity_in/
https://cinnamon-spices.linuxmint.com/applets/view/296

Multiple users on multiple Linux Mint versions/configurations are reporting serious breakage with getting usable redshift functionality. Qredshift sounds good but it does not appear to be visible in default package repositories.

**Configuration info, if applicable**
If this bug report is related to an Applet, Desklet or Extension, please paste (or use a pastebin service) the offending extension's settings, if it has any.  You can obtain this by opening its configuration, clicking the 'hamburger' button in the upper-right corner of the window, and selecting "Export to a file". **Please be sure to review the contents and remove any personal data it may contain.**

Nothing I noticed:

```
$ ls ~/.*redshift*
ls: cannot access '/home/christos/.*redshift*': No such file or directory
$

```

```

Please paste here

```

Thanks,
[C.J.S. Hayward](https://cjshayward.com)

**Comment by Ammako** [comment]
Try adding custom config to use manual location instead of using online location, and see if it works that way.

```
[redshift]
; Set the day and night screen temperatures
temp-day=5500
temp-night=2700

; enabling smooth transition
transition=1

adjustment-method=randr

; Now specify the location manually
location-provider=manual

[manual]
; use the Internet to get your latitudes and longitudes
lat=41.85
lon=-88.08
```

In ~/.config/redshift.conf

(Of course, adjust temperatures to your preferences, and if these coordinates aren't actually the correct ones, look up the coordinates online for your location and enter those in instead.)

**Comment by leigh123linux** [comment]
Report the issue against redshift.

geoclue2 needs adjustment to allow redshift access

https://wiki.archlinux.org/index.php/redshift#Automatic_location_based_on_GeoClue2
