### ISSUE TITLE
Website has blocker missing link to get on to reporting bug on https://linuxmint.com/getinvolved.php and more problematically https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html#why-are-ideas-and-feature-requests-closed

### ISSUE THREAD

**Issue by CJSHayward** [linuxmint/cinnamon#9773]
**Note to developers: I didn't find an obvious candidate for where to put this. Please feel free to migrate this report to a more appropriate place. *This is a website IA/UX defect AFAICT.***

```
 * Cinnamon version (cinnamon --version)
4.6.7
   - Please specify if you are using the daily builds PPA
     (https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds).
No
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
Mint 20
 * Graphics hardware *and* driver used
On motherboard graphics card.
 * 32 or 64 bit
64 bit
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
N/A
 ```

**Issue**

I went to report another defect, navigated to [Get Involved](https://linuxmint.com/getinvolved.php). The section relevant to reporting issues has a link to [the Linux Mint Troubleshooting Guide](https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/) but not any Linux Mint-related troubleshooting guide that I could tell.

Also, and specifically, [the last page of the FAQ](https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html) has no "Continue to submit an issue" button at the bottom right, nor anywhere else on the page AFAICT, apart from an "Edit on Github" link in the top banner.

**Steps to reproduce**

1. Go to linuxmint.com (using Chrome on Ulyana).
2. Go to the Project menu heading.
3. Click on "Get Involved."
4. Try to find a direct link to open a ticket. *I failed when I tried.*
5. Click on "Linux Mint Troubleshooting Guide."
6. Follow your nose and keep scrolling down and clicking on "Next" until you reach the last page.
7. Try to find a direct link to open a ticket. *I failed to do this here too.*

**Expected behaviour**

The "Get Involved" page should have a link to open an issue even if you try to steer new issue reporters to Issue Reporting 101 on readthedocs.

The end of the Linux MInt Troubleshooting Guide should show an obvious link to now report an issue.

**Other information**

I consider this an IA/UX blocker in severity.

**Configuration info, if applicable**
If this bug report is related to an Applet, Desklet or Extension, please paste (or use a pastebin service) the offending extension's settings, if it has any.  You can obtain this by opening its configuration, clicking the 'hamburger' button in the upper-right corner of the window, and selecting "Export to a file". **Please be sure to review the contents and remove any personal data it may contain.**

```

Please paste here

```

Thanks,
[C.J.S. Hayward](https://cjshayward.com)

**Comment by icarter09** [comment]
There is a link on the Linux Mint Troubleshooting Guide under "Reporting Bugs" -> "Where".

`When reporting a bug to one of these teams, try to find the compoment on the Linux Mint Github site.` With "Linux Mint Github site" as a link.
