### ISSUE TITLE
cinnamonsetting.py: cannot change / remove ALT+F7 "window resize" shortcut !

### ISSUE THREAD

**Issue by afkrause** [linuxmint/cinnamon#9777]
```
 * Cinnamon version: 4.6.7
   - Please specify if you are using the daily builds PPA: NO
 * Distribution: Mint 20
 ```

**Issue**
the default keyboard binding ALT+F7 for "window-resize" cannot be modified or removed, because it is not listed  in cinnamon-settings.py .

but ALT-F7 interferes with Doublecommanders ALT-F7 search command.

**Steps to reproduce**

**Expected behaviour**

**Other information**

**Configuration info, if applicable**
If this bug report is related to an Applet, Desklet or Extension, please paste (or use a pastebin service) the offending extension's settings, if it has any.  You can obtain this by opening its configuration, clicking the 'hamburger' button in the upper-right corner of the window, and selecting "Export to a file". **Please be sure to review the contents and remove any personal data it may contain.**

```

Please paste here

```

**Comment by icarter09** [comment]
Cinnamon 4.8.6
Mint 20.1 64bit

I'm not able to reproduce this. I see that `Resize window` is mapped to `Alt+F8` and `Move window` is mapped to `Alt+F7`. I'm able to map either one of them to other keybindings. 

@afkrause are you still experiencing this issue?

**Comment by afkrause** [comment]
no, this seems to be fixed with linux mint 20.1!
thank you very much!

**Comment by MarkJeronimus** [comment]
I have cinnamon 5.2.7 and I can't find these two settings in the Keyboard/Shortcuts dialog. I checked all categories.

**Comment by mtwebster** [comment]
![image](https://github.com/linuxmint/cinnamon/assets/262776/69d8b48d-8264-474c-939d-939524de5aaa)
