### ISSUE TITLE
Disable Alt+Tab Q feature

### ISSUE THREAD

**Issue by Philipp91** [linuxmint/cinnamon#9787]
```
 * Cinnamon 4.6.7
 * Distribution - proprietary
 * 64 bit
 ```

**Issue**

Windows are closed by accident when I use the Alt+Tab window switcher, specifically when pressing Q while it's open. This problem is worsened by the fact that Q is so close to Tab on the keyboard, and also because I use Alt+Q itself as a shortcut in Chrome to toggle between tabs (so my brain decides very late whether it wants to hit Tab or Q, and thus the finger often lands in between).

Users have asked about this issue before:
* https://forums.linuxmint.com/viewtopic.php?t=284426
* https://www.reddit.com/r/linuxquestions/comments/fsssw9/disable_alt_tab_q_keybind_for_cinnamon/

This matters because closing windows can mean data loss or other kinds of pain. E.g. Chrome windows can have many many tabs open and there's no easy way to make Chrome ask before closing a window.

**Steps to reproduce**

* Open at least two windows.
* Press and hold Alt.
* Press and release Tab. The window switcher will open and select the "other" window.
* Press Q. The selected window is closed.

While this behavior is "as implemented", it's not intended by the user when they press `Alt+Tab+Q` or `Alt+Tab Q` very quickly. In particular this happens when hitting the Tab and Q buttons with one finger around the same time by accident.

**Expected behaviour**

Either nothing happens when Q is pressed (not sure how many users even use this as a feature to close windows on purpose), or the behavior should be configurable. I can think of two ways to configure this:

1. Add "Q" or "Alt+Q" as the default (but removable) shortcut in the "Keyboard" settings.
2. In the "Windows" settings on the tab "Alt-Tab" add a boolean to disable the Q=close behavior.

**Comment by Philipp91** [comment]
This behavior is really annoying me. I have a workaround for my most important Chrome windows, keeping an "edited" tab open that prevents them from being closed, but sometimes I accidentally close some window and then don't even know anymore what it was (there's no "Undo" feature like with Chrome tabs, where I can press Ctrl+Shift+T to re-open the most recently closed one), until much later when I realize what is missing. And even when the window protects itself from being closed, it still interrupts my whole workflow/concentration. I'm seriously thinking of migrating to another window manager to work around this issue.

Does anyone know a workaround that works globally? Can I use a different window switcher that doesn't do this?

**Comment by RedBearAK** [comment]
I understand the pain of this. But to be fair to the Cinnamon team for a moment, "Q" is commonly associated with [Q]uitting applications on all platforms, not just Linux DEs. It works exactly the same way in the macOS app switcher, but I never noticed for decades because I always stayed well away from touching the "Q" and "W" keys while switching apps. 

I'm looking into the possibility of using a python utility call `xkeysnail` to provide a band-aid solution for this, but I will need to figure out if there is a way to determine the WM_CLASS name of the Alt+Tab switcher dialog, if it even has one. 

In the meantime I strongly advise you to break the habit of using the "Q" key for anything other than [Q]uit. As you've seen, it's an extremely problematic choice for something as innocuous and common as tab navigation. 

At the same time, I would also advocate to the Cinnamon team to make this a configurable option in the Windows preferences. It shouldn't be difficult to allow it to be disabled.

**Comment by Philipp91** [comment]
Thank you.

I guess Alt+Q is a [common](https://chrome.google.com/webstore/detail/alt-%20-q-switch-recent-act/odhjcgnlbagjllfbilicalpigimhdcll) [choice](https://chrome.google.com/webstore/detail/quickey-%E2%80%93-the-quick-tab-s/ldlghkoiihaelfnggonhjnfiabmaficg) for Chrome tab switching because Q is next to Tab and the feature is conceptually similar to Alt+Tab for OS-level windows.

And even if it weren't for those Chrome extensions, Q can still be hit by accident when using the Alt+Tab switcher just due to its proximity. E.g. when I switch between ergonomic and non-ergonomic keyboards (external vs laptop-internal), the Alt-to-Tab axis is rotated a bit, so muscle memory can easily hit the wrong spot.

**Comment by RedBearAK** [comment]
@Philipp91 

> And even if it weren't for those Chrome extensions, Q can still be hit by accident when using the Alt+Tab switcher just due to its proximity. E.g. when I switch between ergonomic and non-ergonomic keyboards (external vs laptop-internal), the Alt-to-Tab axis is rotated a bit, so muscle memory can easily hit the wrong spot.

Very true. I never really liked those curved ergonomic keyboards for that very reason. 

All right, it took me quite a while to figure out if this was even possible. But if you're willing to follow these instructions, this should basically "patch" your Alt+Q problem in all practical terms. Don't worry, it's not as complicated as it looks. You're just going to install an application, turn it off, replace its config file with a new one, and then turn it back on. In a nutshell. 

This will remap the key codes when you press Alt+Q to [Esc]ape whenever you aren't using Chrome, and when you are using Chrome it will remap Alt+Q to Alt+W. So the worst that should happen when you accidentally press Alt+Q is that you get kicked out of the app switcher. Then you can just hit Tab again (if you're still holding down Alt) to continue switching. 

Don't ask why it has to be mapped to Alt+W, I really don't know for sure. I just know it can't be mapped to Alt+Q in Chrome or you will always be [Q]uitting applications accidentally in the Alt+Tab switcher. 

If you're following along this means, yes, you will need to change the keyboard shortcut that activates your tab switching extension in Chrome. Which is very easy to do in Chrome. But you'll still be physically pressing Alt+Q to switch tabs. If that's what you want. I assume so. 

To understand what you're about to do, xkeysnail is a (python, I think?) utility that is able to completely remap modifier keys and key combinations all over your keyboard. Another python application called Kinto.sh (by Ben Reaves), uses this tool with a pre-configured config file to make a Linux keyboard behave as if it is a Mac keyboard. But you probably don't want Mac-style keyboard shortcuts like I do (Alt becomes Cmd key, Win becomes Alt/Option key, and lots of Mac-like shortcuts are defined). So I have a copy of the config file that is completely stripped down to just do exactly one thing: Remap Alt+Q. 

On my machine, Linux Mint 20.1, Cinnamon desktop, this works. Hopefully it will work for you too. Should work fine in other desktop environments also. 

You'll need to install Kinto.sh. It should put a handy tray icon (a big "K") in the indicator tray on the panel, that will allow you to start and stop the xkeysnail service. When you first install Kinto.sh in Cinnamon on Mint, Alt+Tab won't work right when Kinto.sh is active. So just click on the "K" icon in the tray and Stop the service, and everything will go back to normal. Then you can replace the default Kinto.sh config file with my stripped-down config file, and use the tray icon to restart it. Then you can fix the keyboard shortcut assigned to the Chrome extension, and go on about your life. 

STEP BY STEP: 

To install Kinto.sh: 

Open a terminal. Then paste these commands one at a time: 

```
cd ~/Downloads

git clone https://github.com/rbreaves/kinto.git

cd kinto

./setup.py
```

On a new system this will usually need to download and install a number of different packages, which could take a little while, and then eventually you will see a dialog that will ask you to press the key on your keyboard just to the left of the Alt key. (Usually that will be the Win/Super key.) This is for the Mac-style remapping stuff, it's identifying your keyboard type. Just complete the install, and then you'll see a strange little window that sort of looks like a small terminal, but it's the early stages of a Kinto.sh GUI application: 

![kinto_GUI_active](https://user-images.githubusercontent.com/64876997/111020474-a1dc1e80-8372-11eb-8ef2-f5059a095d0f.png)

The little green "active" in the bottom right corner tells you the xkeysnail service is successfully started and is running in the background. If you want, you can stop it right from the File menu in this little window. Or use the tray icon. Either way. You can close the GUI window. 

Now download this file into your Downloads folder: 

[kinto.py.altq_remap.txt](https://github.com/linuxmint/cinnamon/files/6134230/kinto.py.altq_remap.txt)

Back into the terminal. You should still be in the Downloads folder. Paste these commands one at a time: 

```
cp ~/.config/kinto/kinto.py ~/.config/kinto/kinto.py.original

zip ~/.config/kinto/kinto.py.original.zip ~/.config/kinto/kinto.py.original

cp ~/Downloads/kinto.py.altq_remap.txt ~/.config/kinto/

zip ~/.config/kinto/kinto.py.altq_remap.zip ~/.config/kinto/kinto.py.altq_remap.txt

rm ~/.config/kinto/kinto.py

cp ~/Downloads/kinto.py.altq_remap.txt ~/.config/kinto/kinto.py
```

Now you can use the tray icon or GUI app to restart Kinto.sh. 

What the commands do is just make a backup copy of the Kinto.sh config file (kinto.py) and a zipped copy just in case, and then the new barebones file is copied into the Kinto.sh config folder, zipped (just in case), and then the main config file is deleted and replaced with the new file. 

So you should end up with, in ~/.config/kinto: 

```
kinto.py
kinto.py.altq_remap.txt
kinto.py.altq_remap.zip
kinto.py.original
kinto.py.original.zip
```

That's everything you need in case you want to try what Kinto.sh actually does (making Linux type like a Mac). 

Anyway, if you already restarted Kinto.sh from the "K" icon, now just go into Chrome and fix the keyboard shortcut assigned to the tab switching extension. If Kinto.sh is running and working correctly with my config file, you should actually be able to edit the keyboard shortcut and press Alt+Q on your keyboard, and the shortcut that will be registered in the Chrome extension will be "Alt+W". 

If Alt+W is a problem for you, you can change the keys you're mapping Alt+Q to by opening the `kinto.py` file in any text editor and changing the line that maps "M-q" to "M-w". The "M" is short for "Meta", which is the Alt key. 

Save the file and restart from the tray icon. If there's a problem the GUI app should provide a clue. 

This is the part that maps to Alt+W: 

```
define_keymap(re.compile(chromeStr, re.IGNORECASE),{
    K("M-q"): K("M-w"),     # Map Alt+Q to Alt+W, but only within Chrome/Chromium
})
```

And that's the end of the story, folks. Nothing more to see here.

**Comment by Philipp91** [comment]
Yay, thanks a lot for figuring this out, it works!

> I never really liked those curved ergonomic keyboards for that very reason.

Yeah I guess there's generally a problem when switching between curved and regular keyboards. But the consequences are usually just typos that you can immediately see and fix. Whereas with Alt+Q it closes a window. And Q is close to Tab on _every_ keyboard.
![image](https://user-images.githubusercontent.com/2501211/111025587-5b73d780-83e5-11eb-8981-c4b1c412d7f4.png)

------

Since I have to vet all the code I install, I didn't go through the trouble of using Kinto at all. I only [installed](https://github.com/mooz/xkeysnail#installation) xkeysnail, which has very little code beyond its already-vetted `evdev` dependency. And I'm using this xkeysnail config now:

```python
import re
from xkeysnail.transform import *

# Map Alt+Q to Alt+W, but only within Chrome/Chromium
chromeStr = "|".join(str(x.casefold()) for x in ["Chromium","Chromium-browser","Google-chrome","microsoft-edge-dev","microsoft-edge"])
define_keymap(re.compile(chromeStr, re.IGNORECASE), {
    K("M-q"): K("M-w"),
})

# Everywhere else, including the Alt+Tab switcher, ignore Alt+Q entirely.
define_keymap(None, {
    K("M-q"): None,
})
```

On the one hand, I'm a bit sad that such a workaround is needed at the moment. I guess we should keep this GitHub issue open as a feature request for a configuration option.

On the other hand, I'm really glad that you came up with this solution and wrote it all down. Now I can finally let the subconscious part of my brain deal with window switching again (without fear) and keep the conscious part focused on my actual work.

**Comment by RedBearAK** [comment]
@Philipp91 

Well, I like to err on the side of over-explaining, but it looks like you're far ahead of me in understanding how to make it work. 

You must have an interesting job if you have to analyze every bit of code you put on your machine. No wonder your distro is "proprietary". 

I am very happy indeed that it actually works. Problems like this are insidiously obnoxious, like having a swarm of biting flies buzzing around your head all day, just waiting for one to take a chomp out of your neck at random times. 

Oh, and of course I was so blindly wandering around trying to find the answer that I didn't even notice you could use "None" as a key remapping. That's handy. I'll have to remember that. Although, other than this one specific thing (blocking Alt+Q) I can't think of any reason I would ever use it. LOL. 

Very concise solution you put together. Enjoy the relief from the biting flies! 

Maybe someday they'll give us a toggle.

**Comment by th-lange** [comment]
Hey @Philipp91 

thx for the reply - and sorry for getting back at it so late. My use case is: I use Linux Mint for all my computers - when working (private or work) - I keep opening a lot of apps (be it calculator, diverse browsers or browser windows, ide's) to a point, where I no longer can handle the windows. The "Alt-Tab" + "Alt-Q" was a very convenient way to get rid of the windows.

I found the issue actually, because I considered creating a bug report.... Because if just stopped working after updating Linux Mint. 

I understand the points being made. On my old work, I hated the Alt-Q shortcut on the Mac to close stuff unexpectedly. And yes- as I was switching between Mac (work) and Linux (home / studies) - it really annoyed me. But here, this only happened, when the Task Switcher was open. So one had to Press "Alt-Tab" to actually enable the "Alt-Q" Shortcut.

For me it is just convenience... And honestly - I would not care if it is the Alt-Q Key that does it. Or Alt-W|E|R|A|S - or configurable. It should just be reachable from Alt-Tab.... And far enough that no-one accidentally hits it.

But as for now, I  just added the lines back to ` js/ui/appSwitcher/appSwitcher.js`...

**Comment by Philipp91** [comment]
> The "Alt-Tab" + "Alt-Q" was a very convenient way to get rid of the windows.

Thanks, that explains the use case well. Side note: Middle-clicking windows on the task bar (if you have one and a mouse with that button) is also quite an efficient way to close many windows.

Alt+E|R|S sounds good, not Q|W|A. And/or making it configurable (boolean or allowing to set the shortcut).

**Comment by osscar** [comment]
> Hey @Philipp91
> 
> thx for the reply - and sorry for getting back at it so late. My use case is: I use Linux Mint for all my computers - when working (private or work) - I keep opening a lot of apps (be it calculator, diverse browsers or browser windows, ide's) to a point, where I no longer can handle the windows. The "Alt-Tab" + "Alt-Q" was a very convenient way to get rid of the windows.
> 
> I found this issue, actually, because I considered creating a bug report.... Because if just stopped working after updating Linux Mint.
> 
> I understand the points being made. On my old work, I hated the Alt-Q shortcut on the Mac to close stuff unexpectedly. And yes- as I was switching between Mac (work) and Linux (home / studies) - it really annoyed me. But here, this only happened, when the Task Switcher was open. So one had to Press "Alt-Tab" to actually enable the "Alt-Q" Shortcut.
> 
> For me it is just convenience... And honestly - I would not care if it is the Alt-Q Key that does it. Or Alt-W|E|R|A|S - or configurable. It should just be reachable from Alt-Tab.... And far enough that no-one accidentally hits it.
> 
> But as for now, I just added the lines back to ` js/ui/appSwitcher/appSwitcher.js`...

I am on Linux Mint 20.2 and I am coming from a mac so this was kind of intuitive and actually quite handy for the same reason @Phillip91 mentioned. Its just handy to be able to get rid of apps you no longer need with a key stroke IMHO. Wish it was an option if it is not convenient for most.

**Comment by rookie-ger** [comment]
I also liked this way of closing programs a lot and I am missing it badly. Please reintroduce it and make it optional.

**Comment by th-lange** [comment]
Hello @Philipp91 

I have a general question concerning the option or making it optional. A few words ahead:

Adding or modifying the files in `appSwitcher.js` is not an issue for me. I could even prepare a MR if this would be appreciated...

But generally I wonder, if adding the setting here would be a good / bad thing:

![Selection_031](https://user-images.githubusercontent.com/4717890/142461232-85e8a312-a510-4613-af28-70c53d686fde.png)

This is just an idea - and I probably don't see all the implications...
One I saw is: KeyUp on Alt will chancel the Activation of Task Switcher... Which could be confusing... So I am not sure, this is a good thing. A point to the rescue is, that many will have a context (like: Close Window only works with active window...)

**Comment by Philipp91** [comment]
I'm not qualified to answer this. For one, I don't know if it's technically feasible / reasonably easy to implement it in that settings dialog and "act" on it in `appSwitcher.js`. And secondly, I don't know the general UX design considerations that the Cinnamon team applies here (as I'm not on the Cinnamon team, I'm just a user).

@mtwebster What do you think?
