### ISSUE TITLE
Can't take screenshot with the Start menu is open

### ISSUE THREAD

**Issue by dandv** [linuxmint/cinnamon#9789]
```
 * Cinnamon version 4.6.7
 * Distribution - Mint 20 Ulyana
 * Graphics hardware *and* driver used
 * 64 bit
 ```
[xsession-errors.zip](https://github.com/linuxmint/cinnamon/files/5733179/xsession-errors.zip)

**Issue**
When attempting to take a screenshot of an area and the Start menu is open, `gnome-screenshot` locks up the system with this error message: `Unable to capture screenshot`, `All possible methods failed`. Clicking the `x` to close the window doesn't work.

![image](https://user-images.githubusercontent.com/33569/102957694-26f41d80-447f-11eb-9ddc-61645442d783.png)

**Steps to reproduce**
1. Open the start menu (e.g. press the Super key)
2. Press Shift+PrintScreen to try taking a screenshot of an area

**Comment by icarter09** [comment]
Screenshots are no longer available with a popup Cinnamon menu. This is expected functionality to prevent the issue described.

**Comment by dandv** [comment]
Sorry, I don't understand what went on here. So there's another buggy behavior when taking screenshots with a popup menu open, and the solution was for gnome-screenshot to give that confusing error instead of something like "Please close any popups before taking a screenshot"?

What is the root issue? Either way, the "solution" masks it with another weird behavior. From an end user's perspective, it should absolutely be possible to take a screenshot whether some popup is open or not, and there are legitimate use cases for this.
