### ISSUE TITLE
White screen before loggin after put username and password

### ISSUE THREAD

**Issue by Mario156090** [linuxmint/cinnamon#9794]
```
 * Cinnamon version (Cinnamon 4.8.4)
   - I don't use daily updates
 * Distribution - (Linux Mint 20.1 ulyssa Beta - Cinnamon edition)
 * Nvidia driver and Intel driver
 * 32 or 64 bit
 * file attached
 ```

When do you put your credentials for login,you received a faster white screen or grey screen, next the desktop shows correctly.

Steps:

Step 1, turn on your computer.
Step 2, put your username and password
Step 3, enter for login.
Step 4, glitch is here.

**Expected behaviour**

[xsession-errors.zip](https://github.com/linuxmint/cinnamon/files/5742484/xsession-errors.zip)

https://user-images.githubusercontent.com/47507975/103143112-7d12cc00-46de-11eb-9f53-a0b4d24e7f9e.mp4

```

**Comment by icarter09** [comment]
@Mario156090 can you provide your `System Info`? Thanks.

**Comment by Mario156090** [comment]
> @Mario156090 can you provide your `System Info`? Thanks.

`System:    Kernel: 5.4.0-58-generic x86_64 bits: 64 compiler: gcc v: 9.3.0 Desktop: Cinnamon 4.8.4 
           wm: muffin dm: LightDM Distro: Linux Mint 20.1 Ulyssa base: Ubuntu 20.04 focal 
Machine:   Type: Laptop System: Dell product: Inspiron 15 7000 Gaming v: N/A serial: <filter> 
           Chassis: type: 10 serial: <filter> 
           Mobo: Dell model: N/A serial: <filter> UEFI: Dell v: 1.12.1 date: 06/19/2020 
Battery:   ID-1: BAT0 charge: 17.2 Wh condition: 45.6/74.0 Wh (62%) volts: 11.3/11.4 
           model: SMP DELL 71JF453 serial: <filter> status: Discharging 
CPU:       Topology: Quad Core model: Intel Core i5-7300HQ bits: 64 type: MCP arch: Kaby Lake 
           rev: 9 L2 cache: 6144 KiB 
           flags: avx avx2 lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx bogomips: 19999 
           Speed: 1025 MHz min/max: 800/3500 MHz Core speeds (MHz): 1: 1025 2: 1165 3: 1152 
           4: 1038 
Graphics:  Device-1: Intel HD Graphics 630 vendor: Dell driver: i915 v: kernel bus ID: 00:02.0 
           chip ID: 8086:591b 
           Display: x11 server: X.Org 1.20.8 driver: modesetting unloaded: fbdev,vesa 
           resolution: 1920x1080~60Hz 
           OpenGL: renderer: Mesa Intel HD Graphics 630 (KBL GT2) v: 4.6 Mesa 20.0.8 
           direct render: Yes 
Audio:     Device-1: Intel CM238 HD Audio vendor: Dell driver: snd_hda_intel v: kernel 
           bus ID: 00:1f.3 chip ID: 8086:a171 
           Sound Server: ALSA v: k5.4.0-58-generic 
Network:   Device-1: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet vendor: Dell 
           driver: r8169 v: kernel port: d000 bus ID: 02:00.0 chip ID: 10ec:8168 
           IF: enp2s0 state: down mac: <filter> 
           Device-2: Intel Wireless 3165 driver: iwlwifi v: kernel port: d000 bus ID: 03:00.0 
           chip ID: 8086:3165 
           IF: wlp3s0 state: up mac: <filter> 
           IF-ID-1: docker0 state: down mac: <filter> 
           IF-ID-2: Pr0 state: down mac: <filter> 
           IF-ID-3: virbr0 state: down mac: <filter> 
           IF-ID-4: virbr0-nic state: down mac: <filter> 
           IF-ID-5: vmnet1 state: unknown speed: N/A duplex: N/A mac: <filter> 
           IF-ID-6: vmnet8 state: unknown speed: N/A duplex: N/A mac: <filter> 
Drives:    Local Storage: total: 1.14 TiB used: 560.58 GiB (47.9%) 
           ID-1: /dev/sda vendor: SanDisk model: X400 M.2 2280 256GB size: 238.47 GiB 
           speed: 6.0 Gb/s serial: <filter> 
           ID-2: /dev/sdb vendor: HGST (Hitachi) model: HTS541010A9E680 size: 931.51 GiB 
           speed: 6.0 Gb/s serial: <filter> 
Partition: ID-1: / size: 233.24 GiB used: 25.30 GiB (10.8%) fs: ext4 dev: /dev/sda2 
Sensors:   System Temperatures: cpu: 34.0 C mobo: 25.0 C sodimm: 28.0 C 
           Fan Speeds (RPM): cpu: 0 
Repos:     No active apt repos in: /etc/apt/sources.list 
           Active apt repos in: /etc/apt/sources.list.d/additional-repositories.list 
           1: deb [arch=amd64] https: //download.docker.com/linux/ubuntu focal stable
           Active apt repos in: /etc/apt/sources.list.d/gns3-ppa-focal.list 
           1: deb http: //ppa.launchpad.net/gns3/ppa/ubuntu focal main
           Active apt repos in: /etc/apt/sources.list.d/google-chrome.list 
           1: deb [arch=amd64] http: //dl.google.com/linux/chrome/deb/ stable main
           Active apt repos in: /etc/apt/sources.list.d/numix-ppa-focal.list 
           1: deb http: //ppa.launchpad.net/numix/ppa/ubuntu focal main
           Active apt repos in: /etc/apt/sources.list.d/official-package-repositories.list 
           1: deb http: //packages.linuxmint.com ulyssa main upstream import backport #id:linuxmint_main
           2: deb http: //archive.ubuntu.com/ubuntu focal main restricted universe multiverse
           3: deb http: //archive.ubuntu.com/ubuntu focal-updates main restricted universe multiverse
           4: deb http: //archive.ubuntu.com/ubuntu focal-backports main restricted universe multiverse
           5: deb http: //security.ubuntu.com/ubuntu/ focal-security main restricted universe multiverse
           6: deb http: //archive.canonical.com/ubuntu/ focal partner
           Active apt repos in: /etc/apt/sources.list.d/papirus-papirus-focal.list 
           1: deb http: //ppa.launchpad.net/papirus/papirus/ubuntu focal main
           Active apt repos in: /etc/apt/sources.list.d/teams.list 
           1: deb [arch=amd64] https: //packages.microsoft.com/repos/ms-teams stable main
Info:      Processes: 243 Uptime: 2m Memory: 23.36 GiB used: 1.56 GiB (6.7%) Init: systemd v: 245 
           runlevel: 5 Compilers: gcc: 9.3.0 alt: 9 Client: Unknown python3.8 client inxi: 3.0.38 `
![image](https://user-images.githubusercontent.com/47507975/103169585-0d4e2f80-480b-11eb-8a3c-6b72d7988ea3.png)

Here my system information, just appears my integrated graphicscard in the pic but also there a nvidia 1050m.

**Comment by icarter09** [comment]
@Mario156090 thanks! Your system info is very close to mine, but without the nvidia card.

**Comment by Mario156090** [comment]
> @Mario156090 thanks! Your system info is very close to mine, but without the nvidia card. Can you switch over to non-nvidia graphics card to test if the issue still persists? Thanks.

Yes, the issue persist with Nvidia and hybrid mode.

**Comment by nsleasy** [comment]
This appears to be a problem with Cinnamon/Muffin 4.8.x on the Lenovo Thinkpad platform. I'm copying the 3 configurations that I have, below, one of which exhibits this problem.

1. Lenovo Thinkpad - Cinnamon 4.6.7 - No White Screen Problem
2. HP ProBook - Cinnamon 4.8.3 - No White Screen Problem
3. Lenovo Thinkpad - Cinnamon 4.8.3 - ** Has White Screen Problem **

Reference corresponding Fedora 33 Bug Report on this issue: 

https://bugzilla.redhat.com/show_bug.cgi?id=1913095


===========================================================

1.

Lenovo T450 Config - Cinnamon 4.6.7 - No White Screen Problem



System:    Kernel: 5.9.13-200.fc33.x86_64 x86_64 bits: 64 compiler: gcc v: 2.35-15.fc33)
           Desktop: Cinnamon 4.6.7 tk: GTK 3.24.23 wm: muffin dm: LightDM
           Distro: Fedora release 33 (Thirty Three)
Machine:   Type: Laptop System: LENOVO product: 20BUS25A00 v: ThinkPad T450 serial: <filter>
           Chassis: type: 10 serial: <filter>
           Mobo: LENOVO model: 20BUS25A00 v: SDK0E50510 WIN serial: <filter> UEFI [Legacy]: LENOVO
           v: JBET73WW (1.37 ) date: 08/14/2019
Battery:   ID-1: BAT0 charge: 16.4 Wh condition: 16.4/23.2 Wh (71%) volts: 12.3/11.1
           model: SANYO 45N1773 serial: <filter> status: Full
           ID-2: BAT1 charge: 10.4 Wh condition: 15.0/23.2 Wh (65%) volts: 11.6/11.1
           model: SANYO 45N1775 serial: <filter> status: Discharging
CPU:       Info: Dual Core model: Intel Core i5-5300U bits: 64 type: MT MCP arch: Broadwell rev: 4
           L2 cache: 3072 KiB
           flags: avx avx2 lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 bogomips: 18357
           Speed: 857 MHz min/max: 500/2900 MHz Core speeds (MHz): 1: 798 2: 798 3: 798 4: 798
Graphics:  Device-1: Intel HD Graphics 5500 vendor: Lenovo driver: i915 v: kernel bus ID: 00:02.0
           chip ID: 8086:1616
           Device-2: Acer Integrated Camera type: USB driver: uvcvideo bus ID: 2-8:5
           chip ID: 5986:0366
           Display: x11 server: Fedora Project X.org 1.20.10 driver: modesetting
           unloaded: fbdev,vesa resolution: 1600x900~60Hz s-dpi: 96
           OpenGL: renderer: Mesa Intel HD Graphics 5500 (BDW GT2) v: 4.6 Mesa 20.2.4
           direct render: Yes
Audio:     Device-1: Intel Broadwell-U Audio vendor: Lenovo driver: snd_hda_intel v: kernel
           bus ID: 00:03.0 chip ID: 8086:160c
           Device-2: Intel Wildcat Point-LP High Definition Audio vendor: Lenovo
           driver: snd_hda_intel v: kernel bus ID: 00:1b.0 chip ID: 8086:9ca0
           Sound Server: ALSA v: k5.9.13-200.fc33.x86_64
Network:   Device-1: Intel Ethernet I218-LM vendor: Lenovo driver: e1000e v: kernel port: 3080
           bus ID: 00:19.0 chip ID: 8086:15a2
           IF: enp0s25 state: down mac: <filter>
           Device-2: Intel Wireless 7265 driver: iwlwifi v: kernel port: efa0 bus ID: 03:00.0
           chip ID: 8086:095b
           IF: wlp3s0 state: up mac: <filter>
Drives:    Local Storage: total: 238.47 GiB used: 8.62 GiB (3.6%)
           ID-1: /dev/sda vendor: Samsung model: MZ7LN256HCHP-000L7 size: 238.47 GiB
           speed: 6.0 Gb/s serial: <filter>
Partition: ID-1: / size: 19.56 GiB used: 8.62 GiB (44.1%) fs: ext4 dev: /dev/sda3
Swap:      ID-1: swap-1 type: zram size: 3.74 GiB used: 0 KiB (0.0%) priority: 100 dev: /dev/zram0
Sensors:   System Temperatures: cpu: 40.5 C mobo: 0.0 C
           Fan Speeds (RPM): cpu: 0
Repos:     Packages: rpm: 1842
           Active yum repos in: /etc/yum.repos.d/fedora-cisco-openh264.repo
           1: fedora-cisco-openh264 ~ https: //mirrors.fedoraproject.org/metalink?repo=fedora-cisco-openh264-$releasever&arch=$basearch
           Active yum repos in: /etc/yum.repos.d/fedora-modular.repo
           1: fedora-modular ~ https: //mirrors.fedoraproject.org/metalink?repo=fedora-modular-$releasever&arch=$basearch
           Active yum repos in: /etc/yum.repos.d/fedora-multimedia.repo
           1: fedora-multimedia ~ https: //negativo17.org/repos/multimedia/fedora-$releasever/$basearch/
           Active yum repos in: /etc/yum.repos.d/fedora-updates-modular.repo
           1: updates-modular ~ https: //mirrors.fedoraproject.org/metalink?repo=updates-released-modular-f$releasever&arch=$basearch
           No active yum repos in: /etc/yum.repos.d/fedora-updates-testing-modular.repo
           No active yum repos in: /etc/yum.repos.d/fedora-updates-testing.repo
           Active yum repos in: /etc/yum.repos.d/fedora-updates.repo
           1: updates ~ https: //mirrors.fedoraproject.org/metalink?repo=updates-released-f$releasever&arch=$basearch
           Active yum repos in: /etc/yum.repos.d/fedora.repo
           1: fedora ~ https: //mirrors.fedoraproject.org/metalink?repo=fedora-$releasever&arch=$basearch
           Active yum repos in: /etc/yum.repos.d/google-chrome.repo
           1: google-chrome ~ http: //dl.google.com/linux/chrome/rpm/stable/x86_64
           No active yum repos in: /etc/yum.repos.d/rpmfusion-free-updates-testing.repo
           Active yum repos in: /etc/yum.repos.d/rpmfusion-free-updates.repo
           1: rpmfusion-free-updates ~ https: //mirrors.rpmfusion.org/metalink?repo=free-fedora-updates-released-$releasever&arch=$basearch
           Active yum repos in: /etc/yum.repos.d/rpmfusion-free.repo
           1: rpmfusion-free ~ https: //mirrors.rpmfusion.org/metalink?repo=free-fedora-$releasever&arch=$basearch
           No active yum repos in: /etc/yum.repos.d/tlp-updates-testing.repo
           Active yum repos in: /etc/yum.repos.d/tlp-updates.repo
           1: tlp-updates ~ https: //repo.linrunner.de/fedora/tlp/mirrors/$releasever/$basearch/tlp-updates.txt
           Active yum repos in: /etc/yum.repos.d/tlp.repo
           1: tlp ~ https: //repo.linrunner.de/fedora/tlp/mirrors/$releasever/$basearch/tlp.txt
Info:      Processes: 216 Uptime: 1m Memory: 7.47 GiB used: 686.2 MiB (9.0%) Init: systemd v: 246
           runlevel: 5 target: graphical.target Compilers: gcc: 10.2.1
           Client: Unknown python3.9 client inxi: 3.1.08



2.

HP ProBook Config - Cinnamon 4.8.3 - No White Screen Problem



System:    Kernel: 5.9.16-200.fc33.x86_64 x86_64 bits: 64 compiler: gcc v: 2.35-15.fc33)
           Desktop: Cinnamon 4.8.3 tk: GTK 3.24.24 wm: muffin dm: LightDM
           Distro: Fedora release 33 (Thirty Three)
Machine:   Type: Laptop System: Hewlett-Packard product: HP ProBook 4430s v: A0001D02
           serial: <filter> Chassis: type: 10 serial: <filter>
           Mobo: Hewlett-Packard model: 167E v: KBC Version 22.26 serial: <filter>
           BIOS: Hewlett-Packard v: 68SRR Ver. F.60 date: 03/13/2015
Battery:   ID-1: BAT0 charge: 40.8 Wh condition: 42.4/42.4 Wh (100%) volts: 12.3/10.8
           model: Hewlett-Packard Primary serial: <filter> status: Unknown
CPU:       Info: Dual Core model: Intel Core i3-2310M bits: 64 type: MT MCP arch: Sandy Bridge
           rev: 7 L2 cache: 3072 KiB
           flags: avx lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx bogomips: 16761
           Speed: 1343 MHz min/max: 800/2100 MHz Core speeds (MHz): 1: 1677 2: 1668 3: 1755
           4: 1732
Graphics:  Device-1: Intel 2nd Generation Core Processor Family Integrated Graphics
           vendor: Hewlett-Packard driver: i915 v: kernel bus ID: 00:02.0 chip ID: 8086:0116
           Device-2: Primax type: USB driver: uvcvideo bus ID: 2-1.4:3 chip ID: 0461:4dc7
           Display: x11 server: Fedora Project X.org 1.20.10 driver: modesetting
           unloaded: fbdev,vesa resolution: 1366x768~60Hz s-dpi: 96
           OpenGL: renderer: Mesa DRI Intel HD Graphics 3000 (SNB GT2) v: 3.3 Mesa 20.2.6
           compat-v: 3.0 direct render: Yes
Audio:     Device-1: Intel 6 Series/C200 Series Family High Definition Audio
           vendor: Hewlett-Packard driver: snd_hda_intel v: kernel bus ID: 00:1b.0
           chip ID: 8086:1c20
           Sound Server: ALSA v: k5.9.16-200.fc33.x86_64
Network:   Device-1: Qualcomm Atheros AR9285 Wireless Network Adapter vendor: Hewlett-Packard
           driver: ath9k v: kernel port: 5040 bus ID: 24:00.0 chip ID: 168c:002b
           IF: wlo1 state: up mac: <filter>
           Device-2: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet
           vendor: Hewlett-Packard driver: r8169 v: kernel port: 2000 bus ID: 25:00.0
           chip ID: 10ec:8168
           IF: enp37s0 state: down mac: <filter>
           Device-3: Qualcomm Atheros AR3011 Bluetooth type: USB driver: btusb bus ID: 2-1.6:5
           chip ID: 0cf3:3005
Drives:    Local Storage: total: 298.09 GiB used: 8.39 GiB (2.8%)
           ID-1: /dev/sda vendor: Seagate model: ST320LT007-9ZV142 size: 298.09 GiB
           speed: 3.0 Gb/s serial: <filter>
Partition: ID-1: / size: 19.56 GiB used: 8.39 GiB (42.9%) fs: ext4 dev: /dev/sda3
Swap:      ID-1: swap-1 type: zram size: 1.88 GiB used: 0 KiB (0.0%) priority: 100 dev: /dev/zram0
Sensors:   System Temperatures: cpu: 50.0 C mobo: 0.0 C
           Fan Speeds (RPM): N/A
Repos:     Packages: rpm: 1790
           Active yum repos in: /etc/yum.repos.d/fedora-cisco-openh264.repo
           1: fedora-cisco-openh264 ~ https: //mirrors.fedoraproject.org/metalink?repo=fedora-cisco-openh264-$releasever&arch=$basearch
           Active yum repos in: /etc/yum.repos.d/fedora-modular.repo
           1: fedora-modular ~ https: //mirrors.fedoraproject.org/metalink?repo=fedora-modular-$releasever&arch=$basearch
           Active yum repos in: /etc/yum.repos.d/fedora-multimedia.repo
           1: fedora-multimedia ~ https: //negativo17.org/repos/multimedia/fedora-$releasever/$basearch/
           Active yum repos in: /etc/yum.repos.d/fedora-updates-modular.repo
           1: updates-modular ~ https: //mirrors.fedoraproject.org/metalink?repo=updates-released-modular-f$releasever&arch=$basearch
           No active yum repos in: /etc/yum.repos.d/fedora-updates-testing-modular.repo
           No active yum repos in: /etc/yum.repos.d/fedora-updates-testing.repo
           Active yum repos in: /etc/yum.repos.d/fedora-updates.repo
           1: updates ~ https: //mirrors.fedoraproject.org/metalink?repo=updates-released-f$releasever&arch=$basearch
           Active yum repos in: /etc/yum.repos.d/fedora.repo
           1: fedora ~ https: //mirrors.fedoraproject.org/metalink?repo=fedora-$releasever&arch=$basearch
           Active yum repos in: /etc/yum.repos.d/google-chrome.repo
           1: google-chrome ~ http: //dl.google.com/linux/chrome/rpm/stable/x86_64
           No active yum repos in: /etc/yum.repos.d/rpmfusion-free-updates-testing.repo
           Active yum repos in: /etc/yum.repos.d/rpmfusion-free-updates.repo
           1: rpmfusion-free-updates ~ https: //mirrors.rpmfusion.org/metalink?repo=free-fedora-updates-released-$releasever&arch=$basearch
           Active yum repos in: /etc/yum.repos.d/rpmfusion-free.repo
           1: rpmfusion-free ~ https: //mirrors.rpmfusion.org/metalink?repo=free-fedora-$releasever&arch=$basearch
Info:      Processes: 212 Uptime: 5m Memory: 3.77 GiB used: 1.05 GiB (27.8%) Init: systemd v: 246
           runlevel: 5 target: graphical.target Compilers: gcc: N/A
           Client: Unknown python3.9 client inxi: 3.1.08


3.

Lenovo T450 Config - Cinnamon 4.8.3 - ** Has White Screen Problem **


System:    Kernel: 5.9.16-200.fc33.x86_64 x86_64 bits: 64 compiler: gcc v: 2.35-15.fc33)
           Desktop: Cinnamon 4.8.3 tk: GTK 3.24.24 wm: muffin dm: LightDM
           Distro: Fedora release 33 (Thirty Three)
Machine:   Type: Laptop System: LENOVO product: 20BUS25A00 v: ThinkPad T450 serial: <filter>
           Chassis: type: 10 serial: <filter>
           Mobo: LENOVO model: 20BUS25A00 v: SDK0E50510 WIN serial: <filter> UEFI [Legacy]: LENOVO
           v: JBET73WW (1.37 ) date: 08/14/2019
Battery:   ID-1: BAT0 charge: 16.4 Wh condition: 16.4/23.2 Wh (71%) volts: 12.3/11.1
           model: SANYO 45N1773 serial: <filter> status: Full
           ID-2: BAT1 charge: 12.2 Wh condition: 15.0/23.2 Wh (65%) volts: 12.0/11.1
           model: SANYO 45N1775 serial: <filter> status: Discharging
CPU:       Info: Dual Core model: Intel Core i5-5300U bits: 64 type: MT MCP arch: Broadwell rev: 4
           L2 cache: 3072 KiB
           flags: avx avx2 lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 bogomips: 18357
           Speed: 799 MHz min/max: 500/2900 MHz Core speeds (MHz): 1: 798 2: 798 3: 798 4: 798
Graphics:  Device-1: Intel HD Graphics 5500 vendor: Lenovo driver: i915 v: kernel bus ID: 00:02.0
           chip ID: 8086:1616
           Device-2: Acer Integrated Camera type: USB driver: uvcvideo bus ID: 2-8:4
           chip ID: 5986:0366
           Display: x11 server: Fedora Project X.org 1.20.10 driver: modesetting
           unloaded: fbdev,vesa resolution: 1600x900~60Hz s-dpi: 96
           OpenGL: renderer: Mesa Intel HD Graphics 5500 (BDW GT2) v: 4.6 Mesa 20.2.6
           direct render: Yes
Audio:     Device-1: Intel Broadwell-U Audio vendor: Lenovo driver: snd_hda_intel v: kernel
           bus ID: 00:03.0 chip ID: 8086:160c
           Device-2: Intel Wildcat Point-LP High Definition Audio vendor: Lenovo
           driver: snd_hda_intel v: kernel bus ID: 00:1b.0 chip ID: 8086:9ca0
           Sound Server: ALSA v: k5.9.16-200.fc33.x86_64
Network:   Device-1: Intel Ethernet I218-LM vendor: Lenovo driver: e1000e v: kernel port: 3080
           bus ID: 00:19.0 chip ID: 8086:15a2
           IF: enp0s25 state: down mac: <filter>
           Device-2: Intel Wireless 7265 driver: iwlwifi v: kernel port: efa0 bus ID: 03:00.0
           chip ID: 8086:095b
           IF: wlp3s0 state: up mac: <filter>
Drives:    Local Storage: total: 238.47 GiB used: 161.97 GiB (67.9%)
           ID-1: /dev/sda vendor: Samsung model: MZ7LN256HCHP-000L7 size: 238.47 GiB
           speed: 6.0 Gb/s serial: <filter>
Partition: ID-1: / size: 19.56 GiB used: 8.88 GiB (45.4%) fs: ext4 dev: /dev/sda3
Swap:      ID-1: swap-1 type: zram size: 3.74 GiB used: 0 KiB (0.0%) priority: 100 dev: /dev/zram0
Sensors:   System Temperatures: cpu: 30.0 C mobo: 0.0 C
           Fan Speeds (RPM): cpu: 0
Repos:     Packages: rpm: 1847
           Active yum repos in: /etc/yum.repos.d/fedora-cisco-openh264.repo
           1: fedora-cisco-openh264 ~ https: //mirrors.fedoraproject.org/metalink?repo=fedora-cisco-openh264-$releasever&arch=$basearch
           Active yum repos in: /etc/yum.repos.d/fedora-modular.repo
           1: fedora-modular ~ https: //mirrors.fedoraproject.org/metalink?repo=fedora-modular-$releasever&arch=$basearch
           Active yum repos in: /etc/yum.repos.d/fedora-multimedia.repo
           1: fedora-multimedia ~ https: //negativo17.org/repos/multimedia/fedora-$releasever/$basearch/
           Active yum repos in: /etc/yum.repos.d/fedora-updates-modular.repo
           1: updates-modular ~ https: //mirrors.fedoraproject.org/metalink?repo=updates-released-modular-f$releasever&arch=$basearch
           No active yum repos in: /etc/yum.repos.d/fedora-updates-testing-modular.repo
           No active yum repos in: /etc/yum.repos.d/fedora-updates-testing.repo
           Active yum repos in: /etc/yum.repos.d/fedora-updates.repo
           1: updates ~ https: //mirrors.fedoraproject.org/metalink?repo=updates-released-f$releasever&arch=$basearch
           Active yum repos in: /etc/yum.repos.d/fedora.repo
           1: fedora ~ https: //mirrors.fedoraproject.org/metalink?repo=fedora-$releasever&arch=$basearch
           Active yum repos in: /etc/yum.repos.d/google-chrome.repo
           1: google-chrome ~ http: //dl.google.com/linux/chrome/rpm/stable/x86_64
           No active yum repos in: /etc/yum.repos.d/rpmfusion-free-updates-testing.repo
           Active yum repos in: /etc/yum.repos.d/rpmfusion-free-updates.repo
           1: rpmfusion-free-updates ~ https: //mirrors.rpmfusion.org/metalink?repo=free-fedora-updates-released-$releasever&arch=$basearch
           Active yum repos in: /etc/yum.repos.d/rpmfusion-free.repo
           1: rpmfusion-free ~ https: //mirrors.rpmfusion.org/metalink?repo=free-fedora-$releasever&arch=$basearch
           No active yum repos in: /etc/yum.repos.d/tlp-updates-testing.repo
           Active yum repos in: /etc/yum.repos.d/tlp-updates.repo
           1: tlp-updates ~ https: //repo.linrunner.de/fedora/tlp/mirrors/$releasever/$basearch/tlp-updates.txt
           Active yum repos in: /etc/yum.repos.d/tlp.repo
           1: tlp ~ https: //repo.linrunner.de/fedora/tlp/mirrors/$releasever/$basearch/tlp.txt
Info:      Processes: 271 Uptime: 50m Memory: 7.47 GiB used: 761.2 MiB (9.9%) Init: systemd v: 246
           runlevel: 5 target: graphical.target Compilers: gcc: 10.2.1
           Client: Unknown python3.9 client inxi: 3.1.08

**Comment by nsleasy** [comment]
After further testing, this problem in the Cinnamon 4.8.x environment appears to be related to the user Startup Application 'xapp-sn-watcher', which calls 'org.kde.StatusNotifierWatcher':

[Desktop Entry]
Type=Application
Name=xapp-sn-watcher
Comment=A service that provides the org.kde.StatusNotifierWatcher interface for XApps

Exec=@launch_folder@/xapp-sn-watcher

X-GNOME-Autostart-Phase=Panel


** WORKAROUND **

Disabling or removing this from the Cinnamon 'Startup Applications' configuration eliminates the problem:

System Settings -> Startup Application -> xapp-sn-watcher -> <disable>


It is not clear what the 'org.kde.StatusNotifierWatcher' process does, especially in the Cinnamon/GTK environment, but disabling it resolves the white screen problem and causes no ill effects.

**Comment by Mario156090** [comment]
> After further testing, this problem in the Cinnamon 4.8.x environment appears to be related to the user Startup Application 'xapp-sn-watcher', which calls 'org.kde.StatusNotifierWatcher':
> 
> [Desktop Entry]
> Type=Application
> Name=xapp-sn-watcher
> Comment=A service that provides the org.kde.StatusNotifierWatcher interface for XApps
> 
> Exec=@launch_folder@/xapp-sn-watcher
> 
> X-GNOME-Autostart-Phase=Panel
> 
> 
> ** WORKAROUND **
> 
> Disabling or removing this from the Cinnamon 'Startup Applications' configuration eliminates the problem:
> 
> System Settings -> Startup Application -> xapp-sn-watcher -> <disable>
> 
> 
> It is not clear what the 'org.kde.StatusNotifierWatcher' process does, especially in the Cinnamon/GTK environment, but disabling it resolves the white screen problem and causes no ill effects.
> 

Ok, with this workaround works perfectly. Thank's a lot.

**Comment by clefebvre** [comment]
Fixed by https://github.com/linuxmint/muffin/commit/ac6c3c8ca9f3b22d22e890dcf71f0f8ccec5bb0d
