### ISSUE TITLE
unable to use as hotspot

### ISSUE THREAD

**Issue by D-EVE-R** [linuxmint/cinnamon#9799]
this issue's on 20 with Cinnamon 4.6.7 and not 19.3 but unfortunately, it's present on 20.1 with Cinnamon 4.8 too, which I cant use as a hotspot from network settings (graphic method) the only option to solve it is by using a command line on the terminal.
20.1 Cinnamon 4.8
![Screenshot from 2020-12-20 22-00-00](https://user-images.githubusercontent.com/66891134/103174949-a2cadd00-4866-11eb-9e9c-822837a73754.png)
20 Cinnamon 4.6.7
![Screenshot from 2020-12-20 23-22-49](https://user-images.githubusercontent.com/66891134/103174958-bc6c2480-4866-11eb-865f-99959098017b.png)

**Comment by icarter09** [comment]
@D-EVE-R you must be root in order to enable a device as a Hotspot through the GUI. I was able to verify this by logging in as root and running cinnamon-settings via the terminal, then Network. "Use as Hotspot" should be enabled.
