### ISSUE TITLE
Can't assign Alt+Print Screen to copy screenshot of current window to clipboard

### ISSUE THREAD

**Issue by dandv** [linuxmint/cinnamon#9814]
```
 * Cinnamon version 4.6.7
 * Distribution - Mint 20 Ulyana
 * Graphics hardware *and* driver used
 * 64 bit
 ```

**Issue**
When trying to assign the Alt+Print Screen keyboard binding, I get "Alt L" instead, and indeed the left Alt key triggers the action.

**Steps to reproduce**
1. Go to System -> Keyboard -> Shortcuts -> Screenshots and Recording
2. Try to assign the Alt + PrintScreen keyboard binding to some action
3. Notice `Alt L`.

![image](https://user-images.githubusercontent.com/33569/103433766-294f2980-4b9b-11eb-916a-480b6c8f7b0f.png)

Might be related to #5718.

**Comment by icarter09** [comment]
Is this ticket a duplicate of #7124?

**Comment by dandv** [comment]
@icarter09: indeed it is!
