### ISSUE TITLE
Grouped Window List does not clear app instances from other workspaces when they are closed

### ISSUE THREAD

**Issue by mattvalley** [linuxmint/cinnamon#9822]
**Setup**

- Linux Mint 20 Cinnamon Edition 64bit
- Cinnamon 4.6.7

**Issue**

When the "Show windows from all workspaces" setting is enabled, the Grouped Window List does not clear app instances from other workspaces when they are closed.  This issue is similar to #8779 but happens with a different scenario.

**Steps to reproduce**

1. Start with the default settings for the Grouped Window List.  At this point the "Show windows from all workspaces" setting should be disabled.
2. Launch a few instances of a given app.
3. Move one of the app instances to a different workspace.
4. Change the "Show windows from all workspaces" setting to enabled.
5. Use the red X close button in the hover area for the given app's icon in the panel to close the app instance that was moved to the other workspace.
6. Notice that the entry for that app instance was not removed.

The attached video demonstrates the bug.

https://user-images.githubusercontent.com/4983376/103473728-05d1dd80-4d59-11eb-8e5b-993388c77b60.mp4

**Expected behavior**

When the "Show windows from all workspaces" setting is enabled and when I close the instance of the app from any workspace (independent of the current workspace) the Grouped Window List should correctly remove the entry for that app instance.

**Other information**

- I did not see any errors in `~/.xsession-errors`
- This issue also does not seem to be specific to any app.
- It did not matter if I used the red X close button or the middle click with the mouse to close the app instance from the other workspace.
- Even though the attached video is from when I tested in a VM, I can also reproduce the issue on my host machine.

**Comment by gadass** [comment]
@mattvalley, it seems a bug that occurs only using the context menu option. If you use the arrow or numeric keys while dragging the app instance to move to another workspace this bug not happens. Please, repeat the steps you described, but use this different approach to move the app instances.

**Comment by gadass** [comment]
Note that if you go to a specific workspace, this workspace can now be chosen to move any app instance with the context menu option without any problem. However, this bug occurs if you move the window to any workspace that wasn't previously mapped. Please see the video below.

https://user-images.githubusercontent.com/38897885/103477449-c8437380-4d9d-11eb-8c27-d79ddc06c3f9.mp4

**Comment by gadass** [comment]
@mattvalley, I made a commit. Please check if your issue solved.

**Comment by mattvalley** [comment]
@gadass I tested the change in your commit and it fixes the issue from this ticket.  I also verified the other scenarios you mentioned above where the bug is limited to when you move the window to a workspace that you haven't switched to yet.

**Comment by gadass** [comment]
Thanks to report this bug @mattvalley. 

I hope this ticket helps the developers @icarter09 figure out a better fix.
