### ISSUE TITLE
[Bug] Battery notification icon is inaccurate

### ISSUE THREAD

**Issue by mystic-githuber** [linuxmint/cinnamon#9823]
Cinnamon version 4.8.5-1
  EndeavourOS Linux x86_64 (Arch)
  Kernel: 5.10.3-arch1-1
  Intel i5-10210U (8) @ 4.200GHz * 64 bit 
   Intel UHD Graphics
 
**Issue**
Battery notification icon displays inaccurate reading. As you see from the image below the icon is showing that there is 3/4 battery left when there is only 30% left. 

Using only the icon without the percentage indicator is problematic. 

![Battery Notifications](https://user-images.githubusercontent.com/66426048/103476810-ba4b1e00-4db0-11eb-8e53-424ba71769d0.png)

**Comment by ItzSwirlz** [comment]
Here's what it really comes down to-we need a system-icon for certain points of the battery percentage.

The Adwaita Icon set has in /usr/share/icons/Adwaita/scalable/status-and that's PERFECT as it has battery level 0, 10, 20, 30, 40 , 50, all of them through 10's :D (and it's not in the legacy folder which has battery stuff so this is probably kept)

I'll see if I can put on my maintainer hat and open a PR

**Comment by ItzSwirlz** [comment]
So far, after leaving my PC unplugged for about an hour on Mint 20.1 Beta, it seems somewhat accurate but not exactly perfect. We will see what happens soon, but I'll begin working on a PR I guess.

![Screenshot from 2021-01-03 17-50-49](https://user-images.githubusercontent.com/24401303/103490802-4b8bb600-4dec-11eb-8c3d-2d3ef4079ad5.png)

**Comment by ItzSwirlz** [comment]
Aha! I found the problem.

@mtwebster 

At line 503 if statement:

```
  } else if (percentage > 5) {
                this._applet_icon.set_style_class_name('system-status-icon warning');
```

This applies to **any** icon-the above won't work, what you need to do is

```
                this.set_applet_icon_symbolic_name('battery-level-20');
```

Now that wouldn't be the correct symbolic icon but you should use set_applet_icon_symbolic_na,e. I guess it also makes sense to keep the style class name, so I will just reword it into a switch case and change it. Will have to test a bit first.

**Comment by JosephMcc** [comment]
The code you are talking about does exactly what it's meant to. You should not be setting the icon that is being used there.

**Comment by ItzSwirlz** [comment]
> The code you are talking about does exactly what it's meant to. You should not be setting the icon that is being used there.

Where? I don't see anywhere checking the percentage variable (checked all 23) that has anything to do with adjusting the icon. Even going through all the other variables I can't find it.

By doing some small injections into the code I can tell what I need to do (and my previous commit didn't work). Even if you want to do an adjustment every 80%, 70%, 60%, or whatever that's fine. but i guess if we want to bring it into question we can.

**Comment by ItzSwirlz** [comment]
Hm. It seems sometimes it works and sometimes it doesn't.

I'll close the other PR and leave this here for now.

**Comment by mystic-githuber** [comment]
@ItzSwirlz @JosephMcc 

I forgot to mention, I am using arc-x-d & papirus icons.

**Comment by ItzSwirlz** [comment]
What happens if you switch to another icon theme/set?

**Comment by mystic-githuber** [comment]
@ItzSwirlz 
Sorry, what I meant to say was its a problem with any of the icon sets.

**Comment by mystic-githuber** [comment]
@mtwebster 

Could you please look at this? Thank you.

**Comment by ItzSwirlz** [comment]
@mystic-githuber does this occur on 4.6x? After the 4.6 release we rebased our JavaScript Interpeter so we may need to update this

**Comment by mystic-githuber** [comment]
@ItzSwirlz 
I am not a developer or technical, I don't understand what was said. 

As for cinnamon 4.6. I am not sure where to find an older version but I got LMDE which has 4.4.1 and it doesn't seem to have this problem. Screenshot below.

![Screenshot from 2021-01-13 17-06-23](https://user-images.githubusercontent.com/66426048/104485442-661b1780-55c2-11eb-90ff-0ccfafef5ff2.png)

**Comment by ugurcansayan** [comment]
Can confirm this issue is on
Linux Mint 20.1 Cinnamon
Cinnamon: 4.8.6
Kernel: 5.4.0-62-generic


![battery misleading](https://user-images.githubusercontent.com/25729919/104830660-c98e9900-5891-11eb-8ee6-ec760d593c60.png)

**Comment by greenworld99** [comment]
@ItzSwirlz @JosephMcc @mtwebster .......... Devs fix this issue asap. I was in a middle of a presentation and my battery died while I thought more was left because of the icon showing I had much more. 

I am on Cinnamon 4.6.7

**Comment by ItzSwirlz** [comment]
My theory was correct. I'll look into it

**Comment by mtwebster** [comment]
@greenworld99 You can display the percentage or time remaining in the panel from the applet's preferences.

**Comment by greenworld99** [comment]
@mtwebster 
Thank you Dev, I figured that later on while reading the comments in this post but the default view doesn't show the percentage. Hopefully it will be fixed now and other users won't have to go through this.

**Comment by NikoKrause** [comment]
@People with this problem: Which icon themes are you using?

**Comment by mystic-githuber** [comment]
@NikoKrause 
I have tried arc icons, adwaita and contrast-high. I have tried other icon sets and its a problem across the board.

**Comment by LinuxOnTheDesktop** [comment]
For people here who are worried about the battery going dead (or PC shutting down) with insufficient warning, there is this:

![image](https://user-images.githubusercontent.com/47056543/106228529-73035200-61e3-11eb-86e5-cd11f6741478.png)

**Comment by mystic-githuber** [comment]
@ItzSwirlz 
Is mtwebster's solution correct for this bug? Should I close this issue or does it have to do with the Javascript problem you theorized and wait for your commit?

**Comment by ItzSwirlz** [comment]
I'll have to do testing-most of the time C is better for better stability. We won't know if we should close it until we can ensure it's fixed(TM).

**Comment by JosephMcc** [comment]
> I was in a middle of a presentation and my battery died while I thought more was left because of the icon showing I had much more.

In addition to showing the percentage, the theme should also be coloring the icon when it drops below five percent as an additional warning. Not sure what Cinnamon theme you are using.

**Comment by mystic-githuber** [comment]
@JosephMcc 

The issue was not with the theme / icon sets but inaccurate displaying of it. If the battery would have been below 10 % the icon would have been showing that there is half of it left.
