### ISSUE TITLE
Defragmenting an external hard drive in Linux

### ISSUE THREAD

**Issue by Ubuntu-2020** [linuxmint/cinnamon#9830]
It is possible that this topic is not quite at the right address.
But since **Linux Mint** is installed in a large number of users, I believe that this innovation would be very useful to everyone.

As you know **Linux** does not need to defragmenting the hard disk.
And in **Windows** defragmentation is very necessary.
Probably everyone knows that it looks like this:
![Defragmenting](https://user-images.githubusercontent.com/65112331/103659061-ac45fa80-4f74-11eb-8d83-d49ff07d0d56.gif)

Often users run out of free hard drive space and buy an external hard drive:
![external-hard-drive](https://user-images.githubusercontent.com/65112331/103659116-ba941680-4f74-11eb-815a-dde9efb76e7d.jpg)

Almost always, the external hard drive has an **NTFS** or **FAT32** file system.
This is where the question arises: **how can a user defragment an external hard drive**?
But Linux is installed on the user's computer! And in Linux, defragmentation is not done!

Therefore, if possible, please **add a program to Linux Mint** that can defragment an external hard drive with the **NTFS** or **FAT32** file system.

P.S. №1: please do not suggest running defragmentation programs under **Wine**.
P.S. №2: please do not suggest formatting the external hard drive :-)

**Comment by leigh123linux** [comment]
File the feature request at the link provided.

https://github.com/linuxmint/linuxmint/issues
