### ISSUE TITLE
Desklets don't snap until you delete one of them

### ISSUE THREAD

**Issue by dandv** [linuxmint/cinnamon#9834]
```
 * Cinnamon version 4.6.7
 * Distribution - Mint 20 Ulyana
 * Graphics hardware *and* driver used
 * 64 bit
 ```

**Issue**
There's a setting to snap desklets to a grid of configurable size, but it doesn't quite seem to work. If you drag a desklet you'll see a target rectangle, but when you drop it, it doesn't snap to that rectangle. It lands where you release the mouse button.

**Steps to reproduce**
1. Have a Clock desklet somewhere, and two Launcher desklets. Drag one of the Launcher desklets like so:

![image](https://user-images.githubusercontent.com/33569/104091519-f6073d00-5221-11eb-89e1-a0d44b645817.png)

2. Release the mouse button. Notice the desklets aren't aligned as the translucent rectangle had suggested:

![image](https://user-images.githubusercontent.com/33569/104091537-10411b00-5222-11eb-9cfa-82d5943563a0.png)

3. Delete that Clock desklet from the desktop.

![image](https://user-images.githubusercontent.com/33569/104091471-ad4f8400-5221-11eb-9fea-7fda44544a65.png)

4. Now, the desklets will snap:

![image](https://user-images.githubusercontent.com/33569/104091482-bb9da000-5221-11eb-87d9-2ac97003b174.png)

**Comment by GangsterGranule** [comment]
> Cinnamon version 4.8.5
> Distribution - Mint 20.1
> Integrated Intel graphics
> 64 bit

Hi,
Same her.
To be noted, the "delete another desklet" trick also works when you add a desklet.
