### ISSUE TITLE
On monitor update, GDBus error

### ISSUE THREAD

**Issue by ItzSwirlz** [linuxmint/cinnamon#9836]
```
 * Cinnamon version 4.8.5
 * Distribution - Mint 20.1
 * GNOME Boxes
 * 64 bit
 ```

***Gathering info. This issue may be located to cinnamon-settings-daemon under csd-xrandr.***

**Issue**
The following error occurs when setting a monitor display:
![Screenshot from 2021-01-09 18-44-43](https://user-images.githubusercontent.com/24401303/104111020-93f31a00-52ab-11eb-93f3-85d74d08414c.png)

**Steps to reproduce**
Change monitor screen resolution.

**Expected behaviour**
It works as intended, but the error pops up. No error should pop up.

**Other information**
Mintreport shows nothing. Attached cinnamon-monitors.xml aswell

[.xsession-errors.txt](https://github.com/linuxmint/cinnamon/files/5791996/default.xsession-errors.txt)

[var-log-syslog.txt](https://github.com/linuxmint/cinnamon/files/5791999/var-log-syslog.txt)

[cinnamon-monitors.xml.txt](https://github.com/linuxmint/cinnamon/files/5791997/cinnamon-monitors.xml.txt)

**Comment by ItzSwirlz** [comment]
Looking at the syslog, it seems this should be a problem with csd-xrandr. I will investigate more.

By the way, when I set it again it makes my cursor disappear (in VM)

**Comment by ItzSwirlz** [comment]
This is a csd-xrandr issue that should be relocated-but the real error is likely this:

```
Xlib:  extension "DPMS" missing on display ":0".
```

Rerunning csd-xrandr will get rid of the cursor again-maybe its the way csd-xrandr is ran?

**Comment by SteeTee** [comment]
Today I upgraded to Linuxmint 20.1 and struck the problem of this error message. My .xsession-errors has :

**> Failed to execute child process “/usr/lib/x86_64-linux-gnu/cinnamon-settings-daemon/csd-xrandr”**
and the directory **/usr/lib/x86_64-linux-gnu/cinnamon-settings-daemon/** does not exist
Seems Mint 20.1 has failed to add all the components to make the Display manager  work!

**Comment by leigh123linux** [comment]
@SteeTee  Try deleting ~/.config/autostart/cinnamon-settings-daemon-xrandr.desktop

```
rm ~/.config/autostart/cinnamon-settings-daemon-xrandr.desktop
```

**Comment by SteeTee** [comment]
I copied the directory /usr/lib/x86_64-linux-gnu/cinnamon-settings-daemon
from backup

Problem solved but potentially not updated files if any files have received
changes between the 20.0 and 20.1

Steve

**Comment by ItzSwirlz** [comment]
I'll have to see if this occurs on bare metals and I'll try what Leigh suggests. If it's a GNOME Boxes issue I'll close and if it's on bare metal I'll relocate to cinnamon-settings-daemon.

**Comment by ItzSwirlz** [comment]
It's only a GNOME Boxes thing as I can see, should we keep this open and relocate it, or close it?
