### ISSUE TITLE
Application menu crashes on musl distros

### ISSUE THREAD

**Issue by jchook** [linuxmint/cinnamon#9838]
```
 * Cinnamon version: 4.2.4
 * Distribution - Void Linux (musl-cinnamon)
 * Graphics hardware *and* driver used: Default on Live CD via VirtualBox
 * No logs available (.xsession-errors is empty, Void Linux doesn't have a syslog by default)
 ```

**Issue**

Clicking application menu crashes Cinnamon into "Fallback Mode"

**Steps to reproduce**

1. Boot Void Linux ([musl-cinnamon](https://voidlinux.org/download/)) from Live CD
2. Click application menu
3. See crash

**Expected behaviour**

Does not crash.

**Other information**

Re-opening https://github.com/linuxmint/cinnamon/issues/7882

**Configuration info, if applicable**

From previous issue

> Turning off application icons in the application menu config (by right clicking the menu) is a viable workaround, as is installing and using the Papirus theme for application icons. The person who originally reported this issue tested multiple other icon themes to no avail.

**Comment by leigh123linux** [comment]
4.2.x is EOL and you provide no useful debug info. try reporting it to your distro bug tracker instead.

**Comment by groovenectar** [comment]
> 4.2.x is EOL and you provide no useful debug info. try reporting it to your distro bug tracker instead.

Disappointing response to this issue

**Comment by jchook** [comment]
> try reporting it to your distro bug tracker instead.

Thanks I'll try that.

I just tried updating to 4.6.7 (latest available from void's xbps repos) and got even stranger behavior. Works perfectly on glibc version of Void, so the issue seems musl-related.

![image](https://user-images.githubusercontent.com/193530/104138096-c9f9d200-536f-11eb-9c87-ef58b7c5f481.png)
