### ISSUE TITLE
No favourites applet appeared, after adding some favourites

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/cinnamon#9839]
```
 * Cinnamon version (cinnamon --version): 4.8.5
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...): Mint 20.1
 * Graphics hardware *and* driver used: Intel; Mesa
 * 32 or 64 bit: 64
 ```
 [xsession-errors.txt](https://github.com/linuxmint/cinnamon/files/5792220/xsession-errors.txt)

**Issue**

Contrary to [the 'New features in Linux Mint 20.1 Cinnamon' document ](https://www.linuxmint.com/rel_ulyssa_cinnamon_whatsnew.php), sadly, and after adding two 'favourites', I did not 'see a little star pop up in [my] panel'.

**Steps to reproduce**

Get Mint 20.1 Cinnamon. (I got my by upgrading.)
Make some favourites (using Nemo).
See no 'star' appear unless and until one adds it via the applets managed.
Perhaps I had the problem because I have only a top panel - no others - and it is set to auto-hide.

**Expected behaviour**

As per the 'what's new' document.

**Comment by NikoKrause** [comment]
Thanks for reporting. This is indeed true. The favorites applet is new and has been added to the default panel configuration in Mint 20.1. If you do an upgrade from Mint 20 to Mint 20.1 you have to add the applet on your own. Mint doesn't mess with the users panel configuration during an upgrade.

**Comment by LinuxOnTheDesktop** [comment]
The behaviour may be intended but it contradicts the 'what's new' document and will confuse.
