### ISSUE TITLE
error: Settings schema 'org.x.apps.favorites' is not installed

### ISSUE THREAD

**Issue by AngryPenguinPL** [linuxmint/cinnamon#9847]
```
 * Cinnamon: 4.8.5
 * Distribution: OpenMandriva Cooker
 * Graphics hardware *and* driver used: Mesa 20.3.2
 * 64 bit
 * Attach ~/.xsession-errors, or /var/log/syslog
 ```

**Issue**
After updating the entire Cinnamon stack to version 4.8.X, there was a problem starting the session.
When I start Cinnamon I see this error:
```
GLib-GIO-ERROR **: 19:50:20.783: Settings schema 'org.x.apps.favorites' is not installed
Trace/breakpoint trap (core dumped)
```
I don't know where this problem happened from but worth to add if I invoke other packages from Cinnamon stack in terminal like nemo etc I see this same error.

**Steps to reproduce**
Install Mandriva Cooker,
Install Cinnamon or any app from cinnamon stack
Run cinnamon or other apps like nemo

**Expected behaviour**
All works fine

**Comment by mtwebster** [comment]
Did you update the xapp package also? That has the new favorite settings - you need xapp 2.0

**Comment by AngryPenguinPL** [comment]
Yes, xapp is at 2.0.5.

**Comment by mtwebster** [comment]
Ah maybe the settings didn't get installed properly -

Check that the settings file is in the correct place:
```
ls -la /usr/share/glib-2.0/schemas/org.x.apps.gschema.xml
```

If it is, recompile them:
```
sudo glib-compile-schemas /usr/share/glib-2.0/schemas
```

**Comment by AngryPenguinPL** [comment]
Compiling schemas fix this.
Thanks.

**Comment by mtwebster** [comment]
Good news - if this was an 'official' package for your distro, you may want to notify whoever maintains these packages to have a look at this.
