### ISSUE TITLE
windows-quick-list@cinnamon.org: fixed height instead of dynamic

### ISSUE THREAD

**Issue by MinePro120** [linuxmint/cinnamon#9851]
```
 * Applet version/Build date (to be found in "About.." or in "metadata.json")
 N/A (Not found in "About" or "metadata.json")
 * Cinnamon version (cinnamon --version)
 Cinnamon 4.8.5
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
 Arch
 * Graphics hardware *and* driver used
 AMD A10 8700P APU w/ AMD Radeon R5 M335 Discrete Graphics Card
 Drivers: "radeon", "amdgpu"
 * Snippet or attachment of ~/.cinnamon/glass.log
 N/A (No such file or directory)
 * Snippet or attachment of ~/.xsession-errors
https://github.com/linuxmint/cinnamon-spices-applets/files/5803707/xsession-errors.txt

 ```

**Notify author of applet**
@cinnamon.org (I can't seem to find any authors or even a mention of this applet anywhere)
**Issue**
The height of the "window" (when clicking on it) doesn't change according to the height of the content inside it. For example, with no windows open, the height is the same with 1 or 2 windows open. The width though, does change according to the size of the content.
![is](https://user-images.githubusercontent.com/37949795/104381747-a41e2a00-5535-11eb-943e-d737ec3fc600.png)

**Steps to reproduce**
Click on the applet with a few (0-5) windows open.

**Expected behaviour**
The height of the pop-up window should change according to the content (just like the width).
![shouldbe](https://user-images.githubusercontent.com/37949795/104381773-ae402880-5535-11eb-9d28-6956344f136a.png)
(Edited with GIMP)

**Comment by NikoKrause** [comment]
This is not a spice. This is an original applet in Cinnamon. Therefore i transfered the issue.

You might like to add a few screenshots to describe your issue better.

**Comment by MinePro120** [comment]
Ah, thanks. Will do.

**Comment by ikoveshnikov** [comment]
I've made a fix for it: #9935 , it requires a single JS file modification.

**Comment by MinePro120** [comment]
Seems good.

**Comment by ikoveshnikov** [comment]
@mtwebster @MinePro120 The solution was merged, I believe the issue can be closed now.
