### ISSUE TITLE
Issue template: explain how to determine the graphics hardware *and* drive used

### ISSUE THREAD

**Issue by dandv** [linuxmint/cinnamon#9857]
The [issue template](https://github.com/linuxmint/cinnamon/blob/master/.github/ISSUE_TEMPLATE.md) here in GitHub asks for "Graphics hardware *and* driver used".

I don't know off the top of my head how to provide that information. It would help to list a command or some mechanism to obtain it.

**Comment by icarter09** [comment]
`System Info` provides the necessary information.

**Comment by dandv** [comment]
1. I don't see any information about the *driver* in System Info:

![image](https://user-images.githubusercontent.com/33569/104828331-53941e80-580c-11eb-81a2-ad657efef7ba.png)

2. If `System Info` provides that information, why not go ahead and fix the issue template?
