### ISSUE TITLE
Add description for `im-launch` in Startup Applications

### ISSUE THREAD

**Issue by dandv** [linuxmint/cinnamon#9863]
![image](https://user-images.githubusercontent.com/33569/104695046-34807a00-56b0-11eb-884d-484de7e6a0cc.png)

**Comment by icarter09** [comment]
I see another application in that list with "No description" as well. Instead of being application specific, the ticket could be changed to hit all applications that need a description, "Add missing descriptions for Startup Applications" or something along those lines. Thanks.

**Comment by JosephMcc** [comment]
Actually this isn't a Cinnamon issue. That works by looking in all the relevant autostart directories and reading the desktop files they contain. It reads the contents of the files to provide that information. If the desktop files does provide a "Comment" field then we have to description to put there. We already make one up when it doesn't provide one. It's "No description". That issue needs to be fixed for the individual startup applications.

**Comment by dandv** [comment]
> I see another application in that list with "No description" as well.

Sorry, I didn't notice that.

> Instead of being application specific, the ticket could be changed to hit all applications that need a description

Cool, why not [go ahead](https://github.com/linuxmint/cinnamon/issues/9857#issuecomment-761708921) and change the ticket title? To both fry the fish teach me how to fish: "I see another application in the list... so I've updated the ticket title to...".

> Actually this isn't a Cinnamon issue. That works by looking in all the relevant autostart directories and reading the desktop files they contain.

OK... As a casual user, I have no idea what's going on behind the scenes. I try to help as much as I can by reporting issues. But if they're closed with "That issue needs to be fixed for the individual startup applications.", that doesn't encourage me to continue.

What options do I have at this point? Try to figure out where the repos are for each individual application (Launchpad? GitLab?), go there, file a bug as a rando? While you probably know much better than me where those applications are maintained and could either point me in that direction (to minimize work for yourself, which is totally fair), or file the issue yourself, putting your clout as a Mint developer behind it.
