### ISSUE TITLE
Cursor Behaviour LMDE 4

### ISSUE THREAD

**Issue by jakoblm** [linuxmint/cinnamon#9864]
* Cinnamon version 4.8.6
   - No PPA used
 * Distribution: LMDE 4
 * Graphics hardware: *Intel Core i7-2620M 
 * driver: i915
 * 64 bit

**Issue**
I refer to this already closed issue: https://github.com/linuxmint/mint20.1-beta/issues/28 
The bug has already been fixed in Mint 20.1, but not in LMDE 4. 
The described workaround still works: `cp /usr/share/applications/redshift-gtk.desktop ~/.local/share/applications` and comment out `#StartupNotify=true`. 

But it would be great if the fix was officially included in LMDE 4.

**Comment by icarter09** [comment]
@jakoblm this will be fixed once the package is updated for LMDE. I'm going to close this ticket, but will reopen it if you continue to notice the issue after the update. Thanks.

**Comment by jakoblm** [comment]
The bug seems to be still present in LMDE 4. When will the package be updated?
