### ISSUE TITLE
Mint 20.1: attaching HDMI cable undid Hi-DPI scaling on my (sole) display and caused windows to appear off screen

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/cinnamon#9865]
```
 * Cinnamon version (cinnamon --version) 4.8.6
   - Please specify if you are using the daily builds PPA: no
     (https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds).
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 20.1
 * Graphics hardware *and* driver used: Intel; Mesa
 * 32 or 64 bit: 64.
 * Attach ~/.xsession-errors, or /var/log/syslog
 ```
[xsesh.txt](https://github.com/linuxmint/cinnamon/files/5822404/xsesh.txt)

**Issue**

Attaching a HDMI cable (1) undid the Hi-DPI scaling on my main and indeed sole display and (2) caused some windows (the main windows from respectively Gnome System Monitor and Lollipop) to appear off screen. I found after that after upon removing the cable, the missing windows reappeared. 

I write of my _sole_ display because the other end of the cable was plugged into an amplifier. Now admittedly it turned out I was using the wrong cable for the amplifier. But still, I really do not think that 1 and 2 should happen in this circumstance.

**Steps to reproduce**

The above. But perhaps merely connecting one end of the HDMI cable will suffice.

**Expected behaviour**

HiDPI scaling on one's main and perhaps only screen should be unaffected by whatever other screen one has connected, at least when one first establishes the connection. Nor should windows appear only when one removes a cable.

**Other information**

Neofetch:

OS: Linux Mint 20.1 x86_64
Host: 20KH001UKP ThinkPad X1 Carbon 6th
Kernel: 5.8.18-050818-generic
Uptime: 14 mins
Packages: 3325 (dpkg)
Shell: bash 5.0.17
Resolution: 2560x1440 @ 60.01Hz
DE: Cinnamon
WM: Mutter (Muffin)
WM Theme: Mint-Y-Dark (Mint-Y-Dark)
Theme: Mint-Y-Dark [GTK2/3]
Icons: Paper [GTK2/3]
Terminal: xfce4-terminal
Terminal Font: InconsolataGo 12
CPU: Intel i7-8550U (8) @ 1.800GHz
GPU: Intel UHD Graphics 620
Memory: 1531MiB / 15899MiB
Disk (/dev/nvme0n1p4): 18G / 40G (47%)
Disk (/dev/nvme0n1p2): 158G / 405G (42%)
Disk (udev): 0 / 7.8G (0%)

**Comment by sangorys** [comment]
Maybe this bug is linked to https://github.com/linuxmint/cinnamon/issues/9901 ?

**Comment by LinuxOnTheDesktop** [comment]
I have not seen this problem recently.
