### ISSUE TITLE
Traditional panel in Welcome screen doesn't have favourites by default

### ISSUE THREAD

**Issue by ugurcansayan** [linuxmint/cinnamon#9867]
```
 * Cinnamon version (cinnamon --version) Cinnamon 4.8.6

   - Please specify if you are using the daily builds PPA
     (https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds).
 * Distribution - Mint 20.1
 * Graphics hardware *and* driver used
 * 64 bit
 * Attach ~/.xsession-errors, or /var/log/syslog
 ```

**Issue**
Traditional panel does not have Favourites by default // It has Favourites by default in Modern & panel-reset

**Steps to reproduce**
Launch Welcome screen
Choose Panel layout 
Click Traditional

**Expected behaviour**
Have Favourites applet/icon near Network Manager

**Other information**
Favourites applet/icon is near Network Manager in Modern panel & panel-reset

**Configuration info, if applicable**
All vanilla, Linux Mint 20.1 Cinnamon**

----

Thank you for your hard work

**Comment by NikoKrause** [comment]
I've noticed that too a few days ago and already fixed it in MintWelcome. We'll need to wait for an update of mintwelcome:

https://github.com/linuxmint/mintwelcome/pull/45

**Comment by NikoKrause** [comment]
P.S.: For the time being you can add the Favourites applet manually in the Cinnamon Settings.

**Comment by ugurcansayan** [comment]
> I've noticed that too a few days ago and already fixed it in MintWelcome. We'll need to wait for an update of mintwelcome:
> 
> [linuxmint/mintwelcome#45](https://github.com/linuxmint/mintwelcome/pull/45)

Thanks for your reply and apologies for the repost



> P.S.: For the time being you can add the Favourites applet manually in the Cinnamon Settings.
I had to figure it out myself but thanks for the advice :)
