### ISSUE TITLE
Cinnamon crashing seemingly out of the blue

### ISSUE THREAD

**Issue by AndreiMiculita** [linuxmint/cinnamon#9871]
```
 * Cinnamon version 4.8.6
 * Distribution - Mint 20.1
 * Graphics hardware NVIDIA GF108M [GeForce GT 620M/630M/635M/640M LE] driver: nvidia 390.141
 * 64-bit
 ```
 * [stack trace](https://termbin.com/1b0m)
 * [crash.tar.gz](https://drive.google.com/file/d/1h8SxgCzCARjjAt99oJCzGuWjRVKPKuOy/view?usp=sharing)

**Issue**
Cinnamon seems to occasionally crash for no apparent reason (once every 3-4 days). I've tried disabling applets that could be causing it, one by one, but it still happens.

**Steps to reproduce**
Don't know. I don't understand the stack trace well enough to explain what happened.
I've attached the stack trace and the crash.tar.gz generated by mintreport.

**Comment by icarter09** [comment]
Are you still experiencing this issue?

**Comment by AndreiMiculita** [comment]
The last occurrence was on Feb 5th. It still happens every few days.

* [stack trace](https://termbin.com/fgdp)
* [crash.tar.gz](https://drive.google.com/file/d/1RkC90qMAa0yn_aaCG1jjdsfqSGwUs60T/view?usp=sharing)

**Comment by AndreiMiculita** [comment]
Happened again.

* [stack trace](https://termbin.com/ze0w)
* [crash.tar.gz](https://drive.google.com/file/d/1IrD6RIO3Em3PTWIGHDVZk7AdfOC6r_uA/view?usp=sharing)

**Comment by AndreiMiculita** [comment]
And again (this time after a fresh reinstall)

* [stack trace](https://termbin.com/4qhb)
* [crash.tar.gz](https://drive.google.com/file/d/1a9bjgjgPQpYvifQ6De8hK_BuvkDrBIaG/view?usp=sharing)

**Comment by icarter09** [comment]
I'm probably going to ask some stupid questions in the process of narrowing down the issue so bare with me. 
   - Were you experiencing this issue when using Mint 20 or any past version? 
   - After the fresh reinstall, how long did it go before crashing? 
   - During that time, did you install any applets/desklets? 
   - What kernel version are you using? 
Thanks.

**Comment by leigh123linux** [comment]
@AndreiMiculita 
Your stacktraces are a worthless waste of time, install the debug symbols!

**Comment by AndreiMiculita** [comment]
@icarter09 
* No, I'm pretty sure it started when I upgraded 20.1
* About 14 hours, during which I restored the home folder from a .tar backup, using the Linux Mint backup tool.

* This is the list of installed applets (all installed before the crash):
```
AutostartPrograms@spacy01          multicore-sys-monitor@ccadeptic23
batterymonitor@pdcurtis            pomodoro@gregfreeman.org
bing-wallpaper@starcross.dev       qredshift@quintao
Cinnamenu@json                     Sensors@claudiux
collapsible-systray@feuerfuchs.eu  SpicesUpdate@claudiux
kdecapplet@joejoetv                temperature@fevimu
kdeccc@Severga                     weather@mockturtl
```

And a single desklet.
```
clock@schorschii
```

Of these, I've activated **Cinnamenu**, **QRedshift**, and **SpicesUpdate**. But I'm not sure which were active at the moment of the crash (I'd assumed the list of active applets would be included in the generated crash.tar.gz). I'll try to use my desktop without any of them for a while, and see if the issue persists. I'd provide the log from `cinnamon-looking-glass`, but unfortunately, after restarting cinnamon, it doesn't show anything from before the crash. I haven't tried to open `cinnnamon-looking-glass` when Cinnamon runs in safe mode right after the crash, I'll try it next time it happens.

* kernel: 5.4.0-66-generic x86_64


@leigh123linux Thanks for the advice. I checked and I have the `cinnamon-debug` package installed. If you have any other advice to help me provide more detail, please do tell me. These reports are made as instructed by mintReport. But really your tone invites me to wonder who hurt you, more than anything else. I'm trying to be as cooperative as I can be.

**Comment by leigh123linux** [comment]
@AndreiMiculita You need cjs, glib2 and mesa debug packages.

**Comment by andymeadows** [comment]
Experiencing this same issue.  Random crashes.  Nothing special being run other than it is being run in a VM.  As with Andrei's (based on reading the thread), it is also crashing in glib2.  Worthless (@leigh123linux) [stack trace](https://termbin.com/pszo) is at https://termbin.com/pszo.  Will install the debug packages and report back if I can catch it again.

The Looking Glass log of what is loaded is as follows:

> info t=2021-05-26T14:16:27Z Cinnamon.AppSystem.get_default() started in 969 ms
info t=2021-05-26T14:16:27Z loading user theme: /usr/share/themes/Mint-Y-Dark-Orange/cinnamon/cinnamon.css
info t=2021-05-26T14:16:27Z added icon directory: /usr/share/themes/Mint-Y-Dark-Orange/cinnamon
info t=2021-05-26T14:16:27Z loaded at Wed May 26 2021 14:16:27 GMT-0400 (Eastern Daylight Time)
info t=2021-05-26T14:16:27Z ExtensionSystem started in 5 ms
info t=2021-05-26T14:16:27Z DeskletManager started in 3 ms
info t=2021-05-26T14:16:27Z SearchProviderManager started in 1 ms
info t=2021-05-26T14:16:28Z Loaded applet show-desktop@cinnamon.org in 126 ms
info t=2021-05-26T14:16:28Z Role locked: tray
info t=2021-05-26T14:16:28Z Loaded applet systray@cinnamon.org in 15 ms
info t=2021-05-26T14:16:28Z Loaded applet removable-drives@cinnamon.org in 7 ms
info t=2021-05-26T14:16:28Z Loaded applet favorites@cinnamon.org in 8 ms
info t=2021-05-26T14:16:28Z Role locked: notifications
info t=2021-05-26T14:16:28Z Loaded applet notifications@cinnamon.org in 20 ms
info t=2021-05-26T14:16:28Z Loaded applet printers@cinnamon.org in 29 ms
info t=2021-05-26T14:16:28Z Loaded applet keyboard@cinnamon.org in 15 ms
info t=2021-05-26T14:16:28Z Loaded applet calendar@cinnamon.org in 65 ms
info t=2021-05-26T14:16:28Z Loaded applet xapp-status@cinnamon.org in 5 ms
info t=2021-05-26T14:16:28Z Loaded applet workspace-switcher@cinnamon.org in 57 ms
info t=2021-05-26T14:16:28Z Role locked: panellauncher
info t=2021-05-26T14:16:28Z Loaded applet grouped-window-list@cinnamon.org in 44 ms
info t=2021-05-26T14:16:28Z Loaded applet power@cinnamon.org in 32 ms
info t=2021-05-26T14:16:28Z Adding XAppStatusIcon: nm-applet (:1.48/org/x/StatusIcon/Icon)
info t=2021-05-26T14:16:28Z Loaded applet sound@cinnamon.org in 81 ms
info t=2021-05-26T14:16:28Z Hiding XAppStatusIcon (we have an applet): nm-applet (:1.48/org/x/StatusIcon/Icon)
info t=2021-05-26T14:16:28Z Loaded applet network@cinnamon.org in 61 ms
info t=2021-05-26T14:16:28Z Loaded applet menu@cinnamon.org in 118 ms
info t=2021-05-26T14:16:28Z AppletManager started in 862 ms
info t=2021-05-26T14:16:28Z Cinnamon took 2254 ms to start

No Desklets.

**Comment by mehdi-rahimi** [comment]
Added some logs to this bug too:
[https://github.com/linuxmint/cinnamon/issues/9916#issuecomment-896049371](https://github.com/linuxmint/cinnamon/issues/9916#issuecomment-896049371)
