### ISSUE TITLE
Consider switching to/writing a terminal emulator that supports mouse click cursor positioning like DomTerm

### ISSUE THREAD

**Issue by mcarans** [linuxmint/cinnamon#9872]
**Issue**
Using the mouse in the terminal emulator to click to position the cursor doesn't work.

**Steps to reproduce**
Type text in terminal. Use mouse to move pointer to middle of text. Click left button.

**Expected behaviour**
Cursor should move to where mouse is clicked, but cursor doesn't move.

**Other information**
I've also raised this [upstream with Gnome Terminal](https://gitlab.gnome.org/GNOME/gnome-terminal/-/issues/322), but not sure of the likelihood of this being done. [DomTerm](https://domterm.org/) can already do this (even with bash), but is challenging for new users to install (requires compiling from source) and is based on QT rather than Gnome.

**Comment by JosephMcc** [comment]
Thanks for the input. Cinnamon doesn't include any terminal emulator and there are no plans to do so. Whichever one you have preinstalled was decided by your distro.

**Comment by mcarans** [comment]
> Thanks for the input. Cinnamon doesn't include any terminal emulator and there are no plans to do so. Whichever one you have preinstalled was decided by your distro.

@JosephMcc My distro is Linux Mint - against which repository should I raise this issue?

**Comment by JosephMcc** [comment]
You could raise it here: https://github.com/linuxmint/linuxmint
However, there are no plans to write an emulator of our own. Your best bet was doing what you already did, bringing it upstream to gnome terminal.
