### ISSUE TITLE
Feature Request: Make Desktop Shortcuts for Web Apps

### ISSUE THREAD

**Issue by svidovich** [linuxmint/cinnamon#9878]
The new web apps feature that was released with Ulyssa is _amazing_. I'm already using it for google messages so I can have a separate window dedicated just to that. I love it!

I would love to also be able to make a desktop shortcut for any of the web apps I make. Is that possible?

Thank you!

**Comment by NikoKrause** [comment]
If you are using Cinnamon:
When you create a Web App, it should appear in the menu. Rightclick the web app in the menu. Click on "Add to desktop."

**Comment by JosephMcc** [comment]
Closing since it was answered.

**Comment by svidovich** [comment]
Hmm @NikoKrause Nothing at all seems to happen when I right click -- perhaps this is a bug?

```
mydriasis@m:~$ inxi -Sxxxx
System:
  Host: m Kernel: 5.4.0-42-generic x86_64 bits: 64 compiler: gcc v: 9.3.0 
  Desktop: Cinnamon 4.8.5 wm: muffin 4.8.0 dm: LightDM 1.30.0 
  Distro: Linux Mint 20 Ulyana base: Ubuntu 20.04 focal 
```

![image](https://user-images.githubusercontent.com/16866899/104963645-fda8ad80-59a8-11eb-9cd4-262c148196d0.png)


By the way, OMG you guys are fast :D

**Comment by NikoKrause** [comment]
I mean the menu in the panel. Usually at the bottom left of your screen

**Comment by JosephMcc** [comment]
Once you create the web app it will create an entry in the Cinnamon start menu. Right click it there to get the option.

**Comment by svidovich** [comment]
Thank you so much -- fabulous! Have a great day, y'all!
