### ISSUE TITLE
Stays unlocked if start menu open

### ISSUE THREAD

**Issue by ssmid** [linuxmint/cinnamon#9879]
```
 * Cinnamon version 4.8.6
    No daily builds PPA
 * Distribution - Mint 20.1
 * Intel UHD Graphics 620
 * 64 bit
 ```

**Issue**
The system won't lock if cinnamon's start menu is open.

My start menu opens when I'm only hovering over it with my mouse. And when I do this by accident before closing my notebook, if find it still being unlocked the next time I open it.
It's not much of an issue, but still it makes me feel like I couldn't trust Linux Mint enough to not manually locking the system, everytime I leave my computer.

**Steps to reproduce**
- Open start menu
- Press Ctrl + Alt + L  or  close notebook

**Expected behaviour**
Lock screen shows up

**Comment by NikoKrause** [comment]
You can turn of opening the menu on hover

**Comment by ssmid** [comment]
I'd rather leave it as it is, this issue is more for information. If this has no priority and won't be fixed, you can close the issue :)

**Comment by JosephMcc** [comment]
This has been around a long time: https://github.com/linuxmint/cinnamon-screensaver/issues/93

**Comment by ssmid** [comment]
Didn't find this one, my bad
