### ISSUE TITLE
Favorite file shows up as duplicate in the start menu

### ISSUE THREAD

**Issue by dandv** [linuxmint/cinnamon#9883]
```
 * Cinnamon version 4.8.6
 * Distribution - Mint 20.1
 * 64 bit
 ```

**Steps to reproduce**
1. Open a file from the file manager
2. Add that file to Favorites
3. From the Mint Start Menu, type the name of the file

There will be two results, both pointing to the same file, one in a human-friendly format, the other URL-encoded. Meta-screencast below.

![Duplicate start menu entry for favorite files](https://user-images.githubusercontent.com/33569/105192351-1796dd00-5adc-11eb-8af6-45392c137306.gif)

**Comment by mtwebster** [comment]
You're probably seeing the file listed in Recent files as well as favorites. At the moment there isn't a way to prevent favorites from being added to recent files.

The encoding problem is a bug, I'll try to fix that.

**Comment by mtwebster** [comment]
Encoding fixed:

https://github.com/linuxmint/cinnamon/commit/28692e9bfa988cc239d1bd9ed7e15f65c9129db2
