### ISSUE TITLE
mount iso error

### ISSUE THREAD

**Issue by AVE-RVV** [linuxmint/cinnamon#9887]
I am trying to mount any iso. But I am getting this error:   GDBus.Error:org.freedesktop.UDisks2.Error.Failed: Error waiting for loop object after creating '/dev/loop0': Timed out waiting for object

![Снимок экрана от 2021-01-22 22-30-15](https://user-images.githubusercontent.com/75805766/105510691-8a34d200-5d01-11eb-8606-202cfe371377.png)

 Kernel: 5.8.0-40-generic x86_64 bits: 64 compiler: N/A Desktop: Cinnamon 4.8.6 
 wm: muffin dm: LightDM Distro: Linux Mint 20.1 Ulyssa base: Ubuntu 20.04 focal

**Comment by leigh123linux** [comment]
Closed  https://github.com/linuxmint/nemo/issues/2636
