### ISSUE TITLE
Windows Borders themes broken

### ISSUE THREAD

**Issue by 4turtlez** [linuxmint/cinnamon#9888]
When one changes window borders to other types(adapta,etc) many apps do not change to them but keep the Minty ones. This also includes in Firefox when one turns off the title bar...

**Comment by mtwebster** [comment]
The windows you're talking about have their titlebars themed by the Gtk (controls) theme, not the window border theme.

A lot of modern apps have started using what's called 'client-side decorations', which means the app itself draws the *entire* window, including their titlebar (you'll notice on these types of windows they can actually put buttons and things in their titlebars.

Firefox behaves the same way when you turn off 'title bar' in the customize page.

Unfortunately, for now this can create some inconsistencies when your window border and control themes diverge. We may change our window manager to eliminate this issue some time in the future.
