### ISSUE TITLE
Cinnamon Crashes After Installing an Update

### ISSUE THREAD

**Issue by LightningsFury** [linuxmint/cinnamon#9890]
### **UPDATE: I've eventually found out that mesa is the cause behind this error!** 

```
 * Cinnamon version (cinnamon --version): **4.8.6**
   - Please specify if you are using the daily builds PPA
     (https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds): **No**
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...): **Mint 20.1**
 * Graphics hardware *and* driver used 
![image](https://user-images.githubusercontent.com/40724972/105618605-1f5ac800-5de1-11eb-9e29-11440e67546c.png)

 * 32 or 64 bit: **64 but**
 * Attach ~/.xsession-errors, or /var/log/syslog **Currently I do not have access to this.**
 ```

**Issue**
This happened a few days ago now, but I was recommended that I post this issue here. 

I've only recently installed Linux Mint, on an old laptop that used to run Windows 7.

Linux Mint works perfectly and better than other distros on this device, insofar as I go towards the update that it recommends I take. Twice, I've installed the update, rebooted my device, only to be greeted with: _(along the lines of)_
> Cinnamon has crashed
> Disable Applets
> Run in safe mode
> Blah blah

If I disable applets and do whatever I can, it is all in vain since I'm perpetually stuck in a loop of Cinnamon crashing outside of being in safe mode. Due to this, with Timeshift, I was forced to return back to a period before I installed the updates; twice until I figured out the root of the problem. 

Of-course, I can always ignore these updates, but its quite agitating to be frank.
**Steps to reproduce**
The update I installed was:
![image](https://user-images.githubusercontent.com/40724972/105618675-fab32000-5de1-11eb-9077-8493e6d3f6b7.png)

Immediately after I rebooted the device. The first time around, I also sudo apt updated, and did a few other miscellaneous tidying-ups. The errors come up after I log in. 

**Expected behaviour**
I expect to be greeted with my wonderful Cinnamon desktop environment <3

**Other information**
I don't really know how this all works, so please tell me if I should add any more information. For safe measures, here's my 
### Neofetch
![image](https://user-images.githubusercontent.com/40724972/105618720-84fb8400-5de2-11eb-802c-7c44352db63b.png)

**Configuration info, if applicable**
Is it applicable?

**Comment by icarter09** [comment]
@LightningsFury have you tried installing each of the updates individually to see which one is the cause?

**Comment by LightningsFury** [comment]
> @LightningsFury have you tried installing each of the updates individually to see which one is the cause?

I haven't, I'd try this when I have time, although I don't wish to have to restore through Timeshift again, since for some reason every time I restore (even from a recent image) I end up having to reinstall packages I had installed with sudo apt-get.

**Comment by lesha198a** [comment]
I have the same issue

**Comment by lesha198a** [comment]
I've updated apt and mesa too
![image](https://user-images.githubusercontent.com/44326479/106151833-70720f80-6185-11eb-8b39-8e81c62a1d4a.png)
![image](https://user-images.githubusercontent.com/44326479/106151940-926b9200-6185-11eb-9610-70ac4d485977.png)

**Comment by LightningsFury** [comment]
> I've updated apt and mesa too
> ![image](https://user-images.githubusercontent.com/44326479/106151833-70720f80-6185-11eb-8b39-8e81c62a1d4a.png)
> ![image](https://user-images.githubusercontent.com/44326479/106151940-926b9200-6185-11eb-9610-70ac4d485977.png)

Have you tested which updates cause the problem? (because I haven't, and my updates are piling up)

**Comment by lesha198a** [comment]
I've downgraded those updates, but it hasn't helped at all

**Comment by lesha198a** [comment]
It seems that problem in Muffin, but I'm not really sure

**Comment by LightningsFury** [comment]
So, today I tried just running **sudo apt update** and **sudo apt upgrade** and this issue came up again, if that clarifies or specifies anything @icarter09

**Comment by lesha198a** [comment]
https://termbin.com/n961

**Comment by lesha198a** [comment]
Here is my crash report from cinnamon. @LightningsFury you can do it too from application System Reports

**Comment by LightningsFury** [comment]
So I tried install some updates today, I had a few lined up, and I did all of the except apt and pulseaudio, and it crashed, meaning that the culprit package is probably either the linux kernel or mesa, but I can't rule out that apt has caused a problem too. 
Here is my crash report: 
https://termbin.com/7wl7

Time to timeshift once again.

**Comment by icarter09** [comment]
@LightningsFury update everything but mesa and let's see how that goes.

**Comment by LightningsFury** [comment]
@icarter09 So I did that, and it worked! Meaning mesa seems to be the culprit...
As Sherlock Holmes says:
> Once you have eliminated the impossible, whatever remains, however improbable, must be the truth



Shall I update the issue to ostracise mesa?

**Comment by icarter09** [comment]
@LightningsFury glad we found the issue! Yes that's a good idea in case other users hit the same problem.
