### ISSUE TITLE
Notifications are shown on the secondary screen

### ISSUE THREAD

**Issue by dandv** [linuxmint/cinnamon#9891]
```
 * Cinnamon version 4.8.6
 * Distribution - Mint 20.1
 * Graphics hardware *and* driver used - Intel UHD Graphics 620 (Whiskey Lake), how can I tell what driver?
 * 64 bit
 ```

**Issue**
Another dual-monitor setup issue ([details about my setup here](https://github.com/linuxmint/cinnamon/issues/9828)): notifications are sent to the secondary, rather than the primary, screen.

**Steps to reproduce**
1. Launch System Settings -> Notifications
2. Click "Display a test notification".

![Notifications shown on the secondary screen](https://user-images.githubusercontent.com/33569/105621158-c707d400-5da8-11eb-8adb-95fc5e695799.png)

**Comment by ItzSwirlz** [comment]
Hm. This is something I'll see if I can reproduce. It may be simple enough in the JS Notification Daemon to just tell it to show notifications on both monitors, preferrably.

**Comment by dandv** [comment]
My bad, I think I had not set as `Primary` the external monitor. @ItzSwirlz Feel free to close if you can't reproduce.

As to whether the notification should be shown on both monitors... interesting idea. :man_shrugging:

**Comment by MrBargz** [comment]
Could you add the option in the notification settings to select where you want to show the notifications? example: primary monitor, secondary monitor, both.
