### ISSUE TITLE
[FR] Show Suspend button in Ctrl+Alt+Del dialog

### ISSUE THREAD

**Issue by dandv** [linuxmint/cinnamon#9892]
```
 * Cinnamon version 4.8.6
 * Distribution - Mint 20.1
 ```

Here are two very similar dialogs, both titled "Session". This is the Ctrl+Alt+Del dialog:

![image](https://user-images.githubusercontent.com/33569/105655641-853c6380-5e64-11eb-81d2-1c52647f6ce1.png)

And this is the Menu -> Quit dialog:

![image](https://user-images.githubusercontent.com/33569/105655633-8077af80-5e64-11eb-9b3a-3394a73e6e29.png)

Do they need to be different? The problem is I want to suspend the computer easily, and having "Suspend" in the Ctrl+Alt+Del dialog would do the job (barring [the focus issue](https://github.com/linuxmint/cinnamon/issues/9850)). But now to find the Suspend menu, I have to do some keyboard acrobatics (Super -> Left -> Up -> Enter (and then I run into the same focus issue). 

Another suggestion would be to add accelerators to the dialogs.

**Comment by leigh123linux** [comment]
Request Denied.

**Comment by dandv** [comment]
OK, I'm not asking for friendliness here, but a reason would be nice?

**Comment by dandv** [comment]
> Request Denied.

OK, I'm not asking for friendliness here, but a reason would be nice?

**Comment by leigh123linux** [comment]
It's been requested before and rejected, we don't want to mix  the options.

**Comment by NikoKrause** [comment]
One dialog has options, which are turning off your PC. The other dialog has no options, which do that. I guess that's one reason not to mixing those two. And if you combine those dialogs, it would be too many buttons in one dialog.

My idea would be to change the keyboard shortcuts.
