### ISSUE TITLE
Taskbar does not remember position of windows after closing any window

### ISSUE THREAD

**Issue by rafjar1188** [linuxmint/cinnamon#9900]
```
Cinnamon 4.8.6
Linux Mint 20.1
 ```

**Issue**
Taskbar/Panel does not remember the position of windows. When closing an application or a application window it looks like taskbar refreshes itself and scrambles all windows positions.

**Expected behaviour**
Windows on Taskbar/Panel should stick to their position after closing any window. It is especially annoying when you have set not to group windows by application and show windows titles - I like have applications which are open organized on Taskbar. This problem does not exist on 20.0 - have it on another device and works perfectly.

**Comment by ronyala** [comment]
Hi, it's mostly fixed in https://github.com/linuxmint/cinnamon/pull/9899
These 'resets' will still happen however when closing a pinned window and using ungrouped windows (as it was originally done to circumvent a bug causing pinned windows to become unpinned in that mode)
