### ISSUE TITLE
xlet-settings.py performance issue

### ISSUE THREAD

**Issue by ByteEnable** [linuxmint/cinnamon#9905]
- Cinnamon 4.8.6
- no daily builds
- Fedora 33
- NVidia GTX1060
- X86_64

**Issue**
xlet-settings consumes high amount of CPU and heavily sputters and freezes while attempting to scroll through icons in the menu dialog -> icons.  After some amount of time the CPU load decreases and the dialog becomes responsive which suggests some sort of caching or list is being created. 

**Steps to reproduce**
Install papirus-dark icon theme.
Right click Menu -> Configure -> icon.  The icon dialog pops up and select applications from the left pane.  Attempt to scroll through the icons.  

**Expected behaviour**
For the dialog to scroll seamlessly and not consume high amounts of CPU.

**Other information**

**Configuration info, if applicable**
If this bug report is related to an Applet, Desklet or Extension, please paste (or use a pastebin service) the offending extension's settings, if it has any.  You can obtain this by opening its configuration, clicking the 'hamburger' button in the upper-right corner of the window, and selecting "Export to a file". **Please be sure to review the contents and remove any personal data it may contain.**

```

Please paste here

```

**Comment by collinss** [comment]
A couple of things. First, this is not actually a cinnamon issue. The dialog is actually provided by xapp. Second, and more important, there is really very little that can be done to speed this up from a coding standpoint. Processing that many images requires large amounts of bandwidth from your hdd/ssd/nvme, regardless of how efficient the code is. The only way to really speed it up any more is to use a faster storage device.

**Comment by ByteEnable** [comment]
Its a running on a Samsung SSD Nvme @ 3500 MBps. 

nvme-Samsung_SSD_970_EVO_Plus_500GB_S4P2NF0M417243N

Thanks for the runaround.
