### ISSUE TITLE
Remove custom shortcut in Linux Mint 20.1 cinnamon edition not working.

### ISSUE THREAD

**Issue by M4c4k** [linuxmint/cinnamon#9913]
## Issue
"Remove custom shortcut" button in Linux Mint 20.1 cinnamon edition is not working.

![Screenshot 2021-02-06 21:35:35](https://user-images.githubusercontent.com/67242036/107129123-72de1300-68c3-11eb-9bee-5ca168c45c61.png)

**Comment by Xmetalfanx** [comment]
not familiar with the keybinds but if there are no custom shortcuts to remove, that would be greyed out

**Comment by mtwebster** [comment]
You can't remove 'Volume Up' - to remove the alt-up keybinding, click on that keybinding so it says 'Pick and accelerator', and hit backspace (this is explained at the bottom of the window).

Custom shortcuts are in the.. 'Custom Shortcuts' section shown on the left - with those you can set up commands or specific programs to run via a key combination.
