### ISSUE TITLE
[Feature Request] Sound volume steps

### ISSUE THREAD

**Issue by Butterfly1984** [linuxmint/cinnamon#9919]
Mint 20.1 Cinnamon

Volume goes by steps of 5% when using volume up/down buttons on keyboard or scroll wheel on sound bar in Cinnamon sound applet.
When using 5.1 surround speakers that are at full volume, going from 0 to 5% is a huge step.

I'd rather hold the volume button half a second to go up 5% in volume instead of going up 5% volume by a single tap of the volume up button.

Requested feature:
Being able to set volume steps to 1% or 2% instead of the default 5%.

**Comment by ItzSwirlz** [comment]
This is a good point. An update would be needed to cinnamon-settings-daemon's sound plugin (csd-sound) and then a plug into cinnamon-settings will do.

**Comment by mtwebster** [comment]
fyi,

https://github.com/linuxmint/cinnamon/pull/8884

**Comment by Butterfly1984** [comment]
> fyi,
> 
> #8884
I've searched for issues that related to my feature request but didn't find it (probably cause I included the word 'sound' in my search term)
It's good to know that the discussion has been made already and there's a workaround but I'd like to see a more user-friendly option to change the scaling of the volume steps.

Since it seems like a working code for it already exist, I think it could be fairly easy to implement it.

In terms of how to implement it in a the GUI design, i made a quick (poorly designed, sorry, I'm not great with picture editing) sketch of what I had in mind:

https://i.imgur.com/VdtsjVB.png

The Sound Settings tab is currently practically empty, and it seems like the best place for this kinda setting, it feels intuitive to look there to see if volume steps can be changed.

**Comment by ByteEnable** [comment]
I was planning on writing the same feature request.  5% is too big for my sound bar as well.  More granularity would be much appreciated.

**Comment by Butterfly1984** [comment]
> I don't understand why they rejected this.. apparently configuration is a burden for the user now?
Let's hope they took notice and are thinking about implementing it. I'm sure I'm not the only one (as 2 people kinda wanted to request the same thing it seems according to this post and a few others according to issue #8884). And there's probably 100's of people who don't even take the time to get on github to suggest such feature requests but would be quite happy if this was implemented into Mint.

**Comment by ssmid** [comment]
Feature was rejected in #8884, so this issue could probably be closed?

**Comment by mankinskin** [comment]
There is still active discussion about why to reject a requested feature like this. If you don't care about people using your software then I guess it is fine to close it.

**Comment by ssmid** [comment]
I'm not part of the Linux Mint team, just working on another PR related to sound. To me it looked like the decision has already been made and then there wouldn't be a reason to leave this issue open.

**Comment by kimimaru4000** [comment]
I think it's okay to keep this issue open. I see it as an additional request for this feature, which is in demand based on the activity around it. The PR was rejected over 2 years ago, and I believe there's still room for discussion. I would personally like to hear from the maintainers on what they think about it now.

**Comment by mat-m** [comment]
@clefebvre Going back to your discussion  in #8884, Increment of 5% is too big on my side. Having a bluetooth headset with noise-canceling, each 5% is a big step in my ears, having almost no parasite sounds around. It is usually to counter-balance a high TV volume beside me or a non-normalized soundtrack.
Implementing it in cinnamon-settings let most users benefit from the 5% setup, but let power users tweak it if they feel to do so.
Reading some issues and forum threads talking about that (and given the ratio of speaking vs supporting), I find  the requests acceptable.

What are your views ?

**Comment by pwozniak89** [comment]
I use this tutorial to manually change volume step at every new cinnamon version.
https://behoston.github.io/pl/linux/tweaks/2021/07/09/cinnamon-volume.html

It's not very long but a GUI option would be a better solution !
Please consider our request...

**Comment by RetroButton** [comment]
+1 for adding an option in the UI to set the increments.
Think some choosable steps (e.g. 1%, 2%, 3%, 5%) would do it.

**Comment by Secret-chest** [comment]
> +1 for adding an option in the UI to set the increments.
> Think some choosable steps (e.g. 1%, 2%, 3%, 5%) would do it.

It shouldn't be preset. Let it be 1-10%. And 3% wouldn't work because 100 is not a multiple of 3.

**Comment by claudiux** [comment]
@Secret-chest 100% is magnetic. When the difference between the sound volume and 100% becomes less than 3%, the sound volume changes to 100%.

**Comment by Secret-chest** [comment]
> @Secret-chest 100% is magnetic. When the difference between the sound volume and 100% becomes less than 3%, the sound volume changes to 100%.

I know but it would still be weird.

**Comment by kimimaru4000** [comment]
I have since switched to a different distro and KDE Plasma. This is how they do it:

![KDE Plasma Volume Step](https://user-images.githubusercontent.com/1388037/224490639-98c62d2f-fedc-46e6-8a0c-f955e2e325a2.png)

Simple, clean, and no nonsense. It works fine with whatever value you put in there (capped from 1 - 100%). I hope one day Cinnamon will finally adopt this highly requested feature.

**Comment by Secret-chest** [comment]
Agree, it's really not bad UX since you aren't forced to change it.
