### ISSUE TITLE
Bogus error when pressing Ctrl+C on the Update Manager log

### ISSUE THREAD

**Issue by dandv** [linuxmint/cinnamon#9921]
```
 * Cinnamon version 4.8.6
 * Distribution - Mint 20.1 64 bit
 * Attach ~/.xsession-errors, or /var/log/syslog
 ```

[var-log-syslog.txt](https://github.com/linuxmint/cinnamon/files/5963799/var-log-syslog.txt)
**Steps to reproduce**
1. Install some updates that end up in failure
2. In the Changes applied window log, press Ctrl+A, Ctrl+C to copy that log, then notice the error

![image](https://user-images.githubusercontent.com/33569/107614436-64a73400-6bee-11eb-83db-99ac887860e8.png)

**Comment by leigh123linux** [comment]
File the issue at https://github.com/linuxmint/mintupdate/issues

**Comment by dandv** [comment]
Do you have permissions to move it to that repo using the GitHub feature?

I'm on my phone and can't even boot to login to GitHub now, after restoring
the snapshot f'ed up my install.

**Comment by leigh123linux** [comment]
> Do you have permissions to move it to that repo using the GitHub feature? I'm on my phone and can't even boot to login to GitHub now, after restoring the snapshot f'ed up my install.

@clefebvre   can you transfer it please?
