### ISSUE TITLE
Empty Warning and Disclaimer when trying to restore snapshot

### ISSUE THREAD

**Issue by dandv** [linuxmint/cinnamon#9922]
```
 * Cinnamon version 4.8.6
 * Distribution - Mint 20.1 64 bit
 * Attach ~/.xsession-errors, or /var/log/syslog
 ```
After a borked update, I tried to restore the snapshot I created an hour ago, and saw this:

![image](https://user-images.githubusercontent.com/33569/107616630-8b676980-6bf2-11eb-94af-900383d3a2d7.png)

It took a looong while (30+ seconds) for that window to get populated, and there was no spinner or progress indicator of any kind. I waited *accidentally* as I was typing this bug report, but otherwise I would've clicked Cancel.

**Comment by leigh123linux** [comment]
File the issue at https://github.com/linuxmint/linuxmint/issues

**Comment by dandv** [comment]
@leigh123linux: Yes, I filed in the wrong repo. I apologize.

May I also suggest a far nicer way of handling mis-filed repos than what feels like barking instructions at a person who took some of their time to report an issue, but screwed up and filed it in the wrong repo?

As a member of the [Mint org](https://github.com/linuxmint), I believe you can use GitHub's feature to [transfer the issue to another repo](https://docs.github.com/en/github/managing-your-work-on-github/transferring-an-issue-to-another-repository). This might even take less of your time than admonishing the issue submitter to file it themselves.

But I do agree that it helps to teach people where to file issues, so something like this would be much nicer:

> Thanks for filing this issue. I've moved it to [correct repo] for you, please file issues related to XXX there from now on.

**Comment by NikoKrause** [comment]
Sorry to bother, but that seems like a timeshift issue. The right repo would be:

https://github.com/teejee2008/timeshift

**Comment by dandv** [comment]
@NikoKrause: no bother at all. It illustrates my point that casual users may not always know where the best place to file an issue is, and if it's not too much to ask of maintainers, the maintainers know better and are likely to have access to transfer issues between GitHub repos.
