### ISSUE TITLE
[Network Manager (network@cinnamon.org)] can not tell by looking at icon if connected to the internet

### ISSUE THREAD

**Issue by Bilal-Z** [linuxmint/cinnamon#9927]
Mint 19.3
 Cinnamon 4.4.8

**Issue**
There is a gulf of evaluation in the network manager applet. users can not be certain if they are connected to the internet by just looking at the applet icon. The user only finds out their network status after, for example, a webpage fails to load. If the user is informed of the network status through an icon change of the network manager applet, they can take corrective measures sooner.

**Steps to reproduce**
connected to network, network has no internet access but icon remains the same.

**Expected behaviour**

for example in windows this is the icon when connected to the internet

![](https://www.covenanteyes.com/lemonade/wp-content/uploads/2019/05/wifi.png)

and this is the icon when the user is not connected to the internet

![](https://www.covenanteyes.com/lemonade/wp-content/uploads/2019/05/no-internet.png)

**Comment by icarter09** [comment]
Cinnamon 4.8.6
Mint 20.1 64bit

I'm not able to reproduce this issue. @Bilal-Z are you not seeing a different icon when not connected?

**Comment by Bilal-Z** [comment]
> Cinnamon 4.8.6
> Mint 20.1 64bit
> 
> I'm not able to reproduce this issue. @Bilal-Z are you not seeing a different icon when not connected?

When not connected to a network, yes, I do see a different icon. I would like to propose that connected but no internet should have a different icon to inform the user that even though they are connected to their network the network does not have internet access. this feature is present on windows and android devices.

**Comment by ItzSwirlz** [comment]
Does it depend on the icon theme being used?

**Comment by ItzSwirlz** [comment]
Not sure, but this HighContrast icon seems good, so if I can find the correct logo for it I can implement it
![network-cellular-offline](https://user-images.githubusercontent.com/24401303/109989430-7a33e900-7cd6-11eb-8117-f25a7a9e022f.png)

**Comment by mtwebster** [comment]
@Bilal-Z:  I assume you mean the 'limited connectivity' indicator.

I think our api can now distinguish between 'connected to the local network' and 'connected to the network *and* have internet access, I'll see what we can do.

**Comment by mtwebster** [comment]
There are already some icons that are probably intended for this:
![image](https://user-images.githubusercontent.com/262776/110002594-8a9e9080-7ce3-11eb-820f-7a7abb816cd3.png)

I don't like them personally (the ! emblem sign like windows uses is more appropriate I think) but we can improve them in our own themes.

**Comment by mtwebster** [comment]
Hi, I did a pull request to address this - if you'd like to test you can download the modified file:

```
wget https://raw.githubusercontent.com/mtwebster/Cinnamon/network-applet-limited/files/usr/share/cinnamon/applets/network%40cinnamon.org/applet.js
sudo cp applet.js /usr/share/cinnamon/applets/network@cinnamon.org
```
Then restart cinnamon (alt-f2, r, enter)

It seems to work ok for me, but I'd like a couple more test cases before I commit it.

Thanks

**Comment by Bilal-Z** [comment]
thank you @mtwebster that's exactly what I mean. I'll test it and get back to you.

**Comment by Bilal-Z** [comment]
@mtwebster It does not work for me. To test I removed the internet cable from my router while the power cable was still connected to the wall. I use ubuntu-mono-dark icons but I also checked with Mint-Y and Adawaita that seem to have the network-wireless-no-route and It still didn't work.

**Comment by mtwebster** [comment]
Can you try disabling and re-enabling networking when you do that - I wonder if it's a matter of it's simply not updating the status in a reasonable amount of time, or the change isn't being detected at all.

**Comment by mtwebster** [comment]
It definitely seems like it's not updating, I'll see what I need to fix and update the PR.

**Comment by mtwebster** [comment]
I've added a bit more to the PR, it will update now. Unfortunately, with the way connectivity is checked, it can take some time to go from good connection -> bad, though it's fairly quick when the connection is restored. There's a bug in the network-manager library that is making this worse than it would ordinarily be but that's out of our hands for now.
