### ISSUE TITLE
Wireshark app theme does not follow the Mint theme

### ISSUE THREAD

**Issue by ByteEnable** [linuxmint/cinnamon#9929]
```
- Cinnamon 4.8.6
- no daily builds
- Fedora 33
- NVidia GTX1060 - 460.39
- Linux 5.10.14-200.fc33.x86_64
````

**Issue**
Wireshark does not follow the Mint theme.  Defaults to basic white QT theme.

**Steps to reproduce**
Install wireshark.  Run wirehark.

**Expected behaviour**
For wireshark to follow cinnamon desktop theme.

**Other information**

**Configuration info, if applicable**
If this bug report is related to an Applet, Desklet or Extension, please paste (or use a pastebin service) the offending extension's settings, if it has any.  You can obtain this by opening its configuration, clicking the 'hamburger' button in the upper-right corner of the window, and selecting "Export to a file". **Please be sure to review the contents and remove any personal data it may contain.**

```

Please paste here

```

**Comment by leigh123linux** [comment]
Is qgnomeplatform package installed?

**Comment by ByteEnable** [comment]
qgnomeplatform is not installed.  I installed the package and the colors appear to match the theme.

I also installed qt5ct and set the colors there and then launched as follows:
wireshark --platformtheme qt5ct

Thanks for the quick response.  Maybe this is a Fedora Spin packaging issue and I should follow up there?

**Comment by ItzSwirlz** [comment]
No; it's that the Mint themes aren't *really* meant for Qt, it's more Gtk based.. While it could go to Fedora, it may impact other distros. Maybe flag it under mint-y-themes or mint-x-themes?

**Comment by JosephMcc** [comment]
Glad you have this solved. As far as I can see this isn't really a Cinnamon issue.

>  Maybe flag it under mint-y-themes or mint-x-themes?

No reason for that. Those have nothing to do with qt theming.

Would also like to point out this isn't an issue in Mint by default.

**Comment by ByteEnable** [comment]
> Glad you have this solved. As far as I can see this isn't really a Cinnamon issue.
> No reason for that. Those have nothing to do with qt theming.
> Would also like to point out this isn't an issue in Mint by default.

Your claiming that Cinnamon is not a desktop environment but merely an application?  Surely Cinnamon should be providing mechanisms that provide a consistent desktop interface across the application ecosystem?

**Comment by leigh123linux** [comment]
@ByteEnable  qgnomeplatform provides the qt5 integration for gtk theming.

**Comment by ByteEnable** [comment]
> @ByteEnable qgnomeplatform provides the qt5 integration for gtk theming.

Ah.  Okay.  Cinnamon is an application running under GNOME.  Thanks for the clarification.

**Comment by JosephMcc** [comment]
> Your claiming that Cinnamon is not a desktop environment but merely an application?

Weird. I don't seem to remember saying that. Some things are handled at a distro level and left for the distro maintainers to decide.
