### ISSUE TITLE
Was playing minecraft and this happened. I can't click on any of the icons

### ISSUE THREAD

**Issue by kahveciderin** [linuxmint/cinnamon#9937]
```
 * Cinnamon version (cinnamon --version)
Cinnamon 4.8.5
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
 Mint 20.1
 * Graphics hardware *and* driver used
 RTX3070 - nvidia-driver-460
 * 64 bit
 * Attach ~/.xsession-errors
[xsessionerrors.txt](https://github.com/linuxmint/cinnamon/files/5996531/xsessionerrors.txt)

 ```

**Issue**

I don't know how, I don't know why. This happened while playing Minecraft, which is an OpenGL game. Can't click on any of the icons.
![Screenshot from 2021-02-17 18-01-49](https://user-images.githubusercontent.com/17106844/108223350-c74a8380-714a-11eb-8fdd-1c2e29364697.png)

**Steps to reproduce**
I genuinely have no idea. Play Minecraft, I guess?

**Expected behaviour**
Definitely not this to happen

**Other information**

**Configuration info, if applicable**
If this bug report is related to an Applet, Desklet or Extension, please paste (or use a pastebin service) the offending extension's settings, if it has any.  You can obtain this by opening its configuration, clicking the 'hamburger' button in the upper-right corner of the window, and selecting "Export to a file". **Please be sure to review the contents and remove any personal data it may contain.**

```

none

```

**Comment by collinss** [comment]
Looks like you accidentally entered panel edit mode. Right click an empty area of the panel, and then click "Panel edit mode". That should make the icons responsive again.

**Comment by kahveciderin** [comment]
@collinss ive though about this too, but right clicking didn't work, the panel was unresponsive

**Comment by collinss** [comment]
Does ctrl+alt+escape fix it?
