### ISSUE TITLE
Optionally auto-update Spices

### ISSUE THREAD

**Issue by Lurux** [linuxmint/cinnamon#9941]
Hi,

I think it would be nice if we had the option, maybe in the general settings, to update spices automatically. I use a few external applets on my panel, and I would prefer to have them auto-update rather than having to check manually :smile:

Alternatively, maybe a central place to see all Spices updates with an "update all" button would do the trick ? This would prevent people from having to check different places if they have, ie, external applets *and* desklets installed.

**Comment by NikoKrause** [comment]
This has been a feature, which has been discussed a few times in the past. In the long run it's planned to have something like that.

For the time being, there is an applet, which notifies about updates and also has some other features:
https://cinnamon-spices.linuxmint.com/applets/view/309

**Comment by Lurux** [comment]
Hi @NikoKrause, sorry for the duplicate. I tried searching before posting this, maybe I didn't go far enough :thinking:

I have heard of this applet indeed; however, it can't perform auto-updates, as far as I'm aware. Am I mistaken ? Also, ideally I don't want to charge Cinnamon with too many applets as to not slow it down :smile:

**Comment by NikoKrause** [comment]
As far as I know, it does not perform autoupdates.
Your feature request is reasonable.

The mentioned applet is (as of now) just the best existing solution i'm aware of.

**Comment by Lurux** [comment]
Ok, I understand. I haven't tried it yet, but it seems like the applet can update spices by clicking a button in the notification. I'll take a look into it.

**Comment by ItzSwirlz** [comment]
Doesn't the new commit with harvester do this?

**Comment by NikoKrause** [comment]
The new blog posts will probably remove any doubts in your heads:
https://blog.linuxmint.com/?p=4054

![Updates](https://www.linuxmint.com/tmp/blog/4054/thumb_automation.png)

**Comment by Lurux** [comment]
Yahoo !
