### ISSUE TITLE
Some Web Apps start too small to use

### ISSUE THREAD

**Issue by svidovich** [linuxmint/cinnamon#9946]
```
 * Cinnamon version (cinnamon --version) - Cinnamon 4.8.6
 * Distribution - Linux Mint 20.1_x86_64
 * Graphics hardware *and* driver used - NVIDIA GeForce GT 1030 w/ nvidia-driver-460
 * Attach ~/.xsession-errors, or /var/log/syslog
 ```

**Issue**
![image](https://user-images.githubusercontent.com/16866899/108605594-fb0fee00-7382-11eb-8763-850d7b8b92a9.png)

Sometimes, a webapp will start too small to use!

**Steps to reproduce**

Open any of your saved webapps.

**Expected behaviour**

I expect the webapp to be at least a size that is usable, but it is too small.

**Other information**

![image](https://user-images.githubusercontent.com/16866899/108605609-2a265f80-7383-11eb-8945-350cf06d692c.png)

Web Apps version 1.1.1

**Comment by icarter09** [comment]
I've tried out a few saved web apps, but haven't been able to reproduce the issue. Which browser are you using to load up the web apps? Do you happen to have a web app or two that will usually reproduce the issue? Thanks.

**Comment by svidovich** [comment]
@icarter09 Hi! I use chrome for web apps. Occasionally, discord and google messages will start in this way. Here's my chrome version:
![image](https://user-images.githubusercontent.com/16866899/119150690-ac72fe00-ba1c-11eb-890e-4f8f389e53d9.png)

**Comment by icarter09** [comment]
Thanks for the info. I'll try test it out with Discord and Slack using both Chrome and Brave (my default browser). Verified that I do have the same version of Chrome.

**Comment by svidovich** [comment]
Awesome!
