### ISSUE TITLE
Incorrect icons on panel for some running flatpak applications

### ISSUE THREAD

**Issue by letuxmasque** [linuxmint/cinnamon#9951]
```
 * Cinnamon version 4.8.6
 * Distribution - Linux Mint 20.1 Cinnamon, LMDE 4
 ```

**Issue**
Icons are incorrect on panels for running LibreOffice and Calibre flatpak applications.
With LibreOffice, on Linux Mint 20.1, the icon is the one for LibreOffice Impress and not this for LibreOffice Writter and on LMDE 4, the icon is this for LibreOffice and not this for LibreOffice Writter.
With Calibre, the icon is the one for Calibre Viewer, not for Calibre.
And when you are running by exemple LibreOffice Writter and LibreOffice Calc, both are grouped together in the same icon on the panel. Same behaviour with Calibre and Calibre Viewer.

Examples:
- with Linux Mint 20.1 and LibreOffice Writter flatpak application:

![linux mint 20 1 - flatpak lo writter](https://user-images.githubusercontent.com/36480615/108850598-d4042700-75e3-11eb-9aa7-4290d1dc6b35.png)

- with Linux Mint 20.1 and LibreOffice Calc & LibreOffice Writter flatpak applications:

![linux mint 20 1 - flatpak lo calc   writter](https://user-images.githubusercontent.com/36480615/108850757-feee7b00-75e3-11eb-9b4d-dfd7773fe58c.png)

- with Linux Mint 20.1 and Calibre & Calibre Viewer flatpak applications:

![linux mint 20 1 - flatpak calibre](https://user-images.githubusercontent.com/36480615/108850858-19c0ef80-75e4-11eb-86a7-8ce7654bca84.png)

- with LMDE 4 and LibreOffice flatpak applications:

![lmde 4 - flatpak lo calc   writter](https://user-images.githubusercontent.com/36480615/108850959-36f5be00-75e4-11eb-8567-6962ccde8c7e.png)

**Steps to reproduce**
Install LibreOffice from the flathub
Run LibreOffice Writter
Look at the icon on the panel

or install Calibre from the flathub
run Calibre
Look at the icon on the panel

**Expected behaviour**
Examples:
- with Linux Mint 20 Cinnamon and LibreOffice Calc & Writter flatpak applications:

![linux mint 20 - flatpak libreoffice](https://user-images.githubusercontent.com/36480615/108851274-8a680c00-75e4-11eb-8df6-72cd54cbb63d.png)

- with Linux Mint 20 Cinnamon and Calibre & Calibre Viewer flatpak applications:

![linux mint 20 - flatpak calibre](https://user-images.githubusercontent.com/36480615/108851337-9a7feb80-75e4-11eb-905c-b39f1b9810dd.png)

**Comment by NerdsMaxx** [comment]
I have this same problem.

**Comment by heroldn** [comment]
Ditto, please fix this as soon as reasonable. Very annoying especially when combined with the[ window re-ordering bug](https://github.com/linuxmint/cinnamon/issues/9802)!
