### ISSUE TITLE
Black bar when firefox is maximised and title bar is not used.

### ISSUE THREAD

**Issue by vrihaspati110** [linuxmint/cinnamon#9970]
```
 * Cinnamon version - 4.8.6
   
 * Distribution - Manjaro 20.2.1 Nibia
 * Graphic Card - Nvidia 1650s
 * Driver Version - 460.39
 * 64 bit
 
 ```

**Issue**

Black bar when firefox is maximised and title bar is not used. Does not happen in any other browser or apps. Does not happen on any other distro. (Other Browser: Chromium and edge, Other Distro: Manjaro Kde 20.2.1 Nibia

**Steps to reproduce**

Open firefox, Go to customize and remove Titlebar, maximize firefox and there will be a black bar just where the title bar used to be.

**Expected behaviour**

Firefox should use all the real state.

**Other information**
OS: Manjaro 20.2.1 Nibia
Kernel: x86_64 Linux 5.11.1-1-MANJARO
Uptime: 12h 13m
Packages: 1358
Shell: zsh 5.8
Resolution: 1920x1080
DE: Cinnamon 4.8.6
WM: Muffin
WM Theme: Mint-Y-Dark-Teal (Mint-Y-Dark-Teal)
GTK Theme: Mint-Y-Dark-Teal [GTK2/3]
Icon Theme: Papirus-Adapta-Nokto-Maia
Font: Fira Sans 11
Disk: 750G / 1.2T (66%)
CPU: Intel Core i3-9100F @ 4x 4.2GHz [38.0°C]
GPU: GeForce GTX 1650 SUPER
RAM: 6330MiB / 15956MiB

```

Please paste here
![image](https://user-images.githubusercontent.com/67848084/110152905-57a1ed00-7e08-11eb-8c3d-ad73e0868ecc.png)

```

**Comment by mtwebster** [comment]
I can't reproduce this. Do you have any third-party cinnamon extensions/applets running?

**Comment by vrihaspati110** [comment]
> I can't reproduce this. Do you have any third-party cinnamon extensions/applets running?

Apart from all the extensions that came with my os I am using a weather and a sticky note desklet and a download and upload speed applet, But the issue was present even after uninstalling them. I've also refreshed and reinstalled firefox too.

**Comment by mtwebster** [comment]
What version of firefox?  And, can you check with a new firefox profile (I doubt this matters but I'd like to be sure) - you can back up ~/.mozilla or make a new user and try there.

Can you provide your cinnamon settings?
```
dconf dump /org/cinnamon/ > dump
```
(there shouldn't really be personal data there but it's text format so you can check)

**Comment by vrihaspati110** [comment]
> What version of firefox

I am using firefox 86.



> Can you provide your cinnamon settings?

https://pastebin.com/81r1t1rp

**Comment by mtwebster** [comment]
Hmm that link doesn't work.

**Comment by vrihaspati110** [comment]
> Hmm that link doesn't work.

Sorry about that!!! And sorry for late reply I went to sleep.
Here...

[/]
alttab-switcher-delay=100
applet-cache-updated=1614719655
command-history=['chromium', 'firefox', 'lutris', 'lut', 'r']
desklet-cache-updated=1614702574
desklet-decorations=0
desklet-snap-interval=25
enabled-applets=['panel1:left:0:menu@cinnamon.org:0', 'panel1:left:1:separator@cinnamon.org:1', 'panel1:left:2:expo@cinnamon.org:2', 'panel1:left:4:separator@cinnamon.org:4', 'panel1:left:5:grouped-window-list@cinnamon.org:5', 'panel1:right:1:notifications@cinnamon.org:6', 'panel1:right:2:workspace-switcher@cinnamon.org:7', 'panel1:right:3:windows-quick-list@cinnamon.org:8', 'panel1:right:4:separator@cinnamon.org:9', 'panel1:right:5:systray@cinnamon.org:10', 'panel1:right:6:separator@cinnamon.org:11', 'panel1:right:8:network@cinnamon.org:13', 'panel1:right:9:sound@cinnamon.org:14', 'panel1:right:10:power@cinnamon.org:15', 'panel1:right:11:inhibit@cinnamon.org:16', 'panel1:right:12:calendar@cinnamon.org:17', 'panel1:right:13:user@cinnamon.org:18', 'panel1:right:0:download-and-upload-speed@cardsurf:19']
enabled-desklets=['simple-system-monitor@ariel:0:1725:0', 'notes@schorschii:1:25:25']
favorite-apps=['firefox.desktop', 'cinnamon-settings.desktop', 'org.gnome.Terminal.desktop', 'nemo.desktop', 'org.manjaro.pamac.manager.desktop']
next-applet-id=20
next-desklet-id=3
panel-zone-symbolic-icon-sizes='[{"panelId": 1, "left": 28, "center": 28, "right": 16}]'
panels-autohide=['1:intel']
panels-height=['1:40']

[desktop/a11y/applications]
screen-keyboard-enabled=false
screen-reader-enabled=false

[desktop/a11y/mouse]
dwell-click-enabled=false
dwell-threshold=10
dwell-time=1.2
secondary-click-enabled=false
secondary-click-time=1.2

[desktop/background]
picture-options='stretched'
picture-uri='file:///home/vrihaspati/Downloads/wallpapers/jakub-kozlowski-final-towers-as.jpg'

[desktop/background/slideshow]
delay=15
image-source='directory:///home/vrihaspati/Downloads/wallpapers'

[desktop/interface]
clock-show-date=false
clock-show-seconds=false
clock-use-24h=true
cursor-blink-time=1200
cursor-size=24
font-name='Fira Sans 11'
scaling-factor=uint32 0
text-scaling-factor=1.0
toolkit-accessibility=false

[desktop/keybindings]
custom-list=['__dummy__', 'custom0']

[desktop/keybindings/custom-keybindings/custom0]
binding=['<Primary><Shift>Escape']
command='gnome-system-monitor'
name='System Monitor'

[desktop/sound]
event-sounds=false

[desktop/wm/preferences]
min-window-opacity=30
mouse-button-modifier='<Super>'
titlebar-font='Fira Sans Medium 10'

[muffin]
resize-threshold=24
workspace-cycle=true

[settings-daemon/peripherals/keyboard]
delay=uint32 500
numlock-state='on'
repeat-interval=uint32 30

[settings-daemon/peripherals/mouse]
custom-acceleration=true
custom-threshold=true
double-click=400
drag-threshold=8
middle-button-enabled=false
motion-threshold=10

[settings-daemon/peripherals/touchpad]
motion-threshold=1

[settings-daemon/plugins/power]
sleep-display-ac=0

[settings-daemon/plugins/xsettings]
hinting='full'
rgba-order='rgba'

**Comment by leigh123linux** [comment]
The issue doesn't reproduce here.

```
$ inxi -S
System:    Host: mpd.lan Kernel: 5.10.19-200.fc33.x86_64 x86_64 bits: 64 Desktop: Cinnamon 4.8.6 
           Distro: Fedora release 33 (Thirty Three)
```

```
$ firefox -v
Mozilla Firefox 86.0
```

**Comment by vrihaspati110** [comment]
Okay Guys, Looks like I've solved it for now. After changing Desktop themes back and forth a few times the issue resolved itself.
