### ISSUE TITLE
Close window button on Disks utility partially hidden.

### ISSUE THREAD

**Issue by valvelifter1951** [linuxmint/cinnamon#9979]
```
 * Cinnamon version (cinnamon --version) Cinnamon 4.6.7
   - Please specify if you are using the daily builds PPA NO
     (https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds).
 * Distribution - Linux Mint 20 Cinnamon
 * Graphics hardware *and* driver used Various, happens on three different machines
 64 bit
 * Attach ~/.xsession-errors, or /var/log/syslog
 ```

**Issue**
The close window button on the Disks utility is partially hidden. This is unique to this program. I have tested on 3 different machines with identical results. Also tested on a machine running Ubuntu 14.04 and it does NOT happen on Ubuntu. I have the window buttons layout set to the left hand side. This  issue does NOT happen with the buttons set to the right hand side.

**Steps to reproduce**
Launch the Disks utility

**Expected behaviour**
Being able to see the close window button

**Other information**

**Configuration info, if applicable**
If this bug report is related to an Applet, Desklet or Extension, please paste (or use a pastebin service) the offending extension's settings, if it has any.  You can obtain this by opening its configuration, clicking the 'hamburger' button in the upper-right corner of the window, and selecting "Export to a file". **Please be sure to review the contents and remove any personal data it may contain.**
No "export to file" option is shown

```

Please paste here

```

**Comment by leigh123linux** [comment]
Feel free to reopen if you can reproduce it on cinnamon-4.8.x
