### ISSUE TITLE
Desktop icons with big text in the label touch each other

### ISSUE THREAD

**Issue by Everest10** [linuxmint/cinnamon#9986]
![111253339-ca258080-85f1-11eb-8377-e146b74bd35f](https://user-images.githubusercontent.com/7228207/111311772-5f019b80-863d-11eb-80f4-7f35f7d05b9f.png)

* Cinnamon version : 4.8.6
* Please specify if you are using the daily builds PPA: None
* Distribution - Fedora 33
* Graphics hardware : Radeon RX 580
* 64 bit
* Attach ~/.xsession-errors, or /var/log/syslog: None

**Issue**

When create desktop icons with big text in the the labels and move files and folders with big text in the the labels and place them all side by side on the desktop the labels touch each other and the best configuration to not touch leaves an unpleasant space on the left side of the screen, the icons are not properly close to the edge of the screen when the user configure a good space to the labels do not touch each other.

Screenshot: [https://imgur.com/xqzcOhU](url)

**Steps to reproduce**

Create desktop icons with big text in the the labels and move files and folders with big text in the the labels and place them all side by side on the desktop. Adjusting the icons so that the labels do not touch each other, leaves an unpleasant space on the left side of the screen, the icons are not properly close to the edge of the screen.

**Expected behaviour**

Create desktop icons with big text in the the labels and move files and folders with big text in the the labels and place them all side by side on the desktop adjusting the icons to not touch each other shortening the text with three dots, and leaves an properly space on the left side of the screen.

**Other information**

None.

**Configuration info, if applicable**

In the screenshot.
![111253339-ca258080-85f1-11eb-8377-e146b74bd35f](https://user-images.githubusercontent.com/7228207/111311818-69239a00-863d-11eb-9d41-afa1f6e1248f.png)

**Comment by leigh123linux** [comment]
Closed, see https://github.com/linuxmint/nemo/issues/2700
Nemo draws the desktop not cinnamon!

**Comment by Everest10** [comment]
Ok ! Never mind !
