### ISSUE TITLE
Cinnamon accidentally launches desktop entries in other DEs

### ISSUE THREAD

**Issue by guicho271828** [linuxmint/cinnamon#9990]
```
 * Cinnamon version (cinnamon --version)
   * Cinnamon 4.6.7
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
   * Fedora 32
 * Graphics hardware *and* driver used
   * nVidia proprietary driver, Driver Version: 460.56
 * 64 bit
 * Attach ~/.xsession-errors, or /var/log/syslog
   * N/A
 ```

**Issue**

After installing kde-desktop-environment (i.e. plasma) through `dnf`, a bunch of KDE-specific autostart script also launches in the cinnamon DE. `$XDG_CURRENT_DESKTOP` is X-Cinnamon.

Among many things, it launches this file
https://github.com/KDE/kglobalaccel/blob/master/src/runtime/kglobalaccel.desktop
which grabs many keyboard shortcuts from cinnamon (e.g. screenshot (Shift+Print)) and remaps them to KDE software.
The file is in /usr/share/kservices5/kglobalaccel5.desktop .

**Steps to reproduce**

Run `dnf install @kde-desktop-environment`, log out, then log in to cinnamon DE.

```
$ pgrep kglobalaccel
120502
$ echo $?
0
```

**Expected behaviour**

```
$ pgrep kglobalaccel
$ echo $?
1
```

**Comment by leigh123linux** [comment]
File the issue against the kde programs, they will need to fix it, they need to add this to their desktop files.

OnlyShowIn=kDE;

Or you could disable them in cinnamon-settings / Startup Applications

**Comment by guicho271828** [comment]
to be honest, I believe the sane default behavior for startup files is to run only those marked by X-Cinnamon.
The sad state of desktop file entry specification, I guess.

**Comment by leigh123linux** [comment]
It's sad that KDE abuses the desktop file entry specification.
