### ISSUE TITLE
nemo-desktop cannot be run as root

### ISSUE THREAD

**Issue by Scorpion2185** [linuxmint/cinnamon#9994]
```
 * Cinnamon version: Cinnamon 3.8.8
   - Please specify if you are using the daily builds PPA
     (https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds): No
 * Distribution - Debian 10
 * Nvidia GeForce GTX with nvidia-driver 
 * 64 bit
 ```

**Issue**

I can' t use `nemo-desktop` as root.
The file is in `/usr/bin/nemo-desktop`.

**Steps to reproduce**

Log in as root `nemo-desktop` doesn' t work, you don' t have desktop icons.<br>
If I try to launch it:
```
# nemo-desktop
nemo-desktop cannot be run as root, please try again as a normal user
```

**Expected behaviour**

To be able to run it also as root.

**Comment by leigh123linux** [comment]
Don't run it as root as we don't intend to support poor root usage.

**Comment by Scorpion2185** [comment]
I tried to check the file with an hex editor, can you tell me how to fix this?

**Comment by leigh123linux** [comment]
Try removing this check section.

https://github.com/linuxmint/nemo/blob/9db77416478b762f318d7a194f56052a14a65a04/src/nemo-desktop-application.c#L298

**Comment by Scorpion2185** [comment]
I have run `git clone https://github.com/linuxmint/nemo.git`.

If I try to compile it:
```
gcc nemo-desktop-application.c -o nemo-desktop-root
nemo-desktop-application.c:29:10: fatal error: config.h: No such file or directory
 #include <config.h>
          ^~~~~~~~~~
compilation terminated.
```

Is this command right? How do I generate the missing file/files?

**Comment by NikoKrause** [comment]
Try
```
dpkg-buildpackage
```

**Comment by Scorpion2185** [comment]
I used `apt source nemo` and with `dpkg-buildpackage -b -uc -us` I built the package.

I extracted `nemo-desktop` and I copied it in `/usr/bin/nemo-desktop`.

Now I can use it as root.

Could you remove the check section? 
On Kali Linux for example by default there is only root, no normal users.

**Comment by Scorpion2185** [comment]
I used `apt source nemo` and with `dpkg-buildpackage -b -uc -us` I built the package.

I extracted `nemo-desktop` and I copied it in `/usr/bin/`.

Now I can use it as root.

Could you remove the check section? 
On Kali Linux for example by default there is only root, no normal users.

**Comment by mtwebster** [comment]
Improved solution:
https://github.com/linuxmint/nemo/commit/1b38f7614251730088f751d4913c1fd270dd1715

**Comment by Scorpion2185** [comment]
Since what version of nemo is that option added?

**Comment by mtwebster** [comment]
It's in nemo 5
```
man nemo
...
...
NOTE ON THE ROOT USER
       Ordinarily, nemo and nemo-desktop treat being run as the root user as special, with certain restrictions and UI changes. This behavior can be bypassed via a gsettings key.
       You can use the following command to enable/disable this override:

       gsettings set org.nemo.preferences treat-root-as-normal true|false
...
```
