### ISSUE TITLE
Graphical error rectangles (artefacts) after sleep/suspend

### ISSUE THREAD

**Issue by jmssil** [linuxmint/cinnamon#9996]
```
Cinnamon 4.8.6
Not using the daily builds PPA.
Linux Mint 20.1 Ulyssa
NVIDIA Corporation G98 [Quadro NVS 295]
nvidia-340
 ```

**Issue**

After suspend/sleep some applications show "damaged" rectangles like the one I attach. These applications are Spotify and Signal. They probably have something in common.

It is possible "clear" the damaged  rectangles in some cases by moving the mouse pointer over them, so that they are redrawn.

**Steps to reproduce**

Use Spotify and/or Signal and suspend/sleep the computer.

**Expected behaviour**

Normal rendering of the applications.

**Comment by jmssil** [comment]
![Screenshot from 2021-03-21 22-29-58](https://user-images.githubusercontent.com/7854469/111923325-8bcb0e00-8a96-11eb-8d6b-462dec94e982.png)

**Comment by jmssil** [comment]
[xsession-errors.txt](https://github.com/linuxmint/cinnamon/files/6178525/xsession-errors.txt)

**Comment by leigh123linux** [comment]
You have a video driver issue, please report it upstream.

**Comment by jmssil** [comment]
@leigh123linux, can you help me understand what "upstream" is? Where should I file this bug? Thanks.

**Comment by leigh123linux** [comment]
Upstream = Nvidia for nvidia-340, but it's a legacy driver so wont be fixed.
Try removing it and using the open source nouveau driver instead.
